### ISSUE TITLE
Push recordings to Youtube.

### ISSUE THREAD

**Issue by amohideen** [bigbluebutton/bigbluebutton#10006]
Hi, I have deployed my instance of BBB. A huge Thanks to all its supporters and it is a great tool. 
I would like to propose a module (feature) to automatically push recording to Youtube (to a subscriber channel)

I hope this feature will add more capability to BBB server.

Thanks.

**Comment by snadal** [comment]
Hello. This is being discussed in #8295.

**Comment by matiasilva** [comment]
I think that's slightly different. They want to upload a recording you YouTube. In any case, this is a task for the frontend you're using and not BigBlueButton itself. I'll close for now but if someone thinks this should be in BigBlueButton itself we can discuss.
