### ISSUE TITLE
Recording not listed

### ISSUE THREAD

**Issue by amohideen** [bigbluebutton/bigbluebutton#10005]
Hi, I have successfully deployed BBB server and coupled it with my Moodle instance using the plugin, everything works fine, except my recordings (recording works fine) are not being listed in the moodle sessions. I am sure this is indeed a configuration issue, but still, I am struggling to get it working. What setting am I missing?

I will greatly appreciate your help. 

In the attached screenshot of settings of BBB session in Moodle, it has no settings fo recording either. 
![bbb](https://user-images.githubusercontent.com/16897993/86837599-084bc700-c097-11ea-9cef-d164891e756a.png)

**Comment by amohideen** [comment]
This is now OK It was a moodle issue.

**Comment by ffdixon** [comment]
Can you share any details in case others encounter the same issue.
