### ISSUE TITLE
Private chat problem in 2.3

### ISSUE THREAD

**Issue by jfsiebel** [bigbluebutton/bigbluebutton#10002]
**Describe the bug**
When you switch between private chats the previous chat content is show in the current open private chat. Also there is a delay is some case when switching between chats.

**To Reproduce**

1. Join with 3 users (AAA, BBB, CCC)
2. AAA send a private message to BBB
3. CCC send a private message to AAA
4. Change the current private chat

![pvt_chat](https://user-images.githubusercontent.com/2110278/86820404-5fce4080-c05f-11ea-8408-e8c20ab1a551.gif)
![delay_change](https://user-images.githubusercontent.com/2110278/86819690-6314fc80-c05e-11ea-8028-908db38b2820.gif)

**Comment by agussang** [comment]
Bro, can you help me
how to install bbb from release? are u first using bbb install?

**Comment by ffdixon** [comment]
We are currently developing BigBlueButton 2.3 and we'll be announcing to bigbluebutton-dev when we have an early build that you can install.

**Comment by amohideen** [comment]
Where is html5client directory? on a V2.2 installation.

**Comment by matiasilva** [comment]
Hi guys, please don't hijack other issues to ask questions. If you need help, use https://docs.bigbluebutton.org/2.2/getting-help.html
