### ISSUE TITLE
Install From Release

### ISSUE THREAD

**Issue by agussang** [bigbluebutton/bigbluebutton#10001]
**Describe the bug**
Hello, any full guides to install bbb from release version
i want install https://github.com/bigbluebutton/bigbluebutton/archive/v2.2.19.zip

Thanks You

**Installation type**
Did you install manually or did you use the bbb-install script?

**Firewall and IP address type**
Is your server behind a NAT or firewall? Does your BBB server have its own IPv4 addres?

**Console output**
Please include the full console output from the install.

**Additional context**

**Comment by matiasilva** [comment]
Yes! See https://docs.bigbluebutton.org/. Join the mailing lists if you want to ask for help.

**Comment by agussang** [comment]
yes i know, but if i use apt-get install bbb-html5 <== that's from new release? with tag 2.2.19?

**Comment by matiasilva** [comment]
Yeah, it should be if you follow the installation instructions on the website. Please use https://groups.google.com/forum/#!forum/bigbluebutton-setup for further questions.
