### ISSUE TITLE
Include join (& leave) time in participants export

### ISSUE THREAD

**Issue by keunes** [bigbluebutton/bigbluebutton#10009]
**Is your feature request related to a problem? Please describe.**
We would like to have a truthful account of how many people follow the webinars we organise. We currently can already export the list with participant names, which provides a number but is not always truthful: some participants may join multiple times because of tech issues, or might chip in briefly and then decide it's not for them.

**Describe the solution you'd like**
We would like to know when (and how long) people joined for a webinar, to get a better view of the true number of participants. To this end, it would be great if the current simple text export of the participant names, could be extended into a file (e.g. CSV) that also contains their join timestamp and maybe even their leave timestamp.
With both join & leave time, we can calculate the duration of their participation, and e.g. only count the users that stayed, say, for 85% of the webinar duration.

**Describe alternatives you've considered**
Can't think of anything at the moment.

**Additional context**
We've been testing out BBB for the webinars we provide to teachers. Participation numbers are expected by the project owners (European Commission), so not having reliable data might be a blocker for adopting BBB.

**Comment by matiasilva** [comment]
See events.xml in the recording or the HTML5 logs.

**Comment by keunes** [comment]
@matiasilva we tested BBB using the official demo. Is what you're talking about available from that interface somewhere?

**Comment by basisbit** [comment]
For support requests, please use the [forum / mailing list](https://groups.google.com/forum/#!forum/bigbluebutton-setup). This issue tracker here is only for BBB development related issues. Sorry.

**Comment by matiasilva** [comment]
@basisbit I think this could be an interesting feature, like a meeting report at the end, dunno.

**Comment by basisbit** [comment]
Well, the required data is already logged in a default setup, so it only needs to be analyzed and exported to your monitoring tool. Please keep in mind that this feature should be on/off configurable for service providers which are stricter on data privacy protection

**Comment by matiasilva** [comment]
Yeah, though for users who don't have log access it could be an issue as @keunes has mentioned. It'd be interesting to hear other thoughts on this.

**Comment by keunes** [comment]
> For support requests, please use the [forum / mailing list](https://groups.google.com/forum/#!forum/bigbluebutton-users). This issue tracker here is only for BBB development related issues. Sorry.

Ok, thanks, wasn't aware of the Google list. Note though that it was specifically not a support request. (Also wondering why there's a feature request template here if they weren't supposed to be submitted on GH.)

**Comment by amg-web** [comment]
> For support requests, please use the [forum / mailing list](https://groups.google.com/forum/#!forum/bigbluebutton-users). This issue tracker here is only for BBB development related issues. Sorry.

it's for development. it's not a user problem. A lot of moderators wants to know when user join and leave the meeting. is it so difficult to add this info to the existing user list download feature?

**Comment by iSamof** [comment]
Meeting stats were also discussed here: https://github.com/bigbluebutton/bigbluebutton/issues/9960

It may be helpful to keep all discussions in one place ... perhaps in #9960

**Comment by matiasilva** [comment]
Agreed, merging this one with  #9960
