### ISSUE TITLE
Error 1020 in kurento when using STUN. It works with externalAddress in WebRtcEndpoint.conf.ini

### ISSUE THREAD

**Issue by rescondio** [bigbluebutton/bigbluebutton#10000]
**Describe the bug**
I have this server in AWS. It has been working properly until today (no intentional changes in server conf in the last days). SSL configured, WebRTC audio, Webcam and screen sharing working perfectly.

Suddenly, since this morning I can join the conference and join audio channel, but when sharing webcam or sharing screen I get a 1020 error message.

Assuming this is a Kurento thing, I've checked `/etc/kurento/modules/kurento/WebRtcEndpoint.conf.ini`
I can confirm that the stun server and port at  "stunserveraddress" variable works (rtp | srflx at https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/)

Anyway, I changed to different stun servers just in case with no luck.

So, as a workaround, I enabled `externalAddress` with the server external IP address in `/etc/kurento/modules/kurento/WebRtcEndpoint.conf.ini `. Did worked and I can now enable webcam from my home to the AWS BBB server.

However, I am curious on how this stopped working. I'd like to be able to enable STUN / TURN server to maximize this server compatibility.

**To Reproduce**
1. Create a conference.
2. Join the conference as user or admin.
3. Join the SIP audio conference (OK)
4. Enable webcam.

**Expected behavior**
It should connect to webcam and start videoconference.

**Actual behavior**
After a few seconds, a 1020 error is returned.

**Screenshots**
![image](https://user-images.githubusercontent.com/67966661/86802271-2274ad80-c075-11ea-8d50-53a9bd2d7ad7.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome, Firefox
 - Version Chrome 83, Firefox 78

**Smartphone (please complete the following information):**
 - Device: iPhone XR
 - OS: iOS 13.3
 - Browser Safari
 - Version 13

**Additional context**
I don't think it's related but just in case and to be honest, the only change that I can remember is that in the last conference that I had some days ago, I went to settings (html5 web interface) and changed the "Enable webcams" and "Enable Desktop Sharing" switchs to OFF. 

Any clue?

**Comment by einst44** [comment]
check your stun server
https://docs.bigbluebutton.org/2.2/configure-firewall.html#updating-kurento
#apt-get install stun-client
#stun your_stun_server_ip_address:port

check if it is open

use google server if necessary

**Comment by matiasilva** [comment]
There was a recent change to the STUN server being used in bbb-install.sh. I'd say this is something for the forums guys: https://groups.google.com/forum/#!forum/bigbluebutton-setup

**Comment by rescondio** [comment]
Thank you @einst44 and  @matiasilva  

Can't believe it. Yes. by default, bbb-install.sh was using 64.233.177.127:19302 and switching to 172.217.212.127 fixes it. 
I swear I tried several other STUN servers, but obviously I was doing something wrong.

Anyway... good to know that I was not losing my mind 😆
