### ISSUE TITLE
Live streaming local audio/video

### ISSUE THREAD

**Issue by CPHM** [bigbluebutton/bigbluebutton#10004]
This is a feature request and not a bug report or support question!
I have deployed bbb for 4 schools and educational institutes(due to the pandemic) and I have been asked by each one of them for a local video/audio streaming feature and unfortunately I have to tell them all that this is not a feature that bbb has or even plans to have. I believe this feature is actually pretty important and is probably a common requirement for many people using bbb.
A few use cases for such a feature would be: audio tracks for listening exercises for a foreign language class, videos demonstrating some physical phenomena or even a powerpoint presentation turned into a video so that the animations can be displayed.
what is needed is a feature to allow streaming a video or audio from local storage alongside or even instead of webcam and mic stream.
I first thought that maybe this is a problem with the WebRTC protocol and that it doesn't support such a behavior but I found [this demo](https://webrtc.github.io/samples/src/content/capture/video-pc/) which would indicate otherwise.
I would like to know if such a feature can be considered for implementation and if not weather there is a way to make it work like the current stream from youtube option

**Comment by iSamof** [comment]
The subject has been discussed many times in various BBB issues. Take a look at this [#8295](https://github.com/bigbluebutton/bigbluebutton/issues/8295)

**Comment by matiasilva** [comment]
What do you mean local audio/video? Like another webcam? If so, you can do that with software like OBS.

**Comment by CPHM** [comment]
I mean a video or audio file which is on my pc

**Comment by matiasilva** [comment]
Ah, I see. You can share a video file already, you just need to upload it somewhere then paste the link to it in the "share video". As for audio, maybe easiest to do the same as above.

**Comment by basisbit** [comment]
there exist already a bunch of feature requests regarding sharing video files here. Some of them for exactly your described use case. Thus I'll close this issue for now. Thanks.
