### ISSUE TITLE
Kurento Media Server High CPU Usage

### ISSUE THREAD

**Issue by murat-vidizayn** [bigbluebutton/bigbluebutton#10017]
**Describe the bug**
kurento-media-server process high CPU usage.

**Screenshots**
![image](https://user-images.githubusercontent.com/53259326/87019900-d85a0c00-c1db-11ea-8147-fc0ad2f18278.png)

**Additional context**
BigBlueButton version 2.2.19

**Comment by matiasilva** [comment]
Hi, please follow these instructions: https://docs.bigbluebutton.org/2.2/getting-help.html#help-installing-or-running-bigbluebutton for asking for help.
