### ISSUE TITLE
CPU Usage in the Recording

### ISSUE THREAD

**Issue by harika1258** [bigbluebutton/bigbluebutton#10013]
Is it possible, when all of the sessions are recording, publish, and rebuild raw files are performed at the free time of server? for example at midnight? Because when a few numbers of sessions are presenting, and also recording set auto true, CPU usage and memory and Read/Write to Hard increase then performance goes down. Any Idea?

**Comment by basisbit** [comment]
For support requests, please use the [forum / mailing list](https://groups.google.com/forum/#!forum/bigbluebutton-setup). This issue tracker here is only for BBB development related issues. Sorry.

The feature you are for can be done using cronjob. There already exist a couple of discussions about this in the mailing list archive. Google search might help for this.
