### ISSUE TITLE
No speaking possible with specific headset.

### ISSUE THREAD

**Issue by Friedrich2** [bigbluebutton/bigbluebutton#10012]
I'm using BigBlueButton with the headset "Sennheiser HD 4.40 BT". It is possible for me to hear what is spoken in the conference, but its's impossible to speak myself, no matter which combination of microphone / right management I use. (tested multiple times). Yes, I am using the newest version of Firefox.

With Jitsi Meet and the same headset, the problem vanishes. Can you please reproduce and solve it? Many thanks in advance.

**Comment by matiasilva** [comment]
Hi.

Can you post this to one of the support groups? https://groups.google.com/forum/#!forum/bigbluebutton-users. Also,

> Can you please reproduce and solve it? 

How?...
