### ISSUE TITLE
raise hand option can be made as separate button

### ISSUE THREAD

**Issue by rexon07** [bigbluebutton/bigbluebutton#10019]
I would like to know its possible make the raise hand option as separate button. if it is possible where can i find the source code file for it so that i would be able to edit the code. currently the raise hand option is available under set status.

**Comment by iSamof** [comment]
@rexon07 - there are a number of issues here in GitHub about customising the HTML 5 client. Example: [#5836](https://github.com/bigbluebutton/bigbluebutton/issues/5836)

Also, the dev team are working on a layout manager or editor. I don't know how comprehensive it will be. It would be nice to know the spec of it. But that too may make it easy for you and many other variations to the client UI.

**Comment by matiasilva** [comment]
Seeing as you asked for how to do it and not as a feature I will point you to https://groups.google.com/forum/#!forum/bigbluebutton-dev where you can ask other developers. The source code is available in this repository and development instructions are available in the documentation. There have been people asking this before, so have a browse too. Closing as this is a support request.
