### ISSUE TITLE
Memory usage by Freeswitch and kurento-media-server in the bigbluebutton

### ISSUE THREAD

**Issue by harika1258** [bigbluebutton/bigbluebutton#10014]
Hi every body,
I understood today, after all of our class (about 20 class online) finished but Freeswitch and Kurento media server, didn't release the memory of server. what do we do? Just reset services every time???
![membig](https://user-images.githubusercontent.com/57555674/86961031-bfb70b00-c175-11ea-998a-9fd7a13e0f5f.jpg)

**Comment by basisbit** [comment]
That looks like virtual memory usage, not actual memory usage. You might want to check the tool which you use for this.

Anyways, for support requests, please use the [forum / mailing list](https://groups.google.com/forum/#!forum/bigbluebutton-setup). This issue tracker here is only for BBB development related issues. Sorry.
