### ISSUE TITLE
Add pause / stop button

### ISSUE THREAD

**Issue by jidanni** [bigbluebutton/bigbluebutton#10018]
Please at least include a stop button, so that we can stop streaming,
and start it later, without having to close the entire browser tab,
and then re-visit the URL all over again later.

We might want to watch a football game in a different browser window,
and not waste bytes in this window. No, I am not demanding that you
save up the bytes we missed, so we don't skip any content. I'm just
saying there should be a way of turning off the bytes coming to this
window.

(I was using
https://osmvideo.cloud68.co/html5client/join?sessionToken=9crfutjyfbvcmdj3 )

**Comment by basisbit** [comment]
What streaming are you referring to? This here is the BigblueButton server software project, not any streaming solution which some event that you participated in might be using.
I'll close this issue for now because it is not a valid FeatureRequest for this software here. This is at least not the right project/repository for your question.

**Comment by basisbit** [comment]
if you are referring to the "state of the map 2020" conference, their video recording should be available later on at https://media.ccc.de/c/sotm2020

**Comment by jidanni** [comment]
I AM SAYING that that conference was using BBB and BBB is curious because it lacks any pause or stop button.

**Comment by basisbit** [comment]
You can't just pause a real-time webconference. We can't stop the world...

**Comment by jidanni** [comment]
Yes we could. While watching the main conference on that https://media.ccc.de/c/sotm2020 they had a pause button. When one resumes, yes, one is no longer in sync with the live version, unless one also clicks "LIVE", which then jumps ahead, back in sync.

**Comment by jidanni** [comment]
The point is, one might want to do something else with their internet connection, without throwing away the whole window just to stop it temporarily.

**Comment by jidanni** [comment]
Or, let's say bytes cost money, and I plan to go to the bathroom for 15 minutes. I suppose I could unplug the ethernet just to stop traffic, but a simple BBB stop button would allow me to still get email during that time.

**Comment by jidanni** [comment]
> You can't just pause a real-time webconference. We can't stop the world...

Just like you didn't start the conference when we joined late, you didn't stop it when we left early.
But we want to rejoin it again, without having to do the many steps over again. If there was a stop button,
then we could just toggle that to rejoin.

**Comment by prlanzarin** [comment]
@jidanni There's a data savings option which will cut down usage to a minimum. Top right, three dots (settings), `Data savings`. Not as easy to find I wished it to be, but it's something.

**Comment by matiasilva** [comment]
I have to say I am quite confused. Are you referring to pausing a live session or a recorded session?

**Comment by jidanni** [comment]
I'm sure data savings is great but I am talking about a good old pause
or stop button.

I recall BBB has a big start arrow that one needs to push to get things
started. (But no stop button!)

All I know is imagine going to YouTube and you can only start movies,
but not pause/stop them.

Ah, live channels too.

1. Let's visit https://www.youtube.com/live
2. Pick oh, https://www.youtube.com/watch?v=RaIJ767Bj_M which has a running 11:33:44 clock inside the bottom of its TV screen while broadcasting news.
3. Now click the center of the screen. The stream freezes. Now wait a while and click again. The (stream and) clock jumps ahead (skipping over the seconds we missed) and streaming resumes.

That's all I'm asking for. Luxuries like being able to pause and resume (though no longer in sync) can be added later.

**Comment by jidanni** [comment]
"Why would you want to pause? Are you answering a phone call? Well there's a mute button (maybe, or your browser has a mute tab right click)."
Mute buttons are fine, but why can't we also freeze the video stream?

**Comment by matiasilva** [comment]
Please answer my question. Your original statement is unclear, but I assume you mean the live video call. That's just slightly pointless. If you don't want to see webcams, then just hide them for yourself. You can't pause incoming live video. YouTube is different, it's a live streaming service. This is a video conferencing/teaching tool.

**Comment by jidanni** [comment]
Yes, live video calls. https://github.com/voc/streaming-website/ has the features I am suggesting.
> then just hide them for yourself

OK, how? Switch to a different browser tab? And how to unhide them later? Switch back to that browser tab. Fine.
Problem is: why have that browser tab wastefully stream while it is "hidden"? Why not have a way to temporarily stop the flow?

**Comment by matiasilva** [comment]
I'm not familiar with the first link you shared. Regarding hiding webcams, you can disable them permanently as mentioned above otherwise there is an active feature request for toggleable webcams. This will allow you to hide/show webcams.

**Comment by basisbit** [comment]
VOC is the "Video Operation Center", a group of cool people mostly from Chaos Computer Club Germany and they provide something like Twitch/YouTube for video live-streaming mostly for events in the hacker-/makerspace area. They did the video streaming for an OpenStreeMap conference that the issue creator apparently participated in.

I still don't get why the issue creator didn't just close the browser tab and reopen it later on when they wanted to join the meeting again.

**Comment by jidanni** [comment]
Because when you reopen it later you have do a lot of actions all over again to get the thing started. You also lose the place where you were reading in the comments, or the chatbook or whatever.

**Comment by jidanni** [comment]
And furthermore where is the user supposed to get the URL to open it again? They must get it from their browser history, or find the page that referred it to them.

**Comment by jidanni** [comment]
One idea is, while watching the conference, find some link at the bottom of the page and press that. Okay now when we're ready to resume watching the conference just click the back button in your browser.

However, I'm sure it isn't that simple. When you land back on the page you got to hit a lot of things to get the movie started again.

**Comment by saerdnaer** [comment]
@jidanni The correct place for this issue would be https://github.com/voc/voc-player/issues
