### ISSUE TITLE
PDF blend modes are lost in pdf conversion

### ISSUE THREAD

**Issue by nilskanning** [bigbluebutton/bigbluebutton#10016]
**Describe the bug**
When uploading a pdf generated from a latex file, the blend modes of pgf images used in that file are not reproduced correctly.

**To Reproduce**
Here is the latex code of a minimal example with the blend mode "screen", which was taken from the pgf manual:
```
\documentclass{article}
\usepackage{tikz}
\begin{document}
\tikz {
  \begin{scope}[transparency group]
    \begin{scope}[blend mode=screen]
      \fill[red!90!black] ( 90:.6) circle (1);
      \fill[green!80!black] (210:.6) circle (1);
      \fill[blue!90!black] (330:.6) circle (1);
    \end{scope}
  \end{scope}
}
\end{document}
```
Compiling this example using pdflatex and uploading it as a presentation on the BigBlueButton demo server evokes the described issue.

**Expected behavior**
The image should be rendered as on the right-hand side of the screenshot.

**Actual behavior**
BigBlueButton produces the left-hand side of the screenshot.

**Screenshot**
![screenshot](https://user-images.githubusercontent.com/68029478/86964616-a9558300-c166-11ea-979f-fb12ebf6aff9.png)

**Comment by GhaziTriki** [comment]
This is related to LibreOffice. It needs more investigation.
