### ISSUE TITLE
Add endMeetingURL to the create API call

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#10015]
**Problem**
For deployments that use a load balancer (such as scalelite), when the moderator ends the meeting, the meeting ends on the BigBlueButton server (not on the load balancer).

As a result, if the meeting starts again quickly, it might start on the same server regardless if there was another least loaded server

**Describe the solution you'd like**
Add a new parameter `endMeetingURL` that the front-end can pass along as the URL that is called (by `akka-apps`) when a moderator executes an 'End Meeting' request.

**Additional context**
If there is no `endMeetingURL` passed, then the operation is handled normally by akka-apps.

**Comment by pedrobmarin** [comment]
How about using the webhooks?

**Comment by ritzalam** [comment]
This can be implemented like https://github.com/bigbluebutton/bigbluebutton/blob/develop/bbb-common-web/src/main/java/org/bigbluebutton/web/services/callback/CallbackUrlService.java

With webhooks, not sure if we can pass the `endMeetingURL` param. 

How should we do this if done using webhooks?

**Comment by pedrobmarin** [comment]
The load balancer subscribe the webhooks for the end meeting events then when it happens they are posted about it

**Comment by ritzalam** [comment]
The LB has to do this for each meeting, right? Or just need to subscribe once and the LB gets all the end meeting events?

**Comment by pedrobmarin** [comment]
It has to do per webhook app. Normally each bbb server can have one webhook app

**Comment by fcecagno** [comment]
You can configure persistent hooks on bbb-webhooks, so it will report all events to the load balancer, no need to register per meeting. If you need only the end meeting events, you can also configure that.
