### ISSUE TITLE
Click the icon in the upper right corner, personal settings, an error of 500 appears.

### ISSUE THREAD

**Issue by N-lucky** [bigbluebutton/bigbluebutton#10025]
**Describe the bug**

Click the icon in the upper right corner, personal settings, an error of 500 appears.
How can I modify it? thank you very much.

**To Reproduce**
1. Log in to the bbb domain name website
2. Click the user icon in the upper right corner
3. Click "Personal Settings"
4. 500 errors on the page

**Screenshots**

![bbb-cuo1.jpg](https://i.loli.net/2020/07/10/2f3tRJ7nIXHTcyE.jpg)
![bbb-cuo2.jpg](https://i.loli.net/2020/07/10/KCMu5iGT3n7sYJv.jpg)

**BBB version (optional):**
BigBlueButton continually evolves. Providing the version/build helps us to pinpoint when an issue was introduced.
Example:
$ sudo bbb-conf --check | grep BigBlueButton
BigBlueButton Server 2.2.19 (2025)

**Desktop (please complete the following information):**
 - OS: [ Windows]
 - Browser [Chrome]
 - Version [Google Chrome 83.0.4103.116]

**Comment by matiasilva** [comment]
Hi, thanks for posting. This is the forum for BigBlueButton, NOT Greenlight. Please ask your question here: https://groups.google.com/forum/#!forum/bigbluebutton-greenlight
