### ISSUE TITLE
Float the chat window to right so that presentation is at the center of the screen.

### ISSUE THREAD

**Issue by rexon07** [bigbluebutton/bigbluebutton#10028]
Is it possible to float the chat  window to the right of the screen. If possible where can i find source code for it. from where i could change its position.

**Comment by matiasilva** [comment]
Hi, in one of your other issues I have already pointed you to the groups, please make use of them: https://groups.google.com/forum/#!forum/bigbluebutton-dev. You can close the chat window in your case and that will center the presentation.
