### ISSUE TITLE
RTL Tools > Text Issue

### ISSUE THREAD

**Issue by peylight** [bigbluebutton/bigbluebutton#10026]
**Describe the bug**
When i use `Tools > Text` in RTL language like Persian, after enter text the text goes to the left side. Actually RTL mean Right To Left so it would be goes to the right side instead of left side.

**To Reproduce**
1. Go to Tools
2. Click on Text
3. Type something in Persian (or any RTL language)

**Expected behavior**
I expect after typing done it is stay in right side.

**Actual behavior**
After typing done the text will be go to left side of text box.

**Screenshots**
![alt first-step](http://s13.picofile.com/file/8402466518/bbb1.png)
![alt second-step](http://s12.picofile.com/file/8402467484/bbb2.png)

**Desktop:**
 - OS: Linux x64_86
 - Browser Firefox
 - Version 68.9.0esr

**Additional context**

**Comment by mailalaki** [comment]
Hi, Yes, this is really annoying for Arabic/Persian Users.
@ffdixon @GhaziTriki , Do you have a solution for this?

**Comment by antobinary** [comment]
Resolved as  part of the transition to tldraw in BBB 2.6
