### ISSUE TITLE
User interface control

### ISSUE THREAD

**Issue by meetingb** [bigbluebutton/bigbluebutton#10039]
Hello,

I submit a request which seems feasible to me.

bring up the view to lock users the possibility for the moderator to be able to put the presentation in full screen or reduce it, put in full screen the webcam or not, leave open, close or lock the pane list of users and tab of discussion in all users interface.

this will make BBB the most versatile solution in the world.

Thank you for the extraordinary work you do.

cordially

**Comment by matiasilva** [comment]
Hi @meetingb, everything you mention can be done already.

> bring up the view to lock users 

not sure what you mean here, you can lock users by clicking on the gear icon

> the possibility for the moderator to be able to put the presentation in full screen or reduce it

can be done, but the changes will not be pushed to the clients

> put in full screen the webcam or not

can also be done 

> leave open, close or lock the pane list of users and tab of discussion in all users interface.

can also be done already

I suggest you read the documentation to find out more information: docs.bigbluebutton.org

**Comment by meetingb** [comment]
thank you for your answer, I know that all its functionalities are feasible but the idea is that the moderator can apply for example the closing and locking of the discussion section or the closing and locking of the section on the left where it is the list of users in order to focus on the important parts that users should see during a course.

there is also the fact that many users do not master the tool so it would be very interesting to be able to act on the user interface from the moderator.

thanks again

**Comment by matiasilva** [comment]
Merging with #7987.
