### ISSUE TITLE
In Mobile if any one click back button then they leave the meeting

### ISSUE THREAD

**Issue by bipintulo** [bigbluebutton/bigbluebutton#10036]
**Describe the bug**
Now teachers and students can connecting to the meeting via mobile. So what happen when they click back on their phone which is most of us having a habit to click back .. they left the meeting. Which is very distorting. 

**To Reproduce**
1. Join a meeting or start a meeting with mobile 
2. Click on universal back button of your mobile 
3. You will be left the meeting

**Expected behavior**
There a pop up box should appear .. do you  want to exit the meeting. which can be created via java script. 

**Where to put Javascript or jquery**
I dont have any idea to where to put.

**BBB version (2.2):**

**Smartphone (please complete the following information):**
 - Device: VIVO S1 pro Android 
 - OS: 
 - Browser Google Chrome latest
 - Version : 82

**Comment by TechRova** [comment]
Same problem for me also . must be fixed

**Comment by matiasilva** [comment]
Hi @TechRova, if there's any sense of time urgency, then I recommend you directly reach out to the companies providing commercial support for BigBlueButton.

**Comment by bipintulo** [comment]
its urgency .. i dont figure out where to write this ..

**Comment by matiasilva** [comment]
@bipintulo, if you want to have a go at this yourself, you can set up a development environment for the HTML5 client with instructions here: https://docs.bigbluebutton.org/2.2/dev.html

**Comment by bipintulo** [comment]
what does it means ? 
any reference video to edit this
By default, the client will run in development mode. Loading into production environment can be done by passing the value of NODE_ENV:

$ NODE_ENV=production npm start

**Comment by matiasilva** [comment]
Hi @bipintulo, feel free to ask for help on the development forum: https://groups.google.com/forum/#!forum/bigbluebutton-dev

**Comment by bipintulo** [comment]
i asked to join the group but they have deny my joining request :(

**Comment by azrdev** [comment]
Maybe the fix ist just as simple as letting the user confirm leaving the current page:
~~~javascript
window.onbeforeunload = function(){
  return 'Are you sure you want to leave?';
};
~~~

**Comment by voidspacexyz** [comment]
I would like to call attention to this bug. The fix from the comments look simple. Many folks using BBB are claiming that the tool doesn't work. I can't engage in a technical argument with them on this. Is there a way this can get added in 2.4?

**Comment by shariquealavi** [comment]
Any possibility of having this?
