### ISSUE TITLE
Error screen has CSS problems

### ISSUE THREAD

**Issue by daminebenq** [bigbluebutton/bigbluebutton#10034]
**BBB 2.2.20**

**to reproduce it:**
just go to `https://bbb.example.com/html5client/join?sessionToken=wrong-token` with a wrong token to get the redirection to the error screen

**console log:**
`Access to XMLHttpRequest at 'http://bbb.example.com/html5log' from origin 'http://bbb.example.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
7df6acf6cb0f651dba4e71b3adac0efd23889793.js?meteor_js_resource=true:9 POST http://bbb.example.com/html5log net::ERR_FAILED
(anonymous) @ 7df6acf6cb0f651dba4e71b3adac0efd23889793.js?meteor_js_resource=true:9
setTimeout (async)
u @ 7df6acf6cb0f651dba4e71b3adac0efd23889793.js?meteor_js_resource=true:9
(anonymous) @ 7df6acf6cb0f651dba4e71b3adac0efd23889793.js?meteor_js_resource=true:9
setTimeout (async)
u @ 7df6acf6cb0f651dba4e71b3adac0efd23889793.js?meteor_js_resource=true:9
(anonymous) @ 7df6acf6cb0f651dba4e71b3adac0efd23889793.js?meteor_js_resource=true:9
setTimeout (async)
u @ 7df6acf6cb0f651dba4e71b3adac0efd23889793.js?meteor_js_resource=true:9
o.start @ 7df6acf6cb0f651dba4e71b3adac0efd23889793.js?meteor_js_resource=true:9
e @ 7df6acf6cb0f651dba4e71b3adac0efd23889793.js?meteor_js_resource=true:9
h @ 7df6acf6cb0f651dba4e71b3adac0efd23889793.js?meteor_js_resource=true:121
b @ 7df6acf6cb0f651dba4e71b3adac0efd23889793.js?meteor_js_resource=true:121
(anonymous) @ 7df6acf6cb0f651dba4e71b3adac0efd23889793.js?meteor_js_resource=true:121
f @ 7df6acf6cb0f651dba4e71b3adac0efd23889793.js?meteor_js_resource=true:121
logger.js @ 7df6acf6cb0f651dba4e71b3adac0efd23889793.js?meteor_js_resource=true:121
g @ 7df6acf6cb0f651dba4e71b3adac0efd23889793.js?meteor_js_resource=true:7
n @ 7df6acf6cb0f651dba4e71b3adac0efd23889793.js?meteor_js_resource=true:7
a @ 7df6acf6cb0f651dba4e71b3adac0efd23889793.js?meteor_js_resource=true:9
main.jsx @ 7df6acf6cb0f651dba4e71b3adac0efd23889793.js?meteor_js_resource=true:121
g @ 7df6acf6cb0f651dba4e71b3adac0efd23889793.js?meteor_js_resource=true:7
n @ 7df6acf6cb0f651dba4e71b3adac0efd23889793.js?meteor_js_resource=true:7
e @ 7df6acf6cb0f651dba4e71b3adac0efd23889793.js?meteor_js_resource=true:7
(anonymous) @ 7df6acf6cb0f651dba4e71b3adac0efd23889793.js?meteor_js_resource=true:121`
![aaaaaa](https://user-images.githubusercontent.com/5144311/87202359-c6a95f00-c2d6-11ea-9067-3f73db5d3922.gif)

**Comment by pedrobmarin** [comment]
Try it out https://dev22a.bigbluebutton.org/html5client/join?sessionToken=wrong-token because looks like only a CORS error because you used http instead

**Comment by daminebenq** [comment]
same thing, i wrote the link without ssl by mistake, you're right, but still an issue

**Comment by GhaziTriki** [comment]
HTTPS is now mandatory.
