### ISSUE TITLE
Is it possible to use GPU encoding for Recording and streaming?

### ISSUE THREAD

**Issue by TechRova** [bigbluebutton/bigbluebutton#10037]
**Is your feature request related to a problem? Please describe.**
The streaming and recording taking CPU but CPU encoding is slow

**Describe the solution you'd like**
Is it possible to use GPU encoding using NVENC or OpenCL? Since GPU encoding is fast and streamers like Ant Media Server supporting GPU enocding 

And if a server have 2 GPUs , then one used for streaming and anther one for encoding of recording

**Comment by basisbit** [comment]
For support requests, please use the [forum / mailing list](https://groups.google.com/forum/#!forum/bigbluebutton-setup). This issue tracker here is only for BBB development related issues. Sorry.

There were already a couple of similar questions in the mailing lists. With the default settings of BigBlueButton, video should never be transcoded except for processing recordings of sessions. For that, BBB uses ffmpeg. If you replace ffmpeg with a custom build tailored to your VDPAU or VAAPI setup, you might get some improvement for processing recording video streams. 

You mentioned streaming - I guess you refer to some custom RTMP video streaming docker container or similar solution. That is not part of the BigBlueButton project - you'll best ask at that project's support channels.

Hope this helps.
