### ISSUE TITLE
Abnormal CPU Usage with no Users

### ISSUE THREAD

**Issue by UnderFenex** [bigbluebutton/bigbluebutton#10033]
**Bug**
I have 30 Virtualized BBB Servers, of 4CPUs and 8GB of RAM, each one has its own BBB Installacion and runs under a subdomain. When Users finish they clases (so no more users left, no more classes left), they finish the session, and most of the servers (around 28), go back o 1 - 5% CPU Usage average. However I have between one and three that have an "abnormal CPU Usage" of around 10% even 20% as shown in the graph.

I have checked the processes with htop, and this consumption is due to Freeswitch.

**To Reproduce**
1. Clases with Users 
2. Users Leave
3. Servers keep using CPU by Freeswitch with no users left
4. CPU Usage sometimes reaches 100% with no users and last for hours.
5. I have stopped BBB, restarted the Server, stop the freeswitch service. All of them flat the CPU usage, but as soon as it's restarted everything  goes back to abnormal.

**Expected behavior**
CPU Usage should be around 1 - 5% as the other 28 Servers.

**Actual behavior**
Abnormal CPU Usage by Freeswith

**Screenshots**
![BBB](https://user-images.githubusercontent.com/3832413/87191435-06158280-c2ba-11ea-8700-8d3073d69a91.png)
![BBB2](https://user-images.githubusercontent.com/3832413/87191448-0a41a000-c2ba-11ea-9368-34e0cd60b4a7.png)

@basisbit you mentioned on #9701 that this can be a freeswitch flood by not having a firewall? Can you explain me how the firewall keep freeswitch from flooding?

**Comment by basisbit** [comment]
For support requests, please use the [forum / mailing list](https://groups.google.com/forum/#!forum/bigbluebutton-setup). This issue tracker here is only for BBB development related issues. Sorry.

For how to firewall, see https://docs.bigbluebutton.org/2.2/customize.html#secure-your-system--restrict-access-to-specific-ports . If you are using sip-call-in for participants by phone, use Fail2Ban (see https://freeswitch.org/confluence/display/FREESWITCH/Fail2Ban ) and only allow the IP addresses from your SIP provider to connect to your port 5060.

**Comment by basisbit** [comment]
Also, please do not open any further issues here in this issue tracker regarding such support questions. This is not a bug in BigBlueButton and thus should not be in the development issue tracker.
Duplicate of #9701
