### ISSUE TITLE
Microphone icon does not appear on unlocking the user

### ISSUE THREAD

**Issue by misisol** [bigbluebutton/bigbluebutton#10038]
Hi everyone,
Whenever I create a class upon API and set **lockSettingsDisableMic=true**, and the moderator  unlock the user to access microphone, the microphone icon does not appear!
The user has to leave the audio and join again to be asked if he wants to use microphone.

**Expected behavior**
Appear the microphone icon when the moderator unlock the user to speak!

BigBlueButton Server 2.2.2 (1816)

**Additional context**

**Comment by jpe9** [comment]
same problem here.. did you find a workaround? it's quite time-consuming to explain how to exit and re-join the audio-conference to users which are not well-proven to webconferencing tools
