### ISSUE TITLE
Migration of recordings to another server

### ISSUE THREAD

**Issue by RenSolis** [bigbluebutton/bigbluebutton#10047]
I have been migrating the recordings from one server to another and trying to update them in different ways such as room internalID and the name of the server, to assign it to a room, but when executing "bbb-record --list" it shows that the recording exists but not ends it showing in greenlight only the recordings that the server already has previously

the problem is the second row:
![image](https://user-images.githubusercontent.com/32459662/87252819-bb237880-c43b-11ea-8dd5-fa78dc63f158.png)

**Comment by matiasilva** [comment]
Hi, for support requests please use the mailing lists: https://docs.bigbluebutton.org/2.2/getting-help.html
