### ISSUE TITLE
Add check in bbb-conf to check stun server

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#10045]
There is a STUN server configured in Kurento's settings file, and it must be an IP address.  The documentation was using a Google STUN server IP address.  However, it recently changed and, as a result, many BigBlueButton server's that were behind a firewall (and hence needed the STUN server to get its external IP address) had users encountering 1020 errors when sharing media.

**Describe the solution you'd like**
Add a check to bbb-conf to ensure the STUN server is reachable and working from the BigBlueButton server.

**Comment by steffen-moser** [comment]
Just a short question: Does this mean that the STUN-related part of "/usr/share/bbb-web/WEB-INF/classes/spring/turn-stun-servers.xml" is ignored by Kurento?

**Comment by ffdixon** [comment]
It's used by Kurento as well.  In other words, the client uses it when connecting either to FreeSWITCH or Kurento.

**Comment by prlanzarin** [comment]
Fixed in https://github.com/bigbluebutton/bigbluebutton/pull/11401
