### ISSUE TITLE
Notify users when presentation is available for download.

### ISSUE THREAD

**Issue by crstnmac** [bigbluebutton/bigbluebutton#10041]
**Describe the bug**
When owner of the room enables presentation is allowed to be downloaded, users find difficult 
to see the download button. It would be nice to notify users that presentation is available for download.

**To Reproduce**
1. Go to 'Action'
2. Click on ' Small icon (like file download) '
3. Users will not be notified.

**Expected behavior**
A toast showing presentation is available for download.

**Actual behavior**
Nothing happens at the user side.

**Comment by tylercopeland** [comment]
@crstnmac, thank you for sharing feedback on this experience. 

I have put together a simple design that will allow us to capture more feedback from the community.

Today, we have a toast message that indicates the current presentation. We could extend this experience by adding a download link.

![Screen Shot 2020-07-31 at 3 23 37 PM](https://user-images.githubusercontent.com/1273169/89069779-cfbfa600-d341-11ea-943a-da16be6414ee.png)

The toast will stay visible until a user either clicks "Download" or "X" to close out the modal.

**Comment by crstnmac** [comment]
Awesome 😊

**Comment by iSamof** [comment]
This clear download link would be a great addition. Thanks @crstnmac and @tylercopeland 

Given the new function for multiple switchable presentations ([https://github.com/bigbluebutton/bigbluebutton/pull/8552](https://github.com/bigbluebutton/bigbluebutton/pull/8552)) I guess the toast pop should list all the presentations marked as downloadable.

**Comment by GhaziTriki** [comment]
Implemented in 2.3
