### ISSUE TITLE
122932

### ISSUE THREAD

**Issue by ntackie** [bigbluebutton/bigbluebutton#10044]
Having this issue when installing bigbluebutton I'm a newbie to this software

<img width="624" alt="Screen Shot 2020-07-11 at 8 17 09 PM" src="https://user-images.githubusercontent.com/40070477/87236166-9daacc00-c3b3-11ea-99b0-881df0d9af66.png">

**Comment by ffdixon** [comment]
This isn't a valid bug report as there is no underling issue in BigBlueButton to fix.  This looks like a configuration issue on your server.  Please see

  https://docs.bigbluebutton.org/2.2/getting-help.html#help-installing-or-running-bigbluebutton

on troubleshooting installation issue and what information you need to share when posting for help.  If you do want to engage the community for help, post to bigbluebutton-setup.
