### ISSUE TITLE
skipCheck: bbb-conf --restart - Error Page shown before Default.pdf loads

### ISSUE THREAD

**Issue by bayden10** [bigbluebutton/bigbluebutton#10049]
This issue tracker is only for bbb development related issues.-->

**Describe the bug**

Modify settings.yml skipCheck: [run bbb-conf --restart] 
Login, start a new session and the default.pdf will load in most cases when skipCheck is set to true but more error pages are shown when set to false. After selecting your audio choice the load Error warning page is displayed. When reload button is clicked then everything loads again as normal to be able to select your Audio choice at which time the default page has already loaded. (default page has 12 slides for extra white boarding). In some cases when the reload button is selected (while skipCheck: false) the page reloads and the audio selection icons are shown again and clicking on Mic the "Connecting to echo test" is shown and then "This is a private echo test. Speak a few words. Did you hear audio?" selecting the YES icon the audio selection Icons are provided again and is caught in a small loop several times while an error message states "you have left the audio session." This seems to happen more just after a run **bbb-conf --restart** 

**To Reproduce**

Steps to reproduce the behavior: [intermittent]
1.  Modify /usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml and change default setting for skipCheck from false to true or true to false:
```
public:
  app:
    mobileFontSize: 16px
    desktopFontSize: 14px
    audioChatNotification: false
    autoJoin: true
    listenOnlyMode: true
    forceListenOnly: false
    skipCheck: true
```
* run 
``` 
bbb-conf --restart
```

2. At the home page of BBB (Greenlight) and already logged out, click sign in button to BBB and start a new session from home room as moderator.
3. Select Microphone icon for audio (page has not loaded the default.pdf at this point in the background)
4. Error page is displayed

**Expected behavior**
The default.pdf should completely load in the background [ use a possible progress indicator for loading the default page if large] and then the audio selection should take place as to give the load process enough time before selecting your audio choice.

**Actual behavior**
Select audio choice before default.pdf has loaded and error page is displayed. [intermittent]

**Screenshots**
![newsession_withaudio](https://user-images.githubusercontent.com/22577485/87255868-78be6380-c45c-11ea-8b07-d88db3af0cd7.png)

Error states: "Cannot destructure property 'width' of 'e' as it is undefined."
Click "Reload" button

**BBB version (optional):**
[2.3Alpha1]
bbb-html5 1:2.3.0-1061 amd64 The HTML5 components for BigBlueButton

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [Chrome]
 - Version 83.0.4103.116 (Official Build) (64-bit)

**Additional context**

**Comment by antobinary** [comment]
Also reported in #11270 , marking this one as duplicate
@ramonlsouza please try to reproduce via this set of steps
