### ISSUE TITLE
Chat message shows up under wrong user name

### ISSUE THREAD

**Issue by jodoma** [bigbluebutton/bigbluebutton#10048]
**Describe the bug**
We are running a BBB installation using scalelite and 20+ BBB instances. On this installation we are hosting several hundred meetings a day with on average 40 participants per meeting.

In **one** of the meetings the following occurred, assuming there are three users Alice, Bob and Carol: Carol has been in the meeting already with Alice and Bob joining later, but not at the same time (indeed, Bob joins 5 minutes after Alice). Carol sends a private message to Bob; this message shows up in the public chat under Alice's name.

**To Reproduce**
We were not able to reproduce the scenario.

**Expected behavior**
When showing a user message the original author of the message should be shown, not someone else.

**Actual behavior**
See description.

**Screenshots**
Screenshots are available, but due to privacy reasons, I cannot share them in the bug tracker.

**Desktop (please complete the following information):**
 - Chrome (all three users)
 - BBB version: 2.2.12

**Comment by ffdixon** [comment]
Can you upgrade to BigBlueButton 2.2.20 and let us know if you can reproduce this.  We had fixed this issue in a subsequent update after 2.2.12 and we would be very interested if you see it happening on the latest build.

**Comment by jodoma** [comment]
Thanks for the very quick response. We only experienced this issue once in the last 4 months. We also applied all upgrades that were available in the last months and are currently running 2.2.19. If you fixed this problem, this issue can probably be closed.

**Comment by Neustradamus** [comment]
Any news on it?

**Comment by ffdixon** [comment]
I think we got this fixed as we've not seeing it appear on our testing in the last month. Closing this issue.
