### ISSUE TITLE
Feature for host controlling the participants screen

### ISSUE THREAD

**Issue by shopnse** [bigbluebutton/bigbluebutton#10046]
Hi Team,
Please help me if there is option for host controlling the participants screen/applications? Like request control/Apporve control and controlling the remote screen/application?

If not, let me know if this is on roadmap or alternative ways to achieve the same?

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by iSamof** [comment]
Always a good idea to search first ... [https://github.com/bigbluebutton/bigbluebutton/issues/1428](https://github.com/bigbluebutton/bigbluebutton/issues/1428)
