### ISSUE TITLE
Cant join a meeting using Greenlight in 2.3 Alpha-1

### ISSUE THREAD

**Issue by mabras** [bigbluebutton/bigbluebutton#10058]
**Describe the bug**
I am testing BBB 2.3 with Greenlight as front-end. When I start a new meeting, it just stuck on the HTML5 blue screen (without the three dots). with this console error:

<img width="1278" alt="Screenshot 2020-07-14 at 9 19 05 AM" src="https://user-images.githubusercontent.com/9248917/87412348-9bbe5400-c5d1-11ea-89a3-757015b7c1d3.png">

With API Mate every thing is just works. The problem seems to be related with the [redirection in greenlight](https://github.com/bigbluebutton/greenlight/blob/master/app/controllers/concerns/joiner.rb#L62) used to the join path

**To Reproduce**
1. Greenlight fresh install
2. Start a meeting
3. Join the meetings
4. See the blue screen with console error

**Desktop:**
 - Device: Macbook Pro
 - OS: macOS Catalina
 - Browser Chrome
 - Version 83

**Comment by maron2000** [comment]
Same as for me.
Can start and attend meeting with bbb-demo, with microphone, camera, and screensharing working,
but not with greenlight.

Ubuntu 18.04 as VMware guest 
Browser: Firefox 77.0.1 on Windows 10

**Comment by strekulev** [comment]
Same problem on BBB 2.3. If you are logged in, then you cannot enter the room, only a blue screen. But if you follow the guest link, then everything works. I hope they will solve the problem in the near future. It is clearly related to authorization.

**Comment by ffdixon** [comment]
Will have it fixed in the next update to BigBlueButton 2.3-dev (coming soon).

**Comment by martux69** [comment]
I'm a newbie to bbb and today I installed the bionic-230-dev version with bbb-install.sh and come to this problem. Is there a time schedule for this fixed version ? Can I fixed it manually on my system ?
