### ISSUE TITLE
Moderator should be able to clear all annotations

### ISSUE THREAD

**Issue by martinclauss** [bigbluebutton/bigbluebutton#10059]
## Scenario

Moderator and one _other person_ in the session, _other person_ leaves, moderator is not able to clear the _other person's_ annotations.

## Bug

It seems that this is a bug. A moderator should be able to clear all annotations even if they are not its own and __other person__ already left the session.

Thanks!

**Comment by basisbit** [comment]
You can clear all annotations by disabling the shared editing mode of the whiteboard and then clicking on the clear annotations button.
