### ISSUE TITLE
multiple join with one join url api

### ISSUE THREAD

**Issue by peymannaderi3** [bigbluebutton/bigbluebutton#10050]
Hello!
i'm creating a join url using bbb api.
this is the link:

https://server/bigbluebutton/api/join?meetingID=test-1&fullName=test&password=123456&checksum=mychecksome
the user can join the meeting fine.

the problem is that there is no expiration on this link so it can be spread and used multiple times.
i want to just one user at a time can join with this link.
how can i do that?

**Comment by basisbit** [comment]
For support requests, please use the [forum / mailing list](https://groups.google.com/forum/#!forum/bigbluebutton-dev). This issue tracker here is only for BBB development related issues. Sorry.
