### ISSUE TITLE
Moodle resource as default presentation slide

### ISSUE THREAD

**Issue by shopnse** [bigbluebutton/bigbluebutton#10052]
Hi Team,
Product is rocking, keep going!

I have integrated Moodle with BBB, I have also tested for creating a room for specific class scheduled. It is working good. Further, I am trying to project the default resource loaded for that particular class as my default presenter slide. 

Please direct me if there are any configuration required to pick the slide from that particular Class-Lesson or any API available for the invocation?

Thanks in advance

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by matiasilva** [comment]
Hi, please use the mailing lists for this: https://docs.bigbluebutton.org/2.2/getting-help.html

**Comment by ffdixon** [comment]
For bugs/enhancement request so the BigBlueButtonBN moodle integration, can you use the Moodle bug tracker for the plugin.  See

  https://tracker.moodle.org/issues/?jql=project%20%3D%20CONTRIB%20AND%20component%20%3D%20%22Module%3A+BigBlueButtonBN%22

Thanks!
