### ISSUE TITLE
Install version 2.2.2

### ISSUE THREAD

**Issue by z-j-j** [bigbluebutton/bigbluebutton#10057]
wget -qO- https://ubuntu.bigbluebutton.org/bbb-install.sh | bash -s -- -w -v xenial-220-2.2.9 -a -w
This command specifies the installation of version 2.2.9
wget -qO- https://ubuntu.bigbluebutton.org/bbb-install.sh | bash -s -- -w -v xenial-220-2.2.2 -a -w
I changed 2.2.9 to 2.2.2, indicating that it cannot be installed
Is there a solution? thank you

**Comment by matiasilva** [comment]
Hi. See: https://docs.bigbluebutton.org/2.2/getting-help.html

**Comment by z-j-j** [comment]
> 你好 请参阅：[https](https://docs.bigbluebutton.org/2.2/getting-help.html)：[//docs.bigbluebutton.org/2.2/getting-help.html](https://docs.bigbluebutton.org/2.2/getting-help.html)

Hello, there is no solution here

**Comment by matiasilva** [comment]
Yes, the above document outlines how you may get help. Is there any reason why you need to switch to 2.2.2, that version is quite outdated and misses a lot of the newer upgrades and bug fixes done in the most recent version.
