### ISSUE TITLE
Default slide not loading 

### ISSUE THREAD

**Issue by faiyaz-ergo** [bigbluebutton/bigbluebutton#10053]
Default slide is not loading when joining room using Greenlight.
But it's loading while joining room using default BigBlueButton's html5 client.

How to fix it?

**Comment by daminebenq** [comment]
Hi @faiyaz-ergo 
would be better to mention what BBB build you are using, and please don't forget to collect the console logs and to add some screenshots of what's happening exactly.
thanks for reporting

**Comment by faiyaz-ergo** [comment]
Please find the version detail below:
~# bbb-conf --version

ii  bbb-apps                              1:2.2.0-45                                      amd64        BigBlueButton applications for Red5
ii  bbb-apps-akka                         2.2.0-87                                        all          BigBlueButton Apps (Akka)
ii  bbb-apps-screenshare                  1:2.2.0-45                                      amd64        BigBlueButton screenshare module for Red5
ii  bbb-apps-sip                          1:2.2.0-11                                      amd64        BigBlueButton SIP module for Red5
ii  bbb-apps-video                        1:2.2.0-42                                      amd64        BigBlueButton video module for Red5
ii  bbb-apps-video-broadcast              1:2.2.0-8                                       amd64        BigBlueButton video broadcast module for Red5
ii  bbb-client                            1:2.2.0-40                                      amd64        BigBlueButton Flash client
ii  bbb-config                            1:2.2.0-191                                     amd64        BigBlueButton configuration utilities
ii  bbb-demo                              1:2.2.0-9                                       amd64        BigBlueButton API demos
ii  bbb-etherpad                          1:2.2.0-51                                      amd64        The EtherPad Lite components for BigBlueButton
ii  bbb-freeswitch-core                   2:2.2.0-112                                     amd64        BigBlueButton build of FreeSWITCH
ii  bbb-freeswitch-sounds                 1:1.6.7-6                                       amd64        FreeSWITCH Sounds
ii  bbb-fsesl-akka                        2.2.0-65                                        all          BigBlueButton FS-ESL (Akka)
ii  bbb-html5                             1:2.2.0-937                                     amd64        The HTML5 components for BigBlueButton
ii  bbb-mkclean                           1:0.8.7-3                                       amd64        Clean and optimize Matroska and WebM files
ii  bbb-playback-presentation             1:2.2.0-30                                      amd64        BigBluebutton playback of presentation
ii  bbb-record-core                       1:2.2.0-66                                      amd64        BigBlueButton record and playback
ii  bbb-red5                              1:1.0.10-16                                     amd64        The Red5 server for BigBlueButton
ii  bbb-transcode-akka                    2.2.0-8                                         all          BigBlueButton Transcoder
ii  bbb-web                               1:2.2.0-130                                     amd64        BigBlueButton API
ii  bbb-webrtc-sfu                        1:2.2.0-99                                      amd64        BigBlueButton WebRTC SFU
ii  bigbluebutton                         1:2.2.0-5                                       amd64        Open source web conferencing platform (bbb)
ii  ffmpeg                                7:4.2.2-1bbb1~ubuntu16.04                       amd64        Tools for transcoding, streaming and playing of multimedia files
ii  libavcodec58:amd64                    7:4.2.2-1bbb1~ubuntu16.04                       amd64        FFmpeg library with de/encoders for audio/video codecs - runtime files
ii  libavdevice58:amd64                   7:4.2.2-1bbb1~ubuntu16.04                       amd64        FFmpeg library for handling input and output devices - runtime files
ii  libavfilter7:amd64                    7:4.2.2-1bbb1~ubuntu16.04                       amd64        FFmpeg library containing media filters - runtime files
ii  libavformat58:amd64                   7:4.2.2-1bbb1~ubuntu16.04                       amd64        FFmpeg library with (de)muxers for multimedia containers - runtime files
ii  libavresample4:amd64                  7:4.2.2-1bbb1~ubuntu16.04                       amd64        FFmpeg compatibility library for resampling - runtime files
ii  libavutil56:amd64                     7:4.2.2-1bbb1~ubuntu16.04                       amd64        FFmpeg library with functions for simplifying programming - runtime files
ii  libopusenc0                           0.2.1-1bbb1                                     amd64        High-level API for encoding Ogg Opus audio streams
ii  libpostproc55:amd64                   7:4.2.2-1bbb1~ubuntu16.04                       amd64        FFmpeg library for post processing - runtime files
ii  libswresample3:amd64                  7:4.2.2-1bbb1~ubuntu16.04                       amd64        FFmpeg library for audio resampling, rematrixing etc. - runtime files
ii  libswscale5:amd64                     7:4.2.2-1bbb1~ubuntu16.04                       amd64        FFmpeg library for image scaling and various conversions - runtime files

When using default html5 client and join into a room I getting the default slide(see the screenshot below)
![VConnect_Demo_Meeting_w_slide](https://user-images.githubusercontent.com/44223640/87353022-da2a2380-c57d-11ea-948b-0e046e631e1f.png)
But when joining a room using greenlight(2.0) I am not getting the default slide. that section is blank(see the screenshot below)
![VConnect_Home_Room_No_Slide](https://user-images.githubusercontent.com/44223640/87353133-0776d180-c57e-11ea-959d-14b2ef82128e.png)

**Comment by basisbit** [comment]
For support requests, please use the [forum / mailing list](https://groups.google.com/forum/#!forum/bigbluebutton-greenlight). This issue tracker here is only for BBB development related issues. Sorry.

**Comment by matiasilva** [comment]
I also recommend you search around the issue tracker, many have had your issue in the past.
