### ISSUE TITLE
Playback without external video/audio

### ISSUE THREAD

**Issue by redesufpel** [bigbluebutton/bigbluebutton#10066]
Hi, 

I faced that all recordings that were published in my server didn't capture audio and video from external video played during the session. While webcam and microfone of everyone are OK;

Our server conf below:

**
root@bbb-node01:~# bbb-conf --check

BigBlueButton Server 2.2.17 (1996)
                    Kernel version: 4.4.0-184-generic
                      Distribution: Ubuntu 16.04.6 LTS (64-bit)
                            Memory: 14366 MB
                         CPU cores: 16

/usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties (bbb-web)
       bigbluebutton.web.serverURL: https://MYSERVER-ADDR
                defaultGuestPolicy: ALWAYS_ACCEPT
                 svgImagesRequired: true

/etc/nginx/sites-available/bigbluebutton (nginx)
                       server name: MYSERVER-ADDR
                              port: 80, [::]:80
                              port: 443 ssl
                    bbb-client dir: /var/www/bigbluebutton

/var/www/bigbluebutton/client/conf/config.xml (bbb-client)
                Port test (tunnel): rtmp://HOST
                              red5: HOST
              useWebrtcIfAvailable: true

/opt/freeswitch/etc/freeswitch/vars.xml (FreeSWITCH)
                       local_ip_v4: MYSERVERIP
                   external_rtp_ip: stun:stun.freeswitch.org
                   external_sip_ip: stun:stun.freeswitch.org

/opt/freeswitch/etc/freeswitch/sip_profiles/external.xml (FreeSWITCH)
                        ext-rtp-ip: $${local_ip_v4}
                        ext-sip-ip: $${local_ip_v4}
                        ws-binding: MYSERVERIP:5066
                       wss-binding: MYSERVERIP:7443

/usr/local/bigbluebutton/core/scripts/bigbluebutton.yml (record and playback)
                     playback_host: MYSERVER-ADDR
                 playback_protocol: https
                            ffmpeg: 4.2.2-1bbb1~ubuntu16.04

/etc/bigbluebutton/nginx/sip.nginx (sip.nginx)
                        proxy_pass: MYSERVERIP

/usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml (Kurento SFU)
                        kurento.ip: MYSERVERIP
                       kurento.url: ws://127.0.0.1:8888/kurento
                    kurento.sip_ip: MYSERVERIP
                    localIpAddress: MYSERVERIP
               recordScreenSharing: true
                     recordWebcams: true
                  codec_video_main: VP8
               codec_video_content: VP8

/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml (HTML5 client)
                             build: 937
                        kurentoUrl: wss://MYSERVER-ADDR/bbb-webrtc-sfu
                  enableListenOnly: true

# Potential problems described below

root@bbb-node01:~#
**

**Comment by matiasilva** [comment]
Hi, thanks for posting. For support, see how to get help here: https://docs.bigbluebutton.org/2.2/getting-help.html

**Comment by redesufpel** [comment]
Sorry @matiasilva, might help others:
https://github.com/bigbluebutton/bigbluebutton/pull/7484

**Comment by matiasilva** [comment]
Yeah, this is not an issue with your server it's simply that the feature has not been implemented. Also, I see that you commented on that post when someone else already asked for an update. It's not necessary to bother others in this way, please be patient and things will take their due course :) The PR discussion area is useful for development, so that bugs can be fixed for those PRs not for asking people to rush it into the software.
