### ISSUE TITLE
10GB of freeswitch logs

### ISSUE THREAD

**Issue by Beiri22** [bigbluebutton/bigbluebutton#10065]
I have a server running bbb 2.2. The log directory of freeswitch is about 10GB of size. That is, in my opinion, too large:
-rw-r--r-- 1 freeswitch daemon 1041462630 Jul 14 17:45 freeswitch.log
-rw-r--r-- 1 freeswitch daemon 1048576109 Jul 10 12:41 freeswitch.log.1
-rw-r--r-- 1 freeswitch daemon 1048576120 Jul  7 23:02 freeswitch.log.2
-rw-r--r-- 1 freeswitch daemon 1048576142 Jul  5 05:40 freeswitch.log.3
-rw-r--r-- 1 freeswitch daemon 1048576108 Jul  2 22:16 freeswitch.log.4
-rw-r--r-- 1 freeswitch daemon 1048576129 Jul  1 09:04 freeswitch.log.5
-rw-r--r-- 1 freeswitch daemon 1048576075 Jun 29 07:14 freeswitch.log.6
-rw-r--r-- 1 freeswitch daemon 1048576111 Jun 28 19:41 freeswitch.log.7
-rw-r--r-- 1 freeswitch daemon 1048576009 Jun 28 07:26 freeswitch.log.8
-rw-r--r-- 1 freeswitch daemon 1048576142 Jun 24 21:54 freeswitch.log.9
-rw-r--r-- 1 freeswitch daemon     571312 Jul 13 14:51 freeswitch.xml.fsxml

It looks like the maximum log rotation is reached; but maybe you could consider 
reducing the single log file size from 1GB to -- lets say -- 100MB?
Or is there any switch in the bbb-configureation?

**Comment by matiasilva** [comment]
Hi, thanks for posting. Please follow the path that's best suited for you for getting help: https://docs.bigbluebutton.org/2.2/getting-help.html.
