### ISSUE TITLE
401 Unauthorized 

### ISSUE THREAD

**Issue by krishnaguragain** [bigbluebutton/bigbluebutton#10063]
**Describe the bug**
Works on Edge Browser but shows 401 on Latest Chrome Browser on iframe but works normally in Edge's iframe.

**Behavior**
401 Unauthorized on Chrome Dev

**BBB version (optional):**
BigBlueButton Server 2.2.20 (2037)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [Chrome]
 - Version [ 85.0.4183.16 (Official Build) dev (64-bit)]

**Additional context**
Works on Edge Browser but shows 401 on Latest Chrome Browser on iframe but works normally in Edge's iframe

**Comment by basisbit** [comment]
Check your third party cookie policies in your webbrowser settings.

For support requests, please use the [forum / mailing list](https://groups.google.com/forum/#!forum/bigbluebutton-users). This issue tracker here is only for BBB development related issues. Sorry.
