### ISSUE TITLE
yaml: line 74: found a tab character that violates indentation when install in bbb-html5

### ISSUE THREAD

**Issue by mahdiprog** [bigbluebutton/bigbluebutton#10060]
when installing bbb-html5 it fails and returns

Reading package lists... Done
Building dependency tree
Reading state information... Done
The following NEW packages will be installed:
  bbb-html5
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/49.1 MB of archives.
After this operation, 141 MB of additional disk space will be used.
Selecting previously unselected package bbb-html5.
(Reading database ... 149375 files and directories currently installed.)
Preparing to unpack .../bbb-html5_1%3a2.2.0-968_amd64.deb ...
Unpacking bbb-html5 (1:2.2.0-968) ...
Setting up bbb-html5 (1:2.2.0-968) ...
13:01:39 main [ERRO] yaml: line 74: found a tab character that violates indentation
dpkg: error processing package bbb-html5 (--configure):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 bbb-html5
E: Sub-process /usr/bin/dpkg returned an error code (1)

1. sudo apt-get install bbb-html5
2. See error

**Comment by basisbit** [comment]
For support requests, please use the [forum / mailing list](https://groups.google.com/forum/#!forum/bigbluebutton-setup). This issue tracker here is only for BBB development related issues. Sorry.
