### ISSUE TITLE
Three symbols stick on the mouse pointer and overlap in multi-user mode

### ISSUE THREAD

**Issue by iznakurnozh** [bigbluebutton/bigbluebutton#10073]
**Describe the bug**
label:"User Experience (UX)" 

Three symbols stick on the mouse pointer (hand or other symbol, red round pointer, and the label with users name), which might cause some confusion. Moreover, the tool symbol overlaps the first letter(s) of user's name. 

**To Reproduce**
1. In presenter mode go to the tool menu (mid right)
2. Click on the "start multiuser mode" (lowest button)
3. Move the mouse
4. See 3 partly overlapping symbols on it

**Possible solusion**
One possible solusion would be not to show user his own name and the pointer because they do not move synchronously with the tool symbol, but come with some delay - which probably couses even more confusion.

**Screenshots**
![cursor3](https://user-images.githubusercontent.com/38284875/87560774-1cf21580-c6bc-11ea-92d5-3a8e17c8bca0.jpg)

**BBB version (optional):**
2.2.20

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Browser Firefox v.78.0.2

**Comment by daminebenq** [comment]
Hi @iznakurnozh 
I don't think this is a bug, i tried it and it's showing exactly what is expected to display.

![aaaaaa](https://user-images.githubusercontent.com/5144311/87569375-6848fb80-c69d-11ea-9cb0-8c65b1f5e2f0.gif)

**Comment by mrkeksi** [comment]
I think the username should just be above the "T" so you can read it better.
