### ISSUE TITLE
Increase Max File Upload Size

### ISSUE THREAD

**Issue by apinos76** [bigbluebutton/bigbluebutton#10076]
**Is your feature request related to a problem? Please describe.**
Customers complain that the maximum file size available for upload is too small.

**Describe the solution you'd like**
Maximum file upload size increased to 50 MB

**Comment by ritzalam** [comment]
Change this to 50MB to have bbb-web handle the upload.

https://github.com/bigbluebutton/bigbluebutton/blob/develop/bigbluebutton-web/grails-app/conf/bigbluebutton.properties#L71

Need to change the html5 client to allow uploading of the bigger size. We'll have to also see if recording processing have size limits but I don't think so.

**Comment by ritzalam** [comment]
It's already set to 50MB on the html5 client.

https://github.com/bigbluebutton/bigbluebutton/blob/develop/bigbluebutton-html5/private/config/settings.yml#L232

**Comment by Trifid** [comment]
It would be helpful if the pre-upload and presentation uploads both used the same uploader. I realize that they are different packages however consistency would be good and the presentation uploader is more user friendly.
