### ISSUE TITLE
Add support for multiple (or dual) document windows

### ISSUE THREAD

**Issue by mkpelletier** [bigbluebutton/bigbluebutton#10082]
It would be useful to be able to display multiple documents at a time in the document viewer.  We often have meetings or classes where we need to move back and forth between documents.  In these cases, having multiple document windows would seem to be the only convenient way to do this.

**Comment by matiasilva** [comment]
Screen real-estate is as small as it already is, I'm not sure having more than one document would be easily legible. The ideal solution would be to quickly switch between presentations as suggested before.

**Comment by mkpelletier** [comment]
Desktop and landscape tablets would handle the situation with ease, but the problem of screen real-estate is a potential problem on a phone.

In portrait mode on mobile you have plenty of room to display two documents, as the current layout does not make full use of the screen:
![BBB-Mobile Portrat Mockup](https://user-images.githubusercontent.com/4638072/87650844-95a3b100-c752-11ea-99a0-6fc2b0ccd57d.png)

Landscape may be more of a problem, though.

**Comment by afsharsafavi** [comment]
One Iranian online class system (skyroom.online) had this feature.
Some teachers that use skyroom and my bigbluebutton asked me to add this feature.
For some teachers it's necessary to have to separated blackboard/presentation area.
For example in first board teacher wants to show his lecture in pdf/powerpoint format and in second board he/she wants to wrote his note.
In some situation his/her lecture pages doesn't have any empty area and having separated empty board is essential.

**Comment by mkpelletier** [comment]
@afsharsafavi, this is an interesting use case and one I can see myself using.  On the issue of screen real-estate, it might make sense to include a canvas that slides in or out of view on demand.  It seems some of this programming is already functionally available in the annotation layers that are present.  Perhaps these "layers" might be extended to include a blank canvas layer and annotation toggles?  hmmm... I think I will add that feature suggestion on another ticket, but I like this kind of exploratory conversation.
