### ISSUE TITLE
Enhance whiteboard functions with the inclusion of Spacedeck

### ISSUE THREAD

**Issue by mkpelletier** [bigbluebutton/bigbluebutton#10084]
I have been combing through the issues in this project and there seem to be a good number of recommendations regarding the whiteboard.  I happened to come across another open source project that was recently open sourced and which is built on top of nodejs.  Since BBB already makes use of node, it seems like BBB could quickly take advantage of this as low-hanging fruit.

Find that project information here: https://github.com/spacedeck/spacedeck-open

**Comment by iSamof** [comment]
Interesting idea but there may be licensing issues and conflicts with BBB's license unless they can be persuaded to adopt BBB's license. 

There are colleagues here who use BBB commercially. They have added some commercial intellectual property (IP) for their own operations. But they have also contributed enormous amounts to BBB and have the community's blessings for their own commercial IP. 

I think such colleagues would then fall foul of Spacedeck's license which includes: 

"... When a modified version is used to provide a service over a network, the complete source code of the modified version must be made available. ... "

I am not a lawyer and am open to being corrected but it seems to me, Spacedeck's license is vastly more restrictive than BBB's.

**Comment by iSamof** [comment]
Whoopsy ... correction. Spacedeck's license is the same as BBB. I wonder if BBB's license has changed since I last read it, a couple of years ago. 

But my point now also applies to BBB's license with respect to commercial colleagues. Hmmm ... colour me confused!

**Comment by mkpelletier** [comment]
Yeah, I did see the LGPL licensing, but I know too little about mixing different licensing types to really comment intelligently.  

I have just been messing around with Spacedeck a bit and it looks promising as a full featured whiteboard.  I can certainly see use cases for it.  I might even be able to use it as it is to compliment our BBB instance.  Spacedeck has some nice sharing features that make it easy to do this on an ad-hoc basis.
