### ISSUE TITLE
Unmute all users [ENHANCEMENT]

### ISSUE THREAD

**Issue by pbdco** [bigbluebutton/bigbluebutton#10081]
With allowModsToUnmuteUsers=true moderators can mute ALL users but can't UNMUTE everyone at once. Only single participant unmuting is possible.

Moderator has to unmute participants one by one. In big meetings this is very tedious and inpractical, specially from an accesibility point of view this can generate inconvenience. 

"Unmute all users" should reconnect all the participants microphone.

**Comment by uka-support** [comment]
This is a privacy issue. Any user should be able to mute him/herself and no moderator should be able to unmute without consent.

That is, "unmute all users" should only allow users to unmute themselves, not forcibly unmute them.

**Comment by iSamof** [comment]
I don't believe this is a privacy issue at all. The users are not forced to talk and to say confidential/private matters. In an in-person conference or seminar, all attendees are effectively unmuted ... is that a privacy matter? No. They simply don't say in public anything that is private.

As long as the microphone symbol correctly shows the use is unmuted, the job is done. My personal view is: building exceptions upon exceptions, upon exception is taking things too far when the dev team can be focusing on much more essential matters.

**Comment by matiasilva** [comment]
Another thing, @uka-support notice the mention of "allowModsToUnmuteUsers=true". You can set this to false as you wish. This property is not related to the issue at hand though. Also, I don't think "accessibility" is a good justification for this, I think you perhaps mean UX.

**Comment by pbdco** [comment]
@matiasilva Yes, I mean accesibility. If there's a 30 user meeting who **can't** unmute themselves, at the moment the moderator can only unmute one by one. This creates confusion during a class. I dont think privacy should be an issue at all, I agree with @iSamof specially if we already have the functionallity to unmute a single user... this is not much more different than just a button to UNMUTE all of them... @uka-support

**Comment by ryprfpryr** [comment]
200% agree with @pbdco

**Comment by matiasilva** [comment]
> Computer accessibility refers to the accessibility of a computer system to all people, regardless of disability type or severity of impairment

I'm still not sold on how the moderator having to unmute every user has to do with worsening the experience for those with for example, screen readers. I still think you mean UX. I agree having to unmute every user is not a good user experience for both the users and the presenter.
