### ISSUE TITLE
How to set only selected languages to bbb

### ISSUE THREAD

**Issue by raoden1** [bigbluebutton/bigbluebutton#10095]
Hi I saw that bbb has the option to override default locales: Issue  #8336 
But I would like to have only to selected languages.
How to do that?

Or should I add that as a feature request?

and  defualt messages in the chat when bbb is loaded could be added to translation?

**Comment by matiasilva** [comment]
You can set the default messages in your bigbluebutton.properties. As for the selected languages, I don't think this is implemented yet. Is there a particular use case you need that would prevent the users from selecting their language in the drop-down?

**Comment by raoden1** [comment]
Yes, I want to have only two languages supported. 
that user can select only english or german. 
Could you label this topic as feature request?

**Comment by matiasilva** [comment]
Ah I see. Is there any reason why the full list is not suitable? I'm just trying to gauge interest here: if the full feature already exists, why limit it?

**Comment by raoden1** [comment]
oh that you have on your mind. So, UE has specific restriction according to law. GDPR is not equal to US law and other countries.

**Comment by matiasilva** [comment]
Yes, @raoden1, I myself am based in the EU as well. My question was just to better understand your feature request. Why do you think it is needed? And since you raised the point, what does it have to do with GDPR?

**Comment by nguyenxuanhoa493** [comment]
set your languages in /usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml
delete json of languagues other

**Comment by matiasilva** [comment]
Merging with #10085
