### ISSUE TITLE
Facing web socket error while configuring external FreeSWITCH

### ISSUE THREAD

**Issue by terrificpanda** [bigbluebutton/bigbluebutton#10098]
Hi there,

We tried to configure external FreeSWITCH using the following link https://docs.bigbluebutton.org/2.2/customize.html#connect-bigbluebutton-to-an-external-freeswitch-server
But we are facing a web socket 1002 error.
Is there anything required to be done apart from this to solve this error 

Thanks & Regards

**Comment by basisbit** [comment]
For support requests, please use the [forum / mailing list](https://groups.google.com/forum/#!forum/bigbluebutton-setup). This issue tracker here is only for BBB development related issues. Sorry.
