### ISSUE TITLE
Users can't join meeting with network mobile 

### ISSUE THREAD

**Issue by BenzaminGM** [bigbluebutton/bigbluebutton#10093]
I config the server bbb, all good

but 

when a user to join a meeting using a mobile network (4G LTE, 3G) does not go from here
![screenshot_32](https://user-images.githubusercontent.com/35932359/87844200-4061bf80-c878-11ea-9e06-d5138ca89de3.png)

but 

when a user to join with network home ISP, yes can
![screenshot_33](https://user-images.githubusercontent.com/35932359/87844196-3b9d0b80-c878-11ea-8714-5326660d5837.png)

please, help

**Comment by matiasilva** [comment]
Hi, for support requests please use the instructions here: https://docs.bigbluebutton.org/2.2/getting-help.html. It looks like a TURN/STUN server issue.
