### ISSUE TITLE
Error 1020: Camera will not work unless connecting test bigbluebutton first

### ISSUE THREAD

**Issue by dpsec** [bigbluebutton/bigbluebutton#10094]
Hello, I have error 1020 issue so camera will not work, audio is ok but strange one and I have tried all the solutions written here.

The strange thing is that I can connect Video from my Office and 4G but when anybody is at home, it will give error 1020. I have my own trun/stun server which is working fine (tested), bigbluebutton has a direct internet (no firewall or NAT). It will work from home only after I connect test.bigbluebutton.org once, and after I connect back to my server it will work so somehow after my connect is successful to test.bigbluebutton.org, my server's video will work as well but why I am lost.

I've been trying to solve this since 1 week now and tried to avoid posting the same issue but I don't have any more ideas. 

Bigbluebutton version 2.2 running on Ubuntu 16.04.

Any ideas? Thanks in advance!

**Comment by ffdixon** [comment]
A few questions:

  * Are you by chance behind a router that connects you to the internet via IPV6?  
  * If you try multiple times (without trying test.bigbluebutton.org first), do some of the connections eventually succeed?  
  * Is there any difference between Chrome and FireFox?
  * If you put your home computer on a wireless hotspot (via you phone) does it connect right away?  

When you try via FireFox, do you see your TURN server as a relay candidate when you do about:webrtc.  Here's a screen shot of the TURN server that is offered when you go to https://test.bigbluebutton.org/. 

![image](https://user-images.githubusercontent.com/290351/87873512-1f8c8d80-c990-11ea-9d89-d441024aac55.png)

If you can post the answers to bigbluebutton-setup, see

  https://groups.google.com/forum/#!forum/bigbluebutton-setup

we'll follow-up there and, if there is a bug in BigBlueButton, we'll open an issue here to track it.

**Comment by dpsec** [comment]
Hello @ffdixon, thanks for your prompt reply. I will do the necessary tests and reply your questions on the google groups. 
Sorry to bother here. 

Regards!
