### ISSUE TITLE
Last User is not visible in the Meeting room when remaining time alert bar display on Top

### ISSUE THREAD

**Issue by premmohantyagi** [bigbluebutton/bigbluebutton#10102]
Last User is not visible in the Meeting room when remaining time alert bar display on Top
![meeting_remaining_time](https://user-images.githubusercontent.com/12059969/88087507-a6b34e80-cba6-11ea-913a-17f3ad4dbbca.png)

**Comment by sam-fls** [comment]
I am facing same issue
