### ISSUE TITLE
Connection failure (ICE error 1007)

### ISSUE THREAD

**Issue by rohitcoder** [bigbluebutton/bigbluebutton#10107]
**Describe the bug**
After stopping and starting multiple times EC2 server i got this error ICE error 1007 (During echo test), this also occured with my previous instance (i started that instance after 2 weeks), i wasn't able to fix this on previous server. So, i created new server with fresh installation and everything was working as expected, however when i stopped/started my server multiple times this occurred again...

I gone through previous github issues and some google group discussions but i wasn't able to find a good solution. 

**To Reproduce**
1. Create ec2 instance with bbb installation
2. Don't use elastic IP here.
3. Keep stopping and starting your server multiple times this may occur.

**Expected behavior**
User should not get this 1007 error

**Actual behavior**
Everytime user is getting 1007 error during echo test.

**Screenshots**
![Screenshot 2020-07-22 at 6 17 04 PM](https://user-images.githubusercontent.com/17665703/88178284-c6e71a00-cc47-11ea-9175-efdf6b419752.png)
This is my browser console log, you can see an error
![Screenshot 2020-07-22 at 6 26 39 PM](https://user-images.githubusercontent.com/17665703/88179076-f8141a00-cc48-11ea-8635-c455c216ef5f.png)

**Desktop (please complete the following information):**
 - OS: MacOS Catalina
 - Browser Chrome
 - Version 84.4.0.4147.89

I don't think i am having problem with my EC2 Firewall, i didn't change anything! and it was working before.
![Screenshot 2020-07-22 at 6 39 48 PM](https://user-images.githubusercontent.com/17665703/88180286-c2703080-cc4a-11ea-85e8-fdc88891243c.png)

**Comment by matiasilva** [comment]
Hi, what version of BBB is this? If it's 2.2.x, I invite you to post this in the forums: https://docs.bigbluebutton.org/2.2/getting-help.html#help-installing-or-running-bigbluebutton and close this issue

**Comment by rohitcoder** [comment]
Its 2.2.20

I am closing thread, and reposting there

**Comment by rohitcoder** [comment]
Just a note

If someone is also facing this same problem, you should move to elastic or fix single IP.
I wasn't using elastic ip because of which my IP was getting changed after each reboot.

**Solution***
1. Create new instance attach elastic IP
2. Re-installl BBB and now you can restart your instance n times
