### ISSUE TITLE
Hide All Interaction Buttons For Viewer (Only Cams and Presentation visible)

### ISSUE THREAD

**Issue by Harshit31** [bigbluebutton/bigbluebutton#10106]
I'm working on a solution where I'll take the stream of the user view and broadcast it using my own API's. 

I need some help on how to configure the views such that the viewer can only see the presentation and cams shared by the presenter. 

Any help would be highly appreciated.

**Comment by matiasilva** [comment]
Hi, see the development mailing list for such queries.
