### ISSUE TITLE
bbb-webrtc-sfu and etherpad are failed

### ISSUE THREAD

**Issue by erfanr** [bigbluebutton/bigbluebutton#10100]
**Describe the bug**
I just Installed BBB by following the manual installation on Ubuntu 16.04 server. When I run `bbb-conf --status`, I see everything ins active except bbb-webrtc-sfu and etherpad which are failed.
I also have an FQDN and installed Greenlight and SSL certificate from Let's Encrypt.
When I enter a meeting, evething is working except screen and webcam share.

**To Reproduce**

1. install ubuntu 16.04
2. follow manual installation instruction for BBB 2.2
3. set up an FQDN
4. set up an SSL certificate by following the instructions.
5. run `bbb-conf --status`
6. see the problem

**Desktop (please complete the following information):**
 - OS: Linux (Fedora 32)
 - Browser: Firefox and Brave

**Smartphone (please complete the following information):**
 - Device: Honor 10 Lite
 - OS: Android 10
 - Browser: Chrome

**Comment by ffdixon** [comment]
Can we get you to post this to bigbluebutton-setup and, if we find there is a problem with BigBlueButton we'll open an issue here to fix it. 

  https://groups.google.com/forum/#!forum/bigbluebutton-setup

Also, is it an option for you to install using [bbb-install.sh](https://github.com/bigbluebutton/bbb-install) which can automate the steps.  If you can do this on a second machine, you should have a working setup that you can compare with the first.
