### ISSUE TITLE
Typo in the Swedish Translations 

### ISSUE THREAD

**Issue by bittin** [bigbluebutton/bigbluebutton#10101]
Hello, not sure if this is the correct place to report typos in your L10n 
But for this sentence to be correct it should be "Hur skulle du vilja gå med med ljud? 
Think someone slant on the spacebar button, was about to report this during LGM - Libre Graphics Meeting end of May but forgot it until now and Online GUADEC  

![2020-07-21-181851_1600x900_scrot](https://user-images.githubusercontent.com/43197/88080288-27f6eb00-cb7f-11ea-8a43-cb38af4a7a35.png)

**Comment by pedrobmarin** [comment]
Hi @bittin 

This project uses Transifex to update it's internationalization https://docs.bigbluebutton.org/dev/localization.html. You can propose any changes in the swedish translations from there

**Comment by bittin** [comment]
> Hi @bittin
> 
> This project uses Transifex to update it's internationalization https://docs.bigbluebutton.org/dev/localization.html. You can propose any changes in the swedish translations from there

Could not see the string there however, but i can see it in the test instance, so maybe thats not updated or such?

**Comment by pedrobmarin** [comment]
Check if you are at the correct bigbluebutton's project. It should be named `BigBlueButton v2.2 HTML5 client`

**Comment by bittin** [comment]
> Check if you are at the correct bigbluebutton's project. It should be named `BigBlueButton v2.2 HTML5 client`

Yep could not find the string there :( 
![2020-07-23-101820_1600x900_scrot](https://user-images.githubusercontent.com/43197/88265578-0e17ee00-ccce-11ea-8f01-cc88097540cc.png)

But its both in the test tenant and the meet.gnome.org one wierd

**Comment by pedrobmarin** [comment]
I believe Transifex' default search only checks for the english match of the locale
![Screenshot_2020-07-23 BigBlueButton v2 2 HTML5 client Transifex Editor](https://user-images.githubusercontent.com/1778398/88278770-54af1d80-ccb9-11ea-97b1-d06701ee0c66.png)

**Comment by bittin** [comment]
> I believe Transifex' default search only checks for the english match of the locale
> ![Screenshot_2020-07-23 BigBlueButton v2 2 HTML5 client Transifex Editor](https://user-images.githubusercontent.com/1778398/88278770-54af1d80-ccb9-11ea-97b1-d06701ee0c66.png)

Did not know that, this is now, fixed so closing this 
Thanks :+1:
