### ISSUE TITLE
Download markers + pdf of presentation

### ISSUE THREAD

**Issue by cod3r0k** [bigbluebutton/bigbluebutton#10113]
Hi, when a presenter mark and plot different notes in each pdf of BBB, How can we download a PDF with their markers and notes in in it?

**Comment by matiasilva** [comment]
Hi @cod3r0k, thanks for your active participation. At present you cannot download the presentation with annotations on it. For further questions about using BigBlueButton, please use this link: https://docs.bigbluebutton.org/2.2/getting-help.html#help-using-bigbluebutton and post in the mailing lists. This place is for development and bugs only!
