### ISSUE TITLE
SIP dial-in username

### ISSUE THREAD

**Issue by some-admins** [bigbluebutton/bigbluebutton#10118]
I followed the instructions [here](https://docs.bigbluebutton.org/2.2/customize.html#add-a-phone-number-to-the-conference-bridge) and it basically works. But all the SIP dial-in users share the same username (the number they called). I would expect it to be their numbers respectively.

What did I miss?

As an alternative solution it would be nice for moderators to be able to rename participants.

**Comment by basisbit** [comment]
For support requests, please use the [forum / mailing list](https://groups.google.com/forum/#!forum/bigbluebutton-setup). This issue tracker here is only for BBB development related issues. Sorry.
