### ISSUE TITLE
Mobile speaker switch button

### ISSUE THREAD

**Issue by cod3r0k** [bigbluebutton/bigbluebutton#10110]
Hi, In some mobile version the audio is coming from ear speaker and the some how it coming from mobile speaker.
How could we have this switching? (like as skype )

Also, if there is some solution in near future update, what's your idea for now? could you help me?

**Comment by mrkeksi** [comment]
@antobinary is the "change audio I/O" only showing when more then one device is detected? Or is this dialog disabled on mobile.

**Comment by mariogasparoni** [comment]
hey @mrkeksi , this is disabled by default in mobile (we think mobile OSs already handle well the input/output devices).

If you just want to test it, you can switch your mobile to **desktop** mode: you will then see the audio device selector.
