### ISSUE TITLE
Support for Dynamic IP Address on each Restart for easy multi instance deployment (Using EC2 Images)

### ISSUE THREAD

**Issue by rohitcoder** [bigbluebutton/bigbluebutton#10116]
**Is your feature request related to a problem? Please describe.**
According to official BBB docs, it mentions BBB needs Elastic or Static IP before installation, but what if someone wants to use Dynamic IPs? (Cost effective in some cases)

One of the main problem is, having an option to change IP using any command. I built an AMI image from BBB ec2 instance and then tried to launch BBB from that Image but it wasn't working, after checking that new instance i figured that bbb is installed because of AMI but its having IP of previous EC2 instance, because of which new instance not works and it shows 404 error.

I also changed domain for new instance using ``bbb-conf --setip xxx.abc.com`` but still 404 error and Freeswitch was also having IP of previous instance.

**Describe the solution you'd like**
1. During installations of BBB it automatically fetches IP of instance and uses it for setup, it would be good if BBB updates it's IP for all modules like Freeswitch after each Restart
2. Or if its possible to provide new IP address using any new ``bbb-conf``` command. Which updates its IP address.

**Describe alternatives you've considered**
Tried changing IP address manually, but still it wasn't working.

**Additional context**
We just want to have an easy deployment process, like cloning instances and doing nothing else or maybe just update subdomain like ```bbb-conf --setip new.bbbdemo.com```

**Comment by maron2000** [comment]
I also use dynamic IP address, and use the following script to change all the settings.
First check your settings by ` sudo bbb-conf --check `
If you find any conflicts, you can use all or part of the following scripts.
Check what is in your respective configuration files before applying the scripts, or it will mess everything up.

Since my server is behind NAT, there are 2 variables ` $EXTERNAL_IP ` and ` $LOCAL_IP `
Please refer to https://docs.bigbluebutton.org/2.2/configure-firewall.html for what each line means.

After everything is done, restart bbb and nginx or simply reboot your server.

    EXTERNAL_IP = "your global IP address"
    LOCAL_IP = "your local IP address if behind NAT otherwise same as EXTERNAL_IP"
    DOMAIN_NAME = "your server host name (e.g. bbb.example.com)"
    sed -i "s/proxy_pass http.*/proxy_pass https:\/\/$EXTERNAL_IP:7443;/g" /etc/bigbluebutton/nginx/sip.nginx
    sed -i "s/\(  *ip:\).*/\1 $EXTERNAL_IP/g" /usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml
    sed -i "s/\(  *sip_ip:\).*/\1 $LOCAL_IP/g" /usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml
    sed -i "s/\(localIpAddress:\).*/\1 $LOCAL_IP/g" /usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml
    sed -i "s/\(name=\"wss-binding\"\).*/\1 value=\"$EXTERNAL_IP:7443\"\/>/g" /opt/freeswitch/etc/freeswitch/sip_profiles/external.xml
    sed -i "s/\"external_rtp_ip=.*\"/\"external_rtp_ip=$EXTERNAL_IP\"/g" /opt/freeswitch/etc/freeswitch/vars.xml
    sed -i "s/\"external_sip_ip=.*\"/\"external_sip_ip=$EXTERNAL_IP\"/g" /opt/freeswitch/etc/freeswitch/vars.xml
    sed -i "s/\"local_ip_v4=.*\"/\"local_ip_v4=$LOCAL_IP\"/g" /opt/freeswitch/etc/freeswitch/vars.xml
    sed -i "s/^ExecStart.*/ExecStart=\/sbin\/ip addr add $EXTERNAL_IP dev lo/g" /lib/systemd/system/dummy-nic.service;     #if behind NAT
    sed -i "s/.*$DOMAIN_NAME/$EXTERNAL_IP $DOMAIN_NAME/g" /etc/hosts        #if behind NAT

**Comment by rohitcoder** [comment]
You tried cloning your instance? Everything works for you after cloning and running this script in cloned instance?

**Comment by maron2000** [comment]
If the IP address is changed and domain name remains unchanged, it should work. 
I thought that was your first question.

And your second question, if you simply clone a working instance and run the above script, I expect it not to work, since I think each clone needs a different domain name.
If you change the domain name, you need a new SSL certificate, and change the settings regarding domain name that you find in ` sudo bbb-conf --check ` as well.
There might be a bunch of other things to do, so it think it more simple to initially run bbb-install for each fresh instance rather than cloning one.

> You tried cloning your instance? Everything works for you after cloning and running this script in cloned instance?

**Comment by severyanin-lub** [comment]
hello, friends!
This is my solution for BigBlueButton behind NAT + dynamic IP (I am using noip.org). Thanks maron2000 for good idea.
Local IP is fixed in my case.

1. First of all do this instructions: https://docs.bigbluebutton.org/2.2/configure-firewall.html#configure-bigbluebutton-to-work-with-your-firewall
All steps including dummy NIC interface creation with your actual in this moment external IP, **BUT** in _/opt/freeswitch/conf/vars.xml_ file this strings: 
```
<X-PRE-PROCESS cmd="set" data="external_rtp_ip=stun:stun.voipstunt.com"/>
<X-PRE-PROCESS cmd="set" data="external_sip_ip=stun:stun.voipstunt.com"/>
```
(any working public stun server - for example from [here](https://gist.github.com/mondain/b0ec1cf5f60ae726202e), but check it before using)
or:
```
<X-PRE-PROCESS cmd="set" data="external_rtp_ip=host:(insert_your_hostname.com)"/>
<X-PRE-PROCESS cmd="set" data="external_sip_ip=stun:(insert_your_hostname.com)"/>
```
seems to work prety well for me. I use first variant.

2. Then check all is working for you while external IP not changing

3. Make this script for automatic requesting external IP, changing IP in config files, dummy interface and BBB rebooting if it needs (if external IP matchs old IP - script will only echo that all is ok):

```
#!/bin/bash

echo "----------------------------"
date #for log
echo "----------------------------"

EXTERNAL_IP=`wget -q -4 -O- http://icanhazip.com`  # extrnal ip requesting
OLD_IP=`cat /etc/old_ip` # in this file storage old IP saved earlier
DUMMY_NIC=`ip addr | grep "$OLD_IP"` # for checking if dummy NIC interface is up 

echo "External IP  ": $EXTERNAL_IP 
echo "IP in configs": $OLD_IP 

if [ "$OLD_IP" = "$EXTERNAL_IP" ] # checking if ip used earlier in config files is actual
then
        echo "IP OK" #for log
        if [ "$DUMMY_NIC" != "" ] # when ip is actual, checking if dummy NIC is up with actual (old) IP 
        then
                echo "Dummy NIC intrface up"
        else
                echo "Dummy NIC intrface not working, setting up..."
                ip addr add $EXTERNAL_IP/32 dev lo
                echo "Sending bbb restart command"
                bbb-conf --restart
        fi
        echo " "
        echo "------------"
        echo "     OK"
        echo "------------"
        echo " "
else # Old IP is not actual. Changing IP in config files...

sed -i "s/proxy_pass http.*/proxy_pass https:\/\/$EXTERNAL_IP:7443;/g" /etc/bigbluebutton/nginx/sip.nginx
sed -i "s/\(  *ip:\).*/\1 $EXTERNAL_IP/g" /usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml
sed -i "s/\(name=\"wss-binding\"\).*/\1 value=\"$EXTERNAL_IP:7443\"\/>/g" /opt/freeswitch/etc/freeswitch/sip_profiles/external.xml
sed -i "s/post-up ip addr add.*dev lo/post-up ip addr add $EXTERNAL_IP\/32 dev lo/g" /etc/network/interfaces
sed -i "s/pre-down ip addr del.*dev lo/pre-down ip addr del $EXTERNAL_IP\/32 dev lo/g" /etc/network/interfaces
echo "all needed changes in config files are made"

echo $EXTERNAL_IP > /etc/old_ip # saving new IP - replacing old IP in file storage file

        if [ "$DUMMY_NIC" != "" ]  # checking if dummy NIC is up with old IP to stop it if needs
        then
        echo "Dummy NIC intrface up with old IP, deleting..."
        ip addr del $OLD_IP/32 dev lo
        fi

echo "Setting up Dummy NIC interface with new external IP"
ip addr add $EXTERNAL_IP/32 dev lo

sleep 3
echo "Sending bbb restart command"
bbb-conf --restart

echo " "
echo "-------------"
echo "IP changed OK"
echo "-------------"
echo " "

fi
exit 0
```
do not foget to make empty file for old IP storage:
`echo > /etc/old_ip`
And make script executable:
`sudo chmod +x /etc/your_script_name.sh`

you can also add this strings in the script if you do not want to use stun server:
```
sed -i "s/\"external_rtp_ip=.*\"/\"external_rtp_ip=$EXTERNAL_IP\"/g" /opt/freeswitch/etc/freeswitch/vars.xml
sed -i "s/\"external_sip_ip=.*\"/\"external_sip_ip=$EXTERNAL_IP\"/g" /opt/freeswitch/etc/freeswitch/vars.xml
```

4. check if script is working well for you after changing external IP

5. add script in /etc/rc.local for system startup running:
```
/path/to/your/script.sh >> /var/BBB_dynIP_status.log
exit 0
```
you can choose other file fol logs

6. use scheduled launch of script (remember that BBB will reboot, but only if IP changes), for example with cron:

`crontab -e`
add there (example for every minute):
```
* * * * * /path/to/your/script.sh >> /var/BBB_dynIP_status.log
0 0 * * * echo "log cleared" > /var/BBB_dynIP_status.log ; date >> /var/BBB_dynIP_status.log
```

and save it

Sorry for my bad english!
I will be happy if it will be helpfull!

**Comment by Proxy5** [comment]
> hello, friends!
> This is my solution for BigBlueButton behind NAT + dynamic IP (I am using noip.org). Thanks maron2000 for good idea.
> Local IP is fixed in my case.
> 
> 1. First of all do this instructions: https://docs.bigbluebutton.org/2.2/configure-firewall.html#configure-bigbluebutton-to-work-with-your-firewall
>    All steps including dummy NIC interface creation with your actual in this moment external IP, **BUT** in _/opt/freeswitch/conf/vars.xml_ file this strings:
> 
> ```
> <X-PRE-PROCESS cmd="set" data="external_rtp_ip=stun:stun.voipstunt.com"/>
> <X-PRE-PROCESS cmd="set" data="external_sip_ip=stun:stun.voipstunt.com"/>
> ```
> 
> (any working public stun server - for example from [here](https://gist.github.com/mondain/b0ec1cf5f60ae726202e), but check it before using)
> or:
> 
> ```
> <X-PRE-PROCESS cmd="set" data="external_rtp_ip=host:(insert_your_hostname.com)"/>
> <X-PRE-PROCESS cmd="set" data="external_sip_ip=stun:(insert_your_hostname.com)"/>
> ```
> 
> seems to work prety well for me. I use first variant.
> 
> 1. Then check all is working for you while external IP not changing
> 2. Make this script for automatic requesting external IP, changing IP in config files, dummy interface and BBB rebooting if it needs (if external IP matchs old IP - script will only echo that all is ok):
> 
> ```
> #!/bin/bash
> 
> echo "----------------------------"
> date #for log
> echo "----------------------------"
> 
> EXTERNAL_IP=`wget -q -4 -O- http://icanhazip.com`  # extrnal ip requesting
> OLD_IP=`cat /etc/old_ip` # in this file storage old IP saved earlier
> DUMMY_NIC=`ip addr | grep "$OLD_IP"` # for checking if dummy NIC interface is up 
> 
> echo "External IP  ": $EXTERNAL_IP 
> echo "IP in configs": $OLD_IP 
> 
> if [ "$OLD_IP" = "$EXTERNAL_IP" ] # checking if ip used earlier in config files is actual
> then
>         echo "IP OK" #for log
>         if [ "$DUMMY_NIC" != "" ] # when ip is actual, checking if dummy NIC is up with actual (old) IP 
>         then
>                 echo "Dummy NIC intrface up"
>         else
>                 echo "Dummy NIC intrface not working, setting up..."
>                 ip addr add $EXTERNAL_IP/32 dev lo
>                 echo "Sending bbb restart command"
>                 bbb-conf --restart
>         fi
>         echo " "
>         echo "------------"
>         echo "     OK"
>         echo "------------"
>         echo " "
> else # Old IP is not actual. Changing IP in config files...
> 
> sed -i "s/proxy_pass http.*/proxy_pass https:\/\/$EXTERNAL_IP:7443;/g" /etc/bigbluebutton/nginx/sip.nginx
> sed -i "s/\(  *ip:\).*/\1 $EXTERNAL_IP/g" /usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml
> sed -i "s/\(name=\"wss-binding\"\).*/\1 value=\"$EXTERNAL_IP:7443\"\/>/g" /opt/freeswitch/etc/freeswitch/sip_profiles/external.xml
> sed -i "s/post-up ip addr add.*dev lo/post-up ip addr add $EXTERNAL_IP\/32 dev lo/g" /etc/network/interfaces
> sed -i "s/pre-down ip addr del.*dev lo/pre-down ip addr del $EXTERNAL_IP\/32 dev lo/g" /etc/network/interfaces
> echo "all needed changes in config files are made"
> 
> echo $EXTERNAL_IP > /etc/old_ip # saving new IP - replacing old IP in file storage file
> 
>         if [ "$DUMMY_NIC" != "" ]  # checking if dummy NIC is up with old IP to stop it if needs
>         then
>         echo "Dummy NIC intrface up with old IP, deleting..."
>         ip addr del $OLD_IP/32 dev lo
>         fi
> 
> echo "Setting up Dummy NIC interface with new external IP"
> ip addr add $EXTERNAL_IP/32 dev lo
> 
> sleep 3
> echo "Sending bbb restart command"
> bbb-conf --restart
> 
> echo " "
> echo "-------------"
> echo "IP changed OK"
> echo "-------------"
> echo " "
> 
> fi
> exit 0
> ```
> 
> do not foget to make empty file for old IP storage:
> `echo > /etc/old_ip`
> And make script executable:
> `sudo chmod +x /etc/your_script_name.sh`
> 
> you can also add this strings in the script if you do not want to use stun server:
> 
> ```
> sed -i "s/\"external_rtp_ip=.*\"/\"external_rtp_ip=$EXTERNAL_IP\"/g" /opt/freeswitch/etc/freeswitch/vars.xml
> sed -i "s/\"external_sip_ip=.*\"/\"external_sip_ip=$EXTERNAL_IP\"/g" /opt/freeswitch/etc/freeswitch/vars.xml
> ```
> 
> 1. check if script is working well for you after changing external IP
> 2. add script in /etc/rc.local for system startup running:
> 
> ```
> /path/to/your/script.sh >> /var/BBB_dynIP_status.log
> exit 0
> ```
> 
> you can choose other file fol logs
> 
> 1. use scheduled launch of script (remember that BBB will reboot, but only if IP changes), for example with cron:
> 
> `crontab -e`
> add there (example for every minute):
> 
> ```
> * * * * * /path/to/your/script.sh >> /var/BBB_dynIP_status.log
> 0 0 * * * echo "log cleared" > /var/BBB_dynIP_status.log ; date >> /var/BBB_dynIP_status.log
> ```
> 
> and save it
> 
> Sorry for my bad english!
> I will be happy if it will be helpfull!

Hi,

thanks for the solution!
I added another line because it gives 1020 errors after ip change.

```
sed -i "s/externalIPv4=.*/externalIPv4=$EXTERNAL_IP/g" /etc/kurento/modules/kurento/WebRtcEndpoint.conf.ini
```

**Comment by maron2000** [comment]
@severyanin-lub 
Nice work!
FYI, I use stun server to obtain external IP.
```
STUN_SERVER="stun.l.google.com"
STUN_PORT="19302"
STUN_RESULT=$(stun $STUN_SERVER:$STUN_PORT -v 2>&1)
EXTERNAL_IP=$(echo "$STUN_RESULT" |& grep -m 1 "Mapped" | \
  grep -Eo '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}')
```

**Comment by angelaki** [comment]
Why does BBB need to know its external ip anyway? Cant it just listen on all ips? Like your idea of updating the ip on restart - but don't like the extra error source ...

**Comment by devZer0** [comment]
yes, please support running bbb with dynip.  lots of people have good quality home connection with lots of upstream bandwith nowadays, i don't see the point why we should not be allowed to run bbb there when we have no problem running other services there.   providers may still provide dynamic ip for home internet, which may change once a day on reconnect.

there should be no reconfigure/patch orgy when public ip is changing, and if there is no other solution besides patching configuration, it should be no 3rd-party script/hack but bbb builtin
