### ISSUE TITLE
Waiting room for multi-user consultations

### ISSUE THREAD

**Issue by wiedenhoeft** [bigbluebutton/bigbluebutton#10119]
Our clinic offers consultation services. The usual process is that there is a common waiting room, and whenever one of the consultants becomes available, the next person from the waiting room is called into that consultant's office. At the moment, we emulate this by having a public chat room, which we check for the next guest whenever we are done with a consultation and then send them a link to our BBB room as a private message. It would be nice if this procedure could be implemented in BBB: 

1. Create a queueing system for guests.
2. Let users (consultants) join a group which has access to this queue.
3. Allow consultants to add the guest on top of the queue to their BBB room, thereby removing the guest from the queue.

**Comment by matiasilva** [comment]
I think this would be handled better by a frontend. Is there any reason why such a feature should be in BBB and not say something like Greenlight?

**Comment by wiedenhoeft** [comment]
Absolutely, I was under the false impression that this was part of BBB.

**Comment by matiasilva** [comment]
Ah, great :) It's been a confusion of mine as well in the past. In any case, feel free (and I even encourage you to) stir up some discussion in the Greenlight repository. Closing for now but feel free to follow up in the development mailing lists.
