### ISSUE TITLE
Laggy and high latency keyboard in Android Chrome

### ISSUE THREAD

**Issue by HosseyNJF** [bigbluebutton/bigbluebutton#10122]
**Describe the bug**
On android's chrome browser, in the chat, when you start typing, you'll see that every typed letter will be shown into the text box aro und 0.5 seconds later.

**To Reproduce**
1. Open a session with 25 users online (I don't know if user count is important in this scenario but anyway)
2. Open public chat or a private chat and click the text box
3. Start typing something
4. You'll see the extreme lag when typing

**Expected behavior**
I expect that I'd be able to type fluently and without lag with the on-screen keyboard.

**Actual behavior**
Every letter that gets typed will be shown in the text box around 0.5 seconds later, and in this duration, the on-screen keyboard will become completely unresponsive.

**Screenshot**
I recorded a video of the lag [here](https://gofile.io/d/nlN5OY)

**BBB version (optional):**
I am a user of the server, can't get to know the server version.

**Desktop (please complete the following information):**
 The problem isn't present in desktop clients.

**Smartphone (please complete the following information):**
 - Device: Galaxy Tab A 10 (SM-T515)
 - OS: Android 9 (The problem is still here after upgrading the tablet to Android 10 although it got a little better)
 - Browser: Google Chrome
 - Version: 84.0

**Additional context**
The keyboard bug is the most obvious and annoying, but I can see the lag everywhere. all controls will respond to touch after a small delay (like 0.2 to 0.3 sec).

**Comment by matiasilva** [comment]
The number of participants does matter as the audio and video processing will be relying on your phone's performance. This is likely just due to poor phone performance, which is inevitable when the number of users increases beyond a certain point. How many video cams were being shared?

**Comment by HosseyNJF** [comment]
@matiasilva Of course, the performance of the phone isn't that good. It only has 2GB of ram. But I use Telegram and WhatsApp on the same device and I never felt any kind of lag like this while typing, It's just smooth.
0 Cams were being shared at that time; the only thing being shared was only one presentation.
I tested this on Firefox Android, and it performs a little better, but you still feel the lag.
