### ISSUE TITLE
Moving from presentation back to Whiteboard

### ISSUE THREAD

**Issue by cdilgard** [bigbluebutton/bigbluebutton#10120]
There doesn't appear to be a way to move from presenting an uploaded presentation back to the white board feature.  This movement back to the whiteboard would be very helpful for teachers.

**Comment by ffdixon** [comment]
Not sure what you are asking ... the whiteboard is an overlay on the presentation, so if you have the presentation visible, so are the whiteboard tools visible.

Are you looking to add blank slides to the current presentation so you have a blank area for whiteboard?

**Comment by cdilgard** [comment]
After I've uploaded a presentation (powerpoint for example), the blank presentation slides disappear.  How do I get rid of that powerpoint and get back to the blank default presentation slides so I can use my whiteboard tools again?
Thanks so much!

**Comment by mvasylenko** [comment]
You can set active presentation on "upload presentation" page by clicking on corresponding circle symbol. This applies also for default.pdf with blank pages.

In 2.3.x release, there is a second way to do it:
https://github.com/bigbluebutton/bigbluebutton/pull/8552

**Comment by matiasilva** [comment]
Excellent response! I'll close this issue seeing as a helpful response has been provided.
