### ISSUE TITLE
Guests are promoted to moderator when join at breakout room

### ISSUE THREAD

**Issue by aloisogomes** [bigbluebutton/bigbluebutton#10126]
Hi, i dont't know if this is an issue or an expected behaviour. 
but when a guest is issued join at breakout room. He will join with moderator privileges, where for instance, can turn muted all in the breakout room.

There are any way to keep participants privileges and hierarchy?

**Comment by matiasilva** [comment]
Hi @aloisogomes, thanks for your post. This forum is for development and bug fixes only, please use the mailing lists: https://docs.bigbluebutton.org/2.2/getting-help.html#help-using-bigbluebutton. Indeed the promotion to moderator is deliberate as in a smaller environment students can share their screen and so on.
