### ISSUE TITLE
Presenting

### ISSUE THREAD

**Issue by cdilgard** [bigbluebutton/bigbluebutton#10121]
After I've uploaded a presentation (powerpoint for example), the blank presentation slides disappear and only my powerpoint shows. How do I get rid of that powerpoint and get back to the blank default presentation slides so I can use my whiteboard tools again?
Thanks so much!

**Comment by matiasilva** [comment]
Hi @cdilgard! Thanks your involvement, but this place is for development and bug fixes. For general help with using BBB, I suggest following the instructions here: https://docs.bigbluebutton.org/2.2/getting-help.html#help-using-bigbluebutton

**Comment by cdilgard** [comment]
That would be great if the answer to my question was there, but it's not.  I've searched.  Google Meet for our district it is!

**Comment by matiasilva** [comment]
Hi @cdilgard. No need for such an attitude, I set aside some of my time to help you and I don't see why my comment merited such a response. I proposed that you email the users mailing list where many others like yourself have encountered such problems before and will be able to help you. There are people there that have used BBB for months and are quite willing to help. As for your question, I suggest you explore the presentation upload interface where you can select certain presentations.

**Comment by iSamof** [comment]
@cdilgard - if you do a search here in the 'issues' for "presentation" or similar you will find a number of relevant discussions. Here are two that seem to me to be close to what you are talking about ...
[https://github.com/bigbluebutton/bigbluebutton/issues/7852](https://github.com/bigbluebutton/bigbluebutton/issues/7852)
[https://github.com/bigbluebutton/bigbluebutton/issues/10082](https://github.com/bigbluebutton/bigbluebutton/issues/10082)

Check the sample for 7852 on the demo site from the link in the ticket. I think it does what you want.

I hope this helps.
