### ISSUE TITLE
Scale meeting over servers

### ISSUE THREAD

**Issue by aloisogomes** [bigbluebutton/bigbluebutton#10123]
Hi, Imagine the following scenario:

I) A balace server (Scalelite may be used)
II) A server (Called bbb1) with meeting A
III) Another idle server (called bbb2).

Fine, guests are came in and balance server deliver them to bbb1, but administrator want share this job. So "tell" to balancer deliver new joins to bbb2, it would be amazing!!

Participants in this scenario, will interact to each other as been in same server. Participant A under bbb1 interact directly with participant B under bbb2.

There are any way to achieve this world?

**Comment by matiasilva** [comment]
No, sadly. I've seen a similar question posted on the forums and it doesn't fit with BBB's modal. Very few meetings ever reach the limit of 100 recommended in the documentation so I think it would be better to spend time on making the majority of the meetings of a higher quality. I welcome you to continue this discussion if you have more ideas, but in the mailing lists please! https://groups.google.com/forum/#!forum/bigbluebutton-dev
