### ISSUE TITLE
Quick website access dropdown (which you can screen-share if needed)

### ISSUE THREAD

**Issue by hiroshisuga** [bigbluebutton/bigbluebutton#10124]
**Is your feature request related to a problem? Please describe.**
During presentation, you may want to share a website by screen share. For doing this, however, you need to open the browser, enter URL, and share the screen. It's tedious when you have many websites that you want to co-browse with students.

**Describe the solution you'd like**
Inspired by https://github.com/bigbluebutton/bigbluebutton/pull/9609 , I would like to have a quick website access dropdown. Any project ongoing?

**Describe alternatives you've considered**
It's also possible to directly screenshare the website that you have chosen from the dropdown list. But I'd prefer a simple solution of launching a new browser window, which you can share if needed. 

**Additional context**
I have written the PR. After a couple of testings, I will post it.

**Comment by ffdixon** [comment]
We have added the list of available presentations to the '+' menu on 2.3-dev


![image](https://user-images.githubusercontent.com/290351/88533324-1de84880-cfd4-11ea-98ea-6308cdecc7e8.png)


You can test this now on 

  https://test23.bigbluebutton.org/

See

  https://docs.bigbluebutton.org/dev/dev23.html

**Comment by hiroshisuga** [comment]
Hi @ffdixon , 
I love this feature!
I am afraid, however, that what I am saying is slightly different. 

![screenrecord](https://user-images.githubusercontent.com/45039819/88534304-c1704200-d042-11ea-9fb9-35e84ebd81b7.gif)
