### ISSUE TITLE
Option to display a photo if webcam stream is not enabled

### ISSUE THREAD

**Issue by VauHa** [bigbluebutton/bigbluebutton#10125]
In large meetings the use of webcams is often omitted in order not to run into bandwidth problems. In this case a user provided photo could help to improve the atmosphere of the meeting. One could think of several options:
- display the photo instead of the camera feed, either continuously or when the user is speaking
- show the photo in the participants list (even independant from the webcam stream)

**Comment by ffdixon** [comment]
This is a good suggestion -- we should have an 'avatar' mode for webcams, which displays either the webcam, initials, or avatar picture (if available).

**Comment by prlanzarin** [comment]
Duplicate of https://github.com/bigbluebutton/bigbluebutton/issues/13844 and related to https://github.com/bigbluebutton/bigbluebutton/issues/12481
