### ISSUE TITLE
bbb-conf complains about non-matching IPs if CNAME in use

### ISSUE THREAD

**Issue by uka-support** [bigbluebutton/bigbluebutton#10135]
**Describe the bug**
bbb-conf complains about non-matching IPs if servername is a CNAME DNS record.

**Installation type**
Installed using bbb-install

**Firewall and IP address type**
No NAT, just local ufw firewall, public IP.

**Console output**

    # IP does not match:
    #                           IP from ifconfig: <ip-redacted>
    #   /etc/nginx/sites-available/bigbluebutton: <servername-redacted>

**Additional context**

I traced the problem down to `check_configuration` function in bbb-conf. Our servers have an internal name and an CNAME alias in DNS:

    # host bbb.our-domain
    bbb.our-domain is an alias for internal-name.our-domain.
    internal-name.our-domain has address <public-ip>

This line (no 733 in 2.2.20) is the culprit:

    HOSTS=$($HOSTS $NGINX_IP | awk '{ print $4 }' | head -n 1)

change it to

    HOSTS=$($HOSTS $NGINX_IP | awk '/ alias /{next} { print $4 }' | head -n 1)

to filter out the line containing the alias.

**Comment by matiasilva** [comment]
Hi @uka-support. Thanks for catching this. Could you open a pull request to implement your changes?

**Comment by uka-support** [comment]
Sorry, I don't have the necessary development environment anywhere. Would have to set it up from scratch.

I supposed, one of the dev's could do this in a minute.
