### ISSUE TITLE
Which type of server is good for Bigbluebutton

### ISSUE THREAD

**Issue by BrizoTech-Labs** [bigbluebutton/bigbluebutton#10139]
Am new to bigbluebutton. When i select server it shows

SHARED CPU
DEDICATED CPU
CPU-Optimized
Memory-Optimized

May i know which type is good for bigbluebutton

**Comment by matiasilva** [comment]
Hello! Welcome, glad to see you explore BigBlueButton. Here's the documentation: https://docs.bigbluebutton.org/ which should have all the answers to your questions. You can always browse the mailing lists for experiences from system administrators that are deploying BBB to hundreds 👍
