### ISSUE TITLE
New red logout button in action-bar

### ISSUE THREAD

**Issue by amguirado73** [bigbluebutton/bigbluebutton#10131]
**Is your feature request related to a problem? Please describe.**

Some our users tell us than logout option is very hide. Besides, sometimes a moderator has use EndMeeting option instead of Logout option.  

**Describe the solution you'd like**
We have create a red logout button in the action bar (next to screenshare button) and delete this option from SettingDropDown (top-righ option). 

![RedButton](https://user-images.githubusercontent.com/65069983/88659343-2e341c80-d0d5-11ea-94bc-280b23843c0e.png)

You can enable/disable this logout button thanks to configuration file with option allowLogoutButton.

**Describe alternatives you've considered**
None

**Additional context**
I send you the code.

[parche_logout_button.txt](https://github.com/bigbluebutton/bigbluebutton/files/4987969/parche_logout_button.txt)

**Comment by antobinary** [comment]
Hi @amguirado73,
Is closing the browser tab an option? The button is always visible, there's consistency with other pages, etc.
The button you added in the screenshot looks nice and to me it's clear what it does but do we really need a third way to log out (close tab || menu -> logout || action button ) ?

**Comment by amguirado73** [comment]
Hello,

the button does the same as the option in the nav-bar/settings-dropdown. 
It does not close the browser. In fact, if the button is enabled, the 
menu option in nav-bar/settings-dropdown is disabled.
In this way, leaving the meeting would be accessible by a button but 
ending the meeting would still be where it is right now. So there are 
only 2 way to go out (close tab AND ( logout nav-bar OR action button)))

Regards

**Comment by antobinary** [comment]
Hi @amguirado73 ,

Could you please share more context - why would a user not rely on the 'close tab' button - maybe you redirect them to somewhere else in the same tab? Maybe you run BigBlueButton in a setup like an iframe where the 'close tab' is not visible, ...
Just would like to clarify on the need to log out and log out in 1 click.

**Comment by amguirado73** [comment]
Hello,

What our users ask us is not a 1 click button. What they really want is 
that it is not hidden in a
menu option. It is true that I have not contemplated confirmation on the 
button (I will work on it) but
really the question is not to look for a 1-click button but rather more 
simplicity for users.
Also, it is not the first time that a moderator ends the meeting 
erroneously. Thus, both functions
(logout and end meeting) would be clearly separated.

Regards

**Comment by iSamof** [comment]
Simplifying user actions is always a good idea and we like this exit button.

@amguirado73 - a confirmation would be very useful ... the position of the button is such that it is possible to click it by mistake. Thanks for your valued work.

**Comment by colorchestra** [comment]
Personally I agree that a visible logout button would be great. From a user perspective it has always felt weird to me to close the BBB browser tab or the window. In all other video call applications that I know (say, things like Skype, Facetime, Whatsapp, Teams...) there's a red logout button right there in the interface. None of those require you to close the app / the tab / the browser window. And other websites have trained users in the past to always log out before they close a tab, so it just feels wrong somehow. I hope this made sense.

**Comment by matiasilva** [comment]
I am not sure about this. The apps you mentioned are all chat apps while this is fundamentally a different tool. However, the design is quite elegant, so I'm tempted to vote in favor.

**Comment by iSamof** [comment]
We could be 100% right about some issue from a technical viewpoint but what really matters is what the user community thinks and how the market perceives that issue. As they say: "the perception of reality is more powerful than reality itself."

As @colorchestra nicely out, the user community is used to - I'd say "conditioned" to - expect certain buttons/functions. If there is not a big technical cost (e.g. performance hit or major structural change), why not give the users what they are used to. 

It has been said that "... familiarity breeds trust ..." and conversely make them jump thru hoops to achieve what they normally get with a red button, they will not disregard all the competition and confirm we are right "technically". They will moan about an "unorthodox/unusual/strange" way of doing things. Some of our users have said while acknowledging fundamentally BBB is excellent.
