### ISSUE TITLE
Showing welcome image of Nginix even after successfull instaltion of BB in AWS EC@

### ISSUE THREAD

**Issue by Arduinolearn** [bigbluebutton/bigbluebutton#10137]
I have installed the bbb  in aws ecs , and got no errors at all i have also attached the print screen

I am still only getting "Welcome to nginx!" when accessing through ip

**Comment by matiasilva** [comment]
Hi, for troubleshooting, please see the https://docs.bigbluebutton.org/. For further support, see the "getting help" section on those docs. This place is for development and bug fixes only 👍
