### ISSUE TITLE
Limit participants count for each session

### ISSUE THREAD

**Issue by Mrhalix** [bigbluebutton/bigbluebutton#10149]
Hey, I'm using moodle for creating sessions and managing them in bigbluebutton.
now I'm asking if it is possible to **control how many users can participate in a session**.
I'm a Python developer myself and I have some experience in editing codes of other programming languages in case this feature does not exist at the moment.
I'd be glad if you give me some help.
Thanks in advance.

**Comment by matiasilva** [comment]
Hi @Mrhalix, indeed it does! Take a look at the API documentation :) I'm not sure about Moodle, though.

**Comment by Mrhalix** [comment]
Oh, i just saw maxParticipants parameter in API Documention.
One more question, can you tell me where is the greenlight source located, so I can add this parameter in greenlight too.

**Comment by basisbit** [comment]
https://github.com/bigbluebutton/greenlight
