### ISSUE TITLE
Bigbluebutton photo for participants

### ISSUE THREAD

**Issue by heba27** [bigbluebutton/bigbluebutton#10141]
Is there an option in Bigbluebutton to enable participants to upload their photos to be displayed beside their names?

**Comment by iSamof** [comment]
Always a good idea to search the issue first to avoid duplicates, avoid extra work for the core team and avoid splitting the info and comments over multiple tickets. 

Have a look at this: [https://github.com/bigbluebutton/bigbluebutton/issues/10125](https://github.com/bigbluebutton/bigbluebutton/issues/10125)

**Comment by matiasilva** [comment]
@iSamof I believe this issue does not refer to that but rather the profile icon. Nonetheless, it is a duplicate: #8566, thanks!

**Comment by iSamof** [comment]
@matiasilva ... 

#8566 "image should appear in the User's list"
#10125 includes "show the photo in the participants list" in the 2nd bullet point

If I have misunderstood, I stand corrected.

**Comment by matiasilva** [comment]
Aha! You're right. The second point in the second PR achieves the same as the first though.

**Comment by iSamof** [comment]
OK, now I am lost! But I trust ya and bow to your superior knowledge :-)
