### ISSUE TITLE
Private chat gets disabled if opponent shortly left

### ISSUE THREAD

**Issue by iznakurnozh** [bigbluebutton/bigbluebutton#10145]
**Describe the bug**
When your opponent leaves the conference the private chat with her gets disabled and one cannot write anymore. If the opponent comes back the writing option stays disabled.

**To Reproduce**
1. Start a private chat with another user
2. Write something in the chat
3. Another user leaves -> writing option gets disabled
4. Another user comes back (with the same user name)
5. Writing option remains unavailable

**Expected behavior**
When your opponent comes back the writing option should be enabled again

**Desktop (please complete the following information):**
 - OS: Windows 10 pro
 - Browser Firefox 78.0.2 (64-Bit)

**Comment by matiasilva** [comment]
This is likely due to how your frontend creates "users" and thus the HTML5 client sees them as different people. What frontend are you using?

**Comment by iznakurnozh** [comment]
You are right, when the opponent writes sth - another instance of a private chat gets created. It was the staging.webconf01.uni-osnabrueck.de and webconf-ext04.uni-osnabrueck.de attending with an invitation link. However, it does not occur when just reloading page, but only when the opponent loggs out or clicks "back" in the browser and reenters from there.

**Comment by matiasilva** [comment]
Yeah, so it seems like a frontend issue. I'm closing this then.

**Comment by matiasilva** [comment]
Ah, I just realized this was you. I think I misunderstood this issue so I'm reopening it :)
