### ISSUE TITLE
Release Etherpad source

### ISSUE THREAD

**Issue by alangecker** [bigbluebutton/bigbluebutton#10159]
the last release (v2.2.21) contains some changes to etherpad, which I can't find anywhere on github, except on my repo made exactly for tracking these, otherwise invisible, changes :)
https://github.com/alangecker/bbb-packages/commit/9c16f8cb08cb231950ddd4dfdb7067770e2d97d9#diff-3897553ed154297d976620d3c2fdcd35

Currently it is not possible to build a working etherpad for BBB by yourself, because all the changes from the original one are closed source. This also leads to all the issues proprietary software includes, like no one external being able to contribute.

All I learned so far, that it must be based on this 1-year old `mconf` fork here:
https://github.com/mconf/etherpad-lite/tree/mconf

**Comment by ffdixon** [comment]
Here's the pull request for changes made to etherpad-lite

 https://github.com/bigbluebutton/etherpad-lite/pull/5

**Comment by alangecker** [comment]
a wired, I did not find this repo o.O
oke, sorry for opening this issue ;)
