### ISSUE TITLE
Delegation of meeting post-processing to other server

### ISSUE THREAD

**Issue by jbarberd** [bigbluebutton/bigbluebutton#10150]
Hi!

I've started to work with BBB with some very powerful instances on EC2.

Those instances are very expensive while they are powered on.

Doing some tests, it takes around 1:50h to process a 1 hour meeting on those instances.

So I was thinking about the possibility to delegate, in any way, all the meeting post-processing process to another server (cheaper one) that can do the job. Maybe transfering the raw files and the session files or something like that.

Is this possible in any way?

Many thanks!

**Comment by basisbit** [comment]
For support requests, please use the [forum / mailing list](https://groups.google.com/forum/#!forum/bigbluebutton-setup). This issue tracker here is only for BBB development related issues. Sorry.

**Comment by matiasilva** [comment]
See #9708. It is certainly possible :)

**Comment by jbarberd** [comment]
Many thanks!

It seems very tricky indeed :P

Cheers!
