### ISSUE TITLE
sharescreen with audio problem

### ISSUE THREAD

**Issue by cod3r0k** [bigbluebutton/bigbluebutton#10167]
**Describe the bug**
I have a problem when I want to share my sharescreen with audio. If I share the screen without the audio, it is OK but when I select to share the audio beside the screen, it cause the problem. (I do it in chrome)

**Comment by matiasilva** [comment]
Hi, for support requests please use our mailing lists.

**Comment by cod3r0k** [comment]
Thank you @matiasilva .  I want to join that like as you sent before, but no body accept my joining in there
