### ISSUE TITLE
How can we omit or trying to run faster audio connecting modal in joining step

### ISSUE THREAD

**Issue by cod3r0k** [bigbluebutton/bigbluebutton#10166]
Hi, I want to omit the audio connecting modal in joining step. 
It takes about 3 or 8 second . ( I force all to have microphone and mute them via moderator access)
But I don't want to showed that message to the audience.

**Comment by matiasilva** [comment]
Hi @cod3r0k, please have a read of the documentation that explains how to do this: https://docs.bigbluebutton.org/2.2/customize.html#html5-client. In the future, please post to the "user" mailing list.
