### ISSUE TITLE
unable to create '/home/bigbluebutton/.cache/dconf/user': Permission denied.  dconf will not work properly.

### ISSUE THREAD

**Issue by cod3r0k** [bigbluebutton/bigbluebutton#10164]
there is not any issue with creating a meeting. but there is a issue in my log file. what's this?

ERROR o.j.local.office.VerboseProcess - ERROR o.j.local.office.VerboseProcess - (process:8727): dconf-CRITICAL **: unable to create file '/home/bigbluebutton/.cache/dconf/user': Permission denied.  dconf will not work properly.

**Comment by matiasilva** [comment]
Hi @cod3r0k, for support please use the mailing lists. https://docs.bigbluebutton.org/2.2/getting-help.html#help-installing-or-running-bigbluebutton

**Comment by hex-m** [comment]
For others who find this, the latest discussion about this topic seems to be [here](https://groups.google.com/d/topic/bigbluebutton-setup/dxOiGVFchRE/discussion).
