### ISSUE TITLE
Participants limit for every moderator and its time limits

### ISSUE THREAD

**Issue by createoppurtuinities** [bigbluebutton/bigbluebutton#10160]
Hi Experts,

is it possible to include these features which will make BBB a much value added addition with these features?

1. Can we have participants limit with respective to every moderator?
2. Time limit set to individual user account?
3. Validity of every users account like monthly or yearly or days whatever it is?

**Comment by matiasilva** [comment]
Hi, I'm not sure what you mean with 1. 2 and 3 sound like a task for a frontend like Greenlight.

**Comment by createoppurtuinities** [comment]
i mean to say. I felt these functionalities need to be brought from both BBB and greenlight too. Hence raised the enhancement request here.

1. any moderator account who launches the meeting should have an option control how many number of participants are allowed under his moderator account.

2. Timelimit set to every meeting based on user account. for eg i have 2 user accounts acting as moderators. One can start the meeting and his meeting should end in 1 hour. Another user account starts the meeting can run for 5 hours or so what ever the timelimit we can set. Now the time limit set in BBB is valid for all user accounts in the BBB server instead of individual user accounts.

3. when the user account will expire like validity for 1 month or 1 year what ever we keep for account or we set an option this during the signup itself will be a great option.

4. we can also include an option in greenlight to have a package validity of 1 month or 3 months or 1 year such a kind of options which helps us for easy customization.

**Comment by matiasilva** [comment]
Hi, I will address 1 and 2 only as the other ones belong in the Greenlight repository. 

> any moderator account who launches the meeting should have an option control how many number of participants are allowed under his moderator account.

I don't quite understand here, sorry. No participants are "under" any moderator. The moderator is simply a user with heightened privileges.

> Timelimit set to every meeting based on user account

Is it not enough to ask them to leave the room? If they are kicked out by some timer, they could just as easily join back in. I think in most cases you can just agree with the moderators of the room that they should leave at a certain time, or you can remove them.

Perhaps I'm misunderstanding. It would be helpful for you to provide a use case.

**Comment by createoppurtuinities** [comment]
Yah, sure, 

Thought that BBB also need to have the settings or coding done where green-light will be dependent on underlying BBB.
Hence any moderator account who launches the meeting should have an option control how many number of participants are allowed under his moderator account, that will help a better control over the system in managing the users and moderators.

as off now i can see in BBB these settings like timer and number of participants are reflected to whole system.  for suppose if we have 100 users in the BBB server and if we keep an hour of timeout of the meeting it will be reflected to every user in the BBB server will end in 1 hour. if we can have a control over user account that our of 100 users i need only 10 users to have time limit of 1 hour and other 20 users i need to allow them the meeting time for 5 hours or so it will be helpful feature.

also if we check any commercial software platforms, everyone controls the number of participants based on hosts that is moderators. one moderator can have 100 participants limit or 50 participants limit. what i think it will have more control over the system rather then we depend on the settings which reflect the whole system and for new settings we might need to go for new server configuration if i am not wrong.
