### ISSUE TITLE
How to install bigbluebutton v2.2.2x (v2.2.20) from bbb-install.sh?

### ISSUE THREAD

**Issue by longlnk** [bigbluebutton/bigbluebutton#10168]
Hello,
Can I install bigbluebutton v2.2.20 from bbb-install.sh?
I currently install it from the software to the latest version v2.2.21
![install](https://user-images.githubusercontent.com/15074179/89028700-1a97e880-d357-11ea-814c-2b30dc955a99.png)
I'm developing on and using version 2.2.20, because it's stable
Please help me.

**Comment by matiasilva** [comment]
Hi @longlnk, 2.2.x is stable and you will find that only minor changes which are unlikely to affect your development have happened. In any case, a bit of searching on the issue tracker never hurts: #9508.
