### ISSUE TITLE
STUN server

### ISSUE THREAD

**Issue by cod3r0k** [bigbluebutton/bigbluebutton#10165]
Do we need any STUN-Server? for FREESWITCH . Why?

I have one turn server. but when I check bbb-conf --check , I found that there is a foreign ip `stun.freeswitch.org`. Do I must change them?

```
/opt/freeswitch/etc/freeswitch/vars.xml (FreeSWITCH)
                       local_ip_v4: xxx.xxx.xx.xxx
                   external_rtp_ip: stun:stun.freeswitch.org
                   external_sip_ip: stun:stun.freeswitch.org

```

**Comment by matiasilva** [comment]
Hi @cod3r0k, please see the docs.bigbluebutton.org/ docs for this information.
