### ISSUE TITLE
A popup near the mute button to indicate if the user is speaking but muted

### ISSUE THREAD

**Issue by akshayrvnkr** [bigbluebutton/bigbluebutton#10161]
### Problem
Many a times user is unaware of the fact that he/she is muted and starts speaking. It would be helpful to indicate to the user (like that done by Google meet) that he/she might be speaking (input > typical threshold for a defined interval of time), so that the user can promptly unmute in such a case

### Solution
Show a popup near the mute button like the following:
![image](https://user-images.githubusercontent.com/7658939/88954551-31d3c900-d2b8-11ea-823f-211c2c32412d.png)

**Comment by matiasilva** [comment]
Hi, see #9851. This is already implemented in the `develop` branch for 2.3.
