### ISSUE TITLE
bbb 2.3-dev: port range for kurento media server not defined as in bbb 2.2

### ISSUE THREAD

**Issue by spblinux** [bigbluebutton/bigbluebutton#10163]
**Describe the bug**
Server behind nat udp 16384-32768 opened. Local client shares webcam. Remote client sees spinning symbol instead of shared webcam image. - Comparing with bbb 2.2 reveals that in _/etc/kurento/modules/kurento/BaseRtpEndpoint.conf.ini_ the setting **minPort=24577** and **maxPort=32768** is missing. As soon as this setting has been applied, shared webcam image is shown.
(Additionally stunServerAddress and stunServerPort has been set in _/etc/kurento/modules/kurento/WebRtcEndpoint.conf.ini_)

**Installation type**
Did you install manually or did you use the bbb-install script? Script install. Lets encrypt secured.

**Firewall and IP address type**
Is your server behind a NAT or firewall? Does your BBB server have its own IPv4 address? 
Behind NAT, accessible by public ipv4 address.

**Console output**
...
Enable Firewall and opening 22/tcp, 80/tcp, 443/tcp and 16384:32768/udp
...
BigBlueButton Server 2.3.0-dev (1044)

**Additional context**
dpkg -l | grep bbb-html5: 1:2.3.0-1008
Tested with bbb moodle integration (2.3.4). - Audio, video and default slides work!

**Comment by maron2000** [comment]
I also found that the port range setting was missing in `/etc/kurento/modules/kurento/WebRtcEndpoint.conf.ini`.
I added the following 2 lines as well.
`minPort=24577`
`maxPort=32768`

version: bbb 2.3.0-dev (1324) alpha-2

**Comment by prlanzarin** [comment]
@maron2000 WebRtcEndpoint.conf.ini doesn't handle the minPort/maxPort configuration options. It's restricted to BaseRtpEndpoint.conf.ini (from which WebRtcEndpoint.conf.ini depends on), so that's not a valid thing.

**Comment by prlanzarin** [comment]
cc @ffdixon since we're back to building KMS again in 2.3, are we setting the minPort/maxPort configs in packaging and/or bbb-install?

**Comment by prlanzarin** [comment]
I'll take the lack of response or further reports of this behavior as a "_it's probably fixed_"
