### ISSUE TITLE
Failure on call (reason = incompatible SDP) (error 1004)

### ISSUE THREAD

**Issue by ParthMacron** [bigbluebutton/bigbluebutton#10174]
I am getting this error "Failure on call (reason = incompatible SDP) (error 1004)" on chrome when i am trying to run on incognito window chrome it's working fine. I cleared the cache and every possibility still getting this issue. For more investigation i run https://test.bigbluebutton.org/ where no error is coming . I am using latest big blue button . What should i do. This problem sucks.

**Comment by matiasilva** [comment]
Hi @ParthMacron, for support please see https://docs.bigbluebutton.org/2.2/getting-help.html#help-installing-or-running-bigbluebutton for how to get help.

**Comment by ParthMacron** [comment]
I already go through with all doc but didn't find any solution also when more than two participants voice issue coming a lot.

**Comment by matiasilva** [comment]
You can also ask in the mailing list :)

**Comment by ParthMacron** [comment]
Where should i mail and where is mailing list

**Comment by matiasilva** [comment]
In the link I posted above

**Comment by ParthMacron** [comment]
You shared nothing its just a doc don't post like this when u cannot help it .
