### ISSUE TITLE
Improve user list and chat export file names

### ISSUE THREAD

**Issue by matiasilva** [bigbluebutton/bigbluebutton#10170]
**Is your feature request related to a problem? Please describe.**
The export functionality for the chat and user lists currently names the files "public-chat-9898392829.txt". This is not very user friendly or descriptive.

**Describe the solution you'd like**
I was considering naming it very similar to the client title, so "BigBlueButton-Room Name". Perhaps we could add a timestamp or omit the BigBlueButton. We can make good use of the Meteor settings here.

I'm willing to submit a PR for this, but would be interested in people's thoughts first.

**Comment by iSamof** [comment]
Great idea. And yes date/time stamp in the file name would be very helpful in the format:
<Room-Name>_<International-Date-Format>_<Start-Time>.txt

Example: GreenRoom_2020-07-31_15-30.txt

I'd say in classroom and educational situations, the moderator's name in the title would make it even more user-friendly:
<Room-Name>_<Mod-Name>_<International-Date-Format>_<Start-Time>.txt

**Comment by matiasilva** [comment]
There are also some HTML tags present in the saved chat as noted in the issue above.
