### ISSUE TITLE
Annotate a Video

### ISSUE THREAD

**Issue by paulraper** [bigbluebutton/bigbluebutton#10179]
**Is your feature request related to a problem? Please describe.**
Currently, when you show a video, you can not show a given problem. What would be really cool is if you could draw on videos.

**Describe the solution you'd like**
You could freeze the video at a given point, and then draw lines on the video, write text and show with free hand lines what the issue is at that point in the video.

**Describe alternatives you've considered**
There are some, but they are too complex.

**Comment by matiasilva** [comment]
I will note that #5835 exists, but it is related to screensharing. Given the current way the videos are played (via the react-player) package, I would find it quite impractical for one to be able to pause and draw on top of them.

**Comment by paulraper** [comment]
I'm not sure that impractical is the problem, as in terms of the idea, it would be extremely practical for the user, and deadly useful. Many has been the time when showing something to students and I have wished I could draw onto the video to show the students precisely what I mean about a particular issue. However, I do accept that making such an idea work would be challenging. ;-)
