### ISSUE TITLE
Echo of the person speaking when  Select Phone Models Users Join the Call

### ISSUE THREAD

**Issue by sraja415** [bigbluebutton/bigbluebutton#10177]
**Describe the bug**
When a user with Phone Models Redmi 4 to 7 and Oppo and other models join a call, the other users will hear the person speaking with echo. Example if i speak, all the users including me will hear myself speak in an echo (glaring and loud). If you MUTE that user with those specific phone models the conversation is smooth without any issue.

The issue persists even if the user uses a headset. 

**Expected behavior**
Echo should be cancelled and mic needs to be adjusted

**Smartphone (please complete the following information):**
 - Device: Redmi Note 4,5,6,7, Oppo Series Phones also
 - OS:Android
 - Browser All Browsers
 - Android Version 6 to 8 (that i know of)

**Additional context**
If need be I can help in getting these users on a call using the BBB Test server for you to look at and solve the issue.

THIS IS HIGH Priority as even 1 user joining the call will spoil the whole meeting for others. 

Many have reported the issue without knowing why this occurs, I have pin pointed it to those phone models and their Mic. 

https://github.com/bigbluebutton/bigbluebutton/issues/7862

**Comment by basisbit** [comment]
I'd suggest you to create a bug report for this at the bug-tracker of your webbrowser.

**Comment by sraja415** [comment]
Pardon my ignorance. Can you please give me the steps on how to use Bug-Tracker from browser? I am also assuming you would want it from the phone that is causing the issue. So how do I do that from that phone so that I can explain to that phone owner what to do. thanks.

**Comment by sraja415** [comment]
Just to add something I noticed...when I talk...the phone user's name is also highlighted in BBB like he/she is talking...which seems to be cause of the issue. Example lets say A is the owner of redmi phone..and B talks..A's name is also showing like he is talking....hence the echo. Checked with multiple Redmi phones.

**Comment by matiasilva** [comment]
What @basisbit is proposing is that you open a bug report in the web browser that you're using. If you're using say Firefox, you would open it at https://bugzilla.mozilla.org/.

**Comment by sraja415** [comment]
@matiasilva @basisbit this bug occurs in all browsers. This is NOT a browser issue. This is a phone issue and how BBB handles echo and cancellation. I have reported this issue in Group and I was told to play with these settings...

https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/bigbluebutton-dev/MsJVVYVMSQw/4DA14qnPAgAJ

Have a look at these. They can be applied to BBB's client-side audio impl.:
https://developer.mozilla.org/en-US/docs/Web/API/MediaTrackSettings/echoCancellation
https://developer.mozilla.org/en-US/docs/Web/API/MediaTrackConstraints/echoCancellation
https://developer.mozilla.org/en-US/docs/Web/API/MediaStreamConstraints/audio
https://developer.mozilla.org/en-US/docs/Web/API/MediaTrackSettings/noiseSuppression

I wish I knew how to do these. I am not a coder and hence reporting as a bug. 

Thanks.

**Comment by basisbit** [comment]
@sraja415  BBB tells the webbrowser to do echo cancellation by default. If that causes problems, it is usually either a bug in the webbrowser, or - in this case here - a faulty driver or hardware implementation from the manufacturer.

**Comment by sraja415** [comment]
@basisbit I thought as much and even found forums which spoke of a similar issue. The one question I am unable to get answer is - why this issue does not occur in commercial software’s or how they have handled it? Hence my thought on MCU ..which I was told is not the answer. Can we find an answer together? Like I said I can get multiple devices with this issues onto a meeting if need be to find root cause?

**Comment by xlbs-rm** [comment]
> Why does the issue occur only in BBB and not in Zoom or Meet? WhatsApp calling...no issue....

I agree with sraja415 the problem only exist on BBB not in zoom, jitsi or Ms Teams, seams the audio Implementation is to blame.
To say it clearly: it only happen if the speaker uses microphone & computer speakers, extern speakers (not laptop build in) make it more terrible. If the speaker uses headset it works.
Unfortunatly not useable for an elementary school class! 
The only way to use it without headset is only one person is unmuted, but good conversations and discussions are not possible.
This is not the technical state of the art in 2021 - Please improve it! The Features are quite good/usefull: OpenSource, Whiteboard, BreakOut Rooms...

**Comment by prlanzarin** [comment]
https://github.com/bigbluebutton/bigbluebutton/pull/11143

If there's another 2.2 release before 2.3, this will land. Then you can tune the audio constraints (including echo, gain, noise control).
