### ISSUE TITLE
Error 401 when redirecting autojoin 

### ISSUE THREAD

**Issue by RamsinChaabian** [bigbluebutton/bigbluebutton#10175]
I Followed [this document](https://docs.bigbluebutton.org/2.2/install.html) for installed BBB in the ubuntu local server,
and implementation [API]( https://docs.bigbluebutton.org/dev/api.html ) but I couldn't auto-join to the room
![Untitled](https://user-images.githubusercontent.com/18450054/89100394-e5999d80-d40b-11ea-89f6-9fb6e6e95b9d.png)

But URL link works well in XML redirect
![Untitled2](https://user-images.githubusercontent.com/18450054/89100483-84be9500-d40c-11ea-98ef-0a7fcc77162a.png)

I think I must use **auth_token** for auto-join but where?

**Comment by matiasilva** [comment]
It looks like you're running your server on your local network. You need an external server with a proper ipv4 address. For support, see this document: https://docs.bigbluebutton.org/2.2/getting-help.html#help-installing-or-running-bigbluebutton
