### ISSUE TITLE
in new update (2.2.21) is is necessary to --setip again

### ISSUE THREAD

**Issue by mailalaki** [bigbluebutton/bigbluebutton#10176]
after spending a lot of time, i realized in new update (2.2.21) is necessary to --setip again, because it stucks in the echo test section!

**Comment by mailalaki** [comment]
> 
> 
> after spending a lot of time, i realized in new update (2.2.21) is necessary to --setip again, because it stucks in the echo test section!

probably for this:
![Capturesdfds](https://user-images.githubusercontent.com/13551603/89101868-424f8500-d419-11ea-8cf1-923bac7f04a2.PNG)

**Comment by ffdixon** [comment]
When doing a manual upgrade (not using [bbb-install.sh](https://github.com/bigbluebutton/bbb-install), the docs state that you need to so a `sudo bbb-conf --setip` as part of the upgrading steps, see

  https://docs.bigbluebutton.org/2.2/install.html#upgrading-from-bigbluebutton-22

**Comment by sreegithck** [comment]
if we do sudo bbb-conf --setip then will the echo hang problem get solved?

**Comment by ffdixon** [comment]
You need to *always* do a `bbb-conf --setip` after a manual upgrade.  After that, let's see if you still get the issue with connecting audio (it should work).

**Comment by sreegithck** [comment]
Yes it is working thank you

**Comment by derek-shnosh** [comment]
@ffdixon I had the same issue today after an `apt upgrade`, the `bbb-conf --setip` command cleared it up... thanks!

**Comment by matiasilva** [comment]
I'm closing this issue as it has been solved. Thanks a lot folks. This will serve as a reference for all those who encounter the same problem again.
