### ISSUE TITLE
Ask confirmation if meetings are currently going on before restart operations

### ISSUE THREAD

**Issue by carroarmato0** [bigbluebutton/bigbluebutton#10187]
**Is your feature request related to a problem? Please describe.**
During an onboarding session organized using BBB, I executed  bbb-conf --clean.
This stopped BBB to clean up the logs, and consequently, stopped the meetings.

**Describe the solution you'd like**
The bbb-conf --clean could query the API to check if there are no meetings currently taking place. 
If not? -> go on without confirmation.
If so? --> prompt to ask if you're sure you want to perform the operation.

**Describe alternatives you've considered**
I've considered letting the coffee work its magic before performing operation and running commands without checking the help to understand what they are going to do. But it's early in the morning.

**Comment by matiasilva** [comment]
I am of the opinion that any such operations should not be done on a production server when users are potentially using it. Monitoring can help tell you this.

**Comment by carroarmato0** [comment]
> I am of the opinion that any such operations should not be done on a production server when users are potentially using it. Monitoring can help tell you this.

I think it's a similar situation (though less dramatic than) as with “rm -fr /”. Do you always assume the user using it knows what they are doing and just executing it knowing that it can cause downtime? Or do you warn the user to confirm that this is really what they want?  I think it's a reflection of how user-friendly you want to make something.

And I fully agree I shouldn't have run that in production and should have checked through monitoring :) Accidents happen.

**Comment by matiasilva** [comment]
Yeah, fair enough. I think CLI tools should take the "rm -fr" approach but it'd be interesting to hear other people's thoughts.

**Comment by hex-m** [comment]
From an admin-perspective I don't think the users in a meeting should decide if a maintenance-task should happen. It would be enough to inform the users, that the server is going down and that they should restart their meeting when that happens.

The easiest way to make such "Server Notices" possible would probably be sending chat messages via API. https://github.com/bigbluebutton/bigbluebutton/issues/10937
