### ISSUE TITLE
tomcat8 start failure (2.3-dev on Ubuntu 18.04)

### ISSUE THREAD

**Issue by maron2000** [bigbluebutton/bigbluebutton#10186]
**Describe the bug**
tomcat8.service fails to start on boot (or when I manually start it with `` /etc/init.d/tomcat8 start ``)
The output of `` systemctl status tomcat8.service `` found below says that tomcat8 is not installed,
however, it is actually installed according to `` dpkg -l  | grep tomcat``
rc  tomcat8                                    8.5.39-1ubuntu1~18.04.3                          all          Apache Tomcat 8 - Servlet and JSP engine

**Installation type**
Executed bbb-install.sh on a freshly installed Ubuntu 18.04 (VMware guest on a Windows10 host)
`` wget -qO- https://ubuntu.bigbluebutton.org/bbb-install.sh | bash -s -- -v bionic-230-dev -s (my domain name) -e (my e-mail address) -d -g ``
No errors found in `` bbb-conf --check `` 

BigBlueButton Server 2.3.0-dev (1044)
  Kernel version: 5.4.0-42-generic
  Distribution: Ubuntu 18.04.4 LTS (64-bit)
  Memory: 16370 MB
  CPU cores: 4

 Potential problems described below
 IP does not match:
                           IP from ifconfig: 192.168.X.X
   /etc/nginx/sites-available/bigbluebutton: www.mydomain.com

 Warning: The setting of XX.XX.XX.XX for proxy_pass in

    /etc/bigbluebutton/nginx/sip.nginx

 does not match the local IP address (192.168.X.X).
 (This is OK if you've manually changed the values)

**Firewall and IP address type**
behind a NAT

**Console output**

 ●tomcat8.service - LSB: Start Tomcat.
    Loaded: loaded (/etc/init.d/tomcat8; generated)
    Active: failed (Result: exit-code) since Mon 2020-08-03 12:14:38 JST; 22s ago
      Docs: man:systemd-sysv-generator(8)
   Process: 7050 ExecStart=/etc/init.d/tomcat8 start (code=exited, status=1/FAILURE)

  Aug. 03 12:14:38 ubuntu systemd[1]: Starting LSB: Start Tomcat....
  Aug. 03 12:14:38 ubuntu tomcat8[7050]:  * tomcat8 is not installed
  Aug. 03 12:14:38 ubuntu systemd[1]: tomcat8.service: Control process exited, code=exited stat
  Aug. 03 12:14:38 ubuntu systemd[1]: tomcat8.service: Failed with result 'exit-code'.
  Aug. 03 12:14:38 ubuntu systemd[1]: Failed to start LSB: Start Tomcat.. 

**Additional context**
I reinstalled tomcat8 by the following commands, and now the status is active.
`` sudo apt purge tomcat8 ``
`` sudo apt-get install tomcat8 ``

I'm just wondering if this matter is some kind of a defect in bbb-install.sh.

**Comment by GhaziTriki** [comment]
@maron2000 Tomcat should only be installed if you install `bbb-demo` package. In 2.3, all VMS applications will be reviewed.

**Comment by maron2000** [comment]
@GhaziTriki Actually, I installed and uninstalled `` bbb-demo ``, so that may be the problem.
Anyway, I'll uninstall tomcat if it is not going to be used besides `` bbb-demo ``.
Thank you for confirming!
