### ISSUE TITLE
Override lock features if user is promoted to presentator.

### ISSUE THREAD

**Issue by ryprfpryr** [bigbluebutton/bigbluebutton#10181]
We are using "See only moderator webcam" lock on students so they cannot see each other. Sometimes they have to present or give a lecture so other students have to see his/her webcam. 

The only solution right now is to promote the student to moderator, but this is not ideal because he/she could accidentally or intendedly stop recording, finish the meeting... etc.

Suggested fix: 
1- a. When a user is promoted to presentator, his camera should be visible to everyone (but still cannot moderate the meeting).
1- b. This fix also should allow to have multiple presentators -- this is very important for scenarios like when we have groups or teams giving a lecture for the rest of spectators / students.

**Comment by matiasilva** [comment]
1a) seems like a good idea. 1b) however is a much more far-reaching change that isn't a simple patch. I suggest looking at #9152 which essentially asks for the same thing.
