### ISSUE TITLE
See other participants videoStats

### ISSUE THREAD

**Issue by ryprfpryr** [bigbluebutton/bigbluebutton#10184]
Moderator should get the banner alert when one of the participants has network/video connection issues as well.

![image](https://user-images.githubusercontent.com/68156081/89133367-9fb70500-d4f1-11ea-9dc0-f2406f578b72.png)

**Comment by demyasha** [comment]
Is there a possibility for moderator to see participants network/video connection statuses?

**Comment by ryprfpryr** [comment]
@demyasha yes you can enable it with enableVideoStats and enableNetworkMonitoring set to true in /usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml

It would really great to be able to have the signal bars indicator icon next to each user ONLY, and being able to remove the warning banner. At some point it can be distracting or confusing 

@matiasilva what's your opinion about this?

**Comment by pedrobmarin** [comment]
We included this extra view at 2.3 https://github.com/bigbluebutton/bigbluebutton/pull/8579

**Comment by ryprfpryr** [comment]
Thanks @pedrobmarin 🚀
