### ISSUE TITLE
problem in Shared External Video on IOS and SAFARI

### ISSUE THREAD

**Issue by mailalaki** [bigbluebutton/bigbluebutton#10192]
when share external video by URL, users using IOS and SAFARI will not be able to watch the video and will see something like this:
![WhatsApp Image 2020-08-01 at 21 42 46](https://user-images.githubusercontent.com/13551603/89239244-e39f2c80-d60d-11ea-8daa-a5fdc46e4d09.jpeg)

What is the problem!?
(bbb version is 2.2.21)

**Comment by ffdixon** [comment]
Can you duplicate this issue on https://demo.bigbluebutton.org/.

**Comment by mailalaki** [comment]
hi @ffdixon , I checked this further. Apparently, when the link refers to the download, instead of streaming and playing, this problem occurs in smartphones (IOS/Android). But on PC, in some versions of Chrome, only this problem exists and in other cases it works properly.

**Comment by pedrobmarin** [comment]
Check if the media you are sharing is supported by the browsers you are trying to access with
