### ISSUE TITLE
Unable to connect to port 1935

### ISSUE THREAD

**Issue by ryprfpryr** [bigbluebutton/bigbluebutton#10190]
Steps to reproduce (Digital Ocean):

1- Create droplet 
2- Assign floating ip
3- Create A record in Cloudflare with floating IP
4- Install latest BBB-install.sh (with -w value)

Setup error message:
#- Error: Unable to connect to port 1935 (RTMP) on bbb.host.com

#- If ufw is disabled error message disappears:
5- ufw disable
6- bbb-conf --check
7- Error message gone

#- If ufw is enabled, same error message output.

**Comment by matiasilva** [comment]
Hi, is this a support request? A bug report?

**Comment by ffdixon** [comment]
You don't need port 1935 (RMTP) as the Flash client is no longer used, so you can ignore that.  In the upcoming BigBlueButton 2.3, we've revmoved the install of the Flash client.

**Comment by ryprfpryr** [comment]
Thanks Fred. We'll ignore this output on bbb-conf --check then. Regards.

**Comment by matiasilva** [comment]
Hi @ryprfpryr, glad to hear your issue has been solved. Are you happy to close this issue then?

**Comment by ryprfpryr** [comment]
Yes Matias of course, thank you.
