### ISSUE TITLE
Saved shared notes and chat files do not have meaningful names

### ISSUE THREAD

**Issue by iznakurnozh** [bigbluebutton/bigbluebutton#10202]
**Describe the bug**
label:"User Experience (UX)" 

Files saved from shared notes and public chat look as following:
![image](https://user-images.githubusercontent.com/38284875/89470876-187dc180-d77d-11ea-82f1-f1d5d35fdd4e.png)

**Expected behavior**
The name of the session or seminar and current date would be more informative

**Additional context**
Also inside a saved public chat file there are some html tags. Deleting the welcome-message might solve this issue as this content is not very informative after a meeting. Right now a saved file looks as following:
![save_public_chat](https://user-images.githubusercontent.com/38284875/89471323-22ec8b00-d77e-11ea-97fa-5ff4535334d4.png)

**Comment by matiasilva** [comment]
Hi @iznakurnozh, I remembered this from the call and I already opened the issue here:  #10170 so I'm merging this one with that one :-)
