### ISSUE TITLE
Some english text within german version

### ISSUE THREAD

**Issue by iznakurnozh** [bigbluebutton/bigbluebutton#10201]
**Describe the bug**
label:"User Interface (UI)"

1. In the German Interface the chat message contains both German and English text.
2. Drop-down menu in the "share webcam" dialog are in English

**To Reproduce**

1. In the (German) conference room click on "Share webcam" and confirm when asked by browser for permission. After confirming see the dialog with English drop-down menu
2. In the (German) conference room read the welcome message in chat: the 2nd part is in English. (depending on version) it says how to join a meeting by phone or how to invite someone with a link.

**BBB version (optional):**
968, 980

**Comment by matiasilva** [comment]
Hello! All translation is done with Transifex. You can create an account on there and join the team for the 2.2 or 2.3 client and submit corrections there.

**Comment by antobinary** [comment]
@iznakurnozh ,

Are these the 2 areas you are talking about?
![Screenshot from 2020-08-07 13-39-26](https://user-images.githubusercontent.com/6312397/89672940-84fadc80-d8b3-11ea-830e-8e3edc6ff448.png)
![Screenshot from 2020-08-07 13-39-15](https://user-images.githubusercontent.com/6312397/89672941-85937300-d8b3-11ea-888b-b6e6be945969.png)

The first one is entirely in the control of the server administrator (although I think it could be overwritten by the meeting administrator too) - check:

```
a@mobile:~$ cat /usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties | grep -i footer
defaultWelcomeMessageFooter=This server is running <a href="https://docs.bigbluebutton.org/" target="_blank"><u>BigBlueButton</u></a>.
a@mobile:~$ 
a@mobile:~$ cat /usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties | grep -i welcome
# Default welcome message to display when the participant joins the web
defaultWelcomeMessage=Welcome to <b>%%CONFNAME%%</b>!<br><br>For help on using BigBlueButton see these (short) <a href="https://www.bigbluebutton.org/html5" target="_blank"><u>tutorial videos</u></a>.<br><br>To join the audio bridge click the phone button.  Use a headset to avoid causing background noise for others.
defaultWelcomeMessageFooter=This server is running <a href="https://docs.bigbluebutton.org/" target="_blank"><u>BigBlueButton</u></a>.
```

The second one - we display the exact device names (Integrated Camera) but I admit - likely we should localize the "Medium quality" labels.

Please clarify/attach screenshot and we'll take it from there

**Comment by matiasilva** [comment]
The second one sounds a lot like the Greenlight welcome that is passed containing the link to the meeting also.

**Comment by iznakurnozh** [comment]
@antobinary 
Sure, here is how the chat welcome-message with an invitation link looks like:
![image](https://user-images.githubusercontent.com/38284875/89734680-de067400-da5d-11ea-8ef2-ebec45440a4a.png)

And this one is with the call option: 
![image](https://user-images.githubusercontent.com/38284875/89734732-2c1b7780-da5e-11ea-8a65-1681eca52c22.png)

The video quality drop-down you posted is exactly what I meant.
I promise not to forget screenshots next time :)

**Comment by rasos** [comment]
The welcome text can not be translated neither in `bigbluebutton.properties` nor as an administrator. We would like to see  an i18n option here, as we do have users with different language capabilities.

**Comment by matiasilva** [comment]
You can translate the welcome text by overriding the welcome parameter in Greenlight.

**Comment by rasos** [comment]
@matiasilva I see that the [API](https://docs.bigbluebutton.org/dev/api.html) allows to override the welcome text when creating a room, but where do I do that with Greenlight? Checked with Greenlight 2.6.5 that comes with BBB 2.2 and 2.7.1 that comes with BBB 2.3 dev, I do not see any option to set in the GUI or in .env.

**Comment by matiasilva** [comment]
What test instance of 2.3 are you using? Greenlight functions as normal regardless of the BBB version. Also, Greenlight localizes the welcome message: https://github.com/bigbluebutton/greenlight/blob/master/config/locales/en.yml#L303 so I'm not sure what the issue is.

**Comment by rasos** [comment]
It seems we're not talking about the same text. I meant the welcome text that is defined in `bigbluebutton.properties` which is default about tutorial and some hints. 

![Bildschirmfoto_2020-09-12_20-59-57](https://user-images.githubusercontent.com/485723/93003023-71d6ce80-f53b-11ea-9c90-f07988402b02.png)

We should be able to publish this text in both English and German with browsers choosing the right one dependent on the user settings.

We've set up your own 2.3 dev server. I know that BBB is independent of Greenlight, but that comes with several versions.
