### ISSUE TITLE
Four buttons with same functionality next to each other

### ISSUE THREAD

**Issue by iznakurnozh** [bigbluebutton/bigbluebutton#10203]
**Describe the bug**
label:"User Interface (UI)"
label:"User Experience (UX)"

As you can see on the image there are three buttons (1,2, and 3) with same functionality next to each other (2. and 3. are different as 3. gets highlighted when mouse over and 2. does not). All of them collapse the chat window. Additionally, there is a 4th button, having a similar function: collapsing both the member and the chat window.
Moreover, there is a 5th button when using a private chat (an "x" where on the image the 3-dots-menu is), also collapsing the chat.
Having many buttons with same functionality that close to each other may cause some distraction or confusion. Especially clicking on the title (3., "publich chat") to collapse the public chat seems not to be intuitive.

![image](https://user-images.githubusercontent.com/38284875/89471791-54b22180-d77f-11ea-97dc-0b882b7c7879.png)

**Comment by daminebenq** [comment]
Good evening @iznakurnozh 
**2** and **3** are only one button, actually they are an icon + text; their role is to **hide** the **chat box**, while on click on **1** the **chat box** should **show** or **hide** but **4** is to toggle the **userslist** and **chat box** all together and to have the **presentation area** with the **actions bar** only showing.
So i believe that this is not a bug.
maybe currently there is a problem with a delay on click on 1 and also breakout and shared notes, but soon will be all fixed back. 
Thanks for reporting.

**Comment by iznakurnozh** [comment]
Hey @daminebenq,
sure, it is not a bug - everything works well, it is more about usability: buttons with same functionality, that close to each other, might make user feel lost. I do not have github rights to report issues with UI/UX labels, so I added those labels in the beginning of description.
**2** and **3** can be perceived as two distinct buttons as long as they behave differently when you go with a mouse over it. Thus, using an icon+label as a button might be not an optimal solution in this case.
