### ISSUE TITLE
Text fields smaller than one letter are possible

### ISSUE THREAD

**Issue by iznakurnozh** [bigbluebutton/bigbluebutton#10204]
**Describe the bug**
label:"User Experience (UX)" 

In the presenter or moderator mode, the text tool to write on slides allows to create small text fields where no letter can fit in. When one tries to type it looks as following:

![image](https://user-images.githubusercontent.com/38284875/89473202-985a5a80-d782-11ea-83ec-515cfa917c60.png)

**Comment by antobinary** [comment]
@KDSBrowne - do we have access to the currently selected font when creating the typing area? Can we guarantee that the area will fit the text?

**Comment by KDSBrowne** [comment]
@antobinary, We do have access to it.
