### ISSUE TITLE
Problem with dispay yes/no button in microphone echo test 

### ISSUE THREAD

**Issue by mtashackori** [bigbluebutton/bigbluebutton#10214]
I've a problem after update the bbb,
the yes/no button in microphon echo test dosent show
but I'm hearing the microphone sound.
![نماگرفت از 2020-08-07 16-42-52](https://user-images.githubusercontent.com/16570244/89644509-4d992980-d8cd-11ea-8847-614e402f97d1.png)

**Comment by matiasilva** [comment]
Hi, @mtashackori for support requests please use the mailing lists: https://docs.bigbluebutton.org/2.2/getting-help.html#help-installing-or-running-bigbluebutton unless this is related to 2.3, in which case disregard this comment!

**Comment by mtashackori** [comment]
> Hi, @mtashackori for support requests please use the mailing lists: https://docs.bigbluebutton.org/2.2/getting-help.html#help-installing-or-running-bigbluebutton unless this is related to 2.3, in which case disregard this comment!

Thank you, but my instance has fully functionality and now (after minor update) have a problem

**Comment by ahasanaki** [comment]
hi
same problem  After update to 2.2.21
if user chooses "Listen Only", it work Fine
but when chooses "Microphone", user can speak, but "Connecting ..." windows does not leave the screen and user can not does any action except speaking!

**Comment by TrueSkrillor** [comment]
Hey everyone, happened for me as well after I updated my instance to 2.2.21. "Connecting to echo test" is shown indefinitely, microphone sound is already repeated after a short time. No way to get around, tried to disable echo test but I'm still stuck during connection.

**Comment by IeP4nieF** [comment]
Hi!

Same problem here. Any news about this?

Sadly there are only the error logs described in this [groups.google.com-discussion](https://groups.google.com/forum/#!topic/bigbluebutton-setup/DQe4GN8ktPg) in the output of `bbb-conf --debug`. So I don't have any other idea.

As mtashackori mentioned before, I think this must be a bug, because it occurred after a regular update (to 2.2.21).

**Comment by ahasanaki** [comment]
hi every body
after reinstall bbb, it works well

**Comment by IeP4nieF** [comment]
> hi every body
> after reinstall bbb, it works well

could be... But then I have a problem with all the greenlight user accounts. Or is there an easy way to backup the config incl. users and put them back in, after reinstallation?

**Comment by ahasanaki** [comment]
> could be... But then I have a problem with all the greenlight user accounts. Or is there an easy way to backup the config incl. users and put them back in, after reinstallation?

1. i'm used https://docs.bigbluebutton.org/greenlight/gl-install.html#1-install-docker for installing greenlight and All greenligh data is permanent when update GL.
2. greenlight settings is different of bigbluebutton, after reinstall bbb, for greenlight just update BIGBLUEBUTTON_SECRET in .env and any change no required. also to make changes run commands:
`cd ./greenligh && docker-compose down && docker-composer up -d`
2. Unfortunately, personalized settings will be deleted by updating bbb. you can make your script for keep changes or using "Automatically apply configuration changes on restart" explained on https://docs.bigbluebutton.org/2.2/customize.html
3. For greenlight, if

**Comment by IeP4nieF** [comment]
@ahasanaki: Thanks for the hints. But what do you exactly mean by "reinstalling bbb"? If the server is wiped and completly reinstalled, then there will be no greenlight data there, because all files are gone after wiping an reinstalling the OS.

Or did you run `bbb-install.sh` on the server again, without wiping before?

(Sorry, seems a little bit offtopic now, but I have to get up the server again and I don't see any other chance to do it.)

**Comment by IeP4nieF** [comment]
The problem still exist after upgrading to v2.2.22.

**Comment by hbel** [comment]
This is not a support issue, but a bug. I can reproduce this without any problems on two completely different servers. I tried out almost everything that can be found about troubleshooting audio/microphone issues, but nothing helps. Minor upgrades never should be able to cause such an error, this is completely invalidating the option to use Big Blue Button in production. We can't simply reinstall the server of every school using it each time an update is released. 

Please give us a hint on what to do about that. And try to provide a fix for the issue at hand.

**Comment by hbel** [comment]
Thanks to the help from the community, I was able to restore the functionality by calling
`bbb-conf --setip` again. It's even in the docs, but I must have overread this before. Maybe this solves your problems too?

**Comment by ahasanaki** [comment]
> @ahasanaki: Thanks for the hints. But what do you exactly mean by "reinstalling bbb"? If the server is wiped and completly reinstalled, then there will be no greenlight data there, because all files are gone after wiping an reinstalling the OS.
> 
> Or did you run `bbb-install.sh` on the server again, without wiping before?
> 
> (Sorry, seems a little bit offtopic now, but I have to get up the server again and I don't see any other chance to do it.)

@IeP4nieF I clean it according to the instructions below(does not remove directories) and then reinstall it according to the BBB documents
# dpkg -l | grep bbb
# apt-get -y purge<package_name>
# apt-get –y auto-remove

#apt-get install -y bigbluebutton
#apt-get install -y bbb-html5
….

**Comment by ahasanaki** [comment]
@hbel; Yes, unfortunately updates do not work as standard on Linux packages, also setting should not be deleted after updating
  I have updated from 2.2.4 so far and this is the first time this problem has occurred
i have 3 bbb server, i had to reinstall all of them

**Comment by mtashackori** [comment]
> Thanks to the help from the community, I was able to restore the functionality by calling
> `bbb-conf --setip` again. It's even in the docs, but I must have overread this before. Maybe this solves your problems too?

This fixes for me!
Thanks for contribution

**Comment by matiasilva** [comment]
Remember to read the documentation when upgrading.
