### ISSUE TITLE
STUN server 

### ISSUE THREAD

**Issue by samihashehatta** [bigbluebutton/bigbluebutton#10215]
**Describe the bug**
I was just wondering if after installing bbb should i configure TURN server on the same instance ( aws ec2 ) or should it be on another instance ? 
**Installation type**
i used bbb-install script
**Firewall and IP address type**
yes it's behind a NAT

**Comment by prlanzarin** [comment]
Answering your question: another instance. And you can share a single coturn instance with **many** BBB instances.

My question: did you even read the issue template? There's literally `PLEASE DO NOT FILE ISSUES FOR GENERAL SUPPORT QUESTIONS` written in all caps. This is a support question. [Go to the mailing list next time](https://groups.google.com/forum/#!forum/bigbluebutton-setup) if you can, please.

**Comment by samihashehatta** [comment]
Hey prlanzarin , sorry for posting it in the wrong place but i did try to join your google group but my request got denied . Anyway thanks for your help
