### ISSUE TITLE
Use my own amended BigBlueButton

### ISSUE THREAD

**Issue by libanj** [bigbluebutton/bigbluebutton#10211]
I want to add a simple profanity checker on the chat box which is why I made a small implementation on the BigBlueButton source code. I want to be able to implement and use my own version of BigBlueButton instead of the one that is publicly available.

This is the first time I'm implementing this and I checked the BigBlueButton docs and it only gives information regarding how to contribute. This is not what I am trying to achieve. I am simply just using my own amended version of BigBlueButton and all I have done was add some extra line of code which detects if there are any profanities in the chat so that I can then disable it.

I want to be able to test my version of BigBlueButton and see if it worked.

Would I need to convert my version of the BigBlueButton as a package so that I can then import it? I'm not sure what to do.

Thank you,

**Comment by matiasilva** [comment]
Hi @libanj, you can find instructions on how to set up your changes to work on your server, namely by building the meteor app for production. As you've noticed in the docs though, others might find this feature useful as well so consider contributing by opening a pull request with your changes. For further help with development, please use the developer mailing lists linked to in the documentation.
