### ISSUE TITLE
bbb-rap-resque-worker.service throws error when processing a recording in 2.3-dev

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#10223]
**Describe the bug**
`bbb-rap-resque-worker.service` throws an `Error connecting to Redis on 127.0.0.1:6379` when process a recording

**To Reproduce**
1. Install latest build of BigBlueButton 2.3
2. run `bbb-record --watch`
3. Create a 30 second recording with video

**Expected behavior**
`bbb-rap-resque-worker.service` should not thrown an error.
 
**Actual behavior**
It shows the following error

~~~
Aug 08 19:54:38 droplet-2237 sh[4911]: Redis::CannotConnectError: Error connecting to Redis on 127.0.0.1:6379 (Errno::ECONNREFUSED)
Aug 08 19:54:38 droplet-2237 sh[4911]: Original Exception (Redis::CannotConnectError): Error connecting to Redis on 127.0.0.1:6379 (Errno::ECONNREFUSED)
Aug 08 19:54:38 droplet-2237 sh[4911]:   /var/lib/gems/2.5.0/gems/redis-4.1.3/lib/redis/client.rb:362:in `rescue in establish_connection'
Aug 08 19:54:38 droplet-2237 sh[4911]: /var/lib/gems/2.5.0/gems/redis-4.1.3/lib/redis/client.rb:343:in `establish_connection'
Aug 08 19:54:38 droplet-2237 sh[4911]: /var/lib/gems/2.5.0/gems/redis-4.1.3/lib/redis/client.rb:106:in `block in connect'
Aug 08 19:54:38 droplet-2237 sh[4911]: /var/lib/gems/2.5.0/gems/redis-4.1.3/lib/redis/client.rb:306:in `with_reconnect'
Aug 08 19:54:38 droplet-2237 sh[4911]: /var/lib/gems/2.5.0/gems/redis-4.1.3/lib/redis/client.rb:105:in `connect'
Aug 08 19:54:38 droplet-2237 sh[4911]: /var/lib/gems/2.5.0/gems/redis-4.1.3/lib/redis/client.rb:381:in `ensure_connected'
Aug 08 19:54:38 droplet-2237 sh[4911]: /var/lib/gems/2.5.0/gems/redis-4.1.3/lib/redis/client.rb:231:in `block in process'
Aug 08 19:54:38 droplet-2237 sh[4911]: /var/lib/gems/2.5.0/gems/redis-4.1.3/lib/redis/client.rb:319:in `logging'
Aug 08 19:54:38 droplet-2237 sh[4911]: /var/lib/gems/2.5.0/gems/redis-4.1.3/lib/redis/client.rb:230:in `process'
Aug 08 19:54:38 droplet-2237 sh[4911]: /var/lib/gems/2.5.0/gems/redis-4.1.3/lib/redis/client.rb:125:in `call'
Aug 08 19:54:38 droplet-2237 sh[4911]: /var/lib/gems/2.5.0/gems/redis-4.1.3/lib/redis.rb:914:in `block in get'
Aug 08 19:54:38 droplet-2237 sh[4911]: /var/lib/gems/2.5.0/gems/redis-4.1.3/lib/redis.rb:52:in `block in synchronize'
Aug 08 19:54:38 droplet-2237 sh[4911]: /usr/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
Aug 08 19:54:38 droplet-2237 sh[4911]: /var/lib/gems/2.5.0/gems/redis-4.1.3/lib/redis.rb:52:in `synchronize'
Aug 08 19:54:38 droplet-2237 sh[4911]: /var/lib/gems/2.5.0/gems/redis-4.1.3/lib/redis.rb:913:in `get'
Aug 08 19:54:38 droplet-2237 sh[4911]: /var/lib/gems/2.5.0/gems/redis-namespace-1.7.0/lib/redis/namespace.rb:469:in `call_with_namespace'
Aug 08 19:54:38 droplet-2237 sh[4911]: /var/lib/gems/2.5.0/gems/redis-namespace-1.7.0/lib/redis/namespace.rb:349:in `block (2 levels) in <class:Namespace>'
Aug 08 19:54:38 droplet-2237 sh[4911]: /var/lib/gems/2.5.0/gems/resque-2.0.0/lib/resque/data_store.rb:231:in `get_worker_payload'
Aug 08 19:54:38 droplet-2237 sh[4911]: /var/lib/gems/2.5.0/gems/resque-2.0.0/lib/resque/worker.rb:752:in `job'
Aug 08 19:54:38 droplet-2237 sh[4911]: /var/lib/gems/2.5.0/gems/resque-2.0.0/lib/resque/worker.rb:670:in `unregister_worker'
Aug 08 19:54:38 droplet-2237 sh[4911]: /var/lib/gems/2.5.0/gems/resque-2.0.0/lib/resque/worker.rb:246:in `work'
Aug 08 19:54:38 droplet-2237 sh[4911]: /var/lib/gems/2.5.0/gems/resque-2.0.0/lib/resque/tasks.rb:20:in `block (2 levels) in <top (required)>'
Aug 08 19:54:38 droplet-2237 sh[4911]: /usr/lib/ruby/vendor_ruby/rake/task.rb:271:in `block in execute'
Aug 08 19:54:38 droplet-2237 sh[4911]: /usr/lib/ruby/vendor_ruby/rake/task.rb:271:in `each'
Aug 08 19:54:38 droplet-2237 sh[4911]: /usr/lib/ruby/vendor_ruby/rake/task.rb:271:in `execute'
Aug 08 19:54:38 droplet-2237 sh[4911]: /usr/lib/ruby/vendor_ruby/rake/task.rb:213:in `block in invoke_with_call_chain'
Aug 08 19:54:38 droplet-2237 sh[4911]: /usr/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
Aug 08 19:54:38 droplet-2237 sh[4911]: /usr/lib/ruby/vendor_ruby/rake/task.rb:193:in `invoke_with_call_chain'
Aug 08 19:54:38 droplet-2237 sh[4911]: /usr/lib/ruby/vendor_ruby/rake/task.rb:182:in `invoke'
Aug 08 19:54:38 droplet-2237 sh[4911]: /usr/lib/ruby/vendor_ruby/rake/application.rb:160:in `invoke_task'
Aug 08 19:54:38 droplet-2237 sh[4911]: /usr/lib/ruby/vendor_ruby/rake/application.rb:116:in `block (2 levels) in top_level'
Aug 08 19:54:38 droplet-2237 sh[4911]: /usr/lib/ruby/vendor_ruby/rake/application.rb:116:in `each'
Aug 08 19:54:38 droplet-2237 sh[4911]: /usr/lib/ruby/vendor_ruby/rake/application.rb:116:in `block in top_level'
Aug 08 19:54:38 droplet-2237 sh[4911]: /usr/lib/ruby/vendor_ruby/rake/application.rb:125:in `run_with_threads'
Aug 08 19:54:38 droplet-2237 sh[4911]: /usr/lib/ruby/vendor_ruby/rake/application.rb:110:in `top_level'
Aug 08 19:54:38 droplet-2237 sh[4911]: /usr/lib/ruby/vendor_ruby/rake/application.rb:83:in `block in run'
Aug 08 19:54:38 droplet-2237 sh[4911]: /usr/lib/ruby/vendor_ruby/rake/application.rb:186:in `standard_exception_handling'
Aug 08 19:54:38 droplet-2237 sh[4911]: /usr/lib/ruby/vendor_ruby/rake/application.rb:80:in `run'
Aug 08 19:54:38 droplet-2237 sh[4911]: /usr/bin/rake:27:in `<main>'
Aug 08 19:54:38 droplet-2237 sh[4911]: /var/lib/gems/2.5.0/gems/redis-4.1.3/lib/redis/client.rb:362:in `rescue in establish_connection'
Aug 08 19:54:38 droplet-2237 sh[4911]: /var/lib/gems/2.5.0/gems/redis-4.1.3/lib/redis/client.rb:343:in `establish_connection'
Aug 08 19:54:38 droplet-2237 sh[4911]: /var/lib/gems/2.5.0/gems/redis-4.1.3/lib/redis/client.rb:106:in `block in connect'
Aug 08 19:54:38 droplet-2237 sh[4911]: /var/lib/gems/2.5.0/gems/redis-4.1.3/lib/redis/client.rb:306:in `with_reconnect'
Aug 08 19:54:38 droplet-2237 sh[4911]: /var/lib/gems/2.5.0/gems/redis-4.1.3/lib/redis/client.rb:105:in `connect'
Aug 08 19:54:38 droplet-2237 sh[4911]: /var/lib/gems/2.5.0/gems/redis-4.1.3/lib/redis/client.rb:381:in `ensure_connected'
Aug 08 19:54:38 droplet-2237 sh[4911]: /var/lib/gems/2.5.0/gems/redis-4.1.3/lib/redis/client.rb:231:in `block in process'
Aug 08 19:54:38 droplet-2237 sh[4911]: /var/lib/gems/2.5.0/gems/redis-4.1.3/lib/redis/client.rb:319:in `logging'
Aug 08 19:54:38 droplet-2237 sh[4911]: /var/lib/gems/2.5.0/gems/redis-4.1.3/lib/redis/client.rb:230:in `process'
Aug 08 19:54:38 droplet-2237 sh[4911]: /var/lib/gems/2.5.0/gems/redis-4.1.3/lib/redis/client.rb:125:in `call'
Aug 08 19:54:38 droplet-2237 sh[4911]: /var/lib/gems/2.5.0/gems/redis-4.1.3/lib/redis.rb:914:in `block in get'
Aug 08 19:54:38 droplet-2237 sh[4911]: /var/lib/gems/2.5.0/gems/redis-4.1.3/lib/redis.rb:52:in `block in synchronize'
Aug 08 19:54:38 droplet-2237 sh[4911]: /var/lib/gems/2.5.0/gems/redis-4.1.3/lib/redis.rb:52:in `synchronize'
Aug 08 19:54:38 droplet-2237 sh[4911]: /var/lib/gems/2.5.0/gems/redis-4.1.3/lib/redis.rb:913:in `get'
Aug 08 19:54:38 droplet-2237 sh[4911]: /var/lib/gems/2.5.0/gems/redis-namespace-1.7.0/lib/redis/namespace.rb:469:in `call_with_namespace'
Aug 08 19:54:38 droplet-2237 sh[4911]: /var/lib/gems/2.5.0/gems/redis-namespace-1.7.0/lib/redis/namespace.rb:349:in `block (2 levels) in <class:Namespace>'
~~~

**Comment by paulraper** [comment]
Is this related to the issue in #10173 (https://github.com/bigbluebutton/bigbluebutton/issues/10173)?

**Comment by Jossef-767** [comment]
My recording are also getting "Failed" to  Publish on  BigBlueButton 2.3.
when i  use **poll**  in the lesson, the recording "Publish"  stage will fail.
if i do not use polling recording  will Publish fine. 
this is what i get in the Publish log file when i use poll:


E, [2020-08-09T10:23:58.521067 #67912] ERROR -- : Failed to generate poll svg
E, [2020-08-09T10:23:58.521117 #67912] ERROR -- : /usr/local/bigbluebutton/core/scripts/publish/presentation.rb:380:in `svg_render_shape_poll'
E, [2020-08-09T10:23:58.521145 #67912] ERROR -- : /usr/local/bigbluebutton/core/scripts/publish/presentation.rb:421:in `svg_render_shape'
E, [2020-08-09T10:23:58.521215 #67912] ERROR -- : /usr/local/bigbluebutton/core/scripts/publish/presentation.rb:468:in `block in svg_render_image'
E, [2020-08-09T10:23:58.521250 #67912] ERROR -- : /usr/local/bigbluebutton/core/scripts/publish/presentation.rb:467:in `each'
E, [2020-08-09T10:23:58.521275 #67912] ERROR -- : /usr/local/bigbluebutton/core/scripts/publish/presentation.rb:467:in `svg_render_image'
E, [2020-08-09T10:23:58.521302 #67912] ERROR -- : /usr/local/bigbluebutton/core/scripts/publish/presentation.rb:957:in `block in processPresentation'
E, [2020-08-09T10:23:58.521324 #67912] ERROR -- : /var/lib/gems/2.5.0/gems/nokogiri-1.10.8/lib/nokogiri/xml/node_set.rb:238:in `block in each'
E, [2020-08-09T10:23:58.521353 #67912] ERROR -- : /var/lib/gems/2.5.0/gems/nokogiri-1.10.8/lib/nokogiri/xml/node_set.rb:237:in `upto'
E, [2020-08-09T10:23:58.521384 #67912] ERROR -- : /var/lib/gems/2.5.0/gems/nokogiri-1.10.8/lib/nokogiri/xml/node_set.rb:237:in `each'
E, [2020-08-09T10:23:58.521569 #67912] ERROR -- : /usr/local/bigbluebutton/core/scripts/publish/presentation.rb:874:in `processPresentation'
E, [2020-08-09T10:23:58.521606 #67912] ERROR -- : /usr/local/bigbluebutton/core/scripts/publish/presentation.rb:1303:in `<main>'
E, [2020-08-09T10:23:58.521722 #67912] ERROR -- : exit

**Comment by paulraper** [comment]
I shall try that too Josef. So far I hadn't thought that there could be an issue with the use of polling.

**Comment by paulraper** [comment]
Josef, Bingo! Same result. If I run a meeting without polling, the script processes, if I include polling, the whole thing aborts.

**Comment by paulraper** [comment]
Great Fred, The recording processed.
Only one thing. When I playback the recording, I do not see the results of the poll published.
Also, I do not see how I can access the class statistics.
![Recording 14 8 20](https://user-images.githubusercontent.com/9352870/90223191-e2d87880-de0d-11ea-8a9a-602c7f1e4a56.png)
I now have two recordings here, one without polling, the top one with. But I do not see any options that allow me to see the statistics.
![join-session-bbb2](https://user-images.githubusercontent.com/9352870/90223327-2337f680-de0e-11ea-85df-a90040bc8db8.png)
This screen shot is taken from the website of Carlton University.

**Comment by paulraper** [comment]
Ok, I have just stumbled over another bug.
The latest release seems to process and publish recordings that have one poll. However, if you include multiple polls, then the processing takes place, but the publishing part aborts. In other words, we still have a problem with recordings publishing, but specifically when there are multiple polls involved.

**Comment by paulraper** [comment]
This bug seems to still exist. :-(

**Comment by peternagelsa** [comment]
Hi everyone, 

I am not sure whether my issue relates to this particular isse, so an apology an advance if it does not fit. 
Install
Ubuntu 18.04
BBB 2.3-Dev alpha 2
Greenlight 2.3.7 

I made a few recordings on the 4th of September. The problem is that none of the recordings are listed in:
Greenlight 2.3.7 
Netxcloud
Moodle 

None of the recordings show up in any of the above. I ran a command line and the recordings are all listed. 

Is this a permission issue? The various UI not having permission to access and show these recordings? 

Thanks in advance
Peter

**Comment by drnlm** [comment]
Since this seems the closest relevant issue:

We had an issue with BBB 2.3dev not processing recordings with polls on our setup (running on Ubuntu 18.04), which we tracked down to `core/scripts/utils/gen_poll_svg` failing with `KeyError: 'could not find foreign type Context'`

Installing `python3-gi-cairo` as an additional dependency has resolved the issue for our recordings (at least so far).

**Comment by paulraper** [comment]
Hi Neil,
Could you perhaps explain how you went about installing this please.

I am assuming that you might need to reinstall after you update BBB each time, or have you somehow incorporated the process into the bionic updater since according to the weblink you give it seems to indicate it is part of the bionic process, or am I misunderstanding something here?
Your thoughts are very much appreciated.

**Comment by paulraper** [comment]
@peternagelsa I am running the Alpha version of BBB, my recordings show up in Moodle, but I do not get any of the statistical information nor editing features that should be available. We have also had problems with BBB processing recordings that include polls, which @drnlm Neil seems to have found a solution to, see above.

**Comment by drnlm** [comment]
> Hi Neil,
> Could you perhaps explain how you went about installing this please.
> 
> I am assuming that you might need to reinstall after you update BBB each time, or have you somehow incorporated the process into the bionic updater since according to the weblink you give it seems to indicate it is part of the bionic process, or am I misunderstanding something here?

`python3-gi-cairo` is a standard Ubuntu package, so we're just installing it using `apt install python3-gi-cairo`

We're using quite short-lived BBB servers (our use case was running an online conference), so we created an ansible playbook to handle the BBB setup, and just added this as an extra step after installing BBB, so I can't comment on whether upgrading BBB causes any issues.

**Comment by paulraper** [comment]
Hi Neil,
Thanks for the feedback. It would be interesting to see if @ffdixon Fred has any thoughts on this. I would certainly be happy to give it a go.

**Comment by paulraper** [comment]
@drnlm Hi Neil, super that worked for me too: thank you very much for the tip.
@ffdixon The inclusion of python3-gi-cairo seems to cure the problem with polls preventing BBB from publishing videos. I followed the advice of Neil, and after installing cairo, the whole thing worked.

**Comment by matiasilva** [comment]
@drnlm What led you to believe that installing that python package would solve it?

**Comment by drnlm** [comment]
> @drnlm What led you to believe that installing that python package would solve it?

As I stated in the my original post, we tracked the actual failure to `core/scripts/utils/gen_poll_svg` failing with `KeyError: 'could not find foreign type Context'`. We found this by trying to run the `gen_pool_svg` script manually - `presention.rb` only reported that the `svg_render_shape_poll` function (which is where this script is called) was failing, and didn't report any further details.

Googling that error led to the suggestion to install `python3-gi-cairo`.

**Comment by paulraper** [comment]
I would simply add that from my side I have had continued problems with the recordings processing since the start. This is an issue Fred has known about now for some time, but up until now, has not been able to resolve.
I install an update of the whole package on an almost daily basis, and the poll issue has not until I followed Neil's suggestion been resolved.
However, as soon as I installed the package Neil suggested, the problem was indeed gone, so I can only conclude that that was indeed where the problem lay.
@drnlm Thanks a lot for fixing this issue.
The only issue that for me, so far as the recordings are concerned, is still outstanding is that of being able to (a) see the attendance and participation statistics, and the exporting of the recording as a video. See above August 10th and August 14th.

**Comment by matiasilva** [comment]
@paulraper what packages updates are you installing? PRs don't get put into a debian package until a new release is made so you might just be reinstalling the same thing over and over again?.. 

Also, BigBlueButton is not just developed by one person as you seem to be suggesting and everyone has different priorities. There are hundreds if not thousands of people running 2.2, so a careful balance has to be struck between developing both versions. Patience is a virtue.

@drnlm Ah, so you googled it then. I was after a clear link between that package and the error you encountered because identifying the core issue is more important than temporarily installing a random package. Interesting that a python package needs to be installed for a ruby issue?

**Comment by drnlm** [comment]
> @drnlm Ah, so you googled it then. I was after a clear link between that package and the error you encountered because identifying the core issue is more important than temporarily installing a random package. Interesting that a python package needs to be installed for a ruby issue?

Please read what I've written.

`gen_poll_svg` is not a ruby program. It's a python program using gobject-introspection to call out to cairo to construct the svg. `python3-gi-cairo` is the package that provides the gobject-introspection binding for that on Ubuntu

I did not install of `python3-gi-cairo` randomly because google said so. I googled because I didn't know which of various possible missing packages was responsible for the error, and found an answer that made sense.

**Comment by matiasilva** [comment]
> `gen_poll_svg` is not a ruby program. It's a python program using gobject-introspection to call out to cairo to construct the svg. `python3-gi-cairo` is the package that provides the gobject-introspection binding for that on Ubuntu

Ah, so somehow between 2.2 and 2.3 this package was missing? Another possibility is that because the recording pipeline was reworked in 2.3, this package was used but accidentally not included.

> I did not install of `python3-gi-cairo` randomly because google said so. I googled because I didn't know which of various possible missing packages was responsible for the error, and found an answer that made sense.

That's not what I was implying, and your further clarification above helped get to the bottom of this issue.

**Comment by paulraper** [comment]
@matiasilva The packages I install are in some instances repetitions of previously installed software, and sometimes updates to to some core applications. I do not wish to appear as though I am stating that only one person is involved in the development of BBB, it is simply that Fred Dixon is about the only person I have to date had much contact with, and who knows my own situation. But please, I do appreciate that there are many people involved in the development of this package: myself included.

**Comment by matiasilva** [comment]
Fret not, myself and others browsing these issues and the group are aware of the bugs you very helpfully report :-) and thanks @drnlm for finding a fix to this

**Comment by paulraper** [comment]
@matiasilva You are welcome. Let's make BBB the best available tool. For my part I love it. It has many really intuitive features.

**Comment by ffdixon** [comment]
Added `python3-gi-cairo` to dependency in packaging for 2.3-alpha4

**Comment by pedrobmarin** [comment]
Was this resolved, @ffdixon ?
