### ISSUE TITLE
After update to 2.2.21 no recording possibility

### ISSUE THREAD

**Issue by lonesomewalker** [bigbluebutton/bigbluebutton#10222]
**Describe the bug**
After upgrading to latest 2.2 release no record button is shown.
Also, no real information in the logfiles found so far.
(bbb-conf --clean already applied)

**Additional context**
/usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties
disableRecordingDefault=false
autoStartRecording=false
allowStartStopRecording=true

**Comment by matiasilva** [comment]
Hi @lonesomewalker could you post your support question in the setup group (https://groups.google.com/forum/#!forum/bigbluebutton-setup). Thanks!

**Comment by ffdixon** [comment]
Just want to dig into this one a bit more as the upgrade shouldn't have affected the recording.  

@lonesomewalker what version were you running before upgrade?  Was it a stock BigBlueButton install?  Did you get any errors during the upgrade?  How did you do the upgrade (manual or with bbb-install.sh)?

**Comment by lonesomewalker** [comment]
bbb-install.sh
Upgraded from 2.2.19
No errors.

And no, this is NOT really the way issues should get treated now.
I am not willing to post this in the setup group because this is an ISSUE and not a setup problem.
Regarding the fact that we do not upgrade our customers machines immediately to the latest version, we get the issues delayed than normal.

@matiasilva you can have a look at my issues here.
I am not to dumb or lazy to do a setup of BBB, i only report REAL issues. ;-)

@ffdixon Nevertheless, we will move this installation to new hardware since debugging took longer than 1 hour.
All logfiles show NO errors or issues which are related to this problem, only the common warnings...

**Comment by ffdixon** [comment]
Hey @lonesomewalker we're all volunteering our time here.  No one said you were lazy or dumb.  If you want to carry that language further, you'll find your ability to post anywhere to these forums will be revoked.  

Regarding your issue, can you do a sample recording and let us know what you see in the archive, process, and publish logs, see

  https://docs.bigbluebutton.org/dev/recording.html#troubleshooting

I personally test the upgrades for each release, so now that we know the version from which you are upgrading, we can try to reproduce it on our end.

**Comment by ffdixon** [comment]
I installed BigBlueButton 2.2.19 with [bbb-install.sh](https://github.com/bigbluebutton/bbb-install) and verified the recording worked.  Upgraded to 2.2.21 using `-v xenial-22` and did another recording.  It worked.

Interested to hear what you find looking at the log files when you process a test recording.

**Comment by lonesomewalker** [comment]
@ffdixon yes, WE ALL do this.
And i found it kinda rude to just close an issue.
Also i put a smiley at the end of this sentence...

But nevermind, i just deleted this server.
Whoever will have this issue again: just reinstall.

**Comment by lonesomewalker** [comment]
Unfortunately i have to reopen this issue again. :-(
Another host, currently running 2.2.22
Setup scripted with bbb-install.sh
How to debug "why" the record button is not shown?
Also used API Mate to get sure there are no weird parameters passed to the server for creating a room.
All parameter from API Mate are set default, and parameter "allowStartStopRecording" is set.
When clicking on creating a room and joining as a moderator, still no record button shown.
But when forcing recording, it will be done correctly and is shown on top.
So i can say, it is not a Greenlight issue, must be BigBlueButton itself.

How to debug which config file might be the issue? bigbluebutton.properties is sane:
`root@ld # cat /usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties | grep "ecord"`

\# Disable recording by default.
\#   true - don't record even if record param in the api call is set to record
\#   false - when record param is passed from api, override this default
disableRecordingDefault=false
\# Start recording when first user joins the meeting.
\# is recorded.
autoStartRecording=false
\# Allow the user to start/stop recording.
allowStartStopRecording=true
\# Saves meeting events even if the meeting is not recorded
\# Directory where we drop the <meeting-id-recorded>.done file
recordStatusDir=/var/bigbluebutton/recording/status/recorded
\# The directory where the published/unpublised recordings are located. This is for
\# the get recording* api calls
breakoutRoomsRecord=false

**Comment by lonesomewalker** [comment]
Addon: when using the checkbox "record" in API Mate, i get the option to record in the room.

**Comment by pedrobmarin** [comment]
Did the Greenlight changes resolved this for you, @lonesomewalker ?

**Comment by lonesomewalker** [comment]
Should, can be closed :-)
