### ISSUE TITLE
Custom CSS on HTML5 client with API call

### ISSUE THREAD

**Issue by ryprfpryr** [bigbluebutton/bigbluebutton#10224]
I am trying to set custom CSS parameters but BBB seems to ignore them, I just can't make this work in 2.2.21.

Trying with the provided example at https://docs.bigbluebutton.org/2.2/customize.html#examples
using API mate without output:

`userdata-bbb_custom_style= %3Aroot%7B--loader-bg%3A%23000%3B%7D.overlay--1aTlbi%7Bbackground-color%3A%23000!important%3B%7Dbody%7Bbackground-color%3A%23000!important%3B%7D`

Other Custom parameter like userdata-bbb_enable_video=false are working ok, but no output with CSS.

Quoted from BBB docs:

```
:root {
  --loader-bg:#000;
}

.overlay--1aTlbi {
  background-color:#000 !important;
}

body {
  background-color:#000 !important;
}
```
```
which looks like

`%3Aroot%7B--loader-bg%3A%23000%3B%7D.overlay--1aTlbi%7Bbackground-color%3A%23000!important%3B%7Dbody%7Bbackground-color%3A%23000!important%3B%7D`
```

**Comment by antobinary** [comment]
Hi @ryprfpryr,

I just ran some examples with `userdata-bbb_custom_style=`
Looks like for single line css this is a working format: `userdata-bbb_custom_style=:root{--loader-bg:red;}.navbar--Z2lHYbG{background-color:pink!important;}`

We are checking why the encoded string is not working as documented

**Comment by antobinary** [comment]
There are some new changes to the documentation: https://github.com/bigbluebutton/bigbluebutton.github.io/commit/8f64ac5317628e6d32a6e614e1c21deb5cedbc88

I am now closing this issue - the main problem was passing of URI encoded styles where no encoding was expected

**Comment by ryprfpryr** [comment]
Thank you very much Anton! 🙏👏
