### ISSUE TITLE
Move the Leave/End Session button at bottom

### ISSUE THREAD

**Issue by faiyaz-ergo** [bigbluebutton/bigbluebutton#10225]
Hi,
how can I move the end session/meeting and leave meeting button at the bottom(Highlighted section in the screenshot)

![22-overview-2-1536x811](https://user-images.githubusercontent.com/44223640/89732089-2fb6fa80-da6e-11ea-8963-2ffce44d8e1c.png)

**Comment by iSamof** [comment]
Always a good idea to do a search before posting ...
https://github.com/bigbluebutton/bigbluebutton/issues/10131
https://github.com/bigbluebutton/bigbluebutton/issues/9938
... and many others

I think someone has already done what you are asking for but I can't spot it right now. I hope this helps.

**Comment by faiyaz-ergo** [comment]
haven't got any clear way forward in the mentioned issues :(

**Comment by matiasilva** [comment]
That's probably because there is none yet :). Merging this issue with the others helpfully pointed out above. Also note that such development help belongs in the mailing lists!
