### ISSUE TITLE
disable camera for only attendee in html5Client

### ISSUE THREAD

**Issue by TivanDev** [bigbluebutton/bigbluebutton#10228]
hello everybody 
I have change 
`webcamsOnlyForModerator=true`
in 
`/usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties`
but all user can use webcam
I want to show webcam icon for moderator and all of the other users can see the webcam icon and share their webcams

**Comment by matiasilva** [comment]
Hi, for questions related to using Bigbluebutton, please use the mailing list: https://groups.google.com/forum/m/#!forum/bigbluebutton-users
