### ISSUE TITLE
Restrict certain cameraProfiles on API call

### ISSUE THREAD

**Issue by ryprfpryr** [bigbluebutton/bigbluebutton#10232]
[Moved from #9789]

**Would it possible to restrict certain cameraProfiles only for moderators?**

Reason of the request:
The ISP's in our country are very very bad and even the mobile internet quality is very precarious / and even 3G and 4G is nonexistent in most remote or rural zones.

Our classes have 1 teacher + 40 students, and for bandwidth reasons we are enabling just 1 cameraProfile (low quality) with bitrate as low as possible --80 kbps (most of students and teachers have VERY bad internet connections..) + of course webcamsOnlyForModerator= true.

A big part of our teachers are using last generation iPhones and similar mobile devices, and they use their mobile internet connection on 3G or 4G when available (slightly superior than their home's --rural zone connections).. BUT the big issue here is that iPhones or similar **smartphones with big resolutions (like 1792 x 828 or similar) require a minimum of 150/200kbps to work smoothly**. Big resolutions look very laggy (even with good internet connection), specially if there are big movements on the image (example: a teacher gesturing in front of a chalkboard).

We already tried to enable just 2 camera profiles and serring userdata-bbb_preferred_camera_profile (one on 80kbps --as "default" and another on 200kbps) **but students sometimes change/select their camera quality to the highest ones** --intentionally or accidentally as well. When this happens, the teacher bandwidth gets very saturated and sometimes is not even possible to them to give the class with their students webcams on (PS: they need to see their students).

This is why it would be necessary to enable this higher bitrates only for moderators (teachers).

This is what we were thinking as ideal solutions:

_Option 1:_

Adding a "moderatorsOnly" value in settings.yml like this example:

   ```
 cameraProfiles:
    - id: low
      name: Low quality
      default: false
      bitrate: 80
      moderatorsOnly: false

    - id: medium
      name: Medium quality
      default: true
      bitrate: 200
      moderatorsOnly: true
```

And then adding something like this on the custom parameters on API call:

`userdata-bbb_moderatorsOnly_camera_profile=`

**--if set to true, the cameraProfiles with moderatorsOnly=true would be NOT shown to participants (students) as an option in videoPreview.**

_Option 2 (suggested by @matiasilva ) :_

**Pass in a new parameter on join specifying a list of allowed camera profiles on API call.**

Your opinions will be much appreciated.
Thank you.

**Comment by mricim** [comment]
It's a very good idea! Was something similar implemented?
