### ISSUE TITLE
turn off and permanently disable the video transmission of participants in the conference

### ISSUE THREAD

**Issue by unamx88** [bigbluebutton/bigbluebutton#10230]
The moderator should be able to turn off and permanently disable the video transmission of participants in the conference

**Comment by matiasilva** [comment]
@unamx88 I just marked your other issue as a duplicate. This one is exactly the same except for a few words. Please add the request for this to be permanent in the other issue than making a new one.

**Comment by unamx88** [comment]
@matiasilva ok.

**Comment by unamx88** [comment]
I'm a little confused. In BigBlueButton I currently see no function to switch off the video transmission of the participants in the conference. Only the participants can turn off the webcam themselves but not the moderator.

**Comment by matiasilva** [comment]
Yes, that's correct. Someone else has brought this up in the past so I ask that you add your thoughts or give the post a thumbs up in the issue I marked a duplicate. This is easier for people to keep track of what features people want.

**Comment by unamx88** [comment]
all right. i hadn't found the previous entry

**Comment by matiasilva** [comment]
No worries :)
