### ISSUE TITLE
minimize presentation for viewer Crushing the presentation

### ISSUE THREAD

**Issue by Jossef-767** [bigbluebutton/bigbluebutton#10242]
1.  set "**restoreOnUpdate: true**" in settings.yml
2.  login as viewer
3.  minimize presentation
4.  get error

BBB version 
BigBlueButton Server 2.3.0-dev (1044)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome, firefox
![image](https://user-images.githubusercontent.com/2356928/89865099-c5a96d00-dbb5-11ea-82e4-d5a2bd99468e.png)

**Comment by PhMemmel** [comment]
Cannot reproduce on 2.3-beta-3, restore on update feature works as expected
