### ISSUE TITLE
welcome record

### ISSUE THREAD

**Issue by Amixengineer** [bigbluebutton/bigbluebutton#10248]
hello there,

I would like to get rid of the welcome voice once someone enters the room and choose listen only I know it makes the student sure that its headphone works great but the language of BBB is different from English, is it possible to change it or remove it? thanks for supporting,

**Comment by matiasilva** [comment]
Hi, please send your question to the appropriate mailing lists. If this is the greenlight welcome then the greenlight list, if it is about the first message, you can find some more info in the docs and then try the setup mailing list.

Good luck!
