### ISSUE TITLE
where to change the default of ''See other viewers webcams''

### ISSUE THREAD

**Issue by Amixengineer** [bigbluebutton/bigbluebutton#10243]
hello there,

after looking through "bigbluebutton.properties" I could not find the default to change it to block. would be gratefull for any assistance

**Comment by ffdixon** [comment]
See

  https://docs.bigbluebutton.org/2.2/customize.html#apply-lock-settings-to-restrict-webcams

This isn't a bug, but a request for help.  In the future, please post such requests to our (see https://bigbluebutton.org/support/community/).  If in helping you there we find a bug, we'll open an issue here to track it.

**Comment by Amixengineer** [comment]
thanks a billion for fast reply but the one that you mentioned is for sharing webcams what I am trying to block is **Seeing other viewers webcams** 
but I cannot find its property.

<img width="346" alt="Screen Shot 1399-05-21 at 16 43 11" src="https://user-images.githubusercontent.com/34276557/89896106-1e96f680-dbf2-11ea-8f33-ecaac3480008.png">

**Comment by Amixengineer** [comment]
solve it! thanks 

webcamsOnlyForModerator=false
