### ISSUE TITLE
Warning - WebRTC: onaddtrack is deprecated! Use peerConnection.ontrack instead.

### ISSUE THREAD

**Issue by sharypovandrey** [bigbluebutton/bigbluebutton#10241]
1) Press screensharing button and give access to the screen
2) Console gives warning - WebRTC: onaddtrack is deprecated! Use peerConnection.ontrack instead.
kurento-utils.js:244

**Comment by pedrobmarin** [comment]
@prlanzarin do we need this opened?

**Comment by prlanzarin** [comment]
Yup.

**Comment by prlanzarin** [comment]
Merging into #12485
