### ISSUE TITLE
Audio Bridge is not connecting

### ISSUE THREAD

**Issue by ashishkpaul** [bigbluebutton/bigbluebutton#10255]
bbb-2.2.22 We are using inbuilt microphone in a webcam. Audio bridge is not connecting while it's giving the echo test but yes and no buttons are not showing. Continuously showing the echo test applet.
No problem found in bbb-2.2.21

**Comment by pedrobmarin** [comment]
`sudo bbb-conf --setip <host>`

**Comment by lightweight** [comment]
Same problem here with 2.2.22. Hanging on "Config to echo test..." where previously it worked well. Gtetting a time out on sip.transaction.ict "Timer (B|M) expired for INVITE client transaction nnnnnnnnnn"... 

Ok - and when I did as @pedrobmarin suggested, in my case `sudo bbb-conf --setup <hostfqdn>` it all burst back into life... wonder what happened with the upgrade?

**Comment by prlanzarin** [comment]
https://github.com/bigbluebutton/bigbluebutton/pull/10148
and then
https://github.com/bigbluebutton/bigbluebutton/releases/tag/v2.2.21 
and then 
https://docs.bigbluebutton.org/2.2/install.html#upgrading-from-bigbluebutton-22
(`Next, use bbb-conf --setip to re-assign your servers IP address or hostname to BigBlueButton’s configuration files.`)
