### ISSUE TITLE
Meeting URL not supporting UIWebview iOS

### ISSUE THREAD

**Issue by emorphisgit** [bigbluebutton/bigbluebutton#10254]
I am using BBB conference functionality with my iOS app but unable to start a conversation, getting a message browser is not supported.
Same meeting URL is working on safari browser but not working with WebView of iOS with **WKWebView** 
![image](https://user-images.githubusercontent.com/30403598/90010540-9f6ef480-dcbd-11ea-8cc1-4791157fe2ab.png)

**Comment by matiasilva** [comment]
Please use the developer mailing lists for such questions: https://docs.bigbluebutton.org/2.2/getting-help.html#help-developing-bigbluebutton
