### ISSUE TITLE
apt upgrade destroys STUN/TURN config

### ISSUE THREAD

**Issue by Natureshadow** [bigbluebutton/bigbluebutton#10258]
For some time now, apt-upgrading bigbluebutton (most recently, to 2.2.23) destroyed `/usr/share/bbb-web/WEB-INF/classes/spring/turn-stun-servers.xml` by overwriting it completely, without any questions and without any notice.

Please stop destroying configuration when doing (security) updates!

**Comment by matiasilva** [comment]
This is expected behavior (https://docs.bigbluebutton.org/2.2/customize.html#automatically-apply-configuration-changes-on-restart). I recommend building your script or using ansible to ensure a consistent configuration. Feel free to email the mailing lists for more support requests.
