### ISSUE TITLE
By Default Server Server URL Configured as HTTPS, How can Remove S and change to HTTP

### ISSUE THREAD

**Issue by rakheshthayyur** [bigbluebutton/bigbluebutton#10253]
By Default Server Server URL Configured as HTTPS, How can Remove S and change to HTTP

**Comment by matiasilva** [comment]
HTTP and HTTPS are protocols. Most modern websites use secure connections over TLS/SSL this is called HTTPS. If you change the protocol to HTTP your instance will be unusable for users as most modern browsers only allow transmitting webcams and user media over HTTPS. So I suggest you keep it as it is, unless there's a good reason to do so. Please use the mailing lists for similar questions: https://docs.bigbluebutton.org/2.2/getting-help.html#help-installing-or-running-bigbluebutton
