### ISSUE TITLE
Best scenario for 150 people in a web conference

### ISSUE THREAD

**Issue by ArmanEsf** [bigbluebutton/bigbluebutton#10259]
Hi everybody,
we have a very important web conference upcoming and it's gonna about 150 people in it at the same time!
I'm wondering how should I deploy BBB for the best performance?

First method :
install a BBB latest release (2.2.22) on a server with the maximum hardware that it support and everything alongside in a single server: BBB( with all its components), Greenlight for the administration.

the second one :
should I use a good server for BBB itself, and set up a TURN server? and install Greenlight on one of these servers?

or any idea I haven't thought through let me know :heart: 

Thanks in advance and for such a great app.

**Comment by matiasilva** [comment]
Hi. It is recommended that you keep sessions below 100 participants as per the documentation. That said, you may be able to accomplish a meeting of such size provided your users are very well behaved, this means very few cameras and not many events or chat.

It seems you are misunderstanding the role of a TURN server, it has little to do with performance. You should install a TURN server regardless to allow users behind restrictive firewalls to access your session. Greenlight is not resource intensive so you can install it on the same server. I suggest you read the documentation for the recommended specification. You should find a good compromise between high single threaded performance (node process is single threaded) and many cores (for freeswitch and kurento). There was a change released tto BBB not too long ago that really improved performance so I'm curious to hear how you get along. In any case, this is not the place for such questions and I ask that you head to the mailing lists and read the documentation: https://docs.bigbluebutton.org/2.2/getting-help.html#help-installing-or-running-bigbluebutton.

Good luck !
