### ISSUE TITLE
Scalelite AGPL license

### ISSUE THREAD

**Issue by reb88** [bigbluebutton/bigbluebutton#10256]
We planning to use 2 bbb servers with scalelite on our saas app project,
but unlike BBB(LGPL), scalelite released under AGPLv3 license for some reason.

if we use scalelite for just load balancing, do we have to make our all private project components open source?

**Comment by matiasilva** [comment]
Please open this issue in the scalelite repository.

My personal opinion is that if you develop something that you think others may enjoy, you should contribute back to the community.
