### ISSUE TITLE
sort of user names in Persian language is not completely alphabetical

### ISSUE THREAD

**Issue by mailalaki** [bigbluebutton/bigbluebutton#10250]
**Describe the bug**
order of users in the user panel when their name is in Persian is not completely alphabetically. I think it is because the letters of the Arabic alphabet are the basis of the sort. Because it puts only the letters گ, چ, پ, ژ, ک at the bottom of the list.
The letters of the Persian and Arabic alphabets are in most cases the same, and in Persian the calligraphy of the letters ک and ی is different, and in Arabic there are no letters گ, چ, پ, ژ from the Persian letters.
This is important for us because we do the presence and absence of people by exporting the names of current users and it is based on this order. It is also difficult to find the desired name when there are many users.

**Screenshots**
![ordersssss](https://user-images.githubusercontent.com/13551603/89978698-6023b200-dc83-11ea-9760-6a514329e89d.PNG)

**BBB version (optional):**
BigBlueButton Server 2.2.21

**Comment by pedrobmarin** [comment]
Same for accented initials.
