### ISSUE TITLE
Loading Presentation Dialog Displays 2x

### ISSUE THREAD

**Issue by bayden10** [bigbluebutton/bigbluebutton#10266]
[BBB v2.2.22]

Copied from greenlight closed [Issue #2012](https://github.com/bigbluebutton/greenlight/issues/2012)

When starting a session with the following room document presentation extensions

DOCX - XLSX - PPTX - ODT

The loading presentation dialog displays twice.

doubling of default-load
![doubling of default-load](https://user-images.githubusercontent.com/22577485/90261559-238abe80-de1b-11ea-82ca-8ccc541a635a.png)

**Comment by jdaviescoates** [comment]
I've noted this issue too, although when on my mobile (Android 8.1.0, Firefox 80.1.3) I actually get the dialogue FOUR times:

![4_dialogues_on_mobile](https://user-images.githubusercontent.com/2113743/93996698-75afef80-fd8a-11ea-82b1-1b200c22eb94.png)

However, having played around a little, it seems this only happens to me when I'm the first person in a room.  It seems that if I join the room after someone else is already in the room, I only get the dialogue once (both on laptop and browser).  Hopefully this'll help debug.
