### ISSUE TITLE
Share webcam not working

### ISSUE THREAD

**Issue by cisuna** [bigbluebutton/bigbluebutton#10260]
Describe the bug
After start sharing my webcam nothing happens.
Got this error in chrome console and also for screensharing.

![bbb_webcam_console_error](https://user-images.githubusercontent.com/40353324/90125766-d9460680-dd62-11ea-9f64-3e5f873e1a7e.PNG)

To Reproduce

Start session
Share webcam

Expected behavior
Shared video should be visible

**BBB version
bbb-html5 1:2.2.0-992 amd64 The HTML5 components for BigBlueButton

Desktop:
OS: Windows
Browser: Chrome 84

**Comment by matiasilva** [comment]
Please post in https://groups.google.com/forum/#!forum/bigbluebutton-setup for support.
