### ISSUE TITLE
Can I show the live Webcam of 100 participants with page scrolling during runing the single session?

### ISSUE THREAD

**Issue by alamgir-bd** [bigbluebutton/bigbluebutton#10267]
Hello!

Recently I build BBB for my Office. My management want to show Live Camera of all the participants during the session. Last day 
session joined 70 participants. But cann't show all participants live cam. Only 8-10 live camera showing. Is there any limitations. If not how I resolve the issues?

Thanks
Alamgir

**Comment by prlanzarin** [comment]
You simply can't right now. The system don't scale that far up as it is now.

Also, this is not an issue. This is a support question. Try searching through the github issues first.
https://github.com/bigbluebutton/bigbluebutton/issues/9655, https://github.com/bigbluebutton/bigbluebutton/issues/9392.
