### ISSUE TITLE
blank blue screen on join meeting

### ISSUE THREAD

**Issue by farbod302** [bigbluebutton/bigbluebutton#10264]
when join class just show blank blue screen

everything is ok on bbb-conf --status and --check

my server ip:http://49.12.60.247/

api demo installed

console err on join:
(index):58 Uncaught ReferenceError: checkform is not defined
    at HTMLFormElement.onsubmit 

console err after join:

Uncaught TypeError: Cannot set property 'ondevicechange' of undefined
    at new T (faaf19482693ee628033a6a7d1d2bbf12b5688a1.js?meteor_js_resource=true:121)
    at service.js (faaf19482693ee628033a6a7d1d2bbf12b5688a1.js?meteor_js_resource=true:121)
    at g (faaf19482693ee628033a6a7d1d2bbf12b5688a1.js?meteor_js_resource=true:7)
    at d.n [as require] (faaf19482693ee628033a6a7d1d2bbf12b5688a1.js?meteor_js_resource=true:7)
    at d.i [as link] (faaf19482693ee628033a6a7d1d2bbf12b5688a1.js?meteor_js_resource=true:9)
    at component.jsx (faaf19482693ee628033a6a7d1d2bbf12b5688a1.js?meteor_js_resource=true:121)
    at g (faaf19482693ee628033a6a7d1d2bbf12b5688a1.js?meteor_js_resource=true:7)
    at d.n [as require] (faaf19482693ee628033a6a7d1d2bbf12b5688a1.js?meteor_js_resource=true:7)
    at d.i [as link] (faaf19482693ee628033a6a7d1d2bbf12b5688a1.js?meteor_js_resource=true:9)
    at container.jsx (faaf19482693ee628033a6a7d1d2bbf12b5688a1.js?meteor_js_resource=true:121)
 

- OS:ubuntu 16
 test all browsers same at all

its ok on my vm virtualBox but have issue on external server

![Screenshot from 2020-08-13 21-17-55](https://user-images.githubusercontent.com/58918958/90230197-6dc96b00-de2e-11ea-9297-969091a11b86.png)

**Comment by matiasilva** [comment]
For support requests, use the mailing list: https://groups.google.com/forum/m/#!forum/bigbluebutton-setup

**Comment by andrekutianski** [comment]
Have you installed from ssh script?

**Comment by farbod302** [comment]
hi
yes
  -v x-22

any splotion?

**Comment by andrekutianski** [comment]
I have same problem here, try 4 installations and all crashed

**Comment by prlanzarin** [comment]
The setup in the screenshot is using plain HTTP. You need HTTPS. I might add an additional check to the ondevicechange listener for .23 so it doesn't crash, but you still need SSL properly setup.

**Comment by armanexplorer** [comment]
I'm surprised by BBB installation document!
The document never talk about requirement of SSL certificate for demo

BUT THE FACT IS:

`You must have an SSL certificate, even for demo! `

BBB, Please "obviously" add this in your document.

**Comment by matiasilva** [comment]
Nowadays, almost everything should be accessed via HTTPS and with Let's Encrypt, there's really no excuse for not doing SSL. What's more, WebRTC only works in browsers if accessed with SSL, so, in my opinion, it's pretty obvious that SSL needs to be done.

**Comment by ThBa** [comment]
Hello, I had the same issue.

And while indeed it doesn't work in http, we just ask to make it clearer in the doc. Even [screenshots](https://docs.bigbluebutton.org/2.2/install.html#5-install-api-demos-optional) in the installation document are showing that it worked at some point in http.

Anyway, if someone else encounter the same issue, find this issue and just want to try this software on a local machine you still can use a self signed certificate follow the [SSL parts on the installation document](https://docs.bigbluebutton.org/2.2/install.html#configure-ssl-on-your-bigbluebutton-server) and also add it to java's keystore.
```bash
mkdir --parents /etc/nginx/ssl/
openssl req -x509 -nodes -days 365 -newkey rsa:4096 -keyout /etc/nginx/ssl/bbb.lan.key -out /etc/nginx/ssl/bbb.lan.crt -subj "/CN=bbb.lan"
keytool -import -alias bbb.lan -file /etc/nginx/ssl/bbb.lan.crt -keystore /etc/ssl/certs/java/cacerts -storepass changeit
```

**Comment by ffdixon** [comment]
We've updated the docs so it's more clear that you can't run BigBlueButton without an SSL certificate.  Also removed the old screen shots that were showing the client loading with an IP address.

  https://docs.bigbluebutton.org/2.2/install.html#4--install-bigbluebutton
