### ISSUE TITLE
All cameras flipped in 2.2.22

### ISSUE THREAD

**Issue by gnaegi** [bigbluebutton/bigbluebutton#10263]
**Describe the bug**
The camera images produced for all meeting participant are flipped (mirrored). While the flipped images is absolute required for your own video it does not make sense to have the other participants video being flipped. 

**To Reproduce**
1. Go to a meeting with some participants that share the camera
2. Tell the other people the raise the left hand
3. You will see them raising the right hand...

**Expected behavior**
Flip/mirror only your own video image. 

**BBB version (optional):**
root@bigbluebutton:~# bbb-conf --check
BigBlueButton Server 2.2.22 (2086)

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser: Chrome
 - Version 84.0.4147.125

**Comment by ryprfpryr** [comment]
@gnaegi you can toggle webcam mirroring on/off with this value in /usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml

`    mirrorOwnWebcam: false
`

**Comment by prlanzarin** [comment]
@gnaegi Yes, sorry, I botched it in .22 while backporting some stuff from 2.3. I'll fix it for .23.

**Comment by gnaegi** [comment]
@prlanzarin Thanks for fixing it, I appreciate it!
