### ISSUE TITLE
BBB not working on Webview iOS app

### ISSUE THREAD

**Issue by xiaozhouboy** [bigbluebutton/bigbluebutton#10261]
![Simulator Screen Shot - iPhone 8 - 2020-08-13 at 20 22 36](https://user-images.githubusercontent.com/15812647/90133915-e1259b00-dda2-11ea-8dad-c21cb5609727.png)

**Comment by GergesEid** [comment]
I added this line of code and it will works fine with me.
Add it in viewDidLoad

myWKWebView.customUserAgent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.97 Safari/537.36"
