### ISSUE TITLE
Desktop Sharing doesn't not notify presenter if it has been disconnected

### ISSUE THREAD

**Issue by bigbluebutton-issue-import** [bigbluebutton/bigbluebutton#1027]
Originally reported on Google Code with ID 272

```
What steps will reproduce the problem?
1.  Start Desktop Sharing
2.  Minimize browser Window
3.

If the BigBlueButton client looses connection with the server, the user 
will get a "You have been logged out message" in the client; however, if 
the browser is minimized, then the presenter will not see this message.

They will not know that desktop sharing has stopped broadcasting until a 
student notifies them.

Is it possible to have the desktop share applet detect when it's no longer 
connected and notify the user with a pop-up?
```

Reported by `ffdixon` on 2009-12-14 00:34:58

**Comment by ffdixon** [comment]
We've improved this in BigBlueButton 1.0 by always playing a sound when the user leaves the audio channel.

This way, if they are sharing their desktop with a minimized client and that client gets disconnected, they will here a sound when the audio connection gets disconnected as well.

**Comment by ffdixon** [comment]
Merged into https://github.com/bigbluebutton/bigbluebutton/issues/5707
