### ISSUE TITLE
Does there is max number of users in breakout room in the same time 

### ISSUE THREAD

**Issue by ElsayedAwdElsayed** [bigbluebutton/bigbluebutton#10276]
I ask about the maximum number of participating users in breakout room or it is include unlimited number of users  as I have see in the documentation 

The default max users in conference 

![max-default](https://user-images.githubusercontent.com/10967608/90393149-76b97700-e090-11ea-9d9c-202c193a3349.PNG)

Does this configuration applied for the breakout room users ?
Does I increase the number of breakout rooms ?

**Comment by matiasilva** [comment]
Breakout rooms are similar to normal rooms in this respect, so I would expect this setting to apply.
