### ISSUE TITLE
Microphone is working, but HTML5 client is still stuck at "Connecting to echo test"

### ISSUE THREAD

**Issue by Fensterbank** [bigbluebutton/bigbluebutton#10284]
**Describe the bug**
I just upgraded BigBlueButton with the system's packaging system.
After I fixed all resetted customizations I tested it and sadly, conferences aren't working anymore.
When I join with microphone, the dialog "Connecting to echo test" is shown and won't go away. But I can hear my echo and technically the conference is working, so the people can hear each other. If only the dialog would go away...

**To Reproduce**
1. Start a conference
2. Select "With Microphone"
3. Hear your echo while seeing "Connecting to echo test"

**Expected behavior**
The Echo Test dialog should continue and I should be able to confirm the functionality and have a meeting.

**Actual behavior**
The dialog won't do anything and is blocking the whole UI. No conference without Echo Test, therefore conferences are not possible anymore.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/1684826/90486426-35c96d00-e139-11ea-8c03-38874bf2ed46.png)

**BBB version (optional):**
```
ii  bbb-apps                               1:2.2.0-47                                      amd64        BigBlueButton applications for Red5
ii  bbb-apps-akka                          2.2.0-89                                        all          BigBlueButton Apps (Akka)
ii  bbb-apps-screenshare                   1:2.2.0-47                                      amd64        BigBlueButton screenshare module for Red5
ii  bbb-apps-sip                           1:2.2.0-11                                      amd64        BigBlueButton SIP module for Red5
ii  bbb-apps-video                         1:2.2.0-44                                      amd64        BigBlueButton video module for Red5
ii  bbb-apps-video-broadcast               1:2.2.0-8                                       amd64        BigBlueButton video broadcast module for Red5
ii  bbb-client                             1:2.2.0-40                                      amd64        BigBlueButton Flash client
ii  bbb-config                             1:2.2.0-201                                     amd64        BigBlueButton configuration utilities
rc  bbb-demo                               1:2.2.0-9                                       amd64        BigBlueButton API demos
ii  bbb-etherpad                           1:2.2.0-58                                      amd64        The EtherPad Lite components for BigBlueButton
ii  bbb-freeswitch-core                    2:2.2.0-112                                     amd64        BigBlueButton build of FreeSWITCH
ii  bbb-freeswitch-sounds                  1:1.6.7-6                                       amd64        FreeSWITCH Sounds
ii  bbb-fsesl-akka                         2.2.0-67                                        all          BigBlueButton FS-ESL (Akka)
ii  bbb-html5                              1:2.2.0-992                                     amd64        The HTML5 components for BigBlueButton
ii  bbb-mkclean                            1:0.8.7-3                                       amd64        Clean and optimize Matroska and WebM files
ii  bbb-playback-presentation              1:2.2.0-32                                      amd64        BigBluebutton playback of presentation
ii  bbb-record-core                        1:2.2.0-68                                      amd64        BigBlueButton record and playback
ii  bbb-red5                               1:1.0.10-16                                     amd64        The Red5 server for BigBlueButton
ii  bbb-transcode-akka                     2.2.0-8                                         all          BigBlueButton Transcoder
ii  bbb-web                                1:2.2.0-135                                     amd64        BigBlueButton API
ii  bbb-webrtc-sfu                         1:2.2.0-102                                     amd64        BigBlueButton WebRTC SFU
ii  bigbluebutton                          1:2.2.0-5                                       amd64        Open source web conferencing platform (bbb)
```

**Desktop (please complete the following information):**
- Linux
- Mozilla Firefox 79
- Chromium 84

**Smartphone (please complete the following information):**
 - Device: Android 10
 - Browser Mozilla Firefox

**Additional context**
Seems to be a problem with the HTML5 client and appears on all devices.
If I set `skipCheck: true` in `/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml`, the conference will work too, but the dialog stucks at "Connecting...".

**Comment by Fensterbank** [comment]
I just found another issue describing my experience.
The [last comment](https://github.com/bigbluebutton/bigbluebutton/issues/9406#issuecomment-669986972) fixed the problem for me.

Just running `apt-get install bbb-apps-sip bbb-config bbb-freeswitch-core bbb-fsesl-akka bbb-html5 bbb-web --reinstall` and make the customizations again fixed the issue.

**Comment by blu-IT** [comment]
I am facing this problem too! 

But reinstalling everything might fix the problem for the moment, but what if it happens again (and again...)?

**Comment by guska42** [comment]
hi

i tired apt-get install bbb-apps-sip bbb-config bbb-freeswitch-core bbb-fsesl-akka bbb-html5 bbb-web --reinstall but not works for me. And i also tired beta line but the same. For now i reverted my version from my snapshot but is there any good solutions for fixing that problem ?
thank you

**Comment by matiasilva** [comment]
Follow the instructions for getting help and don't revive an old issue, please. https://docs.bigbluebutton.org/2.2/getting-help.html

**Comment by robregonm** [comment]
> Follow the instructions for getting help and don't revive an old issue, please. https://docs.bigbluebutton.org/2.2/getting-help.html

I think that reportings are not "reviving" an issue, since it's still alive ;-)
It's an actual issue.
I'm already aware that i's a "know issue" in BBB, after each upgrade I've got to check the echo if it fails (failing after each upgrade with no exception unfortunately)

**Comment by ffdixon** [comment]
You need to do a `bbb-conf --setip` after each upgrade to re-apply the hostname to all of BigBluebutton's configuration files.

**Comment by guska42** [comment]
> You need to do a `bbb-conf --setip <hostname>` after each upgrade to re-apply the hostname to all of BigBluebutton's configuration files.

thank you very much, that was very helpful. After --setip command the echo stuck situations gone.

**Comment by marinasigona** [comment]
> You need to do a `bbb-conf --setip <hostname>` after each upgrade to re-apply the hostname to all of BigBluebutton's configuration files.

Great this solved mine. works perfect now. thank you

**Comment by basti1499** [comment]
> You need to do a `bbb-conf --setip <hostname>` after each upgrade to re-apply the hostname to all of BigBluebutton's configuration files.

Thank you so much for this! Worked perfectly fine.

**Comment by TheJJ** [comment]
The reason seems to be that the glorious `bbb-conf --setip` does not only set IPs, but also sets up audio passwords:

https://github.com/bigbluebutton/bigbluebutton/blob/v2.2.28/bigbluebutton-config/bin/bbb-conf#L1998-L2008

When those are not set, the audio connection is established by the browser to freeswitch, but not handled correctly on server side then.
