### ISSUE TITLE
WebRTC functions not working in firefox

### ISSUE THREAD

**Issue by Marsimplodation** [bigbluebutton/bigbluebutton#10286]
Hello,

My Problem is, that I'm not able to use any webrtc function in firefox, with the html5 client. In chrome everything works perfectly fine, I can share my screen, I can use my webcam and it gets shown. In Firefox I got a loadingscreen each time I try to use webrtc functions. When I try to share my screen via firefox, I can see the screen in chrome, but not in firefox
Below is a screenshot how it looks like. The two left Browsers are Chrome and there it works like it should and right is Firefox, where it does not work.

I hope Someone can help me to find the problem

![image](https://user-images.githubusercontent.com/46057569/90517783-2876a780-e166-11ea-9d40-c5d411886789.png)

**Comment by prlanzarin** [comment]
What BBB build is that??

**Comment by Marsimplodation** [comment]
I installed it recently with apt-get install. bbb-vonf --version says its version 2.0

and befor it gets asked, all services are active

> root@bbb:~# bbb-conf --status
> red5 ——————————————————► [✔ - active]
> tomcat7 ———————————————► [✔ - active]
> nginx —————————————————► [✔ - active]
> freeswitch ————————————► [✔ - active]
> redis-server.service ——► [✔ - active]
> bbb-apps-akka —————————► [✔ - active]
> bbb-transcode-akka ————► [✔ - active]
> bbb-fsesl-akka ————————► [✔ - active]
> mongod ————————————————► [✔ - active]
> bbb-html5 —————————————► [✔ - active]
> bbb-webrtc-sfu ————————► [✔ - active]
> kurento-media-server ——► [✔ - active]

**Comment by prlanzarin** [comment]
You're using 2.0. There's no use debugging that. [Please install 2.2](https://github.com/bigbluebutton/bbb-install).

**Comment by Marsimplodation** [comment]
thanks, I don't know, why it installed version 2.0 in the first place, I mean I installed it two weeks ago, but with version 2.2 its now working
