### ISSUE TITLE
'-' char in .env

### ISSUE THREAD

**Issue by MichalGizaSrv** [bigbluebutton/bigbluebutton#10282]
Hi! I use this SMTP server: email-smtp.us-east-2.amazonaws.com. When I paste it in .env file, it has other colour: 

![image](https://user-images.githubusercontent.com/58888243/90423881-8b603400-e0bd-11ea-8ce2-e38bd0a2331e.png)

Also, when I run _docker run --rm --env-file .env bigbluebutton/greenlight:v2 bundle exec rake conf:check_ I see this error:

![image](https://user-images.githubusercontent.com/58888243/90423580-06751a80-e0bd-11ea-85a4-4f14d7169b2c.png)

Any workaround?

**Comment by matiasilva** [comment]
This is the repository for BigBlueButton, you're looking for Greenlight: https://github.com/bigbluebutton/greenlight
