### ISSUE TITLE
Does BigblueButton making Survey ?

### ISSUE THREAD

**Issue by ElsayedAwdElsayed** [bigbluebutton/bigbluebutton#10292]
I know that  we can make a Poll in Bigbluebutton but I have searched  for making survey but I did't find .

So is supported right now ?

**Comment by matiasilva** [comment]
Hi, could you please elaborate what you are looking for? BigBlueButton is a video conferencing software not a survey software, by the way.

**Comment by ElsayedAwdElsayed** [comment]
Okey I know that BigBlueButton is a Video conference but I am  asking about the existence of survey feature during the Video conference.

**Comment by iSamof** [comment]
Yes BBB does have surveys. They are called "polls" in BBB And they are very good. More improvements are being made. 

Checkout the demo site at https://demo.bigbluebutton.org/gl   

... use the '+' sign and "Start a Poll"

**Comment by matiasilva** [comment]
I would have suggested polls, but given that @ElsayedAwdElsayed mentioned the poll feature I suspect they are looking for something else. Could you further elaborate what is different between a survey and a poll for you?

**Comment by iSamof** [comment]
Whoopsy ... yes I missed the initial post. Then, I too don't know what is meant by a "survey feature during the Video conference" as opposed to a poll.
