### ISSUE TITLE
my bbb show error when trying to join a room : you must have the bigbluebutton html5 client installed to use this api demo

### ISSUE THREAD

**Issue by NOURELAINE** [bigbluebutton/bigbluebutton#10298]
hello, please i have an error when i try to join a room in bbb, it's show **you must have the bigbluebutton html5 client installed to use this api demo**
then it redirect me to a blue empty page, 

here is my output for bbb-conf --check and bbb-conf --status

root@bbb:~# bbb-conf --check

BigBlueButton Server 2.2.22 (2086)
                    Kernel version: 4.4.0-187-generic
                      Distribution: Ubuntu 16.04.7 LTS (64-bit)
                            Memory: 16414 MB
                         CPU cores: 4

/usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties (bbb-web)
       bigbluebutton.web.serverURL: http://192.168.17.176
                defaultGuestPolicy: ALWAYS_ACCEPT
                 svgImagesRequired: true

/etc/nginx/sites-available/bigbluebutton (nginx)
                       server name: 192.168.17.176
                              port: 80, [::]:80
                    bbb-client dir: /var/www/bigbluebutton

/var/www/bigbluebutton/client/conf/config.xml (bbb-client)
                Port test (tunnel): rtmp://192.168.17.176
                              red5: 192.168.17.176
              useWebrtcIfAvailable: true

/opt/freeswitch/etc/freeswitch/vars.xml (FreeSWITCH)
                       local_ip_v4: 192.168.17.176
                   external_rtp_ip: stun:stun.freeswitch.org
                   external_sip_ip: stun:stun.freeswitch.org

/opt/freeswitch/etc/freeswitch/sip_profiles/external.xml (FreeSWITCH)
                        ext-rtp-ip: $${local_ip_v4}
                        ext-sip-ip: $${local_ip_v4}
                        ws-binding: :5066
                       wss-binding: :7443

/usr/local/bigbluebutton/core/scripts/bigbluebutton.yml (record and playback)
                     playback_host: 192.168.17.176
                 playback_protocol: http
                            ffmpeg: 4.2.2-1bbb1~ubuntu16.04

/etc/bigbluebutton/nginx/sip.nginx (sip.nginx)
                        proxy_pass: 192.168.17.176

/usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml (Kurento SFU)
                        kurento.ip: 192.168.17.176
                       kurento.url: ws://127.0.0.1:8888/kurento
                    kurento.sip_ip: 192.168.17.176
                    localIpAddress: 192.168.17.176
               recordScreenSharing: true
                     recordWebcams: true
                  codec_video_main: VP8
               codec_video_content: VP8

/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml (HTML5 client)
                             build: 992
                        kurentoUrl: ws://192.168.17.176/bbb-webrtc-sfu
                  enableListenOnly: true

# Potential problems described below

# Warning: The API demos are installed and accessible from:
#
#    http://192.168.17.176
#
# and
#
#    http://192.168.17.176/demo/demo1.jsp
#
# These API demos allow anyone to access your server without authentication
# to create/manage meetings and recordings. They are for testing purposes only.
# If you are running a production system, remove them by running:
#
#    apt-get purge bbb-demo
-----------------------------------------------------------------------------------------
root@bbb:~# bbb-conf --status
nginx —————————————————► [✔ - active]
freeswitch ————————————► [✔ - active]
redis-server ——————————► [✔ - active]
bbb-apps-akka —————————► [✔ - active]
bbb-transcode-akka ————► [✔ - active]
bbb-fsesl-akka ————————► [✔ - active]
red5 ——————————————————► [✔ - active]
tomcat7 ———————————————► [✔ - active]
mongod ————————————————► [✔ - active]
bbb-html5 —————————————► [✔ - active]
bbb-webrtc-sfu ————————► [✔ - active]
kurento-media-server ——► [✔ - active]
etherpad ——————————————► [✔ - active]
bbb-web ———————————————► [✔ - active]

**Comment by matiasilva** [comment]
For support requests, use https://groups.google.com/forum/#!forum/bigbluebutton-setup.
