### ISSUE TITLE
why I can not download modifed presentation in BigBlueButton

### ISSUE THREAD

**Issue by amira133** [bigbluebutton/bigbluebutton#10308]
hi ,
I upload a pdf and then modifed that pdf like this:
![image](https://user-images.githubusercontent.com/27830573/90977970-301bbf00-e55f-11ea-81e3-cf053c29fa17.png)

but when I download it, it download Original file and shows this:
![image](https://user-images.githubusercontent.com/27830573/90977995-6eb17980-e55f-11ea-90fa-7ad72f51d886.png)

**Comment by matiasilva** [comment]
Hi, it's not possible to download modified presentations. For more questions on how to use BigBlueButton, please use the mailing list: https://groups.google.com/forum/#!forum/bigbluebutton-users
