### ISSUE TITLE
Cannot destructure property 'color' of 'sender' as it is undefined.

### ISSUE THREAD

**Issue by nanovim** [bigbluebutton/bigbluebutton#10306]
**Describe the bug**
The room crashes while loading and only the dark blue background is loading.

**To Reproduce**
I know what happens but not actually how to reproduce it.
In the file: bigbluebutton-html5/imports/ui/components/chat/service.js on line 50 and following it says:

const sender = Users.findOne({ userId: message.sender },
      {
        fields: {
          color: 1, role: 1, name: 1, connectionStatus: 1,
        },
      });
    const {
      color,
      role,
      name,
      connectionStatus,
    } = sender;

For one reason or another, the sender becomes undefined and therefore crash.
I guess it was a user that did not use our SSO but just a temporary user and his/her
message survived longer than the user itself.

**Expected behavior**
Room loads and the client asks for joining audio.

**Actual behavior**
javascript exception and crash of the html6 client.

**Screenshots**

**BBB version (optional):**
BigBlueButton continually evolves. Providing the version/build helps us to pinpoint when an issue was introduced.
Example:
$ sudo bbb-conf --check | grep BigBlueButton
BigBlueButton Server 2.2.2 (1816)

**Desktop (please complete the following information):**
 - OS:  Open Suse Tumblewees
 - Browser Chrome
 - Version 

**Additional context**

**Comment by pedrobmarin** [comment]
@Tainan404 is this something we should take a closer look after all the changes done in chat/users?
