### ISSUE TITLE
Error: Unable to connect to port 1935 (RTMP) on chatxlive.com

### ISSUE THREAD

**Issue by spinovation** [bigbluebutton/bigbluebutton#10325]
Hello @ffdixon 
I am getting issue RTMP when I restart bbb-conf --restart
I have setup bigbluebutton on server
Please help me

ubuntu@ip-172-31-69-81:~$ sudo bbb-conf --restart
# IP does not match:
#                           IP from ifconfig: 172.31.69.81
#   /etc/nginx/sites-available/bigbluebutton: chatxlive.com
# Warning: API URL IPs do not match host:
#
#                                IP from ifconfig: 172.31.69.81
#  /var/lib/tomcat7/demo/bbb_api_conf.jsp: chatxlive.com

# Warning: Detected the directory
#    /var/bigbluebutton/screenshare
# is not owned by red5
Restarting BigBlueButton 2.2.21 ...
Stopping BigBlueButton

Applying updates in /etc/bigbluebutton/bbb-conf/apply-config.sh: 
  - Enable Firewall and opening 22/tcp, 80/tcp, 443/tcp and 16384:32768/udp
Skipping adding existing rule
Skipping adding existing rule (v6)
Skipping adding existing rule
Skipping adding existing rule (v6)
Skipping adding existing rule
Skipping adding existing rule (v6)
Skipping adding existing rule
Skipping adding existing rule (v6)
Firewall is active and enabled on system startup

Starting BigBlueButton
....................
#    sip may not have started properly
#    video may not have started properly

# Potential problems described below
# IP does not match:
#                           IP from ifconfig: 172.31.69.81
#   /etc/nginx/sites-available/bigbluebutton: chatxlive.com
# Warning: API URL IPs do not match host:
#
#                                IP from ifconfig: 172.31.69.81
#  /var/lib/tomcat7/demo/bbb_api_conf.jsp: chatxlive.com

# Warning: Detected the directory
#    /var/bigbluebutton/screenshare
# is not owned by red5
.................
# Error: Unable to connect to port 1935 (RTMP) on chatxlive.com

# Warning: The setting of 3.234.59.121 for proxy_pass in
#
#    /etc/bigbluebutton/nginx/sip.nginx
#
# does not match the local IP address (172.31.69.81).
# (This is OK if you've manually changed the values)

# Warning: The API demos are installed and accessible from:
#
#    https://chatxlive.com
#
# and
#
#    https://chatxlive.com/demo/demo1.jsp
#
# These API demos allow anyone to access your server without authentication
# to create/manage meetings and recordings. They are for testing purposes only.
# If you are running a production system, remove them by running:
#
#    apt-get purge bbb-demo

# Warning: found only 2 cores, whereas this server should have (at least) 4 CPU cores
# to run BigBlueButton in production.
#
#   https://docs.bigbluebutton.org/install/install.html#minimum-server-requirements

![image](https://user-images.githubusercontent.com/15327734/91182402-c2f75d80-e707-11ea-8b3d-d4588412a1f4.png)

**Comment by matiasilva** [comment]
For support requests, use the mailing list: https://groups.google.com/forum/#!forum/bigbluebutton-setup. Also, increase your core count.
