### ISSUE TITLE
Blue window in HTML5 Client

### ISSUE THREAD

**Issue by Steback** [bigbluebutton/bigbluebutton#10326]
I installed BBB using the bbb-install.sh script,  all the installation process was successfully, but when I try to test de API Demo, first it show a white window with this message "You must have the BigBlueButton HTML5 client installed to use this API demo.", later the window have a blue color and nothing happend. 

I don't know if my server specs affect, I read the minimal requirementes, and It say that for a development server with 2 CPU core is fine.

My Server specs are this:
2 CPU core
4G Ram
80G Disk
![Screenshot_20200825_145905](https://user-images.githubusercontent.com/31460273/91222088-4d2dca80-e6e4-11ea-9a33-507066601453.png)
![Screenshot_20200825_144502](https://user-images.githubusercontent.com/31460273/91222109-53bc4200-e6e4-11ea-870f-477b6164c204.png)
![Screenshot_20200825_144503](https://user-images.githubusercontent.com/31460273/91222132-5880f600-e6e4-11ea-9f49-b93e640e4e6c.png)

**Comment by prlanzarin** [comment]
You're probably in a HTTP environment. Set up SSL in your BBB instance.

There's a crash going on with non secure environments since .22, won't be fixed in .23, prolly will be fixed in .24.
