### ISSUE TITLE
Getting blue screen after click on START meeting button

### ISSUE THREAD

**Issue by Amritmatti** [bigbluebutton/bigbluebutton#10323]
Hello all,
I have just installed big blue button from script wget -qO- https://ubuntu.bigbluebutton.org/bbb-install.sh | bash -s -- -w -v xenial-22 -a -w
But after insallation am able to login and when click on start button getting blue screen and getting below error in browser's inspect console window;;
Please help Thanks in advance.

Uncaught TypeError: navigator.mediaDevices is undefined
    T http://ip/html5client/faaf19482693ee628033a6a7d1d2bbf12b5688a1.js?meteor_js_resource=true:121
    js http://ip/html5client/faaf19482693ee628033a6a7d1d2bbf12b5688a1.js?meteor_js_resource=true:121
    g http://ip/html5client/faaf19482693ee628033a6a7d1d2bbf12b5688a1.js?meteor_js_resource=true:7
    n http://ip/html5client/faaf19482693ee628033a6a7d1d2bbf12b5688a1.js?meteor_js_resource=true:7
    i http://ip/html5client/faaf19482693ee628033a6a7d1d2bbf12b5688a1.js?meteor_js_resource=true:9
    jsx http://ip/html5client/faaf19482693ee628033a6a7d1d2bbf12b5688a1.js?meteor_js_resource=true:121
    g http://ip/html5client/faaf19482693ee628033a6a7d1d2bbf12b5688a1.js?meteor_js_resource=true:7
    n http://ip/html5client/faaf19482693ee628033a6a7d1d2bbf12b5688a1.js?meteor_js_resource=true:7
    i http://ip/html5client/faaf19482693ee628033a6a7d1d2bbf12b5688a1.js?meteor_js_resource=true:9
    jsx http://ip/html5client/faaf19482693ee628033a6a7d1d2bbf12b5688a1.js?meteor_js_resource=true:121
    g http://ip/html5client/faaf19482693ee628033a6a7d1d2bbf12b5688a1.js?meteor_js_resource=true:7
    n http://ip/html5client/faaf19482693ee628033a6a7d1d2bbf12b5688a1.js?meteor_js_resource=true:7
    i http://ip/html5client/faaf19482693ee628033a6a7d1d2bbf12b5688a1.js?meteor_js_resource=true:9

**Comment by prlanzarin** [comment]
You're using a non secure deployement. Please setup SSL in your BBB instance.

**Comment by DevOpsTechy** [comment]
Thanks @prlanzarin 

but after adding SSL I am getting this
greenlight-v2 | Error during failsafe response: bbb.igyani.com is not a safe host
greenlight-v2 |   /usr/src/app/app/controllers/application_controller.rb:51:in `block_unknown_hosts'
greenlight-v2 |   /usr/src/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.3/lib/active_support/callbacks.rb:426:in `block in make_lambda'
greenlight-v2 |   /usr/src/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.3/lib/active_support/callbacks.rb:198:in `block (2 levels) in halting'
greenlight-v2 |   /usr/src/app/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.4.3/lib/abstract_controller/callbacks.rb:34:in `block (2 levels) in <module:Callbacks>'
greenlight-v2 |   /usr/src/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.3/lib/active_support/callbacks.rb:199:in `block in halting'
greenlight-v2 |   /usr/src/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.3/lib/active_support/callbacks.rb:513:in `block in invoke_before'
greenlight-v2 |   /usr/src/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.3/lib/active_support/callbacks.rb:513:in `each'
greenlight-v2 |   /usr/src/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.3/lib/active_support/callbacks.rb:513:in `invoke_before'
greenlight-v2 |   /usr/src/app/vendor/bundle/ruby/2.5.0/gems/activesupport-5.2.4.3/lib/active_support/callbacks.rb:131:in `run_callbacks'

**Comment by prlanzarin** [comment]
Can't help you with Greenlight stuff (because I know little about it). Suggest you see this through in greenlight's or bbb-setup's mailing lists.
