### ISSUE TITLE
Landscape mode on Safari (iOS) of BBB does not look good

### ISSUE THREAD

**Issue by ftrinco** [bigbluebutton/bigbluebutton#10331]
If a professor is sharing its camera and is showing a presentation, the presentation is too small and the size can't be changed
![IMG_3098](https://user-images.githubusercontent.com/63117500/91343868-83864b00-e7b3-11ea-9eac-5fdb028d532d.PNG)

**Comment by pedrobmarin** [comment]
@vitormateusalmeida is this something we can consider to be fixed with the side positioning of the cameras?
