### ISSUE TITLE
media server offline error 2001

### ISSUE THREAD

**Issue by naveen433** [bigbluebutton/bigbluebutton#10330]
I am trying and configuring bigbluebutton on vm having 16Gb and 12 cores behind NAT
i configured firewall and sip configuration, all are working fine.. except webcam sharing and screen sharing.
bbb--conf --check
BigBlueButton Server 2.2.23 (2106)
                    Kernel version: 4.15.0-112-generic
                      Distribution: Ubuntu 16.04.7 LTS (64-bit)
                            Memory: 16421 MB
                         CPU cores: 24

/usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties (bbb-web)
       bigbluebutton.web.serverURL: https://live.narayanaanglovedicschool.com
                defaultGuestPolicy: ALWAYS_ACCEPT
                 svgImagesRequired: true

/etc/nginx/sites-available/bigbluebutton (nginx)
                       server name: live.narayanaanglovedicschool.com
                              port: 80, [::]:80
                              port: 443 ssl
                    bbb-client dir: /var/www/bigbluebutton

/var/www/bigbluebutton/client/conf/config.xml (bbb-client)
                Port test (tunnel): rtmp://live.narayanaanglovedicschool.com
                              red5: live.narayanaanglovedicschool.com
              useWebrtcIfAvailable: true

/opt/freeswitch/etc/freeswitch/vars.xml (FreeSWITCH)
                       local_ip_v4: 192.168.0.231
                   external_rtp_ip: 103.105.103.5
                   external_sip_ip: 103.105.103.5

/opt/freeswitch/etc/freeswitch/sip_profiles/external.xml (FreeSWITCH)
                        ext-rtp-ip: $${external_rtp_ip}
                        ext-sip-ip: $${external_sip_ip}
                        ws-binding: :5066
                       wss-binding: 103.105.103.5:7443

/usr/local/bigbluebutton/core/scripts/bigbluebutton.yml (record and playback)
                     playback_host: live.narayanaanglovedicschool.com
                 playback_protocol: https
                            ffmpeg: 4.2.2-1bbb1~ubuntu16.04

/etc/bigbluebutton/nginx/sip.nginx (sip.nginx)
                        proxy_pass: 103.105.103.5

/usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml (Kurento SFU)
                        kurento.ip: 192.168.0.231
                       kurento.url: ws://127.0.0.1:8888/kurento
                    kurento.sip_ip: 192.168.0.231
                    localIpAddress: 192.168.0.231
               recordScreenSharing: true
                     recordWebcams: true
                  codec_video_main: VP8
               codec_video_content: VP8

/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml (HTML5 client)
                             build: 1006
                        kurentoUrl: wss://live.narayanaanglovedicschool.com/bbb-webrtc-sfu
                  enableListenOnly: true

# Potential problems described below
# IP does not match:
#                           IP from ifconfig: 192.168.0.231
#   /etc/nginx/sites-available/bigbluebutton: live.narayanaanglovedicschool.com

# Warning: The setting of 103.105.103.5 for proxy_pass in
#
#    /etc/bigbluebutton/nginx/sip.nginx
#
# does not match the local IP address (192.168.0.231).
# (This is OK if you've manually changed the values)

#
# Warning: Detected that systemctl does not define a UTF-8 language.
#
# To temporarily correct, run the command 
#
#   sudo systemctl set-environment LANG=en_US.UTF-8
#
# See https://docs.bigbluebutton.org/2.2/install.html#pre-installation-checks

bbb-conf --status
nginx —————————————————► [✔ - active]
freeswitch ————————————► [✔ - active]
redis-server ——————————► [✔ - active]
bbb-apps-akka —————————► [✔ - active]
bbb-transcode-akka ————► [✔ - active]
bbb-fsesl-akka ————————► [✔ - active]
red5 ——————————————————► [✔ - active]
tomcat7 ———————————————► [✔ - active]
mongod ————————————————► [✔ - active]
bbb-html5 —————————————► [✔ - active]
bbb-webrtc-sfu ————————► [✔ - active]
kurento-media-server ——► [✔ - active]
etherpad ——————————————► [✘ - failed]
bbb-web ———————————————► [✔ - active]

Please guide me how to resolve this.. 

Thanks

**Comment by matiasilva** [comment]
Hi, please check the docs (https://docs.bigbluebutton.org/) and if you need further support feel free to post in the mailing list: https://groups.google.com/forum/#!forum/bigbluebutton-setup
