### ISSUE TITLE
Firefox 80 return from fullscreen hides buttons at bottom of screen

### ISSUE THREAD

**Issue by caniwi** [bigbluebutton/bigbluebutton#10337]
**Describe the bug**
User running bigbluebutton on Firefox80.  User escapes from fullscreen mode and the buttons at the bottom of the window are not visible.  Resizing the window makes them re-appear.  This behaviour does not manifest itself with other backends after going fullscreen.

**To Reproduce**
1. Enter a bbb session.
2. Make a component (presentation, camera etc.) of the session fullscreen mode.
3. Escape from fullscreen mode.
4. Buttons along the bottom are hidden by the reduced component.
5. Resize the window changes the component and the buttons are revealed again.

**Expected behavior**
The component, when reduced from fullscreen mode, should reveal the action buttons.

**Actual behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser Firefox 80 (does not happen in Firefox 79, Chrome or Chromium)[e.g. Chrome, Safari]
 - Version  80

**Smartphone (please complete the following information):**

**Additional context**
Confirmed it happens in BigBlueButton 1008 and 980.  This does not happen with other apps (youtube, alfresco, lool) going to and from fullscreen mode.

**Comment by ffdixon** [comment]
Good catch!

**Comment by KDSBrowne** [comment]
There is already mention of this in #10155, It was introduced by #10144. I believe @vitormateusalmeida is working on it?

**Comment by prlanzarin** [comment]
I don't think it's related to that PR, @KDSBrowne. It happens on latest 2.2 as well, so probably something related to FF 80.

**Comment by KDSBrowne** [comment]
@prlanzarin I think your right

**Comment by KDSBrowne** [comment]
This issue seems to have been resolved in the latest version of FF `81.0 (64-bit)`

**Comment by caniwi** [comment]
I agree it does seem to be resolved in FF 81.0.
