### ISSUE TITLE
PPA timeout when installing in China

### ISSUE THREAD

**Issue by leoniscsem** [bigbluebutton/bigbluebutton#10344]
**Describe the bug**
Due to the Great Firewall of China, installing all the **bbb-*** packages fail after timing out. Their monitoring and deep package inspection system affects every self hosted PPA unlike those hosted on Launchpad. Even though the packages comprise only of ~230 MB in size, downloading them takes nearly two days, which of course then throws a time out error.

**Installation type**
installation via bbb-script

**Firewall and IP address type**
Hosted instance on Aliyun/Alibaba Web Services, firewall and ports configuration is set up perfectly fine.

**Additional context**
I had to manually download the deb packages from the PPA to one of my EU servers, then rsync them over to our Chinese server. The install script failed everytime before I took this step. In total the installation process took me about three days. I am especially concerned about updates, as we are using the 2.3-dev version of BBB.

Is there a way to mirror the packages on Launchpad or any other way? GitHub releases aren't a viable solution in China either, as after the last CCP congress in November last year the download speed from GitHub decreased massively (~12 KB/s on a machine with 800 Mbit connectivity), the "raw" subdomain is blocked entirely.

It's a pity, because China is the largest education market in the world. Not only because of the vast population of the country, but parents spend a significant amount on after-school education for their kids. BBB could have remarkable impact on the e-learning market, as proprietary competitors like Zoom really do not cut it (traffic monitoring). During the Covid period, online teaching business soared incredibly, creating a major change in the overall education sector. Schools shut down their physical locations and try everything to enter the online teaching market.

**Comment by jibon57** [comment]
As a workaround you can setup [shadowsocks](https://github.com/shadowsocks/shadowsocks-libev) in any of provider outside of Mainland prefer HongKong. After that setup proxy in apt of your BBB server. Now connection will be faster. We always followed that.

**Comment by basisbit** [comment]
@leoniscsem what alrernatives do you suggest rhe project could use as a long term solution? Is there any way to get the bbb package server allowlisted so thatit doesn't get throttled any more? Would a package mirror behind cloudflare hosted in Europe help?

**Comment by leoniscsem** [comment]
> @leoniscsem what alternatives do you suggest the project could use as a long term solution? 

It in fact is a dire situation. The only viable solution in my opinion is to mirror the BBB PPA on Launchpad, as they are approved by the Chinese authorities and mirrored on several university servers here.

>Is there any way to get the bbb package server allow-listed so that it doesn't get throttled any more? 

This is wishful thinking, because you are not a Chinese organisation, not under direct control of the relevant authority, and they have no means to control the data you put there. Please understand I cannot put more details here, since I live in China and my company is Chinese. As a foreign entity, you will never get past this.

> Would a package mirror behind cloudflare hosted in Europe help?

Cloudflare has their own system for China, this costs big time money. I do not think this is a solution, but maybe you can figure out a way?
[Cloudflare info about China](https://www.cloudflare.com/network/china/)

I can in fact establish a cooperation for this on a dedicated PPA mirror server, but then we still would have tight government control. At least they could hold our company accountable in case anything goes wrong and we hold all the necessary licences. But then the legal discussion and due diligence starts. In the long run, yes, we are willing to offer an open source cooperation, but then we need to find a solution for the traffic costs. Aliyun (Alibaba) is significantly more expensive than AWS or comparable services. I do not see our company perfectly suited to host the upgrade packages for competitors. Please understand, all this licensing is not cheap here, we just paid 40,000 RMB (EUR:RMB = 1:8) for a newly established licence just to run distance learning systems. Renewal per year costs us another 10,0000 RMB. This is the lowest cost in China, as our education company is registered in Wuhan. For Beijing or Shanghai, this can easily go up to 200,000 RMB.

If you can go with Launchpad for now, we are willing to contribute to set up the measures, so that the packages can be distributed there.

**Comment by leoniscsem** [comment]
> As a workaround you can setup [shadowsocks](https://github.com/shadowsocks/shadowsocks-libev) in any of provider outside of Mainland prefer HongKong. After that setup proxy in apt of your BBB server. Now connection will be faster. We always followed that.

I cannot give you details, but we also run a SOCKS5. No, this is not a solution, not even a workaround. The connection gets cut down to 5 kB/s after ~150 MB data transfer in curl. Otherwise I would not "complain" here. Besides, it is far more annoying to set up a socks client on a server to receive all the data through the proxy than to manually download the bbb packages. Did you really run the whole bbb script through a SOCKS proxy?? I admire your patience. You must have set your SSH timeout to "forever and ever", right?

**Comment by jibon57** [comment]
In my case I never saw download dropped to `5 kB/s`. Using `shadowsocks` I always get stable connection. It'll depend on the provider where you had setup `shadowsocks`. My provider has direct connectivity with Mainland China. Yes, having some dedicated solution will be be helpful but having those inside China will be expensive.

**Comment by basisbit** [comment]
Please provide a link to the "launchpad" software hosting that you are referring to.

Does only http80/https443 get throttled and would hosting the http server on another port work? How do you update your linux distribution and so on?

I wonder how other free/libre open source software projects like libreoffice handle this.

PS: AWS traffic costs are quite expensive - if Alijuan is even more expensive, then this might not be a good solution. A mirror operated by a university sounds much better.

**Comment by leoniscsem** [comment]
> Please provide a link to the "launchpad" software hosting that you are referring to.

There is already a BBB team existing on Launchpad, as [you can see here](https://launchpad.net/~bigbluebutton), but no PPA is created yet.

> Does only http80/https443 get throttled and would hosting the http server on another port work? How do you update your linux distribution and so on?

I am sure changing the ports won't do anything, it goes beyond that. I had some licensing issues for one of our platforms, so I kept changing the ports over and over. It became a game of whack-a-mole for weeks, yet they found out every slight change within 24 hours.

We do use the regular Canonical repos, which are being mirrored at university servers like Tsinghua, Shanghai, Hangzhou and the like. Aliyun provides PPA mirrors themselves, so that goes blazing fast.

> I wonder how other free/libre open source software projects like libreoffice handle this.

I use their Launchpad PPA, there is no issues with that. Yes, Launchpad PPAs are a bit slower than university hosted mirrors, but it is fine. Let's not forget that Canonical themselves operate Launchpad, and they of course have some agreement with the Chinese government. They also provide the Ubuntu Kylin system in cooperation with a Chinese organisation.

> PS: AWS traffic costs are quite expensive - if Alijuan is even more expensive, then this might not be a good solution. A mirror operated by a university sounds much better.

We are in touch with several universities, I could talk with several people if they would host the packages. Of course, this means I would only initiate the talks and you people talk to them yourselves.
Next I could reach out to the fine folks from Deepin Linux; they are based in Wuhan and distribute their packages worldwide. Perhaps we could ask them to host the BBB packages on their servers? As I am frequently going to Wuhan, I just could drop by at their premises and have a talk.
The Ubuntu Kylin maintainers could be the third option, but I do not know their package policy yet.

PS: I reached out to you on Gitter. Some topics might be a bit stupid to discuss here in an issue tracker.

**Comment by basisbit** [comment]
issue is still not solved. A few listed third party mirrors hosted by universities would probably solve the problem.

**Comment by leoniscsem** [comment]
Adding two mirrors of both the Nanjing and the Shanghai Jiao Tong university:

- https://mirror.sjtu.edu.cn/
- https://mirrors.nju.edu.cn/

[Shanghai Jiao Tong](https://www.sjtu.edu.cn/)

You can check out the packages they host there. There is a lot of third party software, which are not necessarily Ubuntu core packages. They are aware of the issues with the GFW, so I appreciate their efforts.

I have a friendly contact in the SJTU on management level, I could easily talk to him about mirroring, but as it is common in China, this would require me to get in touch with the BBB core team and get their approval first. I also know some people of Nanjing university, but they are researchers, so I do not think this might be of great help here. But if BBB reach out to them through the official channels, establishing a cooperation with them should be simple.
