### ISSUE TITLE
bug - 2.3-alpha-2 RTL Layout Manager #10144

### ISSUE THREAD

**Issue by Jossef-767** [bigbluebutton/bigbluebutton#10354]
when using RTL language. user list, wrong alignment and wrong spacing.
resizing user list and chat width Shows unexpected results.

**Comment by ffdixon** [comment]
Can you include a screen shot.

**Comment by KDSBrowne** [comment]
![image](https://user-images.githubusercontent.com/22058534/91669217-4c7ca600-eae1-11ea-88a7-62bc89e6f958.png)

**Comment by Goldenstarc** [comment]
I cant change locale at all!  (overrideLocale in settings.yml)
its fixed on en

**Comment by cod3r0k** [comment]
> after upgrading to 2.3-alpha2, I cant change locale at all! (overrideLocale in settings.yml)
> its fixed on en

What do you do @Hamid-Najafi , Was it resolved?
