### ISSUE TITLE
Error 1007 while connecting to Echo Test with Firefox

### ISSUE THREAD

**Issue by MeinhartEsrohr** [bigbluebutton/bigbluebutton#10356]
Hello Community,
I finally got BBB up and running, as we use a proxy server I also had to install a turn server.
I only have one problem left, when I start a session with Chrome everything works, but when I try to start a session with the FireFox, I get the error code 1007, the about: Webrtc Log shows the following:

`(registry/INFO) insert 'ice' (registry) succeeded: ice

(registry/INFO) insert 'ice.pref' (registry) succeeded: ice.pref

(registry/INFO) insert 'ice.pref.type' (registry) succeeded: ice.pref.type

(registry/INFO) insert 'ice.pref.type.srv_rflx' (UCHAR) succeeded: 0x64

(registry/INFO) insert 'ice.pref.type.peer_rflx' (UCHAR) succeeded: 0x6e

(registry/INFO) insert 'ice.pref.type.host' (UCHAR) succeeded: 0x7e

(registry/INFO) insert 'ice.pref.type.relayed' (UCHAR) succeeded: 0x05

(registry/INFO) insert 'ice.pref.type.srv_rflx_tcp' (UCHAR) succeeded: 0x63

(registry/INFO) insert 'ice.pref.type.peer_rflx_tcp' (UCHAR) succeeded: 0x6d

(registry/INFO) insert 'ice.pref.type.host_tcp' (UCHAR) succeeded: 0x7d

(registry/INFO) insert 'ice.pref.type.relayed_tcp' (UCHAR) succeeded: 0x00

(registry/INFO) insert 'stun' (registry) succeeded: stun

(registry/INFO) insert 'stun.client' (registry) succeeded: stun.client

(registry/INFO) insert 'stun.client.maximum_transmits' (UINT4) succeeded: 7

(registry/INFO) insert 'ice.trickle_grace_period' (UINT4) succeeded: 5000

(registry/INFO) insert 'ice.tcp' (registry) succeeded: ice.tcp

(registry/INFO) insert 'ice.tcp.so_sock_count' (INT4) succeeded: 0

(registry/INFO) insert 'ice.tcp.listen_backlog' (INT4) succeeded: 10

(registry/INFO) insert 'ice.tcp.disable' (char) succeeded: \000

(registry/INFO) insert 'ice.forced_interface_name' (string) succeeded:

(ice/INFO) /builds/worker/checkouts/gecko/media/mtransport/third_party/nICEr/src/net/nr_socket_multi_tcp.c:173 function nr_socket_multi_tcp_create_stun_server_socket skipping UDP STUN server(addr:)

(ice/ERR) ICE(PC:1598340041056000 (id=38 url=https://bbb.mycompany.de/html5client/join?sessionToken=my4dgigtzqesnkvo)): duplicate priority 1669292031 candidate srflx(IP4:10.10.42.48:53814/TCP|turn.mycompany.de.de:443) passive and candidate srflx(IP4:10.10.42.48:53814/TCP|turn.mycompany.de.de:443) passive

(ice/INFO) /builds/worker/checkouts/gecko/media/mtransport/third_party/nICEr/src/net/nr_socket_multi_tcp.c:173 function nr_socket_multi_tcp_create_stun_server_socket skipping UDP STUN server(addr:)

(ice/ERR) ICE(PC:1598340041056000 (id=38 url=https://bbb.mycompany.de/html5client/join?sessionToken=my4dgigtzqesnkvo)): duplicate priority 1669292030 candidate srflx(IP4:10.10.42.48:50562/TCP|turn.mycompany.de.de:443) passive and candidate srflx(IP4:10.10.42.48:50562/TCP|turn.mycompany.de.de:443) passive

(generic/INFO) Write buffer not empty for IP4:45.45.44.43:443/TCP 20 - already armed (@000002BDDADA05F4), not connected

(generic/INFO) Write buffer not empty for IP4:45.45.44.43:443/TCP 44 - already armed (@000002BDE45AF9F4), not connected

(generic/INFO) Write buffer not empty for IP4:45.45.44.43:443/TCP 40 - already armed (@000002BDDADA05F4), not connected

(generic/INFO) Write buffer not empty for IP4:45.45.44.43:443/TCP 44 - already armed (@000002BDEA8C2DF4), not connected

(generic/INFO) Write buffer not empty for IP4:45.45.44.43:443/TCP 20 - already armed (@000002BDEF1E35F4), not connected

(generic/INFO) Write buffer not empty for IP4:45.45.44.43:443/TCP 44 - already armed (@000002BDEF1E5DF4), not connected

(generic/INFO) Write buffer not empty for IP4:45.45.44.43:443/TCP 40 - already armed (@000002BDEF1E35F4), not connected

(generic/INFO) Write buffer not empty for IP4:45.45.44.43:443/TCP 44 - already armed (@000002BDEF1E7DF4), not connected

(ice/WARNING) ICE(PC:1598340041056000 (id=38 url=https://bbb.mycompany.de/html5client/join?sessionToken=my4dgigtzqesnkvo)): peer (PC:1598340041056000 (id=38 url=https://bbb.mycompany.de/html5client/join?sessionToken=my4dgigtzqesnkvo):default) has no stream matching stream PC:1598340041056000 (id=38 url=https://bbb.mycompany.de/html5client/join?sessionToken=my4dgigtzqesnkvo) transport-id=transport_0 - 55c06f79:ac8443c2923b02ee0de91d52244ba179

(ice/INFO) ICE-PEER(PC:1598340041056000 (id=38 url=https://bbb.mycompany.de/html5client/join?sessionToken=my4dgigtzqesnkvo):default)/CAND-PAIR(GTqu): setting pair to state FROZEN: GTqu|IP4:10.10.42.48:57295/UDP|IP4:195.13.123.124:16994/UDP(host(IP4:10.10.42.48:57295/UDP)|candidate:1881991537 1 udp 659136 195.13.123.124 16994 typ host generation 0)

(ice/INFO) ICE(PC:1598340041056000 (id=38 url=https://bbb.mycompany.de/html5client/join?sessionToken=my4dgigtzqesnkvo))/CAND-PAIR(GTqu): Pairing candidate IP4:10.10.42.48:57295/UDP (7e7f00ff):IP4:195.13.123.124:16994/UDP (a0ec0) priority=2830971808121343 (a0ec0fcfe01ff)

(ice/INFO) ICE-PEER(PC:1598340041056000 (id=38 url=https://bbb.mycompany.de/html5client/join?sessionToken=my4dgigtzqesnkvo):default)/CAND-PAIR(GTqu): setting pair to state WAITING: GTqu|IP4:10.10.42.48:57295/UDP|IP4:195.13.123.124:16994/UDP(host(IP4:10.10.42.48:57295/UDP)|candidate:1881991537 1 udp 659136 195.13.123.124 16994 typ host generation 0)

(ice/INFO) ICE-PEER(PC:1598340041056000 (id=38 url=https://bbb.mycompany.de/html5client/join?sessionToken=my4dgigtzqesnkvo):default)/ICE-STREAM(PC:1598340041056000 (id=38 url=https://bbb.mycompany.de/html5client/join?sessionToken=my4dgigtzqesnkvo) transport-id=transport_0 - 55c06f79:ac8443c2923b02ee0de91d52244ba179): Starting check timer for stream.

(ice/INFO) ICE-PEER(PC:1598340041056000 (id=38 url=https://bbb.mycompany.de/html5client/join?sessionToken=my4dgigtzqesnkvo):default)/CAND-PAIR(GTqu): setting pair to state IN_PROGRESS: GTqu|IP4:10.10.42.48:57295/UDP|IP4:195.13.123.124:16994/UDP(host(IP4:10.10.42.48:57295/UDP)|candidate:1881991537 1 udp 659136 195.13.123.124 16994 typ host generation 0)

(ice/NOTICE) ICE(PC:1598340041056000 (id=38 url=https://bbb.mycompany.de/html5client/join?sessionToken=my4dgigtzqesnkvo)): peer (PC:1598340041056000 (id=38 url=https://bbb.mycompany.de/html5client/join?sessionToken=my4dgigtzqesnkvo):default) is now checking

(ice/NOTICE) ICE(PC:1598340041056000 (id=38 url=https://bbb.mycompany.de/html5client/join?sessionToken=my4dgigtzqesnkvo)): peer (PC:1598340041056000 (id=38 url=https://bbb.mycompany.de/html5client/join?sessionToken=my4dgigtzqesnkvo):default) no streams with pre-answer requests

(ice/INFO) ICE-PEER(PC:1598340041056000 (id=38 url=https://bbb.mycompany.de/html5client/join?sessionToken=my4dgigtzqesnkvo):default): no FROZEN/WAITING pairs for PC:1598340041056000 (id=38 url=https://bbb.mycompany.de/html5client/join?sessionToken=my4dgigtzqesnkvo) transport-id=transport_0 - 55c06f79:ac8443c2923b02ee0de91d52244ba179

(ice/INFO) ICE(PC:1598340041056000 (id=38 url=https://bbb.mycompany.de/html5client/join?sessionToken=my4dgigtzqesnkvo)): peer (PC:1598340041056000 (id=38 url=https://bbb.mycompany.de/html5client/join?sessionToken=my4dgigtzqesnkvo):default) Trickle grace period is over; marking every component with only failed pairs as failed.

(stun/INFO) STUN-CLIENT(srflx(IP4:10.10.42.48:57295/UDP|turn.mycompany.de.de:3478)): Timed out

(ice/WARNING) ICE(PC:1598340041056000 (id=38 url=https://bbb.mycompany.de/html5client/join?sessionToken=my4dgigtzqesnkvo))/CAND(srflx(IP4:10.10.42.48:57295/UDP|turn.mycompany.de.de:3478)): failed to initialize, 9 remaining

(stun/INFO) STUN-CLIENT(srflx(IP4:10.10.42.48:57296/UDP|turn.mycompany.de.de:3478)): Timed out

(ice/WARNING) ICE(PC:1598340041056000 (id=38 url=https://bbb.mycompany.de/html5client/join?sessionToken=my4dgigtzqesnkvo))/CAND(srflx(IP4:10.10.42.48:57296/UDP|turn.mycompany.de.de:3478)): failed to initialize, 8 remaining

(stun/INFO) STUN-CLIENT(srflx(IP4:10.10.42.48:53814/TCP|turn.mycompany.de.de:443) passive): Timed out

(ice/WARNING) ICE(PC:1598340041056000 (id=38 url=https://bbb.mycompany.de/html5client/join?sessionToken=my4dgigtzqesnkvo))/CAND(srflx(IP4:10.10.42.48:53814/TCP|turn.mycompany.de.de:443) passive): failed to initialize, 7 remaining

(stun/INFO) STUN-CLIENT(relay(IP4:10.10.42.48:50893/TLS|turn.mycompany.de.de:443)::TURN): Timed out

(turn/WARNING) TURN(relay(IP4:10.10.42.48:50893/TLS|turn.mycompany.de.de:443)): mode 20, nr_turn_client_error_cb

(turn/WARNING) TURN(relay(IP4:10.10.42.48:50893/TLS|turn.mycompany.de.de:443)) failed

(turn/INFO) TURN(relay(IP4:10.10.42.48:50893/TLS|turn.mycompany.de.de:443)): cancelling

(turn/WARNING) ICE-CANDIDATE(relay(IP4:10.10.42.48:50893/TLS|turn.mycompany.de.de:443)): nr_turn_allocated_cb called with state 4

(turn/WARNING) ICE-CANDIDATE(relay(IP4:10.10.42.48:50893/TLS|turn.mycompany.de.de:443)): nr_turn_allocated_cb failed

(ice/WARNING) ICE(PC:1598340041056000 (id=38 url=https://bbb.mycompany.de/html5client/join?sessionToken=my4dgigtzqesnkvo))/CAND(relay(IP4:10.10.42.48:50893/TLS|turn.mycompany.de.de:443)): failed to initialize, 6 remaining

(stun/INFO) STUN-CLIENT(srflx(IP4:10.10.42.48:53814/TCP|turn.mycompany.de.de:443) passive): Timed out

(ice/WARNING) ICE(PC:1598340041056000 (id=38 url=https://bbb.mycompany.de/html5client/join?sessionToken=my4dgigtzqesnkvo))/CAND(srflx(IP4:10.10.42.48:53814/TCP|turn.mycompany.de.de:443) passive): failed to initialize, 5 remaining

(stun/INFO) STUN-CLIENT(relay(IP4:10.10.42.48:50894/TCP|turn.mycompany.de.de:443)::TURN): Timed out

(turn/WARNING) TURN(relay(IP4:10.10.42.48:50894/TCP|turn.mycompany.de.de:443)): mode 20, nr_turn_client_error_cb

(turn/WARNING) TURN(relay(IP4:10.10.42.48:50894/TCP|turn.mycompany.de.de:443)) failed

(turn/INFO) TURN(relay(IP4:10.10.42.48:50894/TCP|turn.mycompany.de.de:443)): cancelling

(turn/WARNING) ICE-CANDIDATE(relay(IP4:10.10.42.48:50894/TCP|turn.mycompany.de.de:443)): nr_turn_allocated_cb called with state 4

(turn/WARNING) ICE-CANDIDATE(relay(IP4:10.10.42.48:50894/TCP|turn.mycompany.de.de:443)): nr_turn_allocated_cb failed

(ice/WARNING) ICE(PC:1598340041056000 (id=38 url=https://bbb.mycompany.de/html5client/join?sessionToken=my4dgigtzqesnkvo))/CAND(relay(IP4:10.10.42.48:50894/TCP|turn.mycompany.de.de:443)): failed to initialize, 4 remaining

(stun/INFO) STUN-CLIENT(srflx(IP4:10.10.42.48:50562/TCP|turn.mycompany.de.de:443) passive): Timed out

(ice/WARNING) ICE(PC:1598340041056000 (id=38 url=https://bbb.mycompany.de/html5client/join?sessionToken=my4dgigtzqesnkvo))/CAND(srflx(IP4:10.10.42.48:50562/TCP|turn.mycompany.de.de:443) passive): failed to initialize, 3 remaining

(stun/INFO) STUN-CLIENT(relay(IP4:10.10.42.48:50895/TLS|turn.mycompany.de.de:443)::TURN): Timed out

(turn/WARNING) TURN(relay(IP4:10.10.42.48:50895/TLS|turn.mycompany.de.de:443)): mode 20, nr_turn_client_error_cb

(turn/WARNING) TURN(relay(IP4:10.10.42.48:50895/TLS|turn.mycompany.de.de:443)) failed

(turn/INFO) TURN(relay(IP4:10.10.42.48:50895/TLS|turn.mycompany.de.de:443)): cancelling

(turn/WARNING) ICE-CANDIDATE(relay(IP4:10.10.42.48:50895/TLS|turn.mycompany.de.de:443)): nr_turn_allocated_cb called with state 4

(turn/WARNING) ICE-CANDIDATE(relay(IP4:10.10.42.48:50895/TLS|turn.mycompany.de.de:443)): nr_turn_allocated_cb failed

(ice/WARNING) ICE(PC:1598340041056000 (id=38 url=https://bbb.mycompany.de/html5client/join?sessionToken=my4dgigtzqesnkvo))/CAND(relay(IP4:10.10.42.48:50895/TLS|turn.mycompany.de.de:443)): failed to initialize, 2 remaining

(stun/INFO) STUN-CLIENT(srflx(IP4:10.10.42.48:50562/TCP|turn.mycompany.de.de:443) passive): Timed out

(ice/WARNING) ICE(PC:1598340041056000 (id=38 url=https://bbb.mycompany.de/html5client/join?sessionToken=my4dgigtzqesnkvo))/CAND(srflx(IP4:10.10.42.48:50562/TCP|turn.mycompany.de.de:443) passive): failed to initialize, 1 remaining

(stun/INFO) STUN-CLIENT(relay(IP4:10.10.42.48:50896/TCP|turn.mycompany.de.de:443)::TURN): Timed out

(turn/WARNING) TURN(relay(IP4:10.10.42.48:50896/TCP|turn.mycompany.de.de:443)): mode 20, nr_turn_client_error_cb

(turn/WARNING) TURN(relay(IP4:10.10.42.48:50896/TCP|turn.mycompany.de.de:443)) failed

(turn/INFO) TURN(relay(IP4:10.10.42.48:50896/TCP|turn.mycompany.de.de:443)): cancelling

(turn/WARNING) ICE-CANDIDATE(relay(IP4:10.10.42.48:50896/TCP|turn.mycompany.de.de:443)): nr_turn_allocated_cb called with state 4

(turn/WARNING) ICE-CANDIDATE(relay(IP4:10.10.42.48:50896/TCP|turn.mycompany.de.de:443)): nr_turn_allocated_cb failed

(ice/WARNING) ICE(PC:1598340041056000 (id=38 url=https://bbb.mycompany.de/html5client/join?sessionToken=my4dgigtzqesnkvo))/CAND(relay(IP4:10.10.42.48:50896/TCP|turn.mycompany.de.de:443)): failed to initialize, 0 remaining

(ice/INFO) ICE(PC:1598340041056000 (id=38 url=https://bbb.mycompany.de/html5client/join?sessionToken=my4dgigtzqesnkvo)): All candidates initialized

(stun/INFO) STUN-CLIENT(GTqu|IP4:10.10.42.48:57295/UDP|IP4:195.13.123.124:16994/UDP(host(IP4:10.10.42.48:57295/UDP)|candidate:1881991537 1 udp 659136 195.13.123.124 16994 typ host generation 0)): Timed out

(ice/INFO) ICE-PEER(PC:1598340041056000 (id=38 url=https://bbb.mycompany.de/html5client/join?sessionToken=my4dgigtzqesnkvo):default)/CAND-PAIR(GTqu): setting pair to state FAILED: GTqu|IP4:10.10.42.48:57295/UDP|IP4:195.13.123.124:16994/UDP(host(IP4:10.10.42.48:57295/UDP)|candidate:1881991537 1 udp 659136 195.13.123.124 16994 typ host generation 0)

(ice/INFO) ICE-PEER(PC:1598340041056000 (id=38 url=https://bbb.mycompany.de/html5client/join?sessionToken=my4dgigtzqesnkvo):default)/STREAM(PC:1598340041056000 (id=38 url=https://bbb.mycompany.de/html5client/join?sessionToken=my4dgigtzqesnkvo) transport-id=transport_0 - 55c06f79:ac8443c2923b02ee0de91d52244ba179)/COMP(1): All pairs are failed, and grace period has elapsed. Marking component as failed.

(ice/ERR) ICE(PC:1598340041056000 (id=38 url=https://bbb.mycompany.de/html5client/join?sessionToken=my4dgigtzqesnkvo))/STREAM(PC:1598340041056000 (id=38 url=https://bbb.mycompany.de/html5client/join?sessionToken=my4dgigtzqesnkvo) transport-id=transport_0 - 55c06f79:ac8443c2923b02ee0de91d52244ba179): state dump

(ice/ERR) ICE(PC:1598340041056000 (id=38 url=https://bbb.mycompany.de/html5client/join?sessionToken=my4dgigtzqesnkvo))/ICE-STREAM(PC:1598340041056000 (id=38 url=https://bbb.mycompany.de/html5client/join?sessionToken=my4dgigtzqesnkvo) transport-id=transport_0 - 55c06f79:ac8443c2923b02ee0de91d52244ba179): Local component 1 - dumping candidates

(ice/ERR) ICE(PC:1598340041056000 (id=38 url=https://bbb.mycompany.de/html5client/join?sessionToken=my4dgigtzqesnkvo))/ICE-STREAM(PC:1598340041056000 (id=38 url=https://bbb.mycompany.de/html5client/join?sessionToken=my4dgigtzqesnkvo) transport-id=transport_0 - 55c06f79:ac8443c2923b02ee0de91d52244ba179)/CAND(QZQ4): host(IP4:10.10.42.48:57295/UDP)

(ice/ERR) ICE(PC:1598340041056000 (id=38 url=https://bbb.mycompany.de/html5client/join?sessionToken=my4dgigtzqesnkvo))/ICE-STREAM(PC:1598340041056000 (id=38 url=https://bbb.mycompany.de/html5client/join?sessionToken=my4dgigtzqesnkvo) transport-id=transport_0 - 55c06f79:ac8443c2923b02ee0de91d52244ba179)/CAND(z/Nu): srflx(IP4:10.10.42.48:57295/UDP|turn.mycompany.de.de:3478)

(ice/ERR) ICE(PC:1598340041056000 (id=38 url=https://bbb.mycompany.de/html5client/join?sessionToken=my4dgigtzqesnkvo))/ICE-STREAM(PC:1598340041056000 (id=38 url=https://bbb.mycompany.de/html5client/join?sessionToken=my4dgigtzqesnkvo) transport-id=transport_0 - 55c06f79:ac8443c2923b02ee0de91d52244ba179)/CAND(5ru8): host(IP4:10.10.42.48:53814/TCP) passive

(ice/ERR) ICE(PC:1598340041056000 (id=38 url=https://bbb.mycompany.de/html5client/join?sessionToken=my4dgigtzqesnkvo))/ICE-STREAM(PC:1598340041056000 (id=38 url=https://bbb.mycompany.de/html5client/join?sessionToken=my4dgigtzqesnkvo) transport-id=transport_0 - 55c06f79:ac8443c2923b02ee0de91d52244ba179)/CAND(t7U+): host(IP4:10.10.42.48:58264/TCP) active

(ice/ERR) ICE(PC:1598340041056000 (id=38 url=https://bbb.mycompany.de/html5client/join?sessionToken=my4dgigtzqesnkvo))/ICE-STREAM(PC:1598340041056000 (id=38 url=https://bbb.mycompany.de/html5client/join?sessionToken=my4dgigtzqesnkvo) transport-id=transport_0 - 55c06f79:ac8443c2923b02ee0de91d52244ba179)/CAND(SLWj): srflx(IP4:10.10.42.48:53814/TCP|turn.mycompany.de.de:443) passive

(ice/ERR) ICE(PC:1598340041056000 (id=38 url=https://bbb.mycompany.de/html5client/join?sessionToken=my4dgigtzqesnkvo))/ICE-STREAM(PC:1598340041056000 (id=38 url=https://bbb.mycompany.de/html5client/join?sessionToken=my4dgigtzqesnkvo) transport-id=transport_0 - 55c06f79:ac8443c2923b02ee0de91d52244ba179)/CAND(+4sV): relay(IP4:10.10.42.48:50893/TLS|turn.mycompany.de.de:443)

(ice/ERR) ICE(PC:1598340041056000 (id=38 url=https://bbb.mycompany.de/html5client/join?sessionToken=my4dgigtzqesnkvo))/ICE-STREAM(PC:1598340041056000 (id=38 url=https://bbb.mycompany.de/html5client/join?sessionToken=my4dgigtzqesnkvo) transport-id=transport_0 - 55c06f79:ac8443c2923b02ee0de91d52244ba179)/CAND(SLWj): srflx(IP4:10.10.42.48:53814/TCP|turn.mycompany.de.de:443) passive

(ice/ERR) ICE(PC:1598340041056000 (id=38 url=https://bbb.mycompany.de/html5client/join?sessionToken=my4dgigtzqesnkvo))/ICE-STREAM(PC:1598340041056000 (id=38 url=https://bbb.mycompany.de/html5client/join?sessionToken=my4dgigtzqesnkvo) transport-id=transport_0 - 55c06f79:ac8443c2923b02ee0de91d52244ba179)/CAND(8vn1): relay(IP4:10.10.42.48:50894/TCP|turn.mycompany.de.de:443)

(ice/ERR) ICE(PC:1598340041056000 (id=38 url=https://bbb.mycompany.de/html5client/join?sessionToken=my4dgigtzqesnkvo))/ICE-STREAM(PC:1598340041056000 (id=38 url=https://bbb.mycompany.de/html5client/join?sessionToken=my4dgigtzqesnkvo) transport-id=transport_0 - 55c06f79:ac8443c2923b02ee0de91d52244ba179): Local component 2 - dumping candidates

(ice/ERR) ICE(PC:1598340041056000 (id=38 url=https://bbb.mycompany.de/html5client/join?sessionToken=my4dgigtzqesnkvo))/ICE-STREAM(PC:1598340041056000 (id=38 url=https://bbb.mycompany.de/html5client/join?sessionToken=my4dgigtzqesnkvo) transport-id=transport_0 - 55c06f79:ac8443c2923b02ee0de91d52244ba179)/CAND(J5JL): host(IP4:10.10.42.48:57296/UDP)

(ice/ERR) ICE(PC:1598340041056000 (id=38 url=https://bbb.mycompany.de/html5client/join?sessionToken=my4dgigtzqesnkvo))/ICE-STREAM(PC:1598340041056000 (id=38 url=https://bbb.mycompany.de/html5client/join?sessionToken=my4dgigtzqesnkvo) transport-id=transport_0 - 55c06f79:ac8443c2923b02ee0de91d52244ba179)/CAND(MYiO): srflx(IP4:10.10.42.48:57296/UDP|turn.mycompany.de.de:3478)

(ice/ERR) ICE(PC:1598340041056000 (id=38 url=https://bbb.mycompany.de/html5client/join?sessionToken=my4dgigtzqesnkvo))/ICE-STREAM(PC:1598340041056000 (id=38 url=https://bbb.mycompany.de/html5client/join?sessionToken=my4dgigtzqesnkvo) transport-id=transport_0 - 55c06f79:ac8443c2923b02ee0de91d52244ba179)/CAND(yoqb): host(IP4:10.10.42.48:50562/TCP) passive

(ice/ERR) ICE(PC:1598340041056000 (id=38 url=https://bbb.mycompany.de/html5client/join?sessionToken=my4dgigtzqesnkvo))/ICE-STREAM(PC:1598340041056000 (id=38 url=https://bbb.mycompany.de/html5client/join?sessionToken=my4dgigtzqesnkvo) transport-id=transport_0 - 55c06f79:ac8443c2923b02ee0de91d52244ba179)/CAND(yJxz): host(IP4:10.10.42.48:54535/TCP) active

(ice/ERR) ICE(PC:1598340041056000 (id=38 url=https://bbb.mycompany.de/html5client/join?sessionToken=my4dgigtzqesnkvo))/ICE-STREAM(PC:1598340041056000 (id=38 url=https://bbb.mycompany.de/html5client/join?sessionToken=my4dgigtzqesnkvo) transport-id=transport_0 - 55c06f79:ac8443c2923b02ee0de91d52244ba179)/CAND(kFKD): srflx(IP4:10.10.42.48:50562/TCP|turn.mycompany.de.de:443) passive

(ice/ERR) ICE(PC:1598340041056000 (id=38 url=https://bbb.mycompany.de/html5client/join?sessionToken=my4dgigtzqesnkvo))/ICE-STREAM(PC:1598340041056000 (id=38 url=https://bbb.mycompany.de/html5client/join?sessionToken=my4dgigtzqesnkvo) transport-id=transport_0 - 55c06f79:ac8443c2923b02ee0de91d52244ba179)/CAND(iPHC): relay(IP4:10.10.42.48:50895/TLS|turn.mycompany.de.de:443)

(ice/ERR) ICE(PC:1598340041056000 (id=38 url=https://bbb.mycompany.de/html5client/join?sessionToken=my4dgigtzqesnkvo))/ICE-STREAM(PC:1598340041056000 (id=38 url=https://bbb.mycompany.de/html5client/join?sessionToken=my4dgigtzqesnkvo) transport-id=transport_0 - 55c06f79:ac8443c2923b02ee0de91d52244ba179)/CAND(kFKD): srflx(IP4:10.10.42.48:50562/TCP|turn.mycompany.de.de:443) passive

(ice/ERR) ICE(PC:1598340041056000 (id=38 url=https://bbb.mycompany.de/html5client/join?sessionToken=my4dgigtzqesnkvo))/ICE-STREAM(PC:1598340041056000 (id=38 url=https://bbb.mycompany.de/html5client/join?sessionToken=my4dgigtzqesnkvo) transport-id=transport_0 - 55c06f79:ac8443c2923b02ee0de91d52244ba179)/CAND(I9C4): relay(IP4:10.10.42.48:50896/TCP|turn.mycompany.de.de:443)

(ice/ERR) ICE-PEER(PC:1598340041056000 (id=38 url=https://bbb.mycompany.de/html5client/join?sessionToken=my4dgigtzqesnkvo):default)/STREAM(PC:1598340041056000 (id=38 url=https://bbb.mycompany.de/html5client/join?sessionToken=my4dgigtzqesnkvo) transport-id=transport_0 - 55c06f79:ac8443c2923b02ee0de91d52244ba179): state dump

(ice/ERR) CAND-PAIR(GTqu): pair GTqu|IP4:10.10.42.48:57295/UDP|IP4:195.13.123.124:16994/UDP(host(IP4:10.10.42.48:57295/UDP)|candidate:1881991537 1 udp 659136 195.13.123.124 16994 typ host generation 0): state=FAILED, priority=0xa0ec0fcfe01ff

(ice/ERR) ICE(PC:1598340041056000 (id=38 url=https://bbb.mycompany.de/html5client/join?sessionToken=my4dgigtzqesnkvo))/ICE-STREAM(PC:1598340041056000 (id=38 url=https://bbb.mycompany.de/html5client/join?sessionToken=my4dgigtzqesnkvo) transport-id=transport_0 - 55c06f79:ac8443c2923b02ee0de91d52244ba179): Remote component 1 in state 3 - dumping candidates

(ice/ERR) ICE(PC:1598340041056000 (id=38 url=https://bbb.mycompany.de/html5client/join?sessionToken=my4dgigtzqesnkvo))/ICE-STREAM(PC:1598340041056000 (id=38 url=https://bbb.mycompany.de/html5client/join?sessionToken=my4dgigtzqesnkvo) transport-id=transport_0 - 55c06f79:ac8443c2923b02ee0de91d52244ba179)/CAND(6Vt/): candidate:1881991537 1 udp 659136 195.13.123.124 16994 typ host generation 0

(ice/ERR) ICE(PC:1598340041056000 (id=38 url=https://bbb.mycompany.de/html5client/join?sessionToken=my4dgigtzqesnkvo))/ICE-STREAM(PC:1598340041056000 (id=38 url=https://bbb.mycompany.de/html5client/join?sessionToken=my4dgigtzqesnkvo) transport-id=transport_0 - 55c06f79:ac8443c2923b02ee0de91d52244ba179): Remote component 2 in state 0 - dumping candidates

(ice/INFO) ICE-PEER(PC:1598340041056000 (id=38 url=https://bbb.mycompany.de/html5client/join?sessionToken=my4dgigtzqesnkvo):default): all checks completed success=0 fail=1

+++++++ END ++++++++`

does anyone have an idea how I can get this to work on Firefox? Thank you very much

I hope this is the correct category

**Comment by matiasilva** [comment]
Please read the docs (https://docs.bigbluebutton.org/) and if that doesn't help, post in the support group (https://groups.google.com/forum/#!forum/bigbluebutton-setup). Thanks!
