### ISSUE TITLE
Latest 2.3 dev web interface doesn't update... Echo Test or Share Screen

### ISSUE THREAD

**Issue by markginter31** [bigbluebutton/bigbluebutton#10352]
I upgraded to alpha 2 -- I can begin the microphone echo test and hear echoing, but the button to click never appears (just shows Connecting to echo test.... continuously)

Also - I can join with headphones fine - but if I try to share any windows/screens - they don't appear in the live window but do appear if I chose to record.

**Comment by ffdixon** [comment]
Can you try it on https://demo.bigbluebutton.org/ and let us know if you have the same issue.

**Comment by markginter31** [comment]
Thanks for responding so quickly! -- I just came back to delete this issue.  I couldn't track down exactly what was happening, so I re-used bbb-install to reinstall everything and then hand edited the files to match my external ip (for freeswitch) -- and now everything is working.  I'm not sure exactly what settled it but everything is now set back to what it was before I attempted to --> apt-get dist-upgrade my setup.

**Comment by tretkowski** [comment]
I see the same behaviour on our BBB instance since running "apt-get dist-upgrade" this morning, but it does not seem to happen on demo.bigbluebutton.org.

**Comment by matiasilva** [comment]
@tretkowski please please follow the upgrade instructions and run `bbb-conf --setip xxxxxxxx`! An `apt upgrade` isn't enough.

**Comment by markginter31** [comment]
I had trouble finding upgrade directions specific to the dev series and didn't want to just assume or apply something from earlier updates.  I do think that what you shared is what was done when I reran bbb-install.... I did need to go back through and edit some files to restore the ability to operate behind a nat after using that.

**Comment by matiasilva** [comment]
I didn't see anything in the changelog that warranted a different upgrade process and also as you've mentioned, bbb-conf does set the IP via that command, so it's meant to work for dev versions too! Let us know @tretkowski if that solved your issue.

**Comment by tretkowski** [comment]
That indeed solved my issue, thanks! Maybe that's something which could be handled by the pre- / post-inst scripts of one of the Debian packages...

**Comment by matiasilva** [comment]
@markginter31 feel free to close this if you find this has been solved!
