### ISSUE TITLE
how change bigbluebutton components code

### ISSUE THREAD

**Issue by SadeqRouhani** [bigbluebutton/bigbluebutton#10355]
hi every body.

i want customize this code:
https://github.com/bigbluebutton/bigbluebutton/blob/develop/bigbluebutton-html5/imports/ui/components/banner-bar/component.jsx

but when  install bigbluebutton on my VPS and search 'bigbluebutton-html5' or 'ui' or 'banner-bar' i couldn't find anything.

can i edit this code? or other bigbluebutton codes?
how can do this?
thanks for your help

**Comment by matiasilva** [comment]
Read the docs (https://docs.bigbluebutton.org/2.2/dev.html).
