### ISSUE TITLE
Support for Ubuntu Server 18 (and maybe 20)?

### ISSUE THREAD

**Issue by pgenderson** [bigbluebutton/bigbluebutton#10353]
Server 16 doesn't recognize my wifi card at all, maybe due to an older kernel. Would installing the latest kernel maybe fix my wireless card problem? `# lshw -C network` doesn't return anything, and there's no RTL8723BS module for my Realtek card.

Update: upgraded kernel on Server 16 installation but still have connecting issues.

**Comment by matiasilva** [comment]
The latest stable install of BigBlueButton runs on 16.04. The upcoming major release will run on 18.04. 20.04 cannot be supported due to some utilized software not being able to run on that version.
