### ISSUE TITLE
Problem with uploading presentations containing special characters in filename

### ISSUE THREAD

**Issue by krim404** [bigbluebutton/bigbluebutton#10357]
Hello,
just a minor bug which has been found by one of our presentators:

if you use a mac and upload a presentation from within the html5 gui with a filename containing special characters like a quotation mark, the upload will hang while converting the file. 

Unfortunately, the internal error report did not include the used browser, but the sanitization of the inputs should always occur on the receiver, not on the sender anyway.

**Comment by florencebiree** [comment]
Hi,

Same problem here, with a file named "2020-11-23\ 13_35_46-réunion\ équipe\ FP.png".
Renaming it "test.png" make it working, uploading the file with special characters in greenlight also work.

I'm using Debian/Linux, so it seems to be not specific to mac.

**Comment by krim404** [comment]
is this issue resolved?
