### ISSUE TITLE
Cannot proceed from "Conncting to echo test..." (2.3 alpha2)

### ISSUE THREAD

**Issue by maron2000** [bigbluebutton/bigbluebutton#10361]
**Describe the bug**
Cannot proceed from "Connecting to echo test"

**To Reproduce**
1. Start a session
2. Click on 'Microphone' when asked "How would you like to join the audio?"
3. Allow access to microphone

**Expected behavior**
Able to select whether echo test is succeeded or not after a few seconds "Connecting to echo test" appears.
Or at least time out after a certain time.

**Actual behavior**
"Connecting to echo test..." appears and cannot do anything more. (_I can hear my voice echoed_)
Cannot close caption.

**Screenshots**
See attached
![screenshot](https://user-images.githubusercontent.com/68574602/91730640-fbec7200-ebe0-11ea-8c23-0405082925f4.png)
![console](https://user-images.githubusercontent.com/68574602/91730758-1aeb0400-ebe1-11ea-9705-ba26221eb75f.png)

**Desktop (please complete the following information):**
 - OS: Windows10
 - Browser: Firefox 78.2.0 ESR, Chrome 85.0.4183.83

**Additional context**
Screenshare and webcam works.
Can proceed if "Listen only" option selected.
Can hear my echo while "Connecting to echo test..." appears.

BigBlueButton Server 2.3.0-dev (1324)
  Kernel version: 5.4.0-42-generic
  Distribution: Ubuntu 18.04.5 LTS (64-bit)
  Memory: 16370 MB
  CPU cores: 4
  Server behind NAT

Edit: The server was an upgrade from 2.3 alpha 1.
Problem resolved by doing `sudo bbb-conf --setip my.domain.com`

**Comment by matiasilva** [comment]
Is this a fresh install or an upgrade? Have you done `sudo bbb-conf --setip your.ip.here`?

**Comment by maron2000** [comment]
@matiasilva It was an upgrade from 2.3 alpha 1.
I did `sudo bbb-conf --setip my.domain.here` and I could complete the echo test with microphone working.
Thanks for your advice.
