### ISSUE TITLE
Can't add a logo to the client

### ISSUE THREAD

**Issue by MichalGizaSrv** [bigbluebutton/bigbluebutton#10363]
**Describe the bug**
I set _displayBrandingArea_ on true and add below _logo: "mydomain.com/logo.png"_  on settings.yml file but it doesn't work. How I can set logo on HTML client in this place?

![image](https://user-images.githubusercontent.com/58888243/91745239-ecf2c900-ebba-11ea-8adb-39bdbe315368.png)

**Comment by matiasilva** [comment]
Hello! Please use the support forum for these requests: https://groups.google.com/forum/#!forum/bigbluebutton-setup
