### ISSUE TITLE
2.3-alpha-2: three clicks needed to open chat from shared notes

### ISSUE THREAD

**Issue by schrd** [bigbluebutton/bigbluebutton#10375]
**Describe the bug**
The chat window cannot be opened with a single click when shared notes are open. This is a regression from BBB 2.2.

**To Reproduce**
1. Open shared notes
2. Click on Public Chat → nothing happens
3. Click on Public Chat → shared notes close
4. Click on Public Chat → Chat opens

**Expected behavior**
1. open shared notes
2. click on Public Chat → shared notes close and Chat opens

**BBB version (optional):**
BigBlueButton Server 2.3.0-dev (1323)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Firefox
 - Version 68.12.0 esr

**Comment by caniwi** [comment]
Noticed this as well.... still occurring in Server 2.3.0-dev (1324) on Firefox 80.0.1 on Ubuntu 18.04.

**Comment by schrd** [comment]
works in alpha 3
