### ISSUE TITLE
2.3-alpha-2: moderator status gets lost when someone is given presenter right

### ISSUE THREAD

**Issue by schrd** [bigbluebutton/bigbluebutton#10376]
**Describe the bug**
A user who has joined the meeting as normal user is given moderator rights. The moderator permission gets lost when he was given the presenter token, someone else gets presenter token, and the user gets back the presenter token

**To Reproduce**
1. User A creates meeting, joins as moderator
2. User B joins, is promoted to moderator
3. User C joins, is promoted to moderator
4. User A hands over presenter token to User C
5. User A hands over presenter token to User B
6. User A hands over presenter token to User C → User C loses moderator status

**Expected behavior**
User C should remain moderator

**BBB version (optional):**
BigBlueButton Server 2.3.0-dev (1323)

**Desktop (User A):**
 - OS: Linux
 - Browser Firefox
 - Version 68.12.0 esr

**Desktop (User C):**
 - OS: Linux
 - Browser Firefox
 - Version 79

**Comment by jfsiebel** [comment]
Hi @schrd ,
tried to reproduce this issue using the latest version, but I couldn't. Seems it's already fixed. Could you try to reproduce this problem again?

**Comment by schrd** [comment]
Can't reproduce in by 2.3 Beta 1 Installation. Thanks for fixing
