### ISSUE TITLE
Exitting from a full screen view of a specific webcam may cause the bottom portion of the client to be cut off from the view

### ISSUE THREAD

**Issue by farhatahmad** [bigbluebutton/bigbluebutton#10370]
**Describe the bug**
After exiting from a full screen view of the webcam, the HTML5 client does not resize correctly, leading to the bottom part of the client (chat box, mute, webcam, screenshare buttons) all being cut off from the view

**To Reproduce**
1. Share your webcam
2. Drag webcam to the bottom view
3. Resize webcam to be greater than the presentation
4. Make webcam fullscreen
5. Exit fullscreen 
6. See error (If it doesn't occur, repeat steps 4 and 5 a couple of times)

**Expected behavior**
After exiting from a full screen webcam view, the client should appear as it normally does

**Actual behavior**
After exiting from a full screen webcam view, a bottom section of the client was cut off

**Screenshots**
Before Error:
![Screenshot from 2020-09-01 13-59-48](https://user-images.githubusercontent.com/35435341/91889798-6e4e6800-ec5c-11ea-9074-026e99708931.png)

After Error:
![Screenshot from 2020-09-01 13-59-20](https://user-images.githubusercontent.com/35435341/91889754-57a81100-ec5c-11ea-8bf2-f8ab4b1fa7f0.png)

**BBB version**
2.2.23 (I believe)

**Comment by aozalevsky** [comment]
encountered this issue couple of times. resize of the full window (go to fullscreen and back) returned things to the normal state.

**Comment by voidspacexyz** [comment]
This occurs in the latest 2.2.25 also. We are running into this issue currently.

**Comment by ffdixon** [comment]
Can you try this on the latest version of FireFox (it just recently updated) and let us know if you still encounter this issue.  @KDSBrowne

**Comment by KDSBrowne** [comment]
I haven't been able to reproduce in the latest version of FireFox `81`

**Comment by farhatahmad** [comment]
Can't reproduce this anymore with the latest firefox, so I'll close the issue
