### ISSUE TITLE
2.3-alpha-2: UI not usable on Firefox for Android and Chrome on Android crashes after some time

### ISSUE THREAD

**Issue by schrd** [bigbluebutton/bigbluebutton#10378]
**Describe the bug**
The UI is almost unusable on Firefox for Android. The user can join audio, see cameras from other users, but no UI element reacts to any tap events. On Chrome for Android the browser is killed by Android after some time. 

**To Reproduce on Firefox**
1. Join a meeting with some users in in who share their camera
2. User on tablet can hear audio, other users can hear user with tablet, user on tablet can see other users cameras
2. Try to tap on any UI element (kebab menu, user list etc)
3. nothing happens

**To Reproduce on Chrome**
1. Join a meeting with some users in in who share their camera
2. wait some minutes
3. Android kills chrome (I assume out of memory)

**Expected behavior**
be able to use the UI. The same devices can use BBB 2.2 without any problems, so they are at least powerful enough for 2.2

**BBB version (optional):**
BigBlueButton Server 2.3.0-dev (1323)

**Tablet:**
 - Device: Samsung SM-T585
 - OS: Android 8.1
 - Browser Firefox for Android
 - Version 68.11.0

**Smartphone:**
 - Device: LG G5, 4 GB RAM
 - OS: Android 8
 - Browser Firefox for Android
 - Version 79

**Tablet:**
- Device: Medion P8502 (Intel CPU, 2 GB RAM)
- OS: Android 7.1
- Browser: Chrome for Android
- Version 83.0.4103.106

**Comment by antobinary** [comment]
Is this still happening? I have not encountered it and use 2.3.0+ on mobile from time to time...

**Comment by schrd** [comment]
I tried again on 2.3.1 today on the LG G5. It works without any issues.
