### ISSUE TITLE
BBB 2.3 Alpha-2 Fit to Width uploaded presentations in portrait

### ISSUE THREAD

**Issue by markginter31** [bigbluebutton/bigbluebutton#10379]
When using the fit to width button the presentation no longer fits the entire width of the background -- it only gets  a little wider.  This is different from alpha 1 when it would fill the entire width of the presentation screen.  This affects only pdf's that I upload as presentations - and I've only tried portrait oriented pdfs at this point.

**Comment by testprepturkey** [comment]
+1

**Comment by antobinary** [comment]
Possibly addressed in https://github.com/bigbluebutton/bigbluebutton/pull/12394

**Comment by ramonlsouza** [comment]
this issue is no longer reproducible, and can be closed (tested in 2.3 and 2.4)
