### ISSUE TITLE
Upload presentation issue on first user joining

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#10372]
In some cases, for the first person joining a meeting on 2.3-alpha2.
I did not try to upload presentation - this is the automatically uploaded default.pdf

![Screenshot from 2020-09-01 16-59-59](https://user-images.githubusercontent.com/6312397/91905487-9d70d380-ec74-11ea-845a-446a9694e2d3.png)

![Screenshot from 2020-09-01 16-07-22](https://user-images.githubusercontent.com/6312397/91905425-87631300-ec74-11ea-84f9-84f575f453e9.png)

![Screenshot from 2020-09-01 16-07-54](https://user-images.githubusercontent.com/6312397/91905436-8af69a00-ec74-11ea-9d75-8725a1a70c7c.png)

**Comment by AndNovAtor** [comment]
In my last and previous install of BBB (by bbb-install.conf) presentation upload is always broken. Now I have another JS error (same when I connect from another device with same admin user [so there are 2 connected users]):
`TypeError: e is undefined
    componentDidMount https://10.0.10.212/html5client/182f2536dec468523e9df5ffa8ef7b39f03e111e.js?meteor_js_resource=true:353
    Os https://10.0.10.212/html5client/182f2536dec468523e9df5ffa8ef7b39f03e111e.js?meteor_js_resource=true:69
    Vl https://10.0.10.212/html5client/182f2536dec468523e9df5ffa8ef7b39f03e111e.js?meteor_js_resource=true:69
    unstable_runWithPriority https://10.0.10.212/html5client/182f2536dec468523e9df5ffa8ef7b39f03e111e.js?meteor_js_resource=true:87
    ui https://10.0.10.212/html5client/182f2536dec468523e9df5ffa8ef7b39f03e111e.js?meteor_js_resource=true:69
    Gl https://10.0.10.212/html5client/182f2536dec468523e9df5ffa8ef7b39f03e111e.js?meteor_js_resource=true:69
    Al https://10.0.10.212/html5client/182f2536dec468523e9df5ffa8ef7b39f03e111e.js?meteor_js_resource=true:69
    di https://10.0.10.212/html5client/182f2536dec468523e9df5ffa8ef7b39f03e111e.js?meteor_js_resource=true:69
    unstable_runWithPriority https://10.0.10.212/html5client/182f2536dec468523e9df5ffa8ef7b39f03e111e.js?meteor_js_resource=true:87
    ui https://10.0.10.212/html5client/182f2536dec468523e9df5ffa8ef7b39f03e111e.js?meteor_js_resource=true:69
    di https://10.0.10.212/html5client/182f2536dec468523e9df5ffa8ef7b39f03e111e.js?meteor_js_resource=true:69
    pi https://10.0.10.212/html5client/182f2536dec468523e9df5ffa8ef7b39f03e111e.js?meteor_js_resource=true:69
    jl https://10.0.10.212/html5client/182f2536dec468523e9df5ffa8ef7b39f03e111e.js?meteor_js_resource=true:69
    enqueueForceUpdate https://10.0.10.212/html5client/182f2536dec468523e9df5ffa8ef7b39f03e111e.js?meteor_js_resource=true:69
    forceUpdate https://10.0.10.212/html5client/182f2536dec468523e9df5ffa8ef7b39f03e111e.js?meteor_js_resource=true:45
    computation https://10.0.10.212/html5client/182f2536dec468523e9df5ffa8ef7b39f03e111e.js?meteor_js_resource=true:317
    _compute https://10.0.10.212/html5client/182f2536dec468523e9df5ffa8ef7b39f03e111e.js?meteor_js_resource=true:279
    _recompute https://10.0.10.212/html5client/182f2536dec468523e9df5ffa8ef7b39f03e111e.js?meteor_js_resource=true:279
    _runFlush https://10.0.10.212/html5client/182f2536dec468523e9df5ffa8ef7b39f03e111e.js?meteor_js_resource=true:279
    a https://10.0.10.212/html5client/182f2536dec468523e9df5ffa8ef7b39f03e111e.js?meteor_js_resource=true:1
    r https://10.0.10.212/html5client/182f2536dec468523e9df5ffa8ef7b39f03e111e.js?meteor_js_resource=true:1
    <anonymous> https://10.0.10.212/html5client/182f2536dec468523e9df5ffa8ef7b39f03e111e.js?meteor_js_resource=true:1
    <anonymous> https://10.0.10.212/html5client/182f2536dec468523e9df5ffa8ef7b39f03e111e.js?meteor_js_resource=true:1
    <anonymous> https://10.0.10.212/html5client/182f2536dec468523e9df5ffa8ef7b39f03e111e.js?meteor_js_resource=true:1`
![image](https://user-images.githubusercontent.com/3628514/91986960-0ff5b800-ed36-11ea-8f10-4d144522c3cd.png)
