### ISSUE TITLE
BigBlueButton upgrade

### ISSUE THREAD

**Issue by Magnou17** [bigbluebutton/bigbluebutton#10386]
Yesterday my bbb server was working fine (egeon.xyz). Yesterday i had executed an upgrade to v2.2.23. Now when i want to launch a session and i clic on "microphone" i get an echo but my screen is staying in this check! All services are running and it is the same issue with a Smartphone. What is changed in 2.2.23? 
Rgds
Chris

**Comment by hiroshisuga** [comment]
This might help.
https://docs.bigbluebutton.org/2.2/install.html#upgrading-from-bigbluebutton-22

**Comment by Magnou17** [comment]
Thanks but are you sure of this procedure because i have done the same upgrade on a second server who worked in v2.2.20 (egeon.space) and i get the same dafault. I think that something is wrong in v2.2.23! Rgds. Chris

**Comment by hiroshisuga** [comment]
bbb-conf --setip yourFQDN solved the problem for me.

**Comment by matiasilva** [comment]
Nothing changed in regards to the process that bbb-conf --setip follows, so there's no reason why it wouldn't work in 2.2.23.

**Comment by Magnou17** [comment]
Thanks for your help hiroshisuga, bbb-conf --setip myFQDM solved the problem. Rgds. Chris

**Comment by matiasilva** [comment]
Make sure to read the upgrade instructions before updating. Glad to see this solved.
