### ISSUE TITLE
error to run html5

### ISSUE THREAD

**Issue by hamid3d** [bigbluebutton/bigbluebutton#10385]
Hi I want to work on part of html5 and install meteor according to manual in windows:

`meteor update --allow-superuser --release 1.8`  --- complete 

then 

`meteor npm install`

in this command I get error 

` node build.js || nodejs build.js

Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
MSBUILD : error MSB3411: Could not load the Visual C++ component "VCBuild.exe". If the component is not installed, either 1) install the Microsoft Windows SDK for Windows Server 2008 and .NET Framework 3.5, or 2) install Microsoft Vis
ual Studio 2008.  [F:\Projects\bigbluebutton-html5\node_modules\fibers\build\binding.sln]
gyp ERR! build error 
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\REZA\AppData\Local\.meteor\packages\meteor-tool\1.8.0\mt-os.windows.x86_64\dev_bundle\lib\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.18363
gyp ERR! command "C:\\Users\\REZA\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.8.0\\mt-os.windows.x86_64\\dev_bundle\\bin\\node.exe" "C:\\Users\\REZA\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.8.0\\mt-os.windows.x86_64\\d
ev_bundle\\lib\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--release"
gyp ERR! cwd F:\Projects\bigbluebutton-html5\node_modules\fibers
gyp ERR! node -v v8.11.4
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok
node-gyp exited with code: 1
Please make sure you are using a supported platform and node version. If you
would like to compile fibers on this machine please make sure you have setup your
build environment--
Windows + OS X instructions here: https://github.com/nodejs/node-gyp
Ubuntu users please run: `sudo apt-get install g++ build-essential`
RHEL users please run: `yum install gcc-c++` and `yum groupinstall 'Development Tools'`
Alpine users please run: `sudo apk add python make g++`
'nodejs' is not recognized as an internal or external command,
operable program or batch file.
npm WARN eslint-config-airbnb@17.1.1 requires a peer of eslint-plugin-import@^2.18.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-airbnb@17.1.1 requires a peer of eslint-plugin-jsx-a11y@^6.2.3 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-airbnb@17.1.1 requires a peer of eslint-plugin-react@^7.14.2 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-airbnb-base@13.2.0 requires a peer of eslint-plugin-import@^2.17.2 but none is installed. You must install peer dependencies yourself.
npm WARN jsdom@15.2.1 requires a peer of canvas@^2.5.0 but none is installed. You must install peer dependencies yourself.
npm WARN ws@7.3.0 requires a peer of bufferutil@^4.0.1 but none is installed. You must install peer dependencies yourself.
npm WARN ws@7.3.0 requires a peer of utf-8-validate@^5.0.2 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! fibers@4.0.3 install: `node build.js || nodejs build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the fibers@4.0.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\REZA\AppData\Roaming\npm-cache\_logs\2020-09-03T08_35_25_969Z-debug.log
`

I try use

`npm install --global windows-build-tools`

after this download on windows I use last command again I get same error and beside this  `meteor npm install`

I try to check 

`npm run start:dev`

and I get error 

`'ROOT_URL' is not recognized as an internal or external command,`

I do not know how to solve this problem and start html5 project

**Comment by matiasilva** [comment]
Hi, this sounds like a general meteor problem which you can probably find solutions to elsewhere on the web. Additionally, this is an issue tracker for bug reporting and feature requests, not for development help. I suggest you follow the instructions here: https://docs.bigbluebutton.org/2.2/getting-help.html#help-developing-bigbluebutton. Thanks.
