### ISSUE TITLE
problem servidor de medios offline 2001

### ISSUE THREAD

**Issue by pascalclerin** [bigbluebutton/bigbluebutton#10393]
Hi

I have just updated bbb this morning and now impossible to start webcam
My versions of software:
ii  bbb-apps                              1:2.2.0-47                                      amd64        BigBlueButton applications for Red5
ii  bbb-apps-akka                         2.2.0-89                                        all          BigBlueButton Apps (Akka)
ii  bbb-apps-screenshare                  1:2.2.0-47                                      amd64        BigBlueButton screenshare module for Red5
ii  bbb-apps-sip                          1:2.2.0-11                                      amd64        BigBlueButton SIP module for Red5
ii  bbb-apps-video                        1:2.2.0-44                                      amd64        BigBlueButton video module for Red5
ii  bbb-apps-video-broadcast              1:2.2.0-8                                       amd64        BigBlueButton video broadcast module for Red5
ii  bbb-client                            1:2.2.0-40                                      amd64        BigBlueButton Flash client
ii  bbb-config                            1:2.2.0-202                                     amd64        BigBlueButton configuration utilities
ii  bbb-demo                              1:2.2.0-9                                       amd64        BigBlueButton API demos
ii  bbb-etherpad                          1:2.2.0-61                                      amd64        The EtherPad Lite components for BigBlueButton
ii  bbb-freeswitch-core                   2:2.2.0-112                                     amd64        BigBlueButton build of FreeSWITCH
ii  bbb-freeswitch-sounds                 1:1.6.7-6                                       amd64        FreeSWITCH Sounds
ii  bbb-fsesl-akka                        2.2.0-67                                        all          BigBlueButton FS-ESL (Akka)
ii  bbb-html5                             1:2.2.0-1006                                    amd64        The HTML5 components for BigBlueButton
ii  bbb-mkclean                           1:0.8.7-3                                       amd64        Clean and optimize Matroska and WebM files
ii  bbb-playback-presentation             1:2.2.0-32                                      amd64        BigBluebutton playback of presentation
ii  bbb-record-core                       1:2.2.0-69                                      amd64        BigBlueButton record and playback
ii  bbb-red5                              1:1.0.10-16                                     amd64        The Red5 server for BigBlueButton
ii  bbb-transcode-akka                    2.2.0-8                                         all          BigBlueButton Transcoder
ii  bbb-web                               1:2.2.0-135                                     amd64        BigBlueButton API
ii  bbb-webrtc-sfu                        1:2.2.0-103                                     amd64        BigBlueButton WebRTC SFU
ii  bigbluebutton                         1:2.2.0-5                                       amd64        Open source web conferencing platform (bbb)
ii  ffmpeg                                7:4.2.2-1bbb1~ubuntu16.04                       amd64        Tools for transcoding, streaming and playing of multimedia files
ii  libavcodec58:amd64                    7:4.2.2-1bbb1~ubuntu16.04                       amd64        FFmpeg library with de/encoders for audio/video codecs - runtime files
ii  libavdevice58:amd64                   7:4.2.2-1bbb1~ubuntu16.04                       amd64        FFmpeg library for handling input and output devices - runtime files
ii  libavfilter7:amd64                    7:4.2.2-1bbb1~ubuntu16.04                       amd64        FFmpeg library containing media filters - runtime files
ii  libavformat58:amd64                   7:4.2.2-1bbb1~ubuntu16.04                       amd64        FFmpeg library with (de)muxers for multimedia containers - runtime files
ii  libavresample4:amd64                  7:4.2.2-1bbb1~ubuntu16.04                       amd64        FFmpeg compatibility library for resampling - runtime files
ii  libavutil56:amd64                     7:4.2.2-1bbb1~ubuntu16.04                       amd64        FFmpeg library with functions for simplifying programming - runtime files
ii  libopusenc0                           0.2.1-1bbb1                                     amd64        High-level API for encoding Ogg Opus audio streams
ii  libpostproc55:amd64                   7:4.2.2-1bbb1~ubuntu16.04                       amd64        FFmpeg library for post processing - runtime files
ii  libswresample3:amd64                  7:4.2.2-1bbb1~ubuntu16.04                       amd64        FFmpeg library for audio resampling, rematrixing etc. - runtime files
ii  libswscale5:amd64                     7:4.2.2-1bbb1~ubuntu16.04                       amd64        FFmpeg library for image scaling and various conversions - runtime files

**Comment by matiasilva** [comment]
Run `sudo bbb-conf --setip YOURFQN`. Please read the update instructions: https://docs.bigbluebutton.org/2.2/install.html#upgrading-from-bigbluebutton-22. For further support, use the mailing list https://groups.google.com/forum/#!forum/bigbluebutton-setup. This issue tracker is for bug reports and feature requests.
