### ISSUE TITLE
Not possible to create Meeting in npm development mode.

### ISSUE THREAD

**Issue by jonathansch1** [bigbluebutton/bigbluebutton#10397]
**Describe the bug**
I actually work on setting up a BBB development environment to contribute to the html5 client.

Few weeks ago I did it successfully and my demo server that based on the develop branch worked.
In between I was on vacation and now I have updated my working branch so that it is on the same state like the develop branch.

But after that it wasn’t possible to create a meeting. I got that error:

<pre><code>
=> App running at: http://127.0.0.1/html5client
I20200902-13:37:58.464(0)? error: MeetingCreatedEvtMsg: Error: Match error: Unknown key in field durationProps.maxInactivityTimeoutMinutes
I20200902-13:37:58.466(0)?     at check (packages/check/match.js:36:17)
I20200902-13:37:58.466(0)?     at addMeeting (imports/api/meetings/server/modifiers/addMeeting.js:19:3)
I20200902-13:37:58.466(0)?     at EventEmitter.handleMeetingCreation (imports/api/meetings/server/handlers/meetingCreation.js:10:10)
I20200902-13:37:58.467(0)?     at EventEmitter.emitAsync (/home/local_jschilling/dev/bigbluebutton/bigbluebutton-html5/node_modules/eventemitter2/lib/eventemitter2.js:463:31)
I20200902-13:37:58.467(0)?     at MeetingMessageQueue.handleTask (imports/startup/server/redis.js:85:10)
I20200902-13:37:58.468(0)?     at PowerQueue.runTask (packages/cfs_power-queue.js:596:14)
I20200902-13:37:58.468(0)?     at PowerQueue.updateThrottleUp (packages/cfs_power-queue.js:402:12)
I20200902-13:37:58.468(0)?     at PowerQueue.next (packages/cfs_power-queue.js:451:10)
I20200902-13:37:58.469(0)?     at PowerQueue._autoStartTasks (packages/cfs_power-queue.js:356:14)
I20200902-13:37:58.469(0)?     at PowerQueue.add (packages/cfs_power-queue.js:381:10)
I20200902-13:37:58.469(0)?     at MeetingMessageQueue.add (imports/startup/server/redis.js:94:23)
I20200902-13:37:58.470(0)?     at RedisPubSub.handleMessage (imports/startup/server/redis.js:187:36)
I20200902-13:37:58.470(0)?     at runWithEnvironment (packages/meteor.js:1286:24)
</code></pre>

**To Reproduce**
Setup development environment:

1. Clone BBB Repository
2. Install Meteor 1.10.2
3. Set `wsUrl` in `private/config/settings.yml`
4. Stop the production html5 client
5. Install npm dependencies
6. start npm

1. Go to BBB HTML5 Client Website (Demo API)
2. Enter a name
3. Join the Meeting

**Expected behavior**
It creates a meeting and you enter it.

**Actual behavior**
You got the loading screen with three white circles and after a while you got a `401 Unauthorized. Authentication timeout.`

In addition there is the error from above on the terminal as output of npm.

**Desktop:**
 - OS: Mac
 - Browser: Safari and Firefox
 - Version: Safari 13.1.2, Firefox 80.0.1

**Additional context**
I already try to solve that problem. In the end I fixed it by reverting the pull request #8417

Is there anyone else with that problem? Do you know another solution? Or was it too much that became deleted in that pull request (#8417)?

Greetings
Jonathan

**Comment by Tainan404** [comment]
Hey @jonathansch1, I got this erro also, the issue is these to properties
```
maxInactivityTimeoutMinutes: Number,
warnMinutesBeforeMax: Number,
```

missing in the `durationProps` check in the [AddMeeting](https://github.com/bigbluebutton/bigbluebutton/blob/develop/bigbluebutton-html5/imports/api/meetings/server/modifiers/addMeeting.js#L41)

**Comment by jonathansch1** [comment]
Hey @Tainan404, that works for me to only include these two properties. 

@pedrobmarin and @antobinary can you have a look at this issue, please?

**Comment by pedrobmarin** [comment]
Those properties were removed from the product on that work you reverted. You are most likely out of sync between client and server. If you are developing client-only and running all the other pieces from the packages, make sure the base client code you are running matches the packages.

**Comment by jonathansch1** [comment]
Before I opened this issue, I updated the BigBlueButton installation and my develop branch was even with the bigbluebutton:develop branch. 

Actually the following versions are installed. And this setup doesn't work for me.
<pre><code>
$ dpkg -l | grep bbb
ii  bbb-apps-akka                              2.3.0-5                                          all          BigBlueButton Apps (Akka)
ii  bbb-config                                 1:2.3.0-7                                        amd64        BigBlueButton configuration utilities
ii  bbb-demo                                   1:2.3.0-2                                        amd64        BigBlueButton API demos
ii  bbb-etherpad                               1:2.3.0-11                                       amd64        The EtherPad Lite components for BigBlueButton
ii  bbb-freeswitch-core                        2:2.3.0-2                                        amd64        BigBlueButton build of FreeSWITCH
ii  bbb-freeswitch-sounds                      1:1.6.7-1                                        amd64        FreeSWITCH Sounds
ii  bbb-fsesl-akka                             2.3.0-3                                          all          BigBlueButton FS-ESL (Akka)
ii  bbb-html5                                  1:2.3.0-1250                                     amd64        The HTML5 components for BigBlueButton
ii  bbb-libreoffice-docker                     1:2.3.0-6                                        amd64        BigBlueButton setup for LibreOffice running in docker
ii  bbb-mkclean                                1:0.8.7-1                                        amd64        Clean and optimize Matroska and WebM files
ii  bbb-playback-presentation                  1:2.3.0-3                                        amd64        BigBluebutton playback of presentation
ii  bbb-record-core                            1:2.3.0-6                                        amd64        BigBlueButton record and playback
rc  bbb-transcode-akka                         2.3.0-1                                          all          BigBlueButton Transcoder
ii  bbb-web                                    1:2.3.0-9                                        amd64        BigBlueButton API
ii  bbb-webrtc-sfu                             1:2.3.0-4                                        amd64        BigBlueButton WebRTC SFU
ii  bigbluebutton                              1:2.3.0-4                                        amd64        Open source web conferencing platform (bbb)
</pre></code>

Is there any information where I can look, which versions of the packages match on the latest client from the git repository?
I thought that if I stay up to date with my installation and the repository it works.

**Comment by pedrobmarin** [comment]
I'm not aware how `develop` packages are built but my best guess would be over a tag. Maybe this one https://github.com/bigbluebutton/bigbluebutton/tree/v2.3-alpha-2

**Comment by pedrobmarin** [comment]
The missing pieces match your issue https://github.com/bigbluebutton/bigbluebutton/compare/v2.3-alpha-2...develop

**Comment by jonathansch1** [comment]
@pedrobmarin thank you very much!

As summary if there is someone else with that problem: My develop branch was in front of the v2.3-alpha-2 tag/version and didn't match to my installation.

So I close this issue.
