### ISSUE TITLE
remove locales/de_DE.json which includes only one translated line

### ISSUE THREAD

**Issue by christmart** [bigbluebutton/bigbluebutton#10392]
**Describe the bug**
bbb-html5 has a translation for German in /usr/share/meteor/bundle/programs/server/assets/app/locales/de.json .
Additionally there is also a de_DE.json for Germany. But this file has only one different translation :+1: 

app.lock-viewers.otherViewersWebcamLabel": "Webcams anderer Teilnehmer sehen

the translation in de.json is:

"app.lock-viewers.otherViewersWebcamLabel": "Nur Moderatoren sehen Webcams"

The separate file for de_DE is not needed. Please remove it.

**BBB version (optional):**

2.2.23

**Comment by antobinary** [comment]
I removed this language from Transifex. I will remove it from 2.2 and 2.3 with next PRs
