### ISSUE TITLE
invite guest join meeting with email

### ISSUE THREAD

**Issue by liuhetongzi** [bigbluebutton/bigbluebutton#10391]
**Is your feature request related to a problem? Please describe.**
if can add a button share。share the meeting to the guests with email.  Thanks..
![image](https://user-images.githubusercontent.com/23496061/92191027-367e3500-ee95-11ea-963a-5bab259f8a62.png)

**Comment by matiasilva** [comment]
This is the repository for BigBlueButton, you're looking for Greenlight. github.com/bigbluebutton/greenlight
