### ISSUE TITLE
Integrate scrumblr as an etherpad alternative for all Scrum teams 

### ISSUE THREAD

**Issue by ghost** [bigbluebutton/bigbluebutton#10394]
#BBB with Pinboard Power

I would like to use scrumblr as an alternative to the etherpad presentation. For example I'm going to click on "Actions" I can choose an scrumblr board.

#What is scrumblr?
>scrumblr is a web-based simulation of a physical agile kanban board that supports real-time collaboration. it is built using >node.js, websockets (using socket.io), CSS3, and jquery. i hope you like it.

(https://github.com/aliasaria/scrumblr )

Thank you very much for this amazing project!

Here how it could look like!
![scrumblr_in_bbb](https://user-images.githubusercontent.com/70140488/92246977-d1433780-eec6-11ea-9235-a3ff27892cfc.jpg)

**Comment by matiasilva** [comment]
My two cents are that this is an interesting idea but my idea is that if you need something so niche, you should probably develop the integration yourself. This is not something that would be helpful to everyone.

**Comment by BenUtzer-git** [comment]
Hey Matiasilva, you're right it could be niche solution, but maybe more schools and universities are going to use Edu-Scrum or other agile methods in the future. And a lot of them are using BBB and other Open Source tools too. Thank you for your answer 👍
