### ISSUE TITLE
new way of installing bbb (on baremetal) with scalelite (on k8s)

### ISSUE THREAD

**Issue by yelhouti** [bigbluebutton/bigbluebutton#10399]
Hi, please concider adding this repo to your documentation, Hopefully it will help the next person:

https://github.com/elhoutico/bbb-scalelite-ansible-k8s

This playbook installs bbb servers using ansible on bare metal servers, and installs scalelite and all its dependencies in your k8s cluster

**Comment by matiasilva** [comment]
Hello! Thanks for this excellent contribution, would you mind adding them to the docs repository: https://github.com/bigbluebutton/bigbluebutton.github.io? I will definitely agree it will help others -- as the creator of the timeout playbooks, I'm happy to see them being used constructively!

**Comment by agussang** [comment]
Can you show topology and what feature and some screenshot about this installation.

**Comment by matiasilva** [comment]
@agussang I believe for such advanced deployments you would need a skilled system administrator, who should be able to deduce what you've asked for by looking at the ode.

**Comment by jihadajUAEU** [comment]
Many thanks to @yelhouti for the efforts. @matiasilva Agree with you that system administrator can install this script. Having some documentation/ steps will even help the admins to have quick start. @agussang

**Comment by agussang** [comment]
> @agussang I believe for such advanced deployments you would need a skilled system administrator, who should be able to deduce what you've asked for by looking at the code.

Hy, so you can install bbb without documentation if tim bbb build new rule? And you know witout bbb topology/schema? Don't be shit people, we are knowing who here as DevOps/Sysadmin.

**Comment by agussang** [comment]
> Many thanks to @yelhouti for the efforts. @matiasilva Agree with you that system administrator can install this script. Having some documentation/ steps will even help the admins to have quick start. @agussang 

Of course sir

**Comment by matiasilva** [comment]
*sigh*, I'm not even going to merit that with a response.
