### ISSUE TITLE
BBB 2.3 Alpha-2 Screen Share issue

### ISSUE THREAD

**Issue by dseral** [bigbluebutton/bigbluebutton#10400]
Describe the bug
Dear bbb team today i was installed BBB 2.3 Alpha-2  on Ubuntu 18.04.05 LTS for testing. I was found that chrome screen share is not working. 
Then i realize that this may be firewall problem of ubuntu 18.04 so i was disabled ufw and screen share started to work again. 
Firewall config looks like below:
Status: active

To                         Action      From
--                         ------      ----
OpenSSH                    ALLOW       Anywhere
Nginx Full                 ALLOW       Anywhere
16384:32768/udp            ALLOW       Anywhere
OpenSSH (v6)               ALLOW       Anywhere (v6)
Nginx Full (v6)            ALLOW       Anywhere (v6)
16384:32768/udp (v6)       ALLOW       Anywhere (v6)

To Reproduce

Open bbb demo page with chrome Browser
Try to use desktop share in application window

However with Firefox Browser its working even firewall is enabled.

BBB version (optional):
BigBlueButton Server 2.3 Alpha-2 (1323)

**Desktop (please complete the following information):**
 - OS: Windows 10 
 - Browser: Chrome 
 - Version : 85.0.4183.83 (Official Build) (64-bit)

Devrim

**Comment by rexon07** [comment]
Hi iam also facing the same issue. I tried disabling the firewall as well.

**Comment by prlanzarin** [comment]
Stale (test23.bigbluebutton.org is the testing mirror)
