### ISSUE TITLE
Upload pdf documents to rooms and permanently reamain in there for room's users (Instructors)

### ISSUE THREAD

**Issue by harika1258** [bigbluebutton/bigbluebutton#10404]
I Have 10 rooms with 150 users and 10 instructors.
Instructors would like to upload their pdf docs as a presentation files to rooms in advance and exists permanently duration course.
How can I do that?

**Comment by matiasilva** [comment]
Hi, please take a moment to familiarize yourself with the architecture of BBB (https://docs.bigbluebutton.org/2.2/architecture.html) after which you will be able to use the API properly (https://docs.bigbluebutton.org/dev/api.html#pre-upload-slides) to accomplish your goal. For further questions, please refer to https://docs.bigbluebutton.org/2.2/getting-help.html

**Comment by harika1258** [comment]
Thanks Silva. :-)
