### ISSUE TITLE
Add translation string [Error 401]

### ISSUE THREAD

**Issue by ryprfpryr** [bigbluebutton/bigbluebutton#10402]
The following line is missing in the translation files. This is a very relevant and common error message that should be available for modifications in /usr/share/meteor/bundle/programs/server/assets/app/locales/*.json 

https://github.com/bigbluebutton/bigbluebutton/blob/e4e44466339e621195fa2daa658909a8c01784c4/bigbluebutton-html5/imports/ui/services/auth/index.js#L197

![image](https://user-images.githubusercontent.com/68156081/92310566-34e06a00-ef86-11ea-9380-c034dc8bb5c9.png)

**Comment by ali-alhaidary** [comment]
No such key in main json file or transifex
