### ISSUE TITLE
Enable viewers to download the presentation

### ISSUE THREAD

**Issue by bigbluebutton-issue-import** [bigbluebutton/bigbluebutton#1040]
Originally reported on Google Code with ID 285

```
By default, BigBlueButton does not give the viewers any link to download 
the presentation.

Possible scenarios:

1.  Provide the download link automatically when the presenter has uploaded 
the slides

2.  Provide the download link only if the presenter has granted permissions 
for download.  There could be a check box during the upload process.

3.  Provide the user a list of download links after they logout (this keeps 
the presenter in control of the current slides during the presentation).


```

Reported by `ffdixon` on 2009-12-22 13:59:50

**Comment by capilkey** [comment]
In 2.0 there's an option when you upload a presentation to allow downloading it. If the option is selected then users are shown a button that they can click to download the clean presentation (no whiteboard marks).

**Comment by fcecagno** [comment]
In 2.0, the original file is downloaded - even if BigBlueButton converts the document to PDF and then SWF, the downloaded file will be the original one (that could be any supported format).
