### ISSUE TITLE
Bigbluebutton server hangs up regularly for about 30 seconds

### ISSUE THREAD

**Issue by MortezaTaghaddomi99** [bigbluebutton/bigbluebutton#10409]
I had multiple hanging up issues with bigblubebutton server. this problem happens 2, 3 times per hour. 
Our usage is not increased at this time. I guess this issue related to FreeSWITCH cpu usage. 

this image shows our CPU utilization vs participant. note that we have very little CPU utilization from 15:48 to 15:50. 
![image](https://user-images.githubusercontent.com/43267281/92474380-f995a380-f1f0-11ea-896b-eb53b63fa433.png)

additional information: 
CPU cores number: 16 cores
ram: 18 GB
max total CPU utilization at this period: 66%

server watch dog error: 
![image](https://user-images.githubusercontent.com/43267281/92476102-b0931e80-f1f3-11ea-8ca8-50ee09f1b8d9.png)

`sudo bbb-conf --check `
there is no potential problem. 

freeswitch CRIT log: 

> 2020-09-08 16:51:50.748402 [CRIT] switch_time.c:1203 Virtual Migration Detected! Syncing Clock

ufw is disabled now but the problem happens yet. 

bbb version: 
2.2.23

**Comment by MortezaTaghaddomi99** [comment]
I updated the bigbluebutton to the last version. but the problem happens yet. 
I don't know why the cpu usage increased that much. 

is there anybody else with this issue?

**Comment by basisbit** [comment]
For support requests, please use the [forum / mailing list](https://groups.google.com/forum/#!forum/bigbluebutton-setup). This issue tracker here is only for BBB development related issues. Sorry.
