### ISSUE TITLE
Get information about the breakout room when someone start talking and stop talking 

### ISSUE THREAD

**Issue by maychine-fatima** [bigbluebutton/bigbluebutton#10413]
in general if there is a voice in breakout room , we dont have any service that gives information about audio in breakout room

**Comment by matiasilva** [comment]
Hi, could you be more specific as to what "service" you're after?

**Comment by maychine-fatima** [comment]
in bigbluebuttonhtml5 , there is  a service about breakoutrooms , but i can get from thet just basic information like number of users id of meeting .. etc, but in fact if we join just with audio this breakout room, after multiple users we dont know if the principale user of that meeting has begined talking or not,  because this information to know if there is an audio there is usefull to control to join the audio of that breakout room or not, its not important to join it and you cant find any sound there.
thank you.

**Comment by matiasilva** [comment]
Do you mean a systemd service?
