### ISSUE TITLE
Two cameras with different pictures at the same time

### ISSUE THREAD

**Issue by Braehler** [bigbluebutton/bigbluebutton#10414]
**Is your feature request related to a problem? Please describe.**
As far as I know its currently only possible to have one camera on the screen. For example the webcam of the computer[...]

**Describe the solution you'd like**
It would be a great benefit for students and teachers to have the option to show 2 cameras shown at the same time. Like one is focused on the teacher, the second one shows the room and/ or the whiteboard in the classroom

**Describe alternatives you've considered**
The only other alternative right now is to use a web presenter streamer like the one which Blackmagic desing offers. With that in use, you can switch between two cameras. 
And there is a second way. You need to log into the room twice, share the webcam and disable the audio in the second tab. Then you have to cameras showing different pictures

**Additional context**

**Comment by matiasilva** [comment]
Hi, have a browse of this repository before posting. This was already integrated into the 2.3 alpha in #8374
