### ISSUE TITLE
Screenshare suddently stops on firefox when plug or unplug USB audio device [firefox]

### ISSUE THREAD

**Issue by vitormateusalmeida** [bigbluebutton/bigbluebutton#10418]
When I'm creen sharing on the bbb and disconnect the usb audio device, the screen sharing stops.

1. Open bbb in firefox and start a screen share
2. Plug or unplug an usb audio device

**Comment by daminebenq** [comment]
I tested this on google hangouts and bbb 2.2 using FF.
and here is the bug report: https://bugzilla.mozilla.org/show_bug.cgi?id=1663934

**Comment by tdjac0bs** [comment]
Nice catch @vitormateusalmeida  / @daminebenq .

As it's not a BBB bug itself, should we close this one @antobinary ?
