### ISSUE TITLE
Camera and audio share buttons do not work on IOS tablet

### ISSUE THREAD

**Issue by burakguder** [bigbluebutton/bigbluebutton#10415]
Most customers using  IOS TABLET do not work even if they press the camera and volume button

IOS TABLET,  
device updates have been made and the latest safari version has been installed

The 2.2 version did not have these problems. After updating to version 2.3, this trouble started to come
I think improvement needs to be done for customers using ios tablets

**Comment by amg-web** [comment]
iOS can no longer join last few days.
Tested on different servers with different version of 2.2

**Comment by burakguder** [comment]
this is so sad Is it because of some of the features it blocks?

**Comment by prlanzarin** [comment]
Please detail the precise version of iOS **AND** Safari.
Also: 2.3 is not production ready. It's alpha.

**Comment by prlanzarin** [comment]
Also try with the problematic device in test.bigbluebutton.org

**Comment by burakguder** [comment]
![WhatsApp Image 2020-09-09 at 21 04 02](https://user-images.githubusercontent.com/560147/92638846-a0f30300-f2e3-11ea-970d-b5b92cdf12f5.jpeg)

camera button not working on all ios tablets.  Works on test.bigbluebutton.org and no problems.  2.3 was working successfully until the last update. I need to rollback all servers to the old version :(

**Comment by Aitiler** [comment]
We have the same problem here. yesterday i set up a new server with ubuntu 18.04 and the bbb version 2.3-dev. Everthing is running fine so far as i can see (only the "problem" with the libreoffice issue after fresh install). Creating and joining a room on pc or android device is no problem. Audio and video works so far. Only our ipads (tested on several pads) have issues.
They can join or create a room. Enter the room. The echo test is fine. But if i want to push any button... nothing happens. the whole room freezes and you can´t do any other than shutting down safari and start it again.

iOS Version: 14.0.1
Safari: 14

The iPads work fine with the test server.

**Comment by NobbeBavaria** [comment]
We also have problems using BBB with iPads. Screen sharing isn't supported and starting the camera to share video results in error 1020. The rest works fine. 

BBB Installation: 2.2.26
Linux-Server: Ubuntu 16.0.4
Newest iOS and Safari

**Comment by PhMemmel** [comment]
2.3-beta-2 works flawlessly on iPad 14.4.2, Safari and Firefox, buttons work, audio, video, no problems at all. Tested on test23.bigbluebutton.org running 2.3-beta-2, html5 version 1552. Guess this can be closed.

Screensharing not working of course, but this is known to be not possible on iOS/iPadOS with browser based software.

**Comment by Davka** [comment]
also works on my iphone and ipad

**Comment by prlanzarin** [comment]
Thanks for re-testing @PhMemmel and @Davka.

Closing as stale and seemingly fixed.

**Comment by Piotr-Fr** [comment]
Please reopen if possible.
Today our client for the first time used BBB, iPad (some new), and no Share button at all.

**Comment by Piotr-Fr** [comment]
> 

Hi. Thanks. The point is, we can't bother our clients with additional contacts and any bug fixing related efforts, a level of clients at which we must deliver, not ask for work in order to fix anything (or even maybe not). I will try to open anyway. Once again, thank you for the reply.
