### ISSUE TITLE
Lag and session timeout suddenly

### ISSUE THREAD

**Issue by emamirazavi** [bigbluebutton/bigbluebutton#10426]
Sometimes for many users (almost 250 users distributed in 40-50 sessions, 1 to 4 activated web cams with even no active viewer in FS conference) we have very strange problem in authenticating. BBB specific API (implemented by Java), works like charm but websocket API (socketjs implemeted by meteor) has awfully lag in response leading to session timeout! Everything lead to destroy relation between sub systems certainly FS audio conference. At this time 32 CPU cores are fresh with 40 to 50 idle time! How can i debug these problems? Should i configure FS conference interval and increase it or anything else to establish more light and fast connection requested in socketjs? Many many thanks in advance.

more information:
2.2.19 BBB stack version
2.2.23 BBB html5 client version
OS: ubuntu 16.04
installation process run by BBB documentaion step by step.

**Comment by matiasilva** [comment]
Hi, please follow the instructions on https://docs.bigbluebutton.org/2.2/getting-help.html for getting help with any issues.

**Comment by emamirazavi** [comment]
I requested join to the development group in google many times and nothing happen! What are you doing?!!!

**Comment by matiasilva** [comment]
What is who doing? You should be joining the setup group, not the development group. Also, since you're asking for help from people volunteering their time, I suggest a bit of courtesy and kindness.

**Comment by emamirazavi** [comment]
Excuse me sir,
Thanks a lot for your response,
I will try setup group
Good luck,
Under God.
