### ISSUE TITLE
2.3-dev use Libreoffice in docker - still needed some changes in bbb files and docs

### ISSUE THREAD

**Issue by AndNovAtor** [bigbluebutton/bigbluebutton#10427]
2.3-dev on Ubuntu 18.04 is installed with libreoffice in a docker container, by installing ```bbb-libreoffice-docker```. In 2.2 libreoffice is installed "into" system.

So, there are some "misprinting"/outdated code/text in bbb installs and bbb 2.3-dev doc.

For example:

1) bbb-conf (for wxample, with --restart) still run ```dpkg-query``` for searching libreoffice package - and there are no libreoffice packages, so dpkg-query warning printed
2) on https://docs.bigbluebutton.org/dev/dev23.html#installation there are basic bbb packages list. Maybe it needed to add ```bbb-libreoffice-docker``` to this list, and maybe to add some another info about this package

**Comment by ffdixon** [comment]
Both points are good -- will update docs before next release of 2.3-dev.

**Comment by mikhailnov** [comment]
bbb-install configures a PPA with libreoffice even on ubuntu 18.04, that is probably not needed

**Comment by antobinary** [comment]
Retagging to 2.5 where the build/ directory contains all the packaging related files (open source). Once resolved we can backport to all maintained versions

**Comment by gustavotrott** [comment]
I think both suggestions are done on current version.





> * bbb-conf (for wxample, with --restart) still run `dpkg-query` for searching libreoffice package - and there are no libreoffice packages, so dpkg-query warning printed

I can't find references for libreoffice package in bbb-conf anymore.

> * on https://docs.bigbluebutton.org/dev/dev23.html#installation there are basic bbb packages list. Maybe it needed to add `bbb-libreoffice-docker` to this list, and maybe to add some another info about this package

It seems to be in the list now:
![image](https://user-images.githubusercontent.com/5660191/155772848-27519277-e034-43dc-a251-e29e9135f61c.png)
