### ISSUE TITLE
2.3-alpha-2: Error message and cant progress in Android on Chrome for  user to allow microphone or/and Share webcam

### ISSUE THREAD

**Issue by erpsolns** [bigbluebutton/bigbluebutton#10428]
**Describe the bug**
2.3-alpha-2 Error message and cant progress in Android on Chrome for  user to allow microphone or/and Share webcam
"another app in displaying over chrome 
to change permission for this site close the other app and try again  if you cant turn off the app-
turn off the app’s permission to display over other apps in android settings"
I tried to see - all apps have permission to display  over the apps - so I cant display everything off

**To Reproduce**

**Expected behavior**
The microphone and /or video camera should have been appearing 

**Actual behavior**
Goes in a loop Try again     or Open settings

**Screenshots**
If applica![WhatsApp Image 2020-09-10 at 8 50 36 PM](https://user-images.githubusercontent.com/31876291/92719999-5470fb80-f3a7-11ea-96f7-34fb5a15624e.jpeg)ble, add screenshots to help explain your problem.

**BBB version (optional):**
BigBlueButton continually evolves. Providing the version/build helps us to pinpoint when an issue was introduced.
Example:
$ sudo bbb-conf --check | grep BigBlueButton
BigBlueButton Server 2.3 (1816)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, Mac]
 - Browser [e.g. Chrome, Safari]

**Smartphone (please complete the following information):**
 - Device: Android - Samsung galaxy 9 plus
- Browser  Chrome

**Additional context**

**Comment by erpsolns** [comment]
I found out that this is Facebook - Messenger app - it is not showing up in any open up - but it is floating.  When I DELETED THAT THE AUDIO WORKED AND VIDEO WORKED

**Comment by antobinary** [comment]
Hi @erpsolns,
Is this still an issue?

**Comment by erpsolns** [comment]
When i removed facebook messenger floating - no problem - all works.
