### ISSUE TITLE
Error 1002 Could not make a websocket connection.

### ISSUE THREAD

**Issue by Schoolkid123** [bigbluebutton/bigbluebutton#10435]
So i am new to all this computer stuff and my school uses schoology  which uses BBB for conferences. Fellas, you got to give me a straight forward response. Half of what I see out there is unintelligible code. Basically, it has been working for me for the past month but now the mic wont connect.

**Comment by matiasilva** [comment]
Does https://test.bigbluebutton.org/ work for you? If so, contact your system administrator.

**Comment by jarmediagmbh** [comment]
Otherwise: possibly this error: #9667?

**Comment by basisbit** [comment]
closing this because of lack of feedback from issue creator.

**Comment by JCatGitHub2020** [comment]
I've had the #1002 Could not make a WebSocket error a couple of times, when logging in failed. The workaround seems to be just to close the tab and start again, log in again (after checking any cable connections - microphone/ethernet).
