### ISSUE TITLE
Media Server is offline error 2001

### ISSUE THREAD

**Issue by javadzobeidi** [bigbluebutton/bigbluebutton#10430]
I was on bionic-230-dev and it works very well. now when i start sharing my webcam , we have this error
error 2001 Media Server is offline
nginx —————————————————► [✔ - active]
freeswitch ————————————► [✔ - active]
redis-server ——————————► [✔ - active]
bbb-apps-akka —————————► [✔ - active]
bbb-fsesl-akka ————————► [✔ - active]
tomcat8 ———————————————► [✔ - active]
mongod ————————————————► [✔ - active]
bbb-html5 —————————————► [✔ - active]
bbb-webrtc-sfu ————————► [✔ - active]
kurento-media-server ——► [✔ - active]
etherpad ——————————————► [✔ - active]
bbb-web ———————————————► [✔ - active]

i think i don't have   bbb-transcode  and i am trying to install many times with bbb-install but it doesn't install.
Please help, it is very urgent.

**Comment by matiasilva** [comment]
The instructions on https://docs.bigbluebutton.org/2.2/getting-help.html apply. If it's urgent, contact commercial support. Otherwise, you can get help but it will take longer. Have you `sudo bbb-conf --setip FQDN`? Are you upgrading from a previous version? 

Note: 2.3 is in ALPHA, it is NOT production ready.

**Comment by javadzobeidi** [comment]
> The instructions on https://docs.bigbluebutton.org/2.2/getting-help.html apply. If it's urgent, contact commercial support. Otherwise, you can get help but it will take longer. Have you `sudo bbb-conf --setip FQDN`? Are you upgrading from a previous version?
> 
> Note: 2.3 is in ALPHA, it is NOT production ready.

yes i have bbb-conf. my Ubuntu is 18.04 and  i have to installed 2.3 bbb. so i think need to downgrade if you don't have any idea.

**Comment by matiasilva** [comment]
How did you install it? You are supposed to start with a fresh install for 2.3. Also, I asked if you had run that command, not if you have the bbb-conf utility -- you should have it already, it comes with BBB.

Regarding your downgrade comment, 2.3 is not for production so your production servers should still be 2.2 anyway.

**Comment by javadzobeidi** [comment]
i installed with bbb-install.sh | bash -s -- -v bionic-230-dev.
I ran bbb-conf and restarted kurento and bbb-webrtc-sfu . Sometimes I can get videos and sometimes get media errors.
After each reset of kurento and webrtc-sfu I can get video for the first time .

**Comment by matiasilva** [comment]
on a fresh server? what is running bbb-conf? it is a utility..so what commands did you use?

**Comment by javadzobeidi** [comment]
yes on a fresh server .
bbb-conf --setip hostname
 systemctl restart  kurento-media-server
 systemctl restart  bbb-webrtc-sfu

**Comment by javadzobeidi** [comment]
When start using webcam it connects after two or three tries. It says media server is offline for the first and second time.

**Comment by Davka** [comment]
Have you activated `enableMultipleKurentos`

If so, then check whether all three instances have started
