### ISSUE TITLE
Webcam isn't shown on playback

### ISSUE THREAD

**Issue by hamedunik** [bigbluebutton/bigbluebutton#10437]
**Describe the bug**
after click on record button the session with chat & presentation & audio is recorded and is available in playback. but in playback webcam video doesn't appear.

**To Reproduce**
1. Go to 'room'
2. Click on 'record'
3. After production go to  'playback'
4. No webcam video playback

**Expected behavior**
playback of webcam beside presentation and audio
**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 85

**Comment by matiasilva** [comment]
What server version? If this is 2.2 then please use the mailing lists.

**Comment by hamedunik** [comment]
I'm using Version 2.2

**Comment by matiasilva** [comment]
Then there's probably an issue with your installation. The mailing lists and information on getting help are here: https://docs.bigbluebutton.org/2.2/getting-help.html
