### ISSUE TITLE
Error 1007

### ISSUE THREAD

**Issue by pgenderson** [bigbluebutton/bigbluebutton#10444]
**Describe the bug**
User gets that error when trying to connect to conference with microphone.

**Desktop (please complete the following information):**
 - Windows
 - Chrome
 - latest

I used bbb-install.sh to install BBB with SSL and Greenlight. I can access my server (and the other user can too) with my domain through DNS. I'm behind a NAT but already port-forwarded, and I was able to video and voicechat fine with someone else on my LAN last night.

**Comment by matiasilva** [comment]
Hi,, please follow the instructions on https://docs.bigbluebutton.org/2.2/getting-help.html for how to get help.
