### ISSUE TITLE
1007 error only on chrome android

### ISSUE THREAD

**Issue by akshaykatale99** [bigbluebutton/bigbluebutton#10442]
We are facing 1007 error only on chrome android. it was working previously but stopped working suddenly without making any changes. i have tested it on desktop chrome its working fine. only not working on android chrome and android firefox. tried with different devices and network but the same error on all devices

**Comment by matiasilva** [comment]
Please follow the instructions on https://docs.bigbluebutton.org/2.2/getting-help.html for support requests.
