### ISSUE TITLE
Users are able to unmute themselves

### ISSUE THREAD

**Issue by ahmdqader** [bigbluebutton/bigbluebutton#10447]
Users are able to unmute themselves

**Comment by matiasilva** [comment]
Follow the issue template please.

**Comment by ffdixon** [comment]
We're looking at adding the ability for a moderator to do per-user lock settings in a future version.

**Comment by ahmdqader** [comment]
> We're looking at adding the ability for a moderator to do per-user lock settings in a future version.

Is there any way to prevent user from unmuting themselves?

what is the purpose of muting all users if they can unmute themselves?

**Comment by ffdixon** [comment]
> Is there any way to prevent user from unmuting themselves?

Yes, you can use the lock settings to lock their microphones (click the Gear icon and choose 'Lock viewers').  However, this applies to all viewers (moderators are unaffected by lock settings).

**Comment by ChristopheRit** [comment]
Locking the microphones of all users before they start a session prevents them to get the icon for the microphone for the rest of the session (even if a moderator unlocks the user). The only way I found to go around the problem was to ask them to refresh the webpage and this makes the icon appears on the bottom and they can use the sound then. Is that a bug on my installation only or more generally?

**Comment by ahmdqader** [comment]
> Locking the microphones of all users before they start a session prevents them to get the icon for the microphone for the rest of the session (even if a moderator unlocks the user). The only way I found to go around the problem was to ask them to refresh the webpage and this makes the icon appears on the bottom and they can use the sound then. Is that a bug on my installation only or more generally?

I have this problem too

**Comment by defnull** [comment]
> Locking the microphones of all users before they start a session prevents them to get the icon for the microphone for the rest of the session (even if a moderator unlocks the user). The only way I found to go around the problem was to ask them to refresh the webpage and this makes the icon appears on the bottom and they can use the sound then. Is that a bug on my installation only or more generally?

After unlocking a user, he/she can simply click "leave audio" and then "join audio" again. The echo-test modal will re-appear in which they can select that they want to join with microphone, as usual.

**Comment by ahmdqader** [comment]
> > Locking the microphones of all users before they start a session prevents them to get the icon for the microphone for the rest of the session (even if a moderator unlocks the user). The only way I found to go around the problem was to ask them to refresh the webpage and this makes the icon appears on the bottom and they can use the sound then. Is that a bug on my installation only or more generally?
> 
> After unlocking a user, he/she can simply click "leave audio" and then "join audio" again. The echo-test modal will re-appear in which they can select that they want to join with microphone, as usual.

but this is unpractical, why to refresh the web page or leave audio and join again, the microphone icon must be real time

**Comment by defnull** [comment]
Listen-only users receive audio from kurento (for efficiency reasons), while bi-directional audio must connect to freeswitch to work properly. The browser must re-establish the audio connection and ask for permission to use the microphone first, which requires user interaction in some cases and cannot be fully automated. It's just two clicks and a short echo-test (which is useful anyway, so users know everything works).

The UI could be more clear, though. Sure.

**Comment by matiasilva** [comment]
> the microphone icon must be real time

says who? other UIs might tell you that but it most definitely isn't instantaneous
