### ISSUE TITLE
Show room URL at better place on HTML5 client

### ISSUE THREAD

**Issue by hiroshisuga** [bigbluebutton/bigbluebutton#10441]
**Is your feature request related to a problem? Please describe.**
Upgraded to 2.3, BBB does not show the room URL (to invite people) anymore in the chat window.

**Describe the solution you'd like**
(1) In HTML5 client, a toast describing the room URL is called up from the three dots button on the top right.
(2) Alternatively, the URL is simply shown to the product information toast.
(3) Or. the URL message in the chat window revives (by fixing the bug in Greenlight or BBB), which I think less elegant.

**Comment by hiroshisuga** [comment]
It seems to be GreenLight that is showing the URL message in chat.

**Comment by matiasilva** [comment]
What meeting URL? The one produced by Greenlight?

**Comment by hiroshisuga** [comment]
Hi @matiasilva ,
Correct. I think showing it in the message window called up from the three dot button on the top right makes more sense, similar to Zoom.

**Comment by matiasilva** [comment]
I see, but note that the URL is purely a Greenlight thing. The message that any front-end passses via the create call could be anything, Greenlight just so happens to make it the meeting URL. Perhaps a meeting URL parameter should be created?

**Comment by hiroshisuga** [comment]
@matiasilva thanks for letting me know. I was trying to do a PR but realized that there is no parameter describing the room URL in the current implementation. Another possibility is to let html5 client read what is written in the chat window, but this does not make a lot of sense.

Anyway, I would feel more comfortable if BBB and Greenlight walk side by side. The thumbnails in Greenlight are not very useful now due to this lack of collaboration...

One problem left to be solved is why the room URL info from GL is not displayed in BBB 2.3.

**Comment by hiroshisuga** [comment]
probably related to #10146

**Comment by mrkeksi** [comment]
@hiroshisuga solved?

**Comment by hiroshisuga** [comment]
partially solved, closing it.
