### ISSUE TITLE
Removing redundant locale

### ISSUE THREAD

**Issue by hiroshisuga** [bigbluebutton/bigbluebutton#10445]
**Describe the bug**
Japanese locales ja and ja_JP are duplicate. 

**Expected behavior**
I think only "ja_JP" (or "ja"?) is enough. 

**Additional context**
Greenlight has only "ja_JP". Is there any good reason to keep two locales in BBB?

**Comment by matiasilva** [comment]
A similar situation happened with the German locale. I think one of them is being removed.

**Comment by hiroshisuga** [comment]
related to #10392

**Comment by hiroshisuga** [comment]
I think removing ja_JP makes sense, like in German language. 
I will also stop tranalating ja_JP.

**Comment by antobinary** [comment]
ja_JP was removed from Transifex. ja was more complete.
