### ISSUE TITLE
'userdata-bbb_skip_video_preview=true' isn't affecting the meeting

### ISSUE THREAD

**Issue by daminebenq** [bigbluebutton/bigbluebutton#10454]
tested in **2.3 servers**

**to reproduce**, start a meeting with the following custom parameter: **`userdata-bbb_skip_video_preview=true`**
and start sharing webcam:

**expectation**: 
webcam preview modal should not appear

**test result**:
webcam preview modal is appearing

**Comment by parrajeremy** [comment]
I can confirm the same behavior. 

settings.yml -> skipVideoPreview: true

in my join call:
            'fullName': full_name,
            'meetingID': str(self.meetingID),
            'password': password,
            'joinViaHtml5': True,
            'userdata-bbb_skip_check_audio': False,
            'userdata-bbb_skip_video_preview': False,
            'userdata-bbb_force_restore_presentation_on_new_events': True,

video preview does not respond accordingly

**Comment by ramonlsouza** [comment]
Checking the code, I noticed that on PR #8353 a change was made so this parameter is ignored if the "share webcam" button is pressed, and is only checked if the `userdata-bbb_auto_share_webcam` (share webcam automatically upon loading the client) parameter is also set to `true`.

If this is the correct behavior, it could be mentioned in [docs](https://docs.bigbluebutton.org/2.2/customize.html#kurento-parameters).
