### ISSUE TITLE
Participants using emojis as or in name are unable to connect to the audiostream

### ISSUE THREAD

**Issue by ContainsLiquid** [bigbluebutton/bigbluebutton#10452]
Participants using emojis as or in their name are unable to join the call. The modal where they can select to just listen or to speak still appears but the buttons are not working.

Expected behavior would be:
* The participant can use emojis without anything crashing, or
* The participant is informed before joining that emojis can not be part of the name

I would suggest the second option by filtering the user input with a regex that checks for emojis and tells the user to not use them as name.

**Comment by PlumedArcher** [comment]
For me it does work on Chrome on version 2.3.

**Comment by schrd** [comment]
@ContainsLiquid what emoji did you use? I can't reproduce this on neither 2.2 nor 2.3. Can you still reproduce this on 2.3? Please test on https://test23.bigbluebutton.org
