### ISSUE TITLE
feature request for pen paint tool with transparent colors / transparency

### ISSUE THREAD

**Issue by comsyspro** [bigbluebutton/bigbluebutton#10465]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
At the moment when you paint in the presentation slides you can only use solid colors which covers the content of the slide. So it would be useful if you could also select 1 or 2 colors with transparency so you can use it as a marker pen tool. As I saw in the code the colors which are defined in the file " settings.yml " and I tried to change the colors there and add RGBA or HEX with alpha values. In the presenter GUI you can see then that the colors have changed accordingly in the color picker but when you then paint something on the whiteboard the color stays solid.

**Describe alternatives you've considered**

**Additional context**

**Comment by pedrobmarin** [comment]
Closing this one to endorse https://github.com/bigbluebutton/bigbluebutton/issues/11012
