### ISSUE TITLE
Transfer Recording

### ISSUE THREAD

**Issue by harika1258** [bigbluebutton/bigbluebutton#10466]
Hi Everybody...

I transfer all of my recording files with dependencies in the bigbluebutton server to new server.  how can I represent them group by users?

**Comment by matiasilva** [comment]
Follow the instructions for getting help, please. https://docs.bigbluebutton.org/2.2/getting-help.html

**Comment by harika1258** [comment]
Doode, Why you closed my issues!? Definitely I check out [https://docs.bigbluebutton.org/2.2/getting-help.html](url) in advance!

**Comment by matiasilva** [comment]
*Are you sure?*

I quote this line 5 paragraphs down from the top of the page:

> If you find that the problem still persists or you have any other questions, you can ask other users in the mailing lists. If you suspect that your issue is a bug, you can post on our issue tracker, otherwise refrain from using the GitHub issue tracker for general queries.

more specifically,

> otherwise refrain from using the GitHub issue tracker for general queries.
