### ISSUE TITLE
Playback.html mobile mode fullscreen recommendation

### ISSUE THREAD

**Issue by blueiceprj** [bigbluebutton/bigbluebutton#10464]
**Describe the bug**
Playback.html In mobile mode dividing the screen two section and I can't see any video in full screen. As bellow example.

**Expected behavior**
User can click to camera or desktop video than can see the video in full screen.

**Screenshots**
This is current version of player
<img width="1047" alt="Screenshot 2020-09-15 at 11 23 36 PM" src="https://user-images.githubusercontent.com/1829975/93267310-c6808080-f7ab-11ea-9a40-d74944f81c4d.png">

This is expected player screen

<img width="1007" alt="Screenshot 2020-09-15 at 11 29 39 PM" src="https://user-images.githubusercontent.com/1829975/93268363-5541cd00-f7ad-11ea-9a0b-aa7bb63b63a3.png">

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser Chrome
 - Version  85.0.4183.83

**Smartphone (please complete the following information):**
 - Device: iPhone8
 - OS: iOS
 - Browser Chrome
 - Version last

**Comment by GhaziTriki** [comment]
We highly encourage using the new playback player which has backward compatibility with the previous versions https://github.com/bigbluebutton/bbb-playback
