### ISSUE TITLE
Update to 2.2.24 with three Kurento Media Servers activated - Problem with webcam and screen sharing in the same time

### ISSUE THREAD

**Issue by aguerson** [bigbluebutton/bigbluebutton#10467]
Hi guys,
I hope your are fine.
I have just updated my BBB server to 2.2.24 and I applied the rule to use three Kurento Media Servers

I have encountered problems with sharing webcam and my desktop screen in the same time.

Now, with the  three Kurento Media Servers activated, I have to choose between webcam shared or sharing my desktop screen.

Is that normal ?

Is there a way to solve this ?

Regards,
Aurélien.

**Comment by ffdixon** [comment]
>  I have to choose between webcam shared or sharing my desktop screen.

Can you be more specific in choosing.  Is this a change in the UI?  Can you post a screen shot to this issue.

**Comment by aguerson** [comment]
To be more simple

If my webcam is enabled ( blue button activated ) and if I want to active my shared my screen ( white button ), nothing append
If I disable my webcam and I click again to share my screen, the white button comes blue and I can shared my screen.

The bug is that you can't active your webcam if you have you screan shared and vis versa

I could post a screenshot if you want, but all is in the text.

**Comment by aguerson** [comment]
![pb_](https://user-images.githubusercontent.com/64071247/93338814-15b9c600-f82b-11ea-8103-9f6db322742f.jpg)

**Comment by ffdixon** [comment]
Got it -- I can reproduce it here locally.  Thanks, we're working now on figuring out why this is happening.  

In the meantime, we recommend turning off the multiple Kurento servers for the moment by editing `/etc/bigbluebutton/bbb-conf/apply-conf.sh` and changing the line to

~~~
disableMultipleKurentos
~~~

and then running `sudo bbb-conf --restart`

**Comment by ffdixon** [comment]
Steps to reproduce.

Setup BigBlueButton 2.2.24 and enable multiple Kurento servers.  Login to Demo Meeting with Chrome and FireFox

1.  On Chrome, share webcam

Webcam appears in FireFox

2. On Chrome, share screen

On FireFox, screen sharing does not appear (only spinning arrows)

3.  On Chrome, stop sharing webcam
4.  On Chrome, share screen again

On FireFox, screen now sharing appears.

Disable multiple Kurento servers and do (1) to (4).  Webcam and screen sharing appear in FireFox.


2.  Share webcam



On Chrome, both webcam and screen share appear in FireFox as expected.

**Comment by ffdixon** [comment]
@aguerson  After enabling three kurento servers, can you also run this command

~~~
sed -i 's/;pemCertificateRSA=.*/pemCertificateRSA=\/etc\/kurento\/dtls-srtp.pem/g' /etc/kurento/modules/kurento/WebRtcEndpoint.conf.ini
~~~

and then do `bbb-conf --restart` and let us know if you can now see both the webcam and screen share stream in FireFox.

**Comment by bilias** [comment]
I also had this problem after enabling multiple kurento servers.

kurento logs show:
2020-09-16T15:23:52,021472 1188 0x00007fa69a7fc700 warning dtlsconnection            gstdtlsconnection.c:694 openssl_poll() <GstDtlsConnection@0x7fa6c40481a0>  do_handshake encountered BIO error

**Comment by aguerson** [comment]
I Try. Just a minute

**Comment by aguerson** [comment]
Well done !
It is OK now !
What is the problem ? The way you generate the selfsigned cert ?

How to resolv ?

**Comment by aguerson** [comment]
You posted before I did it ;)

**Comment by aguerson** [comment]
Thank you Fred ;)

**Comment by bilias** [comment]
works for me.
also tested enable/disable workflow

**Comment by ffdixon** [comment]
Thanks guys, there will be a 2.2.25 shortly with this fix.

**Comment by bilias** [comment]
Does logic exist to change certificate CN if you change hostname?

**Comment by ffdixon** [comment]
@bilias For an abundance of caution, just had it generate a new certificate 

 https://github.com/bigbluebutton/bigbluebutton/pull/10473

**Comment by aguerson** [comment]
;)

**Comment by bilias** [comment]
lol :)
you could also just delete the cert when --setip runs and is different than the previous

**Comment by aguerson** [comment]
It depends of one thing, is that changhe affect the clients ?
if no, you can force to recreate a cert each time you restart bbb
else the way of bilias is more secure
