### ISSUE TITLE
Shared notes are no longer available

### ISSUE THREAD

**Issue by hbel** [bigbluebutton/bigbluebutton#10472]
**Describe the bug**
After upgrading to the latest builds of BBB 2.2.0- 1024 (HTMl5 client) and 2.2.0-62 (etherpad), there is no longer a shared notes option in the left-side panel, regardless of whether I create rooms via Greenlight or via the Nextcloud Big Blue Button App.

**To Reproduce**
1. Update BBB to the versions mentioned above and restart the server.
2. Open a room via Greenlight.
3. Participate with or without microphone.

**Expected behavior**
There is a *shared notes* option in the left panel. 

**Actual behavior**
There is no such option

**Screenshots**
![image](https://user-images.githubusercontent.com/7416029/93348596-b3ff5900-f836-11ea-9297-73dc795f07a2.png)

**BBB version (optional):**
BigBlueButton Server 2.2.24 (2142

**Desktop (please complete the following information):**
 - OS: Mac OS Catalina, Chrome OS
 - Browser Chrome
 - Version 85

**Comment by pedrobmarin** [comment]
Hi @hbel . This normally means one of three things: your notes are somehow disabled at your client settings https://github.com/bigbluebutton/bigbluebutton/issues/6801 ; there is a mismatch at your etherpad's server API_KEY and the key configured at the same settings file https://github.com/bigbluebutton/bigbluebutton/issues/9027 or your etherpad server is somehow offline. The last one you can check by running `sudo bbb-conf --status`.

If everything looks at the right place, you can try the ultimate form of machinery fixing that lead mankind to the point we are today turning on and off again.

**Comment by hbel** [comment]
Thanks, for some reason note was disabled in the HTML5 clients settings. Is that meant to be the new default?

**Comment by pedrobmarin** [comment]
Not that I'm aware of. But I did see some updates failing on enabling it in the past.
