### ISSUE TITLE
Do monitoring detects other browser tab or window open and on focused (active)

### ISSUE THREAD

**Issue by OverShifted** [bigbluebutton/bigbluebutton#10477]
Excuse me if this issue is asked in the wrong place.
I am not a bbb developer but I have a quick question.
We use bbb in school and one of the admins said to me: `We can use bbb monitoring to detect you are in another tab or window or not `
is he right?

if yes, then is it using focus API?
so I can stimulate the browser to get focus events with some `winapi` code I already have (I am using windows10).
if no, then how can I play a trick with this system?

**Comment by matiasilva** [comment]
No, you can't. The right place to ask is: https://docs.bigbluebutton.org/2.2/getting-help.html#help-using-bigbluebutton

**Comment by OverShifted** [comment]
he can't do it or I can't play a trick?

**Comment by matiasilva** [comment]
I don't know what the admin is referring to when they say "bbb monitoring". A second thing to consider is that BBB is open source and your school may well have modified the code to include such a feature.

**Comment by OverShifted** [comment]
Thank you for your reply and excuse me because of asking question in the wrong place
