### ISSUE TITLE
2.3-alpha-2 clicking user list toggle does not restore it to previous width

### ISSUE THREAD

**Issue by caniwi** [bigbluebutton/bigbluebutton#10476]
**Describe the bug**
In a html5 session, click to collapse the user list, it shrinks but on clicking again to restore, it does not restore to the same width.

**To Reproduce**
1. Go into room
2. Click on user list toggle icon in upper left to collapse
3. Click on user list toggle icon in upper left to expand
4. The expansion is much narrower than original.

**Expected behavior**
Expansion of user toggle expands to be pre-collapse size.

**Actual behavior**
Expansion of user toggle is narrower than original making it difficult to read.  Expanding public chat or shared notes then also expand narrower.

**Screenshots**

**BBB version (optional):**
BigBlueButton continually evolves. Providing the version/build helps us to pinpoint when an issue was introduced.
Example:
$ sudo bbb-conf --check | grep BigBlueButton
BigBlueButton Server 2.3.0-dev (1324)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser Firefox
 - Version 80.0.1

**Smartphone (please complete the following information):**
Not tested

**Additional context**
Also happens on Google Chrome 85.0.4183.102

**Comment by LMSSPACE** [comment]
I have the same issue too and opened an issue post for this problem too.

**Comment by PlumedArcher** [comment]
On Google Chrome 89.0.4389.82 it's the same problem with the user list. Can be fixed by expanding manually.
Public chat or shared notes don't expand narrower though.

**Comment by ffdixon** [comment]
Tested on https://test23.bigbluebutton.org/ which is running the latest build of 2.3-alpha8 and still occurs there.

**Comment by antobinary** [comment]
Likely addressed in https://github.com/bigbluebutton/bigbluebutton/pull/12394

**Comment by ramonlsouza** [comment]
not reproducible (tested in 2.4)

![userlist-width](https://user-images.githubusercontent.com/3728706/129722412-e8ff9379-9600-4f49-8525-7f4514c8bdd4.gif)
