### ISSUE TITLE
Add new user state "exercise finished"

### ISSUE THREAD

**Issue by g-v-egidy** [bigbluebutton/bigbluebutton#10475]
I teach online courses where the students are expected to solve small exercises during the online meeting. I need to know when each student is finished with their exercise, to know when to start continuing the course or who might need some extra help with their exercise. Currently I misuse the "Thumbs up" state for this, so I can see the finished state in the user overview. But I always have to explain this and sometimes a student forgets what to do and so on.

I would like to have a dedicated "exercise finished" or just "finished" state for this. I suggest to use a checkmark icon for it. 

I think it would be ok if this state was handled just like the regular states a user can set, like Happy, Sad, Thumbs up and so on.

**Comment by iSamof** [comment]
Our users run a variety of meetings. A dedicated status of "Exercise Finished" would customise BBB to specific educational classes and be irrelevant to other uses. While the focus of BBB is education, there is no need to for it to move towards excluding other uses.

A checkmark is broadly usable if it is not specifically labelled "Exercise Finished". What may help the OP and the entire user base would be custom statuses populated at meeting runtime by the front end (from a Greenlight session config or other front end). 

This enables varying statuses for lots of applications/audiences. Even statues that vary from session to session, depending on need, become possible.

**Comment by ffdixon** [comment]
We are doing some work on the thumbs up/ thumbs down to give the instructor an easy way to ask a yes/no question.  We'll be sharing some designs on this shortly, and it might be more applicable to ask for a "thumbs up" when done than raise hand.
