### ISSUE TITLE
After upgrade to 2.2.5 the "Connecting to echo test" never ends

### ISSUE THREAD

**Issue by rabser** [bigbluebutton/bigbluebutton#10478]
**Describe the bug**
After the upgrade to the latest release, when enabling the microphone, the popup with "Connecting to echo test" never pass to the next step; the audio loopback does works as i can hear myself.

**To Reproduce**
1. open a room
2. enable microphone
3. the test never ends

**Expected behavior**
it should pass to the "i ear/i cannot ear myself" UI

**Actual behavior**
the firefox console prints out:
Thu Sep 17 2020 11:07:45 GMT+0200 (Central European Summer Time) | sip.invitecontext.mediahandler | RTCIceChecking Timeout Triggered after 5000 milliseconds sip.js:2900:10
Thu Sep 17 2020 11:08:12 GMT+0200 (Central European Summer Time) | sip.transaction.ict | Timer B expired for INVITE client transaction z9hG4bK933051 sip.js:2900:10
Thu Sep 17 2020 11:08:12 GMT+0200 (Central European Summer Time) | sip.transaction.ict | Timer M expired for INVITE client transaction z9hG4bK933051 sip.js:2900:10

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser firefox

**Additional context**
i tried many bbb-conf --clean and --restart but without luck.
I tried also to change to three kurento media server and back to one, but no changes.

**Comment by matiasilva** [comment]
Did you `sudo bbb-conf --setip your.fqdn`?

**Comment by rabser** [comment]
After filing this issue, i tried the same command you suggested, remembering that in the past I had a problem with the breakout rooms urls, solved by a setip: I can confirm that **it solve the problem**.
I'll add the bbb-conf --setip <fqdn>  to my automated update script, as it seems needed often.

**Comment by ffdixon** [comment]
Anytime you install an update to BigBlueButton, to ensure that all the configuration files are updated, you need to do `bbb-conf --setip`.  See

  https://docs.bigbluebutton.org/2.2/install.html#upgrading-from-bigbluebutton-22

**Comment by rabser** [comment]
You're surely right, but i (erroneously) interpreted that these instructions should be applied only in case of major upgrades (ie. 2.0 to 2.2) and not needed necessarily in minor versions (2.2.x to 2.2.x+1) using the classic apt-get update/upgrade.
Again, i was wrong about it,  but maybe adding some slightly changes to the documentation can help other users like me.

Thanks again for your effort and support.

**Comment by matiasilva** [comment]
Every time a new update is released, a few issues like this pop up, so it should probably be highlighted better. Then again, few people read the docs...

**Comment by rabser** [comment]
Unfortunately, yes, I know.
Just for the sake of BBB, the apply-config.sh template embedded in apply-lib.sh is missing the reference to enableMultipleKurentos / disableMultipleKurentos, even if corresponding bash functions are there.

**Comment by ffdixon** [comment]
I think we'll just put a link to the docs in the template.
