### ISSUE TITLE
Change pencil cursor for tiny dot cursor when drawing

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#10483]
When drawing on the whiteboard with pen, turn the cursor into a tiny dot. This way the pen shape will not be in the way of the drawing.

First requested in https://groups.google.com/g/bigbluebutton-users/c/AxW-ekRTg8c/m/dnasHe88AgAJ

**Comment by vasylOstrovskyi** [comment]
To make it transparent would be a much better idea - you will see both the pen shape and the drawing (like in some other online whiteboards)
