### ISSUE TITLE
Upgrade to 2.2.25 Echo Test broken

### ISSUE THREAD

**Issue by stonerl** [bigbluebutton/bigbluebutton#10488]
I upgraded from 2.2.23 to 2.2.25. Now I cannot join the meeting via microphone because the echo test is stalling and no buttons are showing up. I can clearly hear the echo, but I since the buttons don't show up I can't actually join also the close button does not work. Basically it's impossible to hold a meeting.

**To Reproduce**

1. Join a meeting.
2. Join with microphone
3. The echo test opens
4. I hear my voice
5. No buttons to confirm show up

**Expected behavior**
I should be able to confirm the echo test in order to join the meeting

**Actual behavior**
I cannot join the meeting because the echo-test is stalling. 

**Screenshots**

![Screenshot_2020-09-18 BigBlueButton - Startraum](https://user-images.githubusercontent.com/2091312/93583600-5f79ec00-f9a4-11ea-9797-7dfb0eb413c5.png)

**Desktop (please complete the following information):**
 - OS: [Mac 10.15.6]
 - Browser [Firefox, Chrome, Safari]
 - Version [80.0.1, 85.0, 14]

**Comment by irworks** [comment]
This may be the same issue as https://github.com/bigbluebutton/bigbluebutton/issues/10478. Have tried executing `sudo bbb-conf --setip example.com` after the upgrade?

**Comment by stonerl** [comment]
@irworks Yes, that worked I'm closing this one in favor of the other issue.
