### ISSUE TITLE
Earlybirds wait for meeting start forever on 2.3a

### ISSUE THREAD

**Issue by hiroshisuga** [bigbluebutton/bigbluebutton#10481]
**Describe the bug**
When a participant arrives a session earlier than the moderator, the session never starts even if the moderator starts the session.

**To Reproduce**
1. A participants join a session which has not started yet.
2. The moderator starts the session.
3. The session never starts, and in 1-2 minutes BBB asks to join the session again

**Expected behavior**
Session of participant starts immediately after the moderator starts the session.

**Actual behavior**
Does not.

**Desktop (please complete the following information):**
 - OS: Windows10
 - Browser: Chrome (moderator), Chromium Edge (participant)

**Additional context**
All of my two installations have the same problem. However the test server (test23.bigbluebutton.org) does not have. It could be a local problem. 

![93482113-4c323680-f93a-11ea-878a-8367d3754cc2](https://user-images.githubusercontent.com/45039819/93483944-4f2e2680-f93c-11ea-8a3d-0e549e686253.png)

**Comment by farhatahmad** [comment]
What version of Greenlight are you using? This should have been fixed in v2.7.2 through: https://github.com/bigbluebutton/greenlight/pull/2027 and https://github.com/bigbluebutton/greenlight/pull/2043

**Comment by hiroshisuga** [comment]
I am using 2.7.3 for both installations. Should I test 2.7.2?

**Comment by hiroshisuga** [comment]
I reboot the servers and both of them are working as expected. Strange....
Thanks anyway @farhatahmad !

**Comment by matiasilva** [comment]
Should this be closed?
