### ISSUE TITLE
Crackling Sound with Bluetooth Headsets and missing device names in Firefox

### ISSUE THREAD

**Issue by Dimitrie23** [bigbluebutton/bigbluebutton#10490]
**Describe the bug**
We are experiencing crackling sound when using bluetooth headsets only when we use firefox. This is also happening on the demo1.bigbluebutton.org. This issue is only happening with firefox. With the new Microsoft Edge everything works fine. Sadly due to privacy concerns the Edge can't be used here for our users. 

**To Reproduce**
1. Use Firefox 
2. Open a Session

**Expected behavior**
Clear sound and names for the input and output devices.

**Actual behavior**
Crackling sound when using Bluetooth Headsets (PLT Voyager Legend/Aukey EP-T10). No appropriate device name is shown when using the echo test and declining the success. The crackling seems to get worse with time. That might hint a sync issue? Only "audioinput-0"/"audioinput-1" and "no soundoutput found" are shown. 

**Screenshots**

![bug-nodevicenames](https://user-images.githubusercontent.com/68272956/93618657-dda3b600-f9d7-11ea-9496-68bdeb1d24f3.png)

**BBB version (optional):**
BigBlueButton continually evolves. Providing the version/build helps us to pinpoint when an issue was introduced.
Example:
$ sudo bbb-conf --check | grep BigBlueButton

BigBlueButton Server 2.2.5 (2152)

Freshly installed with bbb-install.sh on a root server.

**Desktop (please complete the following information):**
 - OS:  Windows 10 x64 2004
 - Browser Firefox x64
 - Version 80.0.1 and latest nightly (82.0a)

**Additional context**
Latest firmware of headset and drivers of bluetooth are up to date. Also the audio quality seems lower when using Firefox even with the integrated microphone compared to the chromium-based Egde.

I suppose it is a Firefox related issue and also opened a bug on their bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1665895

Firefox's console does not point to any problems neither does bbb-conf --check.

I tried the new dev version of 2.3 as well with bbb-install.sh script on a fresh ubuntu18.04. Same behaviour.

I have one last idea to use x86 firefox and see if the behaviour changes. I will comment on that.

**Comment by Dimitrie23** [comment]
Nope FF x86 shows the same issue

**Comment by ojdo** [comment]
@Dimitrie23 as mentioned in bugzilla ticket [1665896](https://bugzilla.mozilla.org/show_bug.cgi?id=1665895), at least the issue of crackling sound over bluetooth has been fixed recently and is scheduled for the next (as of 2020-10-23) FF release 83. 

<sub>(I can confirm that the beta release 83.0b3 already no longer makes BigBlueButton crackle for me over Bluetooth. Hooray!)</sub>

**Comment by Dimitrie23** [comment]
Fixed the issue, but an overloaded System can still run into this Problem. But so far it is a FF issue. Therefore I close it here.
