### ISSUE TITLE
Show recording duration and room name in bbb-record --list

### ISSUE THREAD

**Issue by zrav** [bigbluebutton/bigbluebutton#10494]
To ease the managing of recordings on heavily used servers, it would be useful to have the output of bbb-record --list include the duration of the recording and the name of the room it was recorded in. Currently we only have the start time as identification aid, which often is too little to find the correct recording.

**Describe the solution you'd like**
Introduce two new columns in the output of bbb-record --list. One for recording duration, one for the room name of the recording.

**Comment by nicolasbonnet** [comment]
:+1:
