### ISSUE TITLE
save user names

### ISSUE THREAD

**Issue by bilias** [bigbluebutton/bigbluebutton#10498]
bbb 2.2.25 does not always downloads user list.

this does not happen at all meetings but it happens in one that currently has 145 people inside.
It doesn't to anything and does not show any error.

Where can I debug this further. Is there a log about it somewhere?

**Comment by leobr2014** [comment]
Hello,

Save names of participants, cause an error:

Uncaught TypeError: e.lastName is null

Thanks

**Comment by ffdixon** [comment]
We should have that fixed in 2.2.26.  See: https://github.com/bigbluebutton/bigbluebutton/pull/10493

Regards,... Fred

**Comment by leobr2014** [comment]
Hello,

What is the forecast for the release of  2.2.26?

Thanks!

**Comment by ffdixon** [comment]
Soon!

**Comment by antobinary** [comment]
2.2.26 was released opn Sept 25 https://github.com/bigbluebutton/bigbluebutton/releases/tag/v2.2.26
