### ISSUE TITLE
set logoutURL inside meeting

### ISSUE THREAD

**Issue by bilias** [bigbluebutton/bigbluebutton#10506]
It would be nice if a moderator could set the logoutURL inside the meeting.

Maybe the meeting is not functioning as well as it should and you want to redirect to another meeting.
Or maybe you want your users to go in another follow-up meeting or go to a specific URL.

Upon end meeting, or user's logout they are redirected there.

This could be set in Manage Users menu.

**Comment by matiasilva** [comment]
Couldn't you paste the URL in the chat?

**Comment by bilias** [comment]
When you have big meetings, chat is a mess especially with younger people...

Most of them will never see it. The moderator ends the meeting and users are redirected, maybe with an altered notice.

**Comment by ReimarBauer** [comment]
had a similiar discussion in greenlight
https://github.com/bigbluebutton/greenlight/issues/2101

this may be also solved by a change in the line. e.g. you can setup an url on a server where you can change the redirection.

I want to use it to send the users on specific meetings to a klicker url for a simple feedback,  see https://uzh-bf.github.io/klicker-uzh/

**Comment by bilias** [comment]
This is interesting but to my understanding it has to be set in advance, which is not always the case.

**Comment by ReimarBauer** [comment]
with a little effort 
we could now do something like our.server/room.name and have this default redirect to the logout url. 

then we have only to change the redirect of our.server/room.name to a different url

of course setting the url in the UI directly would make it much easier.
