### ISSUE TITLE
html5client doesn't load - Cannot read property 'offsetHeight' of null

### ISSUE THREAD

**Issue by arnaudl** [bigbluebutton/bigbluebutton#10519]
**Describe the bug**
The html5 client sometimes doesn't load and something seems to be looping in the JS code. The behaviour is random (or appears as such, I couldn't determine a pattern). The client will sometimes load fine, and other times keeps stuck on the spinner, with errors messages being sent continuously to the console. Usually a refresh or two will make the client load fine.

**BBB version (optional):**
BigBlueButton Server 2.3.0-dev (1323)
bbb-html5 package : 1:2.3.0-1250

**Desktop (please complete the following information):**
Chrome mac 85.0.4183.121

[chrome-console.log](https://github.com/bigbluebutton/bigbluebutton/files/5275751/chrome-console.log)

**Comment by arnaudl** [comment]
It looks like it might be linked to the locale (fr_FR). If I set the html5client language to english the issue disappears.

**Comment by CamZie** [comment]
Experiencing the same problem here. Is there a way we can continue to use the locale (fr_FR) without any problems?

**Comment by laudeon** [comment]
We have the same issue here but only on Chrome or Vivaldi. If locale is FR_fr, then when joining a room, we have the same error in console. Actually, the error occurred in loop, never ending. But if you reload the page in error, then it works and you can join the room.

On Firefox, even with the FR_fr locale, it works great.

Thanks for the great tool though!

**Comment by basisbit** [comment]
8MB log file, got no time to read all of that and figure out what you might be referring to... please mention the important log content in the isuse description and please also add how to reproduce this for a new default install of bbb.

**Comment by antobinary** [comment]
Sounds like you hit https://github.com/bigbluebutton/bigbluebutton/issues/11056
which was fixed in https://github.com/bigbluebutton/bigbluebutton/pull/11171 (2.3-alpha5)
