### ISSUE TITLE
Cannot call the getMeetingInfo api after moderator click the "End Meeting" option from client.

### ISSUE THREAD

**Issue by Mayurmk** [bigbluebutton/bigbluebutton#10514]
**Describe the bug**
Is there a way to get the **total attendees** and other info like **endTime** who joined in the meeting, when we ends the meeting?. I m using **BBB 2.2.20** version.

**To Reproduce**

**Expected behavior**
getMeetingInfo must return data when meeting ends so that we can save attendeed information.

**Actual behavior**
It returns this error.
 response:
      { returncode: 'FAILED',
        messageKey: 'notFound',
        message: 'We could not find a meeting with that meeting ID' } } 

**Screenshots**

**Additional context**

**Comment by matiasilva** [comment]
It makes sense that you cannot retrieve data for a meeting after it is closed. For metadata about the meeting, you want to parse the `events.xml` file generated, more on this in the docs. Otherwise, you can use BBB webhooks.

**Comment by Mayurmk** [comment]
> It makes sense that you cannot retrieve data for a meeting after it is closed. For metadata about the meeting, you want to parse the `events.xml` file generated, more on this in the docs. Otherwise, you can use BBB webhooks.

**Comment by Mayurmk** [comment]
https://docs.bigbluebutton.org/dev/api.html#end-meeting-callback-url
I already used BBB webhook of **end meeting callback url** to fetch the data when meeting ends.


Can you please share me the **events.xml** doc link what is there in that and what is the procedure to get the metadata?
