### ISSUE TITLE
Problem with android mobile device

### ISSUE THREAD

**Issue by gennosukenokoga** [bigbluebutton/bigbluebutton#10518]
Hi there!
I have some problem when accessing BBB from Moodle with android mobile phone. It won't connect to meeting for a long time. But no problem when connecting with laptop/PC

What i do:
1. Creating Moodle course with BBB.
2. Joining video conference.
3. Load blue background web app (BBB)
4. And stuck here

But when i tested accessing demo.bigbluebutton.org, same device can go to the main meeting interface. Any wrong config with my BBB, server or infrastructure?

Thanks

**Comment by matiasilva** [comment]
Can you please follow the issue template? It had fields for the device model and the server version. Without these details, it's near impossible to know what your problem is.

**Comment by basisbit** [comment]
For support requests, please use the [forum / mailing list](https://groups.google.com/forum/#!forum/bigbluebutton-setup). This issue tracker here is only for BBB development related issues. Sorry.
