### ISSUE TITLE
dial in to breakout rooms 

### ISSUE THREAD

**Issue by lonesomewalker** [bigbluebutton/bigbluebutton#10515]
**Describe the bug**
Dial in to breakout rooms are not possible because no verification (like press # to apply) is done.

**To Reproduce**
1. setup dial in by landline
2. create session
3. create breakout rooms
4. try to dial in

**Expected behavior**
Either an "accept" promt or another dial in PIN should be created.

**Actual behavior**
Only a number is added at the end of the current PIN.

**Comment by basisbit** [comment]
duplicate of #9478
