### ISSUE TITLE
REPORT ABOUT BIG BLUE BUTTON CRON ERROR ON CHAMILO PLUGIN

### ISSUE THREAD

**Issue by EsMapachito** [bigbluebutton/bigbluebutton#10527]
In the BBB input and output control, when we use the cron, it updates correctly the connection and disconnection times, but when we finish the meeting by means of the corresponding option in the open room, what happens is that it updates all the times of the connection closure, of the room that we close and of all the rooms of the previous days, that is to say, of the whole database, and this is a problem, because the access control is lost and with it the functionality that we intend.
The operation should be that the cron is updating the partial abandonment and when the meeting closes the time of abandonment of the last ones remaining in the meeting would be modified.
I imagine that when the plugin runs the update routine with the closing instruction, it does not do the discrimination well and updates the "out_at" field in the whole table and not only in the meeting and the records that are affected.
If we could solve this, the operation would be perfect, since in this way through reports we could extract the connection and disconnection times to a videoconference ("Virtual Class"), for the purpose of attendance audits.

I would be grateful for any help on this line or any other that solves this problem and that escapes my knowledge.

Thanks

**Comment by ffdixon** [comment]
The BigBlueButton project doesn't have any developers working on the Chamilo plugin.  Recommend reaching out to the folks at https://chamilo.org/en/contact/.

**Comment by ywarnier** [comment]
Hi @EsMapachito,
Indeed, that's more of our stuff at Chamilo. Please report it in our issue queue at https://github.com/chamilo/chamilo-lms/issues
