### ISSUE TITLE
Is there a way to upload presentation slide in create meeting call with node.js?

### ISSUE THREAD

**Issue by Mayurmk** [bigbluebutton/bigbluebutton#10520]
<!--PLEASE DO NOT FILE ISSUES FOR GENERAL SUPPORT QUESTIONS.
Is there any api from which we can upload the pre-uploading slide with node.js.

**Expected behavior**
Want to display the desired slides when create meeting api will call.

**Actual behavior**
Didn't find any proper documentation/url to upload it when create api call.

**Additional context**

**Comment by Mayurmk** [comment]
If yes then Please provide the url/doc/code.

**Comment by matiasilva** [comment]
The docs are here: https://docs.bigbluebutton.org/dev/api.html. There is no official node SDK but this community sourced one exists: https://www.npmjs.com/package/bigbluebutton-js. You need to implement the presentation aspect according to what the API expects.
