### ISSUE TITLE
timer / BOR-signals / individual audio channel

### ISSUE THREAD

**Issue by dschudi** [bigbluebutton/bigbluebutton#10526]
Hi, 
I was very surprised to see this: https://elos.vc/site/en - a perfect copy of BBB in green. 
BUT Elos has 2 useful extra features: 
- a very small but useful timer for the main room (an additional sound signal at the end is missing...)
- the moderator can open an individual audio channel - a personal breakout-room - to participants (indiv. coaching)

That would be nice in BBB too!

AND some kind of signal (flag, sound) for the participants in BOR, that reaches the main room as call for help / plz visit us.

Thank you!
Judit

**Comment by pedrobmarin** [comment]
I'm sure Elos has more useful features than that!

**Comment by dschudi** [comment]
yep - but the other features are the same as in BBB - its a complete copy of BBB. 
I should add "has to EXTRA features" compared to BBB.

**Comment by iSamof** [comment]
@dschudi - BBB is an open source projects. Everyone can use it, contribute to the main project or create custom additions - checkout the BBB license. If I am not mistaken, Elos's developers and parent company are a great long term contributor to BBB  :-)

**Comment by pedrobmarin** [comment]
At least 19 out of 123 bbb's contributors developers came to this project through mconf/elos.

**Comment by dschudi** [comment]
"NIX FÜR UNGUT!" - The reason for my post was asking to ADD this features to BBB.

**Comment by pedrobmarin** [comment]
"MEÇA SUAS PALAVRAS, PARÇA" - Well, now that you edited your first post may sound like that but originally just sounded you were also trying to help catch some criminals.

Both bigbluebutton and elos are projects with their own agenda. Bigbluebutton has an extra responsibility with it's open source community so it has to measure what is reasonable to maintain. As a product _per se_, both are also diffferent with different design ideals so it's not so simple to just add things up.

**Comment by dschudi** [comment]
no, it wasnt my intention. I was simply wondering. Thanx for explaining the relations between elos and bbb.

**Comment by dschudi** [comment]
Thanks, I´ll edit the issue.
Judit


[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
09/25/20,
07:42:25 PM

Am Fr., 25. Sept. 2020 um 16:00 Uhr schrieb Felipe Cecagno <
notifications@github.com>:
