### ISSUE TITLE
Multiples tabs are opened when you try to join private breakout rooms recently created

### ISSUE THREAD

**Issue by aguerson** [bigbluebutton/bigbluebutton#10528]
BBB version 2.2.25

To reproduce
Create private breakout rooms
Try to join one
Multiple tabs is opened pointed to this private breakout room

With last stable version of firefox...

It's random, not all the time...

Strange ?

**Comment by ffdixon** [comment]
Can you provide more specific steps using https://demo.bigbluebutton.org/.

**Comment by iam-TJ** [comment]
I've just noticed this with Firefox 82.0.3 (64-bit) on Xubuntu 20.04. Same occurred with a similar version of Firefox on Apple MacOS BigSur.

When joining the breakout room it opens in a new tab and the parent room remains with the user in it and transmitting audio and video in the parent room and the breakout room.

Greenlight 2.7.1 on BBB 2.2.0

**Comment by mariogasparoni** [comment]
@iam-TJ 
We are looking into this issue you mentioned , could you please provide more steps to reproduce this ? 
Thanks in advance

**Comment by iam-TJ** [comment]
Maybe we can try on our server, using my home room @ https://meet.bhive.community/tj - current access code is 276824 (2020-11-19 15:06 GMT).

As far as I can tell from our experimenting this morning, we start the parent room, enable audio and video there, add some breakout rooms that allow users to join themselves, do not drag user names into room lists initially, and then users join the break-out rooms from the HTML 5 client list.

In all the tests we did, the user's video continued in the parent room Firefox tab, a new tab opened for the breakout room, and the video continued in both parent and break-out room.

**Comment by mariogasparoni** [comment]
Thanks for all this info. Have you noticed if the same happened for audio in all these cases you mentioned ?

**Comment by iam-TJ** [comment]
It seems like this only occurs when creating the breakout rooms immediately after starting a room - not sure of the precise timing window though.

So, we start the room afresh, share audio, start camera, create 2 breakout rooms with default settings but allowing users to join. Then we cancel the option/invite to enter a breakout room immediately and return to the primary room. From there we choose to join a breakout room.

The breakout room opens in a new tab, echo test, enable audio. Enter breakout and enable video sharing.

User shows as present in both parent and breakout rooms and both have live video. Parent room no longer shows the microphone button andAudio button is in "Join Audio" state (dark icon).

**Comment by mariogasparoni** [comment]
Thanks. I can reproduce with the steps you mentioned, but only for video (my webcam remains transmitting in the main room). Will try a couple more times to reproduce the same with audio

**Comment by iam-TJ** [comment]
I'm not 100% confident we had the issue with audio earlier today - was trying to help a novice moderator with the breakout rooms and didn't know what to expect myself, but I seem to recall experiencing audio in both rooms and having to mute one.

In that scenario I had joined the other person's home room and he had promoted me to moderator so that I could create the break-out rooms (I was working it out on-the-go to teach him for a large meeting later!)
