### ISSUE TITLE
change web server

### ISSUE THREAD

**Issue by ashanet** [bigbluebutton/bigbluebutton#10524]
hello every one
my question is : possible change nginx web server with litespeed ? if it possible please say how?

**Comment by ffdixon** [comment]
We're pretty happy with nginx.  Why would you want to change it to lightspeed?

**Comment by ashanet** [comment]
Yes nginx is very good but my server is very busy and has 300 online at the same time my server crashes.
I think ... more intelligently can handle requests at high speed. I'm looking to both learn this and run it on my servers.

**Comment by matiasilva** [comment]
300 is nothing for nginx. Your server is likely crashing because of the excess of users.

**Comment by ashanet** [comment]
i have several powerful server 
128 GIG Ram 
48 core cpu 
-
i,m follow a way to learn how can switch between webserver i want get maximum performance .

**Comment by ffdixon** [comment]
There are components of BigBlueButton (i.e. nodejs) that only run on a single core, so you are better to have many smaller servers and front-end them with [scalelite ](https://github.com/blindsidenetworks/scalelite).

There is work underway in BigBlueButton 2.3 to improve BigBlueButton's architecture to handle more meetings on a server.  See #10349.

**Comment by matiasilva** [comment]
Merging with the myriad of other issues about performance and more users.
