### ISSUE TITLE
Cameraprofiles names ignored [2.2.26]

### ISSUE THREAD

**Issue by pbdco** [bigbluebutton/bigbluebutton#10538]
The visible camera profiles names set in settings.yml are ignored, still showing the defaults after bbb-conf --restart.

`/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml`

BBB v2.2.26

**Comment by KDSBrowne** [comment]
The camera profile names set in `settings.yml` only get displayed if it's corresponding localized label doesn't exist.

settings.yml:
 `     - id: low
        name: Low
        default: false
        bitrate: 100`

en.json:
`"app.videoPreview.quality.low": "Low quality",`

The `name: ` value is acting more like a fallback.

**Comment by matiasilva** [comment]
A workaround then for @pbdco would be to hide all the default profiles and write your own.

**Comment by pbdco** [comment]
> The camera profile names set in `settings.yml` only get displayed if it's corresponding localized label doesn't exist.
> 
> settings.yml:
> ` - id: low name: Low default: false bitrate: 100`
> 
> en.json:
> `"app.videoPreview.quality.low": "Low quality",`
> 
> The `name: ` value is acting more like a fallback.

I renamed them from the language json files and it works. Thanks

For anyone looking for this in the future:

Check if your language file ( /usr/share/meteor/bundle/programs/server/assets/app/locales/XX.json ) has all the app.videoPreview.quality. -hd-medium-low-high strings. If not, I suggest you to also modify the en.json file with the translated / customized string as well.

Regards
