### ISSUE TITLE
After installing APIs for demo, after clicking Join, says I need to install HTML5 client, and Is already installed. 

### ISSUE THREAD

**Issue by yoa0102** [bigbluebutton/bigbluebutton#10537]
Hi, I need some help with this issue: 

Every time I try to access my domain name assigned for my BBB server and type my name and then click on join: 

It shows really quick HTML5 client needs to be installed to use this API and then the page does not load at all. 

![image](https://user-images.githubusercontent.com/19862724/94376109-6d3b1a00-00e6-11eb-8e91-4c59a490a0c0.png)

Appreciate any help on this.

**Comment by matiasilva** [comment]
Hi, thanks for posting. As this issue tracker is reserved exclusively for development and bug fixes, could you post your support query in the mailing lists: https://docs.bigbluebutton.org/2.2/getting-help.html#help-installing-or-running-bigbluebutton

**Comment by ffdixon** [comment]
You'll find the text in `/var/lib/tomcat7/webapps/demo/demoHTML5.jsp`.  Matias is right -- we only want to use the issue tracker for issues and features (not for support requests).  See above link.
