### ISSUE TITLE
BBB 2.3-dev: daily cronjob references red5 directories

### ISSUE THREAD

**Issue by odenbach** [bigbluebutton/bigbluebutton#10539]
**Describe the bug**
After a fresh install of BBB 2.3-dev (bbb-config 1:2.3.0-7) /etc/cron.daily contains a cron job bigbluebutton which still references some red5 directories which do not exist any more with 2.3:

 root@torino[cron.daily]# grep red5 bigbluebutton
 # Delete streams in red5 older than N days
        webapp_dir=/usr/share/red5/webapps/$webapp/streams
 find /var/log/red5 -type f -mtime +$log_history -delete

The last line results in daily error cron mails:

/etc/cron.daily/bigbluebutton:
find: '/var/log/red5': No such file or directory

**To Reproduce**
Install BBB 2.3-dev
Wait a day
Read your email

Thanks,

Christopher

**Comment by antobinary** [comment]
Handled as part of https://github.com/bigbluebutton/bigbluebutton/pull/10700 
Thanks for reporting!
