### ISSUE TITLE
Enable recording.

### ISSUE THREAD

**Issue by squid46** [bigbluebutton/bigbluebutton#10535]
Hello.
Please indicate where the default recording resolution is enabled/disabled. Somebody turned it off a long time ago and can't find it now.

**Comment by matiasilva** [comment]
Hello. Please read the documentation: docs.bigbluebutton.org/. If that doesn't help, post in the mailing lists on the "getting help" page.

**Comment by squid46** [comment]
and you think I'm such an idiot... I read all the official documentation for starters - there's nothing there.

**Comment by ffdixon** [comment]
You can enable/disable recording system-wide on your server by changing `disableRecordingDefault` in `/usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties`.  

See https://github.com/bigbluebutton/bigbluebutton/blob/develop/bigbluebutton-web/grails-app/conf/bigbluebutton.properties#L198

**Comment by iSamof** [comment]
Dear @squid46 - Your tone is not appreciated. I say this, not to pick a fight but to indicate from one colleague to another: this is a community where people do their best for each other and treat each other with respect.

And we are a grateful to Matias (@matiasilva ) and the rest of the team for doing this valuable work ... which they do in their own time and without pay.

If you check the issues carefully, you will see Matias **patiently** points colleagues to the 'correct' places for them to get help, multiple times per day. Nobody thinks you are an idiot but you are the exception who has already read the documentation. However, you should also notice Matias included the  "mailing lists on the "getting help" page."  

As Matias regularly points out: this forum is for development and bugs only. Help and support are provided in the Google groups. 

I hope this helps you understand other people's view point.
I wish you success

**Comment by squid46** [comment]
> You can enable/disable recording system-wide on your server by changing `disableRecordingDefault` in `/usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties`.
> 
> See https://github.com/bigbluebutton/bigbluebutton/blob/develop/bigbluebutton-web/grails-app/conf/bigbluebutton.properties#L198

Thank you. This is the right thing to do.
