### ISSUE TITLE
Moderator only message with invite link

### ISSUE THREAD

**Issue by amg-web** [bigbluebutton/bigbluebutton#10546]
Is there a way to enable moderator only message with invite link to be visible by default?

Canvas lms plugin do not have such option and all others too missing this feature.

**Comment by dgidevwcc** [comment]
This is something I am also keen to achieve. Hopefully someone has an answer.

**Comment by amg-web** [comment]
I found the respective code here: https://github.com/bigbluebutton/bigbluebutton/blob/v2.2.x-release/bbb-common-web/src/main/java/org/bigbluebutton/api/domain/Meeting.java

**Comment by matiasilva** [comment]
What do you mean visible by default? The moderator only message is only visible if passed in. If you set a default, it will no longer be unique to each room..

**Comment by amg-web** [comment]
ok. let's do setting to enable it without passing this message by api, because not all can do this.
Canvas Plugin at least can't send this message. 
We need get room id and create link visible to moderator

**Comment by dgidevwcc** [comment]
I think what @amg-web is trying to achieve is much like the greenlight joiner.rb https://github.com/bigbluebutton/greenlight/blob/master/app/controllers/concerns/joiner.rb which sets the moderator message and provides an invite URL
To achieve the same when the meeting is created via the canvas LMS integration.
Is it possible to set the moderator only message as a variable? as per the ruby above?

**Comment by matiasilva** [comment]
How are you going to set it as a default when it needs to vary from room to room? If this is a Canvas integration issue, I suggest you take it up with them in the relevant repository.

**Comment by amg-web** [comment]
I want to have an option to see this invite link wether it was sent via api or not. I don't have possibly to fix it on canvas plugin.

Even can say more the problem with sound if the meeting was started from Canvas is actually canvas side not bbb, but this problem exist many years and nobody fix it. Do shell I wait them fix api call to send moderator only message?

**Comment by matiasilva** [comment]
@amg-web where do you want to see the link? in the bigbluebutton client?

**Comment by amg-web** [comment]
> @amg-web where do you want to see the link? in the bigbluebutton client?

yes, same as if session started by Greenlight

**Comment by matiasilva** [comment]
> I want to have an option to see this invite link wether it was sent via api or not.

Your request seems to suggest a misunderstanding of how BigBlueButton works. The API feeds the client data, so without sending the parameter to the API call, you cannot possibly have the invite link show. Your only option here is to contact those that made the Canvas integration and ask them to implement it.
