### ISSUE TITLE
Max Participants Reached Bug

### ISSUE THREAD

**Issue by soheilrahsaz** [bigbluebutton/bigbluebutton#10545]
**Describe the bug**
BBB is returning "maxParticipantsReached" while there is still more room for people.

**To Reproduce**
I don't know exactly how to reproduce it. It doesn't happen all the time, out of 50 different servers and more than 2500 classes per day, only a couple of them has this problem.
When I use "getMeetingInfo" at the time, it says it has a capacity of 30 and there are 10 attendees inside, but when I try to join, I get the "maxParticipantsReached" error.
I'm using the latest version 2.2.26.

Also, I don't find anything interesting in "bbb-web.log". I don't know what I should be looking for.
Any help will be appreciated.

**Comment by mabras** [comment]
This a known issue: https://github.com/bigbluebutton/bigbluebutton/issues/9078 https://github.com/bigbluebutton/bigbluebutton/issues/8990

The issue is being tracked here: https://github.com/bigbluebutton/bigbluebutton/issues/8510
