### ISSUE TITLE
problem with sharing screen and webcam

### ISSUE THREAD

**Issue by hadibokaei** [bigbluebutton/bigbluebutton#10556]
We are regularly facing problems with sharing screen and webcam. The error code is 2001 Media server is offline.
Everything is ok with bbb-conf --status and bbb-conf --check:

sudo bbb-conf --status
nginx —————————————————► [✔ - active]
freeswitch ————————————► [✔ - active]
redis-server ——————————► [✔ - active]
bbb-apps-akka —————————► [✔ - active]
bbb-transcode-akka ————► [✔ - active]
bbb-fsesl-akka ————————► [✔ - active]
red5 ——————————————————► [✔ - active]
mongod ————————————————► [✔ - active]
bbb-html5 —————————————► [✔ - active]
bbb-webrtc-sfu ————————► [✔ - active]
kurento-media-server ——► [✔ - active]
etherpad ——————————————► [✔ - active]
bbb-web ———————————————► [✔ - active]

but in the bbb-conf --debug this error is logged:
/var/log/bigbluebutton/bbb-web.log:2020-09-30T07:31:26.581+03:30 WARN  i.l.c.protocol.ConnectionWatchdog - Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: /127.0.0.1:6379

When we restart the server through bbb-conf --restart the problem will gone but it came back again in future. We had version 2.2.23, but because of this problem we upgrade to 2.2.26 yesterday but the problem still there.
Any help will be appreciated.

**Comment by matiasilva** [comment]
Hi, as this issue tracker is reserved exclusively for bug reports and feature requests, please post your support query as per the guidelines in the documentation: https://docs.bigbluebutton.org/2.2/getting-help.html thanks.

**Comment by ffdixon** [comment]
Port 6379 is used by redis -- check that the redis server is running and you can connect to it via `redis-cli`.
