### ISSUE TITLE
BigBlueButton - Stress test with bigbluebot using Greenlight

### ISSUE THREAD

**Issue by aguerson** [bigbluebutton/bigbluebutton#10550]
Hi BBB dev teams,

I spent many time to write a kind of HowTo to install BBB Bots to stress test BBB servers.

The installation is documented here 

https://github.com/mconf/bigbluebot/issues/14

Thanks again @pedrobmarin 

I hope it could help some sys admins to test their BBB infrastructure in reals conditions.

The documentation is Greenlight oriented, but I think we could use it for Scalelite or a LTI like Moodle.
Regards,
Aurélien.

**Comment by matiasilva** [comment]
@aguerson Great stuff! Post something in the developer group.

**Comment by aguerson** [comment]
Where ?

**Comment by matiasilva** [comment]
https://groups.google.com/forum/#!forum/bigbluebutton-dev

**Comment by aguerson** [comment]
Do I have to sign to google group to post ? For many reasons, I don't want to see my mail scanned by search engines ( private joke ).
I prefer to use github as source of my works.
But you can post for me ;).
I saw you are a "Collaborator" in BBB repo ^^
@ffdixon @pedrobmarin Does it exist any way to become a french collaborator ?
