### ISSUE TITLE
Mongodb is not running..

### ISSUE THREAD

**Issue by shaikhreza43** [bigbluebutton/bigbluebutton#10559]
● mongod.service - High-performance, schema-free document-oriented database
   Loaded: loaded (/etc/systemd/system/mongod.service; disabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Wed 2020-09-30 11:56:33 UTC; 5s ago
     Docs: https://docs.mongodb.org/manual
  Process: 32257 ExecStart=/usr/bin/mongod --config /usr/share/meteor/bundle/mongo-ramdisk.conf --oplogSize 8 --replSet rs0 --noauth --nojournal (code=exited, status=1/FAILURE)
  Process: 32244 ExecStartPre=/usr/share/meteor/bundle/mongod_start_pre.sh (code=exited, status=0/SUCCESS)
 Main PID: 32257 (code=exited, status=1/FAILURE)

Sep 30 11:56:33 ip-10-0-0-201 systemd[1]: Starting High-performance, schema-free document-oriented database...
Sep 30 11:56:33 ip-10-0-0-201 systemd[1]: Started High-performance, schema-free document-oriented database.
Sep 30 11:56:33 ip-10-0-0-201 systemd[1]: mongod.service: Main process exited, code=exited, status=1/FAILURE
Sep 30 11:56:33 ip-10-0-0-201 systemd[1]: mongod.service: Unit entered failed state.
Sep 30 11:56:33 ip-10-0-0-201 systemd[1]: mongod.service: Failed with result 'exit-code'.

**Comment by shaikhreza43** [comment]
exception in initAndListen: 29 Data directory /data/db not found., terminating

**Comment by matiasilva** [comment]
Hi, is this with 2.2 or with 2.3?

**Comment by shaikhreza43** [comment]
2.2

**Comment by matiasilva** [comment]
Please follow the guidelines for getting help then by asking in the mailing lists: https://docs.bigbluebutton.org/2.2/getting-help.html
