### ISSUE TITLE
Correctly set iceServer in latest sip.js version

### ISSUE THREAD

**Issue by mariogasparoni** [bigbluebutton/bigbluebutton#10569]
**Describe the bug**
We are not able to set iceServers (turn/stun) when using latest sip.js

**To Reproduce**
1. Setup stun/turn servers in bbb-web
2. Changes won't have effect in html5-client

**Expected behavior**
Ice servers should be set in html5's audio-manager

**Actual behavior**
Turn is not working. Once, SIP.js uses stun.l.google.com as default, so Stun actually works now.

**Additional context**
I am working on this at this moment. I already have a patch for this, but i am still testing it.
Thanks to @mabras , who first reported this

**Comment by bigbluemeeting** [comment]
@mariogasparoni Can you please provide a patch to at least know where to make changes?

**Comment by IBROF** [comment]
> Can you please provide a patch, even if it is not tested, to at least know where to make changes?

1+ Yes please

**Comment by mariogasparoni** [comment]
I have updated my repository with the patch i am testing. I already had success using stun/turn on a first server, but i would like to run more tests before sending the PR (this is still a working in progress). Feel free to help testing it also.

**Comment by basisbit** [comment]
Problem was solved by above mentioned PRs in 2.2.x.
