### ISSUE TITLE
stun.freeswitch.org unstable = ICE 1007 error

### ISSUE THREAD

**Issue by STROMANZ** [bigbluebutton/bigbluebutton#10562]
This may be regarded as an issue with stun.freeswitch.org, but it clearly affects a default BBB install!
The response of stun.freeswitch.org (or the lack thereof) results either in a working HTML5 client or an ICE1007 error.

When connecting to BBB and selecting "Microphone" during the question "How would you like to join the audio?".
This results in a ICE 1007 error, caused by the HTML5 client being unable to connect to stun.freeswitch.org.

**Steps I use to debug the behavior:**
1. Open about:webrtc in firefox (this suits my debugging needs)
2. Click start debug mode button on about:webrtc page
2. Open a BBB room (we use Ilias)
3. Select Microphone
4. In case of an ICE 1007 error, refresh the about:webrtc page
5. On the about:webrtc page: Notice the HTML5 client only sends an RFC1918 address
no attempt is made using an internet routable address.

The ICE1007 error only occures when stun.freeswitch is "unavailable".
I test the availability via the "stun" CLI tool, see behavior.

**Expected behavior**
stromanz@i7:~$ stun stun.freeswitch.org
STUN client version 0.97
Primary: Independent Mapping, Independent Filter, preserves ports, no hairpin	
Return value is 0x000013

**Actual behavior**
stromanz@i7:~$ stun stun.freeswitch.org
STUN client version 0.97
Primary: Blocked or could not reach STUN server	
Return value is 0x00001c

**BBB version:**
BigBlueButton Server 2.2.26 (2165)

**Desktop/Mobile**
 - OS: Linux, IOS, Android
 - Browser: [firefox, chrome, safari]
 - Location: Multiple

**I solved this issue via**
vi /usr/share/bbb-web/WEB-INF/classes/spring/turn-stun-servers.xml
```<constructor-arg index="0" value="stun:stun.freeswitch.org"/>```
change to:
```<constructor-arg index="0" value="stun:stun.stunprotocol.org"/>```

followed by a bbb-conf --restart

Another solution would be configuring a stun2 by default in /usr/share/bbb-web/WEB-INF/classes/spring/turn-stun-servers.xml ?
A single (failing) stun server (pool?) could leave a bad first impression for BBB!

**stun.freeswitch.org is never guaranteed to be up and running so use it in production at your own risk.**
source: https://freeswitch.org/confluence/display/FREESWITCH/NAT+Traversal

**Comment by mariogasparoni** [comment]
I have been testing stun/turn these days and , indeed, stun.freeswitch.org seems to be offline very often.
I changed my default stun server to  **stun:stun.l.google.com:19302** and had no ICE/audio issues anymore.

**Comment by lhl102401** [comment]
Hi:
I have the same problem
ICE error 1007 ,But I've already configured my own STUN service .
two servers are tested STUN:  stun xxx.xxx.xxx.xxxx:3478,The return message is "Primary: Open" and "Return value is 0x000001",Microphone video normal
the other two servers are tested STUN:  stun xxx.xxx.xxx.xxxx:3478,The return message is "Primary: Dependent Mapping, preserves ports, will hairpin" and "Return value is 0x000009",The Microphone is wrong, the video is ok
What does 0x000009 mean and Why is two normal and two abnormal in the same environment
Thanks !

**Comment by basisbit** [comment]
since 2.2.30, the administrator will be warned if they are still using `stun.freeswitch.org`. (changed in #10887 )
BBB server operators should [set up and maintain](https://docs.bigbluebutton.org/2.2/setup-turn-server.html) their own STUN+TURN service.
