### ISSUE TITLE
Allow only specific users to be able to join in a meeting room

### ISSUE THREAD

**Issue by omiid-ad** [bigbluebutton/bigbluebutton#10563]
Hi, 
is there any functionality to create rooms and only allow specific users to join that room somehow ?
The problem is, i want to hold a conference and its NOT gonna be free. so only people who payed for it can join that room!
I know i can e-mail the room's invite link for them, but what if a stranger finds the link somehow ?! 

I tried 
`"joining needs moderator Approve"
`
and 
`"Only registered users can join rooms" 
`
but neither could satisfy my problem.

Can you please add a feature to give room's access to specific users ? 
or if this already exists, can someone guide me please ?
Thanks~

**Comment by matiasilva** [comment]
What frontend are you using? This is a task for a frontend.

How do you propose going about this? You didn't follow the issue template, so it's unclear what implementation form this would take.

**Comment by omiid-ad** [comment]
> What frontend are you using? This is a task for a frontend.
> 
> How do you propose going about this? You didn't follow the issue template, so it's unclear what implementation form this would take.

I'm sorry about that !
I'm using the lastest version of `GreenLight` as frontend.

**Comment by omiid-ad** [comment]
> What frontend are you using? This is a task for a frontend.
> 
> How do you propose going about this? You didn't follow the issue template, so it's unclear what implementation form this would take.

I think it can be done just like "Manage Access --> Share Room Acces" functionality.

It shows me a dropdown where i can select users and share room with them (this just allow them to start the room and view room's recordings).

You can add an extra option like "Who can join this room?" , and a dropdown showing all registered and active users  so moderator can select multi users and give them access to join this room via invite link or any other joining method.

**Comment by matiasilva** [comment]
So authentication is based on Greenlight users, that could work. I suggest proposing it in the Greenlight repository: github.com/bigbluebutton/greenlight.
