### ISSUE TITLE
Add time stamp to save users list

### ISSUE THREAD

**Issue by apinos76** [bigbluebutton/bigbluebutton#10560]
**Is your feature request related to a problem? Please describe.**
When an instructor saves the user list, they do not see the time in the user list (though they do see it in the file properties/details).

**Describe the solution you'd like**
Add the time the user list was generated into the list (i.e. something like):
yyyy/mm/dd hh:mm:ss
Adam
Bob
Colin
etc.

**Comment by KDSBrowne** [comment]
Below is the output currently generated by saving the names in a meeting:
```
List of users in meeting Demo Meeting at 9/30/2020:10:19:05 AM
Sorted by first name:
aaa 
bbb 
ccc 
  
Sorted by last name:
aaa 
bbb 
ccc
```
The date / time is displayed at the end of the first line.
