### ISSUE TITLE
PDF Conversion issue for files larger than 12mb

### ISSUE THREAD

**Issue by kwisatz** [bigbluebutton/bigbluebutton#10579]
_Note_: This may be slightly related to #8555

When converting PDF files for pre-uploaded presentations, any PDF files that are larger than 12mb will exhibit the following behavior:

```
2020-10-02T18:49:29.279+02:00 INFO  o.b.p.imp.PresentationFileProcessor -  --analytics-- data={"filename":"airOS_8_UG_V02.pdf","num_pages":56,"logCode":"presentation_conversion_num_pages","authzToken":"preupload-download-authz-token","meetingId":"6c0028ceab386556f9d3cda90586633d3cf86a8a-1601657364118","message":"Presentation conversion number of pages.","podId":"DEFAULT_PRESENTATION_POD","presId":"0a51b04b4419ee220be5604f1c966980b37aad93-1601657364132"}
2020-10-02T18:49:39.279+02:00 INFO  o.b.p.imp.ExternalProcessExecutor - TIMEDOUT excuting : pdfseparate -f 1 -l 1 /var/bigbluebutton/6c0028ceab386556f9d3cda90586633d3cf86a8a-1601657364118/6c0028ceab386556f9d3cda90586633d3cf86a8a-1601657364118/0a51b04b4419ee220be5604f1c966980b37aad93-1601657364132/0a51b04b4419ee220be5604f1c966980b37aad93-1601657364132.pdf /var/bigbluebutton/6c0028ceab386556f9d3cda90586633d3cf86a8a-1601657364118/6c0028ceab386556f9d3cda90586633d3cf86a8a-1601657364118/0a51b04b4419ee220be5604f1c966980b37aad93-1601657364132/extracted-1.pdf
2020-10-02T18:49:39.288+02:00 WARN  o.b.p.imp.ThumbnailCreatorImp -  --analytics-- data={"filename":"airOS_8_UG_V02.pdf","logCode":"create_thumbnails_failed","meetingId":"6c0028ceab386556f9d3cda90586633d3cf86a8a-1601657364118","page":1,"message":"Failed to create thumbnails.","presId":"0a51b04b4419ee220be5604f1c966980b37aad93-1601657364132"}
2020-10-02T18:49:39.288+02:00 INFO  o.b.p.imp.ThumbnailCreatorImp - Copying blank thumbnail for slide 1
```

So for each page/slide display a TIMEDOUT message. _(Note the excuting (sic!) typo here)_
After it has finishing "attempting" to process all pages, it finally ends up having indeed converted them into SVG files. I.e. for each page in the PDF document, an svg file has been created and will be shown in the room.

```bash
root@botany ~ # ls -l /var/bigbluebutton/6c0028ceab386556f9d3cda90586633d3cf86a8a-1601657364118/6c0028ceab386556f9d3cda90586633d3cf86a8a-1601657364118/0a51b04b4419ee220be5604f1c966980b37aad93-1601657364132/svgs/
[…]
-rw-r--r-- 1 bigbluebutton bigbluebutton  108061 Oct  2 18:58 slide56.svg
-rw-r--r-- 1 bigbluebutton bigbluebutton  371428 Oct  2 18:50 slide5.svg
-rw-r--r-- 1 bigbluebutton bigbluebutton  952904 Oct  2 18:50 slide6.svg
-rw-r--r-- 1 bigbluebutton bigbluebutton  464537 Oct  2 18:50 slide7.svg
-rw-r--r-- 1 bigbluebutton bigbluebutton   29957 Oct  2 18:50 slide8.svg
-rw-r--r-- 1 bigbluebutton bigbluebutton 1204239 Oct  2 18:50 slide9.svg
```

Running the pdfseparate command manually also shows that there is no real (?) issue here:

```bash
root@botany ~ # time sudo -u bigbluebutton pdfseparate -f 1 -l 1 /var/bigbluebutton/6c0028ceab386556f9d3cda90586633d3cf86a8a-1601657364118/6c0028ceab386556f9d3cda90586633d3cf86a8a-1601657364118/0a51b04b4419ee220be5604f1c966980b37aad93-1601657364132/0a51b04b4419ee220be5604f1c966980b37aad93-1601657364132.pdf /var/bigbluebutton/6c0028ceab386556f9d3cda90586633d3cf86a8a-1601657364118/6c0028ceab386556f9d3cda90586633d3cf86a8a-1601657364118/0a51b04b4419ee220be5604f1c966980b37aad93-1601657364132/extracted-1.pdf

[…]
Syntax Warning: PDFDoc::markDictionnary: Found recursive dicts
Syntax Warning: PDFDoc::markDictionnary: Found recursive dicts
Syntax Warning: PDFDoc::markDictionnary: Found recursive dicts
[…]

real    0m0.884s
user    0m0.824s
sys     0m0.031s
```

**To Reproduce**
1. Go to greenlight
2. Create a new room
3. Click on "Add a presentation" in the room context-menu
4. Select a PDF file of about 18mb or more
5. Enter the room to start the conversion process

**Expected behavior**
I would expect the conversion of an 18mb file to only take slightly longer than the conversion of a file that has 12mb. I would also not expect to see `TIMEDOUT` messages.

**Actual behavior**
`TIMEDOUT` messages in the logs and it took about 15 minutes to convert the document on an 16 threads, 64gb RAM server.

**Comment by emaalouf** [comment]
I don't think it is a server issue rather than a settings issue, I will investigate on my server and let you know, could you state which version are you using please?

**Comment by kwisatz** [comment]
> I don't think it is a server issue rather than a settings issue, I will investigate on my server and let you know, could you state which version are you using please?

We're using `2.2.0-5` (for the `bigbluebutton` meta-package). As for `greenlight` (if relevant), the container image is `7c7d72bae3d2`.

**Comment by emaalouf** [comment]
I have the 2.2.26 and working on the testing of 2.3-dev I will try to update you when possible!

**Comment by kwisatz** [comment]
> I will try to update you when possible!

Do you mean to say we should update if possible? I installed this according to the docs, wanting to have a stable install. For `Xenial`, 2.2.0 seems to be the only available version.

**Comment by kwisatz** [comment]
Actually, @emaalouf bbb-conf says 2.2.26.

**Comment by GhaziTriki** [comment]
@kwisatz Thank you for filing this issue. In reality the conversion to PDF time depends on a lot of factors. One of the is the number of objects in the page itself. If you can share the PDF that you were trying to convert we do deeper investigation.

**Comment by ali-alhaidary** [comment]
We do have per-defined presentations in BBB plugin for moodle that are bigger than 12 MB (could reach 90MB). Teachers and TAs noticed that if they enter a session and do not click on the selection of (mic or listen only) and just wait for the document to be displayed in background, all goes well, however, if they click on the (mic or listen only) dialog box, the presentation will not be displayed. Our tech team did not inspect log files till now, they just recommended to wait.
