### ISSUE TITLE
getRecordings() API function fails with 404 error if too many recordings exist on a server.

### ISSUE THREAD

**Issue by bigbluemeeting** [bigbluebutton/bigbluebutton#10570]
**Describe the bug**
Timeout on proxy for the BigBlueButton API server in getRecordings() API function if too many recordings.

**To Reproduce**
Have too many recordings on a BigBlueButton server so that it takes more than 30 seconds for it to return a set of XML files for all the recordings on the server.

**Expected behavior**
It should return an XML file.

**Actual behavior**
Returns 404 error because the timeout is reached and when it goes to look for the template of a 500.html file it is not found, and it uses this fact (Nginx does) to return a 404 error.

** Resolution **
Increase timeout on the nginx template for the API to about 120-240 seconds so it returns the file.

**Comment by matiasilva** [comment]
If you can, please submit a PR.

**Comment by GhaziTriki** [comment]
Hi @bigbluemeeting,

The issue you are describing is related to #6541, #10497. If you use a load balancer for BigBlueButton to handle the getRecordings API they will be fetched at a higher speed.

However from a design perspective having pagination for recordings would make it work perfectly. Another solution is to add cache for metadata.xml that can be rebuilt, so we can still rely on reading the files, however we only read the cache to fetch data;

**Comment by bigbluemeeting** [comment]
Would love to provide a PR if someone can tell us where this file is in the repo:

/etc/bigbluebutton/nginx/web.nginx

**Comment by ffdixon** [comment]
That file should be moved into the repo.  Right now, it's in the build system, but our intent is to move it to where it belongs in the repo.  Not sure we'll get this in 2.2, but we'll look at doing it in 2.3-dev.

**Comment by mohammadalijf** [comment]
can someone help me to change timeout in web.ngnix?
```
        location /bigbluebutton {
                proxy_http_version 1.1;
                proxy_read_timeout  300s;
                proxy_send_timeout  300s;
                client_body_timeout 300s;
                send_timeout        300s;

                location /bigbluebutton {
                        proxy_pass         http://127.0.0.1:8090;
                        proxy_redirect     default;
                        proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;

                        # Workaround IE refusal to set cookies in iframe
                        add_header P3P 'CP="No P3P policy available"';
                }
```
this is what i am using but still i would get a timeout for records.

**Comment by GhaziTriki** [comment]
@mohammadalijf It is not a timeout issue. Please take a look at this comment https://github.com/bigbluebutton/bigbluebutton/issues/10570#issuecomment-702025633

**Comment by mohammadalijf** [comment]
@GhaziTriki Although pagination and cache are the best solutions here, It's hard to implement and i don't think these features will be shipped anytime soon. Changing the timeout is a quick fix for now until these features get developed. however, i am not able to change that... i used the config that i posted and still Greenlight gets timeout error in 20 seconds.

**Comment by GhaziTriki** [comment]
@mohammadalijf There is some quick ways to improve the `getRecordings` especially when you are trying to get a lot of records. An intermediary database between the file system and the API can highly improve the performances even without caching and pagination.

On the other hand Greenlight is doing the pagination and filtering after every call and it sadly affects servers or load balancer that have a high number of recordings, it should rely on DataTables JS library to do so.

**Comment by fcecagno** [comment]
There has been some development here: https://github.com/bigbluebutton/bbb-recording-api

The current implementation on bbb-web doesn't scale for a large number of recordings, so I'd suggest to include a limit configured on bigbluebutton.properties to return only the last X recordings (e.g. 1000).
