### ISSUE TITLE
Screenshare with audio not working

### ISSUE THREAD

**Issue by piscu7** [bigbluebutton/bigbluebutton#10575]
i installed bigbluebutton successfully and i screen-share without audio successfully but when i was screen-share with audio not working. help please 

i installed  bbb-install.sh

no nat only ufw firewall

**Describe the bug**

**Installation type**
Did you install manually or did you use the bbb-install script?

**Firewall and IP address type**
Is your server behind a NAT or firewall? Does your BBB server have its own IPv4 addres?

**Console output**
Please include the full console output from the install.

**Additional context**

**Comment by matiasilva** [comment]
That feature is currently not supported by BigBlueButton, that's why it's not working. I suggest visiting the other issues about that and even the PR implementing this.

**Comment by piscu7** [comment]
but this feature worked yestarday but not working today.  Default value is audio=false and then i change audio=true 
![bbb](https://user-images.githubusercontent.com/35420941/94861416-292a7b00-0440-11eb-9436-88e2f4606b1f.png)

**Comment by matiasilva** [comment]
That option isn't supported, it was added preemptively but never got used.

**Comment by matiasilva** [comment]
I don't know what to tell you @piscu7. I've already told you that it was never implemented. Chrome displays that box on screen share, but it's up to the software to do something with the value. You were probably hearing feedback from your microphones and believed that was audio from the screen share. You've already opened this issue, why post in the PR that is *actually solving* what you are trying to achieve????

**Comment by piscu7** [comment]
because when I saw similar messages, I wanted to get their opinion. Since there is no reply to my message in this section..
 thank you for interest

**Comment by piscu7** [comment]
Also, as you said, it cannot be a situation because when i select the share audio option and start screen share, the sharing does not open, but when we tried yesterday, the screen sharing was opened with the sound. Perhaps the ports or permissions are blocking and I opened these topics to understand this ...

**Comment by piscu7** [comment]
Also, as you said, it cannot be a situation because when i select the share audio option and start screen share, the sharing does not open, but when we tried yesterday, the screen sharing was opened with the sound. Perhaps the ports or permissions are blocking and I opened these topics to understand this ...

**Comment by matiasilva** [comment]
@piscu7 That PR is implementing what you want. If the PR is there, it means the solution hasn't been implemented. I'm not sure what kind of behavior you experienced yesterday but I believe it was feedback from the microphones. There is no need to post there, as other users can see this issue. In addition, there's this issue: https://github.com/bigbluebutton/bigbluebutton/issues/8632 where many have already commented.
