### ISSUE TITLE
clickable urls of presented documents (not screen sharing)

### ISSUE THREAD

**Issue by ReimarBauer** [bigbluebutton/bigbluebutton#10576]
**Is your feature request related to a problem? Please describe.**

Currently an uploaded PDF with URLs inside the text, these URLs  are converted to plain text 
They are readable but not clickable.

**Describe the solution you'd like**
A pretty good solution would be the conversion of  the slides could keep urls and make them useable to open on a different target than the bbb screen.

**Describe alternatives you've considered**
Also a good solution could be similar to the poll feature that the urls got extracted and shown somewhere on the screen, clickable.

**Additional context**
It happens sometimes if we have first a tutorial and afterwards a session that a lot wonder why the links are not doing as expected.

**Comment by matiasilva** [comment]
Partially adressed by #10132.

**Comment by hex-m** [comment]
duplicate: https://github.com/bigbluebutton/bigbluebutton/issues/6708

**Comment by matiasilva** [comment]
Thanks @hex-m.
