### ISSUE TITLE
How to change the place of webcam on top of conversations

### ISSUE THREAD

**Issue by cod3r0k** [bigbluebutton/bigbluebutton#10572]
Hi every one, I want to move the webcam on top of the conversation/participants section to see the all part of participant names beside webcam and also the board.

Could you help me how can I do this?

**Comment by matiasilva** [comment]
You need to develop a custom build of the HTML5 client. Please see the guidelines on how to get help https://docs.bigbluebutton.org/2.2/getting-help.html#help-developing-bigbluebutton as this issue tracker is exclusively for feature requests and bugs.
