### ISSUE TITLE
Recording playback in fullscreen

### ISSUE THREAD

**Issue by Bevito** [bigbluebutton/bigbluebutton#10573]
**Describe the bug**
When you watch a recording of a meeting, if you try to watch it in fullscreen, you'll have a blank page.

**To Reproduce**
1. Watch a recording playback of a previous meeting
2. Click on 'Toggle fullscreen mode'
3. See error

**Expected behavior**
Video playback should be in fullscreen mode.

**Actual behavior**
Video is put in fullscreen, but we only see a blank page.

**Screenshots**

**BBB version (optional):**
BigBlueButton Server 2.2.26 (2165)

**Desktop (please complete the following information):**
 - OS: Linux Debian 10, Windows 10 LTSC
 - Browser : Chromium, Firefox
 - Version : 83.0.4103.116 for chromium, 78.3.0esr (64 bits) for Firefox
![bbb](https://user-images.githubusercontent.com/4436403/94840592-ee611c80-0418-11eb-812b-b710ed69af55.png)

If you need any informations, don't hesitate.

Best regards

**Comment by romulusFR** [comment]
I've a similar issue. It looks like the "blank screen" is indeed the presenter's camera which is turned off, so everything is white in he player while in fullscreen. The "switch button" at the bottom right corner does switch camera and presentation in windowed mode, but fullscreen is quite stuborn and keeps showing the camera... so everything is still white

**Comment by GhaziTriki** [comment]
@Bevito, BigBlueButton is transitioning to the recordings playback player in 2.3 https://github.com/bigbluebutton/bbb-playback. It is backward compatible with the previous versions.

**Comment by Bevito** [comment]
Thanks @GhaziTriki I'll give It a try.
