### ISSUE TITLE
BBB 2.3-dev issue to load cameras

### ISSUE THREAD

**Issue by emaalouf** [bigbluebutton/bigbluebutton#10586]
**Describe the bug**
I was trying the new BBB 2.3-dev and I was really impressed with the new features, yet it is very buggy, I will report every single bug so we can fix them.
The new update has a problem with loading the cameras on startup, in other words, it takes around 5-7 minutes to load the camera, and this happens after multiple times of turning the camera on and off, especially if the camera is set to high quality of high definition.

**To Reproduce**
1. Start a session.
2.Send the session to friends.
3.Make sure that the camera enabled setting is set to false
4.Turn on the camera when you are in the conference 
5.It will take a lot of time to show on the other screens

**Expected behavior**
The camera to load by maximum 20 seconds

**Actual behavior**
The camera is loading after 5-7 minutes.
This has been tried around 30 times and every time it is the same issue, especially that we tried fiber optic internet for the host, in multiple attempts.

**Screenshots**
No screenshots, but when the host has the camera on, it doesn't even show that the camera is loading for the other users.

**Desktop (please complete the following information):**
-MacOS Mojave 10.14.6

**Smartphone (please complete the following information):**
-iPhone 8
-Samsung Galaxy 10

**Additional context**
Nothing else.
Thanks

**Comment by jlabonte24** [comment]
I have the same probleme with iphone XR. i have an error 1020. after few minutes the camera load.  User can't view the participant and can't load her camera. I try it on 3 XR phones and it's the same problem.

**Comment by prlanzarin** [comment]
There's been a lot of water under this specific bridge in 2.3 since October 2020.
I'm closing this as stale.
But please feel free to test it in test23.bigbluebutton.org and, if you find an issue, re-open or open a new one.

Thanks for the report and sorry for the delay.

**Comment by PlumedArcher** [comment]
I could not reproduce, neither on Windows (firefox, google chrome), nor on my android phone.
