### ISSUE TITLE
Optional axial camera reflection

### ISSUE THREAD

**Issue by zsolt-beringer** [bigbluebutton/bigbluebutton#10582]
Now there is an axial reflection of the camera. It can be bothersome for some. 

Please consider making it optional.

Driver tweaking can be a user side hack that could work.

All platforms (OS+Browser) are involved. I used [Demo site](https://demo.bigbluebutton.org)

PS: Accidentally hit new issue instead of preview. :-|

**Comment by matiasilva** [comment]
It is optional. Go into the HTML5 client configuration file and switch `mirrorOwnWebcam` to false.
