### ISSUE TITLE
Speaker source setting not used when Microfone source was not changed.

### ISSUE THREAD

**Issue by ArminXG** [bigbluebutton/bigbluebutton#10592]
When the echo test reveals a wrong speaker setting and the user clicks "No" on "Did you hear audio?", a change in
"Speaker source" dialog is not saved if "Microfone source" was correct and is not changed by the user.

**To Reproduce**
Have 2 sound devices available. Start the room with Microfone audio and say "No" after echo test.
Now just change the speaker source and leave microfone source unchanged. Now click "retry".
The echo test will again use the old (default) speaker source.
The speaker source change is accepted only if the microfone source was changed as well
(or at least the dialog for microfone source needs to be changed and reverted).

**Expected behavior**
A change in of just one source setting should be accepted as well.

**BBB version (optional):**
2.2.26 (2165)

**Desktop (please complete the following information):**
 - OS: Windows or Linux
 - Browser Chrome
 - Version 85.0.4183.121

**Comment by mariogasparoni** [comment]
I am actually working on it and i already have a patch for this "correct audio device selection". This should be released together with the port to the latest sip.js version. Sending a PR asap.
Thanks for reporting

**Comment by MAMEK70** [comment]
Not sure if my issue belongs here, or should I open a new issue.
Changing audio devices (switching between internal and external devices) in the middle of a session works seamlessly when using a phone or a tablet (android). However on a windows 10 PC, changing an audio device requires leaving the audio bridge and reconnect again to be able to use the newly selected audio device. In both cases, the navigator used is chrome.

**Comment by ArminXG** [comment]
Thank you. Is fixed since 2.2.27.
