### ISSUE TITLE
Member Listing does not work for higher member numbers

### ISSUE THREAD

**Issue by ubu17** [bigbluebutton/bigbluebutton#10598]
**Describe the bug**
Member Listing (download member list) only works with small number of users, 17 Users works, 19 does not.

**To Reproduce**
Have room with 20+ users
Go to Members (Gear Symbol) -> Save Users List

**Expected behavior**
Textfile is downloaded

**Actual behavior**
Nothing happens

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Firefox

**Comment by ffdixon** [comment]
Which version of BigBlueButton are you reporting this issue on?

**Comment by Davka** [comment]
we have a similar case on 2.2.26

The list of participants in a larger meeting could not be saved.
I thought it was a user problem, but this ticket indicates a technical one

**Comment by ubu17** [comment]
I updated today, will report if issue still exists, i am not exaclty shure which component delivers this function, these are the installed packages as of now:
bigbluebutton                       1:2.2.0-5
bbb-client                             1:2.2.0-40
bbb-html5                             1:2.2.0-1032
bbb-web                               1:2.2.0-138

**Comment by daminebenq** [comment]
This is not anymore reproducible.

**Comment by antobinary** [comment]
Thanks for verifying @daminebenq !
