### ISSUE TITLE
BBB not have any audio in playback, but the audio file is located at /var/bigbluebutton/recording/raw/mid/audio

### ISSUE THREAD

**Issue by cod3r0k** [bigbluebutton/bigbluebutton#10591]
Hi, I want to render again a specific meeting. My playback not have any audio but the audio is located at /var/bigbluebutton/recording/raw/mid/audio

**Comment by matiasilva** [comment]
Please follow the guidelines for getting help: https://docs.bigbluebutton.org/2.2/getting-help.html. Thanks. You have posted multiple times ignoring the issue format. I ask you to please comply to it so others can better help you.

**Comment by cod3r0k** [comment]
**Describe the bug**
When I want to check my playback, I found that it has no audio. But I check the files which located at `/var/bigbluebutton/recording/raw/###meeting_id##/audio` and I found the audio file.

I rebuild it again and it is not resolved yet.

**Expected behavior**
A clear and concise description of what you expected to happen.

**Actual behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, Mac]
 - Browser [e.g. Chrome, Safari]
 - Version [e.g. 22]

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6]
 - OS: [e.g. iOS8.1]
 - Browser [e.g. stock browser, Safari]
 - Version [e.g. 22]

**Additional context**
Add any other context about the problem here.

**Comment by cod3r0k** [comment]
Dear @matiasilva , In the meeting, the audio is OK, but in the playback it was silent. this is an issue, Isn't it?

**Comment by ffdixon** [comment]
Can you post this to bigbluebutton-setup and include the information asked for in  https://docs.bigbluebutton.org/2.2/getting-help.html.

At the moment, we really don't have much to go on (or to try and reproduce the issue).

**Comment by cod3r0k** [comment]
> Can you post this to bigbluebutton-setup and include the information asked for in https://docs.bigbluebutton.org/2.2/getting-help.html.
> 
> At the moment, we really don't have much to go on (or to try and reproduce the issue).

Dear @ffdixon , It was a rare incident that took place. I use recording and playback many times and this is just one time which I see in BBB 2.2.26 last day. The audio file in `/var/bigbluebutton/recording/raw/########/audio/#####.opus` is works well with player which I download it. But the published file which located at `/var/bigbluebutton/published/########/`  is silent

**Comment by cod3r0k** [comment]
> Please follow the guidelines for getting help: https://docs.bigbluebutton.org/2.2/getting-help.html. Thanks. You have posted multiple times ignoring the issue format. I ask you to please comply to it so others can better help you.

@matiasilva @ffdixon 

I should ask whom?

Unfortunately, your request to join the bigbluebutton-users group was denied by a group moderator.
More information about joining a group is available at the Google Groups Help Center.

**Comment by matiasilva** [comment]
You should join the bigbluebutton-setup group and make sure to follow the join instructions to prevent being flagged as spam.

**Comment by lneoj** [comment]
Hi @cod3r0k Did you find a solution to that?

**Comment by pshabanov** [comment]
@matiasilva @ffdixon @cod3r0k
Hello, i have this problem too.

**Comment by hostbbb** [comment]
@pshabanov go to biglbluebutton-setup in google. this is 3yr old issue.   We need more info like version BBB etc, to help you.
Post the details.

**Comment by pshabanov** [comment]
BBB v2.5

bbb-conf --check

BigBlueButton Server 2.5.11 (299)
Kernel version: 5.4.0-136-generic
Distribution: Ubuntu 20.04.5 LTS (64-bit)
Memory: 8148 MB
CPU cores: 4

/etc/bigbluebutton/bbb-web.properties (override for bbb-web)
/usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties (bbb-web)
bigbluebutton.web.serverURL: https://staging-mkk-bbb.o.kg
defaultGuestPolicy: ALWAYS_ACCEPT
svgImagesRequired: true
defaultMeetingLayout: CUSTOM_LAYOUT

/etc/nginx/sites-available/bigbluebutton (nginx)
server_name: staging-mkk-bbb.o.kg
port: 80, [::]:80
port: 443 ssl

/opt/freeswitch/etc/freeswitch/vars.xml (FreeSWITCH)
local_ip_v4: staging-mkk-bbb.o.kg
external_rtp_ip: staging-mkk-bbb.o.kg
external_sip_ip: staging-mkk-bbb.o.kg

/opt/freeswitch/etc/freeswitch/sip_profiles/external.xml (FreeSWITCH)
ext-rtp-ip: $${external_rtp_ip}
ext-sip-ip: $${external_sip_ip}
ws-binding: staging-mkk-bbb.o.kg:5066
wss-binding: staging-mkk-bbb.o.kg:7443

/usr/local/bigbluebutton/core/scripts/bigbluebutton.yml (record and playback)
playback_host: staging-mkk-bbb.o.kg
playback_protocol: https
ffmpeg: 4.2.7-0ubuntu0.1

/usr/share/bigbluebutton/nginx/sip.nginx (sip.nginx)
proxy_pass: 172.27.135.121
protocol: http

/usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml (Kurento SFU)
/etc/bigbluebutton/bbb-webrtc-sfu/production.yml (Kurento SFU - override)
kurento.ip: 172.27.135.121
kurento.url: ws://127.0.0.1:8888/kurento
kurento.sip_ip: 172.27.135.121
recordScreenSharing: true
recordWebcams: true
codec_video_main: VP8
сodec_video_content: VP8

/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml
(HTML5 client)
/etc/bigbluebutton/bbb-html5.yml (HTML5 client config override)
build: 2894
kurentoUrl: wss://staging-mkk-bbb.o.kg/bbb-webrtc-sfu
enableListenOnly: true
sipjsHackViaWs: true

/usr/share/bbb-web/WEB-INF/classes/spring/turn-stun-servers.xml (STUN Server)
stun: stun.l.google.com:19302

# Potential problems described below

# Warning: The setting of staging-mkk-bbb.o.kg for local_ip_v4 in
#
#    /opt/freeswitch/etc/freeswitch/vars.xml
#
# does not match the local IP address (172.27.135.121).
# (This is OK if you've manually changed the values)


Problem only Pixel 3... BBB working good, no errors, no lags. I fixed
error 1006, 1007, 1002, 1107. Now is work fine from ios and android,
mb problem in this device?
Pixel 3
Android 12
Chrome 91.0.44
Selfie camera shoots normally outside the bbb

Or mb camera
пн, 10 апр. 2023 г. в 16:07, Stephen ***@***.***>:

**Comment by hostbbb** [comment]
local_ip_v4: staging-mkk-bbb.o.kg
external_rtp_ip: staging-mkk-bbb.o.kg
external_sip_ip: staging-mkk-bbb.o.kg



these need to be xx.xx.xx.xx IP addresses

 

regards,

Stephen
