### ISSUE TITLE
Arabic keyboards write from right to left on whiteboard

### ISSUE THREAD

**Issue by apinos76** [bigbluebutton/bigbluebutton#10609]
**Is your feature request related to a problem? Please describe.**
When using an Arabic keyboard to enter text on the whiteboard, the text is still written from left to right.

**Describe the solution you'd like**
When using an Arabic keyboard to enter text on the whiteboard, the text is still written from right to left.

This would also apply to Hebrew keyboards as well.

**Describe alternatives you've considered**
None.  Arabic is written from right to left.

**Comment by emaalouf** [comment]
Please state which version are you using?

**Comment by apinos76** [comment]
@emaalouf the most recent version.  Simply, the test boxes do not account for right to left writing.  We have an Arabic customer looking for this feature when they want to write in Arabic

**Comment by antobinary** [comment]
Version where this was reported is BigBlueButton 2.2.26, client build 1032-1034

**Comment by daminebenq** [comment]
I just tried it in both of FF and Chrome, and it's working fine
![Peek 2020-10-09 12-48](https://user-images.githubusercontent.com/5144311/95605138-e9aaf280-0a2e-11eb-850f-9ec39cab8ef7.gif)

**Comment by antobinary** [comment]
@daminebenq Do you need to be in a right-to-left (e.g. Arabic, Hebrew, etc) mode in the client to be able to type in a right-to-left language or the system picks up what you're inputting?

**Comment by daminebenq** [comment]
@antobinary RTL depends to the browser default language or the Text Entry Language selected, or the app selected language

**Comment by daminebenq** [comment]
text inputs get automatically in RTL mode when the Text Entry Language selected is an RTL language. and what we have now in BBB is a bug.
@apinos76 sorry I misunderstood what you described in the issue in the beginning, but yes, your customer is right and it's a real bug.

**Comment by Jossef-767** [comment]
the RTL displayed text should be aligned to the right. 
RTL text is currently jumping to left align when you finish typing,

**Comment by antobinary** [comment]
@pedrobmarin which issue was this merged into?

**Comment by pedrobmarin** [comment]
https://github.com/bigbluebutton/bigbluebutton/issues/10026
