### ISSUE TITLE
White board issue

### ISSUE THREAD

**Issue by Prasanna-NatarajanVR** [bigbluebutton/bigbluebutton#10605]
**Is your feature request related to a problem? Please describe.**
As our teachers are using the white board for writing (using the writing pad) as we are getting a problem that the whiteboard
is trying to auto correct and making rounds like squares(so we can't write much)

**Describe the solution you'd like**
Fix the white board

**Additional context**

![image](https://user-images.githubusercontent.com/64462247/95319329-5d28f480-08b5-11eb-9b7c-89062987fed3.png)

![image](https://user-images.githubusercontent.com/64462247/95319503-9bbeaf00-08b5-11eb-8de5-25e716665608.png)

**Comment by ffdixon** [comment]
Can you have your teachers test writing on the whiteboard at this site: https://dev23.bigbluebutton.org/.  This is running a build of the next version of BigBlueButton (2.3-dev) where we've done some whiteboard improvements.

**Comment by Prasanna-NatarajanVR** [comment]
Hey!!! Thanks
