### ISSUE TITLE
bigbluebutton large scale users

### ISSUE THREAD

**Issue by hmahdi-s** [bigbluebutton/bigbluebutton#10600]
I want to get some information about large scale experience.
If anyone has the experience please share it here.
my questions are there:
1- how many active users at moment?
2- what is your server resource? metal server or vm?  CPU RAM etc
3- what is your challenge in large number user? 
4- Do you change any default configuration to improve performance?

**Comment by matiasilva** [comment]
Hi, thanks for your questions. You will find all the answers to them in the developer and setup mailing lists where many have asked them: https://bigbluebutton.org/support/community/
