### ISSUE TITLE
improve turn documentation

### ISSUE THREAD

**Issue by fireba11** [bigbluebutton/bigbluebutton#10616]
Documentation for setting up a TURN server at https://docs.bigbluebutton.org/2.2/setup-turn-server.html has example command to use certbot with http challenge, and could do with a note to open port 80 for that ;-)

**Comment by matiasilva** [comment]
Would you mind submitting a PR with your proposed changes? Thanks!

**Comment by fireba11** [comment]
Sure, is the documentation somewhere i can do a pull request?
Haven't found it yet ;-)

**Comment by matiasilva** [comment]
github.com/bigbluebutton/bigbluebutton.github.io

Looking forward to it!

**Comment by fireba11** [comment]
Thx, will make a pull request against that with some improvements :-)
