### ISSUE TITLE
Studio URLS not accepted with more than three parts of the domain

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#10620]
**Describe the bug**
The following Studio URL is playable in BigBlueButton

  https://xxx.instructuremedia.com/embed/d3ae4950-5348-41a6-be6d-dbdc3340771c

but not this URL with more parts in the domain.

  https://xxx.uswest-2.instructuremedia.com/embed/d3ae4950-5348-41a6-be6d-dbdc3340771c

**Comment by lfzawacki** [comment]
Fixed in https://github.com/bigbluebutton/bigbluebutton/commit/7efcd3b87e6b975266c58f9168e74f46533bc916
