### ISSUE TITLE
when having text area open, drop down in settings doesn't expand

### ISSUE THREAD

**Issue by daminebenq** [bigbluebutton/bigbluebutton#10623]
This bug is **2.2** and **2.3** reproduceable.

**To reproduce it:**
1) go to a meeting room
2) as presenter, click on the text area tool
3) leave the text area open 
4) click on Options > Settings
5) click on the languages drop down

**PS:** no console errors, it's just about the focus is kept on the open text area

**Idea to solve it:**
add an auto drop of the focus, once a click is made out of the whiteboard
 
**Visualization of how to reproduce this bug:**
![azeazeazeazeazeazeazeaze](https://user-images.githubusercontent.com/5144311/95605282-1ced8180-0a2f-11eb-8719-bd8fa80adca8.gif)

**Comment by antobinary** [comment]
Resolved in https://github.com/bigbluebutton/bigbluebutton/pull/11207 (in both 2.2 and 2.3)
