### ISSUE TITLE
live captions via dictation not displaying

### ISSUE THREAD

**Issue by tliebetanz** [bigbluebutton/bigbluebutton#10637]
PR #9357 fixed a bug with live captions via dictation not displaying in v2.2.9, I have the same issue in v2.2.26.

**Comment by tliebetanz** [comment]
Fixed in v2.2.29.

**Comment by FreeScholar** [comment]
I am having the same issue - There is no button for Live Dictation and the UI does not allow me to select the language for captions.
![closedCaptionsBBBnoSelectLang](https://user-images.githubusercontent.com/1201170/111807921-d9365800-88a9-11eb-9aa5-a43881148500.png)

**Comment by FreeScholar** [comment]
![closedCaptionsBBB](https://user-images.githubusercontent.com/1201170/111807986-ef441880-88a9-11eb-9764-a57d45958ca3.png)
