### ISSUE TITLE
Default Presentation can't be deactivated

### ISSUE THREAD

**Issue by erisd** [bigbluebutton/bigbluebutton#10635]
The Default Presentation can only with a hack deactivated in the Web Interface - without a Reasen.

1. Create and join a conference
2. Click on "Actions" and "Upload a Presentation" (which is IMHO wrong, because you manage Presentations here)
3. The checkbox behind the default Presentation is deactivated

The Hack to disable a default Presentation:
1. Create and join a conference
2. Click on "Actions" and "Upload a Presentation"
3. Upload a random presentation
4. Click on "Actions" and "Upload a Presentation"
5. Delete the new Presentation and confirm

The default presentation ist now deactivated and we have a Clean Video Conference Window. Every new Conference Member now has a "Jitsi like" View, without Presentations. We often need that and I don't see a Reason why this should be deactivated.

**Comment by matiasilva** [comment]
Make sure to read the documentation, you can disable the presentation area on join: https://docs.bigbluebutton.org/2.2/customize.html#layout-parameters and in the global `settings.yml`. If you think that "upload a presentation" is wrong, please open a another issue to request a feature enhancement.

**Comment by AdrianMaslowskiAMTL** [comment]
I am doing it in a brutal way:
sudo rm /var/www/bigbluebutton-default/default.pdf
sudo rm /var/www/bigbluebutton-default/default.pptx

:)

**Comment by erisd** [comment]
> Make sure to read the documentation, you can disable the presentation area on join: https://docs.bigbluebutton.org/2.2/customize.html#layout-parameters and in the global `settings.yml`. If you think that "upload a presentation" is wrong, please open a another issue to request a feature enhancement.

Yeah, I know that there are several ways to remove it for the complete BBB instance. But thats not what I'm talking about - I just want to give the User the choice. A default presentation makes sense (we replaced it with an short BBB manual), but I don't see an reason to enforce a presentation...

**Comment by matiasilva** [comment]
The user has a choice, they can click the presentation button on the lower left, which minimizes the presentation area.

**Comment by erisd** [comment]
I think a Moderator should be able to lead the guests through a conference. And that means that the guests see a presentation only when the moderator wants that. That has nothing to do with the possibility to minimize the presentation.

Where do you see a problem when I have the possibility do deactivate the presentation? I can upload and change the  presentation and I even can deactivate it with an workaround. And why do you try to discuss my problem away? If you think it would be an anti feature, just say "no because of xyz" and stop to rumble around.

**Comment by bigbluemeeting** [comment]
> I think a Moderator should be able to lead the guests through a conference. And that means that the guests see a presentation only when the moderator wants that. That has nothing to do with the possibility to minimize the presentation.
> 
> Where do you see a problem when I have the possibility do deactivate the presentation? I can upload and change the presentation and I even can deactivate it with an workaround. And why do you try to discuss my problem away? If you think it would be an anti feature, just say "no because of xyz" and stop to rumble around.

Moderator can do this with an additional setting that synchronizes moderator's actions with the user's. Not entirely sure atm where it is located but it does exist if you search for it.

**Comment by matiasilva** [comment]
> 
> I think a Moderator should be able to lead the guests through a conference. And that means that the guests see a presentation only when the moderator wants that. That has nothing to do with the possibility to minimize the presentation.

So the functionality you're looking for is for the moderator's actions to be synchronized across all participants' windows. That was not clear at all from your original post.

> Where do you see a problem when I have the possibility do deactivate the presentation? I can upload and change the presentation and I even can deactivate it with an workaround. And why do you try to discuss my problem away? If you think it would be an anti feature, just say "no because of xyz" and stop to rumble around.

I'm not really sure what you're trying to say here -- it's always useful to gather more information as the true purpose of your issue was only revealed in your last comment. I and others gave solutions to the problem you presented. Your proposed solution is thus a duplicate of #7987.

**Comment by erisd** [comment]
> > I think a Moderator should be able to lead the guests through a conference. And that means that the guests see a presentation only when the moderator wants that. That has nothing to do with the possibility to minimize the presentation.
> 
> So the functionality you're looking for is for the moderator's actions to be synchronized across all participants' windows. That was not clear at all from your original post.

No, that would be a alternative but thats not what I'm looking for.
I think it would be useful if bbb-html5 doesn't require an presentation. Thats much easier to realize - instead of requiring an presentation, a presentation can be optional but default enabled.
Nothing changes for our users, but if moderators like they can deactivate the default presentation in the conference.

**Comment by github-luckow-org** [comment]
If you change default.pdf in something else in beans.presentationService.defaultUploadedPresentation=${bigbluebutton.web.serverURL}/default.pdf located in /usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties a presenter can delete the former default.pdf. That's works perfect for a "kind of" default everytime loaded if a room starts. But after the room starts you can delete the whole default presentation..

**Comment by erisd** [comment]
uh, nice hack - thats helpful - I will try that, thanks a lot!
(sounds like the "can the mod delete this"  decision is taken by the filename...)

**Comment by matiasilva** [comment]
I'm still not aware what the point of this issue and why it can't be addressed with existing tools. I'm tempted to close it unless anyone has further words?

**Comment by erisd** [comment]
Okay, lets say I have a BBB Instance and want to prepare the Meetingroom. I just want to talk with the people, no Presentation. As a Moderator, I want to disable the Presentation. The Guest will join the Meetingroom, activate their camera and have a conference - without the need to minimize the presentation. I often have conferences with "not so computer people" - they even don't have the idea that this picture in the middle of the screen is something that they could "make that it goes away".
When I deactivate the presentation, they join the room and its fine.
On the other hand I have meetings on the same Server where we talk with kids. Our default presentation is a manual which explains in a minimal way what you can do during a meeting. The kids try everything and without a question they realize what they can do with the tools. Its great that they have the presentation and that nobody has to activate it first.

The hack from github-luckow-org works great. I renamed the default presentation to bbbmanual.pdf and chaged the path in the config file. It works! Looks like there is a hardcoded option in BBB that says "when the presentations name is default.pdf and the number of presentations in the room is under 2 then the delete button is disabled".

**Comment by matiasilva** [comment]
Okay -- I understand now. Why can't you implement the userdata parameter that hides the presentation area by default on join?

**Comment by erisd** [comment]
We have a BBB Cluster for about 2000 Members with a mix of Greenlight, Nextcloud and Moodle Frontends. I don't want to change the default - and I want to give the moderator the choice.

**Comment by matiasilva** [comment]
The userdata parameter is exactly there to give the moderator a choice. The settings.yml file sets global defaults and the userdata parameters can override those on each API call, so you customize it even on the viewer level.

**Comment by herzkerl** [comment]
> Moderator can do this with an additional setting that synchronizes moderator's actions with the user's. Not entirely sure atm where it is located but it does exist if you search for it.

@bigbluemeeting Sorry for replying to a closed issue, but could you maybe point me in the right direction? Searched a bit but haven't found it yet. Thanks!

**Comment by MartinH-open** [comment]
This issue was closed.
But it is still unclear what the solution/workaround for the user (as a room owner / not a BBB Admin) is?
Please add some hints how to overcome this issue from that perspective.

**Comment by lachlanphillips** [comment]
This definitely seems like an overly complicated problem for what should be basic functionality.

1) There should be a "disableDefaultPresentation = true" option
2) There should be a "minimumPresentations = 0" option

Inexplicably, even if you delete the default.pdf, as soon as you add a presentation it cannot be deleted at all. I can think of no reason to prevent users from deleting the 0th presentation.

**Comment by easy-bios** [comment]
Just in case someone is still searching the solution:

Add
`beans.presentationService.defaultUploadedPresentation=0`
to file
`/etc/bigbluebutton/bbb-web.properties`

The file may be necessary to be created first if you have no custom configuration jet.

_Works since version 2.6_

**Comment by da5nsy** [comment]
Here's my user experience in case it is useful as a case study:

- I'm a new user on socialcoop.meet.coop
- I'm just tinkering around getting to know the platform.
- I start my home room.
- "Huh, there's a default presentation in here. How do I remove that so that when I invite other folks to a call they don't see it?"
- Several minutes later after starting a new room to test whether it is just the behaviour of the "Home Room", uploading a new presentation and then deleting it, etc etc, and then finding and reading through this issue...
- "Huh, I **can't**. There is literally no way for me to start a room without a presentation, or to remove the default presentation" (aside from contacting the server admin and getting them to modify the custom config)

My expectations as a naive new user:
- There would be a way to remove a (default) presentation, from within the room itself and/or from the Home screen.
   - One potential way that I might expect to be able to do this from the Home screen: on the home screen, on the three-dot menu for the room, instead of "Add presentation" the button might read "Manage presentation" and the panel which comes up would show you what presentation was loaded, with a little delete button next to it which would remove it.
   - One potential way that I might expect to be able to do this from within the room: , alongside the "Hide presentation" button, I would expect to see an "x"/"Remove presentation" button (visible only to room owner).
- When creating a new room there would be a toggle which asks whether you want to include the default presentation, and if toggled off there would be no presentation.
