### ISSUE TITLE
allowModsToUnmuteUsers=true not working

### ISSUE THREAD

**Issue by pedped** [bigbluebutton/bigbluebutton#10630]
Hi, I am trying to get moderator the ability to unmute users, I have used the 

**allowModsToUnmuteUsers=true** 
in
**/usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties**

and restarted the big blue button, but it does not work and there is no feature or button to unmute user, just mute and take presenter or leave user...

I am using latest version of BBB, 2.2.26

**Comment by bigbluemeeting** [comment]
Mods can not unmute users, it's a privacy concern so this ability was removed from BBB 2.2

**Comment by matiasilva** [comment]
Oh? I'm not sure if I'm misremembering, but I was able to unmute users in one of my BBB installations.

**Comment by bigbluemeeting** [comment]
https://groups.google.com/g/bigbluebutton-dev/c/MO3HvVohG7k

Chad Pilkey
Jul 9, 2019, 11:26:03 PM
to BigBlueButton-dev
Do you have unmuting turned on? What value do you have for "allowModsToUnmuteUsers" in "/usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties"? In 2.2 we disabled the ability for moderators to unmute other people for privacy reasons.

**Comment by pedrobmarin** [comment]
It's disabled by default. It wasn't removed.

**Comment by matiasilva** [comment]
@pedped Any update on your side?

**Comment by pedped** [comment]
Yes it works like  a charm. you have to enable unmuting in the create\join request....

**Comment by matiasilva** [comment]
Excellent!

**Comment by elloe** [comment]
Please do not remove this option - as a Blind Society in the UK using BBB to allow our visually impaired and blind service users to communicate this is a very important feature that allows remote moderators to enable/disable microphones on behalf of those users who many not be able to easily locate the control in the client.
