### ISSUE TITLE
Possiblity to deactivate the echo test by default

### ISSUE THREAD

**Issue by Gecko-Gihub** [bigbluebutton/bigbluebutton#10639]
**Is your feature request related to a problem? Please describe.**
We didn't found any possibility to deactivate the echo test by default. There is no serverside possibility and no function at the frontend   

**Describe the solution you'd like**
We would like to deactivate the echo test for all meetings by default.

**Comment by bigbluemeeting** [comment]
It already exists in the config for the HTML5 client, but causes plenty of other issues so beware.

**Comment by bigbluemeeting** [comment]
/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml 

public.app.skipCheck: true

**Comment by matiasilva** [comment]
Thanks @bigbluemeeting
