### ISSUE TITLE
admin can't unmute a dialin user

### ISSUE THREAD

**Issue by fireba11** [bigbluebutton/bigbluebutton#10648]
If you mute a dialin user as admin you can't unmute him anymore :-(

bbb 2.2.25
grenlight 2.7.4

**Comment by NerdyProjects** [comment]
It should not matter if the person is a dialin user or not: There is a configuration option to allow moderators to unmute users. It is a privacy concern, so it might be disabled on most setups.

A dialin user can mute/unmute themselves by pressing the `0` key.

**Comment by fireba11** [comment]
That was what i expected too. My testers reported there is simply no such button with dialin while it worked fine with browser users.

**Comment by NerdyProjects** [comment]
So you say you can unmute non-dialin users but not dialin users?

If that is right, there should be a bug. Unfortunately, I cannot test this right now as I don't have an installation at hand, where moderators are allowed to unmute users. I tested the muting part which works equally for dialin/non-dialin users.

Hm, I spend 15 minutes now looking into it:
https://github.com/bigbluebutton/bigbluebutton/blob/6f60324a4e4e860038404591b9b27516f6fec576/bigbluebutton-html5/imports/ui/components/user-list/service.js#L348 here it is figured out what the allowed actions are - there is no reason, this should be different for a dial in user. So I would ask you to triple-check, if unmuting regular other users, e.g. NOT YOURSELF, is enabled and working :-)

**Comment by fireba11** [comment]
Thank you for looking into it, i'll verify myself and will report back.

**Comment by Daedalus3** [comment]
Issue has been reported in #9890.

**Comment by matiasilva** [comment]
Thanks, closing.
