### ISSUE TITLE
Screen Sharing does not function

### ISSUE THREAD

**Issue by paulraper** [bigbluebutton/bigbluebutton#10642]
When you share the screen with other users, the screen shows only on the hosts page of BBB. The other participants see only two arrows rotating round and round.

**To Reproduce**
Login to BBB
Share the screen with another person.

**Expected behavior**
I would expect my course participants to see the screen I am trying to share.

**Actual behavior**
The participants see only two arrows chasing each other round and round.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, Mac]
 - Browser Firefox

**Smartphone (please complete the following information):**
 - Device: LapTop
 - OS: Windows 10
 - Browser [e.g. stock browser, Safari]
 - Version 70.0b4

**Additional context**

**Comment by matiasilva** [comment]
What version of BigBlueButton is this? Always useful to include that.

**Comment by paulraper** [comment]
2.3Alpha

**Comment by basisbit** [comment]
For support requests, please use the [forum / mailing list](https://groups.google.com/forum/#!forum/bigbluebutton-setup). This issue tracker here is only for BBB development related issues. Sorry.
