### ISSUE TITLE
breakout rooms + dialin is broken

### ISSUE THREAD

**Issue by fireba11** [bigbluebutton/bigbluebutton#10645]
Out testers tried to use dialin with breakout rooms and the combination seems completely broken.

* if you create a breakout room the dialins don't show up in the user selection
* dialin into a breakout room (the pin gets extended by 1) gives a voice message "negativ 1" and hangs up on you -_-

**Additional context**
bbb v2.2.25
greenlight 2.7.4

**Comment by iam-TJ** [comment]
Confirmed here too, unable to telephone into break out rooms - PIN appears to be accepted then we hear "negative 1". HOWEVER, the caller IS connected in the main room and can talk there - the call isn't disconnected.

We also noticed there is no way as moderator to invite a telephone caller to a breakout room - they do not appear in the list of users when creating an invite.

**Comment by antobinary** [comment]
Merging into https://github.com/bigbluebutton/bigbluebutton/issues/9478
