### ISSUE TITLE
Guest wait page should be localized

### ISSUE THREAD

**Issue by nicolopez77** [bigbluebutton/bigbluebutton#10649]
When a user is waiting for moderator approval, it shows a page in English (not localized) with the message "Please wait for a moderator to approve you joining the meeting.". This message should be localized.

**To Reproduce**
1. Open a meeting that requires moderator approval. 
2. Another user tries to enter the meeting and the message "Please wait for a moderator to approve you joining the meeting." is being shown always in English (not localized).

**Expected behavior**
The message should be localized

**Actual behavior**
The message is only in English

**Comment by matiasilva** [comment]
Specific line @nicolopez77 is referring to: https://github.com/bigbluebutton/bigbluebutton/blob/f60ec758da5a954e201f38566fc3245338254e9f/bigbluebutton-html5/private/static/guest-wait/guest-wait.html#L151

**Comment by jgribonvald** [comment]
:+1: for localization on this page.
