### ISSUE TITLE
restore delete file

### ISSUE THREAD

**Issue by ashanet** [bigbluebutton/bigbluebutton#10650]
hello 
I accidentally deleted all my conference files with the command 
bbb-record --deleteall
 Is there a way to recover deleted files?

**Comment by matiasilva** [comment]
No, unless you maintain some system backup then they are gone. Notice the permanent `rm -f` operations here: https://github.com/bigbluebutton/bigbluebutton/blob/develop/bigbluebutton-config/bin/bbb-record#L395
