### ISSUE TITLE
Random freezes during meetings

### ISSUE THREAD

**Issue by crog3ar** [bigbluebutton/bigbluebutton#10654]
**Describe the bug**
Random freeze (that last sometimes few seconds to minutes.

**BBB version (optional):**
2.2.26

**Desktop (please complete the following information):**
Persons who starts a meeting using Windows 10

bbb-conf --status 
All are ACTIVE

bbb-conf --check
no errors

**Additional context**
Pastebin log bbb-conf --debug
https://pastebin.pl/view/036c68de

**Comment by matiasilva** [comment]
Hi, what do you mean by "Windows 10 host"? BBB is meant to be run on Ubuntu, unless this is in a virtual machine?

**Comment by crog3ar** [comment]
My bad, person who starts a meetings, they are using w10

**Comment by matiasilva** [comment]
What's the computer CPU usage like? Can you reproduce this on other devices?

**Comment by crog3ar** [comment]
8core 16gb ram 1tb drive. Nothing suspicious in pastebin (log) file that i attached?

**Comment by matiasilva** [comment]
I mean on the computer, not the server.

**Comment by paraviz02** [comment]
Even then, what type of server are we talking about? If other things are running on the server or if the server is using swap (or even if bandwidth is an issue), that could surely cause this. Is the server running on a VPS or similar type of virtual environment? To have some info about how the server is hosted would also help. The UDP packets won’t get resent, so if there is a bandwidth problem on either server or client side, those packets may be “sent” but could be lost forever.

Doesn’t sound like a bug, sounds like a resource issue on either server or client.

**Comment by basisbit** [comment]
For support requests, please use the [forum / mailing list](https://groups.google.com/forum/#!forum/bigbluebutton-setup). This issue tracker here is only for BBB development related issues. Sorry.
