### ISSUE TITLE
Include join (& leave) time in participants export

### ISSUE THREAD

**Issue by amg-web** [bigbluebutton/bigbluebutton#10653]
Many teachers would like to have a information  how many people follow the webinars they organised. We currently can export the list with participant names, but it is not informative: some participants may join multiple times because of tech issues, or leave session soon.

**Describe the solution you'd like**
It is required to the list of users currently on meeting add timestamp join and leave meeting.
It may be downloadable file or separate page which can be saved and/or printed

**Comment by matiasilva** [comment]
Merging with #9960

**Comment by Rajesh98y** [comment]
we have implemented the webhooks for attendance and getting accurate attendance data.

**Comment by matiasilva** [comment]
Interesting. Do you have an example to share?

**Comment by Rajesh98y** [comment]
Please refer the below link to implement

https://docs.bigbluebutton.org/dev/webhooks.html


Best Regards:
Rajeshwar Yeleti
