### ISSUE TITLE
web socket error and fixed by restart

### ISSUE THREAD

**Issue by hmahdi-s** [bigbluebutton/bigbluebutton#10658]
There is a problem.
sometimes users faced web socket  error and can't start microphone.
In this case i did restart ngnix and not effected. just restart bbb is working and shows tomcat not running. but after restart the problem solve. and if I restart again  tomcat error disappear. 
I want to know what is the reason for web socket error and is there any main solution for that?

**Comment by matiasilva** [comment]
Hi, please read the documentation for troubleshooting: https://docs.bigbluebutton.org/2.2/troubleshooting.html#webrtc-errors-1001-1002. If you find the error persists, please follow the instructions for requesting help: https://docs.bigbluebutton.org/2.2/getting-help.html, I note especially the setup mailing list. This issue tracker is reserved exclusively for bugs and feature requests, and you also ignored the issue format.
