### ISSUE TITLE
Microphone button in bbb 2.2.27

### ISSUE THREAD

**Issue by YassineBaggar** [bigbluebutton/bigbluebutton#10652]
<img width="1019" alt="Capture d’écran 2020-10-14 à 11 34 50 a m" src="https://user-images.githubusercontent.com/44171427/95978249-d1ade700-0e11-11eb-9bb5-6877e61a3ba9.png">

Hi,

I updated bbb from 2.2.26 to 2.2.27, everything works fine, but when I clicked the microphone button nothing happens, and when I clicked on ListenOnly it works

**Comment by ffdixon** [comment]
Can you check the Javascript console log to see if there are any issues.  

Did you use [bbb-install](https://github.com/bigbluebutton/bbb-install) or the installation docs to upgrade?  If the docs, did you run `sudo bbb-conf --setip <hostname>` after the upgraded? See: https://docs.bigbluebutton.org/2.2/install.html#upgrading-from-bigbluebutton-22

**Comment by YassineBaggar** [comment]
Nothing in Javascript console.

I used the installation docs to upgrade and after the upgrade i ran sudo bbb-conf --setip <hostname> 

any solution, please?

**Comment by matiasilva** [comment]
There should be something in the console, not even some attempts to connect to any of the ICE candidates? Make sure to open the console and then click again.

**Comment by YassineBaggar** [comment]
I am sure there is nothing in the console

**Comment by mariogasparoni** [comment]
Are you guys using default settings for bbb-html5 ?
Please, share your config in this file:
```
/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml
```

**Comment by matiasilva** [comment]
Run `bbb-conf --setip your.fqdn` not with your IP.

**Comment by mtkunkel** [comment]
> Are you guys using default settings for bbb-html5 ?
> Please, share your config:

@mariogasparoni - Ansible generated settings available [here](
https://bin.disroot.org/?ab977ae0fe837c61#9CKfeLrE9nk6wpkEV5AH3XD11rKMffFgeaUUhmZ2W1e9).


> Run `bbb-conf --setip your.fqdn` not with your IP.

@matiasilva - Ansible does this for you, no change to any parameters since 2.2.26: 
https://github.com/n0emis/ansible-role-bigbluebutton/blob/master/tasks/config.yml#L7

Looks like the 2.2.26 packages have been pulled from the apt repos?  Tried rolling back (no dice).

**Comment by mariogasparoni** [comment]
@mtkunkel ,  i can see your settings differs a little from default one. 
Let me test if a combination in audio settings could be the problem.
Get back to you asap.

**Comment by nexusVI** [comment]
Same problem here, afaik the only modification in my settings.yml is 
skipCheck: true

Occurs after upgrading to 2.2.27.

**Comment by ahasanaki** [comment]
same problem on new installation 
bbb version 2.2.27

**Comment by mariogasparoni** [comment]
I believe i am able to reproduce.
Temporary workaround: try setting skipCheck to false.

**Comment by mariogasparoni** [comment]
yes, working to fix this asap

**Comment by aguerson** [comment]
Hello Guys,
I have just updated BBB from 2.2.24 ( patched manually to 2.2.25 ) to 2.2.27
And everything is OK
I never installed BBB with the script, but only with the repo !
No need to fix in my case.
Regards,
Aurélien.

**Comment by aguerson** [comment]
I precise that the version 2.2.27 is better with STUN / TURN activated with the echo test than before.

**Comment by paraviz02** [comment]
This has happened to us multiple times when upgrading BBB on Ubuntu 16.04. To the point where we image the server before any update.

I don’t know why it happens, but after upgrading the BBB components, more often than not, all users on all devices get stuck at the connecting to echo test.

Today, after updating to 2.2.27, the same issue happened. I’m not at a computer so don’t have access to server, but I can get some info if you request. We ended up re-imaging to 2.2.26 and everything works.

Building servers from scratch on any given version from the package repository seem to work fine every time. It is the upgrades that have problems.

**Comment by paraviz02** [comment]
Just to add ... besides setting FQDN, TURN server (or is it STUN?), wildcard SSL, there are no other changes to any settings.

**Comment by ffdixon** [comment]
After you upgrade, if your following the docs, did you do `sudo bbb-conf --setip <fqdn>`?  See: https://docs.bigbluebutton.org/2.2/install.html#upgrading-from-bigbluebutton-22

**Comment by paraviz02** [comment]
@ffdixon great question. I have not. But this is random, some updates work without incident. Some sit at “connecting to echo test” indefinitely. I will try it tomorrow when I get to my desk.

**Comment by maron2000** [comment]
Upgraded 2.2.26 to 2.2.27 via `sudo apt-get dist-upgrade`
Echo test fails

Then, after `sudo bbb-conf --setip my.domain.com` (not IP address but fqdn)
Echo test succeeds.
skipCheck is false (I didn't change anything intensionally)

**Comment by matiasilva** [comment]
> 
> 
> @ffdixon great question. I have not. But this is random, some updates work without incident. Some sit at “connecting to echo test” indefinitely. I will try it tomorrow when I get to my desk.

In some cases, a patch update necessitates that being set again due to some change in a configuration or the way something is done. That's why it's "random".  Even though that instruction is in the documentation for upgrading, it is rare that people actually do it and there was a an update where a configuration changed and so loads of folks reported audio not working..when they could've just read the documentation ;)

**Comment by matiasilva** [comment]
> 
> 
> I precise that the version 2.2.27 is better with STUN / TURN activated with the echo test than before.

Good to hear! 2.2.27 comes with a new version of sip.js (upgraded from the last 3-year-old one).

**Comment by aguerson** [comment]
Is it necessary to apply the PR "wrong SkipCheck handling" 10659 ?

**Comment by aguerson** [comment]
I think there are two issue in one here. 
https://github.com/bigbluebutton/bigbluebutton/pull/10659 fix the skipCheck: true problem
and update to 2.2.27 with bbb-conf --setip my.domain.com solved the other one.
Am I right ?

**Comment by matiasilva** [comment]
Yes :)

**Comment by aguerson** [comment]
Very strange : In my local LAN, the echo is more slow than with my VPN....

Do I have to skip my LOCAL subnet in the file /etc/kurento/modules/kurento/WebRtcEndpoint.conf.ini with the entry "ipIgnoreList" ?

**Comment by aguerson** [comment]
With my public IP, filtering it is no sense

**Comment by ffdixon** [comment]
If you hang tight, we should have 2.2.28 out shortly with the fix.

**Comment by matiasilva** [comment]
> Do I have to skip my LOCAL subnet in the file /etc/kurento/modules/kurento/WebRtcEndpoint.conf.ini with the entry "ipIgnoreList" ?

Note the discussion above. Kurento handles all media EXCEPT microphone audio. So doing anything with Kurento will do absolutely nothing as FreeSWITCH (and sip.js) is handling that.

**Comment by muellerlukas** [comment]
> If you hang tight, we should have 2.2.28 out shortly with the fix.

Is it realistic to release a new version until sunday? We are rolling out new releases every week in the night from sunday>monday.

**Comment by paraviz02** [comment]
@ffdixon @matiasilva you guys are awesome. That was my issue the entire time ... Simply setting the hostname. <facepalm>
