### ISSUE TITLE
BreakOutRoom - PDF Pagination

### ISSUE THREAD

**Issue by Davka** [bigbluebutton/bigbluebutton#10669]
**Describe the bug**
After creating a breakout room, only the first page is taken from the default pdf (5 pages).

**To Reproduce**
Create breakout rooms and try to navigate the pdf

**Expected behavior**
I get the original PDF

**Actual behavior**
I get only the first page

**Screenshots**

Main room
<img width="187" alt="Bildschirmfoto 2020-10-16 um 23 40 46" src="https://user-images.githubusercontent.com/1117697/96311118-12bc1c00-1009-11eb-9271-86469365e624.png">

BreakOutRoom

<img width="210" alt="Bildschirmfoto 2020-10-16 um 23 40 37" src="https://user-images.githubusercontent.com/1117697/96311125-13ed4900-1009-11eb-820c-05861e60a60d.png">

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser Chrome
 - Version 2.2.26 and 2.2.27

**Comment by basisbit** [comment]
This behavior is as designed: a teacher shows a presentation slide with a task, sends the students into the breakout room where they are moderators, and then later the students come back, they talk about it, and after that the teacher continues to the next slide which may contain the solution or other stuff which students should not yet see.
In most use case you'll not want students to see the next slides and possibly get distracted by them, but instead only want them to work on that task and return when they are done.

**Comment by basisbit** [comment]
If the current behavior is not what the teacher wants, they can join the breakout rooms and upload different presentation slides, so this should work well for all use cases.
