### ISSUE TITLE
BreakOutRoom - Random distribution doesnt Workd

### ISSUE THREAD

**Issue by Davka** [bigbluebutton/bigbluebutton#10668]
**Describe the bug**
The random distribution of the participants in the breakout rooms does not work. 

**Desktop (please complete the following information):**
 - OS: Mac
 - Chrome
 - 2.2.26 and 2.2.27

**Comment by matiasilva** [comment]
Please submit a new issue, this time following the issue format for your bug and with screenshots, details, as requested.
