### ISSUE TITLE
Settings are rollback after changing

### ISSUE THREAD

**Issue by Rajesh98y** [bigbluebutton/bigbluebutton#10665]
**Issue Statement:**

In Meeting Session, Goto **Options** (vertical 3 dots at right side upper corner) then **Settings** from dropdown.
then try to change "Audio Alerts for Chat" off to on
then save it.

Again comeback to same page, will see the it is in "off" mode only.

Can anyone please explain why it is not holding the changed value.

![Options_Settings](https://user-images.githubusercontent.com/48441020/96217573-84ac4b00-0fa0-11eb-9f98-115cf1a4f089.jpg)

**Comment by matiasilva** [comment]
Please repost the issue, this time following the issue format.
