### ISSUE TITLE
Audio reconnecting process may create a duplicated session/channel in FreeSWITCH

### ISSUE THREAD

**Issue by mariogasparoni** [bigbluebutton/bigbluebutton#10662]
**Describe the bug**
When reconnecting due to an unexpected closing of WebSocket (1001 code) , audio-manager creates a new audio session/channel in FreeSWITCH, even if the current audio channel is active and working fine. Instead of that, we should reconnect websocket without creating a new session.

**To Reproduce**
1. Join microphone, with a single user in the room
2. In bbb server, kill the worker thread of nginx, which is handling the reverse proxy between nginx <--> browser. To do that quickly, i am using this weird non-canonical bash command:
```
sudo kill -9 `sudo netstat -tanp4  | grep 443 | grep nginx | tail -n1 | xargs | cut -f7 -d" " | cut -f1 -d"/"`
```
This command will look for the nginx connections in netstat, and get the PID of the last worker-thread which holds the WebSocket connection (probably the audio connection) and then kill this thread :slightly_smiling_face:  . You may need to run it two times to drop websocket

3. Audio will reconnect, a new WebSocket connection will be created
4. Check fs_cli, there will be 2 channels/sessions

**Expected behavior**
After reconnectiing there shouldn't be duplicated channels in FreeSWITCH.

**Actual behavior**
As described, we have duplicated channels for a single user. The old channel will expire after a couple minutes, but we still have a time window of duplicated channels.

**BBB version (optional):**
2.2.27
Happens using any browser

**Additional context**
I have done a patch to fix this. Created this issue for documenting the problem.
Sending a PR asap

**Comment by simonschweizer** [comment]
We can confirm the occurrence of this issue in our organization under some conditions (mostly IPSec VPN users) with reconnects after like 13 minutes.

A quick fix would be really appreciated!

**Comment by Lukas2000** [comment]
This is a major issue for us as well on 2.2.27. Have had to instruct all students to switch to Chrome. It's causing a mess.
