### ISSUE TITLE
mouse pointer is shown mislocated on shared screen

### ISSUE THREAD

**Issue by ownhardy** [bigbluebutton/bigbluebutton#10661]
**Describe the bug**
When the presenter shares one of his screens, then the position of the mouse pointer is shown at a different position for the watching participants than for the presenter himself on his original screen. This happens for a two monitor setup under Windows, when in the Windows screen settings the position of the two screens is vertically shifted with respect to each other.

**To Reproduce**
1. use a Windows computer that has (at least) two screens
2. set the Windows "screen settings" such that the two screens are used "side by side", but with a shift in height with respect to each other (see attached screenshot)
3. start a BBB session as moderator
4. share one screen as moderator
5. move the mouse pointer into the shared screen and watch where you see it. Compare this to the position of the mouse pointer that you can also see in the BBB browser window that shows the shared screen.

**Expected behavior**
You want to see the mouse pointer at the identical position (with respect to the showed content, e.g. a slide) both at the "real" screen, as well as at the "shared screen" as displayed by BBB in the browser window for the presenter himself as well as for all watching participants in the BBB session.

**Actual behavior**
The position of the mouse pointer in the BBB browser display (and for all watching participants) is SHIFTED at a different position. (The mouse pointer is shown "higher" on the screen, when the screen setup is used, that is shown in the attached screenshot.)

**Screenshots**
See attaches screenshot with the Windows settings of the two monitors used. The "left" screen is shared.
![Screenshot_Anzeige-Einstellungen](https://user-images.githubusercontent.com/4622654/96114816-62ee8d80-0ee6-11eb-82d2-bc2df0a70f3b.png)

**BBB version (optional):**
Clientversion: 1032
ServerVersion: unknown (installed around June/July 2020)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version 81.0.2

**Comment by matiasilva** [comment]
Can you reproduce this issue with another browser?

**Comment by ownhardy** [comment]
I have now also tested this with the Chrome browser (still the same "shifted" monitor setup under Win10). And with Chrome (version 86.0.4240.75) this bug does NOT happen.

**Comment by matiasilva** [comment]
The reason that I asked to check across two browsers is that this sounds like a browser-specific issue and not necessarily a BBB issue. I suggest looking on bugzilla to see if you can find similar issues.

**Comment by ownhardy** [comment]
I have checked on bugzilla and do not find there any open bug report that sounds similar to this issue.

I share the suspicion of matiasilva that this might be a Firefox problem that cannot be fixed on the BBB code at all (becuse it works fine in Chrome). But on the other hand I would really like to see this bug fixed, because it would be a pity if BBB only runs on the Google browser Chrome flawlessly. How could we proceed to get this bug fixed?

Could someone with insight into the BBB code maybe generate a SIMPLE TEST CASE that shows what html-code (in the BBB code) gives the wrong result in the Firefox browser? With this test case I would then be willing to open a new bug report on bugzilla and discuss this with the Firefox team. But without help from the BBB team I see no reasonable way to open a useful bug report on bugzilla for this issue.

**Comment by prlanzarin** [comment]
This is most likely a browser thing, not related to BBB at all. Screen capture is browser **and** environment dependent (environment as in OS, OS version, display server, ...), so it's natural that it might vary in behaviour between those combinations.

You can check the canonical, untainted WebRTC screen capture sample here: https://webrtc.github.io/samples/src/content/getusermedia/getdisplaymedia/. We do nothing out of the ordinary in comparison to that sample (besides setting resolution constraints, which are configurable in BBB).

If you find out what you described happens in there as well, I suggest that this issue be closed.

**Comment by matiasilva** [comment]
Agreed!

**Comment by ownhardy** [comment]
I have opened a bug report with the above information on the Firefox bugtracker: https://bugzilla.mozilla.org/show_bug.cgi?id=1672126
