### ISSUE TITLE
Comfort noise (to subtly indicate an intact connection even if nobody's talking)

### ISSUE THREAD

**Issue by eMPee584** [bigbluebutton/bigbluebutton#10672]
Just stumbled over https://en.wikipedia.org/wiki/Comfort_noise , and it is exactly what I missed the other day as I was attending a B³ session (via chrome browser on android) with a few others and my audio got disconnected multiple times.. I was busy in the kitchen and had to fiddle out the phone again and again to check whether the connection was still up, even while I was speaking..

Some (very subtle!) form of comfort noise might help with this (although it probably has less of a priority than improving those other issues 😅)..

**Comment by matiasilva** [comment]
Should be relatively easy to implement with FreeSWITCH. I googled "bigbluebutton comfort noise", first result tells you what to do: https://groups.google.com/g/bigbluebutton-users/c/qf531pFhigA

**Comment by mabras** [comment]
Is this what you need or something diffrent:
https://docs.bigbluebutton.org/2.2/customize.html#turn-off-the-comfort-noise-when-no-one-is-speaking

**Comment by matiasilva** [comment]
Oddly enough, I don't think there is a comfort noise by default. That must've been enabled by default in an older version I presume..

**Comment by ffdixon** [comment]
Updated the documentation so it now reads "turn on" comfort noise.

https://docs.bigbluebutton.org/2.2/customize.html#turn-on-the-comfort-noise-when-no-one-is-speaking

**Comment by basisbit** [comment]
Closing this issue as it is a configuration option and is also documented properly. Nothing left to do here.
