### ISSUE TITLE
Audio bridge over websockets as fallback for when WebRTC fails

### ISSUE THREAD

**Issue by bigbluemeeting** [bigbluebutton/bigbluebutton#10671]
**Describe the bug**
Currently BBB exclusively uses WebRTC. Zoom however uses WebRTC with Audio over WebSockets as fallback. Zoom works all the time, BBB fails about 10-15% of users at any time who are unable to join the audio bridge. This will not improve over time, as certain users are guaranteed to be behind firewalls that block UDP and TCP ports that WebRTC needs.

**To Reproduce**
Host a BBB server, see users complain about the fact that they can not join the audio conference, have them do a WebRTC test and tell them that they are out of luck.

**Expected behavior**
BBB should ideally work for all users, regardless of their firewall settings.

**Actual behavior**
It does not work for 10-15% of users at any given time.

**Desktop (please complete the following information):**
 - All

**Smartphone (please complete the following information):**
 - All

**Additional context**
According to this document:
https://webrtchacks.com/zoom-avoids-using-webrtc/

Zoom uses an audio data channel over websockets. Examples of this exist online, for instance here:
https://github.com/Ivan-Feofanov/ws-audio-api
https://www.nexmo.com/blog/2016/12/19/streaming-calls-to-a-browser-with-voice-websockets-dr

This would then allow users who are behind firewall and unable to join via WebRTC to still be able to participate, even if they can not share video. And in fact a similar fallback over data channels could be implemented for video.

**Comment by bilias** [comment]
You can setup a turn/coturn server on 443 port. 
This is how we solved this

**Comment by basisbit** [comment]
Closing this issue because every BBB operator should also be running a TURN+STUN server and this is properly documented, so there is nothing left to do.
