### ISSUE TITLE
skipCheck is not working in BigBlueButton 2.2.7

### ISSUE THREAD

**Issue by pedped** [bigbluebutton/bigbluebutton#10676]
I am using big blue button 2.2.7 and it seem that skipCheck=true cause the problem

if I set it to true, and make listenOnlyMode=false,  when I open the meeting, it sucks at microphone. It works well in 2.2.6 but it have problem in 2.2.7.

**Comment by ffdixon** [comment]
We have this fixed in the upcoming 2.2.28.  If you want to try it out now, you can switch your server to the repository with developer packages (be sure to switch it back after 2.2.28 is released).  To try out the latest development build, use `bbb-install.sh` with the parameter `-v xenial-220-dev22a`.

**Comment by pedped** [comment]
I already have installed 2.2.7 on server, can I upgrade it but following codes?

`wget -qO- https://ubuntu.bigbluebutton.org/bbb-install.sh | bash -s -- -w -v xenial-220-dev22a -s c4.server.com -e support@server.com `

if I run this, do I need to change my config files again?

**Comment by ffdixon** [comment]
If you have done any custom configuration, you will need to re-apply the configuration after the upgrade. See https://docs.bigbluebutton.org/2.2/customize.html#automatically-apply-configuration-changes-on-restart.

**Comment by ha3ant** [comment]
Same problem with a fresh install.

**Comment by pedped** [comment]
@ffdixon thanks, I will try

**Comment by MortezaTaghaddomi99** [comment]
I didn't have this problem in version 2.2.26 or earlier versions. but after updating to 2.2.27 the issue appeared.

**Comment by matiasilva** [comment]
Folks, read above. This is a known bug and there is a pull request that is fixing it.

**Comment by antobinary** [comment]
Addressed in https://github.com/bigbluebutton/bigbluebutton/pull/10659
