### ISSUE TITLE
UserJoinedMeetingEvtMsg: TypeError: Cannot read property 'meetingProp' of undefined

### ISSUE THREAD

**Issue by ansomkrd** [bigbluebutton/bigbluebutton#10678]
Good afternoon. We do everything according to the documentation and with v2.2 everything goes well, but when installing 2.3 and building the develop branch, we get an error, we were building html5. erroruserjoinedmeetingevtmsg: TypeError: Cannot read property 'meetingProp' of undefined: "UserJoinedMeetingEvtMsg: TypeError: Cannot read property 'meetingProp' of undefined". And the conference window doesn't open.

**Comment by higunjan** [comment]
Getting same issue since couple of days but didn't find any solution for it. Did you find out @ansomkrd

**Comment by higunjan** [comment]
@ansomkrd 
I resolved it. This is problem with latest commits.
`git reset --hard 95277836f816d121e9a6c6c1350a1995de63be36`

Use above to go backward with some back commit and again do steps like `npm install` and `npm start`
