### ISSUE TITLE
BreakOutRoom - Random assignment does not work

### ISSUE THREAD

**Issue by Davka** [bigbluebutton/bigbluebutton#10670]
**Describe the bug**
The random distribution of the participants in the breakout rooms does not work.

**To Reproduce**
1. Create Meeting
2. Create BreakOut rooms in the participant list using the options
3. Click on Assign at random
4. Nothing happens

**Expected behavior**
The participants are randomly distributed to the rooms

**Actual behavior**
Nothing happens

**Screenshots**
![image](https://user-images.githubusercontent.com/1117697/96276456-5300a780-0fd3-11eb-98e7-65a419f510e6.png)

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser Chrome and Firefox
 - Version: Latest Releases

BBB Version 2.2.26 and 2.2.27

**Comment by jfsiebel** [comment]
Hi @Davka, only viewers are randomly distributed. In your test you had viewers among the participants?

**Comment by Davka** [comment]
Ah, thank you that of course explained itself. In the test, everyone had moderation rights
