### ISSUE TITLE
Error: Could not connect to the configured hostname/IP address (Read other similar issues with no solution)

### ISSUE THREAD

**Issue by pabusa99** [bigbluebutton/bigbluebutton#10688]
I have installed Bigbluebutton in own environment, with SSL certificate, the fact is if that when I use bbb-conf --check I have two errors:

Error: Could not connect to the configured hostname/IP address

.. and ...

Error: Unable to reach default URL for presentation:
.....

on the other side if I write HTTPS://myurl .... it works, I can see the mainweb in HTTPS
if I write the presentation URL also via HTTPS ..... it works. I can see the main web in HTTPS
If I write in the explorer  HTTPS://myurl/bigbluebutton/api I get  the .xml
---
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<response>
<returncode>SUCCESS</returncode>
<version>2.0</version>
</response>
------

However I still get errors with it... I can't connect from my moodle. I suppossed it could be relationed to the error I get from --check

It is Ubuntu 16.04, and I am nearly new in Ubuntu and BBB.... I have openned all ports from and for the bigbluebutton server in my firewall....

I have a proxy.

What can I try? It seems it works, however I can "not" connect (local with --check, neither from another machine with moodle,) but "yes" from the explorer)....

**Comment by matiasilva** [comment]
Hi, please follow the guidelines for getting help: https://docs.bigbluebutton.org/2.2/getting-help.html.
