### ISSUE TITLE
Presentation not working on configuration with SSL coded on ECDSA

### ISSUE THREAD

**Issue by tomaszlis86** [bigbluebutton/bigbluebutton#10687]
**Describe the bug**
After clean instalation of BigBlueButton Server 2.2.28 (2210) with option to use certificate provided in /local/certs presentation area is not showed on accessing demo meeting. The certificate is coded in ecdsa (wildcard certificate for whole domain) and log for html5 shows errors: sslv3 alert handshake failure. https://www.ssllabs.com/ssltest provides site with A raiting.
When using certificate coded in RSA (Let's Encrypt), installed in the same manner (copied to /local/certs and -d option on install script) everything works fine. 
It looks like some problem in html5 client component not being able to resolve the certificate.

**To Reproduce**
1. Use clean version Ubuntu 16.04.7 LTS
2. Copy certificate coded in ecdsa to /local/certs
3. Install BigBlueButton Server 2.2.28 (2210) using command (wget -qO- https://ubuntu.bigbluebutton.org/bbb-install.sh | bash -s -- -w -a -v xenial-22 -s hostname.domain.com.pl -d)
4. Open demo meeting from address hostname.domain.com.pl
5. Default presentation is not loaded correctly

**Expected behavior**
Presentation working smoothly with ssl configured on certificate coded in ecdsa.

**Actual behavior**
Presentation not working correctly with errors shown on html5 log.

**Screenshots**
![image](https://user-images.githubusercontent.com/73178905/96703431-bea79380-138a-11eb-88cf-7ea33d8ea0e2.png)

**Logs**
journalctl -u bbb-html5 | grep error :

`Oct 21 11:42:59 ip78 systemd_start.sh[10043]: error: No file found. Error: write EPROTO 139768127661888:error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure:../deps/openssl/openssl/ssl/s23_clnt.c:802:
Oct 21 11:42:59 ip78 systemd_start.sh[10043]: error: Error parsing image size. Error: write EPROTO 139768127661888:error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure:../deps/openssl/openssl/ssl/s23_clnt.c:802:`

this error shows as many times as there are slides in presentation.

**BBB version (optional):**
BigBlueButton Server 2.2.28 (2210)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browsers(64bit): Chrome(86.0.4240.111), Firefox (82.0), Edge (86.0.622.48)

**Comment by basisbit** [comment]
For support requests, please use the [forum / mailing list](https://groups.google.com/forum/#!forum/bigbluebutton-setup). This issue tracker here is only for BBB development related issues. Sorry.

I'd guess the problem is caused either by an invalid nginx config change or by specifying an encryption option which the nginx version of ubuntu 16.04 does not support.
