### ISSUE TITLE
 whiteboard sensitivity

### ISSUE THREAD

**Issue by burakguder** [bigbluebutton/bigbluebutton#10693]
I made some changes on the bbb html5-client V 2.2 .  

service.js

 if (annotation.status === DRAW_END || annotation.status === DRAW_START ) {
	  annotationsQueue.push(annotation);
	    if (!annotationsSenderIsRunning) setTimeout(proccessAnnotationsQueue, annotationsBufferTimeMin);
  }

and with other changes I made, I managed to send data in the DRAW_END event. But the line comes behind the cursor. 

Where should I look to improve this feature in bbb V 2.2? 
![bbb_whiteboard](https://user-images.githubusercontent.com/560147/96767949-e1b36100-13e5-11eb-97e4-88e264074722.gif)

**Comment by matiasilva** [comment]
The developer mailing list will help you:  https://groups.google.com/forum/#!forum/bigbluebutton-dev
