### ISSUE TITLE
BBB-Web Ubuntu Package overwriting TURN Config on apt upgrade

### ISSUE THREAD

**Issue by wmchris** [bigbluebutton/bigbluebutton#10698]
Just a quick information:
the post-install script of bbb-web has a typo, which results in loss of the turn configuration

**Comment by DrRetro** [comment]
Could you please describe the problem and the solution in more detail? Currently I am struggling with a bbb-server that was installed from scratch (about 2 hours ago) but the process of connecting to the echo test is very long (20 seconds). But the echo test works. 
I am grateful for any help just now.

**Comment by matiasilva** [comment]
Two very unrelated requests and an issue out of format. Please reopen the issue and follow the issue template.

**Comment by wmchris** [comment]
updated it. i think this should be enough to see the problem.

**Comment by ffdixon** [comment]
Thanks @wmchris for pointing this out.  We just double checked the post-install scrip for `bbb-web` and found (and fixed) the typo.  The fix will be in 2.2.29.
