### ISSUE TITLE
Cross domain cooking sharing on Chrome denies BBB server connection request

### ISSUE THREAD

**Issue by abdnafees** [bigbluebutton/bigbluebutton#10690]
**Describe the bug**
As mentioned in the title our BBB server is set up in a different environment than the host environment as a result Chrome is not allowing cross-site cookie sharing. Is it possible that this is a BBB issue than a Chrome issue?

**To Reproduce**
1. Go to your BBB meeting component.
2. Click on Join Meeting button.
4. See error "Connection could not be established".

**Expected behavior**
BBB meeting should be able to open when the user click Join Meeting button

**Actual behavior**
BBB component on Open edX does not connect to the BBB server

**Screenshots**
![d174966e-6315-42e1-8947-3dad07a0b6f1](https://user-images.githubusercontent.com/19777158/96724798-aacf5200-13c9-11eb-8e26-b165a1a26743.png)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Chrome
 - Version: Version 86.0.4240.75 (Official Build) (64-bit)

**Additional context**
This error will occur when your BBB server is hosted on a different domain than your host domain.

**Comment by matiasilva** [comment]
Can you edit your issue to conform to the issue format?

**Comment by daminebenq** [comment]
@abdnafees 
if you are using iframe with cross domain, then yes bbb supports all basic functionalities in iframe and cross-domain iframe.
is this what you are asking ?

**Comment by abdnafees** [comment]
> Can you edit your issue to conform to the issue format?

Yeah, the format didn't appear when initially opened the issue.

**Comment by abdnafees** [comment]
> @abdnafees
> if you are using iframe with cross domain, then yes bbb supports all basic functionalities in iframe and cross-domain iframe.
> is this what you are asking ?

I am using LTI Consumer in Open edX

**Comment by abdnafees** [comment]
Hey guys, any update on this?

**Comment by pedrobmarin** [comment]
I made some effort to read the message from your browser on that tiny pic you sent. This is more related with your setup other than a BigBlueButton issue. You have to set the cookie policy as SameSite=None. Please go after more help at the mailing lists.

**Comment by abdnafees** [comment]
> I made some effort to read the message from your browser on that tiny pic you sent. This is more related with your setup other than a BigBlueButton issue. You have to set the cookie policy as SameSite=None. Please go after more help at the mailing lists.

I could have provided you with a better screenshot but you just conveniently closed the issue! I mean, way to go!

**Comment by pedrobmarin** [comment]
I did not ask for a better screenshot. I asked you to use the mailing lists for problems like this one. There are half of a dozen threads there that already discussed similar issues. Next time you can also try searching before posting.

https://groups.google.com/d/msg/bigbluebutton-dev/-xXkwtfjTo0/WXObk9K7AgAJ
https://groups.google.com/d/msg/bigbluebutton-dev/3SE928jGagg/l0MvKLElAQAJ
https://groups.google.com/d/msg/bigbluebutton-dev/CCCObMNin0s/xDxdRguIAgAJ
https://groups.google.com/d/msg/bigbluebutton-dev/bUeHOo4Yu6o/EpMaGqKbAQAJ
https://groups.google.com/d/msg/bigbluebutton-dev/3SE928jGagg/1_doLNObAQAJ

**Comment by abdnafees** [comment]
Five years later. Still hurts. Don't even remember why I was angry or for which client I was asking.
