### ISSUE TITLE
Error 1004 during echo test after clone the server 

### ISSUE THREAD

**Issue by haykelbensalha** [bigbluebutton/bigbluebutton#10707]
I have a BBB server running fine on a VM with a public address and hostname, the version of BBB is 2.2.28.
I decided to migrate the VM to another more powerful host, so I cloned the VM,
in the new VM I launched the bbb-install.sh script to make the necessary modifications concerning the new public IP address
BBB works works except an error 1004 during the echo test
i need your help

![image](https://user-images.githubusercontent.com/36150447/96971624-a912a500-1515-11eb-8550-e990128532ec.png)

**Comment by matiasilva** [comment]
Hi, thanks for posting.  This issue tracker is for bug reports and feature enhancements only, so please follow the guidelines for getting help here: https://docs.bigbluebutton.org/2.2/getting-help.html.
