### ISSUE TITLE
Place own video aside from all attendees videos

### ISSUE THREAD

**Issue by MateMatiker** [bigbluebutton/bigbluebutton#10709]
**My feature request is related to the following problem**
I find myself looking at my own video all the time, even though I am more interested in what others are doing. 

**I would welcome the following solution**
Display own video not on the same level as attendees. Yes I want to be able to see myself, but primarily I will look at others. When I am in a meeting I will rarely look at myself in a mirror. The own video is mostly important to check if my video is on, okay and if I and my surroundings look presentable. It follows that the own webcam picture should be available for inspection if needed but not in the foreground. This could be achieved by putting it at a fixed position, a bit smaller and aside from the other attendees videos with the option to enlarge if needed.

**I have considered the following alternatives**
- own video could be made smaller, but then it would still be in the attention focus and make it difficult to arrange video in window
- it could be turned off, but then I am less aware whether my webcam is on or off. This information is important and should be prominent
- it could be hidable, but then this means extra configuration effort for the user. The product can help the user by setting reasonable default configurations. I personally prefer a solution that reduces the effort needed from me and that is not only physical effort (true - a click is not so bad), but also mental effort (I have to think about what I can do and if I want that). This distracts me from the meeting I want to attend.

**Additional context**
I think of a small (thumb size) video window at the lower right for example.

**Comment by matiasilva** [comment]
Since this is a layout enhancement, you should note that there is a feature that is already being developed that will allow you to customize the layout in a very flexible way. I bet this PR will likely be resolved that that. Not to mention you can drag your own camera around and resize it as you wish already.

**Comment by MateMatiker** [comment]
Hi Matiasilva,

that sounds awesome. Thanks for the info! Dragging around and customizing would solve this if the settings could be saved. If I have to do this in each call this would be a bit cumbersome. But I guess it depends how many users like it. If its only a few that is a solution, if it is the majority then a default setting would be more appropriate.
 
> Since this is a layout enhancement, you should note that there is a feature that is already being developed that will allow you to customize the layout in a very flexible way. I bet this PR will likely be resolved with that. Not to mention you can drag your own camera around and resize it as you wish already.

**Comment by stephenglobal1** [comment]
Hi. **Has there been any movement on this feature yet?**  It would drastically improve the 1-on-1 chat experience when you can view the person you are talking to and the thumbnail size video of yourself on screen.  

At present, If you go full screen on the person you are speaking to, then all the buttons and timer are not seen. This takes away from the user experience, plus, it's more effort for users to do extra clicks.

**Comment by antobinary** [comment]
In https://github.com/bigbluebutton/bigbluebutton/pull/17935 we have implemented the option to hide your own webcam stream so you don't see it. This is as far as we plan on proceeding in this direction (i.e. we're not considering reducing the size of your own webcam view or moving it or changing the layout, etc)
We welcome any feedback on it in 2.7. #17935 will be part of 2.7.0-alpha.1 whenever it's out (currently in progress).
