### ISSUE TITLE
Double appearance of some languages 

### ISSUE THREAD

**Issue by iznakurnozh** [bigbluebutton/bigbluebutton#10706]
label:"Low Priority" 
label:"User Interface (UI)"

**Describe the bug**
Some languages in the settings list appear twice. If there is any difference maybe we could indicate it somehow?

![image](https://user-images.githubusercontent.com/38284875/96933034-1267c900-14c0-11eb-9cd3-55f12ac9fd68.png)

**BBB version (optional):** 2.2.28

**Comment by antobinary** [comment]
The language files that these files refer to are different and have different content. ru.json and ru_RU.json for example. They come straight from Transifex.
On 2.2 we use a library for this part and we don't have much control.
However, on 2.3 we expanded the level of control, so I will mark this to be addressed on 2.3.
Thank you for bringing this up!
