### ISSUE TITLE
User gets "Audio Connected" message, even if microphone is working fine

### ISSUE THREAD

**Issue by mariogasparoni** [bigbluebutton/bigbluebutton#10712]
**Describe the bug**
Sometimes user gets "Audio Connected" message, but audio is running just fine

**To Reproduce**
1. Join with microphone
2. Wait until the message appears
(It takes 10min~15min to happens, especially if user is having network issues)

**Expected behavior**
Audio is running fine. There shouldn't be any popup alert

**Actual behavior**
BBB shows a popup message "Audio Connected"

**Additional context**
As explainned in the commit message, this happens because 'connected' state is triggered after ICE connection is estabilished.
Created this issue for documenting purpose, i already have a patch that fix this.
Sending it asap

**Comment by mabras** [comment]
We have apply https://github.com/bigbluebutton/bigbluebutton/pull/10714. Users disconnected and reconnected from time to time.

**Comment by mariogasparoni** [comment]
#10714 actually is focused on the start/begin of audio connection (echo test), and also solve this "You have joined the audio conference" message (while user still in audio). If you are having audio issues during the session (different from this one), please open a new issue , including all info you can gather.

**Comment by FerretBoiX** [comment]
I have found a fix for this.
You have to open CMD in administrator mod and write the command
`net stop http`
