### ISSUE TITLE
Images in slides disappear and appear

### ISSUE THREAD

**Issue by vdtoorn** [bigbluebutton/bigbluebutton#10711]
During a presentation (teaching) some of the images in slides disappear when going back a slide, and sometimes reappear when going back and forth between slides

**To Reproduce**
1. upload a PDF as presentation, including images
2. click through the presentation, make annotations
3. go back one or more slides, sometimes images are not displayed. Same for some users but not all
4. sometimes browsing through the presentation will restore some images and remove others

**Expected behavior**
Images don't disappear :)

**Actual behavior**
Unexpected and unpredictable absence of images

**Screenshots**
Screenshot with disappeared content
https://ibb.co/xfxb01n

**BBB version (optional):**
BigBlueButton Server 2.2.28 (2210)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - Version 81.0.2 (64-bit)

**Comment by wiebkemueller-hsh** [comment]
A lecturer at Hochschule Hannover also reported the same problem: 

Steps to reproduce see above.

Some extra info to actual behaviour:
- Images on slides disappear whilst the footer and header of the slide and the before made annotations remain.
- Images had been inserted in an MS Office document which was then converted to PDF and uploaded to BBB for presentation.
- The problem occured in meetings with differing nb. of attendees (from 30-130).

OS Windows 8.1.
Browser Firefox

**Comment by hex-m** [comment]
Does the problem also occur on https://test.bigbluebutton.org? Can you provide an example presentation so it can be reproduced?

**Comment by wiebkemueller-hsh** [comment]
unfortunately the problem could not be reproduced neither on https://test.bigbluebutton.org/ nor in a test session in our local BBB. makes me think it only occurs when there are multiple attendees in a conference?

**Comment by vdtoorn** [comment]
Hi, that may be possible, for me it happened during a busy class (~ 40 people attending)
