### ISSUE TITLE
Recording files are not getting proccessed - no raw file

### ISSUE THREAD

**Issue by Darkw00** [bigbluebutton/bigbluebutton#10715]
**Describe the bug**
After five days, there was no recording of the session. I tried to rebuild but can't rebuild because there is no raw file. There are correct files in /var/kurento/recordings/, just sitting there, how can i get them to start proccessing?

**Expected behavior**
Raw file is created and then recording is published. 

**Actual behavior**
The files are not getting processed no raw file is getting created. 

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [Chrome]
 - Version [e.g. 86]

**Additional context**
This happend on 2.22.26 i updated to latest 2.22.28 in hope of saving the problem but to no avail. Files are still there but not getting proccessed to raw files and then to presentation.

**Comment by Darkw00** [comment]
Let me clarify that there is only just ONE such recording. Others are getting processed normally as they should. Does anybody have any idea how to start processing this one, or is it lost. I can download files for webcam, screenshare and audio. But they are not proccessed, should I just give up and try to sync them manually, it has been over a week.

**Comment by myOmikron** [comment]
This is still a thing in 2.2.31, in `bbb-record --list` meetings apear sometimes without a external meeting id, sometimes they have. But they all have in commen that there are no raw files, the events.xml isn't inplace. When looking through the logs, `recording=true` was passed when the meeting was created and the moderator started the recording.
