### ISSUE TITLE
Install older Version possible?

### ISSUE THREAD

**Issue by MichaelSauerHTWdS** [bigbluebutton/bigbluebutton#10723]
Is it possible to install an older version, e.g. to go back 2 or 3 tags?

**Comment by antobinary** [comment]
Check this comment https://github.com/bigbluebutton/bbb-install/issues/249#issuecomment-667639041
If you hit a specific issue in the latest release, please make sure you report it (on the bigbluebutton-dev https://groups.google.com/g/bigbluebutton-dev list)
