### ISSUE TITLE
error 1020 with safari on iphone

### ISSUE THREAD

**Issue by jlabonte24** [bigbluebutton/bigbluebutton#10729]
Hi when i try to open camera on safari iphone, i have a error 1020.
I try turn/stun server and the error is the same.
my server is on OVH metal server.
i open all port on my firewall to be sure it's not a deny port.

i'm confuse????

This is possible remove safari as obligatory on iphone, because if people try to open with chrome, a message say will be open with safari
or do you have a other solution.

THNKS

**Comment by ffdixon** [comment]
Can you post this message to [bigbluebutton-setup](https://groups.google.com/forum/#!forum/bigbluebutton-setup) where the community can help you out.

If in your post we determine there is an problem with BigBlueButton itself, we'll open open an issue here to solve it.

When you post, let us know if you get the 1020 error with https://test.bigbluebutton.org/.
