### ISSUE TITLE
Waiting participants - Implement a scroll bar for the accept/deny list

### ISSUE THREAD

**Issue by Subdarub** [bigbluebutton/bigbluebutton#10722]
**Is your feature request related to a problem? Please describe.**
If more then 20 ppl are waiting to join your conference, the 21th person gets cut off and you would be unable to accept this specific person to the conference.

**Describe the solution you'd like**
Implement a scroll option to the list, so if youve had more than 20 ppl waiting you would still be able to accept everbody after that.

**Workaround**
You can zoom out to see more particpants but then you would be unable to read the names.

**Additional context**

Of course more than 20 ppl waiting is a little bit out of the ordniary. But in this case this solution is for a conference that generally lasts a whole day and where the topics are rather of confidential nature. There is a lot of preparing involved for said conference. On a good day there will be about 20 to 30 presentations. Parts of the conference are only relevant for a set amount of people. Meaning if everbody were to try to join the conference about 50 ppl or so, the list wouldnt be able to fit them all. In a worst case scenario you wouldnt be able to accept a person into the conference that actually has to be in the conference because you cant see them.

I also added a screenshot so you can see whats happening here. The resolution of my monitor is 1440p, so on a 1080p u might even be able to see less.
![2020-10-26_12-59-03](https://user-images.githubusercontent.com/35487480/97171096-2005a300-178d-11eb-953e-b0456b5f50aa.png)

**Comment by antobinary** [comment]
This is fixed in the upcoming 2.3.x https://github.com/bigbluebutton/bigbluebutton/pull/10027
