### ISSUE TITLE
Join user names with character decoding: '&'--> '&amp;' issue

### ISSUE THREAD

**Issue by rajasekharponakala** [bigbluebutton/bigbluebutton#10724]
**Describe the bug**
When a user want's to put two names with an ampersand symbol in the 'join', it shows `&amp;` rather than '&'

**To Reproduce**

**Expected behavior**

**Actual behavior**

**Screenshots**

**BBB version (optional):**
BigBlueButton continually evolves. Providing the version/build helps us to pinpoint when an issue was introduced.
Example:
$ sudo bbb-conf --check | grep BigBlueButton
BigBlueButton Server 2.2.2 (1816)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, Mac]
 - Browser [e.g. Chrome, Safari]

**Smartphone (please complete the following information):**
 - Browser [e.g. stock browser, Safari]

**Additional context**

**Comment by antobinary** [comment]
We sanitize special characters. You can also use 'and'. I don't think we want to change this.
