### ISSUE TITLE
meeting  Statistics   server side

### ISSUE THREAD

**Issue by DiptoChakrabarty** [bigbluebutton/bigbluebutton#10735]
From the bigbluebutton web UI we can view meeting statistics ,I have deployed  a big blue button server and would like to take that data retrieved from the meetings and use it   elsewhere

**Describe the solution you'd like**
A directory or location in server where meeting statistics are stored and server administrators can access it from there

**Comment by lonesomewalker** [comment]
There are already SO MANY dashboards out there which are fully functional.
I suggest you have a look.

**Comment by matiasilva** [comment]
Documentation: https://docs.bigbluebutton.org/admin/monitoring.html
