### ISSUE TITLE
Run BigBlueButton (BBB) with two different interfaces/IP addresses? For internal and external usage

### ISSUE THREAD

**Issue by benutzer-prog** [bigbluebutton/bigbluebutton#10731]
Hello, is it possible run BigBlueButton (BBB) with two different interfaces/IP addresses?

Something like that:

![image](https://user-images.githubusercontent.com/55136823/97261432-1c226100-181f-11eb-9c81-eda59abbdbc9.png)

We already tried different installations which are described in the firewall guide (https://docs.bigbluebutton.org/2.2/configure-firewall).

It was possible to use BBB normally as an external user. A user from 10.0.2.x is only able to use the website without audio/video. The hostname of the webserver were resolved with a internal IP. So far so good. 

After joining a session from the internal network the „sip.js“ trying to connect to the server and getting a response while the echotest like that:
| sip.Transport | Received WebSocket text message:
…
v=0
o=FreeSWITCH 1603699034 1603699035 IN IP4 203.0.113.1
s=FreeSWITCH
c=IN IP4 203.0.113.1
…
a=rtcp:24460 IN IP4 203.0.113.1
a=ice-ufrag:wCPdt71Q5gFRq4IN
a=ice-pwd:fdULe4aNJAJngA5C2LFmJx2E
a=candidate:9809564085 1 udp 659136 203.0.113.1 24460 typ host generation 0
…

The problem of this response is that it only contains the public ip address.

After some research I found out that it is possible to expand the candidates (https://github.com/signalwire/freeswitch/issues/58#issuecomment-683256366) with the external IP. So we changed the setup but then we had the problem that the freeswitch server was trying to response over the internal interface on external request.

A solution could be that the „Received WebSocket text message“ would contain a DNS name like bigbluebutton.example.com or both IP addresses (internal and external). But then all components need to be configured to listen on both addresses.

Kind regards,

Ben

**Comment by ffdixon** [comment]
Good investigation.  We (the core developers) have not tried it ourselves, but perhaps others can chime in.

**Comment by maron2000** [comment]
It'll be totally easier if you setup a NAT in the firewall of the right hand side of your figure,
and forward all required communication to 10.0.2.12.
Then you can simply follow the steps in [https://docs.bigbluebutton.org/2.2/configure-firewall](https://docs.bigbluebutton.org/2.2/configure-firewall).
(or even bbb-install.sh may do everything for you)
In addition, you can run your server with a single interface.

**Comment by ichdasich** [comment]
Take a look here: https://github.com/ichdasich/bbb-rev-prox 

Your usecase should be relatively similar.

**Comment by greenycat** [comment]
Hello, issue is solved with proper network configuration.
Check out _Hairpin NAT_ or _Hairpinning_.

**Comment by benutzer-prog** [comment]
Thank you very much for your responses!

These hints (specially https://github.com/bigbluebutton/bigbluebutton/issues/10731#issuecomment-719081701) were very helpful in finding a working solution:

![image001](https://user-images.githubusercontent.com/55136823/99487611-04925000-2967-11eb-8d07-764c30bed73f.png)

**Comment by benutzer-prog** [comment]
Closing the issue. The #10731 (comment) solved our problems. Thanks to everyone.
