### ISSUE TITLE
Please deploy packages for xenial-220-2.2.28

### ISSUE THREAD

**Issue by aogilvie** [bigbluebutton/bigbluebutton#10732]
and 29 if ready.

:pray:

**Comment by antobinary** [comment]
The version 2.2.28 is what's in `xenial-220` repository. It will become `xenial-220-2.2.28` only when we push 2.2.29 out. What is the specific issue you hit that is present on .28 but not on .29?

**Comment by aogilvie** [comment]
Thanks. I saw there was a version bump already to 29 in the repository. Will use xenial-220 packages for now then.
