### ISSUE TITLE
Servers behave strangely after a load situation

### ISSUE THREAD

**Issue by Davka** [bigbluebutton/bigbluebutton#10736]
**Describe the bug**
Servers behave strangely after a load situation

**To Reproduce**
Put the server under extreme load, over 1000 users in one meeting

**Expected behavior**
The servers continue to operate normally after the load situation

**Actual behavior**
audio lost video stable, notice: "Your are joining the conference", Disconnections,
Meetings that continue with "ghost participants"

**Screenshots**
<img width="166" alt="Bildschirmfoto 2020-10-27 um 22 00 34" src="https://user-images.githubusercontent.com/1117697/97362360-31d86a80-18a1-11eb-9522-e420771d78cf.png">

**Desktop (please complete the following information):**
 - OS: [Windows, Mac]
 - Browser [Chrome, Firefox]

**Comment by ffdixon** [comment]
Yes, we recommend in 2.2. that no single meeting have over 100 users.  We're working in improving that scalability in 2.3-dev (currently under development).  See https://docs.bigbluebutton.org/support/faq.html#how-many-simultaneous-users-can-bigbluebutton-support.

**Comment by Davka** [comment]
What about 10 meetings with over 100 participants? We have such situations too. Everything's going well so far, just these little problems afterwards.

**Comment by lonesomewalker** [comment]
All sessions above 100 users require special setup.
We run several servers with larger meetings.
Suggest to have a look at low latency kernel, raising system limits, using no hdd's, network card should be configured to match your network situation,...
There are so many tweaks.

Also it makes a huge difference if the participants join simultaneously or just by smaller groups/joined by moderators.

**Comment by harykeyrun** [comment]
Can we scale Kurento media server only, if there are simultaneous webcam users in multiple sessions?

**Comment by soheilrahsaz** [comment]
@lonesomewalker NEVER use Low Latency Kernel, it will reduce your performance by 60%.
I have tested it on several servers.

**Comment by Davka** [comment]
I think our setup is sufficient. We now have 20 BBB nodes in the cluster that meet our requirements. However, after a load situation, the respective nodes do not continue to run properly, so the above-mentioned problems occur.

**Comment by Davka** [comment]
Basically, it can be observed that compared to 2.2.26, the 2.2.28 is more unstable. Participants lose the connection or have serious sound problems. Entering a meeting also takes an unusually long time.

**Comment by lkiesow** [comment]
I can confirm the issue. It sometimes happens that in certain load situations users seems to reconnect over and over again while that original sessions are never removed. This means that a meeting can blow up and you end up with hundreds of ghost users in a meeting which will never end. If this starts to happen, it also usually means that quickly all users end up having problems and the whole conference (sometimes the whole server) grinds to a halt.

We also have seen this in recent version but this could also be due to semester starts here at universities, causing a high load with lots of users in general. I've seen similar issues in April. But it's certainly still a somewhat critical issue.

**Comment by TeachReo** [comment]
I have same problem like you and I search how it's possible to downgrade to specific version ?

**Comment by schaary** [comment]
> I have same problem like you ( @Davka ) and I search how it's possible to downgrade to specific version ?

If you downgrade to v2.2.26 or lower you inherit serious security issues.

**Comment by lonesomewalker** [comment]
Okay, finally we are able to reproduce the "ghosting" situation.
Mostly if people have bad internet connection and try to reconnect :-|

Is there a possibility that BBB can "recognise" the same client and delete the old "ghost" users related to the same profile?
Like giving an ID to the user which is "maybe" self-chosen?

**Comment by ffdixon** [comment]
There has been work done 2.3-dev (still under development) to better handle client reconnections and not create "ghost" users.  See https://github.com/bigbluebutton/bigbluebutton/pull/10369.

This pull request has merged into the `develop` branch and will be in the upcoming 2.3-alpha3 release, which we are working on getting released soon.

**Comment by SamuelWei** [comment]
I can confirm that we had the same problem end of last week. Suddenly the server crashed and after a restart we had meetings running with hunderts of ghost users.

**Comment by Davka** [comment]
I think we can close this for the first time. With the 2.2.29-alpha and the stable, it has become significantly better.
