### ISSUE TITLE
"You have joined the audio conference" popup message appears multiple times throughout the conference

### ISSUE THREAD

**Issue by farhatahmad** [bigbluebutton/bigbluebutton#10749]
**Describe the bug**
While participating in a conference, the `You have joined the audio conference` popup appears multiple times at seemingly random times throughout the conference. 

**To Reproduce**
1. Start a conference 
2. Join using audio
3. Pay attention to the top right of the screen. You should see the popup appear there every once in a while

**Expected behavior**
The `You have joined the audio conference` should only appear once as soon as I join the audio

**Actual behavior**
The `You have joined the audio conference` appears multiple times

**Screenshots**
![image](https://user-images.githubusercontent.com/35435341/97614180-0021e980-19f0-11eb-8cb3-d12416bfc9f3.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser: Firefox
 - Version: 82.0

**Comment by ffdixon** [comment]
Hmm ... I wonder if this is a result of a reconnect.

**Comment by timm2k** [comment]
Some of my users having same problem but I don't want to hijack your issue.

@farhatahmad please gather some data if this error occours, 
Grab your `sessionToken` (eg. `rfxhqlo8ylftq3q2`) out of your Browser's address bar and run `grep <sessionToken>  /var/log/syslog` on your server (or ask the admin). Replace sensitive data like Names or IP adresses before you post the output here (use formatting!), gist.github.com or pastebin.com etc.

**Comment by mariogasparoni** [comment]
I believe this can be related to https://github.com/bigbluebutton/bigbluebutton/issues/10712

**Comment by FerretBoiX** [comment]
I have found a fix for this.
You have to open CMD in administrator mod and write the command
`net stop http`
