### ISSUE TITLE
[Bountysource] Safari Support Broken [IOS|Mac] v2.3-alpha-1 & v2.3-alpha-2

### ISSUE THREAD

**Issue by Cosnavel** [bigbluebutton/bigbluebutton#10747]
[This Issue is on Bountysource](https://www.bountysource.com/issues/93710846-safari-support-broken-ios-mac-v2-3-alpha-1-v2-3-alpha-2)

Regarding some other issues opened on this topic, I want to sum this up. 
#10729 #10746 

Since Version 2.3-alpha-1, the safari support dropped on Mac and IOS. This affects the webcam integration. Incoming streams from other participants take a long time to load. Outgoing webcams cannot be started due to error 1020. The webcam preview won't be shown in Safari (Mac).

To reproduce, start a Meeting on a Big Blue Button Server using Version 2.3-alpha-* and connect with an IOS Device. Then start Webcam Sharing. 

I have tested these things on an iPhone XS & iPhone 8 running IOS 14 & IOS 13. Aswell on a Macbook Pro running Big Sur, Macbook Pro running Catalina, and an iMac running High Sierra. 

On iPad Pro and iPad Air, I cannot prove this issue because I cannot start any dialog. The Buttons won't react. Referencing issue #10415 

Screenshots Safari Macbook Big Sur:
<img width="734" alt="CleanShot 2020-10-29 at 5 06 56@2x" src="https://user-images.githubusercontent.com/42392570/97601308-53a13100-1a0a-11eb-9011-e539008ac1f3.png">
![CleanShot 2020-10-29 at 5 07 37@2x](https://user-images.githubusercontent.com/42392570/97601326-5734b800-1a0a-11eb-8456-9352fc886a2b.png)
<img width="1418" alt="CleanShot 2020-10-29 at 5 07 46@2x" src="https://user-images.githubusercontent.com/42392570/97601349-5c920280-1a0a-11eb-93a1-2331b3fd3ce9.png">

Screenshots iPhone XS:
![IMG_3826](https://user-images.githubusercontent.com/42392570/97601432-73d0f000-1a0a-11eb-8701-045d2c3a56fb.PNG)

**Comment by DokSchneider** [comment]
error 1020 no connection to server when trying to share the webcam with Safari 14 on macOS Catalina 10.15.7 or with IOS 13.7 on iphone or ipad

**Comment by mcferdev** [comment]
I am with the same problem.
Mine doesn´t work with iOS 13.7
BBB version 2.2.26

Was working perfect before the iOS upgrade.

**Comment by mcferdev** [comment]
If you try on https://test.bigbluebutton.org/ , it works ?

Here, worked.

**Comment by DJeremyy** [comment]
> If you try on https://test.bigbluebutton.org/ , it works ?

It works on test.bigbluebutton.org 🤔

**Comment by Cosnavel** [comment]
I can only confirm the Issue on the Versions 2.3-alpha-1 and 2.3-alpha-2. 
As I know [test.bigbluebutton.org](test.bigbluebutton.org) runs on 2.2.*

**Comment by matiasilva** [comment]
test23.bigbluebutton.org

**Comment by Cosnavel** [comment]
> test23.bigbluebutton.org

What Version are you running ?

**Comment by DokSchneider** [comment]
On test23.bigbluebutton.org I get a web socket error 1002 when starting a session and the audio does not work (same with Safari and Firefox on macOS Catalina on a Macbook Air). However, the webcam appears to work with both browsers.

**Comment by ffdixon** [comment]
We just updated https://test23.bigbluebutton.org/ to the latest version of 2.3-dev.  Can you try it again and let us know if you get the 1002 error.

**Comment by DDQW** [comment]
I can confirm it works now on ios 14.1 safari.

**Comment by Cosnavel** [comment]
I cannot confirm it working. I now get the same issue in Chrome Version 86.0.4240.111 (Mac). Error 1020 when I start the Webcam on Mid Quality. On High Quality it works. Never got this issue in Chrome before.

**Comment by DokSchneider** [comment]
It now works with Safari 14 on macOS Catalina 10.15.7 and Safari on iOS 13.7 on iphone. 
It does NOT work on my ipad pro with iPadOs 14.1 (12.x did not work either). On my iPad Pro upon joining a conference the interface does not react (pressing buttons, menu items, entering text in the public chat... nothing works).

**Comment by mcferdev** [comment]
> I can only confirm the Issue on the Versions 2.3-alpha-1 and 2.3-alpha-2.
> As I know [test.bigbluebutton.org](test.bigbluebutton.org) runs on 2.2.*

I don't understand. My Version is 2.2.26 and doesn't work. But test.bigbluebutton is working. Which version is running in test ?

**Comment by JohnWalkerx** [comment]
> I don't understand. My Version is 2.2.26 and doesn't work.

My version is 2.2.28 and it also doesn't work. Also get error 1020.
Tested on iOS 12.4.8 on iPhone 5S.

**Comment by ffdixon** [comment]
> I can confirm it works now on ios 14.1 safari.
> how can we update to this release?

The server at https://dev23.bigbluebutton.org/ is running a build of 2.3-alpha3.  We're working on releasing this build to everyone soon.

**Comment by DokSchneider** [comment]
I have testet with my iphone XR running iOS 13.7 and with my iPad Pro running iPadOS 14.1 and with both devices I get the error 1004
![IMG_6929](https://user-images.githubusercontent.com/8005372/98251783-76d35f80-1f79-11eb-9831-253746ad1051.PNG)

**Comment by PhMemmel** [comment]
Not reproducible for me:
Safari works on test23.bigbluebutton.org, currently running 2.3-beta-2 (html5 client 1552) on iPadOS 14.4.2. Freeswitch audio, kurento audio, video sharing in all qualities, no problem at all.

**Comment by mrkeksi** [comment]
not comprehensible for me either:
tested with Safari on test23 with iOS 14.5 (Beta) on an Iphone 12 Mini. Audio input and output as well as webcam work.
