### ISSUE TITLE
mixed up messages 

### ISSUE THREAD

**Issue by testerik** [bigbluebutton/bigbluebutton#10748]
This happens with the actual version 1058 of the html5client:

When changing the possibility of downloading a presentation (after ⊕ → upload presentation), there is the symbol right from the presentation correct (a sheet of paper, which is crossed out if download is not possible). But the Hover tooltips are mixed up. They should be exchanged against each other.

**Comment by matiasilva** [comment]
Hi, can you please follow the issue format?

**Comment by ffdixon** [comment]
Ahh -- your right, they should be reversed.

![image](https://user-images.githubusercontent.com/290351/97630880-8fd29280-1a06-11eb-9c2d-f9466c7d1cf4.png)
