### ISSUE TITLE
Access local server file for remote presentation 

### ISSUE THREAD

**Issue by pedped** [bigbluebutton/bigbluebutton#10751]
I am adding many presentation file while creating a meeting. after that BBB download the file. so I need to point to local file instead of the remote file. how that is possible.

my PDF files in server is under /bigbluebutton/ folder that can be accessed by the URL.

**Comment by matiasilva** [comment]
Hi, please use the mailing lists for these questions: https://docs.bigbluebutton.org/2.2/getting-help.html. This issue tracker is reserved exclusively for bugs and feature requests.
