### ISSUE TITLE
Allow creating only a single Breakout Room

### ISSUE THREAD

**Issue by Skgland** [bigbluebutton/bigbluebutton#10750]
**Is your feature request related to a problem? Please describe.**
For office hours (Sprechzeiten) I would like to use the Main Room as a Waiting Area and a Breakout Room to move individual or groups into to consult in private.
I need to speak those waiting to figure out who is first in line, belongs together and has pressing matters.
But currently I am forced to create at least 2 Breakout Rooms even though I only need one.

**Describe the solution you'd like**
Lower the minimum amount of Breakout Rooms to one.

**Describe alternatives you've considered**
Add a proper waiting area when *Require moderator approval before joining* is set,
so that the above mentioned is fulfilled.

**Additional context**
No option for 1 Breakout Room:
![bbb-create-breakout-room-censored](https://user-images.githubusercontent.com/3877590/97617197-c7990480-1a1d-11eb-9e60-518e8a2462ad.png)

Manually adding 1 option per Browsers DevTools doesn't work:
![bbb-create-breakout-room2-censored](https://user-images.githubusercontent.com/3877590/97617194-c7006e00-1a1d-11eb-8a9a-9102fb31ff8f.png)

Current view when joining a room with *Require moderator approval before joining*:
![bbb-require-mod-approval-censored](https://user-images.githubusercontent.com/3877590/97616526-f4005100-1a1c-11eb-8827-45da6b09de42.png)

**Comment by matiasilva** [comment]
What is wrong with the current waiting area?

**Comment by Skgland** [comment]
![bbb-require-mod-approval-censored](https://user-images.githubusercontent.com/3877590/97616526-f4005100-1a1c-11eb-8827-45da6b09de42.png)
Is there a waiting area for a live room other than what is shown in the image above?

First I stated that I would like to interact with those waiting, which is not possible currently, to determine who to let in next.
Second a user might think the page is broken with how it currently looks and leave without reading.

**Comment by matiasilva** [comment]
Yeah, there is. Try it on demo.bigbluebutton.org.

**Comment by Skgland** [comment]
Same thing there, once the guest clicks join they get this: 
![image](https://user-images.githubusercontent.com/3877590/98314980-6c47b300-1fd7-11eb-90e1-6664a59573da.png)

**Comment by matiasilva** [comment]
The waiting area is visible on the moderator's side:
![image](https://user-images.githubusercontent.com/23108156/98331810-4a5d2900-1ff5-11eb-9cae-1748ab183e48.png)

**Comment by Skgland** [comment]
Yes, I am aware of what the current Waiting Area looks from the Moderators/Hosts point of view,
This doesn't change how it looks for the waiting participants nor does it solve my Problem of not being able to interact with the waiting to determine whom to accept and who should continue to wait. 
As stated currently using a normal Room with no "Require Moderator approval to join" option set as a replacement for the Waiting Room and a Breakout Room as the actual Room works. It is just a tid annoying that I always need to create two breakout Rooms if I only need one.

**Comment by matiasilva** [comment]
The waiting area *has* been changed and improved, see #9271.

>  nor does it solve my Problem of not being able to interact with the waiting to determine whom to accept and who should continue to wait.

How so? You can approve/deny via the host's point of view.

**Comment by schristoforou** [comment]
> The waiting area _has_ been changed and improved, see #9271.
> 
> > nor does it solve my Problem of not being able to interact with the waiting to determine whom to accept and who should continue to wait.
> 
> How so? You can approve/deny via the host's point of view.

I think @Skgland is talking about interacting with the users waiting to be accepted, something we would like to have as well. Right now, for our exams, we have to have a main room for attendees talking to a secretary, and then being transferred to a breakout room for the exam. It would be much better if the exam room was the main room and the secretary could somehow interact with the people waiting "outside" in order to allow them into the exam.
