### ISSUE TITLE
2.3 screenshare start/end notifications are showing the opposite

### ISSUE THREAD

**Issue by daminebenq** [bigbluebutton/bigbluebutton#10758]
starting notification shows "screenshare has ended"
![image](https://user-images.githubusercontent.com/5144311/97754885-0b037980-1ad7-11eb-90e0-7591d599136c.png)

ending notification shows "screenshare has started"
![image](https://user-images.githubusercontent.com/5144311/97754909-122a8780-1ad7-11eb-8165-0619467859bd.png)

**Comment by antobinary** [comment]
I can no longer reproduce this on 2.3-alpha6. @daminebenq can we close this?

**Comment by daminebenq** [comment]
closing it, it was fixed in #10983
