### ISSUE TITLE
HTML(React) client files not working.

### ISSUE THREAD

**Issue by Naman-2001** [bigbluebutton/bigbluebutton#10759]
I am trying to integrate bigbluebutton in my react project. I downloaded the html files from improved-eureka github repo but its not working.There is not npm package for the same too. Can you tell me how can I solve this issue of integrating bigbluebutton in reactjs.

**Comment by matiasilva** [comment]
Please familiarize yourself with the architecture of BigBlueButton and the HTML5 React client. Further questions should be directed to the mailing list per the advice on https://docs.bigbluebutton.org/2.2/getting-help.html.
