### ISSUE TITLE
v2.3dev - Error 1020 (Media can not reach the server) when using webcam

### ISSUE THREAD

**Issue by mohghm** [bigbluebutton/bigbluebutton#10752]
Camera share is buggy, working sometimes and sometimes not, in websockets connection, the server acknowledges the data and returns the connection id as well as the camera id.

Just open your camera in a room.

Also when screensharing there is no error but infinite loading

An error appears as shown:
![image](https://user-images.githubusercontent.com/73681073/97658026-fc37ab00-1a73-11eb-87f8-ac727247d804.png)

From what appears as well there are 2 wss connections to the same node from kurento doing the exact same thing of ping/pong as well as sending and receiving the same data when sharing a screen or a video cam.
![image](https://user-images.githubusercontent.com/73681073/97659454-ba106880-1a77-11eb-93a5-d1a1c56f84c5.png)

Server version:
BigBlueButton Server 2.3.0-dev (1323)
Server is a fresh ubuntu 18.04 install and bbb was installed from the bbb-install.sh with the version specified as bionic-230-dev
No TURN server, no restrictive firewall, Audio is working correctly, not an issue of a browser block of WebRTC, 

Client
 - OS: Windows 10 19041
 - Browser Chrome 
 - Version 86.0.4240.111

PS. I have multiple BBB v2.2 servers running on the same server configuration without any issues

**Comment by glotovdanila** [comment]
Hi, I ran into the same problem today. I was able to solve this problem using https://github.com/bigbluebutton/bigbluebutton/issues/8269 . Can you check which stun or turn server you have in the /etc/kurento/modules/kurento/WebRtcEndpoint.conf.ini file ? You can check the specified stun server by "stun serverip: port" if the specified server is unavailable try using free google server: stun2.l.google.com:19302 
It worked for me.

**Comment by mohghm** [comment]
It is not related to TURN, same exact configuration, also audio is working which is over UDP, if the issue is a restrictive NAT or Firewall, the audio shouldn't work either.

**Comment by vog3lm** [comment]
same problem over here.

Open camera in a room leads to Error 1020.
Screensharing in a room leads to no error but infinite loading.
Audio, chat, shared notes etc. works lika charm.

Suprisingly this behaviour occurs only on clients in a particular network.
No Firewall or NAT between this network and the other client networks.


We also had a problem with sharing presentation. 
I only mention that because I don't know if there is a correlation with the issue above. 
These steps solved the presentation sharing issue:

1. copied self-signed cert to `/usr/local/share/ca-certificates` and `/etc/nginx/ssl`
2. add `export NODE_EXTRA_CA_CERTS=/usr/local/share/ca-certificates/[CERT].pem` in `/usr/share/meteor/bundle/systemd_start.sh`
3. `update-ca-certificates`
4. `bbb-conf --restart`

Definitly ran out of ideas, would be great if anyone has one.



Running Big Blue Button on Ubuntu 16.04.7 LTS.

```
bbb-conf --version

bbb-apps                              1:2.2.0-50
bbb-apps-akka                         2.2.0-95
bbb-apps-screenshare                  1:2.2.0-50
bbb-apps-sip                          1:2.2.0-11
bbb-apps-video                        1:2.2.0-48
bbb-apps-video-broadcast              1:2.2.0-8 
bbb-client                            1:2.2.0-40
bbb-config                            1:2.2.0-218
bbb-etherpad                          1:2.2.0-63
bbb-freeswitch-core                   2:2.2.0-113
bbb-freeswitch-sounds                 1:1.6.7-6 
bbb-fsesl-akka                        2.2.0-72
bbb-html5                             1:2.2.0-1058
bbb-mkclean                           1:0.8.7-3 
bbb-playback-presentation             1:2.2.0-33
bbb-record-core                       1:2.2.0-71
bbb-red5                              1:1.0.10-16
bbb-transcode-akka                    2.2.0-8 
bbb-web                               1:2.2.0-142
bbb-webrtc-sfu                        1:2.2.0-105
bigbluebutton                         1:2.2.0-5 
ffmpeg                                7:4.2.4-1ubuntu0.1bbb1~16.04.1
libavcodec58:amd64                    7:4.2.4-1ubuntu0.1bbb1~16.04.1
libavdevice58:amd64                   7:4.2.4-1ubuntu0.1bbb1~16.04.1
libavfilter7:amd64                    7:4.2.4-1ubuntu0.1bbb1~16.04.1
libavformat58:amd64                   7:4.2.4-1ubuntu0.1bbb1~16.04.1
libavresample4:amd64                  7:4.2.4-1ubuntu0.1bbb1~16.04.1
libavutil56:amd64                     7:4.2.4-1ubuntu0.1bbb1~16.04.1
libopusenc0                           0.2.1-1bbb1
libpostproc55:amd64                   7:4.2.4-1ubuntu0.1bbb1~16.04.1
libswresample3:amd64                  7:4.2.4-1ubuntu0.1bbb1~16.04.1
libswscale5:amd64                     7:4.2.4-1ubuntu0.1bbb1~16.04.1
```

Clients run on Windows 10 with Firefox 68.11.0esr

**Comment by robregonm** [comment]
I experienced the same issue after installing v2.3 using bbb-install and STUN server enabled, and the solution was to edit `/etc/kurento/modules/kurento/WebRtcEndpoint.conf.ini`:
```stunServerAddress=127.0.0.1 ;Your STUN Server IP - you can use Google STUN server IP
stunServerPort=12345 ; STUN Server port

externalIPv4=10.10.10.1 ; Your server public IP (for some reason bbb-install put a wrong IP here)
```
I restarted and it worked fine :-)
