### ISSUE TITLE
Give the moderator the ability to see only 5 webcams

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#10763]
**Is your feature request related to a problem? Please describe.**
There are times when an instructor does not want to see 25 webcams.  Currently, the viewers are shown 5 webcams.

**Describe the solution you'd like**
Give the moderator a settings option to only see 5 webcams.

**Describe alternatives you've considered**
We could add some UI to toggle between grid view and top view (only 5 webcams in one row at the top)

**Comment by MariusE** [comment]
Maybe that would be a good feature for every user, not only moderators?

e.g, on lower powered devices you could reduce the amount of visible cams.

Also that "5" value should be configurable in the yaml file, next to the other UI Settings

**Comment by pbdco** [comment]
> Maybe that would be a good feature for every user, not only moderators?
> 
> e.g, on lower powered devices you could reduce the amount of visible cams.
> 
> Also that "5" value should be configurable in the yaml file, next to the other UI Settings

+1

**Comment by prlanzarin** [comment]
Values are already configurable. For every user.
What we lack is a toggle for enabling/disabling it inside the client (and it's basically what's this issue is about).
