### ISSUE TITLE
Turn server link removed after each update

### ISSUE THREAD

**Issue by RealLordK1** [bigbluebutton/bigbluebutton#10762]
**Describe the bug**
It seems that every time I update my server with an apt update && apt upgrade, the link with the turn server is removed. The configuration in /usr/share/bbb-web/WEB-INF/classes/spring/turn-stun-servers.xml is back to the default one.

**To Reproduce**
Update your turn linked bbb server with an apt update && apt upgrade. Look at the config file before and after.

**Expected behavior**
The turn server configuration should stay in place.

**Actual behavior**
The turn server configuration is reseted to the default one.

**Comment by matiasilva** [comment]
I believe https://docs.bigbluebutton.org/2.2/customize.html#automatically-apply-configuration-changes-on-restart solves the issue.

**Comment by ffdixon** [comment]
We've also fixed the issue with packaging so that in 2.2.29 it should properly restore `/usr/share/bbb-web/WEB-INF/classes/spring/turn-stun-servers.xml` after upgrade.

**Comment by RealLordK1** [comment]
> We've also fixed the issue with packaging so that in 2.2.29 it should properly restore `/usr/share/bbb-web/WEB-INF/classes/spring/turn-stun-servers.xml` after upgrade.

Amazing. Thanks for all this great job !
