### ISSUE TITLE
Audio error - errorCode=1004, cause=Incompatible SDP

### ISSUE THREAD

**Issue by sandahtmlteam** [bigbluebutton/bigbluebutton#10761]
User gets "Failure on call"(1004) error on echo test for any conference we create in chromium browser(version 79). The same conference works fine in Chrome and Firefox. I am not sure if this is an issue with the bigbluebutton itself or browser support problem. Anyone else come across this problem?

> ERROR: clientLogger: Audio error - errorCode=1004, cause=Incompatible SDP

**Comment by mpellicer** [comment]
Yes, we're getting this error more frequently since we upgraded from 2.2.23 to 2.2.28, looks like they fixed the problem. We're using google as STUN server and works better.

**Comment by basisbit** [comment]
Closing this as duplicate and not enough information for responding to this issue. The issue should be fixed by installing a current version of BigBlueButton (which has some fixes regarding ipv4/ipv6 handing).
