### ISSUE TITLE
Overlapping phrases "You're now muted" and "You're currently the only person in this conference" on join. 

### ISSUE THREAD

**Issue by greenycat** [bigbluebutton/bigbluebutton#10767]
Many students when they join have noisy environment & setting **"Mute users when they join"** is my default for all rooms. 
My guess this feature is popular, otherwise **your lecture is always interrupted** on rejoins after downlinks.

And here comes bad experience:
The owner of the room or whoever from students who started room session, **if joins first** gets two audio notifications simultaneously: 

- "You're now muted" 
- "You're currently the only person in this conference". 

They overlap each other: 
Muting the owner of room is expected behaviour.
The overlapping of voice messages is annoying behaviour. 
This pleasant voice messages should come **next to each other**, not at a time. 

Issue concerns 2.2.27 and 2.3-dev

[Overlap sample](https://s2.khimich.org/temp/overlap_sample.wav)
Sorry in advance for external link, I couldn't attach wav/mp3 file directly.

**Comment by ffdixon** [comment]
We're looking into replacing the _you are now muted_ and _you are now unmuted_ phrases with simple sounds.

**Comment by ffdixon** [comment]
We have two sounds that you can use to replace these phrases

  https://ubuntu.bigbluebutton.org/files/conf-muted.wav
  https://ubuntu.bigbluebutton.org/files/conf-unmuted.wav

If you use these two sounds to overwrite the following two files

 /opt/freeswitch/share/freeswitch/sounds/en/us/callie/conference/48000/conf-muted.wav
 /opt/freeswitch/share/freeswitch/sounds/en/us/callie/conference/48000/conf-unmuted.wav

you shouldn't have the issue with overlap.
