### ISSUE TITLE
Breakout Rooms, include moderators in randomly-assign to rooms

### ISSUE THREAD

**Issue by Braehler** [bigbluebutton/bigbluebutton#10773]
**Describe the bug**
When you create several breakoutrooms and you want to assign the users randomly it´s not possible if you and one or more  person with "moderator" rights

**To Reproduce**
1. Go to 'a meeting of your choise'
2. Have at least two users with the right of "moderator"
3. Click on 'Create breakout rooms'
4. Click on randomly assign
5. When you click on randomly assign, nothing happens

**Expected behavior**
Should be the same behavior if as if you just have only one moderator and some viewers, so you can randomly assign all users

**Actual behavior**
When you have two users with the "morderator rights" and the rest have viewer rights, you can not randomly assign the users to the breakout rooms 

**Screenshots**

**BBB version (optional):** 
2.2.28
BigBlueButton continually evolves. Providing the version/build helps us to pinpoint when an issue was introduced.
Example:
$ sudo bbb-conf --check | grep BigBlueButton
BigBlueButton Server 2.2.2 (1816)

**Desktop (please complete the following information):**
 - OS: [Windows, Mac]
 - Browser [Firefox, Chrome, Safari]
 - Version [all the latest stable versions]

**Smartphone (please complete the following information):**
 - Browser [e.g. stock browser, Safari]

**Additional context**

**Comment by matiasilva** [comment]
I believe this is intentional behavior, and not a bug just fyi.

**Comment by kuehn-innerste** [comment]
It would be helpful to have a message to the user/moderator when this behavior is intended.
I just witnessed a moderator not knowing about this and thinking that this random assignment is broken.

**Comment by ffdixon** [comment]
Hmm .. just tried this on demo (running a dev build of 2.2.31) and was not able to reproduce.  Can you try it on demo and let us know if you encounter the error there.

**Comment by wmchris** [comment]
we can confirm this bug on 2.2.30.

**Comment by daminebenq** [comment]
Hey guys,
I just tried this on 2.2.30 with 2 Moderators and 1 Viewer
I started creating Breakout rooms from Moderator1 and clicked Randomly Assign. The expected behaviour happened which is to see the Viewer getting randomly placed to one of the Breakout rooms. Which means that there are no problems at all with randomly assigning Viewers, because only Viewers should be randomly assigned and none of the Moderators should get assigned.

**Comment by baumschubser** [comment]
> only Viewers should be randomly assigned and none of the Moderators should get assigned

In communities where people trust each other and want to avoid additional technical problems, they often make all users moderators, at least in my experience. In 99% of my BBB calls vandalism is unimaginable, so "all users are mods" setting is the default. This issue demonstrates that people assign moderator roles differently, so maybe both options should be considered. A radiobutton "assign all members"/"assign only users"?

**Comment by antobinary** [comment]
Reading the previous comments and talking to @gustavotrott , looks like the behavior is intentional. However, we can consider a setting similar to 

```
   breakouts:
      sendInvitationToIncludedModerators: false
```

where we include moderators in the auto assign...
Or add yet another checkbox to the menu
[ ] Include moderators when auto-assigning to rooms

**Comment by baumschubser** [comment]
Since this issue was already considered for milestone 2.4, I assume that may be deprioritized but not rejected altogether, so I take stalebot's activity as opportunity to "ping" this request with this comment, to avoid it's automatic closure.

Maybe we see an implementation like this suggestion in the future..?

> Reading the previous comments and talking to @gustavotrott , looks like the behavior is intentional. However, we can consider a setting similar to
> 
> ```
>    breakouts:
>       sendInvitationToIncludedModerators: false
> ```
> 
> where we include moderators in the auto assign... Or add yet another checkbox to the menu [ ] Include moderators when auto-assigning to rooms

**Comment by antobinary** [comment]
We transitioned to a plugin for this functionality in BBB 3.0. TODO -- transfer this to the plugin related issues. Related #19785
