### ISSUE TITLE
Moderator should be able to enter his bbb room

### ISSUE THREAD

**Issue by iznakurnozh** [bigbluebutton/bigbluebutton#10776]
related to #10775

**Is your feature request related to a problem? Please describe.**
When the room limit of members is reached and moderator has to reload page, (s)he cannot enter the room anymore.

**Describe the solution you'd like**
Moderator should have special rights to always be able to enter the room. Otherwise e.g. students are waiting for a lecturer, who cannot reach them anymore.

**Comment by erisd** [comment]
Its also an Issue for us, would be great if its fixed.

**Comment by pedrobmarin** [comment]
Is this something associated with Greenlight? If it is, I recommend moving this discussion there. BigBlueButton already have a permissive policy for page refreshes.
