### ISSUE TITLE
Bigbluebutton 2.3.0-dev (1323) missing Export current pad as Word, PDF, ODF

### ISSUE THREAD

**Issue by dolevu** [bigbluebutton/bigbluebutton#10778]
Bigbluebutton 2.3.0-dev (1323) missing Export current pad as Word, PDF, ODF

Libreoffice is running as docker image, so I think the value here need to be changed
/usr/share/etherpad-lite/settings.json
from 
"soffice": "/usr/bin/soffice" --> to something else?

**Comment by ffdixon** [comment]
Thanks for pointing this out.  There will need to be some adjustments for Etherpad to connect to the Libreoffice running in docker.

**Comment by antobinary** [comment]
Resolved by https://github.com/bigbluebutton/bigbluebutton/pull/12008
And also the `soffice` has been afterwards updated in https://github.com/bigbluebutton/bigbluebutton/releases/tag/v2.3-rc-1 
`"soffice": "/usr/share/bbb-libreoffice-conversion/etherpad-export.sh"`
