### ISSUE TITLE
Simultaneous webcams with horizontal scrolling strip

### ISSUE THREAD

**Issue by aguerson** [bigbluebutton/bigbluebutton#10772]
Hi guys,
I hope you are fine.
The cold is coming ;)

I have a question / request.
Now when more than 6 webcams are enabled, there is now a horizontal scrolling strip to show webcam.

Is that a new functionality ? Since which version ?
Maybe I didn't see something ?

My instance is in version 2.2.24 with 3 KMS activated.

Thanks,
Regards,

**Comment by aguerson** [comment]
Is there any method to modify that and to show all the webcam or more than 6 webcams ?

**Comment by matiasilva** [comment]
Hi, the information you requested is available publicly in the GitHub releases page: https://github.com/bigbluebutton/bigbluebutton/releases/tag/v2.2.23. For future questions like this, please use the mailing lists as is described on https://docs.bigbluebutton.org/2.2/getting-help.html.

**Comment by aguerson** [comment]
@matiasilva Thanks.
I missed it. :'(

https://github.com/bigbluebutton/bigbluebutton/blob/v2.2.23/bigbluebutton-html5/private/config/settings.yml#L203-L217

Regards

**Comment by aguerson** [comment]
The reason I missed it => it is my first time that I am a simple user viewer and not as moderator !
