### ISSUE TITLE
webcam buttons not clickable on iPad in 2.3-dev

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#10779]
**Describe the bug**

**To Reproduce**
1. Use iPad running iOS 14.x to join a 2.3-dev meeting
2. Try and click the share webcam button

**Expected behavior**
Share webcam dialog appears

**Actual behavior**
No response.

**Comment by KDSBrowne** [comment]
Can anyone confirm this is still an issue? I was not able to reproduce.

**Comment by ffdixon** [comment]
Unable to reproduce on latest build -- closing.
