### ISSUE TITLE
Post pre-composed question. Quicker and far efficient than polling.

### ISSUE THREAD

**Issue by greenycat** [bigbluebutton/bigbluebutton#10771]
### Background of idea
Based on the on the quarantine experience with BBB, I decided to share one more idea for enhancement:
I post questions sometimes to keep my students attached to the lecture and to make it more interactive.
It's yet another way to get student involved, make them awake & turn students into active participants.
We need to seek some substitutions of those advantages of rithorics, mimics, room control which we had before quarantine.
If question if poorly answered by majority we return back to deeper explanation, so, room feedback is a must.

### What is present:
![4](https://user-images.githubusercontent.com/1878503/98178849-253dbd00-1f06-11eb-910b-fca13e04e7e5.png)
_Fig. 1 Dialog for polling_
Existing polling is good for its own purposes but has some disadvantages for schooling or teaching:
* Typing in some extended options is time consuming, all are waiting...
* Targeting each field with mouse and c&paste takes additional 10-15 seconds.
* All c&pastes are real pain when you use graphic tablet for drawing as mouse, need to grab mouse 
* Many sleepy and not attentive participants wake up from popup sound and after being insufficiently attentive 
keep re-askin what was the question or you keep repeating question many times if you have crowd of people.
* Modal window covers the question (even if you predicted it on slide)
* Sometimes, during the lecture for another group of students you find, that prepared slide with question is too elementary for this group, so you skip it, making bad experience with lecture.

### What is suggested:
To add another module solely for questioning, where text of question is parsed from single textarea field.
It can be used as far more convenient tool to repeat what was discussed few minutes ago before moving to next question.
Pasting all together is fast and convenient, nobody waits. Many teachers are not computer nerds, they type or use mouse slo-o-owly.

![1](https://user-images.githubusercontent.com/1878503/98177399-3933ef80-1f03-11eb-98fa-3784fbd7217d.png)
_Fig. 2 Suggested integration in UI_

![3](https://user-images.githubusercontent.com/1878503/98180269-26bcb480-1f09-11eb-997a-484fdc18c3c8.png)
_Fig. 3 Suggested UI for pasting entire question which is parsed.
Before display instructor may privately preview it if there are any doubts about input syntax_

### Further enhancement
This module can be killing feature for teaching & assessment control if percentage of correct answers at the end of lesson will be shown with ability tor teacher to export it to txt file. Mixing of options is also to be considered, at least it will make it a little harder to cheat. Of course, questions without correct options (those are just for interactions and understanding if students need more explanation) do not count, and, questions perhaps should be with one correct option for quicker development.

**Example:**
```
Questions asked in conference: 34
Room name: Sea pollution
Conference started: 13:05 12 May 2019 

Participants:
Ronald Decosta - 25%
Michael Brown - 78%
Ray Walker - 89%
Gilbert Mayes - 50%
```

It quite complies with BBB policy not to keep any user files attached to the system. After lesson room is clean, no external databases... But as summary we get completed school/college/university lesson with assessment.

**Comment by matiasilva** [comment]
On your last point, the poll results are available in the `events.xml` file, so you could extract that information presently if you wanted to.

**Comment by hiroshisuga** [comment]
related to #10631

**Comment by lucas12433** [comment]
A good export function, that everyone can use (not over a complex export of some files,...) would be a killer feature against Zoom, webex,...

But at the moment there isn't such a feature. Where is the events.xml located?

**Comment by antobinary** [comment]
Possibly implemented via https://github.com/bigbluebutton/bigbluebutton/pull/15607
