### ISSUE TITLE
Sticky notes on whiteboard

### ISSUE THREAD

**Issue by hiroshisuga** [bigbluebutton/bigbluebutton#10770]
**Is your feature request related to a problem? Please describe.**
People do a collaborative discussion on the whiteboard. Sticky note on a slide would be useful.

**Describe the solution you'd like**
Sticky notes that can be moved by simple dragging. 

**Additional context**
Dragging every annotation would be ideal, although technically difficult. Sticky note with a rectangle background is probably feasible. MS Whiteboard starts to provide it.

**Comment by iSamof** [comment]
Given the rise of Agile methodology (with Scrums/Daily Stand-ups/Workshops) this feature would be really helpful to mimic the real life operations of a great many collaborative teams.

**Comment by Thorgrimson** [comment]
Maybe this: https://github.com/bigbluebutton/bigbluebutton/issues/10084 could be a Solution?

**Comment by ramonlsouza** [comment]
closed by #14994 (sticky notes available in BBB 2.6 with tldraw whiteboard)
