### ISSUE TITLE
Redirection without an error message when a bbb room is full

### ISSUE THREAD

**Issue by iznakurnozh** [bigbluebutton/bigbluebutton#10775]
label:"User Experience (UX)"
label:"User Interface (UI)"

**Describe the bug**
When one tries to enter a BBB room after max limitation of members was reached, no error gets raised and one finds himself on the starting page.

**Expected behavior**
An infotext like "The bbb room is already full, you cannot enter it"

**Comment by pedrobmarin** [comment]
This information already exists https://github.com/bigbluebutton/bigbluebutton/blob/a1d6ad3e299641ad84445afca198fcfcefd02cd0/bigbluebutton-web/grails-app/controllers/org/bigbluebutton/web/controllers/ApiController.groovy#L467 It's up to the front-end to use it.
