### ISSUE TITLE
Text box on whiteboard not working

### ISSUE THREAD

**Issue by Braehler** [bigbluebutton/bigbluebutton#10774]
**Describe the bug**
The textbox field on the whiteboard does not work. If you try to add some text here, the box is gone, and you can not see anything

**To Reproduce**
1. Go to 'a meeting of your choise'
2. Click on 'Tools'
3. Choose 'Text'
4. Make a textbox
5 When you click into the textbox to write something, the box disappears 

**Expected behavior**
When you click into the textbox, it should be visible to see what and where the person is writing some text. also it should be movable 

**Actual behavior**
AS soon as you click into the textbox, it disappears and you are not able to write some text. If you try to move it, you can´t do anything, because the box is gone

**Screenshots**

**BBB version (optional):**

BigBlueButton Server 2.2.28

**Desktop (please complete the following information):**
 - OS: [Windows, Mac]
 - Browser [Firefox, Chrome, Safari]
 - Version [latest stable versions]

**Smartphone (please complete the following information):**
 - Browser [e.g. stock browser, Safari]

**Additional context**

**Comment by matiasilva** [comment]
Can you please fill out the remainder of the issue request? The textbox feature works in the current version of BBB so it must be something specific to your case.

**Comment by lonesomewalker** [comment]
Nope, can replicate permanently on Firefox.

**Comment by lonesomewalker** [comment]
Neither on 2.2.31 nor on 2.3-current it is possible to use the text tool on whiteboard.
FF latest, OS Windows (7,8,10)

**Comment by mantridereso** [comment]
We’ve been faced with the same problem in 2.3-alpha5 and FF today - can’t reproduce bug in Chrome, however.
I’m going to take a closer look at it within the next few days, as this feature is crucial for one our customer projects next week.

**Comment by pedrobmarin** [comment]
Had the same problem friday at one of the 2.2 develop servers.
FF 85.0.0, OS Linux

**Comment by antobinary** [comment]
Most likely this was introduced by or is tightly related to https://github.com/bigbluebutton/bigbluebutton/pull/11207
(which was done on 2.3 and propagated back to 2.2)
Hoping that @KDSBrowne (first to give it a try) will be able to resolve it on 2.3 and we'll propagate to 2.2 again.

**Comment by mcibk** [comment]
This bug also exists in 2.2.32 / .33
I can reproduce it on our own servers and on https://test.bigbluebutton.org/ (tested with firefox 85)
chrome/chromium works

Can you please merge this to 2.2.x?
