### ISSUE TITLE
Polls are not visible in full screen mode

### ISSUE THREAD

**Issue by iznakurnozh** [bigbluebutton/bigbluebutton#10783]
label:"User Interface (UI)"

**Is your feature request related to a problem? Please describe.**
When the presentation slides are miximized to full screen user does not see a currently published poll.

**Describe the solution you'd like**
It would be nice to be able to see polls and vote without exiting the full screen mode.

**Comment by antobinary** [comment]
When I tried to reproduce this it actually looked like the issue is that if you expand the presentation you won't see the _buttons to vote_ rather than the poll result. We can possibly overlay the polling buttons on top of an expanded presentation
