### ISSUE TITLE
recoding stopped working (bbb-rap-starter.service)

### ISSUE THREAD

**Issue by Bharat-vyas** [bigbluebutton/bigbluebutton#10782]
**Describe the bug**
We have installed bbb-2.3-dev in ubuntu 18.04 (Bionic Beaver), everything was working as expected at first time.
But after making the changes in UFW and restarting the bbb (bbb-conf --restart) one service "bbb-rap-starter.service" is not running. 

We have tried to start that service manually, and even tried with running the service in frount-ground mode (/usr/local/bigbluebutton/core/scripts/rap-starter.rb)
Still it is not starting.
Due to this issue we are unable to see the recordings in greenlight .

**While checking the logs it is showing -** 
bbb-rap-starter.service: Main process exited, code=exited, status=1/FAILURE
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:warning: constant Gem::ConfigMap is deprecated
/usr/local/bigbluebutton/core/scripts/rap-starter.rb:95:in `block in <main>':undefined local variable or method `recording_id' for main:Object (NameError)
Did you mean?  recording_dir
from /usr/local/bigbluebutton/core/scripts/rap-starter.rb:94:in `each'
from /usr/local/bigbluebutton/core/scripts/rap-starter.rb:94:in `<main>'

**To Reproduce**
1. Install bbb-2.3-dev in ubuntu 18.04 (ufw was stopped while installing) 
2. systemctl status bbb-rap-starter.service
3. Restart UFW
4. Restart BBB (bbb-conf --restart)
5. systemctl status bbb-rap-starter.service

**Expected behavior**
"bbb-rap-starter.service" service should not be affected

**Actual behavior**
But after restarting ufw and bbb, "bbb-rap-starter.service" in not starting

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04.5 LTS
 - bbb-2.3-dev
-  greenlight:v2 (docker)
![bbb](https://user-images.githubusercontent.com/43302156/98368527-81672500-205d-11eb-9c14-83d05679dec8.png)

**Comment by hostingnuggets** [comment]
@Bharat-vyas the solution to your issue is meniotned here: https://github.com/bigbluebutton/bigbluebutton/issues/10638#issuecomment-717339548

@matiasilva & others of BBB, it would be great to integrate this solution in the Ubuntu packages of BBB 2.3... Cheers!

**Comment by fcecagno** [comment]
There has been many bug fixes and improvements on the recording system on 2.3, this is most probably the case for this issue as well. @Bharat-vyas would you please try to reproduce this in the release? Is this still an issue for you?
