### ISSUE TITLE
Ayuda Error 404 urgente, help error 404

### ISSUE THREAD

**Issue by Luisral** [bigbluebutton/bigbluebutton#10780]
BigBlueButton Server 2.2.28 (2210)
                    Kernel version: 4.4.0-193-generic
                      Distribution: Ubuntu 16.04.7 LTS (64-bit)
                            Memory: 14377 MB
                         CPU cores: 8

/usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties (bbb-web)
       bigbluebutton.web.serverURL: https://colrioclaro.ddns.net
                defaultGuestPolicy: ALWAYS_ACCEPT
                 svgImagesRequired: true

/etc/nginx/sites-available/bigbluebutton (nginx)
                       server name: colrioclaro.ddns.net
                              port: 80, [::]:80
                              port: 443 ssl
                    bbb-client dir: /var/www/bigbluebutton

/var/www/bigbluebutton/client/conf/config.xml (bbb-client)
                Port test (tunnel): rtmp://colrioclaro.ddns.net
                              red5: colrioclaro.ddns.net
              useWebrtcIfAvailable: true

/opt/freeswitch/etc/freeswitch/vars.xml (FreeSWITCH)
                       local_ip_v4: 192.168.0.x
                   external_rtp_ip: 189.127.166.32
                   external_sip_ip: 189.127.166.32

/opt/freeswitch/etc/freeswitch/sip_profiles/external.xml (FreeSWITCH)
                        ext-rtp-ip: $${external_rtp_ip}
                        ext-sip-ip: $${external_sip_ip}
                        ws-binding: :5066
                       wss-binding: 189.127.166.32:7443

/usr/local/bigbluebutton/core/scripts/bigbluebutton.yml (record and playback)
                     playback_host: colrioclaro.ddns.net
                 playback_protocol: https
                            ffmpeg: 4.2.4-1ubuntu0.1bbb1~16.04.1

/etc/bigbluebutton/nginx/sip.nginx (sip.nginx)
                        proxy_pass: 189.127.166.32

/usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml (Kurento SFU)
                        kurento.ip: 192.168.0.x
                       kurento.url: ws://127.0.0.1:8888/kurento
                    kurento.sip_ip: 192.168.0.x
                    localIpAddress: 192.168.0.x
               recordScreenSharing: true
                     recordWebcams: true
                  codec_video_main: VP8
               codec_video_content: VP8

/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml (HTML5 client)
                             build: 1058
                        kurentoUrl: wss://colrioclaro.ddns.net/bbb-webrtc-sfu
                  enableListenOnly: true

# Potential problems described below
# Warning: API URL IPs do not match host:
#
#                                IP from ifconfig: 192.168.0.x
#  /var/lib/tomcat7/demo/bbb_api_conf.jsp: colrioclaro.ddns.net

# Warning: The setting of 189.127.166.32 for proxy_pass in
#
#    /etc/bigbluebutton/nginx/sip.nginx
#
# does not match the local IP address (192.168.0.x).
# (This is OK if you've manually changed the values)

# Warning: The API demos are installed and accessible from:
#
#    https://colrioclaro.ddns.net
#
# and
#
#    https://colrioclaro.ddns.net/demo/demo1.jsp
#
# These API demos allow anyone to access your server without authentication
# to create/manage meetings and recordings. They are for testing purposes only.
# If you are running a production system, remove them by running:
#
#    apt-get purge bbb-demo

**Comment by matiasilva** [comment]
Hi, please respect the issue format and the guidelines for getting help: https://docs.bigbluebutton.org/2.2/getting-help.html
