### ISSUE TITLE
Waiting room: user reappearance

### ISSUE THREAD

**Issue by iznakurnozh** [bigbluebutton/bigbluebutton#10786]
**Describe the bug**
In BBB rooms, where participants have to wait for the moderator approval to enter it, there is a timeout of approx. 8 minutes. After that they have to reenter the waiting room and their name appears in the moderator list of waiting persons an additional time. Afterwards the moderator does not know which names in the list refer to accually waiting users and which ones are "empty" names.

**Expected behavior**
It would be great when the user name could be deleted from the waiting list when (s)he leaves the room and is not waiting anymore.

**Comment by pedrobmarin** [comment]
Fixed in v2.3
