### ISSUE TITLE
Show the maximum size allowed when uploading a file.

### ISSUE THREAD

**Issue by MiStErLu** [bigbluebutton/bigbluebutton#10788]
Hi,

I would like to know if it's possible to show that maximum size of a publication when a user want to upalod one.

It'is possible to modify the text, or something like that :

In this file ?
    /usr/share/meteor/bundle/programs/server/assets/app/locales/

And doing something like that : Adding that "**The maximum size allow is {0}Mb**" at the end ?

    "app.presentationUploder.message": "As a presenter you have the ability to upload any office document or PDF file.  We recommend PDF file for best results. Please ensure that a presentation is selected using the circle checkbox on the right hand side.",

Thanks a lot !

MiStErLu

**Comment by antobinary** [comment]
Addressed in 2.3.0 via https://github.com/bigbluebutton/bigbluebutton/pull/12100 and https://github.com/bigbluebutton/bigbluebutton/pull/11956

![Screenshot from 2021-05-07 10-33-55](https://user-images.githubusercontent.com/6312397/117465704-f4bff580-af1f-11eb-8fb9-5c5ede7c8888.png)
