### ISSUE TITLE
Waiting room: infotext for kicked out users

### ISSUE THREAD

**Issue by iznakurnozh** [bigbluebutton/bigbluebutton#10787]
label:"User Interface (UI)"

**Is your feature request related to a problem? Please describe.**
related to  #10786
After timeout users get kicked out from the waiting room. Currently it looks as following: 
![grafik](https://user-images.githubusercontent.com/38284875/98370951-ac408180-203b-11eb-93f7-a0ba0eeb8c78.png)

**Describe the solution you'd like**
An informative text instead, like "Timeout. You can reenter the room with following link: https://xxx"

**Comment by koenr** [comment]
Releated to #10649 - it would be nice to have these messages translated.

**Comment by pedrobmarin** [comment]
v2.3 already implemented feedback improvements. Please try it out.
