### ISSUE TITLE
Echo test thumb down button replacement with settings button

### ISSUE THREAD

**Issue by TheJJ** [bigbluebutton/bigbluebutton#10794]
Users apparently never click on the red thumb-down button in case their echo test fails.
This is likely to the lack of knowledge that the thumb-down-button will open a settings dialog where one can select the audio source etc.

Improvement-suggestion: Replace the thumb-down by a settings button so users are aware that they can change and probably fix things there.

**Comment by matiasilva** [comment]
Merging with #9698.
