### ISSUE TITLE
Presenter icon is not visible

### ISSUE THREAD

**Issue by greenycat** [bigbluebutton/bigbluebutton#10798]
**Describe the bug**
A presenter icon is not visible in mobile version.

**To Reproduce**
Open users list on mobile device and try to locate presenter icon.
Background for presenter icon is missing.

**Expected behavior**
Should be visible like here:
![02_expected_small](https://user-images.githubusercontent.com/1878503/98469741-16972480-21ea-11eb-82d4-8b00232fb5d5.png)

**Actual behavior**
Not visible like here:
![00](https://user-images.githubusercontent.com/1878503/98469805-742b7100-21ea-11eb-9853-f9056e560b72.png)
![01](https://user-images.githubusercontent.com/1878503/98469806-755c9e00-21ea-11eb-942a-28ee2aa8061f.png)

**BBB version (optional):**
BigBlueButton Server 2.2.28 (2210)

**Desktop (please complete the following information):**
 - N/A

**Smartphone (please complete the following information):**
iPhone 7+ (Safari browser, iOS 14.1)

**Comment by ffdixon** [comment]
Good catch!

**Comment by pedrobmarin** [comment]
#9978

**Comment by mrkeksi** [comment]
Can not reproduce on iPhone with latest dev https://test23.bigbluebutton.org/
