### ISSUE TITLE
Waiting room: smartphone UI: scrolling option is disabled

### ISSUE THREAD

**Issue by iznakurnozh** [bigbluebutton/bigbluebutton#10791]
**Describe the bug**
related to #10786

When a room moderator views a waiting list on some mobile devices the scrolling option is not enabled. On the following img only 2 first membes are visible whereas there are 5:

![grafik](https://user-images.githubusercontent.com/38284875/98373987-54f0e000-2040-11eb-9ea5-04df65b8ec2d.png)

**Smartphone (please complete the following information):**
 - Device: Huawei Mate 10 Lite
 - OS: Android
 - Browser Chrome 86.0.4240.185

**Comment by franzgratzer** [comment]
I can confirm this issue on Firefox and Chromium on the desktop (on Debian stable and Ubuntu 18.04).

**Comment by sebastianberm** [comment]
This issue is visible with any amount of users, depending on the screen size. 
There should probably be an overflow: auto element on the generated div. But I'm not entirely sure where this should be changed.

**Comment by pedrobmarin** [comment]
This should be fixed in v2.3
