### ISSUE TITLE
Breakout Rooms improvements

### ISSUE THREAD

**Issue by MudrekaBohra** [bigbluebutton/bigbluebutton#10797]
1) An option to close single breakout room right now we can only close all the breakout rooms together but if you only want to close selected breakout room it is not possible
2) An option to unmute any participant in the breakout room by the moderator currently if a participant is in the breakout room then there is no option to unmute them by the moderator
3) Also an option for the participant to come back to the master meeting without breakout room getting closed
4) If possible walkie talkie mode in that scenario if a teacher want to speak to only a particular student in the meeting the teacher would select that student name then speak then only that particular student will be able to hear them

**Comment by hex-m** [comment]
Hi @MudrekaBohra!

Thanks for your input.

> An option to unmute any participant in the breakout room by the moderator currently if a participant is in the breakout room then there is no option to unmute them by the moderator

There are no permissions in breakout rooms. Nobody can mute/unmute/kick other users. related: https://github.com/bigbluebutton/bigbluebutton/issues/8652 https://github.com/bigbluebutton/bigbluebutton/issues/11065

> Also an option for the participant to come back to the master meeting without breakout room getting closed

This is possible by choosing "Leave Meeting" or "Logout" in the breakout room.

The other two points seem like interesting feature requests. I would suggest you create to separate issues for them and close this one. Having only one topic in an issue makes it easier.

**Comment by prlanzarin** [comment]
I see you've started splitting the enhancement requests into separate issues (which is the _proper_ way). So I'm closing this.
