### ISSUE TITLE
guest access approbation

### ISSUE THREAD

**Issue by slafarguette** [bigbluebutton/bigbluebutton#10793]
**Describe the bug**
When moderator approbation is configured with greenlight, when the guest try to join using link he is redirected on this uri : /client/guest-wait.html?sessionToken=vsx6nmh0eagc2rch

should be 

/html5client/guest-wait.html?sessionToken=vsx6nmh0eagc2rch

Reproductibility always

**Comment by matiasilva** [comment]
Hi, can you please post your support query to the mailing lists per the instructions on https://docs.bigbluebutton.org/2.2/getting-help.html
