### ISSUE TITLE
allowDuplicateExtUserid issue Not worked ins version 2.2.28

### ISSUE THREAD

**Issue by mnordesigner62** [bigbluebutton/bigbluebutton#10802]
**Describe the bug**
I update my bigbluebutton v 2.2.26 to 2.2.28 and after that the uniq user can multiple logged in 
in configuration file I set allowDuplicateExtUserid=false but not worked

**Expected behavior**
I use moodle LMS and bigbluebuttonBN plugin and call api with that 

**BBB version (optional):**
BigBlueButton Server 2.2.28 (2210)

**Desktop (please complete the following information):**
 - OS:  Windows
 - Browser Chrome
 - Version 86
 the number of concurrent user about 250 pers 

Please help me to solve it

**Comment by pedrobmarin** [comment]
https://github.com/bigbluebutton/bigbluebutton/issues/9354
