### ISSUE TITLE
Volume slider for live sessions

### ISSUE THREAD

**Issue by VitoDrofenik** [bigbluebutton/bigbluebutton#10814]
I miss the volume slider to set the volume of sound on live sessions similar to the one in the player for recordings.
That would not be a problem if BBB had a client app (such as zoom, MS Teams), where you can set the volume in the volume mixer (Windows) or if browsers would somehow had an option for per-tab volume settings that would be shared across all tabs with the same url (or regex).

**Describe a solution you'd like**
A simple volume slider that controls the volume of sound in a live player.
A plus would be for it to save the setting for future sessions (also on the recording player).

**Comment by dschemp** [comment]
I would like to add that it might be better to change the volume on a per-user level. You could utilize the user menu in the Users panel.
Having a master volume slider is a bit inconvenient when you have multiple people / sessions with different mic volumes for participating users. For that reason it should be possible to not only de- but increase the users output aswell like on a range between 0% (muted) to 150% / 200% with 100% being the default.

**Comment by ffdixon** [comment]
Commenting to keep open.

**Comment by dschemp** [comment]
Commenting to keep open.

**Comment by dschemp** [comment]
Ping.
