### ISSUE TITLE
Audio degradation after setting skipCheck=true option in settings.yml

### ISSUE THREAD

**Issue by kusznerr** [bigbluebutton/bigbluebutton#10812]
We are observing different audio  with skipCheck veriable set to true or false. When skipCheck is set on true , audio quality is significantly degradated (frequent cracks etc). With skipCheck set to false (default option) - audio quality is much better.

Setting done in : /usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml

Option : skipCheck

Expected behavior - no difference in audio quality between both options. 

Devices tested - PC and smartphone.

**Comment by ffdixon** [comment]
This is really strange!  Are you able to verify this first-hand (you can hear the differences yourself)?

**Comment by kusznerr** [comment]
Hello Fred - yes , we've spend some time on this by testing multiple server configurations (GCP / AWS / baremetal etc) and it all boiled to this setting. If you want we can share some samples we recorded.

**Comment by lookas1** [comment]
Fred we have client video and audio captures which we can share but I believe you can test it in your lab to see the difference. We did a multiple test runs with off and on echo test, couldn't believe the results. Do you think different profiles can be loaded with this option?

**Comment by mariogasparoni** [comment]
Which version of bbb are you running? Also, which OS and browser this happens more often.

**Comment by kusznerr** [comment]
Latest BBB version (2.2.28 and 26). Results do not vary on client side , as we are testing it across few of us.

**Comment by dariosera** [comment]
I can confirm the problem. Same results also setting the `userdata-bbb_skip_check_audio` parameter using _join_ API call.
I'm running BBB 2.2.28 on a DigitalOcean c-8 droplet.
Initially I tested with my own voice, then I used a voice recording sent directly to the conference from audio loopback.

**Comment by ffdixon** [comment]
Thanks for the confirmation.  We're going to take a closer look for the FreeSWITCH configuration for the join audio sequence `browser -> echo test -> main room` and `browser -> main room`.

**Comment by mariogasparoni** [comment]
Yes, i can reproduce this too. After listening for a while you notice mic's audio quality is better

**Comment by mariogasparoni** [comment]
Did some tests taking a look at FreeSWITCH, and it seems jitterbuffer is not being set when using skipCheck=true. There's an action on diaplan which sets it, but apparently this has no effect.
Still needs more investigation, i will run a few more tests and update it here

**Comment by mariogasparoni** [comment]
> @ffdixon we have client video and audio captures which we can share but I believe you can test it in your lab to see the difference. We did a multiple test runs with off and on echo test, couldn't believe the results. Do you think different profiles can be loaded with this option?

By changing skipCheck to **true**, you will hit a different dialplan. Although this is a different dialplan , this is intended to set same audio call parameters when skipCheck is **false**. Both skipCheck **true/false** use the same profile: **external**

**Comment by mariogasparoni** [comment]
Just took a closer look on FreeSWITCH. jitterbuffer is being correctly set for both dialplans (those used when skipCheck is true or false).
And after running more tests, i can't really feel much difference, which makes me think if i can really reproduce this problem.
I am running Chrome 86 on Linux (Ubuntu focal) and Safari 13.1.2 on macOS for my tests

@lookas1 can you share your video/audio when showing the problem ? So i can see if i am able to reproduce it.
you can email me: mariogasparoni at gmail

**Comment by lookas1** [comment]
@mariogasparoni apologies it took some time but we decided to make new samples :-) Please check them here:
https://drive.google.com/drive/folders/1snb3u84amrPf7E0UAb473ZY7SaY2wema?usp=sharing

I think names are self-explanatory.

Samples were taken with XBox Game Bar on Win10.

**Comment by kusznerr** [comment]
@mariogasparoni - wanted to check if you were able to validate samples we provided ?

**Comment by mariogasparoni** [comment]
@lookas1 @kusznerr , thanks for the high quality samples you guys provided. Indeed, when echo test is off i can hear some audio 'cracks' during the talk. I took a closer look on the audio process and i couldn't find any difference in dialplans/profiles that could decrease quality when echo test is off.

I am working on general audio improvements, and there's a chance i find a solution for this (can't promise though). In the meantime, can you run a similar test on a different server/setup ? Email me so i can give you access to a private server (running 2.2.29), so you can run a test on it (no need to record this time, and i will make sure echo test is off) and then we eliminate the possibility there's something different in your hardware/SO/BBB-install that causes this issue.

**Comment by lookas1** [comment]
@mariogasparoni can you send details to our email info@wabbit.pl? Not sure how I can get your email (is it possible through github anyway? ;-) ) We are happy to test it on your setup.

**Comment by kusznerr** [comment]
Hello - wanted to check if there was any luck in finding what the issue may be ...

**Comment by kiakeykhosravi** [comment]
hello - we have exactly the same problem i even added it in google dev group today its really starting to create problems for us.is there any chance you guys found whats the problem?
