### ISSUE TITLE
muteOnStart for single user

### ISSUE THREAD

**Issue by dariosera** [bigbluebutton/bigbluebutton#10811]
Hi everyone!
I would like allow users to enable/disable their microphones and webcams before they enter in the conference.

If the user wants to join with the webcam enabled, I can add this to the _join_ API call:
```http
userdata-bbb_auto_share_webcam=true
userdata-bbb_skip_video_preview=true
```

If the user wants to join with mic enabled, I can set:
```http
userdata-bbb_auto_join_audio=true
userdata-bbb_listen_only_mode=false
userdata-bbb_skip_check_audio=true
```

But I can't find a solution for a user that wants to join with audio enabled, but with mic muted.
The `muteOnStart` parameter can be set only during the creation of the meeting, so it applies to all users.

**Describe the solution you'd like**
A parameter (let me call it `userdata-bbb_mute_on_join`) in addition to those that are already available [here](https://docs.bigbluebutton.org/2.2/customize.html#application-parameters).

**Comment by basisbit** [comment]
For developer support requests, please use the [forum / mailing list](https://groups.google.com/forum/#!forum/bigbluebutton-dev).

**Comment by dariosera** [comment]
Thanks for your reply @basisbit 
I'll re-check the docs and parameters available, but I think is not possible to do what I'm trying to do.

**Comment by TallTed** [comment]
I want to do with BBB as I do with Zoom, Webex, etc. -- Join the call with my mic *available* but *muted*
