### ISSUE TITLE
Display emoji the user selected in his/her webcam stream

### ISSUE THREAD

**Issue by jdepi** [bigbluebutton/bigbluebutton#10828]
Hi all,
for users, who have turned on their webcam it would be great to see their emoji in their camera stream.
For small groups having all their camera turned on there would be no need anymore to turn on the particpants list - everybody could see the whole status of everybody just in their webcam stream :+1:, then.

jdepi

**Comment by ffdixon** [comment]
It's a good suggestion.  e'll look at getting it into a subsequent release (after 2.2).

**Comment by Corradones** [comment]
Amazing function. Quote Jdepi
