### ISSUE TITLE
How to see who is wrinting on the screen thingy as a student?

### ISSUE THREAD

**Issue by Ryan-samaeian** [bigbluebutton/bigbluebutton#10827]
Hi im an student in a school,and i wanted to ask you guys how i could see who is drawing on the screen? kids tend to hide their names by drawing very fast or just drawing on the edge! so please help!

**Comment by Ryan-samaeian** [comment]
i tried to open the js but i still dont understand how it works PLEASE HELP!

**Comment by matiasilva** [comment]
Hi, thanks for the question. Unfortunately, this issue tracker is for bug reports and feature requests only so questions like these are better served by the forums, per the instructions here: https://docs.bigbluebutton.org/2.2/getting-help.html#help-using-bigbluebutton
