### ISSUE TITLE
Multiuser pointer for desktop sharing

### ISSUE THREAD

**Issue by boeddeker** [bigbluebutton/bigbluebutton#10823]
**Is your feature request related to a problem? Please describe.**

When teaching over BBB, I often share my screen.
When a student has a question, the student has to explain where I should look.
This is sometimes complicated, depending what is on the screen.

**Describe the solution you'd like**

An option like the "multi user mode" also for desktop sharing.
In this case each user gets a pointer similar to the pointers as in the whiteboard.
Then each user can use the pointer to highlight where everyone should look.

Note: It would be enough for me, when the pointers are only visible in the BBB window and
not on the desktop. Then I can see BBB browser tab on one screen and share the other screen.
This would not be the best solution, but a solution that is probably much easier to realize.

**Describe alternatives you've considered**

Use the voice to advice where to look.

**Additional context**

I tried to find an issue, where someone already asked for such a feature.
But I didn't found one.

**Comment by greenycat** [comment]
Af far as I know even the teacher's red pointer is not shared. Is that expected behaviour?

**Comment by vladimirsmutny** [comment]
I fully support the feature, either in its full (student cursor appears in shared part of the screen) or minimal version (student cursor appear only in BBB window). When discussed the code or text, line number can help, but when discussing e.g. CAD model or drawing (my case) or other visual information (photo, painting, image of the sculpture), this is absolutely essential.
Thank you for your effort.
