### ISSUE TITLE
BBB uses old Etherpad Version

### ISSUE THREAD

**Issue by erisd** [bigbluebutton/bigbluebutton#10832]
**Describe the bug**
Etherpad is still on Version 1.8.0 but 1.8.7 is the latest Version.

**Additional context**
https://github.com/ether/etherpad-lite/blob/develop/CHANGELOG.md

**Comment by ffdixon** [comment]
Good point.  We'll take a look at pulling in the latest release.

**Comment by pedrobmarin** [comment]
https://github.com/ether/etherpad-lite/releases/tag/1.8.0

`REQUIREMENTS: minimum required Node version is 8.9.0 LTS. Release 1.8.3 will require at least Node 10.13.0 LTS`

**Comment by ffdixon** [comment]
> Release 1.8.3 will require at least Node 10.13.0 LTS

2.3-dev which is running Node 12.x.  Let's see if we can get to the latest release of Etherpad there.

**Comment by antobinary** [comment]
Resolved as part of 2.3-alpha6, see release notes - packaging https://github.com/bigbluebutton/bigbluebutton/releases/tag/v2.3-alpha-6
