### ISSUE TITLE
2.3-dev - ubuntu 18.4 deb packages have dependency problems. ?

### ISSUE THREAD

**Issue by andrex4k** [bigbluebutton/bigbluebutton#10835]
[shell-out.txt](https://github.com/bigbluebutton/bigbluebutton/files/5545664/shell-out.txt)

**Comment by uka-support** [comment]
Bevore everybody else has to download you .txt, here's a copy for easier consumption:

`
root@bbb:~# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.5 LTS
Release:        18.04
Codename:       bionic
root@bbb:~# uname -r
4.15.0-123-generic
root@bbb:~# dpkg -l | grep 'bigbluebutton\|bbb'
root@bbb:~# 
root@bbb:~# apt search bbb
Sorting... Done
Full Text Search... Done
bbb-apps-akka/unknown 2.3.0-5 all
  BigBlueButton Apps (Akka)

bbb-config/unknown 1:2.3.0-7 amd64
  BigBlueButton configuration utilities

bbb-demo/unknown 1:2.3.0-2 amd64
  BigBlueButton API demos

bbb-etherpad/unknown 1:2.3.0-11 amd64
  The EtherPad Lite components for BigBlueButton

bbb-freeswitch-core/unknown 2:2.3.0-2 amd64
  BigBlueButton build of FreeSWITCH

bbb-freeswitch-sounds/unknown 1:1.6.7-1 amd64
  FreeSWITCH Sounds

bbb-fsesl-akka/unknown 2.3.0-3 all
  BigBlueButton FS-ESL (Akka)

bbb-html5/unknown 1:2.3.0-1250 amd64
  The HTML5 components for BigBlueButton

bbb-libreoffice-docker/unknown 1:2.3.0-6 amd64
  BigBlueButton setup for LibreOffice running in docker

bbb-lti/unknown 1:2.3.0-1 amd64
  BigBlueButton endpoint for LTI

bbb-mkclean/unknown 1:0.8.7-1 amd64
  Clean and optimize Matroska and WebM files

bbb-playback-notes/unknown 1:2.3.0-1 amd64
  BigBluebutton playback of notes

bbb-playback-podcast/unknown 1:2.3.0-1 amd64
  BigBluebutton playback in podcast

bbb-playback-presentation/unknown 1:2.3.0-3 amd64
  BigBluebutton playback of presentation

bbb-playback-screenshare/unknown 1:2.3.0-1 amd64
  BigBluebutton playback of screenshare

bbb-record-core/unknown 1:2.3.0-6 amd64
  BigBlueButton record and playback

bbb-transcode-akka/unknown 2.3.0-1 all
  BigBlueButton Transcoder

bbb-web/unknown 1:2.3.0-9 amd64
  BigBlueButton API

bbb-webhooks/unknown 1:2.3.0-3 amd64
  BigBlueButton Webhooks

bbb-webrtc-sfu/unknown 1:2.3.0-4 amd64
  BigBlueButton WebRTC SFU

bigbluebutton/unknown 1:2.3.0-4 amd64
  Open source web conferencing platform (bbb)

root@bbb:~# 
root@bbb:~# wget -qO- https://ubuntu.bigbluebutton.org/bbb-install.sh | bash -s -- -v bionic-230-dev -s bbb.lan -e noreply@mil.bbb.lan -a -w

Reading state information... Done
E: Unable to locate package linux-image-extra-4.15.0-123-generic
E: Couldn't find any package by glob 'linux-image-extra-4.15.0-123-generic'
E: Couldn't find any package by regex 'linux-image-extra-4.15.0-123-generic'
Warning: apt-key output should not be parsed (stdout is not a terminal)
/usr/bin/docker


The following packages have unmet dependencies:
 bigbluebutton : Depends: bbb-config but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
Reading package lists...
Building dependency tree...
Reading state information...
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 bbb-html5 : Depends: bbb-web but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
.............^C

root@bbb:~# apt search linux-image-extra
Sorting... Done
Full Text Search... Done
linux-image-extra-virtual/bionic 4.15.0.125.112 amd64
  Extra drivers for Virtual Linux kernel image

linux-image-extra-virtual-hwe-16.04/bionic 4.15.0.125.112 amd64
  Extra drivers for Virtual Linux kernel image (dummy transitional package)

linux-image-extra-virtual-hwe-16.04-edge/bionic 4.15.0.125.112 amd64
  Extra drivers for Virtual Linux kernel image (dummy transitional package)

linux-image-extra-virtual-hwe-18.04/bionic 5.4.0.55.61~18.04.49 amd64
  Full Generic Linux kernel and headers for virtual instances

linux-image-extra-virtual-hwe-18.04-edge/bionic 5.4.0.55.61~18.04.49 amd64
  Full Generic Linux kernel and headers for virtual instances

`

**Comment by andrex4k** [comment]
use aptitude install bigbluebutton, downgrade libpcre3  libxml2
