### ISSUE TITLE
Fix continuous zoom for vertical/portrait documents

### ISSUE THREAD

**Issue by matt-htw** [bigbluebutton/bigbluebutton#10837]
**Is your feature request related to a problem? Please describe.**
While BBB supports presentation of PDFs, typical vertical/portrait documents are displayed with a fixed window width (windows scaled to document height), resulting in small size and bad readability. When zooming in, the reduced window width is unfortunately not extended to the new scale, but the windows ratio is maintained - even though the full view document height is not relevant for zoomed in presentation. So one has to chose between small letters or cropped paragraph width - even though there is plenty of unsused windows space to the left and right.

Vertical/portrait documents are a frequent use case - In engineering, I often need vertical tables not suitable for horizontal/landscape slide format, and I clearly prefer to explain using zoom & pan on a printable reader as basis for presentation rather than unloading a scripted slideshows of several 100 as lecture notes (or maintaining it in double format). So I definitely prefer to make the uploaded PDFs available in readable scale.

**Describe the solution you'd like**
I wish BBB would not limit the presentation window based on 100 % document ratio - I would like to zoom in and have the document extend in width dynamically (up to full available window size) - independent of ratio of the original document in static full view.

**Describe alternatives you've considered**
As a work-around, I can enable the "fit to width" option. However, this works only down to 100 %. So I can switch between portrait mode (full document height, width too small) and landscape mode 100 % (full document width, but height cropped too narrow) - but nothing in between.

Another solution would be to allow less than 100 % scale in "fit to width" mode - But that would include full height mode as a special case, but maintain the two modes. I would think it is easier to make one function covering all zoom states rather than program two overlapping modes.

**Comment by timokau** [comment]
Another way to look at this: It would be nice if we could freely resize the canvas (change its aspect ratio) independent of the zoom level. That would have a very similar effect, but would not depend on the presenter's window size.

**Comment by conceptionist** [comment]
Comment (to avoid an auto-close and bring it to awareness): I still think this is a major issue for everyday operation and should be addressed. Many staff members prefer Zoom over BBB - for useability reasons like this one.
