### ISSUE TITLE
How to change /bigbluebutton/ url

### ISSUE THREAD

**Issue by pedped** [bigbluebutton/bigbluebutton#10833]
I want to change the <hostname>/bigbluebutton/ url and replace bigbluebutton with my own path, how can I achieve that. I did not find any good data on documantion

**Comment by basisbit** [comment]
For such support requests, please use the [forum / mailing list](https://groups.google.com/forum/#!forum/bigbluebutton-setup). This issue tracker here is only for BBB development related issues. Sorry.
