### ISSUE TITLE
Upload-Button Placement

### ISSUE THREAD

**Issue by HDValentin** [bigbluebutton/bigbluebutton#10845]
**Describe the bug**
Upload-Button at a position that is not expected by users.
Beginners have often problems to find/recognise the button.

**To Reproduce**
1. Click at the plus on the left corner
2. Select Upload Presentation
3. select a file

**Expected behavior**
Users expect a Button under the file to upload the presentation

**Actual behavior**
The button Upload is on top of the site.

**Screenshots**
![bbb-button-usability](https://user-images.githubusercontent.com/1276955/99388314-ad906a80-28d5-11eb-9015-a4d0ca074771.jpg)

**Desktop (please complete the following information):**
- Tested on Windows 10 and Debian Linux Systems with
- Chromium and Firefox Browsers

**Additional context**
This is a usability enhancement

**Comment by ffdixon** [comment]
Its a good suggestion.

**Comment by HDValentin** [comment]
I think it is quite easy to solve. For a developer who knows in which file it is.

**Comment by greenycat** [comment]
The whole dialog should be a modal window. Many students of mine are stumbling upon question how to return back. (Normally UI implies that modal may be quickly closed by clicking surrounding field). Here everybody MUST click "Close" button which is confusing to find.

**Comment by HDValentin** [comment]
This problem is still there in BBB conferences.

**Comment by antobinary** [comment]
The location of the "Upload" is consistent with the rest of our fullscreen modals - Settings, Create breakout rooms, ...
In the past (<2.2) we were using a non-fullscreen modal and it caused a lot of confusion with people trying to return to the meeting without confirming (upload or cancel) and since the fullscreen switch this has not been a problem (afaik)
