### ISSUE TITLE
Safari iOS in app webview audio stream support

### ISSUE THREAD

**Issue by MeherBa** [bigbluebutton/bigbluebutton#10843]
**Describe the bug**
I'm trying to get bbb running on iOS [WKWebViewRTC](https://github.com/OpenTelecom/WKWebViewRTC) but am having some trouble getting it to work reliably. first of all, i changed the user agent to bypass the browser support issue with this : "Mozilla/5.0 (iPad; CPU OS 13_2_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Mobile/15E148 Safari/604.1". After clicking on mic icon and error pops up that says "There was an issue with your media devices"
Microphone permission is authorized in the app and the browser.

**Console log from safari**
`[Log] [17:28:52:0893]  INFO: clientLogger: Client loaded successfully https://demo1.bigbluebutton.org/html5client/360dab2bc7fe72fc104370eff8fc6e4d001522d5.js?meteor_js_resource=true:121:982525 (360dab2bc7fe72fc104370eff8fc6e4d001522d5.js, line 9)
[Log] [17:28:52:0906]  INFO: clientLogger: Subscriptions are ready https://demo1.bigbluebutton.org/html5client/360dab2bc7fe72fc104370eff8fc6e4d001522d5.js?meteor_js_resource=true:121:1213537 (360dab2bc7fe72fc104370eff8fc6e4d001522d5.js, line 9)
[Log] [17:28:57:0701]  INFO: clientLogger: User requested to join audio conference with mic https://demo1.bigbluebutton.org/html5client/360dab2bc7fe72fc104370eff8fc6e4d001522d5.js?meteor_js_resource=true:121:1152251 (360dab2bc7fe72fc104370eff8fc6e4d001522d5.js, line 9)
[Log] [17:28:57:0925] DEBUG: clientLogger: Creating the user agent https://demo1.bigbluebutton.org/html5client/360dab2bc7fe72fc104370eff8fc6e4d001522d5.js?meteor_js_resource=true:121:1185997 (360dab2bc7fe72fc104370eff8fc6e4d001522d5.js, line 9)
[Log] Tue Nov 17 2020 17:28:57 GMT+0100 (CET) | sip.UserAgent | Configuration: (sip.js, line 9602)
[Log] Tue Nov 17 2020 17:28:57 GMT+0100 (CET) | sip.UserAgent | · allowLegacyNotifications: false (sip.js, line 9602)
[Log] Tue Nov 17 2020 17:28:57 GMT+0100 (CET) | sip.UserAgent | · authorizationHa1: "" (sip.js, line 9602)
[Log] Tue Nov 17 2020 17:28:57 GMT+0100 (CET) | sip.UserAgent | · authorizationPassword: NOT SHOWN (sip.js, line 9602)
[Log] Tue Nov 17 2020 17:28:57 GMT+0100 (CET) | sip.UserAgent | · authorizationUsername: "" (sip.js, line 9602)
[Log] Tue Nov 17 2020 17:28:57 GMT+0100 (CET) | sip.UserAgent | · autoStart: false (sip.js, line 9602)
[Log] Tue Nov 17 2020 17:28:57 GMT+0100 (CET) | sip.UserAgent | · autoStop: true (sip.js, line 9602)
[Log] Tue Nov 17 2020 17:28:57 GMT+0100 (CET) | sip.UserAgent | · delegate: {} (sip.js, line 9602)
[Log] Tue Nov 17 2020 17:28:57 GMT+0100 (CET) | sip.UserAgent | · displayName: "w_dbfqn49r6brv_1-bbbID-Aa" (sip.js, line 9602)
[Log] Tue Nov 17 2020 17:28:57 GMT+0100 (CET) | sip.UserAgent | · forceRport: false (sip.js, line 9602)
[Log] Tue Nov 17 2020 17:28:57 GMT+0100 (CET) | sip.UserAgent | · hackAllowUnregisteredOptionTags: false (sip.js, line 9602)
[Log] Tue Nov 17 2020 17:28:57 GMT+0100 (CET) | sip.UserAgent | · hackIpInContact: false (sip.js, line 9602)
[Log] Tue Nov 17 2020 17:28:57 GMT+0100 (CET) | sip.UserAgent | · hackViaTcp: false (sip.js, line 9602)
[Log] Tue Nov 17 2020 17:28:57 GMT+0100 (CET) | sip.UserAgent | · hackViaWs: true (sip.js, line 9602)
[Log] Tue Nov 17 2020 17:28:57 GMT+0100 (CET) | sip.UserAgent | · hackWssInTransport: false (sip.js, line 9602)
[Log] Tue Nov 17 2020 17:28:57 GMT+0100 (CET) | sip.UserAgent | · logBuiltinEnabled: true (sip.js, line 9602)
[Log] Tue Nov 17 2020 17:28:57 GMT+0100 (CET) | sip.UserAgent | · logConfiguration: true (sip.js, line 9602)
[Log] Tue Nov 17 2020 17:28:57 GMT+0100 (CET) | sip.UserAgent | · logConnector: undefined (sip.js, line 9602)
[Log] Tue Nov 17 2020 17:28:57 GMT+0100 (CET) | sip.UserAgent | · logLevel: "log" (sip.js, line 9602)
[Log] Tue Nov 17 2020 17:28:57 GMT+0100 (CET) | sip.UserAgent | · noAnswerTimeout: 60 (sip.js, line 9602)
[Log] Tue Nov 17 2020 17:28:57 GMT+0100 (CET) | sip.UserAgent | · preloadedRouteSet: [] (sip.js, line 9602)
[Log] Tue Nov 17 2020 17:28:57 GMT+0100 (CET) | sip.UserAgent | · reconnectionAttempts: 0 (sip.js, line 9602)
[Log] Tue Nov 17 2020 17:28:57 GMT+0100 (CET) | sip.UserAgent | · reconnectionDelay: 4 (sip.js, line 9602)
[Log] Tue Nov 17 2020 17:28:57 GMT+0100 (CET) | sip.UserAgent | · sessionDescriptionHandlerFactory: (session, options) => { (sip.js, line 9602)
        // provide a default media stream factory if need be
        if (mediaStreamFactory === undefined) {
            mediaStreamFactory = Object(_media_stream_factory_default__WEBPACK_IMPORTED_MODULE_0__["defaultMediaStreamFactory"])();
        }
        // make sure we allow `0` to be passed in so timeout can be disabled
        const iceGatheringTimeout = (options === null || options === void 0 ? void 0 : options.iceGatheringTimeout) !== undefined ? options === null || options === void 0 ? void 0 : options.iceGatheringTimeout : 5000;
        // merge passed factory options into default session description configuration
        const sessionDescriptionHandlerConfiguration = {
            iceGatheringTimeout,
            peerConnectionConfiguration: Object.assign(Object.assign({}, Object(_peer_connection_configuration_default__WEBPACK_IMPORTED_MODULE_1__["defaultPeerConnectionConfiguration"])()), options === null || options === void 0 ? void 0 : options.peerConnectionConfiguration)
        };
        const logger = session.userAgent.getLogger("sip.SessionDescriptionHandler");
        return new _session_description_handler__WEBPACK_IMPORTED_MODULE_2__["SessionDescriptionHandler"](logger, mediaStreamFactory, sessionDescriptionHandlerConfiguration);
    }
[Log] Tue Nov 17 2020 17:28:57 GMT+0100 (CET) | sip.UserAgent | · sessionDescriptionHandlerFactoryOptions: {"peerConnectionConfiguration":{"iceServers":[{"urls":"stun:turn.blindsidenetworks.com"},{"urls":"turn:turn.blindsidenetworks.com:443?transport=tcp","credential":"TLtky6WtLNLfx/xSBg4r4sCMEEk=","username":"1605716937:w_dbfqn49r6brv"},{"urls":"turns:turn.blindsidenetworks.com:443?transport=tcp","credential":"TLtky6WtLNLfx/xSBg4r4sCMEEk=","username":"1605716937:w_dbfqn49r6brv"}],"sdpSemantics":"plan-b"}} (sip.js, line 9602)
[Log] Tue Nov 17 2020 17:28:57 GMT+0100 (CET) | sip.UserAgent | · sipExtension100rel: "Unsupported" (sip.js, line 9602)
[Log] Tue Nov 17 2020 17:28:57 GMT+0100 (CET) | sip.UserAgent | · sipExtensionReplaces: "Unsupported" (sip.js, line 9602)
[Log] Tue Nov 17 2020 17:28:57 GMT+0100 (CET) | sip.UserAgent | · sipExtensionExtraSupported: [] (sip.js, line 9602)
[Log] Tue Nov 17 2020 17:28:57 GMT+0100 (CET) | sip.UserAgent | · sipjsId: "u22dp" (sip.js, line 9602)
[Log] Tue Nov 17 2020 17:28:57 GMT+0100 (CET) | sip.UserAgent | · transportConstructor: Transport (sip.js, line 9602)
[Log] Tue Nov 17 2020 17:28:57 GMT+0100 (CET) | sip.UserAgent | · transportOptions: {"server":"wss://demo1.bigbluebutton.org/ws?sessionToken=e7eqzk9zkwnd4wsa","connectionTimeout":5000} (sip.js, line 9602)
[Log] Tue Nov 17 2020 17:28:57 GMT+0100 (CET) | sip.UserAgent | · uri: sip:w_dbfqn49r6brv_1-bbbID-Aa@demo1.bigbluebutton.org (sip.js, line 9602)
[Log] Tue Nov 17 2020 17:28:57 GMT+0100 (CET) | sip.UserAgent | · userAgentString: "BigBlueButton" (sip.js, line 9602)
[Log] Tue Nov 17 2020 17:28:57 GMT+0100 (CET) | sip.UserAgent | · viaHost: "51k4afi88310.invalid" (sip.js, line 9602)
[Log] Tue Nov 17 2020 17:28:57 GMT+0100 (CET) | sip.UserAgent | · register: false (sip.js, line 9602)
[Log] Tue Nov 17 2020 17:28:57 GMT+0100 (CET) | sip.UserAgent | Starting sip:w_dbfqn49r6brv_1-bbbID-Aa@demo1.bigbluebutton.org (sip.js, line 9602)
[Log] Tue Nov 17 2020 17:28:57 GMT+0100 (CET) | sip.UserAgent | Transitioned from Stopped to Started (sip.js, line 9602)
[Log] Tue Nov 17 2020 17:28:57 GMT+0100 (CET) | sip.Transport | Connecting wss://demo1.bigbluebutton.org/ws?sessionToken=e7eqzk9zkwnd4wsa (sip.js, line 9602)
[Log] Tue Nov 17 2020 17:28:57 GMT+0100 (CET) | sip.Transport | Transitioned from Disconnected to Connecting (sip.js, line 9602)
[Log] Tue Nov 17 2020 17:28:58 GMT+0100 (CET) | sip.Transport | WebSocket opened wss://demo1.bigbluebutton.org/ws?sessionToken=e7eqzk9zkwnd4wsa (sip.js, line 9602)
[Log] Tue Nov 17 2020 17:28:58 GMT+0100 (CET) | sip.Transport | Transitioned from Connecting to Connected (sip.js, line 9602)
[Log] [17:28:58:0585]  INFO: clientLogger: User agent succesfully connected https://demo1.bigbluebutton.org/html5client/360dab2bc7fe72fc104370eff8fc6e4d001522d5.js?meteor_js_resource=true:121:1187969 (360dab2bc7fe72fc104370eff8fc6e4d001522d5.js, line 9)
[Log] Tue Nov 17 2020 17:28:58 GMT+0100 (CET) | sip.Inviter | Inviter.invite (sip.js, line 9602)
[Debug] iosrtc:MediaStream new MediaStream(arg) | [arg:undefined] +0ms (user-script:1, line 378)
[Debug] iosrtc:MediaStream new MediaStream(arg) | [arg:undefined] +14ms (user-script:1, line 378)
[Debug] iosrtc:RTCPeerConnection new() | [pcConfig: (user-script:1, line 378)
{bundlePolicy: "balanced", certificates: undefined, iceCandidatePoolSize: 0, iceServers: [{urls: "stun:turn.blindsidenetworks.com"}, {urls: "turn:turn.blindsidenetworks.com:443?transport=tcp", credential: "TLtky6WtLNLfx/xSBg4r4sCMEEk=", username: "1605716937:w_dbfqn49r6brv"}, {urls: "turns:turn.blindsidenetworks.com:443?transport=tcp", credential: "TLtky6WtLNLfx/xSBg4r4sCMEEk=", username: "1605716937:w_dbfqn49r6brv"}], iceTransportPolicy: "all", …}
, pcConstraints:undefined] +0ms
[Debug] iosrtc:getUserMedia [original constraints: (user-script:1, line 378)
{audio: true, video: false}
] +0ms
[Debug] iosrtc:getUserMedia [computed constraints: (user-script:1, line 378)
{audio: {}}
] +13ms
[Debug] iosrtc:getUserMedia getUserMedia() | success +109ms (user-script:1, line 378)
[Debug] iosrtc:MediaStream create() | [dataFromEvent: (user-script:1, line 378)
{id: "78517D11-DFEB-4118-90B9-8E3D30A1ED94", audioTracks: Object, videoTracks: {}}
] +143ms
[Debug] iosrtc:MediaStream new MediaStream(arg) | [arg: (user-script:1, line 378)
[] (0)
] +1ms
[Debug] iosrtc:MediaStreamTrack new() | [dataFromEvent: (user-script:1, line 378)
{readyState: "live", id: "B33A7241-50F7-4FC5-9D83-B3BE5B84A5F9", kind: "audio", enabled: true, trackId: "B33A7241-50F7-4FC5-9D83-B3BE5B84A5F9"}
] +0ms
[Debug] iosrtc:MediaStream emitConnected() +11ms (user-script:1, line 378)
[Debug] iosrtc:MediaStream getAudioTracks() +0ms (user-script:1, line 378)
[Debug] iosrtc:MediaStream getAudioTracks() +1ms (user-script:1, line 378)
[Debug] iosrtc:MediaStream getVideoTracks() +1ms (user-script:1, line 378)
[Debug] iosrtc:MediaStream addTrack() [track: (user-script:1, line 378)
MediaStreamTrack {_listeners: Object, id: "B33A7241-50F7-4FC5-9D83-B3BE5B84A5F9", kind: "audio", label: undefined, muted: false, …}
] +0ms
[Debug] iosrtc:MediaStream emitConnected() +1ms (user-script:1, line 378)
[Debug] iosrtc:MediaStream addTrack() [track: (user-script:1, line 378)
MediaStreamTrack {_listeners: Object, id: "B33A7241-50F7-4FC5-9D83-B3BE5B84A5F9", kind: "audio", label: undefined, muted: false, …}
] +1ms
[Error] Tue Nov 17 2020 17:28:58 GMT+0100 (CET) | sip.SessionDescriptionHandler | SessionDescriptionHandler.getDescription failed - TypeError: Type error
	print (sip.js:9594)
	genericLog (sip.js:9574)
	genericLog (sip.js:9647)
	error (sip.js:9635)
	(anonymous function) (sip.js:18325)
	(anonymous function) (360dab2bc7fe72fc104370eff8fc6e4d001522d5.js:1:8248)
	promiseReactionJob
[Error] Tue Nov 17 2020 17:28:58 GMT+0100 (CET) | sip.Inviter | Session.getOffer: SDH getDescription rejected...
	print (sip.js:9594)
	genericLog (sip.js:9574)
	genericLog (sip.js:9647)
	error (sip.js:9635)
	(anonymous function) (sip.js:13637)
	(anonymous function) (360dab2bc7fe72fc104370eff8fc6e4d001522d5.js:1:8248)
	promiseReactionJob
[Error] Tue Nov 17 2020 17:28:58 GMT+0100 (CET) | sip.Inviter | Type error
	print (sip.js:9594)
	genericLog (sip.js:9574)
	genericLog (sip.js:9647)
	error (sip.js:9635)
	(anonymous function) (sip.js:13639)
	(anonymous function) (360dab2bc7fe72fc104370eff8fc6e4d001522d5.js:1:8248)
	promiseReactionJob
[Log] Tue Nov 17 2020 17:28:58 GMT+0100 (CET) | sip.Inviter | Type error (sip.js, line 9602)
[Log] Tue Nov 17 2020 17:28:58 GMT+0100 (CET) | sip.Inviter | Session u22dpolrkptj28no53k1vic02p6p6j transitioned to state Terminated (sip.js, line 9602)
[Log] Tue Nov 17 2020 17:28:58 GMT+0100 (CET) | sip.Inviter | Session u22dpolrkptj28no53k1vic02p6p6j in state Terminated is being disposed (sip.js, line 9602)
[Debug] iosrtc:MediaStream getTracks() +12ms (user-script:1, line 378)
[Debug] iosrtc:MediaStreamTrack stop() +17ms (user-script:1, line 378)
[Debug] iosrtc:RTCPeerConnection close() +171ms (user-script:1, line 378)
[Debug] iosrtc:RTCPeerConnection onEvent() | [type:iceconnectionstatechange, data: (user-script:1, line 378)
{iceConnectionState: "closed", type: "iceconnectionstatechange"}
] +128ms
[Debug] iosrtc:RTCPeerConnection onEvent() | [type:signalingstatechange, data: (user-script:1, line 378)
{type: "signalingstatechange", signalingState: "closed"}
] +1ms`

**To Reproduce**
1. Clone this repo [WKWebViewRTC](https://github.com/OpenTelecom/WKWebViewRTC)
2. Add `webView.customUserAgent = "Mozilla/5.0 (iPad; CPU OS 13_2_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Mobile/15E148 Safari/604.1"` in ViewController.swift in example project
3. Change URLRequest to bbb participant url
4. Run the project
5. Click on mic button

**Screenshots**
![Simulator Screen Shot - iPhone Xʀ - 2020-11-17 at 08 47 01](https://user-images.githubusercontent.com/47627084/99360966-ae170a00-28b1-11eb-8c73-1720cf1f8fb8.png)

**BBB version (optional):**
Using BBB [demo](https://demo.bigbluebutton.org/)

**Smartphone (please complete the following information):**
 - Device: iPhone Xʀ
 - OS: iOS 12.4
 - Browser Safari WKWebView

**Additional context**
I tried [Janus WebRTC Server](https://janus.conf.meetecho.com/audiobridgetest.html) demo Test and the mic works perfectly i think the problem is that the web client can't handle audio streams from bbb.

**Comment by basisbit** [comment]
`WKWebView` doesn't fully support WebRTC natively, but instead only supports some webrtc basics:

- https://forums.developer.apple.com/thread/88052
- https://stackoverflow.com/questions/45055329/does-webkit-in-ios-11-beta-support-webrtc/49467964#49467964
- https://stackoverflow.com/questions/54319924/access-camera-or-webcam-without-webrtc
- https://stackoverflow.com/questions/46988450/wkwebview-or-uiwebview-in-ios-app-does-this-webview-support-webrtc

BBB only uses HTML5 + WebRTC standard features, thus, you'll have to ask the webbrowser developer for support.
