### ISSUE TITLE
Multi-User-Whiteboard - Text input Problem with iOS / iPadOS

### ISSUE THREAD

**Issue by Schmitt-A** [bigbluebutton/bigbluebutton#10859]
Hey there :)

it isn't possible for iOS / iPadOS users with Safari to use the Multi-User-Whiteboard Text input.
Is it a problem with iOS / iPadOS? Or with BBB?

Thanks 
Andreas

**Comment by basisbit** [comment]
For support requests, please use the [forum / mailing list](https://groups.google.com/forum/#!forum/bigbluebutton-users). This issue tracker here is only for BBB development related issues. Sorry.

There also already exist issues here in the issue tracker for improving touch device support on the whiteboard.
