### ISSUE TITLE
PDF not apear after upload

### ISSUE THREAD

**Issue by hdhamid1371** [bigbluebutton/bigbluebutton#10856]
**Describe the bug**
when upload pdf not apear slides in version 2.2.29!!
whats the problem?this is work in 2.2.19 version but not work final version
[session 1.pdf](https://github.com/bigbluebutton/bigbluebutton/files/5560120/session.1.pdf)

context about the problem here.
**To Reproduce**
1. action
2. Click on 'upload a presentation'
3. see nothing

![bug bbb](https://user-images.githubusercontent.com/13962284/99533587-62e91e00-29bb-11eb-8c0d-2ea5082b8189.JPG)

**Comment by itum** [comment]
Hello 
Do you have Iran Server ?
if you have please check out your speedtest in your server.
you can install by this command : 
$ _apt-get install speedtest-cli_
and then 
$ _speedtest --share_

Speed upload/download is more important.
i have a test in my server located in Iran and i sent a ticket to  support vds and solve it.

**Comment by ffdixon** [comment]
Can you try reproducing this on https://test.bigbluebutton.org/

**Comment by hdhamid1371** [comment]
> Can you try reproducing this on https://test.bigbluebutton.org/

no problem in this server:(

speed test:
https://www.speedtest.net/result/10441135854.png

**Comment by itum** [comment]
> > Can you try reproducing this on https://test.bigbluebutton.org/
> 
> no problem in this server:(
> 
> speed test:
> https://www.speedtest.net/result/10441135854.png

your server is not Good !! look at your speedtest data :
Ping 2504 ms !! Download: 12Mbps / Upload 3.12 Mbps !! its so bad .
please send a ticket to your server provider ( Faraso ). 
its my speedtest : 

https://www.speedtest.net/result/10444882961.png
you can compare it with your server that i run it in Iran.

**Comment by hdhamid1371** [comment]
> > > Can you try reproducing this on https://test.bigbluebutton.org/
> > 
> > 
> > no problem in this server:(
> > speed test:
> > https://www.speedtest.net/result/10441135854.png
> 
> your server is not Good !! look at your speedtest data :
> Ping 2504 ms !! Download: 12Mbps / Upload 3.12 Mbps !! its so bad .
> please send a ticket to your server provider ( Faraso ).
> its my speedtest :
> 
> https://www.speedtest.net/result/10444882961.png
> you can compare it with your server that i run it in Iran.

thanks
my server is in iran but if i not set dns not work!!! i upload pdf and really not show pdf content and then i cant get speed test,
i set 8.8.8.8 dns for my server, i have this ping!!! time
what do i do?

**Comment by itum** [comment]
you dnt need to set your iran server to 8.8.8.8 because its forbidden...
just you need to do this : 

_$ sudo vim /etc/resolvconf/resolv.conf.d/base_

Then put your Shecan/Begzar Nameservers here :
(Shecan is recommend)
nameserver 178.22.122.100
nameserver 185.51.200.2

Finally update resolvconf:

_$ sudo resolvconf -u_

and then you  can install BBB Software...without any problem.
when your installation finished you can clean dns nameservers...you dnt need it again.

**Comment by uka-support** [comment]
Do you have a proper SSL certficate for your server? I've had this issue when I was using an internal CA (non-public) for issuing the SSL certificate for the server. It needs to be made available to node.js

If you are using an internal CA, you need to add a line to /usr/share/meteor/bundle/systemd_start.sh:
```
export NODE_EXTRA_CA_CERTS=/usr/local/share/ca-certfiicates/your-ca-here.crt
```

**Comment by hdhamid1371** [comment]
> you dnt need to set your iran server to 8.8.8.8 because its forbidden...
> just you need to do this :
> 
> _$ sudo vim /etc/resolvconf/resolv.conf.d/base_
> 
> Then put your Shecan/Begzar Nameservers here :
> (Shecan is recommend)
> nameserver 178.22.122.100
> nameserver 185.51.200.2
> 
> Finally update resolvconf:
> 
> _$ sudo resolvconf -u_
> 
> and then you can install BBB Software...without any problem.
> when your installation finished you can clean dns nameservers...you dnt need it again.

thnaks solve it...
delete default nameserver and get ping again and this very good and retry then solve my problem
thanks

**Comment by itum** [comment]
your welcome.
The server speed Upload/Download is important.

Good Luck.

**Comment by basisbit** [comment]
For support requests regarding initial server setup and configuration, please use the [forum / mailing list](https://groups.google.com/forum/#!forum/bigbluebutton-setup). This issue tracker here is only for BBB development related issues. Sorry.
When posting your problem description to the setup mailing list, please also add bigbluebutton logfiles and the result of `bbb-conf --check` and `bbb-conf --status`.

@itum The speed test is not related to this problem, if at all it would take maybe a second longer for the webbrowser to download the jpg file of the slide.
