### ISSUE TITLE
etherpad listens to 0.0.0.0

### ISSUE THREAD

**Issue by crosscodr** [bigbluebutton/bigbluebutton#10869]
**Describe the bug**
etherpad listens on 0.0.0.0, which should be unnecessary.

**Expected behavior**
Since etherpad is behind nginx proxy, I would expect it to listen only on localhost/127.0.0.1

**Actual behavior**
etherpad listens on 0.0.0.0

**Additional context**
I have bbb-etherpad 2.2.0-63 installed, per bbb-install.sh

I came up with this while investigating _connection refused by upstream_ errors in nginx-bigbluebutton.error.log because proxy_pass is configured with localhost instead of 127.0.01 in /etc/bigbluebutton/nginx/notes.nginx

**Comment by ffdixon** [comment]
Thanks -- we'll take a closer look.

**Comment by erisd** [comment]
> I came up with this while investigating _connection refused by upstream_ errors in nginx-bigbluebutton.error.log because proxy_pass is configured with localhost instead of 127.0.01 in /etc/bigbluebutton/nginx/notes.nginx

I was shortly before to open also an ticket for this - but then I found this. That reduced the etherpad opening time to under 1 Second - compared to over 2 seconds with that ugly bug...

**Comment by pedrobmarin** [comment]
Closed in https://github.com/bigbluebutton/etherpad-lite/pull/11
