### ISSUE TITLE
support hiding usernames on whiteboard

### ISSUE THREAD

**Issue by oguzhancelikarslan** [bigbluebutton/bigbluebutton#10866]
Hey, thanks for building this great software!
I want to remove the name box with the color circle which represents the user while drawing on the presentation, two users at the same time. I tried to remove it by passing the CSS template but it did not work. its cuz it does not have any class or id. it is just an object.

Below object. How can I remove this one while two users drawing something?  Just circle is enough for me. 

`<g x="195.35264587402347" y="555.3751831054688"><circle cx="195.35264587402347" cy="555.3751831054688" r="4.708680142687277" fill="red" fill-opacity="0.6"></circle><g><rect fill="white" fill-opacity="0.8" x="202.8865341023231" y="553.4917110483939" width="64.03804994054697" height="16.015141944114152" stroke-width="0.9417360285374554" stroke="red" stroke-opacity="0.8"></rect><text x="195.35264587402347" y="555.3751831054688" dy="9.417360285374555" dx="9.417360285374555" font-family="Arial" font-weight="600" fill="red" fill-opacity="0.8" font-size="11.300832342449464" clip-path="url(#ZJY2bz4Sp6GkXnJDe)" text-anchor="start">Name Surname</text><clipPath id="ZJY2bz4Sp6GkXnJDe"><rect x="202.8865341023231" y="553.4917110483939" width="64.03804994054697" height="16.015141944114152"></rect></clipPath></g></g> `

**Comment by hiroshisuga** [comment]
If you are able to modify the source code (the official document nicely describes how to) and run it locally,
https://github.com/bigbluebutton/bigbluebutton/blob/develop/bigbluebutton-html5/imports/ui/components/presentation/cursor/component.jsx
should be the file that you need to touch. Hope it helps!

**Comment by oguzhancelikarslan** [comment]
> If you are able to modify the source code (the official document nicely describes how to) and run it locally,
> 
> https://github.com/bigbluebutton/bigbluebutton/blob/develop/bigbluebutton-html5/imports/ui/components/presentation/cursor/component.jsx
> 
> should be the file that you need to touch. Hope it helps!

if it is okay, can you share the docs' link with me?
