### ISSUE TITLE
hide webcam quality dropdown select

### ISSUE THREAD

**Issue by archidn** [bigbluebutton/bigbluebutton#10864]
bbb 2.2
How to hide webcam quality dropdown select combobox?
It appears even if only one quality profile is not hidden.
Since there is no effect from the choice of high or low quality, except for the load on the network, then I want to hide this list and not make users nervous by the presence of such an opportunity.
I only have found how to disable whole camera selection window
but camera selection is needed for me

**Comment by matiasilva** [comment]
For development help, use the mailing lists. https://bigbluebutton.org/community
