### ISSUE TITLE
Polling export

### ISSUE THREAD

**Issue by lfirewall1243** [bigbluebutton/bigbluebutton#10874]
Would be cool if the Moderator can export the Polls.
So that you can see who voted for what after a session. Its already show but only until you sumbit  the votings to the participants.

Maybe a csv export or so. Or that it is visisble for the moderator in a recording.....

**Comment by greenycat** [comment]
related #10771

**Comment by hiroshisuga** [comment]
this may help:
https://github.com/bigbluebutton/bbb-events

**Comment by manishkatyan** [comment]
Check this out: https://github.com/manishkatyan/bbb-admin#meeting-polls

meeting_poll.rb will extract polls answers from the given events.xml. The output is in JSON format that you can export and use are per your requirements.

**Comment by antobinary** [comment]
https://docs.bigbluebutton.org/2.4/new.html#learning-dashboard The Learning Dashboard shows this info and (depending on server config) can be accessible after the end of the meeting too
