### ISSUE TITLE
Error "presentation is too large" is not saying "how much exactly"

### ISSUE THREAD

**Issue by greenycat** [bigbluebutton/bigbluebutton#10872]
Please, fix it, this is easy fixable serious usability issue.

The error about too big file to upload may tickle badly your nerves right before the lesson.
**Instructor may use smaller presentations for weeks without even suspecting about this limit**  of X Mb.

Just imagine him, once upon a foggy morning starting a class with presentation of 35 Mb failing to upload, informing students to wait while in jerks and hassle he will be splitting it apart...
 
And more! Imagine he did cut it to 31 Mb but form says NOTHING but "File is too large"! 
Well, how much the large is? 
![03](https://user-images.githubusercontent.com/1878503/99743603-aee0b380-2ade-11eb-868b-7fadb12a665d.png)
Fig. 1 _It should say: "Allowed size X Mb, your file is Y Mb. Try to split presentation"_

**Expected behavior**
A user must be warned sooner about the limit with shown values in interface from configs. 
In UI practices, many upload forms take this value either from app configs or from server configs if app does not provide it.
I suppose, the upload form should show it more clear: 

![02](https://user-images.githubusercontent.com/1878503/99742810-f2d2b900-2adc-11eb-81e6-3a2005cb3531.png)
_Fig. 2 Users are warned._

Also, editing config value and changing it from 30 Mb to 50 Mb brings no luck.
There's still some unexposed settings...

**BBB version (optional):**
BigBlueButton Server 2.2.28 (2210)

**First face experience**
I stepped on those rakes yesterday before the class, having to pick size, because I was unaware of size 30, and server was too late to dig configs or reboot — there were many students in room already.

**Comment by antobinary** [comment]
Related to https://github.com/bigbluebutton/bigbluebutton/issues/8416
