### ISSUE TITLE
Get CPU and memory usage with BBB Api

### ISSUE THREAD

**Issue by pedped** [bigbluebutton/bigbluebutton#10871]
It is nice to have an in API in BBB to retrieve server CPU and Memory usage. As we can log the server CPU and Memory usage without installing any monitoring system.

**Comment by basisbit** [comment]
There exist lots of open source solutions exactly for this task already. Adding such a feature again would be considered [feature creep](https://en.wikipedia.org/wiki/Feature_creep).
When operating BigBlueButton servers, you'll definitely want to set up a server monitoring solution, just like you should do whenever you operate any online service on self-managed machines.
