### ISSUE TITLE
Raw files not exist, can't rebuild

### ISSUE THREAD

**Issue by aaswaisi** [bigbluebutton/bigbluebutton#10879]
when i do "bbb-record --rebuild" from recording >>>>>>>

root@s10932502:~# bbb-record --rebuild 0dff36e7291882275ac71be0a39648f6d314d926-1604123428230
Marking for rebuild 0dff36e7291882275ac71be0a39648f6d314d926-1604123428230
Raw files for 0dff36e7291882275ac71be0a39648f6d314d926-1604123428230 do not exist, can't rebuild

i need help..........

**Comment by basisbit** [comment]
For support requests, please use the [forum / mailing list](https://groups.google.com/forum/#!forum/bigbluebutton-users). This issue tracker here is only for BBB development related issues. Sorry.
