### ISSUE TITLE
Video synchronisation

### ISSUE THREAD

**Issue by sasidhar-serv** [bigbluebutton/bigbluebutton#10884]
we are using BBB latest 2.2.26, while playing a video from youtube link we are getting an issue "play the video to enable media synchronisation". let us know what can be the issue. only few students get these issues.

**Comment by basisbit** [comment]
For support requests, please use the [forum / mailing list](https://groups.google.com/forum/#!forum/bigbluebutton-setup). This issue tracker here is only for BBB development related issues. Sorry.
