### ISSUE TITLE
Ubuntu 16.04 reaches end of life in April 21

### ISSUE THREAD

**Issue by nough** [bigbluebutton/bigbluebutton#10883]
https://wiki.ubuntu.com/Releases

**The Issue**
Ubuntu 16.04.07 LTS reaches end of life in April 21, and while it will have extended security releases for another 3 years afterwards, these will be a paid option. This could leave many thousands of BigBlueButton servers unpatched.

Is there a plan to release BBB v2.3 on Ubuntu 18.04 before April 21?

**Comment by basisbit** [comment]
there exist various issue regarding this topic already. BBB 2.3.x uses Ubuntu 18.04.

**Comment by nough** [comment]
Fair enough - I searched and could not find any related to it. I am aware of 2.3.0 but was unsure if there was any plan to release it before April.

**Comment by basisbit** [comment]
The bbb team will have to release a stable 2.3 before april next year... (My personal opinion) If not, then a fork of BBB will do that.
