### ISSUE TITLE
Can I create personal room using BBB api?

### ISSUE THREAD

**Issue by noproblematall** [bigbluebutton/bigbluebutton#10880]
Hi,
I am creating personal rooms for each user in the greenlight admin dashboard manually. so, I can save a simple URL for each user(room) in the database and each user can use the simple URL. But I wanna automate this process. So, when each user registers to my website, I wanna create a simple URL for BBB through API automatically. Is there a way for this?
Thanks in advance.

**Comment by prlanzarin** [comment]
Mailing lists are the proper place for things like this.

https://docs.bigbluebutton.org/2.2/getting-help.html
