### ISSUE TITLE
Hotlink Protection of recordings

### ISSUE THREAD

**Issue by HomayGH** [bigbluebutton/bigbluebutton#10896]
If someone needs Hotlink Protection of recordings and preventing direct download, the following code can be added in nginx/sites-available/bigbluebutton

`location ~* \.(webm)$ {
    valid_referers EXAMPLE.COM;
    if ($invalid_referer) {
        return 403;
    }
root    /var/bigbluebutton/published;
} 
`

**Comment by aguerson** [comment]
`$invalid_referer` is a nginx global variable ?

In your case, EXAMPLE.COM is your domain ? bbb instance full name ?

**Comment by HomayGH** [comment]
yes. just replace your domain

> `$invalid_referer` is a nginx global variable ?
> 
> In your case, EXAMPLE.COM is your domain ? bbb instance full name ?

yes. its global. just replace example.com with your domain eg. github.com without any prefix/suffix

**Comment by erisd** [comment]
The ngx_http_referer_module module is used to block access to a site for requests with invalid values in the “Referer” header field. It should be kept in mind that **fabricating a request with an appropriate “Referer” field value is quite easy**, and so the intended purpose of this module is not to block such requests thoroughly but to block the mass flow of requests sent by regular browsers. It should also be taken into consideration that regular browsers may not send the “Referer” field even for valid requests. 

That's snakeoil protection. Please don't integrate that!
