### ISSUE TITLE
Coturn + chrome 401 Unauthorized

### ISSUE THREAD

**Issue by Foxprodev** [bigbluebutton/bigbluebutton#10899]
Firefox works. Chrome client sending no credentials to coturn. Checked using multiple PCs.

Coturn log
```
654: session 002000000000000002: realm <> user <>: incoming packet message processed, error 401: Unauthorized
655: session 002000000000000002: realm <> user <>: incoming packet message processed, error 401: Unauthorized
655: session 002000000000000002: realm <> user <>: incoming packet message processed, error 401: Unauthorized
655: session 002000000000000002: realm <> user <>: incoming packet message processed, error 401: Unauthorized
655: session 002000000000000002: realm <> user <>: incoming packet message processed, error 401: Unauthorized
655: session 002000000000000002: realm <> user <>: incoming packet message processed, error 401: Unauthorized
```

**To Reproduce**
Use coturn to pass the NAT

**Expected behavior**
Chrome client connects through coturn

**Actual behavior**
Only firefox users able to pass the NAT

**BBB version (optional):**
2.2.29

**Additional context**
I've got 2.2.0 instance as well and configs looks like identical. Works fine with chrome through coturn.

**Comment by Foxprodev** [comment]
@mariogasparoni Audio works using proper IceCandidate, because of external host in sip.nginx. At the same time there are 401 errors in coturn logs too. I know that there is a way to set external ip for video too, but i want TURN to work as fallback.

**Comment by wb7** [comment]
same here, also with Safari in iPadOS 14.2.

**Comment by mariogasparoni** [comment]
@Foxprodev thanks for the info. 
Can you reproduce this problem on https://demo.bigbluebutton.org ?

Also, what happens at client side ? 
I mean , does the user takes too long to connect to audio or video ? or maybe the video doesn't work for specific devices (which devices)

@wb7 Thanks for the info, can you also share what happens at client side ?

Thanks in advance

**Comment by Foxprodev** [comment]
@mariogasparoni does https://demo.bigbluebutton.org use coturn?

**Comment by mariogasparoni** [comment]
@Foxprodev it does use coturn. Unfortunately i am also having issues to connect to demo.bigbluebutton.org at this moment. Try again later, please

**Comment by eemirtekin** [comment]
> @mariogasparoni Audio works using proper IceCandidate, because of external host in sip.nginx. At the same time there are 401 errors in coturn logs too.
> I know that there is a way to set external ip for video too, but I want TURN to work as fallback.

This is same for me too.

**Comment by basisbit** [comment]
For support requests, please use the [forum / mailing list](https://groups.google.com/forum/#!forum/bigbluebutton-setup). This issue tracker here is only for BBB development related issues. Sorry.

I'd suggest you update your bbb server and follow the coturn install + configuration suggestions from https://docs.bigbluebutton.org/2.2/setup-turn-server.html#configure-coturn and make sure to use a current version of debian or ubuntu so that your coturn version is current.
