### ISSUE TITLE
I am unable to find BBB SDK for Android and iOS. is BBB planning for Android and iOS SDK ?

### ISSUE THREAD

**Issue by pankajnegi1893** [bigbluebutton/bigbluebutton#10893]
I am unable to find BBB SDK for Android and iOS. is BBB planning for Android and iOS SDK ? if there is any SDK for Android and iOS please let us know.

**Comment by basisbit** [comment]
BBB uses HTML5 and WebRTC. A SDK for building/integrating your own app is not yet being worked on. I am going to close this issue for now because there already exist a bunch of issues with similar questions and discussions on the bigbluebutton-dev mailing list.
