### ISSUE TITLE
Menu item "Write closed captions" enables them, but how to disable?

### ISSUE THREAD

**Issue by greenycat** [bigbluebutton/bigbluebutton#10897]
**Describe the bug**
One can enable Write closed captions from menu of settings as on image.
![001](https://user-images.githubusercontent.com/1878503/100126924-3df71e00-2e87-11eb-9feb-470b91d252e9.png)
But since it is on, there's no way to hide it back.

**To Reproduce**
Open it as moderator, then try to disable in current sessions.

**Expected behavior**
User should be able to get it closed or properly informed about impossibility to turn it off until session alive.

**Actual behavior**
![002](https://user-images.githubusercontent.com/1878503/100128186-a397da00-2e88-11eb-9299-f6a367f82b90.png)
Fig. 2 Functionality still on, no matter how the menu item is pressed.

**BBB version (optional):**
BigBlueButton Server 2.2.28 (2210)

**Desktop (please complete the following information):**
 - OS Windows 7, Chrome

**Smartphone (please complete the following information):**
 - Did not try

**Comment by PlumedArcher** [comment]
It's still a thing with the 2.3-alpha8 build.

**Comment by JustinMogel** [comment]
behavior still occurs on Version 2.3-alpha-8 (1511)

**Comment by pedrobmarin** [comment]
There is no closing option. Once you enabled there is no going back, you will have to live with your mistakes until the end of the meeting. It's a feature designed to build character.
