### ISSUE TITLE
Display Avatar into the HTML5

### ISSUE THREAD

**Issue by ic-armando-1992** [bigbluebutton/bigbluebutton#10909]
**Describe the bug**
I am sending the url for the custom avatar but it is doesnot displaying into the HTML5 client. could you tellme if i need to turn on a configuration into the server and if i need to do it, what's the path to do it.

**Comment by hiroshisuga** [comment]
In my understanding, no official release of BBB (neither 2.2.x nor 2.3a) supports user avatar URL (yet).

**Comment by itum** [comment]
i think this [topic ](https://github.com/bigbluebutton/bigbluebutton/pull/10458)related to your problem.

**Comment by antobinary** [comment]
Avatars are supported in 2.3.x https://github.com/bigbluebutton/bigbluebutton/pull/10458
