### ISSUE TITLE
Adjust the voice of the user you want.

### ISSUE THREAD

**Issue by barkinarga** [bigbluebutton/bigbluebutton#10901]
Different users have different loudnesses during the lesson, and we are very uncomfortable due to this situation. We should be able to adjust the voice of the user we want.

**Comment by almirayd** [comment]
YES IT'S SOOO TRUE

**Comment by FurkanZhlp** [comment]
It would be great 👍

**Comment by uka-support** [comment]
Users need to learn to adjust their microphone level. Allowing somebody else to do that opens up a can of worms.

**Comment by barkinarga** [comment]
> Users need to learn to adjust their microphone level. Allowing somebody else to do that opens up a can of worms.

It is hard to expect this from users in large classes, such a need would not arise if they did. If possible, it would be great to do this feature.

**Comment by axkibe** [comment]
> Users need to learn to adjust their microphone level. Allowing somebody else to do that opens up a can of worms.

As moderator/enabler of meetings I'd so wish for this feature. Yes someone could misuse it to "mute" them.. but well I could do that anyway?

I also really wish I'd had inbackground a "mixing console" I could adjust gains (audio values to be multiplied by on the server) of various people to make the whole meeting a more pleasant experience.

**Comment by axkibe** [comment]
Why did you close this?
