### ISSUE TITLE
Ability to view webpage URL and allow for whiteboard

### ISSUE THREAD

**Issue by paraviz02** [bigbluebutton/bigbluebutton#10904]
**Is your feature request related to a problem? Please describe.**
We have had a requirement to annotate a webpage "on the fly" (ie, not part of a planned presentation), which is not possible using screen sharing.

**Describe the solution you'd like**
It would be ideal to have a feature similar to loading a video link  where a webpage could be loaded/processed into a PDF or image (or similar) that scrolls any overflow, along with a whiteboard overlay for annotating.

**Describe alternatives you've considered**
We have tried sharing desktop screen to view a webpage, but it is difficult for some students to understand without being able to annotate.

**Additional context**
Realistically, with the right tools/capabilities installed, a presenter could load a page, print to PDF and upload that as a presentation for annotation, but it would be a multiple step process and also dependent on the user's capabilities. This would be more for convenience and to streamline instruction by the presenter.

**Comment by Jossef-767** [comment]
checkout epic-pen.com - whiteboard overlay for annotating on screen when sharing desktop
