### ISSUE TITLE
User in userlist options menu UI is broken on 2.3 from Android

### ISSUE THREAD

**Issue by daminebenq** [bigbluebutton/bigbluebutton#10915]
Bug found on a SM-A31 device **Android latest version** using **chrome mobile browser**, Not sure if this happens also on **iPhone**
**PS: this only happens with 2.3 latest version**

<img src="https://user-images.githubusercontent.com/5144311/100460528-18942b00-30a6-11eb-9a10-f22503895f8f.gif" width="60%" height="60%" />

**Comment by basisbit** [comment]
please edit your issue description and use the template text which you can find when creating a new issue.
