### ISSUE TITLE
BigBlueButton not working on Webview android app

### ISSUE THREAD

**Issue by Naveendodda** [bigbluebutton/bigbluebutton#10913]
Hi Team,
We are trying integrate  BigBlueButton as a web view app ionic-v4 app web site Loding fine . We are getting below error when try to load the conference "It looks like you are using an older version of supported browser. Please upgrade your browser for full support" Any ideas?

![WhatsApp Image 2020-11-23 at 5 12 52 PM](https://user-images.githubusercontent.com/54097808/100454007-0801a600-30e2-11eb-9505-3d8feacd6ba8.jpeg)

**Comment by sreegithck** [comment]
You need to set UserAgentString like follows


webView.getSettings().setUserAgentString("Mozilla/5.0 (Linux; Android 9; Pixel 3 XL) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.97 Mobile Safari/537.36");

**Comment by Naveendodda** [comment]
Thanks you for your response sir . where to add  above code .i.e mens client side or server side

**Comment by basisbit** [comment]
closing this because there exist various duplicates already.

**Comment by Naveendodda** [comment]
I tried with same for Android working but IOS not working

**Comment by Naveendodda** [comment]
Hi Team  
I amFacing issue below Please suggest me  


![Simulator Screen Shot - iPod touch (7th generation) - 2020-12-01 at 09 29 00](https://user-images.githubusercontent.com/54097808/100740927-79ea3000-33ff-11eb-9b9a-766ff630fcf1.png)
