### ISSUE TITLE
2.3-alpha: Closing menu fails on mobile device view

### ISSUE THREAD

**Issue by uzeportal** [bigbluebutton/bigbluebutton#10911]
Hello, after the bigbluebutton updated to the latest version, I ran into the following two problems. 

1- When users who connect to the session from the phone, go to the chat window, they cannot switch to the presentation window again. 

2- The session does not end when the moderator exits.

**Comment by uka-support** [comment]
Please provide the information suggested in the issue template: Which BBB version are you running (bbb-conf --check), which phones do your users use?

The session will not end automatically if moderator exits. The moderator needs to terminate the session, Otherwise it will end when nobody is in there anymore.

**Comment by uzeportal** [comment]
Hello, thank you for your answer. BBB version information is as follows. My users log in from android and ios phones. Both options give the same error.


BigBlueButton Server 2.3.0-dev (1323)
                    Kernel version: 4.15.0-124-generic
                      Distribution: Ubuntu 18.04.5 LTS (64-bit)
                            Memory: 10231 MB
                         CPU cores: 8

**Comment by uzeportal** [comment]
I wonder if anyone can help about this issue or will the problem be fixed with the new update?

**Comment by KDSBrowne** [comment]
Can anyone confirm this is still an issue? I was not able to reproduce on the android devices I tried. 

@antobinary, Is the session supposed to end if the moderator leaves?

**Comment by antobinary** [comment]
> Is the session supposed to end if the moderator leaves?

https://github.com/bigbluebutton/bigbluebutton/issues/6116 - depending on the configuration, and it may be broken - it's one of the remaining 2.3 items (currently)

**Comment by daminebenq** [comment]
Hi @uzeportal, thank you for reporting this 
I really couldn't reproduce this on ios or android

iOS Device used:
![image](https://user-images.githubusercontent.com/5144311/107384578-dbe6a600-6ad0-11eb-942d-5c909f4bc01a.png)

iOS Recorded proof:
https://user-images.githubusercontent.com/5144311/107385055-4ef01c80-6ad1-11eb-81a2-aae491875f6b.mp4


Android Device used:
![image](https://user-images.githubusercontent.com/5144311/107384909-29631300-6ad1-11eb-9f3c-53aeeed23cff.png)

Android Recorded proof:

https://user-images.githubusercontent.com/5144311/107384970-37b12f00-6ad1-11eb-913c-b2b247f6a2b0.mp4


Can you please send tell us what device are you using to reproduce it and what browser ?
Thanks again !

**Comment by antobinary** [comment]
If this is reproducible in the future we can re-open it. Right now it's not reproducible by QA and we are missing the right steps
