### ISSUE TITLE
Manually set dial-in PIN?

### ISSUE THREAD

**Issue by iam-TJ** [bigbluebutton/bigbluebutton#10916]
**Describe the bug**
bbb-apps                              1:2.2.0-47

Unable to set dial-in PIN.

Our scenario is a blind charity about to hold an annual general meeting and using BBB + dial-in to ensure visually impaired people can take part.

Notice of AGM had to be sent out several weeks ago. That included instructions on how to access via web and dial-in. Obviously we had to publish the dial-in PIN at that time.

Since then BBB needed to be restarted and the dial-in PIN for the room has changed. We need a way to force that PIN to be the original that was published.

I assume this is going to require some ruby hack, or locating and altering a database table, or poking memory, but there needs to be a way to achieve this.

**Comment by iam-TJ** [comment]
From digging through the code it seems it comes down to:

`bbb-common-web/src/main/java/org/bigbluebutton/api/ParamsProcessorUtil.java::processCreateParams()`:
```
String telVoice = processTelVoice(params.get(ApiParams.VOICE_BRIDGE));
```
where `processTelVoice()` will generate a random number if `ApiParams.VOICE_BRIDGE` is null:
```
public String processTelVoice(String telNum) {
    return StringUtils.isEmpty(telNum) ? RandomStringUtils.randomNumeric(defaultNumDigitsForTelVoice) : telNum;
}
```
So the question is how can we control VOICE_BRIDGE ?

**Comment by iam-TJ** [comment]
Getting further. The freeswitch log contains entries that mention the current PIN, e.g. where the PIN is 50638 I find in `/opt/freeswitch/var/log/freeswitch/freeswitch.log`:
```
Dialplan: sofia/external/w_x7x3owij7lfk_1-bbbID-Tj@example.org Action set(vbridge=50638)
EXECUTE [depth=0] sofia/external/w_x7x3owij7lfk_1-bbbID-Tj@example.org set(vbridge=50638)
[DEBUG] mod_dptools.c:1672 SET sofia/external/w_x7x3owij7lfk_1-bbbID-Tj@example.org [vbridge]=[50638]
```
and `vbridge=` seems to map to bbb's `params.voiceBridge` at `bigbluebutton-web/grails-app/controllers/org/bigbluebutton/web/controllers/ApiController.groovy`:
```
    // Ensure unique TelVoice. Uniqueness is not guaranteed by paramsProcessorUtil.
    if (!params.voiceBridge) {
      // Try up to 10 times. We should find a valid telVoice quickly unless
      // the server hosts ~100k meetings (default 5-digit telVoice)
      for (int i in 1..10) {
        String telVoice = paramsProcessorUtil.processTelVoice("");
        if (!meetingService.getNotEndedMeetingWithTelVoice(telVoice)) {
          params.voiceBridge = telVoice;
          break;
        }
      }
      // Still no unique voiceBridge found? Let createMeeting handle it.
    }

    Meeting newMeeting = paramsProcessorUtil.processCreateParams(params)
```
This is in the Groovy  `create` definition that begins by readsing some input into `params` :
```
  /***********************************
   * CREATE (API)
   ***********************************/
  def create = {
    String API_CALL = 'create'
    log.debug CONTROLLER_NAME + "#${API_CALL}"
    log.debug request.getParameterMap().toMapString()

    //sanitizeInput
    params.each {
      key, value -> params[key] = sanitizeInput(value)
    }
```
The debug logging here appears to match the run-time logging in `/var/log/bigbluebutton/bbb-web.log` where I find:
```
91:2020-11-27T14:25:21.514Z DEBUG o.b.web.controllers.ApiController - ApiController#create
92:2020-11-27T14:25:21.514Z DEBUG o.b.web.controllers.ApiController - [attendeePW:[password], guestPolicy:[ASK_MODERATOR], logoutURL:[https://example.org/b/slb-sb8-dqq-kv4/logout], meetingID:[kwygbggbki9zowqkdrwjtnaefzb2y8sqkmvnigna], meta_bbb-origin:[Greenlight], meta_bbb-origin-server-name:[example.org], meta_bbb-origin-version:[2.7.1], meta_gl-listed:[false], moderatorOnlyMessage:[To invite someone to the meeting, send them this link:

https://example.org/b/slb-sb8-dqq-kv4], moderatorPW:[password], muteOnStart:[true], name:[AGM], record:[false], checksum:[ab7a0e83d67d
cf5dc132383489713fd63556f025]]
```
Combined with the previous code it seems like, if there is a way to set `param.voiceBridge` in the call to `ApiController.create()` the randomisation statements would be by-passed.

**Comment by iam-TJ** [comment]
API  response is defined via FMPP  at `bigbluebutton-web/src/main/webapp/WEB-INF/freemarker/create-meeting.ftlx` :
```
<#ftl output_format="XML" auto_esc=true>
<#compress>
<response>
    <#-- Where code is a 'SUCCESS' String -->
    <returncode>${returnCode}</returncode>
    <meetingID>${meeting.getExternalId()}</meetingID> <#-- Yielded -->
    <internalMeetingID>${meeting.getInternalId()}</internalMeetingID> <#-- Yielded -->
    <parentMeetingID>${meeting.getParentMeetingId()}</parentMeetingID> <#-- Yielded -->
    <attendeePW>${meeting.getViewerPassword()}</attendeePW> <#-- Yielded -->
    <moderatorPW>${meeting.getModeratorPassword()}</moderatorPW> <#-- Yielded -->
    <createTime>${meeting.getCreateTime()?c}</createTime>
    <voiceBridge>${meeting.getTelVoice()}</voiceBridge> <#-- Yielded -->
    <dialNumber>${meeting.getDialNumber()}</dialNumber> <#-- Yielded -->
    <createDate>${createdOn}</createDate>
    <hasUserJoined>${meeting.hasUserJoined()?c}</hasUserJoined>
    <duration>${meeting.getDuration()?c}</duration>
    <hasBeenForciblyEnded>${meeting.isForciblyEnded()?c}</hasBeenForciblyEnded>
    <messageKey>${msgKey!}</messageKey>
    <message>${msg!}</message>
</response>
</#compress>
```
This is used from `bbb-common-web/src/main/java/org/bigbluebutton/api/util/ResponseBuilder.java::ResponseBuilder.buildMeeting()`
```
    public String buildMeeting(Meeting meeting, String msgKey, String msg, String returnCode) {
        StringWriter xmlText = new StringWriter();

        String createdOn = formatPrettyDate(meeting.getCreateTime());

        Map<String, Object> data = new HashMap<String, Object>();
        data.put("returnCode", returnCode);
        data.put("meeting", meeting);
        data.put("createdOn", createdOn);
        data.put("msgKey", msgKey);
        data.put("msg", msg);

        processData(getTemplate("create-meeting.ftlx"), data, xmlText);

        return xmlText.toString();
    }
```
which shows that `meeting.voiceBridge` should be defined by now and takes us to callers of `buildMeeting()`.
That leads to `bigbluebutton-web/grails-app/controllers/org/bigbluebutton/web/controllers/ApiController.groovy::respondWithConference()`:
```
  def respondWithConference(meeting, msgKey, msg) {
    response.addHeader("Cache-Control", "no-cache")
    withFormat {
      xml {
        log.debug "Rendering as xml"
        render(text: responseBuilder.buildMeeting(meeting, msgKey, msg, RESP_CODE_SUCCESS), contentType: "text/xml")
      }
    }
  }
```
and this takes us full circle back to `ApiController.create()` !
```
      // Still no unique voiceBridge found? Let createMeeting handle it.
    }

    Meeting newMeeting = paramsProcessorUtil.processCreateParams(params)

    if (meetingService.createMeeting(newMeeting)) {
      // See if the request came with pre-uploading of presentation.
      uploadDocuments(newMeeting);  //
      respondWithConference(newMeeting, null, null)
    } else {
```

**Comment by iam-TJ** [comment]
`bbb-lti/grails-app/services/org/bigbluebutton/BigbluebuttonService.groovy::getJoinURL()` mentions an `extended` mode that will set `voiceBridge` from `CUSTOM_VOICEBRIDGE` (key "`custom_voicebridge`") :
```
        if( "extended".equals(mode) ){
            voiceBridge = getValidatedBBBVoiceBridge(params.get(Parameter.CUSTOM_VOICEBRIDGE))
            record = getValidatedBBBRecord(params.get(Parameter.CUSTOM_RECORD)) || ltiService.allRecordedByDefault()
            duration = getValidatedBBBDuration(params.get(Parameter.CUSTOM_DURATION))
        }
```

In `bbb-lti/grails-app/controllers/org/bigbluebutton/lti/controllers/ToolController.groovy::doJoinMeeting()` is the only call to `BigBlueButtonService.getJoinURL()` passing in a `params` array. This method uses the other `CUSTOM_` values to set parameters but **does not** use `CUSTOM_VOICEBRIDGE` which rules out this route to setting it.

**Comment by defnull** [comment]
Perhaps I am missing something, but the `/create` API has a `voiceBridge` parameter that can be used to set the dailin pin. It must be unique, though, so the frontend must ensure uniqueness.

**Comment by iam-TJ** [comment]
@defnull  thank-you! I'd totally forgotten about doing it via ending and re-creating the room - i got tunnel vision trying to modify an active room.

Not a complete loss of time though since we're getting familiar with the code-base preparatory to making contributions.

**Comment by iam-TJ** [comment]
Unfortunately, even though creating the room with voiceBridge= works dial-in calls fail with an instant disconnect for the caller.

Freeswitch logs:
```
Dialplan: sofia/external/07395493665@46.31.225.185 Regex (FAIL) [check_if_conference_active] ${conference ${pi
n} list}(-ERR Conference 26708 not found
```

**Comment by defnull** [comment]
There must be at least one voice participant in the meeting before the conference exists in freeswitch and dail-in can work.

**Comment by iam-TJ** [comment]
@defnull  Thank-you once again! I had a web client in the room but microphone was disabled and the browser tab was buried behind many others so I missed that.

**Comment by GhaziTriki** [comment]
@iam-TJ Can you please close this issue if it has been fixed?

**Comment by basisbit** [comment]
Closing this issue because the pin can be set by the frontend within the create call Regarding the problem of not being able to call in unless someone already joined the freeswitch call previously, there already exists another issue for that.
