### ISSUE TITLE
Missing space between words

### ISSUE THREAD

**Issue by Dennis1993** [bigbluebutton/bigbluebutton#10923]
**Describe the bug**
If you start a session the following text is shown:
"Um jemanden zur Konferenz einzuladen, schicken Sie ihm diesen Link:https://onlineunterricht.stmichaelrealschule.de/b/jan-sps-pxz-eyk"
There is a missing space: "Link:https...."
It's better to write "Link: https....." because the link is not breaking. See:
![image](https://user-images.githubusercontent.com/1473674/100499140-72105e80-3167-11eb-9230-20646bac7860.png)

If we do a space between Link: and the URL it is better to read and longer URLs will be shown better:
![image](https://user-images.githubusercontent.com/1473674/100499093-1c3bb680-3167-11eb-98ff-5542051e4631.png)

**To Reproduce**
1. Start a new session
2. See the welcome message and below the info to invite pupils

**Expected behavior**
Space between the words and a breaking function to see the full URL

**Actual behavior**
URL is cutted and the text is hard to read

**BBB version (optional):**
2.2.30

**Desktop (please complete the following information):**
Microsoft Edge

**Comment by Dennis1993** [comment]
May be it is a problem in greenlight?
Then please move this Issue to greenlight. I'm not sure where is right place, sorry!

**Comment by hiroshisuga** [comment]
https://github.com/bigbluebutton/greenlight/pull/2309

**Comment by Dennis1993** [comment]
Thanks! That's the same, I close it. :)
