### ISSUE TITLE
Double canceling window on screen sharing

### ISSUE THREAD

**Issue by mabras** [bigbluebutton/bigbluebutton#10928]
**Describe the bug**
Double canceling window on screen sharing

**To Reproduce**
1. Using Chrome, Go to 'demo.bigbluebutton.org'
2. Click on Sharing screen button.
3. Cancel the window.

**Expected behavior**
Canceling screen sharing shows up one time.

**Actual behavior**
Canceling screen sharing shows up twice.

**Desktop (please complete the following information):**
 - OS: [Mac]
 - Browser [Chrome]

**Comment by basisbit** [comment]
Using test.bigbluebutton.org, I can reproduce the problem: join the session, click screen share button, click cancel in the selection window, then the windows is shown again. If you then press cancel again, the window closes and stays closed.
