### ISSUE TITLE
BBB 2.2.30 update silently reverts sipHack changes to /etc/bigbluebutton/nginx/sip.nginx

### ISSUE THREAD

**Issue by ichdasich** [bigbluebutton/bigbluebutton#10926]
**Describe the bug**
BBB 2.2.30 update silently reverts sipHack changes to /etc/bigbluebutton/nginx/sip.nginx, i.e., `s/http/https/` for the proxy statement.

**Additional context**
As this happens silently, it is extremely annoying to debug.

**Comment by basisbit** [comment]
not a fix for those BBB packaging issues, but a workaround: I'd suggest adding the commands to modify the config for the sipHack changes to your apply-config.sh or your ansible setup.
This issue should be fixed together with #9667 in bbb v2.2.31 when the sipHack is applied by default.

**Comment by ichdasich** [comment]
I know how to fix the symptom. However, I can not anticipate $everything and put it into apply-config.sh. I already shot myself in the foot with automating away too much in that file.

The underlying issue here is that there seems too be too much assumption and automation from BBB and its install scripts--see also the three-kurento-thing. Either the software should find a more stable balance, or really centralize all its automated configuration (kind of like an upstream apply-config.sh with a config file all in _one_ place).

**Comment by nzmhtpgl** [comment]
> I know how to fix the symptom. However, I can not anticipate $everything and put it into apply-config.sh. I already shot myself in the foot with automating away too much in that file.
> 
> The underlying issue here is that there seems too be too much assumption and automation from BBB and its install scripts--see also the three-kurento-thing. Either the software should find a more stable balance, or really centralize all its automated configuration (kind of like an upstream apply-config.sh with a config file all in _one_ place).

it was fixed yesterday
