### ISSUE TITLE
BBB updates to v2.2.31 without any release announcement

### ISSUE THREAD

**Issue by krishnateja-ct** [bigbluebutton/bigbluebutton#10929]
After running

> 	sudo apt update
> 	sudo apt upgrade -y

BBB updated to v2.2.31 instead of v2.2.30. Should we expect a new release soon or any technical error in packages versions released? I do not see any new release (i.e. v2.2.31) announcement being made at this point in time.

I notice bbb-config and bbb-html5 versions different.

Please refer to the screenshot of two different servers, 

This server was updated yesterday and now is running on v2.2.30
![Screenshot from 2020-11-30 17-33-50](https://user-images.githubusercontent.com/43333239/100608399-560ce880-3332-11eb-82b8-eb5f407f7eaa.png)
The output of bbb-conf --version
![Screenshot from 2020-11-30 17-34-12](https://user-images.githubusercontent.com/43333239/100608413-5c02c980-3332-11eb-8f6d-273a9da2acf7.png)

This is another server which was updated a few minutes ago from the time of this post
![Screenshot from 2020-11-30 17-35-14](https://user-images.githubusercontent.com/43333239/100608529-8c4a6800-3332-11eb-897b-45e79aa4ef85.png)
![Screenshot from 2020-11-30 17-35-38](https://user-images.githubusercontent.com/43333239/100608533-8ce2fe80-3332-11eb-9a5e-6499bcf17d3e.png)

**Comment by krishnateja-ct** [comment]
Please note:
The server with v2.2.31 mentioned in the issue was updated with the following command 

> sudo ./bbb-install.sh -v xenial-220-dev22a -e email -g -c turnServer -s FQDN -x

in the previous instance of BBB update to pull in early changes of v2.2.x-release branch.

**Comment by uka-support** [comment]
Why did you specify xenial-220-dev22a ? Just leave out the "-v" and it should pull the current release.
