### ISSUE TITLE
Do you plan another 2.3-alpha release?

### ISSUE THREAD

**Issue by Beiri22** [bigbluebutton/bigbluebutton#10939]
It has been some time from August (alpha-2) - so maybe it would be time for an alpha-3, so that users that are already experimenting with the alpha of 2.3 receive some of the bux fixes and features that are already done.

**Comment by ffdixon** [comment]
Yes, we are working towards 2.3-alpha3 release in the near future.   We are merging in the updates we're making from 2.2 into 2.3-dev.

**Comment by Beiri22** [comment]
That sounds good. I'm eagerly looking forward to St. Nicholas Day. Maybe, I'll find alpha-3 all of a sudden in my shoes ;-)

**Comment by basisbit** [comment]
Closing the issue because the question was answered :)
