### ISSUE TITLE
Turn off video and mic except presenter or list of selected people from dropdown

### ISSUE THREAD

**Issue by Akshay-Hegde** [bigbluebutton/bigbluebutton#10938]
Thanks for healthy opensource platform, few features probably enhance meeting overall performance, I am not sure whether this feature request is already in pipeline.

- Similar to turn off mic except presenter if we can have turn off mic and video and lock/disable video and mic button on client **except** `presenter or list of selected people from dropdown`  (in manage users )  we can probably avoid video from normal other audience, which can probably reduce number of stream, and then improve overall meeting performance.

This can really help many meetings in schools / colleges  where there will be 4-5  people in public talk /  debate / quiz competition rest all audience who will just have public chat to ask questions.

**Comment by FreeScholar** [comment]
This is a fantastic suggestion!
