### ISSUE TITLE
Do actions like sending messages or starting a poll via API

### ISSUE THREAD

**Issue by bmnds** [bigbluebutton/bigbluebutton#10937]
We have this particular use case where we need to communicate with the attendees during the meeting.

# Feature Request
I would like to either send a Message in the chat or start a Poll in a specific Meeting via API.

# Description
I've seen that a poll is created by sending a JSON like this one via websocket:
```JSON
{
    "msg": "added",
    "collection": "polls",
    "id": "ocj3AiLX29She7a2h",
    "fields": {
        "meetingId": "60188c22bfe949b50c1457551d1a7903f22ad4f8-1606764483300",
        "requester": "w_jlq0nc0tx4sb",
        "users": [],
        "id": "d2d9a672040fbde2a47a10bf6c37b6a4b5ae187f-1606764483314/1/1606764643283",
        "answers": [
            {
                "id": 0,
                "key": "True"
            },
            {
                "id": 1,
                "key": "False"
            }
        ]
    }
}
```

And that a message to the chat is sent via websocket with a JSON like this one:
```JSON
{
    "msg": "method",
    "method": "sendGroupChatMsg",
    "params": [
        "MAIN-PUBLIC-GROUP-CHAT",
        {
            "color": "0",
            "correlationId": "w_gkymm9rmzjqy-1606770914062",
            "sender": {
                "id": "w_gkymm9rmzjqy",
                "name": "Bruno Mendes"
            },
            "message": "this is a message sent to the chat"
        }
    ],
    "id": "56"
}
```

The question now is: does it make sense to provide these actions via API? If yes, what one should look at to be able to implement such functionality?

# Guidance
I'm not familiar with BigBlueButton code yet, but with some guidance on where to look to implement a new method in the API like this one (and its impact on the other components of the architecture) and I might be able to pull this out myself.

**Comment by hex-m** [comment]
Duplicate of #1660?

https://github.com/aau-zid/BigBlueButton-liveStreaming/ built a workaround to deliver messages to the chat afaik.

**Comment by solonsloop** [comment]
This is a good topic IMO given the need to spawn polls from central administration.  A related use-case is spawning a poll within  breakout rooms as a central administrator or teacher.  Currently, the only way I see to spawn the poll in Breakout rooms is to join each room and initiate a poll OR from the main room the admistrator can start a poll, which is available only in the main room browser window, requiring users to go to back to that window to complete the poll.  In this case the polling data is not connected to the breakout room (e.g., breakout room's meeting ID is not associated with the pollID or the answers).  If polls could be initiated via API as in the above example, the breakout room meetingID could be used to spawn the poll within the breakout room, and the data-layer would be consistent across both parent and child meetings.

**Comment by solonsloop** [comment]
@hex-m this is not a duplicate issue to live-streaming.
