### ISSUE TITLE
Human-Computer-Interface usability improvements.

### ISSUE THREAD

**Issue by axkibe** [bigbluebutton/bigbluebutton#10932]
First you for this awesome OpenSource Software, been using it for a few months now (via greenlight) and in total it has been great. (Version 2.2)

I've seen now a bunch of first time users approaching this and I suggest acceptance may be better if some superficial usability "papercuts" could be smoothened out. Yes it's superficial, but users form their opinion in a very short time and it's difficult after this to convince them, that beyond these it is actually really good...

* Most importantly I've watched presenter again and again struggling with uploading their first presentation. The welcome screen of the BBB has these blue bullet points that look like buttons, I've watched people keep trying to click them and then complaining they can't upload their presentation. The + and the lower left is quite hidden and it isn't obvious what it does. 

  * Suggestion:` renaming it to "Upload Presentation" (or making 3 buttons with start poll and share video or upload presentation and "more" for the less used options) and make the blue bullet points look less like buttons.

* After selecting a file for upload you have to click a second time to upload... 

  * Suggestion: I've also seen people struggling with this, I suggest removing the upload screen all together and make the upload directly in the home screen, without a second conformation.

* While it is converting a presentation you're client is basically blocked, you cannot mute/unmute yourself or do other things

  * Suggestion: Same as before, don't make it a separate screen.

* The welcome slide has a link to bigbluebutton.org, that is blue underlined which cannot be clicked. Because it is just a slide. To be honest, this one is a cristal-clear HCI violation. If something looks like a Link it has to be one, or if it isn't it shouldn't look like one.

  * Suggestion: Remove the blue color and underlining of a "link" that cannot be clicked.

Otherwise, still BBB is our favorite conferencing/teaching solution. I wrote this, since I think it would be usability things that are easy to fix and would greatly improve first impressions.

**Comment by ckruetze** [comment]
Not sure if this is still an issue for you, but we have also had way too many users trying to click on the default presentation and expecting it to work as this presentation really looks like buttons.

A simple solution is add your own default presentation without the blue icons. but instead describe in it to use the blue buttons at the bottom of the screen.

**Comment by ffdixon** [comment]
Good feedback.

> While it is converting a presentation you're client is basically blocked, you cannot mute/unmute yourself or do other things

We did improve this in 2.3 where the uploading now happens in the background.  I think we're good with this one.

> The welcome slide has a link to bigbluebutton.org, that is blue underlined which cannot be clicked. Because it is just a slide. To be honest, this one is a cristal-clear HCI violation. If something looks like a Link it has to be one, or if it isn't it shouldn't look like one.

Yes, we need to improve the welcome slides to not make it look like clickable buttons.
