### ISSUE TITLE
Number of Breakout Rooms can't be set while a textbox is open in the presentation

### ISSUE THREAD

**Issue by NicoKnebel** [bigbluebutton/bigbluebutton#10931]
Hello,
I don't exactly know if this is a bug in BBB or Greenlight so please correct me, if this is the wrong project.

The number of Breakout Rooms can't be set, when the user has an "open" textbox on the presentation.

To Reproduce:
1. Join a room
2. On the Slide, go to tools an select the text
3. Click on the slide an create a textbox (you can write into it if you want ... doesn't matter)
4. Click on the "Manage user" button
5. Click on "Create Breakout Rooms"
6. Click on the pull-down menu for "Number of rooms"

Expected behavior
The pull-down menu should appear.

Actual behavior
Firefox: The pull-down menu does not appear.
Chrome: The pull-down menu does not appear or only for a split second and never again.

Testet on:
BBB version: 2.2.29 and test.bigbluebutton.org
OS: Linux
Browser: Firefox 83.0 and Google Chrome 87.0.4280.66

**Comment by antobinary** [comment]
Resolved for 2.2.x in https://github.com/bigbluebutton/bigbluebutton/pull/11240
