### ISSUE TITLE
Screenshare start became unreliable with 2.2.30

### ISSUE THREAD

**Issue by uka-support** [bigbluebutton/bigbluebutton#10944]
**Describe the bug**
After upgrading to 2.2.30 the screenshare function became very unreliable.

**To Reproduce**
I cannot reproduce it 100% but it was bad enough I restored the whole VM (need to snapshot next time...)

1. Start a meeting (use two browsers on same machine or another one remotely - doesn't matter)
2. Start screenshare (select window or screen)
3. Wait for the screenshare to appear

**Expected behavior**
After a few seconds the screen share should appear for all participants.

**Actual behavior**
Chome (87.0.4280.66 on Windows, 32 Bit) was least reliable in my test

- sometimes, nothing happens for several seconds, no local screen share appears, no reaction on other participant's browsers.
- sometimes, screen sharing starts locally and the rotating circles appear on the other participant's browsers, but it takes very long (30s or over a minute) for the screen share to appear

Firefox (78.5 ESR) was more reliable - screen share seemed to work most of the time.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chome (87.0.4280.66, Win32), Firefox (78.5 ESR Win32)

**Additional context**
Test was performed within the following environment:

- Client with a VPN connection to the company network (good bandwidth)
- company internal server (no public IP, only reachable internally)
- STUN etc. disabled as far as I know

A downgrade to 2.2.29 resolved the issue immediately. Screenshare works as expected in Firefox and Chrome (no other changes to the environment, just restored the VM from backup).

**Comment by prlanzarin** [comment]
Nothing really groundbreaking changed for screensharing in 2.2.30 (nor in the last couple of releases AFAIK).
Are you sure you haven't got any Kurento related configuration overwritten when upgrading from 2.2.29 to 2.2.30?

Configs like:
  - https://docs.bigbluebutton.org/2.2/configure-firewall.html#configure-bigbluebutton-to-work-with-your-firewall
  - externalAddress/externalIPv4
  - bbb-web#turn-stun-servers.xml

**Comment by uka-support** [comment]
There was one change regarding screensharing and akka in bbb-webrtc-sfu.

```apply-config.sh``` does the following here: (no change to 2.2.30)

- overwrite ```turn-stun-servers.xml```  - disable TURN/STUN since it's an internal-only system
- dito for ```/opt/freeswitch/conf/vars.xml```

Kurento config has not been not touched as far as I know - maybe I should add externalIPv4 to ```/etc/kurento/modules/kurento/WebRtcEndpoint.conf.ini```? But I didn't configure STUN for Kurento at all. Apart from ```WebRtcEndpoint.conf.ini``` (which has no active settings) is there another file where  there might be changes I've forgotten?

Thanks!

**Comment by prlanzarin** [comment]
> There was one change regarding screensharing and akka in bbb-webrtc-sfu.

I'm aware of the changes. None of them alter default screensharing behaviour, hence why I said there were no _groundbreaking_ changes.

Could try setting https://github.com/bigbluebutton/bbb-webrtc-sfu/blob/master/config/default.example.yml#L17 to false and testing again, though. Might be that mDNS candidate processing is garbling something with Chrome. Does the same thing happen for ie video?

Otherwise, can you please reproduce the problem and attach:
  - chrome://webrtc-internals dump
  - bbb-webrtc-sfu logs
  - kurento-media-server logs
  - client logs

for the session where you reproduced the issue.

**Comment by uka-support** [comment]
I performed the updated again but couldn't reproduce the problem afterwards (same environment, just a reboot of the client inbetween). Pretty strange. Sorry for the bogus report.

**Comment by prlanzarin** [comment]
No worries. Maybe some temporary instability in the internal network?
Anyways, if you find something else please reopen/ping me.
