### ISSUE TITLE
error 1020 after a spike in webcam connections to a room

### ISSUE THREAD

**Issue by IJOL** [bigbluebutton/bigbluebutton#10949]
Hi, Folks:

Yesterday, in a room with about 30 to 40 persons in, they decided to put about 30  web cameras on,  and suddenly they all of them started to see error 1020 and all the cameras in the HTML5 clients of every session gone berserk if we try to get to the room again with or without a camera, error 1020 again.

Tested in another empty room with only 2 users, and error 1020 too.

This morning after a bbb-conf --restart everything is working fine.. not tested before the restart.. ;(

The records show the cameras and everything is fine in this regard, cameras were no working in the live session but were ok in the record.

The Machine is about 10 times bigger in every aspect that the one named as Minimal setup stated in the docs,  but we seen after the camera thing break, a very high processor use, about 26 in top, and 2 processes at 300% to 400% processor, kurento and freeswitch

We have some questions:

Which is the software component that sends back camera stream to session users?

It's possible to restart this component without breaking every room, as bbb-conf --restart does? it closes every room.. without noticing the users at all.. only a brief non-connection message...

**Comment by basisbit** [comment]
For support requests, please use the [forum / mailing list](https://groups.google.com/forum/#!forum/bigbluebutton-setup). This issue tracker here is only for BBB development related issues. Sorry.
