### ISSUE TITLE
Persian or Arabic names shows up as a url encoded string randomly during sessions

### ISSUE THREAD

**Issue by mohammadalijf** [bigbluebutton/bigbluebutton#10948]
**Describe the bug**
Sometimes Persian or Arabic characters doesn't get decoded right during a session; hence, the name is unclear.

**To Reproduce**
happens randomly for participants with Persian or Arabic names

**Expected behavior**
the name shuld decode correctly. this is extracted from save-user-list.txt and decoded manually:
**احسان نیایش مهر**

**Actual behavior**
shows url encoded string for the same name

**%D8%A7%D8%AD%D8%B3%D8%A7%D9%86%20%D9%86%DB%8C%D8%A7%DB%8C%D8%B4%20%D9%85%D9%87%D8%B1**

**Screenshots**
![WhatsApp Image 2020-11-21 at 11 26 00 AM](https://user-images.githubusercontent.com/7884637/100849187-73a79280-3497-11eb-80e5-410cf6c8e980.jpeg)

**Comment by uka-support** [comment]
Could you please include the exact version of BBB you are running? - output of ```bbb-conf --check```.

Does it happen with all browsers? Does it happen with all names or just some or always with the same names?

**Comment by basisbit** [comment]
Also, which frontend do you use? This might be a bug in the frontend.

**Comment by mohammadalijf** [comment]
Sorry for late reply.
output of `sudo bbb-conf --check`:

```bash
BigBlueButton Server 2.2.30 (2264)
                    Kernel version: 4.4.0-197-generic
                      Distribution: Ubuntu 16.04.7 LTS (64-bit)
                            Memory: 24679 MB
                         CPU cores: 8

/usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties (bbb-web)
       bigbluebutton.web.serverURL:  {{domain}}
                defaultGuestPolicy: ALWAYS_ACCEPT
                 svgImagesRequired: true

/etc/nginx/sites-available/bigbluebutton (nginx)
                       server name: {{domain}}
                              port: 80, [::]:80
                              port: 443 ssl
                    bbb-client dir: /var/www/bigbluebutton

/var/www/bigbluebutton/client/conf/config.xml (bbb-client)
                Port test (tunnel): {{domain}}
                              red5: {{domain}}
              useWebrtcIfAvailable: true

/opt/freeswitch/etc/freeswitch/vars.xml (FreeSWITCH)
                       local_ip_v4: {{host_ip}}
                   external_rtp_ip: stun:stun.freeswitch.org
                   external_sip_ip: stun:stun.freeswitch.org

/opt/freeswitch/etc/freeswitch/sip_profiles/external.xml (FreeSWITCH)
                        ext-rtp-ip: $${local_ip_v4}
                        ext-sip-ip: $${local_ip_v4}
                        ws-binding: :5066
                       wss-binding: {{host_ip}}:7443

/usr/local/bigbluebutton/core/scripts/bigbluebutton.yml (record and playback)
                     playback_host: {{domain}}
                 playback_protocol: https
                            ffmpeg: 4.2.4-1ubuntu0.1bbb1~16.04.1

/etc/bigbluebutton/nginx/sip.nginx (sip.nginx)
                        proxy_pass: {{host_ip}}

/usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml (Kurento SFU)
                        kurento.ip: {{host_ip}}
                       kurento.url: ws://127.0.0.1:8888/kurento
                    kurento.sip_ip: {{host_ip}}
                    localIpAddress: {{host_ip}}
               recordScreenSharing: true
                     recordWebcams: true
                  codec_video_main: VP8
               codec_video_content: VP8

/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml (HTML5 client)
                             build: 1095
                        kurentoUrl: {{domain}}
                  enableListenOnly: true
```
**Does it happen with all browsers?**
well it shows url encoded string for everyone in the room so yeah.

**Does it happen with all names or just some or always with the same names?**
First it happened in one classroom (and the student used this opportunity to fool around, i had to dig into logs to find the student's real name, which by the way was not so easy and i think admins should have some kind of monitoring system over rooms and shared notes). after further investigation i realized this is happening on other classes as well but not as frequent. participants cannot change their name so my guess is that it happens randomly for some names.

**which frontend do you use?**
I use custom version of Greenlight forked from _release-2.7.11_. i didn't mess around with business logic and only played around with UI. It is possible that this is a bug with Greenlight where it fails to encode and pass proper query parameter to bigbluebutton. but i thought i should open an issue in BigBlueButton to make sure then move on to Greenlight.

**Comment by mohammadalijf** [comment]
also this is a save-user-text.txt exported when the user showed up with url encoded name.

```
فهرست کاربران حاضر در جلسه کلاس ششم یک در ۱۳۹۹/۹/۹:۱۰:۵۹:۰۹

مرتب شده بر اساس نام:
%D8%A7%D8%AD%D8%B3%D8%A7%D9%86%20%D9%86%DB%8C%D8%A7%DB%8C%D8%B4%20%D9%85%D9%87%D8%B1 
ali mokhtari
amirali khashabizadeh
Barman jafari nezhad
pourshirazi_teacher 
Sam Eslami
yashar parastar
احسان نیایش مهر
حسین برزگر
حمید رضا رحیمی
شهروز میرهادی
علی ایمانی
محمد متین چهره نگار
مهربد سرایی
  

مرتب شده بر اساس نام خانوادگی:
Sam Eslami
amirali khashabizadeh
ali mokhtari
Barman jafari nezhad
yashar parastar
علی ایمانی
حسین برزگر
حمید رضا رحیمی
مهربد سرایی
احسان نیایش مهر
شهروز میرهادی
محمد متین چهره نگار
%D8%A7%D8%AD%D8%B3%D8%A7%D9%86%20%D9%86%DB%8C%D8%A7%DB%8C%D8%B4%20%D9%85%D9%87%D8%B1 
pourshirazi_teacher 
```

as you can see both decoded and encoded version of the student name is present in the room at the same time

`%D8%A7%D8%AD%D8%B3%D8%A7%D9%86%20%D9%86%DB%8C%D8%A7%DB%8C%D8%B4%20%D9%85%D9%87%D8%B1`
and 
`احسان نیایش مهر`

**Comment by mojtaba82** [comment]
I have bbb version 2.2.31 and have same issue

**Comment by schrd** [comment]
@mohammadalijf @mojtaba82 can you please try to reproduce this on the public 2.3 test server: https://test23.bigbluebutton.org (API Demo) or https://test23.bigbluebutton.org/b (Greenlight)

**Comment by mohammadalijf** [comment]
@schrd This issue happens randomly and I have no idea how to reproduce it again. Same user with the same name sometimes does not get decoded properly. I tried greenlight demo server and I was not able to reproduce the bug

**Comment by mojtaba82** [comment]
@schrd Usually this issue happens when internet connection of that user is slow and user icon changea to phone as saw in screenshot that @mohammadalijf has sent.

**Comment by daminebenq** [comment]
Not sure how to reproduce this.

**Comment by alialic** [comment]
Has the problem been resolved? I also have this problem.

**Comment by antobinary** [comment]
> This issue happens randomly and I have no idea how to reproduce it again. Same user with the same name sometimes does not get decoded properly.

@alialic please share instructions how to reproduce this consistenly

**Comment by GhaziTriki** [comment]
@alialic What integration are you using? Looks like the names are encoded twice.

**Comment by hrsaberi** [comment]
راه حل پیدا شد؟
