### ISSUE TITLE
nextcloud integration

### ISSUE THREAD

**Issue by edmundlaugasson** [bigbluebutton/bigbluebutton#10947]
**Is your feature request related to a problem? Please describe.**
Would be very much appreciated, if there could be BBB integrated with Nextcloud. Currently there is integration by Nextcloud site - https://apps.nextcloud.com/apps/bbb - would be nice to respond and support integration also by BBB side.

**Describe the solution you'd like**
Integration should allow to configure, whether users can be created directly in BBB or not.
As current proposal is about integration with Nextcloud, then via Nextcloud should be all BBB be configurable. Also managing recordings, etc,

**Describe alternatives you've considered**
Perhaps use some other software instead of Moodle

**Comment by uka-support** [comment]
BBB does not have a concept of users outside of a running meeting. You need an interface like Greenlight or Moodle or the Nextcloud App you mention to actually start a meeting (which means: creating a meeting in BBB and being able to join there).

Please be more specific: what kind of functionality would you like in BBB regarding Nextcloud?

**Comment by edmundlaugasson** [comment]
Main goal is, that you can list Nextcloud here https://bigbluebutton.org/integrations/
Next thing: handle user management. E.g. prevent user creation outside Nextcloud.
Offer almost same functionality via Nextcloud as BBB has independently.
Allow to choose, where to save recordings in Nextcloud, also download them.
Currently not clear, where recordings are going.

**Comment by uka-support** [comment]
As I said: There are no users in BBB. Only Greenlight (which is often used as BBB Frontend) has users, but you don't need Greenlight at all if you use Nextcloud as the only frontend for creating meetings.

Recordings are stored on the BBB server, there is currently no simple download option (it's not one file but many with metadata).

I don't see anything which needs to be implemented on the BBB side here. That's all stuff for Nextcloud side - you can [access recordings via API](https://docs.bigbluebutton.org/dev/api.html#getrecordings) too.

Listing the integration on the web page is another issue - I cannot speak for BBB but I suppose the Nextcloud plugin might be sufficient to list Nextcloud there.

**Comment by edmundlaugasson** [comment]
Sure, [Greenlight can be uninstalled](https://docs.bigbluebutton.org/greenlight/gl-install.html#uninstall). Actually even now can recordings be accessed via Nextcloud. But it is not seen from Nextcloud, where they are stored and cannot also download or store in Nextcloud.
If Nextcloud plugin is sufficient, then do BBB people read current GitHub repository issues? Why haven't they noticed that plugin? It is not my business either to deal with such communications. Anyway, I can drop a line to BBB, if I find appropriate contact. But tried to dig at BBB website and couldn't find any contact. There are community and commercial support, but no direct contact. So, community is responsible, I guess current repository belongs to community either and therefore should notice soon or later current issue and list the integration, if it is sufficient.

**Comment by basisbit** [comment]
@edmundlaugasson can you please write title + short description + provide the logo (and a permission to use the logo if necessary)? That would make it less work for a core team member to edit that website.

**Comment by edmundlaugasson** [comment]
I am just regular user and no way connected either BBB or Nextcloud.
Although logo and its usage regulations can be found:
* https://bigbluebutton.org/wp-content/themes/bigbluebutton/library/images/bigbluebutton-logo.png
* https://bigbluebutton.org/trademark/

One example integration text can be found - https://moodle.com/certified-integrations/bigbluebutton/ - I guess would be suitable also for current case. Copying it also here:
_BigBlueButton is an open source web conferencing solution for online learning that provides real-time sharing of audio, video, slides, whiteboard, chat and screen. It also allows participants to join the conferences with their webcams and invite guest speakers._

**Comment by basisbit** [comment]
@ffdixon could Nextcloud be added to https://bigbluebutton.org/integrations/ ? The Nextcloud plugin is similar to the Drupal and Wordpress plugins. Then this here issue could be closed.

**Comment by digitalrevisor** [comment]
Has somebody managed to get recordings in NC app bigbluebutton to work properly? To record meetings, save them in NC as a movie or some other formats?

**Comment by edmundlaugasson** [comment]
Well, in my instance [it](https://apps.nextcloud.com/apps/bbb) seems to work, just takes a bit time to process the video.

**Comment by antobinary** [comment]
This is getting (at least partially) addressed in BigBlueButton 2.6. See https://github.com/bigbluebutton/bigbluebutton/pull/15251 for the UI and https://github.com/bigbluebutton/bigbluebutton/pull/14264 for the API

**Comment by GuiLeme** [comment]
Hi, Please, see if https://github.com/bigbluebutton/bigbluebutton.github.io/pull/480 covers your request! And as said in the PR, I will open some issues to report some tweaks and room for improvements!

**Comment by ffdixon** [comment]
Yay!
