### ISSUE TITLE
Ampersand (&) in room name gets converted to &amp; in recording name

### ISSUE THREAD

**Issue by floeschie** [bigbluebutton/bigbluebutton#10956]
When I use a room name with an ampersand in it, the name of recordings contain the html special char representation of the ampersand.

# Steps to reproduce
1. Create a room called "You & Me"
1. Start a session and record it
1. Wait for the recording to show up in the recording list
1. Check the name

# Expected results
The name of the recording is `You & Me`

# Actual results
The name of the recording is `You &amp; Me`

# Additional info
- Greenlight version 2.7.6

**Comment by mabras** [comment]
Dup of https://github.com/bigbluebutton/bigbluebutton/issues/10936 ?

**Comment by floeschie** [comment]
> Dup of #10936 ?

I have no idea if it's a duplicate, as #10936 sounds very technical to me, and the information provided in this issue seems a bit sparse…

**Comment by hd42** [comment]
Please note that the issue [#10271](https://github.com/bigbluebutton/bigbluebutton/issues/10271) that was closed as a duplicate referred to user names while this issue mentions room names. Probably those problems are related but may need to be fixed in different locations in the same way.

**Comment by ErikLtz** [comment]
Using the BBB API with GET URL:s use & as argument separator. A "real" & in user name or room name is thereby encoded into %26. It then seems to be re-encoded into &amp; entity, but then printed in several places without proper entity decoding.

(I'm currently replacing & in user and room names with a simple character in my BBB API calls to avoid this problem)

**Comment by jplatte** [comment]
Why does anybody ever set up this annoying bot? 😑

**Comment by jplatte** [comment]
Here's some activity for you, Mr. Bot.

**Comment by jplatte** [comment]
*activity*

**Comment by jplatte** [comment]
🤖🔨
