### ISSUE TITLE
some recodrs diseapred after last upgrade

### ISSUE THREAD

**Issue by matro91** [bigbluebutton/bigbluebutton#10952]
**Describe the bug**

I made the last update last Monday. Since all the recordings made from November 13th have disappeared. I tried running a bbb-record --rebuildall but it didn't change anything.

What can i do ? 
Thanks for your Help.
M.

**Comment by basisbit** [comment]
For support requests and such questions, please use the [forum / mailing list](https://groups.google.com/forum/#!forum/bigbluebutton-setup). This issue tracker here is only for BBB development related issues. Sorry.
