### ISSUE TITLE
HTML5 client stuck on 3 dots on Android

### ISSUE THREAD

**Issue by CamZie** [bigbluebutton/bigbluebutton#10957]
**Describe the bug**
When connecting to every session using Android the HTML5 client is stuck in loading with 3 dots. After a reload in the browser it will successfully connect.

**To Reproduce**
1. Go to 'Moodle app with BBB' using the Android phone
2. Click on 'Join session' on every room
3. Choose browser (Chrome, Edge or Firefox)
4. See loading stuck with 3 dots (only refresh will make it work)

**Expected behavior**
The HTML5 client will successfully connect on the first try.

**Actual behavior**
The HTML5 client will get stuck on the first try with the 3 loading dots. Only a reload of the browser will it successfully connect.

**Screenshots**
![android_chrome](https://user-images.githubusercontent.com/16030886/100986737-e6734500-354d-11eb-9d77-af00d03bf525.png)

**BBB version (optional):**
BigBlueButton Server 2.3.0-dev (1323)

**Smartphone (please complete the following information):**
 - OS: Android 10
- Browser and Version:
Chrome: 86.0.4240.198 
Firefox: 83.1.0
Edge: 45.11.4.5102

**Comment by mabras** [comment]
Try to inspect the page and share the logs (console tab).

**Comment by dom0** [comment]
We have the same behaviour on Firefox 84.0 on Linux and randomically on Google Chrome for Android.
Entering the room via demo app cause a page reload loop (it seems stucked on three dots but indeed page is quickly reloaded) and only a force reload (F5 or Ctrl-R) resolve the issue. There are no errors in browser dev console

**Comment by netbsdis** [comment]
I've seen this with FF 78.[56].0esr on NetBSD , server is BBB 2.2.26, for several days. It went away when I disabled _Open links in tabs instead of new windows_ but I can't reproduce it know even when re-enabling it, so something else must be happening. I'll report if I find something reproducible

**Comment by jlebleu** [comment]
Same problem on chrome with bbb dev version bbb-html5   1:2.3.0-1250 on ubuntu
Here is the error in console.log
Uncaught TypeError: Cannot read property 'offsetHeight' of null
    at x.handleScrollChange (​)
    at m (​)
    at _ (​)
    at b (​)
​ [18:38:52:0212]  INFO: clientLogger: Client loaded successfully H.componentDidMount (https://bbb.paquerette.eu/html5client/182f2536dec468523e9df5ffa8ef7b39f03e111e.js?meteor_js_resource=true:353:1061036)
​ [18:38:52:0263] ERROR: clientLogger: TypeError: Cannot read property 'offsetHeight' of null https://bbb.paquerette.eu/html5client/182f2536dec468523e9df5ffa8ef7b39f03e111e.js?meteor_js_resource=true:353:1346752
​ Uncaught TypeError: Cannot read property 'offsetHeight' of null
    at x.handleScrollChange (​)
    at m (​)
    at _ (​)
    at b (​)
​ [18:38:52:0347]  INFO: clientLogger: Client loaded successfully H.componentDidMount (https://bbb.paquerette.eu/html5client/182f2536dec468523e9df5ffa8ef7b39f03e111e.js?meteor_js_resource=true:353:1061036)
​ [18:38:52:0360] ERROR: clientLogger: TypeError: Cannot read property 'offsetHeight' of null https://bbb.paquerette.eu/html5client/182f2536dec468523e9df5ffa8ef7b39f03e111e.js?meteor_js_resource=true:353:1346752
​ Uncaught TypeError: Cannot read property 'offsetHeight' of null
    at x.handleScrollChange (​)
    at m (​)
    at _ (​)
    at b (​)

**Comment by jlebleu** [comment]
Updated to the last dev version (1:2.3.0-1312) and I have still the same issue

**Comment by dhebert91** [comment]
Hello,
I have the same issue (with the last version either). 
Every chrome or chromium client will get stuck on the first try with the 3 loading dots. Only a reload of the browser will it successfully connect. 
It works correctly with Firefox.
I use BBB on other instances and it works correctly with Chrome.
Any idea? I can't open our visio service untill it is not solved.
Thank's
Dominique

**Comment by robregonm** [comment]
I have the same issue in both Android (Chrome) and Safari (iOS), however, version 2.2 works perfectly.
So it seems that issue is only present in 2.3.

**Comment by jlebleu** [comment]
Upgraded my dev server to alpha5 seems to be ok now to be confirmed

**Comment by antobinary** [comment]
If you are able to reproduce at some point in the future, please open new issue and reference this one. It seems resolved for now
