### ISSUE TITLE
Update 2.2.2x to BBB 2.2.X - 2.2.31 - 1007 error with TURN STUN activated

### ISSUE THREAD

**Issue by aguerson** [bigbluebutton/bigbluebutton#10954]
Hi guys,

I am testing the last 2.2.X ( updated today 02.12.2020 )  - Release 2.2.31 - html5ClientBuild: 1102

For some reasons, I encoutered a 1007 error to connect with MIC.

I have a STUN/TURN in front of the BBB Instance.

I tried with and without the hack described here https://github.com/bigbluebutton/bigbluebutton/issues/9667#issuecomment-727598755

But nothing.

If I open UDP Ports for the trafic coming from outside, no more 1007 error.

When I check on the TURN/STUN server, I feel like I don't see the traffic coming from freeswitch anymore.

Did you introduce something in 2.2.29 or 2.2.30 to not use TURN/STUN for freeswitch ?

In 2.2.28, everything was OK...

I have no NAT, everything is on public IPs

My conf

`in /usr/share/bbb-web/WEB-INF/classes/spring/turn-stun-servers.xml`

```
<?xml version="1.0" encoding="UTF-8"?>
<!--

BigBlueButton open source conferencing system - http://www.bigbluebutton.org/

Copyright (c) 2012 BigBlueButton Inc. and by respective authors (see below).

This program is free software; you can redistribute it and/or modify it under the
terms of the GNU Lesser General Public License as published by the Free Software
Foundation; either version 3.0 of the License, or (at your option) any later
version.

BigBlueButton is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public License along
with BigBlueButton; if not, see <http://www.gnu.org/licenses/>.

-->
<beans xmlns="http://www.springframework.org/schema/beans"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.springframework.org/schema/beans
            http://www.springframework.org/schema/beans/spring-beans-2.5.xsd">

    <bean id="stun0" class="org.bigbluebutton.web.services.turn.StunServer">
        <constructor-arg index="0" value="stun:ts.domain"/>
    </bean>

    <!-- Turn servers are configured with a secret that's compatible with
         http://tools.ietf.org/html/draft-uberti-behave-turn-rest-00
         as supported by the coturn and rfc5766-turn-server turn servers -->

    <bean id="turn0" class="org.bigbluebutton.web.services.turn.TurnServer">
        <constructor-arg index="0" value="xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"/>
        <constructor-arg index="1" value="turns:ts.domain:443?transport=tcp"/>
        <!--TTL in seconds for shared secret-->
        <constructor-arg index="2" value="86400"/>
    </bean>

    <bean id="turn1" class="org.bigbluebutton.web.services.turn.TurnServer">
        <constructor-arg index="0" value="xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"/>
        <constructor-arg index="1" value="turn:ts.domain:443?transport=tcp"/>
        <constructor-arg index="2" value="86400"/>
    </bean>

   <bean id="stunTurnService" class="org.bigbluebutton.web.services.turn.StunTurnService">
        <property name="stunServers">
            <set>
                <ref bean="stun0" />
            </set>
        </property>
        <property name="turnServers">
            <set>
                <ref bean="turn0" />
                <ref bean="turn1" />
            </set>
        </property>
        <!--
        <property name="remoteIceCandidates">
            <set>
        /-->
                <!--ref bean="iceCandidate1" /-->
                <!--ref bean="iceCandidate2" /-->
        <!--
            </set>
        </property>
        /-->
    </bean>
</beans>

```
`in /etc/kurento/modules/kurento/WebRtcEndpoint.conf.ini`
```

networkInterfaces=eth0
stunServerAddress=${public ip v4 of stun/turn server}
stunServerPort=3478
pemCertificateRSA=/etc/kurento/dtls-srtp.pem
externalIPv4=${public ip v4 of bbb instance}
niceAgentIceTcp=0
```

On the STUN/TURN server 

`in /etc/turnserver.conf`

```
listening-port=3478
tls-listening-port=443
listening-ip=${public ip v4 of stun/turn server}
fingerprint
lt-cred-mech
use-auth-secret
static-auth-secret=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
realm=ts.domain
cert=/etc/ssl/certs/ca_chain.pem
pkey=/etc/ssl/private/private.key
cipher-list="ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:ECDH+3DES:DH+3DES:RSA+AESGCM:RSA+AES:RSA+3DES:!aNULL:!MD5:!DSS:!AES256"
dh2066
log-file=/var/log/coturn.log
simple-log
no-loopback-peers
no-multicast-peers
proc-user=turnserver
proc-group=turnserver
no-cli
no-tlsv1
no-tlsv1_1
```

**Comment by aguerson** [comment]
To complete.
To resolve the problem, I need to open these ports

`iptables -t filter -A INPUT -m state --state NEW -m udp -p udp --dport 16384:32768 -j ACCEPT`

**Comment by aguerson** [comment]
```
https://docs.bigbluebutton.org/2.2/configure-firewall.html

=> UDP ports in the range 16384 - 32768 (for FreeSWITCH/HTML5 RTP streams)
```

**Comment by aguerson** [comment]
In 2.2.28, from the client, I saw a connection on TCP 443 on the BBB Instance, and another connection on TCP 443 on the STUN / TURN server...

Since 2.2.31, The client need to connect to UDP ports directly to the BBB Instance, like described in the doc... 

What is wrong in my conf ?

**Comment by basisbit** [comment]
For support requests, please use the [forum / mailing list](https://groups.google.com/forum/#!forum/bigbluebutton-setup). This issue tracker here is only for BBB development related issues. Sorry.

**Comment by basisbit** [comment]
also see https://docs.bigbluebutton.org/2.2/customize.html#networking
It lists the ports which you'll have to open to the internet. Clients should only use the TURN server if all other options don't work. The sipHack only helps against Freeswitch rarely freezing on systems with high load after a couple of days.

**Comment by aguerson** [comment]
Excuse me guys, what ?
It is not an answer.

You can say to the people using BBB to let all UDP port open to the Internet !

TURN is used for security reason.

So did you have change something between 2.2.28 and 2.2.31+ ?

I've been supporting the project for almost 10 months, a little help wouldn't be a bad thing...

@basisbit @ffdixon @pedrobmarin 

A litle help ? I just want to know about the change between 2.2.28 and 2.2.31+.
I saw a update of Kurento, but in my case, it seems the problem come from the relation between freeswitch and coturn.
In the BBB demo, do you use a coturn server in front of your instance ?
Could you test ?

The test is simple.
BBB instance only accept 443 from Internet
BBB instance accept all the trafic between himself and the cortun server ( UDP + TCP )
coturn server only accept 443 from Internet 
coturn server accept all the trafic between himself and BBB instance ( UDP + TCP )
apply my conf ( Kurento and stun turn xml file )
Test to connect to BBB, and see if you have a 1007 error.

Maybe the problem is not inside BBB... But all was OK in 2.2.28....

Thanks in advance,
Regards,
Aurélien.

**Comment by basisbit** [comment]
The issue was closed because you should use the mailing list for such a support request.

**Comment by aguerson** [comment]
OK @basisbit.

I don't undestrand when to post on Google forum, and when to open an issue to github.
At the end, there is a help and maybe a PR.
It is better to have one entry point ( it is my opinion ). Maybe I don't have all the overview...

Sure it take time to resolve some problems. But it is win win in most cases.

I will search by myself...

Thanks.
Aurélien.

**Comment by prlanzarin** [comment]
@aguerson  Need a bit more info:

- Can you reproduce it with Kurento-based modules (ie video), or it only happens with microphone?
- Can you reproduce the problem by 1) opening all UDP ports 2) forcing relay usage in Firefox (about:config -> media.peerconnection.ice.relay_only -> true) ?
- Can you please do the following
  * Get your setup in order (UDP closed, rely only on TURN)
  * Open chrome://webrtc-internals
  * Reproduce the problem in Chrome
  * Save the chrome://webrtc-internals dump, attach it here
  * Attach Chrome's console logs

Also, a bit of friendly advice: don't lash out on people that are trying to keep the repo issues in order. You may notice we're having a hard time to keep them in check (1.3k issues, most of them are bogus support requests; I'm not saying it's your case, but that's what basisbit and other volunteers try to keep in check when they do this).

Mailing lists usually are a better first approach due to the following rationale: you open a thread there, you look for help. You either solve your problem (which, let's suppose, is some sort of misconfiguration somewhere) OR you discover that it's indeed a regression in BBB, which then warrants an issue in BBBs repo so we can "officially" keep track of it.

**Comment by aguerson** [comment]
@prlanzarin You are right.
But If I found a configuration problem, or a kind of bad mecanism with TURN, it could be good for others users to find this kind of infos in the official documentation.
I will check what you asked me ;)

**Comment by aguerson** [comment]
@prlanzarin @basisbit 

Just a precision

I read this https://github.com/Kurento/bugtracker/issues/461#issuecomment-737941153
I read this https://doc-kurento.readthedocs.io/en/latest/user/faq.html#how-to-configure-stun-turn-in-kurento
I read this https://github.com/bigbluebutton/bigbluebutton.github.io/pull/138#issuecomment-737963362
I read this https://github.com/bigbluebutton/bbb-install/issues/157

Do you think my actual configuration  is good, or do I need to use 2 coturns servers as described is the issues ?
Just to be sure.

I have many server, I can do manay tests on it with differents configs and I can simulate trafic with bbb Bots ( like you I think ), but in my case I don't develop for the BBB project, maybe I have a little more time to help you to test the conf to help you in the documentation. Always win win ;). Just in case ;)
BBB is really good project.

Regards,
Aurélien.

**Comment by aguerson** [comment]
@prlanzarin @basisbit you had right.

The problem was mine.

1) I had a cache in firefox
2) I had a link between a local vpn and the bbb infra

Thanks for you help.
The conf was good.

I updated it with this preconisation https://www.rtcsec.com/post/2020/04/how-we-abused-slacks-turn-servers-to-gain-access-to-internal-services/

```
listening-port=3478
tls-listening-port=443
listening-ip=${ip_stun_turn_server}
verbose
Verbose
fingerprint

#lt-cred-mech

use-auth-secret

static-auth-secret=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

realm=hostname.domain

cert=/etc/ssl/certs/cachain.pem
pkey=/etc/ssl/private/my.key

cipher-list="ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:ECDH+3DES:DH+3DES:RSA+AESGCM:RSA+AES:RSA+3DES:!aNULL:!MD5:!DSS:!AES256"

dh2066

log-file=/var/log/coturn.log

simple-log

no-loopback-peers

no-multicast-peers

proc-user=turnserver
proc-group=turnserver

no-cli

no-tlsv1
no-tlsv1_1

denied-peer-ip=0.0.0.0-0.255.255.255
denied-peer-ip=10.0.0.0-10.255.255.255
denied-peer-ip=100.64.0.0-100.127.255.255
denied-peer-ip=127.0.0.0-127.255.255.255
denied-peer-ip=169.254.0.0-169.254.255.255
denied-peer-ip=172.16.0.0-172.31.255.255
denied-peer-ip=192.0.0.0-192.0.0.255
denied-peer-ip=192.0.2.0-192.0.2.255
denied-peer-ip=192.88.99.0-192.88.99.255
denied-peer-ip=192.168.0.0-192.168.255.255
denied-peer-ip=198.18.0.0-198.19.255.255
denied-peer-ip=198.51.100.0-198.51.100.255
denied-peer-ip=203.0.113.0-203.0.113.255
denied-peer-ip=240.0.0.0-255.255.255.255
```
