### ISSUE TITLE
Blue screen when i finish installation and test demo

### ISSUE THREAD

**Issue by malogo** [bigbluebutton/bigbluebutton#10951]
Hi, I'm new to BBB. Once I finished installing the latest available BigBlueButton Server 2.2.30 version, when trying to load the demo, I get a blue screen without any error and when I do "sudo bbb-conf --check" the only error is "/ usr / sbin / ufw ". I did something wrong while installing BBB? I tried to follow all the steps one by one. edit: My ip addres is 185.58.196.239

Thanks in advance!

**Comment by uka-support** [comment]
Please consult [the documentation](https://docs.bigbluebutton.org/2.2/getting-help.html#help-installing-or-running-bigbluebutton) on how and where to get help installing and setting up BBB.

This is an issue tracker, not a support forum. Let's not spam the developers with support questions - there are also more people in the [bigbluebutton-setup](https://groups.google.com/forum/#!forum/bigbluebutton-setup) mailing list willing to help.

(The ```/usr/sbin/ufw output``` is harmless - just a quirk in 2.2.30.)
