### ISSUE TITLE
Proposed Improvements of the Word Request Function

### ISSUE THREAD

**Issue by melolontha-melolontha** [bigbluebutton/bigbluebutton#10958]
**Is your feature request related to a problem? Please describe.**
Word requests in BBB should be easier for the participants. Managing word requests for the moderator is far from easy, especially for larger meetings.

**Describe the solution you'd like**
BigBlueButton has a word request function after a (left) click on oneself in the participant list and then **Set Status>Rise**, but this is hidden too deeply in the menu. When you have set it, a raised hand appears in the middle of the symbol for this participant in the participant list.

If you have set this status with your hand raised, you can also cancel your request to speak using **Set Status>Clear Status** or you can replace it with one of the other emojis offered.

The position of the control element for setting/cancelling the request to speak is hidden too deeply in the control system. Other conference systems, e.g. Jitsi, have an icon of a raised hand further to the left of the three main control buttons to indicate that you have asked to speak. This is a slightly better solution.

But for the moderator, this is not enough to moderate an online meeting with more than 10 to 20 participants. It would be better if, similar and in addition to to the chat list, the moderator had a list with the times when people asked to speak and their desired topics (and if he could could reset it if necessary).

To submit a request to speak, I also suggest using the **+** (plus) key, and to withdraw, using the **–** (minus) key. The symbols could be a hand raised with a plus sign above the thumb or an open hand with the fingers pointing downwards with a minus sign below the thumb.

It would be even better if a participant who requests to speak (**+**) were asked to give a keyword to his or her request to speak: To do this, they should first be offered a list of keywords from the existing list of requests to speak and then (if necessary, only accessible after scrolling) and in addition the possibility to enter a new keyword. Similarly, when withdrawing a request to speak (**–** or clicking on the hand pointing downwards), a participant should be asked to which of the keywords his or her chosen withdrawal applies. If a participant has only one request to speak, the question about the keyword can and should be omitted: Then it should take effect immediately.

The list of requests to speak should appear sorted by keyword and the requests to speak should be sorted by keyword and below each keyword with visible timestamps and the abbreviation of the requester. If a participant so wishes, he or she can register for one or more keywords, if necessary a separate entry with timestamp is made for each requested keyword. This also ensures that a selected speaker does not put forward everything he or she can think of about the conference, but only about his or her chosen keyword. His or her requests to speak on other points will not be lost by his current request.

There should be the option (to be enabled by the moderator) that all participants can see the list of requests to speak.
It makes sense to leave it up to the moderator to decide in which order to call up the keywords and within the keywords the requests to speak.

When the moderator clicks on an entry in the list of requests to speak, it should be highlighted and the click should also cancel any microphone lock that may have been set for the participant. If the moderator then clicks again on the highlighted participant, the participant's name should be crossed out and the microphone lock, if previously set, should become effective again.
For the moderator you should also provide functions to

- to delete individual requests to speak or all requests to speak by a participant in one step (e.g. by a troublemaker),
- Delete keywords with all associated requests,
- he should be able to specify a number of keywords in advance and have the possibility to allow or prohibit any extension of it,
- to delete the entire list of requests to speak, including keywords.

With this improvement, online meetings could perhaps become even become more effective than traditional face-to-face meetings: The topic "list of speakers" could be made transparent for all participants. One could avoid "all exhaustive" requests to speak: A moderator could ask each speaker to contribute only what belongs to his or her keyword and to submit separate requests on other topics. This improvement will also make it easier for moderators to manage larger online meetings better than at present.

**Describe alternatives you've considered**
see above.

**Additional context**

**Comment by basisbit** [comment]
duplicates of #9396, #9166, #9394 and possibly #9072. Please use the search feature before writing such song issue descriptions.

**Comment by melolontha-melolontha** [comment]
basisbit, you are right. The problem was described earlier in #9072, #9166, #9394, #9396 and I did not know about them. Btw: is there a search function by keywords for the issues? 
Some of my solutions were already described or came up in the discussions of those issues.
To let a requestor assign a keyword to his or her request to speak, did not come up in any of them and seems to be new.
