### ISSUE TITLE
Fix Reduce mirror effect when screen sharing for presentor 

### ISSUE THREAD

**Issue by mnjsnj** [bigbluebutton/bigbluebutton#10955]
I fix it by doing this on maybe it helps you

/usr/share/meteor/bundle/programs/web.browser/app/compatibility/kurento-extension.js

       if (message.type === 'screenshare') {

        let interval = setInterval(function() {
          let video=document.getElementById('screenshareVideo');
          if(video){
            video.pause();
            video.setAttribute('poster','https://i.ytimg.com/vi/GYaezmG__wk/maxresdefault.jpg');
            video.setAttribute('width', '50% !important');
             let pauseTime = video.currentTime;
             video.load(); //THIS IS FOR LOAD POSTER
            clearInterval(interval);
          }
          console.log('enter for interval');
          }, 1000);
        this.onSuccess()
         }

_Originally posted by @mnjsnj in https://github.com/bigbluebutton/bigbluebutton/issues/7183#issuecomment-737660328_

**Comment by melolontha-melolontha** [comment]
Beautiful! Further possible enhancement: Would it be possible to change the caption to "Screen sharing (fullscreen)" or "Screen sharing (application name)" or ScreeenSharing (Tab URL)"?

**Comment by HasanMajhali** [comment]
sorry for opening closed issue 
the BigBlueButton 2.3.0-beta-2 don't have the kurento-extension.js file
![sorry for opening closed issue kurento-extension js Not found](https://user-images.githubusercontent.com/52064854/114063734-96144700-98a1-11eb-8b09-e04318566fd5.png)

/usr/share/meteor/bundle/programs/web.browser/app/compatibility

**Comment by prlanzarin** [comment]
Yeah. It doesn't (for good reason).
The rough equivalent of that chunk of code now is https://github.com/bigbluebutton/bigbluebutton/blob/develop/bigbluebutton-html5/imports/ui/components/screenshare/service.js#L83-L89.

**Comment by HasanMajhali** [comment]
> Yeah. It doesn't (for good reason).
> The rough equivalent of that chunk of code now is https://github.com/bigbluebutton/bigbluebutton/blob/develop/bigbluebutton-html5/imports/ui/components/screenshare/service.js#L83-L89.
I don't Find imports/ui/components/screenshare/service.js 
i'm installing bigbluebutton bbb-install.sh 

wget -qO- https://ubuntu.bigbluebutton.org/bbb-install.sh | bash -s -- -a -w -v bionic-230 -s

**Comment by prlanzarin** [comment]
You need to [setup a development environment](https://docs.bigbluebutton.org/dev/dev23.html#setup-development-environment). That file is bundled and minified in a regular install so you will find it incredibly hard to make a hotfix upon it in a packaged environment.

Any further questions of that nature, please use the bigbluebutton-dev mailing list rather than using a **defunct** issue.
