### ISSUE TITLE
Enable Pagination in Settings

### ISSUE THREAD

**Issue by lkiesow** [bigbluebutton/bigbluebutton#10961]
Video pagination is a great feature to reduce load but if you do not need it (somewhat powerful machine, good internet connection) it can be very annoying. Recently we found ourselves several times in the situation that attendees were actively asking to be made moderators on servers where pagination was enabled to be able to see everyone all cameras at once. That is why the feature seems to be disabled on most servers despite it being potentially being helpful to some users.

That is why we would like to add it to other personal data savings settings in the HTML5 client settings like this:

![bbb-feature-pagination](https://user-images.githubusercontent.com/1008395/101089779-ec9d0c00-35b5-11eb-90b4-1dfd333cbb98.png)

To respect the administrator's choice to enable this globally – e.g. to also reduce load on the server – we could show this option only if it is not globally enabled in the HTML5 client's `settings.yml` already.

---

If no one else does, we will likely start working on this soon.

**Comment by prlanzarin** [comment]
@lkiesow Don't worry about it. I have something similar to this issue implemented but I forgot to send it upstream. I'll do it today and tomorrow and tag this issue so we can get input on it.

**Comment by PhMemmel** [comment]
I like that approach very much.

Maybe it's even more useful to set both a default and a maximum webcam count per page in settings.yml and give the user the opportunity to adapt this count in the data savings tab with a slider up to the given maximum in settings.yml.

**Comment by basisbit** [comment]
It would be nice if server administrators can still set max values for desktop + mobile devices, especially to reduce impact of big sessions on other sessions which are also on that server.

**Comment by lkiesow** [comment]
> Don't worry about it. I have something similar to this issue implemented but I forgot to send it upstream.

That's awesome. Let me know if you need someone for testing, @prlanzarin

> It would be nice if server administrators can still set max values for desktop + mobile devices

That's basically why my idea was to just show the option if  administrators have not enabled it. That would mean that users could only be more restrictive which fits with the menu anyway since the other options are all about restricting features to use up less resources anyway. It also makes the implementation and the usage quite a bit easier.

**Comment by prlanzarin** [comment]
Opened it as a draft, ported it in a rush. I plan to test it more thoroughly tomorrow morning. Appreciate feedback in the PR, preferably.

Don't agree with the slider thing, at least not in 2.2. I think fine graining the settings toggle between user classes (mods, viewers) and having the toggle constrained to the page size (which serves as a maximum, always) is the way to go for 2.2. Also, sliders are clunky UX.

Also, we have to keep in mind why pagination was implemented (at least that's what I had in mind when I did it): having the means to control Kurento (which is a known server breaker and a bit _temperamental_) and controlling client side resource usage. I don't want to give up all the control to the end user too easily because them pagination would be useless. Administrators still need to have the final word.

**Comment by PhMemmel** [comment]
Thank you very much, that's great.

> Don't agree with the slider thing, at least not in 2.2. I think fine graining the settings toggle between user classes (mods, viewers) and having the toggle constrained to the page size (which serves as a maximum, always) is the way to go for 2.2. Also, sliders are clunky UX.
>
> Also, we have to keep in mind why pagination was implemented (at least that's what I had in mind when I did it): having the means to control Kurento (which is a known server breaker and a bit _temperamental_) and controlling client side resource usage. I don't want to give up all the control to the end user too easily because then pagination would be useless. Administrators still need to have the final word.

I totally agree to administrators having the final word. What I was trying to address there is the unsatisfying feeling of having, e. g., exactly maxCamCountsPerPage webcam users in the session leading to having a full page of webcams on the first and just one single webcam on the second page. To avoid that a slider (or something else to configure the number of cams per page up to the given maximum) would be nice. Users then would more often set the webcam count per page to a value lower than max to even out the number of webcams per page reducing client and server load even slightly more than forced by the admin. Being able to put "0" in there could even replace the "enable webcams" toggle.

Of course this could also be solved by evening out webcams per page automatically by the system as soon as the webcam count becomes greater than n*maxCamCounts.
