### ISSUE TITLE
[2.3] removing a user from session, gets him removed, but keeps him appearing in users list

### ISSUE THREAD

**Issue by daminebenq** [bigbluebutton/bigbluebutton#10963]
To reproduce:
1- go to 2.3 updated server
2- connect with 2 users
3- remove one of the users (kick a second user out of the meeting)

reprodution expectation:
user gets removed from the meeting but his name remains appearing in the users list.

**Comment by antobinary** [comment]
Resolved - cannot reproduce on 2.3-alpha5
