### ISSUE TITLE
Choppy audio at the beggining of microphone/listenonly session

### ISSUE THREAD

**Issue by mariogasparoni** [bigbluebutton/bigbluebutton#10967]
**Describe the bug**
Right after activating Microphone of Listen Only, users start to receive a choppy audio; something like ["Predator's sound"](https://www.youtube.com/watch?v=OloB7rASmME) :)

More info can be found [here](https://groups.google.com/g/bigbluebutton-users/c/USgV-djn1vE) (Thanks to Sasidhar, who reported this)

**To Reproduce**
1. Join audio or listen only from problematic devices (list below)
2. Audio will be bad/choppy
3. Users reported sometimes audio quality becomes normal after a few seconds

**Expected behavior**
Audio quality should not be bad.

**Actual behavior**
Audio quality is very bad. You can't understand what the received audio (not sure if the quality of the audio that is being sent also decreases).

**BBB version (optional):**
Happens on 2.2.26 and 2.2.30

**Devices**
iPad with iOS 14, Safari 14.0.1
(Users reported this occurred in multiple iOS devices, but didn't specify the exact version: i will leave it to be filled later)

**Additional context**
I have one confirmed report on the first listed device. I also have tested on iPad and iPad mini (both with iOS 12.4.9) on https://demo.bigbluebutton.org : could not reproduce the problem on these devices.

**Comment by mariogasparoni** [comment]
Tested the following devices.
- iPhone 12 - iOS 14.1
- iPad Pro 12.9.2020 - iOS 14.0

Could not reproduce the problem on these devices.

**Comment by sasidhar-serv** [comment]
Today we have tested again, but we are facing the same issue. Initially, it will  be good and after some time there will be intense sound.

**Comment by mariogasparoni** [comment]
We received one more report for iPad (6gen) running iOS 14.2. Can you confirm if this is the same version as yours ?

**Comment by mabras** [comment]
Alson, iPhone 11 (iOS 14.2):
https://groups.google.com/g/bigbluebutton-users/c/wF6TjTdUApk/m/VpjpVlFkAgAJ

**Comment by mariogasparoni** [comment]
thanks @mabras

**Comment by mariogasparoni** [comment]
Thanks to @hostbbb , who found this issue on webkit's bugtracker
https://bugs.webkit.org/show_bug.cgi?id=219634

Seems to be our problem

**Comment by sasidhar-serv** [comment]
> We received one more report for iPad (6gen) running iOS 14.2. Can you confirm if this is the same version as yours ?
No it was not the same version

**Comment by Ectalite** [comment]
I have the same problem since last week. I am on MacOS 10.15.7 and Safari 14.0.1

**Comment by mariogasparoni** [comment]
We tested one iPad that could reproduce this problem on 14.2. Updating to 14.3 fixed the problem.
