### ISSUE TITLE
BBB record doesnot show slides

### ISSUE THREAD

**Issue by mthm99** [bigbluebutton/bigbluebutton#10979]
Hello
I installed Ubuntu 16.04.7 LTS and BBB 2.2.30 and it join by moodle.
every thing work well.
but my recording session don't show slides.
please help me.

 sudo bbb-conf --check

BigBlueButton Server 2.2.30 (2320)
                    Kernel version: 4.4.0-197-generic
                      Distribution: Ubuntu 16.04.7 LTS (64-bit)
                            Memory: 16431 MB
                         CPU cores: 6

/usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties (bbb-web)
       bigbluebutton.web.serverURL: https://bbb.example.com
                defaultGuestPolicy: ALWAYS_ACCEPT
                 svgImagesRequired: true

/etc/nginx/sites-available/bigbluebutton (nginx)
                       server name: bbb.example.com
                              port: 80, [::]:80
                    bbb-client dir: /var/www/bigbluebutton

/var/www/bigbluebutton/client/conf/config.xml (bbb-client)
                Port test (tunnel): rtmp://bbb.example.com
                              red5: bbb.example.com
              useWebrtcIfAvailable: true

/opt/freeswitch/etc/freeswitch/vars.xml (FreeSWITCH)
                       local_ip_v4: 5.x.x.x
                   external_rtp_ip: 5.x.x.x
                   external_sip_ip: 5.x.x.x

/opt/freeswitch/etc/freeswitch/sip_profiles/external.xml (FreeSWITCH)
                        ext-rtp-ip: $${local_ip_v4}
                        ext-sip-ip: $${local_ip_v4}
                        ws-binding: :5066
                       wss-binding: 5.x.x.x:7443

/var/www/bigbluebutton/check/conf/config.xml (client check)
                      client check: bbb.example.com

/usr/local/bigbluebutton/core/scripts/bigbluebutton.yml (record and playback)
                     playback_host: bbb.example.com
                 playback_protocol: https
                            ffmpeg: 4.2.4-1ubuntu0.1bbb1~16.04.1

/etc/bigbluebutton/nginx/sip.nginx (sip.nginx)
                        proxy_pass: 5.x.x.x

/usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml (Kurento SFU)
                        kurento.ip: 5.x.x.x
                       kurento.url: ws://127.0.0.1:8888/kurento
                    kurento.sip_ip: 5.x.x.x
                    localIpAddress: 5.x.x.x
               recordScreenSharing: true
                     recordWebcams: true
                  codec_video_main: VP8
               codec_video_content: VP8

/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml (HTML5 client)
                             build: 1095
                        kurentoUrl: wss://bbb.example.com/bbb-webrtc-sfu
                  enableListenOnly: true

 Potential problems described below
 Warning: API URL IPs do not match host:

                                IP from ifconfig: 5.x.x.x
  /var/lib/tomcat7/demo/bbb_api_conf.jsp: bbb.example.com

/usr/sbin/ufw

 Warning: The API demos are installed and accessible from:

    https://bbb.example.com

 and

    https://bbb.example.com/demo/demo1.jsp

 These API demos allow anyone to access your server without authentication
 to create/manage meetings and recordings. They are for testing purposes only.
 If you are running a production system, remove them by running:

    apt-get purge bbb-demo

 Warning: The client self check is installed and accessible from:

    https://bbb.example.com/check

**Comment by mthm99** [comment]
Please Help me.
I installed BBB 2.2.29 and work well
but another server that installed BBB 2.2.30 has problem.

**Comment by pedrobmarin** [comment]
Hi @mthm99 , sorry for the delay. We've been extra busy the past few months. Did this problem persisted at the current version?

**Comment by mthm99** [comment]
Hi
I reinstall bigbluebutton and this problem solved.
But BBB behind the NAT has this problem.
Thank you

**Comment by pedrobmarin** [comment]
Hmm, maybe there's an extra configuration to solve that. Usually folks are very helpful with those issues at the setup mailing list (https://groups.google.com/g/bigbluebutton-setup). Closing this one for now.
