### ISSUE TITLE
Bigbluebutton attendees' cameras and microphones are deactivated by the moderator before they are turned off

### ISSUE THREAD

**Issue by dogangokce** [bigbluebutton/bigbluebutton#10973]
Hello I have a request
If the participants of the Bigbluebutton conference are connected with a camera and microphone, when we disable the camera and microphone feature, the cameras and microphones of the participants who already open cameras and microphones do not turn off. Let it be disabled for participants who have not yet opened a camera and microphone in the system.

So when the camera and microphone are disabled, what can I do to prevent the open ones from being turned off?

**Comment by uka-support** [comment]
Please use the issue template to report issues.

Which version are you using (include output of ```bbb-conf --check```).

I'm not sure I understand your issue correctly. When you disallow participants from enabling webcam and using the microphone, all affected participants will become muted and have their webcam turned off.

There might be a workaround:

- restrict participants permissions first, but only disable e.g. "edit share notes"
- then unlock every participant who has the microphone/webcam already open
- then enforce more restrictions

Alternatively you could make the participants moderators who should be able to talk and share their webcam. Restrictions do not apply to moderators.

Please not that this issue tracker is for reporting bugs (and enhancement proposals) only, not for support questions. Your question seems to be related to using BBB, so please have a look here on how to get support: https://docs.bigbluebutton.org/2.2/getting-help.html#help-using-bigbluebutton

**Comment by dogangokce** [comment]
camera and microphone button will be hidden. The moderator will be able to turn the hidden camera and microphone buttons back at will. The cameras and microphones will remain open while these operations are being performed.what i want is to add this feature. Where is the frontend design directory. I can learn the location of the buttons, if necessary, I want to delete it from the system. Because the camera and microphones automatically start when starting the session

BigBlueButton Server 2.2.29 (2244)
                    Kernel version: 4.4.0-194-generic
                      Distribution: Ubuntu 16.04.7 LTS (64-bit)
                            Memory: 16431 MB
                         CPU cores: 6

/usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties (bbb-web)
       bigbluebutton.web.serverURL: https://live13.idrakacademy.com
                defaultGuestPolicy: ALWAYS_ACCEPT
                 svgImagesRequired: true

/etc/nginx/sites-available/bigbluebutton (nginx)
                       server name: live13.idrakacademy.com
                              port: 80, [::]:80
                              port: 443 ssl
                    bbb-client dir: /var/www/bigbluebutton

/var/www/bigbluebutton/client/conf/config.xml (bbb-client)
                Port test (tunnel): rtmp://live13.idrakacademy.com
                              red5: live13.idrakacademy.com
              useWebrtcIfAvailable: true

/opt/freeswitch/etc/freeswitch/vars.xml (FreeSWITCH)
                       local_ip_v4: 80.253.245.211
                   external_rtp_ip: stun:stun.freeswitch.org
                   external_sip_ip: stun:stun.freeswitch.org

/opt/freeswitch/etc/freeswitch/sip_profiles/external.xml (FreeSWITCH)
                        ext-rtp-ip: $${local_ip_v4}
                        ext-sip-ip: $${local_ip_v4}
                        ws-binding: :5066
                       wss-binding: 80.253.245.211:7443

/usr/local/bigbluebutton/core/scripts/bigbluebutton.yml (record and playback)
                     playback_host: live13.idrakacademy.com
                 playback_protocol: https
                            ffmpeg: 4.2.4-1ubuntu0.1bbb1~16.04.1

/etc/bigbluebutton/nginx/sip.nginx (sip.nginx)
                        proxy_pass: 80.253.245.211

/usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml (Kurento SFU)
                        kurento.ip: 80.253.245.211
                       kurento.url: ws://127.0.0.1:8888/kurento
                    kurento.sip_ip: 80.253.245.211
                    localIpAddress: 80.253.245.211
               recordScreenSharing: true
                     recordWebcams: true
                  codec_video_main: VP8
               codec_video_content: VP8

/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml (HTML5 c                                                                             lient)
                             build: 1081
                        kurentoUrl: wss://live13.idrakacademy.com/bbb-webrtc-sfu
                  enableListenOnly: true


# Potential problems described below
