### ISSUE TITLE
Error in Html5client development env.

### ISSUE THREAD

**Issue by gaurav-bothra** [bigbluebutton/bigbluebutton#10981]
Hello Team,

I am following steps mentioned in [https://docs.bigbluebutton.org/2.2/dev.html#developing-the-html5-client](docs)
I am getting following error

![image](https://user-images.githubusercontent.com/29119145/101343536-2453ce80-38aa-11eb-9dbd-808a0e69d5cf.png)

Branch use v2.2.x-release

**Comment by basisbit** [comment]
For such support requests, please use the [forum / mailing list](https://groups.google.com/forum/#!forum/bigbluebutton-dev). Sorry.
