### ISSUE TITLE
etherpad can fail to start with bbb-conf --restart

### ISSUE THREAD

**Issue by crosscodr** [bigbluebutton/bigbluebutton#10989]
**Describe the bug**

```
bbb07 node[92950]: events.js:183
bbb07 node[92950]:       throw er; // Unhandled 'error' event
bbb07 node[92950]:       ^
bbb07 node[92950]: Error: Redis connection to localhost:6379 failed - connect ECONNREFUSED 127.0.0.1:6379
bbb07 node[92950]:     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1191:14)
bbb07 systemd[1]: etherpad.service: Main process exited, code=exited, status=1/FAILURE
bbb07 systemd[1]: etherpad.service: Unit entered failed state.
bbb07 systemd[1]: etherpad.service: Failed with result 'exit-code'.
```

**To Reproduce**
Hard to reproduce, saw it just once, since.

**Expected behavior**
etherpad should start after dependent services (e.g. redis)

**Actual behavior**
Systemd sometimes seems to start etherpad before redis and fails to do it.

**Comment by antobinary** [comment]
Possibly we need to add `redis-server.service` as part of `After=`? https://github.com/bigbluebutton/bigbluebutton/blob/v2.5.x-release/build/packages-template/bbb-etherpad/etherpad.service#L4

**Comment by schrd** [comment]
> Possibly we need to add `redis-server.service` as part of `After=`? https://github.com/bigbluebutton/bigbluebutton/blob/v2.5.x-release/build/packages-template/bbb-etherpad/etherpad.service#L4

In addition to `After=` the unit should include a `Wants=` directive
