### ISSUE TITLE
presentation not work 

### ISSUE THREAD

**Issue by ashanet** [bigbluebutton/bigbluebutton#10988]
hi 
i install new bbb from install.sh 
but after install have problem ! 
bbb show to me:
/usr/sbin/ufw in check and in my conferance have problem :
my presentation not work and not show to user but upload !!

my server information:
ubuntu 16.04 
ram :32 
cpu : 12 

BigBlueButton Server 2.2.30 (2264)
                    Kernel version: 4.4.0-197-generic
                      Distribution: Ubuntu 16.04.7 LTS (64-bit)
                            Memory: 32171 MB
                         CPU cores: 12

-----------------------
bbb-conf --check:

# Potential problems described below
/usr/sbin/ufw

bbb-conf --status
nginx —————————————————► [✔ - active]
freeswitch ————————————► [✔ - active]
redis-server ——————————► [✔ - active]
bbb-apps-akka —————————► [✔ - active]
bbb-transcode-akka ————► [✔ - active]
bbb-fsesl-akka ————————► [✔ - active]
red5 ——————————————————► [✔ - active]
mongod ————————————————► [✔ - active]
bbb-html5 —————————————► [✔ - active]
bbb-webrtc-sfu ————————► [✔ - active]
kurento-media-server ——► [✔ - active]
etherpad ——————————————► [✔ - active]
bbb-web ———————————————► [✔ - active]

-----------------

**Comment by ashanet** [comment]
i found new problem !!
my whiteboard not load !!

**Comment by prlanzarin** [comment]
Sorry, but github issues aren't the proper place for setup debugging. You can read more about getting help in https://docs.bigbluebutton.org/2.2/getting-help.html.

Mailing lists are usually the proper place for this.
