### ISSUE TITLE
lockSettings: hideUserList has no effect (via API & UI)

### ISSUE THREAD

**Issue by jarmediagmbh** [bigbluebutton/bigbluebutton#10980]
**Describe the bug**
The hideUserList lock settings have no effect in current versions of BBB. Bug is reproducible aswell at demo.bigbluebutton.org.

**To Reproduce**
*VIA API*
1) Set lockSettingsHideUserList = true via the API and join users.
2) Guests can see full user list. As well, in the lockSettings modal the respective option is not locked.

*VIA UI*
1) Create a meeting and join one mod and one guest.
2) As Mod: Click on settings cog in the participants list and lock the User list. Apply.
3) As Guest: You can still see full user list.

**Expected behavior**
As guest, you are not able to see user list anymore.

**Actual behavior**
As guest, you can still see the full user list.

**Screenshots**
![Unbenannt](https://user-images.githubusercontent.com/3168086/101339907-4dab3500-387f-11eb-9b92-9fb5e9397895.gif)

**BBB version (optional):**
On our systems: 2.2.30
On demo.bigbluebutton.org: Unknown.

**Additional context**
No other context.

**Comment by pedrobmarin** [comment]
I believe there's a misunderstanding here. That lock hides other **viewers** from a **viewer**'s user list. It does not apply to moderators and will not hide moderators. Try reproducing your test using multiple viewers (the one you are calling guest in your example).

**Comment by jarmediagmbh** [comment]
Ha! You got me! :) Yes, I was confused there.

HOWEVER: The situation you described does not work either. :)
As per my understanding, this should not happen then, right?

![Unbenannt (1)](https://user-images.githubusercontent.com/3168086/101344031-25bed000-3885-11eb-8c46-32b0ba3f0853.gif)

**Comment by jarmediagmbh** [comment]
Update: I am NOT able to reproduce this with demo.bigbluebutton.org. Any ideas why this happens on our systems?

**Comment by pedrobmarin** [comment]
Was about to ask about that. Not sure what you are running, Is it something directly from the official packages?

**Comment by jarmediagmbh** [comment]
Yes, it is 2.2.30, installed with bbb-install.sh. We are doing some modifications in the config files (webcam profiles etc.), but that's all. Do you know about any config setting interfering with these lock settings?
I realized something strange additionally: Webcam-lock does also NOT work. All other lock settings DO work.

If you do not have any idea, then we will install a clean system, see if it works there - and if so - apply all customizations one after another to see which setting is causing this. It is a lot of work, so maybe I can kindly ask you if you have any ad-hoc idea? :P Thanks so much!

**Comment by pedrobmarin** [comment]
Unfortunately it doesn't ring any bell... I didn't find any other similar issue to this one.

Do you have any lock preset configured at bbb-web `bigbluebutton.properties` file? It can be something API related...

**Comment by jarmediagmbh** [comment]
@pedrobmarin I found the reason and for me it is an unexpected behavior of the API.
When creating meetings we default all lockSettings-params to "false" (which is not correct in our usecase, but that's our issue). 

However: When explicitly setting either "lockSettingsLockOnJoin=true" (with or without "lockSettingsLockOnJoinConfigurable=true", it does not matter) will cause the error to appear.

Should I open a new ticket for this? Or what do you want me to do?

**Comment by pedrobmarin** [comment]
Maybe a new issue would be better so the person that will be assigned to resolve this won't have to follow up all this thread to figure it out what the problem is.

**Comment by jarmediagmbh** [comment]
I will do so.
