### ISSUE TITLE
BBB Backup and Restore in Moodle

### ISSUE THREAD

**Issue by ecampuswizard** [bigbluebutton/bigbluebutton#10987]
**Is your feature request related to a problem? Please describe.**
An existing Moodle course has BBB links set up according to the course's start date. 

When we backup and restore the course to a new course with a new start date, the BBB links are not updated according to the new course's start date (although they appear under the Upcoming Events block with the correct dates). The BBB session dates settings remain the same as in the originally backed up course.

**Describe the solution you'd like**
BBB session dates to be adapted to the restored course's start date.

**Describe alternatives you've considered**
Only manually changing the BBB session links settings was possible.

**Additional context**

**Comment by basisbit** [comment]
Thank you for reporting this issue! Unfortunately, this is not a problem in BigBlueButton and there is nothing that should be changed in the BBB server component to somehow adjust the described behavior. Instead, please report the issue for the Moodle plugin where this probably has to be fixed. -> https://github.com/blindsidenetworks/moodle-mod_bigbluebuttonbn
