### ISSUE TITLE
API: lockSettingsLockOnJoin=true will break some lockSettings in API and UI

### ISSUE THREAD

**Issue by invokablegmbh** [bigbluebutton/bigbluebutton#10986]
**Describe the bug**
When explicitly adding "lockSettingsLockOnJoin=true" to the CREATE-call in the API, some other lockSettings (e.g. hideUserList or webcam) will not have any effect anymore. Even when toggeling in the UI, the settings won't have any effect anymore.

**To Reproduce**
1. CREATE a meeting via API and explicitly set "lockSettingsLockOnJoin=true" in the URL.
2. Join one moderator and two viewers/guests.
3. As Moderator: Try to toggle lock setting for "hide other users..."
4. Have a look at the viewers/guests screen. Other viewers/guests are still visible.

**Expected behavior**
Other viewers / guests should not be visible any more for other viewers / guests.

**Actual behavior**
Other viewers/guests are still visible for all participants.

**Screenshots**
![Unbenannt (1)](https://user-images.githubusercontent.com/3168086/101344031-25bed000-3885-11eb-8c46-32b0ba3f0853.gif)

**Additional context**
1) In the API call it does not matter what the value of "lockSettingsLockOnJoinConfigurable" is.
2) Without "lockSettingsLockOnJoin=true" everything works as expected, because true is already the default value for "lockSettingsLockOnJoin". So one can just omit this param in the URL. Nevertheless, setting it should not break things.
3) Cross-reference: Originally created out of #10980

**Comment by gustavotrott** [comment]
I'm not able to reproduce this problem on 2.5! It seems that it was already fixed.
