### ISSUE TITLE
Etherpad's Timeslider Feature is Broken

### ISSUE THREAD

**Issue by KimBrodowski** [bigbluebutton/bigbluebutton#10990]
**Describe the bug**
Please note: This issue isn't quite related to bbb-html5, but BBBs Etherpad fork doesn't have an issue tracker. The nginx config enforcing the behaviour mentioned below is also not tracked in the Etherpad fork, but partially responsible.

Unfortunately https://github.com/bigbluebutton/etherpad-lite/pull/5 broke Etherpad's timeslider feature, which allows users to track who made changes to a pad.

This feature IS NOT enabled by default, but very useful, so I hope you'll consider fixing it anyway.

**To Reproduce**
1. Modify your settings.json: `sed -i -E -e 's|^(\s*)"right":(\s*)\[\["importexport"\]\](\s*)$|\1"right":\2[["importexport", "timeslider"]],\3\n\1"timeslider":\2[["timeslider_export"]]|' /usr/share/etherpad-lite/settings.json`
2. Restart services: `bbb-conf --restart`
3. Join any conference
4. Click on the shared notes tab
5. Use the right most icon to open the timeslider

**Expected behavior**
The Etherpad timeslider should appear and work like on vanilla instances of Etherpad.

**Actual behavior**
Access is denied (401) due to a missing sessionToken GET parameter.

**Screenshots**
N/A

**BBB version (optional):**
2.2.30

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by pedrobmarin** [comment]
When I included Etherpad as part of BigBlueButton I, indeed, left this view enabled. But that was voted out. I'm not planning on touching this too soon. Do you want to give it a try, @KimBrodowski ? Or maybe share your solution if you got this running on your deploy?

**Comment by pedrobmarin** [comment]
Closing this one, fell free to suggest any change at the nginx configuration files.
