### ISSUE TITLE
Use Drawing during screensharing

### ISSUE THREAD

**Issue by Thorgrimson** [bigbluebutton/bigbluebutton#10992]
**Is your feature request related to a problem? Please describe.**
I use BigBluebutton with fellow students to coordinate our project. Everybody draws building plans with a CAD software. To comment on this we would like to use the painting function, which does not work during the screensharing. So we always switch to zoom which annoys me totally; (

**Describe the solution you’d like**
I want to have access to the painting function during the screensharing.

**Comment by prlanzarin** [comment]
Duplicate of https://github.com/bigbluebutton/bigbluebutton/issues/5835.
