### ISSUE TITLE
Configuration file isn't updated after a bbb update

### ISSUE THREAD

**Issue by Haunui** [bigbluebutton/bigbluebutton#11007]
After an update, I got the following message when i restart my bbb server (bbb-conf --restart) :
> Error: Could not connect to the configured hostname/IP address

When I load the website, I get the message 'Invalid BigBlueButton Endpoint and Secret'.
And these message appear in the log (/var/log/bigbluebutton/bbb-web.log)  :
> org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'meetingService' defined in class path resource [spring/resources.xml]: Cannot resolve reference to bean 'paramsProcessorUtil' while setting bean property 'paramsProcessorUtil'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'paramsProcessorUtil' defined in class path resource [spring/resources.xml]: Initialization of bean failed; nested exception is org.springframework.beans.TypeMismatchException: Failed to convert property value of type 'java.lang.String' to required type 'java.lang.Boolean' for property 'endWhenNoModerator'; nested exception is java.lang.IllegalArgumentException: Invalid boolean value [${endWhenNoModerator}]

> Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'paramsProcessorUtil' defined in class path resource [spring/resources.xml]: Initialization of bean failed; nested exception is org.springframework.beans.TypeMismatchException: Failed to convert property value of type 'java.lang.String' to required type 'java.lang.Boolean' for property 'endWhenNoModerator'; nested exception is java.lang.IllegalArgumentException: Invalid boolean value [${endWhenNoModerator}]

> Caused by: org.springframework.beans.TypeMismatchException: Failed to convert property value of type 'java.lang.String' to required type 'java.lang.Boolean' for property 'endWhenNoModerator'; nested exception is java.lang.IllegalArgumentException: Invalid boolean value [${endWhenNoModerator}]

> Caused by: java.lang.IllegalArgumentException: Invalid boolean value [${endWhenNoModerator}]  
  
  
Steps to reproduce the problem:
- Install a bbb server before the following commit : [- set html5 as default client](https://github.com/bigbluebutton/bigbluebutton/commit/9e6a40280e659671cb5d8bbba982909de40e30d0)
- Update to 2.3 (or a version after the '- set html5 as default client' commit)

The problem is comming from the commit [Patch of improvements for bbb-web](https://github.com/bigbluebutton/bigbluebutton/commit/2fb26ff0cf8de7a0779eec354fcdc5ff0b24ee79) and [- set html5 as default client](https://github.com/bigbluebutton/bigbluebutton/commit/9e6a40280e659671cb5d8bbba982909de40e30d0) which add new variables in this file :
> /usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties

But when you update from a older version that doesn't have these variables, the new version will not add them to your configuration file.

To fix this error, add these variables to your bigbluebutton.properties file :
> endWhenNoModerator=false
> usersTimeout=60000
> enteredUsersTimeout=45000

And restart bbb.

Someone can try to code something that will automatically update de configuration file.

h.s.s.

**Comment by antobinary** [comment]
In 2.3 we have introduced `/etc/bigbluebutton/bbb-web.properties` - see https://docs.bigbluebutton.org/2.3/install.html#local-overrides-for-configuration-settings
That file's content will be preserved even if you update bbb-web package. On 2.3 this is the place to edit _instead_ of `bigbluebutton.properties`

> But when you update from a older version that doesn't have these variables, the new version will not add them to your configuration file.
