### ISSUE TITLE
Big Blue Button recording does not record audio

### ISSUE THREAD

**Issue by vacant309** [bigbluebutton/bigbluebutton#11003]
Hello,
I have a problem with presentations, after a long time I can publish it but the video is correct but no audio is heard
As read in other discussions I have checked the directory  /var/freeswitch/meetings

this is the output:
total 170516
drwxrwxr-x 2 freeswitch freeswitch     4096 dic 11 10:00 .
drwxr-xr-x 3 freeswitch daemon         4096 dic  3 17:26 ..
-rw-r--r-- 1 freeswitch daemon     32251904 dic 11 10:27 0a0639d950a1aa73efb0b471b91007a4b4b74984-1607676985138-44782908.opus
-rw-r--r-- 1 freeswitch daemon     31105024 dic 11 10:27 38e444f1024e7717e32c02e126e0a10c2121ee6a-1607677233684-45030039.opus
-rw-r--r-- 1 freeswitch daemon     20926464 dic 11 10:27 5ad12cd236ad146dc443dc669b4a7c39eb3ef453-1607679054289-46844612.opus
-rw-r--r-- 1 freeswitch daemon       737002 dic 11 08:33 aa8301f0b5f9156761abca09d87832984a76d2b8-1607675435567-43244746.opus
-rw-r--r-- 1 freeswitch daemon     38645760 dic 11 10:27 aa8301f0b5f9156761abca09d87832984a76d2b8-1607675435567-43389492.opus
-rw-r--r-- 1 freeswitch daemon     31465472 dic 11 10:27 d679f889177280f508fced0f6d6b305cd88b96ec-1607676992669-44793533.opus
-rw-r--r-- 1 freeswitch daemon     19443712 dic 11 10:27 fff97676d2e03ca1a8355996e0a947de6576206f-1607679211652-47004923.opus
-rw-r--r-- 1 freeswitch freeswitch       48 set 14 21:40 readme.txt

it seems that only from today 11/12/2020 the audio files are present.
I wonder how it is possible that not all audio files are present?
the Server has been installed for about a week, it works perfectly, but yesterday I realized that the presentations were not published
automatically so last night I ran the command: bbb-record --rebuildall .

below I also put the output of the command : bbb-conf --check 

BigBlueButton Server 2.2.30 (2264)
                    Kernel version: 4.19-ovh-xxxx-std-ipv6-64
                      Distribution: Ubuntu 16.04.7 LTS (64-bit)
                            Memory: 131938 MB
                         CPU cores: 48

/usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties (bbb-web)
       bigbluebutton.web.serverURL: https://server
                defaultGuestPolicy: ALWAYS_ACCEPT
                 svgImagesRequired: true

/etc/nginx/sites-available/bigbluebutton (nginx)
                       server name: server
                              port: 80, [::]:80
                              port: 443 ssl
                    bbb-client dir: /var/www/bigbluebutton

/var/www/bigbluebutton/client/conf/config.xml (bbb-client)
                Port test (tunnel): rtmp://server
                              red5: server
              useWebrtcIfAvailable: true

/opt/freeswitch/etc/freeswitch/vars.xml (FreeSWITCH)
                       local_ip_v4: ip
                   external_rtp_ip: ip
                   external_sip_ip: ip

/opt/freeswitch/etc/freeswitch/sip_profiles/external.xml (FreeSWITCH)
                        ext-rtp-ip: $${local_ip_v4}
                        ext-sip-ip: $${local_ip_v4}
                        ws-binding: :5066
                       wss-binding: ip:7443

/usr/local/bigbluebutton/core/scripts/bigbluebutton.yml (record and playback)
                     playback_host: server
                 playback_protocol: https
                            ffmpeg: 4.2.4-1ubuntu0.1bbb1~16.04.1

/etc/bigbluebutton/nginx/sip.nginx (sip.nginx)
                        proxy_pass: ip

/usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml (Kurento SFU)
                        kurento.ip: ip
                       kurento.url: ws://127.0.0.1:8888/kurento
                    kurento.sip_ip: ip 
                    localIpAddress: ip
               recordScreenSharing: true
                     recordWebcams: true
                  codec_video_main: VP8
               codec_video_content: VP8

/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml (HTML5 client)
                             build: 1095
                        kurentoUrl: wss://server/bbb-webrtc-sfu
                  enableListenOnly: true

Sure of your help I wish you a good day

**Comment by basisbit** [comment]
For support requests, please use the [forum / mailing list](https://groups.google.com/forum/#!forum/bigbluebutton-setup). This issue tracker here is only for BBB development related issues. Sorry.
