### ISSUE TITLE
Cannot downgrade from 2.2.30 to 2.2.26

### ISSUE THREAD

**Issue by GhaziTriki** [bigbluebutton/bigbluebutton#11000]
I tried to downgrade from 2.2.30 to 2.2.26 using that command and it did not work
`wget -qO- https://ubuntu.bigbluebutton.org/bbb-install.sh | sudo bash -s -- -v xenial-220-2.2.26 -s $(hostname) -e devops@mail.com && sudo apt-get install bbb-webhooks`

**Comment by mabras** [comment]
https://github.com/bigbluebutton/bigbluebutton/issues/9508#issuecomment-652897005

**Comment by GhaziTriki** [comment]
Yes a purge was required.
