### ISSUE TITLE
Meeting is recorded in hidden mode (with just keepEvents=True)!

### ISSUE THREAD

**Issue by cod3r0k** [bigbluebutton/bigbluebutton#11014]
Hi, I set `keepEvents` to be `True` and I don't record the session. But I find that the session is recorded and in the recorded session I saw that my recording button is off (This is amazing that I can see this situation when I never start the recording session).

Do we must set keepEvents to be no ?   Can it be solved?

**Comment by basisbit** [comment]
Please read this page of the documentation. https://docs.bigbluebutton.org/admin/privacy.html#bigbluebutton-either-records-all-of-a-session-or-does-not-record-at-all

**Comment by cod3r0k** [comment]
Dear @basisbit , No, My question is not about one whole meeting. My question is about the recording procedure which save and record each session when we set `KeepEvents=True` in the bigbluebutton setting. It means that when we don't click on `Start recording` button, it is recorded BDW you never click on `Start recording` button. Also, When we click `Start recording`, the output rendering is just that duration but if we never click on `Start recording`, the session is recorded and the instructor found that it was not recorded (because nothing is clicked and nothing is shown), and after the session, He/She could see its video (in 2.2)

**Comment by hostbbb** [comment]
any time record=true is passed on create all media is captured.  pass record=false on create and you will get only events.xml
