### ISSUE TITLE
Firefox with JACK as audio backend doesn't route audio if only BBB is used

### ISSUE THREAD

**Issue by zserik** [bigbluebutton/bigbluebutton#11017]
**Describe the bug**
I use a Firefox installation compiled with JACK (and without pulseaudio) on linux. If I open a BBB session, audio sometimes doesn't work, it does especially not work if BBB is the only loaded page with audio output. If I open another page with audio (e.g. YouTube seems to work pretty reliable), then BBB audio (both input and output) starts working. Althrough this seems to be a firefox issue, maybe there is something that BBB could do to force firefox to establish a JACK audio connection (YouTube is able to do it, althrough I don't know *how*), which currently doesn't seem to be the case, even if firefox successfully asks for a microphone input.

**To Reproduce**
Steps to reproduce the behavior (I'm unsure how the buttons are called because I use the german version):
1. Open Firefox, open only BBB
2. Join an existing and already started BBB session
3. Click on '[join with] microphone' ("Mit Mikrofon teilnehmen")
4. Firefox opens a "choose microphone" dialog, choose "JACK capture"
5. **Althrough audio should work, it doesn't**
6. Open a new tab
7. Navigate to a random YouTube video
8. Click on the '(|>) play' button of the video
9. Go to the BBB tab
10. Quit audio
11. Rejoin audio using the 'join audio' (maybe "Audio beitreten") button
12. **Audio works now**

**Expected behavior**
Audio optimally should work after the audio session is joined and should not depend on other tabs to connect audio.

**Actual behavior**
Audio doesn't work (under the circumstances described above). No input or output happens at all.

**Screenshots**

**BBB version (optional):**
Copyright: ©2020 BigBlueButton Inc.
Clientversion: 2.2.30-tuc

**Desktop (please complete the following information):**
 - OS: Gentoo Linux
 - Browser: Firefox
 - Version: 83.0 (64-Bit)

**Additional context**
The firefox is compiled with JACK support and without PulseAudio support.
The issue seems to stem between mismatched expectations between BBB, Firefox and JACK.

**Comment by mariogasparoni** [comment]
Thanks for this well described report. This indeed seems to be a Firefox issue. Can you reproduce the same using https://appr.tc ? If so , I would recommend reporting this on Firefox's bug tracker.

**Comment by zserik** [comment]
Yes. I can reproduce it.

**Comment by zserik** [comment]
found a mention of the same issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1614278#c13

**Comment by zserik** [comment]
ok, found a bug report with this exact issue. https://bugzilla.mozilla.org/show_bug.cgi?id=1547447
