### ISSUE TITLE
2.3 Kicked out of main room if joining audio in breakout and then joining breakout

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#11029]
Steps to reproduce
1. Join a meeting with full audio
2. Start breakouts
3. Hit on the button to join the *audio bridge* of a breakout.
4. Then hit the button to join the breakout itself
5. You will be kicked out of the main room with error 403

**Comment by rasos** [comment]
Not reproducable on 2.3alpha4.

**Comment by mariogasparoni** [comment]
I am able to reproduce this on 2.3-alpha5 with a small difference on **step 4**
1. Join a meeting with full audio
2. Start breakouts
3. Hit on the button to join the audio bridge of a breakout.
4. ***Then hit the button "Return audio" to leave the audio bridge of the breakout***
5. You will be kicked out of the main room with error 403

![screen](https://user-images.githubusercontent.com/1780868/106552625-6b4ef080-64f6-11eb-8533-93da31b1220f.gif)
