### ISSUE TITLE
Media could not reach the server

### ISSUE THREAD

**Issue by yassersheikh** [bigbluebutton/bigbluebutton#11020]
WebCam. Every time "share webcam" is invoked, after a while there is a notification saying: "Media could not reach the server (error 1020)"

https://www.screencast.com/t/Dynb4Q31HPUO

**Comment by prlanzarin** [comment]
`If you are unable to solve the problem after consulting the above documentation, then post as much information as possible about the problem to bigbluebutton-setup mailing list [...] refrain from using the GitHub issue tracker for general queries.`


https://docs.bigbluebutton.org/2.2/getting-help.html
