### ISSUE TITLE
Issue: ICE Erro 1007 /BBB in EC2(AWS) Ubuntu 16.04

### ISSUE THREAD

**Issue by cpimentel25** [bigbluebutton/bigbluebutton#11030]
Hello everyone, I have made the installation of bigbluebutton on a private server using greenligth following the following parameters:  [https://github.com/bigbluebutton/bbb-install](url)

when creating a room and allowing to use the microphone it generates this error **ICE ERROR: 1007**

how can I solve that?

_Note: i have mounted bbb to an aws instance_ 

Ubuntu 16.04 64-bit Linux kernel 4.x
16GB de memorias (RAM)
4 vCPUs Cores (minimo)
10 GB SSD-GP2 (EBS-Minimo)
Instance (AWS): t3a.xlarge

TCP 80 | Anywhere
TCP 443 | Anywhere
TCP 1935 | Anywhere
TCP 22 | Anywhere
UDP 16384-32768 | Anywhere

**Comment by prlanzarin** [comment]
Hey. Github issues are not the proper venue to get setup support.

https://docs.bigbluebutton.org/2.2/getting-help.html
Check this. I recommend you try to get help in bigbluebutton-setup mailing list.
