### ISSUE TITLE
Updates retain most settings, but not for HTML5 client

### ISSUE THREAD

**Issue by paraviz02** [bigbluebutton/bigbluebutton#11034]
**Describe the bug**
While most files have custom configurations migrated to new updated versions, the /usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml file is overwritten regardless.

**To Reproduce**
1. Update BBB after modifying the HTML5 client settings file.

**Expected behavior**
Certain settings, such as mirroring camera or auto hiding the chat window should always be retained. Whereas, settings that are not specific to the function of the HTML5 client on the user side that are purposely changed by BBB developers should be as the devs desire.

**Actual behavior**
Certain settings that should always be retained are completely overwritten, as the settings.yml file seems to be replaced.

**Comment by ffdixon** [comment]
> Certain settings, such as mirroring camera or auto hiding the chat window should always be retained

We can add some logic to the upgrade script for bbb-html5 to propagate some of these values.

**Comment by basisbit** [comment]
There already exist tons of issues regarding improving the packaging and improving how and where configuration files are stored.
Linking this to one of the newest ones so it can be found. #10971
