### ISSUE TITLE
Attempt to join with microphone on Opera (73.0.3856.284) returns ERROR 1004.

### ISSUE THREAD

**Issue by blinchk** [bigbluebutton/bigbluebutton#11038]
**Describe the bug**
Incomplatiblity with Opera (73.0.3856.284).

**To Reproduce**
1. Opened installed BBB.
2. Connected to session.
3. Joined with microphone.

**Expected behavior**
Session would be joined like was before update.

**Actual behavior**
Trying to join with microphone on Opera (73.0.3856.284) returns error with code 1004: Incomplatible SDP.

**Screenshots**
![image](https://user-images.githubusercontent.com/49353043/102585673-db0d4580-4119-11eb-9c61-379d29756073.png)

**Desktop:**
![image](https://user-images.githubusercontent.com/49353043/102585747-fbd59b00-4119-11eb-9ca2-3d5287ae00bc.png)

**Comment by Daedalus3** [comment]
Hm, works fine with Opera (73.0.3856.284), so I'd aasume there is some missconfiguration on your end. Did you try the BBB demo server at demo.bigbluebutton.com [?](https://demo.bigbluebutton.com)

**Comment by blinchk** [comment]
@Daedalus3, yes. I am using internal Opera ad blocking and privacy badget and tried on the other BBB server. Also the BBB-demo-server returns 404 on Opera and MSEdge.

**Comment by prlanzarin** [comment]
demo might be overloaded.

The usual proper venue to test issues in upstream is https://test.bigbluebutton.org. Try it there, please.

**Comment by blinchk** [comment]
@prlanzarin, on https://test.bigbluebutton.org it works as well with enabled and disabled AdBlocker and privacy badger. I think, this isn't related with it. 

So, thanks for @prlanzarin and @Daedalus3 for help. I will try connect external server's owner to ask fix this issue and update BBB.

**Comment by prlanzarin** [comment]
FYI I've explained this at length in https://github.com/bigbluebutton/bigbluebutton/issues/10777
