### ISSUE TITLE
HTML5 do not start after update

### ISSUE THREAD

**Issue by eurogla** [bigbluebutton/bigbluebutton#11037]
After update from 2.2.30 to 2.2.31 HTML5 do not start.
Maybe its a bug. I try restart Server und do upgrade & update.

It is a Step-by-step-Installation on Ubuntu 16.04 and has worked great so far

bbb-html5 1:2.2.0-1114
nodejs 8.17.0-1nodesource1

**Comment by peterVoisin** [comment]
Hi,
Same issue, after upgrade to 2.2.31.

Probably this in `/usr/lib/systemd/system/bbb-html5.service` :
CPUSchedulingPolicy=fifo
Nice=19

Without these options, bbb-html5.service start fine !?

See this :
https://docs.bigbluebutton.org/2.2/troubleshooting.html#bbb-html5-fails-to-start-with-a-setscheduler-error

**Comment by eurogla** [comment]
Yes this solved the Problem. Thank you very much

**Comment by eurogla** [comment]
Sorry, can I close this issue?

**Comment by peterVoisin** [comment]
I think no !
Did you test your system after that?

**Comment by eurogla** [comment]
Yes it is working fine

**Comment by peterVoisin** [comment]
Ok, with this solution, my system no longer responds after the echo test...
I went back to the 2.2.30

We should know if the update causes this problem for everyone !?

**Comment by eurogla** [comment]
This solution didnt work for you? 

How can i went back to a further Version?

**Comment by peterVoisin** [comment]
I work with a virtual machine and I restore backup!

As I said, after upgrade and applying this solution, my system no longer responds after echo test

**Comment by prlanzarin** [comment]
> my system no longer responds after echo test
`sudo bbb-conf --setip <hostname>`

As documented in https://docs.bigbluebutton.org/2.2/troubleshooting.html#echo-test-hangs-upgrading-bigbluebutton-22

**Comment by peterVoisin** [comment]
Thanks,
I was waiting other user feedback before digging
My system work well now

**Comment by eurogla** [comment]
@peterVoisin a little question:
How can I backup my complete BBB include Greenlight?
