### ISSUE TITLE
bbb-conf: No HTTPS URLs are used

### ISSUE THREAD

**Issue by paulmenzel** [bigbluebutton/bigbluebutton#11036]
With BigBlueButton 2.2.31, `sudo bbb-conf --restart` results in the warnings below.

```
# Potential problems described below

# Warning: Detected FreeSWITCH is using default stun.freeswitch.org server.  See
#
#     http://docs.bigbluebutton.org/2.2/troubleshooting.html#freeswitch-using-default-stun-server
#


# Warning: No firewall detected.  Recommend using setting up a firewall for your server
#
#     http://docs.bigbluebutton.org/2.2/troubleshooting.html#freeswitch-using-default-stun-server
#
```

Please use HTTPS URLs.

**Comment by basisbit** [comment]
could you please create a PR for this? the file can be found here: https://github.com/bigbluebutton/bigbluebutton/blob/3424c5b7c9ea4d7d432254f3f4c1c818b47ef503/bigbluebutton-config/bin/bbb-conf#L796

**Comment by Dennis1993** [comment]
I created a pull request, thanks for your report @paulmenzel 

PR: https://github.com/bigbluebutton/bigbluebutton/pull/11043

**Comment by antobinary** [comment]
Thank you for spotting it and the quick PR!

**Comment by paulmenzel** [comment]
Thank you all for quickly resolving this.
