### ISSUE TITLE
2.2.31 bbb-html5 does not start in unprivileged LXD container

### ISSUE THREAD

**Issue by janmuennich** [bigbluebutton/bigbluebutton#11031]
It seems that in 2.2.31 two options were added to `/usr/lib/systemd/system/bbb-html5.service` that prevent it from starting within an unprivileged LXD container.

**Fix:**
Comment out:
```
#CPUSchedulingPolicy=fifo
#Nice=19
```
```
systemctl daemon-reload
service bbb-html5 start
```

If these options are going to stay, this fix should be documented at: https://docs.bigbluebutton.org/2.2/troubleshooting.html#running-within-an-lxd-container

**Comment by bilias** [comment]
Probably this will work for you

https://github.com/bigbluebutton/bigbluebutton/pull/11022

**Comment by janmuennich** [comment]
Thanks, didn't see the PR.

**Comment by ffdixon** [comment]
https://docs.bigbluebutton.org/2.2/troubleshooting.html#bbb-html5-fails-to-start-with-a-setscheduler-error
