### ISSUE TITLE
Enhancement: add meeting-token or meeting-id to the logout/redirect URL

### ISSUE THREAD

**Issue by bigbluebutton-issue-import** [bigbluebutton/bigbluebutton#1104]
Originally reported on Google Code with ID 349

```
If possible please pass the id of the meeting or the full meeting-token to
the url that get's called when the user logs out of the conference. 

The idea is to redirect the user to a evaluation-form so he/she can enter
information about the meeting he/she attended to. 

This could be great feedback for as well the meeting-host as well as the
admin of the server/service/BBB.

```

Reported by `wpm.tak` on 2010-02-10 20:45:16

**Comment by ffdixon** [comment]
A further enhancement to this would be to add wildcards to the `logoutURL` to enable passing other parameters, such as %%ROLE%%.

**Comment by premmohantyagi** [comment]
Waiting..............  for this enhancement. need to pass the different-2 parameter  for moderator and viewer with logoutURL

**Comment by matiasilva** [comment]
@premmohantyagi Comments like yours aren't very nice to the developers and contributors to this project as you're implying that they are somehow working for you and only you. Please, embrace the open-source side to this project and collaborate and contribute constructively :-)

**Comment by iSamof** [comment]
You know something is not right when a poster 'likes' or up-votes his own post.

**Comment by jamesexperts** [comment]
> @premmohantyagi Comments like yours aren't very nice to the developers and contributors to this project as you're implying that they are somehow working for you and only you. Please, embrace the open-source side to this project and collaborate and contribute constructively :-)

Thanks for remind

**Comment by premmohantyagi** [comment]
> 
> 
> @premmohantyagi Comments like yours aren't very nice to the developers and contributors to this project as you're implying that they are somehow working for you and only you. Please, embrace the open-source side to this project and collaborate and contribute constructively :-)

Thanks for remind
