### ISSUE TITLE
Chat notification while chat is open

### ISSUE THREAD

**Issue by H-B-Schmidt** [bigbluebutton/bigbluebutton#11042]
It would be nice to get  another option for chat audio/popup notification that will notify on a chat message even while the chat is open. 

Teachers sometimes don't look at the screen at all while stylus writing on another device and would like to be notified when a student is communicating via chat.

**Comment by behzadi9667** [comment]
hi fiends you don't have an answer for this question???????  because I have similar  question !
?
?
?
@H-B-Schmidt @basisbit @iMonZ @znerol @kishba
