### ISSUE TITLE
Waiting room page still not found in 2.3a4

### ISSUE THREAD

**Issue by Beiri22** [bigbluebutton/bigbluebutton#11053]
I've just updated version 2.3 from alpha-3 to alpha-4. When I am using the waiting room feature, the waiting room page seems to be not found.

Reproduce:
1. Create new room with waiting room feature activated / moderator has to approve all new guests.
2. Let new guest enter.
3. Guest gets 404 (https://FQDN/bigbluebutton/api/join?fullName=NAME&join_via_html5=true&meetingID=SOMETHING&password=SOMETHING&userID=gl-guest-SOME&checksum=SOME)

**Comment by antobinary** [comment]
Addressed in #11104
