### ISSUE TITLE
Record the events of external video share and publish the link in chat 

### ISSUE THREAD

**Issue by hiroshisuga** [bigbluebutton/bigbluebutton#11051]
**Is your feature request related to a problem? Please describe.**
Students complain that in the playback they cannot see the external videos shared in the live session. 

**Describe the solution you'd like**
Record the video sharing events in the events.xml and publish them in the chat pane when played back, so that students can watch them by clicking the link.

**Describe alternatives you've considered**
Ideally, the shared external video should show up directly in the playback screen, but it would not be possible due to technical and probably copyright reasons. 

**Additional context**

**Comment by pedrobmarin** [comment]
I'll consider the core of this one as `done`
