### ISSUE TITLE
Missing folder for Recording BBB2.3-Dev Alpha 2 & 3

### ISSUE THREAD

**Issue by Rahimimojtaba** [bigbluebutton/bigbluebutton#11058]
The recording process face with error. I checked the logs and found that some folder missed in the path /var/bigbluebutton/recording/status/published/
When I created manually in the above path, recording process start to work normally without any issues.

**To Reproduce**
1. Open a session
2. Start recording
3. End the meeting and check the journalctl -u bbb-rap-resque-worker

**Expected behavior**
After end of meeting, the system should process the recording.

**Actual behavior**
Have an error that show directory not found.

**Comment by ffdixon** [comment]
Thanks for reporting this -- we'll have it fixed for 2.3-alpha4 (coming soon!).

**Comment by antobinary** [comment]
Resolved in https://github.com/bigbluebutton/bigbluebutton/releases/tag/v2.3-alpha-4
