### ISSUE TITLE
Dev2.3-alpha3: menues aren't closing by just clicking outside the menu area

### ISSUE THREAD

**Issue by PhMemmel** [bigbluebutton/bigbluebutton#11059]
**Describe the bug**
Menus aren't closing when clicking somewhere else

**To Reproduce**
1. Join session
2. Open menu by clicking on gear of list of participants (same for three dot menu of public chat)
3. Click somewhere outside the menu
4. menu doesn't close

**Expected behavior**
Menues should close when clicking somewhere else, especially when a new/different menu is opened

**Actual behavior**
Menues don't close.

**BBB version (optional):**
2.3-dev, alpha 3, as currently running on dev23.bigbluebutton.org

**Desktop (please complete the following information):**
Chrome, Firefox, don't think there's a difference in OS or Browsers

**Smartphone (please complete the following information):**
not relevant for smartphones cause menues will pop up as fullscreen with closing button

**Additional context**
just a minor problem, low priority I guess.
"three dot menu" in the right upper corner not affected by that behaviour.

**Comment by ramonlsouza** [comment]
@pedrobmarin fixed by #11364
