### ISSUE TITLE
Change locale BBB2.3-Dev Alpha 3

### ISSUE THREAD

**Issue by Rahimimojtaba** [bigbluebutton/bigbluebutton#11056]
I tested the BBB 2.3 alpha 2 and also alpha 3. Same problem in both version, when you change the fallbackLocale and overrideLocale value in settings.yml for html5 meteor bundle to one of the languages that have underscore (_) (ex. pl_PL) , the users couldn't join into the meeting and freeze on three dots.

**To Reproduce**
1. Go to settings.yml file of html5
2. On line 57 and 58, change it to pl_PL (or any other underscore locale(_) ex. fa_IR)
3. Save and restart BBB
4. Try to join into a session
5. Also check the  browser console while you are joining

**Expected behavior**
I should change the language of user interface while user join into meeting.

**Actual behavior**
Freese on three dots and user can't join into the meeting.

BigBlueButton Server 2.3-Dev Alpha 3

 - OS: Windows 10
 - Browser Chrome, FireFox and Edge
 - Version 87.0.4280.88 (Official Build) (64-bit)

**Comment by cod3r0k** [comment]
Do you have any idea? @ffdixon, I checked it. He said right, but we can change language anymore during the session and this happened just in the joining situation

**Comment by cod3r0k** [comment]
Dear @antobinary and @Rahimimojtaba , What should we do before the new release come?? Could you help me to use it for pl_PL ?
