### ISSUE TITLE
BBB2.3-Dev Multiple HTML5 Process

### ISSUE THREAD

**Issue by Rahimimojtaba** [bigbluebutton/bigbluebutton#11057]
As new feature added to BBB 2.3-Dev Alpha 3 for HTML5 multiple process, this feature have some issues.
When you set number of HTML5 process more than 1 process in the apply-config.sh (setNumberOfHTML5Processes 2), first you need to restart manually the bbb-html5 service by systemctl restart bbb-html5.service. So with bbb-conf --restart, it'll not applied to it. Another issue is about the console error that show 404 not found for silence.mp3. As the URL is not correct and I think one slash (/) missed between the resources and the process number. Check below:
https://bbb.example.com/html5client/2resources/sounds/silence.mp3

**To Reproduce**
1. Go to apply-config.sh
2. Change the value of setNumberOfHTML5Processes 2
3. Save the file and run bbb-conf --restart
4. If with bbb-conf --restart not applied, try to run systemctl restart bbb-html5.service
5. Then create a new session and join into the session
6. Check the browser console and you'll find the 404 not found error

**Expected behavior**
1- After changing setNumberOfHTML5Processes in apply-config.sh, it should applied with bbb-conf --restart
2- Should find the silence.mp3 file and have slash (/) in the URL after node number

**Actual behavior**
1- Not applied after running bbb-conf --restart
2- Missed the slash (/) after node number in the URL

**Screenshots**
https://gofile.io/d/ibU5Ln

BigBlueButton Server 2.3 Alpha 3

 - OS: Windows 10
 - Browser Chrome, FireFox and Edge
 - Version 87.0.4280.88 (Official Build) (64-bit)

**Comment by antobinary** [comment]
Hi @Rahimimojtaba 

Thank you for reporting these. I just fixed the silence.mp3 path in #11112

Regarding the number of nodejs processes - the idea is to make the change in the script *and to run the script* right away
