### ISSUE TITLE
akka-apps(bbb.properties): Inactivity check is not working

### ISSUE THREAD

**Issue by mschwrdtnr** [bigbluebutton/bigbluebutton#11062]
**Describe the bug**
I want to use the following settings in [bigbluebutton.properties](https://github.com/bigbluebutton/bigbluebutton/blob/145107166803b7203664cb3cd3591c3aaa26cd8b/bigbluebutton-web/grails-app/conf/bigbluebutton.properties):
- userInactivityInspectTimerInMinutes
- userInactivityThresholdInMinutes
- userActivitySignResponseDelayInMinutes

I tested several options and never got disconnected because of inactivity or got any dialog.

**To Reproduce**
1. Set `userInactivityInspectTimerInMinutes` to 1
2.  Set `userInactivityThresholdInMinutes` to 5
3.  Set `userActivitySignResponseDelayInMinutes` to 3
4.  Connect to the meeting in another browser or an another client (without being an Moderator).
5.  Wait 10 Minutes. Nothing will happen.

**Expected behavior**
I want to get kicked if I am not active after the given time of minutes.

**Actual behavior**
I don't see any warning and don't get kicked because of inactivity.

**Desktop:**
 - OS: Windows
 - Browser: Chrome, Firefox

**Comment by mrkeksi** [comment]
I have set the following settings to 60 minutes:
userInactivityInspectTimerInMinutes
userInactivityThresholdInMinutes

**Comment by mrkeksi** [comment]
@antobinary nice thanks 👍  I guess I have overlooked the pull request

**Comment by mschwrdtnr** [comment]
So @antobinary and @mrkeksi you can both confirm that the inactivity check is working and this issue can closed?

**Comment by antobinary** [comment]
The inactivity check is **not** fully working and @gustavotrott is on it.

Expect Gustavo's updates shortly. Please keep the issue open.
