### ISSUE TITLE
404 in html5client in 2.3-alpha-3

### ISSUE THREAD

**Issue by freddygreve** [bigbluebutton/bigbluebutton#11067]
**Describe the bug**
After joining a room the url (https://bbb.example.com/html5client/1/join?sessionToken=***********) is not found (404).

**To Reproduce**
1. Open the BBB Web Api demo
2. Join a room

No error in `bbb-conf --status`:
```
nginx —————————————————► [✔ - active]
freeswitch ————————————► [✔ - active]
redis-server ——————————► [✔ - active]
bbb-apps-akka —————————► [✔ - active]
bbb-fsesl-akka ————————► [✔ - active]
tomcat8 ———————————————► [✔ - active]
mongod ————————————————► [✔ - active]
bbb-html5 —————————————► [✔ - active]
bbb-webrtc-sfu ————————► [✔ - active]
kurento-media-server ——► [✔ - active]
etherpad ——————————————► [✔ - active]
bbb-web ———————————————► [✔ - active]
```
`

**Comment by hiroshisuga** [comment]
hope 
bbb−conf −−setip fqdn
solves the problem.

**Comment by freddygreve** [comment]
> bbb−conf −−setip fqdn

I've already tried that. Unfortunately nothing changes.

**Comment by freddygreve** [comment]
I've found this in `bbb-conf --debug`:

```
Dec 22 23:57:14 h2889551 sh[23392]: SignalException: SIGTERM
Dec 22 23:57:15 h2889551 sh[23392]: Original Exception (Redis::CannotConnectError): Error connecting to Redis on 127.0.0.1:6379 (Errno::ECONNREFUSED)
Dec 22 23:57:15 h2889551 sh[23392]: /usr/lib/ruby/vendor_ruby/rake/application.rb:186:in `standard_exception_handling'
```

**Comment by xlan-codes** [comment]
I have the same problem

**Comment by Rahimimojtaba** [comment]
It's because of HTML5 node process.
Let's try: systemctl restart bbb-html5
Then try again.
I've created issue about this problem:
https://github.com/bigbluebutton/bigbluebutton/issues/11057

**Comment by freddygreve** [comment]
I know your report. Unfortunately, that doesn't improve anything either.

**Comment by jrk-omf** [comment]
Having a similar issue: https://bbb.example.com/html5client/guestWait?sessionToken=xxxxxxxxxxxxx if the room is set to be moderator controlled facing also a 404 error

**Comment by antobinary** [comment]
@freddygreve what do you get when you run `ps -ef | grep node-` ? 
Additional info may be found via `sudo journalctl -u bbb-html5-worker@*`

@jrk-omf this is a separate issue that I had missed in alpha3 and is resolved in the upcoming 2.3-alpha5 (see PR #11104 )

**Comment by freddygreve** [comment]
> @freddygreve what do you get when you run `ps -ef | grep node-` ?

That one is only
`root      5368  1466  0 00:30 pts/0    00:00:00 grep --color=auto node-`


> Additional info may be found via `sudo journalctl -u bbb-html5-worker@*`
```
Jan 07 00:27:58 h2889551.stratoserver.net systemd[1]: Started BigBlueButton HTML5 service, instance 1.
Jan 07 00:28:03 h2889551.stratoserver.net systemd[1]: bbb-html5-worker@1.service: Main process exited, code=exited, status=214/SETSCHEDULER
Jan 07 00:28:03 h2889551.stratoserver.net systemd[1]: bbb-html5-worker@1.service: Failed with result 'exit-code'.
```

**Comment by freddygreve** [comment]
I have solved this issue:

1. create this folder `/etc/systemd/system/bbb-html5.service.d`

2. add the file `/etc/systemd/system/bbb-html5.service.d/override.conf`:

```
[Service]
CPUSchedulingPolicy=other
Nice=-10
```

3. Change the file `/usr/lib/systemd/system/bbb-html5-worker\@.service`

```
CPUSchedulingPolicy=other
Nice=-10
```

4. Restart BBB
```
systemctl daemon-reload
bbb-conf --restart
```

**Comment by cod3r0k** [comment]
Dear @antobinary & @ffdixon ; Do we have the same issue now (on alpha-5)? I check the entrance of the `guestPolicy=ASK_MODERATOR` option on apimate and I get the 404 error from the nginx but in BBB the moderator see the attendee's request. When the moderator accept him/her, nothing will be happened because the attendee get stuck in the 404 not found page of nginx.
