### ISSUE TITLE
No interaction with text in chat area in 2.3-alpha-3 possible

### ISSUE THREAD

**Issue by hex-m** [bigbluebutton/bigbluebutton#11064]
**Describe the bug**
In BigBlueButton 2.3-alpha-3 links in the chat area can't be clicked and text can't be selected.

**To Reproduce**
1. Go to 'https://test23.bigbluebutton.org'
2. Create a room
3. Start a meeting
3. write a URL into the chat
4. try to click it

Tested with Firefox and Chromium.

**Comment by b01xy** [comment]
I can confirm the issue on a ubuntu 18.04 installation

**Comment by hiroshisuga** [comment]
#11080 may have fixed the problem.

**Comment by b01xy** [comment]
Yes, solved after update, great, thanks !
