### ISSUE TITLE
For Load Balancing reasons- ask Meeting Creator on Start how many participates will connect (max)

### ISSUE THREAD

**Issue by netzwerk-azv** [bigbluebutton/bigbluebutton#11063]
The Loadbalancing (at least via Scalelite) is not very efficient right now. 
There is always the problem of meetings starting with low participant numbers which grow over time being placed on the same server.
Result is something like:
Server A: 4 Meetings with 400 Users total
Server B: 4 Meetings with 75 Users total

Why not make a variable (max_participant) and whenever a meeting is started or a room is created (through Greenlight). And  it will ask the moderator how many Users he assumes will be max? Like:

up to 25
between 25 and 75
more than 75

The Loadbalancer could then use this number to calculate the best server for the meeting. 
My hope would be a better balance in usercounts.

I know this would need a change in scalelite (ar any other loadbalancer) too but without this variable being set in Greenlight a use in Scalelite is not possible.

**Comment by pedrobmarin** [comment]
Bigbluebutton already have such thing: `maxParticipants` at https://docs.bigbluebutton.org/dev/api.html#create
I'm closing this issue and suggest you check Greenlight/Scalelite repositories for support on this one.
