### ISSUE TITLE
Problems after installing BBB with bbb-html5 and freeswitch

### ISSUE THREAD

**Issue by compelectr** [bigbluebutton/bigbluebutton#11066]
After the installation, BBB will run. Only the conference cannot be entered. This is followed by the error: 404 Not Found
nginx

nginx ▒————————————————————► [✔ - active]
freeswitch ▒▒——————————————————► [✘ - failed]
redis-server ——————————————————► [✔ - active]
bbb-apps-akka ▒▒—————————————————► [✔ - active]
bbb-transcode-akka ————————————————► [✔ - active]
bbb-fsesl-akka ▒—————————————————► [✔ - active]
red5 ▒▒————————————————————► [✔ - active]
mongod ————————————————————► [✔ - active]
bbb-html5 ———————————————————► [✘ - failed]
bbb-webrtc-sfu ▒—————————————————► [✔ - active]
kurento-media-server ▒———————————————► [✔ - active]
etherpad ▒———————————————————► [✔ - active]
bbb-web ▒▒———————————————————► [✔ - active]

BigBlueButton Server 2.2.31 (2307)
                    Kernel version: 4.4.0
                      Distribution: Ubuntu 16.04.7 LTS (64-bit)
                            Memory: 25165 MB
                         CPU cores: 8

/usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties (bbb-web)
       bigbluebutton.web.serverURL: https://v-conferences.de
                defaultGuestPolicy: ALWAYS_ACCEPT
                 svgImagesRequired: true

/etc/nginx/sites-available/bigbluebutton (nginx)
                       server_name: v-conferences.de
                              port: 80, [::]:80
                              port: 443 ssl

/opt/freeswitch/etc/freeswitch/vars.xml (FreeSWITCH)
                       local_ip_v4: 195.90.200.247
                   external_rtp_ip: 195.90.200.247
                   external_sip_ip: 195.90.200.247

/opt/freeswitch/etc/freeswitch/sip_profiles/external.xml (FreeSWITCH)
                        ext-rtp-ip: $${local_ip_v4}
                        ext-sip-ip: $${local_ip_v4}
                        ws-binding: 195.90.200.247:5066
                       wss-binding: 195.90.200.247:7443

/usr/local/bigbluebutton/core/scripts/bigbluebutton.yml (record and playback)
                     playback_host: v-conferences.de
                 playback_protocol: https
                            ffmpeg: 4.2.4-1ubuntu0.1bbb1~16.04.1

/etc/bigbluebutton/nginx/sip.nginx (sip.nginx)
                        proxy_pass: 195.90.200.247
                          protocol: http

/usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml (Kurento SFU)
                        kurento.ip: 195.90.200.247
                       kurento.url: ws://127.0.0.1:8888/kurento
                    kurento.sip_ip: 195.90.200.247
                    localIpAddress: 195.90.200.247
               recordScreenSharing: true
                     recordWebcams: true
                  codec_video_main: VP8
               codec_video_content: VP8

/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml (HTML5 client)
                             build: 1114
                        kurentoUrl: wss://v-conferences.de/bbb-webrtc-sfu
                  enableListenOnly: true
                    sipjsHackViaWs: true

/usr/share/bbb-web/WEB-INF/classes/spring/turn-stun-servers.xml (STUN Server)
                              stun:stun.l.google.com:19302

# Potential problems described below
grep: /opt/freeswitch/var/log/freeswitch/freeswitch.log: No such file or directory

#
# Error: Unable to connect to the FreeSWITCH Event Socket Layer on port 8021
#
# Warning: The voice application may not have registered with the sip server.
#   Try running:
#
#      bbb-conf --clean
#

# Error: Could not detect FreeSWITCH listening on port 5060

# Error: FreeSWITCH failed to start with SETSCHEDULER error, see
#
#   http://docs.bigbluebutton.org/2.2/troubleshooting.html#freeswitch-fails-to-start-with-a-setscheduler-error

**Comment by prlanzarin** [comment]
C'mon now, there's a documentation pointer at the end of bbb-conf --status output you posted that explains how to fix your issue.

Also: setup support is not done via github. See: https://docs.bigbluebutton.org/2.2/getting-help.html
