### ISSUE TITLE
Recording ready url is not getting called 

### ISSUE THREAD

**Issue by Bharat-vyas** [bigbluebutton/bigbluebutton#11072]
**Describe the bug**
We have installed bbb-2.3-dev in ubuntu 18.04 (Bionic Beaver)
After recording a meeting, the recording ready callback URL doesn't work. We have tried by passing the 'bbb-recording-ready-url' parameter both with and without urlencode but still the ready callback url is not getting called. Although, the call back url is correct which we verified in event.xml generated for each recording

Due to this issue we are unable to fetch recordings.

**Expected behavior**
Callback URL should be called mentioning in the bbb-recording-ready-url parameter 

**Actual behavior**
Callback URL in not getting called 

**Desktop (please complete the following information):**
 - OS: ubuntu18.04
 - Browser [ Chrome]

**Comment by Bharat-vyas** [comment]
Is there any updates or this issue or anyone else around facing the same issue ?

**Comment by kumar-m-ecot** [comment]
Hi Folks,

I am facing exactly similar issue in same Ubuntu 18.04 Version. Any suggestion or help would be appreciated.

**Comment by kumar-m-ecot** [comment]
Hi.

Anybody i having any kind of useful updates or suggestions?

**Comment by kumar-m-ecot** [comment]
Hi @ffdixon @ritzalam 

Good day!

Is there any update/suggestion which can help us with the reported issue?

**Comment by ffdixon** [comment]
We are working on 2.3-alpha5.  No promises that we can fix this problem in the next update, but we resolve it in 2.3-dev.

**Comment by kumar-m-ecot** [comment]
Thanks for the update @ffdixon 

Can we expect any tentative date for this to be fixed?

Thanks in advance!

**Comment by ffdixon** [comment]
Not sure if this fix will be in alpha5.  We want to stabilize this build as soon as possible for the user first, which is a higher priority than subsequent processing of recordings.  We will fix this issue as part of 2.3-dev.

**Comment by kumar-m-ecot** [comment]
Hi @ffdixon 

Good Day!

Are there any plans or a tentative date now, you can share with us regarding the reported issue to be fixed.

I already appreciate your work!

Thanks.

**Comment by dev-umesh** [comment]
Hello @ffdixon @ritzalam 

I hope you guys are doing good, I am facing the similar issue posted by @kumar-m-ecot . Any updates regarding the issue or fixes would be greatly appreciated. Great work BTW!!

Thank you

**Comment by dhavalparmar13** [comment]
Hi @ffdixon and @ritzalam 

I am also facing similar type of issues regarding recording posted by @kumar-m-ecot on the same ubuntu 18.04 version, Is there any update on the fix? 

Thanks in advance.

**Comment by ffdixon** [comment]
We will be looking at this in subsequent updates to BigBlueButton 2.3-dev as it's a needed feature.

**Comment by pedrobmarin** [comment]
BigBlueButton has a feature called webhooks that can be used to cover needs exact like this one (and many others). There is a good documentation about it here https://docs.bigbluebutton.org/dev/webhooks.html

**Comment by dhavalparmar13** [comment]
Hi @ffdixon I am facing this issue from a long time do you guys have any tentative date we can have the fix on the issue please.
Thanks

**Comment by ffdixon** [comment]
It's tagged for 2.3 and we will fix it!  Just trying to get the main features in place first.  Rest assured, this will be fixed.

**Comment by kumar-m-ecot** [comment]
Hi Fred,

Just Following up to check if your team got any tentative timeline to fix this issue in v2.3?

Thanks in advance.

**Comment by kumar-m-ecot** [comment]
Hi @ffdixon 

I am following up to check with you if the any timeline has been planed for this issue to be fixed. If yes, can you please share the tentative date?

Thanks already for your support!

**Comment by pedrobmarin** [comment]
https://github.com/bigbluebutton/bigbluebutton/issues/8392
