### ISSUE TITLE
Fast forward feature in playback (mobile/android css) not visible

### ISSUE THREAD

**Issue by mabdullahijaz** [bigbluebutton/bigbluebutton#11076]
I have found that newly added feature of fastfarword in playback media player is not visible. 
Please see this demo playback video
https://test23.bigbluebutton.org/playback/presentation/2.0/playback.html?meetingId=5437844a34defd19fa59de1efe432db67b0fead0-1609013597135

**Comment by basisbit** [comment]
please use the issue template and fill it in. thanks.

**Comment by ffdixon** [comment]
Updated test23.bigbluebutton.org.  The link now properly displays the new player.
