### ISSUE TITLE
Bigbluebutton 2.3 meta bbb-recording-ready-url not working

### ISSUE THREAD

**Issue by Kaabi** [bigbluebutton/bigbluebutton#11073]
**Describe the bug**
Bigbluebutton 2.3 meta bbb-recording-ready-url not working

**To Reproduce**
1. Create New Session with webhook
2. Create meta bbb-recording-ready-url
3. Start Recording
4. End Session

**Expected behavior**
to callback the bbb-recording-ready-url with presentation information and log the result failed or success at /var/log/bigbluebutton/post_publish.log 

**Actual behavior**
the bbb-recording-ready-url meta is doesn't call and the file /var/log/bigbluebutton/post_publish.log is not exist

**Additional context**
This work flawless in BBB 2.2.x but in 2.3 is doesn't work I tested this on BBB 2.3-Alpha 2 & 3

**Comment by ffdixon** [comment]
Can you upgrade to 2.3-alpha4 and let us know if this is still an issue.

**Comment by Kaabi** [comment]
> Can you upgrade to 2.3-alpha4 and let us know if this is still an issue.

I tested it on 2.3-alpha4 the problem is resolved on this version
