### ISSUE TITLE
new alternative for handling recording in html5

### ISSUE THREAD

**Issue by maychine-fatima** [bigbluebutton/bigbluebutton#11082]
For  some cases like connection issue the recording takes a long time so i preferred to do it in the front-end , i used MediaRecorder  like this way: 

let stream;
  const constraints = { video: false, audio: true };

  try {
    stream = await navigator.mediaDevices.getUserMedia(constraints);
  } catch (error) {
    throw new Error(`
      MediaDevices.getUserMedia() threw an error. 
      Stream did not open.
      ${error.name} - 
      ${error.message}
    `);
  }

var options = {mimeType: 'audio/webm'};
mediaRecorder = new MediaRecorder(stream, options);
var constraints = {
  audio: true,
  video: false
};
mediaRecorder.ondataavailable = handleDataAvailable;

but the ondataavailable is not fired in the frontend after the user is talking, it's like it's not detecting the stream, can anyone help me here.

**Comment by antobinary** [comment]
Development questions usually get better response rate at the dev group https://groups.google.com/g/bigbluebutton-dev
