### ISSUE TITLE
dev/bbb 2.3 latest - Missing information to STATS_HELP_URL

### ISSUE THREAD

**Issue by lonesomewalker** [bigbluebutton/bigbluebutton#11088]
**Describe the bug**
When entering a conference with network issues, the top bar notifies you about having some issues and provides a clickable link.
However, when you follow this:

Forbidden
Session token was not provided
401

**BBB version (optional):**
BigBlueButton Server 2.3.0-alpha4 (1476)

**Comment by ffdixon** [comment]
Thanks -- it is a placeholder at the moment. We'll likely implement it in a similar way to the help URL in the settings menu.

**Comment by lonesomewalker** [comment]
Yup, found it in the settings.
Is there a plan to offer this as a local file or prefered external?

**Comment by ffdixon** [comment]
Closing as the connectivity message has been replaced by the connectivity status icon.
