### ISSUE TITLE
External videos doesnt appear in recording

### ISSUE THREAD

**Issue by human-bieng** [bigbluebutton/bigbluebutton#11086]
Hello there 
I am using Bigbluebutton 2.3 
When i open room & add external video i found it doesnt appear within playback

**Comment by ffdixon** [comment]
Correct.  

When you share an external video, each browser is told to load the video.   Currently, the BigBlueButton server does not download the video itself, so it doesn't have it for inclusion within the recording.

We could modify the player when viewing a recording to play the external video at the same time it was played in the live session.  We've not explored doing this yet, but it is one possible solution.

**Comment by hiroshisuga** [comment]
@human-bieng , you are not the only one;-)

You may want to follow the progress in the new playback app here:
https://github.com/bigbluebutton/bbb-playback/issues/17

In #11051 , I have proposed another solution (although it's closed already); just showing the URL of external video in the chat window will help following the playback.

**Comment by ffdixon** [comment]
Showing the URL is not a bad suggestion.  We've moved to the new player in BigBlueButton 2.3-dev, and we'll be exploring options for including the external video in the playback.

**Comment by human-bieng** [comment]
Thank you so much Fred
We realy appreciate this & we seee different change in paths & icons too
I am searching a way to change paly back bigbluebutton icon for playback
but it doesnt work with replacing old files

**Comment by pedrobmarin** [comment]
Closing this in favor of https://github.com/bigbluebutton/bigbluebutton/issues/10091
