### ISSUE TITLE
Error 1002, could not connect to websocket on fresh install

### ISSUE THREAD

**Issue by orangethakkali** [bigbluebutton/bigbluebutton#11083]
I know this has been discussed multiple times but I'm not able to get this wonderful piece working. I ran `wget -qO- https://ubuntu.bigbluebutton.org/bbb-install.sh | bash -s -- -w -a -v xenial-22 -s bbb.example.com -e info@example.com` replacing the domain name and email, installation was successful on Ubuntu 16.04 with 8GB Ram VPS. I do not have NAT or Firewall and I see only eth0 and lo interfaces in ifconfig. So I assume this is not going to be complicated and there is just one static public IPV4 that I need to use everywhere.

I can connect to the domain and creating a meeting but when I try to join audio or do screen share, I get `Could not connect to WebSocket`. And this is what I get on the FF console.

`Firefox can’t establish a connection to the server at wss://connect.dataprik.com/ws?sessionToken=a5p4dbvlqrz9ilex.
Mon Dec 28 2020 12:12:25 GMT+0530 (India Standard Time) | sip.Transport | WebSocket error occurred. sip.js:9594:25
    print https://connect.dataprik.com/html5client/compatibility/sip.js?v=1114:9594
    genericLog https://connect.dataprik.com/html5client/compatibility/sip.js?v=1114:9574
    genericLog https://connect.dataprik.com/html5client/compatibility/sip.js?v=1114:9647
    error https://connect.dataprik.com/html5client/compatibility/sip.js?v=1114:9635
    onWebSocketError https://connect.dataprik.com/html5client/compatibility/sip.js?v=1114:19246
    _connect https://connect.dataprik.com/html5client/compatibility/sip.js?v=1114:19091`

I did a clean install several times and even tried docker but the same error pops up. Have followed/referred below but no luck.

https://github.com/bigbluebutton/bigbluebutton/issues/9667
https://github.com/bigbluebutton/bbb-install/issues/275
https://github.com/bigbluebutton/bigbluebutton/issues/2628#issuecomment-635107717

`/etc/bigbluebutton/nginx/sip.nginx`
```
location /ws {
        proxy_pass https://185.213.XXX.XXX:7443;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_read_timeout 6h;
        proxy_send_timeout 6h;
        client_body_timeout 6h;
        send_timeout 6h;

        auth_request /bigbluebutton/connection/checkAuthorization;
        auth_request_set $auth_status $upstream_status;
}

```

Can someone please help me to get this working.

**Comment by ffdixon** [comment]
Check out 

  https://docs.bigbluebutton.org/2.2/getting-help.html#help-installing-or-running-bigbluebutton

for details on what information to share.  Post this question to [bigbluebutton-setup](https://bigbluebutton.org/support/community/) mailing list and, if we see an error, we'll open an issue here to track it.

**Comment by orangethakkali** [comment]
Thanks will do.

**Comment by yregaieg** [comment]
I had the same issue, after much struggling I ran `bbb-conf --check` which gave me a hint about a mis-configured ip-v4... apparently the local IP with my provider changes whenever the VM is stopped for a few days.. Once I adjusted that to the new value every thing started working as expected ;-)
