### ISSUE TITLE
HTML5 client in 2.3-dev does not display presentation fullscreen

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#11092]
**Describe the bug**
The full screen button in BigBlueButton 2.3-alpha4 does not make the presentation full screen.

**To Reproduce**
1. Go to test23.bigbluebutton.org
2. Click on the maximize presentation button

**Expected behavior**
Expect presentation to be full screen

**Actual behavior**
In full screen it still has a large black border around it.

**Screenshots**

![BigBlueButton_NotFullScreen](https://user-images.githubusercontent.com/290351/103287861-f568de00-49b9-11eb-8b5b-55d59ce9a8c1.png)

**Comment by hiroshisuga** [comment]
This PR #10604 quickly fixes the problem at least in my server.

**Comment by AlexanderTN** [comment]
Hi,
I also notice that not only the fullscreen have bug, but the fit to witch in release 2.3  have problem (not working), because of this change in render() (in bigbluebutton-html5/imports/ui/components/presentation/component.jsx)
//in bbb 2.2.31
if (this.refWhiteboardArea) { // This version works well
      if (svgWidth === presentationAreaWidth
        || presentationAreaWidth <= 400
        || fitToWidth === true) {
        toolbarWidth = '100%';
      } else if (svgWidth <= 400
        && presentationAreaWidth > 400) {
        toolbarWidth = '400px';
      } else {
        toolbarWidth = svgWidth;
      }
    }
//in bbb 2.3 which has the problem
if (this.refWhiteboardArea) {
      toolbarWidth = svgWidth;
}

**Comment by mrkeksi** [comment]
I have this bug in Safari (see screenshot) I also can't press the lower right button to minimize the fullscreen. When I click the upper right button zu minimize I got a empty white screen (why white?). in Chrome on MacOS iit works as desired. <img width="1440" alt="image" src="https://user-images.githubusercontent.com/8763656/115955778-043f4780-a4f9-11eb-9b2b-c7123723d768.png">

testet on test23 with RC1

**Comment by antobinary** [comment]
The layout system saw very significant refactor in BBB 2.4. Please report if you encounter issues similar to this on 2.4+
