### ISSUE TITLE
Video focus on the speaker

### ISSUE THREAD

**Issue by siavash79** [bigbluebutton/bigbluebutton#11102]
**Describe the solution you'd like**
Like some other video conferencing solutions do, it would be great if the speaker (whose video gets a highlight when they speak), can also gain a higher frame size as well (speaker almost full screen and others as thumbnail-sized frames). This way, listeners will get a more clear (and detailed) picture of the person who is speaking. This specially gets more useful when the presentation is minimized.
I believe since the highlighting code is already written, it can be used for this purpose as well.

**Example screenshot from zoom**
![zoom%20active%20speaker%20view](https://user-images.githubusercontent.com/25217714/103534297-0a58dc00-4ea8-11eb-913c-bb6cb4d1eacd.png)

**Comment by ffdixon** [comment]
Thanks for the suggestion.  Merging into https://github.com/bigbluebutton/bigbluebutton/issues/8388.
