### ISSUE TITLE
Big Blue Button recording playback does not contain audio

### ISSUE THREAD

**Issue by mhd-shf** [bigbluebutton/bigbluebutton#11101]
Why does recording playback sometimes have no audio?
What might be causing this problem?
Only occasionally this problem happen!!!

**Comment by basisbit** [comment]
For support requests, please use the [forum / mailing list](https://groups.google.com/forum/#!forum/bigbluebutton-setup). This issue tracker here is only for BBB development related issues. Sorry.
You also did not provide any details, no logs, server version,... and thus made it impossible for us to help you.
