### ISSUE TITLE
Iphone XS playback recording shows chats but not presentation Error: no compatible source was found for this media.

### ISSUE THREAD

**Issue by erpsolns** [bigbluebutton/bigbluebutton#11100]
<!--PLEASE DO NOT FILE ISSUES FOR GENERAL SUPPORT QUESTIONS.
Version BBB2.3alph4  
browser safari14

**Describe the bug**
The recorded meeting is played on mac/android properly - but users say -  in Iphone devices they see only chat not presentation or video- he message. .no compatible source was found for this media..

**To Reproduce**
1. Go to '...'Click the link for recorded meeting
2. Click on '..After it opened up..'

**Expected behavior**

**Actual behavior**

**Screenshots**

**BBB version (optional):**
BigBlueButton Server 2.23 alpha4

**:**

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhoneXS]
 - Browser Safari]
 - Version [14]

![nocompatible devicewasfound](https://user-images.githubusercontent.com/31876291/103474753-04f18800-4dfb-11eb-984f-47436f47b5c2.jpeg)

**Comment by erpsolns** [comment]
on Ipad and iPhone 7s also the same error reported

**Comment by ffdixon** [comment]
See https://docs.bigbluebutton.org/2.2/customize.html#enable-playback-of-recordings-on-ios

**Comment by erpsolns** [comment]
thank you.
