### ISSUE TITLE
recordings processing few days

### ISSUE THREAD

**Issue by datapack** [bigbluebutton/bigbluebutton#11103]
Hello,
I have BBB installed on an EDU institute.
They have many lessons per day and some of them with a duration of 3-4 hours.
As I see now, we are almost 10 days back on recordings.
Is it any way to change processing speed?
![htop](https://user-images.githubusercontent.com/1810382/103561046-84e22580-4ec1-11eb-81a2-4615bb1290c1.png)

Server Load average:1.80

Server Hardware : 
AMD EPYC™ 7502P 32-Core "Rome"
RAM: | 128 GB DDR4 ECC
1.92 TB NVMe SSD Datacenter Edition

**Comment by nikkei00** [comment]
https://github.com/bigbluebutton/bigbluebutton/issues/8770#issuecomment-600656480


Yes, I also tested it, increasing only threads didn't do anything, but
"-quality realtime -speed 5 -tile-columns 2 -threads 4"
like this, the encoding speed incresed 5-6 times.

**Comment by basisbit** [comment]
For support requests, please use the [forum / mailing list](https://groups.google.com/forum/#!forum/bigbluebutton-setup). This issue tracker here is only for BBB development related issues. Sorry.

**Comment by basisbit** [comment]
By the way, a BBB server will not make use of more than maybe 8 to 12 CPU cores. Your system has 32, so I suggest you to change the system to run 3 or 4 BBB servers within containers or VMs on that hardware. This will allow you to handle much more users with that server.

**Comment by basisbit** [comment]
And your Kurento setup runs with full debug logging enabled. You might want to change that as shown in https://docs.bigbluebutton.org/admin/privacy.html#kurento
