### ISSUE TITLE
While polling, or notes, curtain is open, webcam disappear if dragged. - 2.3 alpha 4/5.

### ISSUE THREAD

**Issue by Jossef-767** [bigbluebutton/bigbluebutton#11118]
**Describe the bug**
While polling, or notes, curtain is open, webcam disappear if dragged on screen.

**To Reproduce**
move the webcam while polling curtain is open.

**Actual behavior**
https://user-images.githubusercontent.com/2356928/103890878-82661280-50f1-11eb-85c3-48db45dbd884.mp4

**BBB version (optional):**
tested on https://test23.bigbluebutton.org/ - 2.3 alpha 5 and 4
Chrome.  87.0.4280.88  on  win10

**Comment by hiroshisuga** [comment]
likely related to #11071
