### ISSUE TITLE
Changed config files after update

### ISSUE THREAD

**Issue by TimNiklas-1802** [bigbluebutton/bigbluebutton#11119]
I did an update for my BigBluebutton instance and after the update some of my config files were set to the default.
As an example in the file /usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml the freeswitch IP was set back to the internal ip but I configured it to be the external IP.
What can I do to make sure this will not happen again and why does it change the files?

**Comment by ffdixon** [comment]
See https://docs.bigbluebutton.org/2.2/customize.html#apply-confsh

**Comment by basisbit** [comment]
For any further support requests, please use the [forum / mailing list](https://groups.google.com/forum/#!forum/bigbluebutton-setup). This issue tracker here is only for BBB development related issues. Sorry.
