### ISSUE TITLE
Request lifecycle

### ISSUE THREAD

**Issue by TheOneWithTheBraid** [bigbluebutton/bigbluebutton#11117]
When joining a BBB meeting using the HTML5 client, a couple of requests is sent to the server, including
- `/html5client/sockjs/info`
- `/bigbluebutton/api/enter?sessionToken=XXX`
- `/html5client/sockjs/YYY/ZZZZZZZZZ/websocket`

To be honest, I did not properly understand based on which information the last URL (the one of the web socket) is being computed. **How do I programmatically get the proper location of the web socket used for server communication?**

**Moreover, I would like to know whether there is detailed information on the commands sent via the web socket?**

I unfortunately did not find the corresponding information in the docs, but maybe I only did not realize it.

Thank you.

**Comment by basisbit** [comment]
For support requests, please use the [forum / mailing list](https://groups.google.com/forum/#!forum/bigbluebutton-dev). This issue tracker here is only for BBB development related issues. Sorry.

**Comment by TheOneWithTheBraid** [comment]
I am very sorry, but this is not at all related to support. It is a question on development.

**Comment by TheOneWithTheBraid** [comment]
We are currently working on an implementation of the BBB frontend which is more suitable for handheld devices and are hence interested in more detailed information on the way the HTML5 client works.

**Comment by basisbit** [comment]
this issue tracker here is only for bbb project internal issues, not for such questions. That is why the above post links to the dev mailing list, which is exactly for the kind of development questions that you would like to get answers for.
