### ISSUE TITLE
Silk Browser Support (Amazon Fire Tablet TV)

### ISSUE THREAD

**Issue by iwl** [bigbluebutton/bigbluebutton#11130]
On Silk Browser, Standard on Amazon Devices, says Browser to old, is newest Fire 10.
May be an issue with different Browser Name / Version only, while would work, other similar systems do.
Conferencing on Fire Tablets / Monitoring on Fire TVs would be nice, very common hardware in field.

**Comment by DanMittendorf** [comment]
1. Edit /usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml
 2. Add to supported browsers at the end
```
- browser: AmazonSilk
    version: 80
```
3. `bbb-conf --restart`
4. Enjoy!

**Comment by iwl** [comment]
I'm only an user, working browsers should be researched/tested some more and added to next version.

**Comment by kaystrobach** [comment]
Silk is still not possible by default: https://github.com/bigbluebutton/bigbluebutton/blob/f8a73cfba713936b2dc5c5067a65a8c370d4e02b/bigbluebutton-html5/private/config/settings.yml#L755

**Comment by ffdixon** [comment]
You can modify this on your server.  See https://docs.bigbluebutton.org/support/troubleshooting.html#the-browser-is-not-supported.

**Comment by kaystrobach** [comment]
Seen it - I’m just wondering why it’s not enabled by default. The engine is based on blink and chromium, but has some additions to render parts in the amazon cloud.

I’ve seen these browser quite often in the last days because of the cheap devices. And amazon made it hard to install other browsers.

Will check it out and provide some feedback.

Thank you.

**Comment by E-holland** [comment]
Hello,
I know nothing about programming and I don't think I understood the discussion above... However I have a screen on which I can use only the Silk browser and I need to get on video conferences on big blue button through https://visio-agents.education.fr/welcome where you get for example there:
https://bbb-adm-w109.visio.education.fr/html5client/join?sessionToken=upjwrnwnz13wzdru
How can I do it?
Thanks for any help you can provide.

**Comment by kaystrobach** [comment]
See docs here: https://docs.bigbluebutton.org/support/troubleshooting.html#the-browser-is-not-supported

**Comment by ffdixon** [comment]
We don't test with the Silk browser, but you can quickly visit https://test.bigbluebutton.org/ to see if it works (I'm expecting not).

**Comment by kaystrobach** [comment]
@ffdixon it works, when the setting is changed. It’s based on chromium we has thousands of participants from version 2.3 until 2.5 of BBB. Works like a charm

**Comment by E-holland** [comment]
> See docs here: https://docs.bigbluebutton.org/support/troubleshooting.html#the-browser-is-not-supported

Thank you... However I don't understand this document. I tried to type the first address (/usr/...) in Silk but it doesn't get me anywhere (except from a Bing search page)...

**Comment by kaystrobach** [comment]
@E-holland asknyour BBB Server Admin to allow Solk as browser. There is no option for you as enduser to fix this. The admin should be able to understand that document and might change the server setting.
