### ISSUE TITLE
Duplicate names in User list

### ISSUE THREAD

**Issue by Ryan-samaeian** [bigbluebutton/bigbluebutton#11138]
Names are being hidden but I shall show the full video and full image with names to the OFFICIAL MODERATORS, I dont like to show these names publicly :)  We constantly need to remove users, And its really bad, we have hit 90 PEOPLE, please help! Has someone seen a youtube video and hacked? Or did they use a free giithub script for bots 🤣 Jokes aside plz help
![Screenshot 2021-01-12 104634](https://user-images.githubusercontent.com/74070770/104282113-cbd4aa00-54c3-11eb-8068-a5338ca0f786.png)

**Comment by Ryan-samaeian** [comment]
Here is some more proof
![Screenshot 2021-01-12 105326](https://user-images.githubusercontent.com/74070770/104282545-78af2700-54c4-11eb-91b4-f3a5c0010eb6.png)

**Comment by ffdixon** [comment]
In BigBlueButton 2.2.x, if the server gets overloaded the join process for a user will take more time.  

There is a chance a user will timeout during the join process and try again; however, even though the client didn't fully load, the server still registers the user, causing a duplicate to appear in the Users list.

We have refactored the join process in 2.3-dev and should have the duplicate user problem solved in the this  release.

**Comment by Ryan-samaeian** [comment]
> In BigBlueButton 2.2.x, if the server gets overloaded the join process for a user will take more time.
> 
> There is a chance a user will timeout during the join process and try again; however, even though the client didn't fully load, the server still registers the user, causing a duplicate to appear in the Users list.
> 
> We have refactored the join process in 2.3-dev and should have the duplicate user problem solved in the this release.

Can you tell me what is causing this issue? How does the server get overloaded it gets overloaded with sessions?

**Comment by Ryan-samaeian** [comment]
> In BigBlueButton 2.2.x, if the server gets overloaded the join process for a user will take more time.
> 
> There is a chance a user will timeout during the join process and try again; however, even though the client didn't fully load, the server still registers the user, causing a duplicate to appear in the Users list.
> 
> We have refactored the join process in 2.3-dev and should have the duplicate user problem solved in the this release.

Thanks for your help :)
