### ISSUE TITLE
[Bug] Exporting Shared Notes to .txt - Incorrent formatting

### ISSUE THREAD

**Issue by jfwerner** [bigbluebutton/bigbluebutton#11134]
This is the source, how it was displayed in the browser
![This is the source, how it was displayed in the browser](https://user-images.githubusercontent.com/32206115/104197486-fd466a80-541c-11eb-8065-048773fc7d1f.png)

Exported as .txt, viewed in Notepad++
![Exported as .txt, viewed in Notepad++](https://user-images.githubusercontent.com/32206115/104197606-2109b080-541d-11eb-8046-a122651fa109.png)

As you can see the numbers are all 1s in the .txt
Export to html is not an issue

**Comment by JustinMogel** [comment]
Tested this on 2.3-alpha-8 Clientversion 1511
Using Firefox 87.0 (64-Bit) and Microsoft Edge Version 89.0.774.57
I viewed the exported .txt with Windows notepad as well as notepad++ and could not reproduce this issue.

**Comment by pedrobmarin** [comment]
v2.2 still has the problem because it's using an old version of Etherpad (v1.8.0) and, since xenial EOL is just ahead I'm marking v2.2 as a wont-fix. Fixed on v2.3 (currently with Etherpad v1.8.13).
