### ISSUE TITLE
Screen Sharing for Safari

### ISSUE THREAD

**Issue by iMonZ** [bigbluebutton/bigbluebutton#11132]
So currently BigBlueButton doesn't support Screen Sharing on Safari but since Safari 13 screen sharing is supported officially.

It would be great if BBB would add this feature cause im currently unable to use another browser.

**Comment by ffdixon** [comment]
Mobile Safari does not support screen sharing (iPad and iPhone), but the latest version of BigBlueButton (2.2.31) does support screen sharing on Safari running on MacOS.  I just tried it with 14.0.2 on https://test.bigbluebutton.org/ and was able to share my screen.

**Comment by iMonZ** [comment]
> Mobile Safari does not support screen sharing (iPad and iPhone), but the latest version of BigBlueButton (2.2.31) does support screen sharing on Safari running on MacOS. I just tried it with 14.0.2 on https://test.bigbluebutton.org/ and was able to share my screen.

Mobile Safari sadly doesn't support Screen sharing but the Desktop version does

**Comment by iMonZ** [comment]
> Mobile Safari does not support screen sharing (iPad and iPhone), but the latest version of BigBlueButton (2.2.31) does support screen sharing on Safari running on MacOS. I just tried it with 14.0.2 on https://test.bigbluebutton.org/ and was able to share my screen.

Thank you!
My own session just used an old version of BBB.

**Comment by iMonZ** [comment]
> Mobile Safari does not support screen sharing (iPad and iPhone), but the latest version of BigBlueButton (2.2.31) does support screen sharing on Safari running on MacOS. I just tried it with 14.0.2 on https://test.bigbluebutton.org/ and was able to share my screen.

@ffdixon 
Is it possible to add an option to select which screen is going to be shared?

**Comment by ffdixon** [comment]
Try Chrome and FireFox on macOS -- both give you that option.

**Comment by iMonZ** [comment]
> Try Chrome and FireFox on macOS -- both give you that option.

So its not an BBB problem?

**Comment by ffdixon** [comment]
> (and in the documentation of BBB there is a line where it describes that safari doesn't support this feature please fix this and add safari to the supported list)

Can you point out that line in the docs -- it should only refer to mobile Safari.

**Comment by iMonZ** [comment]
> > (and in the documentation of BBB there is a line where it describes that safari doesn't support this feature please fix this and add safari to the supported list)
> 
> Can you point out that line in the docs -- it should only refer to mobile Safari.

https://support.blindsidenetworks.com/hc/en-us/articles/360025284251-What-are-the-minimum-requirements-for-BigBlueButton-

First: `Desktop/Laptop: Chrome, Firefox or Edge (latest versions)
Mobile iOS (12.2+): Safari Mobile
Mobile Android (6.0+): Chrome Mobile`
Safari Browser is missing

Second:
`For browsers, we recommend Google Chrome, Mozilla FireFox or Microsoft Edge.  You can also use Safari on Mac OS X, but you will not be able to use the screen sharing feature .`
Safari is missing to and the last sentence is referring to the desktop version of safari

**Comment by iMonZ** [comment]
https://docs.bigbluebutton.org/support/faq.html#what-browsers-support-playback

`What browsers support playbackAnchor link for: what browsers support playback
BigBlueButton supports playback in Chrome and FireFox.

In BigBlueButton, the audio from a recorded session is encoded into Vorbis, an open source audio format that is not patent-encumbered. Playback of Vorbis audio is supported in FireFox and Chrome, but not IE and Safari.

BigBlueButton will playback the webcams from a session using the WebM container, which, thanks to Google, provides a high-quality open source video codec VP8. Playback of video in VP8 is supported by FireFox and Chrome, but not IE and Safari. See the HTML5 video Wikipedia article.`

my edit:
`What browsers support playbackAnchor link for: what browsers support playback
BigBlueButton supports playback in Google Chrome, Mozilla Firefox and on macOS Apple Safari.

In BigBlueButton, the audio from a recorded session is encoded into Vorbis, an open source audio format that is not patent-encumbered. Playback of Vorbis audio is supported in Mozilla Firefox, Google Chrome, on macOS Apple Safari, but not IE.

BigBlueButton will playback the webcams from a session using the WebM container, which, thanks to Google, provides a high-quality open source video codec VP8. Playback of video in VP8 is supported by Mozilla Firefox, Google Chrome, on macOS Apple Safari, but not IE. See the HTML5 video Wikipedia article.`

**Comment by iMonZ** [comment]
Don't forget to add the Safari browser in the Documentation :)

**Comment by prlanzarin** [comment]
> Is it possible to add an option to select which screen is going to be shared?
FYI: this is on webkit's/Apple side. They have to implement application/tab capture (nothing we can do). You can check their issue trackers to see what's the current state on those.

**Comment by iMonZ** [comment]
> > Is it possible to add an option to select which screen is going to be shared?
> 
> FYI: this is on webkit's/Apple side. They have to implement application/tab capture (nothing we can do). You can check their issue trackers to see what's the current state on those.

Thats fine but everything else is supported so the documentation can be updated!

**Comment by iMonZ** [comment]
> https://docs.bigbluebutton.org/support/faq.html#what-browsers-support-playback
> 
> ```
> What browsers support playbackAnchor link for: what browsers support playback
> BigBlueButton supports playback in Chrome and FireFox.
> 
> In BigBlueButton, the audio from a recorded session is encoded into Vorbis, an open source audio format that is not patent-encumbered. Playback of Vorbis audio is supported in FireFox and Chrome, but not IE and Safari.
> 
> BigBlueButton will playback the webcams from a session using the WebM container, which, thanks to Google, provides a high-quality open source video codec VP8. Playback of video in VP8 is supported by FireFox and Chrome, but not IE and Safari. See the HTML5 video Wikipedia article.
> ```
> 
> my edit:
> 
> ```
> What browsers support playbackAnchor link for: what browsers support playback
> BigBlueButton supports playback in Google Chrome, Mozilla Firefox and on macOS Apple Safari.
> 
> In BigBlueButton, the audio from a recorded session is encoded into Vorbis, an open source audio format that is not patent-encumbered. Playback of Vorbis audio is supported in Mozilla Firefox, Google Chrome, on macOS Apple Safari, but not IE.
> 
> BigBlueButton will playback the webcams from a session using the WebM container, which, thanks to Google, provides a high-quality open source video codec VP8. Playback of video in VP8 is supported by Mozilla Firefox, Google Chrome, on macOS Apple Safari, but not IE. See the HTML5 video Wikipedia article.
> ```
> 
> ```
> How do I get the best audioAnchor link for: how do i get the best audio
> Use FireFox or Chrome.
> 
> Both these browsers support web real-time communications (WebRTC) audio. BigBlueButton will use WebRTC for audio if the user is on FireFox or Chrome browser.
> ```
> 
> ```
> How do I get the best audioAnchor link for: how do i get the best audio
> Use Firefox, Chrome or on macOS Safari.
> 
> Both these browsers support web real-time communications (WebRTC) audio. BigBlueButton will use WebRTC for audio if the user is on Mozilla Firefox, Chrome browser or on macOS Apple Safari.
> ```

@ffdixon could you edit the wrong documentation?

**Comment by ffdixon** [comment]
Actually, you can't playback recordings on Safari Mobile on iOS without [enabling the creation of .h264 videos in recording processing](https://docs.bigbluebutton.org/2.2/customize.html#enable-playback-of-recordings-on-ios).  Updated the docs at https://docs.bigbluebutton.org/support/faq.html#what-browsers-support-playback to reflect this.

**Comment by maychine-fatima** [comment]
i.ve used the branch v.2.2.31 in my server but the screensharing is not working in safari ,i have read the code for the button of screenshare and i'veseen that the code is not updated since May in the component bigbluebutton/bigbluebutton-html5/imports/ui/components/actions-bar/desktop-share/component.jsx
![image](https://user-images.githubusercontent.com/33045799/107785664-25dbc000-6d4d-11eb-882e-eead00dedf92.png)

**Comment by prlanzarin** [comment]
If Safari is >= 13.1, it should work. Lower versions didn't support it.

**Comment by maychine-fatima** [comment]
thank you for your reply ,
i was debugging and i found that code that i shared is  for any safari browser it shows a modal screenshare unavailable

**Comment by prlanzarin** [comment]
> i was debugging and i found that code that i shared is for any safari browser it shows a modal screenshare unavailable

That code **is not** for **any** Safari version.
See: `if (IS_SAFARI && !ScreenshareBridgeService.hasDisplayMedia) {`
That means: if the browser **is safari** _and_ getDisplayMedia **is not** available, then display the unsupported modal.
getDisplayMedia was made officially available on Safari 13.1. Previous versions did not expose the method in all scenarios. So >= 13.1 should work.

**Comment by daminebenq** [comment]
confirming 
safari versions from 13.1 worked all successfully. and to sharescreen is really simple:
1) click on start share screen
2) click allow in the dialog popup that should appear

popup confirmation dialog:
![image](https://user-images.githubusercontent.com/5144311/107791196-65e17980-6d32-11eb-8198-db5fb7339cc1.png)

screenshare working:
![image](https://user-images.githubusercontent.com/5144311/107791369-9f19e980-6d32-11eb-92cb-b8f31f8e7d87.png)

Browser version used:
![image](https://user-images.githubusercontent.com/5144311/107791840-28c9b700-6d33-11eb-8396-eefe25f27cf2.png)

**Comment by daminebenq** [comment]
confirming 
safari versions from 13.1 worked all successfully. and to sharescreen is really simple:
1) click on start share screen
2) click allow in the dialog popup that should appear

popup confirmation dialog:
![image](https://user-images.githubusercontent.com/5144311/107792041-6f1f1600-6d33-11eb-846e-685d86f50912.png)

screenshare working:
![image](https://user-images.githubusercontent.com/5144311/107791369-9f19e980-6d32-11eb-92cb-b8f31f8e7d87.png)

Browser version used:
![image](https://user-images.githubusercontent.com/5144311/107791840-28c9b700-6d33-11eb-8396-eefe25f27cf2.png)
