### ISSUE TITLE
Change Listen-Only-Kurento process priority

### ISSUE THREAD

**Issue by basisbit** [bigbluebutton/bigbluebutton#11146]
**Describe the problem**
When a server is under high load, FreeSWITCH and NGINX will get most CPU time, and only little amount of CPU time is left for any of the Kurento processes. This is mostly very good, because that means that webcam sharing as well as screen sharing is "sacrificed" so that classes can still continue which is mostly okay for users. The only problem with this is that listen-only participants thus get really bad audio quality in such cases and listen-only Kurento fights against video handling Kurento processes and processing of session recordings for CPU time.

**To Reproduce**
1. Set up BBB
2. Make users somewhat overload the server, so that shared webcams get auto-disconnected
3. Join a session in listen-only audio
4. Listen to the stuttering audio

**Suggested improvement**
Change the three-split Kurento scripts so that the Kurento process for listen-only-audio gets higher priority (lower `nice`) than the other Kurento processes or the recording processes and so on.

**Comment by ffdixon** [comment]
We should be able to do this with a systemd override script for just the Listen Only Kurento server.

**Comment by ffdixon** [comment]
Closing this given the improvements with using Mediasoup in 2.4 (see [docs](https://docs.bigbluebutton.org/2.4/new.html#mediasoup)).
