### ISSUE TITLE
Presentation Button

### ISSUE THREAD

**Issue by stagestars** [bigbluebutton/bigbluebutton#11145]
**Describe the bug**
When presentations are turned off, the restore presentation button is still visible in the bottom right corner, and clicking it will make all the webcams very small, with no way to turn it back, as the presentations dont exist

**To Reproduce**
1. Disable presentation and enable auto layout. Click on presentation restore button

**Expected behavior**
Buttons should be there is presentation are disabled

**Actual behavior**
Buttons is there

**BBB version (optional):**
2.2 and 2.3-dev

**Comment by basisbit** [comment]
could you please add screenshots of the problem as well as  proper description for the `Actual behavior`? Thanks!
