### ISSUE TITLE
Some recording stay on process for a week .... after rebuild

### ISSUE THREAD

**Issue by farsad2020** [bigbluebutton/bigbluebutton#11147]
Hi
 after rebuildall record 
 some record donot publish and stay in /var/bigbluebutton/recording/process/presentation for a week
 when check list item  i get this
 
 bbb-rap-publish-worker.service - BigBlueButton recording and playback publish worker
   Loaded: loaded (/usr/lib/systemd/system/bbb-rap-publish-worker.service; static; vendor preset: enabled)
   Active: inactive (dead) since Wed 2021-01-06 03:19:18 UTC; 1 weeks 0 days ago
Condition: start condition failed at Wed 2021-01-13 06:32:13 UTC; 22s ago
           ConditionPathExistsGlob=/var/bigbluebutton/recording/status/processed/*.done was not met
 Main PID: 9977 (code=exited, status=0/SUCCESS)

 
![image](https://user-images.githubusercontent.com/66263484/104425450-f131e880-5595-11eb-9aca-02c257e9b57c.png)

how can solve it?!!

**Comment by basisbit** [comment]
For support requests, please use the [forum / mailing list](https://groups.google.com/forum/#!forum/bigbluebutton-setup). This issue tracker here is only for BBB development related issues. Sorry.
