### ISSUE TITLE
Screensharing/Webcam issue 1020 in Chrome behind Firewall. Works in Firefox at the same location on same client.

### ISSUE THREAD

**Issue by kolping-mw** [bigbluebutton/bigbluebutton#11149]
Since our upgrade from 2.2.29 to 2.2.31 we have problems in using the Screensharing/webcam behind our firewall with Chrome which we didn't have before. Before it worked in Firefox and Chrome with Audio and Screensharing/Webcam.
Our own Stun and Turn server is configured and working, Audio is working in Firefox and Chrome (via TURN). Screensharing/Webcam only working in Firefox.

Saw the change while updating in /etc/kurento/modules/kurento/WebRtcEndpoint.conf.ini and configured the file. ExternalIPv4 is set and my own stun server is set, connections are coming in to Stun. Seems to be fine.

As a test: on current test.bigbluebutton.org it is even worse. Audio 1007 and Webcam 1020 in Chrome and no Screensharing. Both working in Firefox and also Screensharing. Everything on the same client with the same network connection, only different browser.

What is the difference between Firefox and Chrome since the update? Should I use TURN instead of STUN for /etc/kurento/modules/kurento/WebRtcEndpoint.conf.ini because Chrome gets correct Audio via TURN?

Which information do you need to analyze further?

**Comment by kolping-mw** [comment]
Test from outside our firewall shows everything works like expected. So for me our configuration seems right because Firefox is working in both environments. Only Chrome doesn't.

**Comment by basisbit** [comment]
For support requests, please use the [forum / mailing list](https://groups.google.com/forum/#!forum/bigbluebutton-setup). This issue tracker here is only for BBB development related issues. Sorry.
