### ISSUE TITLE
add apple-touch-icon.png

### ISSUE THREAD

**Issue by fireba11** [bigbluebutton/bigbluebutton#11158]
**Describe the bug**
Logfile gets spammed by
/var/www/bigbluebutton-default/apple-touch-icon.png not found

**To Reproduce**
1. Join BBB with an apple touch device
2. check log

**Expected behavior**
Simply add the icon file the client tries to load so it doesn't bloat the logs :-)

**Comment by basisbit** [comment]
Not a bug in BBB. A `apple-touch-icon.png` icon is not part of any web-standard. Use log-rotate to get rid of messages from old log files.

**Comment by fireba11** [comment]
that apple behaviour is anoying as hell if you ever need anything from your logs.
i ended up adding an icon with my ansible-role for bbb for a more zen logfile ;-)

**Comment by basisbit** [comment]
I'd suggest instead doing
```
location =/apple-touch-icon-precomposed.png {
        return 444;
}
```

That will still do access logging for those who want / need it for whatever reason, reduces resource usage, will not log an error and is better than returning 404.
