### ISSUE TITLE
[BBB-2.3-alpha-4] Random downtime issue

### ISSUE THREAD

**Issue by skybox211** [bigbluebutton/bigbluebutton#11154]
This bug seems to occur randomly when the server is running. Mine was last restarted 2 days ago and today, it sometimes (for a duration of 15 ish minutes) decides to fail with an error in the greenlight logs

1. Create Server with greenlight instance on another server, with the bbb-install script and the customize greenlight instructions.
2. Wait
3. See error

**Expected behavior**
Work without downtime

**Actual behavior**
ERROR: [a72a4520-eed7-4484-8666-5a6ad7a026bb] BigBlueButtonException: Impossible to convert XML to hash. Error: Missing end tag for 'hr' (got 'body')
Line: 6
Position: 151
Last 80 unconsumed characters:

This error was supposed to be related to SSL, but seems to fix itself after some time which means this is probably not the same error as other issues, and specific to 2.3-alpha-4

 - OS: Windows and Android
 - Browser: Affects all

**Comment by skybox211** [comment]
Please let me know if more logs are needed

**Comment by hmt** [comment]
There is an issue over at the greenlight repo with the exact same problem.
