### ISSUE TITLE
[privacy] Option to anonymize participants in recording

### ISSUE THREAD

**Issue by jgrewe** [bigbluebutton/bigbluebutton#11156]
Dear all, we use a bbb server for the digital lectures this and probably also in the coming terms. Generally we are really happy with it but students raised concerns about recording sessions. 
On the one hand they value the option to use the recordings for later recap but on the other hand do not feel comfortable with being recognizable in the recordings. This relates to the webcam recordings as well as the public chat (where most use real names). They do feel exposed to anyone who has the room's link. While the link is only shared among the participants and we do not reuse the recordings in any other context, this makes them feeling awkward about actually contributing to the lecture and asking questions.

I tried to find something in the docs about not including the webcam recordings of participants in the recording but could not find it. If there is such an option I would be happy for a hint. 
Otherwise, a possible solution could be to add a config flag about anonymizing (blurring the faces and names) or non-presenting participants.

Thanks

**Comment by ffdixon** [comment]
This is a good suggestion.  The removal of webcams via a settings is something we can look at in 2.3-dev.  

The anonymizing of user names is a bit more tricky as we would need change their references (through a string match) as well in the body of the chat text.  This would not be 100% as there would be cases where another user misspells a name in the chat, or shortens the name, so the matching in these cases would not work.

**Comment by jgrewe** [comment]
Thank you @ffdixon, this would be most appreciated. On second thought: instead of blurring webcam recordings replacing them with a dummy still might be a much easier approach

**Comment by greatfireball** [comment]
Besides chat with clear names and a video stream, they might be identified by their voice due to it is included in the audio stream. During my lectures, I am pausing the recording and ask for questions. If their are any questions, I restart the recording, repeat the question and hopefully answer that question.

**Comment by pedrobmarin** [comment]
https://docs.bigbluebutton.org/2.2/customize.html#kurento-parameters `userdata-bbb_record_video` can be used to avoid recording an user webcam

**Comment by jgrewe** [comment]
@pedrobmarin thank you. Can you tell me into which settings file this goes? From the docs I understand it should go into /usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml in which I find a *kurento* section but I does not really fit in (different property name style)

**Comment by pedrobmarin** [comment]
@jgrewe it doesn't go on any settings file. It's a parameter you add to the join API call for the users you want the webcam disabled. Not sure what you have running in front of bigbluebutton but if changing the API call could get a little complicated there is also an option to disable all videos' recording at the WebRTC SFU application

**Comment by jgrewe** [comment]
@pedrobmarin sorry for asking stupid questions but I guess I need some more guidance. 
I am running greenlight as frontend mostly with default settings. If I understand you correctly, I would need to change the respective call in one of the greenlight ruby files and divert from upstream.  
For the second option I  need to change the settings of WebRTC globally which would be just fine for me. Question is where.
Thanks in advance.

**Comment by pedrobmarin** [comment]
No need to apologize.
It might get hard to maintain a custom Greenlight deploy. As far as I know there is no easy way to add and remove URL parameters from there unless you touch the code.
To globally disable the webcams recording you can check for https://github.com/bigbluebutton/bbb-webrtc-sfu/blob/a73429ebb82827a6be9cfae7b22f154a47d4dcf4/config/default.example.yml#L56 at `/usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml`. You will need to restart the service after that for the changes to be applied `sudo systemctl restart bbb-webrtc-sfu`

**Comment by jgrewe** [comment]
Thank you that worked nicely. As I see it, bbb itself offers the option of control recording of webcams even on a user  level (https://github.com/bigbluebutton/bigbluebutton/pull/10304) so it is a matter of the frontend (greenlight etc.) to expose that feature, correct?
