### ISSUE TITLE
Echo test timeout on Ipad

### ISSUE THREAD

**Issue by jankrieg** [bigbluebutton/bigbluebutton#11155]
**Describe the bug**
Started BBB on iPad -> Asked whether to allow use of microphone -> Confirmed that -> Timeout

Started BBB on Windows or Linux -> Asked whether to allow use of microphone -> Works
 

**To Reproduce**

**Expected behavior**

**Actual behavior**

**Screenshots**

**BBB version (optional):**
BigBlueButton continually evolves. Providing the version/build helps us to pinpoint when an issue was introduced.
Example:
$ sudo bbb-conf --check | grep BigBlueButton
BigBlueButton Server 2.2.2 (1816)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, Mac]
 - Browser [e.g. Chrome, Safari]

**Smartphone (please complete the following information):**
 - Browser [e.g. stock browser, Safari]

**Additional context**

**Comment by jankrieg** [comment]
Forgot to mention: Server version 2.3.4

**Comment by basisbit** [comment]
For support requests, please use the [forum / mailing list](https://groups.google.com/forum/#!forum/bigbluebutton-setup). This issue tracker here is only for BBB development related issues. Sorry.
