### ISSUE TITLE
cleanup of presentation files

### ISSUE THREAD

**Issue by fireba11** [bigbluebutton/bigbluebutton#11159]
**Describe the bug**
/var/bigbluebutton/
contains one folder per meeting with the presentation (most of the time only a copy of the default presentation)
I've got folders that are several days old, how is the cleanup supposed to work?

Those files could contain sensitive data so cleanup is important ;-)

**Possible improvement**
* find a way not to make a gazillion copies of the default presentation
* clean up the presentation after the meeting has ended

**Additional context**
bbb 2.2.31 with greenlight 2.7.14

**Comment by basisbit** [comment]
Please read https://docs.bigbluebutton.org/admin/privacy.html for how to implement data privacy related topics as needed by your use case.

**Comment by fireba11** [comment]
@basisbit that link contains just an open todo about presentations?
