### ISSUE TITLE
BBB 2.3.0-alpha4-build-1312 on CT OpenVZ Virtuozzo 7 with docker

### ISSUE THREAD

**Issue by aguerson** [bigbluebutton/bigbluebutton#11157]
Hi BBB Devs,

Just a short feedback.
I installed BBB 2.3.0-alpha4-build-1312 on a CT OpenVZ Virtuozzo 7 with docker, and it works.
I didn't use bbb install.sh but directly yours repos
I followed the BBB 2.2 installation steps ( modifying the version of mongodb )
I disabled the CPU priorities in .service files ( because it doesn't work with OVZ CT )
I modified my custom script  like apply-lib.sh and apply-conf.sh ( because you deleted of the conf related to flash )

It works well for now.

Next step, update/install coturn on ubuntu 20.04 lts, due to security alert.

Test with bbb bots

And the best for the end, try a apt-get update/upgrade of all with docker :D

Regards,
Aurélien.

**Comment by basisbit** [comment]
Thank you for the update! Could you please post this message in the bigbluebutton-dev mailing list or does there exist a BBB -> Docker issue? This issue tracker here is mostly for tracking bugs or issues, but not for in-development status updates.

**Comment by basisbit** [comment]
On a side note, instead of disabling CPU priorities, please instead change the CPU priorities so that they only use non-realtime scheduling. The process priorities are very important to keep BBB working during higher load situations.
