### ISSUE TITLE
Feature Request: video picking

### ISSUE THREAD

**Issue by apinos76** [bigbluebutton/bigbluebutton#11150]
**Is your feature request related to a problem? Please describe.**
The following is from Zendesk ticket number 10261

> My manager would like to be able to click on a name during a video conferencing and only see the image (video) of the user the name was clicked on. Since currently, even if you see all the users, the system picks the images to display (not sure what the criteria is) and not all the users are displayed, especially if you are projecting a presentation.

**Describe the solution you'd like**
Moderator chooses a user from the user list and the users webcam is highlighted among all the webcam streams (or set focus on the user is enabled) 

**Describe alternatives you've considered**
Not to add this feature

**Additional context**
This stems from a discussion with the Product Manager and the customer in ticket 10261

**Comment by prlanzarin** [comment]
Please confirm whether https://github.com/bigbluebutton/bigbluebutton/issues/13702 contemplates this.
