### ISSUE TITLE
Closed Captions available languages drop down showing empty in 2.3

### ISSUE THREAD

**Issue by daminebenq** [bigbluebutton/bigbluebutton#11162]
This is only a 2.3 bug currently happening in develop branch.

To reproduce it:
1) update to develop branch
2) connect to the server address and create a meeting
3) connect to the meeting
4) click on userslist option > click Write closed captions

Expected successful behavior:
- Closed Captions Modal should appear with a drop down list showing available CC languages.

Reprodution behavior: 
- The CC modal is showing an empty drop down.

![CC drop down empty](https://user-images.githubusercontent.com/5144311/104776256-8f6dac00-5758-11eb-9118-678b8467e35a.gif)

**Comment by hiroshisuga** [comment]
#11116

**Comment by daminebenq** [comment]
@hiroshisuga 
Thanks for the comment. I didn't know that there is already an open issue about it. But good you mentionned. Closing this one. duplicate of #11116.
