### ISSUE TITLE
BBB 2.3-Alpha4 - No video (webcam, screensharing)

### ISSUE THREAD

**Issue by AK1912** [bigbluebutton/bigbluebutton#11166]
**Describe the bug**
I need to move our working 2.2 BBB to a new server because of power issues. Our provider doesn't offer ubuntu 16.04 installation anymore. I need to go with 18.04 and so bbb 2.3. Unfortunately i have issues with sending video. 

**To Reproduce**
When starting webcam the window for choosing the quality appears and after accepting the black window with my name appears and nothing happens else.
When sharing a screen nothing happens. I get no errors.

```
BigBlueButton Server 2.3.0-alpha4 (1476)
                    Kernel version: 4.15.0-132-generic
                      Distribution: Ubuntu 18.04.5 LTS (64-bit)
                            Memory: 32811 MB
                         CPU cores: 8

/usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties (bbb-web)
       bigbluebutton.web.serverURL: http://bbb.XXX.de
                defaultGuestPolicy: ALWAYS_ACCEPT
                 svgImagesRequired: true

/etc/nginx/sites-available/bigbluebutton (nginx)
                       server_name: bbb.XXX.de
                              port: 80, [::]:80
                              port: 443 ssl

/opt/freeswitch/etc/freeswitch/vars.xml (FreeSWITCH)
                       local_ip_v4: 62.138.xxx.xxx
                   external_rtp_ip: 62.138.xxx.xxx
                   external_sip_ip: 62.138.xxx.xxx

/opt/freeswitch/etc/freeswitch/sip_profiles/external.xml (FreeSWITCH)
                        ext-rtp-ip: $${local_ip_v4}
                        ext-sip-ip: $${local_ip_v4}
                        ws-binding: :5066
                       wss-binding: :7443

/usr/local/bigbluebutton/core/scripts/bigbluebutton.yml (record and playback)
                     playback_host: bbb.XXX.de
                 playback_protocol: http
                            ffmpeg: 4.2.4-1ubuntu0.1bbb2~18.04

/etc/bigbluebutton/nginx/sip.nginx (sip.nginx)
                        proxy_pass: 62.138.xxx.xxx
                          protocol: https

/usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml (Kurento SFU)
                        kurento.ip: 62.138.xxx.xxx
                       kurento.url: ws://127.0.0.1:8888/kurento
                    kurento.sip_ip: 62.138.xxx.xxx
                    localIpAddress: 62.138.xxx.xxx
               recordScreenSharing: true
                     recordWebcams: true
                  codec_video_main: VP8
               codec_video_content: VP8

/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml (HTML5 client)
                             build: 1312
                        kurentoUrl: ws://bbb.XXX.de/bbb-webrtc-sfu
                  enableListenOnly: true
                    sipjsHackViaWs: false

/usr/share/bbb-web/WEB-INF/classes/spring/turn-stun-servers.xml (STUN Server)
                              stun:stun.l.google.com:19302


# Potential problems described below
```

- Jan 16 22:16:59 astra5203 bbb-webrtc-sfu[5018]: 2021-01-16T21:16:59.031Z - info: [RedisWrapper] Started Redis client at 127.0.0.1:6379 for subscription pattern: from-akka-apps-redis-channel
- Jan 16 22:16:59 astra5203 bbb-webrtc-sfu[5018]: 2021-01-16T21:16:59.032Z - info: [BigBlueButtonGW] Added redis client to this.subscribers[from-akka-apps-redis-channel]
- Jan 16 22:16:59 astra5203 bbb-webrtc-sfu[5018]: 2021-01-16T21:16:59.032Z - info: [sfu-mcs-api] Connecting to MCS at ws://localhost:3010/mcs
- Jan 16 22:16:59 astra5203 bbb-webrtc-sfu[5018]: 2021-01-16T21:16:59.038Z - error: [sfu-mcs-api] SFU socket connection to mcs-core failed due to connect ECONNREFUSED 127.0.0.1:3010 message=connect ECONNREFUSED 127.0.0.1:3010, code=undefined
- Jan 16 22:16:59 astra5203 bbb-webrtc-sfu[5018]: 2021-01-16T21:16:59.039Z - error: [sfu-mcs-api] SFU socket connection to mcs-core closed unexpectedly
- Jan 16 22:16:59 astra5203 bbb-webrtc-sfu[5018]: 2021-01-16T21:16:59.041Z - info: [RedisWrapper] Successfully subscribed to pattern [to-video-sfu]
- Jan 16 22:16:59 astra5203 bbb-webrtc-sfu[5018]: 2021-01-16T21:16:59.042Z - info: [RedisWrapper] Successfully subscribed to pattern [from-akka-apps-redis-channel]
- Jan 16 22:16:59 astra5203 bbb-webrtc-sfu[5018]: 2021-01-16T21:16:59.042Z - error: [sfu-mcs-api] SFU socket connection to mcs-core failed due to connect ECONNREFUSED 127.0.0.1:3010 message=connect ECONNREFUSED 127.0.0.1:3010, code=undefined
- Jan 16 22:16:59 astra5203 bbb-webrtc-sfu[5018]: 2021-01-16T21:16:59.043Z - error: [sfu-mcs-api] SFU socket connection to mcs-core closed unexpectedly
- Jan 16 22:16:59 astra5203 bbb-webrtc-sfu[5018]: 2021-01-16T21:16:59.045Z - info: [RedisWrapper] Successfully subscribed to pattern [to-screenshare-sfu]
- Jan 16 22:16:59 astra5203 bbb-webrtc-sfu[5018]: 2021-01-16T21:16:59.045Z - info: [RedisWrapper] Successfully subscribed to pattern [bigbluebutton:from-bbb-transcode:system]
- Jan 16 22:16:59 astra5203 bbb-webrtc-sfu[5018]: 2021-01-16T21:16:59.045Z - info: [RedisWrapper] Successfully subscribed to pattern [from-akka-apps-redis-channel]
- Jan 16 22:16:59 astra5203 bbb-webrtc-sfu[5018]: 2021-01-16T21:16:59.055Z - info: [mcs-adapter-factory] Configured media server adapters: 0=Kurento, 1=Freeswitch
- Jan 16 22:16:59 astra5203 bbb-webrtc-sfu[5018]: 2021-01-16T21:16:59.081Z - info: [mcs-strategy-manager] Strategy manager started.
- Jan 16 22:16:59 astra5203 bbb-webrtc-sfu[5018]: 2021-01-16T21:16:59.084Z - info: [app] MCS Server is ready to receive connections
- Jan 16 22:16:59 astra5203 bbb-webrtc-sfu[5018]: 2021-01-16T21:16:59.092Z - info: [mcs-freeswitch-esl-wrapper] Connected to FreeSWITCH ESL
- Jan 16 22:16:59 astra5203 bbb-webrtc-sfu[5018]: 2021-01-16T21:16:59.095Z - info: [mcs-balancer] New media server host added hostId=silent-silence-Fgo1MBU, url=ws://127.0.0.1:8888/kurento, ip=62.138.xxx.xxx, mediaType=all
- Jan 16 22:17:01 astra5203 bbb-webrtc-sfu[5018]: 2021-01-16T21:17:01.020Z - info: [sfu-mcs-api] Trying to reconnect to MCS at ws://localhost:3010/mcs
- Jan 16 22:17:01 astra5203 bbb-webrtc-sfu[5018]: 2021-01-16T21:17:01.024Z - info: [sfu-mcs-api] Connected to MCS
- Jan 16 22:17:01 astra5203 bbb-webrtc-sfu[5018]: 2021-01-16T21:17:01.040Z - info: [sfu-mcs-api] Trying to reconnect to MCS at ws://localhost:3010/mcs
- Jan 16 22:17:01 astra5203 bbb-webrtc-sfu[5018]: 2021-01-16T21:17:01.044Z - info: [sfu-mcs-api] Trying to reconnect to MCS at ws://localhost:3010/mcs
- Jan 16 22:17:01 astra5203 bbb-webrtc-sfu[5018]: 2021-01-16T21:17:01.045Z - info: [sfu-mcs-api] Connected to MCS
- Jan 16 22:17:01 astra5203 bbb-webrtc-sfu[5018]: 2021-01-16T21:17:01.049Z - info: [sfu-mcs-api] Connected to MCS
- Jan 16 22:17:34 astra5203 bbb-webrtc-sfu[5018]: 2021-01-16T21:17:34.647Z - info: [mcs-freeswitch] Dispatching conference new video floor event released for room 39516 roomId=39516
- Jan 16 22:17:34 astra5203 bbb-webrtc-sfu[5018]: 2021-01-16T21:17:34.649Z - error: [mcs-controller] releaseConferenceFloor for room 39516 failed due to ROOM_NOT_FOUND roomId=39516, code=2101, message=ROOM_NOT_FOUND
- Jan 16 22:17:34 astra5203 bbb-webrtc-sfu[5018]: 2021-01-16T21:17:34.650Z - error: [mcs-controller] Error releasing conference floor at 39516 errorMessage=ROOM_NOT_FOUND, errorCode=2101

**Comment by AK1912** [comment]
I solved the issue:

> Open /usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml editing and change:
> 
>   kurento:
>     wsUrl: ws://bbb.example.com/bbb-webrtc-sfu
> to
> 
>   kurento:
>     wsUrl: wss://bbb.example.com/bbb-webrtc-sfu

**Comment by rasos** [comment]
Behaviour not reproducible here. wss was standard in our installation.

**Comment by prlanzarin** [comment]
Setup shenanigans, so not an issue.
1 - Always review the SSL steps in the docs
2 - Always be sure to run setip on updates
3 - If this was via bbb-install, try to reproduce in a fresh installation and open an issue in that repo (github.com/bigbluebutton/bbb-install)
