### ISSUE TITLE
Disable generation of user typing notifications when feature is disabled

### ISSUE THREAD

**Issue by NerdyProjects** [bigbluebutton/bigbluebutton#11161]
HTML5 client generates an API event for each keypress inside the chat message window. When the typing notifications feature is disabled, (`settings.yml`: `chat.typingIndicator.enabled: false`, this disables just the rendering of the typing indicators, but still generates the requests in the client as well as multiplexes them in the server.

On our production setup, in a high-load scenario about half of the API traffic are typing events. I did not manage to profile the application yet but I would hope for a performance increase by disabling the typing notification event generation and forward, for example by making `startUserTyping` and `stopUserTyping` a noop in `chat/message-form/container.jsx`.

I confirmed this in a 2.2.31 production setup and quickly checked `develop` to confirm it's still the case.

**Comment by ffdixon** [comment]
>  I did not manage to profile the application yet but I would hope for a performance increase by disabling the typing notification event generation and forward, for example by making startUserTyping and stopUserTyping a noop in chat/message-form/container.jsx.

Interesting -- we would be interested to hear the performance difference between disabling the event notifications on the server.
