### ISSUE TITLE
Multiuser whiteboard cursor position update overloads server

### ISSUE THREAD

**Issue by basisbit** [bigbluebutton/bigbluebutton#11169]
**Describe the bug**
Roughly once every 1/30 second, the user's mouse cursor position gets processed by the whiteboard handling code.
[Up to every 1/15th second](https://github.com/bigbluebutton/bigbluebutton/blob/v2.2.x-release/bigbluebutton-html5/imports/api/annotations/server/handlers/whiteboardSend.js#L8), an update of the cursor position is sent to the server over the websocket port, where it then gets processed by the single-threaded NodeJS/Meteor app, which uses expensive events to publish position updates to the various clients.

This works okay under light server load with few users, but if you have for example two classes of 30 students moving their mouse cursors over the whiteboard surface and both classes have multiuser whiteboard enabled and then the students draw stuff, well, that is a whopping 1000 updates per second hitting the NodeJS process over the websocket connections. Each of those messages gets a response from the server, and then the updates also get aggregated (I hope so) and then pushed to the 60 clients again using the websocket connections.

**Expected behavior**
Multiuser-whiteboard updates should be sent much less frequently, or the frequency should depend on NodeJS process load. Maybe the NodeJS server could add a rate-limit number as part of the websocket message response, s the client know how long to wait at least before sending the next whiteboard update?

**Actual behavior**
On a typical decent BBB server under load with 450 connected users, everything works well, until a few classes decide to use the multiuser-whiteboard, and suddenly the server is not usable any more, clients drop out after 15 or 30 seconds and you just made 450 people not like BigBlueButton any more.

**Screenshots**
![image](https://user-images.githubusercontent.com/10870269/104832854-a1546980-5894-11eb-9ee6-4598a2034763.png)
![image](https://user-images.githubusercontent.com/10870269/104832880-e8425f00-5894-11eb-9632-ce86277375c5.png)

**BBB version (optional):**
BigBlueButton Server 2.2.31

**Comment by basisbit** [comment]
fyi @jfsiebel

**Comment by basisbit** [comment]
Alternatively, just changing the position update interval for the multiuser whiteboard might be a good compromise.

**Comment by Jossef-767** [comment]
This is a critical issue for me too, will be very helpful to have an option for admin to disable Multi User whiteboard for a specific room, manually, or automatically after N number of users in a room. 
Also if #10283 will be Merged, it can replace this option and allow only individual access to the whiteboard.

**Comment by basisbit** [comment]
individual whiteboard access won't solve the issue because just opening multiuser whiteboard for the whole class will still be the most common (because easy to use) use-case.

**Comment by basisbit** [comment]
For our own setup, we ended up changing the client code so that it only sends mouse move updates every 150ms which is okay for our use cases. Drawing events are not affected by this.

The value changed was https://github.com/bigbluebutton/bigbluebutton/blob/v2.2.x-release/bigbluebutton-html5/imports/ui/components/whiteboard/whiteboard-overlay/cursor-listener/component.jsx#L7

**Comment by ffdixon** [comment]
@basisbit, thanks for sharing this.  We'll look at making this a parameter in `settings.yaml` so it's easier for others to adjust this value.

**Comment by pedrobmarin** [comment]
@basisbit was https://github.com/bigbluebutton/bigbluebutton/pull/11187 sufficient to cover this?

**Comment by basisbit** [comment]
Yes. For any further improvement of this, there exists #11342
Thank you for so quickly adopting the fix!
