### ISSUE TITLE
using kurento instead of freeswitch

### ISSUE THREAD

**Issue by burakguder** [bigbluebutton/bigbluebutton#11168]
Hello there

Problem
freeswitch does not support SFU. the audio mixing feature causes a lot of noise. When 3 people speak, nothing is understood and the voices are cut off.

I see the kurento code for the audio module in the directory below, but I couldn't find how to enable the kurento server use for audio.
https://github.com/bigbluebutton/bigbluebutton/tree/develop/bigbluebutton-html5/imports/api/audio/client/bridge

I think a quality close to Zoom will be achieved with SFU audio transmission.

**Comment by basisbit** [comment]
please see https://github.com/bigbluebutton/bigbluebutton.github.io/pull/212/files for how to adjust audio quality settings as needed for your setup.

Kurento is notoriously slow for mixing individual audio streams for users, thus freeswitch is used for that. This has nothing to do with MCU or SFU. Switching this to SFU would result in much more load on the client side, and the results can be seen in the performance problems of Jitsi.

For any further similar discussion please use the bigbluebutton-dev mailing list.
