### ISSUE TITLE
Reset all statuses 

### ISSUE THREAD

**Issue by Xrasure** [bigbluebutton/bigbluebutton#11174]
It would be very useful for the meeting host (for example the teacher) to be able to reset the status of all users. 

The problem : When you get asked in a business meeting or in online class and you raise your hand, you will likely forget resetting your status after the question and the teacher/ host will think that you are still raising your hand when you don't

The solution: A button for the host/teacher to reset the status of all members in a meeting when the question is answered

**Comment by simonschweizer** [comment]
You can already do that (if you are moderator):

![image](https://user-images.githubusercontent.com/5512013/105019051-f4b9e980-5a45-11eb-9d44-7a941ce618b4.png)
