### ISSUE TITLE
No audio with Chromium 

### ISSUE THREAD

**Issue by ArminXG** [bigbluebutton/bigbluebutton#11172]
**Describe the bug**
When using BigBlueButton 2.2.31 with Chromium, audio is not possible. A popup tells:
_There was an issue with your media devices
Did you give permission for access to your microphone? Note that a dialog should appear when you try to join audio, asking for your media device permissions, please accept that in order to join the audio conference. If that is not the case, try changing your microphone permissions in your browser's settings._

**To Reproduce**
1. BigBlueButton 2.2.31 or  https://test.bigbluebutton.org/
2. Chromium 87.0.4280.88 (Linux Mint 20)
3. Start room and join audio.

**Expected behavior**
The permissions for microphone are given. It works with BigBlueButton 2.2.29.

**Actual behavior**
No audio possible because of this error message.

Maybe this is related to #11139

**Comment by basisbit** [comment]
For support requests, please use the [forum / mailing list](https://groups.google.com/forum/#!forum/bigbluebutton-users). This issue tracker here is only for BBB development related issues. Sorry.

**Comment by ArminXG** [comment]
Well, this is not a support request. It is an issue with latest version of BBB. 2.2.29 works, 2.2.31 does not.

**Comment by prlanzarin** [comment]
I just tried the steps you mentioned in a fresh, right out of the box Chromium installation (87.0.4280.88, Mint 20) at test.bigbluebutton.org and could not reproduce the issue.

You might be missing some detail on your environment. Extensions, previously denied microphone permissions, ...?

**Comment by ArminXG** [comment]
I works now, but I cannot tell the cause. 
The problem did not occur with our production BBB 2.2.29, all was still fine here. The new test instance with BBB 2.2.31 and test.bigbluebutton.org showed the problem with different browsers.
After cleanup of all my profiles on local machine it works. But why did it work with BBB 2.2.29?
Anyway, case closed. Thank you for taking care.
