### ISSUE TITLE
users list improvement

### ISSUE THREAD

**Issue by Braehler** [bigbluebutton/bigbluebutton#11176]
**Is your feature request related to a problem? Please describe.**
Its currently possible to save a list of current users in the meeting. But the moderator has to do this on his own

**Describe the solution you'd like**
It would be great if this could be done via an atomatic process. Lets say: 10 minutes after the meeting started a list is generated. 
Or the moderator clicks on safe list, and the list will be send via email. And an output as xls or xml would be great

**Describe alternatives you've considered**
Right now the moederator saves the list on his computer and then sends it either to the office via email, or in a third party sofware, where the users presence is noticed

**Additional context**

**Comment by basisbit** [comment]
This can already be implemented by a third party using the [getMeetingInfo API](https://docs.bigbluebutton.org/dev/api.html#getmeetinginfo). To avoid feature creep, I'd suggest not adding this to BigBlueButton itself, but instead implementing this in the tool where you integrated BigBlueButton. Tha is usually also the place where you can actually make use of the information and for example mark a student as having attended the session.

**Comment by Braehler** [comment]
@basisbit 
ok, I just read through this, but to be honest, I do not exactely know how to do this. Any further docs or examples of how to implement this?

**Comment by pedrobmarin** [comment]
I believe the best (available) choice for something like this would be using https://github.com/bigbluebutton/bbb-events or a similar thing at one of the record `post_[something]` steps. You can find further documentation here https://docs.bigbluebutton.org/dev/recording.html
