### ISSUE TITLE
Send a chat (announcement) to all breakouts (simultaneously)

### ISSUE THREAD

**Issue by dfasani** [bigbluebutton/bigbluebutton#11189]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I need to chat to each of the 20 breakout rooms I use in my course.

**Describe the solution you'd like**
A feature that would allow the moderator/presenter to push a chat message in every single breakout room.

**Describe alternatives you've considered**
n/a

**Additional context**
A large number of breakout rooms

**Comment by rasos** [comment]
We are investigating options to enhance or replace the chat framework. Your requirement has been noted https://git.fairkom.net/chat/bbbsecurechat/-/issues/9

**Comment by ffdixon** [comment]
@rasos Would be interested in your thoughts on a user experience for implementing the ability for a moderator to broadcast a message to all breakout rooms.

**Comment by amadsalmon** [comment]
My team and I are going to start working on such a feature for a university project which will hopefully end in a successful pull request. Where would you recommend we start? @rasos @ffdixon

**Comment by antobinary** [comment]
Including the latest state of designs from @tylercopeland 

The location of the countdown and the end control are located in different area compared to BBB 2.4.0. I will have to follow up with @tylercopeland to confirm if this relocation is within scope.
![Screenshot from 2022-01-13 15-42-31](https://user-images.githubusercontent.com/6312397/149406328-626ef5e9-b9b3-4656-8557-2653b599d761.png)


![Screenshot from 2022-01-13 15-42-51](https://user-images.githubusercontent.com/6312397/149406348-ef6afd26-d4ae-4257-9520-1c0f145e41a4.png)


![Screenshot from 2022-01-13 15-43-01](https://user-images.githubusercontent.com/6312397/149406357-72e164b5-9c82-46f8-b1b6-7239ff9db200.png)


Here we see a slightly different style compared to the bolded moderator text in BBB 2.4.0. Let's leave the styling change for another iteration. As part of this issue please implement the announcement delivery as a public chat.
![Screenshot from 2022-01-13 15-43-14](https://user-images.githubusercontent.com/6312397/149406367-a1f93d8d-7d16-409e-b268-d5c3e21e906b.png)

**Comment by gustavotrott** [comment]
Hey @antobinary,
The requested success notification was:
![image](https://user-images.githubusercontent.com/5660191/151547996-4975a277-4b99-48df-bf94-920c17cf58a3.png)

But, considering the use case with several breakout rooms. I think we can change the message for:
![msg_sent_breakouts](https://user-images.githubusercontent.com/5660191/151548213-52e55a55-dc04-4dc0-89ed-ed234a3fd71d.png)

**Comment by antobinary** [comment]
Agreed, @gustavotrott !
We can do a round of adjustments with @tylercopeland 's feedback once this is merged
