### ISSUE TITLE
Webcam resolution is always set back to 640x480 (Linux)

### ISSUE THREAD

**Issue by bschatz** [bigbluebutton/bigbluebutton#11180]
**Describe the bug**
BBB sets the resolution of my webcam always back to 640x480

**To Reproduce**
1. set resolution of webcam e.g.:

```bash
v4l2-ctl --set-fmt-video=width=320,height=240,pixelformat=YUYV
v4l2-ctl --get-fmt-video
Format Video Capture:
	Width/Height      : 320/240
	Pixel Format      : 'YUYV' (YUYV 4:2:2)
```

2.Klick on ,,Share Webcam''' (do not klick on ,,Start Sharing''')

Now the resolution of the webcam is (always) changed  to 640x480

```bash
$ v4l2-ctl --get-fmt-video
Format Video Capture:
	Width/Height      : 640/480
	Pixel Format      : 'YUYV' (YUYV 4:2:2)
```

**Expected behavior**
Don't change the resolution.

**Actual behavior**
The resolution is always set back to 640x480
(My webcam can higher and lower resolutions, dont know why it is set to 640x480)

**Screenshots**
---

**BBB version (optional):**
Copyright: ©2020 BigBlueButton Inc., Client build: 1114

**Comment by prlanzarin** [comment]
I'm closing this as duplicate (and non issue).
I'll also link the first 3 issues that popped up in a search that are about pretty much the same thing. There's info on them about how you can adjust camera profiles via constraints. Hope that helps.

https://github.com/bigbluebutton/bigbluebutton/issues/9509
https://github.com/bigbluebutton/bigbluebutton/issues/9463
https://github.com/bigbluebutton/bigbluebutton/issues/8435
