### ISSUE TITLE
White screen when watching video in full screen

### ISSUE THREAD

**Issue by anik3t** [bigbluebutton/bigbluebutton#11192]
**Describe the bug**
When watching the video in the full screen, the video disappears & white screen appears, while we can only hear the audio.

**Expected behavior**
Video should play in fullscreen as it is in the regular mode of screen. 

**Actual behavior**
Video plays fine in the normal mode, but when we go to full screen mode, we cannot see the video(picture) & can hear audio. Screen goes complete white in full screen mode. When we come back to regular mode from full screen mode, it plays fine.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [ubuntu based linux]
 - Browser [Chrome, firefox ]
 - Version [e.g. v 87.0.4280.88 chrome]

**Comment by prlanzarin** [comment]
BBB version? Also, you labelled it as recording. Not clear whether you're talking about the recording playback or the HTML5 client, though. Both have full screen thingies for video.

**Comment by anik3t** [comment]
Right now, I have just observed the recorded session, Screenshot attached
![Screenshot from 2021-01-21 01-25-10](https://user-images.githubusercontent.com/27769614/105227925-e83daa00-5b87-11eb-9b62-199b65decec6.png)

I will confirm about the live session in a day or two.
About the version, I cannot confirm now, however it is built from the recent version. I will take this detail & share it in a day

**Comment by basisbit** [comment]
This is most likely a browser / OS issue. Please try using another webbrowser.

**Comment by anik3t** [comment]
We tried it in firefox and chrome. Also used the recorded session on different desktops and mobile, but still the issue persist with full screen mode

**Comment by anik3t** [comment]
we see download option in full screen mode, when we download the webm format video, we can see this white screen with audio & no picture.
I see a option on BBB bottom bar where we have "Toggle video and presentation swap" Button, when we press on it, I see this white screen in enlarged view. 
Actually we had a recorded session by screen sharing & it didn't have any presentation in it.
So is it showing only presentation blank screen with video audio in full screen & when we come to normal view, it shows video & presentation screen both, where video is taking max screen space

**Comment by daminebenq** [comment]
Hi @anik3t
I would like to reproduce this issue, so can you please describe the steps to reproduce it ?

**Comment by anik3t** [comment]
@daminebenq @prlanzarin 
I have recorded the video on moodle platform,
Steps:-
Start the video
Share your screen on the video
Make sure you are keeping your camera ON
Start the recording


After recording it for sometime, play the recorded video
open the recorded video, enter into the fullscreen mode.
You will see that you can't see the screen shared by the presenter & you can only see the presenter on the camera. 

Issue: Here in fullscreen mode of recorded video, we see the background as shown in the above attached image & on top of it, we see a small screen of presenter from the camera (picture in picture mode)

Fix suggested: When host shares his screen, it should be shown in the full screen mode also

**Comment by basisbit** [comment]
Which button exactly do you press to open fullscreen view (there are different buttons for webcam video in fullscreen or whole oage in fullscreen or presentation/whiteboard surface in fullscreen)? Do you see the video if you press F11 key to view the page in fullscreen mode instead?

**Comment by prlanzarin** [comment]
> it is built from the recent version.

There's really one question I asked and it's unanswered: what BBB version are you using? That does not answer it. More recent what? 2.2 or 2.3?

It's important that you explain which is the exact version because 2.2 and 2.3 have two **completely** different recording playbacks. The 2.2 one will most probably not receive any more adjusments.

**Comment by anik3t** [comment]
![bbb](https://user-images.githubusercontent.com/27769614/105731959-fad42c80-5f55-11eb-8b2e-a94303670c40.png)
Toggle fullscreen mode button near the cursor

**Comment by anik3t** [comment]
@prlanzarin I couldn't get those details from the dev team. I am not in a place to connect with them. Only thing I could confirm is BBB is integrated with moodle in Jan 2021

**Comment by pedrobmarin** [comment]
This is not a bug, just an annoying thing the playback had as @prlanzarin mentioned. #9052 for extra details.
