### ISSUE TITLE
BBB2.3 Alpha 4,  telephone dialin option not showing in join audio dialog  

### ISSUE THREAD

**Issue by hostbbb** [bigbluebutton/bigbluebutton#11196]
**Describe the bug**

change in bigbluebutton.properties the phone number, 
restart server
does not trigger the option to join with the pin# in join audio dialog

**Comment by mariogasparoni** [comment]
Can't reproduce this in **2.3-beta-3**.
To test it, in `/usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties` i set `defaultDialAccessNumber` like this:
```
defaultDialAccessNumber=613-555-1235
```
and then restarted bbb: the dial-in option appeared :)
The number must be different from `613-555-1234` (default value), or the dial-in option won't shown.

This issue can be closed.

cc @antobinary
