### ISSUE TITLE
Breakout Room: Number of rooms dropdown does not work

### ISSUE THREAD

**Issue by apinos76** [bigbluebutton/bigbluebutton#11197]
**Describe the bug**
When creating breakout rooms and clicking on the dropdown to specify the number of rooms, the dropdown does not open.

This is very random and hard to reproduce but we have had many occurrences/tickets about it in the past.  Only now were we able to see what is going on through a video shared with us by a customer. 

**To Reproduce**
1. Go to "Create breakout rooms"
2. Click on the dowpdown for Number of rooms
3. See error

**Expected behavior**
We expect that the dropdown opens as it normally should, giving the user the option to choose more than two breakout rooms.

**Actual behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/30633300/105364080-bd287a00-5bca-11eb-83e2-29c4f523085b.png)

**BBB version (optional):**
BigBlueButton Server 2.2.31(1114) (but also happened in earlier versions)

**Desktop (please complete the following information):**
 - OS: Windows, Mac
 - Browser Chrome
 - Version 86

**Additional context**

**Comment by basisbit** [comment]
> See error

Which error does it show? Also, please fill out the `Actual behavior` section of the issue description. Than you.

**Comment by apinos76** [comment]
@basisbit there is no error. It just does not open the dropdown, as explained.  Actual behavior is the same as the expected behavior.  It seems redundant.

**Comment by basisbit** [comment]
can not reproduce, on various webbrowsers and various device types. Anyways, this uses the standardized html element `select` containing a bunch of `option` tags. There is no magic javascript which handles the clicking or similar. Thus I guess that your webbrowser or your device just has some bug. Please try updating or consider using another webbrowser temporarely.

**Comment by ritzalam** [comment]
I remember there was a report about this issue end of 2020. The reporter says, that the issue happens when a whiteboard textbox is open in the presentation area and the presenter creates a breakout room.

However, I can't find the issue anymore in the open issue. Perhaps that has been fixed and this is another edge case.

**Comment by apinos76** [comment]
@basisbit this is for a customer or rather a list of customers.  We cannot reproduce but have seen a video of it happening.  This bug was opened to track work done to try to reproduce and hopefully fix it.
