### ISSUE TITLE
Random viewer select: "no selectable viewer" warning disabled

### ISSUE THREAD

**Issue by hiroshisuga** [bigbluebutton/bigbluebutton#11209]
**Describe the bug**
When selecting a viewer randomly alone in a meeting with #11175, "no selectable viewer" warning is not displayed.

**To Reproduce**
1. With the latest dev branch, start a meeting alone.
2. Select a viewer randomly
3. Nothing displayed

**Expected behavior**
"No selectable viewer" warning should be displayed, as is implemented in the PR.

**Actual behavior**
Nothing displayed

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, Mac]
 - Browser [e.g. Chrome, Safari]

**Smartphone (please complete the following information):**
 - Browser [e.g. stock browser, Safari]

**Additional context**

**Comment by MaximKhlobystov** [comment]
This has been fixed in the PR #11280. When there's no viewers in the meeting, special modal is displayed. I think we can close this issue.
