### ISSUE TITLE
Can't accept waiting members because missing scrollbar

### ISSUE THREAD

**Issue by Dennis1993** [bigbluebutton/bigbluebutton#11200]
**Describe the bug**
If we create a room with the option, that members needs to be accepted before joining, the cant scroll down and accept members after the 14th position.
We have over 100 users waiting. If I want to accept some users after the 14th entry in the list I cant do that, becuase no scrollbar is available

**To Reproduce**
1. Create a room with the option, that they needs to be accepted by moderator
2. You need over 14 users which are waiting to start the meeting
3. Try to accept oder deny a user in the list
4. 1 - 14 you can manager, the rest is not visible because no scrollbar is available

**Expected behavior**
scrollbar to scroll down in the user list

**Actual behavior**
We can't accept users to join the meeting

**Screenshots**
![Unbenannt-1](https://user-images.githubusercontent.com/1473674/105395034-972cc500-5c1e-11eb-9b83-130692b606a6.jpg)

**BBB version (optional):**
BigBlueButton continually evolves. Providing the version/build helps us to pinpoint when an issue was introduced.
Example:
$ sudo bbb-conf --check | grep BigBlueButton
BigBlueButton Server 2.2.31

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Microsoft Edge, Chrome and Firefox tested
 - Version always the latest build/version

**Comment by ffdixon** [comment]
Thanks for reporting this.  We are working on fixing this issue in BigBlueButton 2.3-dev, the next version of BigBlueButton currently under development.

**Comment by Dennis1993** [comment]
Thank you for your reply!
Is it a big change?
Because: we have every week a big conference and can‘t accept users. If it‘s a simple fix, maybe we can fix it in 2.2 too?

**Comment by ffdixon** [comment]
We're increasingly focusing our efforts on 2.3-dev which will provide a new UI for guest management.  And, 2.3-dev should have more scalability for larger conferences.

**Comment by Dennis1993** [comment]
Ok, thanks 👍

**Comment by wolbernd** [comment]
@Dennis1993 There already was a PR to fix this which got merged with the 2.3 branch. 
The change is a relatively simple CSS change you could manually put into your BBB servers: https://github.com/bigbluebutton/bigbluebutton/pull/10027

**Comment by Dennis1993** [comment]
Thanks! I can do that 👍
Thats a Solution for me

**Comment by daminebenq** [comment]
This is not anymore reproducible.

**Comment by pedrobmarin** [comment]
This is a 2.2 bug

**Comment by antobinary** [comment]
We won't be pushing out any more 2.2 updates (End of support). 2.3+ have this addressed from what I can tell.
