### ISSUE TITLE
Extend getRecordings to provide processing status

### ISSUE THREAD

**Issue by Dennis1993** [bigbluebutton/bigbluebutton#11205]
Sone users uses the recording feature in bbb. After the meeting the recording is rendering in the background but the user doesnt know that. No information is shown in the system. Every day I receive a call from the moderators that the recording is not saved.

After some minutes the recording is shown.

Is it possible to show the video directly in the recording list with a label or so, that the video is rendering at the moment and will be ready in some minutes?
A little information for the user is ok. But nothing is bad 😊

**Comment by hiroshisuga** [comment]
I agree. But this appears to be a frontend (probably Greenlight) issue.

**Comment by Dennis1993** [comment]
I asked before: https://github.com/bigbluebutton/greenlight/issues/2457

**Comment by hiroshisuga** [comment]
Hahaha, this is a typical BBB - GL going back and forth. GL needs an API to read the recording information, but BBB does not have so much motivation to implement because it doesn't have the frontend.

**Comment by Dennis1993** [comment]
Typical for open source software...
A little message on the recording page is enough. If it‘s to complicate to read the current status a simple message would be useful 😊

**Comment by pedrobmarin** [comment]
Greenlight should use bigbluebutton's webhooks.

**Comment by hiroshisuga** [comment]
Wow I didn't know this bbb-webhooks. Sounds useful!

**Comment by ffdixon** [comment]
Regarding the back and forth, we need to extend the BigBlueButton API to provide feedback on the current status for processing recordings.  

Once we do that, Greenlight (and any other front-end) can display that information for the user.

**Comment by prlanzarin** [comment]
Just to add a bit on what @pedrobmarin said:

- https://docs.bigbluebutton.org/dev/webhooks.html
- https://github.com/bigbluebutton/bigbluebutton/blob/v2.2.x-release/bbb-webhooks/messageMapping.js#L343

**Comment by fcecagno** [comment]
The API already supports the state parameter in the getRecordings call, see: https://docs.bigbluebutton.org/dev/api.html#getrecordings
I agree with the suggestion to use the webhooks (we do it, and works great), although it would require an implementation on Greenlight and most probably on Scalelight as well.
For now, I'd suggest to re-open the issue on Greenlight and close this one, since the recording status is already present in the getRecordings API.

**Comment by misisol** [comment]
@fcecagno But it doesn't give any information if the recording has not start being processed, not information before that. Idn if it's a Bug or not..

**Comment by Dennis1993** [comment]
Still exists and not optimized
