### ISSUE TITLE
When joining a breakout room's audio, the microphone button dissappears

### ISSUE THREAD

**Issue by Elaborendum** [bigbluebutton/bigbluebutton#11208]
**Describe the bug**
There's an option to join a breakout room's audio, but when doing so the presenter is only able to hear the audio and has no option to reactivate their microphone as it dissappears.

Server is configured to mute all participants on entry.

Is this intended?

**To Reproduce**
1. Create breakout rooms
2. Click on "Join audio" in any of them
3. See error

**Expected behavior**
The presenter would be able to speak to the participants in the breakout room.

**Actual behavior**
The presenter can't communicate with the participants in the breakout room.

**Screenshots**
![image](https://user-images.githubusercontent.com/71190696/105564635-0ffc5180-5cf1-11eb-9941-1fafdc5a3f9c.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome, Firefox
 - Version: 86.0, 84.0

**Comment by PlumedArcher** [comment]
Couldn't reproduce with Chrome Version 89.0.4389.90 and BBB build 2.3-alpha8. The presentator can communicate with the participants in the breakout room normally.
