### ISSUE TITLE
How do I record each participant's audio differently and save them separately?

### ISSUE THREAD

**Issue by sourabharsh** [bigbluebutton/bigbluebutton#11204]
I am able to record audios of all the participants mixed up. Is there a way to keep them separate? I need it for running speech to text on individual participants.

**Comment by prlanzarin** [comment]
What is going on with you? It's the third issue about the _same thing_ you opened in a 30 minute timespan. Refrain from doing that if possible.

**Comment by sourabharsh** [comment]
Can you please provide a reason for closing this?

**Comment by prlanzarin** [comment]
As I said: you created three duplicates of the same issue. I left one of them open (https://github.com/bigbluebutton/bigbluebutton/issues/11202).

**Comment by sourabharsh** [comment]
Ohh. I am really sorry. the second one was made by mistake. Probably, I clicked the publishing shortcut unknowingly
