### ISSUE TITLE
How do I record each participant's audio separately and save them separately?

### ISSUE THREAD

**Issue by sourabharsh** [bigbluebutton/bigbluebutton#11202]
I am able to record the entire conference where audios for all the participant's are mixed up. 
However, I cannot figure out how to do it at individual participant level. 
Please help.

**Comment by basisbit** [comment]
For support requests and such questions, please use the [users forum / mailing list](https://groups.google.com/forum/#!forum/bigbluebutton-users) or  the [developer forum / mailing list](https://groups.google.com/forum/#!forum/bigbluebutton-users). This issue tracker here is only for BBB development related issues. Sorry.

**Comment by basisbit** [comment]
By the way, the template for the issue type which you chose contained this as first sentence:
> PLEASE DO NOT FILE ISSUES FOR GENERAL SUPPORT QUESTIONS.
