### ISSUE TITLE
Dark theme

### ISSUE THREAD

**Issue by bbb651** [bigbluebutton/bigbluebutton#11218]
**Is your feature request related to a problem? Please describe.**
I have all of my apps set with a dark theme, and BigBlueButton is really bright, which is pretty distracting and annoying. Moreover, I have a modified `userChrome.css` (a firefox feature that I use to modify the default stylesheet) and that makes the text white on white as it's color is not explicitly set to black, but rather it assumes the browser's default is black.

**Describe the solution you'd like**
I would like the app would style the app to a dark theme based on [`prefers-color-scheme`](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme). Looking at the existing stylesheets, is seems most of the colors are css variables rather than being hardcoded, which should makes implementing this easier. In addition to that, the color of the text (and any other elements that relay on browser defaults) should be explicitly set even in the light theme, to work on different browsers/browsers with modified defaults.

**Describe alternatives you've considered**
 I've tried using a 3rd party extension [Dark Reader](https://darkreader.org/) to force a dark theme, but the result is not as good as a native implementation could be. Some areas aren't dark, text on presentations is affected and becomes white on white, slows down the app a bit, etc.

**Additional context**
![White text issue](https://user-images.githubusercontent.com/53972231/105624662-3c68b880-5e2c-11eb-88d1-e069db254344.png)

![Dark reader](https://user-images.githubusercontent.com/53972231/105624665-41c60300-5e2c-11eb-9348-87e144dd8407.png)

Tested on Windows 10 Pro 64-bit 19041 Firefox 84.0.2

**Comment by EitanGITHUB** [comment]
Yes.

**Comment by Dennis1993** [comment]
Some teachers and students have asked me several times as the person responsible for IT, since classes are often given in the morning and working with them is a bit uncomfortable. Many other applications already support this, which is why it turns out that way.
