### ISSUE TITLE
Fancier random viewer selection

### ISSUE THREAD

**Issue by hiroshisuga** [bigbluebutton/bigbluebutton#11211]
**Is your feature request related to a problem? Please describe.**
I would like the PR #11175 (#10359) to be fancier. Currently it just shows who's been selected only to the selected one and the presenter, in a moment after a click. The unselected ones would never know who's been selected until the presenter announces it (not displayed in their PC). I would like the students feel more thrilled!

**Describe the solution you'd like**
What I would like is:
1. after a click, BBB starts to show one candidate after another, until the final decision is made (start drumming ;-).
2. on the screen, everybody sees the process of selection (candidates avatars changing). Students are scared even before being selected.
3. the pace that BBB shows the next candidates slowly drops, and eventually stops completely to show the final selected viewer. Yes, you are the one!

**Additional context**
I will try to do a PR.

**Comment by basisbit** [comment]
just my 2 cents: this sounds like `feature creep`, additional over-complex code that has to be maintained and which causes avoidable additional load on the NodeJS server. I'd like to hear some other developers opinions on this.

**Comment by hiroshisuga** [comment]
Thanks for the comment @basisbit !
Obviously we need a test with multiple meeting with many users. In my current implementation, however, it does not seem to suffer too much as it simply send a message ~10 times to the clients. Probably not more than the load from the pointer movement that you pointed out somewhere else, but I cannot be sure as I am not an expert. Let's see what the other developers say...

**Comment by ffdixon** [comment]
> 2. on the screen, everybody sees the process of selection (candidates avatars changing). Students are scared even before being selected.

This was actually actually part of our original UI design.  

The 'scared' part is good as students need to be ready to respond if called upon, and this helps focus the brain on the question at hand.  Our design had each student seeing an animation of about 10 names, and they aways see their name appearing in the animated list -- emphasizing that they could be selected.

@hiroshisuga, your suggestions are almost exactly what we had originally designed.  If you want to take a shot at implementing your suggestions, we would look forward to reviewing the PR!

**Comment by basisbit** [comment]
Could this maybe be implemented purely on client-side, so that one message from the server is enough to transfer the names and the final name?

**Comment by ffdixon** [comment]
@basisbit that's a good suggestion.  It's good to reduce the messages from the server where possible -- especially in meetings with 100 users (and maybe larger meetings in upcoming versions of BigBlueButton!).

**Comment by hiroshisuga** [comment]
Interesting suggestion, and I was considering it as well. The downside would be that the code may get complicated and a synchronization problem may happen (ie, the moderator announces the selected one before the animation finishes in each client).

**Comment by hiroshisuga** [comment]
This is what I have now. I will check the code and post it probably tomorrow.

![random](https://user-images.githubusercontent.com/45039819/105582386-2d095100-5dd3-11eb-8f3b-69431da29e3d.gif)

**Comment by antobinary** [comment]
A few items to keep in mind:
- implementation like the above would cause issues with accessibility - quickly switching modal contexts/selections
- seeing your name/avatar (for a second) can be confusing if it suddenly switches to a different user
- while not an expert in the subject matter, I would question the positive effct of being scared to be selected
- reminds me of the case of quickly switching screens/colours in anime triggering seisures...

Additional UX/implementation complexities
- distinguish between the avatar of John A and Joanne B (avatar = Jo)
- while not keeping akka-apps informed about the ongoing "shuffling" might be OK, it could be showing different screens to different viewers, which I am not too excited about

All in all, I would prefer not proceeding with the Fancy random viewer selection despite it being implementable in short fashion.

**Comment by hiroshisuga** [comment]
Thanks for the suggestions / great opinions. I will change the implementation design so that it doesn't impair the UI. I do not care so much if it will be merged or not. I just want my students enjoy online lectures!
