### ISSUE TITLE
Translation errors

### ISSUE THREAD

**Issue by Rafamaker** [bigbluebutton/bigbluebutton#11219]
**Describe the bug**
There are English strings for the Spanish version of bigbluebutton. 

**To Reproduce**
1. Go to 'course'
2. Click on 'Add an activity or resource'
3. Click on 'bigbluebuttonBN'
3. Scroll down to 'Lock settings'

**Expected behavior**
In the Spanish version, they should be translated.

**Actual behavior**
It is being seen in English.

**Screenshots**
I add screenshot.
![Captura](https://user-images.githubusercontent.com/77964836/105693622-3c39ed00-5f00-11eb-8caa-38cea1b71321.PNG)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [Mozilla Firefox]

**Comment by mpellicer** [comment]
As far as I can tell this source is related to the bigbluebutton Moodle integration plugin, maybe report this in:

https://github.com/blindsidenetworks/moodle-mod_bigbluebuttonbn

I suggest closing this issue and raising it in https://github.com/blindsidenetworks/moodle-mod_bigbluebuttonbn.
