### ISSUE TITLE
BBB2.3 - Not possible to write on every point of the whiteboard with an iPad

### ISSUE THREAD

**Issue by jonathansch1** [bigbluebutton/bigbluebutton#11212]
**Describe the bug**

On an iPad it isn't possible to write on every point of the whiteboard.

* There is a vertical line that divides the whiteboard into a left part where you cannot write on and a right part where it's possible.
* But if you're start writing on the right side and paint over that vertical line to the left, it's also possible to write on the left part. The unexpected behavior **only** appears if you try to start writing on the left side.
* There is no difference in behavior if you are using your finger or the Apple Pencil.

There are 3 different cases. These are shown in the attached screenshots.

1. Sidebar with participants & public chat opened:
    * It isn't possible to start writing on the left 1/3 part.
2. Only sidebar with participants opened:
    * It isn't possible to start writing on the left 1/2 part.
3. Nothing opened:
    * The whiteboard works without bad behavior.

**To Reproduce**

1. Start BigBlueButton's HTML 5 Client on an iPad (Pro).
2. Activate the pencil function.
3. Try to start writing on the left side of the whiteboard (it's not possible).
4. Try to start writing in the middle of the whiteboard (there is a vertical line from that it's possible, as like in the screenshots).
5. Try to start writing on the right side of the whitebard (it's possible).

**Expected behavior**

It's possible to use the whole whiteboard for writing.

**Actual behavior**

There are parts of the whiteboard where it isn't possible to write (under specific conditions).

**BBB version:**

That was tested and reproduced on:

* https://test23.bigbluebutton.org/ with client build: 1319
* our own BBB with client build: 1312

**iPad:**
 - Device: iPad Pro 10.5, Model number: MQDT2FD/A
 - OS: iPad OS 14.3
 - Browser: (Mobile) Safari
 - Version: 14.0.2

**Additional context**

Actually it was only possible to reproduce that behavior on an iPad. With a Mac and on Windows the whiteboard works fine.

**Screenshots**

![screen](https://user-images.githubusercontent.com/57761546/105607974-7345bc80-5da1-11eb-8fe6-6618f2953330.jpg)

**Comment by basisbit** [comment]
Duplicate

**Comment by ffdixon** [comment]
Wish all our bugs were reported this well -- thanks!

**Comment by jonathansch1** [comment]
Thanks Fred!

I search for the duplicate again and found these: #9348 and #9383
But they are for BBB v2.2 and it was solved.

Now that bug is for BBB v2.3 and iPad only.

I did some more tests with the information from #9348.

![screen2](https://user-images.githubusercontent.com/57761546/105631750-4bf9f880-5e50-11eb-9e69-4820904f33ca.jpg)

That code covers the part of the whiteboard, where it isn't possible to write.

```html
<div class="tether-element tether-out-of-bounds tether-out-of-bounds-top tether-out-of-bounds-left tether-out-of-bounds-right tether-element-attached-middle tether-element-attached-center tether-target-attached-middle tether-target-attached-center tether-enabled" style="z-index: 1; width: 100%; height: 100%; top: 0px; left: 0px; position: absolute; transform: translateX(-481.5px) translateY(-157px) translateZ(0px);"><div>
```

**Comment by steffen-moser** [comment]
I can fully confirm Jonathan's observation on an iPad Pro with the following data:

    Device: iPad Pro 11 inch
    Model number: MTXN2FD/A
    OS: iPad OS 14.3
    Browser: (Mobile) Safari
    Version: 14.0.2

No problem on an Android Smartphone (Huawei P20 Pro).

**Comment by EmmyGraugans** [comment]
the bug is still present in BBB 2.3 alpha 7 on an iPad mini with iOS 14.4

**Comment by ffdixon** [comment]
Just tried it on my iPad (not iPad mini) running iOS 14.4 and the writing worked.  Can anyone else reproduce on their iPad mini?

**Comment by steffen-moser** [comment]
Unfortunately, I don't have an iPad mini. I'll test against alpha7 today with my iPad and iOS 14.4 this evening.

**Comment by EmmyGraugans** [comment]
For me it's also reproducible on test23.bigbluebutton.org
It's not that I can't draw *onto* the left part, it's that I can't *start* to draw on the left part (see screenshots from the original reporter)

**Comment by EmmyGraugans** [comment]
Additional note: with hidden chat and people-list, it is possible to start drawing everywhere. But with visible chat and participants, the problem occurs
