### ISSUE TITLE
audio notification when user joins the waiting room

### ISSUE THREAD

**Issue by PhMemmel** [bigbluebutton/bigbluebutton#11221]
**Is your feature request related to a problem? Please describe.**
When the moderator/presentator is busy teaching (especially when screensharing with only one screen) he/she often misses out on new attendees trying to join or attendees having connection issues trying to rejoin when **waiting room** is activated. An audio notification when someone joins the waiting room would solve this problem.

**Describe the solution you'd like**
Possibility to enable audio notification when a user joins the waiting room like the already existing feature when a user joins the session

**Additional context**
I'd propose to add an enable-switch for this feature in the notification menu which is disabled by default because at the start of a meeting the moderator probably doesn't want to hear 20 to 30 bling sounds. He usually prefers to enable this feature after the majority of users have successfully joined the session and before he starts his lession/presentation.

**Comment by basisbit** [comment]
Important consideration before implementing this: When people try to raid a publicly shared invite link to a room, that should not cause dozens of notification messages or sounds to show up. A rate-limiting like for the new chat messages notification should probably be used. That would probably also already solve the problem of many students joining at the beginning of the session.

**Comment by PhMemmel** [comment]
You are making me think of another possibility to implement this, but I'm not sure if this is wanted by the majority of users: Having someone waiting in the waiting room could trigger a notification sound every 30-ish seconds. So the sound would be triggered on a time basis, not triggered by a user join request, but of course only in the case when there is at least one attendee in the waiting room.

Advantages:
- solves the storming problem
- solves the situation at the beginning of a meeting where many attendees try to join in a short amount of time
- notifies the moderator continually even when he overhears/doesn't recognize the first sound notification
- is less annoying in the mentioned situations
- is less confusing for the moderator in contrast to rate-limiting: easier to understand when there is gonna be a sound and when there isn't

Disadvantage:
- This can become a bit annoying when you want users to be stuck in the waiting room (e. g. you are just finishing your current conversation before letting the next person in). The sound would have to be not very disturbing or - which would even be better IMO - there would have to be an "offensive" option/switch in the waiting room control window (where you accept or deny users) to disable the audio notification. This could also be done on a time basis, e. g. "Disable audio notification for the next 10 minutes"

**Comment by cyfrax** [comment]
Good ideas! I'm afraid if we make it too complicated then developers will postpone the implementation.

Maybe a simpler way to implement is enough:
- ON/OFF switch for audio notifications in the waiting room context menu (default: ON) 
- Only output audio notification if the last audio notification is older than 15 seconds so we avoid the multiple sound issue

This means the moderator has a maximum 15 second attention span he/she has to look after the waiting room. In real life this will be closer to 0 seconds as it'll take a while to change into the correct window, allow participants in - the moderator will probably be still in the waiting room GUI anyway. In very busy conferences he/she will probably turn off the notification sound anyway or have an assistant moderator.

**Comment by falkiy** [comment]
Just want to state having the same requests from users, would really appreciate such a feature.

**Comment by IT44-studIT** [comment]
We also need this feature for our remote support via BBB. Would be awesome if someone would kick this off.
