### ISSUE TITLE
[2.3] Presentation actions bar dropdown UI bug

### ISSUE THREAD

**Issue by daminebenq** [bigbluebutton/bigbluebutton#11237]
**URL tested:** https://develop.bigbluebutton.org/html5client/2/join?sessionToken=vpov0rdloyygm1fk

Open [URL](https://live.browserstack.com/dashboard#os=iOS&os_version=14.0&device_browser=safari&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fdevelop.bigbluebutton.org%2Fhtml5client%2F2%2Fjoin%3FsessionToken%3Dvpov0rdloyygm1fk&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://develop.bigbluebutton.org/html5client/2/join?sessionToken=vpov0rdloyygm1fk&utm_campaign=bug-report&utm_source=bug-report-url-to-reproduce&utm_medium=github) on Browserstack

Tested on iPhone 12, but it's happening on all mobile devices on 2.3

|Property | Value|
|------------ | -------------|
| Device | iPhone 12 |
| Browser | Mobile_safari |
| Operating System | iOS 14.0 |
| Resolution | 1170x2532 px |
| Screen size | 5.5 in - 2.46 x 4.92 in |
| Viewport | 393 x 786 dp |
| Aspect Ratio | 19.5 : 9 |
![image](https://user-images.githubusercontent.com/5144311/107548842-e460de80-6bad-11eb-9201-e6adaace4ec1.png)

**Screenshot Attached** 
[Screenshot URL](https://live.browserstack.com/issue-tracker/4ebd8dd9357d47d30007d7887b6065eebee45de4/realios_iPhone_12.jpg)
 ![Screenshot URL](https://live.browserstack.com/issue-tracker/4ebd8dd9357d47d30007d7887b6065eebee45de4/realios_iPhone_12.jpg)

STEPS TO REPRODUCE:
1) go to a meeting using a mobile device in 2.3
2) tap action button (+) in presentation area
3) the close modal button has audio/webcam/screenshare buttons (maybe placed in center or right of the button but won't be showing because of they are in white and the background color of the modal is also white) are on top of it (if you tap Close button, audio/webcam/screenshare modal will appear)

Expectation:
Only close presentation actions modal should be clickable. other buttons (main screen button; audio/webcam/screenshare) in the background should not appear at all when the modal is expanded.

**[Click here](https://live.browserstack.com/dashboard#os=iOS&os_version=14.0&device_browser=safari&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fdevelop.bigbluebutton.org%2Fhtml5client%2F2%2Fjoin%3FsessionToken%3Dvpov0rdloyygm1fk&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://develop.bigbluebutton.org/html5client/2/join?sessionToken=vpov0rdloyygm1fk&utm_campaign=bug-report&utm_source=bug-report-url-to-reproduce&utm_medium=github) to reproduce the issue on Browserstack**

**Comment by pedrobmarin** [comment]
What's up with this?

**Comment by daminebenq** [comment]
@pedrobmarin i edited the issue with the reprodution steps, sorry forgot to add the description in the issue reporting modal from Browserstack directly

**Comment by daminebenq** [comment]
closing after unability to reproduce.
