### ISSUE TITLE
upload-convert presentations without being presenter

### ISSUE THREAD

**Issue by bquast** [bigbluebutton/bigbluebutton#11249]
This way I could prepare presentations while somebody else is presenting

**Is your feature request related to a problem? Please describe.**
I often use two devices during meetings, one to run through the presentation, the other to upload presentation coming in. If I could upload presentations from the second device, the conversion time would not interfere with the meeting.

**Describe the solution you'd like**
A way to upload presentations by moderators that are not at that moment presenters.

**Describe alternatives you've considered**
Now I convert everything (office docs) to PDF on my device, to limit the conversion time.

**Additional context**

**Comment by basisbit** [comment]
@bquast Please fill in the issue description template.

**Comment by bquast** [comment]
@basisbit done now, thank you
