### ISSUE TITLE
Add API call to get the number of guest waiting for approval before me

### ISSUE THREAD

**Issue by francov** [bigbluebutton/bigbluebutton#11246]
**Is your feature request related to a problem? Please describe.**
When a guest is in a wait for approval status, she has no way to know ehat is her position in the queue for approval (I consider a queue that list, despite the moderator may accept or deny in an unordered manner).

**Describe the solution you'd like**
I want an API that returns my position in the queue based on request join timestamp

**Describe alternatives you've considered**
Nothing considered, because the `getMeetingInfo` returns only attendees that have joined the room, not those who are waiting.

**Comment by pedrobmarin** [comment]
There is already an API call that could be used for that, is the same the guest user fetches to find out if he/she was approved into the meeting. It's called `guestWait'

**Comment by francov** [comment]
My app is actually polling that route for until the response guestStatus is "ALLOW", then redirects to the html5 client. In the response of `guestWait` i can't find anything usefull as you stated... this is a sample response:
```
{
  "response": {
    "returncode": "SUCCESS",
    "messageKey": "guestWait",
    "message": "Guest waiting for approval to join meeting.",
    "meeting_id": "a1305ca10f94f2340770c73e26d427588f236709-1611776532770",
    "user_id": "w_ddodphshrnen",
    "auth_token": "vzzeabyn8ve3",
    "session_token": "eit7j2zck0wswhrm",
    "guestStatus": "WAIT",
    "url": "https://bbb1.gmcricerche.com/client/guest-wait.html?sessionToken=eit7j2zck0wswhrm"
  }
}
```
Am I missing something?

**Comment by pedrobmarin** [comment]
Maybe I wasn't clear on my answer, sorry about that. All I mean was that we could include the information you suggested at this API call response.

**Comment by francov** [comment]
Ah I misunderstood. Yes, for my use case it would be the ideal in `guestWait` response.

However there may be cases where you want to know the status of the wait queue from a management panel or before making a join request, in those case I think that `getMeetingInfo` may contains that information too.

**Comment by ConfMe** [comment]
I am also very interested in this feature.
