### ISSUE TITLE
Allow publishing survey results into text chat

### ISSUE THREAD

**Issue by zseri** [bigbluebutton/bigbluebutton#11257]
**Is your feature request related to a problem? Please describe.**
In "whiteboard mode", if scrolled in, survey results may be published in a corner which isn't visible.
It would be good if alternatively survey results could be published into the text chat.

**Describe the solution you'd like**
Add a room setting which allows switching between publication into whiteboard vs chat.

**Describe alternatives you've considered**
Scale publish results and put them in a corner of the currently visible area.

**Comment by pedrobmarin** [comment]
Implemented in v2.3 https://github.com/bigbluebutton/bigbluebutton/pull/8525
