### ISSUE TITLE
Option to prepopulate user-list of breakout rooms

### ISSUE THREAD

**Issue by crazy-daddy** [bigbluebutton/bigbluebutton#11256]
At our school one of the most requested features is the ability to prepare breakout rooms ahead of time. 
I would imagine something like adding a button to load a textfile into the breakout-rooms-creation screen. Textfile would be
USERNAME;ROOMNUMBER
UserA;1
UserB;2
UserC;1
UserD;2
etc.

This of course only works in scenarios where - like for us using Nextcloud-integration - the usernames are defined in advance.

**Comment by antobinary** [comment]
Merging into https://github.com/bigbluebutton/bigbluebutton/issues/13628 for 2.5

**Comment by nidico** [comment]
> Merging into #13628 for 2.5

I'm fine with merging both issues as they very much overlap, however I wonder whether what has been implemented in #13678 allows moderators to assign users to multiple groups (which can be used in subsequent breakout rooms) without prepopulating through an external LMS, as this is what this issue (#11256) is about in the first place. If this isn't fully implemented yet, we should keep the issue open.
