### ISSUE TITLE
Extend phone number documentation to support inband dtmf

### ISSUE THREAD

**Issue by SoerenBusse** [bigbluebutton/bigbluebutton#11253]
**Describe the bug**
When using the documentation from https://docs.bigbluebutton.org/install#add-a-phone-number-to-the-conference-bridge to setup a dialplan for external telephone number support you always get the error "This was an invalid entry" after entering the Pin, when using a phone which only supports Inband DTMF.

RTP (RFC2833) and SIP Info works absolutly fine.

This is because you've to enable Inband DTMF in freeswitch manually using the `start_dtmf` action, which is missing in the official documentation

```
<extension name="PHONE_NUMER">
    <condition field="destination_number" expression="^PHONE_NUMER">
        <action application="start_dtmf" />
        <action application="answer"/>
        <action application="sleep" data="2000"/>
        <action application="play_and_get_digits" data="5 5 3 7000 # conference/conf-pin.wav ivr/ivr-that_was_an_invalid_entry.wav pin \d+"/>
        <action application="transfer" data="SEND_TO_CONFERENCE XML public"/>
    </condition>
</extension>
```

**Comment by basisbit** [comment]
Fred already added this to the documentation. For future issues regarding documentation, please use the correct github repository at https://github.com/bigbluebutton/bigbluebutton.github.io/issues . Thanks!
