### ISSUE TITLE
Wrong icon on audio button

### ISSUE THREAD

**Issue by Dennis1993** [bigbluebutton/bigbluebutton#11269]
If I want start an audio session the icon is a phone:
![image](https://user-images.githubusercontent.com/1473674/106355537-024e5980-62f9-11eb-8c3c-daab40cb0a83.png)

If I start the session and select "only listen" the icon is correct:
![image](https://user-images.githubusercontent.com/1473674/106355570-227e1880-62f9-11eb-8056-aee7971791a6.png)

If I start the audio session with microphone, the icon switched to a phone. I think thats a wrong icon. Users dont understand that. Some users mean that they can start a call by a telephone.
![image](https://user-images.githubusercontent.com/1473674/106355526-e64ab800-62f8-11eb-8a4d-eb1c7563ca77.png)

It's possible to change the icon to a headphone by default?

We use BBB 2.3.31 with the latest Greenlight 2.7.18

**Comment by ffdixon** [comment]
When joining listen only, there is only one operation: leave audio.  When joining with microphone, there are two operations: mute/unmute and leave audio.

We recognize at the moment that the phone icon suggest phoning into the conference bridge.

**Comment by Jossef-767** [comment]
in bigbluebutton custom icon library there is an "Audio Off" icon that maybe can better indicate disconnecting audio 
![image](https://user-images.githubusercontent.com/2356928/106378398-1f446480-63ad-11eb-9778-a6ff7d93329e.png)

**Comment by Dennis1993** [comment]
That icon is more logical for users! 👍

**Comment by pedrobmarin** [comment]
Personally I vote this one up https://github.com/bigbluebutton/bigbluebutton/pull/11614
