### ISSUE TITLE
HTTP 500 on api Call -> /bigbluebutton/api/guestWait?sessionToken=xxxxxxxxxxxxx&redirect=false

### ISSUE THREAD

**Issue by mfoehlinger** [bigbluebutton/bigbluebutton#11261]
We use version 2.3.0 and so far everything works, except if a guest is waiting in the lobby then always gets a status code 500 with the request /bigbluebutton/api/guestWait?SessionToken=xxxxxxxxx&redirect=false

![oie_OLhSTqtFaMMa(1)](https://user-images.githubusercontent.com/13310688/106302157-e2675900-6258-11eb-9ada-e84ce1c9e5dd.png)

bbb-conf --check

nginx —————————————————► [✔ - active]
freeswitch ————————————► [✔ - active]
redis-server ——————————► [✔ - active]
bbb-apps-akka —————————► [✔ - active]
bbb-fsesl-akka ————————► [✔ - active]
tomcat8 ———————————————► [✔ - active]
mongod ————————————————► [✔ - active]
bbb-html5 —————————————► [✔ - active]
bbb-webrtc-sfu ————————► [✔ - active]
kurento-media-server ——► [✔ - active]
etherpad ——————————————► [✔ - active]
bbb-web ———————————————► [✔ - active]

**Comment by ffdixon** [comment]
We should have 2.3-alpha5 out soon with a fix for this.

**Comment by mfoehlinger** [comment]
how can i update to Version 2.3-alpha5 ?

**Comment by ffdixon** [comment]
We'll announce its availability (along with steps to upgrade) to [bigbluebutton-dev](https://groups.google.com/forum/#!forum/bigbluebutton-dev) mailing list.

**Comment by ffdixon** [comment]
We've released 2.3-alpha5.  Please see [release notes](https://github.com/bigbluebutton/bigbluebutton/releases/tag/v2.3-alpha-5) and steps to [install/upgrade](https://docs.bigbluebutton.org/dev/dev23.html).

**Comment by mfoehlinger** [comment]
Thank You. ... very nice work
