### ISSUE TITLE
app.error.fallback.view.title in new session

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#11270]
**Describe the bug**
In testing 2.3-alpha5, I occasionally see app.error.fallback.view.title when starting a new session.

**To Reproduce**
Start new sessions and this error will occasionally appear. A refresh of the page will cause the presentation to load.

**Expected behavior**
The presentation always loads.

**Screenshots**
![image](https://user-images.githubusercontent.com/290351/106359256-e3939700-62e7-11eb-9249-051e1149b51b.png)

**BBB version (optional):**
2.3-alpha5

```
BigBlueButton Server 2.3.0-alpha5 (1527)
                    Kernel version: 4.15.0-121-generic
                      Distribution: Ubuntu 18.04.5 LTS (64-bit)
                            Memory: 16424 MB
                         CPU cores: 8
```

**Additional context**

3db6e0bbbc534f411771528262979c2d67eb22de.js?meteor_js_resource=true:69 TypeError: Cannot destructure property 'width' of 'e.slidePosition' as it is undefined.
    at P.componentDidUpdate (3db6e0bbbc534f411771528262979c2d67eb22de.js?meteor_js_resource=true:353)
    at Es (3db6e0bbbc534f411771528262979c2d67eb22de.js?meteor_js_resource=true:69)
    at Vl (3db6e0bbbc534f411771528262979c2d67eb22de.js?meteor_js_resource=true:69)
    at n.unstable_runWithPriority (3db6e0bbbc534f411771528262979c2d67eb22de.js?meteor_js_resource=true:87)
    at ui (3db6e0bbbc534f411771528262979c2d67eb22de.js?meteor_js_resource=true:69)
    at Gl (3db6e0bbbc534f411771528262979c2d67eb22de.js?meteor_js_resource=true:69)
    at Al (3db6e0bbbc534f411771528262979c2d67eb22de.js?meteor_js_resource=true:69)
    at 3db6e0bbbc534f411771528262979c2d67eb22de.js?meteor_js_resource=true:69
    at n.unstable_runWithPriority (3db6e0bbbc534f411771528262979c2d67eb22de.js?meteor_js_resource=true:87)
    at ui (3db6e0bbbc534f411771528262979c2d67eb22de.js?meteor_js_resource=true:69)
[console.log](https://github.com/bigbluebutton/bigbluebutton/files/5898128/console.log)

**Comment by ramonlsouza** [comment]
Could not reproduce, but (based on the error message) may be related to `bigbluebutton-html5/imports/ui/components/presentation/component.jsx:171`:

```const { width: prevWidth, height: prevHeight } = prevProps.slidePosition;```

**Comment by ffdixon** [comment]
Thanks @ramonlsouza -- it happens intermittently in 2.3-alpha-5.

**Comment by antobinary** [comment]
@ramonlsouza You can try to comment out (temporarily) the event handler (server side) for upserting Slide Position. That will likely trigger this bug more consistently. Once you reach that stage, you can:
1)  modify the fallback case - instead of rendering the presentation unusable, we can default to a safe generic Slide Position. That would likely make pan/zoom unusable on the slide but at least we will be able to see the slide.
2) see if there is a good way to tweak the flow of events so we either wait->retry->fallback to safe values OR something else

**Comment by aogilvie** [comment]
I don't want to muddy the waters on this but I've only seen this error from ppt documents. When uploading a PDF never saw this issue. I can't confirm the above but these are facts at the time of the errors:
- a default pdf was set in bigbluebutton.properties which is loaded for all meetings
- after entering the meeting, passed presenter rights, someone uploaded a ppt, all users saw the error.

**Comment by ArlexFabian** [comment]
De igual forma tengo instalada esta Versión 2.3-alpha5 y de igual forma me aparece el  error, por otra parte la opción de en cuenta redirige a una pantalla vacía en algunos casos

**Comment by daminebenq** [comment]
@ArlexFabian Gracias por confirmar!!
This issue is still reproducible on 2.3. Tested it manually and with the test scripts.
