### ISSUE TITLE
BBB 2.3 upgrade alpha4->5 dependency issue

### ISSUE THREAD

**Issue by rasos** [bigbluebutton/bigbluebutton#11279]
We had a working BBB 2.3 alpha4. Upgrade currently fails: 

```
Setting up bbb-web (1:2.3.0-30) ...
sed: -e expression #1, char 81: unknown option to `s'
dpkg: error processing package bbb-web (--configure):
 installed bbb-web package post-installation script subprocess returned error exit status 1
Setting up mongodb-org (4.2.12) ...
Setting up nplan (0.99-0ubuntu3~18.04.4) ...
dpkg: dependency problems prevent configuration of bbb-html5:
 bbb-html5 depends on bbb-web; however:
  Package bbb-web is not configured yet.

dpkg: error processing package bbb-html5 (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of bbb-config:
 bbb-config depends on bbb-html5; however:
  Package bbb-html5 is not configured yet.

dpkg: error processing package bbb-config (--configure):
 dependency problems - leaving unconfigured

dpkg: dependency problems prevent configuration of bigbluebutton:
 bigbluebutton depends on bbb-config; however:
  Package bbb-config is not configured yet.

dpkg: error processing package bigbluebutton (--configure):
 dependency problems - leaving unconfigured
Processing triggers for systemd (237-3ubuntu10.44) ...
Processing triggers for man-db (2.8.3-2ubuntu0.1) ...
Processing triggers for dbus (1.12.2-1ubuntu1.2) ...
Processing triggers for libc-bin (2.27-3ubuntu1.4) ...
Errors were encountered while processing:
 bbb-web
 bbb-html5
 bbb-config
 bigbluebutton
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by rasos** [comment]
after a bbb-conf --restart I got

**Comment by ffdixon** [comment]
For the issue on upgrading, I just tried upgrading from alpha-4 to alpha-5 using `bbb-install.sh` and didn't encounter the same error.

By chance did you edit any the configuration files yourself?  Can you edit `/var/lib/dpkg/info/bbb-web.postinst` and change the first line to

```
#!/bin/bash -ex
```

and then run `sudo apt-get install -f` and let us know the lines proceeding the error.

**Comment by rasos** [comment]
Yes we usually adapt `bigbluebutton.properties` . I did the first update with `apt upgrade`, which failed. Upgrading from alpha-4 to alpha-5 using `bbb-install.sh` then worked fine.  So I can't test the suggested patch anymore. We are using BBB 2.3 already for production and we needed to be ready for Monday morning teaching sessions.

**Comment by basisbit** [comment]
@rasos why are you using an alpha build for production?
I'd suggest wiping that machine, installing bbb 2.2.x and then using that for production. We can not provide support for alpha and beta versions that are clearly marked as not ready for production use.

**Comment by rasos** [comment]
We do have several 2.2 machines in production and are gaining experience with 2.3 in a real world environment. 

This issue was meant as a feedback to improve the update handling, not a support request. We could fix it by re-applying the install script.

**Comment by ffdixon** [comment]
While the label of 'alpha-5' is meant to convey that this is still in active development, we are iterating quickly to a stable environment on which we can build more features. 

Our priorities for 2.3 development (in equal order) are stability, usability, and security.  We want to get the joining/leaving and stability of the meetings solid, while pulling in all the work we've done on 2.2 (including all security fixes).

Of course, we don't recommend running 2.3-alpha-5 in production, BUT we do value the feedback from anyone who does so (even for a limited length of time) so we can quickly address the outstanding issues for our community and help move everyone quickly to the newer release.

Thanks @rasos, we appreciate it.
