### ISSUE TITLE
Mic audio level indicator OR/AND individual volume control.

### ISSUE THREAD

**Issue by Beiri22** [bigbluebutton/bigbluebutton#11277]
Hi there,

we sometime experience the problem of people having very different mic volume settings, some giving a lound signal, others a rather quiet one. It's hard to listen to such a mixed group. As far as I understand, bbb is mixing the audio server-side, which would make the following features very intersting to me:

1.) A personal mic level indicator in echo-test and the running meeting, so that everyone can see his (lets say) avg audio level / loudness. Maybe an automatic hint when the level is on average too high or low.

2.) A control panel for the host / moderators that allows them to apply a per-person volume adjustment during meeting. In most cases this would be only a few changes, but the possibility to do so would be great. The setting could be sent to the server and applied when mixing the streams.

Sincerely, Rico

**Comment by basisbit** [comment]
Please search for duplicate issues before opening an issue here in the issue tracker. Also please do not ignore the mandatory issue template.

Closing this as duplicate.
