### ISSUE TITLE
Ensure bbb-etherpad is included in --zip and --clean commands

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#11289]
Currently I do not see bbb-etherpad listed in neither `bbb-conf --clean` nor `bbb-conf --zip` handles
https://github.com/bigbluebutton/bigbluebutton/blob/develop/bigbluebutton-config/bin/bbb-conf

`   --zip                            Zip up log files for reporting an error`
`   --clean                          Restart and clean all log files`

**Comment by lonesomewalker** [comment]
Where are the logfiles of bbb-etherpad stored?

**Comment by antobinary** [comment]
Looks like logs are passed on to systemd if I understand correctly

`journalctl -u etherpad.service` produces the logs of the day.

**Comment by lonesomewalker** [comment]
*bump*
