### ISSUE TITLE
bbb-install: Unable to determine local IP address.

### ISSUE THREAD

**Issue by serveisinformatics** [bigbluebutton/bigbluebutton#11287]
Hi all.

We recently made a server copy of big blue button and today we tried to install it from scratch.

We have had the following problem:

bbb-install: Unable to determine local IP address.

We're using a different ip internal/external.

We have no idea what the problem may be.

Any ideas?

Thanks in advance.

**Comment by ffdixon** [comment]
Can you post this question to [bigbluebutton-setup](https://bigbluebutton.org/support/community/) and we'll help you there.  Please post the output of the following two commands

echo $(ifconfig | grep -v '127.0.0.1' | grep -E "[0-9]*\.[0-9]*\.[0-9]*\.[0-9]*" | tail -1 | cut -d: -f2 | awk '{ print $1}')
echo $(ifconfig $(route | grep ^default | head -1 | sed "s/.* //") | awk '/inet /{ print $2}' | cut -d: -f2)

**Comment by serveisinformatics** [comment]
I'll do.

Thanks.
