### ISSUE TITLE
Polling results in chat are missing the icon

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#11291]
**Describe the bug**
Polling results in chat are missing the icon on the left-hand side

**To Reproduce**

**Expected behavior**
![Screenshot from 2021-02-02 11-32-06](https://user-images.githubusercontent.com/6312397/106631323-a7ac3c00-654a-11eb-9975-5be3879b4d35.png)

**Actual behavior**
The icon is missing
![Screenshot from 2021-02-02 11-35-07](https://user-images.githubusercontent.com/6312397/106631399-bb57a280-654a-11eb-9fc6-776a401187d0.png)

**BBB version (optional):**
BigBlueButton 2.3-alpha5

**Comment by daminebenq** [comment]
This is back again to be reproducible

https://github.com/bigbluebutton/bigbluebutton/pull/11314#issuecomment-784259909

![image](https://user-images.githubusercontent.com/5144311/108861660-3e11d180-75ce-11eb-87c0-b4b94d7ead8e.png)
