### ISSUE TITLE
Screenshare switch screen

### ISSUE THREAD

**Issue by alombia** [bigbluebutton/bigbluebutton#11292]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

I am not sure if this already available but when you screenshare a tab or application window, it is mildly annoying to stop sharing in order to switch to a new tab or window. I know this can be avoided by sharing whole screen but i prefer to see my users and really dislike the picture in picture situation. Is it possible to have a feature to switch to new screenshare window?

**Describe alternatives you've considered**

**Additional context**

**Comment by basisbit** [comment]
You forgot to fill in the description...
