### ISSUE TITLE
Custom frontend Bigbluebutton

### ISSUE THREAD

**Issue by newgate1999** [bigbluebutton/bigbluebutton#11294]
Hi all,
I want to custom frontend bigbluebutton locally. 
I have run the html5 project, but I have yet to find a way to join a meeting to see the change when I code. so that can you show me how to custom html5?
Regards,

**Comment by basisbit** [comment]
For support requests, please use the [forum / mailing list](https://groups.google.com/forum/#!forum/bigbluebutton-dev). This issue tracker here is only for BBB development related issues. Sorry.
