### ISSUE TITLE
Unable to mute users in break-out rooms 2.3-dev alpha5

### ISSUE THREAD

**Issue by markginter31** [bigbluebutton/bigbluebutton#11290]
I cannot find a way to mute users once they have been assigned to a break out room. Clicking on their icon shows no option for muting.  I am the moderator and assign myself to the breakout room.  I also noticed there are no room-locking options in break-out rooms?  Learning as I go :)

**Comment by antobinary** [comment]
Duplicate of https://github.com/bigbluebutton/bigbluebutton/issues/11065
