### ISSUE TITLE
bbb-record --rebuild <internal-ID> produces recording without sound

### ISSUE THREAD

**Issue by myymi** [bigbluebutton/bigbluebutton#11295]
While processing initially unrecorded raw material to the recording, outcome is left without sound. There is no sound on either presentation nor podcast. Links appear and presentation is otherwise OK.
When checking raw material directory, there is audio file present in the .opus format. 
Normal recording process (i.e. user pushes button) produces correct recording with sound and everything.
We're using BBB 2.2.3, upgraded to the latest, Greenlight frontend and Scalelite load balancer. 
We also use TURN server, but that shouldn't matter for this problem.
Which logs should I check to get the idea of whats going on with sound?

**Comment by basisbit** [comment]
For support requests, please use the [forum / mailing list](https://groups.google.com/forum/#!forum/bigbluebutton-setup). This issue tracker here is only for BBB development related issues. Sorry.

**Comment by myymi** [comment]
I'm sorry, but this is not support question but issue report. I cannot point out previous versions where this bbb-record --rebuild worked correctly, but its not working on current version. 
This last question is merely question for instructions, which logs are relevant to add to report.
Please reopen and check whether this situation is repeatable. Our installation is installed using bbb-install script.
