### ISSUE TITLE
A Volume Control for each single User

### ISSUE THREAD

**Issue by DeSchmiddi** [bigbluebutton/bigbluebutton#11301]
**Is your feature request related to a problem? Please describe.**
Its quite problematic when your presenter is quite silent and then one of the participants says something, but he has a normal volume, which is does very loud and earrape-y

**Describe the solution you'd like**
I'd like to see a dedicated volume control for each single user. Since that would need much more server capacity, it'd make sense to move the mixer to the client rather than the server, this is optional though.

**Describe alternatives you've considered**
I've tried working with the normal volume, but then I cant hear other users who are more quiet. Ive also tried to adjust each stream of the users on my own, but that's not possible. Why? Because the mixer is on the server and not on the client.

**Additional context**
-

**Comment by JimKnoxx** [comment]
This is probably the single most requested feature from our users.

Also there was an High Priority issue from 2015, which was closed, probably due to a bug with the bot and never reopend:
https://github.com/bigbluebutton/bigbluebutton/issues/1043
