### ISSUE TITLE
Firefox: Screensharing fails if participating without microphone

### ISSUE THREAD

**Issue by werk21** [bigbluebutton/bigbluebutton#11309]
**Describe the bug**
If a user participates without microphone and tries to share the screen with firefox the sharing will fail without error-message.

**To Reproduce**
1. Start Room in Firefox
2. Click on 'Listen only' (dont know the english term, in german it is "Nur zuhören")
2. Click on 'Start Screenshare' (dont know the english term, in german it is "Bildschirm freigeben")
4. Choose what you want to share
5. All looks like you a sharing - but the screen is not shared

**Expected behavior**
The shared screen appears in own and participant's browsers or an error-message occurs.

**Actual behavior**
It looks like you are sharing your screen - but the screen is not shown in your or participant's browsers.

**Screenshots**
nope.

**BBB version (optional):**
BigBlueButton Server 2.2.31 (2321) installed on Ubuntu 16.04 via bbb-install

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Mozilla Firefox 
 - Version: 85.0 and ESR 78.7.0

**Additional context**
Yes, the windows firewall is open. If participating with microphone the screen sharing works.

**Comment by prlanzarin** [comment]
Can you please try reproducing this in test.bigbluebutton.org?
If you're able to, please attach console logs.

Wasn't able to reproduce: Firefox 85, 78 ESR; Windows 10, Debian buster.

**Comment by werk21** [comment]
Hi @prlanzarin 

I can confirm that test.bigbluebutton.org works fine and I could not reproduce, too.

On several of our customer's servers we have this problem.
We enabled enableMultipleKurentos. Can this cause the problem?

**Comment by prlanzarin** [comment]
>  We enabled enableMultipleKurentos. Can this cause the problem?

Not if everything is properly configured.
test.bigbluebutton.org runs with that enabled AFAIK.
Can you please run the following tests so I can ascertain whether the Kurento DTLS certs are misconfigured:
Please run the steps **in order**. Tell me what fails in which tX.
t1:
  - Enable camera
  - Enable screen sharing
  
t2:
  - Enable screen sharing
  - Enable camera

**Comment by lonesomewalker** [comment]
Funny thing is, one of our clients also has this issue, but we are not able to reproduce that on any machine (Win7, Win8, Win10) :-/

**Comment by prlanzarin** [comment]
Closing due to being unable to reproduce and lack of feedback.
If it's reproducible or you have more data on this, please ping and I'll re-open the issue.
