### ISSUE TITLE
Error 1002/1007, CGNAT and Providers, IPv6

### ISSUE THREAD

**Issue by runout-at** [bigbluebutton/bigbluebutton#11303]
This might not be directly a bug inside BBB but we got stuck on this for weeks and want to report it just for reference for other people as providers are starting to make changes on customer lines which lead to this problem. Line-Providers try to blame BBB or the BBB-provider for this.

Trying to use Microphone or screensharing gives Error 1002/1007 in some combination of specific setups of client lines.

As providers are running out on IPv4 addresses the start to use Carrier Grade NAT (CGNAT) to reuse IPv4 addresses and start migration to IPv6. CGNAT is actually a pain... (just search for more information in the net) and misconfiguration is done easily.

If your BBB server is IPv6 ready, you probably will run into problems in such a scenario.

It was not easy (for me as a small company working for a private school in Vienna/Austria) to convince the big providers (especially Magenta) to accept that the problem is on there side. But now we found the right contacts.

The customer support of the providers will disable CGNAT if necessary. You have to use the right terms so they can find it in there knowledge base. They do not know about webrtc and are obsessed by working speedtests.

- Magenta Austria: "change to IPv4-only"
- A1/Telekom Austria "remove CGNAT"

**Comment by basisbit** [comment]
@runout-at We have many users that participate in sessions while using DualStack Lite without a problem - please make sure you have set up enough TURN+STUN servers as described here: https://docs.bigbluebutton.org/2.2/setup-turn-server.html

**Comment by runout-at** [comment]
My setup has its own TURN+STUN servers - there is no problem with that.

We already did tests with the same client machines on different lines or mobile connections and in the end the only change which solves the problems is when the providers remove CGNAT.

Maybe they will find a different configuration for the CGNAT which works. The problem can be specific to the setup or even to the firmware of the used hardware. This was confirmed by the providers.

**Comment by basisbit** [comment]
@runout-at could you please add your coturn server configuration as well as the content of `/usr/share/bbb-web/WEB-INF/classes/spring/turn-stun-servers.xml` here? Is there anything unusual in the coturn service log? Also, can you reproduce the problem on senfcall.de or https://demo.bigbluebutton.org/ ?
Nowadays, you just have to expect CGNAT setups which load-balance different connections on different outbound IP addresses - which causes problems when not using TURN+STUN.

**Comment by runout-at** [comment]
the problem is, I don't have such a connection myself, that's why it is hard to do all this tests. The lines of our teachers are fixed already by there providers.

One interesting fact is, that some of the teachers had no problems until this problem occured. In this case we did contact the customer support and they did roll back...

If there is IPv6 available, no turn/stun server should be necessary.

on the broken lines, in firefox debugging with 'about:webrtc' gives nothing - no output at all.

**Comment by angelaki** [comment]
Got a question maybe concering the same problem: I was able to setup BBB with a TURN server. When not using TURN no client behind a nat router was able to join (unless he was configured as DMZ / all ports forwarded). But since these days everyone is using thr internet via router I must assume that all my clients will use my TURN server and i will have a heavy load on it.

How do solutions like Jitsi connect their users using only STUN servers?

**Comment by runout-at** [comment]
Is your server behind a NAT too? And what kind of NATs are involved?

The best article on this subject i could find: https://www.frozenmountain.com/developers/blog/webrtc-nat-traversal-methods-a-case-for-embedded-turn

In my case (CGNAT) the customer is behind two NAT routers. My BBB server has a public IPv4 and IPv6 without any NAT and STUN/TURN on the same machine. Native IPv6 has no NAT by design anyways.

**Comment by angelaki** [comment]
I'm testing my setup on a Microsoft Azure VM with a static IPv4. If I join via a cellphone no TURN server is required. But I never got a client to connect with a regular consumer router (while all these clients were able to use Jitsi on the same server / ip).

**Comment by lonesomewalker** [comment]
Please STOP spamming the issue tracker for your lack of knowledge.

Neither BBB nor coturn have issues in this case.
It solely depends on your setup.

Please use Google groups for this.

Thanks.

**Comment by basisbit** [comment]
For support requests, please use the [forum / mailing list](https://groups.google.com/forum/#!forum/bigbluebutton-setup). This issue tracker here is only for BBB development related issues. Sorry.

If you want to continue this issue here because you are sure everything s correctly set up according to documentation, please answer the questions from https://github.com/bigbluebutton/bigbluebutton/issues/11303#issuecomment-774036851

**Comment by runout-at** [comment]
@basisbit it's completely fine for me closing this thread. Thanks for your time!

I'm sure this is not an issue inside BBB. But admins might find this information useful for supporting their clients.

We found some info about AVM Fritzbox models causing this or a similar problems: https://www.ip-phone-forum.de/threads/kabel-fritzbox-blockiert-gewisse-udp-pakete.308076/
