### ISSUE TITLE
Audio alerts for join do not always work

### ISSUE THREAD

**Issue by apinos76** [bigbluebutton/bigbluebutton#11307]
**Describe the bug**
When setting "Audio Alerts for User Join" to on, the user is not always alerted to a user joining, especially if they are not on the BBB tab/window.
![image](https://user-images.githubusercontent.com/30633300/106923109-bd9d3680-66db-11eb-8dfd-8093bc850191.png)

**To Reproduce**
1. Set "Audio Alerts for User Join" to "On"
2. Have another user join the meeting while you are not on the BBB tab/window

**Expected behavior**
We expect the audio alert to sound when a user joins.  The is even more critical if the one who has set the alert is not on the BBB tab/window of their browser.

**Actual behavior**
When the alert is set to sound, it does not always sound.  I tested this on a Mac(OS 11.0.1), using Chrome (88.0.4324.96).
The first session I joined, set the alert and saved.  I then joined using an incognito window and got no alert.  I then joined using a safari window and got the alert.  

The second session I joined and set the alert.  I then joined, scrolled to another tab in Chrome, opened up Safari and joined.  I did not get the audio alert.

**Screenshots**

**BBB version (optional):**
BigBlueButton continually evolves. Providing the version/build helps us to pinpoint when an issue was introduced.
Example:
$ sudo bbb-conf --check | grep BigBlueButton
BigBlueButton Server 2.2.31 (1114)

**Desktop (please complete the following information):**
 - OS: Mac 11.0.1
 - Browser Chrome 
 - Version 88.0.4324.96

**Comment by mariogasparoni** [comment]
After merging #11608 you can close this issue, @antobinary
