### ISSUE TITLE
Recording of slide changes continuous even on paused/stoped recording 

### ISSUE THREAD

**Issue by svergata** [bigbluebutton/bigbluebutton#11310]
**Describe the bug**
In a processed recording slides appear in the Processed recording, that have been shown without Active Recording/ after recording was stoped/paused.

**To Reproduce**
1. Start a Recorded session
2. Click Record start in the Resulted meeting
3. Stop/pause the recording
4. upload slide and show "NonRecording Slide"
5. change slide to back to normal 
6. finish meeting

After Processing all slides will be in the resulting BBB-Record as slides-1.png and counting 
**Expected behavior**
Clean Recording without a trace of the "NonRecording Slide".

**Actual behavior**
A Recording with embedded png of "NonRecording Slide" in Hamburger Menue on the left and presence of the captured "NonRecording Slide" png in the recording location.

**Screenshots**
NaN

**BBB Versions**
2.2.31

**Comment by danielpetri1** [comment]
Addressed in #13836.
