### ISSUE TITLE
Custom join parameter userdata-bbb_custom_style_url doesnt work.

### ISSUE THREAD

**Issue by limsko** [bigbluebutton/bigbluebutton#11311]
Adding custom parameter to join URL:
userdata-bbb_custom_style_url=https%253A%252F%252Fvideo.example.com%252Fcss%252Fcustom.css
is not recognised. Same issue with userdata-bbb_custom_style.

Other parameter like userdata-bbb_auto_join_audio works fine.

**Comment by daminebenq** [comment]
Hi @limsko 
can you please tell us on what bbb version you could reproduce this ?
in my case, i couldn't reproduce this on 2.3 
```
    ✓ Custom Styles (7815ms)
    ✓ Custom Styles URL (7448ms)

Test Suites: 1 total
Tests:       2 passed, 2 total

**Comment by daminebenq** [comment]
confirming also on 2.2 latest, couldn't reproduce this.
I suggest you describe us the steps you are taking to reproduce this case, maybe you are passing something wrong to the parameters.

in my case, for `userdata-bbb_custom_style` **(1)** and `userdata-bbb_custom_style_url` `userdata-bbb_custom_style_url` **2** i'm passing these:
**(1)** `userdata-bbb_custom_style=.presentationTitle--1LT79g{display: none;}`
**(2)** `userdata-bbb_custom_style_url=https://bbb.example.com/css-test-file.css`

result **(1)**: 
![image](https://user-images.githubusercontent.com/5144311/107036653-ba1bb500-6798-11eb-80ae-b4a40846bd97.png)

result **(2)**:
![image](https://user-images.githubusercontent.com/5144311/107037503-eedc3c00-6799-11eb-8dcc-15e0318f6a4a.png)


**CSS code written in the external file:**
```
:root{--loader-bg:#000;}
.overlay--1aTlbi{
background-color:#000!important;}
body{background-color:#000!important;}
.presentationTitle--1LT79g{display: none;}
.navbar--Z2lHYbG{display:none;}
.actionsbar--Z1ant6U{display:none;}
```

**Comment by limsko** [comment]
@daminebenq Thanks for fast reply. I already know what I was doing wrong. I encoded the url parameter twice. Problem solved and everything works fine. My bad.

`function bigbluebuttonbn_get_join_url($meetingid, $username, $pw, $logouturl, $configtoken = null,
        $userid = null, $clienttype = BIGBLUEBUTTON_CLIENTTYPE_FLASH) {
    $data = ['meetingID' => $meetingid,
              'fullName' => $username,
              'password' => $pw,
              'logoutURL' => $logouturl,
              'userdata-bbb_auto_join_audio' => false,
              'userdata-bbb_custom_style_url' => 'https://example.com/custom.css',
              //'userdata-bbb_custom_style_url' => urlencode('https://example.com/custom.css') // <- mistake.
    ];`

Later this url data is encoded with http_build_query.
