### ISSUE TITLE
BigBlueButton 2.2.31 cause 1007 error after initial successful join.

### ISSUE THREAD

**Issue by parsa25eng** [bigbluebutton/bigbluebutton#11316]
**Describe the bug**
Recently I have installed bbb 2.2.31 on ubuntu 16.04 with 12 core CPU and 24 GB Ram based on the instructions of [this](https://docs.bigbluebutton.org/2.2/install.html).
When I try to join a meeting for the first time, everything is O.K. but after that, join with a microphone cause 1007 error. I have some installs of bbb on some other servers with the same configuration working properly. On this situation, "listen only" works properly.
My server has a public IP address and there is no NAT in the configuration. Also, all UDP ports have been opened.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome[Version 88.0.4324.150-last version]
 - Version [2.2.31]

**Additional context**
here you can see the summary of the server configuration:
      `BigBlueButton Server 2.2.31 (2307)
                          Kernel version: 4.15.0-133-generic
                            Distribution: Ubuntu 16.04.7 LTS (64-bit)
                                  Memory: 24681 MB
                               CPU cores: 12
    
    /usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties (bbb-web)
           bigbluebutton.web.serverURL: my_fqdn_https_url
                    defaultGuestPolicy: ALWAYS_ACCEPT
                     svgImagesRequired: true
    
    /etc/nginx/sites-available/bigbluebutton (nginx)
                           server_name: my_fqdn
                                  port: 80, [::]:80
                                  port: 443 ssl
    
    /opt/freeswitch/etc/freeswitch/vars.xml (FreeSWITCH)
                           local_ip_v4: my_valid_ip
                       external_rtp_ip: my_valid_ip
                       external_sip_ip: stun:stun.freeswitch.org
    
    /opt/freeswitch/etc/freeswitch/sip_profiles/external.xml (FreeSWITCH)
                            ext-rtp-ip: $${external_rtp_ip}
                            ext-sip-ip: $${external_rtp_ip}
                            ws-binding: my_valid_ip:5066
                           wss-binding: :7443
    
    /usr/local/bigbluebutton/core/scripts/bigbluebutton.yml (record and playback)
                         playback_host: my_fqdn
                     playback_protocol: https
                                ffmpeg: 4.2.4-1ubuntu0.1bbb1~16.04.1
    
    /etc/bigbluebutton/nginx/sip.nginx (sip.nginx)
                            proxy_pass: my_valid_ip
                              protocol: http
    
    /usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml (Kurento SFU)
                            kurento.ip: my_valid_ip
                           kurento.url: ws://127.0.0.1:8888/kurento
                        kurento.sip_ip: my_valid_ip
                        localIpAddress: my_valid_ip
                   recordScreenSharing: true
                         recordWebcams: true
                      codec_video_main: VP8`

**Comment by prlanzarin** [comment]
Hi.

0 - Can you please direct this question to the bigbluebutton-setup mailing list since it relates more to setup support than it does to development itself?
1 - Prefer bbb-install for installation instead of the step-by-step guide.
2 - `external_sip_ip: stun:stun.freeswitch.org` please change that to something else; either your own coturn instance or just put the server's public IP in there.
3 - Not clear if you set up your own coturn instance, how, in which OS and if you configured it in bbb-web.

Follow up in the mailing list and more folks might be able to help you through it.
