### ISSUE TITLE
Set an audio threshold serverside

### ISSUE THREAD

**Issue by Richardvi** [bigbluebutton/bigbluebutton#11313]
After some extensive testing we noticed that BBB has far better audio-quality than MS Teams. Which is really good, compliments for that!

But, we also noticed that our microphones were way more sensitive. If someone moved on his chair, moved the mouse on his/her desk, the sound was immediately picked up by BigBlueButton. You can see this because the names appear top left from the people that have active audio streams.

So even more than in Teams, it's really important to mute yourself if you are not contributing to the conversation. 

However, we were wondering if the minimal audiolevel could be adjusted. A threshold so to speak that makes sure only voices are captured and the (very faint) sounds surrounding someone are not picked up.

Is this easy to implement? And yes, you could do this on all clients of course. But if it could be done serverside that would be great.

Thanks anyway to the makers for this excellent product.

**Comment by PhMemmel** [comment]
You might wanna play around with the parameter `energy-level` in `/opt/freeswitch/conf/autoload_configs/conference.conf.xml`, just read the corresponding documentation of freeswitch. This should be exactly that server side setting you're looking for.

BTW: Usually the default settings of BBB are pretty good overall for most of the people. You might want to consider turning down your microphone sensitivity on client side first.

Please close this issue afterwards as the requested feature is already available.

**Comment by Richardvi** [comment]
Thanks and apologies for opening this...
