### ISSUE TITLE
Cannot hear audio after enabling notifications (2.3-alpha-5)

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#11318]
**Describe the bug**
Got an exception when saving settings.

**To Reproduce**
1. Go to Settings
2. Click on Notifications
3. Select both Popup Alerts and Audio Alerts for user join

**Actual behavior**
If you join audio, open setting > Notifications and click Save... the user can no longer hear audio, but the UI will work as though they are still in audio"

**Expected behavior**
Audio would still be played, alerts would be triggered too

## Version
Build 2.3-alpha-5

**Comment by hiroshisuga** [comment]
could be related to #11071

**Comment by antobinary** [comment]
When I reproduce this locally I only see errors in the console but no visible errors within the client. Could anyone confirm this to be the case?
I do see the same error when I open shared notes, again only within the console

**Comment by mariogasparoni** [comment]
I am able to reproduce this on chrome 88. This happens if you select any option.
