### ISSUE TITLE
Enabling secret polls / surveys, also allow the poll/survey starter to vote

### ISSUE THREAD

**Issue by lonesomewalker** [bigbluebutton/bigbluebutton#11326]
**Is your feature request related to a problem? Please describe.**
Currently it is not possible to vote secretly, the poll starter is able to see who voted.
Also the poll starter can't vote himself.

**Describe the solution you'd like**
An option to enable secret voting, which also shows the users that the poll is done in secret mode (UX).
Also the possibility that a poll starter is allowed to vote.
Currently the moderator who starts this can't express his opinion.

**Comment by basisbit** [comment]
Duplicate of #9524

**Comment by cyfrax** [comment]
I haven't found an enhancement issue for "also allow poll starter to vote", I'll add it as a comment to #9524
