### ISSUE TITLE
Optimize bbb for written exams

### ISSUE THREAD

**Issue by Struthiomimus** [bigbluebutton/bigbluebutton#11320]
**Is your feature request related to a problem? Please describe.**
I'm a lecturer and in the current situation my students do their written exams at home. I supervise them with the help of bbb. There are two typical situations:
1. A student wants to ask me sth.
2. I want to ask a student to show me his/her identity card to verify that the registered person is actually doing the exam

**Describe the solution you'd like**
For the purposes 1. and 2. it would be a great feature for the moderator to enable/disable the participants headphones/speakers individually.

**Describe alternatives you've considered**
Private chat would work, but seems to be unhandy.

**Additional context**

**Comment by lonesomewalker** [comment]
Just look at your bigbluebutton.properties. Already possible.

**Comment by Struthiomimus** [comment]
Sorry, I can not find. Could you send a screenshot? I have to use BBB via Moodle.
Thank you very much

**Comment by demogorgi** [comment]
@lonesomewalker, I can't find this option either. Can you kindly drop a line how this has to look like? I would expect someting like
`lockSettingsDisableSpeaker=true`
or
`lockSettingsDisableAudio=true`
