### ISSUE TITLE
Zabbix-agent tries to uninstall bbb(2.3 dev) package in the installation step 

### ISSUE THREAD

**Issue by cod3r0k** [bigbluebutton/bigbluebutton#11329]
When I want to install the zabbix-agent on my BBB (2.3 dev) server, a message show me that the agent wants to remove bbb-web , bbb-html5 and so on. What's happened there? @ffdixon @antobinary

**Comment by ffdixon** [comment]
Just tried installing `zabbix-agent` on BigBlueButton 2-3-alpha-6 (soon to be released) and it worked.

```
root@droplet-:~# apt-get install zabbix-agent
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  zabbix-agent
0 upgraded, 1 newly installed, 0 to remove and 4 not upgraded.
Need to get 197 kB of archives.
After this operation, 664 kB of additional disk space will be used.
Get:1 http://mirrors.digitalocean.com/ubuntu bionic/universe amd64 zabbix-agent amd64 1:3.0.12+dfsg-1 [197 kB]
Fetched 197 kB in 0s (6424 kB/s)       
Selecting previously unselected package zabbix-agent.
(Reading database ... 215172 files and directories currently installed.)
Preparing to unpack .../zabbix-agent_1%3a3.0.12+dfsg-1_amd64.deb ...
Unpacking zabbix-agent (1:3.0.12+dfsg-1) ...
Setting up zabbix-agent (1:3.0.12+dfsg-1) ...

Creating config file /etc/zabbix/zabbix_agentd.conf with new version
Created symlink /etc/systemd/system/multi-user.target.wants/zabbix-agent.service → /lib/systemd/system/zabbix-agent.service.
Processing triggers for man-db (2.8.3-2ubuntu0.1) ...
Processing triggers for ureadahead (0.100.0-21) ...
Processing triggers for systemd (237-3ubuntu10.44) ...

root@droplet-:~# cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.5 LTS"
```

Can you post the output from your console when you try to install `zabbix-agent`.

**Comment by cod3r0k** [comment]
> Just tried installing `zabbix-agent` on BigBlueButton 2-3-alpha-6 (soon to be released) and it worked.
> 
> ```
> root@droplet-:~# apt-get install zabbix-agent
> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> The following NEW packages will be installed:
>   zabbix-agent
> 0 upgraded, 1 newly installed, 0 to remove and 4 not upgraded.
> Need to get 197 kB of archives.
> After this operation, 664 kB of additional disk space will be used.
> Get:1 http://mirrors.digitalocean.com/ubuntu bionic/universe amd64 zabbix-agent amd64 1:3.0.12+dfsg-1 [197 kB]
> Fetched 197 kB in 0s (6424 kB/s)       
> Selecting previously unselected package zabbix-agent.
> (Reading database ... 215172 files and directories currently installed.)
> Preparing to unpack .../zabbix-agent_1%3a3.0.12+dfsg-1_amd64.deb ...
> Unpacking zabbix-agent (1:3.0.12+dfsg-1) ...
> Setting up zabbix-agent (1:3.0.12+dfsg-1) ...
> 
> Creating config file /etc/zabbix/zabbix_agentd.conf with new version
> Created symlink /etc/systemd/system/multi-user.target.wants/zabbix-agent.service → /lib/systemd/system/zabbix-agent.service.
> Processing triggers for man-db (2.8.3-2ubuntu0.1) ...
> Processing triggers for ureadahead (0.100.0-21) ...
> Processing triggers for systemd (237-3ubuntu10.44) ...
> 
> root@droplet-:~# cat /etc/lsb-release 
> DISTRIB_ID=Ubuntu
> DISTRIB_RELEASE=18.04
> DISTRIB_CODENAME=bionic
> DISTRIB_DESCRIPTION="Ubuntu 18.04.5 LTS"
> ```
> 
> Can you post the output from your console when you try to install `zabbix-agent`.
Thanks, The below image shows that the installation process has some conflict dependencies
![image](https://user-images.githubusercontent.com/36899025/107232600-d63c8200-6a36-11eb-800c-05d52bb4f5db.png)

**Comment by basisbit** [comment]
did you maybe already mark those for deletion previously?

**Comment by antobinary** [comment]
Please comment if this is still an issue and we'll reopen
