### ISSUE TITLE
Order of End-meeting and Logout in the navigation bar

### ISSUE THREAD

**Issue by hiroshisuga** [bigbluebutton/bigbluebutton#11324]
**Describe the bug**
Currently the item "end meeting" comes earlier than the item "logout" in the navigation bar. Is there any good reason?

**To Reproduce**
1. start a meeting
2. click the three-dot on the up-right
3. Look at the dropdown

**Expected behavior**
I prefer to have "End-meeting" below "Logout" because I feel like ending a meeting is kind of a final option to the administrator. It may be confusing for many users.

**Actual behavior**
As stated above.

**Comment by antobinary** [comment]
Closing based on the discussion in https://github.com/bigbluebutton/bigbluebutton/pull/11325
