### ISSUE TITLE
Picture in Picture for Safari

### ISSUE THREAD

**Issue by iMonZ** [bigbluebutton/bigbluebutton#11332]
A feature for using BigBlueButton in PiP mode.
This feature would allow multitasking on Safari as example on the iPad when you are still able to see the presentation or the screen sharing!

**Comment by basisbit** [comment]
please fill in the issue template which you deleted when writing this issue here. You can copy it from clicking the buton for creating another issue.
Please also include screenshots of other apps which support this already and what exactly you suggest the solution should look like.
