### ISSUE TITLE
Breakout Room panel doesn't show "Return Audio" after reopening the panel

### ISSUE THREAD

**Issue by NicoKnebel** [bigbluebutton/bigbluebutton#11333]
**Describe the bug**
If you close the breakout rooms panel, after joining the audio of a breakout room and reopen it, it won't show, that you are still connected to a room. Instead you will be shown the option to join a room. 

**To Reproduce**
1. Create a breakout room
2. "Join Audio" of one of the rooms
3. Click on "Breakout Rooms" to close the panel
4. Click on "Breakout Rooms" to open the panel

**Expected behavior**
Display the options "Join room | Return audio" on the connected room.

**Actual behavior**
Display the options "Join room | Join audio" on the connected room.

**BBB version (optional):**
BigBlueButton Server 2.2.29 (2244)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Firefox and Chrome

**Comment by basisbit** [comment]
What do you mean by "Return audio"? A Breakout Room is basically just another BBB room, thus audio is handled separately for each of the rooms (there exist already issues for improving that).

Also, please update your BBB server.

**Comment by PhMemmel** [comment]
It's about the feature that you, as moderator, can fast-join the listen-only (kurento) audio stream of the breakout rooms via the breakout room panel, even without actually joining the rooms themselves:
![grafik](https://user-images.githubusercontent.com/65113153/107476941-26baf900-6b77-11eb-804b-0a4e16229174.png)

I can confirm that this is an issue in 2.2.31 (test.bigbluebutton.org) and on 2.3-alpha6 (current test23.bigbluebutton.org)

It indeed doesn't track the audio status of the moderator in the breakout rooms which, for better UX, should probably be fixed (for both freeswitch and kurento status ideally).

**Comment by antobinary** [comment]
@mariogasparoni can we close this now?

**Comment by mariogasparoni** [comment]
@antobinary we can now close it. 
#11587 fixes this
