### ISSUE TITLE
Original Sound

### ISSUE THREAD

**Issue by Braehler** [bigbluebutton/bigbluebutton#11331]
**Is your feature request related to a problem? Please describe.**
This is related to the way how BBB handles the sound. The sound is great so far, but in some cases, espacially on long voice/ singing sounds the sound is a little crackly/ cut of, because they are interpreted as "background" noise

**Describe the solution you'd like**
A button in the settings tab for using "original sound". maybe in some way like this:
Click the Audio tab.
 check Show in-meeting option to "Enable Original Sound" from microphone.
(Optional) Check High fidelity music mode.
(Optional) Uncheck Echo cancellation.
(Optional) Uncheck Stereo audio
 Zoom already has this function.

**Describe alternatives you've considered**
Currently this is handled by a workaround by sending audio files (of singing voices etc) via a cloud link 

**Additional context**

**Comment by hostbbb** [comment]
So the getuserMedia sets the browser constraints on the call setup to freeswitch.   so browser noise suppression, echo cancelation can be set only before the audio peer connection is made,  any change would require a new request/reconnect of audio after setting constraints. (don't think this can be turned on/off mid connection, maybe browsers can handle would need testing)   

Safari does not yet support stereo in webrtc connections.

Zoom is doing this all in native low level clients, be need to rely on FireFox, Chrome, Safari capabilities.

Stereo, requires you config freeswitch mod_conference to mix in stereo.   Firefox works in browser, chrome currently requires a hack to the browser sip.js (set local sdp with hacked sdp before sending offer).  issue 8133 in chromium i think.     

Stereo will also add 5-10% more cpu to mix users in conferencing, and the recordings will be twice the size.  Not an issue, just reduces the concurrent users that can mix for a given number of cores..

**Comment by ann0see** [comment]
I also support this feature request! Audio quality in BBB is quite good (if people have a good internet connection). Jitsi supports this feature too (at least in some way). Found this: https://community.jitsi.org/t/music-mode-for-jitsi-original-sound-option/32578/3

**Comment by prlanzarin** [comment]
https://github.com/bigbluebutton/bigbluebutton/pull/11143
https://github.com/bigbluebutton/bigbluebutton/pull/11206

**Comment by antobinary** [comment]
See the links in the post above, this is resolved
