### ISSUE TITLE
[2.2 & 2.3] Uncaught ReferenceError: checkform is not defined

### ISSUE THREAD

**Issue by daminebenq** [bigbluebutton/bigbluebutton#11348]
```
(index):58 Uncaught ReferenceError: checkform is not defined
    at HTMLFormElement.onsubmit ((index):58)
```

check at 00:03 seconds
https://user-images.githubusercontent.com/5144311/107359781-df1f6900-6ab3-11eb-8e42-9b290ac03939.mp4

**Comment by antobinary** [comment]
I would think this is from bbb-demo, not html5 client
