### ISSUE TITLE
worker_connections are not enough while connecting to upstream & nginx return 50x

### ISSUE THREAD

**Issue by cod3r0k** [bigbluebutton/bigbluebutton#11347]
Hi @ffdixon & @antobinary , When the users goes upper then 100 users (in different rooms), the BBB-dev2.3-alpha5 get me an error in the `/var/log/nginx/errors.log`.

I didn't have this issue in BBB-2.2 and when I want to test the BBB2.3-dev-alpha5, I have some problem in joining and also screen sharing.  I think the BBB2.3 must be better than 2.2 in handling much users. 
I put some error logs in the below lines, Thanks.

```
2021/02/09 11:13:18 [error] 1926#1926: *100478 open() "/var/www/nginx-default/50x.html" failed (2: No such file or directory), client: xxxxxxxxxxxxxxx, server: xxxxxxxxxxxxxxx, request: "GET /html5client/1/resources/sounds/LeftCall.mp3 HTTP/1.1", upstream: "http://127.0.0.1:4000/html5client/1/resources/sounds/LeftCall.mp3", host: "xxxxxxxxxxxxxxx", referrer: "https://xxxxxxxxxxxxxxx/html5client/1/join?sessionToken=pwshphygtpvwywre"
2021/02/09 11:13:19 [alert] 1926#1926: 768 **worker_connections are not enough**
2021/02/09 11:13:19 [alert] 1926#1926: 768 **worker_connections are not enough**
2021/02/09 11:13:19 [alert] 1926#1926: 768 **worker_connections are not enough**
2021/02/09 11:13:20 [alert] 1926#1926: *100483 768 worker_connections are not enough while connecting to upstream, client: 46.41.207.196, server: xxxxxxxxxxxxxxx, request: "GET /ws?sessionToken=pwshphygtpvwywre HTTP/1.1", subrequest: "/bigbluebutton/connection/checkAuthorization", upstream: "http://127.0.0.1:8090/bigbluebutton/connection/checkAuthorization", host: "xxxxxxxxxxxxxxx"
2021/02/09 11:13:20 [error] 1926#1926: *100483 open() "/var/www/nginx-default/50x.html" failed (2: No such file or directory), client: xxxxxxxxxxxxxxx, server: xxxxxxxxxxxxxxx, request: "GET /ws?sessionToken=pwshphygtpvwywre HTTP/1.1", subrequest: "/50x.html", upstream: "http://127.0.0.1:8090/bigbluebutton/connection/checkAuthorization", host: "xxxxxxxxxxxxxxx"
2021/02/09 11:13:20 [error] 1926#1926: *100483 auth request unexpected status: 404, client: xxxxxxxxxxxxx, server: xxxxxxxxxxxxxxx, request: "GET /ws?sessionToken=pwshphygtpvwywre HTTP/1.1", host: "xxxxxxxxxxxxxxx"
2021/02/09 11:13:20 [error] 1926#1926: *100483 open() "/var/www/nginx-default/50x.html" failed (2: No such file or directory), client: xxxxxxxxxxxxxxx, server: xxxxxxxxxxxxxxx, request: "GET /ws?sessionToken=pwshphygtpvwywre HTTP/1.1", host: "xxxxxxxxxxxxxxx"
2021/02/09 11:13:20 [alert] 1926#1926: *100486 768 worker_connections are not enough while connecting to upstream, client: xxxxxxxxxxxxxxx, server: xxxxxxxxxxxx, request: "GET /html5client/1/resources/sounds/LeftCall.mp3 HTTP/1.1", upstream: "http://127.0.0.1:4000/html5client/1/resources/sounds/LeftCall.mp3", host: "xxxxxxxxxxxx", referrer: "https://xxxxxxxxxxxx/html5client/1/join?sessionToken=pwshphygtpvwywre"
```

also we have :

```
2021/02/09 11:12:43 [error] 1926#1926: *100362 open() "/var/www/nginx-default/50x.html" failed (2: No such file or directory), client: 31.193.159.32, server: xxxxxxxxxxxxxxx, request: "GET /html5client/1/resources/sounds/ScreenshareOff.mp3 HTTP/1.1", upstream: "http://127.0.0.1:4000/html5client/1/resources/sounds/ScreenshareOff.mp3", host: "xxxxxxxxxxxxxxx", referrer: "https://xxxxxxxxxxxxxxx/html5client/1/join?sessionToken=wbfr5hatfwwltsmy"
2021/02/09 11:12:43 [alert] 1926#1926: 768 worker_connections are not enough
2021/02/09 11:12:43 [alert] 1926#1926: 768 worker_connections are not enough
2021/02/09 11:12:44 [alert] 1926#1926: 768 worker_connections are not enough
2021/02/09 11:12:44 [crit] 1926#1926: *100367 SSL_do_handshake() failed (SSL: error:14209102:SSL routines:tls_early_post_process_client_hello:unsupported protocol) while SSL handshaking, client: xxxxxxxxxxxxx, server: 0.0.0.0:443
2021/02/09 11:12:44 [crit] 1926#1926: *100375 SSL_do_handshake() failed (SSL: error:14209102:SSL routines:tls_early_post_process_client_hello:unsupported protocol) while SSL handshaking, client: xxxxxxxxxxxxx, server: 0.0.0.0:443
2021/02/09 11:12:44 [alert] 1926#1926: 768 worker_connections are not enough
2021/02/09 11:12:44 [alert] 1926#1926: 768 worker_connections are not enough
2021/02/09 11:12:47 [alert] 1926#1926: *100412 768 worker_connections are not enough while connecting to upstream, client: 172.20.0.2, server: xxxxxxxxxxxxxxx, request: "GET /bigbluebutton/api/getMeetings?checksum=8fbeeb50dfe06f5c56b5b11e5cedbec659209aa6 HTTP/1.1", upstream: "http://127.0.0.1:8090/bigbluebutton/api/getMeetings?checksum=8fbeeb50dfe06f5c56b5b11e5cedbec659209aa6", host: "xxxxxxxxxxxxxxx"
2021/02/09 11:12:47 [error] 1926#1926: *100412 open() "/var/www/nginx-default/50x.html" failed (2: No such file or directory), client: 172.20.0.2, server: xxxxxxxxxxxxxxx, request: "GET /bigbluebutton/api/getMeetings?checksum=8fbeeb50dfe06f5c56b5b11e5cedbec659209aa6 HTTP/1.1", upstream: "http://127.0.0.1:8090/bigbluebutton/api/getMeetings?checksum=8fbeeb50dfe06f5c56b5b11e5cedbec659209aa6", host: "xxxxxxxxxxxxxxx"
2
```

**Comment by basisbit** [comment]
@cod3r0k nginx will create 768 times CPU threads amount of worker_connections at most. That should be enough, except when your server is under DDoS. Even on our servers with 600+ users in bbb ~2.2.32 we do not run in such limits.

Could you please check that `worker_processes auto;` is set in `/etc/nginx/nginx.conf` on bbb2.3-alpha6? If it is set, please confirm here. Also, I'd suggest you to add some connection-limits in iptables/nftables or add rate-limiting to your nginx setup and see if that solved the problem for you (if it does, then Denial of Service on your server seems to be the problem).

However, on the typical server sizes that BBB runs on, setting `worker_connections 10000;` (or much higher) in `/etc/nginx/nginx.conf` should be no problem at all. However, this would make it easier for a Denial of Service attacker to overload NodeJS (nginx can easily handle more than your network port, when configured properly).

**Comment by cod3r0k** [comment]
> @cod3r0k nginx will allow 768 times CPU-threads-count amount of worker_connections at most. That should be enough, except when your server is under DDoS. Even on our servers with 600+ users in bbb ~2.2.32 we do not run in such limits.
> 
> Could you please check that `worker_processes auto;` is set in `/etc/nginx/nginx.conf` on bbb2.3-alpha6? If it is set correctly by default, please confirm here. Also, I'd suggest you to add some connection-limits in iptables/nftables or add rate-limiting to your nginx setup and see if that solved the problem for you (if it does, then Denial of Service on your server seems to be the problem).
> 
> However, on the typical server sizes that BBB runs on, setting `worker_connections 10000;` (or much higher) in `/etc/nginx/nginx.conf` should be no problem at all. However, this would make it easier for a Denial of Service attacker to overload NodeJS (nginx can easily handle more than your network port, when configured properly).

Dear @basisbit , I take a screenshot from `/etc/nginx/nginx.conf` as below
![image](https://user-images.githubusercontent.com/36899025/107505726-5f2bf880-6bb2-11eb-9763-3a0120e1535c.png)


You said that I might be under the DDoS. How can I check this?

I can't update to the latest version because as @antobinary and @ffdixon know, the alpha6 have some problems in UI and users might crash for different reason like as clearing the chat and so on. 

Could you suggest me what should I do now? because tomorrow again we have a meeting and I'm afraid to be update to the BBB2.3-dev alpha6.

Thanks a lot.

**Comment by basisbit** [comment]
what CPU does your BBB server use? If it is a VM, how many CPU threads / cores does it have assigned?
Do you have any monitoring metrics of inbound and outbound network traffic of your server's ethernet port?
You can try setting `worker_connections 4000;` in `/etc/nginx/nginx.conf`.
Also please post a screenshot of `htop` on that server when the problem happens again or when many people are using the server at the same time and you expect it to be close to its limit.

**Comment by prlanzarin** [comment]
@cod3r0k I've stumbled in an issue where `auto` would pick the count as `1` in weirdly virtualized environments. Not sure it's the same thing, but I saw it happening twice already when load testing new providers.

 I'd check whether it's picking 1 or not. If it is, you'll have to bump the number of workers by yourself.

**Comment by basisbit** [comment]
> I'd check whether it's picking 1 or not. If it is, you'll have to bump the number of workers by yourself.

That would be setting `worker_processes X;` (X being the amount of CPU core threads) in `/etc/nginx/nginx.conf`. This is safe to do. If you are not sure, just set it to `worker_processes 8;`
After changing the nginx conf, run `service nginx restart` for it to apply the changes.

**Comment by cod3r0k** [comment]
> what CPU does your BBB server use? If it is a VM, how many CPU threads / cores does it have assigned?
> Do you have any monitoring metrics of inbound and outbound network traffic of your server's ethernet port?
> You can try setting `worker_connections 4000;` in `/etc/nginx/nginx.conf`.
> Also please post a screenshot of `htop` on that server when the problem happens again or when many people are using the server at the same time and you expect it to be close to its limit.

Dear @basisbit , In one of our servers which this happened, we have a VM with 8 cores (each of them up to 2297.339MHz). I put more information in the following lines.

```
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              8
On-line CPU(s) list: 0-7
Thread(s) per core:  1
Core(s) per socket:  1
Socket(s):           8
NUMA node(s):        1
Vendor ID:           GenuineIntel
CPU family:          6
Model:               63
Model name:          Intel(R) Xeon(R) CPU E5-2650 v3 @ 2.30GHz
Stepping:            0
CPU MHz:             2297.339
BogoMIPS:            4594.67
Hypervisor vendor:   VMware
Virtualization type: full
L1d cache:           32K
L1i cache:           32K
L2 cache:            256K
L3 cache:            25600K
NUMA node0 CPU(s):   0-7
```

I have a more successful experience with the same configuration in 2.2 but in 2.3-alpha5, I have this bad experience!

Hope it was solved ASAP.

Do you prefer to me that I set `worker_processes 8` ? (with this configuration, what would happen to the number of my users? I mean, I must have at least 110 users in different rooms tomorrow in that server. Is it enough (`worker_processes 8`)?

**Comment by prlanzarin** [comment]
> Do you prefer to me that I set worker_processes 8 ? (with this configuration, what would happen to the number of my users? I mean, I must have at least 110 users in different rooms tomorrow in that server. Is it enough (worker_processes 8)?

Setting worker_procs to 8 will do exactly what auto was _supposed_ to do, so the only thing that you'll be doing is enforcing something that would be done in a normal scenario.
So yeah, you should set it and see how it goes.

**Comment by cod3r0k** [comment]
> > Do you prefer to me that I set worker_processes 8 ? (with this configuration, what would happen to the number of my users? I mean, I must have at least 110 users in different rooms tomorrow in that server. Is it enough (worker_processes 8)?
> 
> Setting worker_procs to 8 will do exactly what auto was _supposed_ to do, so the only thing that you'll be doing is enforcing something that would be done in a normal scenario.
> So yeah, you should set it and see how it goes.

Excuse me! Is it correct?
![image](https://user-images.githubusercontent.com/36899025/107519866-04040100-6bc6-11eb-9395-3398a2acd88f.png)

We have two `worker_processes ` variable. One of them is `auto` and the other in the event scope set to `8` . Is it correct?

**Comment by cod3r0k** [comment]
Dear @prlanzarin and @basisbit , I set the previoues image configuration and restart the nginx.
I create a test session and when I want to join into the session, I get stuck in the 3dots entrance page as below with some javascript error.
![image](https://user-images.githubusercontent.com/36899025/107520407-a2906200-6bc6-11eb-8a4a-521749ca8ff8.png)


I changed again to previous `worker_connections 784` and refreshing the joining session and the previous event was solved.

So, I think my main question is not related to this option. Isn't it?

**Comment by cod3r0k** [comment]
I set `worker_processes 8` and restart the nginx.
![image](https://user-images.githubusercontent.com/36899025/107521036-4e39b200-6bc7-11eb-8c2c-57d270ce3253.png)

Unfortunately, I'm getting stuck on the 3dots entrance page. 

I restore the configuration and restart nginx and this was resolved.

But I think our main question is not really related to this option. Isn't it?

**Comment by cod3r0k** [comment]
Dear @prlanzarin & @basisbit , Here is my nginx error log when I set 8 for `worker_processes`.

```
2021/02/10 02:35:29 [alert] 35257#35257: *237 8 worker_connections are not enough while connecting to upstream, client: xxxxxxxxxxxxxxx, server: xxxxxxxxxxxxxxx, request: "GET /metrics/ HTTP/1.1", upstream: "http://127.0.0.1:9688/", host: "xxxxxxxxxxxxxxx", referrer: "https://xxxxxxxxxxxxxxx:443/metrics"
2021/02/10 02:35:29 [error] 35257#35257: *237 open() "/var/www/nginx-default/50x.html" failed (2: No such file or directory), client: xxxxxxxxxxxxxxx, server: xxxxxxxxxxxxxxx, request: "GET /metrics/ HTTP/1.1", upstream: "http://127.0.0.1:9688/", host: "xxxxxxxxxxxxxxx", referrer: "https://xxxxxxxxxxxxxxx:443/metrics"
2021/02/10 02:35:35 [alert] 35257#35257: *238 8 worker_connections are not enough while connecting to upstream, client: xxxxxxxxxxxxxxx, server: xxxxxxxxxxxxxxx, request: "GET /metrics/ HTTP/1.1", upstream: "http://127.0.0.1:9688/", host: "xxxxxxxxxxxxxxx", referrer: "https://xxxxxxxxxxxxxxx:443/metrics"
2021/02/10 02:35:35 [error] 35257#35257: *238 open() "/var/www/nginx-default/50x.html" failed (2: No such file or directory), client: xxxxxxxxxxxxxxx, server: xxxxxxxxxxxxxxx, request: "GET /metrics/ HTTP/1.1", upstream: "http://127.0.0.1:9688/", host: "xxxxxxxxxxxxxxx", referrer: "https://xxxxxxxxxxxxxxx:443/metrics"
2021/02/10 02:35:40 [alert] 35257#35257: *239 8 worker_connections are not enough while connecting to upstream, client: xxxxxxxxxxxxxxx, server: xxxxxxxxxxxxxxx, request: "GET /metrics/ HTTP/1.1", upstream: "http://127.0.0.1:9688/", host: "xxxxxxxxxxxxxxx", referrer: "https://xxxxxxxxxxxxxxx:443/metrics"
2021/02/10 02:35:40 [error] 35257#35257: *239 open() "/var/www/nginx-default/50x.html" failed (2: No such file or directory), client: xxxxxxxxxxxxxxx, server: xxxxxxxxxxxxxxx, request: "GET /metrics/ HTTP/1.1", upstream: "http://127.0.0.1:9688/", host: "xxxxxxxxxxxxxxx", referrer: "https://xxxxxxxxxxxxxxx:443/metrics"
2021/02/10 02:35:41 [alert] 35257#35257: *240 8 worker_connections are not enough while connecting to upstream, client: 212.80.13.71, server: xxxxxxxxxxxxxxx, request: "GET /html5client/1/sockjs/info?cb=ggt0nxqtsl HTTP/1.1", upstream: "http://127.0.0.1:4000/html5client/1/sockjs/info?cb=ggt0nxqtsl", host: "xxxxxxxxxxxxxxx", referrer: "https://xxxxxxxxxxxxxxx/html5client/1/join?sessionToken=okwfj4wqiekiy1hq"

```

**Comment by prlanzarin** [comment]
basisbit and I suggested that you change **worker_processes** from _auto_ to **8**.

You don't need to change **worker_connections**. They're two very different things. Keep it the default (768).

**Comment by basisbit** [comment]
> But I think our main question is not really related to this option. Isn't it?

Most likely this option is exactly what you need to resolve this issue. You are running BBB in VMWare on a system with either one CPU and 10 cores or 2 CPUs and 20 cores. If it is running with 2 CPUs, then sharing memory between nginx processes that are on a different CPU can be very very slow (slow as in compared to usual CPU cache speed). Your setup has
> CPU(s):              8
On-line CPU(s) list: 0-7
Thread(s) per core:  1
Core(s) per socket:  1
Socket(s):           8
NUMA node(s):        1

Thus I would not be surprised if some nginx version update included code to detect this geometry and then reduce worker process count for best speed - which would be 1 to avoid slow memory access. In such a case, 768 worker_connections is way too little of course.

**Comment by basisbit** [comment]
@prlanzarin any objections against setting worker_connections to 4000 to better handle this here problem case by bbb default configuration?

**Comment by prlanzarin** [comment]
Don't see an issue with it. I don't have access to the packaged nginx stuff, though, so cc @ffdixon, @antobinary

**Comment by cod3r0k** [comment]
> So the problem here is that VMWare does not tell your VM the actually used CPU geometry and thus nginx probably did a not optimal assumption.

Wow, @basisbit That's a fantastic analysis!  Thanks. And what would you suggest? Do you mean I increase it to 4000 or as @prlanzarin said, I set it to 8 ?

**Comment by basisbit** [comment]
> Do you mean I increase it to 4000 or as @prlanzarin said, I set it to 8 ?

Both or any one of them should solve your problem.

**Comment by cod3r0k** [comment]
> basisbit and I suggested that you change **worker_processes** from _auto_ to **8**.
> 
> You don't need to change **worker_connections**. They're two very different things. Keep it the default (768).

Dear @prlanzarin and @basisbit , I set it to 8. but again today we have a the same problem with 109 online user.

```
2021/02/13 03:04:32 [alert] 1648#1648: 768 worker_connections are not enough
2021/02/13 03:04:32 [alert] 1648#1648: 768 worker_connections are not enough
2021/02/13 03:04:32 [alert] 1648#1648: 768 worker_connections are not enough
2021/02/13 03:04:32 [alert] 1648#1648: 768 worker_connections are not enough
2021/02/13 03:04:32 [alert] 1648#1648: 768 worker_connections are not enough
2021/02/13 03:04:32 [alert] 1648#1648: 768 worker_connections are not enough
```

**Comment by basisbit** [comment]
Did you restart nginx after the configuration change? Do you see 8 nginx child-processes in htop?

As temporary fix, set worker_connections 4000; as mentioned above, and also set `worker_rlimit_nofile 10000;` within the main context of /etc/nginx/nginx.conf

**Comment by cod3r0k** [comment]
> Did you restart nginx after the configuration change? Do you see 8 nginx child-processes in htop?
> 
> As temporary fix, set worker_connections 4000; as mentioned above, and also set `worker_rlimit_nofile 10000;` within the main context of /etc/nginx/nginx.conf . Then restart nginx again.

Yes, Also I restart the server but I don't have any well situation in tonight session. 

OK, I set new configuration which you said and will send you feedback

**Comment by cod3r0k** [comment]
> Did you restart nginx after the configuration change? Do you see 8 nginx child-processes in htop?
> 
> As temporary fix, set worker_connections 4000; as mentioned above, and also set `worker_rlimit_nofile 10000;` within the main context of /etc/nginx/nginx.conf . Then restart nginx again.

Is it correct? @basisbit 
![Uploading image.png…]()

**Comment by basisbit** [comment]
`worker_rlimit_nofile 10000;` should be outside of events.

**Comment by cod3r0k** [comment]
> worker_rlimit_nofile 10000;

Thanks. I edit it as below:


```
user www-data;
worker_processes 8;
pid /run/nginx.pid;
include /etc/nginx/modules-enabled/*.conf;

worker_rlimit_nofile 10000;

events {
        worker_connections 4000;
        # multi_accept on;
        #worker_connections 8;
}

```

**Comment by antobinary** [comment]
These changes were included in https://github.com/bigbluebutton/bigbluebutton/releases/tag/v2.3-alpha-7

(see the last lines of the release notes)

>Package bbb-config now sets worker_rlimit_nofile 10000; and worker_connections 4000; in /etc/nginx/nginx.conf #11347

**Comment by cod3r0k** [comment]
> These changes were included in https://github.com/bigbluebutton/bigbluebutton/releases/tag/v2.3-alpha-7
> 
> (see the last lines of the release notes)
> 
> > Package bbb-config now sets worker_rlimit_nofile 10000; and worker_connections 4000; in /etc/nginx/nginx.conf #11347

Thank you so much @antobinary ! That's a good news!

**Comment by basisbit** [comment]
@cod3r0k could you please confirm that this change "fixed" your problem?

**Comment by cod3r0k** [comment]
Dear @basisbit & @antobinary , I will notify you the result.

Do we need to do any manual updates which you said in alpha 2.3.7 release notes? or we can just use the main approach as below?

`wget -qO- https://ubuntu.bigbluebutton.org/bbb-install.sh | bash -s -- -v bionic-230-dev -s bbb.example.com -e notice@example.com  -a -w`

**Comment by basisbit** [comment]
the changes in https://github.com/bigbluebutton/bigbluebutton/issues/11347#issuecomment-778626170 should be enough already.

For your production setup, I'd suggest you to test the new version first, and only deploy it, if it looks good for you.

**Comment by cod3r0k** [comment]
> the changes in [#11347 (comment)](https://github.com/bigbluebutton/bigbluebutton/issues/11347#issuecomment-778626170) should be enough already.
> 
> For your production setup, I'd suggest you to test the new version first, and only deploy it, if it looks good for you.

OK, I will test this configuration in a huge event and will send you a feedback. In small event that configuration was suitable and I never find any previous logs in `errror.log` file, But for huge event I must check it again.

**Comment by rasos** [comment]
We also run out of workers on a 2.3.5 and have then adapted the `nginx config`as proposed here. Looks good now also in larger conferences.

**Comment by basisbit** [comment]
thank you for providing the feedback!
