### ISSUE TITLE
Reduce echo timing using udp opened port test before using coturn

### ISSUE THREAD

**Issue by aguerson** [bigbluebutton/bigbluebutton#11346]
Hi BBB devs,
On my BBB instances, I configured coturn like described in the BBB documentation.
Since I did it, the cliens only use coturn to connect ( full TCP 443 ).
Is there anay solution or approach to let the clients test if the UDP ports are still open and use them before to pass to coturn ?

An option somewhere in the code, or a fast test ?

At the end, if the UDP ports are opened, the echo test will be more fast, and coturn will be less used ( CPU load ).

Thanks in advance for your answer,
Regards,
Aurélien.

**Comment by PhMemmel** [comment]
The usual behavior is already that direct UDP connections are favored over using the turn server. So if you find all your users connecting via coturn you or your users will probably have a firewall which isn't allowing UDP traffic between your users and the BBB server(s) on the specified ports. So this pretty sure isn't a BBB issue, but a configuration/networking problem.

**Comment by basisbit** [comment]
For support requests (yes, this is a setup configuration specific question, not a general problem of every bbb setup), please use the [forum / mailing list](https://groups.google.com/forum/#!forum/bigbluebutton-setup). This issue tracker here is only for BBB development related issues. Sorry.
