### ISSUE TITLE
[2.3] RTL isn't realigning chat elements

### ISSUE THREAD

**Issue by daminebenq** [bigbluebutton/bigbluebutton#11352]
To reproduce:
1) go to bbb2.3 server 
2) set meeting display language to any RTL language
3) type messages in chat

Expectations:
4) Chat elements should be aligned to the right.

Result:
4) Chat elements are not getting aligned at all.

![image](https://user-images.githubusercontent.com/5144311/107362355-67533d80-6ab7-11eb-9f36-24bda029055c.png)

**Comment by Rahimimojtaba** [comment]
Same result as I tested.
[Chat RTL not Aligned](https://screencast-o-matic.com/watch/crnQIpSi68)

**Comment by daminebenq** [comment]
solved in #11173
