### ISSUE TITLE
[2.3] Chat text selection is kinda impossible

### ISSUE THREAD

**Issue by daminebenq** [bigbluebutton/bigbluebutton#11353]
To reproduce: 
1) go to bbb 2.3 server
2) type and send chat messages 
3) try to select some chat text from the chat box

Result:
4) Chat elements aren't selectable

Expectations:
4) Selecting a text from the chat should be allowed.

https://user-images.githubusercontent.com/5144311/107363001-4c34fd80-6ab8-11eb-88fe-99a7125011da.mp4

**Comment by daminebenq** [comment]
I couldn't reproduce this issue using #11173 (the chat text is easily selectable)
but it's still happening on [v2.3-alpha-6](https://github.com/bigbluebutton/bigbluebutton/releases/tag/v2.3-alpha-6)

**Comment by EmmyGraugans** [comment]
maybe even worse: it isn't possible to select and copy out the "invite-link" which is written above the chat-window. In Chromium it's possible to select the text only from the `Welcome to Home Room!` start to whereever the cursor tries to draw a selection (i.e. also when trying to select the invite link, the actual selection starts at the top!), but as soon as the cursor isn't moved any more, the selection vanishes. Once a chat-message was posted within Chrome, it's no longer possible to select *anything*.

**Comment by timmwille** [comment]
I can confirm, also not possible to copy the phone call options with PIN etc. Only Workaround was CTRL+A (which is not really a workaround, only emergency solution to not retype by hand)
