### ISSUE TITLE
[2.3] Changing Language fully interrupts and stops webcams and screenshare

### ISSUE THREAD

**Issue by daminebenq** [bigbluebutton/bigbluebutton#11351]
To reproduce:
1) go to bbb 2.3 server
2) enable webcam and audio
3) change the language in the meeting settings

Result:
4) Audio only continues working, while webcam is fully stopped.

Expectations:
4) Audio and Webcam should all continue working without any interruptions.
 
https://user-images.githubusercontent.com/5144311/107361572-5c4bdd80-6ab6-11eb-8dd3-8fd46aef8499.mp4

#10035 has same problem with Screensharing

**Comment by antobinary** [comment]
Screenshare case already has an open issue https://github.com/bigbluebutton/bigbluebutton/issues/10035
Let's keep this issue only for webcams

**Comment by antobinary** [comment]
Nevermind, the issue I linked to was about joining breakouts, not about changing a locale
