### ISSUE TITLE
Breakout and parent room countdown timer out of sync

### ISSUE THREAD

**Issue by ritzalam** [bigbluebutton/bigbluebutton#11358]
**Describe the bug**
During breakouts, the parent and breakout rooms have their own countdown timer. After a while
these timers drift causing a room to end earlier than the others. When this happens, users get
kicked out of the room prematurely.

**To Reproduce**
1. Create a few breakout rooms with duration of more than 20 minutes
2. Observe their countdown timer and see if the timers gets out of sync
3. A room that is ahead of other rooms will end earlier than other rooms

**Expected behavior**
Timers should be synched as closely as possible so they end at the same time..

**Screenshots**
![breakout-room-countdown-not-sync](https://user-images.githubusercontent.com/184672/107391543-c9676f00-6ac6-11eb-8741-c3ce280c0a53.png)

**Comment by rasos** [comment]
Yes this behavior has been reported by several users.

**Comment by antobinary** [comment]
New key info available via https://github.com/bigbluebutton/bigbluebutton/issues/11498#issuecomment-785771157

**Comment by ritzalam** [comment]
Reopening this issue as there is a server side work needed.

The parent and breakout rooms each has its own countdown timer. There should only be a single source of truth how much time remaining in the breakout session. The parent should be this source and tell the breakout rooms the time remaining.

**Comment by antobinary** [comment]
Closed via #12140 (and other aspects improved in #11510 )
