### ISSUE TITLE
bbb-record --rebuild <internal-ID> produces recording without sound and slides

### ISSUE THREAD

**Issue by myymi** [bigbluebutton/bigbluebutton#11368]
While processing initially unrecorded raw material to the recording, outcome is left without sound abd skudes. There is no sound on either presentation nor podcast. Links appear and video is there.
When checking raw material directory, there is audio file present in the .opus format, also all the other materials exist.
Normal recording process (i.e. user pushes button) produces correct recording with sound and everything.
**To reproduce**
1) on the command line, use command bbb-record --rebuild <internal-ID> on previously unrecorded presentation
2) after a while, go check recording, check podcast and presentation, there is no sound on neither the presentation nor podcast.
**Expected behaviour**
bbb-record --rebuild <internal-ID> creates fully functional recording, with sound and slides.
**Actual behaviour**
bbb-record --rebuild <internal-ID> produces recording without sound and slides
**Additional context**
Bigbluebutton is latest 2.2 version, installed with bbb-install.sh script. I remember that this bbb-record --rebuild used to work well in spring, but now it reproduces presentation without sound and slides, and podcast without sound. 
I have checked file permissions, and the owner is always bigbluebutton:bigbluebutton. 
[process_798e989b53d691a1b03302492ce34f5dce4a5d35-1612436286714.log](https://github.com/bigbluebutton/bigbluebutton/files/5957083/process_798e989b53d691a1b03302492ce34f5dce4a5d35-1612436286714.log)

**Comment by kepstin** [comment]
Hi,

Are you able to share the contents of the `events.xml` file in the recording raw directory?

If you can't share the entire contents of the events.xml for privacy reasons, please share the output of the following commands:
```
grep -c SharePresentationEvent events.xml
grep -c StartRecordingEvent events.xml
```

According to the processing log you posted, the events.xml appears to not be referencing any audio files, therefore they're not being processed in the recording.

It would also help if you can find the logs from the `archive` and `sanity` steps for this recording.

**Comment by myymi** [comment]
Good day! 
Thanks for having a look at my problem. I'm sorry to say that I haven't kept those logs for that long, and concidering that there's a completely nwe build out already, I think that this ticket can be closed.
Sorry for forgetting to close that earlier and wasting your time.
