### ISSUE TITLE
shared notes get lost on closing sessions - display possibility to download them on session end for mods?

### ISSUE THREAD

**Issue by joergmschulz** [bigbluebutton/bigbluebutton#11379]
Shared notes get lost along with all other session states on end of session. This is intended, and it is good.

As some people write session protocols into the shared notes, it would be good to have a popup/reminder to save the notes before a moderator closes the session.

**Comment by antobinary** [comment]
@pedrobmarin Are shared notes forever lost or stored somewhere and included in recordings?

**Comment by pedrobmarin** [comment]
If the meeting wasn't recorded the notes will be lost

**Comment by joergmschulz** [comment]
by the way - not quite. If the meeting has been created with the possibility to be recorded, and the deletion grace period isn't over, the admin might find them under
/var/bigbluebutton/recording/raw/
About the duration: https://docs.bigbluebutton.org/admin/privacy.html

**Comment by pedrobmarin** [comment]
Does this means you solved your own problem, @joergmschulz ?

**Comment by joergmschulz** [comment]
@pedrobmarin Sorry, no, it is not resolved. I describe a workaround for cases where recording has been activated and an admin is at hand. We shouldn't rely on admins to salvage notes accidentally lost by moderators. We should somehow prevent the loss of notes on end-of-session.

**Comment by tbussmann** [comment]
isn't this a duplicate of Issue #10721?

**Comment by joergmschulz** [comment]
indeed. Duplicate of  #10721 .
