### ISSUE TITLE
Set playback speed

### ISSUE THREAD

**Issue by Morinator** [bigbluebutton/bigbluebutton#11385]
When you are watching a recorded lecture, you often want to increase playback-speed when the presenter is speaking slowly.
Similarly to Youtube, where you can pick from 1.25x, 1.5x speed etc.

**Comment by hiroshisuga** [comment]
the newest 2.3alpha implements the novel playback system, with which you can do exactly what you want.
You can install it to 2.2 server as well.
https://github.com/bigbluebutton/bbb-playback

**Comment by e-hengirmen** [comment]
> the newest 2.3alpha implements the novel playback system, with which you can do exactly what you want.
> You can install it to 2.2 server as well.
> https://github.com/bigbluebutton/bbb-playback

Does it also work on the browser or do I need to download the bbb-playback?
