### ISSUE TITLE
[2.3 Only] private/public chat notifications and user join notification audio and visual notifications are broken

### ISSUE THREAD

**Issue by daminebenq** [bigbluebutton/bigbluebutton#11399]
Chat Message and User Join notifications alerts are broken:
![image](https://user-images.githubusercontent.com/5144311/107840787-7c202180-6d94-11eb-8016-e4ffbabeb6b8.png)

https://user-images.githubusercontent.com/5144311/107840874-f9e42d00-6d94-11eb-8cc7-637f93f97b77.mp4

**Comment by mariogasparoni** [comment]
I think this is related to: https://github.com/bigbluebutton/bigbluebutton/issues/11318
The fix i am working on might covers this case

**Comment by mariogasparoni** [comment]
Turns out this is related to a different code i was working on. So ,nothing to worry about @Tainan404.
