### ISSUE TITLE
BBB 2.3a6 and latest greenlight 404 waiting room

### ISSUE THREAD

**Issue by markginter31** [bigbluebutton/bigbluebutton#11407]
**Describe the bug**
When Greenlight is trying to connect - the "waiting room" feature works - but the greenlight client that is waiting gets 404'd.

**To Reproduce**
1. Go to Greenlight
2. Start room (as moderator)
3. Share link with guest -- they attempt to join room
4. Moderator sees the approval prompt - guest sees 404

**Expected behavior**
Guest is shown a holding screen (I guess?)

**Actual behavior**
Guest sees 404

**Screenshots**
I did notice the tokens are different in the two?  I don't know if that's of consequence...

![Screenshot from 2021-02-14 06-39-00](https://user-images.githubusercontent.com/7345618/107891385-5017b400-6eec-11eb-8092-56ce75f101af.png)

![Screenshot from 2021-02-14 06-39-28](https://user-images.githubusercontent.com/7345618/107891386-53ab3b00-6eec-11eb-94b2-85822812b5d9.png)

**Comment by pedrobmarin** [comment]
Looks like this is related with the multiple Meteor's nodes instances. This was fixed with https://github.com/bigbluebutton/bigbluebutton/pull/11104. Can you check your bbb-web properties file if it have the correct settings? Your guest landing page URL should look like `https://<host>/html5client/<instance id>/guestWait?<params>`

**Comment by markginter31** [comment]
I tried to edit /usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties and changed the:
defaultGuestWaitURL=${bigbluebutton.web.serverURL}/html5client/guestWait

to
defaultGuestWaitURL=${bigbluebutton.web.serverURL}/html5client/%%INSTANCEID%%/guestWait

Seems to work.  Thanks.

Does the bigbluebutton.properties file get overwritten on updates when using bbbinstall.sh?

**Comment by pedrobmarin** [comment]
I'm not sure if bbbinstall overwrites it. I understand that in cases like this one it should but there is also the drawback that custom modifications would be lost.

**Comment by markginter31** [comment]
Good point.  Wonder why the Debian pkg feature of asking to over-write the .conf isn't used.  But that's off topic.  This one's closed...
