### ISSUE TITLE
Where is Annotation SVG saved?

### ISSUE THREAD

**Issue by irkreja** [bigbluebutton/bigbluebutton#11412]
Looks like when we upload a pdf all are converted to SVG and annotation is appear on top of svg as another svg. Can you please provuide a location where is annotation is saved? So that I can work with these file differently?

**Comment by basisbit** [comment]
For support requests, please use the [forum / mailing list](https://groups.google.com/forum/#!forum/bigbluebutton-dev). This issue tracker here is only for BBB development related issues. Sorry.
