### ISSUE TITLE
Watch time + who watch the recordings

### ISSUE THREAD

**Issue by louia** [bigbluebutton/bigbluebutton#11419]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated. Has a developper of moodle, i can't access to record's view's (know which people has seen a record and their watch time) via API of BBB. In this period of COVID etc, i can't make the attendance of the classes with the recordings of meetings.

**Describe the solution you'd like**
Store and develop the API to store which users saw the record and their watch time.

**Comment by basisbit** [comment]
When developing a solution for this, please make this optional or make it possible to disable/configure it so that server operators can comply with whatever legal privacy requirements there are.

**Comment by louia** [comment]
Any update of know watchtime of user's video playback ?
