### ISSUE TITLE
bbb 2.3 alpha 7 stunclient test warning

### ISSUE THREAD

**Issue by markginter31** [bigbluebutton/bigbluebutton#11440]
once everything is running I receive a 
"Warning: Failed to verify STUN server at 172.217.212.127:19302 with command stunclient --mode full --localport 30000 172.217.212.127 19302"

I'm behind a firewall/NAT.  Running the command on the command line shows:
Binding test: success
Local address: local.ip.x.x:30000
Mapped address: external.ip.x.x:30000
Behavior test: fail
Filtering test: fail

A quick google and I found a comment that said WebRTC doesn't depend on the Behavior/Filtering -- and will function if the Binding test is successful.  From what I can tell - this is correct.  Everything is still shareable from my setup.  I assume dropping the "--mode full" from the command would still show the successful bind but would drop this from being a warning when bbb-conf is run?  Or - is there something I need to reconfigure to ensure that behavior/filtering don't fail?

**Comment by ffdixon** [comment]
We added that test based on 

  https://docs.bigbluebutton.org/2.2/setup-turn-server.html#test-you-turn-server

>  I assume dropping the "--mode full" from the command would still show the successful bind but would drop this from being a warning when bbb-conf is run?

We'll investigate further and may tweak this test in the next release of 2.3-dev.

**Comment by cod3r0k** [comment]
After I update my BBB to alpha-2.3.7 , I'm getting the same warning.

> We added that test based on
> 
> https://docs.bigbluebutton.org/2.2/setup-turn-server.html#test-you-turn-server
> 
> > I assume dropping the "--mode full" from the command would still show the successful bind but would drop this from being a warning when bbb-conf is run?
> 
> We'll investigate further and may tweak this test in the next release of 2.3-dev.

**Comment by masakkre** [comment]
Hi!
I am trying to do a fresh install of BBB and, since last week, I am getting always this error too:

# Potential problems described below


#
# Warning: Failed to verify STUN server at stun.l.google.com 19302 with command
#
#    stunclient --mode full --localport 30000 stun.l.google.com 19302
#

#
# Warning: Failed to verify STUN server at 172.217.212.127:19302 with command
#
#    stunclient --mode full --localport 30000 172.217.212.127 19302
#

The strange thing is that the server seems to be working well. I can do video meetings...

Hope this my help.


Thank you for your great work!!

> We added that test based on
> 
> https://docs.bigbluebutton.org/2.2/setup-turn-server.html#test-you-turn-server
> 
> > I assume dropping the "--mode full" from the command would still show the successful bind but would drop this from being a warning when bbb-conf is run?
> 
> We'll investigate further and may tweak this test in the next release of 2.3-dev.

**Comment by sina-rostami** [comment]
I got the same errors...

**Comment by ankushnayak** [comment]
Getting the same warning in the 2.3.1 release too. Everything works fine though in terms of meetings.
```
#
# Warning: Failed to verify STUN server at stun.l.google.com 19302 with command
#
#    stunclient --mode full --localport 30000 stun.l.google.com 19302
#

#
# Warning: Failed to verify STUN server at 172.217.212.127:19302 with command
#
#    stunclient --mode full --localport 30000 172.217.212.127 19302
#
```

**Comment by renanrmelo** [comment]
Getting the same warning in the 2.3.1 release too.

**Comment by ffdixon** [comment]
> Getting the same warning in the 2.3.1 release too.

It might be the networking setup for your server.  Just tried it on one of our test servers and it returned success.

```
# stunclient --mode full --localport 30000 stun.l.google.com 19302
Binding test: success
Local address: 159.89.126.53:30000
Mapped address: 159.89.126.53:30000
Behavior test: success
Nat behavior: Direct Mapping
Filtering test: success
Nat filtering: Endpoint Independent Filtering
# echo $?
0
```

**Comment by ankushnayak** [comment]
> 
> 
> > Getting the same warning in the 2.3.1 release too.
> 
> It might be the networking setup for your server. Just tried it on one of our test servers and it returned success.
> 
> ```
> # stunclient --mode full --localport 30000 stun.l.google.com 19302
> Binding test: success
> Local address: 159.89.126.53:30000
> Mapped address: 159.89.126.53:30000
> Behavior test: success
> Nat behavior: Direct Mapping
> Filtering test: success
> Nat filtering: Endpoint Independent Filtering
> # echo $?
> 0
> ```

Weird since it is a new EC2 instance on AWS with the firewall settings as recommended in the BigBlueButton docs. See screenshot below.
![Screenshot 2021-05-30 102047](https://user-images.githubusercontent.com/71924022/120092491-cef9cb00-c130-11eb-931c-91f10ed95368.png)

**Comment by kusznerr** [comment]
We got the same for GCP. Running the test without --mode full, returns success. 
```
kuszner@www90:~$ stunclient --mode full --localport 30000 172.217.212.127 19302
Binding test: success
Local address: 10.4.0.7:30000
Mapped address: 35.246.138.252:30000
Behavior test: fail
Filtering test: fail
kuszner@www90:~$ stunclient --localport 30000 172.217.212.127 19302
Binding test: success
Local address: 10.4.0.7:30000
Mapped address: 35.246.138.252:30000
```

**Comment by rasos** [comment]
We are getting on one of our test servers

       Warning: Failed to verify STUN server at  3478 with command
       stunclient --mode full --localport 30000  3478

Obviously, somewhere the IP address for a stun server is missing. But which one in which setting?

However, stun servers are defined and working - I double checked 
```

/etc/kurento/modules/kurento/WebRtcEndpoint.conf.ini
/usr/share/bbb-web/WEB-INF/classes/spring/turn-stun-servers.xml
/etc/bigbluebutton/turn-stun-servers.xml
```
Any other place for configuring STUN services?

**Comment by PhMemmel** [comment]
You probably are hitting #12638?

**Comment by rasos** [comment]
Yes, reducing to one stun server eliminated the error message, thanks @PhMemmel . 
Still getting 1006 audio timeout errors, needs further investigations.

**Comment by prlanzarin** [comment]
>  Still getting 1006 audio timeout errors, needs further investigations.

Most probably related to signaling rather than WebRTC media connectivity.

Recommend checking whether `sipjsHackViaWs` is activated in settings.yml.
The config must correspond to the reverse proxy entry in sip.nginx.
a) sipjsHackViaWs: true => sip.nginx should reverse proxy to http://<etc>:5066
b) sipjsHackViaWs: false => sip.nginx should reverse proxy to https://<etc>:7443

Prefer the first option (a).

**Comment by salytwo** [comment]
same issue here version  2.4.7 (3065) greenlight 2.4
Warning: Failed to verify STUN server at stun.l.google.com 19302 with command
#
#    stunclient --mode full --localport 30000 stun.l.google.com 19302

I am using letencrypt and complete local enviroment also ubuntu firrewall is inactive
