### ISSUE TITLE
User Name Changing in Session Frontend

### ISSUE THREAD

**Issue by ARK1988** [bigbluebutton/bigbluebutton#11449]
Hi
It is a very useful feature to be able to change the user name in the session frontend (HTML5). In this way, when the user clicks on the name icon in the class list, next to the status option, there is also the option to change the name. By renaming through this option, only the name displayed in the users list will be changed temporarily and the profile name of user will not be changed.

![feature_bbb](https://user-images.githubusercontent.com/9945018/108679618-0fc6c000-7502-11eb-8bfe-d262c0c95b0a.jpg)

**Comment by ARK1988** [comment]
Hi

no any idea by developer team?!
Is it possible to set this feature in the next version of bbb?

thanks a lot!

**Comment by antobinary** [comment]
Hi @ARK1988 
This is actually a duplicate issue. Here's the original issue with the conclusive comment https://github.com/bigbluebutton/bigbluebutton/issues/998#issuecomment-362776604
