### ISSUE TITLE
400 Bad Request nginx in joining a session

### ISSUE THREAD

**Issue by cod3r0k** [bigbluebutton/bigbluebutton#11442]
When I update one of my BBB to alpha-2.3.7 , I check server with `bbb-conf --secret` api-mate. 
After I create a session in api-mate, I try to join as a moderator or attendee. At that time I get an error as below

```
400 Bad Request
nginx
```

**To Reproduce**
1. Update to BBB 2.3.7 alpha
2. Create a session in api-mate
3. Join as moderator or attendee

Maybe it is related my previous setting in nginx @basisbit  . Isn't it? @antobinary 

/var/log/nginx/error.log

`2021/02/20 12:00:39 [error] 23113#23113: *340 open() "/var/www/bigbluebutton-default/client/conf/config.xml" failed (2: No such file or directory), client: x.x.x.x, server: xxxxxxxxxxxxxxxxxx, request: "GET /client/conf/config.xml HTTP/1.1", host: "xxxxxxx"
`

**Comment by ffdixon** [comment]
Hmm ... we're seeing the same error.  Taking a closer look.

**Comment by ffdixon** [comment]
A clean install works, but the upgrade breaks.  Looking closer.

**Comment by cod3r0k** [comment]
> A clean install works, but the upgrade breaks. Looking closer.

Wow! thanks so bad!  I have many video on this sever.   I hope it will be solved soon!  @ffdixon

**Comment by cod3r0k** [comment]
I found the solution as @antobinary said at release notes.
https://github.com/bigbluebutton/bigbluebutton/releases/tag/v2.3-alpha-7

```
Note that we removed the recently introduced in 2.3-alpha5 instanceId from the HTML5 client's url. You may need to edit the following two lines in /usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties if you are updating an existing 2.3.x server.

- defaultHTML5ClientUrl=${bigbluebutton.web.serverURL}/html5client/%%INSTANCEID%%/join
+ ￼defaultHTML5ClientUrl=${bigbluebutton.web.serverURL}/html5client/join
- ￼defaultGuestWaitURL=${bigbluebutton.web.serverURL}/html5client/%%INSTANCEID%%/guestWait
+ ￼defaultGuestWaitURL=${bigbluebutton.web.serverURL}/html5client/guestWait`
```

and also change all files in `/etc/bigbluebutton/nginx` and it works well!

**Comment by antobinary** [comment]
@ffdixon tweaked the bbb-install script too, so this should be fine 

https://github.com/bigbluebutton/bbb-install/commit/4ed08facf9db6c7ad27a247ace8342eea329e89a#diff-b02a2e8accf3dc268b4cc8c4a6ce2b6b51cbaee1a254fb674c6429fbfdf5ef81R399-R401

**Comment by odejinmisa** [comment]
![Screenshot 2021-02-24 171948](https://user-images.githubusercontent.com/62740154/109031001-99be8680-76c4-11eb-97a6-b593be964f4c.jpg)

I am encountering in my development  error: ValidateAuthTokenRespMsg: Error: Match error: Expected number, got undefined

I have 2.3apha4 installed in production and 2.3aplha7 for development.
 
Thanks.

**Comment by basisbit** [comment]
For support requests, please use the [forum / mailing list](https://groups.google.com/forum/#!forum/bigbluebutton-setup). This issue tracker here is only for BBB development related issues. Sorry.

**Comment by cod3r0k** [comment]
> I found the solution as @antobinary said at release notes.
> https://github.com/bigbluebutton/bigbluebutton/releases/tag/v2.3-alpha-7
> 
> ```
> Note that we removed the recently introduced in 2.3-alpha5 instanceId from the HTML5 client's url. You may need to edit the following two lines in /usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties if you are updating an existing 2.3.x server.
> 
> - defaultHTML5ClientUrl=${bigbluebutton.web.serverURL}/html5client/%%INSTANCEID%%/join
> + ￼defaultHTML5ClientUrl=${bigbluebutton.web.serverURL}/html5client/join
> - ￼defaultGuestWaitURL=${bigbluebutton.web.serverURL}/html5client/%%INSTANCEID%%/guestWait
> + ￼defaultGuestWaitURL=${bigbluebutton.web.serverURL}/html5client/guestWait`
> ```
> 
> and also change all files in `/etc/bigbluebutton/nginx` and it works well!

Dear @ffdixon and @antobinary , please notify this comment in `2.3.4`. I have the same issue from upgrading 2.3.0 to 2.3.4.
