### ISSUE TITLE
Convert Leave audio to end meeting in BBB.

### ISSUE THREAD

**Issue by jhamobi** [bigbluebutton/bigbluebutton#11446]
When we click on Join Live Classroom, there are 4 icons that are shown on the bottom of the screen. Out of these 4 icons, there is a phone icon which says Leave audio/join audio. The following needs to change in this icon:

This icon should end the meeting as is done using the setting as shown in screenshot

Color of the icon to be changed to red.

**Comment by EmmyGraugans** [comment]
Uh, no? "Leave Audio" is something entirely different from "End Meeting"!

**Comment by antobinary** [comment]
@jhamobi 

> The following needs to change 

People are welcome to customize their fork of BigBlueButton. For the vast majority of the use cases though I do not see this as a valid request.

**Comment by jhamobi** [comment]
I am new to bigbluebutton. What is the access point of this change in codebase? 

Thanks
