### ISSUE TITLE
Simultaneous Interpretation in multiple languages 

### ISSUE THREAD

**Issue by ranjithrajv** [bigbluebutton/bigbluebutton#11459]
Feature that enables users to choose interpretations/translations in multiple languages and allows hosts to invite/add new interpreters/translators

Similar feature in Zoom: [
Language interpretation in meetings and webinars
](https://support.zoom.us/hc/en-us/articles/360034919791-Language-interpretation-in-meetings-and-webinars
)

Labels: Feature Request, Accessibility

**Comment by antobinary** [comment]
Hi @ranjithrajv 
Thanks for opening this issue. There is already a thread about this, and some community members have posted about having [most] of this working https://github.com/bigbluebutton/bigbluebutton/issues/2642
I am not aware of anyone sharing the code changes though
