### ISSUE TITLE
handle multiple default rules

### ISSUE THREAD

**Issue by hex-m** [bigbluebutton/bigbluebutton#11452]
**Describe the bug**
`bbb-conf` throws an error when the system has multiple default rules configured.

**To Reproduce**
1. Install BigBlueButton 2.3 alpha7 with `bbb-install.sh`
2. `bbb-conf --restart`

**Expected behavior**
No error.

**Actual behavior**
```
# bbb-conf --restart                                                                                           
ens3: Unknown host
ifconfig: `--help' gives usage information.
Restarting BigBlueButton 2.3.0-alpha7 ...
[...]
# Potential problems described below
.......
/usr/bin/bbb-conf: line 1016: [: 123.123.123.123: unary operator expected
ens3: Unknown host
ifconfig: `--help' gives usage information.
```

**Additional context**
This seems to be the same issue that was already fixed in `bbb-install.sh`. https://github.com/bigbluebutton/bbb-install/pull/327/

Somewhat off-topic: net-tools (ifconfig, route,..) is deprecated and iproute2 (`ip route`) should be used.

**Comment by ahasanaki** [comment]
same problem when install BigBlueButton 2.3-beta-2

```
root@w7:~# bbb-conf --restart
default
eth0: Unknown host
ifconfig: `--help' gives usage information.
Restarting BigBlueButton 2.3.0-beta-2 ...
Stopping BigBlueButton

Applying updates in /etc/bigbluebutton/bbb-conf/apply-config.sh:
  - Enable Firewall and opening 22/tcp, 80/tcp, 443/tcp and 16384:32768/udp
Skipping adding existing rule
Skipping adding existing rule (v6)
Skipping adding existing rule
Skipping adding existing rule (v6)
Skipping adding existing rule
Skipping adding existing rule (v6)
Firewall is active and enabled on system startup

Starting BigBlueButton


# Potential problems described below
...............................
/usr/bin/bbb-conf: line 1045: [: <Valid IP>: unary operator expected
eth0: Unknown host
ifconfig: `--help' gives usage information.
```

**Comment by ffdixon** [comment]
Could you modify `/usr/bin/bbb-conf` and set the first line to

```
#!/bin/bash -ex
```

and try running the command again. This will print out each command in `bbb-conf` and give clues as to why the error is occurring.

**Comment by hex-m** [comment]
Thanks for the debugging advise.

```
+++ route
+++ sed 's/.* //'
+++ grep '^default'
++ ifconfig ens3 ens3
ens3: Unknown host
ifconfig: `--help' gives usage information.
+ IP=
```
Setting `IP` to emtpy string leads to a subsequent error but the caus is the output of `route`:
```
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
default         123.123.123.254   0.0.0.0         UG    0      0        0 ens3
default         123.123.123.254   0.0.0.0         UG    100    0        0 ens3
[..]
```

So it's about "multiple default rules" as described in the first post.

**Comment by ahasanaki** [comment]
thanks;
i removed duplicate default route and it's worked
