### ISSUE TITLE
Break-out rooms: When rejoining allow to skip echo test

### ISSUE THREAD

**Issue by sebastianberm** [bigbluebutton/bigbluebutton#11450]
**Is your feature request related to a problem? Please describe.**
I don't know if this is a bug or intended behavior, although I've heard this one a couple of times already.

We have echo tests enabled (mostly due to most users not being really computer savvy), but when people rejoin the audio of the main room, after having spent time in a break-out, it would be nice if it was possible to just rejoin with the last used settings and skipping the echo test all together.

**To Reproduce**
1. Create break-out room
2. Join break-out room with audio
3. After end of break-out room, rejoin main room
4. Rejoin with audio, and you get an echo tests again.

**Expected behavior**
I would suggest the system to 'remember' the last used settings and rejoin with those settings (only if coming back from a break-out room).

**Actual behavior**
The echo test reappears.

**Comment by antobinary** [comment]
Hi @sebastianberm 
This work was actually just done https://github.com/bigbluebutton/bigbluebutton/pull/11381
Try it out on test23.bigbluebutton.org (I just tried it too on that server)
