### ISSUE TITLE
paste or drag'n'drop poll with title, timer and answers

### ISSUE THREAD

**Issue by viktor-c** [bigbluebutton/bigbluebutton#11457]
Based on the result of #11336 and #11330 adding the possibility of drag and dropping polls from a text file.

**Is your feature request related to a problem? Please describe.**
2.3-Alpha7 introduced PollTitle. Having drag and drop is great, it is already approved and will be hopefully merged sometime soon. 

**Describe the solution you'd like**
I would like to organize my polls the following way
```
title: What do you think of big blue button?
time: 60 (see #11456)
A: It is great!
B: Keep up the good work!
C: It's okay
D: ....
```
Then either drag and drop or copy paste to a text field of the polling component

Also JSON way of formatting could be an idea, but I guess it would be to complicated for regular presenters.

**Describe alternatives you've considered**
Manually entering title and options

**Comment by viktor-c** [comment]
Hello, it has been a while since I posted this. It is also stale, so I will bump it up once.
I was thinking about this lately: Imagine you are presenting a slideshow. And you want to engage your students or listeners, but don't want to have long waiting times, until you enter Poll title and so on. (AFAIK only the presenter can start a poll) 
So I would find it useful to have something like this:
`
pollTitle: What do you think of big blue button?
beginOnSlide: 10
delayBegin: 15s
timeToVote: 60s (see #11456)
A: It is great!
B: Keep up the good work!
C: It's okay
D: Withold
`
This way you can work your way through your slides and bigbluebutton (meteor) recognizes which page you are on and starts automatically your poll. 
So when beginning your pdf presentation you can paste/upload a saved text with poll data. :)

I hope somebody finds this useful and has time to work on an implementation blueprint.

**Comment by ffdixon** [comment]
> This way you can work your way through your slides and bigbluebutton (meteor) recognizes which page you are on and starts automatically your poll.

While BigBlueButton does not allow the user to upload/paste polls (yet), it does scan the text of the slide for a poll-like question and make it easy for the teacher to initiate a poll.  See

  https://docs.bigbluebutton.org/2.3/new.html#smart-poll-button-with-choices

**Comment by viktor-c** [comment]
> https://docs.bigbluebutton.org/2.3/new.html#smart-poll-button-with-choices

The page above link is not active anymore, it returns 404

https://support.bigbluebutton.org/hc/en-us/articles/1500005216661-Use-polling
shows the info above

**Comment by ffdixon** [comment]
Thanks @viktor-c, the link to the support docs is the correct link.
