### ISSUE TITLE
Ubuntu Update for BBB

### ISSUE THREAD

**Issue by msebastian100** [bigbluebutton/bigbluebutton#11463]
Hello, 
What about an Ubuntu update?
since Ubuntu 16.x.x will no longer be updated from April.
From the company's point of view, it is not advisable to continue using BBB as long as it is not updated. An unupdated system is a security risk.

With BBB, security should play a major role and not use old Ubuntu versions.

Greetings

**Comment by ffdixon** [comment]
The next release of BigBlueButton is 2.3-dev, see

  https://docs.bigbluebutton.org/dev/dev23.html

which will run on Ubuntu 18.04.  Please try it out and give us feedback to bigbluebutton-dev.
