### ISSUE TITLE
bbb 2.3 alpha 7 - Chat-Messages all show timestamp 01:00

### ISSUE THREAD

**Issue by EmmyGraugans** [bigbluebutton/bigbluebutton#11461]
In bbb 2.3 alpha 7 all chat-messages show the timestamp 01:00 (which corresponds to 00:00 UTC)

**To Reproduce**
1. Start a conference
2. Type something in the chat.

**Expected behavior**
The timestamp next to the name should show the current time.

**Actual behavior**
All chat-messages get the same time "01:00" (which might be different in a different time-zone)

**BBB version (optional):**
bbb 2.3 alpha 7

**Desktop (please complete the following information):**
 - OS: Linux, Mac
 - Firefox, Chrome, Safari
 
**Smartphone (please complete the following information):**
 - iPad
 - iOS 14.4
 - Safari
 
**Additional context**
Seems to be completely independent which browser or OS.

**Comment by ffdixon** [comment]
Thanks for reporting this.
