### ISSUE TITLE
Impossible to use BBB to launch meetings (used to work fine)

### ISSUE THREAD

**Issue by amandinepene** [bigbluebutton/bigbluebutton#11465]
**Describe the bug**
ver since yesterday (02/22/2021), we cannot access any meeting on bigbluebutton.
When accessing a meeting using a michrophone, the sound check freezes and nobody can access it. It loops on the "echo test". I have used the tool many times on this computer and with this browser, with success.
Now I tried with Chrome, Edge and it does not work at all
This is a very urgent issue since we are using bigbluebutton to deliver our service to customers (we deliver online trainings to health staff).

**To Reproduce**
1. Go to http://classe.orionsante.fr/b/ama-emb-vgg-p3d 
2. Try lauching any of the meetings with my profile (amandine.pene@orionsante.fr // Nalahudson1&)
3. Select "use mic"

**Expected behavior**
The session should launch and other people should hear me and be heard.

**Actual behavior**
No user can access the session : I cannot hear them, they cannot hear me or the other users.
The last screenshot shows what the frame is freezing on : the sound test.

**Screenshots**
![image](https://user-images.githubusercontent.com/79508549/108838529-09a11400-75d4-11eb-9d35-0bff3b01f2e8.png)
![image](https://user-images.githubusercontent.com/79508549/108838547-1160b880-75d4-11eb-8242-742d571e5127.png)
![image](https://user-images.githubusercontent.com/79508549/108838569-1887c680-75d4-11eb-9259-616d4a29aa43.png)

**BBB version (optional):**
I don't know

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser : Chrome, Edge
 - Version Chrome : Version 88.0.4324.182 (Build officiel) (64 bits)
 - Version Edge : Version 88.0.705.74 (Version officielle) (64 bits)

**Comment by hostbbb** [comment]
you need to post on bigbluebutton-setup of google forums, the results of sudo bbb-conf --check?
did you try to restart the server?  this is for software issues... you have a server admin issue.

**Comment by basisbit** [comment]
For support requests, please use the [forum / mailing list](https://groups.google.com/forum/#!forum/bigbluebutton-setup). This issue tracker here is only for BBB development related issues. Sorry.

**Comment by basisbit** [comment]
Please contact the administrator of your server or the operator of the BBB service that you use, so that they solve the problem.
