### ISSUE TITLE
Call timed out - errorCode=1006.

### ISSUE THREAD

**Issue by borhanreo** [bigbluebutton/bigbluebutton#11460]
**Describe the bug**
I have successfully install html5. But when i am trying to connect audio then show an error **Call timed out - errorCode=1006**. also working well camera.
i am using **remotes/upstream/v2.2.x-release** version

**Comment by ffdixon** [comment]
@borhanreo Please post such issues to bigbluebutton-setup with enough information for others to troubleshoot.  See https://docs.bigbluebutton.org/2.2/getting-help.html#help-installing-or-running-bigbluebutton.
