### ISSUE TITLE
Text annotation cannot be created on FireFox

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#11472]
**Describe the bug**
In Firefox one cannot use the tool Text to add text - once you pull the rectangle, it does not produce the usual window to add text, works fine in Chrome & Safari

**To Reproduce**
1. Join as presenter via FireFox
2. Try to input text annotation on whiteboard
3. Draw a rectangle of the area where you want to type

**Expected behavior**
The rectangle will mark an area to type, it will stay selected, background will become white for good contrast

**Actual behavior**
The recrangle area closes immediately, as if the focus changed automatically

**Screenshots**

**BBB version (optional):**
2.3-alpha 6, 7

**OS:**
Tested on Windows 10 and MacOS Big Sur.

**Additional context**
First reported on https://groups.google.com/g/bigbluebutton-dev/c/MvpY7S_n60s

**Comment by gilou** [comment]
I can confirm the bug occurs on alpha7, on Firefox 85 / Ubuntu as well (and it works fine in Chromium).

**Comment by antobinary** [comment]
Turns out this was already reported. Marking this as a duplicate of https://github.com/bigbluebutton/bigbluebutton/issues/10774
