### ISSUE TITLE
Breakouts creation: allow choice between passing current slide and whole presentation

### ISSUE THREAD

**Issue by markginter31** [bigbluebutton/bigbluebutton#11474]
Currently (2.2.x and 2.3-alphax) breakouts are created with one slide presentation only - the slide that was current in the main room.

It would be useful if there was a control on the breakouts create modal to allow choosing between
 * use the current slide in the breakouts (default)
 * use the entire current presentation

Context:
I'm a teacher and I have tried to match my online instruction with my in class instruction.  This means I've created pdf's of each lesson and I can present the exact same material through BBB to remote students that my in-person students are seeing at the same time.  Rather than being just a presentation - it is the content of the lesson itself.  If I want to have in person students work with online students in breakout rooms, it would be great to have the option of passing through the entire presentation so I don't have to go back through and re-upload the material into each breakout room.

**Comment by antobinary** [comment]
Hi @markginter31 

This is done by design.

A very common usage of breakout rooms is for the instructor to present a question/topic on a slide, split the participants into breakout discussion groups (on that slide) and then to resume in the main room.

It's not a bug, it was a requirement

**Comment by markginter31** [comment]
Makes sense... I ran into a use case where I needed each of my student groups to have 3 pages from social studies to read -- and then I had to go into each breakout room and re-upload the document for them.  Maybe it's an option when creating the breakout room?  A toggle for "Send visible slide" or "Send all slides"?

**Comment by antobinary** [comment]
@markginter31 I reopened the issue and reworded it as an enhancement request. Feel free to edit any of the fields to better describe what you had in mind...
Thank you for your suggestion!

**Comment by markginter31** [comment]
Wording looks great!  Thanks for considering this.

**Comment by basisbit** [comment]
related to #10851

**Comment by MWWorks** [comment]
I also have a similar use case to @markginter31 : sometimes the current behaviour is exactly what I need, ie a single slide with prompt for discussion etc; but other times I want participants to work through multiple exercises that can on separate pages. The suggested enhancement of giving a choice would be a great solution and would avoid having to manually upload content to multiple breakout rooms. So likewise, thank you for the reword and consideration!

**Comment by markginter31** [comment]
With this school year - I have a better sense of what I need:  I have one classroom but within that room I have 3 group levels.  If we are virtual - we have 1 main bbb room setup to gather in first -- and then -- it would be incredibly flexible to be able to assign the appropriate material to the appropriate group when breakout rooms are created.  Group 1 would get assigned the Group 1 material, Group 2 would get assigned the Group 2 material, and so on.   All the group material could be loaded into the Main Room presentation list and then picked/assigned to the appropriate group upon breakout.

**Comment by ffdixon** [comment]
We want to do this in a future update to breakout rooms.

**Comment by danielpetri1** [comment]
This feature has been added in #20626.
