### ISSUE TITLE
Sound Breaking off with Teams open fixed

### ISSUE THREAD

**Issue by Dretjie** [bigbluebutton/bigbluebutton#11478]
After spending a couple of hours trying to find the problem of my sound cutting out. I closed Teams to see if it works. And bang. Sound is back... Hope this will help others... or better yet. Get it fixed

**Comment by ffdixon** [comment]
Did you close the Teams desktop app or Teams running in a web page?

**Comment by Dretjie** [comment]
No. Had teams installed on computer and minimized. Had to exit teams.

**Comment by sebastianberm** [comment]
Users of our system reported this as well.
They didn't test this thoroughly though, so I am unsure if this is Teams or browser related.
