### ISSUE TITLE
Floating user menu on iPad

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#11473]
**Describe the bug**

**To Reproduce**
1.  Join a meeting with a few users
2. Try to tap on the user menu for one of them (to trigger start chat, kick, etc)

**Expected behavior**
The menu should open immediately beside the user's position in the userlist

**Actual behavior**
The menu will open far away on the screen

**Screenshots**
![Screenshot from 2021-02-23 14-32-00](https://user-images.githubusercontent.com/6312397/108897296-f302b900-75e3-11eb-8a7e-0a09bb0b4ba0.png)

**BBB version (optional):**
2.3-alpha5,6,7

*OS**
 iPad/Safari 14.3 & 14.4 

Initially reported on https://groups.google.com/g/bigbluebutton-dev/c/MvpY7S_n60s

**Comment by ramonlsouza** [comment]
may be fixed by PR #11500 (tested on chrome device emulation, needs to be tested on a real device)

![mobile-landscape-fix-ipad](https://user-images.githubusercontent.com/3728706/109150299-72f56400-7747-11eb-8d56-ace9ed53a08e.gif)
