### ISSUE TITLE
[2.2/2.3] when microphone muted, getting in breakout with audio only and leaving it, gets you back to main room with unmuted microphone

### ISSUE THREAD

**Issue by daminebenq** [bigbluebutton/bigbluebutton#11489]
https://user-images.githubusercontent.com/5144311/109057251-477b6680-76c0-11eb-9965-fc784dd88297.mp4

To reproduce:
1. go to a bbb meeting
2. connect with microphone
3. start breakout
4. mute your microphone in main room
5. click to join breakout with audio only
6. click return audio 
7. See result

Expected behavior:
Microphone should be kept muted in main room.

Actual behavior:
Microphone doesn't stay muted in main room.

**Comment by antobinary** [comment]
Possibly related to https://github.com/bigbluebutton/bigbluebutton/pull/8696 @mariogasparoni
