### ISSUE TITLE
Unable to upload pptx \ doc file

### ISSUE THREAD

**Issue by AUstinovKCO** [bigbluebutton/bigbluebutton#11481]
Unable to load pptx \ doc file. please, help. Conf-bbb --debug:
 /var/log/bigbluebutton/bbb-web.log:2021-02-24T12:31:45.896Z ERROR o.b.p.imp.Office2PdfPageConverter -  --analytics-- data={"exception":{"detailMessage":"Could not establish connection to external office process","cause":{"detailMessage":"org.jodconverter.local.office.OfficeConnectionException: Connection failed: \u0027socket,host\u003d127.0.0.1,port\u003d8202,tcpNoDelay\u003d1\u0027; java.net.ConnectException: Connection refused (Connection refused)","cause":{"connectString":"socket,host\u003d127.0.0.1,port\u003d8202,tcpNoDelay\u003d1","detailMessage":"Connection failed: \u0027socket,host\u003d127.0.0.1,port\u003d8202,tcpNoDelay\u003d1\u0027; java.net.ConnectException: Connection refused (Connection refused)","cause":{"detailMessage":"java.net.ConnectException: Connection refused (Connection refused)","stackTrace":[],"suppressedExceptions":[]},"stackTrace":[],"suppressedExceptions":[]},"stackTrace":[],"suppressedExceptions":[]},"stackTrace":[],"suppressedExceptions":[]},"filename":"logsknopka.txt","logCode":"office_doc_to_pdf_failed_with_exception","meetingId":"c6c44d0bc4b54f9d24ca77e8ddea925357fed671-1614168156044","message":"Failed to convert Office doc to PDF.","presId":"5b62974214ec5635248f8d1065444cbbafae61b3-1614169892841"}

**Comment by ffdixon** [comment]
You need to share more information.  See https://docs.bigbluebutton.org/2.2/getting-help.html#help-installing-or-running-bigbluebutton

**Comment by basisbit** [comment]
For support requests, please use the [forum / mailing list](https://groups.google.com/forum/#!forum/bigbluebutton-setup). This issue tracker here is only for BBB development related issues. Sorry.
