### ISSUE TITLE
Mobile browser

### ISSUE THREAD

**Issue by jhamobi** [bigbluebutton/bigbluebutton#11509]
What is the access point of this warning message in codebase? Need to update this warning message which is coming on mobile browser. Also, the error message is cut and not shown on full screen. 

PFA screenshot below-

![image-20210208-075228](https://user-images.githubusercontent.com/65014913/109285770-7bcd5f00-7847-11eb-9d19-e608f8be3b84.png)

Thanks for reading this

**Comment by antobinary** [comment]
https://github.com/bigbluebutton/bigbluebutton/blob/develop/bigbluebutton-html5/imports/ui/components/legacy/component.jsx#L134 (link to 2.3 codebase. That file is slightly different on 2.2.x)

**Comment by basisbit** [comment]
For future questions, please use bigbluebutton-dev mailing list. Thank you.
