### ISSUE TITLE
change copyright year in html5 to 2021

### ISSUE THREAD

**Issue by afsharsafavi** [bigbluebutton/bigbluebutton#11519]
Hi
It seems copyright value in this path should change to 2021:
/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml
current value:
    copyright: "  2020 BigBlueButton Inc."

**Comment by ffdixon** [comment]
Thanks for letting us know.

**Comment by KDSBrowne** [comment]
I think this was already done in https://github.com/bigbluebutton/bigbluebutton/commit/c0c5a87e3c2a7446f1c1b0dfff6d5e751a7b077a

**Comment by afsharsafavi** [comment]
> I think this was already done in [c0c5a87](https://github.com/bigbluebutton/bigbluebutton/commit/c0c5a87e3c2a7446f1c1b0dfff6d5e751a7b077a)

It seems it was already done in 2.3-dev. but last day I upgraded to latest stable version (2.2.33) and I saw this : copyright: " 2020 BigBlueButton Inc.", So I reported it.

**Comment by mohe2015** [comment]
I have no idea but I always thought copyright should be a range from creation to now. So e.g. 2010 - 2021

**Comment by antobinary** [comment]
Addressed via https://github.com/bigbluebutton/bigbluebutton/commit/98486727750835df6b935ac86e253b11327e786e
