### ISSUE TITLE
HeapDumpOnOutOfMemoryError and High CPU processing in 2.3.7 on VPS

### ISSUE THREAD

**Issue by cod3r0k** [bigbluebutton/bigbluebutton#11513]
I try to create a new VPS on ESXI 6.5.0 with the following specification (the main server is G8):

```
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              10
On-line CPU(s) list: 0-9
Thread(s) per core:  1
Core(s) per socket:  1
Socket(s):           10
NUMA node(s):        1
Vendor ID:           GenuineIntel
CPU family:          6
Model:               45
Model name:          Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz
Stepping:            7
CPU MHz:             2593.750
BogoMIPS:            5187.50
Hypervisor vendor:   VMware
Virtualization type: full
L1d cache:           32K
L1i cache:           32K
L2 cache:            256K
L3 cache:            20480K
NUMA node0 CPU(s):   0-9
```

When I installed bbb2.3 alpha7 version of BBB, It was amazing handling the CPU processors. 
![image](https://user-images.githubusercontent.com/36899025/109313369-62371200-785d-11eb-9f30-076a2e119920.png)

I have never this experience with 2.2 in this ESXI 6.5.0 (VPS servers as I created before). Do you have any idea about this? @antobinary @ffdixon @basisbit 

**To Reproduce**
1. Create a VPS as I mentioned
2. Install BBB 2.3.7 
3. Create a session or run bbb-restart or any other related BBB commands
4. You can see that about 5-10 min we have this high CPU processing.

**Comment by basisbit** [comment]
For support requests, please use the [forum / mailing list](https://groups.google.com/forum/#!forum/bigbluebutton-setup). This issue tracker here is only for BBB development related issues. Sorry.

**Comment by cod3r0k** [comment]
> For support requests, please use the [forum / mailing list](https://groups.google.com/forum/#!forum/bigbluebutton-setup). This issue tracker here is only for BBB development related issues. Sorry.
> 
> Also, please do not ping people in new issues. We are not your paid-for commercial support.

Dear @basisbit , I found this problem and I just want to said that maybe it is a fault in BBB 2.3.7 and we are here to solve these issues of BBB for developing a best version forever! isn't it?  I can't digest your answer.

**Comment by cod3r0k** [comment]
Maybe you can say that in ESXI 6.5 or lower version of ESXI, BBB could be failed and never use this version or these specification ...

I think this could be an answer and not as you answer me! 

> For support requests, please use the [forum / mailing list](https://groups.google.com/forum/#!forum/bigbluebutton-setup). This issue tracker here is only for BBB development related issues. Sorry.
> 
> Also, please do not ping people in new issues. We are not your paid-for commercial support.

**Comment by cod3r0k** [comment]
What's your idea @antobinary and @ffdixon ? Am I saying a bad thing to basisbit ?

We are here to solve the BBB problems in different situation. I'm announcing you because I found that you can see this issue earlier than anybody facing an error.

**Comment by cod3r0k** [comment]
Also, I test this in create a session event and found that it was again happened in 2.3.7 .


![image](https://user-images.githubusercontent.com/36899025/109322674-d080d200-7867-11eb-97d1-a5004876745a.png)

**Comment by basisbit** [comment]
You provide almost no information - it is difficult to comment on that. Sadly we can't just put our hands on the server and instantly know what is wrong. Please check your logs, try to find out what the server is doing. You could also try it giving the server the recommended 16GB of RAM solved the problem.

**Comment by cod3r0k** [comment]
> You provide almost no information - it is difficult to comment on that. Sadly we can't just put our hands on the server and instantly know what is wrong. Please check your logs, try to find out what the server is doing. You could also try if giving the server the recommended 16GB of RAM solved the problem.

Dear @basisbit , I clearly put my server config in the first comment.  

Also you can see at my pictures that my RAM is not full and it is use just 3.1GB from 10 GB. Therefore, I think it is related to the BBB which can't handle the resource.
