### ISSUE TITLE
Afteer update to 2.2.33 i get error 1002 when trying to connect to the audio session. It worked minutes before the update perfectly fine.

### ISSUE THREAD

**Issue by DDQW** [bigbluebutton/bigbluebutton#11517]
fixed

**Comment by ffdixon** [comment]
How did you upgrade -- [step-by-step](https://docs.bigbluebutton.org/2.2/install.html#upgrading-from-bigbluebutton-22) or using [bbb-install.sh](https://github.com/bigbluebutton/bbb-install)?

**Comment by DDQW** [comment]
i updated using apt upgrade like always (so far that was not a problem)

**Comment by DDQW** [comment]
i did the step by step now and ran dist-upgrade it found nothing new

**Comment by DDQW** [comment]
can be closed its fixed. 

i am not exactly sure why it works now i didnt change anything except the repos which pulled no updates.

weired
