### ISSUE TITLE
[2.3] Cannot read property 'posJoinMessages' of undefined

### ISSUE THREAD

**Issue by daminebenq** [bigbluebutton/bigbluebutton#11528]
Switching between private and public chat gives `Cannot read property 'posJoinMessages' of undefined`, with a client crash (audio remains connected).

![image](https://user-images.githubusercontent.com/5144311/109644724-a0ba1e80-7b34-11eb-9514-fb870523b0f3.png)

**PS:** This happens inconsistently, and it should be retested.

**Comment by daminebenq** [comment]
Just to confirm this is still reproducible, but also still inconsistently happening.

**Comment by antobinary** [comment]
Reopening - see @GyR4uk 's comments in https://github.com/bigbluebutton/bigbluebutton/pull/11676
