### ISSUE TITLE
WebSocket Connection Error - 1002

### ISSUE THREAD

**Issue by lterlecki** [bigbluebutton/bigbluebutton#11534]
**Describe the bug**
After upgrade bbb by apt: bbb-html5:amd64 (1:2.2.0-1114 --> 1:2.2.0-1140), bbb-etherpad:amd64 (1:2.2.0-66 --> 1:2.2.0-69), bbb-web:amd64 (1:2.2.0-150 --> 1:2.2.0-151), bbb-fsesl-akka:amd64 (2.2.0-73 --> 2.2.0-74), bbb-apps-akka:amd64 (2.2.0-97 --> 2.2.0-100), bbb-config:amd64 (1:2.2.0-234 --> 1:2.2.0-236), bbb-webrtc-sfu:amd64 (1:2.2.0-110 --> 1:2.2.0-114) I have problem on any device to connect microphone, I have an 1002 error. I have any problem when I've connect to https://test.bigbluebutton.org or https://test.webrtc.org, everything work's fine.

**To Reproduce**
No idea.

**Expected behavior**
Everything works fine?

**Actual behavior**
Now I can create room, start meeting, show presentation, share screen, but without sound stream.

**Screenshots**
![obraz](https://user-images.githubusercontent.com/22658233/109693580-1dc3b300-7b8a-11eb-844c-79b48f6b6b0a.png)

**Desktop (please complete the following information):**
 - OS: Linux Mint 20.1
 - Browser: Firefox 86, Opera 69, Chromium 88

**Server (please complete the following information):**
 - OS: Ubuntu 16.04
 - bbb version: 2.2.33
 - CPU: 8
 - RAM: 16GB

**Additional context**
bbb-conf --check:
`BigBlueButton Server 2.2.33 (2347)
                    Kernel version: 4.4.0-203-generic
                      Distribution: Ubuntu 16.04.7 LTS (64-bit)
                            Memory: 16431 MB
                         CPU cores: 8

/usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties (bbb-web)
       bigbluebutton.web.serverURL: https://bbb.mydomain.pl
                defaultGuestPolicy: ALWAYS_ACCEPT
                 svgImagesRequired: true

/etc/nginx/sites-available/bigbluebutton (nginx)
                       server_name: bbb.mydomain.pl
                              port: 80, [::]:80
                              port: 443 ssl

/opt/freeswitch/etc/freeswitch/vars.xml (FreeSWITCH)
                       local_ip_v4: 146.XX.Y.ZZZ
                   external_rtp_ip: 146.XX.Y.ZZZ
                   external_sip_ip: 146.XX.Y.ZZZ

/opt/freeswitch/etc/freeswitch/sip_profiles/external.xml (FreeSWITCH)
                        ext-rtp-ip: $${external_rtp_ip}
                        ext-sip-ip: $${external_sip_ip}
                        ws-binding: 146.XX.Y.ZZZ:5066
                       wss-binding: 146.XX.Y.ZZZ:7443

/usr/local/bigbluebutton/core/scripts/bigbluebutton.yml (record and playback)
                     playback_host: bbb.mydomain.pl
                 playback_protocol: https
                            ffmpeg: 4.2.4-1ubuntu0.1bbb1~16.04.1

/etc/bigbluebutton/nginx/sip.nginx (sip.nginx)
                        proxy_pass: 146.XX.Y.ZZZ
                          protocol: http

/usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml (Kurento SFU)
                        kurento.ip: 146.XX.Y.ZZZ
                       kurento.url: ws://127.0.0.1:8888/kurento
                    kurento.sip_ip: 146.XX.Y.ZZZ
                    localIpAddress: 146.XX.Y.ZZZ
               recordScreenSharing: true
                     recordWebcams: true
                  codec_video_main: VP8
               codec_video_content: VP8

/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml (HTML5 client)
                             build: 1140
                        kurentoUrl: wss://bbb.mydomain.pl/bbb-webrtc-sfu
                  enableListenOnly: true
                    sipjsHackViaWs: true

/usr/share/bbb-web/WEB-INF/classes/spring/turn-stun-servers.xml (STUN Server)
                              146.XX.Y.ZZZ

# Potential problems described below

root@bbb:~#`

I have no idea what's going on, in freeswitch logs I have any error, just notice and debug lines.

**Comment by ffdixon** [comment]
> After upgrade bbb by apt

You need to also run `bbb-conf --setip` as per the docs.  https://docs.bigbluebutton.org/2.2/install.html#upgrading-from-bigbluebutton-22

**Comment by lterlecki** [comment]
> > After upgrade bbb by apt
> 
> You need to also run `bbb-conf --setip` as per the docs. https://docs.bigbluebutton.org/2.2/install.html#upgrading-from-bigbluebutton-22

I did it, before setip I had error 1006.

**Comment by lrit18** [comment]
i have the same mistake too.

after I tried to repair it, I get the message 

# Warning: You have this server defined for https, but in
#
#   /etc/bigbluebutton/nginx/sip.nginx
#
#  did not find the use of port 7443 in definition for proxy_pass
#
#            proxy_pass https://xxx:5066;

when i enter sudo bbb-conf --check

when i change the port from 5066 to 7443 i have the same issue like in 
https://github.com/bigbluebutton/bigbluebutton/issues/11552 on my other server

**Comment by lrit18** [comment]
@lterlecki maybe this works for you:
https://github.com/bigbluebutton/bigbluebutton/issues/8514
after i do that in #8514 and then running bbb-conf --setip mybbb.domain.org it solves my issue.

**Comment by lterlecki** [comment]
> @lterlecki maybe this works for you:
> #8514
> after i do that in #8514 and then running bbb-conf --setip mybbb.domain.org it solves my issue.

I did it on every upgrade, in this case didn't work.

**Comment by mk-hs** [comment]
> Note: As of BigBlueButton 2.2.29 (and later), you can have nginx proxy incoming WSS connections to WS on port 5066 to work around a bug in FreeSWITCH. If you are using 2.2.29 or later, you can run the following BASH script to implement the workaround. 

> If you use bbb-install.sh to install/upgrade BigBlueButton, it will automatically apply [the above] changes. If you manually upgrade your BigBlueButton server, you can add the above lines to apply-conf.sh to have the above settings applied by bbb-conf when doing the manually upgrade steps.

https://docs.bigbluebutton.org/2.2/install.html#configure-freeswitch-for-using-ssl

**Comment by basisbit** [comment]
For support requests, please use the [forum / mailing list](https://groups.google.com/forum/#!forum/bigbluebutton-setup). This issue tracker here is only for BBB development related issues. Sorry.

**Comment by Rhywden** [comment]
Oh, so I see, your updates break stuff but that's not a development issue. Bravo for that!

**Comment by caos30** [comment]
Ok, i would like to remember here to **open port 7443 for --UDP-- protocol in the firewall** !! 

The audio and video on my BBB server room didn't worked until i opened it. Until now (during the past years) i only had opened that port for TCP protocol and it was enough, but i think that after i upgraded today my ubuntu server and BBB then the audio & video don't worked anymore, getting on web browser this error:
```
0 - Failed to construct 'WebSocket': An insecure WebSocket connection 
may not be initiated from a page loaded over HTTPS.
```

Obviously, i also had to modify the file `/usr/share/bigbluebutton/nginx/sip.nginx` to replace:
```
proxy_pass http://xxx.xxx.xxx.xxx:5066;
```
by:
```
proxy_pass https://xxx.xxx.xxx.xxx:7443;
```
and then reboot server.

I'm leaving this message here to the less expert admin users ☺️
