### ISSUE TITLE
[2.3.0-alpha7] Presentation not taking full width

### ISSUE THREAD

**Issue by enaut** [bigbluebutton/bigbluebutton#11536]
**Describe the bug**
When trying to toggle the full width button on the presentation it does not take the full width:
![Präsentation](https://user-images.githubusercontent.com/290005/109702674-d2fb6880-7b94-11eb-9d6f-ff7b956d3ebe.png)

even though the button is clicked the presentation does not go to full width.

**To Reproduce**
1. Upload a portrait mode presentation
2. click on "adjust to width" (translated highlighted in the image above)
4. See that the presentation width is not really increased

**Expected behavior**
The presentation is as wide as the space available

**Actual behavior**
The Presentation has "whitespace" left and right

**"Workaround":**
It is possible to achieve the desired result using the developer tools (Although its not perfect as one cannot scroll the whole document):

By selecting:
1. the presentation svg
2. then the first child which is the pdf
3. of this element set
    4. `width` to 100%
    5. `height` disabled

see the screenshot below:

![full-width-presentation](https://user-images.githubusercontent.com/290005/109703925-549fc600-7b96-11eb-827d-af93e99e925c.png)

**Screenshots**

**BBB version (optional):**
BigBlueButton continually evolves. Providing the version/build helps us to pinpoint when an issue was introduced.
Example:
$ sudo bbb-conf --check | grep BigBlueButton
BigBlueButton Server 2.3.0-alpha7 (1652)

**Desktop (please complete the following information):**
 - OS: different
 - Browser firefox, chrome

**Comment by hiroshisuga** [comment]
I believe this will be fixed by #11532.

**Comment by enaut** [comment]
@hiroshisuga thanks for the hint! I can confirm that it works when at least one webcam is active so it looks indeed like #11532 will fix this.

**Comment by enaut** [comment]
I'll close this for now and hope this gets included soon.
