### ISSUE TITLE
Shared notes download broken in 2.2.34 (possibly related to #11535)

### ISSUE THREAD

**Issue by ichdasich** [bigbluebutton/bigbluebutton#11545]
**Describe the bug**
After upgrading to 2.2.34, which merged #11535, downloading shared notes gives a 401 instead of providing a download.

**To Reproduce**
1. Start a meeting
2. Type in shared notes
3. Attempt to download shared notes, e.g., as a PDF
4. Receive a 401

**Expected behavior**
The shared notes are successfully downloaded.

**Actual behavior**
Authorization to the resource is denied.

**Additional context**
This occurs after an upgrade to 2.2.34. Removing the auth statement in notes.nginx or reverting it as follows restores the desired functionality:
```
 16     #auth_request /bigbluebutton/connection/validatePad;                        
 17     auth_request /bigbluebutton/connection/checkAuthorization;                  
 18     auth_request_set $auth_status $upstream_status;       
```
~~I did not in-depth go over the potential security impact of this. I assume, however, that it may disable auth (see below).~~

~~Furthermore, I see the following issues in #11535:~~
- ~~The change to `bigbluebutton-web/grails-app/controllers/org/bigbluebutton/web/UrlMappings.groovy`  removes `/connection/checkAuthorization` but does not introduce an endpoint for `/connection/validatePad`.~~
- ~~With `/connection/checkAuthorization` removed, technical the revert should not work (unless without a UrlMapping we always get a 200, which would effectively disable auth as well)~~

Edit: 
as @prlanzarin just commented on the dev ML, these are internal routes that don't have to be in `UrlMappings.groovy`; Hence the hotfix should also only revert to old behavior.

**Comment by pedrobmarin** [comment]
Fixed in https://github.com/bigbluebutton/bigbluebutton/releases/tag/v2.2.35
