### ISSUE TITLE
Scanned pdf problem

### ISSUE THREAD

**Issue by crog3ar** [bigbluebutton/bigbluebutton#11541]
**Describe the bug**
I wrote some exams on paper and scanned them to .pdf. I simply uploaded pdf to bbb and it's showing only some lines without numbers and leters. 

**To Reproduce**
Simply try to upload attached pdf to meeting.

[AV1_riješeni zadaci.pdf](https://github.com/bigbluebutton/bigbluebutton/files/6075885/AV1_rijeseni.zadaci.pdf)

P.S.
If i convert same exact pdf to docx everything works fine. (attaching docx)
[AV1_riješeni zadaci.docx](https://github.com/bigbluebutton/bigbluebutton/files/6075923/AV1_rijeseni.zadaci.docx)

**BBB version (optional):**
BigBlueButton Server 2.2.31

**Desktop (please complete the following information):**
 Windows 10

**Comment by ffdixon** [comment]
Thanks for reporting this.  Merged into https://github.com/bigbluebutton/bigbluebutton/issues/9680.
