### ISSUE TITLE
Countdown not working

### ISSUE THREAD

**Issue by jannis6023** [bigbluebutton/bigbluebutton#11551]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Actual behavior**

**Screenshots**

**BBB version (optional):**
BigBlueButton continually evolves. Providing the version/build helps us to pinpoint when an issue was introduced.
Example:
$ sudo bbb-conf --check | grep BigBlueButton
BigBlueButton Server 2.2.2 (1816)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, Mac]
 - Browser [e.g. Chrome, Safari]

**Smartphone (please complete the following information):**
 - Browser [e.g. stock browser, Safari]

**Additional context**

**Comment by jannis6023** [comment]
If you are in a breakout room, leave the audio and reconnect the audio, the countdown restarts from the beginning.

**Comment by antobinary** [comment]
Hi @jannis6023 
Thanks for reporting this. What version of BigBlueButton did you encounter this on? 2.2.34 or 2.3-alpha7 perhaps?Is it easily reproducible?

**Comment by basisbit** [comment]
@jannis6023 please fill in the issue template in the issue description.
