### ISSUE TITLE
Clearer version of BBB in ubuntu packages

### ISSUE THREAD

**Issue by bilias** [bigbluebutton/bigbluebutton#11554]
Alhough in github there is clear version system of BBB,
ubuntu packages installed follow a different scheme.

# dpkg -s bbb-config
Package: bbb-config
Status: install ok installed
Priority: extra
Section: default
Installed-Size: 2734
Maintainer: ffdixon@bigbluebutton.org
Architecture: amd64
Version: 1:2.2.0-235

Could be nice if bbb version was included in the package version.

**Comment by ichdasich** [comment]
Duplicate of #9107, i'd say. ;-)

**Comment by bilias** [comment]
> Duplicate of #9107, i'd say. ;-)

sure :)
