### ISSUE TITLE
API checksum hashes should be case-insensitive

### ISSUE THREAD

**Issue by ethrgeist** [bigbluebutton/bigbluebutton#11561]
**Describe the bug**
The query checksum for the REST API can be a SHA1 or SHA256 hash, but the query fails with

```xml
<response>
  <returncode>FAILED</returncode>
    <messageKey>checksumError</messageKey>
  <message>You did not pass the checksum security check</message>
</response>
```

if the the hash is written with uppercase letters, while lowercase letters work just fine.

**To Reproduce**
1. Try <https://test-install.blindsidenetworks.com/bigbluebutton/api/create?allowStartStopRecording=true&attendeePW=ap&autoStartRecording=false&meetingID=random-3110272&moderatorPW=mp&name=random-3110272&record=false&voiceBridge=70860&welcome=%3Cbr%3EWelcome+to+%3Cb%3E%25%25CONFNAME%25%25%3C%2Fb%3E%21&checksum=bd74bc3c07945eef284118f1cd6e09463c7a49ea>
Which should work
3. Try <https://test-install.blindsidenetworks.com/bigbluebutton/api/create?allowStartStopRecording=true&attendeePW=ap&autoStartRecording=false&meetingID=random-3110272&moderatorPW=mp&name=random-3110272&record=false&voiceBridge=70860&welcome=%3Cbr%3EWelcome+to+%3Cb%3E%25%25CONFNAME%25%25%3C%2Fb%3E%21&checksum=BD74BC3C07945EEF284118F1CD6E09463C7A49EA>
Which will fail

**Expected behavior**
The checksum hash should work regardless of lower or upper case, since `HEX` does not differentiate between lower and upper case. It's just 0-9 and a-f and both forms represent the same hash value.

**Actual behavior**
Lower case works, upper case does not.

**Additional context**
Possible solutions from my point of view:

- Document that only hashes with lower case letters will be accepted (and maybe throw a better to read error)
- Accept upper case hashes and convert them to lower case internally if that is needed.

**Comment by basisbit** [comment]
alternative solution: convert the hash to lower-case before sending the API request

**Comment by eth3rgeist** [comment]
That would be Option 1 and i'd prefer if the documentation would reflect that. I spend a bit of time to debug this issue and trying different methods to build the string and the hash, only to realize that only lower cases are excepted.

Chances are, that i am not the only one that has hit this issue.
