### ISSUE TITLE
Исправления Greenlight, отображение сторонних комнат

### ISSUE THREAD

**Issue by nikkei00** [bigbluebutton/bigbluebutton#11567]
1. I propose to make it so that in Greenlight you can see rooms that are created or used through third-party applications (moodle and others), and you can also join these rooms as a moderator (if admin is in Greenlight) and as a user (if a user is in Greenlight).
2. I suggest to add in Greenlight in the "Server Rooms" section sorting by the "Status" column to sort and see which rooms are running in the heap. (On a permanent basis, make the running rooms rise up the table of the list of rooms???)
3. I suggest that you highlight the line in which the room is started with a green fill (it is very convenient to search for a room or check whether the conference was finished correctly)
![0208](https://user-images.githubusercontent.com/64165027/110155648-55876080-7dff-11eb-8e82-4cf67710b02e.png)

4. Correct hyphenation for long names of ROOMS and RECORDS, because of the long name, the table stretches to the right beyond the screen very far

**Comment by antobinary** [comment]
Hi @nikkei00,

Woulld you be able to open this in https://github.com/bigbluebutton/greenlight instead?
