### ISSUE TITLE
Default presentation not show in bigbluebutton strating page

### ISSUE THREAD

**Issue by mahmoudabdelhalim** [bigbluebutton/bigbluebutton#11576]
**Describe the bug**
The default presentation does not show in bigbluebutton when open the session and working when uploading from Mange Presentation.
And when access the pdf link https://domain.com/default.pdf I got it and displayed the file.

**Expected behavior**
Showing the default presentation when starting the session.

**Screenshots**
![image](https://user-images.githubusercontent.com/16545049/110255375-ff035900-7f9b-11eb-9154-b0c8a42d8438.png)

**BBB version (optional):**
$ sudo bbb-conf --check | grep BigBlueButton
BigBlueButton Server 2.3.0-alpha7 (1650)

**Comment by ffdixon** [comment]
Thanks -- we're seeing this issue as well and working on it.

**Comment by mahmoudabdelhalim** [comment]
Any updates @antobinary

**Comment by ffdixon** [comment]
We should have 2.3-alpha8 our shortly for you to test.

**Comment by antobinary** [comment]
Hi @mahmoudabdelhalim 
https://github.com/bigbluebutton/bigbluebutton/pull/11650 should solve this - we investigated two instances of this happening on a server and in both cases there was an incorrect order of events in the beginning of the meeting. The CreateMeetingEvtMsg which we use to start aggregating info about the meeting should be the first message to receive from `akka-apps` but in both cases where we saw the issue the message used for initializing the meeting's presentation pod arrived prior to CreateMeetingEvtMsg and was thus ignored.

This was fixed after 2.3-alpha8 was released, so it will be included in the following release.
I will be closing this issue now but if you (or anyone) spot a similar problem in the future we can reopen.
Thanks for reporting it!

**Comment by mahmoudabdelhalim** [comment]
Hi @antobinary 
Thanks for you keeping in contact, After I have updated to 2.3-alpha8 still default presentation not showing when starting the session.
Any advice?

**Comment by antobinary** [comment]
Hi @mahmoudabdelhalim 

>This was fixed after 2.3-alpha8 was released, so it will be included in the following release.

We are releasing the fix (and other improvements) later this week. I just updated https://test23.bigbluebutton.org/demo/demo2.jsp (so it includes the fix). Could you please try to reproduce the issue on that server?

**Comment by mahmoudabdelhalim** [comment]
Hi @antobinary,
Okay, that's good.
https://test23.bigbluebutton.org/demo/demo2.jsp and I see the presentation working.
