### ISSUE TITLE
Meeting stops and kick all user due inactivity

### ISSUE THREAD

**Issue by SebastianZiegler** [bigbluebutton/bigbluebutton#11571]
Hello, 

we use bbb for proctoring in our exams, today we had a strange problem, 3 proctoring meetings seems to been killed due inactivity. Depending on time the meeting get killes, there thems to be an timer of 120 minutes for inactivity. How can we prevent that, any ideas? 
Here are the log files:

Mar  6 10:06:45 bbb4 bbb-apps-akka[23645]: 2021-03-06T10:06:45.240+01:00 INFO  o.b.core2.AnalyticsActor - -- analytics -- {"envelope":{"name":"MeetingEndingEvtMsg","routing":{"msgType":"BROADCAST_TO_MEETING","meetingId":"2b7c65b24f77973d76331ae483c2dc843fbd70ba-1615011287150","userId":"not-used"},"timestamp":1615021605239},"core":{"header":{"name":"MeetingEndingEvtMsg","meetingId":"2b7c65b24f77973d76331ae483c2dc843fbd70ba-1615011287150","userId":"not-used"},"body":{"meetingId":"2b7c65b24f77973d76331ae483c2dc843fbd70ba-1615011287150","reason":"ENDED_DUE_TO_INACTIVITY"}}}
Mar  6 10:06:45 bbb4 bbb-apps-akka[23645]: 2021-03-06T10:06:45.243+01:00 INFO  o.b.core.running.MeetingActor - Meeting 2b7c65b24f77973d76331ae483c2dc843fbd70ba-1615011287150 expired with reason ENDED_DUE_TO_INACTIVITY

Greeting
Sebastian

**Comment by fnord235** [comment]
Hey there,
there are some parameters in the following configuration file related to this, although default is set to a 30 minute threshold and it should warn participants before ending the meeting. So I don't know if the behaviour is really linked to this settings, but I suppose it is worth a try.
 
Relevant extract from /usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties:
```
# User inactivity audit timer interval.
userInactivityInspectTimerInMinutes=0

# Number of minutes to consider a user inactive.
# iSend warning message to client to check if really inactive.
userInactivityThresholdInMinutes=30

# Number of minutes for user to respond to inactivity
# warning before being logged out.
userActivitySignResponseDelayInMinutes=5
```

Good luck, I hope this helps!

**Comment by basisbit** [comment]
Closing this issue as it is configuration and known behavior. There already exist a couple of other issues to improve the behavior in the future.
Activity for BBB is when more than one webbrowser user is connected to the FreeSWITCH audio (connected with microphone, not just listen only). You can disable this in the BBB server configuration or increase the Timeout.
