### ISSUE TITLE
on a small sized screen pollingContainer appears on top of audioModal after refreshing the page

### ISSUE THREAD

**Issue by daminebenq** [bigbluebutton/bigbluebutton#11577]
To reproduce:
1. Go to bbb23 server with 2 users
2. Create Polling from first user and start it
3. On the second user, reload the page
4. See result

Current behavior:

https://user-images.githubusercontent.com/5144311/110259878-9f4f8280-7f88-11eb-9837-987c4993de5e.mp4

Expected behavior:

pollingContainer should not appear with an overlay, and it should not avoid access to the rest of the page elements.

**Comment by antobinary** [comment]
Hmm, not sure if this is a bug or desired behavoir. There was recent work to address the issue of polling options not overlapping full-screen screenshare (or modals). There the descision was made to overlap to ensure the vote for poll takes precendence. It would take a redesign / reimplementation of the modal system to support different layers of controls (a bit like minimizing) and some might argue that such approach would interfere with user focus / accessibility
