### ISSUE TITLE
race condition on startup between meteor and mongo

### ISSUE THREAD

**Issue by BrentBaccala** [bigbluebutton/bigbluebutton#11580]
It is possible for mongod to have started but not yet be listening on port 27017 when the meteor server tries to connect.  In this case, one or more of the bbb-html5-worker processes will fail to start.  `systemctl status bbb-html5-worker*` will show something like this:

    ubuntu@test:~$ systemctl status bbb-html5-worker@1
    ● bbb-html5-worker@1.service - BigBlueButton HTML5 service, instance 1
       Loaded: loaded (/usr/lib/systemd/system/bbb-html5-worker@.service; disabled; vendor preset: enabled)
       Active: failed (Result: exit-code) since Mon 2021-03-08 04:53:06 UTC; 22min ago
     Main PID: 24482 (code=exited, status=1/FAILURE)
    
    Mar 08 04:53:06 test systemd_start.sh[24482]: Initializing replicaset
    Mar 08 04:53:06 test systemd_start.sh[24482]: MongoDB shell version v4.2.12
    Mar 08 04:53:06 test systemd_start.sh[24482]: connecting to: mongodb://127.0.1.1:27017/test?compressors=disabled&gssapiServiceName=
    Mar 08 04:53:06 test systemd_start.sh[24482]: 2021-03-08T04:53:06.780+0000 E  QUERY    [js] Error: couldn't connect to server 127.0
    Mar 08 04:53:06 test systemd_start.sh[24482]: connect@src/mongo/shell/mongo.js:353:17
    Mar 08 04:53:06 test systemd_start.sh[24482]: @(connect):2:6
    Mar 08 04:53:06 test systemd_start.sh[24482]: 2021-03-08T04:53:06.785+0000 F  -        [main] exception: connect failed
    Mar 08 04:53:06 test systemd_start.sh[24482]: 2021-03-08T04:53:06.785+0000 E  -        [main] exiting with code 1
    Mar 08 04:53:06 test systemd[1]: bbb-html5-worker@1.service: Main process exited, code=exited, status=1/FAILURE
    Mar 08 04:53:06 test systemd[1]: bbb-html5-worker@1.service: Failed with result 'exit-code'.

**Comment by znerol** [comment]
I suggest to add `Restart=on-failure` to the `Service` section in the `bbb-html5-worker@.service` unit file (see [systemd.service(5)](https://manpages.ubuntu.com/manpages/bionic/en/man5/systemd.service.5.html))

**Comment by antobinary** [comment]
> I suggest to add Restart=on-failure to the Service section in the bbb-html5-worker@.service unit file (see systemd.service(5))

Implemented in https://github.com/bigbluebutton/bigbluebutton/pull/13527

**Comment by antobinary** [comment]
We have not seen this happen since we implemented the suggested solution with Restart=on-failure, see https://github.com/bigbluebutton/bigbluebutton/blob/v2.5.x-release/build/packages-template/bbb-html5/bbb-html5-frontend%40.service#L20 Thank you for that suggestion!

Please comment if you see anything similar to this in the future!
