### ISSUE TITLE
Image Upload does not work in 2.2.35

### ISSUE THREAD

**Issue by FaeyUmbrea** [bigbluebutton/bigbluebutton#11586]
**Describe the bug**
When you upload a PNG or JPEG image in BBB 2.2.35, the result produces a blank slide and the backend produces a "Failed to create svg images." error.

**To Reproduce**
1. Start a meeting
2. Click on upload presentation
3. Upload any png or jpeg
4. See blank slide
5. Find error message in the backend logs

**Expected behavior**
The image to show up in the presentation space

**Actual behavior**
Blank presentation space 

**Screenshots**
![image](https://user-images.githubusercontent.com/1144986/110359735-20b51c80-803e-11eb-99fd-deddfa75eba4.png)
![image](https://user-images.githubusercontent.com/1144986/110359760-29a5ee00-803e-11eb-944f-d45c3423b0fd.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome, Firefox and Edge Chromium
 - Version latest respective version (updated before test)

**Additional context**
It only occurs in 2.2.35 not in 2.2.34. I do not have servers to test earlier versions on.

**Comment by daminebenq** [comment]
Hi @FaeyUmbrea 
I just tested with [this PNG File](https://user-images.githubusercontent.com/5144311/110361516-e6885280-801e-11eb-8cd9-a6b0bae4229d.png) in a recent version of 2.2, and i couldn't reproduce what you described. So can you please retest it ?

**Comment by FaeyUmbrea** [comment]
Hi @daminebenq 
Please make sure to test specifically on 2.2.35 to reproduce as it occurs specifically on those machines for me
https://i.imgur.com/wsCjLXH.gif

I cut out the user list for safety reasons.
The error is also not limited to my system. Several users have reported it so far. It might be a configuration issue, but bbb-conf --check reported no issues.

**Comment by basisbit** [comment]
@FaeyUmbrea can you reproduce this problem at https://test.bigbluebutton.org/ ?

**Comment by FaeyUmbrea** [comment]
@basisbit 
I can not reproduce on the test site. 
Also about 128GB

**Comment by basisbit** [comment]
For this support requests, please use the [forum / mailing list](https://groups.google.com/forum/#!forum/bigbluebutton-setup). This issue tracker here is only for BBB development related issues. Sorry. Uploading to the test install worked, so it most likely is a setup or configuration problem - those are best discussed in the mailing list / forum, where more people from the community will help you.

**Comment by daminebenq** [comment]
@FaeyUmbrea May I have the png file you're using it to test ?
I'm testing in both of production and development servers, with many images extensions files, and didn't arrive to get in any problems.
```
BigBlueButton Server 2.2.35 (2411)
```
