### ISSUE TITLE
Rare error 1006, "partial service crash"

### ISSUE THREAD

**Issue by inDane** [bigbluebutton/bigbluebutton#11583]
**Describe the bug**
Users cannot join audio. Join via Microphone tries to connect to the echo test, but results in error (1006). It doesn't show anything if "Just listening" is selected, but nothing happens either. Users are just stuck here.

**To Reproduce**
None, I don't know.

**Additional context**
I do not know how to trigger this error. If I would restart the service, everything would work as usual. This condition is very rare.
Once the service is in this state, bbb-conf --check gives this:

```
 # Potential problems described below
 
 # Warning: You have this server defined for https, but in
 #
 #   /etc/bigbluebutton/nginx/sip.nginx
 #
 #  did not find the use of https in definition for proxy_pass
 #
 #            proxy_pass http://<ip>:5066;
 #
 
 # Warning: You have this server defined for https, but in
 #
 #   /etc/bigbluebutton/nginx/sip.nginx
 #
 #  did not find the use of port 7443 in definition for proxy_pass
 #
 #            proxy_pass http://<ip>:5066;
 
```
After a fresh restart of the service, this is not showing up.

/etc/bigbluebutton/nginx/sip.nginx is in fact not proxying to 7443. 

```
location /ws {
        proxy_pass http://<ip>:5066;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_read_timeout 6h;
        proxy_send_timeout 6h;
        client_body_timeout 6h;
        send_timeout 6h;

        auth_request /bigbluebutton/connection/checkAuthorization;
        auth_request_set $auth_status $upstream_status;
}
```
But why is it working after a restart of the service (and working for weeks) and then suddenly changing to this state?

I will leave the server in this state, in case you want me to test something.

**Comment by basisbit** [comment]
For support requests, please use the [forum / mailing list](https://groups.google.com/forum/#!forum/bigbluebutton-setup). This issue tracker here is only for BBB development related issues. Sorry.

The freeswitch signaling traffic being redirected to the ws port is a workaround for a known bug in FreeSWITCH websocket TLS handling. That is as intended, that warning can be ignored. For the occasional 1006 error, please make sure you operate your own TURN+STUN server and then ask for support in the above mentioned mailing list / forum, where more people from the community will help you.

**Comment by inDane** [comment]
> For support requests,
I do not see this as a support request, I am rather pointing out a rare bug. This server behavior is not expected.

> For the occasional 1006 error, please make sure you operate your own TURN+STUN server
I do have a a working TURN server of course. The "partial crashed BBB" wont accept any audio connections. Not from TURN nor directly. I tested this with Firefox (media.peerconnection.ice.relay_only).

Once I reboot the server again, it will run again for weeks...

**Comment by inDane** [comment]
Looks like you are right and this is a problem on my side. Yet I do not understand how this one occurs :thinking:
