### ISSUE TITLE
npm start got started ... but didn't get complete

### ISSUE THREAD

**Issue by jhamobi** [bigbluebutton/bigbluebutton#11594]
I am new to bigbluebutton. 
I am following https://docs.bigbluebutton.org/2.2/dev.html this link for setting up the development environment for Bigbluebutton.
In this link i am not able to execute the npm start command.

Thanks for reading

![WhatsApp Image 2021-03-08 at 6 36 56 AM](https://user-images.githubusercontent.com/65014913/110488250-4f052b80-8114-11eb-828a-dce33ea6703a.jpeg)

**Comment by basisbit** [comment]
For support requests, please use the [forum / mailing list](https://groups.google.com/forum/#!forum/bigbluebutton-dev). This issue tracker here is only for BBB project development related issues. Sorry.
