### ISSUE TITLE
exceptions accessing storageLData

### ISSUE THREAD

**Issue by BrentBaccala** [bigbluebutton/bigbluebutton#11597]
I'm seeing intermittent failures when the HTML5 client loads that result in a blank screen.

The Javascript console shows an exception trying to access non-existent properties in storageLData in calculatesPanelsSize.

Adding some debugging (a console.log near the beginning of calculatesPanelsSize) shows what storageLData looks like at the start of this function:

![image](https://user-images.githubusercontent.com/5731463/110583014-0876f780-813b-11eb-8cef-9b543b1159a2.png)

So, clearly, trying to access "pollSize" and "noteSize" is going to cause problems.  I've fixed the problem on my system by adding some tests a few lines into calculatesPanelsSize:

    if (storageLData) {
      if (storageLData.userListSize) storageUserListWidth = storageLData.userListSize.width;
      if (storageLData.chatSize) storageChatWidth = storageLData.chatSize.width;
      if (storageLData.pollSize) storagePollWidth = storageLData.pollSize.width;
      if (storageLData.noteSize) storageNoteWidth = storageLData.noteSize.width;
      if (storageLData.breakoutRoomSize) storageBreakoutRoomWidth = storageLData.breakoutRoomSize.width;
    }

Since I don't really understand this code, I'm not proposing this as a PR.

More investigation is required.

**Comment by antobinary** [comment]
Related to https://github.com/bigbluebutton/bigbluebutton/pull/11600

**Comment by BrentBaccala** [comment]
Fixed by PR #11600
