### ISSUE TITLE
Screenshare may causes layout problem

### ISSUE THREAD

**Issue by lkiesow** [bigbluebutton/bigbluebutton#11610]
**Describe the bug**

Under some conditions, the layout of BigBlueButton breaks if a user starts sharing a screen, causing webcams to be partially hidden and webcams to overlap screenshare (note that the mouse cursor in the following picture is right on top of the devider):

![mpv-shot0002](https://user-images.githubusercontent.com/1008395/110691433-6d872780-81e5-11eb-9622-01bdbfbab320.jpg)

**To Reproduce**

Probably not the only way to reproduce it and not sure if all steps are necessary but this more or less reliably causes the issue to appear:

1. Make sure another person is in the session and has a webcam shared
2. Take Firefox (tested with 85.0.1 (64-bit) on Fedora Linux)
3. Join the session
4. Share webcam
5. Minimize slide
6. Take presenter
7. Share screen

https://user-images.githubusercontent.com/1008395/110691934-0fa70f80-81e6-11eb-8139-2ab4ae46bcd3.mp4

**BBB version:**
BigBlueButton 2.3-alpha-7 up to at least 2.3-beta-3

**Desktop (please complete the following information):**
 - OS: Fedora Linux 33
 - Browser: Firefox 85.0.1 (64-bit)

**Additional context**
- Moving the layout manually fixes the problem
- Stop sharing, then share again fixes the problem (only happens once after entering the room)

**Comment by lkiesow** [comment]
There seem to be more issues with the layout arrangement.

This happened again after joining. Note that the cameras should be arranged in a row and that parts of the presentation are missing including controls like the button which should be in the top right corner:

![Screenshot from 2021-03-11 14-37-57](https://user-images.githubusercontent.com/1008395/110798115-20a16080-827a-11eb-9005-274210535169.png)


And this happened after a number of people left the meeting:

![Screenshot from 2021-03-11 14-32-37](https://user-images.githubusercontent.com/1008395/110798200-36168a80-827a-11eb-8acf-44f5c6d624d7.png)

**Comment by daminebenq** [comment]
I believe that we don't have this problem anymore, i couldn't reproduce it in my dev environment.
But sure, let's keep an eye on it.
Thanks for reporting !!

**Comment by PhMemmel** [comment]
I just encountered this issue in 2.3-beta1:

First one is not completely easy to reproduce, I'm trying to describe what I did when it happened to me:

- current version of Firefox on Win10 Surface (but happened to me before on my notebook as well)
- Have a meeting with 2 webcams running (can be own ones), move webcams to the left of the presentation
- Let another attendee join with waiting room enabled
- Open waiting room window -> layout crashes, have a look at screenshot 1

![grafik](https://user-images.githubusercontent.com/65113153/113066337-ab5ee680-91ba-11eb-920a-68aed610aef0.png)

**Comment by lkiesow** [comment]
This still happens in BigBlueButton 2.3-beta3

![Screenshot from 2021-04-12 15-32-28](https://user-images.githubusercontent.com/1008395/114431063-5dd17900-9bbf-11eb-9703-3c48b640dc81.png)

**Comment by daminebenq** [comment]
Hi @lkiesow 
What are the steps to reproduce this please ?

**Comment by PhMemmel** [comment]
Last post of @lkiesow looks like same problem as mine described above https://github.com/bigbluebutton/bigbluebutton/issues/11610#issuecomment-810632764

Reproducable by (as mentioned above):
- Chrome on Win10 (probably also Firefox others), join session on 2.3-beta3
- have some webcams enabled
- hide presentation
- another user shares his screen
- issue: webcam bar overlaps screensharing, also see my screenshot above and the very first comment of @lkiesow in this issue: https://github.com/bigbluebutton/bigbluebutton/issues/11610#issue-828288039
