### ISSUE TITLE
waiting room: messages to waiting user

### ISSUE THREAD

**Issue by TheJJ** [bigbluebutton/bigbluebutton#11616]
We use the BBB waiting room for students to queue for their course guidance.

It would be nice if one could send messages to waiting students, so they can estimate when it's their turn.

Basically we would need a message channel from the moderator to queued people.

**Comment by PhMemmel** [comment]
If you are talking about sending one message to all waiting guests, this was merged into develop yesterday: #11593

**Comment by antobinary** [comment]
Good timing, @TheJJ 
This should be released (enabled by default) with BigBlueButton 2.3-alpha8 (likely in a few days)
