### ISSUE TITLE
Chat indicator sometimes does not update properly in 2.3

### ISSUE THREAD

**Issue by lkiesow** [bigbluebutton/bigbluebutton#11617]
**Describe the bug**
The chat indicator in 2.3 sometimes shows that there are new messages even if you have the chat open and are scrolled down to the bottom of the page.

![Screenshot from 2021-03-11 14-44-45](https://user-images.githubusercontent.com/1008395/110799087-17fd5a00-827b-11eb-9891-3dcbd0080897.png)

**BBB version:**

BigBlueButton 2.3-alpha7

**Desktop (please complete the following information):**

 - OS: Fedora Linux 33
 - Browser: Firefox 85.0.1 (64-bit)

**Comment by lkiesow** [comment]
Seems like the Shared Notes indicator might have the same problem. I just had BBB showing no indicator that something has happened in the shared notes even though it did.

**Comment by Tainan404** [comment]
I made some changes on unread meassages code, they're in the lastest build of 2.3, I think those changes fix this issue, could you comment again if you spot this bug again?

**Comment by ffdixon** [comment]
You can also test the (near) latest builds of BigBlueButton 2.3-dev on https://test23.bigbluebutton.org/.  We're always interested if you can reproduce the issue there as well.

**Comment by Tainan404** [comment]
I found a consistent way to reproduce it.

1. join with two users in the meeting
2. send a message of 5k characters 

in the other user should appear a notification of 1 that isn't cleared 


https://user-images.githubusercontent.com/15806883/112644929-b74a5180-8e24-11eb-9eb6-3112c874c7dc.mp4
