### ISSUE TITLE
error installed BigBlueButton 2.2 on Ubuntu 16.04

### ISSUE THREAD

**Issue by asdasim007** [bigbluebutton/bigbluebutton#11613]
I performed the following on my BBB-2.2 Server  
sudo apt-get install bigbluebutton

I received following error messages: 

  Package bbb-config is not configured yet.

dpkg: error processing package bigbluebutton (--configure):
 dependency problems - leaving unconfigured
No apport report written because the error message indicates its a followup erro                                                                                        r from a previous failure.
                          No apport report written because the error message ind                                                                                        icates its a followup error from a previous failure.
                                                    No apport report written bec                                                                                        ause MaxReports is reached already
                                  Errors were encountered while processing:
 bbb-record-core
 bbb-playback-presentation
 bbb-config
 bigbluebutton
E: Sub-process /usr/bin/dpkg returned an error code (1)
server@ubuntu:~$ ^C
server@ubuntu:~$ dependency problems - leaving unconfigured
dependency: command not found
server@ubuntu:~$ No apport report written because the error message indicates it                                                                                        s a followup error from a previous failure.
No: command not found
server@ubuntu:~$ clear
server@ubuntu:~$ sudo apt-get install bigbluebutton
Reading package lists... Done
Building dependency tree
Reading state information... Done
bigbluebutton is already the newest version (1:2.2.0-5).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
4 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n] y
Setting up bbb-record-core (1:2.2.0-77) ...
ERROR:  While executing gem ... (SocketError)
    getaddrinfo: Name or service not known
dpkg: error processing package bbb-record-core (--configure):
 subprocess installed post-installation script returned error exit status 1
dpkg: dependency problems prevent configuration of bbb-playback-presentation:
 bbb-playback-presentation depends on bbb-record-core; however:
  Package bbb-record-core is not configured yet.

dpkg: error processing package bbb-playback-presentation (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of bbb-config:
 bbb-config depends on bbb-playback-presentation; however:
  Package bbb-playback-presentation is not configured yet.

dpkg: error processing package bbb-config (--configure):
 dependency problems - leaving unconfigured
No apport report written because the error message indicates its a followup erro                                                                                        r from a previous failure.
                          No apport report written because the error message ind                                                                                        icates its a followup error from a previous failure.
                                                    dpkg: dependency problems pr                                                                                        event configuration of bigbluebutton:
 bigbluebutton depends on bbb-config; however:
  Package bbb-config is not configured yet.

dpkg: error processing package bigbluebutton (--configure):
 dependency problems - leaving unconfigured
No apport report written because MaxReports is reached already
                                                              Errors were encoun                                                                                        tered while processing:
 bbb-record-core
 bbb-playback-presentation
 bbb-config
 bigbluebutton
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by basisbit** [comment]
Please read the documentation for how to install, configure and operate BigBlueButton. https://docs.bigbluebutton.org/2.2/install.html
