### ISSUE TITLE
Release 2.2.36

### ISSUE THREAD

**Issue by lonesomewalker** [bigbluebutton/bigbluebutton#11646]
Currently there was a release 2.2.36 without a release note.
Demo server got this, now unavailable.

Error or on purpose and we have to check our repository mirroring?

**Comment by ffdixon** [comment]
It's not released yet (no tag or release notes).  

Did you use `-v xenail-220-dev22a` with `bbb-install.sh` -- that will get you the latest development build of 2.2.36.  

Check `/etc/apt/sources.list.d/bigbluebutton`.  If you want the latest production release, change it to `xenial-22`.

**Comment by lonesomewalker** [comment]
Well, all i can say, one of our mirror server got new packages, and some testing instances already run 2.2.36 with bbb-install.sh (without the devxxx)
Will have an eye to this now.
