### ISSUE TITLE
Clearing up the guests waitlist users should not affect chat box

### ISSUE THREAD

**Issue by daminebenq** [bigbluebutton/bigbluebutton#11649]
Clearing up the guests wait list users, makes the waiting list button disappear but also makes chat box disappear.

https://user-images.githubusercontent.com/5144311/111190455-dc71d100-8595-11eb-879e-ad73e37f1554.mp4

**Comment by pedrobmarin** [comment]
@daminebenq are you talking about the chat or the guest lobby message component that is inside the waiting users panel?

**Comment by daminebenq** [comment]
@pedrobmarin, it's all about the chat box getting disappeared, as it's showing in the video.

**Comment by pedrobmarin** [comment]
What's a chat box?

**Comment by mojtaba82** [comment]
Chatbox is in top of list as public chat and you can select it to appear again

**Comment by pedrobmarin** [comment]
As far as this went, it's working as intended. Closing but you can reopen it if there are more information that could validate this as a bug/defect.

**Comment by daminebenq** [comment]
This problem is related to Layout Managers, and @vitormateusalmeida has a fix for these problems, so I think we better keep this issue open until we receive a fix and we confirm the fix of this behavior after testing his PR.

**Comment by pedrobmarin** [comment]
If the problem is the layout manager why should we expect that to be resolved over an issue that stands the problem is clearing the guest's wait list?
