### ISSUE TITLE
Whiteboard: No keyboard on iPad (iOS 14.4) 

### ISSUE THREAD

**Issue by talpaworld** [bigbluebutton/bigbluebutton#11647]
**Describe the bug**
After opening the text frame, no keyboard appears on the iPad (iOS 14.4) for entering text. 

**To Reproduce**
1. Take an iPad with iOS 14.4 or newer
2. Go to Whiteboard and open a text frame
3. Click in the frame to enter text
4. No keyboard appears on the display. (If you have an external keyboard, you can enter text.)

**Expected behavior**
The virtual keyboard on the iPad should appear. 

**Actual behavior**
No keyboard appears on screen and the frame is hidden.

**Screenshots**
https://user-images.githubusercontent.com/18173048/111069362-ff847e00-84cc-11eb-9893-552094705c28.MP4

**BBB version (optional):**
BBB Server 2.2.35
also at demo.bigbluebutton.org

**Desktop (please complete the following information):**
 - OS: iPad with iOS 14.4 or 14.4.1
 - Browser: Safari, Firefox (Webkit); Chrome not tested, iPhone with iOS 14.4 works fine. 
 - Version: 

**Additional context**
Testet on more then 10 BBB-Servers (all of them with 2.2.35) with many iPads (14.4).
iPhone with 14.4 works fine. Likewise iPad with iOS 12.5 does.

**Comment by antobinary** [comment]
Thanks for reporting!
This looks very much like the issue #11477 fixed on 2.3 and I backported as https://github.com/bigbluebutton/bigbluebutton/pull/11537 into 2.2.34

@talpaworld Could you please test the same behaviour against https://test23.bigbluebutton.org/demo/demo2.jsp (what is to be 2.3-alpha8)

**Comment by talpaworld** [comment]
Thanks for the answer!
Same bug on your test23-Testserver:

Uploading 2021-03-15 21.44.14.mp4…

Tested on iPad with iOS 14.4.1 and 14.5.Public Beta 5 (Firefox and Safari)

**Comment by antobinary** [comment]
We'll try to address this on 2.3 and hopefully a fix is easy to find, implement and backport to 2.2.
