### ISSUE TITLE
WB toolbar text color change does not alter the color-picker icon

### ISSUE THREAD

**Issue by hiroshisuga** [bigbluebutton/bigbluebutton#11641]
**Describe the bug**
In the WB toolbar, the text color change does not alter the color of the color-picker icon. This makes a confusion when you select a non-text tool because the color of the color-picker and that of the tool gets different.

**To Reproduce**
1. select text in the WB toolbar
2. change the color by the color picker
3. you see the color of color picker remains the same, while the color of the text tool in the toolbar is altered
4. you select a non-text annotation tool, such as the triangle tool
5. you see the color of the color-picker is different from the color of the triangle tool in the toolbar.
6. you change the color by the color-picker
7. the color of the triangle gets finally the same with the color-picker color. This is what it should be.

**Expected behavior**
The color of the color-picker icon should be changed even when the text tool is selected.

**Actual behavior**
The color of the color-picker icon is not changed as long as the text tool is selected. 

**Screenshots**
This is how it is now:
![toolbar1](https://user-images.githubusercontent.com/45039819/111026613-6b63d980-842e-11eb-95c3-ba59e52b3ab6.gif)

and this is how it should be:
![toolbar2](https://user-images.githubusercontent.com/45039819/111026618-76b70500-842e-11eb-932d-075849f25e87.gif)

**BBB version (optional):**
Confirmed on the test23 server and the test server. So this has been like this since 2.2.

**Comment by JustinMogel** [comment]
i could reproduce this in Microsoft Edge Version 89.0.774.50 (Offizielles Build) (64-Bit)
but in Firefox 86.0.1 (64-bit) changing the text color works as intended

**Comment by hiroshisuga** [comment]
Confirmed that it is working more or less in FF, not like Edge or Chrome. However, the color change of the color selector icon does not animate. With #11642, animation also works in FF.
