### ISSUE TITLE
send notification when bbb page is not visible

### ISSUE THREAD

**Issue by mojtaba82** [bigbluebutton/bigbluebutton#11640]
Hi. Excuse me for my bad English.
Usually when moderator share screen, He or She leave bbb page and for example go to powerpoint to teach something. meanwhile teacher teach a student type message in public or private chat to ask something or change status to for example rise hand, and teacher dont see this question. but if bbb send notification to os then teacher dont miss everything.
Thanks a lot.

**Comment by hiroshisuga** [comment]
What about connecting a second external display, showing and sharing the Powerpoint slide on it?

**Comment by prlanzarin** [comment]
Another alternative (for chat messages): enable audio alerts for chat. It'll play a fairly distinguishable sound when someone sends a message in public or private chat. At least you'll know when something pops up.

To enable it: three dots at top right -> audio alerts for chat (on)

**Comment by mojtaba82** [comment]
> What about connecting a second external display, showing and sharing the Powerpoint slide on it?

It costs money while send notification costs no money.
> Another alternative (for chat messages): enable audio alerts for chat. It'll play a fairly distinguishable sound when someone sends a message in public or private chat. At least you'll know when something pops up.

This is true but presenter have to frequently switch between for example powerpoint and bigbluebutton for read messages.

I add a tiny javascript file to bigbluebutton html5 client that monitor page and send notification to user when someone send message and bigbluebutton page is not active. but this way is not professional and has bad effect on performance. it would be better that official bigbluebutton send os notification instead popup in-page notification when bigbluebutton is not active page or browser is not active window.

**Comment by prlanzarin** [comment]
Yeah. Asides from the suggested alternatives, web notifications are something that could be implemented.

I'll merge this into https://github.com/bigbluebutton/bigbluebutton/issues/3587.
