### ISSUE TITLE
Error screensharing

### ISSUE THREAD

**Issue by GyR4uk** [bigbluebutton/bigbluebutton#11644]
**Describe the bug**
After the last screensharing update
https://github.com/bigbluebutton/bigbluebutton/pull/11622

When the screen is shown, it crashes in error
![image](https://user-images.githubusercontent.com/35705596/111030872-a9083880-8415-11eb-9b8a-88f32ee4864f.png)

**To Reproduce**
1) Update to the latest version from the develop branch
2) Try sharing the screen

P.S.
I tried it on different versions
webrtc-sfu

**Comment by ffdixon** [comment]
Did you update using [bbb-install.sh](https://github.com/bigbluebutton/bbb-install)?  We just update test23.bigbluebutton.org with the latest build from the development branch.  Can you try screen sharing there and let us know if it works for you.

**Comment by GyR4uk** [comment]
Hi Fred.
I didn't update using bbb-install.sh. I'm using a docker version of bbb configured for a develop build.

I will look for what the problem is, because test23 works fine.

**Comment by prlanzarin** [comment]
Please attach the whole console logs. The screenshot is not complete.

Also make sure you've updated **every** BBB component.

**Comment by GyR4uk** [comment]
![image](https://user-images.githubusercontent.com/35705596/111033090-95ae9a80-8420-11eb-9d06-88de10ed36a2.png)

WebRTC-sfu build 2.4.x-release build

**Comment by prlanzarin** [comment]
> WebRTC-sfu build 2.4.x-release build

This is the problem.

May I ask why are you using 2.2's version in 2.3? Not that there's anything wrong with it, just out of curiosity.

If you do want to run that with 2.3's HTML5 client, then flip [this](https://github.com/bigbluebutton/bbb-webrtc-sfu/blob/v2.4.x-release/config/default.example.yml#L53) to `true`.
