### ISSUE TITLE
bbb 2.3 alpha 8 shared notes - red notification blob does not show

### ISSUE THREAD

**Issue by timmwille** [bigbluebutton/bigbluebutton#11659]
Hello everything seems to work well in alpha 8 so far, thx for fixing the copy-text bug. 
Only thing I noticed is, that the little red notification blob is not showing for new shared notes

![grafik](https://user-images.githubusercontent.com/8081055/111346615-aeb48700-867e-11eb-8c4c-80b28a4e0d5d.png)

**Comment by antobinary** [comment]
Thanks for reporting! I can reproduce this locally on alpha8

**Comment by lkiesow** [comment]
Sounds like this could be related to #11617 (or even the same issue)

**Comment by pedrobmarin** [comment]
Related with https://github.com/bigbluebutton/bigbluebutton/issues/11518
