### ISSUE TITLE
2.3a8 bbb-install and apt upgrade

### ISSUE THREAD

**Issue by markginter31** [bigbluebutton/bigbluebutton#11652]
I checked my ubuntu setup this morning:
1) ran apt update
2) saw updates for bbb so I ran the bbb-install script
3) once the script was done I went ahead and ran apt upgrade once more
4) apt reported --> 0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded 2 not fully installed or removed
5) kms-elements hadn't finished setting up
6) seemed to finish setting up fine and apt reports that everything looks good now

**Comment by ffdixon** [comment]
Recommend using the [bbb-install.sh](https://github.com/bigbluebutton/bbb-install) to upgraded to the latest version.  Just re-run the same BigBlueButton command again to pull down 2.3-alpha-8.
