### ISSUE TITLE
/var/www/bigbluebutton-default/client/ isn't installed

### ISSUE THREAD

**Issue by ProVeg-Simon** [bigbluebutton/bigbluebutton#11655]
**Describe the bug**
After installation of 2.3 with bbb-install, the directory /var/www/bigbluebutton-default/client/ is missing. A user getting into a room that hasn't been opened yet receives a 404 error. This is in the nginx error.log (the actual domain replaced with DOMAIN):
```
2021/03/16 14:26:31 [error] 5358#5358: *13 open() "/var/www/bigbluebutton-default/client/conf/config.xml" failed (2: No such file or directory), client: 217.110.71.45, server: DOMAIN, request: "GET /client/conf/config.xml HTTP/1.1", host: "DOMAIN"
2021/03/16 14:26:32 [error] 5358#5358: *1 open() "/var/www/bigbluebutton-default/client/guest-wait.html" failed (2: No such file or directory), client: 217.110.71.42, server: DOMAIN, request: "GET /client/guest-wait.html?sessionToken=e2gkpo6uv3y1xy3q HTTP/1.1", host: "DOMAIN", referrer: "https://DOMAIN/b/sim-yew-gxi-fag"
```

**To Reproduce**
1. Run bbb-install
2. Create a room
3. Call the room's URL from another computer, enter the user name

**Expected behavior**
Guest waiting page instead of HTTP error

**Actual behavior**
HTTP error instead of waiting page.

**Desktop (please complete the following information):**
yes

**Smartphone (please complete the following information):**
also

**Comment by ffdixon** [comment]
Did you upgrade an existing 2.3-dev server or install on a new server?

**Comment by ProVeg-Simon** [comment]
There was a previous version (alpha 6 or something) installed on the server. But installing with bbb-install should remove the old packages, shouldn't it?

**Comment by ProVeg-Simon** [comment]
OK, I manually removed all BBB packages and reinstalled, now it's working. :-)
