### ISSUE TITLE
Improve poll function 

### ISSUE THREAD

**Issue by timmwille** [bigbluebutton/bigbluebutton#11660]
**Is your feature request related to a problem? Please describe.**
The new 2.3dev alpha8 version has some nice upgrades for the poll function, but can be easily improved to greatness:
When you get the results in the chat you can not see the questions, as well as for the result preview of the presentor where no question is shown. (although the new alpha8 has a field for writing the question down and showing it in the results cheers for that one!)

**Describe the solution you'd like**
Clear way to success:
- [x] write the question solved in alpha7/8
- [x] show question with results solved in alpha7/8
- [ ] show title/question during and after the poll is done (for presenter view, to take easy screenshots)
- [ ] show in recordings → not solved at least for 7
- [ ] add poll title/question in front of the chat input with results
→ could look like this (my current workaround is to first share the question)
![grafik](https://user-images.githubusercontent.com/8081055/111348625-a8bfa580-8680-11eb-9b97-7693d41e6cc7.png)

also having the option of anonym/open poll, to have the option to show who voted for what would be nice
**Describe alternatives you've considered**
currently I'm writing the question in the chat first to have it at least in the chat export

**Additional context**
this is important for official board decisions and association meeting events etc. where legal decision making has to be documented well. 

→ side note the text is really small if longer text is put in as mentioned in #5265 

![grafik](https://user-images.githubusercontent.com/8081055/111349536-7febe000-8681-11eb-90b0-23f700976780.png)

also others might connect to #11556 #11455 and #9303

**Comment by antobinary** [comment]
Hi @timmwille 
Thank you for sharing this feedback!

**Comment by antobinary** [comment]
>show title/question during and after the poll is done (for presenter view, to take easy screenshots)

Addressed by https://github.com/bigbluebutton/bigbluebutton/pull/11686

>show in recordings → not solved at least for 7

Should be done as part of https://github.com/bigbluebutton/bigbluebutton/issues/11455

>add poll title/question in front of the chat input with results

Addressed by https://github.com/bigbluebutton/bigbluebutton/pull/11686

**Comment by timmwille** [comment]
Nice, I've just tested the new features in 2.3 amazing guys, thank you!
