### ISSUE TITLE
chromeExtensionKey and chromeExtensionLink inserted in settings.yml

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#11666]
**Describe the bug**
Remove

```
    chromeExtensionKey: KEY
    chromeExtensionLink: LINK
```
from settings.yml
(likely added by packaging / config) 

**BBB version (optional):**
BigBlueButton 2.3-alpha8

**Comment by pedrobmarin** [comment]
There is also some code that must be removed on this refactor https://github.com/bigbluebutton/bigbluebutton/blob/7dfea96fbc595ad5a14e331ca950b9dd59e94b89/bigbluebutton-html5/imports/ui/components/media/container.jsx#L82-L99
