### ISSUE TITLE
no recording after update

### ISSUE THREAD

**Issue by kaffeeweisser2020** [bigbluebutton/bigbluebutton#11667]
Hi
There is no recording after the last systemupdate. I`ve tried it over the moodleplugin and also via greenlight login. 

There are also no recordings in /var/kurento/recordings

BBB Server specs:

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.7 LTS"

                      total        used        free      shared  buff/cache   available
Mem:            31G        4.1G         13G        455M         14G         26G
Swap:           15G          0B         15G
Kernel:
4.15.0-136-generic

cores:12

Clientversion: 1144

How can I fix this problem.

cu kw

**Comment by ffdixon** [comment]
Can you post this to bigbluebutton-setup with more information (see: https://docs.bigbluebutton.org/2.2/getting-help.html#help-installing-or-running-bigbluebutton).  

If there is an issue in BigBlueButton itself, we'll open an issue here to track it.  See also
 
  https://docs.bigbluebutton.org/dev/recording.html#troubleshooting

**Comment by kaffeeweisser2020** [comment]
Thanks, will do.
