### ISSUE TITLE
Public chat reappears while viewing different panels

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#11665]
**Describe the bug**
When public chat is not visible (moderator viewing breakouts), public chat will reappear [every x seconds or when someone starts typing (but not sending)] every so often

There is likely a trigger by who-is-typing or some other change which causes the public chat to re-appear

**To Reproduce**
1. Enter as moderator in a meeting where 2 other moderators are sending public messages
2. Start a breakout. Since the others are also moderators by default nobody will be sent to a breakout.
3. Select the Breakout Rooms menu which allows you to join a selected meeting (see screenshot)
4. The Breakout Rooms menu will be replaced by Public Chat without you triggering it

**Expected behavior**
If you are viewing a non-public chat component, the public chat should not interrupt

**Actual behavior**
The view switches to public chat often (I saw it switch twice in under a minute)

Screenshots
![Screenshot from 2021-03-16 16-55-07](https://user-images.githubusercontent.com/6312397/111378582-66926600-8678-11eb-8c93-55d5e60d6b80.png)

**BBB version (optional):**
BigBlueButton 2.3-alpha8

**Comment by mariogasparoni** [comment]
Possibly related to #11625
