### ISSUE TITLE
Creating a recording with the presenter's camera only

### ISSUE THREAD

**Issue by GyR4uk** [bigbluebutton/bigbluebutton#11668]
I would like to see a mode for creating meeting records, in which only the presenter's camera will be displayed.
This solution will be very useful for the community, as most of the participants of the meeting do not want their webcams to be recorded.

**Comment by antobinary** [comment]
Related to https://github.com/bigbluebutton/bigbluebutton/pull/10070

**Comment by GyR4uk** [comment]
This is not quite true, since only the presenter's webcam needs to be displayed here

**Comment by prlanzarin** [comment]
https://github.com/bigbluebutton/bigbluebutton/pull/10304 definitely related

**Comment by GyR4uk** [comment]
I studied the PR you suggested, but I don't really like it, because if the administrator wants to get all the cameras from the meeting, he can't do it, because they won't be recorded.
