### ISSUE TITLE
Activity Reports

### ISSUE THREAD

**Issue by samuelpetrosyan** [bigbluebutton/bigbluebutton#11679]
**Dear Developers and Community,**

At the moment, I didn't find any solution to get some activity statistics per room /start times, participant counts etc./

I need some meeting rooms' activity report per room /start times, participant counts etc./
For example, What rooms did start in this month? What rooms is top active rooms?
It would be nice to have something that would collect/log some API data and give something as a rooms/sessions history.

If this feature was in BBB standard features, it would be nice.
But also I am searching something modular created by community, e.g. some script/project.

Please share your experience, how we can solve this issue?

Thanks in advance!

**Comment by mabras** [comment]
The basics are exist:

https://github.com/bigbluebutton/bbb-events

https://github.com/bigbluebutton/bigbluebutton/blob/develop/record-and-playback/core/scripts/post_events/post_events_analytics_callback.rb

You need a front-end for it though.

**Comment by samuelpetrosyan** [comment]
OK, thanks, but it seems they are only for recorded sessions!!??
