### ISSUE TITLE
Spotlight one webcam

### ISSUE THREAD

**Issue by sebastianberm** [bigbluebutton/bigbluebutton#11670]
**Is your feature request related to a problem? Please describe.**
At the moment, we have one presenter who'd like to show both a presentation and himself like he is in a lecture(hall).

**Describe the solution you'd like**
As a moderator (or presenter), I'd like to be able to set 1 webcam as a 'spotlighted' webcam which will always be shown (including when paging is enabled) and be shown larger than the others.
This is already possible in software like Teams, however, we'd prefer everyone to use BBB instead of Teams ;-)

**Describe alternatives you've considered**
We've done a few tests to see if this works with using the screen sharing feature, but this lags too much.
His software allows the generated feed to present as a webcam, which works for his usecase. But the effect is he is 'one of many' webcams.

**Additional context**
I have blurred all stuff that isn't relevant for this question but the current setup looks like:
![image](https://user-images.githubusercontent.com/6470150/111451412-b113f100-8711-11eb-9270-881c7a3aa60b.png)

**Comment by lonesomewalker** [comment]
There is 3rd party software for this.

**Comment by sebastianberm** [comment]
@lonesomewalker : You mean to spotlight someone? - Would you be able to provide the name of the software or a link?

Anyhow; My particular usecase was an example.
If we all want BBB to maintain it's market penetration and it being used, it should also implement features competitors are offering, imho.

**Comment by lonesomewalker** [comment]
If you would know how complex this is and know the components of BBB, you wouldn't ask.

**Comment by ffdixon** [comment]
Please ask!  Our focus for BigBlueButton is (and always has been) on the virtual classroom.  We don't mind having a backlog of feature requests.  

With three (or more) webcams you can use the drop-down menu in a webcam to bring a particular webcam into focus.  It looks like you are also looking to hide the other webcams.  With the upcoming 2.3, you could then put the webcam to the left/right of the presentation and achieve your layout.

So now we need to figure out how to hide the other webcams, but just show the current presenter only.

There is also a related feature on showing the current speaker as the focus webcam.

  https://github.com/bigbluebutton/bigbluebutton/issues/8388

**Comment by sebastianberm** [comment]
@lonesomewalker : I understand the complexities of the request, and it wasn't my goal to state otherwise. I do have to admit, I was frustrated a bit by the remark there currently already is 3rd party software, but without any comment on what kind of software you meant. My apologies.
My PR's so far are mostly for related systems like Greenlight. My team will submit a fix for something we encountered in Scalelite as well (after we've confirmed it's still an issue) tomorrow or next week. 
So yes, I do understand the complexities of BBB and related systems.

@ffdixon: It seems like that will do more than 50% of the usecase, so that's really great!
I will setup a couple of 2.3 test machines in the coming weeks to test this. At the moment we have 2.2 servers only.
After that's been completed, and we moved the particular presenter over to 2.3, I will get back with the results.


As for hiding/showing webcams, isn't there a way to emit a new event for that? - That way, the only real issue would be to process that correctly in the html5-web part and how to process that with the presentation recordings (eg webcams feed). I doubt ffmpeg will really like that when merging those views. So that particular process will need a larger overhaul to be able to implement this. (I think something like cutting out the feed and removing feeds based upon the events and adding to the already generated file.)
Although, there is a chance this approach would create issues with the fact the opus audio file and the mp4 mixed webcams go out of sync if this happens a lot. No clue yet on how to work with that.
How does that work for pagination in recordings? (Haven't tested that yet.)

I don't mind on thinking with you guys about possible solutions, but I don't know if I'm capable of creating this as feature.

**Comment by lonesomewalker** [comment]
> Please ask! Our focus for BigBlueButton is (and always has been) on the virtual classroom. We don't mind having a backlog of feature requests.

Sorry to be the nasty guy, but how about to cover up all the old issues, and furthermore the outstanding pull requests?
There are A LOT usefull solutions already done, waiting for release.
Also, it is possible to customize the html client for individual purposes.

And as you can clearly see at the screenshot above, this has nothing to do with virtual classroom.
It looks like a "cheap" tv studio -> commercial purposes for companies, not universities, schools or other educational related stuff.

> With three (or more) webcams you can use the drop-down menu in a webcam to bring a particular webcam into focus. It looks like you are also looking to hide the other webcams. With the upcoming 2.3, you could then put the webcam to the left/right of the presentation and achieve your layout.

Nope, i don't think so, this has a lot to do with greenscreen.
And when entering this domain: good luck.

Sorry for being the annoying part, but i think BBB has recently lost a lot of focus.
Many peoples/organisations/companies are looking for other solutions which offer the same possibilities, but a lot more stability, bigger sessions, and not cluttered "single-person-needs".

We recently had to fix A LOT of non-functional BBB self-hosted instances from admins which are not stupid, but BBB updates/upgrades broke everything (speaking of redis issues).

And since i am ranting, i'll crossreference that here:
in general, we tend to share our knowledge and thoughts, because that is how open source works (or at least should).
Seeing people from mconf here which try to get as much out of BBB for their own product but only contributing back as much as they need for their version of...
I was not interested to have conversations like that:
https://github.com/bigbluebutton/bigbluebutton/issues/2483#issuecomment-795801531

This is not leading to a real solution, so we did the ONLY right thing:
bought an iPad and sent this to abautu

I do not like talking much, instead i prefer to decide what has to be priorized and how to delegate.
(and in this case, it looks pretty commercial with no real benefit for virtual "classrooms". Only for marketing and optical preferences.
If somebody invests time in that, fine.
But as already shown from other "pentests" (hint), there are several parts of BBB which need more attention, especially if you plan to release 2.3 as stable before support for Ubuntu 16.04 ends :-|


just my 2c

**Comment by sebastianberm** [comment]
@lonesomewalker: While I understand what you say (and partially also agree with you), please do note this particular usecase is being used as virtual classroom.
The presenter wanted a way to be able to more naturally point to certain stuff and write stuff down for the viewers (depending on questions).
He did create a green wall and uses third party software for a part of the usecase, but I'd say that to be out of scope for the more generic solution I wanted to request (eg the spotlight like feature).

> Many peoples/organisations/companies are looking for other solutions which offer the same possibilities, but a lot more stability, bigger sessions, and not cluttered "single-person-needs".

This is the reason why I mentioned the entire usecase for this presenter, so it's better to understand, although this isn't needed for the request (eg, please implement spotlighting of users like it's possible in Teams).

We indeed use open source software, but also try to contribute to it, with for example a lot of Moodle plugins we have developed and do maintenance for, but also via PR's for quite a different set of projects.
But I do understand you're not 'targetting' me _directly_. ;-)
I didn't know mconf btw...

> But as already shown from other "pentests" (hint), there are several parts of BBB which need more attention, especially if you plan to release 2.3 as stable before support for Ubuntu 16.04 ends :-|

My request was abolutely not to be picked up for 2.2. I think it's everyones goal to get 2.3 released before 16.04's support ends (which is approaching rapidly)...

As for BBB I can say it has come a long way since the 'great' installation procedure on CentOS years ago with the _amazing_ Flash based client. But I can see it's harder and harder to maintain a healthy momentum with competition like Google, Microsoft and so on.

**Comment by lonesomewalker** [comment]
> @lonesomewalker: While I understand what you say (and partially also agree with you), please do note this particular usecase is being used as virtual classroom.

Really? :D

> The presenter wanted a way to be able to more naturally point to certain stuff and write stuff down for the viewers (depending on questions).
> He did create a green wall and uses third party software for a part of the usecase, but I'd say that to be out of scope for the more generic solution I wanted to request (eg the spotlight like feature).

See, i knew that ;-)

> But I do understand you're not 'targetting' me _directly_. ;-)

This has NEVER been the intention, right. But your use case was... kinda the last drop which... you know :-)

> I didn't know mconf btw...

mconf is NOT a bad company, they contributed MANY lines of code!
But there are also some "improvements" which are already done by them and which are (sadly but fair!) not public code.

> As for BBB I can say it has come a long way since the 'great' installation procedure on CentOS years ago with the _amazing_ Flash based client. But I can see it's harder and harder to maintain a healthy momentum with competition like Google, Microsoft and so on.

AMAZING, hr hr hr, do i smell sarcasm? ;-)

Well, regarding the competition, no.

It becomes more easy if you split things up:
- core team does all the crucial stuff
- community delivers all the "nice to have" features
- core team checks if there is neccessary code to get these features running.
And this can be all financed, our company is participating in several other projects which run fine this way.

**Comment by prlanzarin** [comment]
@sebastianberm 
Discussion got a bit too long for me to read through this.
Can you confirm whether https://github.com/bigbluebutton/bigbluebutton/issues/8388 (auto focus on active talker, which will always be shown first) is virtually the same than this spotlighting request?

**Comment by sebastianberm** [comment]
Hi @prlanzarin,
Fixing #8388 would resolve this issue as well, it's basically the same idea. Due to the dicussion here, it's probably wise to close #11670 in favor of #8388, if that means there's a chance of #8388 will be picked up/selected for development ;-).

**Comment by prlanzarin** [comment]
I'm merging this to #8388, then.

Thanks for the report.

**Comment by Beltrando** [comment]
> There is 3rd party software for this.

Hello. Wich one ?
