### ISSUE TITLE
Where can I find HTML5 Conference HTML template files?

### ISSUE THREAD

**Issue by lrit18** [bigbluebutton/bigbluebutton#11682]
Hello,
I like to edit the appereance from the conference room.
Where a the files (.html, .css, etc.) for HTML5 Client (located in bbb-html5 (I hope so :=) )) package which I can edit?
For "guest wait lobby" it is for example in /var/www/bigbluebutton/client/guest-wait.html
Thanks.

**Comment by antobinary** [comment]
>For "guest wait lobby" it is for example in /var/www/bigbluebutton/client/guest-wait.html

Actually this is no longer correct in BigBlueButton 2.3+, the guest wait lobby page is here: https://github.com/bigbluebutton/bigbluebutton/blob/develop/bigbluebutton-html5/private/static/guest-wait/guest-wait.html

>Where a the files (.html, .css, etc.) 

Here are the files responsible for HTML5 client's UI https://github.com/bigbluebutton/bigbluebutton/tree/develop/bigbluebutton-html5/imports/ui

You can find more info on the docs website https://docs.bigbluebutton.org/2.2/dev.html#developing-the-html5-client

Please check the docs and if you have more questions about development, https://groups.google.com/g/bigbluebutton-dev is better suited for it. Here we keep development issues / bugs / feature requests /etc

**Comment by lrit18** [comment]
My version is 2.2.35.
But where are the files located at my servers hard disk?

**Comment by antobinary** [comment]
>But where are the files located at my servers hard disk?

/usr/share/meteor/bundle/programs/web.browser/*
The resources are minified, combined and prepared for production use. Your best bet for making changes is to set up a development environment, make the changes you desire and then deploy or run as is. Check the Google groups for similar questions
