### ISSUE TITLE
Feature request: Multiple User Screen sharing.

### ISSUE THREAD

**Issue by CookieXD** [bigbluebutton/bigbluebutton#11695]
**Is your feature request related to a problem? Please describe.**
My problem is, that working together on one project (online-school) is not easy.

**Describe the solution you'd like**
Would you concider adding multi user screenshare?

**Describe alternatives you've considered**
Maybe enable multiple users to share only small parts of their screen/application.

**Comment by basisbit** [comment]
This does not really fit with the BigBlueButton UI design. Also, I hardly can imagine a use case where this would actually be helpful. Most users have only one screen, so during screen sharing they hide the bbb browser tab and do stuff in another app. Then, how should a user watch the other users screen while sharing their own screen, even if it is only a part of the screen? For most use cases, the already integrated whiteboard is all you need. There already exist feature request issues to show viewer integration during screen sharing or allow users to draw on the screen sharing surface. Thus, please mention use cases and how exactly the dual screen sharing feature would be used.

I'd guess that the extra complexity in the UI to allow for this is not worth it or is already considered feature creep.

**Comment by chrisuthe** [comment]
@CookieXD  I wonder if looking for more direct integration with existing collaboration tools (Google Workspace, Microsoft 365) where live collaboration is already enabled would be more beneficial.  Group work where everyone has voice and video with BBB and a centralized pane of Google Docs with everyone editing together seems like one of the core requirements? 

I know that doesn't leave it as "open" as just sharing a portion of your screen but lacking interaction leads to @basisbit 's concerns of real usefulness of simply seeing a small portion of other users screens.

**Comment by pedrobmarin** [comment]
Merging this with #9152.
