### ISSUE TITLE
Remove the fields `sender.name` and `color` from the message `GroupChatMessageBroadcastEvtMsg`

### ISSUE THREAD

**Issue by Tainan404** [bigbluebutton/bigbluebutton#11696]
**Describe the bug**
We have duplicated data transferred for each chat message (as discussed in #11081)

**Expected behavior**
We want to transfer only the `userId` into `sender` field.
We dont want to transfer the `color` field (as is user related)

**Comment by antobinary** [comment]
@Tainan404 do you mean to no longer send the fields from Akka-apps? In bbb-html5 server side we could instead just not use these fields when populating Chat related collections...

**Comment by Tainan404** [comment]
Yes, because it would be useless to send this data to meteor (not having it on message payload will make the parsing lighter and simplify the code).

**Comment by antobinary** [comment]
`color` is used in PublicChatRecordEvent which is obtained via GroupChatMessageBroadcastEvtMsg in akka-apps
akka-apps sends these messages to potentially multiple components, not just to bbb-html5 (indirectly via redis)

**Comment by Tainan404** [comment]
For reference this includes modifying this part too : https://github.com/bigbluebutton/bigbluebutton/blob/c2e6c3e8ca57db80aea618f33ed899a42fb6b165/bigbluebutton-html5/imports/api/group-chat-msg/server/modifiers/addGroupChatMsg.js#L27

**Comment by tdjac0bs** [comment]
Nice cach @antobinary.

As far as I understood the issue  #11081 does not depend in this one, that one will stop using the info, this one is about not receiving the info anymore.

Adding this kind of cleanup in Meteor sounds like unneeded extra effort for node.

Do you see a way to make `PublicChatRecordEvent` not depend on `GroupChatMessageBroadcastEvtMsg `?

**Comment by antobinary** [comment]
I am not spotting where `PublicChatRecordEvent` is consumed, I can't tell if it needs the `color` property, all I can see is it's included in the message. `name` does not seem to be used, so technically it could be dropped in a refactor period. Given the big effort on stabilizing and polishing 2.3.x I would prefer if we proceed via:
1) in bbb-html5 server side we drop the `name` and `color` property in the existing collection and we populate them in the new collection (with avatar)
2) we postpone the 'refactor' aspect (i.e. this issue) and we obtain full clarity on whether these fields are needed in any of the modules. This issue will be kept open until then, but unassigned

**Comment by tdjac0bs** [comment]
nice approach, so you'll tag this one for 2.4 and we add this cleanup to scope of #11081 ?

**Comment by antobinary** [comment]
>add this cleanup to scope of #11081
Exactly
