### ISSUE TITLE
HTML5: client crashes on ejection when user is starting to share camera

### ISSUE THREAD

**Issue by ramonlsouza** [bigbluebutton/bigbluebutton#11699]
#### Describe the bug

The HTML5 client (2.3) crashes on an ejection if the ejected user has started to share camera (but image is not appearing yet).

Very similar to #11680, but it's not the same case.
This happens if the user clicked on "start sharing" button, but the camera image is not appearing for other users.

#### To Reproduce

1. Join a meeting with two sessions (1, 2)
2. Select a camera to share on session 2
3. Click on "Start sharing" button on session 2
4. From session 1, kick session 2 (before you see any image from session 2 camera on session 1)
5. Session 2: instead of the 403/You've been removed from the meeting screen, the client shows a blue screen (crashed) and `Cannot read property 'role' of undefined` error in dev tools console

#### Expected behavior

Ejected user should gracefully exit.

#### Actual behavior

Client crashes.

#### BBB version (optional):

2.3-alpha8

Any environment, any browser.

**Comment by antobinary** [comment]
This will likely be fixed as a side effect of https://github.com/bigbluebutton/bigbluebutton/issues/11081 if the new collection includes 'role'
