### ISSUE TITLE
bbb-web debug while opening etherpad

### ISSUE THREAD

**Issue by blastrider** [bigbluebutton/bigbluebutton#11707]
**Describe the bug**
When a session is started I click on shared notes 404 nginx appears instead of etherpad 

**To Reproduce**
1. Go login a session
2. Click on "Shared Notes"
3. Go server side see logs (journalctl -xe or -f)
4. <hostname> run-prod.sh[61087]: 2021-03-22T09:06:18.957+01:00 ERROR o.a.c.c.C.[.[.[.[grailsDispatcherServlet] - Servlet.service() for servlet [grailsDispatcherServlet] threw exception
<hostname> run-prod.sh[61087]: javax.servlet.ServletException: Could not resolve view with name '/error' in servlet with name 'grailsDispatcherServlet'
<hostname> run-prod.sh[61087]:         at org.springframework.web.servlet.DispatcherServlet.render(DispatcherServlet.java:1266)
<hostname> run-prod.sh[61087]:         at org.springframework.web.servlet.DispatcherServlet.processDispatchResult(DispatcherServlet.java:1041)
<hostname> run-prod.sh[61087]:         at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:984)
<hostname> run-prod.sh[61087]:         at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901)
<hostname> run-prod.sh[61087]:         at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
<hostname> run-prod.sh[61087]:         at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)
<hostname> run-prod.sh[61087]:         at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
<hostname> run-prod.sh[61087]:         at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
<hostname> run-prod.sh[61087]:         at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
<hostname> run-prod.sh[61087]:         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
<hostname> run-prod.sh[61087]:         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
<hostname> run-prod.sh[61087]:         at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:728)
<hostname> run-prod.sh[61087]:         at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:472)
<hostname> run-prod.sh[61087]:         at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:395)
<hostname> run-prod.sh[61087]:         at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:316)
<hostname> run-prod.sh[61087]:         at org.apache.catalina.core.StandardHostValve.custom(StandardHostValve.java:395)
<hostname> run-prod.sh[61087]:         at org.apache.catalina.core.StandardHostValve.status(StandardHostValve.java:254)
<hostname> run-prod.sh[61087]:         at org.apache.catalina.core.StandardHostValve.throwable(StandardHostValve.java:349)
<hostname> run-prod.sh[61087]:         at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:175)
<hostname> run-prod.sh[61087]:         at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
<hostname> run-prod.sh[61087]:         at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
<hostname> run-prod.sh[61087]:         at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
<hostname> run-prod.sh[61087]:         at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:800)
<hostname> run-prod.sh[61087]:         at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
<hostname> run-prod.sh[61087]:         at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:806)
<hostname> run-prod.sh[61087]:         at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498)
<hostname> run-prod.sh[61087]:         at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
<hostname> run-prod.sh[61087]:         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
<hostname> run-prod.sh[61087]:         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
<hostname> run-prod.sh[61087]:         at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
<hostname> run-prod.sh[61087]:         at java.lang.Thread.run(Thread.java:748)

**Expected behavior**
I expected shared notes may be useable

**Actual behavior**
java returns This dump

**Screenshots**
![sc_404](https://user-images.githubusercontent.com/69965284/111962459-9dda9a00-8af2-11eb-993b-e4dec223d2cd.png)

**Desktop (please complete the following information):**
 - OS: FreeBSD / Linux / Windows
 - Firefox 86.0 / Chrome 89.0

**Additional context**
BigBlueButton Server 2.2.35 (2442)
                    Kernel version: XXXXX  (anonymized)
                      Distribution: Ubuntu 16.04.7 LTS (64-bit)
                            Memory: 32643 MB
                         CPU cores: 16

/usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties (bbb-web)
       bigbluebutton.web.serverURL: http://51.77.153.11
                defaultGuestPolicy: ALWAYS_ACCEPT
                 svgImagesRequired: true

/etc/nginx/sites-available/bigbluebutton (nginx)
                       server_name: classes-virtuelles.cfssi.gouv.fr
                              port: 80, [::]:80
                              port: 443 ssl

/opt/freeswitch/etc/freeswitch/vars.xml (FreeSWITCH)
                       local_ip_v4: 51.77.153.11
                   external_rtp_ip: 51.77.153.11
                   external_sip_ip: 51.77.153.11

/opt/freeswitch/etc/freeswitch/sip_profiles/external.xml (FreeSWITCH)
                        ext-rtp-ip: $${local_ip_v4}
                        ext-sip-ip: $${local_ip_v4}
                        ws-binding: 51.77.153.11:5066
                       wss-binding: 51.77.153.11:7443

/var/www/bigbluebutton/check/conf/config.xml (client check)
                      client check: classes-virtuelles.cfssi.gouv.fr

/usr/local/bigbluebutton/core/scripts/bigbluebutton.yml (record and playback)
                     playback_host: classes-virtuelles.cfssi.gouv.fr
                 playback_protocol: https
                            ffmpeg: 4.2.4-1ubuntu0.1bbb1~16.04.1

/etc/bigbluebutton/nginx/sip.nginx (sip.nginx)
                        proxy_pass: 51.77.153.11
                          protocol: https

/usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml (Kurento SFU)
                        kurento.ip: 51.77.153.11
                       kurento.url: ws://127.0.0.1:8888/kurento
                    kurento.sip_ip: 51.77.153.11
                    localIpAddress: 51.77.153.11
               recordScreenSharing: true
                     recordWebcams: true
                  codec_video_main: VP8
               codec_video_content: VP8

/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml (HTML5 client)
                             build: 1144
                        kurentoUrl: wss://classes-virtuelles.cfssi.gouv.fr/bbb-webrtc-sfu
                  enableListenOnly: true
                    sipjsHackViaWs: false

/usr/share/bbb-web/WEB-INF/classes/spring/turn-stun-servers.xml (STUN Server)
                              stun:stun.l.google.com:19302

after update from 2.2.33 to 2.2.35 tomcat7 wasn't active then became active alone still don't know why

nginx —————————————————► [✔ - active]
freeswitch ————————————► [✔ - active]
redis-server ——————————► [✔ - active]
bbb-apps-akka —————————► [✔ - active]
bbb-transcode-akka ————► [✔ - active]
bbb-fsesl-akka ————————► [✔ - active]
red5 ——————————————————► [✔ - active]
tomcat7 ———————————————► [✔ - active]
mongod ————————————————► [✔ - active]
bbb-html5 —————————————► [✔ - active]
bbb-webrtc-sfu ————————► [✔ - active]
kurento-media-server ——► [✔ - active]
etherpad ——————————————► [✔ - active]
bbb-web ———————————————► [✔ - active]
bbb-webhooks ——————————► [✔ - active]

EDIT  I had this (i anonymised and parsed the log) by using bbb-conf --debug: 
/bbb-web.log:2021-03-20<TIME><TIME><TIME><TIME> ERROR o.a.c.c.C.[.[.[.[grailsDispatcherServlet] - Servlet.service() for servlet [grailsDispatcherServlet] in context with path [] threw exception [Could not resolve view with name '/error' in servlet with name 'grailsDispatcherServlet'] with root cause
/bbb-web.log:2021-03-20<TIME><TIME><TIME><TIME> ERROR o.a.c.c.C.[.[.[.[grailsDispatcherServlet] - Servlet.service() for servlet [grailsDispatcherServlet] threw exception
/bbb-web.log:2021-03-20<TIME><TIME><TIME><TIME> ERROR o.a.c.c.C.[Tomcat].[localhost] - Exception Processing ErrorPage[errorCode=500, location=/error]
/bbb-web.log:2021-03-20<TIME><TIME><TIME><TIME> ERROR o.g.w.e.GrailsExceptionResolver - NullPointerException occurred when processing request: [GET] /bigbluebutton/connection/validatePad
/bbb-web.log:java.lang.NullPointerException: null
/bbb-web.log:javax.servlet.ServletException: Could not resolve view with name '/error' in servlet with name 'grailsDispatcherServlet'
ort ubbb-web.log:2021-03-20<TIME><TIME><TIME><TIME> ERROR o.a.c.c.C.[.[.[.[grailsDispatcherServlet] - Servlet.service() for servlet [grailsDispatcherServlet] in context with path [] threw exception [Could not resolve view with name '/error' in servlet with name 'grailsDispatcherServlet'] with root cause

**Comment by pedrobmarin** [comment]
Give this a look https://github.com/bigbluebutton/bigbluebutton/issues/11565 . You might find a solution for your problem there. Closing this one to avoid duplicating issues
