### ISSUE TITLE
Send EjectReasonCode in ValidateAuthTokenResp message

### ISSUE THREAD

**Issue by jfsiebel** [bigbluebutton/bigbluebutton#11715]
Send [eject reason](https://github.com/bigbluebutton/bigbluebutton/blob/develop/akka-bbb-apps/src/main/scala/org/bigbluebutton/core/models/Users2x.scala#L302-L311) code together with `validateAuthTokenResp` message.

Today we only receive a text message from akka-apps, making it difficult to translate this message for the default user language.

**Comment by ritzalam** [comment]
@jfsiebel Here are the akka-apps changes for this. https://github.com/bigbluebutton/bigbluebutton/pull/11727

I believe you need to make changes to the html5 server side to handle this change in the message body.
