### ISSUE TITLE
Accessibility enhancements to HTML5 client's main page for colorblind people

### ISSUE THREAD

**Issue by otdftr** [bigbluebutton/bigbluebutton#11720]
The main page of the HTML5 client has a dark blue background, this and several buttons are hardly distinguishable for colorblind people (as one such user just reported today).

**Expected behavior / Suggestion**
Would be nice to have a button to switch to a light skin / high contrast skin.

**Actual behavior**

**BBB version (optional):**
BigBlueButton 2.2

**Comment by antobinary** [comment]
Hi @otdftr Thanks for reporting!

**Comment by antobinary** [comment]
@KDSBrowne 
Could you please confirm if 2.4.0's Accessibility audit included color contrast verification?

**Comment by KDSBrowne** [comment]
@antobinary I can confirm that it was included.

**Comment by antobinary** [comment]
Excellent! May we close this issue?
