### ISSUE TITLE
Add emoji picker to chat

### ISSUE THREAD

**Issue by Jossef-767** [bigbluebutton/bigbluebutton#11745]
problem: 
emojis have become essential on chat platforms.
built-in emoji picker in Windows 10 works great in bbb chat, but not all users are aware of this option since it is hidden. and requires left mouse  click and selecting the emoji option from the menu.

**Describe the solution you'd like**
add a visual link, button, or other form of clickable area, to open the built-in emoji picker in Windows 10

![image](https://user-images.githubusercontent.com/2356928/112462336-9a9d1380-8d69-11eb-8c46-626541b2053d.png)

**Comment by tosteiner** [comment]
No direct solution, but just to note that the `WINDOWS`+`.` keybord shortcut also works in BBB's public chat: https://support.microsoft.com/en-us/windows/windows-10-keyboard-tips-and-tricks-588e0b72-0fff-6d3f-aeee-6e5116097942

**Comment by pedrobmarin** [comment]
We've been using https://www.npmjs.com/package/emoji-mart and, after filtering some multiple-browsers incompatibility related unicodes, it's working pretty well.
