### ISSUE TITLE
Multi-user Whiteboard access

### ISSUE THREAD

**Issue by GyR4uk** [bigbluebutton/bigbluebutton#11744]
If you allow all users to access the whiteboard, the newly joined users will not have access to the whiteboard.

I would like to extend access to new users who join.

**Comment by basisbit** [comment]
closing this issue because you did not fill in most of the necessary information from the template.

**Comment by antobinary** [comment]
I created a new issue https://github.com/bigbluebutton/bigbluebutton/issues/11765 to track this.
Thanks @GyR4uk for bringing it up. Please follow the template when possible - it helps to clarify what you encountered.
Thanks @basisbit for keeping the standards high. It is easier to work with GH issues when it is clear what the details are.
