### ISSUE TITLE
Ship BBB 2.3 freeswitch NAT friendly default config

### ISSUE THREAD

**Issue by znerol** [bigbluebutton/bigbluebutton#11743]
**Is your feature request related to a problem? Please describe.**

As detailed in bigbluebutton/bigbluebutton.github.io#126 the complicated instructions in the docs on how to setup FreeSWITCH behind a NAT, especially [the dummy NIC section](https://docs.bigbluebutton.org/2.2/configure-firewall.html#configure-a-dummy-nic-if-required) is completely superflous when FreeSWITCH si instructed to always advertise the external IP during ICE gathering phase.

**Describe the solution you'd like**

There are two ways to achieve this.

**1. include_external_ip channel variable**

FreeSWITCH can be instructed to advertise multiple ICE candidates using the include_external_ip channel variable introduced in signalwire/freeswitch@15fd3f1 (PR here: #11864)

```
diff --git a/bbb-voice-conference/config/freeswitch/conf/dialplan/public/bbb_webrtc.xml b/bbb-voice-conference/config/freeswitch/conf/dialplan/public/bbb_webrtc.xml
index 0582cceec68..0eb404d5657 100644
--- a/bbb-voice-conference/config/freeswitch/conf/dialplan/public/bbb_webrtc.xml
+++ b/bbb-voice-conference/config/freeswitch/conf/dialplan/public/bbb_webrtc.xml
@@ -4,6 +4,7 @@
       <condition field="${sip_via_protocol}" expression="^wss?$" break="on-false">
 	<action application="set" data="bbb_authorized=true"/>
 	<action application="set" data="jb_use_timestamps=true"/>
+	<action application="set" data="include_external_ip=true"/>
         <action application="transfer" data="${destination_number} XML default"/>
       </condition>
     </extension>
```

**2. Set local-network-acl param in external profiles**

An alternative change to make FreeSWITCH working flawlessly behind a NAT is to set `local-network-acl` param in external sip profiles to `none`.

```diff
diff --git a/sip_profiles/external-ipv6.xml b/sip_profiles/external-ipv6.xml
index 5efa79b..514f8e9 100644
--- a/sip_profiles/external-ipv6.xml
+++ b/sip_profiles/external-ipv6.xml
@@ -36,7 +36,7 @@
     <!--<param name="enable-100rel" value="true"/>-->
     <!--<param name="disable-srv503" value="true"/>-->
     <!-- This could be set to "passive" -->
-    <param name="local-network-acl" value="localnet.auto"/>
+    <param name="local-network-acl" value="none"/>
     <param name="manage-presence" value="false"/>
 
     <!-- Added for Microsoft Edge support 
diff --git a/sip_profiles/external.xml b/sip_profiles/external.xml
index c93346d..fe5c7a4 100644
--- a/sip_profiles/external.xml
+++ b/sip_profiles/external.xml
@@ -36,7 +36,7 @@
     <!--<param name="enable-100rel" value="true"/>-->
     <!--<param name="disable-srv503" value="true"/>-->
     <!-- This could be set to "passive" -->
-    <param name="local-network-acl" value="localnet.auto"/>
+    <param name="local-network-acl" value="none"/>
     <param name="manage-presence" value="false"/>
 
 
```

**Comment by ffdixon** [comment]
Thanks for sharing this -- we're going to make these changes to 2.3-beta.

**Comment by PhMemmel** [comment]
My NAT setup is doing well without these changes. What's their purpose?

**Comment by ffdixon** [comment]
We've published our FreeSWITCH configuration files here 
 
 https://github.com/bigbluebutton/bigbluebutton/tree/develop/bbb-voice-conference/config/freeswitch

We're going to modify the build of FreeSWITCH for 2.3 to pull from this directory.  Pull request are welcome!

**Comment by znerol** [comment]
Thanks @ffdixon, that's good news. Before filing a PR I'm gonna try another option (with a less scary name than `local-network-acl`. There seems to be an `include_external_ip` channel var introduced in signalwire/freeswitch@15fd3f1353a8f08c2dba6a5d9a3560ec8717be12 which looks like it has the same effect (i.e., advertise the external ip in SIP even when connection is originating from nginx on localhost/localnet).

**Comment by znerol** [comment]
@PhMemmel it simplifies the setup when the server is behind a NAT (e.g., when running on openstack). There are more details in #11846 and bigbluebutton/bigbluebutton.github.io#126 

Basically it makes setting up the [dummy NIC](https://docs.bigbluebutton.org/2.2/configure-firewall.html#configure-a-dummy-nic-if-required) superflous in every case.

**Comment by PhMemmel** [comment]
@znerol Thank you for the explanation. So this isn't affecting my setup because my NAT is doing reflection properly. If this option is set, will NAT reflection still be used or is this handled completely internally by freeswitch?

**Comment by znerol** [comment]
> If this option is set, will NAT reflection still be used or is this handled completely internally by freeswitch?

FreeSWITCH by default looks at the source address of any incoming connection in order to decide which IP (local vs extarnal) it includes in its SDP (ICE candidate). If option 1 is implemented (`include_external_ip` channel var), then FreeSWITCH will always advertise both IPs (local and external) to connecting browsers. If option 2 is implemented, then only the external one will be included in the SDP.

Thus let's put it like this. If any of the options is implemented, then the source address of an incoming connection does not matter anymore for FreeSWITCH. It will always include the external address in its ICE candidates. As a result, you can safely use the internal address (or even the local loopback `127.0.0.1`) in `sip.nginx` and the behavior of your NAT device is completely irrelevant. You can also continue to use the external address in `sip.nginx` if you insist, that will continue to work.

**Comment by devZer0** [comment]
i installed 2.3 beta2 with bbb-install.sh (as being told in https://github.com/bigbluebutton/bbb-install/issues/109 ) on another system behind nat router and hit this issue https://github.com/bigbluebutton/bbb-install/issues/133 , so i'd like to give my vote for an intelligent fix which makes freeswitch behave correctly
