### ISSUE TITLE
New configuration - join session with Audio first; allow students to join microphone later

### ISSUE THREAD

**Issue by lneoj** [bigbluebutton/bigbluebutton#11748]
Hi All,

I did testing this evening with BBB 2.3-dev and I am so excited about the progress; so far good job. I managed on one single VM open 200 students in listening mode only and 2 moderators with cams on and microphone plus sharing screen without any lack.

BUT; I am looking for a configuration to join student into listening mode automatically; without clicking on AUDIO button; more importantly once a student is in a session and a student needs to talk then they could hang out the audio and click join audio with the microphone.

WHY? If I do set up "join microphone only" and "mute on start" this brings the max capacity per same VM to 90 users only.

From my understanding, each session is mostly listening but I don't want to take the capability to talk if needed but I don't want students initially to use a microphone as they don't follow instructions.

Hope this makes sense;

Config I tried:
skipCheck: true
skipCheckOnJoin: true
autoJoin: true
listenOnlyMode: true

**Comment by basisbit** [comment]
For support requests, please use the [forum / mailing list](https://groups.google.com/forum/#!forum/bigbluebutton-setup). This issue tracker here is only for BBB development related issues. Sorry.
