### ISSUE TITLE
Online Exams Feature

### ISSUE THREAD

**Issue by Bachta96** [bigbluebutton/bigbluebutton#11759]
The **Online Exams Feature** will allow teachers to share an exam (MCQ or open questions). The feature will give teachers access to a determined number of questions but also to a timer that they can adjust. Students will be able to access the functionality to take an exam and will be able to have their grade directly on the platform.

I want that the professors find a simple and fast solution to give exams to the students and I want that the students do not waste time on searching the exam on an another platform.

I have considered the alternative of sending the exam with a file but the professor can not control the time. The other alternative is to use another platform which is not the most efficient alternative.

**Comment by basisbit** [comment]
Please see my comments in your other issues. This also is something for a LMS, not for BigBlueButton.
