### ISSUE TITLE
2.3-beta1: obsolete config file snippet related to red5

### ISSUE THREAD

**Issue by danimo** [bigbluebutton/bigbluebutton#11754]
**Note:** This is a packaging issue, not a problem in the install scripts.

The following snippet is obsolete in `/etc/nginx/sites-available/bigbluebutton` and should be dropped:

``` 
         # Handle RTMPT (RTMP Tunneling).  Forwards requests
         # to Red5 on port 5080
      location ~ (/open/|/close/|/idle/|/send/|/fcs/) {
          proxy_pass         http://127.0.0.1:5080;
          proxy_redirect     off;
          proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;

          client_max_body_size       10m;
          client_body_buffer_size    128k;

          proxy_connect_timeout      90;
          proxy_send_timeout         90;
          proxy_read_timeout         90;

          proxy_buffering            off;
          keepalive_requests         1000000000;
      }

         # Handle desktop sharing tunneling.  Forwards
         # requests to Red5 on port 5080.
       location /deskshare {
           proxy_pass         http://127.0.0.1:5080;
           proxy_redirect     default;
           proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
           client_max_body_size       10m;
           client_body_buffer_size    128k;
           proxy_connect_timeout      90;
           proxy_send_timeout         90;
           proxy_read_timeout         90;
           proxy_buffer_size          4k;
           proxy_buffers              4 32k;
           proxy_busy_buffers_size    64k;
           proxy_temp_file_write_size 64k;
           include    fastcgi_params;
       }
```

Also, this snipped in `/usr/share/bbb-apps-akka/conf/application.conf` is probably obsolete:

```
red5 {
    deskshareip="<ip>"
    deskshareapp="video-broadcast"
}
```

**Comment by ffdixon** [comment]
Thanks for pointing this out -- it gets overwritten by `bbb-install.sh`, but we still want to remove these older references.

**Comment by schrd** [comment]
bbb-install.sh should not patch anything that is distributed by packages.

**Comment by antobinary** [comment]
@danimo `/etc/nginx/sites-available/bigbluebutton` no longer has the block you quoted. Thanks for pointing that out.
This change will ship with 2.3-beta-2.


```
red5 {
    deskshareip="<ip>"
    deskshareapp="video-broadcast"
}
```
About this block - there is work underway to include screenshare info in akka-apps again. Currently the screenshare part in akka-apps is obsolete, the logic has been handled by bbb-webrtc-sfu. The `deskshareip` and `deskshareapp` will be removed/replaced as part of this work. I split this into separate issue https://github.com/bigbluebutton/bigbluebutton/issues/11761

**Comment by antobinary** [comment]
> bbb-install.sh should not patch anything that is distributed by packages.

Opened https://github.com/bigbluebutton/bbb-install/issues/357 to track the implementation of this recommendation.

Thank you both!
