### ISSUE TITLE
2.3b2 2.3b1 2.3a8 Guest Wait Room does not work

### ISSUE THREAD

**Issue by jrk-omf** [bigbluebutton/bigbluebutton#11757]
**Describe the bug**
Prior to 2.3-alpha-8 waiting room was working. Since then guest are put directly into the conference regardless if option for Waiting room is activated for a room or not.

**To Reproduce**
Room already open
1. Start a conference as a moderator
2. Login as a Guest with Link only
3. Guest will be logged in without waiting room

Room not open
1. Login as a Guest with Link only
2. Guest is in a waiting Room
3. Start conference as a moderator
4. Guest will be logged in instantly without acceptance of moderator
 
**Expected behavior**

Guests should not automatically join a session once Room is set for Moderator acceptance

**Actual behavior**

Guests are automatically joining the conference regardless of configuration of the room

**Screenshots**
n/a

**BBB version (optional):**
BigBlueButton Server 2.3.0-beta-1 (1848)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 89.0.4389.90

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy Tab S5e
 - OS: Android 10
 - Browser Chrome
 - Version 89.0.4389.105

**Additional context**
It worked before 2.3a8

**Comment by basisbit** [comment]
please try again with bbb 2.3-beta1

**Comment by pedrobmarin** [comment]
> Login as a Guest with Link only

Would you mind throwing some extra details on this? What's a **guest** for you and what's **link only** login? Is this Greenlight stuff?

**Comment by jrk-omf** [comment]
Okay - put it like this: I configured a room like this:
![image](https://user-images.githubusercontent.com/76527725/112634111-79582800-8e3a-11eb-92ef-b8953fb0874a.png)

Then I send the Room Link to the Guests, which will access the room via the link (not via Greenlight)

**Comment by basisbit** [comment]
>  via the link (not via Greenlight)

Actually, the access link will send people to the greenlight frontend. Which version of Gteenlight are you using?

**Comment by jrk-omf** [comment]
It's greenlight-v2

**Comment by basisbit** [comment]
please check which version exactly.

**Comment by pedrobmarin** [comment]
BigBlueButton has a new option to change the guest policy inside the meeting. It's a valid alternative to make sure what's the policy being set by Greenlight. Could you verify on that? Here's the reference https://github.com/bigbluebutton/bigbluebutton/pull/11634

**Comment by jrk-omf** [comment]
Version is 2.7.12 - I guess I need to update to a newer one ...

**Comment by jrk-omf** [comment]
Updated to 2.8.2.2 - seems to not change the behaviour (and updated to 2.3b2 also)

**Comment by jrk-omf** [comment]
> BigBlueButton has a new option to change the guest policy inside the meeting. It's a valid alternative to make sure what's the policy being set by Greenlight. Could you verify on that? Here's the reference #11634

Yes, this is active:
![image](https://user-images.githubusercontent.com/76527725/113464479-465ef700-942d-11eb-994b-ef6e59e84101.png)
But didn't change the behaviour

**Comment by PhMemmel** [comment]
This has to be sth specific to your setup. I'm running greenlight v2.8.2.2 and 2.3-beta2 and the waiting room is working exactly as it should, I can switch it on and back off, behavior ist like it is supposed to be in both cases. Can you maybe provide some logs?

You should find the API calls in `/var/log/bigbluebutton/bbb-web.log` or `/var/log/nginx/bigbluebutton.access.log`, maybe with the create and join API calls it's possible to figure out where your (probably configuration) problem is.

**Comment by jrk-omf** [comment]
> I even tried to change defaultGuestPolicy in `/etc/bigbluebutton/bbb-web.conf`. Behavior is exactly like it's supposed to be in all different cases.

This file does not exist on my configuration.  Will try to find some logs where I tried to use the waiting room.

**Comment by PhMemmel** [comment]
That is an optional overlay config file. If it doesn't exist the default config in `/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml` is being used, so this shouldn't be an issue for you.

To narrow it further down you could also try to generate an API call with apimate. Just hit `bbb-conf --secret` on your bbb server and use the shown apimate url in a browser to generate a join call to an opened session (enter meetingID and attendeePW properly, you can find out with "getMeetings" call before) with waiting room enabled. Add `guest=true` at "Custom parameters" section. You should be able to join the session and end up in the waiting room.

**Comment by jrk-omf** [comment]
> To narrow it further down you could also try to generate an API call with apimate. Just hit `bbb-conf --secret` on your bbb server and use the shown apimate url in a browser to generate a join call to an opened session (enter meetingID and attendeePW properly, you can find out with "getMeetings" call before) with waiting room enabled. Add `guest=true` at "Custom parameters" section. You should be able to join the session and end up in the waiting room.

This is interessting. I tried it, but once clicking on "join as attendee" it goes to the login page. (But I do not find a field to enter the Conference Code)

**Comment by PhMemmel** [comment]
With "login page" you mean the greenlight page? If "Join as attendee" via apimate leads you to a greenlight page, you definitely did something wrong :-) You should being directed directly to the waiting room landing page.

I feel like you are mixing up the BBB server itself with the greenlight frontend. By using the apimate you directly access the BBB API without doing anything greenlight-y at all. As I don't think this is an BBB issue but a configuration problem I suggest closing this issue and moving this discussion to the BBB setup mailinglist. Try to provide as much information as possible along with some screenshots. Hopefully you get the help needed there.

**Comment by jrk-omf** [comment]
> Can you maybe provide some logs? You should find the API calls in `/var/log/bigbluebutton/bbb-web.log` or `/var/log/nginx/bigbluebutton.access.log`. Maybe with the create and join API calls it's possible to figure out where your (probably configuration) problem is.

So I reproduced the issue during no other use of the system (so only my tests are in the logs).
The following logs starts after the moderator opens the room and waits for participants. Then within the log, the Gues user enters the room using the room's url, entering the 6-digits code, then entering a Test name and check the checkbox to agree sessions to been recorded. Afterwards session is started for the guest, echo check is running and conference has been entered successfully. Then Guest is loging out of the room. (End of log files).

So here the log from `/var/log/bigbluebutton/bbb-web.log`

> 2021-04-11T00:56:36.797+02:00 DEBUG o.b.web.controllers.ApiController - ApiController#isMeetingRunning
> 2021-04-11T00:56:36.797+02:00 INFO  o.b.api.ParamsProcessorUtil - CHECKSUM=d9f6c6759aa14d7cb1facd385bedc2ede2d3d065 length=40
> 2021-04-11T00:56:36.797+02:00 INFO  o.b.api.ParamsProcessorUtil - CHECKSUM=d9f6c6759aa14d7cb1facd385bedc2ede2d3d065 length=40
> 2021-04-11T00:56:36.797+02:00 INFO  o.b.web.controllers.ApiController - Retrieving meeting 17060b39d2ad0b35b42ac5469be2c5f9527eb375
> 2021-04-11T00:56:36.810+02:00 DEBUG o.b.web.controllers.ApiController - ApiController#getRecordings
> 2021-04-11T00:56:36.811+02:00 INFO  o.b.api.ParamsProcessorUtil - CHECKSUM=f607cca1d98930e60d818b344600d0b868b6f593 length=40
> 2021-04-11T00:56:36.811+02:00 DEBUG o.b.web.controllers.ApiController - meetingID=hgbycwsbbaioicihy7lvpastbbag0icjfyc4d8jr&checksum=f607cca1d98930e60d818b344600d0b868b6f593
> 2021-04-11T00:56:36.811+02:00 INFO  o.b.api.ParamsProcessorUtil - CHECKSUM=f607cca1d98930e60d818b344600d0b868b6f593 length=40
> 2021-04-11T00:56:36.811+02:00 DEBUG o.b.web.controllers.ApiController - 17060b39d2ad0b35b42ac5469be2c5f9527eb375
> 2021-04-11T00:56:54.854+02:00 DEBUG o.b.web.controllers.ApiController - ApiController#isMeetingRunning
> 2021-04-11T00:56:54.854+02:00 INFO  o.b.api.ParamsProcessorUtil - CHECKSUM=d9f6c6759aa14d7cb1facd385bedc2ede2d3d065 length=40
> 2021-04-11T00:56:54.854+02:00 INFO  o.b.api.ParamsProcessorUtil - CHECKSUM=d9f6c6759aa14d7cb1facd385bedc2ede2d3d065 length=40
> 2021-04-11T00:56:54.854+02:00 INFO  o.b.web.controllers.ApiController - Retrieving meeting 17060b39d2ad0b35b42ac5469be2c5f9527eb375
> 2021-04-11T00:56:54.868+02:00 DEBUG o.b.web.controllers.ApiController - ApiController#getRecordings
> 2021-04-11T00:56:54.868+02:00 INFO  o.b.api.ParamsProcessorUtil - CHECKSUM=f607cca1d98930e60d818b344600d0b868b6f593 length=40
> 2021-04-11T00:56:54.869+02:00 DEBUG o.b.web.controllers.ApiController - meetingID=hgbycwsbbaioicihy7lvpastbbag0icjfyc4d8jr&checksum=f607cca1d98930e60d818b344600d0b868b6f593
> 2021-04-11T00:56:54.869+02:00 INFO  o.b.api.ParamsProcessorUtil - CHECKSUM=f607cca1d98930e60d818b344600d0b868b6f593 length=40
> 2021-04-11T00:56:54.869+02:00 DEBUG o.b.web.controllers.ApiController - 17060b39d2ad0b35b42ac5469be2c5f9527eb375
> 2021-04-11T00:57:00.570+02:00 DEBUG o.b.web.controllers.ApiController - ApiController#isMeetingRunning
> 2021-04-11T00:57:00.570+02:00 INFO  o.b.api.ParamsProcessorUtil - CHECKSUM=d9f6c6759aa14d7cb1facd385bedc2ede2d3d065 length=40
> 2021-04-11T00:57:00.570+02:00 INFO  o.b.api.ParamsProcessorUtil - CHECKSUM=d9f6c6759aa14d7cb1facd385bedc2ede2d3d065 length=40
> 2021-04-11T00:57:00.571+02:00 INFO  o.b.web.controllers.ApiController - Retrieving meeting 17060b39d2ad0b35b42ac5469be2c5f9527eb375
> 2021-04-11T00:57:00.587+02:00 DEBUG o.b.web.controllers.ApiController - ApiController#create
> 2021-04-11T00:57:00.587+02:00 DEBUG o.b.web.controllers.ApiController - [attendeePW:[OtEmRJyikZzM], guestPolicy:[ASK_MODERATOR], logoutURL:[https://my-domain.com/b/tho-oid-f4g-gri/logout], meetingID:[hgbycwsbbaioicihy7lvpastbbag0icjfyc4d8jr], meta_bbb-origin:[Greenlight], meta_bbb-origin-server-name:[my-domain.com], meta_bbb-origin-version:[v2-custom], meta_gl-listed:[false], moderatorOnlyMessage:[Um jemanden zur Konferenz einzuladen, schicken Sie ihm diesen Link:<br> https://my-domain.com/b/tho-oid-f4g-gri], moderatorPW:[kHjhkoyjRvMM], muteOnStart:[true], name:[Startraum], record:[true], checksum:[d3ad327066b7f868e1aee7484c5f403d41d2f66b]]
> 2021-04-11T00:57:00.587+02:00 INFO  o.b.api.ParamsProcessorUtil - CHECKSUM=d3ad327066b7f868e1aee7484c5f403d41d2f66b length=40
> 2021-04-11T00:57:00.587+02:00 INFO  o.b.api.ParamsProcessorUtil - CHECKSUM=d3ad327066b7f868e1aee7484c5f403d41d2f66b length=40
> 2021-04-11T00:57:00.611+02:00 DEBUG o.b.web.controllers.ApiController - Existing conference found
> 2021-04-11T00:57:00.612+02:00 DEBUG o.b.web.controllers.ApiController - Rendering as xml
> 2021-04-11T00:57:00.671+02:00 DEBUG o.b.web.controllers.ApiController - ApiController#join
> 2021-04-11T00:57:00.672+02:00 INFO  o.b.api.ParamsProcessorUtil - CHECKSUM=0d19a3120822c201df3fa2dcef6cf4d5d33858d5 length=40
> 2021-04-11T00:57:00.672+02:00 INFO  o.b.api.ParamsProcessorUtil - CHECKSUM=0d19a3120822c201df3fa2dcef6cf4d5d33858d5 length=40
> 2021-04-11T00:57:00.672+02:00 INFO  o.b.web.controllers.ApiController - Retrieving meeting 17060b39d2ad0b35b42ac5469be2c5f9527eb375
> 2021-04-11T00:57:00.672+02:00 INFO  o.b.web.controllers.ApiController - Session sessionToken for Test [null]
> 2021-04-11T00:57:00.672+02:00 INFO  o.b.web.controllers.ApiController - Session user-token for Test [null]
> 2021-04-11T00:57:00.672+02:00 INFO  o.b.web.controllers.ApiController -  --analytics-- data={"extMeetingid":"hgbycwsbbaioicihy7lvpastbbag0icjfyc4d8jr","logCode":"join_api","name":"Test","sessionToken":"7sjtfwljv35pt1u9","description":"Handle JOIN API.","meetingid":"17060b39d2ad0b35b42ac5469be2c5f9527eb375-1618095324607","userid":"w_udgymzxqnv2v"}
> 2021-04-11T00:57:00.672+02:00 INFO  o.b.web.controllers.ApiController - Redirecting to https://my-domain.com/html5client/join?sessionToken=7sjtfwljv35pt1u9
> 2021-04-11T00:57:03.805+02:00 DEBUG o.b.web.controllers.ApiController - ApiController#enter
> 2021-04-11T00:57:03.805+02:00 INFO  o.b.web.controllers.ApiController - Token 7sjtfwljv35pt1u9 is valid
> 2021-04-11T00:57:03.805+02:00 INFO  o.b.web.controllers.ApiController -  --analytics-- data={"extMeetingid":"hgbycwsbbaioicihy7lvpastbbag0icjfyc4d8jr","logCode":"handle_enter_api","name":"Test","sessionToken":"7sjtfwljv35pt1u9","description":"Handling ENTER API.","meetingid":"17060b39d2ad0b35b42ac5469be2c5f9527eb375-1618095324607","userid":"w_udgymzxqnv2v"}
> 2021-04-11T00:57:03.868+02:00 INFO  o.bigbluebutton.api.MeetingService -  --analytics-- data={"role":"VIEWER","clientType":"HTML5","externalUserId":"gl-guest-42bd2a66a817abea115de351","logCode":"user_joined_message","name":"Startraum","description":"User joined the meeting.","meetingId":"17060b39d2ad0b35b42ac5469be2c5f9527eb375-1618095324607","externalMeetingId":"hgbycwsbbaioicihy7lvpastbbag0icjfyc4d8jr","guest":false,"guestStatus":"ALLOW","userId":"w_udgymzxqnv2v","username":"Test"}
> 2021-04-11T00:57:07.298+02:00 DEBUG o.b.web.controllers.ApiController - ApiController#stuns
> 2021-04-11T00:57:07.298+02:00 INFO  o.b.web.controllers.ApiController - Token 7sjtfwljv35pt1u9 is valid
> 2021-04-11T00:57:07.299+02:00 INFO  o.b.w.services.turn.StunTurnService - 
> StunTurnService::getStunServers 
> 
> 2021-04-11T00:57:07.299+02:00 INFO  o.b.w.services.turn.StunTurnService - 
> StunTurnService::getStunAndTurnServersFor w_udgymzxqnv2v
> 
> 2021-04-11T00:57:31.433+02:00 DEBUG o.b.web.controllers.ApiController - ApiController#isMeetingRunning
> 2021-04-11T00:57:31.433+02:00 INFO  o.b.api.ParamsProcessorUtil - CHECKSUM=d9f6c6759aa14d7cb1facd385bedc2ede2d3d065 length=40
> 2021-04-11T00:57:31.433+02:00 INFO  o.b.api.ParamsProcessorUtil - CHECKSUM=d9f6c6759aa14d7cb1facd385bedc2ede2d3d065 length=40
> 2021-04-11T00:57:31.433+02:00 INFO  o.b.web.controllers.ApiController - Retrieving meeting 17060b39d2ad0b35b42ac5469be2c5f9527eb375
> 2021-04-11T00:57:31.449+02:00 DEBUG o.b.web.controllers.ApiController - ApiController#getRecordings
> 2021-04-11T00:57:31.450+02:00 INFO  o.b.api.ParamsProcessorUtil - CHECKSUM=f607cca1d98930e60d818b344600d0b868b6f593 length=40
> 2021-04-11T00:57:31.450+02:00 DEBUG o.b.web.controllers.ApiController - meetingID=hgbycwsbbaioicihy7lvpastbbag0icjfyc4d8jr&checksum=f607cca1d98930e60d818b344600d0b868b6f593
> 2021-04-11T00:57:31.450+02:00 INFO  o.b.api.ParamsProcessorUtil - CHECKSUM=f607cca1d98930e60d818b344600d0b868b6f593 length=40
> 2021-04-11T00:57:31.450+02:00 DEBUG o.b.web.controllers.ApiController - 17060b39d2ad0b35b42ac5469be2c5f9527eb375
> 2021-04-11T00:57:39.640+02:00 INFO  o.bigbluebutton.api.MeetingService -  --analytics-- data={"role":"VIEWER","externalUserId":"gl-guest-42bd2a66a817abea115de351","logCode":"user_left_message","name":"Startraum","description":"User left the meeting.","meetingId":"17060b39d2ad0b35b42ac5469be2c5f9527eb375-1618095324607","externalMeetingId":"hgbycwsbbaioicihy7lvpastbbag0icjfyc4d8jr","guest":false,"guestStatus":"ALLOW","userId":"w_udgymzxqnv2v","username":"Test"}


And here for `/var/log/nginx/bigbluebutton.access.log`:

> 172.18.0.3 - - [11/Apr/2021:00:56:36 +0200] "GET /bigbluebutton/api/isMeetingRunning?meetingID=hgbycwsbbaioicihy7lvpastbbag0icjfyc4d8jr&checksum=d9f6c6759aa14d7cb1facd385bedc2ede2d3d065 HTTP/1.1" 200 93 "-" "Ruby"
> 172.18.0.3 - - [11/Apr/2021:00:56:36 +0200] "GET /bigbluebutton/api/getRecordings?meetingID=hgbycwsbbaioicihy7lvpastbbag0icjfyc4d8jr&checksum=f607cca1d98930e60d818b344600d0b868b6f593 HTTP/1.1" 200 241 "-" "Ruby"
> xx.xxx.xxx.xxx - - [11/Apr/2021:00:56:37 +0200] "GET /images/bjrk_logo_web.png HTTP/1.1" 200 19839 "https://my-domain.com/" "Mozilla/5.0 (Linux; Android 10; SM-T720) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.105 Safari/537.36"
> 172.18.0.3 - - [11/Apr/2021:00:56:54 +0200] "GET /bigbluebutton/api/isMeetingRunning?meetingID=hgbycwsbbaioicihy7lvpastbbag0icjfyc4d8jr&checksum=d9f6c6759aa14d7cb1facd385bedc2ede2d3d065 HTTP/1.1" 200 93 "-" "Ruby"
> 172.18.0.3 - - [11/Apr/2021:00:56:54 +0200] "GET /bigbluebutton/api/getRecordings?meetingID=hgbycwsbbaioicihy7lvpastbbag0icjfyc4d8jr&checksum=f607cca1d98930e60d818b344600d0b868b6f593 HTTP/1.1" 200 241 "-" "Ruby"
> 172.18.0.3 - - [11/Apr/2021:00:57:00 +0200] "GET /bigbluebutton/api/isMeetingRunning?meetingID=hgbycwsbbaioicihy7lvpastbbag0icjfyc4d8jr&checksum=d9f6c6759aa14d7cb1facd385bedc2ede2d3d065 HTTP/1.1" 200 93 "-" "Ruby"
> yyy.yyy.yyy.yyy - - [11/Apr/2021:00:57:00 +0200] "GET /client/conf/config.xml HTTP/1.1" 404 136 "-" "Apache-HttpClient/4.5.6 (Java/1.8.0_282)"
> 172.18.0.3 - - [11/Apr/2021:00:57:00 +0200] "GET /bigbluebutton/api/create?attendeePW=OtEmRJyikZzM&guestPolicy=ASK_MODERATOR&logoutURL=https%3A%2F%2Fmy-domain.com%2Fb%2Ftho-oid-f4g-gri%2Flogout&meetingID=hgbycwsbbaioicihy7lvpastbbag0icjfyc4d8jr&meta_bbb-origin=Greenlight&meta_bbb-origin-server-name=my-domain.com&meta_bbb-origin-version=v2-custom&meta_gl-listed=false&moderatorOnlyMessage=Um+jemanden+zur+Konferenz+einzuladen%2C+schicken+Sie+ihm+diesen+Link%3A%3Cbr%3E+https%3A%2F%2Fmy-domain.com%2Fb%2Ftho-oid-f4g-gri&moderatorPW=kHjhkoyjRvMM&muteOnStart=true&name=Startraum&record=true&checksum=d3ad327066b7f868e1aee7484c5f403d41d2f66b HTTP/1.1" 200 775 "-" "Ruby"
> xx.xxx.xxx.xxx - - [11/Apr/2021:00:57:00 +0200] "GET /bigbluebutton/api/join?createTime=1618095324607&fullName=Test&join_via_html5=true&meetingID=hgbycwsbbaioicihy7lvpastbbag0icjfyc4d8jr&password=OtEmRJyikZzM&userID=gl-guest-42bd2a66a817abea115de351&checksum=0d19a3120822c201df3fa2dcef6cf4d5d33858d5 HTTP/1.1" 302 0 "https://my-domain.com/" "Mozilla/5.0 (Linux; Android 10; SM-T720) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.105 Safari/537.36"
> xx.xxx.xxx.xxx - - [11/Apr/2021:00:57:00 +0200] "GET /html5client/join?sessionToken=7sjtfwljv35pt1u9 HTTP/1.1" 200 5072 "https://my-domain.com/" "Mozilla/5.0 (Linux; Android 10; SM-T720) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.105 Safari/537.36"
> xx.xxx.xxx.xxx - - [11/Apr/2021:00:57:01 +0200] "GET /html5client/5698c061cfba32badc3285de664514e3f4c25d8b.css?meteor_css_resource=true HTTP/1.1" 200 3497 "https://my-domain.com/html5client/join?sessionToken=7sjtfwljv35pt1u9" "Mozilla/5.0 (Linux; Android 10; SM-T720) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.105 Safari/537.36"
> xx.xxx.xxx.xxx - - [11/Apr/2021:00:57:01 +0200] "GET /html5client/compatibility/adapter.js?v=1552 HTTP/1.1" 200 36713 "https://my-domain.com/html5client/join?sessionToken=7sjtfwljv35pt1u9" "Mozilla/5.0 (Linux; Android 10; SM-T720) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.105 Safari/537.36"
> xx.xxx.xxx.xxx - - [11/Apr/2021:00:57:01 +0200] "GET /html5client/compatibility/kurento-utils.js?v=1552 HTTP/1.1" 200 38659 "https://my-domain.com/html5client/join?sessionToken=7sjtfwljv35pt1u9" "Mozilla/5.0 (Linux; Android 10; SM-T720) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.105 Safari/537.36"
> xx.xxx.xxx.xxx - - [11/Apr/2021:00:57:01 +0200] "GET /html5client/compatibility/sip.js?v=1552 HTTP/1.1" 200 169187 "https://my-domain.com/html5client/join?sessionToken=7sjtfwljv35pt1u9" "Mozilla/5.0 (Linux; Android 10; SM-T720) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.105 Safari/537.36"
> xx.xxx.xxx.xxx - - [11/Apr/2021:00:57:01 +0200] "GET /html5client/fc47c37407fe894303d9dabbd8a10008fe2721b6.js?meteor_js_resource=true HTTP/1.1" 200 820107 "https://my-domain.com/html5client/join?sessionToken=7sjtfwljv35pt1u9" "Mozilla/5.0 (Linux; Android 10; SM-T720) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.105 Safari/537.36"
> xx.xxx.xxx.xxx - - [11/Apr/2021:00:57:01 +0200] "GET /html5client/fonts/SourceSansPro/SourceSansPro-Regular.woff HTTP/1.1" 200 148620 "https://my-domain.com/html5client/5698c061cfba32badc3285de664514e3f4c25d8b.css?meteor_css_resource=true" "Mozilla/5.0 (Linux; Android 10; SM-T720) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.105 Safari/537.36"
> xx.xxx.xxx.xxx - - [11/Apr/2021:00:57:03 +0200] "GET /html5client/sockjs/info?cb=chc5abuvgk HTTP/1.1" 200 90 "https://my-domain.com/html5client/join?sessionToken=7sjtfwljv35pt1u9" "Mozilla/5.0 (Linux; Android 10; SM-T720) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.105 Safari/537.36"
> xx.xxx.xxx.xxx - - [11/Apr/2021:00:57:03 +0200] "GET /bigbluebutton/api/enter?sessionToken=7sjtfwljv35pt1u9 HTTP/1.1" 200 2154 "https://my-domain.com/html5client/join?sessionToken=7sjtfwljv35pt1u9" "Mozilla/5.0 (Linux; Android 10; SM-T720) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.105 Safari/537.36"
> xx.xxx.xxx.xxx - - [11/Apr/2021:00:57:04 +0200] "GET /html5client/locale?locale=de-DE&init=true HTTP/1.1" 200 61 "https://my-domain.com/html5client/join?sessionToken=7sjtfwljv35pt1u9" "Mozilla/5.0 (Linux; Android 10; SM-T720) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.105 Safari/537.36"
> xx.xxx.xxx.xxx - - [11/Apr/2021:00:57:04 +0200] "GET /html5client/locales/en.json HTTP/1.1" 200 12620 "https://my-domain.com/html5client/join?sessionToken=7sjtfwljv35pt1u9" "Mozilla/5.0 (Linux; Android 10; SM-T720) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.105 Safari/537.36"
> xx.xxx.xxx.xxx - - [11/Apr/2021:00:57:04 +0200] "GET /html5client/locales/de.json HTTP/1.1" 200 14430 "https://my-domain.com/html5client/join?sessionToken=7sjtfwljv35pt1u9" "Mozilla/5.0 (Linux; Android 10; SM-T720) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.105 Safari/537.36"
> xx.xxx.xxx.xxx - - [11/Apr/2021:00:57:04 +0200] "GET /bigbluebutton/presentation/17060b39d2ad0b35b42ac5469be2c5f9527eb375-1618095324607/17060b39d2ad0b35b42ac5469be2c5f9527eb375-1618095324607/d2d9a672040fbde2a47a10bf6c37b6a4b5ae187f-1618095324624/svg/2 HTTP/1.1" 200 29167 "https://my-domain.com/html5client/join?sessionToken=7sjtfwljv35pt1u9" "Mozilla/5.0 (Linux; Android 10; SM-T720) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.105 Safari/537.36"
> xx.xxx.xxx.xxx - - [11/Apr/2021:00:57:04 +0200] "GET /bigbluebutton/presentation/17060b39d2ad0b35b42ac5469be2c5f9527eb375-1618095324607/17060b39d2ad0b35b42ac5469be2c5f9527eb375-1618095324607/d2d9a672040fbde2a47a10bf6c37b6a4b5ae187f-1618095324624/svg/3 HTTP/1.1" 200 29167 "https://my-domain.com/html5client/join?sessionToken=7sjtfwljv35pt1u9" "Mozilla/5.0 (Linux; Android 10; SM-T720) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.105 Safari/537.36"
> xx.xxx.xxx.xxx - - [11/Apr/2021:00:57:04 +0200] "GET /html5client/fonts/BbbIcons/bbb-icons.woff?j1ntjp HTTP/1.1" 200 16556 "https://my-domain.com/html5client/5698c061cfba32badc3285de664514e3f4c25d8b.css?meteor_css_resource=true" "Mozilla/5.0 (Linux; Android 10; SM-T720) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.105 Safari/537.36"
> xx.xxx.xxx.xxx - - [11/Apr/2021:00:57:04 +0200] "GET /html5client/fonts/SourceSansPro/SourceSansPro-Light.woff HTTP/1.1" 200 146020 "https://my-domain.com/html5client/5698c061cfba32badc3285de664514e3f4c25d8b.css?meteor_css_resource=true" "Mozilla/5.0 (Linux; Android 10; SM-T720) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.105 Safari/537.36"
> xx.xxx.xxx.xxx - - [11/Apr/2021:00:57:04 +0200] "GET /html5client/fonts/SourceSansPro/SourceSansPro-Semibold.woff HTTP/1.1" 200 150320 "https://my-domain.com/html5client/5698c061cfba32badc3285de664514e3f4c25d8b.css?meteor_css_resource=true" "Mozilla/5.0 (Linux; Android 10; SM-T720) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.105 Safari/537.36"
> xx.xxx.xxx.xxx - - [11/Apr/2021:00:57:04 +0200] "GET /html5client/fonts/SourceSansPro/SourceSansPro-Bold.woff HTTP/1.1" 200 151868 "https://my-domain.com/html5client/5698c061cfba32badc3285de664514e3f4c25d8b.css?meteor_css_resource=true" "Mozilla/5.0 (Linux; Android 10; SM-T720) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.105 Safari/537.36"
> xx.xxx.xxx.xxx - - [11/Apr/2021:00:57:04 +0200] "GET /html5client/fonts/SourceSansPro/SourceSansPro-Italic.woff HTTP/1.1" 200 115924 "https://my-domain.com/html5client/5698c061cfba32badc3285de664514e3f4c25d8b.css?meteor_css_resource=true" "Mozilla/5.0 (Linux; Android 10; SM-T720) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.105 Safari/537.36"
> xx.xxx.xxx.xxx - - [11/Apr/2021:00:57:04 +0200] "GET /html5client/resources/sounds/bbb-handRaise.mp3 HTTP/1.1" 206 6975 "https://my-domain.com/html5client/join?sessionToken=7sjtfwljv35pt1u9" "Mozilla/5.0 (Linux; Android 10; SM-T720) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.105 Safari/537.36"
> xx.xxx.xxx.xxx - - [11/Apr/2021:00:57:04 +0200] "GET /bigbluebutton/presentation/17060b39d2ad0b35b42ac5469be2c5f9527eb375-1618095324607/17060b39d2ad0b35b42ac5469be2c5f9527eb375-1618095324607/d2d9a672040fbde2a47a10bf6c37b6a4b5ae187f-1618095324624/svg/1 HTTP/1.1" 200 215371 "https://my-domain.com/html5client/join?sessionToken=7sjtfwljv35pt1u9" "Mozilla/5.0 (Linux; Android 10; SM-T720) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.105 Safari/537.36"
> xx.xxx.xxx.xxx - - [11/Apr/2021:00:57:07 +0200] "GET /bigbluebutton/api/stuns?sessionToken=7sjtfwljv35pt1u9 HTTP/1.1" 200 632 "https://my-domain.com/html5client/join?sessionToken=7sjtfwljv35pt1u9" "Mozilla/5.0 (Linux; Android 10; SM-T720) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.105 Safari/537.36"
> xx.xxx.xxx.xxx - - [11/Apr/2021:00:57:30 +0200] "GET /ws?sessionToken=7sjtfwljv35pt1u9 HTTP/1.1" 101 3306 "-" "Mozilla/5.0 (Linux; Android 10; SM-T720) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.105 Safari/537.36"
> xx.xxx.xxx.xxx - - [11/Apr/2021:00:57:30 +0200] "GET /html5client/sockjs/075/qcx9c0de/websocket HTTP/1.1" 101 103727 "-" "Mozilla/5.0 (Linux; Android 10; SM-T720) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.105 Safari/537.36"
> xx.xxx.xxx.xxx - - [11/Apr/2021:00:57:30 +0200] "GET /html5client/resources/sounds/LeftCall.mp3 HTTP/1.1" 206 20257 "https://my-domain.com/html5client/join?sessionToken=7sjtfwljv35pt1u9" "Mozilla/5.0 (Linux; Android 10; SM-T720) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.105 Safari/537.36"
> 172.18.0.3 - - [11/Apr/2021:00:57:31 +0200] "GET /bigbluebutton/api/isMeetingRunning?meetingID=hgbycwsbbaioicihy7lvpastbbag0icjfyc4d8jr&checksum=d9f6c6759aa14d7cb1facd385bedc2ede2d3d065 HTTP/1.1" 200 93 "-" "Ruby"
> 172.18.0.3 - - [11/Apr/2021:00:57:31 +0200] "GET /bigbluebutton/api/getRecordings?meetingID=hgbycwsbbaioicihy7lvpastbbag0icjfyc4d8jr&checksum=f607cca1d98930e60d818b344600d0b868b6f593 HTTP/1.1" 200 241 "-" "Ruby"

**Comment by pedrobmarin** [comment]
Hmm, what are you configuring at https://github.com/bigbluebutton/bigbluebutton/blob/ef337acbe6055beac8fb8f41ebe633caca5443db/bigbluebutton-web/grails-app/conf/bigbluebutton.properties#L155-L156

**Comment by jrk-omf** [comment]
> Hmm, what are you configuring at
> 
> https://github.com/bigbluebutton/bigbluebutton/blob/ef337acbe6055beac8fb8f41ebe633caca5443db/bigbluebutton-web/grails-app/conf/bigbluebutton.properties#L155-L156

Okay, this was it - sorry, that wasn't well enough described for me :-)

**Comment by pedrobmarin** [comment]
Yeah, just to everyone involved on trying to solve this one to know what was going on, when you set `authenticatedGuest=false` you will only have guests waiting to join if you set `guest=true` at the join API call. GreenLight has no support for this yet.
