### ISSUE TITLE
Update akka-apps screenshare code left from 2.2

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#11761]
**Implementation request**
Update the akka-apps deskshare (red5 related and freeswitch webrtc screenshare related) code with the current screenshare.

Also drop or update /usr/share/bbb-apps-akka/conf/application.conf section
```
red5 {
    deskshareip="<ip>"
    deskshareapp="video-broadcast"
}
```

**Comment by prlanzarin** [comment]
[Internal messages](https://github.com/bigbluebutton/bigbluebutton/blob/develop/bbb-common-message/src/main/scala/org/bigbluebutton/common2/msgs/VoiceConfMsgs.scala#L9-L108) that should be slated for review/refactor/removal:

- ScreenshareHangUpVoiceConfMsg
- ScreenshareRtmpBroadcastStartedVoiceConfEvtMsg
- ScreenshareRtmpBroadcastStartedEvtMsg
- ScreenshareRtmpBroadcastStartedEvtMsg
- ScreenshareRtmpBroadcastStartedEvtMsg
- ScreenshareRtmpBroadcastStartedEvtMsg
- ScreenshareStartRtmpBroadcastVoiceConfMsg
- ScreenshareStoppedVoiceConfEvtMsg
- ScreenshareStopRtmpBroadcastVoiceConfMsg

They still carry a lot of weight from the Flash inter-op and Verto screen sharing and could be significantly simplified.

**Comment by prlanzarin** [comment]
future ref:
- https://github.com/bigbluebutton/bigbluebutton/pull/13187/

Preferably turn 13187 into a new ejection message that: 1) is discernible from the *Stop event  2) has a proper ejection reason attribute
