### ISSUE TITLE
ShareMyNotes

### ISSUE THREAD

**Issue by Bachta96** [bigbluebutton/bigbluebutton#11762]
ShareMyNotes is a feature that will allow students to share their notes, courses or any other work material on the platform and other students to take advantage of these materials. Each student who has made sheets for a course can share their course on the platform. 
The functionality will then be divided by section. The sections can correspond to different high schools / universities or just to different subjects. Each student wanting to add a support, then other students will judge if the document can become public and if so the platform offers some kind of reward to the student.
Each University can then find a whole data base of their courses with notes and even exams of last years. The feature can become after that a full separate platform under BBB.

**Comment by basisbit** [comment]
@Bachta96 I suggest you to read about what BigBlueButton is and what a learn management system is. The features you suggested are something for a LMS, not for BBB.
