### ISSUE TITLE
MyGrades

### ISSUE THREAD

**Issue by Bachta96** [bigbluebutton/bigbluebutton#11760]
My Grades would be a feature where professors can add students' grades and thus their GPA. Students will be able to consult their grades with notifications for each grade added and also an automatic calculation of their GPA according to their University.

Each time a professor want to add a grade he can add it with this feature and students receive a notification which is not the case in other platforms.

The other alternatives are posting the grade on the actual platforms but having all the information on a unique plateform as BBB is better for students.

**Comment by basisbit** [comment]
@Bachta96 Please describe what this has to do with BigBlueButton and what you want to be changed or added. BigBlueButton is a video conferencing system for online-teaching. Grades and so on should be tracked in your learn management system. I am not sure what use case there is where a change in BBB would be needed.

**Comment by basisbit** [comment]
For a list of LMS and similar systems which can integrate BBB video conferencing, see https://bigbluebutton.org/integrations/
