### ISSUE TITLE
Feature request: CameraQualityThreshold, exclude currently speaking/presentator/moderators?

### ISSUE THREAD

**Issue by einhirn** [bigbluebutton/bigbluebutton#11764]
**Is your feature request related to a problem? Please describe.**
No, `CameraQualityThreshold` just applies to any video in the session, so a lecturer will have reduced video quality when there are many cameras active.

**Describe the solution you'd like**
Exclude some videos from the reduction in quality effected by CameraQualityThreshold setting.
Perhaps this is related to #9392 - that issue mentions some kind of "Last N speakers"-logic for reducing the frame rate of "inactive" videos.
This also might work by excluding the video of the user having the "presenter" role, or maybe even excluding the first N moderators...

**Describe alternatives you've considered**
Accept overall reduced quality in settings with many videos, not "focus"- or full-screening single videos in that case.
If higher video quality is needed, reduce the number of active cameras.

**Comment by prlanzarin** [comment]
> **Is your feature request related to a problem? Please describe.**
> 
> The camera profiles defined in `cameraQualityThresholds` are applied to all inbound cameras.
> 
> It would be interesting if the audio floor's camera had its original profile preserved (ie floors should bypass `cameraQualityThresholds`).
> 
> This should provide a better overall experience while still preserving the resource usage control provided by `cameraQualityThresholds`.
> 
> **Describe the solution you'd like**
> 
> - [ ] Add a **configurable** option to preserve the current audio floor's original camera profile when `cameraQualityThresholds` is **active**
> 
> **Additional context**
> 
> The streams collection already have a `floor` (Boolean) property which indicates whether a stream comes from an audio floor or not.
> 
> Use that property to restore the original profile in https://github.com/bigbluebutton/bigbluebutton/blob/c16567ecf212809e11020288d3968adcd7fb8998/bigbluebutton-html5/imports/ui/components/video-provider/component.jsx#L232-L243.
> 
> The `floor` property is filtered out in some sorting modes. If the prioritization is enabled, the prop should be included in the needed data types in https://github.com/bigbluebutton/bigbluebutton/blob/develop/bigbluebutton-html5/imports/ui/components/video-provider/stream-sorting.js
