### ISSUE TITLE
Etherpad fails to fully launch after 2.3-beta upgrade...

### ISSUE THREAD

**Issue by markginter31** [bigbluebutton/bigbluebutton#11778]
I dug around in the other issues [11497](https://github.com/bigbluebutton/bigbluebutton/issues/11497) but none of the solutions seemed to work.  From journalctl I see:

[DEBUG] console - Running on Node v12.20.1 (minimum required Node version: 8.9.0)
[INFO] console - All relative paths will be interpreted relative to the identified Etherpad base dir: /usr/share/etherpad-li
 [DEBUG] AbsolutePaths - Relative path "settings.json" can be rewritten to "/usr/share/etherpad-lite/settings.json"
[DEBUG] AbsolutePaths - Relative path "credentials.json" can be rewritten to "/usr/share/etherpad-lite/credentials.json"
 [INFO] console - settings loaded from: /usr/share/etherpad-lite/settings.json
INFO] console - No credentials file found in /usr/share/etherpad-lite/credentials.json. Ignoring.
[INFO] console - Using skin "no-skin" in dir: /usr/share/etherpad-lite/src/static/skins/no-skin
INFO] console - Session key loaded from: /usr/share/etherpad-lite/SESSIONKEY.txt
 [ERROR] console - soffice (libreoffice) does not exist at this path, check your settings file. File location: /usr/bin/soffi
 node[17770]: events.js:291
 node[17770]:       throw er; // Unhandled 'error' event
node[17770]:       ^
 node[17770]: Error: Redis connection to localhost:6379 failed - connect ECONNREFUSED 127.0.0.1:6379
node[17770]:     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1144:16)
 node[17770]: Emitted 'error' event on RedisClient instance at:
 node[17770]:     at RedisClient.on_error (/usr/share/etherpad-lite/src/node_modules/redis/index.js:406:14)
node[17770]:     at Socket.<anonymous> (/usr/share/etherpad-lite/src/node_modules/redis/index.js:279:14)
 node[17770]:     at Socket.emit (events.js:314:20)

A quick systemctl status redis-server shows that it is running.
A quick systemctl status etherpad shows that it tries to start, and then it exits, and then tries to start again with this:
 "ueberdb_writesToDbFinished": 0
 [ERROR] server - Error: Command exited with code 1: npm ls --long --json --depth=0 --no-production
     at exports (/usr/share/etherpad-lite/src/node/utils/run_cmd.js:119:25)
     at Object.exports.getPackages (/usr/share/etherpad-lite/src/static/js/pluginfw/plugins.js:125:48)
    at Object.exports.update (/usr/share/etherpad-lite/src/static/js/pluginfw/plugins.js:99:34)
     at Object.exports.start (/usr/share/etherpad-lite/src/node/server.js:139:19)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
 [2021-03-28 06:55:52.808] [INFO] server - Exiting...
 [2021-03-28 06:55:52.809] [INFO] server - Waiting for Node.js to exit...

And - in syslog:
 [ERROR] runCmd|npm - #033[39mnpm ERR! missing: ep_author_follow@0.1.14, required by etherpad-lite
I used npm to install the ep_author_follow, but etherpad still won't start and stay started.  Exits with above errors...

This is the first time etherpad has acted up after an update.  I've been using bbb-install.sh from 2.3-alpha1 ...

**Comment by pedrobmarin** [comment]
Anything else you have running custom at your Etherpad?

**Comment by markginter31** [comment]
I do not. Only bbb.

**Comment by pedrobmarin** [comment]
A fresh `bbb-etherpad` install might be nice to check if the problem you had was something related to any change left behind. You can stop etherpad's service, make a backup of `/usr/share/etherpad-lite` folder and run an `apt-get install --reinstall bbb-etherpad`. After that, copy your old APIKEY file over the new one to avoid having to configure that all over the place and restart etherpad's service.

**Comment by markginter31** [comment]
That worked. Thank you!
