### ISSUE TITLE
Using turn server in WAN and LAN

### ISSUE THREAD

**Issue by amini2425** [bigbluebutton/bigbluebutton#11770]
Dears
I installed bbb with turn server because we have a strict firewall and bb use behind NAT, everything work well in WAN but users in LAN see ICE 1007 Error.
BBB-Pub-IP: 46.X.Y.Z
BBB-Private-IP: 172.16.Y.Z
TurnSRV-Pub-IP: 46.A.B.C
TurnSRV-Private-IP: 172.16.B.C
Could you please reply me if you resolve this issue.

**Comment by basisbit** [comment]
For support requests, please use the [forum / mailing list](https://groups.google.com/forum/#!forum/bigbluebutton-setup). This issue tracker here is only for BBB development related issues. Sorry.
