### ISSUE TITLE
Microphone access dialog partially off-screen on smartphone browsers

### ISSUE THREAD

**Issue by hjek** [bigbluebutton/bigbluebutton#11775]
**Describe the bug**
The microphone access dialog is partially off-screen to the right on smartphone browsers (or a similarly sized vertical window on a desktop browser)

**To Reproduce**
1. Join a BBB meeting
2. Choose to join via audio
3. The microphone access dialog will then appear partially off the screen (or browser window)

**Expected behavior**
I expected the dialog box to be centered and thus readable because there's plenty of space for that.

**Actual behavior**
Half of the dialog box is cut off because it's too far to the right.

**Screenshots**

BBB in Chrome on Android:
![BBB_chrome_android](https://user-images.githubusercontent.com/11958965/112737500-4a85a300-8f5b-11eb-8b5e-23dde00a727a.png)

BBB in Firefox on Debian:
![Screenshot_2021-03-27 BigBlueButton - test01](https://user-images.githubusercontent.com/11958965/112737541-8fa9d500-8f5b-11eb-91a3-7db1e0e83fff.png)

**BBB version:**
`Client build: 1006` according to the **About** dialog.

**Desktop:**
 - OS: Debian
 - Browser: Firefox
 - Version 87.0

**Smartphone (please complete the following information):**
 - Device: unkown
 - OS: Android
 - Browser: Chrome
 - Version: unknown

**Suggested solution**

This is the current styling of the dialog:
```
.hint--2rRCSB {
 position: absolute;
 left: var(--position-left-firefox);
}
```

If it is changed to this then the dialog box is centered:
```
.hint--2rRCSB {
 position: absolute;
 left: 0;
 right: 0;
 margin-left: auto;
 margin-right: auto;
}
```

Screenshot of the suggested fix:
![Screenshot_2021-03-27 BigBlueButton - test01 fixed](https://user-images.githubusercontent.com/11958965/112737713-b74d6d00-8f5c-11eb-9c13-544c5b468c3d.png)

**Comment by basisbit** [comment]
please update your BigBlueButton server to a somewhat recent version. If the problem still occurs, please comment here and we will reopen the issue.
