### ISSUE TITLE
System of random attendance during the online courses

### ISSUE THREAD

**Issue by Bachta96** [bigbluebutton/bigbluebutton#11787]
Online courses during the Covid 19 crisis have been a very practical solution for both teachers and students. However, absences during online courses have become problematic for teachers in the sense that some students log in for a course but do not necessarily follow. A continuous absence system during the course could be a solution. For this, a feature that would make it possible to verify that the student is currently following during the course could be a solution. During the course an attendance system would be set up randomly and the student has an allotted time (15 seconds for example) to press a button and confirm his presence. Obviously not all the students have this confirmation at the same time but each student would have on average 1 confirmation every 10 minutes for example. This would allow teachers to know that the students are taking the course and would force the students to take the course.

**Comment by mohe2015** [comment]
I don't know if this is really worth it, it won't work because there *will* be people that will write a browser addon or so to press the button and also just sitting in front of the PC but e.g. playing games still works.

It's like before the pandemic: paying attention can not be forced.
