### ISSUE TITLE
Update browser detection library

### ISSUE THREAD

**Issue by pedrobmarin** [bigbluebutton/bigbluebutton#11790]
We are currently using https://github.com/bigbluebutton/bigbluebutton/blob/develop/bigbluebutton-html5/package.json#L39 as a browser detection library. The last update made to this lib was 3 years ago (https://www.npmjs.com/package/browser-detect). There are already some issues being reported regarding the mobile detection for some devices (iPads mostly).

There are a couple of alternatives that seem better than this lib, e.g:
 - https://www.npmjs.com/package/bowser
 - https://www.npmjs.com/package/detect-browser

**Comment by daminebenq** [comment]
#11806 didn't solve this issue.

**Comment by pedrobmarin** [comment]
Personally I think you should stay with `bowser`. Look's like the healthier choice right now. Maybe IPads just need a little tweak because Apples UA are a mess

**Comment by ramonlsouza** [comment]
Thanks for the suggestions @pedrobmarin! I'll go back to this issue tomorrow.
My PR was merged+reverted because we could not test it on ipads/iphones before the merge (but we found a way to do it now)

**Comment by pedrobmarin** [comment]
We were following @mariogasparoni's work on the audio button and @prlanzarin pointed out this other lib `react-device-detect`. Does anyone knows why we have two different libs doing almost the same thing?
