### ISSUE TITLE
Customized Logout Button

### ISSUE THREAD

**Issue by mandakni** [bigbluebutton/bigbluebutton#11802]
I have setup bigbluebutton to my server and it works perfectly as per the requirement. I have done some customization but i am stuck in logout customization. i have changed the logout url and it redirect to assigned url not i need to show the logout and end meeting button on default screen with big icon like audio,webcam and screen share. Is it Posssible ?

**Comment by basisbit** [comment]
For development/customization support requests, please use the [forum / mailing list](https://groups.google.com/forum/#!forum/bigbluebutton-dev). This issue tracker here is only for BBB project development related issues. Sorry.
