### ISSUE TITLE
[2.3] Connection status button is overlapping

### ISSUE THREAD

**Issue by daminebenq** [bigbluebutton/bigbluebutton#11816]
Just like #11733.
Reproducible on develop branch, and 2.3 beta-1.

![image](https://user-images.githubusercontent.com/5144311/113043162-6d3dd480-9172-11eb-890d-671f0d8005a5.png)

PS: This is on PC, and it maybe happens on small mobile devices.

**Comment by antobinary** [comment]
@daminebenq please add more info - is this mobile?
Looks like 2.3-beta~2

**Comment by daminebenq** [comment]
I just edited the ^comment
