### ISSUE TITLE
Some Tooltips don't automatically disappear

### ISSUE THREAD

**Issue by daminebenq** [bigbluebutton/bigbluebutton#11814]
**Expected behavior:**
Hovering on a button should show a Tooltip, which should disappear when the mouse moves away from the button.

**Current behavior:**

https://user-images.githubusercontent.com/5144311/113042442-94e06d00-9171-11eb-9f6c-1bc4c8832fc5.mp4

**Comment by PlumedArcher** [comment]
This behavior can be observed on Chrome and  Microsoft Edge.
