### ISSUE TITLE
Can someone explain the websocket interaction?

### ISSUE THREAD

**Issue by FelixSelter** [bigbluebutton/bigbluebutton#11823]
I'm trying to write an own client for the BBB-Websocket system

Would be really nice if some dev could take 15min to explain how the interaction is working.
Currently, I joined the Session and did the first handshakes like submitting the auth token, etc.
For stuff like sending messages, I can easily look up the token. I'm more interested in the default routine.
The huge js file is a bit unreadable

Thanks, help would be really appreciated

**Comment by prlanzarin** [comment]
Appropriate place is the bigbluebutton-dev mailing list, so I'm closing this.
See: https://docs.bigbluebutton.org/2.2/getting-help.html
See: https://docs.bigbluebutton.org/2.2/architecture.html

**Comment by FelixSelter** [comment]
So please accept me for the mailing list
