### ISSUE TITLE
Freeswitch max number of users with mic

### ISSUE THREAD

**Issue by bilias** [bigbluebutton/bigbluebutton#11822]
We're trying to run a specific meeting with approx ~ 150 users
More than half of them connect with mic -> freeswitch and rest listen only -> kurento
PDF presentation and maybe one camera from presenter/moderator.
BigBlueButton is 2.2.35

Server load is fine with the load (~ 2 @ 16 cores)
Freeswitch  is around 150%

After ~70-90 users have connected to freeswitch then you can cannot connect more users with mic.
Random errors 1007, 1008
Clicking listen only make user join. After a while maybe the system allows you to join via mic.

There is a stun server involved but it's also without load (only running this meeting on Saturday afternoon).

My guess is that freeswitch should be able to handle much more than this. Isn't this true?
I cannot make anything from logging nor browser webrtc debug.

What would you suggest? Maybe there is a hardcoded limit somewhere or a timeout?
If you manage to connect with mic, then you're not disconnected (at least not me).

**Comment by schrd** [comment]
Freeswitch is definitively able to handle more than 400 concurrent users on a single server. Freeswitch CPU usage scales almost linear with the number of participants. On my servers its about 1 core per 50 participants. 

This must be something related with your setup. Check the number of file handles, if there is a firewall involved, check number of connections it is able to handle. Check network traffic if there were many cameras involved. Check for packet loss (`netstat -su`), especially if your setup runs in a virtualized environment.

This is not a BBB bug and should be closed IMHO. Please use the forums for troubleshooting assitance.

**Comment by prlanzarin** [comment]
https://docs.bigbluebutton.org/2.2/getting-help.html
