### ISSUE TITLE
Setup for a local client (dev mode) and a remote bbb-server 

### ISSUE THREAD

**Issue by ouya99** [bigbluebutton/bigbluebutton#11832]
Given i wanted to make changes to the BBB-HTML5 frontend and am already running my bbb on a remote server.

On my client i checkout the same bbb (BBB-HTML5 included) and would like to connect to the bbb on my remote server 

I updated host and port for etherpad and redis in settings.yml . Then I tried to just launch BBB on my client with "meteor"

At first it starts up a local server (which i won't need) 

I20210331-21:23:28.140(2)? warn: Started bbb-html5 process with instanceId=1
I20210331-21:23:28.140(2)? warn: SERVER STARTED.
I20210331-21:23:28.140(2)?   ENV=development
I20210331-21:23:28.140(2)?   nodejs version=v12.21.0
I20210331-21:23:28.140(2)?   BBB_HTML5_ROLE=undefined
I20210331-21:23:28.140(2)?   INSTANCE_ID=1
I20210331-21:23:28.140(2)?   PORT=23218
I20210331-21:23:28.140(2)?   CDN=

and then i'm seeing this redis error. 

=> Started your app.

=> App running at: http://localhost:3000/
I20210331-21:23:57.938(2)? info: Active connections
I20210331-21:24:27.940(2)? info: Active connections
I20210331-21:24:42.976(2)? error: uncaughtException: Redis connection to HOST:6379 failed - connect ETIMEDOUT 159.89.109.81:6379
I20210331-21:24:42.977(2)? Error: Redis connection to HOST:6379 failed - connect ETIMEDOUT HOST:6379

On my server I adjusted the redis server to 0.0.0.0 (which should fix the connection), but it would not. I can ping-pong my redis-server, yet I am not getting a " redis-cli" connection from my client to the server.

Yet I still do not even know if this was the right way to go. Or should I use a npm-script given in package.json and configure it correctly? what would it be like?

Thanks for pointing me in any direction. I have been browsing issues for hours now, but seems that either this setup is not possible or nobody is having that issue.

Thank you

**Comment by antobinary** [comment]
I have not tried to connect to redis on a remote machine for bbb-html5 development.
However, you could deploy locally your bbb-html5 changes (on the same server you're developing) so you can confirm all works as you intended it. Check https://github.com/bigbluebutton/bigbluebutton/blob/v2.3-beta-1/bigbluebutton-html5/deploy_to_usr_share.sh

Once happy with the results you could then copy over /usr/share/meteor/bundle* (that you deployed locally) to your remote server... Make sure to compare permissions / file ownership, etc to the existing packaged files for best results. I have not tried this in production. I made the script to facilitate local deployment for testing in multi nodejs env.

Best place to ask dev questions in future is https://groups.google.com/g/bigbluebutton-dev 
Please comment about whether this worked fine for you.
