### ISSUE TITLE
Screensharing IPad OS

### ISSUE THREAD

**Issue by Herrki** [bigbluebutton/bigbluebutton#11837]
Right now screensharing is not supported on IPad OS.

Screensharing should be possible like ist is on desktop devices.

**Comment by mrkeksi** [comment]
Screensharing is not supported in this browser. From Apple, the implementation in the mobile Safari is not supported.

**Comment by prlanzarin** [comment]
Duplicate of https://github.com/bigbluebutton/bigbluebutton/issues/10051
