### ISSUE TITLE
[2.3] Buttons cut off on small screen [Design]

### ISSUE THREAD

**Issue by mrkeksi** [bigbluebutton/bigbluebutton#11836]
**Describe the Style bug**

I have a small screen with my iPhone 12 mini.  When entering test23.BigBlueButton.org, some buttons are cut directly.

**Screenshots**
![image](https://user-images.githubusercontent.com/8763656/113256518-902ecc80-92c9-11eb-9633-2381ad46dba7.png)
**BBB version (optional):**
1511 on test23.BigBlueButton.org

**Smartphone (please complete the following information):**
 - safari on iOS 14.5 beta 5(?)

**Comment by antobinary** [comment]
Thanks for reporting @mrkeksi 
Solved by https://github.com/bigbluebutton/bigbluebutton/pull/11844
Should be out with 2.3-beta2
