### ISSUE TITLE
Changing timer of breakout rooms after opening them

### ISSUE THREAD

**Issue by bigshit11elf** [bigbluebutton/bigbluebutton#11843]
I'm always frustrated when groups need more time to work and you cannot grant their request. Moderators should have the right to change the timer in breakout rooms after they've been opened.
Alternatives are not really possible. Having the rooms forcefully closed when the timer runs out and re-opening them creates a lot of confusion.

**Comment by nikos-pappas** [comment]
> I'm always frustrated when groups need more time to work and you cannot grant their request. Moderators should have the right to change the timer in breakout rooms after they've been opened.
> Alternatives are not really possible. Having the rooms forcefully closed when the timer runs out and re-opening them creates a lot of confusion.

This is an important enhancement! In fact in the majority of cases you will need to postpone a little the duration of breakout rooms. To overcome this problem I set every time a very long duration and I keep track of time so as to be able to close the rooms at the appropriate time.

**Comment by The-Compiler** [comment]
I agree! I use the same workaround as @nikos-pappas, but that closes the rooms without any advanced warning, so users are often interrupted mid-sentence (and might not even realize until looking at their browser window again).

**Comment by bwurst** [comment]
Another comment to vote this up. 

When breakout rooms are created with random user assignments, you cannot really reproduce to give the users more time.

Would be great to be able to change the timer when breakout rooms are running.

**Comment by peter-lernyx** [comment]
@bwurst I take a screenshot of the breakout rooms in session to do that, so if you have only 3 or so per room it's relatively quick to drag and drop them into their previous rooms again. Of course with 10 per room, that's a different story and it isn't really a professional approach.

**Comment by antobinary** [comment]
Merging into https://github.com/bigbluebutton/bigbluebutton/issues/9435
