### ISSUE TITLE
[2.3 Beta 1] Duplicated private chat messages (viewer → moderator)

### ISSUE THREAD

**Issue by schrd** [bigbluebutton/bigbluebutton#11842]
**Describe the bug**
Chat messages in private chat are duplicated if participant is propagated to moderator

**To Reproduce**
1. let User A be moderator, let User B be viewer
2. User A opens private chat with B
3. A and B exchange some messages
3. propagate User B as moderator
4. Chat messages in User B are duplicated

**Expected behavior**
Chat messages should not be duplicated

**Actual behavior**
Chat messages in private chat are duplicated each time a user is promoted to moderator

**Screenshots**

![Bildschirmfoto von 2021-04-01 14-45-09](https://user-images.githubusercontent.com/179952/113296730-22e75f80-92fa-11eb-998a-8ec6bb990cad.png)

**BBB version (optional):**

BigBlueButton 2.3 Beta 1

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Chromium, Firefox

**Comment by ffdixon** [comment]
Good catch!

**Comment by daminebenq** [comment]
Hi @schrd,
I could reproduce it on a 2.3 beta-1 server, and it was easy to reproduce.

https://user-images.githubusercontent.com/5144311/113307849-f7557c80-92db-11eb-877a-2f51362aeb4a.mp4

Thanks for reporting it.
