### ISSUE TITLE
2.3-beta2: Old messages in public chat not cleared properly

### ISSUE THREAD

**Issue by PhMemmel** [bigbluebutton/bigbluebutton#11859]
**Describe the bug**
Old messages in public chat aren't cleared for attendee when moderator tries to clear chat.

**To Reproduce**
1. Open session
2. Add some public chat messages
2. Let attendee join the session
3. Moderator clears chat
4. Chat in moderator session is cleared
5. Chat in attendee session still there (but welcome message is pushed again)
6. Moderator clears chat again
7. Attendee's chat now properly cleared

This problem is related to the old messages in public chat which were sent before the client joined. The messages before the client joined aren't properly cleared out. As soon as there is a single new message **after** client joined chat gets properly cleared. 

**Expected behavior**
Attendee's chat should be cleared including messages before joining

**Actual behavior**
Chat is not cleared for the attendee, but for the moderator

**BBB version (optional):**
2.3-beta2

**Comment by antobinary** [comment]
Resolved by #12012
