### ISSUE TITLE
Some locales only become available after it's root language is activated

### ISSUE THREAD

**Issue by pedrobmarin** [bigbluebutton/bigbluebutton#11863]
**Describe the bug**
At the language picker, `Português (Brasil)` (brazilian portugues) only gets available after changing the language to `Português`.

**To Reproduce**
1. Access a language selector (tested at settings and closed captions)
2. Search for `Português (Brasil)`
3. Select `Português`
4. Repeat for the same selector

**Expected behavior**
All available languages to be in the selector (the exception would be the languages that are already in use).

**Actual behavior**
Seems like the language root is filtering child languages.

**BBB version (optional):**
BigBlueButton Server 2.3 (1552)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Firefox
 - Version 87.0

**Comment by antobinary** [comment]
This was supposed to be an enhancement https://github.com/bigbluebutton/bigbluebutton/pull/11247
Looks like it's not clear to lots of people. We should probably revert it @ramonlsouza

**Comment by pedrobmarin** [comment]
Maybe just change the default value. Personally I was surprised brazilian portuguese just appeared in.
