### ISSUE TITLE
Bbb-web: Remove config.xml from BigBlueButton 2.3

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#11861]
**Describe the bug**
BigBlueButton 2.3-beta-2 still attempts to load `config.xml` as shown in the nginx error logs

```
open() "/var/www/bigbluebutton-default/client/conf/config.xml" failed (2: No such file or directory), client: xxx.xxx.xxx.xxx, server: bbb.my.site, request: "GET /client/conf/config.xml HTTP/1.1", host: "bbb.my.site"
```

**To Reproduce**
1. Install 2.3-beta-2
2. Launch the BigBlueButton client
3. Check the nginx error logs

**Expected behavior**
The server should not attempt to load `config.xml`

**Comment by pedrobmarin** [comment]
We have an old request to use some kind of config.xml at the HTML5 client https://github.com/bigbluebutton/bigbluebutton/issues/4710 . Looks like this one drives that project to a different path.

@jfsiebel and @antobinary , what you guys think about this?

**Comment by jfsiebel** [comment]
@antobinary, the config xml file is called from here https://github.com/bigbluebutton/bigbluebutton/blob/develop/bbb-common-web/src/main/java/org/bigbluebutton/api/ParamsProcessorUtil.java#L505.

**Comment by antobinary** [comment]
Thanks @jfsiebel !

Looks like we need to clean up / refactor that part of bbb-web. Retagging/Relabelling
