### ISSUE TITLE
2.3-beta2: Microsoft Edge not working at all

### ISSUE THREAD

**Issue by PhMemmel** [bigbluebutton/bigbluebutton#11865]
**Describe the bug**
HTML5 client currently crashing on current Microsoft Edge

**To Reproduce**
1. Open session on 2.3-beta2, for example on test23.bigbluebutton.org
2. Join meeting with current Microsoft Edge browser
3. three white dots disappear after short time
4. screen stays dark blue, error in console appears, see below

**Expected behavior**
Session can be joined properly

**Actual behavior**
HTML5 breaks, no joining possible

**Screenshots**
Browser console shows following error:
![grafik](https://user-images.githubusercontent.com/65113153/113429355-ae372280-93d8-11eb-918e-1ef33ad81d86.png)

**BBB version (optional):**
2.3-beta2, HTML5 client version 1551 and 1552

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser: Microsoft Edge Version 89.0.774.68 (Official Build) (64-Bit)

**Additional context**
originally mentioned by @Miralis in #6135, extracting it to this separate issue

**Comment by prlanzarin** [comment]
I'm re-opening this until beta3 lands with the fix.

**Comment by waesien** [comment]
> Beta3 düzeltmeyle gelene kadar bunu yeniden açıyorum.

I have this problem right now

Where can I not find this file path on the server?

bigbluebutton-html5/imports/ui/components/app/component.jsx

**Comment by prlanzarin** [comment]
You can't, the client is (almost entirely) bundled and minified in a regular installation.

**Comment by waesien** [comment]
> Yapamazsınız, istemci (neredeyse tamamen) normal bir kurulumda paketlenir ve küçültülür.

![image](https://user-images.githubusercontent.com/81984557/113884688-db644600-97c7-11eb-80da-3c3da91b6144.png)

I want to add this part but I can't find the file path, can you help me?

**Comment by prlanzarin** [comment]
Fixed in https://github.com/bigbluebutton/bigbluebutton/releases/tag/v2.3-beta-3

**Comment by nikos-pappas** [comment]
Great news!
