### ISSUE TITLE
Closed captions issue for some languages in 2.3-beta

### ISSUE THREAD

**Issue by vasylOstrovskyi** [bigbluebutton/bigbluebutton#11862]
**Describe the bug**
"Such a padname is forbidden" message appears when trying to add closed captions for some languages.

**To Reproduce**
1. Start BBB session
2. Click on Create closed captions
3. Select Ukrainian language Українська
4. See error "Such a padname is forbidden", also tried Greek with the same result, English is OK

**Expected behavior**
Editor window is opened allowing to add closed captions
**Actual behavior**
Error message in place of the editor window for (at least some) languages whose name contains non-ascii unicode

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04 LTS
 - Browser Chromium
 - Version BigBlueButton 2.3beta-2

**Comment by pedrobmarin** [comment]
Hi @vasylOstrovskyi , thanks for reporting.

The problem here is that Etherpad has a maximum of 50 characters for pad ids and suffixed locales like `uk-UA`, `pt-BR`... exceed that lenght in 2 characters.
