### ISSUE TITLE
problem in selecting audio input/output menu in RTL locales

### ISSUE THREAD

**Issue by afsharsafavi** [bigbluebutton/bigbluebutton#11870]
In demo3.bigbluebutton.org, when I change language to RTL ones (like Farsi, Arabic) , there is a problem for displaying the new menu that recently added for change/leave audio button.
The menu works fine in LTR locales but it seems there is problem in RTL locales.

**To Reproduce**
1.After connecting to a microphone, From the top-right corner, select three dots icon, then select settings option.
2. In the first tab of setting window (Application), change Application Language from English to "فارسی" or "العربیه" and click on Save button.
3. Click on change/leave audio button on bottom-middle of the screen, then you can see the menu displays incorrectly.
(Also the texts of this new button and the new menu didn't translated yet)
**Screenshots**
<img width="936" alt="Screen Shot 2021-04-03 at 06 34 57" src="https://user-images.githubusercontent.com/14315351/113465444-4371ff80-9449-11eb-9a32-dcf9f969be6d.png">

**BBB version (optional):**
2.3-beta-2
**Desktop (please complete the following information):**
 - OS: Mac
 - Browser: FireFox
 - Version 82

**Comment by mariogasparoni** [comment]
Thanks for reporting it.

The text is intended to be translated by transifex.
