### ISSUE TITLE
Use Transifex to localise the welcome message

### ISSUE THREAD

**Issue by hiroshisuga** [bigbluebutton/bigbluebutton#11876]
**Describe the bug**

In the chat window, the welcome message is not translated. We can change it by editing /usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties, but why don't we bring it to Transifex?

**To Reproduce**
1. open a meeting
2. the welcome message is in English

**Expected behavior**
The welcome message is translated.

**Actual behavior**
The welcome message is not translated.

**Additional context**
In searching the past issues, I could find people complaining about the untranslated message. It seems to be planned to be removed in the future. But wouldn't it be more natural to bring it to Transifex before it is finally removed?
English speaking people may not realise how much Japanese students (even university students) are scared seeing English texts;-)
I would not be surprised if this has been already discussed somewhere (although I did not find it). I am sorry for the duplication if it is the case.

**Comment by basisbit** [comment]
Transifex would only work for translating a standard message. However, most setups out there use their own custom welcome message, so using Transifex would only make it more difficult for their setup. There also already exist other issues regarding translation of the welcome message and other similar messages.

**Comment by hiroshisuga** [comment]
I see. Thanks for explaining! I think we can remove these messages completely.
