### ISSUE TITLE
MEDIA_SERVER_OFFLINE after offline STUN/TURN

### ISSUE THREAD

**Issue by mikhailnov** [bigbluebutton/bigbluebutton#11875]
coturn server sometimes crashes and goes offline (why it crashes is another question), people try to connect webcams and get an error 2001 that media server is offline (`MEDIA_SERVER_OFFLINE` in browser console). I restart Kurento (`systemctl restart kurento-media-server.service`), it is restarted successfully, bind to port correctly. But the error on frontend is still shown.

Looks like it caches something. I wanted to make it work without full restart of BBB to avoid interrupting running meetings.

bbb-web 1:2.2.0-142

**Comment by mikhailnov** [comment]
`systemctl restart bbb-webrtc-sfu.service` helps

**Comment by basisbit** [comment]
I suggest fixing the actual issue with your coturn setup instead of trying to handle the symptoms.
Also, for any future issues, please fill in the issue template in order to save some time for other people who read the issue. Thanks.

**Comment by mabras** [comment]
We had 'coturn server sometimes crashes' with ubuntu 16.04. After update to Ubuntu 20.04 version, we do not had this problem anymore.
Just follow the docs:
https://docs.bigbluebutton.org/2.2/setup-turn-server.html#required-software

**Comment by ffdixon** [comment]
We would recommend everyone running coturn update their coturn servers to 20.04.

**Comment by mikhailnov** [comment]
I will make a new coturn server on risa2019.1 rootfs in systemd-nspawn and use a pure systemd unit instead of the one generated from sysvinit script in ubuntu. I am using an older version of bbbbecause I do not like libreoffice in docker, I will have to somehow solve this, unfortunately bbb develioers do not accept contributions to rather crazy packaging of bbb.

But this bug is not about it. Is it expectd behaviour that once coturn goes offline , bbb-webrtc-sfu thinks it is offline even after it is online again?

**Comment by prlanzarin** [comment]
> I am using an older version of bbb

How old? We need an specific version.

> But this bug is not about it. Is it expectd behaviour that once coturn goes offline , bbb-webrtc-sfu thinks it is offline even after it is online again?

bbb-webrtc-sfu is not aware of coturn and does not depend on it.

Kurento might use coturn, but it shouldn't. If your server is behind a 1:1 NAT, use externalIPv4 instead of setting a STUN server in Kurento (which you should avoid at all costs).

Error 2001 being churned means bbb-webrtc-sfu lost connectivity to a specific Kurento instance. Next time it happens, check KMS's uptime before restarting it via systemctl (and get it's exit log and code), because that's either a crash or a signaling connection tear off.

**Comment by prlanzarin** [comment]
@mikhailnov 

Any updates (and specific BBB version...)?
