### ISSUE TITLE
Html5 Client fails in Edge

### ISSUE THREAD

**Issue by nikos-pappas** [bigbluebutton/bigbluebutton#11873]
**Describe the bug**
Congrats, great improvements in 2.3beta2...
I 've just noticed that when trying to join a room using Edge, this results in a black screen.
This happens also to https://test23.bigbluebutton.org/

**To Reproduce**
Just join a room and the interface disappears and nothing happens 

**BBB version (optional):**
BigBlueButton Server 2.3.0-beta-2 (1924)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Microsoft Edge Version 89.0.774.68 (Official build) (64-bit)

**Comment by PhMemmel** [comment]
Already reported in #11865, fixed by #11868 which has already been merged, so will be fixed in next release.
