### ISSUE TITLE
HTML5 Frontend Hangs on the three white loading dots

### ISSUE THREAD

**Issue by Oasis256** [bigbluebutton/bigbluebutton#11879]
**Describe the bug**
BigBlueButton Frontend hangs at the three loading dots while server side logs shows two errors
1. I20210404-18:15:26.654(3)? error: Pads' server unreachable
2. I20210404-18:15:30.109(3)? error: ValidateAuthTokenRespMsg: Error: Match error: Expected string, got undefined

**To Reproduce**
1. [Setup Dev Environment](https://docs.bigbluebutton.org/dev/dev23.html#setup-development-environment)
2. Stop bundled HTML-5 client with 'sudo systemctl stop bbb-html5'
3. Inside '[bigbluebutton-html5' folder, run 'npm start'
3. Start BigBlueButton Meeting
4. Keep an eye on your Terminal Window
4. See errors one shortly after the other
5. Frontend hangs on the three white loading dots

**Expected behavior**
Meeting should begin loading and opening the presentation window.

**Actual behavior**
Frontend Hangs on the three white loading dots

**Screenshots**
Error(s) Image 1
![HTML5](https://user-images.githubusercontent.com/17212431/113513712-b7102b80-9573-11eb-9909-c4031d058be5.jpg)

Error Image 2
![BBB-HTML5](https://user-images.githubusercontent.com/17212431/113513610-39e4b680-9573-11eb-8a0c-814aac2b75f6.jpg)

**BBB version (optional):**
BigBlueButton Server 2.3.0-beta-1 (1848)

**Desktop (please complete the following information):**
 - OS:  Windows 10
 - Browser: Microsoft Edge
 - Version 89.0.774.68 (Official build) (64-bit)

**Additional context**
The same could be happening with the official demo site [v2.3-Beta-2](https://test23.bigbluebutton.org/)

**Comment by antobinary** [comment]
Hi @Oasis256 
Do you see this happen only when you try to join Demo Meeting (but creating a new meeting and joining it is fine)? I see something similar when I try to join a meeting which has started before bbb-html5 (or meteor in dev env) has started. If this is the case, restarting `sudo systemctl restart bbb-web bbb-apps-akka` and only then `meteor reset; npm start` should resolve the issue.

**Comment by Oasis256** [comment]
Tried what @antobinary  Suggested but the result is the same.
This time I waited a bit longer and got 
```
app.error.408
Authentication timeout
408
```
on the Frontend but same errors Server side.
Trying to join keeps you in the waiting room
Here is the image

![Error](https://user-images.githubusercontent.com/17212431/113516619-e9c22000-9583-11eb-9490-d253d791632c.jpg)

**Comment by pedrobmarin** [comment]
Can you check if you are building from the same version you are using from the packages?

**Comment by Oasis256** [comment]
I have v2.3-beta-1 running but am trying to develop HTML5 Client for v2.3-Beta-2.
Could this be the issue?

**Comment by pedrobmarin** [comment]
> I20210404-18:15:30.109(3)? error: ValidateAuthTokenRespMsg: Error: Match error: Expected string, got undefined

Indicates something like that

**Comment by pedrobmarin** [comment]
> I20210404-18:15:26.654(3)? error: Pads' server unreachable

Means you have some configuration problem within your Etherpad server. Probably an APIKEY mismatch

**Comment by Oasis256** [comment]
Thanks guys for helping out am going to set up v2.3-beta-2
I will close this and re-open if necessary.
Peace!
