### ISSUE TITLE
English key with user name

### ISSUE THREAD

**Issue by ali-alhaidary** [bigbluebutton/bigbluebutton#11882]
**Describe the bug**
In the room user list, sometimes the English key is attached with the user name

**To Reproduce**
1. enter the room'
2. sometimes an English key is attached to the user name

**Expected behavior**
only user name is displayed

**Actual behavior**

**Screenshots**
attached

**BBB version (optional):**
BigBlueButton 2.2.36

**Desktop (please complete the following information):**
 - OS: varies
 - Browser varies
![Screenshot_2021-04-04 almajlis - غرفة درس اللغة العربية](https://user-images.githubusercontent.com/75235623/113557802-431f6300-9607-11eb-8d83-000568dafb1b.png)
![Screenshot_2021-04-04 almajlis - غرفة درس اللغة العربية1](https://user-images.githubusercontent.com/75235623/113557809-44509000-9607-11eb-86ff-d16dcbf2dfb3.png)

**Comment by schrd** [comment]
@ali-alhaidary can you please try to reproduce this on the public 2.3 test server: https://test23.bigbluebutton.org/b

**Comment by ali-alhaidary** [comment]
we are using 2.2.36 not 2.3

Ali

**Comment by schrd** [comment]
> we are using 2.2.36 not 2.3

It would be nice if you could try to reproduce this on 2.3 as the user list implementation has changed a lot in 2.3. BBB 2.2 is near its end of life and 2.3 to be released soon.

**Comment by ali-alhaidary** [comment]
Sure, however, I will need a secret to add it to our moodle please

Ali

**Comment by ali-alhaidary** [comment]
not reproducible in 2.4-rc5
