### ISSUE TITLE
How I can remove or disable leave audio Button 

### ISSUE THREAD

**Issue by haykelbensalha** [bigbluebutton/bigbluebutton#11883]
Hello, 
How i can remove/disable leave audio button from the interface for all users  
![image](https://user-images.githubusercontent.com/36150447/113563144-19fad480-95ff-11eb-981a-82396ae7a1fa.png)

BigBlueButton Server 2.2.30 (2264)

Regards,

**Comment by pedrobmarin** [comment]
Hi @haykelbensalha ,

For those kind of questions, please use https://groups.google.com/forum/#!forum/bigbluebutton-dev
