### ISSUE TITLE
High CPU usage for tailing logs

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#11888]
**Describe the bug**
Very high CPU usage for system tailing logs

![Screenshot from 2021-04-05 09-40-49](https://user-images.githubusercontent.com/6312397/113580278-7f48c880-95f3-11eb-8167-83ef3b21eed7.png)

See last 2 lines ^

The issue appears sporadic. Only happens occassionally. I have seen this for a variety of log related processing - tail for bbb-html5 logs, for akka-apps, for bbb-web too I believe...

This is production env only, no dev env on this server.

**Installation type**
bbb-install script
BigBlueButton alpha*, beta 1,2

**Comment by devZer0** [comment]
are this tail processes still belonging to ca console/terminal  or are that orphaned ones ?

think this is not related to bbb, as tail is completely disjunkt tool from coreutils and this are just 2 ordinary nginx logfiles you are watching

there had been cpu usage bugs in tail in the past  ( for example https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=205251 )  maybe there is some left....

**Comment by antobinary** [comment]
No other open terminals, only one running `htop`. Typically seen for 2-3 BBB processes at a time, and it has huge impact on CPU usage.
I have not noticed this on BBB 2.2. Possibly due to earlier version of Ubuntu. I have not noticed it on non-bbb processes either.

Afaik these tail commands represent the built-in logging for the components, nothing extra installed.

I wonder if this could be related to #11887 even though I only see this issue intermittently.

**Comment by devZer0** [comment]
mhh, i don't see any tail process after starting my bbb 2.3 beta2 instance, so did this change in 2.3 ?

**Comment by ffdixon** [comment]
Closing this issue -- figured out this was from a test server that was running components outside of BigBlueButton.
