### ISSUE TITLE
beta-2 save or copy messages doesn't work

### ISSUE THREAD

**Issue by waesien** [bigbluebutton/bigbluebutton#11894]
Hello,

After upgrading from alpha-8 to beta-2, we cannot save and copy messages in chat.

**Comment by antobinary** [comment]
Hi @waesien 
I just tested v2.3-beta2 and was able to copy, save and clear fine.

Please re-test this against test23.bigbluebutton.ort/demo/demo2.jsp if you are able to reproduce.

What steps did you use to update your server? In the other issue you just opened I see client build 1552 but we released client build 1551 in 2.3-beta2, which raises some suspicion. Please copy-paste the command which you used.

**Comment by waesien** [comment]
I was using alpha-8, I used bbb-install.sh to upgrade to beta-2

It's ok when there is only one user, but save and copy doesn't work when there are 50 people

I don't know what a compile is, I just did a turn install

**Comment by PhMemmel** [comment]
Can't contribute anything to the main discussion, but 1552 is the current deployed html5 client version. 2.3-beta-2 was released with 1551 (I updated pretty much instantly), but after some time (can't quite remember the exact duration) there popped up a new bbb-html5 package in apt repo which was build 1552: 

`dpkg -l bbb-html5`
`ii  bbb-html5      1:2.3.0-1552 amd64        ...`

**Comment by ffdixon** [comment]
A few hours after the release we found it wasn't working with Edge.  This request go merged

  https://github.com/bigbluebutton/bigbluebutton/pull/11868

and I updated the packages so beta-2 could work with Edge.  Normally, we would wait until the next release, but this was a small update to fix a very visible issue.

**Comment by Jossef-767** [comment]
tested on test23.bigbluebutton.org, was able to reproduce on chrome when there is only one user, it is not consistent, sometimes works fine.
![image](https://user-images.githubusercontent.com/2356928/113667147-06ac3f80-96b9-11eb-9800-c8127a68ea06.png)

**Comment by PhMemmel** [comment]
@ffdixon To avoid hijacking this issue, I commented on the 1152 vs 1151 bbb html5 version here: #11901

**Comment by prlanzarin** [comment]
So, I was testing an unrelated thing and found out one variant where Save doesn't work and Copy works in a rather odd way.

1. Populate the chat with a few messages
2. Clear chat

Result:
1. Save doesn't work at all
2. Copy actually copies the whole chat history before the chat clear, which is weird

Seems like we're leaving stuff dangling in the chat when we shouldn't.

Potentially related: https://github.com/bigbluebutton/bigbluebutton/issues/11859, https://github.com/bigbluebutton/bigbluebutton/issues/11878

**Comment by waesien** [comment]
problem still persists in beta-3


![image](https://user-images.githubusercontent.com/81984557/114277709-0901f700-9a35-11eb-9bbb-5d0b44dd340f.png)

**Comment by antobinary** [comment]
Thank you both, the logs you provided should help resolving the issue!
