### ISSUE TITLE
[2.3] a Microsoft Edge browser's client crashes when kicked 

### ISSUE THREAD

**Issue by daminebenq** [bigbluebutton/bigbluebutton#11896]
To reproduce:
1. Connect with 2 users (moderators), **should use Microsoft Edge for the User to be kicked**
2. From User1, kick User2 (the Microsoft Edge user)
3. See result

Result:
Client crashes and gives the console error below.
![image](https://user-images.githubusercontent.com/5144311/113638888-4722a380-964e-11eb-9d60-99dc2912f8a1.png)

Expected behavior:
![image](https://user-images.githubusercontent.com/5144311/113638907-56095600-964e-11eb-86a8-a62ffb7c9933.png)

**Comment by mariogasparoni** [comment]
Hey @daminebenq. 
I am not able to reproduce this one in current HEAD of `develop`
Does it happen for an specific version ? I tested using Microsoft Edge 89.0.774.63 (Windows 64-bits)

**Comment by mariogasparoni** [comment]
Still not able to reproduce in an updated local dev. I also tried the same server i was able to reproduce before, but not the problem is not happening using same OS/Browser version.
It seems this problem happens sporadically.

**Comment by daminebenq** [comment]
Yes, sorry, I tested this yesterday on Browserstack and idk why it gave this error. Closing it for unability to reproduce.
