### ISSUE TITLE
[2.3] Talking indicator highlighting webcam border during webcam connection has a wrong behavior

### ISSUE THREAD

**Issue by daminebenq** [bigbluebutton/bigbluebutton#11902]
To reproduce:
1. Connect using ~MS Edge~ any browser to a bbb 2.3 meeting
2. Connect to audio using microphone
3. Start sharing webcam, and try to do some noise to see your name appearing in the talking indicator bar
4. During the webcam connection status, the talking indicator appears with a wrong behavior

Talking Indicator appears overlayed when the webcam is connecting.
![image](https://user-images.githubusercontent.com/5144311/113719468-05344480-96c4-11eb-81cf-8a88414f6906.png)

**Comment by prlanzarin** [comment]
This is not Microsoft Edge specific. It happens with every major browser.

**Comment by prlanzarin** [comment]
If someone is picking this up I'd suggest altering the desired behavior.
I think it would be better if the talking indicator was displayed in the video container regardless of whether the video has already loaded or not.
