### ISSUE TITLE
2.3 beta2  when muted, cant leave audio

### ISSUE THREAD

**Issue by hostbbb** [bigbluebutton/bigbluebutton#11913]
![image](https://user-images.githubusercontent.com/519542/113784445-747d5900-9703-11eb-9c29-3c3c025f90f2.png)

**Describe the bug**
Try to leave audio when muted, the toast is over the leave option.

**Comment by hostbbb** [comment]
Also blocks the page number of the presentation, so mutes users can see what page number is displayed.

**Comment by mariogasparoni** [comment]
We discussed this internally a bit , and apparently the best solution would be putting the muted banner elsewhere, or make it smaller,  changing the css somehow (suggestions are welcome  :-) )

As a workaround for this problem , we can simply disable the muted banner untill we update the ui (settings.yml in bbb-html5 for those who want to disable it in your own deployment)

**Comment by PhMemmel** [comment]
Possible solution IMHO:

- Let shape/size of the muted banner as it is. It is ok for it to pop over audio menu slide navigation, if:
- Make the banner closeable (little x in the corner to close it), maybe even make it disappear if the user clicks next to it.
- Banner isn't shown again until the user mutes and unmutes himself/herself again.

**Comment by Oasis256** [comment]
Possible Solution
I believe the warning is fair and deserves to be visible just like the comfort noise for when the mic is hot / live
1. Leave the banner as is now
2. Make it click through
3. Fade out or disappear on hover

**Comment by mariogasparoni** [comment]
Thanks for all the suggestions. 
Please, let me break this work in 2 parts. The first one is the simpler, where i just make sure the device list is shown over the muted alert (see #11950).

In the second part (may create a new issue or renamed this one), let's deal with the good suggestions brought here. 
We could add the close button and also preventing showing the muted alert after the close, until user unmute/mute mic again.
