### ISSUE TITLE
404 Not Found nginx 

### ISSUE THREAD

**Issue by Ameni-inova** [bigbluebutton/bigbluebutton#11918]
Hello Guys,

Our bigbluebutton server with greenlight v2 was installed since 2 years and we made interface customisation since 6 months and it works great

Yestarday, the site in not accessible with message 404 not found.

The file /var/log/nginx/error.log show:

https://prnt.sc/116b1qa

I check the configuration file /etc/nginx/sites-enabled/bigbluebutton and I notice that uses use /var/www/bigbluebutton-default as the default site but I thnik it's not our case.
we have folder /var/www/bigbluebutton
https://prnt.sc/116b4m4

docker ps result:
![image](https://user-images.githubusercontent.com/68748065/113844024-5e6ba900-9794-11eb-8167-1878e0b5ec9a.png)

with bbb-conf -check 
one Issue red5 log file not found

Please I need your help to resolve the issue. do you think I must edit the file  /etc/nginx/sites-enabled/bigbluebutton to use /var/www/bigbluebutton ?
if yes must I restart nginx ? I will not loose my branding and custom devlopment if I restart nginx (another devloper tell me this)

Thank you very much for your help

**Comment by basisbit** [comment]
For support requests, please use the [forum / mailing list](https://groups.google.com/forum/#!forum/bigbluebutton-setup). This issue tracker here is only for BBB development related issues. Sorry.
