### ISSUE TITLE
2.3-beta-2: presentator quick access menu not scrollable

### ISSUE THREAD

**Issue by PhMemmel** [bigbluebutton/bigbluebutton#11916]
**Describe the bug**
If a presenter uses lots of presentations (use case: prevent clever students from getting access to other slides than currently shown, https://groups.google.com/g/bigbluebutton-dev/c/ocnUnWWdDuc/m/QK7JaOF6CAAJ) he can't access all presentations via the presenter button (+), because it's not scrollable.

**To Reproduce**
1. Open BBB session
2. Upload lots of presentations
3. Click the (+) button
4. See not scrollable panel

**Expected behavior**
Panel should be scrollable in the case of many presentations

**Actual behavior**
Panel not scrollable

**Screenshots**
![grafik](https://user-images.githubusercontent.com/65113153/113842212-bd302300-9792-11eb-9ae3-d70a7919ea1b.png)

**BBB version (optional):**
2.3-beta-2

**Desktop (please complete the following information):**
 - Win10
 - tested on current Chrome and Firefox

**Comment by ffdixon** [comment]
Opened an issue to change how we are indexing slides on the server (see https://github.com/bigbluebutton/bigbluebutton/issues/11919).

We can see what you are doing here in the work around, and I think the better approach is for us to fix the underlying issue.

For the moment, if you want to use this workaround, you'll need to use the presentation upload dialog to scroll through the list of presentations.

**Comment by PhMemmel** [comment]
I intentionally put this one in a separate issue, because I can imagine additional use cases where many presentations are used (for example wanting to show many pictures, which can be uploaded via drag&drop easily). So making this list scrollable when getting too big would be nice IMHO.
