### ISSUE TITLE
2.3-beta-2: Presentations should be sorted alphabetically

### ISSUE THREAD

**Issue by PhMemmel** [bigbluebutton/bigbluebutton#11917]
**Describe the bug**
Presentations aren't sorted alphabetically. However, in some cases, especially when there are a lot of presentations, it would be nice to have them sorted alphabetically.

**To Reproduce**
1. Open BBB session
2. Upload multiple presentations with drag&drop all at once
3. See random(?) order of presentations after finished upload/conversion

**Expected behavior**
Presentations should be sorted alphabetically by filename

**Actual behavior**
Order of presentations is random. I assume it's sorted by conversion completion time

**Screenshots**
![grafik](https://user-images.githubusercontent.com/65113153/113843477-e43b2480-9793-11eb-8b7b-abd506ece883.png)

**BBB version (optional):**
2.3-beta-2

**Additional context**
For a specific use case see #11916, but there are for sure others as well. Presentation order should also be alphabetically in the presentator quick menu -> (+) button

**Comment by hiroshisuga** [comment]
I guess it is the order of upload completion. Should roughly aligned by the file size.

**Comment by PhMemmel** [comment]
I'm working on a PR...Coming soon hopefully :-)
