### ISSUE TITLE
beta 2.3 I was kicked out of the voice call

### ISSUE THREAD

**Issue by waesien** [bigbluebutton/bigbluebutton#11926]
I was kicked out of a voice conversation in a 60 minute broadcast

This incident happened 4 times

![image](https://user-images.githubusercontent.com/81984557/113888286-e076c480-97ca-11eb-81d0-d6238537502e.png)

and suddenly the empty icon appears at the places I marked with an arrow, then it comes back.

**Comment by prlanzarin** [comment]
We need:
  - exact beta version
  - logs from a session where you can reproduce the problem: /var/log/bbb-apps-akka, /var/log/bbb-fsesl-akka, /var/log/bbb-webrtc-sfu. Send the full logs for the day, do not try to isolate stuff.

**Comment by waesien** [comment]
We use it in the production environment because it has an acceleration feature;

(Web Socket 1002)
