### ISSUE TITLE
bbb-conf doesn't consider turn-stun-servers.xml overlay config

### ISSUE THREAD

**Issue by PhMemmel** [bigbluebutton/bigbluebutton#11929]
**Describe the bug**
Since #11804 (already live in beta2) an overlay config for `turn-stun-servers.xml` in `/etc/bigbluebutton` is possible. However, bbb-conf isn't considering this overlay config yet.

**To Reproduce**
1. Have an overlay config for turn-stun-servers.xml in `/etc/bigbluebutton`
2. Execute `bbb-conf --restart` (for example) or `bbb-conf --check`
3. STUN detection not working or giving wrong results because it's reading default file without considering `/etc/bigbluebutton/turn-stun-servers.xml`

**Expected behavior**
bbb-conf should consider stun server in `/etc/bigbluebutton/turn-stun-servers.xml` instead of stun server in `/usr/share/bbb-web/WEB-INF/classes/spring/turn-stun-servers.xml`, if the file in `/etc/bigbluebutton` exists

**Actual behavior**
bbb-conf is only considering `/usr/share/bbb-web/WEB-INF/classes/spring/turn-stun-servers.xml`

**Comment by antobinary** [comment]
Hi @PhMemmel , thank you for reporting!

Looks like you were the one who did the first pass of this feature. Could you please clarify if you're investigating this and may send in a fix OR you're asking for someone else to lend a hand?

**Comment by PhMemmel** [comment]
I will try to fix this myself and send a PR. If I fail I'll ask for help :-)
