### ISSUE TITLE
Clear / Delete User Status as a moderator doesn't work 

### ISSUE THREAD

**Issue by Strahlemann85** [bigbluebutton/bigbluebutton#11930]
**Describe the bug**
It isn't possible to clear / reset the user status icons as a moderator.

**To Reproduce**
1. Open a meeting
2. Join a second user an set a status
3. try to reset the status as a moderator

**Expected behavior**
All Status Icons go back to the initials of the username.

**Actual behavior**
Nothing happens.

**BBB version (optional):**
BigBlueButton Server 2.3.0-beta-2 (1925)

**Desktop (please complete the following information):**
 - OS: Windows, Mac
 - Browser: Chrome, Safari, Firefox
 - Version all up-to-date

**Comment by antobinary** [comment]
Resolved in 2.3-beta3 via https://github.com/bigbluebutton/bigbluebutton/pull/11910
