### ISSUE TITLE
2.3-beta-2: userdata-bbb_auto_join_audio api call ignored if userdata-bbb_force_listen_only=true

### ISSUE THREAD

**Issue by vasylOstrovskyi** [bigbluebutton/bigbluebutton#11933]
**Describe the bug**
If api join call contains a parameter userdata-bbb_force_listen_only=true, then modal asking for permission to reproduce audio is shown even if userdata-bbb_auto_join_audio=true is set. In particular, this breaks the functionality of bbb-livestreaming application

**To Reproduce**
1. Start a bbb session
2. Configure api mate to join that session listen-only, by adding userdata-bbb_force_listen_only=true.
3. Join the session. A modal asking for permission to play audio is shown - that is OK.
4. Configure api mate adding also userdata-bbb_auto_join_audio=true (optionally also userdata-bbb_skip_check_audio=true)
5. Join the session.

**Expected behavior**
Automatic joining the session in listen-only mode
**Actual behavior**
Modal pops up asking for permission to play audio, userdata-bbb_auto_join_audio=true is ignored

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.4 LTS
 - Browser Chromium
 - Version BBB 2.3 beta-2

**Comment by antobinary** [comment]
Thanks for reporting this @vasylOstrovskyi

**Comment by mtsonline** [comment]
...in the past this only happened for moderators, now it also is the case for attendees. 

please put a note to this issue, when this is fixed:
https://github.com/aau-zid/BigBlueButton-liveStreaming/issues/119#issuecomment-815246046
thanks and cheers

**Comment by ramonlsouza** [comment]
This is actually the [expected behavior](https://developer.mozilla.org/en-US/docs/Web/Media/Autoplay_guide#autoplay_availability)... We need some kind of user interaction before audio autoplay.

**Comment by prlanzarin** [comment]
Yeah, @ramonlsouza is correct. 

The modal prompt only appears (conditionally) if both the tag's autoplay directive and the programatic `play` methods fail, which indicates that the browser's autoplay heuristics triggered. Each browser have their own policies regarding when to fire that error; eg some do not need a gesture IF the user has granted a getUserMedia permission beforehand.

That usually means a `play` action failed with `NotAllowedError`, which means it needs to be bound to an user action. That's exactly what that modal state exists for. As to why it seemingly wasn't happening with beta.1: have no idea why. No changes autoplay related from beta-1 to beta-2. 

The correct approach here is handling it at the streamer's side. Not too deep into the code, but I'll guess it's spawning a headless Chromium(Chrome). AFAIK there's a flag to be passed that deactivates the need for user gestures to handle autoplay (--autoplay-policy=no-user-gesture-required I think?). cc @mtsonline

**Comment by pedrobmarin** [comment]
When I need to run those things in automation I set [--no-user-gesture-required](https://peter.sh/experiments/chromium-command-line-switches/#no-user-gesture-required)

**Comment by mtsonline** [comment]
oh okay, thought this dialogue was triggered by bbb not by the browser - so we will add the flag to the chromium and see if that solves it.
strangely this never happened in 2.2 for attendees and I thought the browser only asks for permission if you want to join with microphone. Never was asked for allowing speakers or audio output at all.
Thanks guys.

**Comment by prlanzarin** [comment]
> strangely this never happened in 2.2 for attendees and I thought the browser only asks for permission if you want to join with microphone. Never was asked for allowing speakers or audio output at all.

Just to clarify something: the browser is not exactly "asking for permission" (as it does with getUserMedia/getDisplayMedia). It's only saying: `I won't play the media stream because that's not coming from an user action, deal with it`. BBB is the one "asking for permission"; the modal is our way of communicating what the browser said and provide a way to replay the media stream directly from an user action (ie the user clicking `Yes`).

**Comment by mtsonline** [comment]
yeah thanks, got that, thats why I used the term "triggered by the browser" of course the dialoge is rendered by bbb. :-)

**Comment by ichdasich** [comment]
Based on https://github.com/aau-zid/BigBlueButton-liveStreaming/issues/119 being closed and resolved using `--autoplay-policy=no-user-gesture-required`, i'd say that this can also be closed.
