### ISSUE TITLE
Add a create (or join) parameters to hide User list and Presentation area

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#11936]
**Is your feature request related to a problem? Please describe.**
To enable creating a default "video chat" layout for a meeting, the client needs to start up with User list and Presentation area hidden by default.

**Describe the solution you'd like**
Add a create (or join) API parameters so that when a user enters the conference

1. The presentation area is minimized. 
2. The User list is minimized.

**Comment by Jossef-767** [comment]
This feature is definitely in demand. I think it would be nice if the lecturer could change to this display mode on the fly, during the lesson.  hiding the presentation display to everyone.
Maybe Simply if no presentation is selected in the presentation upload window, will hide presentation area.

**Comment by pedrobmarin** [comment]
```
userdata-bbb_auto_swap_layout=true
userdata-bbb_show_participants_on_login=false
```

**Comment by pedrobmarin** [comment]
And, for the record, automatic video-chat:
```
userdata-bbb_auto_swap_layout=true
userdata-bbb_show_participants_on_login=false
userdata-bbb_listen_only_mode=false
userdata-bbb_auto_join_audio=true
userdata-bbb_skip_check_audio=true
userdata-bbb_auto_share_webcam=true
userdata-bbb_skip_video_preview=true
```

**Comment by pedrobmarin** [comment]
@ffdixon is the userdata (join parameter) enough for this requirement?

**Comment by antobinary** [comment]
> userdata-bbb_auto_swap_layout=true
> userdata-bbb_show_participants_on_login=false

I don't think we need to do anything else. Closing.

**Comment by pshabanov** [comment]
> And, for the record, automatic video-chat:
> 
> ```
> userdata-bbb_auto_swap_layout=true
> userdata-bbb_show_participants_on_login=false
> userdata-bbb_listen_only_mode=false
> userdata-bbb_auto_join_audio=true
> userdata-bbb_skip_check_audio=true
> userdata-bbb_auto_share_webcam=true
> userdata-bbb_skip_video_preview=true
> ```

In local override file will be better in /etc/bigbluebutton/bbb-html5.yml (if not exsist create and dublicate of original settings.yml on /usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml)

In 2.5 and 2.6 BBB is
autoSwapLayout: true
showParticipantsOnLogin: false
....
And other properties
