### ISSUE TITLE
Textfield and other tools are not movable

### ISSUE THREAD

**Issue by Braehler** [bigbluebutton/bigbluebutton#11937]
**Describe the bug**
The textfield and other tools can not be moved after they are placed into the presentation

**To Reproduce**
1. Go to a room of your choise
2. Upload a presentation or use the standard whiteboard
3. Click on the toolbar and choose for example textfield
4. Add some words into the textfield
5. Now chose the "move" button and try to move the textfield or any other object
6. The field can not be moved

**Expected behavior**
After the texfield or any other tool is placed into the presentation it should be movable, to adjust it to the right place into the presentation,

**Actual behavior**
Currently once the texfield is placed it can not be moved around or changed

**Screenshots**

**BBB version (optional):2.2.36
BigBlueButton continually evolves. Providing the version/build helps us to pinpoint when an issue was introduced.
Example:
$ sudo bbb-conf --check | grep BigBlueButton
BigBlueButton Server 2.2.2 (1816)

**Desktop (please complete the following information):**
 - OS: Windows, Mac
 - Browser: Chrome, FireFox
 - Version: both current stable versions

**Smartphone (please complete the following information):**
 - Browser [e.g. stock browser, Safari]

**Additional context**

**Comment by pedrobmarin** [comment]
Hi @Braehler ,

I believe there is a misunderstanding of the pan tool here. BigBlueButton's annotations cannot be moved. The hand tool moves the entire slide when you zoom-in or use the fit-to-width option.

**Comment by Braehler** [comment]
Hey @pedrobmarin 
thanks, alright, I misunderstood the hand tool ;-). But it would be a great benefit to have the textfield movable

**Comment by pedrobmarin** [comment]
Yeah, it's something a lot of people ask https://github.com/bigbluebutton/bigbluebutton/issues/2351. Just a little complicated to deliver. I'm closing this one since looks resolved and there is already an issue opened for the movable annotations.
