### ISSUE TITLE
2.3 beta 2 all issues

### ISSUE THREAD

**Issue by waesien** [bigbluebutton/bigbluebutton#11952]
Hello,

We were using up to 800 people in BigBlueButton 2.2 version, we did not encounter any problems without scalelite.

I am using it in a manufacturer environment, we have provided tests up to 300 people simultaneously.

I know it's wrong to use this in a producer environment, but our students want the acceleration feature.

I am listing all bugs in version 2.3 beta-2

**1:** **I am encountering the Microsoft edge blue screen error**

![image](https://user-images.githubusercontent.com/81984557/114077824-dfb85e00-98b0-11eb-98dd-caa0595200f7.png)

****2:** Save messages does not work when there are over 50 users**

![image](https://user-images.githubusercontent.com/81984557/114078222-581f1f00-98b1-11eb-8de5-495855d4f134.png)

**3: Our most important problem**

No problem if the student joins by voice.

But when she only attends as a listener, she encounters this situation 3-4 times during the lesson. 

There is a problem with those who participate as listeners

**So if the teacher talks like :** ADKASDJNKASJNDASD
**Voice participants hear this way:** ADKASDJNKASJNDASD
**Only listeners hear this way:** ADKASDJNKA...........................

It gives a web socket notification on mobile, but it does not appear on the desktop.

![image](https://user-images.githubusercontent.com/81984557/114078730-f612e980-98b1-11eb-8c20-0c01b082389d.png)

**Comment by waesien** [comment]
![image](https://user-images.githubusercontent.com/81984557/114080630-47bc7380-98b4-11eb-9581-542611fe52b7.png)
![image](https://user-images.githubusercontent.com/81984557/114080641-4ab76400-98b4-11eb-86ee-9ab90b22a36b.png)
![image](https://user-images.githubusercontent.com/81984557/114080654-4d19be00-98b4-11eb-810e-e48e9ffa9117.png)
![image](https://user-images.githubusercontent.com/81984557/114080665-4f7c1800-98b4-11eb-96b5-6730070edbd5.png)

**Comment by basisbit** [comment]
For support requests, please use the [forum / mailing list](https://groups.google.com/forum/#!forum/bigbluebutton-setup). This issue tracker here is only for BBB development related issues. Sorry.

Please stick to the issue tracker template and actually fill it in.

Please create one issue per problem and not one with all of your stuff, which makes it impossible for developers of the community to track work and focus on the issue. Please use the search to first find other issues which already were reported.

**Comment by basisbit** [comment]
Your websocket problem is probably just a not properly configured coturn or you are using an old version of coturn or your IPv4/IPv6 setup is broken. Please follow https://docs.bigbluebutton.org/2.2/setup-turn-server.html

**Comment by waesien** [comment]
> For support requests, please use the [forum / mailing list](https://groups.google.com/forum/#!forum/bigbluebutton-setup). This issue tracker here is only for BBB development related issues. Sorry.
> 
> Please stick to the issue tracker template and actually fill it in.
> 
> Please create one issue per problem and not one with all of your stuff, which makes it impossible for developers of the community to track work and focus on the issue. Please use the search to first find other issues which already were reported.

Thank you
