### ISSUE TITLE
BBB-Etherpad / Shared Notes needs detailed logging

### ISSUE THREAD

**Issue by Rhywden** [bigbluebutton/bigbluebutton#11959]
**Is your feature request related to a problem? Please describe.**
This just cropped up. We have a BBB installation wherein our pupils have access to the BBB server. They're authenticated against our LDAP so anonymous access is not a problem.
What we just found out, however, is that it is possible to write into the shared notes without anyone knowing who wrote what.

With some pupils being what they are, this is ... somewhat problematic as it may result in abusive behaviour.

I've already tried `grep`ping the existing logs but they don't seem to have this level of information. Also tried to trawl the Redis db but that's a non-starter as well. I've also been unable to discover how to set the log level for etherpad to the level I need.

**Describe the solution you'd like**
A setting which logs precisely who wrote what in the etherpad instance

**Describe alternatives you've considered**
a setting to disable etherpad altogether - whether that's server-wide or for specific rooms.

**Comment by pedrobmarin** [comment]
Hi @Rhywden ,

We understand that when dealing with kids (and some adults) the shared notes can become that sort of an issue. For those scenarios I recommend you just to lock the access of that feature. We have a soft integration with Etherpad that is not fully reliable on telling who did what, or not in an easy way that admins would get comfortable doing.

The shared notes can be disabled server-wide at the client's settings file: https://github.com/bigbluebutton/bigbluebutton/blob/598dcb7751e379498aa06cf698fabc32768bf744/bigbluebutton-html5/private/config/settings.yml#L388-L390 or for the viewers in distinct meetings using the lock settings, both from inside the running meeting or as a create parameter: https://github.com/bigbluebutton/bigbluebutton/blob/598dcb7751e379498aa06cf698fabc32768bf744/bigbluebutton-web/grails-app/conf/bigbluebutton.properties#L348-L357

**Comment by Rhywden** [comment]
Okay, I'll talk the "nuclear option" over with my team.
In the meantime, I found a workaround of sorts - basically, in case something like this happens you can simply download the Etherpad file. And then, using a "proper" Etherpad client you can see who wrote what through the rewind feature.

This, of course, is only possible as long as the meeting is still active. Maybe this could be something to add to the documentation?

**Comment by pedrobmarin** [comment]
BigBlueButton will archive the `.etherpad` file for you at the end of the meeting if the meeting was recordable. You can check that at your recordings raws.

**Comment by Rhywden** [comment]
Ah. We already killed the recording feature for GDPR reasons...

**Comment by ArmanEsf** [comment]
Hi @Rhywden and @pedrobmarin ,
I've ran into this problem recently and it's bad since someone from the class is typing worse things in the shared notes a I've no clue who's doing that! can u tell me the name of that Etherpad client you used to read those .etherpad files?
and Pedro since I've recording enabled the path to the etherpad files is `/var/bigbluebutton/recordings/raw/INTERNAL_MEETING_ID/notes` am I right?

Thanks in advance.

**Comment by pedrobmarin** [comment]
Hi @ArmanEsf ,
Yes, that's the correct path. As far as I know, you can use any Etherpad client that allows file import. You can also open it in a text editor and match the author id with the change you're interested.

**Comment by ArmanEsf** [comment]
Thanks @pedrobmarin ,
That's right Pedro I finally figured it out and used the original Etherpad itself downloaded from [here](https://etherpad.org/#download) and then import the `notes.etherpad` file that I could found them all with this command (may help others) :
`find /var/bigbluebutton/recording/raw/* -name "notes.etherpad"`
BTW the Etherpad runs a web client on `0.0.0.0:9001` and it has a really cool Timeslider feature that shows every character that every author typed or deleted!
