### ISSUE TITLE
playback of youtube videos not always synchronized between participants

### ISSUE THREAD

**Issue by szekster** [bigbluebutton/bigbluebutton#11969]
**Describe the bug**
more often than not sharing a video (eg youtube) will not start and stop playback on all connected clients at the same time, forcing each participant to start / stop manually,

**To Reproduce**
1. start a meeting and connect several participants.
2. share any youtube video
3. start playback
4. note if all connected participants also start playback.
5. repeat for stop playback

**Expected behavior**
All participants should start or stop playback in sync with the presenter control

**Actual behavior**
sometimes it works, other times it does not.   if it works then it seems to work across all connected participants.  if it fails then all participants fail to start or pause video. (ie. i have not seen a case where some participants are in sync and some are not)

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome, Firefox, Edge
 - Version : latest

**Smartphone (please complete the following information):**
 - Device: not used in test.
 - Browser [e.g. stock browser, Safari]

**Additional context**

**Comment by basisbit** [comment]
Which version of BigBlueButton do you use? Can you reproduce the problem at https://test23.bigbluebutton.org/ ?

**Comment by szekster** [comment]
shouldn't mentioned it.  it's on 2.3 dev alpha7.  i figured it was a bug in the dev version but just wanted to make you aware of it.

**Comment by ffdixon** [comment]
We would be interested to hear if your experience is better in 2.4.

**Comment by szekster** [comment]
no issues in 2.4 to my knowledge.

**Comment by invokablegmbh** [comment]
Yes. We aswell have no more problems with external video sync in 2.4.
