### ISSUE TITLE
2.3 beta-2 Blue screen appears after survey is sent

### ISSUE THREAD

**Issue by waesien** [bigbluebutton/bigbluebutton#11968]
You can only poll when there is one user, but there were 58 people, we polled twice and a blue screen came out.

**Comment by antobinary** [comment]
Hi @waesien 
Any chance you could copy-paste the browser console lines when the blue screen came out?

**Comment by waesien** [comment]
I updated the beta-3 and I will check it after testing

**Comment by tibroc** [comment]
I can confirm this issue for beta-3 on at least two different instances with meetings with ~50 and ~170 participants, respectively.

**Comment by antobinary** [comment]
Reproduced locally with @ramonlsouza 
Steps:
1. Join as moderator M
2. Join as viewer V
3. M starts polling
4. V sees the poll and refreshes client (not voting)
