### ISSUE TITLE
Textfield and other tools/ annotations should come with the downloaded presentation

### ISSUE THREAD

**Issue by Braehler** [bigbluebutton/bigbluebutton#11960]
**Is your feature request related to a problem? Please describe.**
When you as a moderator add some tools like textfield on the presentation (no matter default are your own presentation) the textdield is not visible after the viewer downloaded the presentation to his computer

**Describe the solution you'd like**
Every change on the presentation should be included to the download file. Like text marked in color, or extra annotations in textfields etc

**Describe alternatives you've considered**
The only alternativ I currently know, is to add everything again to the presentation on the moderators computer (original presentation) and then send it to the viewers by email or cloud link

**Additional context**

**Comment by pedrobmarin** [comment]
Hi @Braehler , I'll merge this issue with https://github.com/bigbluebutton/bigbluebutton/issues/4882 to better keep track of this.
