### ISSUE TITLE
The settings icon in the user list disappears after joining a breakout room audio

### ISSUE THREAD

**Issue by GhaziTriki** [bigbluebutton/bigbluebutton#11977]
**Describe the bug**
When a moderator created breakout room then join the audio of any breakout room, the setting menu disappears from the users menu.

**To Reproduce**
1. Join audio.
2. Create breakout rooms.
3. Join the audio of any breakout room.

**Expected behavior**
The settings icon in the users list should not disappear.

**Actual behavior**
The settings icon in the users list disappear.

**Screenshots**
![image](https://user-images.githubusercontent.com/4991088/114264582-a59ba900-99e3-11eb-965a-eb3341dd72ca.png)

**BBB version (optional):**
2.3.alpha3

**Desktop (please complete the following information):**
 - OS: Windows 10 20H2
 - Browser: Firefox
 - Version: 87.0 (64 bits)

**Comment by PhMemmel** [comment]
Can confirm on 2.3-beta3. No error in browser console. There is no way to recover the settings icon except reloading the site.

Tested on current FF and Chrome.

**Comment by PhMemmel** [comment]
Just realized this is probably related to a role problem. After starting audio I can't end the session anymore despite being moderator. Only "Leave session" is available. I can't see the moderator only message in public chat either. I can't kick attendees anymore etc.

Apparently the "join audio" of breakout room switches my current role to "attendee" in the main room context. Only my icon stays "squared", but I don't have moderator access to the session anymore.
