### ISSUE TITLE
Shared notes export / import icon, not using download icon (2.3-beta2)

### ISSUE THREAD

**Issue by galupa** [bigbluebutton/bigbluebutton#11974]
**Describe the bug**
The export / import icon on shared notes, is not using the download icon.
It is using the old icon just as described on https://github.com/bigbluebutton/bigbluebutton/issues/7054

**To Reproduce**
1. Click shared notes to open shared notes pane
2. See the export / import icon (screenshot)

**Expected behavior**
The icon should be download icon, just as https://github.com/bigbluebutton/bigbluebutton/issues/7054

**Actual behavior**
It using the old icon (see screenshot)

**Screenshots**
![Screenshot from 2021-04-10 18-32-27](https://user-images.githubusercontent.com/29434066/114260842-5aa58400-9a2b-11eb-9b27-fb720aa82c18.png)

**BBB version (optional):**
2.3-beta2

**Comment by mrkeksi** [comment]
Also in Beta 3. but is this the right issue u are linked? I don't see any connection.

**Comment by galupa** [comment]
Oops, you are right, I put the wrong link there, I edited it now.
Thanks for checking

**Comment by pedrobmarin** [comment]
It's because we now run Etherpad-latest direct from the official repository. I'll move this request to the repository we keep the skin theme for BigBlueButton to check what we can do about it.

**Comment by steffen-moser** [comment]
It would be really nice to get both, the text and the icon changed to an "export only" semantics. When doing tests with BigBlueButton 2.3-RC2 today, users got really eager in importing pre-formatted shared notes. When they learned that this does not seem to be possible, they were slightly disappointed.

**Comment by pedrobmarin** [comment]
I'd rather allow importing files than going through that customization again. Not sure why it was removed... @antobinary have any idea?
