### ISSUE TITLE
Firefox not showing speakers

### ISSUE THREAD

**Issue by PhMemmel** [bigbluebutton/bigbluebutton#11978]
**Describe the bug**
Firefox isn't offering speaker devices.

**To Reproduce**
1. Join Session
2. Join FS or kurento audio
3. Hit phone/headphone icon/button
4. See screenshot below: No output devices shown

**Expected behavior**
Firefox should offer different output devices.

**Actual behavior**
Doesn't offer any device.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/65113153/114267339-2ca84b80-99fb-11eb-80b5-535675526d22.png)

**BBB version (optional):**
2.3-beta3

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser: Firefox 87.0 64bit

**Additional context**
Not sure, if this problem can be solved on BBB side. I tried turning off FF privacy mode as well, didn't help. Would it at least be possible to change the label to "default device" or don't show speakers section at all when there is no device? The message "no device found" is at least confusing for users, it possibly makes them think there is something wrong in their sound setup which in fact isn't.

Possibly related to #11849 and #11813, but couldn't figure out if this issue has already been tried to address in these PRs.

**Comment by mariogasparoni** [comment]
Firefox by default won't allow you to retrieve information about output devices, unless you explicitly enable it in `about:config`  by setting the following config to true:
```
media.setSinkId.enabled
```

**Comment by PhMemmel** [comment]
Thank you for that information. I suspected something like that. Would it be possible to display a more accurate message or remove the speaker selection section completely in that case?

**Comment by mariogasparoni** [comment]
I think so, we already programmatically test the availability of `setSinkId` before trying to set output devices. Shouldn't be hard hide some parts of the GUI based on that.

I might update the docs with some information about browsers and the device selector (including this one related to firefox)

**Comment by mariogasparoni** [comment]
@PhMemmel feel free to close this issue, once it is now clear how to proceed with firefox.

**Comment by PhMemmel** [comment]
@mariogasparoni So you don't see the neccessarity to implement a more clarifying message or should this be tracked by a separate issue?

**Comment by mariogasparoni** [comment]
I think we can treat it separatedly

**Comment by PhMemmel** [comment]
Alright, thank you very much. I will open it as separate issue when I can provide a PR closing it as well ;-)
