### ISSUE TITLE
[2.3] 2 Upload areas?

### ISSUE THREAD

**Issue by mrkeksi** [bigbluebutton/bigbluebutton#11976]
**To Reproduce**
Open manage presentations 

**Expected behavior**
Only one upload area. 

**Actual behavior**

two fields with different text but the same behavior are available

**Screenshots**
![image](https://user-images.githubusercontent.com/8763656/114261157-68cab480-99d9-11eb-9ff2-2c7c05b74fb9.png)

BBB version (optional):
2.3 beta 3(1588)

Smartphone (please complete the following information):

Device: iPhone 12 mini
OS: iOS 14.5 beta
Browser Safari

**Comment by schrd** [comment]
I can reproduce this on Firefox for Android 87 and Chrome for Android 89
