### ISSUE TITLE
Network quality visual indicator not fully dislaying (2.3-beta-3)

### ISSUE THREAD

**Issue by GhaziTriki** [bigbluebutton/bigbluebutton#11970]
![image](https://user-images.githubusercontent.com/4991088/114238695-f6c48200-997c-11eb-87af-f8f6d5c3119b.png)

Tested on FireFox 87.0 (64 bits) Windows 10

**Comment by antobinary** [comment]
Hi @GhaziTriki
Please fill out the issue template, what device is this / os / browser type
Looks like RTL is enabled, 2.3-beta2+

**Comment by GhaziTriki** [comment]
It seems like all the circle button have that issue when we click on them.

![image](https://user-images.githubusercontent.com/4991088/114264423-cfa09b80-99e2-11eb-9efa-a5ed934f5cd9.png)

**Comment by pedrobmarin** [comment]
This looks like the `outline` style from buttons. It can be disabled
