### ISSUE TITLE
Resize the presentation when a video is open too small and not releasing the action (2.3-beta-3)

### ISSUE THREAD

**Issue by GhaziTriki** [bigbluebutton/bigbluebutton#11971]
When the presentation area is resized, the size can go to 0 px. And when the mouse is not released, switch the tab then get back the client tab, you can still resized the windows while moving your mouse.

Tested on FireFox 87.0 (64 bits) Windows 10

**Comment by PlumedArcher** [comment]
Also reproducible with Google Chrome on Windows 10 and BBB 2.3 beta 3.
Similiar to #7991, may have the same root.

**Comment by antobinary** [comment]
Likely handled in https://github.com/bigbluebutton/bigbluebutton/pull/12394
