### ISSUE TITLE
Resizing closed caption editor makes video layout a bit messy (2.3-beta2)

### ISSUE THREAD

**Issue by galupa** [bigbluebutton/bigbluebutton#11975]
**Describe the bug**
Resizing closed caption window makes the video layout a bit messy.

**To Reproduce**
1. Click manage user to open menu
2. Click on 'write closed caption'
3. Choose language and click start
4. After closed caption window opened, resize the closed caption window (slide right and left)
5. See video layout (example on screenshot). All video and presentation will eventually gone, if you keep resizing
6. User can restore the video layout by open chat window or others (shared notes, etc).

**Expected behavior**
Resizing closed caption window should not make video layout messy.

**Actual behavior**
Resizing closed caption window seems to minimize all video which eventually make them gone.

**Screenshots**
![Screenshot from 2021-04-10 18-37-33](https://user-images.githubusercontent.com/29434066/114261139-1f0bb980-9a2d-11eb-9c30-0da5fdeedc1c.png)

**BBB version (optional):**
BBB 2.3-beta2

**Comment by pedrobmarin** [comment]
We could have a common panel component the be used as a wrapper to all panels and implement all those trigger events.
