### ISSUE TITLE
 error: [mcs-media] Failed to run underlying _connect procedure due to MEDIA_NOT_FOUND

### ISSUE THREAD

**Issue by Aaomt** [bigbluebutton/bigbluebutton#11982]
BigBlueButton Server 2.3.0-beta-3 (1975)
When the connection is made, the following error is received

/var/log/syslog
 `Apr 10 19:09:45 vd30 bbb-webrtc-sfu[2201]: 2021-04-10T16:09:45.589Z - error: [mcs-media] Failed to run underlying _connect procedure due to MEDIA_NOT_FOUND sourceId=little-shape-zNlPDZq, sourceAdapterElementId=withered-feather-yGgV51b, sinkId=hidden-wildflower-QdHFrTV, sinkAdapterElementId=a6b2fd26-8a58-47f6-b325-eb53fda5b481_kurento.MediaPipeline/1368b341-fc03-41ae-a843-e87d548f2b14_kurento.RtpEndpoint/misty-snowflake-cw1XBKy, connectionType=AUDIO, code=2201, message=MEDIA_NOT_FOUND`

/var/log/bbb-webrtc-sfu/bbb-webrtc-sfu.log
`{"sourceId":"little-shape-zNlPDZq","sourceAdapterElementId":"withered-feather-yGgV51b","sinkId":"hidden-wildflower-QdHFrTV","sinkAdapterElementId":"a6b2fd26-8a58-47f6-b325-eb53fda5b481_kurento.MediaPipeline/1368b341-fc03-41ae-a843-e87d548f2b14_kurento.RtpEndpoint/misty-snowflake-cw1XBKy","connectionType":"AUDIO","error":{"code":2201,"message":"MEDIA_NOT_FOUND"},"level":"error","message":"[mcs-media] Failed to run underlying _connect procedure due to MEDIA_NOT_FOUND","timestamp":"2021-04-10T16:09:45.590Z"}`

/var/log/kurento-media-server/2021-04-10T183144.00000.pid1430.log
`2021-04-10T19:09:45,545226 1416 0x00007f94fbe62700 warning sdpmidext                 kmssdpmidext.c:134 kms_sdp_mid_ext_add_answer_attributes() <KmsSdpMidExt@0x7f94c8009840>  Remote agent does not support groups`

When I search for kurento error. 
I found this
https://github.com/Kurento/kms-core/blob/master/src/gst-plugins/commons/sdpagent/kmssdpmidext.c   on the page

  mid = gst_sdp_media_get_attribute_val (offer, MID_ATTR);
  if (mid == NULL) {
    GST_WARNING_OBJECT (ext, "Remote agent does not support groups");
    return TRUE;
  }

I'm waiting for your help.

**Comment by prlanzarin** [comment]
None of those log entries are actual errors.
