### ISSUE TITLE
[2.3 beta-3] Switching from LTR and RTL or vice-versa gives a wrong behavior with resizing chat and userlist panels

### ISSUE THREAD

**Issue by daminebenq** [bigbluebutton/bigbluebutton#11983]
To reproduce:
1. Connect with atleast 1 User to a bbb 2.3 beta 3 meeting
2. Switch from LTR to RTL or vice-versa
3. Try to resize Chat and Userlist panels
4. See result..

Current behavior:

https://user-images.githubusercontent.com/5144311/114278858-1e146100-9a08-11eb-99cd-f2b8b65c6e49.mp4

**Comment by antobinary** [comment]
Possibly addressed in https://github.com/bigbluebutton/bigbluebutton/pull/12394

**Comment by ramonlsouza** [comment]
this issue is no longer reproducible, and can be closed (tested in 2.3 and 2.4)
