### ISSUE TITLE
2.3 beta 3 Page not responding error and icons are broken

### ISSUE THREAD

**Issue by waesien** [bigbluebutton/bigbluebutton#11980]
![image](https://user-images.githubusercontent.com/81984557/114276221-5e86d580-9a2e-11eb-823d-c76c81c5295a.png)
![WhatsApp Image 2021-04-10 at 14 35 37](https://user-images.githubusercontent.com/81984557/114276246-73636900-9a2e-11eb-9633-0d9a7942c274.jpeg)

the icons are broken but getting better later

the page has not responding error bigbluebutton freezes

**Comment by waesien** [comment]
![image](https://user-images.githubusercontent.com/81984557/114278105-c93c0f00-9a36-11eb-9a04-e81e8e95c745.png)

**Comment by waesien** [comment]
![image](https://user-images.githubusercontent.com/81984557/114428390-cd963280-9bc4-11eb-8600-9009a3ba7c88.png)

Freezing problem occurs after joining the meeting

Page loading depends on the number of users, for example, icons fix in 10 seconds for 134 users and freeze problem is eliminated

There is no such problem in single user or 5 users

For users with broken computers, the page does not open chrome sends a warning, exit the page or wait option

I upgraded from beta-2 to beta-3, I updated it with the bbb-install.sh command without any installation.This problem occurred.

**Comment by daminebenq** [comment]
Hi !

> For users with broken computers, the page does not open chrome sends a warning, exit the page or wait option

I would like to reproduce this, so can you please give us more details ? So I will need an example of a **broken computer** setup, RAM, CPU and browser version.

**PS:** I'm gonna create a windows session under virtual box and test the described issue using it.

**Comment by waesien** [comment]
> Selam !
> 
> > Bilgisayarları bozuk olan kullanıcılar için sayfa açılmıyor krom bir uyarı gönderir, sayfadan çık veya bekleme seçeneği
> 
> Bunu çoğaltmak istiyorum, lütfen bize daha fazla ayrıntı verebilir misiniz? Bu yüzden **bozuk bir bilgisayar** kurulumu, RAM, CPU ve tarayıcı sürümü örneğine ihtiyacım olacak .
> 
> **Not:** Sanal kutu altında bir Windows oturumu oluşturacağım ve anlatılan sorunu kullanarak test edeceğim.

Users with low computer specs cannot connect at all, the page freezes and chrome sends a warning

Not broken sorry google translate error.

**Comment by daminebenq** [comment]
Hi @waesien 
no problems. I totally understood you. Alright, thanks for the reply. gonna try the described pc specs.
I will comment here with details after tests.
Thanks so much for reporting this.

**Comment by waesien** [comment]
> Merhaba @waesien
> sorun yok. Seni tamamen anladım Pekala, cevap için teşekkürler. açıklanan bilgisayar özelliklerini deneyeceğim.
> Burada testlerden sonra detaylarla yorum yapacağım.
> Bunu bildirdiğiniz için çok teşekkürler.

I'll send a video now

**Comment by waesien** [comment]
> Hi @waesien
> no problems. I totally understood you. Alright, thanks for the reply. gonna try the described pc specs.
> I will comment here with details after tests.
> Thanks so much for reporting this.

https://www.loom.com/share/371b61d844754c2ab26ad976db2f5388

Opened in 19 seconds

**Comment by antobinary** [comment]
@waesien please show a screenshot of the Chrome Task Manager (Shift + Esc)
Also, if you hide the userlist the performance should be slightly better.

**Comment by waesien** [comment]
Many students reported this problem

Lesson finished I cannot show the Chrome task manager

I did not encounter such a problem in Beta 2 without hiding the user list, I need to take immediate action immediately.

I use it in a producer environment because it has the acceleration feature, otherwise I would use 2.2.

This is our only problem right now. Edge problem solved with Beta-3, survey problem continues

I'm not testing as a single user, I'm testing with at least 100 users at the same time.

**Comment by waesien** [comment]
> @waesien please show a screenshot of the Chrome Task Manager (Shift + Esc)
> Also, if you hide the userlist the performance should be slightly better.

![image](https://user-images.githubusercontent.com/81984557/114577808-0564af00-9c85-11eb-94cd-711e8786bd4e.png)

**Comment by waesien** [comment]
@antobinary If you want, you can test the broadcast information, and I can send a log record,

**Comment by waesien** [comment]
This issue is also present here at https://test23.bigbluebutton.org/
