### ISSUE TITLE
Bug of individual access to the whiteboard

### ISSUE THREAD

**Issue by GyR4uk** [bigbluebutton/bigbluebutton#11988]
The function of providing individual access to the whiteboard disappears.

This error was traced in all versions, only now I managed to repeat it.

How to repeat the error:
1) Start the room
2) Attach participants
3) Check that individual access is working
4) Upload the presentation
5) Try to give individual access

https://user-images.githubusercontent.com/35705596/114314446-551b6d00-9b03-11eb-8467-b69777d7b992.mp4

**Comment by pedrobmarin** [comment]
Hi @GyR4uk , thanks for the report.

I was able to reproduce in a similar way. It looks like the user list is missing some data update.
