### ISSUE TITLE
nevermind, sometimes it is time to stop commiting to a toxic, stupid community

### ISSUE THREAD

**Issue by lonesomewalker** [bigbluebutton/bigbluebutton#11984]
Installing BBB 2.3 beta 3, modifying the config for using STUN at 443 TCP instead of 3478 gives the following error:

```
# Warning: Failed to verify STUN server at  3478 with command
#
#    stunclient --mode full --localport 30000  3478
```

This is somewhat problematic, because not always port 3478 is possible.
Don't know if this is an issue with the config (BBB server is running fine), but this error is somewhat irritating.

**Comment by PhMemmel** [comment]
You can't use STUN on 443 TCP, because STUN is always UDP. If you are talking about TURN server, you can do that, but that's not what this warning is about.

Where exactly do you have inserted your STUN/TURN server information? The message you are seeing is probably referring to the entry with id "stun0" in `/usr/share/bbb-web/WEB-INF/classes/spring/turn-stun-servers.xml`. You most likely have entered your stun/turn server hostname there without any specific port, so the default STUN UDP port is being used.

**Comment by prlanzarin** [comment]
My 2ct is that the configuration warning is not really necessary, although I get why it was included.

Setting a STUN server is not mandatory, and 3478 is the default port, but not mandatory to be that as well (it can be any UDP port other than the slipstream-filtered ones). Adding a check that supposes those two conditions are true is bound to render false positives (which is the case here, one way or another).

It's not a breaking issue. But it's a warning that's not fail safe.

**Comment by lonesomewalker** [comment]
Funny is, i did it with BBB 2.2 and no issues?

**Comment by prlanzarin** [comment]
It's good to have a warning, though. As I said, I get why it was added: people were setting borked STUN servers (ie public deprecated STUN servers) and didn't pay attention to it. Which is fine, the whole technological stack involved is a hellscape. So the warning helps operators to detect if anything is messed up.

So I'd suggest making the warning work upon the turn-stun-servers config:
  - if a stun bean is set, fetch the configured values (which includes the full URL + (port|3478))
  - run the test with the values retrieved from the previous step

**Comment by PhMemmel** [comment]
@lonesomewalker what is your point?

**Comment by lonesomewalker** [comment]
This would be a good solution :-)
We configure several STUN/STUNS and TURN/TURNS servers, and all of them are available.
So we got this error the first time, tried the session, worked.

I just opened this ticket so that others don't get stuck by re-checking their servers for nothing wrong :-)

**Comment by lonesomewalker** [comment]
> @lonesomewalker what is your point?

As written: sometimes i wish there were more professionals (like @prlanzarin i.e.)

Your comment was somewhat useless and also wrong.

**Comment by prlanzarin** [comment]
https://github.com/bigbluebutton/bigbluebutton/blob/develop/bigbluebutton-config/bin/bbb-conf#L1248-L1264

Hmm, the check already does most of what I suggested (it includes the port fetching as well), so what I said is useless. It doesn't do multiple STUN beans, but that's minor. So I don't know why it's running a check of 3478 if you have a bean set with a explicitly specified port.

Can you please paste a redacted version of your STUN beans @lonesomewalker ?

**Comment by lonesomewalker** [comment]
Sure, same config working on 2.2:

```
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://www.springframework.org/schema/beans
        http://www.springframework.org/schema/beans/spring-beans-2.5.xsd">

    <bean id="stun0" class="org.bigbluebutton.web.services.turn.StunServer">
        <constructor-arg index="0" value="stun:server1.stunserver.tld:443?transport=tcp"/>
    </bean>
    <bean id="stun1" class="org.bigbluebutton.web.services.turn.StunServer">
        <constructor-arg index="0" value="stun:server2.stunserver.tld:443?transport=tcp"/>
    </bean>


    <bean id="turn0" class="org.bigbluebutton.web.services.turn.TurnServer">
        <constructor-arg index="0" value="pass"/>
        <constructor-arg index="1" value="turn:server1.turnserver.tld:443?transport=tcp"/>
        <constructor-arg index="2" value="86400"/>
    </bean>
    
    <bean id="turn1" class="org.bigbluebutton.web.services.turn.TurnServer">
        <constructor-arg index="0" value="pass"/>
        <constructor-arg index="1" value="turns:server2.turnserver.tld:443?transport=tcp"/>
        <constructor-arg index="2" value="86400"/>
    </bean>

    <bean id="stunTurnService"
            class="org.bigbluebutton.web.services.turn.StunTurnService">
        <property name="stunServers">
            <set>
                <ref bean="stun0"/>
                <ref bean="stun1"/>
            </set>
        </property>
        <property name="turnServers">
            <set>
                <ref bean="turn0"/>
                <ref bean="turn1"/>
            </set>
        </property>
    </bean>
</beans>
```

**Comment by PhMemmel** [comment]
@lonesomewalker Alright. So you open an issue, don't fill out the template, don't provide exact information on what exactly you configured and then blame me for trying to help clarify the problem? Good job on that, very "professional".

And BTW: I happened to look at the bbb-conf script recently because I added the overlay turn config option to it and realized that it is picking the corresponding port out of the bean configuration. So if you have 3478 reported in the bbb-conf script you probably have some weird configuration where this didn't happen. That's why I answered to your post. But there isn't any reason at all to disrespect random people you don't know on a public platform trying to help you.

**Comment by waesien** [comment]
> https://github.com/bigbluebutton/bigbluebutton/blob/develop/bigbluebutton-config/bin/bbb-conf#L1248-L1264
> 
> Hmm, kontrol önerdiğim şeyin çoğunu zaten yapıyor (bağlantı noktası getirmeyi de içeriyor), bu yüzden söylediklerim yanlış. Birden fazla STUN fasulyesi yapmaz, ancak bu önemsizdir. Bu yüzden, açıkça belirlenmiş bir bağlantı noktasına sahip bir fasulye setiniz varsa neden 3478'lik bir kontrol çalıştırdığını bilmiyorum.
> 
> Lütfen STUN çekirdeklerinizin düzeltilmiş bir versiyonunu yapıştırabilir misiniz @lonesomewalker ?

<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://www.springframework.org/schema/beans
        http://www.springframework.org/schema/beans/spring-beans-2.5.xsd">

    <bean id="stun0" class="org.bigbluebutton.web.services.turn.StunServer">
        <constructor-arg index="0" value="stun:turn.site.net"/>
    </bean>


    <bean id="turn0" class="org.bigbluebutton.web.services.turn.TurnServer">
        <constructor-arg index="0" value="a87f5b02ceafa5900668f2783d75b8ad"/>
        <constructor-arg index="1" value="turns:turn.site.net:443?transport=tcp"/>
        <constructor-arg index="2" value="86400"/>
    </bean>
    
    <bean id="turn1" class="org.bigbluebutton.web.services.turn.TurnServer">
        <constructor-arg index="0" value="a87f5b02ceafa5900668f2783d75b8ad"/>
        <constructor-arg index="1" value="turn:turn.site.net:443?transport=tcp"/>
        <constructor-arg index="2" value="86400"/>
    </bean>

    <bean id="stunTurnService"
            class="org.bigbluebutton.web.services.turn.StunTurnService">
        <property name="stunServers">
            <set>
                <ref bean="stun0"/>
            </set>
        </property>
        <property name="turnServers">
            <set>
                <ref bean="turn0"/>
                <ref bean="turn1"/>
            </set>
        </property>
    </bean>
</beans>

Do you think it is configured correctly?

**Comment by lonesomewalker** [comment]
@PhMemmel the thing is: the title of this issue says ALL.
It is BBB 2.3, and it is a STUN error message.
If you read the first line, you see BBB 2.3 beta 3, and it is well described.

So what do you want more?

And as you should be aware, we run more than 20k instances of BBB worldwide, i am somewhat active on Github (if you just click on my nickname, there should be enough to see that i am not to stupid to set up a BBB nor STUN/TURN server).

So, SORRY for saying you are wrong when you write STUN IS ALWAYS UDP.
This is clearly wrong, misleading, and you should feel ashamed for posting this on Github.

**Comment by PhMemmel** [comment]
And having a look at your config: I don't think your STUN setup is working, trying to get srflx candidates from a public (and also my own) STUN/TURN server via https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/ fails when I try to use "?transport=tcp", because AFAIK (if I'm wrong, I'm happy to learn, please enlighten me) the address lookup itself is done via UDP which is - again AFAIK - the purpose of the stun bean.

**Comment by lonesomewalker** [comment]
@PhMemmel time to learn... there are so many funny things...
