### ISSUE TITLE
2.3-beta-3: Disabling private chat also disables public chat

### ISSUE THREAD

**Issue by PhMemmel** [bigbluebutton/bigbluebutton#11986]
**Describe the bug**
Disabling private chat also disables public chat

**To Reproduce**
1. Open session
2. As moderator click on user list gear and click on "Lock viewers"
3. Set "private chat" to "locked"
4. Attendees in session which are locked can't write into public chat anymore

**Expected behavior**
Only private chat to other attendees should be locked, not public chat

**Actual behavior**
Setting private chat to "locked" disables public chat as well.

**BBB version (optional):**
2.3-beta-3

**Comment by prlanzarin** [comment]
Thanks for reporting.

Just registering: while verifying I noticed the "inverse" is also buggy: locking public chat also locks private chat, which is not intended behavior. So two slightly similar issues with probably the same root cause.
