### ISSUE TITLE
Hide/minimize self video

### ISSUE THREAD

**Issue by bersace** [bigbluebutton/bigbluebutton#11990]
Hi,

First of all, thanks for BBB, it's a great piece of code !

**Is your feature request related to a problem? Please describe.**

Always having self video is distracting and can even be a source of stress.

**Describe the solution you'd like**

I suggest to be able to hide a video while still sending webcam data.

**Describe alternatives you've considered**

I considered cutting video, but other people don't see me as well.

I also use browser dev tools to hide HTML element.

**Additional context**

See this article from Standford about video conf stress. 2nd section describe stress caused by seeing self always.

https://news.stanford.edu/2021/02/23/four-causes-zoom-fatigue-solutions/

Regards,

**Comment by uka-support** [comment]
Might have privacy implications - if the video is hidden one might forget that it's still turned on. Webcams often have indicator lights but still.

**Comment by cyBerta** [comment]
As a temporary workaround you can also install and use a browser plugin like ublock origin (or a similar plugin). With that you can either manually select which element you want to hide or you can create manual filter rules. 
The filter rule you need to add to ublock origin is 

`bbb.yourprovider.org##div.videoListItem--ZP5lQT:nth-of-type(1)`

You need to replace `bbb.yourprovider.org` by the domain of your provider.

**Comment by bersace** [comment]
@cyBerta thanks for the hint. In the same vein, I put my own video in Picture-in-Picture mode and move it around.

Stil, a toggle to blur my own video and/or minimize it would be nice. Or something like that.

**Comment by bersace** [comment]
Zoom US does have a "hide self video" option that match this feature requests.

**Comment by AlphaDE** [comment]
Any news on this issue, I am really missing such an option...?

**Comment by antobinary** [comment]
Closed via https://github.com/bigbluebutton/bigbluebutton/pull/17935
