### ISSUE TITLE
Long poll optioons break container in 2.3

### ISSUE THREAD

**Issue by lkiesow** [bigbluebutton/bigbluebutton#11999]
**Describe the bug**

Setting longer options for a poll in BigBlueButton 2.3 causes the option buttons to reach out of the surrounding container.

![Screenshot from 2021-04-12 15-22-11](https://user-images.githubusercontent.com/1008395/114430110-62e1f880-9bbe-11eb-997a-89a762ed34b1.png)

Instead of having a fixed size, the container should probably just specify the `min-width` CSS property.

**BBB version:**

BigBlueButton 2.3-beta3

**Desktop (please complete the following information):**
 
All OS and desktop browsers

**Comment by antobinary** [comment]
Thanks for reporting!

**Comment by lkiesow** [comment]
Always happy to complain 😛
