### ISSUE TITLE
2.3 Beta 3 - individual white board not showing tools for student

### ISSUE THREAD

**Issue by markginter31** [bigbluebutton/bigbluebutton#12001]
We just attempted to use the individually assigned white-board access but the tools would not appear on the student's browser.  Enabling whiteboard access for everyone worked.  Just not individuals.

2.3 Beta 3

**Comment by antobinary** [comment]
Thanks for reporting @markginter31 

This was just resolved by https://github.com/bigbluebutton/bigbluebutton/pull/11995
