### ISSUE TITLE
Echotest not working on Mobiledevices (1007)

### ISSUE THREAD

**Issue by hahaxd35** [bigbluebutton/bigbluebutton#12007]
**Describe the bug**
iPad (Safari) got 1007 ICE Error, while PC is working fine 
Android (Chrome) got the same problem
**To Reproduce**

changed the Default STUN Server 
STUN Server is working

**Actual behavior**
Echo test is aborting 

I got this "Error" on bbb-conf --check:
`
Warning: Failed to verify STUN server at  3478 with command
stunclient --mode full --localport 30000  3478
`

DID not replace the URL, but BBB Server send the STUN-Server URLs  to client 

**Desktop (working -> no problem):**
 - OS: Windows, Linux
 - Browser: Firefox and Chrome
  - Version: newest and older 

**Smartphone(not working -> ICE 1007 Error:**
 - Device: ipad pro 2020, Huawei P40 pro
 - OS: [e.g. ipadOS 14.4.2 and Android 10
 - Browser Safari  Chrome
 - Version: newest

**Additional context**

**Comment by prlanzarin** [comment]
Please test it in test23.bigbluebutton.org (which is the official testing mirror for 2.3).

**Comment by hahaxd35** [comment]
hmm. on test23.bigbluebutton.org both are working....

we use the same STUN Server on all BBB Server

**Comment by prlanzarin** [comment]
Review all the steps in https://docs.bigbluebutton.org/2.2/setup-turn-server.html.

And don't forget to set the TURN beans. Having TURN properly configured is more important than having just STUN everywhere.
I'm closing this. Feel free to reach out in the mailing lists if you have any setup questions, folks might be able to help you.

**Comment by hahaxd35** [comment]
hmm?

as i said: 
the same STUN Server is working on BBB 2.2.32 with any device. 

has the Syntax changed in  /usr/share/bbb-web/WEB-INF/classes/spring/turn-stun-servers.xml?

and why cant "bbb-conf --check" not parse my STUN setting? 
it says:
Warning: Failed to verify STUN server at  3478 with command
stunclient --mode full --localport 30000  3478 (HOST is missing)

**Comment by prlanzarin** [comment]
> hmm?
> 
> as i said:
> the same STUN Server is working on BBB 2.2.32 with any device.

You did not state that it worked in 2.2.32 anywhere in this issue.

> has the Syntax changed in /usr/share/bbb-web/WEB-INF/classes/spring/turn-stun-servers.xml?

It hasn't.

> and why cant "bbb-conf --check" not parse my STUN setting?
> it says:
> Warning: Failed to verify STUN server at 3478 with command
> stunclient --mode full --localport 30000 3478
> 
> (HOST is missing/ not parsed)

Hard to know without more info. Please attach a (preferably redacted) version of your turn-stun-servers.xml file.

**Comment by antobinary** [comment]
Talking about turn-stun-servers.xml these might be related https://github.com/bigbluebutton/bigbluebutton/pull/11804 and https://github.com/bigbluebutton/bigbluebutton/pull/11934

**Comment by hahaxd35** [comment]
this is the only part i have changed:

```
    <bean id="stun1" class="org.bigbluebutton.web.services.turn.StunServer">
        <constructor-arg index="0" value="stun:stun1.webweaver.de:3478"/>
    </bean>

    <bean id="stun2" class="org.bigbluebutton.web.services.turn.StunServer">
        <constructor-arg index="0" value="stun:stun2.webweaver.de:3479"/>
    </bean>

                <ref bean="stun1" />
                <ref bean="stun2" />
```

this is the answer from Server:

```
{
    "stunServers": [
        {
            "url": "stun:stun1.webweaver.de:3478"
        },
        {
            "url": "stun:stun2.webweaver.de:3479"
        }
    ],
    "turnServers": [
        
    ],
    "remoteIceCandidates": [
        
    ]
}
```

**Comment by basisbit** [comment]
I'd guess you are missing a turn server. STUN alone is not enough for some use cases when clients are connected over very crowded CGNAT'ed internet connections. Anyways, this is not an issue on the test server and stun+turn is so far working fine in various setups with bbb 2.3, thus I'll close this issue and point you to the support-forum for further support.

For support requests, please use the [forum / mailing list](https://groups.google.com/forum/#!forum/bigbluebutton-setup). This issue tracker here is only for BBB development related issues. Sorry.

**Comment by basisbit** [comment]
For how to properly set up the turn server and configure it, please see https://docs.bigbluebutton.org/2.2/setup-turn-server.html

**Comment by hahaxd35** [comment]
OKAY the same mobiledeviceS (on same and different Networks) with same STUN Server/setting, on same Hostnetwork is not working on 2.3 so i need a Turn Server because of "crowded CGNAT'ed internet connections."

**Comment by basisbit** [comment]
> Anyways, this is not an issue on the test server and stun+turn is so far working fine in various setups with bbb 2.3, thus [...]

**Comment by prlanzarin** [comment]
> OKAY the same mobiledeviceS (on same and different Networks) with same STUN Server/setting, on same Hostnetwork is not working on 2.3 so i need a Turn Server 

1. Review https://docs.bigbluebutton.org/2.2/configure-firewall.html#update-freeswitch
2. Review https://docs.bigbluebutton.org/2.2/troubleshooting.html#configure-bigbluebuttonfreeswitch-to-support-ipv6
3. Review https://docs.bigbluebutton.org/2.2/troubleshooting.html#freeswitch-using-default-stun-server

And, as already mentioned, if those don't work for you, the mailing lists are there with a handful of capable folks that may be able to help you out.
