### ISSUE TITLE
Audio Connection Modal inactive after connection error

### ISSUE THREAD

**Issue by PhMemmel** [bigbluebutton/bigbluebutton#12018]
**Describe the bug**
If an audio connection error appears (e. g. 1004) the audio modal is inactive

**To Reproduce**
1. Open meeting on server with broken configuration (e. g. config wrong turn server and force using turn relay via firefox config)
2. Click on "Microphone" in audio connection modal
3. Wait for error to appear
4. Try again to click "Microphone" or click "Listen only", both don't work, modal doesn't react. I have to close modal and click phone symbol again for next try.

**Expected behavior**
Modal shouldn't become inactive, user immediately wants to retry audio connection or switch to listen only.

**Actual behavior**
Modal becomes inactive.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/65113153/114625859-28a65300-9cb3-11eb-88bf-4ad0d2f0694f.png)
After error click on either of the buttons shows that the click is registered (blue border), but nothing is triggered:
![grafik](https://user-images.githubusercontent.com/65113153/114626187-a0747d80-9cb3-11eb-944c-d6fbafd12a74.png)

**BBB version (optional):**
2.3-beta-3

**Desktop (please complete the following information):**
Tried on current Firefox, but experienced that in Chrome as well (just harder to reproduce a failing audio connection with Chrome)

**Additional context**
IIRC this has been a bug for a pretty decent time in 2.2, but was fixed at some point in one of the latest releases (about 2.2.30?). Unfortunately I don't remember and couldn't figure out when this was fixed precisely. It would be nice if this fix could also be implemented in 2.3, because it's quite confusing for the user.

**Comment by PhMemmel** [comment]
I noticed this is somewhat dependent on the type of error: 1004 error -> reproducable like described, had 1007 error today -> modal didn't become inactive.

**Comment by antobinary** [comment]
Possibly related to https://github.com/bigbluebutton/bigbluebutton/issues/7903

**Comment by mariogasparoni** [comment]
@antobinary this one can be closed
