### ISSUE TITLE
& in username does not render correctly in 2.3

### ISSUE THREAD

**Issue by lkiesow** [bigbluebutton/bigbluebutton#12017]
**Describe the bug**

If a user uses a name with an ampersand in it, the name does not render correctly anywhere in the BigBlueButton 2.3 HTML5 client.

**To Reproduce**

Use Greenlight or API Mate and choose `a & b` as username.

**Screenshots**

![Screenshot from 2021-04-13 20-44-53](https://user-images.githubusercontent.com/1008395/114615530-196cd880-9ca6-11eb-89bc-edacd566c386.png)

**BBB version:**

BigBlueButton 2.3.0-beta-3

**Desktop:**
 - Any browser and OS

**Additional context**
The `getMeetings` API contains the correct name:

```xml
<fullName>x &amp; y</fullName>
```

**Comment by antobinary** [comment]
Thanks for reporting this @lkiesow !
I believe this is fixed as part of https://github.com/bigbluebutton/bigbluebutton/pull/11687 but we welcome some feedback on it before merging (in case you have a moment)

**Comment by JustinMogel** [comment]
could reproduce this on 2.3.0

**Comment by lkiesow** [comment]
Yes, I can confirm that it is still broken in 2.3.0

**Comment by antobinary** [comment]
We have not merged #11687 yet. Any chance one of you could provide feedback on it?

**Comment by antobinary** [comment]
Merging into #11687
