### ISSUE TITLE
private Chat lock affects public Chat and Chat to Moderator

### ISSUE THREAD

**Issue by Superjamp** [bigbluebutton/bigbluebutton#12019]
**Describe the bug**
If you lock the private chat, participants will no longer be able to write in the public chat and send private messages to the moderators

**To Reproduce**
1. Open meeting, join a moderator and a Participant
2. Moderator locks private chatting
3. Participant tries to write in the public Chat
4. "Chat is locked, messages can't be sent"
5. Participant tries to write with a Moderator (start private Chat dialog is shown)
6. Chat Box is disabled (similar to #12014)
7. Clicking on the private Chat the message "Chat is locked, messages can't be sent" is shown.

**Expected behavior**
Participants can write in the public chat and can send private messages to moderators

**Actual behavior**
"Chat is locked, messages can't be sent" or Chat Box is disabled

**Screenshots**
![2](https://user-images.githubusercontent.com/26893184/114688014-959e0500-9d14-11eb-8f55-4e807509b07a.png)
![1,3](https://user-images.githubusercontent.com/26893184/114687992-9171e780-9d14-11eb-974b-a50e90d12033.png)
![5](https://user-images.githubusercontent.com/26893184/114688024-9898f580-9d14-11eb-8f4a-331c9d5e4894.png)
![6](https://user-images.githubusercontent.com/26893184/114688034-9a62b900-9d14-11eb-8e17-1f7418191d1d.png)

**BBB version:**
BigBlueButton Server 2.3.0-beta-3 (1975)

**Desktop:**
 - OS: Linux Fedora 33
 - Browser Chrome
 - Version 89.0.4389.90

**Comment by PhMemmel** [comment]
This has already been reported in #11986 and fixed in #11989 which has already been merged. There is still an issue with that, because chats to moderators still aren't working, but I've already submitted a PR #12013 to fix that. If it is approved and merged in time, the chat lock problem will be fixed in next beta.
