### ISSUE TITLE
Mute Notification covers presentation controls in noisy environment

### ISSUE THREAD

**Issue by markginter31** [bigbluebutton/bigbluebutton#12024]
**Describe the bug**
Click To Unmute notifcation will cover presentation controls if the environment is noisy

**To Reproduce**
1. Go to '...' presentation
2. Click on '....' mute
4. See error --> notification will not go away when the environment is noisy and hides some of the controls

**Expected behavior**
Notification is in a position that will not cover presentation controls

**Actual behavior**
Notification is persistent in noisy environment and one cannot change slide number until unmuting mike

**Screenshots**
muted
![muted](https://user-images.githubusercontent.com/7345618/114738845-5a9cd100-9d16-11eb-8abb-192fa511fbcb.png)

not muted
![not muted](https://user-images.githubusercontent.com/7345618/114738902-67212980-9d16-11eb-97ec-078d534eb6b6.png)

BBB 2.3 Beta 3

**Comment by PlumedArcher** [comment]
I could reproduce on Windows 10 and Google Chrome using BBB 2.3 beta5.

**Comment by mariogasparoni** [comment]
@antobinary  , @ramonlsouza.
This is a workaround we have adopted at mconf.
![fix-muted-banner](https://user-images.githubusercontent.com/1780868/116308929-81c7b980-a77e-11eb-93f7-ea873a6cbbff.png)

**Comment by antobinary** [comment]
Are you able to click the < > buttons behind the rectagle?

**Comment by mariogasparoni** [comment]
Not really. 
I believe the screenshot represents a rare situation (i took it to show the transparency only) where the presenter is not speaking somehow. But yes, this could be improved.

**Comment by uka-support** [comment]
Presenter and speaker might be different persons in some scenarios (if there are multiple speakers they might share one presentation and have somebody assigned to click next).

**Comment by ramonlsouza** [comment]
We could add a way for the user to close the alerts, or even stop them for some time

![mute-alerts](https://user-images.githubusercontent.com/3728706/116405098-a6b33f80-a805-11eb-8276-a3281f1d52a7.gif)

**Comment by mariogasparoni** [comment]
Cool.
Forgot to mention but in #11913, there are some good suggestions (i believe something like as you proposed @ramonlsouza )

**Comment by Oasis256** [comment]
Or It could be made dragable using react-draggable package, This package is already  already a dependency
Gif Showing Working on Edge Mobile
![Works With Microsoft Edge Mobile](https://user-images.githubusercontent.com/17212431/116451663-74d1c580-a865-11eb-9b48-10973e6c40b5.gif)

Gif Showing working on Windows Touch
![Works With Windows Touch](https://user-images.githubusercontent.com/17212431/116451768-9763de80-a865-11eb-8f25-1a302100a083.gif)

**Comment by antobinary** [comment]
Thanks @ramonlsouza for #12204!

I see the end result and to be honest I am not sure if this approach is sufficient.

Have we considered adding a notification level flag in settings to stop this Click to unmute notification?
OR
Moving the notification out of the way - how complex would it be? I recall us experimenting with movable box in the past...

**Comment by markginter31** [comment]
Why not just have it pop up in the middle of the screen? With a little
"unmute below" kind of message?
