### ISSUE TITLE
2.3 beta 3: cannot save public chat

### ISSUE THREAD

**Issue by jdepi** [bigbluebutton/bigbluebutton#12021]
In 2.3 beta 3 saving the public chat does not work. It is also not possible to copy the chat. Functions can be selected in the html5 client, but nothing happens, then.

**To Reproduce**
1. Create a session with chrome browser or firefox (both were tested)
2. write someting into the public chat
3. select save in upper right corner of the chat window

**Expected behavior**
The browser should mention, that a file was saved.

**Actual behavior**
No hint from browsers, no file in download directory

**BBB version:**
BigBlueButton Server 2.3.0-beta-3 (1975)

**Desktop:**
 - OS: LinuxMint 20.1, Kernel Linux 5.4.0-71-generic
 - Browser 1) Chromium Version 89.0.4389.114 (official build) for Linux Mint (64-Bit)
 - Borwser 2) Mozilla Firefox for LinuxMint v87.0 (64 bit)

**Comment by pedrobmarin** [comment]
@jdepi thanks for the report.

This was fixed in https://github.com/bigbluebutton/bigbluebutton/pull/11994 and will be available in the next release.
