### ISSUE TITLE
[Feature request] Participants list should also list absentees

### ISSUE THREAD

**Issue by ParaDice13** [bigbluebutton/bigbluebutton#12033]
For people teaching courses with mandatory BBB presence, it's a bit of a hassle to manually compare the list of attendees with name lists of people who should be present. Hence, it would be great if the participants list could have a separate section that lists those participants that should be present, but are absent.

Obviously, this would only work for use-cases like mine where BBB gets all user names via Moodle/LDAP. Hence server *could* also pass a list of participants that _should_, theoretically, be present in a BBB session. If BBB got such a list from the server, it could find out who is present and who isn't, and list the names accordingly.

**Comment by antobinary** [comment]
Hi @ParaDice13 
BigBlueButton is the conferencing portion of your Moodle session. We have no knowledge of people who do not join meetings. I suggest you look into a solution within Moodle.

While I have no knowledge of Moodle (or other LMS), I'd imagine that you could track who hit the button/link to join a meeting at least once.
