### ISSUE TITLE
run-prod.sh error connecting to redis

### ISSUE THREAD

**Issue by rmorenocampos** [bigbluebutton/bigbluebutton#12031]
**Describe the bug**
BBB cant connect to redis server.

**To Reproduce**
Fresh install of the 2.3 dev version with autoinstall script

**Expected behavior**
I would connec to bbb api

**Actual behavior**
I have a 404 from the server when i try to connect to the api

**Screenshots**
bbb-conf --status
![status2](https://user-images.githubusercontent.com/78098914/114842624-51c10380-9dd9-11eb-8741-47a0de5d8799.png)

bbb-conf --debug
![error](https://user-images.githubusercontent.com/78098914/114842645-55ed2100-9dd9-11eb-882a-53da2929e70e.png)              

bbb-conf --check has the typicall information about the server standard configuration and the only warning is the api demos.

**Comment by antobinary** [comment]
Hi @rmorenocampos 
What module are you trying to run? bbb-web?
Could you please confirm that redis is indeed running?

How do you connect to the api? https://mconf.github.io/api-mate/ ?

**Comment by rmorenocampos** [comment]
Yes actually everything is running I'm going to attach screenshot about it 

![redisserver](https://user-images.githubusercontent.com/78098914/115017213-78a13780-9eb6-11eb-8ff6-a668f4a63d0a.png)

This is my api connection  
https://mconf.github.io/api-mate/#server=https://h2931082.stratoserver.net/bigbluebutton/&sharedSecret=MRkb9NokyWm0N63vku9mhm9BcT0Y26F3gKCsWqAnw
Some services fail with 404 error and the only stack trace about the error is in the bbb-conf --debug 

![redisserver](https://user-images.githubusercontent.com/78098914/115017474-e483a000-9eb6-11eb-88fa-5b252d998623.png)

But i dont reallt know if it is a connection error or memory error
