### ISSUE TITLE
Profile picture not being shown during the meeting

### ISSUE THREAD

**Issue by PlumedArcher** [bigbluebutton/bigbluebutton#12032]
**To Reproduce**
1. Choose a profile picture in your profile settings 
2. Click on 'update'
3. Start/join a conference
4. Profile picture is not visible in the user list/ public chat, neither for me nor for others.

**Expected behavior**
Seeing the selected picture

**Actual behavior**
I still just see the first letters. 

**BBB version (optional):** BBB 2.3 beta 4
Tested on https://test23.bigbluebutton.org/ 
Client build 1595

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browsers: Chrome, Microsoft 
Edge
 - Version:  89.0.4389.128 (Chrome)  ;    89.0.774.76 (edge)

**Smartphone (please complete the following information):**
- not tested

**Additional context**
Seems to be an issue regardless of the size of the picture.
When an other user joins, he can see the profil picture of the initiator on the joining screen. After joining, one can't see any profile pic. 
Not sure if intended, but if so, it would be a nice feature to add.

![Screenshot (817)_LI](https://user-images.githubusercontent.com/80673946/114844977-a06f9d00-9ddb-11eb-9bb3-a6a73d83bce3.jpg)

**Comment by pedrobmarin** [comment]
Done in https://github.com/bigbluebutton/bigbluebutton/pull/10458 . If you want to use the avatar support check on how it's handled at the join API call.

**Comment by hahaxd35** [comment]
does not work in 2.5.0-rc1 too

**Comment by prlanzarin** [comment]
> does not work in 2.5.0-rc1 too

See https://github.com/bigbluebutton/bigbluebutton/pull/14968.

Please do not resurrect old issues.

**Comment by hahaxd35** [comment]
sorry Github search is not easy and fid not see 2021
