### ISSUE TITLE
[2.3-beta3] Could not install bbb-libreoffice-docker

### ISSUE THREAD

**Issue by caniwi** [bigbluebutton/bigbluebutton#12030]
<!--PLEASE DO NOT FILE ISSUES FOR GENERAL SUPPORT QUESTIONS.
After upgrade to 2.3 beta3 bbb-libreoffice-docker does not seem complete.  There is no docker running for Libreoffice and document conversion fails silently.

**Describe the bug**
Upgrade from 2.3-beta2 to 2.3-beta3, libreoffice document conversion does not complete.  We are pretty sure it worked on beta2.

**To Reproduce**
1. As presenter try to upload a presentation in libreoffice format (docx, ods, etc)
2. Get document conversion in progress message but never completes.
3. A pdf works fine.

**Expected behavior**
Document conversion completes and converted document is available for presentation.

**Actual behavior**
Document conversion never completes and no presentation is available.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser Firefox 
 - Version 87

**Additional context**
There are no libreoffice docker containers available.  There are no bbb-libreoffice systemd files.

bbb-conf --version
default

BigBlueButton Server 2.3.0-beta-3 (1976)

ii  bbb-apps-akka                               2.3.0-67                                    all          BigBlueButton Apps (Akka)
ii  bbb-config                                  1:2.3.0-57                                  amd64        BigBlueButton configuration utilities
ii  bbb-etherpad                                1:2.3.0-45                                  amd64        The EtherPad Lite components for BigBlueButton
ii  bbb-freeswitch-core                         2:2.3.0-12                                  amd64        BigBlueButton build of FreeSWITCH
ii  bbb-freeswitch-sounds                       1:1.6.7-1                                   amd64        FreeSWITCH Sounds
ii  bbb-fsesl-akka                              2.3.0-37                                    all          BigBlueButton FS-ESL (Akka)
ii  bbb-html5                                   1:2.3.0-1588                                amd64        The HTML5 components for BigBlueButton
ii  bbb-libreoffice-docker                      1:2.3.0-22                                  amd64        BigBlueButton setup for LibreOffice running in docker
ii  bbb-mkclean                                 1:0.8.7-1                                   amd64        Clean and optimize Matroska and WebM files
ii  bbb-playback                                1:2.3.0-8                                   amd64        BigBlueButton playback
ii  bbb-playback-presentation                   1:2.3.0-9                                   amd64        BigBluebutton playback of presentation
ii  bbb-record-core                             1:2.3.0-29                                  amd64        BigBlueButton record and playback
rc  bbb-transcode-akka                          2.3.0-1                                     all          BigBlueButton Transcoder
ii  bbb-web                                     1:2.3.0-67                                  amd64        BigBlueButton API
ii  bbb-webrtc-sfu                              1:2.3.0-16                                  amd64        BigBlueButton WebRTC SFU
ii  bigbluebutton                               1:2.3.0-5                                   amd64        Open source web conferencing platform (bbb)
ii  ffmpeg                                      7:4.2.4-1ubuntu0.1bbb2~18.04                amd64        Tools for transcoding, streaming and playing of multimedia files
ii  libavcodec58:amd64                          7:4.2.4-1ubuntu0.1bbb2~18.04                amd64        FFmpeg library with de/encoders for audio/video codecs - runtime files
ii  libavdevice58:amd64                         7:4.2.4-1ubuntu0.1bbb2~18.04                amd64        FFmpeg library for handling input and output devices - runtime files
ii  libavfilter7:amd64                          7:4.2.4-1ubuntu0.1bbb2~18.04                amd64        FFmpeg library containing media filters - runtime files
ii  libavformat58:amd64                         7:4.2.4-1ubuntu0.1bbb2~18.04                amd64        FFmpeg library with (de)muxers for multimedia containers - runtime files
ii  libavresample4:amd64                        7:4.2.4-1ubuntu0.1bbb2~18.04                amd64        FFmpeg compatibility library for resampling - runtime files
ii  libavutil56:amd64                           7:4.2.4-1ubuntu0.1bbb2~18.04                amd64        FFmpeg library with functions for simplifying programming - runtime files
ii  libopusenc0                                 0.2.1-1bbb1                                 amd64        High-level API for encoding Ogg Opus audio streams
ii  libpostproc55:amd64                         7:4.2.4-1ubuntu0.1bbb2~18.04                amd64        FFmpeg library for post processing - runtime files
ii  libswresample3:amd64                        7:4.2.4-1ubuntu0.1bbb2~18.04                amd64        FFmpeg library for audio resampling, rematrixing etc. - runtime files
ii  libswscale5:amd64                           7:4.2.4-1ubuntu0.1bbb2~18.04                amd64        FFmpeg library for image scaling and various conversions - runtime files

**Comment by caniwi** [comment]
ARGHHHH what happened to my description?

**Comment by caniwi** [comment]
After upgrade to beta3 from beta2 Office document conversion fails and no presentation is available.  There are no Libreoffice containers and no systemd files.

 bbb-conf --version
default

BigBlueButton Server 2.3.0-beta-3 (1976)

ii  bbb-apps-akka                               2.3.0-67                                    all          BigBlueButton Apps (Akka)
ii  bbb-config                                  1:2.3.0-57                                  amd64        BigBlueButton configuration utilities
ii  bbb-etherpad                                1:2.3.0-45                                  amd64        The EtherPad Lite components for BigBlueButton
ii  bbb-freeswitch-core                         2:2.3.0-12                                  amd64        BigBlueButton build of FreeSWITCH
ii  bbb-freeswitch-sounds                       1:1.6.7-1                                   amd64        FreeSWITCH Sounds
ii  bbb-fsesl-akka                              2.3.0-37                                    all          BigBlueButton FS-ESL (Akka)
ii  bbb-html5                                   1:2.3.0-1588                                amd64        The HTML5 components for BigBlueButton
ii  bbb-libreoffice-docker                      1:2.3.0-22                                  amd64        BigBlueButton setup for LibreOffice running in docker
ii  bbb-mkclean                                 1:0.8.7-1                                   amd64        Clean and optimize Matroska and WebM files
ii  bbb-playback                                1:2.3.0-8                                   amd64        BigBlueButton playback
ii  bbb-playback-presentation                   1:2.3.0-9                                   amd64        BigBluebutton playback of presentation
ii  bbb-record-core                             1:2.3.0-29                                  amd64        BigBlueButton record and playback
rc  bbb-transcode-akka                          2.3.0-1                                     all          BigBlueButton Transcoder
ii  bbb-web                                     1:2.3.0-67                                  amd64        BigBlueButton API
ii  bbb-webrtc-sfu                              1:2.3.0-16                                  amd64        BigBlueButton WebRTC SFU
ii  bigbluebutton                               1:2.3.0-5                                   amd64        Open source web conferencing platform (bbb)
ii  ffmpeg                                      7:4.2.4-1ubuntu0.1bbb2~18.04                amd64        Tools for transcoding, streaming and playing of multimedia files
ii  libavcodec58:amd64                          7:4.2.4-1ubuntu0.1bbb2~18.04                amd64        FFmpeg library with de/encoders for audio/video codecs - runtime files
ii  libavdevice58:amd64                         7:4.2.4-1ubuntu0.1bbb2~18.04                amd64        FFmpeg library for handling input and output devices - runtime files
ii  libavfilter7:amd64                          7:4.2.4-1ubuntu0.1bbb2~18.04                amd64        FFmpeg library containing media filters - runtime files
ii  libavformat58:amd64                         7:4.2.4-1ubuntu0.1bbb2~18.04                amd64        FFmpeg library with (de)muxers for multimedia containers - runtime files
ii  libavresample4:amd64                        7:4.2.4-1ubuntu0.1bbb2~18.04                amd64        FFmpeg compatibility library for resampling - runtime files
ii  libavutil56:amd64                           7:4.2.4-1ubuntu0.1bbb2~18.04                amd64        FFmpeg library with functions for simplifying programming - runtime files
ii  libopusenc0                                 0.2.1-1bbb1                                 amd64        High-level API for encoding Ogg Opus audio streams
ii  libpostproc55:amd64                         7:4.2.4-1ubuntu0.1bbb2~18.04                amd64        FFmpeg library for post processing - runtime files
ii  libswresample3:amd64                        7:4.2.4-1ubuntu0.1bbb2~18.04                amd64        FFmpeg library for audio resampling, rematrixing etc. - runtime files
ii  libswscale5:amd64                           7:4.2.4-1ubuntu0.1bbb2~18.04                amd64        FFmpeg library for image scaling and various conversions - runtime files

bbb-conf --status
default
nginx —————————————————► [✔ - active]
freeswitch ————————————► [✔ - active]
redis-server ——————————► [✔ - active]
bbb-apps-akka —————————► [✔ - active]
bbb-fsesl-akka ————————► [✔ - active]
mongod ————————————————► [✔ - active]
bbb-html5 —————————————► [✔ - active]
bbb-webrtc-sfu ————————► [✔ - active]
kurento-media-server ——► [✔ - active]
etherpad ——————————————► [✔ - active]
bbb-web ———————————————► [✔ - active]

docker ps --all
CONTAINER ID   IMAGE                                                                                          COMMAND                  CREATED       STATUS          PORTS                      NAMES
d9eb90e41bcf   gitlab.catalyst.net.nz:4567/catalyst-bbb/docker-images/greenlight:release-2.7.20-cat1.0-MCI3   "bin/start"              3 weeks ago   Up 28 minutes   127.0.0.1:5000->80/tcp     greenlight-v2
6e2a509f3252   postgres:9.5                                                                                   "docker-entrypoint.s…"   3 weeks ago   Up 28 minutes   127.0.0.1:5432->5432/tcp   greenlight_db_1

apt install bbb-libreoffice-docker --reinstall
Reading package lists... Done
Building dependency tree       
Reading state information... Done
0 upgraded, 0 newly installed, 1 reinstalled, 0 to remove and 1 not upgraded.
Need to get 5,118 B of archives.
After this operation, 0 B of additional disk space will be used.
Get:1 https://ubuntu.bigbluebutton.org/bionic-230 bigbluebutton-bionic/main amd64 bbb-libreoffice-docker amd64 1:2.3.0-22 [5,118 B]
Fetched 5,118 B in 1s (5,875 B/s)                                                         
(Reading database ... 217403 files and directories currently installed.)
Preparing to unpack .../bbb-libreoffice-docker_1%3a2.3.0-22_amd64.deb ...
Failed to stop bbb-libreoffice-01.service: Unit bbb-libreoffice-01.service not loaded.
dpkg: warning: old bbb-libreoffice-docker package pre-removal script subprocess returned error exit status 5
dpkg: trying script from the new package instead ...
Failed to stop bbb-libreoffice-01.service: Unit bbb-libreoffice-01.service not loaded.
dpkg: error processing archive /var/cache/apt/archives/bbb-libreoffice-docker_1%3a2.3.0-22_amd64.deb (--unpack):
 new bbb-libreoffice-docker package pre-removal script subprocess returned error exit status 5
#
# Building bbb-libreoffice docker image
#
Sending build context to Docker daemon  2.048kB
Step 1/6 : FROM openjdk:11-jre
 ---> 1cf688a75b44
Step 2/6 : ENV DEBIAN_FRONTEND noninteractive
 ---> Using cache
 ---> 5b0917ec78ab
Step 3/6 : RUN apt update
 ---> Using cache
 ---> ee294ca1b5ca
Step 4/6 : RUN apt -y install locales-all fontconfig libxt6 libxrender1
 ---> Using cache
 ---> 581ce492095b
Step 5/6 : RUN apt -y install  --no-install-recommends libreoffice fonts-crosextra-carlito fonts-crosextra-caladea fonts-noto fonts-noto-cjk
 ---> Using cache
 ---> 209b6401aadd
Step 6/6 : RUN dpkg-reconfigure fontconfig && fc-cache -f -s -v
 ---> Using cache
 ---> 4258cad14338
Successfully built 4258cad14338
Successfully tagged bbb-soffice:latest
Errors were encountered while processing:
 /var/cache/apt/archives/bbb-libreoffice-docker_1%3a2.3.0-22_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)

systemctl status bbb-
bbb-apps-akka.service          bbb-html5-frontend@1.service   bbb-rap-resque-worker.service  bbb-web.service
bbb-fsesl-akka.service         bbb-html5-frontend@2.service   bbb-rap-starter.service        
bbb-html5-backend@1.service    bbb-html5.service              bbb-transcode-akka.service     
bbb-html5-backend@2.service    bbb-rap-caption-inbox.service  bbb-webrtc-sfu.service

**Comment by wolbernd** [comment]
@caniwi I'm not sure if it is the same issue, but we had a similar problem with building libreoffice containers. In our case it was the MTU size for the docker bridge. The main interface of our VM has a MTU of 1450. However docker bridges are built by default with a MTU of 1500. You can check the MTU of your interface with `ip a` and if it is less then 1500 then create a file `/etc/docker/daemon.json` with the following content:
```
{
  "mtu": 1450
}
```
Then restart docker and try to reinstall `bbb-libreoffice`

**Comment by antobinary** [comment]
Hi @caniwi 

I encountered similar issues yesterday when testing upgrading of 2.3 servers to 2.3-beta-4. This is what I added in the release notes:

```
Note - if upgrading from previous 2.3-beta install, edit /var/lib/dpkg/info/bbb-libreoffice-docker.prerm to comment out the line (near the bottom)
docker network remove bbb-libreoffice -> # docker network remove bbb-libreoffice this should help you to uninstall the previous bbb-libreoffice-docker version
```

You may want to also comment out the 

```
systemctl stop bbb-libreoffice-0${i}
systemctl disable bbb-libreoffice-0${i}
```

I have improved the condition checking for these in beta4's bbb-libreoffice-docker prerm step (executed before upgrade)

Please let me know how it goes!

**Comment by caniwi** [comment]
I can confirm our MTU is 1500 all the way down.

I just upgraded to beta 5 and the image is there.  It seems to launch but document conversion fails.  This should go on a separate ticket I think.

docker image list
REPOSITORY                                                          TAG                          IMAGE ID       CREATED          SIZE
bbb-soffice                                                         latest                       8ae657bfb241   29 minutes ago   1.31GB
openjdk                                                             11-jre                       1cf688a75b44   8 days ago       301MB
gitlab.catalyst.net.nz:4567/catalyst-bbb/docker-images/greenlight   release-2.7.20-cat1.0-MCI3   34e1a3f5e5f9   4 weeks ago      289MB
postgres                                                            9.5                          5e94c23120dd   8 months ago     196MB
