### ISSUE TITLE
[2.3 beta 3] Mute notification is triggered if lock settings forbid microphone usage

### ISSUE THREAD

**Issue by schrd** [bigbluebutton/bigbluebutton#12048]
**Describe the bug**
The "Click to unmute" popup is shown on audio activity if microphone usage is forbidden and there is noise activity.

**To Reproduce**
1. Join as viewer using microphone
2. As moderator change lock settings to lock share microphone
3. as viewer produce some noise

**Expected behavior**
Voice activity popup should only be shown if the users may share their microphone

**Actual behavior**

**Screenshots**
![Bildschirmfoto von 2021-04-15 23-47-10](https://user-images.githubusercontent.com/179952/114943295-114b9f00-9e46-11eb-841a-304f1aea1e0b.png)

**BBB version (optional):**

Found on BBB 2.3 Beta 3. Also reproducable on latest commit on develop (8cd827a37927d19bb962481edefb11959569337b)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Firefox, Chrome

**Comment by antobinary** [comment]
Thanks for reporting!

**Comment by mariogasparoni** [comment]
@antobinary this can be closed since #12730 got merged
