### ISSUE TITLE
reload page after a while on 2.3-beta3

### ISSUE THREAD

**Issue by smb3843** [bigbluebutton/bigbluebutton#12041]
my users page reload after a while and i got follow error:
and how can i downgrade to beta2 or beta1?
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]: Exception while invoking method 'toggleVoice' Error: Match error: Expected string, got undefined
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:     at check (packages/check/match.js:36:17)
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:     at MethodInvocation.muteToggle (imports/api/voice-users/server/methods/muteToggle.js:17:3)
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1771:12)
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:     at packages/ddp-server/livedata_server.js:719:19
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:     at packages/ddp-server/livedata_server.js:717:46
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:     at packages/ddp-server/livedata_server.js:715:46
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:     at new Promise (<anonymous>)
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:     at Session.method (packages/ddp-server/livedata_server.js:689:23)
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:     at packages/ddp-server/livedata_server.js:559:43
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]: Sanitized and reported to the client as: errorClass [Error]: Match failed [400]
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:     at errorClass.<anonymous> (packages/check/match.js:91:27)
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:     at new errorClass (packages/meteor.js:655:17)
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:     at check (packages/check/match.js:36:17)
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:     at MethodInvocation.muteToggle (imports/api/voice-users/server/methods/muteToggle.js:17:3)
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1771:12)
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:     at packages/ddp-server/livedata_server.js:719:19
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:     at packages/ddp-server/livedata_server.js:717:46
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:     at packages/ddp-server/livedata_server.js:715:46
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:     at new Promise (<anonymous>)
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:     at Session.method (packages/ddp-server/livedata_server.js:689:23)
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:     at packages/ddp-server/livedata_server.js:559:43 {
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:   isClientSafe: true,
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:   error: 400,
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:   reason: 'Match failed',
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:   details: undefined,
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:   message: 'Match failed [400]',
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:   errorType: 'Meteor.Error'
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]: }
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]: Exception while invoking method 'toggleVoice' Error: Match error: Expected string, got undefined
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:     at check (packages/check/match.js:36:17)
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:     at MethodInvocation.muteToggle (imports/api/voice-users/server/methods/muteToggle.js:17:3)
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1771:12)
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:     at packages/ddp-server/livedata_server.js:719:19
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:     at packages/ddp-server/livedata_server.js:717:46
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:     at packages/ddp-server/livedata_server.js:715:46
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:     at new Promise (<anonymous>)
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:     at Session.method (packages/ddp-server/livedata_server.js:689:23)
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:     at packages/ddp-server/livedata_server.js:559:43
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]: Sanitized and reported to the client as: errorClass [Error]: Match failed [400]
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:     at errorClass.<anonymous> (packages/check/match.js:91:27)
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:     at new errorClass (packages/meteor.js:655:17)
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:     at check (packages/check/match.js:36:17)
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:     at MethodInvocation.muteToggle (imports/api/voice-users/server/methods/muteToggle.js:17:3)
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1771:12)
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:     at packages/ddp-server/livedata_server.js:719:19
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:     at packages/ddp-server/livedata_server.js:717:46
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:     at packages/ddp-server/livedata_server.js:715:46
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:     at new Promise (<anonymous>)
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:     at Session.method (packages/ddp-server/livedata_server.js:689:23)
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:     at packages/ddp-server/livedata_server.js:559:43 {
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:   isClientSafe: true,
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:   error: 400,
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:   reason: 'Match failed',
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:   details: undefined,
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:   message: 'Match failed [400]',
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:   errorType: 'Meteor.Error'
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]: }
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]: Exception while invoking method 'toggleVoice' Error: Match error: Expected string, got undefined
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:     at check (packages/check/match.js:36:17)
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:     at MethodInvocation.muteToggle (imports/api/voice-users/server/methods/muteToggle.js:17:3)
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1771:12)
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:     at packages/ddp-server/livedata_server.js:719:19
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:     at packages/ddp-server/livedata_server.js:717:46
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:     at packages/ddp-server/livedata_server.js:715:46
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:     at new Promise (<anonymous>)
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:     at Session.method (packages/ddp-server/livedata_server.js:689:23)
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:     at packages/ddp-server/livedata_server.js:559:43
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]: Sanitized and reported to the client as: errorClass [Error]: Match failed [400]
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:     at errorClass.<anonymous> (packages/check/match.js:91:27)
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:     at new errorClass (packages/meteor.js:655:17)
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:     at check (packages/check/match.js:36:17)
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:     at MethodInvocation.muteToggle (imports/api/voice-users/server/methods/muteToggle.js:17:3)
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1771:12)
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:     at packages/ddp-server/livedata_server.js:719:19
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:     at packages/ddp-server/livedata_server.js:717:46
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:     at packages/ddp-server/livedata_server.js:715:46
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:     at new Promise (<anonymous>)
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:     at Session.method (packages/ddp-server/livedata_server.js:689:23)
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:     at packages/ddp-server/livedata_server.js:559:43 {
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:   isClientSafe: true,
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:   error: 400,
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:   reason: 'Match failed',
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:   details: undefined,
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:   message: 'Match failed [400]',
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:   errorType: 'Meteor.Error'
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]: }
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]: Exception while invoking method 'toggleVoice' Error: Match error: Expected string, got undefined
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:     at check (packages/check/match.js:36:17)
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:     at MethodInvocation.muteToggle (imports/api/voice-users/server/methods/muteToggle.js:17:3)
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1771:12)
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:     at packages/ddp-server/livedata_server.js:719:19
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:     at packages/ddp-server/livedata_server.js:717:46
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:     at packages/ddp-server/livedata_server.js:715:46
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:     at new Promise (<anonymous>)
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:     at Session.method (packages/ddp-server/livedata_server.js:689:23)
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:     at packages/ddp-server/livedata_server.js:559:43
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]: Sanitized and reported to the client as: errorClass [Error]: Match failed [400]
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:     at errorClass.<anonymous> (packages/check/match.js:91:27)
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:     at new errorClass (packages/meteor.js:655:17)
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:     at check (packages/check/match.js:36:17)
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:     at MethodInvocation.muteToggle (imports/api/voice-users/server/methods/muteToggle.js:17:3)
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1771:12)
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:     at packages/ddp-server/livedata_server.js:719:19
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:     at packages/ddp-server/livedata_server.js:717:46
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:     at packages/ddp-server/livedata_server.js:715:46
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:     at new Promise (<anonymous>)
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:     at Session.method (packages/ddp-server/livedata_server.js:689:23)
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:     at packages/ddp-server/livedata_server.js:559:43 {
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:   isClientSafe: true,
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:   error: 400,
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:   reason: 'Match failed',
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:   details: undefined,
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:   message: 'Match failed [400]',
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:   errorType: 'Meteor.Error'
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]: }
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]: Exception while invoking method 'toggleVoice' Error: Match error: Expected string, got undefined
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:     at check (packages/check/match.js:36:17)
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:     at MethodInvocation.muteToggle (imports/api/voice-users/server/methods/muteToggle.js:17:3)
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1771:12)
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:     at packages/ddp-server/livedata_server.js:719:19
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:     at packages/ddp-server/livedata_server.js:717:46
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:     at packages/ddp-server/livedata_server.js:715:46
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:     at new Promise (<anonymous>)
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:     at Session.method (packages/ddp-server/livedata_server.js:689:23)
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:     at packages/ddp-server/livedata_server.js:559:43
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]: Sanitized and reported to the client as: errorClass [Error]: Match failed [400]
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:     at errorClass.<anonymous> (packages/check/match.js:91:27)
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:     at new errorClass (packages/meteor.js:655:17)
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:     at check (packages/check/match.js:36:17)
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:     at MethodInvocation.muteToggle (imports/api/voice-users/server/methods/muteToggle.js:17:3)
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1771:12)
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:     at packages/ddp-server/livedata_server.js:719:19
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:     at packages/ddp-server/livedata_server.js:717:46
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:     at packages/ddp-server/livedata_server.js:715:46
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:     at new Promise (<anonymous>)
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:     at Session.method (packages/ddp-server/livedata_server.js:689:23)
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:     at packages/ddp-server/livedata_server.js:559:43 {
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:   isClientSafe: true,
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:   error: 400,
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:   reason: 'Match failed',
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:   details: undefined,
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:   message: 'Match failed [400]',
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:   errorType: 'Meteor.Error'
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]: }
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]: Exception while invoking method 'toggleVoice' Error: Match error: Expected string, got undefined
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:     at check (packages/check/match.js:36:17)
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:     at MethodInvocation.muteToggle (imports/api/voice-users/server/methods/muteToggle.js:17:3)
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1771:12)
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:     at packages/ddp-server/livedata_server.js:719:19
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:     at packages/ddp-server/livedata_server.js:717:46
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:     at packages/ddp-server/livedata_server.js:715:46
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:     at new Promise (<anonymous>)
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:     at Session.method (packages/ddp-server/livedata_server.js:689:23)
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:     at packages/ddp-server/livedata_server.js:559:43
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]: Sanitized and reported to the client as: errorClass [Error]: Match failed [400]
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:     at errorClass.<anonymous> (packages/check/match.js:91:27)
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:     at new errorClass (packages/meteor.js:655:17)
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:     at check (packages/check/match.js:36:17)
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:     at MethodInvocation.muteToggle (imports/api/voice-users/server/methods/muteToggle.js:17:3)
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1771:12)
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:     at packages/ddp-server/livedata_server.js:719:19
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:     at packages/ddp-server/livedata_server.js:717:46
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:     at packages/ddp-server/livedata_server.js:715:46
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:     at new Promise (<anonymous>)
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:     at Session.method (packages/ddp-server/livedata_server.js:689:23)
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:     at packages/ddp-server/livedata_server.js:559:43 {
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:   isClientSafe: true,
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:   error: 400,
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:   reason: 'Match failed',
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:   details: undefined,
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:   message: 'Match failed [400]',
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]:   errorType: 'Meteor.Error'
Apr 15 21:56:02 vc231 systemd_start_frontend.sh[25962]: }
Apr 15 21:56:02 vc231 run-prod.sh[26018]: 2021-04-15T21:56:02.442+04:30 DEBUG o.b.web.controllers.ApiController - ApiController#enter

**Comment by antobinary** [comment]
Hi @smb3843 
Is there actual issue that you're encountering? Sounds like your connection was unstable for a moment and you reconnected. We'll check the usage of the toggleVoice call but please elaborate a bit - did you hit an issue or just spotted error lines in the terminal?

**Comment by smb3843** [comment]
the page reload and when come backed cant active microphone.
another question ,is there any way to install or downgrade beta1 or beta2?

**Comment by antobinary** [comment]
Please reopen if this issue reoccurs
