### ISSUE TITLE
Shared notes not working after update 

### ISSUE THREAD

**Issue by Braehler** [bigbluebutton/bigbluebutton#12049]
**Describe the bug**
After the update to the current version the shared notes are not working.  We receive the message 404 Not Found nginx

**To Reproduce**
1. Go to a room of your choise
2. Click on shared notes
3. See error: 404 Not Found ngnix

**Expected behavior**
Shared notes should work like before

**Actual behavior**
Shared notes do not work see error

**Screenshots**

**BBB version (optional):
BigBlueButton continually evolves. Providing the version/build helps us to pinpoint when an issue was introduced.
Example:
$ sudo bbb-conf --check | grep BigBlueButton
BigBlueButton Server 2.2.36

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, Mac]
 - Browser [e.g. Chrome, Safari]

**Smartphone (please complete the following information):**
 - Browser [e.g. stock browser, Safari]

**Additional context**
Here is the output of bbb-conf --check

BigBlueButton Server 2.2.36 (2416)
                    Kernel version: 4.4.0-208-generic
                      Distribution: Ubuntu 16.04.7 LTS (64-bit)
                            Memory: 65755 MB
                         CPU cores: 8

/usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties (bbb-web)
       bigbluebutton.web.serverURL: https://our-domain.de
                defaultGuestPolicy: ALWAYS_ACCEPT
                 svgImagesRequired: true

/etc/nginx/sites-available/bigbluebutton (nginx)
                       server_name: our-domain.de
                              port: 80, [::]:80
                              port: 443 ssl

/opt/freeswitch/etc/freeswitch/vars.xml (FreeSWITCH)
                       local_ip_v4: 5.9.31.198
                   external_rtp_ip: 5.9.31.198
                   external_sip_ip: 5.9.31.198

/opt/freeswitch/etc/freeswitch/sip_profiles/external.xml (FreeSWITCH)
                        ext-rtp-ip: $${external_rtp_ip}
                        ext-sip-ip: $${external_sip_ip}
                        ws-binding: 5.9.31.198:5066
                       wss-binding: 5.9.31.198:7443

/usr/local/bigbluebutton/core/scripts/bigbluebutton.yml (record and playback)
                     playback_host: our-domain.de
                 playback_protocol: https
                            ffmpeg: 4.2.4-1ubuntu0.1bbb1~16.04.1

/etc/bigbluebutton/nginx/sip.nginx (sip.nginx)
                        proxy_pass: 5.9.31.198
                          protocol: http

/usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml (Kurento SFU)
                        kurento.ip: 5.9.31.198
                       kurento.url: ws://127.0.0.1:8888/kurento
                    kurento.sip_ip: 5.9.31.198
                    localIpAddress: 5.9.31.198
               recordScreenSharing: true
                     recordWebcams: true
                  codec_video_main: VP8
               codec_video_content: VP8

/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml (HTML5 client)
                             build: 1144
                        kurentoUrl: wss://our-domain/bbb-webrtc-sfu
                  enableListenOnly: true
                    sipjsHackViaWs: true

/usr/share/bbb-web/WEB-INF/classes/spring/turn-stun-servers.xml (STUN Server)
                              stun:stun.l.google.com:19302

# Potential problems described below

We updated the bbb server first via the update upgrade functionality, not with the install.sh. After getting some errors like 1006 when trying to connect the audio, we ran the install.sh script. Everything works, only the shared notes are not available

**Comment by pedrobmarin** [comment]
Can you verify it's the same problem described in https://github.com/bigbluebutton/bigbluebutton/issues/11965 ?

**Comment by Braehler** [comment]
Seems to be the same, we also got some messages regarding the conflicts in the config file, we keped the old version during the distupgrade. 
As far as I can remember they were also shown during the install.sh

**Comment by pedrobmarin** [comment]
I'm not aware what's the package maintainer recommendations on those but looks like ignoring it's not the best choice. I found this piece of documentation that might help you out https://docs.bigbluebutton.org/2.2/install.html#upgrading-from-bigbluebutton-22 .

**Comment by Braehler** [comment]
thanks,
pretty sure we did not enter the updates for ffmpeg and libre office.
When we set up our server we did it via stept by step install, not with the install.sh. That was only the solution to get it working again yesterday
 I´ll give it a try and hope to not destroy the whole installation ;-)

**Comment by pedrobmarin** [comment]
Alright, good luck on that!

I'm closing this one for us to follow this problem at #11965
