### ISSUE TITLE
bbb-freeswitch-core 2.3-beta3 still contains FreeSWITCH vanilla config

### ISSUE THREAD

**Issue by znerol** [bigbluebutton/bigbluebutton#12047]
**Describe the bug**

In #11864 a whole bunch of FreeSWITCH config was removed. That PR was referenced from the 2.3-beta3 release notes. However, it looks like that change did not make it into `bbb-freeswitch-core` 2.3-beta3 package:

```
$ apt policy bbb-freeswitch-core
bbb-freeswitch-core:
  Installed: 2:2.3.0-12
  Candidate: 2:2.3.0-12
  Version table:
 *** 2:2.3.0-12 500
        500 https://ubuntu.bigbluebutton.org/bionic-230 bigbluebutton-bionic/main amd64 Packages
        100 /var/lib/dpkg/status
```

```
$ dpkg -L bbb-freeswitch-core | grep tetris
/opt/freeswitch/etc/freeswitch/tetris.ttml
```

**To Reproduce**

Install BBB 2.3-beta3 (using any method).

**Expected behavior**

The directory `/opt/freeswitch/etc/freeswitch` only should not contain any config and content for superflous FreeSWITCH modules.

**Actual behavior**

The directory `/opt/freeswitch/etc/freeswitch` a whole bunch of stuff the PR referenced above actually removed.

**Comment by antobinary** [comment]
Thanks  @ffdixon for addressing this in packaging! This should be part of 2.3-beta6
