### ISSUE TITLE
2.3-beta4: Public chat doesn't show old messages after being locked

### ISSUE THREAD

**Issue by PhMemmel** [bigbluebutton/bigbluebutton#12062]
**Describe the bug**
If public chat is being locked, old messages aren't shown anymore for locked attendees

**To Reproduce**
1. Open session, log in as a mod and two attendees
2. Let attendee private chat with other attendee (for sure there are also other scenarios in which this happens, but this one is reproducable easily)
3. Lock public chat as mod
4. Click "public chat" as attendee (don't close private chat separately before)
5. All messages from before aren't shown for the attendee switching from private to public chat, sometimes it even cuts off default welcome message (see screenshot). This cut-off is not completely easy to reproducable, though.

**Expected behavior**
Old messages should be shown in the public chat as only **writing** messages should be locked.

**Actual behavior**
Public chat has completely been cleared for client, only shows messages sent after being locked.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/65113153/115122108-7a522480-9fb6-11eb-9378-526ff03d191a.png)

**BBB version (optional):**
2.3-beta4

**Desktop (please complete the following information):**
Not browser related I feel like. I used current FF on Win10 for mod, current Chrome on Win10 for Clients

**Additional context**
Sometimes the red warning message that chat is locked is also not shown. I couldn't reproduce it reliably though.

**Comment by PlumedArcher** [comment]
After switching from private to public chat it was messed up only once for me. (although not all messages got deleted)
![Screenshot (819)2](https://user-images.githubusercontent.com/80673946/115222203-c4e4b580-a10a-11eb-9885-1d32389b4ecc.png)

What's always messed up, is the private chat though with huge gaps.

![Screenshot (818)2](https://user-images.githubusercontent.com/80673946/115222451-04ab9d00-a10b-11eb-9f6e-1ca9f85a3b03.png)

This is on 2.3 Beta 5 and Chrome on Windows 10.

**Comment by antobinary** [comment]
Looks like there is another way to reproduce:

2 users A and B,
lots of chat in public chat
user A tries to initiate private chat with user B
Then user A returns to public chat and public chat is empty, only [broken] welcome message

**Comment by antobinary** [comment]
@ramonlsouza do you think this is the same issue ^ ?

**Comment by ramonlsouza** [comment]
> @ramonlsouza do you think this is the same issue ^ ?

Yes, and it might not be related to locking... I'm able to trigger empty chat by:

- user A (moderator) and B (attendee) send messages in public chat
- user B initiate private chat with user A
- user A chat gets empty

no need to lock public chat or write anything in private chat
