### ISSUE TITLE
ICE 1007 in LAN

### ISSUE THREAD

**Issue by amini2425** [bigbluebutton/bigbluebutton#12067]
I installed BBB with a local Turn-Server which access users behind strict firewall.
Everything works well in WAN, but users in LAN face ICE 1007. 
I checked all settings and configurations with instructions and all of them are matched with best practice..
Could please help me about this issue?

**Comment by basisbit** [comment]
For support requests, please use the [forum / mailing list](https://groups.google.com/forum/#!forum/bigbluebutton-setup). This issue tracker here is only for BBB development related issues. Sorry.
