### ISSUE TITLE
Security/code quality status of /usr/share/bbb-libreoffice-conversion/convert-local.sh

### ISSUE THREAD

**Issue by ichdasich** [bigbluebutton/bigbluebutton#12066]
**Describe the bug**
`/usr/share/bbb-libreoffice-conversion/convert-local.sh` currently omits best practices in terms of input validation leading to shell escapes and least-permission settings. Furthermore, the tmp-directory creation might lead to race-conditions, and, in general, pathing is inconsistent, and set -e/-u are not used.

# Issues summary

## Potential shell escapes
`/usr/share/bbb-libreoffice-conversion/convert-local.sh` uses $1 and $2 in several places, directly passing to shell (e.g., l26 and l28). While technically no malicious input should reach this script (reencoding of filenames), it would be more best-practices compliant to ensure that this input is properly escaped, see: https://www.gnu.org/savannah-checkouts/gnu/bash/manual/bash.html#Shell-Parameter-Expansion 

## tmp dir creation
The tmp directory created in ll9-12 uses some self-rolled function. Instead, https://www.mktemp.org/ from coreutils should be used.

## Insecure permissions
Line 24 uses chmod 777 for the tmp directory. For obvious reasons this should more likely be 750, depending on the interaction with docker.

## Use of relative paths
Paths are used inconsistently, i.e., sudo with a relative path while docker is called with its absolute path. This makes the script susceptible to issues in env, i.e., `$PATH`. Either properly define `$PATH` or use absolute paths throughout the script.

## set -e/-u
It would be good if the script could use `set -e` (terminate upon failure of one pipeline) and `set -u` (do not run if not all used variables are defined). This obviously clashes with the current tmpdir creation.

**Expected behavior**
Script follows BCPs concerning shell scripting.

**Additional context**
The issues above are not directly security critical or functionally critical. Nevertheless, they introduce inconsistencies which may come biting one later on.

To illustrate an example:
- A future release has (accidentally) an API exposed that allows users to call the script with arbitrary parameters -> Remote shell as user bigbluebutton
- The lengthily discussed issues of systemd unit files -> elevate this to root

**Comment by ffdixon** [comment]
Thanks Tobias, we'll be making adjustments to this script based on your feedback.

**Comment by gustavotrott** [comment]
Everything fixed in #12083.

Thank you!

**Comment by antobinary** [comment]
Nice work @gustavotrott and thank you for reporting this @ichdasich !

I will merge the (now approved) PR 12083. I will keep this issue open for a day or two longer in case other items to address are still spotted.

**Comment by uka-support** [comment]
I took a quick look: it looks good and have a minor addition:

```
source=${1}
dest=${2}
```
should become
```
source="$1"
dest="$2"
```
In both convert-local.sh and convert-remote.sh.

Rationale: curly brackets are not required there (quote from manual: _"The braces are required when parameter is a positional parameter with more than one digit, or when parameter is followed by a character that is not to be interpreted as part of its name."_), but quotes should be used to protect against spaces in the file names.

**Comment by gustavotrott** [comment]
Good sugestion, thank you @uka-support!

PR #12163 will include this.
