### ISSUE TITLE
private Chat lock - Chat to Moderator

### ISSUE THREAD

**Issue by Superjamp** [bigbluebutton/bigbluebutton#12073]
**Describe the bug**
If you lock the private chat, participants will no longer be able send private messages to the moderators.

**To Reproduce**
1. Open meeting, join a moderator and a Participant
2. Moderator locks private chatting
3. Participant tries to write with a Moderator

**Expected behavior**
Participants can send private messages to moderators
or
hide the "Start a private Chat" Dropdown

**Actual behavior**
"Chat is locked, messages can't be sent" and Chat Box is disabled

**Screenshots**
![114688024-9898f580-9d14-11eb-8f4a-331c9d5e4894](https://user-images.githubusercontent.com/26893184/115207422-dffbf900-a0fb-11eb-928a-8f2a6c58bd84.png)
![114688034-9a62b900-9d14-11eb-8e17-1f7418191d1d](https://user-images.githubusercontent.com/26893184/115207426-e1c5bc80-a0fb-11eb-8705-be8933ea3d0a.png)
(reuploaded screenshots from #12019 only missing the "Chat is locked, messages can't be sent" message)

**BBB version (optional):**
BigBlueButton Server 2.3.0-beta-5 (2045)

**Desktop:**
 - OS: Linux Fedora 33
 - Browser Chrome
 - Version 89.0.4389.90

**Comment by PhMemmel** [comment]
Looks like 56c33ed36dc4a7f4239c035b119539e9a4956c80 interfered with my fix for that.
@ramonlsouza Can you have a look at it maybe? I could also try if you want me to. Thanks in advance.

**Comment by PhMemmel** [comment]
already found the problem, will send a PR asap
