### ISSUE TITLE
2.3.3 - Document conversion fails for Libreoffice documents

### ISSUE THREAD

**Issue by caniwi** [bigbluebutton/bigbluebutton#12071]
**Describe the bug**
Office documents, spreadsheets and presentations  bbb 2.3 beta5 fails to convert.

**To Reproduce**
1. Go to 'manage presentation'
2. Click on 'browse for files'
3. Select an Office document (ods, docx, xslx, odt, doc)
4. Click upload
5. Document conversion starts (the bbb-soffice docker container briefly runs)
6. See failed to convert document message. 

**Expected behavior**
Document gets converted and is able to be used as a presentation.

**Actual behavior**
A red cross displays in the pop describing the conversion and upload.  The manage presentation requires you to clear errors.
PDF's png and such work fine.
**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser Firefox
 - Version 87

**Smartphone (please complete the following information):**
 - Browser [e.g. stock browser, Safari]

**Additional context**
bbb-conf --version
default

BigBlueButton Server 2.3.0-beta-5 (2047)

ii  bbb-apps-akka                               2.3.0-70                                    all          BigBlueButton Apps (Akka)
ii  bbb-config                                  1:2.3.0-61                                  amd64        BigBlueButton configuration utilities
ii  bbb-etherpad                                1:2.3.0-47                                  amd64        The EtherPad Lite components for BigBlueButton
ii  bbb-freeswitch-core                         2:2.3.0-12                                  amd64        BigBlueButton build of FreeSWITCH
ii  bbb-freeswitch-sounds                       1:1.6.7-1                                   amd64        FreeSWITCH Sounds
ii  bbb-fsesl-akka                              2.3.0-41                                    all          BigBlueButton FS-ESL (Akka)
ii  bbb-html5                                   1:2.3.0-1617                                amd64        The HTML5 components for BigBlueButton
ii  bbb-libreoffice-docker                      1:2.3.0-45                                  amd64        BigBlueButton setup for LibreOffice running in docker
ii  bbb-mkclean                                 1:0.8.7-1                                   amd64        Clean and optimize Matroska and WebM files
ii  bbb-playback                                1:2.3.0-9                                   amd64        BigBlueButton playback
ii  bbb-playback-presentation                   1:2.3.0-9                                   amd64        BigBluebutton playback of presentation
ii  bbb-record-core                             1:2.3.0-30                                  amd64        BigBlueButton record and playback
rc  bbb-transcode-akka                          2.3.0-1                                     all          BigBlueButton Transcoder
ii  bbb-web                                     1:2.3.0-70                                  amd64        BigBlueButton API
ii  bbb-webrtc-sfu                              1:2.3.0-17                                  amd64        BigBlueButton WebRTC SFU
ii  bigbluebutton                               1:2.3.0-5                                   amd64        Open source web conferencing platform (bbb)
ii  ffmpeg                                      7:4.2.4-1ubuntu0.1bbb2~18.04                amd64        Tools for transcoding, streaming and playing of multimedia files
ii  libavcodec58:amd64                          7:4.2.4-1ubuntu0.1bbb2~18.04                amd64        FFmpeg library with de/encoders for audio/video codecs - runtime files
ii  libavdevice58:amd64                         7:4.2.4-1ubuntu0.1bbb2~18.04                amd64        FFmpeg library for handling input and output devices - runtime files
ii  libavfilter7:amd64                          7:4.2.4-1ubuntu0.1bbb2~18.04                amd64        FFmpeg library containing media filters - runtime files
ii  libavformat58:amd64                         7:4.2.4-1ubuntu0.1bbb2~18.04                amd64        FFmpeg library with (de)muxers for multimedia containers - runtime files
ii  libavresample4:amd64                        7:4.2.4-1ubuntu0.1bbb2~18.04                amd64        FFmpeg compatibility library for resampling - runtime files
ii  libavutil56:amd64                           7:4.2.4-1ubuntu0.1bbb2~18.04                amd64        FFmpeg library with functions for simplifying programming - runtime files
ii  libopusenc0                                 0.2.1-1bbb1                                 amd64        High-level API for encoding Ogg Opus audio streams
ii  libpostproc55:amd64                         7:4.2.4-1ubuntu0.1bbb2~18.04                amd64        FFmpeg library for post processing - runtime files
ii  libswresample3:amd64                        7:4.2.4-1ubuntu0.1bbb2~18.04                amd64        FFmpeg library for audio resampling, rematrixing etc. - runtime files
ii  libswscale5:amd64                           7:4.2.4-1ubuntu0.1bbb2~18.04                amd64        FFmpeg library for image scaling and various conversions - runtime files

**Comment by ffdixon** [comment]
Hi Doug,

> OS: Ubuntu 20.04

Are you sure you have the right OS -- it should be Ubuntu 18.04.

**Comment by caniwi** [comment]
My desktop is 20.04.  The server is 18.04.

**Comment by caniwi** [comment]
[bbb-web.log](https://github.com/bigbluebutton/bigbluebutton/files/6332581/bbb-web.log)


Web log from session attached.

**Comment by caniwi** [comment]
Having done some research, it appears that the directory structure built by /usr/share/bbb-libreoffice-conversion/convert-local.sh does not have sufficient permissions to create the output pdf from inside the container.  I managed to determine this by running the container interactively.  The conversion was failing to write the output file to the /data/ directory.  For me altering the /usr/share/bbb-libreoffice-conversion/convert-local.sh to include a chmod for the /tmp/bbb-libreoffice-conversion/$randomDirectoryName/.

**Comment by laserrapt0r** [comment]
I can't reproduce this with a fresh installation. Did you upgrade?

**Comment by caniwi** [comment]
yes it was an upgrade from 2.3 beta3

**Comment by antobinary** [comment]
Hi @caniwi 

Are you able to upload/convert this same document to test23.bigbluebutton.org <-- 2.3-beta5 server where I am able to convert docx, etc documents (will answer the question whether you perhaps hit a setup issue)
If you see it failing to convert, could you please try to upload/convert it to test.bigbluebutton.org <-- 2.2.36 server, it will answer the question of whether the specific document is problematic for BBB. We have a few GitHub issues in under development about this

**Comment by caniwi** [comment]
Hi Anton,
I can confirm that it is not the document.  I had to change some directory
permissions to allow the libreoffice docker  to write the output files.  I
updated the issue with what I did.

Found that /usr/share/bbb-libreoffice-conversion/convert-local.sh that runs
up the container and converts the document needed extra permissions on the
directory structure it uses for passing the file to be converted.

diff /usr/share/bbb-libreoffice-conversion/convert-local.sh
~/convert-local.sh
25a26
> chmod 777 "/tmp/bbb-libreoffice-conversion/$randomDirectoryName/"

**Comment by caniwi** [comment]
We have just upgraded to 2.3.0-rc-1.  We needed to perform the following:

diff   /usr/share/bbb-libreoffice-conversion/convert-local.sh /usr/share/bbb-libreoffice-conversion/convert-local.sh_orig
25c25
< chmod 777 $tempDir
---
> 

To get the libreoffice document conversion to work.

**Comment by laserrapt0r** [comment]
Are you using bbb-install.sh? Have you tried uninstalling and then reinstalling or just upgrading BBB?

**Comment by caniwi** [comment]
Hi,
I have just installed what appears to be 2.3.0 over top of 2.3.0-rc-1.  It required the same fix as detailed in my comment above.

bbb-conf --version
default

BigBlueButton Server 2.3.0 (2149)

ii  bbb-apps-akka                               2.3.0-78                                    all          BigBlueButton Apps (Akka)
ii  bbb-config                                  1:2.3.0-68                                  amd64        BigBlueButton configuration utilities
ii  bbb-etherpad                                1:2.3.0-48                                  amd64        The EtherPad Lite components for BigBlueButton
ii  bbb-freeswitch-core                         2:2.3.0-19                                  amd64        BigBlueButton build of FreeSWITCH
ii  bbb-freeswitch-sounds                       1:1.6.7-1                                   amd64        FreeSWITCH Sounds
ii  bbb-fsesl-akka                              2.3.0-46                                    all          BigBlueButton FS-ESL (Akka)
ii  bbb-html5                                   1:2.3.0-1669                                amd64        The HTML5 components for BigBlueButton
ii  bbb-libreoffice-docker                      1:2.3.0-53                                  amd64        BigBlueButton setup for LibreOffice running in docker
ii  bbb-mkclean                                 1:0.8.7-1                                   amd64        Clean and optimize Matroska and WebM files
ii  bbb-playback                                1:2.3.0-9                                   amd64        BigBlueButton playback
ii  bbb-playback-presentation                   1:2.3.0-9                                   amd64        BigBluebutton playback of presentation
ii  bbb-record-core                             1:2.3.0-31                                  amd64        BigBlueButton record and playback
rc  bbb-transcode-akka                          2.3.0-1                                     all          BigBlueButton Transcoder
ii  bbb-web                                     1:2.3.0-76                                  amd64        BigBlueButton API
ii  bbb-webrtc-sfu                              1:2.3.0-24                                  amd64        BigBlueButton WebRTC SFU
ii  bigbluebutton                               1:2.3.0-5                                   amd64        Open source web conferencing platform (bbb)
ii  ffmpeg                                      7:4.2.4-1ubuntu0.1bbb2~18.04                amd64        Tools for transcoding, streaming and playing of multimedia files
ii  libavcodec58:amd64                          7:4.2.4-1ubuntu0.1bbb2~18.04                amd64        FFmpeg library with de/encoders for audio/video codecs - runtime files
ii  libavdevice58:amd64                         7:4.2.4-1ubuntu0.1bbb2~18.04                amd64        FFmpeg library for handling input and output devices - runtime files
ii  libavfilter7:amd64                          7:4.2.4-1ubuntu0.1bbb2~18.04                amd64        FFmpeg library containing media filters - runtime files
ii  libavformat58:amd64                         7:4.2.4-1ubuntu0.1bbb2~18.04                amd64        FFmpeg library with (de)muxers for multimedia containers - runtime files
ii  libavresample4:amd64                        7:4.2.4-1ubuntu0.1bbb2~18.04                amd64        FFmpeg compatibility library for resampling - runtime files
ii  libavutil56:amd64                           7:4.2.4-1ubuntu0.1bbb2~18.04                amd64        FFmpeg library with functions for simplifying programming - runtime files
ii  libopusenc0                                 0.2.1-1bbb1                                 amd64        High-level API for encoding Ogg Opus audio streams
ii  libpostproc55:amd64                         7:4.2.4-1ubuntu0.1bbb2~18.04                amd64        FFmpeg library for post processing - runtime files
ii  libswresample3:amd64                        7:4.2.4-1ubuntu0.1bbb2~18.04                amd64        FFmpeg library for audio resampling, rematrixing etc. - runtime files
ii  libswscale5:amd64                           7:4.2.4-1ubuntu0.1bbb2~18.04                amd64        FFmpeg library for image scaling and various conversions - runtime files

**Comment by gustavotrott** [comment]
Hey @caniwi, 

Can you make a test?
Copy `/usr/share/bbb-libreoffice-conversion/convert-local.sh` to `/usr/share/bbb-libreoffice-conversion/convert.sh`

In the last `convert-local.sh` the temporary directory should be: `/tmp/bbb-soffice-bigbluebutton/`
![image](https://user-images.githubusercontent.com/5660191/117043027-141e0f00-ace3-11eb-903b-6dd37726b780.png)

This directory will be created by the `bigbluebutton` user and then the user will have owner permissions.
Can you check if this solve the problem?

**Comment by antobinary** [comment]
Looks like @ caniwi was able to resolve the issue for himself. Thank you @gustavotrott for following up!

If I understand this correctly, this issue could only happen for admins who had specific very early version on 2.3-alpha and then updated.
Please comment here if there are updates to this and we can reopen.

**Comment by caniwi** [comment]
I have just upgraded to 2.3.3 and this is still and issue.  To fix the issue I need to update the /usr/share/bbb-libreoffice-conversion/convert-local.sh script to add chmod 777 $tempDir after line 24.

**Comment by metlt** [comment]
BigBlueButton Server 2.3.14 
I made an edit in the file  /usr/share/bbb-libreoffice-conversion/convert-local.sh, but it didn't help me

**Comment by antobinary** [comment]
Let's reopen if this is reproducible on BBB 2.4.4+

**Comment by caniwi** [comment]
Hi Anton,

It is still there in 2.4.4

**Comment by ffdixon** [comment]
To narrow this down, 
  1. Did you do a clean install of 2.4 (no previous version of BigBlueButton on the server) or an upgrade from a previous version.  
  1. Did you use `bbb-install.sh`?

**Comment by caniwi** [comment]
Hi Fred,

It was a clean install of 2.4 as we are perfoming blue-green deployments
now.  So we don't use bbb-install.sh.  We use puppet to manage the
configuration of bigbluebutton.

**Comment by ffdixon** [comment]
I would recommend doing a clean install of BigBlueButton 2.4 using `bbb-install.sh` and see if document conversion works.  

If so, you'll have two servers that should be very close to each other, but some configuration/permission is causing the issue with your server.

By comparing your server with a working server, you should be able to slowly make it identical to the working server -- testing after each change.  At some change, the conversion should start working again and you'll have found the configuration/permission issue.
