### ISSUE TITLE
Mobile Audio depends on first choice on "how to join the conference"

### ISSUE THREAD

**Issue by PlumedArcher** [bigbluebutton/bigbluebutton#12076]
**Describe the bug**
If I join on my device with "listen only", I can hear everything fine. Afterwards I can connect my microphone and I am still able to hear all the audio.
However, if I join directly with microphone, from that point on there is no audio for the rest of the session. (except Video audio), although I can still see the names and the talking symbols.

So everything depends on the first choice here. If you close that window, you are not able to hear anything until you click "start audio" and then "listen only". If you join with microphone, again, you are not able to hear anything, so it's the same behavior, just delayed.

**To Reproduce**
1. Join a conference with microphone. 
2. From that point on, there is no audio (even in the echo test, your own words can't be heard)

**Expected behavior**
Being able to also hear audio

**Actual behavior**
no audio

**BBB version (optional):**
BBB 2.3-beta5 client 1617 (most recent testserver)

**Smartphone (please complete the following information):**
 - Device: Motorola G7 Power
 - OS: Android-Version 10
 - Browser Chrome
 - Version 89.0.4389.105

**Additional context**
Microphone still works fine, other people are able to hear me when I talk.
It works perfectly fine with Motorola G8 Power, could not test on other devices.

**Comment by antobinary** [comment]
Hi! Are you able to reproduce this on https://test23.bigbluebutton.org/demo/demo2.jsp ?

(if you join with 2 clients in the same meeting)

**Comment by PlumedArcher** [comment]
Hi, i could somewhat reproduce. I must say, that the behavior was a little bit different in the last few minutes. It did no longer depend on the first choice, but on the moment I try to connect my mircophone the first time (even if i cancel immediately). Audio just works until that point, I can no longer reproduce joining successfully with microphone after I started with "listen only".
 (The same difference is now observable on the test server as well. After I joined with "listen only", the mircophone does no longer work when I now try to connect it.  Somehow I can't reproduce this 'old' behavior anymore).

**Comment by mariogasparoni** [comment]
This may be related to #11458.
So, as far i understood you are to reproduce this problem happens in moto g7 only , right ?

**Comment by mariogasparoni** [comment]
I see, but you were able to were able to reproduce it in moto g7 , right ? Just wanna make sure the following info wasn't a typo:
>**Smartphone (please complete the following information):**
>
>   - Device: Motorola G7 Power
>    - OS: Android-Version 10
> ...

**Comment by PlumedArcher** [comment]
Yes, I am able to reproduce the bug in moto g7 each time. (not the fixed audio after i first joined with "listen only" though. I am not sure what caused it to work at first, but now I always lose the audio after i tried to connect the microphone)

**Comment by ffdixon** [comment]
Could you reproduce this issue on https://demo.bigbluebutton.org/ (which is running 2.4.1)?
