### ISSUE TITLE
Missing button template in the guide: "HTML5 Best Practices"

### ISSUE THREAD

**Issue by skchande** [bigbluebutton/bigbluebutton#12070]
**Describe the bug**
The coding practice states, that I can should a default button (template) which I could use for some changes in the program. But the button which should be located inside of` /imports/ui/shared/Button.jsx` does not exist in the code.

Here is the link to the guide:
https://docs.bigbluebutton.org/html5-best-practices.html#buttons

Here is the link to the code:
https://github.com/bigbluebutton/bigbluebutton/tree/develop/bigbluebutton-html5/imports/ui

**Expected behavior**
I expected a small coding example to add a button or something similar after reading the headline "HTML5 Coding Practices" here:
https://docs.bigbluebutton.org/2.2/dev.html#html5-coding-practices

**Actual behavior**
Just got some coding conventions with missing button template.

**BBB version (optional):**
BigBlueButton Server 2.2.36 (2406)

Regards
skchande

**Comment by antobinary** [comment]
For the record, in 2.4.0 I am redirected to https://bigbluebutton.org/teachers/tutorials/
