### ISSUE TITLE
Wrong ID when creating breakout rooms via the API

### ISSUE THREAD

**Issue by Kibusch** [bigbluebutton/bigbluebutton#12084]
**Describe the bug**
In the case of breakout rooms created by the API, the ID is not known to the server. As a result, it is not possible to retrieve the detailed meeting information of the breakout room, join the breakout room through the API or terminate the breakout room through the API. The breakout room is assigned to the parent room with the meetingID and also appears there in the result of the request. For breakout rooms created by Greenlight, the API works to join the breakout room and also the meeting information. I suspect by comparing the result of the two requests in the meeting room, that possibly the internal and external ID are confused and it comes to errors in the room assignment.

**To Reproduce**
1. Creating a main room with the API
2. Creating a breakout room associated with the main room
3. Joining the breakout room or requesting detailed meeting information via the API -> Does not work.

**Expected behavior**
Breakout rooms are created neatly through the API, assigned to the parent room, and are accessible through the API.

**Actual behavior**
Breakout rooms are created via the API and assigned to the parent room. Unfortunately, however, due to the ID not being known to the server, access or calling detailed information is not possible.

**Screenshots**
Main room:
`"meetingID": "fgfctooy5gfqawmphbare701rfzu5jjnqz0p2ohi",
"internalMeetingID": "4b5cfa4a1cfd809a4f290277e14cb3d9767315f7-1618850042415",`

Breakout room:
`"meetingID": "85ab78573f6c07bdb577baf6a530c1a1d3307c8f-1618850057519",
"internalMeetingID": "fbcbdf388a7d8f191a4252c0d64b6874c7e910b1-1618850057519",`

These two rooms were created by Greenlight and work fine.

Main room:
`"meetingID": "f01caa23-fa1a-4636-b1c4-50d23edc9b36",
"internalMeetingID": "cbb772cab5f73c8ee975e997e57f91e271c197c7-1618853899503",`

The main room can be joined via API and information about the API can be obtained via ID.

Breakout room:
`"meetingID": "5938a476aad5f7ad471d6c4be52bc92e5fb7972e-",
"internalMeetingID": "test1234",`

Here, "test1234" was stored in the call via API, i.e. ID. Therefore the assumed wrong assignment. Also, no information can be retrieved via API for this breakout room, the room can be terminated via API or the room can be added via API.

These two rooms were created by the API and unfortunately do not work as expected.

```
2021-04-19T17:24:29.427+02:00 DEBUG o.b.web.controllers.ApiController - ApiController#create
2021-04-19T17:24:29.427+02:00 DEBUG o.b.web.controllers.ApiController - [isBreakout:[true], parentMeetingID:[cbb772cab5f73c8ee975e997e57f91e271c197c7-1618845834994], sequence:[1], duration:[30], maxParticipants:[2], name:[bXEk0vS2pxXtEci], meetingID:[], checksum:[02210f9df48523b985d7a34701ffb1bfc0188a65]]
2021-04-19T17:24:29.428+02:00 DEBUG o.b.web.controllers.ApiController - ApiController#invalid You must specify a meeting ID for the meeting.
2021-04-19T17:24:49.169+02:00 DEBUG o.b.web.controllers.ApiController - ApiController#create
2021-04-19T17:24:49.169+02:00 DEBUG o.b.web.controllers.ApiController - [isBreakout:[true], parentMeetingID:[cbb772cab5f73c8ee975e997e57f91e271c197c7-1618845834994], sequence:[1], duration:[30], maxParticipants:[2], name:[T315hOMjHhqFTnB], meetingID:[test], checksum:[70e4592a3b6996d4a8ef024572d907e57dd143d9]]
```

Perhaps in conclusion. The bbb-web.log shows that it could not find a MeetingID.

I hope you got a proper idea of the error and what this could be due to. Unfortunately, I can't figure out anything from the various data.

Forgot the Version: 2.2.

**Comment by schrd** [comment]
can you reproduce this on a 2.3 server?

**Comment by Kibusch** [comment]
So far only tested with version 2.2. Since we already use BigBlueButton partially with the basic functions productively for events, I first have to set up a new server in the short term to be able to test it. I'll let you know as soon as I've done it.

Is version 2.3. already suitable for productive purposes? The API is intended to take our events to a new level with the help of an automatic matching and an automatic classification of the users.

**Comment by Kibusch** [comment]
Completely reinstalled the server this morning and provided it with version 2.3. Installation worked and also via Greenlight and the API demo was a room to enter. Unfortunately, the error also occurs in the version 2.3. as can be seen from the output.

For the main room the following MeetingID was passed: 57250e40-0817-49bb-b8ea-5823d7847b28 this was also inserted correctly. For the group room, the MeetingID test1234 was passed, which was again saved as an internal ID. Calling or entering the group room does not work as in version 2.2.

```
{
    "returncode": "SUCCESS",
    "meetings": [
        {
            "meetingName": "kTxgqNmaBD6WwSl",
            "meetingID": "7b98c5f5aae8333dafd843f5204b906740fd18aa-",
            "internalMeetingID": "test1234",
            "createTime": 1618991197192,
            "createDate": "Wed Apr 21 09:46:37 CEST 2021",
            "voiceBridge": 72781,
            "dialNumber": "613-555-1234",
            "attendeePW": "GvOm62tH",
            "moderatorPW": "JnoP2OHU",
            "running": false,
            "duration": 30,
            "hasUserJoined": false,
            "recording": false,
            "hasBeenForciblyEnded": false,
            "startTime": 1618991197287,
            "endTime": 0,
            "participantCount": 0,
            "listenerCount": 0,
            "voiceParticipantCount": 0,
            "videoCount": 0,
            "maxUsers": 2,
            "moderatorCount": 0,
            "attendees": "",
            "metadata": "",
            "isBreakout": true,
            "parentMeetingID": "895490861766cea7710e02c9ea470b0a0b7e7ab4-1618991176816",
            "sequence": 1,
            "freeJoin": false
        },
        {
            "meetingName": "RsgSbLXOrRiyujs",
            "meetingID": "57250e40-0817-49bb-b8ea-5823d7847b28",
            "internalMeetingID": "895490861766cea7710e02c9ea470b0a0b7e7ab4-1618991176816",
            "createTime": 1618991176816,
            "createDate": "Wed Apr 21 09:46:16 CEST 2021",
            "voiceBridge": 89317,
            "dialNumber": "613-555-1234",
            "attendeePW": "JU3BIzGJ",
            "moderatorPW": "3OY2OORP",
            "running": false,
            "duration": 0,
            "hasUserJoined": false,
            "recording": false,
            "hasBeenForciblyEnded": false,
            "startTime": 1618991178870,
            "endTime": 0,
            "participantCount": 0,
            "listenerCount": 0,
            "voiceParticipantCount": 0,
            "videoCount": 0,
            "maxUsers": 0,
            "moderatorCount": 0,
            "attendees": "",
            "metadata": "",
            "isBreakout": false,
            "breakoutRooms": {
                "breakout": "7b98c5f5aae8333dafd843f5204b906740fd18aa-"
            }
        }
    ]
}
```

**Comment by basisbit** [comment]
"group room", do you mean "breakout room"?

**Comment by Kibusch** [comment]
> "group room", do you mean "breakout room"?

Oh sorry. Yes, I mean "breakout room"

**Comment by JoachimLaviolette** [comment]
Do you guys know if any fix was done for this issue?
