### ISSUE TITLE
Audio menu does not display Leave Audio choice

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#12089]
**Describe the bug**
When zoomed in the browser at 125%, the audio chooser has a scroll bar which obscures the leave audio.

**To Reproduce**
1. Set Chrome to 125% zoom
2. Join a BigBlueButton 2.3 session
3. Join audio
4. Click the headset icon to leave audio

**Expected behavior**
All the menu choices are displayed without word wrapping

**Actual behavior**
The menu is too narrow and causes the scroll bar to appear

**Screenshots**
![image](https://user-images.githubusercontent.com/290351/115316025-e8315400-a14e-11eb-805f-dd1b0a142e34.png)

**BBB version (optional):**
Latest build of BigBlueButton 2.3 + latest Chrome

**Comment by mariogasparoni** [comment]
Possibly related to #12320

**Comment by antobinary** [comment]
I'll reopen this issue because the width control is only one part of the solution.

There is an effort to improve the  UX of the entire menu, after which the Leave audio will be 1 click away
