### ISSUE TITLE
Public Chats don't load

### ISSUE THREAD

**Issue by Rahimimojtaba** [bigbluebutton/bigbluebutton#12094]
In BBB nodes with more than 100 users and specially in a sessions with more than 30+ or 50+ users, after some while, when new users attend to session, they can't see the previous public chats. It show loading: 25% or sometime different numbers and never load the previous chats.

**To Reproduce**
On a BBB node with more than 100+ users, create a session with more that 30+ attendees, then join to the session with new user and you'll see that the chats will not load properly and you can't see the previous messages. Only Welcome message will appear for you.

**Expected behavior**
The previous chats should be load for new attendees.

**Actual behavior**
New attendees can't find the previous public chats. Only see the loading message.

**Screenshots**
![image](https://user-images.githubusercontent.com/10870269/115444784-517b9a80-a215-11eb-9d91-ded54cb95142.png)

**BBB version (optional):**
BigBlueButton Server 2.3-beta5

**Desktop (please complete the following information):**
 - OS: Windows, iOS, Android
 - Browser: Chrome, FireFox and Safari
 - Version all latest version

**Additional context**
Keep in mind that this problem will not show itself on the servers with low volume of users.

**Comment by basisbit** [comment]
@Rahimimojtaba could you please add logs of bbb-html5 from when these problems happened? Simply just having more than 150 users in a meeting seems to not be enough to reproduce your problem.

**Comment by Rahimimojtaba** [comment]
@basisbit Thanks for your follow up. Would you please let me know where can I find bbb-html5 logs? I checked /var/log/bigbluebutton/html5 and also /var/log/nginx/html5-client.log, both was empty. I also checked the browser console and there wasn't any issue there. Still can't load the previous public chats.
I also can provide your direct access. If you arrange a fixed time, we can go online and check together on the server.

**Comment by antobinary** [comment]
Hi @Rahimimojtaba the logs from bbb-html5 would be found via `sudo journalctl -u bbb-html5-*` but they "rotate" daily on the servers I have access to. When I look for server logs from previous days, I parse `/var/log/syslog*`.
But for this particular issue, the client logs might be more interesting. Have you enabled logging from client to server? https://docs.bigbluebutton.org/2.2/customize.html#send-client-logs-to-the-server

**Comment by djtilo-ol** [comment]
@antobinary, @basisbit, @Rahimimojtaba 
I am consistently able to reproduce the issue on my bbb23-rc-1 installation. We start our rooms through Moodle & NextCloud and it happens to both. The room itself does not have to be populated, I encounter the error even if I log in a second time after having typed sth. into the chat, but there is a load on the server of 200 concurrent users at the time.
I have checked the console and could not detect anything that would hint at the problem, I'll add a screenshot.
(Un)fortunately I do not have activated logrotation, yet, so I have a
<img width="1437" alt="Bildschirmfoto 2021-04-27 um 10 16 17" src="https://user-images.githubusercontent.com/81173481/116209366-21b32200-a742-11eb-8347-7781c6351fcb.png">
ctually full access to logs dating back to 19th April.
If I paste `sudo journalctl -u bbb-html5-*` I get a very long list, obviously, how can I narrow it down or jump to the time, i.e. 27th April 10:10? I'm sorry that I am not that capable at searching the logs, trying to resolve the issue.
I'll try activating logging from client to server tonight.
Cheers, John Alistair

**Comment by antobinary** [comment]
>but there is a load on the server of 200 concurrent users at the time.

Thank you very much for this crucial piece of info!
This helped @Tainan404 reproduce and fix. Should be available shortly via 2.3-rc-2
