### ISSUE TITLE
npm start is giving error.

### ISSUE THREAD

**Issue by Ankit949** [bigbluebutton/bigbluebutton#12090]
I'm trying to develop HTML5 client from documentation  ### https://docs.bigbluebutton.org/2.2/dev.html
while running npm start I'm getting 

[](url)
> start
> if test "$NODE_ENV" = "production" ; then npm run start:prod; else npm run start:dev; fi

> start:dev
> ROOT_URL=http://127.0.0.1/html5client NODE_ENV=development meteor

[[[[[ ~/dev/bigbluebutton/bigbluebutton-html5 ]]]]]

=> Started proxy.
Unexpected mongo exit code 14. Restarting.
=> A patch (Meteor 1.8.1) for your current release is available!
   Update this project now with 'meteor update --patch'.
Unexpected mongo exit code 14. Restarting.
Unexpected mongo exit code 14. Restarting.
Can't start Mongo server.
Unspecified unrecoverable error. Exit was not clean

This ERROR . Please help me to resolve this issue.

**Comment by prlanzarin** [comment]
This is not the place to debug setup issues.

Check the [mailing lists](https://docs.bigbluebutton.org/2.2/getting-help.html) instead.

**Comment by antobinary** [comment]
@Ankit949 
https://groups.google.com/g/bigbluebutton-dev
Direct link to the Developers mailing list

(the link above seems to point elsewhere)

**Comment by prlanzarin** [comment]
> (the link above seems to point elsewhere)

https://docs.bigbluebutton.org/2.2/getting-help.html#help-developing-bigbluebutton

**Comment by ksnandhan** [comment]
> I'm trying to develop HTML5 client from documentation ### https://docs.bigbluebutton.org/2.2/dev.html while running npm start I'm getting
> 
> > start
> > if test "$NODE_ENV" = "production" ; then npm run start:prod; else npm run start:dev; fi
> 
> > start:dev
> > ROOT_URL=http://127.0.0.1/html5client NODE_ENV=development meteor
> 
> [[[[[ ~/dev/bigbluebutton/bigbluebutton-html5 ]]]]]
> 
> => Started proxy. Unexpected mongo exit code 14. Restarting. => A patch (Meteor 1.8.1) for your current release is available! Update this project now with 'meteor update --patch'. Unexpected mongo exit code 14. Restarting. Unexpected mongo exit code 14. Restarting. Can't start Mongo server. Unspecified unrecoverable error. Exit was not clean
> 
> This ERROR . Please help me to resolve this issue.

Did you resolve this issue?

**Comment by chetanakashV** [comment]
> > I'm trying to develop HTML5 client from documentation ### https://docs.bigbluebutton.org/2.2/dev.html while running npm start I'm getting
> > > start
> > > if test "$NODE_ENV" = "production" ; then npm run start:prod; else npm run start:dev; fi
> > 
> > 
> > > start:dev
> > > ROOT_URL=http://127.0.0.1/html5client NODE_ENV=development meteor
> > 
> > 
> > [[[[[ ~/dev/bigbluebutton/bigbluebutton-html5 ]]]]]
> > => Started proxy. Unexpected mongo exit code 14. Restarting. => A patch (Meteor 1.8.1) for your current release is available! Update this project now with 'meteor update --patch'. Unexpected mongo exit code 14. Restarting. Unexpected mongo exit code 14. Restarting. Can't start Mongo server. Unspecified unrecoverable error. Exit was not clean
> > This ERROR . Please help me to resolve this issue.
> 
> Did you resolve this issue?

I'm also getting this same issue, was it resolved
@ksnandhan
