### ISSUE TITLE
unify button style in "viewer rights"

### ISSUE THREAD

**Issue by mrkeksi** [bigbluebutton/bigbluebutton#12106]
With a little rewording, you could unify the buttons as in the settings. This would also improve the mobile view. ERemove the locked and unlocked and put it in the button.

What it looks like at the moment:
![image](https://user-images.githubusercontent.com/8763656/115761359-8e28cc80-a3a2-11eb-9211-a888718d1c14.png)
How I think it should look:
![image](https://user-images.githubusercontent.com/8763656/115761814-0c856e80-a3a3-11eb-93a8-3374a518693c.png)

So it looks more uniform as in the settings
![image](https://user-images.githubusercontent.com/8763656/115762057-566e5480-a3a3-11eb-9008-72effa76a79f.png)

**Comment by mrkeksi** [comment]
Sorry. This was just quickly created. Is it more understandable now?

**Comment by antobinary** [comment]
Yes, thanks! I see your point. I recall we had to revisit this area because what we had before was not clear enough, but I do not recall all the details. I will ask @tylercopeland to comment on how he sees things too.

**Comment by tylercopeland** [comment]
@mrkeksi thank you for sharing your feedback. I like your recommendation as it provides consistency in our product. @antobinary, I'm happy to move forward with this update.

**Comment by antobinary** [comment]
Thanks @tylercopeland !

**Comment by mrkeksi** [comment]
I'm going to close this here because of the decision to outsource the labels. #12230
