### ISSUE TITLE
Remove or hide Whiteboard as presentator for all users

### ISSUE THREAD

**Issue by joo4mart** [bigbluebutton/bigbluebutton#12103]
**Is your feature request related to a problem? Please describe.**
If many people want to discuss together they don't need the whiteboard. But it always exist and earch user must hide it yourself. It is escpecially a huge problem if you give sport lessons for kids.

**Describe the solution I would like**
The best would be a switch in the configuration to turn off or disable the whiteboard at startup. But if someone upload a new document (pdf or similar) the whiteboard appears.

**Describe alternatives you've considered**
Another way would be about the choice of documents/presentations to select "no presentation".
A third way could be an icon at the top right corner (only for the presenter) to hide the whiteboard for all users.

**Additional context**
Perhaps these feature could also be supported by greenlight.

**Comment by mrkeksi** [comment]
Is this related to 2.3? (There it really doesn't work anymore) In 2.2 there is currently a trick you can do to get the presentation away from everyone: 
- Upload a new presentation
- edit the presentations again and remove the green check mark of the active, uploaded presentation
 
![image](https://user-images.githubusercontent.com/8763656/115551414-512dde80-a2ab-11eb-8432-f74beb42f161.png)

**Comment by joo4mart** [comment]
Similar to Zoom or MS-Teams it would be nice to remove the Whiteboard for all users to only see the users on the whole surface. Perfectly for discussions.

**Comment by easy-bios** [comment]
This one needs more attention since 2.3 doesn't allow removal of last presentation any more.
Never had any issues if I just removed it from the "Manage Presentations" menu but now it is disabled.
