### ISSUE TITLE
beta 2.3,  uploading .odp presentations messes up character spacing in conversion

### ISSUE THREAD

**Issue by JustinMogel** [bigbluebutton/bigbluebutton#12118]
**Describe the bug**
after uploading and converting a openoffice presentation (.odp), some characters are spaced incorrectly (slightly more space between characters) resulting in words being pushed in the next line

**To Reproduce**
1. prepare a .odp presentation with words going right to the end of the line in the textbox
2. upload presentation
3. see the sentence overflowing in the next line

**Expected behavior**
characters being converted correctly and spaced like in the preview in open office

**Actual behavior**
characters being spaced slightly more distant to each other resulting in more lines being used

**Screenshots**
left BBB, right open office 
![BBB präsentation schriftgröße](https://user-images.githubusercontent.com/80588280/115765194-bf0b0080-a3a6-11eb-8b85-c70297b55969.png)

**BBB version (optional):**
beta 2.3 (1617)
test23.bigbluebutton.org/b

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Firefox
 - Version 87.0 64bit

**Additional context**
converting to pdf and then uploading yields positive results and circumvents this issue

**Comment by JustinMogel** [comment]
tried again with "times new roman" and the font looks noticable different 

![BBB präsentation schriftgröße 2](https://user-images.githubusercontent.com/80588280/115769634-0c3da100-a3ac-11eb-8162-753129ff37ec.png)


maybe off topic but might be related:
Question: is it intentional, that a custom font gets replaced by a default one when uploading?

**Comment by joergmschulz** [comment]
This is the downside of the server side conversion. You only have some default fonts which may be quite different from what you have locally. If you convert to a .pdf locally and upload that pdf, you should have better results. Eventually, you'll need to include the fonts in the pdf.

**Comment by gustavotrott** [comment]
Hi @JustinMogel,
can you confirm which font you was using in the original presentation?

I tried creating a pres in OpenOffice with TimesNewRoman and I had good results:
![image](https://user-images.githubusercontent.com/5660191/115908143-288b1d80-a440-11eb-98ae-a715790043f9.png)
![image](https://user-images.githubusercontent.com/5660191/115908154-2c1ea480-a440-11eb-84d0-d9bbee8538e6.png)

Maybe I have different fonts in my Dev environment..

Can you please check the Libreoffice version and if TimeNewRomans is installed in libreoffice Docker?
```
sudo /usr/bin/docker run bbb-soffice sh -c "/usr/bin/soffice --version"

sudo /usr/bin/docker run bbb-soffice sh -c "fc-list | grep Times_New_Roman.ttf"
```
And let me know the results?

**Comment by GhaziTriki** [comment]
@JustinMogel Are you able to share the original uploaded file?

**Comment by JustinMogel** [comment]
When testing today, the conversion worked good and all pages were displayed as in OpenOffice
except page 1 (because of a custom font Street Ruler)

so i could not reproduce the behavior with version (1654)

Original Font for most of the pages was called Albany (seems to be some kind of default font used 
by OpenOffice which is not installed in windows itself)

Here the file i used to test:
[testpräsi.zip](https://github.com/bigbluebutton/bigbluebutton/files/6391845/testprasi.zip)

here the fonts how i could find them on my computer. (Times new Roman and Street Ruler (page 1))
[Fonts.zip](https://github.com/bigbluebutton/bigbluebutton/files/6391901/Fonts.zip)
[Street Ruler.zip](https://github.com/bigbluebutton/bigbluebutton/files/6391912/Street.Ruler.zip)

font Street Ruler can also be found here: https://www.1001freefonts.com/de/street-ruler.font

**Comment by gustavotrott** [comment]
> 
> 
> When testing today, the conversion worked good and all pages were displayed as in OpenOffice
> except page 1 (because of a custom font Street Ruler)
> 
> so i could not reproduce the behavior with version (1654)
> 
> Original Font for most of the pages was called Albany (seems to be some kind of default font used
> by OpenOffice which is not installed in windows itself)
> 
> Here the file i used to test:
> [testpräsi.zip](https://github.com/bigbluebutton/bigbluebutton/files/6391845/testprasi.zip)
> 
> here the fonts how i could find them on my computer. (Times new Roman and Street Ruler (page 1))
> [Fonts.zip](https://github.com/bigbluebutton/bigbluebutton/files/6391901/Fonts.zip)
> [Street Ruler.zip](https://github.com/bigbluebutton/bigbluebutton/files/6391912/Street.Ruler.zip)
> 
> font Street Ruler can also be found here: https://www.1001freefonts.com/de/street-ruler.font

Hi @JustinMogel ,
you will be able to install news fonts with last release `2.3.0`.

I tried the pres you attached!
I downloaded the font Street Ruler:
`wget https://github.com/bigbluebutton/bigbluebutton/files/6391912/Street.Ruler.zip`
`unzip Street.Ruler.zip`
then:

# Copy the font (.ttf) to /usr/share/fonts/
`sudo cp 'Street Ruler.ttf' /usr/share/fonts/`


## That's all! The font will be available on next presentations




![image](https://user-images.githubusercontent.com/5660191/117025881-ac12fd00-acd1-11eb-89bf-256b2bd87f7d.png)

**Comment by antobinary** [comment]
Thanks @gustavotrott for the instructions on adding custom fonts support! I just added them to the official BBB docs: https://docs.bigbluebutton.org/admin/customize.html#add-custom-fonts-for-presentation-conversion
