### ISSUE TITLE
2.3-beta5: Poll results on slide not properly styled for long answers

### ISSUE THREAD

**Issue by PhMemmel** [bigbluebutton/bigbluebutton#12111]
**Describe the bug**
If a poll contains a long answer poll results are rendered too small (unreadable).

**To Reproduce**
1. Initiate Poll
2. Insert a long answer (up to max character count)
3. Publish results
4. See results on slide: font size too small

**Expected behavior**
Readable rendering

**Actual behavior**
Font size far too small, not readable

**Screenshots**
![grafik](https://user-images.githubusercontent.com/65113153/115714704-b818c980-a377-11eb-828b-6886baf9394c.png)

**BBB version (optional):**
2.3-beta5

**Desktop (please complete the following information):**
tested on current FF, but probably browser independent

**Smartphone (please complete the following information):**
even worse, because it isn't even possible to zoom in onto the slide

**Additional context**
Has to be reconsidered if feature request in #12108 is being applied

**Comment by PlumedArcher** [comment]
Similar to  #6782.
