### ISSUE TITLE
Poll results disappear after minimizing the presentation

### ISSUE THREAD

**Issue by PlumedArcher** [bigbluebutton/bigbluebutton#12119]
**Describe the bug**
For everyone who has minimized the presentation during a poll, the results are not visible on the presentation after restoring

**To Reproduce**
1. Minimize the presentation
2. Start a poll
3. publish results
4. restore presentation
5. everyone who had minimized the presentation can't see the results on the presentation

**Expected behavior**
After restoring, the newest results should be visible there too. This leads to the point, that people don't see the same on their screens and might not get needed informations.

**Actual behavior**
Nothing changed.

**BBB version (optional):**
BBB 2.3 beta 5

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Google Chrome, Firefox

**Smartphone (please complete the following information):**
 - Device: Motorola g7 Power
 - OS: Android
 - Browser: Chrome
 

 - Same behavior on smartphones and regardless of moderator or attendees

![InkedScreenshot (843)_LI](https://user-images.githubusercontent.com/80673946/115772291-3775bf80-a3af-11eb-9ffd-8e71f1aff1da.jpg)

In the screenshot, only the user on the right didn't minimize the presentation

**Comment by JustinMogel** [comment]
refreshing the browser makes the poll results visible on the presentation again (same as when joining after the poll got published)
