### ISSUE TITLE
webcam selection doesn't show in 2.3

### ISSUE THREAD

**Issue by erichrueger** [bigbluebutton/bigbluebutton#12126]
**Describe the bug**
When enabling the webcam, the video starts without showing the camera-selection dialogue. On an system with multiple cameras, the default camera starts and can't be changed to another one. It is also impossible to change the video quality.
 
**To Reproduce**
1. enter a Room
2. click on the share camera button

**Expected behavior**
the camera selection dialogue opens

**Actual behavior**
the default camera starts 

**BBB version (optional):**
2.3 beta 5

**Desktop (please complete the following information):**
independent of OS

**Smartphone (please complete the following information):**
independent of device

**Comment by prlanzarin** [comment]
Please reproduce in test23.bigbluebutton.org.

**Comment by erichrueger** [comment]
It is working on your site. However, I am running a fresh installation. Is there any configuration file I should check?
-------- Ursprüngliche Nachricht --------Von: Paulo Lanzarin ***@***.***> Datum: 23.04.21  14:05  (GMT+01:00) An: bigbluebutton/bigbluebutton ***@***.***> Cc: erichrueger ***@***.***>, Author ***@***.***> Betreff: Re: [bigbluebutton/bigbluebutton] webcam selection doesn't show in 2.3 (#12126) 
Please reproduce in test23.bigbluebutton.org.

**Comment by prlanzarin** [comment]
Check whether one of these two is enabled in your server: https://github.com/bigbluebutton/bigbluebutton/blob/1416a0d255e4ebc43eb1f18594d85e92fcbb508e/bigbluebutton-html5/private/config/settings.yml#L270-L271

They should be disabled. Config file is either the overlay in /etc/bigbluebutton/bbb-html5.yml or /usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml.

Also check whether you have a front-end that's using the [following metadata](https://docs.bigbluebutton.org/2.2/customize.html#kurento-parameters): userdata-bbb_skip_video_preview, userdata-bbb_skip_video_preview_on_first_join. It shouldn't.

**Comment by erichrueger** [comment]
Thank you. Your advice helped me to solve the problem.

Am Fr., 23. Apr. 2021 um 14:27 Uhr schrieb Paulo Lanzarin <
***@***.***>:

**Comment by prlanzarin** [comment]
Sure. But next time, please prefer using the mailing lists for setup issues/debugging (https://bigbluebutton.org/community-support/).

**Comment by erichrueger** [comment]
Yes, I will do so. I was expecting a general error in BBB 2.3 beta 5 as the installation was new. I am sorry if I held you up.Thank you again for your help.
-------- Ursprüngliche Nachricht --------Von: Paulo Lanzarin ***@***.***> Datum: 23.04.21  15:51  (GMT+01:00) An: bigbluebutton/bigbluebutton ***@***.***> Cc: erichrueger ***@***.***>, Author ***@***.***> Betreff: Re: [bigbluebutton/bigbluebutton] webcam selection doesn't show in 2.3 (#12126) 
Sure. But next time, please prefer using the mailing lists for setup issues/debugging (https://bigbluebutton.org/community-support/).
