### ISSUE TITLE
bbb-conf not changing the server name with --setip in /etc/nginx/sites-available/bigbluebutton    (and other problems.)

### ISSUE THREAD

**Issue by D33M0N** [bigbluebutton/bigbluebutton#12127]
**Describe the bug**
sudo bbb-conf --setip something.something.com

```
...
Assigning something.something.com for servername in /etc/nginx/sites-available/bigbluebutton
...
```

does not set it correctly in this file (frankly, it does not alter the file at all). also the variable in nginx is server_name not servername

**To Reproduce**
1. sudo bbb-conf --setip something.something.com
2. sudo cat /etc/nginx/sites-available/bigbluebutton | grep something
3. nothing there. I should see at least one `server_name something.something.com;` line there. probably 2 for http and https

**Expected behavior**
new ip/name set in the /etc/nginx/sites-available/bigbluebutton file

**Actual behavior**
file remains unaltered

**Comment by D33M0N** [comment]
while on the subject, it doesn't even try to alter server IP/name in /usr/share/red5/webapps/sip/WEB-INF/bigbluebutton-sip.properties and then later with `bbb-conf --restart` complains something:
```
# Warning: The setting of 192.168.100.100 for bbb.sip.app.ip in
#
#    /usr/share/red5/webapps/sip/WEB-INF/bigbluebutton-sip.properties
#
# does not match the local IP address (172.16.100.100).
# (This is OK if you've manually changed the values to an external 
# FreeSWITCH server.)
```

**Comment by D33M0N** [comment]
While on the subject of `bbb-conf` the `Error: Unable to reach default URL for presentation` also fails unfairly, when the SSL certificate is self-signed. You use for detection `curl -sS url-and-filename`, but you should use `curl -sSk url-and-filename`.

```
$ curl -sS https://my.server.mydomain.intra/default.pdf
curl: (60) server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
```

**Comment by antobinary** [comment]
Thanks for reporting this!

**Comment by fireba11** [comment]
[2.3] I just tried to change a server name (to replace a 2.2 server with a new box with 2.3 so i got a rollback option).
bbb-conf --check
showed hostname not updated in
/usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties
/etc/nginx/sites-available/bigbluebutton

I ended up runnig install script again (and manually running certbot since it sumbled there) to change it.
Especially for ppl migration to 2.3 the "make a new box, test and then switch it via dns" seems like a good idea, so we should fix/document all issues with that.

**Comment by christmart** [comment]
We also see this problem in 2.3 and change it after each setip in the following files:
Servername in:
/etc/nginx/sites-available/bigbluebutton
Ip in:
/opt/freeswitch/etc/freeswitch/vars.xml
/opt/freeswitch/etc/freeswitch/sip_profiles/external.xml
/etc/bigbluebutton/nginx/sip.nginx
/usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml

**Comment by renatus** [comment]
It is by no means "stale", persisting in v.2.5, so shouldn't be closed.
