### ISSUE TITLE
No Audio Output with Bluetooth on Android

### ISSUE THREAD

**Issue by schewara** [bigbluebutton/bigbluebutton#12131]
**Describe the bug**
No Audio on Android with Bluetooth Headset

**To Reproduce**
1. Connect your Bluetooth Headset
2. Join the Room and choose any of the Audio options
3. No Audio Output, but microphone working

**Expected behavior**
When joining a Room with a Bluetooth Audio device connected, I would expect to hear the Audio Output on the Headset device

**Actual behavior**
When joining a room with an already connected headset, there is no audio output (Microphone and Listen only mode)
Restarting / Reconnecting the Headset while in the Room fixes the Problem
When logging out and joining again in Listen only mode leaves the Audio intact.
When joining again with Microphone breaks it again.

**BBB version (optional):**
2.3-beta-5

**Smartphone (please complete the following information):**
 - Device: multiple
 - OS: Android + LineageOS
 - Browser: Firefox
 - Version: 10

**Comment by basisbit** [comment]
Please report this problem to the LineageOS team. This is most likely not a bug in BigBlueButton. Could you test the similar use case with for example Jitsi - is it the same there? Also, can you reproduce this problem at https://test23.bigbluebutton.org/ ?

**Comment by schewara** [comment]
@basisbit : Thanks for your reply.
Yes I see the same behavior on the test instance.

I will try to test it with someone who has a regular Android to verify if this is really just related to LineageOS and will give you an update.

**Comment by schewara** [comment]
I was able to retest on a Stock version on a LG K52, with Android 10 and the preinstalled Chrome.
There I couldn't reproduce the issue,
Will close this issue therefore and see how this can be addressed otherwise.

@basisbit: Thanks again and have a good Day

**Comment by FreeScholar** [comment]
> Please report this problem to the LineageOS team. This is most likely not a bug in BigBlueButton. Could you test the similar use case with for example Jitsi - is it the same there? Also, can you reproduce this problem at https://test23.bigbluebutton.org/ ?

I have the same issue on a regular Android LG phone using the Brave browser. No audio with bluetooth. I am going to test on a few different instances of BBB, my hosts serve, the test.bigblue... and a demo server I suspect it may be a config issue on certain instances? Will post if I find anything useful.

**Comment by basisbit** [comment]
@FreeScholar this is no an issue of the BigBlueButton servers, but instead a problem of your LG phone. I'd suggest you to ask your vendor or LG for help, so that they fix their audio drivers, or ask the Brave browser developers, if the problem only happens with that web browser - try with Chrome or Firefox maybe.

**Comment by adam-op** [comment]
Allow me to ask a NEW question

does Bluetooth Headsets in Chrome work for ANY SAMSUNG MOBILE DEVICES ANDROID users (HTML5 client for BBB on Android 11 or 12) ? System and Chrome latest as of today
Device Samsung Galaxy Note 10

I would be really happy if someone helps to solve this
thank you for your time and effort

**Comment by mariogasparoni** [comment]
@adam-op 

It should work fine for all Samsung devices running latest Chrome, and Firefox browsers.

For Samsung's stock browser, it depends on which chromium version is being used to build it. Depending on the device and chromium version it won't work (see the link below)

There's a known bug related to some samsung devices. More info can be found here: https://github.com/bigbluebutton/bigbluebutton/issues/13008

**Comment by adam-op** [comment]
@mariogasparoni thank you for trying to help me here
I am willing to test / generate logs / ... 
I need this for my current job / it is super demotivating that it does not work
first of all, where is the documentation of that integration, i could read a little bit about what are the preconditions for bluetooth to work on android through chrome...
things as Bluetooth protocol Version, Android Versions, Browsers supported, as you know Samsung will not really help me here :)
I would be greateful if you link me to the OFFICIAL ANDROID DOCUMENTATION of BBB HTML5 where these are explained in details... I could not find it until now, too many companies on the globe who do more strong SEO than github BBB repo :)

**Comment by ant0nwax** [comment]
I have the same issue, no bluetooth Audio, on Android 12
