### ISSUE TITLE
Username including odd text omitted in polling response list

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#12138]
**Describe the bug**

**To Reproduce**
1. Join as ☕ username ☕ (copy unicode, perhaps from app)
2. 
![Screenshot from 2021-04-23 16-18-06](https://user-images.githubusercontent.com/6312397/115925685-8c691280-a44f-11eb-8ddc-55693f2f057d.png)

2. join as another user
3. the other user starts "user response" polling
3. ☕username☕ response to poll

**Expected behavior**
username : answer pair to be displayed at both voting live result, poll summary and poll annotation (upon publishing)

**Actual behavior**
The entire username for ☕username☕ including the coffee cups is omitted, see screenshots

**Screenshots**
![Screenshot from 2021-04-23 16-17-26](https://user-images.githubusercontent.com/6312397/115925617-6e9bad80-a44f-11eb-9b54-429a9a34f7b7.png)
![Screenshot from 2021-04-23 16-17-20](https://user-images.githubusercontent.com/6312397/115925618-6f344400-a44f-11eb-938c-7c7768f31c5e.png)

**BBB version (optional):**
BigBlueButton 2.3-beta5+ (develop from Fri April 23, 2021)

## Additional context
Might be related to https://github.com/bigbluebutton/bigbluebutton/pull/11687

**Comment by antobinary** [comment]
Looks like this omitting of username can affect other users too, see these screenshots:

![Screenshot from 2021-04-23 16-27-30](https://user-images.githubusercontent.com/6312397/115926500-f0400b00-a450-11eb-9bad-e3bd5ce240c2.png)
![Screenshot from 2021-04-23 16-27-15](https://user-images.githubusercontent.com/6312397/115926503-f0d8a180-a450-11eb-961a-4fc710ca8734.png)

**Comment by ramonlsouza** [comment]
Current behavior is the expected behavior (username only appears in live result, and not in chat/whiteboard annotation), and it's working for names with emoji

![live-1](https://user-images.githubusercontent.com/3728706/117650119-afd9d000-b166-11eb-9f57-775101966d7d.png) ![live-2](https://user-images.githubusercontent.com/3728706/117650124-b23c2a00-b166-11eb-921e-da748289b494.png)

**Comment by ramonlsouza** [comment]
@antobinary this issue can be closed (described behavior is not a bug)
