### ISSUE TITLE
getUserMedia failed in video-preview in Firefox

### ISSUE THREAD

**Issue by chfxr** [bigbluebutton/bigbluebutton#12148]
**Describe the bug**
Frontend cannot get Webcam in Firefox when "allow webcam for this domain" is checked

**To Reproduce**
1. Open a BBB meeting
2. Turn on Webcam
3. Set the tick on "remember for this domain"
4. Disconnect
5. Open a new BBB meeting
6. Turn on the webcam

**Expected behavior**
Webcam video will appear an no error will occur

**Actual behavior**
"Some problem occurred which prevented the device from being used"
Error message: `clientLogger: getUserMedia failed in video-preview https://XX.XX.XX/html5client/6c3e925c964755040758bdd12f06b4f7bd8007ff.js?meteor_js_resource=true:331:1221424`

**Screenshots**

**BBB version (optional):**
v2.3-beta-5, (1617-docker)

**Desktop (please complete the following information):**
- Firefox 85
- Ubuntu 18.04

**Smartphone (please complete the following information):**
None

**Additional context**

**Comment by prlanzarin** [comment]
@chfxr Are you able to reproduce this in test23.bigbluebutton.org?

**Comment by chfxr** [comment]
Yes its reproducible:
`ERROR: clientLogger: getUserMedia failed in video-preview https://test23.bigbluebutton.org/html5client/b07b1b653da23ab…a7ead7390e2b6e48a4c4f.js?meteor_js_resource=true:331:1230760`
![Screenshot_2021-04-25 BigBlueButton - Test Session (14654)](https://user-images.githubusercontent.com/64739555/116008885-0697c380-a617-11eb-828e-9fbcf78b68be.png)

**Comment by prlanzarin** [comment]
@chfxr Thanks. I'm going to ask for a second test: are you able to reproduce the problem here https://webrtc.github.io/samples/src/content/getusermedia/gum/? It's not BBB but the steps should be pretty much the same.

**Comment by chfxr** [comment]
@prlanzarin Works pretty fine, no problems at all.

**Comment by prlanzarin** [comment]
@chfxr

I can't reproduce the problem, neither in FF stable nor nightly (so not 85). So we need to find if there's anything non standard in your setup that's triggering the bug.

Do you have more than one camera device connected to your computer?

**Comment by chfxr** [comment]
@prlanzarin 
The problem doesn't occurs on my laptop.
Looks like there is a very seldom webcam hardware problem.

**Comment by SebastianBoldt** [comment]
Same Issue over here on my moms lenovo laptop.
