### ISSUE TITLE
Lobby management interface does not show up for moderator

### ISSUE THREAD

**Issue by pielonet** [bigbluebutton/bigbluebutton#12159]
**Describe the bug**
Lobby management interface does not show up for moderator when a user wants to join. So it is impossible to manually accept a user.

**Actual behavior**
Moderator hears a bell and a popup informs that a user wants to join. **Management interface shows up for a few seconds and then disappears**.

**BBB version (optional):**
BigBlueButton Server 2.3 RC1

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Firefox
 - Version 87

**Comment by pedrobmarin** [comment]
Hi @pielonet ,

Could you add more details on how to reproduce?
 - guest policy
 - user parameter (are you using the `guest` param?)
 - how is configured your bbb-web's `authenticatedGuest` property?
 - are you joining your users through greenlight? if so, could you try [API Mate](https://mconf.github.io/api-mate)?

**Comment by pielonet** [comment]
Hi @pedrobmarin ,

I inspected the console in the guest lobby page and found a Javascript error.

I found the issue : I had introduced a single quote in the French translation for the text "Please wait for a moderator to approve you joining the meeting." in the file `/usr/share/meteor/bundle/programs/server/assets/app/static/guest-wait/guest-wait.html` thus breaking a javascript string into pieces and breaking javascript code at the same time.

Replacing this quote with "&rsquo;" html entity did the trick.

Thanks for your support.

Kind regards,
Thierry
