### ISSUE TITLE
BBB 2.2: Presentation now showing (when using self-signed ssl certificate)

### ISSUE THREAD

**Issue by D33M0N** [bigbluebutton/bigbluebutton#12151]
**Describe the bug**
When I use self-signed cert for my internal test BBB installation, presentation's don't show.

(Everything else works. Audio; Video; Screen sharing; shared notes and public chat; even uploading presentations works and it does generate the thumbnails and SVG files and TXT files and everything to /var/bigbluebutton/<presentation_id>/...)
Just showing them on the web interface fails (slide selector even has right number of slides etc).

**To Reproduce**
1. install BBB
2. use self-signed SSL certificate
3. create presentation
4. See default.pdf not showing up.

**Expected behavior**
presentations are visible

**Actual behavior**
Only presentations are somehow lost.

**Screenshots**
![BBB_no_presentation2](https://user-images.githubusercontent.com/15782020/116075485-ae56d500-a69b-11eb-8a53-76164b066b21.png)

**BBB version (optional):**
BigBlueButton Server 2.2.36 (2416)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, Mac] Kubuntu 20.10
 - Browser [e.g. Chrome, Safari] Firefox
 - Version [e.g. 22] 87

**Additional context**
Everything works perfectly in Live installation (with proper CA certificate) -- test server is clone from live, just IP, name and cert changed.

**Comment by pedrobmarin** [comment]
https://nodejs.org/api/cli.html#cli_node_tls_reject_unauthorized_value

**Comment by D33M0N** [comment]
yes, well... where can I modify this then NODE_TLS_REJECT_UNAUTHORIZED=0 for BBB?
or make the node.js use actual server CA trusted certificates in /etc/ssl/certs/?

**Comment by pedrobmarin** [comment]
```
sudo systemctl status bbb-html5.service 
● bbb-html5.service - BigBlueButton HTML5 service
   Loaded: loaded (/usr/lib/systemd/system/bbb-html5.service; enabled; vendor preset: enabled)
   Active: active (running) since Mon 2021-04-26 12:09:17 UTC; 18s ago
 Main PID: 221 (systemd_start.s)
   CGroup: /system.slice/bbb-html5.service
           ├─ 221 /bin/bash -e /usr/share/meteor/bundle/systemd_start.sh
           └─1167 /usr/share/node-v8.17.0-linux-x64/bin/node --max-old-space-size=4096 --max_semi_space_size=128 main.js
```

How about trying it out at `/usr/share/meteor/bundle/systemd_start.sh`?

**Comment by D33M0N** [comment]
Thanks. Adding line there next to other exports:
`export NODE_TLS_REJECT_UNAUTHORIZED=0`
did work. However instead trying to use more secure:
`export NODE_EXTRA_CA_CERTS="/etc/ssl/certs/my_CA.pem"`
did not :-(

**Comment by AndNovAtor** [comment]
@D33M0N, your proplem is what I had, and "reported" as https://github.com/bigbluebutton/bigbluebutton/issues/10381.
Thx for @kaihen (but I don't try it yet), from "related" issue (1455):

> We just overwriting the `ca-certificates.crt` file in the docker container (similar to the way you did it):
> 
> ```
> services:
>   app:
>     volumes:
>       - ./ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt
> ```
> 
> We just added our CA certificate to the `ca-certificates.crt` file. That solved our greenlight problems with the self-signed cert.
> 
> The [issue](https://github.com/bigbluebutton/bigbluebutton/issues/10381) of AndNovAtor isn't a greenlight issue and can be solved by adding the `ca-certificates.crt` to `/usr/share/meteor/bundle/systemd_start.sh`:
> 
> ```
> #!/bin/bash -e
> export NODE_EXTRA_CA_CERTS=/etc/ssl/certs/ca-certificates.crt
> ```
> 
> We also needed to import the certificate to truststore of java for bbb by using following command:
> 
> ```
> keytool -import -alias CA -keystore /etc/ssl/certs/java/cacerts -file /etc/ssl/certs/CA.pem
> ```
>
