### ISSUE TITLE
BBB 2.3 RC1: Can't get cameras back on top after album orientation (mobile)

### ISSUE THREAD

**Issue by yvikt** [bigbluebutton/bigbluebutton#12157]
Android 10, Chrome 90
https://www.youtube.com/watch?v=DuAhauDMi_s&t=35s
Can't get cameras back on top after albom orientation.
And is it possible to make "border" between cameras and presentation visible to make resize process easier?

**Comment by prlanzarin** [comment]
From the mailing list:

> That's because you've resized the presentation viewport, which deactivates automatic positioning of webcams.
> And then webcam dragging is disabled on mobile, so you can't move them back. The problem here is that resizing
> shouldn't be enabled in mobile as well (at least that was always the approach since early 2.2), so the UA detection
> on that might have regressed (or someone might've changed the behavior).


So we have to figure out why resizing is enabled in mobile. If it's intentional, then we have to check whether moving cameras around in mobile is working as well. Both have to work simultaneously (or both have to be disabled in mobile, like it was in 2.2).

**Comment by JustinMogel** [comment]
could not reproduce this. after tilting back my phone, webcams were diplayed above the presentation again.
 - device: Motorola Moto G8 Power
 - OS: Android 10
 - Browser: Chrome, Brave

**Comment by prlanzarin** [comment]
Did you resize the camera viewport before trying to tilt it back?
