### ISSUE TITLE
408 Authentication Timeout - Joining private session

### ISSUE THREAD

**Issue by CamZie** [bigbluebutton/bigbluebutton#12167]
**Describe the bug**

Many users have problems joining a private session that has 90 users already listening, which results to the following 408 error. The dedicated server is not under a high load.

```
app.error.408
Authentication timeout
408
```

When reloading the page again we then received a 403 error, even if the Moderator has not removed any users
```
You have been removed from the meeting
User has an invalid sessionToken due to ejection
403
```

**To Reproduce**
1. Join session through a invitation link from Greenlight
2. Waiting for Moderator to accept my invitation
3. After Moderator has accepted, blue screen loading with 3 dots
4. See 408/403 errors above

**Expected behavior**
Can join sessions without timeouts via:` https://***REMOVED***/html5client/join?sessionToken=fvkag5j3x7macfzj`

**Actual behavior**
Cannot join sessions, causes timeouts and invalid Token if reloaded

**Screenshots**
![408_Timeout](https://user-images.githubusercontent.com/16030886/116212014-b454c080-a744-11eb-8565-ba4de57ce45b.png)
![403_error](https://user-images.githubusercontent.com/16030886/116212018-b61e8400-a744-11eb-929a-e5f76ead911d.png)

**Desktop (please complete the following information):**
 - OS: Linux / Windows / Mac OS
 - Browser: Chrome, Firefox
 - Version: e.g. Firefox 78.x, Chrome 89.x,

**Additional context**
On server logs we could not find any error, since the bbb-web.log outputs "Token is valid" even if we have received "Token is invalid" on the browser.

OS: Ubuntu 18.04
BBB version: 2.3.0-5

**Comment by XL-Maggus** [comment]
hello, 


we are facing the same errors... joining the waiting room via link end up in an 403 error
Ubutnu 18.04
BBB 1:2.3.0-7

**Comment by ffdixon** [comment]
Can you reproduce this error on 2.4 https://demo.bigbluebutton.org/?

**Comment by antobinary** [comment]
Let's reopen if needed

**Comment by mathmartins2** [comment]
same error here!
