### ISSUE TITLE
Kurento config IP address do not match the server IP address

### ISSUE THREAD

**Issue by GhaziTriki** [bigbluebutton/bigbluebutton#12166]
**Describe the bug**
In some cases the Kurento config IP address `externalIPV4` in `/etc/kurento/modules/kurento/WebRtcEndpoint.conf.ini` is not the the server IP. When it happens the webcams and screen-sharing do never start.

**Installation type**
Using `bbb-install`

**Firewall and IP address type**
No Firewall with IPv4.

**Console output**
none

**Additional context**
The issue happens when the A DNS entry of the BigBlueButton server has been changed and BigBlueButton is being installed on a new sever, the `externalIPV4` value contains the old IP address and the SSL certificate fails later to be generated.

**Suggested Solution**
- `bbb-conf` should have a check for that value `externalIPV4`, if provided it must warn if it does not match the IP address of the server.
- `bbb-install` should update the `externalIPV4` value with the right IP address (or in the packaging).

**Comment by prlanzarin** [comment]
If it's bbb-install related (and not bbb-conf), shouldn't the issue be in bbb-install's repo?

**Comment by laserrapt0r** [comment]
On my servers everything in this file is commented out. But as far as I can see bbb-install should alter this file and uncommend important lines and change the values. Am I right?

**Comment by coderDem** [comment]
Had the same problem. Wrote about here: https://groups.google.com/g/bigbluebutton-setup/c/VyJPDg63oOM
