### ISSUE TITLE
Presentation uploading toast is showing slide bar in RTL mode

### ISSUE THREAD

**Issue by GhaziTriki** [bigbluebutton/bigbluebutton#12168]
**Describe the bug**

**To Reproduce**
1. Change language to Arabic.
2. Upload a presentation.

**Expected behavior**
No slide bar should appear in the toast.

**Actual behavior**
A slide bar is shown in the toast.

**Screenshots**
![image](https://user-images.githubusercontent.com/4991088/116217433-8a4dcf00-a741-11eb-9e62-aae8ce7ee9dc.png)

**BBB version (optional):**
2.3-rc1

**Desktop (please complete the following information):**
 - OS: Win10 x64
 - Browser Firefox
 - Version 88.0 x64

**Comment by antobinary** [comment]
@JoVictorNunes are you able to reproduce this on 2.4.4+?

**Comment by JoVictorNunes** [comment]
@antobinary Yes. Reproducible on 2.4.4+. I'm sending a fix.
