### ISSUE TITLE
Break-out Rooms - Flashing Top Bar towards end of break-out session

### ISSUE THREAD

**Issue by peter-lernyx** [bigbluebutton/bigbluebutton#12175]
**Describe the solution you'd like**
Delegates regularly complain that break-out session end abruptly mid-sentence, not allowing them to complete their group work. Many delegates don't discover the timer on top of the screen until specifically told where to look for it. Suggestion:
Make the top bar with the timer change color (Yellow?) one minute before the end of the break-out session, start flashing yellow 30 seconds before end of session, flash red 10 seconds before end of session.

Edit:

Additionally, with Break-out teams in-session, allow admin to increase breakout session timer in 1-minute increments from main-room break-out session panel.

**Comment by antobinary** [comment]
Merging into https://github.com/bigbluebutton/bigbluebutton/issues/10991
