### ISSUE TITLE
[RC2] chatWelcomeMessageText height 

### ISSUE THREAD

**Issue by mrkeksi** [bigbluebutton/bigbluebutton#12178]
**Describe the bug**
chatWelcomeMessageText has max height 599px? and will overflow with new chat messages.

**To Reproduce**
1. set a long Welcome Message
2. write something in the chat
3. reload page
4. write more in the chat

**Screenshots**
![image](https://user-images.githubusercontent.com/8763656/116295506-746bf880-a799-11eb-9ddb-74e1d631e8ed.png)

**BBB version (optional):**
2.3 RC2

**Desktop (please complete the following information):**
Windows Chrome 90

**Comment by lonesomewalker** [comment]
I think the chat thing is still a mess, also refer to #12130 
Seems something has to be checked really thoroughly...

**Comment by antobinary** [comment]
#14023 should be resolving this fully as part of the upcoming BBB 2.4.1
