### ISSUE TITLE
[2.3] - Change recording processing time 

### ISSUE THREAD

**Issue by Hamid-Najafi** [bigbluebutton/bigbluebutton#12186]
In BBB 2.2, we could add bbb-rap-starter.timer.d according to this page:
https://docs.bigbluebutton.org/2.2/customize.html#change-processing-time

since that recording services had some changes in 2.3, how we can set the timer for that?

**Comment by mori5ive** [comment]
Hi hamid Jan :)
I use this way and work it on bbb 2.3
crontab -e

Add the following entries
Stop recording at 7 AM during week days
00 7 * * 1-5 systemctl stop bbb-rap-starter.service bbb-rap-resque-worker.service
Start recording at 13:30 PM during week days
30 13 * * 1-5 systemctl start bbb-rap-starter.service bbb-rap-resque-worker.service
