### ISSUE TITLE
Disable the audio beeps and maybe the animation when using the selectRandomUser feature or make it configurable.

### ISSUE THREAD

**Issue by christmart** [bigbluebutton/bigbluebutton#12193]
**Describe the bug**
When using the selectRandomUser feature an animation with different usernames and a countdown is displayed with extremly disturbing sounds for each displayed username. The sounds and the countdown animation should be configurable to disable. Also displaying the user names to other users could be a privacy issue, if displaying the user names in the user list is disabled.

**To Reproduce**
Use selectRandomUser and watch the reaction

**Expected behavior**
There should be an option to disable the sounds and maybe also the animation. 

**Actual behavior**
While the animation of the user shuffle is displayed for each user a sound is played. This cascade of sounds is disturbing.

**BBB version (optional):**
BigBlueButton Server 2.3.0-rc-2 (2121)

**Comment by antobinary** [comment]
In progress - this is being addressed in https://github.com/bigbluebutton/bigbluebutton/pull/12169

**Comment by antobinary** [comment]
Resolved in #12169
