### ISSUE TITLE
First audio join in breakout room fails

### ISSUE THREAD

**Issue by freddyertl** [bigbluebutton/bigbluebutton#12190]
With the following in settings.yml:
listenOnlyMode: false
skipCheck: true
skipCheckOnJoin: true
the first audio join fails when entering the breakout room. It is then retried and connects successfully, but the process takes longer and it shows an error message. This was not the case in one of the previous versions.

![bbb-breakout](https://user-images.githubusercontent.com/76210329/116394718-901be100-a823-11eb-812c-18a1eb03e6fa.jpg)

BBB version:
2.3.0-rc-2 (2121)

**Comment by mariogasparoni** [comment]
Thanks @freddyertl.
We'll look into it for the next release

**Comment by PhMemmel** [comment]
Auto-connecting into breakout rooms works for me with the following options:
```
listenOnlyMode: true
skipCheck: false
skipCheckOnJoin: true
```

Maybe this is helpful for debugging/as workaround in the meantime.

**Comment by freddyertl** [comment]
Setting skipCheck to false works, but we want the most direct way of joining, that's why we came up with the configuration mentioned above.
