### ISSUE TITLE
equalizing and compressing differences in loudness

### ISSUE THREAD

**Issue by docjochim** [bigbluebutton/bigbluebutton#12194]
bbb ist used by iServ to provide video-conferences in school.

Often microphone adjustments differ a lot from user to user. If I rise my volume to hear one user, my headphone and also my ears explode, if the second user is speaking.

As fast as the different loudnesses change, I'm not able to correct my own speaker-volume.

Using other software as e.g. skype, there's no problem, because they seem to align the different adjustments and microphone sensitivities.

I wish a feature could be implemented to compress different single audio streams while merging them together into a resulting master-stream in order to reduce dynamics and to equalize differences in volume.

André

**Comment by prlanzarin** [comment]
mod_conference has an automatic gain control configuration parameter.
I know it from memory but I've never even made a field trial with it. And I'm almost sure BBB ships with a default conference profile that has it disabled.

You can ask your provider to experiment with that parameter and see whether that works in steadying the mixed audio volume level (without noticeable quality regressions).

**Comment by tapulator** [comment]
> mod_conference has an automatic gain control configuration parameter. I know it from memory but I've never even made a field trial with it. And I'm almost sure BBB ships with a default conference profile that has it disabled.
> 
> You can ask your provider to experiment with that parameter and see whether that works in steadying the mixed audio volume level (without noticeable quality regressions).

Thanks for this hint, @prlanzarin!

I'm currently evaluating if our provider uses the aforementioned parameter.

Out of curiosity: Would it be possible to set this parameter on the fly, so a moderator could decide wether he/she wants to use the auto gain?

**Comment by hostbbb** [comment]
So, just checked... you can thru ESL set the AGC 0 thru 1100 value for any or all members of a conference.  Like @prlanzarin i have never used it.    The browsers also have an AGC function which are turned on by default in a webrtc connection.       so need to test and see what the effect of Browser AGC - Server AGC does to the end audio quality.   can be turned off in the browser by setting some some params
