### ISSUE TITLE
Offline label in network status not localised

### ISSUE THREAD

**Issue by GhaziTriki** [bigbluebutton/bigbluebutton#12203]
**Describe the bug**
Where a user goes offline, the "(Offline)" label is not loaded from the localisation file.

**To Reproduce**
1. Change the language to Turkish.

**Expected behavior**
The displayed label should be localised.

**Actual behavior**
Change the language to Turkish or any that "app.chat.offline" value set.

**Screenshots**
![image](https://user-images.githubusercontent.com/4991088/116538605-a5564580-a8df-11eb-9d1a-2932ca4cd549.png)

**BBB version (optional):**
2.3-rc-2

**Desktop (please complete the following information):**
 - OS: Windows 10 x64
 - Browser Firefox
 - Version 88.0 x64

**Additional context**
In our test we had Turkish language with `"app.chat.offline": "Çevrimdışı"` set/

**Comment by pedrobmarin** [comment]
https://github.com/bigbluebutton/bigbluebutton/blob/2ed5319b781da128a96792cdc33b4db0c46b0126/bigbluebutton-html5/public/locales/en.json#L633

**Comment by prlanzarin** [comment]
The string is localized, so I'm closing this.

**Comment by antobinary** [comment]
I will pull again Transifex strings later today!

**Comment by GhaziTriki** [comment]
Thanks @antobinary
