### ISSUE TITLE
2.3-rc2: Assertion failed when sending chat message

### ISSUE THREAD

**Issue by PhMemmel** [bigbluebutton/bigbluebutton#12210]
**Describe the bug**
Whenever a chat message is sent, there is an assertion error in the browser console. It's probably just annoying and doesn't break anything, but maybe should be addressed at some point.

**To Reproduce**
1. Open meeting
2. Send chat message
3. Open console
4. See error -> screenshot

**Screenshots**
![grafik](https://user-images.githubusercontent.com/65113153/116582485-b8840800-a915-11eb-85ed-9ba666cb3888.png)

**BBB version (optional):**
2.3-rc2

**Desktop (please complete the following information):**
browser independent

**Comment by antobinary** [comment]
We've had this reported a few times and every time so far it's been linked to LastPass extension. Please confirm you have no extensions on the browser

**Comment by PhMemmel** [comment]
You're right, this is caused by last pass extension. Disabling it makes the assertion error go away. Thank you and sorry, didn't find anything in the issues.
