### ISSUE TITLE
Russian has 2 HTML5 translation files

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#12226]
from @nikkei00 in #12146
Why are there two Russian languages in transifex (ru) and (ru_RU) ? I did a full check and correction of grammatical errors, but I have to duplicate everything in the second language.**
![image](https://user-images.githubusercontent.com/64165027/116650419-181ff900-a992-11eb-8868-b889a1232f07.png)

_Originally posted by @nikkei00 in https://github.com/bigbluebutton/bigbluebutton/issues/12146#issuecomment-829829066_

**Comment by antobinary** [comment]
@MaximKhlobystov what would be your recommendation - should we only keep `ru.json` ?
Essentially a Russian speaker can run
`diff ru.json ru_RU.json` and tell if the differences are insignificant.

If this is the case I can remove ru_RU.json from Transifex, so Russian translators can focus on one locale and maintain the high quality.

**Comment by MaximKhlobystov** [comment]
Yes, I think that's a good idea to keep only one file. I've had a look. The differences don't look significant. Let's keep `ru.json`. In my opinion, that one is a bit better than the other.

**Comment by antobinary** [comment]
Thanks for checking this, Maxim!
I deleted ru_RU from Transifex. Once we send a commit to remove ru_RU.json, this issue can be closed!
