### ISSUE TITLE
bbb-libreoffice-docker: Dockerfile should give the posibility to include environment file

### ISSUE THREAD

**Issue by christmart** [bigbluebutton/bigbluebutton#12222]
**Describe the bug**
When installing BBB and specialiy bbb-libreoffice-docker on a node which has to use a proxy for internet access, building of the libreoffice docker container failes, because docker build always tries do connect directly to upstream images.

**To Reproduce**
Run installation of BBB in a restricted network which has to use a proxy for Dockerhub access.

**Expected behavior**
Docker build in package bbb-libreoffice-docker should respect http_proxy settings and succeed in loading Docker images from Docker HUB

**Actual behavior**
Docker build in bbb-libreoffice-docker fails with timeouts.

A workaround is to include lines like

ENV http_proxy http://webproxy....
ENV https_proxy http://webproxy....

after the failed package installation and run a reconfigure and install again.

A better solution would be to include an envfile in the Dockerfile if possible or to execute docker build with options which include proxy options from a config file.

**Comment by mk-hs** [comment]
Same issue as this one: https://github.com/bigbluebutton/bbb-install/issues/364
`p = <host for http proxy>` should be able to take care of it, but doesn't right now.

**Comment by klepptor** [comment]
Hi @christmart ,

I'm also using BBB in a 'proxied' environment, but I've no problems with the Dockerhub access.

Did you already make the docker daemon aware of your proxy? Can you run e.g. the hello-world container from the Docker guys?

**Comment by klepptor** [comment]
For the Docker daemon to get the images:

mkdir -p /etc/systemd/system/docker.service.d

printf "[Service]\nEnvironment="HTTP_PROXY=http://<proxy>:<port>/"\n" >> /etc/systemd/system/docker.service.d/http-proxy.conf
printf "[Service]\nEnvironment="HTTPS_PROXY=http://<proxy>:<port>/"\n" >> /etc/systemd/system/docker.service.d/https-proxy.conf

For the setup of the LibreOffice containers during BBB installation:

~/.docker/config.json
{
 "proxies":
 {
   "default":
   {
     "httpProxy": "http://proxy-rzh.ofd-h.de:8080",
     "httpsProxy": "http://proxy-rzh.ofd-h.de:8080",
     "noProxy": "127.0.0.1,localhost"
   }
 }
}

**Comment by christmart** [comment]
Thanks for the hint. I already have the service override, but not the config.json. 
I'll try that solution.

**Comment by Commifreak** [comment]
bbb-install should take care of proxy in general.

To install bbb behind a proxy:

1. export http[s]_proxy= variables (both)
2. Setup docker BEFORE running bbb-install and set proxy as described here: https://docs.docker.com/config/daemon/systemd/
3. Set config.json as described here: https://github.com/bigbluebutton/bigbluebutton/issues/12222#issuecomment-831281759

/root/.docker/.config.json:
```json
{
   "proxies":{
      "default":{
         "httpProxy":"http://192.168.205.10:8000/",
         "httpsProxy":"http://192.168.205.10:8000/",
         "noProxy":"127.0.0.1,localhost"
      }
   }
}


```

4. Run bbb-install as usual.

**Comment by remil1000** [comment]
(I was about to open a separate issue on this)

As the user/admin is supposed to already have its Docker daemon well configured and able to pull images, wouldn't be possible to create this container upstream and simply pull it directly ? this would speed up and simplify deployment of this image

Is this an image size problem (bbb-soffice weigths about 2GB) ? as we have the `bigbluebutton/greenlight` readily available on the Docker hub the bigbluebutton account seems to be created and used already
