### ISSUE TITLE
Bug in playAudioAlert method

### ISSUE THREAD

**Issue by jibon57** [bigbluebutton/bigbluebutton#12228]
**Describe the bug**
The bug is here:
https://github.com/bigbluebutton/bigbluebutton/blob/6c33d54dc5a2c98a209e006c7cbd249623ee019e/bigbluebutton-html5/imports/ui/components/activity-check/component.jsx#L81

It should be:
`this.alert.addEventListener('ended', () => { this.alert.src = null; });`

For this problem frontend get crashed.

**To Reproduce**
For my case I set `userInactivityThresholdInMinutes=5`. When it tried to show notification that time error happended & crashed frontend.

**Expected behavior**

**Actual behavior**

**Screenshots**

**BBB version (optional):**
BBB 2.3.0

**Comment by mariogasparoni** [comment]
Thanks @jibon57 . Let's patch this.
Wondering how you are able to reproduce this , do you need to enable a notification or something ?

**Comment by jibon57** [comment]
@mariogasparoni change the value of `userInactivityInspectTimerInMinutes=3` & `userInactivityThresholdInMinutes=5` in 
/usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties
Now remain inactive for 5+ minutes. You'll see frontend has been crashed during showing notification.

**Comment by mariogasparoni** [comment]
Thanks @jibon57 , I'll look into it
