### ISSUE TITLE
How to setup only Moderator Camera for Recording 

### ISSUE THREAD

**Issue by clptec** [bigbluebutton/bigbluebutton#12239]
How to setup only Moderator Camera for Recording 

we setup Camera Only for Moderator , but while recording output all the open camera has recorded its privacy concern
please tell us possibility of set only Mods camera for recording

**Comment by prlanzarin** [comment]
https://docs.bigbluebutton.org/2.2/customize.html#kurento-parameters
AT userdata-bbb_record_video=


Questions => mailing lists.
