### ISSUE TITLE
upload to 2.3. kurento media server multiple fails

### ISSUE THREAD

**Issue by viisauksena** [bigbluebutton/bigbluebutton#12233]
just a write-up - which may help others, 
(for that reason the issue may be closed instantly)
while i was heavily fighting against kurento issues when upgrading / or even [reinstalling Bigbluebutton to 2.3](https://docs.bigbluebutton.org/dev/dev23.html#install-bbb-23-dev) on an upgraded ubuntu 18.04, most of the install process went pretty smoothly, but kurento fails over and over again (in suggested 6.15 version for bbb 2.3)

### problem indicators
problem becomes obvious in bbb because you cant use Video, Screensharing or even "listen" only.
Error which is shown in BBB web-frontend inside a room-session was <del>2006</del> 2001

on Serverside **netstat -tulpen** didnt show any 8888 active Ports, ie. running kurento. It crashes shortly after start. 
you may see **service kurento-media-server status** (which may trick you if you're using the [3 kurento instances suggestion](https://docs.bigbluebutton.org/dev/dev23.html#run-three-kurento-servers), because this then returns /bin/true)

### solution
not sure what exactly of the 2 following solved the issue, my best guess is some incompatible mixing with bbb - repo kms packages and kurento-media-server 
- removed kurento-media-server and all suggested kms (like kms-core ..) Packages from bigbluebutton repo (which for some reason also existed)
- reinstalled kurento as stated on kurento website (which is pretty much the same as stated on[ 2.3 dev install](https://docs.bigbluebutton.org/dev/dev23.html#install-kurento-media-server))

### notes to reinstall kurento-media-server
```## try to fix kurento stuff
#install latest/upgrade
# https://doc-kurento.readthedocs.io/en/latest/user/installation.html#local-installation
# https://doc-kurento.readthedocs.io/en/latest/user/installation.html#installation-local-upgrade
# maybe look also 
## https://doc-kurento.readthedocs.io/en/latest/user/installation_dev.html
## https://doc-kurento.readthedocs.io/en/latest/user/troubleshooting.html
## https://doc-kurento.readthedocs.io/en/latest/user/troubleshooting.html#troubleshooting-issues
## https://doc-kurento.readthedocs.io/en/latest/user/troubleshooting.html#media-server-crashes
sudo apt-get update && sudo apt-get install --no-install-recommends --yes gnupg
# Import the Kurento repository signing key
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 5AFA7A83
# # Get Ubuntu version definitions
source /etc/lsb-release
# # Add the repository to Apt
sudo tee "/etc/apt/sources.list.d/kurento.list" >/dev/null <<EOF
# Kurento Media Server - Release packages
deb [arch=amd64] http://ubuntu.openvidu.io/6.16.0 $DISTRIB_CODENAME kms6
EOF

# install aptitude
sudo apt install aptitude -y
# remove old and update/ install kurento
# basicly try to leave all other packages untouched - ok to remove bbb kms packages
sudo aptitude remove '?installed?version(kurento)'
sudo apt-get update && sudo apt-get install --no-install-recommends --yes \
    kurento-media-server
```

**Comment by ffdixon** [comment]
> while i was heavily fighting against kurento issues when upgrading / or even reinstalling Bigbluebutton to 2.3 on an upgraded ubuntu 18.04,

We haven't tested this upgrade path.  

We recommend that you start with a new Ubuntu 18.04 server and then install BigBlueButton 2.3 on that server using `bbb-install.sh`.  This way, you don't need to worry about older 2.2 packages.

That being said, others have tried the upgrade from Ubuntu 16.04 to Ubuntu 18.04, see https://github.com/bigbluebutton/bbb-install/issues/366.

**Comment by prlanzarin** [comment]
> not sure what exactly of the 2 following solved the issue, my best guess is some incompatible mixing with bbb - repo kms packages and kurento-media-server
> 
>     removed kurento-media-server and all suggested kms (like kms-core ..) Packages from bigbluebutton repo (which for some reason also existed)
>     reinstalled kurento as stated on kurento website (which is pretty much the same as stated on 2.3 dev install)

The docs on dev 2.3 install in that specific regard are outdated and we'll updated it soon.

Prior to alpha.5, we weren't building Kurento in 2.3 which is something we did/do in 2.2.

After that, BBB has its own KMS build again. So if you try to run the docs steps OR Kurento's official one stating to install from upstream and then try to install 2.3, you'll have a broken dependency system due to conflicting packages. You can install Kurento from upstream _as long as_ you're aware of that fact.

**Comment by selyod-ka** [comment]
hey!
i also tried to upgrade from xenial/bbb-2.2 to bionic/bbb-2.3.
with regard to this issue, the following solved the problem for me:
`apt-get remove kms-core kms-elements kms-filters kms-jsonrpc kmsjsoncpp && 
apt-get install tomcat8
`
and then re-running: `./bbb-install.sh -v bionic-23....`
