### ISSUE TITLE
Usability: Presentation and raise hand button are switching places

### ISSUE THREAD

**Issue by lkiesow** [bigbluebutton/bigbluebutton#12242]
After switching to 2.3, I have lately seen several people accidentally raising their hands, confusing the presenter. The reason for that is that when you quickly want to check if the presentation has changed, a user will open the presentation which causes the “Raise Hand” button to replace the “Open Presentation” button which users may not immediately notice. Users then cannot even immediately lower their hand again, but have to wait for a short period of time.

https://user-images.githubusercontent.com/1008395/116824264-91357100-ab89-11eb-8d28-a40ee073befc.mp4

Two very simple solutions for this would be:

- Switch the “Raise hand” and “Open Presentation” buttons. That way, the “Raise Hand” will always be in the same place and there is no confusion.
- Always show the presentation button and make it a “Close Presentation” in case the presentation is open right now

### BigBlueButton Version

- BigBlueButton version 2.3
- Any desktop(?) browser

**Comment by ffdixon** [comment]
Good feedback.  

I think the first suggestion of switching the Raise Hand and Open Presentation is better as it's one less icon on the screen.

**Comment by antobinary** [comment]
Agreed, let's proceed with

>Switch the “Raise hand” and “Open Presentation” buttons. That way, the “Raise Hand” will always be in the same place and there is no confusion.

Thanks for reporting!
