### ISSUE TITLE
share screen and webcam simultaneously in Firefox does not work

### ISSUE THREAD

**Issue by santos525** [bigbluebutton/bigbluebutton#12248]
**Describe the bug**
Share screen and webcam simultaneously does not work with Firefox. The sequence does not matter. If I first share the screen and then webcam, screen sharing works but webcam not, after a while I get Error 1020. If I first share webcam and then screen, webcam works screen sharing does not, the arrows circle forever.

If I use another Browser like Chromium everything works fine.

**To Reproduce**
1. Share screen
2. Share Webcam

**Expected behavior**
shared screen and webcam are shown simultaneously.

**Actual behavior**
The screen is shared, webcam not.

**Screenshots**
![firefox_screensharingandcameraatthesametimeimpossible](https://user-images.githubusercontent.com/83571987/116853280-16566f80-abf6-11eb-8bf3-31bd77b76fd3.png)

**BBB version (optional):**
BigBlueButton Server 2.3.0 (2146)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Firefox
 - Version 88.0

**Additional context**
I also tried oder Firefox Versions under Windows, same problem.

**Comment by schrd** [comment]
Is this server using multiple kurento setup? If this is the case, please check that you generated a DTLS key and shared this between all kurento instances and Freeswitch. Please check https://github.com/bigbluebutton/bigbluebutton/blob/4b2f1d7bedd85b0d22aa2935c1bbb8c67f1b3366/bigbluebutton-config/bin/apply-lib.sh#L107 how to setup this.

If you don't configure a certificate which is shared between the instances, then they will generate emphemeral ones which differ and firefox will only connect to the first connection to kurento, no matter if it is video, audio or screenshare

**Comment by santos525** [comment]
enableMultipleKurento was activated via apply-config-script, but i checked the script apply-lib and noticed that the line 
pemCertificateRSA=/etc/kurento/dtls-srtp.pem
appeared twice in /etc/kurento/modules/kurento/WebRtcEndpoint.conf.ini. 
I deleted one line, restarted bbb. Problem ist solved. :-)

Thank you!
