### ISSUE TITLE
Users shown

### ISSUE THREAD

**Issue by runc-it** [bigbluebutton/bigbluebutton#12247]
Hi
when start the BBB after login and logout some user aren't show in the user list but it's login and can speak in the room.
In attach picture you can see user (BANK) is in the room and can speak but doesn't in the user list.
Best regards Thanks
![Screenshot_from_2021-04-06_11-50-29](https://user-images.githubusercontent.com/82929246/116851554-d1d3cf80-ac07-11eb-822a-5da0a5eac8d9.png)

**Comment by hostbbb** [comment]
What version on BBB is this 2.2 or 2.3  What you are saying, even though users are "muted" in UI,  both of you can talk and hear each other?

**Comment by runc-it** [comment]
@hostbbb 
The version is 2.2 . someone is speaking in the room and he doesnot in the list of users.

**Comment by prlanzarin** [comment]
Which **specific** 2.2 version is that? We need the patch version as well.

Also: you were in the room as a viewer. Are you sure you were not under the effect of the `See other viewers in the Users list` lock setting? It looks like it because that lock setting is a bit _too literal_ in its behaviour and talking indicators/cameras/whatever are not locked along with the user list.

**Comment by runc-it** [comment]
Yes , I am sure about that effect of the see other viewers in the users list is Unlock.
@prlanzarin

**Comment by runc-it** [comment]
![Untitled](https://user-images.githubusercontent.com/82929246/117613527-4d8bca00-b17c-11eb-9dae-9032800ab8d2.png)
This picture is my setting of users and  all of them can see other users

**Comment by prlanzarin** [comment]
@runc-it 

This is a staleness heads-up.

> Which specific 2.2 version is that? We need the patch version as well.

This info was still not provided. At this point in time, the recommendation is to just use 2.3. If the problem happens again, feel free to re-open with proper info attached, including:
  - FULL BIGBLUEBUTTON VERSION
  - /var/log/bbb-apps-akka/ | /var/log/bbb-html5/ logs, along with an identifier of the supposed missing user
