### ISSUE TITLE
Guest Lobby List does not show after Initiator reconnect

### ISSUE THREAD

**Issue by Li-amK** [bigbluebutton/bigbluebutton#12254]
**Describe the bug**
This Bug occourred, after leaving the conference (as Initiator) and rejoining short it after whilst having the Guest Lobby active. After rejoining, No more waiting Guests were shown and always Timed out in the Guest Lobby.

**To Reproduce**
1. Start a Conference and have people join it
2. Disconnect from Conference by clicking the "back" arrow in the address bar and reconnecting via the Admin window
3. Open Guest Lobby Waiting List
4. Have more people join
5. The won't show up in the List and won't be able to join the conference

**Expected behavior**
You would expect to still see new members waiting in the Lobby.

**Actual behavior**
The list was empty  and showed no more waiting Participants.

**Desktop:**
 - OS: Windows 10 Education Version 1809 build 17763.316
 - Browser Google Chrome
 - Version 90.0.4430.93 (official Build) (64-Bit)

**Comment by pedrobmarin** [comment]
Hi @Li-amK , thanks for the report.

Could you add more details to the steps to reproduce? By your description, sounds like you are using greenlight. Can you reproduce this using only [API calls](https://mconf.github.io/api-mate)

**Comment by mltschlz** [comment]
So I am the user who noticed the bug... (though not a developer). I think you are right in that our server uses greenlight. 
In my words, here's what I did:
(1) Started a conference as admin (with guest lobby)
(2) Share Link / Let some people access the guest lobby 
(3) Leave conference (via browser "back" arrow)
(4) Re-access conference
--> Guest lobby is empty (previous members of guest lobby are not shown)

However, just tried this again on another computer and the behavior was as expected. So it could be related to the chrome or windows version, or there are other unknown factors causing the bug.

**Comment by h0jeZvgoxFepBQ2C** [comment]
Yeah can confirm

**Comment by GhaziTriki** [comment]
@pedrobmarin 

I can confirm the bug in 2.3.15

![image](https://user-images.githubusercontent.com/4991088/144204019-f81f9ebc-51f9-46a9-afae-9a9010e0285e.png)
