### ISSUE TITLE
Presentation moves when talking indicator is set to true

### ISSUE THREAD

**Issue by aahepp** [bigbluebutton/bigbluebutton#12251]
**Describe the bug**
When you have set the talking indicator to true (enableTalkingIndicator: true) any time someone uses their mic the presentation will adjust down while the talking indicator is shown.  As soon as the indicator closes the presentation adjusts back up

**To Reproduce**
Enable mic and speak (same results on test server)

**Expected behavior**
talking indicator bubble to show and presentation stay in a static position

**Actual behavior**
talking indicator comes on presentation drops down slightly, talking indicator goes off presentation moves back to original spot

**Screenshots**

**BBB version (optional):**
BigBlueButton Server 2.3.0 (2148)

**Desktop (please complete the following information):**
 - OS: Linux and Windows
 - Browser Firefox and Chrome
 - Version FF: 88.0 (64-bit)    Chrome: Chromium: 90.0.4430.93

**Smartphone (please complete the following information):**
 - Browser [e.g. stock browser, Safari]

**Additional context**

**Comment by ffdixon** [comment]
Thanks for opening an issue for this.  It's a small shift down, but it is something we do want to resolve.
