### ISSUE TITLE
Mic Allowed even when locked

### ISSUE THREAD

**Issue by aahepp** [bigbluebutton/bigbluebutton#12252]
**Describe the bug**
Users able to share mic even when mic is set to locked

**To Reproduce**
1. change settings in 
/usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties
           lockSettingsDisableMic=true
/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml
               autoJoin: true
               listenOnlyMode: true
2. User enters room is prompted if they want to allow their mic (see attached)

**Expected behavior**
User joins room and is automatically connected to the audio bridge in listen mode

**Actual behavior**
User joins room and is prompted to share their mic

**Screenshots**
![mic](https://user-images.githubusercontent.com/32578214/116871987-26188880-abe3-11eb-9e03-bbf9bc8013c1.png)
![lock_settings](https://user-images.githubusercontent.com/32578214/116872012-2ca70000-abe3-11eb-9472-8eb7c57ccfe1.png)

**BBB version (optional):**
BigBlueButton Server 2.3.0 (2148)

**Desktop (please complete the following information):**
 - OS: Linux and Windows
 - Browser Firefox and Chrome
 - Version  FF: 88.0 (64-bit) Chrome: Chromium: 90.0.4430.93

**Smartphone (please complete the following information):**
N/A
**Additional context**
I am able to get around this issue by change the setting in:
/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml
     forceListenOnly: true

But then if you want a user to be able to share their mic and you unlock them, they will immediately go to a muted state (due to forceListenOnly) and there is no way to get around that.

**Comment by mariogasparoni** [comment]
Related to #12048

**Comment by mariogasparoni** [comment]
@aahepp , are you still able to reproduce this ?
I can't reproduce this using the settings you mentioned (tested on BBB 2.3.5)
When joining as attendee,  i get the expected behavior.

**Comment by aahepp** [comment]
I will have to test this tonight and report back.  I set forceListenOnly to true so it never will prompt them to use their mic even when they are unlocked as a work around.  I am still running 2.3.3 so will let you know.

**Comment by aahepp** [comment]
I just tested this on version BigBlueButton Server 2.3.3 (2326) and yes it was still present (in a sense)
/usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties
lockSettingsDisableMic=true
/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml
autoJoin: true
listenOnlyMode: true

When the user enter they are getting the security warning:
Allow xxxxxxxx.com to use your microphone (Block / Allow)

But you see the pop-up in the back ground:
How would you like to join the audio?  Which the only option is Listen Only

Would expect if you have it set to disable mic in the bigbluebutton.properities you should never get the security warning wanting you to share your mic in the first instance, and should only be alerted if that user is unlocked and rejoins the audio.  

If you set 
/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml
forceListenOnly: true

Then they are never prompted with the security warning but also they are never able to share their mic even if you unlock the user.  The only way they are allowed to share their mic with that option forced is to make them a moderator.

I will try upgrading to 2.3.6 (latest) to see if it is still present and let you know.

**Comment by mariogasparoni** [comment]
Thanks @aahepp . I will also check this with the info you provided

**Comment by aahepp** [comment]
No worries.  Just finished the upgrade:
bbb-conf --version
BigBlueButton Server 2.3.6 (2378)

And looks like it was fixed sometime after 2.33 as it is working as it is supposed to.  User joins no security prompt for mic and they are auto joined to the audio.  Unlock user user rejoins audio bridge and selects mic and then prompted for allowing mic.

So we can consider this bug/issue resolved.

**Comment by ffdixon** [comment]
Thanks for verifying.
