### ISSUE TITLE
Debian-Packaging-Bug in postinst (etc.) scripts related to determination of IP-address

### ISSUE THREAD

**Issue by EmmyGraugans** [bigbluebutton/bigbluebutton#12262]
CC @schrd and @danimo

**Describe the bug**
There is a bug in several (almost all) `bbb-*.preinst` and `bbb-*.postinst`, `bbb-*.prerm` and `bbb-*.postrm` files regarding the determination of the IP-Address. The same issue came up last December for both bbb-install and bbb-conf, but apparently wasn't fixed everywhere.

see also: https://github.com/bigbluebutton/bbb-install/pull/286
see also: https://github.com/bigbluebutton/bigbluebutton/pull/10900

Actually, those two pull-requests aren't complete either. They fix the *second* line (which is used in most cases anyways), but the *first* line, which is hit when there's a network-interface named `venet0:0` is still clearly wrong (at least in Ubuntu 18.04 it can't work). I cannot test with "OpenVZ" for which this line allegedly is or was useful, but I'd recommend removing the entire `if` thingy around the assignment of IP= unless and until somebody with OpenVZ says it is still needed (and how it would work correctly).

The files in question contain the snippet
```
if LANG=c ifconfig | grep -q 'venet0:0'; then
  # IP detection for OpenVZ environment
  IP=$(ifconfig | grep -v '127.0.0.1' | grep -E "[0-9]*\.[0-9]*\.[0-9]*\.[0-9]*" | tail -1 | cut -d: -f2 | awk '{ print $1}')
else
  IP=$(hostname -I | sed 's/ .*//g')
fi
```
which probably should be changed to

```
IP=$(ifconfig $(route | grep ^default | sed "s/.* //") | awk '/inet /{ print $2}' | cut -d: -f2)
```

The same snippet occurs also in `/etc/bigbluebutton/bbb-conf/apply-lib.sh` and with the modifications mentioned in the above linked pull-requests also in `/usr/bin/bbb-conf` and in `bbb-install.sh`

**Installation type**
Installation with bbb-install.sh, but doesn't matter, because the bug is in the Deb-Packages themselves.

**Firewall and IP address type**
No NAT, own IP-address. On some hosts, BBB would statistically use the IP-address of the docker-network (installed through bbb-install-sh) instead of the real IP-address of the machine. *Maybe* relevant, but probably that needs a separate issue: external DNS-Servers do NOT work in our network (there's a firewall on port 53 UDP).

**Console output**
Not relevant, however `bbb-conf --check` shows the warning
```
# Warning: The setting of 172.17.0.1 for local_ip_v4 in
#
#    /opt/freeswitch/etc/freeswitch/vars.xml
#
# does not match the local IP address (xxx.xxx.xxx.xxx).
# (This is OK if you've manually changed the values)
```

**Additional context**
The bug is only *relevant* in five files, but it is present in 26 out of 34 files in `/var/lib/dpkg/info`. But in these five files, the value of `$IP` is used later on in the same script:

bbb-freeswitch-core.postinst
bbb-html5.postinst
bbb-record-core.postinst
bbb-web.postinst
bbb-webrtc-sfu.postinst

The most obvious of these is freeswitch, since it won't work (error 1007 after fresh installation).

**Comment by znerol** [comment]
`hostname -I` is clearly wrong. This will report all IPs of all interfaces in an unknown order. Still I wouldn't suggest do fix that with `ifconfig` and `route`. Those commands were replaced long time ago by `iproute2` (i.e., `ip route` and `ip address` commands). The `ip` command even has a `-j` flag which will output results in `json` and thus can be handled with `jq` easily.

```shell
DEFAULT_IP4_IFACE=$(ip -4 -j route show default | jq -r '.[]?.dev | select(.)')
DEFAULT_IP4_ADDR=$(ip -4 -j address show dev $DEFAULT_IP4_IFACE scope global primary up | jq -r '.[]?.addr_info[]?.local | select(.)')
DEFAULT_IP6_IFACE=$(ip -6 -j route show default | jq -r '.[]?.dev | select(.)')
DEFAULT_IP6_ADDR=$(ip -6 -j address show dev $DEFAULT_IP6_IFACE scope global primary up | jq -r '.[]?.addr_info[]?.local | select(.)')
```

I've tested these on a couple of machines. Some with multiple interfaces, some with only one. Works in LXC and Podman/Docker. I do not have any OpenVZ around anymore.

Note `DEFAULT_IP4_IFACE` and `DEFAULT_IP6_IFACE` will be empty if there is no default route for the respective address family.

**Comment by EmmyGraugans** [comment]
Yes, I am aware that iproute2 is more modern, yet I still haven't "mastered" it yet and am very happy that the old commands exist also still in Ubuntu 20.04 and Debian Bullseye. ;) (And to be honest, I find both the output and the syntax of the old commands a lot easier to read.)

As to your suggested commands: unfortunately it doesn't work that way in Ubuntu 18.04, where the switch `ip -j` has an effect only for the command `addr`, but not for `route`. It is still a valid option, but `ip -j route` and `ip route` give the same output (which is not json-formatted).

Working in both 18.04 and 20.04:
`DEFAULT_IP4_IFACE=$(ip -4 route show default | cut -d ' ' -f 5)`

The commands you wrote for getting the address work. An Alternative (without the json and somewhat shorter) could be
`DEFAULT_IP4_ADDR=$(ip -4 -brief address show dev $DEFAULT_IP4_IFACE scope global primary up | grep -Eo '([0-9]+\.?){4}')`

**Comment by EmmyGraugans** [comment]
Bug still present in BBB 2.3.9

**Comment by antobinary** [comment]
Retagging to 2.5 where the build/ directory contains all the packaging related files (open source). Once resolved we can backport to all maintained versions
