### ISSUE TITLE
Refactor of the Subscriptions component

### ISSUE THREAD

**Issue by Tainan404** [bigbluebutton/bigbluebutton#12271]
In the current implementation of the subscriptions component we've all the subscriptions wrapped together.
It made sense when it was implemented, because all subscriptions followed the same parttern, however with new features added every day, we have some subscriptions that does not follow same pattern, specially due to parameters.
This lead us to some bugs that could be avoided by handling subscriptions individually ( i.e. PR #11909 ).
Other than that, we have also some situations where a subscription is redone causing re-synchronization of collections, resulting in an excessive use of bandwidth and extra processing in client side.
For a better handle of the subscriptions, I propose a refactor of the subscriptions with the following goals:
 1. split the subscriptions into two categories, dynamics and statics 
    1.1 Static subscriptions: subscriptions with no dependecies
    1.2 Dynamic subscriptions: subscriptions with they own workflow and dependencies
 2. A disconnection/reconnection handler.
 3. Allow to hook into subscription events without rewriting the whole callback ( i.e. onError, onChange, etc )
 4. Add logs for debug.
Notes:
- To achieve item 1, we can create one [Tracker.autorun](https://docs.meteor.com/api/tracker.html#Tracker-autorun) for each subscription ( instead of having one big component using withTracker )

**Comment by antobinary** [comment]
This is open for discussion / feedback so we gather perspectives before we commence work.
@pedrobmarin do you spot anything missing?

**Comment by pedrobmarin** [comment]
Looks good. I think this cover some of the points I noticed too while facing this component. I'll keep this discussion updated if I remember anything else.
