### ISSUE TITLE
Screen freezes after the screen went black

### ISSUE THREAD

**Issue by PlumedArcher** [bigbluebutton/bigbluebutton#12289]
**To Reproduce**
1. Have a conference, mute yourself and let your screen get black due to inactivity
2. After your screen went black, wait a few minutes
3. Move your mouse, so that your screen starts again
4. unmute yourself

**Expected behavior**
The mute symbol returns to "unmuted" (green).

**Actual behavior**
The symbol stays red like if you were muted. However, you can still talk, get the audio notifications of muted/unmuted and others see the correct state whether you are muted or unmuted. Also the symbol at the bottom gets locked.
After 15 seconds, the normal behavior returns and the symbol is displayed properly.

**BBB version (optional):**
BBB 2.3 Clientversion: 1668

**Desktop (please complete the following information):**
 - OS:  Windows 10
 - Browser Chrome

**Additional context**
I was not able to lock the symbol when leaving while unmuted.
This occurs only about 50 % of the time, so i can't reproduce this consistently.

**Comment by antobinary** [comment]
Hi @PlumedArcher 
thanks for reporting this!

> let your screen get black due to inactivity

Is this a computer screen saver ? Like a laptop battery consumption minimizer?
If there is another user in the meeting, do they see your inactive user in the userlist?

Could you please join with a unique name in https://test23.bigbluebutton.org/demo/demo2.jsp and try to reproduce this, then send here the name you used so I can go check the logs.

**Comment by PlumedArcher** [comment]
No screen saver, not sure what's the english term for this, but basically the screen just gets turned off in order to save energy (first option in windows 10 settings under "save energy").
And yes, others can still see me.

My first description was somewhat misleading i guess. I noticed that it is more like the whole screen freezes, also the tool bar and the pencil for example are froozen, but still work somewhat (see screenshot). I can stop the freeze after some actions like dragging the window or closing something. So it does not seem to depend on a time window. And also now I was able to reproduce this while unmuted.

Reproduced this on your server with the problems at 18:19 and 18:23. with the names "inactive" and "second user".

18:39 I reproduced it again, and everything i had written ( just some curves, not visible at the beginning) just turned into straight lines. 

![Screenshot (864)](https://user-images.githubusercontent.com/80673946/117178869-c680cf80-add2-11eb-9cdf-15740da7ef10.png)
