### ISSUE TITLE
2.3.0: akka-apps is spamming the logfile

### ISSUE THREAD

**Issue by schrd** [bigbluebutton/bigbluebutton#12284]
**Describe the bug**

bbb-akka-apps produces a lot of repeating log messages (several per second):

~~~
2021-05-05T04:04:03.768+02:00 INFO  o.b.core2.AnalyticsActor - -- analytics -- {"envelope":{"name":"PresenterUnassignedEvtMsg","routing":{"msgType":"BROADCAST_TO_MEETING","meetingId":"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx-yyyyyyyyyyyyy","userId":"w_xxxxxxxxxxxx"},"timestamp":1620180243768},"core":{"header":{"name":"PresenterUnassignedEvtMsg","meetingId":"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx-yyyyyyyyyyyyy","userId":"w_xxxxxxxxxxxx"},"body":{"intId":"w_xxxxxxxxxxxx","name":"John Doe","assignedBy":"w_xxxxxxxxxxxx"}}}
2021-05-05T04:04:03.769+02:00 INFO  o.b.core2.AnalyticsActor - -- analytics -- {"envelope":{"name":"PresenterAssignedEvtMsg","routing":{"msgType":"BROADCAST_TO_MEETING","meetingId":"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx-yyyyyyyyyyyyy","userId":"w_xxxxxxxxxxxx"},"timestamp":1620180243768},"core":{"header":{"name":"PresenterAssignedEvtMsg","meetingId":"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx-yyyyyyyyyyyyy","userId":"w_xxxxxxxxxxxx"},"body":{"presenterId":"w_xxxxxxxxxxxx","presenterName":"John Doe","assignedBy":"w_xxxxxxxxxxxx"}}}
~~~

I was draining the server for some maintenance task, and according to our monitoring there were 2 conferences with 2 users in total at the time when this happened. So I assume that this was a left over user in one of the two conferences.

The message tuple (PresenterUnassignedEvtMsg, PresenterAssignedEvtMsg) which are produced at the same millisecond is repeated over and over again. Between the tuples is a delay of some milliseconds.

**To Reproduce**
I don't know how to reproduce this yet. This happened on one of my servers running 2.3.0 in production.

**Additional context**
BBB version: 2.3.0

**Comment by antobinary** [comment]
Thanks for reporting this. We had looked into this a few years ago via https://github.com/bigbluebutton/bigbluebutton/pull/6326 (among other prs) but this is the first recurrence I am aware of.

**Comment by crosscodr** [comment]
Hi @antobinary,
I had this issue today. It was in a Breakoutroom, where `getMeetings` reported, that one person is in the room, but I couldn't see anyone when I joined the room.
I had the same INFO-log messages as @schrd in syslog. Several hundreds per second.
Eventually, I forcibly ended the meeting to relieve the server. One out of two nodejs-backend processes was using 50% CPU (one core) constantly.

**Comment by antobinary** [comment]
Hi @crosscodr 
Any chance you could provide logs for the main meetings+breakouts?
Something like `sudo journalctl -u bbb-apps-akka | grep <meetingId>` and same for `-u bbb-html5-*`?

here / via email/ ... Sanitizing user names is fine. If it's possible, please respond and I will pass you my email if needed

**Comment by crosscodr** [comment]
Hi @antobinary, sure, I can send you sanitized logs per mail.

**Comment by antobinary** [comment]
(anton dot georgiev at blindsidenetworks dot com)
Thanks!

**Comment by antobinary** [comment]
I have not received logs from @crosscodr but one of the servers I have access to hit this earlier.

In the case that I am investigating:
Immediately before this flood of messages there is a disconnect and re-join of the user who was _presenter_.
We have this code: https://github.com/bigbluebutton/bigbluebutton/blob/v2.3.x-release/bigbluebutton-html5/imports/api/users/server/handlers/presenterAssigned.js#L51-L64

I am still investigating, but this is the area that I am looking into.

**Comment by crosscodr** [comment]
Hi @antobinary,
I send the logs to you today. Spend some time to sanitize the logs.

**Comment by schrd** [comment]
I had this once again, BBB 2.3.4 this time.

The getMeetingInfo lists the same user twice (same user id). Maybe it is bouncing between the two?
See the attached output of getMeetingInfo
[meeting.txt](https://github.com/bigbluebutton/bigbluebutton/files/6755437/meeting.txt)

**Comment by antobinary** [comment]
In the most recent encounter on @schrd 's server we had some interesting findings:

MongoDB had info on only one user in the meeting

```
{
  "_id": "4JfaLrvxSazTttxW3",
  "meetingId": "cf8a18d1892c85226c651ea52363d17edb28386c-1625212590386",
  "userId": "w_b6gja224ymg5",
  "authToken": "cul2e3vqduit",
  "clientType": "HTML5",
  "validated": true,
  "approved": true,
  "authTokenValidatedTime": 1625213237602,
  "inactivityCheck": false,
  "loginTime": 1625213152672,
  "authed": true,
  "avatar": "",
  "breakoutProps": {
    "isBreakoutUser": false,
    "parentId": "bbb-none"
  },
  "color": "#3949ab",
  "effectiveConnectionType": null,
  "emoji": "none",
  "extId": "gl-  id = 1",
  "guest": false,
  "guestStatus": "ALLOW",
  "intId": "w_b6gja224ymg5",
  "locked": true,
  "loggedOut": false,
  "mobile": false,
  "name": "User 1",
  "presenter": false,
  "responseDelay": 0,
  "role": "MODERATOR",
  "sortName": "User 1"
}
```

(notice presenter: false)

Akka-apps and bbb-web had info on two users in the meeting (same external user id)

```
"users": [
        {
          "intId": "w_clhety6nxcqk",
          "extId": "gl-guest-___Id=1__",
          "name": "User 1",
          "role": "MODERATOR",
          "guest": false,
          "authed": true,
          "guestStatus": "ALLOW",
          "emoji": "none",
          "locked": true,
          "presenter": true,
          "avatar": "",
          "clientType": "HTML5"
        },
        {
          "intId": "w_b6gja224ymg5",
          "extId": "gl-guest-___Id=1__",
          "name": "User 1",
          "role": "MODERATOR",
          "guest": false,
          "authed": true,
          "guestStatus": "ALLOW",
          "emoji": "none",
          "locked": true,
          "presenter": false,
          "avatar": "",
          "clientType": "HTML5"
        }
      ]
```

(notice the presenter: true vs presenter: false)


Discussing this further with @jfsiebel and @ritzalam
