### ISSUE TITLE
double popup alerts

### ISSUE THREAD

**Issue by Superjamp** [bigbluebutton/bigbluebutton#12287]
**Describe the bug**
While chatting with a user while the popup alert is active and the chat is open, two popup alerts are displayed

**To Reproduce**
1. Open a Meeting with two Users
2. User-1 starts a private Chat with User-2
3. User-2 opens the created Chat
4. User-1 writes a message to User-2
5. See error

**Expected behavior**
there schould be only 1x popup alert displayed
or
because the user has an open chat with the other user, should there be a popup alert at all?

**Actual behavior**
2x popup notification are displayed

**Screenshots**
![image](https://user-images.githubusercontent.com/26893184/117113633-0ae87d00-ad8b-11eb-996a-2aca5c3905f2.png)
![image](https://user-images.githubusercontent.com/26893184/117114243-de813080-ad8b-11eb-8f9d-d07943548106.png)

**BBB version (optional):**
BigBlueButton Server 2.3.0 (2146)

**Desktop (please complete the following information):**
 - OS: Linux Fedora 33
 - Browser: Chrome
 - Version: 90.0.4430.93

**Comment by JustinMogel** [comment]
could reproduce this issue with
 - OS: Windows 10
 - Browser: Firefox
 - Version: 88.0
