### ISSUE TITLE
etherpad cutting of text

### ISSUE THREAD

**Issue by Superjamp** [bigbluebutton/bigbluebutton#12286]
**Describe the bug**
At the end of the document in the Etherpad iframe the last line is cutting off

**To Reproduce**
1. Open a Meeting
2. Open the shared Notes Tab
3. Write a lot of Text with new Lines

**Screenshots**
![image](https://user-images.githubusercontent.com/26893184/117111406-d45d3300-ad87-11eb-9a8a-93eac188d5ee.png)

**BBB version (optional):**
BigBlueButton Server 2.3.0 (2146)
bbb-etherpad 1:2.3.0-48

**Desktop:**
 - OS: Linux Fedora 33
 - Browser: Chrome
 - Version: 90.0.4430.93

**Additional context**
In my local tests it is possible to fix the visual error when I replaced the top padding with a margin
```
#innerdocbody, #sidediv {
    margin-top: 15px;
    padding-bottom: 15px;
}
```

**Comment by cgruber-uos** [comment]
This issue is annoying for a lot of lecturer and we get often bug reports about that so it would be nice in case this could be fixed, especially when the proposed solution works.
