### ISSUE TITLE
Outdated Node.js modules - Security risk

### ISSUE THREAD

**Issue by laserrapt0r** [bigbluebutton/bigbluebutton#12288]
BigBlueButton and its components use a lot of outdated node.js modules. 

Some of these outdated modules have known vulnerabilities with high severity and could be a potential security risk.

They are for example referenced in https://github.com/bigbluebutton/bigbluebutton/blob/develop/bigbluebutton-html5/package.json

I ask you to please update as many as possible of those JavaScript librarys to the most recent versions. 

Just one example:

https://snyk.io/vuln/npm:sanitize-html

Thank you

**Comment by antobinary** [comment]
Hi @laserrapt0r 

Thank you for this report!
sanitize-html was updated to 1.27.5 two months ago https://github.com/bigbluebutton/bigbluebutton/pull/11639
You are right that there's 2.x branch that is maintained. I switched to it in #12296 

If you spot any security risk though, please inform us via https://github.com/bigbluebutton/bigbluebutton/blob/develop/SECURITY.md rather than opening an issue.

Your vigilance is appreciated!

**Comment by laserrapt0r** [comment]
Thank you for your answer. As far as I understand sanitize-html 1.27.5 is also affected by known vulnerabilities. But this was just one example. 

There are also outdated modules in https://github.com/bigbluebutton/bigbluebutton/blob/develop/bbb-webhooks/package.json 

In bbb-html5 lodash 4.17.21 is used what is up to date but in bbb-webhooks version 4.17.19 is used. 
https://snyk.io/vuln/npm:lodash

**Comment by antobinary** [comment]
I am using a different way to scan for vulnerable versions (as of your post) and am able to see ones I was not aware of. Already working on addressing. Thank you for this!

Running `npm audit` on the bigbluebutton-html5 code base did not signal about sanitize-html.

I will bring this to the attention of the maintainers of bbb-webhooks, thanks!

**Comment by laserrapt0r** [comment]
cat /usr/local/bigbluebutton/bbb-webrtc-sfu/node_modules/lodash/lodash.js | grep "var VERSION" and 
cat /usr/share/etherpad-lite/src/node_modules/lodash/lodash.js | grep "var VERSION"
=> var VERSION = '4.17.20';

/usr/share/meteor/bundle/programs/server/npm/node_modules/meteor/babel-compiler/node_modules/lodash/lodash.js | grep "var VERSION"

=> var VERSION = '4.17.15';

**Comment by antobinary** [comment]
These (and more) were patched and will be out with BBB 2.3.1
Thanks again!

**Comment by laserrapt0r** [comment]
Thank you sir :-)

**Comment by MaximilianJacobs** [comment]
@antobinary Will this fix be backported to BBB 2.2.x?
Is there an ETA for the update?
