### ISSUE TITLE
Tool bar is cut off in small window

### ISSUE THREAD

**Issue by PlumedArcher** [bigbluebutton/bigbluebutton#12290]
Having a small enough browser window does cut off the tool bar. If the height is small enough, one can't click the options that aren't visible.

**Screenshots**

![Screenshot (863)_LI](https://user-images.githubusercontent.com/80673946/117127723-c49c1980-ad9c-11eb-9b77-62437e32249b.jpg)

**BBB version (optional):**

BBB 2.3 Clientversion: 1668

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome, Edge

**Comment by mrkeksi** [comment]
I do not know if I should say works as intended. Since many other things are not displayed in such a small window. But at least the toolbar would be smaller if the palm recognition would be moved to the settings as described in #12243.
