### ISSUE TITLE
bbb-html5-loadbalancer.conf configures invalid number of NodeJS processes

### ISSUE THREAD

**Issue by KimBrodowski** [bigbluebutton/bigbluebutton#12291]
**Describe the bug**
`/etc/nginx/conf.d/bbb-html5-loadbalancer.conf` is statically provided by bbb-html5. While the number of NodeJS processes can be customized (see https://docs.bigbluebutton.org/dev/dev23.html#increase-number-of-processes-for-nodejs), as of right now the config file always comes preconfigured for 8 processes.

~~~
root@bbb0:/tmp# cat deb/etc/nginx/conf.d/bbb-html5-loadbalancer.conf
upstream poolhtml5servers {
  zone poolhtml5servers 32k;
  least_conn;
  server 127.0.0.1:4100 fail_timeout=5s max_fails=3;
  server 127.0.0.1:4101 fail_timeout=5s max_fails=3;
  server 127.0.0.1:4102 fail_timeout=5s max_fails=3;
  server 127.0.0.1:4103 fail_timeout=5s max_fails=3;
  server 127.0.0.1:4104 fail_timeout=5s max_fails=3;
  server 127.0.0.1:4105 fail_timeout=5s max_fails=3;
  server 127.0.0.1:4106 fail_timeout=5s max_fails=3;
  server 127.0.0.1:4107 fail_timeout=5s max_fails=3;
}
~~~

nginx gracefully fails over to running processes, however this does create a rather lot of noise in the log files:

~~~
2021/05/05 13:44:37 [error] 2078#2078: *5871 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.137, server: bbb0.iserv.eu, request: "GET /html5client/join?sessionToken=5n8jif4yolfd0f7c HTTP/1.1", upstream: "http://127.0.0.1:4102/html5client/join?sessionToken=5n8jif4yolfd0f7c", host: "bbb0.iserv.eu"
2021/05/05 13:44:37 [error] 2078#2078: *5871 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.137, server: bbb0.iserv.eu, request: "GET /html5client/join?sessionToken=5n8jif4yolfd0f7c HTTP/1.1", upstream: "http://127.0.0.1:4107/html5client/join?sessionToken=5n8jif4yolfd0f7c", host: "bbb0.iserv.eu"
2021/05/05 13:44:37 [error] 2078#2078: *5871 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.137, server: bbb0.iserv.eu, request: "GET /html5client/join?sessionToken=5n8jif4yolfd0f7c HTTP/1.1", upstream: "http://127.0.0.1:4103/html5client/join?sessionToken=5n8jif4yolfd0f7c", host: "bbb0.iserv.eu"
2021/05/05 13:44:37 [error] 2078#2078: *5871 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.137, server: bbb0.iserv.eu, request: "GET /html5client/join?sessionToken=5n8jif4yolfd0f7c HTTP/1.1", upstream: "http://127.0.0.1:4105/html5client/join?sessionToken=5n8jif4yolfd0f7c", host: "bbb0.iserv.eu"
2021/05/05 13:44:37 [error] 2078#2078: *5871 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.137, server: bbb0.iserv.eu, request: "GET /html5client/join?sessionToken=5n8jif4yolfd0f7c HTTP/1.1", upstream: "http://127.0.0.1:4106/html5client/join?sessionToken=5n8jif4yolfd0f7c", host: "bbb0.iserv.eu"
2021/05/05 13:44:37 [error] 2078#2078: *5871 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.137, server: bbb0.iserv.eu, request: "GET /html5client/compatibility/adapter.js?v=1669 HTTP/1.1", upstream: "http://127.0.0.1:4104/html5client/compatibility/adapter.js?v=1669", host: "bbb0.iserv.eu", referrer: "https://bbb0.iserv.eu/html5client/join?sessionToken=5n8jif4yolfd0f7c"
~~~

**To Reproduce**
1. Install BBB 2.3 from bionic-23
2. Join a random meeting
3. Check the nginx error.log

**Expected behavior**
No error is logged.

**Actual behavior**
Example log see above.

**Screenshots**
n/a

**BBB version (optional):**
BigBlueButton Server 2.3.0 (2148)

**Desktop (please complete the following information):**
n/a

**Smartphone (please complete the following information):**
n/a

**Additional context**
n/a

**Comment by hostbbb** [comment]
Is there a way to source this file from /etc/bigbluebutton, instead of the file in conf.d  like have an include in conf.d so everything is in /etc/bigbluebutton/nginx/conf.d for config?

**Comment by KimBrodowski** [comment]
> Is there a way to source this file from /etc/bigbluebutton, instead of the file in conf.d like have an include in conf.d so everything is in /etc/bigbluebutton/nginx/conf.d for config?

Sure. From a maintainers point of view this is as simple as just moving the file. However I believe the upstream directive doesn't work in a server context, so you'd probably need another include in http context and have the file not end in `.nginx` as this is what is included in the server context. I haven't tested this though.

For your own servers you can just edit the file. It is specified as a config file by bbb-html5, so it can be overridden safely without causing issues on upgrades.

It is just odd that the default configuration of 2 processes will cause errors to be logged. Even if the config isn't generated to match the number of processes I'd at least expect the default configuration to not cause such issues and adjustments requiring updates to the nginx config.

**Comment by antobinary** [comment]
By default we have 2 bbb-html5-frontend services, so

```
  server 127.0.0.1:4100 fail_timeout=5s max_fails=3;
  server 127.0.0.1:4101 fail_timeout=5s max_fails=3;
```

should suffice. However, in `bbb-html5-with-roles.conf` we say we allow up to 8 frontends by just changing that value `NUMBER_OF_FRONTEND_NODEJS_PROCESSES=`

So to match the 8 frontends, we included pre-defined nginx handling for 8 ports (4100 through 4107).
I was not aware of the noise in the log files.

`bbb-html5-loadbalancer.conf` is copied over to `/etc/nginx/conf.d` as part of the build - install process, defined in packaging. From what I can see we don't do anything more than just [create the nginx dir if needed and] put the file in it.

In terms of solutions...
A) If we just ship with ports 4100 and 4101, this will render useless any bbb-html5-frontend services on higher ports for operators who increased their `NUMBER_OF_FRONTEND_NODEJS_PROCESSES`. This will also be difficult for them to detect. So this is not a favorable solution...

B) I am looking into adding some logic on installing bbb-html5 package to check if `/etc/bigbluebutton/bbb-html5-loadbalancer.conf` exists and if it does, to copy it over (or perhaps a soft link) to `/etc/nginx/conf.d`.

**Comment by uka-support** [comment]
Surprisingly, this isn't too easy to fix automatically. What about the following solution/workaround:

1. ship a default bbb-html5-loadbalancer.conf which has 8 lines but 6 of them commented and a note pointing to the `bbb-html5-with-roles.conf`
2. update documentation in `/usr/share/meteor/bundle/bbb-html5-with-roles.conf` to include a note that the nginx config needs to be updated accordingly

like this:

```
# Default = 2; Min = 1; Max = 4
# On powerful systems with high number of meetings you can set values up to 4 to accelerate handling of events
NUMBER_OF_BACKEND_NODEJS_PROCESSES=2
# Default = 2; Min = 0; Max = 8
# If 0 is set, bbb-html5 will handle both backend and frontend roles in one process (default until Feb 2021)
# Set a number between 1 and 4 times the value of NUMBER_OF_BACKEND_NODEJS_PROCESSES where higher number helps with meetings
# stretching the recommended number of users in BigBlueButton
# Please update /etc/nginx/conf.d/bbb-html5-loadbalancer.conf and ensure that exactly this many servers 
# are made available there
NUMBER_OF_FRONTEND_NODEJS_PROCESSES=2
```

**Comment by KimBrodowski** [comment]
I actually outlined this as a possible solution above as well, so that's fine with me. ;)

> It is just odd that the default configuration of 2 processes will cause errors to be logged. Even if the config isn't generated to match the number of processes I'd at least expect the default configuration to not cause such issues and adjustments requiring updates to the nginx config.

**Comment by lonesomewalker** [comment]
Consider to do this fast, because this not only creates "noise" in the logfile, but rather drives users to nuts when the nginx tries to send them to an upstream which does not exist... have a look at the debug session above.

This is somewhat problematic as a default.

**Comment by antobinary** [comment]
>where do ports 4001+ come from?

`PORT=$(echo "3999+$INSTANCE_ID" | bc)` in `/usr/share/meteor/bundle/systemd_start.sh`

**Comment by lonesomewalker** [comment]
@antobinary THX.
Hm, as i can see at least this should make no issues, because it counts up the portnumbers itself and not predefine them :-)
As you already suggested above, if somebody wants to tweak around with the proccess number, he should know where to also have another manual correction -> commented in nginx config.

**Comment by vlasov01** [comment]
As per @uka-support  siggestion I've commented out several lines in **/etc/nginx/conf.d/bbb-html5-loadbalancer.conf**  and now these errors gone from my log.
```
upstream poolhtml5servers {
  zone poolhtml5servers 32k;
  least_conn;
  server 127.0.0.1:4100 fail_timeout=5s max_fails=3;
  server 127.0.0.1:4101 fail_timeout=5s max_fails=3;
#  server 127.0.0.1:4102 fail_timeout=5s max_fails=3;
#  server 127.0.0.1:4103 fail_timeout=5s max_fails=3;
#  server 127.0.0.1:4104 fail_timeout=5s max_fails=3;
#  server 127.0.0.1:4105 fail_timeout=5s max_fails=3;
#  server 127.0.0.1:4106 fail_timeout=5s max_fails=3;
#  server 127.0.0.1:4107 fail_timeout=5s max_fails=3;
}
```

No I have only the following errors :
```
2021/06/17 20:21:28 [error] 7719#7719: *59 open() "/var/www/bigbluebutton-default/client/conf/config.xml" failed (2: No such file or directory), client: 127.0.0.1, server: www.mydomain.ca, request: "GET /client/conf/config.xml HTTP/1.1", host: "www.mydomain.ca"
```
I'm wondering if I have missed something in my configuration?

**Comment by lonesomewalker** [comment]
Still open?

**Comment by sumeshiit** [comment]
Hi,
Our bbb server is BigBlueButton Server 2.3.10 (2419). is there documentation available, to apply this fix in a running server.

**Comment by antobinary** [comment]
We've cleaned this up in BBB 3.0 -- no pool of frontends anymore.
