### ISSUE TITLE
Timeout of Guest Waiting page should give user the ability to close the page

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#12299]
**Describe the bug**
Currently in 2.3, the Guest Waiting Page will redirect to home page of BigBlueButton server if the user is waiting for approval and the meeting ends.

However, in a production environment the users would not access the home page of the BigBlueButton server, but should be given the option to close the page (or return back in the history if BigBlueButton was launched within the same page as the front-end).. 

**To Reproduce**
1. Modify a front-end (such as Moodle) so it passes `guestPolicy=ASK_MODERATOR`
2. Join a meeting as viewer that causes a new tab to open
3.  Do not join as moderator (wait until the meeting gets terminated by bbb-web)
4.  The guest waiting page redirects to the home page of the BigBlueButton server

**Expected behavior**
Expected to receive a message "The meeting has not been started." with a button to close the page.

**Actual behavior**
When the timeout occurs, the page redirects to the home page of the BigBlueButton server.

**Screenshots**
Here's the guest waiting page

![image](https://user-images.githubusercontent.com/290351/117208954-1d36db00-adcc-11eb-8e65-908e2ecab3dc.png)

After 5 minutes the client displays

![image](https://user-images.githubusercontent.com/290351/117209785-3429fd00-adcd-11eb-952e-3af24088023c.png)

After 10 sections it redirects the user to the home page of the BigBlueButton server.

**BBB version (optional):**
BigBlueButton 2.3.0

**Comment by ffdixon** [comment]
After investigating more the options for Javascript, it might not be possible to close the page.

**Comment by pedrobmarin** [comment]
The guest page will redirect to the logoutURL provided by bbb-web.

**Comment by antobinary** [comment]
@ffdixon does anything need adjusting?
