### ISSUE TITLE
2.3.0: Etherpad crash

### ISSUE THREAD

**Issue by schrd** [bigbluebutton/bigbluebutton#12292]
**Describe the bug**
Etherpad crashes:

~~~
May 04 21:11:04 bbb-server node[731]: [2021-05-04 21:11:04.735] [WARN] client - InvalidStateError: An exception was thrown -- {
May 04 21:11:04 bbb-server node[731]:   errorId: 'v7wDhGNTEb3pGEzlUgSw',
May 04 21:11:04 bbb-server node[731]:   type: 'Uncaught exception',
May 04 21:11:04 bbb-server node[731]:   msg: 'InvalidStateError: An exception was thrown',
May 04 21:11:04 bbb-server node[731]:   url: 'https://bbb-server/pad/p/[2]xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx?userName=John%20Doe&lang=de&rtl=false&sessionToken=yyyyyyyyyyyyyyyyyy',
May 04 21:11:04 bbb-server node[731]:   source: '',
May 04 21:11:04 bbb-server node[731]:   linenumber: 0,
May 04 21:11:04 bbb-server node[731]:   userAgent: 'Mozilla/5.0 (Windows NT 10.0; WOW64; rv:56.0) Gecko/20100101 Firefox/76.0',
May 04 21:11:04 bbb-server node[731]:   stack: ''
May 04 21:11:04 bbb-server node[731]: }
May 04 21:11:04 bbb-server node[731]: [2021-05-04 21:11:04.737] [WARN] client - InternalError: too much recursion -- {
May 04 21:11:04 bbb-server node[731]:   errorId: 'PFtquvJ1JhHm0HinejSL',
May 04 21:11:04 bbb-server node[731]:   type: 'Uncaught exception',
May 04 21:11:04 bbb-server node[731]:   msg: 'InternalError: too much recursion',
May 04 21:11:04 bbb-server node[731]:   url: 'https://bbb-server/pad/p/[2]xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx?userName=John%20Doe&lang=de&rtl=false&sessionToken=yyyyyyyyyyyyyyyyyy',
May 04 21:11:04 bbb-server node[731]:   source: 'https://bbb-server/pad/javascripts/lib/ep_etherpad-lite/static/js/ace2_common.js?callback=require.define&v=d3b1f3ab',
May 04 21:11:04 bbb-server node[731]:   linenumber: 38,
May 04 21:11:04 bbb-server node[731]:   userAgent: 'Mozilla/5.0 (Windows NT 10.0; WOW64; rv:56.0) Gecko/20100101 Firefox/76.0',
May 04 21:11:04 bbb-server node[731]:   stack: ''
May 04 21:11:04 bbb-server node[731]: }
May 04 21:11:04 bbb-server node[731]: [2021-05-04 21:11:04.739] [WARN] client - InvalidStateError: An exception was thrown -- {
May 04 21:11:04 bbb-server node[731]:   errorId: 'a9ZXiTSe8ZmM7OpuNJTe',
May 04 21:11:04 bbb-server node[731]:   type: 'Uncaught exception',
May 04 21:11:04 bbb-server node[731]:   msg: 'InvalidStateError: An exception was thrown',
May 04 21:11:04 bbb-server node[731]:   url: 'https://bbb-server/pad/p/[2]xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx?userName=John%20Doe&lang=de&rtl=false&sessionToken=yyyyyyyyyyyyyyyyyy',
May 04 21:11:04 bbb-server node[731]:   source: '',
May 04 21:11:04 bbb-server node[731]:   linenumber: 0,
May 04 21:11:04 bbb-server node[731]:   userAgent: 'Mozilla/5.0 (Windows NT 10.0; WOW64; rv:56.0) Gecko/20100101 Firefox/76.0',
May 04 21:11:04 bbb-server node[731]:   stack: ''
May 04 21:11:04 bbb-server node[731]: }
~~~

**To Reproduce**

Join as 3 users:
* User A (moderator) 
* User B
* User C (has Browser addons NoScript and uBlock origin installed, no script everything permitted for this host)

User B opens the shared notes, copy some text into the pad:
~~~
https://github.com/bigbluebutton/bigbluebutton/issues/12289

https://github.com/bigbluebutton/bigbluebutton/issues/11378

https://github.com/bigbluebutton/bigbluebutton/issues/12290

~~~

User A opens shared notes, clicks somewhere into the pad. User B leaves Pad (for example open chat). User C opens shared notes, User B opens shared notes and User C gets a crash report in etherpad.

**Screenshots**

![Bug-etherpad](https://user-images.githubusercontent.com/179952/117153535-5b77ce80-adbb-11eb-8791-962b36e040dc.png)

**BBB version (optional):**

BBB 2.3.0

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Firefox
 - Version 88

**Comment by pedrobmarin** [comment]
Can you reproduce this at one of [Etherpad's demo servers](https://github.com/ether/etherpad-lite#try-it-out) ?

**Comment by ichdasich** [comment]
I encountered the same issue in #12295 ; The logs i extracted there saw the first issues occurring around the minification of some ace2 related resources (which are not included in @schrd 's log extract). Full log from my instance: 
[etherpad_redux.log](https://github.com/bigbluebutton/bigbluebutton/files/6429927/etherpad_redux.log)

**Comment by GhaziTriki** [comment]
Might not be related to this issue but one of our 2.3.0 server is showing Etherpad process unavailable then available through Zabbix.

**Comment by JustinMogel** [comment]
> Can you reproduce this at one of [Etherpad's demo servers](https://github.com/ether/etherpad-lite#try-it-out) ?

Yes

![BBB notes issue 1](https://user-images.githubusercontent.com/80588280/117940691-9f158f80-b309-11eb-9673-d5982010c127.PNG)

on the left Firefox 88.0.1 with the Addons uBlock Origin and NoScript (Deactivated in the addon for this tab)
on the right Edge (works fine)

when using a private Window for Firefox this Error does not occur, which leeds me to believe that NoScript might be responsible in some way (even though its deactivated for this tab)

**Comment by pedrobmarin** [comment]
Thanks for the update @JustinMogel ! And thanks for opening an issue at Etherpad's tracker. I'll try to follow up from there.
