### ISSUE TITLE
minimize my own Video

### ISSUE THREAD

**Issue by Thorgrimson** [bigbluebutton/bigbluebutton#12307]
**Is your feature request related to a problem? Please describe.**
Long sight-for-yourself in video conferences is very tiring.

**Describe the solution you'd like**
minimize my own Video

**Comment by prlanzarin** [comment]
Duplicate of https://github.com/bigbluebutton/bigbluebutton/issues/11990

(please search the issue tracker before opening a new one. Have a nice day.)
