### ISSUE TITLE
BBB 2.3: survey regression, no custom survey anymore

### ISSUE THREAD

**Issue by aligot-cblue** [bigbluebutton/bigbluebutton#12305]
**On BBB 2.2:**
![image](https://user-images.githubusercontent.com/13678047/117312656-7f074b80-ae85-11eb-9438-69b2bc1b97b9.png)

**On BBB 2.3:**
![image](https://user-images.githubusercontent.com/13678047/117312480-5c753280-ae85-11eb-8b8c-6ebe612352a7.png)

it seems custom survey where moderator define possible answer is not possible anymore using BBB 2.3. 

**To Reproduce**
create a survey using BBB 2.2 and BBB 2.3

**Expected behavior**
a possible way to create a custom survey in BBB 2.3

**Actual behavior**
No possible way to create custom survey in BBB 2.3

**Screenshots**
see above

**Comment by PhMemmel** [comment]
In 2.3 this is now included in the type A/B/C/D. Just click on it and replace "A" and "B" and "C" and "D" with whatever items you like. You can even add additional items or remove one of the four default ones.

**Comment by aligot-cblue** [comment]
Hoo indeed, I did not find it at first. Thanks!

May be the button may be renamed to "custom choices" ?

Also I have seen some user using one answer only survey to collect information about which student is really "online". I think a trash bin can easily added next to second option ? 

Best regards,

A.
