### ISSUE TITLE
Separate audio recordings for each user.

### ISSUE THREAD

**Issue by prajinkhadka** [bigbluebutton/bigbluebutton#12302]
Greetings ! 

We are integrating bigbluebutton in our platform. It is really handy and has helped a lot. 
But one feature that I think can be added is, giving provision to separately record thee audio of the users. 
Just like,  videos are saved separately, if audios would also be saved.

Is this not done consciously to reduce bandwidth or any reason ? or wont scale

Right now, I  guess freeswitch mixes all the audio segment.

Has anyone implemented this feature on their own ? or any guide ho to do this. I might want to implement in free time if possible.

**Comment by GyR4uk** [comment]
Hello. Is there any progress on this issue?
We partially did this by adding a new diplan to freeswitch, but there was a problem that the recording starts immediately as the user approaches the room, and the microphone lock event is not observed.

**Comment by hostbbb** [comment]
yes, need to let  bbb handle the start stop of mixed recordings, for the BBB html5 recordings to work.

its possible to add a media bug on incoming webrtc channel for every user and write out an  inbound wav or opus file for each user.  then bbb recordings still work, and you have a folder of recordings for each user...  

freeswitch.org has detailed documentation on how to do it.   then you just need to map the events.xml with user_id to map these raw files to users....

I have the code somewhere, if i locate will post here when get the time.

**Comment by GyR4uk** [comment]
That would be excellent

**Comment by prajinkhadka** [comment]
@hostbbb  did u find the code ? It would be very helpful.

**Comment by tobiasgoecke** [comment]
+1

**Comment by Assylzhan11482928** [comment]
> yes, need to let bbb handle the start stop of mixed recordings, for the BBB html5 recordings to work.
> 
> its possible to add a media bug on incoming webrtc channel for every user and write out an inbound wav or opus file for each user. then bbb recordings still work, and you have a folder of recordings for each user...
> 
> freeswitch.org has detailed documentation on how to do it. then you just need to map the events.xml with user_id to map these raw files to users....
> 
> I have the code somewhere, if i locate will post here when get the time.

Very late, but can u give a link for documentation?
