### ISSUE TITLE
Joining audio not possible with backslash in name

### ISSUE THREAD

**Issue by ichdasich** [bigbluebutton/bigbluebutton#12310]
**Describe the bug**
If you join a conference with a backslash in your name, you can not connect to audio, but receive an error 1006. Listen-only errors out immediately. Tested on 2.3.0.

**To Reproduce**
1. Join a room with `test\` as username
2. Click join by microphone
3. Wait for connection to time out.

**Expected behavior**
Users with a backslash in their name can also join the audio of a room.

**Actual behavior**
Users with a backslash in their name can not join the audio bridge.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome 90.0.4430.93 and FF 88.0

**Additional context**
```
Thu May 06 2021 22:00:40 GMT+0200 (Central European Summer Time) | sip.Inviter | Session jqe3ji9r2s4foa570hmbl1gfe25al1 transitioned to state Establishing sip.js:9602:25
Thu May 06 2021 22:00:40 GMT+0200 (Central European Summer Time) | sip.UserAgent | Missing mandatory header field : from. sip.js:9598:25
Thu May 06 2021 22:00:40 GMT+0200 (Central European Summer Time) | sip.UserAgent | Response missing mandatory header field. Dropping.
```

I think I saw a ticket about this before but could not find it when going over old issues; If someone remembers, please link it and close as a duplicated.

**Comment by prlanzarin** [comment]
@ichdasich https://github.com/bigbluebutton/bigbluebutton/issues/11675  I think that's the issue you're referring to.

> Listen-only errors out immediately. Tested on 2.3.0.

I can reproduce this with microphone, but listen only actually works. Did you test in test23?

**Comment by ichdasich** [comment]
Listen only must have been pebkac; Indeed works on retesting. Tested this on my own infra. #11675 indeed seems to be the right one. Closing this one then.
