### ISSUE TITLE
Embedd a third party application into the presentation area

### ISSUE THREAD

**Issue by GhaziTriki** [bigbluebutton/bigbluebutton#12311]
**Is your feature request related to a problem? Please describe.**
Few years ago during the developer summit @lfzawacki created a generic components to load third party HTML applications. It would good to have this implemented in the final product.

**Describe the solution you'd like**
Here is the work done https://github.com/lfzawacki/bigbluebutton/commit/c4c8709bf029606b6234e125b071d5eddf3f3df4

**Describe alternatives you've considered**

**Additional context**
It will enable loading H5P apps as example.

**Comment by mrkeksi** [comment]
Hey.
can you please explain what Hi5 Apps are?

Would something like that be possible then?

> I found this library that can do very nice math stuff http://www.fmath.info/
> 
> _Originally posted by @GhaziTriki in https://github.com/bigbluebutton/bigbluebutton/issues/2485#issuecomment-350280948_

**Comment by basisbit** [comment]
@GhaziTriki This looks like a duplicate of https://github.com/bigbluebutton/bigbluebutton/issues/9785

**Comment by GhaziTriki** [comment]
Hi fixed, it is H5P
> 
> Hey.
> can you please explain what Hi5 Apps are?
> 
> Would something like that be possible then?
> 
> > I found this library that can do very nice math stuff [http://www.fmath.info](http://www.fmath.info/)
> > _Originally posted by @GhaziTriki in [#2485 (comment)](https://github.com/bigbluebutton/bigbluebutton/issues/2485#issuecomment-350280948)_

**Comment by hex-m** [comment]
H5P (HTML5 Package) is a file format for web content. It can be used to embed interactive content and there is a whole range of [applications](https://h5p.org/content-types-and-applications) already available. Moodle (and others) supports the standard and could send the "h5p app" to BigBlueButton with the create-call. There is an example for an H5P-Player [implementation](https://github.com/tunapanda/h5p-standalone).

**Comment by hex-m** [comment]
follow-up: https://github.com/bigbluebutton/bigbluebutton/issues/15482
