### ISSUE TITLE
Whiteboard crash after screenshare closed

### ISSUE THREAD

**Issue by schrd** [bigbluebutton/bigbluebutton#12314]
**Describe the bug**
A user reported a crash in the whiteboard component. According to the user, the session was running about 60min without any issues. Then he started a screen share, terminating it after about 1 minute. The whiteboard crashed immediately afterwards.

**To Reproduce**
Unfortunately I am not able to reproduce this.

**Expected behavior**
The whiteboard should not crash.

**Screenshots**
This is a screenshot sent by the user.

![bbb-error](https://user-images.githubusercontent.com/179952/117322694-81ba6e80-ae8e-11eb-9415-91370cce98c2.png)

**BBB version (optional):**
BigBlueButton 2.3.0

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome

**Comment by ffdixon** [comment]
This might be fixed by https://github.com/bigbluebutton/bigbluebutton/pull/12297.

**Comment by antobinary** [comment]
offtopic - 
![Screenshot from 2021-05-07 08-51-36](https://user-images.githubusercontent.com/6312397/117452195-79efde00-af11-11eb-9a13-0702b4473ba3.png)

I like this! Is it a complete replacement of the toast message in top right-hand corner, or a complement to it?

**Comment by ramonlsouza** [comment]
> This might be fixed by #12297.

Yes, I just tested with/without #12297 changes and it's fixed.
