### ISSUE TITLE
2.3.0   Leave audio takes two many steps.

### ISSUE THREAD

**Issue by hostbbb** [bigbluebutton/bigbluebutton#12320]
**Describe the bug**
To leave audio,  have to click in audio icon, then scroll down and click "Leave Audio" when you have lots of devices.
Leave audio should just be selected, so no scrolling is required.

![image](https://user-images.githubusercontent.com/519542/117480375-82571180-af2f-11eb-90c6-449a62f07f86.png)

**Comment by antobinary** [comment]
Closely related https://github.com/bigbluebutton/bigbluebutton/issues/12089

**Comment by mariogasparoni** [comment]
Some suggestions i received (no specific priority or preference for each suggestion):

1. Add one scroll for Mic, other for speaker and make "Leave audio" label fixed at the bottom.
2. Only make "Leave audio" label fixed (and keep the scrollbar only for the device list).
3. Move the selector to the mute button, and add a second smaller button over mute that triggers the device selector. Something similar to what OP proposed in #9723
