### ISSUE TITLE
bibluebutton-dev-2.3 The video conference recording does not play

### ISSUE THREAD

**Issue by sonntagausgang** [bigbluebutton/bigbluebutton#12331]
**Describe the bug**
I installed the dev version of bigbluebutton 2.3. 
The video conference recording does not play on ios 14.5 safari 14.1.
It gives the following message: "No compatible source was found for this media"

**To Reproduce**
1. Go to the list of records
2. Click the presentation button in the playback column
3. After switching to the record, it returns an error

**Expected behavior**
Displaying the video conference recording playback interface

**Actual behavior**
Shows error: No compatible source was found for this media

**Screenshots**

<img src="https://user-images.githubusercontent.com/4164765/117538071-22cf3380-b00d-11eb-9e3b-d07a9f3c7b57.jpg" width="180">

**Smartphone (please complete the following information):**
 - Device: iPhone11Pro
 - OS: iOS14.5
 - Browser Safari
 - Version 14.1

**Additional context**

**Comment by jibon57** [comment]
You'll require to enable MP4 generation. https://docs.bigbluebutton.org/2.2/customize.html#enable-playback-of-recordings-on-ios

**Comment by testprepturkey** [comment]
Hi,

I have a question about the meetings. Here is the output of "sudo bbb-record --list"
![sss1](https://user-images.githubusercontent.com/62310973/117544581-d135a180-b02a-11eb-9815-0ad460c746c5.JPG)
The only X is always under the P of APVD. Is there something wrong with the recording? I tried "sudo bbb-record --rebuildall" command, too however, nothing changed.
Than you.

**Comment by ffdixon** [comment]
It means these meetings are only sharing a presentation (not audio 'A', video 'V', or screen share 'D').

**Comment by testprepturkey** [comment]
Actually, most of them are sharing a camera, screen, and audio.

**Comment by ffdixon** [comment]
Are the sessions started with "&record=true" on the `create` API call?   If so, you'll see data in these columns in `sudo bbb-record --list`.

**Comment by Orren19** [comment]
The link posted in order to help enabling MP4 generation leads to a « Page not found », any solutions ?

**Comment by datapack** [comment]
@jibon57 page not found

**Comment by jibon57** [comment]
This is the new link: https://docs.bigbluebutton.org/admin/customize.html#enable-playback-of-recordings-on-ios

**Comment by shahawiz** [comment]
This will fix your issue : https://hossamelshahawi.com/2021/11/19/fix-bigbluebuttom-player-issue-no-compatible-source-was-found-for-this-media/

**Comment by konfib** [comment]
Hi,
could someone tell until which version of BBB this **iOS** problem exists? 
And does BBB 2.5 version still needs to solve via enabling mp4?
**Enable playback of recordings on iOS** https://docs.bigbluebutton.org/admin/customize.html#enable-playback-of-recordings-on-ios

```
video_formats:
  - webm
  - mp4
```

Thanks a lot.
