### ISSUE TITLE
Have to leave TextCreate tool to make Text visible for all - Whiteboard

### ISSUE THREAD

**Issue by Strahlemann85** [bigbluebutton/bigbluebutton#12336]
**Describe the bug**
In Version 2.2.36 in was possbile to write with the textcreate tool on the whiteboard and all could see it. 
Now it is only visible, if you leave the text creation mode.

**To Reproduce**
Open Meeting and write text on the whiteboard and observe what happens as an attendee.

**Expected behavior**
Text ist visible while typing.

**Actual behavior**
Text is not visible while typing. 

**BBB version (optional):**
BigBlueButton Server 2.3.0 (2146)

**Desktop (please complete the following information):**
 - all

**Smartphone (please complete the following information):**
- all

Thanky for your deployment - BBB is a great plattform

**Comment by antobinary** [comment]
Merging into #12345
