### ISSUE TITLE
Screenshare not visible for few Attendees

### ISSUE THREAD

**Issue by Strahlemann85** [bigbluebutton/bigbluebutton#12334]
**Describe the bug**
If a moderator uses screenshare a few Attendees can not see it. They see only the rotating arrows.
The Attendees are using multiple browsers in the latest version. Also the connection status is not a note for thie error.

**Expected behavior**
All Attendees can see the screenshare, when the connection is good and the right browser is up-to-date.

**Actual behavior**
Some can not see the screenshare although the connection is good and the browser is right.

**BBB version (optional):**
BigBlueButton Server 2.3.0 (2146)

**Desktop (please complete the following information):**
 - OS: Windows, Mac
 - Browser Chrome, Safari, Firefox
 - Version up-to-date]

**Smartphone (please complete the following information):**
 - Device: iPad 7
 - OS: differently
 - Browser Safari
 - Version differently

**Comment by JustinMogel** [comment]
one observation i made: sharing a screen via firefox works significantly worse that with chrome.

often times when sharing my (2560x1080) desktop via firefox i often get infinite loading screen with chrome (and edge) when having both windows side by side.
   whe sharing the same with chrome or edge the screen sharing works fine (with the expectable delay and stuttering) 

when only sharing a certain window via firefox i sometimes have the screen sharing freeze in chrome (and edge), mostly whe the window gets too busy

**Comment by basisbit** [comment]
Possibly a duplicate of https://github.com/bigbluebutton/bigbluebutton/issues/11099

**Comment by Strahlemann85** [comment]
New and clean installation of version 2.3.1 solved the problem.
