### ISSUE TITLE
Failing to join a guestPolicy=ALWAYS_DENY meeting as guest doesn't display error message

### ISSUE THREAD

**Issue by KimBrodowski** [bigbluebutton/bigbluebutton#12335]
**Is your feature request related to a problem? Please describe.**
With BBB 2.3 moderators can update the guest policy of a meeting. In previous versions of BBB this was only possible when creating the meeting or by (javascript) console commands.

This means that a 3rd party user interface might not be aware of a meeting's current guest policy, allowing guests to generate join URLs even though they will be instantly rejected.

When this happens, guests are not informed as to why they were unable to join. Users receive a simple redirect to `/`.

**Describe the solution you'd like**
BBB already has 2 mechanisms to inform users of problems while joining a meeting. The guest lobby can display a message informing the user that their request to join was denied and there is a more generic way to display error messages on BBB's index page, e.g. `/?errors=[%7B%22message%22:%22You%20either%20did%20not%20supply%20a%20password%20or%20the%20password%20supplied%20is%20neither%20the%20attendee%20or%20moderator%20password%20for%20this%20conference.%22,%22key%22:%22invalidPassword%22%7D]`

Either option would work for me.

**Describe alternatives you've considered**
The problem could be dealt with by the 3rd party interface, however URLs might have been saved etc.

**Additional context**

Steps to reproduce:
1. Create a meeting with an ALWAYS_DENY guest policy. `/bigbluebutton/api/create?meetingID=test&name=Test&guestPolicy=ALWAYS_DENY` Alternatively you can update the guest policy of an existing meeting as a moderator.
2. Join the meeting as a guest. `/bigbluebutton/api/join?fullName=Kim%20Brodowski&password=secret&meetingID=test&guest=true`
3. The server answers with a `Location` header that redirects you to `/`.

**Comment by worldthumbler** [comment]
It would also be an idea to directly redirect to /signin or include a link to the login page in the error message. Since logging in will fix the "error"

**Comment by antobinary** [comment]
Let's verify this is handled in BBB 2.5
