### ISSUE TITLE
Give viewers who are the current presenter the ability to see raise hand dialog

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#12357]
**Is your feature request related to a problem? Please describe.**
A moderator may make a viewer (student) the current presenter.   Only moderators see the raise hand dialog box, so a viewer who has the presenter capabilities will not see it.

**Describe the solution you'd like**
Enable the presenter to see the raise hand dialog. 

**Describe alternatives you've considered**
Currently, we are only showing the raise hand to moderators.  We could modify the show hands dialog so it displays only to presenters, but don't give them ability to lower any hands.

**Additional context**
Our guiding principles for designs is that viewers can only do things that affect themselves, presenters can additionally affect the presentation area, and moderators can affect all users (such as muting and clearing emojis).  

We could keep this division but still show the raise hand dialog to the presenter, or let them lower hands as well (as it's what they may expect).

**Comment by mtsonline** [comment]
...I would allow them to lower the hands too. As they are interacting with the autdience, they also should be capable of reacting on them.
