### ISSUE TITLE
Text Annotation size on whiteboard scales with whiteboard size

### ISSUE THREAD

**Issue by maxjacobs283** [bigbluebutton/bigbluebutton#12350]
**Describe the bug**
If you write Text on the Whiteboard using the Text-Field input, the font size is rendered relative to the screen resoltuion and not scaled with Whiteboard size, but the Text is then resized to be displayed relative to the size on the Whiteboard. This causes 16px fonts to become significantly larger if BBB is not viewed in full screen. 

See this image:
![grafik](https://user-images.githubusercontent.com/75142597/117850827-fd992a00-b285-11eb-80f5-8ac97496eb8b.png)
It is written in a screen relative 16px font. But if I fullsize the window.
![grafik](https://user-images.githubusercontent.com/75142597/117850930-143f8100-b286-11eb-81f0-7e30439a95f9.png)
The font becomes significantly larger than before.

**To Reproduce**
1. Start a Meeting
2. Resize the window to be smaller in the horizontal axis (on windows, drag it to the side of the screeen)
3. Type text in any font size
4. Resize the window to fill the screen and see the text become massive

**Expected behavior**
Font size should be relative to the other text on the whiteboard. 

**Actual behavior**
Font size is relative to the screen of who ever typed the text and scales with whiteboard.

**Screenshots**
See description

**BBB version (optional):**
Tested on BigBlueButton Server 2.2.36 and 2.3.0

**Desktop (please complete the following information):**
 - OS: Windows, Mac
 - Browser Chrome, Safari, Edge, Firefox
 - Version Latest available at time of writing.

**Comment by antobinary** [comment]
Thanks for reporting!

> Tested on BigBlueButton Server 2.2.36 and 2.3.0

To clarify ... is this issue present in both 2.2.36 and 2.3.0?

**Comment by MaximilianJacobs** [comment]
Yes, it happens on both 2.3.0 and 2.2.36

**Comment by ramonlsouza** [comment]
issue is not present in 2.6
