### ISSUE TITLE
Polling: Problem with a ":" in a free text answer

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#12375]
Copied from https://groups.google.com/g/bigbluebutton-dev/c/bxwyTymzxiA

**Describe the bug**
someone entered a :) smiley. The result is shown a bit reformatted and
also changed to a bold text.

regards
Reimar

Frage der Umfrage
Pizza mit Annanas?

1: 1 |||||| 25%
2: 1 |||||| 25%
3: 1 |||||| 25%
4:-): 1 |||||| 25%

Umfrageoptionen
1: Bah!
2: Lecker, sagt mein Mann
3: das ist eine Hawai Pizza
4:

**BBB version (optional):**
BigBlueButton Server 2.3.0

**Comment by pedrobmarin** [comment]
Hey @germanocaumo , could you take a look at this one?
