### ISSUE TITLE
If the Internet is weak, users are removed from the meeting

### ISSUE THREAD

**Issue by GyR4uk** [bigbluebutton/bigbluebutton#12377]
Some of our users complain that when the Internet is weak, they are often removed from the conference.

How it happens:
1) Join a meeting with a weak internet
2) There are constant interruptions in connection with the web socket (the audio itself reconnects)
3) As a result, the user is removed from the conference with an error of 403.

**Comment by basisbit** [comment]
For support requests, please use the [forum / mailing list](https://groups.google.com/forum/#!forum/bigbluebutton-setup). This issue tracker here is only for BBB development related issues. Sorry.

**Comment by saeed-parsaee** [comment]
this seems to be a development bug. this happen to us on 2.4.2 occasionally on all of our servers and many users.
