### ISSUE TITLE
Bug on mobile: cameras are dispalying on the right by default if the board width is small causing several problems

### ISSUE THREAD

**Issue by moh85** [bigbluebutton/bigbluebutton#12383]
Hello,
I have a problem when using the latest version of BBB on mobile if the board width is small (for example presenting a PDF - A4 size / a portrait image).
I tested the bug on multiple Android devices on Chrome.
The old version default cameras position was "On Top", above the board whatever it's width and height since it's the perfect UX for users and the boar will always be the bigger part in the page.

In the new version, the user must drag the cameras manually and place it on top, if not, the board will look very buggy (big font size, the board options are not visible correctly) as you can see here:

![pic1](https://i.imgur.com/qXCjZ6i.png)

Comparing to the old versions, you can see that the default look was perfect:

![pic2](https://i.imgur.com/e7h8hQB.png)

------------------------------------------------------------------------

Any idea to solve the problem temporary?

I think we can work this around if there's a setting to set the default camera position to be on "top".

Thank you.

**Comment by mabras** [comment]
This is also reported in mailling list:
https://groups.google.com/g/bigbluebutton-dev/c/smtcynsWmOw/m/4_KuXOsPAwAJ

**Comment by valerio-bozzolan** [comment]
(There is a typo in the title: -dispalying +displaying. Sorry for my comment!)
