### ISSUE TITLE
Customize Icon in Title Bar in Version 2.3

### ISSUE THREAD

**Issue by Mustakim-78** [bigbluebutton/bigbluebutton#12389]
**Describe the bug**
I have changed the favicon.ico in /var/www/bigbluebutton-default and replaced it with the new one.
but it is not updated in the meeting.

**Expected behavior**
An icon is replaced with a new one in the title bar

**Actual behavior**
Still, the old bbb icon is displayed in the meeting in the title bar.

**Screenshots**
![Screenshot (113)_LI](https://user-images.githubusercontent.com/59732290/118399916-17b77b80-b67d-11eb-8ae9-ae2a6bacf321.jpg)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, Mac]
 - Browser [e.g. Chrome, Safari]

**Smartphone (please complete the following information):**
 - Browser [e.g. stock browser, Safari]

**Additional context**

**Comment by Buda9** [comment]
in bbb 2.3 sometimes reboot is necessary for changes to appy

**Comment by mabras** [comment]
```
rm /var/www/bigbluebutton-default/images/favicon.png
```

**Comment by antobinary** [comment]
Looks like this customization question was fully answered! Thanks all!
