### ISSUE TITLE
Please Publish Ubuntu Package Names in Release Notes

### ISSUE THREAD

**Issue by aogilvie** [bigbluebutton/bigbluebutton#12385]
If the project is not going to update previous release notes. I would like especially beta 1 package name.

Alpha packages were named `bionic-230-dev-alpha7` we tried bionic-230-dev-beta1 but no packages exist.

If there are beta packages, would it be possible for a common visioning system?

**Comment by basisbit** [comment]
If I may ask, why do you want to deploy old non-stable versions of BBB?

**Comment by aogilvie** [comment]
At the time we deployed and tested alpha 7. Then we found a critical bug with presentation display in production. The commit that fixes this bug is in the not open source Ubuntu Akka apps package. Since the packaging scripts are not open source we cannot build the package with the 3 line code change ourselves. Thus we require the specific package with that commit at the closest version to what we have deployed.

You should be careful labelling "Old non stable versions" as bigbluebutton releases. If all prior to current releases are unstable it means even the current is unstable as that will soon become a prior release itself. In which case it makes no sense to update because all versions are inherently unstable.

**Comment by basisbit** [comment]
So, you'd be happy as soon as those closed source things are finally all open sourced?

**Comment by aogilvie** [comment]
This ticket can be closed if package names are going to included in release notes. Open sourcing the packaging scripts however is a separate discussion; one that I've already had many times with the BBB team to unfortunately no avail.

**Comment by antobinary** [comment]
@aogilvie 

![Screenshot from 2021-05-19 11-40-56](https://user-images.githubusercontent.com/6312397/118842360-224d5d00-b897-11eb-8c0c-e885b7b53f0f.png)
I just updated the 2.3.0 and 2.3.1 release notes - this is at the very bottom.

Is this the information you were looking for?

**Comment by aogilvie** [comment]
Perfecto!
