### ISSUE TITLE
External videos work with https:// URLs, but not with http://

### ISSUE THREAD

**Issue by rauferd** [bigbluebutton/bigbluebutton#12390]
In BBB, build: 1720, I can share an external video directly, using an URL like this: `https://.../video.mp4`
I cannot share the same video using the URL without SSL/TLS: `https://.../video.mp4`.

**To Reproduce**
1. In a BBB session, click Actions (+) -> Share an external video
2. Type or paste any video URL starting with http://

**Expected behavior**
The share video button should become "clickable" when a valid URL is typed/pasted. BBB should be able to play the video.

**Actual behavior**
A red message pops up, saying
> This video URL isn't supported
The "Share a new video" button cannot be clicked in this situation.
Btw. this even happens, when I paste a valid URL and delete the "s" afterwards. No https, no video.

**BBB version (optional):**
The "About" window says: Client build: 1720 (I am not a server admin, but I could find out the precise version, if required.

Tested with Firefox 89.0b12 on Debian Linux 10, but it doesn't work with my iPad or Android Smartphone either.

**Additional context**
Unfortunately, some web servers do not offer https or do so using self-signed certificates that the users would have to import/confirm, etc. In this situation (wanting to share a _public_ video from the _public internet_ anyway), I personally do not care about the implications of causing non-encryted web traffic. I would prefer to have it "just work".

**Possible solution**
Maybe the solution is to change only one line in `bigbluebutton-html5/imports/ui/components/external-video-player/service.js`:
```
const isUrlValid = (url) => {
  return /^https.*$/.test(url) && (ReactPlayer.canPlay(url) || Panopto.canPlay(url));
}
```
to
```
const isUrlValid = (url) => {
  return /^http.*$/.test(url) && (ReactPlayer.canPlay(url) || Panopto.canPlay(url));
}
```

But I am not sure about the solution and did not try it, since I have no BBB instance running myself. I am only a user, not a server admin.

And of course, some servers serve only https pages, no http at all. I would certainly not want to break https-only videos.

**Comment by pedrobmarin** [comment]
Hi @rauferd . This is intentional.

Mixing secure/unsecure content is something some browsers already [block by default](https://security.googleblog.com/2019/10/no-more-mixed-messages-about-https_3.html).

**Comment by rauferd** [comment]
Thank you for the information.

Could you then please update the expanatory text "Note: Shared external videos will not appear in the recording. YouTube, Vimeo, Instructure Media, Twitch, Dailymotion and media file URLs (e.g. https://example.com/xy.mp4) are supported." to something like "Note: Shared external videos will not appear in the recording. YouTube, Vimeo, Instructure Media, Twitch, Dailymotion and media file URLs (**via https only,** e.g. https://example.com/xy.mp4) are supported."

That would have saved me 2 hours yesterday, plus your time and mine spent with this issue report.

**Comment by pedrobmarin** [comment]
But I love spending time with the community 🙂

**Comment by rauferd** [comment]
By the way, mixing secure and insecure content works just fine in my setup (BBB in Firefox 89).

To find out, I just tested the following:
In a BigBlueButton conference, enter the URL of a http-only video, but with the extra s (in http**s**). The result is: I can click the "Share new video" button, but obviously no video is played, since the URL does not exist.

Then, using the Firefox Web Developer Tools, I remove the "s" again. The insecure video will play just fine in the secure BBB conference.

I understand that this is bad practice, though and I agree that BBB should not encourage users to mix secure and insecure content.
