### ISSUE TITLE
Display consent field before activating dictation

### ISSUE THREAD

**Issue by ichdasich** [bigbluebutton/bigbluebutton#12393]
**Is your feature request related to a problem? Please describe.**
When the dictation feature is enabled, users can use google chrome's voice recognition API to auto-transcribe text. However, this means that the users' voice is processed by google's systems. It would be nice to have a consent pop-up when (first) clicking this button, so users still pertain a conscious choice when activating this feature, and are appropriately informed about the implications.

**Describe the solution you'd like**
When clicking the 'start dictation' button, a pop-up should occur which briefly describes what will happen. Users can then click 'consent/ok' to start the dictation, or 'cancel', if they do not consent to the processing of their speech by google.

**Describe alternatives you've considered**
The absence of this feature currently means that i can not activate that feature on my setup.

**Comment by ffdixon** [comment]
The current dictation for Google Voice was experimental.  We're working on a new dictation interface for Google Voice that should be better.

**Comment by antobinary** [comment]
I am reopening this one as it likely is at least partly relevant to the upcoming [2.6] closed captions implementation.
