### ISSUE TITLE
Camera/Video Feed squeezed when using HDMI capture card

### ISSUE THREAD

**Issue by felixdimmerling** [bigbluebutton/bigbluebutton#12397]
**Describe the bug**
Camera/Video Feed is squeezed when using HDMI capture card with a (Mirrorless) Camera. The Camera records (and outputs) a video signal in 16:9 which gets squeezed (not cropped) into 4:3.

**To Reproduce**
1. Open the share webcam menu
2. Look at the preview window and see the distorted feed

**Expected behavior**
Either the feed being fully shown in the webcam window by putting black bars at the top and bottom or the image being cropped in to leave out the sides and make it smaller.

**Actual behavior**
The whole image area gets squeezed into 4:3.

**Screenshots**
![Screenshot 2021-05-18 at 08 59 15](https://user-images.githubusercontent.com/38992356/118606280-813ba500-b7b7-11eb-9b8f-fc8af242a6ba.png)
The keys are actually square.

**BBB version (optional):**
Client build: 1157 (This is the only info I could get)

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser Chrome, Safari
 - Version Chrome (90.0.4430.212), Safari (14.1)

**Additional context**

**Comment by prlanzarin** [comment]
Capture being squeezed in 4:3 default aspect ratio seems out of our reach since 1) we're not scaling the local preview 2) capture is done by browsers.

Since the original aspect ratio is 16:9, try it out in test23.bigbluebutton.org with the **HIGH** and **HIGH QUALITY** camera profiles. Both of them try to priotize 16:9 aspect ratio.

Also try to reproduce this in https://webrtc.github.io/samples/src/content/getusermedia/gum/.

**Comment by kaixxx** [comment]
I have the exact same problem (on windows using firefox with a usb hdmi capture device).

I have tried your suggestions - "test23.bigbluebutton.org" is giving me a connection error. 

https://webrtc.github.io/samples/src/content/getusermedia/gum/ shows the exact same problem, image ist squished.

But if I go to [https://webrtc.github.io/samples/src/content/getusermedia/resolution/](https://webrtc.github.io/samples/src/content/getusermedia/resolution/), I can see that only the VGA-resolution is squished, "HD" and "Full HD" is working fine.

Hope this helps.

(It seems to be an older issue, see #9463 
As I do not have access to the server, I cannot change any settings there.)

**Comment by prlanzarin** [comment]
> As I do not have access to the server, I cannot change any settings there.

Can't really do much.
Constraints are configurable for this sole reason.
