### ISSUE TITLE
2.3.1 Raise hand feature should be optional

### ISSUE THREAD

**Issue by aogilvie** [bigbluebutton/bigbluebutton#12396]
In a setup where there are only ever one presenter and one participant this feature is not necessary.

It should be customisable like other features (video upload, polling etc.)

![example](https://user-images.githubusercontent.com/970364/118588440-5b26fc80-b7d9-11eb-90ea-915ca1a9dc33.png)

**Comment by JorritDeKlerk** [comment]
I second that.

**Comment by antobinary** [comment]
Let's introduce `public.app.raiseHandActionButton.enabled: true`
This setting will not display the raise hand easy to access button when the value is `false`.

The problem is that it would be much better if we could control whether to display or not on a per-meeting basis, rather than per-server...
