### ISSUE TITLE
Chat message liking functionality would be quite useful

### ISSUE THREAD

**Issue by theocheslerean** [bigbluebutton/bigbluebutton#12403]
It would be cool if we could "like" chat messages since I noticed while using the BBB with a big group of people that many of them are responding with "+1" at different questions or messages from the audience to support them. And these "+1"s quickly fill up the chat window and push the relevant messages towards the top and beyond.
I saw there is an issue for emoji functionality but not one for "likes". I am sorry if I missed it and created a duplicate.

**Comment by rasos** [comment]
MS Teams or RocketChat count the number of thumbs up in the chat message.
