### ISSUE TITLE
feat: Allow to move camera in front of presentation

### ISSUE THREAD

**Issue by mschwrdtnr** [bigbluebutton/bigbluebutton#12409]
**Is your feature request related to a problem? Please describe.**
Back to version 2.2.3x it was possible to move the camera in front of the presentation. Since 2.3 this isn't possible. This feature is nice to have for people with a small screen to have a better view on the presentator and the presentation. Currently it's only possible to move the camera to left, right, top and bottom of the presentation.

**Describe the solution you'd like**
Like v.2.2.3x I want to be allowed to move the camera in front of the presentation.
![grafik](https://user-images.githubusercontent.com/39745446/118774116-c928fd80-b885-11eb-8155-64238667b422.png)

**Describe alternatives you've considered**
No alternatives.

**Additional context**
This feature request was already working in v2.2.3x.

**Comment by ffdixon** [comment]
In Chrome you can right-click on the video and chose "Picture in Picture" and have a floating webcam window that you can move anywhere on your screen.

**Comment by mschwrdtnr** [comment]
Thanks for your answer. This is not the solution I want, but I am fine with that.
