### ISSUE TITLE
Configure for multiple stun servers produces error/warning messages v2.2 and v2.3

### ISSUE THREAD

**Issue by caniwi** [bigbluebutton/bigbluebutton#12407]
**Describe the bug**
The file /usr/share/bbb-web/WEB-INF/classes/spring/turn-stun-servers.xml has the capability to define multiple stun servers. After doing so, bbb-conf --status seems fine but bbb-conf --check shows problems.

v2.2 last lines of bbb-conf --check

/usr/share/bbb-web/WEB-INF/classes/spring/turn-stun-servers.xml (STUN Server)
                              
\# Potential problems described below
\# Error: Unable to connect to port 1935 (RTMP) on uat-bbb1.catalystdemo.net.nz
\# Warning: The setting of 202.49.241.90 for proxy_pass in
\#
\#    /etc/bigbluebutton/nginx/sip.nginx
\#
\# does not match the local IP address (10.15.8.114).
\# (This is OK if you've manually changed the values)

v2.3 last lines of bbb-conf --check
/usr/share/bbb-web/WEB-INF/classes/spring/turn-stun-servers.xml (STUN Server)
                              stun: 
/etc/kurento/modules/kurento/WebRtcEndpoint.conf.ini (STUN Server)
                              stun: 150.242.43.125:3478
\# Potential problems described below
\# Warning: The setting of 150.242.42.213 for proxy_pass in
\#
\#    /etc/bigbluebutton/nginx/sip.nginx
\#
\# does not match the local IP address (10.15.8.128).
\# (This is OK if you've manually changed the values)
\#
\# Warning: Failed to verify STUN server at  3478 with command
\#
\#    stunclient --mode full --localport 30000  3478
\#

**To Reproduce**
1. Update /usr/share/bbb-web/WEB-INF/classes/spring/turn-stun-servers.xml to have multiple stun servers.
2. bbb-conf --restart
3. bbb-conf --status seems okay
4. bbb-conf --check shows problems

**Expected behavior**
No warning messages.

**Actual behavior**
Error messages as per above and attachments.

**Screenshots**
See attached txt files.

**Desktop (please complete the following information):**
N/A this is a server issue

**Smartphone (please complete the following information):**
N/A this is a server issue

**Additional context**
More than 1 stun server adds resilience to the solution and it appears the config file supports it.
[uat1-bigbb-multiple-stun-servers.txt](https://github.com/bigbluebutton/bigbluebutton/files/6504694/uat1-bigbb-multiple-stun-servers.txt)
[uat2-bigbb-multiple-stun-servers.txt](https://github.com/bigbluebutton/bigbluebutton/files/6504695/uat2-bigbb-multiple-stun-servers.txt)

**Comment by hiroshisuga** [comment]
may be related to #10746 and #10764 (people there would find this useful) . In my 2.3a3 setup, bbb-conf --check does not give error, but neither show up any STUN server.

**Comment by caniwi** [comment]
This appears fixed in 2.3, we no longer run 2.2.
