### ISSUE TITLE
Simultaneous Users Support in 2.3.1

### ISSUE THREAD

**Issue by itzurkarthi** [bigbluebutton/bigbluebutton#12401]
HI,

I would like to know how many users (1 presenter with webcam and presentation - other users will join via listen only mode with chat option) can **BBB 2.3.1** can support in a single meeting on AWS c5.4xlarge instance

**Instance details**
16 core CPU
32 GB RAM

enableMultipleKurentos is ON

**_My previous version BBB 2.2.2 can't handle more than 90 users - meeting slows down after 90th user and can't change the slide.._**

Please let us know.

**Comment by prlanzarin** [comment]
Please use the mailing lists for those kind of inquiries.
