### ISSUE TITLE
Add BBB version to About screen

### ISSUE THREAD

**Issue by Nyco** [bigbluebutton/bigbluebutton#12417]
**Is your feature request related to a problem? Please describe.**
As a simple user sometimes, I need to know the version I am using, in order to report issues properly for example

**Describe the solution you'd like**
In the about screen, a version is displayed, but it is not the SemVer/public version

**Describe alternatives you've considered**
Not sure yet, but indeed there might be other places

**Additional context**
None

**Comment by pedrobmarin** [comment]
Duplicate of #10443
