### ISSUE TITLE
Language selection from browser/system is not working in most browsers

### ISSUE THREAD

**Issue by prazape** [bigbluebutton/bigbluebutton#12413]
**Describe the bug**
We are a Czech company using several BBB2.2 servers and now I have installed two new with BBB2.3. (manual install by step-by-step manual) We use our custom made administration to create and manage meetings/rooms. 

When I open meeting on BBB2.2 a czech language UI appears (when I have czech browser/system). But if I do the same (on the same system) with BBB2.3 the UI opens in english and users have to go to settings to change that. Which is quite unpleasant for our clients who expects czech language.

**To Reproduce**
1. Open a meeting in czech browser (i assume another non-eng. languages will behave the same, but have no such to test on)
2. See english UI (= error)

**Expected behavior**
Language of the UI is selected from the language list in the browser.

**Actual behavior**
For some reason I always get an english UI.

**BBB version (optional):**
root@atlantis:~# sudo bbb-conf --check | grep BigBlueButton
BigBlueButton Server 2.3.1 (2209)

**Desktop (please complete the following information):**
 - OS: Win10
   Browser: Firefox 88, Edge (should be 90.0.818.62)
   (but it is working like it should on chrome 90.0 itself!)

 - OS: Win10
   Browser: Firefox,  Edge, Chromium

 - OS: CentOS 7
   Browser: Firefox 78.10, Chromium 89.0.4389.90 (Developer Build) Fedora Project 
 
Versions only on my setup or where I was personaly nearby while testing, but several colleaques tested it with the same result.

PS: At the begining I tried to use .json downloaded directly from transifex after enhancing the translation but I was unable to select it. It showed only the 3 dots loading animation for ever... Were there some changes regarding using custom language .json files?
(Did this only on one of those servers and reinstaled it from pre BBB snaphost for other reasons after)

**Comment by antobinary** [comment]
Hi @prazape,

I just tried this and yes, was able to reproduce.

1) In Transifex in both 2.2 and 2.3 we have the same locale name for Czech  - `cs_CZ` ( **note to devs that this is CZ, not cs_CS** )

2) When I set my Chromium to Czech, it seems it looks for `cs`, not `cs_CZ`

3) In 2.3 we redid how we pick up locales (lots of changes, so far vastly positive). I suspect that since most locales have the same letters repeating ab_AB this is a problem for Czech due to not following the pattern - ab_AC

We'll take a look at this, thanks for reporting!


### Temporary solution for your 2.3 servers if you this was the only thing stopping you ( ** note that this will be reset when you update bbb-html5 package **)

```
# rename the locales file from cs_CZ.json to cs.json
root@droplet-5853:/usr/share/meteor/bundle# mv ./programs/web.browser/app/locales/cs_CZ.json ./programs/web.browser/app/locales/cs.json

root@droplet-5853:/usr/share/meteor/bundle# grep -irn cs_CZ
programs/web.browser/program.json:115:      "path": "app/locales/cs_CZ.json",
programs/web.browser/program.json:119:      "url": "/locales/cs_CZ.json",
programs/web.browser.legacy/program.json:115:      "path": "app/locales/cs_CZ.json",
programs/web.browser.legacy/program.json:119:      "url": "/locales/cs_CZ.json",

# edit cs_CZ.json to cs.json in these two files
root@droplet-5853:/usr/share/meteor/bundle# vim programs/web.browser/program.json
root@droplet-5853:/usr/share/meteor/bundle# vim programs/web.browser.legacy/program.json 

# restart the service so it takes effect
root@droplet-5853:/usr/share/meteor/bundle# systemctl restart bbb-html5


```

**Comment by antobinary** [comment]
To whoever is going to work on this, please check with the following locales - 

cs_CZ
zh_CN
zh_TW
el_GR

Looks like the pattern is not really a pattern after all...

**Comment by prazape** [comment]
Hi @antobinary,
thank you for quick response.

The workaround is working, it was not stopping us from "production" but we can now move to client tests. We still have some customizing to do so I still for example look forward to #12365 as we have some custom logic build around that.
We use BBB since something like version 1 so I am used to lose my changes and I use (my own) ansible to set things up. :)

I have additional question:
We use czech in BBB 2.2 just after release, when I even had to add it manually as it was not yes there and it sticked to us to use our custom translation with some phrases translated a bit different. (even if we were authors of most of the czech translation)
In the past it was enough to just edit the cs_CZ.json but If i look correctly now I have to update the /usr/share/meteor/bundle/programs/web.browser/program.json with the correct size and hash of the language .json file?
Can you tell me / guide me where to find what hash function is used and how is it counted?

Regards,
Prazape
