### ISSUE TITLE
Send a semi-private message by specifying multiple recipients through the chat panel

### ISSUE THREAD

**Issue by hiroshisuga** [bigbluebutton/bigbluebutton#12415]
**Is your feature request related to a problem? Please describe.**
Currently you can send a message to everyone through the chat panel (public chat), and send a private message to one single person through the user list panel (private chat). However, we may want to send a message to, say, only 10 persons out of 100 participants. 
Students are frustrated in finding out a way to send a message by specifying multiple recipients on the chat panel, not from the user list panel which is kind of hidden.

**Describe the solution you'd like**
In the chat panel, you can specify recipients of the message, similar to the UI that Zoom implements.

**Additional context**
Ideally, we may want to drag and drop the icons in the user list panel to the chat panel to specify the recipients.

Related to #4989..?

**Comment by GhaziTriki** [comment]
This is chat groups feature from the Flash client. The backend components are ready, we just need to port the work into the HTML5 client.

**Comment by hiroshisuga** [comment]
I still would like to have this feature.
