### ISSUE TITLE
Implementing LaTeX math mode in public chat

### ISSUE THREAD

**Issue by IgnisArdere** [bigbluebutton/bigbluebutton#12421]
As an engineering student who will be attending online lessons for quite a while, being able to interact with the professor by typing down equations clearly would be super helpful. 

For example:
"My solution would be $\frac{-b \pm \sqrt{b^2-4ac}}{2a}$"
and the text shown would be normal for "my solution would be" and symbols for the equation.

**Comment by hiroshisuga** [comment]
duplicate of #5730
