### ISSUE TITLE
Recordings are always saved at 5 FPS

### ISSUE THREAD

**Issue by ivdorelian** [bigbluebutton/bigbluebutton#12436]
**Describe the bug**
No matter how smooth a webcam or screen share goes, the recording is always saved at 5 FPS and 720p resolution, despite configs choosing otherwise and enough bandwidth.

**To Reproduce**
1. Start a session in greenlight
2. Record it
3. Share the screen, type something, select some text, move things around a bit
4. View the recording, it is laggy and low quality
5. `mediainfo deskshare.mp4` in `/var/bigbluebutton/published/presentation/xzy` will output `Frame rate 5.000 FPS` and 720p resolution.

**Expected behavior**
A higher frame rate and resolution should be used - my upload speeds can definitely handle more than 5 FPS and so can my server.

**Actual behavior**
I even put this into `/etc/bigbluebutton/bbb-conf/apply-config.sh` with no success, the above still happens:

```
#!/bin/bash

# Pull in the helper functions for configuring BigBlueButton
source /etc/bigbluebutton/bbb-conf/apply-lib.sh

enableUFWRules
enableMultipleKurentos

KURENTO_CONF="/usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml"
BBB_PROPERTIES="/usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties"


echo "  - Setting HTML5 Client"
# Set Framerate and Resolution to high values - it will be throttled through bitrate
yq w -i $HTML5_CONFIG public.kurento.screenshare.constraints.video.frameRate.ideal 30
yq w -i $HTML5_CONFIG public.kurento.screenshare.constraints.video.frameRate.max 60
yq w -i $HTML5_CONFIG public.kurento.screenshare.constraints.video.width.max 2560
yq w -i $HTML5_CONFIG public.kurento.screenshare.constraints.video.height.max 1440
# Enable option to share screen with audio in supported browsers
yq w -i $HTML5_CONFIG public.kurento.screenshare.constraints.audio true
yq w -i $HTML5_CONFIG public.app.skipCheck false

echo " - Setting Screenshare and Video Constraints"
yq w -i $KURENTO_CONF conference-media-specs.H264.tias_content 3000000
yq w -i $KURENTO_CONF conference-media-specs.H264.as_content 3000
```

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac OS Big Sur
 - Browser: tested on FF and Safari. The in-browser screen share on safari is smoother and visibly above 5 FPS.
 - Version FF 88.0.1, Safari 14.0.3

**Smartphone (please complete the following information):**
Not tested.

**Additional context**
BBB installed using the install.sh script on Ubuntu 18.04 running on a gcloud VM with 4 cores and 6 GB RAM. During the screenshare, cpu load is at most 2 and RAM usage below 45%.

**Comment by jibon57** [comment]
Most probably because of this setting:
https://github.com/bigbluebutton/bigbluebutton/blob/b6625fc5b80fe0c6849c3419cbdc1260808d16b9/record-and-playback/presentation/scripts/presentation.yml#L8

So, you can edit this file: `/usr/local/bigbluebutton/core/scripts/presentation.yml` of your BBB server.

**Comment by ivdorelian** [comment]
> Most probably because of this setting:
> 
> https://github.com/bigbluebutton/bigbluebutton/blob/b6625fc5b80fe0c6849c3419cbdc1260808d16b9/record-and-playback/presentation/scripts/presentation.yml#L8
> 
> So, you can edit this file: `/usr/local/bigbluebutton/core/scripts/presentation.yml` of your BBB server.

That did it! The videos are still just a bit blurry - are there any other settings I can add there to increase the quality? I changed the framerate and the resoluton to 1080p.

Either way, thank you, it's very usable now.

**Comment by prlanzarin** [comment]
Original inquiry solved.

I suggest using the mailing lists for this kind of inquiry next time around.
