### ISSUE TITLE
Screenshare very low framerate and freezes

### ISSUE THREAD

**Issue by misisol** [bigbluebutton/bigbluebutton#12437]
**Describe the bug**
After Installing 2.3.1 version on a fresh Ubuntu 18.04, Screensharing became very unstable and freezes a lot. It has very low frame rate which makes it unusable.

I've changed first changed the screenshare.**bitrate** &  screenshare.constraints.video.frameRate.**ideal** & screenshare.constraints.video.frameRate.**max** ( settings.yml )  attributes to a higher values to have a greater frame rate but it doesn't seems to have any effects.
Next I've changed **tias_content** & **as_content** (bbb-webrtc-sfu/config/default.yml ) but it also didn't made any changes.

This problem is not happening on our servers on 2.2.x version of bigbluebutton. Is there anything that can be done?

( This problem is not reproduce able on test.bigbluebutton.com server **because** it seems to be still on 2.2.x version )

**Comment by PhMemmel** [comment]
Use test23.bigbluebutton.org for trying to reproduce.

**Comment by misisol** [comment]
> Use test23.bigbluebutton.org for trying to reproduce.

Thanks for reply. I've Checked but could made the test because the freezing and low frame rate happens only to client not the one who shares the screen.
Is there any way to have a 2 participant meeting on test servers to check it out?

**Comment by ffdixon** [comment]
You can use https://demo.bigbluebutton.org/ to test multiple people in a session on BigBlueButton 2.3.

**Comment by misisol** [comment]
> You can use https://demo.bigbluebutton.org/ to test multiple people in a session on BigBlueButton 2.3.

Thanks for answering. I've checked it and the result got worse. 
First the rotating circle shows up, but after 1 minute it goes black and then after some time it comes out of screen share mode and shows 1020 error.
On the attendee side, it remains on default presentation and does not react to screen share mode.


![Screen Shot 2021-05-24 at 4 23 16 PM](https://user-images.githubusercontent.com/26188869/119344931-831cd100-bcad-11eb-89cc-dfc3b2144922.jpg)

**Comment by misisol** [comment]
I've installed a 2.3.1 version on a fresh installed ubuntu 18.04.5 again.
This time I was looking closer.
After installation the screen sharing works as expected. But I've decided to leave the server as it is and check it out again later. 12 hours later, the problem got back without doing any custom configuration.

`BigBlueButton Server 2.3.1 (2209)
                    Kernel version: 4.15.0-143-generic
                      Distribution: Ubuntu 18.04.5 LTS (64-bit)
                            Memory: 16379 MB
                         CPU cores: 32

/etc/bigbluebutton/bbb-web.properties (override for bbb-web)
/usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties (bbb-web)
       bigbluebutton.web.serverURL: https://HOST
                defaultGuestPolicy: ALWAYS_ACCEPT
                 svgImagesRequired: true

/etc/nginx/sites-available/bigbluebutton (nginx)
                       server_name: HOST
                              port: 80, [::]:80
                              port: 443 ssl

/opt/freeswitch/etc/freeswitch/vars.xml (FreeSWITCH)
                       local_ip_v4: SERVER_IP
                   external_rtp_ip: SERVER_IP
                   external_sip_ip: SERVER_IP

/opt/freeswitch/etc/freeswitch/sip_profiles/external.xml (FreeSWITCH)
                        ext-rtp-ip: $${local_ip_v4}
                        ext-sip-ip: $${local_ip_v4}
                        ws-binding: SERVER_IP:5066
                       wss-binding: SERVER_IP:7443

/usr/local/bigbluebutton/core/scripts/bigbluebutton.yml (record and playback)
                     playback_host: HOST
                 playback_protocol: https
                            ffmpeg: 4.2.4-1ubuntu0.1bbb2~18.04

/etc/bigbluebutton/nginx/sip.nginx (sip.nginx)
                        proxy_pass: SERVER_IP
                          protocol: http

/usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml (Kurento SFU)
                        kurento.ip: SERVER_IP
                       kurento.url: ws://127.0.0.1:8888/kurento
                    kurento.sip_ip: SERVER_IP
                    localIpAddress: SERVER_IP
               recordScreenSharing: true
                     recordWebcams: true
                  codec_video_main: VP8
               codec_video_content: VP8

/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml (HTML5 client)
                             build: 1720
                        kurentoUrl: wss://HOST/bbb-webrtc-sfu
                  enableListenOnly: true
                    sipjsHackViaWs: true

/usr/share/bbb-web/WEB-INF/classes/spring/turn-stun-servers.xml (STUN Server)
                              stun: turn.host`

**Comment by papinaser** [comment]
> **Describe the bug**
> After Installing 2.3.1 version on a fresh Ubuntu 18.04, Screensharing became very unstable and freezes a lot. It has very low frame rate which makes it unusable.
> 
> I've changed first changed the screenshare.**bitrate** & screenshare.constraints.video.frameRate.**ideal** & screenshare.constraints.video.frameRate.**max** ( settings.yml ) attributes to a higher values to have a greater frame rate but it doesn't seems to have any effects.
> Next I've changed **tias_content** & **as_content** (bbb-webrtc-sfu/config/default.yml ) but it also didn't made any changes.
> 
> This problem is not happening on our servers on 2.2.x version of bigbluebutton. Is there anything that can be done?
> 
> ( This problem is not reproduce able on test.bigbluebutton.com server **because** it seems to be still on 2.2.x version )

HI,
Do you find any solution for screen share freezing?

**Comment by axkibe** [comment]
Just had the same issue on a live talk... I cannot reproduce it locally tough. Anything from the server logs that can help?

**Comment by misisol** [comment]
@axkibe I've fully reinsalled OS and installed BBB again to make it work again. Still don't know that the problem was.

**Comment by m2msoft** [comment]
I am experiencing the same lag.

Every time I turn a page in PowerPoint, there is a delay of about 5-10 seconds.
When the PowerPoint page is not turned, there is only a difference of 1-2 seconds when it is displayed.
Web pages with a black background seem to be displayed in real time. However, web pages with a white background are also very lag.

The same is true when using it alone.

We installed it on a VM. Could it be different depending on the installed server?

**Comment by axkibe** [comment]
Also on VM if it helps (but assigned 8 cores to it).
But it was only with that one presenter, otherwise it runs just fine.

**Comment by misisol** [comment]
> I am experiencing the same lag.
> 
> Every time I turn a page in PowerPoint, there is a delay of about 5-10 seconds. When the PowerPoint page is not turned, there is only a difference of 1-2 seconds when it is displayed. Web pages with a black background seem to be displayed in real time. However, web pages with a white background are also very lag.
> 
> The same is true when using it alone.
> 
> We installed it on a VM. Could it be different depending on the installed server?

Our servers are all dedeicated with now virtualizaton, so I can't help.
