### ISSUE TITLE
Allow to hide Settings->Guest Waiting Approval

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#12444]
(...)Is it possible to hide the guest related notification setting as well and cannot find any hints on that question.

User-Settings -> Notifications -> Guest Waiting Approval

_Originally posted by @dahrens in https://github.com/bigbluebutton/bigbluebutton/issues/12361#issuecomment-848731265_

![Screenshot from 2021-05-26 09-18-47](https://user-images.githubusercontent.com/6312397/119666735-a2c60d80-be03-11eb-8f23-7c1574f097e1.png)

**Comment by pedrobmarin** [comment]
I'd say to create a new setting property for this because it does not relate with the `dynamicGuestPolicy `

**Comment by pedrobmarin** [comment]
Another suggestion: use the guest policy to show this option.

Makes sense to have this visible only when the policy is `ASK_MODERATOR`.
