### ISSUE TITLE
Breakout room recording

### ISSUE THREAD

**Issue by erpsolns** [bigbluebutton/bigbluebutton#12448]
**Is your feature request related to a problem? Please describe.**
I have a need for recording breakout rooms.  
**Describe the solution you'd like**
I cant find recording buttons in breakout rooms.
I request sincerely either a) a custom code for me to use to enable recording of break out rooms
or b) Pull requests to enable a button in breakoutrooms to record

**Describe alternatives you've considered**

**Additional context**

**Comment by erpsolns** [comment]
I saw this https://github.com/bigbluebutton/bigbluebutton/issues/9872.  
"change the value of breakoutRoomsRecord in your bigbluebutton.properties to true and restart your server"   I am looking forward to the directory/file path to find this please in a standard bbb-install.sh install 2.3.1

**Comment by erpsolns** [comment]
I found out the file 2.3.1   at  /usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties line 368

**Comment by erpsolns** [comment]
For everyone's record: The recording of breakout room are there in the published folder each breakoutroom separately- they are  published - But in Greenlight these breakoutroom recordings are not showing up.  If anyone can think about any configuration for Greenlight?

**Comment by erpsolns** [comment]
#9872 This works . But Greenlight is not showing these recordings in the recordings list

**Comment by GhaziTriki** [comment]
Hi there,

Just enable `breakoutRoomsRecord` in `bigbluebutton.properties` and make sure the parent rooms is recorded.

**Comment by erpsolns** [comment]
Greenlight Collaborator
farhatahmad commented on 2 Jun
Breakout room recordings are not returned in a getRecordings call, so unfortunately there isn't much that we can do. You'll need to bring it up with the BigBlueButton devs

**Comment by lonesomewalker** [comment]
this is somewhat problematic, because an implemented "broken" feature creates more fuzz than just removing it :-(
