### ISSUE TITLE
Polls: adaptive results table

### ISSUE THREAD

**Issue by iznakurnozh** [bigbluebutton/bigbluebutton#12445]
label:"User Interface (UI)"

It would be nice to keep the table uniform and have a narrow number-of-voters column (as max. 3 digits possible) even if some option texts are short. Otherwise, with different text lenghs, it looks like in the pic below:

![grafik](https://user-images.githubusercontent.com/38284875/119680718-bb551880-be41-11eb-8b19-206c214e75f6.png)

**Comment by antobinary** [comment]
We should also think of how to correctly display the result if both `A` and `ccccccc cccc.. ` had one vote
