### ISSUE TITLE
I have old recording for BBB v2.0 I need to move it to new server with BBB v2.3

### ISSUE THREAD

**Issue by kjaedu** [bigbluebutton/bigbluebutton#12456]
I have old recording for BBB v2.0 I need to move the folders  to new server with BBB v2.3
to working with new server , so from where need to copy the recording files from old server BBB 2.0 and where I must put at new server with BBB v2.3

**Comment by antobinary** [comment]
Hi @kjaedu 
Here is the answer of a similar question: https://groups.google.com/g/bigbluebutton-setup/c/u7O8g-uDE1k/m/RqUdFGjsBwAJ
Please use the mailing lists for questions in the future - you can also search for more related info there. https://groups.google.com/g/bigbluebutton-setup

We use the GitHub issue tracker for development items. Thanks!
