### ISSUE TITLE
No permission error message on skipCheck true

### ISSUE THREAD

**Issue by misisol** [bigbluebutton/bigbluebutton#12463]
**Describe the bug**
When skipCheck ( or skipCheckOnJoin ) in settings.yml is set to true, the browser microphone permission is not getting checked so the warning modal which describes the permission problem never gets triggered. 
In this situation after clicking telephone button and selecting  Microphone, it tries to connect for a second then get back to Microphone selection modal and no error message is shown to user.

And the same thing happens for camera on setting skipVideoPreview or skipVideoPreviewOnFirstJoin to true;

**To Reproduce**
1. Set on of the skipCheck or skipCheckOnJoin options to true, then restart the server.
2. Start a meeting and don't give microphone permission
3. No error Message is shown.

**Expected behavior**
The system should show the error message on modal as when those options are set to false.

‌‌BBB version : 2.3.1

**Comment by misisol** [comment]
This problem still exists on 2.3.8 version

**Comment by prlanzarin** [comment]
I'm merging this into https://github.com/bigbluebutton/bigbluebutton/issues/6948 (the older one - although it doesn't mention the setting.yml config it's pretty much the same issue). Also marking that one as accepted.
