### ISSUE TITLE
Firefox does not show speakers for audio output - no output device selection possible

### ISSUE THREAD

**Issue by laserrapt0r** [bigbluebutton/bigbluebutton#12471]
**Describe the bug**
Firefox does not show a selection for the speaker. 

**To Reproduce**
In Firefox choose thumb down during the echo test or click the phone icon in a session. Firefox says "no audiooutput found" (echo test) or "no device found" (phone icon).

**Expected behavior**
Firefox lists all audio output devices and lets you select one.

**Actual behavior**
Firefox says no audiooutput found.

**Screenshots**
![image](https://user-images.githubusercontent.com/68563050/120227836-3fe0d600-c24a-11eb-8aa6-22435d2b0dfe.png)

**BBB version (optional):**
2.3.1
Also tested on test23.bigbluebutton.org

**Desktop (please complete the following information):**
Windows 10
Firefox 88 + Firefox 78esr

**Additional context**
This worked in the past. Audio output is working but it is not possible to select the device when the audio comes out of the speaker instead of the headset. Edge and Chrome work fine. This was tested with several different devices - private and company devices.

**Comment by laserrapt0r** [comment]
This bug is still present in 2.3.2

**Comment by PhMemmel** [comment]
AFAIK that is not a bug, see #11978. Sure this has worked before? Maybe the mentioned Firefox default setting has been introduced recently?

**Comment by laserrapt0r** [comment]
Okay media.setSinkId.enabled to true fixes the issue. Thank you for the hint.
It worked in the past but I don't know how far back it was. 

What is the best way for users to change their output device then without changing the Firefox config? Going to the OS audio settings? Both ways are uncomfortable for users. There should be a hint for Firefox users instead of just showing no device.

**Comment by jocelynetienne** [comment]
This issue is still happening, I have just had to change media.setSinkId.enabled on 2 computers, with firefox 91.13.0esr and 102.10.0esr, for a BBB service hosted by my university. The same service used to work on these configs a few days ago, is this issue likely to be BBB-version related?  As a user, how can I check which BBB version is running?

**Comment by ffdixon** [comment]
You can use the About option in the Settings menu to get the version of BigBlueButton.

<img width="246" alt="image" src="https://user-images.githubusercontent.com/290351/232232512-a9cba1fc-0f89-481f-ac8f-3e43790a7d3c.png">

**Comment by ffdixon** [comment]
It looks like your running BigBlueButton 2.4 (or earlier).   Recommend updating with 2.6.2 releases.
