### ISSUE TITLE
Echo Test Times out in 2.3.2

### ISSUE THREAD

**Issue by amishbhavsar** [bigbluebutton/bigbluebutton#12498]
**Describe the bug**
The latest version 2.3.2 upgrade breaks the echo test function. Upon starting a session on BBB and selecting the microphone on "How would you like to join the audio?" starts the Connecting to Echo Test.... and then after some time, it just times out.

**To Reproduce**
1. Start a new session on BBB
2. Click on the "join audio" icon at the bottom of the screen
3. Click on "Microphone" on How would you like to join audio?
4. This will initiate the Echo test
5. The Connecting to Echo Test.... will start and shows for a few seconds and then it times out

**Expected behavior**
It should successfully complete the echo test

**Actual behavior**
The Echo test times out

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 91.0.4472.77

**Comment by tom230764** [comment]
Even after an update from 2.3.1 to 2.3.2 via bbb-install.sh the sipjsHackViaWs is reverted. There is also a bug in /usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml.

What you have to do:

1) determine your external ip-address

ADAPTER=`netstat -r|grep default|awk '{ print $NF }'`
IPext=`ifconfig $ADAPTER|grep inet|grep -v inet6|awk '{ print $2 }'|sed 's;addr:;;'`

2) insert this address in /usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml

sudo yq w -i /usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml freeswitch.sip_ip $IPext
sudo yq w -i /usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml freeswitch.ip $IPext

3a) if you want to enable the sipjsHack:
add sipjshack as mentioned by mk-hs

or
3b) if not: convert http to https in /etc/bigbluebutton/nginx/sip.nginx
sudo sed -i "s;http://.*:5066;https://$IPext:7443;" /etc/bigbluebutton/nginx/sip.nginx

@mk-hs: please correct me if I am wrong.

**Comment by tom230764** [comment]
I had a fresh install of 2.3.1 with sipjsHackViaWs enabled: "true" in bbb-conf --check. 
After the update via bbb-install.sh sipjsHackViaWs  was shown as "false" with bbb-conf --check.

**Comment by PhMemmel** [comment]
This feels like `bbb-install.sh` couldn't properly determine your network setup. In 1 of about 10 cases this happens in my setup as well (behind NAT, but no idea if this is the reason). Rerunning `bbb-install.sh` a second or sometimes even a third time until the local and external ip address is properly recognized (this is shown at the start of the output of `bbb-install.sh`) fixed the problem. All settings like `sipJsHackViaWs`, external ip settings in `default.yml` etc. then are properly setup (again).

**Comment by ffdixon** [comment]
`bbb-install.sh` tries a number of approaches to determine the external IP of the server.  

  https://github.com/bigbluebutton/bbb-install/blob/master/bbb-install.sh#L462

@PhMemmel, based on your setup, let us know if you have any suggestions on improving the logic.

**Comment by tom230764** [comment]
In my case the server is not behind NAT. The IP address shown in default.yml after the update was something like 10.3.... (no idea where it came from) so I had to change it to my real ip address.
I didn't change sipJsHackViaWs in '/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml'. Before the update (BBB 2.3.1) it was true, after the update it was false?????

**Comment by PhMemmel** [comment]
@tom230764 That's because the packaged version of `settings.yml` has `sipJsHackViaWs=false`, but `bbb-install.sh` changes it after deploying the new version of it in some cases. So in your case it didn't for some reason. Same probably for `default.yml`, `bbb-install.sh` probably determined a wrong ip address (you probably have an interface with a 10.3... network?). If you find out the reason, pls share :-)

@ffdixon Thanks, I'm not sure what causes the problem and I haven't experienced this issue for a few time, so probably/hopefully the minor issue will be gone. If I experience it again, I will try to figure out what the problem is and happily open an issue about it. In general, the logic works well, even in my pretty weird and not recommended setup ;-)

**Comment by uka-support** [comment]
We have a working 2.3.1 server and a non-working 2.3.2 (completely fresh install - new server, bbb-install.sh) which shows exactly the problem described here. Both servers have public IPs (v4 + v6), no NAT involved.

I verified the following:

- sipjsHackViaWs is true
- freeswitch is listening on external_ip:5066
- sip.nginx has: proxy_pass http://external_ip:5066
- firewall (ufw) output is identical to other server (tried allowing 5066 completely - no change)

I looked at Chrome (current version) network inspector: the response to the /ws?sessionToken=... request is identical for the working server and the broken one (as far as one can see - it only says: Sec-WebScoket-Accept: somestring, Sec-WebSocket-Protocol: sip, Upgrade: websocket). On the working server, there's an immediate request to /bigbluebutton/api/stuns, not so on the broken.

BTW: if I try to join listen-only, I get the "you left the audio conference" notice immediately (and the sound), a little later the error 1006 pops up.

No errors in freeswitch nor nginx logs except one message in bbb-fsesl-akka.log:
```
2021-06-02T16:10:19.457Z INFO  o.b.f.v.f.a.GetUsersStatusCommand - Conference is not running 48041.
```
Nobody is able to join the conference anyway.

I can do `wget -S -O - http://external_ip:5066` and get "400 Bad Request" (not unexpected).

There's one difference between the 2.3.1 and 2.3.2 server: Freeswitch is listening on 8081 and 8082 too - this seems to come from `autoload_configs/verto.conf` which is not found on the 2.3.1 server. Removing that config doesn't resolve the problem.

bbb-conf --check is identical on both servers (except IP and version numbers).

**Comment by tom230764** [comment]
@PHMemmel I've tested the installation from the beginning and found the error:

1) installation of BBB 2.3.1 ( wget -qO- https://ubuntu.bigbluebutton.org/bbb-install.sh | bash -s -- -v bionic-230-2.3.1 -s <FQDN BBB-Server> -e <email-address> -c <FQDN TURN-Server>:<secret> ):
bbb-conf --check : sipjsHackViaWs: true
/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml : sipjsHack: true
/usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml : freeswitch.sip_ip / ...ip : <correct ip-address>

2) update 2.3.2 ( wget -qO- https://ubuntu.bigbluebutton.org/bbb-install.sh | bash -s -- -v bionic-230 -s <FQDN BBB-Server> ):
bbb-conf --check : sipjsHackViaWs: false and kurento.sip_ip: 10.0.3.66
/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml : sipjsHack: false
/usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml : freeswitch.sip_ip / ...ip : 10.0.3.66

3) update 2.3.2 ( wget -qO- https://ubuntu.bigbluebutton.org/bbb-install.sh | bash -s -- -v bionic-230 -s <FQDN BBB-Server> -e <email-address> -c <FQDN TURN-Server>:<secret> ):
bbb-conf --check : sipjsHackViaWs: true and kurento.sip_ip: <correct ip-address>
/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml : sipjsHack: true
/usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml : freeswitch.sip_ip / ...ip : <correct ip-address>

-> for an successful update bbb-install.sh needs all options

**Comment by tom230764** [comment]
@PhMemmel  I've tested the installation from the beginning and found the error:

1) installation of BBB 2.3.1 ( wget -qO- https://ubuntu.bigbluebutton.org/bbb-install.sh | bash -s -- -v bionic-230-2.3.1 -s (FQDN BBB-Server) -e (email-address) -c (FQDN TURN-Server>:<secret) ):
bbb-conf --check : sipjsHackViaWs: true
/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml : sipjsHack: true
/usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml : freeswitch.sip_ip / ...ip : (correct ip-address)

2) update 2.3.2 ( wget -qO- https://ubuntu.bigbluebutton.org/bbb-install.sh | bash -s -- -v bionic-230 -s (FQDN BBB-Server) ):
bbb-conf --check : sipjsHackViaWs: false and kurento.sip_ip: 10.0.3.66
/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml : sipjsHack: false
/usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml : freeswitch.sip_ip / ...ip : 10.0.3.66

3) update 2.3.2 ( wget -qO- https://ubuntu.bigbluebutton.org/bbb-install.sh | bash -s -- -v bionic-230 -s (FQDN BBB-Server) -e (email-address) -c (FQDN TURN-Server):(secret) ):
bbb-conf --check : sipjsHackViaWs: true and kurento.sip_ip: (correct ip-address)
/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml : sipjsHack: true
/usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml : freeswitch.sip_ip / ...ip : (correct ip-address)

-) for an update bbb-install.sh needs all options

**Comment by tom230764** [comment]
@PhMemmel  I've tested the installation from the beginning and found the error:

1) installation of BBB 2.3.1 ( wget -qO- https://ubuntu.bigbluebutton.org/bbb-install.sh | bash -s -- -v bionic-230-2.3.1 -s (FQDN BBB-Server) -e (email-address) -c (FQDN TURN-Server):(secret) ):
bbb-conf --check : sipjsHackViaWs: true 
/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml : sipjsHack: true
/usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml : freeswitch.sip_ip / ...ip : (correct ip-address)
-> ok

2) update 2.3.2 ( wget -qO- https://ubuntu.bigbluebutton.org/bbb-install.sh | bash -s -- -v bionic-230 -s (FQDN BBB-Server) ):
bbb-conf --check : sipjsHackViaWs: false and kurento.sip_ip: 10.0.3.66
/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml : sipjsHack: false
/usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml : freeswitch.sip_ip / ...ip : 10.0.3.66
-> nok

3) update 2.3.2 ( wget -qO- https://ubuntu.bigbluebutton.org/bbb-install.sh | bash -s -- -v bionic-230 -s (FQDN BBB-Server) -e (email-address) -c (FQDN TURN-Server):(secret) ):
bbb-conf --check : sipjsHackViaWs: true and kurento.sip_ip: (correct ip-address)
/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml : sipjsHack: true
/usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml : freeswitch.sip_ip / ...ip : (correct ip-address)
-> ok

-> for an update bbb-install.sh needs all options !

**Comment by mk-hs** [comment]
For what it's worth, should it be bionic-23 or bionic-230? 
https://github.com/bigbluebutton/bbb-install mentions bionic-23.

**Comment by tom230764** [comment]
https://github.com/bigbluebutton/bigbluebutton/releases/tag/v2.3.2 : -v bionic-230 
???

**Comment by amishbhavsar** [comment]
> Did you update via apt?
> Sipjshack isn't automatically reapplied when updating via apt.
> You can either run the bbb-install.sh again (which you can and probably should for updating) or add sipjshack to apply-config.sh as described here: https://docs.bigbluebutton.org/2.2/install.html#configure-freeswitch-for-using-ssl

I updated via apt as I do not know how to update via bbb-install.sh. Is there any documentation on updating via bbb-install.sh?

**Comment by mk-hs** [comment]
> I updated via apt as I do not know how to update via bbb-install.sh. Is there any documentation on updating via bbb-install.sh?

Just run it again, the same way you did on install.

**Comment by ffdixon** [comment]
@uka-support. Taking a closer look at this.  Can you compare the contents of the `/opt/freeswitch/conf` directory on both machines.  Do they look like they have the same number of files?

**Comment by uka-support** [comment]
@ffdixon There are a lot more files on the broken system - maybe an issue with the freeswitch package?

```
--- freeswitch-conf-working.txt 2021-06-03 06:24:26.662408018 +0000
+++ freeswitch-conf-broken.txt  2021-06-03 06:24:19.934401825 +0000
@@ -1,67 +1,229 @@
 /opt/freeswitch/conf/
 /opt/freeswitch/conf/autoload_configs
+/opt/freeswitch/conf/autoload_configs/abstraction.conf.xml
 /opt/freeswitch/conf/autoload_configs/acl.conf.xml
+/opt/freeswitch/conf/autoload_configs/alsa.conf.xml
+/opt/freeswitch/conf/autoload_configs/amqp.conf.xml
+/opt/freeswitch/conf/autoload_configs/amr.conf.xml
+/opt/freeswitch/conf/autoload_configs/amrwb.conf.xml
+/opt/freeswitch/conf/autoload_configs/av.conf.xml
+/opt/freeswitch/conf/autoload_configs/avmd.conf.xml
+/opt/freeswitch/conf/autoload_configs/blacklist.conf.xml
+/opt/freeswitch/conf/autoload_configs/callcenter.conf.xml
+/opt/freeswitch/conf/autoload_configs/cdr_csv.conf.xml
+/opt/freeswitch/conf/autoload_configs/cdr_mongodb.conf.xml
+/opt/freeswitch/conf/autoload_configs/cdr_pg_csv.conf.xml
+/opt/freeswitch/conf/autoload_configs/cdr_sqlite.conf.xml
+/opt/freeswitch/conf/autoload_configs/cepstral.conf.xml
+/opt/freeswitch/conf/autoload_configs/cidlookup.conf.xml
 /opt/freeswitch/conf/autoload_configs/conference.conf.xml
+/opt/freeswitch/conf/autoload_configs/conference_layouts.conf.xml
 /opt/freeswitch/conf/autoload_configs/console.conf.xml
+/opt/freeswitch/conf/autoload_configs/curl.conf.xml
+/opt/freeswitch/conf/autoload_configs/db.conf.xml
+/opt/freeswitch/conf/autoload_configs/dialplan_directory.conf.xml
+/opt/freeswitch/conf/autoload_configs/dingaling.conf.xml
+/opt/freeswitch/conf/autoload_configs/directory.conf.xml
+/opt/freeswitch/conf/autoload_configs/distributor.conf.xml
+/opt/freeswitch/conf/autoload_configs/easyroute.conf.xml
+/opt/freeswitch/conf/autoload_configs/enum.conf.xml
+/opt/freeswitch/conf/autoload_configs/erlang_event.conf.xml
+/opt/freeswitch/conf/autoload_configs/event_multicast.conf.xml
 /opt/freeswitch/conf/autoload_configs/event_socket.conf.xml
+/opt/freeswitch/conf/autoload_configs/fax.conf.xml
+/opt/freeswitch/conf/autoload_configs/fifo.conf.xml
+/opt/freeswitch/conf/autoload_configs/format_cdr.conf.xml
+/opt/freeswitch/conf/autoload_configs/graylog2.conf.xml
+/opt/freeswitch/conf/autoload_configs/hash.conf.xml
+/opt/freeswitch/conf/autoload_configs/hiredis.conf.xml
+/opt/freeswitch/conf/autoload_configs/httapi.conf.xml
+/opt/freeswitch/conf/autoload_configs/http_cache.conf.xml
+/opt/freeswitch/conf/autoload_configs/ivr.conf.xml
+/opt/freeswitch/conf/autoload_configs/java.conf.xml
+/opt/freeswitch/conf/autoload_configs/kazoo.conf.xml
+/opt/freeswitch/conf/autoload_configs/lcr.conf.xml
+/opt/freeswitch/conf/autoload_configs/local_stream.conf.xml
 /opt/freeswitch/conf/autoload_configs/logfile.conf.xml
+/opt/freeswitch/conf/autoload_configs/lua.conf.xml
+/opt/freeswitch/conf/autoload_configs/memcache.conf.xml
 /opt/freeswitch/conf/autoload_configs/modules.conf.xml
+/opt/freeswitch/conf/autoload_configs/mongo.conf.xml
+/opt/freeswitch/conf/autoload_configs/msrp.conf.xml
+/opt/freeswitch/conf/autoload_configs/nibblebill.conf.xml
+/opt/freeswitch/conf/autoload_configs/opal.conf.xml
 /opt/freeswitch/conf/autoload_configs/opus.conf.xml
+/opt/freeswitch/conf/autoload_configs/oreka.conf.xml
+/opt/freeswitch/conf/autoload_configs/osp.conf.xml
+/opt/freeswitch/conf/autoload_configs/perl.conf.xml
+/opt/freeswitch/conf/autoload_configs/pocketsphinx.conf.xml
+/opt/freeswitch/conf/autoload_configs/portaudio.conf.xml
+/opt/freeswitch/conf/autoload_configs/post_load_modules.conf.xml
+/opt/freeswitch/conf/autoload_configs/pre_load_modules.conf.xml
+/opt/freeswitch/conf/autoload_configs/presence_map.conf.xml
+/opt/freeswitch/conf/autoload_configs/python.conf.xml
+/opt/freeswitch/conf/autoload_configs/redis.conf.xml
+/opt/freeswitch/conf/autoload_configs/rss.conf.xml
+/opt/freeswitch/conf/autoload_configs/rtmp.conf.xml
+/opt/freeswitch/conf/autoload_configs/sangoma_codec.conf.xml
+/opt/freeswitch/conf/autoload_configs/shout.conf.xml
+/opt/freeswitch/conf/autoload_configs/skinny.conf.xml
+/opt/freeswitch/conf/autoload_configs/smpp.conf.xml
+/opt/freeswitch/conf/autoload_configs/sms_flowroute.conf.xml
 /opt/freeswitch/conf/autoload_configs/sndfile.conf.xml
 /opt/freeswitch/conf/autoload_configs/sofia.conf.xml
+/opt/freeswitch/conf/autoload_configs/spandsp.conf.xml
 /opt/freeswitch/conf/autoload_configs/switch.conf.xml
+/opt/freeswitch/conf/autoload_configs/syslog.conf.xml
 /opt/freeswitch/conf/autoload_configs/timezones.conf.xml
+/opt/freeswitch/conf/autoload_configs/translate.conf.xml
+/opt/freeswitch/conf/autoload_configs/tts_commandline.conf.xml
+/opt/freeswitch/conf/autoload_configs/unicall.conf.xml
+/opt/freeswitch/conf/autoload_configs/unimrcp.conf.xml
+/opt/freeswitch/conf/autoload_configs/v8.conf.xml
+/opt/freeswitch/conf/autoload_configs/verto.conf.xml
+/opt/freeswitch/conf/autoload_configs/voicemail.conf.xml
+/opt/freeswitch/conf/autoload_configs/voicemail_ivr.conf.xml
+/opt/freeswitch/conf/autoload_configs/vpx.conf.xml
+/opt/freeswitch/conf/autoload_configs/xml_cdr.conf.xml
+/opt/freeswitch/conf/autoload_configs/xml_curl.conf.xml
+/opt/freeswitch/conf/autoload_configs/xml_rpc.conf.xml
+/opt/freeswitch/conf/autoload_configs/xml_scgi.conf.xml
+/opt/freeswitch/conf/autoload_configs/zeroconf.conf.xml
 /opt/freeswitch/conf/chatplan
+/opt/freeswitch/conf/chatplan/default.xml
 /opt/freeswitch/conf/dialplan
 /opt/freeswitch/conf/dialplan/default
 /opt/freeswitch/conf/dialplan/default.xml
 /opt/freeswitch/conf/dialplan/default/bbb_conference.xml
 /opt/freeswitch/conf/dialplan/default/bbb_echo_test.xml
 /opt/freeswitch/conf/dialplan/default/bbb_echo_to_conference.xml
+/opt/freeswitch/conf/dialplan/features.xml
 /opt/freeswitch/conf/dialplan/public
 /opt/freeswitch/conf/dialplan/public.xml
 /opt/freeswitch/conf/dialplan/public/bbb_sip.xml
 /opt/freeswitch/conf/dialplan/public/bbb_webrtc.xml
 /opt/freeswitch/conf/dialplan/skinny-patterns
+/opt/freeswitch/conf/dialplan/skinny-patterns.xml
+/opt/freeswitch/conf/dialplan/skinny-patterns/20-Demo.xml
+/opt/freeswitch/conf/dialplan/skinny-patterns/20-Local_extension.xml
+/opt/freeswitch/conf/dialplan/skinny-patterns/90-External.xml
+/opt/freeswitch/conf/dialplan/skinny-patterns/99-Default_Drop.xml
 /opt/freeswitch/conf/directory
 /opt/freeswitch/conf/directory/default
 /opt/freeswitch/conf/directory/default.xml
 /opt/freeswitch/conf/directory/default/bbbuser.xml
+/opt/freeswitch/conf/extensions.conf
 /opt/freeswitch/conf/freeswitch.xml
+/opt/freeswitch/conf/fur_elise.ttml
 /opt/freeswitch/conf/ivr_menus
+/opt/freeswitch/conf/ivr_menus/demo_ivr.xml
+/opt/freeswitch/conf/ivr_menus/new_demo_ivr.xml
 /opt/freeswitch/conf/jingle_profiles
+/opt/freeswitch/conf/jingle_profiles/client.xml
+/opt/freeswitch/conf/jingle_profiles/server.xml
 /opt/freeswitch/conf/lang
 /opt/freeswitch/conf/lang/de
+/opt/freeswitch/conf/lang/de/de.xml
 /opt/freeswitch/conf/lang/de/demo
+/opt/freeswitch/conf/lang/de/demo/demo.xml
 /opt/freeswitch/conf/lang/de/vm
+/opt/freeswitch/conf/lang/de/vm/sounds.xml
+/opt/freeswitch/conf/lang/de/vm/tts.xml
 /opt/freeswitch/conf/lang/en
 /opt/freeswitch/conf/lang/en/demo
+/opt/freeswitch/conf/lang/en/demo/demo-ivr.xml
+/opt/freeswitch/conf/lang/en/demo/demo.xml
+/opt/freeswitch/conf/lang/en/demo/funnies.xml
+/opt/freeswitch/conf/lang/en/demo/new-demo-ivr.xml
 /opt/freeswitch/conf/lang/en/dir
+/opt/freeswitch/conf/lang/en/dir/sounds.xml
+/opt/freeswitch/conf/lang/en/dir/tts.xml
+/opt/freeswitch/conf/lang/en/en.xml
 /opt/freeswitch/conf/lang/en/ivr
+/opt/freeswitch/conf/lang/en/ivr/sounds.xml
 /opt/freeswitch/conf/lang/en/vm
+/opt/freeswitch/conf/lang/en/vm/sounds.xml
+/opt/freeswitch/conf/lang/en/vm/tts.xml
+/opt/freeswitch/conf/lang/en/vm/voicemail_ivr.xml
 /opt/freeswitch/conf/lang/es
 /opt/freeswitch/conf/lang/es/demo
+/opt/freeswitch/conf/lang/es/demo/demo-es-ES.xml
+/opt/freeswitch/conf/lang/es/demo/demo-es-MX.xml
+/opt/freeswitch/conf/lang/es/demo/demo-ivr-es-ES.xml
+/opt/freeswitch/conf/lang/es/demo/demo-ivr-es-MX.xml
 /opt/freeswitch/conf/lang/es/dir
+/opt/freeswitch/conf/lang/es/dir/sounds-es-ES.xml
+/opt/freeswitch/conf/lang/es/dir/sounds-es-MX.xml
+/opt/freeswitch/conf/lang/es/dir/tts-es-ES.xml
+/opt/freeswitch/conf/lang/es/dir/tts-es-MX.xml
+/opt/freeswitch/conf/lang/es/es_ES.xml
+/opt/freeswitch/conf/lang/es/es_MX.xml
 /opt/freeswitch/conf/lang/es/vm
+/opt/freeswitch/conf/lang/es/vm/sounds-es-ES.xml
+/opt/freeswitch/conf/lang/es/vm/sounds-es-MX.xml
+/opt/freeswitch/conf/lang/es/vm/tts-es-ES.xml
+/opt/freeswitch/conf/lang/es/vm/tts-es-MX.xml
 /opt/freeswitch/conf/lang/fr
 /opt/freeswitch/conf/lang/fr/demo
+/opt/freeswitch/conf/lang/fr/demo/demo.xml
 /opt/freeswitch/conf/lang/fr/dir
+/opt/freeswitch/conf/lang/fr/dir/sounds.xml
+/opt/freeswitch/conf/lang/fr/dir/tts.xml
+/opt/freeswitch/conf/lang/fr/fr.xml
 /opt/freeswitch/conf/lang/fr/vm
+/opt/freeswitch/conf/lang/fr/vm/sounds.xml
 /opt/freeswitch/conf/lang/he
 /opt/freeswitch/conf/lang/he/demo
+/opt/freeswitch/conf/lang/he/demo/demo-ivr.xml
+/opt/freeswitch/conf/lang/he/demo/demo.xml
 /opt/freeswitch/conf/lang/he/dir
+/opt/freeswitch/conf/lang/he/dir/sounds.xml
+/opt/freeswitch/conf/lang/he/he.xml
 /opt/freeswitch/conf/lang/he/vm
+/opt/freeswitch/conf/lang/he/vm/sounds.xml
 /opt/freeswitch/conf/lang/pt
 /opt/freeswitch/conf/lang/pt/demo
+/opt/freeswitch/conf/lang/pt/demo/demo-ivr-pt-BR.xml
+/opt/freeswitch/conf/lang/pt/demo/demo-ivr-pt-PT.xml
+/opt/freeswitch/conf/lang/pt/demo/demo-pt-BR.xml
+/opt/freeswitch/conf/lang/pt/demo/demo-pt-PT.xml
 /opt/freeswitch/conf/lang/pt/dir
+/opt/freeswitch/conf/lang/pt/dir/sounds-pt-BR.xml
+/opt/freeswitch/conf/lang/pt/dir/sounds-pt-PT.xml
+/opt/freeswitch/conf/lang/pt/dir/tts-pt-BR.xml
+/opt/freeswitch/conf/lang/pt/dir/tts-pt-PT.xml
+/opt/freeswitch/conf/lang/pt/pt_BR.xml
+/opt/freeswitch/conf/lang/pt/pt_PT.xml
 /opt/freeswitch/conf/lang/pt/vm
+/opt/freeswitch/conf/lang/pt/vm/sounds-pt-BR.xml
+/opt/freeswitch/conf/lang/pt/vm/sounds-pt-PT.xml
+/opt/freeswitch/conf/lang/pt/vm/tts-pt-BR.xml
+/opt/freeswitch/conf/lang/pt/vm/tts-pt-PT.xml
 /opt/freeswitch/conf/lang/ru
 /opt/freeswitch/conf/lang/ru/demo
+/opt/freeswitch/conf/lang/ru/demo/demo-ivr.xml
+/opt/freeswitch/conf/lang/ru/demo/demo.xml
 /opt/freeswitch/conf/lang/ru/dir
+/opt/freeswitch/conf/lang/ru/dir/sounds.xml
+/opt/freeswitch/conf/lang/ru/dir/tts.xml
+/opt/freeswitch/conf/lang/ru/ru.xml
 /opt/freeswitch/conf/lang/ru/vm
+/opt/freeswitch/conf/lang/ru/vm/sounds.xml
+/opt/freeswitch/conf/lang/ru/vm/tts.xml
 /opt/freeswitch/conf/lang/sv
+/opt/freeswitch/conf/lang/sv/sv.xml
 /opt/freeswitch/conf/lang/sv/vm
+/opt/freeswitch/conf/lang/sv/vm/sounds.xml
+/opt/freeswitch/conf/mime.types
 /opt/freeswitch/conf/mrcp_profiles
+/opt/freeswitch/conf/mrcp_profiles/loquendo-7-mrcp-v2.xml
+/opt/freeswitch/conf/mrcp_profiles/nuance-1.0.0-mrcp-v1.xml
+/opt/freeswitch/conf/mrcp_profiles/nuance-5.0-mrcp-v1.xml
+/opt/freeswitch/conf/mrcp_profiles/nuance-5.0-mrcp-v2.xml
+/opt/freeswitch/conf/mrcp_profiles/unimrcpserver-mrcp-v1.xml
+/opt/freeswitch/conf/mrcp_profiles/vestec-mrcp-v1.xml
+/opt/freeswitch/conf/mrcp_profiles/voxeo-prophecy-8.0-mrcp-v1.xml
+/opt/freeswitch/conf/notify-voicemail.tpl
 /opt/freeswitch/conf/sip_profiles
 /opt/freeswitch/conf/sip_profiles/external
 /opt/freeswitch/conf/sip_profiles/external-ipv6
@@ -69,11 +231,14 @@
 /opt/freeswitch/conf/sip_profiles/external-ipv6/example.xml
 /opt/freeswitch/conf/sip_profiles/external.xml
 /opt/freeswitch/conf/sip_profiles/external/example.xml
-/opt/freeswitch/conf/sip_profiles/internal
 /opt/freeswitch/conf/sip_profiles/internal-ipv6.xml
 /opt/freeswitch/conf/sip_profiles/internal.xml
 /opt/freeswitch/conf/skinny_profiles
+/opt/freeswitch/conf/skinny_profiles/internal.xml
+/opt/freeswitch/conf/tetris.ttml
 /opt/freeswitch/conf/tls
 /opt/freeswitch/conf/tls/dtls-srtp.pem
 /opt/freeswitch/conf/tls/wss.pem
 /opt/freeswitch/conf/vars.xml
+/opt/freeswitch/conf/voicemail.tpl
+/opt/freeswitch/conf/web-vm.tpl
```

Freeswitch version: 2:2.3.0-20 on working system, 2:2.3.0-22 on broken.

**Comment by ffdixon** [comment]
We've fixed this in the latest build of 2.3.3.  Can you try updating to the latest developer build of 2.3.3 using `bbb-install.sh` with `-v bionic-23-dev`.

Let us know if the audio starts working again.  

(When we release 2.3.3 we copy the snapshot from `bionic-23-dev` to `bionic-23` and that becomes the release.)

**Comment by uka-support** [comment]
No luck. Now, FreeSWITCH is almost identical except some verto.conf.xml and some directories.

```
--- freeswitch-conf-working.txt 2021-06-03 12:34:24.888149537 +0000
+++ freeswitch-conf-broken2.txt 2021-06-03 12:32:51.651698769 +0000
@@ -11,7 +11,7 @@
 /opt/freeswitch/conf/autoload_configs/sofia.conf.xml
 /opt/freeswitch/conf/autoload_configs/switch.conf.xml
 /opt/freeswitch/conf/autoload_configs/timezones.conf.xml
-/opt/freeswitch/conf/chatplan
+/opt/freeswitch/conf/autoload_configs/verto.conf.xml
[...]
-/opt/freeswitch/conf/dialplan/skinny-patterns
-/opt/freeswitch/conf/ivr_menus
-/opt/freeswitch/conf/jingle_profiles
-/opt/freeswitch/conf/lang
-/opt/freeswitch/conf/mrcp_profiles
-/opt/freeswitch/conf/sip_profiles/internal
-/opt/freeswitch/conf/skinny_profiles
```

bbb-conf --check seems to be happy, reporting "BigBlueButton Server 2.3.3 (2320)" and all the correct IPs.

Is there some debug level we can/should raise?

**Comment by uka-support** [comment]
tcpdump taken on BBB server, port 5066. After the upgrade message there is no more traffic.
![image](https://user-images.githubusercontent.com/6216577/120651717-59b72e80-c47f-11eb-8c63-27a3f0938bcc.png)

**Comment by uka-support** [comment]
What shall I say? It's been an STUN/TURN configuration issue. 🤦‍♂️ At least in our case.

We had this misconfiguration in our turn-stun-servers.xml:
```
    <bean id="stun1" class="org.bigbluebutton.web.services.turn.StunServer">
        <constructor-arg index="0" value="stun:turn:ourturnserver:443?transport=udp"/>
    </bean>
```
(note: the URL is broken - starts with "stun:turn:")

**Comment by amishbhavsar** [comment]
> > I updated via apt as I do not know how to update via bbb-install.sh. Is there any documentation on updating via bbb-install.sh?
> 
> Just run it again, the same way you did on install.

When I update via bbb-install.sh, it wipes all customizations on BBB and Greenlight. Any reason apt is not recommended?

**Comment by uka-support** [comment]
> > > I updated via apt as I do not know how to update via bbb-install.sh. Is there any documentation on updating via bbb-install.sh?
> > 
> > 
> > Just run it again, the same way you did on install.
> 
> When I update via bbb-install.sh, it wipes all customizations on BBB and Greenlight. Any reason apt is not recommended?

That's because bbb-install.sh does certain modifications to the files installed via the packages. See [Customizing BBB](https://docs.bigbluebutton.org/2.2/customize.html) how to make those modifications permanent via apply-config.sh .

We were using apt-get dist-upgrade for a while but stopped to do so. bbb-install.sh ensures that the configuration matches the current state of the art.

**Comment by amishbhavsar** [comment]
> > > > I updated via apt as I do not know how to update via bbb-install.sh. Is there any documentation on updating via bbb-install.sh?
> > > 
> > > 
> > > Just run it again, the same way you did on install.
> > 
> > 
> > When I update via bbb-install.sh, it wipes all customizations on BBB and Greenlight. Any reason apt is not recommended?
> 
> That's because bbb-install.sh does certain modifications to the files installed via the packages. See [Customizing BBB](https://docs.bigbluebutton.org/2.2/customize.html) how to make those modifications permanent via apply-config.sh .
> 
> We were using apt-get dist-upgrade for a while but stopped to do so. bbb-install.sh ensures that the configuration matches the current state of the art.

Thanks, I was able to update via bbb-install.sh and Echo test is working fine too. Just wanted to see if there is a way to:
1. Configure Nginx to Route to Greenlight through the /b subdirectory after the bbb-install.sh update. The apt update kept the routing intact, but the bbb-install.sh update removes the config as it replaces the Nginx configuration file (/etc/bigbluebutton/nginx/greenlight.nginx)
2. Can Greenlight update be included in the bbb-install.sh script? This will help a nice single command upgrade across BBB and Greenlight

**Comment by uka-support** [comment]
That's probably a packaging issue - maybe some package removes the file while being purged?

bbb-install.sh doesn't do anything to that file - it only creates it if it doesn't exist already.

**Comment by antobinary** [comment]
BBB 2.3.3 was shipped to correct this issue. https://github.com/bigbluebutton/bigbluebutton/releases/tag/v2.3.3
See comment https://github.com/bigbluebutton/bigbluebutton/issues/12498#issuecomment-853771046

I believe this has been addressed. Please comment if anything further comes up.
