### ISSUE TITLE
Hiding the chat at the start of the room does not work

### ISSUE THREAD

**Issue by GyR4uk** [bigbluebutton/bigbluebutton#12491]
At the last update of the develop branch, the chat stopped hiding at the start of the room.

The true chat flag is set in settings.yml:
startClosed: true

**Comment by antobinary** [comment]
Thanks for the heads-up!
This falls into 2.4 territory. Just a reminder that if you are looking into 2.3.x development, the branch to use is `v2.3.x-release`. Otherwise - happy to see you on 2.4+ ;)
