### ISSUE TITLE
post_archive scripts is not running after update to 2.3.1

### ISSUE THREAD

**Issue by amg-web** [bigbluebutton/bigbluebutton#12493]
post_archive scripts is not running after update to 2.3.1
where to check the reason?
post_archive.log is empty after update.

script located in core/scripts/post_archive/

**Comment by amg-web** [comment]
> Was it 2.3.0 to 2.3.1?
yes.
After update to 2.3.3 looks better, but I'm not sure if is was running for all meetings.

**Comment by pedrobmarin** [comment]
> After update to 2.3.3 looks better, but I'm not sure if is was running for all meetings.

Hmmm, so that's one point at my last comment. It will only run for the meetings that had the recording button activated.

**Comment by amg-web** [comment]
> It will only run for the meetings that had the recording button activated.
I need it after all meetings.
Where shall I put it?

**Comment by pedrobmarin** [comment]
One alternative, if it's appropriated with your business, is enabling https://github.com/bigbluebutton/bigbluebutton/blob/af42d2dddd8284fbf6abc722d9bc32c74895dcd8/bigbluebutton-web/grails-app/conf/bigbluebutton.properties#L251-L252 and using the post events script.

**Comment by amg-web** [comment]
> One alternative, if it's appropriated with your business, is enabling

what should it do? I see all events in place in recording/raw

**Comment by pedrobmarin** [comment]
It will store the `events.xml` file for all meetings inside `/var/bigbluebutton/events/<meetingId>`. You can take a look at these scripts for examples https://github.com/bigbluebutton/bigbluebutton/tree/develop/record-and-playback/core/scripts/post_events.

I'll be closing this issue for now. Feel free to open a new one if needed and please reach for further assistance at the mailing lists.

**Comment by amg-web** [comment]
Thanks
I need to parse events.xml but not to keep them.
is it possible to move check setting to store events.xml to post_events_analytics_callback.rb itself ?
