### ISSUE TITLE
I couldn't program the ENCODING time on 2.3

### ISSUE THREAD

**Issue by burakguder** [bigbluebutton/bigbluebutton#12508]
I have installed the latest version of bbb. In version 2.2, I was changing the /etc/systemd/system/bbb-record-core.timer.d/override.conf file so that the encoding processes are done at night. In 2.3 this did not work and the encoding process started at the same time as the sessions.

How can I make the encoding time night for version 2.3

**Comment by antobinary** [comment]
Hi @burakguder,

I see you posted this question at https://groups.google.com/g/bigbluebutton-dev/c/AW4GjPRkn-c as well, reaching out to thousands of BBB-dev members. I am linking to it here too.
Let's keep the discussions there.
