### ISSUE TITLE
Whiteboard: Undo annotation not working as intended after multi-user session

### ISSUE THREAD

**Issue by mk-hs** [bigbluebutton/bigbluebutton#12502]
**Describe the bug**
Presenters are able to use the multi-user Whiteboard to allow others to draw on the Whiteboard as well.
If a presenter continues drawing after a multi-user session and tries to use the undo annotation button to remove a recent addition to the whiteboard, some information added by other users is removed instead.

**To Reproduce**
1. Start a session, let other users join (tested with 1 presenter/moderator, 3 users)
2. As presenter, draw something on the whiteboard
2. Activate the multi-user whiteboard, either for everyone or for specific users, let them draw something
3. Deactivate multi-user whiteboard
4. draw something as presenter and use undo-annotation function

**Expected behavior**
Only recent additions by the presenter are undone.

**Actual behavior**
Additions by other users are undone first.

**Screenshots**
![9bJ9ghBPbo](https://user-images.githubusercontent.com/63116186/120509738-113d3980-c3c9-11eb-887c-1b403bc3ba53.gif)

**BBB version (optional):**
Tested on demo.bigbluebutton.org
and on BigBlueButton Server 2.3.2 (2313)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Firefox 89.0, Chrome 91.0.4472.77

**Comment by mk-hs** [comment]
I initially thought this is only the case on firefox, but it's happening on Chrome as well.

**Comment by antobinary** [comment]
This area is under heavy reconstruction in https://github.com/bigbluebutton/bigbluebutton/pull/13987 (possible 2.5). I will re-tag for 2.5. It is still open if anyone is looking into a fix for it to be applied in 2.3 or 2.4

**Comment by antobinary** [comment]
To be addressed together with https://github.com/bigbluebutton/bigbluebutton/issues/15379 in BBB 2.6 tldraw

**Comment by germanocaumo** [comment]
Addressed in https://github.com/bigbluebutton/bigbluebutton/pull/15636
