### ISSUE TITLE
Breakout session duration out of sync in main room

### ISSUE THREAD

**Issue by azeiser** [bigbluebutton/bigbluebutton#12510]
When I set up breakout rooms with a long duration (say 2 hours) the count down shown in the main room tab "Breakout Rooms" is sometimes out of sync. Switching to "Public Chat" for example and back updates the timer to the correct value.

**Comment by antobinary** [comment]
Hi @azeiser 
What version of BigBlueButton are you using?

`bbb-conf --version`
or client -> About (in top right-hand corner)

**Comment by azeiser** [comment]
In the client it says
Client build: 1157

**Comment by antobinary** [comment]
> In the client it says
Client build: 1157

That is BigBlueButton 2.2.36

In BigBlueButton 2.3 we have this resolved via https://github.com/bigbluebutton/bigbluebutton/pull/12140

**Comment by azeiser** [comment]
Thanks. I haven't seen this fix.
