### ISSUE TITLE
Problem when displaying 1280 x 720p - Screenshoot - A4 PDF presentations on mobile.

### ISSUE THREAD

**Issue by fayadatoui** [bigbluebutton/bigbluebutton#12524]
This problem makes the platform completely unusable on the mobile phone. Many users have reported it, but it has not been addressed in the new updates. 

Reproduce the issue: 
1- Join with mobile phone as presenter 
2- Open camera 
3- Mange presentation > Take photo or upload a presentation 1280 x 720p  "Vertically"  (or any screenshot size - PDF A4..)
4- Confirm uploading 
Result: The presentation will cut and move to right side (or left side in case of rtl) as pictures attached.

![nW-vti7Y](https://user-images.githubusercontent.com/85411701/120901839-ce3bca00-c645-11eb-933c-c21611a543e5.jpg)

![Screenshot_20210605_213638](https://user-images.githubusercontent.com/85411701/120901929-34c0e800-c646-11eb-9cf9-ead426128e8b.jpg)

https://user-images.githubusercontent.com/85411701/120902342-8d918000-c648-11eb-9282-1029432ec087.mp4

I hope the issue will be resolved quickly.

**Comment by antobinary** [comment]
Closed via https://github.com/bigbluebutton/bigbluebutton/pull/12718
