### ISSUE TITLE
Czech language client is not working

### ISSUE THREAD

**Issue by prazape** [bigbluebutton/bigbluebutton#12537]
**Describe the bug**
After update to last version, when you use browser with czech language set you only get the 3 dots loading sign (without animation). From my previous experiments with using my own json I would guess that cs_CZ.json file has differrent size or hash than expected in program.json and BBB instead of using it with displaying some error to log (or somewhere) or fallbacking to usable language file just hangs.

**To Reproduce**
1. Open a meeting in czech browser (cz_CZ)
2. See only loading 3 dots (not animated)

**BBB version (optional):**
$ sudo bbb-conf --check | grep BigBlueButton
BigBlueButton Server 2.3.3 (2326)

**Hot fix**
After I noticed that it works in eng browser I have managed to fix this by using previous cs_CZ.json file and its size and hash in program.json. 
```
    {
      "path": "app/locales/cs_CZ.json",
      "where": "client",
      "type": "asset",
      "cacheable": false,
      "url": "/locales/cs_CZ.json",
      "size": 58112,
      "hash": "26e043af827339b7e1aab3da581ee2131db3a254",
      "sri": null
    },
```
The trick from #12413  with just using cs.json does not work anymore, but I guess that was expected

**Proposed actions**
***1***
So I would say my question from previous my issue #12413 still stands and only gains importance:

> Can you tell me / guide me where to find what hash function is used and how is it counted?

Please add it somewhere in BBB 2.3 documentation.

***2***
When language file fails verification, show info/log error message and use it anyway or fallback to default language.
Or even better create a configuration option so admins can choose from those two.

Regards,
Petr

**Comment by ramonlsouza** [comment]
> Can you tell me / guide me where to find what hash function is used and how is it counted?

Hello @prazape!

The `program.json` file is generated by Meteor in build time, and should not be edited manually.

I was able to trigger the 3 static dots by starting bbb-html5 after manually adding cs.json file (without rebuilding meteor after that). To get rid of it, just remove the `cs.json` file and restart bbb-html5 (`sudo bbb-conf --restart`)

If you need custom translation, you should be able to do it by editing the contents of an already available file (in your case the best option would be `cs_CZ.json`)
