### ISSUE TITLE
Upload presentaation modal fallback.view.title

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#12532]
**Describe the bug**
Sporadic issue with presentation upload modal.

**To Reproduce**
 I don't know the exact steps to trigger it, only happens sometimes.
I have seen this when trying to upload a presentation. The YouTube below captures the steps but I have not been able to reproduce via those steps, so I list none here. This section will be updated if we narrow down the issue.

**Screenshots**
![Screenshot from 2021-06-07 10-03-17](https://user-images.githubusercontent.com/6312397/121039404-0d216b00-c77f-11eb-9a10-bc78dcc663a8.png)

`https://youtu.be/gmoRqO1zYNQ` too

**BBB version (optional):**
BigBlueButton Server 2.3.3

**Comment by ReimarBauer** [comment]
We had this yesterday. We tried parallel uploading, while the converting of very detailed presentations where not finished. These presentations did not made it in the selection list. This opens also another question, do we need to wait for the conversion before switching presenter and uploading the next? Should the conversion continue in the background?
If it should continue in the background, I assume when this did'nt sucessfully it can get to this.

**Comment by ramonlsouza** [comment]
> We had this yesterday. We tried parallel uploading, while the converting of very detailed presentations where not finished. These presentations did not made it in the selection list. This opens also another question, do we need to wait for the conversion before switching presenter and uploading the next? Should the conversion continue in the background?
> If it should continue in the background, I assume when this did'nt sucessfully it can get to this.

@ReimarBauer did it happen only once or happens everytime you follow these steps?

I tried to reproduce the error by changing the presenter during presentation processing and uploaded a new file with the other presenter... and the conversion continued in background, no errors.

**Comment by ReimarBauer** [comment]
> > We had this yesterday. We tried parallel uploading, while the converting of very detailed presentations where not finished. These presentations did not made it in the selection list. This opens also another question, do we need to wait for the conversion before switching presenter and uploading the next? Should the conversion continue in the background?
> > If it should continue in the background, I assume when this did'nt sucessfully it can get to this.
> 
> @ReimarBauer did it happen only once or happens everytime you follow these steps? And which BBB version?
> 
> I tried to reproduce the error by changing the presenter during presentation processing and uploaded a new file with the other presenter... and the conversion continued in background, no errors.

I've had this with the recent 2.3.3 version only yet. And I also recognized that converting was slowed down, because they used some Arial font and this font or a good representation was not installed. One uploaded a 60 pages paper the other some slides. We had later smaller files uploaded and with selecting one of the uploads we run into this view.title problem. I try to repeat if I can get into it again.

**Comment by ReimarBauer** [comment]
Not yet reproduced but I got to another question. Somehow related maybe. If we toggle presentation upload between users and you take back presenter right and check presentation upload you could probably see 75 of 100 pages only of your uploads converted. 

if you don't want to select a presentation how did you get back to the webconf screen?

It is "Cancel" but at first moment I thought this means "Cancel Upload" and clicked Browser Back button. Of course this logged me out.

**Comment by ReimarBauer** [comment]
I've tried several things now. uploading waiting until it is converted removing the files again. It seems I can't trigger it again. I  found small other things. e.g. when one moderator gets presenter right and uploads files the other has an empty list besides the default presentation. 

Both can now select a file and push it. The one with real presenter right gets that presentation pushed to all others while when the other tries that then there is not anymore a presentation screen on both accounts.

![blue](https://user-images.githubusercontent.com/278728/121726966-91f7e600-caeb-11eb-93cc-fbfad2384c62.png)

The short selection list above the + symbol has not any presentation then. and also the uploaded presentation list gets emptied besides the default.pdf. Not immediatly. I need toggle presenter  between both accounts.

**Comment by antonbsa** [comment]
**The following test will be applied to this PR:**

1. Open chrome ( chrome-a )
2. Open chrome in anonymous mode ( chrome-b )
3. chrome-a: join BBB v2.3.x-release with name chrome-a;
4. chrome-b: join BBB v2.3.x-release with name chrome-b;
5. chrome-a: check if the user is the current presenter ( it should be );
6. chrome-a: open the send new presentation popup, but don't upload yet;
7. chrome-b: click in "Take presenter" button;
8. chrome-b: open the send new presentation popup;
9. chrome-a: see if the popup disappears

**Expected result without the PR:** 
popup stays visible to chrome-a user, causing an inconsistent state.

**Expected result with the PR:**
 popup should disappear to chrome-a user.

**Comment by antobinary** [comment]
I have not spotted this issue for 2-3 months. Let's reopen if it resurfaces.

**Comment by aligot-cblue** [comment]
For your information, we just had same issue on 2.3.18
![image](https://user-images.githubusercontent.com/13678047/157251621-56275999-4a9c-40b7-9312-63bcc179d44d.png)
