### ISSUE TITLE
bbb-conf --check does not consider /etc/-overwrites

### ISSUE THREAD

**Issue by crosscodr** [bigbluebutton/bigbluebutton#12530]
**Describe the bug**
`bbb-conf --check` does not consider overwrite-settings in /etc/bigbluebutton/bbb-webrtc-sfu/production.yml and /etc/bigbluebutton/bbb-html5.yml.

**Installation type**
ansible: https://github.com/ebbba-org/ansible-role-bigbluebutton

**Firewall and IP address type**
Is your server behind a NAT or firewall? No.
Does your BBB server have its own IPv4 address? Yes

**Console output**
```
# Warning: You have this server defined for https, but in
#
#   /etc/bigbluebutton/nginx/sip.nginx
#
#  did not find the use of https in definition for proxy_pass
#
#            proxy_pass http://130.75.xxx.xxx:5066;
#

# Warning: You have this server defined for https, but in
#
#   /etc/bigbluebutton/nginx/sip.nginx
#
#  did not find the use of port 7443 in definition for proxy_pass
#
#            proxy_pass http://130.75.xxx.xxx:5066;
#

# Kurento will try to connect to 10.0.3.66 but FreeSWITCH is listening on 130.75.xxx.xxx for port 5066
#
# To fix, run the commands
#
# sudo yq w -i /usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml freeswitch.sip_ip 130.75.xxx.xxx
# sudo chown bigbluebutton:bigbluebutton /usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml
```

**Additional context**
sipjsHackViaWs is set to `true` in /etc/bigbluebutton/bbb-html5.yml and the correct freeswitch ip is set in /etc/bigbluebutton/bbb-webrtc-sfu/production.yml.
BBB works, however, bbb-conf should not complain about wrong system-settings.

**Comment by Mylinuxforyou** [comment]
**Warnung** 

bbb-webrtc-sfu will try to connect to null but FreeSWITCH is listening on my ip for port 
 To fix, run the commands
#
# sudo yq e -i 'freeswitch.sip_ip' = my ip  etc/bigbluebutton/bbb-webrtc-sfu/production.yml
# sudo chown bigbluebutton:bigbluebutton /etc/bigbluebutton/bbb-webrtc-sfu/production.yml
