### ISSUE TITLE
bbb-conf --setip does not change domain in bigbluebutton.properties

### ISSUE THREAD

**Issue by amg-web** [bigbluebutton/bigbluebutton#12540]
Actually everything is described in the subject:
bbb-conf --setip  eexample.com
does not change domain name in 
/usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties

**Comment by antobinary** [comment]
That's by design in 2.3

We no longer want to be tweaking the config files that ship with packaging.
There is a new file, introduced in 2.3
`/etc/bigbluebutton/bbb-web.properties` - bbb-conf --setip modifies that file. The file trumps `/usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties`. Check for more info (as we made similar changes to other components beside bbb-web): https://docs.bigbluebutton.org/2.3/install.html#local-overrides-for-configuration-settings

**Comment by amg-web** [comment]
bbb-conf --setip eexample.com we have got a problem with breakout room which still used old domain

**Comment by antobinary** [comment]
I just tried to reproduce this.


```
root@droplet-3362:~# cat /etc/bigbluebutton/bbb-apps-akka.conf 
// include default config from upstream
include "/usr/share/bbb-apps-akka/conf/application.conf"

// you can customize everything here. API endpoint and secret have to be changed
// This file will not be overridden by packages

services {
  bbbWebAPI="https://droplet-3362.example.com/bigbluebutton/api"
  sharedSecret="mBFC44sED6abiT0ncnHhSfxJh0PVd4QJi4oL1xjEkt"
}
root@droplet-3362:~# 
root@droplet-3362:~# 
root@droplet-3362:~# 
root@droplet-3362:~# 
root@droplet-3362:~# 
root@droplet-3362:~# bbb-conf --setip droplet-3363.example.com
Assigning droplet-3363.example.com for web application URL in /etc/bigbluebutton/bbb-web.properties
Assigning droplet-3363.example.com for web application URL in /etc/bigbluebutton/bbb-apps-akka.conf
Assigning droplet-3363.example.com for api demos in /var/lib/tomcat8/webapps/demo/bbb_api_conf.jsp
Assigning droplet-3363.example.com for record and playback in /usr/local/bigbluebutton/core/scripts/bigbluebutton.yml
Assigning droplet-3363.example.com for playback of recordings: 
Restarting the BigBlueButton 2.3.3 ...
Stopping BigBlueButton


Applying updates in /etc/bigbluebutton/bbb-conf/apply-config.sh: 
/etc/bigbluebutton/bbb-conf/apply-config.sh: line 6: setHTML5ClientAsDefault: command not found
  - Enable HTML5 client log to /var/log/nginx/html5-client.log

Starting BigBlueButton
root@droplet-3362:~# cat /etc/bigbluebutton/bbb-apps-akka.conf 
// include default config from upstream
include "/usr/share/bbb-apps-akka/conf/application.conf"

// you can customize everything here. API endpoint and secret have to be changed
// This file will not be overridden by packages

services {
  bbbWebAPI="https://droplet-3363.example.com/bigbluebutton/api"
  sharedSecret="mBFC44sED6abiT0ncnHhSfxJh0PVd4QJi4oL1xjEkt"
}

```

`bbbWebAPI="https://droplet-3363.example.com/bigbluebutton/api"` was correctly updated in `/etc/bigbluebutton/bbb-apps-akka.conf` 

Could you please share some logs for 

>bbb-conf --setip eexample.com we have got a problem with breakout room which still used old domain

and grep for `bbbWebAPI` in `/etc/bigbluebutton/bbb-apps-akka.conf` and `/usr/share/bbb-apps-akka/conf/application.conf`

**Comment by antobinary** [comment]
Reinstall sounds fine. Try to only edit `/etc/bigbluebutton/*`
