### ISSUE TITLE
(Poll) User/Presenter typed responses are always being translated

### ISSUE THREAD

**Issue by germanocaumo** [bigbluebutton/bigbluebutton#12546]
**Describe the bug**
As described by @schrd in #12534:

> This leads me to another bug: Even answers entered in user response are translated (and should not). Example:
> 
> 1. Choose a locale != english
> 2. start a poll with user responses
> 3. enter "yes" as answer. It will be translated to the chosen locale. IMHO it should not be translated.

This also happens when the presenter manually enter a default answer in English (ex: yes/false), 

**Expected behavior**
The answer should not be translated when the user/presenter type the answer.

**Actual behavior**
The answers are always being translated if the answers are written in english.

**Additional context**
This is easy to fix in the live result component and in the user polling component, we just need to check if the poll is not a default one (can check via isDefaultPoll from service).
But in the Whiteboard we do not have the poll type sent with the annotation so this would require adding the info in akka-apps.

**Comment by antobinary** [comment]
Fixed in https://github.com/bigbluebutton/bigbluebutton/pull/12561
