### ISSUE TITLE
Users get not promoted to moderator if the moderator leaves room anymore

### ISSUE THREAD

**Issue by coderDem** [bigbluebutton/bigbluebutton#12547]
Hello,

the behavior of the atomatical promotion of users to moderator seems to have changed in BBB 2.3.
In BBB 2.2 the last user was promoted to presenter if the moderator leaves room.

**To Reproduce**
1. Go to https://demo.bigbluebutton.org/
2. Click on open an new room
3. Invite some users 
4. Join with the users
5. Leave the room as moderator
6. No user in the room is promoted to presenter anymore

**Expected behavior**
The moderator leaves room and the last user get atomatic the moderator right to upload files
and promote other users to presenter.

**Actual behavior**
The moderator leaves room and the last user get not the presenter right in the room.
So nobody can upload new presentation change the slides on presentation or share screen.

**BBB version (optional):**
BigBlueButton Server 2.3.3 (2326)

**Desktop (please complete the following information):**
You can use any browser.

**Comment by ferdinandSoethe** [comment]
I wonder if this new behaviour is intended.
Making any other user moderator when the intended moderator losses connection connection never has been such an ideal solution and caused many privacy and security problems.
To avoid lockout as a moderator, you can promote other participants right from the start or hand out moderator codes for greenlight lock-in. So where would you see problems?
Kind regards
Ferdinand

**Comment by antobinary** [comment]
The 'actual behavior' is the preferred behavior in pretty much all cases I can think of.
If you are OK with any of your viewers becoming a moderator, you may consider having everyone join with moderator role in first place.

**Comment by coderDem** [comment]
@antobinary @ferdinandSoethe you are right. I should close this issue.
