### ISSUE TITLE
Listen-only audio modal UX/UI issues

### ISSUE THREAD

**Issue by mabras** [bigbluebutton/bigbluebutton#12558]
When mic is locked, the audio modal can not be closed. Also, click on the Listen-only button will not show any loading indication. One more thing, The button is not centered.

![image](https://user-images.githubusercontent.com/9248917/121649603-66500e00-caa1-11eb-8a8e-81b1976baa80.png)

**To Reproduce**
1. New meeting.
2. Lock the mic for the viewer
3. Join as an attendee
4. See the behavior

**Expected behavior**
I should able to close the modal.
The modal should show a loading state after clicking the listen-only button.

**Actual behavior**
The opposite of the expected behavior.

**Comment by uka-support** [comment]
Please use the issue template when reporting issues. Which is the exact version you are using?

I can partially reproduce this on 2.3.3: cannot close the modal via the X button, but I can join listen-only - takes 1-3 seconds until there's a visible reaction.

**Comment by ramonlsouza** [comment]
fixed by #12551
