### ISSUE TITLE
Recordings of 9+ hours

### ISSUE THREAD

**Issue by jfernhdzg** [bigbluebutton/bigbluebutton#12554]
Hello, is it possible to process recordings of more than 9 hours? specifically recordings of 24 to 96 hours.
If the above is not feasible, is it possible to extract only the audio from a recording when it is processed by the BBB server?

**Comment by mabras** [comment]
Please use google group for questions.

**Comment by H4CK3RB0Y** [comment]
I haven't tried a recording for 9 hours or more than before, but I didn't have a problem up to 4-5 hours. Only audio recordings of meetings are possible. BBB records microphone audio automatically after the microphone is activated.

![image](https://user-images.githubusercontent.com/5767842/122000166-1205a080-cdb7-11eb-8d4d-fd8922f667ae.png)

**Comment by valerio-bozzolan** [comment]
First of all, be sure to have enough disk space on your server.

https://docs.bigbluebutton.org/support/faq.html#what-is-the-disk-space-usage-for-storing-one-hour-of-recordings

**Comment by ffdixon** [comment]
Yes, you should be able to have recordings longer than 9 hours.  Check the setting in `/usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties` and ensure `defaultMeetingDuration=0` so there is no maximum limit.

```
# Default duration of the meeting in minutes.
# Current default is 0 (meeting doesn't end).
defaultMeetingDuration=0
```

You should be able to hold a meeting for 20 hours, for example, and have the recording process at the end.
