### ISSUE TITLE
BigBlueButton V.2.2.36 & V.2.3.3 - iPad  iOS 14.4.2 - No sound when opening another app

### ISSUE THREAD

**Issue by FluffyUnicorn161** [bigbluebutton/bigbluebutton#12550]
We noticed the following problem / strange behavior:

If a conference is in progress and then another app is opened for the first time, the sound no longer works.
Only when Safari including the conference is reopened does the sound come back.
If the same app is opened again from the background, the sound from the session is still retained.

**Comment by antobinary** [comment]
Could you please repeat the same test but with another in-browser application? For example if you play a video on youtube.com *in Safari* (not via YouTube app), and you switch the app the same way, do you lose the sound?
I don't have iOS devices but this happens for me on other platforms regardless of what browser page is open (i.e. if this is reproducible with you tube, then it is not a BigBlueButton issue but a browser/OS quirk)
