### ISSUE TITLE
Screenreader focus in Menus using Chrome

### ISSUE THREAD

**Issue by WestphalDenn** [bigbluebutton/bigbluebutton#12573]
Description: 
Using a Screenreader and the Chrome browser I have noticed that there is a Problem opening Menus. The Focus of the Screenreader doesn't land in the opened menus. 

Current behaviour:
For example opening the Actions-Menu doesn't place me in the menu to work with it. I have to manually find where the Menu appears. That seems to be inconsistent. Sometimes at the end of the Page. 

Expected behaviour:
When I open a Menu pressing the Tab-Key (That is how it works in Firefox) places me in the Menu where I can select the option I want. Even better if the extra Press of the Tab-button wouldn't be required. 

Why is that important:
Fixing this issue would lead to way more efficient use of BBB in Chrome by blind people. Thank you for your great work. I really love to use BBB as a blind user myself.

**Comment by antobinary** [comment]
Closed in BBB 2.4 via #12745
