### ISSUE TITLE
`Error: Unable to connect to the FreeSWITCH Event Socket Layer on port 8021` when no IPv6 address is configured on ethernet device

### ISSUE THREAD

**Issue by paulmenzel** [bigbluebutton/bigbluebutton#12578]
In a minimal Ubuntu 18.04 installation in a virtual machine, install BBB with the command below:

    $ sudo bash ./bbb-install.sh -v bionic-230 -s bigbluebuttonX.molgen.mpg.de -e XXX@molgen.mpg.de -w -g
    […]
    $ more /etc/bigbluebutton/bigbluebutton-release
    BIGBLUEBUTTON_RELEASE=2.3.3

Starting a room, in the echo dialog, choosing to join with the microphone, after giving permissions to access the microphone to the browser, the echo test dialog does not finish and stays white.

Checking the configuration gives:

    $ sudo bbb-conf --check
    […]
    # Potential problems described below

    # Error: Found text in freeswitch.log:
    #
    #    Thread ended for mod_event_socket
    #
    # FreeSWITCH may not be responding to requests on port 8021 (event socket layer)
    # and users may have errors joining audio.
    #
 
    #
    # Error: Unable to connect to the FreeSWITCH Event Socket Layer on port 8021
    #
    

Nothing is indeed running on that port:

    $ sudo lsof -i -P -n | grep 8021
    $

The FreeSWITCH log contains:

    2021-06-12 07:55:11.323088 [ERR] mod_event_socket.c:2962 Cannot get information about IP address ::

So problem seems to be, that only an IPv4 address is configured for the network interface.

    2: ens3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
        link/ether 52:c6:11:00:00:33 brd ff:ff:ff:ff:ff:ff
        inet 141.14.15.171/29 brd 141.14.15.175 scope global ens3
           valid_lft forever preferred_lft forever

This is due to me configuring the systemd-networkd network configuration with:

    IPv6AcceptRA=no
    LinkLocalAddressing=no

Strangely, after restarting the BBB services with `bbb-conf`, the service gets up:

    $ sudo bbb-conf --clean
    […]
    Restarting BigBlueButton 2.3.3 (and cleaning out all log files) ...
    Stopping BigBlueButton
     ... cleaning log files

    Applying updates in /etc/bigbluebutton/bbb-conf/apply-config.sh:
      - Enable Firewall and opening 22/tcp, 80/tcp, 443/tcp and 16384:32768/udp
    Skipping adding existing rule
    Skipping adding existing rule (v6)
    Skipping adding existing rule
    Skipping adding existing rule (v6)
    Skipping adding existing rule
    Skipping adding existing rule (v6)
    Firewall is active and enabled on system startup

    Starting BigBlueButton

    # Potential problems described below
    ............
    $ grep ERR /opt/freeswitch/var/log/freeswitch/freeswitch.log
    $

Any idea, what FreeSWITCH does differently the second time?

**Comment by laserrapt0r** [comment]
Have you disabled IPv6 in Freeswitch?

sed  -i 's_.*<param name="listen-ip" value="::"/>.*_    <param name="listen-ip" value="127.0.0.1"/>_' /opt/freeswitch/etc/freeswitch/autoload_configs/event_socket.conf.xml
mv /opt/freeswitch/etc/freeswitch/sip_profiles/internal-ipv6.xml /opt/freeswitch/etc/freeswitch/sip_profiles/internal-ipv6.xml_
mv /opt/freeswitch/etc/freeswitch/sip_profiles/external-ipv6.xml /opt/freeswitch/etc/freeswitch/sip_profiles/external-ipv6.xml_

**Comment by paulmenzel** [comment]
No, I have not, I am going to try it later. I am wondering though, why it only seems to fail during boot and not when restarting it with `bbb-conf --restart`.
