### ISSUE TITLE
Unable to save public chat (intl error)

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#12597]
**Describe the bug**
In some cases saving the public chat triggers a browser console error (see screenshot) and the user is unable to save the chat.

**To Reproduce**
1. Start a meeting
2. Join as moderator
3. Send a few public chat messages
4. At the top of the public chat go to the three-dot menu and hit 'Save'.

**Expected behavior**
A file download is initiated.

**Actual behavior**
In some cases an error is output to the browser console and no file is downloaded.

**Screenshots**
![Screenshot from 2021-06-16 11-19-10](https://user-images.githubusercontent.com/6312397/122246898-eeb12300-ce94-11eb-9f85-7a2a598a644b.png)

**BBB version (optional):**
BigBlueButton 2.3.3

**Additional context**
I have a video report of this from a production environment. I was not able to reproduce on my own in new meeting.

**Comment by germanocaumo** [comment]
@antobinary do you have the poll example that causes this?

**Comment by antobinary** [comment]
```
    <answers>[{"id":0,"key":"A"},{"id":1,"key":"B"}]</answers>
    <answers>[{"id":0,"key":"A","numVotes":2},{"id":1,"key":"B","numVotes":28}]</answers>
    <answers>[{"id":0,"key":"A"},{"id":1,"key":"B"},{"id":2,"key":"C"},{"id":3,"key":"D"},{"id":4,"key":"E"}]</answers>
    <answers>[{"id":0,"key":"A","numVotes":9},{"id":1,"key":"B","numVotes":6},{"id":2,"key":"C","numVotes":6},{"id":3,"key":"D","numVotes":5},{"id":4,"key":"E","numVotes":0}]</answers>
    <answers>[{"id":0,"key":"A"},{"id":1,"key":"B"},{"id":2,"key":"C"},{"id":3,"key":"D"},{"id":4,"key":"E"},{"id":5,"key":"F"}]</answers>
    <answers>[{"id":0,"key":"A","numVotes":1},{"id":1,"key":"B","numVotes":7},{"id":2,"key":"C","numVotes":5},{"id":3,"key":"D","numVotes":0},{"id":4,"key":"E","numVotes":9},{"id":5,"key":"F","numVotes":6}]</answers>
```
