### ISSUE TITLE
[feat] Change remaning time for breakout-rooms at runtime

### ISSUE THREAD

**Issue by crosscodr** [bigbluebutton/bigbluebutton#12600]
**Is your feature request related to a problem? Please describe.**
Teachers at our university reported, that there are cases, where students need more time in the breakout-rooms.
They asked for a possibility to increase the breakout-room-time after creation of those.

**Describe the solution you'd like**
A way to change the remaining time for breakout-rooms when they already run.

**Comment by antobinary** [comment]
Hi @crosscodr 

We just implemented this in #12505 
Expect this in BigBlueButton 2.4 scheduled to be out in a few months
