### ISSUE TITLE
Get event when user click "Listen only" or "Microphone"

### ISSUE THREAD

**Issue by dothanhhao** [bigbluebutton/bigbluebutton#12615]
Hi all,
Can I get the event when user click  "Listen only" or "Microphone"
![image](https://user-images.githubusercontent.com/26756461/122527210-51492100-d045-11eb-98cd-3535a3ca190e.png)

**Comment by hostbbb** [comment]
Whats the exact use case... you can monitor server side.  every full audio, and listen only connection in redis?

**Comment by dothanhhao** [comment]
> Whats the exact use case... you can monitor server side. every full audio, and listen only connection in redis?

In my case, I want to get the event when user click one of them at client side to show more infomation. Do we have any option configs or API to do that @hostbbb ?
