### ISSUE TITLE
Small Red button to leave meeting

### ISSUE THREAD

**Issue by peterVoisin** [bigbluebutton/bigbluebutton#12614]
It's a question, why not a red button to leave the conference?

**Comment by iSamof** [comment]
@peterVoisin - The team will probably ask you to discuss the matter in the Google group. But I do like your suggestion a lot.

Very few users will go to a menu find the correct entry and click it to leave. Most just close the browser tab. An easily accessible "Leave Meeting" button will be much more popular. With a conveniently located button, very few people will reach for the browser tab to close it.

**Comment by peterVoisin** [comment]
@iSamof - No one seems interested in this feature

**Comment by iSamof** [comment]
@peterVoisin - Rome wasn't built in a day :-)

How about filling in a proper feature request with justification provided (you can also include any part of my text above, if you wish) AND refer to the like of Zoom and others who have this user-friendly function. Then we can see if there is interest or not.

I think this will happen, at some point in the future. All meeting and conferencing software have this feature (call/show video/hang up) within easy reach, for a reason: "user convenience" ... and it is much easier to **trigger events** from this than from the browser event which is different for each browser.

**Comment by ffdixon** [comment]
People would recognize the exit button as it's common to other applications.

The reason we've not added this feature as we've been trying to keep the number of buttons on the screen to a minimum.  Closing the browser tab works well enough.

**Comment by peterVoisin** [comment]
@iSamof - I share your opinion

@ffdixon - Of course, closing browser tab works well, but people want landmarks.
For many people, leaving a meeting is like ending a phone call. A red button is comforting, even if unnecessary.
It is not easy to promote BigBlueButton precisely because it doesn't look like enough to other web-conferencing solution.
People are quickly in discomfort.
Contrary to BigBlueButton's original philosophy, for people, this system is not easy.
First, the echo test, which requires user action, people don't like to make choices.
In fact, BigBlueButton is not as easy as clicking a button
And there is no red button :-p
Then people ask me to use Zoom... :-/

**Comment by antobinary** [comment]
We are looking at shifting the "Leave" functionality into its own button outside of the three dots menu. We've received lots of feedback over the years and despite the fact that people can close the browser tab at any point, some still prefer clicking on a red button in the top right-hand corner of the client.

Plan:
introduce join parameter `userdata-bbb_extra_leave_button` such that if `true`:
An extra button will appear immediately to the left of the three-dots menu. The icon will be the same as the existing leave icon. The background will be red ('danger'). Clicking on this button will act the same way as clicking on the existing button today in the three dots menu - optionally showing the Are you sure dialog, optionally redirecting to logoutURL, optionally showing feedback dialog. Leaving the session.

If `false` (or if no such parameter passed) (i.e. default) - the leave button will be in the list of options opened by the three dots button. Same as today in 2.7.2.

Let's also document this new parameter under https://docs.bigbluebutton.org/administration/customize#application-parameters

**Comment by gustavotrott** [comment]
I like this idea! I'd suggest making this new button the default.

The main reason is it's really easy to get mixed up between the "leave meeting" button and the "end meeting" button. I've seen moderators accidentally end the meeting several times.

![image](https://github.com/bigbluebutton/bigbluebutton/assets/5660191/a3698a7c-92c1-40ae-b3a2-b5b3d0a96376)

**Comment by antobinary** [comment]
I'd be open to making it the default in BBB 3.0 or 3.1 let's say -- after we've had months of new feedback. For BBB 2.7 I'd rather not change too much visible functionality as it's likely already in production at schools and the documentation is in place already. Such a change would be more fitting for a new major release so people have a chance to document/train/adapt.

**Comment by antobinary** [comment]
After some further conversations, it appears that we should also include the word `Leave` in this button.
