### ISSUE TITLE
External video in Breakout Rooms

### ISSUE THREAD

**Issue by nstylianides** [bigbluebutton/bigbluebutton#12617]
**Describe the bug**
When entering a Breakout Room with an External Video already playing for others, the video does not sync or play. 
If the Moderator that started the Video PAUSES it, and then REPLAYS it, then the video syncs and play correctly

**To Reproduce**
You will need two connections from different Browsers
1. Fron the 1st connection Create BRs (Room-1 and Room-2) , Join Room-1 and and start an external video in that BR
2. From the 2nd Connection, the other Browser, Join Room-1
3. You can see the video in freezing mode
4. From 1st Connect PAUSE video and REPLAY
5. In 2nd Connection the video should work as expected

**Expected behavior**

**Actual behavior**

**Screenshots**

**BBB version (optional):**
2.3.4

**Desktop (please complete the following information):**
 - OS: all OS
 - Browser: All browsers
 - Version

**Comment by nstylianides** [comment]
Any response on this issue?

**Comment by hostbbb** [comment]
did this work in 2.3.3 or earlier? does it only break in a breakout room,  or the same thing occurs in nornal room?

**Comment by nstylianides** [comment]
It only appears in Breakout Rooms. In 2.3.3 was working just fine.

**Comment by nstylianides** [comment]
seems that 2.3.13 has no longer this behavior

**Comment by nstylianides** [comment]
Hi there. After many tests with 2.3.13 It seems that this issue **remains**. 
So i reopen it. Will someone be assigned or is solved in 2.4?

**Comment by nstylianides** [comment]
Just tested with public 2.4 server at https://test24.bigbluebutton.org/
Video issue seems to be solved both in Main room and Breakout Rooms. 
But 2.4 has other issues that prevent us to move to it. 
Can the solution for 2.4 applied to 2.3.13 also?

**Comment by ffdixon** [comment]
(heard that you have moved to 2.4 -- let us know if you encounter any issues there on that release)
