### ISSUE TITLE
Using 2 stun servers in turn-stun-servers.xml still gives error message

### ISSUE THREAD

**Issue by lonesomewalker** [bigbluebutton/bigbluebutton#12638]
When using 2 stun servers in turn-stun-servers.xml, bbb-conf --whatever still gives an error message that the server is not responding (and not telling which).

But, both are fine, if used single.

**Comment by jpetrihst** [comment]
Can confirm this. Output is:

```
#
# Warning: Failed to verify STUN server at  3478 with command
#
#    stunclient --mode full --localport 30000  3478
#
```

**Comment by lonesomewalker** [comment]
I already reported this weeks ago... was a "nice discussion" here.
Hopefully with a confirmation now this gets accepted as a bug.

**Comment by basisbit** [comment]
@lonesomewalker could you please link that mentioned discussion for completeness?
