### ISSUE TITLE
2.3 + 2.4 - Demoted moderator with access to lock viewers settings

### ISSUE THREAD

**Issue by antonbsa** [bigbluebutton/bigbluebutton#12636]
**Describe the bug**
Demoted moderators who were in the `lock viewers` settings screen can stay there. If the "ex-moderator" tries to apply this, the "see other viewers' webcam" option is being applied;

**To Reproduce**
1. As moderator (A), open the lock screen settings;
2. demote user A to a viewer
3. change all options and try to apply

**Expected behavior**
After demoted, go back to meeting page;

**Actual behavior**
Can stay in the lock viewers settings screen - and change one option;

**Video**
_Note: also occurs in v2.4_

https://user-images.githubusercontent.com/56703993/122807161-9a95ac80-d2a1-11eb-995c-dcf3f362289d.mp4

**Comment by antobinary** [comment]
@antonbsa reports this occurs again on 2.3.10-candidate

**Comment by antonbsa** [comment]
Issue rewritten in #13116.
