### ISSUE TITLE
App.error.fallback.view.description

### ISSUE THREAD

**Issue by erpsolns** [bigbluebutton/bigbluebutton#12633]
**Describe the bug**
When session is on and slides and we had some polls - all of a sudden the screen went with the message with blackscreen -App.error.fallback.view.description
[React Intl] An 'id' must be provided to format a message
app.error.fallback.view.relaod button

And cant bring back the slides at all.

**To Reproduce**

**Expected behavior**

**Actual behavior**
only slides and poll results should be seen - slides gone away

**Screenshots**

**BBB version (optional):**
2.3.4
Example:
$ sudo bbb-conf --check | grep BigBlueButton
BigBlueButton Server 2.2.2 (1816)

All users experienced irrespective of system
**Desktop (please complete the following information):**
 - OS: [e.g. Windows, Mac]
 - Browser [e.g. Chrome, Safari]

All users experienced the same thing irrespective of devices
**Smartphone (please complete the following information):**
 - Browser [e.g. stock browser, Safari]

**Additional context**
All users

**Comment by steffen-moser** [comment]
We have seen this just a few minutes ago in BBB 2.3.4. I can say that the professor was doing polls.

![error1](https://user-images.githubusercontent.com/4097996/123322657-d98f6080-d534-11eb-8f5d-5cb1460a151b.png)

 I am trying to analyze the logs.

**Comment by antobinary** [comment]
Let's merge this into #12532 since it looks like a common cause.
