### ISSUE TITLE
Chat option : "startClosed: true" not working in 2.4-alpha-1 

### ISSUE THREAD

**Issue by hunben** [bigbluebutton/bigbluebutton#12660]
**Describe the bug**
Option setting in html5 client Chat startClosed set to true not working in 2.4-alpha-1 but working in 2.3

**To Reproduce**
1. Edit/set option "startClosed : true" in /usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml line 401
2. bbb-conf --restart
3. Go to create room
4. See Chat module starts Open /not collapsed

**Expected behavior**
View Chat module closed / collapsed

**Actual behavior**
View Chat module open / not collapsed

**Comment by antobinary** [comment]
Related to https://github.com/bigbluebutton/bigbluebutton/issues/12647
