### ISSUE TITLE
2.4 - Auto-assigned presenter cannot manage presentations

### ISSUE THREAD

**Issue by antonbsa** [bigbluebutton/bigbluebutton#12679]
**Describe the bug**
When a moderator leaves the meeting as a presenter, another moderator is assigned as presenter but he cannot manage the presentations (when clicked, nothing happens).
_Note: Only in v2.4_

**To Reproduce**
1. Join with 2 moderators
2. left the meeting with one of them
3. try to manage presentation

**Video**

https://user-images.githubusercontent.com/56703993/123705265-1a40ef80-d83d-11eb-95d0-469cf4d70675.mp4

**Comment by jfsiebel** [comment]
Hi @antonbsa, tried to repoduce this problem but I couldn't. Could test again and check if the problem still happens?
