### ISSUE TITLE
Option to mix stereo microphone channels 

### ISSUE THREAD

**Issue by jmu2015** [bigbluebutton/bigbluebutton#12671]
**Is your feature request related to a problem? Please describe.**
I have an audio interface that has two microphone inputs. I wanted to use it with a good microphone on video calls. With other tools like Skype, Zoom, discord, etc. it works fine. On BigBlueButton, however, the audio is only on the left channel. The problem is that audio interfaces often send a stereo stream to the computer, each side consisting of the signal of one input. It is up to the software to mix these together. 

**Describe the solution you'd like**
Microphone input should be mixed to mono if it is a stereo signal. When sharing a screen and computer audio, the computer audio should be treated differently and not be mixed. 
Possibly also a button that asks if the audio should be mixed or not.

**Describe alternatives you've considered**
Buy a more expensive audio interface that does the mixing? Not really a solution. 
There might be software solutions, but that would be really complicated because it would involve routing the microphone audio to another application and then using this app's output for BBB.

**Comment by hostbbb** [comment]
you can set a constraint to 2 channel input in getUserMedia,  in chrome it did not work with AEC enabled, last tested early this year.

with firefox, AEC worked with stereo input.

Also, in mod_conference you need set the conference profile cdquality to have "2 channels" to put conference in stereo.
The audio recording files are 2x the size when recorded.

regards,
Stephen

**Comment by jmu2015** [comment]
I think we misunderstood. First of all, what do you mean by AEC? 
I now tried the same situation with Chromium Edge, and there it worked as I wanted it to. I don't know why exactly that is though. 

My problem was that when using an audio interface as a microphone, the audio on the other end was just on the left. This problem does not occur with the Edge browser. 

Regards jmu2015

**Comment by hostbbb** [comment]
chrome had an issue where 2 channel audio input would not work when AEC "Acoustic Echo Cancelation" was enabled.
Edge is now based on chrome engine, so the audio effect should be the same in theory
if you are using 2.3 there is an option in html5 client settings to turn off client audio filters, and toggle and see if anything is different

i was talking about configuring freeswitch for stereo so your 2 channels would be seperated and mixed all the way thru mod conference and the other participants could here the difference in the left/right channel of your mic.

think, you just want mod_conference to mix the L/R and send 1 combined feed dont care about stereo.    you want your audio to just come out both channels

are you on 2.2 or 2.3?

**Comment by lfrancke** [comment]
I know this is old...but I thought I'd at least mention that the same problem still exists today for me.

BBB is unusable for me on Firefox for this reason. It works on Chrome but not on Firefox.
Other meeting solutions e.g. Zoom, Google Meet, Jitsi work just fine on both browsers.

The end result for others in a meeting is that I'm barely audible (volume is basically halfed).
