### ISSUE TITLE
Without Turn Server Audio test is 1 second, with Turn Server 7-8 seconds?

### ISSUE THREAD

**Issue by peter-lernyx** [bigbluebutton/bigbluebutton#12670]
Could this be the turn server trying different connection options, starting with those that don't work? 

Can I change that order to go back to immediate connection as in without turn server. Can someone point me in a direction for analysis?

Much appreciated

Peter

**Comment by laserrapt0r** [comment]
In your scenario would it be working without a turn server? It trys to connect directly and if that fails it tries to connect via turn. But if a direct connection is working it should not take longer.

**Comment by peter-lernyx** [comment]
I had this running without turn and that where the connection was immediate. I installed turn because of one customer's firewall and now it's 7-8 seconds. So I already know it works fine without turn but I need to have it deployed and don't want to accept the delay.

**Comment by PhMemmel** [comment]
Please someone correct me, if I'm wrong about that, but AFAIK it works like that: The browser tries every possible connection to figure out what connection is the best and, after that, decides which one it takes.
So if you have more possible connections (e. g. additional turn servers) in general you will have a longer delay before being able to join.

**Comment by hostbbb** [comment]
Correct during gathering of ice candidates its contacting the turn(s) server as well to get a valid IP and port to offer if relaying is needed.

Also if you have bunch of network adapters, and vpns, or vmware players, that list gets large and even more time is required.    

 

You can look at the browser console in debug or webrtc tab and see all the candidates

 

Regards,

Stephen

**Comment by peter-lernyx** [comment]
Maybe it's me but I don't strictly understand how this relates to my question. So let me ask this: Where **on the turn server** can I check the order in which the turn server checks available and workable connections and where if any can I modify that configuration of connections to check, so that it's done in the order that is fastest?

**Comment by hostbbb** [comment]
the turn server does not check...  its the browser in its webrtc icegathering step... the turn always provides a ip, and port which is added to the list in the SDP that is sent to freeswitch.   So the browser is the one taking all the time gathering to send the SDP to freeswitch over websocket.

**Comment by hostbbb** [comment]
there is a protocol called trickle ice that speeds up the process of connections used by most modern webrtc systems.   bbb is currently limited to being able to use... our current media servers.  freeswitch/kurento do not have full support at this time.

@prlanzarin has best understanding, and looking at this on deciding future media architecture for future releases.

**Comment by peter-lernyx** [comment]
Ah ok, I see what you say.
