### ISSUE TITLE
Capture Live Captions

### ISSUE THREAD

**Issue by BuckDuane** [bigbluebutton/bigbluebutton#12673]
Google Chrome can provide Live Captions. We want to be able to capture this feed to use to create audio transcripts of a meeting. The reverse function of providing a stenographer. The ideal solution would work incrementally with a save, pause/resume, and append to file options. Bonus for inserting speakers name and elapsed time stamp between conversations.

**Comment by hostbbb** [comment]
freeswitch has all the audio. and talking events on server side, could have server side process transcribe and place the data into a notes window.. where it could be edited and saved.    google has paid for apis to do this direct, or a docker image could join meeting similar to live stream, and use the chrome client side code forgoing cost.

just needs to be speced. definitely doable.
