### ISSUE TITLE
Webcam move when click to drag

### ISSUE THREAD

**Issue by owenz97** [bigbluebutton/bigbluebutton#12697]
![124230545-7dd75f80-db52-11eb-8fbe-a8436184ed18](https://user-images.githubusercontent.com/86584607/124231146-3e5d4300-db53-11eb-9b6f-f59759e296e2.png)

When you want to drag the webcam to another place, the webcam will move left when you click on the webcam for moving.

**Comment by basisbit** [comment]
please fill in the sections from the issue template, which you were requested to fill in when creating this issue here.

**Comment by owenz97** [comment]
**Describe the bug**
When you want to drag the webcam to another place, the webcam will move left when you click on the webcam for moving.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to Meeting and open webcam
2. Click and hold on the webcam for dragging, make sure not to move mouse when clicking on it
3. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Actual behavior**
The Webcam should not be moved when dragging

**Screenshots**
![124231146-3e5d4300-db53-11eb-9b6f-f59759e296e2](https://user-images.githubusercontent.com/86584607/124408086-d3954d00-dd88-11eb-9320-cb892da75565.png)

**BBB version:**
BigBlueButton Server 2.3
