### ISSUE TITLE
Sorting in users list is incorrect

### ISSUE THREAD

**Issue by MWRAMC** [bigbluebutton/bigbluebutton#12699]
**Describe the bug**
The content of a downloaded user list is not sorted correct.
The list named "Sorted by first name" is sorted by the last name and the list named "Sorted by last name" is sorted by the first name.

**To Reproduce**
1. Start a session with BBB.
2. Login parallel with a few users.
3. Download a user list and open it.

**Expected behavior**
The headers of the downloaded lists give the correct information about how the lists were sorted.

**Actual behavior**
The included list named "Sorted by first name" is sorted by the last name and the list named "Sorted by last name" is sorted by the first name.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/16242126/124259809-3b505b80-db2f-11eb-82db-f8098bb0019b.png)

**Further information**
We use BBB in combination with the Moodle plugin.

**Comment by antobinary** [comment]
Hi @MWRAMC 

What version of BigBlueButton are you using? Perhaps you could add info on the build number (About page in the menu where Settings/Logout are)

**Comment by MWRAMC** [comment]
Hi antobinary,
thanks for your answer.

We use BBB Clientversion 1783 and the Moodle plugin v2.4.0.

**Comment by antobinary** [comment]
Thanks! This would be BigBlueButton 2.3.4+

Just a bit more info pls:
The following is a common pattern in [most?] English speaking countries

Lastname, Firstname

1) In your example are there any `,` ?
2) What locale do you use? German?

It sounds like we need to take into consideration the locale used.

**Comment by MWRAMC** [comment]
Hi antobinary,

sry for my late answer.
I had to contact one of our developers for this information.
Because of your hint we checked all steps where the user's name will be mentioned and finally where able to found the reason for that.
This is not a bug at all. In Moodle you have to define what style has the fullname, where we have defined "lastname, firstname". If we change this, the sorting would be correct.

Thanks for your hint. We will close the ticket.

Cheers,
Martin
