### ISSUE TITLE
app.error.408 Authentication timeout 408 with test.bigbluebutton.org

### ISSUE THREAD

**Issue by mahmood2395** [bigbluebutton/bigbluebutton#12690]
**Describe the bug**
when joining the test.bigbluebutton.org after a minute of waiting got this error

**To Reproduce**
1. Go to 'test.bigbluebutton.org' and enter your name
2. Click on 'join'
3. See error

**Expected behavior**
expected to join the meeting instead of this error

**Screenshots**
#12526 

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 91
 -------------------
- bbb version 2.3.4
- ubuntu 18.04

**Additional context**
i had the exact same problem with my server,
explained here :  #https://github.com/bigbluebutton/bigbluebutton/issues/12526#issuecomment-865092795
i'll be grateful if anyone can look at this problem

**Comment by basisbit** [comment]
Please do not open duplicate issues
