### ISSUE TITLE
Feature request: Popup notification for event "user left"

### ISSUE THREAD

**Issue by timm2k** [bigbluebutton/bigbluebutton#12698]
For committee meetings, it is important to provide information about participants who have left the meeting. This may affect the quorum of the panel.
It is very important for the meeting chair or minute taker to get an indication when participants leave the current meeting.

Is it possible to integrate a popup notification for the event "user left" in BBB on short (like user join notification)?

**Comment by hostbbb** [comment]
one easy workaround.. in freeswitch enable the enter and leave sounds in conference profile.   Will get an audible beep anytime an audio user enters or leaves the meeting. When here the noise, look at user list.
after the meeting, the events.xml has the complete history of joins/leaves for reporting.
