### ISSUE TITLE
Poll choices misaligned

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#12709]
**Describe the bug**
Poll voter sees poll choices misaligned

**To Reproduce**
1. Presenter starts an ABCD poll

**Expected behavior**
Each of the options buttons should be equal weight/area

**Actual behavior**
A and C are much larger than B and D

**Screenshots**
![Screenshot from 2021-07-02 16-04-08](https://user-images.githubusercontent.com/6312397/124340517-c0656000-db83-11eb-9559-b5fc246dc44e.png)

**BBB version:**
BigBlueButton 2.3.4

Desktop

**Comment by hiroshisuga** [comment]
I could not reproduce it, either on 2.3.4 or on 2.3.x-dev (2.3.5 candidate), using Firefox or Edge...

**Comment by antobinary** [comment]
@ramonlsouza do you know in which case we display polling options centered in the screen (rather than bottom right-hand corner)?

**Comment by ramonlsouza** [comment]
> @ramonlsouza do you know in which case we display polling options centered in the screen (rather than bottom right-hand corner)?

On any device with -480px height or width ([source](https://github.com/bigbluebutton/bigbluebutton/blob/95f5b6faf961cebec7c2beaaba959b1ad2e64c13/bigbluebutton-html5/imports/ui/components/polling/styles.scss#L49-L61))
