### ISSUE TITLE
Layout issues on mobile with portrait presentation

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#12708]
**Describe the bug**
Portrait presentation + webcam causes layout issues (see screenshot) on mobile.

**Expected behavior**
The webcam is supposed to be above the presentation

**Actual behavior**
The webcam is displayed beside the presentation, pushing it out of the visible area

**Screenshots**
![nW-vti7Y](https://user-images.githubusercontent.com/6312397/124340221-b7738f00-db81-11eb-847a-eed9c5c9ab1b.jpg)

**BBB version (optional):**
BigBlueButton Server 2.3.x

**Smartphone (please complete the following information):**
 - Browser [e.g. stock browser, Safari]

**Additional context**
Reported in bbb-dev google group https://groups.google.com/g/bigbluebutton-dev/c/obtGS_U7row/m/7qodeKD3AAAJ on 2.3.0+

**Comment by mabras** [comment]
This is a video from the [same thread](https://groups.google.com/g/bigbluebutton-dev/c/obtGS_U7row/m/7qodeKD3AAAJ
) to show the problem :
https://www.youtube.com/watch?v=XkLEDgefE7I

**Comment by IBROF** [comment]
The issue persists with all smartphones.
