### ISSUE TITLE
[Feature request] Drop `html5client` from URL and API response

### ISSUE THREAD

**Issue by mabras** [bigbluebutton/bigbluebutton#12710]
After dropping the flash client, there is no need to be explicit about html5client. It is in the URL and it is shown in API response.

**Describe the solution you'd like**
I prefer to drop it and not replace it with anything.
Before:
```
https://example.com/html5client/join?sessionToken=ijjg0gsnihz64off
```
After:
```
https://example.com/join?sessionToken=ijjg0gsnihz64off
```

**Comment by hostbbb** [comment]
there is a post in forums, on how to edit settings.yml and nginx rule set to change html5client to something else.
tweakin nginx rules should allow it working at /, just needs someone to focus on this.

when you figure it out, add steps here and could be considered in future.   Think the core developers are working on deeper challenges for next release...  great opportunity for someone to provide solution from community.

**Comment by antobinary** [comment]
Starting point: https://docs.bigbluebutton.org/admin/customize.html#change-the-default-path-for-html5-client
