### ISSUE TITLE
v. 2.3.* sanity *.done files left in folder after record is processed

### ISSUE THREAD

**Issue by amg-web** [bigbluebutton/bigbluebutton#12716]
v. 2.3.* sanity *.done files left in folder /var/bigbluebutton/recording/status/sanity/ after record is processed
even more then 14 days.

Af far as I remember they was removed in v. 2.2.x

**Comment by InfoFractal** [comment]
This breaks bbb-exporter, had to add a cron job to delete all .done files to correctly report finished recordings.

**Comment by amg-web** [comment]
sanity files was removed by /usr/local/bigbluebutton/core/scripts/rap-process-worker.rb
despite the fact this script is still in a folder on developer branch actually this script is missing on production systems.
https://github.com/bigbluebutton/bigbluebutton/blob/develop/record-and-playback/core/scripts/rap-process-worker.rb
So I do not know if it still needed by BBB

**Comment by antobinary** [comment]
Merging into https://github.com/bigbluebutton/bigbluebutton/issues/12365
