### ISSUE TITLE
Support localization of FreeSWITCH audio prompts

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#12722]
**Is your feature request related to a problem? Please describe.**
Currently, FreeSWITCH only provides audio prompts in english.

**Describe the solution you'd like**
Customers in French speaking countries would prefer to have French audio prompts.  FreeSWITCH use the browser's locale for the audio prompts.

**Additional context**
Currently FreeSWITCH is only shipping with `en` locales.  We would need to install additional audio language files

  https://freeswitch.org/confluence/display/FREESWITCH/Language+Files

**Comment by ichdasich** [comment]
Great idea, especially as this would also help with phone dial-in i18n.

As this is somewhat related: Changing the greeting for dial-in is also not that difficult; Might be worth to add to the documentation as well.

Have: `input.mp3`

```
ffmpeg -i input.mp3 -acodec pcm_s16le -ac 1 -ar 8000 custom-greeting.wav
ffmpeg -i input.mp3 -acodec pcm_s16le -ac 1 -ar 16000 custom-greeting.wav
ffmpeg -i input.mp3 -acodec pcm_s16le -ac 1 -ar 32000 custom-greeting.wav
ffmpeg -i input.mp3 -acodec pcm_s16le -ac 1 -ar 48000 custom-greeting.wav
```

Place the files:
```
/opt/freeswitch/share/freeswitch/sounds/en/us/callie/conference/8000/custom-greeting.wav
/opt/freeswitch/share/freeswitch/sounds/en/us/callie/conference/16000/custom-greeting.wav
/opt/freeswitch/share/freeswitch/sounds/en/us/callie/conference/32000/custom-greeting.wav
/opt/freeswitch/share/freeswitch/sounds/en/us/callie/conference/48000/custom-greeting.wav
```

Adjust my_provider.xml:
```
   <action application="play_and_get_digits" data="5 5 3 7000 # conference/custom-greeting.wav ivr/ivr-that_was_an_invalid_entry.wav pin \d+"/>
```

Works analogous for invalid-entry.

**Comment by Daedalus3** [comment]
@ffdixon I created German audio files that can be found here: https://github.com/Daedalus3/freeswitch-german-soundfiles 
If someone provides me with a French text translation, I'll try to make French versions.

You may also find a solution for setting the right configuration values at my repo. Maybe it helps integrating it into BBB.

**Comment by rasos** [comment]
We are working on some earcons to make some of the translations obsolete. Here is the draft set of our sound engineer: https://git.fairkom.net/hosting/fairteaching/-/issues/34#note_35237 - we are on the way deploying that on https://dev.fairteaching.net  for user testing.
