### ISSUE TITLE
Missing translation strings

### ISSUE THREAD

**Issue by pielonet** [bigbluebutton/bigbluebutton#12737]
Hi,

It looks like some strings were not translated in BBB 2.3 and are not present in the Transifex project : 3 layout options

- Listen only option 
If disabled, a microphone is needed to join the conference.
- Skip media check before usage
If enabled, the user has not to perform an echo call and webcam preview on the first join (available since BBB server 2.3). 
- Clean layout 
If enabled, the user list, chat area and presentation are hidden by default.

Please add these strings to Transifex so that we can translate them !
Kind regards,
Thierry

**Comment by antobinary** [comment]
@ali-alhaidary It's possible that we have some 2.3 vs 2.4 discrepancy.
What is the exact json key you're referring to?

**Comment by ali-alhaidary** [comment]
@antobinary I do not know the keys, but such strings are not in transifex, and I can not locate any string that is not translated in the html5 web client that we use for 2.4. The strings are:
Skip media check before usage
Clean layout

**Comment by ali-alhaidary** [comment]
@pielonet Are you sure of the syntax?

**Comment by antobinary** [comment]
If there are remaining strings that are not localized in BBB 2.3 or 2.4+ please copy-paste the exact string (or screenshot it) and we can take it from there. Closing for now as the strings in question seem to be obsolete
