### ISSUE TITLE
Webcam moves left sharply when trying to drag

### ISSUE THREAD

**Issue by owenz97** [bigbluebutton/bigbluebutton#12751]
Describe the bug:
- When you want to drag the webcam to another place, the webcam will move left when you click on the webcam for moving.

To Reproduce

- Go to Meeting and open webcam
- Click and hold on the webcam for dragging, make sure not to move mouse when clicking on it
- See error

Expected behavior:
- A clear and concise description of what you expected to happen.

Actual behavior:
- The Webcam should not be moved when dragging

Screenshots:
![124408086-d3954d00-dd88-11eb-9320-cb892da75565](https://user-images.githubusercontent.com/86584607/125027257-4c6a1100-e0c9-11eb-9b13-26b69101450b.png)

BBB version:
BigblueButton 2.3

**Comment by ramonlsouza** [comment]
fixed by #12930
