### ISSUE TITLE
Job for tomcat8.service failed after bbb-conf --start / bbb-conf --restart

### ISSUE THREAD

**Issue by andrem1987** [bigbluebutton/bigbluebutton#12750]
**Describe the bug**
I installed BBB 2.3 on a fresh Ubuntu 18.04 with the bbb-install script and the `bbb-demo`. After uninstalling the demo with `apt remove bbb-demo` and `apt autoremove` i am receiving the following message after every start/restart:

```bash
# bbb-conf --restart
Restarting BigBlueButton 2.3.6 ...
Stopping BigBlueButton

Applying updates in /etc/bigbluebutton/bbb-conf/apply-config.sh: 
  - Enable Firewall and opening 22/tcp, 80/tcp, 443/tcp and 16384:32768/udp
Skipping adding existing rule
Skipping adding existing rule (v6)
Skipping adding existing rule
Skipping adding existing rule (v6)
Skipping adding existing rule
Skipping adding existing rule (v6)
Firewall is active and enabled on system startup

Starting BigBlueButton
Job for tomcat8.service failed because the control process exited with error code.
See "systemctl status tomcat8.service" and "journalctl -xe" for details.
```

By uninstalling the `bbb-demo` package, the `tomcat8` will be uninstalled as well, so this message makes totally sense ;-) It seems that there is a false positive in the `/usr/bin/bbb-conf` at line *402*.

**To Reproduce**
1. uninstall `bbb-demo` and clean up with `apt autoremove`
2. Restart bbb with `bbb-conf --restart`

**Comment by andrem1987** [comment]
Okay, i figured it out. I entered the command `systemctl list-units --full -all | grep tomcat` (just like in the `bbb-conf` at line *402*, but without -q) and got the following output:

```bash
● tomcat8.service                                                                                  loaded    failed   failed    LSB: Start Tomcat.
```
Even though the daemon was uninstalled, there where some systemd leftovers. After running the following commands the problem was gone:

```bash
systemctl disable tomcat8.service
systemctl daemon-reload
systemctl reset-failed
```

**Comment by andrem1987** [comment]
Oh man... i just saw that i used `apt remove bbb-demo` instead of `apt purge bbb-demo`... So all the steps from above would not have been necesseray. Time to go to bed.

My soliloquy can be closed ;-)

**Comment by antobinary** [comment]
Hi @andrem1987 
Thanks for documenting why this happened on your setup. This info may be useful to others in the future.
Closing this issue without code/config changes.

**Comment by mamair** [comment]
I used "apt purge bbb-demo" to remove demo and had the same error message ;-)

Tipp of andrem1987 solved problem. Thank You!

maybe bbb-conf could test if demo has been removed properly and disable tomcat if necessary, or make a note at /support/troubleshooting
