### ISSUE TITLE
Publicly available API to retrieve the server version

### ISSUE THREAD

**Issue by bennyboer** [bigbluebutton/bigbluebutton#12762]
Hello there, I am currently developing a [BBB client](https://github.com/bennyboer/bbb_app) for mobile devices that is using the HTML5 server interfaces.
Unfortunately the interface tends to change every now and then and leaves the app broken.
Thus I am only able to really support one version of the BBB server at a time.

Now I see that using the HTML5 server interfaces is kind of an "inofficial" way of interacting with BBB, but as far as I know the only sensible one to achieve the desired results of having an alternative client.
One simple way for me to support multiple BBB server versions at once is if I could retrieve the server version from a publicly available API of the individual BBB servers.

### Related issues

I've seen that #9212 already addressed this issue, but not specifically an easy way to retrieve the version programmatically. But maybe it's still considered to be a duplicate.

### Security concerns

I also see that a publicly available API may be a security problem that we have to consider, but personally I don't see a feasible alternative.

**Comment by antobinary** [comment]
Implemented in https://github.com/bigbluebutton/bigbluebutton/pull/13609

**Comment by bennyboer** [comment]
Is this really publicly available or do I need a shared secret to access this information?

**Comment by antobinary** [comment]
`someserver.com/bigbluebutton/api` returns this. No shared secret / checksum, see https://test.bigbluebutton.org/bigbluebutton/api  (

But the bbbVersion field will only have content if the bigbluebutton.properties field is enabled (or overridden in /etc/bigbluebutton/bbb-web.properties)
