### ISSUE TITLE
Get notification when user have weak connection

### ISSUE THREAD

**Issue by dothanhhao** [bigbluebutton/bigbluebutton#12770]
I'm using BBB ver 2.3
Can I get the notification when user have weak connection
![image](https://user-images.githubusercontent.com/26756461/125647438-680e2dc3-2076-4925-9e26-62b0d0e8088e.png)

**Comment by ffdixon** [comment]
If you are a moderator, when you look at your connection status indicator, you'll see a log of your messages and all other viewers (students) in the session.

**Comment by dothanhhao** [comment]
> If you are a moderator, when you look at your connection status indicator, you'll see a log of your messages and all other viewers (students) in the session.

Hi @ffdixon ,
I want to show a notification for user if they are having bad network connection. Currently, we only have an UI that show user connection status, do we have any detail parameters to support this situation?
