### ISSUE TITLE
certificate expired for ubuntu.bigbluebutton.org repository

### ISSUE THREAD

**Issue by zimmersi** [bigbluebutton/bigbluebutton#12776]
**Describe the bug**
Your lets encrypt certificate for the apt repository is expired!

**Installation type**
bbb-install script

**Console output**
Err:15 https://ubuntu.bigbluebutton.org/bionic-23 bigbluebutton-bionic Release
  Certificate verification failed: The certificate is NOT trusted. The certificate chain uses expired certificate.  Could not handshake: Error in the certificate verification. [IP: 167.99.180.121 443]
Reading package lists... Done
E: The repository 'https://ubuntu.bigbluebutton.org/bionic-23 bigbluebutton-bionic Release' no longer has a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

wget https://ubuntu.bigbluebutton.org/repo/bigbluebutton.asc -O- | sudo apt-key add -
--2021-07-16 08:19:40--  https://ubuntu.bigbluebutton.org/repo/bigbluebutton.asc
Resolving ubuntu.bigbluebutton.org (ubuntu.bigbluebutton.org)... [sudo] password for it: 167.99.180.121
Connecting to ubuntu.bigbluebutton.org (ubuntu.bigbluebutton.org)|167.99.180.121|:443... connected.
ERROR: cannot verify ubuntu.bigbluebutton.org's certificate, issued by ‘CN=R3,O=Let's Encrypt,C=US’:
  Issued certificate has expired.
To connect to ubuntu.bigbluebutton.org insecurely, use `--no-check-certificate'.

**Comment by garblixa** [comment]
Ok, we posted this nearly the same minute :-)
See  #12777

**Comment by ffdixon** [comment]
Fixed -- updated the certificate on ubuntu.bigbluebutton.org

**Comment by zimmersi** [comment]
great! it is working again....
