### ISSUE TITLE
Stop screenshare if external video was initiated

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#12803]
This is a follow-up from https://github.com/bigbluebutton/bigbluebutton/pull/12801 and https://github.com/bigbluebutton/bigbluebutton/pull/12504

**Is your feature request related to a problem? Please describe.**
On both 2.3 and 2.4(under construction) when screenshare is ongoing and the presenter initiates external-video-share, the client side decides to only show the more recent - external video share. This can lead to problems with state of the meeting and consistency with recording (i.e. recording assuming screenshare continued), etc. Also it leads to additional client side decision making which should not be resposibility to client side.

**Describe the solution you'd like**
This should ultimately be a backend decision in akka-apps (see #12504 for similar logic)

**Describe alternatives you've considered**
The alternative is to keep things as they are now, but this is not ideal, see the issues mentioned above.

**Comment by ramonlsouza** [comment]
After this change in back-end, we can remove the `!shouldShowExternalVideo` additional check in [app container](https://github.com/bigbluebutton/bigbluebutton/blob/develop/bigbluebutton-html5/imports/ui/components/app/container.jsx#L169-L170), added in #12801.
