### ISSUE TITLE
Video stream limit in Chrome 92

### ISSUE THREAD

**Issue by PhMemmel** [bigbluebutton/bigbluebutton#12806]
**Describe the bug**
The new Chrome 92 seems to have a limitation for video streams.

**To Reproduce**
1. Open session with many video streams (also pagination works!)
2. Switch to second page, maybe switch back to first page (I had the setup of 16 concurrent webcam streams)
3. See some streams are blackened out.
4. Switch back to first page: (Nearly) all cams are blackened out.
5. You have to reload the session to be able to see any webcam streams.
6. Browser console shows:
![grafik](https://user-images.githubusercontent.com/65113153/126657324-9e1f580f-b2a1-44c9-9d84-3ebf9ecba647.png)

**Expected behavior**
All video streams should be shown.

**Actual behavior**
When reaching max amount of streams they aren't loaded anymore.

**BBB version:**
Tested on my 2.3.7 server.

**Desktop (please complete the following information):**
 - OS: Current Windows 10 64bit
 - Chrome 64bit 92.0.4515.107

**Additional context**
Switching back to first page will blacken out these streams as well as they are apparently seen as new/additional streams "of this website" after switching back to first page.

This is not a BBB bug, but if the Chrome developers aren't reverting this limitation, this will be a problem for BBB. Here the Jitsi discussion about it:
https://community.jitsi.org/t/chrome-new-version-limits-participants-in-one-room-at-40-70/103063/1

A workaround might be neccessary...

**Comment by EmmyGraugans** [comment]
An idea for a workaround(?) seems to be:

https://stackoverflow.com/questions/68480528/blocked-attempt-to-create-a-webmediaplayer-as-there-are-too-many-webmediaplayers

haven't tested that, nor do I fully understand it, and apologies if it isn't applicable here at all...

**Comment by PhMemmel** [comment]
As #12814 and #12810 both are merged, I'm closing this.
