### ISSUE TITLE
bbb-record lists recordings despite disableRecordingDefault being true

### ISSUE THREAD

**Issue by herzkerl** [bigbluebutton/bigbluebutton#12811]
**Describe the bug**
Despite having recordings disabled globally (via bigbluebutton.properties), BigBlueButton shows recordings (at least via CLI). It seems though, that neither audio nor video actually gets recorded, as the folders within `/var/bigbluebutton` only seem to contain slides.

**To Reproduce**
Set `disableRecordingDefault=true` in `/usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties` and start a room.

**Expected behavior**
There should be no recordings at all.

**Actual behavior**
`bbb-record --list` shows recordings
`/var/bigbluebutton` contains several folders with recordings

**Additional context**
`root@host:/var/bigbluebutton# bbb-conf --version`
BigBlueButton Server 2.3.7 (2394)

**Full file list from within one folder:**

`root@host:/var/bigbluebutton# ls -laR 17f94b601e2ff3e44e694619c49ff6d7fd31d246-1627025362967
17f94b601e2ff3e44e694619c49ff6d7fd31d246-1627025362967:`
`total 12`
`drwxr-xr-x  3 bigbluebutton bigbluebutton 4096 Jul 23 09:29 .`
`drwxr-xr-x 26 bigbluebutton bigbluebutton 4096 Jul 23 09:29 ..`
`drwxr-xr-x  3 bigbluebutton bigbluebutton 4096 Jul 23 09:29 17f94b601e2ff3e44e694619c49ff6d7fd31d246-1627025362967`

`17f94b601e2ff3e44e694619c49ff6d7fd31d246-1627025362967/17f94b601e2ff3e44e694619c49ff6d7fd31d246-1627025362967:`
`total 12`
`drwxr-xr-x 3 bigbluebutton bigbluebutton 4096 Jul 23 09:29 .`
`drwxr-xr-x 3 bigbluebutton bigbluebutton 4096 Jul 23 09:29 ..`
`drwxr-xr-x 5 bigbluebutton bigbluebutton 4096 Jul 23 09:29 d2d9a672040fbde2a47a10bf6c37b6a4b5ae187f-1627025363107`

`17f94b601e2ff3e44e694619c49ff6d7fd31d246-1627025362967/17f94b601e2ff3e44e694619c49ff6d7fd31d246-1627025362967/d2d9a672040fbde2a47a10bf6c37b6a4b5ae187f-1627025363107:`
`total 384`
`drwxr-xr-x 5 bigbluebutton bigbluebutton   4096 Jul 23 09:29 .`
`drwxr-xr-x 3 bigbluebutton bigbluebutton   4096 Jul 23 09:29 ..`
`-rw-r--r-- 1 bigbluebutton bigbluebutton 369690 Jul 23 09:29 d2d9a672040fbde2a47a10bf6c37b6a4b5ae187f-1627025363107.pdf`
`drwxr-xr-x 2 bigbluebutton bigbluebutton   4096 Jul 23 09:29 svgs`
`drwxr-xr-x 2 bigbluebutton bigbluebutton   4096 Jul 23 09:29 textfiles`
`drwxr-xr-x 2 bigbluebutton bigbluebutton   4096 Jul 23 09:29 thumbnails`

`17f94b601e2ff3e44e694619c49ff6d7fd31d246-1627025362967/17f94b601e2ff3e44e694619c49ff6d7fd31d246-1627025362967/d2d9a672040fbde2a47a10bf6c37b6a4b5ae187f-1627025363107/svgs:`
`total 472`
`drwxr-xr-x 2 bigbluebutton bigbluebutton   4096 Jul 23 09:29 .`
`drwxr-xr-x 5 bigbluebutton bigbluebutton   4096 Jul 23 09:29 ..`
`-rw-r--r-- 1 bigbluebutton bigbluebutton 350648 Jul 23 09:29 slide1.svg`
`-rw-r--r-- 1 bigbluebutton bigbluebutton  21964 Jul 23 09:29 slide2.svg`
`-rw-r--r-- 1 bigbluebutton bigbluebutton  21964 Jul 23 09:29 slide3.svg`
`-rw-r--r-- 1 bigbluebutton bigbluebutton  21964 Jul 23 09:29 slide4.svg`
`-rw-r--r-- 1 bigbluebutton bigbluebutton  21964 Jul 23 09:29 slide5.svg`
`-rw-r--r-- 1 bigbluebutton bigbluebutton  21964 Jul 23 09:29 slide6.svg`

`17f94b601e2ff3e44e694619c49ff6d7fd31d246-1627025362967/17f94b601e2ff3e44e694619c49ff6d7fd31d246-1627025362967/d2d9a672040fbde2a47a10bf6c37b6a4b5ae187f-1627025363107/textfiles:`
`total 32`
`drwxr-xr-x 2 bigbluebutton bigbluebutton 4096 Jul 23 09:29 .`
`drwxr-xr-x 5 bigbluebutton bigbluebutton 4096 Jul 23 09:29 ..`
`-rw-r--r-- 1 bigbluebutton bigbluebutton  475 Jul 23 09:29 slide-1.txt`
`-rw-r--r-- 1 bigbluebutton bigbluebutton   37 Jul 23 09:29 slide-2.txt`
`-rw-r--r-- 1 bigbluebutton bigbluebutton   37 Jul 23 09:29 slide-3.txt`
`-rw-r--r-- 1 bigbluebutton bigbluebutton   37 Jul 23 09:29 slide-4.txt`
`-rw-r--r-- 1 bigbluebutton bigbluebutton   37 Jul 23 09:29 slide-5.txt`
`-rw-r--r-- 1 bigbluebutton bigbluebutton   37 Jul 23 09:29 slide-6.txt`

`17f94b601e2ff3e44e694619c49ff6d7fd31d246-1627025362967/17f94b601e2ff3e44e694619c49ff6d7fd31d246-1627025362967/d2d9a672040fbde2a47a10bf6c37b6a4b5ae187f-1627025363107/thumbnails:`
`total 36`
`drwxr-xr-x 2 bigbluebutton bigbluebutton 4096 Jul 23 09:29 .`
`drwxr-xr-x 5 bigbluebutton bigbluebutton 4096 Jul 23 09:29 ..`
`-rw-r--r-- 1 bigbluebutton bigbluebutton 4885 Jul 23 09:29 thumb-1.png`
`-rw-r--r-- 1 bigbluebutton bigbluebutton  573 Jul 23 09:29 thumb-2.png`
`-rw-r--r-- 1 bigbluebutton bigbluebutton  573 Jul 23 09:29 thumb-3.png`
`-rw-r--r-- 1 bigbluebutton bigbluebutton  573 Jul 23 09:29 thumb-4.png`
`-rw-r--r-- 1 bigbluebutton bigbluebutton  573 Jul 23 09:29 thumb-5.png`
`-rw-r--r-- 1 bigbluebutton bigbluebutton  573 Jul 23 09:29 thumb-6.png`

**Comment by jibon57** [comment]
Those are temporary files & will be delete in schedule. By default every 5 days but you can change it according to your needs.

https://github.com/bigbluebutton/bigbluebutton/blob/081d6a527e9cfed75d519c55561a8a8074a5498a/bigbluebutton-config/cron.daily/bigbluebutton#L34

**Comment by herzkerl** [comment]
Did that change in 2.3? Im pretty sure in earlier versions disabling recordings globally via `bigbluebutton.properties` worked differently, i.e. `bbb-record list` would not list any recordings.

**Comment by herzkerl** [comment]
Update: Also, for some installations, `bbb-record --list` doesn't show all recordings.

**Comment by GuiLeme** [comment]
Hey @herzkerl, sorry for the delay to respond to you!
So, I gathered some information, and I would like to confirm with you:

 - Is this `disableRecordingDefault=true` really used to clean out all recordings? I think it only prevents you from creating new ones, but it doesn't really exclude the others, that's why you still have those recordings under `/var/bigbluebutton`. If you are looking for something to clear out the recordings, `sudo bbb-record --deleteall` may be your solution;
 - As far as I'm concerned, this property doesn't share a bond with bbb-record, since it's part of the bbb-web component, and bbb-record command is a package in the system. What I mean is that you can't really change that specific behavior on bbb-record, while changing `bigbluebutton.properties`;
 - For 2.4 and 2.5 when you set the disableRecordingDefault=true, it just doesn't let you record the session. And it is working fine.

So, confirm all these information for me, and should you have any complaints or suggestion of feature, please, let me know. :slightly_smiling_face:
