### ISSUE TITLE
Localization for 2.4 - Transifex

### ISSUE THREAD

**Issue by PhMemmel** [bigbluebutton/bigbluebutton#12821]
**Describe the bug**
Not sure if I see this correctly, but it looks like there is no separate transifex integration for 2.4/develop.

This means that newly added keys coming with new features in 2.4 cannot be translated via transifex because transifex bot seems to pull `en.json` from `2.3.x-release` which doesn't include the language keys being added by new features.

Possible solutions:
- separate transifex repository for 2.4 targeting `en.json` of `develop` branch.
- merge language keys from `en.json` from `develop` into `2.3.x-release` so the community can help translating the new keys.

This is my conclusion because the last update of `en.json` by transifex bot seems to be from 21-07-19. Sorry, if I'm just too impatient, please close in this case.

**Comment by antobinary** [comment]
Hi @PhMemmel 

You are correct, I have not set up a Transifex project for 2.4 yet. My plan is to have this created shortly, ideally this week.
The reason for waiting until now is that there is a [rather complex] step to copy over translations from 2.3 Transifex project into this new 2.4 project, and once copied, new 2.3 translations would have to be re-translated for 2.4 even if the strings are identical.

In the release notes for 2.4-beta-1 I intend on linking to a 2.4 Transifex project for BBB HTML5 client.

**Comment by antobinary** [comment]
Transifex now has a 2.4 project for HTML5 client. The translations have been copied over from 2.3, so there is only new strings left to translate. This is what it looks like at the moment:

![Screenshot from 2021-07-27 13-48-53](https://user-images.githubusercontent.com/6312397/127203099-017f582c-b821-464e-879f-f550338cee43.png)

**Comment by PhMemmel** [comment]
Thank you very much. Going to start translating ASAP! :-)
