### ISSUE TITLE
[2.4-alpha2] Webcam/Screenshare exits when switching layouts

### ISSUE THREAD

**Issue by PhMemmel** [bigbluebutton/bigbluebutton#12820]
**Describe the bug**
When switching between one of the new layouts and "legacy" all own webcam shares are killed. This also applies when sharing the screen. Webcam shares of other participants are not affected, so isn't screen sharing of another user.

**To Reproduce**
1. Open session.
2. Share webcam, screen or both
3. Switch to "legacy" layout.
4. Share again
5. Switch to "smart" layout.

**Expected behavior**
Own webcam shares and screenshare should "survive" that switching of layouts.

**Actual behavior**
Own webcam shares and screen sharing is being cancelled whenever you switch between legacy and one of the new layouts.

**BBB version:**
2.4-alpha2

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Tested on both current Chrome and Firefox

**Additional context**
This problem doesn't occur when switching in between the new layouts (custom, smart, focus on presentation, focus on videos).

**Comment by schrd** [comment]
I can reproduce this.

**Comment by ramonlsouza** [comment]
It was a temporary issue that happened because we had different components for legacy / new layouts (so we could push new features to the new layouts without breaking legacy), and these components were dismounted/mounted after every layout switch between legacy and new layouts.

It does not happen now that #12915 was merged.

**Comment by PhMemmel** [comment]
Thanks @ramonlsouza for the explanation
Didn't know legacy will be removed that early, so closing this.
