### ISSUE TITLE
Introduce a plugin/extension/module system

### ISSUE THREAD

**Issue by ranjithrajv** [bigbluebutton/bigbluebutton#12835]
**Is your feature request related to a problem? Please describe.**
Great applications like [BBB LiveStream](https://github.com/aau-zid/BigBlueButton-liveStreaming), [BBB Recorder](https://github.com/jibon57/bbb-recorder), [BBB Twilio](https://github.com/manishkatyan/bbb-twilio) etc. are being built as an extended functionality or complementing feature for BigBlueButton, good to see massively growing adoption of BigBlueButton. The troubling part here is these have to be deployed as a separate microservice, which is not a cost-effective option and a timely process to set up and maintain.

**Describe the solution you'd like**
Introduce a mechanism that allows admins the ability to extend functionality of BigBlueButton by loading plugins/extensions/modules. 

**Describe alternatives you've considered**
We've discussed maintaining a fork, but came to a conclusion that it is hard to maintain a fork than maintaining a plugin/extension/module.

**Additional context**
BigBlueButton will become more customizable, that will be a great boost to BBB adoption. This will create an opportunity to invite/accommodate more developers into BBB ecosystem.

**Comment by ranjithrajv** [comment]
@ffdixon tagging you here to request you to respond to this proposal.

**Comment by ffdixon** [comment]
> Introduce a mechanism that allows admins the ability to extend functionality of BigBlueButton by loading plugins/extensions/modules.

We would like to have such a mechanism as well.  You can see it today in the recording scripts -- there are directories where you can add your own scripts that will become part of the recording process workflow.

BigBlueButton also uses redis to send events between the components, and mongoDB to hold the state of many components.   A third-party component running on the BigBlueButton server could subscribe to pub/sub events in specific channels to get a live stream of events, and query mongoDB to get the state of BigBlueButton's rooms.  

Given the above hooks, the question would be what other areas of BigBlueButton should become more extensible to make it easier for third-party applications to integrate?

**Comment by FreeScholar** [comment]
Go for the community built module model - similar to Drupal.org

**Comment by ffdixon** [comment]
We're still interested in exploring adding a plug-in architecture to BigBlueButton.  This issue remains open and a topic of discussion (and will probably be discussed at the upcoming [BigBlueButton Developer Summit in Berlin](https://groups.google.com/g/bigbluebutton-dev/c/E3rPyNnX0w4/m/1WkqNxheBAAJ).

**Comment by ranjithrajv** [comment]
Requesting to remove to stale status label.

Also, requesting the team to consider prioritizing this feature request in upcoming releases.

**Comment by ranjithrajv** [comment]
Dear Developer Team,

I hope this message finds you well. I wanted to kindly inquire about the status of the feature request I submitted nearly two years ago. I understand the challenges involved in implementing new features and would greatly appreciate any information you can provide regarding your plans for this particular request.

Thank you for your time and consideration.
