### ISSUE TITLE
Can not play BBB 2.3.8 recordings using scalelite as fronted

### ISSUE THREAD

**Issue by parreitu** [bigbluebutton/bigbluebutton#12833]
**Describe the bug**

A year ago I configured scalelite with 3 BBB version 2.2 servers, and it has worked perfectly. For the installation of scalelite I used the great script of @jfederico (https://jffederico.medium.com/scalelite-lazy-deployment-745a7be849f6)

Now, I am migrating the BBB servers to version 2.3.8, using the same IP addresses and DNS names for less problems.

So far so good, except that I can't play the new recordings. Apparently the version of the player has changed, and now when accessing the new recordings it gives an error because it doesn't like the URL.

When accessing through Greenlight to old recordings that were made with BBB versions 2.2.x, the URL works correctly, for example.

https://scalelite.example.com/playback/presentation/2.0/playback.html?meetingId=OLD-RECORDING-ID

On the other hand, when accessing through Greenlight to a recording made on a BBB server updated to the latest version (2.3.8), the URL changes, and gives error (404 Not Found). This would be an example:

https://scalelite.example.com/playback/presentation/2.3/NEW-RECORDING-ID

If I manually modify the URL to show the new recording with the URL format of the old recordings, it works correctly. For example

https://scalelite.example.com/playback/presentation/2.0/playback.html?meetingId=NEW-RECORDING-ID

From all this I gather that the integration of the scalelite server with the BBB nodes goes smoothly, and that the recordings from the BBB nodes are shared seamlessly with the scalelite server via the NFS folder. It seems that the only problem is when viewing the new recordings made in version 2.3.8 of the BBB nodes.

Any idea how to solve it ? As soon as I have this solved I will be able to migrate the rest of the BBB nodes of our installation.

**To Reproduce**
Access to new recordings from Scalelite fronted (Greenlight)

**Expected behavior**
Correct playback of all recordings, both old and new.

**Actual behavior**
I can only play back the new recordings if I manually modify the URL

**Comment by pedrobmarin** [comment]
Hi,

You'd probably have more success on solving this issue posting it at [scalelite's repository](https://github.com/blindsidenetworks/scalelite). As far as I can tell [v1.1](https://github.com/blindsidenetworks/scalelite/releases/tag/v1.1) is the first with support for this player. Please check on the release notes if something went missing on your deploy.

**Comment by defnull** [comment]
You need a more recent scalelite version that bundles the 2.3 player. If you have your own nginx infront of scalelite and not using the scalelite-nginx docker image, you can also just proxy requests to `/playback/...` to one of your newer BBB servers. That way clients will be able to load whatever player is installed on the BBB node but actual presentation data (`/presentation/...`) is still served from scalelite.

**Comment by parreitu** [comment]
Hi @pedrobmarin 

Thank you, you have given me the right hint (https://github.com/blindsidenetworks/scalelite/issues/405)

Until scalelite version 1.1, recordings made with BBB versions 2.3 were not supported.

To solve the problem I have done this:
- edit the scalelite-run/.env file and change the scalelite version to the current version (SCALELITE_TAG=v1.1.6).
- docker-compose down
- docker-compose up -d

Thank you very much !
