### ISSUE TITLE
RTL webcam floating in focus-on-video mode

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#12830]
**Describe the bug**

**To Reproduce**
1. Join a meeting
2. Switch the locale to a right-to-left one
3. Share webcam
4. Switch the layout from Smart to Focus-on-video

**Expected behavior**
The webcam should take large area, the presentation should be tucked in under the chat area

**Actual behavior**
The webcam and the presentation area overlap with a large empty area, see screenshot

**Screenshots**
![Screenshot from 2021-07-26 09-02-56](https://user-images.githubusercontent.com/6312397/126993485-9ae774cd-7135-4eda-9aa5-af748629722e.png)

**BBB version:**
BigBlueButton 2.4-alpha2

**Comment by Jossef-767** [comment]
it is not only the webcam, the screen direction is LTR and not RTL.
in  legacy mode it's the proper screen direction.

Incorrect:
![image](https://user-images.githubusercontent.com/2356928/127014988-d91b0994-c787-4632-acd5-e3183863d6d5.png)

Correct (legacy)
![image](https://user-images.githubusercontent.com/2356928/127015296-003cc6a6-c115-4466-8c44-25ff8d51056a.png)
