### ISSUE TITLE
BBB-Recording replay shows WHITE in the webcam area. (v2.3.8)

### ISSUE THREAD

**Issue by NthmAnTi** [bigbluebutton/bigbluebutton#12849]
**BigBlueButton Server 2.3.8 (2397)**

**Describe the bug**
Basically, when you recorded the session, you can see it is published when you clicked to replay slideshow replays with audio but the webcam area is **white**. I also imported my old recordings but they work fine.

**To Reproduce**
1. Record the session.
2. Click on the presentation button to replay the session.
3. If you check the webcam area it is white.
4. There should be webcam record but nothing.

**Expected behavior**
We should see the webcam recording.

**Actual behavior**
Just webcam area is WHITE. The rest is working fine.

**Screenshots**
![bbb_bug_report_1](https://user-images.githubusercontent.com/70592943/127318908-bd1612ee-5008-47a1-a802-aaa93e431b2b.png)

**Server**
 - OS: Ubuntu 18.04.5 LTS (64-bit)
 - Browser Chrome
 - Version 92.0.4515.107 (Offizieller Build) (64-Bit)
**BigBlueButton Server 2.3.8 (2397)**

**Additional context**
bbb-conf --check shows no error.
File permissions also checked.
bbb recording files have a symbolic link to /mnt/bbbrecordings so in this case we have a symbolic link between /var/bigbluebutton and /mnt/bbbrecordings/
bbb-conf --status shows everything OK.

**Comment by pedrobmarin** [comment]
The player only shows and sync data up. A white media is the default for the recorded webcams when there's no content to be composed at the recording processing stage. Can you verify if you have the webcam files at your recording raw folder?

**Comment by NthmAnTi** [comment]
On the path `/var/bigbluebutton/recording/raw`, I can see raw folders and when I looked video folder, I couldn't see any video :/

For example:
```bash
root@bbb-new:/var/bigbluebutton/recording/raw/43a079890ff95d1a2c95497ec5113227a8826fba-1627473094995/video/43a079890ff95d1a2c95497ec5113227a8826fba-1627473094995
```

Shows nothing. It is empty.

**Comment by NthmAnTi** [comment]
Eventually, I installed the latest release which is **BigBlueButton 2.4-alpha-2** and problem **gone**.

**Comment by prlanzarin** [comment]
> Eventually, I installed the latest release which is BigBlueButton 2.4-alpha-2 and problem gone.

No significant changes on how raw files are generated by the media servers (or how they're treated by the recording scripts) between 2.3 and 2.4.

I'd recommend checking your 2.3 setup if it's eventually needed. bigbluebutton-setup mailing list is also useful.
