### ISSUE TITLE
Video preview: review UI behavior on mobile

### ISSUE THREAD

**Issue by prlanzarin** [bigbluebutton/bigbluebutton#12840]
**Is your update request related to a problem? Please describe.**

The video preview UI on mobile devices can be improved.

Specially with the new virtual background thumbnails, the UI became problematic on mobile devices @ horizontal orientation. See screenshot down below.

**Describe the solution you'd like**

- [ ] Make the video preview modal "full screen" in mobile devices (like ie the chat panel, settings panel works)
- [ ] Figure out a way to improve the UI on horizontal orientation

**Additional context**

Mobile devices @ horizontal orientation: video preview overflows with a scroll
![image](https://user-images.githubusercontent.com/4529051/127170897-7c42d2c7-7bfc-4302-a243-7e843d2e5a12.png)

**Comment by iMonZ** [comment]
Picture in Picture support for example iOS Safari would be great!
So you can as example: Write a document and still see the screen sharing of the presentor.
This would be a huge productivity boost!
