### ISSUE TITLE
Redundant Japanese locale in 2.4

### ISSUE THREAD

**Issue by hiroshisuga** [bigbluebutton/bigbluebutton#12848]
**Describe the bug**
As already accepted for 2.3.x (see #10445), ja_JP can be removed from Transifex. It's effectively a duplicate of ja.

**To Reproduce**
1. Go to Transifex
2. for BBB 2.4, there are two Japanese locales, namely, ja and ja_JP, the latter has been already removed for BBB 2.3

**Comment by antobinary** [comment]
Just did it. Thanks!
Looks like the scripts I use import even deleted Transifex languages into a new project...
