### ISSUE TITLE
Changing the layout in bigbluebutton.properties is not working properly (2.4-alpha-2)

### ISSUE THREAD

**Issue by cod3r0k** [bigbluebutton/bigbluebutton#12858]
When you want to set a default `defaultMeetingLayout` parameter in `/usr/share/bbb-web/WEB-INF/classes`, you can't see anychanges.

**To Reproduce**
1. Go to '/usr/share/bbb-web/WEB-INF/classes'
2. edit bigbluebutton.properties file
3. Set `defaultMeetingLayout` to `LEGACY`
4. run `bbb-conf --clean`
5. check if your layout in such a session

**Comment by antobinary** [comment]
Hi @cod3r0k 

We are going to be deprecating "legacy" - we are keeping it around just until the 2.4 layout manager is super solid. Thus we are not using it as a valid `[default]meetingLayout` value.

**Comment by antobinary** [comment]
You are right though,

```
# Default Meeting Layout
# Valid values are LEGACY, CUSTOM_LAYOUT, SMART_LAYOUT, PRESENTATION_FOCUS, VIDEO_FOCUS
defaultMeetingLayout=SMART_LAYOUT
```

We need to remove it from this comment since it's not implemented to be set
