### ISSUE TITLE
Creating breakout rooms not working

### ISSUE THREAD

**Issue by thwien** [bigbluebutton/bigbluebutton#12860]
**Describe the bug**
Opening the dialog window via "Create breakout rooms". Selecting users clicking "Randomly assign" results in no effect. Selecting users per drag'n'drop is working. After clicking on "Create" breakout rooms will be created, but no selected users change automatically to the breakout rooms. Breakout rooms are shown with no users in it. Entering the breakout rooms manually is working.

No error logs found in browser or server. This issue refers to current Firefox and Chrome both on Linux and Windows. Also demo.bigbluebutton.org is not working and shows exactly the same behavior with BBB HTML5 client version 1813.

**To Reproduce**
Users -> Create breakout rooms -> Randomly assign -> Create

**Expected behavior**
Displayed users will be randomly assigned to all rooms. After creating the breakout rooms with manually selected users breakout rooms should be started with the selected users and users should be switched automatically to the breakout rooms.

**Actual behavior**
Nothing happens on clicking the button "Randomly assign". Creating the breakout rooms by clicking "Create" creates empty breakout rooms an no user is switched to the breakout rooms automatically.

**BBB version:**
BigBlueButton Server 2.3.8 (2397) (new installation with bbb-install.sh)
BBB HTML5 client version: 1813

**Desktop:**
 - OS: Windows, Linux
 - Browser:Firefox,Chrome (current versions)

**Comment by antobinary** [comment]
Hi @thwien 

Are all users in the meeting moderators by any chance? We only randomly assign viewers (attendees) but not moderators since they can visit any room any time.

**Comment by thwien** [comment]
Thanks a lot !!! In fact we tested the new BBB 2.3 version with moderators only to check all functions before setting this BBB node to public. In BBB 2.2 this test was working with moderators. We tested now the breakout rooms with one moderator an three viewers and it is working as expected. This issue can be closed.
