### ISSUE TITLE
Get google meet like layout on mobile

### ISSUE THREAD

**Issue by k1tzu** [bigbluebutton/bigbluebutton#12869]
Current BBB layout on mobile provides two webcams per screen is not comfortable to use on a group meeting.
And I've found the layout of google meet where you could observe 8 participants on the mobile at once much more useful.
Please consider the possibility to implement it.
Thank you
![image](https://user-images.githubusercontent.com/8276458/127654850-e05e916c-896c-4dcd-b23e-710aff508d48.png)

**Comment by prlanzarin** [comment]
> Current BBB layout on mobile provides two webcams per screen is not comfortable to use on a group meeting.

That's not an accurate reading at all.

The number of simultaneous cameras is _configurable_. The fact that _someone_ decided to set it to <magic number 2> in the server you're using does not mean it's bound to be two. Just need to alter the camera page size for mobile to 8. If you minimize presentation you'll get something closer to that.

I'm closing this :man_shrugging:

**Comment by k1tzu** [comment]
I've changed the settings for mobilePageSizes from 2 to 8. And got not the google meet layout at all. autoSwapLayout is set to true - but nothing helped. The layout wasn't able to auto-layout participants to fill the screen as they joined both on mobile and desktop. 
![IMG_8532](https://user-images.githubusercontent.com/8276458/128534876-e99a0f23-f4d6-420e-99d0-3fd2b8332aa3.jpg)
