### ISSUE TITLE
[2.3.9] Quick Poll regression

### ISSUE THREAD

**Issue by schrd** [bigbluebutton/bigbluebutton#12888]
**Describe the bug**
A presenter with role viewer (not moderator) starting a quick poll can't publish results and doesn't see live results.

**To Reproduce**
1. As a viewer open some slides which trigger the quick poll feature. You can use this document, page 2:
[Päsentationsdemo2.odp](https://github.com/bigbluebutton/bigbluebutton/files/6915969/Pasentationsdemo2.odp)
2. start quick poll
3. The polls panel opens but does not switch to live results. Other participants can answer the poll. The presenter sees the normal start poll widgets.
4. The presenter has no possibility to publish the results
5. promoting the presenter to moderator allows moderator to publish the results after closing and opening the polls panel

**Screenshots**

![Bildschirmfoto von 2021-08-02 11-38-04](https://user-images.githubusercontent.com/179952/127841630-bc8c5534-44ca-4a76-8556-947e78e1bd41.png)

**BBB version:**
2.3.9

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Firefox
 - Version 78 ESR

**Comment by ffdixon** [comment]
We just tested this on

 https://test.bigbluebutton.org/demo/demo2.jsp

which is running 2.3.9 and it did start the poll.


https://user-images.githubusercontent.com/290351/127855944-9d950694-0473-4484-8abd-82b2432694a6.mp4


Are you able to reproduce on the test server?

**Comment by antobinary** [comment]
I think the important difference is @schrd reported a **non-moderator** presenter [...]

Likely I broke this in - https://github.com/bigbluebutton/bigbluebutton/pull/12872 in 2.3.9... I did not think of that use case.

Tagging this for 2.3 to be fixed in upcoing 2.3.10. Thank you for reporting this @schrd

**Comment by ffdixon** [comment]
Nice catch Anton!
