### ISSUE TITLE
Closed captioning does not update when removing text

### ISSUE THREAD

**Issue by Peterburnett** [bigbluebutton/bigbluebutton#12886]
**Describe the bug**
If a CC writer makes a typo, which is sent through, then backspaces and corrects it, this is not sent through, instead the user will be shown the corrected text next to the previous text.

**To Reproduce**
1. Go to https://test.bigbluebutton.org/ and start a new test presentation.
2. Click on the cog menu and click 'Write closed captions'
3. Click the 'View closed captions' button in the main window and enable viewing.
4. In the close caption pad, write a few letters, backspace them, and write a few more.

**Expected behavior**
The incorrect letters would be cleared by the backspace action, while the rest off the line remained the same.

**Actual behavior**
The corrected input is displayed directly next to the end of the line, leading to garbled words if a writer backspaces at all during captioning.

**Screenshots**
![image](https://user-images.githubusercontent.com/21162968/127792598-3d48fdd8-e9df-4c7d-ba9c-78be828af95f.png)

**BBB version:**
Build 1820

**Desktop (please complete the following information):**
Any

**Smartphone (please complete the following information):**
Any

**Comment by jibon57** [comment]
This is expected. As soon you'll type something there it will broadcast instantly.

**Comment by zfgrnzfsberire** [comment]
This is not useful, people actively avoid the feature because this behavior is confusing.

**Comment by EmmyGraugans** [comment]
> This is expected. As soon you'll type something there it will broadcast instantly.

Yes, and it is also expected that a backspace will likewise be broadcasted instantly and applied in client-side. Worse: even a „select this word and overwrite it with something else“ should be broadcasted to the clients. (or actively prevented in the editing-window)

**Comment by pedrobmarin** [comment]
Fixed in #13916

**Comment by Merotix** [comment]
Please note, that the usual behavior of a professional speech-to-text translator's workplace keeps an entry line editable with immediate updates until the <enter> key is pressed (which adds a newline to closed captions). I also mention that these professionals typically use 3rd party shortcut tools (e.g. [TextExpander](https://textexpander.com/) to keep on realtime typing contstraints while subtiteling.
