### ISSUE TITLE
Media stack: add mediasoup adapter

### ISSUE THREAD

**Issue by prlanzarin** [bigbluebutton/bigbluebutton#12894]
**Is your feature request related to a problem? Please describe.**

We need a baseline adapter with which we can do some testing and field trials with mediasoup.
This issue is expected to touch only bbb-webrtc-sfu and land on sfu@2.6, but better to track it here.

**Describe the solution you'd like**

  - [x] Implement a MVP of a mediasoup adapter built in bbb-webrtc-sfu
  - [x] Make it configurable, meaning: optional dependencies, its usage configurable via config files and API (meeting wide) as well, if possible
  - Capabilities:
    * [x] Cameras
    * [x] Listen only
    * [x] Screen sharing
    * [x] Screen sharing + audio
    * [x] Recording
       - I still don't consider this to be in an ideal state since mediasoup's default recording mode in our adapter uses Kurento as a walking cane. **It's pretty stable as is**, though, so it's good as a temporary measure;
       - There is an option to use ffmpeg for recording, but I consider that to be still unstable/being worked on and is most likely to be the default in 2.5+.
    
 **Additional information**
 
 Current SFU branch: development
 Current SFU release branch: v2.6.x-release
 BBB branches: 2.4.x-release, develop
 
 How to set it up:
 https://github.com/bigbluebutton/bbb-webrtc-sfu/wiki/Back-of-the-envelope-calculations:-mediasoup

**Comment by jibon57** [comment]
Thank you @prlanzarin. I missed that wiki. After following step 7 it's working as expected!! Excellent job!!

**Comment by prlanzarin** [comment]
This has been addressed in https://github.com/bigbluebutton/bbb-webrtc-sfu/releases/tag/v2.6.0.

Documentation on how to set it up: https://github.com/bigbluebutton/bbb-webrtc-sfu/wiki/Back-of-the-envelope-calculations:-mediasoup (if someone wants to move that to the official docs, be my guest).

Documentation on mediasoup-specific Prometheus metrics can be found in: https://github.com/bigbluebutton/bbb-webrtc-sfu/blob/development/docs/metrics.md#adapter-mediasoup

### Post-mortem

- The adapter is feature complete as far as what was proposed here is concerned;
- The adapter is fairly stable == it's safe to field trial, but it has not seen production usage as extensively as Kurento's adapter has seen;
- The status of the adapter is still to be considered **EXPERIMENTAL** _as far as I'm concerned_. That will only change (_as far as I'm concerned x2_) when Kurento is phased out as the default adapter.


### What's next

The two pending, shorter term major tasks/issues related to mediasoup's adapter are:
  - [ ] Recording: it's pretty stable with the _default configuration_. The caveat: I still don't consider this to be in an ideal state since mediasoup's default recording mode in our adapter uses Kurento as a walking cane. A Kurento-less, production grade recording adapter is being worked on and the target is BBB 2.5;
  - [ ] Firefox doesn't always play nice with mediasoup. The latter is ICE-lite only, which implies, by RFC, that the browser _must_  use regular nomination when running ICE. [Firefox doesn't do that and sticks to aggressive nomination](https://bugzilla.mozilla.org/show_bug.cgi?id=1034964), which can be spotty with ICE-lite peers (mediasoup) if the client's network topology is complex enough/meets the right conditions. A few options:
     * **The short-term countermeasure**: we need to add a client-side flag that allows forcing relay-only peer negotiations in Firefox;
     * **The medium-term-that-sucks-countermeasure**: adding a flag in mediasoup that allows ignoring aggressive nomination's trigger happy usage of the USE-CANDIDATE field in binding requests + coupling the server-side ICE state machine to the RTP packet flow when that flag is enabled (so we can get ICE to `completed` even when ignoring USE-CANDIDATE). This sounds like it would work and I prototyped it. There's no guarantee it'll always work. Finally, I have a passionate aversion to this option;
     * **The ideal countermeasure**: working with Mozilla folks to try and patch `nICEr` to use regular nomination with `ice-lite` peers as stated by the standards.
     
I'll now shift focus to the client-side part of the WebRTC stack. Lots of things need to be re-written there and we're underusing mediasoup's capabilities because our client stuff still has to catch up with mediasoup. I've documented a few of those tasks in this repo's `Media stack` project. 

What I have not mapped into issues yet can be found in [BBB World's media stack presentation](https://www.youtube.com/watch?v=SBO5iWLs0KE). The plan that outlines where the WebRTC stack is headed  for **video and audio** is explained there by yours truly.
