### ISSUE TITLE
[2.3.9] Accessing breakout rooms isn't possible when users are allowed to choose the room

### ISSUE THREAD

**Issue by antwertinger** [bigbluebutton/bigbluebutton#12901]
**Describe the bug**
Since version 2.3.9 users will only see a blue background when they choose a breakout room for joining.
The following javascript error occurs:
TypeError: can't access property "find", n.users is undefined

**To Reproduce**
1. Moderator create breakout rooms and check the checkbox "Allow users to choose a breakout room to join"
2. User choose a room for joining

**Expected behavior**
Joining the breakout room

**Actual behavior**
Joining is not possible, javascript error occurs.

**Screenshots**
<img width="1673" alt="Bildschirmfoto 2021-08-04 um 11 26 49" src="https://user-images.githubusercontent.com/576402/128157727-325ad364-a84e-43a5-8161-8bd083cf3484.png">

**BBB version:**
BigBlueButton Server 2.3.9 (2421)

**Additional context**
The bug exists since version 2.3.9 and might be caused by this commit https://github.com/bigbluebutton/bigbluebutton/commit/aa0ea219907417e68af2631a4eeb56c6d986905c

**Comment by ffdixon** [comment]
Thanks for finding this issue -- confirmed it is in 2.3.9.

**Comment by danimo** [comment]
What was the last known version? 2.3.7 or 2.3.8?

**Comment by antobinary** [comment]
Before 2.3.9 we had 2.3.8 https://github.com/bigbluebutton/bigbluebutton/releases

**Comment by danimo** [comment]
Sorry, this meant to say "last known GOOD version"? (asking for a temp. rollback).

**Comment by danimo** [comment]
We did some testing: Breakout rooms work if you allow users to assign themselves. I therefore supect that aa0ea219907417e68af2631a4eeb56c6d986905c is bad. It introduces a filter by userId, which might not be available in the auto-assign case. Note this is only a hypothesis, I have not yet tried to roll back the change.

**Comment by danimo** [comment]
Rolling back `aa0ea21` indeed seems to help (with the obvious drawbacks of loosing the added protection).

**Comment by crosscodr** [comment]
The problem still exists in 2.3.10.
After choosing a breakout room from the drop-down-menu as normal user and press the button to join, the result is an empty blank page.
However, back in the main room, one can successfully join a breakout-room by going to Breakout-rooms in the left panel.

**Comment by antobinary** [comment]
Thanks @crosscodr !
@antonbsa was able to reproduce this variation here too and opened https://github.com/bigbluebutton/bigbluebutton/issues/12923 to track it.
