### ISSUE TITLE
Audio Device Selection Popup not Intuitive

### ISSUE THREAD

**Issue by danimo** [bigbluebutton/bigbluebutton#12914]
**Describe the bug**

In 2.4, the audio device can be picked through a dropdown sub-button on the "Leave audio" button. This means a *less destructive action* is layered on top of a *more destructive action* which is easy to hit by mistake. As a consequence, such a mis-click will mean missing out on the conversation for a couple of seconds until the user realizes their mistake, re-enters and re-gains audio.

This is how the buttons look now:

![image](https://user-images.githubusercontent.com/1315934/128328207-96414edb-f2f4-498f-8b80-1493d545a6f4.png)

Me (and a couple of others who have independenly voiced this after testing 2.4) would find it more intuitive to find the option with the "mute" button (which has a microphone, which is what you are going to pick, mostly).

On top, on the mobile UI, the popup-button does not show at all. Jitsi's mobile UI shows it as a separate action in a vertically dotted menu, which seems a fitting place for an option needed only sometimes given the space constraint on a mobile UI. This may be the topic of another ticket though as no such menu exists today and we may need a different solution here. Having no option at all to switch seems like a bug though.

**Expected behavior**

Audio device popup button is on the Mute button.

**Actual behavior**

Audio device popup button is on the "Leave Audio" button.

**BBB version:**
BigBlueButton Server 2.4-beta-1 (1495)

**Desktop (please complete the following information):**
 - OS: [Linux, Mac]
 - Browser [Chrome, Safari, Firefox]

**Smartphone (please complete the following information):**
 - Device: [Pixel 4a]
 - OS: [Android 11]
 - Browser [Brave, Chrome]
 - Version [latest]

**Comment by mariogasparoni** [comment]
Thanks, @danimo.

We disabled it by default in mobile , to avoid a bad user experience. It is quite easy to make this an option, though.

About rendering the selector over the mute button , that's a good point but we ended up by placing it over the "Leave audio" button because mute button is used more often, which means a higher chance of doing a wrong click. Changing this in your custom branch shouldn't be hard (ping me if you need help)

**Comment by hiroshisuga** [comment]
#11614 may help a bit.

**Comment by tylercopeland** [comment]
@danimo, thank you for sharing this feedback. I've gone ahead and have taken your feedback and built out the appropriate designs.

**Leave audio** - incorporated into the audio/speaker selector experience. 
![Screen Shot 2021-08-22 at 9 59 02 PM](https://user-images.githubusercontent.com/1273169/130379899-52531159-272c-430e-a164-8630add741ff.png)

**Presenter Experinece**

![html5-leave-audio-1](https://user-images.githubusercontent.com/1273169/130379985-0b915593-7cda-4c0b-9dbd-9c8755b47e75.png)

**Participant Joined With Audio**

![html5-leave-audio-2](https://user-images.githubusercontent.com/1273169/130379994-c6053124-0c36-46f9-9875-036dc5f83e7d.png)

**Participant Joined Listen Only**

![html5-leave-audio-3](https://user-images.githubusercontent.com/1273169/130380052-77e7cd09-ef7f-4b8a-86d7-2b250686faa7.png)
