### ISSUE TITLE
bbb_install.sh 2.3 and 2.4 failed for me due to letsencrypt in a lxc-based ubuntu 18.04 vm for testing

### ISSUE THREAD

**Issue by xavidp** [bigbluebutton/bigbluebutton#12920]
Hi:

I'm happily using bbb 2.2 in a vm on a ssd-based dedicated server of my own. so far so good (for more than a year already), also with audio and video in recording being synchronized (that was an issue before using ssd-based disks in the server hosting the vm where I installed bbb).

I wanted to test bbb 2.4 and/or 2.3, to see whether I would have any issue when I want to upgrade my bbb install (migrating recordings over to a new vm installed from scratch with ubuntu 18.04 64b as OS, etc)

I failed in my both attempts. And I'm not sure why. This time I was using linux container (lxc) for the new virtual machine within my ssd-disks dedicated server. Made the new vm with a 18.04.1 template for linux container (using Proxmox 6.x on the host, like in the case of the kvm-based vm where I have bbb 2.2 running without issues for more than one year).

Once the vm is up, I update it (apt update & apt dist-upgrade), ensure system locale is as expected (according to the bbb documentation). I added the apt key for bbb ubuntu repos (otherwise the install script failed for me, and I had to install the key and start again).

Then I fire as root the bbb_install.sh script with the proposed syntax in the bbb documentation. And the script fails and stops at the step when attempting to setup the letsencrypt cert. It does fail to place the html file in nginx, apparently, and letsencrypt part of the bbb_install.sh script make the process to stop, complaining as if the domain was not properly set (and it was working for me; I had set it up something like 45' minutes before hand, and pinging it from my desktop at home replied properly, etc. But I confirm the html file that letscrupt attemps to place under the web server is not under the web server folder. 

Could this be related to the fact that I was using some (unprivileged) linux container as the base for my virtual machine?

(I don't seem to be able to use kvm based virtual machines with ubuntu 18.04 any more - like what I did with ubuntu 16.04 and bbb 2.2 to have it working nicely in a vm -  under that proxmox-based server, since the networking system in ubuntu 18.04 changed from using ifupdown to using netplan, and the former config doesn't work for me)

So, is using linux containers (lxc) an option to setup some debug/test/low traffic vm to test bbb 2.3/2.4? Or using lxc is a no-go for testing bbb?

Thanks in advanced Fred and team!

Xavi (aka xavidp in github/gitlab, and xavi @ tiki.org )

**Comment by aguerson** [comment]
with Openvz I had a dependancy problem with java. 

java from ibm is selected.. But it seems ok when I installed the good java and then I selected the good one via the alternative command.

I installed a fresh ubuntu 18.04 server on kvm. You just to deal with cloud-init and subiquity. But it is OK.
I already give my feedback here : https://github.com/bigbluebutton/bigbluebutton/issues/12913

**Comment by EmmyGraugans** [comment]
> Could this be related to the fact that I was using some (unprivileged) linux container as the base for my virtual machine?

Possibly. We use privileged lxc and it works (both on Ubuntu 18.04 host and on Debian Bullseye host). We use some preparing-steps before we fire the bbb-install.sh:

```
DOMAIN=.my.example.com
EMAIL=email@my.example.com

cat - > /etc/apt/preferences.d/block-apparmor <<EOF
Package: apparmor
Pin: release *
Pin-Priority: -1
EOF

apt-get install -y fail2ban man-db rsync
apt-get install -y wget net-tools dirmngr
apt-get install -y nginx certbot ufw
sed -i '/^IPV6=/s/yes/no/' /etc/default/ufw
systemctl restart ufw

sed -ri "s/($(hostname))/&$DOMAIN   \1/" /etc/hosts

## symlink, to let letsencrypt run before installing BBB, and still valid after: 
mkdir -p /var/www/bigbluebutton-default/
ln -s /var/www/bigbluebutton-default/.well-known /var/www/html/
certbot --email $EMAIL --agree-tos --rsa-key-size 4096 -w /var/www/bigbluebutton-default -d $(hostname -f) --deploy-hook "systemctl reload nginx" --webroot --non-interactive certonly
```
At that point it might be useful to take a snapshot before doing the big run:

`wget -qO- https://ubuntu.bigbluebutton.org/bbb-install.sh | bash -s -- -v bionic-230 -w -s $(hostname -f) -d`

**Comment by xavidp** [comment]
Thanks!

I tried with the unprivileged container, with your recipe, @EmmyGraugans , and I could continue the process after the letsencrypt cert. But I did hit a problem lacking permissions at the step to install/configure the docker for libreoffice.

```
(...)
Step 3/6 : RUN echo "deb http://deb.debian.org/debian buster-backports main" >> /etc/apt/sources.list
 ---> Running in 2cf98df9f96a
OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: rootfs_linux.go:76: mounting "proc" to rootfs at "/proc" caused: mount through procfd: permission denied: unknown
dpkg: error processing package bbb-libreoffice-docker (--configure):
 installed bbb-libreoffice-docker package post-installation script subprocess returned error exit status 1
dpkg: dependency problems prevent configuration of bbb-web:
(...)

```
I started over with a privileged lxc, and then I could continue little furhter, but not much: the install of the docker for libreoffice failed also, but not about perms this time, but because it was inside a container?

```
(...)
Step 3/6 : RUN echo "deb http://deb.debian.org/debian buster-backports main" >> /etc/apt/sources.list
 ---> Running in a9814fcc342f
AppArmor enabled on system but the docker-default profile could not be loaded: running `/sbin/apparmor_parser apparmor_parser -Kr /var/lib/docker/tmp/docker-default917960506` failed with output: apparmor_parser: Unable to replace "docker-default".  Permission denied; attempted to load a profile while confined?

error: exit status 243
dpkg: error processing package bbb-libreoffice-docker (--configure):
 installed bbb-libreoffice-docker package post-installation script subprocess returned error exit status 1
(...)

```

Oh well, In the meantime, I have been provided today a tweaked recipe to setup a vm with kvm and get the networking up & running again with netplan in my proxmox6-based dedicated server. Therefore I've been able to continue playing with the kvm-based vm with ubuntu 18.04, and then I could fire the whole bbb_install.sh script for bbb 2.4 until the end, producing a working installation of the 2.4-beta1 : wohooo! :-)

**Congrats again Fred & Team, and thanks for the feedback @aguerson and @EmmyGraugans here.**

**Comment by ffdixon** [comment]
@xavidp Glad to hear you got it working!
