### ISSUE TITLE
[2.3.10] - Trying to join in a breakout room but being redirected to a blank tab

### ISSUE THREAD

**Issue by antonbsa** [bigbluebutton/bigbluebutton#12923]
**Describe the bug**
After a moderator create the breakout rooms - with the option to allow users to choose them enabled - the normal user (attendee) is being redirected to a blank tab if choosing a room other than the pre-selected.

**To Reproduce**
1. Join in a meeting with a moderator and a attendee;
2. Create the breakout rooms and allow users to choose them;
3. As the attendee, try to join in a room other than the pre-selected;

**Video**

https://user-images.githubusercontent.com/56703993/128414319-7ffba030-ddcc-4a2e-8320-042fa183d781.mp4

___
**Screenshots**

log in attendee tab after click to join in the room:
![image](https://user-images.githubusercontent.com/56703993/128410842-94fc5829-c5d3-4b0f-83c9-9989c0990afc.png)

**Comment by antobinary** [comment]
Fixed by https://github.com/bigbluebutton/bigbluebutton/pull/12955
