### ISSUE TITLE
BBB2.4-beta2 - Dashboard - Dial In Participants not listed

### ISSUE THREAD

**Issue by martin-77** [bigbluebutton/bigbluebutton#12936]
**Is your feature request related to a problem? Please describe.**

When using the Dial-In Function in a conference, the participants are not listed in the Learning-Dashboad. 

**Describe the solution you'd like**

Would be nice, to see the Phone-number and the Talk-Time in the Dashboard

Overall: the new Dashboard function is a wonderfull improvement and I am very thankfull for all the time you invested in BBB-project.

**Comment by martin-77** [comment]
same behavior on 2.4-beta3

**Comment by hostbbb** [comment]
Neat, does the dashboard show the telephone number that appears in the user window of meeting to be able to identify the actual caller from another user...  like  207-555-2222, or if in dialplan we mask the number xxx-xxx-2222?

**Comment by gustavotrott** [comment]
> Neat, does the dashboard show the telephone number that appears in the user window of meeting to be able to identify the actual caller from another user... like 207-555-2222, or if in dialplan we mask the number xxx-xxx-2222?

The same name of the meeting users list is being used in the Dashboard!
