### ISSUE TITLE
BBB2.4-beta5 - own Background-Images

### ISSUE THREAD

**Issue by martin-77** [bigbluebutton/bigbluebutton#12937]
**Is your feature request related to a problem? Please describe.**
With the latest 2.4 Beta-Release, we can choose between 4 different backgrounds. 

**Describe the solution you'd like**
It would be nice, to use our own backgrounds. Tried to copy a jpg into /usr/share/meteor/bundle/programs/web.browser/app/resources/images/virtual-backgrounds and /usr/share/meteor/bundle/programs/web.browser.legacy/app/resources/images/virtual-backgrounds/ and edited /usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml but did not have any success.
Maybe the idea was stupid, or I did it the wrong way, but on this way, it did not work. Images were scaled at 1920x1080 with a resolution of 300dpi.

Thanks in advance

Martin

**Comment by markginter31** [comment]
I think you need an equivalent image file with the same name in the thumbnails directory.... I could get something to appear in the list, but I didn't spend enough time formatting the image.  I could choose the custom image but it would lock the camera.  I'd have to cancel the camera choice dialog and open it back up.

**Comment by martin-77** [comment]
Thanks for your answer. Thumnail was generated, but without any success.
And as I wrote, by editing the settings.yml, I was able to use my own Filenames, so, I do not thinks, that this is related to the image or the scaling. (If i do remember correctly, thumbnails are 50x50 at 100???dpi). 
But anything I tried was - as I said - without any success.
I was able to disable a background by # the line in the setting.yml file. 
I could imagine, that there is another folder or setting to use own backgrounds.

**Comment by markginter31** [comment]
And you restarted bbb (bbb-conf --restart) ?

**Comment by martin-77** [comment]
yes. and to be sure I restarted the server. Maybe someone else will find the solution... for now, I am out of ideas...

**Comment by ArminXG** [comment]
You also need to add the jpg file and its thumbnail file to
/usr/share/meteor/bundle/programs/web.browser/program.json

regards
Armin

**Comment by martin-77** [comment]
Thanks - this was the missing information.
Would be nice, if bbb would offer an easier way - and for future releases: must have in the documentation

Thanks again!

> 
> 
> You also need to add the jpg file and its thumbnail file to
> /usr/share/meteor/bundle/programs/web.browser/program.json
> 
> regards
> Armin

Thanks - this was the missing information.
Would be nice, if bbb would offer an easier way - and for future releases: must have in the documentation

Thanks again!

**Comment by martin-77** [comment]
> 
> 
> You also need to add the jpg file and its thumbnail file to
> /usr/share/meteor/bundle/programs/web.browser/program.json
> 
> regards
> Armin

Thanks - this was the missing information.
Would be nice, if bbb would offer an easier way - and for future releases: must have in the documentation

Thanks again!

**Comment by martin-77** [comment]
Updated to the latestest release - own background has to be implemented again - program.json is changed

**Comment by aguerson** [comment]
```
{
      "path": "app/resources/images/virtual-backgrounds/coffeeshop.jpg",
      "where": "client",
      "type": "asset",
      "cacheable": false,
      "url": "/resources/images/virtual-backgrounds/coffeeshop.jpg",
      "size": 446038,
      "hash": "7ce79ccdcafe45cf0c833991207be529d5d7584a",
      "sri": null
    }
```

How to find the hash ?

```
md5sum coffeeshop.jpg
027f5b0d39a971fac5caf602e9285c66  coffeeshop.jpg

sha1sum coffeeshop.jpg
096d56fed3f7d7b663841121a75d113adc88407e  coffeeshop.jpg

sha256sum coffeeshop.jpg
4e2f3a28051ce16f070bc521ca657831ed6f881b752dfb464742c36a3684e6fc  coffeeshop.jpg
```
Regards,
Aurelien

**Comment by aguerson** [comment]
Is there a salt in the hash ?

**Comment by schrd** [comment]
changing `program.json` should not be required anymore. See the documentation: https://docs.bigbluebutton.org/admin/customize.html#use-custom-images-for-virtual-background

**Comment by JoVictorNunes** [comment]
@schrd This documentation will change soon.

**Comment by martin-77** [comment]
good job! had to create the file, put in the corresponding filenames - works!
If the file survives the next update, I think this can be closed.

**Comment by kaystrobach** [comment]
Is it planned to allow user uploads? Or setting images via the api?

**Comment by antobinary** [comment]
> Is it planned to allow user uploads?

I would not expect to see this functionality. Essentially it allows any [student] to upload visible images at any time and that can go south pretty quickly...

>  Or setting images via the api?

If you are looking for api setting image viewable in the webcam space, you may want to check the `avatarURL` join parameter. There are some ideas to display the avatar as a placeholder if no webcam stream is found. The implementation of these ideas are not for the immediate future though.

**Comment by kaystrobach** [comment]
> > Is it planned to allow user uploads?
> 
> I would not expect to see this functionality. Essentially it allows any [student] to upload visible images at any time and that can go south pretty quickly...

I thought about an image, that can be used by just that one student at a time.
With SnapCam, OBS and other tools, i can have any (also weird) background as well ... this is no argument imho

> > Or setting images via the api?
> 
> If you are looking for api setting image viewable in the webcam space, you may want to check the `avatarURL` join parameter. There are some ideas to display the avatar as a placeholder if no webcam stream is found. The implementation of these ideas are not for the immediate future though.

Same as above, this would allow to provide company backgrounds or similar stuff per user from the API user (greenlight) or any other integration.

**Comment by kaystrobach** [comment]
Another use case would be, that a moderator can pre upload the same image in greenlight for all meetings and use it in the meeting room.

**Comment by ArminXG** [comment]
Isn't the image needed on the client (browser is doing the virtual background)? 
An upload wouldn't be neccessary, the client just choose the image from local storage.

**Comment by kaystrobach** [comment]
i think so - the processing is done locally, if lateron this needs to happen on the remote site an upload would be needed.

**Comment by ArminXG** [comment]
If the image is needed locally only and no upload to the server needs to be done, it should be easy to allow the client/user to use an own image.

What could be the reason to have the processing on the remote site? Isn't it better to let the client do whatever possible?

**Comment by kaystrobach** [comment]
Agree - but some clients have hardly the processing power to render 1 or 2 video streams.

So a fat client should do whatever is possible on the client side.
A thin client should have the option to move the processing to the server - but that's another thing and not related to this ticket.

**Comment by pya** [comment]
# Hover Text

This description works for me:
https://docs.bigbluebutton.org/admin/customize.html#use-custom-images-for-virtual-background

However the hover text for a new background is "Background 2". Is there a way to customize this text?

I found the text for default backgrounds here:

     /usr/share/meteor/bundle/programs/web.browser/app/locales/en.json
    "app.video.virtualBackground.coffeeshop": "Coffeeshop",

And, since I am also interested in German as user interface language, also here:
    
    /usr/share/meteor/bundle/programs/web.browser/app/locales/de.json
     "app.video.virtualBackground.coffeeshop": "Café",

Can I add a display text for may background in ` /etc/bigbluebutton/bbb-html5.yml` or somewhere else?

**Comment by EmmyGraugans** [comment]
> Can I add a display text for my background in ` /etc/bigbluebutton/bbb-html5.yml` or somewhere else?

My guess is, "somewhere else", at least the following works (for a file named "basename.jpg" depicting a kitchen):

```
LOCALE_DE="/usr/share/meteor/bundle/programs/web.browser/app/locales/de.json"
LOCALE_EN="/usr/share/meteor/bundle/programs/web.browser/app/locales/en.json"

yq -jP w -i $LOCALE_EN '"app.video.virtualBackground.basename"' "My kitchen"
yq -jP w -i $LOCALE_DE '"app.video.virtualBackground.basename"' "Meine Küche"
```

I had to empty the cache of my browser before it was picked up though. Probably/Possibly it would have worked without that, had I edited the file `/usr/share/meteor/bundle/programs/web.browser/program.json` properly and updated the SHA1 for the modified json-files.

**Comment by antobinary** [comment]
> changing `program.json` should not be required anymore. See the documentation: https://docs.bigbluebutton.org/admin/customize.html#use-custom-images-for-virtual-background

I think this is as far as we'll go in BBB 2.4. Thank you, @schrd !

**Comment by antobinary** [comment]
This issue splits into three:

1) deploying own images on server side, please follow  https://github.com/bigbluebutton/bigbluebutton/issues/12937#issuecomment-1018548924

2) Setting images via the api -- follow
https://github.com/bigbluebutton/bigbluebutton/issues/14179

3) User uploads own background [on join/during the live meeting] (which by now has been requested a few times and it warrants a new issue) https://github.com/bigbluebutton/bigbluebutton/issues/14249
