### ISSUE TITLE
2.4-b2 "focus on video" mode does not work correctly

### ISSUE THREAD

**Issue by nikkei00** [bigbluebutton/bigbluebutton#12939]
**Describe the bug**
"focus on video" mode does not work correctly

**To Reproduce**
1. Go to test24.bigbluebutton.org
2. Set layout type  "focus on video"
![image](https://user-images.githubusercontent.com/64165027/128640541-c92970b8-0bbb-45cc-9a4f-536604d4c6c8.png)

**Comment by antobinary** [comment]
Thanks @nikkei00 for reporting this and other cases that need more attention!!
