### ISSUE TITLE
Download Recording

### ISSUE THREAD

**Issue by voltan** [bigbluebutton/bigbluebutton#12935]
Hello

Does BBB have an option or web service for download recordings as mp4?

**Comment by hiroshisuga** [comment]
Officially not, but there are a couple of solutions proposed. Among these, 
https://github.com/danielpetri1/bbb-recording-exporter
is the best one in my personal opinion.

**Comment by antobinary** [comment]
Link to the pull request: https://github.com/bigbluebutton/bigbluebutton/pull/12533 from the same author

**Comment by hiroshisuga** [comment]
And it's a duplicate of #1969, which has been duplicated many times already...

**Comment by voltan** [comment]
Thank you very much& I will text it
