### ISSUE TITLE
Auto Layout wrong for 8 participants both on mobile and desktop

### ISSUE THREAD

**Issue by k1tzu** [bigbluebutton/bigbluebutton#12947]
**Describe the bug**
The layout don't auto-layout participants webcams to fill the entire screen as they joined both on mobile and desktop. 

**To Reproduce**
1. Go to bigbluebutton-html5/private/config/settings.yml 
2. set mobilePageSizes: viewer from default 2 to 8
3. set autoSwapLayout true
4. set hidePresentation: true
4. get a conference call with 5+ people
5. Observe empty spaces
![IMG_8532](https://user-images.githubusercontent.com/8276458/128703029-b80db7a6-a6ed-4878-9167-400ae24dc2e3.jpg)

**Expected behavior**
I expect user webcams to fill as much of the screen as possible like can be experienced with google meet
<img width="155" alt="xccc" src="https://user-images.githubusercontent.com/8276458/128703315-b2826173-8087-42ff-9a82-72d3309c1d56.png">

**Actual behavior**
Instead of it I experienced a lot of empty spaces and lack of auto-filling and re-layout of user webcams as they joining-leaving.

**BBB version:**
BigBlueButton Server 2.3.10 (2438)

**Desktop (please complete the following information):**
 - OS: MacOs
 - Browser Chrome

**Smartphone (please complete the following information):**
 - Device:  iPhone X
 - Browser Safari

**Comment by hostbbb** [comment]
you should look at 2.4 beta2,  a new layout manager is being developed, and comment on its progress here..  2.3 is no longer actively developed.

**Comment by k1tzu** [comment]
> you should look at 2.4 beta2, a new layout manager is being developed, and comment on its progress here.. 2.3 is no longer actively developed.

bigbluebutton-html5 is from git, last commit 493a47e55e38eb912f80a07b8a011a1673041b42 "Thu Aug 5 09:31:26 2021"
Or layout somehow depends on the backend?
