### ISSUE TITLE
2.4-beta2: Inconsistent Camera Interface with only one camera

### ISSUE THREAD

**Issue by danimo** [bigbluebutton/bigbluebutton#12945]
**Describe the bug**
With only one camera, clicking the camera icon, skipping the camera selection dialog. After unshare, a second sharing attempt (i.e. clicking the icon for the third time) will bring up the dialog. This is a bug because only the dialog grants access to camera blur and backgrounds, which defeats the purpose of the feature (privacy).

**To Reproduce**
**Precondition:** Machine must only have one camera
1. Click Camera Icon. Sharing starts instantly
2. Click Camera Icon again. Sharing stops
3. Click Camera Icon again, dialog comes up.

**Expected behavior**

**Actual behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [Mac, Linux]
 - Browser [Chrome, Chromium]
 - Version [e.g. 29]

**Additional context**
I think the whole concept of the camera dialog with multiple cameras and background blurring needs a visual clean up. It is hard to understand as is, especially compared to Jitsi and others. But this is probably something for 2.5 given we are already in Beta.

**Comment by prlanzarin** [comment]
See https://github.com/bigbluebutton/bigbluebutton/issues/12836 which expands on unifying the single vs multiple camera experience in 2.4.
