### ISSUE TITLE
Audio channel is completely empty, when speaker voice is very low

### ISSUE THREAD

**Issue by sumeshiit** [bigbluebutton/bigbluebutton#12946]
**Describe the bug**
we observed a complete silence (not even a background sound) in the recording, when the presenter volume is low. Is there any optimization is enabled in bigbluebutton, to remove audio, when input volume is low?.

**To Reproduce**
1. Start a meeting with bigbluebutton (2.3,bionic-23)
2. Start recording and speak some sentences, please speak in low volume for some seconds OR please give 'pause' , while speaking.
3. end the meeting and wait for the link to play
4. open the link and play the recording, we observed complete silence (not even a background sound) in the recording, when the speaker volume is low. (This issue happens only in the some part of presentation, where the presenter volume is low, audio is good in the remaining part of the recording).

**Expected behavior**
Recording should contain some audio, even if the presenter volume is low.

**Actual behavior**
Recording don't have any audio, if the presenter volume is low.

**Desktop (please complete the following information):**
 - OS: Debian Linux
 - Browser Firefox
 - Version BigBlueButton 2.3

**Additional context**

**Comment by hostbbb** [comment]
freeswitch mod_conference has a setting in profile, to trigger the "energy level" if that level is not reached, no audio from that user is mixed.   if you set this level to 0,  everyones mic is always sent into the mixer...

look in /opt/freeswitch/conf/autoload_configs/ for the conference.xml file and change energy to 0 in the cdquality profile, and restart and test to see if you get the results you want.

**Comment by sumeshiit** [comment]
Thanks it working now.
