### ISSUE TITLE
Install previous releases (2.2.36)

### ISSUE THREAD

**Issue by amirhnader** [bigbluebutton/bigbluebutton#12965]
Hi ,
Can I install BBB 2.2.36 by bbb-install.sh script instead 2.3.x  ?
if so, please send the command.
thanks 
Amir

**Comment by prlanzarin** [comment]
https://bigbluebutton.org/community-support/

Github issues are not the appropriate place for this.

**Comment by ffdixon** [comment]
We would strongly recommend you move to 2.3.x as 2.2 is on Ubuntu 16.04 which is EOL.
