### ISSUE TITLE
Specific attached vectorized pdf hang the bbb demo 

### ISSUE THREAD

**Issue by cgt-training2** [bigbluebutton/bigbluebutton#12960]
[Brazilian-Real-Book.pdf](https://github.com/bigbluebutton/bigbluebutton/files/6960102/Brazilian-Real-Book.pdf)

**Describe the bug**
When i upload the attached PDF([Brazilian-Real-Book.pdf](https://github.com/bigbluebutton/bigbluebutton/files/6960102/Brazilian-Real-Book.pdf)) which is vectorized pdf the bigbluebutton  hangs noticeably. After uploading the attached pdf it converts successfully but after the conversion when i draw any annotation using pencil or triangle then the specified annotation reflecting very late.

Please check with the attached PDF and help me out with this issue because i always use this kind of pdf's. This is urgent please revert back asap.

**To Reproduce**
1. Go to demo page of bbb
2. Click on + icon and click manage presentation.
3. download linked pdf to your system and upload to bbb demo then try to draw anything on the pages.
4. error can be seen it won't allow you to reflect the drawing with your action the drawing reflects after some time and also the complete site gets hanged the click event also don't reflect properly.

**Expected behavior**
Drawing of pencil should reflect when move my mouse with pencil and system doesn't hangs & user should be able to click on any event to get results quickly.

**Actual behavior**
Drawing reflecting very late and system doesn't responding as expected even on mouse click on + icon given at bottom.

**Screenshots**
Not applicable

**BBB version:**
Please check on BBB demo page i also checked it there.

**Desktop (please complete the following information):**
 - OS: Ubuntu/MAC
 - Browser: Chrome
 - Version: Demo BBB current version and also on BBB 2.2.20 

**Additional context**
This problem occurs when you upload the attached pdf which is vectorized PDF. Also provide solution for the bbb 2.2.20 version if possible.

**Comment by jibon57** [comment]
I'm confirming this problem. Looks like during pdf to svg conversion something went wrong. The actual svg was generated like the attached but those aren't same as pdf.

[svg_files.zip](https://github.com/bigbluebutton/bigbluebutton/files/6960751/svg_files.zip)

**Comment by jibon57** [comment]
Found the problem. Looks like converting that pdf with `pdftocairo (poppler)` didn't give correct output. I've tried with [inkscape](https://inkscape.org/release/inkscape-1.1/gnulinux/ubuntu/ppa/dl/) & found it working fine.

**Comment by cgt-training2** [comment]
@jibon57 ,
Thank you for the response and digging into problem really appreciable. but as suggested by converting that pdf with `pdftocairo (poppler)` didn't give correct output. but `inkscape and pdf2svg` were giving correct output. so how i could use these solution at my end for big blue button are there any settings which i need to enable? if yes then please help me out with this.

**Comment by jibon57** [comment]
@cgt-training2 I checked that manually from command line. You may check the code from here: 

https://github.com/bigbluebutton/bigbluebutton/blob/5189abb225247290d1954e10827853d5fc022b66/bbb-common-web/src/main/java/org/bigbluebutton/presentation/imp/SvgImageCreatorImp.java#L256

**Comment by cgt-training2** [comment]
@jibon57 ,
Thank you for the reply please correct me if i am wrong, I just need to replace this line of code:
` String rawCommand = "pdftocairo -r " + (analyze ? " 300 " : " 150 ") + format + (analyze ? "" : " -singlefile") `

either with this

` String rawCommand = "inkscape -r " + (analyze ? " 300 " : " 150 ") + format + (analyze ? "" : " -singlefile") `

or this one:

` String rawCommand = "pdf2svg -r " + (analyze ? " 300 " : " 150 ") + format + (analyze ? "" : " -singlefile") `

Please revert back on this.

**Comment by ffdixon** [comment]
Tested [Brazilian-Real-Book.pdf](https://github.com/bigbluebutton/bigbluebutton/files/6960102/Brazilian-Real-Book.pdf) on latest build of 2.6 and there characters missing (which makes sense as we're still using `pdftocairo`).
