### ISSUE TITLE
[2.3.11] Breakout room "allow users to choose a breakout room to join" not working

### ISSUE THREAD

**Issue by antwertinger** [bigbluebutton/bigbluebutton#12989]
**Describe the bug**
If you create breakout rooms and letting users choose the room they want to join, they will be redirected to blank page after selecting a room.

**To Reproduce**
1. Moderator creates breakout rooms and check the option "allow users to choose a breakout room to join"
2. Users select a breakout room 

**Expected behavior**
Users join the selected breakout room

**Actual behavior**
Users will be redirected to a blank page with the url about:blank

**Screenshots**
<img width="1679" alt="Bildschirmfoto 2021-08-12 um 22 42 03" src="https://user-images.githubusercontent.com/576402/129266857-239b5fe0-c7da-4962-b348-3db1d1011d0c.png">

**BBB version:**
2.3.11

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser: Chrome 92.0.4515.131, Firefox 92.0b2

**Comment by antobinary** [comment]
Hi @antwertinger 

Any chance you could reproduce this on test.bigbluebutton.org?
Did you use the dropdown as a viewer?
Could you provide a bit more info on the steps you did.
Thanks!

**Comment by PhMemmel** [comment]
Could reproduce this on my own instance of 2.3.11 (test.bigbluebutton.org is a bit hard to test without being able to join into the same session as another user).

In the main room after trying to join breakout room, there is a log message:
![grafik](https://user-images.githubusercontent.com/65113153/129269414-9bce7a59-9a9e-493e-b6eb-b82e344dffef.png)

Breakout room tab is just "about:blank".

After that going to breakout room panel and joining manually as user works fine.

**Comment by danimo** [comment]
Can reproduce on our test instance as well.

**Comment by PhMemmel** [comment]
After creating breakout rooms it takes between 1 and 6 seconds (duration seems to be quite randomly?) until the "join breakout room" window is shown. However, "Join room" button is active instantly.

If I wait long enough before hitting "Join room" I can enter the breakout room. However, I cannot determine "long enough" properly. Sometimes it works after even a very short amount of time. Sometimes it doesn't even work after waiting more than 3s.

**Comment by antobinary** [comment]
Client build: 1832
on the server where I test. What do you see on your server?

**Comment by PhMemmel** [comment]
same

**Comment by antobinary** [comment]
@PhMemmel Could you please join https://test.bigbluebutton.org/demo/demo3.jsp as student to rule out some cases? I have a 2h breakouts session open with freeJoin=true.

I am using English locale

**Comment by PhMemmel** [comment]
I switched both HTML5 clients to "English". So I don't think that's the issue, but you can try in German, if you want.

I can reproduce it on your test server easily. Here as well the button "Join room" is at no point disabled and the message "We are generating a join URL ..." is never shown to me.

I'm using Windows 10 64bit with Chrome and Firefox. System locale is DE. However, I don't think this is relevant.

**Comment by PhMemmel** [comment]
BTW: As soon as I joined your session as user, I was asked to join a breakout room immediately (as it's supposed to be): It showed the same behaviour (no message, button not disabled). I hit the join button and were redirected to about:blank.

This apparently happened despite the fact that the corresponding breakout rooms for sure were alive for a longer time (as you were the one who created them a decent time before I joined)

**Comment by antobinary** [comment]
I see! The default case has the Join button active - we need to address this asap. Thank you for testing!

**Comment by PhMemmel** [comment]
You're right. Seems like the waiting/link checking routine doesn't trigger on load but only when choosing a room from the list.
