### ISSUE TITLE
BigBlueButton 2.4-beta-3 (except 2.4-alpha 2) Webcam area is grey in presentation replay

### ISSUE THREAD

**Issue by NthmAnTi** [bigbluebutton/bigbluebutton#12992]
**Describe the bug**
When I played the presentation recording the webcam area is grey. But sound is exist.

**To Reproduce**
1. Start a session
2. Open your webcam
3. Start recording
4. Record around 20 sec.
5. Stop Recording
6. End the conference
7. Replay the session

**Expected behavior**
We suppose to see webcam recording.

**Actual behavior**
The webcam area is grey in presentation replay.

**Screenshots**
![bbb-2 4-beta-3-webcam-grey](https://user-images.githubusercontent.com/70592943/129342828-185cce06-7dc7-4386-8bd3-2752a60ea81c.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser: Chrome
 - Version 92.0.4515.107 (Offizieller Build) (64-Bit)

**Additional context**
Behavior is the same on the Firefox browser too. It was working fine only on BBB 2.4 alpha version 2.

**Comment by antobinary** [comment]
This looks like it would have been handled better in the https://groups.google.com/g/bigbluebutton-setup BBB setup group... 
I have not seen anything similar on the more recent BBB 2.4.x releases.
