### ISSUE TITLE
Settings menu not working for simple users (BBB 2.4-beta-3)

### ISSUE THREAD

**Issue by nikos-pappas** [bigbluebutton/bigbluebutton#13001]
**Describe the bug**
The settings menu is not working for the simple user. It works only for moderators

**To Reproduce**
Join a room as a simple user. Try to open settings menu on the top right and a small white rectangle appears.

**BBB version:**
BigBlueButton Server 2.4-beta-3 (2346)
HTTP5Client: Build 2187

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome

![Capture](https://user-images.githubusercontent.com/74572602/129458124-1057dca4-b376-4d2b-8e81-bad421830c56.PNG)

**Comment by vasylOstrovskyi** [comment]
Confirm, no error messages in browser console. The issue also exists for user which was demoted from moderator and disappears when the user is promoted to moderator.
