### ISSUE TITLE
Live caption not displaying (2.4)

### ISSUE THREAD

**Issue by jibon57** [bigbluebutton/bigbluebutton#13002]
**Describe the bug**
Live caption not displaying because it had been removed in this commit: 

https://github.com/bigbluebutton/bigbluebutton/commit/09082734c9f8bbb74fd55581c71ad2f37bc78175#diff-fb6608947529786a0ffa74b1a2db0e5335192623c2dad42bc2631e27192895a2

`renderMedia` method was removed which was displaying caption from `this.renderCaptions()` method

**To Reproduce**
1. Start Caption
2. Enable to display 
3. Nothing will display.

**Expected behavior**
Caption should render 

**Actual behavior**
But not rendering. 

**Screenshots**

**BBB version:**
2.4-beta-3

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, Mac]
 - Browser [e.g. Chrome, Safari]

**Smartphone (please complete the following information):**
 - Browser [e.g. stock browser, Safari]

**Additional context**

**Comment by ramonlsouza** [comment]
@pedrobmarin could you assign me to this one, please?
