### ISSUE TITLE
FreeSwitch DDoS and log spam in non-firewalled setup of BigBlueButton 2.4 (without ufw)

### ISSUE THREAD

**Issue by mikhailnov** [bigbluebutton/bigbluebutton#13005]
Hello!

I saw very high CPU usage by Freeswitch and sound quality degradation on BigBlueButton 2.2 and was pretty sure that is was issue https://github.com/bigbluebutton/bigbluebutton/issues/9472 , but workarounds intoduced by commits https://github.com/bigbluebutton/bbb-install/commit/61fab4905509d281ab332b1197659ebfff285f12 and https://github.com/bigbluebutton/bbb-install/commit/46295a1c8a7c92be488e85240d9f3e66841bad76 were already applied on my setup, I had no ideas and installed BBB v2.4. CPU spikes by freeswitch repeated when many meetings were online. Now, at night, when there are no meetings online, I saw abnormally high bandwitch usage and started to investigate...

There are no meetings running (I have checked using the script from https://stackoverflow.com/a/61326845), but I am seeing ~1-2 Mbit/s bandwith in `nload`, both outgoing and incoming:

![image](https://user-images.githubusercontent.com/15802528/129495589-dfd61e9e-2007-4fc2-ac94-35e9e3201f2c.png)

Nothing consuming so much bandwitch is seen in nethogs (I don't know why):

![image](https://user-images.githubusercontent.com/15802528/129494820-a81104dd-9551-49cf-a26d-eca5d2b33af0.png)

`iotop` shows that freeswitch is spamming in logs:

![image](https://user-images.githubusercontent.com/15802528/129494838-2e9d63f6-b13e-498d-9acc-c2881edc6520.png)

about 500 MiB of logs have been written in ~9 hours:

![image](https://user-images.githubusercontent.com/15802528/129495030-958786b1-9a22-4ace-a42d-baa864dca91c.png)

freeswitch is comsuimg a lot of CPU (and there are no meetings online at this moment!):

![image](https://user-images.githubusercontent.com/15802528/129495021-df4f6f12-b510-4e3f-89ef-43d648675754.png)

Now I go into the freeswitch console:

```bash
/opt/freeswitch/bin/fs_cli -p $(xmlstarlet sel -t -m 'configuration/settings/param[@name="password"]' -v @value /opt/freeswitch/etc/freeswitch/autoload_configs/event_socket.conf.xml)
```

...and see just tones of spam going there:
```
<...>
2021-08-15 22:59:54.512516 [WARNING] sofia_reg.c:2932 Can't find user [10@my_server_ip] from 20.201.114.173
You must define a domain called 'my_server_ip' in your directory and add a user with the id="10" attribute
and you must configure your device to use the proper domain in its authentication credentials.
2021-08-15 22:59:54.512516 [WARNING] sofia_reg.c:2932 Can't find user [588@my_server_ip] from 193.46.255.184
You must define a domain called 'my_server_ip' in your directory and add a user with the id="588" attribute
and you must configure your device to use the proper domain in its authentication credentials.
<...>
```
Such text is going very fast, ~500 MiB of logs in `/opt/freeswitch/var/log` have been collected in ~9 hiurs after this virtual machine was created and went online.

Let's look into the logs:

```
# ls /opt/freeswitch/var/log/freeswitch/freeswitch.log* -1v
/opt/freeswitch/var/log/freeswitch/freeswitch.log
/opt/freeswitch/var/log/freeswitch/freeswitch.log.1
/opt/freeswitch/var/log/freeswitch/freeswitch.log.2
/opt/freeswitch/var/log/freeswitch/freeswitch.log.3
/opt/freeswitch/var/log/freeswitch/freeswitch.log.4
```

```
# grep '] from ' /opt/freeswitch/var/log/freeswitch/freeswitch.log* | awk -F ' from ' '{print $NF}' | wc -l
1264110
# grep '] from ' /opt/freeswitch/var/log/freeswitch/freeswitch.log* | awk -F ' from ' '{print $NF}' | sort -u | wc -l
8
```

There are just 8 IPs producing such spam. I looked at `whois` of those IPs, 7 of them belong to Microsoft Azure and two other hosting providers from Netherlands, 1 belongs to something from Palestine (and I `traceroute`'d it, trace really looks like going to Isreal/Palestine, +50 ms after hop in Frankfurt). So, all or almost all those IPs belong to bots.

Now, to make sure that it is freeswitch who is generating 1-2 Mbit/s bandwitch when BBB is doing nothing, I ran `systemctl stop freeswitch` and so bandwitch descrease down to ~20 Kbit/s.

Now I restarted freeswitch, saw bandwitch become ~2 Mbit/s again. Let's block those 8 IPs using a firewall:

```bash
grep '] from ' /opt/freeswitch/var/log/freeswitch/freeswitch.log* | awk -F ' from ' '{print $NF}' | sort -u | while read -r line ; do iptables -I INPUT -s "$line" -j DROP; done
```

Bandwitch and CPU load have decreased to about zero.

Freeswitch is listening to ports 5060, 5090, 7443 and 8021 on the global interface, I even don't know here how to protect it from CPU spikes using a firewall.

What comes to mind is parsing freeswitch log with fail2ban, but logs will still be spammed, it is by far not a full solution of the problem.

Is it possible to disallow any connectons to FreeSwitch outside of BigBlueButton? Bots are just trying to log in with different logins, but it can also be a *dedicated* denial of service attack.

**Comment by mikhailnov** [comment]
Documentation about the firewall (https://docs.bigbluebutton.org/admin/customize.html#setup-a-firewall)does not list those freeswitch ports in the ones that must be opened. nginx is configured to proxy traffic into freeswitch.

So, applying an ufw setup recommended by BigBlueButton should probably solve the issue?

**Comment by ffdixon** [comment]
All web socket connections to FreeSWITCH are proxied through port 443 via nginx.  The firewall rules only allow for incoming UDP connections.

**Comment by mikhailnov** [comment]
`bbb-conf --check` warns about misisng firewall, but it should probably explain better why it is needed. I was pretty sure that a firewall is just an additional layer of security, but it turns to be in fact a must have layer of security because setup is vulnerable without it.

> The firewall rules only allow for incoming UDP connections.
Do you mean "UDP ports 16384 to 32768 for media connections"? WebRTC?

**Comment by ffdixon** [comment]
Yes, the UDP ports are for media traffic for WebRTC.

**Comment by mikhailnov** [comment]
Is it really necessary for freeswitch to listen to global network interfaces out of the box in the default setup without NAT? Why can't it listen to localhost/lo? nginx will still be able to proxy traffic to 127.0.0.1 I think

**Comment by mikhailnov** [comment]
I've tried to block all external traffic for nginx:

`systemctl edit freeswitch`, add:

```ini
[Service]
IPAccounting=yes
IPAddressDeny=any
IPAddressAllow=127.0.0.0/16
```
(it will work on Ubuntu 18.04, but will not on 16.04, http://0pointer.net/blog/ip-accounting-and-access-lists-with-systemd.html)

Spam was stopped, but sound inside BBB also stopped working for some reasons

**Comment by jibon57** [comment]
@mikhailnov in that case you may also need to change freeswitch IP here: https://github.com/bigbluebutton/bbb-webrtc-sfu/blob/dfc5addee6ae986379e75fb80e99d3018c8bd790/config/default.example.yml#L72

But simple firewall can solve this problem. You won't need to edit anything else.

**Comment by basisbit** [comment]
Changed the title, because the "default" BBB setup doesn't have this issue because setting up UFW as described is part of the default setup. Having to secure your setup is a common task when installing new publicly reachable services and is not a bug of BBB or anything.
Having all install script automatically configure the firewall will end up occasionally locking out admins from their servers or breaking their security layering or similar and should not be done by the bbb-install.sh in my opinion.

**Comment by mikhailnov** [comment]
> Having all install script automatically configure the firewall will end up occasionally locking out admins from their servers or breaking their security layering or similar and should not be done by the bbb-install.sh in my opinion.

I agree. But what I would try to do is avoid listening 0.0.0.0 by default where it is not needed.

> Freeswitch has to be publicly reachable over UDP or over the TURN server so that clients can connect for transferring audio data over dtls. Only the management / signalling traffic goes through Nginx reverse proxy.

Hm... How does this work? I do not see freeswitch using ports 16384 - 32768 in `ss -ntulp`...

**Comment by mikhailnov** [comment]
I see that it starts listening after joining audio:

```
udp    UNCONN     0      0      GLOBAL_IP:23662                 *:*                   users:(("freeswitch",pid=1419,fd=224))```

**Comment by basisbit** [comment]
@mikhailnov I suggest you to read some basic documentation about how WebRTC works.

**Comment by mikhailnov** [comment]
> @mikhailnov I suggest you to read some basic documentation about how WebRTC works.

Here the main question is BBB-specific implementation, but the advice is good, thanks.

systemd allows to pin a eBPF program to the unit (https://www.freedesktop.org/software/systemd/man/systemd.resource-control.html#IPIngressFilterPath=BPF_FS_PROGRAM_PATH), probably we can (I can try and contribute the results) write a eBPF program that would block all not needed traffic for `freeswitch.service` out of the box.

Will anything break? In other words, who does freeswitch on ports 8081, 8082, 7443, 8021, 5060, 5066 communicate with? If I understood correctly, nginx does not route to freeswitch directly (and it probably can't route non-HTTP traffic).

Is bbb-webrtc-sfu running as a nodejs application with which the html5 client communicates? How does bbb-webrtc-sfu interact with freeswitch?

P.S. Sorry for so many questions, but I did not see a thorough enough description of the architecture which would answer all these questions.

**Comment by prlanzarin** [comment]
> Is bbb-webrtc-sfu running as a nodejs application with which the html5 client communicates? How does bbb-webrtc-sfu interact with freeswitch?

There's no direct interaction between bbb-html5 and bbb-webrtc-sfu.
bbb-webrtc-sfu interacts with FreeSWITCH via two distinct signaling routes: 8021 (FS-ESL, event bus) and 5066 (SIP, media signaling bridge).

>  but I did not see a thorough enough description of the architecture which would answer all these questions.

https://docs.bigbluebutton.org/2.3/architecture.html#internal-network-connections
