### ISSUE TITLE
Wrong version is displayed by index.html (2.2 instead of 2.3)

### ISSUE THREAD

**Issue by zem** [bigbluebutton/bigbluebutton#13006]
We recently installed bbb 2.3 on a server. However when we open https://bbb.example.com in a Browser we get this: 

```
Copyright © 2020 BigBlueButton Inc.
Version 2.2
```

however bbb-conf --version shows that it is running 2.3.12 (2427)

It looks like an "optical"  problem to me. ;-)

**Comment by antobinary** [comment]
Hey! I am not spotting in what context you were seeing the incorrect label. Could you please take a screenshot of it with a bit of context? Perhaps it was on bbb-demo but I don't spot it there at the moment...
