### ISSUE TITLE
Keep the username in breakout room after end breakout until ended room

### ISSUE THREAD

**Issue by hdhamid1371** [bigbluebutton/bigbluebutton#13011]
**Is your feature request related to a problem? Please describe.**
Each time the breakout room is run, I have to re-determine the position of each user in the breakout  rooms, which is very difficult for me. There should be a mechanism to keep these people in fixed groups and breakout rooms throughout the room

**Describe the solution you'd like**
There is an option to save users and reset the breakout rooms.

**Describe alternatives you've considered**
There is an additional option to create breakout

**Comment by ffdixon** [comment]
It's a good suggestion.   A first step would be remembering the breakout room assignment during the session.  How helpful would that be?

Remembering breakout assignment between sessions is much harder, especially in environments that have multiple BigBlueButton servers with Scalelite -- subsequent meetings may get put on different servers.

**Comment by hdhamid1371** [comment]
ok,you can save breakout detail in database. there is breakout room setting in main room that you can save detail(username,...) in database.

**Comment by hdhamid1371** [comment]
> It's a good suggestion. A first step would be remembering the breakout room assignment during the session. How helpful would that be?
> 
> Remembering breakout assignment between sessions is much harder, especially in environments that have multiple BigBlueButton servers with Scalelite -- subsequent meetings may get put on different servers.

can you add this feature in next update?

**Comment by antobinary** [comment]
This is part of BigBlueButton 2.5-alpha-3
