### ISSUE TITLE
Closed caption panel improvements

### ISSUE THREAD

**Issue by antonbsa** [bigbluebutton/bigbluebutton#13021]
**Describe the bugs**
- Whit the 'focus on presentation' and 'custom' layouts (placing cameras below closed caption content) it's hard to resize it (same behavior that was reported in #12948) (**beginnig of the video**);
- It's possible to complete hide the top bar - with back and 'start dictation' buttons (**~00:17 of the video**);
- If the content is too small, will need to resize it to see the 'stop dictation' button after starting this (**~00:22 of the video**);

**To Reproduce**
1. Join as moderator;
2. Click to "write closed caption";

**Videos**

https://user-images.githubusercontent.com/56703993/129784375-12f4457f-b8c4-45ce-b3d5-2f7a3778fc4f.mp4

**Comment by pedrobmarin** [comment]
Hi @antonbsa ,

Do we have/had a similar problem with the shared notes?

**Comment by antonbsa** [comment]
@pedrobmarin Good point! Yes, I have a similar problem when resizing and with the hidden top bar
