### ISSUE TITLE
Feature request: Decouple activity reports from a single BBB node

### ISSUE THREAD

**Issue by PhMemmel** [bigbluebutton/bigbluebutton#13030]
**Is your feature request related to a problem? Please describe.**
On a cluster/load balancer setup the activity report information is not guaranteed to be accessible after a session as the BBB node the meeting has just taken place is being considered as a stateless node in a cluster setup. If this node is being removed from the cluster due to maintenance, upgrade, re-installation etc. the learning dashboard links become dead and the statistical information about the meeting is lost: Instructors are most likely confused about the fact that the information is lost while the BBB system appears to work properly (most users don't realize they are on a cluster setup) which will likey lead to a decent amount of "error reports".

**Describe the solution you'd like**
- In the end screen (or even while the session is still running) a moderator should be able to download the activity report json file
- There should be an activity report landing/start page (which even could be separately hosted, e. g. on the loadbalancer itself as standalone application) where everyone in possession of a downloaded activity report json can upload this to review the statistics of an already ended session in a human readable format (using the nice UI provided by the activity report react app).
- Additional CSV/PDF export feature would also be nice, of course :-) (see #12941)
- Activity report json on the BBB node should be removed after the meeting has ended (not just due to privacy reasons but to not make the instructor believe this link will stay accessible for a longer time). The instructor needs to be informed about the fact that link will be dead after meeting ended and that he can upload the json again.

Another nice effect of this: The instructor has full control of the meeting information by having control over the json file.

**Describe alternatives you've considered**
Make the host where activity reports are being hosted configurable and make the BBB node upload the statistics directly to this centrally hosted activity report app. For this approach, of course, the activity report app needs to be extended to accept POST requests by certain BBB nodes or something similar, authentication has to be considered etc.

Downside: User won't be able to control how long this information is being stored, there has to be a lot of work done to get there.

**Comment by manicmarvin** [comment]
Bump.

Just checking if there is wider or continued interest in this feature?
**Exporting Activity Reports at the end of a session, will be very helpful for many of us in my organisation.**
