### ISSUE TITLE
Empty page after login on iOS  - no menu for meeting-members - 2.4-beta3

### ISSUE THREAD

**Issue by makabar** [bigbluebutton/bigbluebutton#13039]
**Describe the bug**
Two issues:
1. After login to existing meeting and deciding audio/noaudio the webinterface shows an empty dark page 
2. Regular meeting members cannot log-off. The click on the 3 points shows an empty popup. That issue exists on all tested desktop devices.

**Smartphone (please complete the following information):**
Issue 1: tested on iPhone 6 and 8. iOS 14 and 15 beta 6. Safari

**Comment by mariogasparoni** [comment]
@makabar  can you confirm this is still an issue ? Sounds similar to #13153 

If not, please close this issue
