### ISSUE TITLE
Introduce a new user role 'Audience'

### ISSUE THREAD

**Issue by ranjithrajv** [bigbluebutton/bigbluebutton#13048]
**Is your feature request related to a problem? Please describe.**
Yes! 

As a conference organiser, I always find it difficult to moderate rooms. It is very difficult to ask the users not to switch on webcams and microphone. Locking them after they've chosen to join with microphone and webcam options sometimes seems rude. Once all the users are locked, it is hard to unlock each user to access the webcam & microphone again.

I assume this feature will also help reduce load on client and allow more audience to join per BBB room, gives confidence as conference organiser to organise events with more users without the fear of crashing.

**Describe the solution you'd like**

Create a default role 'Audience', lock the users with this role from sharing webcam and microphone by default.

- Allow moderators to invite them as presentors/speakers.
- Add a provision for owners of the room to chose 'Allow users to join as: audience, speakers or moderators'
- Add a provision for instance admins to configure room configuration in organization setting, allowing to enable or disable the option to lock users from accessing webcam and microphone.

**Describe alternatives you've considered**

**Additional context**
This feature can be complementary for these
- https://github.com/bigbluebutton/bigbluebutton/issues/11764
- https://github.com/bigbluebutton/bigbluebutton/issues/9392
- https://github.com/bigbluebutton/bigbluebutton/issues/9695

**Comment by hiroshisuga** [comment]
These may do the job:
https://github.com/aau-zid/BigBlueButton-liveStreaming
https://github.com/manishkatyan/bbb-streaming

**Comment by ranjithrajv** [comment]
> These may do the job:
> https://github.com/aau-zid/BigBlueButton-liveStreaming
> https://github.com/manishkatyan/bbb-streaming

Running a separate microservice is too hard to set up, maintain and operate. Some simple tweaks to BBB would do the required job.

**Comment by PhMemmel** [comment]
As far as I understand your feature request BBB is already capable of doing this:

- Open session as mod
- Disable Webcam and Mic for all (UserList Gear, Lock viewers)
- So, all joining users will be restricted and are forced into listen only mode
- You then can unlock users who will participate with audio and Webcam by clicking on their name in the user list. They then will be able to rejoin audio with microphone access

**Comment by ranjithrajv** [comment]
>     * Open session as mod 
>     * Disable Webcam and Mic for all (UserList Gear, Lock viewers)
>     * So, all joining users will be restricted and are forced into listen only mode
>     * You then can unlock users who will participate with audio and Webcam by clicking on their name in the user list. They then will be able to rejoin audio with microphone access

I've been doing this, thanks for the suggestion anyway. This is a tiresome process, as I mentioned in the opening paragraph. This is almost unbearable when handling it in cases like using BBB for conferences. 
> 
> Making this available as room preference is job of your used frontend.

Okay, I'll open issue(s) about this in greenlight.

**Comment by ranjithrajv** [comment]
Closing this in favor of https://github.com/bigbluebutton/greenlight/issues/2883
