### ISSUE TITLE
*.fodp is not allowed as presentation

### ISSUE THREAD

**Issue by mikhailnov** [bigbluebutton/bigbluebutton#13049]
I often make presentation if *.fodp format in LibreOffice Impress. It is plain text XML, what allows to track changes via git. Bigbluebutton v2.4 does not allow to upload an fodp file.

**Comment by antobinary** [comment]
Thanks for this enhancement request!

**Comment by mikhailnov** [comment]
It has a different MIME type that *.odp:

```
[user@rosa2019 Рабочий стол]$ file *.fodp
ОС РОСА mikhailnov.fodp: XML 1.0 document, Unicode text, UTF-8 text, with very long lines (2386)
[user@rosa2019 Рабочий стол]$ file --mime-type *.fodp
ОС РОСА mikhailnov.fodp: text/xml
[user@rosa2019 Рабочий стол]$ xdg-mime query filetype *.fodp
application/vnd.oasis.opendocument.presentation-flat-xml
```

Should I try adding a new mime type there?
