### ISSUE TITLE
Playing external videos in recordings (bbb-playback component)

### ISSUE THREAD

**Issue by amguirado73** [bigbluebutton/bigbluebutton#13041]
BBB doesn't support external videos in recordings. I would like to contribute a PR for bbb-playback.
You can check it in:

https://github.com/bigbluebutton/bbb-playback/pull/127

This is only a PR for bbb-playback. BBBCore should be updated to generate a xml file with information about external videos
base on redis messages. Now this player is only a alpha version and file is generate manually.

You can test it in:

https://bbbdemo23.f-integra.org/playback/presentation/2.3/1facfc84a74fb0957f2f1ceb4760a984925bc61b-1629192064279

**Comment by pedrobmarin** [comment]
Amazing work, @amguirado73 !

**Comment by iSamof** [comment]
@amguirado73 - well done, sir. THANK YOU

**Comment by hiroshisuga** [comment]
Finally!

**Comment by hiroshisuga** [comment]
related to #11051, which will be solved in a better way. Yet, I prefer to have also video's URLs in the chat window.
