### ISSUE TITLE
[2.4-beta-3] - Bug when trying to publish a poll in a different presentation

### ISSUE THREAD

**Issue by antonbsa** [bigbluebutton/bigbluebutton#13054]
**Describe the bug**
If you start a poll on one presentation and try to publish the results on another, the publish button will be blocked and you will not be able to start another poll.

**To Reproduce**
1. Start a poll
2. Change the presentation file
3. Click to publish polling results

**Video**

https://user-images.githubusercontent.com/56703993/130485629-9562a349-8423-4cb6-a7c3-3274c283343b.mp4

**Comment by ramonlsouza** [comment]
Looks like an issue with the back-end not sending `PollStoppedEvtMsg` back to the client after a `StopPollReqMsg` is sent from the client (polls are somehow related to slide/presentation when poll starts, and will only end if the same slide and presentation are active).

**Comment by pedrobmarin** [comment]
Hmmm, I might know what's this about... thanks @ramonlsouza

**Comment by pedrobmarin** [comment]
Hi @antonbsa , can you still reproduce this bug after #13062 was merged in v2.4?

**Comment by antonbsa** [comment]
Hi @pedrobmarin, I can't reproduce it. Seems to be fixed!
Closing this.
