### ISSUE TITLE
Create live push ability

### ISSUE THREAD

**Issue by rfakit** [bigbluebutton/bigbluebutton#13098]
I thinks if you add sth to push live class to nginx rtmp inorder to make it as live stream class, that would be a blast feature.
hope you add this one to next update

**Comment by GhaziTriki** [comment]
@rfakit Do you find what you need in https://github.com/bigbluebutton/bigbluebutton/issues/8295?

**Comment by prlanzarin** [comment]
Duplicate of #8295
