### ISSUE TITLE
Adding notes/comments to a recording

### ISSUE THREAD

**Issue by ali-alhaidary** [bigbluebutton/bigbluebutton#13096]
**Is your feature request related to a problem? Please describe.**
As BBB is used in education, Teachers usually review the recording and sometimes the find some errors in the lecture and need to notify students by adding a note to the recording.

**Describe the solution you'd like**
Moderators can add notes/comments to a recording that is kept with the recording

**Describe alternatives you've considered**
1. email notification to students, but it is not very effective.
2. adding the note/comment in the description field of the recording, which is in many cases can be miss leading.
3. Putting the note/comment in the lesson/course announcement section, which stays not attached to the recording.
4. Creating a 'changes' file for each course with an entry for each lesson.

**Comment by hiroshisuga** [comment]
I add chat messages manually, which is pretty easy as long as you are an admin. But I guess you want a user interface for it.

**Comment by ali-alhaidary** [comment]
How do you do that?

**Comment by hiroshisuga** [comment]
By modifying /var/bigbluebutton/published/presentation/[your meeting ID]/slides_new.xml .

**Comment by ali-alhaidary** [comment]
Thanks, but this is way far from our use case.

**Comment by hiroshisuga** [comment]
I guess so... but I can tell you the modification of slides_new.xml is still very helpful for students in the current version. We teachers often say something wrong during live lectures while students can play it as much as they want;-).

To  have a user interface enabling every user to modify the recording, you may need a new API in the BBB's side, and another massive modification in the frontend (Greenlight or Moodle). In my experience, such cross-project modification is not easy unless the core team decide it as a new product design (which is far better than the initial idea though).

Just in case, I would second you; I would like to have a comprehensive API to modify the recording, such as adding post-publish chat messages and editing the presentation (especially cutting).

**Comment by ali-alhaidary** [comment]
We are not asking for that much, just for a field in the playback to add notes/comments.

**Comment by hiroshisuga** [comment]
As far as I understand, the playback app only reads the information provided by BBB. Adding notes is impossible without changing the published files.
