### ISSUE TITLE
Shared notes service missing after Upgrade to  2.3.13

### ISSUE THREAD

**Issue by dahrens** [bigbluebutton/bigbluebutton#13113]
**Describe the bug**

After upgrading to  2.3.13 the shared notes service is missing in the HTML5 Client.
The reason is, that the `ETHERPAD_APIKEY` in `/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml` is not replace properly.

Running `bbb-conf clean` and/or `bbb-conf --setip $(hostname)` does not help

We've worked around this by adding the following to the `apply-config.sh`

```bash
ETHERPAD_APIKEY=$(cat /usr/share/etherpad-lite/APIKEY.txt)
sed -i "s/ETHERPAD_APIKEY/$ETHERPAD_APIKEY/" /usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml
```

**Additional context**

This issue is related to #9027.

**Comment by antobinary** [comment]
Hi @dahrens 

Have you considered using `/etc/bigbluebutton/bbb-html5.yml` instead of `/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml` ? The /etc/bigbluebutton/* files are not touched on updates. Check https://docs.bigbluebutton.org/admin/configuration-files.html#local-overrides-for-configuration-settings

**Comment by dahrens** [comment]
Sure, but this makes life even harder. We've a bunch of servers and this key is unique on each of them. Therefore I can't easily push those file from our configuration management (I it makes sense IMO that each BBB host has it own etherpad key). The original file already has the value I'd like to replace (`ETHERPAD_APIKEY`) - the user config does not know about it in the first place. Or do I miss something?

IMO the main issue here is, that - since the last upgrade - that key is not replaced by default anymore, which most likely happend before.

**Comment by antobinary** [comment]
Which BBB version were you running prior to 2.3.13? I do not quite spot which code change may have contributed to this in the 2.3.12 -> .13 jump https://github.com/bigbluebutton/bigbluebutton/releases/tag/v2.3.13

**Comment by dahrens** [comment]
It was this minor upgrade. I've checked the changes as well. There might be additional scripts in the debian package that get triggered. I was searching for CVS regarding the systemd configs in the past and did not find anything.

**Comment by dahrens** [comment]
Oh and it is possible that we had this issue already before, but nobody noticed it, as we have semester holidays. We upgrade our stack automatically in chunks of machines and BBB worked quite fine without this setting, just the shared notes were missing.

**Comment by antobinary** [comment]
Let's reopen if this is reproducible on BBB 2.4.4+
