### ISSUE TITLE
Blank Blue Screen when users are locked before joining session 2.4 beta 3

### ISSUE THREAD

**Issue by markginter31** [bigbluebutton/bigbluebutton#13124]
**Describe the bug**
Moderator locks all options before user joins.  When user joins, the screen flashes with the user list on left and presentation - then the screen only shows a blue background
**To Reproduce**
1. Go to --> lock users
2. Click on --> choose all lock options
4. See error --> when users join, their screen goes blue

**Expected behavior**
A user will join with all options locked and see the normal presentation screen
**Actual behavior**
A clear and concise description of what you saw.
Moderator chose all lock options, users joined, users screens flash and go to blue background.

**BBB version:**
BigBlueButton continually evolves. Providing the version/build helps us to pinpoint when an issue was introduced.
Example:
$ sudo bbb-conf --check | grep BigBlueButton
BigBlueButton Server 2.4-beta-3 (2351)

**Desktop (please complete the following information):**
Linux with Firefox

**Comment by markginter31** [comment]
Trying to re-create this at home and I'm not able.  It probably has something to do with my classroom proxy getting in the way.  Closed.

**Comment by ffdixon** [comment]
Thanks for the update and letting us know.
