### ISSUE TITLE
2.4 beta 3 User can join, but cannot leave 

### ISSUE THREAD

**Issue by markginter31** [bigbluebutton/bigbluebutton#13126]
**Describe the bug**
Once a user joins, if they click the three dots, no menu shows up for leaving the meeting --> just a small white box appears.
**To Reproduce**
1. User joins meeting
2. User clicks three dot menu
3. User is shown small white box

**Expected behavior**
User is presented with options in drop down menu from three dots
**Actual behavior**
A clear and concise description of what hapens.
User is presented with tiny white box (this does not happen to moderators)

**BBB version:**
2.4 beta 3

**Desktop (please complete the following information):**
Linux / Firefox / Chrome

**Comment by PhMemmel** [comment]
That's already fixed in #12996, should be included in 2.4-RC1

**Comment by markginter31** [comment]
Sorry about that.  Tried to search for any existing post but didn't come across that one.  Thanks!
