### ISSUE TITLE
Broken Link for tutorial videos

### ISSUE THREAD

**Issue by fuu0** [bigbluebutton/bigbluebutton#13136]
**Describe the bug**
Every Room has a welcome Text like "For help on using BigBlueButton see these (short) tutorial videos."
The integrated Link is broken:
https://www.bigbluebutton.org/html5
The new Link seems to be:
https://bigbluebutton.org/teachers/tutorials/

**To Reproduce**
1. Go to http://test.bigbluebutton.org/
2. Create a test conference
3. Click on the Link in the Chat

**Expected behavior**
See some Videos

**Actual behavior**
SSL Error

**Comment by antobinary** [comment]
Thank you @fuu0 
I replaced the link with the newer version. This should handle it for BBB 2.4+
