### ISSUE TITLE
2.4 - beta 4: foreign (shared) camera view on mobile device not working. 

### ISSUE THREAD

**Issue by makabar** [bigbluebutton/bigbluebutton#13144]
After login i cannot see shared camera of presenter. I see the room with the current meeting now (was not working in in 2.4 - beta 3), but there is only a black box including the presenters name shown where the camera view was expected.
Tested on iOS15 Beta 8 iPhone SE 2020 and iOS14 iPad.
Additional issue: I cannot choose blurred or other background while setting up camera share on iOS.

**Comment by antobinary** [comment]
> Additional issue: I cannot choose blurred or other background while setting up camera share on iOS.

The feature is disabled for Safari for the time being, not exactly a bug https://github.com/bigbluebutton/bigbluebutton/pull/12841


> cannot see shared camera of presenter

Do you happen to have any browser console logs from this session?

**Comment by makabar** [comment]
Tested in 2.4-rc1 again. It´s working as expected.
Ticket can be closed. Thanx
