### ISSUE TITLE
overrideLocale parameter is not applied on some captions and dialog boxes

### ISSUE THREAD

**Issue by ali-alhaidary** [bigbluebutton/bigbluebutton#13159]
**Describe the bug**
overrideLocale parameter is not applied on some captions and dialog boxes

**Expected behavior**
overrideLocale parameter is applied on some captions and dialog boxes

**Actual behavior**
overrideLocale parameter is not applied on some captions and dialog boxes

**Screenshots**
Attached
![1](https://user-images.githubusercontent.com/75235623/132116717-16c4e70e-3d2f-4874-adda-6988048d427a.png)
![2](https://user-images.githubusercontent.com/75235623/132116718-b4b9a0c8-c363-4abb-ab15-2254fc35a03b.png)
![3](https://user-images.githubusercontent.com/75235623/132116719-f6ed974e-58e1-4b9e-9bcf-5f5a4237e47a.png)
![4](https://user-images.githubusercontent.com/75235623/132116721-7a3fe2fb-7ddf-44c0-8e9e-84409c0346fd.png)
![5](https://user-images.githubusercontent.com/75235623/132116722-c591f77b-73d6-4e8e-a726-e3f564bd995b.png)
![6](https://user-images.githubusercontent.com/75235623/132116724-6c3bdf43-b35c-408e-bc52-3b3d5bf4469f.png)

**BBB version:**
BigBlueButton Server 2.4-rc-1 (2446)

**Desktop (please complete the following information):**
 - OS: All
 - Browser All
 - Version All

**Smartphone (please complete the following information):**
 - Device: All
 - OS: All
 - Browser All
 - Version All

**Comment by PhMemmel** [comment]
These are language strings which have been introduced by recent PRs, so at the time the locales have been pulled from transifex they were still missing for your language.

As soon as they have been translated in transifex they will be shown properly in the next release.

**Comment by ali-alhaidary** [comment]
Thank you, however, I have translated all strings before 2.4.b-4 was pulled, and there is no pending strings to be translated.

**Comment by ali-alhaidary** [comment]
https://www.transifex.com/bigbluebutton/bigbluebutton-v24-html5-client/translate/#ar/enjson/329012773?q=translated%3Ano

**Comment by PhMemmel** [comment]
Last pull in develop branch of `ar.json` apparently was 10 days ago. As you can see the language keys `app.learning-dashboard.*` are missing, for example:
https://github.com/bigbluebutton/bigbluebutton/blob/develop/bigbluebutton-html5/public/locales/ar.json

If you have translated them by now they for sure will be included in the next release.

**Comment by ali-alhaidary** [comment]
Yes, you are right, but I can download it from transifex and use locally. what local path it should be in please?

**Comment by PhMemmel** [comment]
`/usr/share/meteor/bundle/programs/web.browser/app/locales`

**Comment by ali-alhaidary** [comment]
Downloaded the file from transifex, put it as in recommended path and restarted BBB. But the same strings are still not translated...

**Comment by ali-alhaidary** [comment]
Only the attached is still not translated
![3](https://user-images.githubusercontent.com/75235623/132119128-caefa741-b47e-44e6-8ffa-81a8e77fadce.png)

**Comment by PhMemmel** [comment]
Double check if the key `app.learningDashboard.participantsTable.colActivityScore` is present

**Comment by ali-alhaidary** [comment]
No, it is no there in ar.jason

**Comment by ali-alhaidary** [comment]
Added the key "app.learningDashboard.participantsTable.colActivityScore": "نتيجة النشاط" to ar.json and restarted BBB.
Now all is OK for Arabic. Unfortunately I can not edit source in transifex, so someone must do it and I will put the proper translation.
So many thanks...

**Comment by PhMemmel** [comment]
This language key apparently has been forgotten in the corresponding PR. I opened PR #13163 to add it. As soon as this is merged and transifex updated its `en.json` this key will be present and available for translation for future releases.

**Comment by ali-alhaidary** [comment]
still not there...

**Comment by ali-alhaidary** [comment]
PR https://github.com/bigbluebutton/bigbluebutton/pull/13195

**Comment by antobinary** [comment]
These seem localized, translated, and (from what I can tell) correctly displayed on 2.4-rc-1

![Screenshot from 2021-09-22 19-24-35](https://user-images.githubusercontent.com/6312397/134434830-fbaf3337-721e-4bcf-b7f3-f8a44d4be055.png)
![Screenshot from 2021-09-22 19-24-10](https://user-images.githubusercontent.com/6312397/134434831-137b5e39-10fe-4a2f-8eab-8db670ffacfd.png)

**Comment by ali-alhaidary** [comment]
@antobinary yes, thank you.
