### ISSUE TITLE
hide all view html in mobile when presentor set "lock viewer"

### ISSUE THREAD

**Issue by hdhamid1371** [bigbluebutton/bigbluebutton#13150]
**Describe the bug**
hide all view html in mobile when presentor set user lock. 
i unlock all items then work html
**To Reproduce**
1. Go to 'lock viewer'
2. set lock
3. join meeting by viewer in mobile browser
4. see blank html!!!!

**BBB version:**
BigBlueButton continually evolves. Providing the version/build helps us to pinpoint when an issue was introduced.
Example:
$ sudo bbb-conf --check | grep BigBlueButton
BigBlueButton Server 2.4-beta-4 (2435)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, Mac]
 - Browser [e.g. Chrome, Safari]

**Smartphone (please complete the following information):**
 - Device: [e.g. huawi]
 - OS: [e.g. android 7]
 - Browser [e.g. stock browser, chrome]
 - Version [e.g. 92.0.4515.166]

**Additional context**

**Comment by markginter31** [comment]
I've seen this too.  Only in my classroom and only in the browsers on those computers.  What seems to be happening in beta 4 is related to the audio chooser.  When all the locks are applied the chooser begins to open and then the screen goes to blue.  If you manage to click on the x in the chooser box as its appearing then the page loads normally with everything locked.  If you lock everything except for the microphone then the audio chooser works fine and the user joins normally.  Again, I could only get this to happen on computers (Linux, Firefox) in my classroom and couldn't replicate elsewhere so I assumed it was something in my small setup there.

**Comment by ramonlsouza** [comment]
I was not able to reproduce the issue in latest release (2.4-rc-1, build 2277)
When joining a meeting with every item locked, a viewer auto joins audio with listen only.

https://user-images.githubusercontent.com/3728706/136264928-e61cec50-a940-4dc4-a7f5-d7995842d886.mov

**Comment by antobinary** [comment]
Let's reopen if this is encountered on BBB 2.4.4+
