### ISSUE TITLE
bbb-web crash leads to reset of the conference login

### ISSUE THREAD

**Issue by GyR4uk** [bigbluebutton/bigbluebutton#13155]
Sometimes we notice that the bbb-web application crashes, which leads to the reset of all entry points to running conferences.

Repeat:
1) Create a conference
2) Check the getMeatings conference
3) Restart bbb-web
4) Check the getMeatings conference
5) PROFIT! the conference is going on, but it is no longer displayed in getmeeting and you can't log in to it.

**Comment by hostbbb** [comment]
Wouldn't we expect this behavior if bbb-web crashes.... Cant restart services while meetings are going. 
You manually restarted right.  bbb-web did not crash?

Be interested in figuring out why bbb-web is crashing.

**Comment by GyR4uk** [comment]
![image_2021-09-03_12-07-27](https://user-images.githubusercontent.com/35705596/132124005-985807ed-b09a-4133-ad9a-52e5fbd85d8e.png)

**Comment by GhaziTriki** [comment]
@GyR4uk Are you trying to list all the recordings from the server? How many recordings are you trying to fetch?

**Comment by GyR4uk** [comment]
There are a lot of records. I know the nature of the bbb-web crash error. But the consequences in the event of a fall are sad for other users.

**Comment by hostbbb** [comment]
yes passing meetingID="" on getRecordings would cause issue if lots of recording.

**Comment by GyR4uk** [comment]
In fact, hanging and restarting is not such a big problem, it is much more terrible when this happens, you can no longer re-enter the conference that is still going on.
