### ISSUE TITLE
screen goes blank when selecting listen only on iOS devices

### ISSUE THREAD

**Issue by ali-alhaidary** [bigbluebutton/bigbluebutton#13153]
**Describe the bug**
screen goes blank when selecting listen only

**To Reproduce**
1. Go to a new session.
2. select 'listen only' icon

**Expected behavior**
the session starts and the the display shows the normal session

**Actual behavior**
the display goes blank

**BBB version:**
BigBlueButton Server 2.4-beta-4 (2437)

**Smartphone (please complete the following information):**
 - Device: iPhone, iPad
 - OS: iOS 14
 - Browser Safari

**Comment by ffdixon** [comment]
Thanks Ali.  We are able to reproduce this on https://test24.bigbluebutton.org/.

**Comment by ali-alhaidary** [comment]
fixed with v2.4 rc1
