### ISSUE TITLE
Feature: Add maximum users per room limit

### ISSUE THREAD

**Issue by ranjithrajv** [bigbluebutton/bigbluebutton#13169]
**Is your feature request related to a problem? Please describe.**
We maintain a BBB instance aimed for public events. As the number of guest users touch the maximum the server can handle, the BBB room gets crashed, with no option leaving us to kill the room and restart it again to allow users afresh. This is a huge interruption to scheduled & time limit public events, disturbing the event being organised. 

**Describe the solution you'd like**
As a server admin of a self-hosted BBB, I'd be aware of how many users a room can handle. Please add a feature that allows the admins of the server to add a limit for maximum number of users that can join a room. If any user drops, it will create a vacuum for a new user to join.

**Describe alternatives you've considered**
As we can't set up maximum users per room now, we tried enabling moderator approval and allowed users around a number we figured out the server can handle in stress tests, that's approving each user, one-by-one, a tiresome process. Users would drop in-between, now we need to approve the new users again. We need to assign a person to constantly watch the number of users and allow new users would drop, this can be fixed with introducing a simple feature that would automate this process.

**Additional context**

**Comment by laserrapt0r** [comment]
In bigbluebutton.yml:

# Default maximum number of users a meeting can have.
# Current default is 0 (meeting doesn't have a user limit).
defaultMaxUsers=0

**Comment by antobinary** [comment]
Hi @ranjithrajv ,
There already is a similar parameter -

`maxParticipants` | Number | `Set the maximum number of users allowed to joined the conference at the same time.`

from the `create` call in the API https://docs.bigbluebutton.org/dev/api.html#create
