### ISSUE TITLE
Enable Multi presentation  and screen share windows

### ISSUE THREAD

**Issue by gorlapraveen** [bigbluebutton/bigbluebutton#13166]
**Is your feature request related to a problem? Please describe.**
In times of colloborative discussion/meetings, need for having mulltiple screen share/presentations options is needed.

**Describe the solution you'd like**
Enbaling screenshare/prrsentation sharing for all the moderators. This can enable the multi screen share during the colloborative meeting and can also enable the pair programming learning environment.

**Describe alternatives you've considered**

**Additional context**

**Comment by ffdixon** [comment]
> This can enable the multi screen share during the colloborative meeting and can also enable the pair programming learning environment.

It's a good use case for collaborating.

However, at the moment, we tie the ability to share screens to the presenter, and BigBlueButton allows only one presenter at a time.

Need to figure out how we could enable this type of engagement in a future update.

**Comment by antobinary** [comment]
Merging into https://github.com/bigbluebutton/bigbluebutton/issues/9152
