### ISSUE TITLE
Migration issue

### ISSUE THREAD

**Issue by suraj401** [bigbluebutton/bigbluebutton#13171]
Trying to migrate recording from bbb 2.2(Ubuntu 16.04, 8 CPU cores/8 GB of memory) to bbb 2.3(Ubuntu 18.04,8 CPU cores/16 GB of memory,) using the following document https://docs.bigbluebutton.org/2.3/install.html#upgrading-from-bigbluebutton-22
Using bbb-record --list I get recording at the backend, but on the frontend dashboard, I'm not able to see migrated recording from bbb 2.2 in all recordings.
![frontend](https://user-images.githubusercontent.com/83824847/132240966-d392a102-85a1-4746-aaff-5ff71cd5a79b.png)
![backend](https://user-images.githubusercontent.com/83824847/132240970-8c0b7183-59de-4819-90cc-e4cbbd78e54d.png)

**Comment by antobinary** [comment]
Questions like this are best handled in BigBlueButton Setup https://groups.google.com/g/bigbluebutton-setup . Posting there will likely yield much better result
