### ISSUE TITLE
Ability to logout a user through API

### ISSUE THREAD

**Issue by mehrancodes** [bigbluebutton/bigbluebutton#13172]
**Is your feature request related to a problem? Please describe.**
We need a way to prevent duplicate users from multiple devices. already when a user wants to join a session we would check if they have already attended or not. but we don't have any API to log them out of any other devices if any exist.

**Comment by pedrobmarin** [comment]
Did you try disabling https://github.com/bigbluebutton/bigbluebutton/blob/04a8d5e35929d2fd8e470e78e63c2259ad3970ae/bigbluebutton-web/grails-app/conf/bigbluebutton.properties#L399
