### ISSUE TITLE
Set Focus on one-on-one Meetings

### ISSUE THREAD

**Issue by approlab** [bigbluebutton/bigbluebutton#13185]
Set focus is not available for a 1-on-1 meetings. It would be great to have a UI similar to whatsapp Video call on a 1-on -1 meetings where tutor will be shown bigger than my own webcam. It can be reversed for Tutors. this way tutor can give maximum attention to student and wise versa. Let me know if i am duplicating an existing issue or if this feature is already available.

Thanks

**Comment by Jossef-767** [comment]
It would also be great for meetings with a lot of attendees.
The possibility that a tutor video will be large by default is always desirable.
Or at least focus by double clicking on the video as it was in the flash client (for those of us who remember 🙂)
