### ISSUE TITLE
Warning message that telephone-user cannot be unmuted

### ISSUE THREAD

**Issue by eegcl-bugs** [bigbluebutton/bigbluebutton#13188]
**Is your feature request related to a problem? Please describe.**
Participants in a bbb-conference via telephone can be muted, but not unmuted! --> problem

**Describe the solution you'd like**
BBB should give show a big warning message to the moderator, when muting a telephone-participant, that he/she cannot be unmuted!

**Describe alternatives you've considered**
Alternatively telephone-muting could be disabled (to kick the participant out of the conference is possible as well)

**Comment by ffdixon** [comment]
Telephone users can unmute themselves by pressing the zero key on their phone's keypad.  By default, a moderator does not have he the ability to unmute a user (this would be a privacy issue) either connected to VoIP or the phone.  

On your BigBlueButton server, you can give moderators the ability to unmute by passing `allowModsToUnmuteUsers=true` on the `create` command.  See https://docs.bigbluebutton.org/dev/api.html#create.
