### ISSUE TITLE
Possibility to re-connect to bbb-conference for telephone-participants

### ISSUE THREAD

**Issue by eegcl-bugs** [bigbluebutton/bigbluebutton#13189]
**Is your feature request related to a problem? Please describe.**
If a telephone participant exits the bbb-conference or is thrown out by the moderator, he/she cannot reconnect!!

**Describe the solution you'd like**
Possibility to re-connect to the same conference via telephone

**Comment by hostbbb** [comment]
tested 2.4 beta3

can confirm if moderator removes dialin user even "without" checking box to block... future attempts fails, the phone connects for second, but bbb kicks it immediately, hear "you are only one in conference" when phone kicked.

if the dial user disconnects,  they can successfully dial back in.

**Comment by hostbbb** [comment]
just tested "prevent user from rejoining" with normal web user..
using demo pages...   a viewer named "test" is kicked with the box checked to prevent rejoining
however after being kicked, i can still join a user named test?  may be another issue.  2.4 beta3
