### ISSUE TITLE
Bigbluebutton 2.3.13 Shared Notes 401 Authorization Required

### ISSUE THREAD

**Issue by dolevu** [bigbluebutton/bigbluebutton#13194]
**Describe the bug**
Click on Shared Notes, the error appears

401 Authorization Required
nginx

**To Reproduce**
1. Go to any Bigbluebutton session
2. Click on Shared Notes
3. See error

**Expected behavior**
The Shared Notes should work

**Actual behavior**
401 Authorization Required
nginx

**Screenshots**
![image](https://user-images.githubusercontent.com/8370438/132936906-349c178e-e605-4cdb-a012-2675e08b1f1e.png)

**Desktop (please complete the following information):**
 - OS: Wndows 10 21H1
 - Browser: Firefox 92.0

**Additional context**
bbb-conf --status

> nginx —————————————————► [✔ - active]
> freeswitch ————————————► [✔ - active]
> redis-server ——————————► [✔ - active]
> bbb-apps-akka —————————► [✔ - active]
> bbb-fsesl-akka ————————► [✔ - active]
> tomcat8 ———————————————► [✔ - active]
> mongod ————————————————► [✔ - active]
> bbb-html5 —————————————► [✔ - active]
> bbb-webrtc-sfu ————————► [✔ - active]
> kurento-media-server ——► [✔ - active]
> bbb-html5-backend@1 ———► [✔ - active]
> bbb-html5-backend@2 ———► [✔ - active]
> bbb-html5-frontend@1 ——► [✔ - active]
> bbb-html5-frontend@2 ——► [✔ - active]
> etherpad ——————————————► [✔ - active]
> bbb-web ———————————————► [✔ - active]

/etc/bigbluebutton/nginx/notes.nginx

> location /pad/p/ {
>     rewrite /pad/p/(.*) /p/$1 break;
>     rewrite ^/pad/p$ /pad/p/ permanent;
>     proxy_pass http://127.0.0.1:9001/p;
>     proxy_pass_header Server;
>     proxy_redirect /p /pad/p;
>     proxy_set_header Host $host;
>     proxy_buffering off;
> 
>     proxy_set_header X-Real-IP $remote_addr;  # http://wiki.nginx.org/HttpProxyModule
>     proxy_set_header X-Forwarded-For $remote_addr; # EP logs to show the actual remote IP
>     proxy_set_header X-Forwarded-Proto $scheme; # for EP to set secure cookie flag when https is used
>     proxy_http_version 1.1;
> 
>     auth_request /bigbluebutton/connection/validatePad;
>     auth_request_set $auth_status $upstream_status;
> }
> 
> location /pad {
>     rewrite /pad/(.*) /$1 break;
>     rewrite ^/pad$ /pad/ permanent;
>     proxy_pass http://127.0.0.1:9001/;
>     proxy_pass_header Server;
>     proxy_redirect / /pad/;
>     proxy_set_header Host $host;
>     proxy_buffering off;
> }
> 
> location /pad/socket.io/socket.io.js {
>     rewrite /pad/socket.io/socket.io.js /socket.io/socket.io.js break;
>     proxy_pass http://127.0.0.1:9001/;
>     proxy_set_header Host $host;
>     proxy_buffering off;
> }
> 
> location /pad/socket.io {
>     rewrite /pad/socket.io/(.*) /socket.io/$1 break;
>     proxy_pass http://127.0.0.1:9001/;
>     proxy_redirect / /pad/;
>     proxy_set_header Host $host;
>     proxy_buffering off;
>     proxy_set_header X-Real-IP $remote_addr;  # http://wiki.nginx.org/HttpProxyModule
>     proxy_set_header X-Forwarded-For $remote_addr; # EP logs to show the actual remote IP
>     proxy_set_header X-Forwarded-Proto $scheme; # for EP to set secure cookie flag when https is used
>     proxy_set_header Host $host;  # pass the host header
>     proxy_http_version 1.1;  # recommended with keepalive connections
>     # WebSocket proxying - from http://nginx.org/en/docs/http/websocket.html
>     proxy_set_header Upgrade $http_upgrade;
>     proxy_set_header Connection "Upgrade";
> 
>     auth_request /bigbluebutton/connection/checkAuthorization;
>     auth_request_set $auth_status $upstream_status;
> }
> 
> location /static {
>     rewrite /static/(.*) /static/$1 break;
>     proxy_pass http://127.0.0.1:9001/;
>     proxy_set_header Host $host;
>     proxy_buffering off;
> }
>

**Comment by dolevu** [comment]
I found out the issue
When the user's display name has some invalid characters, like # or ?, it will cause the issue.

**Comment by pedrobmarin** [comment]
Hi @dolevu , thanks for the report.

We should fix so I'll reopen this issue.

**Comment by sonerd** [comment]
I can confirm this issue. A participant with `?` in the name is getting the same error as described above.

**Comment by pedrobmarin** [comment]
This is likely resolved on develop branch
