### ISSUE TITLE
Scalelite-api cpu 100%

### ISSUE THREAD

**Issue by bbbmm** [bigbluebutton/bigbluebutton#13200]
Hello,

we are facing an issue with BBB and seeking your support in fixing.

the container cpu of the scalelite-api is getting 101% usage while the scalelite server is reaching less than 1% cpu usage.

we are not sure how to fix this.

it is causing super slowness in the distribution of the BBB servers by the scalelite.

we are using bbb through Moodle

**Comment by ffdixon** [comment]
Can you open this issue at https://github.com/blindsidenetworks/scalelite -- that is the proper issue tracker.
