### ISSUE TITLE
Network connectivity icon : French translation

### ISSUE THREAD

**Issue by maschmutz** [bigbluebutton/bigbluebutton#13202]
**Describe the bug**
There is a small error in the French translation of HTML5 client.
The word "**status**" is not spelled correctly in the network connectivity status icon. 

**To Reproduce**
1. Go to BBB 2.3 HTML5 client.
2. Mouse over the network connectivity status icon to view the error.

**Expected behavior**
Connection status label : `Statut de la connexion`

**Actual behavior**
Connection status label : `Satut de la connexion`

**Screenshots**
![bbb_connection_status_label](https://user-images.githubusercontent.com/65963478/133003385-d5da97ec-144e-47b3-b96b-d8125a8cc696.png)

**BBB version:**
BigBlueButton Server 2.3.13 (2444)

**Desktop:**
 - OS: Windows 10 1909
 - Browser: Firefox
 - Version: 78.14.0esr
 - Language: French

**Comment by pedrobmarin** [comment]
Hi @maschmutz , thanks for pointing that out.

The BigBlueButton project uses a third party tool for setting localization. More details [here](https://docs.bigbluebutton.org/dev/localization.html). Feel free to register at the french community and propose any changes.
