### ISSUE TITLE
Presentation small on joining Meeting

### ISSUE THREAD

**Issue by easy-bios** [bigbluebutton/bigbluebutton#13208]
**Describe the bug**
Sometimes if you join a meeting with running webcams AND a allready running screenshare the screenshare is rally small. (minimum I guess)

**To Reproduce**
1. Start a meeting
2. Share webcam
3. Do screenshare
4. Join as attendee (sometimes it's 50% chance, sometimes it's just 1% chance this bug happens, it is higher if the bbb-server load is higher)

**Screenshots**
![image](https://user-images.githubusercontent.com/42430994/133105924-c44a6256-addb-43de-b13a-c814c6850b44.png)

**BBB version:**
BigBlueButton Server 2.3.11 (2425)
BigBlueButton Server 2.3.13 (2444)

**Desktop (please complete the following information):**
 - Windows
 - Chrome (89), Firefox (92)

**Additional context**
As we are streaming workshops via RTMP we can not resize by hand.
But the bug is not only showing up in headless servers.

**Comment by antobinary** [comment]
The layout system saw very significant refactor in BBB 2.4. Do you encounter issues similar to this on 2.4+?
