### ISSUE TITLE
2.4-beta-4 private and general chat issue

### ISSUE THREAD

**Issue by vasylOstrovskyi** [bigbluebutton/bigbluebutton#13204]
**Describe the bug**
In some very special cases, messages in general chat disappear for some user; general chat area obscured. This happens only in a very special case described below.

**To Reproduce**
1. Open greenlight window, login, select some room. Start session. (ok)
2. Open new tab in _the same_ browser, go to greenlight interface; you are logged in as the same user. (ok) 
3. Join the session; you are joined with the same name as moderator. (ok)
4. in the first tab, select second user and demote them to viewer (ok)
5. write something in general chat. In the second tab, chat message appears (ok)
6. go to the first tab, and write in private chat to second user. In the second tab, the message in general chat disappear (not ok - issue 1)
7. in the second tab, click name to read private message; private message appears (ok)
8. click to view public chat; chat area is cut off - only fist line is visible completely (not ok - issue 2)

**Expected behavior**
In  (6), general chat message must be shown properly; in (8), general chat area must be shown completely

**Screenshots**
Step 5, user receives a message in general chat

![Знімок екрану з 2021-09-13 11-44-35](https://user-images.githubusercontent.com/33595182/133058237-efa38970-9875-4cea-bc60-10a46e50097a.png)

Step 6, private message received, but public message disappeared (issue 1)

![Знімок екрану з 2021-09-13 11-45-11](https://user-images.githubusercontent.com/33595182/133058287-3e627200-7cb8-4752-b7f1-5a20c9e42040.png)

Step 7, user reads private message

![Знімок екрану з 2021-09-13 11-45-36](https://user-images.githubusercontent.com/33595182/133058310-b8779789-9212-4771-a00f-baf4281ef804.png)

Step 8, user try to switch back to general chat (issue 2)

![Знімок екрану з 2021-09-13 11-45-41](https://user-images.githubusercontent.com/33595182/133058354-4e5f5b86-8548-4c4e-b420-6436881000b3.png)

**BBB version:**
2.4-beta-4

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser Chromium
 - Version 92.0.4515.159

**Additional context**
These issues could be reproduced only if there are two tabs in  the same browser, and only if the second user is demoted from moderator

Regards,
 Vasyl

**Comment by antobinary** [comment]
Hi @vasylOstrovskyi 

Thank you for the detailed information!
Issue 1) looks quite similar to https://github.com/bigbluebutton/bigbluebutton/issues/13192 which we recently addressed on 2.4 and plan on backporting to 2.3 once we are sure it was a clear improvement.

Issue 2) had not been previously reported (afaik).
@Tainan404 could you please look into (2) and try to reproduce it?

**Comment by Tainan404** [comment]
Hi, I'm able to reproduce this issue.


https://user-images.githubusercontent.com/15806883/133325001-82a87490-3c53-4851-a6eb-865f315aeb23.mp4

**Comment by Tainan404** [comment]
It's reproducible without the shared id

**Comment by Tainan404** [comment]
Hi, I'm sorry, I was testing it on [develop](https://github.com/bigbluebutton/bigbluebutton/tree/develop) Branch, but in [v2.4](https://github.com/bigbluebutton/bigbluebutton/tree/v2.4.x-release) branch, where my [fix](https://github.com/bigbluebutton/bigbluebutton/pull/13193) was merged the bug doesn't happen anymore.

**Comment by antobinary** [comment]
I have not seen this in a few months now. Let's reopen if anyone is able to reproduce this on BBB 2.4.4+
