### ISSUE TITLE
Sluggishness when switch chats

### ISSUE THREAD

**Issue by jfsiebel** [bigbluebutton/bigbluebutton#13211]
**Describe the bug**
Sometimes when switching between chats 

**To Reproduce**
1. Switch between chats

**Expected behavior**
A more smooth transition.

**Screenshots**

https://user-images.githubusercontent.com/2110278/133152075-4d00770e-dd8b-43c6-b150-7421bb02dd22.mp4

**BBB version:**
BigBlueButton Server 2.4-rc-1 (2451)

**Comment by antobinary** [comment]
@antonbsa let's retest this
