### ISSUE TITLE
Webcam backgrounds not translated via en.json

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#13214]
**Describe the bug**
We received a report that the strings Coffeeshop, Board, Home are not currently localized, so they cannot be translated via Transifex.

![Screenshot from 2021-09-13 19-10-58](https://user-images.githubusercontent.com/6312397/133168703-fb85d88b-9916-40c5-95d1-72424c0f86bf.png)

We should consider our options there - possible options come to mind:
a) replace the titles with numbers - i.e. Background 1, Background 2
b) add the default backgrounds so at least they are localized...

Ideas / opinions are welcome...

**BBB version:**
BigBlueButton 2.4

**Comment by prlanzarin** [comment]
Image background items _were_ prefixed with a localized `Thumbnail` locale up to https://github.com/bigbluebutton/bigbluebutton/pull/13107. 13107 removed the prefix.

If it needs to both show a tooltip and be localized, don't use the file name. Option a) is a good approach.

**Comment by ali-alhaidary** [comment]
@antobinary preferring option a, that is numbering, as naming them could indicate different things to different people in different environments :-)

**Comment by KDSBrowne** [comment]
The only thing I see with option a is the screen readers lose some context, numbers are not very helpful there.

It might be good to just make formatted strings for each button, and if there doesn't happen to be a formatted label then fall back to the numbers.

**Comment by nautilusx** [comment]
@antobinary You can close the issue. The strings are now translatable via Transifex. Thank you.
