### ISSUE TITLE
Beta 2.4 Api Create needs "moderatorPW"

### ISSUE THREAD

**Issue by hahaxd35** [bigbluebutton/bigbluebutton#13220]
I dont know where to place this issue.

**Describe the bug**
got a FAILED on "create"
<response>
<returncode>FAILED</returncode>
<messageKey>validationError</messageKey>
<message>You must provide your password</message>
</response>

**To Reproduce**
create room like in 2.3

**Expected behavior**
 it's much better to generate a secured password instead of believe in good passwords generated from Users. 

**Actual behavior**
create fail's, 
did not appear in "https://docs.bigbluebutton.org/dev/api.html" as "new change"

**Additional context**

**Comment by pedrobmarin** [comment]
@hahaxd35 , thanks for the report.

Hey @paultrudel, is the docs update the only thing that went missing here?
