### ISSUE TITLE
Add a new setting to block removal of presentations

### ISSUE THREAD

**Issue by TiagoJacobs** [bigbluebutton/bigbluebutton#13238]
It would be good to have a setting to disable the delete presentation feature.

This is useful when we want to ensure that presentations will be available for the entire meeting ( in case of pre-uploaded presentations it's more important as moderator don't have the file to re-upload ).

I propose that we add a flag similar to `presentation.allowDownloadable` but with name `presentation.allowRemove`.

When this flag is true, we could hide the delete presentation button:
![image](https://user-images.githubusercontent.com/2075267/133825565-c679eba5-1ad3-415a-96ba-714b9638142f.png)

**Comment by antobinary** [comment]
In https://github.com/bigbluebutton/bigbluebutton/pull/13059 we allowed to remove any presentation.
In my opinion implementing a per-server `settings.yml` parameter would negate the benefits of #13059 

Perhaps we could pass `protected=true` on presentation [pre]upload and keep things flexible. I agree with the use case - pre-uploaded documents may not be at hand to be re-uploaded after an unintentional delete

**Comment by GuiLeme** [comment]
This way, I am going to:
1. add new attribute to presentation named `removable` ;
2. add the both attributes in the pre-upload payload: `downloadable` and `removable` .
