### ISSUE TITLE
[2.4] - Pre-selected breakout room is not the same as suggested

### ISSUE THREAD

**Issue by antonbsa** [bigbluebutton/bigbluebutton#13250]
**Describe the bug**
Sometimes, the pre-selected room is not the same as the moderator suggested. 

**To Reproduce**
1. Go to breakout menu;
2. Allow users to choose a room;
4. Drag and drop users into rooms and create them.

**Video**

https://user-images.githubusercontent.com/56703993/134175249-49652928-5fe2-4a07-b360-dcd39edf54d3.mp4

**Comment by PhMemmel** [comment]
Is this with #13232 applied?

**Comment by antonbsa** [comment]
> Is this with #13232 applied?

Yes. The bug with breakout room assignment only working first time has been fixed but the reported behavior here is happening.

**Comment by antobinary** [comment]
I did not think that the columns matter if you set the :heavy_check_mark: option to pick on your own... Let's see if there are redis messages carrying that info.

**Comment by ramonlsouza** [comment]
> I did not think that the columns matter if you set the  option to pick on your own... Let's see if there are redis messages carrying that info. If the info is not passed already, I think this will be an enhancement request for a release later than 2.4

If `Allow users to choose a breakout room to join` is checked, each user will be assigned to a (random?) room, so it will always receive an invitation. Dragging users to a column should have no effect in this case.

In the example screenshots I did not drag viewers to a column and **VIEWER A** is assigned to **room 5**, while **VIEWER B** is assigned to **room 1**

![Screenshot from 2021-09-23 14-04-17](https://user-images.githubusercontent.com/3728706/134552540-6fee0447-0926-493e-a62c-f703cff7fe1e.png)
![Screenshot from 2021-09-23 14-05-57](https://user-images.githubusercontent.com/3728706/134552544-dbbc76bf-31be-4be8-a1b8-f22dea39c740.png)
![Screenshot from 2021-09-23 14-06-04](https://user-images.githubusercontent.com/3728706/134552547-2983f38a-eba3-4709-b249-8291fd240d16.png)
