### ISSUE TITLE
Screensharing keeps loading on internal network (NAT firewall).

### ISSUE THREAD

**Issue by bspujari** [bigbluebutton/bigbluebutton#13251]
Hi

We have our installation of BBB on a network that is behind a NAT-firewall. The setting of firewall is such that a range of IP's (10.20.X.0) is mapped to an external (public) IP range, while several VLANs are on other IP ranges (10.X.Y.0). The firewall does not support "hair-pining", so the machines on the internal VLANs can't ping the public IP.
 
Going through the very well written documentation of  BBB and taking help of online forums, we could set up our system fairly well to an extent that:

- everything works flawlessly for persons outside our network,
- webcam/audio work fine for persons on the internal VLANs.
- BUT: Screen-sharing keeps loading forever for the participants who are on the internal networks.

Upon inspecting the `about:webrtc` from the computer on the internal network we see two  IPs are shown for Remote Candidate: internal IP and Public IP. 

ICE State | Nominated | Selected | Local Candidate | Remote Candidate | Component ID | Priority | Bytes sent: | Bytes received:
-- | -- | -- | -- | -- | -- | -- | -- | --
succeeded | true | true | 10.31.243.253:50217/udp(host) [non-proxied] | **10.20.60.X**:17910/udp(prflx) | 1 | 9115005270282338000 | 30398 | 94606
succeeded | true | true | 10.31.243.253:50217/udp(host) [non-proxied] | 10.20.60.X:17910/udp(prflx) | 1 | 9115005270282338000 | 30398 | 94606
inprogress | false | false | 10.31.243.253:50217/udp(host) [non-proxied] | **196.1.X.X**:17910/udp(host) | 1 | 9115005270299247000 | 0 | 0
cancelled | false | false | 10.31.243.253:50217/udp(host) [non-proxied] | 196.1.X.X:17910/udp(host) | 1 | 9115005270299247000 | 0 | 0
inprogress | false | false | 10.31.243.253:50217/udp(host) [non-proxied] | 196.1.X.X:17910/udp(host) | 1 | 9115005270299247000 | 0 | 0
cancelled | false | false | 10.31.243.253:50217/udp(host) [non-proxied] | 196.1.X.X:17910/udp(host) | 1 | 9115005270299247000 | 0 | 0

We believe that the machines on the internal VLAN fails to ping external IP and the screen-sharing fails. But what we don't understand that other webrtc components seems to be working alright. 

Here is our config-check

> 
> BigBlueButton Server 2.3.13 (2444)
>                     Kernel version: 5.4.0-81-generic
>                       Distribution: Ubuntu 18.04.5 LTS (64-bit)
>                             Memory: 65831 MB
>                          CPU cores: 72
> 
> /etc/bigbluebutton/bbb-web.properties (override for bbb-web)
> /usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties (bbb-web)
>        bigbluebutton.web.serverURL: https://name-of-server
>                 defaultGuestPolicy: ALWAYS_ACCEPT
>                  svgImagesRequired: true
> 
> /etc/nginx/sites-available/bigbluebutton (nginx)
>                        server_name: name_of_server
>                               port: 80, [::]:80
>                               port: 443 ssl
> 
> /opt/freeswitch/etc/freeswitch/vars.xml (FreeSWITCH)
>                        local_ip_v4: 10.20.60.X
>                    external_rtp_ip: 196.1.X.X
>                    external_sip_ip: 196.1.X.X
> 
> /opt/freeswitch/etc/freeswitch/sip_profiles/external.xml (FreeSWITCH)
>                         ext-rtp-ip: $${external_rtp_ip}
>                         ext-sip-ip: $${external_sip_ip}
>                         ws-binding: 196.1.X.X:5066
>                        wss-binding: 196.1.X.X:7443
> 
> /usr/local/bigbluebutton/core/scripts/bigbluebutton.yml (record and playback)
>                      playback_host: name_of_server
>                  playback_protocol: https
>                             ffmpeg: 4.2.4-1ubuntu0.1bbb2~18.04
> 
> /etc/bigbluebutton/nginx/sip.nginx (sip.nginx)
>                         proxy_pass: 196.1.X.Y
>                           protocol: http
> 
> /usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml (Kurento SFU)
>                         kurento.ip: 196.1.X.Y
>                        kurento.url: ws://127.0.0.1:8888/kurento
>                     kurento.sip_ip: 196.1.X.Y
>                     localIpAddress: 10.20.60.X
>                recordScreenSharing: true
>                      recordWebcams: true
>                   codec_video_main: VP8
>                codec_video_content: VP8
> 
> /usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml (HTML5 client)
>                              build: 1842
>                         kurentoUrl: wss://name-of-server/bbb-webrtc-sfu
>                   enableListenOnly: true
>                     sipjsHackViaWs: true
> 
> /usr/share/bbb-web/WEB-INF/classes/spring/turn-stun-servers.xml (STUN Server)
>                               stun: stun.l.google.com:19302
> 
> 
> \# Potential problems described below
> 
> 
> \#
> \# Warning: Failed to verify STUN server at stun.l.google.com 19302 with command
> \#
> \#    stunclient --mode full --localport 30000 stun.l.google.com 19302
> \#
> 

Here is our respond to stun query:

>  $stunclient --mode full --localport 30000 stun.l.google.com 19302
> Binding test: success
> Local address: 10.20.60.X:30000
> Mapped address: 196.1.X.Y:30000
> Behavior test: fail
> Filtering test: fail

Any help towards resolving this issue is highly appreciated. 

Thanks

**Comment by rezav** [comment]
Hi, we have the same problem with bbb 2.3. bbb 2.2 works without issues though. We would appreciate any suggestions.
