### ISSUE TITLE
Change UI colors

### ISSUE THREAD

**Issue by bigbluebutton-issue-import** [bigbluebutton/bigbluebutton#1326]
Originally reported on Google Code with ID 571

```
Can we change the background colors of the windows, title bars etc - like main window,
presentation window?

Please le us know where do we change the code for this?

```

Reported by `vkc108` on 2010-07-08 08:51:44

**Comment by vipinMeravi** [comment]
> Originally reported on Google Code with ID 571
> 
> ```
> Can we change the background colors of the windows, title bars etc - like main window,
> presentation window?
> 
> Please le us know where do we change the code for this?
> ```
> 
> Reported by `vkc108` on 2010-07-08 08:51:44

There is an answer related to your question, have a look [Dynamically background color change](https://stackoverflow.com/questions/62600066/bigbluebutton-change-branding-dynamically-on-different-conference-without-changi), I think it will help you.

**Comment by matiasilva** [comment]
Thanks for posting this. Though, I would hope in 10 years they would have figured out something :-)
