### ISSUE TITLE
[2.3.14] Cannot connect audio via Firefox (ICE 1007 error)

### ISSUE THREAD

**Issue by miztaka** [bigbluebutton/bigbluebutton#13276]
**Describe the bug**
After update BBB to 2.3.14, Audio connection (echo test) failed with ICE 1007 error when you join the meeting.
It happens when you use Firefox and with configuration `media.peerconnection.ice.default_address_only=true`

It worked all fine with production instance which is BBB 2.3.12.

Probably root cause is Freeswitch only returns local IP for ICE candidate.
In case of production (BBB 2.3.12), it return global IP which we set in `external_rtp_ip` and `external_sip_ip`

**To Reproduce**
1. Join the meeting (In my case via greenlight)
2. Connect with audio
3. Echo test loading dialog shows up...
4. See error ICE 1007 after a while

**Expected behavior**
Audio should be connected

**Actual behavior**
Audio is not connected

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser Firefox
 - Version 92.0

**Additional context**

This is webrtc log on Firefox.

Local SDP (Offer)
v=0
o=mozilla...THIS_IS_SDPARTA-92.0 3009965923707785404 0 IN IP4 0.0.0.0
s=-
t=0 0
a=sendrecv
a=fingerprint:sha-256 13:F7:24:90:33:E7:05:E3:8C:5E:60:B5:A8:94:E7:A6:F0:D6:43:91:FE:E9:F6:33:BC:16:12:22:92:BF:C5:CB
a=group:BUNDLE 0
a=ice-options:trickle
a=msid-semantic:WMS *
m=audio 8127 UDP/TLS/RTP/SAVPF 109 9 0 8 101
c=IN IP4 49.224.76.59
a=candidate:0 1 UDP 2122252543 192.168.43.228 51814 typ host
a=candidate:3 1 TCP 2105524479 192.168.43.228 9 typ host tcptype active
a=candidate:0 2 UDP 2122252542 192.168.43.228 48622 typ host
a=candidate:3 2 TCP 2105524478 192.168.43.228 9 typ host tcptype active
a=candidate:2 1 UDP 1686052351 49.224.76.xxx 8127 typ srflx raddr 192.168.43.228 rport 51814
a=candidate:2 2 UDP 1686052350 49.224.76.xxx 7600 typ srflx raddr 192.168.43.228 rport 48622
a=candidate:1 2 UDP 1686052862 49.224.76.xxx 7600 typ srflx raddr 192.168.43.228 rport 48622
a=candidate:1 1 UDP 1686052863 49.224.76.xxx 8127 typ srflx raddr 192.168.43.228 rport 51814
a=sendrecv
a=end-of-candidates
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=extmap:2/recvonly urn:ietf:params:rtp-hdrext:csrc-audio-level
a=extmap:3 urn:ietf:params:rtp-hdrext:sdes:mid
a=fmtp:109 maxplaybackrate=48000;stereo=1;useinbandfec=1
a=fmtp:101 0-15
a=ice-pwd:6a4a76e65c139e8da84bc09ba72da53e
a=ice-ufrag:abb1c147
a=mid:0
a=msid:{28bc3f21-f520-4f2b-888e-e19effd6762f} {7d78e67d-db6d-43c0-9d41-4d23fbcfe3c9}
a=rtcp:7600 IN IP4 49.224.76.xxx
a=rtcp-mux
a=rtpmap:109 opus/48000/2
a=rtpmap:9 G722/8000/1
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:101 telephone-event/8000
a=setup:actpass
a=ssrc:1318058115 cname:{1cff6574-b589-46c4-aa7d-620809bcdb68}

Remote SDP (Answer)

v=0
o=FreeSWITCH 1632351665 1632351666 IN IP4 10.15.8.xxx
s=-
t=0 0
a=sendrecv
a=msid-semantic:WMS tcrl2iXNBy4eC8uDD9swM2fxq23agWkz
m=audio 23506 UDP/TLS/RTP/SAVPF 109 101
c=IN IP4 10.15.8.xxx
a=candidate:3188503252 1 udp 2130706431 10.15.8.xxx 23506 typ host generation 0
a=sendrecv
a=end-of-candidates
a=fingerprint:sha-256 05:0A:6C:1E:32:E7:A6:49:38:56:A3:93:44:8A:F5:66:C9:69:FE:5B:47:EC:31:86:85:E3:A3:D8:64:F9:08:7C
a=fmtp:109 maxplaybackrate=0;stereo=1;useinbandfec=1
a=ice-pwd:xxxxxxxxxxxxxxxxxxxxxxxxxxxxx
a=ice-ufrag:Acfc4kAldtmkgwK5
a=ptime:20
a=rtcp:23506 IN IP4 10.15.8.xxx
a=rtcp-mux
a=rtpmap:109 opus/48000/2
a=rtpmap:101 telephone-event/8000
a=setup:active
a=ssrc:4115712315 cname:ZCLRKzvbYqgqpAUT
a=ssrc:4115712315 msid:tcrl2iXNBy4eC8uDD9swM2fxq23agWkz a0
a=ssrc:4115712315 mslabel:tcrl2iXNBy4eC8uDD9swM2fxq23agWkz
a=ssrc:4115712315 label:tcrl2iXNBy4eC8uDD9swM2fxq23agWkza0

**Comment by mariogasparoni** [comment]
Hi @miztaka  , thanks for your report.
Could you please test it in https://test.bigbluebutton.org ?

Using Firefox 92, this works for me (i also set `media.peerconnection.ice.default_address_only=true`).

**Comment by krim404** [comment]
can not confirm this issue. even when forcing TURN usage, everything works as expected.

Tested with Firefox 92 on MacOS 11.6 on test.bigbluebutton.org and a local instance.

**Comment by miztaka** [comment]
It worked on test.bigbluebutton.org. Wonder if any config change around freeswitch between 2.3.12 and 2.3.14? 
We have puppet to manage the config.

**Comment by prlanzarin** [comment]
> It worked on test.bigbluebutton.org. Wonder if any config change around freeswitch between 2.3.12 and 2.3.14?

Have you verified that the correct IP is set in vars.xml#external_rtp|sip_ip in the problematic server?
There was a FreeSWITCH update in the latest release, so a config or two was probably ovewritten.

**Comment by miztaka** [comment]
@prlanzarin Yes, double checked that those config are correct ip, also confirmed there is no config regession by puppet.
I wonder why FreeSWITCH does not respond external IP in ICE candidate, only when browser have config `media.peerconnection.ice.default_address_only=true` ..

**Comment by mariogasparoni** [comment]
> @prlanzarin Yes, double checked that those config are correct ip, also confirmed there is no config regession by puppet.
> I wonder why FreeSWITCH does not respond external IP in ICE candidate, only when browser have config `media.peerconnection.ice.default_address_only=true` ..


Setting up FreeSWITCH behind NAT is quite painful, you can play with ACLs or use some specific configs.
I would ask you to recheck this: https://docs.bigbluebutton.org/admin/configure-firewall.html#configure-a-dummy-nic-if-required

bbb-install.sh should deal with this for you.

**Comment by miztaka** [comment]
noted, yeah our config is based on bbb-install.sh. Does anyone know which version of FreeSWITCH is build in 2.3.12 and 2.3.14?

**Comment by miztaka** [comment]
Hi, this issue seems to be fixed by setting `ext-rtp-ip` on `verto.conf.xml`. Thanks
