### ISSUE TITLE
Select whiteboard objects, move them and Bring forward/backward

### ISSUE THREAD

**Issue by more-zamani** [bigbluebutton/bigbluebutton#13285]
Hi 
I want a feature request for the whiteboard of BBB

Please add the movement ability and "Bring forward/backward" feature for shapes and other objects on the whiteboard.

**Comment by ffdixon** [comment]
This feature is coming in BigBlueButton 2.6 as we integrate tldraw (see https://tldraw.com/) into BigBlueButton.

**Comment by ali-alhaidary** [comment]
There is no Arabic in tidraw

Ali

**Comment by ramonlsouza** [comment]
closed by #14994
