### ISSUE TITLE
Support for Ubuntu 20.04

### ISSUE THREAD

**Issue by aditnanda** [bigbluebutton/bigbluebutton#13288]
**Is your feature request related to a problem? Please describe.**
Previously I have also used this bigbluebutton on a server with Ubuntu 18.04 OS which runs very smoothly, but currently the server I have has Ubuntu 20.04 OS where the OS is not yet supported by BBB, I hope that in the next version there will be support for the Ubuntu 20.04 OS, thank you

**Comment by ffdixon** [comment]
We won't have support for Ubuntu 20.04 in the next version of BigBlueButton (2.5), but we should be able to move to Ubuntu 20.04 in a subsequent release.
