### ISSUE TITLE
Add arrow tools to BigBlueButton whiteboard

### ISSUE THREAD

**Issue by more-zamani** [bigbluebutton/bigbluebutton#13284]
Hi BBB team
I want to make a feature request to add an ability to draw an arrow in various thicknesses on the whiteboard like this:

https://s4.uupload.ir/files/111_mjpa.png

It's useful more math classes.

**Comment by ffdixon** [comment]
This feature is coming in BigBlueButton 2.6.

**Comment by ramonlsouza** [comment]
closed by #14994
