### ISSUE TITLE
github-project links to www.bigbluebutton.org which has bad cert and redirects

### ISSUE THREAD

**Issue by fwolfst** [bigbluebutton/bigbluebutton#13296]
The github-projects "about" section (top right when browsed with a desktop on https://github.com/bigbluebutton/bigbluebutton/) mentions www.bigbluebutton.org.

As of today (2021-09-26), that server unfortunately serves the wrong certificate (for the domain without www : bigbluebutton.org), and will anyway redirect to the domain without www subdomain.

Easiest solution would thus be: change the repos about section to link to https://bigbluebutton.org directly.

**Comment by ffdixon** [comment]
Thanks -- fixed!
