### ISSUE TITLE
Freeswitch 100 percent ram usage

### ISSUE THREAD

**Issue by mohgh** [bigbluebutton/bigbluebutton#13294]
We are running a cluster of 200 bigbluebutton virtual machines (8 core, 32gb ram) behind 5 scalelite servers and 5 turn servers. We have recently upgraded to 2.3.13 and an issue is happening randomly in one or two servers daily. Freeswitch is consuming all the ram available to it (32gb) and the audio won't connect on the user side. This happens very randomly and not necessarily on a high load. Restarting the freeswitch will resolve the issue. This issue happened also in 2.3.9 version so we upgraded to 2.3.13 but the issue persists.

I have looked at the freeswitch logs and there is no error log.

Please tell me if I should provide any logs or evidance.

**Comment by mohgh** [comment]
![error](https://user-images.githubusercontent.com/8774487/134794374-679415ce-e1b3-489d-989b-ee5770ab8c00.png)

**Comment by ffdixon** [comment]
Hi @mohgh -- thanks for reporting this.  

> .. and the audio won't connect on the user side 

Do you have [sipjsHackViaWs](https://docs.bigbluebutton.org/2.2/install.html#configure-freeswitch-for-using-ssl) enabled?  

This gets around a bug in FreeSWITCH that causes web socket connections over SSL to randomly lock until existing users disconnect.  By proxing the incoming web sockets connections over SSL by nginx (and then relaying them internally over a non-SSL connection) we were able to work around this issue with FreeSWITCH.

**Comment by mohgh** [comment]
@ffdixon
No. As I was not aware of this issue and sipjsHackViaWs was not enabled.
I will test this workaround on my cluster and let you know the result.
Thank you very much.

**Comment by GhaziTriki** [comment]
@mohgh I can ass an usual RAM usage. Do you have any document conversion failing in your logs?

**Comment by mohgh** [comment]
@ffdixon 
The issue seems to be resolved after I enabled the hack.

@GhaziTriki 
Where is the log for converting documents?

**Comment by aguerson** [comment]
Hi @ffdixon 
Why don't you force the use of sipjsHackViaWs by default ?
@mohgh Does the problem persist if you reboot the BBB instance one time a day ?
Regards,
Aurelien

**Comment by aguerson** [comment]
@ffdixon @pedrobmarin 
In 2.2.X I used the Hack. It worked very well.
But in 2.3.x, I thinked that the problem was resolved. Why do not force the hack in the conf ? ( whith the good change in bbb-install.sh )

**Comment by ffdixon** [comment]
> We have recently upgraded to 2.3.13 and an issue is happening randomly in one or two servers daily.

We recommend re-running [bbb-install.sh](https://github.com/bigbluebutton/bbb-install) command again when upgrading to a newer version of 2.3.  This will update the values in [sipjsHackViaWs](https://github.com/bigbluebutton/bbb-install/blob/master/bbb-install.sh#L922). See

  https://docs.bigbluebutton.org/2.3/install.html#upgrading-bigbluebutton-23

**Comment by mohgh** [comment]
> @mohgh Does the problem persist if you reboot the BBB instance one time a day ? Regards, Aurelien
@aguerson
I don't think restarting once a day guarantees this problem won't happen as it happens randomly.
@ffdixon 
We have to install bbb manualy because our servers are behind a firewall and access to the internet is limited.

**Comment by mohgh** [comment]
I will close this issue because using the hack has fixed my issue.

**Comment by pielonet** [comment]
Hi,
I faced this issue today on a server that had been running for over two weeks  BBB 2.5.12
Freeswitch was suddenly consuming the whole RAM (16GB).
I had to restart BBB in order to fix the issue.
We have setup `sipjsHackViaWs` to be `false` since setting it to true prevents users from connecting with audio (error 1006) at Scaleway.
Any other suggestion ?
Kind regards,
Thierry

**Comment by pielonet** [comment]
... what logs should I lookup for Freeswitch apart from `/opt/freeswitch/log/freeswitch.log` ?

**Comment by pielonet** [comment]
Hi,

I eventually had it working also on a machine behind NAT although I got some warnings (about usinh http rather than https for proxying) when restarting BBB.

Thank you for your support,
Thierry
