### ISSUE TITLE
Embedding a Website in BigBlueButton as a Presentation (v2.4)

### ISSUE THREAD

**Issue by Ashrafhaq** [bigbluebutton/bigbluebutton#13293]
Hi BBB team,
I am requesting to BigBlueButton team to add 
1. Website Embedding option as a presentation object
2. Multiple whiteboards to present multiple presentations
3. Easy scrolling option for a presentation page

I describe in detail in the video

https://drive.google.com/file/d/15MrOcKa7thVXs8IFaRSMKTqKuGdkULxO/view?usp=sharing

**Comment by Ashrafhaq** [comment]
@kishba @znerol @lfzawacki @kepstin

**Comment by prlanzarin** [comment]
If you want to make an actual feature request:
  - Step 0: **do not call out specific people** unless it makes sense (sure doesn't in this scenario) 
  - Step 1: search for duplicates in the issue tracker
  - Step 2: describe them appropriately
  - Step 3: don't add multiple things to the same issue
