### ISSUE TITLE
Ability to setup the echo test message

### ISSUE THREAD

**Issue by b3** [bigbluebutton/bigbluebutton#13338]
I have looked up the configuration documentation, available at <https://docs.bigbluebutton.org/admin/customize.html>, without finding anything which enables to change the message which appears when doing the echo test.

If I didn't miss anything it would be nice to be able to adapt sentences printed at that stage to adapt them to the public using the instance.

The default sentences have been misinterpreted by some of my users which did not understand that they should speak and ear what they just said. They reported that the audio connection was failing, while it was OK but they just did not understand what to do.

**Comment by PhMemmel** [comment]
You can just edit the locale file(s) for your language in `/usr/share/meteor/bundle/programs/web.browser/app/locales` and restart `bbb-html5` service. These changes will be overriden by each update though.

**Comment by b3** [comment]
Thx.
