### ISSUE TITLE
certificate has expired with nodejs

### ISSUE THREAD

**Issue by yazilimevde** [bigbluebutton/bigbluebutton#13353]
i have a bigbluebutton meeting url. I access via postman and browser without any problem and I get the success code. But when I send https get request to the url in my nodejs project, I get certificate has expired error. What can be the problem?

```
let createApiUrl = `https://bbb.example.com/bigbluebutton/api/create?name=${meetingName}&logoutURL=${logoutUri}&record=true&meetingID=${meetingId}&attendeePW=${attendeePW}&
moderatorPW=${moderatorPW}&checksum=${checkSum}`;
response = await new Promise((resolve, reject) => {
  return HTTP.call("GET", `${createApiUrl}`, {}, (error, response) => {
    if (error) {
      reject(error);
    } else {
      resolve(response);
    }
  });
});
```
Error message =>
Error: certificate has expired
at TLSSocket.
at emitNone
at TLSSocket.emit
at TLSSocket._finishInit
at TLSWrap.ssl.onhandshakedone code: 'CERT_HAS_EXPIRED' }

**Comment by GhaziTriki** [comment]
Are you using BBB 2.2.x with let's encrypt?
If yes check this : https://groups.google.com/g/bigbluebutton-setup/c/U3Xj_hQSe5s
(no need to duplicate issues https://github.com/bigbluebutton/bbb-install/issues/432)

**Comment by yazilimevde** [comment]
Thank you so much!! @GhaziTriki
