### ISSUE TITLE
Do not display the presentation file in BigBlueButton

### ISSUE THREAD

**Issue by alialic** [bigbluebutton/bigbluebutton#13375]
The presentation file is not displayed for any of my servers

![Untitled](https://user-images.githubusercontent.com/65443862/135713806-52bb807c-9f61-47db-b32f-87301cd7ced6.png)

**Comment by prlanzarin** [comment]
Search the mailing lists. There are dozen of new threads in the past three days with the exact same issue as yours (Let's Encrypt cross-signed root CA expiring on Sept 30); and it's not a BigBlueButton issue.

**Comment by alialic** [comment]
thanks for attention,
can you help me more ?
I can't fixed this problem.

**Comment by alialic** [comment]
can you give me a link for this problem?

**Comment by vova-zush** [comment]
https://github.com/bigbluebutton/bigbluebutton/issues/6139#issuecomment-932679845

**Comment by alialic** [comment]
thank you
