### ISSUE TITLE
Let's Encrypt SSL not showing presentation default or whiteboard but ZeroSSL works fine

### ISSUE THREAD

**Issue by SaeedFazlollahzadeh** [bigbluebutton/bigbluebutton#13377]
As you know, Let's Encrypt Root X3 CA has expired a couple of days ago and the issue has raised after this incident.
**First of all, I should say I'm sorry because I'm not sure whether this issue can is related to BBB or not.
If you need the real domain, I can name it the real domain of my website using BBB.**

**Describe the bug**
Issue is when I use Let's Encrypt SSL in nginx config file, I see the class like this: https://imgur.com/LZZc7qe (incorrect)
But when I change it to ZeroSSL certificate, I see like this: https://imgur.com/ewiw2DC

**To Reproduce**
Setup a BBB with Let's Encrypt, then join a class.
You'll see the image as uploaded in screenshot section.

**Expected behavior**
Full buttons as expected like before.
Expected like this: https://imgur.com/ewiw2DC

**Actual behavior**
Less buttons than expected.

**Screenshots**
That's it: https://imgur.com/LZZc7qe

**Desktop (please complete the following information):**
 - OS: Ubuntu Desktop 20.04
 - Browser Chrome
 - Version 94.0.4606.54

**Additional context**
The issue is only when I use Let's Encrypt SSL certificate in `nginx`.
But as soon as I change certificates to ZeroSSL, the issue resolves.

I cannot use ZeroSSL due to some restrictions, and the advantage of Let's Encrypt is that it renews itself without any worries.

Are there any ways to fix this issue?

**Comment by datapack** [comment]
I have the same issue on three servers.
But I can't find a solution.

**Comment by datapack** [comment]
this may be related to the expiration of the DST Root CA X3 certificate.

To check if this is the case
run
journalctl -f -u bbb-html5
and restart BigBlueButton:
bbb-config --restart
If you see the lines like

systemd_start.sh[30265]: error: No file found. Error: certificate has expired
systemd_start.sh[30265]: error: Error parsing image size. Error: certificate has expired.

then it may be the case.

To fix the problem
Make sure the ISRG Root X1 certificate is present on your system:
grep ISRG_Root_X1 /etc/ca-certificates.conf
If it is not there, you should upgrade the ca-certificates package and the OpenSSL to the latest version possible.
Comment out the expired DST Root CA X3 certificate in /etc/ca-certificates.conf with an exclamation mark like this:
!mozilla/DST_Root_CA_X3.crt
Update the ca-certificates:
sudo update-ca-certificates
Make the Node.js use the system-wide CA certificates. For this purpose at the end of the file /usr/share/meteor/bundle/systemd_start.sh add the parameter --use-openssl-ca like this:
PORT=3000 /usr/share/$NODE_VERSION/bin/node --use-openssl-ca --max-old-space-size=4096 --max_semi_space_size=128 main.js
After that restart, the BigBlueButton again, start some sessions,s and watch the logs. The lines about the expired certificate should not appear. At least, it worked in my case. Hope that helps somebody.

**Comment by SaeedFazlollahzadeh** [comment]
> this may be related to the expiration of the DST Root CA X3 certificate.
> 
> To check if this is the case run journalctl -f -u bbb-html5 and restart BigBlueButton: bbb-config --restart If you see the lines like
> 
> systemd_start.sh[30265]: error: No file found. Error: certificate has expired systemd_start.sh[30265]: error: Error parsing image size. Error: certificate has expired.
> 
> then it may be the case.
> 
> To fix the problem Make sure the ISRG Root X1 certificate is present on your system: grep ISRG_Root_X1 /etc/ca-certificates.conf If it is not there, you should upgrade the ca-certificates package and the OpenSSL to the latest version possible. Comment out the expired DST Root CA X3 certificate in /etc/ca-certificates.conf with an exclamation mark like this: !mozilla/DST_Root_CA_X3.crt Update the ca-certificates: sudo update-ca-certificates Make the Node.js use the system-wide CA certificates. For this purpose at the end of the file /usr/share/meteor/bundle/systemd_start.sh add the parameter --use-openssl-ca like this: PORT=3000 /usr/share/$NODE_VERSION/bin/node --use-openssl-ca --max-old-space-size=4096 --max_semi_space_size=128 main.js After that restart, the BigBlueButton again, start some sessions,s and watch the logs. The lines about the expired certificate should not appear. At least, it worked in my case. Hope that helps somebody.

Thank you a lot for the solution:D

My certificate was not expired (in fact I did renew and renewal worked but the issue was with Let's Encrypt only).
It works and solved my problem:)

I was thinking about a way to find and remove X3 certificate, but I did not know what to do for that.

**Comment by SaeedFazlollahzadeh** [comment]
> this may be related to the expiration of the DST Root CA X3 certificate.
> 
> To check if this is the case run journalctl -f -u bbb-html5 and restart BigBlueButton: bbb-config --restart If you see the lines like
> 
> systemd_start.sh[30265]: error: No file found. Error: certificate has expired systemd_start.sh[30265]: error: Error parsing image size. Error: certificate has expired.
> 
> then it may be the case.
> 
> To fix the problem Make sure the ISRG Root X1 certificate is present on your system: grep ISRG_Root_X1 /etc/ca-certificates.conf If it is not there, you should upgrade the ca-certificates package and the OpenSSL to the latest version possible. Comment out the expired DST Root CA X3 certificate in /etc/ca-certificates.conf with an exclamation mark like this: !mozilla/DST_Root_CA_X3.crt Update the ca-certificates: sudo update-ca-certificates Make the Node.js use the system-wide CA certificates. For this purpose at the end of the file /usr/share/meteor/bundle/systemd_start.sh add the parameter --use-openssl-ca like this: PORT=3000 /usr/share/$NODE_VERSION/bin/node --use-openssl-ca --max-old-space-size=4096 --max_semi_space_size=128 main.js After that restart, the BigBlueButton again, start some sessions,s and watch the logs. The lines about the expired certificate should not appear. At least, it worked in my case. Hope that helps somebody.

Is that required to add `--use-openssl-ca` to `/usr/share/meteor/bundle/systemd_start.sh`? And why to add that?
Before I add that, how does nodejs checks CA Roots?

**Comment by SaeedFazlollahzadeh** [comment]
> this may be related to the expiration of the DST Root CA X3 certificate.
> 
> To check if this is the case run
>
> journalctl -f -u bbb-html5
>
> and restart BigBlueButton:
>
> bbb-config --restart

Please edit the last line to:
```
bbb-conf --restart
```
Because `bbb-config` is not a package for BBB.

**Comment by dongzhaolong** [comment]
这个问题，我最近也遇到过，查了一下相关资料，确认是服务器的Encrpt的问题，是因为Let's Encrpt提供正到ISRG Root。根据Let's Encrypt，其服务使用的一个由IdenTrust的根证书将于 2021 年 9 月 1 日获得赠金。让我们用自己的名义加密，但称为 ISRG Root X1 的根证书为到期做好准备，它在很多设备上得到了支持，存在一个问题：由于 Android 系统缓慢的更新形势，数百万运行的Android 7.1.1以下版本的设备将无法使用让我们的加密证书连接网站。
由此，按@fernandoheb（费尔南多·安德拉德博士）的处理说明，是对的。
apt-get 删除 certbot
apt-get install snapd
snap install --classic certbot
ln -s /snap/bin/certbot /usr/bin/certbot
certbot 更新 --force-renewal --cert-name www.xxx.com --首选链“ISRG 根 X1”
通过上面的方式，这个问题得到了解决。谢谢费尔南多·安德拉德博士！
