### ISSUE TITLE
[2.4] - Webcam sharing does not complete when webcam dataSaving setting is changed

### ISSUE THREAD

**Issue by antonbsa** [bigbluebutton/bigbluebutton#13370]
**Describe the bug**
By setting this option to "off", the user is blocked on "webcam sharing is starting" and this cannot be cancelled. No error logs.

**To Reproduce**
1. Join the meeting;
2. Click on connection status button;
3. Turn off "Enable other participants webcams";
4. Click to start sharing webcam;

**Video**

https://user-images.githubusercontent.com/56703993/135660471-2f65ecad-1cbf-4a49-93e3-4fad05c6a416.mp4

**Comment by prlanzarin** [comment]
To put another variant of this (with, probably, the same underlying cause): if you have your camera shared and enable Data Savings, it'll get unshared.
That's unintended behavior. It's a regression of the feature introduced in https://github.com/bigbluebutton/bigbluebutton/pull/12569
