### ISSUE TITLE
BigBlueButton Server 2.3.14 (2457) playback returns a 404 error when trying to play a transferred recording recorded without a camera (no video directory in recording directory)

### ISSUE THREAD

**Issue by kotovi** [bigbluebutton/bigbluebutton#13376]
BigBlueButton Server 2.3.14 (2457) playback returns a 404 error when trying to play a transferred recording recorded without a camera (no video directory in recording directory).
Empirically copying the directory solves the problem( cp ./audio/audio.webm ./video/webcams.webm) .
Please fix it, killed all day (

**Comment by pedrobmarin** [comment]
Duplicate of https://github.com/bigbluebutton/bbb-playback/issues/112
