### ISSUE TITLE
 i can't see whiteboard in bigbluebutton  Whiteboard does not appear in screen

### ISSUE THREAD

**Issue by mahdiyardiyanat** [bigbluebutton/bigbluebutton#13383]
Hello to all
after installation bbb in ubuntu 16.04 
This program installed and worked well on my server, but after a few days there was a problem that I could not upload a file or write to the whiteboard 
root@server11:~# sudo bbb-conf --check

BigBlueButton Server 2.2.36 (2416)
                    Kernel version: 4.4.0-210-generic
                      Distribution: Ubuntu 16.04.7 LTS (64-bit)
                            Memory: 16431 MB
                         CPU cores: 12

/usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties (bbb-web)
       bigbluebutton.web.serverURL: https://server11.lmsschool.ir
                defaultGuestPolicy: ALWAYS_ACCEPT
                 svgImagesRequired: true

/etc/nginx/sites-available/bigbluebutton (nginx)
                       server_name: server11.lmsschool.ir
                              port: 80, [::]:80
                              port: 443 ssl

/opt/freeswitch/etc/freeswitch/vars.xml (FreeSWITCH)
                       local_ip_v4: 91.98.31.164
                   external_rtp_ip: 91.98.31.164
                   external_sip_ip: 91.98.31.164

/opt/freeswitch/etc/freeswitch/sip_profiles/external.xml (FreeSWITCH)
                        ext-rtp-ip: $${local_ip_v4}
                        ext-sip-ip: $${local_ip_v4}
                        ws-binding: 91.98.31.164:5066
                       wss-binding: 91.98.31.164:7443

/usr/local/bigbluebutton/core/scripts/bigbluebutton.yml (record and playback)
                     playback_host: server11.lmsschool.ir
                 playback_protocol: https
                            ffmpeg: 4.2.4-1ubuntu0.1bbb1~16.04.1

/etc/bigbluebutton/nginx/sip.nginx (sip.nginx)
                        proxy_pass: 91.98.31.164
                          protocol: http

/usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml (Kurento SFU)
                        kurento.ip: 91.98.31.164
                       kurento.url: ws://127.0.0.1:8888/kurento
                    kurento.sip_ip: 91.98.31.164
                    localIpAddress: 91.98.31.164
               recordScreenSharing: true
                     recordWebcams: true
                  codec_video_main: VP8
               codec_video_content: VP8

/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml (HTML5 client)
                             build: 1157
                        kurentoUrl: wss://server11.lmsschool.ir/bbb-webrtc-sfu
                  enableListenOnly: true
                    sipjsHackViaWs: true

/usr/share/bbb-web/WEB-INF/classes/spring/turn-stun-servers.xml (STUN Server)
                              stun:stun.l.google.com:19302

# Potential problems described below

root@server11:~#

**Comment by shahawiz** [comment]
Check this maybe fix your issue : https://hossamelshahawi.com/2021/10/01/bigbluebutton/

**Comment by mahdiyardiyanat** [comment]
> 
> 
> Check this maybe fix your issue : https://hossamelshahawi.com/2021/10/01/bigbluebutton/

My problem was resolved after reinstalling the SSL certificate, thank you very much for your help

**Comment by dongzhaolong** [comment]
这个问题，我最近也遇到过，查了一下相关资料，确认是服务器的Encrpt的问题，是因为Let's Encrpt提供正到ISRG Root。根据Let's Encrypt，其服务使用的一个由IdenTrust的根证书将于 2021 年 9 月 1 日获得赠金。让我们用自己的名义加密，但称为 ISRG Root X1 的根证书为到期做好准备，它在很多设备上得到了支持，存在一个问题：由于 Android 系统缓慢的更新形势，数百万运行的Android 7.1.1以下版本的设备将无法使用让我们的加密证书连接网站。
由此，按@fernandoheb（费尔南多·安德拉德博士）的处理说明，是对的。
apt-get 删除 certbot
apt-get install snapd
snap install --classic certbot
ln -s /snap/bin/certbot /usr/bin/certbot
certbot 更新 --force-renewal --cert-name www.xxx.com --首选链“ISRG 根 X1”
通过上面的方式，这个问题得到了解决。谢谢费尔南多·安德拉德博士！
