### ISSUE TITLE
getMeetings returns wrong number of participantCount

### ISSUE THREAD

**Issue by depava95** [bigbluebutton/bigbluebutton#13394]
**Describe the bug**
getMeetings returns the number of participants with a delay after the webhook is received.

**To Reproduce**
1. Create a meeting.
2. Join this meeting.
3. Left this meeting.
4. Wait for the webhook "user-left".

**Expected behavior**
Response getMeetings -> find target meeting  -> shows participantCount: 0

**Actual behavior**
Response getMeetings -> find target meeting ->  shows participantCount: 1

**Additional context**
Version:  BigBlueButton Server 2.3.1 (2218)

**Comment by ffdixon** [comment]
@depava95 Would it be possible for you to test this in the latest build of BigBlueButton 2.5 and let us know if it's still there.

**Comment by gustavotrott** [comment]
It seems both 2.5 and 2.6 have a strong delay to update the `participantCount`.

When a user leave the meeting:
- It waits between 10 and 20 seconds to remove users from the UI Userlist (to prevent from removing users facing connection instability)
- Once the user was removed from the Userlist, the API wait 1 more minute to remove the user from the memory (waiting for re-connection attempts)

And the current `participantCount` considers all users that are in the memory.

I think we can't change the current behavior in BBB 2.5, but I'll send a improvement for BBB 2.6 to make `participantCount` count only users that are still in the Userlist and then it will be synched with the UI user list.

**Comment by gustavotrott** [comment]
Fixed in #15993.
