### ISSUE TITLE
Bad fonts in PDF presentation when using Chrome

### ISSUE THREAD

**Issue by rriscado** [bigbluebutton/bigbluebutton#13419]
When I'm using google Chrome, some words are broken.

I'm in BBB 2.3.12

**Slide 25 in Original PDF File:**
![image](https://user-images.githubusercontent.com/14829973/136101636-dfce1d23-3803-4420-9b95-a55dcbe7899d.png)

**Slide 25 after loaded in BBB using chrome:**
![image](https://user-images.githubusercontent.com/14829973/136101620-5e94534c-09d7-4804-8170-fc1534c6a193.png)

**Slide 25 after loaded in BBB using Firefox:**
![image](https://user-images.githubusercontent.com/14829973/136101697-fbcfb57a-70c1-4ae5-9254-d18679902008.png)

**Original PDF File**
[AULA 1.pdf](https://github.com/bigbluebutton/bigbluebutton/files/7289280/AULA.1.pdf)

**Comment by prlanzarin** [comment]
This is a Chromium issue, see: https://bugs.chromium.org/p/chromium/issues/detail?id=1253952.

They're working on a fix for it and you can track the status there. Thanks for the report anyways.
