### ISSUE TITLE
Poll question on slide not visible, when chrome flags' dark mode is enabled (chrome 94).

### ISSUE THREAD

**Issue by Samarth-Ashish** [bigbluebutton/bigbluebutton#13444]
**Describe the bug**
When dark mode (in chrome experiments >"Force Dark Mode for Web Contents" ) is enabled, the poll question that appears on the white slide has default white fonts (i guess) on white slide background, hence the question in poll is invisible. Such does not happen when "Force Dark Mode for Web Contents" is set to default (disabled). But, when teacher uses color marker on this poll-question-slide, it is clearly visible, just the pre-types-fonts are not visible. And, other than poll-question-slide, rest slides appear fine & normal.

**To Reproduce**
1. Go to 'chrome://flags' (on chrome 94).
2. In the 'Search flag' bar, type and search 'Force Dark Mode for Web Contents'.
3. Set this option to 'enabled', and relaunch chrome.
4. Join a class and when the poll comes, you will find that only a blank slide and poll options are visible.
5. See the bug.

**Expected behavior**
Poll's question should be visible on slide.

**Actual behavior**
Poll's question IS NOT VISIBLE on slide, because of dark mode being on.

**Screenshots**
![image_2021-10-06_10-39-35](https://user-images.githubusercontent.com/83908065/136497979-5105279f-7c54-4e1d-929e-ae90d68c7b03.png)
![image_2021-10-07_11-49-31](https://user-images.githubusercontent.com/83908065/136497985-37111a40-34a5-4179-9b8e-5b64ef2c3fe6.png)
![image_2021-10-07_11-10-15](https://user-images.githubusercontent.com/83908065/136497986-df02909d-91c0-4da3-9089-da68326f1756.png)
![image_2021-10-07_11-05-41](https://user-images.githubusercontent.com/83908065/136497991-85f303d0-aba6-4fa5-80f0-283af7e97269.png)
![image_2021-10-06_10-40-10](https://user-images.githubusercontent.com/83908065/136497992-41a30889-98cd-4bf6-b7a6-5c469b8b25fc.png)

**BBB version:**
BigBlueButton 2.3.14

**Desktop (please complete the following information):**
 - OS: Windows 10 64-bit (version 20H2)
 - Browser: Google Chrome 94 (Version 94.0.4606.81 (Official Build) (64-bit))
 - Version: Chrome 94.0.4606.81 , Windows 10 20H2

**Comment by JoVictorNunes** [comment]
I can confirm that it's happening on 2.5.
