### ISSUE TITLE
Unhandled curl error: SSL certificate problem: certificate has expired

### ISSUE THREAD

**Issue by Entretoize** [bigbluebutton/bigbluebutton#13446]
**Describe the bug**
I receive the following erro when trying to join a room:

`Fatal error: Uncaught RuntimeException: Unhandled curl error: SSL certificate problem: certificate has expired in /var/www/vendor/bigbluebutton/bigbluebutton-api-php/src/BigBlueButton.php:480 Stack trace: #0 /var/www/vendor/bigbluebutton/bigbluebutton-api-php/src/BigBlueButton.php(108): BigBlueButton\BigBlueButton->processXmlResponse('https://conf.li...', '') #1 /var/www/bigbluebutton-default/run.php(103): BigBlueButton\BigBlueButton->createMeeting(Object(BigBlueButton\Parameters\CreateMeetingParameters)) #2 {main} thrown in /var/www/vendor/bigbluebutton/bigbluebutton-api-php/src/BigBlueButton.php on line 480`

The error remains after I did  `certbot --webroot -w /var/www/bigbluebutton-default/ -d mydomain.tld certonly`

I'm on Ubuntu 16.04.7 LTS (Xenial Xerus)

**Comment by lonesomewalker** [comment]
Upgrade to 2.3.
Period.

For a quick fix:
`apt-get remove certbot -y && apt-get install snapd -y && snap install --classic certbot && certbot renew --force-renewal --cert-name here-your-hostname --preferred-chain "ISRG Root X1"`

And replace here-your-hostname with your real BBB server name.

**Comment by ffdixon** [comment]
> Upgrade to 2.3.

Ditto.
