### ISSUE TITLE
[2.4] - Random user select modal is reopening

### ISSUE THREAD

**Issue by antonbsa** [bigbluebutton/bigbluebutton#13448]
**Describe the bug**
The non-presenter modal is reopening after some actions if the presenter doesn't close his modal.

**To Reproduce**
1. As presenter, click on "Select random user";
2. Keep this modal opened;
3. With another user, close modal;
4. Click to open/close chat or hide/restore presentation;

**Video**

https://user-images.githubusercontent.com/56703993/136575323-f7989135-3ad0-4b00-a726-f78e3a59070c.mp4

**Comment by antobinary** [comment]
I am changing the milestone to 2.5, explanation can be found here: https://github.com/bigbluebutton/bigbluebutton/pull/13716#issuecomment-973236221

**Comment by antobinary** [comment]
@antonbsa is this still an issue?

**Comment by antonbsa** [comment]
I tested with the latest version of BBB v2.5 and I couldn't reproduce the bug!
