### ISSUE TITLE
 when i want to install bbb 2.3 get this error "bbb-html5 : Depends: bbb-webrtc-sfu but it is not going to be installed"

### ISSUE THREAD

**Issue by vamcan** [bigbluebutton/bigbluebutton#13459]
on my server BBB 2.2 installed, I wanted to upgrade to 2.3 
first, I upgraded the ubuntu to 18.4 and then run the script of installation

i follow the installation in BBB website but i got this error:

Reading state information...
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 bigbluebutton : Depends: bbb-config but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
Reading package lists...
Building dependency tree...
Reading state information...
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 bbb-html5 : Depends: bbb-webrtc-sfu but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
........................................................................................................................................................................................................................................................................................................................................................................

**Comment by ffdixon** [comment]
We (the core developers) have not tested this path as many updates were made in the shift from Ubuntu 16.04 (2.2) to Ubuntu 18.04 (2.3).

However, there are others in the community that have shared their experiences in upgrading a server from 2.2 directly to 2.3.  See: 
 https://groups.google.com/g/bigbluebutton-setup/c/u7O8g-uDE1k/m/X6Mu1DjdBwAJ

**Comment by vamcan** [comment]
i did it,but it not worked
