### ISSUE TITLE
Replace docker with systemd-run

### ISSUE THREAD

**Issue by mikhailnov** [bigbluebutton/bigbluebutton#13453]
BigBlueButton runs LibreOffice in docker, this is a really big headache, for example, to install BBB into systemd-nspawn container, I had to install `docker-ce` and then:
`mv -v /usr/bin/docker /usr/bin/docker.bin`
and create a file:
`nano /usr/bin/docker`
with text:
```sh
#!/bin/sh
exit 0
```
`chmod +x /usr/bin/docker`
and edit `/usr/share/bbb-libreoffice-conversion/convert-local.sh`:
```diff
# diff -u --color /usr/share/bbb-libreoffice-conversion/convert-local.sh.orig /usr/share/bbb-libreoffice-conversion/convert-local.sh
--- /usr/share/bbb-libreoffice-conversion/convert-local.sh.orig	2021-10-09 08:58:42.988946858 +0300
+++ /usr/share/bbb-libreoffice-conversion/convert-local.sh	2021-10-09 09:32:26.740787559 +0300
@@ -37,7 +37,7 @@
 fi
 
 cp "${source}" "$tempDir/file"
-sudo /usr/bin/docker run --rm --memory=1g --memory-swap=1g --network none --env="HOME=/tmp/" -w /tmp/ --user=$(printf %05d `id -u`) -v "$tempDir/":/data/ -v /usr/share/fonts/:/usr/share/fonts/:ro --rm bbb-soffice sh -c "/usr/bin/soffice -env:UserInstallation=file:///tmp/ $convertToParam --outdir /data /data/file"
+HOME="$tempDir" soffice -env:UserInstallation=file://"$tempDir" $convertToParam --outdir "$tempDir" "$tempDir"/file
 cp "$tempDir/file.$convertTo" "${dest}"
 rm -r "$tempDir/"
```
`apt-mark hold docker-ce`
`apt install libreoffice-core libreoffice-writer libreoffice-calc libreoffice-impress`

This is because running docker inside the container requires too many capabilities and cgroups hackery.

Also, differents issues with fonts etc. occur, new and new workarounds are invented to mitigate them.

What for it is done? As far as I understand, the purpose of dockerizing LibreOffice here is protecting system from arbitary code execution in case of vulnerabilities or special features in LibreOffice.

But this can be achieved without docker using `systemd-run`. It can create a transient unit where all directories except needed ones will be mounted read only and network will be disabled. Or `bubblewrap` can be used.

An example of using systemd-run is here: http://0pointer.net/blog/ip-accounting-and-access-lists-with-systemd.html

So I suggest to remove all docker crap and use systemd-run to run LibreOffice from host.

**Comment by PhMemmel** [comment]
To be fair there are keys in `/usr`, see etherpad key in `settings.yml` of meteor, for example. Maybe this should be moved to the html5 overlay config file?
