### ISSUE TITLE
[2.4-RC-2] Learning dashboard - The headings in the table are not transferred, the table does not fit on the 1366x768 screen

### ISSUE THREAD

**Issue by nikkei00** [bigbluebutton/bigbluebutton#13456]
**Describe the bug**
**The headings in the table are not transferred, the table does not fit on the 1366x768 screen**
There are long translations, the table is stretched due to headings that do not have hyphenation

1.
![6356](https://user-images.githubusercontent.com/64165027/136654577-7626c030-ddb0-4470-9196-03de779d7efd.png)

2.
![6357](https://user-images.githubusercontent.com/64165027/136654580-83c6249e-ddd6-4a89-b0a5-31393baf5e1f.png)

**To Reproduce**
1. Open Learning dashboard
2. Change the page size to a narrower one

**BBB version:**
2.4 RC-2

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser Chrome

**Comment by hiroshisuga** [comment]
The change came from #13305, to fix the problem #13297. In my understanding, the current style has been the intended design.
Another fix that was not adopted was #13297, which you may want to try after removing the change in #13305.
