### ISSUE TITLE
Big blue button client integration/customization

### ISSUE THREAD

**Issue by valentinMachado** [bigbluebutton/bigbluebutton#13460]
**Is your feature request related to a problem? Please describe.**

Iam looking for how to integrate big blue button in the web app of my company. For now I am using the npm package bigbluebutton-js on the server side, and my client send request on the api to create room then return url produced by the bbb server. These url are embeded inside an iframe but it's seems to be not recommended for performance and security reasons.

**Describe the solution you'd like**

Solution 1 (integrate big blue button layout in my client)
I am not a web expert but from what I am understanding the big blue button api doesn't allow to customize the client layout since the only thing we can request are urls. A solution would have be to request html content of the page then my server could inject its own html inside before to return it to clients. Is that possible ?

I hope i am posting this at the right place, if not tell me where should I.

Thanks for enlighten me on these questions

**Comment by antobinary** [comment]
For development/customization support requests, please use the [forum / mailing list](https://groups.google.com/forum/#!forum/bigbluebutton-dev). This issue tracker here is only for BBB project development related issues. Sorry.
