### ISSUE TITLE
Text tool for whiteboard

### ISSUE THREAD

**Issue by bigbluebutton-issue-import** [bigbluebutton/bigbluebutton#1346]
Originally reported on Google Code with ID 591

```
What is the feature?

The feature is a text function for the whiteboard. Several users asked about this feature
and it would make it easier to write on the whiteboard, instead of drawing on it.

```

Reported by `seb.sschneider` on 2010-07-29 17:40:15

**Comment by testprepturkey** [comment]
Dear All,

I have a problem with the whiteboard. Whenever I type using the pen tool, the whiteboards trims the edges of the letters, shapes, etc. It does not happen in the demo server, but I set up my own server. Is there any way to fix it?

Thanks.
Baris.
