### ISSUE TITLE
Reduce mental workload when using quick polls

### ISSUE THREAD

**Issue by StephanJanosch** [bigbluebutton/bigbluebutton#13474]
**Is your feature request related to a problem? Please describe.**
I observed mental stress during quick poll usage. Questions and answer options are not picked up  

**Describe the solution you'd like**

During quick poll selection the order of the question should be same as on slide. And the question should appear.

![Screenshot 2021-10-13 at 09 30 30](https://user-images.githubusercontent.com/11651596/137090588-8cc344f5-a233-45ee-95ee-ef18d2f0ec6d.png)

During answering the question and the option values should appear, not the option labels

![Screenshot 2021-10-13 at 09 30 41](https://user-images.githubusercontent.com/11651596/137090796-8dd61126-aff3-45a3-a466-19008dc1108d.png)

When publishing, the option values should appear, not the labels
![Screenshot 2021-10-13 at 09 31 06](https://user-images.githubusercontent.com/11651596/137090809-61c11c8c-7b8a-4336-971f-8515ff4ac964.png)

**Describe alternatives you've considered**
being able to prepare questions in advance would be an alternative. Saw a ticket somewhere.

**Additional context**
n/a

**Comment by hiroshisuga** [comment]
HI, I had the same problem and proposed a PR at #12713. Might help.
