### ISSUE TITLE
[2.4 RC-2]: Install by bbb.install.sh, but 1006 or 1007 error!!!!!!

### ISSUE THREAD

**Issue by nikkei00** [bigbluebutton/bigbluebutton#13489]
**Describe the bug**
This morning, our server 2.2 crashed after the reboot command. I inserted another hard drive in order to install a new version of ubuntu 18.04 + bbb 2.4.
That is, bbb 2.2 worked with these router settings for TWO YEARS, THERE WERE NO PROBLEMS. The hardware has not changed either, the IP addresses have not changed - ONLY the SERVER'S HARD DRIVE has been replaced. Next, I installed ubuntu 18.04 and bbb 2.4-rc2 using a script.

wget -qO- https://ubuntu.bigbluebutton.org/bbb-install.sh | bash -s -- -w -a -v bionic-240 -s bbb.SITE.org -e MY@EMAIL.RU -g

Everything started to start right away, except for connecting as a MICROPHONE. (1006\1007)

Connection diagram:
White static IP address + domain name >>>> Mikrotik router >>>> bbb server

*All blurred ip addresses are white static ip addresses

Following the instructions: https://docs.bigbluebutton.org/admin/configure-firewall

Router settings (port forwarding) HAVE NOT CHANGED FOR TWO YEARS while the server 2.2 was running
![image](https://user-images.githubusercontent.com/64165027/137370179-b67d9b18-7b4c-4e3a-95af-1845bb523e41.png)

# Following the instructions: 

Updating Kurento
nano /etc/kurento/modules/kurento/WebRtcEndpoint.conf.ini
![image](https://user-images.githubusercontent.com/64165027/137370785-d41ed2b8-9ec4-4882-9cee-4bd4ce9bf72d.png)

Update FreeSWITCH
nano /opt/freeswitch/conf/vars.xml
![image](https://user-images.githubusercontent.com/64165027/137370946-fc25a8fb-cc00-46a4-8009-d942e3427b11.png)

nano /opt/freeswitch/conf/sip_profiles/external.xml
![image](https://user-images.githubusercontent.com/64165027/137371077-3190069f-2d00-4d21-b8e8-eb711112fa9a.png)

nano /etc/bigbluebutton/nginx/sip.nginx
![image](https://user-images.githubusercontent.com/64165027/137371168-ef958c39-3710-4521-a328-2f9763017d7f.png)

Configure FreeSWITCH for using SSL

nano /usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml
![image](https://user-images.githubusercontent.com/64165027/137371315-7b540b1a-92b8-46b0-a146-6d0b8e3ed64b.png)

nano /opt/freeswitch/conf/sip_profiles/external.xml
![image](https://user-images.githubusercontent.com/64165027/137371481-3cd98522-31cc-401b-89e5-5e63c031e39d.png)

nano /usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml
![image](https://user-images.githubusercontent.com/64165027/137371598-4011cb41-23ae-4bdf-963b-28a9a5722f73.png)

grep enableListenOnly /usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml
![image](https://user-images.githubusercontent.com/64165027/137371701-0a2fefa0-e343-49c8-8de9-6188d91de5a0.png)

Step again  /usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml 

After making the above changes, restart BigBlueButton.
![image](https://user-images.githubusercontent.com/64165027/137371916-8647e7f3-6725-43be-8c04-ee9cc8ac4917.png)

**Connecting via Mozilla Firefox**
MICROPHONE
![image](https://user-images.githubusercontent.com/64165027/137372133-c4c8381d-efc2-4c67-8a08-6adc28c1ecfe.png)
![image](https://user-images.githubusercontent.com/64165027/137372468-b3a7f0d2-3e52-4963-a9d7-3e68d3888681.png)

**Just listen - everything is ok
Webcams and screen demonstrations work!**

**bbb-conf --check**

000.000.000.000 - White static IP address
192.168.88.61 - Local IP

BigBlueButton Server 2.4-rc-2 (2539)
                    Kernel version: 4.15.0-159-generic
                      Distribution: Ubuntu 18.04.6 LTS (64-bit)
                            Memory: 32797 MB
                         CPU cores: 8

/etc/bigbluebutton/bbb-web.properties (override for bbb-web)
/usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties (bbb-web)
       bigbluebutton.web.serverURL: https://bbb.SITE.org
                defaultGuestPolicy: ALWAYS_ACCEPT
                 svgImagesRequired: true
              defaultMeetingLayout: SMART_LAYOUT

/etc/nginx/sites-available/bigbluebutton (nginx)
                       server_name: bbb.SITE.org
                              port: 80, [::]:80
                              port: 443 ssl

/opt/freeswitch/etc/freeswitch/vars.xml (FreeSWITCH)
                       local_ip_v4: 192.168.88.61
                   external_rtp_ip: 000.000.000.000
                   external_sip_ip: 000.000.000.000

/opt/freeswitch/etc/freeswitch/sip_profiles/external.xml (FreeSWITCH)
                        ext-rtp-ip: $${external_rtp_ip}
                        ext-sip-ip: $${external_sip_ip}
                        ws-binding: 000.000.000.000:5066
                       wss-binding: 000.000.000.000:7443

/usr/local/bigbluebutton/core/scripts/bigbluebutton.yml (record and playback)
                     playback_host: bbb.SITE.org
                 playback_protocol: https
                            ffmpeg: 4.2.4-1ubuntu0.1bbb2~18.04

/etc/bigbluebutton/nginx/sip.nginx (sip.nginx)
                        proxy_pass: 000.000.000.000
                          protocol: https

/usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml (Kurento SFU)
/etc/bigbluebutton/bbb-webrtc-sfu/production.yml (Kurento SFU - override)
                        kurento.ip: 000.000.000.000
                       kurento.url: ws://127.0.0.1:8888/kurento
                    kurento.sip_ip: 000.000.000.000
               recordScreenSharing: true
                     recordWebcams: true
                  codec_video_main: VP8
               codec_video_content: VP8

/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml (HTML5 client)
/etc/bigbluebutton/bbb-html5.yml (HTML5 client config override)
                             build: 2323
                        kurentoUrl: wss://bbb.SITE.org/bbb-webrtc-sfu
                  enableListenOnly: true
                    sipjsHackViaWs: true

/usr/share/bbb-web/WEB-INF/classes/spring/turn-stun-servers.xml (STUN Server)
                              stun: stun.3cx.com:3478

/etc/kurento/modules/kurento/WebRtcEndpoint.conf.ini (STUN Server)
                              stun: 54.37.20.144:3478

# CHANGE
nano /usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml 
sipjsHackViaWs TO FALSE

Now it looks like an adequate job (This message has been on the bb 2.2 server for 2 years)

![image](https://user-images.githubusercontent.com/64165027/137373101-e247dd28-5e26-423c-97a1-64829414d75c.png)

**Connecting via Mozilla Firefox**
MICROPHONE:
![image](https://user-images.githubusercontent.com/64165027/137373223-54c412cd-9f98-499e-bd02-0a7804067afe.png)

about:WebRTC
![image](https://user-images.githubusercontent.com/64165027/137373296-207fbed1-0512-4a88-9d73-e9fdc7f38f21.png)

**Just listen - everything is ok
Webcams and screen demonstrations work!**

**There is no result**
sudo ufw disable
reboot

# I do not know what else to do to make the connection through the microphone work. I tried to connect from the organization's Internet, via 4G from my phone, from home, and asked colleagues.

**Comment by bjoernzingel** [comment]
Please have a look at:
https://github.com/bigbluebutton/bigbluebutton/issues/11743

these hints worked well for me setting up a bbb 2.3 / 2.4 behind a nat

Greetings
Bjoern

**Comment by nikkei00** [comment]
![image](https://user-images.githubusercontent.com/64165027/137422918-42d56afd-871c-4fe0-955f-8acf0ef53b19.png)

and reboot

ERROR 1007




I DON'T UNDERSTAND why you can join as headphones, but not as a microphone?? At the same time, the webcam is WORKING, the screen demonstration is WORKING

**Comment by nikkei00** [comment]
I follow the instructions clearly. What kind of setup is missing?
Why with "SIPJSHACKVIAWS: true" - The server does NOT write that proxy_pass does not match the local IP address (192.168.88.61).
# (This is OK if you've manually changed the values)



When the server 2.2, which worked until yesterday, always wrote this?


When I do "sipjshackviaws: false" - a message is output that shows ME that this is MORE CORRECT??????

**Comment by MrCapitalist** [comment]
for more info, I add this solution too:

If you upgrade your server to BigBlueButton 2.4 and get the 1007 error, check and fix these properties.

Edit `/opt/freeswitch/etc/freeswitch/vars.xml`, and change

```
<X-PRE-PROCESS cmd="set" data="external_rtp_ip=stun:stun.freeswitch.org"/>
<X-PRE-PROCESS cmd="set" data="external_sip_ip=stun:stun.freeswitch.org"/>
```
to:
```
<X-PRE-PROCESS cmd="set" data="external_rtp_ip=EXTERNAL_IP_ADDRESS"/>
<X-PRE-PROCESS cmd="set" data="external_sip_ip=EXTERNAL_IP_ADDRESS"/>
```
