### ISSUE TITLE
[2.4-rc-2] - Users are not receiving breakout invitation

### ISSUE THREAD

**Issue by antonbsa** [bigbluebutton/bigbluebutton#13480]
**Describe the bug**
After creating breakout rooms allowing users to choose one, users are not receiving the invitation through **manage users > breakout invitation**.

**To Reproduce**
1. Go to breakout rooms menu;
2. Allow users to choose a room;
3. Create the rooms;
4. With moderator, go to breakout room invitation menu and try to invite user;

**Video**

https://user-images.githubusercontent.com/56703993/137178209-2bd60756-4451-4dbc-93f3-a7dad0b30afc.mp4

**Comment by frankemax** [comment]
What would be the expected result?
- The user who was invited has the option to choose which room to join:
![image](https://user-images.githubusercontent.com/42683590/140792873-20c62298-e432-4416-a931-115a71539e68.png)

- The user who was invited only receive the option to enter the room assigned to him:
![image](https://user-images.githubusercontent.com/42683590/140792982-521b62fc-f6f1-47f7-814b-4a83be6b9306.png)

**Comment by mariogasparoni** [comment]
cc @antobinary  @tylercopeland

**Comment by mariogasparoni** [comment]
Just to clarify things here in the issue.
As we spoke internally, the default behavior is to show the selector when the checkbox "Allow users to choose a breakout" is marked. Otherwise, show the invitation , only,

**Comment by antonbsa** [comment]
It's been a long time since the last time I hit this bug (as far as I remember, it was only in early versions of 2.4-rc). Also, no related bugs have been hit so far.

**Comment by frankemax** [comment]
I think it was fixed in fe944c1bdb61856fe6f48520fd494ae0a0d45522 part of https://github.com/bigbluebutton/bigbluebutton/pull/13816
