### ISSUE TITLE
recording always fail in processing  bbb: 2.3.15

### ISSUE THREAD

**Issue by freehussain** [bigbluebutton/bigbluebutton#13510]
hello,

processing bbb recording always failed with the following error

 ERROR -- : no implicit conversion of nil into String
ERROR -- : /usr/local/bigbluebutton/core/scripts/publish/presentation.rb:1327:in `directory?'
ERROR -- : /usr/local/bigbluebutton/core/scripts/publish/presentation.rb:1327:in `<main>'
 ERROR -- : exit
 ERROR -- : /usr/local/bigbluebutton/core/scripts/publish/presentation.rb:1350:in `exit'
ERROR -- : /usr/local/bigbluebutton/core/scripts/publish/presentation.rb:1350:in `rescue in <main>'
ERROR -- : /usr/local/bigbluebutton/core/scripts/publish/presentation.rb:1166:in `<main>'

can you help me please

**Comment by danielpetri1** [comment]
The publish directory in your `presentation.yml` file is likely wrong.

**Comment by antobinary** [comment]
Please reopen if needed
