### ISSUE TITLE
iOS low level sound problem

### ISSUE THREAD

**Issue by more-zamani** [bigbluebutton/bigbluebutton#13523]
Hi
I want to report the sound problems in iOS devices. We had this issue last year and it was resolved by updating iOS or BigBlueButton. But again this problem comes back. 

When an iOS device join a room, the sound of speakers is very low and hard to hear even on the latest volume status

We tested it on iOS 15 and BigBlueButton v2.3.14 and v2.3.15

Is there any suggestion?

**Comment by dsafl** [comment]
Hi, 
we also have this sound problem with our iOS devices.
Tested with several iPhones with iOS 15.0.2 and with an iPad with iPadOS 15.0.2. 
Our hoster told us they are using the lastet BBB Version.

**Comment by ravi-ct** [comment]
> > > Hi @ali-alhaidary , @ravi-ct , would you be willing to test a workaround for this on another server ? If so , email mariogasparoni at gmail , i will send you the server credentials.
> > > I already sent you an email with the info, @ali-alhaidary Thanks in advance
> > 
> > 
> > Thank you @mariogasparoni we do have our own servers, and testing was done on demo and our servers with the same results. If you have a remedy, we certainly appreciate it.
> 
> Nice , i emailed you with the credentials for my server. Please , test it on there and see if it works for your iOS device

Hi @mariogasparoni 

We conducted the test on your server with the patch. It didn't help for iPhone. For one version of iPad with iOS 15, it worked fine. For iPhone 12 with iOS 15.1, it did not work. The voice was coming through only the earpiece and not the loudspeakers.

**Comment by misisol** [comment]
The same problem has been reported from our customers before and it still exists.
our servers are on 2.3.15 and devices varies from 14 to 15 iOs version.

**Comment by mariogasparoni** [comment]
Thanks for testing it, @ravi-ct 
Yes, this seems to be a regression in iOS 15. More info can  be found [here](https://bugs.webkit.org/show_bug.cgi?id=230902).

According to the reports , the workaround is not very effective so we should probably wait for iOS folks to fix this in the next release.
