### ISSUE TITLE
update(audio): make fullaudio bridge treats audio as bidirectional

### ISSUE THREAD

**Issue by mariogasparoni** [bigbluebutton/bigbluebutton#13539]
This was pointed by @prlanzarin in https://github.com/bigbluebutton/bigbluebutton/pull/13533#discussion_r733196356, https://github.com/bigbluebutton/bigbluebutton/pull/13533#discussion_r733196767 and https://github.com/bigbluebutton/bigbluebutton/pull/13533#discussion_r733196845
This will make fullaudio/listenonly stream more transparent, and will cooperate with one of the goals of the fullaudio bridge that is removing listenonly option (making microphone/listenonly differences transparent for the user)

**Comment by prlanzarin** [comment]
#14868, https://github.com/bigbluebutton/bbb-webrtc-sfu/releases/tag/v2.8.0
