### ISSUE TITLE
2.4 RC3,  creating meeting with existing voicebridge bbb-web throws 500 does not return proper error

### ISSUE THREAD

**Issue by hostbbb** [bigbluebutton/bigbluebutton#13556]
**Describe the bug**

** How to reproduce.
With api mate, create a meeting with random vbridge.

then try to create another meeting with different name with same vbridge number.

 get 500 error,  instead of error response its a duplicate.

/var/log/bigbluebutton/bbb-web.log:groovy.lang.MissingMethodException: No signature of method: org.springframework.validation.MapBindingResult.nonUniqueVoiceBridr() is applicable for argument types: () values: []
/var/log/bigbluebutton/bbb-web.log:2021-10-23T16:18:01.079Z ERROR o.g.w.e.GrailsExceptionResolver - MissingMethodException occurred when processing request: [GETbluebutton/api/create
/var/log/bigbluebutton/bbb-web.log:groovy.lang.MissingMethodException: No signature of method: org.springframework.validation.MapBindingResult.nonUniqueVoiceBridr() is applicable for argument types: () values: []
/var/log/bigbluebutton/bbb-web.log:2021-10-23T16:18:01.084Z ERROR o.a.c.c.C.[.[.[.[grailsDispatcherServlet] - Servlet.service() for servlet [grailsDispatcherServn context with path [] threw exception [Could not resolve view with name '/error' in servlet with name 'grailsDispatcherServlet'] with root cause
/var/log/bigbluebutton/bbb-web.log:javax.servlet.ServletException: Could not resolve view with name '/error' in servlet with name 'grailsDispatcherServlet'
/var/log/bigbluebutton/bbb-web.log:2021-10-23T16:18:01.085Z ERROR o.a.c.c.C.[.[.[.[grailsDispatcherServlet] - Servlet.service() for servlet [grailsDispatcherServhrew exception
/var/log/bigbluebutton/bbb-web.log:javax.servlet.ServletException: Could not resolve view with name '/error' in servlet with name 'grailsDispatcherServlet'
/var/log/bigbluebutton/bbb-web.log:2021-10-23T16:18:01.085Z ERROR o.a.c.c.C.[Tomcat].[localhost] - Exception Processing ErrorPage[errorCode=500, location=/error]

**Comment by ritzalam** [comment]
In 2.3, the response is

![dup-vconf-2 3](https://user-images.githubusercontent.com/184672/139481476-08035ebf-cc1a-40e9-85a7-08999cc5f9bb.png)
