### ISSUE TITLE
Feature request: Make webcams rotatable/flippable

### ISSUE THREAD

**Issue by PhMemmel** [bigbluebutton/bigbluebutton#13573]
**Is your feature request related to a problem? Please describe.**
Webcams should be rotatable/flippable.
Use case: Sometimes the rotation of webcams is wrong (e. g. some iPads seem to send wrong information about the rotation of the webcam/device, also see #13315, which doesn't seem super easy to fix for all devices). As the user sending the stream sees his own stream the correct way it would be nice if at least on the receiving client side it would be possible to rotate or flip the webcam via css.

**Describe the solution you'd like**
Webcams currently can be mirrored, but not rotated or flipped. I'd like to have an additional option "flip" and/or "rotate 90°" in the small popup menu which opens when you click on the name in the webcam container (just below "mirror").

**Describe alternatives you've considered**
As the client itself sees the correct orientation of his own webcam it's probably not a solution to rotate/flip the webcam stream itself on the sender's side (including submitting the correct rotation information).

**Additional context**
It would also offer the possibility to intentionally share a webcam stream with an "incorrect" rotation (of a demonstration/microscope camera or sth similar) and each participant would be able to rotate/flip it the way he/she wants to.

As far as I can tell this feature would be easy and small to implement (just a little bit of CSS?), but would provide an easy possibility to address some "edge cases" with very little effort.

**Comment by pitlochry** [comment]
This feature is sooo important when using mobile phones. Why was this closed by a bot, can it be reopened, or should I create a new issue?
