### ISSUE TITLE
User response poll is missing "publish" button

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#13582]
**Describe the bug**
User response poll is missing "publish" button. Instead, a button to create a new poll is present. (It might be the case that the label is wrong)

**To Reproduce**
1. Create a poll of type "User response"
2. Start the poll

**Expected behavior**
A button offering to publish the poll should appear, like for other poll types
![Screenshot from 2021-10-27 09-43-13](https://user-images.githubusercontent.com/6312397/139077893-c5b398cc-1fca-4767-af6f-f97a675ab19a.png)

**Actual behavior**
Instead of publish button, a create poll button is displayed, see

![Screenshot from 2021-10-27 09-40-37](https://user-images.githubusercontent.com/6312397/139077783-8337eb5e-fb3f-421d-8462-7550e68c3fe9.png)

**Screenshots**

**BBB version:**
BigBlueButton Server 2.3, 2.4

**Additional context**
Thanks @tylercopeland for reporting!

**Comment by AhmadrezaP** [comment]
> **Additional info**: While I was testing this behavior, I could see the "publish" button being shown right after the polling had received some response
> 
>  poll-user-resp-bug-.mp4

Yes after one answer this would be shown but for non-response type polls, immediately after starting a poll, you can publish the results.
