### ISSUE TITLE
Move record from old server to new server bigbluebutton

### ISSUE THREAD

**Issue by kjaedu** [bigbluebutton/bigbluebutton#13595]
I have 1000 records in my old bigbluebutton server , I want to move to new bigbluebutton server , but when I coped the records folders and putted it in new one it is returned

when i call by api  it is return this 
<response>
<returncode>SUCCESS</returncode>
<recordings/>
<messageKey>noRecordings</messageKey>
<message>There are no recordings for the meeting(s).</message>
</response>

but if i open by the https://myservername/playback/presentation/2.3/dd0a23e0xxxxxxxxxxxxxx-1678xxxxx
it is open 
so how can i make it working with api to get the url link ?

**Comment by kjaedu** [comment]
I did this command "bbb-conf –setip" but still not working

**Comment by info5050info** [comment]
Any update still not solve the issue !

**Comment by kjaedu** [comment]
Any update still not solved it

**Comment by hostbbb** [comment]
cat /var/bigbluebutton/published/presentation/*/metadata.xml | grep link  

this will list all the recording links...  see if any have the old bb server name,   --setip should have changed them all.

if not you can change with sed...

**Comment by antobinary** [comment]
This might be related https://github.com/bigbluebutton/bigbluebutton/pull/12682
