### ISSUE TITLE
no presentation shown

### ISSUE THREAD

**Issue by kiar1404** [bigbluebutton/bigbluebutton#13602]
**Describe the bug**
Uploaded presentation in PDF format will not appear. Slide presenter with blank presentation appears. But recognizes the amount of pages.
If you record the conferenze, the presetation is shown

**To Reproduce**
1. Start a conference
2. Upload a presentation (pdf)
3. it is empty

**Expected behavior**
The presentation should be shown during conference and not only if the conference was recorded in the recorded presentation

**Actual behavior**
only the controls are shown

**Screenshots**
![bbb1](https://user-images.githubusercontent.com/93373491/139406460-bf0879a0-2967-4c73-9b2f-acd32f398c90.png)
![bbb2](https://user-images.githubusercontent.com/93373491/139406809-a355b594-8f33-48f5-90e9-124e41b39a90.png)

**Desktop (please complete the following information):**
 - Linux and Windows
 - Firefox and Chrome
 - Version current

**additional information:**
In an other issue the fix should be a change on certbot (#13441)
I do not use certbot for certificates.

**Comment by lonesomewalker** [comment]
How about upgrading from BBB 2.2 (which is outdated) to 2.3?
