### ISSUE TITLE
Uncomplete instruction on Akka-apps development

### ISSUE THREAD

**Issue by AhmadrezaP** [bigbluebutton/bigbluebutton#13619]
**Describe the bug**
after Akka-bbb-apps development, when I want to deploy the app and follow the instructions [here](https://docs.bigbluebutton.org/2.3/dev.html#developing-akka-apps), ./run.sh command only runs the app in development mode and it's not declared in the documentations how to deploy this app.
I use these commands to deploy the app (I've got it from a bigbleubutton conversation on google groups):
```
sbt debian:packageBin
sudo dpkg -i ./target/bbb-apps-akka_<tab>.deb
```
**Expected behavior**
A clear instruction for Akka-apps development and deployment like other apps have on bigbluebutton development documents.

**Comment by antobinary** [comment]
Thanks for pointing this out @AhmadrezaP 
I just added this to the docs. https://github.com/bigbluebutton/bigbluebutton.github.io/pull/324
