### ISSUE TITLE
deploy_to_usr_share meteor error

### ISSUE THREAD

**Issue by AhmadrezaP** [bigbluebutton/bigbluebutton#13612]
**Describe the bug**
When I want to deploy my bigbluebutton-html5 development through bigbluebutton-html5/deploy_to_usr_share.sh on a server, it executes commands successfully till reaches command "meteor reset" and gives this error:

`reset: You're not in a Meteor project directory.`

**Comment by antobinary** [comment]
You need to be in the `bigbluebutton-html5` directory, same as when you run the client in any other way (e.g. `npm start`)

`cd bigbluebutton-html5`
`./deploy_to_usr_share.sh`

**Comment by AhmadrezaP** [comment]
Of course I am in the `bigbluebutton-html5` directory and I execute `deploy_to_usr_share.sh` file.
The script needs a review?

**Comment by antobinary** [comment]
Could you please add a line 

```
echo `pwd`
```

before the
```
meter reset
```

 line and re-run. This will help with outputing the location.
Also, what branch do you run this on?

**Comment by AhmadrezaP** [comment]
I made a mistake sorry. There is no error in bigbluebutton-html5 deploy code.

**Comment by antobinary** [comment]
No worries, thank you for writing back! Have a nice day!
