### ISSUE TITLE
2.4 - Audio and Microphone Device Selection

### ISSUE THREAD

**Issue by rob0403** [bigbluebutton/bigbluebutton#13620]
**Describe the bug**
BBB 2.4 allows to switch between different audio input and audio output device on the speaker button 
![grafik](https://user-images.githubusercontent.com/15635417/139900838-81dd6a2b-c495-4512-a81a-ffe840969fa7.png)
![grafik](https://user-images.githubusercontent.com/15635417/139901526-a60b1d11-2178-4eca-83ed-4d8ff2e129d1.png)
From a usability point of view it would probably be easier to split the selection of audio in- and output to its corresponding buttons. --> The microphone icon should have a small arrow that allows you to select a microphone; the speaker icon should keep the small arrow (already available) but only allow to select a speaker.

**To Reproduce**
Join a room in BBB2.4 RC3 and have a look at the icon set.

**Expected behavior**
Split up the microphone and speaker selection to the microphone and the speaker icon.

**Actual behavior**
Currently you select microphone and speaker on the speaker icon.

**Comment by Philipp000** [comment]
This sounds really useful to me!
I will start working on this.

**Comment by prlanzarin** [comment]
Obsoleted in 2.6 via https://github.com/bigbluebutton/bigbluebutton/pull/15154.
