### ISSUE TITLE
Predefine breakout room belonging

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#13628]
**Is your feature request related to a problem? Please describe.**
In some cases large classes consist of pre-defined sub-groups and when such a class holds a meeting with breakouts, it would make sense to offer the breakouts initiator to use the pre-defined group belonging to group teams into their own breakouts.

**Describe the solution you'd like**
Utilize information passed from LMS to define groups, store this information, offer to optionally use the info at breakout creation

**Describe alternatives you've considered**
Without such information the alternative is what we have now - assign users at random OR let them self-select a breakout based on a specific breakout room name (introduced in BBB 2.4) OR painstakingly drag the pool of all viewers into breakouts while looking up their group in the LMS interface

**Additional context**

**Comment by jfederico** [comment]
Just so start the conversation. Since the point of contact between the LMS and BBB is the `create` request, an alternative I would consider is to give the LMS the ability to pass a full roster though a parameter (or even meta parameter) as an HTML encoded string with a JSON payload `enrolment={}` such as:

```
{
  'users': [
    {
      'id': 943
      'uid': '91330665'
      'name': 'John Doe',
      'email': 'john.doe@example.com'
      'role': 'viewer'
    },
    {
      'id': 1045
      'uid': '95330715'
      'name': 'Jane Doe',
      'email': 'jane.doe@example.com'
      'role': 'viewer'
    }
  ],
  'groups': [
    {
       'id': 1,
       'name': 'Group 1',
       'roster': [
         943
       ]
    },
    {
       'id': 2,
       'name': 'Group 2',
       'roster': [ 
         1045
       ]
    }
  ]
}
```
One thing to consider is that would only work with POST requests

**Comment by gustavotrott** [comment]
Hey @jfederico,

I'm wondering if we need to use objects in the `roster` array:
![image](https://user-images.githubusercontent.com/5660191/157081485-59ab0085-4e40-4d3d-8864-5c1e531025e1.png)

Maybe it could be simpler just using a list of integers.

Now:
```js
{ roster: [{id:123},{id:234},{id:345}]}
```

After:
```js
{ roster: [123,234,345]}
```

**Comment by jfederico** [comment]
@gustavotrott One detail here, what if the id is not numeric? Some LMS such as Sakai would either use a UUID (by default) or what they call Student Number, which in most cases is alphanumeric

Of course that would not work with the current implementation either.

Would BBB be able to identify it they are different or it must be numeric. 

What happen on join actually, does join only support numbers?

It is OK for Moodle as it uses numeric values for identifying users, but it is just of the few that do that

**Comment by gustavotrott** [comment]
Yes, it support IDs as string!
`{ roster: ['abc','ddd','zzz-dddd'] }` is valid.

I just sent an update for documentation, where I set all IDs as string in the example!
https://github.com/bigbluebutton/bigbluebutton.github.io/pull/369
