### ISSUE TITLE
Remove iframe postMessage api

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#13633]
This is a legacy API which we no longer support/maintain. It's been disabled by default since creation (so I hope nobody relies on it). If people rely on it, they should make sure to improve the security in their calls source checks.

![Screenshot from 2021-11-03 13-22-52](https://user-images.githubusercontent.com/6312397/140149877-5bceb48c-6786-48f1-b036-0c84112da205.png)

Remove work introduced by
https://github.com/bigbluebutton/bigbluebutton/pull/6215
https://github.com/bigbluebutton/bigbluebutton/pull/6274
https://github.com/bigbluebutton/bigbluebutton/pull/6308

The following will have to remain - https://github.com/bigbluebutton/bigbluebutton/pull/6513  (edit: confirmed by @maths22 )

Related enhancement pull requests which I believe we should decline 
https://github.com/bigbluebutton/bigbluebutton/pull/11377 (apologies @maths22 )

**Comment by maths22** [comment]
Does this mean BBB in an iframe is officially unsupported now?  That's somewhat disappointing given that that is the primary reason I chose to integrate with BBB.

**Comment by antobinary** [comment]
It's not unsupported, but these postMessage hooks with the listeners would not be part of the main code if this work proceeds.
From what I imagine you already use a modified version of the client because of #11377
Do you use the flag you implemented in 11377? Do you use any of the other flags available?
