### ISSUE TITLE
Breakout Room - Student's audio is in breakout room but also in main room

### ISSUE THREAD

**Issue by peter-lernyx** [bigbluebutton/bigbluebutton#13636]
In Breakout Session sometimes a student's audio is still present in main room, but simultaneously in the breakout-room as in the scenario below:

![image](https://user-images.githubusercontent.com/75390480/140171874-3b679bda-1e36-4a79-b847-b94c042cdeb7.png)

The student experiences the breakout room normally but can still hear the moderator in the main room, while the moderator can also hear the student's contribution

**Comment by ffdixon** [comment]
Can you provide more details. 
 - What version of BigBlueButton are you running?
 - Did you make any changes (outside of bbb-install.sh) to this version?
 - Are you able to reproduce this (if so, can you reproduce on demo.bigbluebutton.org)?

For more details, see

  https://docs.bigbluebutton.org/support/getting-help.html#help-installing-or-running-bigbluebutton

**Comment by peter-lernyx** [comment]
Oh yes, Version, I apologize.

- Version 2.3 latest
- No changes made except standard configurations in /usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml
- Reproduce: Well,  I experienced this on long calls (4h) with 18-20 people on the call and then it is sporadic. 
BTW. That same person in the pic above upon coming back from that breakout room couldn't hear anything and had to log out and log back in to connect back to audio. She had no video engaged btw. , so can't tell if video would have followed the audio problem. 
I had this one other time before with a single delegate also in big a 15 people call , so how I would reproduce this on the demo, I don't know.

**Comment by ffdixon** [comment]
Thanks Peter -- we'll try and reproduce it on our end.

**Comment by mariogasparoni** [comment]
This is possibly closed by the PR #15358 .
Let's see if this happens after merging it
