### ISSUE TITLE
Audio state inconsistent after joining breakout room audio-only

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#13631]
**Describe the bug**
When a moderator joins breakout rooms with `join audio`

![image](https://user-images.githubusercontent.com/290351/140098948-a34c5e24-8b2e-4bca-9854-065435b9368f.png)

and returns to the main room.  If they click `join room` they do return with an audio state that 

**To Reproduce**
1. Start 2.4 as moderator
2. Create breakout room and invite yourself
3. Join/leave with `join audio`
4. join/leave with `join room`

**Expected behavior**
User's two/way audio is in proper state (i.e. the mute/unmute buttons are visible).

**Actual behavior**
User is show not in audio, but audio button is highlighted.  There is no mute/unmute button.

**Screenshots**
Here is the audio state for the moderator in the main room.  Note the audio button is highlighted, but there is no microphone on the user's icon and there is no mute/unmute button.

 
![image](https://user-images.githubusercontent.com/290351/140099176-91af11be-701e-4c66-95a1-f5cf07225fe5.png)

**BBB version:**
Version 2.4 on Chrome 94

**Comment by danimo** [comment]
We can reproduce this pretty reliably, if you perform the steps quick enough (race condition?):

1. As moderator create create breakout rooms
1. assign yourself to a breakout room
1. Join breakout room
1. Leave meeting via menu in upper right corner
    ➔  State is still “already in room” for the breakout room for some seconds
1. Quickly rejoin main rooms' audio
1. Quickly “join audio” of the breakout room and “return audio. Wait for “already in room” changing to “Join room”
1. Join breakout room again
1. Leave breakout room

➔ Result: moderator audio broken

There are probably others ways to trigger the issue, but this was the most stable for us to reproduce.

This may not seem critical at first glance, but teachers tend to "hop" between working groups rapidly, so this is easily triggered, causing frustration. Reload 'fixes' the issue, but moderators often do not realize that in time.

**Comment by ffdixon** [comment]
Thanks for sharing this Daniel.
