### ISSUE TITLE
Cannot sharing screen with electron (Error 1136)

### ISSUE THREAD

**Issue by alvinkurniakamal** [bigbluebutton/bigbluebutton#13658]
I tried to build desktop apps using electron.
I embed bbb html5 using WebView. Everythings running well except screen share.
I got this error :

![Screenshot 2021-11-09 110338](https://user-images.githubusercontent.com/93963060/140860001-58c0c061-b4f4-4e66-8506-ab8c215032e9.png)

Is there any way to solve this ?

**Comment by prlanzarin** [comment]
We rely on navigator.mediaDevices.getDisplayMedia and Electron doesn't support getDisplayMedia.

For screen sharing to work we'd have to a) fall back to getUserMedia-based screen capture or b) use Electron's own desktop-capturer polyfill. 

We had those two implemented a couple of years ago, but I removed them. Electron was never an officially supported environment and I don't really like the idea of maintaining either of those options.
