### ISSUE TITLE
Exclude given userID(s) from Learning Dashboard

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#13653]
**Is your feature request related to a problem? Please describe.**
When doing automated testing or monitoring, a test script could access a meeting to check its state.  With the new Learning Dashboard, these test users would appear in the users list.

**Describe the solution you'd like**
Add a property `learningDashboardExcludeUserID` which can pass a list of comma-separate userID to exclude from the Learning Dashboard.

**Describe alternatives you've considered**
We considered excluded by name, but in some cases the name may conflict with an existing name entered by the user.  Using the userID will ensure that only an automation script can generate the specific userID.

**Comment by antobinary** [comment]
Implementation clarification: Here I am pretty sure we mean _external_ userId, i.e. `extId` https://github.com/bigbluebutton/bigbluebutton/blob/v2.4.x-release/bigbluebutton-html5/imports/api/users/server/modifiers/addUser.js#L25
LMS, etc, are not aware of internal BBB ids

**Comment by gustavotrott** [comment]
Hey @ffdixon and @antobinary ,

is the idea to provide the user ids through `API Param` or `Config file`?

**Comment by ffdixon** [comment]
We only need this property in the config file.

**Comment by hostbbb** [comment]
Like with webcams? do some want to opt out students on the join, that have not given parental permission to capture such data?
Or teacher unions don't want the teacher data to be collected, just students...

Understand this initial request is to remove test users on first release.. . just trying to understand long term use.

**Comment by ffdixon** [comment]
On more thought, a better approach is to pass an additional parameter on the join URL such as `excluedDashboard=true`, and that special user would not appear on the learning dashboard.

No configuration file changes needed, just an additional parameter on the `join` URL.

**Comment by antobinary** [comment]
`userdata_bbb-exclude-user-from-learning-dashboard=true`   (default is false), and let's add this to the bbb docs api

**Comment by ali-alhaidary** [comment]
> My impression was that this was to be fed by an external app (maybe LMS) where the user to be excluded has a specific extId.
> 
> @ffdixon could you please specify which config file and a sample content of such file?

That will need an update to the plugin, right?
