### ISSUE TITLE
2.4 RC3 -  bug - presentation causes the client to crash 

### ISSUE THREAD

**Issue by Jossef-767** [bigbluebutton/bigbluebutton#13659]
After uploading many files (usually more than 5) of different types, including JPEG, to the presentation window. Opening a presentation upload window will cause an error message in the presentation area. Refreshing the browser does not help. The only way is to close and open the Session. Other classrooms that are open at the same time are not affected.

My guess is that it has to do with the function of sorting the list of uploaded files.
Or something in the names of the files uploaded.

**To Reproduce**
This critical random bug is difficult to re-create.

Steps to reproduce :
1.  upload 7 or more JPEG , JPG, PDF files. with long names.
2. delete the default.pdf from the presentation list
3. Opening a presentation upload window 
4. See error (sometimes)

**Screenshots**
I actually saw in the console 2 types of error
![image](https://user-images.githubusercontent.com/2356928/140876538-b16a2467-af7f-4325-bc06-f7ef8b308ca6.png)

And sometimes, this shows up 
![image](https://user-images.githubusercontent.com/2356928/140876769-c2c188f2-0412-4b05-91fc-05e31e0f7248.png)

**BBB version:**
2.4 RC3 - Windows, Chrome,  Safari
i have servers running version 2.3.0 (1669) without any such error.

**Comment by FarzadKarkhani** [comment]
I have the same issue with the presentation and upload
![Screen Shot 2021-11-16 at 18 30 59](https://user-images.githubusercontent.com/1698851/142015091-65e34fbe-5b51-43d8-83fc-7f09158e15b9.png)
.

**Comment by Jossef-767** [comment]
this is from the firefox console when error is seen
![image](https://user-images.githubusercontent.com/2356928/142207955-3591bad2-1632-42f8-b5e6-95b4fd537351.png)

**Comment by jfsiebel** [comment]
Hi @FarzadKarkhani,

how often do you get this error? The steps that you do are the same reported in the issue?

**Comment by antobinary** [comment]
"msg":"TypeError: Cannot read properties of undefined (reading 'length')","time":"2021-11-08T22:52:32.920Z","src":"https://demo3.bigbluebutton.org/html5client/3d33e24d382523578c2254d34bb16abb06f7fe09.js?meteor_js_resource=true:375:1532956","v":1,"userInfo":{"sessionToken":"2xx8vvcqkk4nn2wo","meetingId":"7e5593c8ab735b5ef5f935709bf02269acff0168-1636411936574","requesterUserId":"w_tjl2b2wdsllb","fullname":"xxxx","confname":"yyyy","externUserID":"gl-gdsfdsfsd","uniqueClientSession":"2xx8vvcqkk4nn2wo-yfcoc8s"},"clientBuild":2366,"connectionId":"M5o8bhRvwi8YidCL7","url":"https://demo3.bigbluebutton.org/html5client/join?sessionToken=2xx8vvcqkk4nn2wo","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36","count":1}]


This is the only log line I find and it is on RC3 from ~10 days ago.
Has anoyone hit this in RC4+?

**Comment by FarzadKarkhani** [comment]
Hello @jfsiebel,
yes that was the same as reported here

**Comment by Jossef-767** [comment]
Hi Anton, Today at 16:30 GMT just after the end of the Community Call I was able to re-create the problem on the test24.bigbluebutton.org server. Class Name: English 232.
Interface is in English LTR but the file names I uploaded were not in English.
You can see in the logs of the server.
I'll leave the classroom stay open so you can come in and see if you'll see this post anytime soon. 
When you try to upload a file you get the error message, When the upload window opens.
It seems to me that there is a bug  if the file names are not in English with the functions that sorts  (or doing other things) with the files in the upload window.
also, Do not know if it is related, but at the time it happened Layout type is custom.

**Comment by Jossef-767** [comment]
OK I did more testing on the test24.bigbluebutton.org server.
Contrary to what I wrote earlier, the file names can be in English, it does not matter.
I have seen that there are a number of conditions for a greater chance of re-creating the bug:
1) Delete the default presentation
2) Upload files in **drag and drop**.
3) Upload  image files, JPEG, PNG, etc.
4) Drag and drop more than 5 files together.

**Comment by antobinary** [comment]
Thanks @Jossef-767 We'll try again using these latest tips!

**Comment by Jossef-767** [comment]
Right now the error is visible on https://test24.bigbluebutton.org/ - meeting name: English 232

**Comment by antobinary** [comment]
I was able to hit it in your meeting, thanks for uploading those files. Here's some info which should further help:

Based on the error and its location in the minified js file, I believe this is the line with the issue: https://github.com/bigbluebutton/bigbluebutton/blob/v2.4-rc-5/bigbluebutton-html5/imports/ui/components/presentation/presentation-uploader/component.jsx#L644

To reproduce, I joined a meeting with several files already uploaded (they were showing fine)
I switched my locale to Arabic (in case RTL was the trigger). The files still displayed fine.
Then I took over presenter's control. I could switch between the files via "+" menu.
!! However, when I opened the presenter upload modal, that's when the crash happened for me.
Note that all of the uploaded files had RTL file names:
![Screenshot from 2021-11-29 13-17-11](https://user-images.githubusercontent.com/6312397/143922532-d3562b73-d05e-410b-be66-69f33e9baba4.png)


![Screenshot from 2021-11-29 13-26-45](https://user-images.githubusercontent.com/6312397/143922657-08b3e212-48fc-4e82-9dc5-8f9dabc610b4.png)

**Comment by antobinary** [comment]
Hi @Jossef-767 
Thank you for the time yesterday - based on your feedback @ramonlsouza was able to make changes to 2.4.x and I am no longer able to reproduce the test cases discussed yesterday!

I just updated test24.bigbluebutton.org with this fix. Could you and possibly @FarzadKarkhani give this another try and report here if all worked well for them or if the issue resurfaced somehow.
Thanks in advance!

**Comment by FarzadKarkhani** [comment]
@antobinary it works for me without the issue.
Thanks
