### ISSUE TITLE
Error during installation of 2.4-rc4 via bbb-install.sh 

### ISSUE THREAD

**Issue by ratondeau** [bigbluebutton/bigbluebutton#13677]
**Describe the bug**
Error messages shown during the installation of 2.4 rc-4

**Installation type**
via install script

**Firewall and IP address type**
no firewall own IP

**Console output**
`Setting up bbb-libreoffice-docker (1:2.4.0-6) ...
#
# Building bbb-libreoffice docker image
#
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
dpkg: error processing package bbb-libreoffice-docker (--configure):
 installed bbb-libreoffice-docker package post-installation script subprocess returned error exit status 1
dpkg: dependency problems prevent configuration of bbb-web:
 bbb-web depends on bbb-libreoffice-docker; however:
  Package bbb-libreoffice-docker is not configured yet.

dpkg: error processing package bbb-web (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of bbb-html5:
 bbb-html5 depends on bbb-web; however:
  Package bbb-web is not configured yet.

dpkg: error processing package bbb-html5 (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of bbb-config:
 bbb-config depends on bbb-html5; however:
  Package bbb-html5 is not configured yet.

dpkg: error processing package bbb-config (--configure):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 bbb-libreoffice-docker
 bbb-web
 bbb-html5
 bbb-config
E: Sub-process /usr/bin/dpkg returned an error code (1)`

**Additional context**
After installation services are only partially started and 2.4-rc-1 (2675) is still active:
`
nginx —————————————————► [✔ - active]
freeswitch ————————————► [✔ - active]
redis-server ——————————► [✔ - active]
bbb-apps-akka —————————► [✔ - active]
bbb-fsesl-akka ————————► [✔ - active]
mongod ————————————————► [✔ - active]
bbb-html5 —————————————► [✔ - active]
bbb-webrtc-sfu ————————► [✔ - active]
kurento-media-server ——► [✔ - active]
kurento-media-server-8888  [✔ - active]
kurento-media-server-8889  [✔ - active]
kurento-media-server-8890  [✔ - active]
bbb-html5-backend@1 ———► [✘ - failed]
bbb-html5-backend@2 ———► [✘ - failed]
bbb-html5-frontend@1 ——► [✘ - failed]
bbb-html5-frontend@2 ——► [✘ - failed]
etherpad ——————————————► [✔ - active]
bbb-web ———————————————► [✔ - active]

`

**Comment by antobinary** [comment]
Hi @ratondeau 
Was this installation performed on a "clean" server or was there an older version of BBB there (perhaps even BBB 2.3.x)?

If you uncomment `set -x` in `/var/lib/dpkg/info/bbb-libreoffice-docker.postinst` and re-run that script, do you get any more info on where the install trips up?

**Comment by ratondeau** [comment]
There was an 2.3 before then the 2.4-rc1.
