### ISSUE TITLE
push layout settings different from documentation / documentation needs to be changed

### ISSUE THREAD

**Issue by joergmschulz** [bigbluebutton/bigbluebutton#13681]
While the specification describes the push option of the layout as follows:
<img width="434" alt="image" src="https://user-images.githubusercontent.com/6523646/141336967-1d214195-6863-4d5a-9e57-8015153fa16c.png">
in reality it looks like:
<img width="509" alt="image" src="https://user-images.githubusercontent.com/6523646/141337154-890a60af-340e-4b9b-9e31-b6f27b36d31f.png">

Browsers: Current Chrome/Macos, Firefox,  Safari

**Comment by antobinary** [comment]
If I understand this report correctly, the issue is the discrepancy between what you see before opening the dropdown - i.e. 'Focus on presentation'
vs
what you see as selected once you open the dropdown - i.e. 'Smart layout' [localized in German] 

In case I misunderstood, please clarify

**Comment by JoVictorNunes** [comment]
Do you mean which "specification" exactly? I don't know if I understood the issue correctly. My understand is tha same as @antobinary's above. Or do you mean the absence of the toggle "Push layout to everyone" component below "Layout type"?

**Comment by joergmschulz** [comment]
Yes, I mean the absence of the toggle "Push..." .

https://docs.bigbluebutton.org/2.4/new.html under "Presenter can set viewers’ layout", there is the first image I pasted above, but in reality the 2nd image appears.

**Comment by JoVictorNunes** [comment]
Hmm, okay!

**Comment by JoVictorNunes** [comment]
@antobinary I will need your help here, is that a specification discrepancy or an implementation discrepancy?

**Comment by antobinary** [comment]
Ah, I see!

Yes, we recently switched ot just dropdown, not dropdown+toggle. The toggle was confusing some people, the current UX is clearer albeit a bit more verbose.

The "fix" here would be to update the screenshot in the docs...
@joergmschulz was everything else working as expected for you? We've done some group testing of the push layouts and found them to be working correctly but please report if you spotted anything odd

**Comment by joergmschulz** [comment]
Good - then only the documentation needs to be fixed. 
Yes, the push of the layouts has worked very good, we had a very agreeable session using this push functionality. I am positively surprised about the quality of this release candidate. 
As my system is .de, I will not create a PR for the documentaion, sorry. Thanks for your work on this tool. Instead of closing the issue, I change the title to have this a reminder of a fix to the doc. Ok? If not, you may close the issue.
