### ISSUE TITLE
Learning Dashboard uses different Favicon

### ISSUE THREAD

**Issue by easy-bios** [bigbluebutton/bigbluebutton#13683]
**Describe the bug**
If bbb is set up with custom Favicon, "Learning Dashboard" Site uses different (default bbb) Favicon.

**To Reproduce**
1. Go to 'any meeting'
2. Click on 'Learn-Dashboard'
3. See Browser Tab
4. See bbb Favicon no matter what Favicon you have set up in bbb

**Expected behavior**
Use same Favicon by default.

**Actual behavior**
Seperate bbb Favicon is used.

**BBB version:**
Server Version: 2.4-rc-4
Clientversion: 2378

**Comment by hostbbb** [comment]
https://github.com/bigbluebutton/bigbluebutton/blob/develop/bbb-learning-dashboard/public/favicon.ico  here is the learning dashboard favicon.

Where the default BBB is at /var/www/bigbluebutton-default/favicon.ico

Just need to change this to customize the learning dashboard
