### ISSUE TITLE
Support slideslive video stream sharing

### ISSUE THREAD

**Issue by dreamflasher** [bigbluebutton/bigbluebutton#13685]
**Is your feature request related to a problem? Please describe.**
Neurips (and other big conferences) use slideslive video stream to share their content. Currently it's not possible to share this streaming service via big blue button.

**Describe the solution you'd like**
support slideslive video stream sharing

**Describe alternatives you've considered**
Stream via screen share. Problem: Low quality, depending on internet connection of host, video not smooth, audio and video drop.

**Comment by hostbbb** [comment]
Just checked out Nuerips. are you looking to use recorded video/slide content in bbb session?   or want to be able to view live conference in BBB?

**Comment by dreamflasher** [comment]
Use recorded video content.

**Comment by dreamflasher** [comment]
push

**Comment by dreamflasher** [comment]
Push
