### ISSUE TITLE
[2.4-rc4] Waiting users list sometimes hard to access

### ISSUE THREAD

**Issue by PhMemmel** [bigbluebutton/bigbluebutton#13695]
**Describe the bug**
On some screen resolutions or window sizes, especially when using the "focus on video" or "focus on presentation" layout, the users list of the waiting room gets cut off and can only be accessed again by zooming out, changing the layout or - if possible - enlarging the window.

This is a minor bug, but I had users who were very confused that they can't see the waiting users and couldn't figure out a workaround, especially when the list was completely hidden (so it wasn't obvious that it was "just" hidden behind the videos/presentation).

**To Reproduce**
1. Open session, enable waiting room
2. Shrink your window or zoom in (enlarge font, ctrl + "+", ctrl+mousewheel, whatever) by a "sufficient" amount
3. Let guest join
4. See missing list -> screenshot

**Expected behavior**
Rest of the waiting room panel mustn't use the complete space vertically so that the list is there and at least scrollable

**Actual behavior**
List not visible/accessible

**Screenshots**
![grafik](https://user-images.githubusercontent.com/65113153/141815584-e14fcfd8-9f55-4091-bef1-ee2c275d1cf1.png)

**BBB version:**
current test24.bigbluebutton.org (Client build 2378)

**Desktop (please complete the following information):**
Tested on current Chrome on Win10, reported by MacBook user with Safari (apparently this happened without zooming in etc.), so the default window size/proportions/screen resolution on such devices might be problematic?

**Smartphone (please complete the following information):**
Should be checked as well, maybe there is a similar problem

**Comment by antobinary** [comment]
With the changes from #13690 I see a scrollbar which allows me to see all awaiting guests.

![Screenshot from 2021-11-17 11-30-19](https://user-images.githubusercontent.com/6312397/142241302-234a5418-3c98-4182-8858-bf8cd160099f.png)

I believe this issue is now resolved. Please comment if there is still a desired change in this area
