### ISSUE TITLE
Finished room reported as running in 2.4-rc4

### ISSUE THREAD

**Issue by vasylOstrovskyi** [bigbluebutton/bigbluebutton#13692]
**Describe the bug**
After finishing meeting, the room is still reported as active, attempt to reconnect freezes at three dots.

**To Reproduce**
1. Remove properly running bbb 2.3.15 by removing all packages containing 'bbb" or "kurento" in their names. 
2. Install 2.4-rc4 by script (the same as for 2.3 but changed version bionic-240)
3. Start a new session (e.g, from greenlight; I tested with my custom application, too). Do something no matter what. Finish the meeting. 
4. On the application page (greenlight), instead of "Start" I see "Join' button; in the management section of greenlight I see that room as running. My custom application also reports the room as still running.
5. Try to join the meeting; see frozen three dots. No errors in browser console.
6. Selecting other room in greenlight, I can start it, and other users can join that room; however, finishing the room makes it still running and thus unusable. Now, in the management section of greenlight I see that both room as running.
7. Remove 2.4, reinstall 2.3.15, it works fine.

**Expected behavior**
Finished meeting should be reported by API as not running

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser: Latest Chromium

As I remember, I noticed this issue after update from 2.4-rc2 to 2.4-rc3, and I had to roll back to 2.3 branch. Reloading page and clearing browser cache does not help, the only remedy was bbb-conf --restart

**Comment by vasylOstrovskyi** [comment]
Update: Tried using api mate. When the meeting is finished (from within bbb of by 'end' api call), 'getMeetingInfo' still returns 'Success' an reports meeting with 'running' true and list of all attendees.
Rolled back to 2.3.15 with the same configs; as expected, for finished meeting 'getMeetingInfo' returns 'Failed' - notFound
Tried to reinstall 2.4-2.3-2.4 several times with the same result: 2.3 works fine, 2.4 has issue.
Is this my fault, or bbb issue?
TIA
Vasyl

**Comment by vasylOstrovskyi** [comment]
Update: This improper behavior is triggered by the following configuration option
learningDashboardCleanupDelayInMinutes=252000
which I included into /etc/bigbluebutton/bbb-web.properties to keep learning dashboard data for future analysis.
When I remove this option, the system works properly, when I enable it again - the issue is back.
Regards,
 Vasyl

**Comment by ffdixon** [comment]
Thanks Vasyl for digging into this issue -- much appreciated!
