### ISSUE TITLE
Disable Download in external Video-Player

### ISSUE THREAD

**Issue by demlak** [bigbluebutton/bigbluebutton#13691]
When we embed an external mp4 video file with the external-video-player, we need to make the download of external video a little bit more difficult (we know, that we can't prevent for 100%).

So we want to inject something like `controlsList="nodownload"` and/or `oncontextmenu="return false;"`

How to do so? Where to inject?

thx in advance

**Comment by hiroshisuga** [comment]
If you mean preventing an easy download of a "meeting record" from the playback app, this PR may do the job.

https://github.com/bigbluebutton/bbb-playback/pull/130

**Comment by demlak** [comment]
thx.. but no.. as the topic says: i want to prevent download of external videos in external video-player

**Comment by demlak** [comment]
maybe, it has something todo with this: `bigbluebutton-html5/imports/ui/components/external-video-player/component.jsx`
but i can't find this file in our installation.

**Comment by ali-alhaidary** [comment]
Are you referring to only the mp4 part of the presentation?

**Comment by demlak** [comment]
https://user-images.githubusercontent.com/11285006/141638438-74ef4095-8292-4a25-90ef-bae28d275152.mp4

i am talking about the external player.. when playing a file (in this example mp4)

**Comment by hiroshisuga** [comment]
I know what you mean. Why don't you upload it to YouTube and share it by URL?

**Comment by demlak** [comment]
well.. when i want people not to download.. for sure i want it not to be on google servers instead..

we have license to show internaly.. not publishing it.. for sure, we are not responsible for what the audience will do.. but we want to have an extra step..

BBB embedds the video with `<video>`-tag.. in a stanard html file it is easy to archive the wanted behaviour..
but bbb is different.. it generates the HTML output on the fly - as far as i know..
since i am not a coder, this makes it difficult to me, to find the correct place to inject those simple control-settings.

**Comment by hiroshisuga** [comment]
Understood. It can happen at every educational scene.
Although you say you are not a coder, modifying the code and deploy it to your own server is not very difficult. Everything is nicely described here:
https://docs.bigbluebutton.org/2.4/dev.html#developing-the-html5-client

Modifying the deployed code directly would be much more difficult as the code is shaped more streamlined so that the server can execute it faster.

**Comment by demlak** [comment]
thx for the hint. i'll take a look if the work is bigger as the benefit. it seems it is more work =)

**Comment by hiroshisuga** [comment]
If you really want to try, /usr/share/meteor/bundle/programs is the place where the HTML5 client code is placed.

**Comment by haviduck** [comment]
not tried it but this looks promising:

https://github.com/bigbluebutton/bigbluebutton/blob/30a96eb405aa69a74a41d58d564ce6be79633b8c/bigbluebutton-html5/imports/ui/components/external-video-player/component.jsx#L91

**Comment by demlak** [comment]
auto-closing as "completed" is a "no go"
