### ISSUE TITLE
Webcams: video pinning

### ISSUE THREAD

**Issue by prlanzarin** [bigbluebutton/bigbluebutton#13702]
**Is your feature request related to a problem? Please describe.**

There's no way to pin a specific webcam right now, which means webcams may be rotated out of the current video page when audio floor switching is activated.

Video pinning is specially important for document cameras and/or interpreter cameras.

**Describe the solution you'd like**

- [ ] Add a bbb-html5 configuration to toggle the feature
- [ ] Add a video pin toggle to the camera container dropdown (where focus lies) and, maybe, to the user list entries for those who have active cameras
  * Pinning an user's camera via the container dropdown interface implies pinning **all** of that user's cameras
  * Pinning via the user list entry implies pinning **all** of that user's cameras
- [ ] Extend akka-apps camera models and Meteor's/Mongo's equivalent to include a `pinned` Boolean field
- [ ] Pin
  * Only moderators should be able to
  * No more than 1 camera should be pinned simultaneously
  * Client should request a pin to akka-apps; request would be validated and executed and then propagated back to clients
  * In the client: filter the pinned stream out of the page accounting just like the local camera is already filtered out. See: https://github.com/bigbluebutton/bigbluebutton/blob/d7df8dd048fa299b0b1217e46b5ce20c72a9b640/bigbluebutton-html5/imports/ui/components/video-provider/service.js#L368
- [ ] Unpin
  * Only moderators should be able to
  * Pinning camera X while camera Y is already pinned implies an unpin action
  * Client should request an unpin to akka-apps; request would be validated and executed and then propagated back to clients
  * In the client: see the previous item

**Comment by schrd** [comment]
@prlanzarin a pinned video should imply that bandwidth throttling should not be applied to this stream. I bet that sign language interpreter with 180px@3fps is barely usable.

**Comment by prlanzarin** [comment]
> @prlanzarin a pinned video should imply that bandwidth throttling should not be applied to this stream. I bet that sign language interpreter with 180px@3fps is barely usable.

There's no underlying mechanism in place to filter streams out of quality limiters, so while that's correct it'll be mapped as a subsequent enhancement request once pinning lands (much like https://github.com/bigbluebutton/bigbluebutton/issues/11764 was materialized).

**Comment by prlanzarin** [comment]
Fixed in #13835 

(which already exempts pinned cameras from the quality limiter)
