### ISSUE TITLE
Spatial audio, to make group conversations easier to follow

### ISSUE THREAD

**Issue by Dave-B** [bigbluebutton/bigbluebutton#13712]
Problem:
When more than one person is talking at once it can be hard to understand anyone.

Solution:
Spatial audio - positioning each participant in a simulated 3D audio volume - should allow easier discernment of what people are saying when they are talking over each other (and may also help even when they're not).

Headphones aren't required, but can make it more effective.

Here's a demonstration of the principle: https://www.highfidelity.com/

**Comment by ffdixon** [comment]
Cool.  Are you aware of any open source solutions for spatial audio?

**Comment by Dave-B** [comment]
Sorry, there appears to be code out there, but I'm not familiar with any of it.

This looks like the sort of thing: https://github.com/3DTune-In/3dti_AudioToolkit
Or maybe something from this topic might be suitable: https://github.com/topics/3d-audio

**Comment by schrd** [comment]
There are headsets on the market which have only one speaker for one ear. When we enabled stereo in freeswitch, we had complaints from users with such a headset who missed parts of the conversation.

**Comment by niklaskorz** [comment]
The web audio API supports spatial audio out of the box. There is also https://resonance-audio.github.io/resonance-audio/ by Google which adds reverb effects on top. If you want to compare them yourself, see https://github.com/niklaskorz/audio3d and https://niklaskorz.github.io/audio3d/.

**Comment by ffdixon** [comment]
Took a quick look at [audioed](https://niklaskorz.github.io/audio3d/), but it looks like you need to install an extension.

<img width="515" alt="image" src="https://user-images.githubusercontent.com/290351/155991976-29d15e5f-115b-4053-971a-ae92fab5f4db.png">

Do you have an example of spacial audio with Web Audio API without requiring an extensions?

**Comment by niklaskorz** [comment]
You don't need to install it, just click cancel. Chrome is just offering to install it as a Progressive Web App, which has nothing to do with browser extensions.

**Comment by niklaskorz** [comment]
Besides that, see this MDN page: https://developer.mozilla.org/en-US/docs/Web/API/Web_Audio_API/Web_audio_spatialization_basics
