### ISSUE TITLE
updating ar.json

### ISSUE THREAD

**Issue by ali-alhaidary** [bigbluebutton/bigbluebutton#13732]
**Describe the bug**
ar.json was updated and needs to be pulled from transifex.

**Comment by ali-alhaidary** [comment]
> Hi @ali-alhaidary What BigBlueButton release are you referring to? 2.3 or 2.4? We've been pretty consistent in pulling the locales as one of the last steps before a BBB release, thus including the latest changes regularly.

We made some updates to 2.4 to fit in new devices screens and to be consistent with others (moodle, GreenLight, ...), however, I am sure you will be pulling them for rc5, so many thanks...

**Comment by ali-alhaidary** [comment]
Applied the same on 2.3 for next update...

**Comment by antobinary** [comment]
Addressed in https://github.com/bigbluebutton/bigbluebutton/pull/13744

Given that we pull all the locales as part of each release there is no real need to open issues or pull requests to update an individual locale.
