### ISSUE TITLE
New join parameter, skip listen-only on first join only

### ISSUE THREAD

**Issue by Rortar** [bigbluebutton/bigbluebutton#13751]
**Is your feature request related to a problem? Please describe.**
A common configuration for minimizing the number of interactions on client load is

> userdata-bbb_auto_join_audio=true
> userdata-bbb_skip_check_audio=true
> userdata-bbb_skip_check_audio_on_first_join=true

In this setup however, if a microphone issue prevents you from joining the call, you are unable to hear the presenter and need to re-join the meeting with a different URL in order to do so.

**Describe the solution you'd like**
Introduce new parameter 

> userdata-bbb_skip_listen_only_mode_on_first_join=true/false

this way, if there are microphone issues preventing the user from joining the call, they will be able to fall back to listen-only mode to hear the presenter by hanging up and joining the audio again via the UI button.

**Describe alternatives you've considered**
We have looked into using the lock feature to remove access to the microphone, however, we already use this to restrict webcam viewing so it isn’t an option. That’s left us with having to monitor sessions and email ‘listen-only’ links to attendees.

**Comment by misisol** [comment]
This is a very handy and useful option to have, hope to have it in the 2.4 version.
