### ISSUE TITLE
2.4 rc-3/4 - bug - data savings on/off not saving state

### ISSUE THREAD

**Issue by Jossef-767** [bigbluebutton/bigbluebutton#13750]
when "Enable other participants webcams" setting is "off", and turned "on", refreshing page will revert to "off" state.

**To Reproduce**
1. go to:  Settings > Data savings
2. turn OFF "Enable other participants webcams" and save 
3. see that webcams will Will turn off successfully on client
3. go to:  Settings > Data savings
4. turn ON "Enable other participants webcams" and save 
5. refresh web page  

**Expected behavior**
see Other participants' webcams.

**Actual behavior**
no  webcams. "Enable other participants webcams" is OFF

**Comment by JoVictorNunes** [comment]
This is an interesting situation. Keeping the settings after the refresh and implementing a 'Reset Settings' button to restore to default settings would be interesting.
