### ISSUE TITLE
FreeSWITCH failed to start

### ISSUE THREAD

**Issue by Pj1017** [bigbluebutton/bigbluebutton#13771]
I am facing an issue with FreeSWITCH, please check the details below

 Error: Unable to connect to the FreeSWITCH Event Socket Layer on port 8021

![error](https://user-images.githubusercontent.com/95181737/143777390-c1cc142c-b9da-46a9-87af-a615196bf33b.png)

**Comment by ffdixon** [comment]
Hi there, can you post this to bigbluebutton-setup and we'll help you there.  If you've encountered a bug, we'll open an issue here to track it.

When you post, please check to see if FreeSWITCH is running and [provide as much information as you can](https://docs.bigbluebutton.org/support/getting-help.html#help-installing-or-running-bigbluebutton).

**Comment by Pj1017** [comment]
I am unable to post this to bigbluebutton-setup and FreeSWITCH is not running. It is getting failed to start as shared in the image. In FreeSWITCH logs it is showing that FreeSWITCH getting failed to connect to ESL.
