### ISSUE TITLE
 The network status screen does not display the user status icon for the user.

### ISSUE THREAD

**Issue by ali-alhaidary** [bigbluebutton/bigbluebutton#13779]
**Describe the bug**
The network status screen does not display the user status.

**To Reproduce**
1. Go to a session
2. Click on network status.

**Expected behavior**
The network status icon (multi-bar) is displayed.

**Actual behavior**
The network status icon (multi-bar) is not displayed.

**BBB version:**
BigBlueButton continually evolves. Providing the version/build helps us to pinpoint when an issue was introduced.
Example:
$ sudo bbb-conf --check | grep BigBlueButton 

BigBlueButton Server 2.4-rc-5 (2715
![Screenshot 2021-11-29 at 09-59-40 المجلس - غرفة درس التلاوة - شكل حالة الاتصال](https://user-images.githubusercontent.com/75235623/144006899-61777819-2ada-4309-81fb-6992784eb90f.png)
)

**Comment by antobinary** [comment]
Hi @ali-alhaidary 
Any chance you could draw an arrow on the screenshot or clarify further which area is not displayed properly for you?

**Comment by ali-alhaidary** [comment]
@antobinary Thank you. As seen in the screen shot there are two users in the room, however, only one status was shown in the network status box.My network status was not shown, only the other person network is shown.

**Comment by ali-alhaidary** [comment]
Thanks, looking forward for v2.5...
