### ISSUE TITLE
[2.4-rc5] Fullaudio: no outgoing audio

### ISSUE THREAD

**Issue by PhMemmel** [bigbluebutton/bigbluebutton#13774]
**Describe the bug**
Connection not properly established in fullaudio bridge.
I'm not sure if this is a bug or a configuration problem, but wanted to share my feedback.

**To Reproduce**
1. Enable fullaudio for a session like documented in the official docs.
2. Join session and connect audio.

Result:
Connection seems to be established fine, I can hear the freeswitch sound ("You're the only one in the session"). Firefox' about:webrtc shows data flowing from and to the server. No sound is going from my microphone(s) to the server though. No error is shown, neither in the browser's console.

Trying to switch the microphone leads to:
![grafik](https://user-images.githubusercontent.com/65113153/143897955-077b43b9-86a7-450e-95b4-10d30b0c9cec.png)

and there is no popup triggered in Firefox to allow access to this specific microphone.
Still no outgoing sound though.

After a long time (minute(s)?) an audio connection reconnect is triggered:
![grafik](https://user-images.githubusercontent.com/65113153/143899251-6651fcec-f2db-4682-91d3-6b90ab5dc839.png)

**Expected behavior**
Fullaudio sound should work :-)

**Actual behavior**
I can only hear, but can't speak :-(

**Desktop (please complete the following information):**
 - Tried on Win10, current Firefox 64bit, also tried on Chrome

**Additional context**
I'm not sure if this is a bug or a problem with my server configuration, I just wanted to share. I'm using mediasoup for video, listenonly and screenshare, I set 
`userdata-bbb_skip_check_audio=true` and `meta_fullaudio-bridge=fullaudio` for this session. I also have `public.kurento.signalCandidates` set to `false`. My server is running behind NAT, not sure if this is relevant. Mediasoup itself without fullaudio is working great, however this probably isn't related as the external SDP in about:webrtc shows that I'm connected to kurento.

Just tested on https://test-install.blindsidenetworks.com/ with same parameters, seemed to work properly, so might be a network/configuration issue of my server.

**Comment by vasylOstrovskyi** [comment]
The same thing. Installed 2.4-rc-5 on clean VM behind NAT with all default settings. Works fine. Then configured fullaudio exactly as written in the manual. Audio connection speed is impressive, but no sound from any microphone from my laptop or mobile. NAT forwards all tcp/udp ports to VM as is.
Regards,
Vasyl

**Comment by ffdixon** [comment]
This feature of using Kurento to enable media connections for FreeSWITCH is experimental and incomplete. We don't recommend on using it in production. 

https://docs.bigbluebutton.org/2.4/new.html#faster-audio-activation-using-fullaudio-bridge-experimental


We'll be working on this in 2.5

**Comment by prlanzarin** [comment]
I'm pretty sure I've fixed this in https://github.com/bigbluebutton/bbb-webrtc-sfu/releases/tag/v2.6.4 (lands on next v2.4 tag).
Closing. Re-open if you find out it's still broken somehow in v2.4.something.

P.S.: The fact that input stream change is not implemented yet in the client is a separate issue and should be handled accordingly.

**Comment by PhMemmel** [comment]
@prlanzarin Can confirm: It works on 2.4-rc6 (except switching microphones as you mentioned)! Good job and thank you very much!
