### ISSUE TITLE
Cannot create breakout rooms via API

### ISSUE THREAD

**Issue by OguzhanCicek** [bigbluebutton/bigbluebutton#13772]
Hello,

after successfully creating a meeting room via the API im trying to add breakout-rooms to this meeting. The API Call to create the breakout room successfully returns with moderator/attendeePW. If i check the main meeting room with the API Call getMeetingInfo i can
also see that the created breakout room is listed there with all the right parameters like freeJoin. 

The Problem is that on the Webpage (in the meeting) the breakout rooms are not visible/listed. Am i missing something obvious or is this a bug?

**Comment by antobinary** [comment]
Possible duplicate of https://github.com/bigbluebutton/bigbluebutton/issues/12084
