### ISSUE TITLE
Remove/disable 'End meeting' action

### ISSUE THREAD

**Issue by MWWorks** [bigbluebutton/bigbluebutton#13784]
**Is your feature request related to a problem? Please describe.**
Some meetings include multiple external presenters who may not be fully familiar with BBB. When their session is finished, they sometimes choose 'End meeting' thinking it will log them out - thus ejecting everyone.

**Describe the solution you'd like**
Some way to remove the 'End meeting' option. Either per user (eg when joining via API) or globally (eg in bbb-html5.yml). It's not really needed since meetings end automatically, and if I really need to end one I can do so via the API.

**Describe alternatives you've considered**
Telling presenters not to do this - they may not remember, especially if they are only occasionally using BBB.

**Comment by AhmadrezaP** [comment]
Hey, I think it's better to make them all Viewer and once they want to present, make them presenter by clicking on their name and  the button "Make presenter"

**Comment by MWWorks** [comment]
Perhaps, but they may swap fairly frequently and it's then awkward to have somebody manage this; also demoting them to viewer then makes it unclear clear in the user list who the presenters actually are.

I found issue #7787 a while back to disable the Leave meeting/logout action, which was added - I see this as an extension of this that...

**Comment by AhmadrezaP** [comment]
Yes it's tough to manage this especially when you are allowed to make only one user presenter but a presenter has an icon on his avatar that demonstrates that he/she is the presenter in the users list.
Your comment is rational and I agree with you.

**Comment by ffdixon** [comment]
> Some meetings include multiple external presenters who may not be fully familiar with BBB. 

You want to make these people the a presenter, not moderator.  The presenter has full control of the presentation area, but no more.  In contrast, making them a moderator allows them to end the meeting, mute other people, kick others out, etc.

In general, only the teacher should be the moderator.  By default the first moderator is also the presenter, but a moderator (and a meeting can have multiple moderators) can make anyone else presenter.

**Comment by ffdixon** [comment]
![image](https://user-images.githubusercontent.com/290351/144762223-f616bc3c-7127-4649-a026-30a3278ab47a.png)

**Comment by MWWorks** [comment]
Fred, many thanks for the reply. This is a good point, but just making them the presenter relies (I think) on having a moderator to reassign presentership back to somebody else.

What I sometimes have is a group of participants, a separate 'panel' of presenters, who will dip in and out of being presenter (and without having to ask the moderator to do so). Making them moderators also makes it clear in the user list who the presenters are.

This works except for some of them not understanding/remembering that 'End meeting' ends the whole thing!

I tried to bodge it with CSS but there's no unique selector for that menu item. I figure this is a similar use case to the issue #7787 I mentioned?

Either way, thanks for the awesome work :)

**Comment by ffdixon** [comment]
> Either way, thanks for the awesome work :)

Thanks!  It's a [team effort](https://github.com/bigbluebutton/bigbluebutton/graphs/contributors).

**Comment by martinhelfrich** [comment]
I think the main issue is that taking presenter is on the same permission level as ending the meeting.

So another solution could add an option that allows all users to "take presenter". Then we don't need to make everyone a moderator that frequently wants to present.
