### ISSUE TITLE
RTL default presentation name is not displayed in RTL characters

### ISSUE THREAD

**Issue by ali-alhaidary** [bigbluebutton/bigbluebutton#13782]
**Describe the bug**
RTL default presentation name is not displayed in RTL characters. if as session starts with a predefined presentation with RTL name, then it will be shown as hex numbers in the (manage presentation) menu, however, if the same presentation is uploaded directly from in the session, has it been RTL or LTR, the name will be displayed correctly.

**To Reproduce**
1. Go to a session with predefined presentation.
2. Click on (+) to upload a presentation.
3. The new presentation will be dispelled.
4. Click on (+) to return to the preloaded presentation.
5. The preloaded presentation name will be shown as string of hex numbers. 

**Expected behavior**
The predefined presentation name should be displayed correctly in RTL.

**Actual behavior**
The predefined presentation name is not displayed correctly in RTL, instead, the name is series of hex numbers.

**Screenshots**
screenshot is attached.

**BBB version:**
BigBlueButton Server 2.4-rc-5 (2715)

![Screenshot 2021-11-30 at 15-32-01 المجلس - غرفة درس التلاوة - Default](https://user-images.githubusercontent.com/75235623/144049032-18f746b1-37b5-4d3b-85ef-bf72ded28f50.png)

**Comment by antobinary** [comment]
Related https://github.com/bigbluebutton/bigbluebutton/issues/7479
and
https://github.com/bigbluebutton/bigbluebutton/issues/8433

I believe this issue can be merged in 8433.

**Comment by ali-alhaidary** [comment]
@antobinary , Could be, but, https://github.com/bigbluebutton/bigbluebutton/issues/7479 and https://github.com/bigbluebutton/bigbluebutton/issues/8433 are talking about the internal RTL encoding, which is also an issue, but I am referring to the RTL preloaded presentation name, which is displayed fine if uploaded from the html5 client directly.
