### ISSUE TITLE
Android vertical camera format does not work

### ISSUE THREAD

**Issue by rob0403** [bigbluebutton/bigbluebutton#13795]
**Describe the bug**
When you log in to a BBB session using Android (in my case Google Pixel 3a and Android 12 on mediasoup 2.4 rc5) the video sharing does not work properly in vertical view (see screenshot). This is not seen by the sharer himself but only by other participants. As soon as I go to horizontal view and restart the camera everything works fine.

**To Reproduce**
1. Log in to BBB (I reproduced it on 2.4 rc5) using an android device and a second device
2. Be in vertical mode of the android device an start camera sharing
3. The camera looks fine on the device which is sharing but not on the other device

**Expected behavior**
Camera sharing should also work in vertical mode.

**Actual behavior**
The camera share does only work properly on android in horizontal mode but not in vertical mode.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/15635417/144206570-00aa732f-b061-41c2-818e-e7ec022f023b.png)

**BBB version:**
2.4 rc5 on mediasoup

**Desktop (please complete the following information):**

- desktop: in my case Chromium 96 on kubuntu 21.10 (but probably valid for all devices)

**Smartphone (please complete the following information):**
 - mobile: Google Pixel 3a (Android 12)
 - Browser: Firefox and Google Chrome

**Comment by PhMemmel** [comment]
I've seen this exact picture with an Android phone in portrait mode on a different video conferencing platform (also no problems in landscape mode there). According to `about:webrtc` they are using janus as media server. It's a Google Pixel 4a, Android 12.

**Comment by prlanzarin** [comment]
Is this reproducible in:
  - test24.bigbluebutton.org
  - https://webrtc.github.io/samples/src/content/peerconnection/pc1/
  - https://appr.tc
  
[?]

**Comment by rob0403** [comment]
Yes, it is. Portrait mode never works but landscape mode does.

**Comment by prlanzarin** [comment]
Then it's a browser + environment (Pìxel, Android) issue. It doesn't seem to stem from BBB.

I'm a bit short on time right now to traverse through Chromium's/Firefox's/Android bugtrackers. I recommend checking whether there are equivalent/similar issues opened there.

**Comment by rob0403** [comment]
This looks kind of familiar: https://bugs.chromium.org/p/chromium/issues/detail?id=1237677
But since this is no BBB issue I think you can close it for now. Thanks for the fast reply!

**Comment by prlanzarin** [comment]
Re-open if necessary.
