### ISSUE TITLE
User consent for video recording while being in the session

### ISSUE THREAD

**Issue by Sedo87** [bigbluebutton/bigbluebutton#13799]
**The problem to be solved:** "sometimes" the coaches need to record a 1:1 session and have to ask verbally the student if he/she can record the session while they are in the room... If the student accepts, they would start the recording... Therefore they would somehow need to see if the user gave consent digitally and then start the recording... 

**Feature:** "As a coach, when I click on the recording button in a 1 to 1 session with my student, I would like that a modal with a consent request pop up for my student,  it can be accepted or declined, so that I can have a proof of consent before the recording starts."

**Note:** I know in Greenlight there is a solution to get consent before joining a session, but how likely do you think in the future you might cover such a case like ours? Getting the consent after joining a session, because we don't record all the sessions...

For example, Zoom has another approach... They show a modal that pops up saying: "This meeting is being recorded by the host or participant.", and "Got it" - "Leave meeting" options there are...

Or would you recommend any other way to solve this? Thank you.

**Comment by antobinary** [comment]
Added in 2.6.0-alpha.1, see https://github.com/bigbluebutton/bigbluebutton/pull/14593
