### ISSUE TITLE
Attendee blocked from sharing his audio when the random user is on and an external video is shared

### ISSUE THREAD

**Issue by GhaziTriki** [bigbluebutton/bigbluebutton#13794]
**Describe the bug**
When an attendee joins a room with a random user selected and an external video being shared, he cannot share his audio.

**To Reproduce**
Steps to reproduce the behaviour:
1. Join as moderator "Teacher"
2. Join the same room as attendee "Student 1"
2. Join the same room as attendee "Student 2"
4. As moderator play an external YouTube video "https://www.youtube.com/watch?v=pkd_F8hJwgM"
5. As a moderator random select a user.
6. Join the same room as attendee "Student 3"
7. As "Student 3" try sharing audio...it won't work.

**Expected behaviour**
Student 3 must be able to normally share his audio.

**Actual behaviour**
The random selected user is displayed before the audio setting window. If you try to share audio the button is blocked. Worse in some cases the random user windows keeps opening when you close it. The audio windows closes and says it lost audio connection.

**Screenshots**
![image](https://user-images.githubusercontent.com/4991088/144202656-c89892b6-1393-4339-ba9f-d0a05a59c08f.png)

**BBB version:**
BigBlueButton Server 2.3.15 (2495)

**Desktop (please complete the following information):**
 - OS: Windows & Mac
 - Browser Chrome Mac & Firefox Win11

**Comment by antobinary** [comment]
Looks like this is closely related to https://github.com/bigbluebutton/bigbluebutton/issues/13448
