### ISSUE TITLE
Analytics actor tweak required

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#13791]
We received a report for logs containing `ERROR o.b.core.running.MeetingActor - Failed to map username for id v_102`

v_102 looks like a voice user id

Update - looks like some web userids are also included in this error report  i.e.`w_abcd...` 

Likely caused by https://github.com/bigbluebutton/bigbluebutton/pull/12559/files#diff-d01261861f866873c7de915f32977da450134df3d1b53c87e0e467cf3ee5c6d0R601

related https://github.com/bigbluebutton/bigbluebutton/pull/12559

**Comment by zhem0004** [comment]
It has been fixed in modification of file `akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/voice/UserJoinedVoiceConfEvtMsgHdlr.scala` in #14344

The actor could not map the id as the user was not fully registered, but now it is
