### ISSUE TITLE
Error installing on ubuntu 18

### ISSUE THREAD

**Issue by taremans** [bigbluebutton/bigbluebutton#13811]
After installation from: 
wget -qO- https://ubuntu.bigbluebutton.org/bbb-install.sh | bash -s -- -v bionic-240 -s meetingsXXXXXXcom -e info@XXXXXX.com  -a -w -g 

## I got this error:

 Potential problems described below
 Not running:  tomcat8 or grails
................................................................................
 Error: Could not connect to the configured hostname/IP address

   https://meetings.XXXXXXXXXXX.com/

 If your BigBlueButton server is behind a firewall, see FAQ.

 Warning: The API demos are installed and accessible from:

   https://meetings.XXXXXXX.com

 and

   https://meetings.XXXXXXXXX.com/demo/demo1.jsp

 These API demos allow anyone to access your server without authentication
to create/manage meetings and recordings. They are for testing purposes only.
If you are running a production system, remove them by running:

  apt-get purge bbb-demo

# And bbb-conf --status Result is:

bbb-conf --status
nginx —————————————————► [✔ - active]
freeswitch ————————————► [✔ - active]
redis-server ——————————► [✔ - active]
bbb-apps-akka —————————► [✔ - active]
bbb-fsesl-akka ————————► [✔ - active]
tomcat8 ———————————————► [✔ - active]
mongod ————————————————► [✔ - active]
bbb-html5 —————————————► [✔ - active]
bbb-webrtc-sfu ————————► [✔ - active]
kurento-media-server ——► [✔ - active]
bbb-html5-backend@1 ———► [✘ - failed]
bbb-html5-backend@2 ———► [✘ - failed]
bbb-html5-frontend@1 ——► [✘ - failed]
bbb-html5-frontend@2 ——► [✘ - failed]
etherpad ——————————————► [✘ - failed]
bbb-web ———————————————► [✔ - active]

The BBB not working

How should I fix this issue?

**Comment by antobinary** [comment]
Hi @taremans 
The best place to get help for BBB setup is the bbb setup group https://groups.google.com/g/bigbluebutton-setup

Please start a thread there or search look through the existing threads and you may spot what's tripping you.

That said, bbb-html5 backends and frontends are not running. Could you paste the output of `sudo journalctl -u bbb-html5-backend@1`

**Comment by taremans** [comment]
This is the result of sudo journalctl -u bbb-html5-backend@1
[journal.txt](https://github.com/bigbluebutton/bigbluebutton/files/7643560/journal.txt)

**Comment by antobinary** [comment]
```
Dec 02 14:17:00 vmi740836.contaboserver.net systemd_start.sh[1092]: error: uncaughtException: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379
Dec 02 14:17:00 vmi740836.contaboserver.net systemd_start.sh[1092]: Error: connect ECONNREFUSED 127.0.0.1:6379
Dec 02 14:17:00 vmi740836.contaboserver.net systemd_start.sh[1092]:     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:16) {"error":{"errno":-111,"code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":6379},
```

This means that Redis is not running. Redis pubsub is a mandatory dependency for BBB - your meetings won't run if Redis is down.

Could you please check `sudo journalctl -u redis-server` to see what's going on, why it's not starting

**Comment by antobinary** [comment]
https://github.com/bigbluebutton/bigbluebutton/issues/12031 is related but looks like we didn't get further than this

**Comment by antobinary** [comment]
https://github.com/bigbluebutton/bigbluebutton/issues/10989 is also related. Looks like we might be missing something related to the order of the services starting. I have not been able to reproduce it though, so I'd be curious if we unearth some further hint in this direction

**Comment by taremans** [comment]
Thank you I understand the error 
because the script is not installing Redis correctly so I installed it manually before starting the script and I changed the binding to the server IP while Mongodb listening to local IP 127.0.0.1 
once I changed it every thing worked fine

Thank you

**Comment by antobinary** [comment]
I'm glad you have it running now!
Could you please elaborate on the changes you had to make, specifically 

>  not installing Redis correctly

We're looking to improve what we have so installations run smoothly

**Comment by taremans** [comment]
Sure
Kindly find attached file that has the error happened after running the scrip.


[installation Error.txt](https://github.com/bigbluebutton/bigbluebutton/files/7644409/installation.Error.txt)

What I figured is my server has disabled IP V6
That's why Redis Server is not starting which cause the interruption in the installation.

One I changed  bind  in 
###  #/etc/redis/redis.conf
 from :   bind 127.0.0.1 ::1 
To: bind 127.0.0.1

And rerun the script installation finished successfully

Then I fixed FreeSWITCH binding as mentioned here:
https://docs.bigbluebutton.org/support/troubleshooting.html#freeswitch-fails-to-bind-to-port-8021

the system was working fine.

**Comment by antobinary** [comment]
Thank you very much!
