### ISSUE TITLE
Customize HTML5 client while installed BBB using bbb-install.sh 

### ISSUE THREAD

**Issue by prp-e** [bigbluebutton/bigbluebutton#13828]
Hello guys. 

Assuming I have installed my BBB instance using `bbb-install.sh` (it means I have access to the API) and then, have my very own customized HTML5 client, which is based on the BBB's original HTML5 client. 
If it is possible, I'd be happy to have some guidance or documentations. 

Thanks.

**Comment by prp-e** [comment]
I still am looking for a solution.

**Comment by hostbbb** [comment]
if you compile the html5 dev client with the build script,  you can deploy this on your bbb servers.   If you want to automate, you can create a custom function in apply-lib, that will modify a stock build as a final step, brand the install, and move your custom built html5 binaries to proper place for production.
