### ISSUE TITLE
Accessibility issue with actions menu

### ISSUE THREAD

**Issue by WestphalDenn** [bigbluebutton/bigbluebutton#13820]
I am a blind user who uses BBB 2.4 RC 5 at the moment. In Firefox, pressing the shortcut ALT Shift A will visually open the actions menu but does not put screenreader focus into the menu. There seems to be no easy way to jump into the menu when it is opened. 

The options menu works perfectly fine though. So fixing the action menu might be pretty simple. Just mirror the behaviour when the options menu is opened to that of the actions menu. 

In Chrome, the issue exists as well. But here simply pressing the Tab-Key will jump into the menu. In Chrome, the options menu works perfectly fine as well.

**Comment by antobinary** [comment]
Hi @WestphalDenn @KDSBrowne 's fix should ship on BBB 2.4 with the upcoming release
