### ISSUE TITLE
Can not remove last presentation in the list

### ISSUE THREAD

**Issue by MichielDilissen** [bigbluebutton/bigbluebutton#13833]
**Describe the bug**
You can't remove the last presentation since BBB 2.3 (this worked for us in 2.2). 

**To Reproduce**
1. Don't set a default presentation
2. Add a presentation
3. Try to remove that presentation from the list
4. No error is shown, but clicking the delete icon does nothing. (it does work when you have multiple presentations in the list, but there is always at least one that can not be removed)

**Expected behavior**
The last presentation should be removable from the list. When this happens this list should be empty and users should not see any presentations.

**Actual behavior**
Clicking the delete icon of the last presentation does nothing. There is no error, but there is also no action that is being executed.

**BBB version:**
BigBlueButton Server 2.3.15 (1854)

**Additional context**
I would expect that presenters (moderators) can guide the guests (attendees) through a conference, and that guests can only see the presentation when the presenter wants this.

**Comment by antobinary** [comment]
Hi @MichielDilissen 

This has been refactored and addressed on BBB 2.4
Would you be able to confirm the behaviour is what you'd expect on test24.bigbluebutton.org ?

**Comment by MichielDilissen** [comment]
Thanks for your feedback. In version 2.4 this seems to work without any problems. We will update as soon as possible once a stable version has been released to resolve our issue.

I would like to note, that in this version a whole lot of the screen is reserved for the presentation placeholder (with text: Waiting for a presentation to be uploaded) when there are no presentations left. Although this does not seem optimal, we will be patient to wait for the stable release. Perhaps there will be a setting to hide the placeholder frame or maybe this functionality is already addressed when releasing a stable version.

Thanks again for your quick reply.
