### ISSUE TITLE
after couple of days everything stops working on 2.4

### ISSUE THREAD

**Issue by vahidajorloo** [bigbluebutton/bigbluebutton#13842]
after couple of days everything stops working i mean when i start a meeting and click on litsen only or microphon bbb stucks on connecting and at the end it says you left the audio meeting or something like that.also webcam would not start and screen sharing will stuck on loading but when i restart bbb-conf everything works fine for 3 to 5 days and then again the problems comes back.
this problem is on bbb 2.4 and we had no problems in 2.3 . `bbb-conf --check and bbb-conf --status` does not show any errors by the way . how can i solve this problem and can anyone tell me where is the main log file so i can read it and maybe find the issue?
*sorry for my bad english its not my native language*

**Comment by antobinary** [comment]
Hey @vahidajorloo 

Could you please collect the status of the services via `sudo systemctl status kurento-media-server bbb-* > issue-13842.log` read through the log file, upload it here.

If no obvious issue was spotted in the log please also copy-paste what you see when you collect logs via `sudo journalctl -f -u bbb-html5* -u bbb-apps-akka -u bbb-web -u bbb-webrtc-sfu -u kurento-media-server` and try to create a meeting / join / try to join audio and share webcam ?

**Comment by antobinary** [comment]
Let's reopen if you (or someone else) is able to reproduce on BBB 2.4.4+
