### ISSUE TITLE
server default for "mute users when joining" to "yes", but leave configurable for room owners

### ISSUE THREAD

**Issue by knarrff** [bigbluebutton/bigbluebutton#13857]
**Is your feature request related to a problem? Please describe.**

At the moment, a BBB admin has the choice to set "mute users when they join" globally to be one of only two options:
- active, not changeable by room owners   or
- inactive, changeable by room owners

This does two things at once: specify a default, and lock that default in one of the two cases.

**Describe the solution you'd like**

As an admin, I would like to be able to specify:
- active, changeable by room owners

This would provide the default we want, but leave the option open for room owners to change that default.

**Describe alternatives you've considered**

The only alternative for us would be to patch BBB ourselves. But we would like to avoid that for obvious reasons. :)

**Comment by test-erik** [comment]
It seems to me that this is a kind of a sub-request from https://github.com/bigbluebutton/greenlight/issues/1686

But let's see what people who know BBB say. This enhancement would be useful in any case.

**Comment by knarrff** [comment]
@test-erik : I guess you are right. On the other hand, that other ticket is closed and as such, hard to find and hardly used for future feature planning. This one is not (yet, at least).
