### ISSUE TITLE
The problem with Chrome 96

### ISSUE THREAD

**Issue by alissonjcguedes** [bigbluebutton/bigbluebutton#13851]
Hello, since updating google chrome to version 96. Chrome users can't access to rooms.
Using the test.bigbluebutton.org everything works.
FF, Edge or Safari works fine.
![image](https://user-images.githubusercontent.com/47307455/145089394-9ee8d3af-c7be-4fca-ac61-3f1a8c918ea1.png)

root@myserver:/# sudo dpkg -l | grep -i "kms\|gst\|kurento"
![image](https://user-images.githubusercontent.com/47307455/145089158-b3e3d2b1-a403-4108-9db4-d1630371cb6b.png)

**Comment by PhMemmel** [comment]
Your version of BBB is far too old. See #13843
