### ISSUE TITLE
Removing a user causes authentication loop for removed user

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#13863]
**Describe the bug**
Removing a user causes authentication loop for removed user.

**To Reproduce**
1. Create a session in 2.5-rc6 and join with two users: one moderator, one viewer
2. Remove the viewer

**Expected behavior**
Viewer displays a message such as "You have been removed from the conference."

**Actual behavior**
Viewer sees three dots as if the client is trying to rejoin.
  
https://user-images.githubusercontent.com/290351/145222203-ed737d31-6990-40cd-b0f5-58ccfe774d4d.mp4

**Screenshots**

Eventually the authentication times out.
![image](https://user-images.githubusercontent.com/290351/145222647-d033027b-2b10-47c9-a018-93350c18057c.png)

Browser log attached.

**BBB version:**
BigBlueButton continually evolves. Providing the version/build helps us to pinpoint when an issue was introduced.
Example:
$ sudo bbb-conf --check | grep BigBlueButton
BigBlueButton Server 2.4-rc-6 (2761)

Used latest version of Chrome to test Version 96.0.4664.93 (Official Build)

**Comment by antobinary** [comment]
Temporarily resolved by https://github.com/bigbluebutton/bigbluebutton/pull/13885
We need to confirm it's not re-introduced by https://github.com/bigbluebutton/bigbluebutton/pull/13893
