### ISSUE TITLE
Recordings doesn't keep aspect ratio for screen share

### ISSUE THREAD

**Issue by mokazemi** [bigbluebutton/bigbluebutton#13879]
**Describe the bug**
When the shared screen aspect ratio changes at the middle of sharing (like sharing a window), the the output video is stretched and its aspect ratio is not kept. 

**To Reproduce**
1. Start recording a meeting.
2. Share a window
3. Change its size, like reducing its width.
4. Stop the recording and play it back

**Expected behavior**
It should keep the aspect ratio and record everything as it is.

**Comment by antobinary** [comment]
Hi @mokazemi 
Thanks for reporting this!
Could you please confirm the BBB version of your server?
`bbb-conf --version` or at least the client build (in the client three dot menu -> About)

**Comment by mokazemi** [comment]
BigBlueButton Server 2.4-rc-5 (2702)
I just found out this issue is duplicated #9653. 
But the fix shouldn't be that much hard I think.

**Comment by danielpetri1** [comment]
Can't reproduce this on 2.4-rc7, but maybe this is related to the `get_deskshare_video_dimension`and `scale_to_deskshare_video` methods in the recording publishing script setting the width and height to the same value?
```
deskshare_video_height = @presentation_props['deskshare_output_height'].to_f
 deskshare_video_width = @presentation_props['deskshare_output_height'].to_f # Should be height?

**Comment by mokazemi** [comment]
> 

It doesn't seem to be solved in 2.4. But I edited the reproduce steps. It happens when the ratio **changes** at the middle of recording, like **resizing** the window to reduce its width, **without stopping** sharing screen.

P.S. Here's an attachment of what happens:
![Screenshot_20211229_124855](https://user-images.githubusercontent.com/18334056/147647428-bdd79d35-8ddc-49c5-a43d-252fc03cf4bd.png)

**Comment by ali-alhaidary** [comment]
https://github.com/bigbluebutton/bigbluebutton/issues/12072

**Comment by Aryagh** [comment]
I have this problem too!

**Comment by mokazemi** [comment]
> Hey guys (@mokazemi), I think I could reproduce this issue, is this what you witnessed?
> issueDemo.mp4
> 
> The window is not resizing as it should be, in the live part for instance, and the text gets stretched as you resize the window, right? In other words, as you said, it doesn't keep the ratio.

Yes, I think That's the same issue. Resizing window during recording makes it stretched or squeezed. @GuiLeme
