### ISSUE TITLE
Stuck on Connecting to Echo test

### ISSUE THREAD

**Issue by MBM1607** [bigbluebutton/bigbluebutton#13875]
I’m getting this issue on Google Chrome when join the session. Permission for microphone is given but the “Connecting to echo test” never completes and nor does it gives any error. On Firefox, it works smoothly and on some devices on Google chrome also works fine but some can not pass from “Connecting to echo test”. 

https://github.com/bigbluebutton/bigbluebutton/issues/10284 https://github.com/bigbluebutton/bigbluebutton/issues/9406, I have tried both of these issues are not relevant to my case. I have tried the solutions offered in them without avail.

**To Reproduce**
1. Join the session
2. Allow site to user microphone
3. On some devices user would now be stuck 'Connecting to Echo test'.

**Expected behavior**
User would do the echo test after giving permission and would be let into the session

**Actual behavior**
After giving microphone permission, with a working microphone user is stuck on 'Connecting to Echo test popup'. Popup cannot be cancelled and user cannot proceed into the session.

**BBB version:**
BigBlueButton Server 2.2.0-rc-5 (1685)

**Additional context**
This issue appeared on our live server without any alteration. Reverting to a snapshot also doesn't resolve the issue.
I have tried 'bbb-conf --setip' and 'bbb-conf --clean' they do not resolve the issue.

![image](https://user-images.githubusercontent.com/47133639/145417036-edc71cd8-4764-407f-9365-e90ed9041973.png)

**Result of bbb-conf-check**

```BigBlueButton Server 2.2.0-rc-5 (1685)
                    Kernel version: 4.4.0-210-generic
                      Distribution: Ubuntu 16.04.6 LTS (64-bit)
                            Memory: 15842 MB
                         CPU cores: 8

/usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties (bbb-web)
       bigbluebutton.web.serverURL: https://meet.example.com
                defaultGuestPolicy: ASK_MODERATOR
                 svgImagesRequired: true

/etc/nginx/sites-available/bigbluebutton (nginx)
                       server name: meet.example.com
                              port: 80, [::]:80
                              port: 443 ssl
                    bbb-client dir: /var/www/bigbluebutton

/var/www/bigbluebutton/client/conf/config.xml (bbb-client)
                Port test (tunnel): rtmp://meet.example.com
                              red5: meet.example.com
              useWebrtcIfAvailable: true

/opt/freeswitch/etc/freeswitch/vars.xml (FreeSWITCH)
                       local_ip_v4:
                   external_rtp_ip: 255.255.255.255
                   external_sip_ip: 255.255.255.255

/opt/freeswitch/etc/freeswitch/sip_profiles/external.xml (FreeSWITCH)
                        ext-rtp-ip: $${external_rtp_ip}
                        ext-sip-ip: $${external_sip_ip}
                        ws-binding: :5066
                       wss-binding: :7443

/usr/local/bigbluebutton/core/scripts/bigbluebutton.yml (record and playback)
                     playback_host: meet.example.com
                 playback_protocol: https
                            ffmpeg: 4.2.2-1bbb1~ubuntu16.04

/etc/bigbluebutton/nginx/sip.nginx (sip.nginx)
                        proxy_pass:  255.255.255.255

/usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml (Kurento SFU)
                        kurento.ip: 15.207.241.37
                       kurento.url: ws://127.0.0.1:8888/kurento
                    localIpAddress:  255.255.255.255
               recordScreenSharing: true
                     recordWebcams: true
                  codec_video_main: VP8
               codec_video_content: VP8

/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml (HTML5 client)
                             build: 1
                        kurentoUrl: wss://meet.example.com/bbb-webrtc-sfu
                  enableListenOnly: true
```

**Comment by prlanzarin** [comment]
>  BigBlueButton Server 2.2.0-rc-5 (1685)

[Update to v2.2.36 or v2.3 or v2.4.](https://github.com/bigbluebutton/bigbluebutton/issues/13843#issuecomment-987856477)

**Comment by MBM1607** [comment]
Thanks @prlanzarin  for the quick reply. Somehow that github issue eluded me when I searching for this issue.

**Comment by jetchevers** [comment]
Hello, I have the same problem.
The bbb servers were working fine until today.
I had no updates or modifications on them.
I have set stunServerAddress = 172.217.212.127 and I tried other stunServers from google but I still have the same problem.

**Comment by hostbbb** [comment]
@jetchevers read above, you need to updated to 2.2.36 or 2.3 2.4
its a chrome browser issue.

**Comment by samuelpetrosyan** [comment]
> @jetchevers read above, you need to updated to 2.2.36 or 2.3 2.4 its a chrome browser issue.

Hi, I have updated to 2.3 stable latest version but the issue still persists.... What can we do with that? Please help us. Thanks in advance...

**Comment by manoj-kumar00** [comment]
Hi All,

I am facing same issue, mic not working on BBB meetings , its get stuck on echo test, tried updated version also.
In vanila setup its working fine but after serving via build getting errors, tried latest patch on our sip.js but still mic having issue.

**Comment by manoj-kumar00** [comment]
Hi All, this is a follow up for my query over mic issue( stuck on echo test ), please share your suggestion and solutions for the same

**Comment by hostbbb** [comment]
this is a config issue and best handled in the bigbluebutton-setup google forum, where you can post your question and config to get help.
