### ISSUE TITLE
2.4 - RC7 - Bug - Joining breakout rooms creates popup windows

### ISSUE THREAD

**Issue by spreeni151** [bigbluebutton/bigbluebutton#13889]
If a breakout room link is called up manually by moderators, a popup window is generated that is blocked by the browser. In this case Firefox does not open a tab to the breakout room. If popups are allowed, several tabs are opened after clicking the breakout room links.

look at the attached video
https://user-images.githubusercontent.com/57463889/145572094-a6334774-a51e-4f83-91a3-cc259761a559.mp4

The behavior shown occurs with the current Firefox, Chrome behaves similarly, but only creates two tabs when pop-ups are allowed. In the standard setting (block pop-up windows), however, Chrome behaves normally.

The behavior occurs under Windows and MacOs.

I set up a new server for testing and a clean BBB installation via bbb-install.sh -v bionic-240.

tested version: BBB 2.40-rc-7
Firefox 95.0
Chrome 96.0.4664.93 

https://user-images.githubusercontent.com/57463889/145572094-a6334774-a51e-4f83-91a3-cc259761a559.mp4

**Comment by spreeni151** [comment]
Just an additional information: A friend of mine could reproduce this behavior with Firefox 95.0 on MacOS. He opened a session at https://test24.bigbluebutton.org and did the same steps I showed in the video above.
If anyone wants to reproduce it with my server (fresh Ubuntu 18.4, fresh 2.4-rc7 installation), heres a link:
https://beta.medienwerkstatt-cloud.de/index.php/apps/bbb/b/RfxjJCMYd74DnsmP
I appreciate any feedback that could explain the problem.
Frank

**Comment by ffdixon** [comment]
Thanks Frank -- I was able to reproduce it on my end.  

I ended up with 4 Fred's in the breakout room after the tabs stopped opening.

![image](https://user-images.githubusercontent.com/290351/145686979-76cf6e4e-a896-4d26-ab26-19d67ef7f304.png)

Thanks for reporting this -- we'll take a closer look.

**Comment by spreeni151** [comment]
Thanks for your response, Fred. Good to know that this will be investigated further :-) .
