### ISSUE TITLE
After update BigBlueButton Server 2.4-rc-7 (2773) meeting cannot start

### ISSUE THREAD

**Issue by blueiceprj** [bigbluebutton/bigbluebutton#13888]
**Describe the bug**
Join meeting getting this error.

<img width="1680" alt="Ekran Resmi 2021-12-10 10 12 01" src="https://user-images.githubusercontent.com/1829975/145548801-cec95244-1ffc-4932-aef1-855520bfd4fd.png">

**To Reproduce**

**Expected behavior**

**Actual behavior**

**Screenshots**

**BBB version:**
BigBlueButton continually evolves. Providing the version/build helps us to pinpoint when an issue was introduced.
Example:

$ sudo bbb-conf --check | grep BigBlueButton
BigBlueButton Server 2.4-rc-7 (2773)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, Mac]
 - Browser [e.g. Chrome, Safari]

**Smartphone (please complete the following information):**
 - Browser [e.g. stock browser, Safari]

**Additional context**

**Comment by hostbbb** [comment]
Looks like this is loading the client with the new proxy feature was just commited?  is this a standard install, or did you try to configure the client to work thru proxy?

**Comment by antobinary** [comment]
Hi @blueiceprj 
Also is this a development environment (running bbb-html5 as `npm start`) or a regular production environment? Editing the description to fill out the template would be really appreciated!

**Comment by blueiceprj** [comment]
Hi,

After that I run "sudo bbb-conf --setip "  than work again. 

Thanks for your reply.
