### ISSUE TITLE
log4j security vulnerability

### ISSUE THREAD

**Issue by abedinpour** [bigbluebutton/bigbluebutton#13897]
Is BigBlueButton or any of its dependencies vulnerable to the recently discovered log4j vulnerability?
https://thehackernews.com/2021/12/extremely-critical-log4j-vulnerability.html?m=1
If yes, Are there any patches that we can apply?
Thanks.

**Comment by hiroshisuga** [comment]
Some discussion here:
https://groups.google.com/g/bigbluebutton-dev/c/hXrvzYPk7JU

**Comment by GhaziTriki** [comment]
Thank you @hiroshisuga.
@abedinpour I have done the necessary investigation, BigBlueButton is not concerned, so no need for any patch.

**Comment by ffdixon** [comment]
Thanks @GhaziTriki.
