### ISSUE TITLE
bbb-conf --setip overwrites bbb-web.properties

### ISSUE THREAD

**Issue by easy-bios** [bigbluebutton/bigbluebutton#13892]
**Describe the bug**
If you have Custom Configs in _/etc/bigbluebutton/bbb-web.properties_
these will be overwritten by _bbb-conf --setip bbb.example.com_

**Installation type**
bbb-install script
version: 2.4-rc-7

To avoid this, updates by _--setip_ should modify existing _bigbluebutton.web.serverURL_ entries.

**Comment by antobinary** [comment]
Hi @easy-bios 

Thanks for reporting this!

Could you please specify which properties you were overwriting in `/etc/bigbluebutton/bbb-web.properties` so I can try to reproduce it here? Is your file completely rewritten to stock `/etc/bigbluebutton/bbb-web.properties` - just url and salt?

(I have not had this happen on my env and I do --setip after each update, so this extra info can help reproduce this locally)

**Comment by easy-bios** [comment]
Probably found the problem:
My `/etc/bigbluebutton/bbb-web.properties` **only** contined the following written there by a script:
`appLogLevel=DEBUG`
`maxFileSizeUpload=30000000`
`defaultDialAccessNumber=xxxxxxxxxxxxxxxxx`
`learningDashboardEnabled=false`
`allowRequestsWithoutSession=true`
Doing `--setip` and `--setsecret` afterwards caused all settings to disapear and only url left.

This probably also is the explaination for #13891 

As described here [Local overrides for configuration settings](https://docs.bigbluebutton.org/admin/configuration-files.html#local-overrides-for-configuration-settings) I assumed I can write configs to `/etc/bigbluebutton/bbb-web.properties` lika with `/etc/bigbluebutton/bbb-html5.yml` or `/etc/bigbluebutton/turn-stun-servers.xml`.

**Comment by antobinary** [comment]
bbb-web.properties is a bit special - it needs at a minimum the url and salt (it also comes by default and already includes these two)
You may want to _append_ to it...

Is there a particular [docs] rewording that would have made it easier for you?

**Comment by ffdixon** [comment]
Thanks for the report of this --  we will enhance`bbb-conf` so it does not cause existing parameters in `/etc/bigbluebutton/bbb-web.properties` to disappear, but rather update/append the hostname and shared secret.

**Comment by antobinary** [comment]
@ffdixon could we please also `echo` that we're doing this (behind the scenes) as we do it otherwise it might trip people who don't expect their /etc/bigbluebutton/ file to be touched by the system

**Comment by easy-bios** [comment]
IMO it could be better to write _url_ and _secret_ to another file.
Nearly all the rest is mostly global for all servers if you have a cluster of bbb servers. But _url_ and _secret_ should be unique for all servers.

**Comment by easy-bios** [comment]
> Is there a particular [docs] rewording that would have made it easier for you?

I think it should be mentioned in the Notes. 
Maybe something like. "Minimum containing general configuration. (url, secret)"

Here: [Local overrides for configuration settings](https://docs.bigbluebutton.org/admin/configuration-files.html#local-overrides-for-configuration-settings)
![image](https://user-images.githubusercontent.com/42430994/145956163-6531dc4b-5151-49ec-99b3-a6fa500b3cd0.png)

**Comment by antobinary** [comment]
I made the suggested change but forgot to comment here... 

![Screenshot from 2022-01-10 15-12-33](https://user-images.githubusercontent.com/6312397/148833237-0b3f49cf-7d3a-4418-8b7c-0acf28d9ce27.png)

**Comment by easy-bios** [comment]
Thanks, the wording could bei misleading. Automatically set sounds like you don't habe to do it yourself. Maybe "At least requires sequritySalt and serverURL" would be better?

**Comment by antobinary** [comment]
Let's stick with your initial suggestion :) https://github.com/bigbluebutton/bigbluebutton.github.io/commit/a49bad7326e71002d6e11675acd99af58521bfcc  Thanks again for commenting back

**Comment by antobinary** [comment]
Tested #14798 with your configs from https://github.com/bigbluebutton/bigbluebutton/issues/13892#issuecomment-991162213
