### ISSUE TITLE
bbb-conf --setsecret does not change the secret

### ISSUE THREAD

**Issue by easy-bios** [bigbluebutton/bigbluebutton#13891]
**BigBlueButton 2.4-rc-7**

![image](https://user-images.githubusercontent.com/42430994/145583812-29e5e008-ecea-4869-855a-586f280bd297.png)

**Describe the bug**
As you can see the Secret set with --setsecret has not been changed.

**Installation type**
bbb-install script

**Comment by antobinary** [comment]
Thanks for reporting this @easy-bios !

In the file /etc/bigbluebutton/bbb-web.properties which version of the salt do you have?
