### ISSUE TITLE
Camera can't be started after upgrade from 2.3.15 to 2.3.16 - error 1020

### ISSUE THREAD

**Issue by sp46887** [bigbluebutton/bigbluebutton#13899]
**Describe the bug**
Camera can't be started after upgrade from 2.3.15 to 2.3.16 with error 1020
The error is reproducible and occurs with several updated servers, while it does not occur with servers with 2.3.15 with the same equipment. The servers are not behind NAT, the coturn works perfectly
Tested under Windows 10, Chrome and Firefox Browsers - latest versions

**To Reproduce**
1. Start a conference
2. Webcam enable
3. See error1020

**Expected behavior**
The Webcam should be seen

**Actual behavior**
Error 1020

**BBB version:**
BigBlueButton continually evolves. Providing the version/build helps us to pinpoint when an issue was introduced.
Example:
$ sudo bbb-conf --check | grep BigBlueButton
BigBlueButton Server 2.3.16 (2515)

**Desktop (please complete the following information):**
 - Windows 10
 -Chrome, Firefox
 - latest

**Smartphone (please complete the following information):**
 - Device: iPhone 12
 - OS: 15.1.1
 - Browser Safari
 - Version see OS

**Additional context**
compared output from bbb-conf --check seems to be equal between 3.15 and 3.16

**Comment by hostbbb** [comment]
if you look at the Kurento /var/log/kurento-media-server/ and /var/log/bbb-webrtc-sfu/ could provide some hints.

also,  /etc/kurento/modules/kurento/WebRtcEndpoint.conf.ini make sure this has correct IPS.  Are you running bbb-install.sh on each server to upgrade, or deploying some other way.   Also,   google bigluebutton-setup group may get you more support if you post there.

**Comment by ffdixon** [comment]
Recommend posting to bigbluebutton-setup as well -- and include how you upgraded your servers (did you do apt-get update or use bbb-install.sh)?

**Comment by ffdixon** [comment]
Also, I just tried a new install of 2.3.16 and an upgrade install from 2.3.15 to 2.3.16 and the camera worked in both cases.

**Comment by sp46887** [comment]
ok, I did the upgrade with apt-get update and apt-get upgrade

A complete new installation is working well, but this much more work for our servers

/var/log/bbb-webrtc-sfu/bbb-webrtc-sfu.log contains many entries with errors like that:
{"error":{"errno":"EPIPE","code":"EPIPE","syscall":"write"},"level":"error","message":"[mcs-freeswitch-esl-wrapper] FreeSWITCH ESL connection received error EPIPE","timestamp":"2021-12-11T19:03:05.355Z"}
{

and one error:
{"level":"error","message":"[mcs-freeswitch-esl-wrapper] FreeSWITCH ESL connection authentication error","timestamp":"2021-12-11T19:03:05.355Z"}
{

Any idea?

If not, I'll make some greenlight database backups and install the servers from scratch

**Comment by ffdixon** [comment]
> ok, I did the upgrade with apt-get update and apt-get upgrade

Use the [bbb-install.sh](https://github.com/bigbluebutton/bbb-install) to upgrade your server.

**Comment by sp46887** [comment]
done, it works fine.
Thank you. I close the issue
