### ISSUE TITLE
Sort participants list in Connection status window

### ISSUE THREAD

**Issue by Jossef-767** [bigbluebutton/bigbluebutton#13908]
**Is your feature request related to a problem? Please describe.**
The list is currently unsorted and makes it difficult to find and understand the status of participants' and server's network connections

**Describe the solution you'd like**
Sort the list of participants by time

**Comment by pedrobmarin** [comment]
Here's how it's currently sorted https://github.com/bigbluebutton/bigbluebutton/blob/6e920ad785f1cf7c7010f21c76866ac4cebf88e3/bigbluebutton-html5/imports/ui/components/connection-status/service.js#L240

Worse connectivity problems first and offline users to the bottom.

**Comment by Jossef-767** [comment]
was not aware of it, Thank's for the clarification. 
 My point is, "Worse connectivity problems first" means that even a user who encountered a serious problem an hour ago can appear first, and this is no longer relevant information as a tool for real-time support. In my experience, it is more helpful for technical support personnel to find the information about the situation in the recent past first.

**Comment by pedrobmarin** [comment]
Definitely is something to bring up for broad discussion.

While thinking the first version of this list, we imagined a scenario where the moderator would be interested mainly on users with the most damaging connectivity issues since mild connectivity problems often go by unnoticed.

**Comment by Jossef-767** [comment]
This is indeed true for moderators,
It may be helpful to have additional rule that will sort by time, so that the moderators will see "Worse connectivity" first, sorted by time.
