### ISSUE TITLE
Participants in a meeting can anonymously vote to end it and the meeting automatically ends if a majority of attendees want it to

### ISSUE THREAD

**Issue by mlncn** [bigbluebutton/bigbluebutton#13902]
**Is your feature request related to a problem? Please describe.**

People can end up spending long amounts of time in meetings that they do not feel bring value because no one takes the initiative to end the meeting.  In many contexts with explicit or implicit hierarchies, being the initiator or supporter of ending a meeting (as with many other things) 

Perhaps only the boldest teachers will enable this in educational contexts but in business and organizing this could be a unique, buzzworthy, and perhaps valuable BBB feature.

**Describe alternatives you've considered**

A poll ('should we end this meeting?') requires someone to initiate it and interrupts the flow of the meeting.  It also requires a person with permissions to honor the results.  This feature would let people asynchronously put in their preference, with the ability to revoke it— next to the logout ("leave meeting") option and the end meeting (for those with permissions) would be a "Vote to end meeting (anonymous)" option.

**Additional context**

Idea from this very popular tweet:

https://twitter.com/joeylorich/status/1468976175821250565

Clearly of more use in corporate settings that lack other mechanisms for honest feedback, but an opportunity for innovation that corporate, proprietary meeting apps are unlikely to provide.

Preserving chat and meeting notes after end of meeting would probably be a useful, crucial combination with this.

A message: "A majority of current attendees would like to end this meeting.  It will end in one minute." is probably a more reasonable approach than an *immediate* end.

**Comment by hostbbb** [comment]
you could do this most of this today right with no software changes?  the meeting leader just creates and anonymous poll with "should we end this meeting?", get the results, and then decides to either contunue/end the meeting
