### ISSUE TITLE
Hidden webcams of participants are shown in recordings (privacy issue)

### ISSUE THREAD

**Issue by dranjor** [bigbluebutton/bigbluebutton#13901]
**Describe the bug**
If participants webcams are not visible to other participants, they should not be shown in the recording.

**To Reproduce**

1. Start a meeting with moderators and participants
2. Set "See other viewers webcams" to "Locked"
3. Start a recording
4. Play the recorded meeting

**Expected behavior**
Only the moderators webcam should be shown.  

**Actual behavior**
All webcams (moderators and participants) are shown

**Desktop (please complete the following information):**
 - OS: Linux - Browser: firefox
 - Version: 2.4-rc-7

**Comment by hiroshisuga** [comment]
The recording function of BBB records what was happening in the moderator's screen, not only the webcams, but also the whiteboard drawings. I think the current behaviour is consistent.

**Comment by dranjor** [comment]
Since recordings can be shared publicly, I think it would be better to present the viewer's perspective.

**Comment by hostbbb** [comment]
You can pass a param on user join to make a user's camera not appear in the recording if your writing custom front end...  the api section of docs.bigbluebutton.org should detail

**Comment by hiroshisuga** [comment]
Rewriting the code to replay the viewer's screen is possible. The problem is which viewer's screen we should record.  This is particularly problematic for the multi-user whiteboard with only specific users allowed to draw.

My use case is surveillance of exam, in which I do not publish the recording and I would prefer the recording of presenter's screen to look it back later.

**Comment by dranjor** [comment]
My use case is about recording lectures to make them available later to students who could not attend.

For this reason, I would like to have a recording that reflects the student perspective. 

In previous BBB versions recordings were rendered in three different variants (podcast, presentition, screenshare). Maybe one could create a "moderator view edition" and "viewer view edition" of the recording?
