### ISSUE TITLE
Error 1006: Call timed out after upgrading to 2.4-rc-7

### ISSUE THREAD

**Issue by mokazemi** [bigbluebutton/bigbluebutton#13903]
**Describe the bug**
I installed recent BBB upgrades to 2.4-rc-7 by running `sudo apt upgrade`. Before than, We've been using 2.4-rc-5 on the server and it was working fine. 
But now people can't join the meeting with microphone and gets "**1006: Call timed out**" error after a while trying to connect. 
Everyone can only enter as a listener, even after a lot of attempts. 

**Additional context**
Version: **BigBlueButton Server 2.4-rc-7 (2776)**

Here's in the output of `sudo bbb-conf --check`:

```
# Potential problems described below
..............
# Warning: You have this server defined for https, but in
#
#   /etc/bigbluebutton/nginx/sip.nginx
#
#  did not find the use of https in definition for proxy_pass
#
#            proxy_pass http://130.185.75.197:5066;
#

# Warning: You have this server defined for https, but in
#
#   /etc/bigbluebutton/nginx/sip.nginx
#
#  did not find the use of port 7443 in definition for proxy_pass
#
#            proxy_pass http://130.185.75.197:5066;
#
```

**Comment by Jossef-767** [comment]
set  settings.yml  >   **sipjsHackViaWs: true**  and restart

**Comment by PhMemmel** [comment]
And please use the bbb-install script to update your server. apt-get only deploys the standard config file templates and overwrites some of the existing configuration. bbb-install will fix that afterwards and adapt the newly installed config files to your needs.

**Comment by mashpie** [comment]
and where tf do we find that ?

root@bbb-upfuckedserver ➜  ~ bbb
bbb-apps-akka   bbb-conf        bbb-fsesl-akka  bbb-record

**Comment by ihtesham786** [comment]
> and where tf do we find that ?
> 
> root@bbb-upfuckedserver ➜ ~ bbb bbb-apps-akka bbb-conf bbb-fsesl-akka bbb-record

Here you go : nano /usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml

**Comment by mokazemi** [comment]
Thanks. Both solutions worked.
