### ISSUE TITLE
Log4j vulnerable - is BBB vulnerable? 

### ISSUE THREAD

**Issue by adulau** [bigbluebutton/bigbluebutton#13904]
[Log4j vulnerability](https://www.circl.lu/pub/tr-65/) - is BBB vulnerable? 

and if you could update [this list](https://github.com/NCSC-NL/log4shell/tree/main/software), it would be great for all the BBB users.

**Comment by GhaziTriki** [comment]
Duplicate of https://github.com/bigbluebutton/bigbluebutton/issues/13897
