### ISSUE TITLE
Chat Notifications (Audio/PopUp) - Not working most of the time

### ISSUE THREAD

**Issue by Subdarub** [bigbluebutton/bigbluebutton#13917]
**Describe the bug**
Enabling audio and popup notifications for chat, wont do anything most of the time.

**To Reproduce**
1. Enable Notifcations
2. Type something in chat with a second account/Get someone else to write a chat msg.

**Expected behavior**
Be notified with audio and visual cues. 

**Actual behavior**
Fail to get notfied with audio and visual cues most of the time.

**BBB version:**
Version: 2.3.15 and 2.4 RC7

Tried both on my own infrastructure and demo.bigbluebutton.org

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 96.0.4664.110 

**Additional context**
On version 2.3.15 i tried enabling Audio and PopUp notifcations as a default, same behavior.

**Comment by antobinary** [comment]
Thanks for reporting this!

**Comment by KDSBrowne** [comment]
After doing some investigation it appears that the Chat notifications (audio/popup) function as intended. The notifications are only applied to unread messages. So the sound and popup are only invoked if the chat panel is closed at time of the incoming message.

**Comment by Subdarub** [comment]
Thank you for looking into this. In my opinion the user would expect a notifcation under any circumstance. As this feature is generally disabled per default it wont interfere with the general use of BBB.

For example if you are using only one monitor and BBB is in the background, you wont get notified, because theoretically the chat window is actually open even tho from a user perspective it is not.

**Comment by antobinary** [comment]
Does this fall under what's requested in https://github.com/bigbluebutton/bigbluebutton/issues/11042 ?

**Comment by KDSBrowne** [comment]
@antobinary Yeah it does

**Comment by antobinary** [comment]
Let's merge this into #11042 so we can track progress/comments in one place. The milestone and assignment remain the same - 2.4 and @KDSBrowne
