### ISSUE TITLE
Implement a pending state for users who are reconnecting to the meeting

### ISSUE THREAD

**Issue by Tainan404** [bigbluebutton/bigbluebutton#13912]
**Is your feature request related to a problem?**
Currently when a user leaves the meeting isn't instantly removed, but flagged with a `userLeftFlag` [flag](https://github.com/bigbluebutton/bigbluebutton/blob/v2.4.x-release/akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/UserLeaveReqMsgHdlr.scala#L22), because it could be an accedentaly refresing or closing tab, so, after a few seconds ([default = 10s](https://github.com/bigbluebutton/bigbluebutton/blob/v2.4.x-release/akka-bbb-apps/src/main/scala/org/bigbluebutton/core/models/Users2x.scala#L53)) if theres no reconnection attempt the user is completely removed, the issue is that akka knows about this flag but it is not notified to the client, so other users don't know who is reconnecting to the meeting or who is actually online

**Describe the solution you'd like**
Create a flag to notify the Meteor about the pending users and set a diffente color to text or backgroud in the user with pending state on userlist

**Comment by TiagoJacobs** [comment]
I propose that we hide users in situation of reconnecting from UserList / userCount
