### ISSUE TITLE
BBB Fails to verify STUN servers: Chrome users cannot join audio

### ISSUE THREAD

**Issue by samuelpetrosyan** [bigbluebutton/bigbluebutton#13911]
**Describe the bug**
BBB Fails to verify STUN servers... In result of it some of clients (Chrome) cannot join audio.

**To Reproduce**
1. Install BBB 2.4-rc-7
2. Wait until installation completion
3. See error No. 1
4. Then also you can create Meeting room and try to join it via Chrome
5. See error No. 2

**Expected behavior**
Successful STUN server verification and successful audio join on Chrome client.

**Actual behavior**
Not the expected :(

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 96.0.4664.93 (Official Build) (64-bit)

**Additional context**

```
# Warning: Failed to verify STUN server at stun.l.google.com 19302 with command
#
#    stunclient --mode full --localport 30000 stun.l.google.com 19302
#
# Warning: Failed to verify STUN server at 172.217.212.127:19302 with command
#
#    stunclient --mode full --localport 30000 172.217.212.127 19302
```

**Comment by MBM1607** [comment]
What is the behaviour of html5 client? Is it stuck on echo test?

**Comment by samuelpetrosyan** [comment]
> What is the behaviour of html5 client? Is it stuck on echo test?

Ya it's stucking on echo test on Chrome clients, but on Edge, Firefox successfully pass echo test.

**Comment by d3hof** [comment]
The current chrome build on on windows and macOS abbandoned plan b sdp. Maybe that's causing the issue.  But i don't know if it's an issue with the stun/turn server or something else. Apperently there is a way to turn it on.

**Comment by samuelpetrosyan** [comment]
> The current chrome build on on windows and macOS abbandoned plan b sdp. Maybe that's causing the issue. But i don't know if it's an issue with the stun/turn server or something else. Apperently there is a way to turn it on.

And is there any solution for chromes?

**Comment by prlanzarin** [comment]
> > The current chrome build on on windows and macOS abbandoned plan b sdp. Maybe that's causing the issue. But i don't know if it's an issue with the stun/turn server or something else. Apperently there is a way to turn it on.
> 
> And is there any solution for chromes?


https://github.com/bigbluebutton/bigbluebutton/issues/13843#issuecomment-987856477

[A search in the issue tracker is all that is needed](https://github.com/bigbluebutton/bigbluebutton/issues?q=is%3Aissue++plan-b+). The solution is in the second entry of that search. Please, use the search function.
