### ISSUE TITLE
Shorter cursor update interval for annotators

### ISSUE THREAD

**Issue by hiroshisuga** [bigbluebutton/bigbluebutton#13921]
**Is your feature request related to a problem? Please describe.**
Compared to other online meeting software, BBB still has some problems in the whiteboard functions. As a teacher, I am not satisfied with the cursor reactivity, which has a small but un-ignorable delay and gives me some frustration. #13854 has solved quite a bit of the problems but it is still not like a real laser pointer.

**Describe the solution you'd like**
Currently the cursor update interval is set 150 ms as a default value not only for the viewers but also for the annotators. We can separate this value for annotators, setting it, say, 50 ms, as long as it does not change the network load very much.
It should be possible because the drawer can update the cursor only locally by the use of the function of MongoDB.
In fact, the BBB's annotation function uses this strategy.  For the annotations, reactivities of the tools are very good (actually too much), with virtually no delay. Only the cursor reacts equally to annotators and viewers.

**Additional context**
A potential problem is the inconsistency between teacher and students. But in my experience, students do not care so much about the cursor that does not perfectly reflect what the teacher is explaining. So we can focus on the teacher's frustration here.
I am aware that this does not change anything on the viewer's side, but making teachers comfortable is also important for a better online learning.

**Comment by ffdixon** [comment]
Thanks again @hiroshisuga for your contributions.  By moving to a new whiteboard based on tldraw, we have addressed many of the whiteboard-related issues in the old whiteboard.
