### ISSUE TITLE
Webcams overlap speakerlist in Breakout Rooms

### ISSUE THREAD

**Issue by EdJoPaTo** [bigbluebutton/bigbluebutton#13933]
**Describe the bug**
When only the webcams are shown (presentation minimized in custom layout or layout focussing on webcams) the webcams overlap the speaker list in breakout rooms. I suspect that the breakout room remaining time indicator moves the speaker list down but not the webcams.

**To Reproduce**
1. Create Breakout Rooms
2. Join with at least one webcam
3. Minimize the presentation in "Custom" layout / use "Focus on video" layout. Smart Layout or having the presentation open in "Custom" don't seem affected.
4. Make sure the browser size / webcams are positioned in a way that a webcam is positioned at the top of the window rather than to the side
5. Speak with multiple people or long enough names

**Expected behavior**

The speaker list is between the webcams and the breakout room name in its own area of space like outside of a breakout room.

**Actual behavior**

Webcams overlap the speaker list and reach into its area

**Screenshots**
![Screenshot from 2021-12-15 22-29-37](https://user-images.githubusercontent.com/7953011/146267989-cf56b33c-0d8d-460b-9fbc-435445289ca6.png)

**BBB version:**
BigBlueButton Server 2.4-rc-7 (2785)

**Desktop:**
 - Arch Linux, Firefox, 95.0
 - Chromium Version 96.0.4664.110 (Official Build) Arch Linux (64-bit)
 - iPadOS 15.1, Safari

**Additional context**

#13805 seems like a similar issue.

**Comment by antobinary** [comment]
Thanks for reporting!
