### ISSUE TITLE
[2.4-rc7] Screenshare not showing up for people who join after screensharing started

### ISSUE THREAD

**Issue by cxmrk** [bigbluebutton/bigbluebutton#13948]
**Describe the bug**
We got a meeting with a single moderator, joining in advance for preparation, which starts sharing his screen once he joined.
If participants join afterwards, shared screen isn't visible for them until screensharing is cancelled and restarted. Modal that screensharing started does appear on the participants client though.

**To Reproduce**
- Start a session with BBB 2.4 RC7
- Join as Moderator
- Share a window
- Let another participant join

**Expected behavior**
Auto-Start and display shared screen.

**Actual behavior**
Modal is popping up on joining, shared screen isn't visible though. Once the moderator has cancelled and restarted sharing his screen it's visible for everyone.

BBB version:
BigBlueButton Server 2.4-rc-7

Browser version
Firefox 96.0b7
Chrome Version 99.0.4776.0

**Comment by ffdixon** [comment]
To rule out local network/computers, can you do a quick test with https://demo.bigbluebutton.org/ and let us know if you can reproduce it there.

**Comment by cxmrk** [comment]
Behaviour seems to be the same there.

**Comment by prlanzarin** [comment]
1 - What do you mean by "modal"? Send a screenshot. There's no "modal" that's shown when a screen is shared.
2 - Are you able to test this with _stable_ versions of the aforementioned browsers? (FF96 is nightly, Chrome 99 is... canary?)
3 - Does that same thing happen while sharing the whole _screen_ rather than a window?
4 - Which browser is the _sharer_ using?

**Comment by prlanzarin** [comment]
@cxmrk Can you please give more details on why this issue was closed?

**Comment by erpsolns** [comment]
In 2.5 and 2.6  also same problem persists
Moderator when 1) share screen  and
2) share an external video. 
A. These screenshare and shared external video  are not visible to those who join after the screen share/share external video started.
B. But audio is heard for both shared external video as well as shared screen
