### ISSUE TITLE
Port definition not clear and different ports used

### ISSUE THREAD

**Issue by Dennis1993** [bigbluebutton/bigbluebutton#13943]
In the install documentation the following information is given:
![image](https://user-images.githubusercontent.com/1473674/146534767-e68a545e-bfbf-4815-b8f1-6fc27c55d60e.png)

Port 80, 443 and 16384-32768

We use BBB behind a firewall and we don't know in which way we can grant the permission to the BBB server. Is that an **in or/and outgoing** forwarding?

We open the ports only ingoing. The BBB works. In our firewall we see other ports as documented (outgoing) which are blocked. What is right and why the ports are above 50000? Is that needed and we should allow that ports outgoing?
The documentation says other.
![image](https://user-images.githubusercontent.com/1473674/146535203-b68e842f-a3a8-4fff-a841-bee19d544cb6.png)

Thanks

**Comment by JeanPluzo** [comment]
I'm no specialist, but AFAIK ports 16384-32768 are for media communication (audio, video). For example, these ports have to be also opened in the TURN-Server, both in and out. Again, no specialist here so correct me if I'm wrong.

**Comment by Dennis1993** [comment]
Thanks for your answer! 👍

I can open these for in and out, no problem. But what are the other ports in my screenshot above 32768?
I can configure the firewall to allow all outgoing ports if needed. ☺️
Maybe we should adjust the documentation for right installation ☺️🙏

**Comment by JeanPluzo** [comment]
A bit more insight is here: 
https://docs.bigbluebutton.org/2.3/architecture.html#internal-network-connections
