### ISSUE TITLE
Enable h.264 video

### ISSUE THREAD

**Issue by bigbluebutton-issue-import** [bigbluebutton/bigbluebutton#1395]
Originally reported on Google Code with ID 640

```
Is there any plan to support high definition video? Thanks.

```

Reported by `jssoble` on 2010-10-11 09:41:58

**Comment by ffdixon** [comment]
Closing this issue.  On recent versions of Flash they support encoding of h264, which is used by BigBlueButton to share webcams

http://www.adobe.com/devnet/adobe-media-server/articles/encoding-live-video-h264.html

If a recording is done, the h264 encoded FLV files are converted into a VP8 .webm file for playback in the browser.
