### ISSUE TITLE
Moderator muting all users from managers user icon

### ISSUE THREAD

**Issue by sakky27** [bigbluebutton/bigbluebutton#13952]
**Describe the bug**

The users can unmute themselves even when they have been unmuted by the moderator and the new user is able to see the options to join as microphone while joining the meeting.

# To Reproduce
1. Select manage users icon (cog wheel in users list).
2. Choose mute all users.

# Expected behavior

All users (moderator/presenter included) who are already joined in the client with a functioning mic will be muted (if unmuted) and unable to unmute their mics. All users (moderator/presenter included) who join after setting is applied will be automatically joined listen only with no mic options available.
 
# Actual behavior
Users should not be able to unmute themselves once muted by the moderator and new user when joins the meeting after the settings are applied as muting all users should not see the microphone option.

# Screenshots
1.	The moderator is muting all the users and able to mute all of them.
 
![image](https://user-images.githubusercontent.com/43130870/146802443-7dd9b0b0-dac3-43fa-b40f-9984af38a7ec.png)

 2.  All the users are muted as moderator has selected mute all users.

 ![image](https://user-images.githubusercontent.com/43130870/146802692-76e33939-9d9c-4491-98f6-4e188803e00e.png)

 3.  User2 tries to click on unmute option and can unmute even though the settings have been applied. (Issue)
 
![image](https://user-images.githubusercontent.com/43130870/146802733-40eebea5-5abf-430c-9151-132bf04f56f7.png)

 4.  The new user(User 10 here) can see the microphone while joining the meeting even when the settings have been applied, though the user joins as muted but should not see the options joining with microphone.
 
![image](https://user-images.githubusercontent.com/43130870/146802765-eaed9588-3bb5-46e5-942f-8fa8ba02a777.png)

 5. New user (User 10 here) is also able to unmute during the meeting.
![image](https://user-images.githubusercontent.com/43130870/146802636-c1f80527-4e15-4922-b5c9-5d3676237ba7.png)

# BBB version:

BigBlueButton Server 2.4

# Desktop (please complete the following information)
 - OS: [e.g. Windows
 - Browser [e.g. Chrome, Edge]
 - Version [e.g. 24]

**Comment by pedrobmarin** [comment]
I believe the confusion here is taking the mute all meeting policy as a lock feature. The mute all policy should not prevent users to unmute themself

**Comment by antobinary** [comment]
Yes, @pedrobmarin , we just went over that with @sakky27 We're going over some [old] docs of step by step manual test to ensure 2.4.0 is in good standing and that the docs are recent enough to be included in the docs section later on. Well, in this case our old test description was a bit vague. We're updating it
