### ISSUE TITLE
See other users in user list 

### ISSUE THREAD

**Issue by sakky27** [bigbluebutton/bigbluebutton#13958]
# Describe the bug
Moderator does not see the option to unlock user, when see other viewers in Users list lock is enabled.

# To Reproduce
1) click on the mange user list cog
2) block see other viewers in user list.
3) go back to users list
4) click on a user.

# Expected behavior
Once see other viewers in Users list locked is enabled, moderato should have an option for unlocking user.

# Actual behavior
Moderator is not able to see the option to unlock the user.

# Screenshots

1.	Moderator has enabled the see other viewers in Users list locked.

![image](https://user-images.githubusercontent.com/43130870/146839699-a15020f3-2b26-4f8b-8a40-10e57b01a229.png)

2.     Moderator does not have the option to unlock the user in this case.

![image](https://user-images.githubusercontent.com/43130870/146839725-b1aff57a-63ff-4913-b0e9-d09ca3d2547b.png)

# BBB version:
BigBlueButton Server 2.4

# Desktop (please complete the following information):
 - OS: [e.g. Windows
 - Browser [e.g. Chrome, Edge]
 - Version [e.g. 24]

# Additional context
The test case plan is failing.

**Comment by ffdixon** [comment]
Just tried this in BigBlueButton 2.3 and the behaviour is the same (no option to unlock a viewer).  

At the moment, the lock option for "See other viewer's webcams" operates a bit differently from the others.  For some hosting environments, this option is used to reduce the overall number of webcam streams by (a) restricting students to only seeing the teacher (enabling this lock setting by default), and (b) hide the option for moderator to unlock the student (moderator is unable to unlock this for students).  

This is also why you don't see the word 'locked' when only applying this lock setting -- it makes BigBlueButton look and act normally, but it's actually restricting the number of webcam streams to avoid the too many webcam streams running on the server.

**Comment by prlanzarin** [comment]
> Just tried this in BigBlueButton 2.3 and the behaviour is the same (no option to unlock a viewer).
> 
> At the moment, the lock option for "See other viewer's webcams" operates a bit differently from the others. For some hosting environments, this option is used to reduce the overall number of webcam streams by (a) restricting students to only seeing the teacher (enabling this lock setting by default), and (b) hide the option for moderator to unlock the student (moderator is unable to unlock this for students).
> 
> This is also why you don't see the word 'locked' when only applying this lock setting -- it makes BigBlueButton look and act normally, but it's actually restricting the number of webcam streams to avoid the too many webcam streams running on the server.

The issue refers to _**See other viewers in the user lis**t_, not _See other viewers webcams_. The latter behaves normally as a lock setting would (individual locks in the user list, server-side constraints, ...).

**Comment by antobinary** [comment]
I asked @sakky27 to open an issue for this - this was one of the items spotted during the 2.4.0 testing. I think the discrepancy for the behaviour of this particular "lock setting" stems from the fact that it is not a real lock setting - it's something we'll likely have to re-implement correctly at some point. It's more of an upper layer visual filter right now...
