### ISSUE TITLE
Hi,

### ISSUE THREAD

**Issue by eman-98-19** [bigbluebutton/bigbluebutton#13968]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Actual behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, Mac]
 - Browser [e.g. Chrome, Safari]

**Smartphone (please complete the following information):**
 - Browser [e.g. stock browser, Safari]

**Additional context**

**Comment by JeanPluzo** [comment]
Are you going to report an issue or did you just "click on something"?
Please don't play around.

**Comment by eman-98-19** [comment]
I was gonna report another type of issues and I did, sorry I thought I quit
without entering any issues.
