### ISSUE TITLE
Lock viewers add feature lock vote for polling

### ISSUE THREAD

**Issue by tamas-pinter-sol** [bigbluebutton/bigbluebutton#13961]
**Is your feature request related to a problem? Please describe.**
Lock viewers add new feature "lock vote for polling"

**Describe the solution you'd like**
If the switch on new lock viewer feature, lock vote for polling, locked viewers can't able to response for polling.

**Describe alternatives you've considered**

**Additional context**
![image](https://user-images.githubusercontent.com/16936008/146900893-8dbd97d6-7c46-4b07-936f-43633a885f9b.png)

**Comment by ffdixon** [comment]
What is the use case for this?

**Comment by tamas-pinter-sol** [comment]
@ffdixon  If you connect a guest student or course visitor, i lock this viewer, and lock vote feature,
that gives an answer only permit for my students.
