### ISSUE TITLE
BigBlueButton Server 2.4.0 (2818) - Missing Symbols and wrong mouseover text / text - Chrome Version 96.0.4664.110 (Offizieller Build) (x86_64)

### ISSUE THREAD

**Issue by VITSarah** [bigbluebutton/bigbluebutton#13960]
**Describe the bug**
1) The button for starting/stopping audio is missing the symbol, so it is only displayed in blue.
![Bildschirmfoto 2021-12-21 um 08 21 18](https://user-images.githubusercontent.com/74904637/146888308-d6d5afc2-bcbb-4ce7-b0ca-7690c5c06a9d.png)

2) The mouseover text at the icon for minimising maximising the presentation is not set correctly.
<img width="536" alt="Bildschirmfoto 2021-12-21 um 08 23 33" src="https://user-images.githubusercontent.com/74904637/146888638-852a30e6-d9e5-4933-9470-0837558b78df.png">

3) When creating a survey, an incorrect text is entered as the placeholder.
![Bildschirmfoto 2021-12-21 um 08 27 50](https://user-images.githubusercontent.com/74904637/146889071-651a4fd1-3111-4a9f-9706-8fa92ee7526f.png)

4) In the settings area, an incorrect text is stored for the selection of the layout. 
![Bildschirmfoto 2021-12-21 um 08 30 40](https://user-images.githubusercontent.com/74904637/146889397-660feaf7-f65b-45bc-b13e-c86534a64895.png)

**To Reproduce**
Open the browser Chrome in the latest version 96.0.4664.110 (Official Build) (x86_64) and start BigBlueButton in it.

**Expected behavior**
The places mentioned should be displayed as they are in other browsers, e.g. Firefox or Safari.

**BBB version:**

BigBlueButton Server 2.4.0 (2818)

**Desktop (please complete the following information):**
 - OS: MAC 
 - Browser Chrome
 - Version 96.0.4664.110 (Offizieller Build) (x86_64)

**Smartphone (please complete the following information):**
 - Browser [e.g. stock browser, Safari]

**Comment by ffdixon** [comment]
Thanks for submitting this issue.  We just tried a clean install and for English the labels appeared.

![image](https://user-images.githubusercontent.com/290351/146906655-322c4ad6-d1d7-4157-a4db-a1a3a6455913.png)

![image](https://user-images.githubusercontent.com/290351/146906686-77b9e513-99b2-4dd4-aa87-91c5dba3ceeb.png)

It looks like a possible issue with localization.  What locale is your browser using?

**Comment by makabar** [comment]
Looks like German de_DE

**Comment by PhMemmel** [comment]
no issues in German language on my upgraded bbb 2.4.0 server upgraded this morning from 2.4-rc7 via bbb-install.sh.

**Comment by VITSarah** [comment]
Sorry! I have found the error. The cache in Chrome apparently still had elements stored from the BBB2.3 version. 
After clearing the cache, the problems disappeared for me and a colleague.
