### ISSUE TITLE
sending automated notifications

### ISSUE THREAD

**Issue by yazilimevde** [bigbluebutton/bigbluebutton#13962]
**Hello, I have integrated the bigbluebutton into my system and I want to send automatic notifications to the participants at certain times of the meetings, how is this possible?**

**Comment by ffdixon** [comment]
Are you looking for an API to send a chat message to a given session?

**Comment by yazilimevde** [comment]
No, I want to warn the participant by sending a notification in the 10th minute for each lecture (or meeting)

**Comment by ffdixon** [comment]
To clarify, are you looking to provide the BigBlueButton server a time (specified in N minutes) + message on the API create call that causes BigBlueButton to display the message at N minutes into the session?

**Comment by yazilimevde** [comment]
It's not about the chat message. An independent notification. The content is for example 'Is the course going well?' will be written and the user will continue by choosing yes or no. I want to send this notification to the screen of the participants in the 10th minute of the lesson.

**Comment by ffdixon** [comment]
Can you be precise about (1) how you would like to define the message and give it to BigBlueButton, (2) what appears to the user, and (3) what user actions you are looking to support, and (4) what should happen after the user takes the action.

As this point, we're only looking to understand the use case.

**Comment by M5211101** [comment]
Heloo 
I want a message to be sent automatically into the meeting, and that message is the reverse timer warning message at the end of the meeting.How can I do this?
