### ISSUE TITLE
Remove label 'BigBlueButton' from guest lobby message

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#13975]
**Describe the bug**
We have hardcoded BigBlueButton in the title of guest lobby.  

**To Reproduce**
1. Goto demo.bigbluebutton.org
2. Create a room with "Require moderator approval before joining"
3. Start room and join with a guest

**Expected behavior**
The text should simply say "Guest Lobby", which makes it easier to use in settings where users may not be familiar with BigBlueButton

**Actual behavior**
The text says "BigBlueButton - Guest Lobby"

**Screenshots**
![image](https://user-images.githubusercontent.com/290351/147181607-b8bca982-6da4-4452-a576-c9f5f5508f6c.png)

**BBB version:**
BigBlueButton 2.4.0

**Comment by ffdixon** [comment]
See discussion https://groups.google.com/g/bigbluebutton-dev/c/AdtckQYi0zg/m/XdC1VrLQCwAJ.

**Comment by antobinary** [comment]
See discussion in https://github.com/bigbluebutton/bigbluebutton/pull/13777 - it was a requirement for accessibility to include the string. Using a `sed` command anyone can modify it on their apply-config deployment if desired.

**Comment by jamesexperts** [comment]
I have edited /usr/share/meteor/bundle/programs/web.browser/app/locales/en.json
after restarting - bbb-conf --restart
Working for me

**Comment by premmohantyagi** [comment]
I have edited /usr/share/meteor/bundle/programs/web.browser/app/locales/en.json
After restarting    bbb-conf --restart
Working for me

**Comment by sutidor** [comment]
for docker see solution here https://github.com/bigbluebutton/bigbluebutton/pull/13777#issuecomment-1047215506
