### ISSUE TITLE
Layout issue on mobile screen when using BBB in iFrame

### ISSUE THREAD

**Issue by adeel-raza** [bigbluebutton/bigbluebutton#13978]
**Describe the bug**
This happens when embedding BBB meetings in iFrame. The UI part on the right side of the meeting screen is clipped and does not display properly on the mobile view due to which it's not possible to click the presentation icon and also access the Leave/End meeting option on mobile. 

**To Reproduce**
1. join the meeting on mobile phone
2. connect the microphone

**Expected behavior**
A complete view of the meeting screen.

**Actual behavior**
The meeting screen view is clipped from right side

**Screenshots**
![image](https://user-images.githubusercontent.com/7985727/147271517-c89fea56-d5c7-441c-8c11-7d40d25157ab.png)

**BBB version:**
2.4.0

**Desktop (please complete the following information):**
 - OS: any
 - Browser Chrome
 - Version 96

**Smartphone (please complete the following information):**
 - Device: Any smartphone device with resolution 320 x 480 or 320 x 568

**Comment by antobinary** [comment]
Hi @adeel-raza 
Have you tried this with an actual device?
If I recall correctly, the start screenshare button would not be displayed on iOS.. And the `+` button is only for presenter/moderator, I doubt your iPhone would be either of those...

**Comment by adeel-raza** [comment]
@antobinary Yes, I have tried this on actual device too and faced the same issue let me share those screenshots too.
