### ISSUE TITLE
Update api version in BBB 2.4?

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#13972]
Last update was 4 years ago as part of BBB ~~2.2~~ 2.0 (it was made 2.0)
https://github.com/bigbluebutton/bigbluebutton/pull/5126

Lots has changed since then but I don't know if it's time for a 2.1 (or different) or is 2.0 still correct.
I am opening an issue to collect feedback.

**Comment by prlanzarin** [comment]
> Last update was 4 years ago as part of BBB 2.2 (it was made 2.0)

Just a small correction: the change was made as part of _2.0_ ([2.0-RC.2](https://github.com/bigbluebutton/bigbluebutton/blob/73db36bc9d8ede10e531265809cda62b0e59ae5b/bigbluebutton-web/grails-app/conf/bigbluebutton.properties#L193)), not 2.2.

**Comment by ali-alhaidary** [comment]
Does that affect different plugins for LMS systems?

**Comment by antobinary** [comment]
We did not change api version in 2.4...
