### ISSUE TITLE
Recording with MediaSoup: missing Video-Feeds

### ISSUE THREAD

**Issue by krim404** [bigbluebutton/bigbluebutton#13985]
**Describe the bug**
The recording deployed does not include Webcam and Videostreams OR webcam and videostreams are extremly async (>3s)

**To Reproduce**
```
yq w -i \$SFU_CONFIG mediasoup.webrtc.listenIps[0].announcedIp $ip
yq w -i \$SFU_CONFIG mediasoup.webrtc.listenIps[1].ip $ipv6
yq w -i \$SFU_CONFIG mediasoup.webrtc.listenIps[1].announcedIp $ipv6
yq w -i \$SFU_CONFIG mediasoup.plainRtp.listenIp[0].announcedIp $ip
yq w -i \$SFU_CONFIG videoMediaServer mediasoup
yq w -i \$SFU_CONFIG screenshareMediaServer mediasoup
yq w -i \$HTML5_CONFIG public.kurento.signalCandidates false
yq w -i \$HTML5_CONFIG public.kurento.screenshare.mediaServer mediasoup
yq w -i \$HTML5_CONFIG public.kurento.videoMediaServer mediasoup
```

**Expected behavior**
Video should appear in recording

**Actual behavior**
No video in recording

**Comment by ffdixon** [comment]
A few quick questions
  - Is this a new installation or upgrade (see [getting help](https://docs.bigbluebutton.org/support/getting-help.html#help-installing-or-running-bigbluebutton))?
  - Does your server meet the [minimum requirements](https://docs.bigbluebutton.org/2.4/install.html#minimum-server-requirements)
  - Are there any errors when the [record/playback](https://docs.bigbluebutton.org/dev/recording.html) scripts run?

**Comment by krim404** [comment]
It is a new installation, the server is way above the minimum requirements and there are no errors.

**Comment by prlanzarin** [comment]
More information would certainly be needed, like:
  - Recording files (all of them) of an affected session OR a clear way to reproduce that
  - Camera aspect ratio and chosen quality profile
  - Size of sessions
  - Value of the `recordingAdapter` field in webrtc-sfu's config


I've received reports of specific 16:9 cameras on HD profiles not being recorded properly, but that's all so far. Haven't looked into that yet and will only do so after vacations.


Until then, as much info as possible so it's quicker to fix when someone gets to it.

**Comment by krim404** [comment]
Short update: i can reproduce this issue by installing BBB using bbb-install.sh on a fresh 18.04 VM. Before i roll out the config modifications printed in the original post everything is working, after doing these changes the videos are missing in the recordings - even the marker in the timeline is missing. As both recordings are affected (webcam and screenshare) i doubt it has something to do with the quality settings.

I'm using the Front Facing Cam of a Macbook Pro 16" 2021 - this is indeed a FHD widescreen camera. I've conducted my evaluation using the medium quality settings. The screen recording has been done on multiple different windows in various sizes.

The test session is only 30sec long and has one test user.

`recordingAdapter` has been set to Kurento, based on #12894 - which states `our adapter uses Kurento as a walking cane`- should i change this to another value?

**Comment by krim404** [comment]
as three more month have come by - any update on this issue?

**Comment by prlanzarin** [comment]
> as three more month have come by - any update on this issue?
> 
> just for information: running on kurento recording works flawless, problem starts the moment when switched to mediasoup.
> 
> Just in case, i didnt mentioned it before as i was pretty sure it has nothing to do with it: but could it be possibly be an incompatibility with scalelite?

Shouldn't have any relation.

As far as updates are concerned: I have none to give. I'd need more infos to debug this further (mainly the first one I mentioned in a previous comment (`Recording files (all of them) of an affected session`) since I can't really reproduce what you're reporting (missing  events, missing raw files).

We are looking on things such as https://github.com/bigbluebutton/bigbluebutton/issues/14202 and a problem with static screenshare images having problems in post processing, though.

**Comment by krim404** [comment]
Yes i already found this issue, this is very similar, thats why i closed this ticket.
For the record: this has been two issues in one, the fact that no video has been recorded at all is based on the fact, that docker created an interface and the sfu bound to it. The documentation should be updated to set the IP adress everytime, not only in case it is behind a nat.
