### ISSUE TITLE
html5 client does insane STUN tests when other networks on client active

### ISSUE THREAD

**Issue by ArminXG** [bigbluebutton/bigbluebutton#13983]
**Describe the bug**
If the client (linux desktop in my case) has more than one network interface active with other IP address, the echo test takes very long
(> 15 secs) because the STUN test uses IP addresses that doesn't make sense.
All works fine and fast if just one network interface is active (default for most users). But when I start my VPN to company network, another network interface with another local IP address becomes active and the STUN test uses that wrong local IP address for tests too and waits longer time.

**To Reproduce**
1. start another network interface like VPN with another local IP address. Example: on my home router network  I have the main ethernet device with IP 192.168.2.20. When I start the VPN, I have another interface (tun device by openvpn) with a local IP like 172.25.51.126 for the company network (172.16.0.0/12) range.
2. start BBB session with audio for echo test
3. connecting to audio now takes much longer (STUN test)

**Expected behavior**
The STUN test should not take much longer than with just one interface.

**Actual behavior**
The html5 STUN test actually sends packets to STUN server (I tried many different and all have same result),
using all local IPs as source address. With just one network interface, it is just one IP and all is good and fast.
But the second IP is also used as source address on the main network interface. Example:
The main local IP for route to internet through my home route is 192.168.2.20, but STUN sends packets through that
interface with source address 172.25.51.126 (which is the local IP of the VPN interface). 
The wrong packets do reach the STUN server and are answered, but they never reach html5 client, because
home router blocks them (of course). The STUN test then waits and tries it again and again.
This wait time wouldn't be needed if the STUN test just doesn't send these insane packets with wrong
local IP. Using a wrong source IP on a network interface will always fail.
It would make sense if the network interface itself has more than one local IP assigned, but this is just not the case.

**BBB version:**
2.4.0 (tried als 2.2.x)

**Desktop (please complete the following information):**
 - OS: Linux Mint
 - Browser: Chrome
 - Version: Version 96.0.4664.110 

**Additional context**
Is the STUN test part of the html5 client, or is it a Chrome issue after all?

**Comment by PhMemmel** [comment]
This issue will be resolved as soon as the new fullaudio bridge is production ready, see https://docs.bigbluebutton.org/2.4/new.html#faster-audio-activation-using-fullaudio-bridge-experimental

Care: this feature isn't production ready yet (changing of input device not implemented yet etc.), but you can already test it. It shortens the connection time to below 1s for me which is awesome.

**Comment by ffdixon** [comment]
This feature isn't ready yet for production, but it lays the groundwork for implementing it in a future update.  We want this awesomeness as well.

**Comment by prlanzarin** [comment]
Client side STUN checks are normal behavior and certainly not insane. And they will be the same regardless of the client side bridge switch. The fact that it's going to be faster is tangential to that. This is not an issue.

**Comment by ArminXG** [comment]
I know client side checks are normal and of course they are needed.
But the way it is done just doesn't make sense.
Or can you explain why a check sends out a packet with a source address that doesn't belong to the interface it is sent on? A reply never will arrive here.
