### ISSUE TITLE
html5 client loads outdated language file from browser cache after update.

### ISSUE THREAD

**Issue by defnull** [bigbluebutton/bigbluebutton#13984]
The language files are loaded from an URL that does not depend on deployed html5-client version. After an update, if the old files are still present in browser cache, the user will see lots of untranslated replacement strings in UI. This could be fixed by appending the client version as a query parameter, similar to how meteor loads all other resources.

https://github.com/bigbluebutton/bigbluebutton/blob/51023b18b845675906036704ed44e1dfa4c73063/bigbluebutton-html5/imports/startup/client/intl.jsx#L76

**Comment by ffdixon** [comment]
Good catch!
