### ISSUE TITLE
Video of Android/Chrome user scrambled

### ISSUE THREAD

**Issue by ArminXG** [bigbluebutton/bigbluebutton#13982]
**Describe the bug**
Video of participants with Android and Chrome is scrambled for others. It looks like a wrong codec is used. 
It doesn't matter which client/OS/browser the other users have, all see the same scrambled video of that Android user.

**To Reproduce**
1. One participant use Android (12) with Chrome and share video.
2. Others watch the video of that user.

**BBB version:**
2.4.0

**Smartphone (please complete the following information):**
 - Device: Google Pixel 3
 - OS: Android 12
 - Browser Chrome

**Comment by PhMemmel** [comment]
This is most likely not a BBB issue, see #13795

**Comment by ArminXG** [comment]
Oh yes, it seems to be exactly that.
I have it in portait and landscape, but it is definately that issue.
I searched for a similar issue, but did not find that.

Thanks for fast response!
