### ISSUE TITLE
Meeting name is now required, but API documentation does not mention it

### ISSUE THREAD

**Issue by altbdoor** [bigbluebutton/bigbluebutton#13989]
**Describe the bug**
Based on the API documentation in https://docs.bigbluebutton.org/dev/api.html#create , it appears that the `name` (or meeting name) is neither required nor recommended. But as of 2.4, meeting name is now a required field, and with no mention about this in the changelogs.

Seems like it was introduced in f74ea387d7e605ab14aefb576c116d68fdb96236, into [v2.4.0](https://github.com/bigbluebutton/bigbluebutton/releases/tag/v2.4.0) which was released in 21 Dec 2021.

**To Reproduce**
1. Perform an API call to create a meeting room
1. `https://example.bigbluebutton.ch/bigbluebutton/api/create?meetingID=abc123&maxParticipants=8&duration=120&deactivateBbbserverDefaultChatTexts=true&record=true&meta_bbb-recording-ready-url=https%3A%2F%2Fexample.com%2Frecording%2Fcallback&moderatorPW=password123&attendeePW=password123&checksum=8f355831786dc8cd6b6ddee7109c29b5c875cb85`

**Expected behavior**
I could not be sure on what is to be expected, but am rather puzzled on why this was not communicated.

**Actual behavior**
```xml
<response>
<returncode>FAILED</returncode>
<messageKey>nullError</messageKey>
<message>You must provide a meeting name</message>
</response>
```

**Comment by ffdixon** [comment]
Hi @altbdoor, thanks for the (very good) bug report.  We just updated the [API docs](https://docs.bigbluebutton.org/dev/api.html#create) to show that `name` is now required as part of the `create` API call.
