### ISSUE TITLE
Learning Dashboard directory is removed by /etc/cron.daily/bigbluebutton

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#13994]
**Describe the bug**
The following line in [/etc/cron.daily/bigbluebutton](https://github.com/bigbluebutton/bigbluebutton/blob/develop/bigbluebutton-config/cron.daily/bigbluebutton#L31)

~~~
find /var/bigbluebutton/ -maxdepth 1 -type d -name "*-*" -mtime +$history -exec rm -rf '{}' +
~~~

Will delete presentation directories older than `$history`.  These directories have names such as `183f0bf3a0982a127bdb8161e0c44eb696b3e75c-1640633350455`.  

However, the directory `/var/bigbluebutton/learning-dashboard` also matches this pattern and could be removed as well.  

This directory contains the supporting HTML for display of the Learning Dashboard.  Once removed, attempts to open the learning dashboard result in a 403 Forbidden error.

**To Reproduce**
1. Install BigBlueButton 2.4
2. Wait for 5 days without creating meetings (the default value for history=5 in /etc/cron.daily/bigbluebutton)
3. Attempt to launch the Learning Dashboard

**Expected behavior**
The Learning Dashboard launches without error

**Actual behavior**
The directory `/var/bigbluebutton/learning_dashboard` is inadvertently deleted by `/etc/cron.daily/bigbluebutton`.

Once deleted, it could be recreated by re-installing the package `bbb-learning-dashboard` again. 

**Screenshots**
![image](https://user-images.githubusercontent.com/290351/147878348-dce521aa-e10c-44db-8ad7-8c40cbbe6540.png)

This was a subtle issue to detect as you need 5 days of idle time on the BigBlueButton server (no new learning dashboard files created in `/var/bigbluebutton/learning_dashboard`) so that the directory is deleted by the cronjob.

**Comment by ffdixon** [comment]
To fix this for the moment, if this directory disappears on your 2.4 server, you can re-install the files in `/var/bigbluebutton/learning-dashboard` with the command

~~~
apt-get --reinstall install bbb-learning-dashboard
~~~

**Comment by antobinary** [comment]
Thanks for the thorough issue description! And for the fix!!
