### ISSUE TITLE
Preserving Learning Dashboard content after ending session

### ISSUE THREAD

**Issue by myymi** [bigbluebutton/bigbluebutton#13997]
For starters, Happy new Year!
Thanks for next great bbb release, especially for Learning Dashboard feature.

This is feature request for Learning Dashboard. At the moment, there is option to view Dashboard during the session and right after the session, and when the printout is needed, then we use Ctl+P on the browser and save the result to pdf.

We'd like to have export option/button for csv/excel/pdf format from Learning Dashboard, and the option to access this final Dashboard later, after the end of session. This is often needed for reports.
 
We have used browser's printing dialog for reports for now, but you can only access dashboard shortly after the session.

**Comment by ffdixon** [comment]
In the upcoming BigBlueButton 2.5, the Learning Analytics Dashboard is available for download as a CSV file to the moderator during the session and for a few moments after the session finishes.  

Here's a screenshot from 2.5 ... notice the download button in the lower right-hand corner.

<img width="1410" alt="image" src="https://user-images.githubusercontent.com/290351/165511037-360700f5-4fda-4670-8a78-22a1f72b40bf.png">

If your a developer, you an also use [bbb-events](https://github.com/bigbluebutton/bbb-events) to extract out a JSON file that forms the underlying data for the Learning Analytics Dashboard after each session finishes, in case you want to send the data to an external database, for example.

**Comment by antobinary** [comment]
Handled (as CSV) in https://github.com/bigbluebutton/bigbluebutton/pull/13626
You can see a sample output in https://github.com/bigbluebutton/bigbluebutton/pull/13626#issuecomment-977096121

**Comment by mrservat** [comment]
I have a question
I developed a panel to manage Big Blue Button
So that I can access the attendance and absence of students after the end of the class, please guide me.
In the new versions, a dashboard has been added. How can I access that dashboard and student activities with the web service?
