### ISSUE TITLE
Error 1006 after changes described in documentation

### ISSUE THREAD

**Issue by nephilim75** [bigbluebutton/bigbluebutton#13993]
Hello

I got complaints from users, that they cannot connect audio using mobile device coming in from mobile networks. I found this part in documentation: https://docs.bigbluebutton.org/support/troubleshooting.html#configure-bigbluebuttonfreeswitch-to-support-ipv6

Now, after making this changes, noone can connect via audio. Timeout 1006 is coming up for every user by now. :-(

Any idea?

Kind regards
//nephilim

**Comment by ffdixon** [comment]
Can you post this issue to bigbluebutton-setup mailing list and we'll help you there.  To make it easier for others to help, please share as much information as possible.  See https://docs.bigbluebutton.org/support/getting-help.html#help-installing-or-running-bigbluebutton.

**Comment by nephilim75** [comment]
Hm, why not here? Anyhow, I am not familiar with this kind of groups. How to work in there?

**Comment by hostbbb** [comment]
https://groups.google.com/g/bigbluebutton-setup  this google group can help you troubleshout.  this github issue tracker is for software enhancements, and bug reporting.

**Comment by nephilim75** [comment]
Requested access to the group, but no reply yet.
