### ISSUE TITLE
whiteboard issue 

### ISSUE THREAD

**Issue by vahidajorloo** [bigbluebutton/bigbluebutton#13992]
**Describe the bug**
when teacher draws a line or any shape on the whiteboard students cant see it unless they refresh the browser tab ,
every single line that teacher draws will apear to students only after a refresh 
how this can be solved?
this bug is on 2.3.15

**Comment by ffdixon** [comment]
The student won't see the individual strokes as they are drawn, but they should see the final stroke after the instructor releases the mouse.  

Are you able to reproduce this issue in BigBlueButton 2.4 on https://demo.bigbluebutton.org/?
