### ISSUE TITLE
Preserving Learning Dashboard content after ending session

### ISSUE THREAD

**Issue by myymi** [bigbluebutton/bigbluebutton#13996]
For starters, Happy new Year!
Thanks for next great release, especially for Learning Dashboard feature. 
Are there any plans for adding export option to this dasboard, either as PDF or CSS? For now, we suggest users to use browser's printing function for that.
Also, some of our users were asking if those dashboards could be added to the room recordings as downloadable files afterwards, for reporting purposes.

**Comment by myymi** [comment]
Wrong place, not an issue, just feature request, sorry.

**Comment by ffdixon** [comment]
In the future, please follow the issue template for requesting new features.  It makes it easier for us to plan ahead for 2022.
