### ISSUE TITLE
bigbluebutton 2.4.0 media-server overload

### ISSUE THREAD

**Issue by himpierre** [bigbluebutton/bigbluebutton#14009]
**Describe the bug**
From time to time i get reports from users they can't start video any more and get a "media-server overload" message. This usually happens when the server is under heavy load. 

Error message:
```
Jan 04 20:25:10 letsmeet kurento-media-server[28281]: **
Jan 04 20:25:10 letsmeet kurento-media-server[28281]: libnice:ERROR:../../agent/conncheck.c:969:priv_conn_check_tick_stream_nominate: as
Jan 04 20:25:10 letsmeet kurento-media-server[28281]: Aborted (thread 139706050160384, pid 28281)
Jan 04 20:25:10 letsmeet kurento-media-server[28281]: Stack trace:
Jan 04 20:25:10 letsmeet kurento-media-server[28281]: [gsignal]
Jan 04 20:25:10 letsmeet kurento-media-server[28281]: /lib/x86_64-linux-gnu/libc.so.6:0x3EFB7
Jan 04 20:25:11 letsmeet kurento-media-server[28281]: [abort]
Jan 04 20:25:11 letsmeet kurento-media-server[28281]: /lib/x86_64-linux-gnu/libc.so.6:0x40921
Jan 04 20:25:11 letsmeet kurento-media-server[28281]: [g_assertion_message]
Jan 04 20:25:11 letsmeet kurento-media-server[28281]: /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0:0x73445
Jan 04 20:25:11 letsmeet kurento-media-server[28281]: [g_assertion_message_cmpnum]
Jan 04 20:25:11 letsmeet kurento-media-server[28281]: /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0:0x737F2
Jan 04 20:25:11 letsmeet kurento-media-server[28281]: [nice_candidate_equal_target]
Jan 04 20:25:11 letsmeet kurento-media-server[28281]: /usr/lib/x86_64-linux-gnu/libnice.so.10:0x1DB97
Jan 04 20:25:11 letsmeet kurento-media-server[28281]: [nice_agent_close_async]
Jan 04 20:25:11 letsmeet kurento-media-server[28281]: /usr/lib/x86_64-linux-gnu/libnice.so.10:0xBEDA
Jan 04 20:25:11 letsmeet kurento-media-server[28281]: [g_source_get_time]
Jan 04 20:25:11 letsmeet kurento-media-server[28281]: /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0:0x4CE23
Jan 04 20:25:11 letsmeet kurento-media-server[28281]: [g_main_context_dispatch]
Jan 04 20:25:11 letsmeet kurento-media-server[28281]: /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0:0x4C3A5
Jan 04 20:25:11 letsmeet kurento-media-server[28281]: [g_main_context_dispatch]
Jan 04 20:25:11 letsmeet kurento-media-server[28281]: /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0:0x4C770
Jan 04 20:25:11 letsmeet kurento-media-server[28281]: [g_main_loop_run]
Jan 04 20:25:11 letsmeet kurento-media-server[28281]: /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0:0x4CA82
Jan 04 20:25:11 letsmeet kurento-media-server[28281]: [kms_loop_get_type]
Jan 04 20:25:11 letsmeet kurento-media-server[28281]: /usr/lib/x86_64-linux-gnu/libkmsgstcommons.so.6:0x21435
Jan 04 20:25:11 letsmeet kurento-media-server[28281]: [g_test_get_filename]
Jan 04 20:25:11 letsmeet kurento-media-server[28281]: /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0:0x742A5
Jan 04 20:25:11 letsmeet kurento-media-server[28281]: [start_thread]
Jan 04 20:25:11 letsmeet kurento-media-server[28281]: /lib/x86_64-linux-gnu/libpthread.so.0:0x76DB
Jan 04 20:25:11 letsmeet kurento-media-server[28281]: [clone]
Jan 04 20:25:11 letsmeet kurento-media-server[28281]: /lib/x86_64-linux-gnu/libc.so.6:0x12171F
Jan 04 20:25:11 letsmeet systemd[1]: kurento-media-server.service: Main process exited, code=killed, status=6/ABRT
Jan 04 20:25:11 letsmeet systemd[1]: kurento-media-server.service: Failed with result 'signal'.
```

So it seems kurento-media-server got killed.

**Expected behavior**
Media Server should not get killed.

**Actual behavior**
Media Server gets killed.

During the media-server restart a lot of:
```
Jan  4 20:25:12 letsmeet bbb-webrtc-sfu[16865]: 2022-01-04T20:25:12.712Z - warn: [mcs-sdp-session] Failed to add ICE candidate mediaSess
ionId=black-dream-meAu8_G, mediaId=late-night-joZihTG, candidate=, sdpMid=video0, sdpMLineIndex=0, usernameFragment=91e46e5a, code=2201,
 type=MEDIA_OBJECT_NOT_FOUND, details=Object 'b81cdeda-b2af-4be1-874d-945feb88c802_kurento.MediaPipeline/1e23c2f6-ffab-453f-b403-8fbede6
83ed4_kurento.WebRtcEndpoint' not found, stackWasLogged=true
Jan  4 20:25:12 letsmeet bbb-webrtc-sfu[16865]: 2022-01-04T20:25:12.712Z - error: [mcs-router] Rejecting operation addIceCandidate opera
tion=addIceCandidate, errorCode=2201, errorMessage=MEDIA_NOT_FOUND, details=Object 'b81cdeda-b2af-4be1-874d-945feb88c802_kurento.MediaPi
peline/1e23c2f6-ffab-453f-b403-8fbede683ed4_kurento.WebRtcEndpoint' not found, stack=ReferenceError: Object 'b81cdeda-b2af-4be1-874d-945
feb88c802_kurento.MediaPipeline/1e23c2f6-ffab-453f-b403-8fbede683ed4_kurento.WebRtcEndpoint' not found
Jan  4 20:25:12 letsmeet bbb-webrtc-sfu[16865]:     at /usr/local/bigbluebutton/bbb-webrtc-sfu/node_modules/kurento-client/lib/KurentoCl
ient.js:365:24
Jan  4 20:25:12 letsmeet bbb-webrtc-sfu[16865]:     at Object.dispatchCallback [as callback] (/usr/local/bigbluebutton/bbb-webrtc-sfu/no
de_modules/kurento-jsonrpc/lib/index.js:546:9)
Jan  4 20:25:12 letsmeet bbb-webrtc-sfu[16865]:     at processResponse (/usr/local/bigbluebutton/bbb-webrtc-sfu/node_modules/kurento-jso
nrpc/lib/index.js:667:15)
Jan  4 20:25:12 letsmeet bbb-webrtc-sfu[16865]:     at RpcBuilder.decode (/usr/local/bigbluebutton/bbb-webrtc-sfu/node_modules/kurento-j
sonrpc/lib/index.js:723:5)
Jan  4 20:25:12 letsmeet bbb-webrtc-sfu[16865]:     at Stream.transportMessage (/usr/local/bigbluebutton/bbb-webrtc-sfu/node_modules/kur
ento-jsonrpc/lib/index.js:208:10)
Jan  4 20:25:12 letsmeet bbb-webrtc-sfu[16865]:     at Stream.emit (events.js:314:20)
Jan  4 20:25:12 letsmeet bbb-webrtc-sfu[16865]:     at Stream.EventEmitter.emit (domain.js:483:12)
Jan  4 20:25:12 letsmeet bbb-webrtc-sfu[16865]:     at drain (/usr/local/bigbluebutton/bbb-webrtc-sfu/node_modules/through/index.js:36:1
6)
Jan  4 20:25:12 letsmeet bbb-webrtc-sfu[16865]:     at Stream.stream.queue.stream.push (/usr/local/bigbluebutton/bbb-webrtc-sfu/node_mod
ules/through/index.js:45:5)
Jan  4 20:25:12 letsmeet bbb-webrtc-sfu[16865]:     at WebsocketStream.onMessage (/usr/local/bigbluebutton/bbb-webrtc-sfu/node_modules/w
ebsocket-stream/index.js:45:15)
Jan  4 20:25:12 letsmeet bbb-webrtc-sfu[16865]: 2022-01-04T20:25:12.713Z - error: [video] ICE candidate failed to be added for
```

cheers, t.

**Comment by ffdixon** [comment]
We would recommend enabling Mediasoup as your default media server.  See https://docs.bigbluebutton.org/2.4/new.html#mediasoup.

You'll find webcams start faster and use less resources on the server.

**Comment by himpierre** [comment]
@ffdixon thanks for the hint. Three questions though. 

1. The config settings mentioned in https://github.com/bigbluebutton/bigbluebutton/pull/13112 go to /usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml?
2. /etc/bigbluebutton/bbb-webrtc-sfu/ needs to be created? Is that correct?
3. What do I put in public.kurento.screenshare.mediaServer? mediasoup? MediaSoup?

Thanks again!

**Comment by prlanzarin** [comment]
3. `mediasoup`, lowercase (the thing is case sensitive)
2. If not yet created, yes. See: https://docs.bigbluebutton.org/admin/configuration-files.html#local-overrides-for-configuration-settings, file name is `production.yml`.
1. No. /etc/bigbluebutton/bbb-html5.yml (same approach as item 2.)

**Comment by himpierre** [comment]
Thanks @prlanzarin 

Now it looks like this:
```
root@letsmeet:~# cat /etc/bigbluebutton/bbb-html5.yml 
public:
  kurento:
    screenshare:
      mediaServer: mediasoup
    videoMediaServer: mediasoup
    listenOnlyMediaServer: mediasoup
meta_media-server-screenshare: mediasoup
meta_media-server-video: mediasoup
meta_media-server-listenonly: mediasoup
root@letsmeet:~#
```

```
root@letsmeet:~# cat /etc/bigbluebutton/bbb-webrtc-sfu/production.yml 
mediasoup:
  webrtc:
    listenIps:
      - ip: 0.0.0.0
        announcedIp: xxx.xxx.xxx.xxx
  plainRtp:
    listenIp:
      ip: 0.0.0.0
      announcedIp: xxx.xxx.xxx.xxx
root@letsmeet:~#
```

Does it look right?
cheers, t.

**Comment by prlanzarin** [comment]
You can remove the meta_* entries from bbb-html5.yml.

Otherwise: looks ok. Restart BBB and try it out.

**Comment by himpierre** [comment]
Looks good. Big Thanks again. Closing the ticket.

**Comment by ffdixon** [comment]
Please share your experience on whether this new configuration has better performance.

**Comment by himpierre** [comment]
Will do!

**Comment by mauser8004** [comment]
Hi! Unfortunately, we also had an overload.
I did what I wrote.
cat /etc/bigbluebutton/bbb-webrtc-sfu/production.yml | sed ip
mediasoup:
  webrtc:
    listenIps:
      - ip: 0.0.0.0
        announcedIp: xxxxxx
  plainRtp:
    listenIp:
      ip: 0.0.0.0
      announcedIp: xxxxxx

AND

cat /etc/bigbluebutton/bbb-html5.yml
public:
  kurento:
    screenshare:
      mediaServer: mediasoup
    videoMediaServer: mediasoup
    listenOnlyMediaServer: mediasoup
    #meta_media-server-screenshare: mediasoup
    #meta_media-server-video: mediasoup
    #meta_media-server-listenonly: mediasoup


<pre>
 sed ip, and domain XXX

BigBlueButton Server 2.4.0 (2818)
                    Kernel version: 5.4.0-1064-azure
                      Distribution: Ubuntu 18.04.6 LTS (64-bit)
                            Memory: 32887 MB
                         CPU cores: 8

/etc/bigbluebutton/bbb-web.properties (override for bbb-web)
/usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties (bbb-web)
       bigbluebutton.web.serverURL: https://xxxdomainxxx
                defaultGuestPolicy: ALWAYS_ACCEPT
                 svgImagesRequired: true
              defaultMeetingLayout: SMART_LAYOUT

/etc/nginx/sites-available/bigbluebutton (nginx)
                       server_name: xxxdomainxxx
                              port: 80, [::]:80
                              port: 443 ssl

/opt/freeswitch/etc/freeswitch/vars.xml (FreeSWITCH)
                       local_ip_v4: 10.50.0.4
                   external_rtp_ip: xxxxxx
                   external_sip_ip: xxxxxx

/opt/freeswitch/etc/freeswitch/sip_profiles/external.xml (FreeSWITCH)
                        ext-rtp-ip: $${external_rtp_ip}
                        ext-sip-ip: $${external_sip_ip}
                        ws-binding: xxxxxx:5066
                       wss-binding: xxxxxx:7443

/usr/local/bigbluebutton/core/scripts/bigbluebutton.yml (record and playback)
                     playback_host: xxxdomainxxx
                 playback_protocol: https
                            ffmpeg: 4.2.4-1ubuntu0.1bbb2~18.04

/etc/bigbluebutton/nginx/sip.nginx (sip.nginx)
                        proxy_pass: xxxxxx
                          protocol: http

/usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml (Kurento SFU)
/etc/bigbluebutton/bbb-webrtc-sfu/production.yml (Kurento SFU - override)
                        kurento.ip: xxxxxx
                       kurento.url: ws://127.0.0.1:8888/kurento
                    kurento.sip_ip: xxxxxx
               recordScreenSharing: true
                     recordWebcams: true
                  codec_video_main: VP8
               codec_video_content: VP8

/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml (HTML5 client)
/etc/bigbluebutton/bbb-html5.yml (HTML5 client config override)
                             build: 2440
                        kurentoUrl: wss://xxxdomainxxx/bbb-webrtc-sfu
                  enableListenOnly: true
                    sipjsHackViaWs: true

/usr/share/bbb-web/WEB-INF/classes/spring/turn-stun-servers.xml (STUN Server)
                              stun: stun.l.google.com:19302

/etc/kurento/modules/kurento/WebRtcEndpoint.conf.ini (STUN Server)
                              stun: 172.217.212.127:19302


# Potential problems described below


#
# Warning: Failed to verify STUN server at stun.l.google.com 19302 with command
#
#    stunclient --mode full --localport 30000 stun.l.google.com 19302
#

#
# Warning: Failed to verify STUN server at 172.217.212.127:19302 with command
#
#    stunclient --mode full --localport 30000 172.217.212.127 19302
</pre>
BigBlueButton Server 2.4.0 (2818)
/etc/bigbluebutton/bbb-webrtc-sfu/production.yml (Kurento SFU - override)
/etc/bigbluebutton/bbb-html5.yml (HTML5 client config override)

How can I check if you're really using mediasoup?

Why not print mediasoup instead of Kurento?

**Comment by hostbbb** [comment]
need apply_lib function to configure mediasoup/kurento?  Let me look at this.

**Comment by mauser8004** [comment]
Don't be mad but I don't understand what you mean

**Comment by prlanzarin** [comment]
@mauser8004 

> Why not print mediasoup instead of Kurento?

Because bbb-conf wasn't extended to expose those settings yet, that's just it.

> How can I check if you're really using mediasoup?

If you want to be 100% sure: the most direct way to figure out whether it's being used is checking about:webrtc (Firefox) or chrome://webrtc-internals. Eg.: open one of those, share a camera. Look for the remote description (SDP); see if it contains `mediasoup-client` in the SDP header.

If you want to be 90% sure: tail -f /var/log/bbb-webrtc-sfu.log | grep -i "mediasoup", share a camera. See if there are a few logs with the `[mediasoup-adp]` prefix.

If you are more keen on the intuitive approach: if it's _pretty fast_ to share a camera, it's mediasoup.

That being said: if you configured everything **exactly as specified**, mediasoup is being used.

**Comment by himpierre** [comment]
After running BigBluButton with mediasoup for a few days now it's safe to say performance is a lot better. No crashes any more either. So it seems mediasoup is preferable. :) Thanks again for the help setting this up.

**Comment by mauser8004** [comment]
Hi!
A week of running the mediasoup well. There were 66 camera shares on the server at one time. But unfortunately there are times when you return this error message: Call to userUnshareWebcam failed because Meteor is not connected

**Comment by prlanzarin** [comment]
> Hi! A week of running the mediasoup well. There were 66 camera shares on the server at one time. But unfortunately there are times when you return this error message: Call to userUnshareWebcam failed because Meteor is not connected

That's a client reconnect. Unrelated to this issue, or just related in the broad spectrum.
