### ISSUE TITLE
Can't assing participant to a breakout room

### ISSUE THREAD

**Issue by pedrobmarin** [bigbluebutton/bigbluebutton#14008]
**Describe the bug**
Can't drag and drop a participant to a breakout room.

**To Reproduce**
1. Join a moderator and a viewer
2. Click to create breakout rooms
3. Try to drag and drop the viewer to a breakout room

![Peek 2022-01-05 11-44](https://user-images.githubusercontent.com/1778398/148237577-539f5694-e291-460d-ac78-88f358db3ae7.gif)

**BBB version:**
2.4 Client build: 2450

**Desktop (please complete the following information):**
 - OS: Linux Mint
 - Browser Chrome
 - Version 97.0.4692.71

OBS.: Might be related with a display issue when using multiple monitors.

**Comment by gustavotrott** [comment]
Hey @pedrobmarin,
I am not being able to reproduce the problem.. did you check for any Console error?
If you discover any further details about when this problem happens will be very helpful!

**Comment by pedrobmarin** [comment]
Hi @gustavotrott ,

The problem seems to be related with my OS display setup and Chrome. The result of my drag-and-dropping name is a text file at my desktop. I'll try to record this once more.

**Comment by pedrobmarin** [comment]
No error on console and inside that text file is the user internal id

![Peek 2022-01-10 17-58](https://user-images.githubusercontent.com/1778398/148838655-155567b3-3bb2-4563-acbe-d332e620d745.gif)

**Comment by antobinary** [comment]
I also encountered this issue earlier today, it's not just @pedrobmarin

**Comment by gustavotrott** [comment]
This is a Chrome/Chromium bug, not related with BigBlueButton code.

The bug is reported in: https://bugs.chromium.org/p/chromium/issues/detail?id=1286294&q=draggable&can=2
