### ISSUE TITLE
Certificate doesn't match after change of hostname

### ISSUE THREAD

**Issue by nephilim75** [bigbluebutton/bigbluebutton#14011]
**Describe the bug**
Set a new hostname and cannot reach server any longer.

**To Reproduce**
1. `bbb-conf --setip bbb.domain.tld`
2. adapted `greenlight/.env` (bbb endpoint & safe host)
3. `docker-compose down`, `docker-compose up -d`, `bbb-conf --restart`
4. Error: `.curl: (51) SSL: no alternative certificate subject name matches target host name 'bbb.mydomain.de'`

**Expected behavior**
New obtained and installed certificate

**Actual behavior**
No new certificate

How can I recreate the new LE cert using bbb system?

Kind regards
//neph

**Comment by ffdixon** [comment]
Was the system working before you did steps (1) to (4)?

**Comment by nephilim75** [comment]
Yes, it did. It worked perfectly well before.

**Comment by lonesomewalker** [comment]
bbb.domain.tld looks different from bbb.mydomain.de ? (or is this a replacement error?)

If you set up the server by bbb-install.sh, simply just run the command again with the correct name.
Works 99%.
