### ISSUE TITLE
Add API call to insert a presentation from the front-end into a live session

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#14014]
**Is your feature request related to a problem? Please describe.**
Some front-ends to BigBlueButton also act as a document repository (such as using NextCloud).  These documents are available to the teacher to help them during their online class.

Currently, BigBlueButton can only accept an uploaded document during create ([pre-upload slides](https://docs.bigbluebutton.org/dev/api.html#pre-upload-slides)).

**Describe the solution you'd like**
Add a new API call to inject a document into a live BigBlueButton session.  This would give front-end developers the ability to put a (display) button next to a list of documents that, when clicked, would send an API call to BigBlueButton with a URL to retrieve the document.

The instructor would see the toast message appear with the document converting process and, after converted, the new document becoming visible.

The API call `insertdocument` would pass two parameters
  - `meetingID`
  - `URL to document`
  

**Describe alternatives you've considered**
BigBlueButton could be given additional privileges to login to a document repository (such as OAuth), but it puts the logic of login, navigation, and selecting a document within BigBlueButton itself.

**Comment by sualko** [comment]
I like the idea of the new endpoint. The alternative would make things way more complicated both on BBB and client side.

> after converted, the new document becoming visible

Would be great if this could be controlled by an additional parameter. I'm thinking about bulk uploads which would otherwise result in "flickering" presentations.
