### ISSUE TITLE
Guest users appear twice if they join, before start of meeting

### ISSUE THREAD

**Issue by SashoVihVas** [bigbluebutton/bigbluebutton#14013]
**Describe the bug**
Every waiting guest user appears for ~ 15 seconds twice in the panel of the moderator at the beginning, if the guest user has requested joining before the meeting has started.

**To Reproduce**
1. The conference room has a guest policy ASK_MODERATOR
2. A guest user tries to join the meeting before the meeting has started
3. The room owner then starts the meeting

**Expected behavior**
Each guest user should appear just once in the panel for user management on the moderator side

**Actual behavior**
Each guest user has two entries for about ~ 15 seconds in the panel for user management on the moderator side. Then one of the entries stays and the other one disappears.

**BBB version:**
v.2.4.x - release

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Chrome

**Comment by pedrobmarin** [comment]
Hey @SashoVihVas ,

Looks like Greenlight is sending multiple join requests for its own lobby room. The 15 seconds make sense because BigBlueButton has an waiting guest control for guests that close the client's waiting guest page.
