### ISSUE TITLE
Delete RaP deploy script

### ISSUE THREAD

**Issue by danielpetri1** [bigbluebutton/bigbluebutton#14026]
**Describe the bug**
After deploying recording scripts in a development environment, playback of recordings stop working.

**To Reproduce**
1. Run `/bigbluebutton/record-and-playback/deploy.sh`
    - This removes `/var/bigbluebutton/playback/*`
    - Presentation playback files are re-added with `cp -r $playback_dir /var/bigbluebutton/playback/`
2.  Attempt playing a recording back
3. See HTTP errors

**Expected behavior**
Playback still works.

**Actual behavior**
The 2.3 playback directory is removed but not copied over, since [/record-and-playback/presentation/playback/presentation](https://github.com/bigbluebutton/bigbluebutton/tree/develop/record-and-playback/presentation/playback/presentation) only contains the files up to 2.0.

**Workaround**
A fix to manually get around the problem is reinstalling [bbb-playback](https://github.com/bigbluebutton/bbb-playback).

Version: latest develop (2022-01-07) code on 2.4-rc7 (2778)

**Comment by antobinary** [comment]
Let's leave this issue open with the intent on deleting the deploy script (and related files?). Do we need to update any docs? Do we have a suggested alternative - what do people use if not deploy.sh?

**Comment by danielpetri1** [comment]
I don't think any docs need to be updated. The instructions on how to setup a development environment for the recording scripts is only contained in the README.

As for an alternative, the script works as intended when the playback-related lines are commented out. I could add this workaround along with the steps on how to run the scripts manually together with the documentation changes from PR [#14022](https://github.com/bigbluebutton/bigbluebutton/pull/14022#issuecomment-1018874972).

**Comment by danielpetri1** [comment]
Since @GuiLeme's PR I cannot reproduce the issue anymore. From his video, I believe the reason playback did not work for him is `playback_host` in `bigbluebutton.yml` not having been set to the correct hostname. 

I've documented the use of the deploy script in the recording documentation since it seems to be working now (PR coming soon). Instead of deleting it, maybe we could consider refactoring it, since the same bash instructions are repeated many times.
