### ISSUE TITLE
Allow use of multiple microphones for one user

### ISSUE THREAD

**Issue by Franz-Heinz** [bigbluebutton/bigbluebutton#14028]
Like described in https://groups.google.com/g/bigbluebutton-setup/c/Nm7UVvk7TsI there are common cases where such a function would be useful.

Best case would be to have the possibility to name each microphone individually (like 'mic-teacher', 'mic-student', ...) and buttons that enable the user to mute single microphones with just one click.

**Comment by stefa168** [comment]
I can confirm that such a functionality would be extremely useful in our university, as the professors use their microphone but the questions made by the students cannot be heard at all.

Would be useful to be able to mute a microphone also when playing the recording, and maybe having some sort of "microphone activity" indicator for the different mics.
