### ISSUE TITLE
[endCallbackUrl] post learning dashboard URL 

### ISSUE THREAD

**Issue by Kaabi** [bigbluebutton/bigbluebutton#14032]
**Is your feature request related to a problem? Please describe.**
Would be great for LMS integrations to have the report name added to endCallbackUrl which can help to develop externals LMS reports based on letting the moderator access the session even after it ended or to retrieve the Learning Dashboard JSON file using internal meeting id & report name.

**Describe the solution you'd like**
sending new parameter in endCallbackUrl called learningdashboard_reportname and should contain the report name

**Describe alternatives you've considered**
add API to retrieve learning dashboard report name by using internal meeting id

**Comment by ffdixon** [comment]
Hi Kaabi,

This might be what you are looking for.  

Here's a sample [post processing script](https://github.com/bigbluebutton/bigbluebutton/blob/5743b29ebaa7ac2d51de6550f5d51dbe29edeb3c/record-and-playback/core/scripts/post_events/post_events_analytics_callback.rb) (it gets run after processing every recorded meeting) that will post a JSON file of the same data used in the Learning Analytics Dashboard.  You can install this on your BigBlueButton server and pass it an [analytics-callback-url](https://github.com/bigbluebutton/bigbluebutton/blob/5743b29ebaa7ac2d51de6550f5d51dbe29edeb3c/record-and-playback/core/scripts/post_events/post_events_analytics_callback.rb#L151) as part of the meta-data when creating the meeting.

It uses the [bbb-events](https://github.com/bigbluebutton/bbb-events) gem to generate the JSON file.

**Comment by Kaabi** [comment]
> Hi Kaabi,
> 
> This might be what you are looking for.
> 
> Here's a sample [post processing script](https://github.com/bigbluebutton/bigbluebutton/blob/5743b29ebaa7ac2d51de6550f5d51dbe29edeb3c/record-and-playback/core/scripts/post_events/post_events_analytics_callback.rb) (it gets run after processing every recorded meeting) that will post a JSON file of the same data used in the Learning Analytics Dashboard. You can install this on your BigBlueButton server and pass it an [analytics-callback-url](https://github.com/bigbluebutton/bigbluebutton/blob/5743b29ebaa7ac2d51de6550f5d51dbe29edeb3c/record-and-playback/core/scripts/post_events/post_events_analytics_callback.rb#L151) as part of the meta-data when creating the meeting.
> 
> It uses the [bbb-events](https://github.com/bigbluebutton/bbb-events) gem to generate the JSON file.

getting analytics JSON file is the alternative solution, but my main request was to send learning dashboard URL in endCallbackUrl
