### ISSUE TITLE
[2.4] FreeSWITCH listen only disconnects after a few seconds

### ISSUE THREAD

**Issue by prlanzarin** [bigbluebutton/bigbluebutton#14034]
**Describe the bug**

FreeSWITCH listen only (the fallback mode) seems to always disconnect a few seconds after a successful connection was established.

**To Reproduce**

1. Set `public.kurento.enableListenOnly: false` in /etc/bigbluebutton/bbb-html5.yml (forces FS listen only)
2. Join listen only on a meeting
3. Listen only disconnects after a few seconds then reconnects (then proceeds to do the same thing forever)

**Expected behavior**

Listen only connection should stay up under normal circumstances.

**BBB version:**

v2.4.0

**Environment**
  - Linux Mint
  - Firefox 96, Chrome 96

**Comment by ashishkpaul** [comment]
Same with me
