### ISSUE TITLE
Getting UserJoinedMeetingEvtMsg: Error: Match error: Missing key 'pin'

### ISSUE THREAD

**Issue by akshaykatale99** [bigbluebutton/bigbluebutton#14031]
**Describe the bug**
Getting  following error on html5 client developmnet.

		error: UserJoinedMeetingEvtMsg: Error: Match error: Missing key 'pin'
		I20220108-19:11:49.839(0)?     at check (packages/check/match.js:36:17)
		I20220108-19:11:49.842(0)?     at addUser (imports/api/users/server/modifiers/addUser.js:23:3)
		I20220108-19:11:49.845(0)?     at EventEmitter.handleUserJoined (imports/api/users/server/handlers/userJoined.js:10:3)
		I20220108-19:11:49.847(0)?     at EventEmitter.emitAsync (/home/akshay/bigbluebutton/bigbluebutton-html5/node_modules/eventemitter2/lib/eventemitter2.js:463:31)
		I20220108-19:11:49.850(0)?     at MeetingMessageQueue.handleTask (imports/startup/server/redis.js:114:10)
		I20220108-19:11:49.852(0)?     at imports/startup/server/redis.js:126:28
		I20220108-19:11:49.853(0)?     at Queue.start (/home/akshay/bigbluebutton/bigbluebutton-html5/node_modules/queue/index.js:145:17)
		I20220108-19:11:49.855(0)?     at Queue.<computed> [as push] (/home/akshay/bigbluebutton/bigbluebutton-html5/node_modules/queue/index.js:59:12)
		I20220108-19:11:49.857(0)?     at MeetingMessageQueue.add (imports/startup/server/redis.js:125:16)
		I20220108-19:11:49.859(0)?     at RedisPubSub.handleMessage (imports/startup/server/redis.js:327:63)
		I20220108-19:11:49.861(0)?     at runWithEnvironment (packages/meteor.js:1320:24)

**To Reproduce**
Followed all steps from html5 development. installed ssl. but still getting this error when i try to join the meeting after **npm start**

**Expected behavior**
Should start meeting.

**Actual behavior**
Stuck at blue screen

**Screenshots**
![image](https://user-images.githubusercontent.com/12472207/148657023-5033caf9-d67f-498c-a8a1-9e8cf0735b66.png)

**BBB version:**

BigBlueButton Server 2.4.0 (2813)

**Comment by PhMemmel** [comment]
Can you doublecheck that your branch already includes https://github.com/bigbluebutton/bigbluebutton/pull/14000?

**Comment by prlanzarin** [comment]
Most likely not related to 14000.

If you're building only bbb-html5 @HEAD V2.4.X-RELEASE over a 2.4.0 installation, you'll need to build Akka apps, BBB common message and bbb-web otherwise you're running an inconsistent env.

Also: appropriate place for this is bigbluebutton-setup mailing list.

**Comment by akshaykatale99** [comment]
@prlanzarin is there any fix for this? @PhMemmel yes my branch includes #14000.

**Comment by prlanzarin** [comment]
> @prlanzarin is there any fix for this?

[As I mentioned:](https://docs.bigbluebutton.org/2.4/dev.html)

> If you're building only bbb-html5 @ HEAD V2.4.X-RELEASE over a 2.4.0 installation, you'll need to build Akka apps, BBB common message and bbb-web otherwise you're running an inconsistent env.
> 
> Also: appropriate place for this is bigbluebutton-setup mailing list.

Otherwise, use the v2.4.0 tag when running dev bbb-html5 instead of branch v2.4.x-release.

**Comment by akshaykatale99** [comment]
Ok. @prlanzarin as per your suggestion I am trying to build Akka apps, BBB common message, and bbb-web. now I am getting this error. could you please suggest anything on that?

    ERROR:  bbb-web must run as bigbluebutton user ( because of the uploaded files permissions )

**Comment by prlanzarin** [comment]
The error is pretty clear. Either run the thing as bigbluebutton or comment the block that checks that in the run.sh script and try again.

And, I don't want to be a prick, but for the last time: use the mailing lists for this.
