### ISSUE TITLE
User list Direction set wrong on changing default_locale over API

### ISSUE THREAD

**Issue by misisol** [bigbluebutton/bigbluebutton#14033]
**Describe the bug**
When the overrideLocale in settings.yml is set to a RTL language ( ex. fa_IR) and try to change it over API with bbb_override_default_locale to a LTR language ( ex. en ) the user list are falsely designed to be shown in RTL on joining conference ( or even with refreshing the page ).
But after closing the user list and opening it again, it get fixed. 

On joining event  :
<img width="153" alt="Screen Shot 2022-01-09 at 11 17 44 PM" src="https://user-images.githubusercontent.com/26188869/148698231-6245a808-4cdf-4a43-89a0-0f8f71a4dac9.png">
<img width="413" alt="Screen Shot 2022-01-09 at 11 09 07 PM" src="https://user-images.githubusercontent.com/26188869/148698234-88e0a4eb-e9c2-46e0-af4e-da93340702f7.png">

After closing and opening it again :
<img width="153" alt="Screen Shot 2022-01-09 at 11 18 07 PM" src="https://user-images.githubusercontent.com/26188869/148698249-1abe6d4b-0a96-454d-9f31-bdbb6cf20cd2.png">
<img width="364" alt="Screen Shot 2022-01-09 at 11 18 14 PM" src="https://user-images.githubusercontent.com/26188869/148698253-21f38498-9258-4be1-a46c-ce7f554e1418.png">

**Comment by ramonlsouza** [comment]
Hello @misisol, do you see this behavior in version 2.3? I tried to reproduce it in 2.4 and it works as expected (page loads in fa_IR/RTL and then changes to en/LTR when the api parameters are available), see attached video:


https://user-images.githubusercontent.com/3728706/148951020-f6ce9f50-92ab-4362-b14d-a1a6b5b76522.mov

**Comment by misisol** [comment]
[](url)We see it on 2.4 version.
in settings.yml : 
```
fallbackLocale: fa_IR
overrideLocale: fa_IR
```

API Parameter :
`bbb_override_default_locale="en";
`
[https://youtu.be/eItad9tINi0](url)

**Comment by misisol** [comment]
> While trying to reproduce the bug again, I noticed that the file included in issue description is a bit different that what we currently have in 2.4, which means your bbb setup is outdated (and does not have the changes made by PR #11724).
> 
> your file:
> 
> ```
> <div data-test="userListItemCurrent" class keepopen="false" aria-expanded="false" stvle-"direction: rtl:">
> ```
> 
> current 2.4:
> 
> ```
> <div data-test="userListItemCurrent" style="direction: ltr; width: 100%;">
> ```
> 
> Updating bigbluebutton packages should fix the problem.

I'll Install the lastest version (2.4.1) to see if the problem exists.

**Comment by antobinary** [comment]
Let's reopen if needed
