### ISSUE TITLE
Chat replying

### ISSUE THREAD

**Issue by misisol** [bigbluebutton/bigbluebutton#14041]
It would be nice to reply chats on public chat to help the conversation keep going on more efficiently.

**Comment by antobinary** [comment]
Hi @misisol could you please fill out the template for the issue or at least elaborate more on what you meant?

Possible duplicate of the threads [visually] described in https://github.com/bigbluebutton/bigbluebutton/issues/7110

**Comment by misisol** [comment]
It the same thing as marking a message an relying it in whatsapp messenger which you can reply a single message.
