### ISSUE TITLE
Error 1006 - echo test fails on any browser

### ISSUE THREAD

**Issue by Entretoize** [bigbluebutton/bigbluebutton#14051]
After an echo test chrome issue with an older bbb version I upgraded my server to ubuntu 18 and bbb to 2.4, now I can't connect microphone on any webbrowser.
The echo test waits for several seconds and finally give the error 1006.

bbb-start gives a warning:

```
Warning: Failed to verify STUN server at 172.217.212.127:19302 with command 
 stunclient --mode full --localport 30000 172.217.212.127 19302
```

I disabled the firewall to be sure it's not causing the problem.

**Comment by Entretoize** [comment]
I searched for 172.217.212.127 on my server and it was in /etc/kurento/modules/kurento/WebRtcEndpoint.conf.ini then I changed it to:

```
stunServerAddress=stun.ippi.fr
stunServerPort=3478
```

That removed the warning but the echo test still fails with the same error...

**Comment by Entretoize** [comment]
It works after having installed a turn server following "Install a turn server" in the documentation.
Is it a required step ?

**Comment by lonesomewalker** [comment]
Since you can see that it is working after that: for you, yes.
Network issues can be solved often by this.

**Comment by Entretoize** [comment]
The good anwser was "no" in fact, I reinstalled ubuntu on the same server and now it works without setting up anther turn server...
