### ISSUE TITLE
Uploading a large JPG image can freeze the client

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#14056]
**Describe the bug**
Uploading large JPG image can cause the BigBlueButton client to freeze when loading the image.

**To Reproduce**

Download the large (> 15MB) test image from

  https://www.learningcontainer.com/sample-jpeg-file-download-for-testing/

1. Start a meeting on a 2.4 server
2. Upload the JPG image

**Expected behavior**
The image displays without error.

**Actual behavior**
The client freezes for a few moments

**Screenshots**
![image](https://user-images.githubusercontent.com/290351/148998739-e1671a69-57a5-48af-8e2e-4aca035737eb.png)

**BBB version:**
BigBlueButton 2.4.0

**Comment by Jossef-767** [comment]
Since upgrading to 2.4, receiving reports of presentation conversion issues. PDF conversion. Takes very long time,  Maybe related to Pull requests #11828

**Comment by Jossef-767** [comment]
I'll try to research this a bit more before I open an issue.
For now I changed "_svgConversionTimeout_" from **60** to **6**. And I'll see tomorrow if it speeds up the conversion.
