### ISSUE TITLE
enable or disable learning (analytics) dashboard via greenlight or moodle

### ISSUE THREAD

**Issue by mwuttke** [bigbluebutton/bigbluebutton#14052]
It might be nice to make the learning (analytics) dasboard configurable from greenlight or moodle settings, so a greenlight or moodle admin or a teacher/lecturer/moderator can enable/disable the learning dashboard function via greenlight or moodle for each bbb session.

**Comment by antobinary** [comment]
Thanks for opening the issues directly in Moodle/GreenLight's tracking! I am not sure if there is commonality to discuss so we'll likely be closing this issue and proceed with the individual ones...
