### ISSUE TITLE
Sharing webcams or screens with Firefox 96 are not visible to other users (if mediasoup is used)

### ISSUE THREAD

**Issue by cmosch** [bigbluebutton/bigbluebutton#14066]
**Describe the bug**
Screensharing or shared webcams with Firefox 96 are not visible to other users in a meeting on a server which uses mediasoup. Meanwhile all received media are presented as normal.

**To Reproduce**
1. create a meeting on a mediasoup-enabled server (eg [demo.bigbluebutton.org](https://demo.bigbluebutton.org) works too)
2. join with browser A (Firefox 96) and browser B (any Browser)
3. share webcam or screen with browser A
4. shared webcam or screen is not visible in browser B (in case of sharing a webcam, only a black box with the username in it appears)

**Expected behavior**
Shared webcams or screens are visible in browser B.

**Additional context**
- happens on BBB version 2.4.0 with mediasoup enabled
- tested Firefox 96 on Windows 11 and Arch Linux
- using Firefox 95 works as expected **(!)**
- using Kurento works as expected

**Comment by prlanzarin** [comment]
Yeah, can reproduce.
I remember testing nightly a few weeks ago and don't remember seeing this, but it's definitely a thing now.

Will look into it.

**Comment by prlanzarin** [comment]
Pinpointed the issue. ssrcs from server-side SDP answers aren't being removed when the client stream is sendonly, which is _wrong_ but up until now was silent/harmless.
Seems to trigger a sore spot in Firefox 96 (but I'm in the wrong here).

Will tag a new SFU release then we'll see that it lands in 2.4.1. Will also document an workaround while v2.4.1 doesn't come out.

**Comment by prlanzarin** [comment]
Fix: https://github.com/bigbluebutton/bbb-webrtc-sfu/commit/cd0b87c5b1a36c0434e82c56feb9abf1fba3694a
I've made it as unobtrusive as I could.

Currently testing, the majority of scenarios seems good. Extra hands testing this are welcome. Will tag it later today if everything's good.

The workaround is basically to apply that commit over /usr/local/bigbluebutton/bbb-webrtc-sfu/ then `sudo systemctl restart bbb-webrtc-sfu`.

**Comment by antobinary** [comment]
The fix will ship with BBB 2.4.1

**Comment by Davka** [comment]
I can confirm the fix works.
