### ISSUE TITLE
Chrome dont work micriophone and camera. 1006 Description Protocol

### ISSUE THREAD

**Issue by convictednft** [bigbluebutton/bigbluebutton#14064]
What is the error and how can I fix it?
Is it only in chrome? everything worked, but at some point the camera and microphone stopped working only in chrome. In the debug, it shows to Google that the old protocol is used for transmission and you need to generate a token. token is but in which config bigbluebutton to insert?

Chrome version All version dont work 

![image_2022-01-12_10-24-19](https://user-images.githubusercontent.com/96697594/149069518-992ed969-40d5-4c66-b3a2-e9d19faa11ea.png)

**Comment by PhMemmel** [comment]
The BBB version you are using is far too old. Please upgrade. See #13843
