### ISSUE TITLE
Samsung phone gives ICE errors - unable to trace

### ISSUE THREAD

**Issue by markginter31** [bigbluebutton/bigbluebutton#14068]
Trying to get my students prepared for "virtual" days - everyone can connect except for one student.  His phone does not allow audio/video over either data or wi-fi -- all other student phones/devices work.  Is it possible it is a parental restriction issue?  Has anyone else seen this?

**Comment by prlanzarin** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=1240237

Most probably that Chromium issue. Instruct the student to use Firefox while it isn't fixed.

**Comment by markginter31** [comment]
Thank you!  Will do - and closing.
