### ISSUE TITLE
Unidirectional streaming mode for hq sound, especially music

### ISSUE THREAD

**Issue by felix-wo** [bigbluebutton/bigbluebutton#14061]
*Is your feature request related to a problem? Please describe.*
BBB works great in conference situations, even when multiple participants have their mics open. (That’s what BBB is programmed for.) However, playing music (e.g. as sound examples in an educational situation) is unsatisfying, so say the least. (This is, of course, the price for the good echo cancellation etc., making BBB usable in a conference setup at all.) **For music education or  similar applications it would be a huge improvement to be able to stream audio (music) over BBB in high or, at least, decent quality (picked up from a microphone or even played back).**

*Describe the solution you'd like*
**Having a switch within the BBB session to turn a single user in a special "hq audio streaming mode".** This feature could, once activated, mute all the other participant’s microphones – so echo cancellation, noise gate and so forth wouldn’t be necessary in this mode, and audio could be transported in hq, without the heavy speach oriented EQ in place and without the dropouts due to the agressive noise gate. A somewhat higher (and fixated!) latency would be absolutely tolerable in such a mode, and this would prevent dropouts and shifting in time (which is crucial for music).

*Describe alternatives you've considered*
Tweaking audio of BBB on a general level – but this would ruin the conferencing capabilities, which remain needed.

*Additional context*
Music education is confronted with the need to work online on a broad scale in these days. Playing music together is not possible over all the available conferencing tools due to latencies – and this is therefor *not* the goal of this feature request. However, transmitting audio (music) in a clear and undistorted way – even just unidirectional and whilst all the other users have to be muted – would be a huge, huge achievement! Practicality is crucial here, and being able to switch between standard audio mode (conferencing) and the special "hq music streaming mode" would be a feasible solution. **I’m sure, such a feature would be much appreciated by a huge amount of users, and BBB could address a whole new category of use cases in education.**

Thank you for considering!

**Comment by ffdixon** [comment]
Hi @felix-wo, it's a good suggestion.  There is more work underway to refactor the audio in BigBlueButton 2.5.

> I’m sure, such a feature would be much appreciated by a huge amount of users, and BBB could address a whole new category of use cases in education.

We're building BigBlueButton for online education, and this is one of the use cases that we still have to address.  I can't promise we'll make progress on this in 2.5, but we'll keep this issue in mind as we continue to improve the audio in BigBlueButton.

**Comment by felix-wo** [comment]
Thank you @ffdixon! I’m glad, you like my suggestion.

Maybe, the way, I’m sketching the feature, it’s actually not too hard to implement? I read somewhere, the unterlying codecs are feasible for a wide range of audio shapings, also HQ.

And I guess, you got my point: Instead of trying to improve audio in the classical conferencing setup, you could rather implement an unidirectional HQ mode – and therefor without bad compromises. (I haven’t tested Zoom with it’s "original sound" feature – trying something similar – but once I tried some time ago, I didn’t find it convincing.)

And by the way: Having some flexible settings on the user level to adjust, how aggressive the noise gate and compression works, would make sense even for the normal conferencing mode.

**Comment by hostbbb** [comment]
without using freeswitch,  or opus it is possible to play other higher defined file formats with the external video player interface,  if the browser plays it, it will sync high quality stereo to users speakers...     One thought.  if the format is audio,  dont show a large video UI to user, but a smaller control to show progess and title,  that way existing presentation UI may be able to be used will streaming this hi-def.  drawback of this is the audio doesnt make it into the recordings.

**Comment by felix-wo** [comment]
This synchronized playback on the respective user devices (what actually happens in BBB’s YouTube playback) is a good feature. Though, there are two major drawbacks:
- This doesn’t work with live audio. (For some educational setups this is crucial.)
- The sound streaming has to be included from a public link. It’s not possible to make use of the user management of the LMS controlling BBB to regulate access to the sound example as well.

**Comment by hostbbb** [comment]
Some custom commercial work was done in 2020 2.2 to add a DRM (digital rights management) enhancement to the external player, that used a secure CDN to serve the content.   So only an authenticated html5 client could access and play the content.  Not sure if something like this done in open source branch down the road makes sense.   Also had a content library that was available to presenter to select from a library of content, that the front end portal sent on the create call.     Conceptually good feature but was tightly dependent on single CDN and front end.

**Comment by jacobjune** [comment]
> _Is your feature request related to a problem? Please describe._ BBB works great in conference situations, even when multiple participants have their mics open. (That’s what BBB is programmed for.) However, playing music (e.g. as sound examples in an educational situation) is unsatisfying, so say the least. (This is, of course, the price for the good echo cancellation etc., making BBB usable in a conference setup at all.) **For music education or similar applications it would be a huge improvement to be able to stream audio (music) over BBB in high or, at least, decent quality (picked up from a microphone or even played back).**
> 
> _Describe the solution you'd like_ **Having a switch within the BBB session to turn a single user in a special "hq audio streaming mode".** This feature could, once activated, mute all the other participant’s microphones – so echo cancellation, noise gate and so forth wouldn’t be necessary in this mode, and audio could be transported in hq, without the heavy speach oriented EQ in place and without the dropouts due to the agressive noise gate. A somewhat higher (and fixated!) latency would be absolutely tolerable in such a mode, and this would prevent dropouts and shifting in time (which is crucial for music).
> 
> _Describe alternatives you've considered_ Tweaking audio of BBB on a general level – but this would ruin the conferencing capabilities, which remain needed.
> 
> _Additional context_ Music education is confronted with the need to work online on a broad scale in these days. Playing music together is not possible over all the available conferencing tools due to latencies – and this is therefor _not_ the goal of this feature request. However, transmitting audio (music) in a clear and undistorted way – even just unidirectional and whilst all the other users have to be muted – would be a huge, huge achievement! Practicality is crucial here, and being able to switch between standard audio mode (conferencing) and the special "hq music streaming mode" would be a feasible solution. **I’m sure, such a feature would be much appreciated by a huge amount of users, and BBB could address a whole new category of use cases in education.**
> 
> Thank you for considering!

Hello. Your reply about libresignage is great. Do you do a freelance work? Adding media to ligbresignage is not working now. I can pay you via paypal as freelance work. If you possible to freelance work, Would you mail me at jac.jun.01@gmail.com? Best Regards,
