### ISSUE TITLE
Screenshare state incorrect after presenter disconnect

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#14072]
**Describe the bug**
I have seen two cases where the meeting's screenshare state is incorrect - shows as ongoing screenshare with no option to stop it. I imagine they are closely related if not the same

**To Reproduce**
1. Start a session
2. join as Presenter (moderator) and Viewer (viewer)
3. Presenter starts sharing screen.
4a. Presenter's connection is lost

**Expected behavior**
The screensharing should stop as the expected clearing procedure of presenter leaving a session (after N seconds).

**Actual behavior**
A frozen image is displayed, as if the screenshare is still ongoing even though the userlist only shows Viewer.

Second way to reproduce:
4b. restart bbb-html5* services (`sudo systemctl restart bbb-html5*`) or technically just the backend the meeting is on
The meeting should recover (depending on the .service including  https://github.com/bigbluebutton/bigbluebutton/pull/13527) but nobody will be able to take control of the presentation area because akka-apps(?) has on record that screenshare is on. 

Tested on BBB 2.4.0

**Comment by FreeScholar** [comment]
Confiming and adding:

Bug Occurrence:
    share screen -> window -> brave browser
    - tried to change tab, and the screen seemed to be stuck on the initial tab (unsure if the share was frozen though)
    - was unable to change the screen share
    - another user took presenter and saw an indication "You are now sharing your screen" (which was not true).
    - Other user was able to select "stop sharing your screen"
    - but no one was able to start sharing screen again
    - fixed by ending the meeting and everyone rejoining

**Comment by prlanzarin** [comment]
> Confirming and adding:
> 
> Bug Occurrence: share screen -> window -> brave browser - tried to change tab, and the screen seemed to be stuck on the initial tab (unsure if the share was frozen though) - was unable to change the screen share - another user took presenter and saw an indication "You are now sharing your screen" (which was not true). - Other user was able to select "stop sharing your screen" - but no one was able to start sharing screen again - fixed by ending the meeting and everyone rejoining

Please add the BigBlueButton version.

**Comment by prlanzarin** [comment]
Just confirming that this is not completely fixed.

**Comment by Subdarub** [comment]
I have a user that is experiencing the same kinda problem. I´ll have a troubleshoot Session with him, later today.

Information about the situation:

- Google Chrome
- BigBlueButton 2.4.4
- No Mediasoup
- User seems to have a unstable Internet Connection (Upload)
- Singular Windows or Chrome tabs are being shared

What i could gather for now:

- #14309 Seems to be related
- Mediasoup could be a possible fix (Will try out later today)

**Comment by prlanzarin** [comment]
Two more adjustments for this one:
  - https://github.com/bigbluebutton/bigbluebutton/pull/14509
  - SFU's v2.6.x-release and development branches got adjustments to ungraceful WebSocket termination handling that should also help with this
  
Let's see if it sticks this time.

**Comment by prlanzarin** [comment]
I think this should finally be fixed.
Re-open if necessary.
