### ISSUE TITLE
[2.4.0] Bad typing behavior in poll options

### ISSUE THREAD

**Issue by PhMemmel** [bigbluebutton/bigbluebutton#14098]
**Describe the bug**
Trying to insert text leads to strange "jumping" behavior in the poll options text fields

**To Reproduce**
1. Open poll
2. Click "A / B / C / D"
3. Enter some text in (for example) the A field
4. Use the left arrow key because you want to insert something (or Pos1 to jump to the beginning)
5. Hit space bar -> Cursor jumps to the end if cursor hasn't been at position 0, text field gets completely cleared out if cursor was at position 0

**Expected behavior**
Inserting text should work like everyone's used to

**Actual behavior**
Question gets cleared or some other strange behavior (see steps to reproduce)

**Screenshots**
![grafik](https://user-images.githubusercontent.com/65113153/149533611-f798d7e5-43ba-45f5-8e66-d2e98b726603.png)

After going left with arrow keys:
![grafik](https://user-images.githubusercontent.com/65113153/149533670-b12f077e-9bbf-461c-9109-a445176fdcab.png)
After hitting space bar:
![grafik](https://user-images.githubusercontent.com/65113153/149533734-9376958d-39b3-4654-b6d7-d06f9f3cb14b.png)

After hitting Pos1: 
![grafik](https://user-images.githubusercontent.com/65113153/149534071-fc10e6bb-11da-4f9a-9c36-1396542ecf2b.png)
After hitting space bar:
![grafik](https://user-images.githubusercontent.com/65113153/149534155-7a861c91-ca2f-4bb9-a989-3e1571741e95.png)

**BBB version:**
2.4.0

**Desktop (please complete the following information):**
Latest Chrome

**Additional context**
Doesn't seem to be a problem in the "Write your question" text area or the public chat.

**Comment by PhMemmel** [comment]
I have to clarify: The cursor only jumps to the end when you move the cursor *after* a whitespace and hit space bar

**Comment by PhMemmel** [comment]
I already found the reason, will probably be able to provide a fix. Seems like the both cases are two different kinds of issues

**Comment by antobinary** [comment]
Hi @PhMemmel !
Thank you for spotting this and digging deeper! I can confirm that none of the devs are working on this item at this very moment. Let us know if you're hitting a rock and would like us to join the effort! Thank you again!!
