### ISSUE TITLE
Upgrade to BBB 2.4 layout bugs in Chromium and Firefox

### ISSUE THREAD

**Issue by systems-levigo** [bigbluebutton/bigbluebutton#14094]
**Describe the bug**
After upgrading from BBB 2.3.17 to 2.4.0 there are several layout bugs using Chromium Version 90.0.4430.212 or Firefox 91.4.1esr.

**To Reproduce**
1. Upgrade from BBB 2.3.17 to 2.4.0
2. Open a new meeting 

**Expected behavior**
All buttons are visible and all text variables are filled.

**Actual behavior**
Missing buttons and missing text fields.

**Screenshots**
In Chromium i found this problems:
![audidevice-chromium](https://user-images.githubusercontent.com/55574926/149494286-0d2d1080-eee7-4a4f-a70c-879387ef22ef.png)
![poll-chromium](https://user-images.githubusercontent.com/55574926/149494311-3b0a1448-f941-4d74-8e73-e89a3e9c9572.png)
While screensharing, the shared screen is really small: 
![screenshare-chromium](https://user-images.githubusercontent.com/55574926/149494317-bc4c9136-4325-4b39-89ed-6bd6411d894c.png)
![webcam-share-chromium](https://user-images.githubusercontent.com/55574926/149494324-0041308e-bc86-4e0d-8e6f-89ed85a27940.png)

In Firefox the page is collapsed (full-hd resolution):
![firefox](https://user-images.githubusercontent.com/55574926/149494381-3eb07c25-6304-4934-82ca-eec3b86b5878.png)

**BBB version:**
2.4.0

**Desktop (please complete the following information):**
 - OS: Debian 11 KDE
 - Chromium Version 90.0.4430.212 and Firefox 91.4.1esr

**Comment by prlanzarin** [comment]
You probably need a cache bust. And we probably need to add build numbers to font files, locales and whatever else is static + served by nginx in 2.4 to avoid this kind of stuff (like we do with the static, unbundled JS scripts in the compatibility folder) cc @antobinary

**Comment by antobinary** [comment]
We just started doing this for locales https://github.com/bigbluebutton/bigbluebutton/pull/14085
