### ISSUE TITLE
[2.4] Chat notification updating on promotion/demotion

### ISSUE THREAD

**Issue by pedrobmarin** [bigbluebutton/bigbluebutton#14103]
**Describe the bug**
A promoted/demoted user is being notified about old chat messages on promotion/demotion.

**To Reproduce**
1. Join a moderator and type some messages in the chat
2. Join an attendee and close the chat panel
3. As the moderator, type extra messages at the chat and make sure the attendee gets the notifications
4. As the attendee, open the public chat panel to refresh the notifications and close it again
5. As the moderator, promote/demote the attendee

**Expected behavior**
No extra notifications if there's no new message at the chat.

**Screenshots**
![Peek 2022-01-14 15-59](https://user-images.githubusercontent.com/1778398/149571397-45bfc277-6c16-470b-95c4-e0e436e66480.gif)

**BBB version:**
BigBlueButton Server 2.4 client build: 2473

**Comment by antobinary** [comment]
@KDSBrowne is currently working in the area - in case someone else takes this, please coordinate with KDSBrowne
