### ISSUE TITLE
GDPR compliant cookie selection?

### ISSUE THREAD

**Issue by ZelphirKaltstahl** [bigbluebutton/bigbluebutton#14109]
**Is your feature request related to a problem? Please describe.**

I've finally managed to set up a BBB instance, but now I see, that there is no good GDPR compliant cookie information on the greenlight index page. What I am talking about is the following thing in the footer:

![image](https://user-images.githubusercontent.com/11130348/149642543-33d42541-c3f5-4450-85a3-8e2a22324f80.png)

This makes me wonder, whether I can even host a BBB instance with Greenlight.

**Describe the solution you'd like**

It would be good to have something there, that says "reject non-essential cookies". I think merely having 1 option and that one being "accept" is not GDPR compliant.

**Describe alternatives you've considered**

Perhaps an alternative would be to have a kind of text, that says, that there are only essential cookies? Or have some setting somewhere during the installation, which configures it to use only essential cookies and then not show that text with the accept button at all?

**Additional context**

I am self-hosting a BBB instance, but now I am not sure, where I can actually host it legally. I also don't want to be that kind of person, who only offers their visitors 1 "choice" (basically no choice), which is "accept".

**Comment by defnull** [comment]
GDPR does not require consent for functionally required (e.g. session/login) cookies. Greenlight does not set non-essential cookies. The banner could be removed completely I think.

**Comment by ZelphirKaltstahl** [comment]
@defnull Ah thank you! Didn't know Greenlight was managed separately. Should I copy paste the post, reference it, or will it be moved to the other repository by someone?

**Comment by laserrapt0r** [comment]
Yeah our privacy officer has checked that. There is no need for any cookie information. I've disabled the banner manually by changing the code.

**Comment by ZelphirKaltstahl** [comment]
OK I think I'll just do the same. I think there is some simple HTML page somewhere, correct?

**Comment by prlanzarin** [comment]
Wrong issue tracker. Greenlight repo.
