### ISSUE TITLE
Moving "push layout to all" buttons in order to make this feature more flexible and intuitive

### ISSUE THREAD

**Issue by PavelZ-creator** [bigbluebutton/bigbluebutton#14106]
**Is your feature request related to a problem? Please describe.**
"Push layout to all" is a very useful feature available for moderators. But right now it is located in the Options which makes it slow to use (it now requires 4 clicks to activate it). It also does not fit into the Options section logically (Options serve for local changes yet this one effects everyone).

**Describe the solution you'd like**
Adding dedicated buttons to main screen for switching layouts would make this feature more flexible and intuitive. 

**Describe alternatives you've considered**
Another option is to implement it into "+" button although this would make this option easily accessible for presenter only. It could also be combined with some keyboard shortcuts.

**Comment by ffdixon** [comment]
Yes!  Our plan is to make this more intuitive for the presenter.  Much of the work in 2.4 was to implement the feature itself, with updates to the UI getting pushed into a subsequent release (2.5 or 2.6).

**Comment by PhMemmel** [comment]
When implementing that it would be nice if the moderator could use one specific layout and push **another one** to the viewers.

**Comment by antobinary** [comment]
Closely related (and likely to be revisited as part of BBB) https://github.com/bigbluebutton/bigbluebutton/pull/13924 and https://github.com/bigbluebutton/bigbluebutton/pull/13974
