### ISSUE TITLE
Quick switch between External Video and Presentation

### ISSUE THREAD

**Issue by yayaxueyu2021** [bigbluebutton/bigbluebutton#14107]
Hi there, we use external video in class often and find it a bit annoying to switch between video and the presentatioin (pdf), since the document would reload dagain when we close the video to show the presentation again.  It is especially inconvenient when we ask students to answer questions based on video details, which requires us to switch between video and doc way too often with many reloads and trying to find the previous position again and again, quite time consuming. 

**Describe the solution you'd like**
Can we have a quick swtich option that allows us to show video or doc without loading again? 

Please find the mockup attached; I hope I have made it clear, thanks a lot.
![quick-switch](https://user-images.githubusercontent.com/84652647/149617503-0febb309-ee62-4070-81e6-afadd7a031f1.jpeg)

**Comment by ffdixon** [comment]
Hi @yayaxueyu2021,

This is a good suggestion - and we appreciate the context for the suggestion.  

We need to give some more thought on the user experience, but we like that you tried to design something to get the conversation going.

**Comment by yayaxueyu2021** [comment]
Hi @ffdixon,

I hope I can help more but I'm not a coder nor a designer. I can only apply some very basic PS to show my ideas, as a product manager. Let me what I can do to help, thanks again for this great tool.

**Comment by hiroshisuga** [comment]
I don't really understand the problem (let me know if I misunderstand something). 

In a lecture I often switch between presentation to external video and it's very comfortable. When I close the external video, the presentation automatically appears and the slide position is the same as before I start the external video. I don't do any reload.

However I understand that there is quite a bit of procedure to switch to the external video, namely, push + button -> share external  video -> type the URL -> play video -> push + again to close the video -> select stop sharing the video. I install locally this #9609, together with partially #10588, by which you can start external video just by clicking a button if you write the URL in the slide, and push the X button overlaid on the video to close the get back to the presentation.

**Comment by yayaxueyu2021** [comment]
@hiroshisuga hi, I understand your scenario, but ours is a bit different. This is because the presentation document for our lesson is normally quite large, and we need to zoom in and move quite often in order to show more details to the students. In that case, when you close a video and return to a document, you must zoom in and move again. Imagine that you need to switch between the video and the document five tim
![kb_dcp_be_06_pb_p074](https://user-images.githubusercontent.com/84652647/150276763-62b82c5b-abbc-45be-9a74-d20cae011be2.jpg)
es in a minute, which is quite possible when you need to ask/hint/confirm/ ... in response to a single question from the video content, let alone multiple questions.  Attached is a sample page you can try in a BBB room. Thanks.

**Comment by hiroshisuga** [comment]
Well, usually the zoom rate and the position that you pan the slide will be preserved even after playing the external video. I have confirmed it with a PDF presentation and the jpeg file that you showed above. 
I am not sure if I understand your case completely... would you record the screen and show what you mean by a movie?

**Comment by yayaxueyu2021** [comment]
Hi @hiroshisuga, thanks for your prompt response. Please find the captured video attached. I also find it useful to keep the playing positions between switches. That way we don't need to locate the previous position again when getting back from the doc view. It is especially critical when the net is slow. 

https://user-images.githubusercontent.com/84652647/150299227-bdd504f5-2889-4d91-9dcc-169c58cc2980.mp4

**Comment by hiroshisuga** [comment]
Hi @yayaxueyu2021 , I do understand what you mean, but it does not happen to me...

Could you test it on https://test24.bigbluebutton.org/ and see if it happens also there?

**Comment by yayaxueyu2021** [comment]
Hi @hiroshisuga please find attached another vdieo capture from the test24 site.  We are using the 2.4.0 (build 2380) 

https://user-images.githubusercontent.com/84652647/150315681-741fda87-b79b-416c-aadb-df2877e5b912.mp4

**Comment by hiroshisuga** [comment]
I think I have gotten the problem. Could you confirm that this happens only when you hit "fit to the width" button before sharing a video? I mean, will you have the same problem if you pan the slide shown in portrait mode?
I think it's a bug and need to be fixed.
