### ISSUE TITLE
Moderator not set over API

### ISSUE THREAD

**Issue by misisol** [bigbluebutton/bigbluebutton#14120]
Since version 2.4.1, when we call the join api set with moderator password ( without setting role ), the user still joins as viewer ( non moderator ) in conference.

Create Meeting URL: 
`/bigbluebutton/api/create?name=Meeting+Name&meetingID=0397e903-62a8-3ac9-8f85-9b615967d6cb&attendeePW=cb7e920c&moderatorPW=58b8129b&logoutURL=https://marcocial.com/&record=false&duration=70&webcamsOnlyForModerator=false&muteOnStart=false&allowModsToUnmuteUsers=true&lockSettingsDisablePrivateChat=false&lockSettingsLockOnJoin=true&lockSettingsLockOnJoinConfigurable=true&allowModsToEjectCameras=true&checksum=7e43a833c46766b1fc71a466e007a22eedb7db10`

Join Meeting URL: 
`/bigbluebutton/api/join?fullName=User+1&meetingID=0397e903-62a8-3ac9-8f85-9b615967d6cb&password=58b8129b&userID=123213123&userdata-bbb_listen_only_mode=true&userdata-bbb_force_restore_presentation_on_new_events=true&userdata-bbb_custom_style_url=%3Aroot%7B--loader-bg%3A%23000%3B%7D.overlay--1aTlbi%7Bbackground-color%3A%23000!important%3B%7Dbody%7Bbackground-color%3A%23000!important%3B%7D&checksum=34a8e397f96fd19a5ce7709151313462c5c817fa`

**Comment by antobinary** [comment]
Hi @misisol 

> Since version 2.4.1

Just to clarify - have you tried 2.4.0 or did you upgrade from 2.3?

**Comment by misisol** [comment]
I've install 2.4.1 version on a fresh dedicated server (18.04).
Didn't check 2.4.0 version.
But its working well on 2.3.x version.

**Comment by misisol** [comment]
It's not even working if we set role=MODERATOR over api :

Create Meeting URL :
`/bigbluebutton/api/create?name=Meeting+Name&meetingID=0397e903-62a8-3ac9-8f85-9b615967d6cb&attendeePW=cb7e920c&moderatorPW=58b8129b&logoutURL=https://marcocial.com/&record=false&duration=70&webcamsOnlyForModerator=false&muteOnStart=false&allowModsToUnmuteUsers=true&lockSettingsDisablePrivateChat=false&lockSettingsLockOnJoin=true&lockSettingsLockOnJoinConfigurable=true&allowModsToEjectCameras=true&checksum=acdcd7ae30ae63b2d0e212c61d6cbc150492e4xx`

Join Meeting :
`/bigbluebutton/api/join?fullName=User+1&meetingID=0397e903-62a8-3ac9-8f85-9b615967d6cb&password=58b8129b&userID=123213123&userdata-bbb_listen_only_mode=true&userdata-bbb_force_restore_presentation_on_new_events=true&userdata-bbb_custom_style_url=%3Aroot%7B--loader-bg%3A%23000%3B%7D.overlay--1aTlbi%7Bbackground-color%3A%23000!important%3B%7Dbody%7Bbackground-color%3A%23000!important%3B%7D&role=MODERATOR&checksum=74933e000bae0cb9417cc1fd2936867be24959xx`

**Comment by misisol** [comment]
Checking 2.4.0 version right now, it doesn't have such a problem.

**Comment by antobinary** [comment]
Just for reference

https://docs.bigbluebutton.org/dev/api.html
 
![Screenshot from 2022-01-17 18-51-13](https://user-images.githubusercontent.com/6312397/149848796-9d58ceaf-17b2-44e7-a1b8-6968e44dcc2e.png)


Hmm, I don't spot signigicant relevant changes between 2.4.0 and 2.4.1

**Comment by antobinary** [comment]
Hmm, this worked for me via API MATE https://mconf.github.io/api-mate/

`join?fullName=User+2495603&meetingID=random-8851275&password=ap&redirect=true&role=MODERATOR&checksum=b74ea7a3f9c1e9b3a7f299726bcb15ae83b228a0` 

Are you able to reduce a bit the number of parameters passed and see if a more base case works for you (and then expand back to the fuller params list?

**Comment by misisol** [comment]
Sure.

'/bigbluebutton/api/join?fullName=User+1&meetingID=0397e903-62a8-3ac9-8f85-9b615967d6cb&password=58b8129b&userID=123213123&checksum=5d37d0cb4182f722e5bd4a559e63a8a982f39905'

The problem is that the same URL works for 2.4.0 but not for 2.4.1.

**Comment by misisol** [comment]
After some investigations founded the reason this happened. In settings.yml  user.role_moderator has been set to true so this changed the server behaviour as described.

**Comment by antobinary** [comment]
Thanks for the update! Glad you were able to resolve it!
