### ISSUE TITLE
Auto-stop recordings when the session is closed.

### ISSUE THREAD

**Issue by ranjithrajv** [bigbluebutton/bigbluebutton#14122]
**Describe the bug**
Recording doesn't stop when everyone leaves the room, when forgot to stop recording before closing the meeting.

**To Reproduce**
1. Open a session
2. Start recording
3. Close the room without stopping recording
4. Recording is not visible in download list.

**Expected behavior**
Allow to auto-stop recordings when the session is closed.

**Actual behavior**
 Video can't be downloaded if the recording wasn't stopped before closing the session.

**Additional context**
I couldn't find enough documentation if this can be done with current stable versions, if you know any please share.

**Comment by CherukupalleNaveen** [comment]
I think it should be in such a way that  if 0 users in the room, Recording should automatically get stopped after 2 mins.
