### ISSUE TITLE
Userdata injection for breakout room members is not consistent

### ISSUE THREAD

**Issue by frankemax** [bigbluebutton/bigbluebutton#14139]
**Describe the bug**
Userdata injection for breakout room members is not consistent.

**To Reproduce**
1. Create a session with some userdata (e.g. userdata-bbb_custom_style_url)
1. Create 2 breakout rooms (1,2);
2. **User A** joins the breakout room 1;
3. **User B** joins the breakout room 2;
4. **User C** joins the breakout room 1;
5. **User A** loses his userdata.

**Expected behavior**
Breakout room user does not loses his userdata.

**Actual behavior**
Breakout room user loses his userdata.

**Screenshots**

https://user-images.githubusercontent.com/42683590/150140364-d592eaee-a502-41b1-97b4-94ef8f3602b0.mp4

**BBB version:**
BigBlueButton Server 2.4

**Comment by antobinary** [comment]
@frankemax is this free for grabs?
