### ISSUE TITLE
In breakout room, only the first slide of default presentation is available

### ISSUE THREAD

**Issue by vasylOstrovskyi** [bigbluebutton/bigbluebutton#14135]
**Describe the bug**
In breakout room, only the first slide of default presentation is shown in the list of slides, cannot  move to other slides.

**To Reproduce**
1. Go to demo.bigbluebutton.org
2. Start session for two users, user1 (moderator) and user2 (viewer)
3. Create breakout rooms, room1 and room2, send user2 to room1
4. User2 joins room1, tries to change slides of default presentation (to have clear page for whiteboard), but only the first slide is avalable

**Expected behavior**
Ability to change slides of presentation

**Actual behavior**
Presentation contains only one slide

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser Chrome 97.0.4692.71

**Additional context**
1. If user1 joins room1 and take presenter, the result is the same - only one page
2. if user downloads their own presentation, it is shown correctly with all pages

Regards,
 Vasyl

**Comment by vasylOstrovskyi** [comment]
Update: I made the presentation in the breakout room downloadable, and dowloaded it. It is indeed one-page pdf file.
 Vasyl

**Comment by antobinary** [comment]
This is done by design actually as in real life breakout rooms are typically used to split into teams and "work" on one item (slide).
It is a valid _enhancement_ request to support more flexible transfer of presentation/slides but it's not a _bug_ in the current implementation.

**Comment by vasylOstrovskyi** [comment]
Thank you for an explanation. In my case, the file contains clear pages used for whiteboard, and one page is often not enough for this purpose. This would be indeed a good enhancement.
Regards,
 Vasyl

**Comment by ffdixon** [comment]
We're looking at improving this for the 2.7 where we extend Smart Slides to let you define the breakout rooms within the slides.
