### ISSUE TITLE
[2.4] mirrorOwnWebcam isn't being enforced on video dock

### ISSUE THREAD

**Issue by prlanzarin** [bigbluebutton/bigbluebutton#14130]
**Describe the bug**

Setting `mirrorOwnWebcam: true` or the userdata equivalent mirrors the webcam in the video preview, but not on the actual video dock.

Manually mirroring the webcam in the camera container action dropdown works.

**To Reproduce**

1. Set mirrorOwnWebcam: true
2. Join a meeting, verify that the camera is mirrored in the video preview
3. Share a camera
4. Camera isn't mirrored in the video dock

**Expected behavior**

Camera should be mirrored on all ends.

**Actual behavior**

Camera is only being mirrored on video-preview.

**BBB version:**

BigBlueButton 2.4.1

**Comment by christmart** [comment]
It was working in 2.4.0

**Comment by prlanzarin** [comment]
Yeah.
