### ISSUE TITLE
Enhance layout manager

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#14146]
(copied from @lfzawacki + @Arthurk12 's https://github.com/bigbluebutton/bigbluebutton/pull/13974 with some adjustents based on the comments there)

These changes introduce a few different behaviors into BBB's layout manager:

  * Push layouts are now defined via a boolean variable instead of the 'Push' suffix
  * Layouts can be push via a button nested in the '+' menu (can be disabled via html5 settings.yml)
  * Default layout for the meeting is now set via html5 settings instead of bbb-web bigbluebutton.properties
  * _Default layout for the whole meeting can also be set via metadata (meta_meeting-layout) and on a user basis via userdata (userdata-bbb_change_layout)_  Comment from antobinary - the existing _create_ parameter `meetingLayout` might be sufficient
      * Both userdata and metadata as well as html5 settings accept the following values: CUSTOM_LAYOUT, SMART_LAYOUT, PRESENTATION_FOCUS, VIDEO_FOCUS 
  * Reduce the different number of layout variables in the code and make them follow this order of precedence: user defined, pushed meeting layout, userdata defined, metadata defined, default html5 defined. This is important in order to correctly sync layout between presenters and viewers

These changes should make the layout push easier to understand for users and will help us with future extensions to it.

**Comment by antobinary** [comment]
Targetting BBB 2.6 after talking with @mariogasparoni

**Comment by lfzawacki** [comment]
Already merged
