### ISSUE TITLE
[Feature Request] Move Webcam Feed to the Left of the Screen by Default and Add Emoji Selection to the Footer

### ISSUE THREAD

**Issue by kevinmatthes** [bigbluebutton/bigbluebutton#14156]
**Suggestion 1:**

*Description*.  In summer 2021, BigBlueButton showed the webcam feed on the left-hand side of the presentation by default.  Unfortunately, this feature was removed in a later release.  When it was gone, I noticed that it was very useful in order to have a better usage of the screen size.

*Solution*. Please consider to add this feature again such that the webcam video feed will appear on the left side of the screen by default as it did in summer 2021.

*Alternative*.  Alternatively, users might also choose their preferred position for it in the settings.

**Suggestion 2:**

*Description*.  I very like the "Raise Your Hand" button in the footer of the main screen, underneath the presentation area.  This benefits distraction-free listening to the conference and enables users to still interact using emojis.

*Solution*.  I would like to ask you to add a similar button to the footer for choosing one of the supported emojis except / in addition to "Raise Your Hand" since it has button on its own.

*Additional Context*.  I suggested to add the whole emoji selection to the footer instead of adding certain ones successively in order to avoid future requests ending up in adding all of them to the footer line eventually.  In my opinion, a shortcut to the emoji selection in addition to some default ones having their own buttons would be the best solution.

**Comment by ffdixon** [comment]
There is plans in place to add an emoji bar to the bottom of the BigBlueButton presentation area, making it much easier for users to select.

This is a design (still in development) of what we are planning.

<img width="456" alt="image" src="https://user-images.githubusercontent.com/290351/212567848-2b4cee30-b38d-44c5-abb3-9ab64faa748b.png">
