### ISSUE TITLE
Error 1007 if FullAudioBridge is enabled

### ISSUE THREAD

**Issue by reweb87** [bigbluebutton/bigbluebutton#14157]
**Describe the bug**
Audio connection cannot be established when FullAudioBridge is activated 

The following error is displayed in the console:
_WebRTC: ICE failed, add a STUN server and see about:webrtc for more details_

We created the file "/etc/bigbluebutton/bbb-html5.yml/bbb-html5.yml" and changed the file "/etc/bigbluebutton/bbb-webrtc-sfu/production.yml" as described here:
https://docs.bigbluebutton.org/2.4/new.html#faster-audio-activation-using-fullaudio-bridge-experimental

**Expected behavior**
Faster audio activation using fullaudio bridge without SipJS

**Actual behavior**
If we rename/remove the file "bbb-html5.yml" and restart BBB, the audio connection established through our turn server.

**Desktop (please complete the following information):**
 - Windows 10, Firefox 91.4.1esr (Corporate Firewall)
 - macOS 10.15.7, Firefox 96.0.1 (internet without public IP)

**Comment by ffdixon** [comment]
Recommend reverting back from using full audio bridge in 2.4.  It's still experimental and we should have a better implementation in 2.5.
