### ISSUE TITLE
"restoreOnUpdate=true" conflicts with "Focus on presentation"

### ISSUE THREAD

**Issue by vasylOstrovskyi** [bigbluebutton/bigbluebutton#14168]
**Describe the bug**
If public.presentation.restoreOnUpdate is set to true in bbb-html5.yml, video control buttons do not work when Focus on presentation layout is active and presentation is minimized.

**To Reproduce**
1. Start a session with many video streams (so that pagination is in effect). Select "Focus on presentation" layout. Videos are in the bottom of chat area, pagination works properly
2. Press Minimize presentation button. Videos go to the main area as expected
3. Try to scroll video pages. Nothing happens, next/previous buttons do not work
4. Restore presentation. Videos go back minimized, scrolling pages works again

**Expected behavior**
Scrolling pages of video works in all situations.

**Actual behavior**
See 3.

**BBB version:**
2.4.2

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.4
 - Browser Chrome, FF

Regards,
 Vasyl

**Comment by prlanzarin** [comment]
@vasylOstrovskyi , tried reproducing and couldn't in current v2.4.x-release HEAD, so there might be something missing.

I did: force page size to two, join with a bunch of cameras to activate pagination.
In a session I selected the Focus on presentation layout. Tried switching pages while presentation was on focus: worked. I hid the presentation then tried switching pages again: worked.

Can you give more details on your scenario? 
  - Roughly +/- number of cameras you had shared
  - Console logs
  - Is that reliably reproducible or intermittent for you?
  - Were you using any non-standard features (eg: video pin etc)

**Comment by vasylOstrovskyi** [comment]
@prlanzarin, I did a bit more investigation. In fact, the problem is not related to pagination. If I open my own camera and enter focus on presentation, then minimize presentation, the video moves to the main area, but no buttons are working: neither video menu (Mirror etc), neither fullscreen. 
I started removing one by one all settings in bbb-html5.yml and detected, that the problem is caused by
public.presentation.restoreOnUpdate = true
Removed this, and now all works fine. Probably, the title of this issue must be changed appropriately.

Regards,
 Vasyl

**Comment by prlanzarin** [comment]
>  Removed this, and now all works fine. Probably, the title of this issue must be changed appropriately.

If you can re-name and re-phrase the issue description then, that would be welcome.

I'll try to reproduce that new behavior later today. If it follows up and the issue is updated, I will tag it as accepted.

**Comment by antobinary** [comment]
Somewhat related to https://github.com/bigbluebutton/bigbluebutton/issues/14069
