### ISSUE TITLE
Selection the audio device before establishing an audio connection

### ISSUE THREAD

**Issue by scheff** [bigbluebutton/bigbluebutton#14171]
**Is your feature request related to a problem? Please describe.**
When (re)establishing the audio connection, the default audio device is used without any selection option. If another device should or must be used, it must be selected in a second step.

**Describe the solution you'd like**
BBB should allow selection of the audio device in the dialogue where you choose how to participate in the conference (with microphone, listen only or by phone). 

**Describe alternatives you've considered**
When re-establishing the audio connection, the device could also be selected directly in the BBB function bar. For this, the selection option would also have to be displayed when there is no connection. (At the moment it is only displayed when there is a connection). However, this is only a supplement, not a replacement for the extension proposed above.

**Additional context**
The request was brought to me by a visually impaired person. For them this double selection is an additional hurdle, especially if access to the device still has to be allowed.   (This context switch from BBB to browser and back is in itself difficult to follow by screen readers).

**Comment by ffdixon** [comment]
Thanks for the feedback.  We want to make BigBlueButton usable by visually impaired users (see [accessibility](https://bigbluebutton.org/accessibility/)).  

We plan to do some refactoring of the audio in 2022 and will keep this in mind.

**Comment by scheff** [comment]
It distinguishes you and BBB that so much value is placed on accessibility. Thank you. :-)

**Comment by prlanzarin** [comment]
I think this is addressed by https://github.com/bigbluebutton/bigbluebutton/pull/14736 (and follow-ups) in 2.6.

cc @scheff if so, I'll close this issue as resolved.

**Comment by scheff** [comment]
@prlanzarin : Hi. Yes, #14736 closes this issue. :-) Thank you.
