### ISSUE TITLE
Deactivate the "end meeting" function for all but one user

### ISSUE THREAD

**Issue by steffen-moser** [bigbluebutton/bigbluebutton#14180]
**Is your feature request related to a problem? Please describe.**
For our extra-occupational learners, we provide some whole-day courses where invited teachers with low technical or low videoconferencing-tool experience are giving presentations. Typically, these sessions are accompanied by technical staff. While the teachers know how to interact with the underlying Moodle course and with the presentation itself (and are therefore moderators in the session, e.g. in order to hand the presentation permissions to students), they sometimes leave the session by ending it. All students and the other teachers are then kicked out which annoys us all. 

**Describe the solution you'd like**
As a moderator, I would prefer to have the possibility to take away the "end the session" permissions from the other moderators. 

**Describe alternatives you've considered**
Taking away the moderator permissions from the technically low-experienced teachers would be possible, but this will increase the workload for technical staff. 

**Additional context**
The solution does not have to be secure from a computer-security perspective. So it is completely O.K. that moderators can claim the "I am the one who can end the session permission" explicitly back if they want to. When unattended closures by inexperienced moderators have happened, they've always happened without any bad intentions.

**Comment by antobinary** [comment]
Hi @steffen-moser 

> Taking away the moderator permissions from the technically low-experienced teachers would be possible, but this will increase the workload for technical staff.

What would a non-moderator presenter need that is only available to moderators? I am more tempted to consider making adjustments to allow the current presenter to have control over these, rather than providing more layers of complexity (i.e. viewer -> presenter -> moderator with limited controls -> moderator)
