### ISSUE TITLE
muteOnStart=true has unstable behavior

### ISSUE THREAD

**Issue by misisol** [bigbluebutton/bigbluebutton#14183]
if muteOnStart is set to true and joining session as Moderator, sometimes the microphone of the Moderator gets green at the time the microphone gets connected but no voice get passed to atendees and after 5 seconds it gets red again and after clicking on microphone again the mic get open and the voice passes to atendees. In between ( in that 5 seconds ) clicking on microphone does nothing like its button has turned disabled. This behavior is not permanent but in refreshing the page for 10 times, half of the time this behavior shows up.

This behavior is seen on 2.4.2 and on previous versions 2.4.0, 2.4.1 is not checked.

**Comment by ffdixon** [comment]
I was able to reproduce this - occasionally I could join unmuted, but it got muted again within 5 seconds.   

This might not be a bug, rather, it might be how it's implemented as a failsafe to ensure the user does get muted if the first mute doesn't succeed.  I'll let others chime in who are more familiar with the audio.  @mariogasparoni

**Comment by JeanPluzo** [comment]
Just wanted to chime in. I was also able to reproduce this without the 5-second delay. Mod and user are both muted on entering a meeting. `muteOnStart=false` in `bigbluebutton.properties`. 
Do the different audio settings in `settings.yml` have anything to do with this bug/problem?

**Comment by BrutalBirdie** [comment]
Same I can confirm this as well.

**Comment by prlanzarin** [comment]
> This might not be a bug, rather, it might be how it's implemented as a failsafe to ensure the user does get muted if the first mute doesn't succeed. I'll let others chime in who are more familiar with the audio.

It is a bug. Flagged as accepted.

**Comment by prlanzarin** [comment]
I stopped experiencing this for the last couple of weeks. Might be coincidental so I need 3rd party confirmation on whether this is still an issue on v2.4 latest.

**Comment by ali-alhaidary** [comment]
We did not have this issue, and could not reproduce it, may be because we set this flag as true from the moodle plugin.

**Comment by rob0403** [comment]
I haven't come across this for a while either. I think it might be closed?

**Comment by antobinary** [comment]
Let's reopen (with more details) if this is reproduced on BBB 2.4.7+ or 2.5.x+
