### ISSUE TITLE
Mic Reconnecting loop

### ISSUE THREAD

**Issue by misisol** [bigbluebutton/bigbluebutton#14185]
Sometimes after a while the user mic gets disconnected and reconnected and this happens recursively in an unlimited loop. The user needs to refresh the page to make the mic working again at best or get another session to make it working again.
This is not reproduce able but this happens for some our students since 2.4.0 version up tp 2.4.2. This behavior is also seen by me several times.

**Comment by antonbsa** [comment]
Hey! thanks for reporting this.

I've been doing some tests related to reconnections trying to hit this bug, but I couldn't. Do you have more informations about it? any log or pattern related to this will be very helpful! I will also keep testing some behaviors to see if I can reproduce it

**Comment by antobinary** [comment]
Let's reopen if this is encountered again on BBB 2.4.6+ (latest at this moment)
