### ISSUE TITLE
To show BBB release version number in About window

### ISSUE THREAD

**Issue by klorydryk** [bigbluebutton/bigbluebutton#14195]
Hi,
I wanted to check the version of the BBB deployed by our provider, and see that the only information available is this "client version: 2478".
I would like to find there the release version number, like "v2.4.2". Would it be possible? Thanks.

**Comment by hiroshisuga** [comment]
Agreed. Related to #10451.

**Comment by antobinary** [comment]
Duplicate of https://github.com/bigbluebutton/bigbluebutton/issues/10443 (which is currently tagged to be included in BBB 2.5)
