### ISSUE TITLE
Error in French translation

### ISSUE THREAD

**Issue by pielonet** [bigbluebutton/bigbluebutton#14199]
BBB version : 2.4.2

The following two files contain a string not well written in French :
```
/usr/share/meteor/bundle/programs/web.browser/app/locales/fr.json
/usr/share/meteor/bundle/programs/web.browser.legacy/app/locales/fr.json
```
The following entry :
```
"app.guest.windowTitle": "Salon d'acceuil",
```
should be replaced by (switch "e" and "u"):
```
"app.guest.windowTitle": "Salon d'accueil",
```

NB : I could not find this string in Transifex...

Kind regards,
Thierry

**Comment by antobinary** [comment]
Hi @pielonet 
11 days ago this was changed altogether
![Screenshot from 2022-01-25 09-14-53](https://user-images.githubusercontent.com/6312397/150993461-dd263e41-8913-435a-b8f9-b3cf04f986de.png)

If you'd like, chat with user RGal there who made the change, and who is the only French reviewer currently. Technically I can add you as a reviewer too if you'd like (just need to know your username there) but I hope this is resolved peacefully.

**Comment by pielonet** [comment]
"Salle d'attente" is a better translation indeed !
My transifex login is "pielo"

**Comment by antobinary** [comment]
Glad to hear this is now resolved!
