### ISSUE TITLE
question about api mate

### ISSUE THREAD

**Issue by vahidajorloo** [bigbluebutton/bigbluebutton#14209]
hi
im sorry for asking this question here i didnt know where can i get help about this
im not a developer and i dont know much about api stuff
but i want to know if there is a way to create a meeting by api mate with some parameters like maxparticipants then add this meeting to greenlight ?
all im saying is that i need multiple rooms with different maxparticipant parameter to add in greenlight.
is that possible?

**Comment by PavelZ-creator** [comment]
Hello, you can try to ask here instead https://groups.google.com/g/bigbluebutton-dev
