### ISSUE TITLE
Improve user privacy of Learning Analytics Dashboard

### ISSUE THREAD

**Issue by cburkert** [bigbluebutton/bigbluebutton#14208]
The current implementation of Learning Analytics Dashboards likely is in conflict with privacy regulations like GDPR and might cause compliance issues for operators. In the following, I detail the privacy concerns and provide suggestions, how a more compliant behaviour could look like.

### Privacy Concerns

Learning Analytics Dashboard is enabled by default ([see default property list](https://github.com/bigbluebutton/bigbluebutton/blob/18a357455c9e236c0e6f3cb9c7385df353943dc3/bigbluebutton-web/grails-app/conf/bigbluebutton.properties#L248)). Options to enable/disable the dashboard on a per-room basis (e.g. via the front-end Greenlight) have been requested (issues for [BigBlueButton](https://github.com/bigbluebutton/bigbluebutton/issues/14052) and [Greenlight](https://github.com/bigbluebutton/greenlight/issues/2873)) but do not yet exist. Therefore, the data is collected if necessary or not.

Moreover, participants have no indication that this gathering of statistics is taking place. They are not asked for consent nor have they any option to opt out or view their personal statistics. This behaviour likely violates data protection regulations (like GDPR) as there is no legal basis for collecting, processing, and storing this personal data.
While these statistics might be necessary for some teaching scenarios, this is not an appropriate assumption by default.
But even if lawful, participants have no transparency and controls about the activity recording.

Learning Analytics Dashboard goes beyond just summarizing events in the meeting that any
participant could have observed anyway. Keeping track of all participants' behaviour including accurate time statistics
would be impractical without technical support by the tool. Moreover, with activity score, it derives additional personal data apparently meant to assess participant behaviour.

### Suggested Changes to Behaviour

To improve user privacy we suggest the following changes to BigBlueButton:

1. Learning Analytics Dashboard should be off by default.
2. Participants joining a meetings with activated Learning Analytics Dashboard should be
   notified upon joining and provided the choice to either consent and join or
   cancel joining.
   Additionally, if enabled for the meeting, participants could be given the
   option to opt out from
   providing their activity data for the Learning Analytics Dashboard but still attend.
3. During a meeting, an active Learning Analytics Dashboard should be clearly indicated
   similarly to a running recording.
4. For transparency, participants should be able to view their respective activity data as shown
   on the Learning Analytics Dashboard for moderators.
5. The calculation of _activity score_ should be explained for transparency.

**Comment by N8Fear** [comment]
I'd second that request. The analytics dashboard in its current form is extremely problematic if BBB is used at schools within EU juristiction!
It needs to be much more transparent and there must be a way to disable it easily.

**Comment by ffdixon** [comment]
Thanks @cburkert for the feedback.  Looking forward to chatting with your directly.  

We care about student privacy and want to make sure we're providing the best virtual classroom for the teacher and students while at the same time respecting their privacy.

**Comment by lars-becker** [comment]
> This behaviour likely violates data protection regulations (like GDPR) as there is no legal basis for collecting, processing, and storing this personal data.

Do you have a background in law? Since the advent of GDPR it has become somewhat of a fashion to see GDPR violations where are none.

I think it's likely that one could argue that a teacher has a justified interest since those stats can help while teaching. If there's justified interest it would be perfectly legal. Also the data isn't stored beyond the session.

Nonetheless it might come handy to disable it if the admin wants to do it, but please don't made those changes mandatory. It's a useful tool as it is.

**Comment by FreeScholar** [comment]
Thank you for this great feature, we use it as part of practicing Sociocracy - making sure we encourage people to allow space for others to talk if they have been quiet.  We do let people know about it at meetings.

Allowing a host to enable/disable would be perfect. Analytics should be DEFAULT=OFF  
When turned on, participants should be notified.
