### ISSUE TITLE
2.4.2 - A meeting with that ID does not exist

### ISSUE THREAD

**Issue by CamZie** [bigbluebutton/bigbluebutton#14207]
Hello everyone,

We have upgraded our BBB from version 2.3 to the latest 2.4.2. After the upgrade, we cannot access the existing rooms that we have in Moodle version 3.11 with the error: `Cannot create meeting.`

We noticed that the External MeetingID in BBB has ` [0]` format at the end of every ID, which it did not have before:

```
c69d5b6c7bbd828cc06851a0cb0a9f860c707dd1-1643042566621  Mon Jan 24 17:42:46 CET 2022  X   XXX X          0                                          320068d1dd8509acb012b5c9365eeb212230ec6f-54-12[0]
69461e26984bad73a2be2a04c51d3c8e3879abe9-1643042034529  Mon Jan 24 17:33:54 CET 2022  X   XXX X          0                                          bc0891a88f2f883b35147b1b491bac345feba6f0-109-65[0]
c69d5b6c7bbd828cc06851a0cb0a9f860c707dd1-1643041901990  Mon Jan 24 17:31:41 CET 2022  X   XXX X          0                                          320068d1dd8509acb012b5c9365eeb212230ec6f-54-12[0]

```
This is the error we receive when joining a room through Moodle:

> 2022-01-26T08:56:04.699+01:00 INFO  o.b.api.service.ServiceUtils - Attempting to find meeting with ID 320068d1dd8509acb012b5c9365eeb212230ec6f-54-12[0]
> 2022-01-26T08:56:04.699+01:00 INFO  o.b.api.service.ServiceUtils - Meeting with ID 320068d1dd8509acb012b5c9365eeb212230ec6f-54-12[0] could not be found
> 2022-01-26T08:56:04.699+01:00 INFO  o.b.api.service.ServiceUtils - Provided ID 320068d1dd8509acb012b5c9365eeb212230ec6f-54-12[0] may be an external ID converting to an internal ID
> 2022-01-26T08:56:04.699+01:00 INFO  o.b.api.service.ServiceUtils - Provided ID 320068d1dd8509acb012b5c9365eeb212230ec6f-54-12[0] converted to internal ID f485cf5e9769dac717ac694269305ab4396d6882
> 2022-01-26T08:56:04.699+01:00 INFO  o.b.a.m.v.MeetingExistsValidator - meetingExistsError: No meeting with the given ID 320068d1dd8509acb012b5c9365eeb212230ec6f-54-12[0] could be found
> 2022-01-26T08:56:04.699+01:00 ERROR o.b.web.controllers.ApiController - A meeting with that ID does not exist
> 2022-01-26T08:56:04.700+01:00 DEBUG o.b.web.controllers.ApiController - ApiController#invalid A meeting with that ID does not exist

When we try to convert the ID to internal manually it does not detect it: 
```
sudo bbb-record  --tointernal bc0891a88f2f883b35147b1b491bac345feba6f0-109-65[0]

Internal meeting ids related to the given external meeting id:
-------------------------------------------------------------
-------------------------------------------------------------
```
But when we remove the [0] it works.
```
sudo bbb-record  --tointernal bc0891a88f2f883b35147b1b491bac345feba6f0-109-65

Internal meeting ids related to the given external meeting id:
-------------------------------------------------------------
-------------------------------------------------------------
```
We appreciate any help we can get. Thanks!

**Comment by CamZie** [comment]
This issue is Moodle related and not BBB, therefore I will now close this.

**Comment by Paradiesgestalter** [comment]
Hello CamZie, 
could you solve this issue? How? I have the same problem but couldn't find a solution in Moodle forum...

Some BBB Recordings disappeared in Moodle and bbb-web.log is full of entries like this: 

2023-07-13T10:36:08.485+02:00 INFO  o.b.a.m.v.MeetingExistsValidator - Validating existence of meeting with ID 133b37d2aed4a9faf22de09d8c7c602c183e8814-2-9[0]
2023-07-13T10:36:08.485+02:00 INFO  o.b.api.service.ServiceUtils - Attempting to find meeting with ID 133b37d2aed4a9faf22de09d8c7c602c183e8814-2-9[0]
2023-07-13T10:36:08.485+02:00 INFO  o.b.api.service.ServiceUtils - Meeting with ID 133b37d2aed4a9faf22de09d8c7c602c183e8814-2-9[0] could not be found
2023-07-13T10:36:08.485+02:00 INFO  o.b.api.service.ServiceUtils - Provided ID 133b37d2aed4a9faf22de09d8c7c602c183e8814-2-9[0] may be an external ID converting to an internal ID
2023-07-13T10:36:08.485+02:00 INFO  o.b.api.service.ServiceUtils - Provided ID 133b37d2aed4a9faf22de09d8c7c602c183e8814-2-9[0] converted to internal ID 82cae8b2aa26aa879d477d6e443d9fc4b1b6ea1f
2023-07-13T10:36:08.485+02:00 INFO  o.b.a.m.v.MeetingExistsValidator - meetingExistsError: No meeting with the given ID 133b37d2aed4a9faf22de09d8c7c602c183e8814-2-9[0] could be found
2023-07-13T10:36:08.485+02:00 ERROR o.b.web.controllers.ApiController - A meeting with that ID does not exist
2023-07-13T10:36:08.485+02:00 DEBUG o.b.web.controllers.ApiController - ApiController#invalid A meeting with that ID does not exist

**Comment by ssj365** [comment]
Hi Paradiesgestalter,

You can open a ticket for Moodle bugs here tracker.moodle.org/ (just make sure to set the component to BigBlueButtonBN). Also, more details would be helpful to identify what the problem could be, including :

- BBB plugin version (if you performed an upgrade, what version were you using before, and what did you upgrade to?)
- Moodle version
- steps that can be taken to reproduce the bug

**Comment by CamZie** [comment]
@Paradiesgestalter 

According to your error message, it looks like you encountered the same issue as we had. The problem was an upgrade of a Moodle instsance, which resulted to change the format of the meeting ID that has the `[0]` at the end.

- BEFORE (correct format for BBB): `320068d1dd8509acb012b5c9365eeb212230ec6f-54-12`
- AFTER (wrong format): `320068d1dd8509acb012b5c9365eeb212230ec6f-54-12[0]`

If I remember correctly the user upgraded their installation, which fixes the format issues. Thefore I suggest to upgrade you Moodle instance.

**Comment by samuel-edmund-morgan** [comment]
Same here. Any solutions?

**Comment by Hernandc13** [comment]
> Este problema está relacionado con Moodle y no con BBB, por lo tanto, lo cerraré ahora.

y cual es el problema ???

**Comment by sudanking** [comment]
any solution?
