### ISSUE TITLE
scrollbar increase and decrease size

### ISSUE THREAD

**Issue by bigbluebutton-issue-import** [bigbluebutton/bigbluebutton#1421]
Originally reported on Google Code with ID 666

```
What steps will reproduce the problem? (not sure)
1. join to a meeting
2. chat a while
3.

What is the expected output? What do you see instead?
scrollbar should be uniform, but instead, while holding the scrollbar, it increases
and decreases the size, it seems that it's near when you are in the welcome message

see attachment

Please use labels and text to provide additional information.

```

Reported by `mcmarkos86` on 2010-10-18 19:42:33
- **Blocked on**: #667

<hr>
- _Attachment: 1.png<br>![1.png](https://storage.googleapis.com/google-code-attachments/bigbluebutton/issue-666/comment-0/1.png)_
- _Attachment: 2.png<br>![2.png](https://storage.googleapis.com/google-code-attachments/bigbluebutton/issue-666/comment-0/2.png)_
- _Attachment: 3.png<br>![3.png](https://storage.googleapis.com/google-code-attachments/bigbluebutton/issue-666/comment-0/3.png)_

**Comment by ffdixon** [comment]
Closing this issue as we are moving to an HTML5 client.
