### ISSUE TITLE
Uploaded PDF file missing elements in BBB 2.4.2 

### ISSUE THREAD

**Issue by LukeMcMiller** [bigbluebutton/bigbluebutton#14223]
When you upload an PDF File as presentation, some fonts go missing,
The PDF file was scanned from a book with a canon device and sent directly via E-Mail (no OCR as far as I know) to user.

This happens with almost all documents, that where scanned with this device. So first, I thought, some OCR stuff is going on.
But when I open the pdf in Affinity Designer (vector program but also good for pdf editing) the text blocks are shown as images and not as text.

Original:
![image](https://user-images.githubusercontent.com/98581683/151515242-5a3bb0cb-b360-4210-bbdd-646d05baefc8.png)

Uploaded to BBB
<img width="649" alt="uploaded" src="https://user-images.githubusercontent.com/98581683/151515757-0abff9d6-b49a-47b5-b074-23bdb761890e.PNG">

Interesting: The highlighted letters don't gone missing

I don't know if I'm allowed to upload the original document here, because of copyrights.

**Comment by lonesomewalker** [comment]
Can you save this PDF "as image", means the content will be not searchable, all the slides will be images.
Yes, it will bloat them, but just to be sure about that....

Related to #14420
