### ISSUE TITLE
The first message sent is duplicated

### ISSUE THREAD

**Issue by frankemax** [bigbluebutton/bigbluebutton#14226]
**Describe the bug**
The first message sent in a session is duplicated. 
It is probably related to the duplicate key warning.

**To Reproduce**
1. Join in a newly created session
2. Send a message
3. See the duplicated message

**Expected behavior**
Non-duplicated message
Non-duplicated key value

**Actual behavior**
Duplicated message
Duplicated key value

**Screenshots**

https://user-images.githubusercontent.com/42683590/151589883-6838cecf-b91e-431a-a2c3-6f4b7524ada9.mp4

**BBB version:**
BigBlueButton Server 2.4-rc-1 (2445)
BigBlueButton Server 2.4.1 (2861)

**Comment by antobinary** [comment]
Hi @frankemax 

Are you able to reproduce this consistently [on 2.4.2+]? I have seen this once or twice in the past in the 2.4 alpha-beta stage but not lately.

> BigBlueButton Server 2.4-rc-1 (2445)

Based on the build number I think this was between 2.4.0 and 2.4.1. Please clarify if the build number is incorrect.

Please confirm also that nobody's working on this (from what you know)

**Comment by frankemax** [comment]
Hi @antobinary 

I ended up updating my docker image to a newer version. Currently I am using build 486. But the problem still happens...

> BigBlueButton Server 2.4.1 (2861)

I usually run the application by stopping the akka-apps, bbb-web, bbb-html5 services and running them manually with `./run.sh `and `npm start`.

AFAIK no ones is currently working on this

**Comment by antobinary** [comment]
Dropping the 2.4 milestone. I have not seen this or heard of it in some time. If there's news in the area we can look into it again
