### ISSUE TITLE
Guests can't join the meeting

### ISSUE THREAD

**Issue by GhaziTriki** [bigbluebutton/bigbluebutton#14232]
**Describe the bug**
A user kept trying to access the meeting ...the modertaor saw them request access and let them in but the user did not gain access just still saw waiting for approval. Another user tried three times and same result ...on fourth try he successfully entered the room.

**BBB version:**
BigBlueButton Server 2.4.2

**Comment by antobinary** [comment]
Thanks for reporting! Are you able to reproduce this against https://test24.bigbluebutton.org/demo/demo2.jsp

**Comment by GhaziTriki** [comment]
After investigation this issue happens when too many users are in the same server and nodejs is no more processing requests at the normal pace.
