### ISSUE TITLE
Presentation upload gets stuck sometimes

### ISSUE THREAD

**Issue by trs80** [bigbluebutton/bigbluebutton#14235]
Fresh install of 2.4.2, behind a fresh greenlight frontend. I tested uploading some files for presentations, and perhaps half the time they get stuck and never finish uploading. This sometimes prevents any further files being uploaded at all. I had a look for errors in the logs but couldn't find any - where should I be looking? Seen on Firefox 91.5.0esr on Linux and Edge 96.0.1054.62 on Windows.

![bbb-presentation-upload-fail](https://user-images.githubusercontent.com/111810/151747780-b8c33be9-ade9-420f-9747-79334e37ca9f.png)

**Comment by trs80** [comment]
I had enableMultipleKurentos in my apply-config.sh, I changed it to disableMultipleKurentos and had one failure but it's more reliable since then. The multiple empty files in the list with the shaded background and "Generating thumbnails ..." and "Converting file ..." are still there even when it works.

**Comment by prlanzarin** [comment]
> I had enableMultipleKurentos in my apply-config.sh, I changed it to disableMultipleKurentos and had one failure but it's more reliable since then. 

That's just a coincidence. That option has little to do with presentation processing. Keep it enabled.

Also I'm pretty sure this is a duplicate of https://github.com/bigbluebutton/bigbluebutton/issues/14138?

**Comment by trs80** [comment]
It looks similar, I'll close this one and comment there, sorry for not seeing it when I was searching for existing bugs.
