### ISSUE TITLE
Inconsistent Character Spacing on PDF Presentations

### ISSUE THREAD

**Issue by mcniceye** [bigbluebutton/bigbluebutton#14236]
**Describe the bug**
Chracater spacings are inconsistent on uploaded PDF presentations. PPTX files are OK.

**To Reproduce**
1. Upload [attached PDF](https://github.com/bigbluebutton/bigbluebutton/files/7969235/Example.pdf) presentation.
2. See the character spacings are inconsistent. 

**Expected behavior**
Character spacings are incorrect.

**Actual behavior**
Character spacings must be "as is" in PDF file.

**Screenshots**
![220131113100](https://user-images.githubusercontent.com/93155358/151761807-a308aa9f-e335-4186-a10b-168a3d75eb78.png)

**BBB version:**
BigBlueButton Server 2.4.2 (2885)

**Desktop (please complete the following information):**
 - OS: OS independent.
 - Browser Browser independent.
 - Version Version independent.

**Smartphone (please complete the following information):**
 - Device: Device independent
 - OS: OS independent.
 - Browser Browser independent.
 - Version Version independent.

**Additional context**
[Example.pdf](https://github.com/bigbluebutton/bigbluebutton/files/7969235/Example.pdf)

**Comment by hiroshisuga** [comment]
already answered at https://groups.google.com/g/bigbluebutton-dev/c/w23uSk_3znU .

**Comment by antobinary** [comment]
Let's keep the discussion in https://groups.google.com/g/bigbluebutton-dev/c/w23uSk_3znU and if the solution is different from #13388 , then let's open a new issue for BBB
