### ISSUE TITLE
Improve moderator chat messages emphasizing (live session and recording)

### ISSUE THREAD

**Issue by TiagoJacobs** [bigbluebutton/bigbluebutton#14243]
We recently implemented a way to emphasize moderator messages.

We currently have two limitations in this feature:

1 - If a user is demoted, the messages sent while user was a moderator are de-emphasized.
2 - The recordings are not emphasizing the messages.

**Describe the solution you'd like**
As proposed by @GuiLeme [here](https://github.com/bigbluebutton/bigbluebutton/issues/13547#issuecomment-1026771918), akka will store "per message" the current role of the user (when the message is sent).

This information will be propagated to html5-server and to recording archive (`events.xml`).

**Describe alternatives you've considered**
We considered calculating the "time periods" that the user was moderator, to emphasize message accordingly, however it added complexity to the code and didn't solved the issue with the UI during the meeting.

**Additional context**

This issue is a follow up of https://github.com/bigbluebutton/bigbluebutton/issues/13547.
This issue also makes PR https://github.com/bigbluebutton/bigbluebutton/pull/14227 obsolete.

**Comment by pedrobmarin** [comment]
Playback partial changes https://github.com/bigbluebutton/bbb-playback/pull/163
