### ISSUE TITLE
`defaultMeetingLayout=VIDEO_FOCUS` not applying?

### ISSUE THREAD

**Issue by Commifreak** [bigbluebutton/bigbluebutton#14242]
**Describe the bug**
When set `defaultMeetingLayout` in `/etc/bigbluebutton/bbb-web.properties` to `VIDEO_FOCUS`, the setting wont be applied. The dropdown inside the settings still shows "Automatic" and the layout stays the same (default).
Shouldnt the `defaultMeetingLayout` override this?

Out goal is it to default minimize the default presentation (hide the default presentation is still not configurable :/ )

`bbb-conf --check` reports, correct value: `defaultMeetingLayout: VIDEO_FOCUS` but is not applied somehow.

**To Reproduce**
1. Edit the .propteries to set `defaultMeetingLayout=VIDEO_FOCUS`
2. Restart bbb, start a meeting
3. default presentation and participant webcams shown together
4. Selecting "Video focus" manually brings up the expetced result only

**Expected behavior**
A new meeting starts with VIDEO focussed

**Actual behavior**
A new meeting starts always with the default layout and "Automatic" setting for the layout-drodpown

**Screenshots**
none

**BBB version:**
BigBlueButton continually evolves. Providing the version/build helps us to pinpoint when an issue was introduced.
Example:
$ sudo bbb-conf --check | grep BigBlueButton
BigBlueButton Server 2.4.2 (2890)

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser Firefox
 - Version 96.0.3

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by ramonlsouza** [comment]
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Edit the .propteries to set `defaultMeetingLayout=VIDEO_FOCUS`
> 2. Restart bbb, start a meeting
> 3. default presentation and participant webcams shown together
> 4. Selecting "Video focus" manually brings up the expetced result only

Hello @Commifreak! In step 2, did you restart BBB by running `sudo bbb-conf --restart`? Restarting the bbb-html5 service is not sufficient (it will not update `bbb-web.properties` settings).

**Comment by Commifreak** [comment]
Yes, I did `bbb-conf --restart` in my tests.

**Comment by ramonlsouza** [comment]
Sorry, I could not reproduce the issue... It works as expected when I follow these steps:
1. add `defaultMeetingLayout=VIDEO_FOCUS` to a new line in  `/etc/bigbluebutton/bbb-web.properties`
2. run `bbb-conf --restart`
3. start new meeting

**Comment by Commifreak** [comment]
Let me check that again. Ill send a follow-up tomorrow.

**Comment by Commifreak** [comment]
Good morning,

So, I captured two videos.

The 1st one - with default settings:

https://user-images.githubusercontent.com/87267/152098017-a7b6b910-ca6d-4091-aed1-34656b68372f.mp4

presentation in foreground and video above.

Now changing the setting (`--check` output conformation):

```
defaultMeetingLayout: VIDEO_FOCUS
```

https://user-images.githubusercontent.com/87267/152098155-a989536e-08bb-4607-be3e-26dae0ec2382.mp4

I dont see any difference. Cleared browser cache as well.

**Comment by vasylOstrovskyi** [comment]
Hello all,
It seems that the layout setting is kept somewhere in browser cookie, so after changing defult layout and restarting server you also need to restart browser.
I have PRESENTATION_FOCUS as default. If I start a session and manually change layout to say, smart, then close the session, and start it again (in the same browser tab), I have the smart layout still applied. However, if I open new session in a new tab, or just restart browser, then start a new session, the layout is correctly set to presentation focus.

Regards,
 Vasyl.

**Comment by Commifreak** [comment]
Can confirm what @vasylOstrovskyi said! It is working after restart of the browser!
