### ISSUE TITLE
change processing time

### ISSUE THREAD

**Issue by GeorgyKhairov** [bigbluebutton/bigbluebutton#14258]
Hi,
I'm trying to change processing time as it described here
https://docs.bigbluebutton.org/admin/customize.html#change-processing-time)](https://docs.bigbluebutton.org/admin/customize.html#change-processing-time

If does not affect.

All the meetings processed just after meeting finished.

**Comment by MiStErLu** [comment]
I got the same problem here with version 2.4.2

**Comment by ffdixon** [comment]
Need to re-test this to ensure we have proper documentation on in 2.5/2.6 on changing the processing time.
