### ISSUE TITLE
Error 408 Authentication Timeout with iPad through Forward Proxy

### ISSUE THREAD

**Issue by laserrapt0r** [bigbluebutton/bigbluebutton#14256]
**Describe the bug**
When joining a session with an iPad an error 408 authentication timeout occures when using a forward proxy.

**To Reproduce**
Join a session with an iPad through a forward html proxy 

**Expected behavior**
no error

**Actual behavior**
error 408 authentication timeout occures.

**Screenshots**

**Desktop (please complete the following information):**
with Windows and Chrome, Firefox, Edge no problems

**Smartphone (please complete the following information):**
with Android no problems. 
iPhone was not tested. 
iPad produces the error.

**Additional context**
Happens with 2.3.17 and 2.4.2. 
Was also reproduces with test23.bigbluebutton.org
We are using a company wide proxy for our network traffic. The person who reported the problem said that he also used tried Firefox instead of Safari and it worked the first time using wifi and then had the issue trough 4G network and that had the issue with wifi too. I am kind of helpless because Android and desktop browsers work fine. The problem does not happen when using no proxy (direct connection without turn server). Not using the proxy is not option.
Does anyone have a clue?

**Comment by laserrapt0r** [comment]
Here is what the nginx error log says at that time (client ip and domain was changed):
2022/02/02 11:53:08 [error] 38176#38176: *634 connect() failed (111: Connection refused) while connecting to upstream, client: ippseudonymised.com, server: domainpseudonymised.com, request: "POST /html5client/sockjs/571/m9rjqks_/xhr HTTP/2.0", upstream: "http://127.0.0.1:4106/html5client/sockjs/571/m9rjqks_/xhr", host: "domainpseudonymised.com", referrer: "https://domainpseudonymised.com/html5client/join?sessionToken=o6wt1mxv1sz57wvu"
2022/02/02 11:53:08 [error] 38176#38176: *634 connect() failed (111: Connection refused) while connecting to upstream, client: ippseudonymised.com, server: domainpseudonymised.com, request: "POST /html5client/sockjs/571/m9rjqks_/xhr HTTP/2.0", upstream: "http://127.0.0.1:4107/html5client/sockjs/571/m9rjqks_/xhr", host: "domainpseudonymised.com", referrer: "https://domainpseudonymised.com/html5client/join?sessionToken=o6wt1mxv1sz57wvu"
2022/02/02 11:53:10 [error] 38176#38176: *634 connect() failed (111: Connection refused) while connecting to upstream, client: ippseudonymised.com, server: domainpseudonymised.com, request: "GET /html5client/locale?locale=de-DE&init=true HTTP/2.0", upstream: "http://127.0.0.1:4105/html5client/locale?locale=de-DE&init=true", host: "domainpseudonymised.com", referrer: "https://domainpseudonymised.com/html5client/join?sessionToken=o6wt1mxv1sz57wvu"
2022/02/02 11:53:10 [error] 38176#38176: *634 connect() failed (111: Connection refused) while connecting to upstream, client: ippseudonymised.com, server: domainpseudonymised.com, request: "GET /html5client/locale?locale=de-DE&init=true HTTP/2.0", upstream: "http://127.0.0.1:4104/html5client/locale?locale=de-DE&init=true", host: "domainpseudonymised.com", referrer: "https://domainpseudonymised.com/html5client/join?sessionToken=o6wt1mxv1sz57wvu"
2022/02/02 11:53:14 [error] 38176#38176: *1870 connect() failed (111: Connection refused) while connecting to upstream, client: ippseudonymised.com, server: domainpseudonymised.com, request: "POST /html5client/sockjs/723/0w9ysar3/xhr_send HTTP/2.0", upstream: "http://127.0.0.1:4107/html5client/sockjs/723/0w9ysar3/xhr_send", host: "domainpseudonymised.com", referrer: "https://domainpseudonymised.com/html5client/join?sessionToken=o6wt1mxv1sz57wvu"
2022/02/02 11:53:14 [error] 38176#38176: *1870 connect() failed (111: Connection refused) while connecting to upstream, client: ippseudonymised.com, server: domainpseudonymised.com, request: "POST /html5client/sockjs/723/0w9ysar3/xhr_send HTTP/2.0", upstream: "http://127.0.0.1:4106/html5client/sockjs/723/0w9ysar3/xhr_send", host: "domainpseudonymised.com", referrer: "https://domainpseudonymised.com/html5client/join?sessionToken=o6wt1mxv1sz57wvu"

**Comment by laserrapt0r** [comment]
Okay the messages in the nginx error log are related to https://github.com/bigbluebutton/bigbluebutton/issues/12291 and are not to related to my problem.

**Comment by laserrapt0r** [comment]
https://github.com/react-native-webview/react-native-webview/issues/2281 
Gave me a hint that it is a new experimental features that triggers the issue. 
The feature is called NSURLSession WebSocket. It is enabled by default in iPadOS 15. By disabling it BBB works. 

Is there anything you can change so that it is not necessary to change that option on iPads?

**Comment by liske** [comment]
We've reports about the same issue and after disabling the NSURLSession WebSocket in Safari the connection via proxy is now working.
