### ISSUE TITLE
Few Enhancements for polls

### ISSUE THREAD

**Issue by rmuzzini** [bigbluebutton/bigbluebutton#14250]
Among the big improvements v2.4 gives us, poll module may deserve attention a little more.
### Why
Currently, poll histogram is not quite attractive, all in black.
The new enhancement putting results into chat window is interesting, but sometimes it runs the risk of messing up the chat itself
And, last one, exposing the total number of votes in the graph could be -well- self-defeating, if you only get a few votes.
### How
Here's my proposal to integrate poll options set :
- new live option to assign a color for each poll choice so that we can have more colorful histograms; and maybe a new global option in settings.yml to set the default color
- new live option to hide poll results in the chat window, to free space for messages and to allow the following:
- new live option to hide # of votes in the poll histogram (sometimes it is a small number despite the # of participants and the class gets depressed…)

Attached some visualization of how my proposals could be implemented.
Regards.

![immagine](https://user-images.githubusercontent.com/6996322/152013913-12311802-f9f1-40bd-b89d-17fa28c2ce66.png)
![immagine](https://user-images.githubusercontent.com/6996322/152013943-ca8d3a89-b0f8-4483-872c-cfa475994407.png)

**Comment by greenycat** [comment]
Parrot colors are not good at all. Current design is quite consistent...
