### ISSUE TITLE
Upgrade from 2.3 to 2.4 recordings not processing

### ISSUE THREAD

**Issue by GhaziTriki** [bigbluebutton/bigbluebutton#14287]
**Describe the bug**
After upgrading a server from 2.3 to 2.4 some gems fails to install. The side effect is that recordings are no more processing.

**Installation type**
Installed using bbb-install script.

**Additional context**
Check the attached image. I had to manually delete the 0 byte files then reinstall ` bbb-record-core`. I found some thread talking about it.
I ran the `sudo apt-get install --reinstall bbb-record-core` command in https://github.com/bigbluebutton/bigbluebutton/issues/12627#issuecomment-866638403

Files deleted are
`/var/lib/gems/2.5.0/cache/racc-1.6.0.gem`
`/var/lib/gems/2.5.0/cache/nokogiri-1.12.5-x86_64-linux.gem`
`/var/lib/gems/2.5.0/cache/optimist-3.0.1.gem`
`/var/lib/gems/2.5.0/cache/rake-13.0.6.gem`
`/var/lib/gems/2.5.0/cache/mini_profile2.-2.6.1.gem`

Then I had to go to failed recordings files and create the `.../recorded/*/*.done` file for them

The issue is discussed here: https://groups.google.com/g/bigbluebutton-dev/c/_G_rjBjzWa4/m/_WBQjsOvEQAJ and here https://groups.google.com/g/bigbluebutton-dev/c/MdyjrwAZON4

Check the attached photo for files to delete:
![MobaXterm_iFjXERSpcA](https://user-images.githubusercontent.com/4991088/152634438-658388e7-9d96-4561-99d6-464f74700a5b.png)

**Comment by ashraful19** [comment]
How to solve this issue ? my recordings during live session isnt found in greenlight.
I am facing this after upgrading from `2.4.2` to `2.4.4`

on  `bbb-conf --restart`
i get this,
```
# Potential problems described below
........

#
# Warning: found 'Nil' message in recording processing logs.  Possible GEM errors
#
#  https://github.com/bigbluebutton/bigbluebutton/issues/14287
#
```
this leds to this page. but not finding a solution.
when i try to manually rebuild the recording,
`sudo bbb-record --rebuild <internal_meeting_id>`
i get the following output,
```
Marking for rebuild <internal_meeting_id>
Enqueing sanity worker with {:single_step=>false, :meeting_id=>"<internal_meeting_id>"}
```

but the recording still doesnt show in greenlight recording list.

`bbb-rap-starter.service` and `bbb-rap-resque-worker.service` services are running.

**Comment by ashraful19** [comment]
How to solve this issue ? my recordings during live session isnt found in greenlight.
I am facing this after upgrading from `2.4.2` to `2.4.4`

on  `bbb-conf --restart`
i get this,
```
# Potential problems described below
........

#
# Warning: found 'Nil' message in recording processing logs.  Possible GEM errors
#
#  https://github.com/bigbluebutton/bigbluebutton/issues/14287
#
```
this leds to this page. but not finding a solution.
when i try to manually rebuild the recording,
`sudo bbb-record --rebuild <internal_meeting_id>`
i get the following output,
```
Marking for rebuild <internal_meeting_id>
Enqueing sanity worker with {:single_step=>false, :meeting_id=>"<internal_meeting_id>"}
```

but the recording still doesnt show in greenlight recording list.

`bbb-rap-starter.service` and `bbb-rap-resque-worker.service` services are running.

**Comment by hostbbb** [comment]
look in /var/bigbluebutton/published/presentation/<internal_meeting_id>  to see if the recording is created.   if it is, take the playback link in metadata.xml and see if link works in browser.    The recording may exist, but greenlight just not seeing it

**Comment by ashraful19** [comment]
Hello @hostbbb 
Thanks for your reply. 
The recordings showed in greenlight after an hr without doing anything further.
thanks again.

**Comment by antobinary** [comment]
The process for installing gems was changed significantly on BBB 2.5. Please re-open if an issue like that is encountered again (or use the mailing list https://groups.google.com/g/bigbluebutton-setup if in need of assistance)

There was an improvement made for @GhaziTriki 's case - https://github.com/bigbluebutton/bigbluebutton/pull/14288 
Additionally it looked like Ghazi was able to get around this issue.
