### ISSUE TITLE
Audio support for video stream

### ISSUE THREAD

**Issue by bigbluebutton-issue-import** [bigbluebutton/bigbluebutton#1429]
Originally reported on Google Code with ID 674

```
For the whole story, see http://groups.google.com/group/bigbluebutton-dev/browse_thread/thread/a7e38905d3d045d9/6a39164b438d545d#6a39164b438d545d

Regards,

Arnaud
```

Reported by `ama.aclnr` on 2010-10-22 16:37:10

<hr>
- _Attachment: [VideoconfModule.patch](https://storage.googleapis.com/google-code-attachments/bigbluebutton/issue-674/comment-0/VideoconfModule.patch)_
- _Attachment: [VideoconfModule.swf](https://storage.googleapis.com/google-code-attachments/bigbluebutton/issue-674/comment-0/VideoconfModule.swf)_

**Comment by ffdixon** [comment]
Closing this issue as it is unfocused.
