### ISSUE TITLE
Allow Access screen sharing overlay interferes with Echo Test popup

### ISSUE THREAD

**Issue by passw0rd123** [bigbluebutton/bigbluebutton#14298]
If you join an already started session with a screen sharing session running, you will be prompted by an overlay to allow showing the shared content. This layout interferes with the echo test popup for setting up the audio connection.

**To Reproduce**
1. Establish a session and start a screen sharing session
2. Join this session as another participant
3. You will see the **Allow Access** screen partly overlaying the **Echo Test** popup

**Expected behavior**
Without changing the design the centered echotest UI should always be on top. Otherwise the echotest popup can be designed differently and can be positioned in the top- or bottom-left corner.

**Actual behavior**
The black Allow Access overlay covers half of the echotest popup.

**Screenshots**
![bbb-overlay](https://user-images.githubusercontent.com/16052268/152843056-6417a274-44fc-47b3-b700-e6bc39dfcc7d.jpg)

**BBB version:**
BigBlueButton 2.4.2  
Client build: 2478

**Desktop (please complete the following information):**
 - Browser: Firefox
 - Version 96.0.3 (64-Bit)

**Comment by prlanzarin** [comment]
Thanks for the report, can reproduce.
