### ISSUE TITLE
Recording settings have no local config override file

### ISSUE THREAD

**Issue by danimo** [bigbluebutton/bigbluebutton#14304]
**Describe the bug**
When setting up recording, at least `playback_host` needs to be set. The default `bigbluebutton.example.com` is specified in 
`/usr/local/bigbluebutton/core/scripts/bigbluebutton.yml`. However, overridding the value there will be purged with the next package update.

**Expected behavior**
The value can be set in `/etc/bigbluebutton/recording.yml`. When set, they will take precedence over the defaults specified in the global `bigbluebutton.yml` file.

**Actual behavior**
No such override file is currently respected when parsing the config. The changes must happen in `/usr/local/bigbluebutton/core/scripts/bigbluebutton.yml`.

**Additional context**
In 2.4, we introduced `/etc/bigbluebutton` with the intent that all local config changes will be done there, so that no config changes ever happen outside `/etc`, in particular not in the `/usr` tree.

**Comment by danimo** [comment]
This also applies to `/usr/local/bigbluebutton/core/scripts/presentation.yml` (frequently adjusted to make available .mp4 versions of a given recording).

**Comment by ffdixon** [comment]
Good feedback -- we need corresponding override file(s) in `/etc/bigbluebutton`.

**Comment by antobinary** [comment]
Also let's document the additional override files in the docs: https://docs.bigbluebutton.org/admin/configuration-files.html

**Comment by danimo** [comment]
Addressed in https://github.com/bigbluebutton/bigbluebutton/pull/14628.
