### ISSUE TITLE
Temporary failure resolving 'deb.debian.org'

### ISSUE THREAD

**Issue by uran21** [bigbluebutton/bigbluebutton#14301]
W: Failed to fetch http://deb.debian.org/debian/dists/buster/InRelease  Temporary failure resolving 'deb.debian.org'
W: Failed to fetch http://security.debian.org/debian-security/dists/buster/updates/InRelease  Temporary failure resolving 'security.debian.org'
W: Failed to fetch http://deb.debian.org/debian/dists/buster-updates/InRelease  Temporary failure resolving 'deb.debian.org'
W: Failed to fetch http://deb.debian.org/debian/dists/buster-backports/InRelease  Temporary failure resolving 'deb.debian.org'
W: Some index files failed to download. They have been ignored, or old ones used instead.

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

**Comment by basisbit** [comment]
closing this because
- not an issue of BBB or its infrastructure
- no information on how to reproduce the issue
- no information on what caused this issue
- author did not fill in the template

**Comment by ffdixon** [comment]
Thanks @basisbit.   For the benefit of others, if you want support for installation, the bigbluebutton-setup mailing list is the best place to post.  And before you post, see the information that will make it easier for others to help.    https://docs.bigbluebutton.org/support/getting-help.html#help-installing-or-running-bigbluebutton
