### ISSUE TITLE
Session Freezing by JPEG Upload

### ISSUE THREAD

**Issue by svergata** [bigbluebutton/bigbluebutton#14303]
**Describe the bug**
Possibly crash a Session with Uploading an unmodified JPGE as Presentation.

**To Reproduce**
1. As Moderator upload a JPEG (attached File not modified Iphone8 )
2. Acknowledge the Upload and return to the Meeting Area
3. Wait for Convert and Rendering of the Image 

**Expected behavior**
Image Upload and conversion and presentation working flawless 

**Actual behavior**
Browser Raises "website not responding ..."
The Presetation change to white (not the uploaded Image neither the Previous Presentation)
Other participants browser freezes also or get thrown out of the session

**Screenshots**
Attached Screenshot is the wating page of the Browser

**BBB version:**
Tested on 2.4.2 Build 2478
Tested on test.bigbluebutton.org with build 2497

**Desktop (please complete the following information):**
Own Test done with
 - OS: [Mac]
 - Browser [Chrome]
 - Version [97.0.4692.99 ]

File is 15 MB: [ProblematicImage](https://cloud.h-da.de/s/FP6XaYQbw22iKXf)

![Wait4me](https://user-images.githubusercontent.com/58933250/152962514-678dcee0-4ecb-4e5c-b71e-6b9f9a877351.png)

**Comment by GhaziTriki** [comment]
Hi @svergata is it for any JPEG file or for a specific file that you can share?

**Comment by svergata** [comment]
Hi @GhaziTriki, we didn't change this default value on our systems and I think also the test server of bigbluebutton.org have this setting at the default 2MB.

The Freeze happens on all Servers. A default install of 2.4.2 via bbb-install, the depoyment in test.bigbluebutton.org and on our modified installation also 2.4.2 with other configurations.

The Image does not get scaled even it is bigger than 2 MB!
