### ISSUE TITLE
Removable propertie of presentation is not defined while uploading a document in html5-client.

### ISSUE THREAD

**Issue by GuiLeme** [bigbluebutton/bigbluebutton#14312]
**Describe the bug**
When uploading a presentation via dropdown zone in html5-client, the new document comes with no removable properties, therefore the uploader modal is not going to recognize the property and the trash can icon is not going to render.

**Expected behavior**
By default, the uploaded presentation should have the removable property set with true, so that it would be able to be deleted.

**Screenshots**
![2022-02-09_11-32-14](https://user-images.githubusercontent.com/69865537/153229086-f0ecfaaa-5bd0-4f18-880b-a86ce323879a.gif)

**BBB version:**
BigBlueButton Server 2.5-alpha-1 (67)

**Comment by JoVictorNunes** [comment]
Hi @GuiLeme!
Does it happen with all files or a single file in specific?
