### ISSUE TITLE
Audio becomes stuttery when Airplaying on Mac

### ISSUE THREAD

**Issue by trs80** [bigbluebutton/bigbluebutton#14310]
**Describe the bug**
When a mac laptop is Airplaying to an Apple TV, audio becomes very glitchy - losing about half the audio in perhaps half-seconds blocks.

**To Reproduce**
1. On a Mac, enable Airplay and connect to a BBB meeting.
2. Listen to the audio on another client connected to the same meeting.

**Expected behavior**
Audio comes through cleanly

**Actual behavior**
Audio comes through glitchy with about half of it missing

**Screenshots**
I'll record how it sounds both with and without Airplay active.

**BBB version:**
BigBlueButton Server 2.4.2 (2887)
                    Kernel version: 5.4.0-97-lowlatency

**Desktop (please complete the following information):**
 - OS: Intel running MacOS Big Sur 11.6.2 and M1 running Monterey 12.1
 - Browser: Chrome, Edge, Safari, Firefox
 - Version: Up to date

**Additional context**
I tested on demo.bigbluebutton.org and it had the same problem. I tested Zoom and Teams in both browser and app versions, and no combination had the problem.

**Comment by trs80** [comment]
http://alfirk.ccgs.wa.edu.au/ipad/Bbb%20airplay%20glitching.m4a - starts with Airplay enabled so you can hear the glitching, then it's disabled about 1m54s in and it comes through clearly. No webcams were enabled, just audio and the iPad client that I recorded was in listen-only.

Some random googling suggested that turning off Bluetooth would help, and indeed it does. So it is client dependent, but still odd that Teams/Zoom in the browser don't have that problem.

**Comment by strickes** [comment]
did you find a solution for the problem? I have the same bug while using a MBP with latest MacOS

**Comment by trs80** [comment]
> did you find a solution for the problem? I have the same bug while using a MBP with latest MacOS

No, we've moved to Teams now anyway.
