### ISSUE TITLE
IOS(Apple) video stuck issue on mobile webview(wkwebview)

### ISSUE THREAD

**Issue by AlbinGlobosoft** [bigbluebutton/bigbluebutton#14311]
**Describe the bug**
I think the issue happened after the ios update. The version I am testing is iOS 15.1/15.2.1.
When I joined a meeting it showed my video instead of showing another user video. After I zoom out and went back to the video gallery where we can see all user's videos seemed stuck. It works on the Safari web browser on mobile. The issue was raised after setting it to the web view(WkWebKit) of ios mobile.

**To Reproduce**
1. Join a meeting in ios web view

**Expected behavior**
The videos shouldn't be stuck after joining the meeting or when zoom out.

**Actual behavior**
All videos seemed stuck in the live stream gallery.

**Screenshots**
[https://drive.google.com/file/d/1iRuiKPzi5gYf-87pCeHxDTlsPmIaQf_E/view?usp=sharing](url)

**Smartphone (please complete the following information):**
 - Device: iPhone7 plus
 - OS: iOS 15.1

**Comment by ffdixon** [comment]
Thanks for sharing the video -- we can't tell what version of BigBlueButton is running on the server.  Can you try testing this against our demo server at https://demo.bigbluebutton.org/ and let us know if your able to reproduce the problem there.

We would also recommend updating to the latest version of iOS, which is 15.3.

**Comment by AlbinGlobosoft** [comment]
I tried after updating the iOS to 15.3 and tried with BigBlueButton 2.3 & 2.4 still existing the issue. Any help would be grateful.

Thanks.

**Comment by prlanzarin** [comment]
I don't think non-standard (as in not Apple Store's Chrome/FF) WKWebView endpoints are something we officially support, so yeah, there might bugs. I personally don't have such an environment to debug/validate.
