### ISSUE TITLE
Scheduled Meetings

### ISSUE THREAD

**Issue by ranjithrajv** [bigbluebutton/bigbluebutton#14326]
**Is your feature request related to a problem? Please describe.**
There is no option to communicate to the audience about scheduled time or other details of the upcoming meeting. Current versions only allow to communicate that 'the meeting hasn't started yet'.

**Describe the solution you'd like**
Make the guests wait in guests lobby until the scheduled time, open the room at scheduled time and allow guests in.

**Describe alternatives you've considered**
Couldn't find any alternatives.

**Additional context**
I think this feature will be complimentary to already listed features for v2.5 'Improvements to Guest Lobby: Private guest lobby message, display of waiting time, moving users back to the lobby, display position in waiting line'

**Comment by ffdixon** [comment]
> Scheduled meetings are the responsibility of the front-end (Greenlight, Moodle, ...) 

That's right.

The BigBlueButton server is controlled via the [BigBlueButton API](https://docs.bigbluebutton.org/dev/api.html).  As such, any business logic such as scheduling is controlled by the front-end.
