### ISSUE TITLE
[2.4.3] Audio waiting room join bug

### ISSUE THREAD

**Issue by PhMemmel** [bigbluebutton/bigbluebutton#14323]
**Describe the bug**
Joining with audio on BBB 2.4.3 isn't possible when waiting room is enabled.

**To Reproduce**
1. Open session on test24.bigbluebutton.org with waiting room enabled
2. Join "with microphone"
3. See audio not establishing properly, instead your user appears in the waiting room list.

**Expected behavior**
Normal join procedure with audio.

**Actual behavior**
see steps to reproduce

**BBB version:**
2.4.3

**Desktop (please complete the following information):**
Both latest Chrome and FF on latest Windows

**Additional context**
This bug is pretty devastating (for me), because `bbb-install.sh` downgrade to 2.4.2 doesn't seem to work, so I'm stuck with this one... :-(
EDIT: I managed to downgrade by removing bbb-packages first, so I'm back to 2.4.2 where everything works great :-)

**Comment by dannyplace** [comment]
Same here!

**Comment by mwuttke** [comment]
I can reproduce this issue with latest Chrome and FF on Linux Mint.

**Comment by antobinary** [comment]
I just updated https://test24.bigbluebutton.org/demo/demo3.jsp to contain the "fix" - @prlanzarin 's #14324 

Doing some more testing on it but it would be awesome if someone other than @prlanzarin and me could confirm this resolved.

If all is well, expect 2.4.4 out right away

**Comment by antobinary** [comment]
https://github.com/bigbluebutton/bigbluebutton/releases/tag/v2.4.4 BBB 2.4.4 was released with the fix specified above

**Comment by PhMemmel** [comment]
Just re-upgraded to 2.4.4, can confirm issue was fixed. Thank you very much @prlanzarin @antobinary for the quick reaction.

**Comment by ffdixon** [comment]
Thanks @PhMemmel for letting us know about the issue -- much appreciated!
