### ISSUE TITLE
Sudden change of current documents when ids are identical in the Back-end.

### ISSUE THREAD

**Issue by GuiLeme** [bigbluebutton/bigbluebutton#14321]
**Describe the bug**
When uploading 2 identical presentations (Same name, and same data inside), their `id` end up being equal in the back-end. The result is that, in the front-end, when we click the "manage presentations" button and then simply click on confirm, the server change the current document.

**Expected behavior**
When we click on the confirm button in the `presentationUploader` modal (not changing anything in it) the current document should stay as it is.

**Actual behavior**
The current document changes.

**Screenshots**
![AnyConv com__2022-02-09 16-17-44](https://user-images.githubusercontent.com/69865537/153277645-4fc2b48c-856e-44d9-8251-e62537264d1f.gif)

**BBB version:**
BigBlueButton Server 2.3;
BigBlueButton Server 2.4;
BigBlueButton Server 2.5;

**Comment by TiagoJacobs** [comment]
Multiple parts of BBB code are expecting `presentationId` to be unique.

The easier way to fix it is to satisfy this condition.

I see some ways to achieve this:
1 - Don't allow a user to upload same file twice;
2 - Add a "-2", "-3", ... on end of presentationId when it's received twice;
3 - Use a random `uuid` as presentationId;

Option 1 is not my preferred one as you might want to upload two equal presentations (to have different annotations on each).

So it leads us to option 2 or 3, however, I would like to know what @ritzalam thinks about it.

**Comment by antobinary** [comment]
Great catch!

Let's address this on 2.4 (and propagate the fix on 2.5 next time we pull 2.4 into 2.5).
Thinking about it more, possibly this would be an even simpler approach:

4 - involve the current time as timestamp in the presentation id, possibly the way we create meeting id, etc

**Comment by TiagoJacobs** [comment]
I would like to understand ( maybe from @ritzalam ) if there is a reason why the ID's are generated based on presentation content, if we don't need it, having the UUID is probably the best (and easier) move.

**Comment by ritzalam** [comment]
We only use the filename to generate the id.

https://github.com/bigbluebutton/bigbluebutton/blob/develop/bbb-common-web/src/main/java/org/bigbluebutton/api/Util.java#L46

I just followed how the meetingid was generated. Did not look at other options 15 years ago :)

I can't remember if there is any code dependent on the presentation id format. If none, we can use UUID.

But awhile back @TiagoJacobs you mentioned using the id calculated from presentation file content as a way to "cache" presentations so users doesn't have to re-upload large presentations. Is there still a plan for that?
