### ISSUE TITLE
Simplify API requests - remove the password field

### ISSUE THREAD

**Issue by TiagoJacobs** [bigbluebutton/bigbluebutton#14335]
Some API requests requires the password (`atendeePW` or `moderatorPW`).

In my opinion these passwords are useless.

Let's get as example the `end` meeting request.

To call this endpoint, you need to "sign" it using the checksum.

To generate the checksum, you need to know the salt.

If you know the salt, you can do a `getMeetingInfo` request (and get the password).

So my proposal is:
- `end` - remove the password field (if received we just ignore);
- `join` - make the password field not required if the `role` attribute is provided.
... (review all API endpoints)

**Comment by jfederico** [comment]
When working on this issue, please consider that removing the password parameter will break old integrations. I guess the right way to do it is simply ignore it for end, and on join when role parameter is included (as suggested by Tiago)

**Comment by jfederico** [comment]
We also need to update the documentation
On
https://docs.bigbluebutton.org/dev/api.html#create

attendeePW
(recommended) -> (deprecated)

moderatorPW
(recommended) -> (deprecated)

On
https://docs.bigbluebutton.org/dev/api.html#end

password
(required) -> (deprecated)

On 
https://docs.bigbluebutton.org/dev/api.html#join

password
(required) -> (deprecated)

role
(required)
