### ISSUE TITLE
lockSettingsLockOnJoin: false prevents from general locking being applied

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#14339]
**Describe the bug**
If `lockSettingsLockOnJoin: false`, general locking (i.e. contrary to individual locking via user list menu) will not take effect.

**To Reproduce**
1. Create a new meeting passing `lockSettingsLockOnJoin=false`
2. Join as moderator
3. Join as viewer
4. Lock webcam sharing
5. Try sharing webcam

**Expected behavior**
Viewer will not be able to share webcam and will have 'locked' status in userlist

**Actual behavior**
Viewer will be able to share webcam and will not have 'locked' status in userlist

**BBB version:**
BigBlueButton 2.4.4

**More**
If the moderator locks and unlocks the viewer, next time Webcam gets locked, the lock will affect that user (but will not affect viewers who never got manually locked)

**Comment by ramonlsouza** [comment]
`locked` property in Users collection is currently set when a user joins (based on `lockSettingsLockOnJoin` value) or when a moderator manually unlocks a user from the userlist. So, if `lockSettingsLockOnJoin=false` lock settings will never be applied to the viewers.

For it to work as expected, `locked` property should also be set (by akka-apps) to all viewers present in the meeting when a moderator changes lock settings.

**Comment by GhaziTriki** [comment]
The background of the `lockSettingsLockOnJoin`
Commit: https://github.com/bigbluebutton/bigbluebutton/commit/4fff479e033d5ceadaf665a8f620cef0dd74db96
Old lock settings: https://github.com/bigbluebutton/bigbluebutton/issues/2260#issuecomment-397839460
Feature request: https://github.com/bigbluebutton/bigbluebutton/issues/2655

**Comment by GhaziTriki** [comment]
Having it in the HTML5 client is useful for the following scenario:

- Lock on join is disabled so all teachers with the principal are discussing the course content.
- The teacher stays in the room, all other admin leaves, students are in the guest lobby, teacher enables back lock on join and start accepting the students.

Some laws forbid public chat for primary schools.

**Comment by antobinary** [comment]
Possible duplication of https://github.com/bigbluebutton/bigbluebutton/issues/10986

**Comment by gustavotrott** [comment]
I made some tests in this part, and it seems that the actual behavior is correct.

`lockOnJoin: false` means: don't apply the locks for any user by default. Only apply locks for user that were manually set to "Lock user x"
![image](https://user-images.githubusercontent.com/5660191/160002369-beb2abc4-e62d-446b-9511-e5ad85b873bc.png)


Therefore, only users that moderator manually set to `lock` will have the flag *Locked* and will have the locks applied.
![image](https://user-images.githubusercontent.com/5660191/160002656-aaa959fd-c005-4534-828b-6616431acab7.png)

If you want that all users have the locks applied by default, you should set `lockOnJoin: true`
