### ISSUE TITLE
Support BigBlueButton on Ubuntu 20.04 (or later)

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#14336]
BigBlueButton 2.3, 2.4, 2.5 are installable on Ubuntu 18.04 bionic. Kurento (KMS) does not seem to support later Ubuntu versions. Technically `bionic` has full official support until ~April 2023.

For BigBlueButton 2.6 (or whatever the name of the version after BBB 2.5 is) we would like to use a newer Ubuntu Long Term Support distribution as the default OS.

We're creating this issue to track the progress and to be able to link a few issues which are blocked [to an extent] due to use of `bionic`.

**Comment by etopian** [comment]
How about going to 22.04 as it's the same amount of effort and supports a secure BBB until 2027 rather than 2025.

**Comment by antobinary** [comment]
As of BigBlueButton 2.5-alpha-5 (next in line to be released), we'll be transitioned to use Ubuntu 20.04 for BBB 2.5.x
Implemented in https://github.com/bigbluebutton/bigbluebutton/pull/14600


Regarding 22.04 -- hoping to do the work to transition to 22.04 later this year. The amount of work is not the same, and it was not super trivial to jump to 20.04
