### ISSUE TITLE
enableWebcamSelectorButton not work on phone browser

### ISSUE THREAD

**Issue by jacobkarimi** [bigbluebutton/bigbluebutton#14341]
**Describe the bug**
enableWebcamSelectorButton=false  work just on desktop browser and just on/off camera  but mobile browser show camera settings on try to off cam.
1- enableWebcamSelectorButton=false in settings.yaml and restart bbb
2. join a room on android chrome and a desktop chrome
3. click on camera button
4. click on start sharing
5. click on camera button

**Expected behavior**
expected to disable webcam for client in both windows and android chrome

**Actual behavior**
in desktop chrome camera switching off properly but 
in android chrome showing camera settings

**Screenshots**

**BBB version:**

BigBlueButton Server 2.4.4

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser  :Chrome,firefox
 - Version :98

**Smartphone (please complete the following information):**
 - Device: redmi 6
 - OS: android 11
 - Browser:chrome,brave
 - Version: 98

**Additional context**
when trying to select desktop site  option in android chrome settings , pressing camera button work properly and switching off

**Comment by prlanzarin** [comment]
That's the expected behavior, not a bug. See https://github.com/bigbluebutton/bigbluebutton/pull/13818.

It was the short term compromise to allow users to change backgrounds/cameras on mobile endpoints while not relying on the chevron selector (it's disabled on ALL components, including microphone, because it's too prone to misclick and small to be usable).

**Comment by prlanzarin** [comment]
Actually I'll keep this open for a day or two to see if others want to chime in. Although I believe the webcam button for mobile should not depend on a flag for something it doesn't use at all (enableWebcamSelectorButton) to change its behavior. If anything, there should be a separate flag and that would be an enhancement request.
