### ISSUE TITLE
Big Presenter Webcam as Presentation

### ISSUE THREAD

**Issue by easy-bios** [bigbluebutton/bigbluebutton#14340]
**Is your feature request related to a problem? Please describe.**
We often have presentations without any slides but one speaking person. It is not allways easy to follow and quickly see who is presentation now. Also new BBB Users don't find the pinning of webcams feature.

**Describe the solution you'd like**
It would be nice to have the option to put the presenters webcam inside the big presentation area.

**Comment by prlanzarin** [comment]
>  It would be nice to have the option to put the presenters webcam inside the big presentation area.

But there is? There's a layout mode call `Focus on video` that does that. You also have a toggle which hides/shows the content area in the bottom right.

I don't think this is an issue.

**Comment by easy-bios** [comment]
Let me explain what i mean with a picture:
![Screenshot 2022-02-15 091230](https://user-images.githubusercontent.com/42430994/154027890-1226497c-6462-43b3-a30e-4e8a36c99478.png)

**Comment by easy-bios** [comment]
There it is! :)
https://docs.bigbluebutton.org/new-features/#camera-as-content

Thank you a lot!!! Great work!
