### ISSUE TITLE
Guest users fail to join meeting if there is a network interruption

### ISSUE THREAD

**Issue by schrd** [bigbluebutton/bigbluebutton#14347]
**Describe the bug**

If guests have a network interruption, they won't notice that they are no longer recognized as potential users in BBB when they wait for moderator approval.

We observed this situation during student exams. Exam meetings are configured to use the guest moderator approval. Teachers will check student identity documents one after each other, so it is quite common that students have to wait several minutes before they are approved. If students have a network interruption in this period they'll disappear from the guest list in BBB, however they won't notice that and continue to wait.

**To Reproduce**
1. Start a meeting, set guest policy to ask moderator
2. in a second browser or private tab join as guest
3. in the guest browser open developer tools, set a breakpoint in the javascript function `fetchGuestWait` so the guest will not make any further requests
4. In the moderator browser wait until the guest user disappears
5. now remove the breakpoint in the guest browser
6. wait for more `guestWait` API calls to complete
7. inspect the API response. API still says "wait" instead of signalling that the user has been removed

**Expected behavior**

Guest should know that they don't have to wait any longer. So the API should signal that to the browser and the guest wait page should handle this approriately.

**BigBlueButton version**
we observed this with 2.4.2, but we can reproduce this with 2.4.4 as well. I was able to reproduce this on https://test24.bigbluebutton.org using demo3.jsp as well.

I don't know if this is the same bug as in #14290 and #14232 so I opened this one.

**Comment by antobinary** [comment]
Thanks for reporting!

I believe this is the same scenario @GhaziTriki reported and @Tainan404 worked on last week. I'll let @Tainan404 comment whether the issue should be fully resolved via https://github.com/bigbluebutton/bigbluebutton/pull/14334 and whether the remaining issues need to be reorganized in any way

**Comment by schrd** [comment]
I built packages with the patch from PR #14334 applied on top of 2.4.4 and could no longer reproduce this scenario

**Comment by antobinary** [comment]
Merged #14334 , closing this issue. Thank you for your test @schrd ! :rocket:
