### ISSUE TITLE
Learning Dashboard still counts webcam time when user leaves the meeting

### ISSUE THREAD

**Issue by mokazemi** [bigbluebutton/bigbluebutton#14358]
**Describe the bug**
When a user leaves the meeting with webcam turned on, learning dashboard still counts the webcam time, though the user is offline.  

**To Reproduce**
1. Keep your webcam turned on
2. Leave the meeting
3. Go to learning dashboard, without ending the meeting
4. See the webcam time still increases

**What happens**
The webcam time of that user still increases

**Additional context**
BigBlueButton Server 2.4.2 (2890)

**Comment by gustavotrott** [comment]
Hey @mokazemi,

The Learning Dashboard may take 20 seconds to receive the updated data.
So, during this interval the webcam time can be out of date and it will be fixed as soon as the new data arrive.

Can you check if the webcam time was corrected after some seconds?

Take a look in the example.. the Dashboard increases time to 1:09.. but when it is updated the time is corrected to 1:07 and then stop increasing.

![webcam-increasing](https://user-images.githubusercontent.com/5660191/157684224-f67a2646-5c59-4ffa-b8ab-6a0582419344.gif)
