### ISSUE TITLE
Store Recording Information in a Database and Add Support for Pagination in the Recording API

### ISSUE THREAD

**Issue by paultrudel** [bigbluebutton/bigbluebutton#14350]
**Is your feature request related to a problem? Please describe.**
Currently recording information is stored in xml files. It would be potentially beneficial to instead store this information in a database to allow for more efficient search and retrieval. Additionally, to improve user experience when working with recordings, support for pagination in the recording API would also be ideal.

**Describe the solution you'd like**
Design a database to store recordings, create a second recording service in bbb-common-web to interact with this database, and add support for pagination, through the introduction of new request parameters, to the recording API.

**Additional context**
This PR #13767 proposes a database design as well as an application which parses recording metadata to store in the database.

**Comment by defnull** [comment]
Nothing against storing this data *also* in a database. Redis is already installed on all BBB nodes. But please keep in mind that databases may break and migrations are tricky. There should always be a way to re-index some or all existing recordings from disk if necessary.

**Comment by antobinary** [comment]
Discussing the timeline for this project and it looks like BBB 2.5 is too soon Targeting 2.6 now
