### ISSUE TITLE
Occasional NPE on invoking create API on bbb-web

### ISSUE THREAD

**Issue by ravi-ct** [bigbluebutton/bigbluebutton#14363]
**Describe the bug**

This is on BigBlueButton Server 2.3.15 (2482)

In a day, among the 50000 to 100000 meetings that are created by our front-end on our BBB servers, 2 to 3 meeting creates fail with the following error:
```
022-02-15T09:56:15.920+05:30 ERROR o.g.w.e.GrailsExceptionResolver - NullPointerException occurred when processing request: [GET] /bigbluebutton/api/create
Stacktrace follows:
java.lang.NullPointerException: null
	at org.bigbluebutton.api.HTML5LoadBalancingService.listItemWithIdExists(HTML5LoadBalancingService.java:73)
	at org.bigbluebutton.api.HTML5LoadBalancingService.findSuitableHTML5ProcessByRoundRobin(HTML5LoadBalancingService.java:89)
	at org.bigbluebutton.web.controllers.ApiController$_closure3.doCall(ApiController.groovy:154)
	at org.grails.core.DefaultGrailsControllerClass$MethodHandleInvoker.invoke(DefaultGrailsControllerClass.java:223)
	at org.grails.core.DefaultGrailsControllerClass.invoke(DefaultGrailsControllerClass.java:188)
	at org.grails.web.mapping.mvc.UrlMappingsInfoHandlerAdapter.handle(UrlMappingsInfoHandlerAdapter.groovy:90)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
	at org.springframework.boot.web.filter.ApplicationContextHeaderFilter.doFilterInternal(ApplicationContextHeaderFilter.java:55)
	at org.grails.web.servlet.mvc.GrailsWebRequestFilter.doFilterInternal(GrailsWebRequestFilter.java:77)
	at org.grails.web.filters.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:67)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
We have always found the html5 backends/frontends being active and running fine at the time of the error. Surprisingly a subsequent create call to the same server succeeds without any issue.
```
$ sudo bbb-conf --status
nginx —————————————————► [✔ - active]
freeswitch ————————————► [✔ - active]
redis-server ——————————► [✔ - active]
bbb-apps-akka —————————► [✔ - active]
bbb-fsesl-akka ————————► [✔ - active]
mongod ————————————————► [✔ - active]
bbb-html5 —————————————► [✔ - active]
bbb-webrtc-sfu ————————► [✔ - active]
kurento-media-server ——► [✔ - active]
kurento-media-server-8888  [✔ - active]
kurento-media-server-8889  [✔ - active]
kurento-media-server-8890  [✔ - active]
bbb-html5-backend@1 ———► [✔ - active]
bbb-html5-backend@2 ———► [✔ - active]
bbb-html5-frontend@1 ——► [✔ - active]
bbb-html5-frontend@2 ——► [✔ - active]
etherpad ——————————————► [✔ - active]
bbb-web ———————————————► [✔ - active]
```
**To Reproduce**
It is sporadic and happens on a different server each time

**Expected behavior**
Create API should not fail even when the bbb-html5 instances are running fine

**Actual behavior**
Fails rarely with an NPE

**Screenshots**
Not Applicable

**Desktop (please complete the following information):**
Not Applicable

**Smartphone (please complete the following information):**
Not Applicable

**Additional context**
This is on BigBlueButton Server 2.3.15 (2482)

**Comment by hostbbb** [comment]
Can you find the actual create call in nginx log that failed...  then try and see if that call fails again when you manually try it?    Maybe some malformed data in params causes thix

**Comment by ravi-ct** [comment]
Yes, we have done that. It succeeded fine:
```
<response>
<returncode>SUCCESS</returncode>
<meetingID>639d85bf-7f09-46fe-a158-667f3e38a520</meetingID>
<internalMeetingID>6bcccd84d36ed50877b4b365ffa6fe05f8e8747e-1644921341234</internalMeetingID>
<parentMeetingID>bbb-none</parentMeetingID>
<attendeePW>1socc7edj</attendeePW>
<moderatorPW>38aaakoij</moderatorPW>
<createTime>1644921341234</createTime>
<voiceBridge>557693929</voiceBridge>
<dialNumber>613-555-1234</dialNumber>
<createDate>Tue Feb 15 16:05:41 IST 2022</createDate>
<hasUserJoined>false</hasUserJoined>
<duration>720</duration>
<hasBeenForciblyEnded>false</hasBeenForciblyEnded>
<messageKey></messageKey>
<message></message>
</response>
```

**Comment by hostbbb** [comment]
In a day, among the 50000 to 100000 meetings?

do you have a loadbalancer?   thats a lot of meetings,  when it throws an exception on a bbb server, how many meetings are running, and whats the cpu/ram on the box.

Also make sure your not calling getRecordings with a blank meetingid in some other part of your application, as this will lock bbb-web and consume all resources if you have 1000's of recordings.

**Comment by ravi-ct** [comment]
Yes, we operate a very large farm of servers across multiple regions. The only APIs our frontend invokes are create, join and end. So the concern you raise about getRecordings is not an issue here.

When the exception was thrown today (as reported in the opening post), there were 12 meetings, each with 2-5 participants.

As to the CPU/RAM utilization on the box, we have done the preliminary analysis every single time we encounter these failures. As stated in the issue, subsequent meeting create requests succeed just fine. The resource usage on the box at the time the failure happens are very much within normal parameters ~15% usage (12 cores), about 6 GB usage (out of 64 GB RAM).

**Comment by ravi-ct** [comment]
None of the methods in `HTML5LoadBalancingService` appear to be thread safe. If this object were to be used as a singleton by the grails app (I didn't check there yet), then the state management inside the class definitely is not safe. Just wondering if this may be the cause.

**Comment by hostbbb** [comment]
thats good, bbb-web still runs, so you can at least code your front end to try again and catch the error if no valid success response happens.  since everyone is fielding 2.4 and 2.5 is under development, would be interested to see if this same issue still exists since your on 2.3  i imagine creating a stress script to create meetings may be able to emulate,  the issue is I think the create call triggers the conversion of default presentations, in the past if you thru 100 creates at a server it would peg to 100% converting everything.   not sure about this now...     good luck

**Comment by ravi-ct** [comment]
Well, I don't see any changes in `HTML5LoadBalancingService` in v2.4.x-release or v2.5.x-release branches. If my suspicion about the lack of thread safety being the cause is correct, this issue likely remains. For now, unless there is some other guidance from the authors, we will go ahead and patch the class to implement it in a more thread-safe way for our needs.

When an API request fails with a HTTP 500, personally I would not retry automatically without understanding the cause.

**Comment by hostbbb** [comment]
Sounds like you have the skills to triage and fix :)  I launch 900 meetings at the top of the hour max. And have not seen it.. let us know what you find.   What config do you use for number of front and back end html5 processes

**Comment by ffdixon** [comment]
Is it an option to upgrade to 2.5.x and see if that issue still occurs?

**Comment by GuiLeme** [comment]
Hey guys.
> we will go ahead and patch the class to implement it in a more thread-safe way for our needs.

Did you manage to do this? Did the error appeared again?  c.c.: @ravi-ct

**Comment by GuiLeme** [comment]
It is worth mentioning:

I was trying to reproduce the error, and in 2.3 bbb version, I faced this exception `ConcurrentModificationException`, with some quite similar logs around it (similar to the `NPE` mentioned).

Despite that, I wasn't able to find anything in bbb26 version, which could lead us to believe that the error was corrected by accident or it is just well masked.

So, for future investigations (if needed), the script I used to reproduce the  `ConcurrentModificationException` in **bbb version 2.3** was this one:

```bash
#!/bin/bash
set -e

# Replace here with your credentials:
sharedSecret="1ErLA4TnUht5sVZPXTKUy43D1Bwkl8OaZGYSedxxo1o"

# Here, you have the /api, which is not in the link made by `bbb-conf --salt`
BASE_URL="https://bbb26.bbbvm.imdt.com.br/bigbluebutton/api"

create_meeting(){
    n=$1
    for counter in $(seq 1 $n); do

        meetingID="Teste$counter"
        voiceBridge="123$counter"

        CREATE_ENDPOINT="create"
        query_arguments="allowStartStopRecording=true&attendeePW=ap&autoStartRecording=false&meetingID=$meetingID&moderatorPW=mp&name=$meetingID&record=false&voiceBridge=$voiceBridge&welcome=ola"

        checksum=$( printf "$CREATE_ENDPOINT$query_arguments$sharedSecret" | sha1sum | sed 's/  -//g' )

        endpoint_complete="$CREATE_ENDPOINT?$query_arguments&checksum=$checksum"

        URL="$BASE_URL/$endpoint_complete"
        list_create="$list_create $URL"

    done

    
    echo "------------------------"
    echo 
    echo

    echo "$list_create" | sed -e 's/ /\n/g' | xargs -n 1 -P 10 -I ___ curl "___" 
    
}

create_meeting $1


```

The number of meetings it will create can be set by calling `create_meetings.sh 100` for creating 100 meetings, for instance (if one names the script with create_meetings.sh).
