### ISSUE TITLE
User using microphone lose all audio actions

### ISSUE THREAD

**Issue by GhaziTriki** [bigbluebutton/bigbluebutton#14373]
**Describe the bug**
User with a connection loss and already connected the the audio conference loses the ability to mute/unmute audio conference.

**Expected behavior**
User should be able to use audio conference action after the automatic reconnection.

**Actual behavior**
The talking indicator is not displayed but in the users list we can see the user highlight speaking effect, but no small mic icon.

**Screenshots**

**BBB version:**
BigBlueButton Server 2.4.4

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Edge

**Additional context**
When you click on leave conference it reload the audio prompt is open, then goes through echo test.
Internal meeting ID reference is `66e32e7ee7866f8d6a886bcdc98985061de28215-1645001740227`

**Comment by ffdixon** [comment]
I wonder if this is any better in 2.6?
