### ISSUE TITLE
"Waiting for a presentation to be uploaded" message is always displayed on smart layout

### ISSUE THREAD

**Issue by halilb** [bigbluebutton/bigbluebutton#14376]
**Describe the bug**
We'd like to let our users upload presentations as they wish but it's not required. They may use the platform as a video conferencing tool without sharing any presentations, too.

We recently upgraded from BBB `2.3` to `2.4` and started experiencing this new behavior. This message is taking the whole screen even for video conferences with 10 participants.

**To Reproduce**
1. Go to https://demo.bigbluebutton.org
2. Create a new room with default settings
3. Join the meeting with camera(single and multiple people both should work)
4. Video streams will be minimized and you'll see a big "waiting for a presentation to be uploaded" message.

**Expected behavior**
BBB should focus on video streams and hide "waiting for a presentation to be uploaded" message on smart layout.

**Actual behavior**
"waiting for a presentation to be uploaded" takes the whole screen until a presentation is uploaded or a screen share is started on the smart layout.

**Screenshots**

<img width="1490" alt="Screen Shot 2022-02-16 at 16 26 37" src="https://user-images.githubusercontent.com/2227041/154274730-48dba702-16a8-4a7e-a16f-7b36117710b6.png">

**BBB version:**
BigBlueButton Server 2.4.2

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser Firefox, Chrome
 - Version Latest available

**Comment by felipe-sv** [comment]
I have the same problem
![image](https://user-images.githubusercontent.com/68794093/154912430-bbbb9149-d31e-4a18-9138-723b213dd98e.png)

**Comment by GitHorst** [comment]
To make the point even clearer: The presenter can delete the current presentation. They would do so b/c the presentation is not relevant anymore and people would rather like to talk "more directly" to each other. "No, we are not waiting for a presentation to be uploaded!" ;)
Thanks & keep up the great work!

**Comment by antobinary** [comment]
Thanks for reporting!

We should probably do two things:
- reword the label to "There is no currently active presentation" or something like it
- in Smart Layout treat this case as a minimized presentation area. If a presentation happens to be set as current (possibly a new upload), the layout should adjust again to whatever Smart Layout is deemed relevant.

**Comment by GitHorst** [comment]
This issue actually persists if there was a presentation uploaded which is then deleted. Everybody who was in the room when the presentation was still present, will see the huge "waiting for..." placeholder.

why don't you get rid of it altogether (and irrespective of the layout)? I cannot think of any situation where this message, and especially the huge empty area would by of any benefit.

to reproduce: start conference, upload a presentation, select smart layout (push layout to all), delete presentation --> placeholder will appear for you and everybody who was in the room until deletion. then let somebody else join --> they will see only the cameras (as intended).
