### ISSUE TITLE
Obtain consent before entering a record=true session

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#14381]
**Is your feature request related to a problem? Please describe.**
In certain use cases the institution operating BigBlueButton wants to ensure consent is given prior to joining a recordable session. (This can be in addition to a more generic consent form served by the Front End (LMS?))

**Describe the solution you'd like**
If meeting is _recordable_ (i.e. `record=true` on CREATE) (existing parameter)
and we pass `consentOnJoin=true` on CREATE (new non-required parameter) (or if `consentOnJoin=true` in bigbluebutton.properties or `/etc/bigbluebutton/bbb-web.properties)  (( notice that one `true` in the chain is sufficient to trigger this)),
we display this new page **prior** to loading the client, in simiar fashion to `guest-wait.html`.

[ Question1: are we allow to send a log to the server (if the log to server is enabled) that user with `sessionToken=xxxxx` got to this page? ]

If the user hits 'Continue', we proceed to guest-wait (if needed) and to the session join.

If the user hits 'Leave Session', we redirect to `logoutURL`.
[ Question2: are we allow to send a log to the server (if the log to server is enabled) that user with `sessionToken=xxxxx` chose to leave at this point? This touches on attendance (if applicable) ]

[Question3: is redirection to logoutURL applicable here? Or do we try go back to LMS ... or just display "consent is needed to go further"?] 

![Screenshot from 2022-02-16 11-01-29](https://user-images.githubusercontent.com/6312397/154306018-aeddc87a-0b51-479f-ac98-f21871c99fb2.png)

**Describe alternatives you've considered**
The discussion in #14077 made it clear that this type of consent needs to be given prior to displaying any portion of the session, prior to media negotiation, etc.

**Additional context**

Above I have included a few questions (considerations) that I don't know the answer of. I'm hoping we clear things like these up before diving too deeply into the implementation.
In terms of the logs -- on my (non GDPR compatible) system I would be able to parse nginx logs to see whether the user got to the page. Logs would just make it easier for the administrator to answer support tickets like "users with id 123 and 456 never attended. When approached they say they hit an error. Did they ever attempted to join, did they really hit an error?" 

The assumption here is that a user can either consent fully and procceed OR not consent and is stuck.

**Comment by antobinary** [comment]
Additional items (list in progress):

* this parameter could be carried forward to breakouts, but the consent is already given. No need to re-prompt for breakouts.
* do we need to add settings.yml properties for this

**Comment by defnull** [comment]
This should better be handled in the front-end I think. Greenlight already asks users for consent before they enter a record=true meeting.

As a side node: Consent must be voluntarily according to GDPR, and users also must be able to revoke consent at any time. The proposed solution does not reflect that. Locking out users that do not consent would effectively render any given consent useless.

We dodged that problem by slightly changing the consent question in Greenlight: We actually do not ask for consent, but simply inform the user that activating webcam or microphone or participating in chat results in being recorded. Consent is given implicitly by (voluntarily) participating in a meeting, and can be revoked any time by stopping participation. Consent cannot be revoked retrospectively, but that's fine with GDPR.

The important part here is that now we can prove that the user made an informed decision and actively requested to be included in the recording. This allows us (the service provider) to do whatever it takes to fulfill this request, including storage and further processing of recorded data. This approach also allows teacher ti interactively ask for consent (e.g. for publication) or include additional legal instructions or information in their slides for the user to read before participating.
