### ISSUE TITLE
Notify (remind) that recording is now on (in recorable session)

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#14382]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

Introduce a new non-required CREATE parameter `remindRecordingIsOn` (default value = false)
If `remindRecordingIsOn=true` in CREATE, or in bigbluebutton.properties , or in /etc/bigbluebutton/bbb-web.properties (note that one `true` in the chain is sufficient to enable this)

If `remindRecordingIsOn=true`
* display the recording indicator in a way that is much more difficult to miss, see screenshot below

* Display the following modal at **any** point the recording is ON. This can be on user joining of session (including right after consent is granted via #14381 ), on recording toggled off->on.

* Ensure accessibility is maintained and screen reader catches the modal and handles it correctly. If needed, an additional alert might be included. (Would it sound if on different tab in browser?)

Note -- this is not replacing a consent obtain form. It would be out of scope to try to silence user produced audio or webcam until the user hits Continue. 
"Continue" just closes the modal, nothing more.
"Leave Session" should act as the existing three-dot menu -> Leave

![Screenshot from 2022-02-16 11-36-31](https://user-images.githubusercontent.com/6312397/154312664-30ec9728-820b-44c5-b7c8-0344fa60b492.png)

**Describe alternatives you've considered**
The goal here is to make it extremely clear that the recording is currently enabled, capturing what's going on. This is requested only in some cases, it is not a replacement for #14381 (the comments in #14077 clearly indicate it is too late to capture consent here), so we're only talking about a **reminder**

**Additional context**

Possible parameter rephrasing to be `notify` rather than `remind`?

**Comment by antobinary** [comment]
Let's try to reuse any code change (cherry-pick) from #14177 as applicable

**Comment by gustavotrott** [comment]
> * do we need to add settings.yml properties for this

Hey @antobinary, we have the exactly same configuration in `settings.yml`, `bigbluebutton.properties` and also `/create`.
this multiple places could cause a mess when user wants to disable or enable it.

why do you think it is necessary on `settings.yml`?

**Comment by gustavotrott** [comment]
I feel that way too!
