### ISSUE TITLE
Can't play recorded lesson (at least on iOS)

### ISSUE THREAD

**Issue by greenycat** [bigbluebutton/bigbluebutton#14399]
**Describe the bug**
Recorded lesson can't be played on mobile phone in Safari or Chrome (iOS)

Little to understand error is poping out on screen:
![01](https://user-images.githubusercontent.com/1878503/154645575-3a89a02b-c04a-4a2b-ba3c-b68038c3f257.jpg)

**BBB version:**
BigBlueButton Server 2.4.2 (2885)

**Smartphone:**
 - Device: iPhone7 Plus
 - OS: 15.3.1 (iOS)
 - Browser: Chrome, Safari (both are latest as of 18 Feb 2022)

**Comment by hiroshisuga** [comment]
Have you uncommented mp4 in /usr/local/bigbluebutton/core/scripts/presentation.yml ?

**Comment by greenycat** [comment]
> Have you uncommented mp4 in /usr/local/bigbluebutton/core/scripts/presentation.yml ?

Thanks for advice, didn't know about this feature.
1. Uncommented mp4
2. Rebiult 15+ recordings (took entire evening)

But new issue is here:
It can play voice, camera image but deskdrawings and embeded images in presentation are white (blank).

**Comment by greenycat** [comment]
> I don't think so. I don't see any problem on my iPad. Try deleting the browser cache, and if it still happens, you'd better post it as a new issue, with some more information such as if it also happens on Windows.

Thank you for you time and help. Will do some more testing and publish as new issue if I will recreate it with latest version.
