### ISSUE TITLE
Akka-apps and akka-fsesl build numbers don't increase

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#14407]
Both of them are only showing `2.5`, so when a newer version of the packages is available, it is ignored

```
Unpacking bbb-apps-akka (2.5) over (2.5) ...
Setting up bbb-apps-akka (2.5) ...
Created symlink /etc/systemd/system/
```

![Screenshot from 2022-02-18 17-08-15](https://user-images.githubusercontent.com/6312397/154768083-fa32a67b-bbbe-4d1d-99ec-22780fe6e62d.png)

**Comment by ffdixon** [comment]
Got it -- will fix before the next release.
