### ISSUE TITLE
Tooltips disappears when speaker changes

### ISSUE THREAD

**Issue by klorydryk** [bigbluebutton/bigbluebutton#14401]
On each camera shown on the front-end we have a "switch full-screen" button. The tool-tip displayed on the mouse hover show this text "put Martin in full-screen".
But each time the speaker changes, this tool-tip disappears.

This tool-tip should be independent of the change of speaker, and disappear only in case of move of the mouse, of after a certain value of time.

**Comment by prlanzarin** [comment]
I don't think this is an issue with the camera full screen tooltip specifically, but _all_ tooltips. And I think the talking indicator is not the only trigger (there are some other client re-render points that might make tooltips disappear).

That being said, we didn't have an issue registered for this. Can you please rename the title and the description to be more general (eg Tooltips disappears when speaker changes)? Thanks.
