### ISSUE TITLE
2.5-alpha-1: bbb-webhooks not packaged properly

### ISSUE THREAD

**Issue by svergata** [bigbluebutton/bigbluebutton#14418]
**Describe the bug**
bbb-webhooks package is quite empty. 
The Repochange is not represented in the build process for the package.

**Console output**
root@bbb25-test:~# dpkg -L bbb-webhooks
/.
/etc
/etc/bigbluebutton
/etc/bigbluebutton/nginx
/etc/bigbluebutton/nginx/webhooks.nginx
/usr
/usr/lib
/usr/lib/systemd
/usr/lib/systemd/system
/usr/lib/systemd/system/bbb-webhooks.service
/usr/local
/usr/local/bigbluebutton
/usr/local/bigbluebutton/bbb-webhooks
/usr/local/bigbluebutton/bbb-webhooks/opts-global.sh
/usr/local/bigbluebutton/bbb-webhooks/package-lock.json
/usr/share
/usr/share/doc
/usr/share/doc/bbb-webhooks
/usr/share/doc/bbb-webhooks/changelog.gz

**Comment by antobinary** [comment]
Thanks for reporting, this is handled in 2.5-alpha-2

```
$ dpkg -L bbb-webhooks | wc -l
3419
```
