### ISSUE TITLE
Audio broken after joining breakout session as moderator

### ISSUE THREAD

**Issue by karlchenotto** [bigbluebutton/bigbluebutton#14419]
**Describe the bug**
After starting several breakout sessions and joining one of them via "ask to join" in der breakout session menu, there seems to be no possibility to reconnect the audio in the main room.

**To Reproduce**
1. As Moderator go to 'Manage Users'
2. Click on 'Create Breakout Rooms -> chose e.g. randomly assign.' and 'create'
3. Click on 'Breakout Rooms'
4. Click on "Ask to join" in one of the rooms, chose "join with Microphone", click "Yes"
5. Close room or chose "Leave meeting"
6. Now in the main room there is no Audio and clicking on "Leave Audio" only canges the look of the leave Audio buttion, but does not have any effect on the audio. 

**Expected behavior**
At step 6 there should be a buttom "Rejoin Audio" or audioconnection should be reestablished automatically.

**Desktop (please complete the following information):**
 - OS: Windows 10 
 - Browser: Firefox ESR
 - Version 91.6.0 esr (64-Bit)

**Additional context**
Bug seems to be not reproducible on 
- OS: Debian Bullseye
- Browser: Firefox ESR
- Version 91.6.0 esr (64-Bit)

**Comment by danimo** [comment]
@karlchenotto can you still reproduce this with BBB 2.4.5?

**Comment by antobinary** [comment]
Resembles closely https://github.com/bigbluebutton/bigbluebutton/issues/13631
