### ISSUE TITLE
Support for right to left language localization

### ISSUE THREAD

**Issue by bigbluebutton-issue-import** [bigbluebutton/bigbluebutton#1441]
Originally reported on Google Code with ID 686

```
Bigbluebutton shows persian texts left-to-right. For example "گفتگوي متني" is correct
translation for "chat" but bbb shows "متني گفتگو".
```

Reported by `moradi.mehdi` on 2010-10-26 10:37:01
- **Blocked on**: #667

**Comment by ffdixon** [comment]
Fixed in https://github.com/bigbluebutton/bigbluebutton/pull/7435
