### ISSUE TITLE
Bad Font Encoding in PDF-Presentations

### ISSUE THREAD

**Issue by karlchenotto** [bigbluebutton/bigbluebutton#14420]
**Describe the bug**
PDF exports from Microsoft Powerpoint show a bad font encoding

**To Reproduce**
1. Create Powerpoint
2. Upload via "Manage Presentations" 
3. Compare "PDF" and "PPTX" files

**Expected behavior**
PDF and PPTX should look the same

**Actual behavior**
The font type in the pdf ist wrong and some latters seem to be dislocated when displaying the PDF

**Screenshots**
![grafik](https://user-images.githubusercontent.com/64355994/154946581-12e8f952-da72-4a60-b5c5-2a17221b6329.png)
![grafik](https://user-images.githubusercontent.com/64355994/154946612-353b0ae2-fb70-45da-aed3-5300eecebc7c.png)

**Desktop (please complete the following information):**
 - OS: Debian Bullseye
 - Browser Firefox ESR / Chromium
 - Version BigBlueButton Client build: 2518

**Comment by hiroshisuga** [comment]
Usually adding the font that is used for the presentation solves the problem. See https://docs.bigbluebutton.org/admin/customize.html#add-custom-fonts-for-presentation-conversion .
