### ISSUE TITLE
Cron Daily not Remove some recordings after N days

### ISSUE THREAD

**Issue by ho30hero** [bigbluebutton/bigbluebutton#14423]
Hello, and I hope you are well.
I set cron.daily in BBB 2.4.4 / Ubuntu 18.04.6 for deleting files as below :

history=2
unrecorded_days=2
published_days=2
log_history=28

But we still have some recordings for more than "2 days" on the server and also in Moodle (v10).
How can I ensure that they are removed well from the server automatically ?

Regards

**Comment by hostbbb** [comment]
This removes archived files.  Not files in /var/bigluebutton/published... or unpublished.  What is the directory you think should be deleted?

**Comment by ho30hero** [comment]
Hi, and Thank you for your response.
I want to keep only 2 published recordings that can be played inside Moodle, and delete everything else.
What should I do?

**Comment by ho30hero** [comment]
Hello
I steel have a problem and I have to delete recordings manually every time.
Please help :)

**Comment by GuiLeme** [comment]
Hey @ho30hero, do you still have the problem? if so, please send us more information on the problem, thank you already in advance!

**Comment by ho30hero** [comment]
Hi @GuiLeme @and thank you for your help.

I setup a new server in these days with BBB 2.5.1 installed. 
In fact, I think there must be a way to full control over any files related to recording. (Published, unpublished, deleted, raw, etc ) to fully manage the server disk space.
And the best place I think is the existing file /etc/cron.daily/bigbluebutton

I BBB developers prefer to keep some of them for always as a default feature, simply "comment" them. So everybody, like me, can uncomment the related setting in that file and everything work in a way that the user wants.

Please make it happen. in version 2.2 I didn't have such problems I remember.

Furthermore, I'm not sure about your command and cron is matching to what I need, So I want to re-check with you.
0 0 */2 * * ./home/{your-user}/deleteScript.sh >> /home/{your-user}/cron.log

#!/bin/bash
sudo bbb-record --deleteall
rm /var/log/bigbluebutton/archive-*
date "+[%D-%T] INFO - All recordings deleted" 

I'm Not sure but, I think this delete every recording every 2 days. So for example when it runs after 2 days, delete this day and yesterday's recordings too. Right or not?

Kind regards

**Comment by ho30hero** [comment]
Hello
And thank you for your help.
currently, only user is root! so I create "deleteScript.sh" in /home/ like this (change the number to 4, for 4 days)

```
#!/bin/bash
filesToDelete=$(find /var/bigbluebutton/ -maxdepth 1 -type d -name "*-[0-9]*" -mtime +4)
for i in $filesToDelete; do
sudo bbb-record --delete "${i#*n/}"
rm /var/log/bigbluebutton/archive-*
done
date "+[%D-%T] INFO - recordings cleaned up"
```

also, my crontab is like this:
```
0 0 */1 * * root /etc/cron.daily/bigbluebutton
0 0 */1 * * ./home/deleteScript.sh >> /home/cron.log
@reboot systemctl enable bbb-rap-starter.service
@reboot systemctl enable bbb-rap-resque-worker.service
```

Also my /etc/cron.daily/bigbluebutton is like this (other codes of this file has no changes)
```
history=5
unrecorded_days=3
published_days=3
log_history=28
```

after 4-5 days, nothing was removed I guess, and here is my disk space after all :
```
root@vc2:# df -h
Filesystem      Size  Used Avail Use% Mounted on
udev             16G     0   16G   0% /dev
tmpfs           3.2G  338M  2.9G  11% /run
/dev/sda1       111G   97G  7.9G  93% /   <<<<<<<< look here <<<<<<
tmpfs            16G  432K   16G   1% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs            16G     0   16G   0% /sys/fs/cgroup
tmpfs           512M  319M  194M  63% /mnt/mongo-ramdisk
overlay         111G   97G  7.9G  93% /var/lib/docker/overlay2/b942566f71557216a344faa4f818e83a433eda63ed90701922ac4386e68aeac0/merged
overlay         111G   97G  7.9G  93% /var/lib/docker/overlay2/025c60fd9627f2fb5f204986003e2135616c056e0ac6e8250bdfbba6a58ecafc/merged
shm              64M   16K   64M   1% /var/lib/docker/containers/27c98cd937ae8ac748868609dfeef554df8402d69fa40377c19284b2361480c5/mounts/shm
shm              64M     0   64M   0% /var/lib/docker/containers/99181db00a5804aea96bc9eceab5b381919197a5372bc31ff719b64a45fecb7a/mounts/shm
tmpfs           3.2G     0  3.2G   0% /run/user/0
```

I have no errors in --status or --check commands. 

**Please please please make a complete solution in the next versions for /etc/cron.daily/bigbluebutton so that we can manage all kinds of recording files deletion without any pain =( 
I mean everything, raw, published, unpublished, deleted, etc ....
You can #comment those that you think must be kept by default, so we can uncomment them as our needs** 

Kind regards =)

**Comment by Nick64M** [comment]
We have version 2.7.6 on our server. Has this issue of deleting archives and records been resolved? The disk is limited, so deletion is necessary.
