### ISSUE TITLE
[2.5-alpha-1] - Custom parameter 'userdata-bbb_enable_screen_sharing' is not working

### ISSUE THREAD

**Issue by antonbsa** [bigbluebutton/bigbluebutton#14444]
**Describe the bug**
The button is showing when screen sharing feature is disabled.

**To Reproduce**
1. Set `userdata-bbb_enable_screen_sharing=false`
2. Join meeting

**Automated tests related**
- `CustomParameters - Presentation - Disable screensharing`;

**Expected behavior**
Button shouldn't be displayed.

**Actual behavior**
Button is displayed.

**Screenshot**
![image](https://user-images.githubusercontent.com/56703993/155373921-63786786-6b32-4334-b9aa-391e86f82f2d.png)

**Comment by ramonlsouza** [comment]
it was replaced by disabledFeatures (https://github.com/bigbluebutton/bigbluebutton/pull/14293)
