### ISSUE TITLE
Error thrown when attendee clicks on 'Breakout Rooms' in sidebar

### ISSUE THREAD

**Issue by JoVictorNunes** [bigbluebutton/bigbluebutton#14452]
**Describe the bug**
Undefined value causes an error when attendee clicks on 'Breakout Rooms' in sidebar navigation. A blue screen shows up.

**To Reproduce**
1. Join as a moderator.
2. Join as an attendee.
3. As the moderator, create breakout rooms.
4. A modal will be displayed for the attendee, questioning if the attendee wants to join the breakout room.
5. Close that modal.
6. In the sidebar navigation, click on 'Breakout rooms' (as attendee).
7. See the blue screen.

**Expected behavior**
Sidebar content for breakout rooms should be shown.

**Actual behavior**
A blue screen is shown.

**Screenshots**
![Captura de tela de 2022-02-24 11-46-49](https://user-images.githubusercontent.com/62393923/155548751-27e3d7b3-019f-4cb4-b5ba-98577f2e978f.png)

**BBB version:**
BigBlueButton Server 2.4.4 (2971)

**Comment by antonbsa** [comment]
just adding a step to reproduce the bug:
- Moderator need to assign each one (himself and attendee) to a different room;

_Ps.: I was only able to reproduce by assigning the moderator to the first room and participant to the second._
