### ISSUE TITLE
To allow to switch minimized shared screen to full display

### ISSUE THREAD

**Issue by klorydryk** [bigbluebutton/bigbluebutton#14459]
I understand minimizing the presenter's screen sharing allows to reduce the bandwidth and the BBB shared artefact.

But when the screen is displayed locally, because you're not alone, for example with the videoconferencing displayed on a video-projector in a big room, and that I share my laptop screen : the only way for the people with me is to watch the shared screen through BBB.

I would like to allow the presenter to choose to switch from minimized screen sharing to full display, if necessary.

Thanks !
![Capture d’écran_2022-02-25_11-22-43](https://user-images.githubusercontent.com/1232047/155698722-5f662c52-525f-4333-8434-8dbc93eefde8.png)

**Comment by ffdixon** [comment]
If you click the maximize button in the upper right-hand corner of the thumbnail, it will display the same size as previous versions.

<img width="117" alt="image" src="https://user-images.githubusercontent.com/290351/155717147-0adce1d1-be89-4a12-9b62-edb053f5c47c.png">

**Comment by prlanzarin** [comment]
> If you click the maximize button in the upper right-hand corner of the thumbnail, it will display the same size as previous versions.
> 
> <img alt="image" width="117" src="https://user-images.githubusercontent.com/290351/155717147-0adce1d1-be89-4a12-9b62-edb053f5c47c.png">

Closing.
