### ISSUE TITLE
Failure On Call (reason=ICE Error) (Error 1004)

### ISSUE THREAD

**Issue by shivaprasad573** [bigbluebutton/bigbluebutton#14463]
I am planning to install BBB (Version 2.4.4) in Ubuntu 18.04 (Aws).
I have installed using the instructions given in https://docs.bigbluebutton.org/2.4/install.html#minimum-server-requirements
But after the installation I got an error and not able to enable the microphone it constantly threw 1004 errors in 

**Ubuntu 20.04  Google Chrome Version 98.0.4758.102 (Official Build) (64-bit)** but it was working fine in Mozilla.

Throwing error **Mac  Google Chrome Version 98.0.4758.109 (Official Build) (64-bit)** but it was working fine in Safari.

But in Windows PC, it was working fine in both Chrome and Mozilla.

I thought it was my installation issue but I found that https://test.bigbluebutton.org/ and https://test24.bigbluebutton.org/

Here am attaching a screenshot from https://test.bigbluebutton.org/

![Screenshot from 2022-02-25 18-54-29](https://user-images.githubusercontent.com/12299919/155723341-f64cd398-8f0d-4d8f-96ab-0e9b9fe17224.png)

**Installation type**
wget -qO- https://ubuntu.bigbluebutton.org/bbb-install.sh | bash -s -- -v bionic-240 -s bbb.example.com -e notice@example.com  -a -w

**Firewall and IP address type**
Is your server behind a NAT or firewall?  **Yes**
Does your BBB server have its own IPv4 address? **Yes**

**Console output**
```
root@ip-10-0-1-122:/home/ubuntu# bbb-conf --restart
Restarting BigBlueButton 2.4.4 ...
Stopping BigBlueButton

Applying updates in /etc/bigbluebutton/bbb-conf/apply-config.sh: 
  - Enable Firewall and opening 22/tcp, 80/tcp, 443/tcp and 16384:32768/udp
Skipping adding existing rule
Skipping adding existing rule (v6)
Skipping adding existing rule
Skipping adding existing rule (v6)
Skipping adding existing rule
Skipping adding existing rule (v6)
Firewall is active and enabled on system startup

Starting BigBlueButton


# Potential problems described below
..........................
# Warning: The API demos are installed and accessible from:
#
#    https://videocall2.axyz.com
#
# and
#
#    https://videocall2.axyz.com/demo/demo1.jsp
#
# These API demos allow anyone to access your server without authentication
# to create/manage meetings and recordings. They are for testing purposes only.
# If you are running a production system, remove them by running:
#
#    apt-get purge bbb-demo

# Warning: found only 2 cores, whereas this server should have (at least) 4 CPU cores
# to run BigBlueButton in production.
#
#   https://docs.bigbluebutton.org/install/install.html#minimum-server-requirements
#

#
# Warning: Failed to verify STUN server at stun.l.google.com 19302 with command
#
#    stunclient --mode full --localport 30000 stun.l.google.com 19302
#

#
# Warning: Failed to verify STUN server at 172.217.212.127:19302 with command
#
#    stunclient --mode full --localport 30000 172.217.212.127 19302
#

```

**Additional context**
I thought it was my installation issue but I found that https://test.bigbluebutton.org/ and https://test24.bigbluebutton.org/

**Comment by mokazemi** [comment]
That's exactly something I'm experiencing. **It also happens in some phones** (with both Chrome and Firefox). 
I've tried the only solution provided [here](https://docs.bigbluebutton.org/support/troubleshooting.html#webrtc-errors-1001-1002) But it doesn't work. 

Additional: I've checked freeswitch log in my case. The only thing looks suspicious is hangup with `[INCOMPATIBLE_DESTINATION]` and then `[CS_DESTROY]`.

**Comment by ffdixon** [comment]
Looking at this and wondering if its related to https://github.com/bigbluebutton/bigbluebutton/issues/7547

**Comment by prlanzarin** [comment]
> Looking at this and wondering if its related to #7547

Since mDNS candidates should be either resolvable (or can be ignored) as of FS 1.10.7, the client-side filtering is obsolete and can probably be phased out. It might be able to attenuate this scenario by providing at least some candidate to be parsed (avoiding the incompatible destination error) and giving a chance for the connection to be established through a peer reflexive candidate (because mDNS probably won't work at all).

Although the actual question is: what kind of heuristic (or bug) is kicking in Chrome that would prevent (or delay) the generation of _relay_/`srflx` candidates?

**Comment by mariogasparoni** [comment]
@shivaprasad573  , could you please share bbb-html5 and FreeSWITCH logs ?

Also, are you behind a restrictive network/firewall ? If so, please tell us which ports are blocked, so we might be able to reproduce your scenario here.

**Comment by shivaprasad573** [comment]
for me  [https://test.bigbluebutton.org/](https://test.bigbluebutton.org/) itself is not working 

These are the logs that are printed in the browser console
```
test.bigbluebutton.org/:1 Unchecked runtime.lastError: The message port closed before a response was received.
test.bigbluebutton.org/:1 Unchecked runtime.lastError: The message port closed before a response was received.
test.bigbluebutton.org/:1 Unchecked runtime.lastError: The message port closed before a response was received.
test.bigbluebutton.org/:58 Uncaught ReferenceError: checkform is not defined
    at HTMLFormElement.onsubmit (test.bigbluebutton.org/:58:109)
onsubmit @ test.bigbluebutton.org/:58
Navigated to https://test.bigbluebutton.org/demo/demoHTML5.jsp?username=Test&isModerator=true&action=create
/demo/demoHTML5.jsp?username=Test&isModerator=true&action=create:1 Unchecked runtime.lastError: The message port closed before a response was received.
/demo/demoHTML5.jsp?username=Test&isModerator=true&action=create:1 Unchecked runtime.lastError: The message port closed before a response was received.
/demo/demoHTML5.jsp?username=Test&isModerator=true&action=create:1 Unchecked runtime.lastError: The message port closed before a response was received.
Navigated to https://test.bigbluebutton.org/html5client/join?sessionToken=lwkkwyoonzbenhhv
join:1 Unchecked runtime.lastError: The message port closed before a response was received.
join:1 Unchecked runtime.lastError: The message port closed before a response was received.
join:1 Unchecked runtime.lastError: The message port closed before a response was received.
d13d9965f0d30ea95c841b5e157517ca9def8c8d.js?meteor_js_resource=true:133 [10:20:52:0879] DEBUG: clientLogger: Initial connection status change. status: connecting, connected: false https://test.bigbluebutton.org/html5client/d13d9965f0d30ea95c841b5e157517ca9def8c8d.js?meteor_js_resource=true:375:1323420
d13d9965f0d30ea95c841b5e157517ca9def8c8d.js?meteor_js_resource=true:133 [10:20:54:0297] DEBUG: clientLogger: Initial connection status change. status: connected, connected: true https://test.bigbluebutton.org/html5client/d13d9965f0d30ea95c841b5e157517ca9def8c8d.js?meteor_js_resource=true:375:1323420
d13d9965f0d30ea95c841b5e157517ca9def8c8d.js?meteor_js_resource=true:133 [10:20:54:0299]  INFO: clientLogger: Connection to Meteor took 1.42s https://test.bigbluebutton.org/html5client/d13d9965f0d30ea95c841b5e157517ca9def8c8d.js?meteor_js_resource=true:375:1323582
d13d9965f0d30ea95c841b5e157517ca9def8c8d.js?meteor_js_resource=true:133 [10:20:54:0671]  INFO: clientLogger: Log information about the client i (https://test.bigbluebutton.org/html5client/d13d9965f0d30ea95c841b5e157517ca9def8c8d.js?meteor_js_resource=true:375:1324797)
d13d9965f0d30ea95c841b5e157517ca9def8c8d.js?meteor_js_resource=true:133 [10:20:54:0679]  INFO: clientLogger: User successfully went through main.joinRouteHandler b.fetchToken (https://test.bigbluebutton.org/html5client/d13d9965f0d30ea95c841b5e157517ca9def8c8d.js?meteor_js_resource=true:375:1325888)
d13d9965f0d30ea95c841b5e157517ca9def8c8d.js?meteor_js_resource=true:133 [10:20:55:0167]  INFO: clientLogger: initCursorStreamListener called u (https://test.bigbluebutton.org/html5client/d13d9965f0d30ea95c841b5e157517ca9def8c8d.js?meteor_js_resource=true:375:1295865)
d13d9965f0d30ea95c841b5e157517ca9def8c8d.js?meteor_js_resource=true:133 [10:20:55:0172]  INFO: clientLogger: initAnnotationsStreamListener called C (https://test.bigbluebutton.org/html5client/d13d9965f0d30ea95c841b5e157517ca9def8c8d.js?meteor_js_resource=true:375:726434)
d13d9965f0d30ea95c841b5e157517ca9def8c8d.js?meteor_js_resource=true:133 [10:20:55:0422] DEBUG: clientLogger: Attaching handlers for cursor stream https://test.bigbluebutton.org/html5client/d13d9965f0d30ea95c841b5e157517ca9def8c8d.js?meteor_js_resource=true:375:1296303
d13d9965f0d30ea95c841b5e157517ca9def8c8d.js?meteor_js_resource=true:133 [10:20:55:0427] DEBUG: clientLogger: Attaching handlers for annotations stream https://test.bigbluebutton.org/html5client/d13d9965f0d30ea95c841b5e157517ca9def8c8d.js?meteor_js_resource=true:375:726845
8The resource <URL> was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
d13d9965f0d30ea95c841b5e157517ca9def8c8d.js?meteor_js_resource=true:133 [10:20:56:0685]  INFO: clientLogger: Client loaded successfully he.componentDidMount (https://test.bigbluebutton.org/html5client/d13d9965f0d30ea95c841b5e157517ca9def8c8d.js?meteor_js_resource=true:375:1262614)
d13d9965f0d30ea95c841b5e157517ca9def8c8d.js?meteor_js_resource=true:133 [10:21:16:0149]  INFO: clientLogger: User requested to join audio conference with mic https://test.bigbluebutton.org/html5client/d13d9965f0d30ea95c841b5e157517ca9def8c8d.js?meteor_js_resource=true:375:1432806
d13d9965f0d30ea95c841b5e157517ca9def8c8d.js?meteor_js_resource=true:133 [10:21:16:0501] DEBUG: clientLogger: Creating the user agent https://test.bigbluebutton.org/html5client/d13d9965f0d30ea95c841b5e157517ca9def8c8d.js?meteor_js_resource=true:375:1495381
sip.js?v=2518:9602 Fri Mar 04 2022 10:21:16 GMT+0530 (India Standard Time) | sip.UserAgent | Configuration:
sip.js?v=2518:9602 Fri Mar 04 2022 10:21:16 GMT+0530 (India Standard Time) | sip.UserAgent | · allowLegacyNotifications: false
sip.js?v=2518:9602 Fri Mar 04 2022 10:21:16 GMT+0530 (India Standard Time) | sip.UserAgent | · authorizationHa1: ""
sip.js?v=2518:9602 Fri Mar 04 2022 10:21:16 GMT+0530 (India Standard Time) | sip.UserAgent | · authorizationPassword: NOT SHOWN
sip.js?v=2518:9602 Fri Mar 04 2022 10:21:16 GMT+0530 (India Standard Time) | sip.UserAgent | · authorizationUsername: ""
sip.js?v=2518:9602 Fri Mar 04 2022 10:21:16 GMT+0530 (India Standard Time) | sip.UserAgent | · autoStart: false
sip.js?v=2518:9602 Fri Mar 04 2022 10:21:16 GMT+0530 (India Standard Time) | sip.UserAgent | · autoStop: true
sip.js?v=2518:9602 Fri Mar 04 2022 10:21:16 GMT+0530 (India Standard Time) | sip.UserAgent | · delegate: {}
sip.js?v=2518:9602 Fri Mar 04 2022 10:21:16 GMT+0530 (India Standard Time) | sip.UserAgent | · displayName: "w_bdgt343ucere_1-bbbID-Test"
sip.js?v=2518:9602 Fri Mar 04 2022 10:21:16 GMT+0530 (India Standard Time) | sip.UserAgent | · forceRport: false
sip.js?v=2518:9602 Fri Mar 04 2022 10:21:16 GMT+0530 (India Standard Time) | sip.UserAgent | · hackAllowUnregisteredOptionTags: false
sip.js?v=2518:9602 Fri Mar 04 2022 10:21:16 GMT+0530 (India Standard Time) | sip.UserAgent | · hackIpInContact: false
sip.js?v=2518:9602 Fri Mar 04 2022 10:21:16 GMT+0530 (India Standard Time) | sip.UserAgent | · hackViaTcp: false
sip.js?v=2518:9602 Fri Mar 04 2022 10:21:16 GMT+0530 (India Standard Time) | sip.UserAgent | · hackViaWs: true
sip.js?v=2518:9602 Fri Mar 04 2022 10:21:16 GMT+0530 (India Standard Time) | sip.UserAgent | · hackWssInTransport: false
sip.js?v=2518:9602 Fri Mar 04 2022 10:21:16 GMT+0530 (India Standard Time) | sip.UserAgent | · logBuiltinEnabled: true
sip.js?v=2518:9602 Fri Mar 04 2022 10:21:16 GMT+0530 (India Standard Time) | sip.UserAgent | · logConfiguration: true
sip.js?v=2518:9602 Fri Mar 04 2022 10:21:16 GMT+0530 (India Standard Time) | sip.UserAgent | · logConnector: undefined
sip.js?v=2518:9602 Fri Mar 04 2022 10:21:16 GMT+0530 (India Standard Time) | sip.UserAgent | · logLevel: "log"
sip.js?v=2518:9602 Fri Mar 04 2022 10:21:16 GMT+0530 (India Standard Time) | sip.UserAgent | · noAnswerTimeout: 60
sip.js?v=2518:9602 Fri Mar 04 2022 10:21:16 GMT+0530 (India Standard Time) | sip.UserAgent | · preloadedRouteSet: []
sip.js?v=2518:9602 Fri Mar 04 2022 10:21:16 GMT+0530 (India Standard Time) | sip.UserAgent | · reconnectionAttempts: 0
sip.js?v=2518:9602 Fri Mar 04 2022 10:21:16 GMT+0530 (India Standard Time) | sip.UserAgent | · reconnectionDelay: 4
sip.js?v=2518:9602 Fri Mar 04 2022 10:21:16 GMT+0530 (India Standard Time) | sip.UserAgent | · sessionDescriptionHandlerFactory: (session, options) => {
        // provide a default media stream factory if need be
        if (mediaStreamFactory === undefined) {
            mediaStreamFactory = Object(_media_stream_factory_default__WEBPACK_IMPORTED_MODULE_0__["defaultMediaStreamFactory"])();
        }
        // make sure we allow `0` to be passed in so timeout can be disabled
        const iceGatheringTimeout = (options === null || options === void 0 ? void 0 : options.iceGatheringTimeout) !== undefined ? options === null || options === void 0 ? void 0 : options.iceGatheringTimeout : 5000;
        // merge passed factory options into default session description configuration
        const sessionDescriptionHandlerConfiguration = {
            iceGatheringTimeout,
            peerConnectionConfiguration: Object.assign(Object.assign({}, Object(_peer_connection_configuration_default__WEBPACK_IMPORTED_MODULE_1__["defaultPeerConnectionConfiguration"])()), options === null || options === void 0 ? void 0 : options.peerConnectionConfiguration)
        };
        const logger = session.userAgent.getLogger("sip.SessionDescriptionHandler");
        return new _session_description_handler__WEBPACK_IMPORTED_MODULE_2__["SessionDescriptionHandler"](logger, mediaStreamFactory, sessionDescriptionHandlerConfiguration);
    }
sip.js?v=2518:9602 Fri Mar 04 2022 10:21:16 GMT+0530 (India Standard Time) | sip.UserAgent | · sessionDescriptionHandlerFactoryOptions: {"peerConnectionConfiguration":{"iceServers":[{"urls":"turns:ipv4.turn.blindsidenetworks.com:443?transport=tcp","credential":"MMfcZ84nRpSXBCUknoSqaRFp8Kk=","username":"1646455876:w_bdgt343ucere"},{"urls":"turn:turn.blindsidenetworks.com:443?transport=tcp","credential":"MMfcZ84nRpSXBCUknoSqaRFp8Kk=","username":"1646455876:w_bdgt343ucere"},{"urls":"turns:turn.blindsidenetworks.com:443?transport=tcp","credential":"MMfcZ84nRpSXBCUknoSqaRFp8Kk=","username":"1646455876:w_bdgt343ucere"}],"sdpSemantics":"unified-plan"}}
sip.js?v=2518:9602 Fri Mar 04 2022 10:21:16 GMT+0530 (India Standard Time) | sip.UserAgent | · sipExtension100rel: "Unsupported"
sip.js?v=2518:9602 Fri Mar 04 2022 10:21:16 GMT+0530 (India Standard Time) | sip.UserAgent | · sipExtensionReplaces: "Unsupported"
sip.js?v=2518:9602 Fri Mar 04 2022 10:21:16 GMT+0530 (India Standard Time) | sip.UserAgent | · sipExtensionExtraSupported: []
sip.js?v=2518:9602 Fri Mar 04 2022 10:21:16 GMT+0530 (India Standard Time) | sip.UserAgent | · sipjsId: "6fsdj"
sip.js?v=2518:9602 Fri Mar 04 2022 10:21:16 GMT+0530 (India Standard Time) | sip.UserAgent | · transportConstructor: Transport
sip.js?v=2518:9602 Fri Mar 04 2022 10:21:16 GMT+0530 (India Standard Time) | sip.UserAgent | · transportOptions: {"server":"wss://test.bigbluebutton.org/ws?sessionToken=lwkkwyoonzbenhhv","connectionTimeout":5000,"keepAliveInterval":30,"keepAliveDebounce":10,"traceSip":false}
sip.js?v=2518:9602 Fri Mar 04 2022 10:21:16 GMT+0530 (India Standard Time) | sip.UserAgent | · uri: sip:w_bdgt343ucere_1-bbbID-Test@test.bigbluebutton.org
sip.js?v=2518:9602 Fri Mar 04 2022 10:21:16 GMT+0530 (India Standard Time) | sip.UserAgent | · userAgentString: "BigBlueButton"
sip.js?v=2518:9602 Fri Mar 04 2022 10:21:16 GMT+0530 (India Standard Time) | sip.UserAgent | · viaHost: "n5jvlra03675.invalid"
sip.js?v=2518:9602 Fri Mar 04 2022 10:21:16 GMT+0530 (India Standard Time) | sip.UserAgent | · register: false
sip.js?v=2518:9602 Fri Mar 04 2022 10:21:16 GMT+0530 (India Standard Time) | sip.UserAgent | Starting sip:w_bdgt343ucere_1-bbbID-Test@test.bigbluebutton.org
sip.js?v=2518:9602 Fri Mar 04 2022 10:21:16 GMT+0530 (India Standard Time) | sip.UserAgent | Transitioned from Stopped to Started
sip.js?v=2518:9602 Fri Mar 04 2022 10:21:16 GMT+0530 (India Standard Time) | sip.Transport | Connecting wss://test.bigbluebutton.org/ws?sessionToken=lwkkwyoonzbenhhv
sip.js?v=2518:9602 Fri Mar 04 2022 10:21:16 GMT+0530 (India Standard Time) | sip.Transport | Transitioned from Disconnected to Connecting
sip.js?v=2518:9602 Fri Mar 04 2022 10:21:17 GMT+0530 (India Standard Time) | sip.Transport | WebSocket opened wss://test.bigbluebutton.org/ws?sessionToken=lwkkwyoonzbenhhv
sip.js?v=2518:9602 Fri Mar 04 2022 10:21:17 GMT+0530 (India Standard Time) | sip.Transport | Transitioned from Connecting to Connected
d13d9965f0d30ea95c841b5e157517ca9def8c8d.js?meteor_js_resource=true:133 [10:21:17:0525]  INFO: clientLogger: User agent succesfully connected https://test.bigbluebutton.org/html5client/d13d9965f0d30ea95c841b5e157517ca9def8c8d.js?meteor_js_resource=true:375:1497465
sip.js?v=2518:9602 Fri Mar 04 2022 10:21:17 GMT+0530 (India Standard Time) | sip.Inviter | Inviter.invite
d13d9965f0d30ea95c841b5e157517ca9def8c8d.js?meteor_js_resource=true:133 [10:21:18:0382]  INFO: clientLogger: ICE gathering candidates took (s): 0.815 Y.onIceGatheringStateChange (https://test.bigbluebutton.org/html5client/d13d9965f0d30ea95c841b5e157517ca9def8c8d.js?meteor_js_resource=true:375:1499598)
sip.js?v=2518:9602 Fri Mar 04 2022 10:21:18 GMT+0530 (India Standard Time) | sip.Inviter | Session 6fsdje9rv5gig3nlrobq75b6hfcthn transitioned to state Establishing
d13d9965f0d30ea95c841b5e157517ca9def8c8d.js?meteor_js_resource=true:133 [10:21:18:0393]  INFO: clientLogger: Audio call session progress update k (https://test.bigbluebutton.org/html5client/d13d9965f0d30ea95c841b5e157517ca9def8c8d.js?meteor_js_resource=true:375:1503385)
sip.js?v=2518:9602 Fri Mar 04 2022 10:21:18 GMT+0530 (India Standard Time) | sip.Inviter | Inviter.onTrying
sip.js?v=2518:9602 Fri Mar 04 2022 10:21:18 GMT+0530 (India Standard Time) | sip.Inviter | Inviter.onReject
sip.js?v=2518:9602 Fri Mar 04 2022 10:21:18 GMT+0530 (India Standard Time) | sip.Inviter | Session 6fsdje9rv5gig3nlrobq75b6hfcthn transitioned to state Terminated
d13d9965f0d30ea95c841b5e157517ca9def8c8d.js?meteor_js_resource=true:133 [10:21:18:0765]  INFO: clientLogger: SIP.js session terminated x (https://test.bigbluebutton.org/html5client/d13d9965f0d30ea95c841b5e157517ca9def8c8d.js?meteor_js_resource=true:375:1505178)
d13d9965f0d30ea95c841b5e157517ca9def8c8d.js?meteor_js_resource=true:133 [10:21:18:0766]  WARN: clientLogger: Audio call terminated. cause=ICE error w (https://test.bigbluebutton.org/html5client/d13d9965f0d30ea95c841b5e157517ca9def8c8d.js?meteor_js_resource=true:375:1504948)
d13d9965f0d30ea95c841b5e157517ca9def8c8d.js?meteor_js_resource=true:133 [10:21:18:0767] ERROR: clientLogger: Audio error - errorCode=1004, cause=ICE error https://test.bigbluebutton.org/html5client/d13d9965f0d30ea95c841b5e157517ca9def8c8d.js?meteor_js_resource=true:375:1438428
sip.js?v=2518:9602 Fri Mar 04 2022 10:21:18 GMT+0530 (India Standard Time) | sip.Inviter | Session 6fsdje9rv5gig3nlrobq75b6hfcthn in state Terminated is being disposed
```

**Comment by panjalamounith** [comment]
Hi @mariogasparoni i am also facing the same issue after installing the bigbluebutton and tried to join the meeting facing the same ICE error please update the solution for this issue.
thanks, please review the comment

**Comment by Kernelogy** [comment]
BBB is working fine in 99.8% of the cases, the rest 0.2% are facing ICE 1004 issue in their devices. A particular customer, who is facing this issue, is using a latest SAMSUNG device with android version 11 and latest chrome version. We adviced them to clear the browser cache, asked them to reinstall chrome still the issue prevailed. And when installed a latest firefox and tried connecting, the audio connected successfully once and after that the same ICE 1004 error appeared whenever try connecting to the meeting.

**Comment by hostbbb** [comment]
@Kernelogy what version of bbb...  sudo bbb-conf --check will tell you?

**Comment by Examsdailytamil** [comment]
@hostbbb 
BigBlueButton Server 2.4.2 (2885)
                    Kernel version: 5.4.0-1061-aws
                      Distribution: Ubuntu 18.04.6 LTS (64-bit)
                            Memory: 32882 MB
                         CPU cores: 8

/etc/bigbluebutton/bbb-web.properties (override for bbb-web)
/usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties (bbb-web)
       bigbluebutton.web.serverURL: https://domain.com
                defaultGuestPolicy: ALWAYS_ACCEPT
                 svgImagesRequired: true
              defaultMeetingLayout: SMART_LAYOUT

/etc/nginx/sites-available/bigbluebutton (nginx)
                       server_name: domain.com
                              port: 80, [::]:80
                              port: 443 ssl

/opt/freeswitch/etc/freeswitch/vars.xml (FreeSWITCH)
                       local_ip_v4: 172.26.xx.xxx
                   external_rtp_ip: 3.108.xx.xxx
                   external_sip_ip: 3.108.xx.xxx

/opt/freeswitch/etc/freeswitch/sip_profiles/external.xml (FreeSWITCH)
                        ext-rtp-ip: $${external_rtp_ip}
                        ext-sip-ip: $${external_sip_ip}
                        ws-binding: 3.108.xx.xxx:5066
                       wss-binding: 3.108.xx.xxx:7443

/usr/local/bigbluebutton/core/scripts/bigbluebutton.yml (record and playback)
                     playback_host: domain.com
                 playback_protocol: https
                            ffmpeg: 4.2.4-1ubuntu0.1bbb2~18.04

/etc/bigbluebutton/nginx/sip.nginx (sip.nginx)
                        proxy_pass: 3.108.xx.xxx
                          protocol: http

/usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml (Kurento SFU)
/etc/bigbluebutton/bbb-webrtc-sfu/production.yml (Kurento SFU - override)
                        kurento.ip: 3.108.xx.xxx
                       kurento.url: ws://127.0.0.1:8888/kurento
                    kurento.sip_ip: 3.108.xx.xxx
               recordScreenSharing: true
                     recordWebcams: true
                  codec_video_main: VP8
               codec_video_content: VP8

/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml (HTML5 client)
/etc/bigbluebutton/bbb-html5.yml (HTML5 client config override)
                             build: 2478
                        kurentoUrl: wss://domain.com/bbb-webrtc-sfu
                  enableListenOnly: true
                    sipjsHackViaWs: true

/usr/share/bbb-web/WEB-INF/classes/spring/turn-stun-servers.xml (STUN Server)
                              stun: stun4.l.google.com:19302

/etc/kurento/modules/kurento/WebRtcEndpoint.conf.ini (STUN Server)
                              stun: 172.217.212.127:19302


# Potential problems described below


#
# Warning: Failed to verify STUN server at stun4.l.google.com 19302 with command
#
#    stunclient --mode full --localport 30000 stun4.l.google.com 19302
#

#
# Warning: Failed to verify STUN server at 172.217.212.127:19302 with command
#
#    stunclient --mode full --localport 30000 172.217.212.127 19302
#

**Comment by Kernelogy** [comment]
@hostbbb 

BigBlueButton Server 2.4.2 (2885)
Kernel version: 5.4.0-1061-aws
Distribution: Ubuntu 18.04.6 LTS (64-bit)
Memory: 32882 MB
CPU cores: 8

/etc/bigbluebutton/bbb-web.properties (override for bbb-web)
/usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties (bbb-web)
bigbluebutton.web.serverURL: https://domain.com/
defaultGuestPolicy: ALWAYS_ACCEPT
svgImagesRequired: true
defaultMeetingLayout: SMART_LAYOUT

/etc/nginx/sites-available/bigbluebutton (nginx)
server_name: domain.com
port: 80, [::]:80
port: 443 ssl

/opt/freeswitch/etc/freeswitch/vars.xml (FreeSWITCH)
local_ip_v4: 172.26.xx.xxx
external_rtp_ip: 3.108.xx.xxx
external_sip_ip: 3.108.xx.xxx

/opt/freeswitch/etc/freeswitch/sip_profiles/external.xml (FreeSWITCH)
ext-rtp-ip: $${external_rtp_ip}
ext-sip-ip: $${external_sip_ip}
ws-binding: 3.108.xx.xxx:5066
wss-binding: 3.108.xx.xxx:7443

/usr/local/bigbluebutton/core/scripts/bigbluebutton.yml (record and playback)
playback_host: domain.com
playback_protocol: https
ffmpeg: 4.2.4-1ubuntu0.1bbb2~18.04

/etc/bigbluebutton/nginx/sip.nginx (sip.nginx)
proxy_pass: 3.108.xx.xxx
protocol: http

/usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml (Kurento SFU)
/etc/bigbluebutton/bbb-webrtc-sfu/production.yml (Kurento SFU - override)
kurento.ip: 3.108.xx.xxx
kurento.url: ws://127.0.0.1:8888/kurento
kurento.sip_ip: 3.108.xx.xxx
recordScreenSharing: true
recordWebcams: true
codec_video_main: VP8
codec_video_content: VP8

/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml (HTML5 client)
/etc/bigbluebutton/bbb-html5.yml (HTML5 client config override)
build: 2478
kurentoUrl: wss://domain.com/bbb-webrtc-sfu
enableListenOnly: true
sipjsHackViaWs: true

/usr/share/bbb-web/WEB-INF/classes/spring/turn-stun-servers.xml (STUN Server)
stun: stun4.l.google.com:19302

/etc/kurento/modules/kurento/WebRtcEndpoint.conf.ini (STUN Server)
stun: 172.217.212.127:19302

Potential problems described below
Warning: Failed to verify STUN server at stun4.l.google.com 19302 with command
stunclient --mode full --localport 30000 stun4.l.google.com 19302
Warning: Failed to verify STUN server at 172.217.212.127:19302 with command
stunclient --mode full --localport 30000 172.217.212.127 19302
