### ISSUE TITLE
Cluster proxy setup does not work as documented (breaks waiting rooms)

### ISSUE THREAD

**Issue by defnull** [bigbluebutton/bigbluebutton#14462]
The documented [Cluster Proxy Setup](https://docs.bigbluebutton.org/admin/clusterproxy.html) breaks waiting rooms, because `guest-wait.html` assumes wrong paths for locals and contacts the wrong domain for API requests.

* Locale information is downloaded from `${window.location.origin}/html5client/locale` and `locales` (relative path). The later works, but the origin based absolute URL will not contain the required node-specific path prefix and result in a 404 error.
* To check guestWait status, the script polls `${window.location.origin}/bigbluebutton/api/guestWait`. Scalelite does not support this API (and cannot support it, because it does not track client sessions). Here the actual node domain is required, not the loadbalancer domain.

**Comment by GuiLeme** [comment]
Hi, @defnull, sorry for the late response, but since this issue has been posted, there were some updates in the docs on that regards, it might worth a try to see if the problem you described is still happening

**Comment by tibroc** [comment]
I can not reproduce this issue any more with 2.6
