### ISSUE TITLE
[2.4] Extra hint for upload limit is missing

### ISSUE THREAD

**Issue by mk-hs** [bigbluebutton/bigbluebutton#14503]
**Describe the bug**
According to https://github.com/bigbluebutton/bigbluebutton/pull/14158 a new hint was introduced in [BigBlueButton 2.4.3](https://github.com/bigbluebutton/bigbluebutton/releases/tag/v2.4.3) and should be displayed while managing presentations. This doesn't happen.

**To Reproduce**
1. Open a meeting
2. Manage presentations

**Expected behavior**
"IMPORTANT: each file may not exceed {0} MB and {1} pages." should be displayed.

**Actual behavior**
Nothing's being displayed.

**Screenshots**
![Unbenannt](https://user-images.githubusercontent.com/63116186/156379912-22f26d49-c96f-4a15-9c16-e97f2c644b27.png)

**BBB version:**
BigBlueButton Server 2.4.4 (2518)
Happens on our local installations and on test.bigbluebutton.org

**Browser**
This happens on both Firefox and Chrome. Both Browsers were using the German locale, setting the client to English didn't make the message appear either.

**Comment by antobinary** [comment]
All good! The thorough description and links allowed for a quick response!
