### ISSUE TITLE
Upgrade Tomcat8

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#14519]
We are looking at upgrading Tomcat from 8 to 9 or even 10. This is desired to make the transition to Ubuntu 20.04 smoother.

We use the package `tomcat8` for running `bbb-demo` (optional package) and `bbb-lti` (also optional package).
`bbb-web` also runs on Tomcat 8, but it is embedded. Relevant: https://github.com/bigbluebutton/bigbluebutton/issues/12580

The initial exploration into Ubuntu 20.04 https://github.com/bigbluebutton/bigbluebutton/pull/14417 showed that BigBlueButton runs alright if the first is upgraded to Tomcat9 and the second one is untouched. I believe replicating this approach is a good first step to satisfy the conditions for using Ubuntu 20.04.

Tracking:
- [x] upgrade tomcat in bbb-demo
- [x] upgrade tomcat in bbb-demo packaging
- [x] upgrade tomcat in bbb-lti
- [x] upgrade tomcat in bbb-lti packaging
- [x] upgrade tomcat in bbb-intstall (2.5 version) install scipt
- [x] upgrade tomcat in BBB 2.5 documentation

@zhem0004 has done preliminary work on Ubuntu 18.04 exploring the upgrade process from `tomcat8` to `tomcat10`.

**Comment by zhem0004** [comment]
<details>
sudo groupadd tomcat
sudo mkdir /opt/tomcat
sudo useradd -g tomcat -d /opt/tomcat -s /usr/sbin/nologin tomcat

cd /tmp

curl -O https://downloads.apache.org/tomcat/tomcat-10/v10.0.16/bin/apache-tomcat-10.0.16.tar.gz

cd /opt/tomcat

sudo tar xzvf /tmp/apache-tomcat-10.0.16.tar.gz -C /opt/tomcat --strip-components=1

sudo chgrp -R tomcat /opt/tomcat

sudo chmod -R g+r conf

sudo chmod g+x conf

sudo chown -R tomcat webapps/ work/ temp/ logs/

sudo update-java-alternatives -l  #write out java home path   #/usr/lib/jvm/java-1.8.0-openjdk-amd64

sudo vim /etc/systemd/system/tomcat.service

_____________________________________
[Unit]
Description=Apache Tomcat Web Application Container
After=network.target

[Service]
Type=forking

Environment=JAVA_HOME=<--JAVA_HOME PATH that you wrote down -->
Environment=CATALINA_PID=/opt/tomcat/temp/tomcat.pid
Environment=CATALINA_Home=/opt/tomcat
Environment=CATALINA_BASE=/opt/tomcat
Environment=’CATALINA_OPTS=-Xms512M -Xmx1024M -server -XX:+UseParallelGC’
Environment=’JAVA_OPTS.awt.headless=true -Djava.security.egd=file:/dev/v/urandom’

ExecStart=/opt/tomcat/bin/startup.sh
ExecStop=/opt/tomcat/bin/shutdown.sh

User=tomcat
Group=tomcat
UMask=0007
RestartSec=10
Restart=always

[Install]
WantedBy=multi-user.target
___________________________________

sudo systemctl daemon-reload

sudo systemctl start tomcat

sudo systemctl status tomcat

vim /opt/tomcat/conf/tomcat-users.xml

# under all comments add
___________________________________

 <role rolename="managet-gui" />
 <user username="admin" password="password" roles="manager-gui"/>
 
 <role rolename="adin-gui" />
 <user username="admin" password="password" roles="manager-gui,admin-gui"/>
___________________________________

vim /opt/tomcat/webapps/manager/META-INF/content.xml

#coment out <Value/>

vim /opt/tomcat/webapps/host-manager/META-INF/content.xml

#coment out <Value/>

#try

http://server_domain_or_IP:8080
http://server_domain_or_IP:8080/manager/html

#can use "Add Virtual Host" to add IP or domain

#to deploy, place .war file in var/lib/tomcat/
</details>
