### ISSUE TITLE
Upgrade yq to v4

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#14511]
Currently (BBB 2.5-alpha-2) we're using `yq` 3.3.2
The recommended version for yq is 4+

The method we currently use for installing `yq` (installing in bbb-install via `rmescandon-ubuntu-yq-bionic.list         ppa:rmescandon/yq` ) does not seem to work when I try to upgrade BBB to Ubuntu 20.04 (even if I change the list to focal)

The approach I see forward is two-fold:
Step 1: On bionic:
- [ ] install yq in a different way, controlling the version, a way that is supported on focal too.

```
    wget https://github.com/mikefarah/yq/releases/download/3.4.1/yq_linux_amd64 -O /usr/bin/yq && chmod +x /usr/bin/yq
    yq -V
```

seems OK

- [ ] temporarily drop the `yq` dependency for a few of the bbb-* packages

< upgrade to Ubuntu 20.04>

Step 2: 
- [ ] upgrade yq to v4 in bbb-install
- [ ] Adapt about 90 uses of `yq` https://mikefarah.gitbook.io/yq/v/v4.x/upgrading-from-v3#updating-writing-documents
- [ ] add `yq` as dependency to those bbb-* packages

The reason why I am not trying to upgrade to v4 while on bionic is that there's heavy reworking on packaging/configuration, see https://github.com/bigbluebutton/bigbluebutton/pull/14485 , https://github.com/bigbluebutton/bigbluebutton/issues/14484

And also if I do that around the same time I upgrade to Ubuntu 20.04 it would be more difficult to debug whether something broke because of 20.04 or because of a yq incorrect usage

**Comment by antobinary** [comment]
Alternatively --
First 
- merge https://github.com/bigbluebutton/bigbluebutton/pull/14485 which will reduce the number of `yq` uses and complexity quite a bit

Then
-  upgrade to v4 and do the ~70 config lines of changes on bionic, 
- confirm all works
- modify bbb-install to use v4 of yq

**Comment by antobinary** [comment]
Related - https://github.com/bigbluebutton/bigbluebutton/pull/14883

**Comment by kepstin** [comment]
After updating the packaging scripts to work with yq 4, will also need to re-enable the upstream ppa for yq in https://github.com/bigbluebutton/bbb-install/blob/3f99885b5c30cd455f1ec20c99873d5f28e6be26/bbb-install-2.5.sh#L236
