### ISSUE TITLE
Snapshot of current presentation on Safari

### ISSUE THREAD

**Issue by JoVictorNunes** [bigbluebutton/bigbluebutton#14510]
The newly implemented screenshot tool (https://github.com/bigbluebutton/bigbluebutton/pull/14406) doesn't support Safari.

The library used to implement this functionality ([html-to-image](https://github.com/bubkoo/html-to-image)) doesn't support the `<foreignObject>` tag on Safari.

> Safari is not supported, as it uses a stricter security model on <foreignObject> tag. Suggested workaround is to use toSvg and render on the server.

So, a workaround is needed in order to implement it on Safari.

**Comment by ffdixon** [comment]
Re-opening as it's still an issue with Safari.

**Comment by antobinary** [comment]
https://github.com/bigbluebutton/bigbluebutton/pull/19599 was recently done in this area. @ramonlsouza do you know if this can be also closed?

**Comment by ramonlsouza** [comment]
> #19599 was recently done in this area. @ramonlsouza do you know if this can be also closed?

Partially, yes. Looks like Safari on macOS needs the same code as on iOS for it to work 100% (now it only works if the slide has annotations), it should work with https://github.com/bigbluebutton/bigbluebutton/pull/19665

**Comment by antobinary** [comment]
Excellent work, @ramonlsouza !! :rocket:
