### ISSUE TITLE
Multiple users screen share

### ISSUE THREAD

**Issue by demogorgonz** [bigbluebutton/bigbluebutton#14516]
**Is your feature request related to a problem? Please describe.**
Sometimes multiple people needs to share screen, it is hassle to give presenter rights each time.

**Describe the solution you'd like**
Multiple screen share streams in same room.

**Comment by prlanzarin** [comment]
Duplicate of https://github.com/bigbluebutton/bigbluebutton/issues/9152

**Comment by blipp** [comment]
For completeness, adding a link to issue #21542, which seems to be the tracking issue for this feature: it has been assigned to the milestone for Version 3.1
