### ISSUE TITLE
Allow admins to set up "events" and allow users to join an event by email

### ISSUE THREAD

**Issue by bzg** [bigbluebutton/bigbluebutton#14523]
I cannot use BBB to allow people to "subscribe" to a webinar (à la eventbrite).

I know people who prefer other proprietary webconference solutions because they provide this feature (e.g. livestorm.co). 

As an admin, I'd like to be able to set up events (date, time, duration, description) associated with existing rooms.

For every event, users would be welcomed by a page similar than the existing one for rooms, except that they could _subscribe_ to the event by filling in their email addresses.

Admins for an event could:

- access the list of subscribers' email addresses
- decide whether or not the subscribers should receive an email reminder for the event, and when
- decide whether all participants (email addresses) are prevalidated for the event with no confirmation
- or whether users should confirm their participation by clicking on a link in a confirmation email.

Admins could delete past events and add, delete, modify future events.

**Comment by garronej** [comment]
This would be great

**Comment by defnull** [comment]
While this is a nice idea, this issue tracker is the wrong place to discuss features like this. BigBlueButton only knows and cares about currently running meetings (and recordings of past meetings). More advanced concepts like rooms, events, user accounts, subscriptions, permissions ect. are all managed by separate front-end applications (e.g. Greenlight or Moodle). You should bring your ideas to these projects. I'd suggest looking at existing open source event management software (like Indico) and check if there are BBB plugins available, or if one could be developed.

**Comment by bzg** [comment]
Thanks @defnull, that's useful to know.  I'm closing this issue now and will see where to share this need.
