### ISSUE TITLE
API joinUrl not working when in window.open

### ISSUE THREAD

**Issue by jasmines** [bigbluebutton/bigbluebutton#14542]
I'm on BBB 2.2, and I'm using API to create/join meetings.
If I call API to get the join URL, it works if I put in the href of an "a" element in the same page, but it returns a message error (checksum security) if I try to open the join URL with the window.open javascript command.
Why?

**Comment by ffdixon** [comment]
Hi there,

BigBlueButton 2.2 is very old and we're now on 2.4.  Is it an option for you to upgrade?  Also, if you encounter problems, post first to bigbluebutton-setup and we'll help you there.  If there is an issue in BigBlueButton that is discovered while helping you in the forums, we'll open an issue here to track it.

**Comment by jasmines** [comment]
Unfortunately upgrade is not an option.
Can you just answer to my question? Can join URL (obtained via API) be opened in a new window called by javascript window.open? If I'm sure it works, I will install a new BBB 2.4 instead of upgrade.

**Comment by hostbbb** [comment]
# Allow requests without JSESSIONID to be handled (default = false)
allowRequestsWithoutSession=false

change to true in bigbluebutton.properties.

try this...  not 100% sure but the session token may be whats preventing you the new window from joininh.

**Comment by jasmines** [comment]
Already did and nothing changes.
Should I restart anything?

**Comment by hostbbb** [comment]
if you make change to bigbluebutton.properties, need to bbb-conf --restart

**Comment by jasmines** [comment]
Doesn't work
