### ISSUE TITLE
Missing ruby files in pakage bbb-playback-notes for BBB 2.4.

### ISSUE THREAD

**Issue by rriscado** [bigbluebutton/bigbluebutton#14554]
**Describe the bug**
The pakage bbb-playback-notes for BBB 2.4 have missing ruby files.

**To Reproduce**
Install a package bbb-playback-notes in BBB 2.4

**Screenshots**

BBB 2.3.12
![image](https://user-images.githubusercontent.com/14829973/157138088-05efede7-4f80-4bd0-b7ed-c2d3c806a0ff.png)

BBB 2.4.4
![image](https://user-images.githubusercontent.com/14829973/157138415-cf98b6b1-4bc6-4f15-b30a-daf90d2839b5.png)

**Comment by ffdixon** [comment]
Thanks for the report.  The presentation playback format in 2.4 includes Shared Notes, so the `bbb-playback-notes` is obsolete.  Our plan is to remove it in 2.5.

**Comment by hostbbb** [comment]
@rriscado - the good news is your notes are accessible for any 2.4 recording by using this relative path.  just need meeting id.

https://xxxxx.distancelearning.cloud/presentation/bd21c297d4802287470458700b2406e5bdede31a-1646738272089/notes.html

you could easily convert to pdf and push somewhere if needed in that format.

**Comment by EmmyGraugans** [comment]
@ffdixon 
> Thanks for the report. The presentation playback format in 2.4 includes Shared Notes, so the `bbb-playback-notes` is obsolete. Our plan is to remove it in 2.5.

Just a tiny note that this package `bbb-playback-notes `is *still* present in 2.6.0-rc.1 – might want to remove it before going stable?

**Comment by antobinary** [comment]
Thanks for the reminder @EmmyGraugans

**Comment by antobinary** [comment]
After checking with @kepstin --
The purpose of the `bbb-playback-notes` package lately has been mostly about providing backward compatibility via the nginx file it deploys. No scripts.

I am not sure if we will continue carrying this package forward forever, but wanted to document the reason it was still around.
