### ISSUE TITLE
Learning dashboard - no data (Data is no longer available)

### ISSUE THREAD

**Issue by sutidor** [bigbluebutton/bigbluebutton#14556]
**Describe the bug**
Whenever I end a meeting I klick on learning dashboard, and after it flashes it says `Data is no longer available`

**To Reproduce**
1. Start meeting
2. End meeting as moderator
3. Click on "learning dashboard"
4. See error `Data is no longer available`, after opening console and refreshing there is a 404 for `https://some.url/learning-analytics-dashboard/<hash>/<id>/learning_dashboard_data.json`

**Expected behavior**
Show me learning dashboard

**Actual behavior**
`Data is no longer available` error occurs

**Screenshots**
![Selection_011](https://user-images.githubusercontent.com/34579211/157236910-eea23fa3-88a8-4a34-8f7c-6a7b658e11b2.png)
![Selection_010](https://user-images.githubusercontent.com/34579211/157236893-ea76299d-61ae-476d-a964-561334735865.png)

**BBB version:**
I guess Version: 2.4.4, how to find out on docker?

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser Firefox
 - Version 97.0

**Additional Context**
```
# set to false to disable the learning dashboard
ENABLE_LEARNING_DASHBOARD=true
```

**Comment by antobinary** [comment]
Hi, this is _similar_ to the default behavior (depending on whether you wait a minute or two before clicking), feel free to change the settings by passing an override key= value
in `/etc/bigbluebutton/bbb-web.properties`

https://github.com/bigbluebutton/bigbluebutton/blob/v2.4.x-release/bigbluebutton-web/grails-app/conf/bigbluebutton.properties#L250-L253

```
# Number of minutes that Learning Dashboard will be available after the end of the meeting
# if 0, the Learning Dashboard will keep available permanently
# this is the default value, can be customized using the create API
learningDashboardCleanupDelayInMinutes=2
```

**Comment by wullxz** [comment]
Just for documentation purposes (and because this is the only thing you'll find on google searching for that error):
This also happens if `bigbluebutton:bigbluebutton` is not owner of `/var/bigbluebutton/learning-dashboard` because the meeting directories cannot be created under that path.
