### ISSUE TITLE
Fix(bbb-conf) unneeded warnings for --check

### ISSUE THREAD

**Issue by pielonet** [bigbluebutton/bigbluebutton#14555]
Hi,
BBB version 2.5-alpha3
`bbb-conf --check` warns the following :
```
# Potential problems described below
# The following properties in /usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties have no value:
#     

/usr/bin/bbb-conf: line 1299: stunclient: command not found
```
It looks like the first warn is about an empty property !
The second line is a warning concerning an executable that was removed at install

Both warnings should not be there !

Kind regards,
Thierry

**Comment by raspoutnik** [comment]
I have difficulties connecting to custom stun server. stunclient binary missing in Ubuntu 20.04 is quite annoying indeed.

**Comment by antobinary** [comment]
Hi there!
Stunclient was _dropped_ from BigBlueButton 2.5. It is not needed. This was done circa Alpha5.
Please ensure you use a _clean_ Ubuntu 20.04 with BigBlueButton 2.5.0-alpha.5 or later (latest is 6 at this very moment with beta.1 coming out later today or early next week).

Please point me to any incorrect docs which led you to installing alpha3 on 20.04, those need to be corrected. In essence 2.5 alphas {1,2,3} were Ubuntu 18.04 releases which should be forgotten.
