### ISSUE TITLE
problem with TLSv1.3 nginx in ubuntu 16 // presentation is not loaded when we remove TLSv1.3

### ISSUE THREAD

**Issue by cod3r0k** [bigbluebutton/bigbluebutton#14563]
BBB 2.3 and 2.4 have some problems with our users who get stuck in the entrance with three loading dots.

So, we switch to BBB2.2 which they don't have any the same problem before. 

When we install ubuntu 16 and BBB 2.2.30, the SSL is installed successfully but nginx is going down because it can't support TLS1.3. Therefore, we remove TLS1.3 and restart nginx and everything is OK. But the presentation PDF or pane is not loaded in this case.

Could you help me, how can I fix BBB 2.2 problem?

**Comment by ffdixon** [comment]
Are these users getting stuck on https://test.bigbluebutton.org/?

**Comment by cod3r0k** [comment]
> Are these users getting stuck on https://test.bigbluebutton.org/?

Yes, last week some of them again said that they can't login in BBB 2.5.0-alpha.6 . (As you know, after about 15 min, the problem is solved automatically... in this period of time, the RAM and CPU is minimum and the limited resource is not reason)

Do you have any solution for TLSv1.3 in Nginx which has an error? 

I check many web pages which show how to install TLSv1.3 in ubuntu 16.04, but they did not work well.
