### ISSUE TITLE
Enhacement of getMeetingInfo api Call

### ISSUE THREAD

**Issue by unesco-iesalc** [bigbluebutton/bigbluebutton#14574]
Many times it is necessary to know the time that the participants in a meeting are connected.
The getMeetingInfo() call returns the attendees, but not the time they were connected to the meeting.

The bbb hosting solution provides it as a external statistic, but is not convenient to an integration.

**Comment by hostbbb** [comment]
you can send webhook callback on any event like join, to post back to your integration everytime someone joins, or access the the learning dashboard data to extract live meeting info
