### ISSUE TITLE
an option to disable built in noise reduction, auto gain and echo cancelation

### ISSUE THREAD

**Issue by audioses** [bigbluebutton/bigbluebutton#14576]
Hello there,
Is it possible to add options to toggle noise reduction, autogain and echo cancelation?
As far as I know BBB uses WebRTC and I found this artical that might help.
https://stackoverflow.com/questions/37326846/disabling-auto-gain-conctrol-with-webrtc-app/37332145#3
This would really help in situations where auto noise reduction makes the sound worse instead of helping.
Thank you so much.

**Comment by mariogasparoni** [comment]
We do have this option. Here's how to enable/disable audio filters.
![audio](https://user-images.githubusercontent.com/1780868/157689844-e5b02a10-4db0-4ea5-b863-ec4c3bf60e86.gif)


Related to #11331 and #13299

**Comment by audioses** [comment]
Hello there,
  Thanks for the reply. I did search that setting but couldnt find it.
  Since I'm visually impaired, I couldnt see where the setting is from the image you've attached. Can you explain where the settings is with text?
  Thanks :)

**Comment by antobinary** [comment]
HI @audioses 

@mariogasparoni recorded and posted a short animation showing that there is an "Audio filters for microphone" toggle in the HTML5 client settings.

To reach it you can open the Settings (three dots menu which can be opened via Alt+O followed by selecting menu Settings). The toggle in quesiton is part of the Application set of options, which is the one displayed when the Settings modal loads. So three dot menu, followed by Settings, followed by setting the "Audio filters for microphone" modal to be off (it is on by default and is listed in second position, under Animations toggle). And then finally, saving the change to exit the Settings.

Please let us know if any further assitance would be beneficial!

**Comment by audioses** [comment]
hello there,
i found the option in question.
Thank you for explaining it in more detail.

iPhone’umdan gönderildi
