### ISSUE TITLE
[2.4] Race condition in (many) users joining from waiting room

### ISSUE THREAD

**Issue by schrd** [bigbluebutton/bigbluebutton#14582]
**Describe the bug**
When there are many users waiting in the waiting room (150), many of them can't load the HTML5 client. Failed clients see a blue screen without dots and get a stacktrace similar to this one:

~~~
Exception in queued task TypeError: i[h.meetingID][h.userID] is undefined
    T https://bbb-server/html5client/d13d9965f0d30ea95c841b5e157517ca9def8c8d.js?meteor_js_resource=true:375
    El https://bbb-server/html5client/d13d9965f0d30ea95c841b5e157517ca9def8c8d.js?meteor_js_resource=true:61
    Ys https://bbb-server/html5client/d13d9965f0d30ea95c841b5e157517ca9def8c8d.js?meteor_js_resource=true:61
    unstable_runWithPriority https://bbb-server/html5client/d13d9965f0d30ea95c841b5e157517ca9def8c8d.js?meteor_js_resource=true:79
    ci https://bbb-server/html5client/d13d9965f0d30ea95c841b5e157517ca9def8c8d.js?meteor_js_resource=true:61
    Xs https://bbb-server/html5client/d13d9965f0d30ea95c841b5e157517ca9def8c8d.js?meteor_js_resource=true:61
    Rs https://bbb-server/html5client/d13d9965f0d30ea95c841b5e157517ca9def8c8d.js?meteor_js_resource=true:61
    hi https://bbb-server/html5client/d13d9965f0d30ea95c841b5e157517ca9def8c8d.js?meteor_js_resource=true:61
    unstable_runWithPriority https://bbb-server/html5client/d13d9965f0d30ea95c841b5e157517ca9def8c8d.js?meteor_js_resource=true:79
    ci https://bbb-server/html5client/d13d9965f0d30ea95c841b5e157517ca9def8c8d.js?meteor_js_resource=true:61
    hi https://bbb-server/html5client/d13d9965f0d30ea95c841b5e157517ca9def8c8d.js?meteor_js_resource=true:61
    di https://bbb-server/html5client/d13d9965f0d30ea95c841b5e157517ca9def8c8d.js?meteor_js_resource=true:61
    Es https://bbb-server/html5client/d13d9965f0d30ea95c841b5e157517ca9def8c8d.js?meteor_js_resource=true:61
    La https://bbb-server/html5client/d13d9965f0d30ea95c841b5e157517ca9def8c8d.js?meteor_js_resource=true:61
    added https://bbb-server/html5client/d13d9965f0d30ea95c841b5e157517ca9def8c8d.js?meteor_js_resource=true:375
    added https://bbb-server/html5client/d13d9965f0d30ea95c841b5e157517ca9def8c8d.js?meteor_js_resource=true:307
    added https://bbb-server/html5client/d13d9965f0d30ea95c841b5e157517ca9def8c8d.js?meteor_js_resource=true:307
    a https://bbb-server/html5client/d13d9965f0d30ea95c841b5e157517ca9def8c8d.js?meteor_js_resource=true:307
    runTask https://bbb-server/html5client/d13d9965f0d30ea95c841b5e157517ca9def8c8d.js?meteor_js_resource=true:1
    flush https://bbb-server/html5client/d13d9965f0d30ea95c841b5e157517ca9def8c8d.js?meteor_js_resource=true:1
    drain https://bbb-server/html5client/d13d9965f0d30ea95c841b5e157517ca9def8c8d.js?meteor_js_resource=true:1
    resumeObservers https://bbb-server/html5client/d13d9965f0d30ea95c841b5e157517ca9def8c8d.js?meteor_js_resource=true:307
    endUpdate https://bbb-server/html5client/d13d9965f0d30ea95c841b5e157517ca9def8c8d.js?meteor_js_resource=true:331
    e https://bbb-server/html5client/d13d9965f0d30ea95c841b5e157517ca9def8c8d.js?meteor_js_resource=true:321
    _performWrites https://bbb-server/html5client/d13d9965f0d30ea95c841b5e157517ca9def8c8d.js?meteor_js_resource=true:321
    _performWrites https://bbb-server/html5client/d13d9965f0d30ea95c841b5e157517ca9def8c8d.js?meteor_js_resource=true:321
    _flushBufferedWrites https://bbb-server/html5client/d13d9965f0d30ea95c841b5e157517ca9def8c8d.js?meteor_js_resource=true:321
    bindEnvironment https://bbb-server/html5client/d13d9965f0d30ea95c841b5e157517ca9def8c8d.js?meteor_js_resource=true:1
~~~

**To Reproduce**
1. Open a meeting, set guest policy to ask moderator
2. Join many bots as viewer
3. Join in a different browser as viewer to later see the error
4. let all guests join.

In my tests all bots are connected in a gigabit network, server has more bandwidth. Having more bots increases the probablility to see the error. I got the following results:

| total bots | failed bots |
| ------------ | --------------|
| 40 | 8 |
| 90 | 30 |
| 140 | 130 |

**Expected behavior**
Everyone should be able to participate

**BBB version:**
BBB 2.4.4 + Patch from PR #14334

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Chrome, Firefox
 - Version Chrome 99, Firefox 91 ESR

**Comment by ffdixon** [comment]
Very interesting -- would you be able to run this test on 2.5-alpha?

**Comment by schrd** [comment]
> Very interesting -- would you be able to run this test on 2.5-alpha?

yes but probably not this weekend. Currently I don't have a 2.5 machine setup yet.

**Comment by schrd** [comment]
@Tainan404 if you would like to reproduce it on your server, try the following steps:

* clone https://gitlab.com/schrd/bbb-bench, `cd bbb-bench`
* copy `server.config.json.example` to `server.config.json`, adjust API and secret
* create a python3 virtualenv and install python libs:
  * `python3 -mvenv /tmp/bbb-bench`
  * `/tmp/bbb-bench/bin/pip install -r requirements.txt`
* run the botserver on a machine that can be reached by the bots:
  * `/tmp/bbb-bench/bin/python botserver.py`
* copy `client.config.json.example` to `client.config.json`, adjust the uri to point to the botserver machine
* deploy `/tmp/bbb-bench`, the `bbb-bench` git repo, `client.config.json` to the bot machines. A bot machine can run multiple browser/bot instances. Adjust the parameter `instances` in client.json. It will automatically limit the number of browser instances by the amount on memory and the number of cores available.
* The bot machines need an installed chrome/chromium + chromedriver
* On the bot machines run the bot instances by running `/tmp/bbb-bench/bin/python bot_user_client.py`
* In the console of the botserver you should see something like 
  ~~~
  1 received {"action": "type", "type": "bot", "name": "botmachinexy-2"}
  notify users: {"users": 0, "bots": 139}
  2 received {"status": "ok"}
  ~~~
* create a meeting `Benchmark` using API mate. Attendee password must be `ap`
* join this meeting as moderator, set guest policy to `ask moderator`
* run `/tmp/bbb-bench/bin/python issue-14582-part1.py`
* wait until all bots appear in the waiting room
* let everyone in at once
* run `/tmp/bbb-bench/bin/python issue-14582-part2.py`
* All bots should join by audio now
* If the HTML5 client does not load, you'll see timeouts after ca 60s and stack traces ending in
  ~~~
  ...
      self._wait_for((By.CSS_SELECTOR, '.ReactModal__Overlay'), 180)
  File ".../bbb-bench/bbb_client.py", line 57, in _wait_for
    WebDriverWait(self.browser, timeout).until(element)
  File "/tmp/bbb-bench/lib64/python3.6/site-packages/selenium/webdriver/support/wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
  ~~~

I know that this is not simple to setup. Let me know if I can help.

I run the bots on a fleet of Ryzen desktop PCs when they are not in use, up to 1.25 browsers per core is okayish.

**Comment by schrd** [comment]
I commented out https://github.com/bigbluebutton/bigbluebutton/blob/v2.4.x-release/bigbluebutton-html5/.meteor/packages#L12 and built packages and got the following stacktrace:

~~~
TypeError: users[Auth.meetingID][Auth.userID] is undefined
    Adapter adapter.jsx:99
    Ii modules.js:7170
    Vj modules.js:7216
    unstable_runWithPriority modules.js:32338
    cg modules.js:7081
    Dj modules.js:7216
    yj modules.js:7198
    fg modules.js:7082
    unstable_runWithPriority modules.js:32338
    cg modules.js:7081
    fg modules.js:7082
    gg modules.js:7081
    Ig modules.js:7189
    zh modules.js:7122
    added adapter.jsx:41
    added minimongo.js:3194
    added minimongo.js:2646
    wrapCallback minimongo.js:1715
    runTask meteor.js:854
    flush meteor.js:883
    drain meteor.js:892
    resumeObservers minimongo.js:2261
    endUpdate mongo.js:358
    method ddp-client.js:593
    _performWrites ddp-client.js:1497
    _performWrites ddp-client.js:1496
    _flushBufferedWrites ddp-client.js:1459
    bindEnvironment meteor.js:1236
modules.js:7168:195
    Ci modules.js:7168
    callback modules.js:7185
    Cg modules.js:7090
    Ji modules.js:7171
    Sj modules.js:7214
    unstable_runWithPriority modules.js:32338
    cg modules.js:7081
    Jj modules.js:7207
    yj modules.js:7198
    fg modules.js:7082
    unstable_runWithPriority modules.js:32338
    cg modules.js:7081
    fg modules.js:7082
    gg modules.js:7081
    Ig modules.js:7189
    zh modules.js:7122
    added adapter.jsx:41
    added minimongo.js:3194
    added minimongo.js:2646
    wrapCallback minimongo.js:1715
    runTask meteor.js:854
    flush meteor.js:883
    drain meteor.js:892
    resumeObservers minimongo.js:2261
    endUpdate mongo.js:358
    method ddp-client.js:593
    _performWrites ddp-client.js:1497
    _performWrites ddp-client.js:1496
    _flushBufferedWrites ddp-client.js:1459
    bindEnvironment meteor.js:1236
~~~

If I inspect this in the browser, it seems like the error happens there: https://github.com/bigbluebutton/bigbluebutton/blob/v2.4.x-release/bigbluebutton-html5/imports/ui/components/components-data/chat-context/adapter.jsx#L99

**Comment by antobinary** [comment]
Let's try to reproduce this on 2.6. 2.4 security patches only at this point..

**Comment by aogilvie** [comment]
I have this issue on 2.3.1. If I use an API create, then access with 4 machines at the same time using the same join API call I can (not always, but) often trigger this error. I noted the machine that had this issue was already experiencing high RAM usage issues from redis (and, no surprise, some Java code) when looking at htop.

**Comment by aogilvie** [comment]
Haha no. Just letting you know the bug is in there for a while :)

**Comment by aogilvie** [comment]
If you fix it I'll update :)

**Comment by paultrudel** [comment]
Hi @schrd would you be able to test this again on rc2 to see if you run into the same issue?

**Comment by antobinary** [comment]
In our tests https://github.com/bigbluebutton/bigbluebutton/pull/16620 resolved this issue. If able to reproduce in 2.6.0-rc.3 or later please report.
