### ISSUE TITLE
Camera thresholds/exclude floor holder: Webcam reset on floor holder change.

### ISSUE THREAD

**Issue by einhirn** [bigbluebutton/bigbluebutton#14580]
###Describe the bug
#13869 introduced the feature “exclude voice floor holder from camera quality limiter” which works in principle. However, we have observed that the webcams of some participants do a reset when they start talking. The webcam's LED shortly turns off and on and the participant's video freezes for 1-2 seconds. This is annoying in meetings with discussions and many switches between moderator and participants.

### To Reproduce
Start a meeting with as many webcam participants as are needed to activate the cam thresholds. Trigger a change in voice floor holder by talking in turns, each about 30 or so, and "loud" enough...

### Expected behavior
The video quality of the active speaker becomes better without any noticeable video hiccup.

### Actual behavior
The video of the active speaker freezes 1-2s before becomes better.

**BBB** version (optional):
2.4.4. The problem could be observed with both kurento and mediasoup.

### Desktop (please complete the following information):
Window 10 21H2, Chrome 99, Webcam Logi Brio 4k

### Additional
The ability to change camera profiles for the active speaker is very good and should stay. We figured that the issue is with the resolution change, so maybe changing the threshold settings to just modify the encoding parameters might help. Also, adding a threshold before switching camera profiles could also be an improvement in discussions when the floor holder switches too easily, too quickly back and forth...

**Comment by prlanzarin** [comment]
Removing constraints dictionaries from camera profiles should alleviate the problem.
I don't think I'll add a debouncer to profile changes since there's already "one" (the floor change should be 2.5 or 3s delayed), but it might be an option.

I'll consider whether to ignore re-applying constraints in the dynamic profile switching since that's the one which usually restarts the encoder. It wasn't initially like this in Chrome - encoder restarts were generally unnoticeable (apart from generating client CPU spikes). I have noticed the blackout behavior ~lately (circa 95-6?), though; c'est la vie.

**Comment by prlanzarin** [comment]
@einhirn See #14592

**Comment by einhirn** [comment]
For the sake of completeness: I can also reproduce the issue in the "share camera" dialogue, it just takes a while after changing the camera profile with a current chrome - the image disappears for a while and I also see the LED on the camera turn off and on again...

**Comment by prlanzarin** [comment]
> For the sake of completeness: I can also reproduce the issue in the "share camera" dialogue, it just takes a while after changing the camera profile with a current chrome - the image disappears for a while and I also see the LED on the camera turn off and on again...

That's expected as the profile switching in video-preview is a completely different mechanism - it re-runs getUserMedia (intentionally). Therefore unrelated to this issue.

**Comment by prlanzarin** [comment]
@einhirn have you noticed improvements after the tentative fix landed on v2.4.6?

**Comment by einhirn** [comment]
Sorry, we didn't roll out 2.4.6 in Production yet, so we can't really tell currently. Sorry.

**Comment by ffdixon** [comment]
> Sorry, we didn't roll out 2.4.6 in Production yet, so we can't really tell currently. Sorry.

Please do!  We would welcome your feedback on this release.

**Comment by einhirn** [comment]
We've switched to 2.4.7 now, and have noticed that the situation is indeed improved. We have configured a 10 second delay before switching and haven't noticed freezing and or re-initialization of cameras during resolution changes.
