### ISSUE TITLE
BBB Turn Server Setup not working with doc instructions

### ISSUE THREAD

**Issue by jonnyfux** [bigbluebutton/bigbluebutton#14597]
**Describe the bug**
I set up a TURN Server with the bbb-install.sh and also confirmed with the current [BBB doc](https://docs.bigbluebutton.org/admin/setup-turn-server.html) that everything was set up following the recommended procedure. 

In the part where coturn is setup ([here](https://docs.bigbluebutton.org/admin/setup-turn-server.html#configure-coturn)) it says to _Replace <IP> with the external IP of your TURN server_. Also if it is behind NAT _external-ip=172.17.19.120_ must be added. 
So I replaced all <IP> with my external IP (elastic IP)

```
listening-ip=<EXTERNAL-IP>
relay-ip=<EXTERNAL-IP>
external-ip=<EXTERNAL-IP>

```
A connection to the BBB with Firefox and media.peerconnection.ice.relay_only: true fails with an ICE Error. In the coturn log i get

```
bind: Cannot assign requested address
0: Trying to bind fd 14 to <EXTERNAL-IP:3478>: errno=99
Cannot bind local socket to addr: Cannot assign requested address
```

If I now comment out listening-ip and relay-ip and only leave the external-ip, it works smoothly. 

**Installation type**
I used the bbb-install script?

**Firewall and IP address type**
Behind a NAT of AWS with elastic IP.

**Comment by MBM1607** [comment]
@jonnyfux  I am facing this exact issue. Did you managed to resolved it?
