### ISSUE TITLE
Remaining recorded session learning dashboard information after deleting the recorded session

### ISSUE THREAD

**Issue by iRealDream** [bigbluebutton/bigbluebutton#14605]
I recently set the LearningDashboardCleanupDelayInMinutes option to 0 to save the learning dashboard information, and everything is fine.
The problem is that when I delete the recording, the learning dashboard information about that recording remains.
It is better to change the system so that by deleting the recording, the learning dashboard information will also be deleted.

**Comment by ffdixon** [comment]
The storage of dashboard and deletion of recordings are separate systems.  Is there a large enough number for holding onto the Learning Analytics Dashboard that implements you use case, while still enabling BigBlueButton server to delete the data after a given time?

**Comment by ccomincini** [comment]
> The storage of dashboard and deletion of recordings are separate systems. Is there a large enough number for holding onto the Learning Analytics Dashboard that implements you use case, while still enabling BigBlueButton server to delete the data after a given time?

Hi Fred, I don't know if this can be a good idea, maybe too simple but... Why not u   the same cron.daily script that deletes raw data and presentation to make the deletion of learning analytics data synchronous with other deletions?

**Comment by ccomincini** [comment]
Is there any idea to implement in API the export of the learning analytics of a bbb session?
