### ISSUE TITLE
2.5: net-tools not installed

### ISSUE THREAD

**Issue by danimo** [bigbluebutton/bigbluebutton#14623]
**Describe the bug**
some install scripts require the `ifconfig` and `route` commands from `net-tools`, which is long deprecated and no longer default in Ubuntu 20.04. 

Suggestion: require `net-tools` as a temporary workaround in all packages that call `ifconfig` or `route`, then replace their by their `ip address` and `ip route` counterparts, since `iproute2` is part of the default installation.

**To Reproduce**
Install 2.5 on default Ubuntu 20.04 cloud image packages, see installation fail.

**Comment by danimo** [comment]
Uses of `route`:


```
build/deb-helper.sh
bigbluebutton-config/bin/bbb-conf
```

Uses of `ipconfig`:

```
build/deb-helper.sh
bigbluebutton-config/bin/apply-lib.sh
bigbluebutton-config/bin/bbb-conf
```

**Comment by antobinary** [comment]
And drop the 2 `need_pkg net-tools` from https://github.com/bigbluebutton/bbb-install

**Comment by antobinary** [comment]
Looks like @danimo has started making some of these changes. I will [temporarily] assign this to him so it does not look vacant

**Comment by danimo** [comment]
I can't really test this in its entirety, so I need a reviewer.

**Comment by antobinary** [comment]
Is this issue the same as https://github.com/bigbluebutton/bigbluebutton/issues/12262 @danimo ?

**Comment by danimo** [comment]
Yes
