### ISSUE TITLE
Upgrade from 2.3 to 2.4 recordings not playing in mobile browsers but desktop browsers work correctly

### ISSUE THREAD

**Issue by mojtaba82** [bigbluebutton/bigbluebutton#14624]
**Describe the bug**
After upgrade from 2.3 to 2.4, mobile browsers like chrome and firefox  dont play recordings but desktop browsers work correctly.
**To Reproduce**
1. Upgrade from 2.3 to 2.4
2. record a meeting
3. Play recording in any mobile browsers
4. Browser just show white page

**Expected behavior**
Browser play recorded meeting correctly
**Actual behavior**
Browser just show white page

**Smartphone (please complete the following information):**
 - Device: [redmi note 8 pro]
 - OS: [android 11]
 - Browser [chrome]
 - Version [99]

I upgrade from 2.3 to 2.4 by below command
```
wget -qO- https://ubuntu.bigbluebutton.org/bbb-install.sh | bash -s -- -v bionic-24 -s bbb.myserver.com -e myemail@gmail.com -w
```

**Comment by bigemme** [comment]
Same problem here with the difference that I can't see the recordings published on chrome and firefox (desktop pc) (on edge and safari everything works).
BigBlueButton Server 2.4.5 (3018) on Ubuntu 18.04.6 LTS.
Here is the error I get (chrome v: 99.0.4844.74 and firefox v: 98.0.1):

![error_firefox](https://user-images.githubusercontent.com/78846246/158977843-8c88c01a-46a9-4fc2-a88b-915098dd11dd.png)

**Comment by mojtaba82** [comment]
@ffdixon Thanks for your reply.
My device is android device not ios, and I check on several android device but all of them not playback recordings. Before upgrade everything was ok. unfortunately mobile browsers not have console part to I see what error cause this problem. What is location of log of playpack in server?

**Comment by natas123** [comment]
Same problem here @bigemme,

With a clean installation of ubuntu 18.04.6 installing bbb 2.4.5 with the bb-install tool when making a recording and then watching it gives me the error "invalid language tag: Es_es" and I can't see the recordings in Chrome and Firefox.

Thanks

**Comment by bigemme** [comment]
@natas123 I opened a new issue here: https://github.com/bigbluebutton/bigbluebutton/issues/14625
We hope to be able to solve it soon ...

**Comment by mojtaba82** [comment]
@pedrobmarin 
when 2.4.6 version is release to apply this fix?

**Comment by pedrobmarin** [comment]
No idea. I left the other issue opened since it would be good for someone else to test it before releasing a new version

**Comment by mojtaba82** [comment]
I apply this
```
git clone https://github.com/bigbluebutton/bbb-playback.git
cd bbb-playback
npm install
./deploy.sh
```
but problem insist. desktop browsers are ok but in android phones this problem exists.

**Comment by mojtaba82** [comment]
I check again. Problem is solved.
Thank you
