### ISSUE TITLE
[2.4.5] View recordings issue with the plugin for moodle (BigBluebuttonBN) on chrome and firefox.

### ISSUE THREAD

**Issue by bigemme** [bigbluebutton/bigbluebutton#14625]
**Describe the bug**
When I try to view the recordings using this link (via the bigbluebuttonBN plugin for moodle):

https://[my_site]/playback/presentation/2.3/[internal_meeting_id]

I get a blank page and this error (only on chrome and firefox, edge and safari both work):

![error_firefox](https://user-images.githubusercontent.com/78846246/158990643-343ee1fc-11e7-459e-a3fd-d5d15fb03705.png)

**To Reproduce**
1. Go to https://[your_site]/playback/presentation/2.3/[internal_meeting_id]
2. See error

**Expected behavior**
Viewing the recording

**Actual behavior**
I get a blank page and the error above

**Screenshots**
See above

**Desktop**
 - OS: Windows, Mac
 - Browser Chrome, Firefox
 - Version chrome:  99.0.4844.74 firefox: 98.0.1

**Additional context**
BigBlueButton Server 2.4.5 (3018)
BigBlueButtonBN 2.4.4 (2019101011)

The issue does not occur on bigbluebutton 2.2.36 (the versions of the other sw unchanged)

**Comment by bigemme** [comment]
@pedrobmarin did you solve the problem? Could you provide the step-by-step solution?
Thanks

**Comment by pedrobmarin** [comment]
You can try running the playback fixes before the new release following these instructions https://github.com/bigbluebutton/bbb-playback#bbb-playback

**Comment by bigemme** [comment]
with 

`./deploy.sh`

i get this:

![deploy](https://user-images.githubusercontent.com/78846246/159015538-4c344c7f-43fd-41f3-b487-cd4fe7e9eaca.png)

**Comment by pedrobmarin** [comment]
Hmmm, that's something I would expect from react-scripts v5+

What Node version is your server running?

**Comment by bigemme** [comment]
> Hmmm, that's something I would expect from react-scripts v5+
> 
> What Node version is your server running?

12.22.11

**Comment by pedrobmarin** [comment]
PS.: Not sure why webpack 5 is being invoked. I'd need more time to investigate this.

**Comment by bigemme** [comment]
Ok, after uploading your files I get this (I don't see the recording):

![novideo](https://user-images.githubusercontent.com/78846246/159023170-10905fb9-3b3b-43f6-86a2-8bbba76f3fcf.png)

**Comment by bigemme** [comment]
> 

This is desktop browser (chrome and firefox)

**Comment by pedrobmarin** [comment]
Any hints at the console log?
