### ISSUE TITLE
Gems at build time for bbb-record-core

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#14631]
We currently install gems in after-install.sh

https://github.com/bigbluebutton/bigbluebutton/blob/v2.5.x-release/build/packages-template/bbb-record-core/after-install.sh#L28-L50

The idea is to move this process to build.sh and ship the gems within bbb-record-core package.

Originally reported in https://github.com/bigbluebutton/bigbluebutton/issues/8455#issuecomment-1028059880

**Comment by ffdixon** [comment]
This would be good for 2.5
