### ISSUE TITLE
Installation script has to modify STUN-server in the sip.js file

### ISSUE THREAD

**Issue by evgkabsusu** [bigbluebutton/bigbluebutton#14633]
**Describe the bug**
/usr/share/meteor/bundle/programs/web.browser/app/compatibility
/usr/share/meteor/bundle/programs/web.browser.legacy/app/compatibility
sip.js file has hardcoded link to stun.l.google.com
stun/turn configuration is not used in the sip.js file

**Installation type**
bbb-install

**Firewall and IP address type**
public IP

**Console output**
none

**Additional context**
1. Go to /usr/share/meteor/bundle/programs/web.browser/app/compatibility
2. search text stun.l.google.com

Usually stun.l.google.com is reachable. But sometimes IP-addresses are filtered due to government restrictions and users may encounter issues.

<img width="1103" alt="Снимок экрана 2022-03-19 в 17 09 12" src="https://user-images.githubusercontent.com/88573734/159120528-08ee6fc0-4c1e-40cc-8f9f-63d354b0e6cc.png">

**Comment by basisbit** [comment]
@evgkabsusu last time I checked, this does not actually get used by the client. Did you actually see the webbrowser trying to connect to stun.l.google.com:19302 after configuring TURN as specified at https://docs.bigbluebutton.org/admin/setup-turn-server.html#configure-bigbluebutton-to-use-your-turn-server ?

**Comment by prlanzarin** [comment]
@basisbit is correct. If you haven't configured STUN nor TURN addresses in bbb-web, _no_ server will be used at all. The default is _always_ overridden (with empty arrays if it must).
