### ISSUE TITLE
Add Lock Setting For Whiteboard Private Cursor Mode (Multiuser)

### ISSUE THREAD

**Issue by KDSBrowne** [bigbluebutton/bigbluebutton#14636]
**Is your feature request related to a problem? Please describe.**
The problem is instructors may use the multiuser whiteboard in the following scenario.
1) Instructor uploads a slide with 4 images.
2) Instructor asks a question related to the slide, enables multi user whiteboard and asks students to move their cursor
over the image on the slide for the best answer to the question.

Issue: Viewers can see all the cursors on the whiteboard so the instructor can't determine which students are just following the
other cursors (essentially copying answers).

**Describe the solution you'd like**
Add a lock setting that will only render the cursor for the instructor and the current viewer when enabled.

**Comment by hiroshisuga** [comment]
Just for your information, the PR #11776 has been written exactly for that purpose (issue raised at #10088), although it hides not only the cursor, but also the annotations, which makes sense in my opinion. But I guess you want a more elegant implementation;-).
