### ISSUE TITLE
we need to periodically delete these records with a cron job.

### ISSUE THREAD

**Issue by yazilimevde** [bigbluebutton/bigbluebutton#14634]
Thank you Manish Katyan for using your bbb-mp4. In order to prevent the disk from getting full, we need to periodically delete these records with a cron job. Can you share the batch script that deletes the created records in a certain period. We are very new to batch scripting in Ubuntu and we need your help to make mistakes.

**Comment by antobinary** [comment]
Hi @yazilimevde ,

Looks like this is not a valid issue. Perhaps you wanted to paste this elsewhere. If you have an issue to report to BigBlueButton, please follow the templates provided
