### ISSUE TITLE
Error 1107. not able to reconnect

### ISSUE THREAD

**Issue by Braehler** [bigbluebutton/bigbluebutton#14645]
**Describe the bug**
Since a few days the get the feedback of our teachers, that during their lessons the connection gets canceld and they are not able to reconnect. The error 1107 is thrown.
And sometimes the audio seems to be delayed a lot

**To Reproduce**
1. Go to a meeting of your choise
2. Start the meeting with about 20 viewers and one moederator
3. Share webcam and share audio as moderator
4. Start the lesson and wait for the error 1107 to appear. This seems to be "random" Sometimes the error appears after 5 minutes and sometimes after 30 minutes.
5. Try to share webcam and adio again, it will not work

**Expected behavior**
No error, or be able to reconnect if webcam and audio is canceld.

**Actual behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS:  Windows10
 - Browser: Chrome, FireFox
 - Version: both latest stable

**Smartphone (please complete the following information):**
 - Browser [e.g. stock browser, Safari]

**Additional context**
BBB Server: 2.4.0
hardware: Intel® Core i7-6700 Quad-Core processor
64 GB DDR4 RAM
two 512 GB NVMe SSDs
Connection: | 1 GBit/s port
Guaranteed bandwidth: 1 GBit/s

**Comment by ffdixon** [comment]
> BBB Server: 2.4.0

Could you upgrade to 2.4.5 (the latest release at the time of this writing) and let us know if you still encounter the same issues.

**Comment by Braehler** [comment]
@ffdixon 
We jsut set up a new server based on the recomendation of the AX51 server on Hetzter and installed the latest 2.4.5 Version of BBB.
I´m now waiting for feedback of our teachers regarding the issue

**Comment by ffdixon** [comment]
Sounds good -- let us know the results.  Also, can you have users who are encountering the error test against https://test.bigbluebutton.org/.

**Comment by ffdixon** [comment]
In the future, please post to https://groups.google.com/g/bigbluebutton-setup and the community will help you there.  If in helping we encounter a bug in BigBlueButton, we'll open an issue here to track it.
