### ISSUE TITLE
Chrome 100 cannot open microphone

### ISSUE THREAD

**Issue by donbowman** [bigbluebutton/bigbluebutton#14644]
**Describe the bug**

Prior to upgrading chrome to 100 I was using bbb w/o trouble. Now my installation works in firefox, but not chrome with respect to microphone.

I have tried resetting mic permissions, clearing state.

problem reproduces with test24.bigbluebutton.org. When I click the mic-mode on attach to session, below errors pop up in the javascript console.

A dialog appears with:
"There was an issue with your media devices
Did you give permission for access to your microphone? Note that a dialog should appear when you try to join audio, asking for your media device permissions, please accept that in order to join the audio conference. If that is not the case, try changing your microphone permissions in your browser's settings."

console shows:

sip.js?v=2539:9594 Mon Mar 21 2022 21:53:17 GMT-0400 (Eastern Daylight Time) | sip.SessionDescriptionHandler | SessionDescriptionHandler.getDescription failed - NotFoundError: Requested device not found
print @ sip.js?v=2539:9594
sip.js?v=2539:9594 Mon Mar 21 2022 21:53:17 GMT-0400 (Eastern Daylight Time) | sip.Inviter | Session.getOffer: SDH getDescription rejected...
print @ sip.js?v=2539:9594
sip.js?v=2539:9594 Mon Mar 21 2022 21:53:17 GMT-0400 (Eastern Daylight Time) | sip.Inviter | Requested device not found

**To Reproduce**
1. Go to test24.bigbluebutton.org
2. Click on microphone
3. Observe error

**Expected behavior**

I expect to be challenged to provide mic permission (or just accepted as is)

**Actual behavior**

No challenge, no mic.

**Screenshots**

**BBB version:**

bbb 2.4.5 for my install, but test24.bigbluebutton.org shows as well.

**Desktop (please complete the following information):**
 - OS: Ubuntu 21.10 (kde)
 - Browser google-chrome-end
 - Version 100.0.4896.46-1

**Additional context**

**Comment by mariogasparoni** [comment]
Hi @donbowman, thanks for reporting it.
I can't reproduce it on test24.bigbluebutton.org, neither test.bigbluebutton.org

Wondering if this might be related to your device settings.
Could you please check if you devices are available in this test page ?
https://webrtc.github.io/samples/src/content/devices/input-output/


Tested using Google Chrome Beta: Version 100.0.4896.46 (Official Build) beta (64-bit)
OS: Ubuntu Focal 20.04

**Comment by donbowman** [comment]
So I apologise, indeed, its something w/ this chrome(?) and profile.
the webrtc... test, it shows no microphone. However, e.g. Google Meet still works.
I cleared the profile and restrted, and now webrtc works as does bbb. So, not sure the root cause,
but its back functioning.
