### ISSUE TITLE
Whiteboard ipad pencil problem 

### ISSUE THREAD

**Issue by blueiceprj** [bigbluebutton/bigbluebutton#14641]
**Describe the bug**
The problem drawing with IPad pencil

**To Reproduce**

**Expected behavior**

**Actual behavior**

**Screenshots**

**BBB version:**
BigBlueButton Server 2.4.5

**Smartphone (please complete the following information):**
 - Device: [e.g. iPad]
 - OS: [IOS]
 - Browser [Safari]
 - Version [2.4.5]

**Additional context**
A

https://user-images.githubusercontent.com/1829975/159299705-985c515b-260a-4711-8457-961d3cdc8a38.mp4

dd any other context about the problem here.

**Comment by antobinary** [comment]
With BBB 2.6+ this has likely been changed as we replaced the entire whiteboard with a different project - tldraw.
I will merge this into issue into https://github.com/bigbluebutton/bigbluebutton/issues/15976 as both of them concern the use of a stylus/pen on iOS
