### ISSUE TITLE
virtualBackgrounds

### ISSUE THREAD

**Issue by datapack** [bigbluebutton/bigbluebutton#14663]
Hello,
I am trying to add new virtual background.
I am running BBB 2.4.4
Following the guide [https://docs.bigbluebutton.org/admin/customize.html...](https://docs.bigbluebutton.org/admin/customize.html?fbclid=IwAR2OpXWgDvo1yz8vYh6CW5TnJRJbYlZFDWr1O72JlYZPkhm1B4azZTqpfA4#use-custom-images-for-virtual-background) I can't find on my server the configuration file for the virtual backgrounds /etc/bigbluebutton/bbb-html5.yml:
I need to create the file manually and it works.
![2022_03_24_12_01_12_BigBlueButton_Customize](https://user-images.githubusercontent.com/1810382/159892864-188af6a8-52cc-41cc-bcf1-d7f3c2aef0f3.png)
![2022_03_24_12_00_51_C_Windows_System32_drivers_etc_hosts_Notepad_](https://user-images.githubusercontent.com/1810382/159892867-39d4ee68-1a73-4e6c-aab9-2d3c4bd37c0c.png)

**Comment by antobinary** [comment]
Hi @datapack 
You can create this file `/etc/bigbluebutton/bbb-html5.yml` -- it is the first override you've needed, so it doesn't exist yet
