### ISSUE TITLE
incorrect welcome message code page

### ISSUE THREAD

**Issue by ali-alhaidary** [bigbluebutton/bigbluebutton#14676]
**Describe the bug**
incorrect welcome message code page

**To Reproduce**
1. edit /usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties
2. defaultWelcomeMessage=السلام عليكم و رحمة الله وبركاته
3. save and restart
4. Go to a new session

**Expected behavior**
welcome message is السلام عليكم و رحمة الله وبركاته

**Actual behavior**
welcome message is Ø§ÙØ³ÙØ§Ù Ø¹ÙÙÙÙ Ù Ø±Ø­ÙØ© Ø§ÙÙÙ ÙØ¨Ø±ÙØ§ØªÙ

**Screenshots**
![Screenshot 2022-03-25 at 22-12-24 الدرس - Home Room - العرض الافتراضي للعرض](https://user-images.githubusercontent.com/75235623/160193345-6555e414-f852-4f2b-9da9-175822d5e645.png)

**BBB version:**
BigBlueButton Server 2.5.0-alpha.5 (130)

**Comment by ali-alhaidary** [comment]
Also, the invite text is not localized. I do not know if the is BBB issue or GL

**Comment by lonesomewalker** [comment]
1. your welcome message should be:
\u0627\u0644\u0633\u0644\u0627\u0645 \u0639\u0644\u064a\u0643\u0645 \u0648 \u0631\u062d\u0645\u0629 \u0627\u0644\u0644\u0647 \u0648\u0628\u0631\u0643\u0627\u062a\u0647
(remember to use native2ascii, as written explicitly in this config)

2. invitation text comes from greenlight, and depends on your language.

**Comment by ali-alhaidary** [comment]
> 1. your welcome message should be:
>        \u0627\u0644\u0633\u0644\u0627\u0645 \u0639\u0644\u064a\u0643\u0645 \u0648 \u0631\u062d\u0645\u0629 \u0627\u0644\u0644\u0647 \u0648\u0628\u0631\u0643\u0627\u062a\u0647
>        (remember to use native2ascii, as written explicitly in this config)
> 
>     2. invitation text comes from greenlight, and depends on your language.

I never needed anything in v2.4.x, just added the welcome message in Arabic in that file. And my default language is Arabic set from BBB server and GR gives the error 500 when changing to Arabic.
![Screenshot 2022-03-26 at 01-41-21 BigBlueButton](https://user-images.githubusercontent.com/75235623/160211440-63306579-c995-43ec-b486-10e8360a6459.png)

**Comment by ali-alhaidary** [comment]
defaultWelcomeMessage=مرحباً في المجلس

This is how we add the message in the file in 2.4. very simple and straight forward and it is displayed correctly.

**Comment by ali-alhaidary** [comment]
It seems that this issue is specific to GreenLight, as when we use BBB via moodle, the welcome message is passed correctly...

**Comment by cod3r0k** [comment]
Dear @ali-alhaidary , please follow the [main instruction](https://docs.bigbluebutton.org/admin/customize.html#change-the-default-welcome-message) for customization!

YOu can edit your welcome message in UTF-8 Unicode and then use the following code:

```
sudo apt-get install -y openjdk-8-jdk-headless 
native2ascii -encoding UTF8 bigbluebutton.properties bigbluebutton.properties
```

**Comment by ali-alhaidary** [comment]
Thank you @cod3r0k 
As this issue is specific to greenlight, and we are testing bbb v2.5 in production for small group of teachers/students with moodle which displays the message correctly, we prefer to stick to packages installed by bbb script only.
Again, thank you.

**Comment by ffdixon** [comment]
> we prefer to stick to packages installed by bbb script only.

Appreciate this Ali as it helps us test.  You closed the issue, but did you solve your problem?

**Comment by ali-alhaidary** [comment]
> > we prefer to stick to packages installed by bbb script only.
> 
> Appreciate this Ali as it helps us test. You closed the issue, but did you solve your problem?

@ffdixon bbb 2.5 is working as expected with moodle front end with few bugs that are already reported by others so I do not want to repeat and and dev team are taking very quick action as usual. As for greenloght, no, both issues were not solved.

**Comment by ali-alhaidary** [comment]
https://github.com/bigbluebutton/greenlight/issues/3351

**Comment by ali-alhaidary** [comment]
> > we prefer to stick to packages installed by bbb script only.
> 
> Appreciate this Ali as it helps us test. You closed the issue, but did you solve your problem?

It seems that the new greenlight version 2.12.5 sorted out the 500 page error issue, however, the UTF-8 Unicode issue is still there and we do not intend to install any extra packages as our front end is moodle and it is displayed correctly.
So many thanks...
