### ISSUE TITLE
Screenshare is not displayed to new users, if autoSwapLayout=true

### ISSUE THREAD

**Issue by einhirn** [bigbluebutton/bigbluebutton#14689]
**Describe the bug**
Screenshare is hidden when a user joins a meeting where a screen is being shared, if autoSwapLayout is set true.

**To Reproduce**

1. Set autoSwapLayout=true and smart layout as default
2. Join a meeting with moderator A
3. Start Screensharing
4. Join the meeting with user B
5. User B is receiving the screenshare stream, but it is hidden 

**Expected behavior**
The current screen sharing is also displayed to user B.

**Actual behavior**
The current screen sharing is hidden for user B.

**BBB version:**
2.4.4

**Additional context**
Maybe the the same problem exists with external videos. I found #14620 , but that relates to BBB 2.5. If this is the same bug, I request a backport to BBB 2.4

**Comment by antobinary** [comment]
Thanks for reporting!
@ramonlsouza let's consider backporting your fix #14620 to 2.4 as well

**Comment by einhirn** [comment]
We found another problem concerning this issue. There seems to be a timing component - Users that join less than 5 min after screenshare started will get the presentation area restored. For users joining later than 5 min after the presenter started the screenshare, the presentation area will stay minimized.

We were able to reproduce this behavior on 2.5.6 in our environment.

**Comment by ffdixon** [comment]
Can you reproduce this on https://demo.bigbluebutton.org/?

**Comment by einhirn** [comment]
Is there a demo host for "autoswaplayout=true"?
