### ISSUE TITLE
Update the way we handle annotation's versions in bbb-html5

### ISSUE THREAD

**Issue by mariogasparoni** [bigbluebutton/bigbluebutton#14688]
A new approach for this was introduced in 40b18b0, but unfortunately this was reverted in https://github.com/bigbluebutton/bigbluebutton/pull/14686  , since the original behavior (immediate text updates) was removed in that commit.

We might 40b18b0

These are the code reference to be updated.
https://github.com/bigbluebutton/bigbluebutton/blob/01866b2c3ededfa5916329ad0001c01aa857d383/bigbluebutton-html5/imports/ui/components/whiteboard/service.js#L58

https://github.com/bigbluebutton/bigbluebutton/blob/01866b2c3ededfa5916329ad0001c01aa857d383/bigbluebutton-html5/imports/ui/components/whiteboard/service.js#L84

**Comment by germanocaumo** [comment]
> @germanocaumo is this still relevant with tl;draw?

Nope, not anymore @antobinary
