### ISSUE TITLE
BigBlueButton does not support IPv6

### ISSUE THREAD

**Issue by bigbluebutton-issue-import** [bigbluebutton/bigbluebutton#1468]
Originally reported on Google Code with ID 713

```
BigBlueButton needs to start supporting IPv6 soon. IPv4 addresses are set to run out
some time in 2011. Doing this a few months earlier than we need to is probably a good
idea.

```

Reported by `Me.Snap` on 2010-11-05 18:16:23

**Comment by bonanza123** [comment]
is there any progress on this issue or advice how to (dirty)-fix it on a IPv6-only network?

**Comment by ffdixon** [comment]
Have you tried it? As I look at it, this issue is very old and may not be valid.

**Comment by kepstin** [comment]
I think BigBlueButton should currently work properly on mixed IPv6/IPv4 connections, using IPv6 when available. In particular, the latest versions of Firefox and Chrome both support webrtc audio over IPv6.

We haven't done any testing of BigBlueButton over an IPv6-only network at this point.

While an IPv6-only client might be ok, I don't think an IPv6 only server will work at this point - you'll run into several issues including the fact that our packing server is currently only available via IPv4.

**Comment by bonanza123** [comment]
Thanks for your very fast response, I just tried it for testing purposes on a virtual machine and here is the output: https://gist.github.com/bonanza123/96270fdc0eabc334f157

I guess there is, at least in bbb-conf, an issue which sets the IPs wrong.

**Comment by kepstin** [comment]
I don't expect that using an IPV6 address directly will work; please use a domain name instead.

**Comment by bonanza123** [comment]
Okay, I used the domain name now (name and IP censored/changed): https://gist.github.com/bonanza123/dd46fc3ae963fc394f02

bbb-conf seems to work, but still I only see nginx startpage or 404 errors

**Comment by bonanza123** [comment]
One more piece of information: If I enable port forwarding on the VM-host (which has a public IPV4) to the VM,e.g. from 8005 -> 80, then I see the bbb-startup correctly and everything seems to work.

Only if I directly use the public IPv6 from the VM nginx doesn't seem to serve the anyone.

**Comment by ffdixon** [comment]
Closing as all the server components -- Kurento, FreeSWITCH, nginx, and bbb-web all support IPV6.
