### ISSUE TITLE
[2.4.5] No recordings are displayed in greenlight

### ISSUE THREAD

**Issue by maxspyone** [bigbluebutton/bigbluebutton#14697]
Hello, I have the problem that no recordings are displayed in greenlight.
I think the recordings will not be processed / published.

**my setup**

- I installed on a new minimal Ubuntu 18.04.6 LTS (64-bit) server via the script:
```
wget -qO- https://ubuntu.bigbluebutton.org/bbb-install.sh | bash -s -- -v bionic-240 -s bbb.example.com -e notice@example.com -w -g
```
- sudo bbb-conf --check
<img width="616" alt="image" src="https://user-images.githubusercontent.com/125687/160779242-5a44504b-1be2-4d38-81ee-34ae40f23ccb.png">

- bbb-record --rebuildall

<img width="906" alt="image" src="https://user-images.githubusercontent.com/125687/160780539-294f9678-d595-410f-ac8b-83ffbf253e01.png">

**In `/var/bigbluebutton/recording/publish/presentation` there is nothing.**

Except for the recordings, bigbluebutton works perfectly.
I Hope someone can help me

**Comment by maxspyone** [comment]
Hello, 
with the support of the google group i did a lot of testing. It is not a configuration hiccup. 
The problem is ffmpeg! 
Is this a bug that i can post here?

**Here the manual attempt to convert a recording:**
dubidu@nooneknowthishost.com:~# ffmpeg -y -v warning -nostats -max_error_rate 1.0 -filter_complex color\=c\=white:s\=640x480:r\=15,trim\=end\=17.965 -an -codec libx264 -preset veryfast -crf 30 -force_key_frames expr:gte\(t,n_forced\*10\) -pix_fmt yuv420p -r 15 /var/bigbluebutton/recording/process/presentation/621a22a9bd8afac1a4dd3c0c5b74df6939ff8186-1648750911618/webcams_0.mp4
**ffmpeg: common/cpu.c:244: x264_cpu_detect: Assertion `!(cpu&(X264_CPU_SSSE3|X264_CPU_SSE4))' failed.
Aborted (core dumped)**

Here the recording process log file with the error:
![image](https://user-images.githubusercontent.com/125687/161378026-51f882a3-df29-424a-a6f3-f455f17c32b8.png)

**Comment by ffdixon** [comment]
Yes, that might be a bug :-).  What recording formats do you have installed?  Have you made any changes to BigBlueButton's default configuration?

**Comment by maxspyone** [comment]
Then please reopen this issue!

I use this install script: `wget -qO- https://ubuntu.bigbluebutton.org/bbb-install.sh | bash -s -- -v bionic-240 -s bbb.example.com -e notice@example.com -w -g`

I don't make any changes, everything is default. It was also an new empty Ubuntu 18.04.6 LTS (64-bit) Server
In the file /usr/local/bigbluebutton/core/scripts/presentation.yml i see the recording format webm

**Comment by vacant309** [comment]
Hi Everyone ,
i have the same problem with Ubuntu 18.04.6 and bbb bionic 240 , not see my recording in Greenlight . 
although I run the "bbb-record --rebuildall" command and sanity file it's ok ,  
the /var/bigbluebutton/recording/publish/presentation folder is empty .

thanks for the support 
Antonio

**Comment by maxspyone** [comment]
> Hi Everyone , i have the same problem with Ubuntu 18.04.6 and bbb bionic 240 , not see my recording in Greenlight . although I run the "bbb-record --rebuildall" command and sanity file it's ok , the /var/bigbluebutton/recording/publish/presentation folder is empty .
> 
> thanks for the support Antonio

Hello Antonio,
do you have the same error in the log file?
you can check an progress log file in the folder: /var/log/bigbluebutton/presentation
You can find more information in the google group: https://groups.google.com/g/bigbluebutton-setup/c/2WCvFXmRR1A

**I think ffmpeg doesn't want my server's cpu. Is there a way to work around this error. Either rewrite the config of ffmpeg so that all cpu are allowed? Or use another scpipt for editing videos?**

**Comment by vacant309** [comment]
> > Hi Everyone , i have the same problem with Ubuntu 18.04.6 and bbb bionic 240 , not see my recording in Greenlight . although I run the "bbb-record --rebuildall" command and sanity file it's ok , the /var/bigbluebutton/recording/publish/presentation folder is empty .
> > thanks for the support Antonio
> 
> Hello Antonio, do you have the same error in the log file? you can check an progress log file in the folder: /var/log/bigbluebutton/presentation You can find more information in the google group: https://groups.google.com/g/bigbluebutton-setup/c/2WCvFXmRR1A
> 
> **I think ffmpeg doesn't want my server's cpu. Is there a way to work around this error. Either rewrite the config of ffmpeg so that all cpu are allowed? Or use another scpipt for editing videos?**


Hi Maxspyone ,
this is log file for test recording rebuild today :

/var/bigbluebutton/recording/process/presentation/fa26eec6fc02bef9eebbb467417b06f65c6d08fb-1649002066346
I, [2022-04-03T18:15:27.136004 #7280]  INFO -- : Traceback (most recent call last):
I, [2022-04-03T18:15:27.136057 #7280]  INFO -- :   File "utils/gen_webvtt", line 21, in <module>
I, [2022-04-03T18:15:27.136075 #7280]  INFO -- :     from lxml import etree
I, [2022-04-03T18:15:27.136089 #7280]  INFO -- : ImportError: cannot import name 'etree' from 'lxml' (/usr/lib/python3/dist-packages/lxml/__init__.py)
I, [2022-04-03T18:15:27.137376 #7280]  INFO -- : Success?: false
I, [2022-04-03T18:15:27.137413 #7280]  INFO -- : Process exited? true
I, [2022-04-03T18:15:27.137423 #7280]  INFO -- : Exit status: 1
E, [2022-04-03T18:15:27.137442 #7280] ERROR -- : Generating closed caption files failed
E, [2022-04-03T18:15:27.137455 #7280] ERROR -- : /usr/local/bigbluebutton/core/scripts/process/presentation.rb:204:in `<main>'


the configuration of the ffmpeg conversion is all in default and uses the CPU at 100%, I have not yet verified how to lower this data, but first I am trying to solve the publication problem .

**Comment by ffdixon** [comment]
We note that your system has only 4 CPU cores, whereas we recommend a minimum of 8 CPU cores.  Is this a virtual machine -- can you resize it and let us know if you still encounter the same issue?

**Comment by maxspyone** [comment]
> ImportError: cannot import name 'etree' from 'lxml'

Unfortunately i think you have another problem. It's best to look in the google group (https://groups.google.com/g/bigbluebutton-setup) to see if anyone has had also a problem with python. If not you can create a new conversation there to check your configuration and installation.

Please put all your info there like, "sudo bbb-conf --check", if it's a freshly installed server etc.

**Comment by maxspyone** [comment]
> We note that your system has only 4 CPU cores, whereas we recommend a minimum of 8 CPU cores. Is this a virtual machine -- can you resize it and let us know if you still encounter the same issue?

Hello [ffdixon](https://github.com/ffdixon),

yes it is only a 4 core cpu, but this is not the problem. 
At the Hetzner company, I have a vserver with 2 cores and only 4GB RAM. I also installed BigBlueButton there and everything works perfectly there. (Certainly you cannot have many users with webcam on in the same room but there is no problem. Recordings are also published)

I now know where my problem is and can avoid it by changing the server to another company, but maybe other users also have CPUs that are not allowed by ffmpeg.

Maybe this would be something for future development, if ffmpeg makes a mistake, an alternative video editing script used to cut the video?

Best regards and many thanks for all your help!
It is a great community!

**Comment by ffdixon** [comment]
> I now know where my problem is and can avoid it by changing the server to another company, but maybe other users also have CPUs that are not allowed by ffmpeg.

How did you determine your CPU was not supported (other than the error)?
