### ISSUE TITLE
Connection failure (ICE error 1107) 3-4 weeks ago, we could no longer share webcams using the BBB

### ISSUE THREAD

**Issue by AndrewBrooks56** [bigbluebutton/bigbluebutton#14698]
Connection failure (ICE error 1107) 
3-4 weeks ago, we could no longer share webcams using the BBB.

Tests have been conducted with students and teachers from office computers (wired Ethernet) and laptops connected with WiFi (eduroam). Tests have been conducted using mobile hotspot connections.

All tests resulted in the Connection failure (ICE error 1107) when trying to share webcams.

**NOTE: BBB works OK at my home using a 5G router and a public IPv6 address.**

https://groups.google.com/g/bigbluebutton-users/c/CCAa4G10cUA)
https://groups.google.com/g/bigbluebutton-users/c/HWP1-MSSIFs

I have sent a last round of emails to our service providers. 
Possibilities:
a. A middle-box or server (BBB?) somewhere is not configured correctly for dual stack IPv4/IPv6.
b. Company X have misconfigured our firewall. (I doubt this is the case.)
c. Company Y have misconfigured the BBB server. (I doubt this is the case.)
d. A good old-fashioned bug in the version of BBB being used.

Andrew Brooks

**Comment by henriquebol** [comment]
I have a similar problem, but apparently it only happens when there is more than one webcam connected. All webcams go down. Users are reloading the page to be able to turn the webcam back on. It's been happening since 2.4.4. I'll do some testing and check the logs to see if I can find anything.

**Comment by prlanzarin** [comment]
@AndrewBrooks56 have you set up your own coturn instance with TURN+STUN?
Review your server firewall policies, make sure your TURN instance is working.

@henriquebol the described behavior is certainly not similar to the OP's, so please try not to add noise to unrelated issues. I suggest going to the mailing lists first and preferably send relevant logs. For starters, look at https://github.com/bigbluebutton/bigbluebutton/issues/14198.

**Comment by prlanzarin** [comment]
@AndrewBrooks56 now I see that you're dealing with a BBB instance provided to you by a 3rd party, so most of things I sent might be a bit difficult to do if you're not the administrator of the system.

Given the scenario, I'm closing the issue. Can we move the discussion back to the the mailing list topic `Connection failure (ICE error 1107)` in bbb-users? We can continue to engage there.
