### ISSUE TITLE
Add automated reconnection tests (media and meteor websocket connection)

### ISSUE THREAD

**Issue by TiagoJacobs** [bigbluebutton/bigbluebutton#14708]
Create a test that kills meteor websocket connection (tcpkill) and drop new connection attempts for X seconds (iptables  ... -j DROP). 

Run it with following parameters: 0s, 5s, 10s, 15s, 20s, 25s, 30s.

In each execution we will want to check:
- Client-side log was generated? 
- Server-side log was generated?
- Did the webcam continue to flow?
- Did the audio continue to flow?
- Did the screenshare continue to flow?
- Did reconnection succeeded?

**Comment by TiagoJacobs** [comment]
Hello @Tainan404 - please let's check what happens with a manual test of the scenario with 30s disconnection with latest 2.6 version

**Comment by Tainan404** [comment]
I made the test:

Client-side log was generated?
[tainan26.bbb.imdt.dev-1666029183888.log](https://github.com/bigbluebutton/bigbluebutton/files/9803261/tainan26.bbb.imdt.dev-1666029183888.log)

Server-side log was generated? N/A
Did the webcam continue to flow? No
Did the audio continue to flow? No, it starts a weird case, where the audio keeps glowing, but the user is disconnected
Did the screenshare continue to flow? No, it stops, but doesn't allow user to unshare
Did reconnection succeeded? Yes



https://user-images.githubusercontent.com/15806883/196260704-5d335d70-c75c-487d-afe3-882b93aa09d8.mp4
