### ISSUE TITLE
Security issue (XSS) found in BBB

### ISSUE THREAD

**Issue by risup8682** [bigbluebutton/bigbluebutton#14718]
**Describe the bug**

I reported a XSS vulnerability twee weeks ago to [security@bigbluebutton.org](mailto:security@bigbluebutton.org) but I don't get any response. I do not want to share the details for the vulnerability here, can you guys check this mailbox or provide antoher secure way to communicate?

**Comment by ffdixon** [comment]
Message received Julian -- thanks for reporting it!  Responded to you from the account.

**Comment by antobinary** [comment]
Thank you @risup8682 ! The fix for what you reported is still under development. We will be closing this issue as it is independent from the actual issue report.
