### ISSUE TITLE
Localize the "Spacebar", "Enter", "Left Arrow", "Right Arrow" in the shortcuts dialog

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#14748]
**Describe the bug**
The text "Spacebar", "Enter", "Left Arrow", "Right Arrow" is always in English, even when the current locale is a different language.

**To Reproduce**
1. Go to test24.bigbluebutton.org
2. Click on Options to menu, select Settings, and change language to a non-English choice (such as French)
3. Click on Options to menu, choose Shortcuts 

**Expected behavior**
The words "Localize" the "Spacebar", "Enter", "Left Arrow", "Right Arrow" on the left side of the table appear in French.

**Actual behavior**
They remain in English.

**Screenshots**
Here the screen shot shows German (Deutsch), but the labels are still in English.

<img width="594" alt="image" src="https://user-images.githubusercontent.com/290351/161889246-a5e698b8-5ccc-457c-b42f-412f9f043b3b.png">

**BBB version:**
2.4.x and 2.5-alpha

**Comment by pielonet** [comment]
Hi,

It wasn't part of 2.5-RC2
When will it be added ?

Kind regards

**Comment by pielonet** [comment]
I translated the chains into French...

**Comment by ali-alhaidary** [comment]
It was translated 2 months ago for Arabic

**Comment by ramonlsouza** [comment]
> I translated the chains into French...

They are [in the latest pull](https://github.com/bigbluebutton/bigbluebutton/pull/15104/files#diff-a13acc65467e98b6ab7def54462a0509d39fb99fb101b7879c73e71af7e6fa32R687-R690), should be present in the next 2.5 release
