### ISSUE TITLE
2.5 - Blue screen when clicking on the breakout room invitation

### ISSUE THREAD

**Issue by antonbsa** [bigbluebutton/bigbluebutton#14740]
**Describe the bug**
The client crashes when the moderator clicks in the breakout room invitation button when there is a user joined to a room.

**To Reproduce**
1. Join in a meeting with 2 users (at least one moderator);
2. Create breakout rooms;
3. Join in a room with a user;
4. As a moderator, click on "Breakout room invitation" button in the manage users menu;

**Video**

https://user-images.githubusercontent.com/56703993/161814902-5872fc4a-1b1d-4423-ad5c-4e1f901e1cdf.mp4

**Comment by antobinary** [comment]
"Cannot set properties of undefined setting 'room'" :eyeglasses:

**Comment by antobinary** [comment]
Nice catch @antonbsa !
