### ISSUE TITLE
[2.4.6] "Autoswaplayout: true" doesn't work as expected

### ISSUE THREAD

**Issue by einhirn** [bigbluebutton/bigbluebutton#14766]
**Describe the bug**
When using "autoswaplayout: true", the presentation starts invisible, but the presentation area is still reserved, so cameras aren't maximized as expected. This is true with "smart layout" as well as "custom layout". I didn't further test other layout managers, because they seem to work as expected.

**To Reproduce**
1. Configure bbb-html5 with `public.layout.autoswaplayout: true`
2. Start a session
3. Share a camera
4. Click "restore presentation"
5. Click "minimize presentation"

**Expected behavior**
The camera should be maximized while the presentation is minimized. This should already be the case after step 3

**Actual behavior**
The camera is shown alongside an empty presentation area at first (after completing step 3). After completing steps 4-5 the camera is shown as expected.

**Screenshots**
Step 3
![grafik](https://user-images.githubusercontent.com/189249/162211631-423ba0a2-dd88-4c32-aeae-6a0f08eb3324.png)

Step 4
![grafik](https://user-images.githubusercontent.com/189249/162214099-723acebe-feaa-41d5-80bb-5d50cd450f2b.png)

Step 5
![grafik](https://user-images.githubusercontent.com/189249/162214193-5d3b4bc0-b64f-49da-97a6-1a6093f1fb40.png)

**BBB version:**
BigBlueButton Server 2.4.6 (3045)
                    Kernel version: 4.15.0-175-generic
                      Distribution: Ubuntu 18.04.6 LTS (64-bit)
                            Memory: 24657 MB
                         CPU cores: 8

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 100.0.4896.60 (Official Build) (64-bit)

**Additional context**
We also have configured "public.presentation.restoreOnUpdate: true", but changing that back to "false" doesn't seem to change anything.

**Comment by einhirn** [comment]
Oh, I forgot to add the Version Number of the "Client Build"...
![grafik](https://user-images.githubusercontent.com/189249/162227314-99030f16-91dc-47d8-8535-363aa53100f5.png)

**Comment by antobinary** [comment]
Thanks for the update! Build 2550 includes the fix for #14750 , so this issue is likely independent

**Comment by einhirn** [comment]
@antobinary can you tell me how to verify whether the patch from #14752 already made it to my System? I searched for the file/directory names but didn't find them. I re-installed the server from the bbb-24-dev repo about 1-2h after the patch was merged.

**Comment by antobinary** [comment]
Hi @einhirn !
Build 2551 (from the same repo `bionic-24-dev` contains @ramonlsouza 's fix #14771 . Any chance you could give it a try and comment back?

**Comment by einhirn** [comment]
Installed the latest build and the Issue is resolved, thank you!
