### ISSUE TITLE
[2.4 + 2.5] - Dragging the chat bar by the content below when the layout is "focus on" doesn't work

### ISSUE THREAD

**Issue by antonbsa** [bigbluebutton/bigbluebutton#14762]
**To Reproduce**
1. Join the meeting with a moderator;
2. Start sharing the screen and webcam;
3. Set the layout to "Focus on Video";
4. Try expanding the chat by dragging on the screen sharing part;

**Video**

https://user-images.githubusercontent.com/56703993/162198946-c1927223-5ef2-4fae-a0cc-f4393f7030ea.mp4

**Comment by prlanzarin** [comment]
It's worth nothing that this is not exclusive to screen sharing - any form of secondary content on a `Focus on \<X\>` layout has the same problem. That means: presentation, external video and screen with Focus on video; webcams with Focus on presentation.

**Comment by mokazemi** [comment]
Today I noticed that users are also unable to resize the panel from webcam area (showed area).
Does this merge request also solve it? @antonbsa

![image](https://user-images.githubusercontent.com/18334056/192113377-575d3094-5177-4bed-ae41-b2e40c75922f.png)

**Comment by antonbsa** [comment]
Hi @mokazemi! I'm not able to reproduce this bug, it's working fine for me. is there any setting different than the default you've made? After the #15737 merge, I tested a bunch of things and it looks like all the resizes are working properly. If the bug persists for you, could you record a video showing it?

**Comment by mokazemi** [comment]
> Hi @mokazemi! I'm not able to reproduce this bug, it's working fine for me. is there any setting different than the default you've made? After the #15737 merge, I tested a bunch of things and it looks like all the resizes are working properly. If the bug persists for you, could you record a video showing it?

Oh, I've forgotten that I'm using 2.5.5 and I thought this merge may not solve it. 
I tried with 2.6 demo and it's working. Thanks.
