### ISSUE TITLE
bbb-conf --setip refreshes UFW rules -- opens SSH for everyone.

### ISSUE THREAD

**Issue by D33M0N** [bigbluebutton/bigbluebutton#14776]
when I installed BBB with -w flag (for UFW install, hoped it's like one time firewall install + rules setup)

 then now running:
`bbb-conf --setip bbb.domain.name.intra` (which running it every time seemed to be necessary previously every time BBB packages got updated from repos) also among other things refreshes UFW rules, which would be fine, except that it keeps opening SSH port globally on all interfaces, which is rather irritating. So i have to manually go and delete the new OpenSSH rules it creates.
(
Have set manual 22/tcp from only internal-interface from certain subnet only -- luckily it doesn't delete this rule, so I have to just delete the added OpenSSH ones.
)

But I would really like if the --setip didn't mess with firewall rules at all. Or some flag/config_option to turn this behavior off. Or it limited it only to actual BBB ports and left SSH alone.

**Comment by hostbbb** [comment]
You can add your customized rules to apply_lib, and remove the rules you don't want applied.. or disable it all together so bbb-conf never runs again

**Comment by D33M0N** [comment]
> You can add your customized rules to apply_lib, and remove the rules you don't want applied.. or disable it all together so bbb-conf never runs again

Can you explain, how this disabling ufw rules update is done? And where this apply_lib is located?

What do you mean by "so bbb-conf never runs again"? It doesn't run by itself I assume/hope, I have always ran it myself manually -- but sadly it was always necessary to run after `apt upgrade`, when bbb packages were involved, because the service just was broke without running `bbb-conf --setip <name>` again. (that was then bbb 2.2; not sure yet about 2.4, haven't got any updates from repos yet with 2.4; but had to run it already because changing server name couple of times).
But while doing so, it also does stuff that I don't like, like refreshing UFW rules.

**Comment by D33M0N** [comment]
apparently it's not only --setip problem but just restarting the BBB service also trigger this BS.
```
:~$ sudo bbb-conf --restart
Restarting BigBlueButton 2.4.5 ...
Stopping BigBlueButton

Applying updates in /etc/bigbluebutton/bbb-conf/apply-config.sh: 
  - Enable Firewall and opening 22/tcp, 80/tcp, 443/tcp and 16384:32768/udp
Skipping adding existing rule
Skipping adding existing rule (v6)
Skipping adding existing rule
Skipping adding existing rule (v6)
Skipping adding existing rule
Skipping adding existing rule (v6)
Firewall is active and enabled on system startup

Starting BigBlueButton
```

what the eff? why does it try to recreate firewall rules on every service restart??? is there a sane way to turn this nonsense off please?

**Comment by prlanzarin** [comment]
> what the eff? why does it try to recreate firewall rules on every service restart??? is there a sane way to turn this nonsense off please?

Just comment the `enableUFW` function call in `/etc/bigbluebutton/bbb-conf/apply-config.sh`.

bbb-install creates that when you run it with -w and apply-config is always run with bbb-conf.

**Comment by hostbbb** [comment]
Like @prlanzarin said uncomment function or even better add your custom rules so they always get re applied

**Comment by D33M0N** [comment]
nvm, found the issue. had to remove the line
`enableUFWRules`
from /etc/bigbluebutton/bbb-conf/apply-config.sh
