### ISSUE TITLE
Extract nodejs from bbb-html5 package

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#14806]
We've been including NodeJS as part of bbb-html5 package. This is mostly done as each Meteor release comes with a recommended NodeJS version. Related: https://github.com/bigbluebutton/bigbluebutton/pull/14163 https://github.com/bigbluebutton/bigbluebutton/issues/14162

We use `wget` and untar the NodeJS file as part of bbb-html5's packaging.

Splitting `bbb-html5` into `bbb-html5` and `bbb-html5-nodejs` will have the following advantages:
- `bbb-html5` will be much more lightweight, at least 30MB reduced. Given that it's updated very frequently, this is a welcome change.
- `bbb-html5-nodejs` could technically be upgraded from NodeJS 14.18.1 to 14.18.3 without touching `bbb-html5` package (see #14163 ) - caveat!! - local testing will be required

Drawbacks:
- still not reusing the OS' NodeJS version, but this is not exactly a drawback of this approach but of the entire Meteor setup.
- possibly some more complexity - bbb-html5-nodejs listed as a dependency for bbb-html5, etc

Comments are welcome!

**Comment by znerol** [comment]
Extracting a separate `bbb-html5-nodejs` package is a good move. :+1:
