### ISSUE TITLE
Drop obsolete Dockerfile

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#14807]
Circa 2019 a few Dockerfile files were added to BigBlueButton during a dockerizing initiative. This initiative did not pull through [for multiple reasons]. However, 
- a viable alternative is driven by @alangecker in https://github.com/bigbluebutton/docker
- a development environment container repository can be found at https://github.com/bigbluebutton/docker-dev
- For packaging we use this dockerfile - https://gitlab.senfcall.de/senfcall-public/docker-bbb-build/-/blob/main/Dockerfile and it's hooked via https://github.com/bigbluebutton/bigbluebutton/blob/v2.5.x-release/.gitlab-ci.yml#L14

That said, the Dockerfiles scattered through bigbluebutton/bigbluebutton have not been maintained, can be confusing (suggesting an incorrect state of dockerization), etc. I believe we **should drop them from the official BBB repository, and if need be, obtain them from one of the older tags/branches.**

### List of obsolete Dockerfiles:

  akka-bbb-apps/Dockerfile
  akka-bbb-fsesl/Dockerfile
  bbb-common-web/Dockerfile
  bbb-fsesl-client/Dockerfile
  bigbluebutton-web/Dockerfile
  bbb-common-message/Dockerfile
  bigbluebutton-html5/Dockerfile
  bigbluebutton-html5/Dockerfile.dev

  labs/docker/Makefile
  labs/docker/sbt/Dockerfile
  labs/docker/nginx/Dockerfile
  labs/docker/coturn/Dockerfile
  labs/docker/kurento/Dockerfile
  labs/docker/freeswitch/Dockerfile

### Still in use:
  bbb-libreoffice/docker/Dockerfile   -> still in use for presentation conversion

### More:

- Question for @alangecker - are you depending on any of these?

**Comment by ffdixon** [comment]
Yes, let's drop them from the main repository as  https://github.com/bigbluebutton/docker is where all the docker action is happening.

**Comment by alangecker** [comment]
to answer your question: none of these are in use for [bigbluebutton/docker](https://github.com/bigbluebutton/docker)  :)
