### ISSUE TITLE
Getting error code on web => 1007 on audio connect with mic

### ISSUE THREAD

**Issue by evilrat** [bigbluebutton/bigbluebutton#14800]
**Describe the bug**
When join a meeting shows bug audio error ---- 1007...it appears only on cellular network on smartphone.

i am using digital ocean server and have added all firewall rules and also i have done setup of freeswitch using stun.l.google.com:19302

**Comment by ffdixon** [comment]
Can we get you to post this issue to [bigbluebutton-setup](https://bigbluebutton.org/community-support/) mailing list. We can help you there and, if there is a bug, we'll open an issue here to track it.

When you post, let us know details on your server setup and if you can reproduce this issue on https://test.bigbluebutton.org/. For more details on what information to share, see https://docs.bigbluebutton.org/support/getting-help.html.

**Comment by evilrat** [comment]
> bigbluebutton-setup

can u please accept the join request....

**Comment by evilrat** [comment]
> Can we get you to post this issue to [bigbluebutton-setup](https://bigbluebutton.org/community-support/) mailing list. We can help you there and, if there is a bug, we'll open an issue here to track it.
> 
> When you post, let us know details on your server setup and if you can reproduce this issue on https://test.bigbluebutton.org/. For more details on what information to share, see https://docs.bigbluebutton.org/support/getting-help.html.

i have sent the request to join the google group on bigbluebutton-dev
