### ISSUE TITLE
The new reduced UI for external video bars access to subtitles for participants with disabilities 

### ISSUE THREAD

**Issue by DavidPruem** [bigbluebutton/bigbluebutton#14818]
One lecturer notified us that the new external video player in bbb 2.4. has accessibility problems.
With the older system users could enable subtitles on youtube videos, but since 2.4 there is no option to do so anymore. It would be helpful if we could get that ability back.

Thank you very much for a great piece of software.

David

**Comment by antobinary** [comment]
Thank you for reporting this!
Let's try to do this on 2.5 and when happy with the result, look into backporting to 2.4
