### ISSUE TITLE
Post events analytics script ignores overrides for securitySalt property

### ISSUE THREAD

**Issue by pielonet** [bigbluebutton/bigbluebutton#14819]
Hi,
Bigbluebutton properties from file `/usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties` are now overriden by file `/etc/bigbluebutton/bbb-web.properties`

Nevertheless, the script `post_events/post_events_analytics_callback.rb` keeps retrieving the `securitySalt` parameter from the first file, ignoring overrides as referenced here : https://github.com/bigbluebutton/bigbluebutton/blob/50b6cf48fb7fb0739e4a0deead909a978d2c8ff8/record-and-playback/core/scripts/post_events/post_events_analytics_callback.rb#L156

It forces administrators to also modify the first file when modifying BBB'secret in order to preserve the functioning of analytics callback script.

Solution : modify script so that it uses the override mechanism to retrieve securitySalt parameter.

Kind regards,
Thierry

**Comment by antobinary** [comment]
Hi @pielonet 

This is likely a duplicate of https://github.com/bigbluebutton/bigbluebutton/issues/14730
However, thinking more about it, the "solution" I quoted in 14730 depends on the salt being in `/etc/bigbluebutton/bbb-web.properties` and your point stands.
