### ISSUE TITLE
Closed captions position when the presentation is minimized

### ISSUE THREAD

**Issue by pedrobmarin** [bigbluebutton/bigbluebutton#14811]
**Describe the bug**
Closed caption live feedback gets over the user-list/side-panel when loses the presentation position reference.

**To Reproduce**
1. Write CC
2. Minimize the presentation

**Expected behavior**
The CC text to keep position.

**Screenshots**
![Peek 2022-04-12 16-14](https://user-images.githubusercontent.com/1778398/163038259-3ee72f57-9aea-4705-8e96-ade58e1623ed.gif)

**Comment by antobinary** [comment]
Nice catch!
