### ISSUE TITLE
BigBlueButton 2.5 Alpha5  and BigBlueButton 2.5 Alpha 6  after new installation share webcam and share your screen fails

### ISSUE THREAD

**Issue by erpsolns** [bigbluebutton/bigbluebutton#14816]
![Screen Shot 2022-04-13 at 9 08 59 am](https://user-images.githubusercontent.com/31876291/163092936-0e53f157-ded0-4db1-824a-266fc1537af7.png)

**Describe the bug**
BigBlueButton 2.4.5 and BigBlueButton 2.4.6  after new installation share webcam and share your screen fails

**To Reproduce**
Share webcam  tries to start messsage webcame share is starting 
 and video square  comes on screen but after some time  returns error
media could not reach the server (error 1020)

click to Screenshare returns 
Error 1020 and also sometimes code 1102 could not share screen

**Expected behavior**
Share webcam should start and video should be visible

**Actual behavior**
Video is not visible and starting ends with error message.

**Screenshots**
![Screen Shot 2022-04-13 at 9 08 44 am](https://user-images.githubusercontent.com/31876291/163092903-e3d9fabd-e2c1-4d22-ad16-7a04c1279465.png)
**BBB version:**
2.5 Alpha 5 and also on 2.5 Alpha6
on chrome mac as well as on Android 

**Additional context**

**Comment by erpsolns** [comment]
BigBlueButton Server 2.5.0-alpha.6 (166)
                    Kernel version: 5.4.0-107-generic
                      Distribution: Ubuntu 20.04.4 LTS (64-bit)
                            Memory: 65758 MB
                         CPU cores: 8

/etc/bigbluebutton/bbb-web.properties (override for bbb-web)
/usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties (bbb-web)
       bigbluebutton.web.serverURL: https://xxxx.xxxxxxxxx.com
                defaultGuestPolicy: ALWAYS_ACCEPT
                 svgImagesRequired: true
              defaultMeetingLayout: SMART_LAYOUT

/etc/nginx/sites-available/bigbluebutton (nginx)
                       server_name: xxxx.xxxxxxx.com
                              port: 80, [::]:80
                              port: 443 ssl

/opt/freeswitch/etc/freeswitch/vars.xml (FreeSWITCH)
                       local_ip_v4: 144.217.72.231
                   external_rtp_ip: 144.217.72.231
                   external_sip_ip: 144.217.72.231

/opt/freeswitch/etc/freeswitch/sip_profiles/external.xml (FreeSWITCH)
                        ext-rtp-ip: $${local_ip_v4}
                        ext-sip-ip: $${local_ip_v4}
                        ws-binding: 144.217.72.231:5066
                       wss-binding: 144.217.72.231:7443

/usr/local/bigbluebutton/core/scripts/bigbluebutton.yml (record and playback)
                     playback_host: xxxx.xxxxxxx.com
                 playback_protocol: https
                            ffmpeg: 4.2.4-1ubuntu0.1

/usr/share/bigbluebutton/nginx/sip.nginx (sip.nginx)
                        proxy_pass: 144.217.72.231
                          protocol: http

/usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml (Kurento SFU)
/etc/bigbluebutton/bbb-webrtc-sfu/production.yml (Kurento SFU - override)
                        kurento.ip: 144.217.72.231
                       kurento.url: ws://127.0.0.1:8888/kurento
                    kurento.sip_ip: 144.217.72.231
               recordScreenSharing: true
                     recordWebcams: true
                  codec_video_main: VP8
               codec_video_content: VP8

/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml (HTML5 client)
/etc/bigbluebutton/bbb-html5.yml (HTML5 client config override)
                             build: 36
                        kurentoUrl: wss://xxxx.xxxxxxx.com/bbb-webrtc-sfu
                  enableListenOnly: true
                    sipjsHackViaWs: true

/usr/share/bbb-web/WEB-INF/classes/spring/turn-stun-servers.xml (STUN Server)
                              stun: stun.l.google.com:19302

**Comment by erpsolns** [comment]
Content of  /etc/kurento/modules/kurento/WebRtcEndpoint.conf.ini

;; configure a STUN or TURN server.
;;
;; <externalAddress> is a single IPv4 or IPv6 address.
;;
;externalAddress=198.51.100.1
;externalAddress=2001:0db8:85a3:0000:0000:8a2e:0370:7334

;; Enable ICE-TCP candidate gathering.
;;
;; This setting enables or disables using TCP for ICE candidate gathering in
;; the underlying libnice library:
;; https://libnice.freedesktop.org/libnice/NiceAgent.html#NiceAgent--ice-tcp
;;
;; You might want to disable ICE-TCP to potentially speed up ICE gathering
;; by avoiding TCP candidates in scenarios where they are not needed.
;;
;; <iceTcp> is either 1 (ON) or 0 (OFF). Default: 1 (ON).
;;
;iceTcp=1

**Comment by erpsolns** [comment]
File cat /usr/share/bbb-web/WEB-INF/classes/spring/turn-stun-servers.xml

0 lines

**Comment by erpsolns** [comment]
chrome://webrtc-internals/

Caller origin: https://live1.saiversity.com
Caller process id: 2969
getUserMedia call
Time: 09:12:40 GMT+1000 (Australian Eastern Standard Time)
Video constraints: {deviceId: {exact: ["84c30f2c154cd163a75c003a2c24ac5ba619362b0c2a7494c2b9c196e97e598f"]}}
getUserMedia result
Time: 09:12:40 GMT+1000 (Australian Eastern Standard Time)
Stream id: kNflPLZT1ouz99y63ZBt9lxPGeJb50HfO1QR
Video track: id:85cc895e-5417-40f6-843f-fb3c598befc8 label:HD Pro Webcam C920 (046d:082d)
Caller origin: https://live1.saiversity.com
Caller process id: 2969
getUserMedia call
Time: 09:20:34 GMT+1000 (Australian Eastern Standard Time)
Audio constraints: true
Video constraints: {width: {max: 2560}, height: {max: 1600}, frameRate: {max: 10, ideal: 5}}
getUserMedia result
Time: 09:20:40 GMT+1000 (Australian Eastern Standard Time)
Stream id: gmrv6Dl9WtWOhVvVcMdYcypnGwYssfDqM6aS
Audio track: id:a6709e91-41c3-4b7b-8aaf-64e8348a44a0 label:Tab audio
Video track: id:42a15f6f-53d6-4f6c-999a-8e212dc21f24 label:web-contents-media-stream://F187CB4C00A7B90896692CFF9FCDED55
Caller origin: https://live1.saiversity.com
Caller process id: 2969
getUserMedia call
Time: 10:16:19 GMT+1000 (Australian Eastern Standard Time)
Audio constraints: true
getUserMedia result
Time: 10:16:19 GMT+1000 (Australian Eastern Standard Time)
Stream id: Jwk1PUc3fRUJqzsrxnbGwkhJidUDPvgmmSms
Audio track: id:c3943a08-fa87-46e8-bcb6-e28cc38b988b label:Default - HD Pro Webcam C920 (046d:082d

**Comment by erpsolns** [comment]
chrome://webrtc-internals/

https://xxxx.xxxxxxx.com/html5client/join?sessionToken=7kylpzzvd2jwfuxo, { iceServers: [stun:stun.l.google.com:19302], iceTransportPolicy: all, bundlePolicy: balanced, rtcpMuxPolicy: require, iceCandidatePoolSize: 0, sdpSemantics: "unified-plan", extmapAllowMixed: true }

ICE connection state: new
Connection state: new
Signaling state: new
ICE Candidate pair: 49.195.113.82:28177 <=> 144.217.72.231:19914
ICE candidate grid
Stats Tables
RTCAudioSource_7 (media-source)
RTCCertificate_4C:9E:F5:E4:28:03:FF:1B:7E:E7:31:0B:BC:0C:98:4C:0F:78:26:2A:F4:87:C6:D2:97:16:2F:46:54:B3:08:DB (certificate)
RTCCertificate_DC:FC:DF:65:BE:1A:B3:AF:D6:92:63:66:1F:4B:94:1D:BB:53:E4:58 (certificate)
RTCIceCandidatePair_EzU2r0E6_iXqZY1GZ (candidate-pair)
RTCIceCandidate_EzU2r0E6 (local-candidate)
RTCIceCandidate_iXqZY1GZ (remote-candidate)
RTCInboundRTPAudioStream_106605671 (inbound-rtp, opus)
RTCMediaStreamTrack_receiver_7 (track)
RTCMediaStreamTrack_sender_7 (track)
RTCMediaStream_a7e6dea5-34ca-41fa-a845-971e87f52792 (stream)
RTCMediaStream_y7D8ru66MZkKIXoy9tBo10kshiOSyyrW (stream)
RTCOutboundRTPAudioStream_536061852 (outbound-rtp, opus)
RTCPeerConnection (peer-connection)
RTCRemoteInboundRtpAudioStream_536061852 (remote-inbound-rtp)
RTCRemoteOutboundRTPAudioStream_106605671 (remote-outbound-rtp)
RTCTransport_0_1 (transport)
Stats graphs for RTCAudioSource_7 (media-source)
Stats graphs for RTCIceCandidatePair_EzU2r0E6_iXqZY1GZ (candidate-pair)
Stats graphs for RTCInboundRTPAudioStream_106605671 (inbound-rtp)
Stats graphs for RTCMediaStreamTrack_receiver_7 (track)
Stats graphs for RTCMediaStreamTrack_sender_7 (track)
Stats graphs for RTCOutboundRTPAudioStream_536061852 (outbound-rtp)
Stats graphs for RTCPeerConnection (peer-connection)
Stats graphs for RTCRemoteInboundRtpAudioStream_536061852 (remote-inbound-rtp)
Stats graphs for RTCRemoteOutboundRTPAudioStream_106605671 (remote-outbound-rtp)
Stats graphs for RTCTransport_0_1 (transport)

**Comment by prlanzarin** [comment]
Please the mailing lists for setup-related stuff.

**Comment by erpsolns** [comment]
NO changes to BigBlueButton outside of  [bbb-conf] or [bbb-install.sh]

**Comment by erpsolns** [comment]
I went back to ubuntu 18 and installed 2.4 [bbb-install.sh](https://github.com/bigbluebutton/bbb-install).and everything works fine.   But the same installation install.sh  2.5 alpha 5 or alpha6 - sharewebcam and share your screen are throwing 1022 errors

**Comment by markginter31** [comment]
It is an error in the bbb-install script (and looks like they have a fix for it) -- best to post over in the bbb-install issues. 

from the google groups / dev list the fix is to:

Run:

chmod 755 /etc/bigbluebutton/bbb-webrtc-sfu

chown bigbluebutton:root /etc/bigbluebutton/bbb-webrtc-sfu

chmod 600 /etc/bigbluebutton/bbb-webrtc-sfu/production.yml

chown bigbluebutton:root /etc/bigbluebutton/bbb-webrtc-sfu/production.yml

restart bbb

**Comment by vasylOstrovskyi** [comment]
Notice that in 2.5, mediasoup is used by default. Try to configure it as described in the 2.4 manual, this worked for me. 
Seems that the install script does not do it, but without proper mediasoup config video and scrrenshare does not work. 
Regards,
 Vasyl

**Comment by ffdixon** [comment]
Permissions for sharing webcams/screenshare should now be setup correctly in a new install (see https://github.com/bigbluebutton/bbb-install/pull/512).
