### ISSUE TITLE
bbb-record --delete/--rebuild/--deleteall ignores "video" folder

### ISSUE THREAD

**Issue by pielonet** [bigbluebutton/bigbluebutton#14827]
Hi,

I filed an issue in Daniel Petri's `bbb-recording-exporter` project to describe the problem : https://github.com/danielpetri1/bbb-recording-exporter/issues/77

Kind regards,
Thierry

**Comment by danielpetri1** [comment]
This is not an issue with BBB. Please see the fix I left as a comment in the thread you linked.
