### ISSUE TITLE
when preloading a presentation from the greenlight interface in bbb, the presentation default.pdf is not displayed

### ISSUE THREAD

**Issue by sergey-balychev** [bigbluebutton/bigbluebutton#14828]
**Describe the bug**
when preloading a presentation from the greenlight interface in bbb, the presentation default.pdf is not displayed

**To Reproduce**
1. Go to greenlight interface
2. Click on 'add presentatoin' in the greenlight interface
3. Click on 'Start'
4. We see the presentation that was uploaded to greenlight, but does not see the presentation default.pdf

**Expected behavior**
Two presentations are available: 1st one that I uploaded, 2nd default.pdf.

**Actual behavior**
there is only one presentation available, which I downloaded from the greenlight interface. presentation default.pdf is not available for display

**Screenshots**
![image](https://user-images.githubusercontent.com/63751589/163386395-7f8504b8-97dc-433c-af96-351297b36b47.png)

![image](https://user-images.githubusercontent.com/63751589/163387977-7dcdc20b-5739-403f-aebd-27d89c7a19ed.png)

**BBB version:**
`$ sudo bbb-conf --check | grep BigBlueButton`
BigBlueButton Server 2.4.6 (3059)
Greenlight. release-2.12.3

**Desktop:**
 - OS: [Windows, Mac]
 - Browser [Chrome, Safari]
 - Device: [hp elitebook g5, MacBook air (m1)]

**Smartphone:**
 - Device: [iPhone11]
 - OS: [iOS 15.3.1]
 - Browser [stock browser, Safari]

**Additional context**
**Question:** should the default.pdf presentation be available in the bbb interface when preloading the presentation from the greenlight interface, or should the default.pdf presentation be unavailable for display if we loaded our presentation from the greenlight interface?

**Comment by antobinary** [comment]
Hi @sergey-balychev !
I tried the use case you described:
![Screenshot from 2022-04-18 10-54-43](https://user-images.githubusercontent.com/6312397/163826957-10095593-7ddd-4d8b-8199-e89a0055ff43.png)

I only see my custom presentation:
![Screenshot from 2022-04-18 10-55-19](https://user-images.githubusercontent.com/6312397/163826985-b23e856a-4058-4aa8-846f-566d69d583a9.png)


Based on the behavior, this acts more like "Use a custom [default] presentation", than "Add Presentation". Let's see how it looks from GreenLight's perspective

**Comment by sergey-balychev** [comment]
@antobinary and what is the logic of work? should only be the downloaded presentation or default.pdf should also be available? Thanks

**Comment by antobinary** [comment]
I checked with @jfederico and looks like we used to keep both the default presentation and the newly added one (via GreenLight). We should recover this behavior.

**Comment by GuiLeme** [comment]
> I checked with @jfederico and looks like we used to keep both the default presentation and the newly added one (via GreenLight). We should recover this behavior.

Hey guys, I did some research, and apparently, the default behavior was to ignore the `default.pdf`, when some other presentations are uploaded via payload in `create` API. 

Even before my PR regarding the `removable` and `downloadable` properties, we had this behavior, as you can see down below:

![image (1)](https://user-images.githubusercontent.com/69865537/166482739-37469fad-169a-4ebc-861e-fcf529c351c3.png)

Here is the line that I highlighted in the image: [click here](https://github.com/bigbluebutton/bigbluebutton/pull/14173/files#diff-66817e37e1424f708e313232f92dcf5a411952de7291671f16c570767b82c8dcR1227)
 
Moreover, the same happens in [2.4](https://github.com/bigbluebutton/bigbluebutton/blob/eda21682ea3fd472c8d16fe7ec6bcf0f80370a6f/bigbluebutton-web/grails-app/controllers/org/bigbluebutton/web/controllers/ApiController.groovy#L1264), and even in [2.3](https://github.com/bigbluebutton/bigbluebutton/blob/8e688d77514a6b9c38ef57bf2ef52c474460bbe4/bigbluebutton-web/grails-app/controllers/org/bigbluebutton/web/controllers/ApiController.groovy#L1992), which gives us the impression that this was the default behavior for sometime now, as we can see in [this](https://github.com/bigbluebutton/bigbluebutton/blame/8e688d77514a6b9c38ef57bf2ef52c474460bbe4/bigbluebutton-web/grails-app/controllers/org/bigbluebutton/web/controllers/ApiController.groovy#L1992) git blame, the last commit in that line was 11 years ago, and even in the line below it, the last change was 4 years ago.

Down below we have a video demonstrating that on 2.3:


https://user-images.githubusercontent.com/69865537/166487607-78ce0999-0a7f-4cd6-8e60-7f68576cd178.mp4



So, just explaining what that line means: It checks if the payload is null (that is: if no presentation is sent via `create` API), then if that is the case, it downloads and process the `default.pdf`, else, it takes the flow to insert all the presentations that are specified in the payload, and in this flow, there is no insertion of the `default.pdf`. Summing up: either the `default.pdf` is inserted or the presentations in the payload, not both.

Given all that, we still have a solution to this issue, we can add a query parameter in the url of `create` API,  say `overrideDefaultPresentation`, which if not sent is going to be true (and the flow would be the the described in the paragraph above), on the other hand, if sent, we follow the flow to add both the `default.pdf` and the other presentation, as requested in the issue.

**Comment by gustavotrott** [comment]
Hey @jfederico.

Once BBB always used to remove `Default.pdf` when a pre-uploaded presentation is sent.
What do you think about keep this behavior and make possible to keep `Default.pdf` using a param `preUploadedPresentationOverrideDefault=false`.

Do you think it can solve the problem?

**Comment by gustavotrott** [comment]
Since #14944 was merged.

It will be possible to display the default presentation even when pre-uploading other presentations together.

Edit `/etc/bigbluebutton/bbb-web.properties` 
and include `beans.presentationService.preUploadedPresentationOverrideDefault=false`

**Comment by sergey-balychev** [comment]
Great. @GuiLeme @gustavotrott Thank you very much.
