### ISSUE TITLE
Cannot share Webcam on 2.5 alpha 1

### ISSUE THREAD

**Issue by makabar** [bigbluebutton/bigbluebutton#14836]
Installed 2.5 beta 1 over alpha 6 on ubuntu 20.04.
Camera worked in a6.

**To Reproduce**
1. Start the session in Greenlight, meeting opens as usual
2. Set audio on (Echo-Test works)
3. Set camera on. I can choose the camera. Preview works.
4. Tryed all options. With or without virtual backgrounds. Get "black window" with "Camera loading" message.

Camera sharing is allowed on Mac OS

Mac OS Monterey 12.4 beta with Google Chrome Version 100.0.4896.75

**Comment by markginter31** [comment]
Just had the same problem - over at google groups / dev list the fix =

(I fixed a typo in the first chown line)
Run:

chmod 755 /etc/bigbluebutton/bbb-webrtc-sfu

chown bigbluebutton:root /etc/bigbluebutton/bbb-webrtc-sfu

chmod 600 /etc/bigbluebutton/bbb-webrtc-sfu/production.yml

chown bigbluebutton:root /etc/bigbluebutton/bbb-webrtc-sfu/production.yml

**Comment by makabar** [comment]
Workaround works! Thanx and Happy Easter!

**Comment by markginter31** [comment]
You're welcome!  Go ahead and close this one out - I'd encourage you to search for the google groups associated with bigbluebutton - tons of great information there.  Happy Easter to you too!

**Comment by prlanzarin** [comment]
It was supposed to be fixed in bbb-install-2.5, but I suspect it isn't fully fixed yet. 
We'll take another look.

**Comment by ffdixon** [comment]
Webcams should now work correctly on a new install of 2.5.x, see: https://github.com/bigbluebutton/bbb-install/pull/512.
