### ISSUE TITLE
remove presentation placeholder

### ISSUE THREAD

**Issue by easy-bios** [bigbluebutton/bigbluebutton#14854]
Many customers don't like the presentation placeholder, but want the webcams bigger instead.
![image](https://user-images.githubusercontent.com/42430994/163983096-31b84cf6-0b14-4107-9d25-991c059d4575.png)

**Describe the solution you'd like**
Optionally disable the placeholder.

**Comment by antobinary** [comment]
Hi @easy-bios 
What BigBlueButton version/build are you on? The changes you request are ones we actually looked into recently...

**Comment by easy-bios** [comment]
> Hi @easy-bios What BigBlueButton version/build are you on? The changes you request are ones we actually looked into recently...

You say there could allready exist a flag for this?
We are on 2.4.5 (3021)

**Comment by ramonlsouza** [comment]
Hello @easy-bios, here are some options to achieve the desirable effect:
1. Open settings menu in a meeting and set **Layout type** to "Focus on video (push layout to all)"
2. Use the join parameter `userdata-bbb_hide_presentation=true` (each user will need to join with this parameter)
3. Set `public.layout.hidePresentation: true` in settings file (will apply to all users/meetings)

Option 1 will still display the placeholder (but only if the chat area is open), options 2 and 3 will not:
![focus-on-video-open](https://user-images.githubusercontent.com/3728706/164526256-d9925665-7a57-4be7-b860-61766d8d7911.png)

**Comment by antobinary** [comment]
Thanks @ramonlsouza !
@ramonlsouza has refactored this area on BigBlueButton 2.5 (currently in beta stage) https://github.com/bigbluebutton/bigbluebutton/pull/14551

The layout type could also be set on meeting create or on the entire server if desired - check https://docs.bigbluebutton.org/dev/api.html
![Screenshot from 2022-04-21 14-31-14](https://user-images.githubusercontent.com/6312397/164529633-ab62a641-7830-4ae3-92e8-7cdfd0b2ce2e.png)

**Comment by antobinary** [comment]
I will merge this issue into https://github.com/bigbluebutton/bigbluebutton/issues/14376 since it's actually resolved in the upcoming BBB releases. Please let us know if we can further assist with potential 2.4 remediation (parameters, etc)
