### ISSUE TITLE
Screen sharing speed problem

### ISSUE THREAD

**Issue by Alex8448** [bigbluebutton/bigbluebutton#14860]
Hello. I have a problem with screen sharing. During screen sharing, the image lags. How to speed up the broadcast of the screen image so that you can watch video files without lags? (Sorry for my English. I am using a translator)

**Comment by ffdixon** [comment]
Can we get you to post this question to our community (probably bigbluebutton-dev), see https://bigbluebutton.org/community-support/.

Include the version of BigBlueButton you are running, as well as testing the screen sharing at https://test.bigbluebutton.org/ and let us know if you see a difference.

If in helping you in the community forums we find a bug, we'll open an issue here to track it.
