### ISSUE TITLE
Installation 2.5.0 beta: netstat might not be installed

### ISSUE THREAD

**Issue by BrentBaccala** [bigbluebutton/bigbluebutton#14867]
**Describe the bug**
netstat is part of the net-tools package, which might not be installed on an Ubuntu 20 system.  Not sure about other versions.

**Installation type**
bbb-install-2.5.sh downloaded from https://ubuntu.bigbluebutton.org/bbb-install-2.5.sh

**Console output**
Waiting for port 443 to clear 
main: line 376: netstat: command not found

**Comment by BrentBaccala** [comment]
I'm getting more related errors during the install:

```
Preparing to unpack .../193-bbb-etherpad_1%3a2.5-6_amd64.deb ...
/var/lib/dpkg/tmp.ci/preinst: line 200: ifconfig: command not found
/var/lib/dpkg/tmp.ci/preinst: line 205: route: command not found
/var/lib/dpkg/tmp.ci/preinst: line 205: ifconfig: command not found
Could not connect to Redis at 127.0.0.1:6379: Connection refused
Could not connect to Redis at 127.0.0.1:6379: Connection refused
Could not connect to Redis at 127.0.0.1:6379: Connection refused
Could not connect to Redis at 127.0.0.1:6379: Connection refused
Could not connect to Redis at 127.0.0.1:6379: Connection refused
Could not connect to Redis at 127.0.0.1:6379: Connection refused
Could not connect to Redis at 127.0.0.1:6379: Connection refused
Unpacking bbb-etherpad (1:2.5-6) ...

```
So, a `net-tools` dependency also seems to be needed for bbb-etherpad.

**Comment by BrentBaccala** [comment]
I'm still getting the `Could not connect to Redis at 127.0.0.1:6379: Connection refused` messages after `net-tools` is installed, so that's a different issue.

**Comment by antobinary** [comment]
The tools in net-tools family were replaced in https://github.com/bigbluebutton/bigbluebutton/pull/14647 and https://github.com/bigbluebutton/bigbluebutton/pull/14660
If I recall correctly, there was a bit of a delay to deploy bbb-install-2.5.sh with the changes from https://github.com/bigbluebutton/bbb-install/pull/496 
It is quite possible that this issue was encountered in that tumultuous timespan. I have installed variations of focal-250 since and have not encountered troubles. Please comment if you hit this again on BBB 2.5.0-rc.1 or later.

**Comment by BrentBaccala** [comment]
I just hit this again using bbb-install-2.5.sh (wget on the fly from ubuntu.bigbluebutton.org) with focal-250 as the repository.

**Comment by antobinary** [comment]
Hi @BrentBaccala Do you see which package or section of the installation requested netstat? Maybe you have some logs you could copy-paste here or email to us directly?

**Comment by antobinary** [comment]
Hi @BrentBaccala 
If you split the install steps

wget ..... bbb-install-2.5.sh

replace `netstat` with `ss` as in https://github.com/bigbluebutton/bbb-install/pull/520

and then run your _local_ modified bbb-install-2.5.sh with the same arguments, does it run fine for you?
You may need to `chmod +x bbb-install-2.5.sh`

**Comment by antobinary** [comment]
I will go ahead and merge this PR to go hand-in-hand with 2.5.0-rc.4
Please keep us posted if you happen to try rc.4 or later
And please kepe us potsed if you spot any other oddity with the installation

Thanks for sending those logs, it certainly helped!

**Comment by BrentBaccala** [comment]
I just ran a 2.5 install from scratch and didn't see this problem.

**Comment by BrentBaccala** [comment]
Here's the relevant part of the installation log:

Selecting previously unselected package dnsutils.
(Reading database ... 172435 files and directories currently installed.)
Preparing to unpack .../dnsutils_1%3a9.16.1-0ubuntu2.10_all.deb ...
Unpacking dnsutils (1:9.16.1-0ubuntu2.10) ...
Setting up dnsutils (1:9.16.1-0ubuntu2.10) ...
Waiting for port 443 to clear
main: line 376: netstat: command not found


  Detected this server has an internal/external IP address.

      INTERNAL_IP: 192.168.4.131
    (external) IP: 100.36.116.65
