### ISSUE TITLE
Kurento often respawned which causes webcam connect error

### ISSUE THREAD

**Issue by miztaka** [bigbluebutton/bigbluebutton#14894]
**Describe the bug**
Our users often faced webcam connect error where you see black screen or 1020 error.
We recognized that kurento media server was respawned around that time according to the log rotation.(/var/log/kurento-media-server)

**To Reproduce**
1. Join a meeting room
2. Start to share your webcam
4. See black screen or 1020 error

**Expected behavior**
Your webcam is connected successfully

**Actual behavior**
See black screen or 1020 error

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser: Firefox
 - Version: 99.0

**Additional context**

- BigBlueButton 2.4.5
- Looks like 10+ participants tried to start videos (maybe)
- Load is spiking (see attached totempore graph)
- but CPU is relatively normal (see attached totempore graph)
- no particular error seen in kurento log

```
foo@host:/var/log/kurento-media-server# ls -lrt
-rw-rw-r-- 1 kurento kurento 61042874 Apr 21 23:17 2022-04-21T054028.00000.pid1630.log
-rw-rw-r-- 1 kurento kurento    31033 Apr 21 23:59 2022-04-21T231702.00000.pid14868.log
-rw-rw-r-- 1 kurento kurento 24639571 Apr 22 23:59 2022-04-22T000003.00001.pid14868.log
-rw-rw-r-- 1 kurento kurento  1363468 Apr 23 23:59 2022-04-23T000003.00002.pid14868.log
-rw-rw-r-- 1 kurento kurento  1434735 Apr 24 23:59 2022-04-24T000004.00003.pid14868.log
-rw-rw-r-- 1 kurento kurento  1401738 Apr 25 23:59 2022-04-25T000004.00004.pid14868.log
-rw-rw-r-- 1 kurento kurento 63345435 Apr 26 18:17 2022-04-26T000005.00005.pid14868.log
-rw-rw-r-- 1 kurento kurento   184819 Apr 26 23:59 2022-04-26T181703.00000.pid31398.log
-rw-rw-r-- 1 kurento kurento 39891679 Apr 27 14:02 2022-04-27T000004.00001.pid31398.log   <---
-rw-rw-r-- 1 kurento kurento  7090526 Apr 27 15:53 2022-04-27T140436.00000.pid17890.log
```

![cat-porwal-prod-bbb1 servers catalyst net nz Load](https://user-images.githubusercontent.com/4747270/165436852-96141b1e-4ed8-45f0-bcca-c0ce3887b046.png)
![cat-porwal-prod-bbb1 servers catalyst net nz Big Blue Button Meetings](https://user-images.githubusercontent.com/4747270/165436856-f2be079a-f705-41ee-a355-dae70e1f7af4.png)
![cat-porwal-prod-bbb1 servers catalyst net nz CPU Usage](https://user-images.githubusercontent.com/4747270/165436931-4c92ae87-6f2f-45ce-be48-4553f3ba76aa.png)

**Comment by prlanzarin** [comment]
@miztaka See if ICE-TCP is enabled in Kurento. If it is, I suggest disabling it.
Follow the steps outlined in this comment: https://github.com/bigbluebutton/bigbluebutton/issues/14198#issuecomment-1021356255 (the iceTcp section).

Otherwise: that's Kurento throwing a fit. It's on its way out, so you might as well try using mediasoup.
It's going to be the default media server in 2.5. It's flagged as "experimental" in 2.4, although 2.4 has
received enough adjustments by this point that mediasoup usage can be considered production grade (and it's used in prod. by quite a few people AFAIK). Should be way more performant and stable all around.

**Comment by miztaka** [comment]
@prlanzarin thanks to point out the way to mitigate. In terms of switching it to mediasoup, what exact value should be set in the config `public.kurento.videoMediaServer` instead of `Kurento`? (Is it simply `mediasoup` ?)
Also is it configurable in `/etc/bigbluebutton/bbb-html5.yml`?
Cheers

**Comment by prlanzarin** [comment]
@miztaka 

>  Also is it configurable in /etc/bigbluebutton/bbb-html5.yml?

Yes.

> what exact value should be set in the config public.kurento.videoMediaServer instead of Kurento? (Is it simply mediasoup ?)

Yes. The configurations you want to override at /etc/... are:
```
    public.kurento.screenshare.mediaServer: mediasoup
    public.kurento.videoMediaServer: mediasoup
    public.kurento.listenOnlyMediaServer: mediasoup
```

For more details, follow the steps outlined here (2.4):
https://github.com/bigbluebutton/bbb-webrtc-sfu/wiki/Back-of-the-envelope-calculations:-mediasoup#using-mediasoup-in-bigbluebutton-24=

**Comment by prlanzarin** [comment]
@miztaka did any of the two suggest approaches work?

**Comment by miztaka** [comment]
@prlanzarin we got a week since we did disable iceTCP and working properly. Will keep an eye on it for another week to see how it goes, cheers.

**Comment by prlanzarin** [comment]
Cool. I'll close this, then - re-open if necessary.

**Comment by miztaka** [comment]
Yep, thanks for your help, since we disable iceTcp, no problem occurred. Cheers.
