### ISSUE TITLE
Capture snapshots from webcam streams

### ISSUE THREAD

**Issue by awsum0225** [bigbluebutton/bigbluebutton#14919]
I have installed bigbluebutton up and running on my digitalocean server.
I'm adding an extension for bbb to capture emotions of participants. I want to add the functionality for capturing images through webcam video streams and send to my aws function for processing it. How can I achieve this.

**Comment by hostbbb** [comment]
2 ways.

1) client side use html5 code to capture image and send data to your server to process anytime camera is on.

2) server side,  hook into the media, either directly thru mediasoup/kurento or the webm produced from a recorded media stream as it is written to disk.
