### ISSUE TITLE
v2.5.0 RTL layout - toggle button Animation does not work

### ISSUE THREAD

**Issue by Jossef-767** [bigbluebutton/bigbluebutton#14921]
**Screenshots**

https://user-images.githubusercontent.com/2356928/166148275-00268160-961e-4f54-9afe-d115d588b2f2.mp4

**BBB version:**
[v2.5.0-beta.1]

**Comment by ali-alhaidary** [comment]
Where is the problem?

**Comment by ffdixon** [comment]
Hey @Jossef-767, this is not a good bug report.  Please follow the template and make it easier for the devs to understand and reproduce the issue.

**Comment by Jossef-767** [comment]
The circle in the toggle button should move from side to side while pressing the button. Right now it just changes color and does not move.
You can change the interface back to the LTR language and see the difference while pressing the button when the animation is working

**Comment by ali-alhaidary** [comment]
@Jossef-767 yes, reproducible...

**Comment by ali-alhaidary** [comment]
@Jossef-767 kindly open a new issue using the proper template so that dev can take a look...
