### ISSUE TITLE
Improve layout selection

### ISSUE THREAD

**Issue by TiagoJacobs** [bigbluebutton/bigbluebutton#14939]
We want to improve improve layout selection window.

Proposal:

- Show two buttons: "Apply" and "Apply to all", so the user can indicate if the change is related with its current window, or to all session participants:
![image](https://user-images.githubusercontent.com/2075267/166605723-a801946b-6d1e-49a6-91e0-0d7882649ad6.png)

- When "Custom" is selected, and the "follow presenter layout" flag is enabled, only the "Apply to all" button will be shown:
![image](https://user-images.githubusercontent.com/2075267/166605710-15bef78c-1246-47ac-aadb-00499dc4b007.png)

- Make a clear indication that "custom" layout only applies to desktop;

- Rename "smart layout" to:
A) Optimized;
B) Automatic;
C) something else

**Comment by gustavotrott** [comment]
I like "Auto Layout" rather than previous "Smart Layout".
At least with this name I can understand better that it is about "responsive behavior".

**Comment by antobinary** [comment]
cc @tylercopeland too

**Comment by antobinary** [comment]
This issue goes hand-in-hand with #15863

**Comment by TiagoJacobs** [comment]
Closing it as duplicate of #15863
