### ISSUE TITLE
mirrorOwnWebcam=True not working in 2.5.0-beta.2

### ISSUE THREAD

**Issue by christmart** [bigbluebutton/bigbluebutton#14956]
**Describe the bug**
Setting public.app.mirrorOwnWebcam True in /etc/bigbluebutton/bbb-html5.yml has no effect.
It is mirrored in the preview but not mirrored in the main screen.

**To Reproduce**
Set in /etc/bigbluebutton/bbb-html5.yml
```
public:
  app:
    mirrorOwnWebcam: true
```
and share your webcam.

**Expected behavior**
You own video should be mirrored

**Actual behavior**
Own video is not mirrored

**BBB version:**
BigBlueButton Server 2.5.0-beta.2 (242)

**Desktop (please complete the following information):**
 - OS: Linux (Debian Bullseye)
 - Browser Firefox
 - Version 91.8.0

**Smartphone (please complete the following information):**
 - Device: Google Pixel 3
 - OS: Android 12
 - Browser Chrome
 - Version

**Comment by prlanzarin** [comment]
Might be a regression from https://github.com/bigbluebutton/bigbluebutton/pull/14590. Marking to verify.
