### ISSUE TITLE
Only 2 participants on the big tablet screen

### ISSUE THREAD

**Issue by dluschan** [bigbluebutton/bigbluebutton#14954]
**Describe the bug**
In the BigBlueButton conference, on the huge screen of the tablet, images from only two webcams of the interlocutors are simultaneously visible. To access the rest, you need to press the arrows.

**To Reproduce**
1. Go to BigBlueButton web conference from a tablet.
2. Wait for the rest of the participants to start the video stream.
3. Start your own video stream.

**Expected behavior**
All conference participants are visible or camera position settings available.

**Actual behavior**
Only 2 conference participants and yourself are visible and arrows to switch to others.

**Screenshots**
*the motorcycle is visible in the camera on the tablet
![IMG_0221](https://user-images.githubusercontent.com/7090815/166907045-21b2510b-4e62-4576-9d78-b7a8aabb84c0.jpeg)
![IMG_0220](https://user-images.githubusercontent.com/7090815/166907059-9610fa3a-67b2-4375-9c36-77425cef2fa4.jpeg)

**BBB version:**
BigBlueButton Server 2.4.4 (2961)

**Smartphone (please complete the following information):**
 - Device: iPad Pro (12.9-inch 3 Gen)
 - OS: iPadOS 15.4.1
 - Browser Safari and Mozilla Firefox
 - Version unknown

**Additional context**
The number of visible webcam images is not affected by the presence of other conference elements on the screen: presentation, chat, and people list.

**Comment by ramonlsouza** [comment]
Hello @dluschan! 

The default number of video streams in a page is 2 for mobile devices, but it can be changed.

You can change the pagination settings in https://github.com/bigbluebutton/bigbluebutton/blob/v2.4.x-release/bigbluebutton-html5/private/config/settings.yml#L384-L390

More information about video pagination can be found here: https://docs.bigbluebutton.org/admin/customize.html#limit-overall-media-streams

**Comment by prlanzarin** [comment]
Besides that, there's a client toggle that allows you to deactivate pagination for yourself during the session (_Settings [three dots, top right] -> Video pagination [On/Off]_).

Closing as not an issue.

**Comment by dluschan** [comment]
Thanks!
