### ISSUE TITLE
When multiple students use a whiteboard, deleting the last action is not performed in the correct order

### ISSUE THREAD

**Issue by Jossef-767** [bigbluebutton/bigbluebutton#14952]
When a teacher allows multiple students to use the whiteboard, and tries to undo the last line drawn on the board, the line actually deleted is that of another student and not the last line drawn. I noticed that the delete order matches the order of the students' names in the list of participants and not the order of the drawing on the board.

**To Reproduce**
1. Introduce a teacher and 4 different students into the class, the names of the 4 students should be are: A B C D
2. Allow common use of the board.
3. From student called A draw a line on the whiteboard
Then from a student called B draw a line on the whiteboard
Then from a student called C draw a line on the whiteboard
Then from a student called D draw a line on the whiteboard
4. Teacher **Disable the possibility for  common use of the  the whiteboard**
5. Instructor Click the undo button on the whiteboard to delete the last line drawn by student D
6. see error : delete the line drawn by student A.

**Expected behavior**
delete the last line drawn by student D

**Actual behavior**
delete the last line drawn by student A.

**BBB version:**
all versions

**Additional context**
An effective fix to this issue would be to incorporate a new whiteboard eraser tool. There are a number of pull requests that already allow this. The issue of lack of eraser  tool causes a lot of frustration for many teachers.

**Comment by antobinary** [comment]
In case this is not fixed within BBB 2.5, it should be re-tested on 2.6 with the new whiteboard - https://github.com/bigbluebutton/bigbluebutton/issues/14976

**Comment by JoVictorNunes** [comment]
Looks like this is not happening on 2.6 anymore.
