### ISSUE TITLE
[2.5] Breakout room state not correctly displayed in UI

### ISSUE THREAD

**Issue by schrd** [bigbluebutton/bigbluebutton#14982]
**Describe the bug**

After breakout rooms are terminated, breakout state is not consistent across users.

**To Reproduce**

To reproduce this I needed 4 users.

1. Open a meeting, join 4 users. At least one of them had to be viewer and had no audio connection
2. start 2 breakout rooms, do no permit users to choose their room. Assign each user a breakout room
3. connect audio in breakout rooms
4. Terminate breakout rooms before the time has finished
5. See error:
    1. Some users still had the breakout rooms displayed in the users list
    2. User 1 in screenshot (no audio connection, viewer) still had the breakout rooms panel open

I am not sure if this audio connection thin in step 1 is related or not.

**Expected behavior**
User join state in breakout rooms should be consistent across users

**Screenshots**
![Bildschirmfoto von 2022-05-09 14-08-52](https://user-images.githubusercontent.com/179952/167414911-a66aebdd-0410-44d3-a926-2489f6465db0.png)
![Bildschirmfoto von 2022-05-09 14-08-57](https://user-images.githubusercontent.com/179952/167414916-7f659b02-b81d-4996-9a8e-065124973b3b.png)

**BBB version:**

BBB 2.5 rc1+, commit a8619fda20

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Firefox
 - Version 91 ESR

**Additional Information:**
- 4 HTML5 Backend servers
- 8 HTML5 Frontend servers

**Comment by schrd** [comment]
@JoVictorNunes I mean the join audio procedure in the breakout room for the user which had no audio connection in the main room. I will try to reproduce again and see if I missed something. Which browser did you use? I had a mix of Firefox and Chrome. If I remember correctly the issue only appears in Firefox. I'll test tomorrow

**Comment by JoVictorNunes** [comment]
@schrd Thank you very much for your answer! I'll appreciate any further information!

> Which browser did you use?

Chrome 101

> the issue only appears in Firefox

That can be the missing part for me then. Thank you!

**Comment by schrd** [comment]
I tried again in rc3. I am able to reproduce this with Firefox 91 ESR and Chrome 101 on my server and on https://test25.bigbluebutton.org

**Comment by mwuttke** [comment]
I tried this with 2.5.0-rc3 as well. And I am also able to reproduce this error with Firefox 100 and Chrome 101 under Linux on my test server.

**Comment by JoVictorNunes** [comment]
Hello @schrd @mwuttke! Could any of you please record a video containing the steps? Thanks in advance!

**Comment by schrd** [comment]
@JoVictorNunes probably a misunderstanding. The issue is not in the area where the avatar is displayed but where the webcams/mobile/breakout room indicator is shown.

**Comment by antobinary** [comment]
Thanks @schrd for sending a patch for this! https://github.com/bigbluebutton/bigbluebutton/pull/15099
