### ISSUE TITLE
Add API support to enable other applications to easily upload files to a live BigBlueButton session

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#15001]
**Is your feature request related to a problem? Please describe.**
Currently, to upload a file to BigBlueButton's presentation area - such as a PDF, PowerPoint, Word, text, image, etc., the presenter uploads the file from their computer.

Some front-ends, such as Moodle, allow you to pre-upload a presentation ahead of the session.  When the session starts, BigBlueButton fetches the presentation from the Moodle and converts it.  No need to upload it manually.

We recently added an API to [insert a document into a live BigBlueButton session](https://github.com/bigbluebutton/bigbluebutton/issues/14014).

The feature is to enable a front-end to add a short-cut to the presentation upload dialog to let the user return to the

**Describe the solution you'd like**
Add two parameters to the `create` API call to enable the user to click and go to a specific page at the front-end to select files for inserting documents into a live presentation. 

The API calls would be

```
upload_external_description=Navigate to NextCloud and select the file you would like to see in the BigBlueButton session.
upload_external_url=https://nextcloud.example.com/display/files/...
```

The would display at the bottom of the presentation upload dialog.

<img width="859" alt="image" src="https://user-images.githubusercontent.com/290351/167943460-b72680ff-6247-4779-9e5e-49ab075ea6f2.png">

Clicking "Browse Files" opens `upload_external_url` in a new tab that shows the file picker for Next Cloud.  The user can then select files in NextCloud and they will be sent to the live session.

<img width="936" alt="image" src="https://user-images.githubusercontent.com/290351/167954027-f3232684-8f30-46a2-8a94-3c8b2e4e8c8c.png">

This saves the user downloading the file then uploading it to BigBlueButton, leaving them more time to focus on teaching their class.
 
**Describe alternatives you've considered**
You could pass this message and link in the moderator welcome message, but the presenter may not be the moderator.  The right place is in the upload dialog.

**Additional context**
One of the first integrations for this would would be with Next Cloud (see [send file to running room](https://github.com/sualko/cloud_bbb/pull/201)).

**Comment by amishbhavsar** [comment]
Hi, I am on Client build: 114, BigBlueButton version: 2.6.0-alpha.3. How do I enable this capability?

**Comment by ramonlsouza** [comment]
> Hi, I am on Client build: 114, BigBlueButton version: 2.6.0-alpha.3. How do I enable this capability?

Hello @amishbhavsar the parameters need to be passed in the `create` API call, more info here: https://docs.bigbluebutton.org/dev/api.html#upload-slides-from-external-application-to-a-live-bigbluebutton-session

**Comment by amishbhavsar** [comment]
Hi, I am sorry, but I am still a bit lost on how to enable this capability. I have Nextcloud and BBB Nextloud integration and I am self-hosting my BBB instance. The question, i am still unclear of is where should I create the API call?

**Comment by amishbhavsar** [comment]
@ramonlsouza , I am using the BBB Wordpress plugin to create meetings and also directly creating meetings by going to my domain accelme.com. My question is, where in BBB do I need to edit any files to add this capability? Is it the bigbluebutton.properties file?
