### ISSUE TITLE
Chat message overlap

### ISSUE THREAD

**Issue by GhaziTriki** [bigbluebutton/bigbluebutton#15004]
**Describe the bug**
Chat message overlap

**Expected behavior**
Chat message list should display without superposition.

**Actual behavior**
Some chat message shows overlapping.

**Screenshots**
![image](https://user-images.githubusercontent.com/4991088/168164355-a003154a-cbb0-4df2-b43a-299b00afcbce.png)

**BBB version:**
BigBlueButton Server 2.4.7

**Desktop (please complete the following information):** (Will update)
 - OS: [e.g. Windows, Mac]
 - Browser [e.g. Chrome, Safari]

**Smartphone (please complete the following information):** (Will update)
 - Browser [e.g. stock browser, Safari]

**Comment by antobinary** [comment]
Hi @GhaziTriki 
Please provide the steps to reproduce
