### ISSUE TITLE
about is still showing 2.5-rc1 in a 2.5-rc2 server

### ISSUE THREAD

**Issue by ali-alhaidary** [bigbluebutton/bigbluebutton#15017]
BigBlueButton Server 2.5.0-rc.2 (270)
![Screenshot 2022-05-15 at 00-31-24 aldarce - الغرفة الرئيسية](https://user-images.githubusercontent.com/75235623/168448828-c777717a-732b-4b95-b480-fc2ebae004d6.png)

**Comment by ali-alhaidary** [comment]
After a fresh ubuntu box install, the about screen shows:
![Screenshot 2022-05-15 at 03-50-53 الدرس - الغرفة الرئيسية](https://user-images.githubusercontent.com/75235623/168454704-25267e01-9ccb-4f35-93e3-b327c9e14b9c.png)

**Comment by ffdixon** [comment]
We just released 2.5.0-rc.3.  Can you update your server and let us know if the build version is now properly propagated to the client.  https://github.com/bigbluebutton/bigbluebutton/releases/tag/2.5.0-rc.3

**Comment by ali-alhaidary** [comment]
upgraded from 2.5.0-rc.2 to 2.5.0-rc.3
![Screenshot 2022-05-16 at 09-53-35 الدرس - الغرفة الرئيسية](https://user-images.githubusercontent.com/75235623/168541787-8e49dfab-89a3-475f-bd2c-7da0b85a2ac6.png)
