### ISSUE TITLE
Error 1102 v2.5.0-rc2

### ISSUE THREAD

**Issue by ali-alhaidary** [bigbluebutton/bigbluebutton#15019]
**Describe the bug**
Error 1102 when trying to share a screen

**To Reproduce**
1. Go to a session
2. Click on share screen
3. Scroll down to an open window
4. See error 1102 not allowing share screen

**Expected behavior**
share screen with others

**Actual behavior**
error 1102

**BBB version:**
BigBlueButton Server 2.5.0-rc.2 (270)

**Comment by ffdixon** [comment]
Hi Ali,

Again, you need to give us more information.  Imagine you are asking a peer to reproduce this problem - what browser should they use?  Are you able to reproduce the issue on https://test25.bigbluebutton.org?

Can you give us a screen shot of the errro.

**Comment by ali-alhaidary** [comment]
Hi Fred,
Sorry for that, this is a first for us that installing did not go well, we are getting used to the smooth process for long time.
We spent the past few hours in preparing a fresh ubuntu box and did the installation and running the same script for customization of the files in https://github.com/bigbluebutton/bigbluebutton/issues/15020 and moved recording to it as it is in production for small group.
All are running well in the new box, however, if we reboot that box, and use bbb-conf --restart, recording stops showing (attached screen shot) and the dots that usually follows checking for potential problems disappear.
![Screenshot 2022-05-15 at 04-03-50 الغرفة الرئيسية](https://user-images.githubusercontent.com/75235623/168454569-9b61f9f1-0d51-45bd-85dc-4f4fd036d5f3.png)

It is clear that most of the problems were because of upgrading from rc1 to rc2.

**Comment by ali-alhaidary** [comment]
we still have the upgraded box, if you need its logs, we will be more than happy to provide...

**Comment by ali-alhaidary** [comment]
Error 1102 is not showing with the new box accessed form ubuntu, mac and windows. BBB in working as expected in all browsers.

**Comment by ali-alhaidary** [comment]
Thank you...
