### ISSUE TITLE
bbb-webrtc-sfu is not starting in v2.5.0-rc.2

### ISSUE THREAD

**Issue by ali-alhaidary** [bigbluebutton/bigbluebutton#15018]
BigBlueButton Server 2.5.0-rc.2 (270)

nginx —————————————————► [✔ - active]
freeswitch ————————————► [✔ - active]
redis-server ——————————► [✔ - active]
bbb-apps-akka —————————► [✔ - active]
bbb-fsesl-akka ————————► [✔ - active]
mongod ————————————————► [✔ - active]
bbb-html5 —————————————► [✔ - active]
bbb-webrtc-sfu ————————► [✘ - failed]
kurento-media-server ——► [✔ - active]
bbb-html5-backend@1 ———► [✔ - active]
bbb-html5-backend@2 ———► [✔ - active]
bbb-html5-frontend@1 ——► [✔ - active]
bbb-html5-frontend@2 ——► [✔ - active]
etherpad ——————————————► [✔ - active]
bbb-web ———————————————► [✔ - active]
bbb-pads ——————————————► [✔ - active]

This is a first that bbb-webrtc-sfu is not starting.

**Comment by ffdixon** [comment]
Hi Ahi,

I just tried an install and didn't get an error.  We need more information to debug this
  - what is the command you used to install 2.5.0-rc.2?
  - What is the output of `sudo bbb-conf --check`
  - What is the output of `journalctl -u bbb-webrtc-sfu`

**Comment by ali-alhaidary** [comment]
Hello @ffdixon 
> Hi Ahi,
> 
> I just tried an install and didn't get an error. We need more information to debug this
> 
>     * what is the command you used to install 2.5.0-rc.2?
>wget -qO- https://ubuntu.bigbluebutton.org/bbb-install-2.5.sh | bash -s -- -v focal-250 -s aldarce.the5stars.org -e the5stars.servant@the5stars.org  -w -g

>     * What is the output of `sudo bbb-conf --check`
> https://github.com/bigbluebutton/bigbluebutton/issues/15020

>     * What is the output of `journalctl -u bbb-webrtc-sfu`
-- Logs begin at Fri 2022-03-25 12:27:44 UTC, end at Sat 2022-05-14 23:19:09 UTC. --
Mar 25 13:18:42 aldarce systemd[1]: Started BigBlueButton WebRTC SFU.
Mar 25 13:18:42 aldarce bbb-webrtc-sfu[39541]: WARNING: NODE_ENV value of 'production' did not match any deployment config file names.
Mar 25 13:18:42 aldarce bbb-webrtc-sfu[39541]: WARNING: See https://github.com/lorenwest/node-config/wiki/Strict-Mode
Mar 25 13:18:42 aldarce bbb-webrtc-sfu[39541]: 2022-03-25T13:18:42.817Z - info: [HttpServer] Listening host=localhost:3016
Mar 25 13:18:42 aldarce bbb-webrtc-sfu[39541]: 2022-03-25T13:18:42.897Z - info: [sfu-mcs-api] Connecting to MCS at ws://localhost:3010/mcs
Mar 25 13:18:42 aldarce bbb-webrtc-sfu[39541]: 2022-03-25T13:18:42.902Z - info: [process-wrapper] Forking process name=core, ipc=native, path=./lib/mcs-core/pr>
Mar 25 13:18:42 aldarce bbb-webrtc-sfu[39541]: 2022-03-25T13:18:42.909Z - info: [process-wrapper] Forking process name=screenshare, ipc=native, path=./lib/scre>
Mar 25 13:18:42 aldarce bbb-webrtc-sfu[39541]: 2022-03-25T13:18:42.912Z - info: [process-wrapper] Forking process name=video, ipc=native, path=./lib/video/Vide>
Mar 25 13:18:42 aldarce bbb-webrtc-sfu[39541]: 2022-03-25T13:18:42.916Z - info: [process-wrapper] Forking process name=fullaudio, ipc=native, path=./lib/audio/>
Mar 25 13:18:42 aldarce bbb-webrtc-sfu[39541]: 2022-03-25T13:18:42.980Z - error: [sfu-mcs-api] SFU socket connection to mcs-core failed due to connect ECONNREF>
Mar 25 13:18:42 aldarce bbb-webrtc-sfu[39541]: 2022-03-25T13:18:42.982Z - error: [sfu-mcs-api] SFU socket connection to mcs-core closed unexpectedly
Mar 25 13:18:43 aldarce bbb-webrtc-sfu[39623]: WARNING: NODE_ENV value of 'production' did not match any deployment config file names.
Mar 25 13:18:43 aldarce bbb-webrtc-sfu[39623]: WARNING: See https://github.com/lorenwest/node-config/wiki/Strict-Mode
Mar 25 13:18:43 aldarce bbb-webrtc-sfu[39629]: WARNING: NODE_ENV value of 'production' did not match any deployment config file names.
Mar 25 13:18:43 aldarce bbb-webrtc-sfu[39629]: WARNING: See https://github.com/lorenwest/node-config/wiki/Strict-Mode
Mar 25 13:18:43 aldarce bbb-webrtc-sfu[39630]: WARNING: NODE_ENV value of 'production' did not match any deployment config file names.
Mar 25 13:18:43 aldarce bbb-webrtc-sfu[39630]: WARNING: See https://github.com/lorenwest/node-config/wiki/Strict-Mode
Mar 25 13:18:43 aldarce bbb-webrtc-sfu[39636]: WARNING: NODE_ENV value of 'production' did not match any deployment config file names.
Mar 25 13:18:43 aldarce bbb-webrtc-sfu[39636]: WARNING: See https://github.com/lorenwest/node-config/wiki/Strict-Mode
lines 1-20

**Comment by ffdixon** [comment]
Can you give us the contents of ` /tmp/bbb-webrtc-sfu.txt` from the command

```
journalctl -u bbb-webrtc-sfu > /tmp/bbb-webrtc-sfu.txt
```

**Comment by ffdixon** [comment]
Was this a clean install on a new Ubuntu 20.04 server, or was it an upgrade from a previous version of 2.5-dev or 2.5-rc?

**Comment by ali-alhaidary** [comment]
it was an upgrade from 2.5.0-rc1 running on ubuntu 20.04, but with  a clean ubuntu 20.04 server bbb-webrtc-sfu is active.

**Comment by ffdixon** [comment]
Hmm ... I just tried an upgrade form 2.5.0-rc1 (with Greenlight option '-g') to 2.5.0-rc1 (with Greenlight option '-g') and my recordings are appearing. When you upgraded, did you notice if a new version of Greenlight was pulled down?

**Comment by ali-alhaidary** [comment]
As a mater of fact, yes, I noticed that it pulled some updated Arabic strings that used to cause some errors in the main screen when Arabic language was selected.https://github.com/bigbluebutton/greenlight/issues/3351

**Comment by ali-alhaidary** [comment]
Thank you, issue is sorted out in v2.5.0-rc3
