### ISSUE TITLE
Potential problems in v2.5.0-rc2

### ISSUE THREAD

**Issue by ali-alhaidary** [bigbluebutton/bigbluebutton#15020]
**Describe the bug**
a conflicting results when running bbb-conf --check

**To Reproduce**
I could not reproduce it, but the case was like this:
After upgrading from v2.5.0-rc1 to v2.5.0-rc2 no potential problems were reported.
After making the usual modifications on:
/opt/freeswitch/etc/freeswitch/autoload_configs/conference.conf.xml
/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml
/usr/local/bigbluebutton/core/scripts/presentation.yml
/usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties
cp turn-stun-servers.xml /usr/share/bbb-web/WEB-INF/classes/spring/turn-stun-servers.xml

And running bbb-conf --check, the following error was reported:
Potential problems described below
/usr/bin/bbb-conf: line 869: 23120 Done                    echo "/quit"
     23121 Segmentation fault      (core dumped) | /opt/freeswitch/bin/fs_cli -p $ESL_PASSWORD - > /dev/null 2>&1

 Error: Unable to connect to the FreeSWITCH Event Socket Layer on port 8021

And after rebooting the server, this error disappeared, however, the series of (dots)  .................... that used to show when checking for potential problems also disappeared as well when using bbb-conf --check.

**Comment by ffdixon** [comment]
We appreciate your reports, but you need to provide enough information for us to reproduce.  There just isn't enough information for us to know what changes you have made.

> After making the usual modifications on:
> /opt/freeswitch/etc/freeswitch/autoload_configs/conference.conf.xml
> /usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml
> /usr/local/bigbluebutton/core/scripts/presentation.yml
> /usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties
> cp turn-stun-servers.xml /usr/share/bbb-web/WEB-INF/classes/spring/turn-stun-servers.xml

FreeSWITCH should *not* core dump.  Can you share the configuration changes you've made so we can try and reproduce?

**Comment by ali-alhaidary** [comment]
We have been using a script to nano these files and visually inspect before saving for a long time now to automate the customization in each and every BBB server.
 **/opt/freeswitch/etc/freeswitch/autoload_configs/conference.conf.xml commented:**
`     <param name="sound-prefix" value="$${sounds_dir}/en/us/callie"/>`
`      <param name="muted-sound" value="conference/conf-muted.wav"/>`
`      <param name="unmuted-sound" value="conference/conf-unmuted.wav"/>`
`      <param name="alone-sound" value="conference/conf-alone.wav"/>`
`      <param name="moh-sound" value="$${hold_music}"/>`
`      <param name="enter-sound" value="tone_stream://%(200,0,500,600,700)"/>`
`      <param name="exit-sound" value="tone_stream://%(500,0,300,200,100,50,25)"/>`
`      <param name="kicked-sound" value="conference/conf-kicked.wav"/>`

 **/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml**
    clientTitle: الدرس
    appName: aldarce HTML5 Client
    helpLink: https://the5stars.org/assist/

        fallbackLocale: ar
        overrideLocale: ar

  notes:
    enabled: false
    id: notes

 **/usr/local/bigbluebutton/core/scripts/presentation.yml commented webm and uncomment mp4**

 **/usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties**
defaultWelcomeMessage=مرحباً بكم في الدرس

**Comment by ali-alhaidary** [comment]
After upgrading from v2.5.0-rc.2 to v2.5.0-rc.3 all checks are active, server is working as expected so far, we will need to get some response from users.
Thank you...
