### ISSUE TITLE
WebRTC issue: Error 1002: Could not make a WebSocket connection

### ISSUE THREAD

**Issue by MBM1607** [bigbluebutton/bigbluebutton#15027]
I have a working BBB server. Upon creating a clone of this server through snapshot using AWS EC2, I am facing this issue on the clone.

After cloning I ran 
```sudo bbb-conf --setip```
command and manually changed ip in files that aren't affected by that as well.

## Result of ```sudo bbb-conf --check```

```
BigBlueButton Server 2.3.16 (2521)
                    Kernel version: 5.4.0-1072-aws
                      Distribution: Ubuntu 18.04.6 LTS (64-bit)
                            Memory: 15917 MB
                         CPU cores: 8

/etc/bigbluebutton/bbb-web.properties (override for bbb-web)
/usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties (bbb-web)
       bigbluebutton.web.serverURL: https://clone-meet.tutorbees.net
                defaultGuestPolicy: ALWAYS_ACCEPT
                 svgImagesRequired: true

/etc/nginx/sites-available/bigbluebutton (nginx)
                       server_name: clone-meet.tutorbees.net
                              port: 80, [::]:80
                              port: 443 ssl

/opt/freeswitch/etc/freeswitch/vars.xml (FreeSWITCH)
                       local_ip_v4: 172.31.9.2
                   external_rtp_ip: 52.66.6.31
                   external_sip_ip: 52.66.6.31

/opt/freeswitch/etc/freeswitch/sip_profiles/external.xml (FreeSWITCH)
                        ext-rtp-ip: $${external_rtp_ip}
                        ext-sip-ip: $${external_sip_ip}
                        ws-binding: 52.66.6.31:5066
                       wss-binding: 52.66.6.31:7443

/usr/local/bigbluebutton/core/scripts/bigbluebutton.yml (record and playback)
                     playback_host: clone-meet.tutorbees.net
                 playback_protocol: https
                            ffmpeg: 4.2.4-1ubuntu0.1bbb2~18.04

/etc/bigbluebutton/nginx/sip.nginx (sip.nginx)
                        proxy_pass: 52.66.6.31
                          protocol: https

/usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml (Kurento SFU)
                        kurento.ip: 52.66.6.31
                       kurento.url: ws://127.0.0.1:8888/kurento
                    kurento.sip_ip: 52.66.6.31
                    localIpAddress: 172.31.0.66
               recordScreenSharing: true
                     recordWebcams: true
                  codec_video_main: VP8
               codec_video_content: VP8

/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml (HTML5 client)
/etc/bigbluebutton/bbb-html5.yml (HTML5 client config override)
                             build: 1864
                        kurentoUrl: wss://clone-meet.tutorbees.net/bbb-webrtc-sfu
                  enableListenOnly: true
                    sipjsHackViaWs: true

/usr/share/bbb-web/WEB-INF/classes/spring/turn-stun-servers.xml (STUN Server)
                              stun: clone-turn.tutorbees.net:443

/etc/kurento/modules/kurento/WebRtcEndpoint.conf.ini (STUN Server)
                              stun: 3.108.10.213:443
```

## Result of ```sudo bbb-conf --status```

```
nginx —————————————————► [✔ - active]
freeswitch ————————————► [✔ - active]
redis-server ——————————► [✔ - active]
bbb-apps-akka —————————► [✔ - active]
bbb-fsesl-akka ————————► [✔ - active]
mongod ————————————————► [✔ - active]
bbb-html5 —————————————► [✔ - active]
bbb-webrtc-sfu ————————► [✔ - active]
kurento-media-server ——► [✔ - active]
bbb-html5-backend@1 ———► [✔ - active]
bbb-html5-backend@2 ———► [✔ - active]
bbb-html5-frontend@1 ——► [✔ - active]
bbb-html5-frontend@2 ——► [✔ - active]
etherpad ——————————————► [✔ - active]
bbb-web ———————————————► [✔ - active]
```

## Viewed and Tried Issues
I have tried all solutions in [Issue# 6766](https://github.com/bigbluebutton/bigbluebutton/issues/6766) and [Issue# 2628](https://github.com/bigbluebutton/bigbluebutton/issues/2628).

## Attached configuration files
ip's are intentionally spoofed. 

[WebRTCEndpoint.conf.ini.txt](https://github.com/bigbluebutton/bigbluebutton/files/8700673/WebRTCEndpoint.conf.ini.txt)
[vars.xml.txt](https://github.com/bigbluebutton/bigbluebutton/files/8700674/vars.xml.txt)
[sip.nginx.txt](https://github.com/bigbluebutton/bigbluebutton/files/8700675/sip.nginx.txt)
[external.xml.txt](https://github.com/bigbluebutton/bigbluebutton/files/8700676/external.xml.txt)
[default.yml.txt](https://github.com/bigbluebutton/bigbluebutton/files/8700677/default.yml.txt)
[bigbluebutton-sip.properties.txt](https://github.com/bigbluebutton/bigbluebutton/files/8700678/bigbluebutton-sip.properties.txt)

**Comment by AlexJezior** [comment]
Simply creating a clone from a snapshot doesn't work because the `--setip` function doesn't work entirely. I have found that re-running the installation script on the server is your best option. 

On your cloned server, run the following command, and after it's finished, it should be working again.

`wget -qO- https://ubuntu.bigbluebutton.org/bbb-install.sh | sudo bash -s -- -v bionic-230-2.3.16 -s YOUR-DOMAIN-HERE.com -e admin@YOUR-DOMAIN-HERE.com -w`

Also, I would recommend installing the latest 2.3 version (2.3.17) for the latest security improvements.

**Comment by MBM1607** [comment]
Thank you @AlexJezior  very much. This resolved the issue

**Comment by ffdixon** [comment]
> Also, I would recommend installing the latest 2.3 version (2.3.17) for the latest security improvements.

We recommend installing the latest build of 2.4 (not 2.3).

As 2.5 is fast approaching, 2.3 will reach end of life and the focus of development will shift to 2.4 and 2.5.
