### ISSUE TITLE
Camera icon

### ISSUE THREAD

**Issue by ali-alhaidary** [bigbluebutton/bigbluebutton#15024]
**Describe the bug**
camera icon is kept active although camera is disabled in data saving settings.

**To Reproduce**
1. start a session
2. Go to settings
3. Click on data savings
4. deactivate share screen and camera.
5. press save.

**Expected behavior**
share screen and camera icons are deactivated.

**Actual behavior**
share screen icon is deactivated and camera icon is still active to press.

**BBB version:**
BigBlueButton Server 2.5.0-rc.3 (2976)

**Desktop (please complete the following information):**
 - OS: varies
 - Browser varies
 - Version varies

**Smartphone (please complete the following information):**
 - Device: varies
 - OS:varies
 - Browser varies
 - Version varies

**Additional context**
The issue is the same if data saving (share screen and camera) are set to false server side.

**Comment by prlanzarin** [comment]
That's expected behavior. Camera sharing is allowed in data savings mode - just viewing is disabled.

IMO we should do the same to screen sharing if it isn't allowed.

**Comment by ali-alhaidary** [comment]
From a user view point, both icons should be disabled if data saving is disabled, otherwise, the user will click on the camera icon thinking he is sharing his camera while he is not. This can be very miss leading.

**Comment by prlanzarin** [comment]
> From a user view point, both icons should be disabled if data saving is disabled, otherwise, the user will click on the camera icon thinking he is sharing his camera while he is not. This can be very miss leading.

As I mentioned: the user is **allowed to share** their camera even with Data savings is enabled. That is by design. **Only viewing is disabled**. I don't understand how that is misleading.
