### ISSUE TITLE
[2.5-rc3] shared notes not always accessible in breakout rooms

### ISSUE THREAD

**Issue by schrd** [bigbluebutton/bigbluebutton#15025]
**Describe the bug**
When testing #15022 I discovered that sometimes shared notes are not accessible in breakout rooms. I could reproduce this on test25.bigbluebutton.org

**To Reproduce**
1. Start a fresh meeting
2. open shared notes
3. start a breakout session, join it
4. in the breakout room open shared notes ASAP
5. sometimes etherpad won't load.

**Expected behavior**
shared notes should always work

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Firefox ESR
 - Version 91.9 ESR

**Additional context**

I could reproduce this on test25.bigbluebutton.org (which probably does not have PR #15022 merged. So I doubt that it is related to this PR. If you want to grab logs on test25.bigbluebutton.org, the meetingId was `bd878ad02f1f00d6d354c0c5f49f8a57fe07b1ef-1652691849208`.

On my server I got the following logs from bbb-pads systemd journal:

~~~
May 16 10:58:05 bbb-server bbb-pads[115195]: 2022-05-16T08:58:05.643Z INFO         [handler] meeting created {"meetingId":"813714c43b7c73a52b3e36e12b351016eccbf783-1652691485633"}
May 16 10:58:05 bbb-server bbb-pads[115195]: 2022-05-16T08:58:05.952Z INFO         [handler] group created {"meetingId":"813714c43b7c73a52b3e36e12b351016eccbf783-1652691485633","externalId":"notes","model":"notes"}
May 16 10:58:06 bbb-server bbb-pads[115195]: 2022-05-16T08:58:06.252Z INFO         [handler] pad created {"meetingId":"813714c43b7c73a52b3e36e12b351016eccbf783-1652691485633","groupId":"g.fov39719ADUiIMpT","name":"notes"}
May 16 10:58:07 bbb-server bbb-pads[115195]: 2022-05-16T08:58:07.453Z INFO         [handler] user created {"meetingId":"813714c43b7c73a52b3e36e12b351016eccbf783-1652691485633","userId":"w_10mj9zguqqpd"}
May 16 10:58:17 bbb-server bbb-pads[115195]: 2022-05-16T08:58:17.968Z INFO         [handler] session created {"meetingId":"813714c43b7c73a52b3e36e12b351016eccbf783-1652691485633","groupId":"g.fov39719ADUiIMpT","userId":"w_10mj9zguqqpd"}
May 16 10:59:07 bbb-server bbb-pads[115195]: 2022-05-16T08:59:07.664Z INFO         [handler] meeting created {"meetingId":"a9abdc85689d4f6abbec298846165c055042cac7-1652691547653"}
May 16 10:59:07 bbb-server bbb-pads[115195]: 2022-05-16T08:59:07.666Z INFO         [handler] meeting created {"meetingId":"de490688dd8baf9f7095d0931bc0bd342568b6a7-1652691547653"}
May 16 10:59:07 bbb-server bbb-pads[115195]: 2022-05-16T08:59:07.685Z ERROR         [api] locked {"id":"createGroup"}
May 16 10:59:07 bbb-server bbb-pads[115195]: 2022-05-16T08:59:07.686Z ERROR         [database] group creating {"meetingId":"de490688dd8baf9f7095d0931bc0bd342568b6a7-1652691547653","externalId":"notes","model":"notes"}
May 16 10:59:07 bbb-server bbb-pads[115195]: 2022-05-16T08:59:07.686Z ERROR         [handler] group creating {"meetingId":"de490688dd8baf9f7095d0931bc0bd342568b6a7-1652691547653","body":{"externalId":"notes","model":"notes"}}
May 16 10:59:07 bbb-server bbb-pads[115195]: 2022-05-16T08:59:07.924Z INFO         [handler] group created {"meetingId":"a9abdc85689d4f6abbec298846165c055042cac7-1652691547653","externalId":"notes","model":"notes"}
May 16 10:59:08 bbb-server bbb-pads[115195]: 2022-05-16T08:59:08.224Z INFO         [handler] pad created {"meetingId":"a9abdc85689d4f6abbec298846165c055042cac7-1652691547653","groupId":"g.8V7OTzr96HBIC9Pw","name":"notes"}
May 16 10:59:10 bbb-server bbb-pads[115195]: 2022-05-16T08:59:10.726Z INFO         [handler] user created {"meetingId":"a9abdc85689d4f6abbec298846165c055042cac7-1652691547653","userId":"w_3fpgd3wfrhyo"}
May 16 10:59:49 bbb-server bbb-pads[115195]: 2022-05-16T08:59:49.476Z INFO         [handler] session created {"meetingId":"a9abdc85689d4f6abbec298846165c055042cac7-1652691547653","groupId":"g.8V7OTzr96HBIC9Pw","userId":"w_3fpgd3wfrhyo"}
~~~

I did some further investigations. It looks like a race condition. It is more likely to see the issue if there are only few seconds between step 3 and 4.

**Comment by pedrobmarin** [comment]
Hmmm, good catch.

The problem seems to be in the time between Etherpad's API calls. I believe we could introduce a query in bbb-pads to hold the events that are dependent from another. Especially session that depends on user and group creation.

**Comment by pedrobmarin** [comment]
I'll leave this issue opened until other developers can test if, indeed, `bbb-pads` v1.2.1 fixed this issue.

**Comment by mwuttke** [comment]
I tried to open the shared notes as a participant in a breakout room as well. And I am also able to reproduce this error with Firefox 100 and Chrome 101 under Linux on my test server with bbb 2.5.0-rc3.

**Comment by schrd** [comment]
> I'll leave this issue opened until other developers can test if, indeed, `bbb-pads` v1.2.1 fixed this issue.

I tested it under the same conditions as yesterday and I'm no longer able to reproduce this with bbb-pads v1.2.1.

**Comment by antobinary** [comment]
@mwuttke I just upgraded https://test25.bigbluebutton.org with the latest changes, including bbb-pads to 1.2.1

```
$ grep version /usr/local/bigbluebutton/bbb-pads/package.json 
  "version": "1.2.1",
```
Anychance you could [also] confirm it resolved there?

**Comment by mwuttke** [comment]
I'm no longer able to reproduce this error with bbb-pads v1.2.1 in the breakout rooms but when I terminate the breakout rooms or just leaving a breakout room, I still could not access the shared notes in the main room whether as moderator or participant. I tested this scenario on my test servers (with bbb 2.5.0-rc3) and on https://test25.bigbluebutton.org.

**Comment by pedrobmarin** [comment]
> I'm no longer able to reproduce this error with bbb-pads v1.2.1 in the breakout rooms but when I terminate the breakout rooms or just leaving a breakout room, I still could not access the shared notes in the main room whether as moderator or participant. I tested this scenario on my test servers (with bbb 2.5.0-rc3) and on https://test25.bigbluebutton.org.

I was able to reproduce this issue. It's related to cookies in the same domain.

There's a chance #15022 fixes this problem too. If it doesn't, please open a new issue for it and I'll try to take a look.

**Comment by antobinary** [comment]
I just upgraded https://test25.bigbluebutton.org again (includes https://github.com/bigbluebutton/bigbluebutton/pull/15022 ) -- perhaps @mwuttke could try to reproduce the use case again?

**Comment by mwuttke** [comment]
I just testet the behavior in the breakout rooms and in the main room in relation to the shared notes on https://test25.bigbluebutton.org again and I can't reproduce the use case again! ;-)
