### ISSUE TITLE
with Acrobat changed PDF is not displayed correctly in recording

### ISSUE THREAD

**Issue by christmart** [bigbluebutton/bigbluebutton#15035]
**Describe the bug**
A PDF file with scans included which were cut in Acrobat to crop unwanted parts of the scan is correctly displayed in the BBB session. In the recording, the original uncropped images are shown. It seams that pdftocairo converts the wrong embedded image inside the PDF. In the BBB session the PDF is first converted to SVG. On this path the the error does not appear. The problem is in BBB 2.4 and 2.5.

**To Reproduce**
Use the PDF from https://seafile.rlp.net/f/52c8026382294636bcf3/?dl=1 and load it into the BBB session. You can see on four pages different cropped parts from the same cartoon page. 
Record the session and change to the different pages.
End the session and look at the recording. You will see the raw uncropped scans on every page of the presentation.

**Expected behavior**
See the same pages in the recording as in the BBB session

**Actual behavior**
You see the unedited images in the recording.

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Firefox
 - Version 91.9

**Comment by ffdixon** [comment]
Thanks Chris -- we have this as an open issue. Merging into https://github.com/bigbluebutton/bigbluebutton/issues/9680.

**Comment by christmart** [comment]
@ffdixon Do you have an idea for a fix?

**Comment by christmart** [comment]
The problem is, that the user does not know in advance that the PDF has this problem. 
He will only see the problem after the session is finished in the recording.
We need a solution where every PDF is rendered correctly in the recording like in the presentation.

**Comment by ffdixon** [comment]
If the PDF has any scanned images, then they may encounter this issue.  It's not all PDFs with scanned images, but it's definitely worth uploading it to a test session (they can use https://test.bigbluebutton.org/) ahead for a quick check.
