### ISSUE TITLE
Retire the Pads Session Manager

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#15038]
In #15022 @pedrobmarin pointed out that the session manager is likely obsolete: 

> This change might replace the session manager inside the client https://github.com/bigbluebutton/bigbluebutton/tree/v2.5.x-release/bigbluebutton-html5/imports/ui/components/pads/sessions . I guess there's no need to have the `sessionID` both in the cookie and the url

_Originally posted by @pedrobmarin in https://github.com/bigbluebutton/bigbluebutton/issues/15022#issuecomment-1130257446_

- [ ] understand what's going on
- [ ] confirm the session manager is obsolete
- [ ] remove it, retest

**Comment by pedrobmarin** [comment]
Right. If this is the case yet, at some point we started to use the session id at the url. So the session cookies can be removed
