### ISSUE TITLE
Security vulnerability in voting: Injections via the text field in "Participant response".

### ISSUE THREAD

**Issue by VITSarah** [bigbluebutton/bigbluebutton#15034]
A poll was performed with the participant response type.

When displaying the results in the chat, the following phenomenon occurs for two out of 30 answers:

Each time a user scrolls, the number of two answers in the chat increases. 
The number displayed is user dependent. And when the tab is closed and one re-enters the session, the number starts at 0 for these two answers and increases again when scrolling.

The problem occurs in only one of many polls in this session and affects exactly two answers that sound quite similar. For this reason, there is a suspicion that two students were having a joke. 

Therefore, the question is whether security mechanisms have been implemented so far to prevent certain strings from being inserted into the text field or to transfer them into a harmless form?

**Screenshots**
![Issue](https://user-images.githubusercontent.com/74904637/169000865-1d840f8d-85e7-4fd0-a716-677ef96fbaf7.png)

**Desktop (please complete the following information):**
 - OS: Windows & MAC
 - Browser: Chrome

**Comment by antobinary** [comment]
Hi @VITSarah 

Thanks for reporting this to us. Please follow the Reporting-A-Vulnerability protocol in future https://github.com/bigbluebutton/bigbluebutton/security/policy#reporting-a-vulnerability 

We're looking into the issue you reported

**Comment by antobinary** [comment]
Hi @VITSarah,

Could you please reach out to us by email on security at bigbluebutton dot org?
We'd like to get a little bit more information about what you reported, but have not been able to find a different way of messaging you.

**Comment by antobinary** [comment]
Update - we're in touch with the reporter via the email address above. I will close this issue now as we're tracking it in the way we track security reports.

**Comment by antobinary** [comment]
Copying @ramonlsouza -- "It was not a security issue, but an error caused by wrong grouping of similar answers (like Blue and blue). Should be fixed by https://github.com/bigbluebutton/bigbluebutton/pull/15174"
