### ISSUE TITLE
[2.4.7] Autoswaplayout/RestoreOnUpdate new presentation fails to show

### ISSUE THREAD

**Issue by einhirn** [bigbluebutton/bigbluebutton#15042]
**Describe the bug**
We're using `autoSwapLayout: true` and `restoreOnUpdate: true`. When uploading a new document, the presentation area doesn't get restored reliably. This happens with both/either/none of the presenters and viewers (with 1 presenter 1 viewer we saw every permutation).

**To Reproduce**
1. Start session, presentation will be minimized
2. Presenter uploads new document
3. Observe whether the presentation was restored after converting the document on either presenter or viewer screen.

**Expected behavior**
Presentation should restore if minimized.

**Actual behavior**
Presentation doesn't restore reliably when uploading a new document.

**BBB version:**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 101.0.4951.67 64Bit

**Comment by ramonlsouza** [comment]
Hello @einhirn I tried to reproduce the bug, but looks like it is not happening in my tests. I have a few questions that might help narrowing it:
1. does it also happen if you set `userdata-bbb_auto_swap_layout=true` and `userdata-bbb_force_restore_presentation_on_new_events=true` join parameters?
2. does it happen with any document you upload?
3. does it happen with any supported document type? (pdf, txt, images)
4. if you have more than 1 presenter + 1 viewer when the bug happens, does it fail to restore the presentation for all of them?
5. do you have any other custom settings that might be affecting `restoreOnUpdate` behavior?

**Comment by einhirn** [comment]
Hello,

my colleague did a test run on two of our bbb nodes and uploaded 20 different PPTX and PDF files to each of them. In both tests there were 5 cases where the presentation wasn't restored - with this small sample we arrive at a probability of 25% for the presentation not restoring. It seems to happen more often with larger files where the conversion process takes longer (up to 1 minute during the tests). Also there seems to be a correlation with client compute power: the slower clients seemed to "miss" the restore trigger more often. But all in all it seems more like random, hard to reproduce. If it didn't work this time, the next time in the same session may work fine again.

Concerning your questions:

1. I'd need to change the configuration back to default for a test server and test it via userdata in the "create" api call. Correct?
2. Yes, it can happen with any document.
3. I didn't test images or txt files, just PPTX and PDF, because that's what's usually used.
4. No, it's kind of random. As if some of the clients don't get the message to restore presentation.
5. I can attach our override file - I don't know which setting might affect restoreOnUpdate behavior... [bbb-html5.yml.txt](https://github.com/bigbluebutton/bigbluebutton/files/8796719/bbb-html5.yml.txt)
