### ISSUE TITLE
Data Saving

### ISSUE THREAD

**Issue by ali-alhaidary** [bigbluebutton/bigbluebutton#15059]
**Describe the bug**
If data saving is set to 'false'  server side, then the client will see that it is disabled in his settings (red), however, the screen share icon is not clickable but the camera is. This makes some users [edited] confused of the situation.

**To Reproduce**
1. set data saving to 'false' server side.
2. open a new session
3. check data saving in settings, they are (red)
4. screen share in not clickable.
5. camera icon is clickable.

**Expected behavior**
camera icon is not clickable.

**Actual behavior**
camera icon is clickable.

**Screenshots**

**BBB version:**
bbb v2.5.0-rc4

**Additional context**
Users are not fully understanding the use case of such situation, if they can use the camera why would it be disabled in settings ?
And if it is not shared, even if the user use the camera, he will think that his video is being sent to all session members

**Comment by ali-alhaidary** [comment]
Any ideas?

**Comment by JoVictorNunes** [comment]
In my opinion this is the intended behavior. The data saving is just to disable other participants webcams, not yours. Therefore, you still can share your webcam. But it's just a guess, I'll take a deeper look at this.

**Comment by ali-alhaidary** [comment]
@JoVictorNunes thanks...

**Comment by JoVictorNunes** [comment]
So, here's the thing:
If 'Enable other participants webcam' is disabled, the user won't see other participants webcams, just his own (if shared). He still will be able to share his webcam with other participants. Thus, his video (if shared) will be sent to other participants even though he can't see other participants webcams.
