### ISSUE TITLE
defaultWelcomeMessageFooter is missing from /usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties

### ISSUE THREAD

**Issue by ali-alhaidary** [bigbluebutton/bigbluebutton#15058]
**Describe the bug**
defaultWelcomeMessageFooter is missing from /usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties

**To Reproduce**
nano /usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties

**Expected behavior**
defaultWelcomeMessageFooter is found

**Actual behavior**
defaultWelcomeMessageFooter is not found

**Comment by ffdixon** [comment]
We just checked this on a clean install of 2.5.0-rc.3 and it's there

```
# cat  /usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties | grep -i footer
defaultWelcomeMessageFooter=This server is running <a href="https://bigbluebutton.org/" target="_blank"><u>BigBlueButton</u></a>.
```

**Comment by ali-alhaidary** [comment]
Is it there on 2.5.0-rc4?

Ali

**Comment by ffdixon** [comment]
Yes.  I meant to write `BigBlueButton Server 2.5.0-rc.4 (2990)` server.

**Comment by ali-alhaidary** [comment]
I do not know how this happened, on our file we have 
defaultWelcomeMessageHeader twice ...

Ali

**Comment by ali-alhaidary** [comment]
![Screenshot 6](https://user-images.githubusercontent.com/75235623/169668647-1ae01afb-9aed-4a4a-acdb-b9a6e3a6e45e.png)
we do not have 2990

**Comment by ali-alhaidary** [comment]
Thanks @ffdixon
