### ISSUE TITLE
20000 Worker Connections are not enough

### ISSUE THREAD

**Issue by RimonShill** [bigbluebutton/bigbluebutton#15057]
Every several hours I start seeing in the error log "20000worker_connections are not enough", and my site slows down / becomes flakey. A nginx restart solves the problem entirely for the next several hours.

Other than looking at the access log (which looks normal), is there a way to observe with greater details what nginx is doing?

Is there some notorious configuration combination that might result in old connections being held open and not closed?

my site configuration:

server {
        server_name example.com;

  location / {

        proxy_pass http://localhost:3003;
        proxy_read_timeout          1m;
        proxy_connect_timeout       1m;

        proxy_set_header X-Real-IP $remote_addr;

        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        proxy_set_header Host $host;

        proxy_set_header X-NginX-Proxy true;

        proxy_http_version 1.1;

        proxy_set_header Upgrade $http_upgrade;

        proxy_set_header Connection "upgrade";

        proxy_redirect off;

}

   listen 80;
   listen 443 ssl;
    access_log /var/log/nginx/example.com;
    error_log /var/log/nginx/example.com;
    include snippets/self-signed.conf;

if ($scheme != "https") {

return 301 https://example.com$request_uri;

}

}

![image](https://user-images.githubusercontent.com/99593576/169659982-8cb808f9-2cff-4b8d-a322-a45715d06c12.png)

**Comment by ffdixon** [comment]
> Every several hours I start seeing in the error log "20000worker_connections are not enough", and my site slows down / becomes flakey. A nginx restart solves the problem entirely for the next several hours.

Can you tell us more about your site: server configuration, version of BigBlueButton, how long is it running, how heavily is it used?

**Comment by ffdixon** [comment]
You closed this, but was it because you solved the issue?  If so, what was the solution?
