### ISSUE TITLE
Tooltip appears in 2 places sometimes on hovering talking indicator

### ISSUE THREAD

**Issue by tomonsoejang** [bigbluebutton/bigbluebutton#15060]
**Describe the bug**
when we hover over the talking indicator, sometimes we see 2 tooltips.

**To Reproduce**
1. Unmute viewers
2. let the viewers speak
3. a talking indicator of viewers will appear on the moderator screen
5. hover over the talking indicator of the viewers,
6. Sometimes, it will show 2 talking indicators

**Expected behavior**
Only 1 talking tooltip should appear always

**Actual behavior**
Sometimes 2 talking indicator appears

**Screenshots**
![image](https://user-images.githubusercontent.com/91654571/169747738-3c0915d7-5392-4e4d-9865-520b0863e8e4.png)

**BBB version:**
BigBlueButton continually evolves. Providing the version/build helps us to pinpoint when an issue was introduced.
Example:
$ sudo bbb-conf --check | grep BigBlueButton
BigBlueButton Server 2.4.4 (2961)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, Mac]
 - Browser [e.g. Chrome]
 - Version [e.g. 101.0.4951.64 (Official Build) (arm64)]

**Comment by antobinary** [comment]
Thanks for reporting! Let's try to reproduce this on a newer BBB - 2.5 ideally and patch there if necessary

**Comment by ali-alhaidary** [comment]
Reproducible on v2.5.0.-rc4
