### ISSUE TITLE
privateChatNotification test can produce duplicate toasts

### ISSUE THREAD

**Issue by BrentBaccala** [bigbluebutton/bigbluebutton#15079]
Big Blue Button version 2.4.7

The `privateChatNotification` test in the playwright test suite will periodically (approximately 1 in every 200 test runs) produce a duplicate toast, as shown in the graphic below.

Only a single message was sent by the test harness, as is shown by the number "1" in the red indicator.

The weird characters after "USERS", "Moderator", and "Attendee" seem to be an artifact of how nbsp is displayed in the snapshot; I don't think they appeared in the actual test session.

I have the playwright trace of this test (5.4 MB), but I don't think it tells us anything more useful than the graphic.

![Screenshot from 2022-05-24 21-16-32](https://user-images.githubusercontent.com/5731463/170158541-4c6a699a-b78c-4ce8-87cb-2e0a1baf500f.png)

**Comment by ffdixon** [comment]
Good catch Brent.

**Comment by antobinary** [comment]
Likely the same as #15088 
Let's look into this on 2.5 at the same time as 15088 if different.

Thanks for the report!

**Comment by ali-alhaidary** [comment]
if private chat is disabled server side, public chat notification does not function as well.
