### ISSUE TITLE
Shared notes cursor wrong position for RTL languages

### ISSUE THREAD

**Issue by mokazemi** [bigbluebutton/bigbluebutton#15073]
**Describe the bug**
In right-to-left languages, when someone is writing on shared notes, other users see the cursor and name in wrong position. It also has weird behavior. 
Something like this:
![notes_bug](https://user-images.githubusercontent.com/18334056/169989980-daa991ae-8522-443c-b8c8-87fc3a07a0c6.gif)

**BBB version:**
BigBlueButton Server 2.4.7 (3068)

**Comment by ffdixon** [comment]
Can you test this on the upcoming 2.5 and let us know if you see the same issue (https://test25.bigbluebutton.org/).

**Comment by mokazemi** [comment]
> Can you test this on the upcoming 2.5 and let us know if you see the same issue (https://test25.bigbluebutton.org/).

**Yes, it was still there.** 
And there was also **another strange issue** which I hadn't noticed! Even if the layout language is set to English, the shared notes are right-to-left! I don't know why, but I think it doesn't obey BBB language and get it from somewhere else.

**Comment by JoVictorNunes** [comment]
https://github.com/ether/ep_cursortrace/issues/47

**Comment by JoVictorNunes** [comment]
https://github.com/ether/etherpad-lite/issues/5559

**Comment by mokazemi** [comment]
Thank you for reporting these issues upstream @JoVictorNunes

**Comment by antobinary** [comment]
We'll upgrade our etherpad-lite when these changes are made. Closing now.
