### ISSUE TITLE
Recording packaging not install gems

### ISSUE THREAD

**Issue by GhaziTriki** [bigbluebutton/bigbluebutton#15085]
Currently when running `bbb-record --rebuild` we get the following error on a clear 2.5-rc4 server

```
Marking for rebuild aa17ee02fcca8b0e8cff43d0fa947d9c65c7c6c5-1653511108834
Traceback (most recent call last):
        7: from /usr/local/bigbluebutton/core/scripts/rap-enqueue.rb:21:in `<main>'
        6: from /usr/local/bigbluebutton/core/scripts/rap-enqueue.rb:21:in `require_relative'
        5: from /usr/local/bigbluebutton/core/lib/recordandplayback.rb:24:in `<top (required)>'
        4: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
        3: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
        2: from /usr/local/bigbluebutton/core/lib/recordandplayback/events_archiver.rb:21:in `<top (required)>'
        1: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
/usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require': cannot load such file -- redis (LoadError)
```

When `redis` gem is installed manually it keeps asking for additional gems.

The server was installed with `root` user.

**Comment by GuiLeme** [comment]
Hey, @GhaziTriki , so as we discussed, you mentioned something about installing the recording packages already in the `bbb_install` and also looping in maybe @kepstin and @antobinary to bring some Ideas to the discussion. 

The thing is that we needed to run 
```bash 
sudo apt install ruby-dev
sudo apt install libsystemd-dev
cd /usr/local/bigbluebutton/core
sudo bundle install
sudo bbb-conf --restart
```

to end this error. So what do you guys think? Should this be already tackled when installing bbb? Or is ther some other concern to that?

**Comment by kepstin** [comment]
The recording gems are already installed - it's just that they are not installed system wide.

The fix is that the `rap-enqueue.rb` script has to be modified to add or move the lines: 

```
require 'rubygems'
require 'bundler/setup'
```

before any other require statements in the file.

**Comment by kepstin** [comment]
Looks like a solution that will work both in development environment and when installed is this code added to rap-enqueue.rb:

```ruby
require 'rubygems'

ENV['BUNDLE_GEMFILE'] = File.join(__dir__, '../Gemfile')
require 'bundler/setup'
```

I'll make a PR.

**Comment by ihtesham786** [comment]
> Looks like a solution that will work both in development environment and when installed is this code added to rap-enqueue.rb:
> 
> ```ruby
> require 'rubygems'
> 
> ENV['BUNDLE_GEMFILE'] = File.join(__dir__, '../Gemfile')
> require 'bundler/setup'
> ```
> 
> I'll make a PR.

**Comment by ihtesham786** [comment]
I have cloned these changes and ran the script. I am still getting this error : 

```
/usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require': cannot load such file -- redis (LoadError)
Traceback (most recent call last):
        8: from ./post_publish/scalelite_post_publish.rb:23:in `<main>'
        7: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
        6: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
        5: from /usr/local/bigbluebutton/core/lib/recordandplayback.rb:24:in `<top (required)>'
        4: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
        3: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
        2: from /usr/local/bigbluebutton/core/lib/recordandplayback/events_archiver.rb:21:in `<top (required)>'
        1: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
/usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require': cannot load such file -- redis (LoadError)

```

**Comment by hamedunik** [comment]
i have the same issue with bbb 2.5.4 when using scalelite_batch_import.sh

https://github.com/blindsidenetworks/scalelite/issues/806
