### ISSUE TITLE
[2.5] - First chat notification duplicated

### ISSUE THREAD

**Issue by antonbsa** [bigbluebutton/bigbluebutton#15088]
**Describe the bug**
After enabling chat notification, the first notification received by the user is being duplicated.

**To Reproduce**
1. Join with 2 users;
2. As user A, go to `Settings > Notifications > Chat message` and enable `Popup Alerts`;
3. As user A, clear all notifications and hide public chat;
4. As user B, send a public message;

**Automated tests related**
- `Notifications - Chat - Public chat notification`;
- `Notifications - Chat - Private chat notification`;

**Video**

https://user-images.githubusercontent.com/56703993/170557422-15340e6b-1c99-4be1-84cd-fd74f19429c8.mp4

**Comment by antobinary** [comment]
Possibly the same as https://github.com/bigbluebutton/bigbluebutton/issues/15079 ?
