### ISSUE TITLE
Size / Icon / Color - Mouse Pointer

### ISSUE THREAD

**Issue by demlak** [bigbluebutton/bigbluebutton#15097]
We would like to change the Settings for Mousepointer.. for example: Size / Icon / Color

Where to dig in?

Thx a lot

**Comment by antobinary** [comment]
Hey @demlak 

You can find the client components code here: https://github.com/bigbluebutton/bigbluebutton/tree/develop/bigbluebutton-html5/imports/ui/components

when you clone the project you can just search for `cursor:` that directory and you'll see different results -- for example the what the cursor will look like when hovering over specific buttons or the whiteboard, etc...

![Screenshot from 2022-06-09 12-44-36](https://user-images.githubusercontent.com/6312397/172900382-fb8cf943-e7f9-4907-b10d-591382d87d64.png)

We encourage you to use the bigbluebutton-dev group to discuss development questions, etc. We use the issues here to track features, bugs, etc.

Hope this helps!
