### ISSUE TITLE
[2.5] Wrong aggregation of broadcast messages to breakout room

### ISSUE THREAD

**Issue by schrd** [bigbluebutton/bigbluebutton#15112]
**Describe the bug**
If 2 moderators send a broadcast message to breakout rooms at the same time, both will show up aggregated in the breakout room. In the breakout room it looks like only one moderator had sent 2 messages.

**To Reproduce**
1. join 2 users as moderator
2. start breakout rooms
3. Both moderators prepare a broadcast message and send it at the same time
4. see the error in the breakout rooms

**Expected behavior**
Users should be able to identify who wrote which message

**BBB version:**
2.5 rc4+ commit 4e5a0467dbdc22ec14c16f51d1a4c1a7d723574a

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Firefox
 - Version 91 ESR

**Comment by antobinary** [comment]
Thanks for reporting!
