### ISSUE TITLE
Better naming of "Share an External Video" to "Share an External Media"

### ISSUE THREAD

**Issue by GhaziTriki** [bigbluebutton/bigbluebutton#15126]
**Is your feature request related to a problem? Please describe.**
Most of the customers are looking to play audio files in the audio conference instead of videos. It is currently implemented but the way the button is named does not make it clear.

**Describe the solution you'd like**
Rename the button from `Share an External Video` to `Share an External Media (Video or Audio)` as example.

**Additional context**
![image](https://user-images.githubusercontent.com/4991088/171814374-60376085-b68b-48e6-8e7e-e6933aced62b.png)

Any thoughts @ffdixon & @tylercopeland ?

**Comment by tylercopeland** [comment]
@GhaziTriki Thanks for sharing feedback from your customer and their needs for this particular experience. I'm not against having the label be more generic. We could even say **"Share media"**, and within the modal, we can provide context as to what they can share at the moment. 

I'm curious, where are your clients hosting the audio files?
