### ISSUE TITLE
Cann't not building BBB-WEB API

### ISSUE THREAD

**Issue by NeihTzxc** [bigbluebutton/bigbluebutton#15120]
**Describe the bug**
When I customize the API and build the code, but the process can't be finished. I'm customize file bigbluebutton-web/grails-app/controllers/org/bigbluebutton/web/controllers/ApiController.groovy

**To Reproduce**
1. Go to cd ~/ubuntu/bigbluebutton/bbb-common-message
2. Run ./deploy.sh
3.  chmod -R ugo+rwx /var/bigbluebutton
4. chmod -R ugo+rwx /var/log/bigbluebutton
5. mkdir -p ~/.sbt/1.0
6. ~/.sbt/1.0/global.sbt Add the following into it [resolvers += "Artima Maven Repository" at "https://repo.artima.com/releases"
updateOptions := updateOptions.value.withCachedResolution(true)]
7. cd ~/ubuntu/bigbluebutton/bbb-common-web
8. service bbb-web stop
9. ./build.sh
10. grails -reloading -Dserver.port=8090 run-app

**Expected behavior**
The build process finished and no errors occurred

**Actual behavior**
The process stops at 87% and cannot be terminated..

**Screenshots**

<img width="865" alt="Capture" src="https://user-images.githubusercontent.com/45267625/171547267-9fef7354-8b92-410a-a50b-479946fd4074.PNG">

**Comment by zhem0004** [comment]
Based on the description it seems like a normal execution for when you run bbb-web 2.5 manually. The reason it does not terminate is because it runs as a service, but you can stop it with Ctrl + C. As for 87%, it is a log from Spring bootRun method 
(percentage log wasn't present in 2.4 because of older version of log4j ). And it appears as not completed because the program is still running at an execution phase, and other 13 are the cleanup tasks.

**Comment by zhem0004** [comment]
Although looking at the logs picture, there normally is a line
"Grails application running at http://localhost:8090 in environment: production",
which you don't seem to have. Could you please check whether you can run meetings? Errors may appear when you try that.

**Comment by NeihTzxc** [comment]
> 

When I run it, greenlight can't call the api to create the meeting

**Comment by zhem0004** [comment]
I have tried to reproduce it with Greenlight and the custom configurations. The changes made in step 6 indeed cause an issue. It causes the secret to not always be recognized. The meeting is created, but cannot be joined.
