### ISSUE TITLE
bbb-web turn/stun server configuration overwritten while upgrading to 2.5.0

### ISSUE THREAD

**Issue by AlphaDE** [bigbluebutton/bigbluebutton#15159]
**Describe the bug**
While upgrading to 2.5.0 

`/usr/share/bbb-web/WEB-INF/classes/spring/turn-stun-servers.xml `

was overwritten with the default despite the file was modified to match the own servers.

**Installation type**
bbb-install

**Firewall and IP address type**
NAT/Firewall, own IP

**Console output**
[See issue 15158](https://github.com/bigbluebutton/bigbluebutton/issues/15158)

**Comment by ali-alhaidary** [comment]
I think you should have used the -c option in bbb-install, this will 
create the proper file.

Ali

**Comment by AlphaDE** [comment]
Thanks @easy-bios and @ali-alhaidary 

I did not notice these changes and copied the turn/stun file on the second installation to /etc accordingly.

@ali-alhaidary I did not find an explanation for the -c parameter in the installscript?

**Comment by ali-alhaidary** [comment]
see https://github.com/bigbluebutton/bbb-install

Ali

**Comment by ali-alhaidary** [comment]
https://github.com/bigbluebutton/bbb-install#command-options

**Comment by AlphaDE** [comment]
@ali-alhaidary 

Thank you, I just searched the normal official install doc.
