### ISSUE TITLE
Retire bbb-demo (dev environment package)

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#15151]
Let's use GreenLight instead of `bbb-demo`. API MATE https://mconf.github.io/api-mate/ is also great

Pros:
+encourage use of GL so we detect bugs early / promote integration
+retire bbb-demo which is a bag of super old JSP code
+reduced risk of having it installed by accident on a production server
Cons:
-users will have to create an account to log in to test25 bbb org for example

Implications
- [x] would need to tweak bbb-install to drop the bbb-demo option
- [x] would need to drop the bbb-demo packaging from build/*
- [ ] would need to update docs anywhere it mentions "demo"
- [x] would need to tweak the steps for setting up a test/dev server
- [ ] docker-dev would need some tweak to have with GL included
- [ ] ...

**Comment by Jossef-767** [comment]
Some users prefer not to use GL for their own reasons.
This will hurt a lot of users who have based their system usage on JSP code and bbb-demo option.
The fact that the JSP code is old does not mean that it is problematic.
No significant advantage. And many disadvantages.
