### ISSUE TITLE
Create empty `/etc/bigbluebutton/nginx/`

### ISSUE THREAD

**Issue by debuglevel** [bigbluebutton/bigbluebutton#15193]
**Is your feature request related to a problem? Please describe.**
`/etc/bigbluebutton/nginx/` does not exist (at least after running `bbb-install-2.5.sh`) while documentation suggest to place overrides in there.

**Describe the solution you'd like**
`/etc/bigbluebutton/nginx/` should exist.

**Describe alternatives you've considered**
Of yourse it's easy to `mkdir -p /etc/bigbluebutton/nginx/`. But actually I already don't know which permissions I should set.

**Comment by Davka** [comment]
what do you need the directory for? 
You will not be able to overwrite the existing NGINX configurations (sip.nginx for example) without touching the original configurations.

**Comment by debuglevel** [comment]
> documentation suggest to place overrides in there.
See also: https://docs.bigbluebutton.org/admin/configuration-files.html#logs-sent-directly-from-the-client

`bigbluebutton.nginx` also describes this:
https://github.com/bigbluebutton/bigbluebutton/blob/fd6104fe0907edb264aad3e34bc6f06cf7775d62/build/packages-template/bbb-html5/bigbluebutton.nginx#L17

It's just not created.

(I personally use it to place reverse proxy configs for Prometheus exporters in there - but it's not relevant what I need that directory for as long documentation state its existence and even describes its usage.)
