### ISSUE TITLE
Does it work on nginx proxy pass?

### ISSUE THREAD

**Issue by solutionall** [bigbluebutton/bigbluebutton#15191]
I have a subdomain, and port forwared from router to my ip to server (ubuntu 18 with nginx) then I configured my 'default' conf as

```
server {
    listen 443 ssl http2;
    server_name bbb.MYDOMAIN.net;
    client_max_body_size 2048M;
    add_header X-Frame-Options "SAMEORIGIN";
    add_header X-XSS-Protection "1; mode=block";
    add_header X-Content-Type-Options "nosniff";
    charset utf-8;
    location / {
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-NginX-Proxy true;
      proxy_pass http://192.168.1.100/;
      proxy_ssl_session_reuse off;
      proxy_set_header Host $http_host;
      proxy_cache_bypass $http_upgrade;
      proxy_redirect off;
    }
}

```

192.168.1.100 - is BBB to install server (ubuntu 20 server).  And script would be

`wget -qO- https://ubuntu.bigbluebutton.org/bbb-install-2.5.sh | bash -s -- -v focal-250 -s 192.168.1.100 -e me@mydomain.net -a -w` ?
or 
`wget -qO- https://ubuntu.bigbluebutton.org/bbb-install-2.5.sh | bash -s -- -v focal-250 -s bbb.mydomain.net -e me@MYDOMAIN.net  -a -w` ?
Does it work like this? or should I install it on root web server (as I mentioned ubuntu 18 with nginx)? 
My bbb.MYDOMAIN.net is ssl certificate signed with Let's encrtypt successfully.

**Comment by defnull** [comment]
Your approach works only for HTTPS traffic, but your BBB server must also be reachable on a lot of other ports for WebRTC traffic. You either need a public IP for your BBB server, or run a TURN server on a public IP. Servers behind NAT are possible, but require extra steps: https://docs.bigbluebutton.org/admin/configure-firewall.html

**Comment by solutionall** [comment]
Installation must be ```wget -qO- https://ubuntu.bigbluebutton.org/bbb-install-2.5.sh | bash -s -- -v focal-250 -s 192.168.1.100 -e me@mydomain.net -a -w
``` ?
or
`wget -qO- https://ubuntu.bigbluebutton.org/bbb-install-2.5.sh | bash -s -- -v focal-250 -s bbb.mydomain.net -e me@MYDOMAIN.net -a -w?`?



> Your approach works only for HTTPS traffic, but your BBB server must also be reachable on a lot of other ports for WebRTC traffic. You either need a public IP for your BBB server, or run a TURN server on a public IP. Servers behind NAT are possible, but require extra steps: https://docs.bigbluebutton.org/admin/configure-firewall.html

Make a stun server is after installation right?

**Comment by defnull** [comment]
Installing BBB is the least of your concerns, you can change the `-s` setting afterwards. First, make sure you meet requirements: You need a public IP for your BBB server, or a separate TURN server that would also need a public IP. TURN, not STUN. There is no use in installing everything if you do not meet minimal requirements.

Also, this is an issue tracker, not a support forum. Perhaps better ask the appropriate mailing list. This issue might be closed by a maintainer soon.
