### ISSUE TITLE
Repeated securitySalt=... in /etc/bigbluebutton/bbb-web.properties

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#15207]
**Describe the bug**
Inaccurate re-appending of securitySalt done by BBB

**To Reproduce**
I am not sure how to reproduce this but I have seen it multipe times, different servers (demo, test, local dev env, etc)

**Expected behavior**
Only one instance of `securitySalt=somestring` should be present in  /etc/bigbluebutton/bbb-web.properties
It gets set by bbb-conf (setip?)

**Actual behavior**
The line for `securitySalt=` is repeated anywhere between 2 to ~30 times. There is no negative symptom other than ... messy file and messy response for `bbb-conf --check` listing all the lines.

**Screenshots**
```
$ cat /etc/bigbluebutton/bbb-web.properties 
bigbluebutton.web.serverURL=https://anton26.test
securitySalt=somestring
securitySalt=somestring
securitySalt=somestring
securitySalt=somestring
```

BBB 2.5.0 has had it, I am seeing this on a 2.6 dev environment right now

**Comment by gustavotrott** [comment]
It should be solved in the last docker images... could you confirm you are using the latest image of the docker-dev? and then see if it still happens
