### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by alfredonodo** [bigbluebutton/bigbluebutton#15205]
Hi,
since BBB 2.5 uses mediasoup. What is the current maximum number of users per room? Is the limit still [150](https://docs.bigbluebutton.org/support/faq.html#how-many-simultaneous-users-can-bigbluebutton-support)?
Thank you

**Comment by ffdixon** [comment]
> since BBB 2.5 uses mediasoup. What is the current maximum number of users per room? Is the limit still 150?

Sigh.  I just finished responding to this in the scalelite issue tracker.  Please don't open the same issue in multiple projects, it just makes more work for us to respond in multiple places.

It's not a hard-coded limit; rather, more of guidelines. We know users have put more than 150 users in a single room, but we are conservative and want to ensure you have a good experience.

**Comment by antobinary** [comment]
Original question: https://github.com/blindsidenetworks/scalelite/issues/794#issuecomment-1159038847
