### ISSUE TITLE
Mirror webcam by default

### ISSUE THREAD

**Issue by debuglevel** [bigbluebutton/bigbluebutton#15200]
**Describe the bug**
About every conferencing software is mirroring the own webcam. Therefore users would expect the same of BBB. Would be nice to set this as a default.

**Comment by steffen-moser** [comment]
You can already configure this behavior by setting
```
public:
  app:
    mirrorOwnWebcam: true
```
in /etc/bigbluebutton/bbb-html5.yml.

**Comment by debuglevel** [comment]
That's why I wrote "by default".

**Comment by danimo** [comment]
I could not agree more. Can we have this an change for 2.6, @ffdixon @antobinary? I am not aware of any counter arguments.

**Comment by debuglevel** [comment]
Still an issue
