### ISSUE TITLE
No join setting to disable screen share

### ISSUE THREAD

**Issue by BrentBaccala** [bigbluebutton/bigbluebutton#15220]
On 2.5.1, the "Disable screensharing" test fails because we dropped support for the user parameter `bbb_enable_screen_sharing` in commit de4688bcdc7 (Feb 7 2022) when `disabledFeatures` was introduced as a meeting parameter.

So, right now, it looks like we can disable screen sharing for an entire meeting, but have no join option to disable it on a per-user basis.

Do we want to reintroduce support for `bbb_enable_screen_sharing`?

**Comment by antobinary** [comment]
>Do we want to reintroduce support for bbb_enable_screen_sharing?

The meeting-wide disableFeatures approach is sufficient for screenshare based on what I can see. Thank you for tracking this. We had decided this earlier but I had missed this issue.
