### ISSUE TITLE
BBB 2.5.1 is not running "post_event" script `post_events_analytics_callback.rb` at all

### ISSUE THREAD

**Issue by pielonet** [bigbluebutton/bigbluebutton#15224]
Hi,
I setup Scalelite with the new feature OVERRIDE_CREATE_PARAMS and set `meta_analytics-callback-url` parameter to point to the URL of our statistics server.

BBB server's "bbb-web.log" show that the URL is well transmitted to the BBB server on meeting creation call.
Nevertheless, the URL is NOT called by the BBB server after meetings end : the Nginx server that runs in front of our statistics application does not log any call. It looks like "post_event" script `post_events_analytics_callback.rb` is not run.

Any idea on how we can debug this ?

Kind regards,
Thierry

**Comment by ritzalam** [comment]
Did you enable keepEvents in bbb-web? The script will only run when an events.xml is stored in the dir.

Can you make sure in ```/etc/bigbluebutton/bbb-web.properties``` the ```meetingKeepEvents=true``` is present?

**Comment by pielonet** [comment]
Hi,

I found the parameter `defaultKeepEvents` with value `false` in `/usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties`.

Is it this parameter rather than `meetingKeepEvents` (inexistant) that I should override ?

**Comment by pielonet** [comment]
I confirm it works with setting `defaultKeepEvents=true` in `/etc/bigbluebutton/bbb-web.properties`.
Thank you @ritzalam for your support.
