### ISSUE TITLE
MongoDB 3.6+ is nonfree, please continue supporting 3.4 and look for alternative databases.

### ISSUE THREAD

**Issue by ian-kelling** [bigbluebutton/bigbluebutton#15237]
**Is your feature request related to a problem? Please describe.**

MongoDB 3.6+ uses a nonfree license:
https://en.wikipedia.org/wiki/Server_Side_Public_License. 

Many users require or strongly prefer to run entirely free software BBB.
Users deserve software freedom for all the programs they run.

**Describe the solution you'd like**

The simplest alternative might be https://www.ferretdb.io/, but it might require waiting until more features are implemented.

MongoDB 3.4 is not supported by MongoDB Inc. anymore, but we can still run it for at least 3 more years on trisquel 10 or ubuntu 20.04 to have a supported base OS. Please continue to support MongoDB 3.4 for BBB and work toward moving BBB to a supported free software database.

**Comment by ffdixon** [comment]
Thanks Ian for the feedback.  We're currently using MongoDB 4.4.15, but we are not providing MongoDB as a service, which is what triggered MongoDB to go to this license.

All the code in BigBlueButton, which embeds MongoDB, is open source.

Nonetheless, like yourself, we would prefer to move away from MongoDB to an alternative with an OSI recognized license.

**Comment by AlekSi** [comment]
FerretDB co-founder and CTO here. We are actively working on making FerretDB compatible with BBB.

**Comment by mxmehl** [comment]
Hi @AlekSi, may I ask whether you succeeded?

**Comment by AlekSi** [comment]
@mxmehl We are still working on it. The most significant missing piece identified is the OpLog tailing support required by BBB and other Meteor applications. That should be available shortly.

**Comment by antobinary** [comment]
Heads up that in BigBlueButton 3.0+ we significantly reduce the use of MongoDB with the goal of entirely dropping Meteor (i.e. the only MongoDB component) later in 2024. We use Hasura, Postgres, GraphQL. Stay tuned for updates on 3.0.
