### ISSUE TITLE
Anonymous polls don't display live results

### ISSUE THREAD

**Issue by BrentBaccala** [bigbluebutton/bigbluebutton#15235]
On a 2.5.2 server, start a new meeting with two participants and start an anonymous A/B/C/D poll.  Instead of live results, the poller see this:

![image](https://user-images.githubusercontent.com/5731463/175196552-c8114800-a97d-41f0-b598-d95140c5248f.png)

If you close and re-open the polling tab, then it starts working right, for both the current poll and future polls.

**Comment by ramonlsouza** [comment]
should be fixed by #15229
