### ISSUE TITLE
Direct access to the white board

### ISSUE THREAD

**Issue by vincentdinumpnp** [bigbluebutton/bigbluebutton#15231]
<!--PLEASE DO NOT FILE ISSUES FOR GENERAL SUPPORT QUESTIONS.
This issue tracker is only for bbb development related issues.
Search for existing feature requests to avoid creating duplicates.--

**Is your feature request related to a problem? Please describe.**

Users do not understand how to reach the whiteboard from the homepage.

**Describe the solution you'd like**
It would be great if we can reach the empty whiteboard by clicking from the "whiteboard icon" on the homepage, instead of clicking 2 or 3 times (in order to reach the diapo 2 or 3)
(See option 1 on the screenshot)

**Describe alternatives you've considered**
Or we could consider to add a button "whiteboard" on the right menu.
This button would lead to the "empty" whiteboard.
(See option 2 on the screenshot)

**Additional context**
![image](https://user-images.githubusercontent.com/99720314/174998891-78dd9314-89f0-410c-8c50-d83c785c20b2.png)

**Comment by ffdixon** [comment]
Invalid issue (no information given).
