### ISSUE TITLE
Focus on text-field is lost if a viewer raises his hand

### ISSUE THREAD

**Issue by muellerlukas** [bigbluebutton/bigbluebutton#15238]
**Describe the bug**
Focus to text field and content on whiteboard is lost when a viewer is raising his hand

**To Reproduce**
1) Start a session with a moderator and a viewer
2) Create as modertator a text field on the whiteboard
3) Start typing, but do not save
4) Raise as viewer the hand
4) Moderator losts focus to the text field, the text field disappears and the content is lost

**Expected behavior**
Even if a viewer raises his hand the moderator should be able to type text into the text-field

**Actual behavior**
Focus on the text field is lost, field disappears and the already typed content is lost

**BBB version:** 
2.4.9, bug does NOT appear in 2.5.1

**Desktop**
- Windows: Chrome 102 and Firefox 101

**Comment by mariogasparoni** [comment]
Also happens if you zoom while using the text tool

**Comment by musyne** [comment]
Same here with 2.4.9. I didn't have this issue with 2.4.7. I don't know if 2.4.8 is also affected.
Even when nobody is raising hands: If I start typing and then stops, the text field sometimes disappears after a few seconds. Video of what's happening here: https://lindobox-my.sharepoint.com/:v:/p/alexis/EQEIaFjem-lDnDhkPYAaOxgBT0rlpU5gqsJvBDXT3KKdTw?e=9f1B93

**Comment by musyne** [comment]
Is this going to be fixed on the 2.4 branch or is the only option to switch to 2.5?

**Comment by ffdixon** [comment]
We're not releasing any updates to 2.4 except security-related.  Is it an option for you to update to 2.5?

**Comment by musyne** [comment]
Yeah I guess I can do that. I'll build a new server and decommission the old one.
I'm a bit surprised that such a show-breaker bug (text field can't be used anymore) was introduced late in the 2.4 branch (it started with 2.4.8) and is not going to be fixed.
However I understand your focus on the future. I'll make sure to update to 2.5 asap.
Thanks.

**Comment by ramonlsouza** [comment]
fixed by #15308
