### ISSUE TITLE
Prevent recording error when using old and new CC simultaneously: process audio captions recorded events

### ISSUE THREAD

**Issue by Arthurk12** [bigbluebutton/bigbluebutton#15249]
**Is your feature request related to a problem? Please describe.**
The new closed captions feature makes use of the same piece of code for processing the recorded events as the written(etherpad) closed captions.
It's events have been adapted to fit the written closed caption's events processing code, which can lead to issues as the feature evolves.

**Describe the solution you'd like**
Implement a separate processing line suitable for the new closed captions recording events.
Suggestions:
- Use the same output format BigBlueButton already implements to avoid playback incompatibilities.
- The transcirptId can also be used to improve processing.

**Comment by antobinary** [comment]
@Arthurk12 Should we tag this to BigBlueButton 2.6?
