### ISSUE TITLE
[2.6] Move notes to whiteboard needs an extra step to show presentation

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#15259]
**Describe the bug**

**To Reproduce**
1. Join a 2.6 server
2. Write some shared notes
3. Click on 'Move notes to whiteboard'
![Screenshot from 2022-06-24 16-24-46](https://user-images.githubusercontent.com/6312397/175662853-f21477e5-1553-492d-a526-6e3ba2ef33d1.png)

4. You will see a notification that the  current presentation  was changed
![Screenshot from 2022-06-24 16-25-18](https://user-images.githubusercontent.com/6312397/175662871-62429939-1197-4412-9727-06aa1f0c2317.png)

5. You will see in the `+` button menu that the current presentation has changed
![Screenshot from 2022-06-24 16-25-36](https://user-images.githubusercontent.com/6312397/175662884-1357c3c1-a4d1-4bf4-87da-0d0174c29d89.png)

6. In the presentation modal you will see that the current presentation has changed...
![Screenshot from 2022-06-24 16-25-45](https://user-images.githubusercontent.com/6312397/175662907-9b8e6d33-eed9-4097-a225-ff2663706412.png)

**Expected behavior**
You are seeing Shared Notes.pdf

**Actual behavior**
You are still seeing default.pdf. A client refresh does the job to show the Shared Notes current presentation
you can see the slide on ![Screenshot from 2022-06-24 16-25-36](https://user-images.githubusercontent.com/6312397/175662884-1357c3c1-a4d1-4bf4-87da-0d0174c29d89.png)

**BBB version:**
BigBlueButton 2.6.0-alpha.1 (pre-release)

**Comment by gustavotrott** [comment]
This problem doesn't happen only on "Move to SharedNoted to Whiteboard".
I can reproduce it even when sending some PDF as presentations, when the upload finishes the previous slide is still being showed in the whiteboard.

Although it doesn't happen every time, this bug is very often.

**Comment by gustavotrott** [comment]
The whiteboard is refreshed to the correct slide once you draw something on the slide using the Tldraw tools.
