### ISSUE TITLE
API docs correction getRecordings

### ISSUE THREAD

**Issue by bbbondemand** [bigbluebutton/bigbluebutton#15255]
The AP documentation for https://docs.bigbluebutton.org/dev/api.html#getrecordings

The example response has three missing fields:  

<size> appears twice, once under recordings and again under format. 
<rawSize>
<data/>

If anyone could comment what data type <data/> is I would be grateful - I have not seen this populated but the empty field is returned.

**Comment by antobinary** [comment]
After checking with @paultrudel it looks like the docs section for getRecordings was improved. Not spotting the specific commit to link here though.
