### ISSUE TITLE
[2.6] tldraw change slide controls accessible to non-presenters

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#15276]
**Describe the bug**

**To Reproduce**
1. Join a meeting with a presenter and one more user
2. The non-presenter right-clicks on the whiteboard area

**Expected behavior**
Looks like most of the actions are not really allowed. Probably don't display the menu at all?

**Actual behavior**
A bunch of menus are displayed, see screenshot.

**Screenshots**
![Screenshot from 2022-06-28 15-06-59](https://user-images.githubusercontent.com/6312397/176264561-cd362f45-38b8-4f93-9732-be0bbd4ce965.png)

**BBB version:**
BigBlueButton 2.6.0-alpha.1

**Comment by ali-alhaidary** [comment]
That indicated that you have created that number of pages :-)

**Comment by ali-alhaidary** [comment]
@antobinary note that the default presentation contains 15 slides, so the sub menu will ask you to which slide you want to move the shape...
