### ISSUE TITLE
tldraw does not work in RTL in v2.6.0 alpha 1

### ISSUE THREAD

**Issue by ali-alhaidary** [bigbluebutton/bigbluebutton#15284]
**Describe the bug**
tldraw does not work in RTL

**To Reproduce**
1. Go to a session
2. change language to Arabic (or any other RTL)
3. Draw a line or shape

**Expected behavior**
the line is drawn properly

**Actual behavior**
the line is drawn outside the canvas

**Screenshots**

**Additional context**
tested on https://test26.bigbluebutton.org/
TLdraw is going so much active development right now, fully arabized, but not RTL supported as it does not need as a stand alone app, but a request for new feature was raised.

**Comment by Buda9** [comment]
Actually, it works but not correctly

![Screenshot_99](https://user-images.githubusercontent.com/1422662/176521717-0e2ab552-ec4a-4898-8842-7d453ef0ae43.png)

**Comment by ali-alhaidary** [comment]
> Actually, it works but not correctly
> 
> ![Screenshot_99](https://user-images.githubusercontent.com/1422662/176521717-0e2ab552-ec4a-4898-8842-7d453ef0ae43.png)

@Buda9 that is what I call "not working" :-)

**Comment by Buda9** [comment]
😁

**Comment by ali-alhaidary** [comment]
https://github.com/tldraw/tldraw/issues/767

**Comment by ali-alhaidary** [comment]
Thanks @KDSBrowne for clarification, how about localization?

**Comment by ali-alhaidary** [comment]
> @ali-alhaidary , The new locales added to `Tldraw` should make their way into BBB once the package is upgraded to the appropriate version.

Thank you @KDSBrowne

**Comment by ali-alhaidary** [comment]
It seems that changing the language while in the session causes this issue, however, if Arabic is set in profile and starts the session in Arabic tldraw acts as expected, but, if changed to LTR language, it will start to shift cursor position.
