### ISSUE TITLE
Removed  student from a lesson is still in the user list

### ISSUE THREAD

**Issue by gm2117** [bigbluebutton/bigbluebutton#15297]
**Describe the bug**
When a moderator removes a student from a lesson. The student remains visible for the students in the user list but not the moderator. Participants number does not decrease.

**To Reproduce**
1. Start a lesson and join as moderator  and as a student
2. Click on remove student
3. User has been removed for moderator but not for the students still in the user list and false count of participants4. 

5. See error

**Expected behavior**
User should be removed from both lists (moderator, student).

**Actual behavior**
User should is not removed from student view.

**Screenshots**

**BBB version:**
BigBlueButton continually evolves. Providing the version/build helps us to pinpoint when an issue was introduced.
Example:
$ sudo bbb-conf --check | grep BigBlueButton
BigBlueButton Server 2.5.1 2807
![Image 2022-06-30](https://user-images.githubusercontent.com/2955472/176678194-f69a9131-2773-402d-8c5d-21c90c9a104f.jpeg)

**Desktop (please complete the following information):**
 - OS: Windows, Mac]
 - Browser [  Chrome, Safari firefox Brave]

**Comment by antobinary** [comment]
Hi @gm2117 
Thanks for reporting! You mention an error (step 4). Could you copy-paste / attach screenshot of the error? Or you meant "error" as in incorrect behavior/state?

@ramonlsouza did some work in this area after 2.5.2 was released -- https://github.com/bigbluebutton/bigbluebutton/pull/15181
This fix should be part of BBB 2.5.3 (planned for next week). It would be nice if we could clarify on the "error" to be certain we've covered your use case. Thanks!

**Comment by gm2117** [comment]
There is no error the behaviour is not correct and is confusing for moderators and students
Also the dial in when the come in the microphone from the phone is not muting was working fine in the previous versions.

**Comment by gm2117** [comment]
Great looking forward to that

**Comment by ramonlsouza** [comment]
fixed by https://github.com/bigbluebutton/bigbluebutton/pull/15181
