### ISSUE TITLE
Normalize webcam aspect ratio

### ISSUE THREAD

**Issue by ramonlsouza** [bigbluebutton/bigbluebutton#15294]
**Is your feature request related to a problem? Please describe.**
Black bars appear on top/bottom when 16:9 camera is shared, because the default aspect ratio for webcam video container is 4:3.

![black-bars](https://user-images.githubusercontent.com/3728706/176537367-625fb86f-9d99-4f9e-a69a-2782b98fe721.png)

**Describe the solution you'd like**
Change video object `object-fit` value from `contain` to `cover`. This would make all videos appear as 4:3, even if the source is in another aspect ratio.

![no-black-bars](https://user-images.githubusercontent.com/3728706/176537352-d5b45008-1d20-4fe1-ac7e-651c31b34a5d.png)

**Describe alternatives you've considered**
- ask the user to select which part of the video will be shared if source is in another aspect ratio (manual crop on share)
- have a checkbox/toggle in video preview modal, so each user can choose to auto-crop webcam video with `object-fit:cover` or share in original ratio with black bars on top/bottom
- add `meeting_webcam_ratio` / `meeting_webcam_zoom_to_fill` parameters for meeting-wide camera ratio/fill settings

**Comment by prlanzarin** [comment]
>  Change video object object-fit value from contain to cover. This would make all videos appear as 4:3, even if the source is in another aspect ratio.

The suggested approach has been discussed before and, at the time (circa 2019 + 2021), the sentiment was against that to guarantee consistency between what is displayed in the meeting and what is actually recorded. Setting it to `cover` breaks that - recorded streams will have the uncropped source stream. To circumvent that, we either 1) forget about that principle or 2) cropping parameters would have to be propagated + stored and later applied in recording processing - which is added complexity that seems kind of an overkill.
