### ISSUE TITLE
Playback not shows presentation on 2.6.0. alpha-1

### ISSUE THREAD

**Issue by sakdeniz** [bigbluebutton/bigbluebutton#15317]
Playback not shows presentation on 2.6.0. alpha-1. Tried with all browsers and playback content looks emptty.

**Comment by antobinary** [comment]
Addressed in https://github.com/bigbluebutton/bigbluebutton/pull/15244 I believe but still tagging to 2.6 so we make sure to re-test soon. Thanks for reporting!

**Comment by germanocaumo** [comment]
Working on latest 2.6, closing.
