### ISSUE TITLE
Minimizing the presentation causes client freeze

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#15339]
**Describe the bug**
If you try to minimize the presentation (or try screenshare in at least some cases), the entire page freezes and the browser hangs.

**To Reproduce**
1. In a meeting press the minimize presentation (see screenshot)

**Expected behavior**
The presentation is minimized

**Actual behavior**
The client hangs, leading to a browser rescue mechanism

**Screenshots**
![Screenshot from 2022-07-07 11-08-45](https://user-images.githubusercontent.com/6312397/177808053-ee81127a-2095-46cc-95d3-d75fca9fe325.png)

**BBB version:**
BigBlueButton 2.6.0-alpha.2, Chromium 102 browser, Ubuntu 20.04

**Additional context**
I believe @KDSBrowne and @ramonlsouza are on it, I am just creating an issue to help track it.

**Comment by ramonlsouza** [comment]
fixed by https://github.com/bigbluebutton/bigbluebutton/pull/15301
