### ISSUE TITLE
Missing whiteboardId in some redis message

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#15340]
**Describe the bug**
No visual difference but spotted this while looking through 2.6 logs

**To Reproduce**
1. TODO

**Screenshots**
![Screenshot from 2022-07-05 14-31-14](https://user-images.githubusercontent.com/6312397/177808967-6c3ac6c7-f5d7-4e62-855d-e8a9981e9219.png)

**BBB version:**
BigBlueButton 2.6.0-alpha.2

**Additional context**

**Comment by zhem0004** [comment]
I could not reproduce the issue
