### ISSUE TITLE
Buttons are displayed a bit too early

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#15341]
**Describe the bug**
Just a bit of visual regression likely related to recent button refactoring

**To Reproduce**
1. Join a meeting and pay attention to the loading of the client.

**Expected behavior**
Regular dark loading screen

**Actual behavior**
The buttons are displayed too early, in the top left-hand corner of the client. Later they go to their proper positions

**Screenshots**
![Screenshot from 2022-07-07 11-23-48](https://user-images.githubusercontent.com/6312397/177811438-5c3f6a67-7a3a-4bc9-a2e6-8e810e12af4e.png)

**BBB version:**
BigBlueButton 2.6.0-alpha.2

**Additional context**

**Comment by JoVictorNunes** [comment]
hmm I'm struggling to reproduce this. I'm able to reproduce this neither on _dev26_, _test26_ nor _locally_. Could you please check whether this is still happening for you, @antobinary?

**Comment by antobinary** [comment]
Can't reproduce on the latest build. If anything changes I'll reopen, thanks!

**Comment by antobinary** [comment]
I just saw this again on the latest 2.6 build. Of course, I could not record it :)
