### ISSUE TITLE
Custom shape control for whiteboard

### ISSUE THREAD

**Issue by bigbluebutton-issue-import** [bigbluebutton/bigbluebutton#1534]
Originally reported on Google Code with ID 779

```
What is it:

A predefined library of 'stamps' or shapes that can be loaded from vectors, similiar
to how Adobe Connect Pro handles it.

This would be incredibly useful for teaching, especially for maths based lessons, as
mathematical symbols can be hard to draw free hand using mouse or pen.

The stamp list could be added to the branding css, simply declaring the paths to the
image files.

Regards
```

Reported by `SirJamm` on 2010-12-03 15:48:45

**Comment by davidrojo** [comment]
There should be a shape selector like in photoshop.

![image](https://cloud.githubusercontent.com/assets/1050749/10369303/d0c5d11e-6dd9-11e5-829f-91712e7bcf37.png)

There can be some common shapes like circle, square, arrow to fast use, and could be easily configurable adding svg files to a folder in the server, or also could be uploaded a custom shapes files in create meeting api method.
