### ISSUE TITLE
Add custom uploaded background disabledFeatures list

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#15348]
**Is your feature request related to a problem? Please describe.**
In BBB 2.6 we are adding the possibility to upload your own background in addition to the existing ones. We should ensure there's the option to omit this via 'create' parameter.

**Describe the solution you'd like**
Ideally to fit the pattern `disabledFeatures=....` `customizeVirtualBackgrounds` or similar

**Describe alternatives you've considered**

**Additional context**

**Comment by gustavotrott** [comment]
I would call `customVirtualBackgrounds`

![image](https://user-images.githubusercontent.com/5660191/178038272-b6d38930-f041-4cda-9a44-f0ae3c4119e1.png)
Using API Mate to pass `disabledFeatures=customVirtualBackgrounds`, html5 will receive it in `meetingProp.disabledFeatures`.
