### ISSUE TITLE
Add importBreakoutAnnotations with annotations to disabledFeatures list

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#15347]
**Is your feature request related to a problem? Please describe.**
In BBB 2.6 we are adding the possibility to import breakouts' slides with annotations. We should ensure there's the option to omit this via 'create' parameter.

**Describe the solution you'd like**
Ideally to fit the pattern `disabledFeatures=....` `importBreakoutAnnotations` or similar

**Describe alternatives you've considered**
This would be in addition to the option where a moderator is able to dynamically control this within the meeting's duration. I.e. If this is disabled for the meeting - the UI is missing. If it's enabled, the UI is there for the breakout creator to opt in or out of this.

**Additional context**

**Comment by danielpetri1** [comment]
This issue can now be closed as it was implemented in the PR linked above.
