### ISSUE TITLE
Making status setting easier

### ISSUE THREAD

**Issue by mokazemi** [bigbluebutton/bigbluebutton#15354]
It's really hard to set status. Currently it's rally out of place!
There's a button for raising hand. Other status could also be available there.

My idea is something like this:

![status-idea](https://user-images.githubusercontent.com/18334056/178113516-5d5168b7-1cf4-4a46-8d87-798090fbf246.png)

**Comment by ffdixon** [comment]
We built in 2.6!

<img width="247" alt="image" src="https://user-images.githubusercontent.com/290351/230723858-8742504d-226a-4050-8df8-f5e4a653179c.png">

Marking this as completed:-).
