### ISSUE TITLE
Create a self-check page for end-users to help troubleshoot and diagnose potential issues before their session starts

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#15361]
**Is your feature request related to a problem? Please describe.**
Sometimes users experience issues when using BigBlueButton related to connectivity.  There is always a reason for such issues, but it is sometimes difficult to determine the underlying reasons.

Given a correctly installed and provisioned BigBlueButton server, when remote users experience instability in their session (their client disconnects or doesn't respond correctly), it could be due to (1) their setup doesn't meet the minimum requirements, or (2) a network connectivity issue, or (3) an issue with BigBlueButton itself.

It could also be any combination of (1), (2), and (3).

When a session concludes, and the user reports the poor experience, it's difficult to go back in time, look through the logs, and determine which combination of these cases is the root cause.

Pinpointing the underlying issues takes data, and the logs can only go so far.

**Describe the solution you'd like**
Provide a self-test application (separate or integrated) that enables the users to go through a series of steps that systematically test the following in their setup
  - Browser
  - Operating System (such as minimal version of iOS or Android)
  - Client (can we detect if there is insufficient CPU to run BigBlueButton?)
  - Network
    - IPV4/IPV6 connectivity
    - Bandwidth (upload/download)
    - Latency
    - Packet loss
    - Using TURN server?
  - Access to audio (access to microphone)
  - Access to video (access to webcam)

If one of these tests show a potential issue (such as the user is going through a TURN server), then the self-test could help the user take action before entering the BigBlueButton session and potentially experience instability.

The self-test could also generate a detailed report that could be shared with support agents.  This reduces the effort to gather data from the user, which can be difficult in cases where the user is in Grade 2, for example, and any diagnosis of their setup would go through the parents.

The detailed report could also include information gathered from the server side (such as the FreeSWITCH Audio Score).  The report could also include information gathered from the WebRTC stats built into the browser.

**Describe alternatives you've considered**
There are some open source test pages (see https://webrtc.github.io/test-pages/), but they are generic.

Our built-in Status Check is a helps, but having a comprehensive self-check page gives the ability to do a more detailed checks (such as testing that to access the webcam works before the user is in a live session and needs to share their webcam) and, based on the results from the check, give users specific recommendations before they enter the session.

**Additional context**
If we can build a framework for this test, then over time we can add to this framework more tests to help users self-diagnose, give support agents information to troubleshoot, and ultimately give developers detailed information to diagnose and narrow down the underlying causes for issues.

**Comment by einhirn** [comment]
I like the proposal, but may I suggest that a separate Page (depending on user action to trigger diagnostic information collection) seems counter-intuitive. While maybe useful as an option, the diagnostic data should be integrated into the "Connection status", either as "Stats for Nerds" like "You tube" or automatically evaluated as information for the user.
Technical details should be added when using "Copy Stats" button. Also it would be nice to include the stats in the feedback data for those who use it - that way when we get a bad feedback or a negative comment, we could easily inspect causes for it...

**Comment by SamuelWei** [comment]
I really like the idea of having a self test application. This could also be added to frontends via a link to allow users to self-test before the actual meeting
