### ISSUE TITLE
Create "groups" param should not be processed for breakout rooms

### ISSUE THREAD

**Issue by GhaziTriki** [bigbluebutton/bigbluebutton#15363]
https://github.com/bigbluebutton/bigbluebutton/blob/90ef6e9e6a9bfef3abec3e41fa292f1ef290798f/bbb-common-web/src/main/java/org/bigbluebutton/api/ParamsProcessorUtil.java#L606

**Comment by gustavotrott** [comment]
Hey @GhaziTriki, 

not sure if it is necessary once the `group` param is never provided while creating a breakout room.
in this case the `processGroupsParams()` will be called and immediately skipped when it verify the param is absent.
