### ISSUE TITLE
Tldraw: Wrong cursor and toolbar position when Fullscreen

### ISSUE THREAD

**Issue by germanocaumo** [bigbluebutton/bigbluebutton#15377]
**Describe the bug**
The cursor and the whitboard toolbar are in the wrong position when we open presentation to Fullscreen

**To Reproduce**
1. Start a meeting
2. Click the three dots button in the top right corner of presentation
3. Click "Fullscreen"

**Expected behavior**
Cursor position should follow in all screen, and presentation toolbar should be centered in the right.

**Actual behavior**
Can't position the cursor in the right side of the screen, and the presentation toolbar is too low in the right.

**Screenshots**
![Animação](https://user-images.githubusercontent.com/2726293/178800843-63519e42-f330-4545-8c74-076b11754058.gif)

**BBB version:**
https://dev26.bigbluebutton.org/

**Comment by ramonlsouza** [comment]
fullscreen cursor fixed by #15406 (toolbar still in the wrong position)
