### ISSUE TITLE
Moderators should be able to edit/delete anyone's annotations (tldraw)

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#15379]
**Describe the bug**
Currently users are only allowed to edit/delete their own shapes. If a moderator tries to remove someone else's annotation (eraser, etc) it has effect only locally, in that specific browser. Shortly after the shape reappears as the change was never confirmed by akka-apps, etc.
Note: Undo <-> Redo should continue to only have effect on the user's own shapes.

### More
Similar work was done by @gigate in https://github.com/bigbluebutton/bigbluebutton/pull/14837 / https://github.com/bigbluebutton/bigbluebutton/pull/14467

**Comment by antobinary** [comment]
Edge cases:
- multi user whiteboard
- promote/demote
- deleting a text shape as it's still being streamed - i.e. "bad word" gets deleted by a moderator after 'word' was typed but then the user continues typing - do we keep sending the whole string?
- ...

**Comment by germanocaumo** [comment]
Addressed in https://github.com/bigbluebutton/bigbluebutton/pull/15636
