### ISSUE TITLE
Presentation download icon missing in TLDRAW whiteboard

### ISSUE THREAD

**Issue by steffen-moser** [bigbluebutton/bigbluebutton#15382]
**Describe the bug**
Using the TLDRAW whiteboard in BigBlueButton 2.6.0-alpha.1, the icon for downloading slides is not shown.

**To Reproduce**
1. Install BigBlueButton 2.6.0-alpha.1
2. Upload a presentation
3. In the presentation management dialog, allow downloading
4. Try to download the presentation.

**Expected behavior**
Users should be able to download presentations.

**Actual behavior**
No download icon is shown.

**BBB version:**
BigBlueButton Server 2.6.0-alpha.1 (62)

**Desktop (please complete the following information):**
 - OS: OpenSUSE Tumbleweed
 - Browser Chrome (103.0.5060.114) and Firefox (101.0.1)

**Comment by antobinary** [comment]
Thank you for reporting this @steffen-moser !

**Comment by danielpetri1** [comment]
This will be fixed once #15412 is merged
