### ISSUE TITLE
Overwritten config files after upgrade from v2.5 to v2.5.3

### ISSUE THREAD

**Issue by matrixbx** [bigbluebutton/bigbluebutton#15393]
Hi there,

For information that might be useful for others, I have a non working instance after upgrading from (fine) v2.5 to v2.5.3

Overwritten config files after upgrade from v2.5 to v2.5.3
/usr/share/bigbluebutton/nginx/sip.nginx
missing "s" in proxy_pass https and port changed

/usr/share/bbb-web/WEB-INF/classes/spring/turn-stun-servers.xml
Back to default (with use of google server), had to reconfigure it following https://docs.bigbluebutton.org/admin/setup-turn-server.html#configure-bigbluebutton-to-use-your-turn-server

**Installation type**
bbb-install script used at v2.5 fresh install (upgrade to v2.5.3 via apt)

Also had https://github.com/bigbluebutton/bigbluebutton/issues/15387 and followed https://github.com/bigbluebutton/bigbluebutton/issues/15387#issuecomment-1185664522 to fix it (thanks a lot).

**Comment by Dennis1993** [comment]
I've the same problem after upgrading, the instance isn't running anymore.

I've changed the file `/usr/share/bigbluebutton/nginx/sip.nginx` manually by adding the s on proxy_pass and changed the port to 7443.

After that it's needed to change the bbb-conf file like this: https://github.com/bigbluebutton/bigbluebutton/issues/15387#issuecomment-1185664522

Thanks, my instance is now running :)

**Comment by ffdixon** [comment]
> bbb-install script used at v2.5 fresh install (upgrade to v2.5.3 via apt)

You can't update with just apt.  Use `bbb-install.sh` with original parameters to upgrade to latest version.  See

 https://docs.bigbluebutton.org/2.5/install.html#upgrading-bigbluebutton-25

**Comment by matrixbx** [comment]
Thanks for your answer.
But why is there repos in /etc/apt/sources.list.d/bigbluebutton.list and bigbluebutton-ubuntu-support-focal.list if I can't use them for update/upgrade ?
Maybe shoud I just remove those files ?

**Comment by debuglevel** [comment]
> But why is there repos in /etc/apt/sources.list.d/bigbluebutton.list and bigbluebutton-ubuntu-support-focal.list if I can't use them for update/upgrade ? Maybe shoud I just remove those files ?
The repositories are needed by `bbb-install.sh` which actually uses apt to install the `bbb-*` packages. You probably need those therefore. But `bbb-install.sh` also does some additional magic afterwards.

System administration with BigBlueButton installed seems a bit error prone to me: Therefore I disabled unattended upgrades (which I would never recommend on a normal Linux server), update my server manually *and* run `bbb-install.sh` afterwards to ensure BigBlueButton did not just break (or to heal a just broken installation).

**Comment by matrixbx** [comment]
Hi debuglevel,
Will probably do it that way in the future.
In fact did exactly that this morning and there is more fun (as you can see in https://github.com/bigbluebutton/bigbluebutton/issues/15404).

**Comment by hex-m** [comment]
> /usr/share/bbb-web/WEB-INF/classes/spring/turn-stun-servers.xml
> Back to default

This is by design. You have to either use the [overwrite files](https://docs.bigbluebutton.org/admin/configuration-files.html#local-overrides-for-configuration-settings) or put your changes into [apply-conf.sh](https://docs.bigbluebutton.org/admin/customize.html#apply-confsh) such that they are re-applied every time you run `bbb-conf --restart`. Otherwise they will be lost when you run `bbb-install.sh` the next time.

The documentation you [linked to](https://docs.bigbluebutton.org/admin/setup-turn-server.html#configure-bigbluebutton-to-use-your-turn-server) is outdated when it suggests

> Edit the file `/usr/share/bbb-web/WEB-INF/classes/spring/turn-stun-servers.xml`.

A more useful document is [here](https://docs.bigbluebutton.org/admin/customize.html#apply-custom-settings-for-turn-server).

**Comment by matrixbx** [comment]
Hello hex-m,

many thanks for your answer, will do that (include config for turn-stun-servers.xml in apply-conf.sh) and hope it'll work just fine.
