### ISSUE TITLE
Breakout room duration not shown when it's two words (e.g. Farsi)

### ISSUE THREAD

**Issue by mokazemi** [bigbluebutton/bigbluebutton#15397]
Breakout room duration in the panel is **not shown** when the layout language is Farsi (Persian). 
I investigated and my guess is, because it's translation is two words. (Since it was correct in some other languages, but wrong in some others)
Based on the strings:
**English** is "Duration {0}"
**Persian (Farsi)** is "مدت زمان {0}"

![image](https://user-images.githubusercontent.com/18334056/179420586-5dc50e41-7cd4-4a55-9a97-5bcd9750f337.png)

![image](https://user-images.githubusercontent.com/18334056/179420570-471400a5-406c-44ff-a632-407919daa4f1.png)

**Comment by JoVictorNunes** [comment]
Hi @mokazemi! Thanks for reporting. Fixed in https://github.com/bigbluebutton/bigbluebutton/pull/15415.
