### ISSUE TITLE
Unwanted contact by competitors

### ISSUE THREAD

**Issue by KonradHoeffner** [bigbluebutton/bigbluebutton#15398]
I recently filed an issue in this repository and in response I got the following email from a competitor of BBB.  Do you know this company? I do not want companies to email me with advertisements when I create github issues. Is it legal for them to do that? Can you do something against that? 

Jay Kanakiya <jay@100ms.live>
Hey Konrad,

Noticed that you were facing issues in sharing screen in Bigbluebutton, which can be solved easily in 100ms

100ms is a SaaS platform that allows devs to add video and audio conferencing to Web, Android and iOS apps

Wanted to check if 100ms can help, can we schedule a quick call?

Thanks, 
Jay Kanakiya, 
Product Consultant, 100ms

**Comment by prlanzarin** [comment]
> I recently filed an issue in this repository and in response I got the following email from a competitor of BBB. Do you know this company? I do not want companies to email me with advertisements when I create github issues. Is it legal for them to do that? Can you do something against that?

@KonradHoeffner we have no affiliation to those folks and I don't know whether we can do anything about that.
I agree that it sucks, but it's not our doing. It must be automated marketing e-mails based on scraping data. 
Maybe just flag them as spam.

I'll close this since it's not an actual issue.
