### ISSUE TITLE
Whiteboard, chat, cursor events not captured in recording

### ISSUE THREAD

**Issue by MatellioVaibhavsharma** [bigbluebutton/bigbluebutton#15407]
**Describe the bug**
Whiteboard shapes, chat, and cursor events are not captured in the recording. I am able to find audio, and video files in /var/bigbluebutton/recording/raw. But where can I find the recording combined with Whiteboard, chat, and cursor events which are captured by Redis.
**BBB version : 2.4.0**
**To Reproduce**
1. Go to any meeting BBB 2.4.0
2. Click on start recording
3. wait two minutes and end the meeting.

**Expected behavior**
Whiteboard, chat, and cursor events should be captured in recording and generate a recording file /var/bigbluebutton/recording/raw to the respective meeting ID folder

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser Chrome
 - Version 101.0.4951.64

**Additional context**
Found on BBB 2.4.0 version. output for **dpkg -l | grep bbb** can be seen in image.
![Screenshot from 2022-07-19 21-57-20](https://user-images.githubusercontent.com/67277044/179801896-ecacf4b1-1286-4108-a99d-09d2ca217cae.png)

**Comment by kepstin** [comment]
BigBlueButton 2.4 is no longer supported.

I cannot reproduce this issue on 2.4, 2.5, or 2.6. The whiteboard, chat, and cursor are all correctly saved in the events.xml file, and the processed "presentation" format recording shows them.
