### ISSUE TITLE
Unable to login via ldap after upgrade from 2.5.3 to 2.5.4

### ISSUE THREAD

**Issue by matrixbx** [bigbluebutton/bigbluebutton#15404]
Hi there,

Apt is signaling available update for bbb this morning.
As suggested in https://github.com/bigbluebutton/bigbluebutton/issues/15393#issuecomment-1186613809 I hit "N" and do it using bbb-install.sh instead.

As I expected my /usr/share/bbb-web/WEB-INF/classes/spring/turn-stun-servers.xml is gone, but I have made backup ...
But, users can't login anymore using ldap as usual. We got a "please use a valid email address" (translated from french).
Everything looks fine in /opt/greenlight/.env.

This is the second time in a week our instance breaks after an update, this is sort of very annoying.
Can we go back to previous version ? How do we do that ?

Thanks for your responses.

**Comment by sthibaul** [comment]
The login web page uses

```
<input class="form-control" placeholder="Email" value="" type="email" name="session[email]" id="session_email" />
```
to ask for the login, thus making the webbrowser require a valid email adress. This does not make sense for ldap-based accounts. Is there a way to disable the `type="email"` part?

**Comment by matrixbx** [comment]
I just realized that greenlight had been reinstalled in /root/greenlight/ (which is really not an acceptable place to me) and of course .env in there is not configured.
Fortunately the old greenlight installation is still present in /opt/greenlight so I just deleted /root/greenlight and made a symbolic link to /opt/greenlight, killed all container, restart them and it worked.
Also made a system reboot to check if it still work fine after that, all is ok.

Will comment lines in /etc/apt/sources.list.d/bigbluebutton.list and bigbluebutton-ubuntu-support-focal.list to avoid surprises in the future and being able to update system without breaking bbb.

**Comment by matrixbx** [comment]
The previous actions left our instance with an outdated version of greenlight so I changed my mind and started again bbb-install.sh. Reconfigured files /usr/share/bbb-web/WEB-INF/classes/spring/turn-stun-servers.xml, /usr/share/bigbluebutton/nginx/sip.nginx and /root/greenlight/.env.
Everything's looks to be functioning.
