### ISSUE TITLE
Add Playwright tests for tldraw whiteboard

### ISSUE THREAD

**Issue by MaximKhlobystov** [bigbluebutton/bigbluebutton#15419]
This is an issue that tracks the work on test coverage of the tldraw whiteboard.

The test scenarios would include all the main whiteboard features (both single-user and multi-user whiteboard) and their propagation.

- [ ] Draw
- [ ] Eraser
- [ ] Rectangle
- [ ] Ellipse
- [ ] Triangle
- [ ] Line
- [ ] Arrow
- [ ] Text
- [ ] Sticky
- [ ] Color
- [ ] Fill
- [ ] Dash
- [ ] Size
- [ ] Undo

**Additional context**
Special attention should be paid to multi-user whiteboard, propagation of new shapes, propagation of Redo/Undo and deletion.

**Comment by MaximKhlobystov** [comment]
It may be wise to use some visual regression testing tool to verify the results.

**Comment by antonbsa** [comment]
Closing this issue as all the items listed have received a test
