### ISSUE TITLE
Add Playwright test spec for pinning and unpinning webcams

### ISSUE THREAD

**Issue by MaximKhlobystov** [bigbluebutton/bigbluebutton#15417]
This is an issue that tracks the development of a new test spec: pinning (dropdown) and unpinning (dropdown / "Unpin" button) multiple webcams.

**Describe the test scenario, be specific**

1. Create 3 browser sessions (session 1, session 2 and session 3).
2. _All sessions_: share webcam.
3. _Session 1_: click on the name inside session 2's webcam, select "Pin" inside the dropdown.
4. _All sessions_: verify that session 2's webcam moved to the first place and got "Unpin" button.
5. _Session 3_: click on the name inside session 1's webcam, select "Pin" inside the dropdown.
6. _All sessions_: verify that session 1's webcam moved to the second place in all sessions.
7. _Session 3_: click on the name inside session 2's webcam, select "Unpin" inside the dropdown.
8. _All sessions_: verify that session 2's webcam lost the first position and "Unpin" button, and session 1's webcam moved to the first place.
9. _Session 1_: click on the "Unpin" button inside session 1's webcam.
10. _All sessions_: verify that session 1's webcam lost the first position (everywhere except session 1) and "Unpin" button.

**Comment by antonbsa** [comment]
Done in #15680
