### ISSUE TITLE
Add a Button with "mailto:"-function inside a room

### ISSUE THREAD

**Issue by VITSarah** [bigbluebutton/bigbluebutton#15420]
**Is your feature request related to a problem? Please describe.**
The problem arises that users do not know who to contact in case of problems. As a result, problems that occur during the use of BigBlueButton or even bugs are not passed on to the administrators. 

**Describe the solution you'd like**
My idea would be to introduce a small button (symbolic e.g. letter, warning sign,question mark or the word "help"). When pressing the button, the "mailto:" function should be triggered, which leads to the personal mail program being opened and the field for the addressee being filled in automatically. In addition, a predefined text could be stored as a message.

The configuration of this data, as well as the possibility to activate and deactivate the button could be done via /etc/bigbluebutton/bbb-conf/apply-config.sh.

**Comment by ffdixon** [comment]
The current Help menu item is actual defined as a URL, so you could override it and have it go to a page on your website with additional help information with mailto: links.

<img width="247" alt="image" src="https://user-images.githubusercontent.com/290351/180202574-43552cb3-4432-49b7-9df1-dbe9cd5d519f.png">
