### ISSUE TITLE
Any webcam start/stop steals focus from typing

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#15422]
**Describe the bug**
While you are typing a chat message if anyone stops sharing webcam, the cursor focus is lost - you no longer will be typing.

**To Reproduce**
1. Join a meeting with two different users A and B
2. A shares webcam
3. B starts typing a long public chat message
4. While B is typing, A stops sharing webcam

**Expected behavior**
User A is able to continue typing

**Actual behavior**
User A's cursor is no longer focused on the chat input box and next characters typed will not be appended to the input.

**Screenshots**

**BBB version:**
BigBlueButton 2.5.4, 2.6.x

**Comment by JoVictorNunes** [comment]
This doesn't seem to be a BBB's bug because I'm not able to reproduce it on Firefox. Everything's normal on Firefox. I'm able to reproduce it only on Chrome. Moreover, on Chrome, the text input doesn't lose focus, it keeps focused. However it doesn't receive keyboard events.
