### ISSUE TITLE
/usr/local/bigbluebutton/core/scripts/publish/presentation.rb:42:in `<main>': undefined method `merge' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by MiStErLu** [bigbluebutton/bigbluebutton#15439]
**Describe the bug**

We install this version 2.5.4 version.

We create the file /etc/bigbluebutton/recording/presentation.yml with this content (in order to add mp4 export)

video_formats:
- webm
- mp4

When we create a record it's never arrived

In the log we can see this error :

Jul 25 12:37:44 bbb-test-25-backend-2 bbb-rap[290905]: /usr/local/bigbluebutton/core/scripts/publish/presentation.rb:42:in `<main>': undefined method `merge' for nil:NilClass (NoMethodError)
Jul 25 12:37:44 bbb-test-25-backend-2 bbb-rap[290905]: Success?: false
Jul 25 12:37:44 bbb-test-25-backend-2 bbb-rap[290905]: Process exited? true
Jul 25 12:37:44 bbb-test-25-backend-2 bbb-rap[290905]: Exit status: 1

I hope it's will help.

**To Reproduce**
1. Create a file /etc/bigbluebutton/recording/presentation.yml with options (mode 644 owner root:root)
2. Create a room and generate a record
3. Look in journalctl to see the error

**Expected behavior**

**Actual behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, Mac]
 - Browser [e.g. Chrome, Safari]

**Smartphone (please complete the following information):**
 - Browser [e.g. stock browser, Safari]

**Additional context**

**Comment by GuiLeme** [comment]
Hey @MiStErLu, as a quick fix and an investigation strategy, could you make a recording in the following scenarios, to see if any of them fails?

 - [ ] Remove the `/etc/bigbluebutton/recording/presentation.yml` file (this should work);
 - [ ] Remove the `mp4` line without removing the file.

If something else comes up, contact us again with more logs and information, if possible, please.
Thank you in advance!

**Comment by MiStErLu** [comment]
I remove the file and it's work. i just give you a issue and a bug.

**Comment by GuiLeme** [comment]
@MiStErLu thanks for the report I will work on that, if any other information shows up, please contact us :slightly_smiling_face:
