### ISSUE TITLE
Users ejected from Meetings

### ISSUE THREAD

**Issue by MBM1607** [bigbluebutton/bigbluebutton#15430]
In meetings, some users with poor connections are automatically getting ejected from meetings.

```
$ sudo bbb-conf --check | grep BigBlueButton
   BigBlueButton Server 2.5.4 (3063)
```

**Screenshots**
![image_2022_07_22T11_22_17_131Z(1)](https://user-images.githubusercontent.com/47133639/180453942-836e3810-f192-4e9b-b9a5-5ac13fed97c1.png)

**Comment by mokazemi** [comment]
This is duplicate of this issue: #15070

**Comment by MBM1607** [comment]
Sorry, I didn't find that issue while searching. @mokazemi  should I close this issue?
