### ISSUE TITLE
Raw files do not exist, but the meeting is supposed to be recorded

### ISSUE THREAD

**Issue by mokazemi** [bigbluebutton/bigbluebutton#15469]
**Describe the bug**
We had a meeting that was recorded and is finished. But there's not recording. 
This is the output of `sudo bbb-record --list-recent`:

![image](https://user-images.githubusercontent.com/18334056/182201915-848f9247-4e80-4231-a83a-902cd4c47a08.png)

It should be processed and published by default. But it's not. 

```
$ sudo bbb-record --rebuild e65f15b248f7a48da30cf8dde7ad2661c3fabf00-1659372376314
Marking for rebuild e65f15b248f7a48da30cf8dde7ad2661c3fabf00-1659372376314
Raw files for e65f15b248f7a48da30cf8dde7ad2661c3fabf00-1659372376314 do not exist, can't rebuild
```

```
$ sudo bbb-record --debug
   -- Ingest and Processing: found recorded meeting but no archive files-- 
  /var/bigbluebutton/recording/status/recorded/4b3e71f206a9dc447888aec5f58ad2d076486463-1659266509370.done
  /var/bigbluebutton/recording/status/recorded/51514cd02b0fafc7740f2ceef098213a1250bfbd-1659215491992.done
  /var/bigbluebutton/recording/status/recorded/e36fb42cbb6c161cd4096f87f73c8704594a00aa-1659349230250.done
  /var/bigbluebutton/recording/status/recorded/e36fb42cbb6c161cd4096f87f73c8704594a00aa-1659354975199.done
  /var/bigbluebutton/recording/status/recorded/e65f15b248f7a48da30cf8dde7ad2661c3fabf00-1659356992678.done
  /var/bigbluebutton/recording/status/recorded/e65f15b248f7a48da30cf8dde7ad2661c3fabf00-1659357389517.done
  /var/bigbluebutton/recording/status/recorded/e65f15b248f7a48da30cf8dde7ad2661c3fabf00-1659359599823.done
  /var/bigbluebutton/recording/status/recorded/e65f15b248f7a48da30cf8dde7ad2661c3fabf00-1659372376314.done
```

**Edit: The same problem is happening to every recording that I make.**

**Comment by mokazemi** [comment]
The issue is fixed by running:
```
systemctl stop bbb-rap-starter
systemctl stop bbb-rap-resque-worker
```
It was the second time that I experienced this issue (I didn't remember this solution). I'll re-open this issue if I experienced this again, or was able to reproduce it.

**Comment by MobinDev** [comment]
I also have this problem.
Do you know how ro reproduce?

**Comment by mokazemi** [comment]
> I also have this problem. Do you know how ro reproduce?

What BBB version you're using, and does stopping and restarting those services help?

**Comment by MobinDev** [comment]
> > I also have this problem. Do you know how ro reproduce?
> 
> What BBB version you're using, and does restarting those services help?

Bigbluebutton version : 2.5.4
No
