### ISSUE TITLE
Assign a webcam to be the presentation area

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#15468]
**Is your feature request related to a problem? Please describe.**
In some classrooms, the instructor has a high definition webcam that is the focus of the lecture.   There is no presentation or screen share.

**Describe the solution you'd like**
Ability to make the presentation area use a webcam for content.

**Describe alternatives you've considered**
It's possible to ask students to bring focus to a webcam, but that doesn't make it as large as having the webcam take up the presentation area.

**Additional context**
By making a webcam the focus of the presentation area, it would also make the webcam independent from existing drag-and-drop webcam operations.  For example, if the user drags their webcams under the chat area, the presentation area (with the webam) should stay.

Once the instructor assigns the webcam to the presentation area, it becomes the default presentation area.  That is, if the instructor starts screen sharing (which takes over the presentation area), then stops screen sharing, the assigned webcam becomes visible again.

**Comment by einhirn** [comment]
Maybe this is related to #8388, which describes an "auto focus" on the current speaker...
