### ISSUE TITLE
Notifications for user join/leave not triggering

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#15463]
**Describe the bug**

**To Reproduce**
1. Set the notifications in Settings -> Notifications to enable both audio + toast for user join/leave
2. Join with a user

**Expected behavior**
a toast and a pop

**Actual behavior**
no notification currently

**Screenshots**
![Screenshot from 2022-07-29 10-14-42](https://user-images.githubusercontent.com/6312397/181779834-9ca35889-7b1a-4ea4-88cd-491bf555199b.png)

**BBB version: 2.6.0-alpha.2 + some commits -- latest on v2.6.x-release**

**Additional context**
I think this was working a week or two ago, I use it often

**Comment by JoVictorNunes** [comment]
Both audio and popup are working properly for me. Tested on latest on v2.6.x-release (https://github.com/bigbluebutton/bigbluebutton/commit/0ab0bb458100c99bb12a9bd2107271f5db5eda20).
