### ISSUE TITLE
Upgrade path from 2.4 to 2.5 with keeping my users and rooms

### ISSUE THREAD

**Issue by lindenthal** [bigbluebutton/bigbluebutton#15461]
Hi,
First of all thanks a lot building this great software. We are using it daily and it really helps us to stay connected in large teams.

I really hope that this is the correct place to ask this question. If not I apologize for this. And I appreciate any help where to ask this question.

We are about to upgrade from 2.4 to 2.5. I had a look at your [upgrade instructions](https://docs.bigbluebutton.org/2.5/install.html#upgrading-bigbluebutton-25). It says:

> If you are upgrading BigBlueButton 2.4 or 2.3 we recommend you set up a new Ubuntu 20.04 server with BigBlueButton 2.5 and then [copy over your existing recordings from the old server](https://docs.bigbluebutton.org/admin/customize.html#transfer-published-recordings-from-another-server).

Does this mean that we lose our data such as the room configurations and the user that we have registered. Is there an upgrade path without loosing our data? If yes, can you please route me to the documentation. I googled it but couldn't find anything.

Thanks a lot for your help. I really appreciate that.

Best
Niels

**Comment by ffdixon** [comment]
> Does this mean that we lose our data such as the room configurations and the user that we have registered. Is there an upgrade path without loosing our data? If yes, can you please route me to the documentation. I googled it but couldn't find anything.

What front-end are you using to access BigBlueButton?  Is it GreenLight, Moodle, etc. All the logic for setting up and configuring rooms is in the front-end.  BigBlueButton has no user database, no calendar, and no storage of room preferences.

You can think of BigBlueButton like a web server.  You don't tell the web server that tomorrow at 2pm you are going to download a particular file, you just make a request, you get the file, and the web server moves on to the next request.

In a similar manner, you don't tell BigBlueButton that you want to start a session tomorrow at 2pm.  When you want to start a session, your front-end makes a `create` API request and passes along the settings for the room. Users than join using the `join` API request, which tells BigBlueButton their role.

The only data that is stateful on the BigBlueButton server is the recordings.  So if you setup a new BigBlueButton server, move over the recordings (you need only move them, not rebuild them), and then modify your front-end to point to the new BigBlueButton server (change the API URL and shared secret), then users should be whole.

It sounds like you are using GreenLight, which means you'll either keep users accessing the old BigBlueButton server (using it only for GreenLight), or migrate GreenLight to the new server as well (see https://github.com/bigbluebutton/greenlight/issues/2544).

**Comment by lindenthal** [comment]
Hi @ffdixon,

Thanks a lot for your support. I really really appreciate this. There is isn't a sponsor button for your project, right?

Best
Niels

**Comment by ffdixon** [comment]
Glad to hear!

Want to help the project, tweet some love to @bigbluebutton as how it's helping you teach your students online.  This really helps spread awareness.
