### ISSUE TITLE
Add Playwright test for removing a user

### ISSUE THREAD

**Issue by MaximKhlobystov** [bigbluebutton/bigbluebutton#15479]
This issue tracks the development of the test spec related to removing users.

**Describe the test scenario, be specific**

1. Join a new meeting with 3 users: 2 moderators and 1 attendee.
2. Moderator 1: click on moderator 2's name in userlist, select "Remove user".
3. Verify that moderator 2 was removed from userlist.
4. Attendee: verify that there's no "Remove user" option when clicking on another user's name in userlist.
5. Moderator 1: click on attendee's name in userlist, select "Remove user".
6. Verify that attendee was removed from userlist.

**Comment by antobinary** [comment]
Closed via #16465
