### ISSUE TITLE
in aws ec2 webcames only get Intranet IP 

### ISSUE THREAD

**Issue by libobo1112006** [bigbluebutton/bigbluebutton#15492]
**Describe the bug**
in aws ec2 webcames only get Intranet IP 
in FF about:webrtc

Local candidate only have  Intranet IP 
![image](https://user-images.githubusercontent.com/8475053/183021270-6214c37b-a53d-4d9f-9fbf-77a98c8db9eb.png)

 when voice is ok。
![image](https://user-images.githubusercontent.com/8475053/183021061-0d372f60-6c85-49e8-8a9b-cfed93e4ace1.png)

**Installation type**
Did you install manually or did you use the bbb-install script?
install in bigbluebutton/docker
**Firewall and IP address type**
Is your server behind a NAT or firewall? Does your BBB server have its own IPv4 addres?
 behind a NAT aws ec2 
BBB server have its own IPv4
**Console output**
Please include the full console output from the install.

**Additional context**
in bbb2.3 is ok。
I have changge this file:
WebRtcEndpoint.conf.ini
freeswitch/vars.xml
freeswitch/external.xml

**Comment by libobo1112006** [comment]
**Some progress has been made and problems have been temporarily avoided.**
videoMediaServer: mediasoup => videoMediaServer : Kurento
I find that my video cannot be connected when ice is different at this location.
In kurento-utils.js
pc.setRemoteDescription(answer)

IN mediasoup

v=0
o=mediasoup-client 10000 1 IN IP4 0.0.0.0
s=-
t=0 0
a=ice-lite
a=fingerprint:sha-224 52:EF:17:58:DB:3D:87:75:EF:99:F7:20:97:70:6D:A9:0E:57:E5:50:B4:E7:01:AC:09:5F:2F:E6
a=msid-semantic: WMS *
a=group:BUNDLE 0
m=video 7 UDP/TLS/RTP/SAVPF 96
c=IN IP4 127.0.0.1
b=TIAS:200000
b=AS:200
a=rtpmap:96 VP8/90000
a=fmtp:96 
a=rtcp-fb:96 goog-remb 
a=rtcp-fb:96 transport-cc 
a=rtcp-fb:96 ccm fir
a=rtcp-fb:96 nack 
a=rtcp-fb:96 nack pli
a=extmap:1 urn:ietf:params:rtp-hdrext:toffset
a=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:4 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=extmap:5 http://www.webrtc.org/experiments/rtp-hdrext/playout-delay
a=extmap:6 http://www.webrtc.org/experiments/rtp-hdrext/video-content-type
a=extmap:7 http://www.webrtc.org/experiments/rtp-hdrext/video-timing
a=extmap:8 http://www.webrtc.org/experiments/rtp-hdrext/color-space
a=extmap:9 urn:ietf:params:rtp-hdrext:sdes:mid
a=extmap:10 urn:ietf:params:rtp-hdrext:sdes:rtp-stream-id
a=extmap:11 urn:ietf:params:rtp-hdrext:sdes:repaired-rtp-stream-id
a=setup:active
a=mid:0
a=msid:L5zc9ZYjLmvHEPkC 83ea5667-136f-4f1f-8909-adc63b5aecbc
a=recvonly
a=ice-ufrag:avmiuhfy5fkewuduvgfb3msb68t353mj
a=ice-pwd:0p40wfxwndu4u8vch6htpoud4yr571cx
a=candidate:udpcandidate 1 udp 1076558079 PUBLICIP 31102 typ host
a=candidate:tcpcandidate 1 tcp 1076302079 PUBLICIP 29879 typ host tcptype passive
a=end-of-candidates
a=ice-options:renomination
a=rtcp-mux
a=rtcp-rsize
a=content:main

IN Kurento 

v=0
o=- 3869174617 3869174617 IN IP4 0.0.0.0
s=Kurento Media Server
c=IN IP4 0.0.0.0
t=0 0
a=extmap-allow-mixed
a=msid-semantic: WMS 4TVY2TkFcnbeOReXF7vP7g5laZoPAr6mb7v9
a=group:BUNDLE 0
m=video 1 UDP/TLS/RTP/SAVPF 96
b=TIAS:50000
b=AS:50
a=rtpmap:96 VP8/90000
a=fmtp:96 
a=rtcp:9 IN IP4 0.0.0.0
a=rtcp-fb:96 goog-remb
a=rtcp-fb:96 ccm fir
a=rtcp-fb:96 nack
a=rtcp-fb:96 nack pli
a=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=setup:active
a=mid:0
a=recvonly
a=ice-ufrag:0/tW
a=ice-pwd:cgmLbHyv9H7/5R8BLdYvRd
a=fingerprint:sha-256 EF:F0:A2:BF:50:A7:5B:C3:A3:CA:F5:3B:2B:C3:0B:EC:0C:34:2E:0C:98:ED:01:01:5E:84:99:FA:63:8E:CE:9E
a=ssrc:176234920 cname:user2843940848@host-1c4be482
a=rtcp-mux
a=content:main

The main differences are as follows:
a=ice-lite
a=ice-options:renomination

**Is there any other way to fix this problem？**

**Comment by prlanzarin** [comment]
Please avoid using GitHub issues to debug setup-related stuff.
Use the mailing lists instead, https://docs.bigbluebutton.org/support/getting-help.html.

> Is there any other way to fix this problem？

Yes. Docs: https://docs.bigbluebutton.org/admin/configure-firewall.html#updating-mediasoup
