### ISSUE TITLE
[2.5.4] is it Ok that bbb-rap-starter disabled and stopped after setup?

### ISSUE THREAD

**Issue by amg-web** [bigbluebutton/bigbluebutton#15496]
is it Ok that bbb-rap-starter disabled and stopped after fresh setup?

![Screenshot from 2022-08-06 10-28-11](https://user-images.githubusercontent.com/22151881/183239409-ab884f35-4b29-405a-8d10-c48265b3272d.png)

**Comment by mokazemi** [comment]
Do you think it's kind of related to this issue that I just made but closed? #15469 
Honestly I didn't check to see if the services are running or dead like yours.

**Comment by amg-web** [comment]
@mokazemi 
yes. same result. 
- set fresh server
- services is not running 
- no events processing

**Comment by mokazemi** [comment]
> @mokazemi yes. same result.
> 
>     * set fresh server
> 
>     * services is not running
> 
>     * no events processing

Though, in my case it's not a fresh server. I think something has caused them to stop.

**Comment by amg-web** [comment]
after fresh setup services are dead
after reboot services are dead
after bbb-conf --clean or bbb-conf --restart - services are running

**Comment by mokazemi** [comment]
> after fresh setup services are dead after reboot services are dead after bbb-conf --clean or bbb-conf --restart - services are running
Oh, Got it! Thanks for helping to reproduce the issue. 
Rebooting the server causes `bbb-rap-starter` and `bbb-rap-resque-worker` become inactive, so that recordings doesn't get processed and published, and cause this problem: #15469

**Comment by amg-web** [comment]
@mokazemi 
you are welcome

also I see this error while executing bbb-conf --clean
![Screenshot from 2022-08-09 09-48-48](https://user-images.githubusercontent.com/22151881/183583140-6fd20a8a-204e-41f7-ac64-20e751dffaf3.png)
