### ISSUE TITLE
Export Poll analytics to excel spreadsheet or to a report format

### ISSUE THREAD

**Issue by JT1983** [bigbluebutton/bigbluebutton#15508]
The idea here is to be able to copy poll answers for each user into an Excel spreadsheet that could be used to generate a report for users showing which questions were correct and incorrect.

**Comment by mokazemi** [comment]
> The idea here is to be able to copy poll answers for each user into an Excel spreadsheet that could be used to generate a report for users showing which questions were correct and incorrect.

You're able to export and download Learning Dashboard Analysis data (as csv), which has polls included.

**Comment by JT1983** [comment]
Oh I didn't see an option for this? Can you explain how I can do this?
Thanks

**Comment by mokazemi** [comment]
[This](https://docs.bigbluebutton.org/2.4/new.html#learning-analytics-dashboard) is more information about the **learning analysis dashboard** that is since BBB 2.4, But in 2.5 you are also able to export and download its data. There's a button for it at the bottom of the dashboard.
