### ISSUE TITLE
Removing presentation is broken.

### ISSUE THREAD

**Issue by GuiLeme** [bigbluebutton/bigbluebutton#15503]
**Describe the bug**

When trying to delete some presentations right after uploading them, they disappear from the presentation menu (when clicking the + sign), however, they are not excluded from the presentation-uploader modal (instead, the user needs to do the same routine twice).

**To Reproduce**
1. add some presentations via presentation uploader-modal (I did it with 2 identical presentations in the video, but it would work with all of them being different from each other);
2. open again the presentation-uploader modal and remove all the previously added presentations;
3. enter the presentation-uploader modal again and see all the presentations right there again.

**Expected behavior**
Once excluded, the presentations shouldn't come back and we wouldn't need to exclude it again.

**Actual behavior**
The exclusion needs to be done twice.

**BBB version:**
BigBlueButton Server 2.6

**Comment by antobinary** [comment]
@ramonlsouza may we close this?
