### ISSUE TITLE
Broadcast to all breakout rooms at once.

### ISSUE THREAD

**Issue by JT1983** [bigbluebutton/bigbluebutton#15506]
It would be really cool if the teacher could speak to all breakout rooms at the same time to let them know they have 5 minutes left to complete their individual tasks in the breakout room. 

The idea here would be a one way message to all breakout rooms to prevent all rooms replying.

**Comment by mk-hs** [comment]
It's already possible to send a text message to all breakout rooms in 2.5.

https://docs.bigbluebutton.org/2.5/new.html#text-message-broadcasting-to-breakout-rooms
