### ISSUE TITLE
pinch-zoom not works on Android & iOS BigBlueButton 2.6.0-alpha.2

### ISSUE THREAD

**Issue by sakdeniz** [bigbluebutton/bigbluebutton#15521]
The pinch-zoom feature does not work on Android and iOS devices.

Tried with BigBlueButton 2.6.0-alpha.2

Please fix the issue.

**Comment by antobinary** [comment]
Thanks for reporting! This is related - https://github.com/tldraw/tldraw/issues/665 
Thanks @KDSBrowne for linking to that issue

**Comment by antobinary** [comment]
I just tested this on BBB 2.6.9 and could no longer reproduce. Please comment/reopen if you're still having issues. Feel free to do a quick test on test26.bigbluebutton.org
