### ISSUE TITLE
Missing http security headers

### ISSUE THREAD

**Issue by laserrapt0r** [bigbluebutton/bigbluebutton#15522]
The installation of BBB 2.5.4 (with bbb-install-2.5) does not set http security headers like content-security-policy, x-frame-options, hsts, x-content-type-options. 

Is there any reason for not using these settings?

**Comment by kepstin** [comment]
A few different mixed up things here.

* [Strict-Transport-Security (HSTS)](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Strict-Transport-Security): Yes, we should be enabling this whenever doing an installation with HTTPS enabled (this should be added to bbb-install and the installation docs).
* [X-Frame-Options](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options): We have some use cases where BBB is explicitly loaded into frames, so there isn't really a once size fits all option here. If we set it by default we will have to provide a way to disable or modify it.
* [Content-Security-Policy (CSP)](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP): Probably makes sense in most cases, but again this will need to be done in a way that allows customization to handle e.g. the BBB client being loaded off a CDN.
* [X-Content-Type-Options](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Content-Type-Options) Should be safe to enable by default. Only thing to watch out for is images uploaded as presentations with incorrect filenames - I think we do sniffing on them and fix them up as part of our server side processing.

**Comment by laserrapt0r** [comment]
Thanks for your reply. You say it should be implemented with the bbb-install script. Should I open an issue there?

**Comment by antobinary** [comment]
> Strict-Transport-Security (HSTS): (...) (this should be added to bbb-install and the installation docs).

- [ ] https://github.com/bigbluebutton/bbb-install/issues/551
- [ ] https://github.com/bigbluebutton/bigbluebutton/issues/15561

> X-Content-Type-Options Should be safe to enable by default.
 - [ ] https://github.com/bigbluebutton/bbb-install/issues/552

These seemed like the two that are ready to be enabled. For the other ones, what would you recommend @kepstin ? Adding a sentence for each in the docs?

**Comment by ffdixon** [comment]
Very interested to dig deeper.  What versions of BigBlueButton and GreenLight did you have tested.

**Comment by ffdixon** [comment]
There is now support for SHA265 and SHA512, see [docs](https://docs.bigbluebutton.org./new-features/#improved-support-for-various-sha-algorithms-for-checksum-calculation) for BigBlueButton 2.7.5.

Regarding some of the lower-level options. we have them listed [above](https://github.com/bigbluebutton/bigbluebutton/issues/15522#issuecomment-1219484636).

> If we evaluated which Nginx directives are required for a secure configuration, I'll be happy to share it here.

Yes!

**Comment by hex-m** [comment]
Reproducible using Mozilla HTTP Observatory to scan one of the demo servers: https://developer.mozilla.org/en-US/observatory/analyze?host=demo6.bigbluebutton.org%2Fhtml5client%2F
