### ISSUE TITLE
Exported shared notes unreadable on dark mode

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#15535]
**Describe the bug**

**To Reproduce**
1. Start a meeting
2. write some text in the shared notes
3. select "Move notes to whiteboard" in the shared notes panel
4. (the new pdf with the shared notes is readable at this point)
5. Go to Settings and enable dark mode

**Expected behavior**
The text on the slide should still be readable (or more accurately -- the background on the slide should not be influenced by dark mode)
![Screenshot from 2022-08-15 11-15-17](https://user-images.githubusercontent.com/6312397/184664105-d9ef4076-a60e-4724-a388-0479c6e55a7a.png)

**Actual behavior**
The background of the slide with shared notes text turns dark, and the text is dark, so can't be seen.
![Screenshot from 2022-08-15 11-15-34](https://user-images.githubusercontent.com/6312397/184664139-c650d98f-4e9f-4b87-b767-2bdc5530ac15.png)

**Screenshots**
inline^

**BBB version:**
BigBlueButton 2.6.0-alpha~3

This console error might be relevant?!
![Screenshot from 2022-08-15 11-15-49](https://user-images.githubusercontent.com/6312397/184664249-eda5fc0a-9c31-44a3-a7f5-2328f38b5dba.png)

**Comment by danielpetri1** [comment]
This appears to be the case with any uploaded PDF that has a transparent background, not just the ones from the shared notes.

I see two ways around this:
- Add a white background forcefully during presentation conversion if needed
- Default the whiteboard area to white in the client (as was the case with the whiteboard before Tldraw (?))

Any other ideas?
Nice catch and thanks for sharing!

**Comment by antobinary** [comment]
I think if you're defaulting the font color to X, you should default the background to <something in high contrast to X>

**Comment by hunben** [comment]
Similar Issue (see screenshot)

1.Start a new meeting in test26.bigbluebutton.org 
2. Open shared notes 
3. Write some text
4. Use buttom move to presentation
![sharednotesfail](https://user-images.githubusercontent.com/14301157/185717339-d86e03e6-984a-470c-a600-361acd1ae21e.png)

5. Text not apearing and the interface kind of crashes

**Comment by danielpetri1** [comment]
Hi @hunben! This is a know issue and fixed in PR #5474.

**Comment by danielpetri1** [comment]
This issue can be closed since [this PR](https://github.com/alangecker/bbb-etherpad-plugin/pull/6) was merged.
