### ISSUE TITLE
RTL: Previous/next slide icons flipped

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#15542]
**Describe the bug**
The buttons for next/previous slide `<` and `>` seem flipped.

**To Reproduce**
1. Join a meeting as a moderator, take presenter control
2. switch display language to a RTL one (I used Arabic in this case)

**Expected behavior**
2.5 (correct I think*)
![Screenshot from 2022-08-15 14-19-58](https://user-images.githubusercontent.com/6312397/184692848-f7eafbbe-021b-497b-8b9a-8b54e82b67da.png)

**Actual behavior**
2.6 (incorrect I think*)
![Screenshot from 2022-08-15 11-25-31](https://user-images.githubusercontent.com/6312397/184694250-a27c3b83-0da8-4b49-9a81-dfea90ac649f.png)

**Screenshots**

**BBB version:**
BigBlueButton 2.6.0-alpha~3
Client build 77

**Comment by antobinary** [comment]
Might be addressed by https://github.com/bigbluebutton/bigbluebutton/pull/15539 but not sure. @JoVictorNunes is it?

**Comment by JoVictorNunes** [comment]
> Might be addressed by #15539 but not sure. @JoVictorNunes is it?

That's right. it's addressed by https://github.com/bigbluebutton/bigbluebutton/pull/15539.
