### ISSUE TITLE
Empty slides bbb 2.5

### ISSUE THREAD

**Issue by shmelfrol** [bigbluebutton/bigbluebutton#15549]
Installed bbb 2.5.4 and got eampty slides. Please, help to solve the problem/
![bbb-empty-slide](https://user-images.githubusercontent.com/104349214/185071902-2f0872ab-e297-47b2-818e-757c0f71a70c.png)

**Comment by antobinary** [comment]
Hi @shmelfrol 

What do you see in the browser console?  (right click on the page -> Inspect) Any errors?
Are you uploading a presentation different than the default? If so, could you try to upload the same file on test25.bigbluebutton.org
Did you install via `bbb-install-2.5.sh`? Are you using letsencrypt certificates? Does the browser complain about https and security on this page -- is the url starting with http or https and is the text red?

P.S. The google group https://groups.google.com/g/bigbluebutton-setup is a better place to debug setup problems in future.

**Comment by shmelfrol** [comment]
yes. i installed via bbb-install-2.5.sh. But i use custom cert from Reg.RU. i put ca-certificate to /usr/share/ca-certificates/mosilla
and then done these commands:
sudo dpkg-reconfigure ca-certificates
sudo update-ca-certificates
besides, i add information about certs in nginx config:
server_tokens off;

server {
  listen 80;
  listen [::]:80;
  server_name vcs1.kubstu.ru;
  return 301 https://$server_name$request_uri; #redirect HTTP to HTTPS

}
server {
  listen 443 ssl http2;
  listen [::]:443 ssl http2;
  server_name vcs1.kubstu.ru;

    ssl_certificate /etc/certs/certificate.crt;
    ssl_certificate_key /etc/certs/kubstu.ru.key;
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 10m;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-S>


    # HSTS (comment out to enable)
    #add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;

  access_log  /var/log/nginx/bigbluebutton.access.log;

  # BigBlueButton landing page.
  location / {
    root   /var/www/bigbluebutton-default;
    index  index.html index.htm;
    expires 1m;
  }
  # Include specific rules for record and playback
  include /usr/share/bigbluebutton/nginx/*.nginx;
  include /etc/bigbluebutton/nginx/*.nginx; # possible overrides
}

after that web-cam, audio is ok, but presentation after loading is empty

**Comment by shmelfrol** [comment]
![bbb2 3](https://user-images.githubusercontent.com/104349214/185143506-a9e29a98-ede8-43cc-9348-cfdb42a20c3e.png)

added certs in 2.3 bbb and got the same result - slides - empty

**Comment by shmelfrol** [comment]
i find https://github.com/bigbluebutton/bigbluebutton/issues/12151
i added      export NODE_TLS_REJECT_UNAUTHORIZED=0     in  /usr/share/meteor/bundle/systemd_start.sh
and it works..
but i don't understand another advice:
export NODE_EXTRA_CA_CERTS="/etc/ssl/certs/my_CA.pem"

i have ca certificate, but i put cetrificate_ca.crt into /usr/share/ca-certificates/mozila
after that i have done commands
sudo dpkg-reconfigure ca-certificates
sudo update-ca-certificates

what is the difference between folders /usr/share/ca-certificates/mozila and /etc/ssl/certs/???
and what certificate i must put in /etc/ssl/certs/?
