### ISSUE TITLE
PresentationUploader's crash when number of pages exceeds 200

### ISSUE THREAD

**Issue by GuiLeme** [bigbluebutton/bigbluebutton#15543]
**Describe the bug**

When uploading a document with more pages than the maximum allowed (in this case 200), the presentation-uploader modal crashes and the toast doesn't properly display the error.

As shown in the video below 

https://user-images.githubusercontent.com/69865537/184706183-cd517306-46ac-4eeb-a301-a7aa786154a1.mp4

**To Reproduce**
1. Go to the presentationUploader modal
2. Click to upload a new presentation
3. Choose one that exceeds the maximum number of pages 
4. See the error 

**Expected behavior**
After a while, the toast responsible for notifying the new presentation converting process should display an error message, and when entering the presentation  uploader modal, the error should be displaying, as well as a "clear errors" button should appear right below the list of documents. 

**Actual behavior**
What is happening is that the toast keeps showing the presentation converting, and when entering the modal, there is simply no other buttons to neither clear the errors, or upload new presentation, the problematic presentation just keeps in converting status and after a while, it disappears leaving the crashed modal behind.

**BBB version:**
Example:
$ sudo bbb-conf --check | grep BigBlueButton
BigBlueButton Server 2.6.0-alpha.2 (250)

Apparently it is also happening on [test25](test25.bigbluebutton.com), and also [dev25](dev25.bigbluebutton.com)

**Comment by antobinary** [comment]
Closely related https://github.com/bigbluebutton/bigbluebutton/issues/15435 with https://github.com/bigbluebutton/bigbluebutton/pull/15438
Could we look at these two when addressing this issue please?
