### ISSUE TITLE
Test removing a (previously uploaded) presentation

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#15540]
**Describe the test scenario, be specific**
On two occassions we've had presentations marked for removal re-appear. This is the more recent case: https://github.com/bigbluebutton/bigbluebutton/issues/15503

Steps to reproduce:

**Edge cases**
If user A removes the presentation, and user B takes over presenterr status, does user B still see the removed presentation listed in the presentation pool ('+' action button or pres upload modal)

**Additional context**

**Comment by MaximKhlobystov** [comment]
Good point. We have an [existing test](https://github.com/bigbluebutton/bigbluebutton/blob/v2.6.x-release/bigbluebutton-tests/playwright/presentation/presentation.js#L134) that checks the removal of the default presentation. I think this should be a separate test. I've added it to the test plans:
[Deleting previously uploaded presentations in 2.5](https://docs.bigbluebutton.org/2.5/release-tests.html#deleting-previously-uploaded-presentations)
[Deleting previously uploaded presentations in 2.6](https://docs.bigbluebutton.org/2.6/release-tests.html#deleting-previously-uploaded-presentations)
