### ISSUE TITLE
Path issue virtual-backgrounds/Blur failed No such file or directory

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#15555]
**Describe the bug**
I am not spotting visual issue but when digging through `/var/log/nginx/error.log` I see lines as follows:

```
2022/08/17 04:16:30 [error] 7461#7461: *34715 open() "/usr/share/meteor/bundle/programs/web.browser/app/resources/images/virtual-backgrounds/Blur" failed (2: No such file or directory), client: 103.135.xx.xx, server: xx.xx.xx.com, request: "GET /html5client/resources/images/virtual-backgrounds/Blur HTTP/2.0", host: "xx.xx.xx.com", referrer: "https://xx.xx.xx.com/html5client/join?sessionToken=izg8wumdlskdyiba"
```

```
ls -l /usr/share/meteor/bundle/programs/web.browser/app/resources/images/virtual-backgrounds/thumbnails/
total 16
-r--r--r-- 1 root root 2170 Jul 18 18:50 blur.jpg
-r--r--r-- 1 root root 1755 Jul 18 18:50 board.jpg
-r--r--r-- 1 root root 3563 Jul 18 18:50 coffeeshop.jpg
-r--r--r-- 1 root root 3301 Jul 18 18:50 home.jpg
__:~# ls -lr /usr/share/meteor/bundle/programs/web.browser/app/resources/images/virtual-backgrounds/
total 2564
drwxr-xr-x 2 root root   4096 Aug 16 17:14 thumbnails
-r--r--r-- 1 root root 316733 Jul 18 18:50 home.jpg
-r--r--r-- 1 root root 446038 Jul 18 18:50 coffeeshop.jpg
-r--r--r-- 1 root root 989152 Jul 18 18:50 brickwall.jpg
-r--r--r-- 1 root root 509102 Jul 18 18:50 board.jpg
-r--r--r-- 1 root root 348999 Jul 18 18:50 architecture.jpg

```

**More Info**
After checking with @JoVictorNunes this was mentioned:
`/usr/share/meteor/bundle/programs/web.browser/app/resources/images/virtual-backgrounds/Blur` actually needs to be `/usr/share/meteor/bundle/programs/web.browser/app/resources/images/virtual-backgrounds/thumbnails/Blur`

Looks like there is also some possible confusion on the exact set of files -- no brickwall thumb, no architecture thumb, odd blur thumb

**BBB version:**
BigBlueButton 2.5.4

**Comment by prlanzarin** [comment]
> Looks like there is also some possible confusion on the exact set of files -- no brickwall thumb, no architecture thumb, odd blur thumb

Brickwall/architecture are leftover files. Just remove them.

**Comment by prlanzarin** [comment]
> After checking with @JoVictorNunes this was mentioned:
/usr/share/meteor/bundle/programs/web.browser/app/resources/images/virtual-backgrounds/Blur actually needs to be /usr/share/meteor/bundle/programs/web.browser/app/resources/images/virtual-backgrounds/thumbnails/Blur

That does not make much sense. Thumbnail base path is hardcoded, so it's probably being requested correctly beforehand.
 
The only way it should be getting the base _image_ path is during virtual background worker creation. In that case, it shouldn't be requesting _anything_ for blur since it's a slightly different path from regular background images.

Is the virtualBackgrounds configuration dictionary (settings.yml) for the server where that's happening the default or a custom one?

**Comment by prlanzarin** [comment]
> effect changes

Yup. This is the borked code: https://github.com/bigbluebutton/bigbluebutton/blob/14d80b4e29cb386e9e8b265c7a69f34877b9b5bc/bigbluebutton-html5/imports/ui/services/virtual-background/index.js#L245-L252. Should have some handling for blur as an edge case there.

**Comment by JoVictorNunes** [comment]
> Thumbnail base path is hardcoded, so it's probably being requested correctly beforehand.

Yep, at a first glance I thought it was a thumbnail issue (symptom of a supposed custom configuration). But it's not the case. It's indeed hardcoded. Thanks, @prlanzarin !
