### ISSUE TITLE
Screenshare: volume controls are hidden

### ISSUE THREAD

**Issue by prlanzarin** [bigbluebutton/bigbluebutton#15559]
**Describe the bug**

The volume controls that should appear on the receiver side when hovering over a shared screen are **hidden**.

Reproducible in 2.5 and 2.6. BBB 2.4 isn't affected.

Originally implemented in https://github.com/bigbluebutton/bigbluebutton/pull/13688. Disabled by default in 2.4, but enabled by default in 2.5+.

**To Reproduce**
1. Go to a 2.5/2.6 instance with two sessions (s1[Chrome], s2[any browser])
2. s1: share a tab _with audio_ (Chrome)
3. s2: hover over the shared screen. No volume control is shown in the screen sharing container.

**Expected behavior**

Volume controls are shown in the receiver when hovering over the shared screen.

**Actual behavior**

Hidden volume controls.

**Screenshots**

n/a

**BBB version:**

2.5, latest
2.6, latest

**Desktop (please complete the following information):**

n/a

**Smartphone (please complete the following information):**

n/a

**Additional context**

https://github.com/bigbluebutton/bigbluebutton/pull/13688

**Comment by rkazak07** [comment]
Hello, I am using the 2.5.6 version of Bigbluebutton. i'm experiencing screen sharing freezes, I've specified my network speed below, how do I configure it in relation to this issue,

Note: All settings are by default


os: Ubuntu 20.04.5 LTS
---------------------------
Network;
Testing download speed................................................................................
Download: 235.70 Mbit/s
Testing upload speed......................................................................................................
Upload: 174.69 Mbit/s

**Comment by ffdixon** [comment]
Hey @rkazak07, this is a closed issue on a different topic.
