### ISSUE TITLE
bbb-install-2.6 (2.6-prerelease)

### ISSUE THREAD

**Issue by hahaxd35** [bigbluebutton/bigbluebutton#15553]
bbb-html5 postinst return:
/bbb-html5.postinst
setting public.app.bbbServerVersion: 2.5.4 in /usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml 
chown: cannot access '/lib/systemd/system/disable-transparent-huge-pages.service': No such file or directory

as i look into bbb-html5.deb i would say Path is wrong: 
/usr/lib/systemd/system != /lib/systemd/system/

or was my installation broken?

**Comment by antobinary** [comment]
Hi @hahaxd35 
I was preparing a pull request to address this (commit: https://github.com/antobinary/bigbluebutton/commit/3530c5fc517e56e6e22ff90e811751cb952c3049   )
but some more research showed that we might be better keeping the current state... 
https://github.com/elastic/elasticsearch/issues/36994#issuecomment-452490141

Perhaps an extra good measure could be to check if the directory exists before executing `chown`.. However, I also see we create such a directory in`build/packages-template/bbb-config/build.sh` https://github.com/bigbluebutton/bigbluebutton/pull/14616/files#diff-4415a7e6a850d21d5bd5fb051833e85da5aea61d427e7d760cc102e2fcbe91b5R23

so it might be a timing concern...
Maybe @danimo has any insights on the topic?

**Comment by danimo** [comment]
On my installation, `/lib` is a symlink to `/usr/lib`, so both should work, with all pathes beginning in `/lib` being legacy (but should still work!). 

```
$ lsb_release  -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.4 LTS
Release:	20.04
Codename:	focal
```

The changes that move it to `/lib` show that this patch was originally targeted at 18.04 which did not have a consollidated filesystem hirachy. Please revert those parts. Still I am puzzled as to why this breaks.

**Comment by antobinary** [comment]
A clean install with #15630 :

```
Setting up bbb-html5 (2:2.6.0~alpha.3+20220901T161752-git.) ...
Created symlink /etc/systemd/system/multi-user.target.wants/disable-transparent-huge-pages.service → /lib/systemd/system/disable-transparent-huge-pages.service.
Created symlink /etc/systemd/system/bigbluebutton.target.wants/disable-transparent-huge-pages.service → /lib/systemd/system/disable-transparent-huge-pages.service.
Adding bbb-html5.service to autostart using systemd
Created symlink /etc/systemd/system/multi-user.target.wants/bbb-html5.service → /lib/systemd/system/bbb-html5.service.
Created symlink /etc/systemd/system/bigbluebutton.target.wants/bbb-html5.service → /lib/systemd/system/bbb-html5.service.
Setting up bbb-config (2:2.6.0~alpha.3+20220901T161752-git.) ...
......
setting public.app.bbbServerVersion: 2.6.0-alpha.3 in /usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml 
Setting up bigbluebutton (2:2.6.0~alpha.3+20220901T161752-git.) ...
```

If @hahaxd35 or someone else has more info on how to reproduce this (maybe it was an upgraded server from Ubuntu18.04?!) we could reopen or address separately. Otherwise it seems fine given @danimo 's explanation
