### ISSUE TITLE
Kurento Media Server error

### ISSUE THREAD

**Issue by Nemu-z** [bigbluebutton/bigbluebutton#15550]
After upgrading from 2.5.4 to 2.6.0alpha2 i get a couple of errors,
first is about tomcat9 inactive but it already done.

There is error sometimes while you're on conference " An error occurred It has been logged. Please try reloading the page. x is undefined"

systemctl status kurento-media-server gives an error - 
`gst-plugin-scan[562232]: Failed to load plugin '/usr/lib/x86_64-linux-gnu/gstreamer-1.5/libgstcurl.so': /lib/x86_64-linux-gnu/libcurl.so.4: version "CURL_OPENSSL_3"not found (required by /usr/lib/x86_64-linux-gnu/gstreamer-1.5/libgstcurl.so)`

**Comment by prlanzarin** [comment]
The three things you mentioned are unrelated to each other.
First two are known and/or being worked on AFAIK.
The Kurento error: is it up? If it is, then ignore the error.
If it's not: I'm not sure upgrading v2.5.x to v.2.6.x is a tested/supported path yet. IMO you're better off installing an alpha version from scratch in a clean serve until it's stated an v2.5.x -> v2.6.x upgrade path is supported.

**Comment by Nemu-z** [comment]
> The three things you mentioned are unrelated to each other. First two are known and/or being worked on AFAIK. The Kurento error: is it up? If it is, then ignore the error. If it's not: I'm not sure upgrading v2.5.x to v.2.6.x is a tested/supported path yet. IMO you're better off installing an alpha version from scratch in a clean server until it's stated an v2.5.x -> v2.6.x upgrade path is supported.

Kurento is up, just it make error while you're in conference call, but not really affects functionality.

As I google it, the error in conference is regarding "An error occurred It has been logged. Please try reloading the page. x is undefined" related to kurento media server.

**Comment by prlanzarin** [comment]
> Same here BBB 2.5.5 with new install on Ubuntu 20.04 in digital ocean.
> 
> libcurl3 is not available in the apt repository. Maybe the root cause?

The libgstcurl warning is irrelevant, not an error, unrelated to whatever was reported. I recommend ignoring it.
