### ISSUE TITLE
Increase/Decrease camera brightness

### ISSUE THREAD

**Issue by JoVictorNunes** [bigbluebutton/bigbluebutton#15572]
**Is your feature request related to a problem? Please describe.**
Camera brightness.

**Describe the solution you'd like**
It would be cool to be able to increase and decrease camera brightness by using a slider.

![2022-08-22_09-09](https://user-images.githubusercontent.com/62393923/185918209-c2f609e1-b10c-4538-9793-3797249131d2.png)

![2022-08-22_09-10](https://user-images.githubusercontent.com/62393923/185918234-b5ad37f7-aa1a-4db3-b4ae-793c648f7eca.png)

![2022-08-22_09-10_1](https://user-images.githubusercontent.com/62393923/185918246-c24d89cf-99e2-4800-a809-6310528d0cfd.png)

**Describe alternatives you've considered**
n/a

**Additional context**
I think HTML Canvas API allows to do it without much work.

Feature proposed by @TiagoJacobs.

**Comment by TiagoJacobs** [comment]
Very nice!

It might be good to add a label on top of the slider saying: "Brigthness"

Other than that, it's perfect - looking forward to see this feature :D
