### ISSUE TITLE
Simplify guest management choices

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#15599]
**Describe the bug**

**To Reproduce**
1. Create a meeting and join it as moderator
2. Set the guest policy to Ask Moderator (if different) -- Gear icon menu -> Guest policy
![Screenshot from 2022-08-25 13-31-09](https://user-images.githubusercontent.com/6312397/186731444-e45e3e6e-7a02-4b8e-8146-296c3a257da9.png)
3. Join the same meeting with another user with guest=true

**Actual behavior**
This is what the moderator sees:
![Screenshot from 2022-08-25 13-34-43](https://user-images.githubusercontent.com/6312397/186732126-19bd8d3a-0da1-40ac-add5-0f4761d2233e.png)

**Requested behavior**
Only show the last two options
![Screenshot from 2022-08-25 13-34-43](https://user-images.githubusercontent.com/6312397/186732379-17187993-e4c4-44fe-8ad7-9b351fe732d2.png)

Something like
![Screenshot from 2022-08-25 12-06-31](https://user-images.githubusercontent.com/6312397/186732422-8a788782-c20f-4bdc-93e3-3c2a5f267926.png)

but if possible, let's keep the red color (may we, @KDSBrowne ?)

**BBB version:**
BigBlueButton 2.5.5

**Comment by frankemax** [comment]
@antobinary I think there is an option that does this already:
https://github.com/bigbluebutton/bigbluebutton/blob/c0567c9c93ea84a8c5488bfc4a2cd6b588163e08/bigbluebutton-web/grails-app/conf/bigbluebutton.properties#L178
Part of: https://github.com/bigbluebutton/bigbluebutton/pull/11215

**Comment by antobinary** [comment]
@frankemax seems to be correct, thank you for pointing this out!

When setting `authenticatedGuest=false` in `/etc/bigbluebutton/bbb-web.properties` and then setting the guest policy to AskModerator and passing guest=true for the viewers on join, I am indeed only presented with the basic options for approving/denying a guest.
![Screenshot from 2022-12-15 10-23-09](https://user-images.githubusercontent.com/6312397/207899329-33fa4e3a-0854-4702-b87c-809098a87a1e.png)
BBB 2.6.0-beta.3

**Comment by antobinary** [comment]
I'll have to reopen this.
We tried setting `authenticatedGuest=false` in `/etc/bigbluebutton/bbb-web.properties` and it works well in the BigBlueButton context. However, this triggered a bunch of changes. Turns out Greenlight v2 was not passing `guest=true` on guests joining a room so they were entering as normal viewers and bypassing the guest waitroom.
We had Greenlight v2 pass `guest=true` and things were well except that on systems where `authenticatedGuest` was not overridden, issues  like https://github.com/bigbluebutton/bigbluebutton/issues/16425 started to appear.
Then we found that likely other integrations will also be experiencing consequences by such a change...

All in all, we're looking for a client-level, configurable via bbb-html5.yml option to hide "allow all authenticated" and "allow all guests" options.

Closely related: https://github.com/bigbluebutton/bigbluebutton/issues/16604

**Comment by SamuelWei** [comment]
I am against the removal of this differentiation. At our university with its own BBB frontend, there are scenarios, e.g. exam situations, in which students are only allowed to enter the room after approval, but must have confirmed their identity via the frontend. Also in some meetings, registered users are supposed to enter a waiting room because this is necessary for legal reasons. External guests should also be allowed, but it must be clear that their identity has not been checked by the frontend.

**Comment by antobinary** [comment]
Hi @SamuelWei !

> All in all, we're looking for a client-level, configurable via bbb-html5.yml option to hide "allow all authenticated" and "allow all guests" options.

No removal here -- I'd like us to add the option on bbb-html5's settings.yml so that administrators who would like can hide or show the extra complexity.
