### ISSUE TITLE
Right click to cancel text annotation does not work

### ISSUE THREAD

**Issue by Arthurk12** [bigbluebutton/bigbluebutton#15595]
**Describe the bug**
When using the whiteboard text tool, it is possible to right click out of the text box to cancel an already started annotation. This behavior does not happen in 2.5.

**To Reproduce**
1. Join meeting
2. Select the whiteboard text tool
3. Click over the whiteboard and write something
4. Right click out of the text box
5. See error

**Expected behavior**
When right clicking, the text annotation should be cancelled.

**Actual behavior**
The text annotation is confirmed and sent.

**Screenshots**
**2.4(working)**
![2 4](https://user-images.githubusercontent.com/32987232/186726605-db8398f9-9bf1-4457-8d8f-3c0b06801580.gif)

**2.5(not working)**
![2 5](https://user-images.githubusercontent.com/32987232/186726626-68c16744-9df1-472d-a110-e748d951398a.gif)

**Comment by antobinary** [comment]
Thanks for spotting and reporting this @Arthurk12 !
