### ISSUE TITLE
Screensharing and Webcam not working after Update to 2.5.5

### ISSUE THREAD

**Issue by haary** [bigbluebutton/bigbluebutton#15615]
I installed BBB 2.5 in Ubuntu Focal earlier this month with bbb-install-2.5.sh, configured a  TURN Server and everything was working.
Last week BBB was updated to 2.5.5 with packages from the configured repo. The config was overwritten. so that I  had to enable the TURN Server in /usr/share/bbb-web/WEB-INF/classes/spring/turn-stun-servers.xml again and re-enabled sipjsHackViaWs.

Audio/Microphone is working, what does not work is Webcam and Screensharing (was working before the update). Webcam shows Error 1020 and Screensharing Error 1121. Tried from several different OS and Browsers. 

I checked the mediasoup config according to https://docs.bigbluebutton.org/admin/configure-firewall.html#updating-mediasoup and everything is configured correctly. 

Since this happens after the update I suspect some kind of regression.

**BBB version:**
$ sudo bbb-conf --check | grep BigBlueButton
BigBlueButton Server 2.5.5 (3091)

**Comment by antobinary** [comment]
Hi, possible duplication of https://github.com/bigbluebutton/bigbluebutton/issues/10821#issuecomment-733958738 but we can't know as there is very little info included here...

Could you please try to reproduce with bbb-install-2.5.sh again (we have patched that bug) and if still an issue, please start a thread in https://groups.google.com/g/bigbluebutton-setup

**Comment by antobinary** [comment]
Looks like someone reported similar issues in https://groups.google.com/g/bigbluebutton-setup/c/wklcAtlia-s 
Is this you by any chance?

**Comment by haary** [comment]
No, this wasn't me. But I was able to fix the issue on the server for me by replacing the IPs with the hostname and ws:// with wss:// in /usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml

**Comment by antobinary** [comment]
We recommend holding this info in `/etc/bigbluebutton/bbb-html5.yml`

Something like

```
public:
    kurento:
        wsUrl: wss://..............

```

This way upgrades don't mess with it. You can find more about it: https://docs.bigbluebutton.org/admin/configuration-files.html#local-overrides-for-configuration-settings

Well done on debugging and resolving it + reporting back!!

**Comment by croessner** [comment]
Thanks a lot. That fixed it for me!
