### ISSUE TITLE
Active session is closed when accidentially closing the browser tab

### ISSUE THREAD

**Issue by danimo** [bigbluebutton/bigbluebutton#15629]
**Describe the bug**
While running BBB in a tab and closing the tab by accident (which happens easily with a lot of tabs), the user drops out of the conference and has to rejoin.

**To Reproduce**
1. Open a new BBB session
2. Close tab

**Expected behavior**
During an active session, closing the tab should prompt if closing is intentional.

**Actual behavior**
No warning is given and the user has to rejoin or undo the tab close (if a user knows how to do that), resulting in an interruption of the meeting.

**BBB version:**
BigBlueButton Server 2.6.0-alpha.3 (199)

**Desktop (please complete the following information):**
 - OS: [e.g. Linux, Mac]
 - Browser [e.g. Chrome, Safari, Firefox]

**Comment by antobinary** [comment]
Implemented by https://github.com/bigbluebutton/bigbluebutton/pull/15842 on BBB 2.6
![Screenshot from 2022-12-14 10-14-02](https://user-images.githubusercontent.com/6312397/207633996-4270d2ac-3222-4c37-878f-ab313fa5455a.png)
