### ISSUE TITLE
ICE 1005 after updating to 2.5.5

### ISSUE THREAD

**Issue by ZhmerenkaSolution** [bigbluebutton/bigbluebutton#15626]
**Describe the bug**
After bbb-conf --clean Mozilla Firefox can catch 1005 ICE error on establishing microphone connection. After restarting server everything works fine.

**To Reproduce**
1. Clean server by bbb-conf --clean
2. In Mozilla Firefox start a room and try to turn on microphone

**Expected behavior**
Working microphone.

**Actual behavior**
Immediately fires 1005 ICE error.

**Desktop (please complete the following information):**
 - OS: Windows 10, 64bit.
 - Browser: Mozilla Firefox (104.0.1) where error appear. In Chrome (>=104.0.5112.102) microphone works.

**Smartphone (please complete the following information):**
Didn't tested.

**Additional context**
The problem appear in BigBlueButton Server 2.5.5 (3091), in BigBlueButton Server 2.5.4 (3063) microphone work (I have a few servers with different versions to say that exactly).

**Comment by henriquebol** [comment]
Exactly the same problem is happening here.

Firefox (107.0), BigBlueButton 2.5.8 and 2.4.5.

@ZhmerenkaSolution , did you manage to solve?

**Comment by ZhmerenkaSolution** [comment]
@henriquebol I didn't try to fix it anymore, but then in time it disappear. Seems I was simply reinstall it by script https://github.com/bigbluebutton/bbb-install after another BigBlueButton update errors and it's worked now (I have only 2.5.5 server working right now).
