### ISSUE TITLE
SSO integration

### ISSUE THREAD

**Issue by airween** [bigbluebutton/bigbluebutton#15635]
**Describe the bug**
It's not a bug, rather a question. We have an installed BBB instance, it works as well. We can create meetings through API, the invitations delivered, users can join to meetings after they logged in into our SSO server.

But the problem is that if someone catches the meeting URL, they also can join to the chat. There was an IT security audit, and the auditor noticed us.

**To Reproduce**
If you have the meeting URL, you can join to that in a private browser window, or from an other machine without log in.

**Expected behavior**
It would be fine if BBB could check the SSO tokens.

**Additional context**
I reviewed Greenlight, but seems it can use only
* own datastore
* Google
* O365
* Twitter
* native LDAP

But we have only an HTTP based SSO.

Is there any way to integrate it?

Thank you.

**Comment by KiaraGrouwstra** [comment]
you can enable the guest lobby, which would allow moderators to filter out joiners.

we've been using a setup using a custom [tool](https://gitlab.com/bij1/meets/ingang) to talk to the api to create user-level join links tied to their name, such that if someone leaks the link, those joining from their name will enter under the same name, if anything making such leaks easier to detect.

i agree SSO would be nice.
oauth2 already seems offered for e.g. google.
openid connect seems like a more secure iteration tho.

**Comment by airween** [comment]
> you can enable the guest lobby, which would allow moderators to filter out joiners.

thanks for the tip, I'm going to check that.

> we've been using a setup using a custom [tool](https://gitlab.com/bij1/meets/ingang) to talk to the api to create user-level join links tied to their name, such that if someone leaks the link, those joining from their name will enter under the same name, if anything making such leaks easier to detect.

thanks, I'll ask the auditor, will that enough.
 
> i agree SSO would be nice. oauth2 already seems offered for e.g. google. openid connect seems like a more secure iteration tho.

In this case, we can't use 3rd party provider. I do not know the SSO service, but as I know, it supports some regular SSO protocol.

Thanks for your help.

**Comment by makabar** [comment]
We are using greenlight with keycloak and openid. Works well

**Comment by airween** [comment]
> We are using greenlight with keycloak and openid. Works well

Thanks - could you give me any documentation about how can I integrate them?

**Comment by KiaraGrouwstra** [comment]
@airween see https://github.com/bigbluebutton/bigbluebutton.github.io/issues/287#issuecomment-883606939

**Comment by makabar** [comment]
create a client in keycloak protocol openid-connect and accesstype confidential

setup .env in greenlight like this
OPENID_CONNECT_CLIENT_ID=greenlight2
OPENID_CONNECT_CLIENT_SECRET=yoursecretfromclientcredentialinkeycloak
OPENID_CONNECT_ISSUER=https://yourkeycloakurl/auth/realms/realmsettingsname
OAUTH2_REDIRECT=https://yourgreenlighturl/b
