### ISSUE TITLE
Suddenly video has too much delay with audio in the recording

### ISSUE THREAD

**Issue by mokazemi** [bigbluebutton/bigbluebutton#15644]
**Describe the bug**
I'm facing a problem which I don't know the reason. In our today's session recording, I noticed the **video is too much out of sync** with the audio. Everything was alright in the live meeting (everything was in sync) but in the one-hour recording, video is more than 8 minutes behind! 
There wasn't any problem before. It just appeared today. Nothing was changed in the server. 

**Notes:**
- I thought it's related to #8815 but I've checked and the clock is correct (set with systemd-timesyncd with a near server)
- Rebooting the server and restarting BBB didn't help
- The problem seems to be with the video. It's too much early (Such that even the presenter says good-bye in the video and stops the recording, but the audio is correct). 

**To Reproduce**
1. Start a meeting and join with audio
2. Turn on the camera and share your screen
3. wait for a few minutes
4. Start the recording
5. Stop the recording, then end the meeting

**Details**:

```
$ sudo bbb-conf --check

BigBlueButton Server 2.5.5 (3091)
                    Kernel version: 5.4.0-125-generic
                      Distribution: Ubuntu 20.04.5 LTS (64-bit)
                            Memory: 12263 MB
                         CPU cores: 8

/etc/bigbluebutton/bbb-web.properties (override for bbb-web)
/usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties (bbb-web)
       bigbluebutton.web.serverURL: https://vhall.scischool.ir
                defaultGuestPolicy: ALWAYS_ACCEPT
                 svgImagesRequired: true
              defaultMeetingLayout: CUSTOM_LAYOUT

/etc/nginx/sites-available/bigbluebutton (nginx)
                       server_name: vhall.scischool.ir
                              port: 80, [::]:80
                              port: 443 ssl

/opt/freeswitch/etc/freeswitch/vars.xml (FreeSWITCH)
                       local_ip_v4: 130.185.75.197
                   external_rtp_ip: 130.185.75.197
                   external_sip_ip: 130.185.75.197

/opt/freeswitch/etc/freeswitch/sip_profiles/external.xml (FreeSWITCH)
                        ext-rtp-ip: $${local_ip_v4}
                        ext-sip-ip: $${local_ip_v4}
                        ws-binding: 130.185.75.197:5066
                       wss-binding: 130.185.75.197:7443

/usr/local/bigbluebutton/core/scripts/bigbluebutton.yml (record and playback)
                     playback_host: vhall.scischool.ir
                 playback_protocol: https
                            ffmpeg: 4.2.7-0ubuntu0.1

/usr/share/bigbluebutton/nginx/sip.nginx (sip.nginx)
                        proxy_pass: 130.185.75.197
                          protocol: http

/usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml (Kurento SFU)
/etc/bigbluebutton/bbb-webrtc-sfu/production.yml (Kurento SFU - override)
                        kurento.ip: 130.185.75.197
                       kurento.url: ws://127.0.0.1:8888/kurento
                    kurento.sip_ip: 130.185.75.197
               recordScreenSharing: true
                     recordWebcams: true
                  codec_video_main: VP8
               codec_video_content: VP8

/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml (HTML5 client)
/etc/bigbluebutton/bbb-html5.yml (HTML5 client config override)
                             build: 2846
                        kurentoUrl: wss://vhall.scischool.ir/bbb-webrtc-sfu
                  enableListenOnly: true
                    sipjsHackViaWs: true

/usr/share/bbb-web/WEB-INF/classes/spring/turn-stun-servers.xml (STUN Server)
                              stun: stun.l.google.com:19302


# Potential problems described below

```

**Comment by prlanzarin** [comment]
I think this probably has to do with https://github.com/bigbluebutton/kurento-build/pull/1.

**Comment by mokazemi** [comment]
> I think this probably has to do with [bigbluebutton/kurento-build#1](https://github.com/bigbluebutton/kurento-build/pull/1).

But since it was working properly till a few days ago, what is caused the problem?

**Comment by prlanzarin** [comment]
hmm, missed "til a few days ago" part in the original description.
Still might have to do with the PR I mentioned since some of the issues it tackles are intermittent by nature.

**Comment by mokazemi** [comment]
It's an example of the problem:
https://vhall.scischool.ir/playback/presentation/2.3/51514cd02b0fafc7740f2ceef098213a1250bfbd-1662447703226
(Note that the recording starts when the timer is 7 seconds. and in the video, it's shown that I press the stop and it says the meeting is no longer being recorded, but since the video is too behind, It's even shown after that I end the meeting!)

**Comment by mokazemi** [comment]
I think I was able to reproduce this issue with BBB 2.6 demo server. Sounds to be a bug!  @prlanzarin 

It is the result: https://test26.bigbluebutton.org/playback/presentation/2.3/956ef436a3674ef70d01923de7bf7371815c8aed-1662484113443

**steps:**
 - start the meeting
 - share your screen
 - wait for about a minute
 - start recording
 - after a little, stop the recording and close the room as fast as possible!

**Comment by kurjajuur666** [comment]
Had issues with 2.5.5 as well. Recording webcam and audio were extremely out of sync, and during the meeting everything seemed fine, mostly. For one test recording, for example, the webcam video stopped long before the audio did. Reverting to 2.5.4 was our solution.

**Comment by jarrodjay** [comment]
I've got this issue too, on 2.5.5. Hour recording is about 2m50s out.
@kurjajuur666 did you simply install 2.5.4 using the script, or use a fresh OS install?

**Comment by mabras** [comment]
I had to revert this https://github.com/bigbluebutton/bigbluebutton/pull/15149 to fix it.

**Comment by prlanzarin** [comment]
> I had to revert this #15149 to fix it.

That's interesting and a good lead. Thanks for letting us known, I'll forward that internally.

**Comment by kepstin** [comment]
I'm taking a look at the changes in #15149 - I'll let you know if I can figure out the cause. The difference seems to be surprisingly larger.

@mokazemi thanks for reproducing on the demo server - I'll be able to grab the data and logs from your meeting to help debug.

One of the changes made in #15149 was switching from using the "movie" filter input to read video files to using separate inputs to the ffmpeg command. My current theory is that a mistake was made in this conversion, and the seek point calculation is not being done correctly.

**Comment by kepstin** [comment]
I have reprocessed the recording https://test26.bigbluebutton.org/presentation/956ef436a3674ef70d01923de7bf7371815c8aed-1662484113443/deskshare/deskshare.webm with the fix from #15702 manually applied on the test server. If you clear your browser cache and reload, you'll see that the correct portion of the screenshare video is now showing.

**Comment by sonerd** [comment]
@kepstin, @mokazemi is the mentioned fix only for the building process of the recording or would it also fix the audio/video delay problem during the video conference? Since 2.5.5. we are facing delay problems during video conferences. Video is behind audio.

**Comment by mabras** [comment]
> @kepstin, @mokazemi is the mentioned fix only for the building process of the recording or would it also fix the audio/video delay problem during the video conference? Since 2.5.5. we are facing delay problems during video conferences. Video is behind audio.

only for the building process of the recording

**Comment by mokazemi** [comment]
> @kepstin, @mokazemi is the mentioned fix only for the building process of the recording or would it also fix the audio/video delay problem during the video conference? Since 2.5.5. we are facing delay problems during video conferences. Video is behind audio.

If I'm not mistaken, BBB deletes raw files of the recordings after 14 days, but for recordings in the last two weeks, you can rebuilt them again after applying the fix. 
I don't have any ideas for recordings older than that (Maybe repairing by a video editing software to sync with audio)

**Comment by sonerd** [comment]
> > @kepstin, @mokazemi is the mentioned fix only for the building process of the recording or would it also fix the audio/video delay problem during the video conference? Since 2.5.5. we are facing delay problems during video conferences. Video is behind audio.
> 
> If I'm not mistaken, BBB deletes raw files of the recordings after 14 days, but for recordings in the last two weeks, you can rebuilt them again after applying the fix. I don't have any ideas for recordings older than that (Maybe repairing by a video editing software to sync with audio)

yes rebuilt would work for recordings. The other problem we have is during video conferences. After one time the video and audio of a user is getting out of sync. There is a issue reported also here: https://github.com/bigbluebutton/bigbluebutton/issues/15172
My hope was, that the above fix would be also the solution for the delay issue during meetings.

**Comment by mokazemi** [comment]
> > > @kepstin, @mokazemi is the mentioned fix only for the building process of the recording or would it also fix the audio/video delay problem during the video conference? Since 2.5.5. we are facing delay problems during video conferences. Video is behind audio.
> > 
> > 
> > If I'm not mistaken, BBB deletes raw files of the recordings after 14 days, but for recordings in the last two weeks, you can rebuilt them again after applying the fix. I don't have any ideas for recordings older than that (Maybe repairing by a video editing software to sync with audio)
> 
> yes rebuilt would work for recordings. The other problem we have is during video conferences. After one time the video and audio of a user is getting out of sync. There is a issue reported also here: #15172 My hope was, that the above fix would be also the solution for the delay issue during meetings.

We also had that problem but it didn't happen again after: 
- syncing the server time (Based on what discussed in #8815)
- Setting [these values](https://github.com/bigbluebutton/bigbluebutton/pull/14893/commits/145307d4dbf62e557a9b65e911d4e94adb69e19e) to `60:120:20` instead of `120` (based ot a suggestion discussed in #15172 But I don't know how it's effective)

**Comment by ffdixon** [comment]
@mokazemi Would you be able to do some more testing on your end to see if the audio is out of sync before you make either of those two changes (server time or `60:120:20`, then make one of the changes, and test again.   

We would be very interested if you can do a specific before/after comparison of making only those these changes.
