### ISSUE TITLE
space in tldraw causes error

### ISSUE THREAD

**Issue by ali-alhaidary** [bigbluebutton/bigbluebutton#15654]
**Describe the bug**
when writing text in tldraw, pressing the space bar causes an error as per the attached screen shot.

**To Reproduce**
1. Go to a session (in RTL or LTR)
2. Click on the text icon of the WB (tldraw)
3. press on space bar.

**Expected behavior**
writing a text of space

**Actual behavior**
generates an error

**Screenshots**
![Screenshot 2022-09-07 at 00-20-31 BigBlueButton - Home Room - العرض الافتراضي للعرض](https://user-images.githubusercontent.com/75235623/188743268-aec709ba-34f0-4a63-9f28-1530e0c22367.png)

**BBB version:**
Client build: 114
BigBlueButton version: 2.6.0-alpha.3

**Additional context**
I did reproduce it twice, once in RTL and another in LTR, however, could not reproduce it third time...

**Comment by antobinary** [comment]
Thank you for reporting this @ali-alhaidary !!

**Comment by germanocaumo** [comment]
Will be fixed by #15636
