### ISSUE TITLE
Error 1006 when :: or :,:, in participant name

### ISSUE THREAD

**Issue by mahmoudalsaman** [bigbluebutton/bigbluebutton#15677]
**Describe the bug**
Users joining a conference, being able to choose their name, came probably to the idea to express their mood by an ASCII-emoji. So instead of Paul, they used **Mahmoud ::**  After joining a conference the echo test fails with error 1006,
names like : 

1. **Mahmoud ::**
2. **Mahmoud :/**
3. **Mahmoud :,:,**

Not working with fails error 1006

**To Reproduce**
1. Join meeting with any name like Mahmoud :: ... etc 
2. Click on Join audio confrance 
3. See error 1006

**Expected behavior**
Join audio conference without error 
**Actual behavior**
Error 1006

**BBB version:**
BigBlueButton Server 2.5.5 

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser Chrome

**Comment by ffdixon** [comment]
Good catch.
