### ISSUE TITLE
Cannot destructure property "ParentId" as 'l' is undefined

### ISSUE THREAD

**Issue by zhem0004** [bigbluebutton/bigbluebutton#15671]
**Describe the bug**
When you draw pencil annotation and scroll up and down using mouse wheel it causes error

**To Reproduce**
1. Choose pencil annotation
2. Start drawing
3. Scroll mouse wheel up and down till it throws error: `Cannot destructure property "ParentId" as 'l' is undefined`

**Expected behavior**
It would just keep annotating 

**Actual behavior**
It throws an error as annotation or instead of whiteboard

**Screenshots**

![Screenshot from 2022-09-09 11-12-38](https://user-images.githubusercontent.com/80958763/189387657-70a626f3-e9c1-4ea6-abc1-efe46c8a7b57.png)

Message pictures

**BBB version:**
2.6

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Chromium, Chrome(takes more time to occur), Firefox(same as Chrome)
 - Version 22

**Comment by zhem0004** [comment]
Another way to get this error: "Start drawing with pencil, right-click on any app in favourites, then click on whiteboard. It causes whiteboard to permanently read annotation without need to hold the mouse. then you click on manage presentation and upload a new presentation."

**Comment by germanocaumo** [comment]
Can be fixed by #15636
