### ISSUE TITLE
Poll answers in wrong language

### ISSUE THREAD

**Issue by IwisGiwis** [bigbluebutton/bigbluebutton#15686]
**Describe the bug**
I found this bug with the application language in German. I do not know if this behaviour occurs in other languages. If you open a poll with Response Type 'Yes/No/Abstention' ('Ja/Nein/Enthaltung' in German) and a user answers with at least 2 answers (Yes and No, Yes and Abstention or No and Abstention) the answers are shown in English and not in german.

**To Reproduce**
1. Click on 'Start a poll'
2. Click on 'Yes/No/Abstention' under Response Types
3. Click on 'Allow multiple answers per respondent'
4. DON'T add an item
5. Click on 'Start Poll'
6. User answers poll with at least 2 answers (Yes and No, Yes and Abstention or No and Abstention)

**Expected behavior**
Under Users Respone you should see the answers in German ('Ja' and 'Nein', 'Ja' and 'Enthaltung' or 'Nein' and 'Enthaltung)

**Actual behavior**
Under Users Response you see the answers in English (Yes and No, Yes and Abstention or No and Abstention)

**Screenshots**
Creating the poll
<br /> <br /> <br />
![grafik](https://user-images.githubusercontent.com/74247647/190103105-fc030603-7ed2-40c3-8646-aaf22a8fe089.png)
<br /> <br /> <br />
The answers of the poll
<br /> <br /> <br />
![grafik](https://user-images.githubusercontent.com/74247647/190103247-95a042b5-d343-4df2-83e1-d799cc234a2c.png)
<br /> <br /> <br />

**BBB version:**
I tested it on your test server: https://test26.bigbluebutton.org/b/ste-sm5-9om-yk4 and on our test server which has version 2.5

**Desktop (please complete the following information):**
 - OS: Windows 10 Enterprise
 - Browser: Firefox and Edge
 - Version: Firefox 91.13.0esr and Edge 105.0.1343.33

**Comment by hex-m** [comment]
I tested it on a BigBlueButton 2.5.6 server and it seems fixed. If you can confirm that @IwisGiwis you could close this issue.

**Comment by IwisGiwis** [comment]
Thanks, it works fine now!
