### ISSUE TITLE
ice error 1007

### ISSUE THREAD

**Issue by AleksandrMikoshi** [bigbluebutton/bigbluebutton#15693]
Hello.

I have not yet been accepted into the "BigBlueButton Setup" group, but there is a problem, so I am writing here.

I have 3 BBB servers deployed, one GL and one SL.
Everyone has an external IP address, all DNS records (both inside the domain and in the outside world) are correct.
When connected to a VPN (or being physically in the corporate network loop), the connection to the conference works properly, but if you disable the VPN, an "ice error 1007" error occurs when connecting.

We don’t use NAT, from the ufw side all ports are open:

`$ sudo ufw status`
status: active

To Action From

OpenSSH ALLOW Anywhere
Nginx Full ALLOW Anywhere
16384:32768/udp ALLOW Anywhere
OpenSSH (v6) ALLOW Anywhere (v6)
Nginx Full (v6) ALLOW Anywhere (v6)
16384:32768/udp (v6) ALLOW Anywhere (v6)

BBB installed with a script
`wget -qO- https://ubuntu.bigbluebutton.org/bbb-install.sh | bash -s -- -v bionic-240 -s {{ site_name }} -a -w`

I did not set up/do not use TURN/COTURN servers on my own.

With `$ sudo bbb-conf --check`
/usr/share/bbb-web/WEB-INF/classes/spring/turn-stun-servers.xml (STUN Server)
                               stun: stun.l.google.com:19302

Potential problems described below
Warning: Failed to verify STUN server at stun.l.google.com 19302 with command

stunclient --mode full --localport 30000 stun.l.google.com 19302

**Comment by EBG-DEV** [comment]
I concur.

Ubuntu 20.04.5 LTS
BBB version 2.5.5
Greenlight 2.13.0

Internal network no problem.

External -> NAT -> LAN

ice error 1007
