### ISSUE TITLE
Pause Recording is not working for webcams

### ISSUE THREAD

**Issue by abonadt** [bigbluebutton/bigbluebutton#15697]
**Describe the bug**
Pause recording of a session while running a camera 

**To Reproduce**
1. Open a new room with Mic and Camera
2. Click on 'Start Recording'
3. After a few seconds click on "Pause recording" 
4. After a few seconds click on "Proceed recording"
5. Do step 3 and 4 again
6. Close the conference session
7. See presentation recording. Audio and whiteboard start and stop according to the recording pauses. Webcam is only correct in first recording part. After this a few seconds of webcam recording during pause is shown an then webcam stops.

**Expected behavior**
Webcam recording in sync with all other parts (whiteboard, audio) an cutted correctly

**Actual behavior**
Webcam recording not working and show some parts not intended to show while pausing

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome and Safari

Tested with BBB 2.55 and 2.6a3 fresh install with recommended settings. Stopping the webcam before proceed with recording and restart webcam after pausing everything works as expected.

**Comment by ffdixon** [comment]
@kepstin I wonder if this is related to https://github.com/bigbluebutton/bigbluebutton/pull/15702 ?

**Comment by abonadt** [comment]
> I wonder if this is related to https://github.com/bigbluebutton/bigbluebutton/pull/15702 ?

I don't think so. Audio and video are in sync in regular non-stop-sessions. Problem **only occures** when recording is paused during a session.

**Comment by kepstin** [comment]
This will be fixed by #15702, yes. One of the main things that pr fixes is selecting the correct start time for a video when recording was started *after* the video share (webcam, deskshare) was started.

**Comment by abonadt** [comment]
> This will be fixed by https://github.com/bigbluebutton/bigbluebutton/pull/15702, yes.

This fixed the issue. Thanks.
