### ISSUE TITLE
Upgrade 2.5 to 2.6 default presentation does not load

### ISSUE THREAD

**Issue by markginter31** [bigbluebutton/bigbluebutton#15706]
Did an update from 2.5 to 2.6 using the bbb install script.  When starting a session everything works except the main "presentation"/whiteboard does not load.  If I upload a pdf/image then it appears after the conversion.  Nothing but a dark blue background initially.  In fact - there is no "default" presenation in the "manage presentations" option list.

**Comment by SECtim** [comment]
I have the same issue, we have a custom default presentation -- we set `beans.presentationService.defaultUploadedPresentation` to `${bigbluebutton.web.serverURL}/default-blank.pdf` in `$BBB_WEB_CONFIG`), the respective PDF file is present in `/var/www/bigbluebutton-default/`.

In the nginx logs, I observe the following, every time a room is opened:
```
<own IP> - - [05/Apr/2023:08:20:43 +0000] "GET /default-blank.pdf HTTP/1.1" 406 0 "-" "Mozilla"
```

Not sure whether this is related, though.

**Comment by hostbbb** [comment]
The issue is 2.6 is looking in assets directory

cp default.pdf /var/www/bigbluebutton-default/assets/default.pdf

**Comment by SECtim** [comment]
Thanks @hostbbb, worked for me.

**Comment by antobinary** [comment]
The `assets/` portion is now documented in the 2.6 changes, see #17485 Thanks for reporting this!

**Comment by frahman80** [comment]
> The issue is 2.6 is looking in assets directory
> 
> cp default.pdf /var/www/bigbluebutton-default/assets/default.pdf

This is not working for me. bbb-2.6.9
