### ISSUE TITLE
Audio modal reappears after breakout rooms end

### ISSUE THREAD

**Issue by antonbsa** [bigbluebutton/bigbluebutton#15716]
**Describe the bug**
The audio modal reopens every time the breakout rooms are ended (if the user is not connected with audio).
_P.S.: The sidebar content (public/private chat, shared notes, etc) is also closing after ending them_ 

**To Reproduce**
1. Join the meeting with 2 users;
2. Connect audio only with one of the users;
3. Create breakout rooms and end them;
4. Check the audio modal reappearing to the user not connected with audio;

**Video**

https://user-images.githubusercontent.com/56703993/191342897-7e5dbe1c-0ec3-431a-a362-8b0ec3acccfa.mp4

**Comment by antobinary** [comment]
Closed via https://github.com/bigbluebutton/bigbluebutton/pull/16868
