### ISSUE TITLE
Wrong focus change on the whiteboard when a chat message is sent

### ISSUE THREAD

**Issue by antonbsa** [bigbluebutton/bigbluebutton#15715]
**Describe the bug**

1 -> When user A is typing on the whiteboard and user B sends a message in the chat, user A loses the focus on whiteboard typing:

https://user-images.githubusercontent.com/56703993/191334782-38a96f77-c937-47d0-b4d0-43e8e294f532.mp4

2 -> When the user sends a message in the chat after typing something on the whiteboard, the focus will get back to the whiteboard text:

https://user-images.githubusercontent.com/56703993/191334852-d057d882-f362-4bf0-af42-cc981b616c81.mp4

**Comment by antobinary** [comment]
@KDSBrowne says he was not able to reproduce on the latest BBB 2.6. @antonbsa could you please reopen if you're able to reproduce it in this (or different) way?
