### ISSUE TITLE
Breakout rooms don't save room assigning

### ISSUE THREAD

**Issue by FerBak** [bigbluebutton/bigbluebutton#15719]
**Describe the bug**
When creating breakout rooms in a single session, only room names and amount of rooms are saved. Participants have to be assigned to rooms manually every time. 

**To Reproduce**
1. Create breakout rooms as normal and assign participants
2. End breakout room session
3. Create new round of breakout rooms
4. Every student is not assigned to room

**Expected behavior**
Update notes BBB 2.5: "Breakout rooms now remember your previous rooms assignments within the current session. This means if you assign students to breakout rooms and then, later in the class want to reuse the breakout rooms, you don’t need to re-assign students."

**Actual behavior**
Assignment is not saved. Only amount and names of rooms.

**BBB version:**
BigBlueButton continually evolves. Providing the version/build helps us to pinpoint when an issue was introduced.

BigBlueButton Server 2.5.5
Issue also happens on 2.6 test servers 

**Desktop (please complete the following information):**
 - OS: [multiple (MacOS Big Sur, Windows 10)]
 - Browser [multiple: Chrome, Safari, Edge, Firefox]

**Comment by antobinary** [comment]
I am able to reproduce this on BBB 2.6.0-beta.3. I believe** it is a regression from one of the pre-release versions of BBB 2.5 where @gustavotrott had implemented this. I am not finding the exact pull request though.

I am marking it as accepted and as a defect. Thanks for reporting this @FerBak
