### ISSUE TITLE
Request at least one user assigned to a breakout room only when there's an attendee

### ISSUE THREAD

**Issue by antonbsa** [bigbluebutton/bigbluebutton#15757]
**Is your feature request related to a problem? Please describe.**
When there're only moderators in the meeting and you click to create breakout rooms, you'll still be required to assign at least one user to be able to create them - and it has no effect because moderators can choose any room to join.

**Describe the solution you'd like**
Request at least one user assigned only when there's a normal user (attendee).

**Video**

https://user-images.githubusercontent.com/56703993/193123758-a3edf783-904b-49ba-9b18-d1e0e14872da.mp4

**Comment by ffdixon** [comment]
HI @antonbsa, do you think this is still an issue in 2.7.x with the ability to add moderators to breakout rooms?
