### ISSUE TITLE
"Create breakout rooms" button is being hidden and shown wrongly

### ISSUE THREAD

**Issue by antonbsa** [bigbluebutton/bigbluebutton#15756]
**Describe the bug**
After creating the breakout rooms, the `Create breakout room` button should not be displayed - the same way as it should reappears after its ending, but it's just getting a different state after clicking the user list toggle button.

**To Reproduce**
1. Join the meeting;
2. Manage users > Create breakout rooms;
3. Confirm the modal;
4. See that the button is still in the manage users' items;
5. Toggle user list;
6. See that now the button isn't there;
7. End the rooms;
8. See that there's no button to create the rooms
9. If you don't toggle the user list, you won't be able to create new rooms;

**Video**

https://user-images.githubusercontent.com/56703993/193120979-6101030d-6aef-48bc-bf02-8d09302a1ac6.mp4

**Comment by antobinary** [comment]
Somewhat related to #16118
