### ISSUE TITLE
[2.5.6] Layout bug with "Smart layout" in Breakout Rooms.

### ISSUE THREAD

**Issue by einhirn** [bigbluebutton/bigbluebutton#15775]
**Describe the bug**
When using "Smart layout" as default and entering a breakout room, the webcams overlap with the presentation area.

**To Reproduce**
1. Open session with "Smart layout" as default setting
2. Create and join breakout room
3. Share webcam, Activate presentation

**Expected behavior**
The webcam images should be positioned as usual.

**Actual behavior**
The webcam images are positioned a bit lower than usual, overlapping the presentation area.

**Screenshots**
![Screenshot 2022-09-27 170455](https://user-images.githubusercontent.com/189249/193784592-9295d033-a8c7-4389-b4c1-0c4d476ec514.png)

**BBB version:**
BigBlueButton Server 2.5.6 (3115)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Chrome 105.0.5195.127 

**Additional context**
If it can't be reproduced immediately: We're using "autoSwapLayout" and "restoreOnUpdate" options...

**Comment by ffdixon** [comment]
Good catch.
