### ISSUE TITLE
Nginx configuration has client expiring every 1 min.

### ISSUE THREAD

**Issue by bigbluebutton-issue-import** [bigbluebutton/bigbluebutton#1577]
Originally reported on Google Code with ID 822

```
/etc/nginx/sites-available/bigbluebutton has BigBlueButton client expiring every 1 minute.
This is to deal with the localization caching problem, but it is not the best solution,
as you do want the browser to cache the client, since it is quite large (1mb). A better
solution needs to be found.
```

Reported by `Me.Snap` on 2011-01-20 17:42:09

**Comment by ffdixon** [comment]
We no longer use the expiry for cache in nginx.  Instead, the BigBlueButton client loads components using the build number in the URL, so the built-in browser cache is in play until the client updates.
