### ISSUE TITLE
Jitter buffer incorrectly set in 2.5.6 (will be updated in 2.5.7)

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#15776]
**Describe the bug**
The current setting for jitterbuffer in 2.5.6 in is incorrect.  These are set in `/opt/freeswitch/etc/freeswitch/dialplan/default/bbb_conference.xml` and `/opt/freeswitch/etc/freeswitch/dialplan/default/bbb_echo_to_conference.xml` as "120".

However, providing a single parameter doesn't provide an upper-bound to the jitterbuffer, so it can lead to 1-5 seconds of drift in the audio.

**To Reproduce**
The jitterbuffer kicks in when there are dropped packets.  While we don't have steps to deterministically reproduce, we know the settings are currently incorrect based on reports in the forum and reading the source code in FreeSWITCH.   

**Expected behavior**
The audio and video should stay closely aligned (it won't be perfect as there are two different streams, but it shouldn't have a 5 second drift).

**Actual behavior**
There are times where the audio can drift up to 5 seconds.

**Screenshots**

**Additional context**
We have applied a fix this in 2.6-dev, see

  https://github.com/bigbluebutton/bigbluebutton/pull/15766/files

and will be back porting it to the upcoming 2.5.7.  Any administrator of 2.5.6 can apply the above settings, restart BigBlueButton, and see an improvement in audio.

See also

  https://groups.google.com/g/bigbluebutton-setup/c/SvWoiQOB4tk/m/1Htqb9olBgAJ
  https://groups.google.com/g/bigbluebutton-setup/c/OJwurn8hfhM/m/wwoDSlAuBQAJ

**Comment by mwuttke** [comment]
@ffdixon: The applied fix for 2.6-dev that you mentioned will make it into 2.5.7? So far I have not been able to find it in the list of changes.

**Comment by ffdixon** [comment]
Yes, this will be in 2.5.7 (coming soon).
