### ISSUE TITLE
Parameter guest used on join only work with quoted values

### ISSUE THREAD

**Issue by jfederico** [bigbluebutton/bigbluebutton#15785]
**Describe the bug**
While working on the Moodle integration, we spotted an issue with the API.

According to the documentation API https://docs.bigbluebutton.org/dev/api.html#join.

Basically if join includes the parameter guest=true (as in a boolean), it will allow the guest user in without asking for moderator (even if the meeting was started with ASK_MODERATOR)

But if you join it with guest="true" (as in a string), then all works as expected.

**Expected behavior**
The behavoiur should the the expected either if the parameter is set as `guest=true` or `guest="true"`

**Comment by ffdixon** [comment]
good catch!

**Comment by jfederico** [comment]
Sorry guys, It is a false positive. The 3rd party implementation was not done right

**Comment by ffdixon** [comment]
No worries!
