### ISSUE TITLE
java.net.ConnectException: Connection refused after installation

### ISSUE THREAD

**Issue by tom23412** [bigbluebutton/bigbluebutton#15781]
Hello,

I have a problem to setup Bigbluebutton juste after installation script :

`wget -qO- https://ubuntu.bigbluebutton.org/bbb-install-2.5.sh | bash -s -- -v focal-250 -s bbb.test -e test@***.fr -w -g`

- bbb-conf --status :
All are OK

- bbb-conf --check :
`curl: (6) Could not resolve host: bbb.test`

- bbb-conf --debug :
`-- Errors found in /var/log/syslog -- 
Oct  4 13:58:52 bbb-test bbb-apps-akka[15395]: Exception in thread "main" io.lettuce.core.RedisConnectionException: Unable to connect to 127.0.0.1:6379
Oct  4 13:58:52 bbb-test bbb-apps-akka[15395]: #011at io.lettuce.core.RedisConnectionException.create(RedisConnectionException.java:78)
Oct  4 13:58:52 bbb-test bbb-apps-akka[15395]: #011at io.lettuce.core.RedisConnectionException.create(RedisConnectionException.java:56)
Oct  4 13:58:52 bbb-test bbb-apps-akka[15395]: Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: /127.0.0.1:6379
Oct  4 13:58:52 bbb-test bbb-apps-akka[15395]: Caused by: java.net.ConnectException: Connection refused
Oct  4 13:59:00 bbb-test bbb-fsesl-akka[16578]: 13:59:00,862 |-ERROR in ch.qos.logback.core.rolling.RollingFileAppender[FILE] - openFile(logs/bbb-fsesl-akka.log,true) call failed. java.io.FileNotFoundException: logs/bbb-fsesl-akka.log (Permission denied)
Oct  4 13:59:00 bbb-test bbb-fsesl-akka[16578]: #011at java.io.FileNotFoundException: logs/bbb-fsesl-akka.log (Permission denied)
Oct  4 13:59:06 bbb-test bbb-fsesl-akka[16578]: java.net.ConnectException: Connection refused
Oct  5 11:09:39 bbb-test bundle[37527]: SignalException: SIGTERM
Oct  5 11:09:40 bbb-test bundle[37685]: Original Exception (Redis::CannotConnectError): Error connecting to Redis on 127.0.0.1:6379 (Errno::ECONNREFUSED)
Oct  5 11:09:40 bbb-test bundle[37685]: /usr/local/bigbluebutton/core/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/application.rb:186:in 'standard_exception_handling'
Oct  5 11:16:08 bbb-test bundle[51699]: SignalException: SIGTERM
`

All requirements are OK (hardware, ubuntu 20.04, update, upgrade etc)

Thanks

**Comment by tom23412** [comment]
Any ideas :( ?

**Comment by dqcuong93** [comment]
I'm having trouble with this issue too :(

**Comment by antobinary** [comment]
"Connection refused: /127.0.0.1:6379" means Redis is not running.

Please post setup/installation related questions to https://groups.google.com/g/bigbluebutton-setup - it's a much better place to do it. If there's a bug with BigBlueButton, we will open an issue here and track it to completion.
