### ISSUE TITLE
BBB 2.5.6: websocket Problem with IPv6 only clients - solveable by manual change in sip.nginx

### ISSUE THREAD

**Issue by mifritscher** [bigbluebutton/bigbluebutton#15797]
I got 1007 (direct) or 1004 errors (forcing relay via media.peerconection.ice.relay_only) on a IPv6 only client connection.

I found following error message in the nginx error.log:
```
2022/10/09 01:00:03 [error] 14631#14631: *6 connect() failed (111: Connection refused) while connecting to upstream, client: <client IPv6>, server: bbb.example.de, request: "GET /html5client/join?sessionToken=9fyblabalba HTTP/2.0", upstream: "http://127.0.0.1:4107/html5client/join?sessionToken=9fyd8wacmzlwlsbq", host: "bbb.example.de", referrer: "https://bbb.example.de/b/mic-abc-123"
```

What helped:
/usr/share/bigbluebutton/nginx/sip.nginx - exchanged the IPv4 with the hostname

**Comment by n8falke** [comment]
I'm using the approach from https://docs.bigbluebutton.org/support/troubleshooting.html#configure-bigbluebuttonfreeswitch-to-support-ipv6 with `/etc/nginx/conf.d/bigbluebutton_sip_addr_map.conf` changed to `/usr/share/bigbluebutton/nginx/sip.nginx`.
Might be for 2.5.x it is not the correct way.
For video streams https://docs.bigbluebutton.org/admin/configure-firewall.html#updating-mediasoup might be interesting as well. There I use the ipv6 before ipv4 (which has an effect) and place ipv6 into `""`.

**Comment by ArminXG** [comment]
After moving to 2.6.1, full IPv6 does not work any more for me. 
No matter where I add the v6 address in /etc/bigbluebutton/bbb-webrtc-sfu/production.yml, video and screensharing still switches to IPv4 (everything else is IPv6 working).

Also, the documentation says I should set 
`proxy_pass https://$freeswitch_addr:7443`
in /usr/share/bigbluebutton/nginx/sip.nginx, but it doesn't work. I need to set
`proxy_pass http://$freeswitch_addr:5066`

The system is not behind firewall and uses public v4 and v6 address.

**Comment by ffdixon** [comment]
Can you do a test against https://test.bigbluebutton.org/ and let us know if you encounter the same issue.

**Comment by ArminXG** [comment]
How do you expect me to test the ipv6 issue with test.bigbluebutton.org? That system seems to be IPv4 only:
```
$ host test.bigbluebutton.org
test.bigbluebutton.org is an alias for test25.bigbluebutton.org.
test25.bigbluebutton.org has address 159.89.120.231
```
