### ISSUE TITLE
Making it easier to switch between participation modes

### ISSUE THREAD

**Issue by davidsiecke** [bigbluebutton/bigbluebutton#15799]
**Is your feature request related to a problem? Please describe.**
In order to change one’s mode of participation, currently one has to first click the “Leave audio” button, then “Join audio”, and finally select either “Microphone” or “Listen only”. In a usability test we conducted at Osnabrück University, we found that to the majority of participants (students, mostly experienced with BBB), having to click “Leave audio” in order to switch participation modes was not intuitive. Additionally, in our experience, it is not rare to switch one’s mode of participation during a lecture or seminar meeting, while intending to leave all audio channels is.
Thus, a functionality that is needed more often (switching participation modes) is hidden behind a functionality (leaving all audio channels) which a) is needed less often and b) users do not seem to associate with switching participation modes.

**Describe the solution you'd like**
Building on the redesign of the audio device selection menu (see [PR #15154](https://github.com/bigbluebutton/bigbluebutton/pull/15154)) which is set to be adopted in BBB 2.6, the problem could be solved by adding a dedicated button for switching to the respectively other mode of participation to the audio device selection menu. This could look as sketched below:
![image](https://user-images.githubusercontent.com/72148199/194826867-b8ba7d06-1d90-46c7-89a5-36aa79339525.png)

**Describe alternatives you've considered**
The “Join" button could also be placed in the “Microphones” heading. Or, the “Microphones" heading could be removed such that only a “Join with microphone” button is shown.
We did not consider alternative placements for the “Listen only” button, as it is functionally similar to the “Leave audio” button which is placed at the very bottom of the audio device selection menu, and placing the “Listen only” button below the microphone options in our opinion nicely mirrors this similarity.
![image](https://user-images.githubusercontent.com/72148199/194826963-6875c009-f698-4d89-a340-dae645d5278f.png)
![image](https://user-images.githubusercontent.com/72148199/194826977-4cd8b55c-8b88-4751-add6-24ed4241f911.png)

**Additional context**
For background information, see the [usability test report](https://doi.org/10.48693/193) (section 3.2.1.2).

**Comment by einhirn** [comment]
I guess I'd like either the "listen only" and "join" buttons to be designed like the "leave audio" button, or, even better, change the "leave audio" to actually look like a "big blue button"...

**Comment by davidsiecke** [comment]
I conducted a survey with 66 users to evaluate this proposal. Towards the end of this comment, there is a short summary of the findings and more detailed information on the survey.

@einhirn: I agree that the buttons for switching one’s participation mode should look similar to the “Leave audio” button, so the concrete redesigns I evaluated are the following.

<img width="400" alt="d2-4" src="https://user-images.githubusercontent.com/72148199/217083389-85aef04f-4429-45f4-a085-61bd51a9f424.png">

As I could not decide for an icon for the “Listen only” button, I evaluated two options for this:

#### Option 1: Microphone icon
<img width="400" alt="d2-3-1" src="https://user-images.githubusercontent.com/72148199/217083466-8d743dc0-5640-4fe6-9916-8279b78e0168.png">

#### Option 2: Headphones icon
<img width="400" alt="d2-3-2" src="https://user-images.githubusercontent.com/72148199/217083656-94a28b06-42a1-40aa-96d2-f088997e1e47.png">

### The microphone icon vs. the headphones icon

44 out of 56 participants (≈ 79 %) preferred the headphones icon.

Commonly cited reasons:
- The microphone icon is unsuitable because the x is too small (11 participants). Two participants who preferred the microphone icon also stated that the x should be bigger.
- They associate the headphones symbol more strongly with the “Listen only” mode / the act of listening (6 participants).
- A positive association is better than a negative one (2 participants).

Commonly cited reasons among participants who preferred the microphone icon:
- This button is about the microphone, not the headphones, so it should not show headphones (2 participants).

What I take away from this: 
The microphone icon is certainly not the way to go. I could see the headphones icon working well, but I also agree with the argument that this button is not about the headphones and should thus not show headphones. Red headphones may evoke the association of not being able to hear others anymore.
I don’t find the arguments stated in favor of the headphones symbol (‘strong association to “Listen only” mode’, ‘a positive association is better than a negative one’) very compelling. I think a ‘negative’ symbol fits a button for disconnecting something (a ‘negative’ action) well – perhaps better than a ‘positive’ symbol which is more about the consequence of the action (entering “Listen only” mode) than the action itself (disconnecting one’s microphone). So a plain red X might be a better icon.

### Redesign vs. current design

Participants were then asked to consider both the proposed “Join with microphone” button and the version of the “Listen only” button they prefer. With these in mind, they should then complete the sentence

> I think that being able to switch one’s participation mode via these two buttons is ______ user-friendly than needing to leave and rejoin the audio.

by choosing one of the options
- “much less”,
- “less”,
- “neither more nor less”,
- “more”,
- “much more”.

Out of 66 participants, 62 (≈ 94 %) chose “more” or “much more”. Here is a plot of response counts:

<img width="400" alt="plot" src="https://user-images.githubusercontent.com/72148199/217084215-1fdcae77-721e-4e5a-b83b-fcddf9b685dd.png">

### Other comments

Some other things participants commented on this redesign:

- The button for disconnecting one’s microphone should not be labelled “Listen only”, but “Deactivate microphone” or the like. (1 participant)

I would say that using “Disconnect” instead of “Deactivate” would help to differentiate this action from muting oneself. But altogether I think “Listen only” would be the most user-friendly option for labelling this button, as it is shorter and gives also less tech-savvy users a clear idea about the consequences.

- “Please consider also adding microphone symbols in front of the entries of the Microphones section and the same for the Speakers section. This would make it easier for the user to see what they are selecting without having to read. Especially if the audio device names are as confusing as in the screenshot.”

I think this is a good point. Adding microphone / headphones icons helps to understand what kind of device each list item is without having to look for the list title. I think this would make the dialog less demanding and easier to understand at a glance.

- The arrow button for opening this menu is very small and not self-explanatory.

I agree that it could be bigger. But perhaps then it would also have to move to the side of the mute / unmute button.

### Summary

62 out of 66 participants (≈ 94 %) stated that the proposed redesign is “more” or “much more” user-friendly than the current design. 44 out of 56 participants (≈ 79 %) preferred a headphones icon for the “Listen only” button over a microphone icon with a small cross, but perhaps just a plain cross would be a better symbol, because
- red headphones may evoke the association of not being able to hear others anymore.
- if the name of the button (“Listen only”) already is more about the consequence of the action than about the action itself, then perhaps at least the icon of the button should be about the action itself.

### About the survey

This survey was conducted with 124 people, mostly students, who had used BBB at least once. About 99 % of participants had been using BBB for more than three months, about 84 % for more than one year. They were allocated randomly to one of two questionnaires, such that 66 users answered questionnaire 1 and 58 users answered questionnaire 2. The data collected in the survey as well as all pages of both questionnaires can be found here:
https://sync.academiccloud.de/index.php/s/w2cWlDCrW4jOpCY
