### ISSUE TITLE
BBB-2.5 having an issue when trying to connect, getting the error connection failure ice error 1007 

### ISSUE THREAD

**Issue by ta123q** [bigbluebutton/bigbluebutton#15798]
form inside it work, but outside is not able to connect all ports are allowed and tested using netcat.
this is the about:webrtc
<html><body>
<div><span class="info-label" data-l10n-id="about-webrtc-peerconnection-id-label">PeerConnection ID:</span><span class="info-body">{fd759b9d-f199-4a58-ad74-30032743fa0b} 1665309927841000 (id=8589934610 url=https://bbb.xyz/html5client/join?sessionTok</span></div><div class="peer-connection-config">RTCConfiguration<br>bundlePolicy: balanced<br>iceTransportPolicy: all<br>peerIdentity(<i data-l10n-id="about-webrtc-configuration-element-provided">Provided</i>/<i data-l10n-id="about-webrtc-configuration-element-not-provided">Not Provided</i>): <i data-l10n-id="about-webrtc-configuration-element-not-provided">Not Provided</i><br>sdpSemantics: <i data-l10n-id="about-webrtc-configuration-element-not-provided">Not Provided</i><br>iceServers: <div>urls: ["stun:turn.xyz"]<br>credential(<i data-l10n-id="about-webrtc-configuration-element-provided">Provided</i>/<i data-l10n-id="about-webrtc-configuration-element-not-provided">Not Provided</i>): <i data-l10n-id="about-webrtc-configuration-element-not-provided">Not Provided</i><br>userName(<i data-l10n-id="about-webrtc-configuration-element-provided">Provided</i>/<i data-l10n-id="about-webrtc-configuration-element-not-provided">Not Provided</i>): <i data-l10n-id="about-webrtc-configuration-element-not-provided">Not Provided</i></div><div>urls: ["turn:turn.xyz.:443?transport=tcp"]<br>credential(<i data-l10n-id="about-webrtc-configuration-element-provided">Provided</i>/<i data-l10n-id="about-webrtc-configuration-element-not-provided">Not Provided</i>): <i data-l10n-id="about-webrtc-configuration-element-provided">Provided</i><br>userName(<i data-l10n-id="about-webrtc-configuration-element-provided">Provided</i>/<i data-l10n-id="about-webrtc-configuration-element-not-provided">Not Provided</i>): <i data-l10n-id="about-webrtc-configuration-element-provided">Provided</i></div><div>urls: ["turns:turn.xyz:443?transport=tcp"]<br>credential(<i data-l10n-id="about-webrtc-configuration-element-provided">Provided</i>/<i data-l10n-id="about-webrtc-configuration-element-not-provided">Not Provided</i>): <i data-l10n-id="about-webrtc-configuration-element-provided">Provided</i><br>userName(<i data-l10n-id="about-webrtc-configuration-element-provided">Provided</i>/<i data-l10n-id="about-webrtc-configuration-element-not-provided">Not Provided</i>): <i data-l10n-id="about-webrtc-configuration-element-provided">Provided</i></div></div><div id="ice-stats: {fd759b9d-f199-4a58-ad74-30032743fa0b} 1665309927841000 (id=8589934610 url=https://bbb.xyz/html5client/join?sessionTok"><h4 data-l10n-id="about-webrtc-ice-stats-heading">ICE Stats</h4>

ICE State | Nominated | Selected | Local Candidate | Remote Candidate | Component ID | Priority | Bytes sent: | Bytes received:
-- | -- | -- | -- | -- | -- | -- | -- | --
inprogress | false | false | 192.168.41.22:62758/udp(host) [non-proxied] | 10.10.30.14:17344/udp(host) | 1 | 9115005270299247000 | 0 | 0
inprogress | false | false | 192.168.41.22:62758/udp(host) [non-proxied] | 10.10.30.14:17344/udp(host) | 1 | 9115005270299247000 | 0 | 0

<div><span class="info-label" data-l10n-id="about-webrtc-ice-restart-count-label">ICE restarts:</span><span class="info-body">0</span></div><div><span class="info-label" data-l10n-id="about-webrtc-ice-rollback-count-label">ICE rollbacks:</span><span class="info-body">0</span></div><div><h4 data-l10n-id="about-webrtc-raw-candidates-heading">All Raw Candidates</h4><div class="section-ctrl no-print"><div class="fold-trigger about-webrtc-raw-cand-show-msg about-webrtc-raw-cand-hide-msg" data-l10n-id="about-webrtc-raw-cand-show-msg" title="click to expand this section">show raw candidates</div></div></div></div><div><h4 data-l10n-id="about-webrtc-sdp-heading">SDP</h4><h5 data-l10n-id="about-webrtc-local-sdp-heading-offer">Local SDP (Offer)</h5><pre>v=0
o=mozilla...THIS_IS_SDPARTA-99.0 1814080469144449510 0 IN IP4 0.0.0.0
s=-
t=0 0
a=sendrecv
a=fingerprint:sha-256 6E:D4:D4:05:44:49:CC:85:02:20:8C:A7:37:88:7C:8E:FB:A3:7A:C6:CC:3C:95:51:DC:9B:26:9A:D3:7C:9D:7E
a=group:BUNDLE 0
a=ice-options:trickle
a=msid-semantic:WMS *
m=audio 62758 UDP/TLS/RTP/SAVPF 109 9 0 8 101
c=IN IP4 192.168.41.22
a=candidate:0 1 UDP 2122252543 192.168.41.22 62758 typ host
a=candidate:2 1 TCP 2105524479 192.168.41.22 9 typ host tcptype active
a=candidate:0 2 UDP 2122252542 192.168.41.22 62759 typ host
a=candidate:2 2 TCP 2105524478 192.168.41.22 9 typ host tcptype active
a=sendrecv
a=end-of-candidates
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=extmap:2/recvonly urn:ietf:params:rtp-hdrext:csrc-audio-level
a=extmap:3 urn:ietf:params:rtp-hdrext:sdes:mid
a=fmtp:109 maxplaybackrate=48000;stereo=1;useinbandfec=1
a=fmtp:101 0-15
a=ice-pwd:b17cc62a9675efa5aafc1a78abb420e9
a=ice-ufrag:4dccfa5a
a=mid:0
a=msid:{9065cbfe-d25b-4494-93cd-06cae7dd6da1} {47181e0b-53cd-4b7d-a6d6-60efbb65ef5d}
a=rtcp:62759 IN IP4 192.168.41.22
a=rtcp-mux
a=rtpmap:109 opus/48000/2
a=rtpmap:9 G722/8000/1
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:101 telephone-event/8000
a=setup:actpass
a=ssrc:3212209675 cname:{9b588e43-1359-4912-9619-56938a59da05}
</pre><h5 data-l10n-id="about-webrtc-remote-sdp-heading-answer">Remote SDP (Answer)</h5><pre>v=0
o=FreeSWITCH 1665292575 1665292576 IN IP4 10.10.30.14
s=-
t=0 0
a=sendrecv
a=msid-semantic:WMS vdwzkifLVZ2sqOIDyyI8Y2pNiLTwxQ6S
m=audio 17344 UDP/TLS/RTP/SAVPF 109 101
c=IN IP4 10.10.30.14
a=candidate:5042833925 1 udp 2130706431 10.10.30.14 17344 typ host generation 0
a=sendrecv
a=end-of-candidates
a=fingerprint:sha-256 AE:6F:72:9F:51:26:93:66:8E:D0:71:D2:2E:61:DF:84:2E:72:7D:2E:5E:84:31:FB:77:46:78:E8:13:23:1E:34
a=fmtp:109 maxplaybackrate=0;stereo=1;useinbandfec=1
a=ice-pwd:8G9zTFMW3if6m3xPoX7CC2YT
a=ice-ufrag:CvzrnP5vrOSOuPxe
a=ptime:20
a=rtcp:17344 IN IP4 10.10.30.14
a=rtcp-mux
a=rtpmap:109 opus/48000/2
a=rtpmap:101 telephone-event/8000
a=setup:active
a=ssrc:1128739303 cname:Uti4BnFncyFtceXB
a=ssrc:1128739303 msid:vdwzkifLVZ2sqOIDyyI8Y2pNiLTwxQ6S a0
a=ssrc:1128739303 mslabel:vdwzkifLVZ2sqOIDyyI8Y2pNiLTwxQ6S
a=ssrc:1128739303 label:vdwzkifLVZ2sqOIDyyI8Y2pNiLTwxQ6Sa0
</pre><h4 data-l10n-id="about-webrtc-sdp-history-heading">SDP History</h4><div><h5 class="sdp-history-link" data-l10n-id="about-webrtc-sdp-set-at-timestamp-local" data-l10n-args="{&quot;timestamp&quot;:1665309930386}">Set Local SDP at timestamp 1665309930386</h5></div><div><h5 class="sdp-history-link" data-l10n-id="about-webrtc-sdp-set-at-timestamp-remote" data-l10n-args="{&quot;timestamp&quot;:1665309935583}">Set Remote SDP at timestamp 1665309935583</h5></div><div class="sdp-history"><div><h4 data-l10n-id="about-webrtc-local-sdp-heading">Local SDP</h4><h5 id="sdp-history: 1665309930386" data-l10n-id="about-webrtc-sdp-set-timestamp" data-l10n-args="{&quot;timestamp&quot;:1665309930386,&quot;relative-timestamp&quot;:0}">Timestamp 1665309930386 (+ 0 ms)</h5><pre>v=0
o=mozilla...THIS_IS_SDPARTA-99.0 1814080469144449510 0 IN IP4 0.0.0.0
s=-
t=0 0
a=fingerprint:sha-256 6E:D4:D4:05:44:49:CC:85:02:20:8C:A7:37:88:7C:8E:FB:A3:7A:C6:CC:3C:95:51:DC:9B:26:9A:D3:7C:9D:7E
a=group:BUNDLE 0
a=ice-options:trickle
a=msid-semantic:WMS *
m=audio 9 UDP/TLS/RTP/SAVPF 109 9 0 8 101
c=IN IP4 0.0.0.0
a=sendrecv
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=extmap:2/recvonly urn:ietf:params:rtp-hdrext:csrc-audio-level
a=extmap:3 urn:ietf:params:rtp-hdrext:sdes:mid
a=fmtp:109 maxplaybackrate=48000;stereo=1;useinbandfec=1
a=fmtp:101 0-15
a=ice-pwd:b17cc62a9675efa5aafc1a78abb420e9
a=ice-ufrag:4dccfa5a
a=mid:0
a=msid:{9065cbfe-d25b-4494-93cd-06cae7dd6da1} {47181e0b-53cd-4b7d-a6d6-60efbb65ef5d}
a=rtcp-mux
a=rtpmap:109 opus/48000/2
a=rtpmap:9 G722/8000/1
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:101 telephone-event/8000/1
a=setup:actpass
a=ssrc:3212209675 cname:{9b588e43-1359-4912-9619-56938a59da05}
</pre></div><div><h4 data-l10n-id="about-webrtc-remote-sdp-heading">Remote SDP</h4><h5 id="sdp-history: 1665309935583" data-l10n-id="about-webrtc-sdp-set-timestamp" data-l10n-args="{&quot;timestamp&quot;:1665309935583,&quot;relative-timestamp&quot;:5197}">Timestamp 1665309935583 (+ 5,197 ms)</h5><pre>v=0
o=FreeSWITCH 1665292575 1665292576 IN IP4 10.10.30.14
s=FreeSWITCH
c=IN IP4 10.10.30.14
t=0 0
a=msid-semantic: WMS vdwzkifLVZ2sqOIDyyI8Y2pNiLTwxQ6S
m=audio 17344 UDP/TLS/RTP/SAVPF 109 101
a=rtpmap:109 opus/48000/2
a=fmtp:109 useinbandfec=1; stereo=1
a=rtpmap:101 telephone-event/8000
a=ptime:20
a=fingerprint:sha-256 AE:6F:72:9F:51:26:93:66:8E:D0:71:D2:2E:61:DF:84:2E:72:7D:2E:5E:84:31:FB:77:46:78:E8:13:23:1E:34
a=setup:active
a=rtcp-mux
a=rtcp:17344 IN IP4 10.10.30.14
a=ice-ufrag:CvzrnP5vrOSOuPxe
a=ice-pwd:8G9zTFMW3if6m3xPoX7CC2YT
a=candidate:5042833925 1 udp 2130706431 10.10.30.14 17344 typ host generation 0
a=end-of-candidates
a=ssrc:1128739303 cname:Uti4BnFncyFtceXB
a=ssrc:1128739303 msid:vdwzkifLVZ2sqOIDyyI8Y2pNiLTwxQ6S a0
a=ssrc:1128739303 mslabel:vdwzkifLVZ2sqOIDyyI8Y2pNiLTwxQ6S
a=ssrc:1128739303 label:vdwzkifLVZ2sqOIDyyI8Y2pNiLTwxQ6Sa0
</pre></div></div></div>
</body>
</html>

**Comment by ffdixon** [comment]
See https://docs.bigbluebutton.org/admin/configure-firewall.html.  Please post to follow-up to https://groups.google.com/g/bigbluebutton-setup (if there is a bug with BigBlueButton, we'll open an issue here to fix).
