### ISSUE TITLE
Webcam drag & drop visualization

### ISSUE THREAD

**Issue by davidsiecke** [bigbluebutton/bigbluebutton#15805]
**Is your feature request related to a problem? Please describe.**
Currently, when clicking on and holding a webcam, three things happen in the UI:
- all webcams become slightly transparent
- the slides stay as they are
- transparent rectangle overlays appear on all four sides of the presentation area

![image](https://user-images.githubusercontent.com/72148199/194852805-823a8820-a6b5-487c-b1b9-311b2eed9b1e.png)
Two out of six students who participated in a usability test we conducted at Osnabrück University took more than a minute to understand that they had to pull the webcams into one of the rectangles (despite both figuring out quickly that they could drag webcams around).

**Describe the solution you'd like**
We would propose to enhance the visibility of the target rectangles, perhaps by displaying the target areas separately from the slides and using visual elements with a higher contrast, such as a hatching. Additionally, we would suggest
- not making the webcams transparent, as they are the object which the user is acting upon at this moment, and
- shrinking the slides and graying them out, as they are not the object which the user is acting upon at this moment.

Here is a sketch of what we imagined:

![image](https://user-images.githubusercontent.com/72148199/194852857-59597722-5bbb-4385-a02b-2387f7c89bb9.png)

**Additional context**
For background information, see the [usability test report](https://doi.org/10.48693/193) (section 3.2.4.1).

**Comment by tibroc** [comment]
https://github.com/bigbluebutton/bigbluebutton/pull/15959

**Comment by ffdixon** [comment]
Great feedback, and good to see #15959 getting there!

**Comment by davidsiecke** [comment]
I conducted a survey with 66 users to evaluate this proposal. For more details on the survey, see the paragraphs at the end of this comment.

For the evaluation, I slightly revised the appearance of the target areas to be more subdued, but still noticeable:

<img width="400" alt="WDD_T2" src="https://user-images.githubusercontent.com/72148199/217079015-d593b430-87d0-4525-be07-cf7a946c8a67.png">

After having read a short explanation of the rationale behind the proposal, participants were asked to complete the statement

> I think that the proposed changes make the process of moving webcams around ______ user-friendly.

by choosing one of the options
- “much less”,
- “less”,
- “neither more nor less”,
- “more”,
- “much more”.

Out of 66 participants, 42 (≈ 64 %) chose “more” or “much more”. Here is a plot of the response counts:

<img width="400" alt="plot" src="https://user-images.githubusercontent.com/72148199/217079605-8ddfd97e-ff0f-42f5-8ef1-6fc907729eef.png">

### Comments

Some comments participants made about this redesign:

- “It seems like a very (!) bad tradeoff to reduce the size of the slide window. Also the transparent design is less distracting. In the end the platform should help to focus during class (therefore transparant + big slides seems good) and not distract with to many options and design things from the class content :)”
- “I would say it’s not good to make the slides less big, however covering them is not good either.”

As the proposal is only about the very short period of time during which users have the goal of finding an alternative place for the webcam windows, I think making the slides smaller and the target areas non-transparent for improved noticeability is worth it, and can actually help users to focus on the presentation. Users could recognize more quickly and less ambiguously where they can drop their webcams – this would minimize the time they are distracted from the presentation while searching for the target areas. The redesign would thus help users to focus on the presentation by not demanding attention for discerning the target areas.

- “With the new design you can better estimate where exactly to place the webcam image, a better delimitation (and idea of how it will look) is given by the non-transparent target rectangles.” (translated from German)

### About the survey

This survey was conducted with 124 people, mostly students, who had used BBB at least once. 99 % of participants had been using BBB for more than three months, 84 % for more than one year. They were allocated randomly to one of two questionnaires, such that 66 users answered questionnaire 1 and 58 users answered questionnaire 2. The data collected in the survey as well as all pages of both questionnaires can be found here: https://sync.academiccloud.de/index.php/s/w2cWlDCrW4jOpCY
