### ISSUE TITLE
Name of the export button in shared notes

### ISSUE THREAD

**Issue by davidsiecke** [bigbluebutton/bigbluebutton#15802]
**Is your feature request related to a problem? Please describe.**
The name of the export button in the shared notes panel reads “Import/export from/to different file formats”, while importing seems not to be implemented as a functionality.

**Describe the solution you'd like**
Renaming this button to "Export".

**Additional context**
This issue was discovered in a usability test we conducted at Osnabrück University. For background information, see the [usability test report](https://doi.org/10.48693/193) (section 3.2.3.2.2).

**Comment by einhirn** [comment]
Since this is an Issue concerning UI design, the proposed solution of course is the way to go. Just mentioning for completeness sake, being able to import shared notes would be useful to continue work where one left of in the last meeting. Currently this kind of task needs external tools.
