### ISSUE TITLE
Making the "Turn multi-user whiteboard on" button's icon more recognizable

### ISSUE THREAD

**Issue by davidsiecke** [bigbluebutton/bigbluebutton#15801]
**Is your feature request related to a problem? Please describe.**
Seven out of seven students who participated in a usability test we conducted at Osnabrück University waited for the title of the “Turn multi-user whiteboard on” button to appear before clicking it. Two of them explicitly stated that they found the icon ambiguous, and expressed that an icon showing the user symbol which is also used in the “User list toggle” button would be more fitting.

**Describe the solution you'd like**
Based on what the two test participants suggested, we want to propose a redesign of the “Turn multi-user whiteboard on / off” button along the lines of the following sketch:
![image](https://user-images.githubusercontent.com/72148199/194840664-09589114-b64e-4e0d-b7c0-bf52031ac620.png)

**Describe alternatives you've considered**
One participant mentioned that also an icon showing multiple pencils would be suitable. So the following could be an alternative:
![image](https://user-images.githubusercontent.com/72148199/194840764-0b434fc8-d0e5-4b8d-98d1-c3274d653fa0.png)

**Additional context**
For background information, see the [usability test report](https://doi.org/10.48693/193) (section 3.2.2.4).

**Comment by davidsiecke** [comment]
I conducted a survey with 66 users to evaluate this proposal. For more details on the survey itself, see the paragraph at the end of this comment.

I updated the icon above showing pencils to include the pencil symbols utilized in tldraw:

<img width="227" alt="mw1" src="https://user-images.githubusercontent.com/72148199/217091093-0b708bfa-49cb-4ed5-8e90-811f3f8f2710.png">

When asked whether they associated this icon or the other icon (the one showing two user icons) more strongly with the functionality of allowing all session participants to draw on the slides, 39 out of 49 (≈ 80 %) chose the icon showing pencils.

12 participants indicated that they were not really happy with either option. Five of them suggested that perhaps a combination of these two icons, showing people as well as a pencil, would be a better option. I made a sketch of what this could look like:

<img width="300" alt="Bildschirm­foto 2023-02-05 um 10 14 06" src="https://user-images.githubusercontent.com/72148199/217091316-ed883ad0-08f4-40d7-b4ea-66f4f1e6aebe.png">

Participants were then asked to complete the statement

> I associate the functionality of allowing all users to draw on the slides ______ strongly with the redesigned icon I chose above than with the current icon.

by choosing one of the options
- “much less”,
- “less”,
- “neither more nor less”,
- “more”,
- “much more”.

40 out of 60 participants (≈ 67 %) chose “more” or “much more”. Here is a plot of the response counts:

<img width="400" alt="plot" src="https://user-images.githubusercontent.com/72148199/217091463-be151cb5-aff9-42e2-8508-d87b75951baf.png">

### About the survey

This survey was conducted with 124 people, mostly students, who had used BBB at least once. About 99 % of participants had been using BBB for more than three months, about 84 % for more than one year. They were allocated randomly to one of two questionnaires, such that 66 users answered questionnaire 1 and 58 users answered questionnaire 2. The data collected in the survey as well as all pages of both questionnaires can be found here:
https://sync.academiccloud.de/index.php/s/w2cWlDCrW4jOpCY

**Comment by ffdixon** [comment]
Wow David, really good feedback!  @tylercopeland

**Comment by tylercopeland** [comment]
@davidsiecke, thank you for taking the lead in these user research studies. They are very insightful and impactful to the BigBlueButton projects. It's also perfect timing, as I'm working on conceptual designs to improve our presentation controls.

**Comment by tylercopeland** [comment]
@davidsiecke, do you have .svg versions of the icons above?

**Comment by davidsiecke** [comment]
![pencils](https://user-images.githubusercontent.com/72148199/218689461-4728a2f5-8681-4b1b-a4e5-2f09fbc25062.svg)
![users_pencil](https://user-images.githubusercontent.com/72148199/219019539-8a1b78bb-a6c8-403c-bf92-796427f48528.svg)

Note that the user icons and the whiteboard icon are PNGs taken from the BBB custom icon library and may be a bit blurry. Here is an alternative version where the whiteboard frame is a vector:

![users_pencil-v2](https://user-images.githubusercontent.com/72148199/219021089-d1cdf830-b342-43eb-b2f0-8f362f9f5a59.svg)

[Figma project](https://www.figma.com/file/yIxq0hY8Ui4tmW2zuQTdvI/Untitled?node-id=7%3A61&t=jxho2oQvoLHRVtKu-1)

**Comment by tylercopeland** [comment]
@davidsiecke, thanks again for sharing these icons. 

I've started to incorporate these icons into a mockup of the presentation controls, and I was wondering what icon size you shared during the research phase?

**Comment by davidsiecke** [comment]
That’s great to hear!
For the survey I used enlarged versions of these icons, to ensure that they weren’t too small for participants filling out the survey on a smartphone. For a participant using a regular computer, the icons would have been shown approximately as follows:

<img width="817" alt="Bildschirm­foto 2023-02-21 um 21 02 44" src="https://user-images.githubusercontent.com/72148199/220446951-3433eb7e-f27d-49fe-af90-3b71c8df1b5f.png">
<img width="814" alt="Bildschirm­foto 2023-02-21 um 21 02 57" src="https://user-images.githubusercontent.com/72148199/220446955-b470157a-f321-4957-b60b-955e9536ee62.png">

The original questionnaire is also available on https://sync.academiccloud.de/index.php/s/w2cWlDCrW4jOpCY (Questionnaire 1, search for “s202”).

If the icons contain too much detail to be properly discernible in the presentation controls menu, then perhaps the whiteboard frame could be omitted from these icons such that the user and pencil symbols could be displayed slightly larger.
