### ISSUE TITLE
Some observations on layout types

### ISSUE THREAD

**Issue by davidsiecke** [bigbluebutton/bigbluebutton#15813]
**Is your feature request related to a problem? Please describe.**
In this issue, we want to question whether “Custom layout” and “Smart layout” should be implemented as layout types and describe other, in our opinion more apt ways in which these features could be integrated into BigBlueButton.
Additionally, we want to point out how the “Focus on presentation” and “Focus on video” layout types could become obsolete when it is possible for users to hide and minimize the user list panel without concomitantly hiding the chat / shared notes panel (as proposed in issue #15812).

**1 “Custom layout”**
In BBB 2.5, users (including viewers) are always able to change their layout, no matter which layout is pushed to them. Therefore, no sharp line can be drawn between the “Custom” layout type and other layout types. The ability to modify one’s layout should in our opinion not be represented as a separate layout type, but implemented as BBB’s fundamental principle of layout manipulation – such that users don’t always have to choose “Custom layout” in the layout settings in order to be able to modify a (potentially extrinsically imposed) layout.

**2 “Focus on presentation”**
We assume that the driving motivation for including this layout option was to offer a space-efficient solution for displaying the webcams to the side of the presentation while still being able to see the chat. But to us, it seems like implementing options for minimizing and hiding the user list panel while still displaying the chat (as proposed in issue #15812) would be a more elegant way to achieve this, especially considering that the visibility of the webcams (or the presentation area, in case of the "Focus on video" layout type) is coupled to the visibility of the chat / shared notes panel. This also means that when pushing a "Focus on ..." layout, the webcams just disappear for users who have hidden the chat / shared notes tab at that moment.

**3 “Focus on video”**
With the “Focus on video” layout type active, the presentation is so small that its contents can hardly be discerned. Making it more legible requires drawing the chat / shared notes panel to questionable widths and heights. To us, adjusting the relative size of the webcam videos and the presentation via the bar between the presentation area and the webcam videos without simultaneously reshaping the chat / shared notes panel seems much more intuitive.

**4 “Smart layout”**
If the “Focus on presentation” and “Focus on video” layout types are removed, there is no need to incorporate “Smart layout” as a layout type. We think it would be more reasonable then to integrate this functionality as a checkbox setting (we pick up on this in issue #15815) which is activated by default. Manually repositioning the webcam videos (without having to select “Custom layout” in advance, as described above) could disable this setting, while according to our intuition, adjusting the relative size of the webcam video positioning should not.

**Summary**
We suggest to remove the “custom” layout type while allowing users to directly modify their layout at all times, also when a layout has been extrinsically imposed on them. When functionalities for hiding and minimizing the user list panel independently of the chat have been implemented, the “Focus on presentation” and “Focus on video” layout options are obsolete. And at the latest when these two layout types have been removed, it would be more straightforward to integrate “Smart layout” as a checkbox option in the appearance settings.

**Additional context**
This proposal was developed in the context of a usability test we conducted at Osnabrück University. For background information, see the [usability test report](https://doi.org/10.48693/193) (section 3.2.4.3).

**Comment by ffdixon** [comment]
Removing the Stale label -- this is good feedback David and we're looking forward to applying it on top of BigBlueButton 3.0.
