### ISSUE TITLE
Connection: Inconsistent state in screen sharing when switching network

### ISSUE THREAD

**Issue by Tainan404** [bigbluebutton/bigbluebutton#15829]
**Describe the bug**
If the system switches networks while a user is sharing the screen, screen sharing is in an irreversible state in which the user cannot stop sharing.

**To Reproduce**
prerequisites: should have a webcam and two different wifi networks
1. Join with two user
2. Share the screen on presenter
3. Change the network 
4. Wait the client to reconnect
5. Try to unshare the screen

**Expected behavior**
Allow user user to re-share his screen.

**Actual behavior**
The client  doesn't allow the user to unshare the screen or retry to reconnect.

**Screenshots**

https://user-images.githubusercontent.com/15806883/195193292-bf8b283b-a72c-4c3f-a071-d10adec5b6e2.mp4

**BBB version:**
BigBlueButton Server 2.6.0-alpha.4

**Desktop (please complete the following information):**
- OS: ubuntu
- Browser: Chrome
- Version: 106.0.5249.91

**Comment by thomas-mc-work** [comment]
Does the problem still exist with version `6.1` which merged this potential fix https://github.com/bigbluebutton/bigbluebutton/pull/16956?
