### ISSUE TITLE
tldraw duplicate objects outside the presentation is cut

### ISSUE THREAD

**Issue by ali-alhaidary** [bigbluebutton/bigbluebutton#15833]
**Describe the bug**
tldraw duplicate objects outside the presentation is cut

*
**Screenshots**
![Screenshot 2022-10-12 at 08-07-59 BigBlueButton - Home Room - العرض الافتراضي للعرض](https://user-images.githubusercontent.com/75235623/195255462-eb754d8f-1c32-472e-8751-b3c05a7801f6.png)

![Screenshot 2022-10-12 at 08-08-25 BigBlueButton - Home Room - العرض الافتراضي للعرض](https://user-images.githubusercontent.com/75235623/195255480-8c7edc72-3250-478c-9aa9-adde0dc9edcc.png)

**BBB version:**
Client build: 152
BigBlueButton version: 2.6.0-alpha.4

**Comment by germanocaumo** [comment]
@ali-alhaidary Couldn't reproduce with latest version. Can you test again and close in case it's fixed?

**Comment by ali-alhaidary** [comment]
Thank you @germanocaumo , it is fixed
