### ISSUE TITLE
tldraw shapes menu do not show in presentation full screen

### ISSUE THREAD

**Issue by ali-alhaidary** [bigbluebutton/bigbluebutton#15830]
**Describe the bug**
tldraw shapes menu do not show in presentation full screen

**BBB version:**
Client build: 152
BigBlueButton version: 2.6.0-alpha.4

**Comment by germanocaumo** [comment]
@ali-alhaidary Couldn't reproduce with latest version. Can you test again and close in case it's fixed?

**Comment by ali-alhaidary** [comment]
@germanocaumo thanks, what is the link that I should the testing on please?

**Comment by germanocaumo** [comment]
> @germanocaumo thanks, what is the link that I should do the testing on please?

https://dev26.bigbluebutton.org/

**Comment by ali-alhaidary** [comment]
Thank you @germanocaumo , it is fixed
