### ISSUE TITLE
Delay when talking

### ISSUE THREAD

**Issue by GwenvaelRoudour** [bigbluebutton/bigbluebutton#15839]
Hi,

I am trying to use BBB with other people located in the same country (France).
I installed BBB on a contabo VPS (8 cores, 600 Mbit/s), and changed the configuration file to use three parallel Kurento media servers, and lower the bitrate quality of the cameras as advised in the documentation.

But even if we are only 2 people using the app, we have bad delay between video and sound, and even worse, we have a delay of about 8 seconds between the two people.
Therefor, when I say a word, the other person has to wait for 8 seconds to hear me talking.

I tried to switch the microphone off when not talking, with no effect.

I understand we'll have a little delay, that si absolutely understandable but 8 seconds is far too much.

I tried and look for an answer here and on the google group, but nothing seems to work so far.

**Comment by ffdixon** [comment]
We have some updates to audio coming in 2.5.7.  If you want to apply the updates to 2.5.6, see

  https://github.com/bigbluebutton/bigbluebutton/issues/15776

These updates should help reduce the delay.  Let us know if you apply them, restart BigBlueButton, and you see an improvement.

**Comment by GwenvaelRoudour** [comment]
Thank you, I'll see what I can do about it then.
Stupid question : does this get rid of the delay between video and audio (sync) and the delay between people talking/waiting to receive sound ?
Because our main problem is not the sync between audio and video but the delay between one talks and is heard by the other person.

**Comment by ffdixon** [comment]
We would say try the above and let us know if you see an improvement.

**Comment by amg-web** [comment]
@GwenvaelRoudour 
can you share your /etc/bigbluebutton/bbb-html5.yml ?
