### ISSUE TITLE
Layout Settings Enhancements

### ISSUE THREAD

**Issue by tylercopeland** [bigbluebutton/bigbluebutton#15863]
Below is a screenshot of the current implementation of the new layout manager experience. 

<img width="621" alt="Screen Shot 2022-10-18 at 9 34 56 AM" src="https://user-images.githubusercontent.com/1273169/196490221-80a4c240-1d9f-4d6c-b07e-ac0cdc8aa18b.png">

After reviewing our new layout settings experience, which is already an enhancement from our existing top-level settings experience, there is an opportunity for us to continue to improve this experience even further. 

The current implementation of the layout settings is primarily focused on the presentation size/location versus hiding and moving other modules and components around on the screen. With this being said, I believe there is an opportunity for us to simplify things by presenting the presenter with the question, "Where do you want the presentation?

<img width="744" alt="Screen Shot 2022-10-18 at 9 50 13 AM" src="https://user-images.githubusercontent.com/1273169/196494209-860ad0ce-c25d-47c4-a6b1-afa396fd4a12.png">

In addition to that general update, there is an opportunity for us to clean up the interface as well. 
- Move the labels below the images
- Tone down the brightness of the colours with a more greyscale approach
- Update the labels to be presentation focused. For example, Shared, Hidden, Larger and Smaller

In terms of functionality, there is an opportunity for us to continue to simplify things. For example, today, we introduced the experience of pushing the layout down to everyone via the (+) button. To limit the complexity of that button, this experience can live within the layout manager modal itself.

<img width="1468" alt="Screen Shot 2022-10-18 at 11 27 15 AM" src="https://user-images.githubusercontent.com/1273169/196513930-cd1f0191-3ff3-442d-b881-74ad5d25124f.png">

In additional l the removal of Propagate Layout within the (+), we would like to update the "Layout Settings Modal" to "Manage Layout".

<img width="583" alt="Screen Shot 2022-10-18 at 11 28 55 AM" src="https://user-images.githubusercontent.com/1273169/196514258-104ea121-7d34-4be5-80e8-b1a943a5817e.png">

Lastly, within the modal, we would also provide the functionality of allowing our viewing to only see "our webcam" as the presenter.

**Comment by TiagoJacobs** [comment]
Hello @tylercopeland - the overall idea is very good!

I would propose a few changes:

1 - Make it clear that the webcam in question is the "presenter webcam":
<img width="1216" alt="image" src="https://user-images.githubusercontent.com/2075267/198357689-05fcb6c4-41ef-4ba6-ad97-7f812604fab6.png">


2 - Remove the "Hidden" option:
If the presenter wants to hide the presentation he can remove the current presentation - making it on layout would mess with "External video", "Screenshare" and others.

3 - Add the "Dynamic" option (that will be same as our current "Smart layout"):
![image](https://user-images.githubusercontent.com/2075267/198358564-052690c9-2791-4536-9280-a30b99e9d7aa.png)

-----

For who is going to implement:

-

**Comment by ramonlsouza** [comment]
> 2 - Remove the "Hidden" option:
> If the presenter wants to hide the presentation, it's better if he do it from the same place where he sends presentation, meaning that he can have an extra option there (and the layouts will understand and not display this presentation area in these cases) - making it on layout would mess with "External video", "Screenshare" and other features.

If we consider to not add the "hidden" layout option, which I agree, we could add a button to easily disable/enable the presentation for all users (in the "+" button or in the presentation upload modal)

**Comment by einhirn** [comment]
Since we're still struggling with "autoswapLayout" and "restoreonupdate" in 2.5.6, please implement this in a way that works like screen sharing: once the presenter starts any presentation, it's shown in the default layout for everyone automatically. The presentation area should also automatically be hidden once the presentation is ended...

Most of the participants in BBB sessions we know of are rather passive concerning the layout - they don't know about or don't care to or are frustrated by the complications of switching layouts - and presenters are usually occupied with their presentation and don't like to spend more time than absolutely needed on setting things up. So to optimize user experience for all types of sessions (video calls, webinars/lectures, collaboration, anything else?) this ideally should work automatically with sensible defaults.
