### ISSUE TITLE
2.5.6 - publishing poll results crashes clients when public chat panel is closed [edit: AND popup chat notifications on]

### ISSUE THREAD

**Issue by MWWorks** [bigbluebutton/bigbluebutton#15865]
This seems easily repeatable on 2 different instances of 2.5.6, and have confirmed in Edge, Chrome and Firefox.

1. One user logged in as presenter
2. Others logged in as attendees
3. Some attendees have the public chat panel open, some closed
4. All attendees have chat popup alerts on (I had this defaulted to true in bbb-html5.yml)
5. Presenter starts poll (any type of poll seems to be affected); attendees vote
6. When presenter publishes poll, the attendees with the chat panel **closed** immediately lose all UI, showing a blank dark blue screen (but still have audio)
7. They need to reload the browser to resume the session
8. Attendees with the chat panel open see the poll results as expected

I think this is new in 2.5.6 - I do not have 2.5.5 running to check but had no reports of this when I was.

**Comment by ffdixon** [comment]
Good catch!

**Comment by MWWorks** [comment]
> Good catch!

Thanks - sorry for the edit, I hadn't realised the extra condition of chat notifications until I remembered I could double check on demo.bigbluebutton.org. For now I'm no longer defaulting them to on.
