### ISSUE TITLE
After Updating to 2.5.7 from 2.5.6 : "Server Error Invalid BigBlueButton Endpoint and Secret"  and also "mod_bigbluebuttonbn/Checksums do not match"

### ISSUE THREAD

**Issue by ho30hero** [bigbluebutton/bigbluebutton#15881]
Hi
After Updating to 2.5.7 from 2.5.6 : I have these problems: 
**In greenlight** : Server Error Invalid BigBlueButton Endpoint and Secret 
**In moodle**: mod_bigbluebuttonbn/Checksums do not match

When I was in 2.5.6 I changed settings based on #15776 by using FTP as the root user.

No errors in --status and --check
On a dedicated server.

Please help.
Regards

**Comment by josch-rigon** [comment]
I also have this after a clean install of 2.5.7 (3135)
i have a clean Ubuntu 20.04 LTS running, After installation including greenlight, i add a new admin on console by using the
`docker exec greenlight-v2 bundle exec rake user:create["hm","xxxx@yyy.de","Secure-123","admin"]`
I open the url https://bbb.yyy.de and log in with the credentials and get the Error "BigBlueButton Endpunkt und Sicherheitsschlüssel ungültig" that means the same then "BigBlueButton Endpoint and Secret"

i then checked the secret and URL in ~/greenlight/.env. Everything seems to be okay.
In the greenlight log ~/greenlight/log/production.log i see 
`... Support: xxxx@yyy.de is attempting to login
... Support: xxxx@yyy.de has successfully logged in.
...
BigBlueButtonException: Checksums do not match, messageKey: checksumError` 
.. i don't know what it is.
Please halp me, too 
Regards

**Comment by ramonlsouza** [comment]
Thanks for the report! We are already working on this, 2.5.8 should be released in the next hours to address it.

**Comment by ramonlsouza** [comment]
update: 2.5.8 was released! https://github.com/bigbluebutton/bigbluebutton/releases/tag/v2.5.8

**Comment by ho30hero** [comment]
Thank so much @ramonlsouza

**Comment by martin-77** [comment]
Problem is fixed - as far as I can see.
Had the same Error with 2.5.7

A simple apt update && apt upgrade -y fixed the problem.

**Comment by josch-rigon** [comment]
YESS!
i also confirm that this update fixed my problem!
i updated my fresh installation by apt update, apt upgrade and reboot (possibly i testet too much before).. and it works like a charm!
very good job!
