### ISSUE TITLE
[2.6.0-alpha.4] tldraw(?) downloads fonts from Google

### ISSUE THREAD

**Issue by danimo** [bigbluebutton/bigbluebutton#15886]
**BBB version:**
BigBlueButton version: 2.6.0-alpha.4 (html5 client custom build from today's git)

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser Chrome, Firefox

**Additional context**
Since tldraw was integrated, loading the HTML5 client with a browser produces the following download (see network Tab):

`https://fonts.gstatic.com/s/sourcesanspro/v21/6xK3dSBYKcSV-LCoeQqfX1RYOo3qOK7lujVj9w.woff2`

I could not locate this in BBB, but in its dependency https://registry.npmjs.org/@tldraw/tldraw/-/tldraw-1.20.0.tgz I found:

`https://fonts.gstatic.com/s/recursive/v23/8vI-7wMr0mhh-RQChyHEH06TlXhq_gukbYrFMk1QuAIcyEwG_X-dpEfaE5YaERmK-CImKsvxvU-MXGX2fSqasNfUlTGZnI14ZeY.woff2`, so there may also be gstatic depdencies elsewhere in the dependencies.

**Comment by ffdixon** [comment]
Good catch @danimo.

**Comment by danimo** [comment]
The fix (https://github.com/tldraw/tldraw/pull/1091) has been merged into tldraw. Any release based on this does not load fonts from Google with the exception of SVG exports. See https://github.com/tldraw/tldraw/issues/1077#issuecomment-1368131620 for options on this one.
