### ISSUE TITLE
Turn presentation management into dialog

### ISSUE THREAD

**Issue by lkiesow** [bigbluebutton/bigbluebutton#15893]
As a moderator, if you click on “manage presentations”, it feels as if you are completely leaving BigBlueButton. For a better user experience, it would be great if we could turn this view into a dialog like this instead:

![Screenshot from 2022-10-21 13-01-12](https://user-images.githubusercontent.com/1008395/197526159-71c3b070-4d87-4b32-987b-c9c586537f70.png)
(as with other dialogs, the button should be moved to the bottom)

Doing so allows users to still be more aware of what happens in the meeting (e.g. who is speaking) and ensures them that they are still part of the meeting.

As the mockup shows, it should also be easy to fit everything on a smaller dialog, since the view right now has a lot of unused space anyway.

> This issue is created for the Fall 2022, mini hackathon at UOS/ELAN on November 10.
> Expect a pull request as part of that until the end of the week.
> If any of these won't get worked on, I'll remove this comment.

**Comment by tibroc** [comment]
We could do something like this (see also discussion in https://github.com/bigbluebutton/bigbluebutton/issues/15954):

![image](https://user-images.githubusercontent.com/39943803/201166534-6e40a34c-f035-4b1b-8eed-eba740e7e709.png)

**Comment by lkiesow** [comment]
I like the idea of moving this into the sidebar. That also where other presentor options already live. Like for example, when starting or managing polls. That makes it consistent with other user interface elements. Having it there also means that users can always interact with the meeting and even mute/unmute themselves while managing presentations. That's great.
