### ISSUE TITLE
Registration form for participants

### ISSUE THREAD

**Issue by Sofistifier** [bigbluebutton/bigbluebutton#15907]
Hello!

Is there any plan for adding some kind of forms creation functionality to the admin panel. I mean an ability to modify(add some fields) to present simple form with one Name field. Thank you in advance for support!
May be there is a way to edit some script in BigBlueButton or Greenlight to add some field to registration form?

**Comment by SamuelWei** [comment]
I think this is related to greenlight (https://github.com/bigbluebutton/greenlight) or any other frontend
