### ISSUE TITLE
Create an Android client for BigBlueButton, take 2

### ISSUE THREAD

**Issue by astrojuanlu** [bigbluebutton/bigbluebutton#15908]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when opening BBB on my Android phone: audio issues, general slowness, lack of some functionality, etc.

**Describe the solution you'd like**
Create a native Android client for BigBlueButton.

**Describe alternatives you've considered**
The alternative is business as usual, but honestly BBB is the videoconferencing app that has the worst behavior on phones.

I understand that BBB was created for teachers and schools, and perhaps an Android client was never needed or wanted (that's at least the impression I get from the [main website](https://bigbluebutton.org/)). But now lots of organizations are using it to provide generic videoconferencing services (meet.coop, meet.commonscloud.coop) and some hybrid events are using it as well. Hence, I think it's more needed to have a good Android client. 

**Additional context**
Instead of leaving a comment in https://github.com/bigbluebutton/bigbluebutton/issues/1606, which should have been reopened, I decided to open a new issue.

**Comment by adam-op** [comment]
+1 I am waiting for this since 2021 when i got to know BBB, my daily work is extremely limited by the HTML5 only limitation of BBB, it would be a great gift for so many people, without a client on Desktops and Smart Devices BBB will NEVER be a competitor to professional solutions. Think about if BBB shall be a professional solution or a underground Open Source Project... I am curious for the decision of the community... Of course everyone likes to stay underground and not go commercial because NO ONE LOVES MONEY :)

**Comment by ffdixon** [comment]
See

  https://bigbluebutton.org/global-conference-2022/

for the presentation on the upcoming mobile client.

**Comment by astrojuanlu** [comment]
Indeed, there's a presentation about BBB Tablet and BBB Mobile here https://youtube.com/watch?v=1-TT1cE5Pdc

![Screenshot_20221028-075438_Firefox](https://user-images.githubusercontent.com/316517/198513989-e92a5b65-b865-4905-8cd8-a55ead6ba2bc.png)
![Screenshot_20221028-075621_Firefox](https://user-images.githubusercontent.com/316517/198513995-77516c13-2f43-40c5-ab25-e3c7e4c80d81.png)

Looking forward to seeing the prototypes in mid-late 2023 then :)

**Comment by antobinary** [comment]
Hey, you may want to check out https://github.com/mconf/bbb-mobile-template and https://github.com/mconf/bbb-mobile-sdk/

**Comment by antobinary** [comment]
Also https://github.com/bigbluebutton/bigbluebutton-tablet and https://github.com/bigbluebutton/bigbluebutton-tablet-sdk

**Comment by astrojuanlu** [comment]
Well, if stalebot says so.

**Comment by antobinary** [comment]
This would still be my answer today:

https://github.com/bigbluebutton/bigbluebutton/issues/15908#issuecomment-1434922982

**Comment by astrojuanlu** [comment]
Of those 4 links, 1 is a GitHub template, 2 are SDKs, and 1 contains a link to an iOS app.

Where is the Android app?
