### ISSUE TITLE
Deskshare Exists but not present in playback

### ISSUE THREAD

**Issue by ramandika** [bigbluebutton/bigbluebutton#15912]
**Describe the bug**
I did a course recording using slide presentation and annotation from my tablet and screen sharing using my desktop (so basically, I used two devices for my teaching). Then when I tried to look at the recording result, I saw no screen sharing shows in the recording. Then I check the status of the recording and 

### it shows x mark under D in the APVDE section
![image](https://user-images.githubusercontent.com/7370645/198142763-0f0c271f-41d7-4473-9472-d9b7dd2615cb.png)

### but the screen records exist in the kurento folder
![image](https://user-images.githubusercontent.com/7370645/198144620-8febb3e8-a011-4580-b44a-c69ec0c6f62e.png)

**To Reproduce**
1. Start recording
2. Do slide presentation from mobile
3. Take presenter from desktop, then do screen sharing
4. Repeat step 2 and 3 while in between pause the recording

**Expected behavior**
Screen share and presentation with annotation are being recorded

**Actual behavior**
Screen share is blank only presentation with annotation and audio are being recorded correctly

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser Chrome
 - Version 106.0.5249.119 (Official Build) (x86_64)

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy Tab S7
 - OS: Android 12
 - Browser Samsung Internet Browser
 - Version 18.0.4.14

**Additional context**
I want to be able to rebuild my recording such that the screen share is present in the playback

**Comment by zoeli-realize** [comment]
same issue here (BigBlueButton Server 2.4.9 (3075))

in playback, the audio is ok, Screen share is blank , but the student's webcam can be seen 
see link below:
https://course.yijueyuan.com/playback/presentation/2.3/0217f2de5eabbf4001fca605a738ed667c22d634-1676768077620
https://course.yijueyuan.com/playback/presentation/2.3/0217f2de5eabbf4001fca605a738ed667c22d634-1674041911723

how can I fix this??
