### ISSUE TITLE
Change the color of the "End Meeting" button

### ISSUE THREAD

**Issue by maxjacobs283** [bigbluebutton/bigbluebutton#15915]
**Is your feature request related to a problem? Please describe.**
We've gotten multiple internal and customer reports of the coloration of buttons in the room menu causing especially novice users to accidentally close the session instead of simply leaving it.
This is frustrating if you want to continue using the room. 

**Describe the solution you'd like**
I would like the coloration of those two buttons to be correct. Making the button to leave the session more neutral, maybe even just black and making the button to close the session a warning label instead.

This would be advantageous for the new user experience and might also improve accessibility a bit.

**Describe alternatives you've considered**
Alternatively, it would be great to be able to manually adjust CSS parameters in BBB

**Comment by ErikLtz** [comment]
Fully agree, would be a small but important enhancement. It appears the only thing added for the colored leave-line is
  color: var(--color-danger, #DF2721);
in the style attribute for the li item so either adding this for the end session too or making it a configurable option would be a great little thing :-)

**Comment by MaximKhlobystov** [comment]
This is very similar to #15891. Let's continue this discussion there. I'll close this issue in favor of #15891.
