### ISSUE TITLE
'Preload' external videos to have ready to play with a click

### ISSUE THREAD

**Issue by MWWorks** [bigbluebutton/bigbluebutton#15928]
I use the external video feature quite often and it works well. But sometimes presenters get a bit flustered trying to find the right URL for the point in the presentation; and/or they manage to somehow mis-copy or mis-paste the URL and it doesn't work.

In the same way that we can pre-load presentations when the room starts, it would be a big QOL improvement to also 'preload' external video URLs. Not to cache them locally or anything like that - but just to have the videos ready to play in advance without having to find the URL.

Ideally this could be done:
- In the Manage Presentations dialog - add a list of URLs with a name/description; and
- Via the API when creating the room

Then perhaps the videos would be available via the + popup menu along with the presentations (eg with a different icon to denote a video).

**Comment by ffdixon** [comment]
Love it -- we've been discussing this internally as the next natural step to Smart Slides (where BigBlueButton is detecting polling questions and giving you a single button to start the poll).

The same could be done for slides that contain a URL to YouTube, for example: give the instructor a one-click button to start sharing the video (as opposed to copy-paste in the URL from outside of BigBlueButton).

**Comment by MWWorks** [comment]
That sounds great - we already use the auto poll detection quite a bit, so having it for video URL detection also sounds a great way to implement this - ideally:

- This should detect all the same media formats as the current share video feature handles - we use Youtube but also self-host some videos (via Nextcloud) so it should detect any .mp4 etc URL
- Be able to detect multiple URLs on a single slide - so eg if they are not able to be worked into a presentation, the user could just rustle up a quick PDF with the URLs and switch to it as required

And, as ever... thanks for the amazing work :)

**Comment by ffdixon** [comment]
Yay!
