### ISSUE TITLE
npm dependency resolution failure: jcenter is not available

### ISSUE THREAD

**Issue by georg3k** [bigbluebutton/bigbluebutton#15943]
Following files:
```
bigbluebutton-web/build.gradle
bigbluebutton-web/pres-checker/build.gradle
```
Contain references to **jcenter** repository which has been shut down. ``jcenter()`` should be replaced with ``mavenCenter()``

**Additional context**
More info and temporary workaround here: https://github.com/bigbluebutton/docker/issues/236

**Comment by antobinary** [comment]
Thanks for reporting! This was resolved by https://github.com/bigbluebutton/bigbluebutton/pull/15937 and https://github.com/bigbluebutton/bigbluebutton/pull/15940
