### ISSUE TITLE
whiteboard: cursor in the wrong place if presenter is changed with multi-user whiteboard

### ISSUE THREAD

**Issue by ramonlsouza** [bigbluebutton/bigbluebutton#15965]
**Describe the bug**
Cursor gets in the wrong position if presenter is changed with multi-user whiteboard enabled.

**To Reproduce**
1. Join a meeting with 2 users
2. Enable multi-user whiteboard
3. Switch presenter
4. See error - cursor is in the wrong place

https://user-images.githubusercontent.com/3728706/200627607-2e61d735-d999-4d45-b440-5a36e9f404ed.mp4

**Expected behavior**
Cursor should appear in right position

**Actual behavior**
Cursor appears in the wrong position (for both users)

**BBB version:**
2.6 alpha 4

**Comment by antobinary** [comment]
Likely duplicate of https://github.com/bigbluebutton/bigbluebutton/issues/16389
