### ISSUE TITLE
[2.6.0-alpha.4] tldraw: Default font settings

### ISSUE THREAD

**Issue by SamuelWei** [bigbluebutton/bigbluebutton#15964]
**Describe the bug**
Currently tldraw is using center text alignment. Muliple beta users have reported, how this has been an issue for them. The wanted to start writing on the slides, so they put their cursor to the left side of the slide. After a few words the text "moved" out of the slide, due to the text alignment.

To change this behavoir the user has to find the align settings in the "styles" popup (this was not easy to find) or move the text to the center of the slide.

It was also asked by the users if the font-size can be adjusted. Currently there is the way to select one of three options, however the smallest is still quite big. Using a smaller font can only be acchieved by resizing the text-box.

The default font family is Caveat Brush ("script"); is is nice looking but not a very serious for businesses and universities. 

As I can imagine,  most of these points can be very controversial; I would suggest to make this configurable via a config file or api; e.g. `whiteboardPresets={"text": {"family": "sans","align":"left","small-size": "10px"}}`

**To Reproduce**
1. Go to whiteboard
2. Move cursor to the left of the slide
3. Start typing

**Expected behavior**
Default text alignment left (or right if RTL)
(optional) different font-family

**Actual behavior**
Text aligment center

**Screenshots**
![image](https://user-images.githubusercontent.com/4281791/200598261-f7008cd5-7193-4dd2-98f1-83396e4cedd3.png)

**BBB version:**
BigBlueButton Server 2.6.0-alpha.4 (413)

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser Chrome
 - Version 107.0.5304.87

**Comment by antobinary** [comment]
Update:
@KDSBrowne says that https://github.com/bigbluebutton/bigbluebutton/commit/4a54cf4bd66d8952702ddbad917747842d22391e fixes the default font alignment but there is still a bit of work in the area.

**Comment by ramonlsouza** [comment]
default font-family addressed by #16475, font-size settings should be part of #16168
