### ISSUE TITLE
[2.6.0-alpha.4] tldraw: Color and fill

### ISSUE THREAD

**Issue by SamuelWei** [bigbluebutton/bigbluebutton#15963]
**Describe the bug**
If the user is choosing the color of a rectangle, triangle, circle, etc. the selected color is not very easy to see, due to the contrast to the background. I also think that is is not very intutive to click on the empty space next to "fill" to fill the area. This concept is unique in BBB.

**To Reproduce**
1. Draw a rectangle
2. Click on stiles
3. Select blue color
4. See bad contrast to background color

**Expected behavior**
Have a higher constrast to the background color

**Actual behavior**
Bad contrast; Not very intuitive to select background color

**Screenshots**
![image](https://user-images.githubusercontent.com/4281791/200592717-61b2118e-92a9-48b1-be64-4ecf730ead6a.png)

**BBB version:**
BigBlueButton Server 2.6.0-alpha.4 (413)

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser Chrome
 - Version 107.0.5304.87 

**Mockup**
![image](https://user-images.githubusercontent.com/4281791/200593632-f18a4884-3a25-4dbe-b6d1-f70ef8b95ce1.png)

**Comment by antobinary** [comment]
Fill is implemented in tldraw v2 which we're in the process of migrating to (BBB 3.0)
![Screenshot from 2023-11-06 05-56-50](https://github.com/bigbluebutton/bigbluebutton/assets/6312397/944f624a-6d22-4bc0-80bc-4dec26c9dea0)

**Comment by SamuelWei** [comment]
@antobinary Thanks, however my issue was not about the missing fill feature but about the usability / UI of the current implementation

**Comment by antobinary** [comment]
I find that in tldraw.com 's v2 it's more usable but I have still reopened the issue so that you can decide if it matches your criteria:
![Screenshot from 2023-11-06 20-03-41](https://github.com/bigbluebutton/bigbluebutton/assets/6312397/adee824f-1ec6-4ac5-8fba-18f433a8d452)

**Comment by antobinary** [comment]
@SamuelWei is this still an issue if you check the current state in demo.bigbluebutton.org (BBB 3.0.0-beta.5)?

**Comment by SamuelWei** [comment]
@antobinary Looks much better now
