### ISSUE TITLE
Menus on the whiteboard overlap and vanquish behind other toolbars. 

### ISSUE THREAD

**Issue by d3hof** [bigbluebutton/bigbluebutton#15973]
**Describe the bug**
Whiteboard Menues Overlap if the screen width gets smaller, for example if I just use half the screen on a 24" monitor on 1920x1080 for the conference.
It actually is fine if i reduce height, then the symbols are moved to the bottom side.

**To Reproduce**
Join a conference as a peresenter or multiuser whiteboard enabled.
Adjust window in width, and see the Menues overlapping.

**Expected behavior**
Menu shouldn't overlap, and should either get smaller (I can see issues with that) or change possition.

**Actual behavior**
Menus overlap and some symbols get invisible, for example the delete button moves behind the navigation toolbar.

**Screenshots**
![image](https://user-images.githubusercontent.com/69150785/200788820-59adb39a-da80-43b1-ad75-c7dc329c7bc3.png)

**BBB version:**
BigBlueButton Server 2.6.0-alpha.4 (396)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Chromium 106.0.5249.103

**Comment by ramonlsouza** [comment]
Hello @d3hof! 

Here's a screenshot (half screen of 1920x1080) of the whiteboard after #16032 (included in BigBlueButton 2.6.0-beta.2), now the toolbar gets smaller and goes to bottom of whiteboard area.

![2022-12-15_08-07](https://user-images.githubusercontent.com/3728706/207844671-c6ec1dc7-fed2-429b-a907-d7e3d7169e91.png)
