### ISSUE TITLE
Better drawing support with a stylus

### ISSUE THREAD

**Issue by liolin** [bigbluebutton/bigbluebutton#15976]
**Is your feature request related to a problem? Please describe.**
When I draw on the iPad with a stylus, BigBlueButton also interprets the touches of my palm when I place my hand on the table while drawing. If it is easy to solve this problem, we would be very happy.

**Describe the solution you'd like**
Use the iOS / Android APIs for the drawing stuff. However, I am not sure if this is even possible.

**Describe alternatives you've considered**

**Additional context**

**Comment by antobinary** [comment]
P.S. In BBB 2.5 we were benefitting from a generous community contribution https://github.com/bigbluebutton/bigbluebutton/pull/11224
