### ISSUE TITLE
Presentation not visible when entering the Conference on Android Phone

### ISSUE THREAD

**Issue by dmtrhfr** [bigbluebutton/bigbluebutton#15972]
**Describe the bug**
When you enter the Conference on an Android Phone I can't see the presentation. Only the 3-Dot menu is visible. As soon as the slides get changed the presentation is visible.

bbb 2.6-alpha4 installed with bbb-install.sh

**To Reproduce**
Join a conference on Android and see. (Browser doesn't seem to matter.)

**Expected behavior**
As soon as I am joining the conference, i wanna see the presentation.

**Actual behavior**
I can't see the conference, and I can't change the behaviour on my side either.

**Screenshots**

![thumb-markup_1000000098](https://user-images.githubusercontent.com/69150785/200784546-cdd76b9a-3c68-4180-8210-13e8edecd424.png)

**Smartphone (please complete the following information):**
- Device: Google Pixel 4a
- OS: Android 13
- Browser Firefox 106.1.0; Google Chrome 107

**Comment by d3hof** [comment]
Sorry for the wrong label, as it is probably a HTML5 Issue.

**Comment by antobinary** [comment]
This should be resolved on < BBB 2.6.0-rc.3.
I have seen it in the past but no longer. Please reopen if new cases occur. Also include the version it happened on
