### ISSUE TITLE
Undo Button does restore drawings

### ISSUE THREAD

**Issue by liolin** [bigbluebutton/bigbluebutton#15975]
**Is your feature request related to a problem? Please describe.**
Sometimes in class we draw something on the screen. When I want to undo some drawings I click the "Undo" button on the right side. But the "Delete" / "Clear" button is right below the undo button and sometimes I click on the delete button by mistake.
My problem is that the "Undo" button does not restore my previous drawing.

**Describe the solution you'd like**
The Undo Button does restore my cleared drawings.

**Describe alternatives you've considered**
No alternative considered.

**Additional context**
No additional context.

**Comment by antobinary** [comment]
Can no longer reproduce on BBB 2.6.0-rc.3; Undo + redo work correctly
