### ISSUE TITLE
Allow webcam focus if only two webcams exist

### ISSUE THREAD

**Issue by lkiesow** [bigbluebutton/bigbluebutton#15978]
Right now, BigBlueButton only allows focussing a webcam if at least three webcams exist. But if I am a viewer without webcam and I have two presenters, it can still be very useful with only two webcams to focus and therefor enlarge one of them. Imaging a situation like the following where with only one webcam on the right side:

![Screenshot from 2022-11-09 18-27-43](https://user-images.githubusercontent.com/1008395/200945917-f140b14c-d64b-4e9a-b32a-0985265dd05a.png)

Fixing this issue is to lower the number of webcams when this feature becomes active from three to two.

> This issue is created for the Fall 2022, mini hackathon at UOS/ELAN on November 10.
> Expect a pull request as part of that until the end of the week.
> If any of these won't get worked on, I'll remove this comment.

**Comment by tibroc** [comment]
I find this is might be a quickfix for https://github.com/bigbluebutton/bigbluebutton/issues/15468.
However, this fix here would for me be superseded by 15468.

**Comment by lkiesow** [comment]
Wanting #15468 is definitely valid and a nice additional feature, but I think even if you have that, there is no need to again limit focus to when you have more than three webcams. Having the feature enabled with two cams should never hurt anyone.

**Comment by ffdixon** [comment]
Thanks for your feedback @tenisha333.  We'll revisit this in a future update.

**Comment by tenisha333** [comment]
Thank you, much appreciated. Any idea when a future update will be?
