### ISSUE TITLE
2.5.8 cutoff sound with mobile data - fixed by revert back to 2.5.5

### ISSUE THREAD

**Issue by ho30hero** [bigbluebutton/bigbluebutton#15970]
Hello,
I hope you are well.

Problem:
After Upgrading to 2.5.8 we have cutoff sound with all users that connect with mobile data all the time they want to speak. 
If they change the network for example to ADSL they don't have any problem with the same device. 
I have to reinstall in a clean environment but again in 2.5.8, the problem is not solved.

Solved By:
So I have to Reinstall again but this time with the old version 2.5.5, after that, the problem is gone.

More Info:
Baremetal server : Hetzner
Linux 20.04.05 LTS in all above tests.

Regards

**Comment by ffdixon** [comment]
Hmm ... this all comes down to the FreeSWITCH settings.  Could you help us narrow this down?  Do you have a user you can test with?

Could you setup a 2.5.8 server and switch back and forth with the user to confirm 2.5.5 doesn't have the issue, and you hear it in 2.5.8 (this back-and-forth will give you a baseline to change and test in the moment)

Then, backup the files `/opt/freeswitch/conf/dialplan/default` in 2.5.8 and copy over the files from 2.5.5.  

Test both servers again, is there still a difference?

This will help us narrow down where the differences are between the servers and help you get onto the latest release.

**Comment by ho30hero** [comment]
Hello
Thank you so much Mr. Dixon,

As the server is in production mode and is active about 90% of the week it is so hard to do tests for me. ( with at least 40-150 GB of recordings) but I try to do what you say or test it on another server and share the result here with you.

kind regards

**Comment by ffdixon** [comment]
We are very interested in hearing the results.  There is some difference, and we are keen to understand what you are experiencing.
