### ISSUE TITLE
Change German wording for "save current slide" via ⋮

### ISSUE THREAD

**Issue by cgruber-uos** [bigbluebutton/bigbluebutton#15985]
### Current Situation 

User can download the **current slide** of a presentation via the ⋮ [three vertical dots]-icon upper right corner in the presentation area: 

![2022-11-10 13_56_16-BigBlueButton - Startraum - Chromium](https://user-images.githubusercontent.com/101632236/201098663-dd864fef-c138-4f94-9820-a8e0d8fea3d4.png)

The German Text is:
> Ausschnitt der aktuellen Folie

and the success message is:
> Aktuelle Präsentation wurde herunter[geladen]...

![2022-11-10 13_56_21-BigBlueButton - Startraum - Chromium](https://user-images.githubusercontent.com/101632236/201109300-cbf0b057-816d-4c08-8fa5-db20d418c91e.png)

What you get ist not the whole presentation as mentioned in the success message but only a single slide as `*.png` image: 

![2022-11-10 13_57_00-Präsentation_Startraum_2022-11-10T12_56_27 569Z png ‎- Windows-Fotoanzeige](https://user-images.githubusercontent.com/101632236/201110468-a9b331a8-e969-4fb9-acb6-163b626e9e0e.png)

### Problem description

1. Both messages are not true! ;-) 
a) It is not a section **of the current slide** ("Folie"), it's a section of the current presentation, aka "a single slide". 
b) Success message is also wrong. Not the presentation is downlaoded but **a single slide from the current presentation only.** 
2. The text 
"Ausschnitt der aktuellen Folie"
is incomplete. **A verb is missing**. What is done with this, what can I get as user, can I see it -- would be my expectation without a verb, but it is downloaded. 

### Solution change wording

Change 
> Ausschnitt der aktuellen Folie
to
> Aktuelle Folie herunterladen

Change the success message
> Aktuelle Präsentation wurde herunter[geladen]...
to 
> Aktuelle Folie wurde herunter[geladen]...

**Comment by Marius1501** [comment]
Could you assign me to this issue, please? I would like to work on it. 😄

**Comment by antobinary** [comment]
Look like @Marius1501 changed the German version in Transifex: https://github.com/bigbluebutton/bigbluebutton/pull/15996#issuecomment-1322575328
