### ISSUE TITLE
Truly anonymous poll 

### ISSUE THREAD

**Issue by SamuelWei** [bigbluebutton/bigbluebutton#15997]
**Is your feature request related to a problem? Please describe.**
In some videoconferences, secret elections / voting are necessary for legal reasons. Also system administrators must not have any technical possibility to reconstruct results from log files, etc.

**Describe the solution you'd like**
Give every user that is allowed to vote a "token" that is send back to validate if allowed to vote and not already voted. Do not send the user id!

**Describe alternatives you've considered**

_💬 Open for comments and other ideas!_ 

**Additional context**
*none*

**Comment by ffdixon** [comment]
Thanks for opening this issue -- we want to make sure there is an option ensure anonymous polls are not recorded in the log files.
