### ISSUE TITLE
Telephone dial-in access doesn't work without web audio users in meeting

### ISSUE THREAD

**Issue by BrentBaccala** [bigbluebutton/bigbluebutton#16003]
If a meeting is running with no audio users, then attempting to dial-in with the telephone access code doesn't work.

Examining `fs_clibbb` and running `conference list` shows "No active conferences".

This happens even though a conference ID number is presented to the users for dial-in access.

I've seen this on a collaborate server, which is a variant of BigBlueButton 2.4.

**Comment by hostbbb** [comment]
Do you have this line in your DID.xml for matching the phone number?
<condition field="${conference ${pin} list}" expression="/sofia/g" />

this makes sure the conference exists, or rejects the dialin.  if you remove it.. then all 5 digit pins will create an adhoc conf on switch,  Fat fingered pins just join empty conferences.

**Comment by BrentBaccala** [comment]
@hostbbb, that sounds like a very good idea.

I don't think it's anywhere in the [instructions](https://docs.bigbluebutton.org/admin/customize.html#add-a-phone-number-to-the-conference-bridge) for adding dialin access.

We could add this to the instructions, but maybe adding dialin access is complicated enough that we should configure it in `/etc/bigbluebutton` or `bbb-conf`.
