### ISSUE TITLE
Recordings are not published recently + error in sanity check

### ISSUE THREAD

**Issue by ho30hero** [bigbluebutton/bigbluebutton#16015]
Hello
I hope you are well

Recordings are not published recently 
Also they are not appear in the Moodle 3.9 & Moodle 3.10
I test a small recording my self in Greenlight and rcording not showing after a while. 

I have this problem in both of the below situations:
1. Clean installed 2.5.5 , transfer recordings >> set permissions >> rebuild all.
2. Update above to 2.5.8, transfer recordings >> set permissions >> rebuild all.

Before update to 2.5.8 in the log I find out that there is no .env file, so I created and paste the default file content and change the secret_key and safe_host there. Also use docker run --rm bigbluebutton/greenlight:v2 bundle exec rake secret

I search a lot to solve the issue but I can't.

bbb-conf --status: all Active
bbb-conf --check: No problem
bbb-record --check: No problem
Dedicated server :
Kernel version: 5.4.0-132-generic
Distribution: Ubuntu 20.04.5 LTS (64-bit)
Memory: 65783 MB
CPU cores: 12

**Here is some parts of bbbconf --debug:**
/var/log/bigbluebutton/sanity.log:E, [2022-11-16T06:55:29.311070 #84559] ERROR -- : error in sanity check: Events file doesn't exists.
/var/log/bigbluebutton/sanity.log:E, [2022-11-16T06:55:29.311081 #84559] ERROR -- : /usr/local/bigbluebutton/core/scripts/sanity/sanity.rb:53:in `check_events_xml'

/var/log/bigbluebutton/bbb-web.log:2022-11-16T15:09:32.828Z ERROR o.b.web.controllers.ApiController - A meeting with that ID does not exist
/var/log/bigbluebutton/bbb-web.log:2022-11-16T15:09:47.375Z ERROR o.b.web.controllers.ApiController - A meeting with that ID does not exist
/var/log/bigbluebutton/bbb-web.log:2022-11-16T15:09:47.996Z ERROR o.b.web.controllers.ApiController - A meeting with that ID does not exist
/var/log/bigbluebutton/bbb-web.log:2022-11-16T15:10:04.682Z ERROR o.b.web.controllers.ApiController - A meeting with that ID does not exist

**Here is the result of bbb-record --watch:**
[https://postimg.cc/0bLN2DTv](https://postimg.cc/0bLN2DTv)

**Here are some of the results of the bbb-record --list:**
[https://postimg.cc/zyGMTjxp](https://postimg.cc/zyGMTjxp)
[https://postimg.cc/hJH5Wqc3](https://postimg.cc/hJH5Wqc3)

Please help.
Kind Regards

**Comment by ho30hero** [comment]
Hello
I want to update my issue,

Today I checked my 1-minute recordings in Greenlight and they appear now.
Also, my 1-minute recording in Moodle appears now. 
They take so much more time to publish than before.

But about the other transferred recordings and some other recent meeting recordings, I still have the problem.

I am not sure that this helps but, Could it be possible to find out that is there something freezing part of the recording workflow? for example an unfinished job or bad recording data files? And a way to delete them, so the server can process the rest of the list normally and faster. (Something like a script for example for this)

**Here is the full result of bbb-record --list:**
https://postimg.cc/62dPnJ3z
As you can see there are a lot of recordings that don't process and don't publish. Mainly our recent ones that are more important than others.

Regards

**Comment by parreitu** [comment]
I have the same problem

- BBB fresh install: BigBlueButton Server 2.5.11 (3193)
- Ubuntu 20.04.5 LTS
- 16GB RAM
- 8 Processors

**Comment by hostbbb** [comment]
post more details errors in bigbluebutton-setup group in google forums

what exactly is failing in sanity log?   Not here in issue tracker
