### ISSUE TITLE
2.6.0-beta.1 tldraw tablet issue (double click?)

### ISSUE THREAD

**Issue by vasylOstrovskyi** [bigbluebutton/bigbluebutton#16029]
**Describe the bug**
When using touchpad or tablet (not mouse), incorrect actions sometimes happen. Touching the tablet by pen, or double-tab the  touchpad sometimes 'locks' the cursor (see video). This is very annoying and makes the whiteboard almost unuseable.

**To Reproduce**
This issue happens sporadically, no reliable way to reproduce

**Screenshots**
[tldraw.webm](https://user-images.githubusercontent.com/33595182/202846358-f22da629-8ea1-4e35-ad31-30d8ce21c995.webm)

**BBB version:**
2.6.0-beta.1 clent 215

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser Crome, Chomium, Brave
**Additional context**

1. I could not reproduce this issue with Firefox, only with Crome-based browsers
2. With mouse, this issue can happen if one double-click left button instead of single click.

Regards,
 Vasyl

**Comment by ffdixon** [comment]
Curious, can you reproduce the issue at https://tldraw.com/?

**Comment by vasylOstrovskyi** [comment]
I could reproduce this on https://test26.bigbluebutton.org, but https://tldraw.com/ works fine. Seems like BBB interprets some touches as double-clicks.

BTW, yet another thing which works on https://tldraw.com/ but is missing in BBB is a posibility to select (and the move etc.) several objects at once. Hope this will be imlpemented.

Regards,
 Vasyl

**Comment by antobinary** [comment]
Hi @vasylOstrovskyi 
Any chance you could try this again on test26.bigbluebutton.org ? Lots of improvements went in the whiteboard since this was reported. I am not able to reproduce right now but might be trying incorrectly. Thanks in advance!

**Comment by vasylOstrovskyi** [comment]
Hello @antobinary,
Unfortunately, the issue is still there, Below I attached video where I try to write "This is a test" three times. 
Pease notice that this can be reproduced with
1. Linux (Windows is OK)
2. Chome or based on it browser (Firefox is OK)
3. Graphic tablet (mouse or touchpad are OK)
Also, under thee conditions I notices significant difference between official versions of tldraw: standard tldraw.com and beta.tldraw.com, the latter seems to work noticeably better (i do not know however where the sources of tldraw-beta can be found)
[bbb-tldraw.webm](https://user-images.githubusercontent.com/33595182/219135278-f1f2885b-ba78-4a4c-b6f5-6d6d1e550d93.webm)

**Comment by vasylOstrovskyi** [comment]
In 2.6.1, I cannot reproduce it anymore. Thanks.
Regards,
 Vasyl
