### ISSUE TITLE
Request and suggestion to use the Vazirmatn font for right-to-left languages such as Persian and Arabic from the Google font repository.

### ISSUE THREAD

**Issue by iRealDream** [bigbluebutton/bigbluebutton#16025]
Considering that for several years, most of the sites that are published in right-to-left languages use the standard vazirmatn font, and in order to beautify the BigBlueButton environment, they have to inject the CSS code into the API; It is requested to use this font for right-to-left languages

**Comment by antobinary** [comment]
Related https://github.com/bigbluebutton/bigbluebutton/issues/13596
