### ISSUE TITLE
Dark Mode issue with files with white background

### ISSUE THREAD

**Issue by abhinavmohan1** [bigbluebutton/bigbluebutton#16028]
**Describe the bug**
Any file uploaded with a white background when converted to PDF is shown with dark background in dark mode. However, if any colour is applied to the background of the file, it appears fine. 

**To Reproduce**
 Upload a PDF with a white  background while dark mode enabled.

**Expected behavior**
The white background becomes grey where it is not supposed to be

**Actual behavior**
White background should remain white in the dark mode.

**Screenshots**

**BBB version:**
<img width="1440" alt="Screenshot 2022-11-18 at 7 55 19 PM" src="https://user-images.githubusercontent.com/15665726/202728363-4f634ffb-bbb6-452c-8372-b192bbc8e66f.png">

BigBlueButton continually evolves. Providing the version/build helps us to pinpoint when an issue was introduced.
Example:
$ sudo bbb-conf --check | grep BigBlueButton
BigBlueButton Server 2.2.2 (1816)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, Mac]
 - Browser [e.g. Chrome, Safari]

**Smartphone (please complete the following information):**
 - Browser [e.g. stock browser, Safari]

**Additional context**

**Comment by antobinary** [comment]
Hi @abhinavmohan1 

I just re-tested this on BBB 2.6.0-beta.2 and could not reproduce. Seems it has been resolved.

![Screenshot from 2022-12-14 10-29-10](https://user-images.githubusercontent.com/6312397/207638221-c3d6a7e1-845d-4350-af3f-ebd320dc18b3.png)

Please let us know if you are still able to reproduce it somehow, maybe there's something particular about the document you are uploading that we could look into?
