### ISSUE TITLE
Nginx fails to start after Ubuntu and BBB-Upgrade

### ISSUE THREAD

**Issue by fpaquet** [bigbluebutton/bigbluebutton#16030]
I'm running a BBB 2.6-beta1 installation.
Note that BBB 2.6-alpha3 was runing without any flaws.

After running 'apt update' and 'bbb-install-2.6.sh' nginx fails to start.

● nginx.service - A high performance web server and a reverse proxy server
     Loaded: loaded (/lib/systemd/system/nginx.service; enabled; vendor preset:>
     Active: failed (Result: exit-code) since Sat 2022-11-19 10:59:57 UTC; 17mi>
       Docs: man:nginx(8)
    Process: 797 ExecStartPre=/usr/sbin/nginx -t -q -g daemon on; master_proces>

Nov 19 10:59:57 bbb systemd[1]: Starting A high performance web server and a re>
Nov 19 10:59:57 bbb nginx[797]: nginx: [emerg] zero size shared memory zone "ws>
Nov 19 10:59:57 bbb nginx[797]: nginx: configuration file /etc/nginx/nginx.conf>
Nov 19 10:59:57 bbb systemd[1]: nginx.service: Control process exited, code=exi>
Nov 19 10:59:57 bbb systemd[1]: nginx.service: Failed with result 'exit-code'.
Nov 19 10:59:57 bbb systemd[1]: Failed to start A high performance web server a>

root@bbb:~# nginx -t
nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: [emerg] zero size shared memory zone "ws_zone"
nginx: configuration file /etc/nginx/nginx.conf test failed

---
We found "ws_zone" in /usr/share/bigbluebutton/nginx/bbb-html5.nginx
which is finally included in /etc/nginx/sites-enabled/bigbluebutton

---
root@bbb:~# cat /etc/os-release 
NAME="Ubuntu"
VERSION="20.04.5 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.5 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

---
root@bbb:~# nginx -V
nginx version: nginx/1.18.0 (Ubuntu)
built with OpenSSL 1.1.1f  31 Mar 2020
TLS SNI support enabled
configure arguments: --with-cc-opt='-g -O2 -fdebug-prefix-map=/build/nginx-lUTckl/nginx-1.18.0=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -Wdate-time -D_FORTIFY_SOURCE=2' --with-ld-opt='-Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now -fPIC' --prefix=/usr/share/nginx --conf-path=/etc/nginx/nginx.conf --http-log-path=/var/log/nginx/access.log --error-log-path=/var/log/nginx/error.log --lock-path=/var/lock/nginx.lock --pid-path=/run/nginx.pid --modules-path=/usr/lib/nginx/modules --http-client-body-temp-path=/var/lib/nginx/body --http-fastcgi-temp-path=/var/lib/nginx/fastcgi --http-proxy-temp-path=/var/lib/nginx/proxy --http-scgi-temp-path=/var/lib/nginx/scgi --http-uwsgi-temp-path=/var/lib/nginx/uwsgi --with-debug --with-compat --with-pcre-jit --with-http_ssl_module --with-http_stub_status_module --with-http_realip_module --with-http_auth_request_module --with-http_v2_module --with-http_dav_module --with-http_slice_module --with-threads --with-http_addition_module --with-http_gunzip_module --with-http_gzip_static_module --with-http_image_filter_module=dynamic --with-http_sub_module --with-http_xslt_module=dynamic --with-stream=dynamic --with-stream_ssl_module --with-mail=dynamic --with-mail_ssl_module

**Comment by ffdixon** [comment]
> After running 'apt update' and 'bbb-install-2.6.sh' nginx fails to start.

You can't upgrade with `apt update`.  See 

 https://docs.bigbluebutton.org./2.6/install.html#upgrading-bigbluebutton-26

Try the above and let us know if that gets you going.  Looking forward to your feedback on 2.6-beta.

**Comment by fpaquet** [comment]
Pulled a fresh copy of https://ubuntu.bigbluebutton.org/bbb-install-2.6.sh
output is showing dpkg dependency problems
```
root@bbb:/usr/files/install# ./bbb-install-2.6.sh -v focal-260 -s bbb-test.opag.ch -e mailbox@opag.ch -g -w 
...
Job for nginx.service failed because the control process exited with error code.
See "systemctl status nginx.service" and "journalctl -xe" for details.
invoke-rc.d: initscript nginx, action "start" failed.
● nginx.service - A high performance web server and a reverse proxy server
     Loaded: loaded (/lib/systemd/system/nginx.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Sun 2022-11-20 08:50:43 UTC; 5ms ago
       Docs: man:nginx(8)
    Process: 13564 ExecStartPre=/usr/sbin/nginx -t -q -g daemon on; master_process on; (code=exited, status=1/FAILURE)

Nov 20 08:50:43 bbb systemd[1]: Starting A high performance web server and a reverse proxy server...
Nov 20 08:50:43 bbb nginx[13564]: nginx: [emerg] zero size shared memory zone "ws_zone"
Nov 20 08:50:43 bbb nginx[13564]: nginx: configuration file /etc/nginx/nginx.conf test failed
Nov 20 08:50:43 bbb systemd[1]: nginx.service: Control process exited, code=exited, status=1/FAILURE
Nov 20 08:50:43 bbb systemd[1]: nginx.service: Failed with result 'exit-code'.
Nov 20 08:50:43 bbb systemd[1]: Failed to start A high performance web server and a reverse proxy server.
dpkg: error processing package nginx-core (--configure):
 installed nginx-core package post-installation script subprocess returned error exit status 1
dpkg: dependency problems prevent configuration of nginx:
 nginx depends on nginx-core (<< 1.18.0-0ubuntu1.4.1~) | nginx-full (<< 1.18.0-0ubuntu1.4.1~) | nginx-light (<< 1.18.0-0ubuntu1.4.1~) | nginx-extras (<< 1.18.0-0ubuntu1.4.1~); however:
  Package nginx-core is not configured yet.
  Package nginx-full is not installed.
  Package nginx-light is not installed.
  Package nginx-extras is not installed.
 nginx depends on nginx-core (>= 1.18.0-0ubuntu1.4) | nginx-full (>= 1.18.0-0ubuntu1.4) | nginx-light (>= 1.18.0-0ubuntu1.4) | nginx-extras (>= 1.18.0-0ubuntu1.4); however:
  Package nginx-core is not configured yet.
  Package nginx-full is not installed.
  Package nginx-light is not installed.
  Package nginx-extras is not installed.
...
# Potential problems described below
# Not running:  Nginx
curl: (7) Failed to connect to bbb-test.opag.ch port 443: Connection refused
.curl: (7) Failed to connect to bbb-test.opag.ch port 443: Connection refused
``

**Comment by fpaquet** [comment]
I was able to reinstall nginx using these instructions
https://stackoverflow.com/questions/50599808/nginx-installation-error

Then running bbb-install-2.6.sh again.

Looks much better now

root@bbb:/etc/nginx# systemctl status nginx
● nginx.service - A high performance web server and a reverse proxy server
     Loaded: loaded (/lib/systemd/system/nginx.service; enabled; vendor preset: enabled)
     Active: active (running) since Sun 2022-11-20 09:09:51 UTC; 1min 47s ago

**Comment by fpaquet** [comment]
After fixing ssl certificate errors, bbb 2.6-beta1 and greenlight is running again.
