### ISSUE TITLE
After leaving session the page stuck on loading 

### ISSUE THREAD

**Issue by misisol** [bigbluebutton/bigbluebutton#16031]
After Leaving or ending the session the user stuck on loading screen and does not redirect user to **logoutURL**.
This happens when I've upgraded my server to 2.5.8 version, in other servers with older version this does not happen (2.5.4).

<img width="652" alt="Screen Shot 2022-11-20 at 1 19 57 PM" src="https://user-images.githubusercontent.com/26188869/202896195-73ec32f1-5e4c-404c-923f-a7f5e6c63e0a.png">

In the console log I've found an error :

<img width="493" alt="Screen Shot 2022-11-20 at 1 20 42 PM" src="https://user-images.githubusercontent.com/26188869/202896159-7d0752ff-2b6b-46b5-bc02-87c48e9edcec.png">

CreateUrl :
example.com/bigbluebutton/api/create?name=Meeting&meetingID=a052e645-5edc-3f67-b974-db3c7b968bb8&attendeePW=92f78b0e&moderatorPW=dfd68c23&maxParticipants=83&logoutURL=https://example.com/profile/5c1a10face7b2f749888e76c&record=true&duration=305&meta_capacity=83&meta_meetingpusage=Mmwg9NzADQ&meta_ownerid=5c1a10face7b2f749888e76c&allowStartStopRecording=true&muteOnStart=true&allowModsToUnmuteUsers=true&allowModsToEjectCameras=true&checksum=8b43fffb5efba406e37132e773d4528d050fbxxx

JoinURL :
https://example.com/bigbluebutton/api/join?fullName=%D9%85%D9%87%D8%B1%D8%AF%D8%A7%D8%AF&meetingID=a052e645-5edc-3f67-b974-db3c7b968bb8&password=dfd68c23&userID=0.03529331515988576&avatarURL=https://example.com/profileDefaultPic/5c1a10face7b2f749888e76c&userdata-bbb_listen_only_mode=false&checksum=6ba0dcbf788af6d7302a79f1c15cebebc851a2d7

**Comment by galupa** [comment]
Hi,

I also experienced this issue.
Initially we are not have this issue but after for a while, some users reporting this issue and after a while longer all users having this issue. After restart the issue is gone.

**Comment by dirk-hl** [comment]
I have the same issue with BBB 2.5.9

**Comment by GuiLeme** [comment]
Hey, guys! I tried to reproduce it here, it seems that it has been already solved. Could you please test it again and if it is still happening, maybe record a video on how to reproduce (step-by-step)? 

It would also help a lot if we could see some more logging, maybe from `bbb-apps-akka.service` and `bbb-web.service`, by running`sudo journalctl -u <service>`
