### ISSUE TITLE
XMPP Support

### ISSUE THREAD

**Issue by bigbluebutton-issue-import** [bigbluebutton/bigbluebutton#1604]
Originally reported on Google Code with ID 849

```
Convert the Chat module to work with XMPP. 

This would enable people to log into bigbluebutton chat with their favorite XMPP compatible
chat client, such as OpenFire, GTalk, Pidgin, etc...

```

Reported by `ffdixon` on 2011-02-06 15:30:54

**Comment by heeplr** [comment]
Alternatively to native XMPP support, a bridge could be provided, so no internal BBB code would need to be touched.
There is [Spectrum 2](https://spectrum.im) to provide such bridges. It supports a variety of backends (e.g. libpurple).
This solution has downsides compared to native XMPP support but it's certainly lesse hassle for developers.

While a 3rd party could provide a BBB bridge, official support would be very nice.

**Comment by hex-m** [comment]
related: https://github.com/bigbluebutton/bigbluebutton/issues/1660
