### ISSUE TITLE
2.6.0-beta1: Speaking person tooltip has wrong encoding

### ISSUE THREAD

**Issue by ivanfilatov** [bigbluebutton/bigbluebutton#16058]
**Describe the bug**
When speaking, tooltip of the name of speaking person is shown as "???" if it is initially cyrrilic.
Tooltip for camera, name in the left panel, latin names - all OK.

**To Reproduce**
1. Start conference with the name "Тест"
2. Speak

**Expected behavior**
See "Тест" in the speaking person tooltip

**Actual behavior**
See "????" in the speaking person tooltip

**Screenshots**
[![2022-11-24-11-30-54.png](https://i.postimg.cc/65737BD1/2022-11-24-11-30-54.png)](https://postimg.cc/9rhVKHXG)

**BBB version:**
```
root@vectorconf:~# sudo bbb-conf --check | grep BigBlueButton
BigBlueButton Server 2.6.0-beta.1 (530)
```

**Desktop (please complete the following information):**
Any

**Smartphone (please complete the following information):**
Any

**Comment by MaximKhlobystov** [comment]
I was able to reproduce it on 2.6. The issue doesn't occur for 2.5.
Looks like the issue is with any non-Latin letters (I've tried to use Arabic as well). Also, it is per-character, so the mixed names give you this: "Tэst" -> "T?st".

**Comment by ivanfilatov** [comment]
Yes, sorry for not mentioning this, on 2.5 that was totally fine.

**Comment by MaximKhlobystov** [comment]
Thanks for reporting. Our client team will be looking into it.

**Comment by JoVictorNunes** [comment]
Are you using Greenlight to join meetings?

**Comment by ivanfilatov** [comment]
No, I'm using API from PHP, requests for meeting join are same for 2.5 and 2.6

**Comment by ivanfilatov** [comment]
Request body for meeting create (from local env, but that does not change on prod):
Generated from `\BigBlueButton\BigBlueButton::createMeeting`
```
name=%D0%91%D1%8B%D1%81%D1%82%D1%80%D0%BE%D0%B5+%D1%81%D0%BE%D0%B1%D1%8B%D1%82%D0%B8%D0%B5+2022-11-25+15%3A48&meetingID=8afe7be2-0ef6-4185-a5b7-52f82419f4c6&logoutURL=https%3A%2F%2F{%SERVER_URL%}%2Fmeetings%2F8afe7be2-0ef6-4185-a5b7-52f82419f4c6&record=true&duration=90&autoStartRecording=false&allowStartStopRecording=true&welcome=%D0%A1%D0%BE%D0%B1%D1%8B%D1%82%D0%B8%D0%B5%3A+%3Cb%3E%D0%91%D1%8B%D1%81%D1%82%D1%80%D0%BE%D0%B5+%D1%81%D0%BE%D0%B1%D1%8B%D1%82%D0%B8%D0%B5+2022-11-25+15%3A48%3C%2Fb%3E%3Cbr%2F%3E%0A++++%D0%97%D0%B0%D0%BF%D0%BB%D0%B0%D0%BD%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%BD%D0%BE%D0%B5+%D0%B2%D1%80%D0%B5%D0%BC%D1%8F+%D0%BD%D0%B0%D1%87%D0%B0%D0%BB%D0%B0%3A+%3Cb%3E15%3A48%3C%2Fb%3E%3Cbr%2F%3E%0A++++%D0%9E%D1%80%D0%B3%D0%B0%D0%BD%D0%B8%D0%B7%D0%B0%D1%82%D0%BE%D1%80%3A+%3Cb%3E%D0%98%D0%B2%D0%B0%D0%BD+%D0%A4%D0%B8%D0%BB%D0%B0%D1%82%D0%BE%D0%B2%3C%2Fb%3E&webcamsOnlyForModerator=false&muteOnStart=false&guestPolicy=ALWAYS_ACCEPT&lockSettingsDisableCam=false&lockSettingsDisableMic=false&lockSettingsDisablePrivateChat=false&lockSettingsDisablePublicChat=false&lockSettingsDisableNote=false&lockSettingsHideUserList=false&lockSettingsLockedLayout=false&lockSettingsLockOnJoin=true&lockSettingsLockOnJoinConfigurable=false&allowModsToUnmuteUsers=true&allowModsToEjectCameras=true&learningDashboardEnabled=false&endWhenNoModeratorDelayInMinutes=15&breakoutRoomsEnabled=false&breakoutRoomsRecord=false&breakoutRoomsPrivateChatEnabled=false&endWhenNoModerator=true&meetingKeepEvents=true&meetingLayout=SMART_LAYOUT&meta_endCallbackUrl=https%3A%2F%2F{%SERVER_URL%}%2Fapi%2Fv1%2Fmeetings%2F8afe7be2-0ef6-4185-a5b7-52f82419f4c6%2Fcallbacks%2Fend%2Fbdce0b98a77afa5db3e389c7d86fc181&meta_bbb-recording-ready-url=https%3A%2F%2F{%SERVER_URL%}%2Fapi%2Fv1%2Fmeetings%2F8afe7be2-0ef6-4185-a5b7-52f82419f4c6%2Fcallbacks%2Frecording-ready%2Fbdce0b98a77afa5db3e389c7d86fc181
```

Redirect url example for joining:
Generated from `\BigBlueButton\BigBlueButton::getJoinMeetingURL`
```
https://{%SERVER_URL%}/bigbluebutton/api/join?meetingID=8afe7be2-0ef6-4185-a5b7-52f82419f4c6&fullName=%D0%98%D0%B2%D0%B0%D0%BD+%D0%A4%D0%B8%D0%BB%D0%B0%D1%82%D0%BE%D0%B2&password={%MODERATOR_PASSWORD%}&userID=4&redirect=true&checksum=1c4057e535018bfcc2040e0a340cccc4420566d0
```

Using `"bigbluebutton/bigbluebutton-api-php": "2.1.3"`

Can provide more information if that helps.

**Comment by JoVictorNunes** [comment]
Thanks @ivanfilatov!
