### ISSUE TITLE
Create an Android client for BigBlueButton.

### ISSUE THREAD

**Issue by bigbluebutton-issue-import** [bigbluebutton/bigbluebutton#1606]
Originally reported on Google Code with ID 851

```
Create a native Android client for BigBlueButton
```

Reported by `ffdixon` on 2011-02-06 15:34:46

**Comment by NSR88** [comment]
> ```
> Closing as this is done by the MConf project.
> ```
> 
> Reported by `ritzalam` on 2011-09-23 13:29:00
> 
> * **Status changed**: `Done`

Is it really done? It doesn't seem so.
https://play.google.com/store/apps/details?id=org.mconf.android.bbbandroid not found :(

**Comment by matiasilva** [comment]
Hi, as you can see by the date this is long expired. I suggest you have a read in the forums about the discussion that came out of producing an Android app.

**Comment by adam-op** [comment]
@matiasilva please share "the forums" discussions that you would like to share here, because I could tell you that there is NO discussion else than this issue in github

**Comment by astrojuanlu** [comment]
Opened gh-15908.
