### ISSUE TITLE
Webcam backgrounds crash the entire client on FireFox

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#16065]
**Describe the bug**
I cannot share webcam on FireFox as there is a crash every time I try to share webcam, specifically it seems to be in the preview step, when looking to obtain the backgrounds.

**To Reproduce**
1. Using FireFox join a meeting
2. Click on sharing webcam
3. Give browser level permission to grant access to the webcam

**Expected behavior**
The webcam sharing preview modal shows up

**Actual behavior**
The client crashes, see screenshots

**Screenshots**
Chrome:
![Screenshot from 2022-11-29 10-13-25](https://user-images.githubusercontent.com/6312397/204567449-1c685a5b-512a-47dd-a21a-3e166d5ab4bc.png)

FireFox:
![Screenshot from 2022-11-29 10-06-23](https://user-images.githubusercontent.com/6312397/204567484-eb4e5f7a-291e-4d05-b953-0d26a30656cf.png)

![Screenshot from 2022-11-29 10-06-49](https://user-images.githubusercontent.com/6312397/204567518-ea3cf667-6e8b-4dc1-87dc-262056fbe5b1.png)

**BBB version:**
BigBlueButton 2.6.0-beta.1 but also on the current latest build 233

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser [e.g. FireFox]
 - Version [e.g. 107.0]

**Additional context**

**Comment by antobinary** [comment]
May be resolved via #15919 ?!

**Comment by JoVictorNunes** [comment]
> May be resolved via #15919 ?!

I don't think so. It's related to something else. Just sent a fix https://github.com/bigbluebutton/bigbluebutton/pull/16090.
