### ISSUE TITLE
Create a native Objective-C client for the iPhone or iPad

### ISSUE THREAD

**Issue by bigbluebutton-issue-import** [bigbluebutton/bigbluebutton#1607]
Originally reported on Google Code with ID 852

```
Create a native Objective-C client for the iPhone or iPad that would enable the user
to participate in a live BigBlueButton session. 

There would be two levels of participation: view only and full participation.
```

Reported by `ffdixon` on 2011-02-06 15:35:54

**Comment by ffdixon** [comment]
Marking as won't do as Apple now has support for WebRTC in Safari as of iSO 11 (thanks Apple!!).  You can try out the latest build of the HTML5 client at https://test.bigbluebutton.org/ (with iOS).
