### ISSUE TITLE
Docs: switched entry in config file overrides

### ISSUE THREAD

**Issue by debuglevel** [bigbluebutton/bigbluebutton#16084]
Could not find where the docs are stored; would have been an PR otherwise.

![image](https://user-images.githubusercontent.com/2401265/205087159-672cee00-b113-4e68-b0b2-e82c4c7bd893.png)

**Comment by ffdixon** [comment]
You can send the PR here: https://github.com/bigbluebutton/bigbluebutton.github.io

**Comment by debuglevel** [comment]
Done: https://github.com/bigbluebutton/bigbluebutton.github.io/pull/466

github somehow did not find it in global and organizational code search.
