### ISSUE TITLE
Confirmation dialog for removing a user has incorrect text

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#16092]
On the latest build of 2.6-dev, when clicking a user's name to remove them from the meeting, the confirmation dialog displays "End session for all users"

<img width="765" alt="image" src="https://user-images.githubusercontent.com/290351/205875501-04511556-1d18-4cfa-aa34-70a39549ab05.png">

The operation is correct, but the label is not.

**Comment by ramonlsouza** [comment]
fixed by #16069
