### ISSUE TITLE
Add setting to enable user to not view a webcam

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#16114]
**Is your feature request related to a problem? Please describe.**
For meetings/classes that rely heavily on webcams, a suer can reduce fatigue by hiding their own webcam view.  

**Describe the solution you'd like**
While BigBlueButton focuses on the virtual classroom), video is an important part of the experience.  However, staring at your own webcam for long periods of time can cause fatigue ("zoom fatigue").  

Give the user the ability to hide viewing their own webcam, but still broadcast it to others.

When a user clicks on the drop-down menu when viewing their webcam

<img width="236" alt="image" src="https://user-images.githubusercontent.com/290351/206896315-79caae4f-7270-41e3-ab53-24ccd9390595.png">

Add a new option "Disable self-view".   This will change the webcam tile to show the text "Self-view disabled" for the user, but all other participants will still receive the webcam stream.  

Clicking the drop down again will show the option "enable self-view" and choosing it will show the user their webcam again.

**Additional improvements**

We could enhance this by taking the last frame of the video, blurring it, dimming it, and using it as the background for the text "Self-view disabled".

We could further enhance this by adding it as an option in the Settings menu

<img width="682" alt="image" src="https://user-images.githubusercontent.com/290351/206896599-1cc0b076-e4b0-4929-b13a-fa510666107a.png">

with the text "Self viewing of webcam" with the options true/false

Having it in the settings would enable sites that use the [cluster proxy setup](https://docs.bigbluebutton.org./admin/clusterproxy.html) to store this preference for the user.

**Comment by tfardet** [comment]
Agree, I have received feedback that this really increases fatigue for some users and makes them unwilling to use BBB compared to other software.
For some, it even seems to prevent them from focusing properly on what is being discussed so it seems this could be a significant benefit in terms of accessibility.

**Comment by ffdixon** [comment]
This feature could be generalized so a user could turn off any webcam.

**Comment by AlphaDE** [comment]
This feature is requested for quite some time

#10709 opened on Oct 23, 2020 by MateMatiker
#11990 opened on Apr 12, 2021 by bersace
