### ISSUE TITLE
After moving a student to a different breakout room, close the obsolete tab

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#16119]
**Describe the bug**
When you move a viewer from breakout roomA to breakout roomB, the viewer will be stuck seeing 

**To Reproduce**
1. Join a meeting as a moderator M
2. Join the meeting as a viewer V
3. M starts a breakout session and puts V in room1
4. V joins room1 (it opens in a new tab)
5. M selects Manage users from the breakouts 3 dot menu and moves V from room1 to room2

**Expected behavior**
V is joining room2, no longer seeing room1.

**Actual behavior**
V is actually stuck seeing a 403 screen that it was removed from the meeting. The user is supposed to notice that **the tab can be closed** and in the main room V is getting invited to room2

Can we close the tab for room1 automatically?

**Screenshots**
![Screenshot from 2022-12-12 16-18-52](https://user-images.githubusercontent.com/6312397/207156884-a65512ca-5b63-489c-85b4-85e0e8e1d11d.png)

**BBB version:**
BigBlueButton 2.6.0-beta.2

**Comment by antobinary** [comment]
As an aside, if we move the user before the client finishes loading, the client breaks

![Screenshot from 2022-12-12 16-16-03](https://user-images.githubusercontent.com/6312397/207158351-bded743c-fe18-4587-a23f-4af4900312d0.png)

**Comment by gustavotrott** [comment]
Since #16492 the breakout-room window will be closed automatically when the user is moved!
