### ISSUE TITLE
Breakouts - if you force end the rooms, you can't start a new batch

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#16118]
**Describe the bug**

**To Reproduce**
1. Join a meeting as a moderator
2. Start breakouts
3. End the breakouts using the 3-dot menu in the breakouts panel
4. Try to start a new batch of breakouts

**Expected behavior**
You see the menu to start breakouts
![Screenshot from 2022-12-12 15-49-53](https://user-images.githubusercontent.com/6312397/207151811-4e1acd28-e6e7-4a09-a5e8-7bb7c2067aff.png)

**Actual behavior**
You don't see the menu to start new breakouts
![Screenshot from 2022-12-12 15-59-50](https://user-images.githubusercontent.com/6312397/207153346-629b92e3-abc9-4bc2-95f5-e7bf5bb51cb7.png)

**Screenshots**

**BBB version:**
BigBlueButton 2.6.0-beta.2

**Additional context**
- It might be a race condition as I have been repeating the flow of events relatively fast.
- refreshing the page and opening the gear icon menu resolves the problem
- It does not always happen... I tried to record this on video but it's eluding me

**Comment by GuiLeme** [comment]
This issue seems to be resolved by #16467, and it is closely related to #15756
