### ISSUE TITLE
Problem with Big Blue & cPanel on ubuntu 20.04

### ISSUE THREAD

**Issue by iam4linb** [bigbluebutton/bigbluebutton#16126]
Dears, 
I hope all is well
I have a problem with cPanel and Big Blue on ubuntu 20.04

When I wanted to Install big blue on the server I faced this error:

N: Skipping acquire of configured file 'nginx/binary-i386/Packages' as repository 'http://nginx.org/packages/ubuntu focal InRelease' doesn't support architecture 'i386'
Warning: apt-key output should not be parsed (stdout is not a terminal)
You must uninstall the Apache2 server first

----
It said to uninstall Apache2, but I want to use cPanel too!

Is there any way to fix this issue?

Appreciated your help

**Comment by iam4linb** [comment]
Hi, Thank You @antobinary 


for BBB machine?
or
for cPanel?

If for BBB Machine you mean, Would you please guide me on How can I change alternatives for my webserver location?
Because I install cPanel in HOME ROOT


Thank You

**Comment by antobinary** [comment]
I did a quick search "cpanel" in the setup group I linked to.

People have asked similar questions, from the few threads I checked, none had proceeded with cpanel on the same box as BBB. This response seemed like it carried some value: https://groups.google.com/g/bigbluebutton-setup/c/zmkRLBELUFc/m/yz4A-QgQAgAJ

**Comment by hostbbb** [comment]
is i386 32bit :)

**Comment by ffdixon** [comment]
Yes.  On a DigitalOcean Ubuntu 20.04 server, for example, `uname -a` outputs

```
 5.4.0-122-generic #138-Ubuntu SMP Wed Jun 22 15:00:31 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

`bbb-install.sh` checks for x86_64

```
need_x64() {
  UNAME=`uname -m`
  if [ "$UNAME" != "x86_64" ]; then err "You must run this command on a 64-bit server."; fi
}
```

so I'm surprised the installer even ran.
