### ISSUE TITLE
Export breakout shared notes only if there is content inside

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#16135]
**Describe the bug**
We currently also export shared notes from breakouts where nobody joined and also rooms where people never used the shared notes.

**More:**
Perhaps we need a way to inform why Room3 has no content exported (because nobody used it?) -- Ideas are welcome

**BBB version:**
BigBlueButton 2.6.0-beta.3

**Comment by gustavotrott** [comment]
Addressed in #16421
