### ISSUE TITLE
Sticky notes are giant on portrait view slides

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#16145]
**Describe the bug**

**To Reproduce**
1. Start a meeting
2. add a sticky note on the default presentation (landscape)
3. Upload a portrait presentation
4. add a sticky note and notice its size

**Expected behavior**
The default size for sticky notes should not vary too much

**Actual behavior**
On portrait the default sticky notes are ~ 4x the area

**Screenshots**
Landscape
![Screenshot from 2022-12-15 11-21-21](https://user-images.githubusercontent.com/6312397/207919460-013c97ea-b79e-41b1-964c-c3e008f03373.png)

Portrait
![Screenshot from 2022-12-15 11-43-14](https://user-images.githubusercontent.com/6312397/207919427-9006cad0-187c-4d22-8eae-3643bb5c23e3.png)

**BBB version:**
BigBlueButton 2.6.0-beta.3
1920p monitor

**Comment by ffdixon** [comment]
Looking at https://github.com/bigbluebutton/bigbluebutton/pull/16169, would it address this issue?
