### ISSUE TITLE
[2.5/2.6] Mute users/unmute meeting UI has confusing behaviour

### ISSUE THREAD

**Issue by schrd** [bigbluebutton/bigbluebutton#16150]
**Describe the bug**
When a moderator uses the mute participants or mute participants except presenter function, the behaviour is a bit confusing. Users can unmute them selves (this is ok and expected). However the menu item changes to "turn off meeting mute" which actually has no effect. This is also good that participants mute status is **not** restored. If BBB unmuted participants this would be a violation of the GDPR.

**To Reproduce**
1. Join as moderator
2. Click on the gear next to the users list
3. Click on 'mute all users'
4. click on the gear next to the users list
5. Click on 'turn off meeting mute'
6. nothing changes in the audio state of the meeting

**Expected behavior**
I'd propose to get rid of the "turn off meeting mute" function. Instead I'd propose to leave the option to mute people again who have unmuted themselves. This makes this option a quick solution for the moderator to get silence. Lock settings are still required.

**BBB version:**
Any BBB Version 2.5 or 26 up to commit ID 84e6ba2d408bf364d428c8e3c7a044cbeab7228b I did not test on 2.4, it is likely also affected.

**Comment by FreeScholar** [comment]
Take a look at the LOCK viewers under the gear. I believe it works in conjunction with the LOCK.
If you mute all users and then lock viewers, they cannot unmute and I think that is when you may want to turn off meeting mute.
