### ISSUE TITLE
[2.6] poll results missing in exported presentation

### ISSUE THREAD

**Issue by schrd** [bigbluebutton/bigbluebutton#16151]
**Describe the bug**

**To Reproduce**
1. create a poll
2. publish result
3. publish presentation to chat
4. no poll results are included in the PDF

**Expected behavior**
I'd like to have all annotations in the exported document.

**BBB version:**
tested on BBB 2.6 beta2 and 2.6 beta commit 84e6ba2d408bf364d428c8e3c7a044cbeab7228b

**Comment by antobinary** [comment]
Thanks for reporting @schrd !
@danielpetri1 Perhaps we just need to listen for the poll result as an annotation event?

**Comment by danielpetri1** [comment]
Hi @schrd, thanks for reporting this. Could reproduce it as well.
The poll result used to be a text shape like any other, but now it seems like an object describing the poll is passed instead. Looking into this.

**Comment by antobinary** [comment]
Tested on 2.6.0-beta.4 (after #16175 ) and it worked correctly 
![Screenshot from 2022-12-30 13-31-31](https://user-images.githubusercontent.com/6312397/210101840-a5458ff3-ab80-4b8a-af4d-9bd89e78bb5d.png)
