### ISSUE TITLE
Two participants are unable to hear each other

### ISSUE THREAD

**Issue by MBM1607** [bigbluebutton/bigbluebutton#16157]
## Explanation
We run a BigBlueButton instance for our tutoring platform. We have a pair of users, a tutor and a student that are unable to hear each other.

This is a very weird case, all other participants are able to hear both of them and they are able to hear other participants as well.

We had both of them connect with us in different classrooms to verify that issue is not with their devices and separately they can talk and hear fine.

Even in their own class, they are able to hear each other fine for the first 10-15 mins and then they stop being able to hear each other.

### Notice
I apologize for the vagueness and lack of steps to reproduce the issue but that is where I am stuck. The issue is not reproducible by us.

**Comment by FreeScholar** [comment]
I feel your pain - never happened to me, but I am happy to be called on to troubleshoot this oddity with you, or setup a time you could ask these users to log on to my BBB instance, or you can test yourself on my instance in the demo room which allows admin access etc. at http://communitybridge.com/demo - micky@agaric.coop

**Comment by ffdixon** [comment]
You didn't mention what version you were running, but assuming it's 2.5, can you try it with 

  https://demo.bigbluebutton.org/

and let us know if you encounter the same issue.  This is running 2.6-beta-2.  We'd be (very) interested to hear if you can reproduce the issue there.

**Comment by MBM1607** [comment]
Hi Everyone.,

The version was 2.5. The participants are no longer facing the issue. 

We made no changes so we have come to the conclusion that the student didn't want to continue the classes and was trying to find an easy way out. Closing the issue thank you for your helpful replies.
