### ISSUE TITLE
The presentation pane is not in recording with prev packages

### ISSUE THREAD

**Issue by cod3r0k** [bigbluebutton/bigbluebutton#16167]
What's happened in BBB 2.6?
I think the presentation section is changed and other packages which work before are corrupted!

I record a video and it is fine in the playback, but I want to download it (Before I found bbb-video-download package and it is fine up to bbb 2.5) and the prev package is not properly working. Could you help me by downloading a video of the session plan or say some tips for enhancing BBB-video-download package to deal with this problem?
![image](https://user-images.githubusercontent.com/36899025/208155808-e6312a77-3015-4a62-b1ad-4c685962d84a.png)

Thanks

**Comment by antobinary** [comment]
Hi @cod3r0k 

Could you please fill out the template for filing an issue. I am not sure what you are describing and the png is not helping all that much. I assume you're enabling some recording format but more info will certainly help!

**Comment by cod3r0k** [comment]
> Hi @cod3r0k
> 
> Could you please fill out the template for filing an issue. I am not sure what you are describing and the png is not helping all that much. I assume you're enabling some recording format but more info will certainly help!

Dear @antobinary 
Thanks for your comment. I explain it again with the template below:

**Describe the bug**
I use https://github.com/tilmanmoser/bbb-video-download tools for downloading videos of BBB. It was working until I upgraded to BBB 2.6.0-beta3. I recorded a video in BBB and after the session, I saw the playback video in good quality. But unfortunately, the video which was rendered and produced in mp4 in bbb-video-downlod tools corrupted anything which I wrote on the slides or whiteboard (presentation pane). Therefore, I write this issue and hope it is fixed ASAP.
I think the changes in the whiteboard in BBB 2.6 may affect this issue. 

**To Reproduce**
Steps to reproduce the behavior:
1. Record a video in BBB
2. See the playback after the session and it was very well.
3. See the result of bbb-download-video tools for producing mp4 and you can see that whenever you wrote anything in the whiteboard, you see the below image: 
![image](https://user-images.githubusercontent.com/36899025/208228443-15ba8be1-b00f-4509-8165-48ca5ef3a20d.png)
But it worked for bbb 2.5 and previous versions

**Comment by ffdixon** [comment]
> I use https://github.com/tilmanmoser/bbb-video-download 

This recording format is not provided the core developers of BigBlueButton.

We've had alphas/betas of BigBlueButton 2.6 available for a few months now, so hopefully the developer of the above recoding format can support and update it for 2.6.

Alternatively we are also working on a new recording format for 2.6 to provide a recording as a downloadable .mp4 file.  This will be build-into the core of BigBlueButton and supported by the core developers.  See

  https://docs.bigbluebutton.org./2.6/new.html#recording-in-mp4-format
