### ISSUE TITLE
  [2.6-beta3] autoSwapLayout=true does not cause that the default presentation is hidden

### ISSUE THREAD

**Issue by mwuttke** [bigbluebutton/bigbluebutton#16257]
**Describe the bug**
The configuration autoSwapLayout=true in the bbb-html5.yml override file does not cause that the default presentation will be hidden at the beginning of a session.

**To Reproduce**
1. Configure autoSwapLayout: true (and restoreOnUpdate: true) in bbb-html5.yml
2. Start a session with 2 participants (a moderator and a viewer).
3. The presentation is not hidden at the beginning for all participants.

**Expected behavior**
The presentation is hidden at the beginning for all participants.

**Actual behavior**
The presentation is not hidden at the beginning for all participants.

**BBB version:**
BigBlueButton Server 2.6.0-beta3

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Firefox
 - Version: 108

**Additional context**
With this parameter, hiding the presentation worked in the BBB old versions (2.4.x & 2.5.x).

**Comment by ramonlsouza** [comment]
`autoSwapLayout` has been removed in 2.6. 
To start a meeting in 2.6 with the default presentation hidden, set `hidePresentation: true` instead.
