### ISSUE TITLE
Breakout room's client crashes when you move yourself to another room.

### ISSUE THREAD

**Issue by MaximKhlobystov** [bigbluebutton/bigbluebutton#16284]
**Describe the bug**
When you have joined a breakout room and move yourself to another room, your breakout room's client crashes.

**To Reproduce**
1. Create breakout rooms.
2. Join a breakout room.
3. Moderator yourself to another room using "Update Breakout Rooms" modal.

**Expected behavior**
Breakout room's client should show the text notifying about being removed from the room.

**Actual behavior**
Your client that's in the breakout room crashes.

**Screenshots**
<img width="288" alt="crash" src="https://user-images.githubusercontent.com/5004762/209221120-f2029f79-60f0-49f0-9e87-72380227c90d.PNG">

**BBB version:**
2.6.0-beta.4

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Firefox
 - Version: 108.0.1

**Comment by gustavotrott** [comment]
Since #16492 the breakout-room window will be closed automatically when the user is moved!
