### ISSUE TITLE
Screenshare not shown in Firefox on Linux when joining after the screenshare started

### ISSUE THREAD

**Issue by jens-br** [bigbluebutton/bigbluebutton#16281]
**Describe the bug**
Using Firefox (Linux), a screenshare will not be shown by default when one joins a BBB session where the screenshare has already started before.

**To Reproduce**
1. Open a BBB session.
2. Let another person/profile join, using Firefox on Linux.
3. See the problem: The screenshare is not shown for the joining user until thew user clicks on the button to restore the presentation. This is highly confusing for users, either not knowing what people were talking about ot simply assuming BBB was broken.

**Expected behavior**
An already running screenshare should be shown to all users.

**Actual behavior**
An already running screenshare is currently not shown to all users (those with Firefox on Linux).

**Screenshots**
-

**BBB version:**
```
Copyright: ©2022 BigBlueButton Inc.
Clientversion: BigBlueButton Server 2.5.8 (269), HTML5Client git.
BigBlueButton Version: 2.5.8
```

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Firefox
 - Version: at least 108.0.1, but other ones are likely to be affected, too

**Smartphone (please complete the following information):**
not tested

**Additional context**
Firefox on Windows is interestingly not affected, as it seems... Vivaldi 5.6 (= Chromium 108) isn't affected (on both plattforms).

**Comment by schrd** [comment]
did you configure a TURN server? And did you set to `public.kurento.forceRelayOnFirefox` option to true in `/etc/bigbluebutton/bbb-html5.yml`? Firefox has a Bug in their ICE implementation which likely causes that problem. See https://bugzilla.mozilla.org/show_bug.cgi?id=1034964

The workaround is to force firefox to use a TURN server.

**Comment by jens-br** [comment]
Hi, sorry for the very late reply. Thank you for your answer!
Unfortunately I have no access to the setup and I don't have any more information in the meantime.
As the problem has stopped for now, I would wait and see. It might be that the server administrators simply added the TURN server.
Otherwise, I would simply re-open this issue again.
Thanks again and sorry for any inconvenience!
