### ISSUE TITLE
Non alphabet name fails when full audio bridge is on

### ISSUE THREAD

**Issue by hiroshisuga** [bigbluebutton/bigbluebutton#16303]
**Describe the bug**
According to https://docs.bigbluebutton.org/2.5/new.html#experimental, you can turn on an experimental function which enables full audio bridge with mediasoup. But this turns a non-alphabet name into ???? on the client. 

**To Reproduce**
1. Turn on the experimental full audio bridge according to the instruction above (I added parameters on bbb-html5.yml, which is the second way to enable the function)
2. Join audio with a non-alphabet name
3. Talk something and see the speaker badge is just "????"
4. When the parameters on bbb-html5.yml are commented out (but the fullAudioEnabled: true flag in bbb-webrtc-sfu’s configuration is still there), the non-alphabet names are shown correctly.

**Expected behavior**
Non alphabet name should also appear correctly.

**Actual behavior**
It shows "????"

**Screenshots**
In Japanese:
![jpn](https://user-images.githubusercontent.com/45039819/209342593-d16d1071-aa57-4f60-bf37-ce59585f8b1d.gif)
In Thai:
![tai](https://user-images.githubusercontent.com/45039819/209342616-e97c4d0d-3751-4155-962d-38217cc16db3.gif)
In alphabet:
![alp](https://user-images.githubusercontent.com/45039819/209342644-42d8483b-81ed-4e89-b77c-eaa4c0d1ef5c.gif)

**BBB version:**
2.6.0 beta1

**Desktop (please complete the following information):**
 - OS: I tested Windows10
 - Browser: I only tested Chrome on PC

**Additional context**
This is possibly my local problem. But I cannot test it more. Thus I post it.

**Comment by antobinary** [comment]
Hi @hiroshisuga !
This looks like a dupicate of https://github.com/bigbluebutton/bigbluebutton/issues/16058 but on BBB 2.5

Are you able to reproduce this same issue on BBB 2.6.0-beta.4+ (using the same name)? - it should not be possible after our patch https://github.com/bigbluebutton/bigbluebutton/pull/16094/files 

If you confirm it fixed on 2.6, we can try to port it to BBB 2.5

**Comment by hiroshisuga** [comment]
@antobinary you are right. I missed that issue. I will take a look again once I upgrade my server to 2.6.0b4. For now I have something else that I want to test on beta1. Until then I close the issue.

**Comment by hiroshisuga** [comment]
I confirmed the problem solved on 2.6.0b4. Sorry for the confusion.

**Comment by ffdixon** [comment]
Thanks for confirming.
