### ISSUE TITLE
Speechbrain integration with BBB

### ISSUE THREAD

**Issue by majesh1210** [bigbluebutton/bigbluebutton#16349]
Hi Team

Hope you are doing great.

The place where I live has a lot of noise issues, and as a result, the audio recorded has a lot of noise.

I have tested speechbrain for audio and it perfectly removes audio. (In batch mode)

I would like to integrate spechbrain woth Bigbluebutton ie process the 
Audio (using speechbrain to remove noise) that BBB captures from mic before delivering to audience  in realtime

Could you please tell me which component I would have to edit in BBB 
to achieve this.

Thanks and Merry christmas

**Comment by ffdixon** [comment]
> that BBB captures from mic before delivering to audience in realtime 

The best approach would be a webassembly-based solution, similar to what we are doing today with background blurring.
