### ISSUE TITLE
tldraw: cannot select multiple objects

### ISSUE THREAD

**Issue by vasylOstrovskyi** [bigbluebutton/bigbluebutton#16356]
**Describe the bug**
A very useful function of the original tl;draw is a possibility to select several objects and then, e.g., move them. Unfortunately, this function is missing in the BBB whiteboard.

**To Reproduce**
1. Start BBB 2.6 session
2. Add some drawings
3. Choose Select tool, press left button and move the mouse 

**Expected behavior**
A rectangular frame should appear, highlighting all objects inside it (original tldraw behaviour)

**Actual behavior**
Nothing happens

**BBB version:**
BigBlueButton Server 2.6.0-beta.4 (647) client build: 273

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Browser Chrome, Firefox
 
Regards,
 Vasyl

**Comment by antobinary** [comment]
Hi @vasylOstrovskyi ,

I was going to comment that we have this.. but I am not able to find the exact key combination. I believe I've seen it as ctrl+left click.

- [ ] let's include the select method to the Whiteboard key shortcuts

**Comment by ramonlsouza** [comment]
Fixed by #16454, should work the same as in [tldraw.com](https://www.tldraw.com/) now
