### ISSUE TITLE
Switching to generated presentation after capturing breakout room's whiteboard annotations

### ISSUE THREAD

**Issue by MaximKhlobystov** [bigbluebutton/bigbluebutton#16368]
**Describe the bug**
Sometimes, it doesn't allow you to switch to a generated presentation (that includes annotations) after ending the breakout rooms that had capturing whiteboard annotations enabled.

**To Reproduce**
1. Join a meeting with a moderator and an attendee.
2. Moderator: create breakout rooms with the capturing of whiteboard annotations enabled.
3. Attendee: join a breakout room and add annotations to the whiteboard.
4. Moderator: end all breakout rooms, see the notification about generated presentations.
5. Moderator: try to switch to the newly generated presentations.

**Expected behavior**
Moderator should be able to switch to the newly generated presentation and see annotations from the breakout room.

**Actual behavior**
Moderator isn't able to switch to the newly generated presentations.

**GIF**
![annotations](https://user-images.githubusercontent.com/5004762/210118980-904d73dc-d9f4-4b47-983d-324db3f99b84.gif)

**BBB version:**
BigBlueButton Server 2.6.0-beta.4

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Firefox
 - Browser version: 108.0.1

**Comment by gustavotrott** [comment]
Fixed in #16495
