### ISSUE TITLE
Free BBB for music and musicians

### ISSUE THREAD

**Issue by cgruber-uos** [bigbluebutton/bigbluebutton#16386]
You may have noticed some troubles by using BBB in **music lessons** or as fast and easy way to support **distance instrumental lessons**. This is not so surprising because the technology behind videoconferences telephone calls is **optimized for speech**. So a pianissimo part of a violin could be easily suppressed as noise and so on. So the question is: Can we adjust the default audio settings in a way that audio quality will get better for music? 

Zoom has for this requirement a feature called ["original sound for musicians"](https://support.zoom.us/hc/en-us/articles/115003279466-Using-original-sound-for-musicians-in-a-meeting), what effects the echo cancellation and other audio filters., they say. 

Lars / @lkiesow wrote a script for the music department of the University Osnabrück to change some audio settings and make it so better for music content. For testing you can execute it in the browser console (Shift + CTRL + K), after you have started a BBB meeting. Just some JavaScript line of code: 

```JavaScript
_getUserMedia = navigator.mediaDevices.getUserMedia;
navigator.mediaDevices.getUserMedia = function() {
  if (arguments[0] && arguments[0].audio) {
    if (arguments[0].audio === true) {
      arguments[0].audio = {};
    }
    arguments[0].audio.echoCancellation = false;
    arguments[0].audio.noiseSuppression = false;
    arguments[0].audio.autoGainControl = false;
    arguments[0].audio.mozNoiseSuppression = false;
    arguments[0].audio.mozAutoGainControl = false;
  }
  return _getUserMedia.apply(this, arguments);
}
```

But first let's have some ears at a BBB recording I did with the default audio settings and the modified settings: Please open the video description to jump easily to the **two different conditions** one is **speech settings** the other **music settings**. 

[![Comparison BigBlueButton audio settings for music](https://user-images.githubusercontent.com/101632236/210554639-3606bd4b-004c-4dbe-91a9-70e7313eae57.png)](https://www.youtube.com/watch?v=HZUaNFf1QPg)

I would have expected a clearer difference between this two conditions. Some tracks sound nearly the same, some better, some are overamplify in the "better" settings. 

We have disabled the filters / auto settings for echo cancellation, noise suppression, gain control. Any proposal to test again with other settings? 

In case we have a got set of "music filters" we could add a button or setting option to activate or deactivate it easily via UI and not so complicate by the console.

**Comment by cgruber-uos** [comment]
Lars / @lkiesow told me that my interaction with BBB and executing the JS was wrong, so I assume that no filter / no change was applied. :-(( The right way would be: 

- start BBB
- **do NOT start audio!!**
- run the script
- only now start audio

So the good thing is, that we have a chance to get better audio output with the filter changes and the bad thing is that the second part of the video is useless and I have to do it again. But that's a reason to make such thing "user-proof" and error tolerant via a UI! :-)

**Comment by lkiesow** [comment]
This is a simple example of how to run the script with a test similar to what Clemens did:

https://user-images.githubusercontent.com/1008395/210600354-cd58bc2d-0044-4e91-b061-8524e3aba79e.mp4

The script modifies the audio device settings when you share the audio device. This means that you need to re-share the device after you run the script or you will still be running with the old settings.

**Comment by hostbbb** [comment]
Neat,  there are some settings similar in client already to turn echo./noise i think.

![image](https://user-images.githubusercontent.com/519542/210602887-438b4dcd-cb0e-450b-8c65-ab88afe842bc.png)

would ne neat to compare and add the ones missing for music,

also, we have manually configured kurento listenonly to play stereo in past.  would be neat to see if media soup can broadcast stereo to browser @prlanzarin would know those specifics.

**Comment by lkiesow** [comment]
Seems like the new setting does more or less what my script does:

https://github.com/bigbluebutton/bigbluebutton/blob/080fd3e86d7c30b18bee42870f97a3131f1777c5/bigbluebutton-html5/imports/ui/components/settings/submenus/application/component.jsx#L202-L206

The Mozilla specific settings are missing, but it might as well be that these are no longer relevant. It's been over two years since I wrote that after all. Having a description of hat audio filters are being en-/disabled would probably be nice though.

**Comment by prlanzarin** [comment]
>  I'm wondering if this would automatically re-share the audio though…

BBB's built-in audio filter toggle won't re-share audio. It transparently reapplies constraints in Firefox/Safari, and Chrome runs a getUserMedia + stream replacement which is also - generally - transparent.

That toggle is a 2.4 feature. Please check whether it is sufficient since it was introduced partially for the reasons discussed here - if it isn't, we can extend it.

**Comment by prlanzarin** [comment]
> also, we have manually configured kurento listenonly to play stereo in past. would be neat to see if media soup can broadcast stereo to browser @prlanzarin would know those specifics.

Yeah, stereo should work in that scenario as well. We need to standardize stereo configurations in SFU-based audio, though - or at least properly document it.

**Comment by cgruber-uos** [comment]
In sense of "Baby One More Time" [https://www.youtube.com/watch?v=C-u5W...](https://www.youtube.com/watch?v=C-u5WLJ9Yk4) ... again:

[![Comparison BigBlueButton audio settings for music, 2nd trial](https://user-images.githubusercontent.com/101632236/210652716-fc85598d-bae7-4d08-b3a1-42abcea58359.png)](https://www.youtube.com/watch?v=5z_svWHS6f8)

Use the timestamp based links in the video description to navigate fast and have a direct comparison. 

Now with three runs: 
- speech settings
- Lars' music settings
- and BBB audio filters disabled

**Comment by hostbbb** [comment]
2.6 freeswitch opus settings.

root@live102:/opt/freeswitch/conf/autoload_configs# cat opus.conf.xml
<configuration name="opus.conf">
   <settings>
      <param name="use-vbr" value="1" />
      <param name="use-dtx" value="0" />
      <param name="complexity" value="10" />
      <param name="packet-loss-percent" value="15" />
      <param name="keep-fec-enabled" value="1" />
      <param name="use-jb-lookahead" value="1" />
      <param name="advertise-useinbandfec" value="1" />
      <param name="maxaveragebitrate" value="64000" />
      <param name="maxplaybackrate" value="48000" />
      <param name="sprop-maxcapturerate" value="48000" />
      <param name="adjust-bitrate" value="1" />
      <param name="negotiate-bitrate" value="1" />
   </settings>
</configuration>

some recommendations worth trying for music,

https://wiki.xiph.org/Opus_Recommended_Settings
