### ISSUE TITLE
Userlist resize problem in RTL

### ISSUE THREAD

**Issue by misisol** [bigbluebutton/bigbluebutton#16384]
When you resize the user list by decreasing the size, after increasing the user list width is not increased as well.

BBB Version : 2.5.9

<img width="254" alt="Screen Shot 2023-01-04 at 11 46 12 AM" src="https://user-images.githubusercontent.com/26188869/210512389-8957d58a-a82c-486a-95ed-e88bbefcf45d.png">

**Comment by Scroody** [comment]
I tried on 2.5.9 and 2.6rc and couldn't reproduce the issue.
