### ISSUE TITLE
[2.6.0-beta.4] User names are hidden in the list of waiting guests

### ISSUE THREAD

**Issue by vasylOstrovskyi** [bigbluebutton/bigbluebutton#16390]
**Describe the bug**
With small resolutions and some locales, names of users waiting in the lobby are hidden

**To Reproduce**
1. Start new session, select 'Ask Moderator' guest policy
2. Add some guest users to wait for moderator approvement
3. Depending on the screen resolution and locale, avatars and names of waiting users may be partially or completly covered by the action buttons (see screenshot for 1920x1200 scaled 125% with Ukrainian locale)

**Expected behavior**
Names of users should be visible.

**Screenshots**
![Знімок екрана з 2023-01-05 09-43-03](https://user-images.githubusercontent.com/33595182/210737155-3ddfed99-9825-4d65-b366-f8cb133d0e58.png)

**BBB version:**
BigBlueButton Server 2.6.0-beta.4 (647) build: 273

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Browser Chrome

**Comment by antobinary** [comment]
Thanks for reporting! Is it as bad when you have scaling at 100% too?

**Comment by vasylOstrovskyi** [comment]
At 100% (full hd), I can see avatar and one or two letters on name. Please notice, that in my report, 125% is not a browser scaling with Ctrl-+, but monitor resolution scaling set by system, so this is equivalent to 1536x864 monitor resolution.
On my laptop with monitor resolution set to 1380x768 and 100% browser scale, I do not see even a part of avatar
![Знімок екрана з 2023-01-06 11-16-15](https://user-images.githubusercontent.com/33595182/210970718-ec1e9aeb-782e-4924-8b4c-60515ffc8806.png)
At browser 80%, I see only avatar, and at browser 50% I see complete name, but the letters are too small to read.

**Comment by antobinary** [comment]
Thanks @vasylOstrovskyi !
We could replace the three clickable words with some type of buttons where the words are in the tooltip... or spread each row into two. What do you recommend @tylercopeland ?

**Comment by tylercopeland** [comment]
@vasylOstrovskyi, thanks for sharing this feedback. I think we can make this experience more responsive for now versus adding new buttons. Here is a quick inline idea. 

![Screen Shot 2023-03-14 at 3 31 01 PM](https://user-images.githubusercontent.com/1273169/225117951-0faaeccc-f654-4aca-87a6-26345c60bab9.png)

This will also alow for xl long names. For example, in a school setting, names will display both the first and last name. 

cc @antobinary

**Comment by ffdixon** [comment]
If we make it responsive, then widening the panel would put the items on one line.  We can also change Apply | Deny to icons. 

Here's how Google Groups lets you accept/deny each user applying to the bigbluebutton-dev mailing list.

<img width="136" alt="image" src="https://user-images.githubusercontent.com/290351/225202083-2a8d586a-6482-401b-8002-66e2235dfc99.png">

We could probably use an icon for writing a message and further condense it.

**Comment by tylercopeland** [comment]
@ffdixon, thanks for sharing this thought. It has inspired me to think of a third solution. 

**(TC)** [1] Tyler Copeland    :heavy_check_mark: X

-----

`(TC) [1] Tyler Copeland` is responsive whereas   :heavy_check_mark: X is static on the far right. For individuals with an extra long name, it will fall into two lines, but the main actions will always be on the right.
