### ISSUE TITLE
[2.6-beta.4] Browser on IOS tablet does not redirect to BigBlueButton App

### ISSUE THREAD

**Issue by christmart** [bigbluebutton/bigbluebutton#16406]
**Describe the bug**

Browser does not redirect to BBB App on Ipad when joining a conference.

**To Reproduce**

Start or join a conference in safari browser.

**Expected behavior**

Browser should call BBB app for the conference to display and make screen share available. 

**Actual behavior**

Conference is started/joined inside the safari browser and no screen share is possible.

**Smartphone (please complete the following information):**
 - Device: Ipad 7
 - OS: iOS 15.7.1
 - Browser Safari

**Additional context**

setting in bbb-html.conf:

public:
  app:
    bbbTabletApp:
      enabled: true

demo-ios.bigbluebutton.org shows the same behavior, but it is still on beta.1

Christoph

**Comment by Ithanil** [comment]
Are there any updates on this topic? Can't test it myself, but would like to know the status.

Furthermore: Since the app is also available on Android, should there be a redirect or at least notification about the app as well?
