### ISSUE TITLE
background music not working

### ISSUE THREAD

**Issue by nephilim75** [bigbluebutton/bigbluebutton#16419]
Hello

tried to setup background music for single user in a conference. Followed instructions on [this site](https://docs.bigbluebutton.org/admin/customize.html#enable-background-music-when-only-one-person-is-in-a-session). I did not get it working.

I am running version 2.5.10 on Ubuntu 20.04 as advised.

Kind regards
//nephilim

**Comment by JeanPluzo** [comment]
Hi,
I have the same problem.
After following the official instructions in the link above, I get the following error in `fs_cli` output:
`[ERR] switch_core_file.c:346 Invalid file format [local_stream] for [moh]!`
I've tried to change the sampling rate and to normalize the wav-file, but still no luck.
Perhaps someone can shed more light to this issue.
Thanks in advance.

Regards,
J.

BTW, running 2.5.11 on focal 20.04
