### ISSUE TITLE
promoting a new moderator in 2.5.10 and 2.5.11 not possible 

### ISSUE THREAD

**Issue by ReimarBauer** [bigbluebutton/bigbluebutton#16425]
**Describe the bug**
In current 2.5.11 a moderator can't promote another user to moderator state through the web interface

**To Reproduce**
see gifcycle
![promoting_moderator_missing](https://user-images.githubusercontent.com/278728/211512496-52feacb0-4104-49d7-ad37-dd35af66ae5a.gif)

**Expected behavior**
There should be a button promote to moderator not only to set a presenter state

**Actual behavior**
There are missing buttons compared to older BBB versions

**Comment by mwuttke** [comment]
I can confirm this also for bbb version 2.6.0-beta5.

**Comment by steffen-moser** [comment]
Strange – tested with 2.5.10, 2.5.11, and 2.6.0-beta5 and **cannot** confirm this. I can promote another viewer user to a moderator without any issues.

**Comment by mvasylenko** [comment]
It seems to be a greenlight v2.14.2 issue.
It is probably introduced with following PR:
https://github.com/bigbluebutton/greenlight/pull/4427

**Comment by mwuttke** [comment]
@mvasylenko: Yes, you are right. We are using Greenlight v2.14.2. With Moodle it still works.

**Comment by antobinary** [comment]
From reading https://github.com/bigbluebutton/bigbluebutton/pull/11215 and more specfiically https://github.com/bigbluebutton/bigbluebutton/commit/19cbef1fd90f6670e0989e1bd0198f2859508ed4
I'm thinking we should be passing `authenticatedGuest=false` in `/etc/bigbluebutton/bbb-web.properties` to be able to allow for guests to be promoted.

**Comment by antobinary** [comment]
Update: After conversation with @farhatahmad the decision was made to no longer send `guest=true` on Greenlight v2. (A release with this change is in the making).
This means that you will no longer be required to set `authenticatedGuest=false` in bbb-web as a workaround to promotion.

**Comment by antobinary** [comment]
Looks like Greenlight v2 no longer is sending `guest=true`, so this should no longer be an issue starting with GL 2.14.3 https://github.com/bigbluebutton/greenlight/releases/tag/release-2.14.3

**Comment by SamuelWei** [comment]
You could implement a solution in Greenlight v3 like we have in PILOS to solve this issue.

<img width="273" alt="image" src="https://user-images.githubusercontent.com/4281791/218414525-acb55fbc-1539-451f-a841-baaefcb581c4.png">


In our room settings we have three options:

- Waiting room is disabled, users and guests can join
- Waiting room is enabled, users and guests have to wain in the waiting room
- Waiting room is enabled only for guests, users can join, guests have to wait in the waiting room

**Note** The waiting room always only effect non-moderator users. If you set "Everyone joins as moderator" the waiting room is ingored.

**How to implement**

- Create room
  - Disabled: Do nothing
  - Enabled: `guestPolicy=ASK_MODERATOR`
  - Enabled only guests: `guestPolicy=ALWAYS_ACCEPT_AUTH`
- User joining
  - User: Do nothing
  - Guest: `guest=true`

See note in the inofficial PHP API docs:  https://github.com/littleredbutton/bigbluebutton-api-php#experimental-features
