### ISSUE TITLE
[2.6 beta 3] ReactModal never closes when connecting with microphone

### ISSUE THREAD

**Issue by Erawpalassalg** [bigbluebutton/bigbluebutton#16420]
**Describe the bug**
On a fresh BBB 2.6 install with [instal script](https://github.com/bigbluebutton/bbb-install/blob/master/bbb-install-2.6.sh), after trying to connect with microphone, the ReactModal does not disappear, while the audio is clearly connected. Closing the modal manually also terminates the audio/mic connection.
This does not append when only connecting to audio.

We do not use GreenLight to access reunion rooms (though GreenLight is currently enabled on the server, and the behavior persists when accessing a room through GreenLight)

**To Reproduce**
This is really is the nominal case, nothing funky : install a server with the script, create a room (using GreenLight if you wish), access reunion with mic, give consent, watch the modal not going off.

**Expected behavior**
The modal should close

**Actual behavior**
The modal does not close

**BBB version:**
BigBlueButton Server 2.6.0-beta.3 (608)

**Desktop (please complete the following information):**

 - OS: Linux
 - Browser:  Chromium & Firefox
 - Version: Ubuntu 20.04
---
 - OS: Mac
 - Browser:  Safari
 - Version: [will update with info]

**Additional context**
bbb is accessed through another website, but things work fine when accessing rooms using a 2.2 bbb server (we use both in parallels, trying to migrate from 2.2 to 2.6)

**Comment by Erawpalassalg** [comment]
Hi, there. Thanks for the pointer.
Unfortunately, it did not change a thing, nor restarting through `bbb-conf --restart`.
Also the nginx logs do not show anything relevant (at least to me).

**Comment by ffdixon** [comment]
> On a fresh BBB 2.6 install with instal script,

Can you share more information on the server on which you installed 2.6-beta.  See https://docs.bigbluebutton.org./support/getting-help.html#help-installing-or-running-bigbluebutton.

**Comment by Erawpalassalg** [comment]
That solved the issue.
Thank you for your time!
