### ISSUE TITLE
Focus stolen when someone with webcam leaves the meeting

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#16435]
**Describe the bug**
The focus is stolen every time someone with webcam leaves the meeting

**To Reproduce**
1. User A joins a meeting
2. User B joins that same meeting
3. User B starts sharing webcam
4. User A starts typing [in the public chat input box]
5. User B leaves the meeting while A is typing

**Expected behavior**
User A can continue typing

**Actual behavior**
The focus is stolen and User A has to click again in the public chat input box to be able to continue typing

**Screenshots**

**BBB version:**

BigBlueButton 2.6.0-beta.5

**Comment by antobinary** [comment]
Closely related to https://github.com/bigbluebutton/bigbluebutton/issues/15238

**Comment by Scroody** [comment]
I tried to reproduce the error but had no success in doing so.
