### ISSUE TITLE
Allow Moderators to also propagate their layout

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#16439]
**Describe the bug**
In BBB 2.6.0-beta.5
- presenter can change their own layout (from modal) and push it to all
- moderators can change their own layout (from modal)
- viewers don't get to see the modal or settings but can drag/drop elements in some layouts (custom)

Allow for non-presenter moderators to also propagate their layout

**Screenshots**
![Screenshot from 2023-01-10 15-17-33](https://user-images.githubusercontent.com/6312397/211660594-36e59939-f2b6-42a5-a58c-5bf3044b2c2d.png)

![Screenshot from 2023-01-10 15-17-20](https://user-images.githubusercontent.com/6312397/211660596-40a74421-5332-4958-9658-cf80a5b6d908.png)

**BBB version:**
BigBlueButton 2.6.0-beta.5

**Comment by einhirn** [comment]
See also #16149
