### ISSUE TITLE
[2.6-beta.5] the systemctl bigbluebutton.target is not calling apply-config.sh

### ISSUE THREAD

**Issue by christmart** [bigbluebutton/bigbluebutton#16448]
**Describe the bug**
starting a server with bigbluebutton does not call apply-config.sh.
bbb-conf --restart does also not call apply-config.sh.

**To Reproduce**
configure enableUFWRules in apply-config.sh
restart the server
run ``ufw status``
ufw is disabled

**Expected behavior**
starting a server with bigbluebutton or issuing bbb-conf --restart should call apply-config.sh like bbb-conf --start does.

**Actual behavior**
bbb-conf --start is not called on startup via systemctl target bigbluebutton, so apply-config.sh is not called and e.g. ufw not enabled.

This is on 2.6-beta.5. 
The change was introduced with: https://github.com/bigbluebutton/bigbluebutton/pull/16347

Christoph

**Comment by antobinary** [comment]
Addressed in https://github.com/bigbluebutton/bigbluebutton/pull/16430 (under review)
