### ISSUE TITLE
The modal window with the "OK" button disappears when the user leaves the conference until "OK" is clicked.

### ISSUE THREAD

**Issue by KapustinVadim1991** [bigbluebutton/bigbluebutton#16453]
I display a window with a conference on my site through the iframe tag. After I join the conference, I close the window with the choice "Connect with a microphone or for listening only" and exit the conference through the options. A modal window appears with a confirmation to leave the conference. By pressing the OK button, a redirect occurs to the link specified in the logoutYURL parameter when creating the conference.

A modal window with an OK button appears for a fraction of a second and disappears, after which I am left with an iframe with a black background, and the following error is displayed in the browser console

<img width="1373" alt="image" src="https://user-images.githubusercontent.com/61548543/212054457-9e42c68a-3c39-4735-b668-bee88234b8bb.png">

If you enter in listening mode or turn on the microphone, the error will rarely be reproduced.

**Expected behavior**
The modal window with the "OK" button does not disappear when leaving the conference.

**Actual behavior**
The modal window with the "OK" button does disappear when leaving the conference.

**BBB version:**
BigBlueButton Server 2.5.8 (3139)

**Desktop (please complete the following information):**
 - OS: Mac, Windows
 - Browser Chrome, Safari, Firefox
 - latest
 
**Additional context**
End meeting button for moderator sometimes produces the same behavior

**Comment by antobinary** [comment]
Hi @KapustinVadim1991 
Could you please try reproducing the same but excluding the iframe?
Based on the error it seems to me you are trying to use the meeting object after it has been removed. If you are able to reproduce this without your customizations, please open a new issue here.

As it stands right now, we can't help you here as this does not appear to be an issue with BigBlueButton but a custom set of changes that we don't see..

If you need additional help, a good spot to look for it is the development mailing list https://groups.google.com/g/bigbluebutton-dev
Note that you will have to provide more info / code for people to be able to assist.
