### ISSUE TITLE
[2.6.0-beta] tldraw. Undocumented duplicated hotkeys

### ISSUE THREAD

**Issue by vasylOstrovskyi** [bigbluebutton/bigbluebutton#16455]
**Describe the bug**
There are undocumented hotkeys in the current implementation of tldraw.
1,v - select
2,d,p - pencil
3,e - eraser 
4,r - square drawing
5,o - circle drawing
6,g - triangle drawing
7,l - line drawing
8,a - arrow
9,t - text
0,s - sticky note
Delete, Backspace - delete
probably others with modifiers...

**Expected behavior**
All hotkeys should be documented in the tooltips and in the list of hotkeys, or duplicated hotkeys should be disabled.

**Actual behavior**
Only 1-0 of the listed are documented, for delete action, tooltip shows Backspace, list in the meny shows Del.

**BBB version:**
2.6.0-beta.5

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Browser Chrome
Regards,
 Vasyl

**Comment by antobinary** [comment]
Thank you for reporting this and summarizing it so well!
