### ISSUE TITLE
refactor - Stop sending pres upload status msg after one page failed

### ISSUE THREAD

**Issue by GuiLeme** [bigbluebutton/bigbluebutton#16461]
**Describe the issue**

Enhance flow of throwing error when PDF is too complex.

**Context**
Since this PR #15688 there has been some issues in the presentation component when we try to refactor it, and the main reason is because of the parallel conversion of pages in the back-end. Basically when the presentation is too complex, the back-end tries to convert the first page 3 times and then notifies the client that an error was thrown, interrupting the conversion. The problem is that since the processing of these pages is parallel, the back-end send, say the first 5 pages, each of them starting a little later then the other one, and for that reason, when the first one throws the timeout error, the other 4 are still processing, and this could end in a bug in front-end, there are messages that are still going to be produced even after it was notified that it stopped.

One example of refactor that bumped into this error is: https://github.com/bigbluebutton/bigbluebutton/pull/16043#pullrequestreview-1242901376 , so basically, if the processing of the other pages were stopped right after the first one got an error, the other messages wouldn't have been sent.   

So I am thinking of a way to prevent those messages from being sent to the front-end.

**Expected behavior**

As soon as the error message was sent to the front-end, the back-end should not send any other message regarding that presentation.

**Info**

This `extractIntoPages` function in https://github.com/bigbluebutton/bigbluebutton/blob/bbdbfb66525da6927cc28ca1ae93a3894bffd1cb/bbb-common-web/src/main/java/org/bigbluebutton/presentation/imp/PresentationFileProcessor.java#L91 is the one responsible to process the pages separately, which calls `pdfSlidesGenerationService.process` in https://github.com/bigbluebutton/bigbluebutton/blob/bbdbfb66525da6927cc28ca1ae93a3894bffd1cb/bbb-common-web/src/main/java/org/bigbluebutton/presentation/imp/PresentationFileProcessor.java#L120 running each iteration of the `for` in parallel processing, as suggested by:
https://github.com/bigbluebutton/bigbluebutton/blob/bbdbfb66525da6927cc28ca1ae93a3894bffd1cb/bbb-common-web/src/main/java/org/bigbluebutton/presentation/imp/PdfSlidesGenerationService.java#L43

**Possible Solution**

One way of resolving this problem is to validate in akka if the messages being sent to the front-end are correct, so basically, it would store this PDF error state for that presentationID in particular and if there was an error message already, it would prevent other new messages from showing up in the client.

If anyone has another idea of enhancing this flow, please comment, let's discuss!

**Comment by gustavotrott** [comment]
Good catch @GuiLeme!!
I think we can definitely improve this part to avoid the client from receiving these late messages.

AFAIK currently `bbb-web` process the presentation and the `html5-backend` handles it and store the presentation state in `mongo`.
In this scenario, `akka-apps` doesn't store any information about the presentation. it just forward the msg from `bbb-web` to the `html5-backend`.
Hence, I suggest to try to solve the problem in the origin. Avoid `bbb-web` from sending the unwanted message instead of add complexity to `akka-apps`. It seems to keep things more clear if we hold all related logic in one single place.
