### ISSUE TITLE
Whiteboard slide change when drawing error

### ISSUE THREAD

**Issue by zhem0004** [bigbluebutton/bigbluebutton#16479]
**Describe the bug**
If you change slide while drawing it causes whiteboard error

![Screenshot from 2023-01-16 13-33-20](https://user-images.githubusercontent.com/80958763/212748673-1a0d5922-729d-4e18-b8c8-299130865eb7.png)

**To Reproduce**
1. Create a meeting
2. Join as moderator
3. Select pencil drawing tool
4. Start drawing and while holding - open some window outside the tab with right-click. (I used accessibility window)
5. Select something in that window (I selected "Show keys, but it can be anything as long as it's left-click). The window will close and now the pencil is drawing without needing to hold left mouse button.
6. Change slide
7. Presentation is replaced by error

**Expected behavior**
Annotation either stops or gets transferred to chosen slide

**BBB version:**
2.6.0-beta.6

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Chrome
 - Version: Ubuntu 22.04

**Comment by ffdixon** [comment]
Good catch!
