### ISSUE TITLE
whiteboad: Presentation showing wrong slide (when capturing whiteboard from breakout room)

### ISSUE THREAD

**Issue by gustavotrott** [bigbluebutton/bigbluebutton#16489]
**Describe the bug**
When I flag to "capture whiteboard from breakout" and it finish the upload to the main room. I select the imported presentation but it still shows the slide of the previous one (only for the presenter).
When I click to minimize presentation and then restore it. The slide is then updated to the correct one.

**To Reproduce**
1. Create a meeting
2. Join as presenter / moderator
3. Join in other tab as viewer
4. Create breakout room and flag the option "Capture whiteboard"
5. Viewer join in a breakout room
6. Viewer draw something in the whiteboard
7. Moderator finish the breakout
8. Moderator wait for the import to finish
9. Moderator select the imported presentation
10. It will not change the slide to the imported from the breakout room

**Expected behavior**
It should show the correct slide with the annotations of the breakout room

**Actual behavior**
It keeps showing the slide of the previous presentation

**Screenshots**

https://user-images.githubusercontent.com/5660191/212905961-19ede0c0-ac26-4c7f-adf9-7d29220487ec.mp4

**BBB version:**
BigBlueButton Server 2.6.0-beta.6 (724)

**Desktop (please complete the following information):**
 - OS: Linux Ubuntu 20.04
 - Browser Firefox 108.0.2 (64-bit) and Chrome 108.0.5359.124 (64-bit)

**Additional context**
A similar issue was fixed in https://github.com/bigbluebutton/bigbluebutton/pull/15967
But not I can reproduce the problem again when capturing slides from breakouts.

**Comment by danielpetri1** [comment]
Thanks for reporting this. Seems related to #16368.

**Comment by gustavotrott** [comment]
Fixed in #16495
