### ISSUE TITLE
Better Nextcloud Integration - Suggestion

### ISSUE THREAD

**Issue by amishbhavsar** [bigbluebutton/bigbluebutton#16497]
With the BBB 2.6 version, the ability to allow file upload from NextCloud is a great addition.
(https://docs.bigbluebutton.org/2.6/new.html#upload-a-presentation-straight-from-nextcloud) 
However, it seems like this functionality is only adding the link to let users go from BBB instance to NextCloud to pick a file, but not really let the user upload that file straight to the active session from where the request came. I still have to download the file from NextCloud to my PC and then upload it to the active BBB session - just like how I would upload a local file from my PC.

Suggestions:
When a user clicks to upload a file from NextCloud, BBB should pass the room name and state to NextCloud and let the user directly upload file from Nextcloud to the room from where the request came from.

**Comment by hiroshisuga** [comment]
As we have already discussed somewhere, you'd better ask the developer of nextcloud BBB integration app...

**Comment by GuiLeme** [comment]
Hi, I understand your request, but this is already been held by BBB side, see https://github.com/bigbluebutton/bigbluebutton/pull/14264 that implements the ability to send a document via API.

From the integration side, this upload of documents works as well. But there is only one minor issue: the room and meeting must be created inside Nextcloud. This could be easily resolved, if it requested `getMeetings` endpoint, and I will open an issue in  https://github.com/sualko/cloud_bbb for that, as well as for other improvements that I could notice during my tests with the integration.
