### ISSUE TITLE
Rename client config `autoJoin` to something more self-explaining

### ISSUE THREAD

**Issue by gustavotrott** [bigbluebutton/bigbluebutton#16490]
**Describe the bug**
The config named `public.app.autoJoin` is used to opt "Shows the audio modal when user joins the room".
It is almost impossible to know what this config does just reading its name.
I suggest to change the config name to something more self-explaining.

Suggestion: `public.app.showAudioModalOnJoin`

_Inspired in similar configs: `skipCheckOnJoin`, `lockOnJoin`, `askForConfirmationOnLeave`_

**Screenshots**
![image](https://user-images.githubusercontent.com/5660191/212906831-1244724e-d09a-4fec-bef8-b84677b29775.png)

**BBB version:**
BigBlueButton Server 2.6.0-beta.6 (724)

**Comment by ffdixon** [comment]
Agreed!
