### ISSUE TITLE
2.6.0-beta.6 (727)  error entering meeting,  client did not load presentation area not repeatable.

### ISSUE THREAD

**Issue by hostbbb** [bigbluebutton/bigbluebutton#16508]
**Describe the bug**
Just built 2.6.0-beta.6 (727) server,   entering meeting the client had following error laoding.

 

**To Reproduce**
Not reproduceable.

**Screenshots**
see attachments

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version Version 109.0.5414.75 (Official Build) (64-bit)

![Screenshot 2023-01-18 125251](https://user-images.githubusercontent.com/519542/213260291-a9bdd494-3d48-40fc-9a3e-c02af795771e.jpg)

![Screenshot 2023-01-18 125148](https://user-images.githubusercontent.com/519542/213260338-4d42975f-7bb2-4e63-8cdc-893d83b0c640.jpg)

**Comment by antobinary** [comment]
Thanks for reporting @hostbbb !

I checked what's at 420:890720 on beta.6 and could map it to the following:
https://github.com/bigbluebutton/bigbluebutton/blob/v2.6.0-beta.6/bigbluebutton-html5/imports/ui/components/whiteboard/component.jsx#L355 -- `slidePosition` seems to be undefined

**Comment by spreeni151** [comment]
Hi,
I found an error that may have the same cause, so I didn't create a new thread.
When starting a meeting with the parameter "startClosed: true" in the settings.yml file (to start with the chat area closed), the default presentation is no longer displayed correctly (see screenshot).

bbb 2.6.0-beta-6
client version 309
Firefox 108, Chrome 109, Windows 10

Regards, Frank
![screenshot](https://user-images.githubusercontent.com/57463889/213378366-2d26d033-8f30-49fa-a009-47a4eef00334.png)

**Comment by antobinary** [comment]
Thanks for reporting this @spreeni151 -- I opened a new issue and commented there too #16515

**Comment by ffdixon** [comment]
> Thanks for reporting this @spreeni151 

Ditto!
