### ISSUE TITLE
Locales not working on tldraw menu bar?

### ISSUE THREAD

**Issue by JuanCasad0** [bigbluebutton/bigbluebutton#16507]
**Describe the bug**
Localized text seems not be working in tldraw menu bar. 

Tested with galician (gl) and both spanish ES + es_ES, which I translated myself, when checking that the translations were right.

**To Reproduce**
Use your browser with your native language as default (galician in my case)
1. Go to the menu bar on tldraw
2. Leave the mouse pointer over any of the buttons, just to let it show its purpose.
3. Check it shows the text in English.

**Expected behavior**
The text shows in a localized language.

**Actual behavior**
The text appears in English.

**Screenshots**
2 screenshots attached.

**Desktop (please complete the following information):**
 - OS: Tested under Windows 10 and Linux Debian Buster
 - Browser: Both Firefox and chrome, latests versions available)

![test2](https://user-images.githubusercontent.com/122808643/213252331-0145715d-380f-4198-b8e7-28ff8ed61822.png)
![test1](https://user-images.githubusercontent.com/122808643/213252390-38fef5a9-cacb-4341-845b-eec4fbb3f1d0.png)

**Comment by JuanCasad0** [comment]
Forgot to tell: "Styles button" shows in English as well. But I've been looking on transifex for the strings to translate and couldn't find anything related to "styles" (fill, dash, etc). Probably not there yet to translate... but I prefer to tell it here just to be sure.

**Comment by antobinary** [comment]
Thanks for reporting! The only mentions of Eraser I find in the locale resource are about the shortcuts - https://github.com/bigbluebutton/bigbluebutton/blob/v2.6.0-beta.6/bigbluebutton-html5/public/locales/en.json

I think this is a valid point - we should look into localizing the toolbars. @KDSBrowne are these strings coming straight via tldraw? I saw locales mentioned in their release notes, perhaps we need to map their locales to our client's locale?

**Comment by germanocaumo** [comment]
@antobinary We already map, but in spanish there were multiple versions, it was only working for the 'es' variation

**Comment by JuanCasad0** [comment]
@germanocaumo Thanks for the info. I've just tried both [es] and [es_ES] in my browser and the info still shows in English. Not sure if you mean this...

**Comment by JuanCasad0** [comment]
My bad.... Just reloaded an with locale [es] it shows in spanish! Just forget my previous message.
