### ISSUE TITLE
Prevent other viewer to hear the viewer with microphone enabled (except instructor)

### ISSUE THREAD

**Issue by Mohamad777** [bigbluebutton/bigbluebutton#16500]
We have a feature to lock other viewrs to see other's webcam: "See other viewers webcams"

Another feature like "Hear other viewers voice" should be added to lock or unlock.

This feature will be used in studio for example. Input sound to our switcher is complex with multiple devices (microphones and virtual inputs). So we need to get the viewer sound, proccess on it and send it to switcher (in this way others can hear the proccessed voice). But bbb shares the sound to others in default. Consequently we need to lock other viewers to hear the unprocessed voice.

Thanks

**Comment by hostbbb** [comment]
mod_conference has the relate api to control the inputs/outputs of every member in a conference, at a low level controlled by ESL events.  not clear exactly of your requirements.

You want everyone to only hear the the presenter? and all the others thru the presenters output still being able to talk?
Do you plan using a custom mixer on server, or the presenters client?
