### ISSUE TITLE
Building bbb-libreoffice hang on fetch https://dl-cdn.alpinelinux.org

### ISSUE THREAD

**Issue by reza1366** [bigbluebutton/bigbluebutton#16512]
Hello everybody,
installing new version of BBB (2.6 and 2.5) hang on  building bbb-libreoffice docker image in fetching "https://dl-cdn.alpinelinux.org/alpine/v3.16/main/x86_64/APKINDEX.tar.gz".
changing the DNS and using Proxy and VPN did not solve the problem,based on my research docker should build with --network host, but I don't know how to do it.
can someone help me?

**Comment by antobinary** [comment]
Crossreferrencing https://groups.google.com/g/bigbluebutton-setup/c/svB6WEu-yTQ

**Comment by antobinary** [comment]
Also I've had to install 2 systems of BBB 2.6.0-beta.6 today but did not hit this

```
Reloading nginx.service using systemd
Setting up bbb-libreoffice-docker (1:2.6-8) ...
#
# Building bbb-libreoffice docker image
#
Sending build context to Docker daemon  2.048kB
Step 1/2 : FROM amazoncorretto:17-alpine
17-alpine: Pulling from library/amazoncorretto
8921db27df28: Pull complete 
5118cc5fafe1: Pull complete 
Digest: sha256:11f4a21348795e3be108637af161d36b4984b58a8b4c5643e0727f7e756097cb
Status: Downloaded newer image for amazoncorretto:17-alpine
 ---> c75c7f4e86bc
Step 2/2 : RUN apk add fontconfig libreoffice
 ---> Running in 5baca7c7e42e
fetch https://dl-cdn.alpinelinux.org/alpine/v3.17/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.17/community/x86_64/APKINDEX.tar.gz
fetch https://apk.corretto.aws/x86_64/APKINDEX.tar.gz
(1/180) Installing libexpat (2.5.0-r0)
...
```

**Comment by hromojaro** [comment]
Restarting the docker daemon, and trying the package install again, worked for me as a workaround.

**Comment by gustavotrott** [comment]
> Restarting the docker daemon, and trying the package install again, worked for me as a workaround.

Good to know it @hromojaro!



> based on my research docker should build with --network host, but I don't know how to do it.

@reza1366, I took a look at this option.. but in general the default is `--network=bridge` which was supposed to work properly!
![image](https://user-images.githubusercontent.com/5660191/213715841-df0d305f-559f-4220-a203-3199d562cb80.png)

Maybe the alpine repository was down.. please let me know if you retry to install it and the problem persists or not!

**Comment by reza1366** [comment]
Thank you for your reply، after set proxy in Dockerfile, my problem is solved.
