### ISSUE TITLE
Starting with closed chat leads to presentation to be max zoomed in

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#16515]
Hi,
I found an error that may have the same cause, so I didn't create a new thread.
When starting a meeting with the parameter "startClosed: true" in the settings.yml file (to start with the chat area closed), the default presentation is no longer displayed correctly (see screenshot).

bbb 2.6.0-beta-6
client version 309
Firefox 108, Chrome 109, Windows 10

Regards, Frank
![screenshot](https://user-images.githubusercontent.com/57463889/213378366-2d26d033-8f30-49fa-a009-47a4eef00334.png)

_Originally posted by @spreeni151 in https://github.com/bigbluebutton/bigbluebutton/issues/16508#issuecomment-1396536108_

**Comment by antobinary** [comment]
I tried this and found that on initial load of the page we see the zoom level of the slide as `NaN`.
Some errors in the console
![Screenshot from 2023-01-19 15-15-18](https://user-images.githubusercontent.com/6312397/213551138-83e91fe5-baa8-4f01-ae4b-68869af97128.png)

If I reload, it is displayed as 400% (max) and if then I decrease it by pressing on the `-` button, it seems that we're just zoomed in lots in the upper left-hand corner of the presentation (which happens to be gray).

![Screenshot from 2023-01-19 15-15-36](https://user-images.githubusercontent.com/6312397/213551117-fd077ddd-9cb3-4b35-992b-2600d753af4d.png)

**Comment by spreeni151** [comment]
Just for information: 
No change in the described behavior in the current Beta-7.
kind regards, Frank

**Comment by NarsimaChilkuri** [comment]
> Just for information: No change in the described behavior in the current Beta-7. kind regards, Frank

Is this solved?

**Comment by spreeni151** [comment]
The problem is still there at the moment, but I'm sure they are working on it and will find a solution soon :-)
