### ISSUE TITLE
Multi Turn server for bigbluebutton server / I think the tutorial guide is not correct

### ISSUE THREAD

**Issue by cod3r0k** [bigbluebutton/bigbluebutton#16531]
The configuration of the turn server has some missing information. Isn't it?

    <bean id="turn0" class="org.bigbluebutton.web.services.turn.TurnServer">
        <constructor-arg index="0" value="<secret_value>"/>
        <constructor-arg index="1" value="turns:<turn.example.com>:443?transport=tcp"/>
        <constructor-arg index="2" value="86400"/>
    </bean>

    <bean id="turn1" class="org.bigbluebutton.web.services.turn.TurnServer">
        <constructor-arg index="0" value="<secret_value>"/>
        <constructor-arg index="1" value="turn:<turn.example.com>:443?transport=tcp"/>
        <constructor-arg index="2" value="86400"/>
    </bean>

As you can see, we use to turn 0 and turn 1 for just one turn server in the configuration and I think this is not ok. We must just set once or set multiple of them like turn2 turn3 and so on. But in the configuration, all the tutorial focus on filling both of them while it needs just one of them. Please clarify this.
Thanks.

**Comment by hostbbb** [comment]
That is correct..   one is turn, one is turns.  Think the non secure turn needed for some edge cases.Regards,Stephen

**Comment by cod3r0k** [comment]
> That is correct..   one is turn, one is turns.  Think the non secure turn needed for some edge cases.Regards,Stephen

Wow :) That's great!
