### ISSUE TITLE
Breakout rooms management panel getting stuck with the shared notes content

### ISSUE THREAD

**Issue by antonbsa** [bigbluebutton/bigbluebutton#16541]
**Describe the bug**
After opening shared notes (in the main room) with the breakout rooms opened, the user will see the same as the shared notes and won't be able to exit it.

**To Reproduce**
1. Join as a moderator
2. Create breakout rooms
3. In the main room, open shared notes
4. Click to open the "breakout rooms panel"

**Video**

https://user-images.githubusercontent.com/56703993/214110308-fa4723a9-31c0-4d25-a158-7f8677c5d86a.mp4

**Comment by antobinary** [comment]
Possibly related to https://github.com/bigbluebutton/bigbluebutton/pull/16072 by @tain
