### ISSUE TITLE
Components not working when using a cluster configuration server

### ISSUE THREAD

**Issue by GuiLeme** [bigbluebutton/bigbluebutton#16542]
**Describe the bug**

When reviewing PR https://github.com/bigbluebutton/bigbluebutton/pull/15457 inside a cluster configured server, some components simply did not work, with or without this PR, leading me to believe that we either wrongly documented the proxy configuration server, or there are some untreated errors in BBB regarding the proxy configuration, so I would like to share them, in order to discuss the best alternative to tackle it. 

- [X] Couldn't manage to upload a presentation and BBB-web didn't seem to work in the first place; (1)
- [x] Audio only and microphone weren't working; (2)
- [ ] Shared-notes didn't even loaded;
- [x] Cameras didn't work;
- [x] Deskshare didn't work as well.

1. These were partially solved by the PR mentioned above, but, since some updates in bbb-web, the `/etc/bigbluebutton/bbb-web.properties` file didn't read the properties `grails.cors.enabled`, `grails.cors.allowedOrigins`, `grails.cors.allowCredentials`. So what we had to do was change these same properties, but applying them to the `/usr/share/bbb-web/WEB-INF/classes/application.yml` file, running the following commands: 

```
sudo yq w -i /usr/share/bbb-web/WEB-INF/classes/application.yml grails.cors.enabled true
sudo yq w -i /usr/share/bbb-web/WEB-INF/classes/application.yml grails.cors.allowedOrigins https://bbb-proxy.example.dev
sudo yq w -i /usr/share/bbb-web/WEB-INF/classes/application.yml grails.cors.allowCredentials true
```

And so we need to add this in the proxy part of the documentation. And see why those configs are not being read by `bbb-web.properties` anymore.

2. This second item was simply resolved by entering `/usr/share/bigbluebutton/nginx/sip.nginx` and replacing the line 
```
proxy_pass http://146.190.152.131:5066;
```
for 
```
proxy_pass https://146.190.152.131:7443;
```
on the grounds that `bbb-conf --restart` kept showing 
```
# Potential problems described below
.................
# Warning: You have this server defined for https, but in
#
#   /usr/share/bigbluebutton/nginx/sip.nginx
#
#  did not find the use of https in definition for proxy_pass
#
#            proxy_pass http://<my-ip>:5066;
#

# Warning: You have this server defined for https, but in
#
#   /usr/share/bigbluebutton/nginx/sip.nginx
#
#  did not find the use of port 7443 in definition for proxy_pass
#
#            proxy_pass http://<my-ip>:5066;

```
So it would be interesting to add this in the docs, just in case.

Now, for the last 2 items, I am in doubt if changing one config from `ws://` to `wss://` would solve the problem, simply because, in bbb-webrtc-sfu, we are considering all requests to being local, but once having a proxy, it is the proxy that is going to call sfu.

**Comment by schrd** [comment]
Etherpad can send the cors headers itself. It needs to adjust the config though: https://github.com/alangecker/bbb-etherpad-plugin/pull/7#issue-1433829880

Still not documented yet, sorry

**Comment by GuiLeme** [comment]
A little late, but it is interesting to document it:

@schrd found a workaround for `Shared-notes didn't even loaded;` which is to add the `bbb_01` instance as an allowed origin in the `/usr/share/bbb-web/WEB-INF/classes/application.yml`, so it would be something like:

```yml
cors:
  enabled: true
  allowedOrigins:
    - https://bbb-proxy.example.dev
    - https://bbb-01.example.com
  allowCredentials: true
```

But this is just a workaround for now, and we will keep digging to see if we find a permanent solution for this.

**Comment by schrd** [comment]
In contrast to previous versions it is no longer possible to set the cors properties in `/etc/bigbluebutton/bbb-web.properties`. I don't understand why. It is however possible to set these properties using the `-D` command line option to the java process. A good option would be to specify this in `/etc/default/bbb-web`:

```
JDK_JAVA_OPTIONS="-Dgrails.cors.enabled=true -Dgrails.cors.allowCredentials=true -Dgrails.cors.allowedOrigins=https://bbb.-proxy.example.dev,https://https://bbb-01.example.com"
```
