### ISSUE TITLE
Implement cap for max number of annotations per slide

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#16552]
We should implement a way to cap how many shapes (annotations) we allow on a slide.

Currently (2.6.0-beta.7) we do not limit the shapes and have cases where weaked devices (old iPads, mobile phones, weak laptops) just freeze or are not able to keep up. In reality, on a fixed size slide, anything over `k` shapes is just denial of service attempts.

Similarly how we have

```
    cursorInterval: 150
    maxStickyNoteLength: 1000
```

in https://github.com/bigbluebutton/bigbluebutton/blob/v2.6.0-beta.7/bigbluebutton-html5/private/config/settings.yml#L745

Option A: `maxNumberOfAnnotations: 100` should be configurable via `settings.yml`
Option B: a limit in akka-apps, so that enforcing it is easier -- there we know how many shapes we have, and if we're over the limit, just don't add the new shape. Deleting shapes should allow for more to be added.
Option C: elsewhere

I like Option B except that we'd be introducing annotations related configs in akka-apps, which would mean we further scatter them. Looking for comments!

P.S. I realize that a huge complex shape would count as '1' but I am not aware of other measuring unit - volume or complexity of shapes...

**Comment by ramonlsouza** [comment]
This is important to have, even if set it to a high number by default. 

Without any limit, a user with a very powerful machine could easily break the client for others.
