### ISSUE TITLE
Presentation does not appear correctly to Meeting attendees - BBB 2.6.0-Beta7

### ISSUE THREAD

**Issue by amishbhavsar** [bigbluebutton/bigbluebutton#16587]
**Describe the bug**
When presenter is sharing a presentation to an attendee "fit to page" mode shows the presentation fine for both the presenter and attendee, but in "fit to width" mode, the attendee only sees a small portion of the presentation instead of the same view that presenter sees in the "fit to width" view. See screenshots: https://pasteboard.co/FgbcaQaqQPIR.png (Presenter view) & https://pasteboard.co/X6xXnDcPlXCj.png (attendee view)

**To Reproduce**
1. Start a new BBB meeting
2. Have an attendee join the same meeting room
3. Presenter should upload a new presentation (a PDF file)
4. Presenter should change the view of presentation to "fit to width"
5. Check how the presentation appears differently to presenter and to the attendee

**Expected behavior**
The presentation should appear the same for both the presenter and attendee in both "fit to page" and "fit to width" views

**Actual behavior**
The presentation appears same to both the presenter and attedee in "fit to page" view, but differently in "fit to width" view

**Screenshots**
https://pasteboard.co/FgbcaQaqQPIR.png (Presenter view)
https://pasteboard.co/X6xXnDcPlXCj.png (attendee view)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome Version 109.0.5414.119
 - BBB Version 2.6.0-beta.7

**Comment by testprepturkey** [comment]
Same as #16568.
I guess we need to edit "/bigbluebutton-html5/imports/ui/components/presentation/component.jsx" however I could not locate it
