### ISSUE TITLE
2.6 RC1 Pan (tool) not working

### ISSUE THREAD

**Issue by Buda9** [bigbluebutton/bigbluebutton#16591]
![pan](https://user-images.githubusercontent.com/1422662/215264603-9fb6d2f7-e8e9-4687-9029-fac164a9478e.gif)

tested on test26 bbb server

**Comment by Buda9** [comment]
Here's a recording. It's also a bit strange (fast forward to middle until end of recording):
https://test26.bigbluebutton.org/playback/presentation/2.3/2f87d06fe93cc0daf07e8f11c180ad830fa14fa5-1674905900633

**Comment by antobinary** [comment]
Thanks for reporting!
Looks identical or closely related to https://github.com/bigbluebutton/bigbluebutton/issues/16595 let's address them both together.

**Comment by ramonlsouza** [comment]
fixed by #16601
