### ISSUE TITLE
Buggy whiteboard cursor after drawing many shapes

### ISSUE THREAD

**Issue by antonbsa** [bigbluebutton/bigbluebutton#16602]
**Describe the bug**
After drawing some shapes on the whiteboard, the user possibly will experience its own cursor buggy, being hard the usage. Once minimizing and restoring the presentation, it gets back to normal.
In the video below, there are not many shapes drawn - they were previously removed - but the cursor is still slow.

**To Reproduce**
1. Join with a user;
2. Draw some shapes on the whiteboard;
3. See if the cursor gets buggy / slowly;

**Video**

https://user-images.githubusercontent.com/56703993/215569180-302eb2a6-92a6-484e-9182-cb015a585890.mp4

**Comment by antobinary** [comment]
Possibly related to https://github.com/bigbluebutton/bigbluebutton/issues/16129
