### ISSUE TITLE
API call to inject messages into the chat window

### ISSUE THREAD

**Issue by bigbluebutton-issue-import** [bigbluebutton/bigbluebutton#1660]
Originally reported on Google Code with ID 905

```
Add an API call to inject messages into the chat window.

This would enable tighter integration, such as enabling a 3rd party application to
notify users that the meeting is about it end.  Clicking on a link could extend the
meeting another 1 hour (and bill for it).

The format of the API would be

  sendChatMesssage( meetingID, message)

```

Reported by `ffdixon` on 2011-03-22 02:07:36

**Comment by haviduck** [comment]
Have u found a slot for this feature yet? It would be amazing

**Comment by mtsonline** [comment]
hi,

just wanted to ask if there is any chance to see this implimented soon? We would need it in a few weeks and otherwise have to find another solution.
  
any development going on / some place you could point me to?
thanks

**Comment by sartaj-m** [comment]
Is this feature available in BigBlueButton now? To inject messages to group chat message or private chat?

**Comment by sartaj-m** [comment]
> e this implimented soon? We would need it in a few weeks and otherwise have to find another solution.
> 
> any development going on / some place you could point me to?

Did you found anything on this yet? We are also looking for this feature.

**Comment by iSamof** [comment]
There is another open issue on this here: https://github.com/bigbluebutton/bigbluebutton/issues/6310

**Comment by sartaj-m** [comment]
> There is another open issue on this here: #6310
> That one is for a popup message. If you search you will find other discussions on this.

Thank you for the response. Any idea when this functionality will be available?

**Comment by pedrobmarin** [comment]
Well, the report date indicates this issue just had it's 10th anniversary this past march.

**Comment by iSamof** [comment]
@sartaj-m - I am not with the core team so I cannot answer you on timing. I was merely suggesting that you can find more info by searching, because the current issue you are commenting on is very old and there are newer threads.

**Comment by hostbbb** [comment]
So,  this can be done today crudely if you connect to redis, no how to authenticate as a user, and send a message in redis.   Can also monitor chat messages, and subscribe to them.   Look at redis-cli and type some messages.   have done a few of these in ruby in past.   would require you connect directly to redis or creating custom api endpoint on bbb server to pass messages.

**Comment by mklampfer** [comment]
We created a node.js-based service that can redirect chat messages from a BigBlueButton Meeting to a Matrix chat room and vice versa. It can also be used as a REST API to send messages to the BBB chat from the outside.

https://git.fairkom.net/chat/fairblue-chat-api/-/tree/main

**Comment by ffdixon** [comment]
Hi @mklampfer -- very cool!  Would you like to give a 25 minute presentation on our work at the upcoming BigBlueButton world conference later next month?   See https://world.bigbluebutton.org/?
