### ISSUE TITLE
[2.6 RC1] HTML5 Client Blue Screen if trying to use more than 5 possible answers for a poll

### ISSUE THREAD

**Issue by Subdarub** [bigbluebutton/bigbluebutton#16623]
**Describe the bug**
If you increase the following variable
``` 
public:
  poll:
    maxCustom: 
```
to 6 or more and try to create a 6th answer the HTML 5 Client Blue Screens.

Console Error:

![grafik](https://user-images.githubusercontent.com/35487480/216339344-d90f9024-8704-408e-9eb6-ed601381b622.png)

**To Reproduce**
1. Increase "maxCustom" to 6 or more
2. Try to create more than 5 Elements in a poll

**Expected behavior**
Desired amount of answers

**Actual behavior**
Bluescreen

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Google Chrome
 - Version 109

**Comment by antobinary** [comment]
Thanks for reporting! Fixed by https://github.com/bigbluebutton/bigbluebutton/pull/16621 and will be included in RC2
