### ISSUE TITLE
FreeSWITCH log doesn't rotate

### ISSUE THREAD

**Issue by ritzalam** [bigbluebutton/bigbluebutton#16629]
**Describe the bug**
We had a report that says FS logs grew to 29GB but was supposed to rotate at 105MB.
The reporter did not look at the contents of the log why it grew that big. I have told him
to send the logs next time it happens. They have destroyed the server since.

A fix for the log rotate issue has been made https://github.com/signalwire/freeswitch/pull/1834

**To Reproduce**
Cannot reproduce.

**Expected behavior**
Log file should rotate as configured.

**Comment by antobinary** [comment]
I upgraded FS to 1.10.9 https://github.com/bigbluebutton/bigbluebutton/pull/16672

https://github.com/signalwire/freeswitch/pull/1834 is listed as one of the bug fixes in 1.10.9
