### ISSUE TITLE
Upgrade from 2.6-RC1 to 2.6-RC2 on AWS Server incorrect interface in SIP

### ISSUE THREAD

**Issue by mkpelletier** [bigbluebutton/bigbluebutton#16644]
**Describe the bug**
A clean install of 2.6-RC1 on AWS works well and without issue. However, following an upgrade /usr/share/bigbluebutton/nginx/sip.nginx is set to the internal interface instead of the external interface and wss port.

**Installation type**
RC1 was installed via the script.  The upgrade was performed using apt upgrade.

**Firewall and IP address type**
This is an AWS install.

**Console output**
No error is reported in the console.  However, in the client browser a 1002 error is returned during connect.

**Additional context**
Work-around is to manually set /usr/share/bigbluebutton/nginx/sip.nginx to the external IP address using port 7443 instead of 5066.

**Comment by ffdixon** [comment]
> RC1 was installed via the script. The upgrade was performed using apt upgrade.

You should run the bbb-install.sh command again for the release as it will properly update all the configuration files.
