### ISSUE TITLE
Update 2.6 docs to latest state

### ISSUE THREAD

**Issue by tibroc** [bigbluebutton/bigbluebutton#16668]
Follow-up from https://github.com/bigbluebutton/bigbluebutton/pull/16113:

The new docs have not been updated since https://github.com/bigbluebutton/bigbluebutton.github.io/commit/8cfdcde8.

**Comment by antobinary** [comment]
Hi @tibroc !
I merged a few recent pending pull requests to the old docs so that you only need to sync old to new once :crossed_fingers: 

Does it make sense to merge https://github.com/bigbluebutton/bigbluebutton.github.io/pull/446 too?

**Comment by tibroc** [comment]
Done in https://github.com/bigbluebutton/bigbluebutton/pull/16926
