### ISSUE TITLE
New Docs: add versioning

### ISSUE THREAD

**Issue by tibroc** [bigbluebutton/bigbluebutton#16671]
The new docs should have the option to select the BBB version for which they are valid. E.g.:

![image](https://user-images.githubusercontent.com/39943803/217313636-5e702efb-55b0-47f9-a7f2-b64be5086e34.png)

See https://docusaurus.io/docs/api/themes/configuration#navbar-docs-version-dropdown for the configuration of this feature.

**Comment by GhaziTriki** [comment]
Hi @tibroc,

The build script goes through the branches and builds a multi-version site.

Check this file please https://github.com/bigbluebutton/bigbluebutton/blob/v2.6.x-release/docs/build.sh

**Comment by tibroc** [comment]
@GhaziTriki Yes, I have seen that. However, the option to select the version is not yet configured. It's easy to configure as well, I just put it here as a todo.

**Comment by tibroc** [comment]
Done in https://github.com/bigbluebutton/bigbluebutton/pull/16686
