### ISSUE TITLE
[2.6] Poll results are difficult to read and not scaled to fit slide

### ISSUE THREAD

**Issue by g550** [bigbluebutton/bigbluebutton#16682]
**Describe the bug**
When publishing a poll result they are drawn on to the slide. In 2.6(rc2) however, the results are drawn too big to fit the slide and without a solid background or frame, so that neither the slide's content nor the poll results are properly readable.

**To Reproduce**
1. Start a poll
2. Publish its results

**Expected behavior**
Poll results should be scaled nicely and drawn on a solid background to make them readable and obscure less of the slide.

**Screenshots**

Here's a published poll in 2.5.11:

![poll2511](https://user-images.githubusercontent.com/70478474/217528787-8328bf2b-10a0-448d-8e06-a43f7d42eea3.png)

And the same poll published in 2.6rc2:

![poll26rc2](https://user-images.githubusercontent.com/70478474/217528852-792a1533-4cb5-4c50-ac59-569575d23460.png)

**Comment by ffdixon** [comment]
Thanks @g550 -- we're aware of the issue (though it's good to have an actual issue # to track it), and will be resolving this before the final release of 2.6.

**Comment by g550** [comment]
(If I understood the comment of @antobinary in #16917 correctly, this is now the issue where the look of tldraw poll results should be discussed, right?)

One comment regarding fonts: Since the "bars" representing the percentages of every answer are constructed from multiple | glyphs, I would recommend to use a monospace font (at least in those lines). Otherwise, the lines of |s won't align properly.
