### ISSUE TITLE
Number of annotations exceeded the limit 300 - Error

### ISSUE THREAD

**Issue by amishbhavsar** [bigbluebutton/bigbluebutton#16701]
**Describe the bug**
When the number of annotations exceeds 300, BBB does not allow adding additional annotations. 

**To Reproduce**
Start a BBB class
Add 300 annotations
When trying to add 301st annotation, it shows the error: Number of annotations exceeded the limit 300

**Expected behavior**
It should allow unlimited annotations

**Actual behavior**
When trying to add 301st annotation, it shows the error: Number of annotations exceeded the limit 300

**BBB version:**
BigBlueButton 2.6.0-rc.3

**Desktop (please complete the following information):**
 - OS: [Windows 11]
 - Browser [Chrome]
 - Version [110]

**Comment by hiroshisuga** [comment]
The change is due to #16552. 
Can you not relax it by adding
  whiteboard:
    maxNumberOfAnnotations: 10000
at /etc/bigbluebutton/bbb-html5.yml , for example?

**Comment by hostbbb** [comment]
https://github.com/bigbluebutton/bigbluebutton/blob/25800ee92b55da3cd6f2f2d77540f7e3e02abe4a/bigbluebutton-html5/private/config/settings.yml#L751

Think there are serious performance issues if lots of annotations are placed on a slide. if you set it to a large number expect issues in production, and delays in recording processing.

Someone mentioned once you reach 300,  take a snapshot of slide, and then upload it, then annotate over that to reduce the issue.

**Comment by ffdixon** [comment]
@amishbhavsar, when did you hit the 300 mark.  Was it with a single presenter or multi-user whiteboard?

**Comment by amishbhavsar** [comment]
@ffdixon, it was in an online class with me teaching 1 student, so multi-user whiteboard.

**Comment by ffdixon** [comment]
We would be interested in hearing your experience after increasing the value beyond 300.

**Comment by amishbhavsar** [comment]
@ffdixon , sure I will, but to be honest, I am not sure where to go an update the value? I searched for /etc/bigbluebutton/bbb-html5.yml as @hiroshisuga mentioned, but there is no such file. see screenshot: https://pasteboard.co/JnqXcbIMu0CZ.png

**Comment by hiroshisuga** [comment]
Hi @amishbhavsar , you can create it. BBB will respect it more than any other setting files.

**Comment by amishbhavsar** [comment]
OK, thanks. I will keep you posted.

**Comment by antobinary** [comment]
@amishbhavsar 
Could you please give a bit more info on what the content was on the page when you hit the 300 annotations limit?
For example:
half a page of math symbols and numbers written with a stylus
or
cursive writing in English, almost the entire page was filled
or
drawing something on the whiteboard and writing labels/arrows all over it
...

Did you use zooming in when writing?
Did you hit the limit after being on the page for 10 minutes or 30 minutes, etc?

This kind of info would help us pick a better default value for the max limit cap, so that we don't impact common use cases.

**Comment by amishbhavsar** [comment]
@antobinary, all the annotations were freehand using the pencil tool. It was on a PDF file that was used to teach a student. There was only 1 student and 1 instructor (as presenter). The error message came in both while zooming and not zooming.
If I deleted some of the annotations, I was again allowed to add more annotations - until the 300 limit was reached.

I have now edited the limit in /usr/share/meteor/bundle/programs/server/assets/app/config/setting.yml file to 500.

Let me know if you have any questions.

**Comment by amishbhavsar** [comment]
Since making the change, I am yet to see any issues.

**Comment by amishbhavsar** [comment]
While changing the annotation limit to 500 in /usr/share/meteor/bundle/programs/server/assets/app/config/setting.yml file, I also noticed that it lets me make some changes to the thickness of annotations. But when I changed the thickness value (for ex, from 14 to 8), I did not see any change of that in the class. Not sure if thickness is a parameter that I am allowed to change? Would appreciate if someone can comment on this.
Thanks

**Comment by antobinary** [comment]
Thanks for your response!


> I also noticed that it lets me make some changes to the thickness of annotations. But when I changed the thickness value (for ex, from 14 to 8), I did not see any change of that in the class. Not sure if thickness is a parameter that I am allowed to change? Would appreciate if someone can comment on this.

The `thickness` configuration is a leftover from before tldraw. We have an issue open to adapt the code (or the configs) to work again https://github.com/bigbluebutton/bigbluebutton/issues/16168

> Since making the change, I am yet to see any issues.

I'm happy to hear! Just note that  `/usr/share/meteor/bundle/programs/server/assets/app/config/setting.yml` is reset every time you upgrade BBB (let't say rc.2 to rc.3) so you'll either have to make the change every time, or you can create the `/etc/bigbluebutton/bbb-html5.yml` file mentioned above

The content could be as simple as

```
public:
  whiteboard:
    # limit number of annotations per slide
    maxNumberOfAnnotations: 500
```

**Comment by antobinary** [comment]
Closing as we're still not seeing cases of hitting the limit of 300 on the systems we monitor. The configuration to bump up the limit is described in the comments above in case anyone is looking for it.
