### ISSUE TITLE
[2.6] Local TURN server randomly stops working permanently (until service restart)

### ISSUE THREAD

**Issue by Ithanil** [bigbluebutton/bigbluebutton#16705]
**Describe the bug**
Since we are using BBB 2.6 with local TURN installation in our test environment, we noticed that after a random amount of runtime (from minutes to multiple days) it could happen that it was not possible anymore to establish an audio connection using Firefox (it would hang indefinitely trying to establish the connection). The problem would not disappear until a manual restart of coturn.service .

**To Reproduce**
1. Let the BBB 2.6 with local TURN run for a sufficient amount of time until the problem starts to appear.
2. Connect to the BBB host and try to establish an audio connection, using Firefox (to force the usage of TURN).
3. Observe that the audio connection will not be established.
4. (restart coturn and see the problem disappears)

**Expected behavior**
It should always remain possible to establish an audio connection.

**Actual behavior**
It can become impossible to establish the connection if TURN usage is forced or required.

**Desktop (please complete the following information):**
 - OS: Debian
 - Browser Firefox 102.7 ESR

**Additional context**
On BBB 2.6 RC3, but the issue did already exist in beta.

Relevant Turnserver log:

> 257065: IPv4. tcp or tls connected to: 134.93.26.191:35078
257065: session 020000000000000005: realm <bbb-26-191.bbb.rlp.net> user <>: incoming packet message processed, error 401: Unauthorized
257065: IPv4. tcp or tls connected to: 134.93.26.191:35090
257065: session 000000000000000009: realm <bbb-26-191.bbb.rlp.net> user <>: incoming packet message processed, error 401: Unauthorized
257065: IPv4. tcp or tls connected to: 134.93.26.191:35094
257065: session 007000000000000007: realm <bbb-26-191.bbb.rlp.net> user <>: incoming packet message processed, error 401: Unauthorized
257065: IPv4. tcp or tls connected to: 134.93.26.191:35106
257065: session 005000000000000010: realm <bbb-26-191.bbb.rlp.net> user <>: incoming packet message processed, error 401: Unauthorized
257065: handle_udp_packet: New UDP endpoint: local addr 134.93.26.191:3478, remote addr 134.93.179.170:37050
257065: session 022000000000000009: realm <bbb-26-191.bbb.rlp.net> user <>: incoming packet message processed, error 401: Unauthorized
257065: handle_udp_packet: New UDP endpoint: local addr 134.93.26.191:3478, remote addr 134.93.179.170:45939
257065: session 003000000000000007: realm <bbb-26-191.bbb.rlp.net> user <>: incoming packet message processed, error 401: Unauthorized
257065: handle_udp_packet: New UDP endpoint: local addr 134.93.26.191:3478, remote addr 134.93.179.170:39936
257065: session 009000000000000004: realm <bbb-26-191.bbb.rlp.net> user <>: incoming packet message processed, error 401: Unauthorized
257065: handle_udp_packet: New UDP endpoint: local addr 134.93.26.191:3478, remote addr 134.93.179.170:49748
257065: session 018000000000000007: realm <bbb-26-191.bbb.rlp.net> user <>: incoming packet message processed, error 401: Unauthorized
257084: session 020000000000000005: TCP socket closed remotely 134.93.26.191:35078
257084: session 020000000000000005: usage: realm=<bbb-26-191.bbb.rlp.net>, username=<1676366393:w_68z8iqkan7h5>, rp=2, rb=192, sp=1, sb=128
257084: session 007000000000000007: TCP socket closed remotely 134.93.26.191:35094
257084: session 007000000000000007: usage: realm=<bbb-26-191.bbb.rlp.net>, username=<1676366393:w_68z8iqkan7h5>, rp=2, rb=192, sp=1, sb=128
257084: session 020000000000000005: closed (2nd stage), user <1676366393:w_68z8iqkan7h5> realm <bbb-26-191.bbb.rlp.net> origin <>, local 134.93.26.191:3478, remote 134.93.26.191:35078, reason: TCP connection closed by client (callback)
257084: session 007000000000000007: closed (2nd stage), user <1676366393:w_68z8iqkan7h5> realm <bbb-26-191.bbb.rlp.net> origin <>, local 134.93.26.191:3478, remote 134.93.26.191:35094, reason: TCP connection closed by client (callback)
257084: session 005000000000000010: TCP socket closed remotely 134.93.26.191:35106
257084: session 005000000000000010: usage: realm=<bbb-26-191.bbb.rlp.net>, username=<1676366393:w_68z8iqkan7h5>, rp=2, rb=192, sp=1, sb=128
257084: session 005000000000000010: closed (2nd stage), user <1676366393:w_68z8iqkan7h5> realm <bbb-26-191.bbb.rlp.net> origin <>, local 134.93.26.191:3478, remote 134.93.26.191:35106, reason: TCP connection closed by client (callback)
257084: session 000000000000000009: TCP socket closed remotely 134.93.26.191:35090
257084: session 000000000000000009: usage: realm=<bbb-26-191.bbb.rlp.net>, username=<1676366393:w_68z8iqkan7h5>, rp=2, rb=192, sp=1, sb=128
257084: session 000000000000000009: closed (2nd stage), user <1676366393:w_68z8iqkan7h5> realm <bbb-26-191.bbb.rlp.net> origin <>, local 134.93.26.191:3478, remote 134.93.26.191:35090, reason: TCP connection closed by client (callback)
257125: session 022000000000000009: usage: realm=<bbb-26-191.bbb.rlp.net>, username=<1676366393:w_68z8iqkan7h5>, rp=8, rb=1080, sp=1, sb=128
257125: session 022000000000000009: closed (2nd stage), user <1676366393:w_68z8iqkan7h5> realm <bbb-26-191.bbb.rlp.net> origin <>, local 134.93.26.191:3478, remote 134.93.179.170:37050, reason: allocation watchdog determined stale session state
257125: session 003000000000000007: usage: realm=<bbb-26-191.bbb.rlp.net>, username=<1676366393:w_68z8iqkan7h5>, rp=8, rb=1080, sp=1, sb=128
257125: session 003000000000000007: closed (2nd stage), user <1676366393:w_68z8iqkan7h5> realm <bbb-26-191.bbb.rlp.net> origin <>, local 134.93.26.191:3478, remote 134.93.179.170:45939, reason: allocation watchdog determined stale session state
257125: session 009000000000000004: usage: realm=<bbb-26-191.bbb.rlp.net>, username=<1676366393:w_68z8iqkan7h5>, rp=8, rb=1080, sp=1, sb=128
257125: session 009000000000000004: closed (2nd stage), user <1676366393:w_68z8iqkan7h5> realm <bbb-26-191.bbb.rlp.net> origin <>, local 134.93.26.191:3478, remote 134.93.179.170:39936, reason: allocation watchdog determined stale session state
257125: session 018000000000000007: usage: realm=<bbb-26-191.bbb.rlp.net>, username=<1676366393:w_68z8iqkan7h5>, rp=8, rb=1080, sp=1, sb=128
257125: session 018000000000000007: closed (2nd stage), user <1676366393:w_68z8iqkan7h5> realm <bbb-26-191.bbb.rlp.net> origin <>, local 134.93.26.191:3478, remote 134.93.179.170:49748, reason: allocation watchdog determined stale session state

**Comment by danimo** [comment]
Can you check the amount of connections left open by HA proxy over time?

cc @schrd

**Comment by Ithanil** [comment]
At the moment I have no server running with the coturn problem triggered or even a long runtime.

But if I compare the output of `ss -ap | grep haproxy` before and after connecting a few times, the amount of `ESTAB` connections seems to increase permanently. Not sure if it is abnormal though. Example output:

>ss -ap | grep haproxy
u_str ESTAB       0       0                                                   * 31608                                                            * 0             users:(("haproxy",pid=1578,fd=2),("haproxy",pid=1578,fd=1),("haproxy",pid=1097,fd=2),("haproxy",pid=1097,fd=1))
u_str LISTEN      0       0                    /run/haproxy/admin.sock.1097.tmp 31616                                                            * 0             users:(("haproxy",pid=1578,fd=8))                                              
u_str ESTAB       0       0                                                   * 31639                                                            * 0             users:(("haproxy",pid=1097,fd=4))                                              
u_str ESTAB       0       0                                                   * 31640                                                            * 0             users:(("haproxy",pid=1578,fd=5))                                              
u_str LISTEN      0       0                   /run/haproxy-master.sock.1097.tmp 31646                                                            * 0             users:(("haproxy",pid=1097,fd=11))                                             
u_dgr ESTAB       0       0                                                   * 8985                                                             * 0             users:(("haproxy",pid=1578,fd=105))                                            
u_dgr ESTAB       0       0                                                   * 11216                                                            * 0             users:(("haproxy",pid=1578,fd=100))                                            
u_dgr ESTAB       0       0                                                   * 12147                                                            * 0             users:(("haproxy",pid=1578,fd=101))                                            
u_dgr ESTAB       0       0                                                   * 15483                                                            * 0             users:(("haproxy",pid=1578,fd=98))                                             
u_dgr ESTAB       0       0                                                   * 17857                                                            * 0             users:(("haproxy",pid=1578,fd=99))                                             
u_dgr ESTAB       0       0                            /var/lib/haproxy/dev/log 24039                                                            * 0             users:(("rsyslogd",pid=594,fd=5))                                              
u_dgr ESTAB       0       0                                                   * 25462                                                            * 0             users:(("haproxy",pid=1578,fd=103))                                            
u_dgr ESTAB       0       0                                                   * 25521                                                            * 0             users:(("haproxy",pid=1578,fd=113))                                            
u_dgr ESTAB       0       0                                                   * 25544                                                            * 0             users:(("haproxy",pid=1578,fd=109))                                            
u_dgr ESTAB       0       0                                                   * 27594                                                            * 0             users:(("haproxy",pid=1578,fd=104))                                            
u_dgr ESTAB       0       0                                                   * 30660                                                            * 0             users:(("haproxy",pid=1578,fd=110))                                            
u_dgr ESTAB       0       0                                                   * 30695                                                            * 0             users:(("haproxy",pid=1578,fd=111))                                            
u_dgr ESTAB       0       0                                                   * 31645                                                            * 0             users:(("haproxy",pid=1578,fd=7),("haproxy",pid=1097,fd=7))                    
u_dgr ESTAB       0       0                                                   * 37175                                                            * 0             users:(("haproxy",pid=1578,fd=122))                                            
u_dgr ESTAB       0       0                                                   * 37176                                                            * 0             users:(("haproxy",pid=1578,fd=119))                                            
u_dgr ESTAB       0       0                                                   * 38764                                                            * 0             users:(("haproxy",pid=1578,fd=108))                                            
u_dgr ESTAB       0       0                                                   * 38891                                                            * 0             users:(("haproxy",pid=1578,fd=116))                                            
u_dgr ESTAB       0       0                                                   * 40525                                                            * 0             users:(("haproxy",pid=1578,fd=107))                                            
u_dgr ESTAB       0       0                                                   * 40718                                                            * 0             users:(("haproxy",pid=1578,fd=114))                                            
u_dgr ESTAB       0       0                                                   * 44984                                                            * 0             users:(("haproxy",pid=1578,fd=129))                                            
u_dgr ESTAB       0       0                                                   * 44985                                                            * 0             users:(("haproxy",pid=1578,fd=125))                                            
u_dgr ESTAB       0       0                                                   * 45330                                                            * 0             users:(("haproxy",pid=1578,fd=102))                                            
u_dgr ESTAB       0       0                                                   * 46380                                                            * 0             users:(("haproxy",pid=1578,fd=112))                                            
u_dgr ESTAB       0       0                                                   * 48464                                                            * 0             users:(("haproxy",pid=1578,fd=106))                                            
u_dgr ESTAB       0       0                                                   * 58564                                                            * 0             users:(("haproxy",pid=1578,fd=118))                                            
u_dgr ESTAB       0       0                                                   * 62501                                                            * 0             users:(("haproxy",pid=1578,fd=115))                                            
u_dgr ESTAB       0       0                                                   * 74335                                                            * 0             users:(("haproxy",pid=1578,fd=121))                                            
u_dgr ESTAB       0       0                                                   * 99692                                                            * 0             users:(("haproxy",pid=1578,fd=124))                                            
u_dgr ESTAB       0       0                                                   * 99733                                                            * 0             users:(("haproxy",pid=1578,fd=120))                                            
u_dgr ESTAB       0       0                                                   * 110709                                                           * 0             users:(("haproxy",pid=1578,fd=126))                                            
u_dgr ESTAB       0       0                                                   * 111717                                                           * 0             users:(("haproxy",pid=1578,fd=127))                                            
tcp   LISTEN      0       16384                                         0.0.0.0:https                                                      0.0.0.0:*             users:(("haproxy",pid=1578,fd=10))

**Comment by ffdixon** [comment]
Digging around on this one, and came across

  https://github.com/coturn/coturn/issues/664

and

  https://groups.google.com/g/bigbluebutton-setup/c/_039NCnoYkI/m/wisTTV5GAwAJ

**Comment by ffdixon** [comment]
@Ithanil -- just following up to see if the above items helped.  Would like to narrow down this issue ... have you seen it occur in the last two weeks?

**Comment by Ithanil** [comment]
@ffdixon Thanks for checking back on this. Of the links above, the second one seemed very similar to what I was experiencing. Unfortunately, I do not have a host running with the problem at the moment and can't verify that I get the syslog entries that Paulo Lanzarin mentions in the thread.
I didn't see the problem occur since I opened the issue, but my testing hosts were rather frequently restarted and not used a lot since then. So I'm not entirely convinced that the issue won't appear again, because it is a rather sporadic occurrence.
If there are any news on this topic I will let you know!

**Comment by Ithanil** [comment]
@ffdixon In any case, when I mentioned my issue in the german BBB community call, it appeared that multiple other parties were seeing similar issues and even had certain workaround cronjobs in place to restart coturn if necessary.

**Comment by schrd** [comment]
I have seen this occasionally before with coturn installed on dedicated VMs (Debian 11). I only saw this on firefox, not on other browsers.

**Comment by Ithanil** [comment]
Still no sign of this problem appearing after 6 days of uptime. Going to reboot the VMs now in the process of deploying the RC.6 (and currently I can't keep the old ones running for ... reasons).

Not sure though what change could have lead to an improvement with that problem. Maybe it's just luck.

**Comment by TelekomHacker** [comment]
Same Problem and same exact log as @Ithanil had on our instance. First happened one week ago and now again. Is there any way to write a script which somehow checks if the problem occurs and if so restart the turnserver? And is there high probability that this issue wont occur using bbb 2.5 and an external Turnserver? Thanks for any help.

**Comment by Ithanil** [comment]
I did encounter the problem again last week, but pretty much immediately after the start of the server. The turnserver log is pretty much identical, e.g.:

`102: session 015000000000000002: TCP socket closed remotely 134.93.26.139:54956
102: session 015000000000000002: usage: realm=<bbb-26-139.bbb.rlp.net>, username=<1679558546:w_irng33lfhhkf>, rp=2, rb=192, sp=1, sb=128
102: session 015000000000000002: closed (2nd stage), user <1679558546:w_irng33lfhhkf> realm <bbb-26-139.bbb.rlp.net> origin <>, local 134.93.26.139:3478, remote 134.93.26.139:54956, reason: TCP connection closed by client (callback)
102: session 004000000000000001: usage: realm=<bbb-26-139.bbb.rlp.net>, username=<1679558553:w_k0zzjd6mlwmt>, rp=1932, rb=2136359, sp=116, sb=7384
105: session 011000000000000002: usage: realm=<bbb-26-139.bbb.rlp.net>, username=<1679558546:w_irng33lfhhkf>, rp=14, rb=1548, sp=2034, sb=2468340
106: session 011000000000000001: usage: realm=<bbb-26-139.bbb.rlp.net>, username=<1679558553:w_k0zzjd6mlwmt>, rp=1026, rb=39056, sp=1022, sb=142900
109: IPv4. tcp or tls connected to: 134.93.26.139:35432
109: session 016000000000000001: realm <bbb-26-139.bbb.rlp.net> user <>: incoming packet message processed, error 401: Unauthorized
109: IPv4. tcp or tls connected to: 134.93.26.139:35448
109: session 003000000000000003: realm <bbb-26-139.bbb.rlp.net> user <>: incoming packet message processed, error 401: Unauthorized
109: IPv4. tcp or tls connected to: 134.93.26.139:35460
109: session 011000000000000004: realm <bbb-26-139.bbb.rlp.net> user <>: incoming packet message processed, error 401: Unauthorized
109: IPv4. Local relay addr: 134.93.26.139:56960
109: session 016000000000000001: new, realm=<bbb-26-139.bbb.rlp.net>, username=<1679558546:w_irng33lfhhkf>, lifetime=3600
109: session 016000000000000001: realm <bbb-26-139.bbb.rlp.net> user <1679558546:w_irng33lfhhkf>: incoming packet ALLOCATE processed, success
109: IPv4. Local relay addr: 134.93.26.139:33856
109: session 003000000000000003: new, realm=<bbb-26-139.bbb.rlp.net>, username=<1679558546:w_irng33lfhhkf>, lifetime=3600
109: session 003000000000000003: realm <bbb-26-139.bbb.rlp.net> user <1679558546:w_irng33lfhhkf>: incoming packet ALLOCATE processed, success
109: IPv4. tcp or tls connected to: 134.93.26.139:35464
109: session 018000000000000002: realm <bbb-26-139.bbb.rlp.net> user <>: incoming packet message processed, error 401: Unauthorized
109: session 016000000000000001: peer 134.93.26.139 lifetime updated: 300
109: session 016000000000000001: realm <bbb-26-139.bbb.rlp.net> user <1679558546:w_irng33lfhhkf>: incoming packet CREATE_PERMISSION processed, success
112: session 004000000000000001: usage: realm=<bbb-26-139.bbb.rlp.net>, username=<1679558553:w_k0zzjd6mlwmt>, rp=1930, rb=2136286, sp=118, sb=7492
116: session 011000000000000002: usage: realm=<bbb-26-139.bbb.rlp.net>, username=<1679558546:w_irng33lfhhkf>, rp=12, rb=1288, sp=2036, sb=2472972
118: IPv4. tcp or tls connected to: 134.93.26.139:49826
118: IPv4. tcp or tls connected to: 134.93.26.139:49832
118: session 001000000000000003: realm <bbb-26-139.bbb.rlp.net> user <>: incoming packet message processed, error 401: Unauthorized
118: session 010000000000000001: realm <bbb-26-139.bbb.rlp.net> user <>: incoming packet message processed, error 401: Unauthorized
118: IPv4. tcp or tls connected to: 134.93.26.139:49836
118: session 006000000000000001: realm <bbb-26-139.bbb.rlp.net> user <>: incoming packet message processed, error 401: Unauthorized
118: IPv4. tcp or tls connected to: 134.93.26.139:49850
118: session 014000000000000004: realm <bbb-26-139.bbb.rlp.net> user <>: incoming packet message processed, error 401: Unauthorized
122: session 004000000000000001: usage: realm=<bbb-26-139.bbb.rlp.net>, username=<1679558553:w_k0zzjd6mlwmt>, rp=1930, rb=2135382, sp=118, sb=7472
126: session 011000000000000002: usage: realm=<bbb-26-139.bbb.rlp.net>, username=<1679558546:w_irng33lfhhkf>, rp=12, rb=1288, sp=2036, sb=2471892
127: session 011000000000000001: usage: realm=<bbb-26-139.bbb.rlp.net>, username=<1679558553:w_k0zzjd6mlwmt>, rp=1025, rb=38992, sp=1023, sb=152344
129: session 016000000000000001: usage: realm=<bbb-26-139.bbb.rlp.net>, username=<1679558546:w_irng33lfhhkf>, rp=1026, rb=310916, sp=1022, sb=217008
132: session 004000000000000001: usage: realm=<bbb-26-139.bbb.rlp.net>, username=<1679558553:w_k0zzjd6mlwmt>, rp=1928, rb=2138560, sp=120, sb=7612
137: session 011000000000000002: usage: realm=<bbb-26-139.bbb.rlp.net>, username=<1679558546:w_irng33lfhhkf>, rp=12, rb=1288, sp=2036, sb=2480656
142: session 004000000000000001: usage: realm=<bbb-26-139.bbb.rlp.net>, username=<1679558553:w_k0zzjd6mlwmt>, rp=1934, rb=2141547, sp=114, sb=7288
146: session 007000000000000002: TCP socket closed remotely 134.93.26.139:39166
146: session 007000000000000002: usage: realm=<bbb-26-139.bbb.rlp.net>, username=<1679558631:w_oepjstkmetxj>, rp=2, rb=192, sp=1, sb=128
146: session 007000000000000002: closed (2nd stage), user <1679558631:w_oepjstkmetxj> realm <bbb-26-139.bbb.rlp.net> origin <>, local 134.93.26.139:3478, remote 134.93.26.139:39166, reason: TCP connection closed by client (callback)
146: session 008000000000000001: TCP socket closed remotely 134.93.26.139:39174
146: session 008000000000000001: usage: realm=<bbb-26-139.bbb.rlp.net>, username=<1679558631:w_oepjstkmetxj>, rp=2, rb=192, sp=1, sb=128
146: session 008000000000000001: closed (2nd stage), user <1679558631:w_oepjstkmetxj> realm <bbb-26-139.bbb.rlp.net> origin <>, local 134.93.26.139:3478, remote 134.93.26.139:39174, reason: TCP connection closed by client (callback)
146: session 003000000000000002: TCP socket closed remotely 134.93.26.139:39180
146: session 003000000000000002: usage: realm=<bbb-26-139.bbb.rlp.net>, username=<1679558631:w_oepjstkmetxj>, rp=2, rb=192, sp=1, sb=128
146: session 003000000000000002: closed (2nd stage), user <1679558631:w_oepjstkmetxj> realm <bbb-26-139.bbb.rlp.net> origin <>, local 134.93.26.139:34`

I failed to save the output of `ss -ap | grep haproxy` this time, but I assume there were not a lot of connections left open due to it being a freshly booted server.

**Comment by Ithanil** [comment]
@ffdixon FYI: I'm cautiously optimistic that we got rid of the problem since we are employing a backport of coturn 4.5.2. I'll keep you updated about any further incidents. If we don't see anything for another week or so we will consider the problem solved (with the newer coturn version).

**Comment by ffdixon** [comment]
@Ithanil Thanks for the update.  This one is a bit more challenging to fix because we're testing for the absence of a problem.  

We notice that by default, the install of BigBlueButton 2.6 uses `4.5.1.1-1.1ubuntu0.20.04.2`

```
# dpkg -l | grep coturn
ii  coturn                               4.5.1.1-1.1ubuntu0.20.04.2        amd64        TURN and STUN server for VoIP
```

**Comment by Ithanil** [comment]
@ffdixon Exactly, on Ubuntu 20.04 it's 4.5.1 and we use an own coturn package with 4.5.2 now. We have also experimented with 4.6.x, but so far it appears as if 4.5.2 might be sufficient.

Fingers crossed that it's not just placebo. :)

**Comment by ffdixon** [comment]
Did you build your own package or did you install from a PPA?

**Comment by Ithanil** [comment]
Own package built by @christmart

**Comment by christmart** [comment]
> Own package built by @christmart By the way, one more change with the newer version is that the --daemon argument has to be dropped in the ExecStart of the systemd service.

It's the version 4.5.2-3.1 from Debian 11/bullseye rebuild for Ubuntu 20.04. This version is also in Ubuntu jammie and kinetic.

**Comment by kepstin** [comment]
When I was setting up my TURN servers, I was running into a similar problem where it would stop accepting new connections. From my investigation, it appeared to be related to bugs with how coturn handles its logs and log rotation. I ended up making the following configuration changes:

In `/etc/turnserver.conf` I disabled logging to stdout and disabled the integrated log rotation.
```
no-stdout-log
log-file=/var/log/turnserver/turnserver.log
simple-log
```

I added a systemd override file `/etc/systemd/system/coturn.service.d/logging.conf` which ensures that the logging configuration is applied on the command line (since the configuration file doesn't get read until after it already starts logging). I also bump up the file descriptor limit, since the default is kinda low and I occasionally observed coturn logging that it had run out of file descriptors and could not accept more connections. The command here is expected to be used with Ubuntu (`Type=forking`); you will need to drop the `--daemon` and `--pidfile` options on Debian.
```
[Service]
LimitNOFILE=1048576
ExecStart=
ExecStart=/usr/bin/turnserver --daemon -c /etc/turnserver.conf --pidfile /run/turnserver/turnserver.pid --no-stdout-log --simple-log --log-file /var/log/turnserver/turnserver.log
```

And finally, I add a logrotate configuration to `/etc/logrotate.d/coturn`, since coturn is no longer rotating its own log files.
```
/var/log/turnserver/*.log
{
	rotate 7
	daily
	missingok
	notifempty
	compress
	compressdelay
	postrotate
		/bin/systemctl kill -s HUP coturn.service
	endscript
}
```

I've had my TURN servers running without any lockups for the past few years with this configuration. I'd love to hear any feedback from other people.

**Comment by Ithanil** [comment]
@kepstin Amazin insights, thanks a lot for sharing your knowledge about this issue.

**Comment by ffdixon** [comment]
There is also a 4.6.2 release last week from the coturn project, see

   https://github.com/coturn/coturn/releases/tag/4.6.2

**Comment by hostbbb** [comment]
so looking at the turnutils_client,

/usr/bin/turnutils_uclient -t -p 443 -W anysecret -e 1.1.1.1 -c -n 0 51.xxx.xxx.157

with embeded turn i get a "recv: Success" after 30 seconds on a working turn with and without the correct turn secret..  Is this delay what you see?  

I had a few turns hang last week,  will try this on the next one to see if fail to connect is detected.

will also apply the recommended logging and config changes as suggested.

**Comment by TelekomHacker** [comment]
No Issues anymore since we updated coturn to 4.5.2 and use bigbluebutton 2.6 with external turn server.

**Comment by GhaziTriki** [comment]
@Ithanil Did you just follow the instructions compiling it to proceed with the updates https://github.com/coturn/coturn#building ?

**Comment by Ithanil** [comment]
@christmart Needs to comment on that, he built the package. (But I guess so, yes)

Regarding the stability, we have the internal TURN setup with 4.6.2 productive since about two months now, with hundreds of meetings per day and so far already hit around 200 concurrent users in a single meeting (maybe even more and I didn't notice it). Since switching to 4.6.2 there was not a single report about the typical connection problems related to TURN malfunction.

A little side note: As expected, CPU usage is somewhat increased with the local TURN setup. But according to our stress testing, we should still be able to safely serve 500-600 users in a single meeting when configuring 4 VMs on 2 AMD EPYC 7413 24-Core processors.

**Comment by christmart** [comment]
@GhaziTriki 
> @Ithanil Did you just follow the instructions compiling it to proceed with the updates https://github.com/coturn/coturn#building ?

No. I used the debian/master branch from https://github.com/coturn/coturn.git. From this branch the debian package is build. I just ran a package build in a Ubuntu/focal builder.

**Comment by pielonet** [comment]
Hi,

We faced the very same issue the last two days when trying to deploy 2.6.10.

@christmart Can you provide us with the deb package of Coturn 4.6.2 for Ubuntu 20.04 and handle it to BlindSide Networks so it can be added to the official BBB release ? Or better create a ppa on launchpad.net ?

Kind regards,
Thierry

**Comment by Ithanil** [comment]
@christmart has created a PPA: https://launchpad.net/~martin-uni-mainz/+archive/ubuntu/coturn

We use it with the following patch to default /etc/systemd/system/coturn.service.d/override.conf:
```
--- old/etc/systemd/system/coturn.service.d/override.conf	2023-03-31 10:03:21.728790967 +0200
+++ new/etc/systemd/system/coturn.service.d/override.conf	2023-03-31 10:07:32.547265234 +0200
@@ -1,6 +1,5 @@
 [Service]
 LimitNOFILE=1048576
-AmbientCapabilities=CAP_NET_BIND_SERVICE
 ExecStart=
-ExecStart=/usr/bin/turnserver --daemon -c /etc/turnserver.conf --pidfile /run/turnserver/turnserver.pid --no-stdout-log --simple-log --log-file /var/log/turnserver/turnserver.log
+ExecStart=/usr/bin/turnserver -c /etc/turnserver.conf --pidfile= --no-stdout-log --simple-log --log-file /var/log/turnserver/turnserver.log
 Restart=always
```
I would also suggest to consider https://github.com/bigbluebutton/bbb-install/pull/668

Cheers

**Comment by ffdixon** [comment]
Hi @Ithanil - thanks for sharing this!

**Comment by ffdixon** [comment]
Added to BigBlueButton 2.7-beta install: https://github.com/bigbluebutton/bbb-install/pull/670.  Will backport to 2.6 after community testing.
