### ISSUE TITLE
hidePresentation=true prevents uploading/managing presentations within the client

### ISSUE THREAD

**Issue by Ithanil** [bigbluebutton/bigbluebutton#16716]
**Describe the bug**
If `hidePresentation` is set to true either via bbb-html5.yml or `DEFAULT_JOIN_PARAMS=userdata-bbb_hide_presentation=true` in scalelite, the button to "Manage presentations" will not exist anymore:

![hidePresentation_bug](https://user-images.githubusercontent.com/5860369/218667419-b287fb1f-96de-428f-8251-40794503f911.png)

According to my understanding, hidePresentation should only hide the presentation on startup and not prevent management of presentations completely. If that understanding is incorrect, I think there needs to be a possibility to achieve the described effect.

Likely related to: https://github.com/bigbluebutton/bigbluebutton/pull/16597

**To Reproduce**
1. Set `hidePresentation=true`
2. Join a meeting.
3. Click on + icon.
4. No "Manage presentations" button is present.

**Expected behavior**
The presentation area should be hidden at start, but it should still be possible to manage/upload presentations if desired.

**Actual behavior**
The presentation area is hidden at start and can be unhidden, but it is not possible to manage/upload presentations.

**BBB version:**
- BigBlueButton Server 2.6.0-rc.3 (877)
- Browser Chromium, Firefox

**Comment by antobinary** [comment]
Thanks for reporting this and your other 3 recent findings!
