### ISSUE TITLE
First slide appears on slide transition later on

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#16725]
**Describe the bug**
When changing slides 1-2-3-4-5....
the slides displayes are 1-2-3-**1**-5...

**To Reproduce**
1. Join as Moderator M and viewer V in adjacent windows
2. M goes through the slides

**Expected behavior**
Expect slides to flow in order

**Actual behavior**
The first slide is inserted from time to time. Also there's an unnatural flash happening (see videos attached)

**Screenshots**
![Screenshot from 2023-02-14 16-42-46](https://user-images.githubusercontent.com/6312397/218870013-f470bc3e-f45c-4aee-868e-2a34d9c7df79.png)

[Screencast from 2023-02-14 04:38:17 PM.webm](https://user-images.githubusercontent.com/6312397/218869708-2a25baff-37c3-46e0-ba0f-b9aec69d3290.webm)
[Screencast from 2023-02-14 04:37:07 PM.webm](https://user-images.githubusercontent.com/6312397/218869723-0d100e5d-0f71-41c0-8f77-469a2e928c86.webm)

**BBB version:**
BigBlueButton 2.60.-rc.3 but previous too, 2.5 included (I think)

**Comment by antobinary** [comment]
Custom made presentation 
[0-14 (1).pdf](https://github.com/bigbluebutton/bigbluebutton/files/10737257/0-14.1.pdf)

**Comment by antobinary** [comment]
Switching 0-14 quickly results in lots of green slides 0
![Screenshot from 2023-02-14 17-05-58](https://user-images.githubusercontent.com/6312397/218874056-b6679400-9fb2-4156-b4b2-6a513b12972b.png)

**Comment by antobinary** [comment]
Looks like on every slide change in bbb-html5-backend we change 2 documents - the old current slide (make it current=false) and the new one (make it current=true) https://github.com/bigbluebutton/bigbluebutton/blob/v2.6.0-rc.3/bigbluebutton-html5/imports/api/slides/server/modifiers/changeCurrentSlide.js

Idea:
Introduce `currentPresentation: somePresentationId` with `currentSlide: someSlideId` so that when we change from slide 2 to slide 3, we only change one spot -- `currentSlideId` value.

This may also address a rare issue where the presenter's client would have state currentSlide = A but viewers would see slide A -1; when the presenter advances, locally the slide would be A+1 but for everyone else it would be A


Alternatives are welcome

**Comment by SamuelWei** [comment]
I was also able to reproduce this, looks quite strange if you click through the slides quickly
