### ISSUE TITLE
Connection-status entries gone when the user leaves

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#16724]
**Describe the bug**

The "Session logs" tab is supposed to list the history of connection troubles in the meeting. It is only visible to moderators.
![Screenshot from 2023-02-14 16-05-03](https://user-images.githubusercontent.com/6312397/218863031-2a5fd53c-f414-4165-857d-2cc49970fb5f.png)

However, looks like we clear the data about the user experiencing connection troubles as soon as the user is gone. This means that the moderator will only see a list of people who are moderately struggling with connection issues, but if the issue is so bad that it causes a disconnect, the user will no longer be listed. Therefore the logs lose quite a bit of their utility and purpose.

**To Reproduce**
1. Join a meeting with moderator M and viewer V in two separate browser windows
2. In the window for M, open connection status and switch to the Session logs tab
3. in the window for V, refresh (or trigger a disconnect but that's tricky).

**Expected behavior**
M should see that V lost connection (it happens) and if V can't remain connected, M should have an entry for the rest of the meeting.

**Actual behavior**
V only appears for little time and then the row is gone

**Screenshots**

I am attaching a video of what happens
[Screencast from 2023-02-14 04:15:30 PM.webm](https://user-images.githubusercontent.com/6312397/218865002-8f552ed2-a981-4cbd-bf73-67bfb4272b52.webm)

**BBB version:**
BigBlueButton 2.6.0-rc.3~4

**Comment by antobinary** [comment]
in https://github.com/bigbluebutton/bigbluebutton/pull/11722 the idea was (iirc) to store minumum set of info

**Comment by gustavotrott** [comment]
The current behavior of this component keeps the user in the list once he changes the connection status to something different from 'normal'.

But the "Client not responding" message is handled differently!
This message is shown only while user is still not responding, and it hides once he sends the status again.

In short: In your example the user was removed because he never changed the connection STATUS! If it was the case the user would be kept in the list for future analysis.

**Comment by linuxmangr** [comment]
Hello to all.
The connection-status  tool is very good.
But when I start the meeting I see only the my connection status.
What I need the change to see all users connection-status.
My version BBB is 
BigBlueButton Server 2.6.0 (1022), Kernel version: 5.4.0-176-generic, Distribution: Ubuntu 20.04.6 LTS (64-bit)
The Greenlight version is v2
What I need to do see all users connection-status?
