### ISSUE TITLE
[2.6-rc3] Metrics stopped working.

### ISSUE THREAD

**Issue by JeanPluzo** [bigbluebutton/bigbluebutton#16728]
**Describe the bug**
When installing/updating, metrics stopped working

**Installation type**
Installed/updated using the bbb-install-2.6.sh script: `bbb-install-2.6.sh 

**Firewall and IP address type**
BBB Server is behind a FW and has it's own IP Address

**Console output**
There's nothing wrong to show here. Everything went smooth.

**Additional context**
It seems that the install script erased my `monitoring.nginx` file in `/usr/share/bigbluebutton/nginx`. This is not the main problem since redoing said file solved that. 
However, the bbb-exporter docker container keeps on restarting with following output:
`bbb-exporter   | 2023-02-15 15:44:53,006 [INFO]: Enabling recordings metrics read from disk, we will not request expensive recordings metrics via the API`
`bbb-exporter   | 2023-02-15 15:44:53,007 [INFO]: HTTP server started on 0.0.0.0:9688`
`bbb-exporter   | 2023-02-15 15:44:53,007 [INFO]: Collecting metrics from BigBlueButton API`
`bbb-exporter   | Traceback (most recent call last):`
`bbb-exporter   |   File "server.py", line 46, in <module>`
`bbb-exporter   |     REGISTRY.register(collector)`
`bbb-exporter   |   File "/usr/local/lib/python3.8/site-packages/prometheus_client/registry.py", line 24, in register`
`bbb-exporter   |     names = self._get_names(collector)`
`bbb-exporter   |   File "/usr/local/lib/python3.8/site-packages/prometheus_client/registry.py", line 64, in _get_names`
`bbb-exporter   |     for metric in desc_func():`
`bbb-exporter   |   File "/app/collector.py", line 74, in collect`
`bbb-exporter   |     yield self.metric_recordings_unpublished(bbb_api_latency)`
`bbb-exporter   |   File "/app/collector.py", line 191, in metric_recordings_unpublished`
`bbb-exporter   |     recording_unpublished_data, recording_unpublished_latency = execution_duration(api.get_recordings)("unpublished")`
`bbb-exporter   |   File "/app/helpers.py", line 19, in wrapper`
`bbb-exporter   |     result = fun(*args, **kwargs)`
`bbb-exporter   |   File "/app/api.py", line 46, in get_recordings`
`bbb-exporter   |     if data['response']['recordings'] is None:`
`bbb-exporter   | KeyError: 'recordings'`
`bbb-exporter exited with code 1`

Perhaps its a bug/problem in the bbb-exporter container. This, however, was not happening before I did an update to rc3.
Should more info be needed I'll be glad to help.
Regards,
J.

**Comment by ffdixon** [comment]
Hi Jean, I'm the maintainer for `bbb-install`.

> It seems that the install script erased my `monitoring.nginx`

That's strange.  Unless I'm missing something, there isn't any code there to delete files in `/usr/share/bigbluebutton/nginx`.

> However, the bbb-exporter docker container keeps on restarting with following output:

Would it be possible to setup a 2.6-rc.2 server, and point `bbb-exporter` to that server.  Does it now work without restarting.  That would help narrow down if something change in 2.6-rc.3 or something else is tripping up `bbb-exporter`.

**Comment by sbt1021** [comment]
After I upgrade from 2.5.x to 2.6.0-rc3, I am getting the same error.

![Screenshot 2023-02-17 at 10 09 17](https://user-images.githubusercontent.com/112631761/219574528-1f86a9d6-6ae0-45c0-998b-25915e84b363.png)

![Screenshot 2023-02-17 at 10 09 04](https://user-images.githubusercontent.com/112631761/219574535-287e17bb-bab2-4396-a6dd-07c54d085d88.png)

![Screenshot 2023-02-17 at 10 11 21](https://user-images.githubusercontent.com/112631761/219574689-a0f03282-ba06-4839-8e70-64dde599c5ab.png)

**Comment by ffdixon** [comment]
Hi Guys, can you open an issue with the devs for [bbb-exporter](https://github.com/greenstatic/bigbluebutton-exporter/issues) and reference this issue.  

I'm not a python programmer myself, so it would be easier to collaborate with others on resolving this.

**Comment by antobinary** [comment]
Cross-referrencing https://groups.google.com/g/bigbluebutton-dev/c/0mDHoBj4UZU

**Comment by JeanPluzo** [comment]
Hi everyone,
just posted the issue on [greenstatic/bigbluebutton-exporter](https://github.com/greenstatic/bigbluebutton-exporter/issues/118)
And also: just updated to 2.6-rc4. Problem is still happening.
@ffdixon : right now I can't setup a new server, but I'll try to do this in a few weeks.

Regards,
J.

**Comment by Wladimir-N** [comment]
> Hi everyone, just posted the issue on [greenstatic/bigbluebutton-exporter](https://github.com/greenstatic/bigbluebutton-exporter/issues/118) And also: just updated to 2.6-rc4. Problem is still happening. @ffdixon : right now I can't setup a new server, but I'll try to do this in a few weeks.
> 
> Regards, J.

https://github.com/greenstatic/bigbluebutton-exporter/pull/116

**Comment by JeanPluzo** [comment]
Hi everyone,
issue seems to be solved. See [this issue](https://github.com/greenstatic/bigbluebutton-exporter/issues/118).
The solution is to pull the new `v0.6.1` image from the docker hub.
Metrics are running fine again in my 2.6-rc4 server.

Regards,
J.
