### ISSUE TITLE
Implement disabledFeatures=presentationArea

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#16734]
**Describe the bug**
Looks like #16716 and #16726 handled the join parameter to no longer display the presentation. However, seems the name was misleading as it actually was implemented and documented as disabling the presentation area display altogether (for that user).

https://docs.bigbluebutton.org/admin/customize.html

![Screenshot from 2023-02-16 01-25-06](https://user-images.githubusercontent.com/6312397/219286196-6a42b550-3a3c-4b2c-a10b-cc82e1c6df9d.png)

Now, I strongly believe we incorrectly implemented this as a JOIN parameter instead of a CREATE parameter (all uses I know of send this parameter to all users in the meeting).

**Proposition**

1) Implement the same functionality we removed in #16726 as a CREATE parameter in the `disabledFeatures` group (see API page https://docs.bigbluebutton.org/dev/api.html)
2) check with @ramonlsouza and @Ithanil on whether `userdata-bbb_auto_swap_layout` would have been what was desired
2.1) revert #16726 so that we don't break the client for people who migrate to 2.6
2.2) mark `userdata-bbb_hide_presentation` as deprecated in the docs
2.3) open an issue tagged to 3.0 milestone to remove the code just like in #16726

**Comment by antobinary** [comment]
I am marking this as priority:high because we actually broke the existing customization option and don't offer an alternative

**Comment by Ithanil** [comment]
We do use autoSwapLayout in BBB 2.5 to achieve the desired effect, so your proposition 2) would serve us well.

Regarding Prop 1), in that context I'd also like to point towards my proposal https://github.com/bigbluebutton/bigbluebutton/issues/16693 .

Thank you very much for looking into this!

**Comment by ramonlsouza** [comment]
I think adding it as a create parameter (in disabledFeatures) makes sense. 
There was a lot of confusion (and issues) about how `hide_presentation` and `auto_swap_layout` should work in BBB 2.5 and 2.6

**Comment by ramonlsouza** [comment]
> Regarding Prop 1), in that context I'd also like to point towards my proposal #16693 .

@Ithanil in BBB 2.6 there is a way to synchonize display/hide presentation for users in a meeting, using _custom layout + push layout to all_ (if both are enabled, the presentation will be closed for all participants when the presenter closes it)

![Screenshot from 2023-02-16 08-47-25](https://user-images.githubusercontent.com/3728706/219357125-778bcd80-39d4-4f55-8967-3e37979bb5cf.png)

**Comment by Ithanil** [comment]
> I think adding it as a create parameter (in disabledFeatures) makes sense. There was a lot of confusion (and issues) about how `hide_presentation` and `auto_swap_layout` should work in BBB 2.5 and 2.6.
> 
> We can do what's described in proposition 1 ... and make "hidePresentation" work as swapLayout was on 2.5 (it already is, on current 2.6.x) and then when upgrading from 2.5 to 2.6 these parameters should work like:
> 
> 2.5 join hidePresentation -> 2.6 create disabledFeatures=presentationArea (permanent disabling of presentation area for all users) 2.5 join swapLayout -> 2.6 join hidePresentation (join a meeting with presentation area hidden, not permanent)

Excellent solution! Seems intuitive too.

**Comment by gustavotrott** [comment]
Settled in #16769.

The new option is `disabledFeatures=presentation`.
