### ISSUE TITLE
BigBlueButton for Wordpress Plugin

### ISSUE THREAD

**Issue by amishbhavsar** [bigbluebutton/bigbluebutton#16733]
Hi,
The BigBlueButton for Wordpress hasn't been updated since mover than 3 years.
Is there any roadmap to update this plugin to add the new capabilities like ability to upload files from NextCloud?

**Comment by FreeScholar** [comment]
If more Greenlight functionality for configuring could be added to the WP plugin - that would be awesome. 
I did find this thread - https://groups.google.com/g/bigbluebutton-dev/c/rRGAs29xqCQ/m/FXsEswuNAgAJ
Looking through the issues there to see what I can find.

**Comment by ffdixon** [comment]
Hi @amishbhavsar,

No plans for the BigBlueButton team to update the plugin at the moment.  We've been working on an updated version of GreenLight that will serve as a stand-alone front-end to BigBlueButton.
