### ISSUE TITLE
BBB Recording limit - BBB 2.6 RC3

### ISSUE THREAD

**Issue by amishbhavsar** [bigbluebutton/bigbluebutton#16757]
**Describe the bug**
BBB version 2.6 RC 3 does not do recording beyond 37 minutes and 54 seconds. The recording automatically stops

**To Reproduce**
1. Start BBB class
2. Enable recording
3. Let class run for over 45 mins with recording on.
4. Recording will stop at 37.54

**Expected behavior**
Recording should continue for the entire length of the class

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [Chrome]
 - Version [latest]

**Comment by hostbbb** [comment]
Is this repeatable?  
What were the params used on the create call?  was recording automatically started, or do you press the start button.

When a meeting is created, the duration starts.     But the recording is not going to start until a user actually joins,  so it is possible for the recording duration to be less than the meeting duration.    Also if you use start/stop segments are combined

regards,
Stephen

**Comment by amishbhavsar** [comment]
Pls close this as I am not able to reproduce this on BBB 2.6 RC3.
Also, I updated to BBB 2.6 RC4. I will let you know if I come across any issues in RC4.
