### ISSUE TITLE
2.6 RC4  VIDEO Playback URL error without ending / creates "Site can't be reached"

### ISSUE THREAD

**Issue by hostbbb** [bigbluebutton/bigbluebutton#16756]
**Describe the bug**
The new playback url for video format has a / on end of url,  where the presentation format does not.

This following happens with HAPROXY/Embedded turn install on 2.6 RC4

getRecordings provide the following.
<type>video</type>
<url>https://xxxx.cloud/playback/video/23b24f48b071993b69b5fdb4d517f6cbbd613753-1676672009993/</url>
<type>presentation</type>
<url>https://xxxx..cloud/playback/presentation/2.3/23b24f48b071993b69b5fdb4d517f6cbbd613753-1676672009993</url>

Entering URL into browser and omitting the ending / returns an error... haproxy says "Site can't be reached"
  https://xxxx.cloud/playback/video/23b24f48b071993b69b5fdb4d517f6cbbd613753-1676672009993

haproxy says "Site can't be reached" with this non secure url returned in browser.
http://xxx.cloud:82/playback/video/23b24f48b071993b69b5fdb4d517f6cbbd613753-1676672009993

Desired behavior
The ending / should not be required and consistent with presentation url.  I can see users sending the link the others copying the url without causing issues.

**Comment by kepstin** [comment]
The nginx configuration for the recording format is set up correctly and generates the right redirects. I have verified the behaviour on the dev26.bigbluebutton.org server.

The problem that you are hitting is related to the haproxy / TURN server configuration set up by bbb-install. I have opened an issue to track that: https://github.com/bigbluebutton/bbb-install/issues/631
