### ISSUE TITLE
Shared notes (re-)appear as "changed" even without changes

### ISSUE THREAD

**Issue by tibroc** [bigbluebutton/bigbluebutton#16767]
**Describe the bug**
The shared notes appear as "changed" even when they are not changed:
![image](https://user-images.githubusercontent.com/39943803/220164955-fe625002-8d91-424d-a6bc-ddaadb484818.png)

This indicator disappears when opening the shared notes (as it should), but reappears after closing and re-opening the side bar, even without changes.

**To Reproduce**
1. Go to shared notes
2. Close the sidebar
3. See the red dot at 'user list toggle' appear
4. Open the user list to see the change-indicator for the shared notes appear

**Expected behavior**
The red dot at 'user list toggle' and the change-indicator for the shared notes should not show again after closing the user list (at least not if there are no changes).

**Screenshots**
![image](https://user-images.githubusercontent.com/39943803/220165958-5a151c9d-da3b-40c6-b731-24099610699b.png)
no change indicators, after opening shared notes

![image](https://user-images.githubusercontent.com/39943803/220166095-5bdbd1e0-6870-4162-ad3d-f51c4c81e97e.png)
The red dot appears after closing the user list.

![image](https://user-images.githubusercontent.com/39943803/220166187-d8770f2f-801d-4833-b16d-8ac05eaed82a.png)
The change-indicator for the shared notes appears as well (no changes were made).

**BBB version:**
2.6.0-rc.3

**Desktop (please complete the following information):**
 - OS: Fedora, Ubuntu
 - Browser: Chrome (110.0.5481.77)

**Comment by antobinary** [comment]
Hi @tibroc !
Thanks for reporting! This was actually just fixed in the newly released rc.4
See https://github.com/bigbluebutton/bigbluebutton/pull/16703

Are you able to reproduce it on rc.4? For example test26.bigbluebutton.org?
