### ISSUE TITLE
Adding new empty slides

### ISSUE THREAD

**Issue by SamuelWei** [bigbluebutton/bigbluebutton#16766]
**Is your feature request related to a problem? Please describe.**
During a lecture a topic may occur by questions of the students. Currently you need to have some blank slides at the end of your presentation to have some space to explain the topic in more detail, however in the downloaded file the order would be "wrong"

**Describe the solution you'd like**
Beeing able to inset blank slides (empty or based on a template file) at any point in the presentation.
These added slides should be part of the file with annotation that can be downloaded.
Bonus: Be able to delete slides if not needed (anymore)

**Comment by ffdixon** [comment]
Hi @SamuelWei -- it's a good suggestion and one we've been thinking about for a long time.  You can think of the work to incorporate tldraw as a foundational piece for this effort.  

There are some changes needed in BigBlueButton to support adding of a blank slide as you described, and it's a feature that we (the core developers) want to add as well in the future.

If your developer chops are up to the task, and your interested in trying to add this capability to BigBlueButton, let us know.  We're interested to work with you on it.

**Comment by ffdixon** [comment]
Hi @SamuelWei.  Not that tldraw has landed in 2.6, we're looking into how we can build upon tldraw and add this in a future version of BigBlueButton.

**Comment by SamuelWei** [comment]
Please reopen
