### ISSUE TITLE
Polling responds very slow with large number of participants

### ISSUE THREAD

**Issue by tibroc** [bigbluebutton/bigbluebutton#16781]
**Describe the bug**
We just had a a Meeting with >170 Participants that featured a lot of polls. Polls were working fine, however, after clicking an answer it took 4-10 seconds for the poll modal to disappear.

**To Reproduce**
1. Open a poll in a big meeting.
2. Click on an asnwer.
3. Wait.

**Expected behavior**
Responsive closing of the modal directly after choosing an option (as is the case in smaller meetings).

**Actual behavior**

**Screenshots**

**BBB version:**
2.5.11

**Desktop (please complete the following information):**
 - OS: Fedora
 - Browser Chrome, Firefox

**Comment by ffdixon** [comment]
We want to try this with 2.7 (and even 3.0) at the upcoming developer summit.
