### ISSUE TITLE
2.6 RC4  getRecordings returns different response with combined presentation and video formats.

### ISSUE THREAD

**Issue by hostbbb** [bigbluebutton/bigbluebutton#16791]
**Describe the bug**
1) getRecordings returns state as "available" not "published" when a presentation and video exist for recordID
2) getRecordings does not return internalMeetingID, and the meetingID is set to the internalID incorrectly.

See getRecordings responses for a meeting with just presentation, and then for presentation and video,  also the raw video/metadata.xml and presentation/metadata.xml differences.

**To Reproduce**
1. configure video recording format.
2. record a meeting
3. call get recording and see the state is available, not published.

get recordings returns 1 state, for 2 formats with different state, and looks like video state is passed and not presentation.

DATA to compare.

**getRecordings with just a presentation format.**

`<response>
<returncode>SUCCESS</returncode>
<recordings>
<recording>
<recordID>bd21c297d4802287470458700b2406e5bdede31a-1677082241715</recordID>
<meetingID>tqqhefja6ddk22jw58gygx3ja60vzflqizr8bhdp</meetingID>
<internalMeetingID>bd21c297d4802287470458700b2406e5bdede31a-1677082241715</internalMeetingID>
<name>Home Room</name>
<isBreakout>false</isBreakout>
<published>true</published>
<state>published</state>`

Notice the internalMeetingID is here and not in one below.
state is published

**getRecordings with both presentation and video formats.**

`<response>
<returncode>SUCCESS</returncode>
<recordings>
<recording>\n
<recordID>25042a370c1789668c0b4afdb7d80c0a1e0f908a-1677070501610</recordID>
<meetingID>25042a370c1789668c0b4afdb7d80c0a1e0f908a-1677070501610</meetingID>
<name>Virtual Class</name>
<isBreakout>false</isBreakout>
<published>true</published>
<state>available</state>`

Notice no InternalMeetingID, and the MeetingID is correctly the internalID
state is available not published.

**presentation metadata.xml**
`<recording>
  <id>25042a370c1789668c0b4afdb7d80c0a1e0f908a-1677070501610</id>
  <state>published</state>
  <published>true</published>`

**video metadata.xml**
`<recording>
  <id>25042a370c1789668c0b4afdb7d80c0a1e0f908a-1677070501610</id>
  <state>available</state>
  <published>true</published>`

**Comment by antobinary** [comment]
Thanks for reporting @hostbbb !

**Comment by paultrudel** [comment]
Hi, when a recording has a video the state is set to `available` instead of `published`. This is done by the video processing script [here](https://github.com/bigbluebutton/bigbluebutton/blob/develop/record-and-playback/video/scripts/process/video.rb#L277).

**Comment by hostbbb** [comment]
Yes,  the issue is when getRecordings returns multiple formats, like presentation and video,   the normal "published" state for the response goes to "available" breaking older integrations that expect "published"

Moodle handles fine since it ask for ANY state.
Greenlight has its own meta fields for visibility.

I just changed it in video.rb to published for our clusters and handle these integrations that dont handle state available.

thanks

**Comment by dmtrhfr** [comment]
I had actually some issues with greenlight Processing the xml responses, when I cam across the fact, taht the respsonse changed for some reason compared to 2.5 - would be great to have this working again.
