### ISSUE TITLE
Detatch polls from presentation

### ISSUE THREAD

**Issue by GuiLeme** [bigbluebutton/bigbluebutton#16808]
**Describe the bug**

This is not exactly a bug, it's more of a  change of behavior request. So, now our poll component is deeply dependent of presentation, and this would not be the expected behavior (mainly with recent changes that you can publish poll results on chat). This slight issue has became more highlighted now since the presentation component is about to be a part of the `disabledFeatures` list with the PR https://github.com/bigbluebutton/bigbluebutton/pull/16769, but it already happened when deleting all documents from the presentation-uploader component.

**Expected behavior**

If presentation is disabled I expect to be able to start a poll and even publish the results on chat, and if the chat is also disabled, I would still expect to be able to start a poll, not necessarily publishing it anywhere though.

**Actual behavior**

If presentation is not enabled or there are no documents to be shown in presentation area, poll functionality is also blocked.

**Screenshots**

When trying to start a poll form the dropdown menu with the PR https://github.com/bigbluebutton/bigbluebutton/pull/16769, this is what we get:

![Screenshot from 2023-02-23 16-40-57](https://user-images.githubusercontent.com/69865537/221251136-9192a943-da44-470d-bb68-f4f5c9d85931.png)

**Possible solution**

If applicable, it would be great to just let the user start a poll if either of the publishing components is disabled (chat or presentation), and if the user tries to publish the results, we make a validation:

- If presentation enabled -> show on presentation;
- If chat enabled -> show on chat;
- if none is enabled -> show error message saying it is not possible to publish due to not having any mean to do it.

For now, the behavior after this PR will be to just hide the button to start a poll, so after all these had been solved, please remove the hide of the start poll button.

**Highly related to:** https://github.com/bigbluebutton/bigbluebutton/issues/12141

**Comment by selyod-ka** [comment]
I'd like to add to this issue:
If you start a room with `disabledFeatures=presentation`, there is no option to start a poll (in BBB-2.6.10). Using `disabledFeaturesExclude=polls` does not change the behaviour.
So at the moment there is no way to start a poll if presentations are disabled.
