### ISSUE TITLE
Missing services from bbb-conf --status

### ISSUE THREAD

**Issue by GhaziTriki** [bigbluebutton/bigbluebutton#16815]
Some services are not listed in bbb-conf --status.

- bigbluebutton (/lib/systemd/system/bigbluebutton.target)
- bbb_record_core
- ufw
- coturn
- docker (used for doc conversion)
- haproxy

@ffdixon I will send a PR. Do you see any missing service or a unit we should not list?

**Comment by antobinary** [comment]
Greenlight perhaps?

ufw is not exactly a service in BBB though. I am not sure it belongs to the list...
docker -- we spin up ephemeral containers so in some moments there could be a few but in typically none [running]. Listing this and showing it as not running could be confusing. I am not sure it belongs to the list...
bbb-record-core -- do you want to show whether recordings are being processed?

This brings up a conversation on whether a `bbb-conf --configuration` or `--list-overrides` is needed. That would be a summary of the modules you wanted set up (mostly flags in bbb-install) + line by line comparison showing anything we override in terms of component settings. For example if you added two new overrides in `bbb-web.properties`  but one of them is same as the default, only list the server name, server salt (marked as changed, not necessarily revealing it), and the overriden property, excluding the one that matches the default.
