### ISSUE TITLE
[2.6] Firefox takes a long time to display graphics in presentations

### ISSUE THREAD

**Issue by einhirn** [bigbluebutton/bigbluebutton#16826]
**Describe the bug**
With Firefox, it takes a long time to display the embedded graphic files (PNG or JPEG) in presentations. The text elements on the slide are displayed immediately and then it can take a few seconds for the graphics to be displayed. With Chrome there is no such problem.

**To Reproduce**

1. Join a meeting with a moderator (presenter) and two viewers (one using Chrome and the other using Firefox)
2. Upload a presentation with several PNG and JPEG graphics
3. e.g. https://github.com/bigbluebutton/bigbluebutton/files/9810570/Smart.Slides.Test.pptx
4. The presenter switches the slides and looks how long it takes for the slides to be fully displayed to the two viewers.

**Expected behavior**
The slides should be displayed in complete immediately for all participants.

**Actual behavior**
In Firefox, the text is loaded first, and it may take a few seconds for the graphics to be displayed as well.

**BBB version**
BigBlueButton version: 2.6.0-rc.5, Client build: 430
Browser: Firefox 110.0, Windows 10

**Comment by mwuttke** [comment]
I can understand the error/behavior with BBB version 2.6-rc.5 and Firefox version 110 on Linux Mint as well.

**Comment by einhirn** [comment]
This is still happening in 2.6-rc.7
