### ISSUE TITLE
[2.6] Bugs in the exported PDF of the whiteboard

### ISSUE THREAD

**Issue by einhirn** [bigbluebutton/bigbluebutton#16827]
**Describe the bug**
I tested a little with the whiteboard and found some errors in the PDF export:

- The page is cut off
- The font family of the annotations is not correct
- There are escape characters in the text

**To Reproduce**

1. Switch to slide 2 of the BBB default presentation
2. Write some text with different font families (script, sans, serif, mono)
3. Write some text with special characters
4. Put text objects in the corners of the slide
5. Export the presentation as PDF file (send to chat)
6. Compare the content of the whiteboard with the content in the PDF file. Have a look where the page are cut off.

**Expected behavior**
The content in the PDF file should be the same as displayed on the whiteboard.

**Actual behavior**
There are discrepancies between the display on the whitebaord and the content of the PDF file. In particular, the page is cut off on the right side.

**Screenshots**
![Screenshot 2023-02-27 180711](https://user-images.githubusercontent.com/189249/221632218-e945db67-d548-477b-aba5-90d8e74dd796.png)
[annotated_slides (8).pdf](https://github.com/bigbluebutton/bigbluebutton/files/10842201/annotated_slides.8.pdf)

**BBB version**
BigBlueButton version: 2.6.0-rc.5, Client build: 430
Browser: Chrome Version 110.0.5481.178, Windows 10

**Comment by danielpetri1** [comment]
Thanks for reporting this. The PR above prevents the page from appearing cut off and stops escaping hyphens with a slash.

To display the font family, there currently is this workaround:

```bash
apt install bbb-presentation-video
cp /usr/share/bbb-presentation-video/bbb_presentation_video/renderer/tldraw/fonts/* /usr/local/share/fonts/
fc-cache -f -v
```
