### ISSUE TITLE
[2.6] restoreOnUpdate does not work when switching presentation

### ISSUE THREAD

**Issue by einhirn** [bigbluebutton/bigbluebutton#16824]
**Describe the bug**
If hidePresentation and restoreOnUpdate are both set to true, the presentation area will still remain hidden when loading a new presentation or switching to another presentation.

**To Reproduce**

1. Set Smart-Layout as default
2. Set hidePresentation = true and restoreOnUpdate = true
3. Join a meeting with a moderator (presenter) and a viewer
4. Upload a new presentation
5. Wait until the conversion is completed
6. Switch between the new presentation and the default presentation

**Expected behavior**
The presentation area should be restored for all participants, when the conversion is completed and when switching to another presentation.

**Actual behavior**
The presentation area remains hidden.

**BBB version**
BigBlueButton version: 2.6.0-rc.5, Client build: 430
Browser: Chrome Version 110.0.5481.178, Windows 10

**Additional context**
I have also tried this with custom layout. There the behavior seems to be very random. For some participants the presentation is restored, for others not. For the presenter it never appears automatically.

**Comment by antobinary** [comment]
Thank you for reporting!
This is closely related to some work in progress https://github.com/bigbluebutton/bigbluebutton/pull/16769

**Comment by antobinary** [comment]
Let's also double check if join parameter `userdata-bbb_force_restore_presentation_on_new_events=` is still behaving properly -- see https://docs.bigbluebutton.org/admin/customize.html#presentation-parameters

**Comment by einhirn** [comment]
`restoreonupdate` still doesn't work reliably when uploading a new presentation, only when changing the presentation. Maybe it's dependent on how long it takes to convert the presentation?
