### ISSUE TITLE
wrong version number in github release page

### ISSUE THREAD

**Issue by afsharsafavi** [bigbluebutton/bigbluebutton#16830]
Hi
I think there is a little mistake at the GitHub release page.
Version 2.6 is in beta state but at the end of 2.6 betas release notes,  you wrote " We still recommend using -v focal-260."
I think it should be " We still recommend using -v focal-250."

**Comment by antobinary** [comment]
Hi @afsharsafavi 

Are you referring to the release notes? This phrase is meant to say that you could install a particular minor version of BBB from the 2.6.x series but if you use focal-260 you always get the latest released version _from the 2.6.x series_ . We could add "We still recommend using -v focal-260 _if you're looking to install BBB 2.6_."
![Screenshot from 2023-02-28 06-35-50](https://user-images.githubusercontent.com/6312397/221842556-d7a029b3-8f86-4178-8b6c-fe15f2605dc2.png)



---

### If you're not referring to those, could you please share a link/screenshot of the context?

**Comment by afsharsafavi** [comment]
‌Yes, I referred to release name. At this sentences:
"We will recommend using -v focal-260"
It should be: "We sill recommend using -v focal-250"
Last night I install with -v focal-260. It has been install version 2.6.0-rc.5 with focal-260.

**Comment by antobinary** [comment]
Hi @afsharsafavi 

I reworded the release notes. This is what they look like now.

![Screenshot from 2023-03-02 08-54-01](https://user-images.githubusercontent.com/6312397/222448288-8a176dba-9347-4e27-ba04-4fc05738d8a2.png)

I hope this makes it clearer!
