### ISSUE TITLE
API to create room with guestPolicy="ALWAYS_DENY" then it deny non guest user too

### ISSUE THREAD

**Issue by heavenknows1978** [bigbluebutton/bigbluebutton#16839]
Dear everyone.

I use BBB 2.5, when create the room with param &guestPolicy=ALWAYS_DENY will allow only moderator to join the meeting, it deny  all this case:   guest=false or guest=true or no guest param. It only allows to join if I set join param :  role=moderator intead of role=viewer. I think that guestpolicy must be applied to guest=true only.

So how to create a room that deny all guest=true access and allow the rest?
Thanks

**Comment by intellecta-lk** [comment]
I'm still having this issue
