### ISSUE TITLE
Virtual background settings contain horizontal scrollbar

### ISSUE THREAD

**Issue by MaximKhlobystov** [bigbluebutton/bigbluebutton#16847]
**Describe the bug**
There's one extra default background image showing up, but the size of the element that contains those images hasn't increased, which causes the horizontal scrollbar to appear.

**To Reproduce**
1. Start a new session
2. Click "Share webcam"
3. Virtual background settings include the horizontal scrollbar

**Expected behavior**
There should be no scrollbar.

**Screenshots**
<img width="227" alt="backgrounds" src="https://user-images.githubusercontent.com/5004762/221933385-e10dba16-10ca-4ae2-bc8c-d4cc78c9eb36.PNG">

**BBB version:**
BigBlueButton 2.6.0-rc.5

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Firefox
 - Version: 110.0

**Comment by Stoppschildgruen** [comment]
@antobinary Would it be possible to reopen the issue and provide a way to remove the scrollbar and display all provided backgrounds in multiple rows?

**Comment by antobinary** [comment]
Hi @Stoppschildgruen
How many images are you looking to display before showing any scrollbar?
This is what the UI is at the moment on BBB 3.0.0-beta.5
![image](https://github.com/user-attachments/assets/2cf1abd8-93a3-4c59-9309-b524be293206)

I.e. you can have all the default images, **two more custom** and still not be seeing scrollbars of any kind

**Comment by Stoppschildgruen** [comment]
Nice! I tried it. Thanks for the quick reply.

**Comment by Stoppschildgruen** [comment]
That's ok. We will upgrade to 3.0 as soon as it is stable.

**Comment by muellerlukas** [comment]
Maybe you can set a own default-css for the users?
 
 We just use:
 `div[data-test="virtualBackground"] {
    flex-wrap: wrap;
}`
