### ISSUE TITLE
bbb install through bbb-install-2.5.sh file fails due to docker problem

### ISSUE THREAD

**Issue by AlexNewr056** [bigbluebutton/bigbluebutton#16846]
**Describe the bug**
Setup a clean server installation (Ubuntu 20.04) and issued the install script right after the first reboot (just made an apt update and apt upgrade before the first reboot)

**Installation type**
Installed through install script with options:
"wget -qO- https://ubuntu.bigbluebutton.org/bbb-install-2.5.sh | bash -s -- -v focal-250 -s "FQDN-from-BBB-Server" -e "E-MAIL-FOR-Let's-encrypt" -w -c "FQDN-from-turn-server":"turn-secret"

**Firewall and IP address type**
No firewall/NAT

**Console output**
...
Setting up bbb-libreoffice-docker (1:2.5-9) ...
#
# Building bbb-libreoffice docker image
#
DEPRECATED: The legacy builder is deprecated and will be removed in a future release.
            Install the buildx component to build images with BuildKit:
            https://docs.docker.com/go/buildx/

Sending build context to Docker daemon  2.048kB
Step 1/2 : FROM amazoncorretto:17-alpine
 ---> 84492b387de7
Step 2/2 : RUN apk add fontconfig libreoffice
 ---> Running in ca935e8c9641
failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: unable to apply apparmor profile: apparmor failed to apply profile: write /proc/self/attr/apparmor/exec: no such file or directory: unknown
dpkg: error processing package bbb-libreoffice-docker (--configure):
 installed bbb-libreoffice-docker package post-installation script subprocess returned error exit status 1
Setting up python3-rfc3339 (1.1-2) ...
Setting up python3-lib2to3 (3.8.10-0ubuntu1~20.04) ...
Setting up python3-distutils (3.8.10-0ubuntu1~20.04) ...
Setting up python3-setuptools (45.2.0-1ubuntu0.1) ...
Setting up python3-pbr (5.4.5-0ubuntu1) ...
update-alternatives: using /usr/bin/python3-pbr to provide /usr/bin/pbr (pbr) in auto mode
Setting up python3-openssl (19.0.0-1build1) ...
Setting up python3-zope.component (4.3.0-3) ...
Setting up python3-mock (3.0.5-1build1) ...
dpkg: dependency problems prevent configuration of bbb-web:
 bbb-web depends on bbb-libreoffice-docker; however:
  Package bbb-libreoffice-docker is not configured yet.

dpkg: error processing package bbb-web (--configure):
 dependency problems - leaving unconfigured
Setting up python3-josepy (1.2.0-2) ...
Setting up python3-future (0.18.2-2ubuntu0.1) ...
update-alternatives: using /usr/bin/python3-futurize to provide /usr/bin/futurize (futurize) in auto mode
update-alternatives: using /usr/bin/python3-pasteurize to provide /usr/bin/pasteurize (pasteurize) in auto mode
Setting up python3-parsedatetime (2.4-5) ...
dpkg: dependency problems prevent configuration of bbb-html5:
 bbb-html5 depends on bbb-web; however:
  Package bbb-web is not configured yet.

dpkg: error processing package bbb-html5 (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of bbb-pads:
 bbb-pads depends on bbb-web; however:
  Package bbb-web is not configured yet.

dpkg: error processing package bbb-pads (--configure):
 dependency problems - leaving unconfigured
Setting up python3-acme (1.1.0-1) ...
Setting up python3-certbot (0.40.0-1ubuntu0.1) ...
Setting up certbot (0.40.0-1ubuntu0.1) ...
Created symlink /etc/systemd/system/timers.target.wants/certbot.timer → /lib/systemd/system/certbot.timer.
dpkg: dependency problems prevent configuration of bbb-config:
 bbb-config depends on bbb-html5; however:
  Package bbb-html5 is not configured yet.

dpkg: error processing package bbb-config (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of bigbluebutton:
 bigbluebutton depends on bbb-config; however:
  Package bbb-config is not configured yet.

dpkg: error processing package bigbluebutton (--configure):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 bbb-libreoffice-docker
 bbb-web
 bbb-html5
 bbb-pads
 bbb-config
 bigbluebutton
E: Sub-process /usr/bin/dpkg returned an error code (1)

Let's encrypt also wasn't able to issue a certificate, but I think that's due to the missing bbb packages.
If I stop the nginx service and let certbot issue the certificate through standalone, getting the certificate works.

The main problem seems to be the libreoffice building process.

**Additional context**
The reason I found this "bug" was a phone call from one of our clients. He reported that converting .pptx files inside the conference isn't working. Upon taking a closer look I found out, that the bbb-soffice docker container isn't working. I tried to convert a .pptx with the "convert-local.sh" file (from "/usr/share/bbb-libreoffice-conversion") but only got the following error: 

"docker: Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: unable to apply apparmor profile: apparmor failed to apply profile: write /proc/self/attr/apparmor/exec: no such file or directory: unknown."

**Comment by AlexNewr056** [comment]
Problem has been solved.
[Apparmor/Docker problem](https://groups.google.com/u/3/g/bigbluebutton-setup/c/JE9vWB526hA)

Before executing the install script on a freshly installed server, install apparmor:

`sudo apt-get install apparmor`

and reboot the server.

After that, the install script should work without errors.
Also works for already installed systems where the upgrade to 2.5.12 fails. (install apparmor, reboot, and update as usually)

**Comment by ffdixon** [comment]
Thanks for sharing this -- it should help others.  [Added this as a dependency](https://github.com/bigbluebutton/bbb-install/commit/3ddafd88da9fc97909a975e09a7e175e678464fe) to `bbb-install.sh`

**Comment by antobinary** [comment]
Related: https://github.com/bigbluebutton/bbb-install/pull/613
