### ISSUE TITLE
Notification of wrong file type: notification text

### ISSUE THREAD

**Issue by MaximKhlobystov** [bigbluebutton/bigbluebutton#16848]
**Describe the bug**
Notification of wrong file type includes the following: `(extension=,content type=)`.

**To Reproduce**
1. Start a new session
2. Attempt to upload a presentation file in `txt` format.
3. Notification contains `(extension=,content type=)`.

**Screenshots**
<img width="218" alt="format" src="https://user-images.githubusercontent.com/5004762/221936151-a9305d79-bfc3-41a7-84d7-9fb5b21180e0.PNG">

**BBB version:**
BigBlueButton 2.6.0-rc.5

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Firefox
 - Version: 110.0

**Comment by danielpetri1** [comment]
Cannot reproduce on `dev26` (2.6.10) since the move to Tika. `.txt` files converted successfully:

![Screenshot 2023-06-26 at 18 17 03](https://github.com/bigbluebutton/bigbluebutton/assets/33319791/91eb6c6e-e54e-4d49-a14b-de62694e1326)

**Comment by ffdixon** [comment]
Thanks Daniel for the good work!
