### ISSUE TITLE
Investigate SMIL playback

### ISSUE THREAD

**Issue by bigbluebutton-issue-import** [bigbluebutton/bigbluebutton#1687]
Originally reported on Google Code with ID 932

```
Investigate the pros/cons of supporting SMIL for record and playback.  

   http://www.w3.org/AudioVideo/


```

Reported by `ffdixon` on 2011-05-05 16:16:02

**Comment by ffdixon** [comment]
Closing as this is an old format and no one has expressed interest in having it for a few years now.
