### ISSUE TITLE
Shared notes behave like RTL in LTR locale

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#16871]
**Describe the bug**
In default locale `en` shared notes are sometimes showing the cursor as I am typing in an RTL language

**To Reproduce**
1. Just open shared notes in a running meeting. Sometimes happens. I have seen it in 4 out of 20 meetings last week

**Expected behavior**
the text should be aligned to the left, cursor at the very right, newly added text should appear where the cursor is

**Actual behavior**
see video

**Screenshots**
[Screencast from 2023-03-01 04:42:20 PM.webm](https://user-images.githubusercontent.com/6312397/222271727-b5d6ed20-a26b-4269-b8ed-da968a0c7ae4.webm)

**BBB version:**
BigBlueButton 2.6.0-rc.5

**Comment by antobinary** [comment]
When this happens, if I put the cursor in the middle of a line and press the left arrow key to fo left, it goes right. The right one goes to the left.

**Comment by KDSBrowne** [comment]
There is an issue related to this in the etherpad repo, adding here for reference  [Issue with RTL URL parameter](https://github.com/ether/etherpad-lite/issues/5559#top)
#5559
