### ISSUE TITLE
wrong infos GitHub Release Mail

### ISSUE THREAD

**Issue by hahaxd35** [bigbluebutton/bigbluebutton#16887]
**Describe the bug**
### Release name
In case an administrator does not want to update to the latest focal-260 version. Use as substitute to the `-v` argument in bbb-install.sh command
`focal-260-2.6.0-rc.5`
We still recommend using `-v focal-260`.

bbb-install-2.6.sh.... this took me a while.... used old 2.5 script (worked, but software didn't work) 

**To Reproduce**
wget -qO- https://ubuntu.bigbluebutton.org/bbb-install-2.5.sh | bash -s -- -v focal-260-2.6.0-beta.5 

**Expected behavior**
bbb-install: This script can only install BigBlueButton 2.X up to 2.5

**Actual behavior**
it installled a different Version? just installed the newest Version and BBB worked again.

**Comment by antobinary** [comment]
Hi @hahaxd35 
bbb-install-2.5.sh is meant to be used with BBB 2.5 (repos `focal-250`, `focal-25*`)
bbb-install-2.6.sh is meant to be used with BBB 2.6 (repos `focal-260`, `focal-26*`)

**Comment by hahaxd35** [comment]
know i know too but if you only keep upgrading you may not notice because there is no info and in Mail the infos is even wrong

**Comment by antobinary** [comment]
Which email -- could you please give the release number that was announced in that mail?

You raise a good point - yes, we should indeed be validating the `-v` parameter to ensure we don't proceed with such mismatched commands.

**Comment by hahaxd35** [comment]
every latest release mail from github. release mails from Version 2.5.X are correct:

> ### Release name
> We recommend using `-v focal-250` to always install the latest release.
>
> You can update to this specific release by passing the release name as `-v focal-250-2.5.11` to `bbb-install-2.5.sh` command.  



last mail was from 24.02.2023 (02/24/2023)
[bigbluebutton/bigbluebutton] Pre-release v2.6.0-rc.5 - BigBlueButton 2.6.0-rc.5

@ the end

**Comment by antobinary** [comment]
Hi @hahaxd35 

Is this wording looking clearer?

![Screenshot from 2023-03-02 09-41-36](https://user-images.githubusercontent.com/6312397/222460399-d587fd92-f5c1-4b89-be88-5548cec66c08.png)

We state earlier in the release notes that BBB 2.6 is in dev stage (not production ready)
Also we mark it as a pre-release.

In this updated wording I tried to emphasize that rc.5 is the newest on the 2.6 release of BBB (not overall)

**Comment by antobinary** [comment]
> know i know too but if you only keep upgrading you may not notice because there is no info and in Mail the infos is even wrong

https://github.com/bigbluebutton/bbb-install/issues/616

**Comment by hahaxd35** [comment]
looks great! have a nice day

**Comment by antobinary** [comment]
Thank you for pointing this out! You too!
