### ISSUE TITLE
[mobile] - Wrong style for set status dropdown button

### ISSUE THREAD

**Issue by antonbsa** [bigbluebutton/bigbluebutton#16944]
_Tested on an iPhone 11 + Safari - iOS 16.3_

**Screenshot**
![image](https://user-images.githubusercontent.com/56703993/223226420-e812c0cf-31e1-4702-9b8b-20fb1afe3453.png)

**Comment by Tainan404** [comment]
I've tested on an Iphone SE (2020) - IOS 16.3.1 and it also happens
