### ISSUE TITLE
[mobile] - Raised hands toast notification stays in front of menus

### ISSUE THREAD

**Issue by antonbsa** [bigbluebutton/bigbluebutton#16947]
**Describe the bug** - _Tested on an iPhone 11 + Safari - iOS 16.3_
When a user raises the hand, the toast notification stays displayed for the other users even opening menus/user list

**To Reproduce**
1. Join in a meeting with 2 users;
2. Raise the hand with some of them;
3. As the other user, press to toggle user list;

**Screenshot**
![image](https://user-images.githubusercontent.com/56703993/223227974-36bdf2b1-449b-4df3-a0d0-328d7d46b11b.png)

**Comment by antobinary** [comment]
We've spoken about redesigning the area displaying all the raised hands. This will not be part of 2.6.
Also, only moderators see this area and the assumption is that moderators are likely not using mobile.
