### ISSUE TITLE
Clicking on a toolbar leads to drawing without pressing any keys

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#16955]
**Describe the bug**
If you accidently click (with the pencil) on the presentation toolbar while trying to draw, the pencil becomes active, draws without any mouse clicks and is a challenge to end drawing (pressing Escape). It also drags the slide around (see video)

**To Reproduce**
1. Select the pencil tool
2. click on the toolbar containing prev/next slide buttons
3. draw around

**Expected behavior**
No drawing unless you click on the canvas

**Actual behavior**
The pencil is somehow activated. In the video below I am not holding any mouse buttons

**Screenshots**
video:
[Screencast from 2023-03-07 04:39:43 PM.webm](https://user-images.githubusercontent.com/6312397/223559654-b6d09069-b7eb-4206-b6f5-a5e404ddd0c6.webm)

**BBB version:**
BigBlueButton 2.6.0-rc.6

**Comment by Scroody** [comment]
I tried to reproduce and I believe that @ramonlsouza did as well. We were both unsuccessful on reproducing it. If you could test again or give us more details, let us know so we can test again.

**Comment by antobinary** [comment]
Can't reproduce anymore on ~2.6.1. Thanks!
