### ISSUE TITLE
Share external video - Autofocus the URL input

### ISSUE THREAD

**Issue by TiagoJacobs** [bigbluebutton/bigbluebutton#16963]
When we click to share an external video, the address input could receive an automatic focus, making it easier to paste the address.

Now if you paste the address without focusing the input, the video URL goes to whiteboard.

Field that should receive the `autofocus`:
<img width="1317" alt="image" src="https://user-images.githubusercontent.com/2075267/223784711-dc79e24d-f473-48d2-b770-c906a5062a9a.png">

**Comment by antobinary** [comment]
Closed via https://github.com/bigbluebutton/bigbluebutton/pull/16980
