### ISSUE TITLE
welcome to nginx

### ISSUE THREAD

**Issue by bigbluebutton-issue-import** [bigbluebutton/bigbluebutton#1696]
Originally reported on Google Code with ID 941

```
I have installed the bbb vm application.

I have run these 3 commands 

1) sudo bbb-conf --check
2) dpkg -l|grep bbb
3) sudo bbb-conf -c

and got no errors at all i have also attached the print screen

I am still only getting "Welcome to nginx!" when accessing through ip


```

Reported by `Global.Impression1` on 2011-05-20 21:23:55

<hr>
- _Attachment: BigBlueButton 0.71a-2011-05-21-02-37-11.png<br>![BigBlueButton 0.71a-2011-05-21-02-37-11.png](https://storage.googleapis.com/google-code-attachments/bigbluebutton/issue-941/comment-0/BigBlueButton 0.71a-2011-05-21-02-37-11.png)_
- _Attachment: BigBlueButton 0.71a-2011-05-21-02-38-01.png<br>![BigBlueButton 0.71a-2011-05-21-02-38-01.png](https://storage.googleapis.com/google-code-attachments/bigbluebutton/issue-941/comment-0/BigBlueButton 0.71a-2011-05-21-02-38-01.png)_

**Comment by bananacy** [comment]
Hello,

Had same issue for me this worked: 
sudo bbb-conf --setip host.com (or ip address)
