### ISSUE TITLE
bbb-soffice: stuck containers accumulate over time

### ISSUE THREAD

**Issue by prlanzarin** [bigbluebutton/bigbluebutton#16981]
**Describe the bug**

While cleaning up a demo server I noticed a few bbb-soffice containers that were up for days, seemingly stuck. According to monitoring, their numbers were building up over time. I'd expect the containers to be short-lived.

BBB v2.6.0-rc.6.

**To Reproduce**

Steps to reproduce the behavior: unclear

**Expected behavior**

Containers should be short lived.

**Actual behavior**

Stuck containers.

**Screenshots**

30 day series:
![image](https://user-images.githubusercontent.com/4529051/224155643-48819449-dbc5-477e-8346-b5e9b4754dca.png)

Stuck containers, server was empty:
![image](https://user-images.githubusercontent.com/4529051/224155848-16f55d8a-1a45-4c21-b80e-d9696541889d.png)

**Additional context**

More info can be gathered internally cc @antobinary

**Comment by tim0n3** [comment]
> **Describe the bug**
> 
> While cleaning up a demo server I noticed a few bbb-soffice containers that were up for days, seemingly stuck. According to monitoring, their numbers were building up over time. I'd expect the containers to be short-lived.
> 

Not sure if this has been fixed as we've had a like-issue more recently. While I'm still mid triage, I wonder if you could stop this from ever happening by either reaping zombie procs or using `SIGKILL` via the `timeout` command (or using both) in:
[bbb-libreoffice/assets/zzz-bbb-docker-libreoffice](https://github.com/bigbluebutton/bigbluebutton/blob/5f5255d33838a4c23701c48e309f5c258bdda379/bbb-libreoffice/assets/zzz-bbb-docker-libreoffice)

If anyone still has this issue I would suggest you try testing either, or both, forcing SIGKILL via `-k` in the `timeout` command first, and then, if it doesn't work remove it and zombie reap with `--init` added to the docker run command.

e.g of both:
```SH
bigbluebutton ALL=(ALL) NOPASSWD: /usr/bin/docker run --init --rm ...... bbb-soffice sh -c timeout -k [0-9][0-9][0-9]s .... --outdir /data /data/file

etherpad ALL=(ALL) NOPASSWD: /usr/bin/docker run --init --rm ...... bbb-soffice sh -c timeout -k [0-9][0-9][0-9]s .... --outdir /data /data/file

etherpad ALL=(ALL) NOPASSWD: /usr/bin/docker run --rm ...... bbb-soffice sh -c timeout -k [0-9][0-9][0-9]s .... --outdir /data /data/file

etherpad ALL=(ALL) NOPASSWD: /usr/bin/docker run --rm ...... bbb-soffice sh -c timeout -k [0-9][0-9][0-9]s .... --outdir /data /data/file
```

Hope this helps and if someone else with more expertise could look to provide more information on whether this is ok to use for prod environments or if it has potential functional consequences that I'm not aware of at the moment.
