### ISSUE TITLE
[2.6 rc6] Somehow, users cannot see others' camera (but can see their camera on their browser). 

### ISSUE THREAD

**Issue by newfluxdev** [bigbluebutton/bigbluebutton#16993]
**Describe the bug**
Somehow, 2 users can't see each other's webcams, but the 3rd person who comes in later (and doesn't turn on the webcam) can see both other's webcams.
It's a bit difficult for me to describe the issue because it happens so randomly for several rooms on our server and I don't even know where to start investigating.
Browser console log and server logs are look quite normally. 2 first users were still able to communicating by voice and slide, etc. were working normally.

**To Reproduce**
I don't have exact reproducibility step. Only a few rooms in the server in the server are randomly affected sometime. When I have joined as one of 2 error users by user id, I hadn't seen any webcam too.

**Screenshots**
Error user's view (as I have joined as them by their user id):
![Screenshot 2023-03-11 195636](https://user-images.githubusercontent.com/103695728/224486745-0069b9a5-7de5-4b7b-81bb-fcf1ced0e2f8.png)

3rd person's view (my view)
![Screenshot 2023-03-11 195458](https://user-images.githubusercontent.com/103695728/224486760-4f369094-26bf-4c60-afd5-eee355c7fcdf.png)

When compared chrome://webrtc-internals of error user (I joined as them) and 3rd person user (me), I have seen different: webrtc log of 3rd person have Codec value.
![image](https://user-images.githubusercontent.com/103695728/224486808-2d83c79a-6795-4ba4-8547-8c6d64de7252.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome Version 110.0.5481.180 (Official Build) (64-bit)
 - Version: 110.0.5481.180 (Official Build) (64-bit)

**Comment by ffdixon** [comment]
The local camera is actually the loopback (the webcam displays the local stream, not the remote stream, for the user).

Not that we would expect this to be different, but can you test with https://test26.bigbluebutton.org/ and let us know if you have the same experience.

**Comment by newfluxdev** [comment]
> The local camera is actually the loopback (the webcam displays the local stream, not the remote stream, for the user).
> 
> Not that we would expect this to be different, but can you test with https://test26.bigbluebutton.org/ and let us know if you have the same experience.

Just several rooms on our server have got into this issue. And it has happened so randomly, I don't have certain steps to reproduce it. When I tested on my server, everything was working well.



> @newfluxdev Upgrade to RC.7. There was an issue in RC.6 that is partially similar to what is being reported and was fixed in RC.7. See #16909.
> 
> If the issue persists, let us know.

Let me try with fresh install on rc7. Thank you!

**Comment by ffdixon** [comment]
> Let me try with fresh install on rc7. Thank you!

Thanks for helping us test the latest builds of BigBlueButton.  We wouldn't know about these issues unless they are reported in the issues.

**Comment by newfluxdev** [comment]
> @newfluxdev Upgrade to RC.7. There was an issue in RC.6 that is partially similar to what is being reported and was fixed in RC.7. See #16909.
> 
> If the issue persists, let us know.

I cannot confirm our issue is fixed on Rc.7 yet. But I would like to confirm our issue is exactly same as issue #16909 . If our users' username have Vietnamese characters, so they have encountered the issue. If we convert their username to ASCII characters only (without Vietnamese characters), they won't!
Really thank you @prlanzarin!
