### ISSUE TITLE
[2.6-rc.7] Webcams/screenshare don't show up in recording.

### ISSUE THREAD

**Issue by prlanzarin** [bigbluebutton/bigbluebutton#17013]
**Describe the bug**

Webcams/screenshare aren't showing up in recordings in 2.6-rc.7.
This is _not_ a processing problem - those streams aren't being captured in the first place.
bbb-webrtc-sfu is having trouble connecting to KMS due to a dependency patch bump which broke a behavior we relied on.

**Additional context**

Workaround until a fix lands:
  - /lib/systemd/system/bbb-webrtc-sfu.service: add `Environment=ALLOW_CONFIG_MUTATIONS=true`
  - `systemctl daemon-reload`
  - `systemctl restart bbb-webrtc-sfu`

**Comment by dirk-hl** [comment]
After the workaround the recording shows all content correctly, but added annotations on the presentation/whiteboard are not included in recordings.

**Comment by antobinary** [comment]
Hi @dirk-hl 

> After the workaround the recording shows all content correctly, but added annotations on the presentation/whiteboard are not included in recordings.

I am in the final stages of testing BBB 2.6.0-rc.8 containing @prlanzarin 's fixed. Just wanted to say that in the recordings I am doing on rc.8 the annotations display fine in both video and presentation format. I did not notice a regression on annotations display in rc.7 but now after reading your comment I explicitly tested this and all seems fine.
![Screenshot from 2023-03-14 11-08-07](https://user-images.githubusercontent.com/6312397/225045798-5be4a945-1283-4a3b-bcca-06d89e6db7d4.png)

**Comment by dirk-hl** [comment]
In our installation, unfortunately, the annotations are missing from the recordings. Can I continue here or should I open a new issue?

**Comment by antobinary** [comment]
> In our installation, unfortunately, the annotations are missing from the recordings. Can I continue here or should I open a new issue?

Please open a new issue and include as much info as possible. Are you able to reproduce this on test26.bigbluebutton.org? Here is a link to a recording there I just did and the annotations display fine https://test26.bigbluebutton.org/playback/presentation/2.3/b59b2265c47bfe66b81015a37264b27b115dda90-1678963743579

**Comment by antobinary** [comment]
Hi @dirk-hl -- someone else reported the same issue and just followed up with how they were able to solve it -- the version of the playback player has to also be upgraded (on your end) to match the latest BBB changes. Could you please double check if your `bbb-playback` version is the latest? 

```
$ dpkg -l | grep bbb-playback
ii  bbb-playback                         1:2.6-13                          amd64        BigBlueButton playback
ii  bbb-playback-presentation            1:2.6-11                          amd64        BigBluebutton playback of presentation
ii  bbb-playback-video                   1:2.6-5                           amd64        BigBluebutton playback of presentation
```
