### ISSUE TITLE
v2.6 - User joining with presentation minimized

### ISSUE THREAD

**Issue by antonbsa** [bigbluebutton/bigbluebutton#17014]
**Describe the bug**
Presentation minimized when a user joins before the end of the presentation upload

**To Reproduce**
1. Create a meeting and join with a user right after;
2. Wait for the end of the upload

**Video**

https://user-images.githubusercontent.com/56703993/224730471-41d5afac-6571-4573-9978-cff9bffe852f.mp4

**Comment by ramonlsouza** [comment]
closed by https://github.com/bigbluebutton/bigbluebutton/pull/17016, let's to try to fix https://github.com/bigbluebutton/bigbluebutton/issues/16511 without setting `setPresentationIsOpen` to avoid this one
