### ISSUE TITLE
Suggestion to Swap Mongodb with a different nosql-db

### ISSUE THREAD

**Issue by dmtrhfr** [bigbluebutton/bigbluebutton#17031]
As of Mongodb v4 it is licensed under the very restrictive SSPL.
So it might make sense to swap the database out, if possible, for something different like CouchDB.

**Comment by ffdixon** [comment]
Thanks.  We know of the license swap and, while we don't think it impacts BigBlueButton, we agree that it would be good to move away from Mongodb in the future.

Closed as duplicate to https://github.com/bigbluebutton/bigbluebutton/issues/15237
