### ISSUE TITLE
Update Customize documentation to include the changes from 2.6

### ISSUE THREAD

**Issue by dmtrhfr** [bigbluebutton/bigbluebutton#17045]
The new Documentation is lacking the new cusomization features of 2.6, currently looks like a copy of 2.5.
Maybe even think about new Subsites, because the site is becoming kind of a monster.
@tibroc can you add the right tags for documentation? 
I would do that, after I am done with the API documentation.

**Comment by antobinary** [comment]
Closed via https://github.com/bigbluebutton/bigbluebutton/pull/17067
