### ISSUE TITLE
Audio controls out of sync due to breakouts Join audio

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#17043]
**Describe the bug**
Two closely related issues with the audio controls both during breakouts

**To Reproduce**
1. Join a room as a moderator
2. Join full audio
3. Create breakouts. Doesn't matter if nobody joins them
4. Click on `Join audio` in the breakout panel - pick one of the breakouts
![Screenshot from 2023-03-14 16-01-28](https://user-images.githubusercontent.com/6312397/225123004-5ca1a282-67f6-4f55-9b35-e23aadb170f3.png)

6. Look at your audio controls - the action bar controls do not match the participants list controls (they are correct)
Issue #1 - the controls show that you're in full audio in the main room even though your audio has switched to the breakout room. You cannot mute yourself via those controls

7. End the breakouts
Issue #2 - the audio controls remain inactive even though they show you as joined in full audio, unmuted; In the participants list you see the audio state correctly - you're not in audio in the main room
![Screenshot from 2023-03-14 15-56-01](https://user-images.githubusercontent.com/6312397/225122658-17165fb7-2a29-489d-870b-8d0f9f46d9f2.png)

**BBB version:**
BigBlueButton 2.6.0-rc.8

**Comment by Ithanil** [comment]
Maybe related? https://github.com/bigbluebutton/bigbluebutton/issues/17036
