### ISSUE TITLE
Transition to new docs

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#17055]
Checklist of remaining tasks. Please comment below if you think we're missing some (or for feedback)
- be happy with the state of 2.6 docs
  - [x] adding https://docs.bigbluebutton.org/2.6/customize.html - @antobinary https://github.com/bigbluebutton/bigbluebutton/pull/17067
  - [x] fixing api tables https://github.com/bigbluebutton/bigbluebutton/issues/16930 @dmtrhfr  (edit: first pass was done, the info is there, but we are looking into generating the tables from yml/json files instead of inline md)
- [x] Copying the `docs/` to the `v2.5.x-release` branch so we have a spot to find docs like "What's new in 2.5" and "How to install 2.5" @antobinary 
- [x] transfer github issues from https://github.com/bigbluebutton/bigbluebutton.github.io to https://github.com/bigbluebutton/bigbluebutton with a `target:documentation` label  (@antobinary)
- [ ] close all pull requests from https://github.com/bigbluebutton/bigbluebutton.github.io (@antobinary)
- [x] archive https://github.com/bigbluebutton/bigbluebutton.github.io so that people know not to tweak it or rely on it @antobinary -- first pass done in https://github.com/bigbluebutton/bigbluebutton.github.io/commit/6304e3920a3f13194525c7cba76121ad8e40b74b
- [x]  link "Teacher & Student" to somewhere with content, e.g. https://support.bigbluebutton.org/ (@tibroc )
- [ ] backport https://github.com/bigbluebutton/bigbluebutton/issues/16930 to `v2.5.x-release` (@antobinary)

**Comment by dmtrhfr** [comment]
So the new docs should include the old docs links? Because i fixed some of the links to the new /bigbluebutton location in the api docs.

**Comment by dmtrhfr** [comment]
Another thing I realised was that the current Font doesn't support bold text. Is there a different font we could consider?

**Comment by antobinary** [comment]
> So the new docs should include the old docs links? Because i fixed some of the links to the new /bigbluebutton location in the api docs.

That's a great way to solve it! And can be done before transitioning fully

**Comment by tibroc** [comment]
We should also link "Teacher & Student" to somewhere with content, e.g. https://support.bigbluebutton.org/
