### ISSUE TITLE
Reduce the max size of the canvas

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#17086]
**Describe the idea**
In order to improve readability of the whiteboard, let's reduce the max size of the [canvas] page to `maxImageWidth = 1440; maxImageHeight=1080`
suggested by @kepstin and discussed with everyone tagged

The change needs to be made in
- [x] bbb-presentation-video by @kepstin
    https://github.com/bigbluebutton/bigbluebutton/pull/17242
- [x] bbb-playback [-presentation?] by @germanocaumo (+tag)
- [x] bbb-html5 by @ramonlsouza or @KDSBrowne
    https://github.com/bigbluebutton/bigbluebutton/pull/17097
- [x] bbb-export-presentation by @danielpetri1
    https://github.com/bigbluebutton/bigbluebutton/pull/17090 

We need to syncronize the merges so that they all target the same BBB minor release

Please link to this issue when opening a PR

**Comment by kepstin** [comment]
A decision has been made to push this to BigBlueButton 2.6.1 - which means that the recording processing code will need to be able to detect and handle both whiteboard sizes.

To facilitate this, https://github.com/bigbluebutton/bigbluebutton/pull/17097 will need to be updated to increase the `bbb_version` number in `/usr/local/bigbluebutton/core/scripts/bigbluebutton.yml` and the recording processing changes to the video and presentation formats will have to read the `bbb_version` from the recording events.xml file and use that to determine which whiteboard size to use.

**Comment by germanocaumo** [comment]
Playback is ready on tag [v5.0.0](https://github.com/bigbluebutton/bbb-playback/releases/tag/v5.0.0)
