### ISSUE TITLE
[2.6] Larger bounding box to a quickly and smoothly drawn ellipse by pen tool

### ISSUE THREAD

**Issue by hiroshisuga** [bigbluebutton/bigbluebutton#17094]
**Describe the bug**
When you draw an ellipse by a pen tool, the bounding box to the shape is sometimes set larger than the actual size. It happens more often when you draw it quickly and smoothly. 

**To Reproduce**
1. Draw an ellipse by the pen tool quickly and smoothly
2. Select it and see the bounding box

**Expected behavior**
The bounding box should be set exactly at the edges of the shape.

**Actual behavior**
Usually it does, but sometimes it does not.

**Screenshots**
![Animation1](https://user-images.githubusercontent.com/45039819/226282053-49194d82-39b8-4fde-b8cd-8171c0e49f2d.gif)

**BBB version:**
Latest, confirmed on test26 server.

**Additional context**
It happens also in the tldraw app. So we cannot do a lot except for submitting an issue to the developers of tldraw. 
![Animation1](https://user-images.githubusercontent.com/45039819/226283164-90d17b36-01ee-4cea-82ff-204da5db8762.gif)
The problem of the wrong bounding box is that you cannot align the shapes correctly, as the app align shapes by the bounding boxes.

**Comment by antobinary** [comment]
@KDSBrowne is this a problem in BBB 3.0?

**Comment by KDSBrowne** [comment]
@antobinary, I don't think so. Haven't been able to reproduce on 3.0.
