### ISSUE TITLE
Update docs to say we include/support coturn on the BBB server 2.6+

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#17103]
Starting with BBB 2.6, when installed with bbb-install-2.6.sh's default options
we install coturn in the same server with BBB for use as TURN

We need to update https://docs.bigbluebutton.org/administration/turn-server/#configure-bigbluebutton-to-use-your-turn-server to say so and to specify if any config changes are needed if you're overriding the defaults

**Comment by code-Gambler** [comment]
The Document link is not working, error 404!
