### ISSUE TITLE
Unify firewall instructions

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#17137]
Currently there are 3 different firewall sections. Pick one or combine the info so only one section remains

https://docs.bigbluebutton.org/2.2/configure-firewall

https://docs.bigbluebutton.org/2.2/customize.html#setup-a-firewall
https://docs.bigbluebutton.org/2.2/customize.html#setup-firewall

**Comment by ffdixon** [comment]
Closing as these directories are out-of-date.
