### ISSUE TITLE
Webcam full screen button fails

### ISSUE THREAD

**Issue by BrentBaccala** [bigbluebutton/bigbluebutton#17160]
**Describe the bug**
Under certain conditions, the full screen button doesn't exit a webcam's full screen mode

**To Reproduce**
1. On a Big Blue Button 2.6 meeting with remote webcams running,
2. full screen the meeting using the BBB option menu (upper right hand corner)
3. then full screen a webcam using its option menu,
4. then try to exit the webcam's full screen by clicking the full screen button

(you can't)

Exit full screen with ESC (or maybe F11)

**BBB version:**
BigBlueButton 2.6.0 (first seen during a dev call on dev26.bigbluebutton.org)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20
 - Browser: Firefox

**Comment by Scroody** [comment]
I tested on the same conditions and seems to be working fine now.

https://user-images.githubusercontent.com/36093456/228277126-79bbfcba-2d5f-4b5b-a1d5-84cbe22a138a.mp4
