### ISSUE TITLE
The editing on board not recorded on bbb 2.6

### ISSUE THREAD

**Issue by mahdidev70** [bigbluebutton/bigbluebutton#17178]
The editing board by pen and other tools does not show in the recorded file.
the board file was recorded but without any line or text that wrote on it

for more detail I got a video:
[more detail](http://b4it.ir/upload/bbb/bug.mp4)

https://user-images.githubusercontent.com/91634743/227097693-7a8997a2-2b60-4225-b555-67bc2313dfa5.mp4

I'm using BBB 2.6 and load balancer scalelite:v1.2.0.1
before using BBB 2.6 I didn't face the problem

**Comment by mahdidev70** [comment]
I think the problem is related to scalelite. but I'm not sure.
because the recorded session on bbb server doesn't have any problem but on scalelite server, it got the problem

**Comment by dirk-hl** [comment]
I have created an issue in scalelight about the problem: https://github.com/blindsidenetworks/scalelite/issues/895

**Comment by mahdidev70** [comment]
Is there any option to change or adjust bbb 2.6 to work according last version?

**Comment by dirk-hl** [comment]
> @dirk-hl so, are you sure the problem comes from scalelite?

Yes, I am. In my issue I compared the same recording with and without Scalelite.

**Comment by hostbbb** [comment]
So you probably have to updated the player code on scalelite so it knows about the tldraw.json file that is produced.   is the url plays on bbb server fine, and not once its moved to scalelite, then its either the player, or the tldraw.json does not exist.

you will probably have to make some modifications to play the new video format as well.

**Comment by dirk-hl** [comment]
The tldraw.json file exists on the Scalelite server, so it is copied correctly. The player must be adapted.

**Comment by mahdidev70** [comment]
@dirk-hl 
did you try last version of scalelite? maybe the player was updated

**Comment by dirk-hl** [comment]
I use the current Scalelite version 1.4. https://github.com/blindsidenetworks/scalelite/releases/tag/v1.4
Look at my Scalelite issue, there I describe my deployment. https://github.com/blindsidenetworks/scalelite/issues/895

**Comment by antobinary** [comment]
Looks like it's a Scalelite issue. Let's continue the conversation in https://github.com/blindsidenetworks/scalelite/issues/895
