### ISSUE TITLE
Clean Mode in BBB 2.6.0

### ISSUE THREAD

**Issue by Schwenn2002** [bigbluebutton/bigbluebutton#17179]
Start with minimal layout no longer possible!

If a clear layout is selected as the start for a room (e.g. in Nextcloud 25 App), the user list, the chat area and the presentation are no longer hidden by default. After the start, the default presentation is always displayed.

The behavior was still as desired in BBB 2.5.14 that the presentation was hidden after starting the room.

**BBB version: 2.6.0 (1022)

**Desktop
 - Windows 11 
 - Edge or Chrome Version 
 - Version 111

**Comment by antobinary** [comment]
Hi @Schwenn2002 

Could you please list what parameters you were passing on create and join on BBB 2.5.14?

I believe this is related to https://docs.bigbluebutton.org/2.6/new-features/#change-of-parameters-naming

**Comment by antobinary** [comment]
Let's reopen if there is more info ^
