### ISSUE TITLE
New features link on release 2.6 page is not working.

### ISSUE THREAD

**Issue by shabeepk** [bigbluebutton/bigbluebutton#17186]
**Link to the portion of the docs that is out of date**
If applicable, link to the section of the docs that is out of date.
https://github.com/bigbluebutton/bigbluebutton/releases/tag/v2.6.0

**Describe what you belive the correct version should be** 
The link https://docs.bigbluebutton.org/bigbluebutton/new-features should work, or the release 2.6 page should not tell the user to go to this link.

**Screenshots**
If applicable, add screenshots to help explain your concern.
![image](https://user-images.githubusercontent.com/2941636/227168573-e2dcd7fb-5f3f-4f9b-8168-79b6fffff4a8.png)

**Additional context**

**Comment by tibroc** [comment]
Right, that slipped after the migration to the new docs, @antobinary .

**Comment by antobinary** [comment]
Thanks for reporting this @shabeepk 

We have corrected the link the release notes https://github.com/bigbluebutton/bigbluebutton/releases/tag/v2.6.0
![Screenshot from 2023-03-23 13-17-58](https://user-images.githubusercontent.com/6312397/227284852-1641fb4b-c97a-40b7-a602-b29a2bbbb7ac.png)
