### ISSUE TITLE
/etc/bigbluebutton/turn-stun-servers.xml overwrite

### ISSUE THREAD

**Issue by hahaxd35** [bigbluebutton/bigbluebutton#17189]
**Describe the bug**
Installed 2.6.0 and wondering why WebCam and screensharing not working

saw "/etc/bigbluebutton/turn-stun-servers.xml" was overwriten.... this is a customization file i thought... just make your changes in original file not in overwrite file!

**Expected behavior**
overwrite files should not be overwriten by maintainer.

**Comment by antobinary** [comment]
Hi @hahaxd35 
thanks for reporting!

I am not immediately spotting what could be overriding that file. Could you please share what the file looked like after it was overriden? Was it all empty, or fully replaced by the version from `/usr/share/bbb-web/WEB-INF/classes/spring/turn-stun-servers.xml` ?

**Comment by hahaxd35** [comment]
the amount of text and "turn:serveradress" looks similar

but example.com was replaced with server address

after update i had execute:
bbb-conf --set-ip 

maybe this replaces text?

**Comment by antobinary** [comment]
> i had execute: bbb-conf --set-ip
> maybe this replaces text?

Yes, `bbb-conf --set****` changes text in the `/etc/bigbluebutton` dir -- it's an optional command helping with administration. You may want to steer away from it if you want all your configs preserved.

**Comment by hahaxd35** [comment]
did again an upgrade.... and this time did not execute --set-ip...

and this configuration again changed again from STUN to TURN server in "/etc/bigbluebutton/turn-stun-servers.xml"

so happy we out sourced BBB...
