### ISSUE TITLE
High frequency of calls of method voidConnection

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#17198]
**Describe the bug**
When checking frequency of calls of all Meteor methods, we see that the calls to `voidConnection` are quite frequent - at times half the total calls. This does not necessarily mean that there's a problem but it warrants a check into what might be the cause

**To Reproduce**

**Expected behavior**

**Actual behavior**

**Screenshots**

**BBB version:**
BigBlueButton 2.5, 2.6

**Comment by Scroody** [comment]
I've look into this issue and I noticed that our code has a timeout set to every 10 seconds (in [this](https://github.com/bigbluebutton/bigbluebutton/blob/5fdd91ba67c6676645adfc73918ae4641ca51c20/bigbluebutton-html5/private/config/settings.yml#L666) line), it calls for the voidConnection. But gladly no bug to be fixed. However if the voidConncetion being logged every 10 seconds isn't what its expected I could set it to a bigger timer perhaps!?

**Comment by gustavotrott** [comment]
I think 10 seconds is a good interval. If it takes more than 10 seconds to detect some connection issue it will be too late..

The call to `voidConnection` seems to be really harmless.
https://github.com/bigbluebutton/bigbluebutton/blob/cacba3c7e773e85fd30b8d4013d3c9119c45077f/bigbluebutton-html5/imports/api/connection-status/server/methods/voidConnection.js#L4

**Comment by antobinary** [comment]
Sounds good! Thank you both for the comments!
