### ISSUE TITLE
How to setting Recording in MP4 format 2.6.0

### ISSUE THREAD

**Issue by mauser8004** [bigbluebutton/bigbluebutton#17306]
Unfortunately, I couldn't find a description anywhere. I updated the server on 2.5.12, but there is no downloadable video format. In the installation description, I found only the one for version 2.5.

**Comment by mabras** [comment]
[Enable generating mp4](https://docs.bigbluebutton.org/2.6/administration/customize/#enable-generating-mp4-h264-video-output)

**Comment by antobinary** [comment]
Thanks @mabras for the link!

@mauser8004 just to clarify -- the MP4 format is called `video` and is available starting with BBB 2.6.0

**Comment by cod3r0k** [comment]
Do we have any further support for `video` format in the scalalite?
