### ISSUE TITLE
2.6 - annotated export requires libmagickcore-6.q16-6-extra (which may not be installed in 20.04)

### ISSUE THREAD

**Issue by MWWorks** [bigbluebutton/bigbluebutton#17303]
Brand new bbb-install.sh on Hetzner server - when adding text annotations to the whiteboard, the annotated export is missing the text annotations (and may also misses graphical annotations on slides that have text).

To isolate this, I reinstalled OS and BBB with the same results; then added a new server on DigitalOcean to compare; this works as expected (albeit with incorrect fonts - resolved by applying the workaround from #16827).

Hetzner seem to have a more minimal Ubuntu install so I'm wondering if there is a dependency that is assumed to be already installed? I cross-referenced the output of apt list --installed between the two - enclosed the list of packages included in DigitalOcean which are NOT in the Hetzner install.

Tried installing fonts-*, gsfonts, libfontenc1, but the issue persists.
[hetzner-vs-ubuntu.txt](https://github.com/bigbluebutton/bigbluebutton/files/11073175/hetzner-vs-ubuntu.txt)

**Comment by MWWorks** [comment]
Think I found this:

Installing libmagickcore-6.q16-6-extra seems to have resolved the issue. Perhaps it needs to be explicitly installed by bbb-install.sh since it may not necessarily already exist?

(Changed name of the issue accordingly)

**Comment by antobinary** [comment]
Hi @MWWorks 
`imagemagick` is a prerequisite for `bbb-web` https://github.com/bigbluebutton/bigbluebutton/blob/v2.6.x-release/build/packages-template/bbb-web/opts-focal.sh#L3
Do you know which version of `imagemagick` you had (either via your minimal Ubuntu or installed at the time of bbb-web installation)?

**Comment by antobinary** [comment]
For the record this is what I see on a working BBB 2.6.0

```
$  dpkg -l | grep libmagickcore
ii  libmagickcore-6.q16-6:amd64          8:6.9.10.23+dfsg-2.1ubuntu11.6    amd64        low-level image manipulation library -- quantum depth Q16
ii  libmagickcore-6.q16-6-extra:amd64    8:6.9.10.23+dfsg-2.1ubuntu11.6    amd64        low-level image manipulation library - extra codecs (Q16)
```

Could you please execute this command on your server? It's not a problem to add `...-extra` as a prerequisite too, just hoping to confirm it first.

**Comment by antobinary** [comment]
Hi @MWWorks ,

Initially I had planned on including this dependency as part of BBB 2.6 but waited a bit to see if anyone else was hitting the issue. Given that nobody else has reported/mentioned/upvoted, I think we should leave it as it currently is. Thank you very much for documenting your investigation and additional details. If this becomes a recurrent issue in the future, we can add the dependency. I am dropping this from the BBB 2.6 milestone.

Thanks again!

**Comment by muellerlukas** [comment]
> Given that nobody else has reported/mentioned/upvoted, I think we should leave it as it currently is.

Also hit that issue. Hetzner still does not install this package in Ubuntu 20 as well as in 22.
So this issue will still be in BBB 3 on a Hetzner-Server.
I think it is a good idea to include this in the dependency-list.
