### ISSUE TITLE
Pan tool turns to select

### ISSUE THREAD

**Issue by vasylOstrovskyi** [bigbluebutton/bigbluebutton#17331]
**Describe the bug**
Sometimes, the pan tool starts working as select tool.

**To Reproduce**
1. Start session. Zoom in to see pan tool effect
2. Select pan tool. Use it to move the slide.
3. Click right button to select context menu. Click on slide to close it (see also Additional context below)
4. Pan tool is still shown as active on the toolbat, but it works as select tool.
5. Click select tool on the toolbar, then click on pan tool, it works correct again.

**BBB version:**
bbb 2.6.0

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04, Windows 11
 - Browser Chrome, Firefox

**Additional context**
With graphic tablet, pan tool often turns to select randomly without pressing the right button, which is a bit annoying.

Regards,
 Vasyl

**Comment by antobinary** [comment]
Thanks for reporting!
