### ISSUE TITLE
The addition to the Raise Hands icon is warped

### ISSUE THREAD

**Issue by Davka** [bigbluebutton/bigbluebutton#17354]
**Describe the bug**
The addition to the Raise Hands icon is warped (see screenshot)

**To Reproduce**
Start a meeting on a mobile phone (iphone for example)

**Screenshots**
<img src="https://user-images.githubusercontent.com/1117697/228477373-9c50aa00-3203-4277-bae9-7aa77020caa0.png" width="50%">
<img src="https://user-images.githubusercontent.com/1117697/228479780-402e6015-8691-4de9-9363-6e67f05b2f5b.jpeg" width="50%">

**BBB version:**
BigBlueButton Server 2.6.0 (1022)

**Smartphone (please complete the following information):**
 - iOS 16.1.2

**Comment by ramonlsouza** [comment]
fixed by #17686
