### ISSUE TITLE
BBB 2.6 Панель інструментів дошки

### ISSUE THREAD

**Issue by Nick64M** [bigbluebutton/bigbluebutton#17356]
The toolbar closes part of the content of the presentation. I need to move further.

![panel](https://user-images.githubusercontent.com/95514883/228529723-d2539a6a-d66d-424d-9a39-dbb6db0cf0fb.jpg)

**Comment by antobinary** [comment]
Duplicate of https://github.com/bigbluebutton/bigbluebutton/issues/15739
