### ISSUE TITLE
[2.6.x] [client] Html5 Client error cause reload or crash on iPhone

### ISSUE THREAD

**Issue by trinhhuutam** [bigbluebutton/bigbluebutton#17375]
Hello, from version 2.6.0, Html5 client causes a serious issue on iPhone. We can reproduce by 2 users: user A (use Windows Laptop) and user B (use iPhone). When user A has opened Webcam and drawn something with pen on Whiteboard. A little later, user B will be forced to reload html5 client web. 
Even after user B has been reloaded successfully, when they see webcam user A again, they are kept getting force reloaded or may crash with error: "A problem repeatedly occurred on xxxx".
I can reproduce it with https://demo3.bigbluebutton.org/ or our self deployed server.

This somehow happen on iPhone only, we cannot reproduce on iPad.

**Comment by trinhhuutam** [comment]
Does anyone here have any ideal about this issue? I have searched on Google and they report may it happened because woff front on Safari? Can anyone confirm????

**Comment by ffdixon** [comment]
HI @trinhhuutam.  Thanks for the reporting this, and thanks for testing this against demo3.bigbluebutton.org.

> When user A has opened Webcam and drawn something with pen on Whiteboard. A little later, user B will be forced to reload html5 client web.

How long do you have to wait?

Can you try it against https://test26.bigbluebutton.org/, which has 2.6.1, and let us know if you can reproduce there.  We're testing your scenario against our own 2.6.1 server to see if we can reproduce.

What version if iOS are you running?

**Comment by trinhhuutam** [comment]
I have encountered this issue on various model and version iPhone. Maybe all iPhone have same problem because so many our users also reports it happened on their iPhone tool.

Evidence:
From my PC (as I'm user A)
![image](https://user-images.githubusercontent.com/7065963/229765790-53809147-023c-4b82-a459-6cacfb9cbe49.png)

From iPhone 1 (iPhone 6) I tested:

https://user-images.githubusercontent.com/7065963/229766407-37327b69-efac-4a94-8d14-05e360cb4206.MP4


From iPhone 13 Promax I tested:

https://user-images.githubusercontent.com/7065963/229766511-eb3e622f-2ed8-4476-8089-e0daf77ec91f.MP4

**Comment by trinhhuutam** [comment]
@ffdixon Hello, have you reproduce it yet? We have a larger number of user using iPhone and they aren't able to using BBB now as we have upgrade all servers to 2.6.0

**Comment by antobinary** [comment]
Might be related -- again whiteboard+webcam correlation on mobile https://github.com/bigbluebutton/bigbluebutton/issues/17332#issuecomment-1488170020

**Comment by trinhhuutam** [comment]
Hello @ffdixon @ramonlsouza Pardon me, but do you have any progress in this issue??? Will we have a fix soon?

**Comment by trinhhuutam** [comment]
Hello @ffdixon @ramonlsouza @antobinary . Do you have any information on the progress of fixing this issue? 
Please let me know if we can't have the fix soon. Otherwise, I must comeback with BBB 2.3.x for my iPhone users.

**Comment by ffdixon** [comment]
No worries -- thanks for the ping.  We're still looking into this issue and don't have a timeline yet for resolving it.

**Comment by hostbbb** [comment]
@trinhhuutam When did this break.   was is working fine on any of the previous 2.6. RC or Beta Releases.   If it was working in earlier in 2.6  you good help by installing an earlier reelases to see when it breaks to help the core developers identify an issue.
using bbb-install you can install any release with repo tag  like focal-260-2.6.0-beta.6

Also 2.5 is still a supported version. Have you tried this to see if it solves your issue?

**Comment by ffdixon** [comment]
Hi @trinhhuutam, we're aware of the issue and can reproduce it here.  The crash seems to occur after a number of whiteboard images are on the presentation area, and mobile users are sharing or viewing a webcam, so it's reproducible.  

We'll update this ticket as we make progress in investigation.

**Comment by ffdixon** [comment]
@trinhhuutam Can you test the just released [BigBlueButton 2.6.5](https://github.com/bigbluebutton/bigbluebutton/releases/tag/v2.6.5) and let us know if you can still make it crash on iOS devices.

**Comment by trinhhuutam** [comment]
> @trinhhuutam Can you test the just released [BigBlueButton 2.6.5](https://github.com/bigbluebutton/bigbluebutton/releases/tag/v2.6.5) and let us know if you can still make it crash on iOS devices.

Really thank you @ffdixon , @KDSBrowne , @ramonlsouza @antobinary .
I just test with my server and look like the issue has been fixed. I'm releasing this fixed version to our users see if it'll work well.

**Comment by trinhhuutam** [comment]
@KDSBrowne Your fix has an issue:

On smart layout, webcam region will prevent to click (+) button below it.
![image](https://user-images.githubusercontent.com/7065963/234212267-9ceeaaab-62f0-431b-bcb2-cf6b54eb4603.png)

Should we use px instead of pt? With px, it won't prevent to click that button
![image](https://user-images.githubusercontent.com/7065963/234213462-3d5a81fc-78e4-4870-8b57-d1987781afbc.png)
