### ISSUE TITLE
Capture a photo or frame of the participant

### ISSUE THREAD

**Issue by leandroveronezi** [bigbluebutton/bigbluebutton#17372]
I need to capture a photo of the participant or a frame from their webcam, as a form of auditing to ensure that they are watching the event and are able to receive the event certificate. Through the API I did not find any way to perform the audit. Does anyone have an idea how to implement this functionality?

**Comment by hostbbb** [comment]
if record=true, and they turn their camera on you can get realtime video frames server side, and send the data to a facial rec eng to see if no- one is there,  if there eyes are open, if they leave, if others show up,   even guesses age, sex, and if they are happy and sad.  we used aws sdk and sent analytics and the frames every 5 secs to monitoring station

not an api,  but possible if you have access to bbb server backend and know a little redis and ruby
