### ISSUE TITLE
Issue on recently 2.5.15 release, kurento media service stop working, webcams in blank

### ISSUE THREAD

**Issue by ravenmanco** [bigbluebutton/bigbluebutton#17390]
**Describe the bug**
After install the version 2.5.15 on ubuntu 20.0.4 , the meetings that have webcams in the recording are not being captured, the webcams appears in blank. When debbug at logs the following error is throwed in the syslog of ubuntu:

Apr  1 01:03:49 vm-bbbs-12 bbb-webrtc-sfu[25595]: {"ip":"20.121.8.123","label":"core","level":"error","message":"KMSBalancer: Failed to connect to media server","retries":102,"timestamp":"2023-04-01T01:03:49.643Z","url":"ws://127.0.0.1:8888/kurento"}

**To Reproduce**
Install the recently version of bbb using the following command:
wget -qO- https://ubuntu.bigbluebutton.org/bbb-install-2.5.sh | bash -s -- -v focal-250 -s $hostname -e dummy@dumy.com  -a -w

**Actual behavior**
The Webcams are displayed in the meeting but not being recorded, and when the recording is published the webcam is in blank, only audio is reproduced.

Kurento media server throws errors in syslogs:
Apr  1 01:03:49 vm-bbbs-12 bbb-webrtc-sfu[25595]: {"ip":"20.121.8.123","label":"core","level":"error","message":"KMSBalancer: Failed to connect to media server","retries":102,"timestamp":"2023-04-01T01:03:49.643Z","url":"ws://127.0.0.1:8888/kurento"}

**Comment by antobinary** [comment]
Hi @ravenmanco 

Thanks for reporting this! We're looking into it now.

**Comment by antobinary** [comment]
Hi @ravenmanco 

I was able to reproduce this on a 2.5.15 server and the issue appears to be https://github.com/bigbluebutton/bigbluebutton/issues/17013 again. The solution suggested in the description worked locally. I am now looking into why this is not happening automatically. I'll update this issue shortly

**Comment by antobinary** [comment]
We are almost done with the release of BBB 2.5.16 containing the correctly built bbb-webrtc-sfu package, containing the aforementioned fix.
You can already upgrade via the same bbb-install command you used, again on `-v focal-250`

**Comment by antobinary** [comment]
Thanks again @ravenmanco 
https://groups.google.com/g/bigbluebutton-dev/c/fi7GOkScBW4/m/TLEYP3tlAwAJ

**Comment by ravenmanco** [comment]
Was a Pleasure @antobinary , one quick question searching for your advice, we are planning to deploy a cluster of BBBs machines, with an scalelite in front with a recent release, we already have one in version 2.2.0 of BBB, my question is, what is the most stable and recomended version to use in this moment of the version 2.5?. We have an institution that use very hard this wondeful solution, but the loads are high so we want to be sure that the release that will be implemented is the most stable.

Thank you in advice.

**Comment by antobinary** [comment]
In terms of BBB -- 2.5.14 had been out for a month with good feedback. 2.5.15-16 were just backports from BBB 2.6 so other than the glitch with the kurento connection but that's been fixed now...

Now, in terms of Scalelite, I don't have enough personal experience to give a personal recommendation. Lots of people are using Scalelite on https://groups.google.com/g/bigbluebutton-dev , feel free to check for opinions there. Whatever setup you decide to go with, I'd recommend keep up with the new updates - BBB 2.2.0 has been out of support for quite some time, we recently phased out 2.4.x and BBB 2.5 will only be supported until 2.7.0 is out (later in 2023).
