### ISSUE TITLE
Disable Slide snapshot

### ISSUE THREAD

**Issue by SamuelWei** [bigbluebutton/bigbluebutton#17410]
**Is your feature request related to a problem? Please describe.**
For some meeting we explicitly write a note on slides, that screenshots, recordings, etc. are prohibited.
With the latest version of BBB the system gives them an "offical" solution to capture the slides, using the snapshot feature.

**Describe the solution you'd like**
Add option to the config file to disable the snapshot feature.

**Describe alternatives you've considered**
- Add option to API
- Add option to restrictions (+api) like the feature: viewsers cannot see others webcam

**Comment by antobinary** [comment]
@danimo is asking if this could be a CREATE parameter

**Comment by SamuelWei** [comment]
@antobinary @danimo Added to disabledFeatures, so it can be set via the create methode

**Comment by SamuelWei** [comment]
Current workaround using a custom css file

```css
#presentation-dropdown-menu .MuiMenu-list li:nth-child(2) {
    display: none;
}

```

**Comment by antobinary** [comment]
Hi @SamuelWei 
Thank you for your pull request!

Based on the file changes, your pull request adds a configuration option in `settings.yml` so if you disable the snapshot taking, it is disabled _for all meetings on the server_.

However, when you documented it (in the same PR) you did it as if it was a supported parameter to be passed in the CREATE command for `disabledFeatures=x,y,z` which would be desired but currently is not the case.
