### ISSUE TITLE
Broken links in settings.yml of html5-client

### ISSUE THREAD

**Issue by dmtrhfr** [bigbluebutton/bigbluebutton#17435]
**Link to the portion of the docs that is out of date**
Links to documentation in [settings.yml](https://github.com/bigbluebutton/bigbluebutton/blob/develop/bigbluebutton-html5/private/config/settings.yml) are broken, maybe some other configs still point to the old docs.

**Describe what you belive the correct version should be**
Fix links in config files

**Comment by antobinary** [comment]
Thanks for reporting!

**Comment by code-Gambler** [comment]
@antobinary @dmtrhfr  Can you Please assign this issue to me, I can fix it.

**Comment by antobinary** [comment]
Sure! Thank you!

**Comment by antobinary** [comment]
Closed via https://github.com/bigbluebutton/bigbluebutton/pull/17521 and https://github.com/bigbluebutton/bigbluebutton/pull/17433
