### ISSUE TITLE
Start and stop meeting recording through API

### ISSUE THREAD

**Issue by halilb** [bigbluebutton/bigbluebutton#17449]
**Is your feature request related to a problem? Please describe.**

We have two requirements for our BBB meetings:

1. Let instructors join the meeting before its scheduled date so they can configure the room.
2. Start recording the meeting automatically when it starts.

Those two requirements do not work well together when the instructor joins the meeting N minutes before students.

**Describe the solution you'd like**

We fixed this problem by using "in-meeting controls" on our Zoom integration: https://developers.zoom.us/docs/api/rest/reference/zoom-api/methods/#operation/inMeetingControl It lets you start and stop recording live meetings. So we are starting the recording when the first student joins.

A similar API endpoint would be great.

**Comment by hostbbb** [comment]
Its possible with custom redis service to start/stop a recording for a meeting, if you send message as the moderator.  We have done this to allow this feature in LMS portal with hackish api.   I think your request is good one for core feature,  schools that autostart recordings and dont allow teachers to start/stop have wasted setup time recorded prior to student joining, with often unattended audio appearing.

**Comment by halilb** [comment]
> Its possible with custom redis service to start/stop a recording for a meeting, if you send message as the moderator. We have done this to allow this feature in LMS portal with hackish api. I think your request is good one for core feature, schools that autostart recordings and dont allow teachers to start/stop have wasted setup time recorded prior to student joining, with often unattended audio appearing.

Thanks for your input @hostbbb! I agree that this could be a valuable core feature.

About the redis hack: Do you remember what kind of message we need to send to start the recording? I checked the documentation but couldn't see anything about running a custom Redis service.

**Comment by hostbbb** [comment]
So the internal messages can be seen in source code.   But basically these messages sent in REDIS to the bbb-akka can turn on and of the recording  just tested with 2.6.1

127.0.0.1:6379> "publish" "to-akka-apps-redis-channel" "{\"envelope\":{\"name\":\"SetRecordingStatusCmdMsg\",\"routing\":{\"meetingId\":\"70093e782e9c57e06f5f9457e2e1084c10dd63a0-1680776793718\",\"userId\":\"w_hehubdqg9vze\"},\"timestamp\":1680776906259},\"core\":{\"header\":{\"name\":\"SetRecordingStatusCmdMsg\",\"meetingId\":\"70093e782e9c57e06f5f9457e2e1084c10dd63a0-1680776793718\",\"userId\":\"w_hehubdqg9vze\"},\"body\":{\"recording\":true,\"setBy\":\"w_hehubdqg9vze\"}}}"
(integer) 1

127.0.0.1:6379> "publish" "to-akka-apps-redis-channel" "{\"envelope\":{\"name\":\"SetRecordingStatusCmdMsg\",\"routing\":{\"meetingId\":\"70093e782e9c57e06f5f9457e2e1084c10dd63a0-1680776793718\",\"userId\":\"w_hehubdqg9vze\"},\"timestamp\":1680776906259},\"core\":{\"header\":{\"name\":\"SetRecordingStatusCmdMsg\",\"meetingId\":\"70093e782e9c57e06f5f9457e2e1084c10dd63a0-1680776793718\",\"userId\":\"w_hehubdqg9vze\"},\"body\":{\"recording\":false,\"setBy\":\"w_hehubdqg9vze\"}}}"

So if some ruby code watched for new meetings,  you could push the start recording when the "second" user joins the meeting with not to much effort.   The ruby code would be installed as a service on the server.     

Devils in the details on how you only do it for meetings that you want, and not every meeting that ever starts, like passing a meta_start-record-on-second-user param on create etc... 

Better to get the core feature implemented, but this is an interim.

**Comment by halilb** [comment]
Thanks a lot @hostbbb! I'll wait to hear from project members about this.
