### ISSUE TITLE
[2.6] The presentation area is always displayed when screensharing is finished.

### ISSUE THREAD

**Issue by einhirn** [bigbluebutton/bigbluebutton#17464]
**Describe the bug** 
Even if the presentation was previously minimized, it will always be restored after a screen share or a external video is finished. In BBB 2.5, the previous state of the presentation area was respected.

**To Reproduce** 

1.	Minimize the presentation
2.	Start a screen share or a external video and stop it.
3.	The presentation is displayed.

**Expected behavior**
The presentation should be minimized after a screenshare or external video if it was minimized before.

**Actual behavior** 
The presentation is always recovered. 

**BBB version:**
BigBlueButton Version: 2.6.0
Clientversion: 489

**Desktop:**
OS: Windows 10
Browser: Chrome, Version 111.0.5563.147

**Comment by antobinary** [comment]
I had to revert #17512 ; See https://github.com/bigbluebutton/bigbluebutton/issues/17668
