### ISSUE TITLE
[2.6] Smartpoll does not work in German language.

### ISSUE THREAD

**Issue by einhirn** [bigbluebutton/bigbluebutton#17466]
**Describe the bug**
The Smartpoll feature automatically offers a poll when a yes/no or true/false question is detected in the presentation. In German only "Freie Antwort" (Typed Respose) is offered instead.

**To Reproduce**

  1. Set language to German
  2. Upload a presentation that includes questions with keywords "(ja/nein)?" and "(richtig/falsch)?" (see below for example)
  3. Switch to the slides that have the questions.
  4. As smartpoll option only "Freie Antwort" (Typed Respose) is provided.

**Expected behavior**
Smartpool should provide yes/no and true/false polls also in German language.

**Actual behavior**
Only Typed Respose is provided.

**BBB version:**
BigBlueButton Version: 2.6.0
Clientversion: 489

**Desktop:**
OS: Windows 10
Browser: Chrome, Version 111.0.5563.147

**Additional context**
It seems that the keywords are matches case sensitive. For the language German it would be better if the match was not case sensitive, because different spellings are possible.

In BBB 2.5.14 Smartpoll works in German language for true/false (richtig/falsch) questions, but also not for yes/no (ja/nein) questions.

Here's a presentation to demonstrate the issue.
[Smart.Slides.Test.en-de.pptx.zip](https://github.com/bigbluebutton/bigbluebutton/files/11160224/Smart.Slides.Test.en-de.pptx.zip)

**Comment by g550** [comment]
Just tried your slides on 2.6.0 and can't reproduce. All slides with quick poll questions in the current client language show the options typed response as well as yes-no/true-false.

The button in the slide's corner always says "typed response" though and the other option is only visible once you click on that – is that your problem, maybe? (Maybe it would be a good idea to switch those options around and always show the more specific type of poll on the button)

**Comment by schrd** [comment]
I can reproduce the bug on demo3.bigbluebutton.org running version 2.6.1. It is dependant on the locale of the client:

* if the client language is English:
  * there will be a true/false quickpoll on slide 2 :heavy_check_mark:
  * there is a typed response on slide 3 :heavy_check_mark:
* if the client language is German:
  * there is no quickpoll option on slide 2 :x: → I'd expect a typed response quickpoll
  * there are 2 quickpoll options on slide 3: `typed response` and `RICHTIG/FALSCH` quickpoll :x:  → I'd expect only `RICHTIG/FALSCH`
