### ISSUE TITLE
Can't find bbb-html5.yml @ /etc/bigbluebutton/bbb-html5.yml

### ISSUE THREAD

**Issue by flowersofpepper** [bigbluebutton/bigbluebutton#17505]
I'm trying to add a custom image to the virtual background folder but cannot refer to it to bbb-html5.yml as I cannot find the file at /etc/bigbluebutton/bbb-html5.yml as mentioned in the documentation.

Documentation link: https://docs.bigbluebutton.org/administration/customize/

**Comment by Zer0CooL4ek** [comment]
because it is created only when there is a need to override the settings
just create it yourself
