### ISSUE TITLE
2.6.1   playback for /2.0/ recordings nginx appears to loop, returns invalid :82

### ISSUE THREAD

**Issue by hostbbb** [bigbluebutton/bigbluebutton#17514]
The /2.0/ nginx redirect for player no longer works in 2.6.1

**To Reproduce**
1. copy /2.0/ recordings run bbb-conf -setip to rewrite server name.
2 From LMS  Greenlight/Moodle try to play the recording.

 

   location /playback/presentation/2.0/playback.html {
                return 301 /playback/presentation/2.3/$arg_meetingId?$query_string;
        }

https://eu27.xxxxxxxxxx.cloud/playback/presentation/2.0/playback.html?meetingId=fe0dfbec3be10209a5999d17581dae65becac029-1675493533330

browser spins for 15 secs.  and returns SITE cant be reached with the following in browser bar.

http://eu27.xxxxxxxxxxx.cloud:82/playback/presentation/2.3/fe0dfbec3be10209a5999d17581dae65becac029-1675493533330?meetingId=fe0dfbec3be10209a5999d17581dae65becac029-1675493533330

If i remove the :82 and refresh it plays in browser..

So looks like the haproxy config with this nginx return 301 is not working as expected.

The 2.0 player is on 2.6 servers, i tried a few attempts to just get that 2.0 player to serve the recording, but always ported the :82

**Expected behavior**

**Comment by hostbbb** [comment]
This fixes the issue shortterm,  the 301 was resulting in an http: with port 82.
Not sure its the best, because requires the hard coded server name, will check if there is nginx variable for server (must be)
We basically need to route 301s thru haproxy to get the needed https and correct port.

/usr/share/bigbluebutton/nginx/presentation.nginx

 location /playback/presentation/2.0/playback.html {
               # return 301 /playback/presentation/2.3/$arg_meetingId?$query_string;
               return 301 https://eu27.xxxxxxxxxxxx.cloud/playback/presentation/2.3/$arg_meetingId?$query_string;
        }

This is telling me any 301 in nginx config  should be checked for the same issue.

**Comment by hostbbb** [comment]
This works fine...  should be final solution

location /playback/presentation/2.0/playback.html {     
               return 301 https://$server_name/playback/presentation/2.3/$arg_meetingId?$query_string;
        }

**Comment by hostbbb** [comment]
Did you get it working with above fix?

**Comment by Buda9** [comment]
yes, it works fine now

**Comment by kepstin** [comment]
The nginx configuration for the recording format is set up correctly and generates the right redirects. I have verified the behaviour on the dev26.bigbluebutton.org server.

The problem that you are hitting is related to the haproxy / TURN server configuration set up by bbb-install. I have opened an issue to track that: https://github.com/bigbluebutton/bbb-install/issues/631
