### ISSUE TITLE
Increase limit of annotations for whiteboard.

### ISSUE THREAD

**Issue by vasylOstrovskyi** [bigbluebutton/bigbluebutton#17525]
**Describe the bug**
There is a limit of annotations per page (currently 300) which makes it impossible to write on the whiteboard when this limit is reached. I've got an error at approximately 80% of moderatedly filled slide.

**To Reproduce**
1. Select pencil tool
2. Start writing on the whiteboard
3. Keep on writing...
4. See error message

**BBB version:**
2.6.1 on my server and demo.bigbluebutton.org

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Browser Chrome

Regards,
 Vasyl

**Comment by hostbbb** [comment]
maxNumberOfAnnotations: 300  

you can adjust in the settings.yml for html5 client if you need higher
