### ISSUE TITLE
Restore option for downloading original presentation as PDF (no whiteboard marks)

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#17531]
**Is your feature request related to a problem? Please describe.**
When we released BigBlueButton 2.6 we added the ability for presenters to download a presentation with whiteboard annotation.  This appeared in the UI as Send to Chat.

<img width="609" alt="image" src="https://user-images.githubusercontent.com/290351/231449812-7ac6072a-02a6-4603-a17a-1bb44ec1fedc.png">

However, the original option to give students the ability to download presentation is no longer present in 2.6.

**Describe the solution you'd like**
Replace Send to Chat with a drop-down menu (three vertical dots) that gives two options

  - Send link to download presentation as PDF to public chat 
  - Send link to download presentation with whiteboard annotations as PDF to public chat

**Describe alternatives you've considered**
Adding more buttons would make the UI more complicated.  A drop-down can give a more fuller explanation of the possible actions.

**Comment by hostbbb** [comment]
The ability on the create call to preupload and to make them downloadable with "no instructor involvement"  like in 2.5 should be preserved.    Provides a download button to viewers on those presentations

<modules>
   <module name="presentation">
        <document downloadable="false" url="https://xxxxx.cloud/default.pdf" filename="myslide.pdf"/>
        <document current="true" downloadable="true" url="https://xxxxx.cloud/docs/22-MDIFW-11-Hunting-Lawbook-2022-23.pdf"/>
        <document downloadable="true" url="https://lxxxxx.cloud/docs/gros_morne.pdf"/>
   </module>
</modules>
