### ISSUE TITLE
need fix misspell 

### ISSUE THREAD

**Issue by MrVer0n** [bigbluebutton/bigbluebutton#17541]
**Describe the bug**
A typo in the Russian localization. 
Project file: bigbluebutton-html5/public/locales/ru.json
Line 569 "app.actionsBar.actionsDropdown.desktopShareLabel": "Демонстировать ваш экран",
Must be: "app.actionsBar.actionsDropdown.desktopShareLabel": "Демонстрировать ваш экран",
Link to the line:
https://github.com/bigbluebutton/bigbluebutton/blob/745bd7e42d82fc7abef7d90cfb08e25b146dca3f/bigbluebutton-html5/public/locales/ru.json#L569

**To Reproduce**
1. Hover over the "Share your screen" icon in Russian localization
2. See error

**Expected behavior**
The inscription of the hint: Демонстрировать ваш экран

**Actual behavior**
The inscription of the hint: Демонстировать ваш экран

**Screenshots**
![image](https://user-images.githubusercontent.com/86586405/231532726-242925c5-9b01-4bd8-b7c5-63c9ebb97c4b.png)

**BBB version:**
Customer Build: 1813
Also present on the current

**Comment by antobinary** [comment]
Thank you!
https://github.com/bigbluebutton/bigbluebutton/pull/17544/files
2.6.2 will carry these translations. It's expected to be out within a few days.
