### ISSUE TITLE
Building bbb-html5 client

### ISSUE THREAD

**Issue by mahdilotfi167** [bigbluebutton/bigbluebutton#17576]
I've installed bigbluebutton using `bbb-install.sh` and everything is OK. `bbb-conf --check` doesn't generate any warning or error.
From [development guide for bbb-html5 client](https://docs.bigbluebutton.org/development/guide/#developing-the-html5-client) I made some changes onto source code and tried to build the client for production environment using the following steps:
- Preparing environment
  - `curl https://install.meteor.com/ | sh`
  - `meteor npm install`
- Building client
  - `meteor build --server-only /home/bigbluebutton/dev/bigbluebutton/bigbluebutton-html5/meteorbundle`
  - `sudo tar -xzvf /home/bigbluebutton/dev/bigbluebutton/bigbluebutton-html5/meteorbundle/*.tar.gz -C /usr/share/meteor`
- Restarting the bbb-html5
  - `sudo systemctl start bbb-html5`  
 
But when I run the `bbb-conf --check`, I'll end up with the following warnings:
```
# Potential problems described below

# Warning: You have this server defined for https, but in
#
#   /usr/share/bigbluebutton/nginx/sip.nginx
#
#  did not find the use of https in definition for proxy_pass
#
#            proxy_pass http://94.184.176.184:5066;
#
# Warning: The setting of 94.184.176.184 for proxy_pass in
#
#    /usr/share/bigbluebutton/nginx/sip.nginx
#
# does not match the local IP address (172.27.1.184).
# (This is OK if you've manually changed the values)


# Warning: You have this server defined for https, but in
#
#   /usr/share/bigbluebutton/nginx/sip.nginx
#
#  did not find the use of port 7443 in definition for proxy_pass
#
#            proxy_pass http://94.184.176.184:5066;
#
```
And I get "Call timeout (Error 1006)" during the microphone echo test for entering any room.

I also tried to use [deploy_to_usr_share.sh](https://github.com/kntu-utils/bigbluebutton/blob/develop/bigbluebutton-html5/deploy_to_usr_share.sh) script, but the problem didn't resolve.

**Building environment:** Ubuntu 20.04.6 LTS
**Building node versions:** Tested on both node v19.4.0 and node v16.19.1
**BBB version:** 2.6

**Comment by hiroshisuga** [comment]
Could this hint a solution? https://docs.bigbluebutton.org/development/guide#audio-configuration-for-development-environment

**Comment by mahdilotfi167** [comment]
> Could this hint a solution? https://docs.bigbluebutton.org/development/guide#audio-configuration-for-development-environment

That seems to be the problem, but it looks like the provided solution is suitable for development environment.

**Comment by schrd** [comment]
If you want to run a modified client in production, you could build your own packages. See https://github.com/bigbluebutton/bigbluebutton/tree/v2.6.x-release/build
