### ISSUE TITLE
Letsencrypt renewal not working with 2.6 (Path to .well-known missing in nginx config)

### ISSUE THREAD

**Issue by jacotec** [bigbluebutton/bigbluebutton#17645]
**Describe the bug**
I received an email for both of my two BBB instances that the Letsencrypt cert will run out in a few days. Renew is not working due to a 404 error calling the ./well-known path in both installations

Installation was done with the official install script.

**To Reproduce**
In the Letsencrypt log, the certificate is generated and saved in /var/www/bigbluebutton-default/.well-known:

```
2023-04-17 08:18:14,833:DEBUG:certbot.plugins.webroot:Creating root challenges validation dir at /var/www/bigbluebutton-default/.well-known/acme-challenge
2023-04-17 08:18:14,839:DEBUG:certbot.plugins.webroot:Attempting to save validation to /var/www/bigbluebutton-default/.well-known/acme-challenge/YCGZSvgFD9_Umo0Seqb0e57yFCEoFHkB5SgsWM9D_RE
2023-04-17 08:18:14,839:INFO:certbot.auth_handler:Waiting for verification... 
```

... but further on the verification failed every time:

```
{
  "identifier": {
    "type": "dns",
    "value": "meet.fep.de"
  },
  "status": "invalid",
  "expires": "2023-04-24T06:18:14Z",
  "challenges": [
    {
      "type": "http-01",
      "status": "invalid",
      "error": {
        "type": "urn:ietf:params:acme:error:unauthorized",
        "detail": "xx.xx.xx.xx: Invalid response from https://mydomain.de/.well-known/acme-challenge/YCGZSvgFD9_Umo0Seqb0e57yFCEoFHkB5SgsWM9D_RE: \"\u003c!--BigBlueButton open source conferencing system - http://www.bigbluebutton.org/.--\u003e\\n\\n\u003c!--Copyright (c) 2022 BigBlueButton Inc.\"",
        "status": 403
      },
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/220121641847/y2syzA",
      "token": "YCGZSvgFD9_Umo0Seqb0e57yFCEoFHkB5SgsWM9D_RE",
      "validationRecord": [
        {
          "url": "http://mydomain.de/.well-known/acme-challenge/YCGZSvgFD9_Umo0Seqb0e57yFCEoFHkB5SgsWM9D_RE",
          "hostname": "mydomain.de",
          "port": "80",
          "addressesResolved": [
            "xx.xx.xx.xx"
          ],
          "addressUsed": "xx.xx.xx.xx"
        },
        {
          "url": "https://mydomain.de/.well-known/acme-challenge/YCGZSvgFD9_Umo0Seqb0e57yFCEoFHkB5SgsWM9D_RE",
          "hostname": "mydomain.de",
          "port": "443",
          "addressesResolved": [
            "xx.xx.xx.xx"
          ],
          "addressUsed": "xx.xx.xx.xx"
        }
      ],
      "validated": "2023-04-17T06:18:15Z"
    }
  ]
}
2023-04-17 08:18:19,478:DEBUG:acme.client:Storing nonce: 5CA2XL3vJ0i7hAiZc_ykR1svs19AUsIVAxJlIMfnXnp1Jbc
2023-04-17 08:18:19,479:WARNING:certbot.auth_handler:Challenge failed for domain mydomain.de
2023-04-17 08:18:19,479:INFO:certbot.auth_handler:http-01 challenge for mydomain.de
2023-04-17 08:18:19,479:DEBUG:certbot.reporter:Reporting to user: The following errors were reported by the server:

Domain: mydomain.de
Type:   unauthorized
Detail: xx.xx.xx.xx: Invalid response from https://mydomain.de/.well-known/acme-challenge/YCGZSvgFD9_Umo0Seqb0e57yFCEoFHkB5SgsWM9D_RE: "<!--BigBlueButton open source conferencing system - http://www.bigbluebutton.org/.-->\n\n<!--Copyright (c) 2022 BigBlueButton Inc." 
```

**Expected behavior**
The certificate should be renewed

**Actual behavior**
The certificate does not renew

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**

Opening the well-known authentication URL in a browser returns a 404, maybe Certbot deletes the challenge after the failure. But from the LE log above it appears as if the LE server received back a 403 error when calling the authentication URL. I guess this happens to the Letsencrypt server as well, so the domain can't be verified.

Did not have this issue under BBB 2.5.

**Comment by jacotec** [comment]
From my perspective the path to /var/www/bigbluebutton-default/.well-known is missing in the nginx config.

Adding this block before the "# Bigbluebutton landing page" in /etc/nginx/sites-available/bigbluebutton" solves the issue for me (restart nginx after the change):

```
  #Letsencrypt
  location ^~ /.well-known/acme-challenge/ {
    allow all;
    default_type "text/plain";
    alias /var/www/bigbluebutton-default/.well-known/acme-challenge/;
  }

```

An `usr/bin/certbot renew` renews the certificate after this change.

**Comment by mvasylenko** [comment]
Webroot was changed in 2.6 from /var/www/bigbluebutton-default/ to /var/www/bigbluebutton-default/assets 
You can correct /etc/letsencrypt/renewal/<your server>.conf manually, if you did an upgrade from BBB 2.5

**Comment by ffdixon** [comment]
We updated `bbb-install-2.6.sh` to now include the `/.well-known/acme-challenge` in the nginx configuration file.

  https://github.com/bigbluebutton/bbb-install/commit/4e6622741bb5a37c7b12d10a9325a0e25fa21360

If you re-run the `bbb-install-2.6.sh` command, Let's Encrypt should now be able to update.   Give it a try and let us know if the above change solves the issue.

**Comment by wurst-hans** [comment]
No luck here. Same as above:

```
IMPORTANT NOTES:
 - The following errors were reported by the server:

   Domain: meet.<domain>.de
   Type:   unauthorized
   Detail: 2a01:4f8:x:y:z: Invalid response from
   http://meet.<domain>.de/.well-known/acme-challenge/MNZjHiJBXLnYs-Z03i68sI3ngpQfIniUqJucJJceAB0:
   404
```

**Comment by Melkin1968** [comment]
> We updated `bbb-install-2.6.sh` to now include the `/.well-known/acme-challenge` in the nginx configuration file.
> 
> [bigbluebutton/bbb-install@4e66227](https://github.com/bigbluebutton/bbb-install/commit/4e6622741bb5a37c7b12d10a9325a0e25fa21360)
> 
> If you re-run the `bbb-install-2.6.sh` command, Let's Encrypt should now be able to update. Give it a try and let us know if the above change solves the issue.

Thank you a lot! The solution works for me fine.
