### ISSUE TITLE
[2.6.2] Telephone participants do not appear in participant sidebar anymore and are not highlighted when they speak

### ISSUE THREAD

**Issue by jacotec** [bigbluebutton/bigbluebutton#17671]
**Describe the bug**
After update to 2.6.2 any dial-in-participants are not appearing in the participant list, They are also not highlighted when they speak. Moderator has zero control over them (can't mute or kick them)

**To Reproduce**
1. Have telephone dial in configured
2. Open conference with waiting room
3. Dial-in via Telephone
4. Moderator gets the waiting participant displayed correctly with the phone number
5. Moderator accepts the participant
6. Telephone participant does not appear in the participant list, but can speak and hear to the conference.
7. When telephone participant speaks, no notification is shown on the screen who speaks
8. Moderator has no control over the telephone participant(s) as they do not appear in the participant list

**Expected behavior**
Telephone participants should appear in the participant list as before

**Actual behavior**
Accepted telephone participants do not appear in the list

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser. Edge, Chrome

**Smartphone (please complete the following information):**
 - Browser [e.g. stock browser, Safari]
 - Version [e.g. 22] 112.0.1722.39

**Additional context**
Was working before, broke in 2.6.2 or 2.6.1

**Comment by hostbbb** [comment]
So just tested with 2.6.1  its working with standard bbb-install.sh and greenlight 3.0.3,  see participant, and can kick them out...

I'm thinking its guest=true related,  let me to try guest options and see if i can replicate your issue.

**Comment by hostbbb** [comment]
So i turned on Guest Policy "Ask Moderator" in the meeting,  this time call trigger the guest room, i approved and entered in the participant list.  Working fine here.

Would be interested in seeing the create call params?  cat /var/log/nginx/bigbluebutton.access.log | grep 'api/create'  I can try and replicate.

**Comment by hostbbb** [comment]
Upgraded to 2.6.2 and I got your same error with and without the guest  Let me debug

**Comment by hostbbb** [comment]
Have the logs, and some developers are looking at the error.  Thanks.

Apr 19 13:43:17 play systemd_start.sh[1153559]: 2023-04-19T13:43:17.302Z backend-2 [#033[31merror#033[39m] : UserJoinedVoiceConfToClientEvtMsg: Error: Match error: Missing key 'color'
Apr 19 13:43:17 play systemd_start.sh[1153559]:     at check (packages/check/match.js:36:17)
Apr 19 13:43:17 play systemd_start.sh[1153559]:     at imports/api/users/server/modifiers/addUser.js:17:3
Apr 19 13:43:17 play systemd_start.sh[1153559]:     at /usr/share/meteor/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
Apr 19 13:43:17 play systemd_start.sh[1153559]:  => awaited here:
Apr 19 13:43:17 play systemd_start.sh[1153559]:     at Function.Promise.await (/usr/share/meteor/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)
Apr 19 13:43:17 play systemd_start.sh[1153559]:     at imports/api/users/server/modifiers/addDialInUser.js:29:13
Apr 19 13:43:17 play systemd_start.sh[1153559]:     at /usr/share/meteor/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
Apr 19 13:43:17 play systemd_start.sh[1153559]:  => awaited here:
Apr 19 13:43:17 play systemd_start.sh[1153559]:     at Function.Promise.await (/usr/share/meteor/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:56:12)
Apr 19 13:43:17 play systemd_start.sh[1153559]:     at imports/api/voice-users/server/handlers/joinVoiceUser.js:36:5
Apr 19 13:43:17 play systemd_start.sh[1153559]:     at /usr/share/meteor/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40

**Comment by gustavotrott** [comment]
We are preparing a new release that will fix it!

@jacotec, I would appreciate if you can give a feedback about this problem once you installed the next release!

**Comment by jacotec** [comment]
@gustavotrott Sure! Will do!

**Comment by hostbbb** [comment]
Confirmed updating to 2.6.3 fixed the issue, all good, thanks

**Comment by jacotec** [comment]
Same here! Thank you for the superfast fixing @gustavotrott !
