### ISSUE TITLE
BBB 2.6.3: Can't select chat content by dragging

### ISSUE THREAD

**Issue by Ithanil** [bigbluebutton/bigbluebutton#17679]
**Describe the bug**
It is not possible to select text in the chat box by clicking and dragging.

**To Reproduce**
1. Try to select chat box content by clicking and dragging.
2. Nothing happens (no selection rectangle visible, nothing gets selected).

**Expected behavior**
You can select text in the chat box by clicking and dragging.

**Actual behavior**
You can't select text in the chat box by clicking and dragging.

**BBB version:**
BigBlueButton Server 2.6.3 (1161)

**Desktop (please complete the following information):**
 - OS: Arch Linux, Debian Linux
 - Browser Chromium, Firefox

**Comment by JeanPluzo** [comment]
Hi,
can confirm. Just updated to 2.6.3 and can't select text in chat.

Regards,
J.

**Comment by defnull** [comment]
Probably caused by https://github.com/bigbluebutton/bigbluebutton/pull/17678

**Comment by hostbbb** [comment]
So can't copy the greenlight url to send to someone...

**Comment by ffdixon** [comment]
Got it.  We were trying to resolve an issue related to using apple pencil on iPads and put in a fix (see https://github.com/bigbluebutton/bigbluebutton/pull/17678/files) that also masked the chat area from the cursor.

We working on an update.

**Comment by ffdixon** [comment]
We have a fix in place -- look for 2.6.4 soon.
