### ISSUE TITLE
no video.yml and screenshare.yml in /usr/local/bigbluebutton/core/scripts/

### ISSUE THREAD

**Issue by Daniel-at-git** [bigbluebutton/bigbluebutton#17677]
In
[https://docs.bigbluebutton.org/administration/customize/#:~:text=%2Fusr%2Flocal%2Fbigbluebutton%2Fcore%2Fscripts%2Fvideo.yml](https://docs.bigbluebutton.org/administration/customize/#:~:text=%2Fusr%2Flocal%2Fbigbluebutton%2Fcore%2Fscripts%2Fvideo.yml)
they mention to edit video.yml and screenshare.yml in /usr/local/bigbluebutton/core/scripts/

But both files are unavailable in 2.6.2 installations.

**Comment by ffdixon** [comment]
Are you able to install the package `bbb-playback-screenshare` and `bbb-playback-notes` to provide these formats?

**Comment by Daniel-at-git** [comment]
@ffdixon Thanks for this hint. Know I undestand [bbb-playback-formatname](https://docs.bigbluebutton.org/administration/customize/#:~:text=The%20processing%20scripts%20and%20playback%20support%20files%20for%20these%20recording%20formats%20can%20be%20installed%20from%20the%20packages%20named%20bbb%2Dplayback%2Dformatname)

Sorry
