### ISSUE TITLE
Media library in server

### ISSUE THREAD

**Issue by jorgelondo** [bigbluebutton/bigbluebutton#17693]
In educational institutions or companies that offer online classes, we usually use the same content to teach the classes.
It would be great to have a media library like on other platforms.
This allows the server's hard drive to not be cluttered with files.
Save time for teachers or users so they don't have to upload the same presentation several times.
organize files into folders and subfolders.
![libreria-2](https://user-images.githubusercontent.com/672505/233796763-b0b1a3fe-ffd8-4e92-9aec-123fb598e816.png)

**Comment by SamuelWei** [comment]
You might be able to achive this using this: https://docs.bigbluebutton.org/development/api/#upload-slides-from-external-application-to-a-live-bigbluebutton-session
However you need a frontend to support this.

**Comment by hostbbb** [comment]
@jorgelondo is that wordress media page?   there is a wordpress api that could be used to integrate this functionality.  sort of like what i "think" nextcloud is doing

**Comment by jorgelondo** [comment]
Hi @SamuelWei and @hostbbb . Thanks for your answer  
The image is just an example for an upcoming media library, but at the moment it is very important for me to be able to do what is shown in the example image of the new features of bbb 2.6 in https://docs.bigbluebutton.org/new-features/
Upload a presentation straight from NextCloud

I was already able to connect Nextcloud with the bbb plugin in bbb 2.65 but I don't know how to do what is shown in the image. (to be able to have the upload button from Nextcloud from the bbb itself)
![26-next-cloud-4ad8859e79b35c21aee9a039eada6725](https://user-images.githubusercontent.com/672505/234294521-2970a77c-f38e-44bf-b60c-ceaee6e84823.png)
Thanks
