### ISSUE TITLE
[2.6.*] Screen sharing and webcam don't show on Firefox

### ISSUE THREAD

**Issue by alirezav2020** [bigbluebutton/bigbluebutton#17696]
**Describe the bug**
Activating webcam in Firefox Browser (v112.0.1 Win x64) only shows avatar picture and screen share not loaded. In browser console I see in log:

Firefox can’t establish a connection to the server at wss://mydomain/bbb-webrtc-sfu?sessionToken=0ry3bxqow8dayqrc. [c782353951675806ca6e124a290399c35bcd3546.js:243:7810](https://mydomain/html5client/c782353951675806ca6e124a290399c35bcd3546.js?meteor_js_resource=true)
The connection to wss://mydomain/bbb-webrtc-sfu?sessionToken=0ry3bxqow8dayqrc was interrupted while the page was loading.

**To Reproduce**

**Update to 2.6.4**
Use Firefox browser to join a room.
Try to see sharing webcam and screen.
Expected behavior
Webcam pic should be visible as in 2.5.10 and before.

**Actual behavior**
Only initials picture / avatar picture is visible. No cam pic. Screen share on Loading with 3 dots

**BBB version:**
BigBlueButton Server 2.6.1, 2.6.3, 2.6.4 everything worked fine on 2.5.10

**Desktop (please complete the following information):**

OS: Win, Linux, Android
Browser Firefox
Version 112.0.1

**Comment by avalou** [comment]
Hi, I've got the same issue with the very same BBB version when I use Firefox. No issue with Chrome/Chromium.

**Comment by alirezav2020** [comment]
> 

No, I have any problem on demo.bigbluebutton.com. Yes, we use more than 5 years of this structure. A separate turn server.

**Comment by quark-s** [comment]
... this indeed fixed those Firefox sharing / camera issues on a 2.6.11 insatalltion! Big thanks. 
Unfortunately, it causes the Whiteboard not to synchronize anymore on any browser . Any ideas?

**Comment by arashe023** [comment]
This problem still persists in version 2.6
Operating system: Arch
Window management: Weiland
Browser: Firefox 120
