### ISSUE TITLE
[2.6.1/2.6.3] 403 no one is able to join the meeting (problem max participants)

### ISSUE THREAD

**Issue by flausen** [bigbluebutton/bigbluebutton#17699]
**Describe the bug**
As soon as the maximum number of participants of a meeting, started via a Stud.IP plugin, is reached, the node does not allow any more participants -> OK! 
If participants leave the meeting so that there is room for new people, they cannot join. Error 403 is displayed. (E.g. For example, in the list of participants there is only 1 person, 20 are allowed.)

11:41:54:0046] ERROR: clientLogger: Failed to validate token: max_participants_reason 

           )).catch((e=>{
                                    c.error("Failed to validate token: ".concat(e.description)),
                                    Session.set("codeError", e.error),
                                    Session.set("errorMessageDescription", e.description)

BigBlueButton 2.6.1 and 2.6.3

**To Reproduce**
1. Start a meeting with a limited Number of possible participants
2. have a meeting with the max number of participants
3. some participants left the room
4. no one can join the meeting.

**Expected behavior**
When participants have left the room, new ones must be able to join because it is unter the limited number of participants

**Actual behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/49376628/233962746-d628a398-575b-4f62-9b05-091efdb41f2f.png)

**Desktop (please complete the following information):**
 - OS: Win
 - Browser Chrome
 - Version 112.0.5615.138

**Smartphone (please complete the following information):**

**Additional context**
See issue [2.5 rc4] Users hitting 403 (tricky to reproduce) #15070

**Comment by flausen** [comment]
![image](https://user-images.githubusercontent.com/49376628/233968007-bda61894-b475-4537-8aec-7b975c18798c.png)

As you can see, the plugin tells ne, that there is no one in the meeting, but at the same time it transmitts 19 names of participants which are courentliy not in the meeting. As a final result, you can't rejoin the meeting.

**Comment by hostbbb** [comment]
I can confirm with api mate and 2.6.4

1) set maxParticipant=2  add 2 users.
2) try to add third get <max participants as expected>

3) remove 1 user.
look at getaMeetingInfo,  you will see participants = 1,  but 2 users still in the list, that why you seel all the names in your front end. after a minute that user dissappears but not immediate as expected.

4) Try to join a new user,  get 403 
You have been removed from the meeting
The maximum number of participants allowed for this meeting has been reached

5) Wait 5 minutes, still get the error... so getMeetingsInfo reporting correct, but no more users can enter.

So the counter never decrements on a leave if i had to guess.
