### ISSUE TITLE
[>=2.6.2] apply-conf.sh not working as expected

### ISSUE THREAD

**Issue by bbb-user-de** [bigbluebutton/bigbluebutton#17692]
**Describe the bug**
sudo bbb-conf --restart, is executed as expected, camera settings are not applyed
...
- Setting camera defaults
- Configuering three Kurento...

**First observed...**
- fresh server with Ubuntu 20.04
- bbb-install-2.6.sh just after release 2.6 OK -> update 2.6.1 OK -> update 2.6.2 Setting camera defaults BROKEN -> update 2.6.4 Setting camera defaults STILL BROKEN

**To Reproduce**
change the camera settings in apply-conf.sh
run sudo bbb-conf --restart

**Expected behavior**
camera settings from apply-conf.sh are applyed

**Actual behavior**
camera settings from apply-conf.sh are NOT applyed

**Comment by hostbbb** [comment]
Looking at apply-config on stock install
root@play:/etc/bigbluebutton/bbb-conf# cat apply-config.sh
#!/bin/bash

# Pull in the helper functions for configuring BigBlueButton
source /etc/bigbluebutton/bbb-conf/apply-lib.sh

enableUFWRules

So only firewall.   So you added the line below to this file?

enableHTML5CameraQualityThresholds

which in the apply-lib should execute
enableHTML5CameraQualityThresholds() {
  echo "  - Enable HTML5 cameraQualityThresholds"
  yq w -i $HTML5_CONFIG public.kurento.cameraQualityThresholds.enabled true
}

if you look in the settings.yml did the value change?

Wondering if its an applylib issue, or that property no longer works  2.6.x

**Comment by bbb-user-de** [comment]
**My  apply-conf.sh**

>#!/bin/bash
>
>#` Pull in the helper functions for configuring BigBlueButton`
>source /etc/bigbluebutton/bbb-conf/apply-lib.sh>
>
>echo "  - Setting camera defaults"
>yq w -i $HTML5_CONFIG 'public.kurento.cameraProfiles.(id==low).bitrate' 50
>yq w -i $HTML5_CONFIG 'public.kurento.cameraProfiles.(id==medium).bitrate' 100
>yq w -i $HTML5_CONFIG 'public.kurento.cameraProfiles.(id==high).bitrate' 200
>yq w -i $HTML5_CONFIG 'public.kurento.cameraProfiles.(id==hd).bitrate' 300
>
>yq w -i $HTML5_CONFIG 'public.kurento.cameraProfiles.(id==low).default' true
>yq w -i $HTML5_CONFIG 'public.kurento.cameraProfiles.(id==medium).default' false
>yq w -i $HTML5_CONFIG 'public.kurento.cameraProfiles.(id==high).default' false
>yq w -i $HTML5_CONFIG 'public.kurento.cameraProfiles.(id==hd).default' false
>chown meteor:meteor $HTML5_CONFIG
>
>enableMultipleKurentos


MultipleKurentos is applyed as expected...
settings.yml - camera settings remain on defaults...

**Comment by JeanPluzo** [comment]
Hi, 

just updated to 2.6.5. Perhaps I don't fully understand but:
- I inserted a custom function in `apply-config.sh`
- Upgraded from 2.6.4 to 2.6.5
- My custom function is still in `apply-config.sh`

Could this mean that the issue is resolved? Am I missing something?

Regards,
J

**Comment by jorgelondo** [comment]
Hi @bbb-user-de i have the same problem. 
bbb Version 2.6.5
AWS instance c6a.xlarge
Ubuntu.

i have this code in the apply-config.sh 

#!/bin/bash

# Pull in the helper functions for configuring BigBlueButton
source /etc/bigbluebutton/bbb-conf/apply-lib.sh

enableUFWRules
#bajar la resolución de las cámaras
echo "  - Setting camera defaults"
yq w -i $HTML5_CONFIG 'public.kurento.cameraProfiles.(id==low).bitrate' 50
yq w -i $HTML5_CONFIG 'public.kurento.cameraProfiles.(id==medium).bitrate' 100
yq w -i $HTML5_CONFIG 'public.kurento.cameraProfiles.(id==high).bitrate' 200
yq w -i $HTML5_CONFIG 'public.kurento.cameraProfiles.(id==hd).bitrate' 300

yq w -i $HTML5_CONFIG 'public.kurento.cameraProfiles.(id==low).default' true
yq w -i $HTML5_CONFIG 'public.kurento.cameraProfiles.(id==medium).default' false
yq w -i $HTML5_CONFIG 'public.kurento.cameraProfiles.(id==high).default' false
yq w -i $HTML5_CONFIG 'public.kurento.cameraProfiles.(id==hd).default' false
chown meteor:meteor $HTML5_CONFIG

#habilitar varios kurentos  para audio, cámaras y  compartir pantalla
enableMultipleKurentos

![bbb-error-webcam](https://user-images.githubusercontent.com/672505/234432082-fb67cc56-f4eb-4548-b68c-5045d49c87ac.png)

Thanks for your help

**Comment by bbb-user-de** [comment]
SEE:
https://github.com/bigbluebutton/bigbluebutton/pull/17369
https://github.com/bigbluebutton/bigbluebutton/issues/17733

**Comment by jorgelondo** [comment]
Hello, thanks I will wait attentively for the new release 2.6.6. Thank you!
