### ISSUE TITLE
bbb 2.6.4 The system didn't load the turn server config file /usr/share/bbb-web/WEB-INF/classes/spring/turn-stun-servers.xml

### ISSUE THREAD

**Issue by ebram-roywong** [bigbluebutton/bigbluebutton#17697]
**Describe the bug**
I installed bbb 2.6.4 and added my stun and turn servers on the config file /usr/share/bbb-web/WEB-INF/classes/spring/turn-stun-servers.xml. I guess that the system didn't load the setting file, as I enabled the 'relay' to 'true' in about:config on firefox and opened about:webrtc to see the turn connection, I only see the my bbb server's domain (urls: ["turn:bbb.xxx.com:3478"] and urls: ["turns:bbb.xxx.com:443?transport=tcp"]) on 'Show Configuration', it is not my turn server's domain.

**Installation type**
I have used the bbb-install script to install the latest version.

**Firewall and IP address type**
My server haven't behind any firewall and the BBB server have its own IPv4 addres.

**Comment by ffdixon** [comment]
Hi @ebram-roywong, we just fixed an error in the [docs](https://docs.bigbluebutton.org/administration/turn-server/#configure-bigbluebutton-to-use-your-turn-server).  You should edit the file `/etc/bigbluebutton/turn-stun-servers.xml`.

Try it again and let us know if it now has your TURN server settings.

**Comment by jorgelondo** [comment]
Hi @ebram-roywong this work form my

/etc/bigbluebutton/turn-stun-servers.xml

<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://www.springframework.org/schema/beans
        http://www.springframework.org/schema/beans/spring-beans-2.5.xsd">

    
    

    <bean id="turn0" class="org.bigbluebutton.web.services.turn.TurnServer">
        <constructor-arg index="0" value="SECRET IN /etc/turnserver.conf"/>
        <constructor-arg index="1" value="turns:turn.example.com:443?transport=tcp"/>
        <constructor-arg index="2" value="86400"/>
    </bean>
    <bean id="turn1" class="org.bigbluebutton.web.services.turn.TurnServer">
        <constructor-arg index="0" value="SECRET IN /etc/turnserver.conf"/>
        <constructor-arg index="1" value="turn:turn.example.com:443?transport=tcp"/>
        <constructor-arg index="2" value="86400"/>
    </bean>

    <bean id="stunTurnService"
            class="org.bigbluebutton.web.services.turn.StunTurnService">
        <property name="stunServers">
            <set>
                
            </set>
        </property>
        <property name="turnServers">
            <set>
                <ref bean="turn0"/>
                <ref bean="turn1"/>
            </set>
        </property>
    </bean>
</beans>


# 1 Secret is the secret in turnserver.conf
# 2 You must create the DNS type A turn.example.com addressed with the ip value
# 3 To generate the certificates First stop NGINX
sudo systemctl stop nginx for free port 80 
#4 generate cert
https://certbot.eff.org/instructions?ws=nginx&os=ubuntufocal
sudo snap install core; sudo snap refresh core
sudo snap install --classic certbot
sudo ln -s /snap/bin/certbot /usr/bin/certbot
sudo certbot --nginx
sudo certbot certonly --nginx

sudo certbot certonly --standalone --preferred-challenges http \
>  -d turn.example.com
# 5 Restart coturn
sudo systemctl restart coturn

# 6 start NGIX
sudo systemctl start nginx
# 7 start BBB
sudo bbb-conf --restart

**Comment by ebram-roywong** [comment]
Thank you so much, it's work now, I copied my setting from /usr/share/bbb-web/WEB-INF/classes/spring/turn-stun-servers.xml to /etc/bigbluebutton/turn-stun-servers.xml,

**Comment by easy-bios** [comment]
This may be related to here: Why is there no more Stun Server? Is it not necessary if you already have a Turn Server?
