### ISSUE TITLE
[2.6.4] Webcam in Firefox Browser (Win) not possible

### ISSUE THREAD

**Issue by motsiw** [bigbluebutton/bigbluebutton#17694]
**Describe the bug**
Activating webcam in Firefox Browser (v112.0.1 Win x64) only shows avatar picture. Cam pic never appears.

**To Reproduce**
1. Update to 2.6.4
2. Use Firefox browser to start a room.
3. Try to share your webcam.

**Expected behavior**
Webcam pic should be visible as in 2.6.3 and before.

**Actual behavior**
Only initials picture / avatar picture is visible. No cam pic.

**BBB version:**
BigBlueButton Server 2.6.4 - up to 2.6.3, everything worked fine.

**Desktop (please complete the following information):**
 - OS: Win
 - Browser Firefox
 - Version 112.0.1

**Comment by Zer0CooL4ek** [comment]
installed the update yesterday everything looks fine
![Снимок экрана 2023-04-24 092436](https://user-images.githubusercontent.com/22744153/233915857-6b313e16-38e1-4bf9-a4db-3f28e30daa1b.jpg)

**Comment by hostbbb** [comment]
112.0.1 Windows works for me on firefox,  with and without forcing the media to relay thru coturn...
