### ISSUE TITLE
Cameras container blocking buttons click

### ISSUE THREAD

**Issue by antonbsa** [bigbluebutton/bigbluebutton#17703]
**Describe the bug**
When the cameras are positioned somewhere different than the default (aside or below the presentation), the near buttons can not be clicked;

**To Reproduce**
1. Join in a meeting;
2. Start sharing webcam;
3. Set custom layout;
4. Move cameras to other locations;

**Comment by trinhhuutam** [comment]
Maybe relate to my latest comment on https://github.com/bigbluebutton/bigbluebutton/issues/17375
