### ISSUE TITLE
[2.6.5] (+) Action button cant be clicked after Layout Setting Focus on presentation or Focus on Video

### ISSUE THREAD

**Issue by chandraes** [bigbluebutton/bigbluebutton#17711]
(+) Action button cant be clicked after change layout setting to focus on presentation or focus on video with webcam share.

**To Reproduce**
1. Share some webcame
2. Click on (+) button.
3. change layout to Focus on presentation or Focus on video
4. (+) button cant be click anymore

**BBB version:**
BigBlueButton Server 2.6.5 (1153)

**Desktop:**
 - OS: Mac
 - Browser Mozilla Firefox

**Comment by trinhhuutam** [comment]
Maybet relate to my latest comment on https://github.com/bigbluebutton/bigbluebutton/issues/17375

**Comment by antobinary** [comment]
Merging into https://github.com/bigbluebutton/bigbluebutton/issues/17703 which is fixed by https://github.com/bigbluebutton/bigbluebutton/pull/17705 and will be out with BBB 2.6.6. Thanks for reporting!
