### ISSUE TITLE
[2.6.5] Webcam area under chat too wide, hiding + button

### ISSUE THREAD

**Issue by SamuelWei** [bigbluebutton/bigbluebutton#17712]
**Describe the bug**
Moving the webcam to the area under the chat breaks the layout. Webcam is too wide, hiding the plus action button.

**To Reproduce**
1. Activate webcam
2. Click on webcam, drag to area under the chat
3. See layout issue

**Expected behavior**
The webcam area should not be wider than the chat

**Actual behavior**
Webcam area is too wide, causing layout issues

**Screenshots**
![image](https://user-images.githubusercontent.com/4281791/234248505-4c01c6f9-aece-4c4f-8060-4e8141ee5cc4.png)

**BBB version:**
Client build: 574
BigBlueButton version: 2.6.5
Server: test26.bigbluebutton.org

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version Version 112.0.5615.138 (64-Bit)

**Comment by SamuelWei** [comment]
Probably related to #17375

**Comment by antobinary** [comment]
Merging into https://github.com/bigbluebutton/bigbluebutton/issues/17703 which is fixed by https://github.com/bigbluebutton/bigbluebutton/pull/17705 and will be out with BBB 2.6.6. Thanks for reporting!
