### ISSUE TITLE
[2.6.X] Saving Usernames sorts in the same order for both first and last name

### ISSUE THREAD

**Issue by Subdarub** [bigbluebutton/bigbluebutton#17734]
**Describe the bug**
Saving usernames will produce 2 lists that are sorted in the same order.

**To Reproduce**
1. Save usernames in a conference

**Expected behavior**
Get 2 lists one sorted by last name one sorted by first name

**Actual behavior**
Get 2 lists in the same order.

**Screenshots**
```
List of users in meeting Startraum at 4/26/2023:10:40:28 AM

Sorted by first name:
Jane, Doe
Jane, Doe2
Jane, Doe3
  

Sorted by last name:
Jane, Doe
Jane, Doe2
Jane, Doe3

```

**Comment by krim404** [comment]
I can confirm this problem on our cluster
