### ISSUE TITLE
It would be very good to be able to upload several pdf files in the presentatios tab

### ISSUE THREAD

**Issue by jorgelondo** [bigbluebutton/bigbluebutton#17779]
It would be very good to be able to upload several pdf files in the presentation tab, normally a teacher needs to upload several files, in our case it only allows uploading 1 (a single file) of presentation.
the solution should look something like this:
![file_upload-solution](https://user-images.githubusercontent.com/672505/235543952-ea4fcccb-0c50-4f6d-9135-9eb8f43cf75a.jpg)

**Comment by ffdixon** [comment]
Yes, GreenLight only allows uploading of a single presentation.   You can pick a single presentation for upload by GreenLight (the default presentation), and BigBlueButton you can drag-and-drop multiple presentations for the rest

<img width="655" alt="image" src="https://user-images.githubusercontent.com/290351/235558020-a78bfd86-38a4-46ca-8ef9-34f85cb5f1c5.png">

This issue tracker is for BigBlueButton.  Recommend you open this issue in the GreenLight issue tracker here: https://github.com/bigbluebutton/greenlight/issues.

**Comment by jorgelondo** [comment]
Hi, Thank you @ffdixon  I understand, in our case and I think that in the case of many other companies and educational institutions the teacher prefers to prepare the class in advance, that is, a few days or hours before entering the classroom, upload the contents (pdf's) before the class.
What we see is that if the contents are uploaded by bbb before the class, when starting the room again, the contents have been deleted.
