### ISSUE TITLE
Frozen webcam button once the focus on video layout is pushed to all (screen recording attached for reference) 

### ISSUE THREAD

**Issue by anandchristudas** [bigbluebutton/bigbluebutton#17772]
**Describe the bug**
When you turn on the webcam and try to push focus on video layout to all, all the buttons like the action button, join audio button, share webcam button, screen share button, and minimize presentation button everything gets frozen. Devices connected on mobile are not affected. 

**To Reproduce**
1. Turn on the webcam
2. Click layout setting modal
3. Push layout to all 
4. Select focus on video
5. Confirm

**Expected behavior**
Once the layout focus on video is pushed to all, all the buttons like the action button, join audio button, share webcam button, screen share button, and minimize presentation button are supposed to work

**Actual behavior**
After the layout focus on video is pushed to all, all the buttons like the action button, join audio button, share webcam button, screen share button, and minimize presentation button are all frozen. Devices connected on mobile are not affected. 

**Screen recording of the issue. (turn on the audio to understand the issue better)**

https://user-images.githubusercontent.com/95290346/235294635-3bb046d1-42a0-4073-9d53-c22568d1e7eb.mp4

**Bigbluebutton Version: 2.6.5**

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome 
 - Version112.0.5615.138

**Comment by jorgelondo** [comment]
Hi, @anandchristudas  Maybe relate to https://github.com/bigbluebutton/bigbluebutton/issues/17375

**Comment by anandchristudas** [comment]
> Hi, @anandchristudas Maybe relate to #17375

maybe, but in this case, mobile and IPad users don't have any issues, the laptop users are getting affected.

**Comment by schorschroch** [comment]
Hi there,

I've just checked the issue via debugger mode in web browser.
The overlaying div "cameraDock" causes the unreachable buttons.

I think, the issue can be easily solved by adding the css rule "z-index:1" to layer "ActionsBar".
`<section id="ActionsBar" ...>`

Hope this helps and this issue will be fixed soon.

Best, Schorsch

**Comment by schorschroch** [comment]
> Hi there,
> 
> I've just checked the issue via debugger mode in web browser. The overlaying div "cameraDock" causes the unreachable buttons.
> 
> I think, the issue can be easily solved by adding the css rule "z-index:1" to layer "ActionsBar". `<section id="ActionsBar" ...>`
> 
> Hope this helps and this issue will be fixed soon.
> 
> Best, Schorsch

**Addendum:**
**My Workaround:**
Create a file custom.css with following content:
"_sudo nano /var/www/bigbluebutton-default/assets/custom.css_"
`#ActionsBar {
    z-index:1
}
`
add the following (in one line) to "/etc/bigbluebutton/bbb-conf/apply-config.sh":
"_sudo nano /etc/bigbluebutton/bbb-conf/apply-config.sh_"
`sed -i 's/customStyleUrl:.*/customStyleUrl: \/custom.css/g' 
/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml`

Then restart your BBB server
"_sudo bbb-conf --restart_"

**Comment by anandchristudas** [comment]
Hi @schorschroch thanks a lot. Will try that and let you know if it works. :)

**Comment by FreeScholar** [comment]
This issue is fixed in v2.6.6
Noted by Fred on the google groups site.

Thanks Fred and Team - swift work!!!!
