### ISSUE TITLE
After finishing a session, it does not allow uploading a presentation

### ISSUE THREAD

**Issue by jorgelondo** [bigbluebutton/bigbluebutton#17778]
![file_upload](https://user-images.githubusercontent.com/672505/235542223-4131ef9c-0ba6-41b4-992a-aff4828d2837.png)

It would be ideal if the teacher could upload a presentation after finishing the class, to be able to reuse it in a new class.
This is useful if you want to do a classroom per group or per student in the case of personalized classes.

**Comment by ffdixon** [comment]
We just tried it here and after we started a session in GreenLight, ended the session within BigBlueButton, and were able to successfully upload a presentation.

<img width="1142" alt="image" src="https://user-images.githubusercontent.com/290351/235558470-c2749689-6f4f-42e6-9705-5b2027db0bcf.png">

If your able to provide steps to reproduce this on https://demo.bigbluebutton.org/ (which as GreenLight as the front-end), then open an issue for it in the GreenLight issue tracker at https://github.com/bigbluebutton/greenlight/issues.

**Comment by jorgelondo** [comment]
Thanks @ffdixon , I think it is related to the file size in Greenlight.
https://github.com/bigbluebutton/greenlight/issues/5142
Sorry for posting this here
