### ISSUE TITLE
Listen only error - When trying to connect in audio only it does not work - SIP_CALL_TIMEOUT

### ISSUE THREAD

**Issue by jorgelondo** [bigbluebutton/bigbluebutton#17775]
When trying to connect in audio only it does not work

1 -start classroom
2 -click the "audio only" button

**To Reproduce**
 
![solo-audio-error-2](https://user-images.githubusercontent.com/672505/235332485-cf017d33-eb68-416f-9916-2bdaf97b7958.png)
![solo-audio-error-3](https://user-images.githubusercontent.com/672505/235332804-ef269089-2203-4289-8fa9-c5e5b0162935.png)

in the console:
Listen only error - SIP_CALL_TIMEOUT - bridge: fullaudio https://bbb.example.com/html5client/b957282ec7fafa119a80ffff62d3a1516373e2e3.js?meteor_js_resource=true:434:1374969
 

**BBB version:**
BigBlueButton 2.6.5
Example:
$ sudo bbb-conf --check | grep BigBlueButton
 
BigBlueButton Server 2.6.5 (1160)
                    Kernel version: 5.15.0-1035-aws
                      Distribution: Ubuntu 20.04.6 LTS (64-bit)
                            Memory: 7949 MB
                         CPU cores: 4

--------------------------------------
/etc/bigbluebutton/bbb-web.properties (override for bbb-web)
/usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties (bbb-web)
       bigbluebutton.web.serverURL: https://bbb.example.com
                defaultGuestPolicy: ALWAYS_ACCEPT
              defaultMeetingLayout: CUSTOM_LAYOUT

/etc/nginx/sites-available/bigbluebutton (nginx)
                       server_name: bbb.example.com
                              port: 80, [::]:80127.0.0.1:82 http2 proxy_protocol, [::1]:82 http2127.0.0.1:81 proxy_protocol, [::1]:81

/opt/freeswitch/etc/freeswitch/vars.xml (FreeSWITCH)
                       local_ip_v4: xxx.xxx.xxx.xxx
                   external_rtp_ip: xxx.xxx.xxx.xxx
                   external_sip_ip: xxx.xxx.xxx.xxx

/opt/freeswitch/etc/freeswitch/sip_profiles/external.xml (FreeSWITCH)
                        ext-rtp-ip: $${external_rtp_ip}
                        ext-sip-ip: $${external_sip_ip}
                        ws-binding: xxx.xxx.xxx.xxx:5066
                       wss-binding: xxx.xxx.xxx.xxx:7443

UDP port ranges

                        FreeSWITCH: 16384-24576
                           kurento: 24577-32768
                    bbb-webrtc-sfu: 24577-32768

/usr/local/bigbluebutton/core/scripts/bigbluebutton.yml (record and playback)
                     playback_host: bbb.example.com
                 playback_protocol: https
                            ffmpeg: 4.2.7-0ubuntu0.1

/usr/share/bigbluebutton/nginx/sip.nginx (sip.nginx)
                        proxy_pass: xxx.xxx.xxx.xxx
                          protocol: http

/usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml (bbb-webrtc-sfu)
/etc/bigbluebutton/bbb-webrtc-sfu/production.yml (bbb-webrtc-sfu - override)
    mediasoup.webrtc.*.announcedIp: xxx.xxx.xxx.xxx
  mediasoup.plainRtp.*.announcedIp: xxx.xxx.xxx.xxx
                        kurento.ip: xxx.xxx.xxx.xxx
                       kurento.url: ws://127.0.0.1:8888/kurento
                 freeswitch.sip_ip: xxx.xxx.xxx.xxx
               recordScreenSharing: true
                     recordWebcams: true
                  codec_video_main: VP8
               codec_video_content: VP8

/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml (HTML5 client)
/etc/bigbluebutton/bbb-html5.yml (HTML5 client config override)
                             build: 574
                        kurentoUrl: wss://bbb.example.com/bbb-webrtc-sfu
            defaultFullAudioBridge: sipjs
           defaultListenOnlyBridge: fullaudio
                    sipjsHackViaWs: true

*Desktop 
 - OS:   Windows 
 - Browser:  firefox 112.0.2 (64-bit)
 -  and Google Chrome Versión 112.0.5615.138
 - 
Thanks

**Comment by jorgelondo** [comment]
I had this option enabled in the file  /etc/bigbluebutton/bbb-html5.yml
defaultListenOnlyBridge: fullaudio
I changed it to the following: 
defaultListenOnlyBridge: sipjs
And everything worked again

**Comment by ffdixon** [comment]
Thanks for sharing how you got it to work.  As of 2.6, we don't recommend using `defaultListenOnlyBridge: fullaudio` for production yet.  We're working on getting it there for a future version.
