### ISSUE TITLE
When the file is selected, the upload starts automatically - button is only to add the presentation to the whiteboard

### ISSUE THREAD

**Issue by jorgelondo** [bigbluebutton/bigbluebutton#17786]
Hi, I suggest this change in the text of the "Upload" button to "Upload in Whiteboard" has seen that some of our teachers upload the presentation and as the message "In the process of being uploaded" is displayed they think that it is going to be uploaded directly, so I suggest change the button text to "Upload to Classroom" or "Put on whiteboard" so they know it's a different process than just uploading.

and when it finishes uploading the file, show a message "The file has been uploaded"
![upload_presentation_3](https://user-images.githubusercontent.com/672505/235691326-5153255a-b4f6-4c8f-8fd3-2360746ad381.png)
Solution:
![upload_presentation_solucion](https://user-images.githubusercontent.com/672505/235693019-1f8cc39a-b7e3-4c53-8634-d9fcf5adf829.png)

Thanks.

**Comment by jorgelondo** [comment]
Seeing the way in which the files are loaded, I propose that when the file is selected, ![Cambio-proceso-carga-PROPUESTA](https://user-images.githubusercontent.com/672505/236235611-e1c67812-396b-4a52-ab75-ddc064ce668f.png) and not wait for the "Load" button to be clicked and a loading bar to be displayed in this part .

All this so that the upload process is faster and that the "Upload in Whiteboard" button is only to add the presentation to the whiteboard, not to upload the file.

**Comment by debuglevel** [comment]
This would be nice. It's very uncommon nowadays to actually press a button to start uploading something.
