### ISSUE TITLE
[2.6.5]  Closed Captions - Start dictation button is inactive

### ISSUE THREAD

**Issue by amg-web** [bigbluebutton/bigbluebutton#17781]
**Describe the bug**
After activation "Write Closed Caption" button **Start Dictation** is inactive
Error from dev console is below.

**Screenshots**
![Screenshot from 2023-05-02 10-02-43](https://user-images.githubusercontent.com/22151881/235603106-c34ec5d1-f2c2-44a0-85a6-cf593bd54906.png)

**Desktop (please complete the following information):**
 - OS:  Windows, Linux
 - Browser  Chrome
 - Version  112.0.5615.165

**Additional context**
Error from browser's dev console
```
[10:06:45:0054] ERROR: clientLogger: Captions speech recognition error a.onError (https://bigbluebutton.server.org/html5client/b957282ec7fafa119a80ffff62d3a1516373e2e3.js?meteor_js_resource=true:434:13246)
DevTools failed to load source map: Could not load content for https://bigbluebutton.server.org/pad/socket.io/socket.io.js.map: Unexpected token '/', "/*!
 * Soc"... is not valid JSON
```

**Comment by hiroshisuga** [comment]
Is dictation true in the setting for bbb-html5?
https://github.com/bigbluebutton/bigbluebutton/blob/9f91d66b605a2580ff160c7ed938535b72713c7a/bigbluebutton-html5/private/config/settings.yml#L507

**Comment by amg-web** [comment]
@hiroshisuga 
I think I missed it. 

any way does not work:
```
DevTools failed to load source map: Could not load content for https://xdomain.com/pad/socket.io/socket.io.js.map: Unexpected token '/', "/*!
 * Soc"... is not valid JSON
b957282ec7fafa119a80ffff62d3a1516373e2e3.js?meteor_js_resource=true:139 [09:08:27:0757] ERROR: clientLogger: Captions speech recognition error a.onError (https://xdomain.com/html5client/b957282ec7fafa119a80ffff62d3a1516373e2e3.js?meteor_js_resource=true:434:13246)
b957282ec7fafa119a80ffff62d3a1516373e2e3.js?meteor_js_resource=true:139 [09:08:28:0916] ERROR: clientLogger: Captions speech recognition error p.onError (https://xdomain
.com/html5client/b957282ec7fafa119a80ffff62d3a1516373e2e3.js?meteor_js_resource=true:434:863092)

```
![Screenshot from 2023-05-03 09-03-23](https://user-images.githubusercontent.com/22151881/235843043-7282a5e8-4af3-4b06-98e9-1769dfb9a9c9.png)


Is it possible to download generated closed captions?

**Comment by amg-web** [comment]
same to windows google chrome

**Comment by FreeScholar** [comment]
Confirmed it does not work:
Latest Chrome Version 113.0.5672.92 (Official Build) (64-bit)
GNU/Linux Ubuntu 22.04

On the shared notes tab, the "Start Dictation" button is grey and not clickable

![image](https://github.com/bigbluebutton/bigbluebutton/assets/1201170/238d6c65-3ecd-4240-910e-f282c2a34e18)

**Comment by FreeScholar** [comment]
Confirmed it does not work:
Latest Chrome Version 113.0.5672.92 (Official Build) (64-bit)
GNU/Linux Ubuntu 22.04

On the shared notes tab, the "Start Dictation" button is grey and not clickable

![image](https://github.com/bigbluebutton/bigbluebutton/assets/1201170/9e808439-8b0c-4143-864f-75cf24c9c62d)

**Comment by FreeScholar** [comment]
Confirmed it does not work:
Latest Chrome Version 113.0.5672.92 (Official Build) (64-bit)
GNU/Linux Ubuntu 22.04

On the shared notes tab, the "Start Dictation" button is grey and not clickable

![image](https://github.com/bigbluebutton/bigbluebutton/assets/1201170/e57792f6-173d-4f67-b2b0-852992f48da6)

**Comment by FreeScholar** [comment]
Confirmed it does not work:
Latest Chrome Version 113.0.5672.92 (Official Build) (64-bit)
GNU/Linux Ubuntu 22.04

On the shared notes tab, the "Start Dictation" button is grey and not clickable

![image](https://github.com/bigbluebutton/bigbluebutton/assets/1201170/3d032543-446d-4794-aa2d-976d503eef68)

**Comment by hiroshisuga** [comment]
I am not sure if Linux version of Chrome works for dictation. Even if you use Windows, this function does not work time to time. That's one of the reasons why the devs try to use an open dictation server, which is coming along with BBB2.7.

To check if your environment is compatible, visit:
https://www.google.com/intl/ja/chrome/demos/speech.html

**Comment by ReimarBauer** [comment]
with a bit trying it works now, auto enabled from the start of the room

**Comment by ReimarBauer** [comment]
btw. when you combine it with libretranslate in your browser you do get a autotranslation of the caption.

**Comment by q16marvin** [comment]
> with a bit trying it works now, auto enabled from the start of the room

and what did you do to got it work?
