### ISSUE TITLE
It would be ideal if the teacher could upload a presentation after "leave the meeting"

### ISSUE THREAD

**Issue by jorgelondo** [bigbluebutton/bigbluebutton#17788]
It would be ideal if the teacher could upload a presentation after "leave the meeting" It is important to prepare the class in advance
When a teacher uploads content to prepare their class an hour or a day before class, when they re-enter the classroom, the presentations have already been deleted.
It would be ideal for the presentations to only be deleted at the "end of the class" but when leaving it you can return to the time of the class and the contents remain without being deleted.

![upload_presentation_2](https://user-images.githubusercontent.com/672505/235700488-de2fb854-12a5-4f7d-b8c4-bf8a738b0afb.png)

**Comment by jorgelondo** [comment]
Hi or I don't know if there is any time parameter that I can modify so that the presentations are available longer

**Comment by SamuelWei** [comment]
In BigBlueButton an uploaded presentation, as well as all other content (Chat, Shared Notes, etc.) only exists during a running meeting. Bigbluebutton has no concept for persisting rooms, only temporary meetings. To always use the same room, a frontend creates a meeting every time no meeting for this room is running.

To prevent a meeting from closing and causing a re-creation on the second join a few hours later you have to adjust the API or Server config for endNoModerator (or something similar). In case a noderators clicks on end Meeting and not leave Meeting the content is always gone. 
Some frontends however allow you to preupload one or more presentation to mitigate this issue.

**Comment by hostbbb** [comment]
Not ideal, but you an also have teacher export the presentation with annotations preserving the whiteboard to a pdf they download, then the next class they use this as the presentation to continue teaching where they left off.

**Comment by ffdixon** [comment]
To expand on the above, we have the goal of creating a "continuous learning environment" where the content at the end of the current class is available at the beginning of the next class.  There is no timeline for this, but when we implement it, it will go a long way to letting you configure your classroom for an upcoming session regardless of the Front-end you are using.

**Comment by jorgelondo** [comment]
Hi @SamuelWei , @hostbbb , @ffdixon , Thank you very much for all your answers. They are an incredible team, I want to share that this week we started all our classes with Bigbluebutton and we found it to be a spectacular tool. 
Thank you for all your effort and work.

**Comment by jorgelondo** [comment]
Hi @ffdixon This would be fantastic, especially in the educational institutions because teachers like to plan their classes and have them scheduled in advance. It is the most desired feature of our teachers. Thanks

Hi @SamuelWei Can you tell me what those interfaces allow you to preload one or more presentations? Thanks

**Comment by SamuelWei** [comment]
Hi @jorgelondo,

Greenlight currently only supports one presentation. I don't know if LMS Plugins like Moodle, or Nextcloud would allow more, maybe @ffdixon knows a bit more.

I maintain a greenlight alternative called PILOS (https://github.com/THM-Health/PILOS).
We have some features greenlight doesn't has and vice verse. e.g. we currently don't support recordings; full comparision with Greenlight v2: https://github.com/THM-Health/PILOS/wiki/Comparison-Greenlight-and-PILOS

Here is a screenshoot how it looks to manage multiple presentations: 
![image](https://github.com/bigbluebutton/bigbluebutton/assets/4281791/1d53d7fb-74e6-4d59-8f20-49bee534a0f1)

You can try it on our demo page: https://pilos.coding-space.de/

If you have any questions, feel free to reach out to me.

**Comment by jorgelondo** [comment]
hi @SamuelWei Thank you very very much.

**Comment by SamuelWei** [comment]
We support BBB 2.6 and have an offical migration path for Greenlight 2. We havn't looked into Greenlight 3 yet, but it shouldn't be to complex

**Comment by jorgelondo** [comment]
Thank you @SamuelWei , I did see it, but since I'm not a developer, suddenly it's complex for me, but I'm going to try it and if I succeed I'll tell you. Thank you so much!

**Comment by SamuelWei** [comment]
The migration process is done once, it's not designed to keep greenlight and PILOS in sync. However if bbb is getting an update nothing changes, as the frontend (greenlight/pilos) is communicating with bbb over an stable api.

**Comment by jorgelondo** [comment]
Hi @SamuelWei , do you provide a commercial service to install and configure PILOS?

**Comment by SamuelWei** [comment]
@jorgelondo My work on PILOS is part of my job at the university - therefore I cannot directly provide any commercial service. However, if you have any specific questions, let me know and I will try my best to assist you.

In case you need a feature that is not part of the open source project yet, I can also offer you to develop this feature outside of my regular job and as part of my freelance business. If this would be something you are looking for, let me know.

**Comment by jorgelondo** [comment]
Hi, Samuel, thank you very much for your answer, okay, I'm going to try installing PILOS but if I have an urgent task, can you give me a way to contact you for a freelance proposal ...
It's about connecting to NextCloud and being able to choose files from a folder and be able to explore it or could also from Google drive. 
https://github.com/bigbluebutton/bigbluebutton/issues/17693#issuecomment-1521813634
Thank you so much.
