### ISSUE TITLE
Some types of pdf documents do not upload correctly

### ISSUE THREAD

**Issue by jorgelondo** [bigbluebutton/bigbluebutton#17780]
Hi, Some types of pdf documents do not upload correctly, in this case I show the properties of the pdf to see if they are related to not being able to upload
![error-pdf-2](https://user-images.githubusercontent.com/672505/235544560-633798d3-efb9-4432-8cb3-83f7ce421fd1.png)
![error-pdf-1](https://user-images.githubusercontent.com/672505/235544563-f601dd8d-ed58-4e60-9316-0d1e3ba15937.png)
I don't know if I should change the format of the pdf's or is there an option to determine what type of pdf's are allowed to be uploaded.

This other type of pdf if you uploaded it, but that is not related by the weight of the file or by the pdf format

![error-pdf-3-ok](https://user-images.githubusercontent.com/672505/235546412-a0dc3434-6074-4e47-b5a0-0af4d145af3f.png)

Thanks

**Comment by ffdixon** [comment]
Can you share a sample PDF that can't be uploaded.

**Comment by jorgelondo** [comment]
Hi @ffdixon What I see is that it has to do with the weight of the pdf file in Greenlight and not in the format,
https://github.com/bigbluebutton/greenlight/issues/5142
PRESENTATION_MAX_FILE_SIZE in app/javascript/helpers/FileValidationHelper
I'm going to close the issue. Thanks
