### ISSUE TITLE
PNG images are resized to full screen

### ISSUE THREAD

**Issue by bigbluebutton-issue-import** [bigbluebutton/bigbluebutton#1778]
Originally reported on Google Code with ID 1023

```
What steps will reproduce the problem?
1.  Upload a 200 x 100 PNG image to the presentation (see resize.png)
2.
3.

What is the expected output? What do you see instead?
Expected to to show at actual size, but instead the image resized to fit the presentation
window.

See resize1.png

BigBlueButton should do some pre-processing processing on the image before converts
it to a swf file.  In this case, it should embed the image in a white background that
is the correct size when displayed by the user.

Note "Correct size" here is relative since BigBlueButton client doesn't know the scale
at which the user is displaying the image in the presentation window, but if we place
it in a white background of the appropriate size we can give the presenter better results.

See resize3.png

Please use labels and text to provide additional information.

```

Reported by `ffdixon` on 2011-09-28 15:16:48

<hr>
- _Attachment: resize.png<br>![resize.png](https://storage.googleapis.com/google-code-attachments/bigbluebutton/issue-1023/comment-0/resize.png)_
- _Attachment: resize1.PNG<br>![resize1.PNG](https://storage.googleapis.com/google-code-attachments/bigbluebutton/issue-1023/comment-0/resize1.PNG)_
- _Attachment: resize3.png<br>![resize3.png](https://storage.googleapis.com/google-code-attachments/bigbluebutton/issue-1023/comment-0/resize3.png)_

**Comment by ffdixon** [comment]
Closing as this was an issue related to the Flash client (the project has moved to an HTML5 client).
