### ISSUE TITLE
JPG annotated export fails

### ISSUE THREAD

**Issue by GuiLeme** [bigbluebutton/bigbluebutton#17807]
**Describe the bug**
When the user tries to export to chat a `JPG` annotated presentation, they get an error. 

**To Reproduce**
1. Upload a JPG document;
2. Make an annotation in this presentation like an X;
3. Go to the presentation uploader modal and click `send to chat` button;
4. See error;

**Expected behavior**
Exporting to chat should happen normally with a `JPG` image.

**Actual behavior**
Export fails when extension is `JPG`.

**Screenshots**
A video to clarify the situation:

https://user-images.githubusercontent.com/69865537/236202169-a6e3393f-b24a-4543-8061-80c8d86a4938.mp4

Screenshot of the error in bbb-export-annotations: 

![image](https://user-images.githubusercontent.com/69865537/236202554-380c7aac-9797-4123-9275-17f4edf7c359.png)

**BBB version:**
`v2.6.x-release` branch

**Comment by danielpetri1** [comment]
Thanks for the report @GuiLeme! PR #17813 adds a check for `JPG` files on top of `JPEG` to prevent this issue from arising.
