### ISSUE TITLE
Recording API content size

### ISSUE THREAD

**Issue by blueiceprj** [bigbluebutton/bigbluebutton#17805]
**Is your feature request related to a problem? Please describe.**
I want to check the size of the recordings(all content) and manage all of them via external app. With this option we can control of scalelite disk size using api by external app

**Describe the solution you'd like**
It should be added to recording api

**Describe alternatives you've considered**

**Additional context**

**Comment by blueiceprj** [comment]
Ok. Thanks and I will try it.

**Comment by blueiceprj** [comment]
It didn't work. But I found it on each recording as size
<img width="346" alt="Ekran Resmi 2023-05-04 16 09 09" src="https://user-images.githubusercontent.com/1829975/236232926-1a27771e-0a9c-4647-8c56-befb7d4a940a.png">

**Comment by hostbbb** [comment]
yes, that is what i was referring to.  you can make a call to fetch all recordings on BBB,  not sure if scalelite supports.

**Comment by hostbbb** [comment]
As a user of bbb your welcome to contribute pull requests to the documentation to help others..

**Comment by blueiceprj** [comment]
I tested on standalone bbb and got the size info. But scalelite there is no info. I think it should be added to scalelite side too.
