### ISSUE TITLE
Whiteboard clean blank included in the menu plus without the need for a pdf

### ISSUE THREAD

**Issue by jorgelondo** [bigbluebutton/bigbluebutton#17812]
In the education part, the tool of having a blank whiteboard is very important. I know that there are blank pages in the default pdf, but it would be great to have a whiteboard without the need for a pdf.
It can be done with a new item in the menu +
![whiteboard-blanco](https://user-images.githubusercontent.com/672505/236270407-5818c0d7-2020-439c-9b93-7cf6200a4412.png)

**Comment by ffdixon** [comment]
Good suggestion, merging it into the previous suggestion.  In the future, check out the existing issues to see if someone has already made the same suggestion.  It's easier for us to manage the requests when they are consolidated.

Merged into https://github.com/bigbluebutton/bigbluebutton/issues/16766
