### ISSUE TITLE
getRecordings API  without recordID return empty

### ISSUE THREAD

**Issue by blueiceprj** [bigbluebutton/bigbluebutton#17815]
**Describe the bug**
If you use getRecordings API  without recordID (only meetingId),  it returns empty recording list. According to API documentation am I missing something or is this a bug?

<img width="681" alt="Ekran Resmi 2023-05-05 03 56 55" src="https://user-images.githubusercontent.com/1829975/236363370-395f323c-7033-418c-8138-424ea0d821fc.png">

<img width="840" alt="Ekran Resmi 2023-05-05 03 57 16" src="https://user-images.githubusercontent.com/1829975/236363415-67d2b653-b35e-459b-8254-c4c51d8e1cef.png">

**Expected behavior**
API has to return list of recordings

**Comment by blueiceprj** [comment]
I see. This internal meeting ID. It must be external.

**Comment by hostbbb** [comment]
FYI, 2.6 also add this as server setting.  it defaults to true so your set., but can be turned off as calling this on a server with 1000's of recording makes it inoperable in some cases.   Live sessions may be impacted in this case.

# when set to true, a single call of getRecordings with no specified meetingID will return a (potentially massive) response listing all recordings on the system
allowFetchAllRecordings=true
