### ISSUE TITLE
[2.6] some pptx file not successfully uploaded

### ISSUE THREAD

**Issue by hiroshisuga** [bigbluebutton/bigbluebutton#17824]
**Describe the bug**
Some pptx file cannot be uploaded. "Invalid format detected (extension=pptx, content type=application/octet-stream)" error is shown. Other pptx files have no problems. Until 2.5 there was no problem with this file.

**To Reproduce**
1. upload a pptx file below

[BBB.pptx](https://github.com/bigbluebutton/bigbluebutton/files/11411867/BBB.pptx)

**BBB version:**
Tested on test26 server.

**Comment by ffdixon** [comment]
Thanks @hiroshisuga.  We can reproduce the error here.  When I open BBB.pptx in PowerPoint and save it (no changes), it converts.

[BBB 1 - saved.pptx](https://github.com/bigbluebutton/bigbluebutton/files/11412087/BBB.1.-.saved.pptx)

What application generated BBB.pptx?

**Comment by hiroshisuga** [comment]
I think I created it by Libreoffice on Windows10 and saved it as pptx file. Until BBB2.5 it was usable.

**Comment by ffdixon** [comment]
In 2.6, we introduced using `file` to determine the mimetype of a document before passing it to LibreOffice and this might be failing.  Looking closer.

**Comment by ffdixon** [comment]
Noticing that when using `file`, it recognizes the original document as `Microsoft OOXML` document

```
root@droplet-9101:~# file BBB.pptx 
BBB.pptx: Microsoft OOXML
```

After opening the document and saving it again, it now recognizes it as `Microsoft PowerPoint 2007+`.

```
root@droplet-9101:~# file BBB-1.pptx 
BBB-1.pptx: Microsoft PowerPoint 2007+
```

I uploaded `BBB.pptx` to a test 2.6 server, converted the file `BBB.pptx` on the server using `convert.sh` (bypassing the `file` check), 

```
/usr/share/bbb-libreoffice-conversion/convert.sh BBB.pptx BBB-converted.pdf
```

Then downloaded generated PDF `BBB-converted.pdf` and tried uploading it to BigBlueButton.  The resulting PDF displayed correctly.

<img width="967" alt="image" src="https://user-images.githubusercontent.com/290351/236699586-00c06fc9-85c3-416d-b1b5-9250bc390ee4.png">

**Comment by spreeni151** [comment]
Thanks Fred for pointing to bug #17824. 
Unfortunately, I can't say if this is related. The attempt to test in settings.yml
```
- extension: .docx
         mime: application/zip 
```
didn't work.
Maybe the two docx files above will help you to find the error.
At the moment we are using only PDF or ODT formats. So far we haven't seen any conversion issues with these formats.

**Comment by antobinary** [comment]
Closing via https://github.com/bigbluebutton/bigbluebutton/pull/18030
