### ISSUE TITLE
BigBlueButton in a private network with self-assigned SSL not working

### ISSUE THREAD

**Issue by JohnPrice2** [bigbluebutton/bigbluebutton#17836]
Im trying to install BigBlueButton 2.6 in my companys private network with our own SSL certificates. 
The server is not going to accessed from outside (Not connected to the outside).

This were my steps

1. Created the directory "/local/certs/"
2. Generated my own SSL certs (4096 bits) in "/local/certs/"
3. Generated my "openssl dhparam" in "/local/certs/"
4. Installed the Certificate CA Root in the server
5. Run the script "wget -qO- https://ubuntu.bigbluebutton.org/bbb-install-2.6.sh | bash -s -- -v focal-260 -s "hostname" -e "email" -g -w -d"
6. Altered the file "/etc/nginx/sites-available/bigbluebutton"

This is the state of my files

**/etc/hosts/**
![image](https://user-images.githubusercontent.com/45044257/236855823-555bdec3-2d01-449a-adc6-0137f814f012.png)

**/etc/nginx/sites-available/bigbluebutton**
![image](https://user-images.githubusercontent.com/45044257/236855642-b0532227-881d-46c1-8cce-42e6317bad76.png)

**/var/log/nginx/error.log**
![image](https://user-images.githubusercontent.com/45044257/236856453-40747280-a30a-4608-bb92-fe67ea3456b1.png)

**/var/log/nginx/access.log**
![image](https://user-images.githubusercontent.com/45044257/236856697-df501540-3a51-4f65-8212-2237619fdca4.png)

When i run the command "curl -sS https://srvlbbb01.ad.airc.pt/bigbluebutton/api --verbose"
![Curl](https://user-images.githubusercontent.com/45044257/236862394-acb5bc44-1ae2-4af6-92c0-fccbec75e597.PNG)

In the browser appears the error "ERR_TOO_MANY_REDIRECTS"

I´m at a lost now... I need help pls.

**Comment by motsiw** [comment]
Have a look at this issue:
https://github.com/bigbluebutton/bigbluebutton/issues/17165

Greenlight needs to know your ca certificate, too.

**Comment by JohnPrice2** [comment]
> Have a look at this issue: #17165
> 
> Greenlight needs to know your ca certificate, too.

Nice! The Greenlight knows my CA certificate now!

But when i run "docker exec -it greenlight-v3 bundle exec rake configuration:check" this shows:
![image](https://github.com/bigbluebutton/bigbluebutton/assets/45044257/dc75a1ca-d4bd-49f2-b5dd-c4cabded19e7)

**Comment by motsiw** [comment]
Here's how it works for me. In `/local/certs/` there should be two *.pem files:
```
fullchain.pem
privkey.pem
```

`fullchaim.pem` should include your public key as well as the intermediate certificates (if any) and your ca's certificate. Every block shoud begin with
`-----BEGIN TRUSTED CERTIFICATE-----`
and end with
`-----END TRUSTED CERTIFICATE-----`
First block: Your crt.
Last block: Your ca's crt.

`privkey.pem` should contain your private key, starting with
`-----BEGIN RSA PRIVATE KEY-----`
and ending with
`-----END RSA PRIVATE KEY-----`

Additionally, your ca's cert (e. g. ca.crt) and your public crt (myserver.crt) should be copied to /usr/local/share/ca-certificates/ and afterwards execute on the console `update-ca-certificates`

Hope this helps a bit.

**Comment by JohnPrice2** [comment]
> 

Ok, i'm going to try that. I need to install BBB again.

Right now i have a cert.crt and cert.key in the "/local/certs/" and i'm assuming this doesn't work then...

**Comment by hostbbb** [comment]
/local/certs/fullchain.pem
/local/certs/privkey.pem 

make sure the  permissions are correct.

**Comment by JohnPrice2** [comment]
Boys, it works!! Thank you so much!
