### ISSUE TITLE
BBB 2.6.6: hidePresentationOnJoin doesn't work anymore

### ISSUE THREAD

**Issue by Ithanil** [bigbluebutton/bigbluebutton#17839]
**Describe the bug**
With BBB 2.6.6 the setting hidePresentationOnJoin (set via Scalelite DEFAULT_JOIN_PARAMS=userdata-bbb_hide_presentation_on_join=true) has no effect anymore. The presentation is not hidden after joining.

It did work as expected in 2.6.5.

**To Reproduce**
1. Join meeting
2. See presentation is not hidden.

**Expected behavior**
Presentation should be hidden after joining.

**BBB version:**
BigBlueButton Server 2.6.6 (1193)

**Comment by ffdixon** [comment]
Tried it on build 592 (just before official release) and this parameter worked.  

However, was able to reproduce the issue on build 594, the release build of 2.6.6.
