### ISSUE TITLE
Learning dashboard is available in breakout rooms

### ISSUE THREAD

**Issue by cvokable** [bigbluebutton/bigbluebutton#17840]
**Describe the bug**
When a breakout room is created, all joiners automatically become moderators. In addition, the learning dashboard is activated. This happens even if learn dashboard is disabled in the main meeting. This poses a major privacy issue as it allows participants to analyze each other. 

**To Reproduce**
1. Create a meeting with disabled learning dashboard
2. Join with one moderator and two guests
3. Create a breakout room and pass the two guests in the breakout room
4. Both of them can now open the learning dashboard of the breakout room

**Expected behavior**
If learning dashboard is disabled in main meeting it should also be disabled in breakout rooms. When learning dashboard is enabled in main meeting, i wnat to deciede if the participants should be able to see the dashboard in breakout room.

**Screenshots**

![Main meeting without learning dashboard](https://user-images.githubusercontent.com/123939747/237030506-6141cdc1-991b-4fae-993a-b22f81c256aa.png)
![Creating breakout room](https://user-images.githubusercontent.com/123939747/237030520-b4d3603c-a172-4486-90c3-4e73894213a4.png)
![Breakout room with learning dashboard](https://user-images.githubusercontent.com/123939747/237030516-4677c10c-f486-47f1-ad84-2a4fdef745e5.png)
![Learning dashboard from breakout room](https://user-images.githubusercontent.com/123939747/237030522-f64146ca-6d63-4428-9a0e-b71fca77cd34.png)

**BBB version:**
BigBlueButton Server 2.6.4 (1150)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 113

**Comment by ffdixon** [comment]
Good catch!  Your right in that it shouldn't be active.  We'll fix that in the next update.
