### ISSUE TITLE
Conference pin is suddenly too long

### ISSUE THREAD

**Issue by hermanntoast** [bigbluebutton/bigbluebutton#17858]
**Describe the bug**
I updated to BBB 2.6.6 yesterday. Since then, dialing in by telephone via Freeswitch no longer works. According to the documentation, Freeswitch expects a five-digit conference pin. However, the pin that is generated or displayed has nine digits. If you enter this via dtmf, the call is either ended immediately or it is reported that the pin is invalid.

I can't find the pin settings. Why is this suddenly nine digits and no longer five digits?

**To Reproduce**
1. Use a BBB 2.6.6 with configured freeswitch
2. Try to connect via phone

**Expected behavior**
Expected is a five digits conference pin

**Actual behavior**
Currently, we have a nine digits conference pin

**Screenshots**
![grafik](https://github.com/bigbluebutton/bigbluebutton/assets/21087610/2f1f43ef-6926-4c10-99c0-e41522ba8162)

**Comment by ffdixon** [comment]
The docs for configuring BigBlueButton for dial-in numbers are here

  https://docs.bigbluebutton.org/administration/customize/#add-a-phone-number-to-the-conference-bridge

and for the parameters for `play_and_get_digits`, see

  https://developer.signalwire.com/freeswitch/FreeSWITCH-Explained/Modules/mod-dptools/6586933/
