### ISSUE TITLE
[2.7] BBB interface never loads beyond dark-blue screen in Android WebView with BBB 2.5, 2.6 and 2.7

### ISSUE THREAD

**Issue by renatus** [bigbluebutton/bigbluebutton#17896]
Hello!

BBB interface never loads beyond dark-blue screen in Android WebView, tree white dots will never appear. Instead, this error message will appear in Android Studio logcat:

[INFO:CONSOLE(374)] "Uncaught TypeError: Cannot read properties of null (reading 'constructor')", source: https://MYSITE.com/html5client/7717e1449d9a9fea60fa418d8ecaa5fd72c67edd.js?meteor_js_resource=true (374) 

- BBB works perfectly fine on the very same phone in Chrome browser (used by Android WebView as well, when installed)
![photo_2023-05-15_15-19-48](https://github.com/bigbluebutton/bigbluebutton/assets/5566361/53d837cd-2836-44ec-b38f-bad48f605398)

- Bug only affects BBB 2.5.x and 2.6.x branches, BBB 2.3.x and 2.4.x work flawlessly in Android Webview

**Expected behavior**
BBB works in Android WebView, as it was with BBB 2.3.x and 2.4.x

**Actual behavior**
BBB interface never loads beyond dark-blue screen in Android WebView, if we're working with BBB 2.5.x and 2.6.x
![photo_2023-05-15_15-19-39](https://github.com/bigbluebutton/bigbluebutton/assets/5566361/b6a94f59-eeb5-4d55-a17a-baa788b6d1a8)

**BBB version:**
Tested couple 2.3, 2.4, 2.5, 2.6 installations, including fresh ones. For sample:
BigBlueButton Server 2.6.6 (1178)

**Smartphone (please complete the following information):**
Used couple of devices to test, Android 9, 10, 12. For sample:
 - Device: ZTE Blade A3 2020
 - OS: Android 9
 - Browser: Chrome
 - Version: 113.0.5672.76

**Comment by FreeScholar** [comment]
Same issue on my Android using FireFox or Brave browser
Android 11
Lineage OS version 18

**Comment by AllwinJohnson** [comment]
We also recently encountered this issue. 
As @renatus mentioned, the WebView with BBB was working fine up to versions 2.3.x and 2.4.x. 
However, **when we started using version 2.6.x, we encountered a blank screen problem**. 
I tried various user agents as a potential fix for this issue, but some resulted in an 'older version warning' on the website.
![image](https://github.com/bigbluebutton/bigbluebutton/assets/46625967/e81b1203-c70d-4039-879a-605a98e6ef8b)
I even attempted to use the user agent from the API header, which is used to fetch sessions from the BBB server in a desktop browser, but unfortunately, it didn't work in this case. 

Log
```
chromium                   I  [INFO:CONSOLE(36)] "Starting Moodle session timeout warning.", source: https://xxx.com/lib/requirejs.php/1666016916/core/first.js (36)
chromium                   W  [WARNING:display_webview.cc(32)] WebView overlays are enabled!
chromium                   I  [INFO:CONSOLE(434)] "Uncaught TypeError: Cannot read properties of null (reading 'constructor')", source: https://xxx.com/html5client/db6fd377f945cfea327efc8e2f9ea830a9a55656.js?meteor_js_resource=true (434)
chromium                   I  [INFO:CONSOLE(0)] "The resource https://xxx.com/html5client/files/source-code-pro-latin-400-normal.woff2 was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.", source: https://xxx.com/html5client/join?sessionToken=7h4shbgqno2ttb89 (0)
```

Device
```
  Device Model: Lenovo TB-8505X
  Android Version: 10
  Build Version: 29
  Device Architecture: arm64-v8a
```
  
So, **are there any possible solutions for this problem**, or does BBB no longer support Android WebView?

**Comment by renatus** [comment]
Tested WebView against BBB 2.7, this issue is still with us, nothing changed.

**Comment by antobinary** [comment]
>Tested WebView against BBB 2.7, this issue is still with us, nothing changed.

Have you checked BBB 3.0 - test30.bigbluebutton.org ?
