### ISSUE TITLE
401 on etherpad if connected to a room for a long time - even though still an active session

### ISSUE THREAD

**Issue by dmtrhfr** [bigbluebutton/bigbluebutton#17895]
**Describe the bug**
When you are in a session for a long time (for example over night) you still have a valid token for the session, but you can't open etherpad as you see a 401 error. 

**To Reproduce**
1. Create and join a room
2. leave the session open for a long time
3. open etherpad
4. See a 401

**Expected behavior**
I expect to that the sessions on all parts of the bbb-html5 client are the same durationn.

**Actual behavior**
Sessions on etherpad run out even though you still have a valid session in the html5 client.

**Screenshots**

**BBB version:**
BigBlueButton continually evolves. Providing the version/build helps us to pinpoint when an issue was introduced.
Example:
$ sudo bbb-conf --check | grep BigBlueButton
BigBlueButton Server 2.6.6

For how long is the session valid for etherpad? As it is a concern that the pad gets lost.

**Comment by Ithanil** [comment]
I think this "long time" is 6 hours and is configured in the following block within `/usr/local/bigbluebutton/bbb-pads/config/settings.json`
```
    "session": {
      "ttl": 21600000
    },
```
which equates to 6 hours if the number is in milliseconds. It should be easy to override the value by using the override file `/etc/bigbluebutton/bbb-pads.json` . I tried to figure out how to change the default number within BBB to 24 hours, but ended up at https://github.com/mconf/ep_pad_ttl as the source for the number. So I guess the default 6 hours is a deliberate choice by the devs and not sure if they want to change it.
