### ISSUE TITLE
[mobile-2.6.7] - Bad drop areas dispositions

### ISSUE THREAD

**Issue by antonbsa** [bigbluebutton/bigbluebutton#17939]
**Describe the bug** - _Tested on an iPhone 11 + Safari and Chrome (iOS 16.4.1)_
On a mobile device, the user can set the custom layout. When using landscape orientation and repositioning the camera's position, it's difficult to set into the sides of the presentation. I'm not sure what supposed to be the expected behavior: either increasing size drop areas or disabling custom layout on mobile

**Screenshot**

<img src="https://github.com/bigbluebutton/bigbluebutton/assets/56703993/b581df5d-dd7b-4e9d-b32d-8dfdac8cd751" width="600">

**Comment by antonbsa** [comment]
I'm able to reproduce the same behavior on 2.7 and 3.0

**Comment by antobinary** [comment]
Closed via #21324
