### ISSUE TITLE
Shared Notes and CC not loading and causing error 409

### ISSUE THREAD

**Issue by eialanjones** [bigbluebutton/bigbluebutton#17956]
**Describe the bug**
Shared Notes and CC not loading and causing error 409

**To Reproduce**
On a machine in the cloud, at Hetzner, I followed the documentation to install the BBB, so far so good. Then I cloned the repository. Inside bigbluebutton-html5, I ran npm install and installed Meteor.js and to test if prod deploy was working I ran:
''''
meteor build --server-only /home/bigbluebutton/dev/bigbluebutton/bigbluebutton-html5/meteorbundle
sudo tar -xzvf /home/bigbluebutton/dev/bigbluebutton/bigbluebutton-html5/meteorbundle/*.tar.gz -C /usr/share/meteor
'''

**Expected behavior**
Expect shared notes and cc working

**Actual behavior**
Causing error 409 when you start using

**Screenshots**
![image](https://github.com/bigbluebutton/bigbluebutton/assets/33515543/dee8adaf-3be8-4738-886a-25ef99b2b560)
![image](https://github.com/bigbluebutton/bigbluebutton/assets/33515543/ee7090fb-f8d7-4e43-89cc-a4a70696f06b)

**BBB version:**
Server 2.6.7 (1206)

**Desktop (please complete the following information):**
 - OS: Linux
 - Chrome

**Comment by danielpetri1** [comment]
Hi @eialanjones,

it looks like `pads.url` is not set correctly in `settings.yml`:

```yml
pads:
    url: https://<your-server-url>/pad
    cookie:
    path: /
    sameSite: None
    secure: true
```

**Comment by eialanjones** [comment]
> Hi @eialanjones,
> 
> it looks like `pads.url` is not set correctly in `settings.yml`:
> 
> ```yaml
> pads:
>     url: https://<your-server-url>/pad
>     cookie:
>     path: /
>     sameSite: None
>     secure: true
> ```

I changed to the right url and everything worked. Thank you!
