### ISSUE TITLE
HTML5 plugin system

### ISSUE THREAD

**Issue by TiagoJacobs** [bigbluebutton/bigbluebutton#17978]
### Motivation

A core objective is to democratize the development process within BigBlueButton, enabling developers to significantly extend the platform's functionalities without the need of constructing a customized build.

By introducing a sophisticated plugin architecture, we strive to mitigate the complexities often associated with custom development and deployment. This transformative approach allows developers to focus on their creative and innovative potential, thereby enhancing BigBlueButton's features and overall user experience.

This innovative framework epitomizes our commitment to cultivating a more inclusive, adaptive, and seamless development environment within BigBlueButton, ultimately fostering a vibrant ecosystem of developers and collaborators.

### Use case

To elucidate the utilization of this new plugin system, here's a succinct walkthrough:

Customers will have the autonomy to download the desired plugin directly from the plugin vendor's website/repository/etc. Subsequent to the file acquisition, they can host the downloaded plugin on their preferred web server, or even within the BigBlueButton `bigbluebutton-default` folder. The final step in this straightforward integration process involves adding the new plugin to the existing configuration file.

### Technical description

1. The plugin system is introduced within the `settings.yml` file by defining a new `plugin` key. Each plugin configuration is represented as an object in an array under the `plugins` key. This object includes details like the plugin's name and its URL, which points to a JavaScript (`.js`) file.

2. These JavaScript files are essentially UMD bundled React applications or micro-frontends. They are dynamically loaded into the BigBlueButton (BBB) system via programmatically created `<script>` tags.

3. To instantiate these micro-frontends, BBB programmatically generates `div` elements within a predefined container. These `div` elements are assigned unique identifiers (`element-id` and `plugin-name`), which are then passed to the React scripts.

4. The plugin accesses these identifiers using the `document.currentScript` object and passes them to the `ReactDOM.createRoot` function.

5. Upon successful mounting, the plugin registers itself in an object named `window.bbb_plugins[pluginName]`. This object will house all the plugin hooks that the corresponding plugin implements.

6. From the BBB side, every feature that supports plugins will scan all loaded plugins to determine whether they possess the requisite plugin hook function. If a plugin has the necessary hook, BBB will invoke it.

7. In the example provided (of adding a toolbar button), the toolbar mounting process (within the BBB code) will iteratively check each plugin. If a plugin contains the `getWhiteboardToolbarButtons` hook, BBB will retrieve the buttons provided by this hook and subsequently integrate them into the toolbar.

This proposed process seems to ensure a smooth integration and interaction between BBB and the plugins, while also maintaining a high degree of modularity and extensibility for the platform.

### Sample snippets 

1.

```yml
plugins:
    - name: plugin01
      url: https://bbb-plugins.bbbvm.imdt.com.br/plugins/Plugin01.js
    - name: plugin02
      url: https://bbb-plugins.bbbvm.imdt.com.br/plugins/Plugin02.js
```

5.

```js
Plugin01 ( ({pluginName})=> {
    window.bbb_plugins[pluginName] = {
        getWhiteboardToolbarButtons: () => [
            {
                label: "Button 1 from plugin",
                onClick: () => {
                    alert("Clicked on the button");
                }
            },
            {
                label: "Button 2 from plugin",
                onClick: () => {
                    alert("Clicked on the button");
                }
            }
        ]
    }
});
```

7.

```js
Object.keys(window.bbb_plugins).forEach((pluginName) => {
  const plugin = window.bbb_plugins[pluginName];

  if (plugin.getWhiteboardToolbarButtons) {
    const buttons = plugin.getWhiteboardToolbarButtons();
    // Add provided buttons to state (and use on render)
  }
});
```

**Comment by TiagoJacobs** [comment]
In order to make this architecture reactive, we defined a slightly different strategy, explained in this youtube video: https://www.youtube.com/watch?v=8SPsrmOfV_Y

**Comment by antobinary** [comment]
The plugin system was introduced in BigBlueButton 3.0
