### ISSUE TITLE
Not able to share webcam while trying to join meeting using Mozilla Firefox 

### ISSUE THREAD

**Issue by anandchristudas** [bigbluebutton/bigbluebutton#17976]
**Describe the bug**
Not able to share the webcam while trying to join the meeting using the Mozilla Firefox browser. Webcam is working fine in all other browsers.  

**To Reproduce**
1. Go to your meeting link using Mozilla browser. 
2. Click on the share webcam option 
4. Wait for the Error 1020 to appear.

**Expected behavior**
While joining with any browser we are supported to share the webcam

**Actual behavior**
While joining with Mozilla browser not able to share the webcam

**ScreenRecording**

https://github.com/bigbluebutton/bigbluebutton/assets/95290346/e257d861-3adc-4f03-8c6c-5d7d6cd6a01a

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Mozilla 113.0.2
 - BBB Version [2.6.7]

**Comment by anandchristudas** [comment]
Thanks @prlanzarin it worked :)

But what do you mean by beware of yaml hierarchy and identation when changing. It you mean this change will affect some other functions of BBB.

**Comment by anandchristudas** [comment]
And can you please tell me how to check if coturn/TURN setup is working? Thanks a lot.

**Comment by mabras** [comment]
> And can you please tell me how to check if coturn/TURN setup is working? Thanks a lot.

https://docs.bigbluebutton.org/administration/turn-server#test-your-turn-server

**Comment by mabras** [comment]
> Thanks @prlanzarin it worked :)
> 
> But what do you mean by beware of yaml hierarchy and identation when changing. Did you mean this change will affect some other functions of BBB.

No. This just to make yaml file valid.

**Comment by anandchristudas** [comment]
Thanks a lot, @prlanzarin @mabras coturn/TURN setup is working fine.

**Comment by anandchristudas** [comment]
@mabras @prlanzarin  the conturn/TURN is active and ruining but still when I turn on media.peerconnection.ice.relay_only to true in Firefox setup the same error is coming so I think the TURN server seems to be not working properly.

**Comment by anandchristudas** [comment]
We were testing in other browsers and found out that we are not able to connect to either audio or video using Opera Browser. Seems like the TURN server that comes built-in with BBB 2.6.7 isn't configured correctly. The TURN server is running but not getting connected when needed.

**Comment by anandchristudas** [comment]
> > We were testing in other browsers and found out that we are not able to connect to either audio or video using Opera Browser. Seems like the TURN server that comes built-in with BBB 2.6.7 isn't configured correctly. The TURN server is running but not getting connected when needed.
> 
> Did you use the bbb install script? What was the command?

We used the below script

wget -qO- https://ubuntu.bigbluebutton.org/bbb-install-2.6.sh | bash -s -- -v focal-260 -s bbb.example.com -e example@gmail.com -g -w

**Comment by anandchristudas** [comment]
@mabras @prlanzarin After many trials and checking different settings we found out what was the error. The subdomain that we were using for BBB was behind Cloudflare and the IP was proxied which is why the TURN server was not getting connected.
