### ISSUE TITLE
Incorrect size and aspect ratio of presentation shown to viewers and recorded

### ISSUE THREAD

**Issue by vasylOstrovskyi** [bigbluebutton/bigbluebutton#17982]
**Describe the bug**
In some cases, presentation is shown to viewers and recorded in the size and aspect ratio different from the one of the presenter.

**To Reproduce**
Steps to reproduce the behavior (see video):
1. Upload a presentation in the portrait format. Zoom it to full width.
2. Go back to the default presentation
3. The viewers see only a part on the slide (and only that part is recorded), but the presenter sees it at full size.
4. Switch again to the uploaded slide.
5. The viewers see it in the full page format, while to the presenter it is shown as zoomed to full width.

[video.webm](https://github.com/bigbluebutton/bigbluebutton/assets/33595182/cd0657d4-db76-4093-8eac-5cdb43be84f6)
**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Browser Chrome

**Additional context**
The test and video are made on demo.bigbluebutton.org. This wrong behaviour is very often but not 100% reproducible.

Regards,
 Vasyl

**Comment by antobinary** [comment]
Thank you for reporting this!
P.S. Great to see you are using an academic paper you co-authored as a sample document. Not many can match that!

**Comment by vasylOstrovskyi** [comment]
More info: using pan tool (even for slides which are shown in full) as presenter restores correct aspect ratio for viewers. A bit annoying, but still a way to work.
Regards,
 Vasyl

**Comment by vasylOstrovskyi** [comment]
@KDSBrowne Just upgraded to 2.7.0-rc.1 with https://github.com/bigbluebutton/bigbluebutton/pull/18452 included. Seems that the issue (at least its essential part) is still there. In fact, it is not related to Presentation change, one can observe it with the default presentation, too, by making browser window very wide and short.
1. open two windows, for the presenter and for the viewer. fit to width is false for both by default (correct)
2. turn on fit fo width as presenter. the viewer sees it with fit to width true (correct)
3. go to page 2, the presenter sees it with fit to width tue (correct), but the viewer sees if wit fit to width false (wrong)
4. pan the slide (or go to page 1, or switch rit to width to false and back to true), the viewer sees the page wit fit to width true (corrected)
5. similarly, on page  2, set fit to width false, the viewer sees the slide with fit to width false (correct)
6. go back to page 1, the viewer sees it with fit to width true (wrong)

Regards,
 Vasyl
8.
