### ISSUE TITLE
Popping open new windows (especially without warning) undesirable for many users

### ISSUE THREAD

**Issue by brandondrew** [bigbluebutton/bigbluebutton#17991]
The main documentation page opens a new window when you click the "buttons" for the 
- Quickstart Guide
- Teaching Experience

This serves no obvious purpose, and many users consider it impolite.  I'm told that it is especially unpleasant for users of screen readers.  

Why would anyone object to this? The controller of the site—whoever makes the final decisions whether that be developer, designer, manager, or CEO—has intruded on the user's normal workflow and changed how links work and prevented the user from deciding how to control their organization of web pages and tabs and windows.  Instead of letting the user (who already has the option to open a link in a new tab or window very easily) this choice is surreptitiously taken away.  To regain this control, the user must (1) close the new window, (2) force the link to open in a new tab, (3) close the tab that contained the link, and (4) switch to the new tab.  All of this breaks the user's train of thought just to restore the results of what they expected when clicking a link.  Instead of thinking about the content of the page, they're thinking about the distraction of fixing their tab and window arrangement.

Fortunately none of the other "buttons" on the page do that—they all keep the new page in the current window and tab.  And fortunately all the other links which open a new page give a warning through an icon.  

Please consider letting your users maintain control over their own browsing habits and information organization and if at all possible _ideally_ allow the links to open normally on the same page.  If there genuinely is some constraint preventing that (and I can't imagine what that might be), please _at least_ show an icon so that users know what to expect.

Thanks for your attention to user experience (and of course for a fabulous product as well!)

**Comment by ffdixon** [comment]
Agreed.  These links to Quickstart Guide and Teaching Experience should open in a new tab, like clicking on GitHub

<img width="179" alt="image" src="https://github.com/bigbluebutton/bigbluebutton/assets/290351/8a09a041-9929-4ec9-a24e-bb68e5535997">
