### ISSUE TITLE
No cursor in presentation recording

### ISSUE THREAD

**Issue by vasylOstrovskyi** [bigbluebutton/bigbluebutton#17997]
**Describe the bug**
During playback of presentation format recordings, no cursor movements are visible.

**To Reproduce**
1. Start a meeting, turn on recording
2. Move cursor over the presentation area
3. Stop recording. Stop session. Wait for recording to appear.
4. Start playback. No cursor movement is visible

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
  - Browser Chrome

BBB version 2.6.8

**Additional context**
1. File raw/.../events.xml contains WhiteboardCursorMoveEvent records
2. Video format, if enabled, displays cursor movements as expected
3. File published/presentation/.../cursor.xml does not contain non-trivial records

Regards,
 Vasyl

**Comment by antobinary** [comment]
Hi, thank you for reporting this @vasylOstrovskyi !

I can confirm this on test26 (2.6.8)
