### ISSUE TITLE
Whiteboard draws not saved and show in recording playback on BBB v2.6.8

### ISSUE THREAD

**Issue by more-zamani** [bigbluebutton/bigbluebutton#18037]
Hi
I have BBB v2.6.8 and I found the draws on whiteboard don't save and show on offline recording playback. Other objects like webcam and whiteboard is OK.

Please check this bug and give me a solution. Thanks.

**Comment by vasylOstrovskyi** [comment]
Had the same with 2.6.7. Enabling video format for publishing noticed that in video format everything is OK. After reinstalling recording-playback packages and some cleanup  (do not remember all the details) and rebuilding recordings, annotations appeared in presentation recordings, too.
Regards,
 Vasyl.

**Comment by antobinary** [comment]
Hi @more-zamani 

Could you please say which version numbers you see for the following packages?

```
root@test26:~# dpkg -l | grep bbb-r
ii  bbb-record-core                      1:2.6-28                          amd64        BigBlueButton record and playback
root@test26:~# dpkg -l | grep bbb-play
ii  bbb-playback                         1:2.6-15                          amd64        BigBlueButton playback
ii  bbb-playback-presentation            1:2.6-13                          amd64        BigBluebutton playback of presentation
ii  bbb-playback-video                   1:2.6-8                           amd64        BigBluebutton playback of presentation
root@test26:~# dpkg -l | grep bbb-pre
ii  bbb-presentation-video               4.0.2                             all          Render BigBlueButton recording events.xml to a video

```

**Comment by sbt1021** [comment]
Hi @more-zamani,

I had the same issue but, it is not related to BBB 2.6.8.
After I upgrade scalelite, recording works right.
If you use scalelite too, please upgrade it.

**Comment by antobinary** [comment]
Based on what others wrote, I think you're hitting https://github.com/blindsidenetworks/scalelite/issues/895
If you're not using Scalelite and the issue persists with the newly released BBB 2.6.9 please reopen/comment with more info.

**Comment by ffdixon** [comment]
We just did a new install of BigBlueButton 2.6.11 (standalone server, no ScaleLite) and tested the recordings for both presentation and video format.  The whiteboard marks were present in both recording formats.

Can you try upgrading to [2.6.11](https://groups.google.com/g/bigbluebutton-dev/c/7vVJia2SXJY/m/SYA08LaXAQAJ) and let us know if the whiteboard marks now appear.

**Comment by Vladbooka** [comment]
> We just did a new install of BigBlueButton 2.6.11 (standalone server, no ScaleLite) and tested the recordings for both presentation and video format. The whiteboard marks were present in both recording formats.
> 
> Can you try upgrading to [2.6.11](https://groups.google.com/g/bigbluebutton-dev/c/7vVJia2SXJY/m/SYA08LaXAQAJ) and let us know if the whiteboard marks now appear.

yes, standalone server BBB works fine. annotations do not work with ScaleLite. I posted a new issue on ScaleLite https://github.com/blindsidenetworks/scalelite/issues/992 ,  bug in ScaleLite
