### ISSUE TITLE
[2.6.8] Viewer gets blank presentation after minimize/restore

### ISSUE THREAD

**Issue by einhirn** [bigbluebutton/bigbluebutton#18039]
**Describe the bug**
When a viewer minimizes and restores the presentation, a blank page is displayed instead of the current slide.

**To Reproduce**

1. Start a meeting with a moderator/presenter and a viewer.
2. The viewer minimizes the presentation and restores it (even the default.pdf)
3. The presentation area is blank

**Expected behavior**
When restoring the presentation area, the current slide should be displayed.

**Actual behavior**
The presentation area is blank until the presenter switches to the next slide.

**Screenshots**
![Screenshot 2023-05-26 160956](https://github.com/bigbluebutton/bigbluebutton/assets/189249/e2321b21-346a-428c-bc80-ca8c9255f284)

**BBB version:**
BigBlueButton Version: 2.6.8
Clientversion: 623

**Desktop:**
OS: Windows 10
Browser: Any

**Additional context**
The problem does not occur for the presenter. 
We use hidePresentationOnJoin = true. But I don't think that makes any difference.

**Comment by antobinary** [comment]
Thank you for reporting! I am able to reproduce. It may be related to https://github.com/bigbluebutton/bigbluebutton/pull/17983
