### ISSUE TITLE
[2.2.36] Old recordings without audio

### ISSUE THREAD

**Issue by bigemme** [bigbluebutton/bigbluebutton#18036]
**Describe the bug**
Premise: at this moment everything works (except the old recordings which are without audio).

I've noticed that some of the older recordings published don't have audio.
I checked and the audio files are there.
The problem only occurs on recordings published BEFORE applying this fix manually: https://github.com/bigbluebutton/bigbluebutton/pull/10238

I tried to rebuild the recordings, but the problem persists (bbb-record --rebuild [internal_id]).

**Expected behavior**
Recording viewed on moodle with audio

**Actual behavior**
Recording viewed on moodle without audio

**Additional context**
BigBlueButton Server 2.2.36 (2416)
BigBlueButtonBN moodle plugin 2.4.7

**Comment by antobinary** [comment]
Hi @bigemme 

> BigBlueButton Server 2.2.36 (2416)

You'd really want to upgrade your BBB version, 2.2.x has been unmaintained, including no security patches for many months. BBB 2.6.x is the version we recommend now. 2.5 is still receiving security patches. Even if there is some bug on 2.2.36, there won't be a fix for it at this point. Please upgrade.

If perhaps you meant that your BBB server is up to date but old recordings from back when you were on 2.2.36 are causing you issues, please say so.

**Comment by bigemme** [comment]
Hi @antobinary,
I don't need to update bbb.
I need to figure out how to fix some recordings that are published without audio (bbb-record --rebuild - the audio file is there).

Right now everything works perfectly, the problem is only those recordings.
I don't think an update will solve the problem (it doesn't currently appear on new recordings).

Thanks.
