### ISSUE TITLE
Eliminate the second sidebar (chat), and make a tab menu in the first sidebar including users, chat, notes

### ISSUE THREAD

**Issue by jorgelondo** [bigbluebutton/bigbluebutton#18048]
Hello, everyone, I propose, Eliminate the second sidebar (chat), and make a tab menu in the first sidebar including users, chat, notes and you can even put another item for cameras. This with the purpose of optimizing the width of the presentation.

Solution:

![redesign-bbb-3](https://github.com/bigbluebutton/bigbluebutton/assets/672505/01e4067b-9685-48cc-bda4-7a8ae4dc8076)
![redesign-bbb-2](https://github.com/bigbluebutton/bigbluebutton/assets/672505/a5ff579a-2e52-483e-91a7-1e2ea1ba70b9)
![redesign-bbb-1](https://github.com/bigbluebutton/bigbluebutton/assets/672505/7070191e-6f01-4b85-a464-ed78e694a789)

thanks

**Comment by ffdixon** [comment]
Thanks for the feedback.  You can always hide the chat and turn on notifications for alerts.

<img width="678" alt="image" src="https://github.com/bigbluebutton/bigbluebutton/assets/290351/7712ef71-bcc0-4151-b946-acab29ce95b3">

There is more design work ahead for BigBlueButton.
