### ISSUE TITLE
[2.6.8] Pinning the shared notes should automatically restore the presentations area.

### ISSUE THREAD

**Issue by einhirn** [bigbluebutton/bigbluebutton#18040]
**Describe the bug**
When a viewer has minimized the presentation and the presenter pins the shared notes, the notes are not shown to this viewer. If hidePresentationOnJoin = true the pinned shared notes remain hidden for later joining viewers.

**To Reproduce**

1. Set hidePresentationOnJoin = true
2. Start a meeting with a moderator/presenter and a viewer A.
3. The presenter opens the shared notes and pins it to the whiteboard. 
4. The presentation areas is not restored automatically. The shared notes are hidden to viewer A.
5. A viewer B joins the meeting.
6. The shared notes are hidden to viewer B.

**Expected behavior**
The presentation area should be restored when the shared notes are pinned to the whiteboard.

**Actual behavior**
The presentation area remains minimized.

**BBB version:**
BigBlueButton Version: 2.6.8
Clientversion: 623

**Desktop:**
OS: Windows 10
Browser: Any

**Additional context**
In my opinion, the presentation area should behave the same way when pinning shared notes as it does when starting screen sharing or playing external videos.

**Comment by einhirn** [comment]
Can I please request a re-open of this issue? We could reproduce it in 2.6.10.

**Comment by antobinary** [comment]
Hi @einhirn 

Are you able to reproduce this consistently? With the same steps? Anything odd (errors) in the browser console?
