### ISSUE TITLE
Whiteboard tools are working only on a small area of the presentation

### ISSUE THREAD

**Issue by Ashes02** [bigbluebutton/bigbluebutton#18066]
**Describe the bug**
All whiteboard tools works only on small area of the entire whiteboard in Google Chrome browser. Problem presist with default presentation and with uploaded one. It started with Chrome latest update and it apears on every PC of my team with updated chrome browser. Issue is not found on Edge, Opera and Mozilla.

**Actual behavior**
moving the mouse otside the marked area of the screenshoot it look like the whiteboard tools are desactivated and for example the hand changes to the usual mouse cursor.

**Screenshots**
![image](https://github.com/bigbluebutton/bigbluebutton/assets/135272311/f0b22d73-cc8b-411e-aa78-5ebba4cbcbd1)

**BBB version:**
BigBlueButton Server 2.3.10 (2419)

**Desktop :**
 - OS: Windows 10
 - Browser Chrome
 - Version 114.0.5735.90 (Official Build) (64-bit)

**Comment by antobinary** [comment]
@hiroshisuga thank you for your patches! We went ahead with #18084 after some testing ( @ramonlsouza + @KDSBrowne )

@Ashes02 note that we no longer maintain BBB 2.4.x as of the moment 2.6.0 was released (see https://github.com/bigbluebutton/bigbluebutton/security/policy ), so there will be no patch or release for BBB 2.4.

BigBlueButton 2.5.18 will be released with this patch within a couple of days.
Thank you all!

**Comment by lfzawacki** [comment]
The merged PR did not solve the problem fully on Microsoft Edge. The second one, however, does make it work again on Chrome and Edge as well https://github.com/bigbluebutton/bigbluebutton/pull/18085

**Comment by fledge-tuition** [comment]
Another note to say that this issue is still affecting the latest version of Edge:

Microsoft Edge
Version 114.0.1823.51 (Official build) (64-bit)
Microsoft Edge is up to date.

**Comment by hiroshisuga** [comment]
Edge is developed based on Chromium project and the patch only detects Chrome browser. As a workaround, you could either include Edge browser in #18084, or take #18085.
