### ISSUE TITLE
Get stuck in three dots intro loading page in some situations

### ISSUE THREAD

**Issue by cod3r0k** [bigbluebutton/bigbluebutton#18061]
**Describe the bug**
Some users when entering the BBB 2.6.1 confront the 3 dots intro page of BBB rooms. I read previous issues which discussed this in https://github.com/bigbluebutton/bigbluebutton/issues/10957 and others and didn't get a main point and problem. I just want to notify the community that this problem is not resolved yet in some situations. I think we must improve this page with some configurations or some notes for visitors that don't be stuck and do anything to resolve their entrance issue.

![image](https://github.com/bigbluebutton/bigbluebutton/assets/36899025/6e5d784d-fc14-4a81-b0f3-c23fa4498a99)

I think we can change and fix the timeout console note with some notifications or alternative notifications for the audience to check another browser or change internet settings or notify the admin of BBB to resolve and check that issues. Also, I hope that we can find the main issue and resolve it ASAP

**To Reproduce**
1. Log in to the BBB room
2. Get stuck in 3 dots intro loading page

**Comment by cod3r0k** [comment]
Also, another important note is that when they try more and more, at the end they successfully can enter the room (by refreshing or by trying again and again).

As we can see in the issue image, some files are not loaded successfully (404 not found error) and it might have occurred because it was generated automatically by BBB. Maybe it is related to some core issues which not loaded or generated, and so on.

**Comment by ffdixon** [comment]
Can you help us determine whether the issue is in BigBlueButton itself or on your server.  

Are you able to reproduce the issue reliability on our server.  From the same client/computer, following the same steps, are you able to reproduce the issue on https://test26.bigbluebutton.org/?

**Comment by cod3r0k** [comment]
Hi @ffdixon

I check it again and I found that lazy loading might be a good solution. 
As I track the issue on the performance tab of Google Chrome, I found that some requests are getting stuck in the `pending` status.

E.g. pending requests are:
- https://test26.bigbluebutton.org/html5client/sockjs/info?t=1685708330935
- https://test26.bigbluebutton.org/html5client/locale?locale=en-US&init=true
- https://test26.bigbluebutton.org/html5client/locales/en.json?v=632

E.g. canceled requests:
- https://test26.bigbluebutton.org/html5client/sockjs/info?t=1685708330935

![image](https://github.com/bigbluebutton/bigbluebutton/assets/36899025/fc2dabdd-3165-4736-b9b2-2b1701136df9)

When I refresh again and again:
![image](https://github.com/bigbluebutton/bigbluebutton/assets/36899025/abe019f4-74df-41ee-8f18-2855d9120b2e)

After refreshing multiple times, it can be login to the room

**Comment by ffdixon** [comment]
Hmm ... can you share more about your computer, browser, and network speed (upload/download), and geographic location. 

We're not seeing this on our end, but if we can reproduce what you are seeing, we can dig deeper.

**Comment by mabras** [comment]
Using CDN could solve this kind of problems. Last time I have checked, BBB CDN feature is broken.

**Comment by FreeScholar** [comment]
> Hmm ... can you share more about your computer, browser, and network speed (upload/download), and geographic location. 
> 
> We're not seeing this on our end, but if we can reproduce what you are seeing, we can dig deeper.

I have this same issue intermittently.
1. I found that if I try to enter on a tab that is open and has the room entry on it that has been left open for some time ( page was generated when I clicked Leave the Room a while ago ) If I refresh/reload the stale room entry page I can get past the 3 dots spinning and enter the room (a few times it made me refresh 2-3x)
2. Sometimes this happens on a freshly opened tab.
3. GNU/Linux  
     . Ubuntu 22.04  
      - Browser: Brave (have not experienced in FireFox or Chrome as I rarely use them - will give a try)
      - speed Download = 269mbps Upload = 29mbps
      - Boston
