### ISSUE TITLE
Sort rooms in personal overview

### ISSUE THREAD

**Issue by RMaxiMal** [bigbluebutton/bigbluebutton#18060]
**Is your feature request related to a problem? Please describe.**
I've got many rooms, but they are likely unsorted in personal room overview.

**Describe the solution you'd like**
I want to sort them alphabetically and/or manually. But my "home room" should be always top left.

optional: Shared rooms should be listed separate.

**Additional context**
I can do a mockup, if you like.

**Comment by FreeScholar** [comment]
Sorting room lists would be helpful, but I believe it is a GreenLight issue.

I think alphabetical and perhaps "category" based listings using tags would rock - I can do this in my Wordpress BBB site using the Wordpress functionality and plugins, so again I think this is a post for the GreenLight  devs over here: 
https://groups.google.com/g/bigbluebutton-dev
