### ISSUE TITLE
Multi user whiteboard needs to be turned-on on every slide

### ISSUE THREAD

**Issue by anandchristudas** [bigbluebutton/bigbluebutton#18083]
**Describe the bug**
When you turn on the multi-user whiteboard it only gets turned on for that particular slide and the teacher needs to turn on the multi-user for every slide which sometimes is creating confusion 

**To Reproduce**
1. Go to a meeting 
2. Click on a multi-user whiteboard 
3. Now go to the next slide you will have to turn on the multi-user whiteboard again on every slide

**Expected behavior**
When the multi-user whiteboard is turned on it should on for all the slides 

**Actual behavior**
Here we have to manually switch it on for every slide

**Screenrecodring**

https://github.com/bigbluebutton/bigbluebutton/assets/95290346/4d88da18-75b5-46c2-91de-89ad9f609d33

**BBB version:**
BigBlueButton Server [2.6.9](https://github.com/bigbluebutton/bigbluebutton/releases/tag/v2.6.9)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome
 - Version Version 114.0.5735.90 (Official Build) (64-bit)

**Comment by FreeScholar** [comment]
I believe this is working as designed. A presenter may not want everyone to have access interact on every slide. They may want to start the drawing and then allow specific people or the whole group. This could be clumbsy if everyone is enabled as you would have to disable if you as a presenter wanted to illustrate a point.
Takes 1 second to enable everyone's access.

**Comment by anandchristudas** [comment]
Ok but a way to allow multi-user access for all slides seems to very useful according to our teachers. 

Thanks a lot for confirming.
