### ISSUE TITLE
no sound after joining

### ISSUE THREAD

**Issue by bigbluebutton-issue-import** [bigbluebutton/bigbluebutton#1808]
Originally reported on Google Code with ID 1053

```
- i click on the share microphone
- flash asks if i want to share the microphone, the micro testing dialog appears. 
- On the testing dialog everything is ok - i can hear from the loudspeakers everything
I say to the micro.
- since I click on 'join audio', i can hear nothing from the loudspeakers. No my sounds,
also no sounds from other users.


(Ubuntu 10.04, chromium 15, adobe flash player 11.0.1.152)
```

Reported by `andrius@kurtinaitis.lt` on 2011-10-29 15:52:58

**Comment by maryam-art** [comment]
I cant hear my teacher and piers

**Comment by Aidagh98** [comment]
My problem is where my mic and webcam works, but I can't hear any audio from another user , Sometimes i hear myself During echo test, sometime I don’t.
on iOS 13.7 on iPhone MT962LL/A
i’m having real problems, because i can’t attend my exams, help me please.
