### ISSUE TITLE
[2.5 Learning Dashboard] download CSV button is grayed 

### ISSUE THREAD

**Issue by hiroshisuga** [bigbluebutton/bigbluebutton#18087]
**Describe the bug**
In Learning Dashboard of BBB2.5, the download CSV button is grayed. But you can push it and download the data.

**To Reproduce**
1. Open Learning Dashboard
2. see the download CSV data button

**Expected behavior**
The button and the "Last updated at..." label on the left is darker. 

**Actual behavior**
They are grayed as if they are inactive (they are active, actually).

**Screenshots**
<img width="753" alt="スクリーンショット 2023-06-04 18 40 20" src="https://github.com/bigbluebutton/bigbluebutton/assets/45039819/261aa265-3b94-4010-a7dd-e85e8c2981e4">

**BBB version:**
2.5.17

**Desktop (please complete the following information):**
 - OS: MacOS
 - Brave

**Comment by antobinary** [comment]
Hi @hiroshisuga 

I just tried this on a 2.5 server and the button "Download Session Data" was active and worked correctly. Anything specfic you may have recently customized on the server perhaps?

I am attaching a screenshot from what I see on https://test.bigbluebutton.org/
Could you please give that server a try?

![Screenshot from 2023-06-05 14-52-25](https://github.com/bigbluebutton/bigbluebutton/assets/6312397/1a970f9b-be7f-4451-8fc9-90134865e3fc)

**Comment by hiroshisuga** [comment]
Hi @antobinary , I could not confirm it on the official test server, which has been closed already. 
I will try a clean install. In the meanwhile I close it, leaving a possibility of reopening.
