### ISSUE TITLE
BBB 2.6 - Error default.pdf

### ISSUE THREAD

**Issue by sheyk87** [bigbluebutton/bigbluebutton#18102]
![Captura de pantalla 2023-06-06 212234](https://github.com/bigbluebutton/bigbluebutton/assets/86056803/6c8c601a-2aab-4129-863e-d97142b38b1c)
I upload a custom default.pdf, but BBB cant process it
I submit screencap

**Comment by hiroshisuga** [comment]
How did you upload it? Is it possible to deposit it here in Github?

**Comment by sheyk87** [comment]
> How did you upload it? Is it possible to deposit it here in Github?

Hi, i upload it by scp... the file has the same rights that original default.pdf, and the new default.pdf can be accesible by bbb.domain.com/default.pdf without problems...

**Comment by sheyk87** [comment]
> Hello,
> 
> A fix has been applied in this PR #18091
> 
> To make the default presentation processing happen just put an empty value for `insertDocumentBlockedHosts` in your `/etc/bigbluebutton/bbb-web.properties` like this
> 
> ```ini
> ...
> insertDocumentBlockedHosts=
> ...
> ```

I'll try this, thank you.

**Comment by sheyk87** [comment]
> Hello,
> 
> A fix has been applied in this PR #18091
> 
> To make the default presentation processing happen just put an empty value for `insertDocumentBlockedHosts` in your `/etc/bigbluebutton/bbb-web.properties` like this
> 
> ```ini
> ...
> insertDocumentBlockedHosts=
> ...
> ```

It's Works! Thank You Very Much!
