### ISSUE TITLE
Error when uploading or switching between presentations - 2.6.9 - intermittent 

### ISSUE THREAD

**Issue by mudislandkid** [bigbluebutton/bigbluebutton#18160]
**Describe the bug**
Intermittent for certain users. When a teacher either tries to upload a presentation or switches between presentations, they get a modal popup error saying "An Error Occurred, it has been logged, please try reloading the page". They then have to go through the echo check again to resume the lesson. This is occurring on multiple installations since upgrading to 2.6.9 (fresh installs).

**To Reproduce**
1. Load a new presentation or switch between already uploaded presentations (intermittent)
2. Error appears
3. Reload page and rejoin the session.
4. Repeats multiple times during the same session.

**Expected behavior**
User should be able to upload and switch between multiple presentations without error.

**Screenshots**
![image](https://github.com/bigbluebutton/bigbluebutton/assets/36311595/02eb8085-36d6-4049-be73-9b31b354f7fa)

**BBB version:**
BigBlueButton continually evolves. Providing the version/build helps us to pinpoint when an issue was introduced.
Example:
$ sudo bbb-conf --check | grep BigBlueButton
BigBlueButton Server 2.6.9 (1269)

**Desktop (please complete the following information):**
 - OS: Mac OSX
 - Browser: Safari and Chrome

**Comment by mudislandkid** [comment]
Has anyone else had this issue?

**Comment by antobinary** [comment]
Hi @mudislandkid 

I do not recall seeing this before. Could you please try to reproduce it on test26.bigbluebutton.org (also 2.6.9) and if you are able to, please take a screenshot including the url session token?

Also, the browser logs (in the developer tools) would really help in case you have those from the session in the screenshot
