### ISSUE TITLE
 Fullscreen Button Not Working in Recorded Sessions

### ISSUE THREAD

**Issue by Mudassarali222** [bigbluebutton/bigbluebutton#18170]
I am using BigBlueButton for recording meetings, and I have noticed that the fullscreen button in the recorded meetings does not function in the same way as the fullscreen button in YouTube videos. When I click the fullscreen button in BigBlueButton's recorded meetings, the video does not expand to fill the entire screen.

I have tried using different browsers and devices, but the issue persists. It seems that the fullscreen functionality in BigBlueButton's recorded meetings is not working as expected.

Has anyone encountered this issue before? Is there a known workaround or a fix for this problem? I would greatly appreciate any insights or suggestions on how to resolve this fullscreen button issue in BigBlueButton recorded meetings.

Thank you in advance for your help!

` <iframe
                  title="Recorded video"
                  style={{ marginLeft: '0.6rem', marginRight: '0.6rem', borderRadius: '0.5rem' }}
                  width={'auto'}
                  height={'690vh'}
                  src={url[0] + '?l=content'} //url contains the recorded video of bigbluebutton
                  allowFullScreen
                />
`
![image](https://github.com/bigbluebutton/bigbluebutton/assets/75826150/fe33684b-1d08-4eff-b8b2-924ebdf3e705)

**Comment by hiroshisuga** [comment]
It is the intended design. 
Please see: https://github.com/bigbluebutton/bbb-playback/issues/155 .

**Comment by Mudassarali222** [comment]
@hiroshisuga This [bigbluebutton/bbb-playback/issues/155](https://github.com/bigbluebutton/bbb-playback/issues/155) issue is already open.I ca not getting the correct answer of my question.

**Comment by hiroshisuga** [comment]
As stated in the issue, the playback app does not use the browser's full-screen function. If you want to use it, you need to modify the code.

**Comment by Mudassarali222** [comment]
I am just installing bigbluebutton on server using command line .please guide me which type of file and line of code modify.

**Comment by hiroshisuga** [comment]
This is where you start:
https://github.com/bigbluebutton/bbb-playback

**Comment by Mudassarali222** [comment]
@hiroshisuga yes this is nice answer but you are right this is not easy to modify the code. I am stuck because its not using iframe.
