### ISSUE TITLE
BBB 2.6.9 Default Presentation Missing

### ISSUE THREAD

**Issue by frahman80** [bigbluebutton/bigbluebutton#18181]
**Describe the bug**
The default presentation does not load automatically on version 2.6.9
Fresh install performed multiple times on bare metal and VM with same result.

**This issue does not exist with version 2.6.8**

**To Reproduce**
bbb-install.sh with focal-260-2.6.9

**Expected behavior**
Default presentation to load automatically on session start.
Or at minimum the default.pdf should be listed in the presentation list. 

**BBB version:**
BigBlueButton Server 2.6.9

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser [Chrome, IE]

**Additional context**
All environment variables were untouched.

**Comment by hiroshisuga** [comment]
This seems likely to solve the problem:
#18102
