### ISSUE TITLE
Zoom into presentation is not recorded

### ISSUE THREAD

**Issue by cvokable** [bigbluebutton/bigbluebutton#18187]
**Describe the bug**
When you record a meeting and zoom into the presentation this is not shown in recording. In the recording you see only a wrong part of the presentation or white space where the presentation should be. 

**To Reproduce**
1. Start a meeting
2. Upload a presentation
3. Record the meeting
4. Zoom in the presentation
5. End the meeting and play the recording

**Expected behavior**
The recording should show the same part of presentation where we zoomed to 

**Screenshots**
Here is a recording that shows the problem: https://playback.app.bbbserver.de/1624e0a8ebb0e1d5f27332cc17c138beec1a9324-1687237776151

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome

**Additional context**
BigBlueButton Version: 2.6.9

**Comment by hiroshisuga** [comment]
I cannot confirm it. Please test your file at test26.bigbluebutton.org .
