### ISSUE TITLE
Export shared notes as *.docx instead of *.doc

### ISSUE THREAD

**Issue by Digiuzi** [bigbluebutton/bigbluebutton#18216]
**Is your feature request related to a problem? Please describe.**
There is no problem but a nice to have. When you export your shared notes, you can choose different types of file formats. But the Microsoft Word format is very old. It's the 97er binary format of Microsoft Word. In many companies, the binary doc format is not allowed, because they use the actually Microsoft Security baselines, which block this format.

**Describe the solution you'd like**

I would like to export the shared notes as *.docx instead of *.doc.

**Describe alternatives you've considered**

It's possible to export as *.odt or to *.pdf and then to convert to *.docx. But it is two more steps.

**Additional context**
-

![shared_notes_export](https://github.com/bigbluebutton/bigbluebutton/assets/137771325/6882aa0d-5c23-43a6-bc88-43208025d761)
![export_doc_filetype](https://github.com/bigbluebutton/bigbluebutton/assets/137771325/e6ad4681-0ba4-4918-923e-56f5ca8ec0d1)

**Comment by lonesomewalker** [comment]
For all who are still searching:
in /usr/share/etherpad-lite/src/node/hooks/express/importexport.js line 29

There you find your filetypes.
They get passed on to soffice, so i STILL wonder why this is an issue :-)
Created pull request at etherpad-lite, hopefully accepted soon.
