### ISSUE TITLE
[2.6.10] Presentation pointer size not precise after pointerDiameter changed

### ISSUE THREAD

**Issue by Buda9** [bigbluebutton/bigbluebutton#18212]
**Describe the bug**
This bug is related to [18106](https://github.com/bigbluebutton/bigbluebutton/pull/18106). Pointer size is not precise on the first load. However, if you change to slide 2 and back to slide 1, it works fine. See video below.

**To Reproduce**
1. Well, in /etc/bigbluebutton/bbb-html5.yml I changed pointerDiameter to 15 and then to 10
2. I restarted bbb and I saw this bug

**Expected behavior**
Pointer should be precise as it currently is on slide 2 in video, but it's not

**Actual behavior**
Pointer is not precise unless we change to slide 2 and back to slide 1

**Screenshots**
video: https://github.com/bigbluebutton/bigbluebutton/assets/1422662/1f6eb200-cfe8-4976-85a3-ebc073828e65
recording (skip to 0:08 sec): https://bbb.vokabula.com/playback/presentation/2.3/089797040bfc4c72985d121f7f1561e14c38aa8d-1687705413474

**BBB version:**
BBB 2.6.10

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Edge 115

**Comment by ffdixon** [comment]
Good catch!  In our testing we probably were moving around the slides and never encountered this case.

Thanks @Buda9 for reporting this.  It makes it easier for us to find and fix.
