### ISSUE TITLE
Bad visual quality of bluring-effect of background 

### ISSUE THREAD

**Issue by eegcl-bugs** [bigbluebutton/bigbluebutton#18229]
Compared to Zoom, the background blur-effect of BBB is not very good. Behind the head of the participants there is a lot of background visible and also distortions.
Compare Zoom: https://stadt-bremerhaven.de/wp-content/uploads/2020/04/zoom-security-icon-1024x649-1.jpg

To BBB: https://upload.wikimedia.org/wikipedia/commons/8/8c/Screenshot-bbb.png

**Describe the solution you'd like**
In order to stay competitive, this problem should be solved.

**Comment by ffdixon** [comment]
We were glad to introduce background blur a few years ago.  It was based on TFLite and used open source models from Google.  There may be later models we could use that would provide better background blur (some investigation needed). 

For more details, see this excellent presentation at the BigBlueButton World 2021 conference https://youtu.be/pnpbL7e3e-0

**Comment by eegcl-bugs** [comment]
Hi ffdixon,
thanks for the quick answer. There seems to be a wide variety of software out there:

https://mobidev.biz/blog/background-removal-and-blur-in-a-real-time-video
https://awesomeopensource.com/projects/background/blur

**Comment by ffdixon** [comment]
The Google project upon which we based the background blur has not released updated models.

  https://github.com/google/mediapipe/tree/master/mediapipe/modules/selfie_segmentation

The ideal solution is to find a newer model that the above that we could use to update the media pipeline in BigBlueButton.   

Thanks for the links, but we didn't see anything that matched what we are looking for above.

**Comment by eegcl-bugs** [comment]
Hm, ok, hope there is an improved model out there...

I made a little web search just a few additional links to check:
https://github.com/EffectsSDK/electron-integration-sample
https://github.com/amanullahtariq/realtime_bg_blurring
https://github.com/jashandeep-sohi/webcam-filters

( Also fun but something else:  https://github.com/alievk/avatarify-desktop)
