### ISSUE TITLE
End Meeting on 2.7 omits feedback/logouturl

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#18224]
**Describe the bug**
Ending the meeting in BBB 2.7 does not show the usual feedback/OK/logouturl options

**To Reproduce**
1. Create a meeting on BBB 2.6
2. Hit End Meeting and observe the results
3. Create a meeting on BBB 2.7
4. Hit End Meeting and observe the results

**Expected behavior**
2.6:
![Screenshot from 2023-06-26 10-54-48](https://github.com/bigbluebutton/bigbluebutton/assets/6312397/ba4bc423-4b30-4d6e-9aff-c50c5dcada06)

**Actual behavior**
2.7
![Screenshot from 2023-06-26 10-55-28](https://github.com/bigbluebutton/bigbluebutton/assets/6312397/69f90b9e-3955-4c56-a035-c33de9dd6287)

**BBB version:**
BigBlueButton 2.7.0-alpha.2

**Comment by antobinary** [comment]
Possibly related https://github.com/bigbluebutton/bigbluebutton/issues/16463

**Comment by antonbsa** [comment]
Related to #18215
