### ISSUE TITLE
Error in bbb-conf script

### ISSUE THREAD

**Issue by CS-sysadmins** [bigbluebutton/bigbluebutton#18225]
**Describe the bug**
In the bbb-conf script, line 1331, at the journalctl -u bbb-rap-* command, generates an error. The asterisk is not interpreted. We resolved in this way:
journalctl -u bbb-rap-starter.service -u bbb-rap-resque-worker.service -u bbb-rap-caption-inbox.service

From
[...]
if journalctl -u bbb-rap-* | grep -q 'Nil'; then

to
[...]
if journalctl -u bbb-rap-starter.service -u bbb-rap-resque-worker.service -u bbb-rap-caption-inbox.service | grep -q 'Nil'

**To Reproduce**
1. run bbb-cof --check after installation of bbb 2.6
2. See error: "Failed to add filter for units: No data available"

**Comment by Ithanil** [comment]
Can't reproduce this on our 2.6 servers, there is neither the error in bbb-conf nor when executing the journalctl on the command-line. Tested on 2.6.10, but can't remember seeing this error ever before and it shouldn't depend on the BBB version anyway. The feature for using unit file patterns was added to systemd in 2014: https://bugs.freedesktop.org/show_bug.cgi?id=59336

I wonder what version of Ubuntu you are running BBB on?

**Comment by CS-sysadmins** [comment]
hello,
i solved it, it was a journalctl problem, not a bbb-conf problem
thanks
