### ISSUE TITLE
[2.6.10] Wrong slide position after zoom in and out

### ISSUE THREAD

**Issue by einhirn** [bigbluebutton/bigbluebutton#18232]
**Describe the bug**
After zoom in and out the position of the slide is wrong.

**To Reproduce**

1. Start a meeting with a moderator/presenter and a viewer.
2. The presenter zoom in and out the current slide.
3. The position of the slide seems correct at the presenter, but it is wrong at the viewer.
4. The presenter switches the slide forward and back.
5. The position of the slide at the presenter is also wrong.

**Screenshots**
![Screenshot 2023-06-26 175423](https://github.com/bigbluebutton/bigbluebutton/assets/189249/beca7fc7-5e02-4f08-9016-ba10d6b937c4)

**BBB version:**
BigBlueButton Version: 2.6.10
Clientversion: 652

**Desktop:**
OS: Windows 10
Browser: Chrome
Version: 114.0.5735.199

**Comment by antonbsa** [comment]
I tested and could easily reproduce this bug. I'm also able to confirm that this is what breaks the `Presentation › Zoom In, Zoom Out, Reset Zoom` automated test (recent CI output screenshot below)

![image](https://github.com/bigbluebutton/bigbluebutton/assets/56703993/c28edc1f-f593-4dee-b6ad-521281c1e728)
