### ISSUE TITLE
constant air play when speaker is idle

### ISSUE THREAD

**Issue by trainng9798** [bigbluebutton/bigbluebutton#18239]
I remember I read about configuring bbb to play some air like sound constantly so listeners dont think they are disconnected or somethings wrong when speaker isnt talking for seconds and class is idle. please guide me where in documentation i Can find it.

**Comment by hostbbb** [comment]
https://docs.bigbluebutton.org/administration/customize#turn-on-the-comfort-noise-when-no-one-is-speaking
