### ISSUE TITLE
bbb-conf outputs "Error: Unable to reach default URL for presentation" for a valid default presentation

### ISSUE THREAD

**Issue by GhaziTriki** [bigbluebutton/bigbluebutton#18241]
**Describe the bug**
Some installations have big default presentations. bbb-conf fails to validate them and shows an error.

**To Reproduce**
1. Put a 90mb default.pdf with 350 pages.
2. Run `bbb-conf --restart`

**Expected behavior**
No error should be in the console output.

**Actual behavior**
We see an error in the console:

```
# Error: Unable to reach default URL for presentation:
#
#    https://bbbserver.com/default.pdf
#
# Check value for beans.presentationService.defaultUploadedPresentation in
#   /usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties and /etc/bigbluebutton/bbb-web.properties
```

**Additional context**

The problem comes from the following line of bash code

https://github.com/bigbluebutton/bigbluebutton/blob/2914208b113b3e9066543941fe5155791102231d/bigbluebutton-config/bin/bbb-conf#L1089C96-L1089C110

**Suggested solution**

Use `curl` to validate the 200 HTTP status only.

_(updated)_
Storing the value of the below command and comparing to `200` should do the trick
`curl -s -o /dev/null --head -w "%{http_code}" https://bbbserver.com/default.pdf`

**Comment by ffdixon** [comment]
Good catch.
