### ISSUE TITLE
Daily cron not calcualting claimed space

### ISSUE THREAD

**Issue by GhaziTriki** [bigbluebutton/bigbluebutton#18254]
**Describe the bug**
When running daily bigbluebutton cron the output is always `Total reclaimed space: 0B` even if files were deleted.

**To Reproduce**
1. Run command line `sudo /etc/cron.daily/./bigbluebutton`

**Expected behavior**
Show the right claimed space.

**Actual behavior**
Always show `0B` as claimed space.

**Comment by mahaesin** [comment]
This line seems to be the output of `docker image prune -f` which is run by the cron job. It will report other values only if old/unused docker images are deleted.

To me this output is irrelevant so i altered the command in the cron job to
`docker image prune -f 2>&1 | logger`

I assume there is no mechanism to sum up total freed up disk space.

**Comment by diatodan** [comment]
Hi,
I have recently updated to BBB 2.6 and am now receiving this daily mail : 
/etc/cron.daily/bigbluebutton:
Total reclaimed space: 0B

I tried to run the command in the cronjob but I am still receiving this message.
Any ideas ?

**Comment by Daniel-at-git** [comment]
Issue still available with BBB 3.0. Please reopen issue.

Can someone modify line 128
https://github.com/bigbluebutton/bigbluebutton/blob/main/bigbluebutton-config/cron.daily/bigbluebutton#L128
like suggested in https://github.com/bigbluebutton/bigbluebutton/issues/18254#issuecomment-1641601022

**Comment by GhaziTriki** [comment]
The simplest would be computing the difference of space before and after cleanup assuming it is accurate.

**Comment by Daniel-at-git** [comment]
> The simplest would be computing the difference of space before and after cleanup assuming it is accurate.

Even if the job deletes something I don't need a cronjob mail. To cleanup data is the usecase... ;-)

**Comment by JohnXLivingston** [comment]
> Issue still available with BBB 3.0. Please reopen issue.
> 
> Can someone modify line 128 https://github.com/bigbluebutton/bigbluebutton/blob/main/bigbluebutton-config/cron.daily/bigbluebutton#L128 like suggested in [#18254 (comment)](https://github.com/bigbluebutton/bigbluebutton/issues/18254#issuecomment-1641601022)

I just made a PR: https://github.com/bigbluebutton/bigbluebutton/pull/23965
I hope that it will be accepted. I just sent my Contributor Agreement, it is my first contribution.
