### ISSUE TITLE
[2.7] - User reaction on Learning dashboard

### ISSUE THREAD

**Issue by antonbsa** [bigbluebutton/bigbluebutton#18260]
There's currently no column for the new user reaction on the learning dashboard. There is the "emojis" column, which is for the user status. When disabling that, it won't have any content to show. In this case, we could show the reactions, or maybe adding a new column (see the example below)

![image](https://github.com/bigbluebutton/bigbluebutton/assets/56703993/1cc51ec2-c882-4545-a782-3267dbc26ac3)

**Comment by farhatahmad** [comment]
Hit this as well when testing
