### ISSUE TITLE
bug: reduceDuplicatedPick doesn't reset correctly

### ISSUE THREAD

**Issue by gustavotrott** [bigbluebutton/bigbluebutton#18278]
Taking a look at this code:
https://github.com/bigbluebutton/bigbluebutton/blob/2879641b89bf35a9ab6b711e73ae4f0605702ed8/akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/SelectRandomViewerReqMsgHdlr.scala#L43

It resets the users exempted when remains only 1 user available.
But it should reset also when there is 0 users available!

The problem happens when the users not exempted leave the meeting and then it remains 0 users available to be picked!

### How to reproduce:

1. Set the config `reduceDuplicatedPick = true` in akka.
2. Start a meeting
3. Join Moderator
4. Join Viewer 1
5. Join Viewer 2
6. Moderator "Select Random User"
7. The Student the was not selected leaves the meeting
8. Moderator "Select Random User" again
9. Moderator receive the msg "No viewers available to randomly select from"

https://github.com/bigbluebutton/bigbluebutton/assets/5660191/312fb305-f7c3-4668-832f-4963ced4e295

**Comment by gustavotrott** [comment]
Related: https://github.com/bigbluebutton/bigbluebutton/pull/13831

**Comment by hiroshisuga** [comment]
Thanks for pointing it out! 
It seems this happens when three students (+ teacher) are joining a meeting. If there are 2 students + 1 teacher, the message "there is only one viewer to be picked up" appears and you can continue random picking. 
Let me see..
