### ISSUE TITLE
Text rendering issues during presentation playback

### ISSUE THREAD

**Issue by defnull** [bigbluebutton/bigbluebutton#18287]
**Describe the bug**

During playback of a recorded presentation, text annotations are sometimes incorrectly word-wrapped. It looks like the text bounding-box is too small to fit the longest line, or the text is rendered larger than it should be. This causes letters or words to be split into the next line or jump around while typing.

There is no issue during the meeting or with the new 'video' format, so I guess the 'raw' recording data is correct, just the 'presentation' format or its playback in browsers is flawed.

**To Reproduce**

See https://join.meet.gwdg.de/playback/presentation/2.3/e8a817d98b0a7c3fe31b160daf51d8c1c79ed66b-1688716736096 and compare it to https://join.meet.gwdg.de/playback/video/e8a817d98b0a7c3fe31b160daf51d8c1c79ed66b-1688716736096/

**Screenshots**
The presenter is slowly typing four lines here, you can clearly see the unwanted word/letter wrapping.
![screen2](https://github.com/bigbluebutton/bigbluebutton/assets/62740/1b624995-6bc6-4f42-8582-b3c862cebdcb)

BBB 2.6, same results in Firefox and Chromium (both Linux)

**Comment by ffdixon** [comment]
Good catch!  They both get the correct layout in the end

<img width="1428" alt="image" src="https://github.com/bigbluebutton/bigbluebutton/assets/290351/1e08ba1f-9216-4f97-b085-9ac980fab1c8">

but the presentation format does do some unnecessary word-wrapping as it plays back the text.
