### ISSUE TITLE
how can i intergrate CDN with Big bluebutton

### ISSUE THREAD

**Issue by bigbluebutton-issue-import** [bigbluebutton/bigbluebutton#1829]
Originally reported on Google Code with ID 1075

```
hi i need to integrate this conference with CDN.
How Can i do it?
please help me
```

Reported by `murali1309` on 2011-11-20 13:03:44

**Comment by ffdixon** [comment]
Closing this issue as there are multiple request in this single issue.  We'll pick up the deployment of BigBlueButton components via a CDN in 2.2.
