### ISSUE TITLE
recording not synce in 2.5.18

### ISSUE THREAD

**Issue by mahdidev70** [bigbluebutton/bigbluebutton#18296]
I am using BigBlueButton Server 2.5.18 (3247)
some of the recordings play back with a problem that video and audio are not synced.
I know the same problem is in 2.6.9 and it was solved in the latest update.
but I need a solution that helps me without updating to the 2.6 version

**Comment by mahdidev70** [comment]
@prlanzarin 
so, what is the solution?

**Comment by hex-m** [comment]
First thing would be to try the latest version of BigBlueButton and check if the problem persists. 2.5 is not supported anymore so there won't be a fix for that version.
