### ISSUE TITLE
Viewer can set the presentation to full screen by double clicking on it

### ISSUE THREAD

**Issue by antonbsa** [bigbluebutton/bigbluebutton#18309]
**Is your feature request related to a problem? Please describe.**

This would be like a shortcut for the viewers, an easier and faster way to set the presentation fullscreen. It would be useful when the viewer wants to quickly maximize the presentation aiming to see something there more clearly - doing the same after that could exit the fullscreen

**Comment by Zvangi** [comment]
This would be really helpful for mobile devices
