### ISSUE TITLE
[2.6] - Switching presentation with fit to width enabled applies super zoom into the slide

### ISSUE THREAD

**Issue by antonbsa** [bigbluebutton/bigbluebutton#18318]
**To Reproduce**
1. Join a meeting and upload a presentation;
2. Wait until the upload end;
3. Click on Actions button (+) and switch to another presentation;
4. See slide with super zoom

**Video**

https://github.com/bigbluebutton/bigbluebutton/assets/56703993/72d74b9d-db40-4d4d-88b4-b7991f4f613a

**More**
Possibly related to 
- #18232 
- #18231
___
**Also:** after uploading multiple presentations I could hit the crash below into a modal:

![image](https://github.com/bigbluebutton/bigbluebutton/assets/56703993/d60bebd0-360f-4633-80e3-2ccbc3012485)

**Comment by KDSBrowne** [comment]
I think this is the same as #17982

**Comment by antobinary** [comment]
Closed via https://github.com/bigbluebutton/bigbluebutton/pull/18597
