### ISSUE TITLE
After lesson time is out moderator isn't being redirected to logoutURL specified under meeting creation

### ISSUE THREAD

**Issue by lex-zhu** [bigbluebutton/bigbluebutton#18334]
**Describe the bug**
After lesson time is over moderator isn't being redirected to logoutURL specified under meeting creation

**To Reproduce**
1. Create a meeting using API call and specify logoutURL
2. Join the meeting
3. Wait until the meeting time run out
4. You're seeing the screen that tells you "This lesson has been ended. You'll be forwarded back to the home screen", but nothing happens

**Expected behavior**
After a small delay it should automatically redirect user to the logoutURL

**Actual behavior**
The screen hangs infinitely, user isn't being redirected

**Screenshots**
<img width="1440" alt="Screenshot 2023-07-17 at 23 30 00" src="https://github.com/bigbluebutton/bigbluebutton/assets/80315078/8bde1614-0a6c-4a8b-9155-aa2c6fa04e75">

**BBB version:**
BigBlueButton Server 2.7.0-alpha.3 (256)

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser Chrome
 - Version 114.0.5735.198 (Official Build) (x86_64)

**Comment by Scroody** [comment]
I've tested and so far as reproduction steps go, I couldn't reproduce this bug. In case you can still reproduce it and have more details regarding the issue, please, don't hesitate in commenting back so I can test it again.

https://github.com/bigbluebutton/bigbluebutton/assets/36093456/b56b7fab-0957-4a99-b179-c01e4761c921

**Comment by antobinary** [comment]
We've improved the wording of the label -- no redirection is supposed to happen (or at least hasn't meant to happen in the last couple of BBB major releases). Thanks for bringing this up!
