### ISSUE TITLE
Investigate using Google Translate APIs v2

### ISSUE THREAD

**Issue by bigbluebutton-issue-import** [bigbluebutton/bigbluebutton#1833]
Originally reported on Google Code with ID 1079

```
Google now has a paid service for its translate APIs.  See

   http://code.google.com/apis/language/translate/overview.html

Need to investigate the work required to use these new APIs in stead of the currently
depreciated APIs.


```

Reported by `ffdixon` on 2011-11-22 01:54:19

**Comment by johnhorst** [comment]
Just successfully installed BBB.  One of my main interests is in being able to support English language learners overseas, so translation in the chat module will be huge.  I understand from searching through the groups/boards (this thread especially) that the deprecated Google Translate API is currently available.  I have my own API key for v2, and would like to participate in developing support for v2.  Just need to be pointed in the right direction.

**Comment by hostbbb** [comment]
An early version .71 has support for this, when it went to a paid service it was factored out.
Looking at the .71 branch
https://github.com/johnhorst/bigbluebutton/blob/v0.71/bigbluebutton-client/src/org/bigbluebutton/modules/chat/views/ChatView.mxml#L59

you can see the flash library that was used.  and looking at this code can see how it was done back them.

there also is a close captioning project that may be a better fit.  this is 1.1 project,  I'll let the core devs jump in on this one.

**Comment by johnhorst** [comment]
@hostbbb Thanks for starting me off...  While I did some flash/actionscript development a long time ago, I am new to Flex, thus am in learning mode.  As I look at this, it strikes me as client side code.  Some research online seems to confirm this.  For the same reason we should not be using our BBB salt in client side JavaScript, I do not want to program against Google Translate's v2 API as I have to pass my API key in the "key'..." name/value pair in the querystring.

It does not look like NGINX supports any server side language.  I am looking at the "Production Environment" graphic and that suggests PHP on Tomcat.  I come into this with deep experience in C# and see something called FastCGI for NGINX that I apparently can use.

Another option would seem to be developing a native IIS application in ASP.NET (MVC) and calling to BBB's API.

The end goal is to program against the Google Translate v2 API in server side code so as not to expose my API key.  Any thoughts?

**Comment by capilkey** [comment]
The biggest problem that I can see is that chat messages don't have unique identifiers (so a client couldn't request a translation based on id) and

**Comment by KiaraGrouwstra** [comment]
i found a [video](https://youtu.be/VjZV0byQERc) demonstrating bigbluebutton captions translation, but afaict this functionality does not seem available in the present version.
why was this closed as completed then?

**Comment by pedrobmarin** [comment]
It's disabled by default. Check on your HTML client settings for "dictation".

**Comment by KiaraGrouwstra** [comment]
hm, wasn't dictation is about speech recognition?
if so, does that mean translating features for manual captions are still missing?
or does this depend on that setting because they both need google apis?

**Comment by pedrobmarin** [comment]
Ah, I see what you mean... the video you linked is from a BBB fork that implemented the translation. As far as I know, this investigation over Google's V2 API halted and wasn't elevated to a product feature.
There are some community driven alternatives in case you need this on your BBB. This is one of them https://github.com/bigbluebutton/bigbluebutton/pull/14355 .
