### ISSUE TITLE
Reintroduce (gear icon) -> "Clear all status icons" for moderators

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#18345]
**Describe the bug**
Looks like we droped what we had in BB 2.6 as (gear icon) -> "Clear all status icons" for moderators

**Expected behavior**
2.6

![Screenshot from 2023-07-18 16-30-14](https://github.com/bigbluebutton/bigbluebutton/assets/6312397/dd09a2f2-eb20-4efe-a578-6bdcd6754a49)

**Actual behavior**

2.7
![Screenshot from 2023-07-18 16-29-45](https://github.com/bigbluebutton/bigbluebutton/assets/6312397/c844866b-9f28-4a49-8a04-24c9862f080a)

**BBB version:**
BigBlueButton 2.7.0-beta.1

**Comment by antobinary** [comment]
Let's double check that clearing does not lower any raised hands (those should be lowered separately)

**Comment by gustavotrott** [comment]
> Let's double check that clearing does not lower any raised hands (those should be lowered separately)

I think it should not clear `away` status as well.
what do you think?
