### ISSUE TITLE
Multiple Audioplayer in the presentation

### ISSUE THREAD

**Issue by jorgelondo** [bigbluebutton/bigbluebutton#18362]
Hi, It would be ideal to be able to upload audio tracks on top of the presentations, in order to carry out listening exercises according to elements in the presentation.

![bbb-audios-en-presentacion](https://github.com/bigbluebutton/bigbluebutton/assets/672505/de598e6b-beaa-4ada-ae97-f49dc51bc9bb)

Other platforms such as openmeetings allow you to do it
Thanks

**Comment by hiroshisuga** [comment]
Aren't these your options?
1. Sharing a media file that you have uploaded to Youtube beforehand
2. Sharing a browser's tab in which you play audio (you can also share audio if you use Google Chrome)

**Comment by jorgelondo** [comment]
Hi @hiroshisuga The idea is to be able to include audio interactively, to listen to an audio according to elements in the presentation, for example, an exercise in listening to the alphabet.

![BBB-AUDIO-in-plataform](https://github.com/bigbluebutton/bigbluebutton/assets/672505/3e3d8008-15bf-4db7-b8d3-df341d02f561)
Thanks
