### ISSUE TITLE
2.7: Dial-in users not in list / no talk indicator

### ISSUE THREAD

**Issue by danimo** [bigbluebutton/bigbluebutton#18371]
Using the latest dev packages, dial-in participants are invisible to other participants.

**Describe the bug**

**To Reproduce**
1. Create room
2. Dial in

**Expected behavior**
Dial-in participant is visible as a dial-in participant and a talk indicator shows up

**Actual behavior**
The dial-in participant appears as though they never joined.

This is a regression over 2.6, although an issue causing identical behavior was fixed (#17671) there, too. However, it seems the [relevant commit](614aa34496a6b3e0b7f1183439cd9cd65cc605a8) is part of 2.7

**Comment by antobinary** [comment]
Link to the "relevant commit" mentioned above https://github.com/bigbluebutton/bigbluebutton/commit/614aa34496a6b3e0b7f1183439cd9cd65cc605a8
