### ISSUE TITLE
BBB-Webhooks installation defective

### ISSUE THREAD

**Issue by marga-reflact** [bigbluebutton/bigbluebutton#18379]
**Describe the bug**
The installation of bbb-webhooks aborts with the error message "unsafe-perm".

**Installation type**
After the installation with "wget -qO- https://github.com/bigbluebutton/bbb-install/v2.7.x-release/bbb-install.sh | bash -s -- -v focal-270 -s domain.de -e domain@domain.de" I install bbb-webhooks with "apt-get install bbb-webhooks -y".

**Console output**
![webhhok-bbb](https://github.com/bigbluebutton/bigbluebutton/assets/110968854/2f9a22f7-db00-44bd-93f6-6de166cc0845)

**Additional context**
[Add any other context about the problem here.
](https://groups.google.com/g/bigbluebutton-dev/c/11RlUkG0yh8/m/QFxAFqw5BAAJ)

**Comment by antobinary** [comment]
Thank you for reporting!

**Comment by antobinary** [comment]
Done as part of BBB 2.7.1 see https://github.com/bigbluebutton/bigbluebutton/issues/18734
