### ISSUE TITLE
How to put your certificate on the server

### ISSUE THREAD

**Issue by miqonee** [bigbluebutton/bigbluebutton#18403]
How to put your certificate on the server, without any crutches, give normal instructions, I don’t know how you could miss the new documentation, this is nowhere. And people like me can't find a solution

**Comment by hostbbb** [comment]
By default bbb-install generates and install letsencrypt certs.  If you want to use your own  the -d looks in /local/certs for key and fullchain that you place prior to running install.

https://github.com/bigbluebutton/bbb-install

 -d                     Skip SSL certificates request (use provided certificates from mounted volume) in /local/certs/
