### ISSUE TITLE
Issue with whiteboard tools with Microsoft Edge browser

### ISSUE THREAD

**Issue by GreciaHdz93** [bigbluebutton/bigbluebutton#18401]
**Describe the bug**

The whiteboard tools such as pencil, text, rectangle, etc., which are functions to write in the presentation, do not work correctly, since they can only be used on the right side of the presentation and not on the entire screen as it should be. .

This happens only in the Edge browser and some versions of Google Chrome.

**To Reproduce**
The whiteboard tools such as pencil, text, rectangle, etc., which are functions to write in the presentation, do not work correctly, since they can only be used on the right side of the presentation and not on the entire screen as it should be. .

This happens only in the Edge browser and some versions of Google Chrome.

1) Enter an online session
2) Use the tools on the board, on the default presentation
3) Start making lines, but only leave the right side of the screen, when you go to the left the pointer disappears and does not let you write.

**Expected behavior**
I was hoping that the tools can be used on the entire screen, not just on the right side.

**Actual behavior**
Currently it is not allowed to use the tools on the whiteboard on the left side of the screen, even with the default presentation of Bigbluebutton

**Screenshots**

![imagen](https://github.com/bigbluebutton/bigbluebutton/assets/140839999/6d2918c1-8721-4803-906a-2b99b1069cea)
https://screenpal.com/watch/c0iuqUVkOLr

**BBB version:**
BigBlueButton Server 2.5.16 (3227)
                    Kernel version: 5.19.1-051901-generic
                      Distribution: Ubuntu 20.04.6 LTS (64-bit)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Microsoft Edge
 - Version Versión 115.0.1901.188 

**Additional context**
[Add any other context about the problem here.](https://screenpal.com/watch/c0iuqUVkOLr)

**Comment by hiroshisuga** [comment]
Seems to be a duplicate of #18066 . Upgrading should solve the issue.

**Comment by GreciaHdz93** [comment]
Hi hiroshisuga according to the case that you shared with us where the issue was solved we did what was recommended, but our issue wasn't solved by installing version 2.5.18

We have the same issue with the browser Microsoft Edge. We cannot write on the left side of the board with the Microsoft Edge browser.

![imagen](https://github.com/bigbluebutton/bigbluebutton/assets/140839999/5eb5ade8-bfcf-429a-9e98-0a731c10566c)

We suggest making a backport of this fix that is from 2.6 to 2.5.18

**Comment by hiroshisuga** [comment]
Hi @GreciaHdz93, I am also still using 2.5.18. 

This fix works perfectly for me. 
https://github.com/bigbluebutton/bigbluebutton/pull/18188

You could either wait for 2.5.19 or apply this patch by yourself.

**Comment by ravenmanco** [comment]
Hi @hiroshisuga , should we talk by internally in order to have your help to implement that fix in our code? as a service?, we appreciate your help, is very importante for us to solve this issue as soon as we can, thanks.

**Comment by hiroshisuga** [comment]
well, I don't think you will have a better support from me than by disclosing the details here... If your problem is to modify the source code, every detail is nicely written in the document.

**Comment by ravenmanco** [comment]
Hi Hiroshuga, we are not developer experts, so we dont know how to compile the code, in our machines the application is installed used the command :

wget -qO- https://ubuntu.bigbluebutton.org/bbb-install-2.5.sh | bash -s -- -v focal-250 -s $hostname -e $email  -a -w

And checking the code there is not such folders in that location after this installation :

![image](https://github.com/bigbluebutton/bigbluebutton/assets/58411407/ba0c77c1-e4fa-48bd-beb9-e46a635d25ea)

As you can see there is no such jsx files or the folder bigbluebutton-html in the entirme machine:

![image](https://github.com/bigbluebutton/bigbluebutton/assets/58411407/a5d28321-7a58-44d3-9d83-203da6a76da2)

That's why we are requiren help.

**Comment by ravenmanco** [comment]
Hi @hiroshisuga , thanks for your quick response, we will go and have a try with that manual, thanks for your feeback, we dind't know that developer manual, 

Thanks.
