### ISSUE TITLE
Google forum ignoring requests to join

### ISSUE THREAD

**Issue by jshrek** [bigbluebutton/bigbluebutton#18428]
I made request to join the google forums, but after several days, request to join is still waiting.

I can't ask questions if nobody lets me join the forum!

https://groups.google.com/g/bigbluebutton-setup
https://groups.google.com/g/bigbluebutton-users
https://groups.google.com/g/bigbluebutton-dev

**Comment by antobinary** [comment]
Hi @jshrek 
I am not seeing pending forums joins. What's the email used (feel free to omit the part after @)

**Comment by jshrek** [comment]
jeff@for...
see attached screenshots
![firefox_2023-08-03_15-50-24](https://github.com/bigbluebutton/bigbluebutton/assets/19673842/ed3008ff-da86-4dd4-96ae-9f5429278618)

**Comment by antobinary** [comment]
Hi @jshrek ,
This should be resolved now, I see you listed as a member in good standing. We shifted some things around so other pending join requests should be treated much faster. Appreciate your patience!
