### ISSUE TITLE
Double escaping of chat links when `bufferChatInsertsMs != 0`

### ISSUE THREAD

**Issue by danimo** [bigbluebutton/bigbluebutton#18429]
**Describe the bug**
In the chat, links are double escaped, like so:

![image](https://github.com/bigbluebutton/bigbluebutton/assets/1315934/fa263855-427b-4038-aa1f-ec00f9888cf4)

The problem is with the refactoring in https://github.com/bigbluebutton/bigbluebutton/commit/838accf0158f1ecf0fdf60c6319d200a98ab9106#diff-fbeed1cf99fe37417380f4093d48280a9579c3423d5ac9ffa92f087819c1bbc4L5, which incorrectly refactors `addBulkGroupChatMsgs.js` to use the incorrect version of `parseMessage()` (actually, both are misnominors as they do a lot more than parsing, and this might have contributed to the confusion, but that's besides the point).

To see why setting the option makes a difference here:

https://github.com/bigbluebutton/bigbluebutton/blob/27fd5552ffda13e86de74aa272ec7a448031a745/bigbluebutton-html5/imports/api/group-chat-msg/server/handlers/groupChatMsgBroadcast.js#L19-L25

**To Reproduce**
1. Set `public.chat.bufferChatInsertsMs` to a value > `0`
2. Restart bbb-html5.service
3. Observe behavor

**BBB version:**
2.6.11 and 2.7.0-beta-3

**Comment by antobinary** [comment]
Thanks for fixing the issue and for also thoroughly documenting what the issue was (once you confirmed it was an issue)!
