### ISSUE TITLE
Support localized audio files in FreeSWITCH

### ISSUE THREAD

**Issue by bigbluebutton-issue-import** [bigbluebutton/bigbluebutton#1843]
Originally reported on Google Code with ID 1089

```
While the BigBlueButton client can localize into French, German, etc., the audio prompts
in FreeSWITCH are all English.

FreeSWITCH does provide audio files, such as the phrase "you have been kicked from
this conference", in different languages.

Investigate how to incorporate these into BigBlueButton so when a user joins they received
a localized audio prompts.



```

Reported by `ffdixon` on 2011-11-30 13:37:59

**Comment by ffdixon** [comment]
We've had a few more people asking for this ... will take a closer look in an upcoming version.

**Comment by Brullworfel** [comment]
Hello! Have you any news about it?

**Comment by ffdixon** [comment]
We've not looked into this yet.  At the moment we're pretty focused on development of the core HTML5 client.  

If you are a developer, the changing of language files (such as moving from English to French), could be done within FreeSWITCH.  

The following link should help you get started: https://freeswitch.org/confluence/display/FREESWITCH/Language+Files

**Comment by mamhoff** [comment]
So there are a few issues related to this. We are setting up an instance primarily geared towards German users and we LOVE the system. Amazing sound quality, and great features that respect the web! Also such sensible tech choices at so many levels. Kudos to your team, this is really wonderful software. 

It is really strange though to have a very well-translated frontend and then hearing English words in every call.

Here's the a list of (IMO) related issues:
#8497, #2153, #6083, probably [this message](https://groups.google.com/forum/#!msg/bigbluebutton-dev/7fk1SPcukHY/xlSe69YRdDQJ), probably [this message](https://groups.google.com/forum/#!topic/bigbluebutton-dev/aO_LZvA2omw), likely [this one too](https://groups.google.com/forum/#!topic/bigbluebutton-dev/GVAnR0t8IrE).

The posters are usually non-native English speakers or working in different locales.

I'm only concerned with the new HTML5 client here. I understand the sounds come out of FreeSwitch. Ideally though, the language of the sounds would correspond to the participant browser's locale, so when the frontend creates the SIP connection, it could potentially add an `Accept-Language` header to its requests. [SIP as a protocol supports this](https://tools.ietf.org/html/rfc3261#section-8.1.1.10), the question is whether FreeSWITCH also does. 

A problem with this approach that BBB or FreeSWITCH would need to start supplying all that audio in all those languages. German, for example, does not exist right now, and the FreeSWITCH distribution has a whole lot of audio files that are not relevant for BBB. Those files are, however, currently distributed with the `bbb-freeswitch-sounds` DEB package (in English only even though a few other languages are present). 

Getting all this audio recorded and then into the right repository (I just spent three hours trying to find the canonical source for the English audio and failed :D) is probably quite a lot of work, and not likely to be a quick success.

Another approach is the one outlined in #6083: Substituting all of the FreeSWITCH messages with sounds. I'm willing to ask around my musician friends to see whether we could get sounds that convey to users that: 

> You are the only person in this conference

> You have been kicked out 

^ This one apparently only happens on slow Firefoxes, but uh what a bad experience :)

> You are now muted

> You are now unmuted

These are the only four sounds I've managed to get out of the HTML5 frontend for now. I'd vote for not localizing, but instead substituting with sounds, and would be very happy for advice as to how to proceed if I obtained some good sounds?

**Comment by hbruch** [comment]
I'm currently investigating the same question. Not found a solution yet, but some nuggets which might become helpful:

* [jpawlowski/freeswitch-sounds-tts](https://github.com/jpawlowski/freeswitch-sounds-tts) made an effort to generate Freeswitch soundfiles via google/bing tts. I got the sound files generated in German. However, the file names/directory structure don't match any longer to current freeswitch ones (last commit to the project was 5 years ago...)
* /opt/freeswitch/conf/lang/de/vm/tts.xml contains German translations which could be used to generate required sound files
* Another [post from 2014](https://lists.freeswitch.org/pipermail/freeswitch-users/2014-October/108542.html) mentions some configs to apply.

**Comment by ScIT-Raphael** [comment]
Hi @hbruch 

Did you found any working german sounds for freeswitch?

**Comment by mave-git** [comment]
Hi,

I reached to set (8k-sound) german files to BBB (okay, now working the intro conf-alone, conf-muted ...) I also added telephone dialin :-) But when calling, only original english speaking comes. I got, that inside the xml-file for

/opt/freeswitch/conf/dialplan/XYprovider.xml

there is:

`<action application="play_and_get_digits" data="5 5 3 7000 # conference/conf-pin.wav ivr/ivr-that_was_an_invalid_entry.wav pin \d+"/>`

But, 'conference/conf-pin.wav" is picked up from? I don't know. I also don't know which sound rate here is taken. 8000, 16000....?
Otherwise in conference.conf.xml there is 'sound-prefix' defined, but this takes no effect on dialin and speaking conf-pin ...

Anybody knows the freeswitch-mechanism inside BBB?

**Comment by Daedalus3** [comment]
Hi @mave-git ,

you may simply replace the files in /opt/freeswitch/share/freeswitch/sounds/en/us/callie/conference (the subfolders are then named after the bitrate of the files, so be sure to replace all files with the correct bitrate.

**Comment by Cyrille37** [comment]
For several languages, sounds files for BBB conferences are available from previous link https://freeswitch.org/confluence/display/FREESWITCH/Language+Files in folderhttps://files.freeswitch.org/releases/sounds/

For example I've downloaded https://files.freeswitch.org/releases/sounds/freeswitch-sounds-fr-ca-june-8000-1.0.51.tar.gz for french language and it contains conference files like defined in `conference.conf.xml` has shown at https://freeswitch.org/confluence/display/FREESWITCH/Conference+Add+Call+Example

**Comment by mave-git** [comment]
For several languages, sounds files for BBB conferences are available
> from previous link ...

Thanks! I saw such files, but need german sounds. These are not
available ;-)

Regards

Am Dienstag, den 15.12.2020, 12:03 -0800 schrieb Cyrille Giquello:

**Comment by Cyrille37** [comment]
Is there a place where we can find all localized sentences as text ?
- it will be easier to translate files in missing languages
- then create sound file with tts software

**Comment by mave-git** [comment]
Sorry, I didn't wrote it. Yes, I found and used the tts software for a
minimal needed set. It works. Unfortunately, the sounds sometimes sound
technical and the emphasis sometimes takes getting used to. But at
least: useful. 

Am Dienstag, den 15.12.2020, 12:14 -0800 schrieb Cyrille Giquello:

**Comment by Cyrille37** [comment]
I ask for a place (github or...) to store and **share** text and audio files to make easier to contribute (without coding) to this so great software :-)

**Comment by mave-git** [comment]
You're right! I will do that as soon as time and I have learned to use
github for this.

Am Dienstag, den 15.12.2020, 12:27 -0800 schrieb Cyrille Giquello:

**Comment by Daedalus3** [comment]
Hi guys, I translated the audio files to German. You can find the files here:

[https://github.com/Daedalus3/freeswitch-german-soundfiles](https://github.com/Daedalus3/freeswitch-german-soundfiles)

I have no idea how bigbluebutton decides what sound files (language) to play, so as of now replace all files/folders in 

/opt/freeswitch/share/freeswitch/sounds/en/us/callie/conference/

**Comment by sualko** [comment]
> I have no idea how bigbluebutton decides what sound files (language) to play, so as of now replace all files/folders in

@Daedalus3 I created a directory with `mkdir -p /opt/freeswitch/share/freeswitch/sounds/de/de/callie/conference` and put there all your sound files. As a second step you have to set `<param name="sound-prefix" value="$${sounds_dir}/de/de/callie"/>` in `/opt/freeswitch/etc/freeswitch/autoload_configs/conference.conf.xml` under the cdquality profile. Thanks for that great sound pack.

**Comment by Daedalus3** [comment]
Thank you @sualko -that seems to be it! Will add it to the instructions.

**Comment by 1758w** [comment]
@Daedalus3 We changed the whole sound config for freeswitch because the conference.conf.xml doesn't include the dial-in sounds.
If you change `<X-PRE-PROCESS cmd="set" data="sound_prefix=$${sounds_dir}/en/us/callie" />` to `<X-PRE-PROCESS cmd="set" data="sound_prefix=$${sounds_dir}/de/de/callie" />` in `/opt/freeswitch/etc/freeswitch/vars.xml` then the dial-in sounds are also changed.

**Comment by jgribonvald** [comment]
@1758w and other, if you don't succeed: setting the `sound_prefix` into `/opt/freeswitch/etc/freeswitch/vars.xml` of bbb 2.3.13 din't apply the new langage sound if you don't set the variable `sounds_dir`

**Comment by jgribonvald** [comment]
> @Daedalus3 We changed the whole sound config for freeswitch because the conference.conf.xml doesn't include the dial-in sounds.
> If you change `<X-PRE-PROCESS cmd="set" data="sound_prefix=$${sounds_dir}/en/us/callie" />` to `<X-PRE-PROCESS cmd="set" data="sound_prefix=$${sounds_dir}/de/de/callie" />` in `/opt/freeswitch/etc/freeswitch/vars.xml` then the dial-in sounds are also changed.

f you don't succeed: setting the `sound_prefix` into `/opt/freeswitch/etc/freeswitch/vars.xml` of bbb 2.3.13 won't apply the new langage sound if you don't set the variable `sounds_dir`
