### ISSUE TITLE
Raised hand emoji in the users list is not a cute yellow one

### ISSUE THREAD

**Issue by debuglevel** [bigbluebutton/bigbluebutton#18437]
**Describe the bug**
Raised hand emoji in the users list is not a cute yellow one.

**To Reproduce**
1. Raise your hand.

**Expected behavior**
It's cute and yellow like the other reactions
![image](https://github.com/bigbluebutton/bigbluebutton/assets/2401265/e609bf50-14c3-4487-8738-8da290404b77)

**Actual behavior**
It's transparent.

**Screenshots**
![image](https://github.com/bigbluebutton/bigbluebutton/assets/2401265/50cb77c0-6914-4e12-939e-a85e0d1ed4cb)

**BBB version:**
2.7. beta 3

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome 115

**Comment by antobinary** [comment]
Thanks for reporting all these items!
