### ISSUE TITLE
Link in chat not fully parsed

### ISSUE THREAD

**Issue by GhaziTriki** [bigbluebutton/bigbluebutton#18438]
**Describe the bug**
When a send a chat message with an an URL that contains an IP address, the URL is not fully parsed.

**To Reproduce**
1. Send `http://51.75.169.134` to chat or `http://51.75.169.135:9000/`

**Expected behavior**
The full URL should be parsed.

**Actual behavior**
Not the full URL is parsed.

**Screenshots**
![image](https://github.com/bigbluebutton/bigbluebutton/assets/4991088/39b92d7c-754b-4174-b5f1-7acc9d91085c)

**BBB version:**
Tested on BigBlueButton 2.6.11 and 2.7.0-beta.3

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Firefox
 - Version: 115.0.3 (64 bits)

**Comment by antobinary** [comment]
Closed via #19795
