### ISSUE TITLE
Rework flow of toasts of layout changed

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#18444]
![Screenshot from 2023-08-03 12-34-46](https://github.com/bigbluebutton/bigbluebutton/assets/6312397/0272fcfb-727f-4656-8302-84b047f8be5c)

We'd like to emphasize that when clicking Update everyone, any future drag/change of the layout is affecting everyone.

Hit "Update everyone", see toast "auto layout updates enabled"
also see toast"layout updates applied to everyone"
..
Make any layout change, for example increase the size of the webcams area. The moment we propagate the event to others, also show the presenter (i.e. the one triggering the change) a toast "layout updates applied to everyone"
..
if any other change, again
"layout updates applied to everyone"
..
if the presenter clicks on "Update" instead of "Update everyone" show toast "auto layout updates disabled" and since the layout changes are no longer propagated to others, no more toasts "layout updates applied to everyone" on making a change.

---

If "Update everyone" was never used (non presenter case or presenter)
"update"
if layout propagation was never enabled, no toast message "auto layout updates disabled"

**BBB version:**
BigBlueButton 2.7.0-beta.3

**Comment by Arthurk12** [comment]
Commenting on this closed issue to add suggestions to those already made by @gustavotrott  and provide clearer feedback on the layout's state. I think that this modal lacks visual feedback about the current layout pushing state. In 2.6, there was a toggle to control the push layout feature, which communicated its state more effectively. Currently, presenters have to rely on the toast notifications or remember the last state. A toggle button would provide immediate visual feedback on whether the layout is being pushed. Here's how it was in 2.6:
![image](https://github.com/user-attachments/assets/81664e4b-645a-4bed-b652-f4768012396b)


Here’s the current version(3.0) with the toggle: ![layout_prop_op2](https://github.com/user-attachments/assets/d9c6688e-1067-4ee0-8e7c-c228d1160e87)

What do you think? @antobinary @gustavotrott

**Comment by gustavotrott** [comment]
> Here’s the current version(3.0) with the toggle: ![layout_prop_op2](https://private-user-images.githubusercontent.com/32987232/357619813-d9c6688e-1067-4ee0-8e7c-c228d1160e87.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1OTc0MjgsIm5iZiI6MTcyMzU5NzEyOCwicGF0aCI6Ii8zMjk4NzIzMi8zNTc2MTk4MTMtZDljNjY4OGUtMTA2Ny00ZWUwLThlN2MtYzIyOGQxMTYwZTg3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE0VDAwNTg0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRiZWZiNzE3ZDc5NWNkOTFmYWI0OTdlYjBiYzU2NDI1MmFmOWM5NTBhYzk4NjU5NmZjMGE4OGMxZDRhNTM1MDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fq1nFd8Cu5uOVVoggFdPZ-w3nyHH71hDekM0DyeFNbY)
> 
> What do you think? @antobinary @gustavotrott

Fully agreed!
I know there have been some discussions about this modal. It would be helpful to document the decisions in an issue (perhaps in this one), as I've never fully understood the motivation behind removing this toggle. Maybe @antobinary can provide some clarification.
