### ISSUE TITLE
Add visual cue that deskshare applet is tunneling

### ISSUE THREAD

**Issue by bigbluebutton-issue-import** [bigbluebutton/bigbluebutton#1850]
Originally reported on Google Code with ID 1096

```
It would be good to show the presenter that the deskshare is tunneling to set expectation
that the updates might be slow.

```

Reported by `ritzalam` on 2011-12-15 14:39:43

**Comment by ffdixon** [comment]
Closing this issue -- the Java-based desktop sharing no longer works with tunneling.  We're moving to WebRTC screen share for a future release.
