### ISSUE TITLE
[2.6.11] - Whiteboard options dropdown rendering multiple times

### ISSUE THREAD

**Issue by antonbsa** [bigbluebutton/bigbluebutton#18505]
**Describe the bug**
Easily reproducible when resizing presentation (e.g. dev tools)

**Screenshots**
![Screenshot from 2023-08-09 15-07-22](https://github.com/bigbluebutton/bigbluebutton/assets/56703993/8f7299af-9faf-46f8-ac70-cc356c3619f7)

![Screenshot from 2023-08-09 15-07-44](https://github.com/bigbluebutton/bigbluebutton/assets/56703993/43f9272f-217c-4d8b-a830-d4b126329df0)

**Comment by NextThread** [comment]
hey, I'd like to work on this issue
