### ISSUE TITLE
Students not ever getting a join button for BBB sessions

### ISSUE THREAD

**Issue by lauriehuber** [bigbluebutton/bigbluebutton#18508]
**Describe the bug**
We set up our BBB class sessions for students using the Moodle API through a BBB host. Students are required to wait for the moderator before they can join.  Yesterday, when students tried to join a session, they got a perpetual "Waiting for Moderator to Join" message.  The moderators had joined the sessions already, but the system did not ever recognize that they were there and produce the join button.  The only way that we could make it possible for students to join was to add a specific Student role to the session set up and deem them to be moderators ( not a long-term workable solution).

**To Reproduce**
1. Go to Course with class sessions
2. Click on the BBB session for the appropriate date
3. Wait for join button

**Expected behavior**
When the above steps are followed, students usually receive a join button which they click.  They go into the room 'lobby' and wait for permission to enter.  The moderator gives permission and the student enters the classroom.

**Actual behavior**
The students logged in and went to their course with the class sessions.  They found the correct session for the date and clicked on it.  The "Waiting for Moderator' message appeared and never changed to a Join button even though the moderators were in the classrooms well before students are allowed to join. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Browser [e.g. Chrome,]
 - Version 115.0.5790.171

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy 
 - OS: ?
 - Browser [e.g. stock browser, Chrome]
 - Version 

**Additional context**
Once I manually set students up as moderators in the settings for the session they could join the room.

**Comment by antobinary** [comment]
Hi @lauriehuber 

Could you please confirm what version of BigBlueButton you're using? This is typically visible in the client top-right-hand corner, three-dots menu -> About

**Comment by lauriehuber** [comment]
Hi Anton

We are on version 2.6.11

Thanks

Laurie

**Comment by antobinary** [comment]
> even though the moderators were in the classrooms well before students are allowed to join.

Are you able to reproduce this on your setup? What does the moderator see in the waiting users panel? Do they approve the users but still the student's are not redirected? What is the guest policy of your meeting?

![Screenshot from 2023-08-10 13-01-27](https://github.com/bigbluebutton/bigbluebutton/assets/6312397/e361d455-2af6-4370-b15c-6ccabfbca270)

![Screenshot from 2023-08-10 13-01-40](https://github.com/bigbluebutton/bigbluebutton/assets/6312397/abc72c30-5105-4763-8c91-f91a475c4b47)

**Comment by lauriehuber** [comment]
Hi Anton

Students are not getting to the waiting room.

The moderators are able to sign in as normal. They always do that 5 minutes
before students can sign-in.

It seems like the system is not acknowledging that the moderators have
opened the room because when students click on the link in their course all
they get is a Waiting For Moderator message. No Join button ever appears.

Thanks for your help.

Laurie

**Comment by antobinary** [comment]
I'll try to guess the answers to the questions I asked above the screenshots.
If your guest policy is "ask moderator" (see above), moderators are asked first to confiem a given student should be let in. See the screenshot below. Moderator on the left hand side, viewer (student) on the right.

![Screenshot from 2023-08-10 15-04-15](https://github.com/bigbluebutton/bigbluebutton/assets/6312397/b3b3a56e-dc47-4800-985b-fc8e30bdf211)


Notice the extra panel visible to the moderator,
![Screenshot from 2023-08-10 15-04-30](https://github.com/bigbluebutton/bigbluebutton/assets/6312397/5c091c32-02dd-4f06-b248-e79f2b384cb4)


The moderator has to let students in, just being present in the meeting early is not enough.

Hope this helps!

**Comment by lauriehuber** [comment]
Sorry. I missed those questions:)

Your guesses are correct.

**Comment by lauriehuber** [comment]
The moderators know to allow students in. They have been working with BBB
for a year now.

This week, students stopped  showing up in the waiting room, so moderators
could not give anyone permission.

Our host company did a version upgrade about 10 days ago and since then,
issues began to occur. Frequent failure of the audio ( shows you as green,
but the audio is not actually working). This week it is the failure of
students to get in.

The host company has done another upgrade last night which they hope will
fix things. I will know for sure in 15 minutes.

Thanks

Laurie

**Comment by antobinary** [comment]
Feel free to reach out if assistance is needed. Otherwise - sounds like your service provider figured it out.
