### ISSUE TITLE
reactions: clicking a reaction again does not clear it in the reaction-bar

### ISSUE THREAD

**Issue by debuglevel** [bigbluebutton/bigbluebutton#18560]
I'm not familiar with the terminology yet. Therefore just some clarifications:

I'll call this a reaction bar (in contrast to the "users list" where the reactions will be shown):
![image](https://github.com/bigbluebutton/bigbluebutton/assets/2401265/b1f8b6ba-4646-4b43-b2c4-4bde7336e807)

I'll call this a reaction: 
![image](https://github.com/bigbluebutton/bigbluebutton/assets/2401265/06df7dca-f06c-41ea-97d9-87520d83d1cb)

**Describe the bug**
If I click on a reaction *again* to "revoke" it, the reaction is cleared from the users list, but not from the reaction bar.

**To Reproduce**
1. Click on a reaction.
2. The reaction has a blue background to state that it is active.
3. Click on the reaction again.
4. The reaction still has a blue background.

**Expected behavior**
The background is removed.

**Actual behavior**
The background stays.

**Screenshots**
Unfortunately my screen recorder does not make it too easy to see when I actually clicked. But I think you'll get it.
![chrome_2023-08-16_11-48-10](https://github.com/bigbluebutton/bigbluebutton/assets/2401265/bf98505e-6b23-4c15-89f0-d74844f4db7e)

**BBB version:**
2.7. rc 1

**Comment by ramonlsouza** [comment]
Looks like this issue has been fixed... Are you still able to reproduce it (on 2.7.0)?

https://github.com/bigbluebutton/bigbluebutton/assets/3728706/926a39c7-b637-4492-8daa-7e354b0e63c2
