### ISSUE TITLE
Allow API create call to override settings.yml parameters for individual meetings

### ISSUE THREAD

**Issue by TiagoJacobs** [bigbluebutton/bigbluebutton#18588]
Background:

The `settings.yml` file in the BBB HTML5 client dictates the behavior and appearance of various features across all meetings on a BBB server. At present, any changes to this file apply universally.

Proposal:

To provide finer-grained control and to allow for flexibility for 3rd party integrations, I propose that we allow override parameters to be passed through the create call of the BBB API. This would enable specific settings to be defined on a per-meeting basis without affecting global server settings.

Benefits:

- Flexibility for 3rd Party Integrations: Third-party platforms and integrations might have varying requirements. Allowing overrides can cater to specific use-cases without the need to maintain separate BBB servers with different configurations.
- Enhanced User Experience: Meeting creators can tailor the experience for their participants, whether it's enabling/disabling specific features or tweaking visual elements.
- Server-Wide Defaults Remain Intact: While providing flexibility, the global server defaults in settings.yml remain unaffected unless explicitly overridden.

Considerations:

- Security: Let's add a key in `bigbluebutton.properties` to configure if this override is allowed (`allowOverrideClientConfigurationOnCreateCall=true/false`)

- Backward Compatibility: The API change should be backward-compatible. An extra module in the XML payload.

Example call:
```xml
<modules>
    <!-- presentation pre-upload  -->
    <module name="presentation"></module>

    <!-- client configuration override -->
    <module name="client">
        <config-override>
            <![CDATA[
            {
                "app": {
                    "appName": "Test",
                    "helpLink": "https://imdt.com.br",
                }
            }
            ]]>
        </config-override>
    </module>
</modules>

```

**Comment by TiagoJacobs** [comment]
This will also allow us to specify plugins when creating a meeting for an end-to-end test (for instance to create a test of this type of  #17994) 

/cc @antonbsa

**Comment by gustavotrott** [comment]
In order to make it easier for 3rd party integrations, I suggest to name the module as `clientSettingsOverride` and remove the second level `<config-override>`.
The Xml will look like this example:

```xml
<modules>
   <module name="presentation"></module>
   <module name="clientSettingsOverride">
         <![CDATA[
         {
            "public": {
               "kurento": {
                  "wsUrl": "wss://test.bigbluebutton.org//bbb-webrtc-sfu"
               },
               "media": {
                  "sipjsHackViaWs": false
               },
               "app": {
                    "appName": "Test",
                    "helpLink": "https://www.bigbluebutton.org",
                    "autoJoin": false,
                    "askForConfirmationOnLeave": false,
                    "userSettingsStorage": "localStorage",
                    "defaultSettings": {
                     "application": {
                        "overrideLocale": "en"
                     }
                    }
                }
            }
         }
         ]]>
   </module>
</modules>
```

Using only one level will keep things simpler.
