### ISSUE TITLE
getRecordings api endpoint breaking change in version 2.6

### ISSUE THREAD

**Issue by lunika** [bigbluebutton/bigbluebutton#18606]
**Describe the bug**

In BBB 2.5, in the `getRecordings` API response, the url for the `video` playback format was effectively a link to a mp4 file:

```xml
<response>
  <returncode>SUCCESS</returncode>
  <recordings>
    <recording>
      <recordID>xxxxx</recordID>
      <meetingID>xxxx</meetingID>
      <internalMeetingID>xxxx</internalMeetingID>
      <name>Test description</name>
      <published>true</published>
      <state>published</state>
      <startTime>1690191327912</startTime>
      <endTime>1690191377418</endTime>
      <participants>1</participants>
      <metadata>
        <analytics-callback-url>https://analytics.co</analytics-callback-url>
      </metadata>
      <playback>
        <format>
          <type>presentation</type>
          <url>https://bigbluebutton.domain/playback/presentation/2.3/xxxx</url>
          <length>0</length>
          <preview>
            <images>
              <image alt="Prague - 12/2022 2" width="176" height="136">https://bigbluebutton.domain/presentation/xxx/presentation/xxx/thumbnails/thumb-3.png</image>
            </images>
          </preview>
        </format>
        <format>
          <type>video</type>
          <url>https://bigbluebutton.domain/presentation/xxx/meeting.mp4</url>
          <length>0</length>
          <preview>
            <images>
              <image alt="Prague - 12/2022 2" width="176" height="136">https://bigbluebutton.domain/presentation/xxx/presentation/xxx/thumbnails/thumb-3.png</image>
            </images>
          </preview>
        </format>
      </playback>
    </recording>
  </recordings>
</response>
```

In BBB 2.6 the `getRecordings` API response does not contains an url to a mp4 file for the `video` playback format. Instead, the url target a html file containing a video player:

```xml
<response>
  <returncode>SUCCESS</returncode>
  <recordings>
    <recording>
      <recordID>xxx</recordID>
      <meetingID>xxx</meetingID>
      <internalMeetingID>xxx</internalMeetingID>
      <name>test recordings</name>
      <published>true</published>
      <protected>true</protected>
      <state>published</state>
      <startTime>1690360921257</startTime>
      <endTime>1690361011675</endTime>
      <participants>1</participants>
      <metadata>
      </metadata>
      <playback>
        <format>
          <type>presentation</type>
          <url>https://bigbluebutton.domain/recording/xxx/presentation</url>
          <length>1</length>
        </format>
        <format>
          <type>video</type>
          <url>https://bigbluebutton.domain/recording/xxx/video</url>
          <length>1</length>
        </format>
      </playback>
    </recording>
  </recordings>
</response>
```

It seems you introduce a new format and you use it in the video format instead of creating a new format in the playback section.
The html is always the same template : 

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>test recordings</title>
    <link rel="stylesheet" href="css/normalize.css">
    <link rel="stylesheet" href="video-js/video-js.min.css">
    <link rel="stylesheet" href="css/video.css">
    <script src="video-js/video.min.js"></script>
    <script src="js/popcorn-complete.min.js"></script>
    <script src="js/popcorn.chattimeline.js"></script>
    <script src="js/video.js"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>
  <body>
    <header>
      <h1>test recordings</h1>
    </header>

    <main>
      <div id="main-area">
        <div id="error-area">
          <p id="firefox-format-warning" style="display:none">Firefox on your operating system does not currently support the video format used in this recording. Please try a different browser, such as Safari or Chrome.</p>
        </div>
        <div id="video-area">
          <video id="video" class="video-js vjs-fill vjs-default-skin vjs-big-play-centered" controls>

              <source src="video-0.m4v" type="video/mp4">


          </video>
        </div>
      </div>
      <div id="chat-area" >
        <h2 class="visually-hidden">Chat Messages</h2>
        <input type="checkbox" name="exposechat" id="exposechat" value="exposechat" class="visually-hidden" checked="checked">
        <label for="exposechat" class="visually-hidden">Read chat messages</label>
        <div id="chat" aria-live="polite" role="region" area-label="Chat Messages"></div>
      </div>
    </main>

    <footer>Recorded with <a href="http://bigbluebutton.org">BigBlueButton</a>.</footer>
  </body>
</html>
```

This break integration with third party application using the Bigbluebutton API.

**Expected behavior**

Have a consistent API between minor version. In the `video` format we expect to have a video file in the url. Not a HTML file.

**Comment by antobinary** [comment]
Hi @lunika 

Thanks for reporting this!
BigBlueButton introduced the MP4 video format of recordings in version 2.6 https://docs.bigbluebutton.org/new-features#recording-in-video-format

Perhaps you were using an external solution like https://github.com/danielpetri1/bbb-recording-exporter ?

**Comment by lunika** [comment]
Thanks for your answer.

We are using scalelite in front of big blue button. 

So there is no solution to have the video file (no matter if it's mp4 or webm or something else) in the API response like before ?

**Comment by antobinary** [comment]
@lunika what version of Scalelite are you using?

**Comment by lunika** [comment]
The last one

**Comment by lunika** [comment]
@antobinary Do you confirm this is a regression and we should have a video file in the response API ? Or is it a misconfiguration from our side ?
Should I report the same issue on the scalelite repo ? 

Thanks

**Comment by hostbbb** [comment]
I think this video in 2.5 was a custom modification?   nor in the standard 2.5 release if i had to guess.
<format>
          <type>video</type>
          <url>https://bigbluebutton.domain/presentation/xxx/meeting.mp4</url>

dont think video format officially existed.

but you can make a change easily in the new video format publishing script to provice the url to .m2v instead of the player.

**Comment by lunika** [comment]
> but you can make a change easily in the new video format publishing script to provide the url to .m2v instead of the player.

Can you provide an exemple or a link to the documentation related to this feature please ?

**Comment by lunika** [comment]
@hostbbb I can confirm you that we have **no** custom modification in 2.5.

And we are using BBB 2.5.6 with scalelite 1.3.4

**Comment by kepstin** [comment]
BigBlueButton 2.5 did not include a recording format that generated mp4 files, or links to mp4 files. If you had mp4 files, you *must* have been using a custom modification.

The "video" recording format included in BigBlueButton 2.6 does not link directly to the mp4 file, because the video only includes presentation area, webcams, and deskshare, but not chat - chat is handled by an html/javascript player.

**Comment by hostbbb** [comment]
> > but you can make a change easily in the new video format publishing script to provide the url to .m2v instead of the player.
> 
> Can you provide an exemple or a link to the documentation related to this feature please ?

https://github.com/bigbluebutton/bigbluebutton/blob/develop/record-and-playback/video/scripts/process/video.rb#L276

this code will create the link in metadata.xml that getRecordings returns.      So you can directly reference the .m2v so this browser plays the video..   Like Calvin.  video will not include the chat messages,  but audio/screenshare/whiteboard will appear.

**Comment by lunika** [comment]
Thanks for the answers.

On BBB 2.5 we have `bbb-exporter` installed indeed, I didn't know that. This explain why we have the `mp4` link.

As I understand, this project is not maintain anymore and is replaced by `bbb-playback-video`, so we have to use this one with BBB 2.6 but it has less feature than `bbb-exporter`. Like the chat integration as you said. And this is annoying because a video can not be downloaded to be watch offline for example. Or worst, it breaks integration in third party applications, so IMHO this is still a regression. And there is no real difference now between a `presentation` and a `video`. This is not a `video` anymore as we need to load a full webpage to read it.
