### ISSUE TITLE
[2.6, 2.7] Quick zoom by mouse wheel breaks the presentation

### ISSUE THREAD

**Issue by hiroshisuga** [bigbluebutton/bigbluebutton#18645]
**Describe the bug**

When a presenter zoom in and out quickly by the mouse wheel, the movement jerks and the zoom rate sometimes does not returns 100% by the wheel, or does not change smoothly (the rate increases in a moment even when the wheel rolls downward). 

**To Reproduce**
1. Zoom in and out just quickly by the mouse wheel

**Screenshots**

https://github.com/bigbluebutton/bigbluebutton/assets/45039819/77012136-61bf-4a17-ad50-ece1040808ca

**BBB version:**
tested on test26 and test27 servers.

**Desktop (please complete the following information):**
 - MacOS, Windows10
 - Brave

**Comment by antobinary** [comment]
Thank you for reporting!
