### ISSUE TITLE
Three dots whiteboard button does not hide even when set to hide

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#18663]
**Describe the bug**
Regardless of the value of `Auto Hide Whiteboard Toolbars` in the Settings, the button does not hide.

**To Reproduce**
1. Go to Settings
2. Enable `Auto Hide Whiteboard Toolbars` (should already be enabled)

**Expected behavior**
The button hides unless your mouse is over the whiteboard

**Actual behavior**
The button remains visible

**Screenshots**
![Screenshot from 2023-08-29 11-54-34](https://github.com/bigbluebutton/bigbluebutton/assets/6312397/9d961e3b-35c7-4957-8336-e9f1e21fc3ad)

**BBB version:**
BigBlueButton 2.7.0-rc.1

**Comment by ramonlsouza** [comment]
not reproducible on latest 2.7 release (2.7.4)
