### ISSUE TITLE
shared notes not starting (mixed block)

### ISSUE THREAD

**Issue by himpierre** [bigbluebutton/bigbluebutton#18679]
**Describe the bug**
Hello Devs.

When opening the shared notes tab the editor is not opening as expected. It just happens nothing so I started the web console to have closer look. Firefox is blocking the auth request with "Mixed Block".

Pads URL in /usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml is http://my.ip/pad

So I suppose this is the problem? But Changing this to https does not change anything.

**To Reproduce**
1. Go to shared notes
2. Tab opens
3. Nothing happens

**Expected behavior**
Editor should open

**Actual behavior**
Edit does not open

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Firefox
 - Version 116

**Additional context**
BigBlueButton 2.6.12

cheers, t.

**Comment by himpierre** [comment]
```
Mixed Content: The page at 'https://letsmeet.mydomain.de/html5client/join?sessionToken=ecf3ug7as6iztkua' was loaded over HTTPS, but requested an insecure frame 'http://xx.xx.xx.xx/pad/auth_session?padName=g.Q3z3RFioubhBZydc$notes&sessionID=s.d3061d2388e34a38c0f9bd2a252ee5af&lang=en&rtl=false&sessionToken=ecf3ug7as6iztkua'. This request has been blocked; the content must be served over HTTPS.
```

**Comment by hostbbb** [comment]
does your url have a domain name or just an IP address.    https needs to resolve cert at FQDN?

**Comment by himpierre** [comment]
I have a regular domain with a valid ssl cert. Let me try domainame in that setting.

Am 31. August 2023 12:27:32 MESZ schrieb Stephen ***@***.***>:
>does your url have a domain name or just an IP address.    https needs to resolve cert at FQDN?
>

**Comment by himpierre** [comment]
Thanks @hostbbb Setting url to https://my.domain.name/pad solves the problem.

cheers, t.
