### ISSUE TITLE
[2.7.0rc2] Zoom in and out of presentation broken

### ISSUE THREAD

**Issue by schrd** [bigbluebutton/bigbluebutton#18688]
**Describe the bug**

The zoom level indicator is not in sync with the real zoom level of the slides.

**To Reproduce**
1. Start a meeting
2. wait until default presentation has converted
3. draw something on slide 1
4. zoom in to something like 142% (by mouse wheel or clicking on the zoom button, doesn't matter)
5. switch to slide 2. The slide is shown in 100% but the zoom level indicator shows 142%
6. zoom out → Slide zooms to the level shown in zoom level indicator
7. zoom out on slide 2 to 100%
8. switch back to slide 1, zoom level shown in the indicator is 100%, but real zoom is 142%

**Expected behavior**
The zoom level of the slide and the indicator should be in sync with the slide.

**BBB version:**
2.7.0 rc2

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Firefox
 - Version 102 ESR

**Comment by KDSBrowne** [comment]
The fix for this on `2.6` was part of #18653

**Comment by antobinary** [comment]
Will be carried to BBB 2.7 as part of 2.7.1 (likely in 2 weeks)
