### ISSUE TITLE
Snapshot of slide shows only annotations but no image

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#18739]
**Describe the bug**
Reported on https://groups.google.com/g/bigbluebutton-users/c/OmpGuQwxwgM/m/nC4dLldCBAAJ
The option to save a snapshot of the slide produces an odd result -- annotations on top of a missing image.

**To Reproduce**
(I can't reproduce the issue yet)

**Expected behavior**
![Screenshot Presentation Fullscreen_what should be visible (1)](https://github.com/bigbluebutton/bigbluebutton/assets/6312397/17c76a66-076a-4fdc-9446-9fa007b8a2c7)

**Actual behavior**
![Snapshot of current slide_what is visible](https://github.com/bigbluebutton/bigbluebutton/assets/6312397/16dca76a-27d1-4b47-8b9f-3f3f3d7cc89c)

**BBB version:**
BigBlueButton 2.6.11

**Comment by ben-ba** [comment]
seems that poppler-utils is missing, no error thrown

see: https://github.com/bigbluebutton/bigbluebutton/issues/19703

**Comment by yossi-a3d** [comment]
Is there anything new on this ?   I installed version 2.7.15 and the problem exists. poppler-utils is installed and yet the bug exists.

**Comment by playernine** [comment]
I have this bug too. It only happens on google Chrome. With Firefox it works fine.
```
apt list --installed|grep poppler

libpoppler97/focal-updates,focal-security,now 0.86.1-0ubuntu1.4 amd64 [installed,automatic]
poppler-data/focal,now 0.4.9-2 all [installed,automatic]
poppler-utils/focal-updates,focal-security,now 0.86.1-0ubuntu1.4 amd64 [installed,automatic]
```

**Comment by antobinary** [comment]
This looks to be a new/different issue likely possibly related to a recent change in browsers (?!) Seems to be working well on BBB 3.0beta which had this reimplemented differently. We'll see if we can backport this to 2.7.

Cross referencing to https://groups.google.com/g/bigbluebutton-setup/c/cHL9PJa179U

**Comment by antobinary** [comment]
BBB 2.7.16 will contain the patch #21747
