### ISSUE TITLE
[2.7] Grid mode display also in automatic layout (when presentation is disabled)

### ISSUE THREAD

**Issue by jacotec** [bigbluebutton/bigbluebutton#18735]
The grid mode in 2.7 is an absolutely awesome feature for video conferences to see also audio-only or dial-in users as a tile.

Unfortunately it does not work in "automatic layout" mode, which is a pity. The automatic mode is the most used mode and default in my installations as it's perfect for video conferences with occasional screen sharing as no moderator needs to switch layouts manually when a presentation/screensharing is activated during the conference.

I'd highly appreciate to have the grid mode also activated in automatic mode. To avoid having "unimportant" tiles with no webcam in case of a presentation, when the space for the webcams becomes limited, the grid mode can be active only in case no presentation / screen sharing is active.

**Comment by antobinary** [comment]
Thank you for the feedback! For now we plan on keeping it as a separate layout. You can also change the layout locally (for your client only) without propagating it to others.

We are considering adding some sorting options for the grid in the future and possibly this could fit in those changes.

**Comment by jacotec** [comment]
Hi @antobinary ,

the local change is correct, but I want to keep it as simple as possible for guest participants and other users without the need to "explain" the layout options ... especially for other useres which are not that "nerdy" to remember this after weeks or months ;-)

Therefore the "automatic layout" is preferred, where everything changes automatically if someone shares his screen without having someone in the conference who know what a "layout" is.

And as a result it would be great in my opinion of the grid view would be active also in automatic mode, when the "automatism" has switched to video only in case of no presentation /screen sharing. It won't harm anything :-)
