### ISSUE TITLE
BBB installation problems (yq)

### ISSUE THREAD

**Issue by root707** [bigbluebutton/bigbluebutton#18747]
**Describe the bug**
New installation of BBB on Ubuntu 22.04 (VPS)

**Installation type**
bbb-install script (2.7)

**Firewall and IP address type**
OK

**Console output**
The following packages have unmet dependencies:
 bbb-config : Depends: bbb-html5 but it is not going to be installed
              Depends: bbb-playback-presentation but it is not going to be installed
              Depends: bbb-playback but it is not going to be installed
              Depends: bbb-freeswitch-core but it is not going to be installed
              Depends: bbb-fsesl-akka but it is not going to be installed
              Depends: yq (>= 3) but it is not installable
              Depends: yq (< 4) but it is not installable
E: Unable to correct problems, you have held broken packages.

**Additional context**
when i try to install them one by one goning down this is the last result

The following packages have unmet dependencies:
 bbb-record-core : Depends: yq (>= 3) but it is not installable
                   Depends: yq (< 4) but it is not installable
E: Unable to correct problems, you have held broken packages.

**Comment by antobinary** [comment]
Hi @root707 

Any chance you could copy-paste here the command you used for the installation? Feel free to mask the domain/email, I'm more interested in the script url and parameters passed. Thanks!

**Comment by debuglevel** [comment]
@root707 
BBB 2.7 officially only supports Ubuntu **20.04**. It's usually the best to stick really really thigh to this recommendation :)

**Comment by antobinary** [comment]
^ That said, next major version runs on Ubuntu 22.04 (from branch 'develop' right now). Lots of things had to be adjusted and almost all Ubuntu 22.04 related issues have been resolved, so in the near future you'll be able to use 22.04!

**Comment by naeemjawaid** [comment]
I have the same error. I'm running Ubuntu 20.04 and installing BBB 2.7. How can I solve this?

**Comment by ffdixon** [comment]
@naeemjawaid Can you confirm your installing on a clean (no previous software installed) Ubuntu 20.04 server.  The `bbb-install.sh` installation script should complete (just tested it myself).
