### ISSUE TITLE
bbb-playback-video     重点词汇 4/5000 传统翻译模型 通用场景 Installation failure

### ISSUE THREAD

**Issue by Song0013** [bigbluebutton/bigbluebutton#18744]
![f0e17348d25aa5b1e324c60418d9ac4](https://github.com/bigbluebutton/bigbluebutton/assets/18046591/c50bbdb4-ddfb-4ac3-a8fd-20894ebe0547)

**Comment by Song0013** [comment]
Package not found

**Comment by Song0013** [comment]
/etc/apt/sources.list.d   Is it my source？

**Comment by Song0013** [comment]
![1694163377749](https://github.com/bigbluebutton/bigbluebutton/assets/18046591/98cf6721-eb2d-482e-acdf-7c42a48526f6)

**Comment by Song0013** [comment]
BigBlueButton Server 2.5.8 (3150)

**Comment by antobinary** [comment]
`bbb-playback-video` was introduced in BigBlueButton 2.6. You are still on 2.5 which is no longer supported. Please upgrade.

**Comment by Song0013** [comment]
> `bbb-playback-video`BigBlueButton 2.6 中引入。您仍在使用不再受支持的 2.5。请升级。

My upgrade command:
wget -qO- https://ubuntu.bigbluebutton.org/bbb-install-2.6.sh | bash -s -- -v focal-260 -s bbb-test.cn  -w -g


An error occurred during the upgrade :
![a6956abc8681ce5ecccdf04de693218](https://github.com/bigbluebutton/bigbluebutton/assets/18046591/b5467d57-573b-4392-8fc4-b75ebc7b0d46)

/opt/freeswitch/log/freeswitch.log :
![1694684312076](https://github.com/bigbluebutton/bigbluebutton/assets/18046591/e44586d0-5028-46e4-9113-5ebbbb5c35f5)

Brother, how should I solve
