### ISSUE TITLE
BBB 2.6 - send presentation from breakout rooms to chat is missing some input

### ISSUE THREAD

**Issue by lonesomewalker** [bigbluebutton/bigbluebutton#18746]
**Describe the bug**
Sending the modified presentation with annotations to chat produces not the desired output. Parts are missing.

**To Reproduce**
Default BBB installation, either by apt or by bbb-install.sh to verify

**Expected behavior**
All the anotations should be available on the presentation

**BBB version:**
BigBlueButton continually evolves. Providing the version/build helps us to pinpoint when an issue was introduced.
Example:
$ sudo bbb-conf --check | grep BigBlueButton
BigBlueButton Server 2.6 latest (also before)

**Desktop (please complete the following information):**
 - OS: independent
 - Browser independent

**Comment by lonesomewalker** [comment]
Maybe duplicate to #17927 

```
root@bbbtest ~ # dpkg -l | grep bbb-export-annotations
ii  bbb-export-annotations                1:2.6-27                          amd64        BigBlueButton Export Annotations
```

```
root@bbbtest ~ # dpkg -l | grep libmagickcore
ii  libmagickcore-6.q16-6:amd64           8:6.9.10.23+dfsg-2.1ubuntu11.9    amd64        low-level image manipulation library -- quantum depth Q16
ii  libmagickcore-6.q16-6-extra:amd64     8:6.9.10.23+dfsg-2.1ubuntu11.9    amd64        low-level image manipulation library - extra codecs (Q16)
```

**Comment by antobinary** [comment]
Hi @lonesomewalker 
Are you able to reproduce this on test26.bigbluebutton.org or test27.bigbluebutton.org ?
Could you elaborate on the steps? Were the missing parts the first ones or last ones or random middle parts drawn on the whiteboard? Did it happen on all breakouts? Did the breakouts end normally or were ended via end all breakouts? What tools were used - just pencil or sticky notes or...? Do you notice if all missing annotations were written by the same user?

I tried reproducing on test27.bigbluebutton.org with no success -- I wrote 1,2,...7 with pencil, all appeared correctly...

**Comment by antobinary** [comment]
This was likely resolved in https://github.com/bigbluebutton/bigbluebutton/issues/20690 in BBB 2.7.
