### ISSUE TITLE
Download Slide - Unable to load fonts

### ISSUE THREAD

**Issue by Davka** [bigbluebutton/bigbluebutton#18750]
**Describe the bug**
When downloading the current slide, errors appear in the browser console stating that various fonts cannot be loaded.

**To Reproduce**
1. Start meeting
2. Open browser console
3. Click in the whiteboard on "Snapshot of current slide"
5. See error

**Screenshots**
<img width="2545" alt="Bildschirmfoto 2023-09-11 um 13 15 26" src="https://github.com/bigbluebutton/bigbluebutton/assets/1117697/27eacbc0-f54a-4cb2-92b6-22de28345b54">

**BBB version:**
BigBlueButton Server 2.7.1

**Desktop (please complete the following information):**
 - latest chrome

**Comment by antobinary** [comment]
@antonbsa let's try reproducing on 3.0 please

**Comment by antonbsa** [comment]
Couldn't see any error log when downloading the snapshot of the current slide (`v3.0-alpha-7`)
