### ISSUE TITLE
Minimizing presentation produces an error

### ISSUE THREAD

**Issue by Davka** [bigbluebutton/bigbluebutton#18751]
**Describe the bug**

When minimizing the presentation, the following errors appears in the browser console

```
lockdown-install.js:1 null
(anonymous) @ lockdown-install.js:1
error (async)
(anonymous) @ lockdown-install.js:1
repairIntrinsics @ lockdown-install.js:1
(anonymous) @ lockdown-install.js:1
(anonymous) @ lockdown-run.js:4
Show 5 more frames
Show less


Uncaught TypeError: Cannot destructure property 'stack' of 'e.error' as it is null.
    at 02532504e93f70983d0dde9b1a0ebab27ebbc5eb.js?meteor_js_resource=true:680:1656009
```

**Screenshots**
<img width="2553" alt="Bildschirmfoto 2023-09-11 um 13 24 07" src="https://github.com/bigbluebutton/bigbluebutton/assets/1117697/be252224-091f-41f1-83da-4edc1bb05a9e">

**BBB version:**

BigBlueButton Server 2.7.1

**Desktop (please complete the following information):**
 - latest chrome

**Comment by Davka** [comment]
Hi @antobinary 

I can still reproduce it, including on demo.bigbluebutton.org. I just started the meeting and minimized the presentation.

**Comment by antobinary** [comment]
@antonbsa let's try reproducing on 3.0 please

**Comment by antonbsa** [comment]
Hi @Davka 

I wasn't able to reproduce this behavior in a 3.0 session, tried it in many different scenarios. I could only see the same error log in a 2.7 session when minimizing the presentation as attendee, however, no crash. Did you have any settings different than the default that might be causing it?
