### ISSUE TITLE
Add delay before calculating num of unread messages

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#18766]
**Describe the bug**
When I have the public chat open and someone sends a new public message, I see the red circle for new unread messages in the public chat in the panel (top left hand corner) for a fraction of the second. This is likely unnecessary as the messages are all read (or open)

**BBB version:**
BigBlueButton continually evolves. Providing the version/build helps us to pinpoint when an issue was introduced.
Example:
$ sudo bbb-conf --check | grep BigBlueButton
BigBlueButton 2.8 (3.0)

**Comment by Scroody** [comment]
The bug appears to not be reproducible anymore - When closed, the chat takes a little interval before showing the unread notification, and when opened doesn't show it at all. In case anyone has any extra step do test it just let me know and I'll re-test it.

https://github.com/user-attachments/assets/b9e47dcf-4b4f-4217-887f-ea994027e10c
