### ISSUE TITLE
upgrade 2.6 fail

### ISSUE THREAD

**Issue by Song0013** [bigbluebutton/bigbluebutton#18784]
My upgrade command:
wget -qO- https://ubuntu.bigbluebutton.org/bbb-install-2.6.sh | bash -s -- -v focal-260 -s bbb-test.cn -w -g

An error occurred during the upgrade :
![a6956abc8681ce5ecccdf04de693218](https://github.com/bigbluebutton/bigbluebutton/assets/18046591/1d420813-1b58-4195-8d6b-bb166f15a147)

/opt/freeswitch/log/freeswitch.log :
![1694743665161](https://github.com/bigbluebutton/bigbluebutton/assets/18046591/c2edaed9-1e64-41f2-b427-baffe0cb69f7)

Brother, how should I solve

**Comment by antobinary** [comment]
I see this is an old question but I'll take the opportunity to link to BigBlueButton's setup google group with thousands of members. This is the best place to search for solutions to setup issues you may have, or in case you're not finding a similar thread, to start one. https://groups.google.com/g/bigbluebutton-setup
If there is a confirmed problem with the installation, we'll open an issue here and track it until solved. Hope you found the above forum early on.
