### ISSUE TITLE
Doorbell stops ringing after ringing once

### ISSUE THREAD

**Issue by fabio-garcia** [bigbluebutton/bigbluebutton#18802]
**Describe the bug**
Using guest policy to ask moderators, a doorbell rings when a user joins session. After first ringing, moderators stop being notified by the audio cue when new users join after they rejoined the conference.

**To Reproduce**
1. Join session as moderator, using guest policy to ask moderator (set guestPolicy=ASK_MODERATOR)
2. Have a user join, doorbell rings
3. Moderator then leaves session
5. Moderator rejoin session
6. Doorbell rings no more for new users joining. Even after accepting/rejecting previous user, respecting the 10 seconds threshold implemented in #11544

**Expected behavior**
The audio and toast notification should pop (is the 10s threshold configurable?).

**Actual behavior**
No doorbell sound is heard for the rest of the session for rejoining moderators.

**BBB version:**
BigBlueButton 2.7.0
goes all the way back to
BigBlueButton 2.5.4

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Microsoft Edge, Firefox
 - Both latest version

**Additional context**
Problem goes all the way back to 2.5.4 on our production servers. Tested on demo.bigbluebutton.org and it also happens there. It does not happen on 2.4.9.

**Comment by fabio-garcia** [comment]
Could be related to #18631.

**Comment by antobinary** [comment]
Addressed via https://github.com/bigbluebutton/bigbluebutton/issues/19011
