### ISSUE TITLE
[2.7.1] no audio after update to 2.7.1 from 2.7.0 (Error: write EPIPE)

### ISSUE THREAD

**Issue by himpierre** [bigbluebutton/bigbluebutton#18813]
**Describe the bug**

After upgrading to 2.7.1 audio is not working anymore. Audio Test succeeds but when entering the room a message pops up asking me to make sure I have set the right permissions to the media device. Shortly after that I get the "connection timeout ice 1010 error). The Logs show:

```
Sep 20 08:20:32 hello bbb-webrtc-sfu[11485]: {"error":{"code":"EPIPE","errno":-32,"message":"write EPIPE","stack":"Error: write EPIPE\n    at afterWriteDispatched (node:internal/stream_base_commons:160:15)\n    at writeGeneric (node:internal/stream_base_commons:151:3)\n    at Socket._writeGeneric (node:net:962:11)\n    at Socket._write (node:net:974:8)\n    at writeOrBuffer (node:internal/streams/writable:392:12)\n    at _write (node:internal/streams/writable:333:10)\n    at Writable.write (node:internal/streams/writable:337:10)\n    at Connection.send (/usr/local/bigbluebutton/bbb-webrtc-sfu/node_modules/modesl/lib/esl/Connection.js:183:21)\n    at Connection.sendRecv (/usr/local/bigbluebutton/bbb-webrtc-sfu/node_modules/modesl/lib/esl/Connection.js:211:10)\n    at Connection.auth (/usr/local/bigbluebutton/bbb-webrtc-sfu/node_modules/modesl/lib/esl/Connection.js:514:10)","syscall":"write"},"label":"core","level":"error","message":"FSESL connection received error EPIPE","timestamp":"2023-09-20T08:20:32.658Z"}
Sep 20 08:20:34 hello systemd_start_frontend.sh[11388]: 2023-09-20T08:20:34.564Z frontend-1 [#033[32minfo#033[39m] : Connection status updated: meetingId=3cd0f27c2c1fb17b0185b551158100de0a1fcd02-1695197818766 userId=w_mz6flmdxpqfi status=normal type=socket
Sep 20 08:20:37 hello bbb-webrtc-sfu[11485]: {"error":{"code":"EPIPE","errno":-32,"message":"write EPIPE","stack":"Error: write EPIPE\n    at afterWriteDispatched (node:internal/stream_base_commons:160:15)\n    at writeGeneric (node:internal/stream_base_commons:151:3)\n    at Socket._writeGeneric (node:net:962:11)\n    at Socket._write (node:net:974:8)\n    at writeOrBuffer (node:internal/streams/writable:392:12)\n    at _write (node:internal/streams/writable:333:10)\n    at Writable.write (node:internal/streams/writable:337:10)\n    at Connection.send (/usr/local/bigbluebutton/bbb-webrtc-sfu/node_modules/modesl/lib/esl/Connection.js:183:21)\n    at Connection.sendRecv (/usr/local/bigbluebutton/bbb-webrtc-sfu/node_modules/modesl/lib/esl/Connection.js:211:10)\n    at Connection.auth (/usr/local/bigbluebutton/bbb-webrtc-sfu/node_modules/modesl/lib/esl/Connection.js:514:10)","syscall":"write"},"label":"core","level":"error","message":"FSESL connection received error EPIPE","timestamp":"2023-09-20T08:20:37.658Z"}
```

**To Reproduce**
1. Update to 2.7.1
2. Enter a room
3. See error explained above

**Expected behavior**
Everything should work as with 2.7.0

**Actual behavior**
No audio.

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Firefox, Chrome
 - Version: Both 117

cheers, t.

**Comment by himpierre** [comment]
Am I the only one with this issue? It seems like that. Just started over and installed BigBlueButton 2.7.0 from scratch. Everything worked beautifuly. Snapshoted the VM. Upgraded to 2.7.1. Same picture. Something has to be wrong here.

cheers, t.

**Comment by antobinary** [comment]
Hi @himpierre 
This is the only report of this nature that I'm aware of. Is there anything special about your setup? How do you upgrade - bbb-install.sh?
cc @prlanzarin Anything relevant in the latest sfu tag?

**Comment by himpierre** [comment]
Thanks for taking the time! I did the upgrade with "apt update && apt upgrade".

It seems bigbluebutton does not get the info I allowed access to the devices. Let me upgrade again. Maybe the browser console is helpful. I Can downgrade via virsh snapshot-revert afterwards. :)

cheers, t.

Am 21. September 2023 14:53:55 MESZ schrieb Anton Georgiev ***@***.***>:
>Hi @himpierre 
>This is the only report of this nature that I'm aware of. Is there anything special about your setup? How do you upgrade - bbb-install.sh?
>cc @prlanzarin Anything relevant in the latest sfu tag?
>

**Comment by himpierre** [comment]
> > Thanks for taking the time! I did the upgrade with "apt update && apt upgrade".
> 
> btw: this might be the problem if you have not set up appropriate post-install routines (eg via apply-lib/config or ansible or etc) :)

Uhm. How Am I supposed to upgrade correctly then? Let the bbb-install.sh script run again?

**Comment by himpierre** [comment]
Sorry guys. Followed the instructions on docs.bigbluebutton.org.
```
Upgrading BigBlueButton 2.7
You can upgrade by re-running the bbb-install.sh script again -- it will download and install the latest release of BigBlueButton 2.7.
```

Now it works...
