### ISSUE TITLE
Change my sit'e title in the browser

### ISSUE THREAD

**Issue by DrEhabDiab** [bigbluebutton/bigbluebutton#18834]
**Describe the bug**
Sit'e title cannot be changed from 'BigBlueButton'

**To Reproduce**
Just open the site's URL!

**Expected behavior**
It should show my updated title.

**Actual behavior**
It is still showing BigBlueButton in the title.

**BBB version:**
# bbb-conf --check | grep BigBlueButton
BigBlueButton Server 2.7.1 (425)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: Version 117.0.5938.92 (Official Build) (64-bit)

**Additional context**
How / Where to edit the page / site's title in the browser?

**Comment by andrekutianski** [comment]
You need to edit the title on HTML5 client, docs has some instructions https://docs.bigbluebutton.org/administration/customize/#change-title-in-the-html5-client

I have a project on git with some scripts that help with some customizations, one of them is precisely changing the client's title.

These mods that I developed are available at https://github.com/strwise/bbb-mods (if help you, give a star!)

Best,
Andre
