### ISSUE TITLE
Changing appLogLevel does not work

### ISSUE THREAD

**Issue by Amanb1145** [bigbluebutton/bigbluebutton#18880]
Hey,
I found that our BBB server was generating log files-
so I changed the `appLogLevel` to `WARN` in `/usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties`
file and restarted the server but I  found after some days that it was still logging DEBUG and INFO logs to log files(ex- bbb-web.2023-09-30.log). 
example of log-

`2023-09-30T00:00:53.918Z DEBUG o.b.web.controllers.ApiController - ApiController#isMeetingRunning
2023-09-30T00:00:53.918Z DEBUG o.b.web.controllers.ApiController - [meetingID:[524d4ef0-c2ce-419b-83f5-d11c9992dad3], checksum:[adb83cdfcb2d92fef1039fef4f86584a8f0e6538]]
2023-09-30T00:00:53.918Z DEBUG o.b.web.controllers.ApiController - meetingID=524d4ef0-c2ce-419b-83f5-d11c9992dad3&checksum=adb83cdfcb2d92fef1039fef4f86584a8f0e6538
2023-09-30T00:00:53.918Z INFO  o.b.api.service.ValidationService - Validating isMeetingRunning request with query string meetingID=524d4ef0-c2ce-419b-83f5-d11c9992dad3&checksum=adb83cdfcb2d92fef1039fef4f86584a8$
2023-09-30T00:00:53.918Z INFO  o.b.a.m.v.GetChecksumValidator - query string after checksum removed: [meetingID=524d4ef0-c2ce-419b-83f5-d11c9992dad3]
2023-09-30T00:00:53.918Z INFO  o.b.a.m.v.GetChecksumValidator - CHECKSUM=adb83cdfcb2d92fef1039fef4f86584a8f0e6538 length=40
2023-09-30T00:00:53.918Z INFO  o.b.web.controllers.ApiController - Retrieving meeting 88ab52305a93503b7d3e12ea54399d0f76045166
`

How do I fix this logging issue that is generating large log files? Is there any other file where I have to change logLevel?

Thanks

**Comment by tobast** [comment]
Hello,
I haven't been easily able to find a way to prevent the `bbb-web` systemd unit from logging at DEBUG level, quickly filling up the system journal with entries similar to the post above, such as eg.

```
oct. 29 16:47:39 srv-bigbluebutton java[23605]: 2024-10-29T16:47:39.630+01:00 DEBUG o.b.web.controllers.ApiController - ApiController#getMeetings
oct. 29 16:47:39 srv-bigbluebutton java[23605]: 2024-10-29T16:47:39.632+01:00 INFO  o.b.api.service.ValidationService - Validating getMeetings request with query string checksum=…
oct. 29 16:47:39 srv-bigbluebutton java[23605]: 2024-10-29T16:47:39.632+01:00 INFO  o.b.a.m.v.GetChecksumValidator - query string after checksum removed: []
oct. 29 16:47:39 srv-bigbluebutton java[23605]: 2024-10-29T16:47:39.632+01:00 INFO  o.b.a.m.v.GetChecksumValidator - CHECKSUM=… length=40
oct. 29 16:47:39 srv-bigbluebutton java[23605]: 2024-10-29T16:47:39.632+01:00 INFO  o.b.a.m.v.GetChecksumValidator - SHA1 …
oct. 29 16:47:39 srv-bigbluebutton java[23605]: 2024-10-29T16:47:39.632+01:00 INFO  o.b.a.m.v.ContentTypeValidator - Validating GET request with content type null
oct. 29 16:47:39 srv-bigbluebutton java[23605]: 2024-10-29T16:47:39.663+01:00 DEBUG o.b.w.c.RecordingController - RecordingController#getRecordings
oct. 29 16:47:39 srv-bigbluebutton java[23605]: 2024-10-29T16:47:39.664+01:00 INFO  o.b.api.ParamsProcessorUtil - CHECKSUM=… length=40
oct. 29 16:47:39 srv-bigbluebutton java[23605]: 2024-10-29T16:47:39.664+01:00 INFO  o.b.api.ParamsProcessorUtil - SHA1 …
oct. 29 16:47:39 srv-bigbluebutton java[23605]: 2024-10-29T16:47:39.664+01:00 DEBUG o.b.w.c.RecordingController - checksum=…&state=unpublished
oct. 29 16:47:39 srv-bigbluebutton java[23605]: 2024-10-29T16:47:39.664+01:00 INFO  o.b.api.ParamsProcessorUtil - CHECKSUM=… length=40
oct. 29 16:47:39 srv-bigbluebutton java[23605]: 2024-10-29T16:47:39.664+01:00 INFO  o.b.api.ParamsProcessorUtil - SHA1 …
oct. 29 16:47:39 srv-bigbluebutton java[23605]: 2024-10-29T16:47:39.664+01:00 INFO  o.bigbluebutton.api.MeetingService - Invalid offset parameter null
oct. 29 16:47:39 srv-bigbluebutton java[23605]: 2024-10-29T16:47:39.664+01:00 INFO  o.bigbluebutton.api.MeetingService - Invalid limit parameter null
oct. 29 16:47:39 srv-bigbluebutton java[23605]: Getting playback formats at /var/bigbluebutton/unpublished
oct. 29 16:47:39 srv-bigbluebutton java[23605]: Playback format = presentation
```

every few seconds.
