### ISSUE TITLE
Enhancement: add client redirect url after login to API

### ISSUE THREAD

**Issue by bigbluebutton-issue-import** [bigbluebutton/bigbluebutton#1889]
Originally reported on Google Code with ID 1135

```
I have added this feature to my code. You can review the code, and free feel to take/modify
whatever you like to be include in your source.

This allows you to pass in &loginURL=xxx to be redirect to load different clients.
This is very helpful if you maintain different versions of the flash client customized
for different rooms.

 Meeting.java
 ParamsProcessorUtil.java
 ApiController.groovy
bbb_api.jsp

You may also want to update the bbb_api.html in the bigbluebutton-API-Buddy if you
are using that for testing.
```

Reported by `living3water` on 2012-02-02 19:08:48

<hr>
- _Attachment: [ApiController.groovy](https://storage.googleapis.com/google-code-attachments/bigbluebutton/issue-1135/comment-0/ApiController.groovy)_
- _Attachment: [Meeting.java](https://storage.googleapis.com/google-code-attachments/bigbluebutton/issue-1135/comment-0/Meeting.java)_
- _Attachment: [ParamsProcessorUtil.java](https://storage.googleapis.com/google-code-attachments/bigbluebutton/issue-1135/comment-0/ParamsProcessorUtil.java)_
- _Attachment: [bbb_api.jsp](https://storage.googleapis.com/google-code-attachments/bigbluebutton/issue-1135/comment-0/bbb_api.jsp)_

**Comment by pedrobmarin** [comment]
This feature was included up to v2.2 https://github.com/bigbluebutton/bigbluebutton/blob/e51f569a8ace2863905853373c9a7a8484bba49d/bigbluebutton-web/grails-app/controllers/org/bigbluebutton/web/controllers/ApiController.groovy#L512-L520 but looks like it was removed in v2.3.
