### ISSUE TITLE
Live translation based on Live Automatic Closed Captions

### ISSUE THREAD

**Issue by fishfree** [bigbluebutton/bigbluebutton#18908]
Since we have already the [Live Automatic Closed Captions feature](https://support.bigbluebutton.org/hc/en-us/articles/12237555994135-What-s-new-in-2-6#:~:text=Accessibility-,Live%20Automatic%20Closed%20Captions,-By%20default%2C%20the). Can we further develop Live Translation feature by calling third-party translation API or local-deployed open source translation service such as [OpenNMT-py](https://github.com/OpenNMT/OpenNMT-py) or [seamless_communication](https://github.com/facebookresearch/seamless_communication)?

**Comment by hiroshisuga** [comment]
Long time ago I did an experiment with Google translation and DeepL. It worked pretty well.
https://github.com/hiroshisuga/bigbluebutton/pull/196

**Comment by fishfree** [comment]
@hiroshisuga Thank you very much for your sharing and tip! Would you also share how to adpat your feature after installing BBB with bbb-install.sh or bbb-docker?

**Comment by JulianKropp** [comment]
Maybe you are interested into my project.  

https://github.com/bigbluebutton/bigbluebutton/issues/17396#issuecomment-1807079182

[bbb-translation-bot](https://github.com/ITLab-CC/bbb-translation-bot)

[bbb-bot](https://github.com/ITLab-CC/bigbluebutton-bot)
