### ISSUE TITLE
[3.0] document AVX requirement

### ISSUE THREAD

**Issue by danimo** [bigbluebutton/bigbluebutton#18914]
**Describe the bug**

Due to its dependency on MongoDB 6.0, BBB 3.0 depends on the AVX CPU extension. This is a placeholder bug which can be closed after this fact has been documented. It should probably also be in the release notes.

From https://www.mongodb.com/docs/manual/administration/production-notes/:

> MongoDB 5.0 requires use of the AVX instruction set, available on [select Intel and AMD processors.](https://en.wikipedia.org/wiki/Advanced_Vector_Extensions#CPUs_with_AVX)

**Rationale**

Usually, most hardware running BBB should provide AVX, however there is a good chance that VMs do not pass AVX to the guest (this has bitten me in my lab setup).

**Comment by ffdixon** [comment]
Hi @danimo,

Thanks for pointing this out -- we'll update the docs.

Also, there is effort in BigBlueButton 3.0 to move away from Meteor/MongoDB with the use of GraphQL and Hasura.  There was a presentation about it at the last BigBlueButton World Conference, see https://youtu.be/2v6X8-_B3lk.

It remains to be seen if we can pull this off for 3.0, but if we do it will remove our dependency on Meteor and it's embedded Mongodb database.

**Comment by antobinary** [comment]
BigBlueButton <= 2.7 uses MongoDB 4.4
BigBlueButton 3.0+ does not use MongoDB as of ~beta.1
Only the first alphas of BBB 3.0 used MongoDB 6. I believe we can close this.
