### ISSUE TITLE
Enable passing of a default presentation as URL on the create GET request

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#18924]
**Is your feature request related to a problem? Please describe.**
To minimize changes to front-end applications that wish to enable the user to specify a default presentation, enable passing of a default presentation on the create URL as a GET request.

**Describe the solution you'd like**
The parameter could be `presentationURL=<url_to_presentation>`.  It will be *only* a single URL, not multiple URLs.

**Describe alternatives you've considered**
Currently, we allow the passing of a URL on the `create` command via a POST request.  However, this is more complex as it requires front-ends to support sending POST requests.

**Additional context**
If we can pass this parameter as a GET request, then ScaleLite can use per-tenant configurations to enable the administrator to specify a default presentation for the tenant

The behaviour for using `presentationURL=<url_to_presentation>` OR passing a single URL as part of the POST request should result in the same: BigBlueButton downloads the file at the URL and makes it the default presentation.

If both `presentationURL=<url_to_presentation>` AND a default presentation are specified in the POST request, then the presentationURL takes precedence.  If the URL fails to load, then there is no presentation in BigBlueButton.

**Comment by gustavotrott** [comment]
The parameter `preUploadedPresentationOverrideDefault` currently determines whether the default `default.pdf` presentation is sent, and if the uploaded presentation should be set as the default.

For consistency, I suggest leveraging this existing parameter to decide the behavior of the new `presentationURL` parameter:
- If `preUploadedPresentationOverrideDefault=false`: The presentation from `presentationURL` will be uploaded but won't be set as the default.
- If `preUploadedPresentationOverrideDefault=true`: The presentation from `presentationURL` will be set as default, and the previous default `default.pdf` will not be uploaded to this meeting.

Furthermore, to maintain consistency in naming, maybe the new parameter can be renamed to `preUploadedPresentation`. For instance:
`?preUploadedPresentation=http://test.com/myNewDefault.pdf`

To make it default then it would be:
`?preUploadedPresentation=http://test.com/myNewDefault.pdf&preUploadedPresentationOverrideDefault=true`
