### ISSUE TITLE
The shortcut for raising hand is not functioning as expected @ 2.7.1

### ISSUE THREAD

**Issue by rfcmaXi** [bigbluebutton/bigbluebutton#18937]
**Describe the bug**
The shortcut for raising hand (Alt + Shift + R or Control + Option + R ) is not functioning as expected.

**To Reproduce**
1. Go to https://demo.bigbluebutton.org
2. Create Room and Join
3. Try the Shortcut

**Expected behavior**
I expected that using Alt + Shift + R would raise my hand in the BigBlueButton session as descripted here:
https://github.com/bigbluebutton/bigbluebutton/blob/693183291db3198c3808715e31bcf5a194a4a39a/docs/docs/accessiblity.md?plain=1#L95C43-L95C43

**Actual behavior**
Instead of raising my hand, there was no response when I pressed Alt + Shift + R.

**BBB version:**
2.7.1

**Desktop (please complete the following information):**
 - OS: Mac and Windows
 - Browser Chrome and Safari
 
**Additional context**
I suspect the problem is related to the reaction bar introduced in 2.7. We have a high number of handicapped users, which is why the bug is relevant to accessibility.

**Comment by leandroveronezi** [comment]
same in 2.6

wget -qO- https://ubuntu.bigbluebutton.org/bbb-install-2.6.sh | bash -s -- -v focal-260 -s ${bbb_url} -e ${email} -w

**Comment by antobinary** [comment]
Thank you for reporting this! I can confirm after trying to reproduce on 2.7.1 that the shortcut listed for Raise hand (in my case At + R) is not active.
![Screenshot from 2023-10-13 11-42-57](https://github.com/bigbluebutton/bigbluebutton/assets/6312397/5737afaf-9494-412d-a524-d0c3644108c3)
