### ISSUE TITLE
Improve the drawing of polls

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#18934]
**Is your feature request related to a problem? Please describe.**
The current polls are drawn with characters, which are not well aligned, making it hard to quickly see the results at a glance.

![image](https://github.com/bigbluebutton/bigbluebutton/assets/290351/9e645c15-72f4-4d35-8c9f-7bc9dd1ceca5)

**Describe the solution you'd like**
Use SVG to draw the poll results in the chat

<img width="182" alt="image" src="https://github.com/bigbluebutton/bigbluebutton/assets/290351/90a36d81-9c76-45c7-859f-5cd033cdcd55">

and tldraw elements to draw the poll on the presentation.

<img width="155" alt="image" src="https://github.com/bigbluebutton/bigbluebutton/assets/290351/e6353df3-753a-4cec-b4e7-9c47286a6cae">

**Describe alternatives you've considered**
We could draw the polls using SVG on the presentation, but if we use tldraw elements it will be easy to support the polls in the recording processing.

Feedback welcome!

**Comment by antobinary** [comment]
Done as part of BBB 3.0
