### ISSUE TITLE
Cannot install 2.7.1

### ISSUE THREAD

**Issue by aogilvie** [bigbluebutton/bigbluebutton#18931]
Today. New GCP VM using image ubuntu-os-cloud/global/images/family/ubuntu-minimal-2004-lts

$ add-apt-repository ppa:bigbluebutton/support -y

Cannot add PPA: 'ppa:~bigbluebutton/ubuntu/support'.
The team named '~bigbluebutton' has no PPA named 'ubuntu/support'
Please choose from the following available PPAs:
 * 'support':  BigBlueButton Support Packages

$ lsb_release -a

No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.6 LTS
Release:	20.04
Codename:	focal

**Comment by aogilvie** [comment]
My offer still stands to host a mirror of BBB packages @ffdixon  Just lemme at the source code :)

**Comment by antobinary** [comment]
Related: https://github.com/bigbluebutton/bigbluebutton/issues/18927#issuecomment-1758315339

**Comment by leandroveronezi** [comment]
same in 2.6

wget -qO- https://ubuntu.bigbluebutton.org/bbb-install-2.6.sh | bash -s -- -v focal-260 -s ${bbb_url} -e ${email} -w

**Comment by KayZ4711** [comment]
Hi, I am new to Open Source, can I work on this issue? How can I set up the development environment for this?

**Comment by leandroveronezi** [comment]
another log causing the same error.

Preparing to unpack .../dnsutils_1%3a9.16.1-0ubuntu2.16_all.deb ...
Unpacking dnsutils (1:9.16.1-0ubuntu2.16) ...
Setting up dnsutils (1:9.16.1-0ubuntu2.16) ...
Traceback (most recent call last):
  File "/usr/bin/add-apt-repository", line 137, in <module>
    shortcut = shortcut_handler(line)
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 884, in shortcut_handler
    ret = factory(shortcut)
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 469, in shortcut_handler
    return PPAShortcutHandler(shortcut)
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 426, in __init__
    info = get_ppa_info(self.shortcut)
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 392, in get_ppa_info
    _get_suggested_ppa_message(user, ppa))
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 349, in _get_suggested_ppa_message
    lp_user = get_info_from_lp(LAUNCHPAD_USER_API % user)
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 104, in get_info_from_lp
    return get_info_from_https(lp_url, True)
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 98, in get_info_from_https
    return json.loads(data)
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Cannot add PPA: 'ppa:~bigbluebutton/ubuntu/support'.
The team named '~bigbluebutton' has no PPA named 'ubuntu/support'
Please choose from the following available PPAs:
 * 'support':  BigBlueButton Support Packages
bbb-install: Unable to setup PPA for ppa:bigbluebutton/support

**Comment by ffdixon** [comment]
We're seeing the same issue here.  The support repository exists at https://launchpad.net/~bigbluebutton/+archive/ubuntu/support.



<img width="1421" alt="image" src="https://github.com/bigbluebutton/bigbluebutton/assets/290351/f11fa7d9-c5b4-4e0e-90c0-863bbc5f9ee7">

And when following the steps to install manually, we see an error.

```
# sudo add-apt-repository ppa:bigbluebutton/support
Cannot add PPA: 'ppa:~bigbluebutton/ubuntu/support'.
The team named '~bigbluebutton' has no PPA named 'ubuntu/support'
Please choose from the following available PPAs:
 * 'support':  BigBlueButton Support Packages
```

Something is a bit weird as this is working sometimes and other times its not.

**Comment by ffdixon** [comment]
Still digging into this as sometimes the command is working, sometimes not

```
# add-apt-repository ppa:martin-uni-mainz/coturn
Cannot add PPA: 'ppa:~martin-uni-mainz/ubuntu/coturn'.
The user named '~martin-uni-mainz' has no PPA named 'ubuntu/coturn'
Please choose from the following available PPAs:
 * 'coturn':  Coturn
 ^C
# add-apt-repository ppa:martin-uni-mainz/coturn
 Newer builds of coturn
 More info: https://launchpad.net/~martin-uni-mainz/+archive/ubuntu/coturn
Press [ENTER] to continue or Ctrl-c to cancel adding it.
```

**Comment by ffdixon** [comment]
Can you try manually running the command `add-apt-repository -y ppa:martin-uni-mainz/coturn` until it works, then run your `bbb-install.sh` command again and let us know if that completes the install.

**Comment by lonesomewalker** [comment]
> My offer still stands to host a mirror of BBB packages @ffdixon Just lemme at the source code :)

Erm, you can just install a mirror. This is doable under 5 minutes ;-)

**Comment by aogilvie** [comment]
> > My offer still stands to host a mirror of BBB packages @ffdixon Just lemme at the source code :)
> 
> Erm, you can just install a mirror. This is doable under 5 minutes ;-)

Well, for the last 5 years I want to build the packages, but the source code for that is NOT open source ;)

**Comment by lonesomewalker** [comment]
> > > My offer still stands to host a mirror of BBB packages @ffdixon Just lemme at the source code :)
> > 
> > 
> > Erm, you can just install a mirror. This is doable under 5 minutes ;-)
> 
> Well, for the last 5 years I want to build the packages, but the source code for that is NOT open source ;)

For what part of BBB do you miss the source code?
