### ISSUE TITLE
bbb install 2.6 error

### ISSUE THREAD

**Issue by leandroveronezi** [bigbluebutton/bigbluebutton#18940]
Since yesterday, new installations are returning error.

command:
wget -qO- https://ubuntu.bigbluebutton.org/bbb-install-2.6.sh | bash -s -- -v focal-260 -s ${url} -e ${email} -w

log:
Preparing to unpack .../dnsutils_1%3a9.16.1-0ubuntu2.16_all.deb ...
Unpacking dnsutils (1:9.16.1-0ubuntu2.16) ...
Setting up dnsutils (1:9.16.1-0ubuntu2.16) ...
Cannot add PPA: 'ppa:~bigbluebutton/ubuntu/support'.
The team named '~bigbluebutton' has no PPA named 'ubuntu/support'
Please choose from the following available PPAs:
 * 'support':  BigBlueButton Support Packages
Cannot add PPA: 'ppa:~bigbluebutton/ubuntu/support'.
The team named '~bigbluebutton' has no PPA named 'ubuntu/support'
Please choose from the following available PPAs:
 * 'support':  BigBlueButton Support Packages
bbb-install: Unable to setup PPA for ppa:bigbluebutton/support

Distributor ID: Ubuntu
Description: Ubuntu 20.04 (LTS) x64
Release: 20.04
Codename: focal

**Comment by antobinary** [comment]
Thank you for reporting! Merging into https://github.com/bigbluebutton/bigbluebutton/issues/18931
