### ISSUE TITLE
Has no option to select automatic transcription language on the joining audio dialog 

### ISSUE THREAD

**Issue by fishfree** [bigbluebutton/bigbluebutton#18947]
The documentation says https://support.bigbluebutton.org/hc/en-us/articles/12237555994135-What-s-new-in-2-6#:~:text=By%20default%2C%20the%20automatic%20transcription,from%20the%20join%20audio%20dialog.

However, there is no this option built on this repo's develop branch. And there is either related configuration in the sample.env to enable this feature.

Actually, I validated this bug both in a fresh environment deployed by running install.sh and docker-compose with https://github.com/bigbluebutton/docker.

**Comment by antobinary** [comment]
Hi @fishfree 

The first link you sent opens for me at a different spot so I am not 100% sure I understand. However, to use automatic transcription language (in its current form - https://github.com/bigbluebutton/bigbluebutton/blob/v2.7.x-release/bigbluebutton-html5/private/config/settings.yml#L91-L95 ) you need to
- enable it (see the setting enable: false in my link)
- confirm your browser supports it recent Chrome browsers do but last I checked FireFox did not

I hope this answers your question!

**Comment by fishfree** [comment]
@antobinary Thank you very much! Would you pls also tell me which folder the settings.yml locates in an instance deplyed by install.sh?
