### ISSUE TITLE
Only send desktop sharing keyframe when a user joins the session

### ISSUE THREAD

**Issue by bigbluebutton-issue-import** [bigbluebutton/bigbluebutton#1895]
Originally reported on Google Code with ID 1141

```
Currently, the desktop sharing server sends out a key frame every 30 seconds to all
users.  

Explore whether the keyframes could be omitted for users that have already received
a keyframe.  In this way, if 30 users are viewing the presenter's desktop, and a 31st
user joins, then only the 31st user need receive a full keyframe of the desktop.

```

Reported by `ffdixon` on 2012-02-09 12:18:44

**Comment by ffdixon** [comment]
Marking this as won't fix.  We've updated BigBlueButton desktop sharing to use ffmpeg (downloaded in a JAR file) which is sending the desktop sharing as SVC2 video stream.  We're not planning to add logic to send out key frames.
