### ISSUE TITLE
Upload of a slide with UTF-8 characters in filename causes download error in 2.7.2-dev

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#18951]
**Describe the bug**
If a slide has a UTF-8 character filename, such as `soeur et frère.pptx`, will cause a download error.

**To Reproduce**
1. Upload the attached presentation
2. Enable download of original presentation in Presentation Upload/Manage dialog
3. Select the download presentation in the presentation area

**Expected behavior**
The presentation downloads.

**Actual behavior**
An error occurs

<img width="615" alt="image" src="https://github.com/bigbluebutton/bigbluebutton/assets/290351/4fbe46a5-bfd6-4cae-b903-4a0cd1e0c124">
[soeur et frère.pptx](https://github.com/bigbluebutton/bigbluebutton/files/12928364/soeur.et.frere.pptx)

**Screenshots**

**BBB version:**
BigBlueButton 2.7.2-dev

**Comment by ffdixon** [comment]
Hmm ... it doesn't seem to be consistent.  I just tried the above on a new meeting and it worked the second time.

**Comment by ffdixon** [comment]
Logs from bbb-web.log look normal

```
bbb-web.log:2023-10-17T11:15:37.548Z DEBUG o.b.w.c.PresentationController - processing file upload soeur et frère.pptx
bbb-web.log:2023-10-17T11:15:37.647Z DEBUG o.b.w.c.PresentationController - file upload success soeur et frère.pptx
bbb-web.log:2023-10-17T11:15:42.649Z INFO  o.b.p.DocumentConversionServiceImp -  --analytics-- data={"current":false,"filename":"soeur et frère.pptx","logCode":"presentation_conversion_start","authzToken":"PresUploadToken-m6cpi83lDEFAULT_PRESENTATION_POD-w_e96zmj0ds2za","meetingId":"462ff9d3d8cc74eb7c1143112c0885567d4cf220-1697540796072","isRemovable":true,"message":"Start presentation conversion.","podId":"DEFAULT_PRESENTATION_POD","presId":"6ee6be95dd5527cd103e6979120c7fb8e18ba8ed-1697541337547"}
bbb-web.log:2023-10-17T11:15:42.650Z INFO  o.b.p.imp.Office2PdfPageConverter -  --analytics-- data={"filename":"soeur et frère.pptx","logCode":"office_doc_to_pdf","meetingId":"462ff9d3d8cc74eb7c1143112c0885567d4cf220-1697540796072","message":"Converting Office doc to PDF.","presId":"6ee6be95dd5527cd103e6979120c7fb8e18ba8ed-1697541337547"}
bbb-web.log:2023-10-17T11:15:46.741Z INFO  o.b.p.i.OfficeToPdfConversionService -  --analytics-- data={"filename":"soeur et frère.pptx","logCode":"office_to_pdf_success","meetingId":"462ff9d3d8cc74eb7c1143112c0885567d4cf220-1697540796072","message":"Successfully converted office file to pdf.","presId":"6ee6be95dd5527cd103e6979120c7fb8e18ba8ed-1697541337547"}
bbb-web.log:2023-10-17T11:15:46.754Z INFO  o.b.p.imp.PresentationFileProcessor -  --analytics-- data={"filename":"soeur et frère.pptx","num_pages":2,"logCode":"presentation_conversion_num_pages","authzToken":"PresUploadToken-m6cpi83lDEFAULT_PRESENTATION_POD-w_e96zmj0ds2za","meetingId":"462ff9d3d8cc74eb7c1143112c0885567d4cf220-1697540796072","message":"Presentation conversion number of pages.","podId":"DEFAULT_PRESENTATION_POD","presId":"6ee6be95dd5527cd103e6979120c7fb8e18ba8ed-1697541337547"}
bbb-web.log:2023-10-17T11:15:47.322Z INFO  o.b.p.i.PresentationConversionCompletionService -  --analytics-- data={"current":false,"filename":"soeur et frère.pptx","logCode":"presentation_conversion_end","meetingId":"462ff9d3d8cc74eb7c1143112c0885567d4cf220-1697540796072","message":"End presentation conversion.","podId":"DEFAULT_PRESENTATION_POD","presId":"6ee6be95dd5527cd103e6979120c7fb8e18ba8ed-1697541337547"}
```

**Comment by GuiLeme** [comment]
Hey, @ffdixon, I just tried both locally and on dev27 and couldn't reproduce, I were able to download the original presentation (pptx) and the converted one (pdf). 

The uploading part you mentioned, is it through the client (the presentation uploader modal), or is it through POST create with the payload configured as described in the issue?

**Comment by ffdixon** [comment]
Thanks Guileme -- it was happening to me in a session, and then it wasn't.  I'll try again to reproduce.

**Comment by GhaziTriki** [comment]
I am intrigued about the redirection to `/bigbluebutton/undefined`. Any `nginx` logs to complete the picture?

**Comment by gabriellpr** [comment]
After testing I concluded this issue does not occur anymore, and due to that the issue can be closed.
