### ISSUE TITLE
Incorrectly formatted markdown in Recording documentation

### ISSUE THREAD

**Issue by MBM1607** [bigbluebutton/bigbluebutton#18967]
The page https://docs.bigbluebutton.org/development/recording has attached images that are not rendering due to incorrectly formatted image inclusions.

`![Record and Playback - Overview](/img/diagrams/Record and Playback Service Diagram-RAP - Overview.png)`

The issue is that there are spaces in the image name, [which are illegal in URLs. So this needs to be encoded to %20](https://url.spec.whatwg.org/#url-writing)

**Comment by MBM1607** [comment]
The ideal solution in my opinion would be to rename the images to snake-case, to make them URL-friendly. I have done so in my fork, if renaming is right then I can create a pull request.

Otherwise, I can create a pull request that simply encodes the spaces in image URLs.

Please let me know, which would be preferred.

**Comment by SuperKXT** [comment]
Closed by https://github.com/bigbluebutton/bigbluebutton/pull/20298

**Comment by MBM1607** [comment]
Closed by https://github.com/bigbluebutton/bigbluebutton/pull/20298
