### ISSUE TITLE
No Notfikation for phone Users that you staretd to record the meeting

### ISSUE THREAD

**Issue by BlumPhilipp** [bigbluebutton/bigbluebutton#18989]
**Is your feature request related to a problem? Please describe.**
When you start as host to record the meeting, users using the regular phone (by phone number) will not be informed that you have started recording

**Describe the solution you'd like**
It would be great if users received a short message on the phone, for example read out by a mechanical voice, that you have started recording the meeting

**Additional context**
maybe related to Issue #18988

**Comment by hostbbb** [comment]
For the the case of late phone joiners... if the meeting is already recording.  some dialplan code can play "this meeting is being recorded" for all new entrants. There are fs cli commands to tell if recording is active so dfialplan condition can play.

For the pressing of start/stop record while already in meeting.

If you play that prompt in the conference thread, it gets in recording.   so here you could detect the start/stop redis events, and play the on and off messages to just the dial in audio members with some ruby code, an add a small custom service to handle today before the feature appears in core.    We do this today with phone users being able to raise/lower their hand with digit.  the audio messages played to just the effected phone member.
