### ISSUE TITLE
bbb-libreoffice: use tags

### ISSUE THREAD

**Issue by debuglevel** [bigbluebutton/bigbluebutton#19006]
**Describe the bug**
#18945 and #18818 introduce a pre-built docker image.
This is fine, because that's how Docker should actually be used.

But please do not use `latest`.
`latest` is often considered evil - because it always uses the latest pushed tag, no matter what breaking changes were introduced.
If you push a new and incompatible `libreoffice` image (e.g. for BBB 3.0), the people using BBB 2.7 will also be affected because they also use `latest`.

It's a good practice therefore, to always use some kind of tag (semver, datetime, does not really matter).
This way you can push a bugfix release `bbb-libreoffice:2.7-20231025` and `bbb-libreoffice:3.0-20231025` and each BBB version will get their according version.

That might be not relevant right now, because the image is rather simple and we could guess LibreOffice will not introduce breaking changes.
But if they do, bad things might happen :)

**Comment by antobinary** [comment]
We are moving to tags, see https://github.com/bigbluebutton/bigbluebutton/pull/18974/files part of BBB 2.7.2
This will trickle down to 2.6 as part of 2.6.15

**Comment by debuglevel** [comment]
Oops. Just looked at the initial pull request :D
