### ISSUE TITLE
Waiting room indicator sound defective

### ISSUE THREAD

**Issue by marga-reflact** [bigbluebutton/bigbluebutton#19011]
Hello,
the notification tone for a waiting participant only rings once, always only for the first participant of the day. After that, the warning tone will no longer sound.

![Screenshot by Snip My at 27 10 2023, 08:03:03](https://github.com/bigbluebutton/bigbluebutton/assets/110968854/c62c7433-183f-4452-870f-1de1427d96e4)

BigBlueButton 2.7.1

**Comment by fabio-garcia** [comment]
Can reproduce on 2.7.2 as well. Also reported in #18802.

**Comment by ffdixon** [comment]
Good catch!
