### ISSUE TITLE
disruptive slide transition for non-white backgrounds

### ISSUE THREAD

**Issue by bigbluebutton-issue-import** [bigbluebutton/bigbluebutton#1906]
Originally reported on Google Code with ID 1152

```
When switching between slides/pages in an uploaded document, the page is blanked briefly
to white and then the next page fades in from white.

This is hardly noticeable on a standard PDF with black text on a white background.
In fact it may have been done like this to make the transition a little bit easier
on the eye. However, if you have a presentation with a dark background e.g. the chalky
blackboard theme from Keynote, then the opposite occurs and it's a bit disruptive.

I'd suggest a simple replacement of the previous page might work for any type of file.
The various pdf2swf examples I found on the web do this and it seems to work well.

```

Reported by `david.scotson` on 2012-02-22 15:37:24

**Comment by hostbbb** [comment]
Ok.  here is a solution to eliminate the flicker for slides with white backgrounds on 1.1  Should address 80% of the presentations.

2 changes to client, and rebuild.

1) diff --git a/bigbluebutton-client/branding/default/style/css/BBBDefault.css b/bigbluebutton-client/branding/default/style/css/BBBDefault.css

 .presentationSlideViewStyle {
-  backgroundColor: #b9babc;
+  backgroundColor: #FFFFFF;
 }

and 

2) https://github.com/bigbluebutton/bigbluebutton/blob/master/bigbluebutton-client/src/org/bigbluebutton/modules/present/ui/views/SlideView.mxml#L529

remove completeEffect="Fade" line 529

Much easier on the eyes.

**Comment by ffdixon** [comment]
Closing as this was an issue related to the Flash client (the project has moved to an HTML5 client).
