### ISSUE TITLE
Add hook to scan uploaded presentations for viruses to comply with local regulations.

### ISSUE THREAD

**Issue by defnull** [bigbluebutton/bigbluebutton#19073]
**Is your feature request related to a problem? Please describe.**
Some local regulations (e.g. BayITSiR-14) require that all files uploaded to a web application must be scanned for viruses before they are processed or distributed. This also applies to presentations uploaded to BBB. I don't want to discuss whether these requirements make sense or not, but they exist and may prevent usage of BBB in certain scenarios.

**Describe the solution you'd like**
We hacked together a solution by modifying `/usr/share/bbb-libreoffice-conversion/convert-local.sh`. It now calls an optional `scan-local.sh` script (if present) before the actual conversion is started and fails if that script returns an error. Our `scan-local.sh` script relies on a local ClamAV daemon and simply calls `exec clamdscan --stream "$1"` to scan the source file, but other solutions (e.g. VirusTotal or a remote ClamAV daemon) could also be supported, so it might be best to leave the implementation of `scan-local.sh` to the user and just add the "if exists then call scan-local.sh" hook to `convert-local.sh`.

**Comment by antobinary** [comment]
Addressed via https://github.com/bigbluebutton/bigbluebutton/pull/21217
