### ISSUE TITLE
Add microphone volume compression to normalise audio across all users

### ISSUE THREAD

**Issue by mkpelletier** [bigbluebutton/bigbluebutton#19087]
**Is your feature request related to a problem? Please describe.**
In any given meeting, we seem to have a wide range in the audio dynamics of user microphones.  Some users are too quiet, some have good audio, and others are too loud.  The user is left raising and lowering the system volume to compensate for the differences.

**Describe the solution you'd like**
Apply audio compression to normalise the audio amplitude across all users in a given room.  We are not talking about audio codecs here, but rather volume normalisation, or audio compression as it is understood in the music industry.  Open source algorithms for this already exist and are widely employed.  Here is one such example: https://gstreamer.freedesktop.org/documentation/audiofx/audiodynamic.html?gi-language=c

**Comment by hostbbb** [comment]
the audio is all miixed in freeswitch mod_conference and sent as one audio stream to all clients.   Freeswitch has some custom AGC settings that can be applied to a conference.  Have not tried but the features exist.
https://developer.signalwire.com/freeswitch/FreeSWITCH-Explained/Modules/mod_conference_3965534/

its also possible to raise or lower the input and output for each member in a conference with esl commands.  have done this in the past to make an inbound telephone line louder via the dialplan.
