### ISSUE TITLE
Display user list when sharing powerpoint screen

### ISSUE THREAD

**Issue by NoemieGit** [bigbluebutton/bigbluebutton#19089]
Hello,

As I'm french native speaker, please apologise if my english is not totally correct.
I'm working as an assistant for digital solutions in a university, where we use BigBlueButton as video-conference solution.

**The problem related by teachers is**
Most of them use PowerPoint to make their lessons, and they use animations and videos inside, so they don't want to convert in PDF. They use the sharescreen button but as they often use a simple laptop, they loose all visibility to the BBB window, with the list of users and public chat.
This is actually their main (if not only) argument to complain about not using Zoom.
Recently, a teacher realise that she was alone in the room after 20 minutes of talking...

**What we would like**
Something similar to Zoom when you share you screen : a top menu that leave you the possibility to display the list of users (blue rectangle in the image) and/or the public chat (green rectangle) and/or overview of the shared screen (yellow rectangle).
![Zoom_Exemple](https://github.com/bigbluebutton/bigbluebutton/assets/150260300/5bc58bef-cc9d-44d7-9ffb-6b2436795dd9)

Thanks for reading me,

Noémie

**Comment by defnull** [comment]
Related -> https://github.com/bigbluebutton/bigbluebutton/issues/19073
