### ISSUE TITLE
"Raise Hand" keyboard shortcut broken by new UI button arrangement bbb >= 2.72

### ISSUE THREAD

**Issue by elemhsb** [bigbluebutton/bigbluebutton#19092]
**Describe the bug**
"Raise Hand" keyboard shortcut broken by new UI button arrangement BBB >= 2.7.x

**To Reproduce**
1. Start bbb session
2. Use browser specific keyboard shortcut for "Raise Hand" and it's not working.

**Expected behavior**
Raise / Lower Hand

**Actual behavior**
nothing 

**BBB version:**
>= 2.7.x
BigBlueButton Server 2.7.2 (463)

**Desktop (please complete the following information):**
 - OS:  Windows, Mac
 - Browser Chrome, Safari, ALL

**Smartphone (please complete the following information):**
- untested
 
**Additional context**
- big issue for handicapped / blind persons

**Comment by Ithanil** [comment]
Is this the same issue as https://github.com/bigbluebutton/bigbluebutton/issues/18937 ? If yes, it has been fixed with Release 2.7.3: https://github.com/bigbluebutton/bigbluebutton/releases/tag/v2.7.3

**Comment by elemhsb** [comment]
Yes, you are right issue is fixed with Release 2.7.3.
