### ISSUE TITLE
Navbar enhancement

### ISSUE THREAD

**Issue by Ericchuk** [bigbluebutton/bigbluebutton#19097]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Noticed the bluebutton logo is big and fixed to a point at the top

**Describe alternatives you've considered**
The bar will still be fixed but for better UI, the navbar items will be repositioned with logo on the left side, navbar link on the left side and social media icons fixed at the bottom right side of the website

**Additional context**
This will make the website looks great and more organised.

**Comment by antobinary** [comment]
Hi @Ericchuk 

Is this the area you're talking about (bigbluebutton.org website?)

![Screenshot from 2023-11-10 08-54-33](https://github.com/bigbluebutton/bigbluebutton/assets/6312397/1ee40111-6a05-491a-be62-56fd4d9cacc1)

**Comment by Ericchuk** [comment]
yeah

**Comment by antobinary** [comment]
Thanks for the feedback!

**Comment by ffdixon** [comment]
thanks for the feedback -- we'll be doing some visual updates to the website in 2024 and will take your feedback into account.
