### ISSUE TITLE
Too many shapes on whiteboard slows down dragging of slide

### ISSUE THREAD

**Issue by bigbluebutton-issue-import** [bigbluebutton/bigbluebutton#1910]
Originally reported on Google Code with ID 1156

```
What steps will reproduce the problem?
1. Draw a bunch of lines on the page
2. Drag the slide around
3. Sometimes the slides get stuck and you can't drag it

What is the expected output? What do you see instead?


Please use labels and text to provide additional information.

```

Reported by `ritzalam` on 2012-02-24 21:52:55

**Comment by capilkey** [comment]
This issue should be alleviated with the 2.0 whiteboard refactor. I changed the way that the shapes update so it should be less intensive.

**Comment by ffdixon** [comment]
Fixed in the refactoring of whiteboard messages in BigBlueButton 2.0-dev.
