### ISSUE TITLE
Protect download of bbb recorded sessions

### ISSUE THREAD

**Issue by Braehler** [bigbluebutton/bigbluebutton#19123]
**Describe the bug**
This is not realy a bug, but a huge violation of data security.
We offer our students some videos to watch only inhouse.
When the recorded session is played, it has an option to download the video content using .webm format which in turn can be converted to MP4 format.
This is a big security issue.
Any chance to stop this behavior? 

**To Reproduce**

**Expected behavior**

**Actual behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, Mac]
 - Browser [e.g. Chrome, Safari]

**Smartphone (please complete the following information):**
 - Browser [e.g. stock browser, Safari]

**Additional context**

**Comment by Zvangi** [comment]
This is the case with everything on web. You can't prevent this.

**Comment by Braehler** [comment]
This has been discussed on this issue here https://github.com/bigbluebutton/bbb-playback/issues/102
 a few years back and it seems to be a solution for this.
I think it´s very needed to disable this,
