### ISSUE TITLE
Stop rap-worker.rb when bbb-record-core is stopped

### ISSUE THREAD

**Issue by bigbluebutton-issue-import** [bigbluebutton/bigbluebutton#1912]
Originally reported on Google Code with ID 1158

```
If rap-worker.rb is blocked (due to a subprocess not finishing), doing

  sudo /etc/init.d/bbb-record-core stop

will not end the rap-worker.rb process.


```

Reported by `ffdixon` on 2012-02-26 14:53:31

**Comment by ffdixon** [comment]
In BigBlueButton 1.1-beta bbb-conf now stops the rap-worker using a systemd script.  All the components of BigBlueButton now use systemd.

See: https://github.com/bigbluebutton/bigbluebutton/blob/master/bigbluebutton-config/bin/bbb-conf#L286
