### ISSUE TITLE
length and Size parameters of recordings are not calculated

### ISSUE THREAD

**Issue by misisol** [bigbluebutton/bigbluebutton#19167]
On getting recoding files from server over API, the parameters **length** and **size** for **TYPE = VIDEO** .. are not calculated or defined : 

	<playback>
				<format>
					<type>**presentation**</type>
					<url>https://example.com//playback/presentation/2.3/283dcrrd379bb2412404fcdda19b78085e8a20-1700370770745</url>
					<processingTime>6312</processingTime>
					<length>0</length>
					<size>**973394**</size>
				</format>
				<format>
					**<type>video</type>**
					<url>https://example.com/playback/video/283dc1529d3efcdda19b78085e8a20-1700370770745/</url>
					<processingTime>0</processingTime>
					<length>0</length>
					**<size>0</size>**
				</format>
			</playback>

**Comment by antobinary** [comment]
We recently checked if this report is relevant to BigBlueButton 3.0 (currently beta.6) and concluded that the `length` value mentioned above has been replaced by `duration` and it is present and calculated correctly in the metadata of both formats.
The value for `size` is also present and calculated correctly for both formats as well.

Thank you for reporting, looks like we missed to investigate or report initially. The stale bot unearthed it and @paultrudel checked the validity.
