### ISSUE TITLE
Link not working

### ISSUE THREAD

**Issue by srikantharika** [bigbluebutton/bigbluebutton#19164]
In the installation page, i found that link to view new features is not working.
Link: https://docs.bigbluebutton.org/administration/install/#upgrading-bigbluebutton-27

**Screenshots**
![image](https://github.com/bigbluebutton/bigbluebutton/assets/24656780/524fcfaf-7105-4688-9e6d-26a52c24dfc4)

**Issue Link:** https://docs.bigbluebutton.org/2.7/new
![image](https://github.com/bigbluebutton/bigbluebutton/assets/24656780/fe85c225-99ca-4c42-bc21-4cccf036a06a)

**Issue Link:** https://docs.bigbluebutton.org/2.7/new#other-notable-changes
![image](https://github.com/bigbluebutton/bigbluebutton/assets/24656780/b12da52f-745a-40a4-962f-8212b5b86df4)

**Comment by antobinary** [comment]
Hey @srikantharika 
Thank you for pointing out the two broken links, you are right!
Thank you also for trying to patch them. The two PRs you sent have some mixup in the branches. I should be able to correct that.

Could you please confirm you have sent a CLA, see https://github.com/bigbluebutton/bigbluebutton/pull/19165#issuecomment-1816887988
