### ISSUE TITLE
3.0 - Confusing notification content for save whiteboard and shared notes from breakout rooms

### ISSUE THREAD

**Issue by antonbsa** [bigbluebutton/bigbluebutton#19234]
**Describe the bug**
After ending breakout rooms, an endless progress notification is displayed for both cases saying there are X uploads complete when there are actually none. After a while, it updates with the correct files uploaded, but the first notification content remains there after this action

**To Reproduce**
1. Create breakout rooms enabling `Save whiteboard` and `Save shared notes`;
2. Join in a room, draw something on the whiteboard, and type on the shared notes;
3. On the main room, end the breakout rooms;

**Video**

https://github.com/bigbluebutton/bigbluebutton/assets/56703993/271612a8-ed73-4d3e-809f-3de59ff643d0

**Comment by JoVictorNunes** [comment]
Not reproducible on a BigBlueButton Server 3.0.0-alpha.7 (1074).

See what I get by following the provided steps:

[Screencast from 26-06-2024 10:14:01.webm](https://github.com/bigbluebutton/bigbluebutton/assets/62393923/3f66cc58-deeb-42b8-890f-007fb3a14661)
