### ISSUE TITLE
3.0: bbb-graphql-middleware crashes in load test

### ISSUE THREAD

**Issue by schrd** [bigbluebutton/bigbluebutton#19247]
**Describe the bug**
When I ran a load test to a 3.0 machine, `bbb-graphql-middleware` crashed:

~~~
bbb-graphql-middleware[235536]: panic: send on closed channel
bbb-graphql-middleware[235536]: goroutine 921626 [running]:
bbb-graphql-middleware[235536]: github.com/iMDT/bbb-graphql-middleware/internal/hascli/replayer.ReplaySubscriptionStartMessages(0xc004928e80, 0xc003c76d80?)
bbb-graphql-middleware[235536]:         /var/tmp/bbb-graphql-middleware_3.0_jammy_m30f/internal/hascli/replayer/replayer.go:15 +0x357
bbb-graphql-middleware[235536]: created by github.com/iMDT/bbb-graphql-middleware/internal/hascli/conn/reader.HasuraConnectionReader
bbb-graphql-middleware[235536]:         /var/tmp/bbb-graphql-middleware_3.0_jammy_m30f/internal/hascli/conn/reader/reader.go:70 +0x832
~~~

**To Reproduce**
1. Start a meeting 
2. join as a user
3. Join lots of bots in a short time
4. let bots send some chat messages
5. terminate bots
6. repeat from 3 until `bbb-graphql-middleware` crashes.

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Firefox 115 ESR, Bots Chrome 119

**Additional context**
I can rerun tests. Let me know what I could do to help debugging this.

**Comment by antobinary** [comment]
@gustavotrott May we close?

**Comment by gustavotrott** [comment]
> @gustavotrott May we close?

Yes, it was fixed with the SafeChannels!
