### ISSUE TITLE
Specific file type containing the link to the external media #5579

### ISSUE THREAD

**Issue by PeterHagen** [bigbluebutton/bigbluebutton#19258]
**Is your feature request related to a problem? Please describe.**

The way external videos have to be added to the presentation requires the presenter to find and copy the url to the media and paste it into the BBB dialog. We can upload presentations automatically with the API, but starting a video would always require the presenter to lookup the correct url.

**Describe the solution you'd like**

Wouldn't it be possible to have some kind of file definition, where the file contains the url, which can be uploaded to BBB. On selecting this file (like a presentation) it would start playing the url from the file.

How about support for [M3U](https://en.wikipedia.org/wiki/M3U)? It could contain the url to the video, that could be visible in the list of presentations. Clicking the link would do the same operation as opening the share video and paste in the url.

**Comment by antobinary** [comment]
You could include the links in your slides, see BBB 3.0.0-beta.6, likely earlier too.

![image](https://github.com/user-attachments/assets/6d314779-d775-4e34-857a-a844dc9f4cb4)
