### ISSUE TITLE
Audio Android App bbb-android

### ISSUE THREAD

**Issue by bigbluebutton-issue-import** [bigbluebutton/bigbluebutton#1932]
Originally reported on Google Code with ID 1178

```
Not working audio in app of the market.

Video works fine.
And audio not working and not lisent another speakers.

Thank you.
```

Reported by `info@redbcn.info` on 2012-03-14 18:26:48

**Comment by GhaziTriki** [comment]
Audio works in the latest implementation of the AIR mobile client.

**Comment by capilkey** [comment]
This issue wasn't about the AIR client, it was reported for the old Java Android app. We've never supported the Java app so I'm going to close this.
