### ISSUE TITLE
Provide json object over websocket

### ISSUE THREAD

**Issue by ayechan-maung** [bigbluebutton/bigbluebutton#19337]
**Please provide Json object to send over websocket for mobile**
Start user typing method is working with this kind of object

    {
      "msg": "method",
      "method": "startUserTyping",
      "params": [
        chatID == null
            ? "public"
            : ""
      ],
    }
 But when I try to send chat message with this object, it's nothing happen, got any update messages.

    {
      "msg": "method",
      "method": "sendGroupChatMsg",
      "params": [
         "chatId"
        {
          "color": "0",
          "correlationId": msgId,
          "sender": {
                     "id": senderID,
                     "name": meetingInfo.fullUserName,
            },
          "message": chat.content,
        }
      ]
    }

  Please provide or where do I get that resources explicitly.

**Comment by antobinary** [comment]
Hi @ayechan-maung 
What branch of BigBlueButton are you working off of?
I believe you are trying to send a message we typically send via Redis PubSub as a server-to-client Meteor.call message...

If you are building a mobile app, could you please confirm you've checked https://github.com/mconf/bbb-mobile-sdk or https://github.com/bigbluebutton/bigbluebutton-tablet-sdk

**Comment by ayechan-maung** [comment]
> Hi @ayechan-maung What branch of BigBlueButton are you working off of? I believe you are trying to send a message we typically send via Redis PubSub as a server-to-client Meteor.call message...
> 
> If you are building a mobile app, could you please confirm you've checked https://github.com/mconf/bbb-mobile-sdk or https://github.com/bigbluebutton/bigbluebutton-tablet-sdk

Yes, I am building a mobile app using Flutter, I've checked the repositories you mentioned, that SDK for React-Native.  In flutter, using flutter-webrtc is to have signalling service and send messages over websocket. That's why I need json object to send message as a parameter.

**Comment by antobinary** [comment]
We're transitioning away from Meteor (which implements its own DDP protocol for client<->server event data transfer over websocket) to using GraphQL. BBB 2.7 has only Meteor. BBB 3.0 (under development, about to be alpha.1) is roughly halfway into the transition. The refactor should be complete likely by mid 2024. This means that if you go the Meteor route you may need to redo all of your work within a year to have your app function with a 3.0+ BBB server. If you go the graphql route, it's more future proof but you will likely have to implement things in the order we refactor them.
You may want to check branch v3.0.x-release and set up a dev environment on it. This way you can inspect the event message transfer and see if it fits your needs.

**Comment by ayechan-maung** [comment]
> We're transitioning away from Meteor (which implements its own DDP protocol for client<->server event data transfer over websocket) to using GraphQL. BBB 2.7 has only Meteor. BBB 3.0 (under development, about to be alpha.1) is roughly halfway into the transition. The refactor should be complete likely by mid 2024. This means that if you go the Meteor route you may need to redo all of your work within a year to have your app function with a 3.0+ BBB server. If you go the graphql route, it's more future proof but you will likely have to implement things in the order we refactor them. You may want to check branch v3.0.x-release and set up a dev environment on it. This way you can inspect the event message transfer and see if it fits your needs.

After I followed your instructions, I've got some request, response from inspecting over websocket. I am closing the issue. Thank you for your help.
