### ISSUE TITLE
Breakout Rooms

### ISSUE THREAD

**Issue by bigbluebutton-issue-import** [bigbluebutton/bigbluebutton#1934]
Originally reported on Google Code with ID 1180

```
As BigBlueButton spreads one of the features we're increasingly asked to implement is
breakout rooms.  See

  https://groups.google.com/d/msg/bigbluebutton-users/GNrf2W3redk/j65vpz3jQdMJ

The feature should enable the teacher to

  1.  Group students 
  2.  Assign the groups to separate rooms (each room is now a distinct BigBlueButton
session)
  3.  Monitor the activity
  4.  Bring everyone back to the same main room

The breakout rooms could have a shared chat with the main room.

At the moment, other features (such as record and playback) are a higher priority than
breakout rooms, but it is our intent to implement them as part of our roadmap to BigBlueButton
1.0.
```

Reported by `ffdixon` on 2012-03-15 12:17:11

**Comment by RastogiSaurabh** [comment]
If polling is available in next release, it will be a great feature to have.

**Comment by umeshs88** [comment]
Hi, 

Is there any update on breakout rooms?

**Comment by ffdixon** [comment]
Hi Umesh,

We're currently working on breakout rooms now.  It's not ready for beta yet, but the work is underway as part of the 1.1 development cycle.

**Comment by umeshs88** [comment]
Thanks Fred!

When is next version due?

**Comment by ffdixon** [comment]
Hi Umesh,

In our project, we release on quality (not dates).  We don't have a date for the release of BigBlueButton 1.1-beta.  We are currently in the development phase.  For more information on our release process, see [http://docs.bigbluebutton.org/support/faq.html#development-priorities](http://docs.bigbluebutton.org/support/faq.html#development-priorities)

**Comment by piiapelimanni** [comment]
Hi there, 
Does bigbluebutton have any breakout room facility yet? Or is this still under development? I am just trying to decide on which conferencing tool to use in our project and breakouts would be essential. I found it quite hard to find information on all the available features. 
Thanks,
Piia

**Comment by antobinary** [comment]
Hi @piiapelimanni. Take a look at the plans for BBB 1.1 https://groups.google.com/d/msg/bigbluebutton-dev/2OLdUbi2K_w/1pzOZoppAwAJ
The feature 'Breakout rooms' is currently under development

**Comment by piiapelimanni** [comment]
Thank you @antobinary !
