### ISSUE TITLE
Creating Presentation Failed

### ISSUE THREAD

**Issue by mstruminski** [bigbluebutton/bigbluebutton#19343]
**Describe the bug**
Upload of Presentations do not work

**To Reproduce**
Upload a docx Documnet as Presentation.

**Expected behavior**
See the converted result

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser Firefox
 - Version  120.0.1

[
[bbb-web.log](https://github.com/bigbluebutton/bigbluebutton/files/13683724/bbb-web.log)
](url)

**Comment by mstruminski** [comment]
Problem with my DocX Document,

**Comment by hostbbb** [comment]
What version of BBB, is it all docs or just DocX?  Does this file upload on the demo.bigbluebutton.org server?

**Comment by mstruminski** [comment]
Nothing needs to be done. It was a mistake on my part. It was an unfortunate combination of OneDrive and a document.
There is no error in BBB.
