### ISSUE TITLE
Repo focal-270-2.7.4 is broken

### ISSUE THREAD

**Issue by mstruminski** [bigbluebutton/bigbluebutton#19441]
**Describe the bug**
https://ubuntu.bigbluebutton.org/focal-270-2.7.4 bigbluebutton-focal main

**Installation type**
aptitude full-upgrade -d (only Download)

**Console output**
See screenshot
![Bildschirmfoto 2024-01-17 um 08 51 28](https://github.com/bigbluebutton/bigbluebutton/assets/100774169/fba91ee8-2312-4a1a-b871-9ab98cd5ee47)

**Comment by antobinary** [comment]
Hi! I received a couple similar reports at roughly the same time and am investigating.

**Comment by mstruminski** [comment]
OK, good luck.

**Comment by antobinary** [comment]
Hi @mstruminski 
Could you please try it now. Should be functional again.

**Comment by mstruminski** [comment]
It is functional again.
