### ISSUE TITLE
[3.0] - Join parameter bbb_hide_presentation_on_join inconsistent

### ISSUE THREAD

**Issue by antonbsa** [bigbluebutton/bigbluebutton#19456]
**Describe the bug**
I first noticed when it failed on the Ci run of #19436. Running locally I could randomly reproduce the same behavior. It looks like sometimes it's being applied correctly, and sometimes it doesn't

**To Reproduce**
1. Create a meeting
2. Join a moderator with `bbb_hide_presentation_on_join=true`
3. Join an attendee with `bbb_hide_presentation_on_join=true`
4. Check session state: both users should join with the presentation minimized

___

**Screenshots**
### Expected behavior:
![Screenshot from 2024-01-18 15-24-14](https://github.com/bigbluebutton/bigbluebutton/assets/56703993/cb6d3c2b-c1ad-48c7-a802-b19a1d75ffd6)

### Wrong behavior
![Screenshot from 2024-01-18 15-23-36](https://github.com/bigbluebutton/bigbluebutton/assets/56703993/6c65694c-6c86-4cb9-8939-ac8084f9746d)

**Comment by JoVictorNunes** [comment]
I think `bbb_hide_presentation_on_join` doesn't exist anymore. It was replaced by `userdata-bbb_hide_presentation_on_join`. I've tried out `userdata-bbb_hide_presentation_on_join=true` locally and it worked fine.

**Comment by antonbsa** [comment]
Yes, the correct parameter is the one with `userdata`. I've checked on the test code and was able to confirm that we use the right parameter:

https://github.com/bigbluebutton/bigbluebutton/blob/032ece8cf3dc878024cb3da7db092447d6cd2e60/bigbluebutton-tests/playwright/parameters/parameters.spec.js#L461-L466

https://github.com/bigbluebutton/bigbluebutton/blob/032ece8cf3dc878024cb3da7db092447d6cd2e60/bigbluebutton-tests/playwright/parameters/constants.js#L44

___

I'll retry to reproduce the reported behavior and comment below any new evidence
