### ISSUE TITLE
Upload the exported users list to presentation breaks the whiteboard

### ISSUE THREAD

**Issue by GhaziTriki** [bigbluebutton/bigbluebutton#19505]
**Describe the bug**
After exporting the users list to a txt file, then uploading it to the presentation the application shows an error `invalid range in character class`

**To Reproduce**
1. Go to users list.
2. Click on the user options menu and select "Save user names"
3. Upload the exported txt file as a presentation.
4. The application shows "An error occured"

**Expected behavior**
The application should be able to convert the text file.

**Actual behavior**
The application shows an error with a "Reload" button.

**Screenshots**
![image](https://github.com/bigbluebutton/bigbluebutton/assets/4991088/8b848546-c3be-41bf-a0bf-065a4fd7ac8f)

**BBB version:**
Tested under BigBlueButton Server 2.7.3 and 2.7.4 and can reproduce the error. Tested under 2.6.5 and works fine.

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Browser Firefox
 - Version 122.0 (64 bits)

**Additional context**
JS console attached.
[console-export-2024-1-24_19-42-18.txt](https://github.com/bigbluebutton/bigbluebutton/files/14042476/console-export-2024-1-24_19-42-18.txt)

Exported file attached
[bbb-Ghazi TRIKI's Room[users-list]_2024-01-24_19-37.txt](https://github.com/bigbluebutton/bigbluebutton/files/14042478/bbb-Ghazi.TRIKI.s.Room.users-list._2024-01-24_19-37.txt)

**Comment by GhaziTriki** [comment]
Thanks for the fix @ramonlsouza

**Comment by antobinary** [comment]
Note: Not able to reproduce on BBB 3.0 so not porting it from 2.7.5 to 3.0.0-alpha.5
