### ISSUE TITLE
BigBlueButton 3.0.0-alpha2 attempts to load assets from to umpkg.com

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#19547]
**Describe the bug**
In BigBlueButton 3.0.0-alpha2 the client is attempting to load assets from unpkg.com.  Here's the error from the browser log

```
Access to image at 'https://unpkg.com/@tldraw/assets@2.0.0-alpha.18/icons/icon/geo-rectangle.svg' from origin 'https://droplet-7519.meetbbb.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

This is probably from our packaging of tldraw attempting to load geo-rectangle.svg remotely.

**Expected behavior**
All assets loaded from the BigBlueButton server.

**Screenshots**

<img width="1008" alt="image" src="https://github.com/bigbluebutton/bigbluebutton/assets/290351/6cfef00d-77e8-444f-afe2-bccedfa05190">

**BBB version:**

```
BigBlueButton Server 3.0.0-alpha.2 (380)
                    Kernel version: 5.15.0-67-generic
                      Distribution: Ubuntu 22.04.3 LTS (64-bit)
                            Memory: 8140 MB
                         CPU cores: 4

```

Tested using Chrome Version 121.0.6167.85 (Official Build) (arm64)

**Comment by Mylinuxforyou** [comment]
Hello Community,

I'm encountering an issue while trying to install BigBlueButton Version 3 on Proxmox. The installation gets stuck at the following step:

perl

Adding bbb-html5.service to autostart using systemd
Created symlink /etc/systemd/system/multi-user.target.wants/bbb-html5.service → /lib/systemd/system/bbb-html5.service.
Created symlink /etc/systemd/system/bigbluebutton.target.wants/bbb-html5.service → /lib/systemd/system/bbb-html5.service.

The installation does not proceed, and there are no apparent error messages in the logs. The status of the "bbb-html5" service does not indicate any issues.

Has anyone in the community encountered similar problems during the installation of BigBlueButton on Proxmox? Any suggestions or tips would be greatly appreciated.

I'm thankful for any assistance you can provide!

**Comment by Mylinuxforyou** [comment]
Hello Community,

I'm encountering an issue while trying to install BigBlueButton Version 3 on Proxmox. The installation gets stuck at the following step:

perl

Adding bbb-html5.service to autostart using systemd
Created symlink /etc/systemd/system/multi-user.target.wants/bbb-html5.service → /lib/systemd/system/bbb-html5.service.
Created symlink /etc/systemd/system/bigbluebutton.target.wants/bbb-html5.service → /lib/systemd/system/bbb-html5.service.

The installation does not proceed, and there are no apparent error messages in the logs. The status of the "bbb-html5" service does not indicate any issues.

Has anyone in the community encountered similar problems during the installation of BigBlueButton on Proxmox? Any suggestions or tips would be greatly appreciated.

I'm thankful for any assistance you can provide!

**Comment by antobinary** [comment]
@Mylinuxforyou please re-post this in https://groups.google.com/g/bigbluebutton-setup - the best place to receive assistance with BBB setup.
And please include even more info -- specs, bbb-install.sh command (you can mask th email and domain), full logs of the installation.
This comment is unrelated to the current thread so I will hide it.

**Comment by KDSBrowne** [comment]
It looks like tldraw has an API to override the urls used to fetch the icon svg's using `setDefaultUiAssetUrls`

Example:

```
  import { setDefaultUiAssetUrls } from "@tldraw/tldraw";

  const customAssetUrls = {
    icons: {
      'geo-rectangle': '/html5client/svgs/bbb_audio_icon.svg',
    },
  };

  setDefaultUiAssetUrls(customAssetUrls)
```

**Comment by KDSBrowne** [comment]
Also might be good to monitor this issue https://github.com/tldraw/tldraw/issues/2668
