### ISSUE TITLE
Ghost user rendering on BBB 2.7 (UI layer only)

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#19564]
**Describe the bug**
If you get promoted to moderator later in the session your client may render a couple of extra users in the participants list -- users who were in the session earlier on but left. They appear as viewers, not in audio. This does not happen every time.
However, if you try initiating a private chat with such a user, your client will crash. If you refresh, it will crash again, likely when trying to show the open chat groups.

**To Reproduce**
Steps to reproduce the behavior: **note that this is not always reproducible for me neither locally nor on the same server the issue was spotted**
1. Join a meeting as moderator
2. Join as viewer1
3. Join as viewer2
4. Viewer1 leaves
5. moderator promotes viewer2 to also be moderator
6. viewer2's participants list refreshes/rerenders and:

**Expected behavior**
viewer1 is not in the userlist

**Actual behavior**
viewer1 is in the userlist

**Screenshots**
![Screenshot from 2024-02-02 11-16-44](https://github.com/bigbluebutton/bigbluebutton/assets/6312397/c3c25a1a-3cd0-4761-afb8-db274aa62493)

**BBB version:**
BigBlueButton 2.7.4

**Additional context**
Tracking the error down points to https://github.com/bigbluebutton/bigbluebutton/blob/v2.7.x-release/bigbluebutton-html5/imports/ui/components/user-list/service.js#L315

I am not able to trigger it locally. Otherwise my plan was to inspect `user`, and at the very least check if we have an `id` property. Something like `!!user.id && user.id !== ....`

**Comment by Ithanil** [comment]
Good catch, I stumbled across this once but unfortunately didn't immediately take notes on how it happened. And a few weeks later I couldn't remember...

**Comment by antobinary** [comment]
Merging into https://github.com/bigbluebutton/bigbluebutton/issues/20251
