### ISSUE TITLE
[3.0] bbb-graphql-middleware listen on 0.0.0.0

### ISSUE THREAD

**Issue by fuu0** [bigbluebutton/bigbluebutton#19574]
**Describe the bug**
The component bbb-graphql-middleware listen on 0.0.0.0, configuration options are only for the port available 

**To Reproduce**
ss -tlpn | grep 8378
LISTEN 0      4096                                     *:8378             *:*    users:(("bbb-graphql-mid",pid=66076,fd=3)) 

**Expected behavior**
There should be something like BBB_GRAPHQL_MIDDLEWARE_LISTEN_IP in /etc/default/bbb-graphql-middleware

**Actual behavior**
bbb-graphql-middleware listen always on 0.0.0.0

**Additional context**

**Comment by fuu0** [comment]
It would be nice if the default configuration is safe: so the default listen IP should be 127.0.0.1 and with a configuration option like "BBB_GRAPHQL_MIDDLEWARE_LISTEN_IP" it could be changeable to 0.0.0.0

**Comment by gustavotrott** [comment]
Fixed on #19619

Thanks for reporting it @fuu0!!
