### ISSUE TITLE
[3.0] source-code-pro-latin-400-normal.woff2 font missing, 404

### ISSUE THREAD

**Issue by fuu0** [bigbluebutton/bigbluebutton#19579]
**Describe the bug**
During entering the room, the font source-code-pro-latin-400-normal.woff2 should be loaded.
But the file is missing, also on test30.bigbluebutton.org

**Comment by fuu0** [comment]
The Issue should be related to this change by @ramonlsouza 
https://github.com/bigbluebutton/bigbluebutton/commit/1cc60fda31576a751ac25771d4daa418b6d6f36b
I think it should be
href="fonts/SourceSansPro/source-code-pro-latin-400-normal.woff2?v=VERSION"
and the font must be placed under /bigbluebutton-html5/public/fonts/SourceSansPro from the used Font Package - should be https://github.com/adobe-fonts/source-code-pro

**Comment by antobinary** [comment]
![Screenshot from 2024-02-05 10-24-47](https://github.com/bigbluebutton/bigbluebutton/assets/6312397/1c49bd3a-b994-4d0c-a9df-a914084a52af)

**Comment by JoVictorNunes** [comment]
Seems it is not being used anymore.
