### ISSUE TITLE
[3.0] Right click menu on whiteboard keeps displayed

### ISSUE THREAD

**Issue by antonbsa** [bigbluebutton/bigbluebutton#19598]
**Describe the bug**
Only able to close when pressing ESC or clicking out of whiteboard area

**Video**

https://github.com/bigbluebutton/bigbluebutton/assets/56703993/77c49c31-c8e4-40e4-baac-42f48ae99b11

**Comment by KDSBrowne** [comment]
This might be related https://github.com/tldraw/tldraw/pull/2355

**Comment by antobinary** [comment]
Merging into #21314
