### ISSUE TITLE
Add userdata parameter to automatically select the pen tool

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#19604]
**Is your feature request related to a problem? Please describe.**
When tutoring younger students, they may have troubles selecting the pen tool to interact with the teacher

**Describe the solution you'd like**
Add a parameter to the join API URL

```
userdata-pen-select=true
```

to have the pen tool selected by default.  

**Describe alternatives you've considered**
Wondering if we can do this as part of BigBlueButton 3.0 to pass in the override for bbb-html5.yml settings?

**Comment by Scroody** [comment]
I just finished testing this issue, and it looks like the `userdata-pen-select=true` is working properly!
