### ISSUE TITLE
Uploading toast is not working propperly

### ISSUE THREAD

**Issue by GuiLeme** [bigbluebutton/bigbluebutton#19629]
**Describe the bug**

The uploading phase of a presentation has duplicated items when it is shown in the toast notification system, as demonstrated by the video below:

https://github.com/bigbluebutton/bigbluebutton/assets/69865537/9785e7e2-6ac9-46d4-b4d3-db2f44c83b6f

It only happens when the uploading phase takes a little more time to complete than the usual, so to simulate it correctly one needs to modify the browser network status as done in the video above.

**To Reproduce**
1. Open a bbb meeting session and enter with a moderator (make sure they are presenter as well);
2. Open the network tab in the dev-tools of the browser it is running on and for the status (where "No throttling" might be selected) select "Slow 3G";
3. Open the presentation upload modal and select some presentation to be uploaded;
4. Click the "Confirm" button;
5. See error. 

**Expected behavior**
Presentation toast should show only the current status of the current presentation being uploaded, and the title of the toast must be coherent with respect to its status.

**Actual behavior**
Presentation toast is showing not only the current status of the presentation being uploaded but also a duplicate which contains a spinner and no more information. Also, the title does not match the current status of the presentation (It says presentation upload completed, when that's clearly not the case). 

**BBB version:**
$ sudo bbb-conf --check | grep BigBlueButton
BigBlueButton Server 3.0.0-alpha.3 (428)

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04;
 - Browser Chrome;

**Comment by JoVictorNunes** [comment]
Not reproducible on a BigBlueButton Server 3.0.0-alpha.7 (1074).

See what I get by following the provided steps:

[Screencast from 26-06-2024 09:46:14.webm](https://github.com/bigbluebutton/bigbluebutton/assets/62393923/b8ead421-12fb-4282-bfc3-9ad4c8afdf3a)

I also tried uploading a 4,7 MB presentation in slow 3G but couldn't reproduce it as well. Things look okay.
