### ISSUE TITLE
[3.0] When drawing and speaking the drawing cursor jumps on the whiteboard

### ISSUE THREAD

**Issue by gabriellpr** [bigbluebutton/bigbluebutton#19639]
**Describe the bug**
If the presenter is speaking and also drawing, at some point the drawing cursor will jump on the whiteboard, making the drawing look different than expected.

**To Reproduce**
1. Create a meeting
2. Join with a moderator
3. Start drawing then start to speak
4. The drawing cursor will jump.

https://github.com/bigbluebutton/bigbluebutton/assets/19312495/c56ee723-5e62-436b-a812-e0f10b28c1e4

**Comment by ramonlsouza** [comment]
may not be related to the talking indicator... I was able to reproduce it without joining audio

**Comment by gabriellpr** [comment]
After testing I concluded this issue does not occur anymore, and due to that the issue can be closed.
