### ISSUE TITLE
Error in bbb-rap-worker.log: `first_event_timestamp': undefined method `[]' for nil:NilClass (NoMethodError)\n

### ISSUE THREAD

**Issue by bigbluebutton-issue-import** [bigbluebutton/bigbluebutton#1964]
Originally reported on Google Code with ID 1210

```
Full error log:
/var/log/bigbluebutton/bbb-rap-worker.log:E, [2012-04-24T01:41:39.316836 #18052] ERROR
-- : Error: stderr: ["/usr/local/bigbluebutton/core/lib/r
ecordandplayback/generators/events.rb:24:in `first_event_timestamp': undefined method
`[]' for nil:NilClass (NoMethodError)\n", "\tfrom /usr/loc
al/bigbluebutton/core/lib/recordandplayback/generators/audio.rb:154:in `process_events'\n",
"\tfrom /usr/local/bigbluebutton/core/lib/recordandp
layback/generators/audio_processor.rb:12:in `process'\n", "\tfrom /usr/local/bigbluebutton/core/scripts/process/slides.rb:30:in
`<main>'\n"]
```

Reported by `calvin.walton@kepstin.ca` on 2012-04-24 14:02:11

**Comment by 1ibo** [comment]
I also encountered this problem, does anyone know how to solve it?

**Comment by darinkaqt** [comment]
Hi, I also encountered this problem, I don't know how to solve this.

**Comment by antobinary** [comment]
Feel free to open a new issue - this one was closed 6+ years ago on a very different code base. Fill out the template for new issues with as much info as possible. Hope that helps!

**Comment by darinkaqt** [comment]
Hi, where can find the template for new issues? @antobinary

**Comment by antobinary** [comment]
https://github.com/bigbluebutton/bigbluebutton/issues/new/choose
