### ISSUE TITLE
[2.7] Breakout room invitation option missing from user dropdown

### ISSUE THREAD

**Issue by schristoforou** [bigbluebutton/bigbluebutton#19644]
**Describe the bug**
Since upgrading to 2.7, we can no longer see the "Breakout room invitation" option in the user management cog after creating breakout rooms

**To Reproduce**
1. Create a room, have a few users enter
2. Create a couple of breakout rooms, assign users to them
3. Try to invite a new user to a breakout room via the user management interface
4. Option not shown in dropdown menu, only able to add via breakout rooms UI.

**Expected behavior**
Being able to invite user to breakout via user management dropdown.

**Actual behavior**
Breakout room invitation option missing from dropdown

**Screenshots**
![Screenshot from 2024-02-19 13-19-59](https://github.com/bigbluebutton/bigbluebutton/assets/62561650/4dbd6fd9-994c-4038-af49-e12b4dd1613a)

**BBB version:**
BigBlueButton Server 2.7.4 (533)

**Desktop (please complete the following information):**
 - OS: Windows, Linux
 - Browser: Chrome, Firefox
 - Version: Latest

**Comment by Ithanil** [comment]
Furthermore, regular users are not able to "Ask to join" a breakout room. They can only join breakout rooms by being assigned or when the flag "allow users to choose rooms" is set (allowing them to enter freely).
