### ISSUE TITLE
[3.0] - bbl-playback-video cannot be installed in ubuntu 22.04

### ISSUE THREAD

**Issue by ccomincini** [bigbluebutton/bigbluebutton#19661]
On a fresh installation with ubuntu 22.04 after the end, of the bbb-install script, if you try to install additional recording processing formats you can install video, screen share and notes without problems, but video does not install.

the command 
`sudo apt-get install bbb-playback-video ` 
ends with the following error:
`The following packages have unmet dependencies:
 bbb-playback-video : Depends: bbb-presentation-video but it is not installable`

**Installation type**
```
BigBlueButton Server 3.0.0-alpha.3 (416)
                    Kernel version: 5.15.0-94-generic
                      Distribution: Ubuntu 22.04.4 LTS (64-bit)
```

**Firewall and IP address type**
Public static IP, no firewall active.

**Comment by antobinary** [comment]
Hi @ccomincini 
This is one of the remaining items for BBB 3.0. Expect to see this package in several weeks. Swithcing to tldraw v2 led to quite a few changes being required here, work is underway.

**Comment by antobinary** [comment]
It is installable in BBB v3.0.0-beta.1+.
