### ISSUE TITLE
404 Not Found Playback Record

### ISSUE THREAD

**Issue by cedjer47** [bigbluebutton/bigbluebutton#19719]
Hi
I record a meeting and it is in Greenlight records page, but when I click on presentation button, to play video, 404 error page occurred.

http://hide/playback/presentation/2.3/1bfc8861a581d3fb6d2091a77da0ef4478e7377c-1709300138662

**Comment by hostbbb** [comment]
not an issue, not sure what versions of greenlight/bbb.   best to go to bigbluebutton-setup forum in google and post the details.
is it just this one meeting,  or all of them etc... Again post in forum..  wont get many responses here.
