### ISSUE TITLE
Broken display of presentations

### ISSUE THREAD

**Issue by mstruminski** [bigbluebutton/bigbluebutton#19731]
**Describe the bug**
After uploading slides, the client's display is displayed distorted.

**To Reproduce**
1. Open a new browser and join the conference.
2. Go to Upload presentations
3. Upload a presentation (docx)
5. After reloading the browser window with the broken display, everything is fine again.

**Screenshots**
![Bildschirmfoto 2024-03-04 um 09 42 45](https://github.com/bigbluebutton/bigbluebutton/assets/100774169/a3bd6373-fb75-4e83-b726-0d397f73c3a2)

After reloading Browser-Window
![Bildschirmfoto 2024-03-04 um 09 43 39](https://github.com/bigbluebutton/bigbluebutton/assets/100774169/cf42095d-fb42-40f0-9b94-a731b625d163)

**BBB version:**
BigBlueButton Server 3.0 Alpha4

**Desktop (please complete the following information):**
 - OS:  MacOS 14.3.1
 - Browser Firefox 
 - Version 123

**Comment by ffdixon** [comment]
Thanks for reporting @mstruminski.  This could be a bug in the alpha.  To compare, are you able to reproduce the issue on 

  https://demo.bigbluebutton.org/

**Comment by mstruminski** [comment]
It is not on the demo server with version 2.7.4, only with Alpha4 of BBB 3.0.

**Comment by Wladimir-N** [comment]
> Thanks for reporting @mstruminski. This could be a bug in the alpha. To compare, are you able to reproduce the issue on
> 
> https://demo.bigbluebutton.org/

It also has problems. I am attaching an example of a document whose conversion ends with an error. The problem exists on 2.7.3 and 2.7.4, on 2.7.2 everything is fine. I froze the package
bbb-libreoffice-docker 1:2.7-5

Everything is fine on this version
[kr-f.doc.zip](https://github.com/bigbluebutton/bigbluebutton/files/14519610/kr-f.doc.zip)

**Comment by gabriellpr** [comment]
After testing I concluded this issue does not occur anymore, and due to that the issue can be closed.

**Comment by antobinary** [comment]
![image](https://github.com/user-attachments/assets/8974285d-f78c-4c4b-979e-732850195330)
Testing with the file from above:
