### ISSUE TITLE
getRecordings API does NOT work

### ISSUE THREAD

**Issue by dashbee** [bigbluebutton/bigbluebutton#19745]
**Describe the bug**
After the video conference recording ends, the "getRecordings" is called, but the result indicates that there is no recording. However, the recording file exists in the server's folder.

**To Reproduce**
1. Records the meeting, and completes the recording and meeting.
2. Checks the recorded files
3. Calls api getRecordings with meetingID and recordingID
4. Gets the answer: No recordings

**Expected behavior**
API result shows the recording record.

**Actual behavior**
API result shows No recording record.

**Screenshots**
![Ids](https://github.com/bigbluebutton/bigbluebutton/assets/7558420/2dd5f504-3fea-4e29-bcd9-07a2c196345a)
![recording completed](https://github.com/bigbluebutton/bigbluebutton/assets/7558420/03824b2a-0f41-4dbe-bf6d-8ac300881e21)
![api](https://github.com/bigbluebutton/bigbluebutton/assets/7558420/cc12ee21-bc5e-4f85-8797-4b04a652a832)
![result](https://github.com/bigbluebutton/bigbluebutton/assets/7558420/7fa937f2-f482-4e8d-83a1-d6ab96d4b407)

**Desktop (please complete the following information):**
Windows
BBB: V2.3.18

**Additional context**

**Comment by Ithanil** [comment]
May I kindly suggest to update to a recent, supported version (i.e. at least BBB 2.6) and see if you still have an issue to report? BBB 2.3 is almost 3 years old now and end of life since almost 2 years.
