### ISSUE TITLE
The recordings were not being processed

### ISSUE THREAD

**Issue by huangxitao** [bigbluebutton/bigbluebutton#19806]
**Describe the bug**
on v2.3.18 the recordings were not being processed

**Screenshots**
<img width="1221" alt="image" src="https://github.com/bigbluebutton/bigbluebutton/assets/29117003/c84be54a-7c19-44f8-9eb9-0fa91dba80cf">

<img width="1238" alt="image" src="https://github.com/bigbluebutton/bigbluebutton/assets/29117003/e6e59386-6c0f-45e5-8499-ae8427e2fe59">

Thank you in advance!

**Comment by antobinary** [comment]
Hi! BBB 2.3 has been out of support for years. Please upgrade to 2.7. If still encountering issues please post a more detailed description at https://groups.google.com/g/bigbluebutton-dev
