### ISSUE TITLE
[3.0] - Promoting/demoting a user zooms its presentation

### ISSUE THREAD

**Issue by antonbsa** [bigbluebutton/bigbluebutton#19872]
**Video**

https://github.com/bigbluebutton/bigbluebutton/assets/56703993/f2d0114d-7aa4-4379-bc0d-d354ae64508d

**Comment by KDSBrowne** [comment]
This was fixed in #19733

**Comment by antonbsa** [comment]
> This was fixed in https://github.com/bigbluebutton/bigbluebutton/pull/19733

Indeed! Tried to hit the same behavior but I wasn't able with the PR changes
