### ISSUE TITLE
[3.0] - Changing language stop webcam sharing

### ISSUE THREAD

**Issue by antonbsa** [bigbluebutton/bigbluebutton#19871]
**To Reproduce**
1. Join in a meeting;
2. Start webcam sharing;
3. Make sure to set a layout different than Grid;
4. Go to `Options > Settings > Application Language` and change it

**More**
_I was able to reproduce only in one meeting a layout change too (always going to Grid)_

**Video**

https://github.com/bigbluebutton/bigbluebutton/assets/56703993/16d20e37-1ace-4675-a46a-16c3b3656a95

**Comment by JoVictorNunes** [comment]
I can't reproduce on BigBlueButton Server 3.0.0-alpha.6 (838) (development) nor on dev30 server. Can you confirm, please?
Maybe it's fixed by recent refactors.

**Comment by antonbsa** [comment]
I just tried and it doesn't seem to be reproducible anymore!
