### ISSUE TITLE
[3.0] Clear status icon not working (+)

### ISSUE THREAD

**Issue by antonbsa** [bigbluebutton/bigbluebutton#19885]
**Describe the bug**
- `Clear all status icon` button doesn't work;
- `Clear status` of a specific user doesn't have any effect;
- Even when the `userStatus` config is disabled, the `Clear all status icon` button is shown

**Videos**

https://github.com/bigbluebutton/bigbluebutton/assets/56703993/3ab6c288-aa5e-4746-8696-1066577b22db

https://github.com/bigbluebutton/bigbluebutton/assets/56703993/aa0a8a7a-f8fd-4b0a-9eef-76d9be737a66

https://github.com/bigbluebutton/bigbluebutton/assets/56703993/7280fe0e-6a64-461f-90ac-106d7bd6a83c

**Comment by ramonlsouza** [comment]
user status is going to be removed (#20267)
