### ISSUE TITLE
[2.7.6] Media error 2200 starting webcams

### ISSUE THREAD

**Issue by caniwi** [bigbluebutton/bigbluebutton#19897]
**Describe the bug**
After upgrading Big Blue Button from 2.7.5 to 2.7.6, webcams fail with Media server failed to process request (error 2200).  This was working fine on v2.7.5.

**To Reproduce**
1. Go to a meeting room and press share webcam.
2. Preview pop up window for webcam appears with camera operating.
3. Press Start sharing
4. Screen adjusts briefly but no webcam appears and the pop up message "Media server failed.....(error 2200) appears. 

**Expected behavior**
Webcam starts and shares.

**Actual behavior**
No webcam, audio is working.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux Ubuntu 20.04 and 22.04
 - Browser  Chromium 122.0.6261.128 Firefox 124.0.1 (64-bit)

**Additional context**
```
bbb-conf --check

BigBlueButton Server 2.7.6 (584)
                    Kernel version: 5.4.0-174-generic
                      Distribution: Ubuntu 20.04.6 LTS (64-bit)
                            Memory: 16381 MB
                         CPU cores: 4

/etc/bigbluebutton/bbb-web.properties (override for bbb-web)
/usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties (bbb-web)
       bigbluebutton.web.serverURL: https://uat-bbb1.catalystdemo.net.nz
                defaultGuestPolicy: ALWAYS_ACCEPT
              defaultMeetingLayout: CUSTOM_LAYOUT

/etc/nginx/sites-available/bigbluebutton (nginx)
                       server_name: <url>
                              port: 80, [::]:80
                              port: 443 ssl

/opt/freeswitch/etc/freeswitch/vars.xml (FreeSWITCH)
                       local_ip_v4: 10.15.8.38
                   external_rtp_ip: <public IP>
                   external_sip_ip: <public IP>

/opt/freeswitch/etc/freeswitch/sip_profiles/external.xml (FreeSWITCH)
                        ext-rtp-ip: $${external_rtp_ip}
                        ext-sip-ip: $${external_sip_ip}
                        ws-binding: :5066
                       wss-binding: :7443

UDP port ranges

                        FreeSWITCH: 16384-24576
                           kurento: 24577-32768
                    bbb-webrtc-sfu: 24577-32768
                    bbb-webrtc-recorder: 24577-32768

/usr/local/bigbluebutton/core/scripts/bigbluebutton.yml (record and playback)
                     playback_host: bigbluebutton.example.com
                 playback_protocol: http
                            ffmpeg: 4.2.7-0ubuntu0.1

/usr/share/bigbluebutton/nginx/sip.nginx (sip.nginx)
                        proxy_pass: <public IP>
                          protocol: https

/usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml (bbb-webrtc-sfu)
/etc/bigbluebutton/bbb-webrtc-sfu/production.yml (bbb-webrtc-sfu - override)
    mediasoup.webrtc.*.announcedIp: <public IP>
  mediasoup.plainRtp.*.announcedIp: <public IP>
                        kurento.ip: 10.15.8.38
                       kurento.url: ws://127.0.0.1:8888/kurento
                 freeswitch.sip_ip: 10.15.8.38
                  recordingAdapter: Kurento
               recordScreenSharing: true
                     recordWebcams: true
                  codec_video_main: VP8
               codec_video_content: VP8

/etc/bbb-webrtc-recorder/bbb-webrtc-recorder.yml (bbb-webrtc-recorder)
/etc/bigbluebutton/bbb-webrtc-recorder.yml (bbb-webrtc-recorder - override)
               debug: false
               recorder.directory: /var/lib/bbb-webrtc-recorder

/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml (HTML5 client)
/etc/bigbluebutton/bbb-html5.yml (HTML5 client config override)
                             build: 249
                        kurentoUrl: wss://uat-bbb1.catalystdemo.net.nz/bbb-webrtc-sfu
            defaultFullAudioBridge: fullaudio
           defaultListenOnlyBridge: fullaudio
                    sipjsHackViaWs: false

/usr/share/bbb-web/WEB-INF/classes/spring/turn-stun-servers.xml (STUN Server)
                              stun: stun1.<our external stun server name>:3478

/usr/share/bbb-web/WEB-INF/classes/spring/turn-stun-servers.xml (STUN Server)
                              stun: stun2.<our external stun server name>:3478


# Potential problems described below

# Warning: The setting of <public IP> for proxy_pass in
#
#    /usr/share/bigbluebutton/nginx/sip.nginx
#
# does not match the local IP address (10.15.8.38).
# (This is OK if you've manually changed the values)

We see the following error message in /var/log/bbb-webrtc-sfu/bbb-webrtc-sfu.log
```

```
{"level":50,"time":"2024-03-25T23:14:47.079Z","pid":105993,"hostname":"cat-porwal-uat-bbb1","mod":"video","userId":"w_sjlrkx64lvcc","roomId":"17921","internalMeeting
Id":"d9898e3ae1c67c9bcccf86d2bb8efa99a42dee35-1711408470257","streamName":"3ae1db6b-b125-4e22-9940-000b499c541fw_sjlrkx64lvcc_6997187fbe34e5701b181b88c42be6bcb448f7d
3c5d7d2af777ac8f983851f8b-share","status":"MEDIA_STARTING","role":"share","cameraId":"w_sjlrkx64lvcc_6997187fbe34e5701b181b88c42be6bcb448f7d3c5d7d2af777ac8f983851f8b
","connectionId":"3ae1db6b-b125-4e22-9940-000b499c541f","sessionId":"w_sjlrkx64lvcc-w_sjlrkx64lvcc_6997187fbe34e5701b181b88c42be6bcb448f7d3c5d7d2af777ac8f983851f8b-s
hare","error":{"type":"error","code":2019,"message":"MEDIA_SERVER_GENERIC_ERROR","details":"invalid RtpHeaderExtensionUri: http://www.webrtc.org/experiments/rtp-hdre
xt/playout-delay","stack":"TypeError: invalid RtpHeaderExtensionUri: http://www.webrtc.org/experiments/rtp-hdrext/playout-delay\n    at rtpHeaderExtensionUriToFbs (/
usr/local/bigbluebutton/bbb-webrtc-sfu/node_modules/mediasoup/node/lib/RtpParameters.js:270:19)\n    at serializeRtpParameters (/usr/local/bigbluebutton/bbb-webrtc-s
fu/node_modules/mediasoup/node/lib/RtpParameters.js:25:21)\n    at createProduceRequest (/usr/local/bigbluebutton/bbb-webrtc-sfu/node_modules/mediasoup/node/lib/Tran
sport.js:951:76)\n    at WebRtcTransport.produce (/usr/local/bigbluebutton/bbb-webrtc-sfu/node_modules/mediasoup/node/lib/Transport.js:348:31)\n    at MediasoupSDPEl
ement.produce (/usr/local/bigbluebutton/bbb-webrtc-sfu/lib/mcs-core/lib/adapters/mediasoup/base-element.js:363:52)\n    at MediasoupSDPElement._processProducerSDPOff
er (/usr/local/bigbluebutton/bbb-webrtc-sfu/lib/mcs-core/lib/adapters/mediasoup/sdp-element.js:99:33)\n    at process.processTicksAndRejections (node:internal/proces
s/task_queues:95:5)\n    at async MediasoupSDPElement._processMediaOffer (/usr/local/bigbluebutton/bbb-webrtc-sfu/lib/mcs-core/lib/adapters/mediasoup/sdp-element.js:
274:28)\n    at async Promise.all (index 0)\n    at async MediasoupSDPElement.processSDPOffer (/usr/local/bigbluebutton/bbb-webrtc-sfu/lib/mcs-core/lib/adapters/medi
asoup/sdp-element.js:318:30)","operation":"publish"},"msg":"Video start procedure failed due to MEDIA_SERVER_GENERIC_ERROR"}
`````

**Comment by ffdixon** [comment]
Hi @caniwi,

Did the hostname of the server change by chance?  Does the error occur with both FireFox and Chrome?  Can you try disabling the TURN server by editing `/etc/bigbluebutton/turn-stun-servers.xml` and changing

```
        <property name="turnServers">
            <set>
                <ref bean="turn0"/>
                <ref bean="turn1"/>
            </set>
        </property>
```

to

```
        <property name="turnServers">
            <set>
                <!-- ref bean="turn0"/ -->
                <!-- ref bean="turn1"/ -->
            </set>
        </property>
```

and restart BigBlueButton and let us know if the error still persists.

**Comment by caniwi** [comment]
Hi Fred,
It happens in both Chromium and Firefox.  Commenting out the turnServers as suggested has not changed the behaviour.

**Comment by caniwi** [comment]
> /usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml



> @caniwi please share any custom bbb-webrtc-sfu configurations you're applying.
> 
>     * /etc/bigbluebutton/bbb-webrtc-sfu/production.yml
> 
>     * /usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml
> 
> 
> Unredacted (apart from IPs/sensitive info).

here is production.yaml

` cat /etc/bigbluebutton/bbb-webrtc-sfu/production.yml 
freeswitch:
  ip: <Public IP>
  sip_ip: 10.15.8.38
  esl_password: <password>
mediasoup:
  workers: "auto"
  worker:
    # "debug", "warn", "error", "none"
    logLevel: "error"
    # + svc, simulcast, srtp, ...
    logTags:
      - "bwe"
      - "dtls"
      - "ice"
      - "info"
      - "rtcp"
      - "rtp"
      - "rtx"
      - "srtp"
    rtcMinPort: 24577
    rtcMaxPort: 32768
    #dtlsCertificateFile:
    #dtlsPrivateKeyFile:
  promExportWorkerResourceUsage: false
  router:
    # TODO fetch from conference-media-specs
    mediaCodecs:
      - kind: "audio"
        mimeType: "audio/opus"
        preferredPayloadType: 111
        clockRate: 48000
        channels: 2
        parameters:
          minptime: 10
          useinbandfec: 1
        rtcpFeedback:
          - type: "transport-cc"
      - kind: "audio"
        mimeType: "audio/telephone-event"
        preferredPayloadType: 101
        clockRate: 8000
      - kind: "audio"
        mimeType: "audio/PCMU"
        preferredPayloadType: 0
        clockRate: 8000
        rtcpFeedback:
          - type: "transport-cc"
      - kind: 'audio'
        mimeType: 'audio/ISAC'
        clockRate: 32000
        preferredPayloadType: 103
        rtcpFeedback:
          - type: "transport-cc"
      - kind: "video"
        mimeType: "video/VP8"
        preferredPayloadType: 96
        clockRate: 90000
        rtcpFeedback:
          - type: "transport-cc"
          - type: "goog-remb"
          - type: "ccm"
            parameter: "fir"
          - type: "nack"
          - type: "nack"
            parameter: "pli"
  webrtc:
    # announcedIP => it's the host public IPv4 in case the machine is
    # behind a 1:1 NAT
    # ip => the address on which mediasoup will bind its RTC sockets
    listenIps:
      - ip: "0.0.0.0"
        announcedIp: "<Public IP>"
        # - ip: <some-ipv6>
    # equivalent to Kurento's/libnice's ice-udp/niceAgentIceUdp
    enableUdp: true
    # equivalent to Kurento's/libnice's ice-tcp/niceAgentIceTcp
    enableTcp: false
    # candidate priority mangling; makes sense to keep this enabled
    # even more when ice-tcp is enabled as well
    preferUdp: true
    # TODO: fetch from conference-media-specs
    initialAvailableOutgoingBitrate: 100000
  plainRtp:
    # announcedIP => it's the host public IPv4 in case the machine is
    # behind a 1:1 NAT
    # ip => the address on which mediasoup will bind its plain RTP sockets
    # This is pretty similar in intent to webrtc.listenIps with two diffs:
    #   - only applies to plain transports (RTP)
    #   - it's not an array, so just one option
    listenIp:
      ip: "0.0.0.0"
      announcedIp: "<Public IP>"
    # Whether RTCP should use RTPs transport.
    # False probably doesn't work yet in the adapter
    rtcpMux: true
    # Port inference through COMEDIA
    comedia: true
  webRtcHeaderExts:
    - uri: 'urn:ietf:params:rtp-hdrext:toffset'
      id: 1
    - uri: 'http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time'
      id: 2
    - uri: 'http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01'
      id: 4
    - uri: 'http://www.webrtc.org/experiments/rtp-hdrext/playout-delay'
      id: 5
    - uri: 'http://www.webrtc.org/experiments/rtp-hdrext/video-content-type'
      id: 6
    - uri: 'http://www.webrtc.org/experiments/rtp-hdrext/video-timing'
      id: 7
    - uri: 'http://www.webrtc.org/experiments/rtp-hdrext/color-space'
      id: 8
    - uri: 'urn:ietf:params:rtp-hdrext:sdes:mid'
      id: 9
    - uri: 'urn:ietf:params:rtp-hdrext:sdes:rtp-stream-id'
      id: 10
    - uri: 'urn:ietf:params:rtp-hdrext:sdes:repaired-rtp-stream-id'
      id: 11
  recorder:
    ffmpeg:
      # UDP, internal only. Doesn't need to be open in the firewall, but should
      # be a dedicated range.
      recMinPort: 50000
      recMaxPort: 51000
      inputOptions:
        - "-protocol_whitelist file,rtp,udp"
        - "-probesize 1000000"
        - "-analyzeduration 1000000"
      outputOptions:
        - '-f webm'
        - '-flags +global_header'
localIpAddress: 10.15.8.38`


here is defaults.yml

`cat /usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml
kurento:
  - ip: 10.15.8.38
    url: ws://127.0.0.1:8888/kurento
    # mediaType: (main|audio|content)
    ipClassMappings:
      local:
      private:
      public:
    options:
      failAfter: 5
      request_timeout: 30000
      response_timeout: 30000
# Number of attemps of connecting to the configured kurento instances the first
# time. Infinity means it tries forever until it's able to connect. Default is Infinity.
kurentoStartupRetries: Infinity
# Whether to allow Kurento to process mDNS ICE candidates
kurentoAllowMDNSCandidates: false
# Whether to track KMS's ICE state changes for every peer.
# Disabled by default for now until we trace the perf. impact of it
kurentoTrackIceStateChanges: false
# balancing-strategy: can be either ROUND_ROBIN or MEDIA_TYPE. The MEDIA_TYPE only
# works properly if you annotated the configured kurento instances in the
# 'kurento' config parameter with a mediaType field (main|audio|content) which
# will specify what will each server handle. Default is ROUND_ROBIN
balancing-strategy: ROUND_ROBIN
# Allow media offloading to Kurento instances with mismatched media types
kurentoAllowMediaTypeMix: false
video-transposing-ceiling: 50
audio-transposing-ceiling: 100
acceptSelfSignedCertificate: false
redisHost: 127.0.0.1
redisPort: "6379"
# Uncomment to set a password if Redis requires auth.
# redisPassword: foobared
clientPort: "3008"
clientHost: 127.0.0.1
# Whether RPCs and WS conns should be rejected/shutdown on user info header
# anomalies
wsStrictHeaderParsing: true
# Time (ms) between server-initiated ping-pong checks
wsHeartbeatInterval: 20000
# wsServerOptions: see https://github.com/websockets/ws/blob/HEAD/doc/ws.md#new-websocketserveroptions-callback).
# It's a passthrough mapping of all config literal (strings, booleans, numbers).
wsServerOptions:
  maxPayload: 51200
mediaFlowTimeoutDuration: 30000
mediaStateTimeoutDuration: 30000
requestQueueTimeout: 30000
screenshareSubscriberSpecSlave: false
screensharePlayStartEnabled: true
screenshareServerSideAkkaBroadcast: true
screenshareIgnoreMediaThresholds: false
audioIgnoreMediaThresholds: true
videoIgnoreMediaThresholds: false
videoSubscriberSpecSlave: false
# Following three configurations: see media-server-adapters config
# to get a list of implemented adapters. The configuration values
# here are the adapter's name of choice
videoMediaServer: mediasoup
screenshareMediaServer: mediasoup
audioMediaServer: mediasoup
fullAudioEnabled: true
transparentListenOnly: true
fullAudioProxyActiveDirection: true
audioIceRestartEnabled: false
# RTP|WebRTC. Dictates how the FS <-> [audioMediaServer] bridge is established:
# via plain RTP or via a WebRTC-backed RTP stream
# WebRTC should be used for environments where the bridge is between external
# servers AND when mediasoup is being used
fsBridgeMode: 'RTP'
# pliOnConnect: whether to send a PLI when a new subscriber joins
#  amount: max amount of PLIs to send. If 0, it won't send any PLIs (default)
#  interval: interval between PLIs (in ms)
#  (e.g.: amount: 3, interval: 2000 => send 3 PLIs every 2 seconds)
pliOnConnect:
  amount: 0
  interval: 2000
# Whether to record screen raw files
recordScreenSharing: true
# Whether to record camera raw files
recordWebcams: true
# Fire a max of 3 PLIs over 6 seconds if recording stops flowing for 500 ms
recordingPliOnNotFlowing: false
# recordingBasePath (DEPRECATED): Base path where recording raw files will be stored
# WARNING => THE FOLLOWING PARROT CEASED TO BE
recordingBasePath: /var/kurento
# recordingAdapter: Adapter to be used to record live streams.
# Possible values:
#   - 'native': same adapter as the source's (eg.: Kurento -> Kurento)
#   - Kurento: use Kurento for recording (eg.: mediasoup -> Kurento)
#   - bbb-webrtc-recorder: use bbb-webrtc-recorder
#     (e.g.: mediasoup -> bbb-webrtc-recorder). EXPERIMENTAL
recordingAdapter: Kurento
# Adapter to be used if #recordingAdapter fails and #recordingUseFallbackAdapter is true
recordingFallbackAdapter: bbb-webrtc-recorder
# Whether to use the fallback adapter if the main adapter fails
recordingFallbackOnFailure: false
# Whether a recording copy should be created with #recordingFallbackAdapter
# regardless of whether the main adapter fails or not
# This is a development/test feature and should not be used in production
# environments. The generated copies will have a -copy suffix in their names,
# won't have any recording metadata registered and should not be processed
recordingCarbonCopy: false
# Recording dry-run mode: always record regardless of meeting state and
# *do not* register any recording metadata.
# This is a development/test feature and should not be used in production envs.
recordingDryRun: false
# The base recording profile for video and screen sharing
# WEBM_VIDEO_ONLY|WEBM_AUDIO_ONLY|WEBM_FULL
recordingMediaProfile: WEBM_VIDEO_ONLY
# The base recording container format.
# webm|mp4
recordingFormat: webm
# bbb-webrtc-recorder integration configs
bbbWebrtcRecorder:
  channels:
    # POV: bbb-webrtc-sfu
    subscribe: from-bbb-webrtc-recorder
    publish: to-bbb-webrtc-recorder
  heartbeatInterval: 5000
  heartbeatDelay: 1000
  connectionTimeout: 5000
# Recording event keys expiry time in Redis
# 14 days is the default
redisExpireTime: 1209600
# Time to wait before ejecting an user which has the autoLeave flag marked
# as true and has no more media sessions under its ownership
mcsUserEjectionTimer: 60000
# Time to wait before destroying a room (on all scenarios)
mcsRoomDestructionTimer: 90000
# mcs-core entrypoint configured on nginx
mcs-path: /mcs
mcs-port: 3010
mcs-host: 127.0.0.1
mcs-address: 127.0.0.1
mcs-ws-timeout: 30000
freeswitch:
  ip: 10.15.8.38
  sip_ip: 10.15.8.38
  port: 5066
  esl_ip: 127.0.0.1
  esl_port: 8021
  #esl_password: FOOBAR
  handleExternalConnections: false
  ipClassMappings:
    local:
    private:
    public:
log:
  # trace|debug|info|warn|error
  level: info
  # Whether to log to stdout
  stdout: true
  # Whether to log to a file
  file: true
  filename: /var/log/bbb-webrtc-sfu/bbb-webrtc-sfu.log
modules:
  - path: ./lib/mcs-core/process.js
    name: core
    dedicated: true
    # IPC can be either native|redis right now. Defaults to native
    ipc:
      mode: native
      options:
      # inboundChannel: to-mcs-core
      # outboundChannel: from-mcs-core
  - path: ./lib/screenshare/ScreenshareProcess.js
    name: screenshare
    dedicated: true
    ipc:
      mode: native
      options:
      # inboundChannel: to-sfu-screenshare
      # outboundChannel: from-sfu-screenshare
  - path: ./lib/video/VideoProcess.js
    name: video
    dedicated: true
    ipc:
      mode: native
      options:
      # inboundChannel: to-sfu-video
      # outboundChannel: from-sfu-video
  - path: ./lib/audio/audio-process.js
    name: fullaudio
    routingAliases:
      - audio
    dedicated: true
    ipc:
      mode: native
      options:
      # inboundChannel: to-sfu-audio
      # outboundChannel: from-sfu-audio
# media-server-adapters: path could refer to a npm module
media-server-adapters:
  - path: kurento/kurento.js
    name: Kurento
  - path: freeswitch/freeswitch.js
    name: Freeswitch
  - path: mediasoup/mediasoup-adapter.js
    name: mediasoup
# strategies: path could refer to a npm module
strategies:
#- path: ./voice-switching-handler.js
# name: VOICE_SWITCHING

# Codec values (codec_video_main, codec_video_content, codec_audio):
# it'll force the specified codec.
# Put the 'ANY' value to prevent forcing a specific codec without the _priority options.
# For the 'ANY' option, there's a trio of optional configuration where you are
# able to specify the priority codec to force in a lenient way (codec_*_priority).
# If codec_*_priority is undefined or not found in the media description,
# no specific codec will be forced (base ANY behaviour).
# If the priority codec is found in the media description, any codec
# that doesn't match it will be filtered out (ie it will act as if the priority
# codec was forced).
# If you wanna add other codecs (e.g.: VP9)
# add it to the list with its specifiers. If the codec isn't in the list,
# it'll default to the specifier values in codec_*_priority OR VP8,
# but still force the entered codec option.
# P.S.: _video_main refers to webcam/main video content, _video_content refers to
# screenshare/content:slides streams.
conference-media-specs:
  codec_video_main: VP8
  codec_video_main_priority: VP8
  codec_video_content: VP8
  codec_video_content_priority: VP8
  codec_audio: ANY
  codec_audio_priority: OPUS
  H264:
    profile_level_id: "42e01f"
    packetization_mode: "1"
    level_asymmetry_allowed: "1"
    tias_main: "300000"
    as_main: "300"
    tias_content: "1500000"
    as_content: "1500"
    max_mbps_main: "0"
    max_fs_main: "0"
    max_br_main: "0"
    max_mbps_content: "0"
    max_fs_content: "12288"
    max_br_content: "0"
  VP8:
    tias_main: "300000"
    as_main: "300"
    tias_content: "1500000"
    as_content: "1500"
  OPUS:
    useinbandfec: "1"
    maxaveragebitrate: "30000"
    maxplaybackrate: "48000"
    ptime: "20"
    minptime: "10"
    maxptime: "40"
kurentoRembParams:
  rembOnConnect: 300
  upLosses: 12
  decrementFactor: 0.5
  thresholdFactor: 0.8
# Munges/removes the SDP REMB rtcp-fb support attribute (ie tries to disable REMB)
kurentoRemoveRembRtcpFb: false
# kurentoAllowedCandidateIps: optional configuration. List of VALID IPs to be used
# to define valid outbound ICE candidates.
# This is a short-term optimization to reduce the number of candidates sent to
# the client by filtering out anything that isn't in this list
kurentoAllowedCandidateIps:
#- <ipv4|ipv6>
# mediaThresholds: mandatory configuration. Establishes type-agnostic media thresholds
# that when hit will make the server refuse to negotiate new medias.
# Any attemps to inject medias past the thresholds will return an error with code
# 2002 and message MEDIA_SERVER_NO_RESOURCES.
# The threshold priority order is global -> perRoom -> perUser. Value 0 means unlimited
# (default). An optional API parameter may be sent on pub/sub calls (ignoreThresholds)
# to make the media ignore the configured thresholds. This is used here for recording
# and audio medias.
mediaThresholds:
  global: 0
  perRoom: 0
  perUser: 0
# Whether to allow duplicate externalUserId's on join. If allowed, join requests with
# a externalUserId specified in the optional parameters will associate the new connection
# with a pre-existing user (if it exists), or create a new one.
# This will create a new virtual link between the request
# and the pre-existing user with a unique internal user ID. The user will be
# cleared from the system when a leave call for it is sent OR it has the autoLeave
# optional parameter set to true and all of its medias were cleared
allowDuplicateExtUserId: true
ejectOnUserLeft: true
permissionProbes: true
destroyRoomOnEject: true
# Direct Prometheus instrumentation. Disabled by default.
prometheus:
  enabled: false
  # mcs-core specific metrics, top level of prometheus dictionary for now
  host: localhost
  port: 3014
  path: '/metrics'
  collectDefaultMetrics: false
  # Main process metrics endpoint (main == websocket entrypoint, module manager)
  main:
    host: localhost
    port: 3016
    path: '/metrics'
    collectDefaultMetrics: false
  # Video process metrics endpoint (video == webcam req handler, ...)
  video:
    host: localhost
    port: 3026
    path: '/metrics'
    collectDefaultMetrics: false
  screenshare:
    host: localhost
    port: 3022
    path: '/metrics'
    collectDefaultMetrics: false
  audio:
    host: localhost
    port: 3024
    path: '/metrics'
    collectDefaultMetrics: false
    holdHistograms: false
mediasoup:
  # mediasoup.workers: "auto"|"cores"|<Number>.
  #   * The number of mediasoup workers for general use (media type agnostic, shared pool).
  #   * "auto" is: ceil((min(nproc,32) * 0.8) + (max(0, nproc - 32) / 2))
  #   * "cores" is: nproc (the host's core count as in os.cpus().length)
  #   * Use a number if you want to override the number of workers.
  #   * Strings other than "auto" and "cores" are ignored :).
  #   * The default value is "auto".
  workers: "auto"
  # mediasoup.dedicatedMediaTypeWorkers:
  #   audio: "auto"|"cores"|<Number>
  #   main: "auto"|"cores"|<Number>
  #   content: "auto"|"cores"|<Number>
  #
  #   * The number of mediasoup workers to use for a specific media type.
  #     They are SEPARATED from the shared pool (mediasoup.workers). Streams
  #     of a specific media type will always land in its dedicated pool if one is set.
  #   * "auto" and Number semantics are the same as #mediasoup.workers.
  dedicatedMediaTypeWorkers:
    audio: 0
    main: 0
    content: 0
  # mediasoup.workerPriorities:
  #   audio: <os.constants.priority> | [19,-20]
  #   main: <os.constants.priority> | [19,-20]
  #   content: <os.constants.priority> | [19,-20]
  #
  #   * Sets the NICE level for each worker type. The app needs the correct user
  #   caps to be effective
  #
  #workerPriorities:
  #  audio: PRIORITY_HIGH
  #  main: PRIORITY_NORMAL
  #  content: PRIORITY_LOW
  worker:
    # "debug", "warn", "error", "none"
    logLevel: "error"
    # + svc, simulcast, srtp, ...
    logTags:
      - "bwe"
      - "dtls"
      - "ice"
      - "info"
      - "rtcp"
      - "rtp"
      - "rtx"
      - "srtp"
    rtcMinPort: 24577
    rtcMaxPort: 32768
    #dtlsCertificateFile:
    #dtlsPrivateKeyFile:
  promExportWorkerResourceUsage: false
  promExportRtpScores: false
  router:
    # TODO fetch from conference-media-specs
    mediaCodecs:
      - kind: "audio"
        mimeType: "audio/opus"
        preferredPayloadType: 111
        clockRate: 48000
        channels: 2
        parameters:
          maxaveragebitrate: 30000
          maxplaybackrate: 48000
          ptime: 20
          minptime: 10
          maxptime: 40
          useinbandfec: 1
        rtcpFeedback:
          - type: "transport-cc"
      - kind: "audio"
        mimeType: "audio/telephone-event"
        preferredPayloadType: 101
        clockRate: 8000
      - kind: "audio"
        mimeType: "audio/PCMU"
        preferredPayloadType: 0
        clockRate: 8000
        rtcpFeedback:
          - type: "transport-cc"
      - kind: 'audio'
        mimeType: 'audio/ISAC'
        clockRate: 32000
        preferredPayloadType: 103
        rtcpFeedback:
          - type: "transport-cc"
      - kind: "video"
        mimeType: "video/VP8"
        preferredPayloadType: 96
        clockRate: 90000
        rtcpFeedback:
          - type: "transport-cc"
          - type: "goog-remb"
          - type: "ccm"
            parameter: "fir"
          - type: "nack"
          - type: "nack"
            parameter: "pli"
  webrtc:
    # announcedIP => it's the host public IPv4 in case the machine is
    # behind a 1:1 NAT
    # ip => the address on which mediasoup will bind its RTC sockets
    listenIps:
      - ip: "0.0.0.0"
        announcedIp: 10.15.8.38
        # - ip: <some-ipv6>
    # equivalent to Kurento's/libnice's ice-udp/niceAgentIceUdp
    enableUdp: true
    # equivalent to Kurento's/libnice's ice-tcp/niceAgentIceTcp
    enableTcp: false
    # candidate priority mangling; makes sense to keep this enabled
    # even more when ice-tcp is enabled as well
    preferUdp: true
    # iceConsentTimeout: ICE consent timeout (in seconds). If 0 it is disabled.
    iceConsentTimeout: 30
  plainRtp:
    # announcedIP => it's the host public IPv4 in case the machine is
    # behind a 1:1 NAT
    # ip => the address on which mediasoup will bind its plain RTP sockets
    # This is pretty similar in intent to webrtc.listenIps with two diffs:
    #   - only applies to plain transports (RTP)
    #   - it's not an array, so just one option
    listenIp:
      ip: "0.0.0.0"
      announcedIp: 10.15.8.38
    # Whether RTCP should use RTPs transport.
    # False probably doesn't work yet in the adapter
    rtcpMux: true
    # Port inference through COMEDIA
    comedia: true
  bitrate:
    # Default per transport max incoming bitrate (bps)
    defaultMaxIncomingBitrate: 1500000
    # Default per transport max outgoing bitrate (bps)
    defaultMaxOutgoingBitrate: 1500000
    # Default per transport initial available outgoing bitrate (bps)
    defaultInitialAvailableOutgoingBitrate: 600000
  webRtcHeaderExts:
    - uri: 'urn:ietf:params:rtp-hdrext:toffset'
      id: 1
    - uri: 'http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time'
      id: 2
    - uri: 'http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01'
      id: 4
    - uri: 'urn:ietf:params:rtp-hdrext:sdes:mid'
      id: 9
    - uri: 'urn:ietf:params:rtp-hdrext:sdes:rtp-stream-id'
      id: 10
    - uri: 'urn:ietf:params:rtp-hdrext:sdes:repaired-rtp-stream-id'
      id: 11
  recorder:
    ffmpeg:
      # UDP, internal only. Doesn't need to be open in the firewall, but should
      # be a dedicated range.
      recMinPort: 50000
      recMaxPort: 51000
      inputOptions:
        - "-protocol_whitelist file,rtp,udp"
        - "-probesize 1000000"
        - "-analyzeduration 1000000"
      outputOptions:
        - '-f webm'
        - '-flags +global_header'`

**Comment by caniwi** [comment]
> @caniwi please share any custom bbb-webrtc-sfu configurations you're applying.
> 
>     * /etc/bigbluebutton/bbb-webrtc-sfu/production.yml
> 
>     * /usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml
> 
> 
> Unredacted (apart from IPs/sensitive info).

Please find attached.
[production.yml.txt](https://github.com/bigbluebutton/bigbluebutton/files/14768920/production.yml.txt)
[default.yml.txt](https://github.com/bigbluebutton/bigbluebutton/files/14768922/default.yml.txt)

**Comment by caniwi** [comment]
> @caniwi also, make sure that if you're overriding the `mediasoup.webRtcHeaderExts` config in bbb-webrtc-sfu, it should contain _at most_ the ones located in https://github.com/bigbluebutton/bbb-webrtc-sfu/blob/040a8ca0844ed2e86d8b163799b893d1e1c0bdde/config/default.example.yml#L467-L479.
> 
> The error above implies there are invalid header extensions configured. The fact that it throws became a thing with a mediasoup update, but it's expected.

It seems removing the excess webRtcHeaderExts from the config and a bbb-conf --restart has resolved the issues.  Had to remove ids 5,6,7,8.

Thanks for your help.

**Comment by ffdixon** [comment]
Thanks @prlanzarin
