### ISSUE TITLE
Welcome to BigBlueButton!

### ISSUE THREAD

**Issue by smerchla** [bigbluebutton/bigbluebutton#19898]
Hello, I have install BBB on local server, after installation I have received only "Welcome to BigBlueButton!" message. Please help solve issue!
Installation process:
OS-Ubuntu 20.04, Core 8, RAM 16GB
sudo ufw allow 80
sudo ufw allow 443

wget -qO- https://raw.githubusercontent.com/bigbluebutton/bbb-install/v2.7.x-release/bbb-install.sh | bash -s -- -w -v focal-270 -s bbb.mydomain.com -e it@mydomain.com

**Comment by Davka** [comment]
This is not an error, but normal behavior. You have to connect a frontend

**Comment by smerchla** [comment]
Thank you, but how can I do it?

**Comment by ffdixon** [comment]
Please read the documentation.  BigBlueButton itself doesn't provide a front-end; rather, it provides an API that various front-ends can use.  

An example of a front-end is GreenLight (this is provided by the BigBlueButton project as a separate component).

  https://docs.bigbluebutton.org/greenlight/v3/install/

This component is very easy to install with `bbb-install.sh` by adding the `-g` options.  See

  https://github.com/bigbluebutton/bbb-install?tab=readme-ov-file#install-greenlight

**Comment by smerchla** [comment]
> Please read the documentation. BigBlueButton itself doesn't provide a front-end; rather, it provides an API that various front-ends can use.
> 
> An example of a front-end is GreenLight (this is provided by the BigBlueButton project as a separate component).
> 
> https://docs.bigbluebutton.org/greenlight/v3/install/
> 
> This component is very easy to install with `bbb-install.sh` by adding the `-g` options. See
> 
> https://github.com/bigbluebutton/bbb-install?tab=readme-ov-file#install-greenlight

**Comment by smerchla** [comment]
> Please read the documentation. BigBlueButton itself doesn't provide a front-end; rather, it provides an API that various front-ends can use.
> 
> An example of a front-end is GreenLight (this is provided by the BigBlueButton project as a separate component).
> 
> https://docs.bigbluebutton.org/greenlight/v3/install/
> 
> This component is very easy to install with `bbb-install.sh` by adding the `-g` options. See
> 
> https://github.com/bigbluebutton/bbb-install?tab=readme-ov-file#install-greenlight

Hi ffdixon, Thank you !!! it worked. I have use this comand: wget -qO- https://raw.githubusercontent.com/bigbluebutton/bbb-install/v2.7.x-release/bbb-install.sh | bash -s -- -v focal-270 -s bbb.mydomain.com -e admin@mydomain.com -w -g -k
