### ISSUE TITLE
Add the name of the user below their webcam

### ISSUE THREAD

**Issue by bigbluebutton-issue-import** [bigbluebutton/bigbluebutton#1993]
Originally reported on Google Code with ID 1239
```
What do you think about add the name of the participants below their camera.
```

Reported by `sergi79` on 2012-05-31 07:20:18

<hr>
 * *Attachment: [suggestion.JPG](https://storage.googleapis.com/google-code-attachments/bigbluebutton/issue-1239/comment-0/suggestion.JPG)*

**Comment by ffdixon** [comment]
The user's name now displays at the top of their webcam video. See

  http://docs.bigbluebutton.org/1.0/10overview.html#improved-video-dock
