### ISSUE TITLE
Missing Translation in de.json

### ISSUE THREAD

**Issue by FluffyUnicorn161** [bigbluebutton/bigbluebutton#19941]
**Describe the bug**
There are some missing translations in BigBlueButton 3.0 for the german language  

**Expected behavior**
A list of the missing translations:
"app.navBar.leaveMeetingBtnLabel": "Konferenz verlassen",
"app.chat.dropdown.showWelcomeMessage": "Zeige die Willkommensnachricht an",
"app.poll.noAnswerWarning": "Um eine Umfrage zu veröffentlichen, wird mindestens eine Antwort benötigt",
"app.navBar.optionsDropdown.leaveSessionLabel": "Konferenz verlassen",
 "app.navBar.optionsDropdown.endMeetingLabel": "Konferenz beenden",
"app.navBar.optionsDropdown.fullscreenLabel": "Vollbild-Anwendung",
"app.navBar.optionsDropdown.settingsLabel": "Einstellungen",
"app.navBar.optionsDropdown.aboutLabel": "Versionsinfo",
"app.navBar.optionsDropdown.helpLabel": "Hilfe",
"app.navBar.optionsDropdown.hotkeysLabel": "Tastenkombinationen",

**BBB version:**
BigBlueButton Server [v3.0.0-alpha.5]

**Comment by ffdixon** [comment]
Thanks for reporting.  We use transifex to community source all translations.  Would you be willing to update transifex with the correct translations -- we pull in the latest translations when we release each build.

For steps, see 

  https://docs.bigbluebutton.org/development/localization/

**Comment by antobinary** [comment]
We have not created a Transifex project for BBB 3.0 yet. This will be done circa 3.0.0-beta.1 (to minimize wasting translator's efforts when we tweak strings, which we still do lots of).

**Comment by antobinary** [comment]
![image](https://github.com/user-attachments/assets/b00fe254-4517-4e68-a20a-345d3446cd21)
Resolved. The above is from BBB v3.0.0-beta.2.
