### ISSUE TITLE
Port userdata-bbb_multi_user_tools to tldraw

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#19961]
**Describe the bug**
Looks like we did not adapt the passable `join` parameters `userdata-bbb_presenter_tools=` and `userdata-bbb_multi_user_tools` to tldraw; As a result the listed parameters do not function. Let's fix this in BBB 3.0 and possibly backport.

Related: https://github.com/bigbluebutton/bigbluebutton/issues/16168

**To fix**
- [ ] adapt the code in bbb-html5 to support tldraw names of tools
- [ ] confirm `userdata-bbb_multi_user_pen_only` is functioning again (api mate)
- [ ] confirm `userdata-bbb_presenter_tools=` is functioning again (api mate)
- [ ] confirm `userdata-bbb_multi_user_tools=` is functioning again (api mate)
- [ ] adapt the documentation in https://github.com/bigbluebutton/bigbluebutton/blob/v3.0.0-alpha.5/docs/docs/administration/customize.md?plain=1#L1501-L1503 so that
  - [ ] `userdata-bbb_multi_user_tools=` lists in the description all the possible options plus an example. Something like: Pass in an array of permitted tools for non-presenters from `settings.yml`. The options we support are: `select`, `pan`, `draw`, `erase`, (`<remaining items>`). For example to only permit pen drawing and the eraser, pass  `userdata-bbb_multi_user_tools=erase,pen`
  - [ ] Do the same type of description with full list of accepted parameters and an example of the syntax for `userdata-bbb_multi_user_tools`

After the fix:
- @antobinary should document the change of the tools options (a paragraph in what's-new)
- @antobinary should possibly backport to BBB 2.7

**Comment by antonbsa** [comment]
Related automated tests:
- `Custom Parameters › Whiteboard › Multi Users Pen Only`
- `Custom Parameters › Whiteboard › Presenter Tools`
- `Custom Parameters › Whiteboard › Multi Users Tools`

They are currently skipped. After the fixes, they might need some updates and should be running correctly
