### ISSUE TITLE
Client memory consumption fluctuates significantly (leak?)

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#19977]
**Describe the bug**
Not sure how to reproduce exactly. I am filing the issue as a placeholder so we investigate further (or keep our eyes open).

Observation:
In a 15 users call with 7 webcams the memory used for my Chromium BBB tab was 260-330MB most of the time. However, at some point** it jumped to 500-520MB. The client was noticeably slower, unmute-mute action had slower reaction time.
Toggling the userlist closed (userlist+chat) dropped it to 260MB, opening the panels again (userlist, chat, shared notes) kept it at 260MB. So by just hiding+showing the panels we reset? halved the memory.

In the same meeting another user reported the client memory jumping from ~300MB to 500+ when grid mode was enabled locally. Reverting to Custom layout dropped the memory. Others tried it but could not reproduce.

Conclusion - something is going on memory-wise and more attention is needed in the area. We may try holding next call in a developer environment setting.

**BBB version:**
BigBlueButton 3.0.0-alpha.5+

**Comment by ramonlsouza** [comment]
grid mode high memory usage is likely fixed by #19996, other improvements in the area: #21323, #21186, #21106, #21043, #21068, #21069, #20720, #20702, ...
