### ISSUE TITLE
External video synchronization

### ISSUE THREAD

**Issue by BBBprelegent** [bigbluebutton/bigbluebutton#19981]
**Describe the bug**
If the external video comes from a source other than YouTube, it starts in a random place for each user and does not react to the speaker's actions.

**To Reproduce**
1. Log in as a speaker and turn on the external YouTube video.
2. Log in as user.
3. If the "speaker" pauses playback, resumes playback, moves the progress indicator, the "user" sees all these actions as expected.
4. If the "speaker" turns on an external video from any other source, the "user's" video starts in a random place and does not respond to the "speaker's" actions.

**Expected behavior**
External video from any source should behave like a YouTube video.

**Actual behavior**
An external video from a source other than YouTube starts in a random place and does not respond to the "speaker's" actions.

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: Windows 10/11
 - Browser: Edge, Firefox

**Smartphone (please complete the following information):**
not tested.

**Additional context**
Version: 2.3-2.6 - The external video behaved as expected.
Version: 2.7-2.8 - Not tested
Version: 2.9-3.0 - Bug occurred

**Comment by antobinary** [comment]
Hi @BBBprelegent 
Could you please include a link to some public video where the issue is reproducible?

**Comment by BBBprelegent** [comment]
For example: https://vimeo.com/channels/bestofstaffpicks/914391191

The issue is reproducible on any external video from: vimeo, dropbox, "direct link".
The issue is NOT reproducible on any external video from YouTube.
