### ISSUE TITLE
Presentation annotation Export failure

### ISSUE THREAD

**Issue by drnalasubra** [bigbluebutton/bigbluebutton#19990]
While I was trying to export the annotated presentation to any of the formats, as available in the option Iam facing '403 can't touch this' error message, The screenshot is attached for your kind reference.. Thank you..

**Comment by drnalasubra** [comment]
While 'exporting' to PDF / Word or to any other format, the attached error drops in.
<img width="824" alt="Screenshot 2024-04-11 073605" src="https://github.com/bigbluebutton/bigbluebutton/assets/114048004/36ceb04f-45f0-4e52-bce9-5250fcbcd485">

**Comment by antobinary** [comment]
Looks like your service provider is still using an older version of BigBlueButton - https://github.com/biggerbluebutton/bigbluebutton/branches/all
We are not affiliated with "biggerbluebutton"

If you are able to reproduce this on the currently supported BigBlueButton we can keep this open and look into fixing this.

Thanks for reporting.

**Comment by drnalasubra** [comment]
Hi
Thank you for your mail.
How do we switch to Bigbluebutton?
Your guidance is much appreciated.
Thanks and regards
Dr Nala

**Comment by antobinary** [comment]
Here's a list of the companies from BigBlueButton's website https://bigbluebutton.org/commercial-support/
Most of them offer hosting.
