### ISSUE TITLE
Users get 'lost' when allowing entry to meeting

### ISSUE THREAD

**Issue by donbowman** [bigbluebutton/bigbluebutton#20000]
**Describe the bug**

I am not 100% certain if this is server core or greenlight.
I am staging out the new v3.0.0-alpha.5.
If i put a 'large' number of users into the waiting to enter state, and then allow them in, some will get stuck and not enter the meeting. The user still sees the 'waiting, X in queue'.

**To Reproduce**
1. Start a meeting
2. In ~30 browser tabs on one or more machines with enough horsepower, join the meeting as a guest
3. In the moderator part of the meeting, select 'allow everyone' under waiting users
4. Observe the number of users in the left does not equal the number you had waiting, and, some are still waiting
these users are now stuck, you cannot manually allow them, if they refresh they still show as waiting. they must create a new session.

**Expected behavior**
All waiting users enter the meeting.

**Actual behavior**
about 10-20% of the users, randomly, are still in waiting.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04 and 24.04 destop
 - Browser Chrome, FIrefox

**Smartphone (please complete the following information):**
did not try

**Additional context**
I am not sure what logs to look in or where to diagnose it.
is it a problem in e.g. redis?  is a message getting dropped? How may i provide more info here.

Above, i said i was uncertain as to whether it was greenlight or core, i am not sure which manages these sessions.

**Comment by antobinary** [comment]
Hi @donbowman 
With the ~30 browser tabs are you trying to reproduce something from real world OR are you trying to push the limits by using only local resources? (not sure but) perhaps browsers cap how many tabs auto-react from is-waiting state...
Do you happen to know the behavior on a 2.7 server like test27.bigbluebutton.org?

**Comment by donbowman** [comment]
it happens w/ real users too (each 1 person 1 device), i'm just trying to reproduce it w/o having a bunch of people.
This did not happen on 2.7

**Comment by donbowman** [comment]
If i inspect the network tab of one of the stuck users, it calls usercurrent periodically. This in turn returns
```
{"user_current":[{"userId":"w_s6ub6mgn9asl","name":"1","guestStatus":"WAIT","guestStatusDetails":{"guestLobbyMessage":null,"positionInWaitingQueue":1},"meeting":{"name":"DB","logoutUrl":"https://test30.bigbluebutton.org/rooms/yy9-lty-cdi-0id/join"}}]}
```

so its not that the client is not polling, its that the server has the wrong status for the user.

```
curl 'https://test30.bigbluebutton.org/api/rest/usercurrent/'   -H 'accept: */*'   -H 'accept-language: en-CA,en-GB;q=0.9,en-US;q=0.8,en;q=0.7'   -H 'content-type: application/json'   -H 'cookie: JSESSIONID=676675ABD4FDEA370B1D7C680388DA9D; _greenlight-3_0_session=XshIIo5Tiqe5Ur1yMa6FomOp%2FaNtVtvV1NG5kX6upo%2Bom%2F62K30hW74hojlS9Gc%2B8wY0Y7zoI%2Be77SsBk6Xoc8CLLdtdjlofUdNLbADUTCedDO6q5pLSmqUfhUhh6gm1K5cyfyOvkOjsO6DFQnyzvWjuJwiv3BRdg%2BBi0G71pkGbahBPvtOdaL9VZws92lqY2FxrIYV0IziLsDkuQh5oyGR7XWxUVHmf4UUTwFJ5JbNnhXZaalBZ%2FCbl37bxIf1NkSg559UnpVAF18WbdEjgSKoLewLQRIk6TbOwI5eVtg%3D%3D--VfIp%2BNdDGogv%2F4IX--QYObZOZ%2FUPlaOgT0dQq6kg%3D%3D; sessionID='   -H 'dnt: 1'   -H 'referer: https://test30.bigbluebutton.org/html5client/guestWait?sessionToken=ddcebu64imnqa9av'   -H 'sec-ch-ua: "Google Chrome";v="123", "Not:A-Brand";v="8", "Chromium";v="123"'   -H 'sec-ch-ua-mobile: ?0'   -H 'sec-ch-ua-platform: "Linux"'   -H 'sec-fetch-dest: empty'   -H 'sec-fetch-mode: cors'   -H 'sec-fetch-site: same-origin'   -H 'sec-gpc: 1'   -H 'user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36'   -H 'x-session-token: ddcebu64imnqa9av' ; echo
{"user_current":[{"userId":"w_s6ub6mgn9asl","name":"1","guestStatus":"WAIT","guestStatusDetails":{"guestLobbyMessage":null,"positionInWaitingQueue":1},"meeting":{"name":"DB","logoutUrl":"https://test30.bigbluebutton.org/rooms/yy9-lty-cdi-0id/join"}}]}
```

**Comment by donbowman** [comment]
some more observations...

it does not appear to matter if i use the 'allow everyone', or, click on them one by one, slowly, or quickly. some will just become stuck.

I now have 0 clients connected (all tabs closed), but i still show 69 'waiting' users.

if i click allow, i get this message in bbb-apps-akka/bbb-apps-akka.log (but no action).

```
analytics -- {"envelope":{"name":"GuestsWaitingApprovedMsg","routing":{"meetingId":"16fb43551d860377703ac0f487b8eeb211b2b934-1713044665018","userId":"w_ee9sez12a2m1"},"timestamp":1713045545889},"core":{"header":{"name":"GuestsWaitingApprovedMsg","meetingId":"16fb43551d860377703ac0f487b8eeb211b2b934-1713044665018","userId":"w_ee9sez12a2m1"},"body":{"guests":[{"guest":"w_bikfecyeughh","status":"ALLOW"},{"guest":"w_jfc6vfjdup1x","status":"ALLOW"},{"guest":"w_nw2wawsupbnd","status":"ALLOW"},{"guest":"w_ppykxa70vvzl","status":"ALLOW"},{"guest":"w_lqllibsowcxs","status":"ALLOW"},{"guest":"w_c9wf7eqfn7si","status":"ALLOW"},{"guest":"w_kjs1v8gfjmh9","status":"ALLOW"},{"guest":"w_9hnlgaznp35k","status":"ALLOW"},{"guest":"w_mi9t7oxtszel","status":"ALLOW"},{"guest":"w_3o1r32wekgvk","status":"ALLOW"},{"guest":"w_sy5mllkgdouk","status":"ALLOW"},{"guest":"w_psk3xtbhssb1","status":"ALLOW"},{"guest":"w_4mp0fhgigbtc","status":"ALLOW"},{"guest":"w_p4mcavzzjlgd","status":"ALLOW"},{"guest":"w_dicwjdwcj9q5","status":"ALLOW"},{"guest":"w_dk8coqejr6hi","status":"ALLOW"},{"guest":"w_a9e1l1ibqxhd","status":"ALLOW"},{"guest":"w_mhiijyyamjyr","status":"ALLOW"},{"guest":"w_2xmqlxhcksjx","status":"ALLOW"},{"guest":"w_ltztvspm7btx","status":"ALLOW"},{"guest":"w_ejnfssjttflv","status":"ALLOW"},{"guest":"w_m75uwyr3pz8r","status":"ALLOW"},{"guest":"w_yy0pcy5cw9ll","status":"ALLOW"},{"guest":"w_iu7wtmb2tnwm","status":"ALLOW"},{"guest":"w_nqcpznrbrv1q","status":"ALLOW"},{"guest":"w_fgud1bzduufz","status":"ALLOW"},{"guest":"w_jdu5fjgjt0l9","status":"ALLOW"},{"guest":"w_iwqb8zgui9hq","status":"ALLOW"},{"guest":"w_dtwscewixuit","status":"ALLOW"},{"guest":"w_iwpzzwx3sxmi","status":"ALLOW"},{"guest":"w_mxdpawoivezk","status":"ALLOW"},{"guest":"w_euw8m3cz5rvl","status":"ALLOW"},{"guest":"w_4jgeqajqozpx","status":"ALLOW"},{"guest":"w_b55cmd03ueuk","status":"ALLOW"},{"guest":"w_ggje6znzs3ak","status":"ALLOW"},{"guest":"w_37aiur0wzenj","status":"ALLOW"},{"guest":"w_7cxm5lu3cwpl","status":"ALLOW"},{"guest":"w_fnwbq6nwsztd","status":"ALLOW"},{"guest":"w_ei6ka3jj3ke0","status":"ALLOW"},{"guest":"w_gzt7qh4t3lvf","status":"ALLOW"},{"guest":"w_qnvzggjuozp9","status":"ALLOW"},{"guest":"w_ykxvul0dbepb","status":"ALLOW"},{"guest":"w_hgckuqx3vzlr","status":"ALLOW"},{"guest":"w_rckiqn2snlbs","status":"ALLOW"},{"guest":"w_wqej8jdztepx","status":"ALLOW"},{"guest":"w_cwiwmqvc0duk","status":"ALLOW"},{"guest":"w_vtqh3cmj5kw5","status":"ALLOW"},{"guest":"w_jybzlhb75fss","status":"ALLOW"},{"guest":"w_npbkqyq0mcex","status":"ALLOW"},{"guest":"w_vuxfmnjbabko","status":"ALLOW"},{"guest":"w_8tvgsuslzhlj","status":"ALLOW"},{"guest":"w_b9wgtip6lupn","status":"ALLOW"},{"guest":"w_kuzx91meenql","status":"ALLOW"},{"guest":"w_lvbrlko1yuhy","status":"ALLOW"},{"guest":"w_ozugph1gzauc","status":"ALLOW"},{"guest":"w_iwktyagv1ohj","status":"ALLOW"},{"guest":"w_yffskvachfcz","status":"ALLOW"},{"guest":"w_r2shc9ju6gxp","status":"ALLOW"},{"guest":"w_qpzrsfa33duj","status":"ALLOW"},{"guest":"w_wvhxojquowqw","status":"ALLOW"},{"guest":"w_egkgkp7enzub","status":"ALLOW"},{"guest":"w_uncsxijhszpw","status":"ALLOW"},{"guest":"w_fg1jqrcnrnto","status":"ALLOW"},{"guest":"w_f8jvtbrerghz","status":"ALLOW"},{"guest":"w_o0seeto9gxkz","status":"ALLOW"},{"guest":"w_c6hjzdnbll0o","status":"ALLOW"},{"guest":"w_tntccif2toy9","status":"ALLOW"},{"guest":"w_ckugyq0ogkbi","status":"ALLOW"},{"guest":"w_hfwowmuuw8rt","status":"ALLOW"}],"approvedBy":"w_ee9sez12a2m1"}}}
```

**Comment by gustavotrott** [comment]
Hey @donbowman, thanks for reporting that!

I was able to reproduce.
A simpler way to reproduce: 
   - Join as guest
   - Wait 30 seconds
   - Moderator approve
   - Guest will stay stuck in the waiting page

The problem is related with the bbb-web config `waitingGuestUsersTimeout=30000`.
If some user doesn't query his position within an interval of 30 seconds, he is removed from the guests list.

The problem happens because the endpoint to inform the guest position was changed. And the new endpoint doesn't update the user's "last position request".
I'll refactor it to use the graphql-connection as a presence indicator.

As a workaround you can increase the default `waitingGuestUsersTimeout`:
Include the line `waitingGuestUsersTimeout=3600000` in `/etc/bigbluebutton/bbb-web.properties`.

**Comment by donbowman** [comment]
thank you very much, i will give this a try.
I'm not 100% sure its precisely the same, i did have people i allowed to stay in the waiting queue more than 30s, it seems to be more a limit on the number. I can safely let 10 people wait, and usually 15, but not more. But perhaps it interacts with this in a time-specific fashion.

**Comment by donbowman** [comment]
i tried your workaround, it worked for me. thanks so much, looking forward to testing the fix as well.
