### ISSUE TITLE
unable to launch conference and showing error in canvas

### ISSUE THREAD

**Issue by patriciainti** [bigbluebutton/bigbluebutton#20054]
<img width="923" alt="image" src="https://github.com/bigbluebutton/bigbluebutton/assets/167723613/12dbf14f-5dc4-4017-8655-6796f1329abe">
 conference got server issue as after create the conference and when click start, it show error message.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Actual behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, Mac]
 - Browser [e.g. Chrome, Safari]

**Smartphone (please complete the following information):**
 - Browser [e.g. stock browser, Safari]

**Additional context**

**Comment by ffdixon** [comment]
Fixed the underlying issue with provisioning of the servers -- it should work now.

**Comment by patriciainti** [comment]
Dear dixon,

Tested and it worked. Thanks.
