### ISSUE TITLE
Raising Hand Malfunction - BBB 3.0 Alpha.5

### ISSUE THREAD

**Issue by FluffyUnicorn161** [bigbluebutton/bigbluebutton#20087]
**Describe the bug**
The notification for raising hands as "PopUp" & "Sound" is no longer displayed for the moderator when a participant answers. Even if the notification has been activated.

**To Reproduce**
1. Login with two Accounts (1x Moderator & 1x Participant)
2. Use the Hand-Raise-Option as Participant
3. Observe whether the moderator receives a pop-up notification for the message

**Expected behavior**
The moderator should receive a pop-up message and a sound when a hand raising is received from a participant.

**Actual behavior**
Neither a pop-up message nor a sound appears. Only the symbol in the participant list changes.

**BBB version:**
3.0.0 Alpha.5

**Desktop (please complete the following information):**
 - OS: Windows, MacOS, IOS
 - Browser Chrome, Safari

**Comment by ramonlsouza** [comment]
Hello @FluffyUnicorn161, thanks for the report! 
There is a fix for this issue (#19884), but it was merged after 3.0.0-alpha.5 release.
It will be part of the next 3.0 release

**Comment by ramonlsouza** [comment]
fixed in [v3.0.0-alpha.6](https://github.com/bigbluebutton/bigbluebutton/releases/tag/v3.0.0-alpha.6)
