### ISSUE TITLE
API - InsertDocument response is inconsistent

### ISSUE THREAD

**Issue by DigitalTimK** [bigbluebutton/bigbluebutton#20109]
**Describe the bug**
The response to insert documents is inconsistent in regards to the general concept: In case a `message`-value is sent, a second `messageKey`-value is expected. 

This concept (`message` and `messageKey` always together) is described for the `error`-case [here](https://docs.bigbluebutton.org/development/api/#error-handling), but should be applied for all responses with a `message`.

**To Reproduce**
https://yourserver.com/bigbluebutton/api/insertDocument?%5Bparameters%5D&checksum=%5Bchecksum

**Expected behavior**
```xml
<response>
    <returncode>SUCCESS</returncode>
    <message>Presentation is being uploaded</message>
</response>
```

**Actual behavior**
```xml
<response>
    <returncode>SUCCESS</returncode>
    <messageKey>documentInsertedOrSimilar</messageKey>
    <message>Presentation is being uploaded</message>
</response>
```

**Screenshots**
n/a

**Desktop (please complete the following information):**
n/a

**Smartphone (please complete the following information):**
n/a

**Additional context**
BBB-Server ~~2.4.7~~ (typo) 2.7.4

**Comment by antobinary** [comment]
Thanks for reporting!
Likely the version above is 2.7.4.
