### ISSUE TITLE
Pekko

### ISSUE THREAD

**Issue by ShalokShalom** [bigbluebutton/bigbluebutton#20111]
Hi there :) 

Considering Akka switched to a non-free license, did you evaluate to adopt to Pekko?

It may be, that you already support that (accidently or on purpose) but I still see Akka all over the codebase.

https://pekko.apache.org/

**Comment by antobinary** [comment]
Hi @ShalokShalom 
Please look through the 3.0 docs (docs.bigbluebutton.org just use the dropdown for 3.0)
We've gone the way you propose a year ago. https://docs.bigbluebutton.org/3.0/new-features/#replaced-akka-framework-with-pekko

We welcome your suggestions but let's filter out the ones we've already completed :stuck_out_tongue_winking_eye:

**Comment by ShalokShalom** [comment]
I wrote code base, not documentation.
