### ISSUE TITLE
Ubuntu 20.04

### ISSUE THREAD

**Issue by ShalokShalom** [bigbluebutton/bigbluebutton#20112]
I know that 20.04 is still supported till 2025. 

Considering that 24.04 is put, I assume 20.04 is not the prefered and recommended version anymore?

https://docs.bigbluebutton.org/administration/install/

**Comment by antobinary** [comment]
BigBlueButton 3.0 (in late alpha stage right now) runs on Ubuntu 22.04. We will consider 24.04 for 3.1 or later, depending on benefits analysis. 22.04 should cover us for the next 3 years.
Switching to the 3.0 version in the docs:

![Screenshot from 2024-04-30 09-35-30](https://github.com/bigbluebutton/bigbluebutton/assets/6312397/2129c557-4080-41ca-95da-17a6ebc9c4b3)
