### ISSUE TITLE
Configuring BigBlueButton with a SIP Trunk provider

### ISSUE THREAD

**Issue by bigbluebutton-issue-import** [bigbluebutton/bigbluebutton#2012]
Originally reported on Google Code with ID 1258

```
We are using BBB from last few month we need to change some feature of this. Also few
information are not available on net like 

How to test and configure Tele conferencing ?

We are searching this from last one month but not getting success. We need that our
BBB server voice communication/session get connect with telephone calls.

If anybody have any information on this please let us know. We are very thankful for
this.

waiting for some response on this.

Thanks,

Regards,
Kapil

```

Reported by `fullestop.flex` on 2012-07-03 10:06:45

**Comment by ffdixon** [comment]
Now covered here in the docs: http://docs.bigbluebutton.org/install/install.html#add-a-phone-number-to-the-conference-bridge.

**Comment by bwildenhain** [comment]
Just for the case someone is searching this feature: The description has been moved to https://docs.bigbluebutton.org/admin/customize#add-a-phone-number-to-the-conference-bridge
