### ISSUE TITLE
Auto laylout lock

### ISSUE THREAD

**Issue by bigbluebutton-issue-import** [bigbluebutton/bigbluebutton#2016]
Originally reported on Google Code with ID 1262
```
It would be nice to add a parameter in the layout module configuration for enabling
the layout lock at the start of bbb.
```

Reported by `stephane.lux1` on 2012-07-06 17:50:23

**Comment by ffdixon** [comment]
Closing this issue as the moderator can now use the lock settings to lock all viewer's layouts -- even for users who join after the lock setting has taken effect.
