### ISSUE TITLE
Port 80 vs Port 443 in different BBB versions

### ISSUE THREAD

**Issue by cod3r0k** [bigbluebutton/bigbluebutton#20183]
Why did BBB in the newer version switch to using a proxy for SSL? In previous versions (below 2.2), they used port 443 directly in Nginx. But in the newer ones, they use port 80 in nginx and then proxy it through HAProxy.

```
/etc/nginx/sites-available/bigbluebutton (nginx)
                       server_name: testBBB.mytest.de
                       port: 80, [::]:80127.0.0.1:82 http2 proxy_protocol, [::1]:82 http2127.0.0.1:81 proxy_protocol, [::1]:81
```

While in the previous version, we listen on 443 directly in `/etc/nginx/sites-available/bigbluebutton` (nginx).

**Comment by hostbbb** [comment]
HAProxy was added to support the embedded coturn server.    haproxy inspects the incoming requests on 443 and routes turn packets, with the rest going to nginx http

this is now the default bbb-install
