### ISSUE TITLE
Improve on-screen verbiage when guests join session without moderator 

### ISSUE THREAD

**Issue by jamesbellbn** [bigbluebutton/bigbluebutton#20204]
When a session that requires moderator approval for guests to join ("guestPolicy": "ASK_MODERATOR") begins without a moderator, then guests see an on-screen message that shows:

"Guest missing session"

This needs to be improved so that users better understand what it really means.

**Comment by antobinary** [comment]
Candidate for new message: "Waiting for moderator to join"

**Comment by Scroody** [comment]
Looks like the component was re-worked recently (four weeks before this comment) and this issue is already fixed!

![image](https://github.com/bigbluebutton/bigbluebutton/assets/36093456/fb34962f-e1e2-4dec-afbd-09184fe7a815)
