### ISSUE TITLE
upgrade from v3.0.0-alpha.5 to v3.0.0-alpha.6 fails (Waiting for Hasura's port (8085) to be ready...)

### ISSUE THREAD

**Issue by himpierre** [bigbluebutton/bigbluebutton#20240]
**Describe the bug**
Upgrade from v3.0.0-alpha.5 to v3.0.0-alpha.6 never finishes because installer waits for Hasura's port (8085) to be ready. But it never gets. I see Hasura is listening on port 8080. But 8085? Nada.

**Installation type**
sudo wget -qO- https://raw.githubusercontent.com/bigbluebutton/bbb-install/v3.0.x-release/bbb-install.sh | sudo bash -s -- -w -v jammy-300 -s blue.domain.de -e user@domain.de

**Firewall and IP address type**
Plain dedicated server.

**Console output**
Waiting for Hasura's port (8085) to be ready...
Waiting for Hasura's port (8085) to be ready...
Waiting for Hasura's port (8085) to be ready...

Had to ctrl+c at some point.

cheers! t.

**Comment by antobinary** [comment]
Thanks for reporting!

**Comment by gustavotrott** [comment]
As a workaround you can restart the service in a different tab `sudo systemctl restart bbb-graphql-server`.

Once it restarts Hasura will then listen on port 8085.

**Comment by himpierre** [comment]
Thanks! That solved the Hasure issue. But now nginx bails out with
`
nginx: [emerg] "proxy_cache" zone "revproxy" is unknown in /etc/nginx/nginx.conf:63
`

During the install I see:
`
+ systemctl start nginx.service
Job for nginx.service failed because the control process exited with error code.
See "systemctl status nginx.service" and "journalctl -xeu nginx.service" for details.
dpkg: error processing package bbb-webrtc-sfu (--configure):
 installed bbb-webrtc-sfu package post-installation script subprocess returned error exit status 1
No apport report written because MaxReports is reached already
dpkg: dependency problems prevent configuration of bbb-config:
 bbb-config depends on bbb-html5; however:
  Package bbb-html5 is not configured yet.
 bbb-config depends on bbb-playback; however:
  Package bbb-playback is not configured yet.
`

Reverting to a prior made snapshot gets me back up and running with alpha.5.

cheers! t.

**Comment by gustavotrott** [comment]
Can you confirm if your `/etc/nginx/nginx.conf` file contains this line:
`include /etc/nginx/conf.d/*.conf;`
?

It should run before `include /etc/nginx/sites-enabled/*;` to make sure the `revproxy` was set.

**Comment by himpierre** [comment]
Yes it is but the missing zone is defined in bbb-html5-meteor-assets-cache.conf.dpkg-new.
```
root@blue:/etc/nginx/conf.d# ls -la
total 24
drwxr-xr-x 2 root root 4096 May 13 20:37 .
drwxr-xr-x 9 root root 4096 May 13 20:36 ..
-rw-r--r-- 1 root root  131 May  8 13:17 bbb-graphql-client-settings-cache.conf
-rw-r--r-- 1 root root   37 Jan 30 21:40 bbb-html5-conn-limit.conf
-rw-r--r-- 1 root root   37 May 10 14:36 bbb-html5-conn-limit.conf.dpkg-new
-rw-r--r-- 1 root root  116 May 10 14:36 bbb-html5-meteor-assets-cache.conf.dpkg-new
root@blue:/etc/nginx/conf.d#
```
After moving bbb-html5-meteor-assets-cache.conf.dpkg-new to bbb-html5-meteor-assets-cache.conf nginx starts fine and as a result alpha.6 too. :)

cheers! t.

**Comment by himpierre** [comment]
Uhm. Should I move bbb-html5-conn-limit.conf.dpkg-new to bbb-html5-conn-limit.conf too? I guess so, right?

**Comment by gustavotrott** [comment]
> Uhm. Should I move bbb-html5-conn-limit.conf.dpkg-new to bbb-html5-conn-limit.conf too? I guess so, right?

I don't think so! This file is not necessary anymore for BBB 3.0. @antobinary can confirm it.

And we will need to understand why some files have this extension `.dpkg-new`. That is unexpected, maybe because the installation failed.

Thanks for sharing these details!

**Comment by antobinary** [comment]
We are keeping `bbb-html5-conn-limit.conf` for now. We can safely remove it once we are done with Meteor.

If you are still finding `.dpkg-new` files around, consider flushing and re-installing via `bbb-intstall.sh`
Entering into the beta+ stages there should be no significant issues like this.

**Comment by himpierre** [comment]
No problem. Thanks for your help. Both of you.

Am 14. Mai 2024 15:37:54 MESZ schrieb Anton Georgiev ***@***.***>:
>We are keeping `bbb-html5-conn-limit.conf` for now. We can safely remove it once we are done with Meteor.
>
>If you are still finding `.dpkg-new` files around, consider flushing and re-installing via `bbb-intstall.sh`
>Entering into the beta+ stages there should be no significant issues like this.
>

**Comment by jorgelondo** [comment]
I have the same problem when upgrading to version 3, from an instance in Azure with Ubuntu 20.04, I upgraded it to Ubuntu Jammy (22.04) on which I had version 2.7.15
> cheers! t.
