### ISSUE TITLE
The client crashes when trying to modify the rosters of running breakout rooms

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#20263]
**Describe the bug**
We had a meeting where breakouts were running (I was moderator, presenter). When I went on to try to modify the breakout rosters/pools, my client crashed.

**To Reproduce**

Not currently able to reproduce it. However, I have a screenshot from when it happened.

1. Join a meeting
2. Create breakouts
3. Open the breakouts panel. Select 'Manage users'

**Expected behavior**
The modal for managing breakouts should open

**Actual behavior**
In my case the client crashed (see below for the error)

**Screenshots**
![Screenshot from 2024-05-15 06-55-09](https://github.com/bigbluebutton/bigbluebutton/assets/6312397/ec7cd316-b557-42f3-911c-a32ad673bca5)

**BBB version:**
BigBlueButton 3.0.0-alpha.6

**Comment by ramonlsouza** [comment]
@antobinary I tried to reproduce it, but the crash did not happen... please include more information about how to reproduce
