### ISSUE TITLE
Exported (notes/wb) from breakout difficult to view 

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#20268]
**Describe the bug**
We now seem to add the exported presentation as a shape rather than opening it. It looks quite different than a normal presentation, can't do fit-to-width, need to manually zoom in to be able to read.

**To Reproduce**
1. Create breakouts with the option to export shared notes.
2. End the breakouts, wait for the export to finish
3. From the + button set the exported pdf to be the active presentation

**Expected behavior**
Easier to set in fit-to-width / or at least no massive margin appearing.

**Actual behavior**
Looks like a shape on a canvas, not like a new pdf opened.

**Screenshots**
![Screenshot from 2024-05-15 07-56-32](https://github.com/bigbluebutton/bigbluebutton/assets/6312397/dd3f07e5-58a8-458c-951b-994c21aa122e)

**BBB version:**
BigBlueButton 3.0.0-alpha.6

**Comment by ramonlsouza** [comment]
no longer reproducible in v3.0.0-alpha.7
