### ISSUE TITLE
[3.0] slide change by arrow keys breaks the presentation

### ISSUE THREAD

**Issue by hiroshisuga** [bigbluebutton/bigbluebutton#20278]
**Describe the bug**
1. slide change by keyboard arrow keys is not possible unless the presenter clicks the presentation toolbar
2. slide change by left arrow key on the 1st slide brings the presentation into another world. 

**To Reproduce**
1. click the slide so that the pointer focus is on the slide
2. you cannot move the slide by the arrow keys.
3. click the presentation toolbar
4. you can move the slide by the arrow keys
5. if you press the left arrow key on the first slide, the presentation gets broken.

**Expected behavior**
The user should be able to change the slide by arrow keys without clicking the toolbar.
The user should stay on the first slide when pressing the left arrow key on the first slide. 

**Screenshots**

https://github.com/bigbluebutton/bigbluebutton/assets/45039819/35c09b8f-7fb3-42c7-b43d-44caf060cd99

**BBB version:**
test30.bigbluebutton.org

**Additional context**
The fix in #19692 seems to be dysfunctional in the latest version.

**Comment by antobinary** [comment]
I can confirm this on build 363, specifically trying to navigate left of the first slide.

![Screenshot from 2024-05-16 10-22-17](https://github.com/bigbluebutton/bigbluebutton/assets/6312397/6a77f7d2-7cb0-4b49-9db4-b3e280f19e49)


Thanks for spotting and reporting this @hiroshisuga !
