### ISSUE TITLE
Allow per-user logoutURL

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#20285]
**Is your feature request related to a problem? Please describe.**
Front-end applications may have users enter through different paths in the application, and when the user log's out want to return them to their previous login screen.

Currently, the `logoutURL` is shared by all users and doesn't provide any way to redirect different users to different areas.

**Describe the solution you'd like**
In the [join](https://docs.bigbluebutton.org/3.0/development/api/#join) API parameters, add support for a `logoutURL` to enable the front-end to send each user their own logout URL.

**Describe alternatives you've considered**
We could add parameters to the `logoutURL` on create, such as `%%USERID%%` or `%%ROLE%%`, but giving each user their own `logoutURL` is simpler and gives all the control to the front-end.

**Comment by ffdixon** [comment]
This will also cover the case where the front-end wants the users to logout to completely different URLs as well.

**Comment by jaapjansma** [comment]
I am also looking for this feature. And I have a pull request coming up which introduces this feature.

**Comment by jaapjansma** [comment]
I have submitted a PR: https://github.com/bigbluebutton/bigbluebutton/pull/21204

And one for the documentation: https://github.com/bigbluebutton/bigbluebutton/pull/21205
