### ISSUE TITLE
Update the BigBlueButton packaging to Ubuntu 14.04 

### ISSUE THREAD

**Issue by bigbluebutton-issue-import** [bigbluebutton/bigbluebutton#2029]
Originally reported on Google Code with ID 1275

```
The BigBlueButton packaging and BigBlueButton VM both run on Ubuntu 10.04 LTS, which
has served us well.

Now that Ubuntu 12.04 LTS is available, investigate running BigBlueButton on the latest
LTS.  

In terms of timing, we won't do this for 0.81 (currently in development), but we'll
revisit moving BigBlueButton to Ubuntu 12.04 in a subsequent release.
```

Reported by `ffdixon` on 2012-07-24 10:52:52

**Comment by ccencho** [comment]
Hello everyone I'm installing ubuntu 14.04 LTS bigbluebutton and I get the following error, agradecere your help:

Gem files will remain installed in /var/lib/gems/1.9.1/gems/nokogiri-1.4.4 for inspection.
Results logged to /var/lib/gems/1.9.1/gems/nokogiri-1.4.4/ext/nokogiri/gem_make.out
Your Gemfile.lock is corrupt. The following gems are missing from the DEPENDENCIES section: 'archive-tar-minitar' 'hoe'
'rcov'
dpkg: error processing package bbb-record-core (--configure):
 subprocess installed post-installation script returned error exit status 20
dpkg: dependency problems prevent configuration of bbb-playback-presentation:
 bbb-playback-presentation depends on bbb-record-core; however:
  Package bbb-record-core is not configured yet.

dpkg: error processing package bbb-playback-presentation (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of bbb-config:
 bbb-config depends on bbb-web; however:
  Package bbb-web is not configured yet.
 bbb-config depends on bbb-playback-presentation; however:
  Package bbb-playback-presentation is not configured yet.

dpkg: error processing package bbb-config (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of bigbluebutton:
 bigbluebutton depends on bbb-config; however:
  Package bbb-config is not configured yet.

dpkg: error processing package bigbluebutton (--configure):
 dependency problems - leaving unconfigured
Processing triggers for libc-bin (2.19-0ubuntu6.7) ...
Errors were encountered while processing:
 bbb-web
 bbb-record-core
 bbb-playback-presentation
 bbb-config
 bigbluebutton
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by ffdixon** [comment]
Can you post this to our bigbluebutton-setup mailing list at
   
   https://groups.google.com/forum/#!forum/bigbluebutton-setup

and we'll help you there.  If it turns out there is a bug (or enhancement needed) to BigBlueButton itself, we'll open an issue here to track it.

**Comment by ccencho** [comment]
Hii ffdixon:

ready and I hope I approve register to post my question and I can help.
Thank you

**Comment by sjuxax** [comment]
@ccencho Downgrade bundler to 1.10 to get around this. Fix your Gemfile.lock and then upgrade back to the latest release of bundler.
