### ISSUE TITLE
BBB 2.6/2.7: Update MongoDB to 6.0

### ISSUE THREAD

**Issue by danimo** [bigbluebutton/bigbluebutton#20338]
Currently BBB depends on MongoDB 4.4 in 2.7.x. This version is EoL and as of now, the Repository key has expired, which causes failures to installations and updates.

```
… 
Err:11 http://repo.mongodb.org/apt/ubuntu focal/mongodb-org/4.4 Release.gpg
  The following signatures were invalid: EXPKEYSIG 656408E390CFB1F5 MongoDB 4.4 Release Signing Key <packaging@mongodb.com>
… 
```

BBB 3.0 uses MongoDB 6.0, and this change will be backported to 2.7 and 2.6 to rectify the issue.

This is a tracking bug. Feel free to post your workarounds here as well.

**Comment by danimo** [comment]
MongoDB have updated their keys.

```
curl -L https://pgp.mongodb.com/server-4.4.asc | sudo apt-key add -
```

works again.

**Comment by antobinary** [comment]
Thank you @danimo !
If needed in the future we could backport the upgrade of MongoDB 4.4 -> 6.0 which was done on BBB v3.0.x-release branch (most of the work was in bbb-install.sh). I am reluctant to do it unless really needed as there are significant changes in terms of accessing the db from within the server (and others). I am aware of at least some community members which would have to adapt their work (internal mongo db queries, scripts). Also we've never had 6.0 on production, so other side effects are also possible.

I will close this issue for now.

For the record, these are the changes I recall. My plan was to apply [most of] them on the 2.7 branch and test.
https://github.com/bigbluebutton/bbb-install/pull/664/files#diff-b02a2e8accf3dc268b4cc8c4a6ce2b6b51cbaee1a254fb674c6429fbfdf5ef81R303-R310
https://github.com/bigbluebutton/bigbluebutton/pull/17763/files
