### ISSUE TITLE
No subscrition on server error (client freeze / stop updating data)

### ISSUE THREAD

**Issue by antonbsa** [bigbluebutton/bigbluebutton#20349]
**Describe the bug**
Not sure if this is the only way to reproduce. I've been trying to get the steps of this bug for a while, as we're hitting it consistently in our daily calls, with no success. This seems like the easiest way to do it. I've also got the same freeze state without performing any action (likely someone else did something), but I could not reproduce it to add it here.

**To Reproduce**
1. Join in a meeting with 2 users;
2. Join user1 with the microphone and select one automatic transcription language;
3. Join user2 with audio;
4. Once user1 speak, user2 presses the CC button;
5. user2 won't be able to change the audio settings, disconnect it, mute/unmute, share the webcam, receive new messages, etc;

```
Error: Error: on subscription to server: {}
```

**Screenshot**
![image](https://github.com/bigbluebutton/bigbluebutton/assets/56703993/623fe296-3282-418e-acb9-22ff6284c5bc)

**Comment by lfzawacki** [comment]
I'm seeing the same problem when trying to pin the shared notes to the whiteboard. Audio/video connections are kept, but most parts of the interface stop responding.

Also seeing `Error: Error: on subscription to server: {}` printed on the console

**Comment by Tainan404** [comment]
I haven't been able to reproduce this issue, is there any new detail that might help?
