### ISSUE TITLE
Error in French translation

### ISSUE THREAD

**Issue by Lutice** [bigbluebutton/bigbluebutton#20383]
BBB version 2.7.4, 2.7.6

The following two files contain a string not well written in French :
/usr/share/meteor/bundle/programs/web.browser/app/locales/fr.json
/usr/share/meteor/bundle/programs/web.browser.legacy/app/locales/fr.json

"app.presentationUploder.browseFilesLabel": "ou parcour**r**ez vos fichiers",
normally is 
"app.presentationUploder.browseFilesLabel": "ou parcourez vos fichiers",
with only one R in parcourez

another problem in same file is :
 "app.presentationUploader.exportCurrentStatePresentation": "Envoyer un lien de téléchargement pour la présentation qui inclut les annotation du tableau blanc",

 "app.presentationUploader.exportCurrentStatePresentation": "Envoyer un lien de téléchargement pour la présentation qui inclut les annotation**s** du tableau blanc",

I don't know how to modify translation in transifex :'(

Regards 
Fabrice

**Comment by antobinary** [comment]
Merci, @Lutice ! https://github.com/bigbluebutton/bigbluebutton/pull/20385
BBB 2.7.9 contiendra les modifications.

**Comment by antobinary** [comment]
P.S. I see you joined Transifex. I bumped you up to a Reviewer. This should allow you to edit existing translations.

Thank you for helping out with the translations!!
