### ISSUE TITLE
Relax Content-Type validation for API Requests to be tolerant to additional values

### ISSUE THREAD

**Issue by GhaziTriki** [bigbluebutton/bigbluebutton#20384]
**Describe the bug**
In https://github.com/bigbluebutton/bigbluebutton/releases/tag/v2.7.8 and https://github.com/bigbluebutton/bigbluebutton/releases/tag/v2.6.18 the `Content-Type` validation for API requests in BigBlueButton is strictly limited to a predefined set of media types with no tolerance to additional values. This strict validation can cause issues for integrations that include these additional values such as `application/xml; charset=UTF-8` or `application/xml; charset=UTF-8; q=0.9`

**To Reproduce**
Steps to reproduce the behaviour:
1. Using https://github.com/bigbluebutton/bigbluebutton/releases/tag/v2.7.8 or https://github.com/bigbluebutton/bigbluebutton/releases/tag/v2.6.18 server create a meeting using HTTP `POST` and `application/xml; charset=UTF-8` as `Content-Type` HTTP header.

**Expected behaviour**
Meeting should be created.

**Actual behaviour**
`unsupportedContentType` is returned by the API.

**Comment by kepstin** [comment]
Note that Scalelite is not affected; in Scalelite, the Rails library fully parses the provided mime type including any parameters prior to doing the mime type matching.
