### ISSUE TITLE
Sticky notes always lose focus and users can't write on them

### ISSUE THREAD

**Issue by lfzawacki** [bigbluebutton/bigbluebutton#20443]
Trying to use sticky note on whiteboard is not possible because they will immediately lose focus after being created. If we use the cursor to select a note we can try typing but most characters will take the focus away from the note (typing numbers works!)

**Comment by ramonlsouza** [comment]
not reproducible in v3.0.0-beta.1

https://github.com/user-attachments/assets/4a483469-e32d-45a8-9c5a-16144d43f7f1
