### ISSUE TITLE
Missing Courser while using Safari on Mac (BBB 3.0 - Alpha 5)

### ISSUE THREAD

**Issue by FluffyUnicorn161** [bigbluebutton/bigbluebutton#20448]
**Describe the bug**
When using the Safari browser on a Macbook in Presenter mode, the mouse cursor disappears as soon as it moves over the presentation area. This can be an obstacle when creating drawings during the presentation.

**To Reproduce**
Open Safari on MacOS
Start BBB-Session
Move cursor over presentation

**Expected behavior**
courser should been displayed

**Actual behavior**
courser not available

**BBB version:**
BigBlueButton continually evolves. Providing the version/build helps us to pinpoint when an issue was introduced.
Example:
BBB. 3.0 Alpha 5

**Desktop (please complete the following information):**
 -OS: Mac
- Browser: Safari

**Comment by antobinary** [comment]
Merging into #20613
