### ISSUE TITLE
Support a "Push to Talk" button - unmute while button is held down

### ISSUE THREAD

**Issue by bigbluebutton-issue-import** [bigbluebutton/bigbluebutton#2045]
Originally reported on Google Code with ID 1292

```
Suggested by Bobby fro Yavapai College on the Community update
```

Reported by `calvin.walton@kepstin.ca` on 2012-08-15 20:32:53

**Comment by robbi5** [comment]
Can this issue be reassigned to the HTML5 client or should I open a new one? 
PTT functionality in the current client would be awesome to have :)

**Comment by mtsonline** [comment]
would be a nice feature

**Comment by mefromthepast** [comment]
Can only second this. PTT is the main feature that makes me favour mumble over BBB at the moment.

**Comment by GitHorst** [comment]
This could be the default "mute" behavior without changing the user experience for most of the users who do not know or care about the new feature. Obvious choice for the button would be space :)

**Comment by martinvonwittich** [comment]
This should probably be relabeled to HTML5 Client.

**Comment by besserwisser** [comment]
Are there news after 5 years?

**Comment by matiasilva** [comment]
Yes, take a look at the comments right above yours. There's even an open pull request for this.

**Comment by astrojuanlu** [comment]
Naughty, naughty bot. This feature is still desired, there was a recent duplicate of this issue.

**Comment by GitHorst** [comment]
_Activity_

**Comment by buforo** [comment]
We need this function too, we have a all time conference running, and it often happens, that we have audio feedbacks, because someone forgets to mute. I would try to add the feature myself, if I had enough html5 knowledge - or is it impossible, because of technical limits of html5?

**Comment by astrojuanlu** [comment]
🃏

**Comment by buforo** [comment]
We need this feature, as people often forget to switch off the microphone. If people have to press a button or key actively, when they talk, this problem would not exist. (Best would be a hint "you are talking/making noise - do you want that the others hear you then press "...")

I am aware, that this does not make sense for some use cases, so we would need activation and deactivation like we have it now too. Push to talk would be  a good feature for inexperienced users. I am not good enough, in changing the user interface, else I would try to implement it myself. Is there any simple description, how the user interface works, then I'd at least try to make a prototype ?

**Comment by keunes** [comment]
Even though old, still desired.

**Comment by klorydryk** [comment]
This feature is still needed. Thanks!

**Comment by ffdixon** [comment]
Yes, we want to get it in place as well.  We're looking to see what we can provide during the development of 3.0 that gets us closer.

**Comment by nekohayo** [comment]
Follow-up suggestion: enabling the feature by default for all users (#24208)
