### ISSUE TITLE
Connection status inconsistencies

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#20486]
**Describe the bug**
Tested BBB 3.0 alpha.~7 and noticed various odd states of the dialog.

- sometimes there was no timestamp
- offline users with green!! or red status
- sometimes there was Client not responding text, sometimes not. Again green or red did not matter

**Screenshots**
![Screenshot from 2024-06-11 15-36-06](https://github.com/bigbluebutton/bigbluebutton/assets/6312397/b2a69f46-abed-47d1-bdb5-ce55132efe45)
![Screenshot from 2024-06-11 15-35-33](https://github.com/bigbluebutton/bigbluebutton/assets/6312397/33f16e85-72ec-4cad-b099-6f27d41daa93)

**BBB version:**
BigBlueButton 3.0.0-alpha.~7

**Comment by Tainan404** [comment]
Solved on:  #20630 #20196 #20519
