### ISSUE TITLE
userdata-bbb_display_branding_area parameter not working

### ISSUE THREAD

**Issue by gabriellpr** [bigbluebutton/bigbluebutton#20526]
**Describe the bug**
The branding parameter is not working when setting these two parameters, userdata-bbb_display_branding_area and the logo.

![Screenshot from 2024-06-18 14-11-19](https://github.com/bigbluebutton/bigbluebutton/assets/19312495/d5338789-dd5e-4a0a-be6d-472782c4281c)

**2.7**

![Screenshot from 2024-06-18 14-11-55](https://github.com/bigbluebutton/bigbluebutton/assets/19312495/d85fee99-e57f-46d5-8cc5-346994cce9c3)

**3.0**
![Screenshot from 2024-06-18 14-12-18](https://github.com/bigbluebutton/bigbluebutton/assets/19312495/1c5745f5-73f2-4a51-a215-f2fa00db06fe)

**Comment by antonbsa** [comment]
there's already an automated test for this, we could enable it on CI after the fix!
