### ISSUE TITLE
React limits the number of nested updates to prevent infinite loops...

### ISSUE THREAD

**Issue by fadgan** [bigbluebutton/bigbluebutton#20533]
Good afternoon,

Installed BBB 3.0 on Ubuntu 22.04. All runs fine.
Followed the docs for setting up the hmtl5 client alongside an already installed BBB.
Pulled the corresponding branch:
```

git status
On branch v3.0.x-release
Your branch is up to date with 'origin/v3.0.x-release'.
```

Stopped the packages version of hmtl5 as per the doc and started the pulled one with  npm install and npm start.

Using API mate to test. Meeting creation is SUCCESS from but when joining as a moderator or an attendee getting this error in the browser:
```

Oops, something went wrong
Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.
```

`
{"componentStack":"\n    at PresenceManagerContainer (https://mydomain.com/html5client/app/app.js?hash=e141f764a08a61d394ecb639c21542af816a72d2:72129:5)\n    at ApolloProvider (https://mydomain.com/html5client/packages/modules.js?hash=50d804e61daf7030adb28c433c4e4f7abdaf270f:123184:21)\n    at ConnectionManager (https://mydomain.com/html5client/app/app.js?hash=e141f764a08a61d394ecb639c21542af816a72d2:68993:5)\n    at ErrorBoundary (https://mydomain.com/html5client/app/app.js?hash=e141f764a08a61d394ecb639c21542af816a72d2:50588:5)\n    at LocatedErrorBoundary (https://mydomain.com/html5client/app/app.js?hash=e141f764a08a61d394ecb639c21542af816a72d2:50511:7)\n    at IntlProvider (https://mydomain.com/html5client/packages/modules.js?hash=50d804e61daf7030adb28c433c4e4f7abdaf270f:189432:47)\n    at IntlLoader (https://mydomain.com/html5client/app/app.js?hash=e141f764a08a61d394ecb639c21542af816a72d2:108771:5)\n    at IntlLoaderContainer (https://mydomain.com/html5client/app/app.js?hash=e141f764a08a61d394ecb639c21542af816a72d2:108842:5)\n    at LoadingScreenHOC (https://mydomain.com/html5client/app/app.js?hash=e141f764a08a61d394ecb639c21542af816a72d2:51096:5)\n    at ErrorBoundary (https://mydomain.com/html5client/app/app.js?hash=e141f764a08a61d394ecb639c21542af816a72d2:50588:5)\n    at StartupDataFetch (https://mydomain.com/html5client/app/app.js?hash=e141f764a08a61d394ecb639c21542af816a72d2:68816:5)\n    at Main"}`.

Tried Firefox, Chrome and Edge. 

Checked out this "`https://github.com/bigbluebutton/bigbluebutton/issues/14118`" but in my case the defaultWelcomeMessage and the defaultWelcomeMessageFooter are not empty.

The client log is clean.

Any tips and help is highly appreciated.

Thank you.

Regards,
Fadai.

**Comment by antobinary** [comment]
Hi @fadgan 

Could you please confirm which `-v` argument you passed on `bbb-install.sh`? Branch `v3.0.x-release` matches `-v jammy-30-dev` (not the usual `jammy-300`)

If you used `jammy-300`, just re-run your bbb-install command with `jammy-30-dev` instead, and do the steps:

> Stopped the packages version of hmtl5 as per the doc and started the pulled one with npm install and npm start.
> Using API mate to test.

**Comment by fadgan** [comment]
This was exactly the reason.

Thank you for the prompt support.

**Comment by fadgan** [comment]
Resolved now.
