### ISSUE TITLE
feat: Accept custom webcamBackgroundURL

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#20540]
**Is your feature request related to a problem? Please describe.**
In some cases we want to be able to pass a custom webcam background for specific users. For example for a certain institution/class set the viewers to join with <background1> and professors to join with <background2>.

**Describe the solution you'd like**
Accept a JOIN parameter `webcamBackgroundURL`="...". If the value passed contains a URI to a jpeg or png image. The image should not be too large, check https://github.com/bigbluebutton/bigbluebutton/blob/v2.7.x-release/docs/docs/administration/customize.md?plain=1#L705-L739 for steps to create sampe image.
We should likely check the size before using it (needs confirmation).

Note: the image link could be pointing to a local asset to avoid ip logging. Or could be to a static (cdn?) remote asset.

**Describe alternatives you've considered**

**Additional context**
Note that we have the existing JOIN parameter `avatarURL` which shares many similarities.

**Comment by kepstin** [comment]
It would be useful to confirm that URLs without protocol or host, like `/path/to/image.jpg`, will work to load images from the BigBlueButton server itself (or proxy host, if that feature is in use).

**Comment by ritzalam** [comment]
Think on handling the case where loading the URL fails. Maybe use a default (greenscreen?) background so we know that the url failed. This would help know right away when someone complains on why the background image isn't backgrounding.
