### ISSUE TITLE
Operation not permitted from apt using bbb-install to upgrade 2.7.4

### ISSUE THREAD

**Issue by JamesH1978** [bigbluebutton/bigbluebutton#20544]
when running bbb-install script to update, we are getting the following output from apt, this happens on any apt command as well as the script. Not sure if bug or other, BBB seems to work fine but stuck at 2.7.4

Thanks
James

BigBlueButton Server 2.7.4 (625)
                    Kernel version: 5.4.0-182-generic
                      Distribution: Ubuntu 20.04.6 LTS (64-bit)
                            Memory: 16379 MB
                         CPU cores: 8

`Setting up bbb-record-core (1:2.7-15) ...
chown: changing ownership of '/var/bigbluebutton/recording/status': Operation not permitted
dpkg: error processing package bbb-record-core (--configure):
 installed bbb-record-core package post-installation script subprocess returned error exit status 1
Setting up bbb-learning-dashboard (1:2.7-12) ...
chown: changing ownership of '/var/bigbluebutton/learning-dashboard/favicon.ico': Operation not permitted
chown: changing ownership of '/var/bigbluebutton/learning-dashboard/index.html': Operation not permitted
chown: changing ownership of '/var/bigbluebutton/learning-dashboard/static/media/bbb-icons.1b4ec364994645317829.woff': Operation not permitted
chown: changing ownership of '/var/bigbluebutton/learning-dashboard/static/media': Operation not permitted
chown: changing ownership of '/var/bigbluebutton/learning-dashboard/static/css/main.43651e12.css.map': Operation not permitted
chown: changing ownership of '/var/bigbluebutton/learning-dashboard/static/css/main.43651e12.css': Operation not permitted
chown: changing ownership of '/var/bigbluebutton/learning-dashboard/static/css': Operation not permitted
chown: changing ownership of '/var/bigbluebutton/learning-dashboard/static/js/main.c07298a2.js': Operation not permitted
chown: changing ownership of '/var/bigbluebutton/learning-dashboard/static/js/main.c07298a2.js.LICENSE.txt': Operation not permitted
chown: changing ownership of '/var/bigbluebutton/learning-dashboard/static/js/main.c07298a2.js.map': Operation not permitted
chown: changing ownership of '/var/bigbluebutton/learning-dashboard/static/js': Operation not permitted
chown: changing ownership of '/var/bigbluebutton/learning-dashboard/static': Operation not permitted
chown: changing ownership of '/var/bigbluebutton/learning-dashboard/asset-manifest.json': Operation not permitted
chown: changing ownership of '/var/bigbluebutton/learning-dashboard/': Operation not permitted
dpkg: error processing package bbb-learning-dashboard (--configure):
 installed bbb-learning-dashboard package post-installation script subprocess returned error exit status 1
Setting up bbb-config (1:2.7-32) ...
...chown: changing ownership of '/var/bigbluebutton/recording/publish/presentation': Operation not permitted
chown: changing ownership of '/var/bigbluebutton/recording/publish': Operation not permitted
chown: changing ownership of '/var/bigbluebutton/recording/status/processed': Operation not permitted
chown: changing ownership of '/var/bigbluebutton/recording/status/sanity': Operation not permitted
chown: changing ownership of '/var/bigbluebutton/recording/status/recorded': Operation not permitted
chown: changing ownership of '/var/bigbluebutton/recording/status/published': Operation not permitted
chown: changing ownership of '/var/bigbluebutton/recording/status/ended': Operation not permitted
chown: changing ownership of '/var/bigbluebutton/recording/status/archived': Operation not permitted
chown: changing ownership of '/var/bigbluebutton/recording/status': Operation not permitted
chown: changing ownership of '/var/bigbluebutton/recording/raw': Operation not permitted
chown: changing ownership of '/var/bigbluebutton/recording/process': Operation not permitted
chown: changing ownership of '/var/bigbluebutton/recording': Operation not permitted
dpkg: error processing package bbb-config (--configure):
 installed bbb-config package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 bbb-record-core
 bbb-learning-dashboard
 bbb-config
E: Sub-process /usr/bin/dpkg returned an error code (1)`

**Comment by antobinary** [comment]
Hi! Are you running as `root`?

Is this a routine you've done before or possibly first ever attempt at upgrading?

The `Operation not permitted chown` logs stand out -- that's why I am asking about user etc.

**Comment by JamesH1978** [comment]
yes as `sudo su` root, first installation with script worked fine with no issues, just ran the script again as before to upgrade as i do on all my other servers in a different setup and this. actually same for any apt command, wth

**Comment by antobinary** [comment]
>actually same for any apt command, wth

That sounds like a trace to follow. Nothing jumps to mind regarding BigBlueButton's install script causing this.
I wonder if `apt-get` is problematic too. Does `apt update` work or only the commands requiring write access fail?

**Comment by JamesH1978** [comment]
apt update works fine, its just upgrading those 3 packages that seem to causing the issue
![image](https://github.com/bigbluebutton/bigbluebutton/assets/87171443/ea5688f3-8a1f-41e2-bd83-ba541c106bd3)

**Comment by JamesH1978** [comment]
it installs other packages, as i ran an upgrade and it installed the mongodb tools, but still failed on the bbb things

**Comment by JamesH1978** [comment]
![image](https://github.com/bigbluebutton/bigbluebutton/assets/87171443/29cb0bbe-4975-41ce-a9ec-c8be506f917c)
ok thats strange, --check doesnt show any issues

**Comment by antobinary** [comment]
```
root@test27:~# ls -l /var/bigbluebutton/recording/
total 24
drwxr-xr-x  4 bigbluebutton bigbluebutton  4096 Aug 14  2023 process
drwxr-xr-x  4 bigbluebutton bigbluebutton  4096 Aug 14  2023 publish
drwxr-xr-x 31 bigbluebutton bigbluebutton 12288 Jun 19 15:01 raw
drwxr-xr-x  8 bigbluebutton bigbluebutton  4096 May 17  2023 status
```

do you have a user `bigbluebutton` at all? Both `bbb-config` and `bbb-learning-dashboard` set ownership of files to `bigbluebutton` user in their post install scripts.

**Comment by JamesH1978** [comment]
ok i feel stupid now and apologise for wasting everyones time with a clearly our end issue. we hold /var/bigbutton on an nfs share and on this new setup, i hard forgotten the no_root_squash and the user/group setup. We had the scalelite share working but not the BBB one, as we has installed and then moved it to the share. Closing this now

Thanks, everyones input made the mistake dawn on me.

James

**Comment by antobinary** [comment]
Thank you for posting the cause. Maybe it will help someone else in the future. Cheers!
