### ISSUE TITLE
[2.7] Layout VIDEO_FOCUS shows empty tiles for other participants with webcamsOnlyForModerator=true

### ISSUE THREAD

**Issue by stefanplk3** [bigbluebutton/bigbluebutton#20569]
**Describe the bug**
When choosing the 'Grid layout' (VIDEO_FOCUS) and setting "See other viewers webcams" to locked (or setting  webcamsOnlyForModerator=true in the create command of the API), other participants can see an empty tile (including the  name of the participant) for every other participant. This bug was not present in 2.6 (no empty tiles at all in the VIDEO_FOCUS view), which is the expected behavior if ""See other viewers webcams" is off. 

**To Reproduce**
1. Create a room
2. Click on three dots in the upper right corner
3. Click on "Choose Layout"
4. Select 'Grid layout'
5. Click on 'Update'
6. Click on 'Gear' Icon next to 'Users' in left bar.
7. Click on 'lock viewers'
8. Set 'See other Viewers webcams' to 'locked'
9. Set 'See other viewers in the Users list' to 'locked'
10. Open the room in two other browser incognito tabs and log in with usernames 'participant 1' and 'participant 2'
11. Set the video mode to 'Grid layout' in the participant tabs as welll (steps 2-5 above!)

**Expected behavior**
Participants cannot see other participants as "See other Viewers webcams" and "See other viewers in the Users list" is set to locked. The empty tiles should only be displayed to moderators, not other participants.

**Actual behavior**
Other participants (that do NOT have moderator status) can see empty tiles with names of all other participants.

**Screenshots**
![Bildschirmfoto vom 2024-06-24 08-17-50](https://github.com/bigbluebutton/bigbluebutton/assets/75616512/23caa194-d125-4061-800a-04f1bb9b0f19)
Screenshot from 'Participant 1'.  'Participant 2' doesn't appear in the users list on the left, but on the empty tile in the grid view in the presentation area, with full name in the tile.

![Bildschirmfoto vom 2024-06-24 08-38-35](https://github.com/bigbluebutton/bigbluebutton/assets/75616512/9666f020-6175-4b55-a192-203ca4ded982)

**BBB version:**
BigBlueButton Server 2.7.8 (638)

**Desktop (please complete the following information):**
 - OS: Windows, Linux (Ubuntu)
 - Browser Chrome
 - Version 126.0.6478.114

**Smartphone (please complete the following information):**
 - Device: iphone SE (chrome developer tools on desktop)
 - Browser Chrome (chrome developer tools on desktop)

**Additional context**
BBB 2.6 didn't have the empty tiles.

**Comment by opensourcecompany** [comment]
Additionally: if a participant has no webcam, is it really neccessary to show an icon at all?

**Comment by stefanplk3** [comment]
Update: This bug is NOT present in 3.0.0-alpha6

Bug IS present in 2.7.9.
