### ISSUE TITLE
Download document feature gives a bad link on the first attempt

### ISSUE THREAD

**Issue by pielonet** [bigbluebutton/bigbluebutton#20580]
**Describe the bug**
During a BBB session when the moderator modifies a document to allow downloading by other participants the notification shown to participants contains a bad link in the form : https://bbb.example.com/bigbluebutton/undefined

Only on the second attempt (that is unshare the document, set if for download once again) is the download link shown in the notification box correct.

BBB version : 2.7.4

**Comment by antobinary** [comment]
@pielonet are you able to share the filename and extension? We believe there might be some special character at play here.

Please retry on 2.7.5 -- we fixed something VERY similar https://github.com/bigbluebutton/bigbluebutton/pull/19734 https://github.com/bigbluebutton/bigbluebutton/issues/19180

**Comment by pielonet** [comment]
Hi,

The issue appears to have been fixed : we tested it successfully in 2.7.9.

Kind regards,
Thierry
