### ISSUE TITLE
Enhancing ,extending shared notes module (adding tools like font size ,bold ,italics ,import and export and others

### ISSUE THREAD

**Issue by bigbluebutton-issue-import** [bigbluebutton/bigbluebutton#2059]
Originally reported on Google Code with ID 1306

```
Enhancing ,extending shared notes module (adding tools like font size ,bold ,italics
,import and export, chat and others


see  screen shot or visit http://piratepad.net/

```

Reported by `amazigh2011@hotmail.com` on 2012-08-30 18:57:10

<hr>
- _Attachment: Bildschirmfoto-1.png<br>![Bildschirmfoto-1.png](https://storage.googleapis.com/google-code-attachments/bigbluebutton/issue-1306/comment-0/Bildschirmfoto-1.png)_
- _Attachment: Bildschirmfoto-2.png<br>![Bildschirmfoto-2.png](https://storage.googleapis.com/google-code-attachments/bigbluebutton/issue-1306/comment-0/Bildschirmfoto-2.png)_
- _Attachment: Bildschirmfoto-5.png<br>![Bildschirmfoto-5.png](https://storage.googleapis.com/google-code-attachments/bigbluebutton/issue-1306/comment-0/Bildschirmfoto-5.png)_
- _Attachment: Bildschirmfoto-6.png<br>![Bildschirmfoto-6.png](https://storage.googleapis.com/google-code-attachments/bigbluebutton/issue-1306/comment-0/Bildschirmfoto-6.png)_

**Comment by ffdixon** [comment]
Implemented in BigBlueButton 2.0-beta.  See http://docs.bigbluebutton.org/2.0/20overview.html#text-formatting.
