### ISSUE TITLE
Whiteboard (tldraw): Viewers often have their whiteboard zoomed in wrongly

### ISSUE THREAD

**Issue by gustavotrott** [bigbluebutton/bigbluebutton#20601]
When I'm drawing on a presentation that is different from Default.pdf, viewers often have their screens zoomed in and can't see what I'm drawing in other parts of the slide.

Version: BigBlueButton Server 3.0.0-alpha.7 (1112)

[Screencast from 2024-06-28 09-18-33.webm](https://github.com/bigbluebutton/bigbluebutton/assets/5660191/cbfb9fab-375a-446d-a20e-b9f4bdced1fa)

The file I used to test:
[mytest.pdf](https://github.com/user-attachments/files/16029503/mytest.pdf)

**Comment by antonbsa** [comment]
As far as I could test, it seems to be related to `portrait` presentations - easily reproducible with those, couldn't have the same with landscape
