### ISSUE TITLE
Wb: Zoom-in and immediately switch slide causes view discrepancy with presenter

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#20666]
**Describe the bug**
If the presenter switches the slide while zoom-in/out [mouse wheel] events are still being transmitted, it can lead to a big difference in what the presenter sees vs what the viewers see.

**To Reproduce**
1. Join a session with presenter
2. Join with a few viewers too
3. The presenter zooms in and switches slide

**Expected behavior**
Same view for both

**Actual behavior**
The presenter's view is more zoomed-in. Note that if I change the presenter, this fixes itself

**Screenshots**
![Screenshot from 2024-07-08 14-07-35](https://github.com/bigbluebutton/bigbluebutton/assets/6312397/f116716d-525b-48d7-a6fa-e9c315ca9223)

**BBB version:**
BigBlueButton 3.0.0-alpha.7

**Comment by antonbsa** [comment]
Although the current zoom state (v3.0-beta-6) is not as stable as expected, I haven't seen this bug specifically when testing the zoom lately
