### ISSUE TITLE
Update 2.7.10 breaks Dial-In-Clients in participant list

### ISSUE THREAD

**Issue by jacotec** [bigbluebutton/bigbluebutton#20796]
**Describe the bug**
After updating to 2.7.10, any Dial-In participants are not visible in the participants list anymore. They can participate normally in the conference, but are invisible. Due to this the moderator also has no tools to remove Dial-In participants from the conference.

Also any speaking Dial-In participants are not indicated in any way in the client (No indication who is speaking if the speaking party is a Dial-In participant)

**To Reproduce**
1. Open a conference
2. Dial-In to the conference using the phone number and PIN
3. Moderator sees Dial-In participant correctly including phone number waiting for approval
4. After approval the Dial-In participant is completely invisible. He does not appear in the participants list and there is no indication when he speaks.

**Expected behavior**
Also Dial-In participant must be listed in the participants list and their speech must be indicated (as it was before)

**Actual behavior**

**BBB version:**
BigBlueButton Server 2.7.10 (708)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, Mac] Windows, MacOS
 - Browser [e.g. Chrome, Safari] Edge, Chrome

Issue is independent from client!

A Hotfix will be highly appreciated.

**Comment by muellerlukas** [comment]
Can confirm this problem.

**Comment by antobinary** [comment]
Thanks for the report, we're looking into it!

**Comment by jacotec** [comment]
@antobinary Is a fix-release planned in the near future, or can I apply the fix manually?

**Comment by antobinary** [comment]
We are planning on releasing this within a few hours under "2.7.11".

**Comment by antobinary** [comment]
(you can also apply the fix manually if you do the change https://github.com/bigbluebutton/bigbluebutton/pull/20799 and rebuild the `bbb-html5` component)
One way to rebuld would be to run `setup.sh bbb-html5` in the `build/` directory: https://github.com/bigbluebutton/bigbluebutton/tree/v2.7.x-release/build

or to run https://github.com/bigbluebutton/bigbluebutton/blob/v2.7.x-release/bigbluebutton-html5/deploy_to_usr_share.sh on a developer environment machine and copy over the new files from `/usr/share/meteor/bundle/programs/server/app/` to your other server(s) after some testing.

We have started the release process of 2.7.11 so it should not take long.

**Comment by antobinary** [comment]
https://github.com/bigbluebutton/bigbluebutton/releases/tag/v2.7.11 was published @jacotec
