### ISSUE TITLE
Explore showing the presenter's desktop in the viewer's presentation window

### ISSUE THREAD

**Issue by bigbluebutton-issue-import** [bigbluebutton/bigbluebutton#2080]
Originally reported on Google Code with ID 1327

```
To simplify the user experience, when the presenter starts sharing his or her desktop,
have the desktop video playback in the viewer's presentation window.

This will reduce the number of open windows for the user.

```

Reported by `ffdixon` on 2012-09-29 17:02:15

**Comment by ffdixon** [comment]
Fixed in BigBlueButton HTML5 client.  See

  https://www.youtube.com/watch?time_continue=4&v=d5v6Uar79Yc

and 

  http://docs.bigbluebutton.org/2.2/install.html
