### ISSUE TITLE
[3.0] Timer/stopwatch drifts back and forth on voice activity

### ISSUE THREAD

**Issue by prlanzarin** [bigbluebutton/bigbluebutton#20858]
**Describe the bug**

The timer/stopwatch counter drifts back and forth whenever there's relevant voice activity transitions in the room.
Seemingly only affects the timer panel counter - although I recommend verifying whether the presentation area counter is affected as well.

**To Reproduce**

1. Open a 3.0 room
2. Join audio
3. Start the stopwatch, keep its panel open
4. Generate voice activity while observing the panel's counter

**Expected behavior**

No drifting.

**Actual behavior**

Drifting.

**Screenshots**

(Highlighter being active is irrelevant)

https://github.com/user-attachments/assets/e685ed2f-81bc-44c8-a47b-2f7a023dff4b

**BBB version:**

v3.0.x-release [HEAD](https://github.com/bigbluebutton/bigbluebutton/commit/45c144d43526b7019a0b806bdd2ca38e22c773ee) 

BBB <= v2.7 is unaffected.

**Desktop (please complete the following information):**

Irrelevant

**Smartphone (please complete the following information):**

Irrelevant

**Comment by ramonlsouza** [comment]
> cc @ramonlsouza et al
> 
> The issue as described (related to voice activity) is mostly fixed, but there's still scenarios where this happens (and the notification issue @Arthurk12 opened - and I'd presume the "Share camera as content" as well).
> 
> e.g., things that are causing the same behavior reported here:
> 
> * resizing the chat area
> * sharing a camera or receiving a new shared camera
> * a random client-wide update that happens due to some yet unknown prop "updating" (I saw this happen with the React highlighter, haven't got the time to track down which prop is this yet).
> 
> So probably this needs to be looked upon holistically as well rather than just focusing on specific props. The solution in #20875 maybe would catch all, for example, even if the unstable hook needed to be fixed in the first place.
> 
> Should I open a new generic issue for this?

yes, please open a new issue for this
