### ISSUE TITLE
Request for Galician language option in 'Automatic transcription'

### ISSUE THREAD

**Issue by jamesbellbn** [bigbluebutton/bigbluebutton#20909]
In addition to having English, Spanish, French, and Catalan already available, please add Galician as well.

![Automatic_transription_languages](https://github.com/user-attachments/assets/7f414e4b-0766-4ce9-88e8-122cbf21bb9d)

**Comment by antobinary** [comment]
Just need to add `gl-ES` in https://github.com/bigbluebutton/bigbluebutton/blob/v2.7.x-release/bigbluebutton-html5/private/config/settings.yml#L101
