### ISSUE TITLE
[3.0] Toast notifications reapper when talking indicator updates

### ISSUE THREAD

**Issue by Arthurk12** [bigbluebutton/bigbluebutton#20915]
**Describe the bug**
Hidden toast notifications reappear when the talking indicator updates.

**To Reproduce**
1. Join meeting with 2 sessions(s1,s2)
3. On s1 session: raise hand
4. On s2 session: hide the raise hand toast notification (grab and slide to the side)
5. On s2 session: generate voice activity
6. See error

**Expected behavior**
Hidden toast notifications should not reappear.

**Actual behavior**
They do reappear.

**Screenshots**
![talking_indicator_+_toast](https://github.com/user-attachments/assets/ce33c639-3c3e-4022-b037-0f4bdecd82df)

**BBB version:**
dev30.bigbluebutton.org

**Comment by antobinary** [comment]
Good findings, @Arthurk12 !!
