### ISSUE TITLE
Inconsistent locale used in Emoji picker 

### ISSUE THREAD

**Issue by lfzawacki** [bigbluebutton/bigbluebutton#20927]
**Describe the bug**
The emoji picker under certain circumstances will display the wrong locate strings

**To Reproduce**

1. Use the html5 client with a non English locale
2. Click the emoji picker button next to the chat box
3. Don't click the emoji picker instead press random letters on the keyboard a few times
4. Wait a few seconds and the emoji picker should display the English locale strings

**Expected behavior**
Emoji picker locale strings should match the html5 client locale

Bigbluebutton 3.0

**Comment by ramonlsouza** [comment]
not reproducible in v3.0.0-alpha.7
