### ISSUE TITLE
[3.0] Custom FreeSWITCH muted/unmuted sounds are missing

### ISSUE THREAD

**Issue by prlanzarin** [bigbluebutton/bigbluebutton#20961]
**Describe the bug**

The custom FreeSWITCH mute/unmute sounds added in 2.5 are missing in 3.0.
FS default is being used ("You're now muted/unmuted").
Custom sounds were originally added in https://github.com/bigbluebutton/bigbluebutton/pull/14588.
<= 2.7 is working regularly.

**To Reproduce**

1. Go to a 3.0 installation (stock, bbb-install)
2. Join audio
3. Mute/unmute - verify playback sound

**Expected behavior**

Use the sounds introduced in https://github.com/bigbluebutton/bigbluebutton/pull/14588.

**Actual behavior**

Using FS's default sounds.

**Additional context**

https://github.com/bigbluebutton/bigbluebutton/pull/14588

**Comment by antobinary** [comment]
A funny consequence is that we seem to reuse the newly muted sound in other areas of the client. For example trying to close the browser tab while in audio currently triggers "You are now muted" notification (without muting). It makes more sense with the custom sounds where it's just a warning beep.

![image](https://github.com/user-attachments/assets/c2179994-98c9-45f9-8595-2a106d52fbf2)
