### ISSUE TITLE
[3.0] First join in a "cold" server fails intermittently

### ISSUE THREAD

**Issue by prlanzarin** [bigbluebutton/bigbluebutton#20980]
**Describe the Bug**

The first join call on a cold server fails intermittently. A cold server is one that has been recently booted up, upgraded, or restarted and has not been used since.

This issue typically occurs in two scenarios:
- Development environments: after an `akka-apps` restart (intermittent).
- "Production" environments: after an upgrade or automated restart (unspecified amount of time afterwards).

**To Reproduce**

Steps to reproduce are unclear. The issue might occur after triggering an update, re-installation via `bbb-install`, running `bbb-conf --restart`, or restarting `akka-apps`.

The problem usually arises after performing one of the above actions and then invoking `/create` followed by `/join`. The issue is intermittent.

Refreshing the session where the error occurred usually resolves it.

**Expected Behavior**

Joining should not fail.

**Actual Behavior**

Joining a room fails.

**Screenshots**

- Error:
  ![image](https://github.com/user-attachments/assets/268ef7f6-1030-456d-bd50-d28886b40c84)
  
- Sample occurrence count on a low traffic test server with actual (not strictly developers) users:
  ![image](https://github.com/user-attachments/assets/20550b45-0345-4c3e-9d45-c92de05e8b2a)

**Additional context**

Additional logs can be provided if necessary.

**Comment by gustavotrott** [comment]
hey @prlanzarin , my merged PR should fix this issue.
let me know if you find a similar issue again!
