### ISSUE TITLE
[3.0] Timer/camera as content/raised hand notification: spurious re-renders/re-mounts

### ISSUE THREAD

**Issue by prlanzarin** [bigbluebutton/bigbluebutton#21015]
**Describe the bug**

This is a follow up to issues:
  - https://github.com/bigbluebutton/bigbluebutton/issues/20858
  - https://github.com/bigbluebutton/bigbluebutton/issues/20914
  - https://github.com/bigbluebutton/bigbluebutton/issues/20915

As mentioned in https://github.com/bigbluebutton/bigbluebutton/issues/20858#issuecomment-2303580498:

> The issue as described (related to voice activity) is mostly fixed, but there's still scenarios where this happens (and the notification issue @Arthurk12 opened - and I'd presume the "Share camera as content" as well). e.g., things that are causing the same behavior reported here:
>   - resizing the chat area
>   - sharing a camera or receiving a new shared camera
>   - a random client-wide update that happens due to some yet unknown prop "updating" (I saw this happen with the React highlighter, haven't got the time to track down which prop is this yet).
>
> So probably this needs to be looked upon holistically as well rather than just focusing on specific props. The solution in https://github.com/bigbluebutton/bigbluebutton/pull/20875 maybe would catch all, for example, even if the unstable hook needed to be fixed in the first place.

The aforementioned **list of scenarios** is just an example, **not extensive**. There might be more cases that trigger the same behavior.
Affected components are also **not an extensive list**.

So, IMO, the important part here is to treat this holistically as well rather than just focusing on specific offending props.

Since this seems to be an easier pitfall to stumble upon in 3.0, everyone would probably also benefit from an actual written "dissection" of the root cause - and some sort of guideline on how to avoid it.

**To Reproduce**

Take any of the repro steps in the issues mentioned above. Apply them to the following:
  - resizing the chat area
  - sharing a camera or receiving a new shared camera
  - a random client-wide update that happens due to some yet unknown prop "updating" (I saw this happen with the React highlighter, haven't got the time to track down which prop is this yet).
  
The above list is not extensive, just an example.

**Expected behavior**

Components should not be re-mounted unless strictly necessary.
Pure re-renders are less of an issue if they're not visible, but still good to avoid them I think?

**Actual behavior**

See issue description.

**BBB version:**

3.0 HEAD as of Aug 23

**Comment by JoVictorNunes** [comment]
#21060 and #21187 were intended to solve the problems described in this issue. I think this issue may be closed. If anything related is spotted in the future we can reopen it.
