### ISSUE TITLE
Debian packages

### ISSUE THREAD

**Issue by bigbluebutton-issue-import** [bigbluebutton/bigbluebutton#2104]
Originally reported on Google Code with ID 1351

```
The installation of Big Blue Button on Debian is complicated and it is not included
with Debian.

I therefore also filed a Debian RFP issue with more information:
http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=691978

```

Reported by `andreas.kuckartz` on 2012-11-01 10:02:38

**Comment by GhaziTriki** [comment]
Obselete. It is all packaged now.

**Comment by hex-m** [comment]
> Obselete. It is all packaged now.

Does this mean Debian (Buster?) is supported for installation? As I read the documentation I got the impression that only Ubuntu is supported. And the original question asked about inclusion into the official Debian repositories which did not happen. The [Debian RFP](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=691978) is still open.

I think this should be reopened.
