### ISSUE TITLE
I Can't enable Allow Adobe Flash Player Setting 

### ISSUE THREAD

**Issue by bigbluebutton-issue-import** [bigbluebutton/bigbluebutton#2109]
Originally reported on Google Code with ID 1356

```
I'm using Ubuntu 12.04 as a client

When i try connect as a client, i can not click or do anything to allow adobe flash
player setting..

when i use Windows 7 as client, the problem doesn't show up

Please help.. Is there another setting for ubuntu 12.04 for become client ?
```

Reported by `dedyisn` on 2012-11-08 06:30:54

<hr>
- _Attachment: Screenshot from 2012-11-08 14:28:13.png<br>![Screenshot from 2012-11-08 14:28:13.png](https://storage.googleapis.com/google-code-attachments/bigbluebutton/issue-1356/comment-0/Screenshot from 2012-11-08 14:28:13.png)_

**Comment by GhaziTriki** [comment]
Can anyone reproduce this issue under Ubuntu with the newest version of Flash Player?
