### ISSUE TITLE
Log user's choice for consent to record

### ISSUE THREAD

**Issue by jamesbellbn** [bigbluebutton/bigbluebutton#21134]
When users select Continue after being prompted for consent per https://github.com/bigbluebutton/bigbluebutton/issues/14077, that operation ought to be logged and stored somewhere, in the event any future audit requires a record of the user's choice.

**Comment by antobinary** [comment]
Note that it is not a "consent" that we're logging with these [upcoming] logs but that the user chose to continue in the session when a reminder was displayed about recording commencing.

This dialog is displayed for sessions with `record=true` and server bbb-web configuration of

```
# Notify users that recording is on
notifyRecordingIsOn=true
```

**Comment by ffdixon** [comment]
Your right, this isn't trying to serve as record of consent; rather, it is only logging that the user has acknowledged that the meeting is being recorded.

**Comment by klorydryk** [comment]
Thanks, this information will be worthwhile in case of GDPR request.
