### ISSUE TITLE
[3.0] Network instabilities cause client crashes (intermittent)

### ISSUE THREAD

**Issue by prlanzarin** [bigbluebutton/bigbluebutton#21147]
**Describe the bug**

Network instabilities may cause client crashes with a `Server closed the connection` error.

Examples of network instabilities:
  - Toggling WiFi on/off
  - Switching WiFi hotspots
  - Varying signal strength for mobile networks
  
Another unexpected byproduct is that the crashed user remains "in the room" for an extended period of time even if their session was fully closed (i.e.: tab closed). e.g.: I've seen an user stay up in the user list ~15 mins.

This seems more easily reproducible in smartphones/mobile endpoints.

Refreshing the page re-joins the client.

**To Reproduce**

1. Join a 3.0 meeting with a smartphone
2. Toggle WiFi on/off

**Expected behavior**

Client should either re-establish the main connection or fail with a proper error message.
Client should not be stuck in the meeting if the session was closed.

**Actual behavior**

Client crash (see screenshot).
Client stuck in the meeting for extended periods of time (~15 min).

**Screenshots**

![image](https://github.com/user-attachments/assets/a1839465-13cc-431f-abd1-efaa235bb7eb)

**BBB version:**

3.0 HEAD as of Sept 10.

**Smartphone (please complete the following information):**
 - OS: Android 14
 - Browser: Chrome
 - Version: 128

**Additional context**

Related: https://github.com/bigbluebutton/bigbluebutton/issues/21062

**Comment by antobinary** [comment]
I see something similar every time I restart BigBlueButton 3.0
![Screenshot from 2024-09-09 15-12-50](https://github.com/user-attachments/assets/b8a17eba-fab7-4507-9d6c-983f43a43953)

![image](https://github.com/user-attachments/assets/0f64010c-eb0e-42c8-9a1e-824332671e73)

**Comment by gustavotrott** [comment]
When the problem is on the server side the same behavior happens.
It's possible to reproduce just running `sudo systemctl restart bbb-graphql-middleware` on the server.

**Comment by TiagoJacobs** [comment]
@Tainan404 - please let's have a implementation similar with what we had in Meteor ( reconnecting attempt 1 of 10 )
