### ISSUE TITLE
Raise hand is not triggering a toast + options

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#21154]
**Describe the bug**
When a participants raises their BBB hand the moderator (and others?) should see a toast box showing the order of raised hands and an option to lower the hand(s). This is missing on 3.0.0-beta.1 circa Sept 10, 2024

**To Reproduce**
1. Join as moderator
2. Join as viewer
3. Viewer raises hand (from reactions bar)

**Expected behavior**
Moderator sees a box. And also sees the :hand: in the webcam area of the user (if webcam shared or grid mode)

**Actual behavior**
Only the :hand: is shown in the webcam area. The box is missing. Moderators can't lower that hand.

**Screenshots**
![Screenshot from 2024-09-10 15-57-24](https://github.com/user-attachments/assets/a0fc89d0-81b5-455d-90f6-f6aca45c3026)
![Screenshot from 2024-09-10 15-55-26](https://github.com/user-attachments/assets/ed82ae2c-bf56-42fa-b8bb-403a97f54853)

**BBB version:**
BigBlueButton 3.0.0-beta.1 circa Sept 10, 2024

**Comment by Scroody** [comment]
The bug appears to not happen anymore, if anyone has any extra steps or specifics to reproduce, just let me know! 🤠

![image](https://github.com/user-attachments/assets/a378d4fe-072f-4caf-bb61-54a945e58da7)
