### ISSUE TITLE
[3.0 Beta2] Pinning shared notes onto whiteboard crashes whiteboard

### ISSUE THREAD

**Issue by schrd** [bigbluebutton/bigbluebutton#21283]
**Describe the bug**
Trying to pin the shared notes onto whiteboard leads to empty presentation area. I could reproduce this on my own server as well as test30.bigbluebutton.org

**To Reproduce**
1. Open shared notes
2. Type something in shared notes
3. Pin the shared nots onto whiteboard

**Expected behavior**
Shared notes should be visible in presentation area

**Screenshots**
![Bildschirmfoto vom 2024-09-30 14-07-59](https://github.com/user-attachments/assets/fd68e094-ab3b-4b75-8e8f-add55ccafcbd)

**BBB version:**
3.0 Beta2 Client build: 739

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Firefox
 - Version 115 ESR

**Additional context**

**Comment by antobinary** [comment]
Thanks for reporting!
