### ISSUE TITLE
Pin notes onto whiteboard not working

### ISSUE THREAD

**Issue by antonbsa** [bigbluebutton/bigbluebutton#21288]
**To Reproduce**
1. Join in a meeting;
2. Open shared notes;
3. Options > Pin notes onto whiteboard;

**Video**

https://github.com/user-attachments/assets/11d1eb94-f910-477c-8df0-ef7a97bf0d7c

**Additional notes**
There's already an automated test for this feature, currently skipped as `@flaky` in CI. After this fix, we should do the following steps:
- Stop minimizing the viewer's presentation before pinning notes (due to [this](https://github.com/bigbluebutton/bigbluebutton/pull/20873#issuecomment-2278721342));
- [Avoid displaying the unrelated toast notification](https://github.com/bigbluebutton/bigbluebutton/issues/20892) on this test by using a join parameter;
- Enable this test in CI;

**Comment by antonbsa** [comment]
duplicate issue of #21283

**Comment by antobinary** [comment]
Merging into #21283
