### ISSUE TITLE
[3.0] Stale client session causes an uncontrolled reconnection loop

### ISSUE THREAD

**Issue by prlanzarin** [bigbluebutton/bigbluebutton#21285]
**Describe the bug**

A stale client session or browser tab can trigger an uncontrolled reconnection loop on the client side. While this appears benign for the server, it affects end-user systems by running an unthrottled reconnection loop continuously, causing resource overuse.

This issue was discovered when re-opening a browser with a stale client session from a defunct meeting. After a minute, I noticed excessive CPU usage and it traced back to the stale BBB session. The console log showed thousands of reconnection attempts per second.

**Steps to Reproduce:**

1. Create a meeting and join with user (u1).
2. End the meeting, but keep u1's tab open.
3. Close the browser.
4. Re-open the browser and switch to u1's old tab.
5. Observe the unbounded reconnection loop in the browser's console.

**Expected Behavior**

- If the session is stale, no reconnection attempts should be made.
- If the session is not stale, reconnection attempts should be controlled and throttled.

**Actual Behavior**

Stale sessions can lead to uncontrolled, unthrottled reconnection loops.

**Screenshots**

Here’s an example of the frequency and volume of reconnection attempt logs:

![image](https://github.com/user-attachments/assets/6e6198a4-78fb-4f32-87f6-3a8c845ea15d)

**BBB Version:**

v3.0.x-release HEAD (as of Sept 30, 2024)

**Desktop Environment:**
- **OS:** Linux
- **Browser:** Chrome
- **Version:** 129

**Comment by Tainan404** [comment]
Hello, I've been trying to reproduce this issue and i wasn't able to, could you confirm this issue still happens? or provide more details?

**Comment by antobinary** [comment]
@Tainan404 I believe something very similar happened to me today when breakouts were ending (ran out of time)
![Screenshot from 2024-10-30 15-21-28](https://github.com/user-attachments/assets/8b521c47-3d34-4346-ad66-6768d68d8f93)

I am not able to reproduce readily but the screenshot is fresh.

**Comment by antobinary** [comment]
^ actually, the server may have had its BBB restarted around the time my breakouts were ending, so this is not a reliable example...
