### ISSUE TITLE
Allow for the whiteboard options button to be repositioned

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#21301]
**Is your feature request related to a problem? Please describe.**

![Screenshot from 2024-10-01 13-00-01](https://github.com/user-attachments/assets/728a8c4a-abad-458b-bae0-4a6988fd2d76)
(a portion of a screenshot taken on mobile by @schrd plus @antobinary 's drawing on top )

The button containing options to take a snapshot of the presentation area is always located on the top-left hand corner of the presentation area. Frequently it reduces the visibility of key portion of the slide. While it can be hidden (one of its menus OR Settings toggle), it would be quite useful if we allowed to have it on the right hand side.

@KDSBrowne reminded me that the historic reason why it's anchored on the left has to do with accessibility and the order of tabbing through the client.

We need to keep the default location for accessibility purposes, as described. However, we could offer override options via join parameter (per user) or via settings.yml (per server). I don't think a per meeting configuration makes sense here.

Additionally, it would be useful to allow the user to override the configuration locally.

Note: Keep in mind that RTL layout should be handled too.

**Describe the solution you'd like**
A) Add a new menu line "Toggle options location" which would switch the location (if it was top-left it would now be top-right and vice-versa). I think only the top two corners should be considered.

B) same as A) but also a join parameter `userdata-bbb_whiteboard_options_menu_original_position` such that if `false` it switches the position and if `true` it keeps the original one. Note: it is tricky to come up with a name that would fit both LTR and RTL layouts.

C) same as B) but also a new toggle in the Settings `Position whiteboard options button on the left  ON/OFF` -- note that using LEFT/RIGHT would be a precedent for the Settings.

**Describe alternatives you've considered**
We could also add a config in `settings.yml` under `presentation`

```
# Determine the position of the whiteboard options button - whether to be on the
# left hand side (better for accessibility flow) or the right hand side
# accepted options: "left" or "right"
positionOfWhiteboardOptionsButton: "left"
```

We could then interpret the left vs right literally regardless of the layout (LTR or RTL)

**Additional context**

This was discussed in the community call on Oct 1, 2024. cc @schrd @SamuelWei

**Comment by antobinary** [comment]
My personal choice would be B) but there are various alternatives. **It would be great if we could obtain a few votes before implementing.**

**Comment by KDSBrowne** [comment]
I’m for B) — it’s simple with a quick toggle and gives extra flexibility with the join option.

**Comment by gustavotrott** [comment]
> @KDSBrowne reminded me that the historic reason why it's anchored on the left has to do with accessibility and the order of tabbing through the client.

Hey @KDSBrowne, could you clarify the specific accessibility issue with placing the button on the right side? I checked out the branch from #21428, and the tab navigation seemed the same whether the button was on the left or right. Am I missing something?

**Comment by KDSBrowne** [comment]
For most viewers, there won’t be any noticeable difference. The issue mainly affected the presenter and those with whiteboard access, as they get the extra TLDraw menu at the top with the undo and other items.

When the whiteboard options button was on the right, the tab order flowed from the top app options menu button, down to the whiteboard options, and then over to the undo toolbar on the left (starting with the first active button) before moving to the vertical toolbar on the right. This broke the expected left-to-right flow, which was flagged as a potential issue under WCAG Success Criterion 2.4.3: Focus Order.

**Comment by gustavotrott** [comment]
It makes sense now. We can't inject an element inside the `tldraw` component and have it appear after the `toolbar-extra-controls` in the order. Thanks for the clarification!

**Comment by gustavotrott** [comment]
It's unfortunate to keep the button in such an inconvenient position, even for viewers who aren't impacted by the issue. I understand the goal is to maintain consistency by placing the button in the same spot for everyone.

Have you considered alternative placements for the `tldraw-toolbar-extra-controls`? 
For instance, both the `bbb-wb-options-button` and `tldraw-toolbar-extra-controls` could be moved to the right side, 
or the `bbb-wb-options-button` could be placed on the bottom bar (before the pagination control).

I’m not sure what the ideal solution is, but the current placement is definitely frustrating. 
Even if we add the option to move it to the right, the default placement is crucial. IMO we shouldn't reduce the experience for 99% of users just to accommodate the 1% who navigate using tab. Finding a balanced solution would be ideal.

**Comment by KDSBrowne** [comment]
Yeah. Right now, we can’t inject the whiteboard options button directly into the TLDraw menu. That said, if we’re able to move to the free-to-use commercial version (with the watermark), it looks like we’d have more flexibility to customize the menus and make that work.

They’ve provided an example of how their custom menus work: [Custom Menus with TLDraw](https://tldraw.dev/examples/ui/custom-menus).

**Comment by KDSBrowne** [comment]
We did explore some alternative placements before, including moving the TLDraw toolbar to the right side. I just can’t recall exactly what issue we ran into at the time, but there was a reason we couldn’t stick with that setup.

**Comment by antobinary** [comment]
Closing via https://github.com/bigbluebutton/bigbluebutton/pull/21779 (which was possible after https://github.com/bigbluebutton/bigbluebutton/pull/21738 )
