### ISSUE TITLE
[3.0 beta 2] Edit link feature in Whiteboard discards keystrokes

### ISSUE THREAD

**Issue by schrd** [bigbluebutton/bigbluebutton#21313]
**Describe the bug**

Links in whiteboard annotations cannot be entered.

**To Reproduce**
1. Create a sticky note on the whiteboard
2. Right click on the sticky node
3. In the popup menu click on "Edit link"
4. Try to enter a URL.
5. not all keystrokes will appear in the URL field

**Expected behavior**

Is this link feature expected to work? Or should the menu item be hidden?

**BBB version:**
BBB 3.0 Beta 2

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Firefox
 - Version ESR115

**Comment by antobinary** [comment]
The popup menu should be disabled on BBB's whiteboard.
This should be closed at the same time as https://github.com/bigbluebutton/bigbluebutton/issues/21314

**Comment by antobinary** [comment]
Merging into #21314
