### ISSUE TITLE
[BBB 3.0 Beta2] Disable tldraw right-click options

### ISSUE THREAD

**Issue by schrd** [bigbluebutton/bigbluebutton#21314]
**Describe the bug**
As a user I can move shapes on the whiteboard to new pages. I am a bit confused how this is supposed to work.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a shape on the whiteboard
2. right click on the shape
3. select move to page → new page in the popup menu
5. a new empty page will be created. Any user ca do this in multiuser whiteboard mode.

**Expected behaviour**

Should users be able to create new pages in the whiteboard? If yes how do they change between the pages?

**Screenshots**

![grafik](https://github.com/user-attachments/assets/cce6dcc2-d2dd-448f-a259-eeee01d443a9)
→
![grafik](https://github.com/user-attachments/assets/c0425d8d-f243-48de-8e7c-15ba96c9d995)

**BBB version:**
BBB 3.0 Beta 2

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Firefox
 - Version: 115 ESR

**Comment by antobinary** [comment]
Thanks for reporting!

@KDSBrowne I believe we had this menu disabled. Could you confirm please?

**Comment by KDSBrowne** [comment]
Yeah, it's supposed to be disabled.
