### ISSUE TITLE
[3.0 Beta2] playing external video file broken

### ISSUE THREAD

**Issue by schrd** [bigbluebutton/bigbluebutton#21310]
**Describe the bug**

Sharing an external video does not work if the URL references a video file (not youtube etc).

**To Reproduce**
1. Share external video
2. Use https://cdn.media.ccc.de/congress/2023/h264-sd/37c3-12142-eng-deu-fra-Breaking_DRM_in_Polish_trains_sd.mp4 as URL
3. Video is stuttering and permanently toggling between playback and pause
4. open browser console and see stack trace: 
    ~~~
    Uncaught TypeError: t.getPlaybackRate is not a function
    at Object.ce (component.tsx:298:60)
    at Object.onPause (Player.js:132:20)
    at HTMLVideoElement.<anonymous> (FilePlayer.js:62:60)
    ce	@	component.tsx:298
    ~~~

Looks like the error is happening here:
https://github.com/bigbluebutton/bigbluebutton/blob/2a956988651beaf456f2cd8749f83781254f4f06/bigbluebutton-html5/imports/ui/components/external-video-player/external-video-player-graphql/component.tsx#L298

**BBB version:**
BBB 3.0 Beta 2

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Firefox and Chrome
 - Version: ESR 115 and 129.0.6668.70

**Comment by ffdixon** [comment]
Good catch!
