### ISSUE TITLE
Presentation uploader toast notification not diplayed when exporting notes from breakout rooms

### ISSUE THREAD

**Issue by antonbsa** [bigbluebutton/bigbluebutton#21321]
**Describe the bug**
Sometimes the expected toast notification is not displayed for the moderator. This is failing its automated test (currently skipped in CI)

**To Reproduce**
1. Join in a meeting with a mod and an attendee;
2. Create breakout rooms enabling the "Save shared notes" option;
3. Join the breakout room as the attendee and type some words in the shared notes;
4. As the moderator, end breakout rooms;

Also: reproducing this bug might be tricky as it doesn't occur in every attempt. Using its automated test would facilitate the debugging process: `Breakout › After creating › Export breakout room shared notes`; To run it:
```sh
# considering dependencies installed and env variables set
cd /bigbluebutton/bigbluebutton-tests/playwright
npm test breakout --parallel -- --project chromium --workers 1 -g shared --repeat-each 5
```

**Comment by antonbsa** [comment]
I also see that sometimes this toast notification is not displayed when uploading a presentation in the main room - failing other automated tests

**Comment by Tainan404** [comment]
I was investigating this issue and noticed that almost every time that the second breakout is ended this bug happens
