### ISSUE TITLE
[3.0] Wrong away toggle initial state

### ISSUE THREAD

**Issue by gabriellpr** [bigbluebutton/bigbluebutton#21333]
**Describe the bug**
When the user sets his status to away, and then reloads the page, the button changes it's side.

**To Reproduce**
1. Create a meeting
2. Join with one user
3. Set the user status to away
4. Reload the page
5. See the button changed it's side

**Video**

[recording (14).webm](https://github.com/user-attachments/assets/7da42fa8-2dd1-4394-9621-bfe1cb0ce360)

**Comment by antobinary** [comment]
Blocked by https://github.com/bigbluebutton/bigbluebutton/issues/20411
