### ISSUE TITLE
Connection status visual changes

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#21406]
**Describe the bug**
Some feedback about the Connection status list visible by moderators

**Expected behavior**
- sort by timestamp i.e. most recent incident to be on top
- put some kind of timestamp (last time we got a "pong"?) instead of the X
- make sure there is no X displayed (as it doesn't do anything anyway)

**Actual behavior**

**Screenshots**
![Screenshot from 2024-10-08 15-37-40](https://github.com/user-attachments/assets/bd870dee-04c4-4075-a49a-94676b6aee88)

**BBB version:**
BigBlueButton 3.0.0-beta.3

**Comment by antobinary** [comment]
@tylercopeland feel free to comment too

**Comment by gustavotrott** [comment]
My guess is that the time is missing for the first "Unstable Status"... and it is populated for the following occurrences.
@Tainan404 can you confirm this hypothesis?
