### ISSUE TITLE
Typing on the whiteboard can result in text hiding in the margins

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#21405]
**Describe the bug**
When you select an area of the whiteboard to type, the text actually tends to move to the left rather than to the right as accepted in LTR languages.

**To Reproduce**

**Expected behavior**
Once shown on the screen, a character/word should not shift location. Newly typed text should be placed to the right of it (in LTR languages)

**Actual behavior**
The text tends to try to escape to the left-hand margin.

**Screenshots**
[Screencast from 2024-10-09 12:13:33 PM.webm](https://github.com/user-attachments/assets/b75cbfae-9f8c-4c6b-949b-416090ce7323)
video from @soheb-somani

**BBB version:**
BigBlueButton 3.0.0-beta.3

**More**
Oddly the current behavior seems to be handled correctly (i.e. reproduces what is seen in the live session) in recordings.
When addressing, we should also test recording, playback and bbb-presentation-video

**Comment by germanocaumo** [comment]
That is the expected behaviour when the alignment is set to "middle", which is the default in our version. We may want to change the default to "start" (in latest tldraw they changed it)
![image](https://github.com/user-attachments/assets/77a74141-e1cd-4f57-88eb-aaae822550fc)
