### ISSUE TITLE
Increasing loading time/client freeze when toggling chat panel

### ISSUE THREAD

**Issue by Arthurk12** [bigbluebutton/bigbluebutton#21434]
**Describe the bug**
When toggling the chat panel, the rendering of chat messages is delayed. For 100+ messages, it takes 2-3 seconds or longer, with time increasing proportionally to the number of messages. In some cases, this results in a complete client freeze for a couple seconds(as shown in the gif below).

**To Reproduce**
1. Join meeting.
2. Open the chat panel.
3. Send at least 50 messages.
4. Toggle the chat panel.
5. Observe the delay in rendering.

**Expected behavior**
The time to render chat messages should remain consistent, regardless of the total number of messages. The existing pagination mechanism should prevent performance degradation.

**Actual behavior**
Rendering time increases with the number of messages, causing delays or even freezing the client.

**Screenshots**
![chat-toggle-issue](https://github.com/user-attachments/assets/1e604f93-c9b3-478b-90da-08156766b05d)

**BBB version:**
Reproducible on: dev30

**Comment by lfzawacki** [comment]
Chat has incorporated some new features like edit, delete, reply, but these problems still happen pretty much the same way.
