### ISSUE TITLE
Undefined user in meeting + solution

### ISSUE THREAD

**Issue by fabio-garcia** [bigbluebutton/bigbluebutton#21483]
Sometimes when a user joins and immediately leaves the meeting they end up as an undefined user, causing some notifications to break. After some digging I've stumbled into the following error in the bbb-html5 client:

```
systemd_start_frontend.sh[1803454]: 2024-10-19T23:15:10.602Z frontend-2 [#033[31merror#033[39m] : NotifyRoleInMeetingEvtMsg: TypeError: Cannot read property 'role' of undefined
systemd_start_frontend.sh[1803454]:     at EventEmitter.<anonymous> (imports/api/meetings/server/publishers.js:175:82)
systemd_start_frontend.sh[1803454]:     at EventEmitter.emit (events.js:400:28)
systemd_start_frontend.sh[1803454]:     at EventEmitter.emit (domain.js:475:12)
systemd_start_frontend.sh[1803454]:     at emitNotification (imports/api/meetings/server/modifiers/emitNotification.js:5:25)
systemd_start_frontend.sh[1803454]:     at EventEmitter.handleNotifyRoleInMeeting (imports/api/meetings/server/handlers/handleNotifyRoleInMeeting.js:14:10)
systemd_start_frontend.sh[1803454]:     at EventEmitter.emitAsync (/usr/share/meteor/bundle/programs/server/npm/node_modules/eventemitter2/lib/eventemitter2.js:1137:31)
systemd_start_frontend.sh[1803454]:     at MeetingMessageQueue.handleTask (imports/startup/server/redis.js:117:10)
systemd_start_frontend.sh[1803454]:     at imports/startup/server/redis.js:129:28
systemd_start_frontend.sh[1803454]:     at Queue.start (/usr/share/meteor/bundle/programs/server/npm/node_modules/queue/index.js:145:17)
systemd_start_frontend.sh[1803454]:     at Queue.<computed> [as push] (/usr/share/meteor/bundle/programs/server/npm/node_modules/queue/index.js:59:12)
systemd_start_frontend.sh[1803454]:     at MeetingMessageQueue.add (imports/startup/server/redis.js:128:16)
systemd_start_frontend.sh[1803454]:     at RedisPubSub.handleMessage (imports/startup/server/redis.js:289:61)
systemd_start_frontend.sh[1803454]:     at runWithEnvironment (packages/meteor.js:1486:24)
```

The log claims we're trying to access a property of an `undefined` user. This is easily reproducible by spamming the API `join` call for any moderator in the meeting followed by exiting/closing the window. Then, when `guestPolicy=ASK_MODERATOR` is set, any new attendant joining the meeting causes the above error in the html-5 client, thus breaking some notifications such as the waiting room bell sound. The above `TypeError` happens at:

`bigbluebutton-html5/imports/api/meetings/server/publishers.js:175`

```
const user = Users.findOne({ userId, meetingId }, { fields: { role: 1, userId: 1 } });
if (notification.meetingId === meetingId && notification.role === user.role) this.added('notifications', Random.id(), notification);
```

Since `user` could be `undefined`, we should check if it is [Truthy](https://developer.mozilla.org/en-US/docs/Glossary/Truthy) which is enough to account for this behavior. A solution is adding this verification at the if statement:

`if (user && notification.meetingId === meetingId && notification.role === user.role) this.added('notifications', Random.id(), notification);`

At any point when `user` is `undefined` we just ignore them. I've yet to uncover why we end up with this undefined user situation, as they weren't removed (yet?) from the meeting. Deployed this small change on our `v2.7.9` and `v2.7.14` servers and it seems to solve the issue.

**Comment by antobinary** [comment]
Thank you! What you described is now a pull request - https://github.com/bigbluebutton/bigbluebutton/pull/21490
