### ISSUE TITLE
Mute all except presenter not working

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#21553]
**Describe the bug**
Hitting "Mute all users except presenter" has no effect.

**To Reproduce**
1. Join with a few users with full audio.
2. [change presenter]
3. Select "Mute all users except presenter"

**Expected behavior**
All users should be muted (except the presenter).

**Actual behavior**
No change in audio state of users already in the session.

**Screenshots**
[Screencast from 2024-10-28 04:45:23 PM.webm](https://github.com/user-attachments/assets/b6277ae6-190f-4008-876b-8ebf1b516679)

**BBB version:**
BigBlueButton 3.0.0-beta.4

Reported by @soheb-somani

**Comment by antonbsa** [comment]
duplicate issue of https://github.com/bigbluebutton/bigbluebutton/issues/21174
