### ISSUE TITLE
[3.0-beta4] packaging: bbb-graphql-middleware binary belongs into /usr/bin

### ISSUE THREAD

**Issue by danimo** [bigbluebutton/bigbluebutton#21565]
`/usr/local/bin` is the place for binaries installed by the admin, packaged binaries go to `/usr/bin`.

**Comment by gustavotrott** [comment]
Hasura binary is placed at the same dir `/usr/local/bin/hasura-graphql-engine`.
Should it be moved too?

**Comment by danimo** [comment]
Yes, bbb should never install things in `/usr/local`. The original sin here is the recording/playback part, but not sure we want to clean this up now.
