### ISSUE TITLE
Offer the BigBlueButton VM in Open Virtualization Format

### ISSUE THREAD

**Issue by bigbluebutton-issue-import** [bigbluebutton/bigbluebutton#2158]
Originally reported on Google Code with ID 1405

```
If we support OVF format for creating the BigBlueButton VM, it would be usable in other
virtualization environments.



```

Reported by `ffdixon` on 2013-02-08 20:35:22

**Comment by ffdixon** [comment]
We are moving to using Docker for exploring containerization (see https://github.com/bigbluebutton/docker).
