### ISSUE TITLE
[3.0 Beta 4] Audio notification for new participants is unreliable

### ISSUE THREAD

**Issue by schrd** [bigbluebutton/bigbluebutton#21595]
**Describe the bug**
Audio notification for new participant is unreliable

**To Reproduce**
Steps to reproduce the behaviour:
1. Enable audio notification for new participant
2. Join a new participant
3. Sometimes the audio notification works, sometimes it doesn't. I don't understand what triggers when it works and when it doesn't work.

**Expected behaviour**
Audio notifications should work the way the user has set them up in the settings

**BBB version:**

BBB 3.0 Beta 4

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Firefox
 - Version 128 ESR

**Comment by antobinary** [comment]
Addressed by https://github.com/bigbluebutton/bigbluebutton/pull/21550
