### ISSUE TITLE
[3.0 Beta4] Presence switch in menu is reversed

### ISSUE THREAD

**Issue by schrd** [bigbluebutton/bigbluebutton#21590]
**Describe the bug**

The presence switch in the menu is turned left and green when the user indicates his presence, it is turned right and red if the user is absent.

In settings the logic is enabled = (green, right), disabled = (red, left)

**Expected behavior**

The presence switch should behave equal to settings switches.

**Screenshots**
![Bildschirmfoto vom 2024-11-01 10-42-55](https://github.com/user-attachments/assets/d8d15d28-a3ba-4306-876a-9d9f6ead528e)
![Bildschirmfoto vom 2024-11-01 10-43-13](https://github.com/user-attachments/assets/40562494-b4ea-4172-a59b-b9a2f6696897)

**BBB version:**
3.0 Beta 4

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Firefox
 - Version 128 ESR

**Comment by tylercopeland** [comment]
I'm in agreement with this feedback. 

Left = Off (red)
Right = On (green)

In special cases like the one above, instead of using "ON/OFF," the text can be contextual to the experience. In this case, we don’t need to change the text.
