### ISSUE TITLE
bbb-graphql-server: Undue restrictions in SQL schema

### ISSUE THREAD

**Issue by danimo** [bigbluebutton/bigbluebutton#21609]
**Describe the bug**
Creating meetings with an external Meeting ID of more than 100 characters will break Hasura's responses, because the external meeting ID (amongst other fields) is limited to `varchar(100)` without adequate checks in the code being in place.

**To Reproduce**
1. Create new meeting with length(Meeting ID) >= 100 chars in API Mate.
2. Join the Meeting

**Expected behavior**
Joining a meeting with long meeting IDs works just as it did in 2.x

**Actual behavior**
The `meeting_clientSettings` object from the `api/rest/clientSettings` route returns an empty array, breaking the HTML5 client ("Oops, something went wrong").

**Additional context**
Modern day Postgres gains no performance benefits from using a fixed-length `varchar` field over using type `text`, which has no upper limit. Unless the length restrictions in the SQL scheme are handled explicitly on the database layer rather than the API layer (which does not seem to be the case here), just use type `text`.

**Comment by ffdixon** [comment]
Thanks @danimo for your help!
