### ISSUE TITLE
[3.0b4] Gladia transcription not working with 2-byte characters

### ISSUE THREAD

**Issue by hiroshisuga** [bigbluebutton/bigbluebutton#21647]
**Describe the bug**
When your username is set with 2-byte characters such as Japanese, Gladia transcription does not work, no matter which language you are transcribing. Even if your username is set with alphabet, Gladia transcription of Japanese speech does not work (European languages are transcribed without problems). 
This problem starts since BBB3.0b4. 

**To Reproduce-1**
1. set your user name in 2 byte characters on Greenlight.
2. start a meeting and set the Gladia transcription on.
3. caption does not appear, no matter whether the speech language is Asian or European.

**To Reproduce-2**
1. set your name in alphabet on Greenlight
2. start a meeting and set the Gladia transcription on.
3. caption appears for European languages, but does not for Asian languages.

**BBB version:**
BBB3.0b4, all updated to the newest. I can't deny the possibility that my local setting accounts for this problem (though not very likely), as I cannot confirm it in the demo server.

**Additional context**
I dug the problem a bit, which is described at https://github.com/bigbluebutton/bbb-transcription-controller/issues/16 .

The FreeSwitch message body from BBB server (or Gladia) is contaminated with strange "control characters" such as "¥u0000", which are corrupted 2 byte letters contained in the user name or in the transcription results. 
For example, if you set your name "hsuga", the "Caller-Caller-ID-Number" is set, e.g., "w_eqlfjz63h5xf_36-bbbID-hsuga" in the message body from FreeSwitch, but if set "菅　　裕", it's set like "w_uhumzlobqt70_10-bbbID-hu000fu0005cu0000u0000   h#u0015", which the parser cannot handle. 

Even when the your name is set in alphabet, Japanese transcription does not work probably because such "control character"-like letters are contained in the transcription results originally encoded by unicode.

**Comment by hiroshisuga** [comment]
Hi @prlanzarin , I am pretty sure that I've migrated from version 3.0 beta 2, skipping beta3.

**Comment by hiroshisuga** [comment]
Hi @prlanzarin , it starts to work like a charm. Amazing..
Thank you!

**Comment by lfzawacki** [comment]
Thanks for the report and investigation @hiroshisuga and @prlanzarin . I'll update the library version and be extra careful with npm audit from now on.
