### ISSUE TITLE
Implement 3.0 chat features for bbb-playback and recording scripts

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#21645]
https://github.com/bigbluebutton/bigbluebutton/pull/21382 added the 3.0 chat enhancements to `events.xml`
Next we need to modify the recording scripts (as needed) and bbb-playback (as needed).

**Chat Reactions**
We could accumulate all ractions for a certain message and as it's time to display it at 10 mins 12s into the recorded session, display it as having 2 likes.
If the chat message was deleted later in the session, show no trace of it even if there were reactions.
I don't think we need to show who reacted with what emoji.

Food for thought: If someone reacted with :hankey: to an old message, should we show it? Likely not.
I think it might be useful to add some kind of configuration so we can reprocess a recording without chat reactions.
`includeChatReactions: true` by default

**Chat Edits**
Display the final version of the chat message (unless it was deleted).
Display an indicator to say this message was edited.
`Hi everyone! (Edited)`

**Chat Deletion**
If the chat message was deleted later in the session, show no trace of it.

**Chat reply**
If replying to a chat message that was deleted, show no trace of the reply (nor the original)
If replying to a chat message that was edited, ensure the original <at that time> is being quoted.

**Comment by GuiLeme** [comment]
Hey, left one minor comment about one of the requirements here in https://github.com/bigbluebutton/bigbluebutton/pull/21713. Feel free to comment out what you think!
