### ISSUE TITLE
Presentation area in HTML5 client doesn't resize

### ISSUE THREAD

**Issue by bigbluebutton-issue-import** [bigbluebutton/bigbluebutton#2167]
Originally reported on Google Code with ID 1414
```
The presentation area in the HTML5 client currently has a fixed, hardcoded size. Instead,
it should scale to fit the available space in the window.
```

Reported by `calvin.walton@kepstin.ca` on 2013-02-19 15:09:15

**Comment by antobinary** [comment]
Closing as it's no longer applicable. The current HTML5 client does not have this issue.
