### ISSUE TITLE
[3.0b5] nginx.service cannot be reloaded

### ISSUE THREAD

**Issue by hiroshisuga** [bigbluebutton/bigbluebutton#21687]
**Describe the bug**
After upgrading 3.0b4 to 3.0b5, "bbb-conf --restart" stopped to work with the following error:

```
Reloading NginX configuration
nginx.service is not active, cannot reload.
```

**Installation type**
Upgrading using bbb-install.

**Firewall and IP address type**
My BBB server have its own IPv4 addres.

**Additional context**
It seems 
`systemctl stop bigbluebutton.target`
stops nginx.service in my server.

If I change 
`systemctl reload nginx`
by the PR #21642 to 
`systemctl reload-or-restart nginx`
, "bbb-conf --restart" starts again.

**Comment by antobinary** [comment]
Thank you @hiroshisuga 
I did have to restart nginx on one of the systems I upgraded recently but somehow the upgrade was fine on the other system.
This adjustment you suggested should handle it. Much appreciated! Your suggestion is now present in https://github.com/bigbluebutton/bigbluebutton/pull/21689
