### ISSUE TITLE
hidePresentationOnJoin has no effect

### ISSUE THREAD

**Issue by Ithanil** [bigbluebutton/bigbluebutton#21706]
**Describe the bug**
The setting

```
public:
  layout:
    hidePresentationOnJoin: true
```

in `/usr/share/bigbluebutton/html5-client/private/config/settings.yml` has no effect. This is also true when the setting is passed as join parameter.

**To Reproduce**
1. Configure `hidePresentationOnJoin: true` (default ist `false`)
2. Start meeting with a default presentation
3. Wait for presentation to be processed
4. See the presentation popping up

**Expected behavior**
The presentation should remain hidden on join.

**BBB version:**
BBB 3.0 beta.5

**Comment by Ithanil** [comment]
bump

**Comment by mwuttke** [comment]
This is obviously a duplicate. See issue [Nr. 21581](https://github.com/bigbluebutton/bigbluebutton/issues/21581). But anyway I can repreduce this issue also with the beta.7 release.

**Comment by antobinary** [comment]
We closed the issue (and #21581 too) without a PR but I confirm that on BBB 3.0.0-rc.1 I cannot reproduce this. It was brought up in the community call on Jan 7, 2024 as a remaining bug, possibly by @mwuttke . Please try this one more time, there might be additional info needed for us to hit the bug.

![Image](https://github.com/user-attachments/assets/be4bc1e3-0288-4a36-bb7f-1643cf782224)

**Comment by Ithanil** [comment]
I don't see this issue anymore with RC1.

**Comment by mwuttke** [comment]
Me neither!
