### ISSUE TITLE
Prevent a user that has been kicked from rejoining the session

### ISSUE THREAD

**Issue by bigbluebutton-issue-import** [bigbluebutton/bigbluebutton#2171]
Originally reported on Google Code with ID 1418

```
What steps will reproduce the problem?
1.  Login to a session from two browsers: one joining as moderator, the other as a
viewer
2.  As moderator, kick the viewer from the session.
3.

The viewer should be kicked and unable to rejoin.

Currently, they are able to refresh their browser and rejoin the session.
```

Reported by `ffdixon` on 2013-02-25 15:58:21

**Comment by ffdixon** [comment]
Refreshing the browser no longer enables the user to re-join.  However, they can still go back to the front-end, such as Moodle, and rejoin from the beginning.

**Comment by pedrobmarin** [comment]
Implemented in https://github.com/bigbluebutton/bigbluebutton/pull/9188
