### ISSUE TITLE
Unable to share camera under certain conditions with Firefox 132

### ISSUE THREAD

**Issue by tibroc** [bigbluebutton/bigbluebutton#21746]
**Describe the bug**
When trying to share the camera in a room *that was started by someone else* the Webcam Settings will show "Camera 0" and "Your camera does not support this quality profile":

![image](https://github.com/user-attachments/assets/32fb59b6-e9ea-495c-aa42-1a5f8b5b975f)

With the following browser console messages:

```
DEBUG: clientLogger: Enumerate devices came back. There are 5 devices and 1 are video inputs
WARN: clientLogger: Error displaying final selection
ERROR: clientLogger: getUserMedia failed in video-preview
```

This does not happen when the user opens the room themselves.

**To Reproduce**

1. Upgrade Firefox to 132
2. Join a room that was already opened by another user
3. Click on 'Share webcam'

Apparently it can not be reproduced reliably.

**BBB version:**
2.7.15 (probably earlier versions as well)

**Desktop (please complete the following information):**
 - OS: Confirmed for linux, Mac, Win
 - Browser Firefox
 - Version 132, 133

**Smartphone (please complete the following information):**
:shrug: 

**Additional context**
This seems to be related to Firefox disabeling the `media.devices.enumerate.legacy.enabled` flag by default. When you switch this back on again in `about:config`, camera share should work.
For reference see:
- https://bugzilla.mozilla.org/show_bug.cgi?id=1916993
- and possibly: https://bugzilla.mozilla.org/show_bug.cgi?id=1528042

**Comment by lkiesow** [comment]
An idea would be to test if executing the following command in the browser console, before sharing your webcam, can you still reproduce the issue at all:

```js
_getUserMedia = navigator.mediaDevices.getUserMedia;
navigator.mediaDevices.getUserMedia = function() {
  console.info('Called getUserMedia', arguments);
  return _getUserMedia.apply(this, arguments);
}

_enumerateDevices = navigator.mediaDevices.enumerateDevices;
navigator.mediaDevices.enumerateDevices = async function() {
  await navigator.mediaDevices.getUserMedia({video: true, audio: true});
  console.info('Called enumerateDevices', arguments);
  return _enumerateDevices.apply(this, arguments);
}
```

This ensures that `getUserMedia` gets called before calling `enumerateDevices`. If the theory Timo mentioned above is correct, that should fix the issue.

This should also help if you did already run into the problem. Executing this and trying to share the webcam again should then also fix the problem.

**Comment by lkiesow** [comment]
Since last week I've experienced this once again and also have seen quite a number of people run into this.

Since it just occurs from time to time, most people expect that to be faulty hardware, … it seems. For example, one colleague told me that he had seen this as well the day before but thought that it must be the mac monitor he had the webcam hooked up to.

All in all, telling people about this and looking for this, we found that things work most of the time, but given the number of people using BBB at our place, the bug is actually a quite regular occurrence.

**Comment by lkiesow** [comment]
Also, I've asked some technical people to try the snippet from above if the error occurs for them and the script reliably fixes the problem. That means we should ask for permission first and only then try to list the devices.

**Comment by lkiesow** [comment]
Having to run `getUserMedia` before `enumerateDevices` seems to be exactly what Firefox requires. They also mention Safari exploring the same option: https://bugzilla.mozilla.org/show_bug.cgi?id=1528042
Despite that being an old issue it seems like that's now active by default in Firefox ≥ 132.

**Comment by lkiesow** [comment]
> […] Running enumerate before getUserMedia should not break subsequent getUserMedia calls like what's happening in the report. […]

I don't think that's what is happening here. Running enumerate before gUM does mean that enumerate doesn't return a valid result. It doesn't mean that following calls to gUM are broken.

I think what's happening is that BBB tries to enumerate the devices, gets no proper feedback and either doesn't call getUserMedia at all or feeds it something weird.

That is why, even if the error already appeared in the HTML5 client, you can run:
```js
navigator.mediaDevices.getUserMedia({video: true, audio: true});
```
…and then just re-open the camera share dialog and things will work.

**Comment by tibroc** [comment]
https://github.com/bigbluebutton/bigbluebutton/pull/21864 seemed to do the trick, while we left https://github.com/bigbluebutton/bigbluebutton/pull/21848 deactivated. Closing this...

Thanks Paulo!
