### ISSUE TITLE
BigBlueButton 3.0 beta5 Breakout room issue

### ISSUE THREAD

**Issue by sudanking** [bigbluebutton/bigbluebutton#21760]
**Describe the bug**
I tested breakout room in ver 3.0 beta5 and I found the following:
1- I create 4 rooms, but I can see only 2 (I tried 3, but only showing 2) when I tried to manage users between rooms.
2- Number of users in each room always 0
3- if I move users from room to other, it is not moved.

**Expected behavior**
When I create breakout room, I get the same numbers of rooms get created. And I can move users between them.

**Actual behavior**
Only 2 room appear in manage users screen.
Users not moved between breakout rooms
number of users in each room always showing 0

**Screenshots**
![image](https://github.com/user-attachments/assets/66483062-8540-45e9-9470-711e047cb2cb)
![image](https://github.com/user-attachments/assets/24b658e2-dba5-423d-9d26-1852da892d03)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [Librewolf]
 - Version [Version 132.0.2-1 (64-bit) ]

**Smartphone (please complete the following information):**
 - Device: [OnePlus12]
 - OS: [Andoird]
 - Browser [Firefox]
 - Version [132.0.2]

**Comment by antobinary** [comment]
Thanks for reporting!

**Comment by mwuttke** [comment]
I'm sorry, but after updating to version [bbb-beta.7](https://github.com/bigbluebutton/bigbluebutton/releases/tag/v3.0.0-beta.7) the error still occurs on my test setup. After creating four or five breakout rooms, assigning a user to one of the rooms and then calling up the ‘Manage users’ page, I only see two rooms again.
