### ISSUE TITLE
Javascript API demo not working on IE 10, Win 7

### ISSUE THREAD

**Issue by bigbluebutton-issue-import** [bigbluebutton/bigbluebutton#2231]
Originally reported on Google Code with ID 1478
```
When trying the javascript demo page, it works in Chrome, and Firefox.

But just get a blue screen in IE when flash tries to load the client.

see attachment




```

Reported by `207TECH` on 2013-04-23 01:32:46

<hr>
 * *Attachment: JavaIE-Bug.PNG<br>![JavaIE-Bug.PNG](https://storage.googleapis.com/google-code-attachments/bigbluebutton/issue-1478/comment-0/JavaIE-Bug.PNG)*

**Comment by ffdixon** [comment]
Won't take any action on this.  Microsoft has ended support for IE 10 (and older) browsers.  See

   https://www.microsoft.com/en-us/WindowsForBusiness/End-of-IE-support
