### ISSUE TITLE
Linux support with FlashPlayer 11.2

### ISSUE THREAD

**Issue by bigbluebutton-issue-import** [bigbluebutton/bigbluebutton#2232]
Originally reported on Google Code with ID 1479
```
The latest FlashPlayer version available for Linux is 11.2.

This out-of-date version appears insufficient for BigBlueButton.

Symptoms: when connecting, the client loads to 100%, then hangs on “Connecting to the
server”.

(Gnash 0.8.10 and Lightspark 0.5.5 do not appear to work either)


(spinned off from issue 1243)
```

Reported by `JeanFred1` on 2013-04-24 22:07:48

**Comment by mikhailnov** [comment]
That seems to be a user-specific issue, I didn't experince anything like that on different machines.

**Comment by kepstin** [comment]
Yes, we regularly test the current BigBlueButton client with Flash 11.2 on Linux and ensure it works. I don't think this issue is valid any longer.
