### ISSUE TITLE
Warning On Flash Debugger When Changing Language

### ISSUE THREAD

**Issue by bigbluebutton-issue-import** [bigbluebutton/bigbluebutton#2235]
Originally reported on Google Code with ID 1482
```
There's something wrong on the language combo box
You can produce this when you use flash debugger
Please refer to my attachment

Another example for similar problem with explanation:
http://nwebb.co.uk/blog/?p=318

To know how to fix please refer :
http://livedocs.adobe.com/flex/3/html/help.html?content=createevents_3.html

```

Reported by `yauriedogawa` on 2013-04-26 15:10:55

<hr>
 * *Attachment: Screen Shot 2013-04-26 at 10.59.06 PM.png<br>![Screen Shot 2013-04-26 at 10.59.06 PM.png](https://storage.googleapis.com/google-code-attachments/bigbluebutton/issue-1482/comment-0/Screen Shot 2013-04-26 at 10.59.06 PM.png)*

**Comment by ffdixon** [comment]
@capilkey Is this still an issue?

**Comment by capilkey** [comment]
I can't reproduce this. I was reported pre-0.81 release so it was probably fixed at some point in the past.
