### ISSUE TITLE
Chat keyboard shortcut combination

### ISSUE THREAD

**Issue by bigbluebutton-issue-import** [bigbluebutton/bigbluebutton#2256]
Originally reported on Google Code with ID 1504

```
I am using the chat keyboard shourtcuts and for the "Focus on chat input window" says
CTRL+I. This can confuse the user between capital i or small L and it is neither combinations,
the font might also contribute to it. I discovered that CTRL+l (small L) logs you out
:) 
Thanks. 
```

Reported by `saadnouri` on 2013-05-14 20:36:45

**Comment by ffdixon** [comment]
With the keyboard shortcuts in the HTML5 client, you can focus the cursor on the chat input filed with Alt + P
 ![image](https://user-images.githubusercontent.com/290351/57977116-0ddfdc80-79bf-11e9-8a3e-615edc804634.png)
