### ISSUE TITLE
In client ChatModule add a property to config.xml to disable chat input

### ISSUE THREAD

**Issue by bigbluebutton-issue-import** [bigbluebutton/bigbluebutton#2260]
Originally reported on Google Code with ID 1508

```
Add property to ChatModule

   <module name="ChatModule" ...
        enableInput ="false"
   />

that disables the chat input field for user.  The could be used with the dynamic config.xml
to restrict features to a view only mode.
```

Reported by `ffdixon` on 2013-05-17 12:23:34

**Comment by GhaziTriki** [comment]
It can be achieved using the new lock settings.

**Comment by ffdixon** [comment]
Won't fix as we already have the lock settings, when enables a moderator to lock out the chat capabilities of viewers.

![image](https://user-images.githubusercontent.com/290351/41502511-90ea699a-7189-11e8-8f4b-a3d742349a2a.png)
