### ISSUE TITLE
Add a highlight tool to the whiteboard

### ISSUE THREAD

**Issue by bigbluebutton-issue-import** [bigbluebutton/bigbluebutton#2269]
Originally reported on Google Code with ID 1517

```
Add a highlighter tool to the whiteboard.


```

Reported by `ffdixon` on 2013-05-21 16:45:12

**Comment by pedrobmarin** [comment]
Being discussed in https://github.com/bigbluebutton/bigbluebutton/issues/3025 and https://github.com/bigbluebutton/bigbluebutton/issues/11012 and prototype made in https://github.com/bigbluebutton/bigbluebutton/pull/11021.
