### ISSUE TITLE
Polling Window off screen, can'f click PREVIEW.

### ISSUE THREAD

**Issue by bigbluebutton-issue-import** [bigbluebutton/bigbluebutton#2303]
Originally reported on Google Code with ID 1551
```
.81 polling enabled

On a 14inch laptop.

1) Open a small poll with 1 question and 4 choices.
2) The PREVIEW button is off screen so no way to submit.
3) You can grab an edge of window and resize smaller, scroll bars appear and so can
then move the module window up to click PREVIEW.

Looks like a lot of free space on form, and it can be compressed.
```

Reported by `207TECH` on 2013-06-08 20:26:39

<hr>
 * *Attachment: pollwindow.PNG<br>![pollwindow.PNG](https://storage.googleapis.com/google-code-attachments/bigbluebutton/issue-1551/comment-0/pollwindow.PNG)*

**Comment by ffdixon** [comment]
Closing as this relates to our older implementation of polling (replaced with a newer implementation in 1.0-beta).
