### ISSUE TITLE
Activating/Deactiving wireless on Google Chrome can cause a dropped connection

### ISSUE THREAD

**Issue by bigbluebutton-issue-import** [bigbluebutton/bigbluebutton#2308]
Originally reported on Google Code with ID 1556

```
What steps will reproduce the problem?
1.  Connect a laptop to a wired network
2.  Join a BigBlueButton session
3.  Enable/disable wireless on the laptop

The BigBlueButton session will drop when the laptop enables/disables wireless.  This
will not happen in FireFox.


```

Reported by `ffdixon` on 2013-06-13 18:11:55

**Comment by ffdixon** [comment]
Tested it on the latest build -- the client will reconnection with audio and video, but sometimes results in broadcasting multiple video streams to participants.  

Not marketing this as closed yet.

**Comment by ffdixon** [comment]
Let's test this with the BigBlueButton HTML5 client in 2.2

**Comment by ffdixon** [comment]
This is no longer an issue on the HTML5 client.
