### ISSUE TITLE
Validate events.xml in sanity phase

### ISSUE THREAD

**Issue by bigbluebutton-issue-import** [bigbluebutton/bigbluebutton#2314]
Originally reported on Google Code with ID 1562

```
The sanity script should be responsible for creating the start or stop events that do
not exist in events.xml, so every method that process video from webcam or deskshare
, audio, don't have to repeat that task.
```

Reported by `guga.salazar.loor` on 2013-06-20 20:55:24

**Comment by ffdixon** [comment]
@kepstin Do we not have this in the sanity phase?

**Comment by kepstin** [comment]
No reason to fix this. It's better to leave events.xml unmodified for debugging reasons. The recording scripts already have the relevant cleanup code abstracted in libraries.
