### ISSUE TITLE
Whiteboard toolbar appears over other windows

### ISSUE THREAD

**Issue by bigbluebutton-issue-import** [bigbluebutton/bigbluebutton#2317]
Originally reported on Google Code with ID 1565

```
Build - 0.81 (latest source as of 6/22/2013 @ 12:51pm EST)

Issue:
     The presentation module's `toolbox` window priority is above any other. Much like
with CSS's z-index. It is not a big deal, not really a bug, just a particular issue
that may need enhancements in future releases.


See attached screenshot.
```

Reported by `josephorlando11` on 2013-06-22 16:53:24

<hr>
- _Attachment: issue.png<br>![issue.png](https://storage.googleapis.com/google-code-attachments/bigbluebutton/issue-1565/comment-0/issue.png)_

**Comment by capilkey** [comment]
This is intended behaviour so that it can "float" above the presentation window. The WhiteboardTextToolbar functions in the same way.
