### ISSUE TITLE
Play sound when someone raises their hand

### ISSUE THREAD

**Issue by bigbluebutton-issue-import** [bigbluebutton/bigbluebutton#2346]
Originally reported on Google Code with ID 1594

```
See discussion

   https://groups.google.com/d/msg/bigbluebutton-dev/CtADHxjOy5U/EykEhhj8b9MJ

Emit a sound for the presenter when a user raises their hand in a session.

```

Reported by `ffdixon` on 2013-07-23 19:11:28

**Comment by neeesn** [comment]
Any ETA on this issue ? Or has it been skipped again

**Comment by ffdixon** [comment]
For information on how we prioritize features between releases, see http://docs.bigbluebutton.org/support/faq.html#when-will-feature-x-be-implemented

**Comment by neeesn** [comment]
So it not in the roadmap - but it is accepted 2 years ago? - Didnt help on the ETA of the feature. I understand its low pri.

**Comment by ffdixon** [comment]
Hi Neesn,

There are many enhancement requests in our issue tracker, and it's not possible to do everything (as much as we would like!); hence, the need to prioritize them.

Knowing that folks are interested in this feature helps us put it at a higher priority.  

We're not saying it will be part of the next release -- for a look ahead at our current plans, see presentations from our recent developer summit: https://bigbluebutton.org/2017/05/10/developer-summit-x/ -- but this is not a large feature and we'll see what we can do.

Thanks again for your feedback.

**Comment by mtsonline** [comment]
would be great to see this in a upcoming release - would improve usability and accessibility a lot.

**Comment by KDSBrowne** [comment]
This raise hand sound was implemented as part of the update to the notification options in  #8814
