### ISSUE TITLE
Audio and Video are too far out of sync

### ISSUE THREAD

**Issue by bigbluebutton-issue-import** [bigbluebutton/bigbluebutton#2356]
Originally reported on Google Code with ID 1604

```
We're noticing in the latest builds for 0.81-beta-2 that the audio and video are to
far out of sync, see

  https://groups.google.com/d/msg/bigbluebutton-dev/hYk8IhK8qp4/bKpFPuKIwBQJ

We're suspecting that FreeSWITCH has not recorded all the audio, or there are gaps
in the audio.

More investigation needed.

```

Reported by `ffdixon` on 2013-08-01 01:13:39

**Comment by alialic** [comment]
The reason for the delay between audio and video in the file playback in bigbluebutton 2.2

**Comment by alialic** [comment]
Hi all
Why is the audio and video in the playback file  in 2.2 version not sync?

**Comment by matiasilva** [comment]
This issue is 5 years old. Can you please submit your detailed support request to the mailing lists: https://groups.google.com/forum/#!forum/bigbluebutton-setup
