### ISSUE TITLE
Whiteboard Rectangle and Circle Drawing Bug

### ISSUE THREAD

**Issue by bigbluebutton-issue-import** [bigbluebutton/bigbluebutton#2359]
Originally reported on Google Code with ID 1607

```
What steps will reproduce the problem:
- select the circle or rectangle tool
- hold down 'control' (not sure what the equivalent is on Macs) and drag the mouse
- if done a certain way near the bottom edge of the whiteboard, it will cause the 
  rectangle/circle, which are now "locked", to overflow into the other module space

What is the expected outcome?
- the circle/rectangle should be constrained to the boundaries of the whiteboard

What is the actual outcome?
- the circle/rectangle leaves the constraints of the whiteboard

I should note that this appears to be only for the presenter, and it shows up properly
for the viewers.

Reported by Ajay in bigbluebutton-dev, see

  https://groups.google.com/d/msg/bigbluebutton-dev/Zk1bsmfeotM/gggGoksLOxAJ


```

Reported by `ffdixon` on 2013-08-08 12:52:27

<hr>
- _Attachment: error1.png<br>![error1.png](https://storage.googleapis.com/google-code-attachments/bigbluebutton/issue-1607/comment-0/error1.png)_
- _Attachment: error2.png<br>![error2.png](https://storage.googleapis.com/google-code-attachments/bigbluebutton/issue-1607/comment-0/error2.png)_

**Comment by ffdixon** [comment]
This is an old bug and the issue has long been fixed.  Of course, if we ever see any problems around this area, we'll open a new issue to track it.
