### ISSUE TITLE
Add subtitles for names of users in recodings

### ISSUE THREAD

**Issue by bigbluebutton-issue-import** [bigbluebutton/bigbluebutton#2367]
Originally reported on Google Code with ID 1615

```
When creating a recording, add the user's name as a subtitle for their video.

```

Reported by `ffdixon` on 2013-09-01 11:30:37

**Comment by pedrobmarin** [comment]
This was duplicated in https://github.com/bigbluebutton/bigbluebutton/issues/4025. Since the discussion is there I'm closing this one.
