### ISSUE TITLE
blank layout list ---0.81beta2

### ISSUE THREAD

**Issue by bigbluebutton-issue-import** [bigbluebutton/bigbluebutton#2370]
Originally reported on Google Code with ID 1618
```
Hi, 
I have successfully installed the BBB 0.81beta2 on an dedicated server. 
and it work perfect. 

I proceeded to install the development environment, and built a client off the latest
BBB repository.

I joined in the meeting and clicked the "apply a layout" button at the lower right
corner. and the layout list turned up as a blank one. see the attachment 
```

Reported by `wangjingzhou.GW` on 2013-09-03 14:50:16

<hr>
 * *Attachment: blank layout-list.png<br>![blank layout-list.png](https://storage.googleapis.com/google-code-attachments/bigbluebutton/issue-1618/comment-0/blank layout-list.png)*

**Comment by ffdixon** [comment]
Old issue (and likely a result of their development environment).
