### ISSUE TITLE
Reduce (or eliminate) the fade-to-white transition between slides  

### ISSUE THREAD

**Issue by bigbluebutton-issue-import** [bigbluebutton/bigbluebutton#2372]
Originally reported on Google Code with ID 1620

```
See initial discussion

  https://groups.google.com/d/msg/bigbluebutton-users/i-0H4Ds8hiQ/dFH6zNINBucJ


```

Reported by `ffdixon` on 2013-09-12 14:15:49

**Comment by ffdixon** [comment]
Closing this issue -- we'll keep the fade-to-white in the transitions between slides.
