### ISSUE TITLE
Add parameter to config.xml to skip the camera settings dialog

### ISSUE THREAD

**Issue by bigbluebutton-issue-import** [bigbluebutton/bigbluebutton#2382]
Originally reported on Google Code with ID 1630

```
Add

  skipCamSettingsCheck="true"

to config.xml to enable administrator to configure the BigBlueButton server to skip
the camera settings dialog.


```

Reported by `ffdixon` on 2013-09-26 20:36:44

**Comment by rriscado** [comment]
I include this parameter in /usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml after "skipCheck" parameter, but doesn't works.

Where I include the "skipCamSettingsCheck" parameter to works fine in HTML5?
