### ISSUE TITLE
Unable to join meeting.

### ISSUE THREAD

**Issue by bigbluebutton-issue-import** [bigbluebutton/bigbluebutton#2383]
Originally reported on Google Code with ID 1631

```
I have bigbluebutton server. 
Specs is: 5gig ram, dual core on a cloud vps setup.
And running the latest bigbluebutton. 0.81rc.

I used bigbluebutton as an Activity module in my Moodle.
Sometimes when i open it to connect to my vps server, there is an error 
that says:

"Unable to join meeting. Please check the url of the BigBlueButton Server AND check
to see if the BigBlueButton server is running".

According to support rep of my hosting company, the server is running fine.

What's happening here? I can't seem to connect sometimes.
```

Reported by `jm.030604` on 2013-09-27 03:11:54

**Comment by hm0ss** [comment]
I and my friends are also not able to join the session. It says waiting for the moderator to join while the lecturer has been lecturing for an hour! First I was able to join but I couldn't hear anything nor see the slides. I left the session once and joined again. This time I could hear but not see anything. After I restarted my modem, I wasn't able to join and that's a big bug.

**Comment by matiasilva** [comment]
Please contact your system administrator.

**Comment by ffdixon** [comment]
This issue has been fixed in the latest versions of Greenlight.  Contact your system administrator and have them update to the latest version of 2.7.x.  https://github.com/bigbluebutton/greenlight/releases
