### ISSUE TITLE
keep custom parameters after upgrade

### ISSUE THREAD

**Issue by bigbluebutton-issue-import** [bigbluebutton/bigbluebutton#2396]
Originally reported on Google Code with ID 1644

```
What steps will reproduce the problem?
1.Install record and playback scripts for Matterhorn integration and configure matterhorn.yml
2. Upgrade your BigBlueButton server


What is the expected output? What do you see instead?
Custom values in /usr/local/bigbluebutton/core/scripts/matterhorn.yml are replaced
by default values in the upgrade


```

Reported by `guga.salazar.loor` on 2013-10-10 18:07:16

**Comment by ffdixon** [comment]
We're adding the ability for the moderator to specify custom configuration changes after package updates and before restart using bbb-conf.

You can see the start of this in `/etc/bigbluebutton/bbb-conf/apply-lib.sh`.

- [ ] Add documentation
