### ISSUE TITLE
different file with same name keeps shapes from old file in presentation

### ISSUE THREAD

**Issue by bigbluebutton-issue-import** [bigbluebutton/bigbluebutton#2409]
Originally reported on Google Code with ID 1657
```
What steps will reproduce the problem?
1.Upload a file
2.Change file and keep same name or upload another file with the same name
3.Upload same filename again

What is the expected output? What do you see instead?
Should be blank but instead kept the shapes from the old file with the same name



```

Reported by `mohamed.ahmed0071` on 2013-10-15 18:04:45

**Comment by ffdixon** [comment]
Made changes to a file three times and saved it as the same file name, each time uploaded it to BigBlueButton.

BigBlueButton now keeps track of files using an internal file name, so uploaded files can now have duplicate names.  

![image](https://cloud.githubusercontent.com/assets/290351/12698998/2fca9c7c-c77a-11e5-8d9e-6cd9eefb0637.png)
