### ISSUE TITLE
Add a configuration for user to have BigBlueButton client emit a sound when a new users joins the session.

### ISSUE THREAD

**Issue by bigbluebutton-issue-import** [bigbluebutton/bigbluebutton#2411]
Originally reported on Google Code with ID 1659

```
The use case is virtual office hours.  The teacher is in a session by themselves and
is looking for an audible alert when a new user joins. 



```

Reported by `ffdixon` on 2013-10-17 15:07:29

**Comment by uka-support** [comment]
This is already implemented - you can adjust the settings of the room accordingly. (It doesn't seem to be persistent for the room though, only for current session.)

**Comment by GhaziTriki** [comment]
Implemented.
