### ISSUE TITLE
PDF file problem

### ISSUE THREAD

**Issue by bigbluebutton-issue-import** [bigbluebutton/bigbluebutton#2414]
Originally reported on Google Code with ID 1662
```
This file from SONY produces white pages and also pages without a background.

The problem with background is attached (PNG file).

PDF file with problem: 
https://dl.dropboxusercontent.com/u/9226799/bug-bbb-pdf.pdf

If we decrypt PDF file using qpdf, the problem is solved.
"qpdf --password= --decrypt $1 out/decrypted.pdf"

The decrypted.pdf doesn't produce the problem.

Link to decrypted.pdf: 
https://dl.dropboxusercontent.com/u/9226799/decrypted.pdf

Suggested fix: Use qpdf command before the conversion process
```

Reported by `tiago.jacobs` on 2013-10-18 14:25:22

<hr>
 * *Attachment: bug-pdf.png<br>![bug-pdf.png](https://storage.googleapis.com/google-code-attachments/bigbluebutton/issue-1662/comment-0/bug-pdf.png)*

**Comment by ffdixon** [comment]
Checked and it now displays properly in BigBlueButton 1.0-beta.

![image](https://cloud.githubusercontent.com/assets/290351/12699030/34032f74-c77b-11e5-98cd-f725ce39faad.png)
