### ISSUE TITLE
The draw thickness in the Flash client for annotations does not change with the zoom

### ISSUE THREAD

**Issue by bigbluebutton-issue-import** [bigbluebutton/bigbluebutton#2426]
Originally reported on Google Code with ID 1674

```
What steps will reproduce the problem?
1. Draw a 30 thickness line
2. Zoom the presentation in to 200%

What is the expected output? What do you see instead?
The line thickness is still 30, but it should be 60.

```

Reported by `capilkey` on 2013-10-29 17:08:43

**Comment by GhaziTriki** [comment]
Cannot reproduce this. Drawing thickness and zoom level match all the time.

**Comment by capilkey** [comment]
Steps to reproduce the second part reported on 2013-10-31:

1. Make the client big
2. Set the line thickness in the middle
3. Draw a pencil line
4. Reduce the width of the PresentationWindow

The line thickness will stay the same even though the scale of the page changes.

The shapes don't consider the presenter's scale factor so it is currently impossible to make it scale correctly.
