### ISSUE TITLE
Webcams are show as half-height windows

### ISSUE THREAD

**Issue by bigbluebutton-issue-import** [bigbluebutton/bigbluebutton#2438]
Originally reported on Google Code with ID 1686
```
Unable to reproduce these yet, but reported

  https://groups.google.com/d/msg/bigbluebutton-users/OhYTFKZqLl4/BuYUgFArXiEJ


```

Reported by `ffdixon` on 2013-11-15 22:13:36

<hr>
 * *Attachment: download.png<br>![download.png](https://storage.googleapis.com/google-code-attachments/bigbluebutton/issue-1686/comment-0/download.png)*

**Comment by ffdixon** [comment]
Marking this as fixed. We've done a number of revisions to the handling of webcams and have not seen this issue now for a few months.  

We can re-open it again if it reappears.
