### ISSUE TITLE
DeskShare does not work on Windows 8 Modern UI (Metro)

### ISSUE THREAD

**Issue by bigbluebutton-issue-import** [bigbluebutton/bigbluebutton#2439]
Originally reported on Google Code with ID 1687

```
Windows 8 Metro UI (Metro) IE supports flash but not java.
For DeskShare to work, we can prompt user to switch to desktop IE.

This can be done via HTTP Header
X-UA-Compatible: requiresActiveX=true

or META tag in the HTML
<meta http-equiv="X-UA-Compatible" content="requiresActiveX=true"/>

(Details at http://msdn.microsoft.com/en-us/library/ie/hh920753(v=vs.85).aspx)


The java test page uses Meta tag
http://www.java.com/en/download/installed.jsp
See attached image for prompt.



```

Reported by `Mike.Lim.CE` on 2013-11-17 01:18:31

<hr>
- _Attachment: RequireActiveX.png<br>![RequireActiveX.png](https://storage.googleapis.com/google-code-attachments/bigbluebutton/issue-1687/comment-0/RequireActiveX.png)_

**Comment by ffdixon** [comment]
Fixed in BigBlueButton 1.1 as we can now share desktop in the latest version of Microsoft Edge on Windows 10 by launching screen sharing outside the browser.

![desktop-edge](https://cloud.githubusercontent.com/assets/290351/21966224/9fcd5fb4-db3d-11e6-8806-d10d974a2031.png)
