### ISSUE TITLE
slides_new.xml contains chat but slides

### ISSUE THREAD

**Issue by bigbluebutton-issue-import** [bigbluebutton/bigbluebutton#2443]
Originally reported on Google Code with ID 1691

```
In playback:

"slides_new.xml" is used as timeline source in the audio html tag, this xml file only
contains chat messages. Change its name to "chat.xml" . Slides are taken from "shapes.svg"
```

Reported by `guga.salazar.loor` on 2013-11-25 18:54:36

**Comment by pedrobmarin** [comment]
@kepstin would you like to change this? I could adapt the new playback to try multiple filenames for the chat.

**Comment by kepstin** [comment]
No reason to change it in the current presentation playback. Trying multiple filenames provides no benefit, and only makes the recording loading slower. This is something that should be fixed when we come up with a new recording format.
