### ISSUE TITLE
Add an erase operation

### ISSUE THREAD

**Issue by bigbluebutton-issue-import** [bigbluebutton/bigbluebutton#2473]
Originally reported on Google Code with ID 1721

```
In bit-mapped whiteboards, it's common to have an erase tool.  A stroke of this tool
simply turns all the pixels to white.

BigBlueButton's whiteboard is vector-based to reduce bandwidth.  While not easy to
add an erase option, we could fake implementing an erase tool as a very white line.

You can experiment with this by choosing the pen tool, increase to maximum thickness,
and draw over an existing object.

Unfortunately, this only works if the user is drawing on a white background, as drawing
a thick white segment would also obscure the slides behind line.

```

Reported by `ffdixon` on 2014-02-01 00:38:38

**Comment by antobinary** [comment]
Merging into #6026

**Comment by hippylover** [comment]
Is a proper Eraser planned that remembers the background?

**Comment by hippylover** [comment]
You could reuse the code to draw in the first place to take copies of the geometrical areas where the brush is located, then save them in a cache. When one chooses the eraser you could simply replace the previous brush with the saved picture.

This is just an idea.

**Comment by ybazlov** [comment]
Given that the whiteboard is based on vector graphics, it is in my opinion not currently possible to implement an eraser which would delete parts of an object on the canvas. Deleting a part of a Bezier curve would mean calculating the connected components of the curve after deletion - a hard topological and analytical problem.

Two existing alternatives:

1. "Correction fluid" - draws a new curve in opaque "background" color over the existing curves.

2. "Select and delete" - a tool to select an object or objects and a tool to delete the selected objects. (Warning: perhaps the "correction fluid" needs to be made unselectable and undeletable.)

Both alternatives are implemented in commercial WebRTC-based systems. I have not seen a tool which would sample the background.
