### ISSUE TITLE
Explore ways to reduce the occurrences of disconnects on wireless networks

### ISSUE THREAD

**Issue by bigbluebutton-issue-import** [bigbluebutton/bigbluebutton#2480]
Originally reported on Google Code with ID 1728
```
Currently, if BigBlueButton detects its network connection has dropped, it immediately
disconnects the user and closes the session.  This ensures the user does not believe
the client is still connected when, in fact, it's no longer receiving updates from
the server.

The initial disconnect occurs from the red5 server after it fails to get a response
from a heartbeat check for the client.  If not response (with a given threshold) is
received, red5 disconnects the client, which triggers the client to close.

Explore if it's possible to adjust the thresholds and lower the frequency of disconnects
on a wireless network without introducing performance (or delays) into the connection
logic.
```

Reported by `ffdixon` on 2014-02-13 01:46:25

**Comment by ffdixon** [comment]
While we can't reproduce the level of disconnects at the OS, we have improved the ability of the BigBlueButton client to auto-reconnect if the network drop is temporary (as in a network state change).

Here's a video with BigBlueButton 1.0-beta where trigger a network change in Chrome on by turning on the wireless in Mac OS X

   https://www.youtube.com/watch?v=a3coz71Z1kc

The client completely reconnects.  (There is a bug where the client will sometimes open two webcams, but we'll open another issue for that).
