### ISSUE TITLE
Gaps in whiteboard drawing on slow network connection

### ISSUE THREAD

**Issue by bigbluebutton-issue-import** [bigbluebutton/bigbluebutton#2487]
Originally reported on Google Code with ID 1735

```
Just spoke with an administrator of a BigBlueButton server.  The server is on a slower
network and it appears to have gaps in the recording of lines.

See attached image.
```

Reported by `ffdixon` on 2014-03-13 15:46:19

<hr>
- _Attachment: slow.PNG<br>![slow.PNG](https://storage.googleapis.com/google-code-attachments/bigbluebutton/issue-1735/comment-0/slow.PNG)_

**Comment by capilkey** [comment]
This shouldn't happen anymore with the 2.0 whiteboard refactor, but will need to verify.
