### ISSUE TITLE
Support slide animations from PowerPoint

### ISSUE THREAD

**Issue by bigbluebutton-issue-import** [bigbluebutton/bigbluebutton#2489]
Originally reported on Google Code with ID 1737

```
Support slide animations from Power Point
```

Reported by `ffdixon` on 2014-03-18 11:34:47

**Comment by TillF** [comment]
+1
A first fix would be issueing a warning when the uploaded presentation contains animations.

As a second step, simple animated slides could be expanded like this:
LibreOffice: https://github.com/monperrus/ExpandAnimations
Powerpoint: http://www.maxonthenet.altervista.org/ppsplit.php 

Thanks for the great work, though!

**Comment by pedrobmarin** [comment]
Closing this one to follow at https://github.com/bigbluebutton/bigbluebutton/issues/9734
