### ISSUE TITLE
Presentation thumbnails get out of sync when you "go back" a slide.

### ISSUE THREAD

**Issue by bigbluebutton-issue-import** [bigbluebutton/bigbluebutton#2503]
Originally reported on Google Code with ID 1751

```
What steps will reproduce the problem?
1. Record button
2. Upload
3. Next
4. Back
5. Next
6. Next
7. Back
8. Back
9. Next
10. Next
11. Draw Something
12. Wait for the processing

What is the expected output? What do you see instead?
It was expected that the thumbnails are in right order of slides. But instead of that,
the thumbnails got different of the slides (see attached files).


```

Reported by `eu.tdj.cc` on 2014-04-23 00:55:00

<hr>
- _Attachment: [raw.tar.gz](https://storage.googleapis.com/google-code-attachments/bigbluebutton/issue-1751/comment-0/raw.tar.gz)_
- _Attachment: [presentation.tar.gz](https://storage.googleapis.com/google-code-attachments/bigbluebutton/issue-1751/comment-0/presentation.tar.gz)_

**Comment by ffdixon** [comment]
Closing as this was an issue related to the Flash client (the project has moved to an HTML5 client).
