### ISSUE TITLE
Text is black not white

### ISSUE THREAD

**Issue by bigbluebutton-issue-import** [bigbluebutton/bigbluebutton#2510]
Originally reported on Google Code with ID 1758

```
What steps will reproduce the problem?

1.  Upload the attached .pptx to 0.9.0-dev

Compared with how it looks in PowerPoint, the text on slides 2 and 4 are black in BigBlueButton
(should be white).


```

Reported by `ffdixon` on 2014-05-21 14:37:59

<hr>
- _Attachment: [slide-test.ppt](https://storage.googleapis.com/google-code-attachments/bigbluebutton/issue-1758/comment-0/slide-test.ppt)_

**Comment by ffdixon** [comment]
Checked this with BigBlueButton 2.0 and the text in the slide is still black (not white).

**Comment by ffdixon** [comment]
Closing as this is an old issue.  We'll open a new issue if this problem arises in the latest version.
