### ISSUE TITLE
Add an "User X is typing" notification to chat

### ISSUE THREAD

**Issue by bigbluebutton-issue-import** [bigbluebutton/bigbluebutton#2511]
Originally reported on Google Code with ID 1759

```
Most chat applications now will display a notification when another user is in the process
of typing a message, such as a 

  "Fred Dixon is typing a message"



```

Reported by `ffdixon` on 2014-05-27 16:03:01

**Comment by GhaziTriki** [comment]
Clone of #1168

**Comment by ffdixon** [comment]
We could place a message above or below the chat dialog box.

![image](https://user-images.githubusercontent.com/290351/43719306-ba1a1444-9963-11e8-9927-e73ba6e6b061.png)
