### ISSUE TITLE
Icon "?" doesn't do anything

### ISSUE THREAD

**Issue by bigbluebutton-issue-import** [bigbluebutton/bigbluebutton#2531]
Originally reported on Google Code with ID 1780
```
The icon "?" on the Audio Echo Test doesn't do anything.


```

Reported by `dias.ferreira.alan` on 2014-08-13 14:17:58

<hr>
 * *Attachment: Screenshot from 2014-08-13 11:08:46.png<br>![Screenshot from 2014-08-13 11:08:46.png](https://storage.googleapis.com/google-code-attachments/bigbluebutton/issue-1780/comment-0/Screenshot from 2014-08-13 11:08:46.png)*

**Comment by ffdixon** [comment]
We removed the '?' from the Audio settings dialog.
