### ISSUE TITLE
Minimizing video stops working

### ISSUE THREAD

**Issue by bigbluebutton-issue-import** [bigbluebutton/bigbluebutton#2533]
Originally reported on Google Code with ID 1782
```
Following these steps:

start sharing the webcam, maximize the video windows and stop the sharing on the webcam
icon. Them minimize the video window and start sharing the webcam again. The window
becomes big and if you try to minimize it, it just stay big.
```

Reported by `dias.ferreira.alan` on 2014-08-13 15:49:18

<hr>
 * *Attachment: Screenshot from 2014-08-13 12:38:39.png<br>![Screenshot from 2014-08-13 12:38:39.png](https://storage.googleapis.com/google-code-attachments/bigbluebutton/issue-1782/comment-0/Screenshot from 2014-08-13 12:38:39.png)*

**Comment by ffdixon** [comment]
@GhaziTriki Is this issue reproducible in 1.0-beta?

**Comment by GhaziTriki** [comment]
This issue cannot be reproduced.

**Comment by ffdixon** [comment]
Thanks @GhaziTriki -- we'll close this issue and open again if it occurs.
