### ISSUE TITLE
Enhance Text tool to return and edit the text

### ISSUE THREAD

**Issue by bigbluebutton-issue-import** [bigbluebutton/bigbluebutton#2552]
Originally reported on Google Code with ID 1801

```
1) Using the text tool, type a message
2) Click outside the message
3) Again click on the message - This creates another textbox instead of allowing to
edit the prior message
(Wiziq whiteboard provides this functionality)
```

Reported by `shahforam14` on 2014-09-18 15:56:53

**Comment by TuringTux** [comment]
My university uses Big Blue Button and this feature requests seems still relevant to me. Even better would be if the size of the text field can be altered afterwards as well.

Is it possible to reopen this issue?

**Comment by TuringTux** [comment]
@ffdixon I don't know whether someone gets notified when I comment on a really old issue, and as you were the one who initially closed the issue I though I'd mention you just to increase my chance of getting input from the devs :smiley:
