### ISSUE TITLE
Uploading xls file on bbb 0.9 failing 

### ISSUE THREAD

**Issue by bigbluebutton-issue-import** [bigbluebutton/bigbluebutton#2560]
Originally reported on Google Code with ID 1809
```
When I tried uploading the xls file using demo.bigbluebutton.org it failed.

Here is the screen shot
http://screencast.com/t/SALFcgtj

Please have look into this issue.
```

Reported by `varunchopra18` on 2014-10-01 05:26:08

**Comment by ffdixon** [comment]
Closing as this bug is very old and there isn't any attached file to test against the newer build.
