### ISSUE TITLE
Blue Crosshairs in Screen Sharing

### ISSUE THREAD

**Issue by bigbluebutton-issue-import** [bigbluebutton/bigbluebutton#2562]
Originally reported on Google Code with ID 1811

```
Using screen sharing on Linux, if I share the entire screen, a blue board and crosshairs
appears in the window and is visible to all users.  This really distracts from whatever
is being shared on the screen.
```

Reported by `nick.e.couchman` on 2014-10-02 16:36:50

<hr>
- _Attachment: Screen Shot 2014-10-02 at 10.36.08 AM.png<br>![Screen Shot 2014-10-02 at 10.36.08 AM.png](https://storage.googleapis.com/google-code-attachments/bigbluebutton/issue-1811/comment-0/Screen Shot 2014-10-02 at 10.36.08 AM.png)_

**Comment by ffdixon** [comment]
Closing this issue as we are moving to an HTML5 client.
