### ISSUE TITLE
Some images missing from converted PDF

### ISSUE THREAD

**Issue by bigbluebutton-issue-import** [bigbluebutton/bigbluebutton#2622]
Originally reported on Google Code with ID 1874
```
1. Upload attached slides to BigBlueButton 0.9.0-beta.  
2. Goto page 6

On page 6 some of the images are missing (see cheese ring in upper right-hand corner).
 

Upload the same slides to BigBlueButton 0.81 and all the images are present.

In BigBlueButton 0.9.0-beta, we used swftools-0.9.2 (see http://www.swftools.org/download.html),
whereas in 0.81 we used swftools-0.9.1.

Issue reported in this thread

  https://groups.google.com/d/msg/bigbluebutton-dev/dq8crtSy-yg/0dsWni1eNxkJ



```

Reported by `ffdixon` on 2015-02-01 14:09:19

<hr>
 * *Attachment: [NÅR VI TENKER NORSK - MAT.pdf](https://storage.googleapis.com/google-code-attachments/bigbluebutton/issue-1874/comment-0/NÅR VI TENKER NORSK - MAT.pdf)*

**Comment by ffdixon** [comment]
Fixed in 1.0-beta.  You can try uploading the given presentation to 

  http://demo.bigbluebutton.org/

and see that it now displays all the images.
