### ISSUE TITLE
WebRTC issue: Error 1002: Could not make a WebSocket connection

### ISSUE THREAD

**Issue by bigbluebutton-issue-import** [bigbluebutton/bigbluebutton#2628]
Originally reported on Google Code with ID 1880

```
hi there, have any of you have the same problem with me, 
i am using BBB 0.9.0 beta with ubuntu 14.04 64bit and when i started to launch the
web conference suddenly there is an error WebRTC issue: Error 1002: Could not make
a WebSocket connection. it suggested me to use flash player but i cannot make it too..
the point is i cant reached my voice through my microphone.
```

Reported by `hardi.zip` on 2015-02-15 06:28:34

**Comment by GopalSharma** [comment]
I'm writing this to help those who still not figred out hot to resolve this issue.
You need to perform one extra steps when server is behind NAT(network address translation).
You need to configre Kurento  to use stun server, which you can get from the link [kurento documentation](https://kurento.readthedocs.io/en/stable/doc/admin_guide.html#installation),
you need to edit `/etc/kurento/modules/kurento/WebRtcEndpoint.conf.ini` and uncomment and assign values for `stunServerAddress` and `stunServerPort`.

For example, to use the STUN server at `64.233.177.127` with port `19302`, edit the lines with stunServerAddress and stunServerPort as follows:

`stunServerAddress`=**64.233.177.127**
`stunServerPort`=**19302** 

 ### Next, this is very important
edit `/opt/freeswitch/conf/sip_profiles/external.xml `and ensure the value for wss-binding uses the **external IP address**

`<param name="wss-binding"  value="EXTERNAL_IP_ADDRESS:7443"/>`
At this point, restart your BigBlueButton server with` bbb-conf --restart`, then try connecting to the WebRTC media again.

If the issue stile not resolved then edit the following files and substitute EXTERNAL_IP_ADDRESS for the external IP address (**not the external hostname**).

Edit `/opt/freeswitch/conf/vars.xml`, and 
change `<X-PRE-PROCESS cmd="set" data="external_rtp_ip=stun:stun.freeswitch.org"/>`
To `<X-PRE-PROCESS cmd="set" data="external_rtp_ip=EXTERNAL_IP_ADDRESS"/>`

Change `<X-PRE-PROCESS cmd="set" data="external_sip_ip=stun:stun.freeswitch.org"/>`
To `<X-PRE-PROCESS cmd="set" data="external_sip_ip=EXTERNAL_IP_ADDRESS"/>`

Next, edit `/opt/freeswitch/conf/sip_profiles/external.xml` and change
    `<param name="ext-rtp-ip" value="$${local_ip_v4}"/>`
    `<param name="ext-sip-ip" value="$${local_ip_v4}"/>`
to
    `<param name="ext-rtp-ip" value="$${external_rtp_ip}"/>`
    `<param name="ext-sip-ip" value="$${external_sip_ip}"/>`

Next, edit `/usr/share/red5/webapps/sip/WEB-INF/bigbluebutton-sip.properties`, and make sure the values of `bbb.sip.app.ip` and `freeswitch.ip` have the internal IP address.

```
bbb.sip.app.ip=<internal_ip>
bbb.sip.app.port=5070

freeswitch.ip=<internal_ip>
freeswitch.port=5060
```
Edit `/etc/bigbluebutton/nginx/sip.nginx `to connect to the external IP address.

If you have **configured SSL,** use port **7443**:

```
location /ws {
        proxy_pass https://EXTERNAL_IP_ADDRESS:7443;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_read_timeout 6h;
        proxy_send_timeout 6h;
        client_body_timeout 6h;
        send_timeout 6h;
}
```
If enableListenOnly is set to true in `/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml`, as in

```
$ grep enableListenOnly /usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml
    enableListenOnly: true
```
edit` /usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml` change the value to `ip` to match the **external IP address** of the server, and the value of `sip_ip` to match the **internal IP address** of the server (where FreeSWITCH is listening to port 5066). For example, if the servers external IP address is `203.0.113.1` and the internal IP address is` 172.30.1.145` then edit default.yml and change the values for ip and sip_ip as follows:

```
freeswitch:
    ip: 203.0.113.1
    sip_ip: 172.30.1.145
    port: 5066
```
After making the above changes, restart BigBlueButton.

`$ bbb-conf --restart`

**Comment by gayan4u** [comment]
Even with all the above settings, Im still getting the WebRTC 1004 failurer

**Comment by matiasilva** [comment]
Hi, thanks for posting here. Please forward your topic to https://groups.google.com/forum/#!forum/bigbluebutton-setup if you continue to have issues.

**Comment by bipintulo** [comment]
video tuitorial of setting STUN Server  for BBB

**Comment by smithagustin** [comment]
good day! im from the Philippines. Im done with the setting up of bbb server. the only problem Im encountering now is the error 1002 websocket connection problem. with regards to the camera sharing, i can successfully share the camera but the other person outside our network is unable to see me. i already conducted a test on https://test.bigbluebutton.org where I can successfully access camera and microphone without any issue. kindly help me on this. thank you!

**Comment by matiasilva** [comment]
@smithagustin please follow the instructions at https://docs.bigbluebutton.org/2.2/getting-help.html to get help. It is bad practice to revive old issues, this one is 5 years old!

**Comment by smithagustin** [comment]
Sorry if I revived an old post. I actually tried everything and followed
every instructions from docs.bigbluebutton.org to no avail. I am just here
because I am looking for assistance with regards to the error I am getting.

Thank you and God bless,

**Comment by matiasilva** [comment]
@smithagustin no worries, but that link contains this excerpt:

> If you find that the problem still persists or you have any other questions, you can ask other users in the mailing lists. If you suspect that your issue is a bug, you can post on our issue tracker, otherwise refrain from using the GitHub issue tracker for general queries.

**Comment by smithagustin** [comment]
Which mailing list are you referring to?

**Comment by matiasilva** [comment]
The ones linked in the link I originally gave you.

**Comment by divinityindia** [comment]
couldnot make a websocket connection (error 1002) bigbluebutton  i have exactly do as above said by GopalSharma but still the same problem occurring when start the session it give error of web socket connection.. please guide I have migrate ec2 to other account.

**Comment by ibrahim-quraishi** [comment]
Hi All I followed all this steps and still getting 1002 error. I managed to get this working couple of time but the cpu was only 2 so I decided to delete and start again. ever since I am struggling to get this running all the ports are open on Azure

**Comment by evaristorivi** [comment]
> Escribo esto para ayudar a aquellos que aún no se han dado cuenta de ello a resolver este problema.
> Debe realizar un paso adicional cuando el servidor está detrás de NAT (traducción de direcciones de red).
> Debe configurar Kurento para usar el servidor de aturdimiento, que puede obtener del enlace de la [documentación de kurento](https://kurento.readthedocs.io/en/stable/doc/admin_guide.html#installation) ,
> debe editar `/etc/kurento/modules/kurento/WebRtcEndpoint.conf.ini`y descomentar y asignar valores para `stunServerAddress`y `stunServerPort`.
> 
> Por ejemplo, para usar el servidor STUN en `64.233.177.127`con puerto `19302`, edite las líneas con stunServerAddress y stunServerPort de la siguiente manera:
> 
> `stunServerAddress`= **64.233.177.127**
> `stunServerPort` = **19302**
> 
> ### A continuación, esto es muy importante
> edite `/opt/freeswitch/conf/sip_profiles/external.xml `y asegúrese de que el valor para el enlace wss use la **dirección IP externa**
> 
> `<param name="wss-binding" value="EXTERNAL_IP_ADDRESS:7443"/>`
> En este punto, reinicie su servidor BigBlueButton con ` bbb-conf --restart`, luego intente conectarse a los medios WebRTC nuevamente.
> 
> Si el problema no se resuelve, edite los siguientes archivos y sustituya EXTERNAL_IP_ADDRESS por la dirección IP externa ( **no el nombre de host externo** ).
> 
> Editar `/opt/freeswitch/conf/vars.xml`y
> cambiar `<X-PRE-PROCESS cmd="set" data="external_rtp_ip=stun:stun.freeswitch.org"/>`
> a`<X-PRE-PROCESS cmd="set" data="external_rtp_ip=EXTERNAL_IP_ADDRESS"/>`
> 
> Cambiar `<X-PRE-PROCESS cmd="set" data="external_sip_ip=stun:stun.freeswitch.org"/>`
> a`<X-PRE-PROCESS cmd="set" data="external_sip_ip=EXTERNAL_IP_ADDRESS"/>`
> 
> A continuación, edite `/opt/freeswitch/conf/sip_profiles/external.xml`y cambie
> `<param name="ext-rtp-ip" value="$${local_ip_v4}"/>`
> `<param name="ext-sip-ip" value="$${local_ip_v4}"/>`
> a
> `<param name="ext-rtp-ip" value="$${external_rtp_ip}"/>`
> `<param name="ext-sip-ip" value="$${external_sip_ip}"/>`
> 
> A continuación, edite `/usr/share/red5/webapps/sip/WEB-INF/bigbluebutton-sip.properties`y asegúrese de que los valores de `bbb.sip.app.ip`y `freeswitch.ip`tengan la dirección IP interna.
> 
> ```
> bbb.sip.app.ip=<internal_ip>
> bbb.sip.app.port=5070
> 
> freeswitch.ip=<internal_ip>
> freeswitch.port=5060
> ```
> 
> Edite `/etc/bigbluebutton/nginx/sip.nginx `para conectarse a la dirección IP externa.
> 
> Si ha **configurado SSL,** use el puerto **7443** :
> 
> ```
> location /ws {
>         proxy_pass https://EXTERNAL_IP_ADDRESS:7443;
>         proxy_http_version 1.1;
>         proxy_set_header Upgrade $http_upgrade;
>         proxy_set_header Connection "Upgrade";
>         proxy_read_timeout 6h;
>         proxy_send_timeout 6h;
>         client_body_timeout 6h;
>         send_timeout 6h;
> }
> ```
> 
> Si enableListenOnly se establece en true en `/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml`, como en
> 
> ```
> $ grep enableListenOnly /usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml
>     enableListenOnly: true
> ```
> 
> editar ` /usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml`cambie el valor a `ip`para que coincida con la **dirección IP externa** del servidor, y el valor de `sip_ip`para que coincida con la **dirección IP interna** del servidor (donde FreeSWITCH está escuchando el puerto 5066). Por ejemplo, si la dirección IP externa del servidor es `203.0.113.1`y la dirección IP interna es ` 172.30.1.145`, edite default.yml y cambie los valores de ip y sip_ip de la siguiente manera:
> 
> ```
> freeswitch:
>     ip: 203.0.113.1
>     sip_ip: 172.30.1.145
>     port: 5066
> ```
> 
> Después de realizar los cambios anteriores, reinicie BigBlueButton.
> 
> `$ bbb-conf --restart`


Thank you very much, I did it this way:

sed -i s/OLD_EXTERNAL_IP_ADDRESS/NEW_EXTERNAL_IP_ADDRESS/g /opt/freeswitch/conf/sip_profiles/external.xml

sed -i s/OLD_EXTERNAL_IP_ADDRESS/NEW_EXTERNAL_IP_ADDRESS/g /opt/freeswitch/conf/vars.xml

sed -i s/OLD_EXTERNAL_IP_ADDRESS/NEW_EXTERNAL_IP_ADDRESS/g /opt/freeswitch/conf/sip_profiles/external.xml

sed -i s/OLD_EXTERNAL_IP_ADDRESS/NEW_EXTERNAL_IP_ADDRESS/g /usr/share/red5/webapps/sip/WEB-INF/bigbluebutton-sip.properties

sed -i s/OLD_EXTERNAL_IP_ADDRESS/NEW_EXTERNAL_IP_ADDRESS/g /etc/bigbluebutton/nginx/sip.nginx

sed -i s/OLD_EXTERNAL_IP_ADDRESS/NEW_EXTERNAL_IP_ADDRESS/g /usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml

**Comment by erselbey** [comment]
> I'm writing this to help those who still not figred out hot to resolve this issue.
> You need to perform one extra steps when server is behind NAT(network address translation).
> You need to configre Kurento to use stun server, which you can get from the link [kurento documentation](https://kurento.readthedocs.io/en/stable/doc/admin_guide.html#installation),
> you need to edit `/etc/kurento/modules/kurento/WebRtcEndpoint.conf.ini` and uncomment and assign values for `stunServerAddress` and `stunServerPort`.
> 
> For example, to use the STUN server at `64.233.177.127` with port `19302`, edit the lines with stunServerAddress and stunServerPort as follows:
> 
> `stunServerAddress`=**64.233.177.127**
> `stunServerPort`=**19302**
> 
> ### Next, this is very important
> edit `/opt/freeswitch/conf/sip_profiles/external.xml `and ensure the value for wss-binding uses the **external IP address**
> 
> `<param name="wss-binding" value="EXTERNAL_IP_ADDRESS:7443"/>`
> At this point, restart your BigBlueButton server with` bbb-conf --restart`, then try connecting to the WebRTC media again.
> 
> If the issue stile not resolved then edit the following files and substitute EXTERNAL_IP_ADDRESS for the external IP address (**not the external hostname**).
> 
> Edit `/opt/freeswitch/conf/vars.xml`, and
> change `<X-PRE-PROCESS cmd="set" data="external_rtp_ip=stun:stun.freeswitch.org"/>`
> To `<X-PRE-PROCESS cmd="set" data="external_rtp_ip=EXTERNAL_IP_ADDRESS"/>`
> 
> Change `<X-PRE-PROCESS cmd="set" data="external_sip_ip=stun:stun.freeswitch.org"/>`
> To `<X-PRE-PROCESS cmd="set" data="external_sip_ip=EXTERNAL_IP_ADDRESS"/>`
> 
> Next, edit `/opt/freeswitch/conf/sip_profiles/external.xml` and change
> `<param name="ext-rtp-ip" value="$${local_ip_v4}"/>`
> `<param name="ext-sip-ip" value="$${local_ip_v4}"/>`
> to
> `<param name="ext-rtp-ip" value="$${external_rtp_ip}"/>`
> `<param name="ext-sip-ip" value="$${external_sip_ip}"/>`
> 
> Next, edit `/usr/share/red5/webapps/sip/WEB-INF/bigbluebutton-sip.properties`, and make sure the values of `bbb.sip.app.ip` and `freeswitch.ip` have the internal IP address.
> 
> ```
> bbb.sip.app.ip=<internal_ip>
> bbb.sip.app.port=5070
> 
> freeswitch.ip=<internal_ip>
> freeswitch.port=5060
> ```
> 
> Edit `/etc/bigbluebutton/nginx/sip.nginx `to connect to the external IP address.
> 
> If you have **configured SSL,** use port **7443**:
> 
> ```
> location /ws {
>         proxy_pass https://EXTERNAL_IP_ADDRESS:7443;
>         proxy_http_version 1.1;
>         proxy_set_header Upgrade $http_upgrade;
>         proxy_set_header Connection "Upgrade";
>         proxy_read_timeout 6h;
>         proxy_send_timeout 6h;
>         client_body_timeout 6h;
>         send_timeout 6h;
> }
> ```
> 
> If enableListenOnly is set to true in `/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml`, as in
> 
> ```
> $ grep enableListenOnly /usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml
>     enableListenOnly: true
> ```
> 
> edit` /usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml` change the value to `ip` to match the **external IP address** of the server, and the value of `sip_ip` to match the **internal IP address** of the server (where FreeSWITCH is listening to port 5066). For example, if the servers external IP address is `203.0.113.1` and the internal IP address is` 172.30.1.145` then edit default.yml and change the values for ip and sip_ip as follows:
> 
> ```
> freeswitch:
>     ip: 203.0.113.1
>     sip_ip: 172.30.1.145
>     port: 5066
> ```
> 
> After making the above changes, restart BigBlueButton.
> 
> `$ bbb-conf --restart`

helped me solve my problem.

**Comment by andrekutianski** [comment]
I have this problem only when configuring IPv6 like described on https://docs.bigbluebutton.org/2.2/troubleshooting.html#configure-bigbluebuttonfreeswitch-to-support-ipv6

**Comment by FihlaTV** [comment]
On my side I had to configure  /etc/bigbluebutton/nginx/sip.nginx and set the:
proxy_pass to https instead of http

**Comment by john1726** [comment]
Please note that I followed the posts above but didn't get the issue resolved until I ran the following command:

`$ wget -qO- https://ubuntu.bigbluebutton.org/bbb-install.sh | bash -s -- -v xenial-22 -s myserver.com -c turn.tuberedu.org:1004a200000000004cb3f2d6f000d85d -e johndoe@myserver.com -d -g | tee bbb-install.log`
