### ISSUE TITLE
Distorted audio in listen only mode with Firefox on Debian

### ISSUE THREAD

**Issue by bigbluebutton-issue-import** [bigbluebutton/bigbluebutton#2630]
Originally reported on Google Code with ID 1882
```
Reported in 

  https://groups.google.com/d/msg/bigbluebutton-dev/ZTn-YWUHNVA/nLCtmRba3tIJ


```

Reported by `ffdixon` on 2015-02-15 22:11:43

**Comment by ffdixon** [comment]
This bug is related to the older version of Flash 11.x on Debian.  Recommend using Chrome on Debian as it has the latest version of Flash.

Closing this bug.
