### ISSUE TITLE
If try to change microphone when entering in BBB, it enters in a loop

### ISSUE THREAD

**Issue by bigbluebutton-issue-import** [bigbluebutton/bigbluebutton#2644]
Originally reported on Google Code with ID 1896
```
When you enter in BBB, you select No when you receive the question: have you heard your
voice? Then you select a different microphone and push Next. It never finishes. You
have to reload the page.
```

Reported by `smoral@adhoclearning.com` on 2015-03-06 14:44:53

**Comment by ffdixon** [comment]
We're going to close this issue.  If anyone can reproduce against a standard install of the BigBlueButton server, we'll re-open.
