### ISSUE TITLE
Flash not detected if IE Enhanced Protected Mode is Enable

### ISSUE THREAD

**Issue by bigbluebutton-issue-import** [bigbluebutton/bigbluebutton#2669]
Originally reported on Google Code with ID 1921

```
Client : Windows 8.1 with IE 11 (latest patches)
Configuration : IE Enhanced Protected Mode and 64-bit process enabled

Flash player is detected at http://www.adobe.com/software/flash/about/
However, Flash player is not detected when accessing http://demo.bigbluebutton.org

```

Reported by `Mike.Lim.CE` on 2015-04-07 00:40:34

<hr>
- _Attachment: BB-IE.png<br>![BB-IE.png](https://storage.googleapis.com/google-code-attachments/bigbluebutton/issue-1921/comment-0/BB-IE.png)_

**Comment by ffdixon** [comment]
Closing this issue as we are moving to an HTML5 client.
