### ISSUE TITLE
Move BBB Red5 jars from google code

### ISSUE THREAD

**Issue by bigbluebutton-issue-import** [bigbluebutton/bigbluebutton#2673]
Originally reported on Google Code with ID 1925

```
Since we build our own Red5 server, we have our own red5.jar stored in https://code.google.com/p/blindside/source/browse/#svn%2Frepository

We need to move it some place and update all build.gradle so as to not break dependencies.

```

Reported by `ritzalam` on 2015-04-10 15:00:17

**Comment by GhaziTriki** [comment]
@ritzalam Google Code service has been shutdown, are the jars available in a new place?

**Comment by ffdixon** [comment]
@ritzalam, as we are now building BigBlueButton 1.1-beta, can you confirm (and close this issue) that the jar files now removed from Google Code
