### ISSUE TITLE
typing sound

### ISSUE THREAD

**Issue by bigbluebutton-issue-import** [bigbluebutton/bigbluebutton#2676]
Originally reported on Google Code with ID 1928
```
How do I disable typing sound (ting ting)in chat window.
```

Reported by `afra_bader@yahoo.com` on 2015-04-13 19:33:59

**Comment by ffdixon** [comment]
The new chat notifications are present when the BigBlueButton client detects the operating system requests is requesting the BigBlueButton client to enable accessibility features.  However, it's not clear to users that they have made this request. 

We added a check box in the 'Options' tab to turn off the notifications if they are active.

  https://github.com/bigbluebutton/bigbluebutton/pull/2748
