### ISSUE TITLE
Add feedback to the user that a recording is unpublished when trying to view it

### ISSUE THREAD

**Issue by bigbluebutton-issue-import** [bigbluebutton/bigbluebutton#2677]
Originally reported on Google Code with ID 1929

```
What steps will reproduce the problem?
1.  Create a recording
2.  View the recording
3.  Unpublish the recording
4.  View the recording again

To the user, the recording looks like it's trying to load (the loading indicator will
keep spinning).  

Remove the loading indicator if the recording is no published.
```

Reported by `ffdixon` on 2015-04-14 11:36:10

**Comment by rohitkk684** [comment]
Thanks for post this helpful post - Please visit for More information about -
<a href="http://www.expert5th.in/packers-and-movers-mumbai/" title="Packers and Movers Mumbai">Packers and Movers in Mumbai</a>
<a href="http://www.expert5th.in/packers-and-movers-pune/" title="Packers and Movers in Pune">Packers and Movers in Pune</a>
<a href="http://www.expert5th.in/packers-and-movers-hyderabad/" title="Packers and Movers Hyderabad">Packers and Movers in Hyderabad</a>

**Comment by rohitkk684** [comment]
If you are looking Best Packers and Movers so Visit at :
<a href="http://www.expert5th.in/packers-and-movers-bangalore/" title="Packers and Movers Bangalore">Packers and Movers in Bangalore</a>
<a href="http://www.expert5th.in/packers-and-movers-chennai/" title="Packers and Movers Chennai">Packers and Movers in Chennai</a>
<a href="http://www.expert5th.in/packers-and-movers-delhi/" title="Packers and Movers Delhi">Packers and Movers in Delhi</a>
<a href="http://www.expert5th.in/packers-and-movers-gurgaon/" title="Packers and Movers Gurgaon">Packers and Movers in Gurgaon</a>

**Comment by rohitkk684** [comment]
Thanks for post this helpful post - Please visit for More information about -
<a href="http://www.expert5th.in/packers-and-movers-noida/" title="Packers and Movers in Noida">Packers and Movers in Noida</a>
<a href="http://www.expert5th.in/packers-and-movers-navimumbai/" title="Packers and Movers in Navi Mumbai">Packers and Movers in Navi Mumbai</a>
<a href="http://www.expert5th.in/packers-and-movers-ghaziabad/" title="Packers and Movers in Ghaziabad">Packers and Movers in Ghaziabad</a>
<a href="http://www.expert5th.in/packers-and-movers-faridabad/" title="Packers and Movers in Faridabad">Packers and Movers in Faridabad</a>
<a href="http://www.expert5th.in/packers-and-movers-thane/" title="Packers and Movers in Thane">Packers and Movers in Thane</a>

**Comment by surajbaba962** [comment]
What steps will reproduce the problem?
1.  Create a recording
2.  View the recording
3.  Unpublish the recording
4.  View the recording again

To the user, the recording looks like it's trying to load (the loading indicator will
keep spinning).  

Remove the loading indicator if the recording is no published.
http://www.movers5th.in/packers-and-movers-hyderabad/
http://www.movers5th.in/packers-and-movers-bangalore/
http://www.movers5th.in/packers-and-movers-pune/
http://www.movers5th.in/packers-and-movers-mumbai/

**Comment by surajbaba962** [comment]
[url=http://www.moveby5th.in/packers-and-movers-hyderabad.html]Packers and Movers Hyderabad[/url]

**Comment by pedrobmarin** [comment]
This problem should not occur with the new playback.
