### ISSUE TITLE
Bigbluebutton Auditing

### ISSUE THREAD

**Issue by bigbluebutton-issue-import** [bigbluebutton/bigbluebutton#2679]
Originally reported on Google Code with ID 1931

```
Currently we have setup bigbluebutton 0.9. now auditing of our bigbluebutton server
is going on. we have reported with some high risk and some low risk Vulnerability.


plz suggest of solve it so that we make it live on our production server.
plz find the attached file for the issue. 
```

Reported by `rupes4ur` on 2015-04-20 06:08:27

<hr>
- _Attachment: [audit.zip](https://storage.googleapis.com/google-code-attachments/bigbluebutton/issue-1931/comment-0/audit.zip)_

**Comment by ffdixon** [comment]
Closing as this is an old issue.  We'll open a new issue if this problem arises in the latest version.
