### ISSUE TITLE
Opera and webRTC

### ISSUE THREAD

**Issue by bigbluebutton-issue-import** [bigbluebutton/bigbluebutton#2688]
Originally reported on Google Code with ID 1940
```
We've tested FireFox and Chrome with the latest version of BigBlueButton (0.9.0+) for
support with webRTC, but not Opera.

It might be possible to get Opera to work, but would need to do further testing.


```

Reported by `ffdixon` on 2015-05-12 05:30:41

**Comment by GhaziTriki** [comment]
The latest tests on Opera using WebRTC worked well.

**Comment by ffdixon** [comment]
We didn't add any code to work with Opera; rather, I think this is more that Opera has built their browser around the Chrome engine and is benefit from the support for WebRTC.

Still, it's great to have another browser that works with BigBlueButton via WebRTC!
