### ISSUE TITLE
Importing some pdf files take more times than usual

### ISSUE THREAD

**Issue by bigbluebutton-issue-import** [bigbluebutton/bigbluebutton#2703]
Originally reported on Google Code with ID 1955
```
I don't know why, but adding some pdf files takes many long time (30+ min) to converted.
I attach mentioned pdf file that takes long time to convert. please check.
```

Reported by `idol.mesut` on 2015-06-23 06:11:55

<hr>
 * *Attachment: [PRS PERF SMPLE.pdf](https://storage.googleapis.com/google-code-attachments/bigbluebutton/issue-1955/comment-0/PRS PERF SMPLE.pdf)*

**Comment by ffdixon** [comment]
Fixed in https://github.com/bigbluebutton/bigbluebutton/commit/febc7ca9ead9e82b6215060ef8b428b08c4fa3e6
