### ISSUE TITLE
Propagate fix for issue 1953 from 0.9.0-release branch

### ISSUE THREAD

**Issue by bigbluebutton-issue-import** [bigbluebutton/bigbluebutton#2705]
Originally reported on Google Code with ID 1957
```
Need to prop fix for 
https://code.google.com/p/bigbluebutton/issues/detail?id=1953

from v0.9.0-release branch to master.
```

Reported by `ritzalam` on 2015-06-30 17:36:17

**Comment by ritzalam** [comment]
Fixed in https://github.com/bigbluebutton/bigbluebutton/commit/27c8b521fbd233f37ba77e9e0709745674b2457b
