### ISSUE TITLE
Broadcast Module

### ISSUE THREAD

**Issue by bigbluebutton-issue-import** [bigbluebutton/bigbluebutton#2706]
Originally reported on Google Code with ID 1958

```
I have succesfully installed bigbluebutton development environment and 3 modules are
disabled in config.xml,
1. Polling
2. Notes
3. Broadcast

I have enabled all the above modules and tested but i am only able to see polling module.
I have no idea about Notes and Broadcast module. Can anyone explain about notes and
broadcast module in bigbluebutton
```

Reported by `manojr.kalpana` on 2015-07-01 10:29:37

**Comment by ffdixon** [comment]
We're currently working on finishing BigBlueButton 1.1-beta.  At this point, we're not planning on updating the broadcast module as part of 1.1.  As before, if anyone is interested in helping to accelerate a feature, see http://docs.bigbluebutton.org/support/faq.html#when-will-feature-x-be-implemented.

**Comment by ffdixon** [comment]
Closing as this was an issue related to the Flash client (the project has moved to an HTML5 client).
