### ISSUE TITLE
Unable to type Chinese characters into the whiteboard text box

### ISSUE THREAD

**Issue by bigbluebutton-issue-import** [bigbluebutton/bigbluebutton#2708]
Originally reported on Google Code with ID 1960

```
What steps will reproduce the problem?
1.
2.
3.

What is the expected output? What do you see instead?


Please use labels and text to provide additional information.

```

Reported by `ffdixon` on 2015-07-04 17:41:31

**Comment by jibon57** [comment]
Is there any update? Still can't write in version 1.0 :(

**Comment by ffdixon** [comment]
We're not planning on including this in BigBlueButton 1.0.  Our goal right now is to finish this release (not add new features).  We'll be revisiting this issue in a future version.

For more information on how we prioritize between releases, see this [FAQ](http://docs.bigbluebutton.org/support/faq.html#when-will-feature-x-be-implemented) entry.

**Comment by ffdixon** [comment]
We just tested this an it looks to work in BigBlueButton 2.0-beta.

![image](https://user-images.githubusercontent.com/290351/33915875-d7364368-df73-11e7-8f0a-e723e6d80b09.png)
