### ISSUE TITLE
Locked layout does not apply to new users

### ISSUE THREAD

**Issue by bigbluebutton-issue-import** [bigbluebutton/bigbluebutton#2710]
Originally reported on Google Code with ID 1962
```
What steps will reproduce the problem?
1.  Login as a moderator
2.  Change the layout (to another layout besides default)
3.  Push down the current layout
4.  Lock the layout (viewers can not change)

When a new viewer joins, they have the default layout and are not able to change. 
They should have the last layout just before the lock.


```

Reported by `ffdixon` on 2015-07-08 01:17:53

**Comment by tdj-br** [comment]
Why was it removed from 1.0 milestone? We still developing this.

**Comment by tdj-br** [comment]
I'm currently testing the fix with current code base.

**Comment by tdj-br** [comment]
@capilkey It's fixed now. Can you verify again, please?

**Comment by ffdixon** [comment]
In testing we're finding the last pushed/locked layout is getting applied to moderators.  It should only apply to viewers.

**Comment by tdj-br** [comment]
Just reproduced that, I'm going to fix it.

**Comment by tdj-br** [comment]
Fixed and merged.

**Comment by ffdixon** [comment]
Confirmed -- thanks Tiago!
