### ISSUE TITLE
Give a moderator the ability to escalate the privileges of another viewer to moderator

### ISSUE THREAD

**Issue by bigbluebutton-issue-import** [bigbluebutton/bigbluebutton#2711]
Originally reported on Google Code with ID 1963

```
See discussion in bigbluebutton-dev

  https://groups.google.com/d/msg/bigbluebutton-dev/e-EvnfqwTZo/OzmIORADAwgJ
```

Reported by `ffdixon` on 2015-07-09 15:08:29

**Comment by Tsaw** [comment]
207TECH

**Comment by ffdixon** [comment]
This capability is now in BigBlueButton 2.0-beta

![promote](https://user-images.githubusercontent.com/290351/41502582-375838e2-718b-11e8-89b7-af0ec39010d8.gif)
