### ISSUE TITLE
Opera being detected as Chrome

### ISSUE THREAD

**Issue by GhaziTriki** [bigbluebutton/bigbluebutton#2728]
Hi,

Actually the determineBrowser() JavaScript function; when executed on an Opera browser; returns "Chrome" instead of "Opera". The User Agent from Opera 15 has been updated like described in the following link : https://dev.opera.com/blog/opera-user-agent-strings-opera-15-and-beyond/

**Comment by kepstin** [comment]
Some things we need to do for Opera support

* Check if Opera WebRTC is available, and if it's compatible with Chrome
* Check the WebRTC permission prompts are similar to Chrome, or if we should make a new set of help images for Opera

**Comment by GhaziTriki** [comment]
Here is the link for checking WebRTC support by browsers http://iswebrtcreadyyet.com/

**Comment by GhaziTriki** [comment]
It causes another issue, desktop sharing cannot launched and we see this error:

![image](https://cloud.githubusercontent.com/assets/4991088/13685884/3219b3ec-e713-11e5-8483-4b655d2dfbc9.png)

**Comment by ffdixon** [comment]
Just checked Opera 37 and BigBlueButton still detects it as Chrome.  While we focus on FireFox and Chrome, it would be good to support Opera in a future release.

**Comment by GhaziTriki** [comment]
Opera has become very restrictive with Flash Player. Enabling Flash and trusting a website is needed to make the the Flash client. It don't think it makes a sense supporting Opera officially for the Flash client. @ffdixon & @kepstin what do you think?

**Comment by ffdixon** [comment]
Closing this issue as it's related to the Flash client (we're moving to a pure HTML5 client in the project).
