### ISSUE TITLE
"porttest" cannot be configured to use rtmps/rtmpts

### ISSUE THREAD

**Issue by kepstin** [bigbluebutton/bigbluebutton#2750]
Even if you configure all of the BigBlueButton modules to use 'rtmps' URLs, the porttest client code still checks rtmp on port 1935 and rtmpt on port 80.

This can give false results - even if the porttest on port 1935 doesn't work, the actual BigBlueButton modules using rtmps might be able to connect on port 443.

We probably want to support 2 settings:
- "rtmp" mode tries rtmp on port 1935 and rtmpt through http on port 80
- "rtmps" mode tries rtmps on port 443 and rtmpt through https on port 443

**Comment by kepstin** [comment]
Upon inspection of the actionscript docs, it looks like the two cases should be:

* "rtmp": set `proxyType="none"` and try with `rtmp://hostname:1935` then `rtmpt://hostname:80`
* "rtmps": set `proxyType="best"` and try with `rtmps://hostname:443`

**Comment by ffdixon** [comment]
Closing this issue as we are moving to an HTML5 client.
