### ISSUE TITLE
Setting lockLayoutForLockedUsers="true"  does not prevent users from changing their layout

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#2768]
If you set

`lockLayoutForLockedUsers="true"`

in `config.xml` and then restart BigBlueButton, a viewer can still change their layout.  Reported in

  https://groups.google.com/d/msg/bigbluebutton-setup/510RlNTR2fY/zqqskwxgCAAJ

**Comment by ritzalam** [comment]
@capilkey Can you please review and merge?
