### ISSUE TITLE
Message for uploading large number of pages is misleading

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#2775]
When a user uploads a PDF document with 200+ pages, or larger than ```maxNumPages``` defined in ```/var/lib/tomcat7/webapps/bigbluebutton/WEB-INF/classes/bigbluebutton.properties```

```
#----------------------------------------------------
# Maximum number of pages allowed for an uploaded presentation (default 100).
maxNumPages=100
```

The message they receive is misleading (see attached image).

![image](https://cloud.githubusercontent.com/assets/290351/9796542/b920bbd0-57c4-11e5-890e-5799e6c27e4f.png)

**Comment by GhaziTriki** [comment]
After some testing and uploading a PDF file that exceeds the maxNumPages, no response is returned from the server and I see that the document is still being converted.

**Comment by ffdixon** [comment]
[lots of pages.pdf](https://github.com/bigbluebutton/bigbluebutton/files/6408/lots.of.pages.pdf)
