### ISSUE TITLE
Shape undo in .90 and 1.0dev

### ISSUE THREAD

**Issue by hostbbb** [bigbluebutton/bigbluebutton#2776]
http://demo.bigbluebutton.org/playback/presentation/0.9.0/playback.html?meetingId=3634be4771f87bb7834acdb30354a4c490f7c1cb-1441905354062

I noticed in 0.9.1 and replicated on demo.bigbluebutton.org

i added 6 shapes, removed 2, then added back new ones.  only the first undo shows in recordings. So the recording shows both shapes in same location.

**Comment by ffdixon** [comment]
Fixed in BigBlueButton 1.1-beta.  Here is a recording with six shapes, the last two are removed via undo, and then two more are added.

![undo-in-recoding](https://cloud.githubusercontent.com/assets/290351/21967194/3df86af0-db50-11e6-9ffc-972e51aed115.gif)
