### ISSUE TITLE
CTRL+S in chat window loses the focus from the message text input

### ISSUE THREAD

**Issue by GhaziTriki** [bigbluebutton/bigbluebutton#2789]
When triggering the keyboard send message shortcut using "CTRL+S" the focus to the message text input is lost.
The expected behaviour is keeping the focus to the message text input.

**Comment by ffdixon** [comment]
Chad, do we need to fix this as part of updates to the accessibility for 1.0?

**Comment by capilkey** [comment]
Fixed
