### ISSUE TITLE
Add ability to disable h.264 encoding for VideoconfModule module

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#2795]
The new VideoconfModule updates the display of webcams (no more boarders) and replaces the older VideodockModule.

Add parameter

  enableH264="<boolean>"

Where

 <boolean> = true|false

to enable/disable h.264 encoding.  The default is true.  Requested in this thread in BigBlueButton-dev

  https://groups.google.com/d/msg/bigbluebutton-dev/ylgka-KR0fs/cz5Qwz9jAwAJ

**Comment by capilkey** [comment]
The "enableH264" property was moved to profiles.xml with the rest of the video settings. Going to close this issue.

https://github.com/bigbluebutton/bigbluebutton/blob/master/bigbluebutton-client/resources/prod/profiles.xml#L14
