### ISSUE TITLE
Reconnect causes two cameras to show video dock

### ISSUE THREAD

**Issue by hostbbb** [bigbluebutton/bigbluebutton#2808]
demo.bigbluebutton.org version 359

Was broadcasting video test from from 1 computer watching on another.

and after some period the other pc client saw 2
streams in videodock. they are identical (assuming this is reconnect).

New users entering after only see one cam.

![reconnect2cams](https://cloud.githubusercontent.com/assets/519542/10107420/ec05135a-6388-11e5-86d3-b3c342efea58.PNG)

**Comment by hostbbb** [comment]
for grins i pulled the network connection on client,  it reconnected sucessfully and only 1 cam appears. So reconnect worked.  Not sure if it was a reconnect that caused 2.

**Comment by ffdixon** [comment]
Are you still able to reproduce this bug on http://demo.bigbluebutton.org/?

**Comment by hostbbb** [comment]
I saw it yesterday on reconnect,  but have not tried to get repeatable test case.  I'll try tomorrow to get it repeated,  when it came back, it had me in video dock twice.  this was with master built from sunday, and running on my local vm on pc.

**Comment by hostbbb** [comment]
Ok, built from master..  client 391
Startup your webcam.

#then on bbb server drop rtmp connections to client
      iptables -A INPUT -p tcp --dport 1935 -s x.x.x.x  -j DROP
#wait few seconds give them back
      iptables -F

The streams are both live and remain that way.

2 normal windows appear, followed by the first image

![dup1](https://cloud.githubusercontent.com/assets/519542/12493921/8f7f215a-c055-11e5-9a72-cc3e83bc6acc.PNG)

then shortly after the second image.
![dup2](https://cloud.githubusercontent.com/assets/519542/12493925/9267ecee-c055-11e5-9227-33665c5f741f.PNG)

If you repeat this every 3rd try the logic cleans it up.

**Comment by ffdixon** [comment]
Thanks Stephen!  We did a bit of work on the reconnecting of webcams in 1.0-beta, and we'll probably do more work on it the next release.

**Comment by hostbbb** [comment]
Ok, so opened viewer with new user to meeting,
And now see three camera, so looks like viewers are effected as well.

This test was moderator chrome, viewer firefox.

![viewdup](https://cloud.githubusercontent.com/assets/519542/12494198/db74e40e-c056-11e5-977f-39ac56cb50bf.PNG)

**Comment by hostbbb** [comment]
This is interesting and possibly embarrassing.

The user turns his camera off,  but the stream on his desktop is still being sent to everyone. Stealth mode.  He doesnt see his cam, by cam pub icon is present.

the logic doesnt allow you to turn this stream off, if you toggle the camera bottom, if just starts a second.  So the stream is live for duration of meeting.  

I wonder what shows up in recording at this point.

![stealth](https://cloud.githubusercontent.com/assets/519542/12494502/7b6511d6-c058-11e5-8d54-4d4f1a579cad.PNG)

**Comment by ffdixon** [comment]
Reproduced using the following steps using a Mac OS X laptop connected via wired network with wireless turned off.

Launch Chrome and join a BigBlueButton session. Share webcam.
Turn on wireless network
This triggers a network change event in Chrome that causes Flash to (temporarily) disconnect. BigBleuButton client reconnects, but it sometimes will show multiple webcams.

Here's a video to reproduce

https://www.youtube.com/watch?v=a3coz71Z1kc

**Comment by ffdixon** [comment]
Fixed in https://github.com/bigbluebutton/bigbluebutton/pull/2996.
