### ISSUE TITLE
Text from text box can appear on next slide

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#2810]
Steps to reproduce

1.  Draw a text box and enter text (but not click outside the text box to close it)
2.  Advance the slide
3.  Draw using one of the drawing toos

The text box will appear on the new slide.

**Comment by capilkey** [comment]
This pull request (https://github.com/bigbluebutton/bigbluebutton/pull/2814) implements a fix to make sure that text annotations are published to the correct whiteboard.

There is also a change to apply a check that ensures that only annotations that have a whiteboardID equal to the current one are shown. A similar check will likely need to be made in the recording processing scripts and the HTML5 client.

**Comment by ffdixon** [comment]
Tested and fixed.
