### ISSUE TITLE
Invalid Url on  the docs for 1.0.0 beta 

### ISSUE THREAD

**Issue by hogsim** [bigbluebutton/bigbluebutton#2816]
for the point 3 
$ echo "deb http://ubuntu.bigbluebutton.org/xxx/ bigbluebutton-trusty main" | sudo tee /etc/apt/sources.list.d/bigbluebutton.list
get that : 

http://ubuntu.bigbluebutton.org/xxx/dists/bigbluebutton-trusty/main/binary-amd64/Packages  404  Not Found

So i suppose xxx has been changed for something else but i dont see anything about that.

**Comment by ffdixon** [comment]
Hi Hogsim,

You've already posted this to our developer mailing list 

   https://groups.google.com/d/msg/bigbluebutton-dev/fQt245ElLr4/FlZ4nhmSBgAJ

There is no need to open an issue for this as we've not released BigBlueButton 1.0.0-beta yet.  When we do release it, we'll make an announcement to bigbluebutton-dev

  https://groups.google.com/forum/#!forum/bigbluebutton-dev
