### ISSUE TITLE
BigBlueButton stun endpoint doesn't allow html5 client to retrieve information

### ISSUE THREAD

**Issue by perroned** [bigbluebutton/bigbluebutton#2822]
<HOST>/bigbluebutton/api/stuns checks for valid client session data for the meeting so it is not compatible with the html5 client. Endpoint requires a valid connection with bbb-web and a valid session thus does not respond to the html5 client.

**Comment by antobinary** [comment]
This is fixed in 2.0 / html5 working with BBB 2.0 since we use sessionToken on the html5 client
