### ISSUE TITLE
Can't create meetings through API

### ISSUE THREAD

**Issue by petrikoz** [bigbluebutton/bigbluebutton#2829]
Hi.

I installed BBB 0.9 in virtual ubuntu. And it is working normally. But I can't create meeting.

When I try `http://192.168.1.26/bigbluebutton/api/create?meetingID=abc123&name=foo&checksum=d03c3e0e7fb1d03f65e5ad1f2efa342b6309e4ce` I get **404 Not Found** from Nginx.

But when I try `http://192.168.1.26/bigbluebutton/api/create?meetingID=abc123&checksum=d03c3e0e7fb1d03f65e5ad1f2efa342b6309e4ce` I get correct answer from server:

```
#!xml

<response>
  <returncode>FAILED</returncode>
  <messageKey>checksumError</messageKey>
  <message>You did not pass the checksum security check</message>
</response>
```

In nginx logs I see `upstream timed out`.

What am I doing wrong?

**Comment by ffdixon** [comment]
Hi,

Can you post this question to our bigbluebutton-dev mailing list at

  https://groups.google.com/forum/#!forum/bigbluebutton-dev

and we'll help you there. If we find there is an problem with 0.9, we'll open an issue to track it.  When you post, please give the output of

  sudo bbb-conf --check
