### ISSUE TITLE
BigBlueButton Flash causes Firefox 41.0.1 to lock up

### ISSUE THREAD

**Issue by kepstin** [bigbluebutton/bigbluebutton#2832]
This is due to the following Firefox bug:
https://bugzilla.mozilla.org/show_bug.cgi?id=1209464
See also our comments when we reported it:
https://bugzilla.mozilla.org/show_bug.cgi?id=1210665 (this issue has been marked as a duplicate of the first one)

This issue only affects Firefox 41.0.1 on windows. Firefox 41 is not affected. The fix is in Firefox 42 and later.

We have included a workaround for the whole-browser hang in BigBlueButton.html, see dbd79cebb52e1240743f107a941c4a76076e78b8
The workaround still exposes the other symptoms of the bug, where right-click menu is slow to open, and clicking on the Flash permissions dialog accept button is problematic.

**Comment by ffdixon** [comment]
Applied fix for BigBlueButton 0.9.x.  Users can update servers with steps here

  http://docs.bigbluebutton.org/install/install.html#upgrading-bigbluebutton-0-9

At this point the fix is in 0.9.x packages and 1.0-beta packages.

**Comment by ffdixon** [comment]
FireFox 42 released and after testing the Windows install I can't get any random freezes in BigBlueButton.  Looks like https://bugzilla.mozilla.org/show_bug.cgi?id=1209464 is fixed.
