### ISSUE TITLE
Saving user preferences

### ISSUE THREAD

**Issue by semirke** [bigbluebutton/bigbluebutton#2834]
Hi, 
  is there a way to prevent initial setup when entering a room? 
  It is unwanted that clients have to set microphone and camera settings all over again whenever they join a room.

Thank you for your help!
Bests,
Semir

**Comment by ffdixon** [comment]
Hi Semirke,

Please post such questions to our mailing list at bigbluebutton-setup

  https://groups.google.com/forum/#!forum/bigbluebutton-setup

We'll help you there. If we determine there is a problem with BigBlueButton itself, we'll open an issue here in GitHub to track it.

**Comment by semirke** [comment]
Thank you for your response.
