### ISSUE TITLE
Serialize and deserialize JSON message from classes

### ISSUE THREAD

**Issue by ritzalam** [bigbluebutton/bigbluebutton#2838]
Right now, we serialize and deserialize the messages by doing it manually when we can use Gson to do it for use.

https://sites.google.com/site/gson/gson-user-guide#TOC-Serializing-and-Deserializing-Generic-Types

This allows us to have consistent field names and less errors when sending/receiving messages.

**Comment by ritzalam** [comment]
An example of how to do this is in

https://github.com/ritzalam/bigbluebutton/blob/3db12990596d3a6e238ed7d2e8d74912a9beb766/bbb-common-message/src/main/java/org/bigbluebutton/messages/CreateBreakoutRoomsRequest.java

And the test in

https://github.com/ritzalam/bigbluebutton/blob/3db12990596d3a6e238ed7d2e8d74912a9beb766/bbb-common-message/src/test/java/org/bigbluebutton/messages/CreateBreakoutRoomsRequestTest.java

**Comment by ffdixon** [comment]
@ritzalam Can we close this?
