### ISSUE TITLE
Allow users to join meeting using the same browser on multiple tabs

### ISSUE THREAD

**Issue by ritzalam** [bigbluebutton/bigbluebutton#2839]
When a user joins the meeting using the same browser on multiple tabs, the session info doesn't get maintained properly. The last user's information will replace the previous user's session.

You can observe this by joining the meeting on one tab, then as another user join in another tab. On the first tab, you refresh the browser. When the user appears on the user's list, it will have the name of the user on the other tab.

**Comment by mouhsinelonly** [comment]
+1

**Comment by ffdixon** [comment]
This work is underway as part of the implementation of breakout rooms (slated for release in BigBlueButton 1.1).  See

   https://groups.google.com/d/msg/bigbluebutton-dev/2OLdUbi2K_w/1pzOZoppAwAJ

**Comment by ffdixon** [comment]
This work has been completed in BigBlueButton 1.1-beta.  The user can now use the same browser to join two separate sessions on the same BigBlueButton server.
