### ISSUE TITLE
Shortcut Keys list contains undefined values

### ISSUE THREAD

**Issue by GhaziTriki** [bigbluebutton/bigbluebutton#2847]
The last two values in Shortcut Keys list are 'undefined'

![image](https://cloud.githubusercontent.com/assets/4991088/10573617/a31d69bc-7648-11e5-8f10-8ced1634133c.png)

**Comment by capilkey** [comment]
Per discussion with @GhaziTriki, the old polling strings were removed from the locales when the PollingModule was redesigned. The locale keys need to be removed from the Shortcut Keys window and anywhere else they are located in the client.

**Comment by capilkey** [comment]
The key list was cleaned up by @GhaziTriki in https://github.com/bigbluebutton/bigbluebutton/pull/2849
