### ISSUE TITLE
Extend lock settings so moderators can chat with viewers

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#2848]
Currently, when a moderator locks private chat, viewers can not private chat -- even with moderators.

However, in a classroom setting, it would be useful for viewers to continue to have private chat with moderators for purposes of support.

Requested in bigbluebutton-dev

  https://groups.google.com/d/msg/bigbluebutton-dev/nNK02ma3lMs/_UsyAsfCBQAJ

**Comment by capilkey** [comment]
This functionality was added in 2.0 so I'm going to close this request.

There was a regression 2.2 and that issue can be found here, https://github.com/bigbluebutton/bigbluebutton/issues/6418.
