### ISSUE TITLE
Adding new language

### ISSUE THREAD

**Issue by acekovac** [bigbluebutton/bigbluebutton#2850]
I have new language translation, translated in http://transifex.com, but it's with ".properties" extension.
I've tried to convert to swf and replace the en_US_resources.swf file, but that didn't worked.

How can I add my language? Should I send you the file?
It's on Macedonian and it's 100% translated.

Thanks

**Comment by GhaziTriki** [comment]
On the [project page](https://www.transifex.com/ritzalam/bigbluebutton) , please click on "Join the team" button in the top right and select Macedonian (Macedonia) language. After being accepted you will be able to submit your file.

**Comment by acekovac** [comment]
Tnx GhaziTriki, but I am already a member.
I've finished the translation there and now I want to start using it somehow :)

**Comment by capilkey** [comment]
The instructions to build the language SWFs can be found here, http://docs.bigbluebutton.org/dev/localization.html#compiling-your-own-language-files-into-your-client.
You will need to add Macedonian to the list in locales.xml so that it is picked up by the client.

**Comment by capilkey** [comment]
Closing this since no further updates have been posted.
