### ISSUE TITLE
Multiple wav files/start audio file recording events generated

### ISSUE THREAD

**Issue by ritzalam** [bigbluebutton/bigbluebutton#2851]
Sometimes, there are multiple start recording events which results in having several recording WAV files in FreeSWITCH. The recordings are processed correctly but consumes disk space especially if the meeting is very long.

**Comment by ffdixon** [comment]
I was able to reproduce creating two simultaneous .wav files in a version prior to 0bba549b383c9c34a747cf2a829d3fda15a99764.  

In the latest build, I'm not able to use the same method to create duplicate .wav files.  Here's a quick video:

   https://youtu.be/KEIp_7MImDE

**Comment by ffdixon** [comment]
Fixed in https://github.com/bigbluebutton/bigbluebutton/pull/2971
