### ISSUE TITLE
stop reconnect when viewers being kick by instructors

### ISSUE THREAD

**Issue by dgclone01** [bigbluebutton/bigbluebutton#2861]

**Comment by hostbbb** [comment]
i think this is best accomplished by have a simple locked meeting button.  that prevents any new members from joining. Have to figure out how to handle reconnects though.

**Comment by hostbbb** [comment]
mconf-guest feature currently prompts a moderator any time a new guest user joins for them to accept/deny. so if you locked meeting, still could accept/deny users/reconnects with this similar approach.

**Comment by ffdixon** [comment]
The latest builds of BigBlueButton 1.0-beta prevent the user from refreshing their browser to reconnect after getting kicked.

**Comment by ffdixon** [comment]
Marking this as fixed in 1.0-beta.
