### ISSUE TITLE
Viewers can unmute themselves using the mute/unmute in video dock when lock settings are enabled

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#2863]
Reported in the forum

  https://groups.google.com/d/msg/bigbluebutton-dev/vf5yYwaK-3o/0uHJ2NMACAAJ

Regards,.. Fred

**Comment by ffdixon** [comment]
Incorrectly opened an issue -- the user was a moderator, not viewer.

https://groups.google.com/d/msg/bigbluebutton-dev/vf5yYwaK-3o/I1LlbzbaCAAJ

**Comment by ffdixon** [comment]
Just tested this and verified that a student can, indeed, mute/unmute themselves through the mute/unmute button on their webcam window.

Steps to reproduce

1.  In two browser tabs, login as viewer and moderator on

  http://demo.bigbluebutton.org/demo/demo3.jsp

2. As viewer, share microphone and webcam
3. As moderator, use lock settings to lock microphones

Viewer can mute/unmute themselves using the mute/unmute icon on their webcam window in the video dock.

   https://groups.google.com/d/msg/bigbluebutton-dev/vf5yYwaK-3o/Atxd-cYUCQAJ

**Comment by capilkey** [comment]
Fixed in this pull request, https://github.com/bigbluebutton/bigbluebutton/pull/2880

**Comment by ffdixon** [comment]
Tested this, but I think it's missing a case.

When the moderator unlocks viewer's microphones, they are not able to mute/unmute themselves using the microphone button in the video window (but they can with the microphone button in the user's list).

**Comment by ffdixon** [comment]
Tested again and looks good.
