### ISSUE TITLE
Text appears on each slide when polling

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#2871]
In BigBlueButton 1.0-beta, text entered with the text tool appears on each slide after a poll.

1.  Join a session on BigBlueButton 1.0 as presenter
2.  Write "Hello" using the text tool
3.  Do a poll (you can publish with no responses)
4.  Advance the slide

The text "Hello" appears on the next slide.

**Comment by capilkey** [comment]
The text annotations were being cast as DrawObjects, but they aren't a subclass which threw an exception. Changed the variable to Object and it now functions as expected.

Fixed in this pull request, https://github.com/bigbluebutton/bigbluebutton/pull/2875.
