### ISSUE TITLE
grails error has occured

### ISSUE THREAD

**Issue by mouhsinelonly** [bigbluebutton/bigbluebutton#2872]
when i try this call 
http://52.32.108.164/bigbluebutton/api/create?name=Test+Meeting+Name&meetingID=1234&attendeePW=ap&moderatorPW=mp&dialNumber=&voiceBridge=&webVoice=&logoutURL=&maxParticipants=-1&record=false&duration=0&checksum=4982b4e652bd075bafe6d1eb78710509e5ceb568

i get an error has occurred without specifying what's the exact error

**Comment by ffdixon** [comment]
Hi, 

Can you please post this message to bigbluebutton-dev (our developer mailing list) and the community can help you there.

  https://groups.google.com/forum/#!forum/bigbluebutton-dev

If during the community's efforts to resolve the problem we determine there is a bug in BigBlueButton itself, we'll open an issue here to track and fix.

Also, when you post, you need to give more information on your setup and any customizations you've done to BigBlueButton.  There isn't enough information in your post for another developer to attempt reproduce the problem.

**Comment by mouhsinelonly** [comment]
i have a fresh bigbluebutton running on amazon EC2 i ve done no customization to it .

**Comment by capilkey** [comment]
I think this might actually be a bug, sort of. The problem is that the URL doesn't have a value for the "voiceBridge" and just leaves it blank. If you change the voiceBridge from blank to a number the resulting page will be our checksum error instead of the default Grails error page.

**Comment by mouhsinelonly** [comment]
i changed it but no luck still getting the same error 

http://52.32.108.164/bigbluebutton/api/create?name=Test+Meeting+Name&meetingID=1234&attendeePW=ap&moderatorPW=mp&dialNumber=&voiceBridge=55668&webVoice=&logoutURL=&maxParticipants=60&record=false&duration=0&checksum=4c4f14c947f9e2eefecfd6b9dd2547b4288a77f1


is there a way i can enable grails errors ?

**Comment by antobinary** [comment]
Mouhsineonly,
I am unable to log in your BBB server through the demo page http://52.32.108.164
Were you ever able to do it? Are you sure your server installed correctly?
sudo bbb-conf --check
Please copy-paste the output of the above command and please let's continue this thread in bigbluebutton-dev, not here.

Regards,
Anton

**Comment by mouhsinelonly** [comment]
i can access it from here and it working just fine http://52.32.108.164/bigbluebutton/

i ve applied to join the group

**Comment by mouhsinelonly** [comment]
i ve installed it now

**Comment by mouhsinelonly** [comment]
its working now it was something due to the configuration thank you
