### ISSUE TITLE
Chat text does not escape html properly

### ISSUE THREAD

**Issue by maxdoumit** [bigbluebutton/bigbluebutton#2878]
Pasting the following into chat for example

xmlns="http://google.co/"

Outputs

xmlns="

**Comment by maxdoumit** [comment]
Problem is not limited only to current release.
Was able to replicate on demo.bigbluebutton.org, bigbluebutton 0.9 and bigbluebutton 0.81

**Comment by maxdoumit** [comment]
If the text message has \" in it, the text message will be ignored.

**Comment by ffdixon** [comment]
Fixed in BigBlueButton 2.2.

![image](https://user-images.githubusercontent.com/290351/55677856-af064e00-58bd-11e9-93c1-3a40a750b023.png)
