### ISSUE TITLE
Status and poll things a localized but still english in my newest installation

### ISSUE THREAD

**Issue by KissDaniGH** [bigbluebutton/bigbluebutton#2881]
Hi
more than 2 month ago "Raise hand" and "Start a poll" is translated, but just installed bbb and status and polling strings are still english.

**Comment by KissDaniGH** [comment]
same "error" on demo.bigbluebutton.org

**Comment by ffdixon** [comment]
Hi Kiss-Kálmán,

We periodically pull the localization strings from Transifex.  We'll pull
the latest strings for the next update to 1.0-beta and update this thread
when they are ready.

Regards,... Fred

On Fri, Nov 6, 2015 at 2:28 AM, Kiss-Kálmán Dániel <notifications@github.com
> wrote:

> same "error" on demo.bigbluebutton.org
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bigbluebutton/bigbluebutton/issues/2881#issuecomment-154333766>
> .
>



-- 
BigBlueButton Developer
http://bigbluebutton.org/
@bigbluebutton

**Comment by ffdixon** [comment]
Hi Kiss-Kálmán,

Can you test http://demo.bigbluebutton.org/ and let us know if you see the the translated text for "Raise Hand" and "Start a poll".

**Comment by KissDaniGH** [comment]
Hi Fred,
it's more than perfect. Thanks
