### ISSUE TITLE
Long meetings have the audio cut off (wave files >4GB) in 0.9

### ISSUE THREAD

**Issue by kepstin** [bigbluebutton/bigbluebutton#2887]
Backport the fix for this issue from 1.0 to the 0.9 branch.

**Comment by kepstin** [comment]
The following commits are needed:
1dcd49e18089665efa520c412b80e7dcf8f5977d
530799776dc41ae7d3875f4f98f70599c71e9980
d44b458b492f5888df16903ede8dd02855c921cc
a6d6001040f961070155789c5c659573343c78ca
7069a4a6d7b3ce277cf2da5132912f33cc15bf1c

**Comment by ffdixon** [comment]
Closing as this is an old issue.  We'll open a new issue if this problem arises in the latest version.
