### ISSUE TITLE
Recording doesn't load over https (hardcoded http url, mixed content) in 0.9

### ISSUE THREAD

**Issue by kepstin** [bigbluebutton/bigbluebutton#2888]
Backport the fix to this issue from 1.0 to 0.9

This needs the following commits ported:
39cc6a80a643beba2245007b59743c0733d994a3
maybe also fc299487e43e2552742a00438987514fc91f00bd

**Comment by ffdixon** [comment]
Tested this in BigBlueButton 2.0-beta and the presentation format correctly loads over https.
