### ISSUE TITLE
Slides not rendered in the client in certain situations

### ISSUE THREAD

**Issue by GhaziTriki** [bigbluebutton/bigbluebutton#2908]
Current behaviour:
- When a presentation is converted in the server, each object is converted to a single SWF shape. The client hangs and fails to open it.

Detected issues:
- Some of the of the rendered swfs contain a font glyph definition with an unknown codepoint value "\<glyph codepoint=' 0(?)'>", the codepoint equals to zero means that this is the NULL character, it should not happen.
- Some slides contains too much objects and the Flash runtime takes a lot of time to render them all.

Suggested solutions
- Understand why the glyph contains an unknown codepoint value and fix it if possible.
- Verbose the swf rendering and fallback to "convert everything to bitmaps" if the number of the polygons is too high.

**Comment by GhaziTriki** [comment]
A reference to the glyph code point issue can be found here https://issues.apache.org/jira/browse/FLEX-34451

**Comment by GhaziTriki** [comment]
A discussion has been started to gather more information about the zero glyph inside a SWF font definition, it can be followed here http://apache-flex-development.2333347.n4.nabble.com/SWF-Glyph-code-point-zero-td50314.html

**Comment by ffdixon** [comment]
Fixed by #2933
