### ISSUE TITLE
Security Issues

### ISSUE THREAD

**Issue by vicencarlos** [bigbluebutton/bigbluebutton#2913]
We found a high potential security issue in the life demo version. It's possible to inject javascript in the parameter meetingID

![xss](https://cloud.githubusercontent.com/assets/754434/11421280/0d3ad4e8-9434-11e5-81be-9364f360e2a6.png)

**Comment by ffdixon** [comment]
Hi,

This was reported in bigbluebutton-dev on Nov 19th, see

  https://groups.google.com/d/msg/bigbluebutton-dev/XwY6EiQF8z8/gAVdFGPJBwAJ

The API demo11.jsp is displaying verbatim what the user entered into the demo.  We'll modify it to remove the ability to inject JavaScript code.

The API examples are for testing BigBlueButton only.  If you install them on a BigBlueButton server, you'll get the following warning message when running

```
$ sudo bbb-conf --check

# Warning: The API demos are installed and accessible from:
#
#    http://demo.bigbluebutton.org/
#
# These API demos allow anyone to access your server without authentication
# to create/manage meetings and recordings. They are for testing purposes only.
# If you are running a production system, remove them by running:
#
#    sudo apt-get purge bbb-demo
```
