### ISSUE TITLE
Audio testing for viewers when microphone is locked

### ISSUE THREAD

**Issue by tdjac0bs** [bigbluebutton/bigbluebutton#2921]
What steps will reproduce the problem?
1.  Login as a moderator
2.  Lock the microphone (viewers can not share)
3.  Login as viewer

When a new viewer joins, there is no way to test the audio (listen only).

**Comment by ffdixon** [comment]
iOS requires that users give permission to play audio.  

Currently, locking the microphone causes BigBlueButton on iOS to join without any user input, which results in no audio being played.

**Comment by ahmed-classtra** [comment]
@ffdixon I have this case with my instance of BBB. Moderator locks microphone and all the mobile students (iOS) stop hearing the voice when they join. I had to force them to allow mic by disabling listen only mode.

Is there any way around this? Maybe another solution for the issue? 
@tdjac0bs mind telling us if you were able to find a solution?

**Comment by antobinary** [comment]
Merging into #9719 (more detailed and describes a possible workaround via muteOnJoin)
