### ISSUE TITLE
I connect BigBlueButton to external FreeSWITCH Server Failed

### ISSUE THREAD

**Issue by mrwutong** [bigbluebutton/bigbluebutton#2932]
i have 2 servers, want external freeswitch server. but failed.
server info: ubuntu 14.04, bigbluebutton 0.9
svr1(server1): 192.168.1.162
svr2(server2): 192.168.1.242

do it with [http://docs.bigbluebutton.org/support/faq.html#how-do-i-connect-bigbluebutton-to-external-freeswitch-server],

*on svr1:
/usr/share/red5/webapps/bigbluebutton/WEB-INF/bigbluebutton.properties
freeswitch.esl.host=192.168.1.242
>> password was not changed, use default value[ClueCon] always.

*on svr2:
/opt/freeswitch/conf/autoload_configs/event_socket.conf.xml
<param name="listen-ip" value="0.0.0.0"/>

*on svr1:
/usr/share/red5/webapps/sip/WEB-INF/bigbluebutton-sip.properties
bbb.sip.app.ip=192.168.1.162
freeswitch.ip=192.168.1.242

*on svr2:
/opt/freeswitch/conf/directory/default/bbbuser.xml
nothing to do;

*on svr1:
sudo bbb-conf --clean
sudo /etc/init.d/bbb-freeswitch stop

*on svr2:
sudo /etc/init.d/bbb-freeswitch restart

*on client browser's url: 192.168.1.162/check
<Item>: WebRTC Socket Test <Result>: 1002 <Status>: Failed

*on svr1: /etc/init.d/bbb-red5 restart
 * Stopping Red5 Server red5  [ OK ]
 * Starting Red5 Server red5                                                                                                                                                  ...... Error: FreeSWITCH didn't start

*on svr1: telnet 192.168.1.242 5060
Trying 192.168.1.242...
Connected to 192.168.1.242.
Escape character is '^]'.

*on svr1: /usr/share/red5/log/192.168.1.242.5070_events.log
======================================================
SipProvider-5070: Date: 17:49:46.038 Tue 15 Dec 2015
SipProvider-5070: SipStack: mjsip stack 1.6
SipProvider-5070: new SipProvider(): 5070/udp/tcp
TransactionClient#0: id: 781546400857@192.168.1.242-1-REGISTER-192.168.1.242:5070-z9hG4bK296820
TransactionClient#0: created

17:49:46.319 Tue 15 Dec 2015, 192.168.1.242:5060/udp (389 bytes): REGISTER sip:192.168.1.242 SIP/2.0, sent

17:49:46.341 Tue 15 Dec 2015, 192.168.1.242:5060/udp (644 bytes): SIP/2.0 401 Unauthorized, received

SipProvider-5070: received new SIP message
TransactionClient#1: id: 781546400857@192.168.1.242-2-REGISTER-192.168.1.242:5070-z9hG4bK010851
TransactionClient#1: created

17:49:46.511 Tue 15 Dec 2015, 192.168.1.242:5060/udp (651 bytes): REGISTER sip:192.168.1.242 SIP/2.0, sent

17:49:46.573 Tue 15 Dec 2015, 192.168.1.242:5060/udp (606 bytes): SIP/2.0 200 OK, received

SipProvider-5070: received new SIP message
TransactionClient#0: Clearing timeout expired
TransactionClient#1: Clearing timeout expired
TransactionClient#2: id: 943471691868@192.168.1.242-1-REGISTER-192.168.1.242:5070-z9hG4bK466472
TransactionClient#2: created

17:50:05.259 Tue 15 Dec 2015, 192.168.1.242:5060/udp (355 bytes): REGISTER sip:192.168.1.242 SIP/2.0, sent

17:50:05.690 Tue 15 Dec 2015, 192.168.1.242:5060/udp (644 bytes): SIP/2.0 401 Unauthorized, received

SipProvider-5070: received new SIP message
SipProvider-5070: WARNING: Error handling a new incoming message

*on svr1: sudo bbb-conf --check
======================================================
BigBlueButton Server 1.0.0-beta (966)
                    Kernel version: 3.13.0-32-generic
                      Distribution: Ubuntu 14.04.1 LTS (64-bit)
                            Memory: 3953 MB

/var/www/bigbluebutton/client/conf/config.xml (bbb-client)
  		Port test (tunnel): 192.168.1.162
                              Red5: 192.168.1.162
              useWebrtcIfAvailable: true

/opt/freeswitch/conf/sip_profiles/external.xml (FreeSWITCH)
                    websocket port: 5066
                    WebRTC enabled: true

/etc/nginx/sites-available/bigbluebutton (nginx)
                       server name: 192.168.1.162
                              port: 80
                    bbb-client dir: /home/bbb/dev/bigbluebutton/bigbluebutton-client

/var/lib/tomcat7/webapps/bigbluebutton/WEB-INF/classes/bigbluebutton.properties (bbb-web)
                      bbb-web host: 192.168.1.162

/var/lib/tomcat7/webapps/demo/bbb_api_conf.jsp (API demos)
                           api url: 192.168.1.162

/var/www/bigbluebutton/check/conf/config.xml (client check)
                      client check: 192.168.1.162

/usr/share/red5/webapps/bigbluebutton/WEB-INF/red5-web.xml (red5)
                  voice conference: FreeSWITCH
                     capture video: true
                   capture desktop: true

/usr/local/bigbluebutton/core/scripts/bigbluebutton.yml (record and playback)
                     playback host: 192.168.1.162

** Potential problems described below **

# The values for listen-ip in
#     /opt/freeswitch/conf/autoload_configs/event_socket.conf.xml
# do not match the settings for esl.host in
#     /usr/share/red5/webapps/bigbluebutton/WEB-INF/bigbluebutton.properties

# The following properties in /var/lib/tomcat7/webapps/bigbluebutton/WEB-INF/classes/bigbluebutton.properties have no value:
#     defaultWelcomeMessage
defaultWelcomeMessageFooter
# Warning: nginx is not serving the client from /var/www/bigbluebutton/.
# Instead, it's being served from
#
#    /home/bbb/dev/bigbluebutton/bigbluebutton-client
#
# (This is OK if you have setup a development environment.)

# Warning: The API demos are installed and accessible from:
#
#    http://192.168.1.162/
#
# These API demos allow anyone to access your server without authentication
# to create/manage meetings and recordings. They are for testing purposes only.
# If you are running a production system, remove them by running:
#
#    sudo apt-get purge bbb-demo

# Warning: The client self check is installed and accessible from:
#
#    http://192.168.1.162/check
#

**Comment by ffdixon** [comment]
This is not an issue with BigBlueButton but rather an error with setting up a specific configuration.

Post setup-related questions to the bigbluebutton-setup mailing list

  https://groups.google.com/forum/#!forum/bigbluebutton-setup
