### ISSUE TITLE
Ensure single instance of akka-bbb-{apps,fsesl} is running

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#2936]
We need to limit the number of instances to one per type. Otherwise it's possible to have two+ at a time and the meeting logic suffers.

**Comment by GhaziTriki** [comment]
Helpful documentation can be found here http://doc.akka.io/docs/akka/2.4/scala/cluster-singleton.html

**Comment by ffdixon** [comment]
Closing as this is an old issue.  We'll open a new issue if this problem arises in the latest version.
