### ISSUE TITLE
Add "thumbsup," "thumbsdown," and "applause" symbols to emoticons

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#2940]
Add three more icons 

  thumbs up
  thumbs down
  applause

to the list of emoticons in BigBlueButton.

**Comment by kephas** [comment]
It might be interesting to have a feature separate from emoticons, to express a passing sentiment. Thumbs up and down and applause might especially be a good fit for this.

**Comment by ffdixon** [comment]
This is pending in pull request

  https://github.com/bigbluebutton/bigbluebutton/pull/3050

**Comment by ffdixon** [comment]
Thanks for the work guys -- we've merged into BigBlueButton 1.1-beta.

![emoji](https://cloud.githubusercontent.com/assets/290351/21966803/a1af30ea-db48-11e6-9902-09c7e9b3fd41.PNG)
