### ISSUE TITLE
Getting exceptions while switching between presentations

### ISSUE THREAD

**Issue by OZhurbenko** [bigbluebutton/bigbluebutton#2941]
Noticed that we still have some exceptions in HTML5 client when switch between different uploaded presentations.
Probably that's caused by the cursor positioning.

![errors](https://cloud.githubusercontent.com/assets/9299997/12127806/4afd6586-b3c7-11e5-9a67-7e77e593cf51.JPG)

**Comment by antobinary** [comment]
Seems to be fixed as part of #2984
