### ISSUE TITLE
WebRTC desktop sharing 

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#2943]
Implement a desktop sharing capability using WebRTC. Some of the benefits are:
-fast high quality desktop sharing
-no need of Java plug-ins
-compatible with the HTML5 client

**Comment by nadavkav** [comment]
My +1 to making it happen. current state of desktop sharing with java (and only on firefox, as chrome does not support java anymore) is unusable. very slow and pixeled view.

**Comment by mkpelletier** [comment]
+1 from me too!  The Java implementation has become less useful since Chrome stopped supporting NPAPI.

**Comment by ffdixon** [comment]
We're actively working on this now.  We want it too :-).

**Comment by udayakiran** [comment]
Hi,

Nice to see that active work is happening on this. Just a couple pointers from myside.

1) Safari and IE are still not supporting webRTC. So, if the presenter is on one of these, he may need to install a webRTC plugin like this one - https://temasys.atlassian.net/wiki/display/TWPP/WebRTC+Plugins and the code needs to support these adapters to capture the desktop.

2) Not sure if this is the right place to suggest, but what about a JNLP app ? 
I can see this here - https://github.com/BigMarker/deskshare-public 
building a JNLP app seems to be the goto way for applets on chrome after the drop for NPAPI plugins.
Thoughts on this ?

3) Building a one click based installer based on webRTC /  something like seem to be the only cross browser & cross device way ? 

Thanks!

**Comment by nadavkav** [comment]
Maybe you already know about this, but just in case:
https://www.webrtc-experiment.com/Pluginfree-Screen-Sharing/
https://www.webrtc-experiment.com/screen-sharing/
https://www.webrtc-experiment.com/RTCMultiConnection/screen-sharing.html

**Comment by yoldar** [comment]
+1 This is a "hot" Enhancement

**Comment by mkpelletier** [comment]
I don't think too much effort should be expended on IE.  IE is dead.  The
new Edge browser does support some aspects of webrtc, and support will
continue to improve.   Safari is the last hold out for this and its users
have been crying for it. The npapi desktop sharing can always serve as a
fallback for the browsers that do not yet support webrtc.

Sent from my phone
pardon brevity and typos

**Comment by ffdixon** [comment]
We plan to keep the current Java-based desktop sharing for supporting Safari and IE.  

This is the same approach we did with WebRTC audio: if you use FireFox or Chrome, WebRTC audio is the default.  If it doesn't work -- or your are on Safari or IE -- BigBlueButton falls back to Flash-based audio.

For desktop sharing, the plan is if you use FireFox or Chrome, WebRTC desktop sharing will be the default.  If it doesn't work -- or your are on Safari or IE -- BigBlueButton will fall back to Java-based desktop sharing.

**Comment by mkpelletier** [comment]
Fred, you guys are awesome! We are looking forward to it.

Sent from my phone
pardon brevity and typos

**Comment by udayakiran** [comment]
Hi,

Gotcha! fallback option works.

(Just to mention that JNLP app instead NPAPI gives a little better UX as users dont need to figure out how to enable java on their browsers. But it's a minor thing.)

Thanks.

**Comment by tsalafi** [comment]
I think we should convert our desktop sharing applet into a jnlp java application (java web start) ... it will eliminate any cross-browser problems.

**Comment by ffdixon** [comment]
Just to let everyone know, we are actively working on converting the desktop sharing applet into a Java Web Start application (launched via JNLP).  

We'll update this issue as we progress.

**Comment by tsalafi** [comment]
Ohk thank you so much.... I don't have words to thank you :) 
awesome team :)

**Comment by udayakiran** [comment]
Fred, Thanks. Great decision keeping cross browser & device support in mind. Looking forward for it.

**Comment by ffdixon** [comment]
We saw the BigMarker release last year. Unfortunately, they released it under the APL license, so we were unable to use any of the work.  We've since been working on our own version that we can release under the LGPL license.

**Comment by udayakiran** [comment]
Fred, okay :) Thanks!

**Comment by nadavkav** [comment]
Hope you are seriously considering other solution than java for desktop sharing, as it is unusable on several levels (very low performance, modern browsers do not like java, java security, UX and usability), especially, comparing to desktop sharing solutions from other web conferencing alternative tools.

Supporting Safari or IE is not something worth consideration, for us. as we have both under 15% usage and steadily declining.

**Comment by ffdixon** [comment]
We do believe it's worth supporting IE and Safari. It makes the BigBlueButton project *much* more attractive if we can say you can support desktop sharing on all major browsers.

We are looking at using WebRTC for desktop sharing as well.  See

   https://github.com/bigbluebutton/bigbluebutton/issues/2943

So, the best result would be to use WebRTC for desktop sharing (if you are on FireFox or Chrome), and, if not, fall back to using Java Web Start.  That way we give the user the best possible experience depending on which browser they are using.

**Comment by nadavkav** [comment]
This is #2943 , what do you mean?

**Comment by nadavkav** [comment]
Do you have a working solution for desktop sharing in Chrome & Firefox that uses WebRTC?

**Comment by ffdixon** [comment]
Watch #2943 for future updates to gauge how close we are to having WebRTC-based desktop sharing.

**Comment by nadavkav** [comment]
Ok. I was too much confused reading email updates to this issue with the word "Java" in the last few comments, that it seems to me that you are not considering WebRTC as a solution. me bad.
Just saw one of your earlier comments:
_"For desktop sharing, the plan is if you use FireFox or Chrome, WebRTC desktop sharing will be the default. If it doesn't work -- or your are on Safari or IE -- BigBlueButton will fall back to Java-based desktop sharing."_
And I totally agree that this is the way to move forward.

**Comment by nadavkav** [comment]
Very much appreciate all your work on this product!

**Comment by gilou** [comment]
jnlp is still a good alternative, especially given the current support of screen sharing in WebRTC,  that doesn't allow proper region (haven't seen that in any browser, out of the box) / full screen (works in Chrome, even though you might not be able to share ONE screen if you have more than one) sharing. However, the packaging/signing of the jnlp might be an issue by itself. Definitely looking forward to all this.

**Comment by philjoseph** [comment]
Hello BBB team. Do  you know what is the status on this enhancement? Is development ongoing or is it just at the level of prioritisation?

**Comment by ffdixon** [comment]
Hi Phil,

The development is ongoing.  For the upcoming BigBlueButton 1.1 release, we'll me moving from a Java Applet to a Java Application launched via a Java Network Launch Protocol File (JNLP).  This way, we can run the Java-based screen sharing outside the browser (and bring Chrome back into the fold).

We're working on the WebRTC-based desktop sharing in parallel and it will land in a future version.

For more information see

   https://groups.google.com/d/msg/bigbluebutton-dev/2OLdUbi2K_w/1pzOZoppAwAJ

**Comment by nguyenthinu0212** [comment]
share your screen is undefined. Help me

**Comment by slimit** [comment]
What are the latest changes concerning the Desktop sharing feature ?

I just tried on Ubuntu Chrome but Java blocks the application because he consider the ssl cert as self-signed one even if it comes from LetsEncrypt and the cert details are showing that it is a LetsEncrypt cert and not a self-signed one.

**Comment by capilkey** [comment]
@slimit I'm not quite sure what you're referring to. This issue is about implementing WebRTC desktop sharing and you mentioned Java blocking a cert. The WebRTC desktop sharing doesn't use Java. Help requests are much better directed to the Google Groups, https://groups.google.com/forum/#!forum/bigbluebutton-setup and https://groups.google.com/forum/#!forum/bigbluebutton-dev.

**Comment by slimit** [comment]
@capilkey You are right, I was not so clear.

Is WebRTC desktop sharing supported on Ubuntu ?

**Comment by ffdixon** [comment]
Closing this as it is now in BigBlueButton 2.0.
