### ISSUE TITLE
Use Chinese meeting name

### ISSUE THREAD

**Issue by onmore** [bigbluebutton/bigbluebutton#2958]
When  I ceate a meeting which use param like "name=测试会议&meetingID=test1&moderatorPW=mp&attendeePW=a",the meeting will create successfully,but the meeting name can not display correct.

**Comment by ffdixon** [comment]
You need to URL escape the name.
For example, here is a create call

http://test-install.blindsidenetworks.com/bigbluebutton/api/create?meetingID=random-2572989&moderatorPW=mp&name=%E6%B5%8B%E8%AF%95%E4%BC%9A%E8%AE%AE ...

and here is what BigBlueButton shows in the meeting

![image](https://cloud.githubusercontent.com/assets/290351/12372477/eb8f92fa-bc26-11e5-80fe-8a6b0efba0b6.png)

Use the excellent API Mate to test your API calls.  See

  http://docs.bigbluebutton.org/dev/api.html#testing-api-calls
