### ISSUE TITLE
passing invalid configToken on join throws grails 500

### ISSUE THREAD

**Issue by hostbbb** [bigbluebutton/bigbluebutton#2960]
![configtoken-error](https://cloud.githubusercontent.com/assets/519542/12381828/d50fd834-bd5f-11e5-9163-668ea5d9592e.PNG)

Current 1.0Beta,  if you send a join with configToken, that is invalid you get 500 error, and not a valid response that does not exist.

I did this with /var/bigbluebutton/configs,  configToken= test.xml  and also with a random made up config number.

Steps.

1) create a meeting
http://test-install.blindsidenetworks.com/bigbluebutton/api/create?allowStartStopRecording=true&attendeePW=ap&autoStartRecording=false&meetingID=random-7705890&moderatorPW=mp&name=random-7705890&record=false&voiceBridge=78188&welcome=%3Cbr%3EWelcome+to+%3Cb%3E%25%25CONFNAME%25%25%3C%2Fb%3E%21&checksum=8cc8e32d2cbfc65bc7d065a75ea17ef366a3aace

2) Pass join with invalid config
http://test-install.blindsidenetworks.com/bigbluebutton/api/join?configToken=testme.xml&fullName=User+2191794&meetingID=random-7705890&password=mp&redirect=true&checksum=729ec0bfc323a6b7e85a31923ebd31dc2f3f32a6

**Comment by jfederico** [comment]
Looking to this issue what I am seeing is that the response is still the 500. What should be the response for this exception?, an error message or to load the default config.xml?

**Comment by ritzalam** [comment]
I think return and error with message that says no valid config found. If we load the default config.xml, the user will get confused if he sees that info in his config.xml isn't there. For example, change in the layout or modules loaded.

Returning an error when it failed will narrow down where the problem occurred than when the user is already inside the meeting and find the config he did not expect is applied on his client.

**Comment by kepstin** [comment]
Since this is on the join call, it probably should go to a user-friendly(ish) error page. Perhaps a page that shows the error in a box, then includes a button that redirects to the logout URL?

I don't think we should allow joining with an invalid config token, since that's a programming error in the integration which we shouldn't hide, since otherwise they might never notice it.

**Comment by ritzalam** [comment]
Yes. It's the path of least surprise.

**Comment by jfederico** [comment]
agreed with that, Looking into the code  it seems that the original intention was to proceed with the default config.xml, that was what made me hesitate

**Comment by jfederico** [comment]
Fixed https://github.com/jfederico/bigbluebutton/commit/a41646e4c47d60cd7bf06826f9975fafa720bdb1

I'll be merged in a cumulative PR

**Comment by ffdixon** [comment]
This fix is merged into BigBlueButton 1.1.  Trying this on the API demos will return back an error that gets printed at the top.

![image](https://user-images.githubusercontent.com/290351/41502598-bd3d80f2-718b-11e8-9db0-3b9512393c5b.png)
