### ISSUE TITLE
On playback page detect Safari browser and show warning message

### ISSUE THREAD

**Issue by yoldar** [bigbluebutton/bigbluebutton#2974]
Safari browser do not support webm file format. When user tries to open recorded webinar, he just sees spinning status and nothing else happens. "playback.html" need to show message like "Safari is not supported".

**Comment by ffdixon** [comment]
Hi Yoldar,

Correct.  We have a message at the bottom of the playback screen that recommends the user use FireFox or Chrome.  

![image](https://cloud.githubusercontent.com/assets/290351/12534519/c831fa82-c22a-11e5-99bb-f2227da19d2e.png)

It would be great if Apple supported WebM, but until then you'll need to use FireFox or Chrome.   See

  http://caniuse.com/#feat=webm
