### ISSUE TITLE
Add a new file support for the whiteboard

### ISSUE THREAD

**Issue by abouhanna** [bigbluebutton/bigbluebutton#2989]
Hello, 

Is it possible to add a new file type in the whiteboard, for example, psd ....

Thank you.

**Comment by ffdixon** [comment]
Hi, 

Can you post these questions to our community at bigbluebutton-users, see

  https://groups.google.com/forum/#!forum/bigbluebutton-users

If we find an issue with BigBlueButton, we'll open an issue here to track it.

**Comment by abouhanna** [comment]
ok tnx.
