### ISSUE TITLE
Client Build Failure

### ISSUE THREAD

**Issue by javadev85** [bigbluebutton/bigbluebutton#3014]
Hi,
when i go to /home/firstuser/dev/bigbluebutton/bigbluebutton-client
then "ant"
i receive the following error i can't find the solution 
Buildfile: /home/firstuser/dev/bigbluebutton/bigbluebutton-client/build.xml
  [taskdef] Could not load definitions from resource flexTasks.tasks. It could not be found.

init-ant-contrib:

clean:
     [echo] Locale output dir exists. Deleting contents of /home/firstuser/dev/bigbluebutton/bigbluebutton-client/client/locale

generate-html-wrapper:

BUILD FAILED
/home/firstuser/dev/bigbluebutton/bigbluebutton-client/build.xml:457: Problem: failed to create task or type html-wrapper
Cause: The name is undefined.
Action: Check the spelling.
Action: Check that any custom tasks/types have been declared.
Action: Check that any <presetdef>/<macrodef> declarations have taken place.

Total time: 0 seconds

BBB Version : 0.9

Please Help me , this is so urgent

Regards

**Comment by GhaziTriki** [comment]
Hello,

It looks like FLEX_HOME environment variable is not defined.
Did you follow the steps for preparing a development environment? http://docs.bigbluebutton.org/1.0/10setup.html#setup-a-development-environment

**Comment by javadev85** [comment]
yes

**Comment by GhaziTriki** [comment]
If you run the following command ```mxmlc -v``` do you get the any error?

**Comment by GhaziTriki** [comment]
I can confirm that the client is building.  This issue you have is proably related to your environment setup. Please post to the development mailing list (https://groups.google.com/forum/?fromgroups=#!forum/bigbluebutton-dev) and someone can help you here.

**Comment by GhaziTriki** [comment]
This can be closed. The reason is in lack of permissions to acces $FLEX_HOME/ant.
