### ISSUE TITLE
Problem in latest upstream build with WebRTC

### ISSUE THREAD

**Issue by mkpelletier** [bigbluebutton/bigbluebutton#3019]
Hello All,

Since updating recently, it seems webrtc no longer works.  I can telnet to the required ports, but no browser connects (Chrome 48, FF 46, or Opera 35).  I have also tried the check facility on demo.bigbluebutton.org in both http and https, but the WebRTC echo and socket tests never complete.  Is this a known issue?

**Comment by ffdixon** [comment]
Hi, please post this issue to our [bigbluebutton-setup mailing list](https://groups.google.com/forum/#!forum/bigbluebutton-setup).  If we determine there is an issue with BigBlueButton itself, we'll open an issue here.

(it very much sounds like an issue with configuration).

**Comment by mkpelletier** [comment]
Thanks Fred.  This seems to have righted itself after running an update to BBB.
