### ISSUE TITLE
Multiple wav files gets generated with only one StartRecording but multiple StopRecording events

### ISSUE THREAD

**Issue by ritzalam** [bigbluebutton/bigbluebutton#3022]
On a few occasions, we've seen a few recordings where in the events.xml there is one StartRecording event but multiple StopRecording events.

From what I've seen, 2 meetings were created. One of the StopRecording events is from the other meeting while the other StopRecording event is for the recorded meeting.

  <event timestamp="1228874733" module="VOICE" eventname="StopRecordingEvent">
    <bridge>24015</bridge>
    <recordingTimestamp>1228874732</recordingTimestamp>
    <filename>/var/freeswitch/meetings/047dcfb53b2568dd7f176002dcc5fc0a37f6c378-1455642043756-1203049062.wav</filename>
  </event>
  <event timestamp="1228874753" module="VOICE" eventname="StopRecordingEvent">
    <filename>/var/freeswitch/meetings/047dcfb53b2568dd7f176002dcc5fc0a37f6c378-1455663702634-1224656701.wav</filename>
    <bridge>24015</bridge>
    <recordingTimestamp>1228874752</recordingTimestamp>
  </event>

Notice that the meetingId for the events are different.

**Comment by ffdixon** [comment]
@ritzalam and @antobinary, do you think this issue still exists in BigBlueButton 1.1-beta?

**Comment by ffdixon** [comment]
@ritzalam Do you think this is still an issue with 2.2-beta?

**Comment by ffdixon** [comment]
Closed -- we are reopen again if found in 2.3 (or beyond).
