### ISSUE TITLE
Enhancement- Add Arrow and highlighter to toolbar

### ISSUE THREAD

**Issue by mkpelletier** [bigbluebutton/bigbluebutton#3025]
It would be useful to have an arrow and highlighter on the tool bar.

**Comment by ffdixon** [comment]
Thanks for the feedback Mark.  We'll look at adding it in a future release.  To understand more how we prioritize features for each release, see

  http://docs.bigbluebutton.org/support/faq.html#when-will-feature-x-be-implemented

**Comment by mrkeksi** [comment]
Duplicate to this one #2269

But yes, is this feature not relevant or why has it existed for over 5 years now?

**Comment by pedrobmarin** [comment]
Closing in favor of the prototyped https://github.com/bigbluebutton/bigbluebutton/issues/11012
