### ISSUE TITLE
Java Desksharing Cursor is Offset

### ISSUE THREAD

**Issue by perroned** [bigbluebutton/bigbluebutton#3033]
Java Desksharing Java Applet's cursor is offset at the top and bottom of the window.

At the top of the window the cursor is offset down by the height of the window frame.

At the bottom of the window the cursor escapes and displays outside the window by the same offset.

[Top](https://cloud.githubusercontent.com/assets/6475374/13409524/629d2414-df01-11e5-89c0-b0b5f009cadd.png)

![top](https://cloud.githubusercontent.com/assets/6475374/13409524/629d2414-df01-11e5-89c0-b0b5f009cadd.png)

[Bottom](https://cloud.githubusercontent.com/assets/6475374/13409527/6835f78e-df01-11e5-9da2-f5630bace928.png)

![bottom](https://cloud.githubusercontent.com/assets/6475374/13409527/6835f78e-df01-11e5-9da2-f5630bace928.png)

**Comment by ffdixon** [comment]
Instead of adding the cursor afterwards, the desktop sharing in BigBlueButton 1.1-beta (which a done by ffmpeg running from within a JAR file downloaded via JNLP) now transmits the cursor as part of the video stream.
