### ISSUE TITLE
Layout get broken when changing from "Video Chat" to any other layout

### ISSUE THREAD

**Issue by tdjac0bs** [bigbluebutton/bigbluebutton#3041]
Steps to reproduce
-> Browser1: Join as moderator
-> Browser2: Join as viewer
-> Browser1: Change layout to Video Chat
-> Browser1: Apply the layout
-> Browser2: Layout is OK
-> Browser1: Change layout to "Presentation Meeting"
-> Browser1: Apply the layout
-> Browser2: Layout get messed (attacnment)
![screenshot from 2016-03-05 14 52 11](https://cloud.githubusercontent.com/assets/2075267/13549346/e017eab2-e2e1-11e5-85b4-e93ac428ae2c.png)

In order to understand if it was a client or a publisher problem, i opened a Browser 3 (with same steps of Browser 2). When the problem happen, it happens in both browsers. So it seems to be a problem in the publisher code.

**Comment by capilkey** [comment]
I think this happens when two layouts have a large difference between them and the animations take longer than expected to finish. My thinking is that the layout is captured before the animation has finished.

**Comment by dipenpatel235** [comment]
yes for me also same issue
but if we do same steps twice then it will set properly

**Comment by ffdixon** [comment]
Closing this issue as it has been fixed in 2.0-beta.
