### ISSUE TITLE
Quick poll fails to identify the correct number of options

### ISSUE THREAD

**Issue by fcecagno** [bigbluebutton/bigbluebutton#3043]
Create a PDF file with the following content:

a) answer 1
b) answer 2
c) answer 3
d) answer 4

Upload it as the room presentation. You'll see the quick poll button with the label "A/B/C".

**Comment by ffdixon** [comment]
Did a quick test with the following PPT file using the built-in numeric and alphanumeric

[sample_polls.pdf](https://github.com/bigbluebutton/bigbluebutton/files/160699/sample_polls.pdf)
[sample_polls.pptx](https://github.com/bigbluebutton/bigbluebutton/files/160698/sample_polls.pptx)

 styles in Microsoft PowerPoint.  The detection of number of answers did work.  Can you upload the PDF you created.

**Comment by fcecagno** [comment]
[quick_poll.PDF](https://github.com/bigbluebutton/bigbluebutton/files/160707/quick_poll.PDF)

I created it using LibreOffice Impress.

**Comment by ffdixon** [comment]
Ahh .. the logic is looking for a CR/LF before each choice.  If you put any text above the four choices, the BigBlueButton client should pick up all four options.

**Comment by fcecagno** [comment]
[quick_poll.pdf](https://github.com/bigbluebutton/bigbluebutton/files/160715/quick_poll.pdf)

Tried with this one, and still get only three options.

**Comment by ffdixon** [comment]
Try putting the line "BigBlueButton rocks!" above the choices.

P.S.  BigBlueButton does rock! :-)

**Comment by fcecagno** [comment]
OK, you're right, adding something before the choices fixed the problem.

Is it the intended behaviour? That was my first test on the quick poll, and it failed (in my perspective), so I'd keep the issue opened to keep track of it and later we can improve the slide parser.

**Comment by capilkey** [comment]
This is the regular expression I used, https://github.com/bigbluebutton/bigbluebutton/blob/master/bigbluebutton-client/src/org/bigbluebutton/modules/polling/views/QuickPollButton.as#L33.

The thinking was that if you are going to have a poll you need a question and that question usually appears before the answers.
