### ISSUE TITLE
After creating a poll as a presenter, using arrow keys remove the poll from screen

### ISSUE THREAD

**Issue by GhaziTriki** [bigbluebutton/bigbluebutton#3048]
**Steps to Reproduce**
1. As a presenter create a poll.
2. Use right and left arrow keys to navigate through slides.

**Actual Behaviour**
When returning back to first or last slide the poll get cancelled.

**Expected Behavior**
The poll window should be displayed and the poll should not be cancelled.

**Comment by capilkey** [comment]
Do we want to allow people to change the slide while poll is running? Because the popup is modal the presenter really shouldn't be able to interact with the background at all. If we set the focus to the pop up when it is opened the keys won't register.
