### ISSUE TITLE
Available microphones are different depending on the browser

### ISSUE THREAD

**Issue by GhaziTriki** [bigbluebutton/bigbluebutton#3057]
The number of available microphones is different between Chrome and Firefox. While Firefox show the two available recording devices, Chrome show two additional devices "default" and "Communications".

**Firefox shows this**
![pasted image at 2016_03_16 16_41](https://cloud.githubusercontent.com/assets/4991088/13829670/86422440-ebc8-11e5-896d-5e0644fd8be8.png)

**Chrome shows this**
![pasted image at 2016_03_16 16_40](https://cloud.githubusercontent.com/assets/4991088/13829671/864b67a8-ebc8-11e5-8339-98c5fdda7d76.png)

**Comment by ffdixon** [comment]
Good catch Ghazi -- we'll take a closer look.

**Comment by mikhailnov** [comment]
On Linux the difference is even deeper. It is because Firefox uses Adobe Flash and Chrome uses Pepper Flash.

**Comment by kepstin** [comment]
Specifically on Linux, Chrome's flash talks to pulseaudio directly, but Firefox's flash talks to pulseaudio via an alsa emulation layer. The available device lists are gonna be different there, and there's not really anything we can do about it.

**Comment by mikhailnov** [comment]
To be more exact, not Firefox and Chrome flash, but Adobe's and Pepper Flash.

**Comment by ffdixon** [comment]
Your right -- that's a better distinction.

**Comment by ffdixon** [comment]
@GhaziTriki Is this still an issue with the HTML5 client?

**Comment by GhaziTriki** [comment]
Microphone selection is handled by the browser for the HTML5 client. Closing.

**Comment by capilkey** [comment]
We actually do have microphone selection in the HTML5 client. If you say "No" in the echo test you will be directed to a modal to change settings.

**Comment by GhaziTriki** [comment]
Thank you @capilkey. I missed that window. There is still a difference between browser.

Firefox On Windows 10 Looks like this

![image](https://user-images.githubusercontent.com/4991088/55821605-c9c30780-5af5-11e9-87c8-0334f448d3c8.png)

While Chrome on Windows 10 shows this

![image](https://user-images.githubusercontent.com/4991088/55821633-db0c1400-5af5-11e9-85c2-1b694f163b68.png)

**Comment by mikhailnov** [comment]
@GhaziTriki It is OK because different browsers work with sound devices in different ways, e.g. fireofx does not have a 'default device', but Chromium has it.
See e.g. https://bugs.chromium.org/p/chromium/issues/detail?id=890010 to better understand this.

**Comment by ffdixon** [comment]
Closing this issue as it related to the Flash client.  The BigBlueButton project has moved to using HTML5.
