### ISSUE TITLE
Https: Config Improvement.

### ISSUE THREAD

**Issue by hostbbb** [bigbluebutton/bigbluebutton#3059]
Would suggest freeswitch just be configured for websockets on 1 port 7443 and remove 5066 altogether.

Just adding wss to config, leaves freeswitch still listening on 5066 for possible mischief. Not needed.

Current docs say add line.
  <param name="ws-binding" value=":5066"/>
  <param name="wss-binding" value=":7443"/>

Suggest removing or commenting out 5066.

Also
http://docs.bigbluebutton.org/1.0/10install.html#before-you-install

Should reference 5066 and 7443 as possibly required like in ec2 where internal ip is eth0.  Have seen this be the issue when they overlook. these ports.

**Comment by ffdixon** [comment]
Thanks for the feedback -- we've updated the 1.0 and 1.1-beta documentation to replace the websocket line in `/opt/freeswitch/conf/vars.xml` with

    <param name="wss-binding" value=":7443"/>

The instructions already have opening port 5066 and 7443 on EC2 (http://docs.bigbluebutton.org/1.1/install.html#audio-not-working)
