### ISSUE TITLE
Exclude Webcam from session recording

### ISSUE THREAD

**Issue by mujahed1987** [bigbluebutton/bigbluebutton#3065]
Hello,
I am deploying BigBlueButton to a client who whould like not to include the webcam with the recording of the session. Is this possible by changing some values in the BBB's files?
Also can you add it as an option for future

**Comment by kepstin** [comment]
This is really more of a support request than an issue at the moment - the mailing lists would have probably been a more appropriate venue for the question: http://bigbluebutton.org/support/

You can disable recording webcam streams server-wide by editing the file `/usr/share/red5/webapps/video/WEB-INF/red5-web.xml` and setting the property `recordVideoStream` to `false`.

**Comment by ritzalam** [comment]
Test if the recording processing is going to break as there will be events recorded in events.xml but no file to process.

**Comment by mujahed1987** [comment]
Hello @kepstin 
First I am sorry for posting my question here. I tried to join the mailing lists two days ago but nobody have accepted my request till now, also I asked  blindsidenetworks to help me with this by using contact form and nobody replied.
I would like to thank you for your answer I will give it a try and I will keep in mind @ritzalam 's note and I will share my results.
