### ISSUE TITLE
Change location of "Change Layout" from footer to top 

### ISSUE THREAD

**Issue by dipenpatel235** [bigbluebutton/bigbluebutton#3066]
Hello..
how can i change location of "Change Layout" from footer to top ?

Thanks
Dipen Patel

**Comment by ffdixon** [comment]
Hi Dipen,

This isn't an issue (or bug) with BigBlueButton; rather, a request for information.  Please post such requests to our bigbluebutton-dev mailing list

   https://groups.google.com/forum/#!forum/bigbluebutton-dev

and the community will help you there. If, in helping you, we determine there is an issue with BigBlueButton itself that needs to be fixed, we'll open an new issue here.
