### ISSUE TITLE
Enable parallel processing of recordings

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#3067]
Currently, raw recordings are processed sequentially into playback files.

On servers with large number of CPU cores, such as 8 or greater, if the record processing could occur in parallel, BigBlueButton server could take advantage of the additional CPU cores to process recordings faster.

**Comment by ffdixon** [comment]
In BigBlueButton 2.0, the archiving, processing, and publishing phases all have their own threads.  While this isn't processing recordings sequentially, it does speed up the display of a recording.

As soon as the processing thread finished processing a recording and it moves onto the next recording to process, the publish thread can publish the recording.

Previously, everything ran in a single thread, and all the processing had to finish before any recordings would publish.

**Comment by cod3r0k** [comment]
> In BigBlueButton 2.0, the archiving, processing, and publishing phases all have their own threads. While this isn't processing recordings sequentially, it does speed up the display of a recording.
> 
> As soon as the processing thread finished processing a recording and it moves onto the next recording to process, the publish thread can publish the recording.
> 
> Previously, everything ran in a single thread, and all the processing had to finish before any recordings would publish.

BBB 2.2.23 is running on one thread? Can we extend it to multi thread to use all the cpu cores?

**Comment by pedrobmarin** [comment]
Closing since a big chunk of this was tackled down by https://github.com/bigbluebutton/bigbluebutton/pull/4487 and https://github.com/bigbluebutton/bigbluebutton/pull/11589 . We can revive this subject as new challenges arrive.
