### ISSUE TITLE
Internal check recognizing Edge browser as Chrome

### ISSUE THREAD

**Issue by akiwenziec** [bigbluebutton/bigbluebutton#3068]
BBB internal check is recognizing Edge browser as Chrome 
![edgeaschrome](https://cloud.githubusercontent.com/assets/18176998/14158564/bfe9319e-f69e-11e5-870f-b3f9304d1f0f.PNG)

**Comment by hostbbb** [comment]
does webtrc audio work?   this means deskshare should be disabled as well

**Comment by ffdixon** [comment]
Currently, deskshare is incorrectly disabled as well.

![image](https://cloud.githubusercontent.com/assets/290351/14180553/8e67360a-f731-11e5-95e6-2e6ab85b8dd3.png)

Marking this as needing to be fixed before we move to BigBlueButton 1.0-RC.

**Comment by kepstin** [comment]
The desktop sharing is correctly disabled (although possibly for the wrong reason). Edge does not support plugins (other than the built-in flash), so it cannot run Java applets.

We just need to update the check to explicitly match Edge so we can put the correct browser name in the error message.
