### ISSUE TITLE
User can type in chat box when the client is reconnecting

### ISSUE THREAD

**Issue by GhaziTriki** [bigbluebutton/bigbluebutton#3069]
When the user is typing a message, then network connection is lost, the user can still type in the chat box while the reconnection popup is being displayed. Shouldn't the focus be out of the chatbox in that case?

**Comment by ffdixon** [comment]
Since the improvements to the reconnect, I did a test and the user is able to type when one of the RTMP connections are lost

![reconnect2](https://user-images.githubusercontent.com/290351/41502763-ac3cf6bc-718f-11e8-8361-3daed123a422.gif)

**Comment by GhaziTriki** [comment]
Fixed in #5776
