### ISSUE TITLE
Support for impress.js

### ISSUE THREAD

**Issue by mkpelletier** [bigbluebutton/bigbluebutton#3085]
Hello All,

I seem to recall this question having been posed before, but I cannot find it in the issues anywhere.  Perhaps it was on another project.  My apologies if this has already been posed.

Has any consideration been given to including support for Impress.js in the presentation window?  Alternatively, is there some other method for displaying animations and transitions?

**Comment by ffdixon** [comment]
No plans at the moment to use something like impress.js -- as it's an HTML5 framework, it would need to land in the HTML5 client. 

Whereas impress.js is for a stand-alone presentation, BigBlueButton is for synchronized presentations.  It would take (quite) a bit of work to synchronize the impress.js events across BigBlueButton clients.

**Comment by hex-m** [comment]
There is another issues about HTML-presentations: https://github.com/bigbluebutton/bigbluebutton/issues/9235
