### ISSUE TITLE
Url file upload fails half on url parameters

### ISSUE THREAD

**Issue by ReimarBauer** [bigbluebutton/bigbluebutton#3091]
If one for example trys to submit urls of files which need parameters 

http://www.fz-juelich.de/SharedDocs/organisationsplaene/artikel/Gesamtorganisationsplan.pdf?__blob=publicationFile

the file becomes stored as 
0343240q23123e24325235.pdf?__blob=publicationFile 

and can't be converted

**Comment by GhaziTriki** [comment]
@ReimarBauer You can now provide the `filename` property.
http://docs.bigbluebutton.org/dev/api.html#pre-upload-slides
