### ISSUE TITLE
Missing on transifex: "You can close this tab by using the key combination control+E."

### ISSUE THREAD

**Issue by KissDaniGH** [bigbluebutton/bigbluebutton#3093]
Hi
there is a message when opening a new private chat "You can close this tab by using the key combination control+E." but can't find it on  transifex.com. Please insert it.

Regards, Daniel

**Comment by daronco** [comment]
I've just translated this to pt-br, it is there. Search in transifex for "You can close this tab by using the key combination", the last part ("control+E") is added dynamically.

**Comment by KissDaniGH** [comment]
yes you r right. it's is english on demo.bbb

**Comment by capilkey** [comment]
The string should have been added after I merged in this PR, https://github.com/bigbluebutton/bigbluebutton/pull/3094
