### ISSUE TITLE
Missing strings "yes", "no" (anwsers for logout confirm)

### ISSUE THREAD

**Issue by KissDaniGH** [bigbluebutton/bigbluebutton#3095]
Hi can't localize "yes" and "no" strings the answers of logout confirmation

**Comment by ffdixon** [comment]
Theses string are properly localized in BigBlueButton 1.1-beta.

![localization](https://cloud.githubusercontent.com/assets/290351/21966724/dc1e6aa4-db46-11e6-9a86-826cc3159e99.PNG)
