### ISSUE TITLE
The private chat lock doesn't always take effect

### ISSUE THREAD

**Issue by capilkey** [bigbluebutton/bigbluebutton#3106]
Steps to reproduce:

1. Join from a viewer and moderator
2. Lock the private chat
3. Reload the viewer client

Actual result:
The viewer client can interact with the user list in the "Options" tab.

Expected result:
The user list should be disabled just like when the private chat lock is initially set.

Reported here, https://groups.google.com/d/msg/bigbluebutton-dev/5W9DS53hwH8/7aSTl7-SAQAJ.

Side note: Even when the list is disabled a user can still use the arrow keys to navigate and open a private chat tab.

**Comment by ffdixon** [comment]
Fixed in 

  https://github.com/bigbluebutton/bigbluebutton/pull/3120
