### ISSUE TITLE
Can't install bbb with vagrant

### ISSUE THREAD

**Issue by egorzot** [bigbluebutton/bigbluebutton#3108]
I try to install bbb with your Vagrantfile, but I have this message from Vagrant:

> Box 'RIADVICE\bigbluebutton-dev'  could not be found.

Maybe there is another box?

**Comment by ffdixon** [comment]
What vagrant file are you referring to -- can you post a link?

**Comment by egorzot** [comment]
A [Vagrantfile](https://github.com/bigbluebutton/bigbluebutton/blob/master/Vagrantfile) in root folder of the official BigBlueButton repo on GitHub

**Comment by ffdixon** [comment]
Hmm ... looks like that file was incorrectly committed.  We've since deleted it.  The best way to install BigBlueButton is to follow the steps at 

    http://docs.bigbluebutton.org/install/install.html

We've found that when we provide scripts, they invariable don't work,
