### ISSUE TITLE
Cannot type on the presentation slide in non-latin scripts

### ISSUE THREAD

**Issue by mkpelletier** [bigbluebutton/bigbluebutton#3115]
Although the chat window appears to support a variety of scripts and languages, the slide annotation tools do not allow one to type in a non-latin script.  Does this have to do with Red5 limitations? Will this be corrected in the upcoming 1.0 release?

**Comment by ffdixon** [comment]
This is a known bug, see
  
   https://github.com/bigbluebutton/bigbluebutton/issues/2708

As the discussion in the above issue states, we're not working on this bug for 1.0.0.  However, we do intent to enable text annotation to support non-latin text in the future.

For now, the workaround is to paste in the non-latin text into the text annotation field.

**Comment by mkpelletier** [comment]
Thanks, Fred!  At least I can paste it in.
