### ISSUE TITLE
Playback issues: supported browsers

### ISSUE THREAD

**Issue by mschipperheyn** [bigbluebutton/bigbluebutton#3116]
The playback 0.81 works with Chrome, Firefox and Edge. On Safari, I see the slides, but there is no interactivity (0.9 recordings). 

Playback 0.9.0 works with Chrome, FireFox and Edge. On Safari, it just hangs with an eternal loading indicator. The documentation suggests that basic functionality is available on Safari. Perhaps this has been fixed in 1.0, but on 0.9 this is not the case.

The documentation doesn't seem to incorporate support for Edge yet.

**Comment by capilkey** [comment]
Apple doesn't support open codecs. Until they do it isn't possible to provide video/audio, in an open-source project, for Safari.

If you need Safari support as a commercial company you can purchase a license from MPEG-LA and change the recording scripts to create h264 video.

We could probably add Edge to the list of supported browsers though.

**Comment by kepstin** [comment]
According to https://en.wikipedia.org/wiki/HTML5_Audio#Supported_audio_coding_formats and https://en.wikipedia.org/wiki/HTML5_video#Browser_support current versions of Edge don't support either the VP8 video codec or Vorbis audio codec that BigBlueButton recordings use by default. It's possible that Edge might be able to play it on some computers, if you have installed third-party decoders.
As a result, I don't think we can list Edge as a supported browser.

**Comment by arku31** [comment]
How about setting message about unsupporting Safari&IE. Spent 3 hours to got this :(

**Comment by ffdixon** [comment]
BigBlueButton already puts the following message at the bottom of each recording when the user attempts to playback
 
   Use Mozilla Firefox or Google Chrome to play this recording.

**Comment by ffdixon** [comment]
I think we should follow @arku31 comments and put a message that the browser is unsupported.

**Comment by ffdixon** [comment]
Playback of recordings now supported on iOS, see https://github.com/bigbluebutton/bigbluebutton/releases/tag/2.2-beta-23
