### ISSUE TITLE
Ubuntu 16.04 build

### ISSUE THREAD

**Issue by mikhailnov** [bigbluebutton/bigbluebutton#3118]
Will you build BBB 1.0 for Ubuntu 16.04?

**Comment by ffdixon** [comment]
BigBlueButton 1.0-RC (soon to be 1.0) is on Ubuntu 14.04 64-bit.  However, we are planning to put BigBlueButton 1.1 on Ubuntu 16.04.  See 

   http://bigbluebutton.org/2016/05/03/bigbluebutton-summit-viii-ottawa-ontario-canada/

**Comment by ffdixon** [comment]
We are working on Ubuntu 16.04 64-bit packaging for BigBlueButton 1.1-dev.  We are now testing this on http://demo.bigbluebutton.org/

**Comment by ffdixon** [comment]
Implemented in BigBlueButton 1.1-dev.  You can see the install instructions here:

   http://docs.bigbluebutton.org/1.1/install.html

(the apt-get URL will be updated when 1.1-beta releases)
