### ISSUE TITLE
Bug with 'send_whiteboard_shape_message' for the Text Shape objects

### ISSUE THREAD

**Issue by OZhurbenko** [bigbluebutton/bigbluebutton#3170]
There are 3 types of messages for the text shape:
1. With the shape.status == 'textCreated' - when you created an initial box for the shape and haven't started typing yet.
2. With the shape.status == 'textEdited' - when you are typing the text, but you haven't finished yet.
3. With the shape.status == 'textPublished' - when you finished typing the text, clicked somewhere on the whiteboard and the text you entered becomes your final version which can't be modified later.

Steps to reproduce the problem:
1. Log into the Flash client as a presenter
2. Draw the box for the Text shape. Write some text if you want. Don't click anywhere else. ('textCreated' is sent and if you typed something than textEdited is sent as well)
3. Click 'Clear All Annotations' or 'Undo Annotation'. (if you click 'Undo Annotation - a box with font-sizes and colors for the text still hangs there, but that's another bug). 
4. Click elsewhere on the whiteboard. At this moment 'textPublished' is sent, which **shouldn't happen**, since you just removed the shape in the step 3.

**Comment by capilkey** [comment]
Fixed with 2.0 whiteboard rewrite.
