### ISSUE TITLE
pdf2swf not converting some Chinese fonts

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#3176]
It looks like the default installation of pdf2swf may need some additional Chinese fonts. The sample PDF below

[经皮椎体后凸成形术围手术期并发症及防治的研究进展_余博臣.pdf](https://github.com/bigbluebutton/bigbluebutton/files/314348/_.pdf)

renders correctly in Acrobat on the desktop, but when uploading it to BigBlueButton 1.0 all the Chinese characters are missing in the resulting SWF file.

Reported in

   https://groups.google.com/d/msg/bigbluebutton-users/Y0vpsB4bmyc/KfJ-m8b6BAAJ

**Comment by kepstin** [comment]
This is very strange… A pdf file should normally have the font embedded? I guess that might not always be the case.

We cover in the FAQ: http://docs.bigbluebutton.org/support/faq.html#i-uploaded-a-document-but-some-fonts-are-missing-after-conversion that you might need to install extra fonts for word or powerpoint documents.
Could just add a note saying "and pdfs that don't have embedded fonts" and also list some chinese font packages.

**Comment by dfeng99** [comment]
I've tried the file on my test server, it doesn't work either, but after that I copied the content and paste it to my Mac's Pages editor then save it as another pdf file and upload it again. all characters displayed well.

**Comment by mikhailnov** [comment]
This PDF is produced against PDF standart and embeded fonts are unreadable.
Not a bug in pdf2swf.
https://www.pdf-online.com/osa/validate.aspx
File	_.pdf
Compliance	pdf1.6
Result	Document does not conform to PDF/A.
Details	
Validating file "_.pdf" for conformance level pdf1.6
The embedded font program 'E-BZ+ZLKCQZ-1' cannot be read.
The embedded font program 'DY2+ZLKCQf-8' cannot be read.
The embedded font program 'SSJ0+ZLKCQZ-3' cannot be read.
The embedded font program 'KTJ0+ZLKCQb-4' cannot be read.
The embedded font program 'E-HZ+ZLKCQc-6' cannot be read.
The embedded font program 'SSJ0+ZLKCQf-7' cannot be read.
The embedded font program 'DY1+ZLKCQZ-2' cannot be read.
The document does not conform to the requested standard.
The document contains fonts without embedded font programs or encoding information (CMAPs).
Done.

**Comment by mikhailnov** [comment]
It seems that the PDF does have information about how the letters should like (glyphs etc.), but fonts are mebeded incorrectly, and you do not have chinese fonts/locale installed on Linux server so that the document could be rendered into an image correctly.

**Comment by ffdixon** [comment]
Thanks @mikhailnov.  We would be thankful if anyone could provide steps to install the Chinese fonts on a BigBlueButton server so the fonts do render correctly in this document.

**Comment by dfeng99** [comment]
I have[ DroidSans and DroidSerif fonts](https://en.wikipedia.org/wiki/Droid_fonts#Typefaces) installed in folder /usr/share/fonts/truetype. Other open source Chinese font can be found [here](http://wenq.org/wqy2/index.cgi) but not tested yet.

**Comment by ffdixon** [comment]
Hi @dfeng99, did the document convert correctly after you installed the fonts?

Regards,... Fred

**Comment by dfeng99** [comment]
No, It can’t be displayed corrected. As my previous post, I need to do copy and paste to other PDF generator to regenerate the document then it can be displayed correctly. I'll agree with mikhailnov, it may be the document issue of itself.

**Comment by ffdixon** [comment]
Closing this issue as we are moving to an HTML5 client.
