### ISSUE TITLE
Locked viewers minimize/maximize windows

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#3188]
When a moderator locks a viewers's layout, the viewer can still minimize/maximize windows.

**Comment by tdj-br** [comment]
I think it's possible to fix binding the showControls attribute of CustomMdiWindow to the opposite of locked state.

**Comment by tdjac0bs** [comment]
When locked, the user is not able to "maximize/minimize" anymore.

Unlocked:
![image](https://user-images.githubusercontent.com/2075267/49234495-483cc980-f3df-11e8-9732-49ab2d2962be.png)


Locked:
![image](https://user-images.githubusercontent.com/2075267/49234344-057af180-f3df-11e8-92e7-5a07b39f5e91.png)
