### ISSUE TITLE
"Load layouts from a file" button not working

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#3190]
After enabling the layout controls in BigBlueButton 1.0, the "Load layouts from a file" button does not work.

(This feature has been disabled for a few years, so the code has not been updated with other parts of the layout.)

**Comment by GhaziTriki** [comment]
This issue should be marked to be tested for v2.0 as this feature is back.

**Comment by ffdixon** [comment]
Closing this issue as we are moving to an HTML5 client.
