### ISSUE TITLE
Missing JAR, bbb-common-message-0.0.18-SNAPSHOT.jar

### ISSUE THREAD

**Issue by proqress** [bigbluebutton/bigbluebutton#3192]
While building project gradle searches for _bbb-common-message-0.0.18-SNAPSHOT.jar_. This file can't be found on GitHub. Using older jar _bbb-common-message-0.0.17.jar_ didn't fix the issue.

**Comment by ffdixon** [comment]
Can you confirm that your using the source code tagged for branch tagged v1.0.x-release (not master).  See  

http://docs.bigbluebutton.org/install/setup.html#checking-out-the-source

**Comment by ritzalam** [comment]
You need to build it.

cd bbb-commons-message
sbt publish
sbt publishLocal

**Comment by proqress** [comment]
Switched to _v1.0.x-release_ branch. No more common-message module error. Now _org.apache.ivy.plugins.resolver.URLResolver_ couldn't be found. Build has failed.

**Comment by ritzalam** [comment]
Have you resolved the error? Which project are you building?

Which development environment did you install? 1.x branch?

**Comment by proqress** [comment]
I resolved the error. Problem was: OS is i686. Switched to x86_64 and builds without any error.
