### ISSUE TITLE
Better division of project

### ISSUE THREAD

**Issue by mansa-dev** [bigbluebutton/bigbluebutton#3194]
You guys did an amazing job with this project.

Can you please consider dividing the project into smaller sub projects. Like different repository for `html5-client` another for `docs`. Big Blue Button is already an organization it will be easy to maintain.

Cloning this project with single branch takes about `400 MB`.

**Comment by ffdixon** [comment]
Hi Mansa,

Hi Mansa,

Thanks for the kind words.  The real size is not due not to code, but rather some large legacy media files were used for testing a few years ago.

There are ways to reduce the size of a GitHub repo -- we could remove all the media files, but it would cause everyone to have to rebase and prevent them from pushing their changes until they clone or rebase.
