### ISSUE TITLE
can t access from android client to bigbluebutton server 1.0 server

### ISSUE THREAD

**Issue by ghost** [bigbluebutton/bigbluebutton#3199]
I build bbb server on ubuntu and am going to access it from android client, but cannot be connected well.

I tried two methods. However, neither is connected.
1. access "http://<ip addr>/demo/mobile.jsp" by a browser
2. input "AAA" into a URL in android clients and click connect button

Each result is as follows.
1. android client starts, and a message is displayed. "Can't join the meeting"
2. A message is displayed when I tap the drop-down list of the meeting "This server doesn't provide mobile access"

I performed the installation of the server in reference to the following URLs.　complete chapter "Installing BigBlueButton 1.0".

http://docs.bigbluebutton.org/install/install.html#installing-bigbluebutton-10

What should mobile do to access it? If there is insufficient setting, please tell me.
Is there not the document described about it?

**Comment by ffdixon** [comment]
Hi,

The current android client is quite old and unsupported.  We're focusing our efforts on the HTML5 client, see

  http://docs.bigbluebutton.org/html/html5-overview.html

The HTML5 client is under active development and we're working towards having a update to the HTML5 client available with BigBlueButton 1.1-dev (also under development). For more information, see

  https://groups.google.com/d/msg/bigbluebutton-dev/2OLdUbi2K_w/1pzOZoppAwAJ

**Comment by aokutemaruino** [comment]
@ffdixon Thank you for an answer!

I intend to try HTML5 client of v1.1-dev.
I appreciate your fantastic job!

Thank you!

**Comment by mikhailnov** [comment]
you can use Puffin browser to make the flash client work on android

**Comment by faisalrahman01** [comment]
I installed HTML5 client on BBB server but not working from chrome in Mobile. But loading Mic and webcam using firefox. But camera seems opened while it's not visible by participants.

**Comment by ffdixon** [comment]
Can you try out the latest build of the HTML5 client at

   https://test.bigbluebutton.org/

and let us know if it works.  We're currently testing a set of updates to the HTML5 client for video support.
