### ISSUE TITLE
Refactor OutMessage serialization in akka-bbb-apps

### ISSUE THREAD

**Issue by tdjac0bs** [bigbluebutton/bigbluebutton#3201]
There is too much duplicated code in the MessageSenderActor.scala

Possible improvements

1 - All the [OutMessages](https://github.com/bigbluebutton/bigbluebutton/blob/master/akka-bbb-apps/src/main/scala/org/bigbluebutton/core/api/OutMessages.scala) inherits from IOutMessage, but in message converters they are organized in types (ChatMessage, MeetingMessage, PresentationMessage, SharedNotesMessage, UsersMessage, WhiteboardMessage, etc). Create interfaces for each message type, to help handling the messages better.

2 - In the [MessageSenderActor](https://github.com/bigbluebutton/bigbluebutton/blob/master/akka-bbb-apps/src/main/scala/org/bigbluebutton/core/MessageSenderActor.scala), instead of having multiple handle methods, use one handle method for each type of message, i.e.: 

```
private def handleUsersMessage(msg: IUserOutMessageMessage) {
    val json = UsersMessageToJsonConverter.toJson(msg);
    service.send(MessagingConstants.FROM_USERS_CHANNEL, json)
  }
```

@ritzalam do you see any problem doing this refactor?

**Comment by ritzalam** [comment]
We are trying to come up with a better way to convert messages from/to JSON. Anton is working on that for 2.x

**Comment by ritzalam** [comment]
Conversion is now done auto-magically using jackson.

https://github.com/bigbluebutton/bigbluebutton/blob/v2.0.x-release/bbb-common-message/src/main/scala/org/bigbluebutton/common2/util/JsonUtil.scala#L25
