### ISSUE TITLE
The bbb-video and bbb-voice projects have 404'd dependencies

### ISSUE THREAD

**Issue by capilkey** [bigbluebutton/bigbluebutton#3215]
The 1.0 version of the build.gradle files for bbb-video and bbb-voice reference the old Google Code repositories for some of the dependencies. The dependencies can't be downloaded anymore so the it isn't possible to build those projects.

The URLs for the dependencies need to be changed and they possibly need to be hosted somewhere else.

I believe the problem has been fixed in the version of those projects on master.

The original mailing list discussion that brought the problem to light can be found here, https://groups.google.com/d/msg/bigbluebutton-dev/PBw0jcIbFfc/Wp1qk9IUCQAJ

**Comment by ffdixon** [comment]
@ritzalam, is this still an issue in BigBlueButton 1.1-beta?
