### ISSUE TITLE
Webcams duplicated after auto-reconnect

### ISSUE THREAD

**Issue by zach-chai** [bigbluebutton/bigbluebutton#3250]
All the webcams in BigBlueButton were duplicated after reconnecting on Chrome

![screenshot](https://cloud.githubusercontent.com/assets/6678182/17340533/88d66e60-58be-11e6-8e61-3614bb0c2b7f.png)

**Comment by ritzalam** [comment]
I can't reproduce this on Firefox.

I shared 2 webcams on Chrome and view them on Firefox. Using NetLimiter, kill connections for Firefox. Webcams still displayed correctly on Firefox.

**Comment by ritzalam** [comment]
I'm able to reproduce on Chrome.

Have 2 FF browsers open, shared webcams, and Chrome viewing both webcams.

Using NetLimiter, kill connection to bbb-video and then while reconnecting, kill connection to bbb-apps. When Chrome finishes reconnecting to both bbb-video and bbb-apps, webcams windows are duplicated.
