### ISSUE TITLE
When client opens with a layout other than default the close captioning window is shown

### ISSUE THREAD

**Issue by jfederico** [bigbluebutton/bigbluebutton#3260]
This is an edge case that can only be reproduced when using a custom config.xml when joining.
![image](https://cloud.githubusercontent.com/assets/578359/17419531/e41c5b82-5a6b-11e6-9065-2b23dbdf54b7.png)

**Comment by jfederico** [comment]
Fixed. Waiting to be merged

**Comment by capilkey** [comment]
Should be fixed in https://github.com/bigbluebutton/bigbluebutton/pull/3259 already

**Comment by jfederico** [comment]
Oh. I didn't see that. I'll cancel the pull request
