### ISSUE TITLE
Internal hypertext links in uploaded document do not work

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#3272]
When saving a .PPT (or .PPTX) document as PDF using PowerPoint on Windows, links to external URLs are clickable in BigBlueButton.  Clicking such a link will open the URL in a new browser tab.

However, the links in your document are internal: they are linking to specific pages in the document.  After uploading to BigBlueButton (and conversion into SWF files by pdf2swf), clicking an internal links do not cause the BigBlueButton client to jump to the specific page in the presentation.

**Comment by kepstin** [comment]
This is probably something that we are not going to support. Links that go from one page to another in the document would interfere with the presentation controls - it would break our concept of "everyone sees the same thing" if we allow non-presenters to interact with them.

Detecting document-internal links, and handling them (for presenter only) to allow jumping between pages would be a significant amount of non-trivial work, probably not worth the effort at this point.

**Comment by tdj-br** [comment]
Will be nice to investigate on that.

**Comment by hex-m** [comment]
This issue is about the legacy Flash-Client. Flash will be deprecated soon (end of 2020) by Adobe and I assume we can close this ticket.

The HTML5 client supports neither internal nor external links. This is tracked here: https://github.com/bigbluebutton/bigbluebutton/issues/6708
