### ISSUE TITLE
Enhance preupload of presentation to specify a default presentation

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#3298]
When using the preupload of presentation capability to upload more than one presentation on the 'create' API request, after all the presentations have processed it is currently non-deterministic which one gets displayed.  

Add a parameter to the preupload to specify which presentation to display as default after all the presentations have processed.

**Comment by GhaziTriki** [comment]
Linked to https://github.com/bigbluebutton/bigbluebutton/issues/2304

The first document is the default one by convention. http://docs.bigbluebutton.org/dev/api.html#pre-upload-slides
