### ISSUE TITLE
recodring raw file was not generated

### ISSUE THREAD

**Issue by dipenpatel235** [bigbluebutton/bigbluebutton#3299]
hello...
when i have started big blue buttton webinar then i have clicked on record button
So now using bbb-record --list i can see that meeting id.
But not able to watch that recording.

When i did
bbb-record --rebuild 4ea6e9874864d2d05a451e963f1c88d615b1bb89-1471696983334
then i get bellow message
Raw files for 4ea6e9874864d2d05a451e963f1c88d615b1bb89-1471696983334 do not exist, can't rebuild

So what is reason for not generated Raw File ?

Thanks

**Comment by ffdixon** [comment]
Can you post this to our bigbluebutton-setup mailing list, see
   
   https://groups.google.com/forum/#!forum/bigbluebutton-setup

and we'll help you there.  If it turns out there is an bug in BigBlueButton, we'll open an issue here to track and fix.
