### ISSUE TITLE
Cannot integrate BBB with Moodle

### ISSUE THREAD

**Issue by karl-johan-grahn** [bigbluebutton/bigbluebutton#3310]
Hi,

I tried to join the BigBlueButton-Setup group but was denied by a group moderator, so am forced to post my question here.

I'm setting up a BigBlueButton 1.0 server and I've run into a problem getting Moodle to talk to it over SSL. I'm stuck and would appreciate any/all help.

We're using these software versions:
* BigBlueButton 1.0.0
* Moodle 3.1.1+ (Build: 20160811)
* BigBlueButtonBN plugin 2.1.1 version 2016051905

I've enabled SSL on the BBB server per http://docs.bigbluebutton.org/install/install.html#configuring-https-on-bigbluebutton, and it seems to work as expected. The correct certificates are being used.

From Moodle, I try adding a new BigBlueButtonBN to Topic 1.

I enter a virtual classroom name "TEST" and click "Save and return to course", and get:

    Unable to connect. Please check the url of the BigBlueButton server AND check to see if the BigBlueButton server is running.

    More information about this error
    Debug info:
    Error code: general_error_unable_connect
    Stack trace:

        line 495 of /lib/setuplib.php: moodle_exception thrown
        line 54 of /mod/bigbluebuttonbn/mod_form.php: call to print_error()
        line 201 of /lib/formslib.php: call to mod_bigbluebuttonbn_mod_form->definition()
        line 95 of /course/moodleform_mod.php: call to moodleform->__construct()
        line 255 of /course/modedit.php: call to moodleform_mod->__construct()

I click "Continue" and get:

    Section error!

    More information about this error
    Debug info:
    Error code: sectionerror
    Stack trace:

        line 495 of /lib/setuplib.php: moodle_exception thrown
        line 26 of /admin/settings.php: call to print_error()

Output of bbb-conf --check (server name changed):

    BigBlueButton Server 1.0.0 (1058)
                        Kernel version: 4.6.3-x86_64-linode70
                          Distribution: Ubuntu 14.04.5 LTS (64-bit)
                                Memory: 3950 MB

    /var/www/bigbluebutton/client/conf/config.xml (bbb-client)
                    Port test (tunnel): ourserver.xyz
                                  Red5: ourserver.xyz
        <logging enabled="true" target="trace" level="info" format="{dateUTC} {time} :: {name} :: [{logLevel}] {message}" uri="https:
    ourserver.xyz
    ourserver.xyz
    ourserver.xyz
    ourserver.xyz
    ourserver.xyz
    ourserver.xyz
    ourserver.xyz
    ourserver.xyz
    ourserver.xyz
    ourserver.xyz
                  useWebrtcIfAvailable: true

    /opt/freeswitch/conf/sip_profiles/external.xml (FreeSWITCH)
                        websocket port: 5066
                        WebRTC enabled: true

    /etc/nginx/sites-available/bigbluebutton (nginx)
                           server name: ourserver.xyz
                                  port: 80
                                  port: 443 ssl
                        bbb-client dir: /var/www/bigbluebutton

    /var/lib/tomcat7/webapps/bigbluebutton/WEB-INF/classes/bigbluebutton.properties (bbb-web)
                          bbb-web host: ourserver.xyz

    /var/www/bigbluebutton/check/conf/config.xml (client check)
                          client check: ourserver.xyz

    /usr/share/red5/webapps/bigbluebutton/WEB-INF/red5-web.xml (red5)
                      voice conference: FreeSWITCH
                         capture video: true
                       capture desktop: true

    /usr/local/bigbluebutton/core/scripts/bigbluebutton.yml (record and playback)
                         playback host: ourserver.xyz

    ** Potential problems described below **
    # IP does not match:
    #                           IP from ifconfig: 123.456.789.10
    #   /etc/nginx/sites-available/bigbluebutton: ourserver.xyz
    # Warning: The client self check is installed and accessible from:
    #
    #    https://ourserver.xyz/check
    #

Connecting directly to https://ourserver.xyz/bigbluebutton/api with a browser returns:
```
<response><returncode>SUCCESS</returncode><version>1.0</version></response>
```

Running this command from the Moodle server returns:
    # wget -O - --quiet https://ourserver.xyz/bigbluebutton/api; echo
```
<response><returncode>SUCCESS</returncode><version>1.0</version></response>
```

Any and all help appreciated!

**Comment by ffdixon** [comment]
Can you install the BigBlueButton API demos, see

   http://docs.bigbluebutton.org/install/install.html#install-api-demos

and let us know if you can connect.  

Regarding joining bigbluebutton-setup, you need to answer a question during the join request; otherwise, we can't tell your request form a spam bot.

**Comment by karl-johan-grahn** [comment]
Demo works just fine seemingly without any problems whatsoever. I can start a conference and add annotations, chat, and share my screen, all over https. Maybe it is something wrong with Moodle or the plugin instead?

**Comment by hostbbb** [comment]
as a workaround try in moodle using just http:// and not https:// in config of bigbluebutton url in moodle admin.  I saw this a few months back on a moodle install.  not sure what the issue was but it worked.

**Comment by karl-johan-grahn** [comment]
Yesterday I got help from Fred Dixon investigating our problem and we are quite certain it is the Moodle server that is the culprit here. All settings and logs looked as expected, but when I tried accessing the course multiple times, sometimes the meeting would start, sometimes not. I tried it again today and same behavior, sometimes the course will enable me to start a conference, sometimes not. So it is most probably a bad network or bad server that is running our Moodle installation.

**Comment by Maryana230515** [comment]
Teaching   methods are changing rapidly. The technology has helped the development of   learning, and as a result, the class, pupils and the roles of instructors /   trainers have completely changed. Consider another option for conducting   modern classes - this is Createwebinar.com (https://createwebinar.com/) - a   convenient control panel based on BigBlueButton, which allows users to create   and host webinars. The features of the panel that distinguish it among others   include managing web seminar settings directly from the site, managing the   address book and creating separate groups of contacts, configuring the web   room, mailing templates for sending and SMTP server, web recording and   playback of web- seminar, three different types of participants' access (open   to all participants, closed list of participants, confirmation of   participation is required), possibility to share webinar record with Vimeo   and Youtube, download webinars in mp4 format, send invitations automatically   participants of the webinar, etc
--
