### ISSUE TITLE
Converting all traffic from HTTP to HTTPS causes errors

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#3345]
See discussion in this thread

  https://groups.google.com/d/msg/bigbluebutton-setup/YhhKnkfcdzk/4zi01QFPGAAJ

Looks like the traffic for RTMPT is still using HTTP (not HTTPS) in a default upgrade of BigBlueButton to use SSL.

Need to dig deeper into client/server modifications to move away from HTTP for RTMPT (RTMP Tunneling).

**Comment by tdjac0bs** [comment]
Just for reference, in MAC, to force the usage of tunneled connection I've used this command:

```
(sudo pfctl -sr 2>/dev/null; echo "block drop quick on en0 proto tcp from any to any port = 1935") | sudo pfctl -f - 2>/dev/null;

sudo pfctl -e
```

Going over the code to fix this issue. Just confirmed that it's using HTTP instead of HTTPS for tunneled connections.

**Comment by ffdixon** [comment]
Closing this issue as we are moving to an HTML5 client.
