### ISSUE TITLE
Main things in education

### ISSUE THREAD

**Issue by SergeyAndreevich** [bigbluebutton/bigbluebutton#3352]
Friends, why you finally cant create video and audio player (video and audio playing) in whiteboard? 
In the world of information there are 3 main format. Text, video and audio. Why teacher can only show text? Why you cant create showing audio, video and give us to teach normal lessons, interesting lessons. Why only text (pdf) and sharing? how can teacher show audio or video to a student? Using sharing desctop? It is a lot of trafic. And how teacher's students will hear? I was waiting for it for about 4 years. Why Adoby captivate, and a lot of others have it but you dont? How long should we wait this baisic, main functions? 
Thank you.

**Comment by ffdixon** [comment]
Hi Sergey,

Thanks for your feedback.  Obviously, we can't implement every feature in a single release.  We have to prioritize.  For information on how we set priorities for each release, see

   http://docs.bigbluebutton.org/support/faq.html#when-will-feature-x-be-implemented
