### ISSUE TITLE
return Forbidden Error in ubuntu 14.04

### ISSUE THREAD

**Issue by kartikdanidhariya** [bigbluebutton/bigbluebutton#3387]
hi,
i follow steps from this link 
http://docs.bigbluebutton.org/install/install.html
after in steps 9 when i write 

sudo bbb-conf --check

it return error like

Forbidden
You don't have permission to access /bigbluebutton/api on this server.
Apache/2.4.7 (Ubuntu) Server at 192.168.1.14 Port 80

how can i solve this error plz help!

**Comment by ffdixon** [comment]
BigBlueButton does not install Apache?  Double check the Before you Install requirements.  It looks like you have a resource conflict.  To understand more why its important that port 80 is free, see

   http://docs.bigbluebutton.org/support/faq.html#we-recommend-running-bigbluebutton-on-port-80
