### ISSUE TITLE
Poll results data

### ISSUE THREAD

**Issue by osteoboon** [bigbluebutton/bigbluebutton#3398]
I think I'm using BBB version 1.0 but I'm not sure how to discover the version. I found [bbb-conf --version documentation](http://docs.bigbluebutton.org/install/bbb-conf.html) but I don't have command-line access to the BBB server I'm using. I am the Moodle/BBB site administrator and I can find the Moodle version I'm using (3.1.2 Build 20160912), but I'm unable to find anything in the Moodle server environment parameters about **which BBB version** I'm using.

In any case, with the BBB version I'm running at gnomio.com, I'm unable to find a way of capturing the poll results data, say for example in a CSV file for post-presentation analysis of audience perceptions of the presentation. If BBB could capture poll results data in raw numbers or percentages for each slide (e.g. row1: slide01, Yes:75%, No:25%; row2: slide05, A:33.3%, B:33.3%, C:33.3%; row3: slide 10, A:10%, B:40%, C:25%, D:25%, etc.) and make it easily exportable in a spreadsheet or CSV, then this would facilitate the process of data analysis for learning how learners learn. For example, it might allow presenters to analyze data from polls to begin to try and understand which slides are most effective at communicating a difficult concept to students.

I know that when I record a BBB session, the published poll results are captured in the recording, but this approach to collecting data scales very poorly. I don't have time to watch hours of video recordings just to find the poll results data from the presentations.

BBB must have access to the poll result data internally in order to be able to produce the poll result statistics for presentation on the screen, but I'm unable to find a way to get that data out of BBB as usable data for analysis; it seems that I can only see it as pixels in a recorded BBB session.

So I guess this is a feature request: please make poll result data exportable in a CSV file or something like that. Thanks.

**Comment by ffdixon** [comment]
We don't have the ability to provide you poll results (yet).  Marking this issue as an enhancement request.  We'll look at adding this in a future version of BigBlueButton.

It might be something like in the Polling window, when you see the results, you right-click on them and copy the numbers to the clipboard, and then click "Publish" to share them with others.

**Comment by ffdixon** [comment]
Added https://github.com/bigbluebutton/bigbluebutton/issues/5469
