### ISSUE TITLE
It does not see my flash player

### ISSUE THREAD

**Issue by Shura0** [bigbluebutton/bigbluebutton#3403]
Hello.

I'm trying to test demo on your site http://demo.bigbluebutton.org/ and getting error:
"You need Flash installed and enabled in order to use the Flash client."

Flash is installed and working on all sites, but your site even does not ask to enable it.
My system is Ubuntu 16.04, firefox 49.0.
It is not browser extension issues, I even tried to create new firefox profile with the same result.

**Comment by ffdixon** [comment]
Hi,

Can you try Chrome (not Chromium) to see if it works.

**Comment by Shura0** [comment]
Yes, it works in chrome (but not in chromium)

**Comment by ffdixon** [comment]
We recommend using Chrome as it always has the latest version of Flash built-in.

**Comment by samboustani** [comment]
It's 2019 and this is not working.

**You need Adobe Flash installed and enabled in order to use this client**

Every browser, every time.

**Comment by capilkey** [comment]
You've posted in an issues that was closed more than 2.5 years ago that was specifically related to Chromium not shipping a Flash plugin.

BigBlueButton 2.2, which we recently released a beta for, has a fully featured HTML5 client. You can try it out at https://test.bigbluebutton.org or find steps to install it yourself here, http://docs.bigbluebutton.org/2.2/install.html.

**Comment by r4dr3fr4d** [comment]
@capilkey I've tried using Chrome, Chromium, *and* Firefox to log onto a Flash-run website - which also has a "system checker" to test compatibility, telling me my Flash version in all three cases.  The same message pops up despite Flash being installed/enabled/unblocked.
