### ISSUE TITLE
How to install bbb-client for w7

### ISSUE THREAD

**Issue by MrJINXIN** [bigbluebutton/bigbluebutton#3412]
my client project install on w7,bbb-server on VM,I would to run in localhost.
please tell me how to do?I am looking forward to your reply.
and May I tell me src/conf/bigbluebutton.nginx on bbb-client effect.thank your very much.
I looked blogs src/conf/config.xml update，but git haven't it

**Comment by GhaziTriki** [comment]
Hello @MrJINXIN 

Can you post this to our bigbluebutton-dev mailing list, see

https://groups.google.com/forum/#!forum/bigbluebutton-dev

And we will help you there.
