### ISSUE TITLE
Support of installation on other operating systems?

### ISSUE THREAD

**Issue by qoopp** [bigbluebutton/bigbluebutton#3416]
Hello，
I would like to ask whether the bigbluebutton support installed on other operating systems, like CentOS or Debian?
Thank you.

**Comment by GhaziTriki** [comment]
Hello @qoopp 

Can you post this to our bigbluebutton-setup mailing list, see

https://groups.google.com/forum/#!forum/bigbluebutton-setup

And we will help you there.

**Comment by qoopp** [comment]
Thank you very much！
