### ISSUE TITLE
Checksum Error in create meetings

### ISSUE THREAD

**Issue by kartikdanidhariya** [bigbluebutton/bigbluebutton#3417]
hi,
I refer api document for bigbluebutton 
in that i want to create meetings from api 
ex: http://BBB_URI/bigbluebutton/api/create?meetingID=111&attendeePW=aaa&moderatorPW=bbb&checksum=fa9a105567e52e16eca328237bac4043

whenever i call this api its give me a check sum error to me
what exactly the value of check sum in api
it give checksum error in that 
how can i solve that

**Comment by GhaziTriki** [comment]
Hello @kartikdanidhariya 

Can you post this to our bigbluebutton-dev mailing list, see

https://groups.google.com/forum/#!forum/bigbluebutton-dev

And we will help you there.

**Comment by kartikdanidhariya** [comment]
hi i tried to post query in that group but for me it will not allow to post new query in that group
do you have any other forum of link where i put my question?
so plz share.

**Comment by ffdixon** [comment]
Can you apply again -- and make sure you answer the challenge question; otherwise, we assume the e-mail address is a bot.

**Comment by mhadieskandari** [comment]
hi
 i want to set meeting name as persian characters like "سلام" but when i use persian character my checksum failed when i call create meeting . and also when webhook call's my api  my checksum is different by webhook's checksum .  anybody can help me in this problem ?

**Comment by GhaziTriki** [comment]
@mhadieskandari BigBlueButton API handles all UTF-8 characters in meeting id, I event tested creating meeting id containing emoji and it works fine. What version of BigBlueButton do you have on your server?

**Comment by mhadieskandari** [comment]
@GhaziTriki I used bbb version 1.1.0  . i try call bbb api with dotnet core 2 . 

this is my code :

public DataTable  CreateMeeting(string meetingName, string meetingId, string attendeePw, string moderatorPw,string logoutUrl,string welcome)
        {
            try
            {
                var strServerIpAddress = File.ReadAllText(AppDomain.CurrentDomain.BaseDirectory + "ServerIPAddress.txt");
                var strSalt = File.ReadAllText(AppDomain.CurrentDomain.BaseDirectory + "ServerId.txt");
                var strParameters = "name=" +HttpUtility.UrlEncode(meetingName,Encoding.UTF8)  + "&meetingID=" + HttpUtility.UrlEncode(meetingId, Encoding.UTF8) + "&attendeePW=" + HttpUtility.UrlEncode(attendeePw, Encoding.UTF8) + "&moderatorPW=" + HttpUtility.UrlEncode(moderatorPw, Encoding.UTF8);
                if (!string.IsNullOrEmpty(logoutUrl))
                {
                    strParameters += "&logoutURL=" + HttpUtility.UrlEncode(logoutUrl, Encoding.UTF8);
                }
                if (!string.IsNullOrEmpty(welcome))
                {
                    strParameters += "&welcome=" + HttpUtility.UrlEncode(welcome, Encoding.UTF8);
                }
                var strSha1CheckSum = Sha1.GetSha1("create" + strParameters + strSalt);
                var request = (HttpWebRequest)WebRequest.Create("http://" + strServerIpAddress + "/bigbluebutton/api/create?" + strParameters + "&checksum=" + strSha1CheckSum);
                //request.ContentType = "text/plain; charset=UTF-8";
                var response = (HttpWebResponse)request.GetResponse();
                var sr = new StreamReader(response.GetResponseStream());
                var ds = new DataSet("DataSet1");
                ds.ReadXml(sr);
                return ds.Tables[0];
            }
            catch (Exception ex)
            {
                _log.Write(ex.Message);
                return null;
            }
        }

**Comment by misisol** [comment]
This problem still exists on create API in meeting name, join API in fullName when using Persian characters.

**Comment by sadeghesfahani** [comment]
I code a function to convert Unicode characters to bigbluebutton readable so checksum can work perfectly. you can use it with Persian too. it is python code but the same concept can be implemented in any other language.
`@staticmethod
    def decode_for_bigbluebutton(string_to_convert):
        decoded_string_to_convert = str(string_to_convert.encode('utf-8')).replace("b'", "").replace("'", "").replace("\\", "%")
        list_of_unicode_characters = re.findall(r'%\w+', decoded_string_to_convert)
        list_of_converted_to_upper_case_utf8 = list()
        for unicode_character in list_of_unicode_characters:
            list_of_converted_to_upper_case_utf8.append(unicode_character.replace("x", "").upper())
        for item_index in range(len(list_of_converted_to_upper_case_utf8)):
            decoded_string_to_convert = decoded_string_to_convert.replace(list_of_unicode_characters[item_index],
                                                                          list_of_converted_to_upper_case_utf8[item_index])
        decoded_string_to_convert = decoded_string_to_convert.replace(" ", "%20")
        return decoded_string_to_convert`
