### ISSUE TITLE
showRecordingNotification

### ISSUE THREAD

**Issue by serhi0z** [bigbluebutton/bigbluebutton#3418]
version 419
....
Using bbb-client 1.0.0-1ubuntu431 and 1.0.0 server
When I enabled record=true and set showRecordingNotification="false" in
/var/www/bigbluebutton/client/conf/config.xml

Recording notification still appeared on the top toolbar. it looks like this parameter doesn't work.
Recording is ok. How can i remove recording notification by any way?

**Comment by ffdixon** [comment]
Just checked and this is still an issue in 2.0-beta

**Comment by GhaziTriki** [comment]
Checked in 2.0-RC6, it seems like it is working like expected.
