### ISSUE TITLE
The new action updateRecordings responds with an exception if the permissions are not correct

### ISSUE THREAD

**Issue by jfederico** [bigbluebutton/bigbluebutton#3422]
There should be an XML error response for that, like:

`<response>
      <returncode>FAILED</returncode>
      <messageKey>fileNotFound</messageKey>
      <message>File not found, update could not be executed</message>
</response>`

**Comment by ffdixon** [comment]
@jfederico Is this an issue with server permissions?

**Comment by jfederico** [comment]
I think this was completed long (very long) time ago. Closing
