### ISSUE TITLE
Add blank-presentation.pdf to the packaging and install it on /var/bigbluebutton/blank

### ISSUE THREAD

**Issue by GhaziTriki** [bigbluebutton/bigbluebutton#3436]
The new file `bigbluebutton-config/slides/blank-presentation.pdf` should be added to the packaging and configured to be installed inside `/var/bigbluebutton/blank`. Rleated to #3411

**Comment by ffdixon** [comment]
Resolved in latest packaging for BigBlueButton 1.1-dev.
