### ISSUE TITLE
Admin Web page Access

### ISSUE THREAD

**Issue by Kamalt1983** [bigbluebutton/bigbluebutton#3442]
Hi Sir,

I have installed bigblubutton. How to create the user and and how to scheduled the meetings. When I am trying to access it. I am getting only demo webpage..

Please help me.

THanks
kamal Thakur
kamalt1983@gmail.com

**Comment by Kamalt1983** [comment]
I am wating for the update

**Comment by ffdixon** [comment]
Hi kamal,

You've posted two messages within 4 hours.  This suggests you believe there is an implied service level agreement in these issues that all questions are answered within X hours or Y days.

There is not.

Keep in mind that the members in these forums volunteer their time to help others.  There are over 2,000 members on the BigBlueButton developer mailing list, and many of them monitor these issues.

You need to be patient and wait for a member to volunteer their time to help.  

If you are unable to wait for a volunteer and require immediate assistance, you can reach out to any of the companies that provide commercial support.  

  http://bigbluebutton.org/support

In any event, closing this issue.  For help, please post to bigbluebutton-setup (see above URL).  If we determine that you have found a bug or have a feature request, we'll open an issue here.

Regards,... Fred

**Comment by Kamalt1983** [comment]
Hi Sir
 I apologise sir. I need the guide how to get the admin interface and how to configure it. I have done the installation by below link till point number 09.

http://docs.bigbluebutton.org/install/install.html#installing-bigbluebutton-10

I am not aware next setp. Please help.

Thanks you
Kamal thakur

**Comment by ffdixon** [comment]
There no admin interface with BigBlueButton.  Instead, we provide API demos that give example of how to use the BigBlueButton interface.  In almost all cases, the setup of BigBlueButton is integrated with an existing system.  See: 

   http://docs.bigbluebutton.org/support/faq.html#front-ends
