### ISSUE TITLE
Welcome message in bigbluebutton.properties does not support Unicode

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#3453]
Reproduced the issue by putting the following string in bigbluebutton.properties

defaultWelcomeMessage=<br>Добро пожаловать в <b>%%CONFNAME%%</b>!<br><br>

and the client displays

  ![image](https://cloud.githubusercontent.com/assets/290351/20175767/7375945e-a712-11e6-9107-a64734314912.png)

Reported in this thread

  https://groups.google.com/d/msg/bigbluebutton-dev/qbbpYAt0oNk/6cdPFTSuN80J

**Comment by ffdixon** [comment]
The problem looks like it Java properties files must have Unicode strings encoded in hex escape.  Need to test this.

**Comment by kepstin** [comment]
To encode the java properties file, you normally want to use the `native2ascii` tool included with the jdk: https://docs.oracle.com/javase/7/docs/technotes/tools/windows/native2ascii.html

**Comment by pedrobmarin** [comment]
I think @kepstin answer is the right way to fix this issue. The only problem I can think is that we have to make the user aware of this procedure.
I could also fix it making an automatic conversion to UTF-8 at ParamsProcessorUtil class. But if we could avoid that would be great.

**Comment by pedrobmarin** [comment]
And let's not forget defaultWelcomeMessageFooter :)

**Comment by pedrobmarin** [comment]
https://github.com/bigbluebutton/bigbluebutton/commit/999541c24286667a686444dbcaa78d1d801b0bca

**Comment by ritzalam** [comment]
There is a plan to externalize configuration so we can override default configuration with per meeting or per user configuration. We'll address this issue when we implement that.

**Comment by ritzalam** [comment]
The goal is to be able to change the configuration without requiring restart of BBB. The challenge right now is that if we want to change a config property, we have to restart BBB. We'll have to wait for the meetings to end or kill the meetings before we can restart.
