### ISSUE TITLE
PDFs not displaying text/Office documents not loading

### ISSUE THREAD

**Issue by rajephcote** [bigbluebutton/bigbluebutton#3456]
Everything has been working absolutely fine on my server (running version 1) as of today users have complained that office documents give 'Failed to convert the office document.null'.  PDF files upload but text does not display.  Server has plenty of space (couple of hundred GB free) Problem files are files that worked perfectly last week and work on the demo server

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.2 LTS"

any help greatly appreciated

**Comment by ffdixon** [comment]
Try

~$ sudo bbb-conf --restart

and try uploading a document.  After that, check that LibreOffice is running

~$ ps -aefww | grep libre
root      81869      1  0 06:36 ?        00:00:00 /usr/lib/libreoffice/program/oosplash --headless --nologo --nofirststartwizard --accept=socket,host=127.0.0.1,port=8100;urp
root      81921  81869  0 06:36 ?        00:01:01 /usr/lib/libreoffice/program/soffice.bin --headless --nologo --nofirststartwizard --accept=socket,host=127.0.0.1,port=8100;urp
sshadmin 107430 107383  0 22:39 pts/1    00:00:00 grep --color=auto libre

Finally, check the output of

  sudo bbb-conf --check

**Comment by rajephcote** [comment]
Restarted but to no avail.

~$ ps -aefww | grep libre
root     10921     1  0 02:37 ?        00:00:00 /usr/lib/libreoffice/program/oosplash --headless --nologo --nofirststartwizard --accept=socket,host=127.0.0.1,port=8100;urp
root     10933 10921  0 02:37 ?        00:00:00 /usr/lib/libreoffice/program/soffice.bin --headless --nologo --nofirststartwizard --accept=socket,host=127.0.0.1,port=8100;urp
root     11296  1403  0 02:43 pts/1    00:00:00 grep --color=auto libre

sudo bbb-conf --check
BigBlueButton Server 0.9.0 (734)
                    Kernel version: 3.13.0-042stab120.5
                      Distribution: Ubuntu 14.04.2 LTS (64-bit)
                            Memory: 8192 MB

/var/www/bigbluebutton/client/conf/config.xml (bbb-client)
                Port test (tunnel): 87.106.233.95
                              Red5: 87.106.233.95
              useWebrtcIfAvailable: true

/opt/freeswitch/conf/sip_profiles/external.xml (FreeSWITCH)
                    websocket port: 5066
                    WebRTC enabled: true

/etc/nginx/sites-available/bigbluebutton (nginx)
                       server name: 87.106.233.95
                              port: 80
                    bbb-client dir: /var/www/bigbluebutton

/var/lib/tomcat7/webapps/bigbluebutton/WEB-INF/classes/bigbluebutton.properties (bbb-web)
                      bbb-web host: 87.106.233.95

/var/www/bigbluebutton/check/conf/config.xml (client check)
                      client check: 87.106.233.95

/usr/share/red5/webapps/bigbluebutton/WEB-INF/red5-web.xml (red5)
                  voice conference: FreeSWITCH
                     capture video: true
                   capture desktop: true

/usr/local/bigbluebutton/core/scripts/bigbluebutton.yml (record and playback)
                     playback host: 87.106.233.95

any ideas?

**Comment by GhaziTriki** [comment]
Is it possible the share the concerned file?

**Comment by rajephcote** [comment]
Sure link below:
http://nationalschoolstraining.co.uk/EnablingLearning.ppt

I tried converting to a PDF which display properly until it is uploaded when all text disappears
[EnablingLearning.pdf](https://github.com/bigbluebutton/bigbluebutton/files/585420/EnablingLearning.pdf)

**Comment by GhaziTriki** [comment]
I have uploaded your ppt file on a server built on latest master and it was converted and displayed. Since we the release of 1.0 we have enhanced the document conversion. The latest build of BigBlueButton can be tested on demo server https://demo.bigbluebutton.org. Please let us know if you still have an issue.

**Comment by rajephcote** [comment]
I found that it worked there too - do you suggest that I update?

I found it strange because it has all worked well for several months

**Comment by ffdixon** [comment]
Tested this slide deck with BigBlueButton 1.1-beta and it converts correctly.

![slides-good](https://cloud.githubusercontent.com/assets/290351/21966316/15be1d84-db3f-11e6-9bf8-3ab5ec961d45.png)
