### ISSUE TITLE
WebRTC cannot connect, Error 1002

### ISSUE THREAD

**Issue by asterismo** [bigbluebutton/bigbluebutton#3465]
Hi, i have set up a BBB server in an internal IP address and redirected traffic from the webserver based on the domain name given to the BBB server using proxy_pass in nginx (BBB is in a VM with enough resources and port redirection in the firewall). Everything seems to work well except for the WebRTC SIP call that gives the error 1002. I need help troubleshooting this issue, maybe a proxy_pass misconfiguration of port 7443?

I have applied the changes for enabling HTTPS but i don't know if i have set up correctly the proxy from the web_server to the BBB server. Here is what i have done.

In the web server that proxies to BBB i'm getting this error:
2016/11/15 13:53:59 [error] 1952#0: *138 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 127.0.0.1, server: bbb.mydomain.com, request: "GET /ws HTTP/1.1", upstream: "http://192.168.1.107:80/ws", host: "bbb.mydomain.com"

The proxy i created in the webserver is this, please take a look
Also i set up hosts and hostname in both web server and bbb server to honor IP addresses

upstream main {
  server bbb.mydomain.com;
}
server {
        listen 80;
	listen 127.0.0.1:443 ssl;
	listen 7443;
        server_name bbb.mydomain.com;
        ssl_certificate       /etc/letsencrypt/live/bbb.mydomain.com/fullchain.pem;
        ssl_certificate_key   /etc/letsencrypt/live/bbb.mydomain.com/privkey.pem;
        ssl_ciphers AES256+EECDH:AES256+EDH:!aNULL;
        ssl_dhparam /etc/ssl/nginx/dhparam.pem;
        add_header Strict-Transport-Security max-age=31536000;
        access_log /var/log/nginx/access-nginx-intranet.log;
        error_log  /var/log/nginx/error-nginx-intranet.log;
        location / {
          proxy_pass http://main;
         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
         proxy_set_header Host $host;
          proxy_set_header X-Real-IP  $remote_addr;
          proxy_read_timeout 150;
                     }
	}

**Comment by capilkey** [comment]
This question is more appropriate for our setup mailing list (https://groups.google.com/forum/?fromgroups=#!forum/bigbluebutton-setup). Can you please post it there and hopefully someone can help.

**Comment by asterismo** [comment]
Done! thanks!
