### ISSUE TITLE
User duplication on reconnect

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#3474]
On reconnect of the Flash client my username appeared twice in the list (presenter!). Shortly afterwards the client logged me out. The following is a screenshot of the case.
<a href="http://tinypic.com?ref=sey6m8" target="_blank"><img src="http://i68.tinypic.com/sey6m8.png" border="0" alt="Image and video hosting by TinyPic"></a>

**Comment by mikhailnov** [comment]
How do you reconnect?

**Comment by ffdixon** [comment]
We've refactored the logic for detecting multiple users on BigBlueButton 2.0-dev.  Closing this issue.
