### ISSUE TITLE
Error while downlaod grail in ubuntu wget command

### ISSUE THREAD

**Issue by zaasmi** [bigbluebutton/bigbluebutton#3525]
http://ww11.dist.springframework.org.s3.amazo                          neaws.com/release/GRAILS/grails-2.3.6.zip
Connecting to ww11.dist.springframework.org.s3.amazoneaws.com (ww11.dist.springf                          ramework.org.s3.amazoneaws.com)|72.52.4.90|:80... connected.
HTTP request sent, awaiting response... Read error (Connection reset by peer) in                           headers.
Giving up.

**Comment by ffdixon** [comment]
Frpm the docs http://docs.bigbluebutton.org/install/setup.html#setup-a-development-environment we tried the command

    wget http://dist.springframework.org.s3.amazonaws.com/release/GRAILS/grails-2.3.6.zip

and it works

root@t4:~# wget http://dist.springframework.org.s3.amazonaws.com/release/GRAILS/grails-2.3.6.zip
--2017-01-15 22:12:10--  http://dist.springframework.org.s3.amazonaws.com/release/GRAILS/grails-2.3.6.zip
Resolving dist.springframework.org.s3.amazonaws.com (dist.springframework.org.s3.amazonaws.com)... 54.231.98.112
Connecting to dist.springframework.org.s3.amazonaws.com (dist.springframework.org.s3.amazonaws.com)|54.231.98.112|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 135503337 (129M) [application/zip]
Saving to: 'grails-2.3.6.zip'

Double-check your using the correct command and path.
