### ISSUE TITLE
is there any feature like countdown show for webinar

### ISSUE THREAD

**Issue by dipenpatel235** [bigbluebutton/bigbluebutton#3536]
Hello..

Would be nice to have a countdown show for webinar. 
For example  we can start it XX minutes before webinar. The clock will show MM:SS countdown lie that.

Thanks

**Comment by ffdixon** [comment]
We added a count-up timer when a recording is started.  Not exactly what you are looking for, but if the webinar is for 30 minutes, you'll see the timer count up to 30 minutes.

**Comment by stevenhuca** [comment]
I think the requirement is similar to a count-up timer when a recording is started:

After meeting moderator join the meeting, a count-up timer should start from 0.
