### ISSUE TITLE
bbb behind apache reverse proxy

### ISSUE THREAD

**Issue by r4a5a88** [bigbluebutton/bigbluebutton#3552]
Hi

I installed bbb on ubuntu 14.x Server. 
Now I moved inot a private network behind a apache revese proxy.
I tried to copy most info from the nginx conf to the apache conf.
the starting page works fine but the demo page does not work and shows me 500 error

with bbb-conf --set-ip I set it to the hostname of the proxy 

![demo](https://cloud.githubusercontent.com/assets/22817846/21808796/2bacb43c-d745-11e6-8a92-20dbc672be35.jpg)
![other](https://cloud.githubusercontent.com/assets/22817846/21808797/2bb137be-d745-11e6-94a8-325134445bba.JPG)

Alias bbb /bbb
Alias bigbluebutton /bbb

HostnameLookups off
UseCanonicalName off

ProxyPass /bbb http://192.168.xxx.yyy
ProxyPass /demo http://192.168.xxx.yyy.8080/demo

ProxyPassMatch ^/deskshare/(.*)$ http://192.168.xxx.yyy:5080/deskshare/$1
ProxyPassMatch ^/bbb/(.*)$ http://192.168.xxx.yyy:8080/bigbluebutton/$1

ProxyPassReverse /bbb http://192.168.xxx.yyy
ProxyPassReverse /demo http://192.168.xxx.yyy:8080/demo
 
ProxyPassMatch ^/(open|close|idle|send)/(.*) http://192.168.xxx.yyyi:8088/$1/$2

Could you help me make it work ?
Do I need to add something to the proxy conf?

**Comment by kepstin** [comment]
We don't support running BigBlueButton behind an Apache reverse-proxy - we recommend that BigBlueButton should be served from a dedicated machine, with its own hostname (domain name). See [The relevant FAQ entry](http://docs.bigbluebutton.org/support/faq.html#we-recommend-running-bigbluebutton-on-port-80).

That said, you might be able to get some help on the [BigBlueButton setup mailing list](https://groups.google.com/forum/#!forum/bigbluebutton-setup)

We don't use Github for support requests, so I'm closing this issue.

**Comment by basisbit** [comment]
for those who stumble over this problem, this might help:
 https://docs.bigbluebutton.org/2.2/configure-firewall.html#extra-steps-when-server-is-behind-nat
