### ISSUE TITLE
Error in BigBlueButtonApplication.java

### ISSUE THREAD

**Issue by Sangwan70** [bigbluebutton/bigbluebutton#3559]
Can you Suggest why I am getting these Errors:
I am trying to build bigbluebutton on rhel 6.8.
I have installed all dependencies and required software.
All other Builds are successful except this one due to this one error.

bigbluebutton-master/bigbluebutton-apps/src/main/java/org/bigbluebutton/red5/BigBlueButtonApplication.java:94: error: illegal start of expression
                Runnable getHeapTask= () -> getHeapStatsHelper();
                                       ^
bigbluebutton-master/bigbluebutton-apps/src/main/java/org/bigbluebutton/red5/BigBlueButtonApplication.java:94: error: illegal start of expression
                Runnable getHeapTask= () -> getHeapStatsHelper();
                                          ^
2 errors

**Comment by ffdixon** [comment]
We haven't tested building BigBlueButton on RHEL 6.8. We focus on Ubuntu 16.04 64-bit.

Still, I would suggest trying out the BigBlueButton 1.1-beta release to see if it builds any easier.  See http://docs.bigbluebutton.org/1.1/11-setup.html
