### ISSUE TITLE
Enable lock settings to be set on create

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#3560]
Today, we provide the ability for the moderator to Lock down viewers in a BigBlueButton session the Lock 
Settings.

![image](https://cloud.githubusercontent.com/assets/290351/21938289/af6e6960-d988-11e6-95cc-dafaa7a5ae2b.png)

It would be good to enable a 3rd party application using the BigBlueButton API to set the default values.

Add parameters to the API 'create' command to enable the default value for a lock settings, such as

  lockWebcam=true|false
  lockMicrophone=true|false
  LockPublicChat=true|false
  LockPrivateChat=true|false
  LockLayout=true|false

The default values would be false.

**Comment by GhaziTriki** [comment]
Implemented in https://github.com/bigbluebutton/bigbluebutton/pull/7116
