### ISSUE TITLE
Swapping presentation with video in playback hides annotation canvas

### ISSUE THREAD

**Issue by alexandrekreis** [bigbluebutton/bigbluebutton#3561]
When we are making annotations...

![bug 1-1](https://cloud.githubusercontent.com/assets/1202973/21941307/4868a3d0-d9af-11e6-9891-94901184aaf2.jpg)

And we swap presentation with video...

![bug 1-2](https://cloud.githubusercontent.com/assets/1202973/21941336/71ccf79e-d9af-11e6-9ade-19fb3f1125f9.jpg)

The annotations and the cursor position are lost.

Swapping presentation with video causes svg file to reset (all images, canvas and shapes are set to "display:none" and/or "visibility: false"). 

The current solution only restores slide visibility and view box size (recently added here: 
https://github.com/alexandrekreis/bigbluebutton/commit/dde5f231888ab894c43ef1fa5cd5a177cc873bac).

However, we also need to restore the cursor position and the annotation canvas.

**Comment by ffdixon** [comment]
Good catch!
