### ISSUE TITLE
Restoring annotations when swapping presentation with video doesn't work when the swapping is made with the playback paused.

### ISSUE THREAD

**Issue by alexandrekreis** [bigbluebutton/bigbluebutton#3563]
Steps to reproduce the bug:
1. Wait some annotations appear
2. Pause playback
3. Swap slide <--> video
4. Resume video.

When the playback is paused and we swap slides with video, we restore everything but the shapes visibility (considering https://github.com/alexandrekreis/bigbluebutton/commit/ac094aa89a0b4614a46cd9fcef3117042ae477fc). 

Couldn't find an easy and fast way to do it.

However, when user resumes playback, annotations are shown properly. Also, when the swapping is made during an active playback, everything works fine (also considering https://github.com/alexandrekreis/bigbluebutton/commit/ac094aa89a0b4614a46cd9fcef3117042ae477fc).

Thus, this is not a severe bug.

**Comment by alexandrekreis** [comment]
Related to: https://github.com/bigbluebutton/bigbluebutton/issues/3561

**Comment by ffdixon** [comment]
Verified fixed in https://github.com/bigbluebutton/bigbluebutton/pull/3562 (thanks!)
