### ISSUE TITLE
Change recording encoder from vp8 to vp9

### ISSUE THREAD

**Issue by mikhailnov** [bigbluebutton/bigbluebutton#3565]
I suggest to change the default webm recordings video encoder from vp8 to vp9 to make the size of the recordings smaller and brandwitch usage lower, while being able to produce recordings in higher resolution not spending to much disk space on the server.

**Comment by kepstin** [comment]
Good idea - we'll take a look at doing this in a future version.
In my experience, the vp9 encoder usually isn't much slower than vp8, and the browser support is fairly good now (almost every browser that supports vp8 also supports vp9).

In the mean time, you can edit the file `/usr/local/bigbluebutton/core/lib/recordandplayback/generators/video.rb` to change the codec and encoding settings used. Note that we use `mkclean` to do streaming optimization, and it doesn't currently support vp9.

**Comment by mikhailnov** [comment]
Thanks very much for the link to the file, now I don't have to look for it by myself. 
What about vp9 in HTML5 client?

**Comment by ffdixon** [comment]
For the HTML5 client, switching from VP8 to VP9 should be all server-side as the HTML5 client is just showing the desktop sharing video in a <video> tag.

**Comment by kepstin** [comment]
We've updated the version of mkclean that we package with BigBlueButton 2.0+, so it's safe to change the codec in the "presentation" recording format to vp9 now.

**Comment by mikhailnov** [comment]
Is there any progress on this?

**Comment by ffdixon** [comment]
We haven't looked at this yet for BigBlueButton 2.2-beta.  Did you try changing it from VP8 to VP9?  Curious what were the results you saw?

**Comment by mikhailnov** [comment]
No, but I will try after upgrading to v2.2, if I don't forget.

**Comment by ffdixon** [comment]
@kepstin I think we should keep with VP8 for compatibility with Safari, no?

**Comment by kepstin** [comment]
vp8 only works in Safari when used with WebRTC; that's not relevant for recording playback. If someone wants recording playback to work in safari, they have to enable h264 video regardless.

**Comment by ffdixon** [comment]
We've added encoding of h.264 for supporting payback on iOS devices, see https://github.com/bigbluebutton/bigbluebutton/releases/tag/2.2-beta-23.
