### ISSUE TITLE
How to reinstall a working version of BBB + Matterhorn integrated

### ISSUE THREAD

**Issue by walterbux** [bigbluebutton/bigbluebutton#3567]
Hello and many compliments for all your activity that I consider a reference point for all people interested in videoconference.
I am interested in recording meetings and I don't see a better solution than the BBB-Matterhorn integration for that (even if there are new video archiving/publishing solutions like MediaDrop to be considered as well).

My question is simple: while waiting for a better solution I would like to install bbb 0.8 and MH 1.2/1.4. I have tested dev0x10/bbb-script without success because some repositories are no more supported and in particular I cannot find the bbb-playback-matterhorn package.

Can you please help me ?
Thank you and kind regards.

Walter Bux

**Comment by ffdixon** [comment]
Duplicate of https://github.com/bigbluebutton/bigbluebutton/issues/2574
