### ISSUE TITLE
Desktop sharing records the wrong region on high-dpi monitors

### ISSUE THREAD

**Issue by kepstin** [bigbluebutton/bigbluebutton#3571]
When using BigBlueButton with a high-dpi monitor in Windows (with a zoom value >100%), in region mode rather than fullscreen, the region of the screen that is actually recorded appears to be different from the blue rectangle displayed by the java applet.

We need to verify that the screen coordinates are getting transformed correctly when going from the (not high-dpi-aware) java applet to the high-dpi-aware ffmpeg code.

**Comment by ffdixon** [comment]
Just tried sharing on a high DPI monitor and can see the incorrect offset

![image](https://cloud.githubusercontent.com/assets/290351/23595333/2187cca6-01ef-11e7-90d7-5505c04640db.png)

**Comment by ffdixon** [comment]
Closing this issue as we are moving to an HTML5 client (and using WebRTC for desktop sharing).
