### ISSUE TITLE
Redirect to html5 client overwritten

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#3593]
On an Android device entering BigBlueButton you would see a notification that the device does not support Flash player. We had added an extra button which redirects the user to the HTML5 client (if running). This logic was impacted in #3519 
We need to recover the redirect to html5 client functionality.

**Comment by capilkey** [comment]
Adding in an extra check for Android will make it behave the same as it did before #3519 for an Android version of Chrome. It should be all that's required.
