### ISSUE TITLE
A .PPTX with a smooth gradient can cause libreoffice to not convert

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#3594]
On some occasions, we've seen libreoffice have troubles with a .pptx slides with a very smooth gradient

![image](https://cloud.githubusercontent.com/assets/290351/22261303/65be7b4c-e23a-11e6-8132-1a29e3837587.png)

Sometimes these slides have the background gradient created from thousands of individual images, as opposed to a single image.  The thousands of individual images causes problems when opened with libreoffice.

Need to add some logic to scan incoming .pptx for this use case and, if found, remove the individual images.  This way the slide will still convert.

In our testing, if you take such a .pptx slide and save it as .pdf, it uploads fine.  Hence, the recommendation to upload .pdf would also avoid this case.

**Comment by GhaziTriki** [comment]
I have provided a fix in #3616. We are now reading PPTX files to check whether they contain a certain image and whether it contains EMF files. If it is the case we don't convert it and invite the user to convert the document to PDF before trying again.

I have also create two issues for Apache POI and a third issue for OpenOffice for future imporvements of this feature:
https://bugs.documentfoundation.org/show_bug.cgi?id=105559
https://bz.apache.org/bugzilla/show_bug.cgi?id=60655
https://bz.apache.org/bugzilla/show_bug.cgi?id=60656
