### ISSUE TITLE
Review accessibility support for JAWS screen reader and Closed Captioning

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#3596]
We need to do an external review of the accessibility support for JAWS screen reader and Closed Captioning before the final release.

**Comment by capilkey** [comment]
Relevant PRs #3652, #3693, #3696, #3721, #3747, #3758. Just awaiting final review confirmation.

**Comment by ffdixon** [comment]
The external review is complete -- attached is the accessibility statement we'll be posting on bigbluebutton.org along with the VPAT for version 1.1.

[Accessibility-statement-BigBlueButton-2017to-be-shared-with-BLINDSIDE-5776.pdf](https://github.com/bigbluebutton/bigbluebutton/files/894040/Accessibility-statement-BigBlueButton-2017to-be-shared-with-BLINDSIDE-5776.pdf)
[VPAT-1.3-forBigBlueButton-2017MARsharedwithBLINDSIDE-5776.pdf](https://github.com/bigbluebutton/bigbluebutton/files/894041/VPAT-1.3-forBigBlueButton-2017MARsharedwithBLINDSIDE-5776.pdf)
