### ISSUE TITLE
HTML5 settings dropdown sometimes closes unexpectedly 

### ISSUE THREAD

**Issue by perroned** [bigbluebutton/bigbluebutton#3598]
1. What steps will reproduce the problem?
Clicking the top-right hand icon for the drop down menu. Either leaving it open or moving the cursor around (on hover related maybe?)

2. Expected output
The menu remains open until a selection is made-- should only close when a selection is made or closed via the open/close button

3. What do you see instead?
it closes either immediately or after a brief pause

Linux Ubuntu 14.04 Google Chrome Version 53.0.2785.101 (64-bit)

**Comment by antobinary** [comment]
Changing presenter in the meeting immediately triggers closing of the drop down menu.

**Comment by OZhurbenko** [comment]
Tested in both Firefox 57 and Chrome 63, can't reproduce it anymore. It looks like it's been fixed.
