### ISSUE TITLE
Screen sharing appears slanted on MacBook Air 11 inch

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#3603]
We've got a report from a member of our community that when the share their screen on their MacBook Air 11 Inch, it appears as follows

![image](https://cloud.githubusercontent.com/assets/290351/22273075/57e96d9c-e26c-11e6-96b6-2536918e712e.png)

Anyone else got a MacBook Air 11" they can try on `http://demo.bigbluebutton.org` and let us know if they encounter the same issue?

**Comment by kepstin** [comment]
We need to apply this patch:
https://trac.ffmpeg.org/attachment/ticket/5654/fix-5654.patch
to the ffmpeg build used in the screensharing applet.

**Comment by kepstin** [comment]
This was fixed with @ritzalam's commit d9e57b7
