### ISSUE TITLE
Nginx config does not listen on ipv6 addresses

### ISSUE THREAD

**Issue by kepstin** [bigbluebutton/bigbluebutton#3606]
Need to add the following line to the file `/etc/nginx/sites-enabled/bigbluebutton`:
```
     listen [::]:80;
```
beside the existing one for ipv4. This is safe on all systems even if they don't have a real ipv6 addess assigned.

**Comment by ffdixon** [comment]
Fixed -- the /etc/nginx/sites-available/bigbluebutton should now listen for ipv6 addresses.
