### ISSUE TITLE
bbb-voice script error

### ISSUE THREAD

**Issue by helpyhelperton** [bigbluebutton/bigbluebutton#3612]
bbb-voice only builds if you edit

`compile 'javax/media:jmf:2.1.1e@jar'`
to be
`compile 'javax.media:jmf:2.1.1e@jar'`

in build.gradle

**Comment by ffdixon** [comment]
@ritzalam Anything needed to be done here?

**Comment by ffdixon** [comment]
Closing as this was an issue related to the Flash client (the project has moved to an HTML5 client).
