### ISSUE TITLE
Annotations made in a different presentation before start recording don't appear

### ISSUE THREAD

**Issue by alexandrekreis** [bigbluebutton/bigbluebutton#3621]
Steps to reproduce the problem:

- Start a room and make annotations on the default first slide
- Upload a new presentation
- Start recording
- Make annotations on the uploaded presentation
- Go back to the default presentation
- Annotations made on it (previously to the start of the recording) will not appear in the RECORDING PLAYBACK.

**Comment by ffdixon** [comment]
Just tried a test on BigBlueButton 2.0-beta and the slide that had annotations before Start Recording was clicked now shows with the annotations in the playback

  https://demo.bigbluebutton.org/playback/presentation/2.0/playback.html?meetingId=6e35e3b2778883f5db637d7a5dba0a427f692e91-1529188586785

Can you give it a try yourself on 

  https://demo.bigbluebutton.org/

and let us know if you see the same thing?
