### ISSUE TITLE
WebRTC bridge code isn't fetching list of stun+turn servers

### ISSUE THREAD

**Issue by kepstin** [bigbluebutton/bigbluebutton#3627]
When you connect to a WebRTC call (in the Flash client), it's supposed to fetch a list of STUN and TURN servers from the endpoint `/bigbluebutton/api/stuns`

However, [bbb_webrtc_bridge_sip.js#156](https://github.com/bigbluebutton/bigbluebutton/blob/master/bigbluebutton-client/resources/prod/lib/bbb_webrtc_bridge_sip.js#L156) checks whether `html5StunTurn` is `null`, and won't fetch the info if it is.

The problem - `html5StunTurn` will never be null, because at [bbb_webrtc_bridge_sip.js#4](https://github.com/bigbluebutton/bigbluebutton/blob/master/bigbluebutton-client/resources/prod/lib/bbb_webrtc_bridge_sip.js#L4) it is initialized as an empty Object.

**Comment by perroned** [comment]
I think if on line #4 `html5StunTurn` was initialised to null it would work correctly. It looks like that is what it was meant to have been originally. That way if an actual object is passed to `callIntoConference` it would use it [here](https://github.com/bigbluebutton/bigbluebutton/blob/master/bigbluebutton-client/resources/prod/lib/bbb_webrtc_bridge_sip.js#L156), and if no object is passed (Flash case) that code would be ignored and it would continue past it to the ajax call
@antobinary
