### ISSUE TITLE
Securing the recorded video through a VOD module

### ISSUE THREAD

**Issue by davidoster** [bigbluebutton/bigbluebutton#3631]
Is there a possibility to have a VOD module like this, https://github.com/kaltura/nginx-vod-module ?
By using such a module the securing and encryption of the videos becomes really simple, since it provides video playback through nginx and basic encryption also through nginx.
Furthermore Kaltura's NGINX VOD module supports playback of webm files via HTML5 techniques!
That would be a huge plus!

If not possible, is there a way to secure the video from not being able to be downloaded or at least encrypted upon local client download and hence make it unviewable? (This is supported as a technique from kaltura's vod module).

Consider the case study of an online private school. We wouldn't want to leak the lessons to others that haven't registered/paid for the teachings.

**Comment by ritzalam** [comment]
We'll see if we're able to do this in the next release.
