### ISSUE TITLE
html5client error , what's  wrong with me?

### ISSUE THREAD

**Issue by frankywen** [bigbluebutton/bigbluebutton#3633]
![image](https://cloud.githubusercontent.com/assets/9948618/22624035/a0fdf02e-ebaa-11e6-933b-0fc8525b93ef.png)

**Comment by ffdixon** [comment]
The HTML5 client is still under development and not yet ready for others.  

We are woking towards a developer (not beta) release of the HTML5 client on BigBlueButton 1.1.  

When that occurs, you'll have the steps both to install it and develop on top of it.  We're looking forward to getting the developer release of the HTML5 client out in the near future.

**Comment by antobinary** [comment]
@frankywen - You are supposed to use the <domain>/demo/demoHTML5.jsp page to log in the client. Simply navigating to <domain>/html5client will not work since you're skipping the authentication step.
