### ISSUE TITLE
WebRTC error 1002

### ISSUE THREAD

**Issue by akovvv** [bigbluebutton/bigbluebutton#3645]
Hello!
When I'm trying to use microphone in demo conference on http://demo.bigbluebutton.org, I'm getting an error "WebRTC: Error 1002". Is it normal? With flash it's all OK. I've tryed in last versions of Mozilla and Chrome.

**Comment by ffdixon** [comment]
Thanks for pointing this out.  We were upgrading it to the latest build of BigBlueButton 1.1-beta and just had to adjust the parameters in sip.nginx.  

It should be fine now.
