### ISSUE TITLE
History is published twice for one meeting

### ISSUE THREAD

**Issue by OZhurbenko** [bigbluebutton/bigbluebutton#3671]
Either the history is requested twice, or there is an inner bug somewhere.
Tested for both captions history and chat history events using HTML5 client.

Steps to reproduce in HTML5:
- stop Meteor
- create a meeting using the Flash client
- start Meteor

**Comment by ffdixon** [comment]
Closing as this is an old issue.  We'll open a new issue if this problem arises in the latest version.
