### ISSUE TITLE
HTML5 - create 'common' folder for all reusable components

### ISSUE THREAD

**Issue by OZhurbenko** [bigbluebutton/bigbluebutton#3672]
We need to have one place for all our reusable components under `/imports/ui/components` .
Right now all of them are on the same level with main modules, and the list is getting bigger and bigger.

It will be easier to find what is already implemented so that nobody was reinventing the wheel.

**Comment by perroned** [comment]
will also help prevent modification of base reusable components from receiving implementation specific code :)

**Comment by OZhurbenko** [comment]
Yay!
