### ISSUE TITLE
Package needed for WebHooks in BigBlueButton 1.1-beta

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#3690]
Need to add a package to BigBlueButton 1.1 for webhooks. See 

  http://docs.bigbluebutton.org/labs/webhooks.html

**Comment by fcecagno** [comment]
Tested the webhooks on 1.1. I suggest to keep nodejs and npm as dependencies of the bbb-webhooks package.

There are two different scenarios that we consider:

**The server has bbb-html5 installed**
In this case, the admin had to install a specific version of nodejs. When the package bbb-webhooks installs, it will detect that its dependency nodejs is already installed, and will just reuse it.

**The server doesn't have bbb-html5 installed**
In this case, the package bbb-webhooks will install nodejs from the main Ubuntu repository, which is fine too. If bbb-html5 is installed later on, nodejs will be upgraded, and we just need to make sure we restart bbb-webhooks.service.

**Comment by ffdixon** [comment]
We could add restart of webhooks and `sudo bbb-conf --restart` so it always gets restarted.

**Comment by fcecagno** [comment]
Yes, I think this is a good strategy.

**Comment by ffdixon** [comment]
Added restart of webhooks

  https://github.com/bigbluebutton/bigbluebutton/blob/master/bigbluebutton-config/bin/bbb-conf#L290

and docs for installation
  
  http://docs.bigbluebutton.org/1.1/install.html#intall-callback-for-events-webhooks

The bbb-webhooks package will be included in the next update to BigBlueButton 1.1-dev.
