### ISSUE TITLE
Record problem. Chat is crashed after somebody used smile ")"

### ISSUE THREAD

**Issue by kovaldn** [bigbluebutton/bigbluebutton#3709]
Problem is in webinar's record player. Chat is crashed after somebody used smile ")" (emoji).

Error appeares after this message in console "playback.js:453 ==Loading acorn media player". 

I have cheked 3 different records and here are results:

record 1 - "Uncaught Error: Syntax error, unrecognized expression: жуть)"
record 2 - "Uncaught Error: Syntax error, unrecognized expression: ))"
record 3 - "Uncaught Error: Syntax error, unrecognized expression: погромче, Сергей)"

![2017-03-06_19-36-15](https://cloud.githubusercontent.com/assets/1854808/23619294/42f74dfc-02a4-11e7-851b-e581f551fb99.png)

**Comment by kepstin** [comment]
Hi @kovaldn - This issue has already been fixed with the changes from #3695 

We haven't pushed out updated packages yet, but they should be coming shortly. In the mean time, you can manually apply the changes from that pull request - they're fairly simple.
