### ISSUE TITLE
HTML5 instead of flash

### ISSUE THREAD

**Issue by ManojVarmaNVK** [bigbluebutton/bigbluebutton#3713]
Can i know how to use HTML5 instead of flash in my own bigbluebutton server?
Can i have more than 500 users per class?
How to get recordings from my own bigbluebutton server to my moodle?

**Comment by ffdixon** [comment]
Hi Manoj,

In the future, please post such questions to bigbluebutton-dev mailing list, see

  https://groups.google.com/forum/#!forum/bigbluebutton-dev

> Can i know how to use HTML5 instead of flash in my own bigbluebutton server?

I think we already responded to your comment in an unrelated pull request (see https://github.com/bigbluebutton/bigbluebutton/pull/3705).  As we had replied in that comment, the HTML5 client is still underdevelopment.  For more information see,

  https://groups.google.com/d/msg/bigbluebutton-setup/ryiaNohcCtE/xgDwrKeTAAAJ

> Can i have more than 500 users per class?

No.  See

  http://docs.bigbluebutton.org/support/faq.html#how-many-simultaneous-users-can-bigbluebutton-support

> How to get recordings from my own bigbluebutton server to my moodle?

The recordings stay in the BigBlueButton server.  You would use the BigBlueButton plugin for Moodle to access BigBlueButton from within your Moodle server.  See

  https://moodle.org/plugins/mod_bigbluebuttonbn
