### ISSUE TITLE
getRecordings API needs to return recorded breakout rooms

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#3716]
Breakout rooms can be recorded, but getRecordings API needs to return the list of recorded breakout rooms.

**Comment by jfederico** [comment]
Changes for adding support to recordings to breakout rooms

The main change can be seen in the result obtained from a getRecordings call
Case A: When the query for getRecordings is based on meetingIDs, the response may include breakout recordings. The parent has a reference to its children and the child has a reference to its parent

PARENT

c0c31b4729a8b7bc21705299286641543baef0f7-1479149223395

...

e5789a99e691d21448e09b4f7b3c311aa69ac1db-1479149289051,563d6d5a57eee453de062849820f26f58578afe1-1479149289052
CHILD

e5789a99e691d21448e09b4f7b3c311aa69ac1db-1479149289051

...

c0c31b4729a8b7bc21705299286641543baef0f7-1479149223395
The flag isBreakout room was removed as the type of recording can be inferred from the parentMeetingID/childrenMeetingID elements

The flag isBreakout room was also removed from the xml responded by getMeetings and getMeetingInfo. It was replaced by a reference to the breakout meetings linked to them, so:

If a meeting is a parent and doesn't have breakout rooms, the response is the same it was before

if a meeting is a parent and has breakout rooms,
breakout-meeting

c0c31b4729a8b7bc21705299286641543baef0f7-1479150771261 ... 871451649e231ff208fa42b6776196eec8f8feae-1479150817161,154594e2ada4a7108d767752e163c8ea423774c0-1479150817162
if a meeting is a child, it will include:
4e77327c10fa611bc2d273caa052e0dbbf2299a4-1479150817161 871451649e231ff208fa42b6776196eec8f8feae-1479150817161 ... c0c31b4729a8b7bc21705299286641543baef0f7-1479150771261 1
The ids used as parentMeetingID and childrenMeetingID are always the internalID (it replaces the externalID that was used before)

**Comment by ritzalam** [comment]
Fixed in PR #3775
