### ISSUE TITLE
Pressing DELETE inside the chat box insert a character ()

### ISSUE THREAD

**Issue by oswaldoacauan** [bigbluebutton/bigbluebutton#3717]
**Browser:** Chrome - 56.0.2924.87 (64-bit)
**OS:** Ubuntu 16.04
**Client:** Flash (build 561)

---

**Steps:**
- Click on the chat box
- Press the Delete key (does not happen when pressing the Del key from numpad)
- Character  is inserted on the input

If you press Delete in the middle of a word, it will replace the character with the  character.

**Comment by jfsiebel** [comment]
Tried again in build 925 available in dev2a, and couldn't reproduce the problem
