### ISSUE TITLE
Add detection for ens3  as default Ethernet connection in packaging

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#3720]
The packaging scripts for BigBlueButton assign a default IP address for the SIP configuration files in FreeSWITCH. 

However, on Ubuntu 16.04, the value for default Ethernet address is sometimes "ens3" instead of "eth0".

Extend the packaging scripts to detect ens3 (if exists) as the default IP address.

**Comment by kepstin** [comment]
Hardcoding 'ens3' makes no sense; the number will vary depending on which pci slot the network adapter is associated with.

The best option for default would be to look at all of the ethernet adapters named "en*" (i.e. en followed by anything) and pick the address from the first one that's configured.

**Comment by ffdixon** [comment]
Fixed in latest update to packaging.  Will be in the next release of bigbluebutton 1.1-beta
