### ISSUE TITLE
Layout of poll results not rendering correctly

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#3725]
Gil Yoder in our bigbluebutton-dev forums reported that rendering of the poll results can sometimes be formatted incorrectly

![image](https://cloud.githubusercontent.com/assets/290351/23828111/02bd6178-0695-11e7-8257-1375ae371f1c.png)

Here is a sample recording 

  https://demo.bigbluebutton.org/playback/presentation/0.9.0/playback.html?meetingId=fb8f6502368927635c63364ceff759fe0b1625df-1489278969692

> I think the problems appear under these circumstances:
 > 
>   * For two part questions the poll is published on a wide screen (4x9) slide. In all of my tests 100% of the answers were for one option. I don’t know if a mix of answers has any bearing on the problem.
>   *  For five part questions the poll is published on a wide screen slide (4x9), and 1 answer is for A and one answer is for E. If only one answer is given, the recorded poll result seems to be correct. You can see this the three recordings that are not highlighted.

Here's a link to the original post
   https://groups.google.com/d/msg/bigbluebutton-dev/jbmFNz98njY/705cvKObBAAJ

**Comment by capilkey** [comment]
It looks like something is going wrong in the poll result SVG creation. The URLs for the two results are here, https://demo.bigbluebutton.org/presentation/fb8f6502368927635c63364ceff759fe0b1625df-1489278969692/presentation/2a0bce8b20f63c0d6b4104ebff6b956917b99f50-1489279060372/poll_result1.svg and https://demo.bigbluebutton.org/presentation/fb8f6502368927635c63364ceff759fe0b1625df-1489278969692/presentation/2a0bce8b20f63c0d6b4104ebff6b956917b99f50-1489279060372/poll_result2.svg

**Comment by kepstin** [comment]
This would be an issue in the code that generates the script for graphiz to use when generating the poll image. It's supposed to move the number of votes (1 in this picture) inside the bar when it's over some threshold, but that appears to not be working.
