### ISSUE TITLE
HTML5 client does not work

### ISSUE THREAD

**Issue by ajinkyagadewar** [bigbluebutton/bigbluebutton#3738]
I have integrated BBB with moodle and it successfully works with Flash on desktop. On mobile devices it shows the option of HTML5 but nothing happens after clicking the button. Though the HTML5 demo is working fine.

Please suggest.

**Comment by ffdixon** [comment]
We're still working on getting a developer build of the HTML5 client out to the community.  We're getting close.  When we have it ready, we'll be making an announcement to [bigbluebutton-dev](https://groups.google.com/forum/#!forum/bigbluebutton-dev) mailing list.

**Comment by ffdixon** [comment]
Merged into https://github.com/bigbluebutton/bigbluebutton/issues/1605
