### ISSUE TITLE
Chrome Recording Playback "Full Screen" provides download of WEBM which is partial recording.

### ISSUE THREAD

**Issue by hostbbb** [bigbluebutton/bigbluebutton#3739]
In Chrome 55+

When playing 1.1 recording, and you full screen.. a download button appears.

1) Misleading to user, since it is just the webm and not complete recording.
2) Some schools desire to not make recording content easily downloadable to be shared with non paying customers.

Even if you disable the button, you can right click and get "Save As" context option.

http://stackoverflow.com/questions/41115801/in-chrome-55-prevent-showing-download-button-for-html-5-video   

I tried adding the above hack to acornmedia.player.base.css,  unsuccessfully.  Think because its the builtin chrome mediaplayer.

Chrome Dev discussions.
https://productforums.google.com/forum/#!topic/chrome/1WXSi6BzK9M

Looks like popcorn.js project is not very active, did not see any issues open.

**Comment by capilkey** [comment]
I think a better option would be to change the full screen button to make the page full screen rather than the video tag. If we did it that way the native controls wouldn't appear.

Also, popcorn.js has been out of development for a while now and doesn't really have any impact with this.

**Comment by pedrobmarin** [comment]
Part of the fullscreen issue was resolved with the new playback. We can move this discussion to https://github.com/bigbluebutton/bbb-playback if this is still a concern.
