### ISSUE TITLE
1.0 and 1.1 DID Dialing,  existing users in conf do not appear in users list.

### ISSUE THREAD

**Issue by hostbbb** [bigbluebutton/bigbluebutton#3741]
1) Dialin to a conference with DID ahead on first bbb user join.
2) Then create a meeting, and join the same vbridge conf id.

User is in conference in stealth mode, and can hear everything but moderator does not know they are there.

Correct behavior.  bbb should check if any existing users and add them to users list on join.   Then subsequent ESL events work fine.   (Felipe has implement this in mconf branch for telco)

**Comment by ffdixon** [comment]
Here is a single dialplan from Stephen to prevent incoming callers

~~~xml
<extension name="from_my_provider">
 <condition field="destination_number" expression="^8133640854$">
   <action application="answer"/>
   <action application="sleep" data="500"/>
   <action application="play_and_get_digits" data="5 5 3 7000 # conference/conf-pin.wav ivr/ivr-that_was_an_invalid_entry.wav pin \d+"/>
   <action application="transfer" data="SEND_TO_CONFERENCE XML public"/>
 </condition>
</extension>
<extension name="check_if_conference_active">
 <condition field="${conference ${pin} list}" expression="/sofia/g" />
 <condition field="destination_number" expression="^SEND_TO_CONFERENCE$">
   <action application="set" data="bbb_authorized=true"/>
   <action application="transfer" data="${pin} XML default"/>
 </condition>
</extension>
~~~

Stephen, we've updated the documentation at

  http://docs.bigbluebutton.org/1.1/install.html#add-a-phone-number-to-the-conference-bridge

Let us know if you see anything that still needs improvement.
