### ISSUE TITLE
BBB 1.1, systemd - abort Freeswitch, Audio does not work

### ISSUE THREAD

**Issue by tiket18** [bigbluebutton/bigbluebutton#3742]
It is installed from the repository on 03/20/2017. The service does not start. Rights and folders checked. Minor edits of the startup file do not help. In this case, if you start the service with your hands, it works. But sound is not recorded.
Log's -
ll /var/freeswitch/meetings/
total 12
drwxr-xr-x 2 freeswitch daemon 4096 Mar 21 19:19 ./
drwxr-xr-x 3 freeswitch daemon 4096 Mar 20 11:56 ../
-rw-r--r-- 1 freeswitch daemon   48 Mar  3 19:46 readme.txt

manual start -
/opt/freeswitch/bin/freeswitch -u freeswitch -g daemon -ncwait
-nonat

systemctl -

systemctl status freeswitch.service
● freeswitch.service - freeswitch
   Loaded: loaded (/lib/systemd/system/freeswitch.service; enabled;
vendor preset: enabled)
   Active: inactive (dead) (Result: exit-code) since Tue 2017-03-21
21:22:33 MSK; 4s ago
  Process: 1011 ExecStart=/opt/freeswitch/bin/freeswitch -u freeswitch
-g daemon -ncwait $DAEMON_OPTS (code=exited, status=214/SETSCHEDULER)

Mar 21 21:22:32 b systemd[1]: Failed to start freeswitch.
Mar 21 21:22:32 b systemd[1]: freeswitch.service: Unit entered failed state.
Mar 21 21:22:32 b systemd[1]: freeswitch.service: Failed with result
'exit-code'.
Mar 21 21:22:33 b systemd[1]: freeswitch.service: Service hold-off time
over, scheduling restart.
Mar 21 21:22:33 b systemd[1]: Stopped freeswitch.
Mar 21 21:22:33 b systemd[1]: freeswitch.service: Start request repeated
too quickly.
Mar 21 21:22:33 b systemd[1]: Failed to start freeswitch.
root@b:/# nano /lib/systemd/system/freeswitch.service
root@b:/# systemctl daemon-reload
root@b:/# systemctl restart freeswitch.service
Job for freeswitch.service failed because the control process exited
with error code. See "systemctl status freeswitch.service" and
"journalctl -xe" for details.
root@b:/#

ll /opt/freeswitch/
total 36
drwxr-xr-x 9 freeswitch daemon 4096 Mar 21 19:14 ./
drwxr-xr-x 3 root       root   4096 Mar 20 11:56 ../
drwxr-xr-x 2 freeswitch daemon 4096 Mar 20 11:56 bin/
lrwxrwxrwx 1 freeswitch daemon   16 Mar  3 19:46 conf -> ./etc/freeswitch/
drwxr-xr-x 3 freeswitch daemon 4096 Mar 20 11:56 etc/
drwxr-xr-x 3 freeswitch daemon 4096 Mar 20 11:56 include/
drwxr-xr-x 4 freeswitch daemon 4096 Mar 20 11:56 lib/
lrwxrwxrwx 1 freeswitch daemon   20 Mar  3 19:46 log ->
./var/log/freeswitch/
drwxr-xr-x 3 freeswitch daemon 4096 Mar 20 11:56 share/
drwxr-x--- 4 freeswitch daemon 4096 Mar 21 19:14 sounds/
drwxr-xr-x 5 freeswitch daemon 4096 Mar 20 11:56 var/

**Comment by ffdixon** [comment]
Hi tiket18,

Can we get you to post this to our BigBlueButton-setup mailing list, see

  https://groups.google.com/forum/#!forum/bigbluebutton-setup

Be sure to double-check that your system meets the minimum requirements for 1.1-beta, see

  http://docs.bigbluebutton.org/1.1/install.html#minimum-server-requirements

If in helping you in the forum we find a bug in BigBlueButton, we'll open an issue to track it here.  We'll look out for your post in the above mailing list and will respond there.

**Comment by tiket18** [comment]
Ubuntu 16.04 64-bit OS
    64 GB of memory 
    8 core 3.x GHZ CPU (or faster)
    TCP ports 80, 443,and 1935 are accessible
    TCP port 7443 is accessible if you intend to configure SSL (recommended), otherwise port 5066 is accessible
    UDP ports 16384 - 32768 are accessible
    Port 80 is not in use by another application
    1000 Mbits/sec bandwidth (symmetrical)

Agree, it should not be so - automatic start does not work, starting in manual mode does not work. A sound recording file is not created.

**Comment by ffdixon** [comment]
Hi Tiket18, 

Can we get you to post this to our bigbluebutton-setup group -- that's the best forum for handling configuration-type issues.  That way, the rest of the community can help out.

**Comment by tiket18** [comment]
If it were not for my Google-English, I would be happy.
I can offer ssh you an input on the working server - see for yourself.
