### ISSUE TITLE
Improve smoothness of the drawn pencil lines on the whiteboard

### ISSUE THREAD

**Issue by capilkey** [bigbluebutton/bigbluebutton#3745]
Currently we take the mouse positions that we are given and we use those exact positions to draw a line on the screen to create our pencil annotations. The downside to this approach is that you can get jagged lines in some cases and words can be hard to read when drawn with the pencil. If we applied a smoothing algorithm to the line either while drawing or after the user finished the line it would improve the quality of the line.

![whiteboardpencilquality](https://cloud.githubusercontent.com/assets/1395090/24215094/08a68a66-0f0e-11e7-9628-69281be6e9d0.png)

(Click on the image to view the original to see the jagged lines)

Original report with image can be found here, https://groups.google.com/forum/?fromgroups=#!topic/bigbluebutton-setup/r5hDOgeVDi0.

**Comment by ffdixon** [comment]
Done in BigBlueButton 2.0-dev

![image](https://user-images.githubusercontent.com/290351/29470870-0afa14bc-841c-11e7-8e8a-87029057e2dc.png)
