### ISSUE TITLE
[HTML5] Can HTML5 server installed separately from BBB Core ?

### ISSUE THREAD

**Issue by meshwara** [bigbluebutton/bigbluebutton#3772]
First of all, may be this is a silly question.

Can we install BBB-HTML5 separately from "BBB-core" ? 
I just imagine that i can provide 1 server with high spec for BBB-core and multiple server with lower spec form BBB-HTML5 server. So every BBB-HTML5 request can be distributed in many server.

Thanks.

**Comment by antobinary** [comment]
Hey Meshwara,
The HTML5 client (BBB-HTML5) communicates with BBB-core via redis pubsub. The model we have used so far was 1 BBB-HTML5 talking to 1 BBB-core on the same server only. We have not looked at the model you describe. BBB-HTML5 (server side) is built to represent the entire set of meetings and users, so having N x BBB-HTML5 on this codebase will not really be considered 'scaling'.
On a different note, please ask any future development questions at https://groups.google.com/forum/#!forum/bigbluebutton-dev
