### ISSUE TITLE
Syntax error in /usr/bin/bbb-conf line 1367

### ISSUE THREAD

**Issue by floh79** [bigbluebutton/bigbluebutton#3777]
Affected version: BigBlueButton 1.1 Beta

At Line 1367 I get syntax error. I examined and found out that its because of german language. At line 154 there is a problem if your language is not english since there is 'grep Mem'.

German free looks like:
f.erfurth@ConferenceDev-1:~$ free -m
              gesamt       benutzt     frei      gemns.  Puffer/Cache verfügbar
Speicher:        3951        1027        2488           5         435        2690
Auslagerungsspeicher:        4093           0        4093

That is why variable $MEM is empty in my case.

So I'd suggest following patch by using /proc/meminfo instead of free:
```
--- /usr/bin/bbb-conf	2017-04-04 11:47:41.799927519 +0200
+++ bbb-restart-fix.sh	2017-04-04 11:59:04.209721813 +0200
@@ -151,7 +151,7 @@
 	IP=$(ifconfig | grep -v '127.0.0.1' | grep -E "[0-9]*\.[0-9]*\.[0-9]*\.[0-9]*" | tail -1 | cut -d: -f2 | awk '{ print $1}')
 fi
 
-MEM=`free -m | grep Mem | awk '{ print $2}'`
+MEM=`grep MemTotal /proc/meminfo | awk '{print $2}'`
 
 
 #
@@ -1364,7 +1364,7 @@
                 echo
         fi
 
-        if (( $MEM < 3940 )); then
+        if (( $MEM < 3940000 )); then
 		echo "# Warning: You are running BigBlueButton on a server with less than 4G of memory.  Your"
 		echo "# performance may suffer."
                 echo
```

cu Floh

**Comment by kepstin** [comment]
Hi,

For the moment we only support servers running in the "en_US.UTF-8" locale, please see the installation docs: http://docs.bigbluebutton.org/1.1/install.html#check-server-specs

We'll probably apply the fix that you've suggested, but there's likely to be other places in the scripts with similar assumptions, or subtle breakages.

Note that the language set on the server console is independent of the language in the BigBlueButton user interface.
