### ISSUE TITLE
[HTML5] The user remains in the userlist if exited via tab close

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#3785]
If the user logs out of the meeting, he is removed from the userlist (and the meeting).
However, if the user simply closes the browser tab, that user remains in the meeting (and is visible in the userlist)

**Comment by Klauswk** [comment]
Close, fix on commit 82a301817161526f557f89df0b9a9234aeeaec6b

**Comment by antobinary** [comment]
Fixed in #3788
