### ISSUE TITLE
Notify users when joining audio to use either FireFox or Chrome

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#3797]
To help users choose a browser that gives better audio, modify the join audio dialog to give the suggestion to use FireFox or Chrome if they are using a different browser.

![image](https://cloud.githubusercontent.com/assets/290351/24866368/ca30af2a-1e01-11e7-9240-b10708d156ea.png)

If they are using FireFox or Chrome, don't show the suggestion (the dialog box looks the same as before).

The format for the callout text should follow the same as in the File Upload dialog

![image](https://cloud.githubusercontent.com/assets/290351/24866411/ee46988e-1e01-11e7-8345-25e422487a7f.png)

**Comment by GhaziTriki** [comment]
Merged in #3800
