### ISSUE TITLE
Flash client does not load in Microsoft Edge 15

### ISSUE THREAD

**Issue by kepstin** [bigbluebutton/bigbluebutton#3812]
In Edge 15, the plugin detection code in swfobject doesn't seem to work, so you get a screen saying
> You need Adobe Flash installed and enabled

even on systems where it *is* installed and enabled.

A few things we should look at:
- Try a newer version of the `swfobject.js` library to see if it handles this better
- Instead of detecting whether flash is available and loading the client if it is, we should try to load the client and display fallback content if it fails to load

**Comment by kepstin** [comment]
So it turns out that if you click the 'Get Flash' download button in Edge, instead of taking you to the flash download page, it actually opens an 'Allow Flash?' prompt, and will reload the page with flash enabled if you click yes. This isn't obvious, and we should still try to get a better UI experience for people running Edge.

**Comment by ffdixon** [comment]
> it actually opens an 'Allow Flash?' prompt, and will reload the page with flash enabled if you click yes.

It's the same experience on Chrome before we modified BigBlueButton.html to detect for Chrome and, if found, just load the Flash directly.

We added some code to directly load the BigBlueButton client when running under Chrome

  https://github.com/bigbluebutton/bigbluebutton/blob/master/bigbluebutton-client/resources/prod/BigBlueButton.html#L69

We could take a similar approach for Edge.

**Comment by ffdixon** [comment]
I think we could easily add detection for Edge

  http://stackoverflow.com/questions/31721250/how-to-target-windows-10-edge-browser-with-javascript
