### ISSUE TITLE
Before publishing a presentation, perform sanity check

### ISSUE THREAD

**Issue by ritzalam** [bigbluebutton/bigbluebutton#3819]
Before publishing the presentation, perform sanity check to make sure generated files have valid formats.

```
 metadata.xml
 captions.json
 cursor.xml
 panzooms.xml
 slides_new.xml
```

**Comment by ffdixon** [comment]
@kepstin Is this an issue with 2.2-beta?

**Comment by kepstin** [comment]
Most of this isn't really necessary - only the metadata.xml should be checked, since it's the only thing that's recording-independent. But very low priority - and it would be better to make bbb-web recording api more resilient to errors instead.
