### ISSUE TITLE
1.1beta Screen share crashes on new Surface Pro laptop,

### ISSUE THREAD

**Issue by hostbbb** [bigbluebutton/bigbluebutton#3821]
New windows 10, surface pro laptop. I7/16gb ram   Both on firefox and chrome.   applet throws exception.

Log started: Fri, 14 Apr 2017 15:50:06 -0400
Java Web Start 11.121.2.13
Using JRE version
 1.8.0_121-b13 Java HotSpot(TM) Client VM
Using passed args: length=[9]
Using passed args: [rtmp://demo.bigbluebutton.org/screenshare/607291d8938cea761ce81390b8af92925308430f-1492199367437] meetingId=[607291d8938cea761ce81390b8af92925308430f-1492199367437] streamId=[607291d8938cea761ce81390b8af92925308430f-1492199367437-1492199398873-1] captureFullScreen=true
========== SYSTEM PROPERTIES ================ 
Java temp dir : C:\Users\sdame\AppData\Local\Temp\
Java name : Java HotSpot(TM) Client VM
OS name : Windows 10
OS arch : x86
JNA Path : null
========== END SYSTEM PROPERTIES ================ 
org.bytedeco.javacpp.logger.debug : true
Sharing full screen.
Check for scaling[3840,2160][800,600]
ScreenShareInfo[captureWidth=3840,captureHeight=2160][0,0][scaleWidth=800,scaleHeight=600]
DESKSHARECLIENT: Sharing full screen.
ScreenSharerRunner[captureWidth=3840,captureHeight=2160][0,0][scaleWidth=800,scaleHeight=600]
Waiting for trigger to Stop client.
sendUpdateMessage sharingStart = [START]
SCREENREGIONSHARER: starting. StreamId=607291d8938cea761ce81390b8af92925308430f-1492199367437-1492199398873-1 fullScreen=true
SCREENREGIONSHARER: Launching Screen Capture Frame
SCREENREGIONSHARER:  - Launching Screen Capture Frame:: x=0,y=0,w=3840,h=2160
SCREENREGIONSHARER: Starting Screen Capture Frame. StreamId=607291d8938cea761ce81390b8af92925308430f-1492199367437-1492199398873-1 fullScreen=true
Loading start time: 2017.04.14 AD at 15:50:11 EDT
Hiding controls ......................
Loading end time: 2017.04.14 AD at 15:50:11 EDT
CaptureRegionFrame - startCapture:: Change border to blue
SCREENREGIONSHARER:  - onStartCapture x=0,y=0,w=3840,h=2160
Publishing stream [607291d8938cea761ce81390b8af92925308430f-1492199367437-1492199398873-1] to rtmp://demo.bigbluebutton.org/screenshare/607291d8938cea761ce81390b8af92925308430f-1492199367437/607291d8938cea761ce81390b8af92925308430f-1492199367437-1492199398873-1
Java temp dir : C:\Users\sdame\AppData\Local\Temp\
Java name : Java HotSpot(TM) Client VM
OS name : Windows 10
OS arch : x86
JNA Path : null
Platform : windows-x86
Platform lib path: C:\Program Files (x86)\Java\jre1.8.0_121\bin;C:\windows\Sun\Java\bin;C:\windows\system32;C:\windows;C:\Program Files (x86)\Java\jre1.8.0_121\bin;C:\Program Files (x86)\Mozilla Firefox;C:\ProgramData\Oracle\Java\javapath;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Skype\Phone\;C:\Users\sdame\AppData\Local\Microsoft\WindowsApps;;"C:\Program Files (x86)\Java\jre1.8.0_121\bin";.
Capturing w=[3830] h=[2150] at x=[5] y=[5]
URL=rtmp://demo.bigbluebutton.org/screenshare/607291d8938cea761ce81390b8af92925308430f-1492199367437
useH264=false
CODEC_OPTS=crf=38&preset=veryfast&tune=zerolatency&frameRate=5.0&keyFrameInterval=5
OPTION: crf=38
OPTION: preset=veryfast
OPTION: tune=zerolatency
OPTION: frameRate=5.0
OPTION: keyFrameInterval=5
Setting up grabber for windows.
JNLPClassLoader: Finding library avutil-55.dll
JNLPClassLoader: Finding library jniavutil.dll
JNLPClassLoader: Finding library swresample-2.dll
JNLPClassLoader: Finding library jniswresample.dll
JNLPClassLoader: Finding library avcodec-57.dll
JNLPClassLoader: Finding library jniavcodec.dll
JNLPClassLoader: Finding library avformat-57.dll
JNLPClassLoader: Finding library jniavformat.dll
JNLPClassLoader: Finding library swscale-4.dll
JNLPClassLoader: Finding library jniswscale.dll
JNLPClassLoader: Finding library avfilter-6.dll
JNLPClassLoader: Finding library jniavfilter.dll
JNLPClassLoader: Finding library avdevice-57.dll
JNLPClassLoader: Finding library jniavdevice.dll
Registering org.bytedeco.javacpp.avcodec$AVPacket[address=0x17be228,position=0,limit=1,capacity=1,deallocator=org.bytedeco.javacpp.Pointer$NativeDeallocator[ownerAddress=0x17be228,deallocatorAddress=0x6a3c1e40]]
Registering org.bytedeco.javacpp.avcodec$AVPacket[address=0x17be960,position=0,limit=1,capacity=1,deallocator=org.bytedeco.javacpp.Pointer$NativeDeallocator[ownerAddress=0x17be960,deallocatorAddress=0x6a3c1e40]]
==== CODEC OPTIONS =====
Key = keyFrameInterval, Value = 5
Key = frameRate, Value = 5.0
Key = crf, Value = 38
Key = preset, Value = veryfast
Key = tune, Value = zerolatency
==== END CODEC OPTIONS =====
Using SVC2 codec
Registering org.bytedeco.javacpp.avcodec$AVPacket[address=0x17b4e58,position=0,limit=1,capacity=1,deallocator=org.bytedeco.javacpp.Pointer$NativeDeallocator[ownerAddress=0x17b4e58,deallocatorAddress=0x6a3c1e40]]
Registering org.bytedeco.javacpp.avcodec$AVPacket[address=0x17b4ea8,position=0,limit=1,capacity=1,deallocator=org.bytedeco.javacpp.Pointer$NativeDeallocator[ownerAddress=0x17b4ea8,deallocatorAddress=0x6a3c1e40]]
Registering org.bytedeco.javacpp.avutil$AVRational[address=0x17bebe0,position=0,limit=1,capacity=1,deallocator=org.bytedeco.javacpp.Pointer$NativeDeallocator[ownerAddress=0x17bebe0,deallocatorAddress=0x70001990]]
Exception starting grabber.
SCREENREGIONSHARER: Closing. Reason=500
Trigger stop client. 5
Triggered stop client. reason=500
Stopping Java Web Start.

**Comment by ffdixon** [comment]
Got it -- will take a closer look.

**Comment by hostbbb** [comment]
fyi...  tried the h264 version on moodle cloud, same results.  will bring device to summit.

**Comment by ffdixon** [comment]
Closing this issue as we are moving to an HTML5 client (and using WebRTC for desktop sharing).
