### ISSUE TITLE
Win10 Chrome Version 58.0.3029.81 (64-bit)  Surface Pro presentation UPLOAD button does not work

### ISSUE THREAD

**Issue by hostbbb** [bigbluebutton/bigbluebutton#3841]
Win10 Chrome Version 58.0.3029.81 (64-bit)  Surface Pro presentation UPLOAD button does not work

tested on 1.0 and 1.1beta.  does not work on either.

you can select the file, and it shows in form.  the upload button highlights and is clickable.  but clicking does nothing.

I searched adobe flash and chrome issue trackers did not see anything.

Firefox and Edge upload work fine.

Loading the chrome flash debugger to see if i can see the issue.

**Comment by ffdixon** [comment]
Thanks for sharing this -- we'll try it on our end as well.

**Comment by hostbbb** [comment]
After updating and testing,  Chrome now uploads presentations on 1.1RC and 1.0 Server.  So issue can be closed.  Can not replicate.

**Comment by ffdixon** [comment]
Thanks Stephen!  Don't hesitate to let us know if you find anything else.
