### ISSUE TITLE
HTML5: Truncate username on user action pop-up

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#3846]
![truncate](https://cloud.githubusercontent.com/assets/6312397/25354589/747a7272-2901-11e7-9ae8-fbce2bf9740b.png)

We need to truncate the username in this dialogue (see attached image). This is especially visible on mobile, portrait mode

**Comment by capilkey** [comment]
If both versions of a user's name are truncated there won't be any way to see the full name. I brought this up before, but we might want the name in a tooltip or something instead so the end doesn't get cut off.

**Comment by antobinary** [comment]
As part of this issue, please address the following: due to truncating, the unread messages counter (on the username line) never shows

**Comment by antobinary** [comment]
Fixed in #3860
