### ISSUE TITLE
Upload a sub-rip title file to add captions to a recording

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#3864]
Extend the API to enable a 3rd party front-end to POST a sub-rip title file (SRT file) to the BigBlueButton server along with the recording ID.

The BigBlueButton server should then reprocess the recording and use the SRT file to place subtitles in the playback.

**Comment by browniecab** [comment]
We will need to add two new API calls to the server to get and upload captions, as described in the attached document.
[apicalls.docx](https://github.com/bigbluebutton/bigbluebutton/files/2040741/apicalls.docx)

**Comment by GhaziTriki** [comment]
@kepstin I think we have implemented it a time go. Can we safely close this issue?

**Comment by ffdixon** [comment]
@kepstin bump

**Comment by ffdixon** [comment]
@kepstin, is this issue covered by: https://github.com/bigbluebutton/bigbluebutton/issues/7263 ?
