### ISSUE TITLE
For viewers display screen sharing window centered in screen

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#3866]
Currently, the screen sharing window is displayed upper left-hand corner.  Start screen sharing in the center of the screen, with height slightly less than maximum height to show top and bottom portions of windows behind the screen sharing.

For example,

![image](https://cloud.githubusercontent.com/assets/290351/25533692/79c02d70-2bff-11e7-9d26-4a2a70e79bb2.png)

Also, make the screen sharing window operate like the video dock in that it can be an arbitrary size and the screen sharing fits within the center of the window.

**Comment by GhaziTriki** [comment]
This has been implemented into 2.0.
