### ISSUE TITLE
Playback in FireFox does not swap presentation and video correctly

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#3868]
Swapping the presentation and video in FireFox during playback causes the presentation area to become misaligned.

Here's a video demonstrating the issue

 https://youtu.be/8G1L_osdVBc

And here's a sample recording to reproduce

  https://demo.bigbluebutton.org/playback/presentation/0.9.0/playback.html?meetingId=9604e3f2a3ef11efa9ff346c5e173edbc43aa692-1493390833823

**Comment by pedrobmarin** [comment]
Hi Fred! The problem was a NPE when trying to load some SVG objects. I'm sending the pull request to fix it.

**Comment by ffdixon** [comment]
Confirmed it's fixed in 2.0 -- thanks Pedro!
