### ISSUE TITLE
A empty (or malformed) metadata.xml will break getRecordings

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#3882]
Currently, if a `metadata.xml` file in the publish directory, such as `/var/bigbluebutton/published/presentation/<internal-meeting-ID>/metadata.xml` is empty or has malformed XML, the getRecordings API call will fail.

Such a `metadata.xml` may be created if the BigBlueButton server temporarily runs out of disk space.

The `getRecordings` should skip over malformed XML `metadata.xml` files so that `getRecordings` always returns.

**Comment by ffdixon** [comment]
@GhaziTriki Is this an issue with 2.2-beta?

**Comment by GhaziTriki** [comment]
@ffdixon Can you please assign it to me since I dealing with some API issues. I will include it to my testings.

**Comment by GhaziTriki** [comment]
@ffdixon Cannot be reproduced. We can close it.

**Comment by ffdixon** [comment]
Thanks Ghazi.
