### ISSUE TITLE
HTML5: Mobile view of Closed Captions currently takes over the entire screen

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#3927]
![screenshot from 2017-05-10 10-32-50](https://cloud.githubusercontent.com/assets/6312397/25904086/2b65c920-356c-11e7-80bb-30eae9abe12e.png)

- [ ] restrict the area where the closed captions component is displayed so that the navbar is always visible

- [ ] in portrait view mode fit the CC component under the whiteboard (above the actions buttons)

**Comment by antobinary** [comment]
Design for desired portrait mode view (credit goes to @capilkey )

![mobilepresentationwithcc](https://cloud.githubusercontent.com/assets/6312397/25966886/5e97f8b0-365a-11e7-9cd2-8ccd9a9e3e29.png)

**Comment by tylercopeland** [comment]
@antobinary the approach that @capilkey provided above is the one I think we should use. Attached is a more refined mockup. 

![closed captioning](https://user-images.githubusercontent.com/1273169/33438348-904ccab8-d5b8-11e7-87af-eeca2cb6227c.png)

**Comment by antobinary** [comment]
Thank you, @tylercopeland @capilkey

**Comment by OZhurbenko** [comment]
@antobinary but we have this implemented, don't we?
Maybe just need to correct the height, but the portrait layout (including small screens) is already there.

![closed_captions](https://user-images.githubusercontent.com/9299997/33511603-93ff02e6-d6eb-11e7-845a-5c84c52df0fd.JPG)

**Comment by OZhurbenko** [comment]
@antobinary and it was merged in May, #3940

**Comment by antobinary** [comment]
Wow! My bad! But I'm glad it's fixed! :)
