### ISSUE TITLE
presenterShareOnly="true" on VideoConfModule not working

### ISSUE THREAD

**Issue by hostbbb** [bigbluebutton/bigbluebutton#3936]
presenterShareOnly="true" on VideoConfModule not working

Test 1.1,  this has no effect,  not sure if the same property on PhoneModule has same issue.

The workaround is to use the lock settings.
<lock **disableCamForLockedUsers="true"** disableMicForLockedUsers="false" disablePrivateChatForLockedUsers="false" disablePublicChatForLockedUsers="false" lockLayoutForLockedUsers="false" **lockOnJoin="true"** lockOnJoinConfigurable="false"/>

**Comment by ffdixon** [comment]
Thanks Stephen for catching this. We'll fix it in 1.1-RC.

**Comment by capilkey** [comment]
We've decided to just remove the old properties (presenterShareOnly for audio and video). The same functionality can be accomplished with the lock settings. The only difference is that the lock settings can be turned off by a moderator whereas the old properties were in place for the whole meeting, but that is an alright compromise I think.

**Comment by GhaziTriki** [comment]
This issue can be closed.
