### ISSUE TITLE
Move away from Flash Player 11.2 to a newer version

### ISSUE THREAD

**Issue by GhaziTriki** [bigbluebutton/bigbluebutton#3962]
As Flash Player is officially supported again under Linux platforms we should move forward and use the a newest version. Here a list of Flash features we may need:
- ActionScript Workers (FP 11.4) 
- LZMA support for ByteArray (FP 11.4)
- Native JSON marshalling/unmarshalling.
- Enhanced Supplementary Character Support for TextField(FP 13)
- Added ability to disable browser zoom factor scaling via HTML(FP 19)
- Override Flash Player's default language via mms.cfg(FP 22)
- HSTS Support in Flash Player(FP 23)
- Spherical video support in Flash and AIR(FP 24)
- Separate HTTP and HTTPS permissions for Camera and Microphone(FP 24)
- Force users to have the security fixes since April 13th ,2012.

This only a selection of new features, the API has more new features.

**Comment by ffdixon** [comment]
We're now at Flash Player 28.  Closing this issue :-).
