### ISSUE TITLE
HTML5-client / Android 6.0 / BBB 1.10 screensharing doesn't show up at all

### ISSUE THREAD

**Issue by Jarvil** [bigbluebutton/bigbluebutton#3974]
Hello,

When joining a session with HTML5-client / Android 6.0 in BBB version 1.10 screensharing doesnt show up at all, you can only see the presentation window but nothing else.

**Comment by Jarvil** [comment]
It should work stated here;

http://docs.bigbluebutton.org/html/html5-overview.html#first-release

**Comment by antobinary** [comment]
Hey Jarvil, the HTML5 client is under development. There was an initial *development* release out but there is still work ahead, including screenshare stream viewing

**Comment by antobinary** [comment]
Addressed in https://github.com/bigbluebutton/bigbluebutton/pull/4738

**Comment by antobinary** [comment]
Addressed in #4661 
Further work on handling edge cases is underway
