### ISSUE TITLE
HTML5 client audio doesn't work with iPad (iOS 10.3.1) & BBB 1.10

### ISSUE THREAD

**Issue by Jarvil** [bigbluebutton/bigbluebutton#3975]
Hello,

HTML5 client audio doesn't work with iPad (iOS 10.3.1) & Safari 10.0 & BBB 1.10.  When you join a meeting you can select audio or microphone -> you select microphone -> you cannot any select audio input/output devices. You can record with other programs normally with this same iPad.

<hr>

![rel1](https://cloud.githubusercontent.com/assets/15193418/26580151/91aa53e4-453f-11e7-9fa6-29ee764800d0.PNG)

![rel2](https://cloud.githubusercontent.com/assets/15193418/26580156/95eea630-453f-11e7-8790-583c886ef47d.PNG)

**Comment by Jarvil** [comment]
It should work stated here;

http://docs.bigbluebutton.org/html/html5-overview.html#first-release

**Comment by antobinary** [comment]
Hey Jarvil,
From the same link you refer to:
`This means FireFox and Chrome on the desktop, Chrome on the Chromebook, and Chrome or FireFox on an Android phone or tablet can (...)`
Browsers on iPad do not support WebRTC calls as of now. While this may change in the future, we are looking into alternatives for iOS. For Android and Chrome/FireFox on desktop the audio works. Stay tuned for updates related to iOS and HTML5 client (as it makes its way towards beta and stable releases)

**Comment by Bellusterra** [comment]
Bigbluebutton appears to be a great tool for collaborating. The audio for a reason that I’m sure is hard to fix is and has been for a very long time broken up and intermittent. Also other then on android devices the is no way to get the audio to work on iOS I have tried Firefox, chrome, safari and Facebook built in browser all with no success and with different iOS devices on the big blue demo server. I really like the collaborative drawing feature everyone has done a great job with it, just hope that those other things can be worked out.

**Comment by Bellusterra** [comment]
Hi Fred,
  Okay did some more testing and found some things that might help. I have 3 iOS devices iPhone 5 and 8+ and an iPad and one android device. The two iPhones are running iOS 12 just updated yesterday. The iPhone 5 works as expected on Safari only, tested on chrome facebooks browser and Firefox asks to enable audio with now way to actually do it that I’m aware. Where Safari handles it.. iPad runnning iOS 10.3.3 audio did not work on any web browser platform. Android worked only with google chrome. And the oddest one was the iPhone 8+ and the one I was using the other day after writing the first comment it fails the echo test! But found today that it is actually working just fine when I hit the green thumbs up that I can hear myself when I actually don’t hear the echo. I would think that might have more to do with iOS then on your end. Seems really odd that the two iOS devices both on iOS 12 and Safari would behave differently. And the audio is clear now and works perfect.

**Comment by ffdixon** [comment]
@Bellusterra -- thanks for the feedback.  We have a couple more updates for Safari on iOS coming in 2.0-RC7.  Keep an eye out in [bigbluebutton-dev](https://groups.google.com/forum/#!forum/bigbluebutton-dev) for updates.  We leave this ticket open until we release RC7 and get your feedback.

**Comment by Bellusterra** [comment]
@ffdixon sounds good, Thank you Fred..

**Comment by ffdixon** [comment]
Closing as audio now works on iOS 12.2+ using Safari mobile.

**Comment by tavakoli-ali** [comment]
now I'm testing on iPhone 7 Plus with iOS 13.4.5 and mic doesn't work
