### ISSUE TITLE
BBB 1.1, Does not record a sound. 

### ISSUE THREAD

**Issue by tiket18** [bigbluebutton/bigbluebutton#3979]
**### I have already made such a request. The problem is not solved.
BBB 1.1. Ubuntu 16.04. Running as a service does not work. Running with the command 
@reboot /opt/freeswitch/bin/freeswitch -u freeswitch -g daemon -ncwait -nonat
 works, but no sound is recorded. Writes everything except the sound.
root@bbb:/# systemctl start freeswitch
Job for freeswitch.service failed because the control process exited with error code. See "systemctl status freeswitch.service" and "journalctl -xe" for details.
root@bbb:/# 

systemctl status freeswitch.service
● freeswitch.service - freeswitch
   Loaded: loaded (/lib/systemd/system/freeswitch.service; enabled; vendor preset: enabled)
   Active: inactive (dead) (Result: exit-code) since Fri 2017-06-02 01:33:37 MSK; 4s ago
  Process: 2394 ExecStart=/opt/freeswitch/bin/freeswitch -u freeswitch -g daemon -ncwait $DAEMON_OPTS (code=exited, status=214/SETSCHEDULER)

Jun 02 01:33:37 bbb systemd[1]: Failed to start freeswitch.
Jun 02 01:33:37 bbb systemd[1]: freeswitch.service: Unit entered failed state.
Jun 02 01:33:37 bbb systemd[1]: freeswitch.service: Failed with result 'exit-code'.
Jun 02 01:33:37 bbb systemd[1]: freeswitch.service: Service hold-off time over, scheduling restart.
Jun 02 01:33:37 bbb systemd[1]: Stopped freeswitch.
Jun 02 01:33:37 bbb systemd[1]: freeswitch.service: Start request repeated too quickly.
Jun 02 01:33:37 bbb systemd[1]: Failed to start freeswitch.

ll /var/freeswitch/
total 12
drwxr-xr-x  3 freeswitch freeswitch 4096 May 28 22:32 ./
drwxr-xr-x 14 root       root       4096 May 28 22:32 ../
drwxr-xr-x  2 freeswitch freeswitch 4096 May 28 22:32 meetings/

freeswitch.log - no errors
bbb-conf --check
yes

BigBlueButton Server 1.1.0 (571)
                    Kernel version: 2.6.32-openvz-042stab113.21-amd64
                      Distribution: Ubuntu 16.04.2 LTS (64-bit)
                            Memory: 33554 MB

/var/www/bigbluebutton/client/conf/config.xml (bbb-client)
  		Port test (tunnel): 138.201.27.242
                              red5: 138.201.27.242
              useWebrtcIfAvailable: true

/opt/freeswitch/etc/freeswitch/sip_profiles/external.xml (FreeSWITCH)
                    websocket port: 5066
                    WebRTC enabled: true

/etc/nginx/sites-available/bigbluebutton (nginx)
                       server name: 138.201.27.242
                              port: 80, [::]:80
                    bbb-client dir: /var/www/bigbluebutton

/var/lib/tomcat7/webapps/bigbluebutton/WEB-INF/classes/bigbluebutton.properties (bbb-web)
                      bbb-web host: 138.201.27.242

/var/lib/tomcat7/webapps/demo/bbb_api_conf.jsp (API demos)
                               url: 138.201.27.242

/var/www/bigbluebutton/check/conf/config.xml (client check)
                      client check: 138.201.27.242

/usr/share/red5/webapps/bigbluebutton/WEB-INF/red5-web.xml (red5)
                  voice conference: FreeSWITCH

/usr/local/bigbluebutton/core/scripts/bigbluebutton.yml (record and playback)
                     playback host: 138.201.27.242

Potential problems described below 
# Warning: API Shared Secret mismatch: 
#  /var/lib/tomcat7/webapps/bigbluebutton/WEB-INF/classes/bigbluebutton.properties  = 2b09a3127a7d31cf97b161b9ddb3b42f
#  /var/lib/tomcat7/webapps/demo/bbb_api_conf.jsp                                   = daaa659babeb315b18e74e28e9c9d908

# Error: Found text in freeswitch.log:
#
#    Thread ended for mod_event_socket
#
# FreeSWITCH may not be responding to requests on port 8021 (event socket layer)
# and users may have errors joining audio.
#

#
# Error: Unable to connect to the FreeSWITCH Event Socket Layer on port 8021
#
# Warning: The voice application may not have registered with the sip server.
#   Try running: 
#
#      sudo bbb-conf --clean
#

# Error: Could not detect FreeSWITCH listening on port 5060

start -
 /opt/freeswitch/bin/freeswitch -u freeswitch -g daemon -ncwait -nonat

bbb-conf --check
yes

BigBlueButton Server 1.1.0 (571)
                    Kernel version: 2.6.32-openvz-042stab113.21-amd64
                      Distribution: Ubuntu 16.04.2 LTS (64-bit)
                            Memory: 33554 MB

/var/www/bigbluebutton/client/conf/config.xml (bbb-client)
  		Port test (tunnel): 138.201.27.242
                              red5: 138.201.27.242
              useWebrtcIfAvailable: true

/opt/freeswitch/etc/freeswitch/sip_profiles/external.xml (FreeSWITCH)
                    websocket port: 5066
                    WebRTC enabled: true

/etc/nginx/sites-available/bigbluebutton (nginx)
                       server name: 138.201.27.242
                              port: 80, [::]:80
                    bbb-client dir: /var/www/bigbluebutton

/var/lib/tomcat7/webapps/bigbluebutton/WEB-INF/classes/bigbluebutton.properties (bbb-web)
                      bbb-web host: 138.201.27.242

/var/lib/tomcat7/webapps/demo/bbb_api_conf.jsp (API demos)
                               url: 138.201.27.242

/var/www/bigbluebutton/check/conf/config.xml (client check)
                      client check: 138.201.27.242

/usr/share/red5/webapps/bigbluebutton/WEB-INF/red5-web.xml (red5)
                  voice conference: FreeSWITCH

/usr/local/bigbluebutton/core/scripts/bigbluebutton.yml (record and playback)
                     playback host: 138.201.27.242

 Potential problems described below 
 API Shared Secret mismatch: 
#  /var/lib/tomcat7/webapps/bigbluebutton/WEB-INF/classes/bigbluebutton.properties  = 2b09a3127a7d31cf97b161b9ddb3b42f
#  /var/lib/tomcat7/webapps/demo/bbb_api_conf.jsp                                   = daaa659babeb315b18e74e28e9c9d908

# Error: Found text in freeswitch.log:
#
#    Thread ended for mod_event_socket
#
# FreeSWITCH may not be responding to requests on port 8021 (event socket layer)
# and users may have errors joining audio.
#

#
# Error: Unable to connect to the FreeSWITCH Event Socket Layer on port 8021
#
# Warning: The voice application may not have registered with the sip server.
#   Try running: 
#
#      sudo bbb-conf --clean
#**

**Comment by ffdixon** [comment]
We don't have much experience with the openvz virtualization, but we suspect it's preventing freeswitch from changing its run priority.

Try applying the changes for [running FreeSWITCH in LXD containers](http://docs.bigbluebutton.org/install/install.html#running-within-an-lxd-container) to see if that enables FreeSWITCH to start.

**Comment by tiket18** [comment]
The issue is not so much that the service does not start - I can also run through the crones when the system starts. The question is why the sound is not recorded.

**Comment by tiket18** [comment]
Thanks for the help - with the corrected startup file the service is started freeswitch on a regular basis. Will this affect the recording of the sound I learn by the evening, please do not close this issue

**Comment by tiket18** [comment]
The service starts, it works, but the sound is not recorded.

**Comment by tiket18** [comment]
inexplicably 
# Error: Found text in freeswitch.log:
#
#    Thread ended for mod_event_socket


ll /opt/freeswitch/var/run/freeswitch/
total 12
drwxr-xr-x 2 freeswitch daemon 4096 Jun  2 11:23 ./
drwxr-xr-x 3 freeswitch daemon 4096 May 28 22:32 ../
-rw------- 1 freeswitch daemon    3 Jun  2 11:23 freeswitch.pid

**Comment by tiket18** [comment]
Starting Nmap 7.40 ( https://nmap.org ) at 2017-06-03 00:13 EEST
Nmap scan report for static.242.27.201.138.clients.your-server.de (138.201.27.242)
Host is up (0.042s latency).
Not shown: 983 closed ports
PORT     STATE    SERVICE
22/tcp   open     ssh
80/tcp   open     http
111/tcp  open     rpcbind
135/tcp  filtered msrpc
139/tcp  filtered netbios-ssn
445/tcp  filtered microsoft-ds
593/tcp  filtered http-rpc-epmap
1935/tcp open     rtmp
2869/tcp filtered icslap
5060/tcp open     sip
5080/tcp open     onscreen
5357/tcp filtered wsdapi
7443/tcp open     oracleas-https
8080/tcp open     http-proxy
8081/tcp open     blackice-icecap
8082/tcp open     blackice-alerts
9999/tcp open     abyss

**Comment by tiket18** [comment]
netstat -ltupn | grep freesw
tcp        0      0 138.201.27.242:8081     0.0.0.0:*               LISTEN      315/freeswitch  
tcp        0      0 138.201.27.242:8082     0.0.0.0:*               LISTEN      315/freeswitch  
tcp        0      0 138.201.27.242:5090     0.0.0.0:*               LISTEN      315/freeswitch  
tcp        0      0 138.201.27.242:5060     0.0.0.0:*               LISTEN      315/freeswitch  
tcp        0      0 138.201.27.242:5066     0.0.0.0:*               LISTEN      315/freeswitch  
tcp6       0      0 ::1:8081                :::*                    LISTEN      315/freeswitch  
tcp6       0      0 ::1:8082                :::*                    LISTEN      315/freeswitch  
tcp6       0      0 ::1:5090                :::*                    LISTEN      315/freeswitch  
tcp6       0      0 ::1:5060                :::*                    LISTEN      315/freeswitch  
udp        0      0 0.0.0.0:1337            0.0.0.0:*                           315/freeswitch  
udp        0      0 138.201.27.242:5060     0.0.0.0:*                           315/freeswitch  
udp        0      0 138.201.27.242:5090     0.0.0.0:*                           315/freeswitch  
udp6       0      0 ::1:5060                :::*                                315/freeswitch  
udp6       0      0 ::1:5090                :::*                                315/freeswitch

**Comment by ffdixon** [comment]
HI there,

> Jun 2 23:50:33 bbb bbb-fsesl-akka[218]: WARNING: EXCEPTION, please implement org.freeswitch.esl.client.inbound.InboundClientHandler.exceptionCaught() for proper handling

We suspect it's an issue with the openvz environment.  We haven't tried running BigBlueButton in such virtualization.

Is it an option for you to run BigBlueButton on a different virtualization environment or dedicated server, see: http://docs.bigbluebutton.org/install/install.html#minimum-server-requirements?

**Comment by tiket18** [comment]
server OK - 64gb, 1gbit, 256gb ssd, 4-core 3.7

**Comment by tiket18** [comment]
BBB v1 Works here - b.loftschool.com.

**Comment by ffdixon** [comment]
Please don't send login credentials to us!  Did you start FreeSWITCH as root?  Check the permissions of the directory `/var/freeswitch/meetings.

They should match the following

~~~
root@t4:/var/freeswitch/meetings# ls -al
total 11
drwxr-xr-x 2 freeswitch freeswitch  3 Mar 20 00:14 .
drwxr-xr-x 3 freeswitch daemon      3 Jan 10 23:42 ..
-rw-r--r-- 1 freeswitch freeswitch 48 Mar 14 00:30 readme.txt
~~~

**Comment by tiket18** [comment]
ll /var/freeswitch/meetings 
total 12
drwxr-xr-x 2 freeswitch daemon 4096 May 28 22:32 ./
drwxr-xr-x 3 freeswitch daemon 4096 May 28 22:32 ../
-rw-r--r-- 1 freeswitch daemon   48 Apr 27 02:05 readme.txt

**Comment by tiket18** [comment]
Is the sound recording tied to the socket?

**Comment by ritzalam** [comment]
The command to tell freeswitch to start/stop recording is sent through the event_socket. So it must be that since the socket got disconnected, BBB wasn't able to communicate to FS to record the conference.

**Comment by tiket18** [comment]
Резюмируем, на великом и могучем (ниже - коротко на гуглоинглише)
Проблема запуска freeswitch в поставке ВВВ в контейнере Openviz заключалась в том, что, -
1. не стартовала служба freeswitch как таковая
2. после починки и старта не создавался сокет, соотв. БББ не получал сигнала для начала записи звука.


Сперва, см. выше, была дана наводка - "running FreeSWITCH in LXD containers", реализация позволила запускать службу. Однако эта реализация сводилась к кастрации файла запуска службы. Потому провел ряд экспериментов и выяснилось, что для корректного запуска службы достаточно закомментировать одну строку -

nano /lib/systemd/system/freeswitch.service
#CPUSchedulingPolicy=rr

перечитать службы, запусить и получить удовольствие -

systemctl daemon-reload
systemctl restart freeswitch


А сокета все равно нет. Переписка выше позволила придти к выводу - да, именно на сокет завязана запись звука. Наводка была в https://freeswitch.org/confluence/display/FREESWITCH/mod_event_socket
прописать в конфиге адрес 127.0.0.1 оказалось недостаточно, надо было еще прибить строку <param name="nat-map" value="false"/>

т.о. решение сокета -
nano /opt/freeswitch/etc/freeswitch/autoload_configs/event_socket.conf.xml
удалить строку -
<param name="nat-map" value="false"/>
указать локальный адрес (вариант :: не катит) -
<param name="listen-ip" value="127.0.0.1"/>

сохранить, bbb-conf --clean

получить удовольствие -

nmap 127.0.0.1

Starting Nmap 7.01 ( https://nmap.org ) at 2017-06-03 16:59 MSK
Nmap scan report for localhost.localdomain (127.0.0.1)
Host is up (0.0000020s latency).
Not shown: 992 closed ports
PORT     STATE SERVICE
80/tcp   open  http
111/tcp  open  rpcbind
1935/tcp open  rtmp
5080/tcp open  onscreen
8021/tcp open  ftp-proxy
8080/tcp open  http-proxy
8100/tcp open  xprint-server
9999/tcp open  abyss

Nmap done: 1 IP address (1 host up) scanned in 0.07 seconds


Briefly - from all that has been said in -  "running FreeSWITCH in LXD containers"

for a normal startup service -
nano /lib/systemd/system/freeswitch.service
#CPUSchedulingPolicy=rr
ctrl+x
systemctl daemon-reload
systemctl restart freeswitch
=OK.

далее,
https://freeswitch.org/confluence/display/FREESWITCH/mod_event_socket

nano 
del-
 <param name="nat-map" value="false"/>

edit -
<param name="listen-ip" value="127.0.0.1"/>

bbb-conf --clean

nmap 127.0.0.1

Starting Nmap 7.01 ( https://nmap.org ) at 2017-06-03 16:59 MSK
Nmap scan report for localhost.localdomain (127.0.0.1)
Host is up (0.0000020s latency).
Not shown: 992 closed ports
PORT     STATE SERVICE
80/tcp   open  http
111/tcp  open  rpcbind
1935/tcp open  rtmp
5080/tcp open  onscreen
8021/tcp open  ftp-proxy
8080/tcp open  http-proxy
8100/tcp open  xprint-server
9999/tcp open  abyss

Nmap done: 1 IP address (1 host up) scanned in 0.07 seconds

**Comment by OZhurbenko** [comment]
```
nano /opt/freeswitch/etc/freeswitch/autoload_configs/event_socket.conf.xml
del-

edit -
```

What exactly did you delete here to make it work? Just curious, it might help somebody else.

P.S. если не сложно, то давайте обойдёмся без "великого и могучего", пожалуйста.

**Comment by tiket18** [comment]
Thanks, did not notice that part of the text fell out
