### ISSUE TITLE
bbb-conf --debug incorrectly flags

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#3985]
Running `bbb-conf --debug` scans through the log files for errors and exceptions.  

It appears that the logic is incorrectly flagging an error in mismatch of the hostnames in published recordings.

~~~
# The hostname in <link> .. </link> (    <link>https://demo.bigbluebutton.org/playback/presentation/0.9.0/playback.html?meetingId=bd036274c1e21ebe9960eb7f2ceee36f556974cc-1495884134601</link>)
#     /var/bigbluebutton/published/presentation/bd036274c1e21ebe9960eb7f2ceee36f556974cc-1495884134601/metadata.xml
# do not match the hostname for bigbluebutton.web.serverURL (demo.bigbluebutton.org)
#     /usr/share/red5/webapps/bigbluebutton/WEB-INF/bigbluebutton.properties
~~~

**Comment by hakaz** [comment]
Tracked the error down to `bbb-record` line 718 ff. which is called by `bbb-conf --debug` and misses support for "https".

Suggested Solution is shown in modified file `bbb-record.corrected` against original file `bbb-record.ori` (both attached to this comment). Tested the modified version on 2 servers, error never occurs again but script shows actual errors correctly.

[bbb-record.zip](https://github.com/bigbluebutton/bigbluebutton/files/1056176/bbb-record.zip)

**Comment by prateeksinghbundela** [comment]
Hello @ffdixon ,
I install bigbluebutton successfully,
and setup all the things its working fine in my local machine, But I have deploy the code on server and test the things its not working

Please let me know how can I resolve this issue.

I got the error like that
http://52.72.194.74:8081/bigbluebutton/api/getMeetingInfo?meetingID=a6c600dbd7af05bf80d2863f52b5587a170a06a0&checksum=23606ca9fe78886e51c7b378618aece521d0acf4
App 28670 stdout: BigBlueButtonAPI: URL response = <response><returncode>FAILED</returncode><messageKey>notFound</messageKey><message>We could not find a meeting with that meeting ID</message></response>

**Comment by ffdixon** [comment]
Hi Prateek, please don't post unrelated comments on existing issues.  For setup/configuration questions, post to bigbluebutton-setup

  https://groups.google.com/forum/#!forum/bigbluebutton-setup

and we'll help you there.  If we find a bug in BigBlueButton in helping your resolve your question, we'll open a new issue here.
