### ISSUE TITLE
HTML5 - The User list dropdown should automatically close

### ISSUE THREAD

**Issue by Klauswk** [bigbluebutton/bigbluebutton#4003]
The userlist dropdown no longer autoclose when you choose an action neither when you click outside of the dropdown

![screenshot from 2017-06-07 16-27-34](https://user-images.githubusercontent.com/17770979/26897255-4a39859c-4b9e-11e7-9e74-aa3464e6de36.png)

**Comment by jfsiebel** [comment]
Couldn't reproduce the bug in dev2.bigbluebutton.org, maybe someone already fixed this issue.
