### ISSUE TITLE
HTML5 - The meeting on HTML5-client is not closed when the meeting is ended through API mate

### ISSUE THREAD

**Issue by JaeeunCho** [bigbluebutton/bigbluebutton#4006]
1. join meeting through flash client and html5 client
2. click end link on API mate
3. flash-client is closed successfully.
4. HTML5-client is not closed and display error at console.

![20](https://user-images.githubusercontent.com/19368114/26947986-c408bb30-4c62-11e7-98b2-93d49056c4c4.jpg)

**Comment by antobinary** [comment]
fixed in #4054
