### ISSUE TITLE
bbb-html5 lacks nodejs dependency

### ISSUE THREAD

**Issue by yurikoles** [bigbluebutton/bigbluebutton#4011]
`bbb-html5` requires `npm` and `nodejs` but they are note specified in dependencies.
Even more, it relies on old binary `node`, but `nodejs` package doesn't provide it, creating a symlink solves this issue.
```
cd /usr/bin
ln -s nodejs node
```

**Comment by ffdixon** [comment]
The packaged versions of nodejs is not recent enough, which is why the instructions have the user install it directly.  See

   http://docs.bigbluebutton.org/html/html5-overview.html#installation

**Comment by yurikoles** [comment]
Its not a good reason to not put a `nodejs` dependency explicitly. Why don't you put `nodejs >=4` in deps?

**Comment by ffdixon** [comment]
That's a good idea ... we'll look at doing this for BigBlueButton 2.0.

**Comment by yurikoles** [comment]
Do you have a Debian control file somewhere in Git? I'm willing to contribute :)

**Comment by ffdixon** [comment]
Thanks for the offer.  It's pretty easy for us go do :-).

**Comment by mikhailnov** [comment]
yes, please put debian specs to git

**Comment by mikhailnov** [comment]
Maybe add adding repositories for mongodb & nodejs as a preinstall script, and make nodejs >= NN Pre-Depend ency of bbb-html5 to force apt install nodejs before processing bbb-html5 post-install scripts?

**Comment by antobinary** [comment]
The documentation (for install and dev install) of the HTML5 client now recommends using `nodejs` v.6.x and above. The `bbb-html5` package contains a dependency to `nodejs` > 6.x (this will become available next time packages are pushed to the BBB 2.0 public repo)
