### ISSUE TITLE
Exams and finals enviorment needed

### ISSUE THREAD

**Issue by mjencabh** [bigbluebutton/bigbluebutton#4014]
Hello developers! awesome work- we love it!
I could relly need an enviorment for exams where the students join in welcome-room and the moderator/teacher stays in a exams-room with the posebility to pull the right student and censor inside and back for voting! That would really be top state of art :) hop someone catches the ball.

Sorry if Im posting the wrong place....

/Admin and teacher - Michael

**Comment by ffdixon** [comment]
Hi Michael,

Thanks for the suggestion.  

Are you look to make sure the correct student is doing the exam (i.e. proctoring) or are you looking to make sure the student is actively working on the exam (i.e. hasn't left the keyboard for 30 minutes)?

Would you see the exam rooms as mini-breakout rooms with some way for the instructor to monitor all the students in the breakout rooms?

Interested in getting a bit more detail.

**Comment by mjencabh** [comment]
Hello ffdixon,

Well here in DK we are having online exams, that's why the environment for Exams would be a great function- Adobe connect has it and some uses Skype but this is a hole other world.
1. Teacher join room - we are on moodle so through the classroom. It could be like breakoutrooms.
The function should be that all joining students are send to a waitingroom/onhold where they are muted-
the when the teacher or moderator wants them to join they simply drop n drag or right-click  and send to.
Then the student should be in the Examsroom where the teacher and censor are ready for the "show".
When the exam is over and the voting process is on the student should either be able to be muted and not able to see anything while the voting is ongoing or they could be send to a votingroom- and after the voting brought back.

So basicly 3 rooms; 1 waitingroom, 1 exam room, and 1 votingroom.
In the exam room there should be 3 webcams and ofcourse big screen for showing the docs/pdf/video/web/etc...

See photo [www.webundervisning.dk/Bigbluebutton.jpg](url)

So to answer your question its and online oral exame how ever your own suggestion could be another setup for Exams.

Best regards
Michael
