### ISSUE TITLE
hard coded port

### ISSUE THREAD

**Issue by vanko69** [bigbluebutton/bigbluebutton#4026]
In file **ModulesProxy.as** in method **testRTMP()** there is 
**portTestProxy.connect(false /*"RTMP"*/, getPortTestHost(), "1935", getPortTestApplication(), getPortTestTimeout());**
I do not understand where this function is used. And it is necessary to be hard coded ?

also in file **NetConnectionDelegate.as** in method **connect()**  there is **bbbAppsUrl = "rtmp://" + result.server + ":1935/" + result.app + "/" + confParams.room;**

**Comment by ritzalam** [comment]
It is used to test if the client needs to use RTMPT (tunnelling) if it's not able to connect directly to Red5.

Please send questions like this to the dev mailing list instead of creating an issue.

Thanks.

**Comment by ffdixon** [comment]
See

   https://bigbluebutton.org/support/community/
