### ISSUE TITLE
Pass a default breakout room with join API

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#4029]
Some front-end applications, such as Moodle, have the concept of student groups.  

In the join API, extend it to add a parameter group=1, group=2, ... group=5.  This would enable the BigBlueButton client to automatically assign the students to a given breakout room.

**Comment by GhaziTriki** [comment]
@ffdixon breakout rooms can be joined using API using their unique ID, with a simple `getMeetings` call we can find which breakout rooms belongs to the main room, then we can generate a join URL.

**Comment by ffdixon** [comment]
This issue relates to auto-assigning users in the breakout dialog based on their student groups in Moodle (instead of randomly assigning the user to rooms).
