### ISSUE TITLE
1.1 getmeetings returns all info.

### ISSUE THREAD

**Issue by hostbbb** [bigbluebutton/bigbluebutton#4037]
Between 1.1RC and 1,1 final release. api version was updated to 1.1

getMeetings now returns all meeting info like passwords, participants list and meeting metadata?

Not sure if this is intended?  

If it is, the docs need to have the sample <response> updated to reflect.

**Comment by ffdixon** [comment]
We had refactored getMeetings code and it was previously returning a subset of getMeetingInfo.   

Returning the full information for getMeetingInfo didn't break anything because it only added more information.

Good catch, we'll update the docs to reflect this change.

**Comment by GhaziTriki** [comment]
Docs are up-to-date http://docs.bigbluebutton.org/dev/api.html#getmeetings

**Comment by ffdixon** [comment]
Thanks for checking this out Ghazi.  Closing.
