### ISSUE TITLE
getMeetings should fail with 503 when server is unable to connect to redis

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#4044]
Currently, on a BigBlueButton 1.1 server, if bbb-web is unable to connect to redis, all of the API calls will fail except getMeetings, which is using an old snapshot of the meeting data.

getMeetings should return a 503 error when the connection to redis fails as well.

**Comment by ritzalam** [comment]
Fixed in https://github.com/bigbluebutton/bigbluebutton/commit/fae9dfdf147305f401cb5c4d20327ab64aa44212#diff-82200b2a48477d76a613140114dbb94a
