### ISSUE TITLE
Changing the /client/BigBlueButton.html portion of the URL

### ISSUE THREAD

**Issue by prateeksinghbundela** [bigbluebutton/bigbluebutton#4053]
Hello,

I need to change my default url, Under the bigbluebutton,

Please suggest me its possible, I need url like /client/triagepmo.html  some thing like ....

**Comment by ffdixon** [comment]
This is covered in the documentation: http://docs.bigbluebutton.org/install/install.html#change-the-clientbigbluebuttonhtml-portion-of-the-url

**Comment by prateeksinghbundela** [comment]
@ffdixon 

I have facing this issues after update the client.nginx file 

Currently this file contain 

        # BigBlueButton.html is here so we can expire it every 1 minute to
        # prevent caching.
        location /client/BigBlueButton.html {
                root    /var/www/bigbluebutton;
                index  index.html index.htm;
                expires 1m;
       }

        # BigBlueButton Flash client.
        location /client {
                root    /var/www/bigbluebutton;
                index  index.html index.htm;
        }



and after changes its look like

location /client/BigBlueButton.html {
        rewrite ^ /conference permanent;
}

location /conference {
        alias  /var/www/bigbluebutton/client;
        index BigBlueButton.html;
        expires 1m;
}

and then restart nginx server and also restart  bbb-conf --restart and then run its display error Please see the screen short



![error](https://user-images.githubusercontent.com/6754191/28005261-4b2be890-6567-11e7-9f14-bb5ce2b9ceec.png)

**Comment by prateeksinghbundela** [comment]
@ffdixon 

Fixed this issue, Thanks :)

**Comment by eamon55** [comment]
Hi Fred 
I am facing the same problem as above, 
I use version 2.0 bigbluebutton 

best

**Comment by ffdixon** [comment]
See the documentation at for details

 http://docs.bigbluebutton.org/install/install.html#change-the-clientbigbluebuttonhtml-portion-of-the-url
