### ISSUE TITLE
Add a phone number to the conference bridge

### ISSUE THREAD

**Issue by prateeksinghbundela** [bigbluebutton/bigbluebutton#4079]
Hello @ffdixon,

I have follow the steps with this url
http://docs.bigbluebutton.org/install/install.html#add-a-phone-number-to-the-conference-bridge

But unable to conference Please let me know if other changes required.

**Comment by prateeksinghbundela** [comment]
@ffdixon 

Please let me know How can we add conference bridge

Thanks

**Comment by spinovation** [comment]
@ffdixon 

Do you have any idea how to update the conference-bridge on bigbluebutton.

Thanks

**Comment by ffdixon** [comment]
Hi,

Did you follow the steps outlined in the documentation?  How far did you get through the steps?

Regards,.. Fred

**Comment by spinovation** [comment]
@ffdixon 

Thanks for response

Hello,

I have integrate bigbluebutton successfully and also port chatx.live. Its working fine But I need to add phone number to conference bridge,
I have follow the process through this link http://docs.bigbluebutton.org/install/install.html#add-a-phone-number-to-the-conference-bridge
and update the change accordingly

1) Create DialPlan under this directory /opt/freeswitch/conf/dialplan/public/chatxlive.xml

<extension name="202-800-XXXX">
 <condition field="destination_number" expression="202-800-XXXX">
   <action application="answer"/>
   <action application="sleep" data="500"/>
   <action application="play_and_get_digits" data="5 5 3 7000 # conference/conf-pin.wav ivr/ivr-that_was_an_invalid_entry.wav pin \d+"/>
   <action application="transfer" data="SEND_TO_CONFERENCE XML public"/>
 </condition>
</extension>
<extension name="check_if_conference_active">
 <condition field="${conference ${pin} list}" expression="/sofia/g" />
 <condition field="destination_number" expression="^SEND_TO_CONFERENCE$">
   <action application="set" data="bbb_authorized=true"/>
   <action application="transfer" data="${pin} XML default"/>
 </condition>
</extension>


I am unable to connect Please suggest me
Please let me know any more changes required???


And Please let me know where I can placed this code under the bigbluebutton
https://freeswitch.org/confluence/pages/viewpage.action?pageId=2883800

<include>
  <gateway name="nextiva">
    
    <param name="username" value="USERNAME"/>
    <param name="password" value="PASSWWORD"/>
    <param name="register" value="true"/>
    <param name="realm" value="sbc.voipdnsservers.com"/>
    <param name="proxy" value="sbc.voipdnsservers.com"/>
    <param name="extension" value="auto_to_user"/>
  </gateway>
</include>

**Comment by ffdixon** [comment]
Old issue -- please post in https://groups.google.com/forum/#!forum/bigbluebutton-setup if you still require help.  That's a better forum as many others are subscribed to the mailing list.
