### ISSUE TITLE
When I click Join button then Issue arise

### ISSUE THREAD

**Issue by prateeksinghbundela** [bigbluebutton/bigbluebutton#4085]
Hello,
I have successfully install the setup bigbluebutton on this "http://chatx.live/", But after click on join button I am getting issues,

Please let me know how can join the meeting successfully under this url.

**Comment by ffdixon** [comment]
A few questions

1.  Did you get any errors during the installation?
2. Did you test it with the API demos?
3. What changes did you make to BigBlueButton?
