### ISSUE TITLE
 Automatic redirection after joining is the VM private network IP?

### ISSUE THREAD

**Issue by xiaocui-s** [bigbluebutton/bigbluebutton#4130]
![2017-07-24 18-57-03](https://user-images.githubusercontent.com/24190657/28520440-10914842-70a2-11e7-830a-0e392f6ad5c3.png)

**Comment by GhaziTriki** [comment]
Hello @xiaocui-s,

Di you use `sudo bbb-conf --setip` to configure your VM?
http://docs.bigbluebutton.org/install/bbb-conf.html#--setip-hostname_or_ip

**Comment by xiaocui-s** [comment]
Instead of setting the public IP access

![2017-07-24 19-02-53](https://user-images.githubusercontent.com/24190657/28520591-b9dc4d48-70a2-11e7-9e1c-ba72c3b88079.png)

**Comment by xiaocui-s** [comment]
@GhaziTriki   Resolved, the default url is replaced

![2017-07-24 19-18-31](https://user-images.githubusercontent.com/24190657/28521159-f50e3f00-70a4-11e7-9839-39b054fc9012.png)

**Comment by xiaocui-s** [comment]
@GhaziTriki   There is a problem, unable to load the document, the WhiteboardModule does not work, how to solve? Thank you!

![2017-07-24 19-25-59](https://user-images.githubusercontent.com/24190657/28521386-ff1fc15c-70a5-11e7-9681-3169997f0a1a.png)

![2017-07-24 19-26-18](https://user-images.githubusercontent.com/24190657/28521391-04fceb72-70a6-11e7-9f8c-6c46f91381eb.png)

**Comment by GhaziTriki** [comment]
@xiaocui-s did you restart your server after using `bbb-conf --setip` command?

**Comment by xiaocui-s** [comment]
@GhaziTriki  yes,Has been restarted. unable to load the document, the WhiteboardModule does not work

**Comment by xiaocui-s** [comment]
@GhaziTriki  Thank you for your answer, the problem has been resolved.
