### ISSUE TITLE
A new presenter isn't assigned when the current one leaves

### ISSUE THREAD

**Issue by capilkey** [bigbluebutton/bigbluebutton#4133]
Steps to reproduce:
1. Join a meeting from two clients
2. Have the client that is the presenter log out

Expected result:
The second client should be made presenter when the old one leaves.

Actual result:
No one is the presenter and nothing happens when you try to manually make them the presenter.

**Comment by antobinary** [comment]
In the current state we seem to have more than one presenter. I will take a look into it
