### ISSUE TITLE
getMeetingInfo: endTime invalid format

### ISSUE THREAD

**Issue by arapoport** [bigbluebutton/bigbluebutton#4135]
Hi,

getMeetingInfo returns endTime using an invalid format (with thousands separators):

    <startTime>1500933964997</startTime>
    <endTime>1,500,934,348,782</endTime>

To see it, getMeetingInfo must be called directly after everyone has left.

BBB version 1.1

**Comment by ritzalam** [comment]
Fixed in https://github.com/bigbluebutton/bigbluebutton/commit/a81f2474e0d56b427e0ed7945bbe2970f81e9a21#diff-82200b2a48477d76a613140114dbb94a
