### ISSUE TITLE
Microphone icon incorrectly highlighted

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#4159]
On the latest developer build of 2.0-dev,

1.  Join user “A”  and share microphone
2.  Join user “B”  and share microphone
3.  Refresh “B”

“A” shows “B” joining in the user list with an active microphone.

**Comment by antobinary** [comment]
same as #4229

**Comment by ritzalam** [comment]
Fixed in https://github.com/bigbluebutton/bigbluebutton/pull/4249
