### ISSUE TITLE
typo: mongod.service

### ISSUE THREAD

**Issue by mikhailnov** [bigbluebutton/bigbluebutton#4163]
`bbb-conf --restart ` tries to 
`systemctl stop/start mongod.service`
It must be mongod**b**.service

bbb-html5 is installed

**Comment by mikhailnov** [comment]
Fixed by https://github.com/bigbluebutton/bigbluebutton/pull/4161/commits/07fdb39d2db405500a4fcffcb3db075a1b2a4dec

**Comment by GhaziTriki** [comment]
@mikhailnov did the `bbb-conf --restart` fail on your machine? Because the service name `mongd` is correct. There is no such service `mongodb`. The `d` at the end of the service name is for `daemon`, so there is no missing `b`.

**Comment by mikhailnov** [comment]
@GhaziTriki Fixed it by https://github.com/bigbluebutton/bigbluebutton/pull/4161/commits/a77a2a7ac1386dea3fd54a4e870faec5ea600812
mongodb.service belongs to mongodb-server from Ubuntu 16.04 repos, mongod.service belongs to the build from the repository, recommended by v
Added a check & warning to prevent such misunderstandings

**Comment by mikhailnov** [comment]
https://github.com/bigbluebutton/bigbluebutton/pull/4161/commits/41f8b9508c4ce2bb8b300ee58dbb611eb0106430
