### ISSUE TITLE
Microphone is not unhighlighting

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#4184]
Once the Microphone icon shows highlight, it doesn't unhighlight when the user stops talking.

![image](https://user-images.githubusercontent.com/290351/28838134-c351f23c-76c5-11e7-8c8c-60ecac7cbcf5.png)

**Comment by Klauswk** [comment]
Same happens on the HTML5 client, i don't receive any message user stop talking.

**Comment by ritzalam** [comment]
Fixed in https://github.com/bigbluebutton/bigbluebutton/pull/4249
