### ISSUE TITLE
Viewers aren't locked on join

### ISSUE THREAD

**Issue by ritzalam** [bigbluebutton/bigbluebutton#4188]
Using lock settings, lock public and private chat. After locking, viewers can still chat.

**Comment by capilkey** [comment]
Users don't have their lock state set to true on join so even if you set the meeting's lock state the client won't obey it until you lock that user from the user list. Once you've clicked on the user's lock button you can then make a change to the lock state and the user's client will be affected.

There's also an additional bug where the user list doesn't show who is locked even when you click the lock button for a user which should toggle the visibility of the lock icon.

**Comment by pedrobmarin** [comment]
Maybe some of this issue was correct with this commit https://github.com/bigbluebutton/bigbluebutton/commit/bf5b73c7a51892338f7733b7b32f0c4f9ab8316d.

**Comment by capilkey** [comment]
I don't think it will affect it. I think there was another issue with accessibilityProperties being null that came up awhile ago and it only affected Linux users. These layout issues affect everyone.
