### ISSUE TITLE
Slide conversion hangs when uploading an empty file with the PDF extension

### ISSUE THREAD

**Issue by daronco** [bigbluebutton/bigbluebutton#4218]
To reproduce:

* Create a new empty file (on linux, right click on the desktop and select "New document").
* Name the file `empty.pdf`.
* Upload the file in a conference.

The file will be uploaded but the conversion process will hang and the upload window will stay open, blocking the rest of the interface. After around 5 minutes the window closes automatically.

**Comment by amazighon** [comment]
hi
you should create empty files with corresponding software (programm). it doesnt work like this, also the empty.pdf you created is not a pdf ! and you cant convert it!

regards

**Comment by ritzalam** [comment]
What tools or libraries can we used to check the validity of files? Right now, we just rely on the filename extension.

**Comment by daronco** [comment]
I think `file` can be used. Examples:

```sh
$ file -i my-real-pdf.pdf
/home/user/my-real-pdf.pdf: application/pdf; charset=binary

$ file -i ~/Desktop/empty-file.pdf
/home/user/empty-file.pdf: inode/x-empty; charset=binary

$ file -i real-image.png
/home/user/real-image.png: image/png; charset=binary

$ file -i ~/Desktop/
/home/user/Desktop/: inode/directory; charset=binary
```

Or even shorter:

```sh
$ file --mime-type -b my-image.jpeg
image/jpeg
```

**Comment by GhaziTriki** [comment]
Confirmed still an issue in 2.3
