### ISSUE TITLE
Audio users appear as talking:true even if they are not talking

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#4226]
Unable to reproduce on a local machine - it works properly there.

To reproduce: Join with audio. Start talking, lower the microphone sensitivity.
Expected result: the talking indicator should switch to inactive
Current result: the indicator remains active

**Comment by ritzalam** [comment]
Same as https://github.com/bigbluebutton/bigbluebutton/issues/4184
