### ISSUE TITLE
Thumbnail conversion are slow

### ISSUE THREAD

**Issue by pedRo-shd** [bigbluebutton/bigbluebutton#4241]
I try to upload in a conference, but the conversion of the thumbnails is slow. I'd like to know what could be wrong.

**Comment by ffdixon** [comment]
Hi there,

You've posted to both an issue and our forum.  

   https://groups.google.com/d/msg/bigbluebutton-dev/I3tazVfM5Js/MLEtdpuhAAAJ

We'll continue the thread in the above discussion and, if there is a bug in BigBlueButton, we'll reopen the issue here.
