### ISSUE TITLE
User unable to rejoin a breakout room 

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#4256]
If a user joins a breakout room and then closes the tab, they should be able to re-join using the 'Join' button in the Breakout Rooms table (see below).

![image](https://user-images.githubusercontent.com/290351/29419279-b37055d8-833c-11e7-9ea3-e74b9b855297.png)

**Comment by ritzalam** [comment]
Fixed in https://github.com/bigbluebutton/bigbluebutton/commit/a7028f53d56338798cd52ae811c671d7bc5fac63
