### ISSUE TITLE
Flash client - reconnection handling (edge cases)

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#4263]
Join with flash client "User A". Join audio and share webcam.
Join with flash client "User B".
Force reconnection on user B and while reconnecting, stop sharing audio and webcam on user A. Allow user B to reconnect.
At this point user B should display that user A is not in audio and not sharing webcam.
issue: Currently user B shows user A still in audio and sharing webcam.

Note: this seems to be a discrepancy between model and view on Flash client

**Comment by ffdixon** [comment]
Closing as this was an issue related to the Flash client (the project has moved to an HTML5 client).
