### ISSUE TITLE
Close out text fields when multi-user whiteboard is turned off

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#4274]
In BigBlueButton 2.0-dev, a viewer could have a text field open and the presenter could turn off multi-user whiteboard; however, the user's text field is still active.

End all whiteboard operations from users when the presenter turns off multi-user whiteboard.

**Comment by capilkey** [comment]
Fixed in this PR, https://github.com/bigbluebutton/bigbluebutton/pull/4304.
