### ISSUE TITLE
Unable to proceed the installation--Help!!!--

### ISSUE THREAD

**Issue by spinware** [bigbluebutton/bigbluebutton#4289]
Hi, someone to help me for this, I am unable to proceed the installation which stops at the 97% for finishing.  This is what I got from the error.

http://ubuntu.bigbluebutton.org/xenial-110 (Connection failed)

![deb sourcelist](https://user-images.githubusercontent.com/17583873/29544681-64bf1f3a-871c-11e7-92a9-9201b42bbae9.JPG)
![deb_update](https://user-images.githubusercontent.com/17583873/29544682-64eeff70-871c-11e7-8f1a-f401f2cfe52c.JPG)
![error](https://user-images.githubusercontent.com/17583873/29544683-6500c1a6-871c-11e7-8a89-312cbc6e54e7.JPG)

**Comment by ffdixon** [comment]
Hi there,

Can you post this to our mailing list at bigbluebutton-setup, see https://bigbluebutton.org/support.

If we find a problem with the packages/instructions, we'll open an issue here to resolve it.

When you post, don't post images but copy-and-paste the text. It makes it much easier to read, and the search engines can index it so it's available for other using Google to search for similar errors.
