### ISSUE TITLE
Chrome only allows webcam and microphone access with HTTPS

### ISSUE THREAD

**Issue by capilkey** [bigbluebutton/bigbluebutton#4319]
Chrome no longer allows webcam access from HTTP domains and this rejection appears as "Your camera might be in use by another application" in the webcam window. We should add detection for HTTP and Chrome and put in a more relevant error message.

**Comment by capilkey** [comment]
This also affects microphone access.

**Comment by capilkey** [comment]
The webcam side of this is now fixed. When you try share your webcam in Chrome from an HTTP server there is now a warning message shown that explains the issue.

There's still an issue with the microphone however. Currently the client falls back to Flash audio as if WebRTC isn't available, but while Flash audio will connect your mic will not transmit anything. There needs to be a warning about microphone access over HTTP similar to the webcam warning.

**Comment by GhaziTriki** [comment]
The warning is in place for 2.0.
