### ISSUE TITLE
Lock settings should apply to shortcut keys

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#4329]
Reported in https://groups.google.com/d/msg/bigbluebutton-dev/-EWiJMNnv-M/DaLGSk_YAAAJ, which Daniel wrote.

> So, I have found a bug. I have set our BBB server lock on join and turned all the "lock" options in the config.xml file to "true". This has been working great, all the users are locked on join and need a moderator to open the class. Unfortunately, the global menu shortcut for the webcam seems to bypass this setting. Even if your room is locked, if you press (Ctrl+shift+b) then you can open the webcam sharing options and share your webcam even while you are supposed to be locked out.

The lock settings should apply to shortcut keys.

**Comment by ffdixon** [comment]
Fixed.

**Comment by lifeofdan** [comment]
This was my issue you fixed. Thank-you! Just in time for the new school year as long as I run the beta client! Very grateful for the work the team is doing.
