### ISSUE TITLE
Shared Note length limit is not applied when a user holds down a key (key repeat) on Chrome Linux

### ISSUE THREAD

**Issue by kepstin** [bigbluebutton/bigbluebutton#4332]
We were able to reproduce this fairly easily -
Fill a shared note until it only has a few characters left (limit indicator has a small positive number)
Have a user on Chrome Linux (TODO: check if this happens in Windows too) press and hold down a key - the note will continue to grow longer, and the character limit indicator will become more and more negative.

**Comment by ffdixon** [comment]
Closing as this was an issue related to the Flash client (the project has moved to an HTML5 client).

We'll open a new issue if this problem arises in the latest version.
