### ISSUE TITLE
Make the "who is typing" area in shared notes a set width

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#4336]
Currently, in BigBlueButton 2.0-beta, when the "who is typing" appears it can trigger a horizontal scroll bar

![typing](https://user-images.githubusercontent.com/290351/29891129-0437aefc-8d98-11e7-8882-08dc3dbe94ff.PNG)

Make the "who is typing" filed area a fixed width (truncate the text if needed) to prevent showing the horizontal scroll bar.

**Comment by pedrobmarin** [comment]
If the idea is just to avoid the horizontal scroll bar the changes I did in #4352 should fix this
