### ISSUE TITLE
The document conversion error needs to be wrapped

### ISSUE THREAD

**Issue by perroned** [bigbluebutton/bigbluebutton#4338]
to reproduce

- select a document that won't convert (wrong extension, corrupt, change the type of files that the dialog is looking for)

- hit upload

In English its placed on top of the progress string and goes outside the window.

![incompatible file](https://user-images.githubusercontent.com/6475374/29893592-8e84ce02-8da0-11e7-921a-5cde89ec898a.png)

In something like German its much harder to read because of the text behind

![german](https://user-images.githubusercontent.com/6475374/29893601-92745582-8da0-11e7-84ae-c3b2e524c023.png)

**Comment by ffdixon** [comment]
Closing as this was an issue related to the Flash client (the project has moved to an HTML5 client).
