### ISSUE TITLE
Can not upload a presentation in Full Sceen mode 

### ISSUE THREAD

**Issue by akiwenziec** [bigbluebutton/bigbluebutton#4340]
Easily reproducible: (Testing on build 698) 
- When in full screen mode on Chrome (60.0.311 64bit) and Firefox (55.0.2 - 32bit) select presentation upload button.
- Presentation upload window will appear 
- Choose "select file", no file explorer loads to select a file
- Does not affect Firefox 64bit

**Comment by perroned** [comment]
I just noticed the exact same thing happens with the dialog box to download shared notes and download the public chat. So it seems like its all the browser dialogs that don't pop up. I would think its all the same problem and fixing it would probably fix all of them

**Comment by capilkey** [comment]
It could be a security restriction on the file select when in full screen.

**Comment by perroned** [comment]
also the help button doesn't open a new tab when you're in full screen

**Comment by antobinary** [comment]
Is this still occurring after the merge of #4344 ? I don't seem to be able to reproduce it.

**Comment by akiwenziec** [comment]
I can no longer reproduce on Win or Mac OS in either browser (32 or 64 bit ff)

**Comment by perroned** [comment]
Dialog box to download shared notes, download public chat, and help button are all working now for me. Chrome 58-64bit ubuntu 16.04

**Comment by antobinary** [comment]
Marking as resolved in #4344
