### ISSUE TITLE
FireFox on Linux - Opening a dialog leads to Flash crashing

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#4347]
Log in the Flash client via FireFox. Try any of the following scenarios involving popping up the file explorer:
-Under Chat 'Options' click on Save public chat -> Flash has crashed
-As presenter try uploading presentation -> Flash has crashed

Reproducible on the following versions of FireFox on Ubuntu 16.04
55.0.2 (64-bit)
57.0a1 (2017-08-30) (64-bit)

Note - audio join modal or download presentation do not trigger a crash
Also note that this happens regardless of full screen mode on or off

**Comment by ttjaden** [comment]
I can confirm this issue!
Linux Mint 18.1 with Firefox 55.0.2 (64-Bit). With Chrome there is no issue!

**Comment by ffdixon** [comment]
Closing as this was an issue related to the Flash client (the project has moved to an HTML5 client).
