### ISSUE TITLE
Shared note text format with wrong icon

### ISSUE THREAD

**Issue by pedrobmarin** [bigbluebutton/bigbluebutton#4353]
I believe "justify" and "center" were swapped in the compilation of v2_skin.swf
![screenshot from 2017-08-31 16-59-03](https://user-images.githubusercontent.com/1778398/29942992-237f072a-8e6e-11e7-819c-542b803b5ef5.png)

**Comment by ffdixon** [comment]
Fixed in latest build of 2.0.

![image](https://user-images.githubusercontent.com/290351/30339753-0bc34e6c-97be-11e7-816c-b5aa41104dca.png)
