### ISSUE TITLE
[html5] install & run error

### ISSUE THREAD

**Issue by notedit** [bigbluebutton/bigbluebutton#4360]
this is how i install and run.

1,  clone the bigbluebutton code
2,  meteor npm install
3, NODE_ENV=production npm start
4, config  nginx

then  http://<your_ip>/html5client/check  is show  bigbluebutton is runing.

when i visite  http://127.0.0.1/html5client

i got this error in backend 

`
=> App running at: http://127.0.0.1/html5client
I20170905-11:26:58.809(8)? Exception from sub current-user2x id F7giSrBhhunyMYWJw Error: Match error: Expected string, got null
I20170905-11:26:58.818(8)?     at exports.check (packages/check.js:56:15)
I20170905-11:26:58.820(8)?     at [object Object]._handler (imports/api/2.0/users/server/publishers.js:12:3)
I20170905-11:26:58.822(8)?     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1768:12)
I20170905-11:26:58.825(8)?     at packages/ddp-server/livedata_server.js:1043:15
I20170905-11:26:58.829(8)?     at [object Object]._.extend.withValue (packages/meteor.js:1126:17)
I20170905-11:26:58.830(8)?     at [object Object]._.extend._runHandler (packages/ddp-server/livedata_server.js:1041:51)
I20170905-11:26:58.835(8)?     at [object Object]._.extend._startSubscription (packages/ddp-server/livedata_server.js:859:9)
I20170905-11:26:58.836(8)?     at [object Object]._.extend.protocol_handlers.sub (packages/ddp-server/livedata_server.js:625:12)
I20170905-11:26:58.836(8)?     at packages/ddp-server/livedata_server.js:559:43
I20170905-11:26:58.847(8)? Sanitized and reported to the client as: Match failed [400]
I20170905-11:26:58.848(8)? 
`

do i miss something?    thanks

**Comment by perroned** [comment]
It's failing because you don't have authorization to access that page. You have to join/create a meeting first from a front end using the API demos for example  and then you'll get directed to that page. 

This should be asked on the bigbluebutton google groups as it's not a problem with bigbluebutton itself.

**Comment by notedit** [comment]
@perroned   sorry for this,  i ask in google groups, but no one  reply me.  so  i can not just run  bbb-html5 alone?  i just want to test the whiteboard module.

**Comment by perroned** [comment]
The html5 client is not stand alone so you'll need a server with bigbluebutton set up first. You can very easily set up a bbb server from packages and then install the html5 client from packages as well. http://docs.bigbluebutton.org/install/install.html

If you want to play around and take a look there's always demo.bigbluebutton.org

**Comment by notedit** [comment]
thanks
