### ISSUE TITLE
Record button being blue colour is confusing.

### ISSUE THREAD

**Issue by kepstin** [bigbluebutton/bigbluebutton#4366]
Based on user feedback:

People often weren't sure whether recording was activated or not, because the button is highlighted in blue when recording is active - recording active is traditionally marked with a red colour.

We should also consider making the center circle of the record button red on the unactivated icon to make it easier to identify the button's purpose.

**Comment by ffdixon** [comment]
Updated in latest build to now be red

![image](https://user-images.githubusercontent.com/290351/30339735-f63c5836-97bd-11e7-941d-221f322d1041.png)
