### ISSUE TITLE
Edit layout of tab options for old displays.

### ISSUE THREAD

**Issue by marshel** [bigbluebutton/bigbluebutton#4388]
The 2.0-beta layout on the meeting is set to a widescreen display. Part of the Options Tab on Chat area are cut on 1280x1024 layout panel as seen on image.

![2017-09-13 09_15_28-bigbluebutton - demow](https://user-images.githubusercontent.com/1764993/30376894-5055dc7e-9864-11e7-83a3-b625f186447a.png)

I Suggest this tab to be responsible (if possible) and to ident the "Chat options" title and content with a bold font or bigger font size.

**Comment by ffdixon** [comment]
Closing as this was an issue related to the Flash client (the project has moved to an HTML5 client).
