### ISSUE TITLE
Make sure message is valid when sending a chat message

### ISSUE THREAD

**Issue by ritzalam** [bigbluebutton/bigbluebutton#4393]
When sending a chat message from the client, we try to sanitize the message. However, we don't check if this succeeds or not.

```
cm.message = ExternalInterface.call('parseURLs', (ChatUtil.cleanup(message)));

```

Check if the "parseURLs" returns NULL. If it does, do not send the message.

**Comment by capilkey** [comment]
Should probably check for null or empty.

**Comment by ritzalam** [comment]
Closing as fix has been merged.
