### ISSUE TITLE
When logging with moodle ver3.3:bigbluebutton2.0

### ISSUE THREAD

**Issue by syusanjun** [bigbluebutton/bigbluebutton#4397]
When logging with moodle ver3.3, the url of the recording file becomes as follows and the page is not displayed.

https://aaa.bbb.com/mod/recordingsbn/_%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20% 20% 20% 20% 20% 20% 20% 20https: /aaa.bbb.com/playback/presentation/2.0/playback.html? MeetingId = 7bf613a51998 db6e4df47723fb9719964e2ac476-1505341817722_% 20% 20% 20% 20% 20% 20% 20% 20 % 20% 20% 20% 20% 20% 20% 20% 20% 20% 20% 20% 20% 20% 20

The page was displayed manually as follows.

https: /aaa.bbb.com/playback/presentation/2.0/playback.html? meetingId = 7bf613a51998db6e4df47723fb9719964e2ac476-1505341817722

**Comment by ffdixon** [comment]
Tested this with Moodle 3.5 and the latest BigBlueButtonBN 2.2.4 plugin and the recording URLS are now working.

Marking this as fixed.  If you test and find it's still an issue, let us know!
