### ISSUE TITLE
ERROR_GETTING_INFO_USING_TOKEN

### ISSUE THREAD

**Issue by satheeshcsedct** [bigbluebutton/bigbluebutton#4398]
Hi Fred,

In Bigbluebutton1.1 screen sharing works fine at the first attempt, When I stop and start the screen sharing again without refreshing the meeting I am getting an error 'ERROR_GETTING_INFO_USING_TOKEN'.

I verified the token, Every time when I initiate screen sharing the token and the session id is passed to the JnlpFileHandler but still I am getting this error because streamId and session id is unknown in the jnlp file. I am not sure how bigbluebutton-client directory connected to bbb-screenshare/app/src/main/java/jnlp/sample/servlet/JnlpFileHandler.java As I understand this is the one which generate the jnlp file.

**Comment by ffdixon** [comment]
Hi @satheeshcsedct, can you test this again on 

  https://demo.bigbluebutton.org/

and let us know if you still get the same error.

**Comment by ffdixon** [comment]
Closing as this was an issue related to the Flash client (the project has moved to an HTML5 client).
