### ISSUE TITLE
MainToolbar doesn't use the config.xml help URL

### ISSUE THREAD

**Issue by capilkey** [bigbluebutton/bigbluebutton#4409]
In 2.0 the way config options are fetched was changed. The old way of fetching the help URL was removed from MainToolbar, but the new way wasn't added in so it always loads the default URL. 

The pre-2.0 way of fetching the help URL can be found here, https://github.com/bigbluebutton/bigbluebutton/blob/v1.1.x-release/bigbluebutton-client/src/org/bigbluebutton/main/views/MainToolbar.mxml#L320.

A working instance of the config help URL fetching can be found here, https://github.com/bigbluebutton/bigbluebutton/blob/bbb-2x-mconf/bigbluebutton-client/src/org/bigbluebutton/main/views/WebRTCEchoTest.mxml#L244-L248.

The way that the help URL is fetched in all three cases (FlashMicSettings, MainToolbar, and WebRTCEchoTest) should really be changed. If the help URL can't be found in config.xml the default would never be used anyways and it would instead load an empty string. You can find the default value for the URL here, https://github.com/bigbluebutton/bigbluebutton/blob/bbb-2x-mconf/bigbluebutton-client/src/org/bigbluebutton/main/model/options/HelpOptions.as#L25. The variables DEFAULT_HELP_URL should be removed from all three classes and the default should be added to the HelpOptions class.

**Comment by extracool727** [comment]
i approve

**Comment by capilkey** [comment]
Fixed in #4477.
