### ISSUE TITLE
2.0 beta file upload fails, chrome,surface pro

### ISSUE THREAD

**Issue by hostbbb** [bigbluebutton/bigbluebutton#4411]
Version 60.0.3112.113 (Official Build) (64-bit)
Surface Pro Windows 10

Fails on demo.bigbleubutton.org and 1.1 servers as well.

You can select file to upload,  but clicking on upload hangs dialog.

This has been intermittent since april..  worked for a while, then stopped.

Not sure how to debug flash in chrome.

Works fine on firefox.

**Comment by ffdixon** [comment]
Can you do a quick test on the latest build of the HTML5 client (https://test.bigbluebutton.org/) and let us know if its still an issue.
