### ISSUE TITLE
Some text displayed in large fonts

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#4424]
On FireFox the some of the text is displayed very large (incorrect font scaling) causing the controls on the right to be pushed off.

![image](https://user-images.githubusercontent.com/290351/30773659-c66f1bce-a042-11e7-8dbd-bb9dbc66ce00.png)

Reported in https://groups.google.com/d/msg/bigbluebutton-setup/Tb6B53Cm2js/pN8t1CVKBQAJ.

**Comment by ffdixon** [comment]
Tested again on the latest build

![image](https://user-images.githubusercontent.com/290351/31075748-114a4958-a745-11e7-99a1-7dc5bf314161.png)

**Comment by GhaziTriki** [comment]
I has been fixed in the pull request #4430

We have the following result, the screenshot is from the official demo server:

![image](https://user-images.githubusercontent.com/4991088/35039546-7853185e-fb7e-11e7-93e9-dda659fb055f.png)

**Comment by ffdixon** [comment]
Looks good -- closing this issue3.
