### ISSUE TITLE
[HTML5] Switching CC language triggers a change on the application language.

### ISSUE THREAD

**Issue by oswaldoacauan** [bigbluebutton/bigbluebutton#4459]
*STEPS TO REPRODUCE*
- Take ownership of an CC language
- Write something
- Go to HTML5 user settings
- Select the CC language
- Go to the application tab and the application language will be changed

**Comment by OZhurbenko** [comment]
[Fixed](https://github.com/bigbluebutton/bigbluebutton/pull/4496#issuecomment-335813887)
