### ISSUE TITLE
Issue with updating Client 

### ISSUE THREAD

**Issue by patriclougheed** [bigbluebutton/bigbluebutton#4472]
After upgrading to BBB v2 everytime there is a new update to the client I get this error:

Setting up bbb-client (1:2.0.0-179) ...
sed: -e expression #1, char 58: unterminated `s' command
dpkg: error processing package bbb-client (--configure):
 subprocess installed post-installation script returned error exit status 1
dpkg: dependency problems prevent configuration of bbb-config:
 bbb-config depends on bbb-client; however:
  Package bbb-client is not configured yet.

Everything works great but I have to manually change the IP to the domain in the client config. I don't think the client is updated and resets the IP in the config every time I run a system update with apt-get.

**Comment by ffdixon** [comment]
Have you commented out lines in sip.nginx or config.xml -- the package scripts are extracting data from config.xml using sed commands

~~~
cat /tmp/config.xml | sed -n '/porttest /{s/.*host="//;s/".*//;p}'
~~~

and

~~~
cat /tmp/sip.nginx | sed -n '/proxy_pass/{s/.*\/\///;s/:.*//;p}'
~~~

where `/tmp/config.xml` and `/tmp/sip.nginx` are copied from their source files in `/var/www/bigbluebutton/client/conf/config.xml` and `/etc/bigbluebutton/nginx/sip.nginx` respectively. 

These sed commands expect to find one match, but sometimes if the administrator has copied and commented out matching lines, the sed command finds multiple matches and it causes the error you reported.

**Comment by s-at-dq** [comment]
I have the same problem and I found out that there is a section in config.xml which must have been commented out by some installation script automatically. The commented out section in config.xml is the following:

    <module name="NotesModule" url="http://server-domain.tld/client/NotesModule.swf?v=947"
      saveURL="http://server-domain.tld"
      position="top-left"
    />
    
    <module name="BroadcastModule" url="http://server-domain.tld/client/BroadcastModule.swf?v=947"
      uri="rtmp://server-domain.tld/bigbluebutton"
      streamsUri="http://server-domain.tld/streams.xml"
      position="top-left"
      showStreams="true"
      autoPlay="false"
      dependsOn="UsersModule"
    />

**Comment by capilkey** [comment]
Those modules are always commented out and aren't a problem. 

This is a old and pretty generic issue, but what Fred was talking about is when someone comments out the default value and then duplicates the line to make their changes. It happens a lot with the nginx files where people will comment out a location block and then add in their own. 

To find the specific sed command that is giving you issues you can edit/var/lib/dpkg/info/bbb-client.postinst  and change the first line from `#!/bin/bash -e` to `#!/bin/bash -ex`. Save the file and then run `sudo apt-get install -f` to restart the package install. The added "x" will make the post install script run in verbose mode and it will let you see where the script is stopping.

If you post the final line of the script and a few lines around it we should be able to narrow it down.

**Comment by s-at-dq** [comment]
I get the following output:

    + sed -i 's/proxy_pass .*/proxy_pass http:\/\/(local-ip):5066;/g' /etc/bigbluebutton/nginx/sip.nginx
    + sed -i 's/\r//g' /var/www/bigbluebutton/client/conf/config.xml
    + '[' -f /etc/nginx/sites-available/bigbluebutton ']'
    + '[' -f /tmp/nginx-bigbluebutton ']'
    ++ cat /tmp/nginx-bigbluebutton
    ++ grep -v '#'
    ++ sed -n '/server_name/{s/.*name[ ]*//;s/;//;p}'
    + IP='subdomain.domain.tld
    subdomain.domain.tld'
    + sed -i 's/server_name  .*/server_name  subdomain.domain.tld
    subdomain.domain.tld;/g' /etc/nginx/sites-available/bigbluebutton
    sed: -e expression #1, char 57: unterminated `s' command

In the output I replaced the IP address with (local-ip) and the servers real domain with subdomain.domain.tld.

**Comment by s-at-dq** [comment]
The problem lies in line 383 of the postinst-script. It retrieves all server_name lines of /etc/nginx/sites-available/bigbluebutton and thereby can store multiple lines with the server domain / IP in the shell variable $IP.

In my case, I enforced HTTPS by adding a "server" directive in /etc/nginx/sites-available/bigbluebutton for HTTP which redirects all traffic to HTTPS (the server created by the BigBlueButton configuration).


I modified the postinst-script in line 383 so that it takes only the last server_name line by adding "tail -n 1":

    IP=$(cat /tmp/nginx-bigbluebutton | grep -v '#' | sed -n '/server_name/{s/.*name[ ]*//;s/;//;p}' | tail -n 1)

After that I was able to run apt-get install -f without any problem.

**Comment by capilkey** [comment]
I think you should be able to move your second server block to a new file in /etc/nginx/sites-enabled/ with some name like "redirect" and you wouldn't have to change any package files. You could also add the file to sites-available, but you'd also need to do a symbolic link to sites-enabled.

**Comment by ffdixon** [comment]
Closing as this was an issue related to the Flash client (the project has moved to an HTML5 client).
