### ISSUE TITLE
[flash] list of users, resize and scroll vertical  stay hidden.

### ISSUE THREAD

**Issue by Tainan404** [bigbluebutton/bigbluebutton#4473]
*steps for simulation*
at screens of 1366x768  or lesser is only add six users.
at others resolution is add sex users and resize list to lesser

**Comment by ffdixon** [comment]
Can you add a screen shot of what your issue so we can better understand.

**Comment by Tainan404** [comment]
![captura de tela de 2017-10-09 18-18-27](https://user-images.githubusercontent.com/15806883/31359042-88842bd6-ad1e-11e7-9ea9-ce7baf59939c.png)
![captura de tela de 2017-10-09 18-22-17](https://user-images.githubusercontent.com/15806883/31359083-d1567b52-ad1e-11e7-9a24-852f82b36abc.png)

**Comment by GhaziTriki** [comment]
@Tainan404 It should be fixed. Can you confirm it from your side?

**Comment by ffdixon** [comment]
@Tainan404 Can you test this on https://demo.bigbluebutton.org/  (it's running the build with the fix).

**Comment by Tainan404** [comment]
solved in pull request 4509
