### ISSUE TITLE
v2 Beta Issues: No 'start/stop record' button

### ISSUE THREAD

**Issue by zenny** [bigbluebutton/bigbluebutton#4484]
Hi,

BBBv2 looks fabulous and very intuitive. Kudos to the entire BBB team.

I just upgraded from bbb v1.1 to v2 as described at http://docs.bigbluebutton.org/2.0/20install.html and it went smoothly well. However, there are a few issues:

1. The client application tend to freeze on time in Chromium (latest version).
2. The client application tend to get garbled in Firefox (latest version)
3. Most importantly, the 'start/stop record' button is nowhere seen ahead of 'Shortcut Keys' as seen in this demo: http://www.youtube.com/watch?v=NQPrdc-W-6A

I guess the slow loading problem maybe due to the debug features in the beta version and the garbled UI output could be css incompatibility issue.

**It would be nice to know how to get the 'start/stop record' button visible for moderators?**

Cheers,
zenny

**Comment by capilkey** [comment]
Could you post a screenshot for #2 please. I want to see if it's one of the known issues with Firefox or not.

For #3 the start/stop button will only show up if recording for the meeting was allowed on the meeting's create call. It should be the same as in 1.1.

**Comment by zenny** [comment]
@capilkey Please find the screenshot for #2 at http://picpaste.com/RzBsYUWv.png

**Comment by capilkey** [comment]
I've never see anything like that before. Could you try clearing your cache and loading the client again. Also try https://demo.bigbluebutton.org and see if you get the same issue. It's almost looks like maybe the client   through an exception while loading or something.

**Comment by ffdixon** [comment]
Closing this issue as the Start/Stop record buttons are working on recent builds of BigBlueButton 2.0-beta. 

@zenny you can try it out on https://demo.bigbluebutton.org/  (sign in with your Google Account) and create a meeting.  It will have the Start/Stop Record button visible.

![image](https://user-images.githubusercontent.com/290351/33915815-62ca302a-df73-11e7-963d-648ecfd45d10.png)

Don't hesitate to post a follow-up if it's still not working for you.

Regards,... Fred
