### ISSUE TITLE
Add contributor names to Shared Notes like in Multi-user drawing.

### ISSUE THREAD

**Issue by zenny** [bigbluebutton/bigbluebutton#4486]
The shared notes is a very nice feature. But won't it be nice to have the username of the one who appends. This is already done in multi-user drawing.

**Comment by wrix** [comment]
Any update on this feature? Many people would love to see this implemented, including myself.

**Comment by pedrobmarin** [comment]
You can add all the plugins you want at etherpad (https://static.etherpad.org). There is probably one or two of them that enables you to identify who's typing.

**Comment by pedrobmarin** [comment]
[ep_cursortrace](https://www.npmjs.com/package/ep_cursortrace) included in v2.3

**Comment by wmchris** [comment]
is it possible to deactivate this feature in 2.3 (preferably "per room") directly?
