### ISSUE TITLE
[HTML5] Focus on a user in User list - animation problem

### ISSUE THREAD

**Issue by jfsiebel** [bigbluebutton/bigbluebutton#4491]
The first time you click on a user the focus animation occurs too fast and get interrupted.
![issue_focus_01_60fps](https://user-images.githubusercontent.com/2110278/31402146-818825c8-adcb-11e7-9df0-5ebf1b0fa405.gif)

**Comment by jfsiebel** [comment]
Also occures in Settings menu
![issue_focus_02_60fps](https://user-images.githubusercontent.com/2110278/31402308-ffa85068-adcb-11e7-9989-51c848c1c002.gif)

**Comment by OZhurbenko** [comment]
Could you explain what wrong is here exactly, please? The border appears on focus, doesn't it?

What would be your expected behavior?

**Comment by MaximKhlobystov** [comment]
I think the border caused by the focus (circle border around the dropdown button; for the userlist button it is a left-side border) is blinking (it appears and then it's interrupted). That is what's described here, as far as I understand.

**Comment by jfsiebel** [comment]
On a selected state the border must always appear?
![image](https://user-images.githubusercontent.com/2110278/31402906-d48cfbd4-adcd-11e7-8760-2c50ef1e7a69.png)
This occurs only when you click a second time, in both cases

**Comment by OZhurbenko** [comment]
> On a selected state the border must always appear?
But it's not selected, once you click it - the focus is moved to the first line of the drop down - "Make fullscreen"

**Comment by perroned** [comment]
@OZhurbenko Yeah that's how I see it. You can see the first menu item has focus. And when you click it a second time like @jfsiebel says you get focus, because since the menu closes your focus is on the button once again

**Comment by ffdixon** [comment]
Is this still an issue in 2.2-beta?
