### ISSUE TITLE
[HTML5] Align problem in chat

### ISSUE THREAD

**Issue by jfsiebel** [bigbluebutton/bigbluebutton#4493]
Send button could be vertical aligned with text input.
![image](https://user-images.githubusercontent.com/2110278/31402710-2f7fee3a-adcd-11e7-98ac-ab6658311849.png)

**Comment by jfsiebel** [comment]
Fixed in #4662, waiting merge to close this issue.

**Comment by antobinary** [comment]
Should be fixed as part of #4662 . To be retested
