### ISSUE TITLE
Add snap package

### ISSUE THREAD

**Issue by baimafeima** [bigbluebutton/bigbluebutton#4528]
Could you add a snap package for easy cross-platform deployment?

**Comment by baimafeima** [comment]
@bigblugbutton Any updates on this? See: https://snapcraft.io/

**Comment by ffdixon** [comment]
Not yet.  We're still recommending you use Ubuntu 16.04 64-bit for running BigBlueButton. 

We now provide a Docker image for letting anyone run a test version of BigBlueButton inside a docker environment.  See http://docs.bigbluebutton.org/labs/docker.html.
