### ISSUE TITLE
Add changelog

### ISSUE THREAD

**Issue by baimafeima** [bigbluebutton/bigbluebutton#4529]
Could you make the changelog directly visible in your GitHub releases? This would increase transparency for potential users and distribution maintainers. Something like https://skywinder.github.io/github-changelog-generator/ could be used to generate the changelog based on merged PRs and closed issues since the last release tag.

**Comment by GhaziTriki** [comment]
Since the release of `BigBlueButton 2.0-RC2` change logs are well provided with each release. Starting from this release https://github.com/bigbluebutton/bigbluebutton/releases?after=v2.0-rc3
