### ISSUE TITLE
[HTML5] Khmer language not changing on Demo site

### ISSUE THREAD

**Issue by sokunthearithmakara** [bigbluebutton/bigbluebutton#4532]
I noticed that Khmer language is added to list of supported languages on the demo HTML5 site, but when I switched the language to Khmer, the interface language is still in English. I tried Japanese and it worked just fine.

**Comment by OZhurbenko** [comment]
Hmm.. this locale is fully translated.
This is definitely an issue.

**Comment by OZhurbenko** [comment]
Fixed in #4538
