### ISSUE TITLE
Close button too narrow for Japanese

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#4554]
See

![image](https://user-images.githubusercontent.com/290351/31940504-6695b64c-b88c-11e7-82ce-3760a1eee84e.png)

Reported in

  https://groups.google.com/d/msg/bigbluebutton-dev/DIEDoRGuZfI/RkOX6n5WBgAJ

**Comment by GhaziTriki** [comment]
Improved in in #4567

**Comment by ffdixon** [comment]
Looks like it's fixed

![image](https://user-images.githubusercontent.com/290351/33531326-9d402514-d859-11e7-89b5-96eb9f5235c7.png)
