### ISSUE TITLE
[HTML5] - A bug with both "Close Chat" controls

### ISSUE THREAD

**Issue by OZhurbenko** [bigbluebutton/bigbluebutton#4574]
When you open a chat with somebody initially, like on the example below - it shows up in the list of active chats, under "Messages". And we have 2 controls to close the chat, an arrow and an X button.

![close_chat_controls](https://user-images.githubusercontent.com/9299997/32066939-6a652586-ba4f-11e7-8080-f880ad891526.JPG)

The current behavior of both "close chat" controls:
1. Clicking an arrow closes the chat **and removes** it from the list of active chat sessions, which is incorrect.
2. Clicking X works as expected, but if you reopen the chat with that person after clicking X - it won't show up in the list of active chat sessions at all.

Expected behavior:
1. Clicking an arrow is supposed to just close the chat tab, not removing it from the list of active chat sessions.
2. Clicking 'X' is supposed to close the chat tab **and remove** it from the list of active chat sessions. If you decide to open it again - it's supposed to appear in the list of active chat sessions.

Here's a gif to demonstrate the current incorrect behavior:

![9c723e816ed034a7b63281cfe0f02852](https://user-images.githubusercontent.com/9299997/32066605-53833f48-ba4e-11e7-82ad-6e34e977c528.gif)

I suspect that it happened during the user list refactoring in #4291 . I remember this feature working before.

**Comment by oswaldoacauan** [comment]
I think that's actually expected.

We only keep the chat on the list if:
 - No in the close list
 - Is the current chat
 - Has messages

Maybe we should change that, but the current behavior is expected.

**Comment by OZhurbenko** [comment]
Even if there are messages in the chat - you click 'X' to close it, open it again and it doesn't show up in the list of active chats.
That is not the expected behavior.

**Comment by oswaldoacauan** [comment]
Yep, seems like we need to remove the chat from the closed list when you open it.

**Comment by OZhurbenko** [comment]
It only leaves the issue with 'X' button though.
I can see that the chat stays on the list when you click Arrow if there are messages in the chat session.

**Comment by Gcampes** [comment]
That is because from what I remember the behavior of the close and the back buttons on the chat are different.
