### ISSUE TITLE
Settings screen not scaled on devices with narrow screen (<450px)

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#4576]
![screenshot from 2017-10-26 13-56-05](https://user-images.githubusercontent.com/6312397/32069024-f3e1e0e6-ba55-11e7-8504-00e4637de50b.png)

**Comment by antobinary** [comment]
@Tainan404

**Comment by tylercopeland** [comment]
@Tainan404 @antobinary 

For smaller screens (< 450px), I believe the best approach (for the current implementation) is to display all the settings on the screen and stack them on top of each other. Refer to the screenshot below. 

Left is the mobile mockup and to the right is the current implementation. 

<img width="1188" alt="screen shot 2017-11-30 at 7 23 51 pm" src="https://user-images.githubusercontent.com/1273169/33462199-4140574a-d604-11e7-9e2d-393ac6325465.png">

Something to note, I think we could come up with a more mobile approach that easily scales as we start to introduce more items in the settings section. However, that would involve having a list of setting items stacked on top of each other, and when an item is selected, it will bring you to a new screen showing the options for the settings item.

This InVision link shows an earlier mobile concept with this approach. 

https://invis.io/FZ5M6TIQE#/128080995_Bbb_Mobile_Portrait_Settings_5

**Comment by tylercopeland** [comment]
Here's an at scale export of the mobile settings screen. 

![settings](https://user-images.githubusercontent.com/1273169/33462479-bf4259a8-d605-11e7-976f-be0d520fa3b6.png)

**Comment by antobinary** [comment]
Looks great, @tylercopeland!

**Comment by antobinary** [comment]
Resolved
