### ISSUE TITLE
[HTML5] Use Transition/TransitionGroup for Toast animations

### ISSUE THREAD

**Issue by OZhurbenko** [bigbluebutton/bigbluebutton#4579]
Animation package is updated in #4578 
When it's merged we should move [client/stylesheets/toastify.css](https://github.com/bigbluebutton/bigbluebutton/blob/v2.0.x-release/bigbluebutton-html5/client/stylesheets/toastify.css#L1) file to the Toast's `styles.scss` and animate it using the Transition/TransitionGroup.

**Comment by pedrobmarin** [comment]
@antobinary are we good on this one?
