### ISSUE TITLE
Add create API parameters for logo and footer text

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#4590]
We added branding in the config.xml in BigBlueButton 2.0-beta

~~~
    <branding logo="logo.swf" copyright="&#169; 2017 &lt;u&gt;&lt;a href=&quot;https://test-install.blindsidenetworks.com/home.html&quot; target=&quot;_blank&quot
;&gt;BigBlueButton Inc.&lt;/a&gt;&lt;/u&gt; (build {0})" background="" toolbarColor="" showQuote="true"/>
~~~

Add two API parameters to the create call for 

  logo=<filename>
  copyright=<text>

Regards,... Fred

**Comment by mikhailnov** [comment]
Yes, that will be great to create sessions passing the logo as a parameter! Thank you.

**Comment by fcecagno** [comment]
Can't we use the setConfigXML API call for this?

**Comment by ritzalam** [comment]
New logo parameter to override logo in client is implemented in https://github.com/bigbluebutton/bigbluebutton/commit/f5502a1a2ad2c7ad4ad4e220b35753fcd7ae5394
