### ISSUE TITLE
Cleaning logs doesn't clear freeswitch's log file, but old error causes logging

### ISSUE THREAD

**Issue by adnanel** [bigbluebutton/bigbluebutton#4595]
I'm not sure if `freeswitch.log` was moved to a new location, but it doesn't get cleared (anymore?).
Now it's located in `/opt/freeswitch/var/log/freeswitch/freeswitch.log`

Meanwhile, when starting up BBB we get this logged:
```
# Error: Found text in freeswitch.log:
#    Thread ended for mod_event_socket
#
# FreeSWITCH may not be responding to requests on port 8021 (event socket layer)
# and users may have errors joining audio.
#
```
The  check for that error is at the line 1142 in this file 
https://github.com/bigbluebutton/bigbluebutton/blob/ffb58bf086c1ad9b49592e8de50d1d5b2d7195fd/bigbluebutton-config/bin/bbb-conf#L1142

Which is a simple grep of the `freeswitch.log` file looking for the error.
In our situation, the error that BBB found in the log was a week old and not relevant anymore, so I'd suggest on of the following:

- Clear the freeswitch.log file log ( here https://github.com/bigbluebutton/bigbluebutton/blob/ffb58bf086c1ad9b49592e8de50d1d5b2d7195fd/bigbluebutton-config/bin/bbb-conf#L1868 )
- Remove the check completely, it tries to connect to the event socket layer right after the above check and logs if it has failed.

**Comment by ffdixon** [comment]
Thanks for the report.  The FreeSWITCH logs do rotate after one week (I think!), so after a bit that message will disappear.  

The `sudo bbb-conf --clean` is for clearing out the log files.  So, if you do a

~~~
  sudo bbb-conf --clean
  sudo bbb-conf --check
~~~

you won't see that message.

**Comment by adnanel** [comment]
We tried cleaning, it didn't clear the `freeswitch.log` (that's why I posted here), I'll very soon...

**Comment by adnanel** [comment]
Just checked, neither clean, restart, stop or start clean the freeswitch log file and we still get the message.
Though it's not that tragic if they rotate weekly.
