### ISSUE TITLE
Text in presentation upload dialog is out of borders in BBB 2.0 new Flash client skin

### ISSUE THREAD

**Issue by mikhailnov** [bigbluebutton/bigbluebutton#4598]
See the screenshot. To reproduce the problem choose the Russian (Русский) language, upload a presentation and see the text that it is being converted.

![](https://i.imgur.com/IwWDaqzl.png)

**Comment by ffdixon** [comment]
Thanks for reporting this.  We'll fix as part of 2.0-beta.

**Comment by ffdixon** [comment]
Hi mikhailnov -- can you test this on 

  https://demo.bigbluebutton.org/

and let us know if you still encounter this issue.

**Comment by mikhailnov** [comment]
Yes, it's now fixed. Thanks to everyone!
