### ISSUE TITLE
Config auto reconnect timeout

### ISSUE THREAD

**Issue by mikhailnov** [bigbluebutton/bigbluebutton#4599]
When the Flash BBB client looses connection with the server, it tries to reconnect for some time and then displays an error that the connection has been lost. 
Is it possible to configurate this timeout to make it retry reconnecting for a longer time?
If not, it's a feature request))

**Comment by ffdixon** [comment]
Closing as this issue relates to the Flash client, which is no longer under development.  We've moved to the HTML5 client.
