### ISSUE TITLE
muteOnStart stopped working after upgrade from 1.1 to 2.0-beta

### ISSUE THREAD

**Issue by oliver-74** [bigbluebutton/bigbluebutton#4612]
I have changed

meeting muteOnStart="false"
to
meeting muteOnStart="true"
in config.xml

on my 2.0-beta server build 757 but users do not get muted on join. Neither in the Flash client nor in the HTML5 client.

This feature was working fine on my 1.1 server. Any chance you made some changes to the related code?

This might be related to #4510 but it is still a different aspect of muting.

**Comment by ritzalam** [comment]
The reason this stopped working is that the param isn't propagated from client into akka-apps. The proper way of setting this should be on the create API call or setting the bigbluebutton.properties in bbb-web.

Are you able to modify your code to pass this in the create API call? Or at the very least modify bigbluebutton.properties in bbb-web?

**Comment by ritzalam** [comment]
PR in https://github.com/bigbluebutton/bigbluebutton/pull/4861

**Comment by oliver-74** [comment]
Richard, changing this to the API makes sense, as now it can be enabled per meeting and not as a server-wide parameter. I'm using the muteOnStart in combination with the BBB Moodle plugin, so I assume this change of the API would have to be included in the Moodle plugin in order to get it working again for me?

**Comment by ritzalam** [comment]
The moodle plugin has to be changed to support this. While waiting for the change, the value can be set in bigbluebutton.properties to set it system wide.

**Comment by oliver-74** [comment]
Richard,

I have just installed the latest -dev build (782) which should contain your recent merge.

As after the update I found the new parameter

# Mute the meeting on start
muteOnStart=false

in

/var/lib/tomcat7/webapps/bigbluebutton/WEB-INF/classes/bigbluebutton.properties

but changing it there to true and restarting BBB does not do anything.

Do I have to change this somewhere else to make it work until the Moodle API is updated?

**Comment by ritzalam** [comment]
No, you don't have to do anything. I assume the client also is up to date if you upgraded using packages.

Can you use API Mate to create the meeting and then all the ENTER API to see if muteOnStart is set?

http://mconf.github.io/api-mate/

**Comment by ffdixon** [comment]
We haven't yet pushed the packaging updates to the public repo, so hang on for a few more days and you should be able to update your 2.0-beta server to the latest packages.

**Comment by ritzalam** [comment]
He says he is on the -dev package repo. So he must have the latest. Will investigate further when I get the chance.

**Comment by ritzalam** [comment]
I confirm that setting the property mteOnStart=true in /var/lib/tomcat7/webapps/bigbluebutton/WEB-INF/classes/bigbluebutton.properties doesn't work.

But passing param muteOnStart=true in CREATE API call works.

**Comment by ritzalam** [comment]
This should be fixed with this PR https://github.com/bigbluebutton/bigbluebutton/pull/4922

**Comment by oliver-74** [comment]
Ok I can confirm that with the changes from today, muteOnStart is working again in the Flash client. I could not test it with the HTML5 client as the version currently on the -dev server is not even starting up.

**Comment by ffdixon** [comment]
Glad to hear it worked!

> I could not test it with the HTML5 client as the version currently on the -dev server is not even starting up.

We're working on that ... we've made a bunch of updates and should have it going shortly.
