### ISSUE TITLE
How to make recording links require user account/authorization?

### ISSUE THREAD

**Issue by Jarvil** [bigbluebutton/bigbluebutton#4613]
Hello,

if you want to move BBB-recording from Moodle course to another you can open the presentation and copy/paste the link. 

But the link is "unsecure" since you can share it outside of Moodle and if you have the link you can access it from anywhere from the internet.

Shoudn't there be some kind of authorization or user account requirement for it to work? Maybe so that it would require Moodle user account to view the video?

**Comment by pedrobmarin** [comment]
Excellent discussion about this issue at https://github.com/bigbluebutton/bigbluebutton/issues/8505
