### ISSUE TITLE
Screen sharing closes unexpectedly - probable bug

### ISSUE THREAD

**Issue by schrink** [bigbluebutton/bigbluebutton#4657]
Hi, 

On website demo https://demo.bigbluebutton.org when I try to share screen, applet starts and closes immediately and I get Screen sharing closed unexpectedly error. I am running on Mac, tried with Chrome and Firefox - same error. Latest version of Java. 

Any clue? 

Thanks, V.

**Comment by ffdixon** [comment]
We fixed a configuration error on the server.  Can you try it again -- it should work correctly now.
