### ISSUE TITLE
[HTML5] - Assigning yourself a presenter breaks the client

### ISSUE THREAD

**Issue by OZhurbenko** [bigbluebutton/bigbluebutton#4668]
Self-assigning a presenter breaks the client, if "Make Presenter" is the only option in the dropdown.

![presenter-assign](https://user-images.githubusercontent.com/9299997/32796239-2878f5c0-c93c-11e7-8bd7-a33333dcc03e.gif)

**Comment by antobinary** [comment]
@Tainan404

**Comment by antobinary** [comment]
Resolved
