### ISSUE TITLE
The logout timer obeys the completely unrelated 'defaultMeetingDuration' property

### ISSUE THREAD

**Issue by capilkey** [bigbluebutton/bigbluebutton#4675]
When the logout timer was put in it was for some reason hooked up to the 'defaultMeetingDuration' property in bigbluebutton.properties. That property is a default for the 'duration' parameter on the create API call and has nothing to do with the logout timer. 

The problematic line, https://github.com/bigbluebutton/bigbluebutton/blame/79dccefecb2b0758339577f76791c7f4d72ae402/bbb-common-web/src/main/java/org/bigbluebutton/api/ParamsProcessorUtil.java#L351.

The logout timer should have its own default and shouldn't be piggybacking off of a completely unrelated feature.

**Comment by ritzalam** [comment]
Fixed in 2.1.x. Just hardcode to zero as we don't use this in 2.0.x. Should have been implemented in 2.1.x branch instead of 2.0.x.

**Comment by ritzalam** [comment]
PR https://github.com/bigbluebutton/bigbluebutton/pull/4844
