### ISSUE TITLE
Media device permissions are asked when you try to join listen only audio

### ISSUE THREAD

**Issue by Gcampes** [bigbluebutton/bigbluebutton#4690]
When you try to join audio in the html5 client in listen only mode, even though it is listen only, microphone permissions are asked.

The exact code that makes the permissions to be asked is [here](https://github.com/bigbluebutton/bigbluebutton/blob/master/bigbluebutton-html5/imports/ui/services/audio-manager/index.js#L68):
```javascript
 if (!this.devicesInitialized) {
      this.setDefaultInputDevice();
      this.changeOutputDevice('default');
      this.devicesInitialized = true;
 }
```
The problem I encountered when trying to fix this issue is that for some reason, if you don't run the `this.setDefaultInputDevice()` in firefox, the call ends in a `ICE Fail` error.
In Chrome, everything works fine, if you don't ask for permissions, and join listen only mode, it will join without any issues.
I am sure the wanted behavior is possible, because Flash does it, and as far as I know flash does it like [this](https://github.com/bigbluebutton/bigbluebutton/blob/master/clients/flash/web-client/src/main/resources/lib/bbb_webrtc_bridge_sip.js#L308):
```javascript
 if (isListenOnly) {
   // create necessary options for a listen only stream
   var stream = null;
   // handle the web browser
   // create a stream object through the browser separated from user media
   if (typeof webkitMediaStream !== 'undefined') {
     // Google Chrome
     stream = new webkitMediaStream;
   } else {
     // Firefox
     audioContext = new window.AudioContext;
     stream = audioContext.createMediaStreamDestination().stream;
   }
 ...
```

Even though we are doing it pretty [similar](https://github.com/bigbluebutton/bigbluebutton/blob/master/bigbluebutton-html5/imports/ui/services/audio-manager/index.js#L163) in our bridge, it is is not working properly.
```javascript
 createListenOnlyStream() {
   if (this.listenOnlyAudioContext) {
     this.listenOnlyAudioContext.close();
   }
   this.listenOnlyAudioContext = window.AudioContext ?
                                 new window.AudioContext() :
                                 new window.webkitAudioContext();
    return this.listenOnlyAudioContext.createMediaStreamDestination().stream;
 }
```

**Comment by capilkey** [comment]
Listen-only in the Flash client goes through red5 not WebRTC. The listen-only code in bbb_webrtc_bridge_sip.js was put in for the HTML5 client to use only so I'm not sure if it works or not.

**Comment by oswaldoacauan** [comment]
Related: https://bugzilla.mozilla.org/show_bug.cgi?id=959893

**Comment by oswaldoacauan** [comment]
Related: https://github.com/onsip/SIP.js/issues/436
