### ISSUE TITLE
Line wraps in recording

### ISSUE THREAD

**Issue by mikhailnov** [bigbluebutton/bigbluebutton#4692]
bbb-apps 1:2.0.0-38
I see in the recording playback:
```
Не спеши, остановись, посмотри вокругМожет рядом, где-то близко притаился вдругВидимый объект, способный путь вам указать
```
But in the flash client it was:
```
Не спеши, остановись, посмотри вокруг
Может рядом, где-то близко притаился вдруг
Видимый объект, способный путь вам указать
```

**Comment by ffdixon** [comment]
Could you reproduce this on https://demo.bigbluebutton.org/ and post a link to the recording here.

This way, we could take a look at the source recording and track down why there are no carriage returns.

**Comment by mikhailnov** [comment]
https://demo.bigbluebutton.org/playback/presentation/2.0/playback.html?meetingId=9f3ff095ad70976b3bd93e1cf33131b262df505b-1511118288698

**Comment by mikhailnov** [comment]
I am using Xubuntu 17.10 (Ubuntu + XFCE), but the original author of the text probably used Windows

**Comment by ffdixon** [comment]
Got it -- thanks!  We'll take a closer look.
