### ISSUE TITLE
list configs in debian/conffiles

### ISSUE THREAD

**Issue by mikhailnov** [bigbluebutton/bigbluebutton#4693]
I am a bit fed up with that config files are not listed in debian/conffiles, e.g. I've just changed the max file upload limit and it has been overwritten after updating bbb packages, just because the config files are not listed in debian/conffiles https://www.debian.org/doc/manuals/maint-guide/dother.en.html#conffiles

And please post debian packages sources to make it possible to commit into them and rebuild them locally easier, including building the development version of BBB as deb packages

**Comment by mikhailnov** [comment]
/var/www/bigbluebutton/client/conf/config.xml
is not marked as a config file in debian packages

**Comment by ffdixon** [comment]
We've specifically excluded some of the configuration files from the packaging as they get updated by bbb-conf.  

In particular, the files `/var/www/bigbluebutton/client/conf/config.xml` and `/var/lib/red5/webapps/bigbluebutton/WEB-INF/bigbluebutton.properties` are not listed as configuration files as the user would be prompted to confirm updates on each package upgrade.

> And please post debian packages sources to make it possible to commit into them and rebuild them locally easier, including building the development version of BBB as deb packages

The packaging of BigBlueButton has evolved over the years and we've updated it many times over the releases.  We've made some substantial improvements over the years and had the freedom to do so without worrying about breaking anyone building upon it.   

> I've just changed the max file upload limit

There is logic in the packages to propagate some of the values in `config.xml` to the newer version.  We've added the parameter `maxFileSize` to the list of parameters that will be automatically propagated.

This update to the bbb-client packaging will be in the next update to BigBlueButton 2.0-beta.

**Comment by ffdixon** [comment]
Pushed out the latest update to the packaging that includes the propagation of maxFileSize.

**Comment by mikhailnov** [comment]
Thank you. But both solutions, not marking configs as configs and changing the config by script trying to save some changes to it, are not good, but I don't know how to make it better.
If there were debian specs available, it would be possible to make pacthes, rebuild packages , the git fetch upstream changes and build newer versions.
