### ISSUE TITLE
Improvements to Presentation Management

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#4700]
Should cover the remaining items from #4423 and #4371 
- [x] The modal doesn't close if you lose presenter status.
- [x] Meteor calls errors are not being handled.
- [x] You end in a stuck "state" if there is an upload/convert error.
- [x] If an upload/convert error occurs and that presentation is marked as current you end up without any current presentation.
- [ ] there is no indication of what presentation is your current presentation
- [x] If you upload at the same time files with the same name, the client will not work as expected

**Comment by oswaldoacauan** [comment]
We need @tylercopeland to solve "there is no indication of what presentation is your current presentation" since there is no design for that indication.

**Comment by capilkey** [comment]
Can you just show a blank area or even something like the text "There's no active presentation".

**Comment by oswaldoacauan** [comment]
@capilkey actually thats not what the item is about. The item is about showing somehow the user which presentations is the "real" current, since you can change the current and while you dont press the "Save" button, the current indicator will not represent the real current presentation.

**Comment by capilkey** [comment]
Ah I gotcha. Didn't realize it was specifically referring to the upload modal.

**Comment by antobinary** [comment]
@oswaldoacauan - can you please provide some more context on item `there is no indication of what presentation is your current presentation` - what scenario are we talking about?

**Comment by tylercopeland** [comment]
@oswaldoacauan you've raised a great point! To solve this, I think we can introduce a "current" tag to the right of the current present name. In the case of the mockup below, the current presentation is the default.pdf presentation. 

![bbb_presentation_upload](https://user-images.githubusercontent.com/1273169/33400499-5b9db564-d524-11e7-98cc-3906c259c142.png)

**Comment by tylercopeland** [comment]
@oswaldoacauan you've raised a great point! To solve this, I think we can introduce a "current" tag to the right of the current present name. In the case of the mockup below, the current presentation is the default.pdf presentation.

![bbb_presentation_upload](https://user-images.githubusercontent.com/1273169/33400789-25aaea5c-d525-11e7-8002-187b76f598d5.png)

**Comment by OZhurbenko** [comment]
@tylercopeland stop right here! 😄 

A few questions left to discuss:

1. Currently in htm5 you can't delete your current presentation without the checkbox auto-selecting something else. Is it good or bad? In Flash you can actually delete the current presentation and display nothing, if you wish.
2. Checkbox for file download (one of the future features) is missing. Are we doing it now?

**Comment by tylercopeland** [comment]
@OZhurbenko 

1. I don't see it being a problem with deleting the currently selected presentation, however, if you don't have any selected, a message should appear suggesting to the user that they should choose a presentation to display.

2. I believe that's a feature we'll be adding to the HTML5 client (@antobinary please correct me if I'm wrong). Regarding its location, I can appear above or below the list of presentations.

**Comment by oswaldoacauan** [comment]
> Checkbox for file download (one of the future features) is missing. Are we doing it now?

I think @antobinary mentioned it for 2.1 when I asked in some dev meeting.

**Comment by tylercopeland** [comment]
@OZhurbenko I should have been more specific, sorry about that.  @oswaldoacauan is correct,  the checkbox for file download is a 2.1 feature.

**Comment by OZhurbenko** [comment]
@tylercopeland sounds great, thanks!

**Comment by antobinary** [comment]
Resolved in #4733
