### ISSUE TITLE
Locking the layout does not hide the minimize/maximize buttons for desktop sharing

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#4703]
When the instructor has locked the layout, the users are still able to minimize/maximize the desktop sharing window.

Before locking

![image](https://user-images.githubusercontent.com/290351/33048063-02e6146a-ce27-11e7-8fdf-ce138fac2741.png)

After locking

![image](https://user-images.githubusercontent.com/290351/33048076-1b7518c8-ce27-11e7-8124-69862571450d.png)

**Comment by capilkey** [comment]
This might be because the layout module doesn't control the screen sharing window. The screen sharing windows are all in the exclusion list.

**Comment by ffdixon** [comment]
Closing as this was an issue related to the Flash client (the project has moved to an HTML5 client).
