### ISSUE TITLE
Update the join audio icon to use the phone icon

### ISSUE THREAD

**Issue by tylercopeland** [bigbluebutton/bigbluebutton#4715]
Before this task can be implemented, it needs to be added to the BBB-font.

**Comment by tylercopeland** [comment]
@antobinary here's a link to the updated bigbluebutton icon font that includes new icons for joining and leaving the audio. 

https://github.com/bigbluebutton/bigbluebutton-font/commits/master

Please note, I used the same naming for the icons, so all that is needed is replacing the font file.

**Comment by antobinary** [comment]
Thank you, Tyler! Got it!

**Comment by antobinary** [comment]
Waiting for #4779 to be closed to avoid conflicts

**Comment by antobinary** [comment]
Resolved
