### ISSUE TITLE
how to fix error "W: GPG error: on update BigBlueButton for install BBB HTML5

### ISSUE THREAD

**Issue by bijism** [bigbluebutton/bigbluebutton#4728]
root@webinar:~# sudo apt-get update Get:1 http://ubuntu.bigbluebutton.org/xenial-200 bigbluebutton-xenial InRelease [2,510 B] Ign:1 http://ubuntu.bigbluebutton.org/xenial-200 bigbluebutton-xenial InRelease Hit:2 http://us.archive.ubuntu.com/ubuntu xenial InRelease Hit:3 http://security.ubuntu.com/ubuntu xenial-security InRelease Hit:4 http://us.archive.ubuntu.com/ubuntu xenial-updates InRelease Hit:5 http://us.archive.ubuntu.com/ubuntu xenial-backports InRelease Fetched 2,510 B in 9s (255 B/s) Reading package lists... Done W: GPG error: http://ubuntu.bigbluebutton.org/xenial-200 bigbluebutton-xenial InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 37B5DD5EFAB46452 W: The repository 'http://ubuntu.bigbluebutton.org/xenial-200 bigbluebutton-xenial InRelease' is not signed. N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use. N: See apt-secure(8) manpage for repository creation and user configuration details.

root@webinar:~#

senario :-1: 
BigBlueButton2 installed and run File: /etc/apt/sources.list.d/bigbluebutton.list

**Comment by ffdixon** [comment]
Did you already add the apt-ket for BigBlueButton to Ubuntu?  See

   http://docs.bigbluebutton.org/install/install.html#2-install-apt-get-key-for-bigbluebutton-repository
