### ISSUE TITLE
Focus doesn't always trigger a dropdown

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#4739]
The focus doesn't always trigger a dropdown.
Approximately in 15 to 20% of the cases it moves the focus, but it doesn't show the dropdown.
![33151816-a4f992f0-cfa7-11e7-9069-9a29c1a4c6a4](https://user-images.githubusercontent.com/6312397/33331244-19605594-d42f-11e7-8a84-57c3a0fb8a50.gif)
First reported by @OZhurbenko in #4682

**Comment by Tainan404** [comment]
I tried to simulate the bug, but to no avail. I even created a bot that pressed the buttons quickly to see if an hour failed.
Talking to Oswaldo he said it may be the setState's fault that does not instantly update the state and some time it takes longer than it should generate the bug.
Because this is very random.

**Comment by antobinary** [comment]
@OZhurbenko - originally you identified the issue. If you see it again could you please try to spot some kind of dependence - to narrow down when it occurs?

**Comment by OZhurbenko** [comment]
@Tainan404 @antobinary 
The only thing I can think about is the short delay in communication between Meteor client and server.
That would explain why you guys can't reproduce it locally, and why I can, I have different network settings for my dev environment.

I also just tried our public server - this issue happens more often there.

**Comment by oswaldoacauan** [comment]
@OZhurbenko nothing to do with delay or server communication nor network configuration. What we have here is a CSS issue where the UI leads you to click on a non-clickable part of the user-list item.

@Tainan404 will send a fix to it today.

**Comment by antobinary** [comment]
Resolved
