### ISSUE TITLE
Fullscreen is not working on iOS devices

### ISSUE THREAD

**Issue by OZhurbenko** [bigbluebutton/bigbluebutton#4770]
Tested on the iPad, iOS 11 in Chrome, FF, and Safari.

**Comment by KDSBrowne** [comment]
iOS 10 and 11 don't support the Fullscreen API.
https://caniuse.com/#feat=fullscreen

The fullsccreen API stopped working in iOS 9; it was suggested that this could be for security.
https://forums.tumult.com/t/full-screen-function-not-working-on-ios/10014/2

**Comment by antobinary** [comment]
Changing the release field to 2.1 - likely there will be no change by then but it would be a good idea to double check

**Comment by OZhurbenko** [comment]
@antobinary maybe we should remove the fullscreen button from the iOS devices at this point?
Who knows when they implement it, right now this button just looks broken :-)

P.S. I used this [one line method](https://github.com/bigbluebutton/bigbluebutton/blob/2f1c4bcc77af96716dff386cb79f124ac23ec07c/bigbluebutton-html5/imports/ui/components/whiteboard/annotations/text/component.jsx#L62) to detect iOS devices - had no issues so far.

**Comment by antobinary** [comment]
Good point, Alex! Let's hide the fullscreen UI on iOS to avoid confusion. Opened #4823 to track it
