### ISSUE TITLE
Node.js on Ubuntu 16.04 is not /usr/bin/node, but /usr/bin/nodejs

### ISSUE THREAD

**Issue by jwarnier** [bigbluebutton/bigbluebutton#4771]
Trying to install BBB 1.1, I got this error when going through bbb-html5:

```
Installing meteor packages (this may take a moment)
Updating Node packages for bbb-html5 (this may take a moment)
loadDep:uuid → mapToRegis ▀ ╢████████████████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟

> fibers@1.0.15 install /usr/share/meteor/bundle/programs/server/node_modules/fibers
> node build.js || nodejs build.js

sh: 1: node: not found
`linux-x64-46` exists; testing
Binary is fine; exiting

> meteor-dev-bundle@0.0.0 install /usr/share/meteor/bundle/programs/server
> node npm-rebuild.js

sh: 1: node: not found

npm WARN meteor-dev-bundle@0.0.0 No description
npm WARN meteor-dev-bundle@0.0.0 No repository field.
npm WARN meteor-dev-bundle@0.0.0 No license field.
npm ERR! Linux 3.16.43
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" 
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! meteor-dev-bundle@0.0.0 install: `node npm-rebuild.js`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the meteor-dev-bundle@0.0.0 install script 'node npm-rebuild.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the meteor-dev-bundle package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node npm-rebuild.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs meteor-dev-bundle
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls meteor-dev-bundle
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/share/meteor/bundle/programs/server/npm-debug.log
dpkg: error processing package bbb-html5 (--configure):
 subprocess installed post-installation script returned error exit status 1
```

As you can see from the "sh: 1: node: not found" error message, "node" is not in the path, while /usr/bin/nodejs exists.
Locally, I created a link from /usr/bin/nodejs->/usr/bin/node, and everything works fine, but it should be solved at the packaging level.

Sincerely,

**Comment by OZhurbenko** [comment]
> Locally, I created a link from /usr/bin/nodejs->/usr/bin/node, and everything works fine, but it should be solved at the packaging level.

node's renaming to nodejs is a very old issue, the name of the package was changed starting at Ubuntu 12.04 if I'm not mistaken. 
In order for it to work you should just install `nodejs-legacy` package, which literally contains the same link that you just created.

We used to have a step with `nodejs-legacy` in the HTML5 installation [instructions](http://docs.bigbluebutton.org/html/html5-install.html#1-install-mongdb-and-nodejs), but it disappeared somewhere.

I have added it back.

**Comment by capilkey** [comment]
Is the nodejs-legacy still relevant for 2.0 or was it only needed for the 1.1 version of the HTML5 client? Maybe that's why it was removed.

**Comment by OZhurbenko** [comment]
It is not that we could fix it..
You see - Meteor still uses `node` command instead of `nodejs` in some places.

In this log they have 1st:
`node build.js || nodejs build.js` which uses either one of them
but then in the next command they have: `node npm-rebuild.js` which relies on a legacy name only and fails 😕 

Same thing happens with some of the npm packages, that are pulled and built locally.

The confusing part is that sometimes that node symlink comes together with the installed nodejs, and sometimes it doesn't, depending on the repository, depending on the version, etc.
