### ISSUE TITLE
freeswitch.service: Failed at step SETSCHEDULER spawning /opt/freeswitch/bin/freeswitch: Operation not permitted

### ISSUE THREAD

**Issue by jwarnier** [bigbluebutton/bigbluebutton#4773]
On Ubuntu 16.04 (Xenial):

When executed in some virtualization contexts (e.g. Xen), SystemD fails to set "CPUSchedulingPolicy" of the unit file /lib/systemd/system/freeswitch.service, and the service fails to start.

The solution is to use a local FreeSwitch service unit file without those scheduling options set, overriding the one in the bbb-freeswitch-core package.

Not sure if there is any clean solution (i.e. a conditional unit file) to this, but I believe it is worth mentioning it.

**Comment by ffdixon** [comment]
There is some documentation already that covers this, see
 
   http://docs.bigbluebutton.org/install/install.html#fneeswitch-fails-to-start-with-a-setscheduler-error
