### ISSUE TITLE
Make call-in/dial-in users visually different than web users

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#4786]
* currently the user-list-item colour is hardcoded to #ffffff
* potentially add some kind of phone identification

This is what it looks on the Flash client in BBB 2.0 as of Dec 08, 2017
![screenshot from 2017-12-08 14-39-50](https://user-images.githubusercontent.com/6312397/33782241-e3e4a7cc-dc25-11e7-8974-df7e71ffa4f3.png)
user `mackerel` has dialed in

**Comment by tylercopeland** [comment]
@antobinary I've explored something similar in another workflow. What are your thoughts on displaying call-in/dial-in users like this?

![bbb-html5-userslist](https://user-images.githubusercontent.com/1273169/36866071-4c1dcd12-1d5f-11e8-9dd6-4019125a4d94.png)

**Comment by antobinary** [comment]
![Screenshot from 2019-05-22 16-17-25](https://user-images.githubusercontent.com/6312397/58285299-78579a80-7d7a-11e9-93d2-38513a6ca478.png)
Looks like this was implemented. @tylercopeland Please confirm (the bottom user is a dial-in one, middle user just has digits in the name)

**Comment by tylercopeland** [comment]
@antobinary the dialled-in user looks good.
