### ISSUE TITLE
Uploading files with the same name or defaultFileName

### ISSUE THREAD

**Issue by oswaldoacauan** [bigbluebutton/bigbluebutton#4805]
As discussed on PR #4733, currently we kinda "cheat" for the conversion status on new presentations when they have the same name.
Same goes for files named `default.pdf`.

Implementing the file counter on the client-side would solve one half of the problem, since if you upload a file named `default.pdf` the HTML5 will break anyway.

Then what we need to do is make the upload endpoint return the `presentationId` of the uploaded presentation.

**Comment by antobinary** [comment]
Merge into #6847
