### ISSUE TITLE
ActionsBar buttons aren't aligned correctly on small screens

### ISSUE THREAD

**Issue by OZhurbenko** [bigbluebutton/bigbluebutton#4819]
Found that our Actions Bar buttons are not aligned properly, since we got presenter's Actions, Audio, and the Video is on its way.

This is how they look now:

![actions_bar_buttons](https://user-images.githubusercontent.com/9299997/33974793-5e0fdfd6-e058-11e7-8d15-a958713fc78d.JPG)

This is how they are supposed to look:

![actions_bar_buttons_2](https://user-images.githubusercontent.com/9299997/33974814-82e6561e-e058-11e7-934d-dd5d77ba23a2.JPG)

**Comment by antobinary** [comment]
Resolved
