### ISSUE TITLE
Improve placement and visual look of the presentation controls

### ISSUE THREAD

**Issue by tylercopeland** [bigbluebutton/bigbluebutton#4853]
Heading into the 2.1 release of the HTML5 client we're going to need an area for the fit-to-width and fit-to-page buttons. This is what led to the creation of the latest designs for the presentation controls. 

Before:

![screen shot 2017-12-20 at 2 19 02 pm](https://user-images.githubusercontent.com/1273169/34224449-ed8f4196-e590-11e7-949d-7bd4c825c225.png)

After:

![screen shot 2017-12-20 at 2 20 37 pm](https://user-images.githubusercontent.com/1273169/34224465-f9b398dc-e590-11e7-8899-6723f1e8567f.png)

Full Screenshot:

![desktop](https://user-images.githubusercontent.com/1273169/34224475-02eb683a-e591-11e7-90b8-cc941793570f.png)

**Comment by OZhurbenko** [comment]
We don't have a limit for the slides' width, users can upload a very narrow portrait slide.
In that case it's not really going to work..

**Comment by OZhurbenko** [comment]
Sure, but we have no control over the presentation size.
For example:

![presentation_size](https://user-images.githubusercontent.com/9299997/34225343-2488a7de-e594-11e7-924b-672297000fcd.JPG)

**Comment by tylercopeland** [comment]
@OZhurbenko you're raising some valid points here. But for the most part, presenters will be uploading any office document or PDF file (as stated in our upload dialogue), and not a skinny image (as shown in the screenshot above).  Also, 9/10 presenters (who have uploaded a portrait PDF document) will zoom-in to make the content more legible to participants. 

This has me thinking, do we try to maximize presentation real-estate and experience by having any presentation set to fit-to-width by default on upload. That way we won't run into situations that you've outlined above, we can show all future presentation controls and avoid additional steps for better viewing experience of portrait documents (set the presentation to fit-to-width).

**Comment by OZhurbenko** [comment]
@tylercopeland I'm just worrying about the edge cases. It will be look very nice in most of the cases, of course..

Theoretically, even if it's fit-to-width by default - a presenter can still switch back to fit-to-page and zoom out.. and that will "destroy" the presentation controls 😕 

Maybe it's better to keep the whole line (100% width) similar to what we have in the Flash client?..

**Comment by tylercopeland** [comment]
@OZhurbenko just revisiting this issue now that I've explored the experience of sharing a portrait document in the HTML5 client. 

GitHub issue -> https://github.com/bigbluebutton/bigbluebutton/issues/5185

cc/ @antobinary

**Comment by antobinary** [comment]
Merge into #5191
