### ISSUE TITLE
Disable microphone AutoGainControl

### ISSUE THREAD

**Issue by mikhailnov** [bigbluebutton/bigbluebutton#4873]
On different OSes with different hardware (microphones) from time to time Chromium's and probably Firefox's) feature of autoadjusting the microphone input level goes crazy and makes good sound impossible.
I do not understand why, but Chromium developers do not want to make an option to disable this
https://bugs.chromium.org/p/chromium/issues/detail?id=792391
https://bugs.chromium.org/p/chromium/issues/detail?id=376796
https://bugs.chromium.org/p/chromium/issues/detail?id=435112
So it would be very useful to make a setting in BBB client to disable Auto Gain Control (Chromium's API allows this)...
In general, the speaker does not move away from the microphone or closer to it, I'm not sure that AutoGainControl is more useful than useless.

https://testing.googleblog.com/2015/10/audio-testing-automatic-gain-control.html

https://stackoverflow.com/questions/26485049/how-can-i-disable-automatic-gain-control-agc-in-webrtc-web-apps-such-as-google

**Comment by mikhailnov** [comment]
Oh, I already reported a similar isue about a year and a half ago (have just googled it): https://github.com/bigbluebutton/bigbluebutton/issues/3086

**Comment by ffdixon** [comment]
Thanks for pointing this out.  

As we're moving towards a delivery of the HTML5 client, which doesn't have any audio except WebRTC, we'll look at adding this option if the user is running BigBlueButton Linux machine.

No promises on the delivery of this feature, but we definitely see the need of it.

**Comment by mikhailnov** [comment]
I is not specific for Linux. My occur on Windows as well.

**Comment by IAmMukeshKumar** [comment]
Hi @ffdixon ,

I want to set Listen only option. I don't want show this dialogue.
![image](https://user-images.githubusercontent.com/13366065/64904805-bfccb280-d6ec-11e9-81a9-1b8382cec2dc.png)

**Comment by capilkey** [comment]
@IAmMukeshKumar Please don't post on unrelated issues. What you posted also isn't an issue and should be directed to the setup mailing list, https://groups.google.com/forum/#!forum/bigbluebutton-setup

**Comment by mikhailnov** [comment]
I have accidently found out thay AGC may be disabled in Firefox:
media.getusermedia.aec_enabled (Acoustic Echo Cancellation)
media.getusermedia.agc_enabled (Automatic Gain Control)
media.getusermedia.noise_enabled (Noise suppression)
From https://wiki.archlinux.org/index.php/Firefox/Tweaks

**Comment by zeroset** [comment]
Any progress here?

**Comment by mariogasparoni** [comment]
@mikhailnov this issue can be closed now

**Comment by prlanzarin** [comment]
Fixed by #11262
