### ISSUE TITLE
Add a subtle drop-shadow to the main navigation

### ISSUE THREAD

**Issue by GhaziTriki** [bigbluebutton/bigbluebutton#4877]
Here is the css for it. 
background: #FFFFFF;
box-shadow: 0 2px 10px 0 rgba(0,0,0,0.10);

<img width="2220" alt="screen shot 2017-08-29 at 4 06 21 pm" src="https://user-images.githubusercontent.com/4991088/34496061-554c7256-eff8-11e7-9c4c-99e4574ed08c.png">

**Comment by ffdixon** [comment]
Closing as this was an issue related to the Flash client (the project has moved to an HTML5 client).
