### ISSUE TITLE
Reduce the height above text in private messages

### ISSUE THREAD

**Issue by GhaziTriki** [bigbluebutton/bigbluebutton#4879]
Remove the grey area in chat messages

![pasted image at 2017_09_12 03_37 pm](https://user-images.githubusercontent.com/4991088/34496210-efee8dee-eff8-11e7-945e-f2454a69c55b.png)

**Comment by ffdixon** [comment]
Closing as this was an issue related to the Flash client (the project has moved to an HTML5 client).
