### ISSUE TITLE
Start / create new shared notes

### ISSUE THREAD

**Issue by tylercopeland** [bigbluebutton/bigbluebutton#4886]
The designs for this experience should also include the actions of undoing, redoing and downloading a note.

**Comment by tylercopeland** [comment]
Below are the latest designs for the shared notes experience. 

**1. Initiating the shared notes experience**
A presenter/moderator will be to start a shared note experience by clicking the "+" button, followed by selecting "Shared Notes."

![html5-shared-notes-1](https://user-images.githubusercontent.com/1273169/42758814-c2c5f96a-88d2-11e8-86be-5005099fbd73.png)

**2. Shared note empty state**
After initiating a shared note, the note item will appear within the left sidebar and the note area to the right.

![html5-shared-notes-2](https://user-images.githubusercontent.com/1273169/42758886-12310d64-88d3-11e8-990d-d5f1fe5294ad.png)

**3. Shared note populated state**
For the first version of the shared notes experience, I believe it's best to build a simple set of features and then add as we receive further feedback from our user base. In the screenshot below, the mockup includes the ability to bold, italic, strike, ordered list, unordered list, under and redo. 

Under the "three dots" icon is where  we will store clearing all and downloading the share note

![html5-shared-notes-3](https://user-images.githubusercontent.com/1273169/42758905-2018b1ac-88d3-11e8-8c63-3cc714a01656.png)

**4. Create a second shared note**
To create a second note, a presenter/moderator will be able to do so by selecting the "+" to the right of the  "Shared Notes" label. 

![html5-shared-notes-4](https://user-images.githubusercontent.com/1273169/42759061-a9162b10-88d3-11e8-8542-1d3ed6520836.png)


As per usual, I'd love to hear feedback from the community on this experience.

**Comment by fcecagno** [comment]
Great work @tylercopeland !
So, why don't we keep one default note already created (like Public Chat), so we can get rid of the option in the action "+" button? Or just leave the SHARED NOTES label there with the plus sign to create new notes?
I think it might be confusing once you can open a new shared note from the action button and from the participants list, so I'd suggest to keep it just in the participants list.

**Comment by antobinary** [comment]
Implemented
