### ISSUE TITLE
Start/share a poll

### ISSUE THREAD

**Issue by tylercopeland** [bigbluebutton/bigbluebutton#4888]

**Comment by tylercopeland** [comment]
Below is the first take of the HTML5 polling experience from both the presenter and participants perspective. 

### **Presenter Point Of View**
1. To start a poll, a presenter must select the option found under the "+" button. 

2. Once the presenter has selected this option, they will see a new entry added in the sidebar, along with the polling options to the right. The polling options include the same choices we see today in the Flash Client. Yes/No, True/False, multiple a/b/c options, as well as the ability to create a custom poll. 

Note: If a user selects any of the options besides the "Custom Poll" it will automatical initiate the poll.

![html5-polling-1](https://user-images.githubusercontent.com/1273169/43969526-6de5bd48-9c98-11e8-85a4-04e5ece4ebb9.png)

3. When a presenter selects the "Custom Poll" option, input fields appear directly below and a button to initiate the poll. 
![html5-polling-1-2](https://user-images.githubusercontent.com/1273169/43969937-c26f259c-9c99-11e8-95a8-bf841bdbfe2c.png)

<hr>

### **Participants Point Of View**
Through various exploration, I boil the experience of responding to a poll to three different directions. Below I have outlined the pros and cons of each of these experiences. 

**1. Modal** 
**Pros:** Adaptable for all screen/device types. 
**Cons:** Participants are unable to see the presentation. This is where possible questions are displayed and or information to help the participants respond.

![html5-polling-response-1](https://user-images.githubusercontent.com/1273169/43970069-44e22f7e-9c9a-11e8-9b15-1bb9eda53539.png)


**2. Corner block** _(bottom right corner)_
**Pros:** It's a not in your face experience, and the participants can keep the presentation slide in view. On mobile devices, we'd have to change this experience to mimic a modal. 
**Cons:** Overlapping elements as the screen size shrinks

![html5-polling-response-2](https://user-images.githubusercontent.com/1273169/43970274-0fa7d72c-9c9b-11e8-9991-ce16d63fad17.png)

3. Leveraging the input panel
Pros: This is a familiar experience for participants, regarding interacting with inputs. 
Cons: Does not adapt well to smaller screen sizes. 

![html5-polling-response-3](https://user-images.githubusercontent.com/1273169/43979529-fbf188b8-9cb8-11e8-805a-738833393199.png)

As always, I'd love to hear feedback from the community on this experience.

**Comment by tylercopeland** [comment]
Here's an example of a corner block experience -> https://evergreen.surge.sh/components/corner-dialog/

**Comment by Tainan404** [comment]
The user interface is different from the one proposed in the @tylercopeland design, in the design a new category is add in the list of users, you add a new option in the action bar.
