### ISSUE TITLE
Starting/engaging in a breakout session 

### ISSUE THREAD

**Issue by tylercopeland** [bigbluebutton/bigbluebutton#4891]

**Comment by tylercopeland** [comment]
Below is the purposed designs for the breakout room experience. 

**1. Initiating the breakout room experience**
To iniate the breakout experience a presenter would click the "+" icon and select "Create breakout rooms". 
![html5-breakoutroom-1](https://user-images.githubusercontent.com/1273169/42760306-08bfde18-88d8-11e8-8050-909c2a70af34.png)

**2. Breakout room settings**
After initiating the breakout room, the breakout room settings will appear in the full-screen modal. This experience will replicate what we see today in the Flash client. A presenter will be able to select the number of rooms, the duration, randomly assign the participants to a room, allow participants to choose a room, and further customize which rooms participants are in by dragging and dropping their name in the desired room.  
![html5-breakoutroom-2](https://user-images.githubusercontent.com/1273169/42761285-12947504-88db-11e8-9a19-aec9f345be25.png)
![html5-breakoutroom-3](https://user-images.githubusercontent.com/1273169/42761524-c79e5118-88db-11e8-93f9-13365cf2b521.png)

**3. Breakout rooms**
Once the breakout rooms have begon, a panel will appear (for the presenter) outlining all the active rooms, how many members are in each room, and the ability to join a room through the full experience or just audio. 

![html5-breakoutroom-4](https://user-images.githubusercontent.com/1273169/42761549-d8903db0-88db-11e8-8ebe-b44bf69e5664.png)

---------------------

**4. Participants joining a breakout room**

Default join modal
![html5-breakoutroom-6](https://user-images.githubusercontent.com/1273169/42763735-e4be7a88-88e1-11e8-9c04-30bce5b45355.png)

The following modal will appear if the presenter selects the option for participants to choose their own room. 
![html5-breakoutroom-5](https://user-images.githubusercontent.com/1273169/42763718-e0cebbae-88e1-11e8-813b-04098abeceec.png)

**Comment by oswaldoacauan** [comment]
Does the "randomly assign" act like a checkbox where you mark it before starting the breakouts or like a action where it just assign them randomly on the client before starting the breakouts? @tylercopeland

**Comment by tylercopeland** [comment]
@oswaldoacauan "randomly assign" acts like a button. After selecting it, participants names will distribute equally across all rooms. From there, the presenter will select "start" to start the breakout room sessions.

**Comment by tylercopeland** [comment]
@oswaldoacauan what are your thoughts? Do you have any further ideas that will improve this experience?

**Comment by tylercopeland** [comment]
The following is a revised mockup of the breakout rooms experience from a presenter point of view. In the latest revision, you'll see an indicator has been added to provide presenters with an understanding of how individual breakout room sessions are going (activity). For example, if there is a straight line (as seen in Room 5), the presenter will know there hasn't been any activity and can take action (provide assistant) by joining that breakout room. cc @ffdixon 

I'd love to hear feedback from the community on this new approach. 

![html5-breakoutroom-4-activity](https://user-images.githubusercontent.com/1273169/44117982-c55b444c-9fe2-11e8-83fe-bc8a891499d6.png)

**Comment by antobinary** [comment]
Implemented in #6108
