### ISSUE TITLE
Create a pointer icon

### ISSUE THREAD

**Issue by tylercopeland** [bigbluebutton/bigbluebutton#4901]
We've received feedback from individuals that it's a little confusing to use the same hand symbol twice with different functionality.

**Comment by tylercopeland** [comment]
@antobinary I've gone ahead and created a new icon for a pointer to limit the confusion of using the same hand icon for the pointer and raise hand experiences. 

In the image below, you'll see it in use. 

<img width="251" alt="screen shot 2018-02-02 at 9 33 08 am" src="https://user-images.githubusercontent.com/1273169/35743960-5207c480-07fc-11e8-8f5e-a6e4d524d506.png">

Here's the icon reference from the bbb icon font

<img width="549" alt="screen shot 2018-02-02 at 9 37 43 am" src="https://user-images.githubusercontent.com/1273169/35744208-fcdf9eaa-07fc-11e8-9237-5126b120b63b.png">

**Comment by OZhurbenko** [comment]
It looks great, thanks!

**Comment by OZhurbenko** [comment]
@antobinary hand is still the tool for pan / zoom
you only needed to swap it with a pointer for non-presenters multi-users, but not for everybody

**Comment by tylercopeland** [comment]
@antobinary I'm closing this issue. The proper pointer icon is being used in the latest version of the html5 client.
