### ISSUE TITLE
Add an active tooltip to the mute button after a user joins using a microphone

### ISSUE THREAD

**Issue by tylercopeland** [bigbluebutton/bigbluebutton#4908]
The goal is to provide emphasis on the mute/unmute button since it's the first thing a user will most likely do when they join a larger sessions using a microphone. 

<img width="945" alt="screen shot 2017-09-19 at 3 11 05 pm" src="https://user-images.githubusercontent.com/1273169/34579207-043b6098-f156-11e7-8f77-2c371dfbfaf3.png">

**Comment by ffdixon** [comment]
Closing as this was an issue related to the Flash client (the project has moved to an HTML5 client).
