### ISSUE TITLE
whiteboard: Increase the width of the box around the name so it that  it displays the entire name

### ISSUE THREAD

**Issue by tylercopeland** [bigbluebutton/bigbluebutton#4910]
<img width="112" alt="screen shot 2017-07-24 at 1 40 02 pm" src="https://user-images.githubusercontent.com/1273169/34579300-65010464-f156-11e7-9e46-43fdd893d6d1.png">

**Comment by GhaziTriki** [comment]
Related to the Flash client (the project has moved to an HTML5 client).

**Comment by ffdixon** [comment]
I think this is still an issue with the HTML5 client, which we're currently showing about 12 characters.  That's probably enough for most cases, but increasing a bit would be good.

Here's a screen shot from the latest build of the HTML5 client

![image](https://user-images.githubusercontent.com/290351/55685545-8c0f8480-5925-11e9-9653-7e5553b70bb2.png)

**Comment by antobinary** [comment]
Works correctly on BBB 2.6.0-rc.3 with tldraw
