### ISSUE TITLE
Optional user feedback on logout

### ISSUE THREAD

**Issue by tylercopeland** [bigbluebutton/bigbluebutton#4912]
When a participant logs out of the session they are presented with the following logout screen. 

![session has ended step 1](https://user-images.githubusercontent.com/1273169/34582765-1addeb1a-f163-11e7-9314-56707243955e.png)

Participants have the option of providing feedback using a star rating system. Furthermore, participants can provide additional feedback using the text area below. 

At any time, a participant can click "Okay" to return to the sessions desired location. 

![session has ended step 2](https://user-images.githubusercontent.com/1273169/34582882-87064c60-f163-11e7-971e-159532544ea7.png)

![session has ended step 3](https://user-images.githubusercontent.com/1273169/34582902-98fed77a-f163-11e7-89de-ea706a5924cc.png)

**Comment by ffdixon** [comment]
The results can be written back to the server using the client logging

  http://docs.bigbluebutton.org/overview/overview.html#client-logging
