### ISSUE TITLE
Client is not aware if bbb-apps-akka or bbb-fsesl-akka stop working

### ISSUE THREAD

**Issue by GhaziTriki** [bigbluebutton/bigbluebutton#4913]
If  `bbb-apps-akka` or  `bbb-fsesl-akka` stops working, the client stays connected to red5 but it is not aware that sent  messages does not arrive to their destination, and of course does not receive messages from them.

**Comment by ffdixon** [comment]
Closing as this was an issue related to the Flash client (the project has moved to an HTML5 client).
