### ISSUE TITLE
Fix settings dropdown's behavior on mobile devices

### ISSUE THREAD

**Issue by OZhurbenko** [bigbluebutton/bigbluebutton#4919]
Tested on the iPad, iOS 11+

Steps to reproduce:
1. Open settings drop down
2. Click anywhere on the screen

Expected result:
Settings drop down is supposed to close.

Current result:
Settings drop down doesn't do anything at all. Although other drop downs (e.g in the user list, status menu) work correctly.

**Comment by antobinary** [comment]
Likely related to #4576

**Comment by OZhurbenko** [comment]
No-no, that's the actual settings modal. I found this drop down buggy:

![settings_dropdown](https://user-images.githubusercontent.com/9299997/34739033-fcdee2ba-f548-11e7-9aee-6d1b672b53d7.JPG)

**Comment by OZhurbenko** [comment]
Can't reproduce this issue anymore, it looks like it fixed itself.
Closing.
