### ISSUE TITLE
Disable tooltips completely for Touch events

### ISSUE THREAD

**Issue by OZhurbenko** [bigbluebutton/bigbluebutton#4920]
If you use a cellphone or a tablet - the tooltips stay visible after the tap.

In some cases it looks really strange:
....
![screenshot_2018-01-08-21-55-58](https://user-images.githubusercontent.com/9299997/34703416-d335fc24-f4c0-11e7-8665-d5d65c802d3f.png)
....

Same happens on larger screens (e.g iPad) when you tap any of the buttons with the tooltips. Tooltips just stay visible.

UPD: After talking to @tylercopeland our requirements here changed, we need to completely disable the tooltips for any touch events.

**Comment by antobinary** [comment]
Re-tested. It's resolved! :+1:
