### ISSUE TITLE
HTML5 Video reconnection: camera does not appear to viewers when video reconnects

### ISSUE THREAD

**Issue by prlanzarin** [bigbluebutton/bigbluebutton#4931]
This happens when there's a reconnection on both the video layer and the HTML5 client (Meteor).
Scenario: a user's internet becomes faulty and it triggers the reconnection procedure. His HTML5 session is still refreshing, but the SFU connection has already been established. The video tries to reconnect, but the API is still unavailable because the HTML5 client is still reconnecting.
What you see: the video reconnects locally, but other conference users won't see the reconnected video.
Expected behaviour: the video reconnection should also be aware of the Meteor reconnection.

**Comment by prlanzarin** [comment]
@lfzawacki I think this is fixed, right?

**Comment by antobinary** [comment]
Resolved
