### ISSUE TITLE
 HTML5 Video: webcam does not appear to viewers ocasionally.

### ISSUE THREAD

**Issue by prlanzarin** [bigbluebutton/bigbluebutton#4933]
It seems to be related to https://github.com/bigbluebutton/bigbluebutton/issues/4931.
We also believe this is a race condition related to the ICE exchange process.

What you see: blank spots in the video dock, as if a webcam was shared, but with no media within it.

![video-fail](https://user-images.githubusercontent.com/4529051/34779807-688f0ea8-f608-11e7-9f97-51ae2f587319.png)

Expected behaviour: the media should be correctly shown. If the process has failed somehow, it should be handled and unshared (or re-shared) as to prevent those ghost webcam tags in the video dock.

**Comment by prlanzarin** [comment]
The situation improved with #4955, mainly on Chrome. The remaining issue is with Firefox 56/57 late joiners where ICE negotiation fails and we're already on this.

**Comment by antobinary** [comment]
This is ready to be closed, right @prlanzarin ?

**Comment by prlanzarin** [comment]
I guess we should wait for an incoming PR from @lfzawacki that fixes the remaining issues @antobinary .

**Comment by antobinary** [comment]
fixed in #5081
