### ISSUE TITLE
Update the HTML5 video dock design

### ISSUE THREAD

**Issue by prlanzarin** [bigbluebutton/bigbluebutton#4934]
The video dock design should be updated to match @tylercopeland 's suggestion depicted in this mockup:

<img width="1279" alt="video-dock-mockup" src="https://user-images.githubusercontent.com/4529051/34780143-73acced2-f609-11e7-980f-cf1711329a15.png">

As I understand this is a temporary design for the 2.0 release and not related to the final webcams design.

**Comment by tylercopeland** [comment]
@prlanzarin we should also add some small adjustments to the position of the video dock for tablet and phone devices. Refer to the following screens for the proper placement. 

**Landscape Tablet** 

![ipad landscape grid](https://user-images.githubusercontent.com/1273169/34781411-c1f3b684-f5f3-11e7-8706-3f4c06023206.png)



**Portrait Tablet & Phone**

![ipad video](https://user-images.githubusercontent.com/1273169/34781429-cd99599e-f5f3-11e7-95d2-0c941e1986c1.png)

**Comment by antobinary** [comment]
Resolved
