### ISSUE TITLE
userID passed with join API all not returned with getMeetingInfo

### ISSUE THREAD

**Issue by arvind4883** [bigbluebutton/bigbluebutton#4952]
Hi,
userID passed with join API all not returned with getMeetingInfo #4660 shows closed.  I updated my dev environment accordingly but I am still able to reproduce this issue.  Please verify it.

**Comment by ffdixon** [comment]
We have not yet released the updates in packaging (coming soon) with the fix.  We'll leave this issue open until the updates are released (we'll also make a post in bigbluebutton-dev when the package updates with this fix are available).

**Comment by ffdixon** [comment]
Fixed in BigBlueButton 2.0-beta.

**Comment by arvind4883** [comment]
Thanks @ffdixon
