### ISSUE TITLE
Actions bar is accessible from dropdown for mobile screen.

### ISSUE THREAD

**Issue by Tainan404** [bigbluebutton/bigbluebutton#4954]
![bug-dropdown](https://user-images.githubusercontent.com/15806883/34886310-c525693a-f7a9-11e7-931f-dd7026082edc.gif)

![deepinscreenshot_select-area_20180112150413](https://user-images.githubusercontent.com/15806883/34886368-ee326652-f7a9-11e7-87bf-86155b2c0ddc.png)

**Comment by antobinary** [comment]
Resolved
