### ISSUE TITLE
Provide a more descriptive experience for allowing your media devices on iOS devices

### ISSUE THREAD

**Issue by tylercopeland** [bigbluebutton/bigbluebutton#4962]
<img width="989" alt="screen shot 2018-01-15 at 10 12 23 am" src="https://user-images.githubusercontent.com/1273169/34949501-421338e2-f9de-11e7-8df7-7d5b051fba0b.png">

**Comment by tylercopeland** [comment]
Also, provide responsive designs. 

<img width="421" alt="screen shot 2018-01-15 at 10 25 23 am" src="https://user-images.githubusercontent.com/1273169/34949575-7832eda0-f9de-11e7-8888-bb21d2ae87dc.png">

**Comment by ffdixon** [comment]
@tylercopeland Still an issue with 2.2-beta?

**Comment by tylercopeland** [comment]
@ffdixon I'm still seeing alignment issues on my mobile phone (iphone XS Max). The audio callout is being cut off. _(Ignore the "You have left the audio conference", trying to time the screenshot wasn't easy)._ 

![IMG_9311](https://user-images.githubusercontent.com/1273169/55991232-bcce2180-5c77-11e9-88ff-4bbee76c506a.PNG)
