### ISSUE TITLE
Kurento Media server: file descriptor leak

### ISSUE THREAD

**Issue by prlanzarin** [bigbluebutton/bigbluebutton#4990]
We found out on a meeting in test.bigbluebutton.org that something was leaking file descriptors somehow, generating `Error: EMFILE: too many open files` exceptions.

We previously thought this was a bbb-webrtc-sfu thing, but that's not the case. This is an exception thrown by Kurento when the number of opens files exceeds the system limit configured for KMS.

The workaround right now is increasing the FD limit for Kurento. Kurento itself opens a LOT of file descriptors per WebRTC and RTP endpoints, and that maybe something we should look to optimize in Kurento in the future.

This caused inconsistent states for both webcams and screenshare, and the screenshare end logic ended up rendering the presentation unusable, and should be handled properly.

**Comment by antobinary** [comment]
Likely related to #5219

**Comment by prlanzarin** [comment]
I have ideas on how to mitigate it application-side (in bbb-webrtc-sfu), but I'm not sure how effective that'll be.

I'll open a PR soon with a batch of SFU optimizations that fixes some stale endpoints left over on Kurento by the SFU component, and later on we should make all the webcams for a webconference go into the same Kurento `MediaPipeline`. My guess is that should lower the number of FDs a bit, but shouldn't solve the issue in definite way.

**Comment by antobinary** [comment]
Addressed in #5333
