### ISSUE TITLE
Improve "Webcams Only For Moderator" feature

### ISSUE THREAD

**Issue by GhaziTriki** [bigbluebutton/bigbluebutton#5001]
- Show webcam icons and button for moderators in the users list but hide them for viewers if `webcamsOnlyForModerator` is enabled.
- Make lock settings window 20% larger.
- Tie `Lock Webcams` & `Webcams Only For Moderator` checkbox states to each other: if one of the is selected, the other one is automatically unselected.
- Update `Webcams Only For Moderator` label to `Hide other viewer's webcams`.
- Add a new help box to lock settings with the following description `These options enable you to restrict certain features available to viewers, such as locking out their ability to use private chat.  (These restrictions do not apply to moderators)`

**Comment by ffdixon** [comment]
Looks good Ghazi!
