### ISSUE TITLE
Buttons not localized in confirmation of end meeting

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#5003]
When the moderator logs out, they can end the meeting as well.  However, the 'Yes' and 'No' buttons the confirmation dialog are not using the localization stringts

![image](https://user-images.githubusercontent.com/290351/35195274-050dcfce-fe8f-11e7-924f-626de1b02fff.png)

**Comment by GhaziTriki** [comment]
Hello,

The Alert `Yes` and `No` strings are available for localisation :

https://github.com/bigbluebutton/bigbluebutton/blob/v2.0.x-release/bigbluebutton-client/locale/en_US/bbbResources.properties#L870

However they have not been translated by the community yet:
https://github.com/bigbluebutton/bigbluebutton/blob/v2.0.x-release/bigbluebutton-client/locale/de_DE/bbbResources.properties

**Comment by ffdixon** [comment]
Marking as fixes as it just depends on localization strings, not code changes.
