### ISSUE TITLE
Desktop Safari given the option to launch the HTML5 client

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#5010]
When accessing from Safari on the desktop, the page gives the option to launch the HTML5 client

![image](https://user-images.githubusercontent.com/290351/35244660-e821c7f2-ff8e-11e7-9934-9b0429e4c02c.png)

We should only see this option when using Safari Mobile.

**Comment by antobinary** [comment]
Addressed in #5106 and #5181
