### ISSUE TITLE
Moderator icon appearing next to non-moderator names in Chat

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#5012]
We are seeing non-moderators getting the moderator icon next to their name in the chat

![image](https://user-images.githubusercontent.com/290351/35250103-ef5aa282-ffa2-11e7-9014-4a10415043f1.png)

Moderators should be bold and with the icon.  Some users are showing as bold with no moderator icon.

**Comment by GhaziTriki** [comment]
Not fully fixed yet.
