### ISSUE TITLE
Update "Clear" text in the status dropdown to be "Clear Status"

### ISSUE THREAD

**Issue by tylercopeland** [bigbluebutton/bigbluebutton#5015]
This is a small request, but in the sidebar menu were using "Clear Status" and in the status drop-down menu, we have "Clear" to clear your status. To make things a little more consistent, my recommendation is to update the copy from "Clear" or "Clear Status" in the status drop-down menu. Refer to the following screenshot.  

![screen shot 2018-01-23 at 1 32 40 pm](https://user-images.githubusercontent.com/1273169/35293869-098293cc-0043-11e8-867c-0a23a2b1a763.png)

**Comment by antobinary** [comment]
Resolved in #5295
