### ISSUE TITLE
Clear error messages

### ISSUE THREAD

**Issue by tylercopeland** [bigbluebutton/bigbluebutton#5016]
@antobinary during our dev call, I decided to test Firefox in parallel with Chrome. This is when I noticed an unclear error message.

I was sharing my webcam in the Chrome browser and I believe that's why I got an error in Firefox. (a webcam can't be shared across multiple browsers). This led me down the path of wondering if it's possible to display a clear error message. For example, "You're unable to share your webcam because it's currently being used on another application."

![screen shot 2018-01-23 at 1 42 37 pm](https://user-images.githubusercontent.com/1273169/35293981-663578be-0043-11e8-893d-917f4d6e3a35.png)

**Comment by antobinary** [comment]
Addressed in #5549
