### ISSUE TITLE
Chat counter stopped updating

### ISSUE THREAD

**Issue by tylercopeland** [bigbluebutton/bigbluebutton#5018]
![screen shot 2018-01-23 at 2 11 21 pm](https://user-images.githubusercontent.com/1273169/35295504-5363b0f8-0047-11e8-9b8d-3cfc3638f193.png)

Here's a link to a video recording of this issue -> https://cl.ly/0Z3S3a1W2Y31

**Comment by antobinary** [comment]
Addressed in  #6790
