### ISSUE TITLE
Joining audio, video or subscribing to any stream should be forbidden when the use is logged out from the conference

### ISSUE THREAD

**Issue by GhaziTriki** [bigbluebutton/bigbluebutton#5020]
### Experienced issue

Due to issue #5019 using Flash Player debug I was disconnected from audio. After seeing the reconnexion window few times then I was ejected from conference. When I was in the user feedback window, I was asked to connect to WebRTC audio, I could not join WebRTC, I was asked to join Flash audio and I successfully joined it.

### Expected behaviour
Subscribing to any stream or creating connection to servers should be forbidden if the user has been logged out.

**Comment by ffdixon** [comment]
Closing as this was an issue related to the Flash client (the project has moved to an HTML5 client).
