### ISSUE TITLE
Add checkbox in Settings for disabling participation in screenshare

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#5029]
The idea is such option will help limit the data usage concerns of mobile users

**Comment by antobinary** [comment]
![screenshot from 2018-01-25 10-36-00](https://user-images.githubusercontent.com/6312397/35396841-ce1f0372-01bb-11e8-890e-8970ee60b410.png)

@tylercopeland Please confirm that the on/off would look like what we now have for 'Audio notifications for chat' and will be located on this very screen

**Comment by tylercopeland** [comment]
@antobinary I agree that's the best approach. 

Attached is the mockup for this updated settings experience. 

![bigbluebutton html settings v2](https://user-images.githubusercontent.com/1273169/35400387-9d3f4a9c-01c4-11e8-9c91-4403bf4b579d.png)

**Comment by tylercopeland** [comment]
@antobinary here's the latest design for the settings panel based on our conversations today. 

![bigbluebutton html settings v2](https://user-images.githubusercontent.com/1273169/35417500-b1541c4c-01fb-11e8-93ce-40afdfc61717.png)

**Comment by antobinary** [comment]
Implemented
