### ISSUE TITLE
Recording Playback Issues In Mobile Browsers BBB2.0

### ISSUE THREAD

**Issue by rahul-chowdhary** [bigbluebutton/bigbluebutton#5030]
Hi, I am using bigbluebutton 2.0.
When the recorded sessions are played back on a mobile browser the presentation and presentation thumbnails are not showing while when played back on the desktop browser they are shown. 

Tested on Following Mobile browsers-
1. Chrome 63.0.3239.111.
2. Firefox 57.0.4

Operating system
Android 6.0.1;

**Comment by GhaziTriki** [comment]
@fcecagno Isn't this issue fixed in #5858?

**Comment by pedrobmarin** [comment]
Even better at https://github.com/bigbluebutton/bbb-playback
