### ISSUE TITLE
Add tooltips to disabled Thickness and Colour whiteboard controls

### ISSUE THREAD

**Issue by tylercopeland** [bigbluebutton/bigbluebutton#5042]
This will provide users with context as to why these items are disabled within the whiteboard controls. 

![screen shot 2018-01-26 at 4 08 56 pm](https://user-images.githubusercontent.com/1273169/35460805-3e68e5a6-02b3-11e8-8fc1-fa490fc69cf5.png)

Also, a small copy recommendation on the whiteboard controls. 
- "Thickness List" update to "Drawing Thickness"
- "Color List" update to "Colors"

**Comment by antobinary** [comment]
Resolved in #5294
