### ISSUE TITLE
Invited to Breakout Room 'G'

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#5046]
Just tested the latest build of BigBlueButton 2.0-beta and the invite dialog for breakout rooms (in Chrome) does not show the room number

![image](https://user-images.githubusercontent.com/290351/35475127-f28d52b6-0366-11e8-8a22-04a78749d308.png)

**Comment by GhaziTriki** [comment]
I could not reproduce it. What conference name did you use?

**Comment by ffdixon** [comment]
Was able to reproduce on a different computer (Windows 10) running Flash 28.0.0.137 in Chrome Version 63.0.3239.132 (Official Build) (64-bit)


![image](https://user-images.githubusercontent.com/290351/35585222-64ec14d6-05c5-11e8-97e0-4a4b7e79afdb.png)
