### ISSUE TITLE
Graphic callout for Chrome position has buttons switched

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#5048]
When prompted for permission on Google Chrome to access your microphone, the graphic shows

![image](https://user-images.githubusercontent.com/290351/35484172-5c0e1000-041a-11e8-8be8-15c239689567.png)

but should be highlighting the left button (not right).

**Comment by kepstin** [comment]
You might need to check this on multiple different operating systems - Mac has traditionally had the primary button on one side, Windows on the other. This change might have been just to make it consistent with the platform.

**Comment by GhaziTriki** [comment]
We have different images for FireFox Win & MacOSX, we need to have the same for Chrome.

**Comment by ffdixon** [comment]
Right, here's what it looks like on Chrome running on Mac OS X

![image](https://user-images.githubusercontent.com/290351/35518843-ab3ae90c-04e0-11e8-95f8-797d27983b4d.png)

**Comment by tylercopeland** [comment]
@ffdixon @GhaziTriki here's the updated graphic for Chrome Microphone Permissions on Windows. 

![bbb-chrome-permissions-windows](https://user-images.githubusercontent.com/1273169/35533872-cf1e12a0-050c-11e8-92cd-55962522e0e4.png)
