### ISSUE TITLE
Inconsistency in webcam share button.

### ISSUE THREAD

**Issue by Tainan404** [bigbluebutton/bigbluebutton#5056]
![button-video](https://user-images.githubusercontent.com/15806883/35510628-071bb3e2-04e0-11e8-98fd-f54d2887a17d.png)
![button-video-off](https://user-images.githubusercontent.com/15806883/35510629-0744a860-04e0-11e8-9115-741b6f26c72f.png)

**Comment by antobinary** [comment]
addressed by @gutobenn on branch `videodock`

**Comment by lfzawacki** [comment]
Just to be clear, what is the consistent behavior? Is it:
 
  * blue button -> normal camera icon
  * red button -> camera with the line crossing through

I think this was implemented in accordance to Tyler's design can we get him to comment on what's the correct way?

**Comment by antobinary** [comment]
>    blue button -> normal camera icon
>    red button -> camera with the line crossing through

This sounds right. I think I spotted the correct version in Augusto's videodock branch

**Comment by antobinary** [comment]
Resolved
