### ISSUE TITLE
Display webcam indicators in the participants list 

### ISSUE THREAD

**Issue by tylercopeland** [bigbluebutton/bigbluebutton#5065]

**Comment by oswaldoacauan** [comment]
There is already a design for that and its implemented. Its something like flash an webcam icon on the right side of the user-item.

**Comment by tylercopeland** [comment]
@oswaldoacauan thanks for pointing this out. I'm going to remove this issue.

**Comment by ffdixon** [comment]
Merged into https://github.com/bigbluebutton/bigbluebutton/issues/5035
