### ISSUE TITLE
Place logos in /var/www/bigbluebutton/client/images

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#5074]
When passing the parameter `logo=<image_name>`, such as `logo=logo.png`, the logo is currently pulled 
from

~~~
  /var/www/bigbluebutton/client/logo.png
~~~

Instead, look for the logo in 

~~~
  /var/www/bigbluebutton/client/images/logo.png
~~~

**Comment by GhaziTriki** [comment]
@ffdixon can be closed.
