### ISSUE TITLE
When a video-dock is unmounted it continues sharing webcam.

### ISSUE THREAD

**Issue by Tainan404** [bigbluebutton/bigbluebutton#5077]
![unmont-dont-stop-share](https://user-images.githubusercontent.com/15806883/35675301-a8da29a2-072e-11e8-810b-2e528785743a.gif)

**Comment by antobinary** [comment]
This might be because we do not call `unshareWebcam()` in https://github.com/bigbluebutton/bigbluebutton/pull/5078
I don't think this is actually an issue. For now I will put `blocked` status until we finalize 5078. That should clarify things

**Comment by antobinary** [comment]
Closing in favour of https://github.com/bigbluebutton/bigbluebutton/issues/5100
