### ISSUE TITLE
Weird char in footer

### ISSUE THREAD

**Issue by ritzalam** [bigbluebutton/bigbluebutton#5082]
<img width="249" alt="weird-footer" src="https://user-images.githubusercontent.com/184672/35697848-6181800c-0759-11e8-8f6c-4653fdf98c22.PNG">

Footer has a weird char in the beginning of footer.

**Comment by kepstin** [comment]
This is an issue with handling unicode character encoding in the `config.xml` file

This is broken:
```xml
<branding logo="logo.swf" copyright="ⓒ 2017 &lt;u&gt;&lt;a href=&quot;https://bigbluebutton.html&quot; target=&quot;_blank&quot;&gt;BigBlueButton Inc.&lt;/a&gt;&lt;/u&gt; (build {0})" background="" toolbarColor="" showQuote="true"/>
```
This works:
```xml
<branding logo="logo.swf" copyright="&#169; 2017 &lt;u&gt;&lt;a href=&quot;https://bigbluebutton.html&quot; target=&quot;_blank&quot;&gt;BigBlueButton Inc.&lt;/a&gt;&lt;/u&gt; (build {0})" background="" toolbarColor="" showQuote="true"/>
```

**Comment by GhaziTriki** [comment]
`config.xml.template` file contains a correctly encoded copyright character since c73739636

@ritzalam Do you see this weird character in your local environment?

**Comment by kepstin** [comment]
@GhaziTriki we're seeing this on some of our production servers because the xml library I was using to edit the config.xml was unescaping the ⓒ character.

Both encodings are correct. Since XML is UTF-8 unless otherwise specified, there is no reason to require this character to be escaped.

**Comment by kepstin** [comment]
The particular characters you see: `Âⓒ` mean that the XML file is being read using the wrong character encoding. It is using Latin1 (or something similar) instead of UTF-8.

```
0xC2 0xA9 → UTF-8 decode → ⓒ
0xC2 0xA9 → Latin1 decode → Âⓒ
```

This problem also means we can't put text from other languages (e.g. arabic, japanese, etc.) into the copyright string unless we escape each character.
