### ISSUE TITLE
Create common messaging library

### ISSUE THREAD

**Issue by ritzalam** [bigbluebutton/bigbluebutton#5084]
Currently, each component implements its own way of receiving and publishing to Redis pubsub. 

Create a common library that is imported by the components so that there is one place to send and receive message from pubsub. Some components use Jedis while others use Redis scala. Unfortunately, Redis scala doesn't have a new version compatible with latest Akka. This means that we can't upgrade akka without replacing redis scala with jedis.

**Comment by pedrobmarin** [comment]
Hi @ritzalam, do you have any more thoughts about this? Did you imagined this as another stand alone common "message broker" component? Could we replace rediscala for scala-redis (https://github.com/debasishg/scala-redis)? I like the idea of having an akka lib that could be aware of all the messaging between the other JVM components and could just provide a simple interface to all of them.
But I also think this may be related to something bigger, maybe some plan to replace Redis? It came to me you are reading more about NATS (is 2018 the BBB-Go year)? How about RabbitMQ? That look really neat too.

**Comment by ritzalam** [comment]
What I'm thinking is a library with 2 interfaces:

void send(IMessage msg);
void addMsgHandler(IMessageHandle handler);

where IMessageHandler has
void handle(IMessage msg);

Then we can different ways of publishing and receiving messages using redis, rabbitmq, natsio. We can start with redis since we have it already.

**Comment by ritzalam** [comment]
Right now we implement pub/sub for the components.

https://github.com/bigbluebutton/bigbluebutton/tree/master/bbb-common-web/src/main/java/org/bigbluebutton/api/messaging

https://github.com/bigbluebutton/bigbluebutton/tree/master/bbb-video/src/main/java/org/bigbluebutton/red5/pubsub

https://github.com/bigbluebutton/bigbluebutton/tree/master/bbb-voice/src/main/java/org/bigbluebutton/voiceconf/messaging

https://github.com/bigbluebutton/bigbluebutton/tree/master/bbb-apps-common/src/main/scala/org/bigbluebutton/client/endpoint/redis

https://github.com/bigbluebutton/bigbluebutton/tree/master/akka-bbb-apps/src/main/scala/org/bigbluebutton/endpoint/redis

https://github.com/bigbluebutton/bigbluebutton/tree/master/akka-bbb-fsesl/src/main/scala/org/bigbluebutton/endpoint/redis

I think it would be better to implement this in a library which makes it easier to support different ways to pub/sub message later.

**Comment by pedrobmarin** [comment]
Oh, ok. I see. It's more like encapsulating only the pub/sub components. Looks like fun

**Comment by ritzalam** [comment]
Are you going to send a PR? :)

**Comment by pedrobmarin** [comment]
Sure! I can give it a try

**Comment by ritzalam** [comment]
Cool! I think just stick with Jedis. The Scala Redis lib we use hasn't been updated. If you sent me a WIP branch, can work with you on it.

**Comment by pedrobmarin** [comment]
How about that other scala lib? Is that the same scala-redis? https://github.com/debasishg/scala-redis

**Comment by ritzalam** [comment]
Haven't tried it. I know Jedis works. You can give it a try.

**Comment by pedrobmarin** [comment]
Ok. I'll have a look. Is this to be built over any specific branch?

**Comment by ritzalam** [comment]
Let's use master branch. Create a project called message-pubsub.

**Comment by pedrobmarin** [comment]
I have no permission to write in BBB projects. Created on my own BBB fork. https://github.com/pedrobmarin/bigbluebutton/projects/1

**Comment by pedrobmarin** [comment]
There is also akka-transcode and bbb-screenshare pubsubs, should we include them too?

**Comment by ritzalam** [comment]
Yes.

**Comment by GhaziTriki** [comment]
@ritzalam Can we consider it was implemented in https://github.com/bigbluebutton/bigbluebutton/pull/6293 ?
