### ISSUE TITLE
how to build flash air-client?

### ISSUE THREAD

**Issue by abba18** [bigbluebutton/bigbluebutton#5087]
Hello everybody.I want to build a mobile app with air-client,but i cant see any doc to build air-client,so i just build the project like [bbb-air-clent](https://github.com/bigbluebutton/bbb-air-client).  Use windows 7 32bit,Flash Builder 4.6,Apache Flex 4.14.1.

I build the project and make some build error,but i solve it .When i debug project,i met some wrong suck as:
> * meeting can not see anything  
> * can not send message
> * other end paint something and air-client are crash  

![pic1](https://user-images.githubusercontent.com/8305752/35724018-48f7e538-0837-11e8-8c25-e9a93f520529.png)  

![pic2](https://user-images.githubusercontent.com/8305752/35724022-4f8cb98c-0837-11e8-8564-b9d65ea3620c.png)  

![pic3](https://user-images.githubusercontent.com/8305752/35724030-561ba786-0837-11e8-8696-5d7f3da3a713.png)  

So i want to know how to build the project,and how to fix problem.
Thanks.

**Comment by capilkey** [comment]
That repo hasn't been updated in 2.5 years and it's not going to work with any recent version of BigBlueButton. There's no BBB AIR client that is ready for production use at the moment. Our hope is that the HTML5 client will be able to fill the mobile need.
