### ISSUE TITLE
misaligned lock settings menu

### ISSUE THREAD

**Issue by Tainan404** [bigbluebutton/bigbluebutton#5128]
![screenshot from 2018-02-09 15-26-27](https://user-images.githubusercontent.com/15806883/36041069-93c28ed4-0dae-11e8-9434-4feead4d3b98.png)

**Comment by GhaziTriki** [comment]
@Tainan404 Can you please re-check this issue. The screenshot is not from the latest build. The latest build should show somthing like this:

![image](https://user-images.githubusercontent.com/4991088/36065850-d3e3c684-0ea0-11e8-8c02-833501533ce5.png)

**Comment by tylercopeland** [comment]
@GhaziTriki I can confirm this is no longer an issue.
