### ISSUE TITLE
Is there a target launch date for HTML5 Client?

### ISSUE THREAD

**Issue by eroy4u** [bigbluebutton/bigbluebutton#5145]
I know you guys are working on it heavily. We're planning to use it for one of our projects. Is there a target launch date? Thanks.

**Comment by ffdixon** [comment]
We release on quality, not dates.  Currently the BigBlueButton HTML5 client is in development phase, and the next milestone is to reach beta (all features are complete, there are no more bugs).  From there, we do a much wider community testing (and fix any bugs found by the community and any we missed during development).

Essentially, you can tell how close we are to a release by where we are in the development process of development -> beta -> release candidate -> release.

For more information, see our [Development Process](http://docs.bigbluebutton.org/support/faq.html#bigbluebutton-development-process).
