### ISSUE TITLE
Ejected/Removed users can still send/receive data

### ISSUE THREAD

**Issue by oswaldoacauan** [bigbluebutton/bigbluebutton#5150]
When a user is ejected or removed the server doesn't cut their connection meaning that they still receive data updates and can send data to the server. You can test it by ejecting a user and on the "You have been removed from the conference" run the following code on the console `
require('/imports/api/chat').default.find().count()` then send a message on the chat and run the code again, the counter will increase.

**Comment by antobinary** [comment]
Resolved
