### ISSUE TITLE
getRecordings returns a status on processing recordings

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#5151]
Some recordings may take time to process.   Extend the BigBlueButton getRecordings API to return status indicators for the recording.

We could extend the <state> indicator to

~~~
  <state>unpublished</state>
~~~

to include other states

   * received
   * processing
 
When in the `received` and `processing` state, there would be no `<playback>` block.

**Comment by jfederico** [comment]
[processing] was already there. Same as [processed] which BTW it is an state that last only for an instant, unless the recording fails in the process.

What [received] would mean?
