### ISSUE TITLE
Webcam settings modal for the HTML5 client

### ISSUE THREAD

**Issue by tylercopeland** [bigbluebutton/bigbluebutton#5154]

**Comment by tylercopeland** [comment]
@antobinary @MaximKhlobystov 

The following is a mockup for the video settings modal. It's based primarily off of the current implementation found in the flash client. 

![html5-video-settings](https://user-images.githubusercontent.com/1273169/37306633-b053da1c-260e-11e8-8471-a04ce752b8a5.png)

While going through the exercise of designing this modal and comparing it against what's currently been implementation, I believe we need to refactor how it is built. The most effective modals found in existing frameworks tend to break it down with a "modal-header", "modal-body" and "modal footer". 

**Modal-Header** 
Can have text, left aligned or centered. Along with an icon on either the right or next hand side. 

**Modal-Body** 
Stores the content for the body

**Modal-Footer**
Can have text, but for the most part, it's the place where the primary actions are stored. 

![html5-modal-breakdown](https://user-images.githubusercontent.com/1273169/37306896-92eb748e-260f-11e8-8dd7-d9d07fc4b8dc.png)

With breaking the modal down in this way, we'll be able to avoid situations where the title is offset (as seen in the initial audio join dialog)
![screen shot 2018-03-12 at 4 11 43 pm](https://user-images.githubusercontent.com/1273169/37307096-2ba7455e-2610-11e8-8374-f17f4322bddf.png)

Lastly, I'm sure it's more of a roadmap item, but at what time do we see ourselves merging the experience of joining the audio and video at the same time? Based on research gathered on existing web conferencing solutions (with the focus of video) this experience is done together at the beginning.

**Comment by antobinary** [comment]
Implemented in #6230
