### ISSUE TITLE
BBB WebRTC Audio Failure

### ISSUE THREAD

**Issue by APUTSA** [bigbluebutton/bigbluebutton#5155]
Hi guys, 
My developers have just finished implementing **BBB 2.0** on my live tutoring website. However, I am getting this error and it seems we don't have a solution as of now: "**Detected the following WebRTC issue: Error 1004: Failure on call (reason=Request Timeout). Do you want to try Flash instead?**" You suggestions and recommendations will be highly appreciated.
@ritzalam @ffdixon @antobinary @GhaziTriki

**Comment by ffdixon** [comment]
Hi Aputsa,

There looks to be an issue with the setup.

Can you post this to our bigbluebutton-setup mailing list along with the output for `sudo bbb-conf --check`.  See https://bigbluebutton.org/support for details on joining the mailing list.  This makes it possible for the BigBlueButton community will help you there.

If we find a bug with BigBlueButton, we'll open an issue here to track it.
