### ISSUE TITLE
HTML5 client not working with greenlight

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#5158]
In the latest build of BigBlueButton 2.0-beta, when the developer build of the HTML5 client is installed, BigBlueButton will correctly redirect a mobile user to launch the HTML5 client when using the built-in API examples.

However, GreenLight is not auto redirecting the mobile user to load the HTML5 client.

**Comment by capilkey** [comment]
The front-end never did the auto-redirecting. The auto redirect is built into BigBlueButton.html. It's done this way to make it always work no matter what front-end you're using.

**Comment by ffdixon** [comment]
Actually, we can close this -- I just tested it on demo and another test server and the HTML5 client loaded automatically when I accessed the site using my iPad.
