### ISSUE TITLE
Client <-> Server Communication

### ISSUE THREAD

**Issue by ritzalam** [bigbluebutton/bigbluebutton#5168]
Prototype transport between client and server using Vertx.

http://vertx.io/docs/vertx-web/scala/#_sockjs

**Comment by oswaldoacauan** [comment]
@ritzalam could you share here the instructions to have the Vertx Server running?

**Comment by ritzalam** [comment]
https://github.com/ritzalam/bigbluebutton/tree/reroute-client-messages/labs/vertx-akka

cd bigbluebutton/labs/vertx-akka
sbt run
