### ISSUE TITLE
Add Tips to loading screen

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#5171]
There are a few common issues that users are encountering.  Change the current "quote" loading screen

![image](https://user-images.githubusercontent.com/290351/36634799-48b53808-1978-11e8-8e96-68b16b77424a.png)

to instead show a random tip to the user

![image](https://user-images.githubusercontent.com/290351/36634808-8070c640-1978-11e8-801e-2241d5f39d00.png)

Notice the '?' to re-enforce the help button.  The link for [show all tips] can be to 

  https://bigbluebutton.org/tips 

where we can list all the tips.  Here is a first cut at the tips

Moderator only

- You need to have Java installed to do desktop sharing
- You can mute all other users to reduce echo
- Breakout rooms are a great way to increase interactivity with users

All users

- If you get logged out due to a network interruption, just click refresh to log back in
- Use FireFox and Chrome as recommended browsers
- Use a headset to avoid causing echo for others when sharing your microphone
- If you are getting logged out on a wireless network, try FireFox (it does a better job of keeping connected on some networks)

**Comment by capilkey** [comment]
Probably don't want to have the word "student" in there as it really narrows the scope of the message. 

I don't know if people will even know that they've been disconnected due to a network interruption. Most people probably don't even know what a network interruption is. Something like "If you get unexpectedly disconnected try refreshing the page to log back in" is simpler.

**Comment by ffdixon** [comment]
> I don't know if people will even know that they've been disconnected due to a network interruption. 

The question is whether we can detect when Chrome fires a network change event + network close event for all connections.  So could we display the message

If you are getting logged out on a wireless network, try FireFox (it does a better job of keeping connected on some networks)

when (a) they are running chrome, (b) network change event fires, (c) need to reconnect all RTMP connections?

**Comment by capilkey** [comment]
The disconnect would happen after the loading screen doesn't exist anymore. I'm not sure where you would show a message like that other than in a pop up.

**Comment by ffdixon** [comment]
For the message

> If you are getting logged out on a wireless network, try FireFox (it does a better job of keeping connected on some networks)

We could show it at the bottom of the reconnecting dialog if (a), (b), and (c) from above are true.

**Comment by tylercopeland** [comment]
@ffdixon having random tips for the user during the loading screen is an interesting approach, but I feel like in some cases, it suggests a negative experience before the user has even entered into the session. Through onboarding, loading and early experiences within BigBlueButton, it should always be a pleasant and positive experience. 

Here are a couple of ideas on incorporating tips into the product. 

1 - A simple approach would be to retool the default presentation to incorporate tips. 

2 - Provide help to users when the time is in need. For example, within the reconnection model (as mentioned above) or when a user gets kicked out of the session. Listing out tips in context would allow the users to take action and rejoin the session quickly. 

I like the idea of including tips on the website, but I think it's best to group tips, how to videos and common questions under one URL. For the most part, web products group everything under help, docs or faqs.

**Comment by ffdixon** [comment]
Closing as this was an issue related to the Flash client (the project has moved to an HTML5 client).
