### ISSUE TITLE
t

### ISSUE THREAD

**Issue by toteote** [bigbluebutton/bigbluebutton#5173]
I have trouble can you help me please

BigBlueButton Server 1.0.0 (1025)
                    Kernel version: 4.4.0-62-generic
                      Distribution: Ubuntu 14.04.5 LTS (64-bit)
                            Memory: 32037 MB

/var/www/bigbluebutton/client/conf/config.xml (bbb-client)
                Port test (tunnel): conference.danteinlinea.com
                              Red5: conference.danteinlinea.com
              useWebrtcIfAvailable: true

/opt/freeswitch/conf/sip_profiles/external.xml (FreeSWITCH)
                    websocket port: 5066
                    WebRTC enabled: true

/etc/nginx/sites-available/bigbluebutton (nginx)
                       server name: conference.danteinlinea.com
                              port: 80
                              port: 443 ssl
                    bbb-client dir: /var/www/bigbluebutton

/var/lib/tomcat7/webapps/bigbluebutton/WEB-INF/classes/bigbluebutton.properties                                                                                                              (bbb-web)
                      bbb-web host: conference.danteinlinea.com

/usr/share/red5/webapps/bigbluebutton/WEB-INF/red5-web.xml (red5)
                  voice conference: FreeSWITCH
                     capture video: true
                   capture desktop: true

/usr/local/bigbluebutton/core/scripts/bigbluebutton.yml (record and playback)
                     playback host: conference.danteinlinea.com

** Potential problems described below **
# The following properties in /var/lib/tomcat7/webapps/bigbluebutton/WEB-INF/cla                                                                                                             sses/bigbluebutton.properties have no value:
#     defaultWelcomeMessageFooter
# Error: Unable to reach default URL for presentation:
#
#    https://conference.danteinlinea.com/default.pdf
#
# Check value for beans.presentationService.defaultUploadedPresentation in
#   /var/lib/tomcat7/webapps/bigbluebutton/WEB-INF/classes/bigbluebutton.propert                                                                                                             ies

**Comment by capilkey** [comment]
It looks like your certificate chain is incomplete and it's probably causing tomcat to not access the presentation, https://www.ssllabs.com/ssltest/analyze.html?d=conference.danteinlinea.com&hideResults=on.

If you install our newer version (2.0-beta) have the option of using an easy to use install script that will install BBB and set up a certificate using Let's Encrypt for you. See here, https://github.com/bigbluebutton/bbb-install.

Also, please post setup related questions to our bbb-setup mailing list instead of GitHub issues please. https://groups.google.com/forum/?fromgroups=#!forum/bigbluebutton-setup

**Comment by toteote** [comment]
I have tried to install the certificates again and it remains the same
Help me please

**Comment by ffdixon** [comment]
Hi there, 

Can you try installing BigBlueButton 2.0-beta on a new user using the install script at

  https://github.com/bigbluebutton/bbb-install

and let us know if that gets you going.  It automates the setup of SSL certificate for you.
