### ISSUE TITLE
WebRTC screensharing: clicking the 'Stop sharing' prompt from the Chrome extension does not fully stop screensharing

### ISSUE THREAD

**Issue by prlanzarin** [bigbluebutton/bigbluebutton#5178]
A handler to listen for the extension's `Stop sharing` procedure should be implemented and added to the `kurento-extension.js` script and used to dispose the screensharing instance, so that the behaviour is the same as clicking in the actions bar `Stop sharing` button.

**Comment by antobinary** [comment]
Resolved
