### ISSUE TITLE
Some webcams do not reconnect successfully on bbb-webrtc-sfu restart

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#5184]
Log in with 2 users with webcams,
One sees: self and Two
Two sees: self and One

stop bbb-webrtc-sfu, wait 10 seconds. The webcams are all gone during these 10 seconds
start bbb-webrtc-sfu. Some webcams are back

One sees: self and Two
*Two sees: self only*

**Comment by GhaziTriki** [comment]
@antobinary Can this isue still be reproduced?

**Comment by pedrobmarin** [comment]
@prlanzarin is this something to keep here?

**Comment by prlanzarin** [comment]
Nah.
