### ISSUE TITLE
Experience and positioning of a portrait document

### ISSUE THREAD

**Issue by tylercopeland** [bigbluebutton/bigbluebutton#5185]

**Comment by tylercopeland** [comment]
@antobinary  here's a first pass on how I envision a presenter interacting with a portrait document in the HTML5 client. 

**Default View (fit-to-width) | Portrait Document**

Based on my experience presenting portrait documents in the Flash client, I found myself always clicking fit-to-width. The default fit-to-page doesn't provide a legible presenting experience, or best uses the given screen real estate. That's where I came to the conclusion of presenting our portrait document fit-to-width by default, and if the presenter would like to see the entire document, they can click fit-to-page

![html5-presentation-portrait-fittowidth](https://user-images.githubusercontent.com/1273169/36853211-dae6d936-1d3b-11e8-8b82-3fdaab83fa05.png)

**Fit-To-Page | Portrait Document**

![html5-presentation-portrait-fittopage](https://user-images.githubusercontent.com/1273169/36864038-8233b156-1d59-11e8-8b74-126105c0e66e.png)

Something to note in the mockup above,  when a portrait document is set to fit-to-page, we're using a black colour to illustrate the presentation area. The width of the presentation controls is always set to the width of the presentation area and not the document. That way we can avoid use cases of presenters uploading narrow documents.

**Comment by ffdixon** [comment]
@tylercopeland Is this still need work after the updates to 2.2-beta for fit-to-width?

**Comment by tylercopeland** [comment]
@ffdixon we ended up going with a different approach, and the toolbar is adaptable based on the width of the presentation that's uploaded. I think for now we can close this issue and being capture feedback from our users on the presentation control experience.
