### ISSUE TITLE
Implement zoom functionality (as presenter)

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#5189]

**Comment by iamdeadman** [comment]
Hi @ffdixon, This is a huge blocker for us too, If this is not already in-progress 
Instead of waiting for it to come I would prefer doing something about it, 
I am not a rockstar dev, but I know my way around if you can show some diretions.

**Comment by ffdixon** [comment]
We do plan in implementing this, but it's a presentation functionality whereas for the first version of the HTML5 client we're focusing on viewer functionality.

If you want to contribute, best to start of fixing some smaller items first.  That will get you familiar with the HTML5 client.  To get started, see  http://docs.bigbluebutton.org/support/faq.html#contributing-to-bigbluebutton

**Comment by antobinary** [comment]
Implemented in #6010
