### ISSUE TITLE
Update the looks of the whiteboard toolbar

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#5192]

**Comment by antobinary** [comment]
![screenshot from 2018-03-01 17-32-32](https://user-images.githubusercontent.com/6312397/36873471-96e2a9b4-1d76-11e8-9df6-809e5afab25a.png)
![screenshot from 2018-03-01 17-31-53](https://user-images.githubusercontent.com/6312397/36873472-96ffa438-1d76-11e8-8af3-e916306bc661.png)

**Comment by pedrobmarin** [comment]
@antobinary are you still planning on doing this?

**Comment by antobinary** [comment]
I just checked with @tylercopeland and we're no longer planning on doing this...
