### ISSUE TITLE
Remove tooltips when a menu is an active/open state

### ISSUE THREAD

**Issue by tylercopeland** [bigbluebutton/bigbluebutton#5194]
@antobinary in the scenarios outlined below, I believe it's best if we remove the tooltips. 

**Actions Menu**

<img width="232" alt="screen shot 2018-03-01 at 7 37 14 pm" src="https://user-images.githubusercontent.com/1273169/36877480-71c87afc-1d88-11e8-99ff-747ac2a511f2.png">

**Settings Menu**

<img width="208" alt="screen shot 2018-03-01 at 7 36 55 pm" src="https://user-images.githubusercontent.com/1273169/36877487-76fb1db8-1d88-11e8-85a2-f88a4444c6fb.png">

**Comment by antobinary** [comment]
Resolved in #5293
