### ISSUE TITLE
WebRTC ERROR on Google Chrome newer versions

### ISSUE THREAD

**Issue by rriscado** [bigbluebutton/bigbluebutton#5203]
I'm running BBB 1.1 and got the message "Could not connect with WebRTC with reason: Could not make a WebSocket Connection. Do you want to try Flash instead?". In Google Chrome browsers with newer versions. This problem does not occur with older versions of Crhome, and does not occur in any version of firefox.

I am using SSL on the server.

I tried to install version 2.0 beta, but the same problem occurred.

**Comment by ffdixon** [comment]
What version of Chrome are you using?   Can you try it with

  https://demo.bigbluebutton.org/

and let us know if you can connect.

**Comment by rriscado** [comment]
Hi ffdixon ,

The Google Chrome version is 63.0.3239.132 - 64 bits.

I've already tested https://demo.bigbluebutton.org/, and it works perfectly.
I followed all the documentation from BBB to SSL.
My BBB is running on an AWS EC2.

**Comment by rriscado** [comment]
Hi,

It is working now. Needed to add the tag <allow="microphone *; camera *"> to my iframe.

Example: <iframe src="https://example.com" allow="microphone *; camera *"></iframe>

You could include this in the BBB documentation.


https://dev.chromium.org/Home/chromium-security/deprecating-permissions-in-cross-origin-iframes
https://groups.google.com/forum/#!topic/bigbluebutton-dev/WfNY3UwBfa8

**Comment by ffdixon** [comment]
Many thanks for sharing this -- I'm sure it will help others.
