### ISSUE TITLE
HTML5 client (viewer) refresh during screenshare causes error on bbb-webrtc-sfu

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#5208]
![screenshot from 2018-03-05 16-21-04](https://user-images.githubusercontent.com/6312397/37000423-60bc03a8-2091-11e8-8acf-72925940302c.png)

**Comment by antobinary** [comment]
https://github.com/bigbluebutton/bigbluebutton/blob/v2.0.x-release/labs/bbb-webrtc-sfu/lib/mcs-core/lib/model/SfuUser.js#L133-L143
I am not sure if this needs addressing - in the logs we see `Unhandled Rejection` while in the code we have this in a try-catch block.
What do you think, @prlanzarin

**Comment by prlanzarin** [comment]
Got it, thanks for the heads up. I'll address this, the rejection is thrown back up to the `mcs-core` client (`screenshare.js` in this case) and it isn't being handling there for some reason, falling back to the catch-all in `ScreenshareProcess.js`. It's harmless right now, but I'll fix it.

**Comment by antobinary** [comment]
Have not seen this in the last 2 months
