### ISSUE TITLE
Capturing feedback through a modal on logout

### ISSUE THREAD

**Issue by tylercopeland** [bigbluebutton/bigbluebutton#5218]
@antobinary this is something we currently have implemented on the Flash client and have received ~1500 entires. 

It's not a priority, but having something similar in the HMTL5 would be amazing. The following is a link to the designs. 

https://invis.io/RDE52214E#/273501005_desktop_-_Session_Has_Ended_Step_1

**Comment by antobinary** [comment]
Implemented in #5404
