### ISSUE TITLE
The whiteboard toolbar is overlapping by the video dock

### ISSUE THREAD

**Issue by Tainan404** [bigbluebutton/bigbluebutton#5223]
![bbbb](https://user-images.githubusercontent.com/15806883/37105542-32a5e618-220e-11e8-88bc-0fce9397d92b.png)

**Comment by antobinary** [comment]
This is caused by the video dock having absolute dimensions. It also fully covers Closed Captions when vertical

**Comment by antobinary** [comment]
Closing in favour of #5215
