### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by wshish000** [bigbluebutton/bigbluebutton#5235]
When I install the bigbluebutton, Nginx doesn't work.
Then I scan the log file,the error appear that:
`2018/03/10 20:33:07 [emerg] 21065#21065: host not found in upstream "192.168.2.236192.168.199.135" in /etc/bigbluebutton/nginx/sip.nginx:2`

Why???

**Comment by ffdixon** [comment]
Which version of BigBlueButton are you installing?  For now, edit `/etc/bigbluebutton/nginx/sip.nginx` so it contains only `92.168.199.135` (not `192.168.2.236192.168.199.135`) and restart BigBlueButton.

**Comment by wshish000** [comment]
@ffdixon 
Version 1.1
I followed the installation instructions and use the cmd "sudo apt-get install bigbluebutton".Then appeared that:
![selection_003](https://user-images.githubusercontent.com/11000848/37248230-5456b700-2507-11e8-92fc-0fb4333129f4.png)
I scan the error.log
![selection_004](https://user-images.githubusercontent.com/11000848/37248232-68d98310-2507-11e8-87e6-08723456a1cb.png)
I cat the /etc/bigbluebutton/nginx/sip.nginx
![selection_005](https://user-images.githubusercontent.com/11000848/37248235-8b469abe-2507-11e8-98d4-debc5541fabd.png)
and the /etc/nginx/sites-available/bigbluebutton
![selection_006](https://user-images.githubusercontent.com/11000848/37248240-b5304960-2507-11e8-873a-4d14fd5ecaf2.png)
Then,
I edit /etc/bigbluebutton/nginx/sip.nginx so it contains only 92.168.199.135 (not 192.168.2.236192.168.199.135) and restart using "sudo bbb-conf --restart", but appears
![selection_007](https://user-images.githubusercontent.com/11000848/37248274-9926c5ae-2508-11e8-803a-7d5e5aac70f3.png)

**Comment by wshish000** [comment]
@ffdixon I solved this problem! the reason is my computer have two network card, when I shut down one of them and fixed some config files, it works!!! thank you !
