### ISSUE TITLE
Add branding area with configurations (disabled by default)

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#5237]
![screenshot from 2018-03-12 15-42-27](https://user-images.githubusercontent.com/6312397/37305828-3127a8ba-260c-11e8-92c9-110f9e6cadbb.png)

In terms of configuration, add the following properties in the json config files:
-'displayBrandingArea': false, 
-'locationOfBrandingImage 'BRANDING_IMAGE',

**Comment by capilkey** [comment]
Why not use the image information that is in config.xml? It's going to need to be more configurable for load balanced environments anyways. The default in config.xml is a SWF, but it could just as easily be a PNG instead. https://github.com/bigbluebutton/bigbluebutton/blob/master/bigbluebutton-client/resources/config.xml.template#L14

**Comment by kepstin** [comment]
Note that in the current BBB system, we actually have the ability to provide a logo as a parameter on the create api. I'm not sure how this is communicated to the client, but it would be nice to have that supported in the html5 client as well.

**Comment by capilkey** [comment]
Good point. I think that information is maybe included with the enter API information. Maybe @ritzalam or @GhaziTriki can chime in.

**Comment by antobinary** [comment]
Let's split this into two:
This github issue will be only for display implementation and it will be picking the resources from .json
Another part will be done when we actually obtain config.xml

**Comment by capilkey** [comment]
There's a "customLogoURL" property in the enter API response. That's the part that @kepstin was referencing. You guys already access the enter API for the auth token.
