### ISSUE TITLE
User reconnecting in FireFox results in logout but the user remains in participants list

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#5240]
Join in HTML5 client with FireFox.
Activate the browser's 'Work offline' mode. Deactivate 'Work offline'.
You will be kicked out of the meeting but your user will remain in the list. The user should not remain in the list if the client session is closing

**Comment by oswaldoacauan** [comment]
Does Firefox actually close the websocket connection when marking 'Work offline'?

**Comment by antobinary** [comment]
Resolved
