### ISSUE TITLE
Remove record notification

### ISSUE THREAD

**Issue by akiwenziec** [bigbluebutton/bigbluebutton#5263]
A significant number of recording recovery requests are a result of users interpreting the recording notification as an initiation of the recording. 

![screenshot from 2018-03-14 13-20-27](https://user-images.githubusercontent.com/18176998/37671996-551882de-2c43-11e8-8c7f-858d44897374.png)

Propose we remove the call out - the start / stop already asks for a confirmation from the user when engaging

**Comment by ffdixon** [comment]
We can remove this in 2.0 to simplify the interface.

**Comment by GhaziTriki** [comment]
This window display can be deactivated by updatin `config.xml` and setting `showRecordingNotification="false"` in `layout` tag.
