### ISSUE TITLE
Integrate Wiris editor into BigBlueButton

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#5277]
Integrate the Wiris equation editor into the BigBlueButton client.

**Comment by serigne7** [comment]
I want the teacher to be able to enter mathematical formulas. For cele, I wanted to integrate wiris in bigbluettion
I wanted help to know how to proceed

**Comment by ffdixon** [comment]
Are you a developer?  The full source code of BigBlueButton is available and we would welcome external help if you wanted to participate.

**Comment by pedrobmarin** [comment]
@ffdixon is Wiris still a thing?

**Comment by ffdixon** [comment]
Closing as we would need to implement an open source equivalent.
