### ISSUE TITLE
Incorporate audio quality bars to determine the quality of a user's network

### ISSUE THREAD

**Issue by tylercopeland** [bigbluebutton/bigbluebutton#5286]
I'll explore designs for this, but some early thoughts are to only display an indicator when the users audio isn't good.

**Comment by tylercopeland** [comment]
I took this issue one step further and built designs around the concept of a global connection status. 

![html5-connectivity-indicator](https://user-images.githubusercontent.com/1273169/38430253-bf541098-398e-11e8-94ba-8616d62ab867.png)

**Sidebar**
In the sidebar, you'll see that "Tyler" has a poor connection and there is an indicator to the right of his name. As a presenter, you'll be able to clearly see who has a poor connection and help take action on solving the problem. Instead of clutering the interface with "great connection" indicators, we're only going to display an indicator if there is a weak connection. If there is no indicator to the right of the name, that means the participant has a good connection. 

**Main Area**
Fixing connection quality is something that the user should take action on right away and I felt that simply having an indicator in the sidebar wasn't enough. This led to adding a second indicator in the presentation area with a clear call to action. Something we're not doing well today is providing our users with in context feedback/help. In the case of the connection indicator, the call to action would point participants to a BBB support section or a specific page on our website outlining steps to improve their connection quality. 

Note: this will also cover the use cases where participants don't have the sidebar open and for mobile devices.

**Comment by ffdixon** [comment]
There are more API calls we can make with Chrome to determine network quality for user, see

   https://googlechrome.github.io/samples/network-information/index.html

Tried this on a train where the internet was intermittent and got the following results

~~~
  // Network type that browser uses
  console.log('         type: ' + navigator.connection.type);
  // Effective bandwidth estimate
  console.log('     downlink: ' + navigator.connection.downlink + 'Mb/s');
  // Effective round-trip time estimate
  console.log('          rtt: ' + navigator.connection.rtt + 'ms');
  // Upper bound on the downlink speed of the first network hop
  console.log('  downlinkMax: ' + navigator.connection.downlinkMax + 'Mb/s');
  // Effective connection type determined using a combination of recently
  // observed rtt and downlink values: ' +
  console.log('effectiveType: ' + navigator.connection.effectiveType);
  // True if the user has requested a reduced data usage mode from the user
  // agent.
  console.log('     saveData: ' + navigator.connection.saveData);
~~~

I got the following results

~~~
          type: unknown
      downlink: 0.75Mb/s
           rtt: 550ms
   downlinkMax: InfinityMb/s
 effectiveType: 3g
      saveData: false
~~~

Anything that shows 3g is not enough.  These APIs look to be only available on Chrome

   http://wicg.github.io/netinfo/

but if the user is running Chrome we should use the to help determine if the user's network is sufficient for BigBlueButton.

**Comment by ffdixon** [comment]
If effectiveType is 3g (or slower), then display the poor network indicator.

**Comment by antobinary** [comment]
Any remaining work will be done as part of https://github.com/bigbluebutton/bigbluebutton/issues/7515

**Comment by shashwatadi** [comment]
Hi, can anybody guide me in enabling this on my bigbluebutton server (version: 2.2.11)

**Comment by junaidHassan84** [comment]
is this feature added ? How to enable it in BBB 2.2
