### ISSUE TITLE
Bug: Username displayed cut out in chat area

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#5287]

**Comment by antobinary** [comment]
Compare the username displayed in the participants list with the one in the chat area. This is an issue for some Arabic characters
![screenshot from 2018-03-27 14-19-13](https://user-images.githubusercontent.com/6312397/37994389-641be824-31df-11e8-924e-f58a43fc3888.png)

**Comment by oswaldoacauan** [comment]
Anyone fixing this needs to remember to test for z̵͕͖̥͙ͅa̻͖̹̟l̸̪͍͙̠g̯͕̠̞̲͟ó̻͍̤̲ͅ ̟̫͞t̠̖e̙̣͚̺x͈̻͢t

**Comment by antobinary** [comment]
Are you serious about Zalgo text? The only non-zalgo issue I've seen was in Arabic.

**Comment by jfsiebel** [comment]
![image](https://user-images.githubusercontent.com/2110278/38623757-d5a55216-3d7c-11e8-86e8-a38c083cb1db.png)
In this case the user name overflow the chat message a little, should we consider Zalgo text @antobinary ?

`H͙̝͝ͅe̯̲͡ ͈̙̭ͅw̙͈̼͈̥̫̦͝h͉̩͓̲o̝̘̭̙͝ ̝͖̥̱ͅW̖̺̳͉͇̣ͅa̛͉̱̫į͇̯̦͚t̫͚̪̖͍͙͈͟s̜̤̗̗̳͝ ͏B̫̠͉ͅé̹͙͇͙h̼̻̝̖͚̮͠ͅi͔̪̟̣̗̦̤n̹̮̪̩d̰͉̤̹̪ͅ ̟̖͟T̝̭͍h̯̤́e̩̠̖̼̤ ͏͖̪͚̹̪W̸̭̣̣̟̝a͙̫͡l͏͍̮̦̤͉̭l̛͍.͍̣͙̗̦ͅ`
