### ISSUE TITLE
html5-dev install error

### ISSUE THREAD

**Issue by kongshine** [bigbluebutton/bigbluebutton#5291]
i install according to this link: 
http://docs.bigbluebutton.org/html/html5-dev.html

have error when Install the npm dependencies with command "meteor npm install"

kong@ubuntu:~/dev/bigbluebutton/bigbluebutton-html5$ sudo su
root@ubuntu:/home/kong/dev/bigbluebutton/bigbluebutton-html5# meteor npm install
npm ERR! code 128
npm ERR! Command failed: /usr/bin/git clone --depth=1 -q -b no-core-util-is-v2.3.3 https://github.com/meteor/readable-stream.git .
npm ERR! fatal: Could not change back to '/root/.npm/_cacache/tmp/git-clone-f5d97d76': Permission denied
npm ERR! 

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-03-29T10_05_56_922Z-debug.log

thanks for help!

**Comment by antobinary** [comment]
Hey @kongshine ,
Is there a reason why you run `meteor npm install` as superuser (`sudo`)?

**Comment by kongshine** [comment]
@antobinary hi,  I have run meteor npm install as ordinary user and it still error and said try as root
 
kong@ubuntu:~/dev/bigbluebutton/bigbluebutton-html5$ meteor npm install
npm ERR! path /home/kong/.npm/_cacache/tmp/git-clone-c08ad293
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall mkdir
npm ERR! Error: EACCES: permission denied, mkdir '/home/kong/.npm/_cacache/tmp/git-clone-c08ad293'
npm ERR!  { Error: EACCES: permission denied, mkdir '/home/kong/.npm/_cacache/tmp/git-clone-c08ad293'
npm ERR!   cause: 
npm ERR!    { Error: EACCES: permission denied, mkdir '/home/kong/.npm/_cacache/tmp/git-clone-c08ad293'
npm ERR!      errno: -13,
npm ERR!      code: 'EACCES',
npm ERR!      syscall: 'mkdir',
npm ERR!      path: '/home/kong/.npm/_cacache/tmp/git-clone-c08ad293' },
npm ERR!   stack: 'Error: EACCES: permission denied, mkdir \'/home/kong/.npm/_cacache/tmp/git-clone-c08ad293\'',
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'mkdir',
npm ERR!   path: '/home/kong/.npm/_cacache/tmp/git-clone-c08ad293' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

and : 
kong@ubuntu:~/dev/bigbluebutton/bigbluebutton-html5$ sudo meteor npm install
[sudo] password for kong: 
npm ERR! code 1
npm ERR! Command failed: /usr/bin/git clone --depth=1 -q -b no-core-util-is-v2.3.3 https://github.com/meteor/readable-stream.git .
npm ERR! /home/kong/.npm/_cacache/tmp/git-clone-7c19f3d6/.git: Permission denied
npm ERR!

**Comment by kongshine** [comment]
problem solve!
$ sudo chmod 777 /home/kong/.npm
$ meteor npm install
error change to:
npm ERR! code ENOTFOUND
npm ERR! errno ENOTFOUND
npm ERR! network request to https://registry.npmjs.org/abbrev/-/abbrev-1.1.1.tgz failed, reason: getaddrinfo ENOTFOUND proxy proxy:8080
npm ERR! network This is a problem related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.

$ npm config set registry https://registry.npm.taobao.org 
and then run `meteor npm install`,  successfully!

**Comment by OZhurbenko** [comment]
It looks like it can be also fixed with this:
https://docs.npmjs.com/getting-started/fixing-npm-permissions
Don't forget that you have 2 `npm`s, one that comes with Meteor ( you can check it by running `meteor npm -v` and another comes with node, you can see its version by just running `npm -v`
You need to fix the `meteor npm` one.

**Comment by kongshine** [comment]
@OZhurbenko hi,i run these 2 comand, it both show 5.6.0, but i run `npm start`  ok, should i still change npm's Default Directory?

**Comment by OZhurbenko** [comment]
It doesn't matter which npm will run the startup script, I'm guessing that `meteor npm start` will work in the same way.

> should i still change npm's Default Directory

Not sure what you mean, is everything working for you now?

**Comment by kongshine** [comment]
@OZhurbenko its ok now
