### ISSUE TITLE
FreeSWITCH restart not handled properly

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#5297]
Join full audio in the Flash client. Restart FreeSWITCH via `sudo systemctl restart freeswitch.service`. Rejoin full audio. Muting the Flash user results in multiple redis messages being dispatched. FS properly displays only one user in the conference.

**Comment by ffdixon** [comment]
@antobinary, is this still an issue if a server is configured to only use the HTML5 client?

**Comment by GhaziTriki** [comment]
@antobinary Any update?
