### ISSUE TITLE
run http://<ip>/html5client/ and get 401 UNAUTHORIZED error

### ISSUE THREAD

**Issue by kongshine** [bigbluebutton/bigbluebutton#5304]
I have installed bigbluebutton 2.0 beta and bbb-html5 client dev environment successfully on my VM. 
And html5client is running at http://ip/html5client/check/ :
{"html5clientStatus":"running"}

But when I try to run the /html5client, it gives a 401  #error.
and one STDERR in the terminal:
W20180403-00:51:38.185(-7)? (STDERR) error: CLIENT LOG: [object Object]
W20180403-00:51:38.185(-7)? (STDERR)  language=zh-CN, userAgent=Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36, width=1920, height=1080, width=1920, height=949, bbbVersion=2.0-rc, location=http://192.168.177.129/html5client/, meetingId=183f0bf3a0982a127bdb8161e0c44eb696b3e75c-1522741527728, requesterUserId=w_nf8gbxy3gls4, requesterToken=36akwgmwurfi, logoutURL=http://192.168.177.129, sessionToken=cechrwpzcztnijhb

thanks
kong

**Comment by antobinary** [comment]
Hey @kongshine 
Install `bbb-demo` package if not installed already. Then navigate to `ip/demo/demoHTML5.jsp` to log in via the html5 client

**Comment by kongshine** [comment]
hi, @antobinary 
i install the bbb-demo, it say its  the newest, 401 still exist. should i start the service bbb-html5 on bigbluebutton 2.0 server?
kong@ubuntu:~/dev/bigbluebutton/bigbluebutton-html5$ sudo apt-get install bbb-demo
Reading package lists... Done
Building dependency tree       
Reading state information... Done
bbb-demo is already the newest version (1:2.0.0-12).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

**Comment by antobinary** [comment]
Hey @kongshine ,
What do you see when you navigate to http://192.168.177.129/demo/demoHTML5.jsp and then enter a username and meeting name and click on Join? This should be the same experience as on http://test.bigbluebutton.org/demo/demoHTML5.jsp if your setup is correct.

**Comment by kongshine** [comment]
hey @antobinary ,
i start the service bbb-html5, then navigate to http://192.168.177.129/demo/demoHTML5.jsp, its correct to view.
kong@ubuntu:~$ service bbb-html5 status
● bbb-html5.service - BigBlueButton HTML5 service
   Loaded: loaded (/usr/lib/systemd/system/bbb-html5.service; enabled; vendor pr
   Active: active (running) since Tue 2018-04-03 09:09:57 PDT; 1min 3s ago
  Process: 30889 ExecStartPre=/bin/sh -c while ! /usr/bin/mongo --eval "db.versi
 Main PID: 30895 (systemd_start.s)
   CGroup: /system.slice/bbb-html5.service
           ├─30895 /bin/bash -e /usr/share/meteor/bundle/systemd_start.sh
           └─30902 node main.js

when i setup html5-dev , it say shut down the bbb-html5 service first. until the `Usage` step, bbb-html5 service without starting, and then i navigate to http://192.168.177.129/demo/demoHTML5.jsp and enter a username and meeting name and click on Join, at last it gives 401 error

**Comment by kongshine** [comment]
@antobinary 
`npm start` output:
kong@ubuntu:~/dev/bigbluebutton/bigbluebutton-html5$ npm start

> bbb-html5-client@ start /home/kong/dev/bigbluebutton/bigbluebutton-html5
> if test "$NODE_ENV" = "production" ; then npm run start:prod; else npm run start:dev; fi


> bbb-html5-client@ start:dev /home/kong/dev/bigbluebutton/bigbluebutton-html5
> ROOT_URL=http://127.0.0.1/html5client NODE_ENV=development meteor --settings private/config/settings-development.json

[[[[[ ~/dev/bigbluebutton/bigbluebutton-html5 ]]]]]

=> Started proxy.                             
=> A patch (Meteor 1.6.1.1) for your current release is available!
   Update this project now with 'meteor update --patch'.
=> Started MongoDB.                           
I20180408-19:59:46.582(-7)? info: REDIS: Subscribed to 'to-html5-redis-channel,from-akka-apps-*'
I20180408-19:59:46.605(-7)? warn: SERVER STARTED. ENV=development, nodejs version=v8.9.3 mobileFont=16, desktopFont=14, audioChatNotification=false, autoJoin=true, listenOnlyMode=true, forceListenOnly=false, skipCheck=false, appName=BigBlueButton HTML5 Client, bbbServerVersion=2.0-rc, copyright=©2018 BigBlueButton Inc., html5ClientBuild=HTML5_CLIENT_VERSION, lockOnJoin=true, basename=/html5client, chatAudioNotifications=false, chatPushNotifications=false, fontSize=16px, locale=en, inputDeviceId=undefined, outputDeviceId=undefined, viewParticipantsWebcams=true, viewScreenshare=true, backgroundColor=#FFFFFF, fontColor=#000000, enabled=false, fontFamily=Calibri, fontSize=16px, takeOwnership=false, muteAll=false, lockAll=false, microphone=false, publicChat=false, privateChat=false, layout=false, allowHTML5Moderator=true, allowModeratorToUnmuteAudio=true, httpsConnection=false, connectionTimeout=60000

.......
I20180408-19:59:46.606(-7)? info: REDIS: SyncGetMeetingInfoRespMsg completed sync
I20180408-19:59:46.606(-7)? info: Upserted meeting id=183f0bf3a0982a127bdb8161e0c44eb696b3e75c-1523235177097
=> Started your app.

=> App running at: http://127.0.0.1/html5client
I20180408-19:59:46.607(-7)? info: REDIS: SyncGetUsersMeetingRespMsg: Error: Match error: Unknown key in field waitingForAcceptance

**when join output:**
I20180408-20:05:09.120(-7)? info: REDIS: CheckAlivePongSysMsg skipped
W20180408-20:05:16.879(-7)? (STDERR)  ~~~~ REDIS RECEIVED: UserRegisteredRespMsg  {"envelope":{"name":"UserRegisteredRespMsg","routing":{"sender":"bbb-apps-akka"}},"core":{"header":{"name":"UserRegisteredRespMsg","meetingId":"183f0bf3a0982a127bdb8161e0c44eb696b3e75c-1523235177097"},"body":{"meetingId":"183f0bf3a0982a127bdb8161e0c44eb696b3e75c-1523235177097","userId":"w_7ndmrn9gufeo","name":"kong","role":"MODERATOR"}}}
I20180408-20:05:16.880(-7)? info: REDIS: {"header":{"name":"UserRegisteredRespMsg","meetingId":"183f0bf3a0982a127bdb8161e0c44eb696b3e75c-1523235177097"},"body":{"meetingId":"183f0bf3a0982a127bdb8161e0c44eb696b3e75c-1523235177097","userId":"w_7ndmrn9gufeo","name":"kong","role":"MODERATOR"}} emitted
I20180408-20:05:16.880(-7)? info: REDIS: UserRegisteredRespMsg completed sync
I20180408-20:05:17.767(-7)? info: User 'w_7ndmrn9gufeo' is trying to validate auth token for meeting '183f0bf3a0982a127bdb8161e0c44eb696b3e75c-1523235177097'
W20180408-20:05:17.768(-7)? (STDERR)  ~~~~ REDIS PUBLISHING:  {"envelope":{"name":"ValidateAuthTokenReqMsg","routing":{"sender":"bbb-apps-akka"}},"core":{"header":{"name":"ValidateAuthTokenReqMsg","meetingId":"183f0bf3a0982a127bdb8161e0c44eb696b3e75c-1523235177097","userId":"w_7ndmrn9gufeo"},"body":{"userId":"w_7ndmrn9gufeo","authToken":"y85j1v7xs0v3"}}}
W20180408-20:05:17.787(-7)? (STDERR)  ~~~~ REDIS RECEIVED: ValidateAuthTokenRespMsg  {"envelope":{"name":"ValidateAuthTokenRespMsg","routing":{"msgType":"DIRECT","meetingId":"183f0bf3a0982a127bdb8161e0c44eb696b3e75c-1523235177097","userId":"w_7ndmrn9gufeo"}},"core":{"header":{"name":"ValidateAuthTokenRespMsg","meetingId":"183f0bf3a0982a127bdb8161e0c44eb696b3e75c-1523235177097","userId":"w_7ndmrn9gufeo"},"body":{"userId":"w_7ndmrn9gufeo","authToken":"y85j1v7xs0v3","valid":true,"waitForApproval":false}}}
I20180408-20:05:17.789(-7)? info: REDIS: {"header":{"name":"ValidateAuthTokenRespMsg","meetingId":"183f0bf3a0982a127bdb8161e0c44eb696b3e75c-1523235177097","userId":"w_7ndmrn9gufeo"},"body":{"userId":"w_7ndmrn9gufeo","authToken":"y85j1v7xs0v3","valid":true,"waitForApproval":false}} emitted
I20180408-20:05:17.804(-7)? info: Created dummy user id=w_7ndmrn9gufeo token=y85j1v7xs0v3 meeting=183f0bf3a0982a127bdb8161e0c44eb696b3e75c-1523235177097
I20180408-20:05:17.810(-7)? info: Updated connectionId user=w_7ndmrn9gufeo connectionId=B6usEKw9T8Hd2eNmd meeting=183f0bf3a0982a127bdb8161e0c44eb696b3e75c-1523235177097
I20180408-20:05:17.824(-7)? info: User= {"_id":"LeWW8c5kNagx9kmWA","meetingId":"183f0bf3a0982a127bdb8161e0c44eb696b3e75c-1523235177097","userId":"w_7ndmrn9gufeo","authToken":"y85j1v7xs0v3","clientType":"HTML5","validated":null,"connectionId":"B6usEKw9T8Hd2eNmd"}
I20180408-20:05:17.826(-7)? info: User='w_7ndmrn9gufeo' is joining meeting='183f0bf3a0982a127bdb8161e0c44eb696b3e75c-1523235177097' authToken='y85j1v7xs0v3' pt1
I20180408-20:05:17.829(-7)? info: User='w_7ndmrn9gufeo' is joining meeting='183f0bf3a0982a127bdb8161e0c44eb696b3e75c-1523235177097' authToken='y85j1v7xs0v3' pt2
W20180408-20:05:17.829(-7)? (STDERR)  ~~~~ REDIS PUBLISHING:  {"envelope":{"name":"UserJoinMeetingReqMsg","routing":{"sender":"bbb-apps-akka"}},"core":{"header":{"name":"UserJoinMeetingReqMsg","meetingId":"183f0bf3a0982a127bdb8161e0c44eb696b3e75c-1523235177097","userId":"w_7ndmrn9gufeo"},"body":{"userId":"w_7ndmrn9gufeo","authToken":"y85j1v7xs0v3"}}}
I20180408-20:05:17.841(-7)? info: REDIS: ValidateAuthTokenRespMsg completed sync
I20180408-20:05:17.848(-7)? info: Removing system messages from: (w_7ndmrn9gufeo)
W20180408-20:05:17.854(-7)? (STDERR)  ~~~~ REDIS RECEIVED: UserJoinedMeetingEvtMsg  {"envelope":{"name":"UserJoinedMeetingEvtMsg","routing":{"msgType":"BROADCAST_TO_MEETING","meetingId":"183f0bf3a0982a127bdb8161e0c44eb696b3e75c-1523235177097","userId":"w_7ndmrn9gufeo"}},"core":{"header":{"name":"UserJoinedMeetingEvtMsg","meetingId":"183f0bf3a0982a127bdb8161e0c44eb696b3e75c-1523235177097","userId":"w_7ndmrn9gufeo"},"body":{"intId":"w_7ndmrn9gufeo","extId":"w_7ndmrn9gufeo","name":"kong","role":"MODERATOR","guest":false,"authed":false,"waitingForAcceptance":false,"emoji":"none","presenter":false,"locked":true,"avatar":"http://192.168.177.129/client/avatar.png"}}}
I20180408-20:05:17.856(-7)? info: REDIS: {"header":{"name":"UserJoinedMeetingEvtMsg","meetingId":"183f0bf3a0982a127bdb8161e0c44eb696b3e75c-1523235177097","userId":"w_7ndmrn9gufeo"},"body":{"intId":"w_7ndmrn9gufeo","extId":"w_7ndmrn9gufeo","name":"kong","role":"MODERATOR","guest":false,"authed":false,"waitingForAcceptance":false,"emoji":"none","presenter":false,"locked":true,"avatar":"http://192.168.177.129/client/avatar.png"}} emitted
I20180408-20:05:17.858(-7)? info: REDIS: UserJoinedMeetingEvtMsg: Error: Match error: Unknown key in field waitingForAcceptance
I20180408-20:05:17.880(-7)?     at exports.check (packages/check.js:55:15)
I20180408-20:05:17.889(-7)?     at addUser (imports/api/users/server/modifiers/addUser.js:24:3)
I20180408-20:05:17.890(-7)?     at EventEmitter.handleUserJoined (imports/api/users/server/handlers/userJoined.js:9:10)
I20180408-20:05:17.890(-7)?     at EventEmitter.emitAsync (/home/kong/dev/bigbluebutton/bigbluebutton-html5/node_modules/eventemitter2/lib/eventemitter2.js:461:31)
I20180408-20:05:17.890(-7)?     at MettingMessageQueue.handleTask (imports/startup/server/redis.js:80:10)
I20180408-20:05:17.890(-7)?     at PowerQueue.runTask (packages/cfs_power-queue.js:596:14)
I20180408-20:05:17.891(-7)?     at PowerQueue.updateThrottleUp (packages/cfs_power-queue.js:402:12)
I20180408-20:05:17.891(-7)?     at PowerQueue.next (packages/cfs_power-queue.js:451:10)
I20180408-20:05:17.891(-7)?     at PowerQueue._autoStartTasks (packages/cfs_power-queue.js:356:14)
I20180408-20:05:17.891(-7)?     at PowerQueue.add (packages/cfs_power-queue.js:381:10)
I20180408-20:05:17.893(-7)? info: REDIS: UserJoinedMeetingEvtMsg completed sync
I20180408-20:05:17.909(-7)? info: Validated auth token as true user=w_7ndmrn9gufeo meeting=183f0bf3a0982a127bdb8161e0c44eb696b3e75c-1523235177097
I20180408-20:05:17.914(-7)? info: Added chat from= to=SYSTEM_MESSAGE time=1523243117883
I20180408-20:05:19.113(-7)? info: REDIS: CheckAlivePongSysMsg skipped
I20180408-20:05:29.118(-7)? info: REDIS: CheckAlivePongSysMsg skipped
I20180408-20:05:39.118(-7)? info: REDIS: CheckAlivePongSysMsg skipped
I20180408-20:05:49.113(-7)? info: REDIS: CheckAlivePongSysMsg skipped
I20180408-20:05:59.119(-7)? info: REDIS: CheckAlivePongSysMsg skipped
I20180408-20:06:09.124(-7)? info: REDIS: CheckAlivePongSysMsg skipped
I20180408-20:06:13.218(-7)? info: REDIS: DoLatencyTracerMsg skipped
W20180408-20:06:18.207(-7)? (STDERR) error: CLIENT LOG: [object Object]
W20180408-20:06:18.207(-7)? (STDERR)  language=zh-CN, userAgent=Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36, width=1920, height=1080, width=1920, height=949, bbbVersion=2.0-rc, location=http://192.168.177.129/html5client/, meetingId=183f0bf3a0982a127bdb8161e0c44eb696b3e75c-1523235177097, requesterUserId=w_7ndmrn9gufeo, requesterToken=y85j1v7xs0v3, logoutURL=http://192.168.177.129, sessionToken=jp1sm9pp5zpkwhoo
I20180408-20:06:18.344(-7)? info: User 'w_7ndmrn9gufeo' is leaving meeting '183f0bf3a0982a127bdb8161e0c44eb696b3e75c-1523235177097'
W20180408-20:06:18.345(-7)? (STDERR)  ~~~~ REDIS PUBLISHING:  {"envelope":{"name":"UserLeaveReqMsg","routing":{"sender":"bbb-apps-akka"}},"core":{"header":{"name":"UserLeaveReqMsg","meetingId":"183f0bf3a0982a127bdb8161e0c44eb696b3e75c-1523235177097","userId":"w_7ndmrn9gufeo"},"body":{"userId":"w_7ndmrn9gufeo","sessionId":"183f0bf3a0982a127bdb8161e0c44eb696b3e75c-1523235177097"}}}

**Comment by antobinary** [comment]
Hey @kongshine 

The issue is here:
```I20180408-20:05:17.856(-7)? info: REDIS: {"header":{"name":"UserJoinedMeetingEvtMsg","meetingId":"183f0bf3a0982a127bdb8161e0c44eb696b3e75c-1523235177097","userId":"w_7ndmrn9gufeo"},"body":{"intId":"w_7ndmrn9gufeo","extId":"w_7ndmrn9gufeo","name":"kong","role":"MODERATOR","guest":false,"authed":false,"waitingForAcceptance":false,"emoji":"none","presenter":false,"locked":true,"avatar":"http://192.168.177.129/client/avatar.png"}} emitted
I20180408-20:05:17.858(-7)? info: REDIS: UserJoinedMeetingEvtMsg: Error: Match error: Unknown key in field waitingForAcceptance
I20180408-20:05:17.880(-7)? at exports.check (packages/check.js:55:15)
I20180408-20:05:17.889(-7)? at addUser (imports/api/users/server/modifiers/addUser.js:24:3)
I20180408-20:05:17.890(-7)? at EventEmitter.handleUserJoined (imports/api/users/server/handlers/userJoined.js:9:10)```

We had an issue like this a few months ago but fixed and pushed the fix. From the messages above it seems that your package is up to date but perhaps the code base for the html5 client has not been pulled lately.

Could you `git pull` the latest code in branch `v2.0.x-release` and then re-run the html5 client in developer mode?
If you still experience the issue, copy-paste what you get in `git log`

**Comment by kongshine** [comment]
@antobinary 
use latest code in branch `v2.0.x-release` and it works in developer mode.
thanks!!!
