### ISSUE TITLE
Remove default active state on dropdown menus

### ISSUE THREAD

**Issue by tylercopeland** [bigbluebutton/bigbluebutton#5313]
**Presenter Controls**
![screen shot 2018-04-04 at 4 00 18 pm](https://user-images.githubusercontent.com/1273169/38331731-03645216-3822-11e8-8de1-bbf940f96058.png)

**Participant Dropdown**
![screen shot 2018-04-04 at 4 00 25 pm](https://user-images.githubusercontent.com/1273169/38331733-055633d2-3822-11e8-99da-4d8a0005290a.png)

**Settings Dropdown**
![screen shot 2018-04-04 at 4 00 32 pm](https://user-images.githubusercontent.com/1273169/38331736-07030b42-3822-11e8-81ce-89dd0b6b6671.png)

By having a list item selected by default suggests to the user that they're currently in that state. My recommendation is that the way a user gets here is by using "tag", "arrow key" or select the item.

**Comment by Tainan404** [comment]
Emoji icon doesn't appear when selected emoji is hovered.
![review-oswaldo-02](https://user-images.githubusercontent.com/15806883/38755507-5cfcc6c0-3f3c-11e8-8f3a-bcf8542a5a54.png)

**Comment by antobinary** [comment]
Resolved in #5351
