### ISSUE TITLE
when changes video quality , it is allowed to share the webcam even with error

### ISSUE THREAD

**Issue by Tainan404** [bigbluebutton/bigbluebutton#5315]
![flash-bug](https://user-images.githubusercontent.com/15806883/38371314-82e696e8-38c2-11e8-9905-74081972ec19.gif)

**Comment by Tainan404** [comment]
It's a broken webcam, your camera does not work (I went to test it). First, it displays the error, and then changing the quality allows it to start sharing the webcam itself without the video.

**Comment by ffdixon** [comment]
Closing as this was an issue related to the Flash client (the project has moved to an HTML5 client).
