### ISSUE TITLE
Setting modal opens when you click to open userlist.

### ISSUE THREAD

**Issue by Tainan404** [bigbluebutton/bigbluebutton#5318]
Steps to reproduce:
1. Open setting modal.
2. Change language for 日本語.
3. Save changes.
4. Click in cancel.
![bug-open-modal](https://user-images.githubusercontent.com/15806883/38426218-747cf06e-398c-11e8-812d-f696e841b855.gif)

**Comment by antobinary** [comment]
Resolved in #5321
