### ISSUE TITLE
How to start recording a session in a demo session in my server

### ISSUE THREAD

**Issue by neutron92** [bigbluebutton/bigbluebutton#5323]
How to start recording a session in a demo session in my server

**Comment by ffdixon** [comment]
These are not issues with BigBlueButton (bugs or improvements), but rather questions on how to setup/use BigBlueButton.  Can you post these to our bigbluebutton-setup mailing list, see https://bigbluebutton.org/support and we'll help you there.

If we find an issue with BigBlueButton that needs fixing, we'll open one here.
