### ISSUE TITLE
Error: there was a timeout in the request

### ISSUE THREAD

**Issue by aghfatehi** [bigbluebutton/bigbluebutton#5325]
when I try to connect with BigBlueButton by HTML5
this Error appear
Error: there was a timeout in the request
If there is a solution, please?
![2018-04-09_17h55_47](https://user-images.githubusercontent.com/31524699/38511563-6fab43e2-3c20-11e8-88c6-6b6e194582ad.png)
![2018-04-09_17h45_07](https://user-images.githubusercontent.com/31524699/38511573-77482ae8-3c20-11e8-9019-fa2202233329.png)

**Comment by ffdixon** [comment]
Hi there, we're just finishing up another set of updates for the HTML5 client.  You'll see a post to bigbluebutton-dev (see https://bigbluebutton.org/support) in a few days.  

After the update, please try the above again and let us know if you still encounter the same error.

**Comment by rogercong** [comment]
After we did a recent update, I am receiving this message, listening mode is fine....

**Comment by ffdixon** [comment]
What steps did you follow to apply the update?

**Comment by ffdixon** [comment]
Follow the steps here to upgrade to the latest build of BigBlueButton 2.0

   http://docs.bigbluebutton.org/install/install.html#upgrading-to-latest-build-of-bigbluebutton-20

and let us know if that gets you going.

**Comment by rogercong** [comment]
ok, it's working now, Thank you Fred.
