### ISSUE TITLE
Moderator user avatar changes in chat when user leaves the meeting

### ISSUE THREAD

**Issue by Tainan404** [bigbluebutton/bigbluebutton#5349]
Steps for reproduce:
- Open two clients HTML5 as moderator.
-  Send a message in public chat and leave the meeting.

![bug-chat-user](https://user-images.githubusercontent.com/15806883/38749359-b3f58724-3f27-11e8-9bdf-3edbb62a9d31.gif)

**Comment by antobinary** [comment]
Resolved in #6761
