### ISSUE TITLE
FreeSWITCH may not be responding to requests on port 8021

### ISSUE THREAD

**Issue by huangdengpan** [bigbluebutton/bigbluebutton#5380]
I am trying to change :: to 127.0.0.1, but it doesn't work.

![image](https://user-images.githubusercontent.com/16663404/39191164-e7fd4018-4808-11e8-8244-32f9e59383d7.png)

**Comment by huangdengpan** [comment]
ufw is disabled

**Comment by huangdengpan** [comment]
Here is my check:
![image](https://user-images.githubusercontent.com/16663404/39191235-184dcb34-4809-11e8-9b67-ff76e1c9f2e9.png)

**Comment by dmi3mis** [comment]
Can you check that?
http://docs.bigbluebutton.org/install/install.html#freeswitch-fails-to-bind-to-port-8021
