### ISSUE TITLE
Change rotation direction of webcam waiting arrows

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#5381]
![screenshot from 2018-04-24 10-29-56](https://user-images.githubusercontent.com/6312397/39193896-83548026-47aa-11e8-98cb-88a6e7b084a9.png)
Right now the arrows rotate clockwise. Please change them to rotate counter-clockwise - the same direction  the arrows are pointing.

**Comment by BobakOftadeh** [comment]
#5406 
Made a pull request that fixes the issue.
