### ISSUE TITLE
Mobile Client for BBB

### ISSUE THREAD

**Issue by havid0707** [bigbluebutton/bigbluebutton#5413]
![image](https://user-images.githubusercontent.com/9440277/39298167-0ca50a52-4978-11e8-86b4-8cd4e7356bf8.png)
HI,
 where can I found the mobile client for BBB? I can't find it at AppStore.
 Is an open source project or not? any information? Thanks

**Comment by ffdixon** [comment]
The mobile client is the HTML5 client for BigBlueButton.  This will run on iPad/iPhone with iOS 11+ (for WebRTC audio) and Android.  

Want to try the latest developer build of the HTML5 client for BigBlueButton.  On your iOS device, use Safari and go to

  https://test.bigbluebutton.org/

You'll be able to login to the latest build of the HTML5 client for BigBlueButton.  You can also login to the same meeting from the Flash client and try joining audio, uploading slides, chatting, starting a pool, drawing on the whiteboard, and sharing an emoji -- basically all the capabilities of a viewer except two-way video.

![image](https://user-images.githubusercontent.com/290351/39304058-5b4bebd2-4926-11e8-9e8f-8164c0481959.png)
 
For more information see: http://docs.bigbluebutton.org/html/html5-overview.html.

**Comment by havid0707** [comment]
Thanks for your reply. I will close this issue.
