### ISSUE TITLE
Enable microphone for moderator only

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#5424]
The use case is the viewers will all either join listen only or dial-in (no microphone button), but the moderator will have full audio controls.

Currently, in the phone module we have

~~~
showButton="true"
~~~

but we could extend it to

~~~
showButton="moderatoronly"
~~~
 
which would mean only the moderator would see the join audio button.

**Comment by kepstin** [comment]
I've responded in the email thread with a possible solution:
https://groups.google.com/d/msg/bigbluebutton-setup/apEB8cKSo-M/u-DH7B-5BAAJ

summary: This can already be done by having a separate config.xml file for participants, and then using the `configToken=` join api parameter to select an alternate configuration to use when the participants join.

**Comment by aogilvie** [comment]
I did give that a go, but the HTML5 client didn't like it.

**Comment by GhaziTriki** [comment]
@ffdixon It can be achieved through lock settings now. Can we close it?

**Comment by aogilvie** [comment]
You can close it if you like but it's not possible. This ticket is to remove all audio capability, to use dial in only. But to do so you need an open audio channel to (listen only is fine) for dial in users to join. To make this into config you need to change quite a few things.
