### ISSUE TITLE
Whiteboard drawing bug

### ISSUE THREAD

**Issue by Tainan404** [bigbluebutton/bigbluebutton#5428]
When you select the edge of the image before drawing and drag to draw it allows you to draw without hold the mouse button.

![whiteboard-bug](https://user-images.githubusercontent.com/15806883/39378925-1f302a0e-4a30-11e8-93fc-71bcef0239c7.gif)

**Comment by antobinary** [comment]
Same result if you right-click ->inspect and then move the mouse around

**Comment by ffdixon** [comment]
@capilkey Can we close this issue?

**Comment by capilkey** [comment]
I can't reproduce anymore. The way the mouse movements are tracked has changed quite a bit since this issue was first opened.
