### ISSUE TITLE
API fails to respond to getRecordings when multiple formats exsits

### ISSUE THREAD

**Issue by jfederico** [bigbluebutton/bigbluebutton#5433]
The response to getRecordings for recordings with multiple formats is not correctly generated.
The XML file containes duplicated recordings instead of grouping the playback formats.

**Comment by fcecagno** [comment]
@pedrobmarin

**Comment by pedrobmarin** [comment]
Hi @jfederico 
I made some changes but I'm not sure if I am missing something. Could you please test it?
https://github.com/bigbluebutton/bigbluebutton/pull/5449

**Comment by ffdixon** [comment]
Merged.
