### ISSUE TITLE
Improve options for WebRTC screen sharing in Flash client

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#5463]
Currently, we are showing

![screen shot 2018-05-04 at 4 59 05 pm](https://user-images.githubusercontent.com/290351/39652716-7ce065d8-4fbc-11e8-9258-3bf1bc32f4fe.png)

Need to improve this choice so it's clearer to the user.

**Comment by tylercopeland** [comment]
@capilkey @ffdixon here's a revised version of the "Choosing screenshare method" modal.

![screen shot 2018-05-10 at 5 46 07 pm](https://user-images.githubusercontent.com/1273169/39897262-89b30ce4-547f-11e8-9f9c-9be636b20448.png)

**Comment by capilkey** [comment]
You can't use the Java logo like this. The license rules are very specific and don't meet our usage. I couldn't find specifics on the WebRTC logo.

**Comment by ffdixon** [comment]
This is now in BigBlueButton 2.0-beta, see http://docs.bigbluebutton.org/2.0/20overview.html#webrtc-screen-sharing.

Here's the latest UI

![image](https://user-images.githubusercontent.com/290351/40380054-e97c89a8-5dc5-11e8-858e-96cb17e257ca.png)
