### ISSUE TITLE
Add a HTML introduction to the client

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#5474]
An increasing number of HTML5 applications will display a series of panels to a new user giving them an introduction to the interface

![walkthrough](https://user-images.githubusercontent.com/290351/39700843-c5d991c6-51cc-11e8-8e91-c6c730af26f4.gif)

Explore using this method to introduce the user to the HTML5 client.

(for now, we'll focus on fixing bugs but wanted to record this as future item)

**Comment by tylercopeland** [comment]
@ffdixon I think this would be a great addition to the HTML5 client. 

There are a few examples of existing solutions out there that we may want to look at using or as inspiration. 

https://github.com/HubSpot/shepherd

http://bootstraptour.com/

**Comment by oswaldoacauan** [comment]
The main issue is to known when is actually a new user, showing them every single time a user join is a no-no.

**Comment by tylercopeland** [comment]
@oswaldoacauan that's a good point. Typically the walkthrough experience is first time users. Do you have any ideas / is it possible to know who's a "new user"? cc/ @ffdixon

**Comment by pedrobmarin** [comment]
We were able to build something really nice using [shepherd](https://shepherdjs.dev/) (mentioned by @tylercopeland). Something like a guided tour.

**Comment by tylercopeland** [comment]
@pedrobmarin I've also seen / used https://react-joyride.com/.

**Comment by pedrobmarin** [comment]
> @pedrobmarin I've also seen / used https://react-joyride.com/.

Looks really nice too!
