### ISSUE TITLE
On Linux the callout for giving audio permission is on the incorrect side

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#5484]
When joining audio on Linux, the user sees the call out inviting them to click the incorrect button (here the screen shot is in German).

![image](https://user-images.githubusercontent.com/290351/39767202-2efa40fa-52b4-11e8-80ea-e50f09dda991.png)

**Comment by GhaziTriki** [comment]
Do we see the same callout for Chrome and FireFox on Linux?

**Comment by kepstin** [comment]
The callout hint for Chrome on Linux also has the buttons reversed.
![screenshot from 2018-05-08 11-42-30](https://user-images.githubusercontent.com/38788/39767545-05eeaf88-52b5-11e8-85af-7e7af460ae36.png)

**Comment by ffdixon** [comment]
@tylercopeland could you create an image for Chrome and FireFox that has the buttons reversed and we'll incorporate it into the client when running under Linux.

**Comment by capilkey** [comment]
We could probably get away with using the MacOS images instead of the Windows images when the client is Linux. https://github.com/bigbluebutton/bigbluebutton/tree/master/bigbluebutton-client/src/org/bigbluebutton/main/views/assets

**Comment by capilkey** [comment]
MacOS Firefox Image
![image](https://github.com/bigbluebutton/bigbluebutton/blob/master/bigbluebutton-client/src/org/bigbluebutton/main/views/assets/firefox-permissions-macosx.png?raw=true)

MacOS Chrome Image
![image](https://github.com/bigbluebutton/bigbluebutton/blob/master/bigbluebutton-client/src/org/bigbluebutton/main/views/assets/chrome-permissions-macosx.png?raw=true)

Those images we already have look like exactly what we need.

**Comment by tylercopeland** [comment]
@capilkey Agreed! cc/ @ffdixon
