### ISSUE TITLE
Update the mute/unmute icon in the user the participant dropdown menu. 

### ISSUE THREAD

**Issue by tylercopeland** [bigbluebutton/bigbluebutton#5493]
While I was conducintnig users testing, it was brought to my attention that the icons we're using for mute/unmute in the participant dropdown menu doesn't match the icon found the main mute/unmute button.

<img width="1392" alt="screen shot 2018-05-08 at 2 39 35 pm" src="https://user-images.githubusercontent.com/1273169/39776075-cc31d982-52cd-11e8-9d22-623b049fff1b.png">

 Let's make sure we're using the right mute/unmute icon in the participant dropdown.

**Comment by antobinary** [comment]
Fixed in #5857
