### ISSUE TITLE
Chat counter isn't disappearing after all chat messages have been read. 

### ISSUE THREAD

**Issue by tylercopeland** [bigbluebutton/bigbluebutton#5494]
<img width="1392" alt="screen shot 2018-05-08 at 2 31 51 pm" src="https://user-images.githubusercontent.com/1273169/39776489-0807e888-52cf-11e8-8b3c-56e0c0dcdf2e.png">

**Comment by MaximKhlobystov** [comment]
Yes, it's going to be one solution for both.
