### ISSUE TITLE
When the whiteboard controls appear over top of the presentation, we lose the border radius. 

### ISSUE THREAD

**Issue by tylercopeland** [bigbluebutton/bigbluebutton#5496]
Whiteboard controls outside the presentation

<img width="189" alt="screen shot 2018-05-08 at 2 58 21 pm" src="https://user-images.githubusercontent.com/1273169/39777040-750af8fc-52d0-11e8-8d8b-45b0aaac552d.png">

Whiteboard controls on the presentation

<img width="80" alt="screen shot 2018-05-08 at 2 59 36 pm" src="https://user-images.githubusercontent.com/1273169/39777047-79044ecc-52d0-11e8-99c8-440b9661b248.png">

**Comment by Tainan404** [comment]
we don't lose the border radius, this is because is over top of a white presentation, draw around the toolbar and you will see the border

![toolbar-border](https://user-images.githubusercontent.com/15806883/39778217-12f409b8-52dc-11e8-9863-8ff82d1133b0.png)

**Comment by Tainan404** [comment]
The same thing happens with presentation controls.

![presentation-control](https://user-images.githubusercontent.com/15806883/39778576-1195928e-52dd-11e8-90dd-c3901a9ef3a4.png)

**Comment by tylercopeland** [comment]
@Tainan404 refer to the images below. You can see there is a transparent white object with no rounded corners. With the Left Arrow example, it visually looks like the button doesn't have rounded corners. 

**Left Arrow**
<img width="64" alt="screen shot 2018-05-08 at 6 05 05 pm" src="https://user-images.githubusercontent.com/1273169/39785486-5cedc4b0-52ea-11e8-914c-412f8297fc28.png">

**Right Arrow**
<img width="161" alt="screen shot 2018-05-08 at 6 03 09 pm" src="https://user-images.githubusercontent.com/1273169/39785421-1b43b9fc-52ea-11e8-9a58-9aa4bcea7cf0.png">

**Whiteboard Control Top**
<img width="188" alt="screen shot 2018-05-08 at 5 57 48 pm" src="https://user-images.githubusercontent.com/1273169/39785513-745eaed4-52ea-11e8-81b2-547c43536c93.png">

**Whiteboard Control Bottom**
<img width="192" alt="screen shot 2018-05-08 at 5 57 42 pm" src="https://user-images.githubusercontent.com/1273169/39785514-746c852c-52ea-11e8-80c3-c7e06a2bfbe0.png">
