### ISSUE TITLE
Architecture without Flash Client

### ISSUE THREAD

**Issue by havid0707** [bigbluebutton/bigbluebutton#5499]
![image](https://user-images.githubusercontent.com/9440277/39800291-d381a614-5399-11e8-9fb7-1a8d9810584d.png)

I don’t care about Flash Client at all, so, apart from the parts I've wiped above, what else aren't used?
Is there a plan to provide a concise installation version without Flash Client.

**Comment by ffdixon** [comment]
We care deeply about the Flash client and will continue to develop and support it in 2018 and 2019.  We are building the HTML5 client in such a way that it works alongside the Flash client and gives our community a smooth transition from Flash to HTML5.

That's important as we want the BigBlueButton community to continue to grow, and so we take care of our current users while opening the product to newer ones (like yourself).

Have you subscribed to our setup mailing list?  See https://bigbluebutton.org/support.  We recommend you subscribe to it at bigbluebutton-setup mailing list as that is were we collaborate on installation/configuration related questions.

This issue tracker in GitHub is more for identifying issues with BigBlueButton and resolving them.  If a question is around "How do I do X", then we usually direct people to start a thread in one of our mailing lists.  

The answer to your question has already been posted and answered here

  https://groups.google.com/d/msg/bigbluebutton-setup/SgkzMgVQ1hE/CJcdAKSoBgAJ
