### ISSUE TITLE
bbb-video should tell akka-apps of start/stop webcam stream

### ISSUE THREAD

**Issue by ritzalam** [bigbluebutton/bigbluebutton#5516]
bbb-video should be responsible of telling akka-apps that a video has started/stopped. Currently, it is the client that notifies akka-apps of cam start/stop. However, if the client is having connection issues (disconnected), the message doesn't get sent to the server. Thus resulting in the user "publishing" multiple cams as the server's list of streams is incorrect.

**Comment by ritzalam** [comment]
Send UserBroadcastCamStartMsg  and UserBroadcastCamStopMsg from bbb-video to akka-apps.

**Comment by ffdixon** [comment]
Fixed in https://github.com/bigbluebutton/bigbluebutton/pull/5523
