### ISSUE TITLE
Specify that a particular webcam should have focus

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#5521]
Some use cases want to have a given webcam stream have default focus.  

Original request

  https://groups.google.com/d/msg/bigbluebutton-dev/k5UC5sGJ6Tg/r9Y9YPo-CAAJ

**Comment by aogilvie** [comment]
Just to add to this; presumably set by the Moderator. Unless you want to go down the whole Google Hangouts route and have auto sizing on audio input and then have forced focus set by the user :/

**Comment by prlanzarin** [comment]
Merging into https://github.com/bigbluebutton/bigbluebutton/issues/7987
