### ISSUE TITLE
Cursor stays with pointer icon when hover disabled button in firefox.

### ISSUE THREAD

**Issue by Tainan404** [bigbluebutton/bigbluebutton#5538]
We should see the :no_entry_sign: on FireFox too when the button is disabled
firefox:
![not-allowed-missing](https://user-images.githubusercontent.com/15806883/40017413-af0f2d98-578f-11e8-8741-14917f393aaf.png)

chrome:
![chrome-sursor](https://user-images.githubusercontent.com/15806883/40017765-a8dff8e8-5790-11e8-9aa8-a799435c3bbd.png)

**Comment by GhaziTriki** [comment]
@antobinary & @Tainan404 Can we please close this?

**Comment by schrd** [comment]
can't reproduce with 2.3
