### ISSUE TITLE
Improve the experience of the swap presentation functionality

### ISSUE THREAD

**Issue by tylercopeland** [bigbluebutton/bigbluebutton#5553]
As much as I enjoy the current implementation, usability tests have shown that this isn’t the best experience. Users are trying to click either the presentation or the webcam to swap. Also, some have said that the red button indicates turning the webcams off versus displaying the swap popup. 

To improve this experience, I'm recommending that we add the functionality where users anticipate it being. 

In the screenshot below, you'll see the new button that has been added directly under the whiteboard controls. This will act as the new swap button. The video button will revert back to turning on and off the webcam. 

![html5-webcam-swap-lg](https://user-images.githubusercontent.com/1273169/40196619-10afb1d4-59df-11e8-9e79-aa45f79eaf00.png)

To bring back the presentation, simply click the small thumbnail of the presentation (bottom right corner).

![html5-webcam-swap-sm-2](https://user-images.githubusercontent.com/1273169/40196787-8ee955aa-59df-11e8-88c9-a3f0b1533e88.png)

**Comment by jvieille** [comment]
A video related control in the context of the whiteboard might not be the right choice.
The "swap" icon has no obvious meaning here: replacing video thumnail by large videos that incidentally makes the presentation disappearing. 
I think the current UI is almost correct appart that the main red video icon is not appropriate (look like it will disconnect the video) and the "swap" feature is unclear

**Comment by fcecagno** [comment]
I believe there's no use case for the presentation after a swap, so we don't need a swap but two different conferencing modes, one with big webcams and no content area, and the other with the content area (which can be presentation or screenshare) and small webcams.

**Comment by antobinary** [comment]
Addressed in #6640
