### ISSUE TITLE
Remove localized string from run_mongo.sh

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#5554]
Currently, we have the logic

   MONGO_OK=`netstat -an | grep LISTEN | grep 127.0.1.1 | grep 27017 &> /dev/null && echo 1 || echo 0`

but it is localized for the word LISTEN.  Change this to

   MONGO_OK=`netstat -lnt | grep 127.0.1.1 | grep 27017 &> /dev/null && echo 1 || echo 0`

**Comment by antobinary** [comment]
Adjusted
