### ISSUE TITLE
Upload of presentation using FireFox 60.0.0 (64-bit) on Windows may not complete

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#5564]
We are seeing a presentation upload issue using the latest build of FireFox 64-bit version 60.0.x 64-bit (or later) on Windows.

This newest version of FireFox seems sends two POST requests to the server when uploading a document (Chrome only sends one).  

The nginx server logs show

12.118.124.24 - - [18/May/2018:21:02:16 -0400] "POST /bigbluebutton/presentation/upload HTTP/1.1" 499 0 "-" "Shockwave Flash"
12.118.124.24 - - [18/May/2018:21:02:17 -0400] "POST /bigbluebutton/presentation/upload HTTP/1.1" 499 0 "-" "Shockwave Flash"
/1.1" 499 0 "-" "Shockwave Flash"

Also, it appears that FireFox is prematurely closing the second connection before the upload finishes, which prevents the upload process in BigBlueButton from proceeding.

![image](https://user-images.githubusercontent.com/290351/40269096-3c0becee-5b47-11e8-9afb-5dcfa2ecad26.png)

We are in progress to file an issue with Mozilla on this.  We're also working on determining if we can work around this issue.  In the meantime, we're going to add detection to the Upload Presentation dialog to detect FireFox 64-bit 60.0.x (or later) on Windows 10.  If detected, BigBlueButton will disable the select and upload button and display the following message

>  This version of FireFox currently has an issue uploading documents (we are working with Mozilla to resolve).  For the moment, please switch to a different browser (we recommend Chrome) to upload your documents.

Finally, we've noticed that if the user uploads a very small presentation, it does sometimes complete.  It looks like it finishes before FireFox prematurely closes the connection.

**Comment by ffdixon** [comment]
We've reported to Mozilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1462979

**Comment by ffdixon** [comment]
We just released an update to BigBlueButton 2.0-beta that disables the Presentation Upload ability if the user is running 64-bit FF 60.0.x (or later) on Windows.

![image](https://user-images.githubusercontent.com/290351/40280025-49f9da94-5c1b-11e8-8840-095ae42ea2e6.png)

This way, they will completely avoid the issue.  The bug looks like a regression in FF60 as the upload worked fine in FF59.

We really like FireFox -- especially with speed increase in the recent additions with the use of Rust.  Mozilla has been very responsive in the past to the bugs that we've reported.

**Comment by ffdixon** [comment]
Looks like Mozilla has identified the issue and working on a fix https://bugzilla.mozilla.org/show_bug.cgi?id=1462979.  Yay!

**Comment by kepstin** [comment]
An update on the ticket status: Mozilla have tested and committed the fix. We're still waiting to hear which releases the fix will be included in.

**Comment by ffdixon** [comment]
The fix is FireFox 62 (currently on nightly).  Hoping to see the fix uplifted to 60.

**Comment by ffdixon** [comment]
They have uplifted this fix to FireFox 61.  We tried the latest beta for 61 and the upload of presentation now works correctly (thanks Mozilla!)

**Comment by ffdixon** [comment]
They have uplifted this fix to FireFox 60.1.0esr and FireFox 61.  Thank you Mozilla!

  https://bugzilla.mozilla.org/show_bug.cgi?id=1462979

Closing this issue.

**Comment by x0rt** [comment]
Hi, 
Firefox 62.0.2 on Windows the presentation upload is not working (not even in demo.bigbluebutton.org). 
Firefox 62.0.1 on Linux is working.

**Comment by german2209** [comment]
I have tested the upload documents with Firefox Quantum 62.0.2 (64-bit) on Windows to my BBB server running build 934 and to demo.bigbluebutton.org build 935 and it worked fine on both servers. I tryed uploading PDF and Word documents and there was no error.
![image](https://user-images.githubusercontent.com/5001239/46158777-d6f46500-c23b-11e8-8460-11dfe509baed.png)

**Comment by ffdixon** [comment]
We just updated demo to BigBlueButton 2.0-RC6 just before @german2209 tried an upload. @x0rt can you try uploading again and let us know if it works.

**Comment by x0rt** [comment]
@ffdixon i just figured out that the problem exist only with the **LTSB** version of windows!
it is **not working** with Firefox 62.0.2 (64-bit) on Windows 10 Enterprise 2016 **LTSB.** 
it is **working** just fine with Firefox 62.0.2 (64-bit) on Windows 10 Pro and any other OS/browser combination i ve tested.

**Comment by ffdixon** [comment]
Thanks for sharing this ... this information will definitely help others who are facing a similar issue.

**Comment by x0rt** [comment]
no problem. thank you for your efforts!
