### ISSUE TITLE
Entering public chat on HTML5 client on phone hides the user icon

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#5568]
With a hidden user icon, there is no way to get back to the main screen.

Steps to reproduce.

1.  Open latest build at https://test.bigbluebutton.org/ on iPhone or Android device
2.  Tap user icon (upper left)
3.  Enter into public chat

The user icon disappears and it's not possible to go back to the main room.  On an Android phone, with full screen enabled, the user icon does stay visible.

**Comment by tylercopeland** [comment]
**Chat Experience**
![img_6218](https://user-images.githubusercontent.com/1273169/40385872-04d853f2-5dd6-11e8-9ed7-77cc89fdadef.PNG)

**User List Experience**
![img_6219](https://user-images.githubusercontent.com/1273169/40385866-0312db6e-5dd6-11e8-9742-ce5e65bf42f8.PNG)

The expected experience (for now, I'm going to open up a new issue that discusses improvements to overall chat experience) is to have the top bar be visible during the chat. Refer to the image below.

![screen shot 2018-05-22 at 3 40 24 pm](https://user-images.githubusercontent.com/1273169/40386096-c07802ce-5dd6-11e8-8321-ba76b1a9e416.png)

**Comment by antobinary** [comment]
Resolved
