### ISSUE TITLE
Include system audio when sharing screen using WebRTC

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#5569]
Investigate whether this is possible with WebRTC screen sharing.  The use case is the instructor wants to share a video with students via screen sharing.

The frame rate won't be as good as giving the students a link to share, as the screen sharing improves, it becomes an option if browser can transmit the system audio instead of the microphone.

**Comment by samuelpeixoto** [comment]
It's a great idea! We need it.
It would be very interesting to share the audio from the system (mixing with the microphone) to the participants during the conference.

**Comment by nickpl456** [comment]
https://www.vb-audio.com/Cable is an option if you need that feature right now, but yes I agree the ability to use system sound would be very helpful.

**Comment by rasos** [comment]
Duplicate of #8632

**Comment by matiasilva** [comment]
@rasos if you look at the issue numbers, #8632 is in fact a duplicate of this one :-). That said, we should merge the two in favor of the new one that has received more activity. Merging with #8632.
