### ISSUE TITLE
Remove default focus state on the public chat input field

### ISSUE THREAD

**Issue by tylercopeland** [bigbluebutton/bigbluebutton#5576]
As a user, I'd like to see the group message before I start to engage in the conversation. Also, if we look at other chat applications, it's best practice to have the user tap the input field to begin writing the message. 

**Current Implementation**

![img_c6ac6eba1c6a-1](https://user-images.githubusercontent.com/1273169/40388775-6728ef82-5dde-11e8-8a71-b520bb9c8e41.jpeg)

**Recommended Experience**
User clicks the public chat item in the user's list, and are brought to the public chat. From there, they can consume the messages in the group. If they would like to engage in the conversation, they can tap the input field.

![screen shot 2018-05-22 at 4 39 22 pm](https://user-images.githubusercontent.com/1273169/40389106-7553095c-5ddf-11e8-9ce3-edacefbcb42d.png)

**Comment by oswaldoacauan** [comment]
@tylercopeland not actually releated to this issue, but having a filled icon for the send button would look a lot better imo
