### ISSUE TITLE
Message counter not updating on mobile

### ISSUE THREAD

**Issue by tylercopeland** [bigbluebutton/bigbluebutton#5578]
When interacting with massive message threads in the public chat, I noticed that the counter wasn't updating even though I scrolled down to read all the messages. 

![screen shot 2018-05-22 at 5 10 19 pm](https://user-images.githubusercontent.com/1273169/40390379-0c76e5ee-5de3-11e8-8b67-4624b1ab6d35.png)

**Comment by capilkey** [comment]
I've seen this on desktop recently also. Seems to be a generic bug.
