### ISSUE TITLE
Confirm that localization is working in the HTML5 client

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#5588]
We need to confirm that HTML5 is properly detecting/setting the localization based on the information from the browser.

See discussion which suggests there are two bugs

  https://groups.google.com/d/msg/bigbluebutton-dev/vCZAYImhdQY/fvsKyi8TAQAJ

**Comment by KDSBrowne** [comment]
I can confirm that the browser's locale is detected in 
`bigbluebutton-html5/imports/startup/server/index.js`

WebApp.connectHandlers.use('/locale', (req, res) => {
      const APP_CONFIG = Meteor.settings.public.app;
      const defaultLocale = APP_CONFIG.defaultSettings.application.locale;
      const localeRegion = req.query.locale.split(/[-_]/g);

from my tests, the dectection of the browsers locale which is stored in `localeRegion ` works as expected.

**Comment by aogilvie** [comment]
@KDSBrowne If this code is accurate then the Japanese file should be duplicated from ja_JP.json to ja.json

The difference is between a native OS browser, and a custom set browser I think.

Reproduction Steps:
Using an English installed windows/linux. If you set your browser to Japanese (I'm using Chrome for this example) :

```
  // Assuming the below line returns similar to navigator.language for Japanese you get: ["ja"]
  const localeRegion = req.query.locale.split(/[-_]/g);
  const localeList = [defaultLocale, localeRegion[0]];

  let normalizedLocale = localeRegion[0];
  let messages = {};

  // no, length is 1, ignored
  if (localeRegion.length > 1) {
    normalizedLocale = `${localeRegion[0]}_${localeRegion[1].toUpperCase()}`;
    localeList.push(normalizedLocale);
  }

  localeList.forEach((locale) => {
    try {
     // locale is "ja", ja.json does not exist
      const data = Assets.getText(`locales/${locale}.json`);
      messages = Object.assign(messages, JSON.parse(data));
      normalizedLocale = locale;
    } catch (e) {
      // Getting here means the locale is not available on the files.
    }
  });


```
in Edge which is a naively installed MS Windows; (ja_JP)

![capture](https://user-images.githubusercontent.com/970364/40594244-fa4fe976-6268-11e8-888c-3345d6a6bffc.PNG)

**Comment by KDSBrowne** [comment]
Futher explanation on how the locales work in the html5 client can be found here https://github.com/bigbluebutton/bigbluebutton/issues/6757

**Comment by ffdixon** [comment]
@KDSBrowne Just wondering if this is still an issue?

**Comment by KDSBrowne** [comment]
@ffdixon this isn't an issue any more
