### ISSUE TITLE
problem with HTML5 behind nat

### ISSUE THREAD

**Issue by danionescu2007** [bigbluebutton/bigbluebutton#5589]
Audio bridge working, video not.
![image](https://user-images.githubusercontent.com/4688610/40576261-7ece3b7c-60fb-11e8-88df-af6844610157.png)

There is no specification to open 8888 for kurento in NAT. There is not for UDP range also.
I have the following config for kurento:
```
# cat /etc/kurento/modules/kurento/WebRtcEndpoint.conf.ini

; Only IP address are supported, not domain names for addresses
; You have to find a valid stun server. You can check if it works
; usin this tool:
;   http://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/
stunServerAddress=77.72.169.210
stunServerPort=3478

; turnURL gives the necessary info to configure TURN for WebRTC.
;    'address' must be an IP (not a domain).
;    'transport' is optional (UDP by default).
; turnURL=user:password@address:port(?transport=[udp|tcp|tls])

;pemCertificate is deprecated. Please use pemCertificateRSA instead
;pemCertificate=<path>
;pemCertificateRSA=<path>
;pemCertificateECDSA=<path>
```

```
# cat /usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml

kurentoUrl: ws://streamhub.24-7.ro:8888/kurento
kurentoIp: 172.16.1.235
localIpAddress: 172.16.1.235
acceptSelfSignedCertificate: true
redisHost : "127.0.0.1"
redisPort : "6379"
clientPort : "3008"
minVideoPort: 30000
maxVideoPort: 33000
mediaFlowTimeoutDuration: 5000
from-screenshare: "from-screenshare-sfu"
to-screenshare: "to-screenshare-sfu"
from-video: "from-video-sfu"
to-video: "to-video-sfu"
from-audio: "from-audio-sfu"
to-audio: "to-audio-sfu"
to-akka: "to-akka-apps-redis-channel"
webcam-force-h264: true
screenshare-force-h264: true
screenshareKeyframeInterval: 2

recordScreenSharing: true
recordWebcams: true
recordingBasePath: "file:///var/kurento"

redisExpireTime: 1209600 # 14 days as per the akka keys

log:
    filename: '/var/log/bbb-webrtc-sfu/bbb-webrtc-sfu.log'
    level: 'verbose'
```

```
# bbb-conf --restart
# IP does not match:
#                           IP from ifconfig: 172.16.1.235
#   /etc/nginx/sites-available/bigbluebutton: streamhub.24-7.ro
# Warning: API URL IPs do not match host:
#
#                                IP from ifconfig: 172.16.1.235
#  /var/lib/tomcat7/webapps/demo/bbb_api_conf.jsp: streamhub.24-7.ro

Restarting BigBlueButton 2.0.0-beta ...
Stopping BigBlueButton
Starting BigBlueButton



** Potential problems described below **
# IP does not match:
#                           IP from ifconfig: 172.16.1.235
#   /etc/nginx/sites-available/bigbluebutton: streamhub.24-7.ro
# Warning: API URL IPs do not match host:
#
#                                IP from ifconfig: 172.16.1.235
#  /var/lib/tomcat7/webapps/demo/bbb_api_conf.jsp: streamhub.24-7.ro

.......
# Warning: The setting of 89.120.216.4 for proxy_pass in
#
#    /etc/bigbluebutton/nginx/sip.nginx
#
# does not match the local IP address (172.16.1.235).
# (This is OK if you've manually changed the values)

# Warning: The API demos are installed and accessible from:
#
#    https://streamhub.24-7.ro/demo/demo1.jsp
#
# These API demos allow anyone to access your server without authentication
# to create/manage meetings and recordings. They are for testing purposes only.
# If you are running a production system, remove them by running:
#
#    sudo apt-get purge bbb-demo

# Warning: The client self check is installed and accessible from:
#
#    https://streamhub.24-7.ro/check
```

I will provide any log or information if needed, please help. I spent over 15 hours trying to figure this out. The NAT won :(

**Comment by ffdixon** [comment]
Currently, Kurento will pick a UDP port in the range 16384 - 65536 range.  We have an open issue to restrict that range to 24,481 - 32,768, see https://github.com/bigbluebutton/bigbluebutton/issues/5156.

Can you try sharing a webcam with https://test.bigbluebutton.org/ the HTML5 client.  Does it work?

To get more information on why it's failing, in FireFox, after you get the error, open a new tab and enter about:webrtc in the URL. FireFox will give you information on what IP address/ports the client and server were negotiating.   You can see if any of the connections succeeded (and thus succeeded in getting through NAT).

Try the above and let us know what you find.

**Comment by ffdixon** [comment]
Closing as not heard back from the user in many months.  If anyone reading this thread encounters a similar problem, please test first with

  https://demo.bigbluebutton.org/

and if you encounter an issue, let us know

  https://bigbluebutton.org/support

**Comment by SIzvekov** [comment]
Hello Fred,
I tried with demo https://demo.bigbluebutton.org/ and at first try I got same error "1007: ICE negotiation failed" in Safari but worked OK in Chrome. Second try worked OK in Safari as well.
But in my instance I am always getting "1007: ICE negotiation failed" in all browsers when try to connect. 
When I do ```bbb-conf --restart``` I am getting this message ```Warning: API URL IPs do not match host``` Could you help me to troubleshoot that?

**Comment by ffdixon** [comment]
Are you behind a firewall yourself?  We have a TURN server setup on demo.bigbluebutton.org, which is probably enabling your client to get a RTP connection (no 1007 error).

See

   http://docs.bigbluebutton.org/2.2/setup-turn-server.html

**Comment by capilkey** [comment]
The documentation needs to be updated for the TURN server to work with Safari. The documentation lists a TURN URL with a "turns" protocol, but Safari needs a second TURN block with a URL that has a "turn" protocol.
