### ISSUE TITLE
[iOS] [Mobile Client] Cannot hide left user/message panel after using public chat  

### ISSUE THREAD

**Issue by aogilvie** [bigbluebutton/bigbluebutton#5590]
iOS 11.2.2
Safari browser
iPhone 6

## Steps

- Start a session
- Tap the top left user icon (next to room name) to show the current session users and chats (1)
- Tap the Public chat
- Type something like "test" tap return or keyboard "Done"
- Tap the top button "< Public Chat" (2)
- You will now be back to the session users and chats pane, but you will not see the top most toolbar to exit the pane. (3)

(1)
![1](https://user-images.githubusercontent.com/970364/40595457-8434af2c-626f-11e8-85f2-bb8edcc33c83.jpg)

(2)
![2](https://user-images.githubusercontent.com/970364/40595467-8ff440de-626f-11e8-88e9-9bf1498728e4.jpg)

(3)
![3](https://user-images.githubusercontent.com/970364/40595469-93acb38c-626f-11e8-9beb-0ee501d37066.jpg)

**Comment by ffdixon** [comment]
Thanks for reporting this, merging this into https://github.com/bigbluebutton/bigbluebutton/issues/5568.

**Comment by aogilvie** [comment]
Great! (I had a quick scout in the issues but didn't see that, thanks 🙏)
