### ISSUE TITLE
Create a simple API interface to trigger start/stop of recording in HTML5

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#5598]
We want to create a demo of embedding the HTML5 client in a `<div />` tag and showing how Javascript running in the tag can trigger actions in the HTML5 client.

This would be similar to [JavaScript Demo](https://demo.bigbluebutton.org/demo/demo11.jsp) for the Flash client.

For the first step, create a web page that embeds the HTML5 client in  `<div />` tag and has a button for starting/stopping recording.

![image](https://user-images.githubusercontent.com/290351/40665017-3196910c-632a-11e8-8f7e-1c385b688c51.png)

**Comment by antobinary** [comment]
http://docs.bigbluebutton.org/html/html5-dev.html#demo-html5-api-via-iframe
