### ISSUE TITLE
red5 is occasionally writing video frames out sequence

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#5603]
We've are seeing examples where the latest version of red5 in BigBlueButton 2.0-beta is writing video frames in incorrect time sequence.

**Comment by ritzalam** [comment]
Red5 was using 2 threads to take packets from the incoming queue and writing them into the flv file. So one thread might be writing a newer packet first while the other writes the older packet later.

**Comment by ritzalam** [comment]
After fixing the order of packets using timestamp into the file, need to remux the flv file during record processing to fix the offset of the timestamp as it is causing seek issues.

https://github.com/bigbluebutton/bigbluebutton/pull/5608

**Comment by ffdixon** [comment]
We've just pushed a package update out to the BigBlueButton repository that should fix this error. If anyone has hit this issue and wants to test the fix, update their BigBlueButton 2.0-beta server to get the latest packages.

http://docs.bigbluebutton.org/2.0/20install.html#upgrade-to-latest-build-of-bigbluebutton-20

**Comment by ffdixon** [comment]
Fixed in latest build of BigBlueButton 2.0-beta
