### ISSUE TITLE
when i create a room using API Create without duration or with duration option ti works for 15 min and it shws me meeting room id doesnot exist

### ISSUE THREAD

**Issue by neutron92** [bigbluebutton/bigbluebutton#5606]
when i create a room using API Create without duration or with duration option ti works for 15 min and it shws me meeting room id doesnot exist

**Comment by neutron92** [comment]
how can i change the 5 min because i need unlimited rooms

**Comment by ffdixon** [comment]
You shouldn't create rooms that are going to be empty long periods of time; rather, just create the room as the first person joins.   Use the technique of making two API calls (`create` and then return a join URL) as covered above.

**Comment by neutron92** [comment]
yes i got you but also i  want to create a long time link to use for my pro meetings

**Comment by jibon57** [comment]
@neutron92 Instated of creating joining URL it will be best to use unique ID for each room. You can share the link which may be generated by PHP or any other language with unique ID. Later when your user will join to the room that time you can call API to generate joining link. This way you can create link for unlimited time.

**Comment by neutron92** [comment]
@jibon57  can you give me more details because after 5 min like @ffdixon i see and error that told me no meeting with this ID

**Comment by ffdixon** [comment]
To put it another way, you should create the room in your front-end and not create the actual room in BigBlueButton until the user is joining (through your front-end).

In other words, the join URL for users is a URL to your front-end that, later when they click, is validated by your front-end and, if valid, allows the user into the room.

Once allowed, your front-end would call `create` to create the room (just in time creation), and then redirect the user to the room with a join URL.

**Comment by neutron92** [comment]
@ffdixon i'm doing like that and i'm creating the room by `create` then generating the URL by `server.administration.join`  when user click in the button by the problem if there is 5min between the creation and the join

**Comment by ffdixon** [comment]
It sounds like you are creating the room in BigBlueButton when a user creates the room in your front end, and then noticing that if the user does not join within 5 minutes, BigBlueButton has erased the room.

It's helpful to think of BigBlueButton like a web server -- it doesn't hold state (other than active rooms).  You don't tell a web server "I'm going to download a file tomorrow at 2:00 PM"; rather, you just request the file when you need it.

In a similar manner, you don't tell BigBlueButton "I'm going to create a room for tomorrow at 2:00 PM"; rather, you just create the room when a user clicks a 'join' button on your front end. 

There is no meeting database in BigBlueButton, no calendar, and no user database.  These functions are all handled by the front-end.
