### ISSUE TITLE
Webcam isn't be recorded until 30-60s into the recording

### ISSUE THREAD

**Issue by jspicard** [bigbluebutton/bigbluebutton#5607]
<b>Reproducible</b>: Yes

<b>Steps</b>:
1. Create a presentation via bigbluebuttonbn plugin in moodle.
2. Join presentation (w/ microphone)
3. Start webcam
4. Import a presentation (we used 15+ slides)
5. Record for more than 5 minutes (less than 5 minutes didn't seem to have the issue)
6. End recording and log out of room and let video process.
7. Playback video and see that 30-60s of video is frozen starting at the beginning.

<b>Issue</b>: The webcam appears frozen for the first 30-60s of a recording. The webcam is stuck at the first frame that the webcam would start from when the system recognizes that a webcam is available. Audio, whiteboard, and chat work as intended with no delay in start-time. It looks as though the webcam isn't being recognized as an option and about 30s into the stream there is a "ParticipantStatuschangeEvent" that modifies the status of the user to add "hasStream" at which point the webcam recording starts. events.xml show the following:
&lt;event timestamp="431706722" module="PARTICIPANT" eventname="AssignPresenterEvent"&gt;
    &lt;assignedBy&gt;w_fmh6l6ni7lll&lt;/assignedBy&gt;
    &lt;userid&gt;w_fmh6l6ni7lll&lt;/userid&gt;
    &lt;name&gt;Patrick&lt;/name&gt;
  &lt;/event&gt;
 &lt;event timestamp="431706722" module="PARTICIPANT" eventname="ParticipantJoinEvent"&gt;
    &lt;userId&gt;w_fmh6l6ni7lll&lt;/userId&gt;
    &lt;externalUserId&gt;10440&lt;/externalUserId&gt;
    &lt;role&gt;MODERATOR&lt;/role&gt;
    &lt;name&gt;Patrick&lt;/name&gt;
  &lt;/event&gt;
&lt;event timestamp="431709111" module="PRESENTATION" eventname="ConversionCompletedEvent"&gt;
    &lt;presentationName&gt;XXXXX&lt;/presentationName&gt;
    &lt;originalFilename&gt;default.pdf&lt;/originalFilename&gt;
  &lt;/event&gt;
  &lt;event timestamp="431709111" module="PRESENTATION" eventname="SharePresentationEvent"&gt;
    &lt;share&gt;true&lt;/share&gt;
    &lt;presentationName&gt;XXXXX&lt;/presentationName&gt;
  &lt;/event&gt;
&lt;event timestamp="431730344" module="VOICE" eventname="ParticipantJoinedEvent"&gt;
    &lt;muted&gt;false&lt;/muted&gt;
    &lt;callernumber&gt;w_fmh6l6ni7lll-bbbID-Patrick&lt;/callernumber&gt;
    &lt;talking&gt;false&lt;/talking&gt;
    &lt;callername&gt;Patrick&lt;/callername&gt;
    &lt;bridge&gt;74992&lt;/bridge&gt;
    &lt;participant&gt;w_fmh6l6ni7lll&lt;/participant&gt;
  &lt;/event&gt;
  &lt;event timestamp="431730369" module="VOICE" eventname="StartRecordingEvent"&gt;
    &lt;bridge&gt;74992&lt;/bridge&gt;
    &lt;recordingTimestamp&gt;431730368&lt;/recordingTimestamp&gt;
    &lt;filename&gt;/var/freeswitch/meetings/XXXXX.wav&lt;/filename&gt;
  &lt;/event&gt;
  &lt;event timestamp="431730410" module="VOICE" eventname="ParticipantTalkingEvent"&gt;
    &lt;talking&gt;true&lt;/talking&gt;
    &lt;bridge&gt;74992&lt;/bridge&gt;
    &lt;participant&gt;w_fmh6l6ni7lll&lt;/participant&gt;
  &lt;/event&gt;
... (A BUNCH OF WHITEBOARD EVENTS) ...
 &lt;event timestamp="431746083" module="PARTICIPANT" eventname="ParticipantStatusChangeEvent"&gt;
    &lt;value&gt;true,stream=wide-w_fmh6l6ni7lll-1527689725565-recorded&lt;/value&gt;
    &lt;userId&gt;w_fmh6l6ni7lll&lt;/userId&gt;
    &lt;status&gt;hasStream&lt;/status&gt;
  &lt;/event&gt;
  &lt;event timestamp="431746427" module="WEBCAM" eventname="StartWebcamShareEvent"&gt;
    &lt;stream&gt;wide-w_fmh6l6ni7lll-1527689725565-recorded&lt;/stream&gt;
  &lt;/event&gt;

![image](https://user-images.githubusercontent.com/39769775/40728087-565726b4-63f7-11e8-970e-52ac2e897c86.png)

We upgrade BBB through the public repo hosted through bigbluebutton.org. The issue started happening after we updated on 5/18/18 to versions listed below (excerpt from apt/history.log).

<b>Repository</b>: http://ubuntu.bigbluebutton.org/xenial-200/ bigbluebutton-xenial main
<b>Versions</b>:
bbb-apps-video:amd64 (1:2.0.0-15, 1:2.0.0-21), bbb-mkclean:amd64 (1:0.8.7-3, 1:0.8.7-4), bbb-transcode-akka:amd64 (2.0.0-4, 2.0.0-5), bbb-apps:amd64 (1:2.0.0-42, 1:2.0.0-46), bbb-playback-presentation:amd64 (1:2.0.0-20, 1:2.0.0-23), bbb-apps-video-broadcast:amd64 (1:2.0.0-4, 1:2.0.0-8), bbb-apps-sip:amd64 (1:2.0.0-6, 1:2.0.0-11), bbb-record-core:amd64 (1:2.0.0-19, 1:2.0.0-23), bbb-web:amd64 (1:2.0.0-69, 1:2.0.0-72), bbb-fsesl-akka:amd64 (2.0.0-19, 2.0.0-21), bigbluebutton:amd64 (1:2.0.0-6, 1:2.0.0-12), bbb-apps-screenshare:amd64 (1:2.0.0-25, 1:2.0.0-34), bbb-freeswitch-core:amd64 (2:1.6-44, 2:2.0.0-45), bbb-apps-akka:amd64 (2.0.0-128, 2.0.0-133), bbb-red5:amd64 (1:1.0.8-33, 1:1.0.8-39), bbb-client:amd64 (1:2.0.0-281, 1:2.0.0-324), bbb-config:amd64 (1:2.0.0-41, 1:2.0.0-52)

Edited to fix log display.

**Comment by ffdixon** [comment]
Thanks for reporting this -- we detected the issue yesterday on our servers as well.  We've got a ticket open for this, see https://github.com/bigbluebutton/bigbluebutton/issues/5603.

We have identified the underlying problem and are working on a fix.  It shouldn't be too long before we publish an update to BigBlueButton 2.0-beta with the fix to red5.

**Comment by kepstin** [comment]
This issue with webcams being frozen at the start of the video has been worked around in #5608 and should be included the next time we update the packages.

**Comment by jspicard** [comment]
Thank you both! Code modification in https://github.com/bigbluebutton/bigbluebutton/pull/5608 seemed to fix the issue. I don't know if it's just me, but the video quality seems more choppy/artifacted than usual.

Thanks again!

**Comment by kepstin** [comment]
Yes, the video quality being choppy/glitch is separate issue that we're still working on. Follow ticket for #5603 for details on that.

**Comment by ffdixon** [comment]
@jspicard We've just pushed a package update out to the BigBlueButton repository that should fix this error.  We've tested it locally, but it would be great if you could update and let us know.

**Comment by jspicard** [comment]
Will do. We have people using the system right now so I can't take it down but we will patch it tomorrow morning and let you know!

Thanks again!

**Comment by jspicard** [comment]
Hey Fred, everything looks great. Both fixes seemed to have worked and presentations look great! Thanks again for all that you guys do!
