### ISSUE TITLE
Screenshare sharing resizing regression

### ISSUE THREAD

**Issue by GhaziTriki** [bigbluebutton/bigbluebutton#5622]
Resize buttons disappeared from the screen sharing viewer window. The video also does not resize if the window is resized.

**Comment by capilkey** [comment]
Did you see this with the Java or WebRTC viewer windows? I just tried both on staging and I could freely resize the viewer windows.

**Comment by GhaziTriki** [comment]
All working fine. I confused the presenter window with the viewer's one.
