### ISSUE TITLE
Weird Flash rendering using Firefox x64 on windwos

### ISSUE THREAD

**Issue by GhaziTriki** [bigbluebutton/bigbluebutton#5624]
We get this non-suitable rendering Firefox x64 windwos 10

Reported issue to Firefox bugzilla https://bugzilla.mozilla.org/show_bug.cgi?id=1466179

![image 358](https://user-images.githubusercontent.com/4991088/40853444-fd4802ca-65c5-11e8-8348-19123c760855.png)

**Comment by ffdixon** [comment]
Do you have steps we can try following to reproduce?  Just tried it and it looked OK in FireFox 60 on Mac OS X

![image](https://user-images.githubusercontent.com/290351/41503088-520b3240-7198-11e8-969a-5f26591f368e.png)

**Comment by GhaziTriki** [comment]
I uninstalled all Firefox obselete plugins and things went well.

**Comment by GhaziTriki** [comment]
Tested with a clean install of Firefox portable. The issue is still there.

**Comment by GhaziTriki** [comment]
Display back to normal with the 62 release of Firefox.
