### ISSUE TITLE
Inconsistent buttons

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#5629]
A quick look through the current interface shows we are starting to be inconsistent in how we prompt the user

Logout Confirmation

![image](https://user-images.githubusercontent.com/290351/40874550-d88252a0-663e-11e8-9b1f-9baac2fd557c.png)

Start/Stop Recording

![image](https://user-images.githubusercontent.com/290351/40874561-048f3502-663f-11e8-8040-834a658619c4.png)

Custom Polls

![image](https://user-images.githubusercontent.com/290351/40874577-19542574-663f-11e8-8912-87e599e8ec78.png)

Closed Captioning 

![image](https://user-images.githubusercontent.com/290351/40874649-af53979e-663f-11e8-9a12-81b6b4fc9287.png)

Create a new Note

![image](https://user-images.githubusercontent.com/290351/40874652-c40696a0-663f-11e8-95b2-506cf46e0a92.png)

We should do a quick cleanup and make the style as consistent (as possible).

**Comment by tylercopeland** [comment]
@ffdixon great catch! For the most part, we should be using the solid blue button for the primary actions, followed by the outlined button for secondary actions.

**Comment by GhaziTriki** [comment]
@tylercopeland Closing popups is also inconsistent, sometimes we have a close button at the top right, sometimes a close/no/cancel button at the bottom. Which one should we keep?

**Comment by capilkey** [comment]
Don't overthink the closes please. The last time somebody tried to remove them they broke a bunch of accessibility stuff and I had to go back and fix them all.

**Comment by tylercopeland** [comment]
@GhaziTriki you have a valid point, but as per @capilkey's comment I don't want to add more work / break things especially accessibility. 

@capilkey what are your thoughts on adding an "X" to the top right hand corner on all modals to make thing a little more consistent? In some, but not cases, we'd also keep the "close" button.

**Comment by capilkey** [comment]
The only scenario where I think it wouldn't make sense to have an "X" is if you want an affirmative action from the user whereas an "X" is usually just a non-committal "go away" button. The one example I could find is the presenter's poll results modal because we want them to either publish or close the poll and not just close the modal.

**Comment by tylercopeland** [comment]
@capilkey that's fair. @GhaziTriki let's go with @capilkey guidances on this.
