### ISSUE TITLE
Webcams Only For Moderators not working properly on HTML5 client

### ISSUE THREAD

**Issue by w3tra** [bigbluebutton/bigbluebutton#5631]
bbb-html5 1:2.0.0-222

Create meeting with `webcamsOnlyForModerator=true`
Join to meeting as attendee, and see share webcam button and my video is visible to all participants.
Is this how it should work? Or this function is not available in HTML5 yet?

**Comment by amirtq** [comment]
To bring up the issue
is this issue implemented to work in HTML5 or it is just an option for Flash interface?
We are also confused here because we put this option in Create API call but it is not working at all in our HTML5 interface.

Regards

**Comment by ffdixon** [comment]
> We are also confused here because we put this option in Create API call but it is not working at all in our HTML5 interface.

What version of BigBlueButton are you running?

**Comment by amirtq** [comment]
here is our --version details by the way:
ii  bbb-apps                              1:2.2.0-42                                      amd64        BigBlueButton applications for Red5
ii  bbb-apps-akka                         2.2.0-77                                        all          BigBlueButton Apps (Akka)
ii  bbb-apps-screenshare                  1:2.2.0-42                                      amd64        BigBlueButton screenshare module for Red5
ii  bbb-apps-sip                          1:2.2.0-11                                      amd64        BigBlueButton SIP module for Red5
ii  bbb-apps-video                        1:2.2.0-39                                      amd64        BigBlueButton video module for Red5
ii  bbb-apps-video-broadcast              1:2.2.0-8                                       amd64        BigBlueButton video broadcast module for Red5
ii  bbb-client                            1:2.2.0-33                                      amd64        BigBlueButton Flash client
ii  bbb-config                            1:2.2.0-171                                     amd64        BigBlueButton configuration utilities
rc  bbb-demo                              1:2.2.0-9                                       amd64        BigBlueButton API demos
ii  bbb-etherpad                          1:2.2.0-50                                      amd64        The EtherPad Lite components for BigBlueButton
ii  bbb-freeswitch-core                   2:2.2.0-97                                      amd64        BigBlueButton build of FreeSWITCH
ii  bbb-freeswitch-sounds                 1:1.6.7-6                                       amd64        FreeSWITCH Sounds
ii  bbb-fsesl-akka                        2.2.0-61                                        all          BigBlueButton FS-ESL (Akka)
ii  bbb-html5                             1:2.2.0-873                                     amd64        The HTML5 components for BigBlueButton
ii  bbb-mkclean                           1:0.8.7-3                                       amd64        Clean and optimize Matroska and WebM files
ii  bbb-playback-presentation             1:2.2.0-28                                      amd64        BigBluebutton playback of presentation
ii  bbb-record-core                       1:2.2.0-63                                      amd64        BigBlueButton record and playback
ii  bbb-red5                              1:1.0.10-16                                     amd64        The Red5 server for BigBlueButton
ii  bbb-transcode-akka                    2.2.0-8                                         all          BigBlueButton Transcoder
ii  bbb-web                               1:2.2.0-119                                     amd64        BigBlueButton API
ii  bbb-webhooks                          1:2.2.0-16                                      amd64        BigBlueButton Webhooks
ii  bbb-webrtc-sfu                        1:2.2.0-99                                      amd64        BigBlueButton WebRTC SFU
ii  bigbluebutton                         1:2.2.0-5                                       amd64        Open source web conferencing platform (bbb)
ii  ffmpeg                                7:4.2.2-1bbb1~ubuntu16.04                       amd64        Tools for transcoding, streaming and playing of multimedia files
ii  libavcodec58:amd64                    7:4.2.2-1bbb1~ubuntu16.04                       amd64        FFmpeg library with de/encoders for audio/video codecs - runtime files
ii  libavdevice58:amd64                   7:4.2.2-1bbb1~ubuntu16.04                       amd64        FFmpeg library for handling input and output devices - runtime files
ii  libavfilter7:amd64                    7:4.2.2-1bbb1~ubuntu16.04                       amd64        FFmpeg library containing media filters - runtime files
ii  libavformat58:amd64                   7:4.2.2-1bbb1~ubuntu16.04                       amd64        FFmpeg library with (de)muxers for multimedia containers - runtime files
ii  libavresample4:amd64                  7:4.2.2-1bbb1~ubuntu16.04                       amd64        FFmpeg compatibility library for resampling - runtime files
ii  libavutil56:amd64                     7:4.2.2-1bbb1~ubuntu16.04                       amd64        FFmpeg library with functions for simplifying programming - runtime files
ii  libopusenc0                           0.2.1-1bbb1                                     amd64        High-level API for encoding Ogg Opus audio streams
ii  libpostproc55:amd64                   7:4.2.2-1bbb1~ubuntu16.04                       amd64        FFmpeg library for post processing - runtime files
ii  libswresample3:amd64                  7:4.2.2-1bbb1~ubuntu16.04                       amd64        FFmpeg library for audio resampling, rematrixing etc. - runtime files
ii  libswscale5:amd64                     7:4.2.2-1bbb1~ubuntu16.04                       amd64        FFmpeg library for image scaling and various conversions - runtime files

**Comment by amirtq** [comment]
here is our --version details:
`ii  bbb-apps                              1:2.2.0-42                                      amd64        BigBlueButton applications for Red5
ii  bbb-apps-akka                         2.2.0-77                                        all          BigBlueButton Apps (Akka)
ii  bbb-apps-screenshare                  1:2.2.0-42                                      amd64        BigBlueButton screenshare module for Red5
ii  bbb-apps-sip                          1:2.2.0-11                                      amd64        BigBlueButton SIP module for Red5
ii  bbb-apps-video                        1:2.2.0-39                                      amd64        BigBlueButton video module for Red5
ii  bbb-apps-video-broadcast              1:2.2.0-8                                       amd64        BigBlueButton video broadcast module for Red5
ii  bbb-client                            1:2.2.0-33                                      amd64        BigBlueButton Flash client
ii  bbb-config                            1:2.2.0-171                                     amd64        BigBlueButton configuration utilities
rc  bbb-demo                              1:2.2.0-9                                       amd64        BigBlueButton API demos
ii  bbb-etherpad                          1:2.2.0-50                                      amd64        The EtherPad Lite components for BigBlueButton
ii  bbb-freeswitch-core                   2:2.2.0-97                                      amd64        BigBlueButton build of FreeSWITCH
ii  bbb-freeswitch-sounds                 1:1.6.7-6                                       amd64        FreeSWITCH Sounds
ii  bbb-fsesl-akka                        2.2.0-61                                        all          BigBlueButton FS-ESL (Akka)
ii  bbb-html5                             1:2.2.0-873                                     amd64        The HTML5 components for BigBlueButton
ii  bbb-mkclean                           1:0.8.7-3                                       amd64        Clean and optimize Matroska and WebM files
ii  bbb-playback-presentation             1:2.2.0-28                                      amd64        BigBluebutton playback of presentation
ii  bbb-record-core                       1:2.2.0-63                                      amd64        BigBlueButton record and playback
ii  bbb-red5                              1:1.0.10-16                                     amd64        The Red5 server for BigBlueButton
ii  bbb-transcode-akka                    2.2.0-8                                         all          BigBlueButton Transcoder
ii  bbb-web                               1:2.2.0-119                                     amd64        BigBlueButton API
ii  bbb-webhooks                          1:2.2.0-16                                      amd64        BigBlueButton Webhooks
ii  bbb-webrtc-sfu                        1:2.2.0-99                                      amd64        BigBlueButton WebRTC SFU
ii  bigbluebutton                         1:2.2.0-5                                       amd64        Open source web conferencing platform (bbb)
ii  ffmpeg                                7:4.2.2-1bbb1~ubuntu16.04                       amd64        Tools for transcoding, streaming and playing of multimedia files
ii  libavcodec58:amd64                    7:4.2.2-1bbb1~ubuntu16.04                       amd64        FFmpeg library with de/encoders for audio/video codecs - runtime files
ii  libavdevice58:amd64                   7:4.2.2-1bbb1~ubuntu16.04                       amd64        FFmpeg library for handling input and output devices - runtime files
ii  libavfilter7:amd64                    7:4.2.2-1bbb1~ubuntu16.04                       amd64        FFmpeg library containing media filters - runtime files
ii  libavformat58:amd64                   7:4.2.2-1bbb1~ubuntu16.04                       amd64        FFmpeg library with (de)muxers for multimedia containers - runtime files
ii  libavresample4:amd64                  7:4.2.2-1bbb1~ubuntu16.04                       amd64        FFmpeg compatibility library for resampling - runtime files
ii  libavutil56:amd64                     7:4.2.2-1bbb1~ubuntu16.04                       amd64        FFmpeg library with functions for simplifying programming - runtime files
ii  libopusenc0                           0.2.1-1bbb1                                     amd64        High-level API for encoding Ogg Opus audio streams
ii  libpostproc55:amd64                   7:4.2.2-1bbb1~ubuntu16.04                       amd64        FFmpeg library for post processing - runtime files
ii  libswresample3:amd64                  7:4.2.2-1bbb1~ubuntu16.04                       amd64        FFmpeg library for audio resampling, rematrixing etc. - runtime files
ii  libswscale5:amd64                     7:4.2.2-1bbb1~ubuntu16.04                       amd64        FFmpeg library for image scaling and various conversions - runtime files
`

**Comment by amirtq** [comment]
> 
> 
> > We are also confused here because we put this option in Create API call but it is not working at all in our HTML5 interface.
> 
> What version of BigBlueButton are you running?

here is our --version details:
`ii  bbb-apps                              1:2.2.0-42                                      amd64        BigBlueButton applications for Red5
ii  bbb-apps-akka                         2.2.0-77                                        all          BigBlueButton Apps (Akka)
ii  bbb-apps-screenshare                  1:2.2.0-42                                      amd64        BigBlueButton screenshare module for Red5
ii  bbb-apps-sip                          1:2.2.0-11                                      amd64        BigBlueButton SIP module for Red5
ii  bbb-apps-video                        1:2.2.0-39                                      amd64        BigBlueButton video module for Red5
ii  bbb-apps-video-broadcast              1:2.2.0-8                                       amd64        BigBlueButton video broadcast module for Red5
ii  bbb-client                            1:2.2.0-33                                      amd64        BigBlueButton Flash client
ii  bbb-config                            1:2.2.0-171                                     amd64        BigBlueButton configuration utilities
rc  bbb-demo                              1:2.2.0-9                                       amd64        BigBlueButton API demos
ii  bbb-etherpad                          1:2.2.0-50                                      amd64        The EtherPad Lite components for BigBlueButton
ii  bbb-freeswitch-core                   2:2.2.0-97                                      amd64        BigBlueButton build of FreeSWITCH
ii  bbb-freeswitch-sounds                 1:1.6.7-6                                       amd64        FreeSWITCH Sounds
ii  bbb-fsesl-akka                        2.2.0-61                                        all          BigBlueButton FS-ESL (Akka)
ii  bbb-html5                             1:2.2.0-873                                     amd64        The HTML5 components for BigBlueButton
ii  bbb-mkclean                           1:0.8.7-3                                       amd64        Clean and optimize Matroska and WebM files
ii  bbb-playback-presentation             1:2.2.0-28                                      amd64        BigBluebutton playback of presentation
ii  bbb-record-core                       1:2.2.0-63                                      amd64        BigBlueButton record and playback
ii  bbb-red5                              1:1.0.10-16                                     amd64        The Red5 server for BigBlueButton
ii  bbb-transcode-akka                    2.2.0-8                                         all          BigBlueButton Transcoder
ii  bbb-web                               1:2.2.0-119                                     amd64        BigBlueButton API
ii  bbb-webhooks                          1:2.2.0-16                                      amd64        BigBlueButton Webhooks
ii  bbb-webrtc-sfu                        1:2.2.0-99                                      amd64        BigBlueButton WebRTC SFU
ii  bigbluebutton                         1:2.2.0-5                                       amd64        Open source web conferencing platform (bbb)
ii  ffmpeg                                7:4.2.2-1bbb1~ubuntu16.04                       amd64        Tools for transcoding, streaming and playing of multimedia files
ii  libavcodec58:amd64                    7:4.2.2-1bbb1~ubuntu16.04                       amd64        FFmpeg library with de/encoders for audio/video codecs - runtime files
ii  libavdevice58:amd64                   7:4.2.2-1bbb1~ubuntu16.04                       amd64        FFmpeg library for handling input and output devices - runtime files
ii  libavfilter7:amd64                    7:4.2.2-1bbb1~ubuntu16.04                       amd64        FFmpeg library containing media filters - runtime files
ii  libavformat58:amd64                   7:4.2.2-1bbb1~ubuntu16.04                       amd64        FFmpeg library with (de)muxers for multimedia containers - runtime files
ii  libavresample4:amd64                  7:4.2.2-1bbb1~ubuntu16.04                       amd64        FFmpeg compatibility library for resampling - runtime files
ii  libavutil56:amd64                     7:4.2.2-1bbb1~ubuntu16.04                       amd64        FFmpeg library with functions for simplifying programming - runtime files
ii  libopusenc0                           0.2.1-1bbb1                                     amd64        High-level API for encoding Ogg Opus audio streams
ii  libpostproc55:amd64                   7:4.2.2-1bbb1~ubuntu16.04                       amd64        FFmpeg library for post processing - runtime files
ii  libswresample3:amd64                  7:4.2.2-1bbb1~ubuntu16.04                       amd64        FFmpeg library for audio resampling, rematrixing etc. - runtime files
ii  libswscale5:amd64                     7:4.2.2-1bbb1~ubuntu16.04                       amd64        FFmpeg library for image scaling and various conversions - runtime files
`

**Comment by amirtq** [comment]
Dear @ffdixon 
Would you please comment?

**Comment by amirtq** [comment]
dear @ffdixon 
Would you comment please?

**Comment by donkarlo** [comment]
Our professor also has this problem. Is there a solution? We can share our video but as an instructor, he can not?

**Comment by antobinary** [comment]
Hi @donkarlo 
Could you please provide more details:
 - what version of BigBlueButton do you use?
 - what are the parameters you use for creating meeting?
 - is this behaviour consistent / reproducible?
 If you are able to provide steps to reproduce, we can try this on the latest release (2.3.0)...

**Comment by donkarlo** [comment]
It is installed by Klagenfurt university and I dont have access to my professor's computer. He says BBB shows his video for himself but we, as students can not see him. He is using a desktop computer with an external webcam.

**Comment by donkarlo** [comment]
> It is installed by Klagenfurt university and I dont have access to my professor's computer. He says BBB shows his video for himself but we, as students can not see him. He is using a desktop computer with an external webcam.

This is what I see in my client version Copyright: ©2021 BigBlueButton Inc.
Client build: 1157

**Comment by antobinary** [comment]
`Client build: 1157` corresponds to BigBlueButton 2.2.36

> He says BBB shows his video for himself but we, as students can not see him.

This can be quite a few different things. This thread is about passing specific parameters on meeting create, which is likely not the case for you, since you're observing the opposite - one of your meeting participants (who happens to be the instructor)'s webcam stream is not propagated to others. 

My suggestion would be to arrange to test this with your professor over at https://test.bigbluebutton.org/demo/demo2.jsp - just say 'meet me at room English 232' - if you are able to see the webcam, then the issue might be at your university's end. If the webcam is not visible - the issue might be at the professor's end, or BBB... 
If you have a moment to help your professor - please ask him to share his screen and see what he sees - perhaps there's an error message, or the professor only sees the webcam preview, ...
