### ISSUE TITLE
Recording processing for "presentation" format does unnecessary file copying.

### ISSUE THREAD

**Issue by kepstin** [bigbluebutton/bigbluebutton#5635]
The "presentation" format scripts, as their first step, make a copy of the raw archive directory into a temporary directory. This isn't necessary - we can read the files directly from the raw archive directory instead.

Look at updating the scripts to improve this. It should help improve recording process times significantly on systems with limited disk io speeds.

**Comment by HakanSaltan** [comment]
Peki bunu nasıl yapabiliriz ?

**Comment by danielpetri1** [comment]
I'll work on this as part of a submission for the [OpenSourceLab](https://www.in.tum.de/cm/teaching/winter-term-202122/open-source-lab/) at my uni.
