### ISSUE TITLE
Address performance on FireFox for UI intensive operations (whiteboard, webcam viewing)

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#5642]
We notice significantly higher use of CPU for FireFox when whiteboard and webcams are being used (viewer perspective)

**Comment by ffdixon** [comment]
@capilkey Given the recent updates to whiteboard, is this still an issue on FireFox?

**Comment by capilkey** [comment]
Firefox and Chrome seem to perform to similar levels. We need to improve performance across the board and not just for one browser I think.
