### ISSUE TITLE
API calls for live statistics and performance

### ISSUE THREAD

**Issue by vishnunn** [bigbluebutton/bigbluebutton#5656]
It would be great if can have API calls to get live statistics as to how many meetings are running, people in each meeting, etc and on performance part, how much resources (CPU, RAM, bandwidth, etc) are being used.

**Comment by iSamof** [comment]
Plus an automated log of the stats and server performance. Log frequency & detail level being server config parameters.

**Comment by GhaziTriki** [comment]
@vishnunn you can use https://my-netdata.io/, it has its own API

**Comment by prlanzarin** [comment]
Just an example of how monitoring is already possible without bloating the APIs: https://github.com/greenstatic/bigbluebutton-exporter.
