### ISSUE TITLE
Black window when user menu is clicked

### ISSUE THREAD

**Issue by llisboa** [bigbluebutton/bigbluebutton#5680]
Please,
After clicking the user's menu, when the pop-up dialog is shown with part out off the screen, a black screen appears and block all resources.
Just go to the window and click the user until the screen appears.

**Comment by ffdixon** [comment]
It would be very helpful if you could add a screen shot of what you are seeing.

**Comment by llisboa** [comment]
Tests in version HTML5Client.
1. When I click on the menu with space it works.
![img01](https://user-images.githubusercontent.com/18197654/41323318-363991ea-6e9d-11e8-8839-598f2273dbe1.jpg)
2. I reduze window space...
![img02](https://user-images.githubusercontent.com/18197654/41323332-46476b8e-6e9d-11e8-87b6-cd08c5643069.jpg)
3. And I click in user menu again resulting in Black Window!
![img03](https://user-images.githubusercontent.com/18197654/41323347-5af84544-6e9d-11e8-8179-e5d8fdf52e82.jpg)

**Comment by antobinary** [comment]
Hi @llisboa 
Does your use case for the HTML5 client include very small window like the above or this is just something you encountered by chance? Were you trying to simulate small (mobile device) experience?

**Comment by llisboa** [comment]
The small screen is for quick testing only. Think of the moderation of multiple users. Click on the last user is common and if the popup exceeds the screen boundaries the problem happens. The more users the more chances the problem happens. Every help is welcome.

**Comment by antobinary** [comment]
I was able to reproduce it on your server (saw URL from the screenshot) but not on test.bigbluebutton.org (build 349 vs your 333). Would you be able to try reproducing it on test.bigbluebutton.org?

**Comment by llisboa** [comment]
I tested it on your version and it worked. We forced the BBB update and the issue was resolved. Thank you very much.
