### ISSUE TITLE
Tweak user menu to allow all text to be displayed (even when localized)

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#5684]
![screenshot from 2018-06-13 14-14-27](https://user-images.githubusercontent.com/6312397/41369910-36c7a256-6f14-11e8-903a-2876602149e9.png)
In some languages (German in particular) the user menu labels are so long that they don't fit. Please 
* remove username from 'demote to viewer' and
* wrap the text on the next line if necessary.

**Comment by tylercopeland** [comment]
@antobinary it's not common to see tooltips in a drop-down menu. 

A couple of thoughts here:  
- Could we remove "Name" from Demote to a viewer?
- From there, could the width of the menu expand based on the length of the text?

@oswaldoacauan do you have any thoughts or suggestions here?

**Comment by antobinary** [comment]
> Could we remove "Name" from Demote to a viewer?
Fine with me

> ... what we could do instead is just wrap the text on the next line.
Fine with me too. Renaming the issue to match the decisions. The goal was to be able to see what the labels are. The way to do it was open to amendments. Thanks for the good suggestions! :smiley:
