### ISSUE TITLE
Add option for 1px line thickness to HTML5 client

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#5686]
In the Flash client, the presenter can select a 1 px thick line, but currently in the HTML5 client the thinnest line is 2px.

![image](https://user-images.githubusercontent.com/290351/41380507-2e475788-6f33-11e8-9c11-904565b85e36.png)

Add the ability for the user to select 1px line thickness.  We can leave the selection of 2px line thickness as default.

**Comment by OZhurbenko** [comment]
The smallest border can be 1px. Thus the smaller circle diameter in the dropdown can be 2px. That's why it's 2px minimum, otherwise the displayed circle diameter in the dropdown won't match the shape thickness.
It's more of a design limitation.. Unless you don't mind it being slightly off :-)

**Comment by antobinary** [comment]
We can definitely afford having the icon be a bit bigger than the actual lines on the whiteboard. The key here is to allow thinner pencil marks on the whiteboard. Merging #5667 into this github issue
