### ISSUE TITLE
Locks still apply to moderators promoted from viewer

### ISSUE THREAD

**Issue by mkpelletier** [bigbluebutton/bigbluebutton#5687]
Build#884

We have an unusual locking behaviour on some users.  If a user joins a meeting after locks have been set, then he or she is promoted, the user (now moderator) is unable to unmute their mic.

We can resolve the problem by demoting the user to viewer, clicking the padlock to unlock them, and then promote them again.  If we promote the user before unlocking them first, the locks persist even after they have been promoted.

**Comment by ffdixon** [comment]
@mkpelletier Is this an issue with the HTML5 client.  Can you do a quick check here

   http://test.bigbluebutton.org/demo/demoHTML5.jsp

and let us know.

**Comment by ffdixon** [comment]
Confirmed this is fixed in the latest build of BigBlueButton 2.2-beta.
