### ISSUE TITLE
Timer on lecture view

### ISSUE THREAD

**Issue by mkpelletier** [bigbluebutton/bigbluebutton#5696]
The lecture view is very helpful in removing UI elements that might otherwise be a distraction.  However, in instances where you might have a presenter and a session moderator, there is no easy way to indicate time to the presenter.  

Perhaps a timer could be added to lecture view- controllable by the moderator?  It would be very useful to allow the moderator to set a some arbitrary value from which the timer counts down, then to have that timer turn red in the last X% of the allotted time.  So, if a speaker has 20 minutes to speak, the timer would count down from 20, and turn red from say 5 minutes.

**Comment by ffdixon** [comment]
We recently added a timer to show the length of the recorded session (the timer appears a few seconds after the Start/Stop record button is clicked.)

![image](https://user-images.githubusercontent.com/290351/41464852-bbc11194-7069-11e8-9d56-6ebb7a130372.png)

We could add another timer, but the key would be to determine where this second timer should appear.  Suggestions?

**Comment by mkpelletier** [comment]
Hi Fred,

Thanks for the response.  Yes, we have that new timer next to the record button, but we just ended a conference with multiple sessions.  I did see issue #5534 , but I am thinking of formats where you have debates and rebuttals, or just simple lectures split into presentation followed by Q/A.  In any case, the recording time is not helpful in this regard, since it is counting up and shows the cumulative recording length.

Do you think perhaps putting the timer on the presenter control bar would be a suitable place?  Since the presenter is regularly using that space anyway, the timer would be ideally placed to be noticed. The only other thought would be to have a separate window for the timer; something like the following maybe?

![bbb timer mockup](https://user-images.githubusercontent.com/4638072/41466320-0bfd8614-70a2-11e8-95af-932420fe4e23.png)

**Comment by yugdeep17** [comment]
Hi,
Any progress on Timer? Can we have a timer display on the ongoing meetings?

**Comment by mkpelletier** [comment]
Hello @yugdeep17, are you referring to a countdown timer as suggested in this thread or just a timer that displays the current running time?  Bigbluebutton already does the latter as you can see here:
![Screenshot 2020-05-29 at 10 02 00](https://user-images.githubusercontent.com/4638072/83236269-87dea000-a193-11ea-9c3c-d30d801a3924.png)

I would still love a countdown timer as I think there are relevant use cases for this, but I would not want it to show to viewers, but for the presenter only. I am not sure how this would work in the newer html5 layout that we have now.  The mockup above was based on the old flash-based UI.

**Comment by yugdeep17** [comment]
Hello @mkpelletier Yes, i was querying about a timer that displays the current running time for presenter only.

**Comment by mkpelletier** [comment]
It is funny, I am actually in a conference right now with breakout rooms.  In the breakout room a timer displays a countdown at the top:
![Screenshot 2020-05-29 at 10 19 00](https://user-images.githubusercontent.com/4638072/83237870-dd1bb100-a195-11ea-8e51-1508387fffb3.png)

Something like this for the presenter would work nicely.

**Comment by yugdeep17** [comment]
Ok, i am using bigbluebutton version 2.2 so unable to see breakout room features.

**Comment by mkpelletier** [comment]
No, I think breakout rooms has been available for quite some time now.  I am fairly certain it has been since at least 2.0 if not before.

**Comment by yugdeep17** [comment]
Yes, you are correct.. got it.

**Comment by matiasilva** [comment]
I've opened a new issue #9844 for this feature as this discussion pertains to the old Flash client.
