### ISSUE TITLE
Logout while in audio plays 'You have been kicked'

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#5703]
Seems to be reproducible on slower clients, in particular FireFox (?).
I was not able to reproduce on any browser/server but saw a video of the bug.

**Comment by kepstin** [comment]
Note that this isn't specific to the html5 client, I've seen it in the flash client as well.

**Comment by capilkey** [comment]
My guess would be that when the user leave is received in akka-apps it sends a message to FreeSWITCH to kick out the corresponding voice user and on slower connections the kick arrives before the client switches to a "logged out" state.

**Comment by jibon57** [comment]
@kepstin you are right. Both flash & HTML5 has this problem.

**Comment by antobinary** [comment]
Stale
