### ISSUE TITLE
Add countdown timer in Screen Sharing Presenters Preview window

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#5706]
When the presenter starts screensharing using WebRTC, it takes about 12 seconds before the keyframe arrives and they see the preview in the client.

![screenshare](https://user-images.githubusercontent.com/290351/41502258-59228dbc-7184-11e8-995c-b8e438523796.gif)

The problem is that the user doesn't know when the screen sharing will start.  Let's change the animation to a 15 second progress bar

![image](https://user-images.githubusercontent.com/290351/41502316-49c9c94c-7185-11e8-9ec9-8e1ddf6b319d.png)

This will give the presenter a better sense of how long they need to wait.

**Comment by capilkey** [comment]
The viewer window uses the same "...." as the presenter. Should the same fake loading bar be used in both windows?
