### ISSUE TITLE
Incorrect message when meeting duration reached

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#5708]
When the main meeting starts with a duration, and the time left is under one minute, all users see the following dialog box

![image](https://user-images.githubusercontent.com/290351/41502462-5f821476-7188-11e8-9e06-3e8c2eaf245b.png)

This makes sense in breakout rooms, but not in the main meeting.   

  "This session will end in less than a minute"

**Comment by ritzalam** [comment]
Why would a meeting duration be less than zero? We'll check in the create meeting if duration passed is less than zero we change it to zero.

**Comment by ffdixon** [comment]
The use case is when a duration is passed at 120, for example, and the meeting is about to hit that threshold.  The dialog box appears with the text "Breakout rooms ...", which is confusing because it's the main meeting that is about to be ended.

**Comment by ritzalam** [comment]
Ok. The title threw me off.

**Comment by ritzalam** [comment]
Fixed in https://github.com/bigbluebutton/bigbluebutton/pull/5742

**Comment by ffdixon** [comment]
Confirmed.

![image](https://user-images.githubusercontent.com/290351/41824514-6ae1af72-77df-11e8-83f1-2740a1fb134e.png)
