### ISSUE TITLE
You did not pass the checksum security check

### ISSUE THREAD

**Issue by neutron92** [bigbluebutton/bigbluebutton#5721]
when i'm in room cration i have this error

`<response><returncode>FAILED</returncode><messageKey>checksumError</messageKey><message>You did not pass the checksum security check</message></response>`

You did not pass the checksum security check

**Comment by antobinary** [comment]
Hi @neutron92 

You need to share more information about the request...

1. How did you create it (API-MATE or manually, or ...)
2. What is the full request?
3. Is this aimed at a public server like http://test-install.blindsidenetworks.com/ ?

The more information you provide, the better we can assist

**Comment by neutron92** [comment]
Hello im usin this node package
