### ISSUE TITLE
Add endMeeting callback to API

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#5724]
Currently, a front-end to BigBlueButton doesn't have anyway of knowing when a meeting has ended in order to update it's UI.  For example, it might be displaying a 'Join' button to let a user join the meeting, but the actual meeting as ended.

Some implementations will poll the BigBlueButton, others will check each time the page is refreshed. 

We do provide a [webhooks ](http://docs.bigbluebutton.org/dev/webhooks.html) server, which provides fine-grained events, but many times the front-end just needs to know when the meeting ends so it can update it's interface for users.

Add to the BigBlueButton `create` parameter called `endCallback` which contains a URL.

When bbb-web is ending the meeting -- whether in response to the `duration` parameter reached, or it had received an `end` meeting API request, or when a moderator exits the meeting and triggers the end -- bbb-web will make one request to the URL provided by `endCallback`

**Comment by ffdixon** [comment]
Implemented in 2.0-beta

**Comment by ffdixon** [comment]
It would be very useful for the front-end to also know whether there are any recordings forthcoming for the session.  This enables the front-end to immediately close the session and not query in the future for a recording.

Add `?recordingmarks=true/false` to the end of the callback URL.  Set `recordingmarks=true` if there are  Start/Stop recording marks in the session (scan the events in redis); otherwise, set `recordingmarks=true`.

**Comment by GhaziTriki** [comment]
We need to keep the provided GET parameters. The current code deletes any custom parameter.

**Comment by GhaziTriki** [comment]
I created a micro-application in Java to test the library. The Apache HTTP docs are misleading.

The following class :

```
import java.net.MalformedURLException;
import java.net.URI;
import java.net.URISyntaxException;

import org.apache.http.client.utils.URIBuilder;

public class UrlUpdater {

    public static void main(String[] args) throws MalformedURLException, URISyntaxException {
        System.out.println(updateUrl("http://google.fr"));
        System.out.println(updateUrl("http://google.fr?update=true"));
        System.out.println(updateUrl("http://google.fr?update=true&test=false"));
        System.out.println(updateUrl("https://www.google.fr?update=true&test=false"));
    }

    private static String updateUrl(String url) throws MalformedURLException, URISyntaxException {
        return new URIBuilder(new URI(url)).addParameter("recordingmarks", true ? "true" : "false").build().toURL()
                .toString();
    }

}
```

Gives the following result : 

```
http://google.fr?recordingmarks=true
http://google.fr?update=true&recordingmarks=true
http://google.fr?update=true&test=false&recordingmarks=true
https://www.google.fr?update=true&test=false&recordingmarks=true
```

We don't need to update the code.
