### ISSUE TITLE
Running bbb-conf --clean doesn't delete WebRTC SFU logs

### ISSUE THREAD

**Issue by capilkey** [bigbluebutton/bigbluebutton#5725]
Requirements:
* BBB 2.0
* HTML5 packages installed

Steps to reproduce:
1. Run "bbb-conf --clean" to remove existing logs

Expected result:
All logs including the WebRTC SFU logs (/var/log/bbb-webrtc-sfu/) to be deleted.

Actual result:
The logs going back months are still there in the SFU directory.

**Comment by ffdixon** [comment]
Fixed in https://github.com/bigbluebutton/bigbluebutton/pull/5754
