### ISSUE TITLE
audio jitter

### ISSUE THREAD

**Issue by zenny** [bigbluebutton/bigbluebutton#5755]
Hi,

Installed bbb-2 using bbb-install script. All seems to work except webrtc (tested with firefox 60, vivaldi and chromium). The audio using the flash client in Firefox 60 is jittery. There is a undesired noise even when doing an echo test. No audio seems to get transferred without any jitter.

Any inputs?

Cheers,
/z

**Comment by ffdixon** [comment]
Can you test using

  https://demo.bigbluebutton.org/

and let us know how the audio sounds.  Use FireFox or Chrome for best audio.  You should see the words '[ WebRTC Audio ]' in the lower right-hand corner.  If not, your not getting WebRTC audio (which is better than Flash-based audio).

![image](https://user-images.githubusercontent.com/290351/41881157-fe393c9c-78af-11e8-8744-0a2e27066261.png)

**Comment by ffdixon** [comment]
Just following up to see if you tried it on https://demo.bigbluebutton.org/.

**Comment by ffdixon** [comment]
Closing this issue.  WebRTC audio has better quality (48khz audio encoded with Opus over UDP with forward error correction) compares with Flash (16khz audio encoded speex over TCP).

Transmitting audio over TCP can cause resending of packets in poor network conditions which can lead to gaps in audio.
