### ISSUE TITLE
HTML5-Webcam doesn't work on Huawei Android phones on 2.0-RC1

### ISSUE THREAD

**Issue by Jarvil** [bigbluebutton/bigbluebutton#5764]
Hello,

You cannot share or see other peoples webcams on Huawei Android phones, it just loads and loads and gives an error "error loading webcam". Tested on two different Huawei android phones and Chrome.

Tested on **BigBlueButton 2.0-RC1**

Huawi P8 lite (ALE-L21) / android 6.0 / Emuix 4.0.3 / Chrome 65.0
Huawei honor 6 (H60-L04) / android 6.0 / Emuix 4.0 / Chrome 67.0

On Oneplus 5 and Samsung s4 webcam sharing works fine.

**Comment by Jarvil** [comment]
Hello,

I tried also with Acer tablet with android 6.0, webcam sharing doesn't work.

**Comment by Jarvil** [comment]
I also tested on https://test.bigbluebutton.org/ but webcam sharing doesn't work there.

**Comment by henriquebol** [comment]
Same problem here, but with several brands of smartphones. All with android 6.0 and chrome (67.0.33.96.87), only a Motorola G2 loaded the webcam, the others load and load and gives the error "error loading webcam" (also does not appear the motorola G2 webcam in them)

In firefox, all work.

A connection error occurs at https://test.bigbluebutton.org/.

Just confirming something else. The html5 version webcams do not appear in the flash version and the same on the other side. Is that right or is it just here?

**Comment by ffdixon** [comment]
> Just confirming something else. The html5 version webcams do not appear in the flash version and the same on the other side. Is that right or is it just here?

Webcams are not shared between Flash and HTML5 users (the codecs are different).

  http://docs.bigbluebutton.org/html/html5-overview.html#features-for-the-first-release

**Comment by henriquebol** [comment]
![screenshot_20180725-084308](https://user-images.githubusercontent.com/3309893/43201275-641f744a-8fee-11e8-9650-c96f2fdca6c2.png)
![screenshot_20180724-152532](https://user-images.githubusercontent.com/3309893/43201276-64342ff2-8fee-11e8-83be-3b0028f987fe.png)
![screenshot_20180725-084420](https://user-images.githubusercontent.com/3309893/43201273-63f20758-8fee-11e8-92d2-5855658a38cb.png)
![screenshot_20180725-084400](https://user-images.githubusercontent.com/3309893/43201274-64094152-8fee-11e8-8376-64ce406f9b10.png)

![screenshot_20180725-084607](https://user-images.githubusercontent.com/3309893/43201271-63c191ea-8fee-11e8-952a-3366e16d47db.png)
![screenshot_20180725-084744](https://user-images.githubusercontent.com/3309893/43201272-63d9997a-8fee-11e8-8085-bec7f1a271ed.png)

**Comment by ffdixon** [comment]
Hey @Jarvil, can you test again on https://test.bigbluebutton.org/ and let us know if your still getting the same errors.

**Comment by Jarvil** [comment]
Hello,

Share webcam doesn't work any better on Huawei honor 6 (H60-L04) / android 6.0 / Emuix 4.0 / Chrome 67.0 at https://test.bigbluebutton.org/ it gives the same error "error sharing webcam"

**Comment by prlanzarin** [comment]
After seeing multiple reports like those, and from the test results @henriquebol showed, my guess is that we're having some sort of WebRTC overconstraining with a subset of mobile devices, probably related to frame rate limitations. I'll try to devise a set of more lax constraints as a fallback to those cases, and when this goes live we'll ask for testing again @Jarvil. Thanks for the reports.

**Comment by ffdixon** [comment]
Merged into #5765
