### ISSUE TITLE
Pen tool disappears when annotating documents

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#5778]
When annotating an uploaded document, the pen tool will disappear on the edges of the document.

![untitled](https://user-images.githubusercontent.com/290351/42107174-688a5a44-7ba4-11e8-8164-81304c90b423.gif)

**Comment by capilkey** [comment]
Possible duplicate of #5768

**Comment by antobinary** [comment]
Closing in favor of #5768
