### ISSUE TITLE
Move "Set Status" to the participants dropdown menu

### ISSUE THREAD

**Issue by tylercopeland** [bigbluebutton/bigbluebutton#5782]
When selecting yourself in the participants list, a new item will appear "Set status". 

![html5-sidebar-participant-dropdown](https://user-images.githubusercontent.com/1273169/42108035-6015bb94-7ba7-11e8-9c8e-f78306d6341a.png)

Once selected, the list will update showing the 9 status items, as well as the ability to clear your status. To go back to the main list, the user can select click the "< back" link. 

![html5-sidebar-participant-dropdown-status](https://user-images.githubusercontent.com/1273169/42108181-cb37dfce-7ba7-11e8-9813-d541da0e6733.png)

Note: With this new direction, we'll be removing the set status button that current appears to the right of the share video button.

**Comment by oswaldoacauan** [comment]
Just a reminder to anyone who will be picking this up, the whole trinity (accessibility, mobile, keyboard nav) will make this task harder than it looks. GLHF (:

**Comment by oswaldoacauan** [comment]
@tylercopeland dont you think we can improve the labels for the (yourself) actions?

**Comment by oswaldoacauan** [comment]
another question is moving "Clear Status" out of the "Set Status" before it wasnt a possibility because we didn't want to add another button but now we can have another option
