### ISSUE TITLE
bbb-check incorrectly reporting that RTMP is not working

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#5791]
Installed `bbb-check` on the latest build of BigBlueButton 2.0-RC1, but it shows that RTMP isn't working

![image](https://user-images.githubusercontent.com/290351/42130412-664d36ac-7cb2-11e8-81c0-9ced80b9cde7.png)

which is incorrect as it does work.

**Comment by ffdixon** [comment]
Fixed in latest update

![image](https://user-images.githubusercontent.com/290351/42234398-69de5ed8-7ec2-11e8-9b78-1d9e8021aa98.png)

**Comment by ffdixon** [comment]
We are having another report of this in 2.0-RC7 when installed on EC2

  https://groups.google.com/d/msg/bigbluebutton-users/KJbQUf5CoSU/ESRee0CFAQAJ

**Comment by dcr18** [comment]
Any update on the issue?

**Comment by ffdixon** [comment]
No update at the moment, but we do plan to take a closer look as this is part of 2.0.

**Comment by ffdixon** [comment]
Just tried 2.0-RC8 on a clean server and the check looks good

![image](https://user-images.githubusercontent.com/290351/49090915-b68d5a80-f22c-11e8-9331-f8a55dce1e72.png)

What version of BigBlueButton are you running?

**Comment by dcr18** [comment]
BigBlueButton Server 2.0.0-beta (1029)

**Comment by ffdixon** [comment]
Closing as this was an issue related to the Flash client (the project has moved to an HTML5 client).
