### ISSUE TITLE
High volume of incoming chat leads to browser perf issues

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#5797]
Likely important - chat push notifications were enabled

**Comment by MaximKhlobystov** [comment]
Tested this with 3-4 users simultaneously typing. It slows down the client when chat notifications are on (for example, closing/opening public chat takes time). But with the chat notifications disabled, the slowness is visibly less significant.

**Comment by antobinary** [comment]
Merge remainder of this issue into #6053
