### ISSUE TITLE
Slide images don't show in the recording on mobile

### ISSUE THREAD

**Issue by capilkey** [bigbluebutton/bigbluebutton#5810]
When watching a recording on mobile the slide image aren't showing and all you see is the BigBlueButton logo. The rest of the recording appears to show as expected because I can see chat and hear the audio, but no big slides nor any slide thumbnails. When debugging through USB there's no unexpected errors or networking issues. The images show as being downloaded in the network tab. This was tested with the following recording, https://demo.bigbluebutton.org/playback/presentation/2.0/playback.html?meetingId=ffbfc4cc24428694e8b53a4e144f414052431693-1530278898111.

Tested with Android 8, Chrome 67 and Firefox 61.

**Comment by capilkey** [comment]
The issue was originally reported here, https://groups.google.com/d/msg/bigbluebutton-users/ACxhnXJ0FXg/2U_3BCuFCQAJ.

**Comment by ffdixon** [comment]
Fixed in the latest release of BigBlueButton 2.2-beta, see

  https://github.com/bigbluebutton/bigbluebutton/releases/tag/2.2-beta-23
