### ISSUE TITLE
Remove active and hover states on mobile devices

### ISSUE THREAD

**Issue by tylercopeland** [bigbluebutton/bigbluebutton#5815]
While using the HTML5 client on my mobile phone this afternoon, I noticed a few scenarios where the active state of a button stayed, even though I was interacting with other elements on the screen. 

I came across this after tapping the video button, closing the modal, tapping the emoji list and then closing the modal. Even though I was interacting with a new element, the video button suggests that it is still in an active state. (which it isn't). 

![img_6450](https://user-images.githubusercontent.com/1273169/42341517-4dc27d60-8061-11e8-8143-b700dd6ad655.PNG)

I also noticed the greyed out users list icon when I returned back to the main interface, which looks slightly disabled. 

![screen shot 2018-07-05 at 2 50 58 pm](https://user-images.githubusercontent.com/1273169/42342166-5bddc826-8063-11e8-8740-dafa99738751.png)

This had me thinking (since mobile apps don't have hover states), should we also be removing them on the HTML5 client on mobile? The same goes with active states.

**Comment by antobinary** [comment]
On mobile there's long-press, which simulates 'hover' and displays tooltip (if any)

**Comment by KDSBrowne** [comment]
I can't seem to reproduce this bug either.

**Comment by tylercopeland** [comment]
@KDSBrowne We've adjusted the button styles _(since I posted this issue)_, therefore it is safe to say we can close out this issue.
