### ISSUE TITLE
Remove space between chat input and the keyboard on mobile devices

### ISSUE THREAD

**Issue by tylercopeland** [bigbluebutton/bigbluebutton#5816]
![img_6448](https://user-images.githubusercontent.com/1273169/42342493-3e09e220-8064-11e8-84cd-9eaccdb4d7f9.PNG)

**Comment by vitormateusalmeida** [comment]
In my tests this problem happened on several websites. Whenever the keyboard is opened and the page is scrolled to the end, "overscroll" happens.
