### ISSUE TITLE
Make the list of whiteboard tools configurable

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#5826]
Currently we have "pencil", "text", "rectangle", etc tools in whiteboard.
Create a configuration in `settings*.json` that controls which tools are available - so that the palette is customizable.

For example:

```
whiteboardToolsForSinglePresenter': ['pencil', 'text'],
whiteboardToolsForMultiUser': ['rectangle'],
```

would cause multi-user whiteboard users to only see [and use] 'rectangle' tool. The actual presenter will be able to use 'pencil' and 'text' tools.

Keep both default values as the full list of whiteboard tools.

**Comment by oswaldoacauan** [comment]
This probably should be a meeting/join configuration and not a HTML5 config.
