### ISSUE TITLE
BBB repeating when creating group in course

### ISSUE THREAD

**Issue by norahalrumayh** [bigbluebutton/bigbluebutton#5837]
Hi,

I'm using Moodle version 3.5 and BBB version "2017101012", when creating a group in course and access BBB from Actvities block its shows duplicate result of activity as showing in screenshot. I've checked with student/teacher account as well and it showing same problem.
![capture](https://user-images.githubusercontent.com/41000232/42448869-59defa82-8387-11e8-851e-ed385dd4dd5e.PNG)

Best wishes,

**Comment by GhaziTriki** [comment]
This issue is related to the moodle plugin not to the BigBLueButton server. Please report it here https://github.com/blindsidenetworks/moodle-mod_bigbluebuttonbn/issues

**Comment by ffdixon** [comment]
@norahalrumayh Can you check with the latest version of the BigBlueButtonBN plugin and let us know if this is still an issue -- thanks!

https://moodle.org/plugins/pluginversions.php?plugin=mod_bigbluebuttonbn

**Comment by GhaziTriki** [comment]
We know multiple Moodle deployment and no one of them is reporting this issue.
