### ISSUE TITLE
maxParticipants parameter not correctly handler in create API call

### ISSUE THREAD

**Issue by GhaziTriki** [bigbluebutton/bigbluebutton#5843]
The number of allowed users to join handled as `maxParticipants` - 1` instead of `maxParticipants`. As example if a meeting is created with `maxParticipants` set to 1, no users will be allowed to join, if `maxParticipants` is to 2, only a single user will be allowed to join the conference.

This issue only occurs in 2.2 dev version.

**Comment by GhaziTriki** [comment]
Something might be incorrect in the following lines https://github.com/bigbluebutton/bigbluebutton/blob/v2.0.x-release/bigbluebutton-web/grails-app/controllers/org/bigbluebutton/web/controllers/ApiController.groovy#L485-L493

**Comment by GhaziTriki** [comment]
@pedrobmarin Does your PR fix the following issue I am describing?

```xml
<participantCount>119</participantCount>
<listenerCount>109</listenerCount>
<voiceParticipantCount>3</voiceParticipantCount>
<videoCount>1</videoCount>
<maxUsers>150</maxUsers>
<moderatorCount>2</moderatorCount>
```

As you see the `maxUsers` is 150 and I am not allowed to join the conference.
I see this in the logs:
`2019-12-23T20:30:29.287+03:00 DEBUG o.b.web.controllers.ApiController - JSON Errors [{"message":"The number of participants allowed for this meeting has been reached.","key":"maxParticipantsReached"}]
`

**Comment by pedrobmarin** [comment]
It does

Em seg, 23 de dez de 2019 14:34, Ghazi Triki <notifications@github.com>
escreveu:
