### ISSUE TITLE
Add 20px of spacing below private chat title / back button

### ISSUE THREAD

**Issue by tylercopeland** [bigbluebutton/bigbluebutton#5845]
Current implementation

<img width="305" alt="screen shot 2018-07-10 at 2 11 24 pm" src="https://user-images.githubusercontent.com/1273169/42529145-a3b4e972-844b-11e8-804e-74e501f81ce0.png">

Recommended implementation 

![screen shot 2018-07-10 at 2 11 53 pm](https://user-images.githubusercontent.com/1273169/42529148-a63e6d58-844b-11e8-9e29-be3b6f1f4791.png)

**Comment by jfsiebel** [comment]
The first item on #4903 have the same suggestion of this issue.
