### ISSUE TITLE
Restrict non-presenters in multi-user whiteboard to only pen tool

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#5850]
When tutoring very young users of BigBlueButton, when the presenter activates multi-user whiteobard the array of tool choices can be very confusing.

Add an option to config.xml

  onlyPenMUW="true"

that when true will restrict users (except the presenter) to only having the pen tool and not seeing any other choices.

**Comment by pedrobmarin** [comment]
Configurable https://github.com/bigbluebutton/bigbluebutton/pull/6168
