### ISSUE TITLE
DEV Environment：bigbluebutton-client build issue

### ISSUE THREAD

**Issue by pop6396** [bigbluebutton/bigbluebutton#5860]
I was trying to build the bigbluebutton-client with ant command when setting the dev environment. but I got the error as below:
Error: unable to load SWC playerglobal.swc: /root/dev/tools/apache-flex-sdk-4.13.0-bin/frameworks/libs/player/11.2/playerglobal.swc is not a SWC file.

Can you help me to fix this issue?
The steps refer to the Setup Development Environment page, thanks

**Comment by ffdixon** [comment]
Closing as this was an issue related to the Flash client (the project has moved to an HTML5 client).
