### ISSUE TITLE
Pepper Flash freezes on Linux Ubuntu when doing screenshare and changing screen dimensions

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#5891]

**Comment by prlanzarin** [comment]
A pending test is playing the RTMP stream in standalone/ordinary flash video player in a plain HTML to try to isolate the leak. That way we can try different versions of playerglobal and other flash decoders.

**Comment by ffdixon** [comment]
Closing as this was an issue related to the Flash client (the project has moved to an HTML5 client).
