### ISSUE TITLE
Locales not applied due to race condition

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#5892]

**Comment by antobinary** [comment]
![screenshot from 2018-07-20 15-16-10](https://user-images.githubusercontent.com/6312397/43020981-00f8ede0-8c30-11e8-8790-0cbabaddd12d.png)
On initial load [in FireFox] on server with bbb-html5 application, the UI does not update when en.json or another locale is pulled *on initial client load*

**Comment by BobakOftadeh** [comment]
![image](https://user-images.githubusercontent.com/32152296/43021829-16dc1c06-8c33-11e8-8fd6-199ced9607b3.png)

I am seeing this on chrome also, but userlist's labels are fine.
