### ISSUE TITLE
Need to bump API version number to 2.0 in BigBlueButton 2.0

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#5899]
We're running the latest build of BigBlueButton 2.0 on https://demo.bigbluebutton.org/, but the API version is still returning 1.1.

~~~
$ wget -O- -q https://demo.bigbluebutton.org/bigbluebutton/api; echo
<response><returncode>SUCCESS</returncode><version>1.1</version></response>
~~~

**Comment by ritzalam** [comment]
The api version is already 2.0. 

```
$ wget -O- -q https://dev2a.bigbluebutton.org/bigbluebutton/api; echo
<response><returncode>SUCCESS</returncode><version>2.0</version></response>
```

**Comment by ritzalam** [comment]
In `bigbluebutton.properties`

```
apiVersion=2.0
```

**Comment by prlanzarin** [comment]
Yeah, I remember bumping it here https://github.com/bigbluebutton/bigbluebutton/pull/5126

**Comment by ffdixon** [comment]
Clo

**Comment by ffdixon** [comment]
Need to confirm this value is updated to 2.0 on an upgrade.

**Comment by GhaziTriki** [comment]
Any `2.0-RC2` install will return version `2.0` when API is called.

**Comment by ffdixon** [comment]
Just need to test if this is true if upgrading from a 1.1 server.

**Comment by ffdixon** [comment]
Fixed.  

Added logic in the latest package for bbb-web to bump the API version from 1.1 to 2.0.
