### ISSUE TITLE
Undefined values in logClient

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#5920]
` Exception while invoking method 'logClient' TypeError: Cannot read property 'meetingId' of undefined`
`Exception while invoking method 'logClient' TypeError: Cannot set property 'validUser' of undefined`
...
at DDPCommon.MethodInvocation.logClient (imports/api/log-client/server/methods/logClient.js:10:36)

**Comment by antobinary** [comment]
`3f5778a……_js_resource=true:1 Error invoking Method 'logClient': Internal server error [500]` on login

**Comment by oswaldoacauan** [comment]
Probably introduced in #5903

**Comment by capilkey** [comment]
Adding the settings didn't cause the bug. The bug is just now showing up because the settings enabled the logging. The bug will be from #5808.

**Comment by MaximKhlobystov** [comment]
It was introduced here: https://github.com/bigbluebutton/bigbluebutton/pull/5808. I just went through the commits and checked.
