### ISSUE TITLE
bbb-webrtc-sfu: inactive

### ISSUE THREAD

**Issue by dingyuanyang** [bigbluebutton/bigbluebutton#5934]
root@broadcast:~# bbb-conf --status
red5: active
tomcat7: active
nginx: active
freeswitch: active
redis-server.service: active
bbb-apps-akka: active
bbb-transcode-akka: active
bbb-fsesl-akka: active
mongod: active
bbb-html5: active
bbb-webrtc-sfu: inactive
kurento-media-server: active

when I check ,I had this result:

root@broadcast:~# bbb-conf --check

BigBlueButton Server 2.0.0-beta (1256)
                    Kernel version: 4.4.0-127-generic
                      Distribution: Ubuntu 16.04.4 LTS (64-bit)
                            Memory: 4046 MB

/var/www/bigbluebutton/client/conf/config.xml (bbb-client)
  		Port test (tunnel): rtmp://10.0.0.27
                              red5: 10.0.0.27
              useWebrtcIfAvailable: true

/opt/freeswitch/etc/freeswitch/sip_profiles/external.xml (FreeSWITCH)
                         websocket: :5066
                    WebRTC enabled: true

/etc/nginx/sites-available/bigbluebutton (nginx)
                       server name: 10.0.0.27
                              port: 80, [::]:80
                    bbb-client dir: /var/www/bigbluebutton

/var/lib/tomcat7/webapps/bigbluebutton/WEB-INF/classes/bigbluebutton.properties (bbb-web)
                      bbb-web host: 10.0.0.27

/var/lib/tomcat7/webapps/demo/bbb_api_conf.jsp (API demos)
                               url: 10.0.0.27

/usr/share/red5/webapps/bigbluebutton/WEB-INF/red5-web.xml (red5)
                  voice conference: FreeSWITCH

/usr/local/bigbluebutton/core/scripts/bigbluebutton.yml (record and playback)
                     playback host: 10.0.0.27

/usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml (Kurento)
                        kurentoUrl: ws://10.0.0.27:8888/kurento
                         kurentoIp: 10.0.0.27 
                    localIpAddress: 10.0.0.27
               recordScreenSharing: true
                     recordWebcams: true

** Potential problems described below **
# Warning: The voice application may not have registered with the sip server.
#   Try running: 
#
#      sudo bbb-conf --clean
#

# Warning: The API demos are installed and accessible from:
#
#    http://10.0.0.27/demo/demo1.jsp
#
# These API demos allow anyone to access your server without authentication
# to create/manage meetings and recordings. They are for testing purposes only.
# If you are running a production system, remove them by running:
#
#    sudo apt-get purge bbb-demo

# Error: Detected some processes have not started correctly
#
#   bbb-webrtc-sfu: inactive

**Comment by ffdixon** [comment]
Can you try updating to the latest build of BigBlueButton 2.0 (which at the time of this writing is 2.0-RC2), see  http://docs.bigbluebutton.org/install/install.html#upgrading-to-latest-build-of-bigbluebutton-20
