### ISSUE TITLE
First Flash client user in the meeting takes over presentation [pod] control

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#5941]
First Flash client user in the meeting takes over presentation [pod] control from current HTML5 moderator+presenter

![happens](https://user-images.githubusercontent.com/6312397/43467291-67b8b4a2-94af-11e8-8e44-8b510ad16ae0.gif)

Likely caused by https://github.com/bigbluebutton/bigbluebutton/blob/v2.2-dev/bigbluebutton-client/src/org/bigbluebutton/modules/present/ui/views/PresentationWindow.mxml#L280-L283

Desired behavior - presenter control is only taken over if there is no current presenter - i.e. only viewers in the meeting

**Comment by capilkey** [comment]
This isn't actually a Flash client problem. The lines you noted are the ones that make the automatic switch, but if you check the conditions it will only activate if no user is assigned to be the pod presenter. The actual fix would be for the HTML5 server to take over pod presenter if one isn't assigned when a moderator logs in.

**Comment by Tainan404** [comment]
Could not this be an akka issue? because if you are a html5 presenter and leave the meeting, the next user is given the role of presenter, but can not interact with the presentation

![peek 2018-08-03 10-34](https://user-images.githubusercontent.com/15806883/43645631-e4ccb65e-9708-11e8-8964-cbea19b485cf.gif)

**Comment by capilkey** [comment]
A change could also be made in akka-apps. There's a couple of different things that could be done, some good, some bad. If the automatic presenter switch also chained to the pod it would probably be enough without interfering with other things.
