### ISSUE TITLE
Html 5 Client : nginx 404 error code

### ISSUE THREAD

**Issue by MohamedBRH** [bigbluebutton/bigbluebutton#5944]
Hi everyone,
I am facing problem with html 5 client setup, I followed the documentation instructions but I think I missed somthing I don't know what it is.
here what I have done :
I installed mongodb : v4.0.0
nodejs : v8.11.3
npm : v5.6.0
sudo apt-get install -y bbb-html5
sudo bbb-conf --restart
sudo apt-get update 
sudo apt-get dist-upgrade 

I checked my server status with "sudo  bbb-conf --check" here the result :
![capture](https://user-images.githubusercontent.com/26926657/43474833-d650436c-94eb-11e8-965a-97793669c9fe.PNG)

everythings seems to work well, I didn't use a firewall or any security layer
![capture1](https://user-images.githubusercontent.com/26926657/43474933-24fefa1c-94ec-11e8-925f-5b597aa474ae.PNG)

![capture2](https://user-images.githubusercontent.com/26926657/43474960-3c97af34-94ec-11e8-8993-57d5ea0dcbd2.PNG)

I tried with the demo api the same error occurs

![capture](https://user-images.githubusercontent.com/26926657/43475087-8914345e-94ec-11e8-8ae8-3d6125c5e5b2.PNG)
**I need your help please**

**Comment by antobinary** [comment]
Follows from thread https://groups.google.com/forum/#!topic/bigbluebutton-setup/KzUQjzI1WYQ

**Comment by Jarvil** [comment]
did you see your mongo process running using ps aux command? i've to edit /usr/share/meteor/bundle/mongo-ramdisk.conf and set cacheSizeGB: 1 to get it start.

**Comment by headria** [comment]
@MohamedBRH it's about you mongdb what I do is dwongrade my mongodb version to 3.4 and it's working.
