### ISSUE TITLE
Add help button in Options menu to link to video tutorials for BBB

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#5962]
Linking to `https://bigbluebutton.org/videos/`
Use icon `?`.
Place it immediately under 'About'.
Add an option in `settings-production.json` and `settings-development.json` to not show the help button. Keep it displayed by default.

**Comment by zhu** [comment]
The server-side setting of help URL did not implement. And what happen when I join with a config.xml file that setup <help url="some where"/>?

**Comment by zhu** [comment]
setup `<help url="some where"/>`

**Comment by capilkey** [comment]
@zhu: The HTML5 client doesn't use config.xml so making changes to it will have no effect. The help URL is not configurable in 2.0. I opened an issue for it a couple of months ago, but it was too late to get it into 2.0 (https://github.com/bigbluebutton/bigbluebutton/issues/6029). I've tagged it for 2.2 and hopefully it can get in then.
