### ISSUE TITLE
SetIP overwrites Chrome Screenshare extension URL in config.xml

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#5967]
When we run `bbb-conf --setip xxxxxx` the link to the Chrome Screenshare extension changes from
`https://chrome.google.com/webstore/detail/bigbluebutton-screenshare/akgoaoikmbmhcopjgakkcepdgdgkjfbc`
to
`https://demo.bigbluebutton.org/webstore/detail/bigbluebutton-screenshare/akgoaoikmbmhcopjgakkcepdgdgkjfbc` - which is incorrect

Lilkely this is due to loose domain matching. The url for the extension should not change

**Comment by GhaziTriki** [comment]
It seems like this issue was fixed in the following commit https://github.com/bigbluebutton/bigbluebutton/commit/f982efa82387f3b33e23c9bbe28c6d73bc1f0831

**Comment by ffdixon** [comment]
Hi Ghazi,

Could you do a quick test with the latest version of 2.0 and confirm the fix works -- thanks!
