### ISSUE TITLE
Webcams items are overlapping the webcam dropdowns in mobile.

### ISSUE THREAD

**Issue by Tainan404** [bigbluebutton/bigbluebutton#5976]
To reproduce it:

- Join a html5 client and a html5 client in a mobile device.
- Share webcam on both.
- Opens the drop-down menu for the first webcam shown in the list

![fdgsgdsfgdsfgdsf](https://user-images.githubusercontent.com/15806883/44093349-b24868d2-9fa9-11e8-8d19-45a7dae303aa.png)

**Comment by prlanzarin** [comment]
Seems to happen on desktop too with an overlap over the presentation on swap mode.
![overlap](https://user-images.githubusercontent.com/4529051/44104668-d702fafe-9fc5-11e8-9944-35c691d1af27.png)

**Comment by ffdixon** [comment]
@Tainan404 Is this still an issue in the latest builds of the HTML5 client?

**Comment by Tainan404** [comment]
Hey @ffdixon, I tested it on the latest version and it doesn't happen anymore.
