### ISSUE TITLE
Update the font size of the text found in chat input to match the text that's display in the chat area

### ISSUE THREAD

**Issue by tylercopeland** [bigbluebutton/bigbluebutton#5980]
Text found in the chat area (after it's rendered) is 14.4px. In the chat input, the text is 16px. 

![screen shot 2018-08-14 at 2 25 32 pm](https://user-images.githubusercontent.com/1273169/44110699-69755a1e-9fce-11e8-8018-c187604cb9f8.png)

**Comment by oswaldoacauan** [comment]
For mobile we need at least `16px` (1rem) otherwise we will bring back the issue solved in #5748.
