### ISSUE TITLE
Update the icon used to open the participants list to the "chat" icon

### ISSUE THREAD

**Issue by tylercopeland** [bigbluebutton/bigbluebutton#5985]

**Comment by ffdixon** [comment]
Based on feedback from early users, they didn't think that a student would understand that chat was behind the user icon.  Most applications put chat behind a chat icon.

Ultimately the panel will have many functions, so one icon isn’t going to cover all of them (user icon, chat icon, etc.).  For the first release of the HTML5 client, we are targeting students (viewers), so all they really care about is chat

**Comment by oswaldoacauan** [comment]
Probably should change the behavior then, since right now that button opens the user-list only.

**Comment by antobinary** [comment]
I agree that the behavior will need to be changed. Currently the userlist icon is used on the button toggling the user list. Chat happens to be accessed via user list. If we change the icon to be 'chat' related, we need a way to access userlist from chat OR we will need to always show both userlist and chat together (tough on mobile)

**Comment by tylercopeland** [comment]
@ffdixon  I'm thinking through this experience a little more and wondering if the icon change is even needed. 

Right now we have the users list open by default, with "Public Chat" at the very top. With large sessions, we often see Public Chat being quite active, which means participants will also see the chat counter within the first few seconds or minutes of interacting with BigBlueButton. Furthermore, if they decide to click the "user icon" to close the sidebar, they'll know to click that button again to open it up. 

Lastly, if a participant has the sidebar closed, notifications for chat appear in the top right-hand corner providing participants with a "one-click" option of opening the sidebar and engaging with others through chat. 

Also, if we think about what is listed in the sidebar it's everything to do with engaging with the user, chat, direct messages, and future items such as breakout rooms, notes, etc. Therefore, having the user icon is more accurate than the chat icon.  

cc @oswaldoacauan  @antobinary

**Comment by tylercopeland** [comment]
@ffdixon was this feedback provided based on interacting with the HTML5 on a mobile device?

**Comment by ffdixon** [comment]
The feedback was for a mobile device.  

> If we change the icon to be 'chat' related, we need a way to access userlist from chat OR we will need to always show both userlist and chat together (tough on mobile)

I don't think we need to change the functionality.  Once you open the user's list you'll see public chat at the top, so it's one more click.

The heart of the problem is that most users are familiar with the chat icon for finding chat (this is how it looks on skype).  On a mobile device, we currently indicate unread chat messages with a red dot next to a user icon.

![image](https://user-images.githubusercontent.com/290351/44198921-97196880-a13a-11e8-88be-c43efd928b82.png)

For the first release of the HTML5 client, which targets viewers, pretty much everything in the user's list is about chat.  

> Lastly, if a participant has the sidebar closed, notifications for chat appear in the top right-hand corner providing participants with a "one-click" option of opening the sidebar and engaging with others through chat.

Currently, we're not enabling the toast messages by default, but we could.  That would go a ways to making it clear.

Another option is instead of a red dot, we could make it slightly bigger and in the shape of a chat bubble.

**Comment by tylercopeland** [comment]
@ffdixon The simple fix is to update the icon to use the chat icon, but when individuals see a "chat icon" they will expect to see a familiar experience, a conversation thread followed by an input field for you to take part in the conversation.

I think the best approach is to come up with an icon that combines the two experience. We are going to need to come up with one soon after the initial release anyways, so it's best to solve this problem now, rather than waiting.

Figuring out a way to have toast messages on by default would be great, but at the same time, we need to think through the flow further. In large sessions, there is often a lot of activity in chat, resulting in several toasts taking up a lot of the screen real estate on smaller devices. One idea would be to display 1-2 toats (on smaller devices) and stacking the rest creating a grouping of toats. 

The following are a few approaches I've to explore for an updated icon.

**Option 1** 
Add a counter to the red indicator on the participant's icon

![screen shot 2018-08-17 at 3 11 42 pm](https://user-images.githubusercontent.com/1273169/44284509-f2795280-a22f-11e8-8b7c-ea758566063b.png)

**Option 2**  
Same experience as #1, but a "chat icon" is included" 

![screen shot 2018-08-17 at 3 17 11 pm](https://user-images.githubusercontent.com/1273169/44284701-a4b11a00-a230-11e8-889c-80b5d1293360.png)

**Option 3**
Participants icon, a red indicator with a chat icon within it. 

![screen shot 2018-08-17 at 3 17 46 pm](https://user-images.githubusercontent.com/1273169/44284735-c3afac00-a230-11e8-89bb-b80e2994d2a0.png)

**Option 4** 
Combine participants and chat icon

![screen shot 2018-08-17 at 3 20 08 pm](https://user-images.githubusercontent.com/1273169/44284836-18ebbd80-a231-11e8-844d-38388769f4c4.png)

**Option 5**
Replace the red circle with a red filled chat icon as the chat indicator. 

![screen shot 2018-08-17 at 3 23 57 pm](https://user-images.githubusercontent.com/1273169/44284979-96173280-a231-11e8-9b16-e5e8817c6f1b.png)

I'm going to stop there for now to get some early feedback.

**Comment by oswaldoacauan** [comment]
I liked the 3rd and 4th option.

**Comment by antobinary** [comment]
I like very much Option 2.
I think it's important to show the counter of unread messages. Mostly because if I see it growing I will be more tempted to go look what's new. Simply having it in on/off unread messages toggle is not enough in my opinion.
In terms of location of the speech/chat 'bubble' - it looks better when higher than the head of the user-icon like in Option 2
Thanks @tylercopeland for providing alternatives. Let's see what we all agree on.

**Comment by pedrobmarin** [comment]
Hey guys, did we decided on this one already? Is the notification we have today is a result from this thread? I'm sure I made things a like more complicated than this when the shared notes notification entered this icon too...

**Comment by tylercopeland** [comment]
@pedrobmarin, at this time, I don't see a need to change the icon to a "chat" icon. If we were to change it, I would recommend using a generate menu icon as the sidebar contains many features and pieces of information.

**Comment by antobinary** [comment]
Let's reopen if needed.
