### ISSUE TITLE
Why do I always get this: "Not running:  tomcat7 or grails"?

### ISSUE THREAD

**Issue by afuno** [bigbluebutton/bigbluebutton#5987]
I have already reinstalled the BBB several times. All the time, there are some problems.

During the installation, there are no errors, but after... Something so it will break.

Specifically, now it is about this team:

```
sudo apt-get install bigbluebutton
```

Installation was successful. But after it you ask to execute this command:

```
sudo bbb-conf --restart
```

Ok. I do it and get it:

```
Restarting BigBlueButton 2.0.0-RC3 ...
Stopping BigBlueButton
Starting BigBlueButton



** Potential problems described below **
# Not running:  tomcat7 or grails
# Warning: The installed ffmpeg version '2.8.14-0ubuntu0.16.04.1' is not recommended.
# Recommend you update to the 4.0.x version of ffmpeg.  To upgrade, do the following
#
#        sudo apt-get install software-properties-common
#        sudo add-apt-repository ppa:jonathonf/ffmpeg-4
#        sudo apt-get update
#        sudo apt-get dist-upgrade
#

....................
# Error: Could not connect to the configured hostname/IP address
#
#    http://111.222.333.444/
#
# If your BigBlueButton server is behind a firewall, see FAQ.
```

As for ffmpeg, everything is clear. 

Speech here exclusively about this:

```
# Not running:  tomcat7 or grails
```

Why is this happening? Sometimes this problem does not exist. Sometimes it is.

**Comment by chineseedu** [comment]
I had the same problem when installing on vps vultr.
You should switch to digitalocean and do not encounter any errors.
linode, add the dns reverse step
googlevps, amazon then open the firewall is ok
Demo I use to teach online [https://chinese.com.vn]
