### ISSUE TITLE
Dynamic config for HTML5

### ISSUE THREAD

**Issue by esaribeiro** [bigbluebutton/bigbluebutton#5989]
Hello!
I was looking for this information in other issues and docs, but did not find it ...

Is it possible to call the HTML5 room dynamically like the Flash version?
For example, I'm trying to apply "forceListenOnly = true" to some cases (users or rooms) and would not like to set it true by default.

If possible, could you show me an example, please?

In addition, why restriction applied to Flash version by dynamic config do not propagate to HTML5?

**Comment by antobinary** [comment]
This is not possible in the HTML5 client part of BigBlueButton v2.0.x
The feature is one of the key improvements under construction for the following iteration of the HTML5 client

**Comment by esaribeiro** [comment]
Thanks, @antobinary 
I'll wait for this feature...

**Comment by rriscado** [comment]
I really need this dynamic configuration. 
Do you have a date to deliver this feature?
