### ISSUE TITLE
Update the "more messages below" logic in the chat so that it's only shown when you've scrolled up and a new message has come in

### ISSUE THREAD

**Issue by tylercopeland** [bigbluebutton/bigbluebutton#5995]

**Comment by ffdixon** [comment]
@tylercopeland Is this still an issue in the latest build of BigBlueButton HTML5 in 2.2-beta?

**Comment by tylercopeland** [comment]
@ffdixon I just tested this experience in HTML5 in 2.2-beta and I can confirm this is no longer an issue. I will close out this issue.
