### ISSUE TITLE
Broken transition between ListenOnly and Microphone audio in Chrome

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#5997]
If you join audio in listenOnly mode and hang up immediately, then right away attempt to join with microphone, you will not be able to join

**Comment by ffdixon** [comment]
@antobinary Just checking if this is still an issue in 2.2-beta?

**Comment by JustinMogel** [comment]
Tested this on 2.3-alpha-8 1511 with Chrome Version 89.0.4389.90 
after listen only mode i hung up and started with microphone without any issue (after microphone test)

**Comment by basisbit** [comment]
seems to be fixed in the mean time, can not reproduce it either. Thanks @JustinMogel for checking this old issue!
