### ISSUE TITLE
Enable multiuser whiteboard by default

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#6003]
Add a parameter in config.xml to enable multiuser whiteboard by default.

**Comment by ffdixon** [comment]
Implemented in BigBlueButton 2.0-RC5, see 

   http://docs.bigbluebutton.org/overview/overview.html#start-all-sessions-with-multi-user-whiteboard-enabled

**Comment by edzus** [comment]
@ffdixon The provided link is broken.
Can you please point to the docs where this option is available in the latest version of BBB?
