### ISSUE TITLE
sudo apt update return this message

### ISSUE THREAD

**Issue by AhmadNosratian** [bigbluebutton/bigbluebutton#6008]
sudo apt-get update
Get:1 http://security.ubuntu.com/ubuntu xenial-security InRelease [107 kB]
Hit:2 http://us.archive.ubuntu.com/ubuntu xenial InRelease
Hit:3 http://us.archive.ubuntu.com/ubuntu xenial-updates InRelease
Hit:4 http://us.archive.ubuntu.com/ubuntu xenial-backports InRelease
Ign:5 https://ubuntu.bigbluebutton.org/xenial-200 bigbluebutton-xenial InRelease
Ign:6 https://ubuntu.bigbluebutton.org/xenial-200 bigbluebutton-xenial Release
Ign:7 https://ubuntu.bigbluebutton.org/xenial-200 bigbluebutton-xenial/main amd6                                                                                        4 Packages
Ign:8 https://ubuntu.bigbluebutton.org/xenial-200 bigbluebutton-xenial/main i386                                                                                         Packages
Ign:9 https://ubuntu.bigbluebutton.org/xenial-200 bigbluebutton-xenial/main all                                                                                         Packages
Ign:10 https://ubuntu.bigbluebutton.org/xenial-200 bigbluebutton-xenial/main Tra                                                                                        nslation-en_US
Ign:11 https://ubuntu.bigbluebutton.org/xenial-200 bigbluebutton-xenial/main Tra                                                                                        nslation-en
99% [Working]
Ign:7 https://ubuntu.bigbluebutton.org/xenial-200 bigbluebutton-xenial/main amd64 Packages
Ign:8 https://ubuntu.bigbluebutton.org/xenial-200 bigbluebutton-xenial/main i386 Packages
Ign:9 https://ubuntu.bigbluebutton.org/xenial-200 bigbluebutton-xenial/main all Packages
Ign:10 https://ubuntu.bigbluebutton.org/xenial-200 bigbluebutton-xenial/main Translation-en_US
Ign:11 https://ubuntu.bigbluebutton.org/xenial-200 bigbluebutton-xenial/main Translation-en
Ign:7 https://ubuntu.bigbluebutton.org/xenial-200 bigbluebutton-xenial/main amd64 Packages
Ign:8 https://ubuntu.bigbluebutton.org/xenial-200 bigbluebutton-xenial/main i386 Packages
Ign:9 https://ubuntu.bigbluebutton.org/xenial-200 bigbluebutton-xenial/main all Packages
Ign:10 https://ubuntu.bigbluebutton.org/xenial-200 bigbluebutton-xenial/main Translation-en_US
Ign:11 https://ubuntu.bigbluebutton.org/xenial-200 bigbluebutton-xenial/main Translation-en
Ign:7 https://ubuntu.bigbluebutton.org/xenial-200 bigbluebutton-xenial/main amd64 Packages
99% [Working]^L
Ign:8 https://ubuntu.bigbluebutton.org/xenial-200 bigbluebutton-xenial/main i386 Packages
Ign:9 https://ubuntu.bigbluebutton.org/xenial-200 bigbluebutton-xenial/main all Packages
99% [Working]Ign:9 https://ubuntu.bigbluebutton.org/xenial-200 bigbluebutton-xenial/main all Packages
Ign:10 https://ubuntu.bigbluebutton.org/xenial-200 bigbluebutton-xenial/main Translation-en_US
Ign:11 https://ubuntu.bigbluebutton.org/xenial-200 bigbluebutton-xenial/main Translation-en
Ign:7 https://ubuntu.bigbluebutton.org/xenial-200 bigbluebutton-xenial/main amd64 Packages
Ign:8 https://ubuntu.bigbluebutton.org/xenial-200 bigbluebutton-xenial/main i386 Packages
Ign:9 https://ubuntu.bigbluebutton.org/xenial-200 bigbluebutton-xenial/main all Packages
Ign:10 https://ubuntu.bigbluebutton.org/xenial-200 bigbluebutton-xenial/main Translation-en_US
Ign:11 https://ubuntu.bigbluebutton.org/xenial-200 bigbluebutton-xenial/main Translation-en
Err:7 https://ubuntu.bigbluebutton.org/xenial-200 bigbluebutton-xenial/main amd64 Packages
  gnutls_handshake() failed: The TLS connection was non-properly terminated.
Ign:8 https://ubuntu.bigbluebutton.org/xenial-200 bigbluebutton-xenial/main i386 Packages
Ign:9 https://ubuntu.bigbluebutton.org/xenial-200 bigbluebutton-xenial/main all Packages
Ign:10 https://ubuntu.bigbluebutton.org/xenial-200 bigbluebutton-xenial/main Translation-en_US
Ign:11 https://ubuntu.bigbluebutton.org/xenial-200 bigbluebutton-xenial/main Translation-en
Fetched 107 kB in 32min 16s (55 B/s)
Reading package lists... Done
W: The repository 'https://ubuntu.bigbluebutton.org/xenial-200 bigbluebutton-xenial Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: Failed to fetch https://ubuntu.bigbluebutton.org/xenial-200/dists/bigbluebutton-xenial/main/binary-amd64/Packages  gnutls_handshake() failed: The TLS connection was non-properly terminated.
E: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by ffdixon** [comment]
Hi Ahmad,

The problem is here

> Err:7 https://ubuntu.bigbluebutton.org/xenial-200 bigbluebutton-xenial/main amd64 Packages
gnutls_handshake() failed: The TLS connection was non-properly terminated.

Can you try running the `sudo apt-get update` and let us know if it works.

**Comment by AhmadNosratian** [comment]
@ffdixon 

it return the same error

**Comment by ffdixon** [comment]
Can you run the command

~~~
 wget -O- -q https://ubuntu.bigbluebutton.org/xenial-200/dists/bigbluebutton-xenial/main/binary-amd64/Packages
~~~

and let us know if you get an error.  Can you also post the output of the file `/etc/apt/sources.list.d/bigbluebutton.list`.

**Comment by AhmadNosratian** [comment]
deb https://ubuntu.bigbluebutton.org/xenial-200/ bigbluebutton-xenial main

the output of the file  /etc/apt/sources.list.d/bigbluebutton.list

**Comment by ffdixon** [comment]
What was the output of the wget command -- did it return an error or print out the contents of the `Packages` file?

**Comment by AhmadNosratian** [comment]
it print out the contents of the packages

**Comment by AhmadNosratian** [comment]
@ffdixon 
why it cant get that repository?

**Comment by AhmadNosratian** [comment]
sudo apt-get update
Hit:1 http://archive.ubuntu.com/ubuntu xenial InRelease
Get:2 http://security.ubuntu.com/ubuntu xenial-security InRelease [107 kB]
Hit:3 http://us.archive.ubuntu.com/ubuntu xenial InRelease
Get:4 http://us.archive.ubuntu.com/ubuntu xenial-updates InRelease [109 kB]
Get:5 http://us.archive.ubuntu.com/ubuntu xenial-backports InRelease [107 kB]
Get:6 http://us.archive.ubuntu.com/ubuntu xenial-updates/main amd64 Packages [838 kB]
Get:7 http://us.archive.ubuntu.com/ubuntu xenial-updates/main i386 Packages [757 kB]
Get:8 http://us.archive.ubuntu.com/ubuntu xenial-updates/universe amd64 Packages [678 kB]
Get:9 http://us.archive.ubuntu.com/ubuntu xenial-updates/universe i386 Packages [619 kB]
Ign:10 https://ubuntu.bigbluebutton.org/xenial-200 bigbluebutton-xenial InRelease
Ign:11 https://ubuntu.bigbluebutton.org/xenial-200 bigbluebutton-xenial Release
Ign:12 https://ubuntu.bigbluebutton.org/xenial-200 bigbluebutton-xenial/main amd64 Packages
Ign:13 https://ubuntu.bigbluebutton.org/xenial-200 bigbluebutton-xenial/main i386 Packages
Ign:14 https://ubuntu.bigbluebutton.org/xenial-200 bigbluebutton-xenial/main all Packages
Ign:15 https://ubuntu.bigbluebutton.org/xenial-200 bigbluebutton-xenial/main Translation-en_US
Ign:16 https://ubuntu.bigbluebutton.org/xenial-200 bigbluebutton-xenial/main Translation-en
Ign:12 https://ubuntu.bigbluebutton.org/xenial-200 bigbluebutton-xenial/main amd64 Packages
Ign:13 https://ubuntu.bigbluebutton.org/xenial-200 bigbluebutton-xenial/main i386 Packages
Ign:14 https://ubuntu.bigbluebutton.org/xenial-200 bigbluebutton-xenial/main all Packages
Ign:15 https://ubuntu.bigbluebutton.org/xenial-200 bigbluebutton-xenial/main Translation-en_US
Ign:16 https://ubuntu.bigbluebutton.org/xenial-200 bigbluebutton-xenial/main Translation-en
Ign:12 https://ubuntu.bigbluebutton.org/xenial-200 bigbluebutton-xenial/main amd64 Packages
Ign:13 https://ubuntu.bigbluebutton.org/xenial-200 bigbluebutton-xenial/main i386 Packages
Ign:14 https://ubuntu.bigbluebutton.org/xenial-200 bigbluebutton-xenial/main all Packages
Ign:15 https://ubuntu.bigbluebutton.org/xenial-200 bigbluebutton-xenial/main Translation-en_US
Ign:16 https://ubuntu.bigbluebutton.org/xenial-200 bigbluebutton-xenial/main Translation-en
Ign:12 https://ubuntu.bigbluebutton.org/xenial-200 bigbluebutton-xenial/main amd64 Packages
Ign:13 https://ubuntu.bigbluebutton.org/xenial-200 bigbluebutton-xenial/main i386 Packages
Ign:14 https://ubuntu.bigbluebutton.org/xenial-200 bigbluebutton-xenial/main all Packages
Ign:15 https://ubuntu.bigbluebutton.org/xenial-200 bigbluebutton-xenial/main Translation-en_US
Ign:16 https://ubuntu.bigbluebutton.org/xenial-200 bigbluebutton-xenial/main Translation-en
Ign:12 https://ubuntu.bigbluebutton.org/xenial-200 bigbluebutton-xenial/main amd64 Packages
Ign:13 https://ubuntu.bigbluebutton.org/xenial-200 bigbluebutton-xenial/main i386 Packages
Ign:14 https://ubuntu.bigbluebutton.org/xenial-200 bigbluebutton-xenial/main all Packages
Ign:15 https://ubuntu.bigbluebutton.org/xenial-200 bigbluebutton-xenial/main Translation-en_US
Ign:16 https://ubuntu.bigbluebutton.org/xenial-200 bigbluebutton-xenial/main Translation-en
Err:12 https://ubuntu.bigbluebutton.org/xenial-200 bigbluebutton-xenial/main amd64 Packages
  gnutls_handshake() failed: The TLS connection was non-properly terminated.
Ign:13 https://ubuntu.bigbluebutton.org/xenial-200 bigbluebutton-xenial/main i386 Packages
Ign:14 https://ubuntu.bigbluebutton.org/xenial-200 bigbluebutton-xenial/main all Packages
Ign:15 https://ubuntu.bigbluebutton.org/xenial-200 bigbluebutton-xenial/main Translation-en_US
Ign:16 https://ubuntu.bigbluebutton.org/xenial-200 bigbluebutton-xenial/main Translation-en
Fetched 3,215 kB in 32min 17s (1,659 B/s)
Reading package lists... Done
W: The repository 'https://ubuntu.bigbluebutton.org/xenial-200 bigbluebutton-xenial Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: Failed to fetch https://ubuntu.bigbluebutton.org/xenial-200/dists/bigbluebutton-xenial/main/binary-amd64/Packages  gnutls_handshake() failed: The TLS connection was non-properly terminated.
E: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by djoudi** [comment]
i have the same problem

**Comment by ffdixon** [comment]
Can you try the command

~~~
wget -O- -q https://ubuntu.bigbluebutton.org/xenial-200/dists/bigbluebutton-xenial/main/binary-amd64/Packages
~~~

and let us know if it gives you an error.  Also, are you behind a proxy?

**Comment by hamidaspnet** [comment]
Hi ffdixon.
I have the same issue! and your approach did not fix that!!!

**Comment by ffdixon** [comment]
Hi @hamidaspnet 

The approach was not a fix but rather an attempt to get more information from the previous poster.  

What was the output of

~~~
wget https://ubuntu.bigbluebutton.org/xenial-200/dists/bigbluebutton-xenial/main/binary-amd64/Packages 
~~~

Here's what you should see.  Do you get a similar output?

~~~
$ wget https://ubuntu.bigbluebutton.org/xenial-200/dists/bigbluebutton-xenial/main/binary-amd64/Packages 
--2019-02-12 08:33:21--  https://ubuntu.bigbluebutton.org/xenial-200/dists/bigbluebutton-xenial/main/binary-amd64/Packages
Resolving ubuntu.bigbluebutton.org (ubuntu.bigbluebutton.org)... 23.253.201.74
Connecting to ubuntu.bigbluebutton.org (ubuntu.bigbluebutton.org)|23.253.201.74|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 179821 (176K) [application/octet-stream]
Saving to: ‘Packages’

Packages                                      100%[==============================================================================================>] 175.61K  --.-KB/s    in 0.07s   

2019-02-12 08:33:21 (2.46 MB/s) - ‘Packages’ saved [179821/179821]
~~~

This will tell us if your Ubuntu computer is able to directly access one of the files via HTTPS (which was the previous poster's error).

If that works, what is the output of

~~~
sudo apt-get update
sudo apt-get dist-upgrade
~~~

**Comment by hamidaspnet** [comment]
Hi [ffdixon].
output:
Ign:10 http://ppa.launchpad.net/rmescandon/yq/ubuntu xenial/main amd64 Packages
Ign:11 http://ppa.launchpad.net/rmescandon/yq/ubuntu xenial/main Translation-en
Err:8 http://ppa.launchpad.net/jonathonf/ffmpeg-4/ubuntu xenial/main amd64 Packages
  Could not connect to ppa.launchpad.net:80 (91.189.95.83), connection timed out
Err:9 http://ppa.launchpad.net/jonathonf/ffmpeg-4/ubuntu xenial/main Translation-en
  Unable to connect to ppa.launchpad.net:http:
Err:10 http://ppa.launchpad.net/rmescandon/yq/ubuntu xenial/main amd64 Packages
  Unable to connect to ppa.launchpad.net:http:
Err:11 http://ppa.launchpad.net/rmescandon/yq/ubuntu xenial/main Translation-en
  Unable to connect to ppa.launchpad.net:http:
Fetched 361 kB in 2min 16s (2,649 B/s)
Reading package lists... Done
W: Failed to fetch http://ppa.launchpad.net/jonathonf/ffmpeg-4/ubuntu/dists/xenial/main/binary-amd64/Packages  Could not connect to ppa.launchpad.net:80 (91.189.95.83), connection timed out
W: Failed to fetch http://ppa.launchpad.net/jonathonf/ffmpeg-4/ubuntu/dists/xenial/main/i18n/Translation-en  Unable to connect to ppa.launchpad.net:http:
W: Failed to fetch http://ppa.launchpad.net/rmescandon/yq/ubuntu/dists/xenial/main/binary-amd64/Packages  Unable to connect to ppa.launchpad.net:http:
W: Failed to fetch http://ppa.launchpad.net/rmescandon/yq/ubuntu/dists/xenial/main/i18n/Translation-en  Unable to connect to ppa.launchpad.net:http:
W: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by ffdixon** [comment]
Can you post the output of the command

~~~
cat /etc/apt/sources.list.d/jonathonf-ubuntu-ffmpeg-4-xenial.list
~~~

**Comment by ffdixon** [comment]
Closing as no response from this user.

**Comment by Alexsandrit2007** [comment]
wget https://ubuntu.bigbluebutton.org/xenial-200/dists/bigbluebutton-xenial/main/binary-amd64/Packages 
--2020-04-08 01:10:09--  https://ubuntu.bigbluebutton.org/xenial-200/dists/bigbluebutton-xenial/main/binary-amd64/Packages
Resolving ubuntu.bigbluebutton.org (ubuntu.bigbluebutton.org)... 167.99.180.121
Connecting to ubuntu.bigbluebutton.org (ubuntu.bigbluebutton.org)|167.99.180.121|:443... connected.
Unable to establish SSL connection.
