### ISSUE TITLE
No audio output with Html5 2.0rc4 client on iOS 11.4.1

### ISSUE THREAD

**Issue by timvdp** [bigbluebutton/bigbluebutton#6017]
Hello, 

I have the issue with a brand new Bbb server running 2.0rc4 (I also tried on test.bigbluebutton.org).
I get no sound output when joining the meeting with the Html5 client on my iPhone running iOS 11.4.1.
Mic is working (other clients can hear the iPhone). 
In the "Echo dialog", it says there is no sound output (see screenshot). 

![image](https://user-images.githubusercontent.com/3727399/44758934-217fa600-ab05-11e8-94a7-61278dd9e008.png)

When I click the 'Play a sound' button, I can hear the sound.

Can I provide more information to debug? 

Thanks for your help,
Tim

**Comment by antobinary** [comment]
Hi @timvdp ,

We noticed this issue a couple days ago and have been working on it since. Addressing it is very high on the priority list for the HTML5 client. No need for more information from you at this point as we are also able to reproduce it.

Best regards,
Anton Georgiev

**Comment by antobinary** [comment]
Are you able to hear the audio if you plugged in a headset?

**Comment by timvdp** [comment]
For some unknown reasons it seems to work on my phone now. When I join a meeting, it always fails one or twice (while connecting to the Echo server I get an Error could not connect, try again) then it connects to the audio. When I was testing with my phone, activating the camera seemed to help get the audio.

I tried this evening with my wife's phone (iPhone 6S with last iOS version) and I could not get it to work with or without headset (or by activating the camera). 

FYI, I upgraded to RC5 this week.

**Comment by ffdixon** [comment]
We're narrowing down the issue to the ipv6 ICE candidate, which you likely have on an iPhone if it's on a cellular network.  In contrast, when you connect your iPhone to a wireless network (such as a home network), you may get an ipv4 address.

Can you try switching your phone between wifi and cellular network connections and let us know if you encounter any differences.

**Comment by timvdp** [comment]
No difference between wifi and cellular network.

**Comment by ffdixon** [comment]
Can you visit https://ipv6-test.com/ on both wifi and cellular with both phones and let us know which phone/network combination is using IPV6

![image](https://user-images.githubusercontent.com/290351/45264849-f7858800-b410-11e8-8f10-52d0960055c1.png)

IPV6 is a good thing as all devices are moving towards it.  Just trying to narrow down the issue.

**Comment by timvdp** [comment]
Neither phones are using ipv6 on the wifi but my wife's is using it on the cellular network (she is on Rogers, I'm on Bell).
I tried to put my wife's phone in airplane mode and join the meeting using wifi but it didn't work either. I was doing the test on test.bigbluebutton.org to make sure it was not related to my server. The "play a sound" button works on both phones. Mic is working on both phone as well. I can't hear the "you are the only person in this room" with my wife's phone.

**Comment by ffdixon** [comment]
> I tried to put my wife's phone in airplane mode and join the meeting using wifi but it didn't work either. 

Airplane mode disables both wifi and cellular.  If you phone is currently on wifi, just turn off Wifi under settings

![image](https://user-images.githubusercontent.com/290351/45265904-95348380-b420-11e8-898b-3a7edc233ace.png)

and it will switch to cellular.  If you turn off cellular you'll need to connect to the wifi to get on the internet again.  

If you put the iPhone 6s on wifi, it will be using your wireless router to get on the internet and will probably get an IPV4 address.  If you you can try that, let us know if you hear sound.

**Comment by timvdp** [comment]
I wasn't explicit enough, sorry:
1. Tried with the iPhone 6S with cellular and wifi ON. Ipv6-test.com said ipv6 not supported. 
2. Tried with the iPhone 6s on cellular only. Ipv6-test.com said ipv6 is supported. 
3. Tried with the iPhone 6S on airplane mode with Wifi activated (so wifi only). Ipv6-test.com said ipv6 not supported. 

All these test cases have the same result. Mic and play a sound button are working , sound not working. 

Let me know if I can do some more test. 
Could it be a timing issue? Except speed I don't see the difference between the iPhone 7 and the 6S. I even rebooted the 6s. With both phones I always get the error that I can't connect to echo server one or twice.

**Comment by ffdixon** [comment]
Thanks for the information.  We're working on updates to playback of sound on iOS.  We'll get you to test again when the updates are ready.

**Comment by timvdp** [comment]
Hello,

Just to let you know I still have the same issue on RC7. HTML5 client connects to audio, mic is working but I don't get any audio. Same thing on test.bigbluebutton.org.

**Comment by ffdixon** [comment]
HI Tim,

Could we try some tests together -- can you e-mail me at ffdixon .at. bigbluebutton .dot. org.

**Comment by timvdp** [comment]
Sure, I sent you an email last week. Did you get it?

**Comment by timvdp** [comment]
Hi Fred,

My phone is now running iOS 12.1.1 and I still have the issue. I did the test on test.bigbluebutton.org as well. I can join the audio but I don't get any sound.

**Comment by ffdixon** [comment]
Hi Tim,

Do you get sound in any of these cases:

1.  Join with Microphone?

2.  Join with Microphone, then join Listen Only?

Regards,... Fred

**Comment by Brullworfel** [comment]
Hello everyone! I have some issue. All our users with iPhones have this problem too.

I have iPhone 6, latest iOS (12.1.1), latest BBB 2 build 945. Everything work fine on MacOS and Windows in Chrome, in Safari of MacOS, in Chrome on Android. But no sound in iOS Safari. 

1. Microphone is works, everyone listen me;
2. I don't listen anyone;
3. I don;t listen myself in sound test (echo);
4. "no audiooutput" in speakers list if I choose "No" in sound test (echo);
5. I listen sound if I tap "play sound" in sound settings.
6. No difference with this problem in "Microphone" and "Listen Only" modes.

Sorry for my English.

**Comment by ffdixon** [comment]
@Brullworfel can you try it on https://test.bigbluebutton.org/ and let us know if you get the same results.

**Comment by timvdp** [comment]
Hello, sorry for not following up earlier on this issue. 
I updated bbb to 2.0RC11 and it is now working with my iphone (audio and video).

**Comment by Brullworfel** [comment]
> Hello, sorry for not following up earlier on this issue.
> I updated bbb to 2.0RC11 and it is now working with my iphone (audio and video).

I updated too, but issue not fixed for me. Some users (and me) from iPhone can't hear anyone on webinar.

**Comment by ffdixon** [comment]
Hi @Brullworfel, can you test against

    https://test.bigbluebutton.org/

with your iPhone and let us know if you can hear.  This server is running a build of 2.2-dev and is the basis for the next release of BigBlueButton HTML5.

**Comment by Brullworfel** [comment]
I'm sorry, but audio still not works for me from Safari on iPhone 6 / iOS 12. Other users hear me, but i don't hear anything except test sound in sound properties window.

Else, I can enable my camera on iPhone and can view myself, but other users can't see that I enabled camera.

On macOS safari audio works well, but I have some problem with camera.
