### ISSUE TITLE
Unable to connect to server

### ISSUE THREAD

**Issue by Naomi-Mifsud** [bigbluebutton/bigbluebutton#6022]
Hi,

We have been using the BBB plugin integrated with Moodle for the past 3 years. We've recently updated our Moodle instance to Moodle 3.5.1 and the BBB plugin to v2.2.4 (2017101012) and all was working fine. We have BBB server 2.0 installed.

Yesterday, we've received a query from one of our tutors informing us that she's unable to use the BBB activity. We tried creating a BBB activity from our end, as well as accessing an existing BBB activity, and we encountered the same error (https://prnt.sc/kol4ce):
"Unable to connect. Please check the url of the BigBlueButton server AND check to see if the BigBlueButton server is running."

Initially, we thought there was something wrong with our server. Hence, we tried connecting to another server we've been using last year but the same error occurs. Moreover, we also changed the setting to use the default BBB server provided by BlindSideNetworks (http://test-install.blindsidenetworks.com/bigbluebutton/) but the same error is being displayed.

Can someone please offer some insight with respect to this error at your earliest convenience, because tutors have planned online sessions and we need to find alternatives.

Thanks in advance,
Naomi

**Comment by ffdixon** [comment]
The server at https://test-install.blindsidenetworks.com/ appears to be functioning correctly.  The issue might be with the BigBlueButtonBN plugin or Moodle.

Did anything happen in the last few days with the Moodle server in the last few days.  Can you check the version of the BigBlueButtonBN plugin.  We updated the version to 2.2.5 yesterday (see https://moodle.org/plugins/pluginversions.php?plugin=mod_bigbluebuttonbn) so we would be very interested if you are now running BigBlueButtonBN 2.2.5 and have encountered an error.

**Comment by Naomi-Mifsud** [comment]
Thank you for your prompt attention.

We will install the latest version of the BBB plugin and keep you updated.

Thanks,
Naomi
