### ISSUE TITLE
Still some cases of listenOnly in iOS not working, particularly on mobile network

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#6037]

**Comment by ffdixon** [comment]
Marking this issue as closed as it appears the listen only is working in recent builds of BigBlueButton 2.2-beta.

**Comment by jtsre** [comment]
Hello, I noticed this exact issue on our install, so as suggested I tried on demo.bigbluebutton.org

Here is the log: https://github.com/bigbluebutton/bigbluebutton/issues/8133#issuecomment-639092552

**Comment by jtsre** [comment]
FYI this issues is still present on demo.bigbluebutton.org in addition to our install. No difference between wifi or mobile. Tried restarting and adjusting settings, un-silencing, adjusting volume etc. Nothing seems to fix it. We can hear the sound effects when joining and leaving, but not the actual audio stream from the instructor when in listen only mode on iOS.
