### ISSUE TITLE
Whiteboard annotation drawing incorrectly

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#6038]
![peek 2018-09-04 15-54](https://user-images.githubusercontent.com/6312397/45054507-36a38a00-b05b-11e8-8b50-d673fea540d1.gif)
Issue will be updated as more information on how to reproduce it is available

**Comment by zhu** [comment]
I think this is because the websocket is broken, the anotation messages sending fallback to ajax.
It does easily happen when the network is unstable.

**Comment by starcwl** [comment]
I found that there two issues cause this problem:
1. Meteor.Streamer process messages asynchronizes. So stream emit later maybe processed before last message has done if the length of the last payload is very large.
2. Streamer.on('publish', ...) .  stream emit later maybe arrived fast than the last message.

So I think it is better to change the library or choose a more proper library for processing the annotation messages in order.

**Comment by zijingcloud** [comment]
i change the line below
` if (!annotationsSenderIsRunning) setTimeout(proccessAnnotationsQueue, annotationsBufferTimeMin);
`
to
`  makeCall('sendAnnotation', annotation);
`
it works now. based on release 2.0

and add import line below

`import { makeCall } from '/imports/ui/services/api';
`

**Comment by starcwl** [comment]
i change the line below
if (!annotationsSenderIsRunning) setTimeout(proccessAnnotationsQueue, annotationsBufferTimeMin);
to
makeCall('sendAnnotation', annotation);
it works now. based on release 2.0

and add import line below

import { makeCall } from '/imports/ui/services/api';

**Comment by oswaldoacauan** [comment]
@starcwl need to check if removing the buffer does not impact the multiwhiteboard performance

**Comment by kepstin** [comment]
I can reproduce this in Firefox but not Chrome on my Windows tablet. In Firefox, the drawing gets slower and laggier as the line gets longer (the line stays grey, the black part doesn't "catch up")
