### ISSUE TITLE
The text tool font size isn't being set correctly in the recordings

### ISSUE THREAD

**Issue by capilkey** [bigbluebutton/bigbluebutton#6044]
Steps to reproduce:

1. Create and start a recorded meeting
1. Create a text annotation and increase the font size to max
1. End meeting and check the recording

Expected result:
The font size should be very large .

Actual result:
The text is always 16px.

Resolution:
The recordings are calculating and using the font-size as expected, but the <p> tag that has the actual text needs "font-size:inherit" added to its styling.

Current:
![image](https://user-images.githubusercontent.com/1395090/45170165-37f4c400-b1cd-11e8-8b50-b2c28bda8717.png)

Proposed:
![image](https://user-images.githubusercontent.com/1395090/45170202-4e028480-b1cd-11e8-9aeb-cb82f3a72214.png)

**Comment by kepstin** [comment]
Huh, I was sure this used to work. What browser are you seeing the problem in?

**Comment by capilkey** [comment]
I tested in both Chrome and Firefox. Win 10 for both.

**Comment by kepstin** [comment]
Analysis: The change in design to the recording playback change with the "Foundation" stylesheet broke this.

This playback change breaks existing recordings, so we don't want to fix this in the recording processing. Might have to just edit the foundation.css files so they don't set a font size on the `<p>` element.

**Comment by kepstin** [comment]
Fixed in #6099 for 2.0 and #6100 for 2.2
