### ISSUE TITLE
NODE_ENV=production npm start  error

### ISSUE THREAD

**Issue by allce231** [bigbluebutton/bigbluebutton#6048]
=> Errors prevented startup:                  
   
   While minifying app code:
   packages/minifyStdJS/plugin/in/minify-js.js:96:26: Ba: Babili minification error
   within app/pp/app.js:
  :
   imports/utils/ls/visibilityEvent.js, li, line 394
   
   Unexpected token, expected {:
   
   };
   
   at maybeThrowMinifyErrorBySourceFile
   (packages/minifyStdJS/plugin/in/minify-js.js:96:26)
  )
   at at files.forEach.file (pa (packages/minifyStdJS/plugin/in/minify-js.js:135:9)
  )
   at at Array.forEach (<a (<anonymous>)
   at at MeteorBabelMinifier.processcessFilesForBundle
   (packages/minifyStdJS/plugin/in/minify-js.js:118:9)
  )

**Comment by allce231** [comment]
imports/utils/ls/visibilityEvent.js  only line 120

**Comment by antobinary** [comment]
Hi @allce231 

https://github.com/bigbluebutton/bigbluebutton/blob/master/bigbluebutton-html5/imports/utils/visibilityEvent.js does not have line 120 (it's a shorter file). Have you made any changes to the code? What branch did you pull ('master', etc)?
