### ISSUE TITLE
Domain name and IP mismatch error during installation

### ISSUE THREAD

**Issue by dushanpiyaratne** [bigbluebutton/bigbluebutton#6050]
The installation command I ran:
> wget -qO- https://ubuntu.bigbluebutton.org/bbb-install.sh | bash -s -- -v xenial-200 -s www.mydomain.com -e email@mydomain.com -g

My server is behind a firewall.

I got below error during installation. Note that IPs do match.

> _DNS lookup for  resolved to mydomain.com.
> 81.123.456.789 but didn't match local 81.123.456.789._

The root cause is apparently related to dns resolution. _dig +short_ command returns below text with a line break in the middle, not just IP address on my server.

> /home/myd # dig +short www.mydomain.com
> mydomain.com.
> 81.123.456.789

Problem is here.

> bbb-install.sh:

> _318 check_host() {
> 319   need_pkg dnsutils
> **320   DIG_IP=$(dig +short $1)**

As a workaround, I commented out _check_host_ validation and continued with the installation without any issue.

**Comment by dushanpiyaratne** [comment]
Thank you for the reply. I tested the fix and it didn't work.

Apparently you've fixed the wrong place.

Problem is with the _dig_ call at line 318 below. It returns two lines as explained above. 

>     316 check_host() {
>     317   need_pkg dnsutils
>     318   DIG_IP=$(dig +short $1)
>     319   if [ -z "$DIG_IP" ]; then err "Unable to resolve $1 to an IP address using DNS lookup."; fi
>     320   get_IP
>     321   if [ "$DIG_IP" != "$IP" ]; then err "DNS lookup for $1 resolved to $DIG_IP but didn't match local $IP."; fi
>     322 }

**Comment by ffdixon** [comment]
Updated 

  https://github.com/bigbluebutton/bbb-install/blob/master/bbb-install.sh#L318

Can you try it again and don't hesitate to let us know if you encounter any problems.

**Comment by dushanpiyaratne** [comment]
Now it works. Thanks.

**Comment by ricardolopez010** [comment]
Hi Everyone

Let me share my solution:

on the main router that provides the network to that server, set in the DNS a host override like:

--> bbb.example.com to 192.168.0.xx (Ip BBB server)
-->in the server set de DNS Resolver (resolv.conf in my case)

Later Run:
-->wget -qO- https://ubuntu.bigbluebutton.org/bbb-install.sh | bash -s -- -v xenial-22 -s bbb.example.com -e info@example.com -w -g

i hope work for you.
