### ISSUE TITLE
Chat updating old messages

### ISSUE THREAD

**Issue by pedrobmarin** [bigbluebutton/bigbluebutton#6053]
Looks like react is forever updating some of the chat components in a couple of occasions:
 - message lenght > 1
 - user object changes
![test_chat](https://user-images.githubusercontent.com/1778398/45313638-d2bf0c80-b505-11e8-9a9a-bd86211d5f42.gif)

Maybe related with this early return in _componentWillReceiveProps_ (https://github.com/bigbluebutton/bigbluebutton/blob/v2.0.x-release/bigbluebutton-html5/imports/ui/components/chat/message-list/message-list-item/component.jsx#L84) and/or _pendingChanges_ not being correctly refreshed when _componentDidUpdate_ is called (https://github.com/bigbluebutton/bigbluebutton/blob/v2.0.x-release/bigbluebutton-html5/imports/ui/components/chat/message-list/message-list-item/component.jsx#L78)

**Comment by jfsiebel** [comment]
Some performance improvements was done in another chats related PR, the next step on improving chat is try to avoid prop-drilling, its possible do use the new `Context API` to mitigate or resolve this problem, but this will need mostly a component rewrite.
