### ISSUE TITLE
Chrome 69 on Mac OS X will attempt tunneling if the mac and an iPV6 address and external IPV6 connects are blocked

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#6059]
We are seeing that for users on

   * Mac OS X
   * Chrome 
   * IPV6 address

and when they are behind a firewall that blocks outgoing IPV6, Pepper Flash within Chrome is unable to drop back to use IPV4 and will start tunneling.

In contrast, FireFox on Mac OS X does properly properly fall back to use IPV4 and connect without  tunneling.

**Comment by capilkey** [comment]
I don't know of any way in Flash to determine the networking set up of a user's computer so I don't think we can do any preventative steps. What we can do though is for the servers that have a domain that resolves to an IPv4 and IPv6 address, we can set up an alternate domain (bbb.ipv4.mydomain.com) that only has IPv4 resolution and use that as a fallback before trying tunnelling.

To achieve this we're going to need to modify multiple components:
* a new option in config.xml for an alternate domain name that we can substitute into our red5 connections
* the main nginx config will need to be modified to handle two domain names
* modifications to bbb-conf and the update scripts to handle multiple "server_name"s in the nginx files
* documentation explaining how others can set this up if they hit the same problem with their users

**Comment by capilkey** [comment]
Fixed in 6069
