### ISSUE TITLE
How to change this link?

### ISSUE THREAD

**Issue by farshidmahmoodi2017** [bigbluebutton/bigbluebutton#6062]
https://github.com/bigbluebutton/bigbluebutton/blob/885539bb2a47057df24a672a58aec63ed1312131/bigbluebutton-html5/imports/ui/components/nav-bar/settings-dropdown/component.jsx#L133

**Comment by antobinary** [comment]
Hi @farshidmahmoodi2017 

On your server you can just replace the link with what you want by using `sed` or simply `vim` - search for `bigbluebutton\.org\/videos` in /usr/share/meteor/bundle/programs/web.browser/<some randomly generated name>.js
then save the file and restart the service via `sudo systemctl restart bbb-html5`

We are planning on making the link configurable, see https://github.com/bigbluebutton/bigbluebutton/issues/6029
