### ISSUE TITLE
Enable instructor to view screen sharing simultaneously from multiple students

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#6063]
There is a use case where the instructor asks a group of students to work on a problem for 10 minutes.  

It would be highly useful if the instructor could see the screen for each student, thereby giving them the ability to focus on helping the students that are experiencing the most difficulty.

**Comment by rudzboy** [comment]
👍 

I need that so much.
I'm sure tons of instructors do as well.

**Comment by prlanzarin** [comment]
I'm merging this with https://github.com/bigbluebutton/bigbluebutton/issues/9152. It's basically the same thing and although that one is newer, it has more info.
