### ISSUE TITLE
Updating components in HTML5 client

### ISSUE THREAD

**Issue by pedrobmarin** [bigbluebutton/bigbluebutton#6065]
Hey guys, it's me again... sorry!

It's kind of the same subject of this https://github.com/bigbluebutton/bigbluebutton/issues/6053 but I have more info related with another component. So, one thing we noticed a couple of weeks ago was the user list updating constantly in the HTML5 client with events not necessarily related with any changes in it, e.g. updating the public chat counter:
![updating](https://user-images.githubusercontent.com/1778398/45440035-a89a5580-b691-11e8-9a46-407ad16f852c.gif)

I was trying to find out the coast of those updates in the client so I recorded two performance profiles in my Chrome, one as it is, with the actual HTML5 client and another with an update controller in the _UserParticipants_ component. Here's the link to them (I believe this can be imported in Chrome for better visualization): https://drive.google.com/drive/folders/1Xa3kYw3oIahuYi-BuagqqRDOGRbq25wb?usp=sharing

One thing I noticed in this case, and you guys can help me out better interpreting this results, when the updates are avoided we get ~40% less _scripting_. And this is what my client looked like (with react dev tool updates turned on):
![avoid_update](https://user-images.githubusercontent.com/1778398/45440552-f2377000-b692-11e8-9daf-e2346e51372d.gif)

**Comment by oswaldoacauan** [comment]
Could you share the changes in the `UserParticipants` component?

**Comment by pedrobmarin** [comment]
I included this:
```
  shouldComponentUpdate(nextProps, nextState) {
    if (this.props.users.length !== nextProps.users.length) return true;
    return false;
  }
```
But I understand this is not enough to make this component work completely because it will miss all the avatar changes and more.

**Comment by oswaldoacauan** [comment]
Like I mentioned in Slack most of those performance bottlenecks are caused because we do not map properties. We just pass the whole user object.

**Comment by antobinary** [comment]
Will be [at least partly] addressed in #6268

**Comment by antobinary** [comment]
Is this still an issue now that #6268 is in place?

**Comment by pedrobmarin** [comment]
Not sure @antobinary . If the component updates are contained this probably won't happen now. Did not test this for a while but we plan testing 2.2 soon.

**Comment by ffdixon** [comment]
@antobinary Given the recent updates to the HTML5 client, is this still an issue?

**Comment by oswaldoacauan** [comment]
@ffdixon if I remember correctly the main offenders where the chat and user-list. The work @jfsiebel did mitigated the user-list and the latest work from @Tainan404 in the chat should also mitigate it.

Anyway @antobinary probably can confirm it better since I'm kinda out of the loop 😂

**Comment by pedrobmarin** [comment]
It's a lot better. I'm closing this one.
