### ISSUE TITLE
Download presentation experience

### ISSUE THREAD

**Issue by tylercopeland** [bigbluebutton/bigbluebutton#6067]

**Comment by tylercopeland** [comment]
@antobinary @oswaldoacauan @capilkey @fcecagno 👋🏻

I've put together potential options for downloading a presentation from the main interface.

**Option - 1** 
Playing it safe and mimicking the experience we see today in the Flash client where the download appears within the presentation control bar. 

![html5-participants-download-1](https://user-images.githubusercontent.com/1273169/45832870-14537280-bcd1-11e8-8cbe-94dde9f8a221.png)

**Option 2** 
Having a button appear on top of the presentation, lower right-hand corner. If we wanted to get fancy, we could display the button as you move your mouse over the presentation area. 

![html5-participants-download-2](https://user-images.githubusercontent.com/1273169/45832939-4ebd0f80-bcd1-11e8-8b40-3aaec0335273.png)

I had another idea of adding a  button, in the main control area, but I felt like it would be out of context. 

With all this being said, it would be great to hear your thoughts on the designs above.

**Comment by tylercopeland** [comment]
Also, something to know for the HTML5 2.2 release we're only providing the option of downloading the presentation. The other features, such as downloading with annotations will come in another release. @antobinary please confirm.

**Comment by capilkey** [comment]
Having a button show on mouse-over won't meet accessibility requirements.

**Comment by kepstin** [comment]
Not to mention that having a button show up on mouse-over doesn't work on touchscreen devices either.

**Comment by tylercopeland** [comment]
@capilkey @kepstin Thanks for the feedback. How do we feel about option #2 with no mouseover? 

cc: @antobinary @oswaldoacauan

**Comment by kepstin** [comment]
I'm not a fan of having anything obscure/overlay the slides - I think that should be avoided where possible. How about having the download button be moved down so it's just below the presentation (in the dark blue area)?
