### ISSUE TITLE
Set uploaded presentation as downloadable experience

### ISSUE THREAD

**Issue by tylercopeland** [bigbluebutton/bigbluebutton#6068]

**Comment by tylercopeland** [comment]
@antobinary here's my purposed option for "enabling the download presentation feature" in the upload presentation experience. The goal for this iteration was to keep the experience similar to what we see today in the Flash client. 

![html5-presentation-upload](https://user-images.githubusercontent.com/1273169/45782994-89239f80-bc32-11e8-9c2d-82b51a3b056f.png)

In the mockup above you'll notice a few adjustments that make this experience feel a little more polished. 

- [ ] Increasing the width of .ReactModal__Content to 750px;
- [ ] Updating grammar mistakes in the modal message
- [ ] Move the "current" tab to the right of the file name, allowing the file names to always be aligned. 
- [ ] Align all "select" input, even the default presentation

**Comment by capilkey** [comment]
There doesn't appear to be any way to change whether it's downloadable after the upload has completed. There are three columns on the right in the Flash client.

![image](https://user-images.githubusercontent.com/1395090/45784012-6ba40500-bc35-11e8-9baa-c8c3bb5ae888.png)

**Comment by tylercopeland** [comment]
@capilkey great catch, let me add that in.

**Comment by antobinary** [comment]
@capilkey - just to confirm - are you able to change from non-downloadable to downloadable after the upload is done? I was left with the impression we would be stuck with what we chose initially. But maybe I missed some 2.2 changes

**Comment by capilkey** [comment]
You're supposed to be able to change it after upload. Those are clickable
buttons.

**Comment by tylercopeland** [comment]
@antobinary @capilkey below are revised designs for this experience.

![html5-presentation-upload-1](https://user-images.githubusercontent.com/1273169/45825883-3e9d3400-bcc1-11e8-9e38-c786172bdc57.png)

![html5-presentation-2](https://user-images.githubusercontent.com/1273169/45825889-4361e800-bcc1-11e8-909c-f0712761c920.png)

![html5-presentation-upload-3](https://user-images.githubusercontent.com/1273169/45825894-465cd880-bcc1-11e8-8d41-8bad3570764d.png)

The three options above are the same, but it is the language used in the buttons that are different. My personal preference is "Download on" and "Download off", which is a little clearer than what we are currently using in the Flash client. A presenter only knows what "Allow" means once they hover over the button. 

Would love to here your thoughts on this.

**Comment by antobinary** [comment]
From the above options I'd pick the second one - clearer difference in 'enabled' vs 'disabled', the only thing I'd consider is moving the `Enable the option for participants to download your presentation' to be _under_ the drop box for upload - to be more visible and distinguishable from just another item in the list of presentations.

**Comment by tylercopeland** [comment]
@antobinary either one works for me. 

Here are the revised designs based on your comments above. 

![html5-presentation-upload-1](https://user-images.githubusercontent.com/1273169/45826722-fa129800-bcc2-11e8-99cc-fba6ade989dc.png)

![html5-presentation-2](https://user-images.githubusercontent.com/1273169/45826729-fda61f00-bcc2-11e8-9ef1-4edd6a8b34d8.png)

**Comment by oswaldoacauan** [comment]
I would love to have only an download icon instead of a texted button but not sure if that works regarding usability and accessibility.

**Comment by tylercopeland** [comment]
@oswaldoacauan I thought about having an icon, it would definitely simplify the interface. But, I put myself into the shoes of a presenter looking at this experience for the first time and the only way they would know to toggle the download state is to hover over the icon which would display the tooltip. 

With that being said tho, I'm going to put together a mockup with an icon so we can compare.

**Comment by tylercopeland** [comment]
Here's a concept that includes an icon as a toggle. My gut tells me that a button provides a clearer indication of the functionality of the button. If we only used an icon, it might not be clear to the user that they have the options to enable the presentation to be downloadable. 

Curious to hear what your thoughts are @oswaldoacauan @antobinary.

![html5-presentation-upload-4](https://user-images.githubusercontent.com/1273169/47165249-9c746a00-d2c7-11e8-9176-64b48846ad2f.png)

**Comment by antobinary** [comment]
I'm still a fan of the 'Download disabled' option as it's clearer that you can press/toggle it. The icon for 'downloadable' (in my opinion) cannot convey that it's setting a state (downloadable) rather than triggering an immediate download
