### ISSUE TITLE
Substitute the "You have been Kicked" message with a sound

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#6083]
When the BigBlueButton client looses a websocket or RTMP connection and is unable to reconnect, it will log the user out of the session.  As part of this logout process, it will tell FreeSWITCH to close to audio connection.

However, when the audio connection closes, FreeSWITCH will tell the user "You have been kicked from this conference."

As a result, there are cases where the client may loose a websocket or RTMP connection, but still have the UDP connection for FreeSWITCH, and they hear "You have been kicked from this conference", which leads them to conclude that some has kicked them from the conference.

We're should replace out that message with an audible sound.

**Comment by pedrobmarin** [comment]
Current version does not have a `You have been kicked from this conference` message and leave audio has an audible sound.
