### ISSUE TITLE
Recordings migrated from 1.0 and previous make some integrations to fail

### ISSUE THREAD

**Issue by jfederico** [bigbluebutton/bigbluebutton#6089]
The meetingID (which is the external meetingID) in recordings migrated from 1.0 and previous are not correct in the XML response given to getRecordings requests.

Instead of being the actual meetingID, the value is the recordingID (a.k.a. internalMeetingID). And neither the internalMeetingID element is included.

```
correct
<recordID>8dc29fd9eb3c46047904f23901103da283ceea7a-1537373218851</recordID>
<meetingID>2e075742584810cacd4aed420335d00983526d67-2-1</meetingID>
<internalMeetingID>8dc29fd9eb3c46047904f23901103da283ceea7a-1537373218851</internalMeetingID>
```

```
incorrect
<recordID>8dc29fd9eb3c46047904f23901103da283ceea7a-1537377577753</recordID>
<meetingID>8dc29fd9eb3c46047904f23901103da283ceea7a-1537377577753</meetingID>
```

The underlying issue is that the metadata.xml file (generated from events.xml) in old versions, did not include the new element <meeting> in which thos values are based

```
  <meeting 
  id="8dc29fd9eb3c46047904f23901103da283ceea7a-1537373218851" externalId="2e075742584810cacd4aed420335d00983526d67-2-1" name="First room (Moodle-3.0/BN-2.1)" breakout="false">
</meeting>
```
It seems that bbb-web failover is somehow to use the recordingID for both properties. The new version has to be fully compatible with migrated recordings as well.

**Comment by fcecagno** [comment]
I believe this fixes the issue (I just renamed to txt to be able to upload here).

[bbb-1.1-meeting-tag.txt](https://github.com/bigbluebutton/bigbluebutton/files/2398579/bbb-1.1-meeting-tag.txt)

**Comment by jfederico** [comment]
So the migrated recording should be re-processed with this script?

**Comment by fcecagno** [comment]
You can run this script on upgrading packages or manually later on. It will only touch recordings without the meeting tag. And you don't need to reprocess the recording, it's going to modify metadata.xml of the processed recordings.

**Comment by jfederico** [comment]
Thanks @fcecagno 
I run a copuple of tests in my dev server. It works as a charm! :)
I opened a PR #6095 , and I am working on updating the docs. Please merge it if you think your script passes QA ;)
