### ISSUE TITLE
Large SVG presentation page freezes HTML5 client

### ISSUE THREAD

**Issue by ritzalam** [bigbluebutton/bigbluebutton#6091]
Uploaded presentations with complex background will result in large SVG files. 

A large SVG file can cause tomcat7 to OOM when several HTML5 clients try to load the file at the same time. Also, the SVG file will cause the HTML5 client to freeze because it will have trouble rendering the file.

One solution would be to convert the SVG -> JPG -> PDF -> SVG to drop down the size of the file.

pdftocairo -scale-to 1600 -jpeg -q -f 8 -l 8 ~/foo.pdf -singlefile page8
convert page8.jpg page8.jpg.pdf
pdftocairo -rx 300 -ry 300 -svg -q -f 1 -l 1 page8.jpg.pdf page8.jpg.pdf.svg

**Comment by GhaziTriki** [comment]
Implemented solution here https://github.com/bigbluebutton/bigbluebutton/pull/6134

SVG -> PNG (150 DPI instrad of 300) -> SVG + ADD HEADER

**Comment by capilkey** [comment]
Related issue here, #5716. In the issue there's a comment from @kepstin about pre-gzipping the SVGs to make the size even smaller for transfer.

**Comment by aogilvie** [comment]
Very related but not exactly same as origin author post. As this is an HTML5 client that can run on mobile (iPad, iPhone) for example, shouldn't further image optimisation be done for mobile clients?

At the moment a PDF with lots of images saved at 300DPI and jpeg compression at 40%, after uploading to the server still produces an avg. slide SVG at 450kb.

This causes a related issue with Safari rendering large SVGs where clipping occurs 
https://github.com/bigbluebutton/bigbluebutton/issues/6153
