### ISSUE TITLE
Load presentation slides using nginx instead of tomcat7

### ISSUE THREAD

**Issue by ritzalam** [bigbluebutton/bigbluebutton#6092]
Currently, slide pages are loaded by tomcat7.

We should change it so that nginx would be serving these files.

The URL patterns for these are located in https://github.com/bigbluebutton/bigbluebutton/blob/v2.0.x-release/bigbluebutton-web/grails-app/conf/UrlMappings.groovy

**Comment by ritzalam** [comment]
This issue is being addressed in this PR (https://github.com/bigbluebutton/bigbluebutton/pull/6088).

One extra step required is during packaging. We need to copy bigbluebutton-web/nginx-confs/presentation-slides.nginx to /etc/bigbluebutton/nginx/ directory.

**Comment by ffdixon** [comment]
Implemented in RC7
