### ISSUE TITLE
Presenter not assigned

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#6109]
Symptom - HTML5 presenter cannot draw on 2.2

```
{
    "_id" : "Whn3X3watb7a3wrzM",
    "meetingId" : "183f0bf3a0982a127bdb8161e0c44eb696b3e75c-1537887451432",
    "podId" : "DEFAULT_PRESENTATION_POD",
    "currentPresenterId" : ""
}
```

**Comment by oswaldoacauan** [comment]
This happens when someone assign presenter via the user-list and then the DEFAULT_PRESENTATION_POD becomes orphan.

In the `AssignPresenterReqMsg` message we need to trigger both `PresenterAssignedEvtMsg` and `SetPresenterInPodRespMsg`.

**Comment by oswaldoacauan** [comment]
Or we can just do in the event handler itself like Flash does but it would be better to fix it in Akka.

**Comment by oswaldoacauan** [comment]
Related #5941
