### ISSUE TITLE
[HTML5] Webcam videos have the top/bottom section of the video cropped out for display

### ISSUE THREAD

**Issue by kepstin** [bigbluebutton/bigbluebutton#6111]
Right now the HTML5 client WebRTC webcams record 4:3 video from the browser, but on display it crops the top/bottom off to fit a 16:9 ratio.

Some of the problems this introduces:
- A closely focused webcam that works in other applications will result in missing sections of video - such as the top/bottom of someone's head
- When an external camera system is used, the viewfinder video no longer matches the display in the html5 client, which could mean viewers are missing important content
- The display in the live meeting no longer matches the recording, since the recording shows the complete video as received.

**Comment by pedrobmarin** [comment]
Not cropping anymore.
