### ISSUE TITLE
when moderator close browser automatic end meeting

### ISSUE THREAD

**Issue by wpp5354** [bigbluebutton/bigbluebutton#6116]
I think when moderator close browser automatic end meeting,Is there a parameter somewhere to indicate to bbb to end the meeting when no moderator? thank you!

**Comment by ffdixon** [comment]
We plan to add this to 2.2 -- provide an option that when all moderators leave a meeting, the meeting is ended shortly afterwards (i.e. with 10 seconds).

The short delay gives a moderator who was disconnected to reconnect (by clicking the reload button in their browser).

**Comment by febincloudyuga** [comment]
@ffdixon - I see that you've removed this work item from 2.2. Any hint on which release we could expect this feature in?

I currently have a corner case in my implementation wherein if the first user to join a meeting is not a moderator and he immediately leaves, the meeting would end, not allowing others to join.

It would be nice to have this feature wherein the meeting ends only when the last person to leave is a moderator and not an attendee.

**Comment by capilkey** [comment]
I don't think we'd ever want to not end the meeting if the last person to leave is a specific role because that would open up an edge case where meetings could live forever.

A different solution to your problem would be to call the create API before the join every time. As long as the parameters are the same the create call will return a success code.

**Comment by febincloudyuga** [comment]
I'd implemented it this way, but the Join link is open even if the meeting ends. I'm trying to overcome this with the help of `meta_endCallbackUrl`.
Thanks for your suggestion.

**Comment by nicolopez77** [comment]
I see ther is a parameter in the config file endWhenNoModerator=false but this issue os open. Was it implemented? What is the period of time considered to close the meeting? Thanks!

**Comment by matiasilva** [comment]
If nobody is in the room, then after 60s (default) the meeting will end. This is in the configuration.

**Comment by nicolopez77** [comment]
@matiasilva I couldn't find such configuration, could you help me where is it?
In bigbluebutton.properties from a 2.2.27 I just found this:

# Param to end the meeting when there are no moderators after a certain period of time.
# Needed for classes where teacher gets disconnected and can't get back in. Prevents
# students from running amok.
endWhenNoModerator=false

**Comment by PhMemmel** [comment]
> 
> 
> If nobody is in the room, then after 60s (default) the meeting will end. This is in the configuration.

I tested it on 2.2.31, I set `endWhenNoModerator=true` in `bigbluebutton.properties`, restarted BBB server, created a meeting, joined as attendee, left as moderator. After 1.5h meeting still not closed automatically (I stopped testing at this point), so definitely not the 60s you were talking about :-)

Is there any other parameter I have to set except `endWhenNoModerator=true` for this to work?

**Comment by gustavotrott** [comment]
Hello,
the function `endWhenNoModerator` is avaiable in `bigbluebutton.properties`, but the implementation is not finished.
I am working on this option and it will be avaiable in develop next days.

I thought include a new config: `endWhenNoModeratorDelayInMinutes`

When last moderator left:
- After x minutes (`endWhenNoModeratorDelayInMinutes`) the meeting will end, but:
If some moderator join, cancel the ending
If some user be promoted to moderator, cancel the ending

What do you think @ritzalam?
