### ISSUE TITLE
The Flash client allows you to open a non-functional 9th chat pod

### ISSUE THREAD

**Issue by capilkey** [bigbluebutton/bigbluebutton#6117]
In 2.2 we've added chat pods and there's a limit of 8 additional pods, but the UI in the Flash client allows you to enter a name for a 9th pod and when you press "Create" it gets added to the list, but never actually opens. I'm not sure if the block is in the server or the client.

**Comment by ffdixon** [comment]
Closing as this was an issue related to the Flash client (the project has moved to an HTML5 client).
