### ISSUE TITLE
failed to fetch config.xml

### ISSUE THREAD

**Issue by morteza81** [bigbluebutton/bigbluebutton#6118]
i get error " failed to fetch config.xml" after use ssl in site .
plz help me for fix problem.
tnx

**Comment by ffdixon** [comment]
We need to have more information:

1.  What version of BigBlueButton are you running?
2.  How did you install BigBlueButton?
3.  Did you get any errors on the install?
4.  How did you install SSL certificate?
5.  What was the test results for `https://www.ssllabs.com/ssltest/`
6.  Can you post the output of `sudo bbb-conf --check`

**Comment by morteza81** [comment]
BigBlueButton Server 2.0.0-RC6 (1062)
                    Kernel version: 4.4.0-31-generic
                      Distribution: Ubuntu 16.04.5 LTS (64-bit)
                            Memory: 4028 MB

/var/www/bigbluebutton/client/conf/config.xml (bbb-client)
                Port test (tunnel): rtmp://web-conf.domain.ir
                              red5: web-conf.domain.ir
              useWebrtcIfAvailable: true

/opt/freeswitch/etc/freeswitch/sip_profiles/external.xml (FreeSWITCH)
                         websocket: :7443
                    WebRTC enabled: true

/etc/nginx/sites-available/bigbluebutton (nginx)
                       server name: web-conf.domain.ir
                              port: 80
                              port: 443 ssl
                    bbb-client dir: /var/www/bigbluebutton

/var/lib/tomcat7/webapps/bigbluebutton/WEB-INF/classes/bigbluebutton.properties (bbb-web)
                      bbb-web host: web-conf.domain.ir

/var/lib/tomcat7/webapps/demo/bbb_api_conf.jsp (API demos)
                               url: web-conf.domain.ir

/var/www/bigbluebutton/check/conf/config.xml (client check)
                      client check: web-conf.domain.ir

/usr/share/red5/webapps/bigbluebutton/WEB-INF/red5-web.xml (red5)
                  voice conference: FreeSWITCH

/usr/local/bigbluebutton/core/scripts/bigbluebutton.yml (record and playback)
                     playback host: web-conf.ba24.ir
                            ffmpeg: 4.0.2-1~16.04.york0.1


** Potential problems described below **
# Warning: API URL IPs do not match host:
#
#                                IP from ifconfig: 10.108.0.26
#  /var/lib/tomcat7/webapps/demo/bbb_api_conf.jsp: web-conf.domain.ir

....................
# Error: Could not connect to the configured hostname/IP address
#
#    https://web-conf.domain.ir/
#
# If your BigBlueButton server is behind a firewall, see FAQ.

# Warning: The API demos are installed and accessible from:
#
#    https://web-conf.ba24.ir/demo/demo1.jsp
#
# These API demos allow anyone to access your server without authentication
# to create/manage meetings and recordings. They are for testing purposes only.
# If you are running a production system, remove them by running:
#
#    sudo apt-get purge bbb-demo

# Warning: The client self check is installed and accessible from:
#
#    https://web-conf.domain.ir/check
#

# Warning: The IMS Learning Tools Integration (LTI) is accessible from:
#
#    http://web-conf.domain.ir/lti/tool
#
# To get the access parameters for LTI, run the command
#
#    bbb-conf --lti

# Error: Unable to reach default URL for presentation:
#
#    https://web-conf.domain.ir/default.pdf
#
# Check value for beans.presentationService.defaultUploadedPresentation in
#   /var/lib/tomcat7/webapps/bigbluebutton/WEB-INF/classes/bigbluebutton.properties

**Comment by morteza81** [comment]
What version of BigBlueButton are you running?
version 2 
How did you install BigBlueButton?
yes 
Did you get any errors on the install?
no
How did you install SSL certificate?
yes . in ngnix config and copy /usr/share/ca-sertificate folder

What was the test results for https://www.ssllabs.com/ssltest/ 
this ca is local and export from PKA local server( vaild is my domain )

**Comment by morteza81** [comment]
![failed bbb](https://user-images.githubusercontent.com/43641122/46149694-b8ac5a80-c277-11e8-8882-794369bd0f03.jpg)

**Comment by capilkey** [comment]
Tomcat doesn't like self-signed certificates. You need a legitimate certificate or add to add the certificate to the Java KeyStore on your server so that tomcat will accept it.

**Comment by capilkey** [comment]
In the future please post setup related problems to the setup mailing list, https://groups.google.com/forum/#!forum/bigbluebutton-setup, because, as in this case, they're usually not actual issues with BBB.

**Comment by morteza81** [comment]
hi 
i 'm create keystore and set certificate and accept from tomcat 7 , but problem not fix.

tomcat 7 server.xml file detail 


<?xml version='1.0' encoding='utf-8'?>


<Server port="8005" shutdown="SHUTDOWN">
  <Listener className="org.apache.catalina.startup.VersionLoggerListener" />
  
  
  
  
  <Listener className="org.apache.catalina.core.JasperListener" />
  
  <Listener className="org.apache.catalina.core.JreMemoryLeakPreventionListener" />
  <Listener className="org.apache.catalina.mbeans.GlobalResourcesLifecycleListener" />
  <Listener className="org.apache.catalina.core.ThreadLocalLeakPreventionListener" />

  
  <GlobalNamingResources>
    
    <Resource name="UserDatabase" auth="Container"
              type="org.apache.catalina.UserDatabase"
              description="User database that can be updated and saved"
              factory="org.apache.catalina.users.MemoryUserDatabaseFactory"
              pathname=" /var/www/bigbluebutton/client/conf/config.xml" />
  </GlobalNamingResources>
  
  <Service name="Catalina">

    
    


    
    <Connector port="8080" protocol="HTTP/1.1"
               connectionTimeout="20000"
               URIEncoding="UTF-8"
               redirectPort="7443" />
    
    
    


           <connector port="7443" maxHttpHeaderSize="8192" maxThreads="100"
           minSpareThreads="25" maxSpareThreads="75"
           enableLookups="false" disableUploadTimeout="true"
           acceptCount="100" scheme="https" secure="true"
           SSLEnabled="true" clientAuth="true"
           sslProtocol="TLS" keyAlias="/usr/share/ca-certificates/cert.crt"
           keystoreFile="/usr/share/ca-certificates/web-con-keystore.jks"
           keystorePass="123456" />

    
    


    

    
    <Engine name="Catalina" defaultHost="localhost">

      
      

      
      <Realm className="org.apache.catalina.realm.LockOutRealm">
        
        <Realm className="org.apache.catalina.realm.UserDatabaseRealm"
               resourceName="UserDatabase"/>
      </Realm>

      <Host name="localhost"  appBase="webapps"
            unpackWARs="true" autoDeploy="true">

        
        

        
        <Valve className="org.apache.catalina.valves.AccessLogValve" directory="logs"
               prefix="localhost_access_log." suffix=".txt"
               pattern="%h %l %u %t &quot;%r&quot; %s %b" />

      </Host>
    </Engine>
  </Service>
</Server>

**Comment by capilkey** [comment]
No connectors involved with this method, https://serverfault.com/a/201407. I've never personally used a self-signed certificate, nor do I know of any developers on the project that have used a self-signed certificate so you're not likely to find much help with the issue here. Google will be your best resource for configuring tomcat.
