### ISSUE TITLE
Whiteboard TypeError

### ISSUE THREAD

**Issue by pedrobmarin** [bigbluebutton/bigbluebutton#6125]
```
2b50053c67285542188880288cad4c26e76d2d66.js?meteor_js_resource=true:147 Uncaught TypeError: Cannot read property 'annotationInfo' of undefined
    at s (2b50053c67285542188880288cad4c26e76d2d66.js?meteor_js_resource=true:147)
    at 2b50053c67285542188880288cad4c26e76d2d66.js?meteor_js_resource=true:147
    at Array.forEach (<anonymous>)
    at n.<anonymous> (2b50053c67285542188880288cad4c26e76d2d66.js?meteor_js_resource=true:147)
    at 2b50053c67285542188880288cad4c26e76d2d66.js?meteor_js_resource=true:129
    at Array.forEach (<anonymous>)
    at n.e [as emit] (2b50053c67285542188880288cad4c26e76d2d66.js?meteor_js_resource=true:129)
    at t.<anonymous> (2b50053c67285542188880288cad4c26e76d2d66.js?meteor_js_resource=true:129)
    at 2b50053c67285542188880288cad4c26e76d2d66.js?meteor_js_resource=true:129
    at Array.forEach (<anonymous>)
```

Saw this happen a couple of days ago but couldn't find a way to describe a path to reproduce back then.

It is possible to draw in the whiteboard without having the mouse button clicked. And if this occurs and the user clicks the clear annotation button is where you got the error above. I could reproduce this mouse held down situation selecting all the text from the client with `Ctrl + A`, dragging this text and starting an annotation.

![annotation](https://user-images.githubusercontent.com/1778398/46297101-3fac4c00-c572-11e8-8bfd-b4244c175681.gif)

Doesn't look like something that may cause a lot of damage. Reporting this more because of the button down hack thing that may break other stuff.

**Comment by pedrobmarin** [comment]
Did this using Chrome

**Comment by ffdixon** [comment]
@pedrobmarin Can you do a quick test on the latest build of the HTML5 client in 2.2 and let us know if you still encounter this issue -- thanks!

**Comment by pedrobmarin** [comment]
Could not reproduce this issue on the latest build.
