### ISSUE TITLE
Add one or more messages to inform the user when the port test fails

### ISSUE THREAD

**Issue by capilkey** [bigbluebutton/bigbluebutton#6133]
We've seen problems where the RTMPS connection (and all available fallbacks) fail to connect and the user is left sitting on the loading bar with no feedback. We need to listen for the failures and send log messages when they occur. We can also potentially modify the message to ask the user to try Chrome if they are using Firefox and the server is configured for RTMPS.

**Comment by ffdixon** [comment]
Closing as this was an issue related to the Flash client (the project has moved to an HTML5 client).
