### ISSUE TITLE
Status of BBB-HTML5 client?

### ISSUE THREAD

**Issue by zenny** [bigbluebutton/bigbluebutton#6136]
Hi,

I just came across https://bigbluebutton.org/2012/10/06/bigbluebutton-html5-client-video-1/ which is about 6 years old. The status is not clear from @capilkey's post of about two years back at https://wiki.cdot.senecacollege.ca/wiki/BigBlueButton#HTML5_Client

Is it ready to be deployed in production to completely replace the flash client both for the presenters and the participants? Just wondering.

Cheers,
/z

**Comment by ffdixon** [comment]
The HTML5 client is ready for deployment -- it implements almost all the capabilities of the viewer (except two-way webcams) and can be deployed alongside the Flash client.  For more information, along with instructions to install, see http://docs.bigbluebutton.org/install/install.html.
