### ISSUE TITLE
Add ability to share screen using WebRTC in FireFox

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#6142]
When screen sharing using WebRTC in BigBlueButton, Chrome gives the user the ability to choose which screen/window, whereas FireFox only lets the user choose a window.

Add the ability in FireFox to choose a screen.  

The choice would appear as an option when the user is using FireFox and clicks the Share Screen button.

![image](https://user-images.githubusercontent.com/290351/46634122-e453fe00-cb1d-11e8-9b9d-654804246854.png)

**Comment by tylercopeland** [comment]
@ffdixon here are high-fidelity designs for this experience. 

![html5-general-firefox-screen-select](https://user-images.githubusercontent.com/1273169/48316532-f90b3200-e5b2-11e8-9815-4fb97ab106f3.png)

**Comment by ffdixon** [comment]
Looks good!

**Comment by prlanzarin** [comment]
@ffdixon @tylercopeland Although I understand the idea behind this design, wouldn't it be better if the option was presented as modal? The rationale here is that it'd make the experience consistent with joining audio and sharing the webcam (which has an upcoming device selection modal). Other benefit of the modal approach is that we could further extend it in the future to add options such as quality profiles.

**Comment by fcecagno** [comment]
Would it be possible to unify the experience between Chrome and Firefox? It would be confusing if on Firefox we choose in the application, but on Chrome we choose on Chrome's selector.

**Comment by prlanzarin** [comment]
Both will still show the picker, and we can restrict Chrome's picker options according to what the user chose in the modal/baloon. It'll be a two-step process anyways, we can't go around that.

**Comment by ffdixon** [comment]
Closing this issue as the recent versions of the BigBlueButton 2.2 HTML5 client have supported screen sharing.
