### ISSUE TITLE
Improve repeated checks for ACL

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#6146]
Continuation from #6138 
> `Another observation about this control list is that it gets really heavy server side to manage cursor and annotations the way it is. I made some tests and ACL takes ~25% of meteor CPU usage when moving the cursor around and annotating in the whiteboard.`

**Comment by pedrobmarin** [comment]
https://github.com/pedrobmarin/bigbluebutton/tree/acl-refactoring here is what I did to help mitigate this problem. Still, IMO if meteor queries could be avoided here would be better

**Comment by oswaldoacauan** [comment]
In the ideal world akka-apps should have this responsibility.

**Comment by pedrobmarin** [comment]
Agree on that. It's not so hard to do this in akka-apps but the client should be prepared to receive rejections somehow. Is this planned to be on akka-apps in the upcoming version of BBB?

**Comment by capilkey** [comment]
In 2.2 akka-apps has a permission check in it. There's no feedback sent back that a message has failed though. If a message fails to pass the permission check it will be ignored. There's also a property (that is disabled by default) for whether or not to eject a user if the message is a high enough severity.

A message like the cursor or annotation isn't a high severity and is pretty common to be rejected (turning multi-user off) that we wouldn't want to eject the person, but if the user tries to send a KickUser message as a viewer they will be ejected.

**Comment by pedrobmarin** [comment]
Do you think that leaving a lightweight ACL running client-only and that 2.2 akka feature could be enough? How about the video/audio sharing messages? Do they go through akka-apps for permission check?

**Comment by oswaldoacauan** [comment]
My two cents, for 2.2 we should remove the server-side ACL and only do simple checks for disabling/removing features (like hiding the whiteboard toolbar) in the client side using the data we already have and leave the heavy lifting for akka. Not having a failed message is not a big deal in most cases and in the ones where it could impact in something we already have failed messages anyway.

**Comment by capilkey** [comment]
I'm not sure about the video and audio sharing messages. With WebRTC they've always kind of lived outside of akka-apps.

The big reason for the ACL originally was because akka-apps didn't have permission checks and it was easy to send elevated messages from the JS console. The original purpose doesn't really exist anymore because we added the checks further downstream. There still needs to be the client checks so the user isn't shown something they shouldn't be, but I don't think the HTML5 code needs to worry about permission elevation anymore.

**Comment by oswaldoacauan** [comment]
@capilkey do you know how akka handle the lock-settings case? Does it handle it or nope?

**Comment by capilkey** [comment]
If you're asking about whether akka-apps checks to see if chat is locked when receiving a message, it does. There's four different things it can check depending on the message.
1. Role - Moderator, Viewer, Guest
2. Presenter - Yes, No
3. Lock Settings
4. Multi-user whiteboard

**Comment by oswaldoacauan** [comment]
Nice. Then the client doesnt need to worry about ACL anymore :top:

**Comment by pedrobmarin** [comment]
Why to keep multi-user whiteboard as a different case to test? Couldn't be inside lock settings?

**Comment by pedrobmarin** [comment]
So this could be similar to _mute all_ and _mute all except presenter_? Where are those cases at?

**Comment by capilkey** [comment]
All that's needed for the "mute all" cases is a check to see if the
requester is a moderator. There's nothing too special there.

**Comment by pedrobmarin** [comment]
Yeah, but where those meeting states are stored? Is there a boolean value that defines a meeting as a _all muted_? Isn't the same as a _multi-user-wb_ status? Sorry if I'm pushing too much here @capilkey ... I believe the server checks are the right way to go, just not entirely convinced multi-user-wd is a completely distinct case

**Comment by capilkey** [comment]
Whether someone is, or isn't, muted as soon as they join the audio is
completely separate from any sort of permission. If the meeting is muted
the user can still unmute themselves. There's no permission check there.
It's just normal application logic to determine the initial state.

The multiuser whiteboard is actually a check to see if someone can publish
messages (annotations and cursor) so there's a permission check in there.

I'm kind of confused how mute all is related to permissions because it
doesn't actually restrict anything.

**Comment by pedrobmarin** [comment]
Oh, I know why you are confused. It's because I thought it muted and restricted.

Just ignore me, nothing to see here.

**Comment by antobinary** [comment]
After some further discussion the decision was to address this in 2 ways:

1. Remove ACL for html5 client for all functionality where ACL-like rules in akka-apps exist (a.k.a Rights Management in BBB 2.2 - currently on 'master'). This likely means 100% of html5 ACL removal

2. Add _client side_ check in HTML5 client to prevent potential attempts to flood the server with requests for unauthorized action[s]

Step 1) is to be achieved as part of this GitHub issue.
Step 2) will be addressed in #6163

**Comment by antobinary** [comment]
Closing in favor of #6163
