### ISSUE TITLE
HTML5 Screen Share connection not closing

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#6152]
Steps to reproduce

1. start session as HTML5 client presenter
2. invite someone
3. open new chrome window and navigate to google.com (or anywhere)
4. start screensharing the chrome window with google.com
5. pkill chrome or crash it
7. re-join session (restore tab or use browser history)
8. screensharing automatically restarts, but the previous chrome window that was screenshared is no longer present so stuck at spinner.
9. cannot un-toggle screensharing

Reported in

 https://groups.google.com/d/msg/bigbluebutton-dev/XZxu2n7-HJs/lN-b-Z8dBwAJ

**Comment by GhaziTriki** [comment]
@ffdixon I remember when this was happening. It seems no more to be the case.
