### ISSUE TITLE
Add client side permission check for annotation + cursor

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#6163]
By having a check on the client side we avoid having to repeatedly consult with server side (confirming permissions) for high volume/frequency actions as annotation and cursor updating.

A simple check could be `am I currently presenter`

**Comment by capilkey** [comment]
That check wouldn't actually be sufficient. For whiteboard it would be "Am I presenter || is multiuser on for this whiteboard". It's essentially the exact same check that has to be performed for showing or hiding the whiteboard toolbar.

**Comment by antobinary** [comment]
We no longer have ACL in bbb-html5 client
