### ISSUE TITLE
Webcam fails to start

### ISSUE THREAD

**Issue by fcecagno** [bigbluebutton/bigbluebutton#6166]
After a while, webcams stopped working in a server. On bbb-webrtc-sfu logs, I can see some occurrences such as:

`{"error":{"type":"error","code":2019,"message":"MEDIA_SERVER_GENERIC_ERROR","details":"Client has been disconnected","operation":"addIceCandidate","params":{"mediaId":"nameless-wood-bC_aYK7","candidate":{"candidate":"candidate:1259281880 1 udp 1685987071 ANONYMOUS_IP 44034 typ srflx raddr ANONYMOUS_IP rport 44034 generation 0 ufrag 93C3 network-id 1","sdpMid":"video","sdpMLineIndex":0,"usernameFragment":"93C3"}}},"level":"error","message":"[mcs-api] Reject operation addIceCandidate with","timestamp":"2018-10-18T01:34:30.200Z"}`

After `systemctl restart kurento-media-server.service bbb-webrtc-sfu.service`, it worked again.

[media-server_2018-10-18_00-00-15.00002.pid26288.log](https://github.com/bigbluebutton/bigbluebutton/files/2493506/media-server_2018-10-18_00-00-15.00002.pid26288.log)
[bbb-webrtc-sfu.2018-18-10.log](https://github.com/bigbluebutton/bigbluebutton/files/2493505/bbb-webrtc-sfu.2018-18-10.log)

**Comment by j1elo** [comment]
The `handling timeout failed` warning message is being printed [here in gst-plugins-bad](https://github.com/Kurento/gst-plugins-bad/blob/3db37b1965c00e820babfcd3e8ee7a257198ef56/ext/dtls/gstdtlsconnection.c#L312). It's caused by a failed call to `DTLSv1_handle_timeout()`.

I'm not familiar with the implementation of OpenSSL or what that function is supposed to do, but [here](https://mta.openssl.org/pipermail/openssl-users/2016-September/004477.html) they clarify:

> The application is expected to call this periodically during the
> handshake if no other data has been sent or received. The causes
> OpenSSL to check its timer and do any retransmits if necessary.

So yes, if this doesn't get called due to some lockout, it is probably just a symptom more than a cause here...

**Comment by antobinary** [comment]
@prlanzarin Is this still an issue?

**Comment by antobinary** [comment]
Lots of improvements since Oct 2018. @prlanzarin confirmed this can be now closed (BBB 2.2)

**Comment by aligot-cblue** [comment]
We have same isse with BBB 2.2

from kurento log:
2020-03-19T17:41:40,678510 17185 0x00007f0308359700 warning dtlsconnection            gstdtlsconnection.c:312 handle_timeout() <GstDtlsConnection@0x7f05a4061af0>  handling timeout failed
2020-03-19T17:41:40,761099 17185 0x00007f04807e0700 warning dtlsconnection            gstdtlsconnection.c:312 handle_timeout() <GstDtlsConnection@0x7f05106d4df0>  handling timeout failed
2020-03-19T17:41:40,763053 17185 0x00007f02f4331700 warning dtlsconnection            gstdtlsconnection.c:312 handle_timeout() <GstDtlsConnection@0x7f04c862c9f0>  handling timeout failed
2020-03-19T17:41:41,033989 17185 0x00007f02f5b34700 warning dtlsconnection            gstdtlsconnection.c:312 handle_timeout() <GstDtlsConnection@0x7f05751782a0>  handling timeout failed

from bbb-web log:
{"level":"info","message":"[mcs-controller] Fetched user broken-smoke-TIDaWIt","timestamp":"2020-03-19T16:37:27.439Z"}
{"level":"info","message":"[mcs-sfu-user] Added new SDP session red-night-BwCjs27 to user broken-smoke-TIDaWIt","timestamp":"2020-03-19T16:37:27.452Z"}
{"level":"info","message":"[mcs-balancer] Available hosts => [{\"url\":\"ws://127.0.0.1:8888/kurento\",\"ip\":\"---------\"}]","timestamp":"2020-03-19T16:37:27.453Z"}
{"level":"info","message":"[mcs-balancer] Chosen host is patient-sound-lVK6fog ws://127.0.0.1:8888/kurento --------- 464 11","timestamp":"2020-03-19T16:37:27.454Z"}
{"level":"info","message":"[mcs-sfu-user] Stopping session => red-night-BwCjs27","timestamp":"2020-03-19T16:37:27.454Z"}
{"error":{"type":"error","code":2003,"message":"MEDIA_SERVER_REQUEST_TIMEOUT","details":"Request has timed out","operation":"publish"},"level":"error","message":"[mcs-router] Reject operation publish with","timestamp":"2020-03-19T16:37:27.454Z"}
{"error":{"type":"error","code":2003,"message":"MEDIA_SERVER_REQUEST_TIMEOUT","details":"Request has timed out","operation":"publish"},"level":"error","message":"[mcs-api] Reject operation publish with","timestamp":"2020-03-19T16:37:27.455Z"}
{"level":"info","message":"[VideoManager] Stopping session 9628w_3kjmg4hcotzp-share","timestamp":"2020-03-19T16:37:27.489Z"}

**Comment by defnull** [comment]
We see this too. Recent version of BBB.

**Comment by aligot-cblue** [comment]
Please note restarting kurento-media-server (or simply killing it since systemd will restart it nicely) fix the issue. Users will have to restart camera/desktop sharing but will not be kicked out of the room.

**Comment by defnull** [comment]
Same or similar problem today with BBB 2.2.3. Open UDP sockets grow under load, until they hit a limit (around 30k) and kurento needs to be killed. But this time, the memory consumption was way better. Last time kurento was stopped by the kernel OOM killer because it had allocated over 16G RSS on a 32G Server.

**Comment by codegeek1001** [comment]
We just had a similar issue where Kurento media server is showing a insanely high CPU% usage:

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                                                          
10485 kurento   20   0 18.371g 742388  23232 S  2388  1.1 122200:04 kurento-media-s   

There is a live session running. I don't want to retart BBB completely. How do restart just kurento ? Is there a command for it ?

**Comment by ffdixon** [comment]
You can use this command

`systectl restart kurento-media-server`

**Comment by longlnk** [comment]
We have same isse with BBB 2.2, My kurento is running
![image](https://user-images.githubusercontent.com/15074179/82469740-a2a77980-9aee-11ea-9b22-428478448971.png)

Version:
![image](https://user-images.githubusercontent.com/15074179/82469892-d6829f00-9aee-11ea-87c1-035663ee61bc.png)

**Comment by codegeek1001** [comment]
Yep I can confirm too. We have constant usage at around 90 users and kurento and freeswitch CPU usage is through the roof. The script to restart it works but this is a bit difficult to manage since we cannot control exactly when it overflows.

**Comment by thitranthanh** [comment]
I have the same issue with BBB 2.2.x when the number of users joins the room up to 60-users and every user shared their camera. Memory usage of the Kurento very high (up to 90%)

![bbb_1](https://user-images.githubusercontent.com/6269892/92229723-1cb01280-eed4-11ea-83a2-34e714b515b6.png)
![bbb_2](https://user-images.githubusercontent.com/6269892/92229728-1e79d600-eed4-11ea-9070-f57dacbd1307.png)
![bbb_3](https://user-images.githubusercontent.com/6269892/92229732-20dc3000-eed4-11ea-8bb5-89368dc458ca.png)

**Comment by thitranthanh** [comment]
> You can use this command
> 
> `systectl restart kurento-media-server`

This command does not resolve our problem. It's a temporary solution.

**Comment by prlanzarin** [comment]
> We have the same issue with BBB 2.2.x when the number of users joins the room up to 60-users and every user shared their camera. Memory usage of the Kurento very high (up to 90%)

60 users, all of them with cameras, **is not supported**. Not even if you had a 2048 cores server because things don't scale vertically as they should. That's 3660 streams. So no, it won't work properly. It'll be unstable and unpredictable.

Look at stuff like video pagination (available in 2.2.23 onwards) or dynamic video profiles (available 2.2.22) and try to tune them according to your use case. It might give you better results.

And, please, do not resurrect an issue from 2018. This is a great topic to be discussed in the mailing lists, not in a 2 year old **closed** issue.

**Comment by thitranthanh** [comment]
Thank you for your reply and nice weekend.!

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by thitranthanh** [comment]
Hi @prlanzarin 

We had been resolved the performance issues on the BBB system. Currently, our system reached more than 70 users in a meeting room with their camera and freely click on next or previous. Today, we will load testing again and we expect the number of users can join a room more than 100 users.
