### ISSUE TITLE
Unable to join microphone after joining ListenOnly in Chrome (RC7)

### ISSUE THREAD

**Issue by pedrobmarin** [bigbluebutton/bigbluebutton#6167]
@prlanzarin showed to me this issue some days ago. AFAIK this is related with the browser trying to reset the audio output (or input, not sure) after a listen-only connection.

**Comment by prlanzarin** [comment]
Not only an issue with RC7. Output device selection on Chrome >= 67 is broken on all prior RCs, and that's the culprit behind the listen only -> mic thing and also with the output device selection in the audio settings modal.

I'm not able to open a PR right now, but I've pinpointed the cause to the HTML audio tag not having its `srcObject` nulled before trying to change the output device. 

The fix should be as follows: https://github.com/bigbluebutton/bigbluebutton/blob/v2.0.x-release/bigbluebutton-html5/imports/api/audio/client/bridge/sip.js#L381 => Add `audioContext.srcObject = null` before the `setSinkId` call.

@antobinary
