### ISSUE TITLE
mongodb expected in 127.0.1.1 instead of 127.0.0.1

### ISSUE THREAD

**Issue by SoloVeniaASaludar** [bigbluebutton/bigbluebutton#6170]
Trying to use the html5 client, all create/join failed due to nobody listening at port 3000.

After some time working on the issue, it seems related with content of file /usr/share/meteor/bundle/systemd_start.sh (included in package bbb-html5) that contains the sentences:

```
cd /usr/share/meteor/bundle
export ROOT_URL=http://127.0.0.1/html5client
export MONGO_OPLOG_URL=mongodb://127.0.1.1/local
export MONGO_URL=mongodb://127.0.1.1/meteor
export NODE_ENV=$ENVIRONMENT_TYPE
PORT=3000 /usr/share/node-v8.9.4-linux-x64/bin/node main.js
```

please, why 127.0.1.1 is used on these sentences, instead of 127.0.0.1 (own server address) ?

Must be changed it during installation or there are some other problem ?

**Comment by ffdixon** [comment]
Those values are correct.  In a default BigBlueButton installation, `mongodb` is listening on 127.0.1.1

~~~
# netstat -antp | grep 127.0.1.1
tcp        0      0 127.0.1.1:27017         0.0.0.0:*               LISTEN      30604/mongod
tcp        0      0 127.0.0.1:50114         127.0.1.1:27017         ESTABLISHED 30775/node
tcp        0      0 127.0.1.1:27017         127.0.0.1:49290         ESTABLISHED 30604/mongod
tcp        0      0 127.0.1.1:27017         127.0.0.1:50114         ESTABLISHED 30604/mongod
tcp        0      0 127.0.1.1:27017         127.0.0.1:51076         ESTABLISHED 30604/mongod
tcp        0      0 127.0.0.1:48742         127.0.1.1:27017         ESTABLISHED 30775/node
tcp        0      0 127.0.0.1:48744         127.0.1.1:27017         ESTABLISHED 30775/node
tcp        0      0 127.0.1.1:27017         127.0.0.1:48742         ESTABLISHED 30604/mongod
tcp        0      0 127.0.0.1:49238         127.0.1.1:27017         ESTABLISHED 30775/node
tcp        0      0 127.0.0.1:51076         127.0.1.1:27017         ESTABLISHED 30775/node
tcp        0      0 127.0.0.1:48740         127.0.1.1:27017         ESTABLISHED 30775/node
tcp        0      0 127.0.1.1:27017         127.0.0.1:48740         ESTABLISHED 30604/mongod
tcp        0      0 127.0.0.1:49290         127.0.1.1:27017         ESTABLISHED 30775/node
tcp        0      0 127.0.1.1:27017         127.0.0.1:49238         ESTABLISHED 30604/mongod
tcp        0      0 127.0.1.1:27017         127.0.0.1:48744         ESTABLISHED 30604/mongod
~~~

**Comment by SoloVeniaASaludar** [comment]
Hi,

Thanks for your answer.

From version 3.6 the default (the value if "bindIp" entry is not included in configuration file) is "localhost", previously it was 0.0.0.0 (see https://docs.mongodb.com/manual/release-notes/3.6-compatibility/#bind-ip-compatibility )

Moreover, config files that mongo team provides for Debian and Ubuntu distros defines it as 127.0.0.1 (see:
https://github.com/mongodb/mongo/blob/master/rpm/mongod.conf
and
https://github.com/mongodb/mongo/blob/master/debian/mongod.conf
)

It is a few surprising a machine listening at 127.0.1.1. Could be something given in the mongod command line or in a modified config file ? Or localhost in /etc/hosts pinting to 127.0.1.1 ?

Kind regards.
