### ISSUE TITLE
Minor improvements of custom presenter tools

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#6171]
- [ ] In #6168 we allow to have a single tool in the presenter toolbox. Do not trigger the expanding of the toolbox if we only have one item.
![peek 2018-10-22 13-00](https://user-images.githubusercontent.com/6312397/47306579-d52f7e80-d5fa-11e8-9760-f40dda7b7d12.gif)
- [ ] Handle the case when we pass an empty array of tools
![screenshot from 2018-10-22 13-04-18](https://user-images.githubusercontent.com/6312397/47306646-0445f000-d5fb-11e8-9243-ffad9844e23f.png)

**Comment by Tainan404** [comment]
In the case we have only one option, is it not better to show the hand and the tool in cases where the user does not want to interact with the multi-whiteboard?

**Comment by antobinary** [comment]
If we want 1 tool and hand we just pass the two options. We need  the option to have only 1 tool for simplicity reasons
