### ISSUE TITLE
Enable USB Video recorder for HTML5 client

### ISSUE THREAD

**Issue by 0000sir** [bigbluebutton/bigbluebutton#6183]
I have a HDMI-USB video capture for presenting some other video from a video player box.

When using flash client, I can choose this video capture as same as the usb webcam, but it is not available in the HTML5 client, there's no option for this video capture.

I can test it at https://www.cam-recorder.com/ this usb video capture works perfectly, can you make it available in the HTML5 client ? The flash client has really poor performance for hd videos.

or can you give some information about how to do it, thanks!

**Comment by ROBERT-MCDOWELL** [comment]
> The flash client has really poor performance for hd videos.
that is simply not true, you can set any quality within actionscript with the Camera class and H264 settings.
I'm using 4K quality in multicast in a private network since years now.

**Comment by ffdixon** [comment]
> but it is not available in the HTML5 client,

Can you try it with FireFox -- it let's you choose the video source when using the HTML5 client to share a video using WebRTC.

**Comment by 0000sir** [comment]
> The flash client has really poor performance for hd videos.
> that is simply not true, you can set any quality within actionscript with the Camera class and H264 settings.
> I'm using 4K quality in multicast in a private network since years now.

Sorry I didn't find these settings, can you give me some more information about that? Thanks.

**Comment by 0000sir** [comment]
> > but it is not available in the HTML5 client,
> 
> Can you try it with FireFox -- it let's you choose the video source when using the HTML5 client to share a video using WebRTC.

Yes, I tested with Firefox (ubuntu desktop) , no choice dialog or any other tips show up.
If there're a usb camera and a usb video capture, it opens the use camera directly.

**Comment by 0000sir** [comment]
I think this is caused by two kinds of html5 video capturing method:

`<input type="file" accept="image/*;capture=camera">`
or
`<input type="file" accept="video/*;capture=camcorder">`

is it right?

**Comment by ffdixon** [comment]
@0000sir Could you try this again on 

  https://demo.bigbluebutton.org/

and let us know if it's still an issue.  We've done quite a few updates recently to the ability to select and share video in the HTML5 client.
