### ISSUE TITLE
BBB 2.0.0-RC6 HTML5 webcam fails

### ISSUE THREAD

**Issue by rrsantin** [bigbluebutton/bigbluebutton#6191]
Hello everybody,

I'm having a problem to start the webcam sharing in a NAT free dedicated server, fresh install of BBB 2.0.0-RC6 when I try HTML5. Using flash, everything is OK.

The error message is something like: Error 1107: ICE negotiation failed

When I test on http://test.bigbluebutton.org/, the webcam works perfectly. 

> #bbb-conf --status
> red5: active
> tomcat7: active
> nginx: active
> freeswitch: active
> redis-server.service: active
> bbb-apps-akka: active
> bbb-transcode-akka: active
> bbb-fsesl-akka: active
> mongod: failed
> bbb-html5: active
> bbb-webrtc-sfu: active
--------------------------------------------------------------------
> #dpkg -l | grep bbb-webrtc-sfu
> ii  bbb-webrtc-sfu                        1:2.0.0-70                                 amd64        BigBlueButton WebRTC SFU
--------------------------------------------------------------------
> #dpkg -l | egrep 'bbb|kurento|kms'
> ii  bbb-apps                              1:2.0.0-52                                 amd64        BigBlueButton applications for Red5
> ii  bbb-apps-akka                         2.0.0-147                                  all          BigBlueButton Apps (Akka)
> ii  bbb-apps-screenshare                  1:2.0.0-41                                 amd64        BigBlueButton screenshare module for Red5
> ii  bbb-apps-sip                          1:2.0.0-14                                 amd64        BigBlueButton SIP module for Red5
> ii  bbb-apps-video                        1:2.0.0-29                                 amd64        BigBlueButton video module for Red5
> ii  bbb-apps-video-broadcast              1:2.0.0-8                                  amd64        BigBlueButton video broadcast module for Red5
> ii  bbb-client                            1:2.0.0-384                                amd64        BigBlueButton Flash client
> ii  bbb-config                            1:2.0.0-79                                 amd64        BigBlueButton configuration utilities
> ii  bbb-demo                              1:2.0.0-14                                 amd64        BigBlueButton API demos
> ii  bbb-freeswitch-core                   2:2.0.0-47                                 amd64        BigBlueButton build of FreeSWITCH
> ii  bbb-freeswitch-sounds                 1:1.6.7-9                                  amd64        FreeSWITCH Sounds
> ii  bbb-fsesl-akka                        2.0.0-27                                   all          BigBlueButton FS-ESL (Akka)
> ii  bbb-html5                             1:2.0.0-468                                amd64        The HTML5 components for BigBlueButton
> ii  bbb-mkclean                           1:0.8.7-4                                  amd64        Clean and optimize Matroska and WebM files
> ii  bbb-playback-presentation             1:2.0.0-27                                 amd64        BigBluebutton playback of presentation
> ii  bbb-record-core                       1:2.0.0-32                                 amd64        BigBlueButton record and playback
> ii  bbb-red5                              1:1.0.8-40                                 amd64        The Red5 server for BigBlueButton
> ii  bbb-swftools                          1:0.9.2-2                                  amd64        The swftools files for BigBlueButton
> ii  bbb-transcode-akka                    2.0.0-6                                    all          BigBlueButton Transcoder
> ii  bbb-web                               1:2.0.0-87                                 amd64        BigBlueButton API
> ii  bbb-webrtc-sfu                        1:2.0.0-70                                 amd64        BigBlueButton WebRTC SFU
> ii  bigbluebutton                         1:2.0.0-13                                 amd64        Open source web conferencing platform (bbb)
> ii  kms-core                              6.7.1+201806211620.27.ddca087              amd64        Kurento Core module
> ii  kms-elements                          6.7.0+201806211634.24.3923f1a              amd64        Kurento Elements module
> ii  kms-filters                           6.7.0+201806211640.18.d3dac3a              amd64        Kurento Filters module
> ii  kms-jsonrpc                           6.7.0+201806190347.8.8357b5e               amd64        Kurento JSON-RPC library
> ii  kmsjsoncpp                            1.6.3.xenial.20170725151047.d78deb7        amd64        Kurento jsoncpp library
> ii  kurento-media-server                  6.7.0+201806281201.25.cc67c2e              amd64        Kurento Media Server
--------------------------------------------------------------------
> #netstat -putan | grep 8888
> kurento   1798  0.0  0.1 2454356 35172 ?       Ssl  18:37   0:05 /usr/bin/kurento-media-server --gst-debug-level=3 --gst-debug=3,Kurento*:4,kms*:4,KurentoWebSocketTransport:5
> root      6237  0.0  0.0  14196   940 pts/0    S+   21:03   0:00 grep --color=auto kurento
--------------------------------------------------------------------

Does anyone have some idea about how to solve this issue?

Regards,

Santin

**Comment by rrsantin** [comment]
> Hi Santin, are you for a few minutes now?

Yep

**Comment by ffdixon** [comment]
Great -- I'm on on https://test.bigbluebutton.org/.

**Comment by ffdixon** [comment]
Good testing with you @rrsantin.  Looks like we're able to share webcams when connecting from outside  your network, but not from within.  You may try setting up a TURN server (outside your network), for BigBlueButton, see: http://docs.bigbluebutton.org/install/install.html#setup-a-turn-server

**Comment by rrsantin** [comment]
Hello Fred,

First of all, I'd like to thank you for testing my installation yesterday.

Continuing my tests, I realized that:
-Inside my network, using Firefox, the webcam works.
-Inside my network, using Google Chrome, the webcam doesn't work.
-Outside of my network, using the Chrome of my cell phone, the webcam works for a while (5 minutes) and then it stops.

**Comment by ffdixon** [comment]
Hi,

> -Inside my network, using Firefox, the webcam works.
> -Inside my network, using Google Chrome, the webcam doesn't work.

Hmm ... I wonder if it Chrome would work with a turn server.  We have a turn server setup on https://test.bigbluebutton.org/.  Does that work with Chrome?

> -Outside of my network, using the Chrome of my cell phone, the webcam works for a while (5 minutes) 
and then it stops.

Can you test against https://test.bigbluebutton.org/ and see if you get the same results.

**Comment by rrsantin** [comment]
> Hi,
> 
> > -Inside my network, using Firefox, the webcam works.
> > -Inside my network, using Google Chrome, the webcam doesn't work.
> 
> Hmm ... I wonder if it Chrome would work with a turn server. We have a turn server setup on https://test.bigbluebutton.org/. Does that work with Chrome?
Yes, it works perfectly. The TURN server should be placed "after" my border firewall, right?
> 
> > -Outside of my network, using the Chrome of my cell phone, the webcam works for a while (5 minutes)
> > and then it stops.
> 
> Can you test against https://test.bigbluebutton.org/ and see if you get the same results.
Yes, same results.

**Comment by ffdixon** [comment]
Can you first try adding a STUN server to the Kurento configuration, see:

  http://docs.bigbluebutton.org/html/html5-install.html#extra-steps-when-server-is-behind-nat

And if that doesn't get it work, you can use bbb-install.sh to setup a TURN server, see

  https://github.com/bigbluebutton/bbb-install#install-a-turn-server

**Comment by ffdixon** [comment]
Need to refactor how mongod is getting started.  Currently, there are two instances running -- one from the mongod package, and a second from bbb-html5 package.

~~~
root@m047:~# ps -aefww | grep mongo
root      6841  6822  0 21:05 pts/1    00:00:00 grep --color=auto mongo
root     29837     1  0 20:03 ?        00:00:22 mongod --config ./mongo-ramdisk.conf --oplogSize 8 --replSet rs0 --noauth --nojournal
mongodb  30066     1  0 20:03 ?        00:00:15 /usr/bin/mongod --config /etc/mongod.conf
~~~

**Comment by ffdixon** [comment]
We've refactored how mongod starts up in the latest build of BigBlueButton 2.2-beta (soon to be released).
