### ISSUE TITLE
BBB not working on kernel Linux 2.6.32-042stab133.2 on x86_64 on OpenVZ VPS 

### ISSUE THREAD

**Issue by jc-jnet** [bigbluebutton/bigbluebutton#6202]
To save people a lot of time troubleshooting, please would the BBB developers update the Minimum server requirements section here, http://docs.bigbluebutton.org/install/install.html#minimum-server-requirements?

BBB does not work on kernel Linux 2.6.32-042stab133.2 on x86_64 on OpenVZ VPS. It does work on a KVM VPS running kernel Linux 4.4.0-138-generic on x86_64.

Have not tested it on kernels in-between these kernel versions. Maybe other BBB users can report which kernels they are using to run BBB successfully.

**Comment by ffdixon** [comment]
Updated

  http://docs.bigbluebutton.org/install/install.html#minimum-server-requirements

to require Kernel 4.x and added a check with `uname -r` to have the administrator verify the kernel version.

Thanks for pointing this out.

**Comment by jc-jnet** [comment]
I guess its due to docker requiring the higher kernel version?

**Comment by ffdixon** [comment]
If your going to run GreenLight, then you need to have a 4.x kernel.  Still, the 2.6 kernel is very old and you should be running Ubuntu 16.04 on a more recent 4.x kernel.

**Comment by jc-jnet** [comment]
Agreed, it is very old but still being offered by various VPS providers. I was attempting to install BBB without GreenLight or HTML5. I tried version 1.1 and version 2.0 BBB, just would not work. Mainly due to FreeSwitch issues.
