### ISSUE TITLE
FreeSWITCH upgrade script should preserve STUN settings

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#6203]
Reported in
 
  https://groups.google.com/d/msg/bigbluebutton-users/ArDhDB8Cj3A/alYsLkU1BwAJ

**Comment by kepstin** [comment]
Note that the freeswitch package isn't responsible - the configuration file for stun/turn servers is installed by bbb-web

**Comment by prlanzarin** [comment]
Addressed by https://github.com/bigbluebutton/bigbluebutton/pull/11804.
