### ISSUE TITLE
bashisms in kurento-media-server.postinst

### ISSUE THREAD

**Issue by jwarnier** [bigbluebutton/bigbluebutton#6204]
It is impossible to successfully install package kurento-media-server 6.7.0+201806281201.25.cc67c2e on Ubuntu Xenial (and I guess others) due to bashisms in kurento-media-server.postinst, while the shebang says #!/bin/sh.

The bashism in question is the use of double [[ ]] in conditions.

Hope this helps.

**Comment by ffdixon** [comment]
Good catch -- we must be testing on servers that has /bin/sh pointing to /bin/bash.  You can edit the file

~~~
/var/lib/dpkg/info/kurento-media-server.postinst
~~~

and fix the top to be

~~~
#!/bin/bash
~~~

and run

~~~
sudo apt-get install -f
~~~

**Comment by jwarnier** [comment]
I had already, but reported this for it to be solved for everybody else, and for future installs/upgrades, especially since this is a trivial fix.

**Comment by ffdixon** [comment]
Thanks again for pointing this out.  The install script and it now reads and shouldn't be causing any issues in current release of BigBlueButton 2.0 (if it still does let us know!).

~~~
# cat /var/lib/dpkg/info/kurento-media-server.postinst
#!/bin/sh

#check if the user already exists
if [ `cat /etc/passwd | grep kurento | wc -l` -eq "0" ]; then
  useradd -d /var/kurento/ kurento
fi

chown kurento -R /var/kurento
mkdir -p /var/log/kurento-media-server
chown kurento -R /var/log/kurento-media-server
~~~
