### ISSUE TITLE
Remove the option to unmute other users from the HTML5 client in 2.2

### ISSUE THREAD

**Issue by KDSBrowne** [bigbluebutton/bigbluebutton#6208]
If a Moderator tries to unmute a specific user other than themself, via the option in the userlist-user-item menu, the meeting breaks for the moderator.

https://www.youtube.com/watch?v=mvAAD4rkdVg&feature=youtu.be

**Comment by capilkey** [comment]
The problem isn't that unmuting breaks the meeting. In 2.2 moderators can't unmute anymore. It's a security change so that a moderator can't turn on your microphone and listen in when you're away from your keyboard.

**Comment by KDSBrowne** [comment]
That makes sense.

**Comment by antobinary** [comment]
Implemented in #6267
