### ISSUE TITLE
apt-get install -y bbb-html5 behind proxy meteor and npm problems

### ISSUE THREAD

**Issue by wolfganghuebsch** [bigbluebutton/bigbluebutton#6213]
Hi, 

when I call
apt-get install -y bbb-html5
the installation behind a webproxy works only until

```
Updating Node packages for bbb-html5 (this may take a moment)
[ .................] \ fetchMetadata: sill install loadAllDepsIntoIdealTree
```

Since now it stucks.

I configures apt and other services so that they can use the proxy and it works well - except this step.

Best regards,
Wolfgang

**Comment by ffdixon** [comment]
> I configures apt and other services so that they can use the proxy and it works well - except this step.

How did you configure the other services to use proxy?

**Comment by wolfganghuebsch** [comment]
in .bashrc I have:

######################
# User Variables (Edit These!)
######################
username="user"
password="password"
proxy="10.98.0.1"

######################
# Environement Variables
# (npm does use these variables, and they are vital to lots of applications)
######################
export HTTPS_PROXY="http://$username:$password@$proxy"
export HTTP_PROXY="http://$username:$password@$proxy"
export http_proxy="http://$username:$password@$proxy"
export https_proxy="http://$username:$password@$proxy"
export all_proxy="http://$username:$password@$proxy"
export ftp_proxy="http://$username:$password@$proxy"
export dns_proxy="http://$username:$password@$proxy"
export rsync_proxy="http://$username:$password@$proxy"
export no_proxy="127.0.0.10/8, localhost, 10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16"

######################
# npm Settings
######################
npm config set registry http://registry.npmjs.org/
npm config set proxy "http://$username:$password@$proxy"
npm config set https-proxy "http://$username:$password@$proxy"
npm config set strict-ssl false
echo "registry=http://registry.npmjs.org/" > ~/.npmrc
echo "proxy=http://$username:$password@$proxy" >> ~/.npmrc
echo "strict-ssl=false" >> ~/.npmrc
echo "http-proxy=http://$username:$password@$proxy" >> ~/.npmrc
echo "http_proxy=http://$username:$password@$proxy" >> ~/.npmrc
echo "https_proxy=http://$username:$password@$proxy" >> ~/.npmrc
echo "https-proxy=http://$username:$password@$proxy" >> ~/.npmrc

######################
# WGET SETTINGS
# (Bonus Settings! Not required for npm to work, but needed for lots of other programs)
######################
echo "https_proxy = http://$username:$password@$proxy/" > ~/.wgetrc
echo "http_proxy = http://$username:$password@$proxy/" >> ~/.wgetrc
echo "ftp_proxy = http://$username:$password@$proxy/" >> ~/.wgetrc
echo "use_proxy = on" >> ~/.wgetrc

######################
# CURL SETTINGS
# (Bonus Settings! Not required for npm to work, but needed for lots of other programs)
######################
echo "proxy=http://$username:$password@$proxy" > ~/.curlrc
in .wgetrc I have

https_proxy = http://user:pass@IP:port/
http_proxy = http://user:pass@IP:port/
ftp_proxy = http://user:pass@IP:port/
use_proxy = on

And the same for apt and npm
So some are duplicates.

**Comment by liberioafonso** [comment]
I have the same problem, I do not know how to solve, the machine proxy is releasing, someone could help.

**Comment by liberioafonso** [comment]
@ffdixon Can you help us?

**Comment by matiasilva** [comment]
Feel free to post in https://groups.google.com/forum/#!forum/bigbluebutton-setup for further support.
