### ISSUE TITLE
clipPath property in foreignObject

### ISSUE THREAD

**Issue by SoloVeniaASaludar** [bigbluebutton/bigbluebutton#6223]
In this source code:
[whiteboard/annotations/text/component](https://github.com/bigbluebutton/bigbluebutton/blob/master/bigbluebutton-html5/imports/ui/components/whiteboard/annotations/text/component.jsx
)

the following tag appears:
```
        <foreignObject
          clipPath={`url(#${this.props.annotation.id})`}
          x={results.x}
          y={results.y}
          width={results.width}
          height={results.height}
        >

```

is it a typo ? usually the property name is "clip-path" not "clipPath" (do not confuse with the tag "clipPath").

**Comment by GhaziTriki** [comment]
As I see it correctly renders the tag under FireFox

![image](https://user-images.githubusercontent.com/4991088/68123795-311b2b80-ff0e-11e9-9384-fdf36b394361.png)

@antobinary Do you confirm that it renders like it is expected?

**Comment by pedrobmarin** [comment]
Camel-cased properties are a React thing.
