### ISSUE TITLE
BBB - Screen sharing is ends after 5 mins

### ISSUE THREAD

**Issue by SivaRI** [bigbluebutton/bigbluebutton#6233]
Hi.. I tested http://test.bigbluebutton.org/. Screen sharing is ends after 5 mins. Is there any limitations to share the screen. I checked with my laptop.
Error 1108

**Comment by ffdixon** [comment]
There are no limitations on this server.  Could you try it with both https://test.bigbluebutton.org/ and https://demo.bigbluebutton.org/.  What browser are you using to test?

**Comment by SivaRI** [comment]
Both have the same problem. I used chrome browser Version 70.0.3538.77.  I tried many times, but the same issue occurs.

**Comment by ffdixon** [comment]
Just to confirm, you are able to start screen sharing, but it stops after 5 minutes.  

This is very strange, but if it's consistent it points to a repeatable bug (which is easier to find and fix).  Is it possible for you to test your laptop on different network conditions -- such as putting it on a wifi hotspot and then try it again.  This would isolate if there are any network issues affecting the screen sharing.

**Comment by SivaRI** [comment]
It is working perfectly with my mobile hotspot. But not with my office LAN.

**Comment by ffdixon** [comment]
> But not with my office LAN.

That was helpful!  The browser sends screen sharing via a UDP connection.  If it stops after 5 minutes, it suggests the office has a firewall that is closing long running UDP connections (after 5 minutes).

Without any knowledge of your firewall, we recommend contacting your IT department, let them know, and have them whitelist the test.bigbluebutton.org server (or any other BigBlueButton server you intend to use).  Then it should work as it does with your hotspot.

**Comment by SivaRI** [comment]
Thank you very much.
