### ISSUE TITLE
Fix issue with kurento-websocket-pool-size 

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#6238]
In BigBlueButton 2.0-RC7, the post install script `/var/lib/dpkg/info/bbb-webrtc-sfu.postinst` sets `kurento-websocket-pool-size: 1` in `/usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml`

~~~
    change_yml_value $TARGET kurento-websocket-pool-size 1
~~~

to (temporarily) fix an issue with the web socket pools in `bbb-webrtc-sfu`.

**Comment by antobinary** [comment]
Obsolete
