### ISSUE TITLE
WebRtc error 1002

### ISSUE THREAD

**Issue by Fabio7586** [bigbluebutton/bigbluebutton#6239]
Hello, after a year that my installation of bigbluebutton works greatly, suddenly it give me error 1002. I don't know why! Can you help me? What info have you need?
Thank you

**Comment by Fabio7586** [comment]
Hello, thank you for response!
Server didn't updated from bigbluebutton installation.
When i write 
`sudo bbb-conf --restart`
bigbluebutton wont restart and i need to restart server from ovh panel. and yes, i get audio from https://test.bigbluebutton.org/.

Thank you

**Comment by ffdixon** [comment]
Are you getting any error messages when you do `sudo bbb-conf --restart`?

**Comment by ffdixon** [comment]
Closing this issue due to no response.  If anyone reading this thread encounters a similar problem, please test first with

  https://demo.bigbluebutton.org/

and if you encounter an issue, let us know

  https://bigbluebutton.org/support
