### ISSUE TITLE
Freezing webcam broadcasting, HTML5, Firefox, Android 5.1

### ISSUE THREAD

**Issue by Russell8** [bigbluebutton/bigbluebutton#6240]
Hello!
We use tablets with Androids 5.1 for studying.
BigBlueButton (client collection: 475, version HTML5).
On this system, Google Chrome does not allow viewing the stream from the webcam of a teacher (it is constantly loading).
Broadcasting on these tablets (Androids 5.1) can only be viewed via Firefox. In this case, the broadcast freezes after 50 seconds after the start of the session. If a teacher moves hand proximate to a camera ( almost touching it), a video unfreezes. I noticed that if a user connects via a smartphone from Androids 8 using Firefox to the session, then  freezes on the tablets disappears on their own without waving in front of the camera (freezes appears and then disappears in 1-2 sec)  
What kind of technical issue can cause this bug?
How it can be solved to enable Firefox to work properly without touching a camera or without an additional device with Firefox among customers?
Thanks in advance!

**Comment by ffdixon** [comment]
Do you have a tablet/phone running Android 6.0+ on the same network that you can test with https://test.bigbluebutton.org/?

**Comment by ffdixon** [comment]
Closing this issue due to no response.  If anyone reading this thread encounters a similar problem, please test first with

  https://demo.bigbluebutton.org/

and if you encounter an issue, let us know

  https://bigbluebutton.org/support
