### ISSUE TITLE
Prompt the user with a "Are you sure you want to clear all annotations" when the "clear all annotations whiteboard item is selected.

### ISSUE THREAD

**Issue by tylercopeland** [bigbluebutton/bigbluebutton#6244]

**Comment by VITSarah** [comment]
Hi,

is there an update on whether this feature has been included in 2.4 or not? Or how I can activate it?

**Comment by antobinary** [comment]
Hi @VITSarah 
This enhancement has not been implemented yet. Feel free to hit "subscribe" here on the page to be notified when the status of the issue has changed (or on new comments).

**Comment by mathjayden** [comment]
Any update to implement this?
