### ISSUE TITLE
Add "End Meeting" as a dropdown menu item

### ISSUE THREAD

**Issue by tylercopeland** [bigbluebutton/bigbluebutton#6245]

**Comment by tylercopeland** [comment]
Here's a simple concept that allows presenters to end the meeting without having to logout. 
cc: @ffdixon 

![html5-general-dropdown](https://user-images.githubusercontent.com/1273169/48388811-ba679b80-e6c8-11e8-9f8a-d61247f40cff.png)

**Comment by aogilvie** [comment]
This is awesome. Avoids any confusion and a simple solution.
