### ISSUE TITLE
maxParticipants: maxModerators & maxAttendees

### ISSUE THREAD

**Issue by sazanof** [bigbluebutton/bigbluebutton#6255]
Hello!
Please tell me if the API when creating an appointment parameter responsible for assigning a **limit** on the number of **moderators** and **attendees**?
How can I use the API to attach a user only as a listener?

**Comment by capilkey** [comment]
The maxParticipants is the total number of users. BBB-Web doesn't care what type of user they are. There's no way to make it ignore some users either. I wouldn't really recommend using that property at all, it's much better to implement the restriction in your front-end application with whatever specific requirements you need.

**Comment by capilkey** [comment]
This isn't an actual issue with BBB so I'm going to close it. In the future, please post queries like this to one of the BigBlueButton mailing lists.

https://groups.google.com/forum/#!topic/bigbluebutton-users
https://groups.google.com/forum/#!topic/bigbluebutton-setup
https://groups.google.com/forum/#!topic/bigbluebutton-dev
