### ISSUE TITLE
Update the default width of the chat panel so that the placeholder text doesn't fall onto two lines. 

### ISSUE THREAD

**Issue by tylercopeland** [bigbluebutton/bigbluebutton#6257]
**Current Implementation**
<img width="1392" alt="screen shot 2018-11-19 at 7 38 35 am" src="https://user-images.githubusercontent.com/1273169/48707785-8a3f6180-ebce-11e8-8747-ab29a9739f20.png">

**Recommended View**
<img width="1392" alt="screen shot 2018-11-19 at 7 39 55 am" src="https://user-images.githubusercontent.com/1273169/48707798-962b2380-ebce-11e8-93a3-7ab7bd361c75.png">

**Comment by antobinary** [comment]
Addressed in #6442
