### ISSUE TITLE
Improve handling of multiple html5 users joining at the same time

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#6259]

**Comment by ffdixon** [comment]
@antobinary Have the recent improvements to the HTML5 addressed this issue?

Also, this issue doesn't give any steps to reproduce or measure (how many users joining at the same time should be supported)?

**Comment by antobinary** [comment]
Addressed in https://github.com/bigbluebutton/bigbluebutton/pull/10349
