### ISSUE TITLE
Breakouts: Drag & drop users into rooms

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#6261]
![screenshot from 2018-11-19 10-06-26](https://user-images.githubusercontent.com/6312397/48709062-1e1b2880-ebe3-11e8-8b27-bdbeaad85cc2.png)

**Comment by ffdixon** [comment]
It's actually how we implemented breakout rooms in the Flash client, see

  https://www.youtube.com/watch?v=iR3v-i7R5t0&feature=youtu.be

**Comment by antobinary** [comment]
Implemented in #6276
