### ISSUE TITLE
Obey the configuration option for allowStartStopRecording

### ISSUE THREAD

**Issue by capilkey** [bigbluebutton/bigbluebutton#6263]
In bbb-web, akka-apps, and the Flash client, we have a property called "allowStartStopRecording". It can be set on the create call and there is a default in bigbluebutton.properties https://github.com/bigbluebutton/bigbluebutton/blob/45cd830f96383ffefe2d3104701c6d2237a7df23/bigbluebutton-web/grails-app/conf/bigbluebutton.properties#L180 

It is processed by bbb-web and sent along with the CreateMeeting messages. When the value is "false" the option to start and stop the recording in the HTML5 client needs to hidden.

This property is usually used with the "autoStartRecording" property, also in bigbluebutton.properties, to force the recording to start and make sure that the attendees cannot stop it.

**Comment by capilkey** [comment]
Looks like support for the property is already in the HTML5 client. I missed it in my original search of the code.

**Comment by ux-jules** [comment]
Is this an option that has to be configured on the back end? Or is there a way to do it in the user interface?

**Comment by capilkey** [comment]
It's an admin option in /var/lib/tomcat7/webapps/bigbluebutton/WEB-INF/classes/bigbluebutton.properties or set on the create meeting API call. Turns out it's all moot though because it already works.

**Comment by ux-jules** [comment]
Cool. thanks. :)
