### ISSUE TITLE
"failed to fetch config.xml"

### ISSUE THREAD

**Issue by aukion** [bigbluebutton/bigbluebutton#6266]
Actualy, we have installed BBB in our server in the domain  https://univirtualcescijuc.com/ and we can create meetings but when try to join as moderator o attendee get the next error:

"failed to fetch config.xml"

This just happen when test the server in the domain but in local network works fine

For test with API you can check on:

http://mconf.github.io/api-mate/#server=https://univirtualcescijuc.com/bigbluebutton/&sharedSecret=03d7e7c5ed6a232b4a3a783e195987ce

BBB Versión: 2.0.
No problems in installation.

bbb-conf --check results:

```

**root@univirtual-ProLiant-ML350-G6:/etc/ssl/newssl# bbb-conf --check

BigBlueButton Server 2.0.0-RC6 (1048)
                    Kernel version: 4.15.0-39-generic
                      Distribution: Ubuntu 16.04.5 LTS (64-bit)
                            Memory: 34990 MB

/var/www/bigbluebutton/client/conf/config.xml (bbb-client)
  		Port test (tunnel): rtmp://univirtualcescijuc.com
                              red5: univirtualcescijuc.com
              useWebrtcIfAvailable: true

/opt/freeswitch/etc/freeswitch/sip_profiles/external.xml (FreeSWITCH)
                         websocket: :7443
                    WebRTC enabled: true

/etc/nginx/sites-available/bigbluebutton (nginx)
                       server name: univirtualcescijuc.com
                              port: 80, [::]:80
                              port: 443 ssl
                    bbb-client dir: /var/www/bigbluebutton

/var/lib/tomcat7/webapps/bigbluebutton/WEB-INF/classes/bigbluebutton.properties (bbb-web)
                      bbb-web host: univirtualcescijuc.com

/var/lib/tomcat7/webapps/demo/bbb_api_conf.jsp (API demos)
                               url: univirtualcescijuc.com

/usr/share/red5/webapps/bigbluebutton/WEB-INF/red5-web.xml (red5)
                  voice conference: FreeSWITCH

/usr/local/bigbluebutton/core/scripts/bigbluebutton.yml (record and playback)
                     playback host: univirtualcescijuc.com
                            ffmpeg: 4.0.2-2~16.04.york0


** Potential problems described below **
# IP does not match:
#                           IP from ifconfig: 192.168.15.15
#   /etc/nginx/sites-available/bigbluebutton: univirtualcescijuc.com
# Warning: API URL IPs do not match host:
#
#                                IP from ifconfig: 192.168.15.15
#  /var/lib/tomcat7/webapps/demo/bbb_api_conf.jsp: univirtualcescijuc.com

# Warning: The voice application may not have registered with the sip server.
#   Try running: 
#
#      sudo bbb-conf --clean
#

....................
# Error: Could not connect to the configured hostname/IP address
#
#    https://univirtualcescijuc.com/
#
# If your BigBlueButton server is behind a firewall, see FAQ.

# Error: Unable to connect to port 1935 (RTMP) on univirtualcescijuc.com

# Warning: The setting of 192.168.15.10 for bbb.sip.app.ip in
#
#    /usr/share/red5/webapps/sip/WEB-INF/bigbluebutton-sip.properties
#
# does not match the local IP address (192.168.15.15).
# (This is OK if you've manually changed the values to an external 
# FreeSWITCH server.)

# Error: Could not detect FreeSWITCH listening on port 5060

# Warning: The setting of 192.168.15.10 for proxy_pass in
#
#    /etc/bigbluebutton/nginx/sip.nginx
#
# does not match the local IP address (192.168.15.15).
# (This is OK if you've manually changed the values)

# Warning: The setting of 192.168.15.10 for local_ip_v4 in
#
#    /opt/freeswitch/etc/freeswitch/vars.xml
#
# does not match the local IP address (192.168.15.15).
# (This is OK if you've manually changed the values)

# Warning: The API demos are installed and accessible from:
#
#    https://univirtualcescijuc.com/demo/demo1.jsp
#
# These API demos allow anyone to access your server without authentication
# to create/manage meetings and recordings. They are for testing purposes only.
# If you are running a production system, remove them by running:
#
#    sudo apt-get purge bbb-demo

# Error: Unable to reach default URL for presentation:
#
#    https://univirtualcescijuc.com/default.pdf
#
# Check value for beans.presentationService.defaultUploadedPresentation in
#   /var/lib/tomcat7/webapps/bigbluebutton/WEB-INF/classes/bigbluebutton.properties

```**

SSL correct

**Comment by ffdixon** [comment]
This might be a problem with the certificate.  Did you use [bbb-install.sh](https://github.com/bigbluebutton/bbb-install) to install (which uses Let's Encrypt for a certificate) or a certificate from a different provider?

Can you login to your BigBlueButton server and run the command

~~~
wget https://univirtualcescijuc.com/default.pdf
~~~

and let us know if it succeeds without error.

Can you also post the output of

~~~
bbb-conf --status
~~~

**Comment by capilkey** [comment]
The server has a GoDaddy certificate. I don't see any warnings in my browser. I think this is a case where the domain name resolves to the external IP and the server can't access the external IP. I think a hosts file change to set "univirtualcescijuc.com 192.168.15.15" would get the client loading.

There's also an additional problem where the server's original IP when installed was "192.168.15.10" and some time later it was changed to "192.168.15.15". The audio won't work until the warnings are resolved.

**Comment by aukion** [comment]
bbb-conf --status:


`root@univirtual-ProLiant-ML350-G6:/etc/ssl/newssl# bbb-conf --status
red5: active
tomcat7: active
nginx: active
freeswitch: active
redis-server.service: active
bbb-apps-akka: active
bbb-transcode-akka: active
bbb-fsesl-akka: active
root@univirtual-ProLiant-ML350-G6:/etc/ssl/newssl# 
`

**Comment by capilkey** [comment]
@aukion What is the result of `wget https://univirtualcescijuc.com/default.pdf`?

**Comment by aukion** [comment]
Outter LAN Network we have the next result:

`MacBook-Pro-de-Alfredo:~ CasasEn360$ wget https://univirtualcescijuc.com/default.pdf
--2018-11-20 13:32:52--  https://univirtualcescijuc.com/default.pdf
Resolviendo univirtualcescijuc.com (univirtualcescijuc.com)... 187.178.230.116
Connecting to univirtualcescijuc.com (univirtualcescijuc.com)[187.178.230.116]:443... connected.
 HTTP request send , waiting response... 200 OK
Length: 369690 (361K) [application/pdf]
Grabando a: "default.pdf"

default.pdf         100%[===================>] 361.03K  1.14MB/s    en 0.3s    

2018-11-20 13:32:53 (1.14 MB/s) - "default.pdf" saved [369690/369690]

MacBook-Pro-de-Alfredo:~ CasasEn360$ 
`

**Comment by capilkey** [comment]
The wget needs to be run on the BigBlueButton server not your personal computer (ie run as root@univirtual-ProLiant-ML350-G6).

**Comment by ffdixon** [comment]
You need to edit some of the configuration files (the warning messages will guide you) and update the settings from using the old IP address: 192.168.15.10 to the new one 192.168.15.15.

**Comment by aukion** [comment]
**New bbb-conf --check**  (We revised warning for SIP):

**

root@univirtual-ProLiant-ML350-G6:/etc/ssl/newssl# bbb-conf --check

BigBlueButton Server 2.0.0-RC6 (1048)
                    Kernel version: 4.15.0-39-generic
                      Distribution: Ubuntu 16.04.5 LTS (64-bit)
                            Memory: 34990 MB

/var/www/bigbluebutton/client/conf/config.xml (bbb-client)
  		Port test (tunnel): rtmp://univirtualcescijuc.com
                              red5: univirtualcescijuc.com
              useWebrtcIfAvailable: true

/opt/freeswitch/etc/freeswitch/sip_profiles/external.xml (FreeSWITCH)
                         websocket: :7443
                    WebRTC enabled: true

/etc/nginx/sites-available/bigbluebutton (nginx)
                       server name: univirtualcescijuc.com
                              port: 80, [::]:80
                              port: 443 ssl
                    bbb-client dir: /var/www/bigbluebutton

/var/lib/tomcat7/webapps/bigbluebutton/WEB-INF/classes/bigbluebutton.properties (bbb-web)
                      bbb-web host: univirtualcescijuc.com

/var/lib/tomcat7/webapps/demo/bbb_api_conf.jsp (API demos)
                               url: univirtualcescijuc.com

/usr/share/red5/webapps/bigbluebutton/WEB-INF/red5-web.xml (red5)
                  voice conference: FreeSWITCH

/usr/local/bigbluebutton/core/scripts/bigbluebutton.yml (record and playback)
                     playback host: univirtualcescijuc.com
                            ffmpeg: 4.0.2-2~16.04.york0


** Potential problems described below **
# IP does not match:
#                           IP from ifconfig: 192.168.15.15
#   /etc/nginx/sites-available/bigbluebutton: univirtualcescijuc.com
# Warning: API URL IPs do not match host:
#
#                                IP from ifconfig: 192.168.15.15
#  /var/lib/tomcat7/webapps/demo/bbb_api_conf.jsp: univirtualcescijuc.com

....................
# Error: Could not connect to the configured hostname/IP address
#
#    https://univirtualcescijuc.com/
#
# If your BigBlueButton server is behind a firewall, see FAQ.

# Error: Unable to connect to port 1935 (RTMP) on univirtualcescijuc.com

# Warning: The API demos are installed and accessible from:
#
#    https://univirtualcescijuc.com/demo/demo1.jsp
#
# These API demos allow anyone to access your server without authentication
# to create/manage meetings and recordings. They are for testing purposes only.
# If you are running a production system, remove them by running:
#
#    sudo apt-get purge bbb-demo

# Error: Unable to reach default URL for presentation:
#
#    https://univirtualcescijuc.com/default.pdf
#
# Check value for beans.presentationService.defaultUploadedPresentation in
#   /var/lib/tomcat7/webapps/bigbluebutton/WEB-INF/classes/bigbluebutton.properties


**

Actualy we have the same error 


![captura de pantalla 2018-11-20 a la s 13 49 56](https://user-images.githubusercontent.com/5127093/48798896-58f88b80-eccb-11e8-989c-b2e540f5900b.png)

**Comment by aukion** [comment]
Inner LAN Network:

`**
root@univirtual-ProLiant-ML350-G6:/etc/ssl/newssl# wget https://univirtualcescijuc.com/default.pdf
--2018-11-20 13:53:25--  https://univirtualcescijuc.com/default.pdf
Resolving univirtualcescijuc.com (univirtualcescijuc.com)... 187.178.230.116
Connecting to univirtualcescijuc.com (univirtualcescijuc.com)|187.178.230.116|:443... failed: Connection refused.
root@univirtual-ProLiant-ML350-G6:/etc/ssl/newssl# 

**`

**Comment by capilkey** [comment]
The server can't connect to itself. The routing of your server's network is rejecting calls from local server -> external IP so you need to either fix the routing so that it works or add a hosts file resolution.  The quickest fix would be to edit the `/etc/hosts` file on your server and add a line with `192.168.15.15 univirtualcescijuc.com`.  The better fix would be to figure out why your server isn't able to connect to the public IP (probably need to ask whoever administrates the hosting environment).

**Comment by aukion** [comment]
/etc/hosts file content:

GNU nano 2.5.3                                                       File: /etc/hosts                                                                                                                     

`127.0.0.1       localhost`
`127.0.1.1       univirtual-ProLiant-ML350-G6`

`# The following lines are desirable for IPv6 capable hosts`
`::1     ip6-localhost ip6-loopback`
`fe00::0 ip6-localnet`
`ff00::0 ip6-mcastprefix`
`ff02::1 ip6-allnodes`
`ff02::2 ip6-allrouters`

**Comment by aukion** [comment]
New /etc/hosts contet:


```

127.0.0.1       localhost
127.0.1.1       univirtual-ProLiant-ML350-G6

#For Big Blue Button Access
192.168.15.15 univirtualcescijuc.com

# The following lines are desirable for IPv6 capable hosts
::1     ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
```

**Comment by capilkey** [comment]
What happens when you do the wget on the server now?

**Comment by aukion** [comment]
```
root@univirtual-ProLiant-ML350-G6:/etc/ssl/newssl# wget https://univirtualcescijuc.com/default.pdf
--2018-11-20 14:52:29--  https://univirtualcescijuc.com/default.pdf
Resolving univirtualcescijuc.com (univirtualcescijuc.com)... 192.168.15.15
Connecting to univirtualcescijuc.com (univirtualcescijuc.com)|192.168.15.15|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 369690 (361K) [application/pdf]
Saving to: ‘default.pdf’

default.pdf                                        100%[================================================================================================================>] 361.03K  --.-KB/s    in 0.005s  

2018-11-20 14:52:29 (72.1 MB/s) - ‘default.pdf’ saved [369690/369690]

```

**Comment by aukion** [comment]
Great. 

We could connect to meeting.

Checking all elements (mic, video, Dashboard, chat, recordings and playbacks)

![captura de pantalla 2018-11-20 a la s 14 55 10](https://user-images.githubusercontent.com/5127093/48802364-b218ed00-ecd4-11e8-82b4-bab94acc8037.png)

**Comment by aukion** [comment]
At start audio we see the next message : 

WebRTC Connection failed:

The problem has been found in WebRTC: Error 1010:  Exhausted trading ICE time ¿Do you want to try with flash?

**Comment by capilkey** [comment]
Your server is sending the local IP for it's WebRTC audio candidate. From the browser console, "a=candidate:5239784630 1 udp 659136 192.168.15.15 17908 typ host generation 0". Which won't connect. You might have success with the firewall steps here, http://docs.bigbluebutton.org/install/install.html#configure-bigbluebutton-behind-a-firewall. You will also probably need the dummy NIC steps so that FreeSWITCH has something to bind to.

**Comment by aukion** [comment]
Thank you so much to all people to help us!

**Comment by gasperinia** [comment]
Hello,

I have installed a clean version of BigBlueButton version 2.0.0 RC(8) and can connect with a direct join but am getting the Failed to Fetch config.xml when using the session_token method.

IE https://hostname/client/BigBlueButton.html?sessionToken=l9ltwp9jnhg4gkr4

I am running the join api with redirect=false to get the XML back with this session_token.  Am I missing a step?  I can't find the log to see why it can't fetch the config.xml file.

Appreciate any help,
Tony

**Comment by capilkey** [comment]
I'm not quite sure what the "session token method" is, but it seems like
your manipulation of the join process has a flaw. You might be calling the
join API on the server side instead of the client.

Can you successfully join through the demos?

**Comment by gasperinia** [comment]
Thank you so much for the quick response!   I am using the join api with the redirect=false parameter set. http://docs.bigbluebutton.org/dev/api.html#configuration 
This returns an XML like this.

<response>
  <returncode>SUCCESS</returncode>
  <messageKey>successfullyJoined</messageKey>
  <message>You have joined successfully.</message>
  <meeting_id>640ab2bae07bedc4c163f679a746f7ab7fb5d1fa-1531155809613</meeting_id>
  <user_id>w_euxnssffnsbs</user_id>
  <auth_token>14mm5y3eurjw</auth_token>
  <session_token>ai1wqj8wb6s7rnk0</session_token>
</response>

I then redirect the user to https://hostname/client/BigBlueButton.html?sessionToken=ai1wqj8wb6s7rnk0

Which causes the error.

I can join the meeting fine if omitting the redirect parameter and letting the browser simply redirect.  However I would like to hide the meetingid, password, etc from the user using the first method.

-Tony

**Comment by gasperinia** [comment]
Oh Yes I do call the join api from the server side and then pass the sessionToken url to the client side.  

How can I make a redirect then without the client seeing the parameters passed if not first from the server side?

Thanks,
Tony

**Comment by capilkey** [comment]
The sessionToken is only valid for the browser that calls the join API.
There's a cookie set on the client-side that tomcat uses to look up the
information. The client browser has to call the join API or it's never
going to work.

You also can't hide the meetingId and other information from the user.
Right after the config.xml is grabbed there will be a request to the enter
API and the return has all of the meeting information.

**Comment by gasperinia** [comment]
Ok.  So what would stop a user from sharing that join URL to another person and having them also join the meeting?  I work at a college institution so I am worrisome of security holes.

Thanks,
Tony

**Comment by gasperinia** [comment]
True but they could manipulate the URL and change the fullName parameter.  I would just like a way to lock it down to only the participants expected.  In this case the faculty member and the single student only.  This cannot by obfuscated from browser network traffic debugging?  

Thanks,
Tony

**Comment by capilkey** [comment]
If you change any part of the URL then the checksum will be invalid and the
request will be rejected. The whole thing would also require cooperation
from one of the participants.

**Comment by gasperinia** [comment]
Thanks Chad, forgot about the Checksum as well.  Thank you again for your help with what I was trying to accomplish.  Amazing product and genuinely appreciate all of the work put in to this project!

-Tony
