### ISSUE TITLE
Expire sessionToken on userEjected

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#6269]
On userLeft pass argument `wasEjected:bool` so we can control whether to invalidate the sessionToken or not. An ejected user will not be able to rejoin with their old sessionToken

**Comment by ffdixon** [comment]
@antobinary Is this still an issue with the HTML5 client?

**Comment by pedrobmarin** [comment]
This seems to be done with user ban or even earlier.
