### ISSUE TITLE
Update the colours used for the main button controls

### ISSUE THREAD

**Issue by tylercopeland** [bigbluebutton/bigbluebutton#6289]
Through usability testing, we've identified that some individuals are having a hard time distinguishing between different states for the main control (join audio, mute/unmute, share webcam and desktop shared). This led us down the path of exploring what the interface would look like using a more subtle button style for the default state and then using our primary colour for the active state. 

We've also heard feedback that using the red colour suggests things like hanging up or ending the meeting. Mainly, if a button is red, users are scared to press it because they assume something significant will happen.

The following are mockups for the different main control use cases. 

**No audio**

![html5-controls-1](https://user-images.githubusercontent.com/1273169/48919681-6136ff00-ee62-11e8-8c07-17da74386c3f.png)

**Joined audio and muted**

![html5-controls-3](https://user-images.githubusercontent.com/1273169/48919694-73b13880-ee62-11e8-8bb2-1181bf8055ab.png)

**Joined audio and unmuted**

![html5-controls-2](https://user-images.githubusercontent.com/1273169/48919688-6ac06700-ee62-11e8-92eb-f88a16058b34.png)

**Joined audio, unmuted and shared video**

![html5-controls-4](https://user-images.githubusercontent.com/1273169/48919702-80359100-ee62-11e8-8b27-3073de3accd4.png)

**Comment by ux-jules** [comment]
I think the mockups show much better feedback for the user. At a glance, it is much easier to understand what the state of each button is.

**Comment by tylercopeland** [comment]
@ux-jules thank you for the feedback!
