### ISSUE TITLE
Text in the chat panel is cut off

### ISSUE THREAD

**Issue by tylercopeland** [bigbluebutton/bigbluebutton#6292]
@antobinary while interacting with the latest dev of the HTML5 client, I noticed that the text in the chat panel was cut off. Please refer to the image below. 

<img width="1442" alt="screen shot 2018-11-23 at 9 04 36 am" src="https://user-images.githubusercontent.com/1273169/48949497-238bb200-ef06-11e8-832c-a35f04bb57d0.png">

**Comment by tylercopeland** [comment]
I can confirm that this is happening after I expand the width of the chat panel.

**Comment by antobinary** [comment]
Has been resolved
