### ISSUE TITLE
Add the pan tool as its own item within the whiteboard controls

### ISSUE THREAD

**Issue by tylercopeland** [bigbluebutton/bigbluebutton#6296]
Now that we've implemented the zoom-in and out functionality and until we can incorporate  https://github.com/bigbluebutton/bigbluebutton/issues/5563 we're going to need a quick way for the presenter to select the "pan" tool. My suggestion is to have "pan" as its own item within the whiteboard controls.

**Comment by ffdixon** [comment]
@tylercopeland is this needed anymore now that the presenter has the ability to hold down the space bar to trigger pan operation?

**Comment by tylercopeland** [comment]
@ffdixon I don't see it being needed anymore. I'm going to create a new ticket to add the spacebar functionality to the "Hotkey" list.
