### ISSUE TITLE
Update the pan tool tip to read "Pan" instead of "Hand"

### ISSUE THREAD

**Issue by tylercopeland** [bigbluebutton/bigbluebutton#6297]
To the user, it's not clear what the "hand" means. 

![screen shot 2018-11-26 at 3 34 43 pm](https://user-images.githubusercontent.com/1273169/49040623-1504fb00-f191-11e8-92a4-121d149ef8f8.png)

My recommendation is that we change it to "pan".

**Comment by antobinary** [comment]
I think we need a 3rd name for this tool. "Pan" is not particularly meaningful to me personally. Tooltips can be longer, no need to put a single word constraint to us. An example could be "Pan tool allows you to move the slide when zoomed in". Do you have a more descriptive tooltip suggestion?

**Comment by ux-jules** [comment]
What is the functionality of the hand tool? In most software apps the hand is used to move a window or board around. In Google Maps, the hand is used to move you around in the map. If we can understand the functionality of the hand tool within BBB, we can come up with the correct icon for it.

**Comment by capilkey** [comment]
Tooltips can be longer than one word, but you also shouldn't put full sentences in them unless it's really required. I don't know if I've ever seen one that was 11 words. The Flash client's tooltip is "Pan and Zoom" which seems accurate enough to me.

@ux-jules Selecting it allows the presenter to click and drag to move a zoomed-in presentation around. I think the icon is appropriate in this usage the question is more so what the text of the tooltip should be.

**Comment by ux-jules** [comment]
@capilkey does the hand icon/button also zoom? If not, then maybe just “pan” or “move tool” are more accurate?

**Comment by capilkey** [comment]
Seems like the current version of the client allows mouse-wheel zooming with every tool. I think originally when that tooltip was set it was only available when that tool was selected
