### ISSUE TITLE
Update the "clear annotations" icon to use the "trash icon"

### ISSUE THREAD

**Issue by tylercopeland** [bigbluebutton/bigbluebutton#6298]
The trash icon is a more familiar icon that represents "deleting" items. The (X) is often used to close items versus removing them. 

![screen shot 2018-11-26 at 3 41 50 pm](https://user-images.githubusercontent.com/1273169/49040931-de7bb000-f191-11e8-9445-68c247ada3ad.png)

**Comment by ux-jules** [comment]
What about clear instead of trash? You aren’t really trashing the screen, but just clearing it like you would an online form.
