### ISSUE TITLE
Update the tooltip text for the share webcam button to "Share your webcam"

### ISSUE THREAD

**Issue by tylercopeland** [bigbluebutton/bigbluebutton#6300]
**Current tooltip**
![screen shot 2018-11-26 at 3 52 04 pm](https://user-images.githubusercontent.com/1273169/49041453-42eb3f00-f193-11e8-95ea-82f2340b4feb.png)

It's unclear to the user what "Video Menu" means. My recommendation is to update the tooltip to read "Share your webcam'", which is consistent with the Deskshare button "Share your screen".

Also _(not sure if it's possible)_, when the webcam is active, it would be great to update the tooltip to read 'Webcam options". Options meaning there is more actions than "unshare webcam".

**Comment by antobinary** [comment]
Obsolete. We now have Share webcam and unshare. The swap trigger is no longer part of the video menu
