### ISSUE TITLE
Cannot end a meeting with long duration

### ISSUE THREAD

**Issue by hacrot3000** [bigbluebutton/bigbluebutton#6304]
I am using BigBlueButton 2.0.0-RC4, I am not sure I meet same issue with #2432 or not but I checked the code and found type of duration attribute of Meeting.java is now interger, on the fix for that item they changed it to long.

I don't have any issue when create new room but if stay long enough I will have some troubles:

1. When click exit and confirm to close the meeting, the client do nothing. It doesn't redirect to any other page, just stuck in the room.
2. When I call API bigbluebutton/api/getMeetingInfo it still return success, the running status is TRUE
>      [returncode] => SUCCESS
>      [meetingName] => Demo class room
>      [meetingID] => 3011
>      [internalMeetingID] => 1d25caa86469e680b7dfceb94bfc822f1d1684a9-3011
>      [createTime] => 1543294204137
>      [createDate] => Tue Nov 27 04:50:04 UTC 2018
>      [voiceBridge] => 1543294204
>      [dialNumber] => 613-555-1234
>      [attendeePW] => ea1df2212ff228c936e0114f4983ec40
>      [moderatorPW] => 80a309dd2000d8f4496a1ce375a4ffca
>      [running] => true
>      [duration] => 0
>      [hasUserJoined] => true
>      [recording] => false
>      [hasBeenForciblyEnded] => false
>      [startTime] => 1543294204259
>      [endTime] => 0
>      [participantCount] => 1
>      [listenerCount] => 0
>      [voiceParticipantCount] => 0
>      [videoCount] => 0
>      [maxUsers] => 0
>      [moderatorCount] => 1
>      [attendees] => SimpleXMLElement Object
>          (
>              [attendee] => SimpleXMLElement Object
>                  (
>                      [userID] => 3011
>                      [fullName] => nataly.n
>                      [role] => MODERATOR
>                      [isPresenter] => true
>                      [isListeningOnly] => false
>                      [hasJoinedVoice] => false
>                      [hasVideo] => false
>                      [clientType] => FLASH
>                  )
>  
>          )
>  
>      [metadata] => SimpleXMLElement Object
>          (
>              [0] => 
>  
>          )
>  
>      [isBreakout] => false
>
3. When I get the join URL, it return a join URL but when I open that link the BBB client will stuck after port test and /bigbluebutton/api/enter?sessionToken=. The last client log code is validate_token_request_timedout
4. When I call end API, it return success but after a day the room still visible with status running when call  getMeetingInfo
>  (
>      [returncode] => SUCCESS
>      [messageKey] => sentEndMeetingRequest
>      [message] => A request to end the meeting was sent.  Please wait a few seconds, and then use the getMeetingInfo or isMeetingRunning API calls to verify that it was ended.
>  )

**Comment by ffdixon** [comment]
Can you upgrade to 2.0-RC7.  In that release, we had fixed an issue in 2.0-RC7 that would sometimes cause the meeting to not end (see #6247) on the server.
