### ISSUE TITLE
Add an API call to inject a pop-up message in a session

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#6310]
There are use cases where the front-end server needs to notify users in a session of a message, such as "The meeting is about to end".

Add an API call sendMessage(meetingID, text) that would display a message to all users in a modal dialog that they need to accept.

**Comment by pedrobmarin** [comment]
Hmm, thanks for pointing this out @iSamof. @ffdixon these two issues looks pretty much the same. Could we close one of them?

Personally I'd vote to close this one because pop-up culture has been canceled by the digital society a long time ago.

**Comment by iSamof** [comment]
You are welcome @pedrobmarin 

My 2 cents: Pop-ups are not favoured by digital society, yes agreed. But that is in the context of visiting sites that visitor doesn't know or when some sites overdo it with constant interruptions ... creating a bad user experience. 

In BBB, the context is more of a community coming together for meetings and lessons etc. I don't think a pop-up comtaining something important from the moderator or presenter will be a problem.

I think adding messages into chat (public and private) and the pops are all helpful.

**Comment by sartaj-m** [comment]
@ffdixon,  any tentative dates by when these features will be available?

**Comment by iSamof** [comment]
Unless covered elsewhere, this API would still be extremely helpful to have.

**Comment by SamuelWei** [comment]
I also agree that an api to inject message to a meeting, via public chat, private chat or popup would be very helpful.
Maybe having a prop like type:private|public|popup could make it flexible. Also limiting the recipients by a given arry of user ids would be helpful. It might even be possible to add feedback buttons or text input like with polls and sending the result with the user id to a webhook.

**Comment by souri84** [comment]
> I also agree that an api to inject message to a meeting, via public chat, private chat or popup would be very helpful. Maybe having a prop like type:private|public|popup could make it flexible. Also limiting the recipients by a given arry of user ids would be helpful. It might even be possible to add feedback buttons or text input like with polls and sending the result with the user id to a webhook.

It's could be a great idea. 

Currently, I'm using BigBlue for my selling webinars. And I would like to show small notification for all people in corner to tell "Hey thank you John for your purchase !" during the webinar by sending a webhook or call an api endpoint !

Like that we add scarecity and can increase our sales rate.

Do you think it's possible ?

Thanks,
