### ISSUE TITLE
Unshare webcam should have '/' through the logo

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#6315]
Here's the current menu

![image](https://user-images.githubusercontent.com/290351/49247074-678a2580-f3e4-11e8-9085-a10b8b486716.png)

The icon for unshare should have a '/' through it

**Comment by ux-jules** [comment]
@ffdixon A thought. When you put a slash through an icon, it usually means that the functionality is turned off and that you will need to turn it on again somewhere. Is that what you are aiming to do with it?

**Comment by ffdixon** [comment]
I see what you mean -- but I think of the operation of closing a window or turning off a feature -- the icons usually show an 'x' or are red to show that it's an operation.

I think the difference here is instead of a single icon in the main area, we are showing the users a range of choices -- and ending the webcam stream is one of these choices.  Usually in a range of choices, the end/stop/terminate option stands out a bit more as being a final action.

**Comment by ux-jules** [comment]
I see what you are saying. Google Hangouts and Zoom do something similar. I am wondering if a visual designer couldn't come up with something better.

I noticed that people need to click on the video icon to get to a menu so they can share or unshare their webcam. Typically people don't need to evoke a menu to do these two actions. An alternative route is to click on the video icon and it will do two things:
(a) turn your webcam on
(b) add the video swap button next to the original video icon. When you turn off your webcam the video swap button disappears. The only time you need to see it is when you share your webcam.

This improves usability in two ways:
(1) There are fewer steps for the users to do to achieve their goal, which means it takes less time for the user. And everyone loves to save time.
(2) The common mental model people have is you just click on the button to start and stop your webcam. Doing it the way you have it adds to the learning curve for the user and takes more thought (adds cognitive load) for the user as well.

**Comment by antobinary** [comment]
Obsolete - we have simplified the experience and no longer have this menu
