### ISSUE TITLE
Trying to share mic but get an error with permission enabled

### ISSUE THREAD

**Issue by GhaziTriki** [bigbluebutton/bigbluebutton#6321]
![image](https://user-images.githubusercontent.com/4991088/49299058-1dc23d80-f4bf-11e8-988a-f4320e60ab37.png)

**Comment by antobinary** [comment]
This means there were no audio input devices. I don't think this is a bug.

**Comment by antobinary** [comment]
Perhaps you are sharing your mic(s) in browser A and you are now trying to also share in browser B?
