### ISSUE TITLE
Kicked user reconnects his way back in

### ISSUE THREAD

**Issue by pedrobmarin** [bigbluebutton/bigbluebutton#6324]
If an user is promoted/demoted and get kicked out of the meeting he reconnects back

at dev22.bigbluebutton.org:

![peek 2018-12-02 20-49](https://user-images.githubusercontent.com/1778398/49346053-ef399380-f673-11e8-81d8-b50d4856b5a6.gif)

**Comment by ffdixon** [comment]
Good catch!

**Comment by Tainan404** [comment]
This has already been reported in #6234.

**Comment by pedrobmarin** [comment]
Ok, closing this one.
