### ISSUE TITLE
No Database created in mongodb

### ISSUE THREAD

**Issue by dhakad97** [bigbluebutton/bigbluebutton#6327]
I successfully installed bigbluebutton server and HTML5client but when users joins a session and they communicate each other there is nothing in mongodb. no database created in mongodb .

**Comment by dhakad97** [comment]
Yes, users are using this successfully. I want to see the database that has been created by the bbb  like MeetingIDs, user info etc.

**Comment by ffdixon** [comment]
There is no such database created by BigBlueButton.  BigBlueButton is stateless in that when a meeting finishes, it flushes it from memory.

We are planning to add a database to a future update.  For now, you can use the API calls getMeetings to get a snapshot of all meeting on the server.  If you poll this API call, say once very two minutes, you can get a pretty accurate log of all the meetings and users in meetings over time.  You can use this information to populate a database of meetings and users for later analysis.
