### ISSUE TITLE
Upgrade should not reset turn-stun-servers.xml

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#6330]
The upgrade script for bbb-web should propagate any changes to

   /var/lib/tomcat7/webapps/bigbluebutton/WEB-INF/spring/turn-stun-servers.xml

**Comment by jvieille** [comment]
Last updates still kill the turn config, even erasing bakup files.

**Comment by ffdixon** [comment]
We'll modify the package scripts for 2.2 and 2.2-dev so it preserves the turn-stun-servers.xml.

**Comment by prlanzarin** [comment]
Addressed by https://github.com/bigbluebutton/bigbluebutton/pull/11804.
