### ISSUE TITLE
Move the "create breakout rooms action" to the manage users dropdown

### ISSUE THREAD

**Issue by tylercopeland** [bigbluebutton/bigbluebutton#6354]

**Comment by ffdixon** [comment]
Not sure about this -- the creation of a breakout room more a presenter action than a user management action.

The counter argument is two fold

  1.  We did it this way in the Flash client
  2.  There are cases where a second moderator is in the session and is helping the instructor with the class and can initiate the breakout rooms

For (1), we should be make UI changes that make the interface more consistent (even if it changes it around for existing users).

For (2), there are far more times that there is only one moderator (the instructor) in a session than times there are two moderators (one of which is presenter).

I think this makes more sense keeping it as a presenter function.  

Others?

**Comment by ux-jules** [comment]
What does the rest of the information architecture look like?

**Comment by akiwenziec** [comment]
The creation of breakout rooms are tied to the moderator role not presenter actions - the function should be with the other moderator role features

**Comment by tylercopeland** [comment]
Thank you, everyone, for all the feedback. It was truly a group effort to come to a conclusion on this revised experience.

In short, the final outcome is to display "Start breakout rooms" in both the "Manage Users" and "Actions" buttons.

We've decided to display it in two areas because:

1) Familiarity for existing BigBlueButton Flash users. 
2) Prominant area such as the action button that way new BigBlueButton users can come across this functionality withing the first few minutes of interacting with the the software.


**Manage Users**

![html5-moderator-presentor-controls-1](https://user-images.githubusercontent.com/1273169/50057948-b56e8f80-013f-11e9-89c4-40c5bc528a66.png)


**Actions | Moderator who's presenting**

![html5-moderator-presentor-controls-2](https://user-images.githubusercontent.com/1273169/50057954-c7503280-013f-11e9-8f3d-9172f038bd8a.png)

**Actions | Moderator**

While going through this exercise we also wanted to provide a quicker way for moderators to take back presenter capabilites. Which led is to the mockup below, including "Take presenter role" within the action button. 

![html5-moderator-presentor-controls-3](https://user-images.githubusercontent.com/1273169/50057977-0da59180-0140-11e9-954a-b37216a28600.png)

@ffdixon is there anything else you would like to add to the breakdown above?
