### ISSUE TITLE
screenshare slow with Firefox

### ISSUE THREAD

**Issue by shilky69** [bigbluebutton/bigbluebutton#6362]
Hello,

I installed bigbluebutton with the overlay HTML5 but the screen sharing on firefox is very slow, I also tested it on the test platform: test.bigbluebutton.org and the report is identitic.

On the other hand, on chrome response times are better

Are there parameters that could be modified?

Thank you

Regards,

**Comment by ffdixon** [comment]
Can you check your internet bandwidth with http://www.speedtest.net/

**Comment by shilky69** [comment]
Hi,

I have a good bandwith 40mbits

With google chrome i don't have latency

thanks

**Comment by ffdixon** [comment]
@shilky69 Can you test this with the latest build of the HTML5 client at https://test.bigbluebutton.org/ and let us know if it's still a problem.

**Comment by ffdixon** [comment]
Closing this issue due to no response.  If anyone reading this thread encounters a similar problem, please test first with

  https://demo.bigbluebutton.org/

and if you encounter an issue, let us know

  https://bigbluebutton.org/support
