### ISSUE TITLE
org.bigbluebutton.web.services.callback.CallbackUrlService  - IOException for callback url

### ISSUE THREAD

**Issue by gasperinia** [bigbluebutton/bigbluebutton#6371]
Hello,

I am passing a callback URL during the create API in the meta_endCallbackUrl parameter.  When passing the url in a cURL command on the host it resolves fine but I am getting an IOExcetion error in the bbb_web.log.

org.bigbluebutton.web.services.callback.CallbackUrlService  - IOException for callback url=[https://mycallbackhost?sess_id=1111&recordingmarks=false] 

Is there any other logs I can look into to resolve this or other requirements I am not meeting?

Once again I appreciate the help from this site.

-Tony

**Comment by ffdixon** [comment]
@gasperinia Could we ask that you do a quick test to see if this is still an issue in the latest build of BigBlueButton 2.2-beta.   Thanks!

**Comment by matiasilva** [comment]
No follow up in a year. Closing for now but feel free to follow up at https://groups.google.com/forum/#!forum/bigbluebutton-setup.
