### ISSUE TITLE
The caption UI doesn't update with moderator promotion/demotion

### ISSUE THREAD

**Issue by capilkey** [bigbluebutton/bigbluebutton#6378]
Steps to reproduce:
1. Join as a moderator and a viewer
2. Open the caption layout on both
3. Promote the view to moderator

Expected result:
The viewer's window should update to show all of the languages and allow for taking ownership of a locale.

Actual result:
The UI doesn't update and the new moderator has to reload their client to get the UI to refresh.

Additional information:
I suspect the reverse is also true with someone who loses moderator status.

**Comment by ffdixon** [comment]
Closing as this was an issue related to the Flash client (the project has moved to an HTML5 client).
