### ISSUE TITLE
bbb-record --rebuildall and .norecord meetings

### ISSUE THREAD

**Issue by pedrobmarin** [bigbluebutton/bigbluebutton#6394]
Not sure what is supposed to happen in this case but `bbb-record --rebuildall` is replacing `.norecord` tag from archive with a `.done` and the result of that is a recording published with no slides.

**Comment by kepstin** [comment]
The reason this is happening is that `bbb-record --rebuildall` essentially runs `bbb-record --rebuild` on each recording, and one of the things `bbb-record --rebuild` does is remove the `.norecord` file to force recordings to be processed for meetings without recording marks.

This probably isn't the desired behaviour, we should change `--rebuildall` to skip recordings with `.norecord` files.
