### ISSUE TITLE
Remove faded lines above and below the participant list. 

### ISSUE THREAD

**Issue by tylercopeland** [bigbluebutton/bigbluebutton#6409]
**Current implementation**
<img width="244" alt="screen shot 2018-12-16 at 2 48 45 pm" src="https://user-images.githubusercontent.com/1273169/50058107-d89a3e80-0141-11e9-9e2e-b160791e0ce1.png">

**Recommendation** 
<img width="244" alt="screen shot 2018-12-16 at 2 50 54 pm" src="https://user-images.githubusercontent.com/1273169/50058123-04b5bf80-0142-11e9-977b-8644702c3aa9.png">

**Comment by antobinary** [comment]
Looks to be already in place. If more changes are needed, @tylercopeland please reopen
