### ISSUE TITLE
Individually lock users

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#6417]
Add the ability to individually lock/unlock users from the list.

The scenario would be

1.  The instructor applies the lock settings to all viewers
2.  The instructor chooses a specific viewer in the Users list in the list to unlock (not apply the global lock settings)

Later on, the instructor can choose the same user and reapply the global lock settings

**Comment by antobinary** [comment]
Addressed in #6676

**Comment by cod3r0k** [comment]
Can instructor lock specific user ?  (not lock all users) @ffdixon
