### ISSUE TITLE
HTML5: 401 Authentication failed due to missing credentials - for some session

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#6433]
We sometimes hit

 ```
error: CLIENT LOG: {"error":401,"description":"Authentication failed due to missing credentials."}
error: CLIENT LOG: User could not log in HTML5, hit 401
```

especially when we have to give permission for media devices on sessions with auto-join audio/video enabled in Safari

**Comment by amohideen** [comment]
I still have this error: Installed on 26/06/2020

Unauthorized
Authentication failed due to missing credentials.
401

**Comment by matiasilva** [comment]
Hi @amohideen. We're happy to help but your question would be better handled in the setup forum: https://groups.google.com/forum/#!forum/bigbluebutton-setup. It might be useful to link this issue as a reference.
