### ISSUE TITLE
Lock settings -> viewers getting ejected

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#6434]
Lock settings have some discrepancy with UI leading to viewers getting ejected.

Some work to narrow down the issue is required but likely it's caused by overreaching - rights management kick the user out. The real issue here is that the UI did not prevent the user from attempting an action that was currently restricted.

**Comment by akiwenziec** [comment]
When trying to reproduce noted the following:

1. All lock settings function as they should when enabled individually
2. Viewer is not ejected when only the private chat is locked 
3. Viewer is ejected when the following lock settings are enabled:
     -webcam
     -microphone
     -public chat
     -private chat 
4. If the viewer has used private chat before the above lock settings are enabled they are not ejected.

**Comment by akiwenziec** [comment]
Behaviour of this issue has changed. 

Now when engaging the lock settings all function as they should individually with the exception of the private chat:
1. Viewer is ejected when the private chat is locked individually or with any combination of other settings. 
2. Viewer is not ejected if they used the private chat PRIOR to the lock setting being engaged.
