### ISSUE TITLE
Make switch presentation and webcams a separate button

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#6472]
Currently, switching the presentation <-> webcams layout in the HTML5 client is under the webcam button.

![image](https://user-images.githubusercontent.com/290351/50377663-3cfc4880-05ef-11e9-8e1d-c4fb085dbd5c.png)

Need to determine whether to keep this switch functionality within the share webcam button or place it elsewhere in the interface.

**Comment by pedrobmarin** [comment]
I think this was done in https://github.com/bigbluebutton/bigbluebutton/pull/6640 .

Kudos to @lfzawacki !
