### ISSUE TITLE
Wrong URL format in chat playback

### ISSUE THREAD

**Issue by GhaziTriki** [bigbluebutton/bigbluebutton#6475]
**Spotted in the latest v2.0**
Any URL shared in chat will be appended by `event:` in the playback, as unwanted effect the navigation URL is wrong.

As example if a user shared `https://bigbluebutton.org` in the chat, the chat playback message will be

``` html
<a href="event:https://bigbluebutton.org" target="_blank"><u>https://bigbluebutton.org</u></a>
```

The `event:` needs to be omitted from the generated HTML.

**Comment by kepstin** [comment]
I can't reproduce this issue. The code in the recording processing in 2.0 and 2.2 is correctly removing the `event:` prefix from links in the processing scripts.

Ref:
https://github.com/bigbluebutton/bigbluebutton/blob/v2.0.x-release/record-and-playback/presentation/scripts/publish/presentation.rb#L1109
https://github.com/bigbluebutton/bigbluebutton/blob/v2.0.x-release/record-and-playback/core/lib/recordandplayback/generators/events.rb#L459-L468

**Comment by GhaziTriki** [comment]
A user reported the same issue https://groups.google.com/forum/#!topic/bigbluebutton-dev/PrwDISn0NWg

**Comment by kepstin** [comment]
I still don't know how to reproduce this - is anyone able to provide an example chat event (from events.xml) which results in a processed recording with this problem?

**Comment by GhaziTriki** [comment]
@kepstin to reproduce the issue we just need to send an URL in the chat of a recorded meeting.

You can take a look at a recording I created on test-install : https://recordings.rna1.blindsidenetworks.com/test-install/a968160d22c45d4fd0924a90e367373a3ba19692-1550669385491/presentation/

**Comment by kepstin** [comment]
Alright, I see what the problem is now. Here's what the chat event looks like in the events.xml:
```xml
  <event timestamp="1197455546" module="CHAT" eventname="PublicChatEvent">
    <sender>BigBlueButton</sender>
    <color>0</color>
    <message>
      <![CDATA[<a href='event:https://bigbluebutton.org/'><u>https://bigbluebutton.org/</u></a>]]>
    </message>
    <senderId>w_rrnumk6ph9u0</senderId>
  </event>
```
But the recording scripts are expecting double-quotes on the link tag, like `<a href="event:` so the replacement doesn't match. There must have been a change in the BigBlueButton client at some point where it started generating single-quotes instead of double-quotes…
