### ISSUE TITLE
Zooming in after Fit-To-Width gives unpredictable results

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#6481]
Here's a look at it running on https://test.bigbluebutton.org/

![zoom issue](https://user-images.githubusercontent.com/290351/50561777-e623fc80-0cdb-11e9-8bc2-609200d64477.gif)

**Comment by capilkey** [comment]
This is still a problem in the latest build. The fit-to-width option doesn't really work.

**Comment by KDSBrowne** [comment]
Yeah, this may be related to https://github.com/bigbluebutton/bigbluebutton/issues/6489 as well

**Comment by ffdixon** [comment]
Just tested this in the latest build for BigBlueButton 2.2-beta and still an issue (I created a video below before finding out that I had already reported it before).

![zoom](https://user-images.githubusercontent.com/290351/55828740-1cdb9100-5adb-11e9-9cb5-32aee7cc4fd7.gif)

**Comment by antobinary** [comment]
Addressed in #7837
