### ISSUE TITLE
Add an area where we could show some minimal detail of the issue to the user

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#6485]
Add a label for additional info ~(3-6 words)
![screenshot from 2019-01-02 11-59-47](https://user-images.githubusercontent.com/6312397/50602688-00014300-0e86-11e9-8642-92e118ac889c.png)
Perhaps it could be retractable (+ press here for more info)

**Comment by tylercopeland** [comment]
@antobinary here are a few options to lay out our 401 pages. 

**Simple**

![html5-401-layout-1](https://user-images.githubusercontent.com/1273169/50614510-1079e380-0eaf-11e9-9d60-10568e9ceb2d.png)


**With an illustration in the background.** 
Here I'm trying to have a little fun with these basic pages. 

![html5-401-layout-2](https://user-images.githubusercontent.com/1273169/50614543-28516780-0eaf-11e9-955e-4d94bd49693e.png)

![html5-401-layout-3](https://user-images.githubusercontent.com/1273169/50614545-28516780-0eaf-11e9-957c-862c517412ce.png)

If it's easier to do the first one, I'd simply move forward with it. 

As always, feedback is welcome.
