### ISSUE TITLE
Meeting title moves right and resizing if use custom logo (flash)

### ISSUE THREAD

**Issue by Brullworfel** [bigbluebutton/bigbluebutton#6488]
Hello! If we use a custom logo (by setting parameter 'logo' on creating by API), meeting title moves right away from logo and resizing to small size, so the title does not fit.

<img width="696" alt="2019-01-03 15 00 27" src="https://user-images.githubusercontent.com/12401672/50639083-c5bca200-0f68-11e9-862b-575246a06592.png">

**Comment by ffdixon** [comment]
Closing as this was an issue related to the Flash client (the project has moved to an HTML5 client).
