### ISSUE TITLE
Fit-to-width showing small on viewer's screens

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#6489]

**Comment by ffdixon** [comment]
When testing Fit-to-width on the HTML5 client, the presenter uploaded a portrait document

![image](https://user-images.githubusercontent.com/290351/50645227-669b6500-0f49-11e9-95ad-c9ba234a385e.png)


but on viewer's monitors it showed a small version of it.

![image](https://user-images.githubusercontent.com/290351/50645135-2d62f500-0f49-11e9-9424-7555d16c8707.png)

**Comment by capilkey** [comment]
Fixed in #7073
