### ISSUE TITLE
how to open two camera when use the html5 client?

### ISSUE THREAD

**Issue by zsinba** [bigbluebutton/bigbluebutton#6492]
Hi,Dear:
when I use the flash version. I can open two camera from the camera button . 
but the html5 version can only open one camera. 
I want to know how to open 2 or 3 cameras when use html5 version?
 thanks

**Comment by pedrobmarin** [comment]
Hey @zsinba . I hope you got your answer already but for anyone that reaches this issue in the future, the HTML5 client has https://github.com/bigbluebutton/bigbluebutton/blob/6a3398751f6b7934214fab7a319dad673284b3e9/bigbluebutton-html5/private/config/settings.yml#L36 enabled by default.

**Comment by zsinba** [comment]
thanks so much.
