### ISSUE TITLE
how to configure to make html5 client use presenterShareOnly and listenOnlyMode? 

### ISSUE THREAD

**Issue by ttfather** [bigbluebutton/bigbluebutton#6495]
as title

**Comment by capilkey** [comment]
Again, general questions should be posted to one of the Google groups (https://groups.google.com/forum/#!forum/bigbluebutton-setup) not to GitHub issues. 

You also haven't given nearly enough information to figure out what properties you're talking about. My best guess is that you want to restrict the ability for viewers to share their microphone and webcam. Both will be possible to restrict with the lock settings in 2.2.
