### ISSUE TITLE
how to deploy my html5 source change to the server?

### ISSUE THREAD

**Issue by ttfather** [bigbluebutton/bigbluebutton#6502]
I want to develop my own function in BBB , I change my html5 client code , but I don't know how to deploy to my server.Looking forward to getting a reply . Thanks!

**Comment by capilkey** [comment]
Again, general questions should be posted to one of the Google groups (https://groups.google.com/forum/#!forum/bigbluebutton-dev) not to GitHub issues as this isn't an issue with the product.
