### ISSUE TITLE
Support multiple webcams in HTML5 client

### ISSUE THREAD

**Issue by zsinba** [bigbluebutton/bigbluebutton#6503]
Hi dear:
In the falsh version, I can install three webcameras on one computer, which are teachers, teaching aids, and lab benches. But when using the html5 version, I found that I can only use one camera. please tell me, how do I use three cameras in the HTML5 version? As  in Flash, I can choose to launch the camera. thank you for your reply

**Comment by zsinba** [comment]
If I want to implement this feature, can you tell me where are the code I need to modify? How to do I modify it?
Thank you for your reply, thank you very much for your contribution.

**Comment by capilkey** [comment]
It won't be a simple change. The local webcam management will need to be changed to an array. The webcam menu will need more options for sharing a second webcam or closing active webcams. There might need to be changes to the local kurento code to handle multiple local cameras. Finally, it's possible that the server-side won't handle cameras from the same source well.

**Comment by zsinba** [comment]
I saw that in version 2.2 of html5, it was possible to list multiple cameras. But it can't be used at the same time.
Another problem, in the FLASH version, can already be used by multiple cameras at the same time, then HTML5 version  can not be used directly? Is the server code different?

**Comment by ffdixon** [comment]
The HTML5 client in 2.2-dev (soon to be released) now lets you choose which webcam to share.  

![image](https://user-images.githubusercontent.com/290351/50835591-1d6e5b00-1325-11e9-8ad1-f1e90888f562.png)

But it only lets you choose a single webcam to share.  As stated earlier, we'll keep this issue open until we implement multiple webcam sharing in the HTML5 client.

The Flash client does support multiple webcam sharing, but it doesn't share webcams with the HTML5 client (they are using two different protocols).  The proper solution is to support multiple webcams in the HTML5 client.

**Comment by zsinba** [comment]
thanks for your reply.  could you tell me when it can run by html5 with multipul webcam?

**Comment by ffdixon** [comment]
We don't have a date.  For more information on how we prioritize features (and how you can influence it), see: http://docs.bigbluebutton.org/support/faq.html#when-will-feature-x-be-implemented.

**Comment by zsinba** [comment]
Hi,Dear。 please close this issues if finished. thanks all your work.

**Comment by zsinba** [comment]
Hi,Dear, What about this point?

**Comment by ffdixon** [comment]
This is still an open issue -- the ability for the client to share multiple webcams.   We don't have a date for implementation of this feature. 

In a pinch, the user could login multiple times (once for each browser tab).

**Comment by zsinba** [comment]
thanks for your pinch. now I can invoke multiple webcam, but sometimes I can't display the content.

**Comment by ffdixon** [comment]
We're currently focused on hardening BigBlueButton 2.2-beta.  Our plan is to take a look at this feature as part of updates to the product after we finish BigBlueButton 2.2.

**Comment by zsinba** [comment]
Thanks for your reply.
How can I use the Flex version of the computer, tablet, mobile phone interoperability video?
Could I compile apk or ipa application by myself with flexbuilder?

**Comment by capilkey** [comment]
There's no mobile Flex client. We had some prototypes, but nothing was ever taken to completion.

**Comment by zsinba** [comment]
We have compiled the flex android .apk file .and it can work ok in the android with flex language.

**Comment by zsinba** [comment]
Please let me know if there is any progress on this issue.Thank you for your reply

**Comment by capilkey** [comment]
No work has been done towards this yet. The focus for videos currently is on making sure that they're solid before we start branching out into supporting multiple cameras.

**Comment by zsinba** [comment]
please tell me if any process for this work. 
thanks so much.

**Comment by ffdixon** [comment]
Nothing yet -- we're still plan to implement the ability for the HTML5 client to share multiple webcams.  Fro the moment, you to achieve the effect, you could login to the HTML5 client twice and in the second session, don't join the audio and share the second webcam.

You'll appear in the Users list twice, but you'll be able to broadcast two webcams.

**Comment by zsinba** [comment]
Thanks for telling me the method.
I  used the flash version to open the multiple webcam.
But I hope we can get the ability on the html5 platform. 
Thanks for your hard work and give so big powerful opensource system.

**Comment by ffdixon** [comment]
> I used the flash version to open the multiple webcam.

Understood.  For the moment, you'll need to make sure you disable the HTML5 client as webcams from the Flash client do not appear for HTML5 user.

Once we have multiple webcams supported in the HTML5 client, you can move over then.

**Comment by zsinba** [comment]
Thank you again.

**Comment by mmkbennani** [comment]
Hi Dear,

Is there any news about this issue please?

Best regards.

**Comment by capilkey** [comment]
Nothing has been started for this as far as I'm aware. The focus has been on stability and performance.

**Comment by pedrobmarin** [comment]
Included in 2.3
