### ISSUE TITLE
Sometimes  Bigbluebutton html5 client run in the android Webview not working.

### ISSUE THREAD

**Issue by starcwl** [bigbluebutton/bigbluebutton#6504]
Does Bigbluebutton html5 client test in android Webview? 
I have tested html5 client in many clients. Some of them work, some not.

**Comment by ffdixon** [comment]
It works on Android 6.0+ (or later).  All the videos are shared as h.264 (to provide compatibility with iOS devices).  We've seen some Android devices that do not have the h.264 codec enabled.  

You can configure BigBlueButton to only use VP8, see https://groups.google.com/d/msg/bigbluebutton-setup/W7LRamjpNxI/s4PE21NJCQAJ

**Comment by custodio78** [comment]
> Does Bigbluebutton html5 client test in android Webview?
> I have tested html5 client in many clients. Some of them work, some not.

Hi,
I trying to run Bigbluebutton on android WebView. My app has MICROPHONE,RECORD_AUDIO and MODIFY_AUDIO_SETTINGS permisions (requested on run time) but I can't hear the audio. When  I do the echo test I can't hear me but the others participants can hear me.    When I run BigBlueButton on default browser works fine, but on my WebView App I can't listen webrtc audios.  (I can hear the audios on "Test your speaker voume" on BigBlueButton audio settings.  Any ideas?  Thank you!

**Comment by custodio78** [comment]
The answer to my question:  webSettings.setMediaPlaybackRequiresUserGesture(false);

**Comment by ffdixon** [comment]
@custodio78 Thanks for sharing this.

**Comment by aviavinas** [comment]
It worked in my case when i changed the userAgentString: 
        WebSettings settings = webView.getSettings();
        settings.setUserAgentString("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.97 Safari/537.36");
