### ISSUE TITLE
how to install bbb-html5 V2.2?

### ISSUE THREAD

**Issue by zsinba** [bigbluebutton/bigbluebutton#6508]
Hi,Dear: 
I install v2.0 version bbb-html5 successful when use apt install bbb-html5. 
but the deom.bigbluebutton.com is v2.2 of bbb-html5. 
could you tell me how to do to install v2.2 bbb-html5 ?
I had a try comiple the newest of source code of v2.2 of html5. but it prompt me 401 error.

**Comment by ffdixon** [comment]
We're working on releasing BigBlueButton 2.2-dev so others can install it (along with the latest build of the HTML5 client) on their server.  Look for a post to https://groups.google.com/forum/#!forum/bigbluebutton-dev shortly for it's availability.

**Comment by ffdixon** [comment]
HTML5 2.2-beta now available for install, see 

  http://docs.bigbluebutton.org/2.2/install.html
