### ISSUE TITLE
Html5 client camera disappear

### ISSUE THREAD

**Issue by yanvictory** [bigbluebutton/bigbluebutton#6509]
Hello
Recently I was sufferied with a problem about html5 client. Well I'd set SSL configuration on both server and client browsers, which works well and healthy, excluded the web camera's sharement.The button on client is unvisible, why?? Anything needed install or config I'd probably omited or missed? Thank you~

**Comment by yanvictory** [comment]
Oh ,my code version is v.2.x-release, Or some errors in that??

**Comment by ffdixon** [comment]
Closing this issue as it's quite old, and we've done a lot of development on the HTML5 client.

If anyone reading this thread encounters a similar problem, please test first with

  https://demo.bigbluebutton.org/

and if you encounter an issue, let us know

  https://bigbluebutton.org/support
