### ISSUE TITLE
Khmer language in demo.bigbluebutton.org

### ISSUE THREAD

**Issue by sokunthearithmakara** [bigbluebutton/bigbluebutton#6515]
Hi,
I have contributed the translations for Khmer language on Transifex. I was wondering if you guys can add this language to the Greenlight instance on demo.bigbluebutton.org and the one that you use for Moodle. If there are additional requirements, please let me know. Appreciate your response.

Regards,
T

**Comment by ffdixon** [comment]
Sorry for the late response, and this might have already been merged. Can you take a look at demo and let us know if you now see the Khmer language there -- thanks!

**Comment by matiasilva** [comment]
Closed due to inactivity -- seems to have been solved.
