### ISSUE TITLE
Users list not updating lock status when lock settings applied / removed

### ISSUE THREAD

**Issue by akiwenziec** [bigbluebutton/bigbluebutton#6524]
The users list does not update the lock status when enabling/disabling any lock setting until the users name is selected in the list. 

Video of bug below:
https://www.youtube.com/watch?v=WzuqvoqD7Fs&feature=youtu.be

**Comment by antobinary** [comment]
Most likely this is a side effect of the performance improvements introduced in
Once we start 'watching' the lock status of a user, this should be fixed
