### ISSUE TITLE
Improve response for getRecordings() API calls

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#6541]
There are two optimizations that we could make

1.  bbb-web currently scans all recordings (on disk) for any matches.  For site that have 1000's of recordings, this introduces a noticeable delay.  We could explore using a database to keep track of recordings.  This way, the queries would be quick to generate.

2.  Add paging to the results so that if there are 500 matched recordings, for example, the client could get the first 100 (most recent), and make subsequent requests for the next 100 and so on.

**Comment by zeeshanali** [comment]
highly needed

**Comment by GhaziTriki** [comment]
The exception raised when doing multiple calls for this API is the following

```
java.io.IOException: Too many open files
	at sun.nio.ch.ServerSocketChannelImpl.accept0(Native Method)
	at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:422)
	at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:250)
	at org.apache.tomcat.util.net.NioEndpoint$Acceptor.run(NioEndpoint.java:482)
	at java.lang.Thread.run(Thread.java:748)
```

We definitely need some improvements here.

**Comment by jfederico** [comment]
I wish we could give this issue a higher priority as it afects all integrations and external applications including Greenlight
