### ISSUE TITLE
404 when trying to join a meeeting => meteor not starting

### ISSUE THREAD

**Issue by s-at-dq** [bigbluebutton/bigbluebutton#6546]
Hello

When I try to join a meeting via the HTML5 client I get an 404 error from nginx. The URL is https://subdomain.domain.tld/html5client/join?sessionToken=xxx...

The web server path /html5client is "forwarded" by nginx to 127.0.0.1:3000 according to the bigbluebutton web server configuration. However, there is no service running on that port. When I try to connect to 127.0.0.1:3000 via curl I only get connection refused. Furthermore, the meteor service isn't running and cannot be started using bbb-conf --restart.

**Comment by capilkey** [comment]
What's the output of `bbb-conf --status`? If you see a "bbb-html5" entry listed and it's in a state other than "active", can you also grab the output of `journalct -u bbb-html5`.

**Comment by s-at-dq** [comment]
"bbb-conf --status" told me, that bbb-html5 failed. The output of "journalctl -u bbb-html5 has a lot of lines like the following:

    Jan 14 15:27:49 servername systemd[1]: Starting BigBlueButton HTML5 service...
    Jan 14 15:29:19 servername systemd[1]: bbb-html5.service: Start-pre operation timed out. Terminating.
    Jan 14 15:29:19 servername systemd[1]: Failed to start BigBlueButton HTML5 service.
    Jan 14 15:29:19 servername systemd[1]: bbb-html5.service: Unit entered failed state.
    Jan 14 15:29:19 servername systemd[1]: bbb-html5.service: Failed with result 'timeout'.

**Comment by s-at-dq** [comment]
Any news regarding this bug?

**Comment by ffdixon** [comment]
We think this is related to this issue: https://github.com/bigbluebutton/bigbluebutton/issues/6413.

Without mongod running, the BigBlueButton HTML5 client will be unable to connect and give you a 404 error.
