### ISSUE TITLE
labs/docker - does not work

### ISSUE THREAD

**Issue by PravenJohn** [bigbluebutton/bigbluebutton#6548]
Hi,

I am trying to get bbb setup on a kubernetes cluster. I tried the sample configs under labs/docker/k8s , but that fails with the error ->
`2019-01-14T15:24:49.922Z ERROR org.codehaus.groovy.grails.web.errors.GrailsExceptionResolver  - NullPointerException occurred when processing request: [GET] /bigbluebutton/
Cannot invoke method isServiceEnabled() on null object. Stacktrace follows:
java.lang.NullPointerException: Cannot invoke method isServiceEnabled() on null object
	at org.bigbluebutton.web.controllers.ApiController$_closure21.doCall(ApiController.groovy:1917)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
`
whenever I hit /bigbluebutton .

Do you have any documentation on how to get this to work? 

Also I would appreciate the Dockerfiles used for the various images - like - fcecagno/bigbluebutton:bbb-web .

**Comment by capilkey** [comment]
The steps to build all of the images are in the README in labs/docker, https://github.com/bigbluebutton/bigbluebutton/tree/v2.0.x-release/labs/docker/README. The instructions show you how to build them all in one command and then how to build them each individually. I'm not sure how far you'll get with it though. It's just an experimental first step towards being able to cluster components, but it's useless in a production setup without a lot more development time. Also, make sure you're on the v2.0.x-release branch and not master because 2.0 was where the original development work was done.

**Comment by capilkey** [comment]
The file name is README.md,
https://github.com/bigbluebutton/bigbluebutton/blob/v2.0.x-release/labs/docker/README.md

**Comment by PravenJohn** [comment]
oh - thanks, will check that.

**Comment by PravenJohn** [comment]
Thank you, that helped a bunch. I was able to get a working Kubernetes env running as well.

I think the reason it was failing was - https://github.com/bigbluebutton/bigbluebutton/blob/v2.0.x-release/labs/docker/k8s/bbb-web.yaml is missing the TURN_DOMAIN . There were a couple of similar missing variables as well.

**Comment by PravenJohn** [comment]
P.S. - do let me know if you want me to create a PR, to your labs/docker/k8s , with my changes.

**Comment by PravenJohn** [comment]
https://github.com/bigbluebutton/bigbluebutton/pull/6564 is the PR with the changes I mentioned. Marking this issue as resolved.

**Comment by fcecagno** [comment]
@PravenJohn did you make it work on Kubernetes using the yaml files under k8s?

**Comment by varac** [comment]
I'd be very interested in more details how to run bbb on kubernetes. @qburst-praven How was your experience, did you even come up with a helm chart for this ?

**Comment by kiennguyen294** [comment]
I deploy bigbluebutton on K8s and have errror not use mic or listen only.
Help me
