### ISSUE TITLE
presentation-slides.nginx missing from packaging

### ISSUE THREAD

**Issue by GhaziTriki** [bigbluebutton/bigbluebutton#6556]
The file `presentation-slides.nginx` is missing from 2.2 packaging. Doing an `ls` on `/etc/bigbluebutton/nginx` shows that the file is no more there.

The file link : https://github.com/bigbluebutton/bigbluebutton/blob/master/bigbluebutton-web/nginx-confs/presentation-slides.nginx

**Comment by GhaziTriki** [comment]
Files are being served by `bbb-web` instead of nginx. We clearly see in logs `Nginx should be serving this SVG file!`.

**Comment by ffdixon** [comment]
Got it -- taking a closer look.

**Comment by ffdixon** [comment]
Fixed in the latest build of BigBlueButton 2.2-dev.
