### ISSUE TITLE
Chrome users can't use WebRTC video when force-h264 is turned off

### ISSUE THREAD

**Issue by capilkey** [bigbluebutton/bigbluebutton#6558]
If a server administrator changes the force-h264 option to false it will stop all Chrome users from being able to connect to WebRTC video streams (publish and subscribe). When the option is turned on (default), we do some SDP mangling and that seems to be changing the Chrome SDP so that the call can succeed. When the option is turned off, we don't do any SDP mangling and the error occurs.

This bug affects 2.0 for sure and possibly 2.2 also.

**Comment by jvieille** [comment]
Any update on this?
Many mobile devices do not support H264.
Thanks

**Comment by prlanzarin** [comment]
It should already be fixed on 2.0 RC10 onwards and 2.2-dev.

**Comment by capilkey** [comment]
Going to close this. We've since switched to VP8 in 2.2 and there's no longer an issue.
