### ISSUE TITLE
In the bbb-lti applicaation, add a way to configure the parameters used for generating the meetingID

### ISSUE THREAD

**Issue by jfederico** [bigbluebutton/bigbluebutton#6578]
As every LMS has its own implementation of LTI, the parameters passed are not standard.

Right now the meetingID generated for the rooms is based on the resource_link_id + oauth_consumer_id. What is really making the meetingID unique should be the resource_link_id, which should be unique in the context.

This approach works for most LMS, but the reality is that some LMS are not sending the resource_link_id and some others are sending a constant value (go figure!).

As the Tool has to be flexible and work with any LMS, regardless of their implementation. In order to workaround this issue, it would be nice to have a way to configure what parameters are going to be used for the meetingID. Even though (and as for backward compatibility) these parameters stay as the ones set up by default.

**Comment by Jacoblab1** [comment]
See my PR here https://github.com/bigbluebutton/bigbluebutton/pull/6714

**Comment by GhaziTriki** [comment]
@jfederico Can this issue be closed?

**Comment by ffdixon** [comment]
Closing this issue as it appears to be resolved (and if not please let us know!).
