### ISSUE TITLE
ppt upload error,the different only is a small image,why?

### ISSUE THREAD

**Issue by XoYoKing** [bigbluebutton/bigbluebutton#6585]
ppt upload error
A.pptx upload faile
B.pptx upload success
the different only is a small image,why?

[A.pptx](https://github.com/bigbluebutton/bigbluebutton/files/2771530/A.pptx)
[B.pptx](https://github.com/bigbluebutton/bigbluebutton/files/2771531/B.pptx)

bug html5-client

**Comment by GhaziTriki** [comment]
Hi @XoYoKing , `A.pptx` contains a media file; an image; named `image1.emf`. Powerpoints files that contains any `emf` file are considered as non-convertable by the presentation checker. Of course `B.pptx` does not contain any `emf` media.

The check is done here https://github.com/bigbluebutton/bigbluebutton/blob/7dfe3f3093974bb1af0891c626ded9de60689385/bigbluebutton-web/pres-checker/src/main/java/org/bigbluebutton/prescheck/Main.java#L39

And this check rule was added after discovering this reported issue to `Apache POI`
https://bz.apache.org/bugzilla/show_bug.cgi?id=60656

We  didn't try yet the update mentioned in the last comment https://svn.apache.org/viewvc?view=revision&revision=1849040

We might need to take a look at this update in the future.

**Comment by GhaziTriki** [comment]
This is linked to #7350, if the latest Apache POI fixes the EMF rendering we will able to close this issue and support EMF embedding presentations conversion.

**Comment by pedrobmarin** [comment]
Both loading the same image at v2.3-beta3
