### ISSUE TITLE
Uploading a presentation using the flash client doesn't work in BigBlueButton 2

### ISSUE THREAD

**Issue by s-at-dq** [bigbluebutton/bigbluebutton#6586]
Hello

Uploading a presentation via the flash client doesn't work in the BigBlueButton 2 instance I set up. After selecting a file and clicking the "upload" button, the progress bar for the presentation reaches 100% but then the whole flash client gets stuck at that point so that one has to reload the whole page in order to be able to use the flash client again. After that, the presentation isn't displayed as uploaded in the list of uploaded files that is shown when I click the upload button in the left bottom corner. The default presentation is the only item in the list of uploaded files.

**Comment by ffdixon** [comment]
Can you try reproducing this on https://demo.bigbluebutton.org/ and https://test.bigbluebutton.org/.

**Comment by s-at-dq** [comment]
demo.bigbluebutton.org requires registration so I skipped testing the problem on that instance. But I cannot reproduce the problem on test.bigbluebutton.org.

**Comment by ffdixon** [comment]
This is good ... https://test.bigbluebutton.org/ is running BigBlueButton 2.2-dev which we are working on releasing.  You can follow the development by subscribing to bigbluebutton-dev mailing list, see https://support.bigbluebutton.org/.

**Comment by capilkey** [comment]
The demo server still has the demos installed. Going to them directly should work, https://demo.bigbluebutton.org/demo/demo1.jsp.

**Comment by ffdixon** [comment]
Closing as this was an issue related to the Flash client (the project has moved to an HTML5 client).
