### ISSUE TITLE
Testing 100 users mockup

### ISSUE THREAD

**Issue by supun19** [bigbluebutton/bigbluebutton#6595]
I want to test BBB with 100 users. is there any way to create mock 100 users for a conference?

**Comment by ffdixon** [comment]
We have some guidelines for testing here http://docs.bigbluebutton.org/support/faq.html#how-many-simultaneous-users-can-bigbluebutton-support.

There are no out-of-the-box tools for testing users, but with the HTML5 client it should be possible to use any tool that can join an HTML5 session.  BigBlueButton uses WebRTC audio, so if your test environment can join the audio, that would be a more accurate test.

**Comment by supun19** [comment]
Thank You @fbottin 
let say I am going to test BBB using server. there are not audio and video devices. is there are any way to feed video file instead of webcam steam to the conference?. could you give me a suggestion to this also?

**Comment by GhaziTriki** [comment]
Closing. This should go to the forums.
