### ISSUE TITLE
Close user menu on scroll 

### ISSUE THREAD

**Issue by tylercopeland** [bigbluebutton/bigbluebutton#6602]
While interacting with the user's list, I noticed that if I have the user menu open and scroll down the list it doesn't close. 

<img width="683" alt="screen shot 2019-01-21 at 1 29 59 pm" src="https://user-images.githubusercontent.com/1273169/51492878-465d0a00-1d81-11e9-8a85-d0450f63e315.png">

My recommendation is to have users menu close on scroll to avoid situations where we have two menus open at the same time (refer to the image above).

**Comment by antobinary** [comment]
Merging issue into #6603
