### ISSUE TITLE
The powerpoint checker is vague when a check is failed and should be clarified

### ISSUE THREAD

**Issue by capilkey** [bigbluebutton/bigbluebutton#6611]
There is a class that check whether or not an uploaded PPT (or PPTX) is valid for processing and there are currently three different cases where the presentation will come back as invalid. If any of the cases is hit the only message in the logs is a generic "Presentation is invalid" log without a easy way to determine which case was the cause. The vague error message is also presented to the uploader and there's no way for them to determine what actually went wrong and correct the presentation.

There should be additional logs in the checking code on the server that clearly state which check was failed so someone investigating doesn't need to run bbb-web in development to debug the cause.

An additional, but more involved change would be to add the cause to the failure message going back to the client so a more accurate message can be displayed to them. This would allow the uploader to take steps to resolve the issue on their own.

The presentation checking code is found here, https://github.com/bigbluebutton/bigbluebutton/blob/7dfe3f3093974bb1af0891c626ded9de60689385/bigbluebutton-web/pres-checker/src/main/java/org/bigbluebutton/prescheck/Main.java.

Recent posts about failed uploads have shown a need for clearer messaging. See https://groups.google.com/forum/#!topic/bigbluebutton-dev/LhHms3Alfvk and https://github.com/bigbluebutton/bigbluebutton/issues/6585.

**Comment by aogilvie** [comment]
Another example:
https://groups.google.com/forum/#!topic/bigbluebutton-dev/5Tx-ClLiS74

Also, it is worth mentioning that if a file is passed with a meeting create API call, the session will still be created and 200 even if the file could not be converted successfully. I would argue this constitutes a failure, but I understand code-wise the meeting is created successfully before uploading the file. On the user-side, this is a failure though.

A separate single or batch file upload API might solve all the things.

Meeting create without a file is a GET, and with file XML data is POST, so without the separate file API it might still be an option to send back a different status code for POST when file convert fails. I have no idea what that status code would be though :(

**Comment by ffdixon** [comment]
For some error messages, it's very hard to describe the reason (and resolution) in a short sentence.

It would be better for the error message to include a link to a page that gives more explanation.
