### ISSUE TITLE
Unread message indicator remains active for private chats

### ISSUE THREAD

**Issue by akiwenziec** [bigbluebutton/bigbluebutton#6624]
The unread chat indicator remains active for private chats. Does not affect public chat.

See video below (private chat at aprox 30 seconds)

https://www.youtube.com/watch?v=y6Xs60J29HQ&feature=em-share_video_user

**Comment by antobinary** [comment]
Cannot reproduce anymore. @akiwenziec could you please try one more time?

**Comment by akiwenziec** [comment]
Am still able to reproduce issue
