### ISSUE TITLE
Locales: Previous locale not used on initial client load

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#6626]
![peek 2019-01-23 15-58](https://user-images.githubusercontent.com/6312397/51636636-bf966180-1f27-11e9-823c-2c728659cf3b.gif)
In the screenshot we see that the last time the client was used German had been set. A new session shows the client in English even though the default language is still set to German (in the Settings)

**Comment by capilkey** [comment]
Should we be using the previously set value for locale at all? It won't be consistent in a lot of real world scenarios.
