### ISSUE TITLE
Locales: Some languages cause the 2.2 html5 client to loop and reload

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#6627]
![peek 2019-01-23 11-00](https://user-images.githubusercontent.com/6312397/51636860-42b7b780-1f28-11e9-991f-9eed7930dba4.gif)
Once we solve this we can pull the latest 2.2 html5 locales

**Comment by aakatev** [comment]
@antobinary what was the issue here? encounter similar problem trying to add new locales to html5 client.

**Comment by antobinary** [comment]
@aakatev likely there is incorrect line(s) in the json - for example someone put double quotes inside which is the delimeter for the json i.e.
"someKey":"some value with "some" quotes" - breaks

"someKey":"some value without quotes" - doesn't break
"someKey":"some value with \"escaped\" quotes" - doesn't break

Next time open a new ticket if you need attention. I happened to stumble upon this by accident

**Comment by aakatev** [comment]
@antobinary gotcha, and thanks for getting back to me.
Ended up building the client from source, cause my desired language wasn't imported from react-intl in the default build. It fixed  all my problems.
