### ISSUE TITLE
Screen share could not stop when network reconnect.

### ISSUE THREAD

**Issue by formyangel** [bigbluebutton/bigbluebutton#6630]
Follow the steps will reproduce the problem.

1. Start share the screen.
2. Disable the network connection
3. Reconnect the network and reload the page.
4. Now, the screen share button is red, and loading animation shows in center. but nothing share.
5. Press stop share screen, could not stop screen share.

The BBB version is 2.0 RC9

**Comment by JustinMogel** [comment]
tested this on 2.3-alpha-8 with Firefox 89.0 
as i reconnected to the internet, the BBB tab in the browser showed the previous presentation and screen sharing stopped.
BBB worked fine afterwards.
So this seems to not be an issue anymore
