### ISSUE TITLE
Include "start recording" as recording action button 

### ISSUE THREAD

**Issue by akiwenziec** [bigbluebutton/bigbluebutton#6641]
Currently only the bullseye icon engages the recording - the words "start recording" should engage the recording when selected / should be included as the record action button

**Comment by tylercopeland** [comment]
@akiwenziec I completely agree. 

The following is an updated flow / screens that takes into consideration clicking the entire item (icon + text) to start and stop the recording. I also incorporated a modal that ensures the user they are about to start the recording as well as ending it. 

![html5-recording-1](https://user-images.githubusercontent.com/1273169/51841164-f7145d80-22db-11e9-883b-48ad1d126abf.png)

![html5-recording-2](https://user-images.githubusercontent.com/1273169/51841167-fb407b00-22db-11e9-9cd8-0cb2d03fa501.png)

![html5-recording-3](https://user-images.githubusercontent.com/1273169/51841183-00052f00-22dc-11e9-85bc-6e1186f8f2cf.png)

![html5-recording-4](https://user-images.githubusercontent.com/1273169/51841186-03001f80-22dc-11e9-8b09-25ab12ba381f.png)

As always further feedback is welcomed. cc @antobinary

**Comment by ffdixon** [comment]
After the record button is clicked, let's change the language from "Stop Recording" to "Pause Recording".

**Comment by antobinary** [comment]
Implemented in #6735
