### ISSUE TITLE
Viewer unable to rejoin after locked audio applied

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#6653]
On https://test.bigbluebutton.org/

if moderator  Lock Viewers Microphone.
and viewer refresh his web page, or reconnect, 
then this viewer is unable to join audio anymore. 

Reported in 

   https://groups.google.com/d/msg/bigbluebutton-dev/kFronMExXxQ/_MzG2714DQAJ

**Comment by jfsiebel** [comment]
This problem was already reported in #6574 and fixed in #6617, just need to test and merge.

**Comment by ffdixon** [comment]
Thanks @jfsiebel for pointing this out!
