### ISSUE TITLE
Intranet Problem

### ISSUE THREAD

**Issue by smtdede10** [bigbluebutton/bigbluebutton#6689]
BiblueButton installed on Ubuntu 16.04. I want to run BBB in the Intranet. Firstly, try to run local network, there is no problem. But, after people who are in other cities  connect to the system, I can not control some settings such as change persentation or sending message or disable user voice etc. but video streaming is awesome no problem also sharing screen is good but ı can not control menus. I dont use firewall or there is no restriction (I hope) in network.

**Comment by pedrobmarin** [comment]
For help on those cases, we suggest https://groups.google.com/g/bigbluebutton-setup
