### ISSUE TITLE
Chat and slides missing in Published recording

### ISSUE THREAD

**Issue by yvangodard** [bigbluebutton/bigbluebutton#6697]
On a fresh install of BBB, we are experiencing some problems with published recordings.
Our problem is simple : chat and slides are missing on published recording.

All the processing seems to work without issu, bbb-conf check just tells this
have a look : https://hastebin.reseauenscene.fr/yugoqetuci.bash

bbb-recording displays that : 
https://hastebin.reseauenscene.fr/egexumudad.lua

bbb-recording --debug doesn't give us any clue.

You could have a look on a public presentation with this problem here : 
https://bbb-serveur.occitanie-en-scene.fr/playback/presentation/2.0/playback.html?meetingId=a7b5e78fd47d6a78bf83a27b07cc294aba855f6b-1549015786662

Any idea to solve this problem?
Thanks a lot!

**Comment by yvangodard** [comment]
If this can help you, here is all the output of bbb-conf --debug : 
https://hastebin.reseauenscene.fr/ekuhulexag.vbs

**Comment by ffdixon** [comment]
Thanks for pointing this out -- we see the issue here and are working on a fix.  Since we can reproduce, we should have it fixed quickly.

**Comment by kepstin** [comment]
We've reverted the change that broke this in 2.0. (This was related to the fix for #6463 )
