### ISSUE TITLE
RC11 has some problem with freeswitch ip

### ISSUE THREAD

**Issue by netlabs** [bigbluebutton/bigbluebutton#6715]
I have upgraded my server to RC11. after upgrading I got error 1007: ICE negotiation failed. I have torubleshooted steps from http://docs.bigbluebutton.org/install/install.html#client-webrtc-error-codes
Problem found at 
**To diagnose this error, open about:webrtc in FireFox and click ‘show details’ for the most recent connection. Look under the column Remote Candidate and check if you see the internal IP address of the BigBlueButton server. If so, you probably have a misconfiguration in the FreeSWITCH settings. Re-check against the examples shown above.**

I have changed all configuration files but still in about:webrtc still its taking internal ip.

**Comment by ffdixon** [comment]
Hi there,

Did you make any custom changes to FreeSWITCH configuration, such as settting it upto work behind firewalls (see: http://docs.bigbluebutton.org/install/install.html#configure-bigbluebutton-behind-a-firewall).

If so, you'll need to re-apply the changes to FreeSWITCH's configuration files.  Also check the sip.nginx file (see the above link for details).

**Comment by netlabs** [comment]
Will check that and revert.

**Comment by netlabs** [comment]
Its working . Thankyou
