### ISSUE TITLE
User and guest management

### ISSUE THREAD

**Issue by tylercopeland** [bigbluebutton/bigbluebutton#6717]
The following are mockups for the guest management experience in the HTML5 client. 

**Moderator | Sidebar + Notification**
As a Moderator  _(when user management is enabled)_, you'll see an item appear as "User Management" in the sidebar and an indicator (4) showing the number of users waiting. As a new user joins the waiting queue, a notification will appear in the top right-hand corner notifing the moderator/presenter that a new user is waiting. 

![html5-moderator-user-management-1](https://user-images.githubusercontent.com/1273169/52290495-2cedbd80-293e-11e9-8be4-fe3d244f8275.png)

**Moderator | User Management**
A Moderator can open the user management panel by selecting the item in the sidebar or by clicking the notification in the top right-hand corner. 

Within the panel, a moderator has bulks actions "allow everyone" and "denies everyone," as well as the ability to allow and or deny individuals. In the mockup below you will see a number to the left of a users name, this indicator their order in the queue. 

![html5-moderator-user-management-2](https://user-images.githubusercontent.com/1273169/52290501-2eb78100-293e-11e9-8b0c-480f51aebc57.png)

**Moderator | User + Guest Management**
If the instance of BigBlueButton also supports guests access, there will be a separate list of guests waiting to join the session. 

![html5-moderator-user-management-3](https://user-images.githubusercontent.com/1273169/52290506-2fe8ae00-293e-11e9-81fb-6bca60cb79e4.png)

**User | Queue Position**

As a user waiting to join the session, we want to provide them with an understanding of where they are in the queue. The mockup below is a simple concept that outlines queue number, the session name and the moderator of the session. 

![html5-queue](https://user-images.githubusercontent.com/1273169/52292809-84425c80-2943-11e9-8643-bd65af1eb866.png)

**Comment by ritzalam** [comment]
The current implementation of guest wait is that on JOIN API, if the client is supposed to wait, the client is redirected to an intermediate page.

```
    if (guestStatusVal.equals(GuestPolicy.WAIT)) {
      clientURL = paramsProcessorUtil.getDefaultGuestWaitURL();
      destUrl = clientURL + "?sessionToken=" + sessionToken
      msgKey = "guestWait"
      msgValue = "Guest waiting for approval to join meeting."
    } else if (guestStatusVal.equals(GuestPolicy.DENY)) {
      destUrl = meeting.getLogoutUrl()
      msgKey = "guestDeny"
      msgValue = "Guest denied to join meeting."
    }
```
[JOIN API](https://github.com/bigbluebutton/bigbluebutton/blob/master/bigbluebutton-web/grails-app/controllers/org/bigbluebutton/web/controllers/ApiController.groovy#L505)

The `defaultGuestWaitURL` is found on `bigbluebutton.properties` [here](https://github.com/bigbluebutton/bigbluebutton/blob/master/bigbluebutton-web/grails-app/conf/bigbluebutton.properties#L221)

```
# The url for where the guest will poll if approved to join or not.
defaultGuestWaitURL=${bigbluebutton.web.serverURL}/client/guest-wait.html
```

The Guest Wait page just polls bbb-web's `guestWait` API to see if the client has been accepted into the meeting.

https://github.com/bigbluebutton/bigbluebutton/blob/master/bigbluebutton-client/resources/prod/guest-wait.html

**Comment by capilkey** [comment]
I'm not sure that we want to have "st", "rd", or "th" after the queue number. I'm going to guess that it will be either impossible or very difficult to localize and cover all of the cases.

**Comment by ritzalam** [comment]
```
# Default Guest Policy
# Valid values are ALWAYS_ACCEPT, ALWAYS_DENY, ASK_MODERATOR
#
defaultGuestPolicy=ALWAYS_ACCEPT
```

Change the `defaultGuestPolicy` to `ASK_MODERATOR` or pass param `guestPolicy=ASK_MODERATOR` on the CREATE API call.

Then on the JOIN API, pass `guest=true` as param with role viewer.

**Comment by tylercopeland** [comment]
@capilkey happy to leave that piece out if it's going to cause issues with localization.

**Comment by nplesa** [comment]
Hi guys,

How can i set guest policy on each meeting?Is is possible?  I do not found in php api getter / setter for guest policy! (I looking on CreateMeetingParams and JoinMeetingParams).

Best Regards,

**Comment by Tainan404** [comment]
Hi @nplesa,

We have a custom parameter on create endpoint where you can pass the rule for the meeting.

`guestPolicy=ALWAYS_ACCEPT //OR ALWAYS_DENY,ASK_MODERATOR`

For more details take a look it the [api docs].(https://docs.bigbluebutton.org/dev/api.html#create)

**Comment by nplesa** [comment]
Hi Tainan404,

I have $bbb is bigbluebutton instance from php API;
For creating Room with guestPolicy =ASK_MODERATOR i have:
$guest_policy = ASK_MODERATOR;
$createParams = new CreateMeetingParameters($room_name."[".$meetingId."]", $room_name);
$createParams = $createParams->setModeratorPassword($mod_pass)
->setAttendeePassword($stu_pass);
		$createParams->setRecord(true);
		$createParams->setAllowStartStopRecording(true);
		$createParams->setAutoStartRecording(false);		
$createParams->setGuestPolicy($guest_policy)(This function doesnt exist yet :) );

after set create params , i do :
$response = $bbb->createMeeting($createParams);

and on response, when i take response xml, response doesnt have any information about room guest policy.

Is corect in this way?

**Comment by nplesa** [comment]
Hi,

After createMeeting url is created, something like "http://192.168.0.120/bigbluebutton/api/create?name=ROOM+1+MODB&meetingID=ROOM+1%5B9a73160a-54d2-4b4f-8560-0815cd0263f0%5D&attendeePW=VkJJbEk3&moderatorPW=aGVrMkZHZjY4LQ%3D%3D&record=true&autoStartRecording=false&allowStartStopRecording=true&webcamsOnlyForModerator=false&guestPolicy=ASK_MODERATOR&checksum=5aaf1b700e658eafdf1d83f195cf3fefeb4e2d79" is executed function named "processXmlResponse" in bigbluebutton.php line 104 which have like first parameter url for creatingMeeting, second function param is empty. After request, by curl, response does not contain guestPolicy. How can be added this guestPolicy to response?

Best Regards,

**Comment by antobinary** [comment]
Salut @nplesa ,

I am guessing you're looking into adding `guestPolicy` in the response for create meeting - see https://github.com/bigbluebutton/bigbluebutton/blob/develop/bigbluebutton-web/grails-app/controllers/org/bigbluebutton/web/controllers/ApiController.groovy#L2149

and

https://github.com/bigbluebutton/bigbluebutton/blob/develop/bbb-common-web/src/main/java/org/bigbluebutton/api/util/ResponseBuilder.java#L67-L121

I hope this is helpful. If you require further help, please ask on bigbluebutton-dev google group or use a new issue - this one is a year old and was closed :)

**Comment by nplesa** [comment]
Thanks Anton,

It is all i want! :)

**Comment by harika1258** [comment]
Hi Guys....
How can I get Nickname who wants to join a room in the Lobby? (Guest.html)

**Comment by harika1258** [comment]
I answered in the this issue : **find user's ip #2224**
