### ISSUE TITLE
bbb-record-core package is missing a dependency on rsync

### ISSUE THREAD

**Issue by kepstin** [bigbluebutton/bigbluebutton#6718]
Starting with 2.2, the recording scripts use rsync to copy media files around. We need to add a dependency on the rsync package so it's installed, otherwise recordings might not process.

rsync is installed by default in most ubuntu server installations, but it might be missing in containers or minimal vms.

**Comment by ffdixon** [comment]
Done.  Added to the packaging for BigBlueButton 2.2-dev.
