### ISSUE TITLE
Make the webcam[s] not cover the presentation at any time

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#6724]
Currently this is a problem specifically when there is only one webcam shared

**Comment by tylercopeland** [comment]
@antobinary through various conversions and now that we are working on the fixed presentation bar, the best next steps for the webcam experience is the following:

1) One webcam - Bottom right-hand corner. It should be small enough and appear under the presentation and presentation bar.

![screen shot 2019-02-14 at 4 08 30 pm](https://user-images.githubusercontent.com/1273169/52817763-d5a0c900-3072-11e9-9567-2ea6d0e19b29.png)

If the webcam is in a small state, as seen above, it might make sense to hide the users name.

2) Two webcams - The appears above the presentation, and the experience follows what we have currently implemented.

**Comment by capilkey** [comment]
A webcam that is that small is very difficult to see.

**Comment by antobinary** [comment]
Seems the attached solution image did not attach properly @capilkey :smiley_cat:

**Comment by ffdixon** [comment]
Agreed that the webcam is going to be small (too small), but this is an intermediate step.  Right now, let's trade the smaller webcam for never obscuring the controls.  

Ultimately, we need the webcam placement a smarter if we're going to make it larger and overlay it on the bottom right-hand corner of the presentation, or place it on the right, or top, depending on where there is "empty space" in the display.  

This area of empty space depends on (a) the orientation of the document (portrait or landscape), and (b) the area for the application to render (is on a mobile, wide window, or tall window).

This pull request is not the final form for webcams, but will service us for the moment to resolve the (very obvious) UI issues of covering controls.
