### ISSUE TITLE
Chat and slides missing in Published recording

### ISSUE THREAD

**Issue by aliabuzaid** [bigbluebutton/bigbluebutton#6745]
Chat and slides missing in Published recording and can't find what can be causing the problem ?
also bbb-record --debug is not working 

example ::
https://bigbluebutton.znoterra.info/playback/presentation/2.0/playback.html?meetingId=6fffef11bdc5ff82fd4a6ecd290763c939e6f0d2-1549556783379

any ideas ?

**Comment by ffdixon** [comment]
Can you upgrade to 2.0-RC11 and let us know if the chat and slides now appear, see: https://github.com/bigbluebutton/bigbluebutton/releases/tag/v2.0-rc11

**Comment by aliabuzaid** [comment]
> Can you upgrade to 2.0-RC11 and let us know if the chat and slides now appear, see: https://github.com/bigbluebutton/bigbluebutton/releases/tag/v2.0-rc11

Dear @ffdixon,
Should I replace files on server, or go through the dev environment setup ?
regards,

**Comment by aliabuzaid** [comment]
Dear @ffdixon 

Thank you very much !! it is fully functional now 

Regards,
