### ISSUE TITLE
Request for STUN/TURN servers not matching expected format

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#6748]
In the previous version of `bbb-web` for 2.2, a request for STUN/TURN server information 

  https://example.com/bigbluebutton/api/stuns?sessionToken=ahbc

returned the following JSON

~~~json
{
   "stunServers":[
      {
         "url":"stun:turn.blindsidenetworks.com"
      }
   ],
   "turnServers":[
      {
         "username":"15498234672:w_490akzryfrud",
         "password":"vAe+8jsmsadfEo=",
         "url":"turns:turn.example.com:443?transport=tcp",
         "ttl":86400
      }
   ],
   "remoteIceCandidates":[

   ]
}
~~~

However, in the new `bbb-web` the return is formatted differently

~~~json
{
   "response":{
      "stunServers":{
         "stunData":{
            "url":"stun:turn.blindsidenetworks.com"
         }
      },
      "turnServers":{
         "turnData":{
            "username":"15498234672:w_490akzryfrud",
            "password":"vAe+8jsmsadfEo=",
            "url":"turns:turn.example.com:443?transport=tcp",
            "ttl":86400
         }
      },
      "remoteIceCandidates":{

      }
   }
}
~~~

and is causing the HTML5 client to throw an error.

**Comment by ffdixon** [comment]
Here's what the response now looks like after #6754. 

~~~
{
    "stunServers": {
        "stunData": {
            "url": "stun:stun.freeswitch.org"
        }
    },
    "turnServers": {
        
    },
    "remoteIceCandidates": {
        
    }
}
~~~

However,  the client is expecting arrays for "stunServers" and "turnServers".

**Comment by GhaziTriki** [comment]
I confirm this is the correct format since at least two years, since we move bbb-web to Java 8 https://github.com/bigbluebutton/bigbluebutton/commit/f8005a52#diff-f4a6b2c8f478d1d26175b01acef414c5R1603

In this case Flash and HTML5 clients need to match the correct format.

**Comment by capilkey** [comment]
The return has been broken for a long time then because it is perfectly valid to have multiple of STUN or TURN servers defined in turn-stun-servers.xml and it's perfectly valid for usage with WebRTC.

**Comment by capilkey** [comment]
My 2.0 and 2.2 servers both return arrays so something changed in this bbb-web upgrade and it needs to be put back to arrays.

**Comment by prlanzarin** [comment]
:thinking: AFAIK we've been using multiple STUN/TURN servers in the config for a long time now (before the bbb-web upgrade), so the previous return values shouldn't be broken.
