### ISSUE TITLE
HTML5: Detect poll options from slide's converted text

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#6755]
Related to
<del> #719 https://github.com/bigbluebutton/bigbluebutton/pull/719/files#diff-73be6b57fb6e08b05bf41482f1c600feR28 </del>

**Comment by antobinary** [comment]
@capilkey -- is there anything related to this feature in Flash client that was implemented outside of #719?

@tylercopeland - do we have a design for this quick poll option?

**Comment by capilkey** [comment]
It's very different from that PR. That was just a first shot at it. The current version can be found here, https://github.com/bigbluebutton/bigbluebutton/blob/master/bigbluebutton-client/src/org/bigbluebutton/modules/polling/views/QuickPollButton.as.

**Comment by capilkey** [comment]
[PollTestPresentation.pdf](https://github.com/bigbluebutton/bigbluebutton/files/2852708/PollTestPresentation.pdf)
I used this file to test the Flash version.

**Comment by antobinary** [comment]
^ slides 1,2,3 trigger the quick poll but 4,5,6 do not (intentionally)

**Comment by tylercopeland** [comment]
@antobinary thanks for pointing this out. 

The following are mockups for having the "Quick Polling" feature in the HTML5 client. 

**Step 1** 
When a Quick Poll is detected within the HTML5 client, a new button _(we can call it the quick polling button)_, will appear to the right of the ( + )  button. This button should use the round button style and primary blue as the colour. When a presenter hovers over the button, a tooltip should appear with "Quick Poll A/B" as the text.

![html5-quickpoll-1](https://user-images.githubusercontent.com/1273169/52727865-24236a00-2f84-11e9-9da1-44e02f7e01cc.png)

**Step 2** 
When the presenter clicks the "Quick Poll" button, the polling type will trigger, and the polling pannel will open showing the presenter the live results for that poll. 

![html5-quickpoll-3](https://user-images.githubusercontent.com/1273169/52728484-5e413b80-2f85-11e9-81a3-22eb45a52b9f.png)
