### ISSUE TITLE
The audio icon flashes in the user list when presenter is lost

### ISSUE THREAD

**Issue by capilkey** [bigbluebutton/bigbluebutton#6762]
When a user loses presenter status a circle shows up momentarily where the audio status should be. I've attached a GIF of it in action. It looks quicker than it is because of the FPS of the GIF. The GIF also shows that changing the emoji doesn't cause the flicker.

![badgeblink](https://user-images.githubusercontent.com/1395090/52602316-2f658100-2e30-11e9-9bae-0f341cc422b9.gif)

**Comment by ffdixon** [comment]
Unable to reproduce in the latest build of the HTML5 client.
