### ISSUE TITLE
Adjust the size of the custom polling results so that the content is legible

### ISSUE THREAD

**Issue by tylercopeland** [bigbluebutton/bigbluebutton#6782]
As seen in the screenshot above belove, I chose a custom poll type and the polling results (specifically the polling options) are displaying quite small. 

![screen shot 2019-02-14 at 3 53 29 pm](https://user-images.githubusercontent.com/1273169/52817889-3af4ba00-3073-11e9-8ea7-62239eedd953.png)

**Comment by antobinary** [comment]
The result is actually an 'annotation' we simply display in the clients. If anything is to be changed, it will have to be in the back end

**Comment by KDSBrowne** [comment]
Using the Pan / Zoom  at the moment can at least make the results legible.

**Comment by ffdixon** [comment]
Making the changes on the back-end as well is fine -- we originally picked a fixed width for the polling results, and with custom poll types, we need to make that width dependent on the longest option for custom poll type.

The width needs to be variable in the display and in the recording.

**Comment by kepstin** [comment]
No recording changes are needed - the recording processing inserts the poll in the location and size from the recording event, so it'll match the live session automatically.

**Comment by grinapo** [comment]
:roll_eyes:  :eyeglasses: :mag:
