### ISSUE TITLE
Error on sharing screen and webcam

### ISSUE THREAD

**Issue by comete-upn** [bigbluebutton/bigbluebutton#6784]
Hi,

After a server reboot, sharing webcam (and screen) was impossible: "Error on sharing webcam".  
The error read "Erreur lors du partage de la webcam" in French.

- BigBlueButton Server 2.0.0-RC11 (1672)
- Kernel version: 4.4.0-142-generic
- Distribution: Ubuntu 16.04.5 LTS (64-bit)
- Memory: 8156 MB

The command `sudo bbb-conf --check` didn't report any potential problem.

The error message in `/var/log/bbb-webrtc-sfu/bbb-webrtc-sfu.log.$(date +%Y-%m-%d)` was of little use: "Cannot read property 'stack' of undefined at Video._handleError".

Reading previous issues, I learned the existence of the command `bbb-conf --status`, which gave me the answer:

```
mongod ————————————————► [✘ - failed]
```

A simple restart was enough to fix the problem: `sudo bbb-conf --restart`

I hope this can help others.

&nbsp;

Could it be possible to use the result of the statuses when looking for potential problems?

I added a watchdog to my server with this simple script:

```bash
if [ "$(bbb-conf --status | grep -v active)" ]; then
  exit 1
fi
```

&nbsp;

Regards.

**Comment by ffdixon** [comment]
We've improved the start of mongod in 2.2-beta.  Closing this issue, but please open a new issue if you see it in 2.2 (or a later release).
