### ISSUE TITLE
Add a redo button to the whiteboard

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#6798]
There are times when a user may want to redo the previous action, such as when they entered text in the whiteboard (using the text tool) and inadvertently cleared the text.

Add a 'redo' button to the list of whiteboard controls.

**Comment by KilluaxGonx** [comment]
This is so relevant! Thank you, and please implement.

Too often after enabling my students to interact with the whiteboard, they'll accidentally clear the board which would erase sometimes 30 minutes worth of work by the student.

This happend to as recent as yesterday!

**Comment by ffdixon** [comment]
Got it -- it's on the our road map and we'll be looking at implementing it after BigBlueButton 2.2 (which will have a HTML5 front-end).

**Comment by antobinary** [comment]
Implemented in BBB 2.6 -- by including tldraw whiteboard. Undo is ctrl+z, Redo is ctrl+shift+z
