### ISSUE TITLE
[2.2 Beta][HMTL5] Chat window is open by default

### ISSUE THREAD

**Issue by aogilvie** [bigbluebutton/bigbluebutton#6799]
By default the chat panel is open when entering a session.
Can that be configured as hidden by default?

**Comment by aogilvie** [comment]
I still see this on 2.2. beta3, there does not seem to be a way to set this from config, can be be done programatically somewhere?

**Comment by aogilvie** [comment]
Looking for an update/solution to this, a small code modification we can implement is also fine. Just looking for where is appropriate to add.

**Comment by ffdixon** [comment]
It's on our radar -- we're looking to add some properties to the 'create' and 'join' API calls to let you customize the meeting (such as locking private chat) and customize the user (start with chat panel hidden).

We don't have a timeline on this, but the work is ongoing.  We'll update this ticket as soon as we have more to report.

**Comment by antobinary** [comment]
Hi @aogilvie 
https://github.com/bigbluebutton/bigbluebutton/blob/master/bigbluebutton-html5/private/config/settings.yml#L6 `showParticipantsOnLogin: false` will not display the userlist + chat by default on client login. Are you looking to further configure userlist to be visible but not chat?

**Comment by aogilvie** [comment]
We would like to show the user list. However chat hidden by default.

**Comment by KDSBrowne** [comment]
Hey @aogilvie

In order to have only the `Userlist` open by default when a user joins, the code in the `join-handler` would have to modified.

https://github.com/bigbluebutton/bigbluebutton/blob/master/bigbluebutton-html5/imports/ui/components/join-handler/component.jsx#L137

switching it to `Session.set('openPanel', 'userlist');` and removing `Session.set('idChatOpen', '');`

**Comment by aogilvie** [comment]
Thanks! Commented out that line works perfect.

**Comment by NodeGuy** [comment]
How do I do this on a fresh installation?  I don't see that source file on my server.
