### ISSUE TITLE
[2.2 Beta][HMTL5] Maximise Presentation Width Configuration

### ISSUE THREAD

**Issue by aogilvie** [bigbluebutton/bigbluebutton#6800]
Can maximise width button be configured as hidden?
We could not find a use case for this feature and it confused our presenters (who though it was re-setting the width to 100% after zoom).

**Comment by ffdixon** [comment]
The button is really only meant for portrait documents, it replaces the earlier fit-to-width and fit-to-page button.

Try uploading a portrait document (such as a word document), and then click the maximize width button (should probably just call it fit-to-width again).

There is a bit more work we need to do on this feature, see . https://github.com/bigbluebutton/bigbluebutton/issues/6489.

**Comment by aogilvie** [comment]
Thanks. We didn't see a need for this feature, so we hid with CSS.
