### ISSUE TITLE
[2.2 Beta][HMTL5] Shared Notes Configuration

### ISSUE THREAD

**Issue by aogilvie** [bigbluebutton/bigbluebutton#6801]
Can this feature be configured? (Display true/false)

**Comment by ffdixon** [comment]
Yes, in BigBlueButton 2.2-beta this is configurable.

 Edit `/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml`, locate the settings for `notes` and set `enabled` to `false`.

~~~
  note:
    enabled: false
~~~

Restart the `bbb-html5` and the shared notes option should now no longer appear.

You can ensure it's always hidden after upgrading packages, add the following lines

~~~
yq w -i /usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml public.note.enabled false
~~~

to `/etc/bigbluebutton/bbb-conf/apply-config.sh` (see `apply-config.template` in the same directory) .

`bbb-conf` automatically runs `apply-config.sh` (if it exists) during `bbb-conf --restart` and `bbb-conf --setip` to ensure your settings are always applied each time BigBlueButton starts.

We added `apply-config.sh` in BigBlueButton 2.2-beta to make it easier to do a package upgrade that might overwrite some custom changes.

**Comment by aogilvie** [comment]
@ffdixon Tried this with 2.2beta3 and setting `enabled: false` has no effect. The session still displays the memo. Please take a look, this might be a bug.

**Comment by leandroald** [comment]
Prezados, 

Onde é guardado o log do que foi digitado na notas compartilhadas? 

É possível descobrir quem digitou algo lá?

**Comment by matiasilva** [comment]
Oi @leandroald. Existe vários pacotes que podes baixar para isto, nomeadamente bbb-playback-notes. Mais informação [aqui](https://groups.google.com/forum/#!searchin/bigbluebutton-dev/bbb-playback-notes%7Csort:date/bigbluebutton-dev/xTSmfi9Wbdo/fwumuE84AwAJ). O processo de instalação é o mesmo já que estes pacotes estão disponiveis nos repositórios de Ubuntu iguais ao, por exemplo, bbb-html5.
