### ISSUE TITLE
[2.2 Beta][HMTL5] Presentation full-screen icon hidden when one camera is displayed

### ISSUE THREAD

**Issue by aogilvie** [bigbluebutton/bigbluebutton#6802]
When one video camera is being displayed (either presenter or participant) the full-screen icon (bottom-right) on the presentation is hidden on screens that are not very wide (laptops etc.).

**Comment by aogilvie** [comment]
1920x1080 (16:9)

![example2](https://user-images.githubusercontent.com/970364/52930668-a8169100-338c-11e9-83f2-28bae1e860c7.png)

**Comment by ffdixon** [comment]
Noted.  We're working on improving the layout of webcams so it doesn't overwrite content in the presentation area, see https://github.com/bigbluebutton/bigbluebutton/issues/6724.

**Comment by aogilvie** [comment]
webcams no longer overlap.
