### ISSUE TITLE
demo.bigbluebutton.org   html5 demo page.   username with " fails webrtc

### ISSUE THREAD

**Issue by hostbbb** [bigbluebutton/bigbluebutton#6805]
[17:06:56:0011] ERROR: clientLogger: Audio Error: GENERIC_ERROR CONFIGURATION_ERROR: Invalid value "w_jy1ja98p8xzb-bbbID-sss\"qq" for parameter "displayName" t (https://demo.bigbluebutton.org/html5client/0bb2d0ed4ff19badb3794c0ab487e62dcc85444e.js?meteor_js_resource=true:125:788960)

https://demo.bigbluebutton.org/demo/demoHTML5.jsp

username with "  enters the session fine and appears,  but webrtc fails to connect with above error

**Comment by hostbbb** [comment]
same for flash client Invalid value "w_eabcyzkqw2dx-bbbID-ddddd\"ccc"

note the backslash to escape appears in websole just does not display in this issue test correctly

**Comment by capilkey** [comment]
I need to pull this commit into 2.2 https://github.com/bigbluebutton/bigbluebutton/commit/1069f9baa8775aa64997472356a627f75574dfd8. It replaces the " with '.

**Comment by hostbbb** [comment]
is demo.bigbluebutton.org running 2.0? or 2.2?   its broke on demo.

**Comment by capilkey** [comment]
demo.bigbluebutton.org is running 2.2 now
