### ISSUE TITLE
Change the color of the current speaker in the video area

### ISSUE THREAD

**Issue by n00n3L** [bigbluebutton/bigbluebutton#6810]
Hello, I apologize if this is not the right place to ask this.

I just upgraded to version 2.0.0-RC11 and my users are having trouble seeing who is the current speaker in the video area cause it gets highlight in light blue. Is there any way to change this color?

**Comment by ffdixon** [comment]
It is a but subtle.  

I'm thinking we should highlight the current speaker in a darker colour, such as a dark blue.

**Comment by pedrobmarin** [comment]
I believe https://github.com/bigbluebutton/bigbluebutton/pull/8292 and https://github.com/bigbluebutton/bigbluebutton/pull/10212 covered this issue. You may reopen if you think otherwise.
