### ISSUE TITLE
Can't disable meeting mute

### ISSUE THREAD

**Issue by capilkey** [bigbluebutton/bigbluebutton#6817]
Steps to reproduce:
1. Join a conference as an HTML5 Moderator
2. Press the gear icon
3. "Mute all users"
4. Press the gear icon
5. "Turn off meeting mute"

Expected result:
The meeting mute should be turned off and when the gear icon is pressed again the option should be given to mute the meeting again.

Actual result:
No change in the meeting state and the menu never changes.

Additional Information:
The meeting mute/unmute works as expected in the Flash client so it looks like this is local to HTML5 code.

**Comment by ffdixon** [comment]
I was about to pen an issue for this but Chad beat me to it :-).  Here's a quick GIF that I had created to demonstrate

![meetingmute](https://user-images.githubusercontent.com/290351/53138171-6257f500-3553-11e9-93e1-54d024bb8953.gif)

**Comment by premmohantyagi** [comment]
"Turn off meeting mute" issue not fixed
Getting the same issue in latest release 2.2.20

**Comment by hemalmewada** [comment]
Hello all... I suppose the feature should be working like explained below. 

1) Mute All Users : This will mute all participants and also disable the ability to unmute themselves except the moderators.
2) Turn off Meeting Mute : Pressing this again will restore the ability for participants to unmute themselves. 

This works perfectly since we have a "Raise your hand" feature to ask permission to speak during an ongoing lecture. When the teacher finishes her session she can turn off the meeting mute and address the person.

**Comment by Jossef-767** [comment]
It would be very helpful if it were so
but Currently it will not disable the ability of users to unmute themselves.
The only way right now to prevent unmute is to lock microphones.
But it causes a problem for those who come in after the lock. Or for users whose page has been refreshed, In this case, they go into "listening only" mode and do not understand why their microphone is not working.

**Comment by mokazemi** [comment]
There are some functions in BBB which it's not clear from their name what they do. 
They're really confusing even in English, let alone translations. I suggest to choose a better name for them. 

**This one for example:**
![image](https://user-images.githubusercontent.com/18334056/177098864-6136d138-34ab-4f18-9928-ebbbfccc87ad.png)
I finally found out that this button, disables the function "Mute users when they join", so the new users join unmuted.
I don't know if it's going to do anything else. 
But a better name would be "disable mute users on start" or something like that.
