### ISSUE TITLE
Implement the per-user inactivity check in the HTML5 client

### ISSUE THREAD

**Issue by capilkey** [bigbluebutton/bigbluebutton#6818]
There's a per-user inactivity check that is in bbb-web, akka-apps, and the Flash client. It involves three properties in bbb-web's bigbluebutton.properties. They are `userInactivityInspectTimerInMinutes`, `userInactivityThresholdInMinutes`, and `userActivitySignResponseDelayInMinutes`. It's tracks each user and will prompt them when the time is up and the audit is run. Each user needs to acknowledge it individually and it also involves akka-apps and client messages.

https://github.com/bigbluebutton/bigbluebutton/blob/master/bigbluebutton-web/grails-app/conf/bigbluebutton.properties#L158-L167
```
# User inactivity audit timer interval.
userInactivityInspectTimerInMinutes=120

# Number of minutes to consider a user inactive.
# iSend warning message to client to check if really inactive.
userInactivityThresholdInMinutes=30

# Number of minutes for user to respond to inactivity
# warning before being logged out.
userActivitySignResponseDelayInMinutes=5
```

For easier testing I would suggest setting them to 1, 5, 1.

I think the language and options can follow the direction from the Flash client.

**Comment by ritzalam** [comment]
Every userInactivityInspectTimerInMinutes, the server will look for users with more than userInactivityThresholdInMinutes of not being active. The server will send a message ("poke") to these users and wait for userActivitySignResponseDelayInMinutes for the user to respond. If no response, the user is ejected from the meeting. The ejecting can only be cancelled by responding to the warning and not by any user activity.

**Comment by ritzalam** [comment]
Here is where we check, send, and eject users https://github.com/bigbluebutton/bigbluebutton/blob/master/akka-bbb-apps/src/main/scala/org/bigbluebutton/core/running/MeetingActor.scala#L623
