### ISSUE TITLE
Audio when removed from meeting

### ISSUE THREAD

**Issue by MaximKhlobystov** [bigbluebutton/bigbluebutton#6819]
You join full audio, get removed from meeting, see 403 page, but can hear yourself.

**Comment by MaximKhlobystov** [comment]
If you join listen only (as `username`) and get removed from meeting, `LISTENONLY-username` joins user list.

**Comment by ffdixon** [comment]
Good catch.

**Comment by ffdixon** [comment]
@MaximKhlobystov Still an issue?

**Comment by antobinary** [comment]
Merging in favour of #7198
