### ISSUE TITLE
Reduce recording processing time in 2.2

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#6826]
If there are no videos to process from red5, is this 120 second delay still needed in 2.2?

  https://github.com/bigbluebutton/bigbluebutton/blob/master/record-and-playback/core/scripts/rap-archive-worker.rb#L27

**Comment by kepstin** [comment]
This delay shouldn't be needed even when there are red5 videos, since the recording scripts sanity step will rebuild the .ser file into an .flv.

**Comment by ffdixon** [comment]
Sounds good.  Let's remove the delay and test the recordings (Flash and Kurento) to make sure everything still works.
