### ISSUE TITLE
Line break ignored during chat export

### ISSUE THREAD

**Issue by GhaziTriki** [bigbluebutton/bigbluebutton#6827]
If a chat message contains more than a single line, only the first line is exported using the chat save feature.

To reproduce it just type : `Hello` then hit SHIFT+ENTER then type `BigBlueButton`. Finally save the chat.

The saved text file will contain `[11:34] Student : Hello`.

We have the same issue for the copy feature.

**Comment by GhaziTriki** [comment]
This is an HTML5 client issue.

**Comment by prlanzarin** [comment]
Can't reproduce as of 2.3-beta.3

```
[19:21] asdasd : Hello
BigBlueButton
[19:21] asdasd : Hello

BigBlueButton
```
