### ISSUE TITLE
Cleared chat contains `PUBLIC_CHAT_CLEAR` after saving it

### ISSUE THREAD

**Issue by GhaziTriki** [bigbluebutton/bigbluebutton#6828]
Clear a chat than export it, it will contain a lines like this `[11:34] Student : PUBLIC_CHAT_CLEAR`. We have the same issue for the copy feature.

**Comment by GhaziTriki** [comment]
This is an HTML5 client issue.

**Comment by pedrobmarin** [comment]
Could not reproduce in v2.3-beta3
