### ISSUE TITLE
html5 video can't see each on the same meeting

### ISSUE THREAD

**Issue by yuexiajiayan** [bigbluebutton/bigbluebutton#6829]
On the HTML 5 page of my mobile phone, I added videos to see my pictures, but I couldn't see my pictures at the same meeting. What happened?

**Comment by ffdixon** [comment]
Are you testing sharing video between your mobile phone and the desktop?  Can you try it on https://test.bigbluebutton.org/ and let us know if it works.  If not, please provide the specs for your phone.  

The video is set to h.264.  

(We've seen that some Huawei phones do not provide the h.264 encoder/decoder in their phones, so they would unable to transfer video using the default settings.)

**Comment by yuexiajiayan** [comment]
> Are you testing sharing video between your mobile phone and the desktop? Can you try it on https://test.bigbluebutton.org/ and let us know if it works. If not, please provide the specs for your phone.
> 
> The video is set to h.264.
> 
> (We've seen that some Huawei phones do not provide the h.264 encoder/decoder in their phones, so they would unable to transfer video using the default settings.)

They can all see their videos, but they can't see each other.

**Comment by yuexiajiayan** [comment]
> Are you testing sharing video between your mobile phone and the desktop? Can you try it on https://test.bigbluebutton.org/ and let us know if it works. If not, please provide the specs for your phone.
> 
> The video is set to h.264.
> 
> (We've seen that some Huawei phones do not provide the h.264 encoder/decoder in their phones, so they would unable to transfer video using the default settings.)

ok

**Comment by yuexiajiayan** [comment]
i use chrome in android phone is ok
