### ISSUE TITLE
Multiline chat message shows in one line in recording playback

### ISSUE THREAD

**Issue by GhaziTriki** [bigbluebutton/bigbluebutton#6830]
If a user types `Hello` then SHIFT+ENTER then `BigBlueButton`, in the meeting we display a two-lines message. In the recording playback we see one-line with this content `HelloBigBlueButton`

**Comment by GhaziTriki** [comment]
This is an HTML5 client issue.

**Comment by pedrobmarin** [comment]
I'm almost sure this was fixed. Any feedbacks @GhaziTriki ?

**Comment by prlanzarin** [comment]
Can't reproduce as of 2.3-beta.3.

![image](https://user-images.githubusercontent.com/4529051/114249587-6df41900-9971-11eb-8f73-522c4ce16ee8.png)
