### ISSUE TITLE
The full screen presentation button doesn't show in Edge

### ISSUE THREAD

**Issue by capilkey** [bigbluebutton/bigbluebutton#6839]
When you look at the presentation area in Edge there's no button in the bottom right corner to make the presentation window full screen.

What I see:
![image](https://user-images.githubusercontent.com/1395090/53205233-bf0eea80-35fb-11e9-9940-b10e0451e6e2.png)

What I should see:
![image](https://user-images.githubusercontent.com/1395090/53205347-09906700-35fc-11e9-8ec8-278268d5575d.png)

**Comment by pedrobmarin** [comment]
Is there any error prompting in the console, @capilkey ?

**Comment by capilkey** [comment]
No errors. I think there's a check to see if a function exists before showing the button and I believe the issue is that the function to make an element full screen is different in Edge. I did some investigation in the the console and searches for "document.fullscree" returns functions and events that are prefixed with "webkit".

Another thing that we discovered is that the fullscreen button is shown on the webcams, but when I click it there's an error because the function doesn't have the same name. `Object doesn't support property or method 'requestFullscreen'`

**Comment by prlanzarin** [comment]
This also happens on Safari 12.0.2, and the thrown error in the webcam fullscreen button is similiar (`TypeError: this.videoTag.requestFullscreen is not a function. (In 'this.videoTag.requestFullscreen()', 'this.videoTag.requestFullscreen' is undefined)`).

**Comment by pedrobmarin** [comment]
Yeah, I saw this problem before. It also affects older versions of Chrome (right @jfsiebel ?). Also the close presentation button because we check if it is fullscreen before rendering.

**Comment by capilkey** [comment]
In the case of Edge there is support for it somewhere because I can make a Youtube video fullscreen so it seems like the code needs to be updated to support alternate function names.

**Comment by kepstin** [comment]
If we want to use a library for this, someone has helpfully made one that maps all the known prefixed fullscreen api implementations: https://github.com/rafrex/fscreen/blob/master/src/index.js
