### ISSUE TITLE
Resizable chat is pushing the presentation off screen

### ISSUE THREAD

**Issue by Tainan404** [bigbluebutton/bigbluebutton#6841]
![peek 2019-02-22 08-46](https://user-images.githubusercontent.com/15806883/53240858-9976f500-367e-11e9-8919-5221d7d8607c.gif)

**Comment by Tainan404** [comment]
Steps to reproduce: 
1) Open chat and decrease to minimum width.
2) Close and re-open the chat.
3) Increase the chat.

**Comment by antobinary** [comment]
![peek 2019-02-22 08-06](https://user-images.githubusercontent.com/6312397/53244397-c1fbf080-3678-11e9-899e-1f91dc376c9a.gif)
As part of the solution we can also handle better the overlap of action buttons (moderator/presenter case)
