### ISSUE TITLE
Cannot upload presentation with the same names even after deletion

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#6847]
![screenshot from 2019-02-22 12-26-21](https://user-images.githubusercontent.com/6312397/53259464-1c0ead00-369d-11e9-9cff-043c810e730f.png)
`{code: 404, message: "Not Found"}`

**Comment by capilkey** [comment]
You should also be able to upload presentations with the same name before deletion.

**Comment by antobinary** [comment]
Closing in favor of #7519 (contains the cause of the issue)
