### ISSUE TITLE
Add an "User X is typing" notification to chat

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#6851]
Add this to the HTML5 client (it was previously in the Flash client).

**Comment by Jarvil** [comment]
Hello,

Will this feature be available in HTML5 version 2.3?

**Comment by ffdixon** [comment]
Yes, probably in the next version.  Right now, we're pretty focused on finishing 2.2-beta.

**Comment by Urpokarhu1** [comment]
Hello,

When will this feature be added?

**Comment by ffdixon** [comment]
Good news -- it was added in BigBlueButton 2.2-beta-19

  https://github.com/bigbluebutton/bigbluebutton/releases/tag/2.2-beta-19
