### ISSUE TITLE
[2.0] --setip does not update the HTML5 clientLog configuration

### ISSUE THREAD

**Issue by GhaziTriki** [bigbluebutton/bigbluebutton#6856]
Using the `bbb-bonf --setip x.x.x.x` the following line in `settings-production.json` is not updated with the provided IP address

```json
    "clientLog": {
      "server": { "enabled": true, "level": "info" },
      "console": { "enabled": false, "level": "debug" },
      "external": { "enabled": false, "level": "info", "url": "https://158.230.156.100/html5Log", "method": "POST" }
    }
```

**Comment by antobinary** [comment]
The recommended way to configure this is by passing an override {with dev ops tools} in /etc/bigbluebutton/bbb-html5.yml
