### ISSUE TITLE
Exception when closing the presentation area

### ISSUE THREAD

**Issue by capilkey** [bigbluebutton/bigbluebutton#6857]
I closed the presentation area while multi-user was active and people were drawing and client went completely blue. The exception is below. I'm not sure that multi-user is required to make the exception happen, but it might make it easier to reproduce with more cursors being active.

![image](https://user-images.githubusercontent.com/1395090/53360447-8e80c680-3903-11e9-8852-9612f08fa102.png)

**Comment by fcecagno** [comment]
I believe the action of closing the presentation is just a coincidence - on issue #6812 I didn't close the presentation and the exception was triggered.
