### ISSUE TITLE
Annotations aren't received in Edge

### ISSUE THREAD

**Issue by capilkey** [bigbluebutton/bigbluebutton#6858]
When drawing in Edge the annotations are sent out and other browsers can see the updates, but Edge never gets the annotations sent to it. If I refresh the client the current snap shot of the annotations is displayed, but again no updates are received.

**Comment by pedrobmarin** [comment]
Since Edge now runs over Chromium I'll set this as a retest needed.

**Comment by pedrobmarin** [comment]
v2.3-beta3 working for Win10 Edge v89.0.774.76
