### ISSUE TITLE
Client locked if the conversion takes a too long time

### ISSUE THREAD

**Issue by GhaziTriki** [bigbluebutton/bigbluebutton#6867]
When uploading a heavy presentation it takes too much time to convert, we see the following message `Ops, the conversion took too long`, then the user interface is blocked and we cannot return back to the main interface.

![image](https://user-images.githubusercontent.com/4991088/53429667-5e155700-39ed-11e9-88ec-f9880e630156.png)

**Comment by antobinary** [comment]
Addressed in #7103
