### ISSUE TITLE
Make presenter OR Take presenter (moderator) need to choose one

### ISSUE THREAD

**Issue by akiwenziec** [bigbluebutton/bigbluebutton#6871]
Currently there are two different ways a moderator can take back the presenter status, both have different language / wording.

When the moderator selects their icon in the users list to take back presenter status the current wording is "make presenter"

![screen shot 2019-02-26 at 3 04 53 pm](https://user-images.githubusercontent.com/18176998/53443550-f3a6eb80-39d9-11e9-9e61-744948e1a524.png)

When the moderator selects the action button the wording is "take presenter role"

![screen shot 2019-02-26 at 3 04 45 pm](https://user-images.githubusercontent.com/18176998/53443686-41235880-39da-11e9-8087-67fe83212cee.png)

Both should be "Take presenter role"

reason: when the moderator is selecting themselves to be the presenter they are taking the role back after having assigned it to another user (viewer or other moderator).

**Comment by ffdixon** [comment]
I think the current way actually makes more sense.  When clicking on a user name, you are going to take an action on that user "Mute that user", "Chat with that user", "Make that user presenter", etc. (We shorten the phrase a bit to remove the 'that', but the operation on a user is implied")

When you click on the '+' icon, you (the presenter) are going to take an action, so the action is more imperative.  So "Start a poll", "Create breakout", "Take presenter" make sense here.

**Comment by akiwenziec** [comment]
I was referring specifically about the moderator:

- When the moderator is making themselves presenter again they are taking the presenter role back regardless of where they are clicking

**Comment by ffdixon** [comment]
Agreed -- the language should match both areas.

**Comment by antobinary** [comment]
![Screenshot from 2019-04-22 13-03-48](https://user-images.githubusercontent.com/6312397/56527115-2e7d5980-651b-11e9-8c15-b7e0179d7796.png)
I think when the moderator is triggering the menu on another user, the label should still be "Make presenter". In this case "taking" does not make sense.
Enacting the menu on yourself or the Action "+" button can keep the current "Take ..." label

**Comment by akiwenziec** [comment]
This change has affected viewer role menu language  - 

When a moderator goes to make a user a presenter the menu option is "take presenter" when it should be "make presenter"

![Screen Shot 2019-04-26 at 12 31 16 PM](https://user-images.githubusercontent.com/18176998/56822519-4dcbfd80-681f-11e9-9b79-9f1de7f6cf0c.png)
