### ISSUE TITLE
Webcam permissions can get into a broken state in Firefox

### ISSUE THREAD

**Issue by capilkey** [bigbluebutton/bigbluebutton#6894]
Firefox permissions are different from Chrome in that the option to remember you choice isn't selected by default and I think this difference allows me to break the sharing logic. 

Steps to reproduce:
1. Click the action button to open the modal (browser permission prompt should pop up)
2. Close the sharing modal without touching the browser popup
3. Select to allow the page to use your webcam
4. Click the action button to open the modal

No browser permission dialog will pop up and you're still allowed to attempt to share your webcam to other people, but the webcam hasn't actually been requested.

**Comment by antobinary** [comment]
Same as https://github.com/bigbluebutton/bigbluebutton/issues/6649 right?

**Comment by gustavotrott** [comment]
> Same as #6649 right?

Right @antobinary
I made some tests and this problem doesn't happen anymore after #6881
