### ISSUE TITLE
Need a definitive way to determine when Firefox enters the echo test

### ISSUE THREAD

**Issue by capilkey** [bigbluebutton/bigbluebutton#6897]
In every browser except Firefox they will send a ICE completed or ICE connected status when media is finished and flowing, but with Firefox they set the ICE status change before the call is actually set up. When the positive status comes back we show the user the options to say whether they hear themselves. Click "yes" will send a DTMF(1) to FS to transfer the user from the echo test into the conference. If in the case of Firefox the user isn't actually in the echo test yet, the DTMF will be ignored and the transfer will timeout. We need some way to positively confirm when FreeSWITCH knows that the user is in the echo test.

I don't think there's any way to determine the call state from the browser side because Firefox thinks that everything is good to go. If we had FreeSWITCH notify the browser when it's ready we could listen for that in the client and do the UI switch then. We should investigate if we can send a DTMF to the client when the echo test is ready.

**Comment by prlanzarin** [comment]
Isn't tracking the SIP dialog state with SIP.js' 'progress' event the proper way to do that?

**Comment by capilkey** [comment]
There's no SIP events received for the initial ICE negotiation nor the B-leg transfer. There's just radio silence in the browser when this is all going on.

**Comment by antobinary** [comment]
Implemented in  #7404
