### ISSUE TITLE
Moderator should be able to lock Shared Notes

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#6903]
Consistent with the lock features, moderators should be able to prevent viewers from writing in the Shared Notes (especially useful for K12).

Requested in bigbluebutton-dev:
   https://groups.google.com/d/msg/bigbluebutton-dev/J7OMGD277Kw/ldqBJpaSBwAJ

**Comment by antobinary** [comment]
Implemented in  #7138
