### ISSUE TITLE
Talking can cause text tool to lose focus

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#6904]
In a test with many webcams on the latest build of BigBlueButton 2.2-dev, after drawing a box to use the text tool, the text field would loose focus after a few seconds (preventing the user from typing further).

(The actual bug may not be related to the webcams, but it was when the issue first appeared).

**Comment by antobinary** [comment]
To reproduce this bug:
- enable multiuser whiteboard on the slide
- join with full audio
- type or draw continuously. The *change* in `isTyping` for self is stealing the focus from the whiteboard.

Tested with and without animation enabled, both are affected.
