### ISSUE TITLE
Web cam viewport goes pixelated/green intermittently for some users

### ISSUE THREAD

**Issue by sydneysider** [bigbluebutton/bigbluebutton#6913]
Hi hi,

Intermittently, our remote office see's one our users' cam window go green/fuzzy, see snapshot. It only happens sometimes. And while monitoring the BBB server, there's nothing intense going on, CPU/Mem appears to be fine.

I'm afraid to say this is our network which is behind a 500Mbps pipe - and Hangouts/Zoom run fine. Any reason why this might be?

AWS instance:
Ubuntu 16.04
Latest BBB
4 cores
8GB RAM
c5.xlarge

**Comment by ffdixon** [comment]
Are you running BigBlueButton 2.2-beta?  We've made some updates recently to (we think) resolve this issue.  Can you try

  https://test.bigbluebutton.org/

and let us know if you see the green/fuzzy video streams there.

**Comment by sydneysider** [comment]
Hi Fred,

I'm running whatever version installs from bbb-install.sh, looks like 2.0 - see attached screenshot for --version. This is now happening from various locations
![capture](https://user-images.githubusercontent.com/48125949/53924300-b45e5600-40cf-11e9-87f8-6da766069a21.PNG)

Huge bummer as I'm trying to roll this out as our main means of comms: MM/BBB.

Please advise.

**Comment by ffdixon** [comment]
> Regarding test on https://test.bigbluebutton.org/ - threw three separate macs at it, didn't detect any fuzzyness or distortion. But we just left them sitting, we weren't doing any talking or moving around.

Glad to hear that https://test.bigbluebutton.org/ isn't showing the artifacts.  We worked on fixing that issue in 2.2-beta.

> I'm running whatever version installs from bbb-install.sh, looks like 2.0 - see attached screenshot for --version. 

That's correct.   We're working on releasing BigBlueButton 2.2-beta to the community shortly.  We'll make an announcement to bigbluebutton-dev mailing list when it's ready.

> Also, why is the "swap" button missing on your test site from after clicking the "webcam" icon. That is super helpful to move presentations out of the way.

The swap is now a 'x' button in the upper right-hand corner of the presentation area.  The following animated GIF shows how it now works on 2.2-beta

![swap3](https://user-images.githubusercontent.com/290351/53930178-5b0a0e80-405e-11e9-9962-9c9b0b62e5eb.gif)

**Comment by sydneysider** [comment]
That's great news Fred! We're loving the BBB/MM integration, if this green fuzziness goes away, I think we'll be in the clear. 

May I ask when 2.2 will be released? Or if i'm able to sign on to deploy 2.2 beta? 

Thanks!

**Comment by ffdixon** [comment]
We've released BigBlueButton 2.2-beta (the timing of your question was very good :-) ).

Do try it out and give us your feedback (especially on the video).  See

  https://groups.google.com/d/msg/bigbluebutton-dev/34SphncjKEw/KJZsbQbEAQAJ

this post has steps to install BigBlueButton 2.2-beta with the script [bbb-install.sh](https://github.com/bigbluebutton/bbb-install) using the parameter `-v xenial-220-beta`.

**Comment by sydneysider** [comment]
Sweet. Just upgraded the server. Seems a hell of a lot zippier. And I love that you can X the presentation/slides out of the way when needed. One question, if I remove the default.pdf, and it's just a blue screen, how do you bring participants to the foreground? (I know with the slides on 2.2 you can click the 'x', but without, there's no swap functionality. 

Polling, YouTube, and breakout rooms seem like they could be helpful. One thing I've already noticed is that when on cam, the resolution seems heavily compressed compared to v2.0. 

*I'll let you know how production meetings go with the green/fuzziness issue.

The chat window opened by default now, is there a way to turn that turn that off?

**Comment by capilkey** [comment]
> One question, if I remove the default.pdf in /Client, and it's just a blue screen, how do you bring participants to the foreground like in v2.0? (I know with the slides on 2.2 you can click the 'x', but without, there's no swap functionality.)

That is a very good point. It would be really nice if the layout just switched seamlessly to make the webcams take up the space. I opened an issue for it #6956.

> The chat window is opened by default now, is there a way to turn that turn that off?

There's an option for opening the participants panel, but there doesn't seem to be an equivalent one for the chat. https://github.com/bigbluebutton/bigbluebutton/blob/master/bigbluebutton-html5/private/config/settings.yml#L7

> First comment from our first test users was that the user's video cam window was heavily compressed, guessing there was some modification to this to allow for better transfer?

I believe we lowered the default resolution so there would be a lower bandwidth requirement. There's a configuration option for webcam resolution if you want to try to increase it. I think the old default was double what it is now. https://github.com/bigbluebutton/bigbluebutton/blob/master/bigbluebutton-html5/private/config/settings.yml#L94-L98

**Comment by sydneysider** [comment]
Can you please let me know where the settings.yml location is in bbb 2.2? Thanks.

**Comment by ffdixon** [comment]
You can find `settings.yml` in the following directory

~~~
# locate settings.yml
/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml
~~~

**Comment by prlanzarin** [comment]
Green artifacts were a side effect of H.264 corrupt frames (either pushed by the server or filled by the decoder on borked/missing keyframes). We're using VP8 for a long time now, works rather differently. Stale.
