### ISSUE TITLE
Move document conversion progress to SVG conversion

### ISSUE THREAD

**Issue by GhaziTriki** [bigbluebutton/bigbluebutton#6918]
Currently, the document conversion progress is calculated in the PDF to SWF file conversion. It needs to be moved to the SVG document conversion because the HTML5 is becoming the default client in the coming months.

**Comment by capilkey** [comment]
Is it not possible to combine the two so progress is tied to both conversions rather than doing one and then the other format?

**Comment by GhaziTriki** [comment]
@capilkey 100% possible.

**Comment by capilkey** [comment]
I don't think we're going to want to lose one for the other, but rather extend or refactor the progress to convert each page to the required formats and update the progress as they complete. It would allow us to add in more formats as required and have it adapt naturally.

**Comment by GhaziTriki** [comment]
Partially implemented in #7639

**Comment by pedrobmarin** [comment]
Can we consider this done, @GhaziTriki ?

**Comment by prlanzarin** [comment]
Since #7639 seems to have tackled the main intent of this issue and it's stale by now, I'm closing it.

Need arises to further improve progression updates to be future proof, please open a new (and updated) issue.

Resolved by #7639
