### ISSUE TITLE
Breakout Room Duration

### ISSUE THREAD

**Issue by akiwenziec** [bigbluebutton/bigbluebutton#6919]
The breakout room duration time can be set to "nil" manually by deleting the number in the duration field.

![screen shot 2019-03-06 at 1 22 39 pm](https://user-images.githubusercontent.com/18176998/53903981-01c8bd80-4013-11e9-8428-ec27d363343c.png)

When launched the breakout room countdown continually attempts to calculate the remaining time & the breakout room never closes:

![screen shot 2019-03-06 at 1 24 31 pm](https://user-images.githubusercontent.com/18176998/53904318-c11d7400-4013-11e9-8231-bbd9fc21d0d2.png)

**Comment by antobinary** [comment]
Implemented in #6924
