### ISSUE TITLE
Breakout rooms moderator control panel does not show user count

### ISSUE THREAD

**Issue by akiwenziec** [bigbluebutton/bigbluebutton#6920]
When breakout rooms are created and launched the moderator control panel does not display a count of users per room:

![screen shot 2019-03-06 at 1 31 45 pm](https://user-images.githubusercontent.com/18176998/53905014-7dc40500-4015-11e9-8ae7-01600e79450e.png)

Users in each break out room:
![screen shot 2019-03-06 at 1 35 21 pm](https://user-images.githubusercontent.com/18176998/53905063-959b8900-4015-11e9-99ae-1f6061f33516.png)

**Comment by antobinary** [comment]
Implemented in #6924
