### ISSUE TITLE
Ejected user redirected to error 403 view

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#6928]
In the Flash client the message when a user is removed from the meeting is:
![screenshot from 2019-03-07 11-07-00](https://user-images.githubusercontent.com/6312397/53970712-49118580-40c9-11e9-9344-23182afa6495.png)

while in HTML5 client we have the generic
![screenshot from 2019-03-07 11-07-05](https://user-images.githubusercontent.com/6312397/53970727-53338400-40c9-11e9-96a5-dbe5f084fcb3.png)

Improve on the HTML5 experience so that the removed user is informed about the removal and it does not look like a client error

**Comment by capilkey** [comment]
It would be good to differentiate between ejection by a moderator, for inactivity, or for a permissions violation.
