### ISSUE TITLE
Slide controls (cont'd)

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#6944]
Follow up to #6778 
(...)
A few comments which I think can be addressed in a subsequent PR:

1) The slide switching buttons seem to be tied to the left-hand side. I imagined they would be more centered in the available area. Comments are welcome.
![screenshot from 2019-03-07 14-55-22](https://user-images.githubusercontent.com/6312397/53985329-5474a900-40e9-11e9-9ca9-9d149c07186a.png)

2) I see this error in the console when I am the presenter
![screenshot from 2019-03-07 14-54-04](https://user-images.githubusercontent.com/6312397/53985330-550d3f80-40e9-11e9-823e-4428740b0b1d.png)

3) The dropdown for slide selection does not seem to have a tooltip 

4) remove unused reference to DownloadButton

5) change case of `AreaWidth` to `areaWidth`

**Comment by antobinary** [comment]
6. on iOS (somewhat visible in Chrome iPhone simulator) the buttons for zooming in/out  are not visible

**Comment by capilkey** [comment]
I just tried out the fullscreen presentation button in Firefox and when I went fullscreen I was still shown the full screen button (expected), but clicking the button did nothing and when I clicked on the "Zoom in" button the full screen button disappeared. I then pressed Escape to leave fullscreen and there's still no fullscreen button. If I think click on one of the zoom change buttons the fullscreen button returns.

The fullscreen button should be entering a leaving and it shouldn't be disappearing.

Also, no error messages in the console while this was going on.

**Comment by capilkey** [comment]
Another interesting fallout from this is that the non-presenters have now lost the ability to go fullscreen.

**Comment by capilkey** [comment]
Looks like there's no fullscreen button for Edge at all also. @MaximKhlobystov had fixed that in a recent PR so you might want to look at what he did to get the fullscreen working in Edge.

**Comment by MaximKhlobystov** [comment]
https://github.com/bigbluebutton/bigbluebutton/pull/6778/files#diff-e529b94d29c4776e67a304f54fb541ceL43 - this part seems to be lost.

**Comment by KDSBrowne** [comment]
The zoom controls on the toolbar arn't being rendered in safari on the Ipad

**Comment by capilkey** [comment]
With desktop Safari, if you go fullscreen and then press fit-to-width the presentation leaves the screen.

**Comment by capilkey** [comment]
The controls don't reposition when the slide does. I changed the size of the chat panel and the controls drift away from where they should be.

![image](https://user-images.githubusercontent.com/1395090/53991624-05cf0b00-40f9-11e9-9f03-38c571bb2c38.png)

**Comment by jfsiebel** [comment]
When presentation is closed, the webcams get some weird grey border.
![image](https://user-images.githubusercontent.com/2110278/53992286-3e77e000-410b-11e9-904a-aca5f02f357a.png)

**Comment by jfsiebel** [comment]
When fit to width is enabled presentation toolbar doesn't follow the slide size

![image](https://user-images.githubusercontent.com/2110278/53992447-9c0c2c80-410b-11e9-975c-1ab2cde8328b.png)

**Comment by capilkey** [comment]
To add on to @jfsiebel's last comment about the toolbar size with fit-to-width. If you change the height of the browser window the width of the toolbar will grow and shrink.

**Comment by jfsiebel** [comment]
1. Make presentation fullscreen
2. Increase zoom level

![image](https://user-images.githubusercontent.com/2110278/53992623-0cb34900-410c-11e9-8e56-db43c301c697.png)

The fullscreen button disappear.

**Comment by pedrobmarin** [comment]
> When presentation is closed, the webcams get some weird grey border.
> ![image](https://user-images.githubusercontent.com/2110278/53992286-3e77e000-410b-11e9-904a-aca5f02f357a.png)

Something changed in the fullscreen button that is causing this issue

**Comment by vitormateusalmeida** [comment]
> > When presentation is closed, the webcams get some weird grey border.
> > ![image](https://user-images.githubusercontent.com/2110278/53992286-3e77e000-410b-11e9-904a-aca5f02f357a.png)
> 
> Something changed in the fullscreen button that is causing this issue

Solved.
