### ISSUE TITLE
Presenter ejected from meeting when trashing presentation after engaging poll

### ISSUE THREAD

**Issue by akiwenziec** [bigbluebutton/bigbluebutton#6945]
When a presenter attempts to remove/trash a presentation from the uploader AFTER engaging a poll they are ejected:

https://www.youtube.com/watch?v=9Ldvu5uAmfs&feature=youtu.be 

Only the presenter is affected, other viewers in the session are not ejected.

Does not occur when polling is not used prior to removing/trashing presentation from uploader

**Comment by antobinary** [comment]
Very likely related to #6710
