### ISSUE TITLE
Shared Notes Font Size

### ISSUE THREAD

**Issue by Jacoblab1** [bigbluebutton/bigbluebutton#6946]
The shared notes font size isn't affected by the HTML5 client's font size. 

If it's possible, maybe have a font size setting alongside the bold/italic/underline options inside of the shared notes?

**Comment by capilkey** [comment]
There could and probably should be a font size, but I don't know if it will be able to follow the browser font size because the text in Etherpad is supposed to be the same in all of the viewing clients.

**Comment by pedrobmarin** [comment]
@capilkey is correct. Unfortunately we can't change Etherpad's font size along with the client font size.

Change font size isn't something Etherpad provides as default but we could add some plugin for that. This one, for instance, is made for accessibility: https://www.npmjs.com/package/ep_user_font_size. It should only change the font size locally. The trouble is to install the plugin, check if works and blend it to the client's style

**Comment by capilkey** [comment]
I was afraid of that. I'm assuming the font colour and background colour will be the same situation?

**Comment by pedrobmarin** [comment]
Yes, same thing. Not impossible but just something we can't do it out of the box

**Comment by pedrobmarin** [comment]
Moved this discussion to ^.
