### ISSUE TITLE
There's no feedback to user when skip check is used with no microphone connected

### ISSUE THREAD

**Issue by capilkey** [bigbluebutton/bigbluebutton#6948]
If you try to join audio with a microphone and you don't actually have a microphone the client will display a message telling you that something went wrong getting your device.

![image](https://user-images.githubusercontent.com/1395090/53994093-3f0a7980-40ff-11e9-95b1-eb0c5b3a7824.png)

If you join the meeting with the custom parameters `userdata-autoJoin=true` and `userdata-skipCheck=true` and no microphone, no message is shown and the user is just directed back to the audio selection dialog.

The same message should be shown to the user when the extra properties are set.

There's also no messages in the console when this occurs.

**Comment by Jossef-767** [comment]
i think this issue is still not fixed.

**Comment by prlanzarin** [comment]
Flushing the assignee for the time being; marked as accepted as it's still a thing in 2.5.
