### ISSUE TITLE
Session end redirect goes to blank page - want it to go to a different landing page

### ISSUE THREAD

**Issue by sydneysider** [bigbluebutton/bigbluebutton#6951]
Since I don't have a frontend set up for BBB (ie green light) as I'm mainly integrating this with Mattermost, what do I do with the redirect link when a session has ended? 

It's two pronged. Because I want my BBB FQDN to go to some where helpful (see below for redirect), but see further below for the other issue.

Right now I have the bigbluebutton landing page (index.html) redirecting to our mattermost chat server.

Which works if I go to our bigbluebutton fqdn, which tells people "hey, log in and you can use BBB!"

But if a user clicks the "ok" button to be redirected back to the home screen after a session ends it adds my redirected mattermost fqdn plus .../plugins/bigbluebutton/redirect and of course fails with a blank page because it doesn't exist on MM.

Where does the "Ok" url source live, and can I change it to point to my mm fqdn?
<img width="563" alt="screen shot 2019-03-08 at 3 46 35 pm" src="https://user-images.githubusercontent.com/48125949/54008172-9d942e00-41b9-11e9-965d-fd60a64576e0.png">

Thanks.

**Comment by capilkey** [comment]
The default logout URL is set here, https://github.com/bigbluebutton/bigbluebutton/blob/master/bigbluebutton-web/grails-app/conf/bigbluebutton.properties#L197-L200. There's an option on the create API to set a different one though and I'm not sure if the the Mattermost integration does so. I would try setting the default and see where it gets you.

**Comment by sydneysider** [comment]
Where does this .properties file live?

**Comment by sydneysider** [comment]
Nevermind, the path got shorted in 2.2: 

/usr/share/bbb-web/WEB-INF/classes/bigluebutton.properties

**Comment by levigo-systems** [comment]
Hello, we just installed the newest version of BBB and Greenlight and got the same issue.

@sydneysider which option have to be changed?

**Comment by IulianDita** [comment]
Hey guys. I'm having the same issue. Anybody got a fix? Thanks!

**Comment by matiasilva** [comment]
Hi guys. You can either make this a default setting or do it per meeting with the create API  call: https://docs.bigbluebutton.org/dev/api.html#create. For questions on how to integrate this, please use the forums: https://groups.google.com/forum/#!forum/bigbluebutton-dev
