### ISSUE TITLE
Add a background colour to a users name on their webcam

### ISSUE THREAD

**Issue by tylercopeland** [bigbluebutton/bigbluebutton#6955]
![screen shot 2019-03-08 at 10 44 52 am](https://user-images.githubusercontent.com/1273169/54038725-395c7480-418f-11e9-8f23-3c7767cb2030.png)

Here's a rough pass that the css to use.
opacity: 0.6;
background: #000000;
border-radius: 100px;
padding:5px;

**Comment by ffdixon** [comment]
(same ping-pong table, different office :-) )
