### ISSUE TITLE
Make the webcams fullscreen when there's no current presentation in BigBlueButton 2.2-beta

### ISSUE THREAD

**Issue by capilkey** [bigbluebutton/bigbluebutton#6956]
If there's no active presentation, the button to hide the presentation area is never shown and there's no way to make the webcams take up all the available space. It would be a good enhancement to automatically make the webcams take the full space if there's no active presentation. It would make the layout more seamless and fix the issue of no swap button.

You can have no presentation if there's no default presentation or if the current presentation is removed.

**Comment by sydneysider** [comment]
Yea, I just added the blank default.pdf back to /var/www/bigbluebutton/client --> then you can 'x' out the slides to make folks full screen.

Bad news on pixel/green - thought 2.2 was goign to fix that.

**Comment by ffdixon** [comment]
> Bad news on pixel/green - thought 2.2 was goign to fix that.

Are you still seeing this issue?  Can you reproduce it on https://test.bigbluebutton.org/?

**Comment by sydneysider** [comment]
We haven't seen it yet, but it's only Monday here in Sydney - so let's see what happens today. I assume capilkey is referring to 2.2 based on the noted changes, if I'm wrong - apologies.

**Comment by ffdixon** [comment]
No worries.  And yes, we're referring to 2.2-beta (changed the title to make this explicit).
