### ISSUE TITLE
Scroll bar appears when sharing screen

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#6959]
When sharing screen on the latest build of BigBlueButton 2.2-beta, a scroll bar appears for the presenter.

![screenshare](https://user-images.githubusercontent.com/290351/54045483-bbed3000-419f-11e9-8634-68269b0254cb.gif)

**Comment by vitormateusalmeida** [comment]
Please test again. I think this was resolved in #6944 .
