### ISSUE TITLE
Propagate welcome message to breakout rooms

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#6962]
Currently, the breakout rooms do not show the welcome message, which can contain %%CONFNUM%% and other parameters.  

The impact is that if there are dial-in numbers given in the main room, they are not given in the breakout rooms, which prevents students who don't have a functioning microphone from participating in the breakout rooms.

The creation of breakout rooms needs to pass along the same welcome message received by the main room.

**Comment by ffdixon** [comment]
@GhaziTriki I believe this is fixed, no?

**Comment by GhaziTriki** [comment]
Fixed here https://github.com/bigbluebutton/bigbluebutton/pull/6989
