### ISSUE TITLE
Microphone stopped working via Flash in Firefox on Linux

### ISSUE THREAD

**Issue by mikhailnov** [bigbluebutton/bigbluebutton#6968]
I have already seen on 2 compeletely different machines in completely different networks that if:

* WebRTC error 1002 occurs
* Bigbluebutton Flash client suggests to connects audio via Flash
* sound input here does work in Chromium, but does not in Firefox (but PulseAudio/pavucontrol report that sound input is OK)

**Comment by mikhailnov** [comment]
Flash player in Firefox does not prompt a permission to use microphone, probably it's a bug in either properietary Flash plugin or Firefox

**Comment by ffdixon** [comment]
Can you try it with https://test.bigbluebutton.org/ and let us know if your getting the same issue with FF.  What OS if FF running on?

**Comment by mikhailnov** [comment]
hm, I prohibited microphone in flash settings, then enbaled it again, and it started to work

**Comment by ffdixon** [comment]
Thanks for sharing this -- let us know if it happens again.  And do try it with the HTML5 client as well (no Flash).

**Comment by ffdixon** [comment]
Closing as this was an issue related to the Flash client (the project has moved to an HTML5 client).
