### ISSUE TITLE
BigBlueButton 2.2-beta unable to convert .pptx

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#6972]
The latest build of BigBlueButton 2.2-beta is unable to convert the attached .pptx file (or any .pptx file).

When tailing `/var/log/bigbluebutton/bbb-web.log` the error given is

~~~
2019-03-10T00:03:20.527Z DEBUG o.b.w.c.PresentationController - NO SUCCESS
~~~

Tried the attached .pptx file on BigBlueButton 2.0 and it converts.

![image](https://user-images.githubusercontent.com/290351/54078888-9266fe00-429e-11e9-8723-ae181c83104c.png)

[test.pptx](https://github.com/bigbluebutton/bigbluebutton/files/2948943/test.pptx)

**Comment by GhaziTriki** [comment]
@ffdixon I just test on the latest 2.2 version and the file you shared is successfully converted.
