### ISSUE TITLE
On BigBlueButton 2.2 server enable HTML5 users to select different resolutions

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#6974]
One of the features we had on the BigBlueButton Flash client was enabling users to select different video resolutions when sharing their webcam.

Most users are fine with 320 x 240, but when capturing a lecture for recording, for example, the instructor may want to choose a higher resolution such as 640 x 480.

**Comment by AdonIrani** [comment]
+1, and if reasonably possible, 16x9 resolutions would be very helpful!

**Comment by lookas1** [comment]
I can see this feature request is pending for a long time now. Are there any plans to add support for 16x9 streams?

**Comment by iSamof** [comment]
I believe this is almost ready in HTML5 Client 2.3

See this [https://github.com/bigbluebutton/bigbluebutton/issues/5556](https://github.com/bigbluebutton/bigbluebutton/issues/5556) and perhaps search the issues in this forum for "16:9" to see all the various discussions.

I hope this helps

**Comment by kusznerr** [comment]
+1 to th8s feature. Will be very useful!

**Comment by CEOGavin** [comment]
+1

**Comment by antobinary** [comment]
We support different webcam resolutions, see the 'cameraProfiles':
https://github.com/bigbluebutton/bigbluebutton/blob/develop/bigbluebutton-html5/private/config/settings.yml#L185-L242
