### ISSUE TITLE
bbb-client postinst breaks configs

### ISSUE THREAD

**Issue by mikhailnov** [bigbluebutton/bigbluebutton#6976]
I already wrote in https://github.com/bigbluebutton/bigbluebutton/issues/6280 that old method of detecting IPs does not detect it on my server. postinstall script of `bbb-client` breaks configs `/etc/bigbluebutton/nginx/sip.nginx` and `/etc/nginx/sites-enabled/bigbluebutton` , because host/IP are just empty after running that script. That script uses the problematic old method of detecting IP.

Please see the log bellow.

Also, the script must make sure that host/IP are not empty and have valid values before making changes to working configs.

I have already asked you to publish debian packaging on Github, but unfortunately I can't contribute a fix because scripts and packaging specs are not published.

```
user@bbb1-nspawn:/var/lib/dpkg$ sudo bash -x ./info/bbb-client.postinst
+ LANG=c
+ ifconfig
+ grep -q venet0:0
++ head -n1
++ sed 's/ //g'
+++ awk -v RS= '{gsub (/\n[ ]*inet /," ")}1'
+++ LANG=c
+++ ifconfig
+++ grep '^wl.*'
+++ grep addr:
+++ head -n1
+++ sed 's/.*addr://g'
+++ sed 's/ .*//g'
+++ LANG=c
+++ ifconfig
+++ awk -v RS= '{gsub (/\n[ ]*inet /," ")}1'
+++ grep '^bo.*'
+++ grep addr:
+++ head -n1
+++ sed 's/.*addr://g'
+++ sed 's/ .*//g'
+++ LANG=c
+++ ifconfig
+++ awk -v RS= '{gsub (/\n[ ]*inet /," ")}1'
+++ grep '^em.*'
+++ grep addr:
+++ head -n1
+++ sed 's/.*addr://g'
+++ sed 's/ .*//g'
+++ LANG=c
+++ ifconfig
+++ awk -v RS= '{gsub (/\n[ ]*inet /," ")}1'
+++ grep '^p.p.*'
+++ grep addr:
+++ head -n1
+++ sed 's/.*addr://g'
+++ sed 's/ .*//g'
+++ LANG=c
+++ ifconfig
+++ awk -v RS= '{gsub (/\n[ ]*inet /," ")}1'
+++ grep addr:
+++ grep '^et.*'
+++ head -n1
+++ sed 's/.*addr://g'
+++ sed 's/ .*//g'
+++ LANG=c
+++ ifconfig
+++ awk -v RS= '{gsub (/\n[ ]*inet /," ")}1'
+++ grep '^en.*'
+++ grep addr:
+++ head -n1
+++ sed 's/.*addr://g'
+++ sed 's/ .*//g'
++ echo '                 '
+ IP=
+ '[' -z '' ']'
+ '[' -f /etc/redhat-release ']'
+ '[' -f /var/lib/tomcat7/webapps/bigbluebutton/WEB-INF/classes/bigbluebutton.properties ']'
++ cat /var/lib/tomcat7/webapps/bigbluebutton/WEB-INF/classes/bigbluebutton.properties
++ sed -n '/^bigbluebutton.web.serverURL/{s/.*\///;p}'
+ SERVER_URL=webinar.dumalogiya.ru
+ '[' '!' -L /etc/nginx/sites-enabled/bigbluebutton ']'
+ '[' -f /tmp/config.xml ']'
+ sed -i 's/host="conf\/join-mock.xml"/host="http[s]*:\/\/\/bigbluebutton\/conference-session\/enter"/g' /var/www/bigbluebutton/client/conf/config.xml
+ sed -i s/HOST//g /var/www/bigbluebutton/client/conf/config.xml
+ sed -i 's/<module[ ]*name="DeskShareModule"\(.*\)\/>/<!-- module name="DeskShareModule"\1\/-->/g' /var/www/bigbluebutton/client/conf/config.xml
+ sed -i 's/\tloadNextModule="DeskShareModule"/\tloadNextModule="PhoneModule"/' /var/www/bigbluebutton/client/conf/config.xml
+ sed -i 's/proxy_pass .*/proxy_pass http:\/\/:5066;/g' /etc/bigbluebutton/nginx/sip.nginx
+ sed -i 's/\r//g' /var/www/bigbluebutton/client/conf/config.xml
+ '[' -f /etc/nginx/sites-available/bigbluebutton ']'
+ '[' -f /tmp/nginx-bigbluebutton ']'
+ sed -i 's/server_name  .*/server_name  ;/g' /etc/nginx/sites-available/bigbluebutton
+ '[' '!' -L /etc/bigbluebutton/nginx/client.nginx ']'
+ '[' '!' -L /etc/bigbluebutton/nginx/web.nginx ']'
+ reloadService nginx
+ app_name=nginx
+ hash systemctl
+ '[' '!' -f /.dockerenv ']'
+ [[ ! nginx =~ ^.*\.[a-z]*$ ]]
+ app_name=nginx.service
+ echo 'Reloading nginx.service using systemd'
Reloading nginx.service using systemd
+ systemctl status nginx.service
+ systemctl reload-or-restart nginx.service
Job for nginx.service failed because the control process exited with error code. See "systemctl status nginx.service" and "journalctl -xe" for details.
user@bbb1-nspawn:/var/lib/dpkg$ 
```

**Comment by mikhailnov** [comment]
```user@bbb1-nspawn:/var/lib/dpkg$ hostname -I | sed 's/ .*//g'
185.125.231.233```

**Comment by ffdixon** [comment]
What version are you installing?  We changed how we are determining the IP address in BigBlueButton 2.2-beta to use the following:

~~~
if LANG=c ifconfig | grep -q 'venet0:0'; then
  # IP detection for OpenVZ environment
  IP=$(ifconfig | grep -v '127.0.0.1' | grep -E "[0-9]*\.[0-9]*\.[0-9]*\.[0-9]*" | tail -1 | cut -d: -f2 | awk '{ print $1}')
else
  IP=$(hostname -I | sed 's/ .*//g')
fi
~~~

To try out BigBlueButton 2.2-beta, see https://groups.google.com/d/msg/bigbluebutton-dev/34SphncjKEw/KJZsbQbEAQAJ

**Comment by mikhailnov** [comment]
Yes, I've just understood myself that I did not upgrade to 2.2. Sorry.

$ dpkg -l | grep bbb | awk '{print $2, $3}'
bbb-apps 1:2.0.0-52
bbb-apps-akka 2.0.0-155
bbb-apps-screenshare 1:2.0.0-41
bbb-apps-sip 1:2.0.0-15
bbb-apps-video 1:2.0.0-29
bbb-apps-video-broadcast 1:2.0.0-8
bbb-client 1:2.0.0-405
bbb-config 1:2.0.0-88
bbb-freeswitch-core 2:2.0.0-50
bbb-freeswitch-sounds 1:1.6.7-9
bbb-fsesl-akka 2.0.0-27
bbb-mkclean 1:0.8.7-4
bbb-playback-presentation 1:2.0.0-31
bbb-record-core 1:2.0.0-35
bbb-red5 1:1.0.8-40
bbb-swftools 1:0.9.2-2
bbb-transcode-akka 2.0.0-6
bbb-web 1:2.0.0-95
bigbluebutton 1:2.0.0-13

**Comment by ffdixon** [comment]
No worries -- let us know if you run into any issues with 2.2-beta.  It's under very active development and we want to make this our best release yet.

**Comment by mikhailnov** [comment]
Yes, it works correctly in v2.2, thank you.

**Comment by jelmd** [comment]
The bbb-client 1:2.0.0-407 postinstall script is still broken. On all our Ubuntu machines we have NIC names neither starting with `et` nor with `en` - they follow ${nodename}${NIC_IDX} convention. Since the fallback ` hostname -I | sed 's/ .*//g'` gets used for RH based distros, **IP** remains empty and thus makes `/etc/bigbluebutton/nginx/sip.nginx` unusable. And because bbb-client tries to restart the nginx service, configuration of the package fails (as well as the dozen packages depending on it).

So looking for eth* or en* via deprecated `ifconfig` is a very bad idea. IMHO  something like this is much better:
```
A=( $( ip -o -4 addr show scope global up ) )
IP=${A[3]%/*}
```
