### ISSUE TITLE
Guest users aren't directed to the client requested in their initial join API call

### ISSUE THREAD

**Issue by capilkey** [bigbluebutton/bigbluebutton#6986]
Steps to reproduce:
1. Set the guest policy to ASK_MODERATOR in bigbluebutton.properties
2. Join a meeting as a moderator (Flash or HTML5)
3. In a different tab join as a viewer with "joinViaHtml5=true"
4. In the moderator tab allow the guest to join

Expected result:
Once allowed, the guest user should be redirected to the HTML5 client.

Actual result:
The guest user is directed to the Flash client (default client).

**Comment by antobinary** [comment]
@ritzalam implemented in 2.2 (can't find the PR)
