### ISSUE TITLE
Colour name tooltip does not hide

### ISSUE THREAD

**Issue by GhaziTriki** [bigbluebutton/bigbluebutton#6990]
The tooltip that contains the name of the colour does not disappear after selecting it.

![image](https://user-images.githubusercontent.com/4991088/54161041-4b6d3a00-4451-11e9-82d5-535839fcfa15.png)

**Comment by antobinary** [comment]
Hi @GhaziTriki,
What browser did you use for this session? I have seen this once or twice but have not been able to reproduce it consistently (to address it)

**Comment by GhaziTriki** [comment]
@antobinary => Firefox 65.0.2 (64 bits),  Windows 10

**Comment by GhaziTriki** [comment]
This issue only happens on Firefox.

**Comment by prlanzarin** [comment]
Can't reproduce as of 2.3-beta.3.

(thanks for testing @schrd).
