### ISSUE TITLE
The pan and zoom is very laggy (and inaccurate) in the HTML5 client

### ISSUE THREAD

**Issue by capilkey** [bigbluebutton/bigbluebutton#6991]
When you're the presenter and pan around a slide, the display and the movement is very laggy compared the same motions in the Flash client. I think the issue is that the HTML5 client is waiting for the slide movement to come back from the server before showing a change. Waiting for the message to come back results in the calculations for the mouse change to be incorrect because it's always behind.

In the Flash client the presenter ignores any slide position updates from the server and makes all of the display changes locally and then sends the new position to the server for everyone else to get.

**Comment by ffdixon** [comment]
The sync looks better in the latest release after the updates to the fit-to-width.

![pan](https://user-images.githubusercontent.com/290351/54867134-3c409300-4d53-11e9-847b-9680a4df9db9.gif)

**Comment by antobinary** [comment]
Addressed in #7837
