### ISSUE TITLE
Hi， Flash video cannot be viewed on HTML 5 client ，How to solve this problem

### ISSUE THREAD

**Issue by caojincool** [bigbluebutton/bigbluebutton#6993]

**Comment by ffdixon** [comment]
Both Flash and HTML5 use different protocols.  Flash uses RTMP and HTML5 uses WebRTC.  The Flash users can't see the HTML5 webcams, see

 http://docs.bigbluebutton.org/html/html5-overview.html#features-for-the-first-release'

Recommend you check out BigBlueButton 2.2-beta which the HTML5 client implements (almost) all of the Flash capabilities.  You can run sessions using on the HTML5 client and all uses can see webcams.

   https://groups.google.com/d/msg/bigbluebutton-dev/34SphncjKEw/KJZsbQbEAQAJ

**Comment by caojincool** [comment]
I know ,  Thanks
