### ISSUE TITLE
The "X" to close the presentation isn't shown in Edge or Safari

### ISSUE THREAD

**Issue by capilkey** [bigbluebutton/bigbluebutton#7003]
The blue "X" isn't being shown to Safari or Edge users so they can't close the presentation area.

Original report from here, https://groups.google.com/forum/#!topic/bigbluebutton-dev/tJRln1k6TG8. Confirmed it's happening on master.

**Comment by KDSBrowne** [comment]
I was not able to reproduce this on my server or dev22. Can someone confirm that this is still an issue?

**Comment by capilkey** [comment]
I can't reproduce anymore either.
