### ISSUE TITLE
Unsync zoom in Flash client

### ISSUE THREAD

**Issue by pedrobmarin** [bigbluebutton/bigbluebutton#7004]
Not sure if this is something new:
 - apply zoom;
 - change presenter;
 - change slide;

![zoom](https://user-images.githubusercontent.com/1778398/54237598-14506480-44f5-11e9-90a8-5a1350cae771.gif)

**Comment by capilkey** [comment]
The presenter switch isn't actually required to reproduce. It's also reproduceable in 2.0. 

The presenter's zoom level should probably be set to default or the last value for the page on page change and an position update sent to the clients to sync them up.

**Comment by ffdixon** [comment]
Closing as this was an issue related to the Flash client (the project has moved to an HTML5 client).
