### ISSUE TITLE
Presentation is clipping the whiteboard tools on mobile.

### ISSUE THREAD

**Issue by Tainan404** [bigbluebutton/bigbluebutton#7013]
Presentation
![image](https://user-images.githubusercontent.com/15806883/54298024-c724cf00-4596-11e9-8fe5-3b1fd2cd2d94.png)

**Comment by JustinMogel** [comment]
Tested this on mobile with Brave Browser (Chromium 89) and the tools bar is displayed correctly
BBB version 2.3-alpha-8 (1511)

**Comment by antobinary** [comment]
Thanks @JustinMogel for this and the other retests!
