### ISSUE TITLE
Webcam wrapped within fullscreen button component

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#7017]
Referenced in https://github.com/bigbluebutton/bigbluebutton/issues/6944#issuecomment-472561630
![Screenshot from 2019-03-13 15-29-28](https://user-images.githubusercontent.com/6312397/54308708-f2161f80-45a4-11e9-9bee-4c486fee4f61.png)

**Comment by vitormateusalmeida** [comment]
This problem was solved on #6944
