### ISSUE TITLE
Shared YouTube videos do not appear in recordings

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#7018]
In BigBlueButton 2.2-beta we allow the presenter to share a YouTube video; however, we don't included any segments of shared YouTube videos in the recordings.

We need to either warn the presenter that their shared YouTube video will not appear in the recordings or figure out a way to incorporate the videos into recordings.

Another option is to put into the playback links in the chat to view the segments of the YouTube recording when watching the playback.

**Comment by kepstin** [comment]
What's the current state of the recording events? Is any event stored in events.xml to indicate when the youtube sharing starts/stops?

**Comment by kepstin** [comment]
There are currently no events being recorded to the events.xml file for youtube video share start/stop/resync - these need to be added.

**Comment by lfzawacki** [comment]
I sent a simple PR to get this issue started https://github.com/bigbluebutton/bigbluebutton/pull/7484

Now the share, un-share, play start, play stop, and status update events are shared via Redis messages. Is this enough to create the events.xml server side and include the videos on the recordings?

**Comment by ffdixon** [comment]
Until we can include the recording in the playback, is there enough information placed in the events to add a URL for the shared YouTube video?  

This way, someone watching the recording later on could click the link to see the YouTube video the instructor shared in the chat.

**Comment by antobinary** [comment]
Resolved by https://github.com/bigbluebutton/bigbluebutton/pull/12739 and https://github.com/bigbluebutton/bigbluebutton/pull/12612 in 2.4
