### ISSUE TITLE
[2.2-beta][HTML5]: user can't on mic after moderator off

### ISSUE THREAD

**Issue by vova-zush** [bigbluebutton/bigbluebutton#7024]
The user can not turn on the microphone after the moderator has clicked the microphone off button for the given user. The microphone restriction is on in the settings, but the user in whom this problem is unlocked. If you turn off the microphone lock, then everything is fine. Also the microphone is turned on for the first time

**Comment by capilkey** [comment]
Just fixed this yesterday in, https://github.com/bigbluebutton/bigbluebutton/pull/7014. The fix should be included in the next update.
