### ISSUE TITLE
Move/Edit Whiteboard Objects

### ISSUE THREAD

**Issue by poetslipvis** [bigbluebutton/bigbluebutton#7036]
The current whiteboard interface is quite limited. To me it seems crucial to be able to edit the whiteboard objects (resize objects/edit text) after being placed on the whiteboard. Now they are stuck there until you delete them. It would be nice to be able to edit/delete them separately instead of going one by one/delete everything altogether without warning nor redo.

**Comment by capilkey** [comment]
We haven't forgotten about #2351. It's something I've wanted to do for awhile and I tried when I last refactored the whiteboard, but there are blocking issues with implementation and the details are tricky. I would expect it to be done at some point, but for now there are higher priority things to work on.

**Comment by prakas24** [comment]
Any update on this requirement?

**Comment by ffdixon** [comment]
Not at this time, we're currently working on finish BigBlueButton 2.2.  For information on how we prioritize features, see http://docs.bigbluebutton.org/support/faq.html#when-will-feature-x-be-implemented.

**Comment by nordby** [comment]
> Not at this time, we're currently working on finish BigBlueButton 2.2. For information on how we prioritize features, see http://docs.bigbluebutton.org/support/faq.html#when-will-feature-x-be-implemented.

maybe now something has changed?

**Comment by ffdixon** [comment]
We're just finishing up BigBlueButton 2.2 and planning the work for 2.3.  We've not decided whether this feature is in place for 2.3 yet (or in a future update).  

We'll update this issue when we have more information.

**Comment by ianme** [comment]
For the moment I use https://openboard.org and share my screen (more bandwidth, no collaboration on the board) but it would be nice to have something similar in BBB!

**Comment by ProfMarte** [comment]
+1! Having the code of openboard to use in BBB would be best of all.
At least a function like the rubber in paint is truely neccessary to work with the whiteboard. 
moving objects or at least mark areas and move them would be great, too.
Clipboard copy & paste would be useful, too.

**Comment by mehdikazemi3120** [comment]
+1 for this
