### ISSUE TITLE
Html5 new realease - can i mute all and disable all cams except the admin and one attendee

### ISSUE THREAD

**Issue by Coinizy1** [bigbluebutton/bigbluebutton#7037]
hi, 
i want to mute all users except the admin and disbale all cams except one presenter
so basically i want to show me and my friends cam and mic to all other attendees is is possible?
thanks

**Comment by capilkey** [comment]
You can do this through the meeting mute and the lock settings in 2.2. The options are in the gear icon in the Participants Panel. The lock settings will apply to all viewers in the meeting and you can selectively unlock certain people if you want them to be able to talk or share their webcam.

**Comment by Coinizy1** [comment]
Hi thankyou for replaying
Talk or webcam?
Talk and webcam?

**Comment by capilkey** [comment]
You can lock 5 different things in the HTML5 client. 

![image](https://user-images.githubusercontent.com/1395090/54453978-cfb00d80-472e-11e9-8211-f8b34a5151a8.png)

![image](https://user-images.githubusercontent.com/1395090/54453931-b6a75c80-472e-11e9-8c79-0cd1dff7e65f.png)
