### ISSUE TITLE
WebRTC screenshare in Flash client no longer works after SFU security changes

### ISSUE THREAD

**Issue by kepstin** [bigbluebutton/bigbluebutton#7038]
The Flash client when starting WebRTC screenshare attempts to connect to `wss://bbb.example.com/bbb-webrtc-sfu` with no sessionToken, and the connection gets rejected with a 401 error. As a result, screenshare fails to start.

This is a regression caused  by #6732

**Comment by prlanzarin** [comment]
Are we talking about 2.0 or 2.2?

**Comment by kepstin** [comment]
Issue only appears in 2.2 - the change that caused the issue is new functionality in 2.2.

**Comment by pedrobmarin** [comment]
Is this happening in dev22?

**Comment by kepstin** [comment]
I just checked - this *is* working on dev22 (sessionToken is sent on the websocket connection)
This is not working on a server that I just upgraded from 2.0 to 2.2 via the "xenial-220" repo (the sessionToken is not sent on the websocket connection)

**Comment by pedrobmarin** [comment]
Maybe cache?

**Comment by kepstin** [comment]
Yeah, turns out to have been cache. Clearing cache helped.
We need to add cache-busting to whichever file causes this issue.

**Comment by pedrobmarin** [comment]
https://github.com/bigbluebutton/bigbluebutton/blob/master/bigbluebutton-client/resources/prod/lib/kurento-extension.js

**Comment by kepstin** [comment]
In the `BigBlueButton.html` file, all the JS files need to have the `?v=VERSION` added to the end of the URL.
