### ISSUE TITLE
Remove references to screenshare "extension" [on Chrome version <73]

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#7039]
![Screenshot from 2019-03-15 11-26-04](https://user-images.githubusercontent.com/6312397/54444039-54dbf800-4718-11e9-8ae7-b6386de90b76.png)

**Comment by capilkey** [comment]
Shouldn't this be "Remove references to the extension for Chrome > 72"?

**Comment by ffdixon** [comment]
Closing as this was an issue related to the Flash client (the project has moved to an HTML5 client).
