### ISSUE TITLE
Make it easier to see when a user is not in the voice conference

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#7053]
In the HTML5 client, displays a small microphone or speaker icon to indicate the user is in the voice bridge.  

![image](https://user-images.githubusercontent.com/290351/54483012-f3548000-4822-11e9-8531-320cea6d29a1.png)

It would be much easier to distinguish a user not in a session by making that area empty instead of solid.

![image](https://user-images.githubusercontent.com/290351/54483006-d8820b80-4822-11e9-937c-d06e14b0dd69.png)

The empty space causes the viewer to think _something is missing with this user's icon_.

The empty space and absence of any icon makes it much easier to tell a user isn't in the audio bridge and can't hear the instructor.

**Comment by antobinary** [comment]
I like to think we can find better UI for this one. @tylercopeland

**Comment by tylercopeland** [comment]
@ffdixon, is this request based on feedback that we’ve received from users of the HTML5 client? 

I’ve explored the concept above through design and it has been discussed heavily as a team. We decided to not go on that direction because it looks more like there is an issue with a client versus actually indicating to the user audio status. 

If this is an issue we are hearing from our users, another option is to take what we are doing in the flash client and mirroring it to the html5 client. Not my preferred approach, but it’s something that is already working for BigBlueButton.

**Comment by ffdixon** [comment]
We could break out the webcam and microphone into their own column, such as in the Flash client, but I would like to try and minimize changes at this point.

The challenge is making it very easy for an instructor to tell that the user is not in the conference bridge.  I was recently in a session where the instructor asked the student "Can you hear me?", and, of course, because the student wasn't in the voice bridge, they couldn't.

The challenge here is to make it really clear to the instructor that the student is not in the voice bridge. 

Are we drawing their avatar using SVG?

**Comment by jfsiebel** [comment]
Gustavo reactivated the webcam icon in his PR #6992, maybe do something for microphone too.
![image](https://user-images.githubusercontent.com/2110278/54536949-6fa8a980-4970-11e9-9ede-8b2636efa273.png)

**Comment by prlanzarin** [comment]
This being closed means the bite out of the avatar will be the definitive solution???

**Comment by ffdixon** [comment]
We're looking for the best near-term solution to avoid scenarios where users don't realize that another person isn't in the audio bridge and are trying to talk with them.

We want to make it *really* clear when a user is in the audio bridge, and the current solution without the "bite" makes it hard to see this when there are 10+ users in the conference bridge with different colored and shaped avatar icons.

**Comment by atar3d** [comment]
![X](https://user-images.githubusercontent.com/2356928/54876335-edf4c800-4e16-11e9-8923-be01f4b48589.png)

Maybe a red X can be noticeable enough

**Comment by ffdixon** [comment]
Thanks for the suggestion; however, a red X would suggest something is wrong with the user's login, whereas we're looking for UI that suggests something is mission or not yet complete.  

You can try out this latest UI change on 

  https://test.bigbluebutton.org/

Feedback welcome!

**Comment by atar3d** [comment]
how about the "bite" with outline ... ? 
![X](https://user-images.githubusercontent.com/2356928/54879321-28268f80-4e40-11e9-8994-867cb1545674.png)

**Comment by lausfranca** [comment]
Hi!

Feedback: for me it seems that when you turn off the audio and there is a hole it looks like a bug.

We could just use the same communication used with the microphone (which the user is already used to) and do something like this:

What do you think?

![Screenshot_61](https://user-images.githubusercontent.com/48809435/54960726-a23c3e80-4f3c-11e9-909d-24ebbcebace3.png)


______

Another (more neutral form) would be this:

**Comment by ffdixon** [comment]
The challenge is for accessibility you can't covey state information with color only.  

You can try out latest build with the visible/absent icon for being in the conference bridge on

  https://test.bigblueubtton.org/

**Comment by capilkey** [comment]
A different icon for not being in the audio might just get lost in the sea of other icons (specifically the muted icon).

![image](https://user-images.githubusercontent.com/1395090/55032497-5db9ad00-4fe7-11e9-9ee8-83e0e199509e.png)

If there were 50-100 people in a meeting and you wanted to see if any of them was not connected to audio, you would need to carefully inspect each icon. In the Flash client where there's a column specifically for each icon, it was much easier to immediately recognize that something was missing. I'm not really a fan of the bite (I'd rather a column), but it's very easy to recognize when scrolling through a large user list.
