### ISSUE TITLE
Correct language in Shared Notes

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#7054]
Currently, the BigBlueButton client labels the export button as Import/Export

![image](https://user-images.githubusercontent.com/290351/54483331-b3dc6280-4827-11e9-9d87-79e858f6947b.png)

Change the label to "Export" and the icon to a download icon (same shade as other icons)

![image](https://user-images.githubusercontent.com/290351/54483326-a8893700-4827-11e9-9530-464a5e3f2bc5.png)

**Comment by pedrobmarin** [comment]
https://github.com/bigbluebutton/etherpad-lite/commit/b842cb8270a7136dc16116cc3524361f109eb177
