### ISSUE TITLE
Webcam sharing locked by moderator

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#7056]
When a moderator locks the webcams for viewers, the tooltip currently says 

![image](https://user-images.githubusercontent.com/290351/54483712-60b9de00-482e-11e9-94cc-0f698ef04784.png)

where it should say "Webcam sharing locked"

**Comment by antobinary** [comment]
I think we need different strings for
- locked
- no camera on device

**Comment by BobakOftadeh** [comment]
I believe changing the string to "Webcam sharing locked" is enough as we already notify the user that no webcams are found in the video previewer. This also shows the the webcams are not in a disabled state and issue comes from the fact that no webcam devices are not found.
