### ISSUE TITLE
Change "Close presentation" to "Hide presentation"

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#7060]
Currently, the language to hide the presentation area reads "Close presentation"

![image](https://user-images.githubusercontent.com/290351/54494533-a7045100-48b1-11e9-999f-c4177b7a0ca0.png)

A more accurate label would "Hide presentation", and the corresponding "Restore presentation" make more sense.

Also, the icon should be a minimize icon (not a close icon).

![image](https://user-images.githubusercontent.com/290351/54494602-7b359b00-48b2-11e9-8067-42cb837e5bdc.png)

**Comment by Beeez** [comment]
Any reason i dont have this option in my current version of HTML5? Client Build shows 484 under About.

**Comment by antobinary** [comment]
@Beeez You are on BigBlueButton 2.0's version of HTML5 client (build 484)

this screenshot was taken from BigBlueButton 2.2-beta version of HTML5 client (build ~320+). See test.bigbluebutton.org for the 2.2-beta version (keep in mind it's under development still, hence the -beta)

**Comment by Beeez** [comment]
> @Beeez You are on BigBlueButton 2.0's version of HTML5 client (build 484)
> 
> this screenshot was taken from BigBlueButton 2.2-beta version of HTML5 client (build ~320+). See test.bigbluebutton.org for the 2.2-beta version (keep in mind it's under development still, hence the -beta)

Makes sense. Thank you! I would assume that the beta is not stable enough for production? I just recently joined in on the Big Blue Button community so i am trying to understand the entire roadmap of when stable releases are made and such.

**Comment by ffdixon** [comment]
We have a development process that processed from beta, to release candidate, to final release, see

  http://docs.bigbluebutton.org/support/faq.html#bigbluebutton-development-process

Right now we're finishing the remaining functionality in BigBlueButton 2.2-beta and hardening the release. you can see the open issues under development here
 
  https://github.com/bigbluebutton/bigbluebutton/projects/2

If you like what you see in BigBlueButton 2.2-beta, we encourage you to try out this build and give us your feedback.  See

  https://groups.google.com/d/msg/bigbluebutton-dev/34SphncjKEw/KJZsbQbEAQAJ

**Comment by tylercopeland** [comment]
@antobinary within the BigBlueButton icon library, we have an icon "icon-bbb-minus". We can use that for the "minimize presentation" experience. Refer to the image below. 

![Screen Shot 2019-04-05 at 11 48 57 AM](https://user-images.githubusercontent.com/1273169/55640088-e8916900-5798-11e9-8876-fb73f189b171.png)

**Comment by diegobenetti** [comment]
Following @tylercopeland 's suggestion, this is how it looks:

![minus-icon-option](https://user-images.githubusercontent.com/7821065/55742280-ac167500-5a05-11e9-8ca7-f8b958dc7a93.png)

**Comment by konfib** [comment]
Hello,
now there is no label anymore to "Close presentation" to "Hide presentation"?
I see only three dots now, with full screen and download option.

`BigBlueButton Server 2.5.11 (3193)

ii  bbb-apps-akka                        2.5-44                            all          BigBlueButton Apps (Akka)
ii  bbb-config                           1:2.5-67                          amd64        BigBlueButton configuration utilities
ii  bbb-etherpad                         1:2.5-11                          amd64        The EtherPad Lite components for BigBlueButton
ii  bbb-freeswitch-core                  2:2.5-15                          amd64        BigBlueButton build of FreeSWITCH
ii  bbb-freeswitch-sounds                1:2.5-8                           amd64        FreeSWITCH Sounds
ii  bbb-fsesl-akka                       2.5-34                            all          BigBlueButton FS-ESL (Akka)
ii  bbb-html5                            1:2.5-2894                        amd64        The HTML5 components for BigBlueButton
ii  bbb-learning-dashboard               1:2.5-23                          amd64        BigBlueButton bbb-learning-dashboard
ii  bbb-libreoffice-docker               1:2.5-9                           amd64        BigBlueButton setup for LibreOffice running in docker
ii  bbb-mkclean                          1:2.5-5                           amd64        Clean and optimize Matroska and WebM files
ii  bbb-pads                             1:2.5-14                          amd64        BigBlueButton Pads
ii  bbb-playback                         1:2.5-9                           amd64        BigBlueButton playback
ii  bbb-playback-presentation            1:2.5-11                          amd64        BigBluebutton playback of presentation
ii  bbb-record-core                      1:2.5-30                          amd64        BigBlueButton record and playback
ii  bbb-web                              1:2.5-63                          amd64        BigBlueButton API
ii  bbb-webrtc-sfu                       1:2.5-31                          amd64        BigBlueButton WebRTC SFU
ii  bigbluebutton                        1:2.5-2                           amd64        Open source web conferencing platform (bbb)
ii  libopusenc0                          0.2.1-1bbb1                       amd64        High-level API for encoding Ogg Opus audio streams
ii  yq                                   3.4.1bbb1                         amd64        lightweight and portable command-line YAML processor`
