### ISSUE TITLE
Revisit flag to swap [hide presentation area]

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#7065]
When passing custom parameter [via API MATE]
`userdata-autoSwapLayout=true`

The code for swapping was changed significantly. Adapt the flag to trigger hiding of presentation on 'true'.

**Comment by antobinary** [comment]
Removing the 'Omit button to display it again if no presentation.' since it is requested in https://github.com/bigbluebutton/bigbluebutton/issues/6956

**Comment by Coinizy1** [comment]
if i make this line to true will the webcams will be bigger and shows instead of presentation? because i really want that feature can i do it manually?
thanks

**Comment by antobinary** [comment]
After some local testing - yes, actually this seems to still work fine despite the code changes

```
userdata-autoSwapLayout=true
joinViaHtml5=true
```

Note that the keyword might change slightly, this work is still in progress

**Comment by Coinizy1** [comment]
Can you tell me where can i find these two lines so i can make the webcam default instead of presentation?
```
userdata-autoSwapLayout=true
joinViaHtml5=true
```

**Comment by Coinizy1** [comment]
@antobinary i can't find it on config.xml and bigbluebutton.properties

**Comment by antobinary** [comment]
@Coinizy1 these parameters are passed when joining - see this link for example

`https://demo.bigbluebutton.org/bigbluebutton/api/join?fullName=User+5887192&joinViaHtml5=true&meetingID=random-2047364&password=mp&redirect=true&userdata-autoSwapLayout=true&checksum=ec883d7c11637240aa1901994f461b12ad940c4d`

**Comment by Coinizy1** [comment]
Thanks for replying fast, 
Actually, i am using Wordpress Plugin and custom server 
i changed attendeesjoinviahtml5=true in bigbluebutton.properties.
how can i change it for wordpress :( i really want to disable presentation and only want to show cams instead of presentation.
thanks

**Comment by Coinizy1** [comment]
Can i pass this parameter via bbb wordpress plugin?

**Comment by antobinary** [comment]
I am not sure how (I have not used the wordpress plugin). I tried to look through the code https://github.com/blindsidenetworks/wordpress-plugin_bigbluebutton/blob/master/includes/bbb_api.php but am not spotting it.
I did find a similar question on https://groups.google.com/forum/#!searchin/bigbluebutton-dev/wordpress%7Csort:date/bigbluebutton-dev/uFOmdUlwA_8/Nve0nkL8AgAJ but without solution
My advice would be to either research more and/or try to edit the code yourself.

Alternatively - post on the  https://groups.google.com/forum/#!forum/bigbluebutton-dev mailing list and take it from there.

_______
That said, we have an issue in development https://github.com/bigbluebutton/bigbluebutton/issues/6956 which should check whether there is a presentation and make the flip automatically. Once that is merged and released, your only concern would be to not have presentation in the meeting

**Comment by Coinizy1** [comment]
Hi, Can you tell me one last thing? how can i edit this file
![image](https://user-images.githubusercontent.com/31903098/54559931-fc8c4b00-49e2-11e9-9baf-d7f24b2a2722.png)
If i click on the close presentation button (close button on top right of presn.) i can achieve what i want.
I tried putting the param in the url but nothing happens.
I just want to edit the layout and i want to close the presentation when anyone joins :(
thanks

**Comment by capilkey** [comment]
The `userdata-autoSwapLayout=true` property needs to be added in the function that constructs the join URL. It would be put on this line, https://github.com/blindsidenetworks/wordpress-plugin_bigbluebutton/blob/master/includes/bbb_api.php#L102. Line 102 would be something like, 
```
$params = 'meetingID='.urlencode($meetingid).'&fullName='.urlencode($username).'&password='.urlencode($password).'&userdata-autoSwapLayout=true';
```

**Comment by Coinizy1** [comment]
@capilkey so if i change this line in wordpress plugin and once i join again and dont have presentation it will show the video web cam right?
thanks

**Comment by capilkey** [comment]
I haven't tested it myself, but it should. It's a simple enough change.

**Comment by Coinizy1** [comment]
@capilkey ThankYOU SIR :) I was looking for this solution for 3 days thank you everyone :) i am very very happy for your help.
One last think can i edit the "Raise question" and show it anywhere else on the attendee screen?
like in the chat?
Thanks

**Comment by capilkey** [comment]
Are you referring to the display of the results of the poll? Currently the final result is only displayed as an annotation on the whiteboard, but we have an issue open to create an alternate view for the cases where the presentation isn't visible. https://github.com/bigbluebutton/bigbluebutton/issues/7058

**Comment by Coinizy1** [comment]
No actually i want to edit the frontend html5 layout
For example what i want is that:
I want to put a button (Raise Hand) just aside of webcsm button and mic
button. When user click that button his hand should be raised just like we
press ctrl shit and r

**Comment by ffdixon** [comment]
> No actually i want to edit the frontend html5 layout

@Coinizy1 are you a developer?  Have you tried to setup a development environment for the HTML5 client?

**Comment by Coinizy1** [comment]
Actually i am a csharp developer lol
I just wanna know which file i have to change for html5 fornt end?
And how can i install developer environment? I want to separate the raise
button in front end html5

**Comment by capilkey** [comment]
There's probably too many changes required to list them all out. The best way to learn would be to investigate the current action buttons and how they're created and styled and then investigate how the status menus work and how they send data to the HTML5 server and replicate that in a new button.

Most of the action bar (big buttons at the bottom) code can be found here, https://github.com/bigbluebutton/bigbluebutton/tree/master/bigbluebutton-html5/imports/ui/components/actions-bar.

The menu to set the status from the user list can be found in this class https://github.com/bigbluebutton/bigbluebutton/blob/master/bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-list-item/user-dropdown/component.jsx. Look for code related to "emoji" for the relevant parts.

Also, development questions are much better served on the developer mailing list, https://groups.google.com/forum/#!topic/bigbluebutton-dev, because these questions aren't issues with the product.

**Comment by shashwatadi** [comment]
@Jazzykhan have you done the raise hand change for your project?

**Comment by Jazzykhan** [comment]
No
