### ISSUE TITLE
Clean 2.2-beta install audio not working with floating IP on Digital Ocean

### ISSUE THREAD

**Issue by GhaziTriki** [bigbluebutton/bigbluebutton#7068]
I created a new clean droplet in DigitalOcean using 2.2-beta, however I was not able  to connect to audio. After a quick search I found that I need to update my FreeSwitch configuration. I edited the file `/opt/freeswitch/etc/freeswitch/sip_profiles/external.xml`

I updated the lines
```xml
    <param name="ext-rtp-ip" value="$${external_rtp_ip}"/>
    <param name="ext-sip-ip" value="$${external_sip_ip}"/>
```

To match the following values that I copied from some development servers.

```xml
    <param name="ext-rtp-ip" value="$${local_ip_v4}"/>
    <param name="ext-sip-ip" value="$${local_ip_v4}"/>
```

I have a floating IP address assigned to this instance. Should the configuration I updated be used as default for the packaging?

**Comment by ffdixon** [comment]
Hmm ... the default values in package are

~~~xml
    <param name="ext-rtp-ip" value="$${local_ip_v4}"/>
    <param name="ext-sip-ip" value="$${local_ip_v4}"/>
~~~

Did you install using step-by-step instructions or `bbb-install.sh`?

**Comment by GhaziTriki** [comment]
I installed the server using the `bbb-install.sh`, I used the following command `wget -qO- https://ubuntu.bigbluebutton.org/bbb-install.sh | sudo bash -s -- -v xenial-220-beta -s subdomain.domain.com -e admin@domain.com -t`

**Comment by ffdixon** [comment]
In testing on Digital Ocean you were using a Floating IP address.  I didn't test for that case (I just use the default IP addresses given by Digital Ocean).

It looks like the the Floating IP address is causing a logic error in `bbb-install.sh` where it thinks the server is behind NAT.  Will do some more testing with this setup to get `bbb-install.sh` to work correctly out-of-the-box.

**Comment by ranahosur** [comment]
I faced this same issue when I installed 2.2 on digitalocean with floating IP using bbb-install.sh. Thanks to this post, after making the changes mentioned above, I was able to make it work.

Thanks
Raghu

**Comment by prlanzarin** [comment]
If that's still an issue it should be moved to bbb-install.

I've seen deploys fully working under DO's floating IP scheme, so I'm closing this.
