### ISSUE TITLE
Document with too many pages upload problem in HTML5

### ISSUE THREAD

**Issue by jfsiebel** [bigbluebutton/bigbluebutton#7071]
![upload-presentation](https://user-images.githubusercontent.com/2110278/54626086-401c9e80-4a4f-11e9-9b21-851e8ebcf710.gif)

**Comment by capilkey** [comment]
Should probably make sure that it handles the 30MB limit also.

**Comment by antobinary** [comment]
.. And the 200 pages limit (or whatever value is in bigbluebutton.properties). But the main thing here is to propagate the info (and not block)
