### ISSUE TITLE
Obsolete old bbb-client

### ISSUE THREAD

**Issue by mikhailnov** [bigbluebutton/bigbluebutton#7076]
From docs:
```
If you are updating your server from BigBlueButton 2.0 (or earlier version), you need to first remove the bbb-client package.

$ sudo apt-get purge -y bbb-client
This is because some files owned by bbb-client have moved to be owned by bbb-web. Deleting the bbb-client package before the upgrade to BigBlueButton 2.2-beta will allow bbb-web to create these files without conflict from the older version of bbb-client.
```
Before executing `sudo apt purge bbb-client`, I think, it would be nice to run `sudo bbb-conf --stop`, but I did not think of it and lost `/usr/bin/bbb-conf`.

I think purging `bbb-client` will not be necessary, if you add to 'Breaks' filed to `debian/control`  of both bbb-client and bbb-web v2.2, see https://wiki.debian.org/PackageTransition#Package_Transition

**Comment by ffdixon** [comment]
Hi @mikhailnov,

We've updated the docs to have the administrator run `bbb-conf --stop`

  http://docs.bigbluebutton.org/2.2/install.html#2-install-apt-get-key-for-bigbluebutton-repository

We'll check out the docs on 'Breaks'.
