### ISSUE TITLE
SSL config in nginx was lost on upgrading from 2.0 to 2.2

### ISSUE THREAD

**Issue by mikhailnov** [bigbluebutton/bigbluebutton#7077]
After upgrading from 2.0 to 2.2, SSL configuration in `/etc/nginx/sites-available/bigbluebutton` was lost. I just made a diff of old and new config thanks to btrfs snapshot and repaired it, but It was not obvious from upgrade instructions.

**Comment by ffdixon** [comment]
Thanks for pointing this out.  We've made an explicit step to have server admins backup any custom changes they made (outside of `bbb-conf`) _before_ they upgrade BigBlueButton's packages.

  http://docs.bigbluebutton.org/2.2/install.html#3--backup-custom-configurations
