### ISSUE TITLE
Timezones mismath in logs

### ISSUE THREAD

**Issue by mikhailnov** [bigbluebutton/bigbluebutton#7079]
Logs of different components of BBB use different timezones, some use local time and some use UTC.

E. g. `/var/logs/bigbluebutton/bbb-web.log` is in local time, but `/var/log/bbb-webrtc-sfu/bbb-webrtc-sfu.log*` is in UTC.

Timezone on my server is UTC+0300, and  `/var/log/bbb-webrtc-sfu/bbb-webrtc-sfu.log*`  has date in filename, so even dates mismatch.

It is not a serious issue.

BBB v2.2

**Comment by ffdixon** [comment]
Thanks @mikhailnov  -- good catch.  We'll keep this issue open until we unify the timestamps in the logs.
