### ISSUE TITLE
Drag and dropping a presentation for upload shows red

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#7087]
In the latest build of BigBlueButton 2.2-beta, tried dragging a .pptx file over the drag-and-drop area and it showed red.

![red](https://user-images.githubusercontent.com/290351/54784007-261ebf80-4bf9-11e9-8de1-7042abc84f92.gif)

**Comment by capilkey** [comment]
Looks like there's a couple of issues with the drag-and-drop functionality.
1. File type detection doesn't work at all in Chrome. It's always red.
2. The allowed MIME types don't include PPT and PPTX files and dropping one of those results in a rejection

The MIME types need to be the same as the ones in the file select dialog. A similar issue was found and reported here, https://github.com/bigbluebutton/bigbluebutton/issues/6792.
