### ISSUE TITLE
demo3.jsp fails to load when server is configured to use HTML5 client

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#7091]
On BigBlueButton 2.2-beta, when the server is [configured to load the HTML5 client](http://docs.bigbluebutton.org/2.2/customize.html#make-the-html5-client-default), the built-in demo3.jsp fails to load the HTML5 client.

Reported in bigbluebutton-setup

  https://groups.google.com/d/msg/bigbluebutton-setup/fXZrI6Y28hA/LAga2keFAgAJ

**Comment by jpmirandaa** [comment]
The issue is that it is not possible to share the desktop or using the webcam with moderator profile getting 'error 1020 webcam has not reached the server' on HTML5 client 329 version.

**Comment by jpmirandaa** [comment]
The same issues with recent 341 HTML5 client version.

**Comment by prlanzarin** [comment]
My guess is that this is not related to the demo page whatsoever. This smells like connectivity problems (most probably, ie firewall) or WebRTC API/codec incompability issues.

Gonna need more info to make sense of what's going on @jpmirandaa, ie:
* Browser (+ version)
* OS (+ version)
* Console log
* Screen share: whole screen, application, tab?
* A dump of the webrtc debugger from the browser you're having problems with (Google Chrome: `chrome://webrtc-internals`, Firefox: `about:webrtc`). Feel free to redact your IP addresses from the dumps.

**Comment by jpmirandaa** [comment]
Hi, Paulo.

Thank you for response.

As I explained in this thread (https://groups.google.com/forum/#!msg/bigbluebutton-setup/fXZrI6Y28hA/LAga2keFAgAJ) **the issues happen only using the html5 client and only through the demo3.jsp file**.
All other demoX.jsp and create.jsp files connect well and are perfectly able to using the webcam and screen sharing.

The flash client works well in all cases as well including the demo3.jsp file.
So, the only case these issues happen is using the html5 client through demo3.jsp file.
This happens on the server https://test.bigbluebutton.org as well as on an own local server and two other own external servers without firewalls or proxies.

I verified these issues with two different internet providers with the same result.
Else, the tests were done using three different browsers: Firefox 66.0.1, Chrome 73.0.3683.86 and Opera 58.0.3135.118, on two different operating systems: Linux Mint 19 (x86_64; MATE) and Windows 10.

I hope that this information could be used to identify and correct the error that, in my opinion, could be in the file demo3.jsp or in some of its auxiliary files, for example, the bbb_api.jsp file or some other.

![Captura de pantalla -2019-03-28 00-05-42](https://user-images.githubusercontent.com/16512393/55118299-271a8a00-50ee-11e9-88b0-0c53defa9513.png)
![Captura de pantalla -2019-03-28 00-05-59](https://user-images.githubusercontent.com/16512393/55118300-27b32080-50ee-11e9-8485-0d2b3eff5ceb.png)
![Captura de pantalla -2019-03-28 00-06-29](https://user-images.githubusercontent.com/16512393/55118301-27b32080-50ee-11e9-9598-68ce4d4c6f2c.png)

Kind regards
JP

**Comment by ffdixon** [comment]
Unable to reproduce on 2.3.
