### ISSUE TITLE
Pressing ENTER key on empty chat causes exception

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#7097]
Open the latest build of BigBlueButton 2.2-beta and press the enter key a few times.  There is an exception thrown for each press.

![exception](https://user-images.githubusercontent.com/290351/54867021-27173480-4d52-11e9-9ee7-1572374c44d5.gif)

**Comment by capilkey** [comment]
I can't reproduce this.

**Comment by jfsiebel** [comment]
This `onloadwff.js` seems to be related to LastPass plugin for Chrome. (https://forums.lastpass.com/viewtopic.php?f=12&t=274205)

**Comment by capilkey** [comment]
Good catch. There might be some way for us to work around this or not trigger LastPass.

**Comment by antobinary** [comment]
Moving to post 2.2 since this is an edge case, depends on extensions installed

**Comment by antobinary** [comment]
> This `onloadwff.js` seems to be related to LastPass plugin for Chrome. (https://forums.lastpass.com/viewtopic.php?f=12&t=274205)
