### ISSUE TITLE
Add the userId into user actions to new_slides.xml

### ISSUE THREAD

**Issue by GhaziTriki** [bigbluebutton/bigbluebutton#7102]
Some custom implementation of the recording playback player needs the `userId` into user actions. How easy is it to add the `userId` to those actions if it is provided by when calling the join API.

Something like this

```xml
<popcorn>
  <chattimeline in="274" direction="down" name="Ghazi" message="Hi" target="chat"/>
  <chattimeline in="280" direction="down" name="Fred" message="Hello" target="chat"/>
  <chattimeline in="282" direction="down" name="Ghazi" message="OK" target="chat"/>
</popcorn>
```

Needs to become

```xml
<popcorn>
  <chattimeline in="274" direction="down" name="Ghazi" userId="5323" message="Hi" target="chat"/>
  <chattimeline in="280" direction="down" name="Fred" userId="9630" message="Hello" target="chat"/>
  <chattimeline in="282" direction="down" name="Ghazi" userId="5323" message="OK" target="chat"/>
</popcorn>
```

**Comment by YanenkoNazar** [comment]
Hey guys. It very important task. Can you please try to change it as soon as possible?
Thanks a lot!

**Comment by pedrobmarin** [comment]
What's the use case of this modification?

**Comment by YanenkoNazar** [comment]
we need to know which comment is connected to userID. So we can open users profile by clicking on the name in the chat

**Comment by capilkey** [comment]
I guess this would be the externalUserId and not the internalUserId. The only thing included with the chat messaging by default is the internalUserId so in order to attach the externalUserId there would need to be a list of users and their information and then the recording processing for the chat messages would have to lookup the extra information.

**Comment by YanenkoNazar** [comment]
Do you want to include to bbb real users id from our side to externalUserId?

**Comment by pedrobmarin** [comment]
That's the purpose of externalUserId. How could you get your user profile from BigBlueButton's internalUserId?

**Comment by YanenkoNazar** [comment]
We can not use internalId, so we need externalId be the same as users id on our side. Actualy we are sending you users id in custom parameter "userId", where user join to classroom, but we are not receiving it back as externalId.

**Comment by GhaziTriki** [comment]
@YanenkoNazar you can match the `externalId` with the `internalId` by using `redirect=false` in `join` API. Store the internal ID you get then use a redirect function in server side.

You will have a response with this format

```xml
<response>
<returncode>SUCCESS</returncode>
<messageKey>successfullyJoined</messageKey>
<message>You have joined successfully.</message>
<meeting_id>
03628f03ad51ba5728c5c35bdd3bd2c574ac1724-1554302182658
</meeting_id>
<user_id>w_6v3visasjirt</user_id>
<auth_token>p8p8yjaqufi2</auth_token>
<session_token>tbdpki0ni7n55xw7</session_token>
<guestStatus>ALLOW</guestStatus>
<url>
https://demo.bigbluebutton.org/client/BigBlueButton.html?sessionToken=tbdpki0ni7n55xw7
</url>
</response>
```

or
```xml
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<response>
<returncode>SUCCESS</returncode>
<messageKey>successfullyJoined</messageKey>
<message>You have joined successfully.</message>
<meeting_id>
03628f03ad51ba5728c5c35bdd3bd2c574ac1724-1554302182658
</meeting_id>
<user_id>w_pfcqou0sunzw</user_id>
<auth_token>r5izbjj6qmed</auth_token>
<session_token>k4perfc4pjuch1ux</session_token>
<guestStatus>ALLOW</guestStatus>
<url>
https://demo.bigbluebutton.org/html5client/join?sessionToken=k4perfc4pjuch1ux
</url>
</response>
```

**Comment by kepstin** [comment]
All of the information required to do this is already present in the events.xml file. You'll have to read all the `ParticipantJoinEvent` from events.xml, and use those to make a mapping of `userId` → `externalUserId`.

Since you're doing a custom recording format anyways, you can add the userid to the 
chat xml yourself - just run the `senderId` from the chat even through the user id mapping to get the external id.

No changes are needed in any BBB upstream components for this.

**Comment by YanenkoNazar** [comment]
When user joined you receive from us user name (like Nazar) and user id (like 456). That is data from our side.

In XML files we can see this user name, but this real user id is lost. Because we receive "w_89wbwvpavgl5", not "456".

How can we get real user id?

**Comment by GhaziTriki** [comment]
When using `redirect=false` in `join` API, you need to store `user_id` value with your own user id on your side.

**Comment by GhaziTriki** [comment]
This issue is a duplicate of https://github.com/bigbluebutton/bigbluebutton/issues/2115

**Comment by GhaziTriki** [comment]
The solution is mapping of `userId` → `externalUserId`
