### ISSUE TITLE
getMeetingInfo not returning correct role after promotion/demotion

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#7109]
In the latest BigBlueButton 2.2-build, if a user is demoted from moderator to viewer, the `getMeetingInfo` API call still returns their role as `MODERATOR`

For example, after demoting user `A` to viewer, here's what the return result looks like
~~~xml
      <attendees>
        <attendee>
          <userID>w_6nkywgrf7wyn</userID>
          <fullName>A</fullName>
          <role>MODERATOR</role>
~~~

In the above, it should have returned `<role>VIEWER</role>`.

Interestingly, `getMeetingInfo` does properly update the `<moderatorCount>`  when a user is made moderator (or has moderator privileges removed).

**Comment by pedrobmarin** [comment]
Hi @ffdixon . Could not reproduce it at my 2.2-dev environment. Is it possible to be missing some instruction on the steps to reproduce you described?

**Comment by ffdixon** [comment]
Hmm ... your right.  I tested this on https://test.bigbluebutton.org/ and it appears to work.  I'll test again on the server where I saw the issue and see if it still has the same problem after upgrade.
