### ISSUE TITLE
Demote/Promote a viewer isn't affecting Start recording

### ISSUE THREAD

**Issue by jfsiebel** [bigbluebutton/bigbluebutton#7115]
When demoting or promoting an user in the user list it is not propagated directly to the start recording button. I had to make another action, in my case clear the chat.

![moderator-demote-propagation](https://user-images.githubusercontent.com/2110278/55073095-a024cd80-506b-11e9-87f1-dc2b80aa2015.gif)

**Comment by ffdixon** [comment]
Good catch!
