### ISSUE TITLE
i want some custom html5 styling on my server, can i hire someone?

### ISSUE THREAD

**Issue by Coinizy1** [bigbluebutton/bigbluebutton#7134]
I tried on all websites like freelancers.com, odesk, codementor.io but couldnt fine anyone to change few things on my server for html5 please help.
thanks

**Comment by chetan-learniphi** [comment]
Hello sir, 

Greetings of the day!
Hope you are doing well!

We have expertise team who are working on BigBlueButton Server, HTML5 Client, API, etc. and we can do all kind of customization. Can you please share more detail about what customization you wanted to have in HTML5 Client. 

Please share your detail on hello@learniphi.com
Skype Id: chetan.parekh12

Thanks, 
Chetan Parekh
Learniphi Technology Pvt. Ltd.

**Comment by antobinary** [comment]
https://groups.google.com/forum/#!forum/bigbluebutton-dev - is a better place to ask this question
