### ISSUE TITLE
Dail-in user does not have mute/unmute state for microphone

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#7136]
When users joins via a dial-in number, the display of their avatar shows they are not in the audio (it has the bite in it).

![image](https://user-images.githubusercontent.com/290351/55241705-064b5500-5212-11e9-96e6-16dadc4bbaef.png)

Need to update them to show their muted/unmuted state.

**Comment by capilkey** [comment]
This is also reproduceable by having a moderator join audio only in a breakout room. It will only happen the first time they join though. 

![image](https://user-images.githubusercontent.com/1395090/55350382-f9d13180-5489-11e9-85ea-b3c895a3fb1e.png)

If you don't see a button to join the breakout room audio, make sure you are in the main room's audio channel.
