### ISSUE TITLE
HTML5 client disappears in iPad when we click on the webcam button while using chrome

### ISSUE THREAD

**Issue by GhaziTriki** [bigbluebutton/bigbluebutton#7137]
On mobile iOS device, if we use chrome and click on the webcam button, the screen becomes blue instead of showing the initial prompt.

**Comment by prlanzarin** [comment]
Since iOS/mobile only supports WebRTC on Safari, my guess is that we're doing a `getUserMedia` call on `video-preview` or something along the `mediaDevices` scope in there without checking its availability and that, probably, isn't being properly enveloped in an error handler.

**Comment by capilkey** [comment]
The audio modal has a special case for Chrome on iOS and the same check needs to be done in video and maybe screenshare.

**Comment by prlanzarin** [comment]
Yeah. It'd be better to devise an utilitary to check for the `mediaDevices` scope or gUM availability tho, if possible, instead of checking the user agent. By checking the behaviour instead of UAs we could catch a lot more odd browsers without WebRTC at once and get the code a little less if-fy.

**Comment by capilkey** [comment]
I agree. In the Flash client we had a utility function for "Is WebRTC Available" and all of the places that used WebRTC would check there first. That approach worked very well and was easy to update as changes had to be made for what we support.
