### ISSUE TITLE
Improve text area background color

### ISSUE THREAD

**Issue by jfsiebel** [bigbluebutton/bigbluebutton#7139]
When the white color is selected for the text tool, it's not possible to see what is being write in the box.

It's possible to do a workaround by changing the text to another color and at the end changing to white.

**Comment by capilkey** [comment]
Why wouldn't there just be a special case to switch the background to black when the text is white?

**Comment by Worti2** [comment]
There must have been no special case. Just leave the box/tool transparent.
Kind Regards
Worti from the Joomla! Project
