### ISSUE TITLE
Interaction with stun.freeswitch.org

### ISSUE THREAD

**Issue by mikhailnov** [bigbluebutton/bigbluebutton#7141]
I have setup a coturn server based on http://docs.bigbluebutton.org/2.2/setup-turn-server.html on a seperate FreeBSD server.

BBB config `/usr/share/bbb-web/WEB-INF/classes/spring/turn-stun-servers.xml` is:

```
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.springframework.org/schema/beans
            http://www.springframework.org/schema/beans/spring-beans-2.5.xsd
            ">

    <bean id="stun1" class="org.bigbluebutton.web.services.turn.StunServer">
        <constructor-arg index="0" value="stun:turn.dumalogiya.ru"/>
    </bean>

    <bean id="turn1" class="org.bigbluebutton.web.services.turn.TurnServer">
        <constructor-arg index="0" value="<secret>"/>
        <constructor-arg index="1" value="turns:turn.dumalogiya.ru:443"/>
        <constructor-arg index="2" value="86400"/>
    </bean>

    <bean id="stunTurnService" class="org.bigbluebutton.web.services.turn.StunTurnService">
        <property name="stunServers">
            <set>
                <ref bean="stun1" />
                <!--ref bean="stun2" /-->
            </set>
        </property>
        <property name="turnServers">
            <set>
                <ref bean="turn1">
                <!--ref bean="turn2" /-->
            </set>
        </property>
        <property name="remoteIceCandidates">
            <set>
                <!--ref bean="iceCandidate1" /-->
                <!--ref bean="iceCandidate2" /-->
            </set>
        </property>
    </bean>
</beans>
```
Of course, `<secret>` is the same as in `/usr/local/etc/turnserver.conf` on coturn server.

The problem is that I saw interation with stun.freeswitch.org before this and still see them.
I attach a traffic dump from WireShark. There, `185.125.231.234` is my BigBlueButton server, 
`77.72.169.210` is `stun.freeswitch.org`, `46.101.1.118` is my coturn server.

I see not encrypted communcation with public FreeSwitch stun servers and TLSv1.2 encrypted communcations with my turn server.

I changed `stun:stun.freeswitch.org` to `stun:turn.dumalogiya.ru:443`, `stun:turn.dumalogiya.ru`, stuns:turn.dumalogiya.ru` in `/opt/freeswitch/etc/freeswitch/vars.xml`, but nothing changed, probably those default values are overriden by values in `/usr/share/bbb-web/WEB-INF/classes/spring/turn-stun-servers.xml`. And I'm not sure that coturn configuration is suitable.

So, I want to understand, why it connects to external servers (stun.freeswitch.org) and does my turn server really work correctly.

[sip1.pcapng.zip](https://github.com/bigbluebutton/bigbluebutton/files/3026002/sip1.pcapng.zip)

**Comment by mikhailnov** [comment]
I've grepped freeswitch source code and did not find hard-coded `stun.freeswitch.org`
![DeepinScreenshot_выберите-область_20190331011510](https://user-images.githubusercontent.com/15802528/55282307-6fd27d00-5352-11e9-97e0-39540aba8200.png)

**Comment by mikhailnov** [comment]
From browser console log:
```
sip.js?v=448:2900 Sun Mar 31 2019 23:16:21 GMT+0300 (Москва, стандартное время) | sip.ua | · stunServers: ["stun:`"]
sip.js?v=448:2900 Sun Mar 31 2019 23:16:21 GMT+0300 (Москва, стандартное время) | sip.ua | · turnServers: []
```

No turn server is defined. `stun.freeswitch.org` is defined. But there is no `stun.freeswitch.org` is `/opt/freeswitch/etc/freeswitch/vars.xml`. Where is it taken from?

**Comment by capilkey** [comment]
Did you restart bbb-web after making changes to turn-stun-servers.xml? You can either restart just the bbb-web service or everything.

The network tab in the browser will have the the returned result. It'll be a request to "stuns".

Also, the values under /opt/freeswitch have no bearing on the client.

**Comment by mikhailnov** [comment]
Of course I did (`bbb-conf --restart`)

**Comment by capilkey** [comment]
What's the raw response in the browser to the request to "stuns"?

The default is:
![image](https://user-images.githubusercontent.com/1395090/55351437-5cc3c800-548c-11e9-8454-c8e40dec6480.png)
So I'm curious what yours shows.

**Comment by mikhailnov** [comment]
It is `stun.freeswitch.org`

![image](https://user-images.githubusercontent.com/15802528/55375669-ba502700-5515-11e9-8a16-f97f0f37eb0f.png)

**Comment by capilkey** [comment]
I'm not really sure why it isn't working. The code definitely works and the file can definitely be changed. You can use API Mate (http://mconf.github.io/api-mate/) to create and join a meeting and you'll see that the stuns response includes a modified result.

The only things I can think of are editing the wrong file, not restarting bbb-web, or editing on the wrong server.

**Comment by prlanzarin** [comment]
Closing (stale, and the bbb-web config definitely works).
