### ISSUE TITLE
mcs-balancer

### ISSUE THREAD

**Issue by shqlzx** [bigbluebutton/bigbluebutton#7144]
["Kurento","Freeswitch"]
{"level":"info","message":"[app] MCS Server is initializing ...","timestamp":"2019-03-31T02:53:53.059Z"}
{"level":"info","message":"[app] MCS Server is ready to receive connections","timestamp":"2019-03-31T02:53:53.159Z"}
{"level":"info","message":"[sfu-mcs-api] Connecting to MCS at ws://localhost:3010/mcs","timestamp":"2019-03-31T02:53:54.082Z"}
{"level":"info","message":"[sfu-mcs-api] Connecting to MCS at ws://localhost:3010/mcs","timestamp":"2019-03-31T02:53:54.162Z"}
{"level":"info","message":"[sfu-mcs-api] Connected to MCS","timestamp":"2019-03-31T02:53:54.186Z"}
{"level":"info","message":"[sfu-mcs-api] Connected to MCS","timestamp":"2019-03-31T02:53:54.273Z"}
{"level":"info","message":"[sfu-mcs-api] Connecting to MCS at ws://localhost:3010/mcs","timestamp":"2019-03-31T02:53:54.348Z"}
{"level":"info","message":"[sfu-mcs-api] Connected to MCS","timestamp":"2019-03-31T02:53:54.405Z"}
{"url":"ws://xxx.xxx.xxx:8888/kurento","ip":"1xx.16x.2x.1x","level":"error","message":"[mcs-balancer] Failed to connect to candidate host","timestamp":"2019-03-31T02:53:54.767Z"}
who can tell me what,s wrong?

**Comment by shqlzx** [comment]
Mar 31 13:45:55 unbuntu1604 bbb-webrtc-sfu[8233]: 2019-03-31T05:45:55.990Z - #033[31merror#033[39m: [mcs-balancer] Failed to connect to candidate host url=ws://bbb.nono.tech:8888/kurento, ip=1xx.16x.2x.1x
Mar 31 13:45:55 unbuntu1604 bbb-webrtc-sfu[8233]: 2019-03-31T05:45:55.993Z - #033[32minfo#033[39m: [mcs-balancer] Available hosts =>
------------------------------------------------------------------------------------------------
/usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml (Kurento SFU)
                        kurento.ip: 1xx.16x.2x.1x
                       kurento.url: ws://bbb.nono.tech:8888/kurento
                    localIpAddress: 192.168.1.16
               recordScreenSharing: true
                     recordWebcams: true
                  codec_video_main: H264
               codec_video_content: H264

**Comment by shqlzx** [comment]
/usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml (Kurento SFU)
                        kurento.ip: 1xx.16x.2x.1x
                       kurento.url: ws://xxx.xxx.xxx:8888/kurento
                    localIpAddress: 192.168.1.16
               recordScreenSharing: true
                     recordWebcams: true
                  codec_video_main: H264
               codec_video_content: H264
---------------------------------------------------------------------------------------------------
Mar 31 13:45:55 unbuntu1604 bbb-webrtc-sfu[8233]: 2019-03-31T05:45:55.814Z - #033[32minfo#033[39m: [sfu-mcs-api] Connected to MCS
Mar 31 13:45:55 unbuntu1604 bbb-webrtc-sfu[8233]: reconnect to server 4 500 undefined
Mar 31 13:45:55 unbuntu1604 bbb-webrtc-sfu[8233]: 2019-03-31T05:45:55.990Z - #033[31merror#033[39m: [mcs-balancer] Failed to connect to candidate host url=ws://xxx.xxx.xxx:8888/kurento, ip=1xx.16x.2x.1x

**Comment by ffdixon** [comment]
@shqlzx Can you provide steps to reproduce this error?

**Comment by amtojsingh** [comment]
I'm struck at the same.
Did you managed to resolve the same?

**Comment by prlanzarin** [comment]
@amtojsingh This issue is very old. Whatever caused that issue might as well been fixed for now. Are you running a modified version or the stock packages?
Would you care to post the output of `sudo bbb-conf --check`?

**Comment by shqlzx** [comment]
not yet


 
---Original---
