### ISSUE TITLE
Recording session, trouble with playback recording

### ISSUE THREAD

**Issue by lfortiz** [bigbluebutton/bigbluebutton#7145]
Hi, my name is Luis Ortiz and my email is lfortiz@unizar.es. I'm and administrator of a Moodle 3.5.5 sytem.  Well, I have the next trouble:

I worked like a moderator role in a VC sessión with the plugin of Moodle. I recorded my activity using the tools of the conference Room for recording a session.   This recording have audio and video.

When the server finished the sound podcast (and published) I can reproduce it, when the server finished the video file (and published) I can reproduce it.  But, when the server built the presentation (and published), I can't see it, and I can't listen the podcast o see the video.  By the way, I did a click over the Presentation link or the others links (audio and video), I saw the next dialog box:

![Screenshot-2019-4-1VCBBB](https://user-images.githubusercontent.com/47659830/55321970-42cdb980-547b-11e9-9e78-91bfd5946ed0.png)

More information about the plugin and server.
Server version 2.0.0-RC11
Plugin BBB version 2.2.10

Can you help me?
Thanks for all

**Comment by dahalday** [comment]
Good Day Team

Congrats on all the good work on this project.

I don't exactly have the same issue and I am not sure if they are related. 

I have installed "apt-get install bbb-playback-screenshare" on a BigBlueButton Server 2.2.0-beta3 (844)

The podcast and presentation were generated but the screenshare view was not. Kindly advise.

Kind Regard
DH

**Comment by ffdixon** [comment]
Hi @dahalday, thanks for pointing this out.  We'll take a closer look to make sure bbb-playback-screenshare works BigBlueButton 2.2-beta (to date, most of our testing has been with the default bbb-playback-presentation).

**Comment by dahalday** [comment]
Thank you also.

On Apr 1, 2019 10:37 PM, Fred Dixon <notifications@github.com> wrote:

Hi @dahalday<https://github.com/dahalday>, thanks for pointing this out. We'll take a closer look to make sure bbb-playback-screenshare works BigBlueButton 2.2-beta (to date, most of our testing has been with the default bbb-playback-presentation).

**Comment by lfortiz** [comment]
Hi, I'm Luis again.  Now we have installed version 2.0 of the BBB server, with the extension of moodle version 2.2.11 and still have the same error :-( A friendly reminder

Iĺl try the version 2.2-beta, I'll comment on my observations

Best Regards

**Comment by lfortiz** [comment]
Well, I have to say then I have installed sever version 2.2.-beta, the server don have the problem wich I wrote in april 1... Thanks for all!
