### ISSUE TITLE
Sort private chats list by last activity

### ISSUE THREAD

**Issue by jfsiebel** [bigbluebutton/bigbluebutton#7146]
![private-chats](https://user-images.githubusercontent.com/2110278/55349280-ae218680-548f-11e9-9ef7-0de13a269388.gif)

In the example bbb7 chat was hidden in scroll and the user didn't received a clear "clue" that someone was talking with him.

**Comment by Jossef-767** [comment]
The main conclusion following recent heavy use of html5 interface, it seems that the interface problem mentioned above becomes more and more annoying and causes serious communication problems between lecturer and students.
The lecturer is not aware that private messages are sent to him.

**Comment by Jossef-767** [comment]
Is there any chance this will be addressed in the approaching build ?
