### ISSUE TITLE
Problem with message too short warning

### ISSUE THREAD

**Issue by jfsiebel** [bigbluebutton/bigbluebutton#7147]
![message-too-short](https://user-images.githubusercontent.com/2110278/55351685-57b74680-5495-11e9-8fb8-1b2a129eda71.gif)

Steps to reproduce:

1. Start writing something
2. Delete the message
3. Hit Enter

The message only disappear when you send a message

**Comment by prlanzarin** [comment]
Can't reproduce anymore.
