### ISSUE TITLE
[2.2beta3][HTML5] Menu does not size correctly to text length

### ISSUE THREAD

**Issue by aogilvie** [bigbluebutton/bigbluebutton#7149]
Text is expected to be on the same line.

![example](https://user-images.githubusercontent.com/970364/55372072-5c363a80-553b-11e9-841b-92bf00f3762c.png)

**Comment by GhaziTriki** [comment]
Displaying as expected in 2.2.x

![image](https://user-images.githubusercontent.com/4991088/100640460-7e531200-3347-11eb-95ee-9bfeaa4c6c1a.png)

**Comment by aogilvie** [comment]
Thanks for following up.
