### ISSUE TITLE
talk statistics: who talked most? (in % of time)

### ISSUE THREAD

**Issue by Paradiesgestalter** [bigbluebutton/bigbluebutton#7153]
We use BBB for video conferences und would need a kind of statistics indicating who are the main speakers in a meeting, who talked most... Since BBB already indicates who's audio channel is broadcasting, it would require a kind of counter to sum up the seconds of broadcasting and divide them by duration of meeting. Feature request: talk statistics in %, preferably live during session and after session finished. Thanks!!

**Comment by GhaziTriki** [comment]
@Paradiesgestalter It can be possible if you use https://github.com/bigbluebutton/bbb-events
