### ISSUE TITLE
[2.2beta3][HTML5] Cannot display default presentation file

### ISSUE THREAD

**Issue by aogilvie** [bigbluebutton/bigbluebutton#7163]
- using the latest master commit.
- HTML5 client server log shows:
```
I20190404-04:47:02.576(0)? error: Error parsing image size. ProbeError: bad status code: 404. uri=https://detailing.entouch.jp/bigbluebutton/presentation/247998260ba93c7573ad9cb308d475383704a7b1-1554353212603/247998260ba93c7573ad9cb308d475383704a7b1-1554353212603/979ad05e497eccf762d24d0a8be5ba8d7ef2f577-1554353212745/svg/1
```

`.properties` file is set to URL of PDF (attached)

![example](https://user-images.githubusercontent.com/970364/55530340-b45a7180-56e0-11e9-8905-d36dea145b62.png)

[wallpaper.pdf](https://github.com/bigbluebutton/bigbluebutton/files/3041805/wallpaper.pdf)

**Comment by antobinary** [comment]
Hi @aogilvie 
I just tried to upload wallpaper.pdf into a running meeting and it converted/uploaded fine. Some more info would help to be able to reproduce what you see:
1) What exact changes did you make on the server to change the default presentation file?
For example in bigbluebutton.properties 
you changed
`beans.presentationService.defaultUploadedPresentation=${bigbluebutton.web.serverURL}/default.pdf`
to
`beans.presentationService.defaultUploadedPresentation=${bigbluebutton.web.serverURL}/wallpaper.pdf` ?
Or you uploaded the file somewhere else `https://some.other.server.com/wallpaper.pdf` ? (not sure if that works)
Did you copy wallpaper.pdf to `/var/www/bigbluebutton-default/`? With what ownership and permissions?

**Comment by aogilvie** [comment]
Closing. I think is outdated.

**Comment by ZockerBoysHD** [comment]
> Closing. I think is outdated.

still not working on latest bbb-docker version
