### ISSUE TITLE
[2.2beta3][HTML5] Receiving webcam fails in Safari

### ISSUE THREAD

**Issue by aogilvie** [bigbluebutton/bigbluebutton#7164]
- tested on test.bigbluebutton.org
- desktop safari versions tested 11.1.2, 12.0.1, 12.0.3 all fail.
- grey box appears, arrows are visible but do not spin, video never shows.
- sending video from Safari appears in Chrome fine.

video being shared from 
73.0.3683.86 (Official Build) (64-bit) (cohort: Stable)
Windows 10 Enterprise

**Comment by prlanzarin** [comment]
Is this an intermittent issue or you're able to reproduce it realibly? Also, what's the network your Safari was on (cable, WiFi, NAT...)?

**Comment by aogilvie** [comment]
Desktop safari, tested with regular home WiFi and tested as hotspot to iPhone on 4Gcellular network.

MacBook Pro and MacBook Air. Can get you model number is necessary.

Location is Japan so expected maybe some lag but like I wrote safari -> Chrome no issues .

In safari, if we set develop > webrtc > enable deprecated webrtc APIs, cams work without issues.

**Comment by prlanzarin** [comment]
2.2 should be compatible with the normal API for Safari >= 12.x :thinking:. You confirm it works on 12.x with legacy API enabled or are you talking about 11.x?
I'll try to have a look at this nonetheless and see if I can reproduce.

**Comment by aogilvie** [comment]
I have just done a mass device re-testing on test.bigbluebutton.org with windows Chrome vs macbooks, iPads and iPhones. I can no longer reproduce the error....................................

**Comment by aogilvie** [comment]
How many TURN servers are running on test.bigbluebutton.org?

**Comment by aogilvie** [comment]
I am continuing to face this issue only on Safari. I will continue to test. iOS often give 1020 media server connection error, but after a few tries manages to connect video.

**Comment by ffdixon** [comment]
We have two turn servers on test.bigbluebutton.org (the DNS will randomly return one of them on lookup).

**Comment by aogilvie** [comment]
Finally resolved this. I am not sure the cause which our settings fix, however a couple of changes we make to each BBB deployment to guarantee webcams work on every browser flawlessly:

- WebRtcEndpoint.conf.ini, set stun address and port to a STUN server that specifically sends back srflx candidates, our coturn servers do not do this, so we used Google servers.
- turn-stun-servers.xml, set stun0 always to freeswitch.org. The bbb-install script overrides this, but we change it back.

Not sure why the above is how it is. I would have thought stun in xml should point to our turn servers as well.

**Comment by capilkey** [comment]
The STUN issue is strange. The coturn server that is set up is supposed to be a fully functional STUN server also and I would expect it to return the same candidates as any other STUN server. Were the coturn servers on the same network (hosting provider or LAN) as the BBB server?

**Comment by YoniMeidan** [comment]
@aogilvie we are also experiencing this issue. Also with test.bigbluebutton server.
Can you elaborate on your solution to this?

**Comment by aogilvie** [comment]
@YoniMeidan 
Debugging webcam issues with test.bigbluebutton will have to be done with a bigbluebutton team member (I cannot help).
If you have your own server setup the community can help you.
In the meantime, you could try using Google Chrome if that is possible for you.

**Comment by muppeth** [comment]
When using on iOS aparently any other browser does not want to even join the room claiming you need safari. Tested on the latest image and latest safari. While audio works, whenever I try to enable camera I get error 1020. I run my own instance. If there is anything I should look into (logs) or test something, please let me know. I'm quite new to BBB so didnt look around much. Tested on desktop and android and it works as expected.
