### ISSUE TITLE
Add password field in settings.yml for Redis, use it if not empty

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#7172]

**Comment by antobinary** [comment]
As part of this work, please ensure the parameters we have set for redis in settings.yml are properly set and used. There was a mention recently that we do not pass them correctly currently and the defaults are used instead

**Comment by capilkey** [comment]
The "port" property in settings.yml is misspelled as "post".

https://github.com/bigbluebutton/bigbluebutton/blob/master/bigbluebutton-html5/private/config/settings.yml#L280
