### ISSUE TITLE
Error WebRTC 1002

### ISSUE THREAD

**Issue by martorres** [bigbluebutton/bigbluebutton#7174]
Hello, my application was running WebRTC and suddenly stopped working. I already rode sudo _bbb-conf --restart_ but it did not work.

![image](https://user-images.githubusercontent.com/2020253/55568782-ba4b5500-56d6-11e9-8fd5-f37dbb2ca5b2.png)

**Comment by ffdixon** [comment]
Thanks for posting output of `bbb-conf --check`.  It looks like your running BigBlueButton 2.0 (RC7).

Is it an option for you to upgrade to the latest build of BigBlueButton 2.2-beta?  See

  https://groups.google.com/d/msg/bigbluebutton-dev/zX5NGZ_rAQs/yXh7Np_CAAAJ

We've done a significant amount of work on the BigBlueButton HTML5 client and support for WebRTC audio/video in the 2.2 development branch.
