### ISSUE TITLE
Allow breakouts to be recordable [+ add a config flag]

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#7181]
Currently we only have the recording option for the main meeting but not the breakouts.
- Add it to breakouts
- Add a flag in settings.yml with a default value of non recordable (like in https://github.com/bigbluebutton/bigbluebutton/blob/master/bigbluebutton-client/resources/config.xml.template#L22)

**Comment by GhaziTriki** [comment]
This flag shows `Record` checkbox in the create breakout rooms modal. If selected the record button will be visible in the breakout rooms.

**Comment by antobinary** [comment]
Implemented in #7337
