### ISSUE TITLE
Reduce mirror effect when screen sharing on a single screen

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#7183]
Currently, when screen sharing with a single monitor, the BigBlueButton HTML5 client shows "mirror in mirror" effect as the screen is shared.

![image](https://user-images.githubusercontent.com/290351/55658897-8d716d80-57bc-11e9-9172-48c55922c179.png)

Reduce the presenter's preview to a smaller thumbnail and put a title above it "You are now sharing your screen".

![image](https://user-images.githubusercontent.com/290351/55658855-6f0b7200-57bc-11e9-8b9f-dc08c8a17ea9.png)

With the smaller thumbnail, it will reduce the "mirror on mirror" effect for the presenter.

**Comment by tylercopeland** [comment]
Below is a revised take on this feature request. 

![html5-desktop-sharing](https://user-images.githubusercontent.com/1273169/62569639-cef25200-b85c-11e9-92b0-45693bf3d13f.png)


The adjustments to the design include changing the background colour to something darker and adding the button to stop sharing your screen.

**Comment by capilkey** [comment]
One fallout from this that we have to consider is that implementing this will remove the ability for us to add whiteboard over the screen share video.

**Comment by vadimluminous** [comment]
Does anyone have a solution to this? Somehow to disable the screen share only on the presenters side

**Comment by ostasevych** [comment]
In my opinion we have to allow viewers to see your screen without infinity loop effect in order to train users to use BBB :). What may be done is to use special algorithm, which counts loopings and disallows to have the 3rd one by replacing blank screen.

**Comment by blacktom** [comment]
I think it’s simple: when the presenter shares his screen, the stream should be sent back to him.

**Comment by aurelienslodzian** [comment]
Other conferencing systems let you choose which application window you want to share, a doc, a presentation, a spreadsheet, etc. Sharing is then limited to the ap. No mirror effect.

**Comment by prlanzarin** [comment]
> Other conferencing systems let you choose which application window you want to share, a doc, a presentation, a spreadsheet, etc. Sharing is then limited to the app. No mirror effect.

We do let you do that.

**Comment by rajeekum** [comment]
Hi All,

Do we have fix for this problem ? Or any suggestions on how to fix this issue. Need help urgently.

Thanks in advance.

Regards
Raj

**Comment by blacktom** [comment]
Just, do not send the image back to the presenter.

**Comment by rajeekum** [comment]
@blacktom Thanks for quick reply. Do you have code snippet for me try ?

**Comment by blacktom** [comment]
No, nothing, sorry. But since the system knows who is the presenter at any moment, it could exempt him from the distribution of the stream.

**Comment by motat331** [comment]
Hello is there any updates on this? This is a very annoying problem and happens all the time. Anytime you Share screen the viewer will see the feedback effect when you're starting the Screenshare and Also when you need to go back into the meeting to End the screenshare. So no matter what (unless you don't show Entire Screen which is not a feasible solution for many problems) the guests will always see this effect

**Comment by rajeekum** [comment]
Hello

I am looking for fix for above issue or any workaround available which can be done at code level not at user level. My users and trainers are continuously complaining about it.

Please help!

**Comment by aurelien-opex** [comment]
There are 2 workarounds:
- Share a single window instead of the whole screen. Works on Firefox, not on Safari.
- Share a secondary screen (e.g. jitsi on laptop screen => share external monitor)

**Comment by ZidaneCA** [comment]
> There are 2 workarounds:
> 
>     * Share a single window instead of the whole screen. Works on Firefox, not on Safari.
> 
>     * Share a secondary screen (e.g. jitsi on laptop screen => share external monitor)

Hello @aurelien-opex , please is there a way to eliminate this mirror effect altogether?

**Comment by matiasilva** [comment]
You can't eliminate this issue. This is by nature of the very action of sharing a screen that is also contains the screen being shared. What's being proposed here is a reduction, not a fix. It's unfixable. Hopefully users should pick up that it is an infinite loop and share something else or a single screen as proposed above.

**Comment by vadimluminous** [comment]
> 
> 
> You can't eliminate this issue. This is by nature of the very action of sharing a screen that also contains the screen being shared. What's being proposed here is a reduction, not a fix. It's unfixable. Hopefully users should pick up that it is an infinite loop and share something else or a single screen as proposed above.

I get what you're saying, but it's not at all true.

Look at any other app with screen share, Zoom, Skype, Teams, etc. None of them have this feedback loop. How do they do it? Well they simple don't display the screen to the one sharing the screen. Seems like an easy fix but I don't know anything about this software and it's infrastructure.

**Comment by prlanzarin** [comment]
There is a proposed design to mitigate this in the beginning of this issue. This has been acknowledged and we are aware of it. That design might be implemented as soon as somebody from the team is able to. On another note: pull requests are **very** welcome.

**Comment by vadimluminous** [comment]
> 
> 
> There is a proposed design to mitigate this in the beginning of this issue. This has been acknowledged and we are aware of it. That design might be implemented as soon as somebody from the team is able to. On another note: pull requests are **very** welcome.

Thank you. That's all I need to know. Unfortunately I don't have the skills to do this myself so I am relying on you guys. 

Thanks BBB Team.

**Comment by GabinhoJean** [comment]
> 
> 
> There is a proposed design to mitigate this in the beginning of this issue. This has been acknowledged and we are aware of it. That design might be implemented as soon as somebody from the team is able to. On another note: pull requests are **very** welcome.

This will be really helpful if this issue could be fixed. We hope to see that in the next release. 
Thanks for this amazing work

**Comment by amitnactus** [comment]
This is very annoying issue and need to be fixed soon. Layman users don't know and difficult to train every presenter for the same that you can't share whole screen and this kind of effect will be there.

**Comment by matiasilva** [comment]
> need to be fixed soon

Hi @amitnactus, feel free to submit a pull request.

**Comment by biksen** [comment]
Waiting for a fix..

**Comment by matiasilva** [comment]
@biksen please, no attitude :-) The community is meant to help each other, not to demand features or treat developers as if they were your servants. It may not have been your intention, but comments like those display a sense of entitlement. If you're interested in this feature, then get involved! Brainstorm possible implementations, ideas, things that can be done concretely so you don't have to wait.

**Comment by NiceboyWiseboy** [comment]
Hello @matiasilva ,

Can you please give some suggestions? As I've tried some possible solutions I could thought of. But that didn't worked.

Thank you

**Comment by alis-maroc** [comment]
Hi,
I test on firefox, right clic when sharing entire screen, on zone shared, and clic on pause button, it will pause mirroring screen and pause it on last opened window or firefox tab...

**Comment by kabaluyot** [comment]
Or similar with this

<img width="1680" alt="Screen Shot 2020-08-20 at 9 06 13 AM" src="https://user-images.githubusercontent.com/38805756/90705137-cb453800-e2c4-11ea-8f50-7beed183bbba.png">

**Comment by kabaluyot** [comment]
Okay so for now I found a workaround esp when you just want to hide that annoying mirror effect and you are sharing the screen of your BBB screen.

1. Right click to the mirrored presentation and select Picture in Picture
2. This will minimize the screen as an pop-up living a black screen. You can adjust the size of the mini player or hide it
3. You can now present your BBB screen in shared screen without the mirror effect

<img width="1614" alt="Screen Shot 2020-08-20 at 10 24 57 AM" src="https://user-images.githubusercontent.com/38805756/90709888-cdf95a80-e2cf-11ea-9fc3-3249fec79dab.png">

**Comment by melolontha-melolontha** [comment]
On 2020-05-27 blacktom provided the solution: “But since the system knows who is the presenter at any moment, it could **exempt him from the distribution of the stream**”. – This would be something to be done on the server side which would e.g. provide a uniformly painted rectangle for this particular participant.

In the now closed duplicate thread #7183 I proposed today: The computer which shares its screen, knows where the BBB window is in it. So it also knows where the BBB-window on the shared screen will be displayed. Then it would only have to **blank or replace that portion of the shared window** with the suggested uniformly painted rectangle **when it is reading its own screen or shared window content.** The rest around it will be to be shared then. – This approach would have to be coded in the script running on the screen-sharing computer.

Both solutions seem to be feasible. I can’t decide, which one causes less effort.

Unfortunately alis-maroc’s approach requires the user to pause the nesting of iterated shared screens very quickly. I never could do that before it was nested three or four times. Further the cursor is no longer shared. Looking above through other comments we see: the motivation to prevent nesting the shared window is mainly to train novice users in using BBB. That’s what triggered my own posting.

Unfortunately kabaluyot’s approach mitigates the disturbing effect a bit, because the nested images are much smaller so they become invisible after less iterations. But the problem (and the data and computation overhead) is still in it.

Unfortunately the approach of aurelien-opex to use a second screen did not work if my **intention is to teach BBB to the participants**: Of course I was able to move the BBB window to another physical or virtual screen. But to teach BBB to others, I have to show them the BBB screen. Then there is the infinite nesting again. Of course, in all other cases where you want **to teach everything on the computer except BBB**, it makes sense to share with BBB only the window of one application or to share the main desktop **while the BBB window lives on another screen**.

**Comment by mnjsnj** [comment]
I fix it by doing this on maybe it helps you

/usr/share/meteor/bundle/programs/web.browser/app/compatibility/kurento-extension.js


  if (message.type === 'screenshare') {

        let interval = setInterval(function() {
          let video=document.getElementById('screenshareVideo');
          if(video){
            video.pause();
            video.setAttribute('poster','https://i.ytimg.com/vi/GYaezmG__wk/maxresdefault.jpg');
            clearInterval(interval);
          }
          console.log('enter for interval');
        }, 1000);
        this.onSuccess()
    }

**Comment by revcjatharv** [comment]
I think the best way to resolve this problem is to follow the approach google meet follows.
So on the main tab where you see mirror while sharing repalce the screen with some balnk UI with a tex Like you are sharing. 
That resolved the issue for us.

**Comment by BuckDuane** [comment]
If the main problem is with displaying the BBB UI to trainers a possible work around would be to produce a slide presentation of the tutorials in advance and then scroll - select them as a standard lesson.

**Comment by uka-support** [comment]
I'd actually rather have the mirror-in-mirror effect than not be aware of what I'm sharing.

Also, a little thumbnail is not helpful there.

Another option might be not to show the shared content to the presenter and have a button to enable it. That should be rather easy. Of course, the wording of the button needs to be chosen carefully so it's obvious that the screen IS being shared but just not displayed back. Or make it an on/off toggle like "show my screenshare".
