### ISSUE TITLE
Hide fullscreen button on iOS devices 

### ISSUE THREAD

**Issue by Hanoos** [bigbluebutton/bigbluebutton#7185]
Within a video training HTML5 - full screen works on MAC but doesn't work on iPhone latest version

Hitting full screen doesn't do anything.

To reproduce :

1- Create a room with HTML5 preferred
2- Join as presenter
3- invite others to join using an iPhone 
4- upon sharing video - iphone users won't be able to go full screen for neither video nor presentation.

**Comment by ffdixon** [comment]
While the fullscreen button does not work on iPhones (and we need to hide it).

You can get Safari (which is running the BigBlueButton client) into full screen mode by rotating your phone to landscape.  When you do this, Safari will show all tabs.  Close each tab until you only have BigBlueButton running.  Then rotate portrait and then landscape again and BigBlueButton will be full screen.

![image](https://user-images.githubusercontent.com/290351/55672831-edb7ec00-585c-11e9-858e-59f3d332da7b.png)

**Comment by capilkey** [comment]
We changed the fullscreen buttons to be shown in iOS in #6981, but support for the API was only included for iPads and not iOS so now we have the non-functional buttons. We need to either do a browser or feature check so we don't show something that won't ever work.
