### ISSUE TITLE
Mobile Safari on iOS now showing who is talking highlights

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#7187]
When testing BigBlueButton using iOS 12.3, after logging into a session with a user with active microphone, there was no corresponding highlighting of the user's avatar when they were speaking.

**Comment by antobinary** [comment]
Merge into #7194

**Comment by capilkey** [comment]
Aren't these two different things? I think #7194 is the action bar highlight and this issue is with the user list highlight.
