### ISSUE TITLE
Hide Closed Captions option in Settings until ability to generate live captions is implemented in HTML5

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#7188]
Currently, the HTML5 client shows the ability to subscribe to closed captions

![image](https://user-images.githubusercontent.com/290351/55678124-8896e180-58c2-11e9-94df-2233025cad4f.png)

But in an all HTML5 client meeting, there isn't (yet) any way to generate the live captions from the HTML5 client.  

Until then, we need to add a server option in `settings.yml` to hide this option until we can generate the captions from the HTML5 client.

**Comment by antobinary** [comment]
If we do this, then closed captions entered via Flash client will not be visible. I tested this use case recently and it was functional. Please confirm

**Comment by ffdixon** [comment]
Confirmed -- let's hide it for now as we expect the vast majority of people will run the HTML5 client only.
