### ISSUE TITLE
Webcam not found in test.bbb.org

### ISSUE THREAD

**Issue by netlabs** [bigbluebutton/bigbluebutton#7191]
![Screenshot_20190408-083328](https://user-images.githubusercontent.com/45689540/55696123-1a7a1980-59ab-11e9-9b8e-41542126807c.jpg)

I have tried to join meeting in test.bbb.org using Firefox. But I have got error.

**Comment by ffdixon** [comment]
What mobile device are you using?  Does it work for you in Chrome?

**Comment by netlabs** [comment]
I have used oneplus 5 and in chrome its working.

**Comment by ffdixon** [comment]
On an Android device you are going to want to use Chrome -- it has the best support for sharing audio/video using WebRTC.

**Comment by netlabs** [comment]
ok Thank you.
