### ISSUE TITLE
Video preview issues

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#7197]
@capilkey please add more context

**Comment by capilkey** [comment]
I'm not 100% sure what is causing the issues, but it started with two mailing list posts that have a handful of people with issues. The posts are here, https://groups.google.com/forum/#!topic/bigbluebutton-dev/cw09SG0nUK4, and here, https://groups.google.com/forum/#!topic/bigbluebutton-dev/uY2G0MsLzpo. The common symptom is that the list of webcams in the video preview modal doesn't show any webcams or only the webcams it does show don't include the webcams it should.

I haven't been able to reproduce the issue so I don't know for sure what part is causing issue or if there's maybe more than one issue. While looking at the code though I saw multiple inconsistencies or odd bits so I'm going to try to clean up the code and add more logging and see if the issues are resolved or if more clues can be gained.

Some of the issues I've noticed are:
1. We call different `navigator.mediaDevices.X` and don't have a catch() for potential issues
2. The code to start a webcam in `componentDidMount` is distinct from the code to start a webcam in `handleSelectWebcam`. Both parts do basically the same thing, but in completely different ways
3. We call `enumerateDevices` twice when we should only need to call it once
4. The state that enables the "Start Sharing" button isn't turned on when the webcam is actually retrieved and it isn't reset when you select a different webcam
5. Adding on to #1, when an issue is encountered there's very limited feedback to the user so there's basically no chance they'll be able to resolve an issue themselves

I'm going to try to streamline the media grabbing to reduce the redundant calls to `enumerateDevices` and make a common path for starting the preview for a webcam. This will simplify the code and make edits in the future easier.

I'm also going to add proper error handling to the various WebRTC calls and try to present a human readable explanation to the user.

**Comment by pedrobmarin** [comment]
@prlanzarin does the changes we did to the provider/preview components covered this?

**Comment by prlanzarin** [comment]
Yeah (enumerate was streamlined, sharing code was streamlined, error feedback was vastly improved, faulty camera fail over was implemented).

Refs: https://github.com/bigbluebutton/bigbluebutton/pull/7328,  https://github.com/bigbluebutton/bigbluebutton/pull/11068, #11871
