### ISSUE TITLE
Use maxNumPages from redis msg for conversion file too large errors

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#7202]
> "`maxNumPages` is configurable in `bigbluebutton.properties` and we receive it in the conversion message in the `maxNumPages` property."

Use this number and plug it in `Ops, the page count exceeded the limit of 200 pages` so we do not hardcode numbers that could be changed on other people's environments

**Comment by TillF** [comment]
Probably related: The current error message when exceeding the page limit does not state the actual number. It would help the user the be given this information.
