### ISSUE TITLE
Allow selection/configuration of webcam resolution

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#7205]
In certain use cases the resolution [and visible area] of the presenter's webcam is to be higher [/larger] than that of the viewers.

Allow for dynamic adjustment of the `ideal` resolution of webcams [and add a configuration to only allow this for some roles]

**Comment by capilkey** [comment]
Do we need restrictions based on role? Would what we had in the Flash client not be enough?

**Comment by samuelpeixoto** [comment]
It's a great idea! We need it.
It would be very interesting to adjust the webcam display layout for participants during the conference.

**Comment by antobinary** [comment]
@prlanzarin Is this still valid?

**Comment by prlanzarin** [comment]
Do we need dynamic profiles based on user roles? If yes, then still valid.

My 2ct is that we don't need "role aware"camera profiles. It would suffice if the current audio floor camera was prioritized, for which there are other issues open.

**Comment by antobinary** [comment]
Thanks! Closing
