### ISSUE TITLE
Don't run tomcat7 if not installed

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#7212]
Reported in 

  https://groups.google.com/d/msg/bigbluebutton-dev/MhxXi-phnHY/X64t1tw6CgAJ

**Comment by jranke** [comment]
As mentioned here https://github.com/bigbluebutton/bigbluebutton/issues/8162#issuecomment-570564938, apt autoremove will remove tomcat7 after purging bbb-demo.

**Comment by GhaziTriki** [comment]
The behaviour of `bbb-conf` has been improved since, the services status shows tomcat only if detected.
