### ISSUE TITLE
User can't Join a meeting

### ISSUE THREAD

**Issue by Goldstareducation** [bigbluebutton/bigbluebutton#7213]
I have successfully installed bigbluebutton plugins in Wordpress WPLMS but plugins cannot work because the user cannot join the meeting room.  Do you have a solution to this problem?

**Comment by Goldstareducation** [comment]
I don't understand why it's wrong but when I updated the PHP version on my website I joined the meeting on bigbluebutton plugins that couldn't work. Is it because of the PHP version that I updated?

**Comment by ffdixon** [comment]
Can you share with us what version of OS/WordPress/PHP you are running.

**Comment by Goldstareducation** [comment]
I use wordpress version 5.1.1 and php version 7.2

**Comment by Goldstareducation** [comment]
Please to response thankyou

**Comment by ffdixon** [comment]
We need to setup your same environment and test it ourselves.  We're pretty focused right now on getting out the next update to BigBlueButton 2.2-beta. We'll update this issue when we have done some testing ourselves.

**Comment by GhaziTriki** [comment]
PHP 7.2 reached its end of life today. No more recommended to use it.
