### ISSUE TITLE
Arabic locale using indian number

### ISSUE THREAD

**Issue by GhaziTriki** [bigbluebutton/bigbluebutton#7214]
When the HTML5 client is loaded with the Arabic language it automatically uses the inadian numbers. Not all the Arabic countries use them. We need to find a how to configure it properley.

![image](https://user-images.githubusercontent.com/4991088/55868228-f02b8600-5b7b-11e9-8c9c-7bf1290d4e7c.png)

**Comment by GhaziTriki** [comment]
![image](https://user-images.githubusercontent.com/4991088/64128450-8328bf00-cdae-11e9-9152-8ece515976c4.png)

**Comment by prlanzarin** [comment]
@GhaziTriki ping, can you please check whether this is still valid?

**Comment by prlanzarin** [comment]
Reopen if needed.
