### ISSUE TITLE
Truncated user menu for the last user

### ISSUE THREAD

**Issue by GhaziTriki** [bigbluebutton/bigbluebutton#7216]
If the user list is full, its actions menu is truncated.

![image](https://user-images.githubusercontent.com/4991088/55868378-41d41080-5b7c-11e9-9500-03ecfec95e41.png)

**Comment by prlanzarin** [comment]
Although the action menu is truncated, the user list is scrollable and the action menu follows the scrolling. So it's not really perpetually truncated, just following the user entry. 

I'm closing this as a wontfix, but if somebody really thinks there's something to be done here, feel free to re-open.
