### ISSUE TITLE
iOS selected breakout rooms users not visible

### ISSUE THREAD

**Issue by GhaziTriki** [bigbluebutton/bigbluebutton#7220]
If we select users to be invited to breakout rooms then get validate, we cannot see those users.

**Comment by ffdixon** [comment]
Hmm ... do you mean we don't see the user in the selection dialog or in the breakout room (after they accept the invite)?

**Comment by GhaziTriki** [comment]
The issue in the breakout rooms creation, if we select users to assign to a breakout room, confirm then get back to the breakout rooms user selection, we still see empty lists. It happens when you click on `Done` of the attached screenshot.

![image](https://user-images.githubusercontent.com/4991088/56827190-04e36b80-6856-11e9-8f7b-67dfb095fd67.png)
