### ISSUE TITLE
Record button text and icon not vertically centered

### ISSUE THREAD

**Issue by GhaziTriki** [bigbluebutton/bigbluebutton#7224]
There is few pixels difference between top and bottom padding.

![image](https://user-images.githubusercontent.com/4991088/55869143-d68b3e00-5b7d-11e9-8f04-00ed43fb71d2.png)

**Comment by GhaziTriki** [comment]
It is still an issue in 2.3

Adding the following style to span containing the SVG image fixes it:

```css
margin-top: auto;
margin-bottom: auto;
```

**Comment by antobinary** [comment]
Addressed a few days ago via https://github.com/bigbluebutton/bigbluebutton/pull/12378

Could you please clarify if you tried branch 'develop' where 12378 was merged
or
latest release 2.3.1?

**Comment by GhaziTriki** [comment]
I testeed against 2.3.1

**Comment by prlanzarin** [comment]
Seems to be fixed (not a thing in 2.4 nor 2.5)
