### ISSUE TITLE
When I use akka-bbb-transcode for example, the camera rotates and it doesn't work, what should I do?

### ISSUE THREAD

**Issue by caojincool** [bigbluebutton/bigbluebutton#7225]

**Comment by ffdixon** [comment]
Are you using BigBlueButton 2.0? Is it an option for you to try BigBlueButton 2.2-beta, see

  http://docs.bigbluebutton.org/2.2/overview.html

which doesn't use akka-bbb-transcode?  You'll have a HTML5 client instead of a Flash client.
