### ISSUE TITLE
 bigbluebutton2.0 hao to change screenshare-chrome-extension on the Chrome extension check for versions >= 72

### ISSUE THREAD

**Issue by yuexiajiayan** [bigbluebutton/bigbluebutton#7226]
it use default not use my ,    hao to change this???
i see:
Remove the Chrome extension check for versions >= 72 
bigbluebutton2.0 hao to change??

**Comment by antobinary** [comment]
Chrome versions >= 72 do not need extension.

If you meant <72, check out this: https://github.com/bigbluebutton/screenshare-chrome-extension
