### ISSUE TITLE
timeout hit waiting for stream to start on share screen on bigbluebutton2.0 use  chrome  73

### ISSUE THREAD

**Issue by yuexiajiayan** [bigbluebutton/bigbluebutton#7227]
i use webrtc  see timeout hit waiting for stream to start  .   how to change config

**Comment by ffdixon** [comment]
Can  you try it on 

  https://test.bigbluebutton.org/

and let us know if you encounter the same problem.

**Comment by yuexiajiayan** [comment]
@ffdixon  it's no problem  ，but I installed  bigbluebutton2.0 the day before yesterday. This problem has arisen.

**Comment by ffdixon** [comment]
We're running BigBlueButton 2.2-beta on https://test.bigbluebutton.org/.  

Is it an option for you to try BigBlueButton 2.2-beta?  See

 http://docs.bigbluebutton.org/2.2/install.html

**Comment by yuexiajiayan** [comment]
@ffdixon  i find error
{"type":"error","code":2203,"message":"[screenshare] I'm sorry, I'm afraid I couldn't start the RTMP screenshare transposer :-)","operation":"subscribe","level":"error","timestamp":"2019-04-11T01:36:27.681Z"}

**Comment by vhuaquis** [comment]
Hi,
I need your help. Whe I try share the screen, it does not work. The log show this message:
May 22 00:17:43 salavirtual.acffaa.gob.pe bbb-webrtc-sfu[11165]: 2020-05-22T05:17:43.760Z - error: [screenshare] Error on starting screensharing RTP_TO_RTMP bridge roomId=67221, internalMeetingId=ebaebf0e5315e05f2c9be525de14556c26dd628f-1590124637663, status=MEDIA_STARTING, userId=little-darkness-4eZWyk_, mediaId=cold-moon-c~G9MIF, connectionId=2, role=presenter, hasFlashRTMPBridge=false, type=error, code=2203, message=MEDIA_NO_AVAILABLE_CODEC, details=undefined, stack=undefined, operation=subscribe

Thanks for your help.

**Comment by ffdixon** [comment]
Can you upgrade to BigBlueButton 2.2 and try again.
