### ISSUE TITLE
bbb-web not launching

### ISSUE THREAD

**Issue by dahalday** [bigbluebutton/bigbluebutton#7232]

**Comment by dahalday** [comment]
Just upgraded from bbb2.2 beta 3 to 4 bbb-web inactive on check even also clean restart. Also setsecret key does not change from default.

**Comment by ffdixon** [comment]
@dahalday Are you free for a few minutes now (we'd like to take a closer look)?

**Comment by ffdixon** [comment]
Did you do the command

~~~
sudo bbb-conf --setsecret <new_secret>
~~~

**Comment by dahalday** [comment]
Thanks @ffdixon. I rebooted the server several times before bbb-web status remained active after the bbb-conf --clean command and bbb-conf --status check. Honestly I am not sure what in particular fixed the issue. 

With regard to the sudo bbb-conf --setsecret <new_secret> the system prompted me to used the addition openssh command option. This generated the new key which worked. 

Thanks as always for your prompt reply.

**Comment by ffdixon** [comment]
Glad to hear -- let us know if you encounter any more issues.
