### ISSUE TITLE
Rotate FreeSWITCH Log files

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#7236]
Currently, the log rotation on FreeSWITCH does not expire the logs -- they simply accumulate and get larger.

Need to put some better parameters to ensure FreeSWITCH logs don't take up tens of gigabytes of disk space.

Reported in bigbluebutton-dev

  https://groups.google.com/d/msg/bigbluebutton-dev/asRCW0QvTJU/ZQ3ZDm_1CgAJ

**Comment by schrd** [comment]
freeswitch does log rotation on its own. It is configured in `/opt/freeswitch/etc/freeswitch/autoload_configs/logfile.conf.xml`

I'd suggest to reduce the default file size to something like 50 MB.

**Comment by erbth** [comment]
Hi there, reducing log level and the maximum log size for rotation is great. But I additionally wanted time based rotation and if someone else is interested in this, too, here is my approach: I added `systemctl kill -s HUP freeswitch.service` to my `/etc/cron.daily/bigbluebutton` just before the part which deletes old log files. By default freeswitch is configured to rotate log files when it receives a SIGHUP (can be changed in `/opt/freeswitch/etc/freeswitch/autoload_configs/logfile.conf.xml`), hence this performs daily rotation with automatic cleanup.

**Comment by hex-m** [comment]
On a `2.3.4` server this is configured by default. Log files are rotated when they reach 100MB in size and 10 files are kept.

**Comment by caniwi** [comment]
From looking in /etc/bbb-fsesl-akka/logback.xml it appears the logs should rotate every 14 days by default but on our 2.3.4 server the /opt/freeswitch/var/log/freeswitch/freeswitch.log has entries going back to when it was stood up:

2021-05-07 15:43:34.198462 [NOTICE] switch_loadable_module.c:350 Adding Application 'socket'
2021-05-07 15:43:34.198488 [NOTICE] switch_loadable_module.c:412 Adding API Function 'event_sink'
2021-05-07 15:43:34.200472 [INFO] mod_sofia.c:6260 Starting initial message thread.

The file is currently on 5.1MB.

Just wondering where the 100MB and 10 iterations is kept.  There does not appear to be any freeswitch.log in /var/log

**Comment by erbth** [comment]
@caniwi I think `/etc/bbb-fsesl-akka/logback.xml` configures the logging of Akka-FSESL itself and hence of the freeswitch ESL client used by it to control freeswitch. At least it refers to `/var/log/bbb-fsesl-akka/bbb-fsesl*.log`.

The actual freeswitch daemon has its own log file (the one at `/opt/freeswitch/var/log/freeswitch/freeswitch.log`), which is controlled by freeswitch's `mod_log`. `mod_log` handles the 100MB/10 files rotation, which is configured in `/opt/freeswitch/conf/autoload_configs/logfile.conf.xml`. And you're right, the log file location is a bit odd being not under `/var/log`, but I guess people decided to have freeswitch separate from the 'regular' filesystem base, considering it's located under `/opt`.

Apart from that I don't think freeswitch's `mod_log` supports time-based rotation on its own or that it could be forced by Akka-FSESL through ESL (see the docs at https://freeswitch.org/confluence/display/FREESWITCH/mod_logfile)... However sending a SIGHUP to freeswitch causes immediate rotation.

**Comment by antobinary** [comment]
Merging into https://github.com/bigbluebutton/bigbluebutton/issues/16629 which was recently closed on BBB 2.6
