### ISSUE TITLE
Low conference capacity 

### ISSUE THREAD

**Issue by dahalday** [bigbluebutton/bigbluebutton#7245]
Hi Team

I am excited about the latest beta 2.2v5. I tested it this morning. Of note the server hosting BBB should have 300Mbps symmetrical bandwidth. 

I noted that after 4 users the share screen quality goes down, lags and hangs. When the slides are uploaded the presentation lags after 8 uses. Is the a way to slightly decrease screen resolution so that I would a better screen share experience? Are there any other settings that could be changed?

On another note is there a way to get the computer keyboard arrows to advance the uploaded slides as opposed to clicking the forward icon?

The other issues related to iOS have been posted already so I will not comment about them here.

Kind Regards
DH

**Comment by ffdixon** [comment]
Hi DH,

Can you do a test session on https://test.bigbluebutton.org/ and let us know if you encounter the same experiences.  Thanks!

**Comment by dahalday** [comment]
Hi ffdixon

Thanks for the suggestion . I made it to 11 persons on  https://test.bigbluebutton.org/ before screenshare  glitched for some. The uploaded slides were excellent. 

I retested my server with others up to 10 on screenshare before a glitch. The uploaded slides were excellent. I think this may be an issue of bandwidth for the end users as the lag in change of view with screenshare on my second test ranged from 1- 10 seconds depending on the user. Everyone had almost immediate  changes with uploaded presentations. 

@antobinary  looking forward to the solution at #7247. This would mean making an uploaded presentation full screen and changing the slide  with clicker or arrows during a live conference. Looking forward to this very much. I will post this at #7247 also. 

Thanks again to everyone 

Kind Regards
DH

**Comment by Henry440** [comment]
I have the same problem.  a solution has now been found after one year?

**Comment by matiasilva** [comment]
@Henry440 please look at the date this was posted...over one year ago. 2.2v5 is long gone and 2.3 has now entered its alpha stage. Don't revive old issues. Please follow the instructions in the docs (https://docs.bigbluebutton.org/2.2/getting-help.html) for getting help.
