### ISSUE TITLE
Check for Safari <12.2 and suggest upgrade to support VP8

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#7246]
Safari 12.2+ seems to support VP8 codec out of the box. https://webkit.org/blog/8672/on-the-road-to-webrtc-1-0-including-vp8/

Add a client side check for the version of Safari and if it's <12.2, display a [toast?] suggestion to update iOS to the latest. [Technically 12.1 supported VP8 but after changing configs]

This should allow us to default to VP8 codec on BBB, and will address https://github.com/bigbluebutton/bigbluebutton/issues/6739 and others

**Comment by ffdixon** [comment]
On my iPhone that is running 12.3 (beta), the browser string is

Mozilla/5.0 (iPhone; CPU iPhone OS 12_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1.1 Mobile/15E148 Safari/604.1

**Comment by capilkey** [comment]
This doesn't seem to be working. Tried it with iOS 12.1.4 and there's no toast notifications.
