### ISSUE TITLE
Switch slides using leftArrow/rightArrow keyboard keys (as an option)

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#7247]
From #7245 

> On another note is there a way to get the computer keyboard arrows to advance the uploaded slides as opposed to clicking the forward icon?

**Comment by dahalday** [comment]
@antobinary  looking forward to the solution.  This would mean making an uploaded presentation full screen and changing the slide  with clicker or arrows during a live conference. Looking forward to this very much.
