### ISSUE TITLE
Explore improving highlighting of audio

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#7257]
In the Flash client we used an immediate change of state to shown when a user is talking.

![one](https://user-images.githubusercontent.com/290351/56098956-dfa94180-5ed4-11e9-9caa-fc27e8710964.gif)

In the HTML5 client, we use a pulse animation to highlight when a user is talking.   The pulse icon is more subtle than the 

![two](https://user-images.githubusercontent.com/290351/56098973-239c4680-5ed5-11e9-82d1-504f90020ea5.gif)

Let's explore whether having a more prominent indicator (such as a solid outline shown below) makes it easier for the instructor to determine who is talking during a session.

![image](https://user-images.githubusercontent.com/290351/56098945-788b8d00-5ed4-11e9-9e1d-1033a441ac64.png)

**Comment by tylercopeland** [comment]
@antobinary @ffdixon - with the new "Who is talking" experience, is this issue still something we want to explore?

**Comment by pedrobmarin** [comment]
Is it?
