### ISSUE TITLE
Add unread indicator to Shared Notes

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#7261]
Currently, we have an unread indicator for Public chat, but not for Shared Notes

![image](https://user-images.githubusercontent.com/290351/56133011-70c1fc00-5f59-11e9-86f9-e8b47cf5833f.png)

Need to add an indicator to Shared Notes when it has been updated after the user has closed the panel.

**Comment by antobinary** [comment]
Implemented in #7546
