### ISSUE TITLE
Subtitle/Captions File Upload API Feature

### ISSUE THREAD

**Issue by GhaziTriki** [bigbluebutton/bigbluebutton#7263]
Accessibility is important in the educational market. Providing captions for audio-only content is important for assisting users who are deaf or hard of hearing - and is a convenience for those who aren't, as well.

We currently offer the ability to have captions in the BigBlueButton meeting (by having a person in the session doing the live captioning), and these are automatically converted into a subtitle format for the recording. However, live captions often contain errors due to lack of editing, and the automatic timing and layout don't always provide great results.

We would like to provide the ability to upload a manually edited subtitle track and have it incorporated into the recording of a meeting.

- [ ] Basic getRecordingTextTracks API call.
- [ ] getRecordingTextTracks errors.
- [ ] Dynamically generate the captions download URL.
- [ ] process captions between sanity and process.
- [ ] transform `captions.json` for the API call.
- [ ] Basic putRecordingTextTrack API call.
- [ ] putRecordingTextTrack  errors.
- [ ] Write uploaded captions in the correct format.
- [ ] Check uploaded captions format.
- [ ] Trigger processing uploaded files.
- [ ] Convert uploaded files to `vtt`.
- [ ] Save and overwrite processed captions into published directory.
- [ ] Extract captions processing to a new worker (new recording step)
- [ ] Update docs with new 2 API methods and 1 new `rap` step.
- [ ] Share instructions for new packaging directories and files.

**Comment by capilkey** [comment]
An important thing will be what caption formats we will support. We'll have to check what the browsers and  the player support.

**Comment by GhaziTriki** [comment]
> An important thing will be what caption formats we will support. We'll have to check what the browsers and the player support.

The following types of subtitle files are accepted:
- SRT (SubRip Text), including basic formatting.
- SRT does not have a standard mime type, but application/x-subrip is accepted.
- SSA or ASS (Sub Station Alpha, Advanced Sub Station). Most formatting will be discarded, but basic inline styles (bold, italic, etc.) may be preserved.
- SSA/ASS does not have a standard mime type.
- WebVTT. Uploaded WebVTT files will be used as-is, but note that browser support varies, so including REGION or STYLE blocks is not recommended.
- The WebVTT mime type is text/vtt

However the captions worker will always convert them to to WebVTT format.

**Comment by GhaziTriki** [comment]
Feature fully implemented.
