### ISSUE TITLE
Chrome 49 does not load the HTML5 client

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#7276]
When testing BigBlueButton in older version of Chrome, the client fails to load (shows only a blue screen).

There is an exception thrown in the console

![image](https://user-images.githubusercontent.com/290351/56371381-03b59d00-61cb-11e9-98d8-fcdb7ed8eb46.png)

Need to add detection for versions of Chrome (at least 49 or earlier) and warn the user that they need to use a more recent version.

Reported here in bigbluebutton-users

  https://groups.google.com/d/msg/bigbluebutton-users/DHK_h7CuAek/G4C5-wvVCgAJ

**Comment by capilkey** [comment]
This was addressed in #7303. People on older browsers will be served an alternate minimal application that will tell them to update their browsers.
