### ISSUE TITLE
Record System Audio

### ISSUE THREAD

**Issue by dahalday** [bigbluebutton/bigbluebutton#7296]
Good Day Team

Keep up the good work. I was just wondering is there was a way to computer system sound during a meeting recording in addition to mic inputs.

Kind Regards
DH

**Comment by dahalday** [comment]
Good Day Team

Keep up the good work. I was just wondering is there was a way to computer system sound during meeting recording in addition to mic inputs. 

Kind Regards
DH

**Comment by ffdixon** [comment]
I think there are tools that let you route the output of the speakers back into the microphone.  I've not used them personally, but check out virtual audio cable

  https://www.howtogeek.com/364369/how-to-record-your-pc%E2%80%99s-audio-with-virtual-audio-cable/

**Comment by dahalday** [comment]
Thank I will look at this.
