### ISSUE TITLE
Remove the hard coded "200 pages limit" in some locale file

### ISSUE THREAD

**Issue by toushin-taishi** [bigbluebutton/bigbluebutton#7300]
The hardcoded "200 page" limit in some locale files (de.json, en.json, es_MX.json, fr.json, pt_BR.json) should be removed as the page limit can be changed in /usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties.

1. app.presentationUploder.upload.413": "File is too large, maximum of 200 pages reached <-- The "maximum of 200 pages reached" should be removed as the returned code is used by nginx to check against the maximum file size.

2. app.presentationUploder.conversion.pageCountExceeded": "Ops, the page count exceeded the limit of 200 pages <-- Should be rephrased and remove the word "200" as it is confusing when the maximum page was changed in the bigbluebutton.properties and error/message is still mentioning the same.

**Comment by ogryniuk** [comment]
This issue should be already closed. The corresponding locale files no longer contain hard coded mentions of 200 pages limit.
