### ISSUE TITLE
Place dial-in users at the bottom of the user's list

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#7304]
To make it easy to distinguish dial-in users from regular users, place all dial-in users at the bottom of the user's list

![image](https://user-images.githubusercontent.com/290351/56700227-3548cf80-66c7-11e9-9deb-651a8a1a4de6.png)

**Comment by antobinary** [comment]
Closing due to 

> I tested this on a recent version of the client and could not reproduce a userlist with dial-in other than on the bottom.
> On a different note, yes, we should adjust the existing isPhone detection rather than adding a new one. Should the issue be reproduced, this is the path we should take. Closing this for now. Also closing #7304
> ![Screenshot from 2019-05-22 16-17-25](https://user-images.githubusercontent.com/6312397/58206018-d9fe0300-7cad-11e9-9a78-f6c3b9bd3050.png)
> (notice how in 7304's screenshot the phone users were between moderators and non-moderators -- can't reproduce it now. Also the icon is different now)

in https://github.com/bigbluebutton/bigbluebutton/pull/7322#issuecomment-494957319
