### ISSUE TITLE
https://20t71z3582.iask.in/html5client/join?sessionToken=onarzijpzuoapnp9

### ISSUE THREAD

**Issue by Chechengwen** [bigbluebutton/bigbluebutton#7309]
https://20t71z3582.iask.in/html5client/join?sessionToken=onarzijpzuoapnp9
html5client/join?sessionToken=onarzijpzuoapnp9
Which project is the code in?
bbb-web？

**Comment by capilkey** [comment]
I don't know what you're asking about. Could you please provide more information.

**Comment by antobinary** [comment]
@Chechengwen this is a link to the HTML5 client. Look for the code under https://github.com/bigbluebutton/bigbluebutton/tree/master/bigbluebutton-html5/imports/ui
