### ISSUE TITLE
"Take Presenter" and "Make Presenter"

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#7311]
When a moderator clicks on their name in the user's list, the operation for switching presenter should read

  "Take presenter"

This makes sense because it's an action done by the user (they are clicking their name).

![image](https://user-images.githubusercontent.com/290351/56823526-20cd1a00-6822-11e9-9b37-0c90651c5ffb.png)

When clicking on another user's name in the list, the action to switch presenter should be 

  "Make presenter"

as your doing an action on a target.   This follows the similar imperative phrasing as "Remove user", "Demote to viewer", etc.

**Comment by ritzalam** [comment]
I suggest "Be presenter" instead of "Take presenter".

**Comment by capilkey** [comment]
There's already two strings on master. It was changed 4 days ago in this PR https://github.com/bigbluebutton/bigbluebutton/pull/7287

**Comment by capilkey** [comment]
What it looks like on master.
![image](https://user-images.githubusercontent.com/1395090/56823973-4870b200-6823-11e9-8d3b-e0dc076ac789.png)
and
![image](https://user-images.githubusercontent.com/1395090/56823986-50305680-6823-11e9-9896-ca4defeaa520.png)

**Comment by ffdixon** [comment]
Looks good!
