### ISSUE TITLE
Users able to click 'Yes' before call is setup with FreeSWITCH causes 1008 error

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#7317]
In the latest build of BigBlueButton, on some networks if a user is too quick to click 'Yes' on the echo test, they can trigger the transfer before FreeSWITCH has had a chance to accept the call for echo test (thus resulting in a 1008 error).

**Comment by capilkey** [comment]
From the other issue:

> In testing Version 74.0.3729.108 (Official Build) (64-bit) on Mac OS X 10.14.4, I found that Chrome was taking a long time (about 5 seconds) to connect to the echo test. Clicking 'Yes' before hearing myself would result in a 1008 Transfer Failed message.
> 
> ![image](https://user-images.githubusercontent.com/1395090/56977071-60f20c80-6b42-11e9-9747-42a461db1b49.png)
>

**Comment by dahalday** [comment]
Good Day
 Having similar issue with BBB v 2.2 beta 6. More noticable when using Chrome for Android OS.

**Comment by capilkey** [comment]
This should be alleviated in 2.2-beta7. The triggers for being in a call and transfer succeeding have been changed in #7404.
