### ISSUE TITLE
Clicking with Text tool should draw default text area

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#7318]
Currently, the text tool in the HTML5 client requires a click and drag operation to draw a text box 
before the user can type.

Users familiar with the previous Flash client could click once and have the client draw a default text box for typing.

We need to support a single click/default text area in the HTML5 client.

**Comment by TuringTux** [comment]
Seconded. This would massively improve the text tool, which at least at my place is used relatively often. Maybe issue #2552 is related regarding the quality of life for the text tool?

**Comment by JustinMogel** [comment]
looks like this issue can be closed since on 2.3-beta-1 (1511) i can draw a text area with one click
