### ISSUE TITLE
WebCam Playback doesn't works in 2.2-beta6

### ISSUE THREAD

**Issue by rriscado** [bigbluebutton/bigbluebutton#7319]
BigBlueButton 2.2-beta6 record and playback scripts did not process the webcams for playback.

**Comment by ffdixon** [comment]
Can you provide us more information

1.  Is this your own BigBlueButton server?
  (a) What version did you install?
  (b) Did you get any errors on the installation
  (c) Did the recording of webcams work previously

2.  Can you reproduce the issue on our https://demo.bigbluebutton.org/ server (you can create an account on that server using a Google account).

Any steps you could give us to reproduce would be helpful.

**Comment by rriscado** [comment]
> Can you provide us more information
> 
> 1. Is this your own BigBlueButton server?
>    (a) What version did you install?
>    (b) Did you get any errors on the installation
>    (c) Did the recording of webcams work previously
> 2. Can you reproduce the issue on our https://demo.bigbluebutton.org/ server (you can create an account on that server using a Google account).
> 
> Any steps you could give us to reproduce would be helpful.

1. Yes this is my BBB Server.
(a) 2.2-beta6. I used bbb-install.sh script.
(b) I Didn't any errors on the instalation.
(c) In flash room records works fine. Only in html5 room occurs this error. (2.2-beta6)
(c.2) In 2.0 stable version Flash and HTML5 works fine.

2. In https://demo.bigbluebutton.org/ works fine.

Other Information: In my BBB Server I skip check audio and auto start WebCam.

**Comment by ffdixon** [comment]
Can you update to the latest build of BigBlueButton 2.2-beta-6, see

  https://groups.google.com/d/msg/bigbluebutton-dev/mgmDVi8yFGU/9AJX9ZJ4AQAJ

and let us know if you still have the problems after update.

**Comment by rriscado** [comment]
> Can you update to the latest build of BigBlueButton 2.2-beta-6, see
> 
> https://groups.google.com/d/msg/bigbluebutton-dev/mgmDVi8yFGU/9AJX9ZJ4AQAJ
> 
> and let us know if you still have the problems after update.

Hi ffdixon!!

Works fine for me now!!!! Thanks!!!!
