### ISSUE TITLE
docker build fail - (bbb-common-web)

### ISSUE THREAD

**Issue by lahirudx** [bigbluebutton/bigbluebutton#7320]
Hi,
I'm trying to bbb on docker.

Inside `bigbluebutton/labs/docker`, I have executed the command `make release`.
After the command execution finished I have checked for available images.
But some required images are not listed there.

when I tried to build `bbb-common-web` image manually by running command
`docker build -t 'bbb-common-web' --build-arg COMMON_VERSION=0.0.1-SNAPSHOT .`
it gives an error,
`[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: org.bigbluebutton#bbb-common-message_2.12;0.0.20-SNAPSHOT: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 
[warn] 	Note: Unresolved dependencies path:
[warn] 		org.bigbluebutton:bbb-common-message_2.12:0.0.20-SNAPSHOT (/bbb-common-web/build.sbt#L33)
[warn] 		  +- org.bigbluebutton:bbb-common-web:0.0.1-SNAPSHOT
[error] sbt.librarymanagement.ResolveException: unresolved dependency: org.bigbluebutton#bbb-common-message_2.12;0.0.20-SNAPSHOT: not found
`
But `bbb-common-message` is listed on the docker image list.

How can I resolve this error.?

**Comment by bigzbigz** [comment]
Do you find a solution for your problem ?

**Comment by MaxEmanuel** [comment]
User tauu has fixed this issue:
https://github.com/MaxEmanuel/bigbluebutton/tree/dockerfile-fix

Not it builds but I get bbb-web then throws java errors on runtime...

**Comment by pedrobmarin** [comment]
https://github.com/bigbluebutton/docker for docker support
