### ISSUE TITLE
First time sharing webcam gives 1020 error

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#7321]
In testing various BigBlueButton 2.2-beta servers, I noticed about half them time after updating a server to the latest build, I needed two attempts to share my webcam.  The first would result in a 1020 error, and the second time it would work.

![second-time](https://user-images.githubusercontent.com/290351/56895869-3b88d400-6a58-11e9-98a7-95f06f1dbd93.gif)

These servers were running

~~~
bbb-webrtc-sfu                        1:2.2.0-55
~~~

and

~~~
root@m031:~# dpkg -l | grep bbb
ii  bbb-apps                              1:2.2.0-19                                      amd64        BigBlueButton applications for Red5
ii  bbb-apps-akka                         2.2.0-45                                        all          BigBlueButton Apps (Akka)
ii  bbb-apps-screenshare                  1:2.2.0-19                                      amd64        BigBlueButton screenshare module for Red5
ii  bbb-apps-screenshare-h264             1.1-3~20171031143106.22                         amd64        H.264 support for BigBlueButton screenshare
ii  bbb-apps-sip                          1:2.2.0-10                                      amd64        BigBlueButton SIP module for Red5
ii  bbb-apps-video                        1:2.2.0-18                                      amd64        BigBlueButton video module for Red5
ii  bbb-apps-video-broadcast              1:2.2.0-8                                       amd64        BigBlueButton video broadcast module for Red5
ii  bbb-client                            1:2.2.0-29                                      amd64        BigBlueButton Flash client
ii  bbb-config                            1:2.2.0-70                                      amd64        BigBlueButton configuration utilities
ii  bbb-etherpad                          1:2.2.0-37                                      amd64        The EtherPad Lite components for BigBlueButton
ii  bbb-freeswitch-core                   2:2.2.0-27                                      amd64        BigBlueButton build of FreeSWITCH
ii  bbb-freeswitch-sounds                 1:1.6.7-9                                       amd64        FreeSWITCH Sounds
ii  bbb-fsesl-akka                        2.2.0-26                                        all          BigBlueButton FS-ESL (Akka)
ii  bbb-html5                             1:2.2.0-396                                     amd64        The HTML5 components for BigBlueButton
ii  bbb-mkclean                           1:0.8.7-4                                       amd64        Clean and optimize Matroska and WebM files
ii  bbb-playback-presentation             1:2.2.0-17                                      amd64        BigBluebutton playback of presentation
ii  bbb-record-core                       1:2.2.0-29                                      amd64        BigBlueButton record and playback
ii  bbb-red5                              1:1.0.10-16                                     amd64        The Red5 server for BigBlueButton
ii  bbb-sender                            2.2.2                                           all          Send BigBlueButton recordings to a recording server
ii  bbb-swftools                          1:0.9.2-2                                       amd64        The swftools files for BigBlueButton
ii  bbb-transcode-akka                    2.2.0-7                                         all          BigBlueButton Transcoder
ii  bbb-web                               1:2.2.0-80                                      amd64        BigBlueButton API
ii  bbb-webrtc-sfu                        1:2.2.0-55                                      amd64        BigBlueButton WebRTC SFU
ii  bigbluebutton                         1:2.2.0-4                                       amd64        Open source web conferencing platform (bbb)
root@m031:~# dpkg -l | grep kms
ii  kms-core                              6.10.0.xenial~20190414162720.25.ebabebd         amd64        Kurento Core module
ii  kms-elements                          6.10.0.xenial~20190414163239.25.fffd5b5         amd64        Kurento Elements module
ii  kms-filters                           6.10.0.xenial.20190414163714.24.100a3f8         amd64        Kurento Filters module
ii  kms-jsonrpc                           6.10.1-0kurento1.16.04~20190410162002.gbp39602c amd64        Kurento JSON-RPC library
ii  kmsjsoncpp                            1.6.3.xenial.20181017180019.d78deb7             amd64        Kurento jsoncpp library
~~~

**Comment by prlanzarin** [comment]
Is this still an issue after the updates to SFU?

**Comment by ffdixon** [comment]
Hmm ... I will do a bit more testing

**Comment by boblmartens** [comment]
I am running into a similar issue, but even on the second attempt it does not connect the camera. When I am on-campus (behind our firewall) it will work, but when I am off campus it will not and the second time will give me the ICE negotiation failure even as the microphone continues to work.

**Comment by ffdixon** [comment]
Hi @boblmartens -- can you test against https://test.bigbluebutton.org/ when you are off campus and let us know if you can connect to this server without errors.

**Comment by boblmartens** [comment]
I will do that tonight.

**Comment by boblmartens** [comment]
I was able to connect just fine this weekend. We are considering a TURN server next to see if that fixes our issues or at least helps mitigate them. Thoughts?

**Comment by prlanzarin** [comment]
From your description it definitely seems the case of a network connectivity problem. Setting up a TURN server is always recommended, specially when you have a firewalled setup like yours (inside/outside university campus). Alongside using a TURN server, you should check again if you opened the recommended UDP ports in your firewall so it'll reduce the number of TURN users.

**Comment by boblmartens** [comment]
I will do that when I go through setting up the TURN server. I will also check out the iOS audio issue I have been running into as well and see if that is a problem on the test BBB instance as well.

**Comment by boblmartens** [comment]
Setup the TURN server and have run into the same issue continually. Looking at the Chrome console, it looks like the BBB server is giving our internal IP to external users specifically for webcam sharing. WebRTC audio is working fine from Chrome, externally, but not the video.

**Comment by prlanzarin** [comment]
https://docs.bigbluebutton.org/2.2/configure-firewall.html#extra-steps-when-server-is-behind-nat
Did you perform these steps?

**Comment by boblmartens** [comment]
Yes I did and I just went ahead and confirmed.

**Comment by vejnas** [comment]
Hi, I have a similar problem, The first time sharing the camera works but if I stop sharing and try new camera sharing it won't work (error 1020 media not able to reach server) until I restart the server (sudo bbb-conf --restart). Do you know what it could be a problem or where to look?. The server is on the google cloud platform and the firewall is opened. 
Thanks in advance.

**Comment by ffdixon** [comment]
What version of BigBlueButton are you running?

Can you do a quick test at https://demo.bigbluebutton.org/ and let us know if you can also reproduce the issue there.

**Comment by vejnas** [comment]
Version: BigBlueButton Server 2.2.0-rc-3 (1661)
I have tested on https://demo.bigbluebutton.org/, didn't have a problem running multiple camera sharing sessions just to mention first try of camera sharing got error 1020 then I tried again and it worked.

**Comment by capilkey** [comment]
Does the server's public IP show up in about:webrtc or chrome://webrtc-internals when you try to share your camera with the server hosted on Google cloud?

**Comment by peraTM** [comment]
Hi,
I've got the same issue on a fresh install of bbb with greenlight (in docker) on a fresh VMware VM with a public IP (no NAT) and opened Firewall (any:any to bbb = permit).

Followed the steps mentioned in these two threads... Anything else I could/should try to resolve this?

**Comment by peraTM** [comment]
Turns out I missed one line in one of the configs when switching to SSL.
My bad.

**Comment by n3niu** [comment]
Hi, which setting did you change to make it work?

I'm still struggling with the 1020 issue. Preview is working fine but then it shows "Webcam sharing locked" constantly.

**Comment by platu** [comment]
Hello,
I'm also interested in further investigations.
I ran into the same problem with a fresh install and a successful test on the demo site https://demo.bigbluebutton.org/

**Comment by KurJay** [comment]
Same here and just fresh install can anybody help? At my iPhone device can not run the video
Regards

**Comment by robregonm** [comment]
I've found that this issue is only occurring on iOS (Safari 13 & 14)

**Comment by robregonm** [comment]
> I've found that this issue is only occurring on iOS (Safari 13 & 14).
> I'm using BBB v. 2.2.28.

Enabling a TURN server solved the issue

**Comment by prlanzarin** [comment]
Closing this as stale.
