### ISSUE TITLE
When presenter leaves[/is changed] stop sharing youtube video

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#7334]
Currently if youtube video is being shared and the presenter leaves, it continues playing while it should be stopped (and the client for all participants should switch back to presentation (or whatever the previous state was))

**Comment by antobinary** [comment]
@jfsiebel reminded me that we had a handle for this in place already via https://github.com/bigbluebutton/bigbluebutton/pull/6806

**Comment by ffdixon** [comment]
A follow-on issue for this is if the presenter starts sharing their screen, the YouTube video player will remain visible.

If another user is given presenter rights, the first presenter's screen share won't automatically stop (the display is still showing the YouTube video).

The client needs to automatically stop the YouTube video when either (a) the presenter starts sharing their screen, or (b) another user becomes the presenter.

**Comment by JustinMogel** [comment]
this issue does not occur on 2.3-beta-1 (1511)
the video stops in seconds after the presenter leaves the coference

looks like this issue can be closed

**Comment by prlanzarin** [comment]
Yeah, as far as I remember this has long been addressed.
