### ISSUE TITLE
Reverse the title in logout

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#7342]
Currently we show the following message to users when the meeting has ended

![image](https://user-images.githubusercontent.com/290351/57146022-647bd280-6d92-11e9-8fff-65a715c624c4.png)

Let's reverse the ordering where Meeting has Ended is in large font and 410 is in the small font.

**Comment by capilkey** [comment]
I think we really want to just completely remove the number from the page. There's really no added benefit to having it there.

**Comment by antobinary** [comment]
We are working on recovering the friendlier set of pages for Meeting end and Removed from meeting https://github.com/bigbluebutton/bigbluebutton/issues/7324
