### ISSUE TITLE
Use RTL layout for RTL scripts in the HTML5 client

### ISSUE THREAD

**Issue by GhaziTriki** [bigbluebutton/bigbluebutton#7345]
W3C Guide : https://www.w3.org/International/techniques/authoring-html#using
Directional SCSS : https://github.com/tysonmatanich/directional-scss
React With Direction : https://github.com/airbnb/react-with-direction

**Comment by pedrobmarin** [comment]
Hi @GhaziTriki . We can also set RTL to the shared notes based on the client language. What do you think?
Besides Arabic, what other RTL languages BBB supports?

**Comment by GhaziTriki** [comment]
@pedrobmarin There is no reason we could not do RTL in shared notes, however, this component may have special care because it is loaded in an iFrame.

The most commonly used RTL languages are Arabic, Persian/Farsi, and Hebrew. With fewer uses, we have Aramaic, Azeri, Dhivehi/Maldivian, Kurdish (Sorani) and Urdu.

**Comment by pedrobmarin** [comment]
Yeah, I'm aware of the iframe. We use Etherpad HTTP API and we can pass a boolean value for RTL as param (https://etherpad.org/doc/v1.7.5/#index_rtl)

**Comment by GhaziTriki** [comment]
@antobinary Where does the highlighted message come from? I could not find it in the locale !!

![image](https://user-images.githubusercontent.com/4991088/57222375-36003080-6ffa-11e9-9a03-38a3199f5037.png)

**Comment by capilkey** [comment]
The string is what bbb-web responds with. 
![image](https://user-images.githubusercontent.com/1395090/57246944-8c766a80-700c-11e9-8445-3fdc9122b365.png)
It should be changed to custom message so it can be translated.

**Comment by antobinary** [comment]
https://github.com/bigbluebutton/bigbluebutton/blob/master/bigbluebutton-html5/imports/ui/components/error-screen/component.jsx#L81 @GhaziTriki 

Should be addressed as part of https://github.com/bigbluebutton/bigbluebutton/issues/7324

**Comment by GhaziTriki** [comment]
Implemented in 2.2-beta8
