### ISSUE TITLE
Update bbb-lti for BigBlueButton 2.2-beta

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#7349]
We recently moved bbb-web to run as a stand-alone application (outside of tomcat7) and we need to either do a similar migration for bbb-lti or update with the newer version of Grails and have it run under tomcat7.

**Comment by gm2117** [comment]
Hi Fred,
I skipped reading this note so the result is that I get the 500 error when I try to use the bbb-lti.
So I am in trouble to make it work. Any tips how to fix this? in the page still refers to old thinks that is not much of help 
Kind regards
George MOUSTAKAS

**Comment by ffdixon** [comment]
Hi George,

We're actively working on updating the bbb-lti plugin for BigBlueButton 2.2-beta.  You should see some updates to the plugin (and documentation) in the next upcoming release of 2.2-beta.

**Comment by gm2117** [comment]
Hi Fred,
Thank you for your reply since is a timing issue, you know when that would happen or you suggest that I have to downgrade to 2.0 My time frame is in one week

**Comment by GhaziTriki** [comment]
@gm2117 Could you please test the LTI upgrade with 2.2 again. We fixed most of the issues.

We recently fixed `--setip` and `--salt` to work as expected.

And we are working on putting logs into a file and checking the implementation with Edx.

**Comment by gm2117** [comment]
Thanx for the info, great news.
While i am trying to upgrade it bbb-lti is stil at version 1:2.2.0- 29 where I can find the new version?

**Comment by gm2117** [comment]
Found it, applied it, did execute it and I attach the log file. Seems that the calculation of the SHA1 or SHA256 is mismatching
[bbb-lti.log](https://github.com/bigbluebutton/bigbluebutton/files/3439442/bbb-lti.log)

**Comment by gm2117** [comment]
@GhaziTriki  All seems to work still in some cases the bbb-conf --lti comes empty but the service is there and running.
When I change the value ltiAllRecordedByDefault=true in  lti-config.properties the 500 error comes back does not show the recordings although they are there.

**Comment by GhaziTriki** [comment]
@gm2117 Recrordings are now correctly shown. Fixed in this PR https://github.com/bigbluebutton/bigbluebutton/pull/8176

**Comment by GhaziTriki** [comment]
@ffdixon This task is finished. I think this issue can be closed.

**Comment by gm2117** [comment]
Yes it can be closed. Although the few lines of documentation update would be much appreciated


Kind regards
George MOUSTAKAS

On 25 Oct 2019, at 20:53, Fred Dixon <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #7349<https://github.com/bigbluebutton/bigbluebutton/issues/7349>.

**Comment by ffdixon** [comment]
Hi Greg -- can you specify the items you would like expanded in the docs and we'll definitely update them.

**Comment by gm2117** [comment]
Hi Fred,
As you see they are from 2012 something.
- In general the lti plug in, is giving errors when you have the ltiAllRecordedByDefault=true and the link is https://yourbigbluebuttonserver.com/bigbluebutton in some cases
but not when the link is
http://yourbigbluebuttonserver.com/bigbluebutton
Can you tel what are the parameters to include when generating the meetingID

- Nothing more than it is now, but has to be adapted to to tomcat7 new directory new commands to generate the files etc….
Actually the sections that need to be updated are:
- Development
- Deployment
- How to use the service

Kind regards
George MOUSTAKAS



On 27 Oct 2019, at 23:53, Fred Dixon <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Greg -- can you specify the items you would like expanded in the docs and we'll definitely update them.
