### ISSUE TITLE
Allow users to make chat panel wider

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#7351]
In the previous version of BigBlueButton (Flash client), users could expand the chat window and make it as large as they want.

We currently have a maximum width of the chat window.  Investigate making it wider to accommodate users who want to primarily chat.

**Comment by pedrobmarin** [comment]
Since the panel manager, this is not hard to achieve. https://github.com/bigbluebutton/bigbluebutton/blob/7c9286ef19589b660ec8489e093e783a2c43b238/bigbluebutton-html5/imports/ui/components/layout/layout-manager.jsx#L20
