### ISSUE TITLE
Message number indicator overflows the chat pane at mouse over

### ISSUE THREAD

**Issue by GhaziTriki** [bigbluebutton/bigbluebutton#7352]
![image](https://user-images.githubusercontent.com/4991088/57230818-188a9100-7011-11e9-826e-4163235ccd4c.png)

**Comment by JustinMogel** [comment]
![BBB chat](https://user-images.githubusercontent.com/80588280/113266390-83b07100-92d5-11eb-996b-ce95ab334b41.png)

this is how it looks on 2.3-beta-1
