### ISSUE TITLE
There's no local preview of the text tool

### ISSUE THREAD

**Issue by capilkey** [bigbluebutton/bigbluebutton#7353]
When you create a text annotation you can't see what you are writing. This worked fine in beta 6 and is now broken on master.

Reported here, https://groups.google.com/forum/#!topic/bigbluebutton-users/WGkY3Bv7ZNY

**Comment by antobinary** [comment]
The issue originated in https://github.com/bigbluebutton/bigbluebutton/pull/7306/files#diff-4216f8350ac0cdfe18a1e8c00201a1d2R74 Still looking for how to modify it

**Comment by antobinary** [comment]
Addressed in #7354
