### ISSUE TITLE
2.2 events of non recorded meetings only processed after a recorded meeting

### ISSUE THREAD

**Issue by hostbbb** [bigbluebutton/bigbluebutton#7378]
processing of non recorded events creates end/meetingid.done files, but scripts do not look here until recorded meeting is processed

root@aiebbb:~# cat /usr/lib/systemd/system/bbb-rap-archive-worker.service
[Unit]
Description=BigBlueButton recording and playback archive worker
ConditionPathExistsGlob=/var/bigbluebutton/recording/status/recorded/*.done

[Service]
Type=simple
ExecStart=/usr/local/bigbluebutton/core/scripts/rap-archive-worker.rb
WorkingDirectory=/usr/local/bigbluebutton/core/scripts
User=bigbluebutton
Slice=bbb_record_core.slice

**Comment by hostbbb** [comment]
UPDATE So updated to Beta7.  the end folder is created, non recorded meetings appear in .done.

the non recorded meeting creates a directory in /var/bigbluebutton/events but no events.xml file.
the non recorded .done flag remains in end folder.

here is log rap worker,  wrong number of arguments?

recorded meetings process fine, and appear in /var/bigbluebutton/events as well. 

Task: Getting meeting metadata
I, [2019-05-16T11:29:37.201696 #32462]  INFO -- : Successfully archived 183f0bf3a0982a127bdb8161e0c44eb696b3e75c-1558006009176
I, [2019-05-16T11:29:37.201993 #32462]  INFO -- : Executing: ruby events/events.rb -m 183f0bf3a0982a127bdb8161e0c44eb696b3e75c-1558003751647
I, [2019-05-16T11:29:37.398072 #32462]  INFO -- : /usr/local/bigbluebutton/core/lib/recordandplayback/events_archiver.rb:38:in `initialize': wrong number of arguments (given 2, expected 3) (ArgumentError)
I, [2019-05-16T11:29:37.398155 #32462]  INFO -- :       from events/events.rb:29:in `new'
I, [2019-05-16T11:29:37.398183 #32462]  INFO -- :       from events/events.rb:29:in `keep_events'
I, [2019-05-16T11:29:37.398217 #32462]  INFO -- :       from events/events.rb:75:in `<main>'
I, [2019-05-16T11:29:37.401501 #32462]  INFO -- : Exit status: 1
I, [2019-05-16T11:29:37.401615 #32462]  INFO -- : Executing: ruby events/events.rb -m 183f0bf3a0982a127bdb8161e0c44eb696b3e75c-1558006009176
I, [2019-05-16T11:29:37.618573 #32462]  INFO -- : Exit status: 0
I, [2019-05-16T11:29:37.618683 #32462]  INFO -- : Executing: ruby events/events.rb -m 183f0bf3a0982a127bdb8161e0c44eb696b3e75c-1558005648908
I, [2019-05-16T11:29:37.832335 #32462]  INFO -- : /usr/local/bigbluebutton/core/lib/recordandplayback/events_archiver.rb:38:in `initialize': wrong number of arguments (given 2, expected 3) (ArgumentError)
I, [2019-05-16T11:29:37.832429 #32462]  INFO -- :       from events/events.rb:29:in `new'
I, [2019-05-16T11:29:37.832461 #32462]  INFO -- :       from events/events.rb:29:in `keep_events'
I, [2019-05-16T11:29:37.832485 #32462]  INFO -- :       from events/events.rb:75:in `<main>'
I, [2019-05-16T11:29:37.838163 #32462]  INFO -- : Exit status: 1

**Comment by ffdixon** [comment]
Thanks for digging into this -- will take a closer look.

**Comment by kepstin** [comment]
We've added a separate processing worker to handle the events files for non-recording meetings which gets triggered automatically. Everything should be good to go in the current 2.2 beta builds.
