### ISSUE TITLE
Join breakout room appears again if the settings are changed

### ISSUE THREAD

**Issue by GhaziTriki** [bigbluebutton/bigbluebutton#7385]
Steps to reproduces:
- Create breakout rooms and put yourself in a breakout room.
- When you are prompted to join click on cancel.
- Go to settings.
- Change the language and save.
=> The application is refreshed and the join breakout room windows appear again.

We need to check if it is not the case for other modals.

**Comment by JustinMogel** [comment]
tested this on 2.3-beta-1 (1511) with windows 10 and chrome Version 89.0.4389.114
this issue did not occur

**Comment by prlanzarin** [comment]
Stale.
