### ISSUE TITLE
Menus do not close when showing poll in small screen

### ISSUE THREAD

**Issue by GhaziTriki** [bigbluebutton/bigbluebutton#7387]
In the following case, we can become a presenter, it validates and publishes the poll.

![image](https://user-images.githubusercontent.com/4991088/57395016-e61e9680-71be-11e9-9917-e66d29f65657.png)

**Comment by KDSBrowne** [comment]
@GhaziTriki Can you confirm that the poll gets published when you become presenter? In my test it cancels the poll and nothing is published.
