### ISSUE TITLE
bbb-html5 is not start

### ISSUE THREAD

**Issue by ishangxue** [bigbluebutton/bigbluebutton#7393]
hello bbb
       i cant open html5-client  ,it show  404 Not Found.
       when  i install html5-client as  bbb-install.sh . i can open  flash-client , but icant open html5-client. it show 404 Not Found.

log:
1、
    **root@ubuntu:/home/ufo# bbb-conf --check**

BigBlueButton Server 2.2.0-beta6 (1001)
                    Kernel version: 4.4.0-146-generic
                      Distribution: Ubuntu 16.04.6 LTS (64-bit)
                            Memory: 8156 MB
                         CPU cores: 4

/usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties (bbb-web)
       bigbluebutton.web.serverURL: http://192.168.11.186
                defaultGuestPolicy: ALWAYS_ACCEPT
                 svgImagesRequired: false

/etc/nginx/sites-available/bigbluebutton (nginx)
                       server name: 192.168.11.186
                              port: 80, [::]:80
                    bbb-client dir: /var/www/bigbluebutton

/var/www/bigbluebutton/client/conf/config.xml (bbb-client)
                Port test (tunnel): rtmp://192.168.11.186
                              red5: 192.168.11.186
              useWebrtcIfAvailable: true

/opt/freeswitch/etc/freeswitch/vars.xml (FreeSWITCH)
                       local_ip_v4: 192.168.11.186
                   external_rtp_ip: stun:stun.freeswitch.org
                   external_sip_ip: stun:stun.freeswitch.org

/opt/freeswitch/etc/freeswitch/sip_profiles/external.xml (FreeSWITCH)
                        ext-rtp-ip: $${local_ip_v4}
                        ext-sip-ip: $${local_ip_v4}
                        ws-binding: :5066
                       wss-binding: :7443

/usr/local/bigbluebutton/core/scripts/bigbluebutton.yml (record and playback)
                     playback_host: 192.168.11.186
                 playback_protocol: http
                            ffmpeg: 4.1.3-0york1~16.04

/etc/bigbluebutton/nginx/sip.nginx (sip.nginx)
                        proxy_pass: 192.168.11.186

/usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml (Kurento SFU)
                        kurento.ip: 192.168.11.186
                       kurento.url: ws://:8888/kurento
                    localIpAddress: 192.168.11.186
               recordScreenSharing: true
                     recordWebcams: true
                  codec_video_main: H264
               codec_video_content: H264

** Potential problems described below **

# Warning: The API demos are installed and accessible from:
#
#    http://192.168.11.186
#
# and
#
#    http://192.168.11.186/demo/demo1.jsp
#
# These API demos allow anyone to access your server without authentication
# to create/manage meetings and recordings. They are for testing purposes only.
# If you are running a production system, remove them by running:
#
#    apt-get purge bbb-demo

2、
**root@ubuntu:/home/ufo# bbb-conf --status**
red5 ——————————————————► [✔ - active]
tomcat7 ———————————————► [✔ - active]
nginx —————————————————► [✔ - active]
freeswitch ————————————► [✔ - active]
redis-server ——————————► [✔ - active]
bbb-apps-akka —————————► [✔ - active]
bbb-transcode-akka ————► [✔ - active]
bbb-fsesl-akka ————————► [✔ - active]
mongod ————————————————► [✔ - active]
bbb-html5 —————————————► [✘ - failed]
bbb-webrtc-sfu ————————► [✔ - active]
kurento-media-server ——► [✔ - active]
bbb-web ———————————————► [✔ - active]

3、
**root@ubuntu:/home/ufo# journalctl -u bbb-html5.service**
-- Logs begin at Wed 2019-05-08 17:18:46 PDT, end at Wed 2019-05-08 19:49:31 PDT
May 08 17:19:06 ubuntu systemd[1]: Started BigBlueButton HTML5 service.
May 08 17:19:06 ubuntu systemd_start.sh[1419]: transparent_hugepage/enabled set 
May 08 17:19:06 ubuntu systemd_start.sh[1419]: transparent_hugepage/defrag set t
May 08 17:19:07 ubuntu systemd_start.sh[1419]: Starting mongoDB
May 08 17:19:16 ubuntu systemd_start.sh[1419]: Mongo started
May 08 17:19:16 ubuntu systemd_start.sh[1419]: Initializing replicaset
May 08 17:19:21 ubuntu systemd_start.sh[1419]: MongoDB shell version v3.4.20
May 08 17:19:23 ubuntu systemd_start.sh[1419]: connecting to: mongodb://127.0.1.
May 08 17:19:23 ubuntu systemd_start.sh[1419]: MongoDB server version: 3.4.20
May 08 17:19:23 ubuntu systemd_start.sh[1419]: { "ok" : 1 }
May 08 17:19:23 ubuntu systemd_start.sh[1419]: Waiting to become a master
May 08 17:19:26 ubuntu systemd_start.sh[1419]: I'm the master!
May 08 17:19:18 ubuntu systemd_start.sh[1419]: module.js:540
May 08 17:19:18 ubuntu systemd_start.sh[1419]:     throw err;
May 08 17:19:18 ubuntu systemd_start.sh[1419]:     ^
May 08 17:19:18 ubuntu systemd_start.sh[1419]: Error: Cannot find module 'fibers
May 08 17:19:18 ubuntu systemd_start.sh[1419]:     at Function.Module._resolveFi
May 08 17:19:18 ubuntu systemd_start.sh[1419]:     at Function.Module._load (mod
May 08 17:19:18 ubuntu systemd_start.sh[1419]:     at Module.require (module.js:
May 08 17:19:18 ubuntu systemd_start.sh[1419]:     at require (internal/module.j
May 08 17:19:18 ubuntu systemd_start.sh[1419]:     at Object.<anonymous> (/usr/s
May 08 17:19:18 ubuntu systemd_start.sh[1419]:     at Module._compile (module.js
May 08 17:19:18 ubuntu systemd_start.sh[1419]:     at Object.Module._extensions.
May 08 17:19:18 ubuntu systemd_start.sh[1419]:     at Module.load (module.js:556
May 08 17:19:18 ubuntu systemd_start.sh[1419]:     at tryModuleLoad (module.js:4
May 08 17:19:18 ubuntu systemd_start.sh[1419]:     at Function.Module._load (mod
May 08 17:19:18 ubuntu systemd[1]: bbb-html5.service: Main process exited, code=
May 08 17:19:18 ubuntu systemd[1]: bbb-html5.service: Unit entered failed state.
May 08 17:19:18 ubuntu systemd[1]: bbb-html5.service: Failed with result 'exit-c
May 08 17:39:50 ubuntu systemd[1]: Stopped BigBlueButton HTML5 service.
May 08 17:39:56 ubuntu systemd[1]: Started BigBlueButton HTML5 service.

4、
**root@ubuntu:/home/ufo# sudo apt-get install bbb-html5**
Reading package lists... Done
Building dependency tree       
Reading state information... Done
bbb-html5 is already the newest version (1:2.0.0-486).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

of course ,  i wang to running Localization。So I don't have SSL

**Comment by ffdixon** [comment]
> Error: Cannot find module 'fibers

The error message looks a bit cut off.  How did you install BigBlueButton (documentation or using `bbb-install.sh`)?

Did you get any errors during installation?

**Comment by ishangxue** [comment]
thank you
i using bbb-install.sh    
However, when nodejs and mongodb was installed in China, the network was very slow, so the source was changed to Alibaba.

**Comment by ishangxue** [comment]
> > Error: Cannot find module 'fibers
> 
> The error message looks a bit cut off. How did you install BigBlueButton (documentation or using `bbb-install.sh`)?
> 
> Did you get any errors during installation?

thank you
i using bbb-install.sh
However, when nodejs and mongodb was installed in China, the network was very slow, so the source was changed to Alibaba.

**Comment by ffdixon** [comment]
> However, when nodejs and mongodb was installed in China, the network was very slow, so the source was changed to Alibaba.

Unfortunately, we can't help you with this issue.  We have tested the install script many times and it works, but the server does need to be able to connect to the package repositories and download the packages.

**Comment by capilkey** [comment]
In this case the unofficial npm repository seems to be missing modules and it results in a failure because they can't be downloaded. It's not something we can test nor can we debug it.

**Comment by ishangxue** [comment]
> > 然而，当在中国安装nodejs和mongodb时，网络速度很慢，因此源代码更改为阿里巴巴。
> 
> 很遗憾，我们无法帮助您解决此问题。我们已多次测试安装脚本并且它可以工作，但服务器确实需要能够连接到软件包存储库并下载软件包。

Ok, still thank you for your help. I'll go and try some other way.

**Comment by ishangxue** [comment]
> 在这种情况下，非官方的npm存储库似乎缺少模块，并且由于无法下载而导致失败。这不是我们可以测试的东西，也不能调试它。

Ok, still thank you for your help. I'll go and try some other way.

**Comment by GhaziTriki** [comment]
@ishangxue Did you get this error during install `The following signatures couldn't be verified because the public key is not available: NO_PUBKEY E074D16EB6FF4DE3`?

**Comment by antobinary** [comment]
This may be solved once we have #7423

**Comment by ishangxue** [comment]
> @ishangxue Did you get this error during install `The following signatures couldn't be verified because the public key is not available: NO_PUBKEY E074D16EB6FF4DE3`?

No, I didn't see the similar information. Now I try to over the wall, but the effect is not ideal.

**Comment by ishangxue** [comment]
> > However, when nodejs and mongodb was installed in China, the network was very slow, so the source was changed to Alibaba.
> 
> Unfortunately, we can't help you with this issue. We have tested the install script many times and it works, but the server does need to be able to connect to the package repositories and download the packages.

Hello after repeated installation test, found html5-client it cannot be started, the lack of function because of nodejs installation error, can you send nodejs version and download address and NPM released version and download address. I think through the browser to download and install.

**Comment by ffdixon** [comment]
I just checked one of our test servers -- here are the version installed

~~~
$ dpkg -l | grep bbb-html5
ii  bbb-html5   1:2.2.0-418           amd64 The HTML5 components for BigBlueButton
$ dpkg -l | grep nodejs
ii  nodejs      8.16.0-1nodesource1   amd64 Node.js event-based server-side javascript engine
~~~

Does this match yours?

**Comment by ishangxue** [comment]
> I just checked one of our test servers -- here are the version installed
> 
> ```
> $ dpkg -l | grep bbb-html5
> ii  bbb-html5   1:2.2.0-418           amd64 The HTML5 components for BigBlueButton
> $ dpkg -l | grep nodejs
> ii  nodejs      8.16.0-1nodesource1   amd64 Node.js event-based server-side javascript engine
> ```
> 
> Does this match yours?

Thank you I have successfully installed and run. Thank you very much.

**Comment by lucky-luuke** [comment]
I have th same Problem. Please look at issue #2645.
What is the solution for this problem?

**Comment by sarfarazsavvy** [comment]
> I just checked one of our test servers -- here are the version installed
> 
> ```
> $ dpkg -l | grep bbb-html5
> ii  bbb-html5   1:2.2.0-418           amd64 The HTML5 components for BigBlueButton
> $ dpkg -l | grep nodejs
> ii  nodejs      8.16.0-1nodesource1   amd64 Node.js event-based server-side javascript engine
> ```
> 
> Does this match yours?

 $dpkg -l | grep bbb-html5
ii  bbb-html5                             1:2.2.0-1157                             amd64        The HTML5 components for BigBlueButton
$dpkg -l | grep nodejs
ii  nodejs                                8.17.0-1nodesource1                      amd64        Node.js event-based server-side javascript engine

Can you let me know how to solve this issue 404 Not Found nginx after click on stat button.
