### ISSUE TITLE
Users list does not show which room the user is connected in 

### ISSUE THREAD

**Issue by akiwenziec** [bigbluebutton/bigbluebutton#7402]
In the HTML5 client the users list does not show/indicate which break out room the user is connected in:

![Screen Shot 2019-05-09 at 10 53 53 AM](https://user-images.githubusercontent.com/18176998/57469941-bf5f6f00-7255-11e9-8926-2d15f256a97d.png)

Previously in the Flash client the users list would show the moderator which breakout room the user was connected to:

![Screen Shot 2019-05-07 at 5 52 19 PM](https://user-images.githubusercontent.com/18176998/57469995-db631080-7255-11e9-86e7-271c6fcec7e7.png)

**Comment by tylercopeland** [comment]
@Tainan404, @ffdixon and I briefly talked about this experience and the best next steps would be to swap the avatar initial with the room number.
