### ISSUE TITLE
When starting a meeting in html5client  I want to hide the chat window.

### ISSUE THREAD

**Issue by ycw7701** [bigbluebutton/bigbluebutton#7406]
Dear developers, 

When starting a meeting in html5client
 I want to hide the chat window.

![1](https://user-images.githubusercontent.com/48506289/57511594-979b0480-7344-11e9-9df2-50a65d6616fa.jpg)

Can you tell me where to fix the source?
Have a good day~~~!

**Comment by antobinary** [comment]
Hi @ycw7701 

Thank you for the good suggestion!
We have something similar in the settings.yml configuration `showParticipantsOnLogin`

Here we check the value and decide on what to display
https://github.com/bigbluebutton/bigbluebutton/blob/b96bbed3a45f8241f3324ad98e368067dc1f0255/bigbluebutton-html5/imports/ui/components/join-handler/component.jsx#L131

From what I just checked if you run `Session.set('openPanel', 'userlist')` in the console after loading the client (in any circumstances) you will get to the view you were aiming for.

We still plan on adding more control over which panels to be open when a user joins but meanwhile you can use the Session.set I mentioned above.

Hope this helps!

**Comment by matiasilva** [comment]
This can be done in 2.2.17 by passing in  `userdata-bbb_show_chat_on_login=false` to the join API call. More info [here](https://github.com/bigbluebutton/bigbluebutton/blob/develop/bigbluebutton-html5/imports/api/users-settings/server/methods/addUserSettings.js).

**Comment by KaranGauswami** [comment]
Documentation Reference : https://docs.bigbluebutton.org/2.2/customize.html#passing-custom-parameters-to-the-client-on-join

**Comment by adnancindioglu** [comment]
for version 2.2.29 
Set Chat-> startClosed: true in settings.yml
