### ISSUE TITLE
Publish poll can cause whiteboard to crash

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#7419]
Repeatedly create and publish poll, not necessarily waiting for votes
![Screenshot from 2019-05-10 13-38-29](https://user-images.githubusercontent.com/6312397/57545632-f5b9ee80-7328-11e9-97c3-091bca3be966.png)

error: CLIENT LOG: Invariant Violation: Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.

**Comment by KDSBrowne** [comment]
I'm still unable to replicate this, Can someone confirm it's still an issue?

**Comment by frank-miller9** [comment]
Yes I can confirm this issue. I got the error: 

```inified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.```

I could sometimes recover it by loading a new presentation, but not always.

**Comment by ffdixon** [comment]
@frank-miller9 What version of BigBlueButton are you running when you got the issue?

**Comment by frank-miller9** [comment]
It was yesterday with 2.2.5

**Comment by ffdixon** [comment]
Can you take a moment and let us know if you can reproduce on https://test.bigbluebuttton.org/.  

Also, recommend updating to https://github.com/bigbluebutton/bigbluebutton/releases/tag/v2.2.6

**Comment by frank-miller9** [comment]
Hello @ffdixon thank you for your answer.

it seems, that the error can also happen on the test instance: https://groups.google.com/forum/#!searchin/bigbluebutton-dev/poll$20185%7Csort:date/bigbluebutton-dev/7Y9TnKeL90I/iAK_mCVbBAAJ

TBH I could not reproduce the issue on the test system, but it's a complete different scenario... When the error happened, we had ~15 users in the conference and it was running for a few hours already. So it's hard to setup the same parameters in the test environment.

**Comment by kinimodmeyer** [comment]
today we had the same problem with ~50 users.

**Comment by Bhargesh11** [comment]
We are having a similar problem on BigBlueButton 2.2.3 
How can we fix this problem?

**Comment by matiasilva** [comment]
See if you can reproduce the error in the test links above and if so update your BigBlueButton server. It's recommended to do so anyway to make sure you're running the latest version with potential security fixes.

**Comment by antobinary** [comment]
Unable to reproduce this on 2.3
