### ISSUE TITLE
Localise poll answers

### ISSUE THREAD

**Issue by GhaziTriki** [bigbluebutton/bigbluebutton#7425]
The poll answers are not localised.

![image](https://user-images.githubusercontent.com/4991088/57573064-ba97e800-741a-11e9-9f54-9753931515dd.png)

![image](https://user-images.githubusercontent.com/4991088/57573066-bcfa4200-741a-11e9-99ec-6d9a5d8e9dce.png)

**Comment by GhaziTriki** [comment]
An easy way to do this is to have only 1 function to create polls, the one for custom polls. If we create a Yes/No poll it will create a customer poll with (Oui/Non) for French as an example. I don't know if it impacts other components.

**Comment by antobinary** [comment]
Is this a duplicate of https://github.com/bigbluebutton/bigbluebutton/issues/7379 ?

**Comment by capilkey** [comment]
This proposes a different solution, but same core problem.
