### ISSUE TITLE
Biggest text size tool bigger than its container

### ISSUE THREAD

**Issue by GhaziTriki** [bigbluebutton/bigbluebutton#7426]
![image](https://user-images.githubusercontent.com/4991088/57573168-8b35ab00-741b-11e9-9f76-fb2a5b7524f6.png)

**Comment by tylercopeland** [comment]
@GhaziTriki a simple approach to this would be to remove the 36px value since it's only 4px greater than the option before and the 32px value stays within the container of the whiteboard control. cc @antobinary.

**Comment by JustinMogel** [comment]
this is still a thing in 2.3-beta-1 (1511)
