### ISSUE TITLE
Download webM file from fullscren fails

### ISSUE THREAD

**Issue by mjencabh** [bigbluebutton/bigbluebutton#7430]
just made a brand new ubuntu 16.04 server with clean instal with html5 only 224-beta.
config Moodle to talk with it. When im trying to wiev recordings it only shows the video of shared pdf/screen in normal window however when toggle fullscreen it gets all white and this make the save video .webm file to show as blank aswell. :( Hope this gets fixed soon.
#keepupthegoodwork

**Comment by ffdixon** [comment]
Hmm ... could you send a link to your recording at ffdixon .at. bigbluebutton .dot. org.  We'd like to take a closer look at it.

**Comment by mjencabh** [comment]
Sure sending it now!

**Comment by ffdixon** [comment]
Can you resend with subject "webM File" -- thanks.

**Comment by pedrobmarin** [comment]
This looks like an UX issue the old playback had. Things done different in https://github.com/bigbluebutton/bbb-playback
