### ISSUE TITLE
Sharing your screen while YouTube is playing causes issues

### ISSUE THREAD

**Issue by capilkey** [bigbluebutton/bigbluebutton#7439]
If you start sharing your screen while a YouTube video is playing the meeting can get into a bad state. 

Steps to reproduce:
1, Share a YouTube video
2. Start sharing your screen
3. Stop sharing your screen
4. Stop sharing the YouTube video

Expected result:
The presentation should be shown and it should be possible to share your screen again.

Actual result:
Continuous spinning arrows as the client tries to connect to a non-existent screen share. The screen share action button will also be permanently blue and clicking it will play the "stop sharing" audio notification every time it's clicked.

Once the meeting is in this bad state, the only way to recover is to make someone else presenter and then take presenter back.

Originally reported here, https://groups.google.com/forum/#!topic/bigbluebutton-dev/vXHGoN0Jb3I

**Comment by JustinMogel** [comment]
this issue seems to not exist anymore. tested this on 2.3-alpha-8 (1511) with Firefox 87.0 on Windows
at step 2 it automatically stopped sharing the video. And with step 3 i returned to the uploaded presentation
