### ISSUE TITLE
bbb-record --list throws an error

### ISSUE THREAD

**Issue by codegeek1001** [bigbluebutton/bigbluebutton#7444]
**Summary**
I have installed 2.2-beta-6 version of BBB and also installed greenlight on top. When I run a meeting through greenlight room and record it, I then come back to command line and see the following error when running bbb-record --list

~/greenlight# bbb-record --list 
Internal MeetingID                                               Time                APVD APVDE RAS Slides Processed            Published           External MeetingID
------------------------------------------------------  ---------------------------- ---- ----- --- ------ -------------------- ------------------  -------------------
a9467a70a5d134eb8d2535694e958ca556727284-1557900248752  Wed May 15 02:04:08 EDT 2019 XX         X        6 
183f0bf3a0982a127bdb8161e0c44eb696b3e75c-1557899200850  Wed May 15 01:46:40 EDT 2019 XX   XXXXX          6                      presentation        Demo Meeting
1f14b44ee3c3f8b5ddd7f464d9ff35bd4285a617-1557899125360  Wed May 15 01:45:25 EDT 2019  X    XX X          6                                          068b975cb4f0b5778b809cd691a9427ea33b1ac9

--
NEXT                         LEFT     LAST                         PASSED   UNIT                  ACTIVATES
Wed 2019-05-15 02:06:47 EDT  29s left Wed 2019-05-15 02:06:17 EDT  43ms ago bbb-record-core.timer bbb-record-core.target

1 timers listed.
--
* bbb-rap-archive-worker.service - BigBlueButton recording and playback archive worker
   Loaded: loaded (/usr/lib/systemd/system/bbb-rap-archive-worker.service; static; vendor preset: enabled)
   Active: active (running) since Wed 2019-05-15 02:06:17 EDT; 16ms ago
 Main PID: 29889 (rap-archive-wor)
   CGroup: /bbb_record_core.slice/bbb-rap-archive-worker.service
           `-29889 /usr/bin/ruby /usr/local/bigbluebutton/core/scripts/rap-archive-worker.rb

May 15 02:06:17 abacwebinars systemd[1]: Started BigBlueButton recording and playback archive worker.

* bbb-rap-sanity-worker.service - BigBlueButton recording and playback sanity check worker
   Loaded: loaded (/usr/lib/systemd/system/bbb-rap-sanity-worker.service; static; vendor preset: enabled)
   Active: inactive (dead) since Wed 2019-05-15 01:49:27 EDT; 16min ago
Condition: start condition failed at Wed 2019-05-15 02:06:17 EDT; 18ms ago
           ConditionPathExistsGlob=/var/bigbluebutton/recording/status/archived/*.done was not met
  Process: 28865 ExecStart=/usr/local/bigbluebutton/core/scripts/rap-sanity-worker.rb (code=exited, status=0/SUCCESS)
 Main PID: 28865 (code=exited, status=0/SUCCESS)

May 15 01:49:27 mywebinars systemd[1]: Started BigBlueButton recording and playback sanity check worker.

* bbb-rap-process-worker.service - BigBlueButton recording and playback process worker
   Loaded: loaded (/usr/lib/systemd/system/bbb-rap-process-worker.service; static; vendor preset: enabled)
   Active: inactive (dead) since Wed 2019-05-15 01:50:36 EDT; 15min ago
Condition: start condition failed at Wed 2019-05-15 02:06:17 EDT; 56ms ago
           ConditionPathExistsGlob=/var/bigbluebutton/recording/status/sanity/*.done was not met
  Process: 28890 ExecStart=/usr/local/bigbluebutton/core/scripts/rap-process-worker.rb (code=exited, status=0/SUCCESS)
 Main PID: 28890 (code=exited, status=0/SUCCESS)

May 15 01:50:02 mywebinars systemd[1]: Started BigBlueButton recording and playback process worker.

* bbb-rap-publish-worker.service - BigBlueButton recording and playback publish worker
   Loaded: loaded (/usr/lib/systemd/system/bbb-rap-publish-worker.service; static; vendor preset: enabled)
   Active: inactive (dead) since Wed 2019-05-15 01:51:07 EDT; 15min ago
Condition: start condition failed at Wed 2019-05-15 02:06:17 EDT; 23ms ago
           ConditionPathExistsGlob=/var/bigbluebutton/recording/status/processed/*.done was not met
  Process: 29239 ExecStart=/usr/local/bigbluebutton/core/scripts/rap-publish-worker.rb (code=exited, status=0/SUCCESS)
 Main PID: 29239 (code=exited, status=0/SUCCESS)

May 15 01:51:06 mywebinars systemd[1]: Started BigBlueButton recording and playback publish worker.

**Comment by capilkey** [comment]
I don't see any errors in that output. The workers aren't running right now, but the output shows that they processed a recording 15 minutes ago and are waiting for another before starting again.

**Comment by matiasilva** [comment]
Closed due to inactivity.

**Comment by farsad2020** [comment]
Hi
I have problem like that
but for a week dead service and some record stay on process and donot publish

![image](https://user-images.githubusercontent.com/66263484/104424424-9ba90c00-5594-11eb-9d26-b041775bb957.png)
 please Help..!!
