### ISSUE TITLE
Behaviour of create API call no longer matches docs (attendeePW / moderatorPW)

### ISSUE THREAD

**Issue by kepstin** [bigbluebutton/bigbluebutton#7448]
The docs say:

Param Name | Required/Optional | Type | Description
--- | --- | --- | ---
attendeePW | Required | String | The password that will be required  for attendees to join the meeting. This is optional, and if not  supplied, BigBlueButton will assign a random password.
moderatorPW | Required | String | The password that will be required  for moderators to join the meeting or for certain administrative actions  (i.e. ending a meeting). This is optional, and if not supplied,  BigBlueButton will assign a random password (which will be returned in  the create response).

Although it is marked 'Required', that seems to be an oversight - since the docs explicitly say "This is optional, and if not supplied, BigBlueButton will assign a random password"

I have existing tools that rely on the automatic password generation behaviour, and I suspect others might as well.

**Comment by pedrobmarin** [comment]
Seems resolved

| Param Name                         | Required / Optional     | Type                                                                                                                                                                        | Description                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
|:---------------------------------- |:----------------------- |:--------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |:------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| attendeePW                         | Optional (recommended)  | String                                                                                                                                                                      | The password that the [join](#join) URL can later provide as its `password` parameter to indicate the user will join as a viewer.  If no `attendeePW` is provided, the `create` call will return a randomly generated `attendeePW` password for the meeting.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |
| moderatorPW                        | Optional (recommended)  | String                                                                                                                                                                      | The password that will [join](#join) URL can later provide as its `password` parameter to indicate the user will as a moderator.  if no `moderatorPW` is provided, `create` will return a randomly generated `moderatorPW` password for the meeting.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
