### ISSUE TITLE
2.2beta screenshare close sound load, appears in recordings.

### ISSUE THREAD

**Issue by hostbbb** [bigbluebutton/bigbluebutton#7450]
When you close deskshare in html5 client, a loud noise is heard/  this noise appears in recordings since its level triggers noise gate.

suggest a lower tone if any.

**Comment by ffdixon** [comment]
Agreed -- it's a bit too loud.

**Comment by JustinMogel** [comment]
tested this on 2.3-beta-1 (1511) 
ending screenshare does not make a sound. So i think this issue can be closed.

**Comment by prlanzarin** [comment]
Stale. The sound was changed to a _click_.
