### ISSUE TITLE
[Feature] Show users list only for moderators

### ISSUE THREAD

**Issue by Mr4enuT** [bigbluebutton/bigbluebutton#7459]
In some cases, we need to hide the number of users and users list for attendees and make it visible only for moderators. One of the goals is to prevent any actions between them except the moderator. Currently, Adobe Connect has a similar feature.

**Comment by atar3d** [comment]
I also support this view, Very common use case on my servers.
as far as I know similar feature is found in most well known systems.

**Comment by ffdixon** [comment]
We would suggest a modification of this -- all users would see the Users list, but viewers would not see each other.

That way, they could still initiate a private chat with a moderator, but they could not initiate a private chat with other viewers.

**Comment by Jossef-767** [comment]
precisely, that's the idea. 
in my view, this relatively small modification will open bigbluebutton to a  wide new user base.

**Comment by ffdixon** [comment]
Merged into https://github.com/bigbluebutton/bigbluebutton/issues/7099
