### ISSUE TITLE
Support translations for webcam quality strings

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#7467]
![image](https://user-images.githubusercontent.com/290351/57982293-6a6be780-7a11-11e9-92f6-734007d62966.png)

Reported in https://groups.google.com/d/msg/bigbluebutton-dev/oXJhCN58m34/UN8PI9eEAgAJ

**Comment by capilkey** [comment]
This was one of the things I didn't have time to get to. The way to do it would be to use the profile "id" to look up a string and see if it exists. If a string is found then use it, but if a string isn't found then use the name from the settings.

**Comment by prlanzarin** [comment]
Fixed in https://github.com/bigbluebutton/bigbluebutton/pull/10280
