### ISSUE TITLE
Change default webcam quality

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#7468]
Reported in https://groups.google.com/d/msg/bigbluebutton-dev/oXJhCN58m34/UN8PI9eEAgAJ

**Comment by capilkey** [comment]
The default can already be changed by adjusting the "default" property on the profiles. https://github.com/bigbluebutton/bigbluebutton/blob/master/bigbluebutton-html5/private/config/settings.yml#L107
