### ISSUE TITLE
comments and docs out of date / broken

### ISSUE THREAD

**Issue by Shaltz** [bigbluebutton/bigbluebutton#7469]
all the docs related to the 2.2 version of bbb or the 2.0 version of greenlight are out of date / broken...

if you edit (for instance) the greenlight's env file, and try to hit the docs related to LDAP :
http://docs.bigbluebutton.org/install/greenlight-v2.html#ldap-auth

or even just :
https://docs.bigbluebutton.org/install/greenlight-v2.html

you'll end up with page not found.... it happens with ALL the doc related to bbb-2.2 or gl-2.0

**Comment by ffdixon** [comment]
Your right -- we've split the Green Light docs a few days ago into four sections and have a few broken links.  Will fix and update this issue.

**Comment by Shaltz** [comment]
thanks for your update ;)

**Comment by ffdixon** [comment]
Can you check them again.  Don't hesitate to let us know if you find any more errors (much appreciated).

**Comment by matiasilva** [comment]
Closed due to inactivity (great work!)
