### ISSUE TITLE
Moderator should be able to mute/unmute user while mic is locked

### ISSUE THREAD

**Issue by GhaziTriki** [bigbluebutton/bigbluebutton#7473]
The Moderator should be able to mute/unmute normal users, while the lock prevents them from unmuting themselves, the moderator can give the mic to students one by one.

**Comment by capilkey** [comment]
Moderators can already lock viewers at any time. The Moderator being able to unlock falls under the `allowModsToUnmuteUsers` property and I don't think we'd want a special case here. https://github.com/bigbluebutton/bigbluebutton/blob/master/bigbluebutton-web/grails-app/conf/bigbluebutton.properties#L194-L196

**Comment by secretreal26** [comment]
Hi,
But when lock is open moderator can not unmute them.  Lock is prevent unmuting.. Am I wrong ?

**Comment by GhaziTriki** [comment]
I missed the `allowModsToUnmuteUsers` configuration property. Thank you @capilkey

**Comment by secretreal26** [comment]
Hi,

Sorry @capilkey but as moderator I try to unmute user but same time mute again ( room restriction prevent to change? )

I looked my bigbluebutton.properties 
allowModsToUnmuteUsers=true

Am I miss something ?

Thanks for help,
