### ISSUE TITLE
Embed in website

### ISSUE THREAD

**Issue by dahalday** [bigbluebutton/bigbluebutton#7475]
Good Team

Thanks for the good work. Just wondered if there is a way to allow recordings playback access only from the Moodle or Greenlight URL. IE the option the link recording play to particular website like Vimeo pro. 

As it is even unlisted recordings can be played once the link is copied and pasted into a browser independent of the of the original URL. 

Kind Regards
DH

**Comment by matiasilva** [comment]
See #1969.
