### ISSUE TITLE
bbb-web not able to download default presentation with non latin characters

### ISSUE THREAD

**Issue by GhaziTriki** [bigbluebutton/bigbluebutton#7479]
We assume we have `beans.presentationService.defaultUploadedPresentation=${bigbluebutton.web.serverURL}/مرحبا بكم.pdf`

`bbb-web` is not able to download the file
We see this error `2019-05-22T10:02:32.377+02:00 ERROR o.b.p.PresentationUrlDownloadService - Invalid HTTP response=[404] for url=[http://*******/ÙØ¬ÙØ¹ÙØ© Ø§ÙÙØ±ÙØ§Ù.pdf] with meeting[183f0bf3a0982a127bdb8161e0c44eb696b3e75c-1558512151549]`

**Comment by GhaziTriki** [comment]
@csaragosti Can you please try this

```bash
sudo apt-get install -y openjdk-8-jdk-headless
sudo native2ascii "/usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties" "/usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties"
sudo bbb-conf --restart
```

**Comment by prlanzarin** [comment]
Merging with #8433 (which is the root issue).
