### ISSUE TITLE
Autocomplete feature for slide selector

### ISSUE THREAD

**Issue by GhaziTriki** [bigbluebutton/bigbluebutton#7480]
If we have a long list it would be easier to type the number of the slide.

![image](https://user-images.githubusercontent.com/4991088/58158500-3c8dd980-7c83-11e9-916d-50cf283ca921.png)

**Comment by ffdixon** [comment]
A better solution would to bring back the ability to visually select the current slide.

Here is a mock up that shows Slide 12 as the current slide.  The presenter could click on the thumbnail of another slide to switch to that slide.

![html5-presention](https://user-images.githubusercontent.com/290351/58382290-90a40100-7f96-11e9-9cae-0febb58ad4c2.png)

**Comment by GhaziTriki** [comment]
The mockup works well. However, it would be nice to add a visual indicator at the top right corner of each thumbnail to show the slide number.

**Comment by capilkey** [comment]
Numbers would definitely be good. Need to have space for a scrollbar also.

![image](https://user-images.githubusercontent.com/1395090/58573659-34e2ad80-820c-11e9-8840-c7c7a281ac79.png)
