### ISSUE TITLE
Add a button to hide the presentation for viewers

### ISSUE THREAD

**Issue by GhaziTriki** [bigbluebutton/bigbluebutton#7481]
A use case where the teacher would test the memorisation of the student, the teacher would like to hide the presentation for a while.

**Comment by sulzer** [comment]
Yes or just for a webcam only meeting.  It would be easier to hide the presentation for all viewers instead having to explain them that they need to minimize the presentation.

**Comment by prlanzarin** [comment]
@GhaziTriki can't this be considered a duplicate of https://github.com/bigbluebutton/bigbluebutton/issues/7987?

**Comment by prlanzarin** [comment]
Grace period has expired, I'm merging this with #7987 which is the meta/root issue.
