### ISSUE TITLE
jar files expired (bbb-apps-screenshare)

### ISSUE THREAD

**Issue by consurity** [bigbluebutton/bigbluebutton#7487]
Found out that the screensharing on our BBB server is not working anymore since yesterday (22/05/2019)

This happened somewhere end of 2017 (10/2017 to 11/2017) as well. At that moment, new jars were pushed and a package upgrade on the VM fixed the issue. 

See also : https://github.com/bigbluebutton/bigbluebutton/commit/116d8793cfc9bfd2aac5d4d6f3abda9c9a08daf0

Can this be fixed again?

![image](https://user-images.githubusercontent.com/45563188/58246498-821bd680-7d57-11e9-82c6-ce4441678c01.png)

**Comment by ffdixon** [comment]
We are very close to releasing new Jars with an updated certificate for BigBlueButton 2.0.   Once we do screen sharing will work again with the Java Applet.

However, you are running a very old version of BigBlueButton (Released in May 2017).  Is it an option for you to upgrade to the latest version of BigBlueButton 2.2-beta, which has a pure HTML5 client and doesn't require Java anymore to do screen sharing?

**Comment by consurity** [comment]
Hi ffdixon, thanks for the update. Looking forward.

We are in the progress migrating to the new BBB server, but still have some actions left. So we can't force an emergency migration yet...

**Comment by ffdixon** [comment]
Understood.  We're finding that the process to obtain a new code signing certificate is a bit more onerous that it was two years ago.  We should have the new certificate in place before May 31..

**Comment by consurity** [comment]
Just to be 100% sure, will you update the bbb-apps-screenshare 1:1.1.0-44 package as well? As we are running 1.x and not 2.x.

**Comment by ffdixon** [comment]
We'll try (no promises).  That release is two years old and you really want to be looking at getting on the latest version of BigBlueButton -- ideally the 2.2-beta release as it doesn't require Flash or Java anymore.

**Comment by safonovpro** [comment]
> We should have the new certificate in place before May 31.

Hi! Did you get the new certificate?

**Comment by consurity** [comment]
I don't see an update so I guess it's still a pending action.

Further working on migrating to the new version in meanwhile but we are not yet there...

**Comment by ffdixon** [comment]
Were working on updating the packaging.  We have the updated JARS ready, and for now you can download them from

  https://test.bigbluebutton.org/svc2.tar.gz

and use these files to overwrite the existing files in

 /var/lib/red5/webapps/screenshare/lib/*.jar

**Comment by consurity** [comment]
Working well! Thanks!

**Comment by safonovpro** [comment]
Thanks a lot!
