### ISSUE TITLE
User Limit bug generates participants error with too few users & continuously returns errors

### ISSUE THREAD

**Issue by GGreen28** [bigbluebutton/bigbluebutton#7490]
**Issue**: applying a User limit: "1" setting for a BigBlueButton room generates the following error message, and does not allow a single user or moderator to enter the room. 

BigBlueButton responded with errors.
The number of participants allowed for this meeting has been reached.
More information about this error -->(https://docs.moodle.org/35/en/error/bigbluebuttonbn/view_error_bigbluebutton)

Setting a user limit of "2" to begin with allows a user to join. 

Setting a user limit of "1" and attempting to join fails, and subsequent adjustments increasing the user limit continue to also fail. 

**Is Reproducible**: Yes

**Steps to Reproduce**:

Setting a user limit of "2" to begin with allows a user to join. 

Create a different BBB Room, set the user limit to 1. observe the above error message. increase the user limit and attempt to join - error message. increasing this user limit to any number continues to generate the error message above. 

**Notes:** See screenshots below for console information

Imposing a "1" User limit returns the following error:

BigBlueButton responded with errors.
The number of participants allowed for this meeting has been reached.
More information about this error -->(https://docs.moodle.org/35/en/error/bigbluebuttonbn/view_error_bigbluebutton)

Testing with a "2" User limit allows for a single user to participate in the room, with a second individual attempting to join the room receiving the exact same error message above. 

The Console indicates an attempt (and failure) to join a room, which creates and leaves an internal meetingid, but not an external meetingid. Could this be causing the limitation of the room to be inaccurate? This issue was not seen in the previous, flash-based version of BBB. 

![205E0193](https://user-images.githubusercontent.com/50883655/58260008-b5546a80-7d43-11e9-8e65-ac3dd2a16659.PNG)
![74A1655A](https://user-images.githubusercontent.com/50883655/58260009-b5546a80-7d43-11e9-909f-7e50a462644a.PNG)
![BBB](https://user-images.githubusercontent.com/50883655/58260056-c43b1d00-7d43-11e9-8860-18f769c572c1.png)

**Comment by pedrobmarin** [comment]
Hopefully fixed in https://github.com/bigbluebutton/bigbluebutton/pull/10542
