### ISSUE TITLE
sending private chat crash the receiving client

### ISSUE THREAD

**Issue by Jossef-767** [bigbluebutton/bigbluebutton#7504]
tested html5 on test.bigbluebutton.org,

**Comment by capilkey** [comment]
Can you give steps to reproduce? I just tried a bunch of different combinations of moderators, viewers, and private chat lock, but I couldn't get anything ejection or crash. If it's crashing to a blank blue screen could you look in the browser console for the error and paste it here.

**Comment by Jossef-767** [comment]
Now it works well without problems,
The only difference is that Chrome was updated yesterday to version 74.0.3729.169 32bit (on win7).
Two days ago, in a random check, Each private chat sending created a black screen (only black background without any notification,)  only on the receiving side.  It was consistent.
As far as I can remember browser console show error, something about "id utility"

**Comment by ffdixon** [comment]
Thanks for testing again.
