### ISSUE TITLE
If I click the mute button on the video to disable the participants and cancel the mute, I will quit the application

### ISSUE THREAD

**Issue by caojincool** [bigbluebutton/bigbluebutton#7505]
![image](https://user-images.githubusercontent.com/466750/58393831-0382aa00-8073-11e9-8dc5-d68b029b481b.png)

![image](https://user-images.githubusercontent.com/466750/58393718-7a6b7300-8072-11e9-961c-33b7fc2333d9.png)

**Comment by ffdixon** [comment]
It looks like this is on the Flash version of BigBlueButton.  Can you try and reproduce it on https://test.bigbluebutton.org/ using the HTML5 version of BigBlueButton.

We would recommend setting up the HTML5 version of BigBlueButton in 2.2-beta, see

  http://docs.bigbluebutton.org/2.2/install.html
