### ISSUE TITLE
Error 1108: ICE connection failed when sharing screen

### ISSUE THREAD

**Issue by liuboren0617** [bigbluebutton/bigbluebutton#7506]
bigbluebutton 2.0&html5&firefox

![image](https://user-images.githubusercontent.com/39522484/58405706-a7cc1700-809a-11e9-9bb1-94368c38a2e2.png)

log:

May 27 01:03:15 ubuntu systemd_start.sh[11720]:  sessionToken=27kwnfzpl6vib3kb, meetingId=183f0bf3a0982a127bdb8161e0c44eb696b3e75c-1558944162731, requesterUserId=w_v7thwvmsjd3i, fullname=hm, confname=Demo Meeting, externUserID=w_v7thwvmsjd3i, validUser=valid
May 27 01:03:15 ubuntu systemd_start.sh[11720]: #033[31merror#033[39m: CLIENT LOG: [screenshare] WebRtcPeerSendonly constructor error:
May 27 01:03:15 ubuntu systemd_start.sh[11720]:  sessionToken=27kwnfzpl6vib3kb, meetingId=183f0bf3a0982a127bdb8161e0c44eb696b3e75c-1558944162731, requesterUserId=w_v7thwvmsjd3i, fullname=hm, confname=Demo Meeting, externUserID=w_v7thwvmsjd3i, validUser=valid
May 27 01:03:15 ubuntu bbb-webrtc-sfu[11776]: 2019-05-27T08:03:15.778Z - #033[32minfo#033[39m: [WebsocketConnectionManager] Closed connection on [2]
May 27 01:03:15 ubuntu systemd_start.sh[11720]: #033[31merror#033[39m: CLIENT LOG: The request is not allowed by the user agent or the platform in the current context.
May 27 01:03:15 ubuntu systemd_start.sh[11720]:  sessionToken=27kwnfzpl6vib3kb, meetingId=183f0bf3a0982a127bdb8161e0c44eb696b3e75c-1558944162731, requesterUserId=w_v7thwv

May 27 01:03:15 ubuntu systemd_start.sh[11720]:  sessionToken=27kwnfzpl6vib3kb, meetingId=183f0bf3a0982a127bdb8161e0c44eb696b3e75c-1558944162731, requesterUserId=w_v7thwvmsjd3i, fullname=hm, confname=Demo Meeting, externUserID=w_v7thwvmsjd3i, validUser=valid
May 27 01:03:15 ubuntu systemd_start.sh[11720]: #033[31merror#033[39m: CLIENT LOG: Ice connection state error
May 27 01:03:15 ubuntu systemd_start.sh[11720]:  sessionToken=27kwnfzpl6vib3kb, meetingId=183f0bf3a0982a127bdb8161e0c44eb696b3e75c-1558944162731, requesterUserId=w_v7thwvmsjd3i, fullname=hm, confname=Demo Meeting, externUserID=w_v7thwvmsjd3i, validUser=valid

**Comment by ffdixon** [comment]
All browsers require that for screen sharing to work, the page must load via HTTPS and have a valid SSL certificate.  Can you try it against https://test.bigbluebutton.org/ and let us know if you can share your screen there.

**Comment by liuboren0617** [comment]
> All browsers require that for screen sharing to work, the page must load via HTTPS and have a valid SSL certificate. Can you try it against https://test.bigbluebutton.org/ and let us know if you can share your screen there.


You're right. Official examples can be used. Thank you.

**Comment by ferasmonther** [comment]
i was working on BBB server and all was running well.
suddenly i had the error ICE 1108 when sharing screen.
i use EC2 and all ports are open.
the server was working perfectly fine then suddenly this happened

**Comment by matiasilva** [comment]
Make sure to post in the support mailing list if you require assistance.

**Comment by karstengo** [comment]
same here suddenly it stopped working with error 1108 ICE also it stopped for webcam sharing.

**Comment by matiasilva** [comment]
As indicated above, use the mailing list. Make sure to follow the instructions in the documentation when upgrading, namely that you run bbb-conf --set-ip
