### ISSUE TITLE
[Future] Update network information

### ISSUE THREAD

**Issue by jfsiebel** [bigbluebutton/bigbluebutton#7515]
Currently we only use data from `RTCPeer​Connection​.get​Stats()` to calculate if the user is with a problem in his connection, any packet loss is a reason to warn a user about his network.

Update the logic to consider:
- [ ] Freeswitch information
- [ ] Network Information API (https://caniuse.com/#feat=netinfo)
- [ ] Dynamic thresholds of time or resources
- [ ] Number of webcams

**Comment by Furiouss38** [comment]
Any news on a quality/network indicator ?
With the current situation my bbb is used a lot and sometimes teachers are complaining about sound getting cut or like robots, my server is not at it's maxmum load in terms of system (CPU/RAM) and I don't know if it comes from their connection or my server ?
With an indicator on their side they would maybe see the server is fine

**Comment by jfsiebel** [comment]
Good afternoon @Furiouss38, there is some changes to be reviewed in https://github.com/bigbluebutton/bigbluebutton/pull/8579

**Comment by pedrobmarin** [comment]
@jfsiebel what do you think? Should we close this one?
