### ISSUE TITLE
Exception being thrown when webcams shutdown with an error

### ISSUE THREAD

**Issue by capilkey** [bigbluebutton/bigbluebutton#7518]
My browser is having issues with the webcam sharing. There's a 1020 toast message and "Camera share has not succeeded in 15000" in the browser console. Once that has gone through there's also a exception thrown.

`TypeError: i is undefined a1c1e7a032b242a4d81090c1aaeca7c9060c37b9.js:125:339716`

I tracked it down to the following code block.
https://github.com/bigbluebutton/bigbluebutton/blob/master/bigbluebutton-html5/imports/ui/components/video-provider/component.jsx#L532-L563
```javascript
      this.webRtcPeers[id] = new WebRtcPeerObj(options, (error) => {
        const peer = this.webRtcPeers[id];

        peer.started = false;
```
In this case `peer` is `i`. I also noticed that all other instances where a peer was fetched from webRtcPeers that the return was checked for `if (peer) {}`, but that checking is missing in the above code block.

**Comment by antobinary** [comment]
Merging into #7672
