### ISSUE TITLE
Uploading a file with the same name fails

### ISSUE THREAD

**Issue by capilkey** [bigbluebutton/bigbluebutton#7519]
In order to upload a file the client has to request an upload token. The first upload of a file always works because the client has to wait for the token to come back, but the second upload of a file will always fail because the client fetches a new token and then reuses the previous token.

There needs to be some sort of invalidation of the upload token after it's used once or a unique identifier to differentiate the upload attempts.

**Comment by antobinary** [comment]
Can we merge https://github.com/bigbluebutton/bigbluebutton/issues/6847 into this one?

**Comment by capilkey** [comment]
Yup. It's a duplicate, sorry. The cause can be copied over.
