### ISSUE TITLE
[HTML5]2.2-beta9 "Allow access to your microhone" modal close not working

### ISSUE THREAD

**Issue by vova-zush** [bigbluebutton/bigbluebutton#7521]
![Selection_721](https://user-images.githubusercontent.com/29659152/58483212-93565000-8168-11e9-940a-89a45fbefeda.png)

**Comment by capilkey** [comment]
You need SSL set up to get access to media devices. We can add in extra detection, but that's the cause of your issue.

**Comment by vova-zush** [comment]
Yes, I know about ssl. If press enable mic then modal hide. But I just want to say what close button not working

**Comment by antobinary** [comment]
I am able to reproduce this locally. I will look into resolving it. Thanks @vova-zush for reporting this!
