### ISSUE TITLE
Zooming into a presentation causes the corner buttons to float away

### ISSUE THREAD

**Issue by capilkey** [bigbluebutton/bigbluebutton#7526]
To reproduce have two clients open and zoom into the presentation from the presenter client while watching the non-presenter client. The "minimize presentation" button will float to the side and the download and full screen buttons will disappear. It will happen with landscape or portrait slides and the zoom percentages that cause issues vary. In the example below the problem zoom was 150%, but I also tried with a portrait document and it had a problem with 150% and 175%.

The following GIF is of the non-presenter client's perspective. 
![PresentationButtonFloat](https://user-images.githubusercontent.com/1395090/58503178-1f12b100-8156-11e9-8968-281d435a6148.gif)

**Comment by antobinary** [comment]
Addressed in #7837
