### ISSUE TITLE
WebCam not sharing

### ISSUE THREAD

**Issue by slobox** [bigbluebutton/bigbluebutton#7535]
Hello,

in my installation everything works perfectly except sharing webcam.
Each user sees his camera but the camera of other users is not visible.
I guess the error is in the some settings.
Please help.

Thanks

**Comment by ffdixon** [comment]
A few questions

1.  What version of BigBlueButton are you running?
2.  Did you get any errors on installation?
3.  Did you make any custom changes to the setup (outside of using bbb-conf)?
4.  Can you test against https://demo.bigbluebutton.org/ and let us know if you see the same issue.

**Comment by slobox** [comment]
Hello,
thanks for quick response.
I did a bbb reinstallation(new installation)  on a clean installation of Ubuntu Server 16.04,then I set it up as an default client for opening is html5  and everything worked in the best way.

Thanks
