### ISSUE TITLE
Closed Captions should default to your current language

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#7551]
When a moderator starts closed captioning, instead of asking for language

![image](https://user-images.githubusercontent.com/290351/58773108-da3dae80-8589-11e9-9b39-05172ef64cd2.png)

it should default to the current locale for the user's browser (such as English below)

![image](https://user-images.githubusercontent.com/290351/58773063-b4180e80-8589-11e9-8892-00b5339d9e5e.png)

**Comment by antobinary** [comment]
I disagree here. We use this dialog in 2 spots:
1) when a CC writer is selecting a language to write captions for. This is not necessarily the language the UI is set to.
2) when a CC consumer is picking from owned language options. Typically there's 1-2 options and I don't see value in trying to filter that list

**Comment by antobinary** [comment]
I addressed this as much as possible in 7654 
Closed in #7654
