### ISSUE TITLE
Guest = false avoids user authentication

### ISSUE THREAD

**Issue by pedrobmarin** [bigbluebutton/bigbluebutton#7561]
If `guest=false` is defined at API call, user's session is not marked as authenticated in `bbb-web`

https://github.com/bigbluebutton/bigbluebutton/blob/7b851cbee7daba299056939e95637b405d3ead9f/bigbluebutton-web/grails-app/controllers/org/bigbluebutton/web/controllers/ApiController.groovy#L223-L232

**Comment by capilkey** [comment]
That authenticated property shouldn't be used for any checks to see if the person is allowed to see content.

**Comment by pedrobmarin** [comment]
Is this the same property?
https://github.com/bigbluebutton/bigbluebutton/blob/7b851cbee7daba299056939e95637b405d3ead9f/akka-bbb-apps/src/main/scala/org/bigbluebutton/core/running/HandlerHelpers.scala#L47-L51

**Comment by capilkey** [comment]
Same property. I think it's referred to as "authenticated", "authed", and "auth" in different places. They all mean "authenticated by the front-end" rather than "authorized".

**Comment by pedrobmarin** [comment]
Ok, I'll send a PR to remove checking this when validating the websocket connections to SFU and Etherpad
