### ISSUE TITLE
Issue Mobile Video not working

### ISSUE THREAD

**Issue by rjrushabh** [bigbluebutton/bigbluebutton#7566]
When we are start our demo with few users. after start our demo few users are access through mobile and few users are join demo through web from laptop. but when mobile users join demo video not working.

**Comment by Jossef-767** [comment]
![image](https://user-images.githubusercontent.com/2356928/58854690-b754ec80-86a6-11e9-92f8-991c71a04beb.png)

**Comment by Jossef-767** [comment]
xiaomi-Mi8.  android-9.  chrome.

**Comment by rjrushabh** [comment]
I checked many time it's happens sometime which is weird because don't get exact issue. i have checked in My Mobile Device Samsung Galaxy S7 Edge , Nokia 6.1, even also checked in One plus 1.

**Comment by rjrushabh** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/2356928/58854690-b754ec80-86a6-11e9-92f8-991c71a04beb.png)

Thanks for your quick reply.

**Comment by capilkey** [comment]
There's an issue with the profile scanning where it won't release the previous media and it causes the rest of the calls to fail because the browser thinks it's already using a webcam. It will sometimes clear up if you swap the camera back and forth.

**Comment by rjrushabh** [comment]
> 
> 
> There's an issue with the profile scanning where it won't release the previous media and it causes the rest of the calls to fail because the browser thinks it's already using a webcam. It will sometimes clear up if you swap the camera back and forth.

Thanks Capilkey, I have tried this solution but still there is no solution found. seems my problem occurs sometimes. Don't find any solution if you have any other suggestion please let me know.

**Comment by pedrobmarin** [comment]
How about this one @prlanzarin ?
