### ISSUE TITLE
How to merge some future bbb-html5 from 2.2 to 2.0

### ISSUE THREAD

**Issue by datphamict** [bigbluebutton/bigbluebutton#7567]
Dear all,

How to merge some future bbb-html5 from 2.2 to 2.0

**Comment by ffdixon** [comment]
Not sure what you are asking ... do you want to take the HTML5 client from BigBlueButton 2.2 branch and run it on a BigBlueButton 2.0 server?  

If so, that isn't possible as the server and client are closely coupled.  You would only be able to run a 2.2 client on a 2.2 server.

**Comment by datphamict** [comment]
Dear Fred,

I like GUI of BBB HTML5 2.0 more than BBB HTML5 2.2.

So, i would like to merge "Webcame setting" future from 2.2 to 2.0.

Thanks.

**Comment by ffdixon** [comment]
Is it an option for you to upgrade to BigBlueButton 2.2?  There have been many features (such as breakout rooms, polling, and pan/zoom) as well as stability improvements in both audio and video that are not present in 2.0.

**Comment by datphamict** [comment]
Thank you so much.
