### ISSUE TITLE
Clicking mute/unmute moves the webcam

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#7573]
With the new ability to move webcams, when a webcam is placed in the presentation area, clicking the mute/unmute button causes the location of the webcam to move.

![moving](https://user-images.githubusercontent.com/290351/58968654-65829400-8784-11e9-889c-4a57bc44690b.gif)

**Comment by antobinary** [comment]
Related: 
![jumping-ui](https://user-images.githubusercontent.com/6312397/59223490-0e245f80-8b9a-11e9-92b5-8c8c51567250.gif)

**Comment by antobinary** [comment]
Cannot reproduce after #7589
