### ISSUE TITLE
Minor redraw of HTML5 client

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#7577]
In a session saw a minor jumping in the UI when users were talking.

![tweek](https://user-images.githubusercontent.com/290351/59045956-05a4ef80-884f-11e9-8d4d-fefa9bd47475.gif)

**Comment by JustinMogel** [comment]
i have not encountered this, is this still reproducable?

**Comment by prlanzarin** [comment]
Closing as stale (this was 2.0).
