### ISSUE TITLE
Set default wb tool back to "pan" 

### ISSUE THREAD

**Issue by akiwenziec** [bigbluebutton/bigbluebutton#7587]
The default text tool is resulting in the following user/support issues:

**Recording processing format:**
When the whiteboard or presentation area is not engaged the recording processing will remove the presentation area to process a webcam only playback.

-Because the text tool is selected as the default users are inadvertently making marks on the whiteboard resulting in recordings that are not processed as webcam meetings in the playback. 
-These cannot be reprocessed to achieve the customers' use case for recordings.

**Document navigation:**
Instructors who upload documents and do not make use of the text tools / annotations are also inadvertently marking up their documents attempting to pan while in fit to width mode and are unable to locate the pan tool:

previous issue was opened to have the text tool set as the default because users were not able to find the text tool / text menu:

https://github.com/bigbluebutton/bigbluebutton/issues/4807

suggestions to improve the whiteboard tool bar have also been made:

https://github.com/bigbluebutton/bigbluebutton/issues/6296

Additionally, regardless of what tool is the default the user is still unaware these are menu options:

![Screen Shot 2019-06-07 at 2 32 45 PM](https://user-images.githubusercontent.com/18176998/59125734-3bbaa000-8931-11e9-9fae-8f1b77580b59.png)
![Screen Shot 2019-06-07 at 2 32 51 PM](https://user-images.githubusercontent.com/18176998/59125738-3d846380-8931-11e9-805d-75222e26ca9a.png)

May want to consider improving the visual queues that indicate there is a menu that can be expanded for example photoshop tools have a > or "triangle" indicator:

![Screen Shot 2019-06-07 at 2 35 18 PM](https://user-images.githubusercontent.com/18176998/59125850-7fada500-8931-11e9-9a75-9ffcdbe5ee28.png)

**Comment by tylercopeland** [comment]
@akiwenziec thanks for sharing this feedback. 

@ffdixon and I were discussing possible solutions to this issue and this is where we landed. 

1) Revert back to having the hand tool active by default.
2) Update the tools tooltip to read "More tools". 
3) Add a visual indicator, triangle, like photoshop to indicate more items.
