### ISSUE TITLE
Open source web conferencing software is not easy enough to use for widespread adoption

### ISSUE THREAD

**Issue by bigbluebutton-issue-import** [bigbluebutton/bigbluebutton#759]
Originally reported on Google Code with ID 1

```
What steps will reproduce the problem?

1.  Download any open source web conference software.
2.  Try to install, setup, and deploy.
3.  Invite users
4.  Watch users (but don't give them any training)

What is the expected output? 
  Users are able to use the software without training.  
  Developers are able to easily add their own extensions.  

What do you see instead?
  Managers can stop using WebEx, Placeware, or other commercial offerings.


```

Reported by `ffdixon` on 2008-07-03 13:42:58

**Comment by ffdixon** [comment]
We're getting close with BigBlueButon 1.1-beta, see  http://bigbluebutton.org/2017/01/12/1-1-beta/

**Comment by ffdixon** [comment]
Our project is shifting to a pure HTML5 client and we're getting closer to reaching our goal in this issue.

Here's a video overview of the upcoming HTML5 client: https://www.youtube.com/watch?v=d5v6Uar79Yc

**Comment by ffdixon** [comment]
Getting closer.  We've released a beta of the BigBlueButton HTML5 client that can replace the Flash client.  See

  https://groups.google.com/d/msg/bigbluebutton-dev/34SphncjKEw/KJZsbQbEAQAJ


No Flash, no Java, no extensions, and no downloadable plugins needed.

It's pure HTML5.

**Comment by ffdixon** [comment]
We've been doing steady updates to the HTML5 client in BigBlueButton 2.2-beta.  You can try it out at https://demo.bigbluebutton.org/.

**Comment by matiasilva** [comment]
I'd say this goal has been achieved judging by the amount of successful installations over the last few months by complete beginners :-)

**Comment by ffdixon** [comment]
Thanks Matias -- we're definitely getting there.  We're now on BigBlueButton 2.2.26 and with each update it's looking more solid.

**Comment by SAEmam4444** [comment]
چی میگید شما ها

**Comment by l3d00m** [comment]
> I'd say this goal has been achieved judging by the amount of successful installations over the last few months by complete beginners :-)

Yes, for me it was comparatively easy despite being such a complex project and no exisiting knowledge about BBB or WebRTC. I was also able to do this due to the great ecosystem that is now existing around BBB: the bbb-install tool, ansible roles, mailing lists, a lot of GitHub issues covering any possible issues and a documentation with lots of FAQs.

And if you look at it from the user side I'd say a lot of common complaints were removed in 2.3 as well: presentation uploads, raising hands and a lot of other QOL stuff.

Many thanks for your great work and for the helpful community! I'd say you could now close this oldest open issue :)

**Comment by ffdixon** [comment]
With the release of [BigBlueButton 2.3](https://github.com/bigbluebutton/bigbluebutton/releases), I think we can close this issue.  

BigBlueButton 2.3 was our best release yet (and it's only going to continue to get better).  We really focused on the teacher and student experience.  Going forward, we will continue (and accelerate) the development to ensure we're building the best virtual classroom for the world.
