### ISSUE TITLE
Move the guest wait page out of the bbb-client package

### ISSUE THREAD

**Issue by capilkey** [bigbluebutton/bigbluebutton#7590]
The current guest wait page is inside of the Flash client code and package (1). This will cause us issues when it comes time to remove the Flash specific packages from the default install. I think we should move the file into /var/www/bigbluebutton-default/ so that it will be included no matter which client packages are installed.

Changing the file location will require packaging changes so that the file is available in the new location and bbb-web changes so that users are directed to the new path. (https://<server>/guest-wait.html)

1. https://github.com/bigbluebutton/bigbluebutton/blob/master/bigbluebutton-client/resources/prod/guest-wait.html

**Comment by capilkey** [comment]
Looks like there's no packaging changes required at all. We can put guest-wait.html in here, https://github.com/bigbluebutton/bigbluebutton/tree/master/bigbluebutton-config/web, and it will be picked up by the packages automatically. The bbb-web changes should be pretty minimal also because the URL is defined in bigbluebutton.properties.

**Comment by miztaka** [comment]
I also want this and styled page like #9378 
In addition to that, no "You are denied" message is shown when moderator denies to join the meeting.

**Comment by basisbit** [comment]
closed by #9979 in develop and thus in 2.3.x.
