### ISSUE TITLE
Update the call to action text found in the connectivity alert bar

### ISSUE THREAD

**Issue by tylercopeland** [bigbluebutton/bigbluebutton#7594]
<img width="1440" alt="Screen Shot 2019-06-10 at 1 08 15 PM" src="https://user-images.githubusercontent.com/1273169/59213380-c1815a00-8b82-11e9-8cae-291cb66b2418.png">

**Current Text** = How to fix it?
**Purposed Update** = How to improve it?

**Comment by ffdixon** [comment]
Or just make it more neutral and say "more information"

**Comment by antobinary** [comment]
I second the "More information" - this is what I am more accustomed to from other apps
