### ISSUE TITLE
Indicated the microphone used to join the audio bridge

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#7596]
When joining with Chrome, the BigBlueButton client chooses the default microphone.  

However, if the user just plugging in their webcam before joining a session, Windows would make the webcam microphone default (which isn't necessarily what the user would want).

While it's possible to go into the Windows Sound settings control panel and switch the default microphone, the user will be likely unaware they need to do so.

Currently, when the user joins the audio, the toast message shows they have joined

![image](https://user-images.githubusercontent.com/290351/59214915-0955b080-8b86-11e9-90ed-a8f1e9fb83ed.png)

It would be great if this could be phrased as

    You have joined the audio conference 
    with microphone "Webcam - C170"

**Comment by JustinMogel** [comment]
on 2.3-beta-1 (1511) when joining with chrome it picks the default microphone (or in my case webcam if plugged in, which is undesirable)
when joining with firefox, I get to choose which microphone I use. 

it would be great if there was information which microphone is being used with chrome.

**Comment by prlanzarin** [comment]
@JustinMogel this will be addressed in an upcoming beta, see https://github.com/bigbluebutton/bigbluebutton/pull/11813

**Comment by mariogasparoni** [comment]
@prlanzarin 
We can close this one, we now indicate the selected device in #11813

**Comment by prlanzarin** [comment]
I'd consider it partially, not fully addressed.

The issue talks about upfront, automatic display of the selected device (eg.: in the echo test modal under the Yes/No prompts, or the toast like in the screen shot)).

The device input selection improves the situation, but the user still has to be proactive enough to click the audio button to see what device was selected. Might go the entire meeting with the wrong input device if nobody gives a heads up or if they aren't proactive.
