### ISSUE TITLE
Dropdown being clipped on mobile.

### ISSUE THREAD

**Issue by Tainan404** [bigbluebutton/bigbluebutton#7597]
![Screenshot_2019-06-10-16-30-48-181_com android chrome](https://user-images.githubusercontent.com/15806883/59221347-6c9f0d00-8b9d-11e9-9ac5-4f234a48582e.png)

**Comment by antobinary** [comment]
Which dropdown is this supposed to be? - how to reproduce?

**Comment by Tainan404** [comment]
Video dropdown.

![WhatsAppVideo20190612at31](https://user-images.githubusercontent.com/15806883/59375652-0218d900-8d25-11e9-8a6f-da8202bcb53c.gif)

**Comment by JustinMogel** [comment]
this is still an issue on 2.3-alpha-8 (1511) and reproducable as by Tainan404's comment.
the overlapping graphics dissapear when tapping on them.

**Comment by antobinary** [comment]
Thanks for bringing this up @JustinMogel , I just tagged it as 2.3 and we'll look into fixing this shortly
