### ISSUE TITLE
How to solve video not fluent ?

### ISSUE THREAD

**Issue by zsinba** [bigbluebutton/bigbluebutton#7600]
When I set a very clear scale, my image will be very sluggish. My Settings are as follows, using the Flex version.
![image](https://user-images.githubusercontent.com/890157/59257751-231bf400-8c69-11e9-8b0f-2c0f2d99617e.png)

Can you tell me that's it because of the Internet? Is it the Flex side? Is it because of the decoding capability of the server? How can I improve the efficiency of its operation and reduce the problem of jam? Should I increase the bandwidth of the network? Or should we increase the amount of CPU and memory on the server? 
Thank you for your reply.

**Comment by zsinba** [comment]
Since there is text on the screen, I hope to use the hd screen. But when it comes to high-definition graphics, it's not smooth.

**Comment by ffdixon** [comment]
Can you try the HTML5 version and let us know if the quality is any better. See http://docs.bigbluebutton.org/2.2/install.html

You can also test this with creating an account at https://demo.bigbluebutton.org/ and try it there.

**Comment by capilkey** [comment]
It depends on what you mean by "sluggish". You've got the video set to 5 FPS so the refresh rate is pretty low, but it could also be that the local computer is unable to handle the video encoding or a networking issue with the server.

**Comment by zsinba** [comment]
Unfortunately I can't use the HTML5 version because I have to use multiple camera cases. In my application scenario, in a computer, I have multiple cameras pushing at the same time, so I can only use the Flex version now. Now that I've added 500 megabytes of bandwidth,8 CPUs and 32 gigabytes of memory to the network, I believe the server configuration is excellent. So I don't know what the problem is now, I suspect it may be because the upload speed is limited, so the high video will be compared with the carton, but it may also be the reason of the poor processing speed of the local computer, I can't know which reason is caused. I want to optimize this part of the code, but I don't have a clue yet. Please give me some more advice. Thanks for your guidance.

**Comment by capilkey** [comment]
It's pretty easy to test issues with the local computer. When you run a normal use case does the browser max out a core or use all the upload bandwidth? I don't know what OS you're using, but Windows 10 shows you lots of information in the task manager like CPU usage for applications and total upload bandwidth for the machine.

**Comment by ffdixon** [comment]
> Please give me some more advice. Thanks for your guidance.

You need to update to the HTML5 client for better video.  If you do a side-by-side comparison of the Flash video and HTML5 video, you'll see one is better than the other.

**Comment by capilkey** [comment]
The only improvement in quality is the uncapped framerate in the HTML5 client, the resolution is the same. It's also UDP rather than TCP so it doesn't get out of sync from packet loss.

**Comment by zsinba** [comment]
> It's pretty easy to test issues with the local computer. When you run a normal use case does the browser max out a core or use all the upload bandwidth? I don't know what OS you're using, but Windows 10 shows you lots of information in the task manager like CPU usage for applications and total upload bandwidth for the machine.

I will do this test in a few days. Then I will ask you about this matter.
Thanks So Much.

**Comment by zsinba** [comment]
> > Please give me some more advice. Thanks for your guidance.
> 
> You need to update to the HTML5 client for better video. If you do a side-by-side comparison of the Flash video and HTML5 video, you'll see one is better than the other.

In the beginning, I planned to use the HTMl5 version, and I consulted you about it. But unfortunately, HTMl5 version cannot meet my needs, I need a computer with multiple cameras, and it is not convenient to use multiple tabs for simultaneous management. Also, the HTML5 and Flash video streams aren't interoperable, so I can't mix HTML5 and Flash. Expect HTML5 to support multiple cameras as soon as possible. Wish you well. 
Thank you for your open source system. 
It's very greate. Thank you for your hard work. It was very meaningful

**Comment by zsinba** [comment]
![image](https://user-images.githubusercontent.com/890157/59429834-38348680-8e13-11e9-8737-400769843e1a.png)

I used the hd configuration, such as 1920*1080 resolution. If it was face-to-face communication, the picture quality was very good, but when I had text in the picture, the text was very blurred.
I want to know how to optimize the picture with text on this camera.
Because I'm using a virtual camera to share my desktop app, the text is blurry.
I know BBB has desktop sharing, but please forgive me for not being able to use it.

**Comment by ffdixon** [comment]
We don't recommend sharing your screen using a webcam -- also, the compression is going to be high and you won't get a good video (as you have shown here).

Is there a reason why your not using the screen sharing in 2.0?  For an overview of how it works, see: https://www.youtube.com/watch?v=xTFuEvmEqB0
