### ISSUE TITLE
Load Balancing or failover ?

### ISSUE THREAD

**Issue by netlabs** [bigbluebutton/bigbluebutton#7604]
I was so happy after using this application. Do we have any load balancing option available for the server?

**Comment by ffdixon** [comment]
Glad you are enjoying BigBlueButton.  

We don't have any load balancing option available, such as load balancing a meeting across two servers, or starting a meeting on the least loaded server.

Our development focuses on making the single BigBlueButton server as solid and scalable as possible.

You should find the stability good, and if you encounter any issues, please let us know in bigbluebutton-dev mailing list.  If there is an issue with the product that needs addressing, we'll open it here to track it.
