### ISSUE TITLE
Let people know how to mute/unmute yourself on the phone

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#7612]
Currently, the defaults are that a moderator can not unmute a viewer.  But if they mute a user dialed in, they can't unmute them and the user need to know they can press the '0' key to unmute themselves.

Add a tip for this in the join audio dialog box.

![image](https://user-images.githubusercontent.com/290351/59395518-5f774f00-8d52-11e9-8067-ce65f00fb6a0.png)

**Comment by antobinary** [comment]
Implemented in #7765 7765
