### ISSUE TITLE
How can i change the layout of HTML bbb?

### ISSUE THREAD

**Issue by MrMed** [bigbluebutton/bigbluebutton#7614]
I just need to show the webcam image when start and only that. I don't want the whiteboard and others stuffs. I need only the webcam video, How can i do this?

**Comment by capilkey** [comment]
There's a property for autoSwapLayout in settings.yml that you can set. There's also an option to automatically popup the webcam dialog if you want to do that also. 

This isn't an issue with the client so I'm going to close it.
