### ISSUE TITLE
BigBlueButton v2.2 HTML5 client text kaizen

### ISSUE THREAD

**Issue by fungma** [bigbluebutton/bigbluebutton#7615]
gray background text in chat message input box

said 

Message Public Chat

It should change to

Public Chat Message ？

**Comment by antobinary** [comment]
Hey @fungma,

Thanks for your feedback!
What we currently have (Message X) where X is the destination Username or Channel name actually matches the experience encountered in other messaging applications (like Slack).
In this case "Message" is used as a verb
Send to <username>
Send to <channel name>

I see reasons to keep the format as-is. If others would like to share their view - go ahead :)

**Comment by fungma** [comment]
bigbluebutton-v22-html5-client in transifex.com 
“Message”  is "Message {0}"
Would it  change to "Send Message to  {0} "

if not，now I am translating Chinese (China) (zh_CN ） in transifex.com 
 "Message {0}"   is  “消息 {0} ”
I would translate it to  “发送消息给 {0} ” instead

> Hey @fungma,
> 
> Thanks for your feedback!
> What we currently have (Message X) where X is the destination Username or Channel name actually matches the experience encountered in other messaging applications (like Slack).
> In this case "Message" is used as a verb
> Send to 
> Send to
> 
> I see reasons to keep the format as-is. If others would like to share their view - go ahead :)

**Comment by antobinary** [comment]
Hi @fungma 

You will see your suggestion as part of the next release

![Screenshot from 2019-06-27 13-56-01](https://user-images.githubusercontent.com/6312397/60289466-7ab29480-98e4-11e9-82fc-6d95bdbfed96.png)
![Screenshot from 2019-06-27 13-55-38](https://user-images.githubusercontent.com/6312397/60289468-7ab29480-98e4-11e9-82af-0580ade793ba.png)

Don't hesitate to provide further feedback about other parts of the client!
