### ISSUE TITLE
The last row in the user list is cut off in Android Chrome

### ISSUE THREAD

**Issue by capilkey** [bigbluebutton/bigbluebutton#7619]
Steps to reproduce:
1. Start 6 clients with different names
2. Join the session with Chrome on an Android phone
3. Scroll to the bottom of the user list

Expected result:
You should be able to see the final name in the list.

Actual result:
The last row is cut off.

Additional Info:
The client was build 522. The device was a Pixel 1. I tested Firefox also, but I could see the final row there.

Originally report here, https://groups.google.com/forum/#!topic/bigbluebutton-dev/h9zA0MItlXY

**Comment by antobinary** [comment]
Likely this has to do with the new SharedNotes and/or Captions sections not being taken into consideration when calculating the available space
