### ISSUE TITLE
Add support for 'logo' parameter on 'create' API call for HTML5 client

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#7629]
Previously, in the Flash client, the front-end could pass a `logo` parameter to display a logo in the Flash client.

Add this support for the HTML5 client so the logo is visible at the top of the Users list (here's a rough design)

![image](https://user-images.githubusercontent.com/290351/59555976-4d332600-8f89-11e9-9b84-48f10a2dc892.png)

**Comment by jfsiebel** [comment]
This feature is already implemented in https://github.com/bigbluebutton/bigbluebutton/pull/5267.

**Comment by ffdixon** [comment]
This is at the server level, but is it also supported on a per-meeting with the `create` API call?  In other words, can two meeting on the server have two different logos?

**Comment by jfsiebel** [comment]
Yes, it's possible.
