### ISSUE TITLE
bigbluebuttonbn Error

### ISSUE THREAD

**Issue by mohamedsalman** [bigbluebutton/bigbluebutton#7630]
bigbluebuttonbn/You did not pass the checksum security check

this error shown when i changed bigbluebutton server on Ubuntu

**Comment by ffdixon** [comment]
To get the shared secret from your BigBlueButton server, do `bbb-conf --secret`, see

  http://docs.bigbluebutton.org/admin/bbb-conf.html#--secret

and use the values given to update the BigBlueButtonBN plugin for Moodle.

**Comment by mohamedsalman** [comment]
I did it and the same error

**Comment by ffdixon** [comment]
Can you check the shared secret field in Moodle to make sure you don't have any spaces before/after the secret.

**Comment by mohamedsalman** [comment]
Thanks ffdixon
It Work Now
