### ISSUE TITLE
A scroll bar appears if the notification text is too long

### ISSUE THREAD

**Issue by GhaziTriki** [bigbluebutton/bigbluebutton#7631]
![image](https://user-images.githubusercontent.com/4991088/59565325-b2a31780-905a-11e9-9bf2-e9d30bcf769f.png)

**Comment by antobinary** [comment]
@JoVictorNunes are you able to reproduce this on 2.4.4+?

**Comment by JoVictorNunes** [comment]
@antobinary Not reproducible on 2.4.4+. Words seem to be breaking properly.

![Captura de tela de 2022-02-11 14-24-46](https://user-images.githubusercontent.com/62393923/153639494-15885479-3919-4960-b5a3-3b86f3e4890e.png)
