### ISSUE TITLE
Trigger the recommended browser dialog for Safari (Mac OS X)

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#7632]
Currently, when using Safari (Mac OS X), the user joins audio with

![image](https://user-images.githubusercontent.com/290351/59571994-f6f0e080-9077-11e9-85e3-e322f300c0cd.png)

But on Windows, when joining with Edge, we display

![image](https://user-images.githubusercontent.com/290351/59572080-a6c64e00-9078-11e9-8365-947da86ea172.png)

Safari works on Mac OS X, but the better experiences would be with Chrome or FireFox.  When joining on Safari on Mac OS X, display the following message:

  It looks like you are using Safari.  If you encounter any problems sharing audio/video, try switching to Chrome or FireFox.

**Comment by prlanzarin** [comment]
As hard as I find it to believe, I think we're in a good enough place with Safari right now so I consider this issue stale and I'm closing it. Re-open if necessary.
