### ISSUE TITLE
Add startup option to set placement of webcams

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#7644]
Enable the configuration of webcams to be always on top.  

Requested in

  https://groups.google.com/d/msg/bigbluebutton-dev/wFuGG3CQj0A/9HX7kBM7CAAJ

**Comment by vitormateusalmeida** [comment]
The default value for placement was changed in #7756 
https://github.com/vitormateusalmeida/bigbluebutton/blob/eb8cae8f4ec34d33241d61454f004d0bfb8c90be/bigbluebutton-html5/imports/ui/components/media/webcam-draggable-overlay/context.jsx#L7
