### ISSUE TITLE
Delete closed caption doesn't works on viewer side.

### ISSUE THREAD

**Issue by Tainan404** [bigbluebutton/bigbluebutton#7648]
![gif-bug](https://user-images.githubusercontent.com/15806883/59769578-d04fc700-927c-11e9-844b-24dcc6e058c7.gif)

**Comment by pedrobmarin** [comment]
This first version of closed captions was not designed to propagate those kind of updates to the viewer. https://github.com/bigbluebutton/bigbluebutton/pull/7453

I like the idea of the caption owner to be able to make some corrections on the fly. But I would recommend to do it only if it is a high priority feature

**Comment by JustinMogel** [comment]
same Issue as Issue #8221

**Comment by pedrobmarin** [comment]
Fixed in https://github.com/bigbluebutton/bigbluebutton/pull/13916
