### ISSUE TITLE
Warn users when the user tries to share microphone when client is loaded from HTTP

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#7650]
With FireFox recently requiring TLS certificate, both FireFox and Chrome need the site loaded from HTTPS for WebRTC media sharing to work.

The client should put an error message when the user tries to share microphone, webcam, or screen, with a site loaded from HTTP.

**Comment by GhaziTriki** [comment]
HTTPS is endorsed in favour of HTTP.
