### ISSUE TITLE
Hide YouTube controls from viewers

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#7652]
Currently, when the moderator shared a YouTube video, viewers still see the controls for stop/start and seek (though they don't do anything if they try using them).

It would be preferable to hide these controls from everyone except the presenter.

**Comment by capilkey** [comment]
I don't think that we would want to block the controls completely because users need to be able to control the volume level

**Comment by lfzawacki** [comment]
I did a little testing and it doesn't seem possible to hide play/pause/seek controls and still keep the volume button. We could hide the controls and implement our own volume slider with javascript though.

**Comment by lfzawacki** [comment]
By the way, the user can stil pause the video by clicking on the player and also seek by using the key bindings, so hiding the controls won't do much... we still need to the dirty work of by passing them via code.

**Comment by criptalis** [comment]
I also think that it is interesting to be able to block (or hide) these functions.
The volume can always be set directly on the device.

**Comment by pedrobmarin** [comment]
Hey @lfzawacki , how are your vacations going?
