### ISSUE TITLE
handleDismiss of undefined

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#7655]
The log encountered was

`[{"name":"clientLogger","level":50,"logCode":"startup_error","levelName":"error","msg":"TypeError: Cannot read property 'callback' of undefinedn    at k.handleDismiss (https://xxxxxxxxx/html5client/a1c1e7a032b242a4d81090c1aaeca7c9060c37b9.js?meteor_js_resource=true:125:710400)n    at d.validateDisabled (https://xxxxxxxxxxxxxxx/html5client/a1c1e7a032b242a4d81090c1aaeca7c9060c37b9.js?meteor_js_resource=true:125:631346)n    at d.internalClickHandler (https://xxxxxxxxxxxxx/html5client`

The chunk of minified code is 

`class k extends s{constructor(e){super(e),this.handleDismiss=this.handleDismiss.bind(this)}handleDismiss(){this.props.modalHide(this.props.dismiss.callback)}render(){const e=this.props,{intl:t,title:n,hideBorder:o,dismiss:s,className:l,modalisOpen:p,onRequestClose:u,shouldShowCloseButton:h,contentLabel:b}=e,v=(0,i.default)
`

Likely we need to tweak

```
  handleDismiss() {
    this.props.modalHide(this.props.dismiss.callback);
  }
```

to be more like

```
  handleDismiss() {
    const { dismiss, modalHide } = this.props;
    if (dismiss && modalHide) {
      modalHide(dismiss.callback);
    }
  }
```
But some digging will be useful (for how come we triggered dismiss without the right props)

**Comment by capilkey** [comment]
Same as #7642
