### ISSUE TITLE
Collaborative code editor

### ISSUE THREAD

**Issue by overclockedllama** [bigbluebutton/bigbluebutton#7659]
Similar to #1630 however I was hoping for something more like the UI of https://codeshare.io (especially my beloved Monokai theme)! Maybe this could be implemented through the + icon with a + new CodePad. 

Many thanks

**Comment by ffdixon** [comment]
Thanks for the suggestion -- is it possible to embed a codepad within another HTML5 application?  We're embedding the YouTube player in the BigBlueButton client..

**Comment by overclockedllama** [comment]
If all the users could see the same codepad then yeah I guess that would be perfect

**Comment by overclockedllama** [comment]
I've had a look at the etherpad software you are using and I have found this 
https://www.npmjs.com/package/ep_codepad
I am going to try patch the current etherpad installed with bbb-install.sh to this codepad. If it all goes successfully, I think it may be possible to implement a switch in bbb-install.sh as to whether you want a notepad (etherpad) or a codepad (ep_codepad).

**Comment by capilkey** [comment]
I think we're already using a custom etherpad package to add some extra features and fit the look and feel of the client. I think our version is here, https://github.com/bigbluebutton/etherpad-lite

**Comment by overclockedllama** [comment]
I've had a look at the fork. Could you help me out with instructions to compile/start the server as I am a little confused?

**Comment by ffdixon** [comment]
Recommend you start with a working BigBlueButton server, then try stopping `bbb-etherpad`

~~~
systemctl stop bbb-etherpad
~~~

and swapping in your version, and then starting again

~~~
systemctl start bbb-etherpad
~~~

This will minimize any changes to the environment and you can focus on etherpad itself.

**Comment by overclockedllama** [comment]
I think you mean `etherpad.service`? I do not have `bbb-etherpad.service` 

After adding my version and restarting etherpad the text editor just disappeared. I put the original code back in `/usr/share/etherpad-lite` but the text editor did not reappear until a full server reboot. Very strange behaviour. 

I shall try again in a VM since I don't want to mess up my main server

**Comment by overclockedllama** [comment]
I've had a go at trying to merge yours and the ep_codepad plugin but no luck. Maybe one of you guys could take a look.

**Comment by matiasilva** [comment]
No follow up in a year. Closing for now but feel free to follow up at https://groups.google.com/forum/#!forum/bigbluebutton-dev.
