### ISSUE TITLE
Add a "Language" label to the Closed Captions modal experience

### ISSUE THREAD

**Issue by tylercopeland** [bigbluebutton/bigbluebutton#7679]
<img width="614" alt="Screen Shot 2019-06-25 at 4 35 55 PM" src="https://user-images.githubusercontent.com/1273169/60131463-7745ce80-9767-11e9-9c4e-63dc3a819c5f.png">

Also, if possible, it would be great to see the "Language" input aligned with the rest of the inputs below.

**Comment by antobinary** [comment]
Looks like this was implemented at some point
Screenshot taken on BBB 2.3-alpha7

![Screenshot from 2021-03-04 09-41-14](https://user-images.githubusercontent.com/6312397/109980356-d0e8f500-7ccd-11eb-887d-881bf17942fa.png)
