### ISSUE TITLE
bug - expired breakout room Disconnects audio in the main room.

### ISSUE THREAD

**Issue by Jossef-767** [bigbluebutton/bigbluebutton#7687]
when a teacher or student canceled their entry into an breakout room,
(Reject the invitation And stayed in the main room) ,
after the time that was set for the breakout room expired (which had not been entered at all)
Their audio will be Disconnected in the main room.

**Comment by ffdixon** [comment]
Hmm ... can you give specific steps to reproduce.  I just 

1. joined a session on https://demo.bigbluebutton.org/ as moderator, 
2. joined the audio bridge with microphone
3. created a breakout room for 1 minute and invited myself
4. declined the invitation
5. waited

The breakout rooms closed but I didn't drop from audio.

**Comment by Jossef-767** [comment]
I did not do step 2.  (did not joine the audio bridge)
my mistake, audio didnot Disconnect, Just pops up the connection window. 
Maybe that makes sense.

**Comment by antobinary** [comment]
Could not reproduce (not joining audio but being removed from audio sounds confusing too)
