### ISSUE TITLE
Message time in chat gets from client, not from server

### ISSUE THREAD

**Issue by Brullworfel** [bigbluebutton/bigbluebutton#7703]
If client have wrong time on his device, his messages in chat shows with wrong time too.

BBB 2.0, flash client.

**Comment by ffdixon** [comment]
Can you tell us if you see the same behavior in the HTML5 client -- thanks!

(we're not going to be doing any more updates to the Flash client, but thank's for reporting it.  We're interested to hear any issues you find with the HTML5 client).
