### ISSUE TITLE
Add space below the welcome message in the public chat

### ISSUE THREAD

**Issue by tylercopeland** [bigbluebutton/bigbluebutton#7717]
A chat message that appears directly after the "Welcome" message is a little too close. 

![Screen Shot 2019-07-02 at 11 31 21 PM](https://user-images.githubusercontent.com/1273169/60561498-b5239380-9d21-11e9-86bc-f8afea7cd500.png)

A small improvement would be to add **margin-bottom:24px;** to the welcome message. 
![Screen Shot 2019-07-02 at 11 34 31 PM](https://user-images.githubusercontent.com/1273169/60561571-f61ba800-9d21-11e9-996d-c4f0be45446b.png)

**Comment by diegobenetti** [comment]
![Screenshot from 2019-07-25 10-01-42](https://user-images.githubusercontent.com/7821065/61876512-6d78cd80-aec3-11e9-8a55-2dd828b827d7.png)

Do you think we can keep this `margin-right` in the welcome message?

**Comment by tylercopeland** [comment]
@diegobenetti it looks about right.
