### ISSUE TITLE
Different configuration parameters are used for different classrooms

### ISSUE THREAD

**Issue by zsinba** [bigbluebutton/bigbluebutton#7722]
Can I set each room to use a different configuration file by profiles(xml file or interface ),

I mean config.xml and profiles.xml, I wanted different rooms, with different configurations, so that they could have different effects. 

What do you suggest? 

Thank you for your reply.

**Comment by zsinba** [comment]
P.S. I'm using the Flash version.

**Comment by capilkey** [comment]
The way to do this is with the setConfigXML API call, http://docs.bigbluebutton.org/dev/api.html#setconfigxml. You could have different config.xml files pre-configured and the profiles.xml URL is already in config.xml so you can have different ones set.

**Comment by zsinba** [comment]
Thank you. That's all I wanted to know
Thank you for your reply. Wish you all the best
