### ISSUE TITLE
Clicking on a <a href="tel:NN>NN</a> link causes a client reconnect

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#7732]
In the latest build of BigBlueButton, clicking on at 

```
  <a href="tel:NN">NN</a>
```

link in the welcome text causes a reconnect in the client.

![tel](https://user-images.githubusercontent.com/290351/60693963-4f164800-9eaa-11e9-90f5-48f136d671cd.gif)

**Comment by GhaziTriki** [comment]
Cannot reproduce in 2.2.30
