### ISSUE TITLE
errors on tomcat 

### ISSUE THREAD

**Issue by rmros** [bigbluebutton/bigbluebutton#7757]
hi
i just installed ubuntu 

root@snapshot-5787278-ubuntu-8gb-new:~# cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.6 LTS"

i run this script 

 wget -qO- https://ubuntu.bigbluebutton.org/bbb-install.sh | bash -s -- -v xenial-220-beta -s xxxxxxxx.com -e xxxxxx@gmail.com -g

but this error on tomcat:

![1](https://user-images.githubusercontent.com/21344663/60963896-49e04f80-a327-11e9-887c-1e93b15db3cd.jpg)

how solve that?

**Comment by ffdixon** [comment]
Can you try running

~~~
sudo apt-get install -f 
~~~

and let us know if that gets you going.  Did this server already have a JDK installed?  Also, did some googling and found this

~~~
https://askubuntu.com/questions/556954/tomcat7-installation-failed-via-apt-get-on-ubuntu-14-04
~~~

**Comment by rmros** [comment]
> Can you try running
> 
> ```
> sudo apt-get install -f 
> ```
> 
> and let us know if that gets you going. Did this server already have a JDK installed? Also, did some googling and found this
> 
> ```
> https://askubuntu.com/questions/556954/tomcat7-installation-failed-via-apt-get-on-ubuntu-14-04
> ```

no its raw ubuntu and there are not any installed in that like java, jdk ...
 not work after   sudo apt-get install libtomcat7-java 

again that error is showing
