### ISSUE TITLE
bbb-playback-screenshare 

### ISSUE THREAD

**Issue by dahalday** [bigbluebutton/bigbluebutton#7762]
Good Day Team

Keep up the great work. Now using BBB version 2.2 beta 16. I was just wondering how the updates for **sudo apt-get install bbb-playback-screenshare** were coming along as referenced in #7145. This functionality seems to have been lost since BBB version 2.0.

Although installed on BBB version 2.2 beta 16 the single share screen playback is not generated. 

Looking forward to hearing from the group.

Kind Regards 
DH

**Comment by ffdixon** [comment]
Thanks for the reminder -- there is still work to be done on #7145.  We'll update the ticket when we have something ready to test.

**Comment by GhaziTriki** [comment]
Screen-share format is working on BigBlueButton 2.3 as far as I know. However it must be manually enabled: https://github.com/bigbluebutton/bigbluebutton.github.io/pull/292
