### ISSUE TITLE
BigBlueButton 2.2-beta-17 html5 client's Application Language setting bug

### ISSUE THREAD

**Issue by fungma** [bigbluebutton/bigbluebutton#7776]
1. html5 client , UI language  will not auto set to your browser's default language .
always keep in English!

2. html5 client in Chrome / Firefox
... Options
Settings
Application Language
set to other language and save
now the screen will be flashing...

**Comment by ffdixon** [comment]
Good catch!  We'll fix this one soon.

Regards,... Fred
