### ISSUE TITLE
How to share a video between teachers and students

### ISSUE THREAD

**Issue by zsinba** [bigbluebutton/bigbluebutton#7795]
Hi, how can I share a video between teachers and students? This video is played by the teacher. Students can see it, but they can't control it. The control of video is entirely up to the teacher. Teachers can pause, drag, and close video. 
Students can only watch this video content. 
Just like the whiteboard, the teacher controls the whiteboard. Students can only check the teacher's page-turning, writing and changing courseware.

Thank you for your help. I would appreciate it very much
Note: I'm talking Flash, not Html5.

**Comment by ffdixon** [comment]
Is it an option for you to use the HTML5 client, which can share a YouTube video?  

We have been transitioning our development away from Flash to focus to the HTML5 client.

Flash has been good for us in the past -- the BigBlueButton project would not exist without it -- but looking ahead to the future, we are focusing our efforts on the HTML5 to make it the best web conferencing system for online learning.
