### ISSUE TITLE
Automatically starts multiple camera video

### ISSUE THREAD

**Issue by zsinba** [bigbluebutton/bigbluebutton#7796]
I set auto start with VideoconfModule　＂autoStart:true＂,skipCamSettingsCheck:true
At this point, if I have multiple cameras, the other cameras can't be enabled.
This should be a bug in the Flash version.
Do you still fix the bugs in Flash version?
When I set skipCamSettingsCheck to True, I can no longer use the peripheral cameras.

thanks so much get your reply.

**Comment by ffdixon** [comment]
We are no longer working on the Flash version (and it will be depreciated in the release that follows BigBlueButton 2.2).

Is it an option for you to use the HTML5 client instead?

**Comment by zsinba** [comment]
thanks
