### ISSUE TITLE
unmute all user can't be work,How can I fix it?

### ISSUE THREAD

**Issue by caojincool** [bigbluebutton/bigbluebutton#7797]
![image](https://user-images.githubusercontent.com/466750/61352164-4b69c480-a89f-11e9-9a9e-e856395190ea.png)

**Comment by capilkey** [comment]
That option turns off the meeting mute and users that start a new voice connection won't be muted, but it doesn't unmute people that are already joined to voice because then you'd have a burst of noise.

**Comment by caojincool** [comment]
ok ,thank you
