### ISSUE TITLE
Screen sharing not always appearing on users of Chrome

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#7798]
Receiving reports that on the latest build of BigBlueButton 2.2-beta, there are cases where uses of Chrome do not initially see the instructors screen share (but do so after refreshing their browser).

Reported here

   https://groups.google.com/d/msg/bigbluebutton-dev/f17h1vEpf3s/aMSRXQpXDwAJ

**Comment by ffdixon** [comment]
Based on testing with others, we're pretty sure this is due to Chrome's AutoPlay restrictions.  Here are the details

  https://developers.google.com/web/updates/2018/11/web-audio-autoplay

**Comment by ffdixon** [comment]
See also 

   https://groups.google.com/d/msg/discuss-webrtc/BwJOWloyS34/-f1g6NpJCQAJ

**Comment by Jossef-767** [comment]
you are absolutely correct ​!  
​in chrome//flags/  page, I disabled autoplay policy and enabled auto play ignores web audio playback
and now screen share ​is always appearing and there is no more​ ​problem. even after  20 times I refreshed the page.
so I guess ​you ​should make the client comply  with chrome autoplay policy, 
Maybe an ​"​accept​"​​ ​ button on ​user ​screen​ on login, 
and add video controls​ on ​player's window.

**Comment by prlanzarin** [comment]
FYI https://github.com/bigbluebutton/bigbluebutton/issues/7693

**Comment by antobinary** [comment]
Addressed in #7693
