### ISSUE TITLE
instal bbb

### ISSUE THREAD

**Issue by Gilang5** [bigbluebutton/bigbluebutton#7801]
Hello All.
 if i loggin to bigbluebutton with my IP ,Browser showed as message :  

                                                              404 Not Found
                                                         nginx/1.10.3 (Ubuntu)

**Comment by ffdixon** [comment]
The problem was traced back to the package unattended-updates updating redis and causing the connection from BigBlueButton to redis to drop.

The solution to avoid this problem in the future was discussed here

  https://groups.google.com/d/msg/bigbluebutton-dev/SBQlLFNLtKc/kWChAgL8AwAJ
