### ISSUE TITLE
cron.daily bigbluebutton not deleting temp kurento files in /var/kurento

### ISSUE THREAD

**Issue by hostbbb** [bigbluebutton/bigbluebutton#7802]
https://github.com/bigbluebutton/bigbluebutton/blob/master/bigbluebutton-config/cron.daily/bigbluebutton#L56

looking for mkv, believe needs to be webm.

Disk drives will prematurely fill up on busy servers since all raw camera and screenshare files dont get deleted.

**Comment by prlanzarin** [comment]
Nice one, that's correct, needs to be `*.webm`. Recording profile got changed when we switched the default codec from H.264 to VP8 (https://github.com/bigbluebutton/bbb-webrtc-sfu/pull/29), but I think we forgot to make the cron job follow the change.
