### ISSUE TITLE
Audio error: Cannot destructure property `mediaHandler` of 'undefined' or 'null'. 

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#7811]
Check for `this.activeSession ?` first before triggering exitAutio()
In some cases with EndMeeting being forced we hit
![Screenshot from 2019-07-18 14-43-46](https://user-images.githubusercontent.com/6312397/61488759-06b15c80-a977-11e9-86d8-fb04ffa5f5b7.png)

**Comment by GhaziTriki** [comment]
@antobinary Does this issue still happen?
