### ISSUE TITLE
dissociate presenter chat window from shared presentation layout

### ISSUE THREAD

**Issue by mkpelletier** [bigbluebutton/bigbluebutton#7814]
In the html5 version, the presentation width and layout changes for all participants, if the presenter hides or shows his/her chat window.  This is unexpected behaviour, as doing the same thing when participating as any other role has no effect on the state of the presentation.

BBB-html5 2.2.0-568
bigbluebutton 2.2.0-4

**Comment by capilkey** [comment]
We wouldn't want to change this. We want to always maintain that what the presenter sees on their screen is the exact same thing as what the viewers are seeing. If the presenter zooms, the other clients zoom. If the presenter pans, the other clients pan.

By enforcing that all of the clients see the exact same part of the presentation we remove the need for the presenter to constantly ask, "Can you see that?".

There's also a rewrite in the works to improve the performance of the presentation area for the presenter. Right now it's pretty laggy to use.
