### ISSUE TITLE
Improve exit logs for video/screenshare to state exit reason

### ISSUE THREAD

**Issue by prlanzarin** [bigbluebutton/bigbluebutton#7816]
When screenshare/camera is closed, log the reason for shutdown; ie.:

- Closed due to lock settings (mods only etc)
- Closed due to error
- Closed due to breakout rooms
etc

**Comment by antobinary** [comment]
@prlanzarin is this still valid?

**Comment by prlanzarin** [comment]
Hmm. I remember why I was asked to open this issue back then. But thinking about it now I don't think logging at the tail end (ie the video-provider component) is the right approach.

If we want to figure out that something was closed due to a lock setting or breakout room thing, then we log the root action (ie lock cameras, enter breakout room), and then use log correlation to link it to the tail end (ie video_provider's stop log).

About errors: screen sharing should have very well defined logs and error maps (<code, message>) now.
And, although I've rewritten video-provider's logs a thousand times now, they still suck :smile:. But errors are logged there nonetheless.
