### ISSUE TITLE
Audio and video not supported on Firefox Nightly 70.a1

### ISSUE THREAD

**Issue by GhaziTriki** [bigbluebutton/bigbluebutton#7820]
![image](https://user-images.githubusercontent.com/4991088/61584510-91e64a00-ab51-11e9-8631-5548c0d27fa3.png)

![image](https://user-images.githubusercontent.com/4991088/61584512-9f033900-ab51-11e9-9dba-68020918309f.png)

**Comment by ffdixon** [comment]
This is running iOS, no?  We should modify the message to specifically reference Firefox.

**Comment by GhaziTriki** [comment]
This is running on Windows 10.

**Comment by ffdixon** [comment]
Can you test with https://appr.tc/ and let us know if it works there.

**Comment by capilkey** [comment]
The check that is failing is ``!!navigator.mediaDevices` and that should only happen if the client isn't HTTPS. https://github.com/bigbluebutton/bigbluebutton/blob/master/bigbluebutton-html5/imports/utils/deviceInfo.js#L15

The text that is shown needs separate strings for other browsers. The block of text used to only be shown for iOS Chrome users, but it was made more generic to show when WebRTC isn't available for any reason. The strings just weren't updated with a version looking for HTTP. https://github.com/bigbluebutton/bigbluebutton/blob/master/bigbluebutton-html5/imports/ui/components/audio/audio-modal/component.jsx#L357-L367

**Comment by ahmed89albttashi** [comment]
same problem appear here. 
client is : fedora 30 64

firefox 
![image](https://user-images.githubusercontent.com/6708191/64699661-519eaa80-d4b6-11e9-82ba-15ffb2253cbc.png)

**Comment by ffdixon** [comment]
@ahmed89albttashi, can you try test with https://appr.tc/ and let us know if it works there.

**Comment by ahmed89albttashi** [comment]
@ffdixon : 
firefox : 
![image](https://user-images.githubusercontent.com/6708191/64911881-5bcfdb80-d738-11e9-8cbe-2b7fa6fc4110.png)

chrome 
![image](https://user-images.githubusercontent.com/6708191/64912196-d864b900-d73c-11e9-988d-04a99d40393a.png)

**Comment by sparse91** [comment]
Same issue on Arch Linux with Firefox and Chrome.

**Comment by ffdixon** [comment]
I personally don't have much experience with FireFox on Fedora or Arch Linux.  BigBlueButton uses WebRTC to send/receive audio/video with remote users.  

If you visit https://test.webrtc.org/ and the microphone and camera tests fail, it means your current configuration (browser + OS) isn't supporting WebRTC.  

This isn't a BigBlueButton issue.  Not sure the solution here, but you need to get your browser + OS passing the tests at https://test.webrtc.org/ before you can run any application that uses WebRTC (including BigBlueButton).

**Comment by sparse91** [comment]
I Httpsifed BigBlueButton and problem solved. Sorry for interrupt.

**Comment by david020** [comment]
> I personally don't have much experience with FireFox on Fedora or Arch Linux. BigBlueButton uses WebRTC to send/receive audio/video with remote users.
> 
> If you visit https://test.webrtc.org/ and the microphone and camera tests fail, it means your current configuration (browser + OS) isn't supporting WebRTC.
> 
> This isn't a BigBlueButton issue. Not sure the solution here, but you need to get your browser + OS passing the tests at https://test.webrtc.org/ before you can run any application that uses WebRTC (including BigBlueButton).

Does this mean every user will have to be WebRTC compliant?

**Comment by ffdixon** [comment]
> Does this mean every user will have to be WebRTC compliant?

Yes.

If your browser does not support the WebRTC libraries, then there is no way for any HTML5-based application to send/receive audio or video.

**Comment by GhaziTriki** [comment]
Duplicate of https://github.com/bigbluebutton/bigbluebutton/issues/8244
