### ISSUE TITLE
How can I develop a desktop client

### ISSUE THREAD

**Issue by zsinba** [bigbluebutton/bigbluebutton#7821]
I wanted to use the BBB server program and then develop a desktop client for Windows and Mac.
Ask me how to get RTMP stream and authentication related interface. Then use RTMP player to develop a desktop software (non-web)。

**Comment by ffdixon** [comment]
The BigBlueButton project has a Flash client when it started in 2007, but we've moved on to building upon a pure HTML5 client.  

As such, all our focus is on the HTML5 client for BigBlueButton.  If your interested in building a desktop client, we would recommend starting with the HTML5 client and exploring technologies such as [Electron](https://electronjs.org/).

**Comment by zsinba** [comment]
I worry that HTML5 clients can't meet the requirements of clarity. I want the resolution to be 1080P or 4K. Can HTML5 meet this definition?
thanks.

**Comment by zsinba** [comment]
I tried using [CEF](https://bitbucket.org/chromiumembedded/cef) to build the client. The question came up:
1. If the Flash version is used, the comparison between 1080P and 1080P is displayed on the CEF client.
2. If it's an HTML5 client, I can't use desktop sharing. And under the same conditions, the stability and clarity of the Flash version.
Now I'm going to use C++ to write desktop clients, hoping to get RTMP streaming addresses to play directly.
Is this feasible?

**Comment by fcecagno** [comment]
I wouldn't consider RTMP as a feasible option, since Flash is being discontinued by the browsers and it should phase out progressively from BigBlueButton.

**Comment by zsinba** [comment]
What technology selection do you think should be used for live streaming?My requirement is 1080P live, millisecond latency.

Thanks for your reply.

**Comment by zsinba** [comment]
Yes, I developed a desktop client using Flex. And it runs well on Windows and Mac. It also worked well.
Are you doing that too?
I've tried using CEF before, opening a web page, and then loading FLash, and it doesn't work very well, especially when there's a lot of video.
Then I developed Desktop using Flex. It worked well, playing 1080P video, and could be used for multiple images with good latency.

**Comment by Beltrando** [comment]
> Yes, I developed a desktop client using Flex. And it runs well on Windows and Mac. It also worked well.
...
> Then I developed Desktop using Flex. It worked well, playing 1080P video, and could be used for multiple images with good latency.

Hello @zsinba I am very interested by your win/mac client. Is it possible to test it ?

**Comment by atharvPegasus** [comment]
> Yes, I developed a desktop client using Flex. And it runs well on Windows and Mac. It also worked well.
> Are you doing that too?
> I've tried using CEF before, opening a web page, and then loading FLash, and it doesn't work very well, especially when there's a lot of video.
> Then I developed Desktop using Flex. It worked well, playing 1080P video, and could be used for multiple images with good latency.

Me tooo can you share the repository for the same i can try on my PC and see if that works for me i also have the same requiremnt as you do

**Comment by zsinba** [comment]
![image](https://user-images.githubusercontent.com/890157/105443317-65f7d780-5ca6-11eb-8c13-0a14f87c0f41.png)

This is a function of surgical teaching live broadcast used by doctors. I made a client using BBB by referring to the function of Zoom.At the same time, the client reads an image of the medical device and displays it in real time.
In addition, I also made the function of real-time marking of images and synchronizing them to each end. Unlike the white board, I need to share and mark the videos in real time.

**Comment by zsinba** [comment]
At first, I used CEF to do this, using HTML5 methods, but HTML5 can't do it:
1.Take multiple cameras or stream files
2.1080P does not work well
3.The performance of the computer is relatively high, the general computer can not achieve normal operation
5.The delay will be large.
A desktop version developed using Flex addresses these issues.
It now includes the server side, the customer side, and the Web version.They are fully online.
Sorry this is a commercial application project, I can not share the small source code to you.

**Comment by zsinba** [comment]
Now I have some problems that I'm working on, and I'm making some progress.
Streams uplink using RTMP will not play properly on the WEB.
My solution:
Through the RTMP upstream stream, I converted to WebRTC for playback, so that the sharpness was very good, and the delay could be kept around 500ms.

**Comment by Beltrando** [comment]
Hello, 

I am very interested.

We manage 10.000 users of BBB for an non-profit organization in France, but we only started one month ago and many members are used to Zoom, and complain about sound / videos problems with BBB. I'm preparing a post about that. Anyway I can test your solution on a very large scale.

Maybe I can also ask one of our engineers to help you. I will ask.

**Comment by ffdixon** [comment]
> A desktop version developed using Flex addresses these issues.

Curious if you are using red5, Kurento, or some other back-end media server?

**Comment by zsinba** [comment]
> > A desktop version developed using Flex addresses these issues.
> 
> Curious if you are using red5, Kurento, or some other back-end media server?

Just BBB  to do it.
no other back-end media server.

![Uploading image.png…]()

**Comment by zsinba** [comment]
I also used BBB to make a version of the big screen, on the big screen can show all the current online students, they can talk to each other, at the same time can be the same as the real classroom experience.

![image](https://user-images.githubusercontent.com/890157/105934655-95825780-608b-11eb-8a38-783c2930f481.png)

**Comment by zsinba** [comment]
> Hello,
> 
> I am very interested.
> 
> We manage 10.000 users of BBB for an non-profit organization in France, but we only started one month ago and many members are used to Zoom, and complain about sound / videos problems with BBB. I'm preparing a post about that. Anyway I can test your solution on a very large scale.
> 
> Maybe I can also ask one of our engineers to help you. I will ask.

Our servers in China, you can prepare some servers and bandwidth resources, I will deploy one for you to do some trying.

**Comment by Beltrando** [comment]
> Our servers in China, you can prepare some servers and bandwidth resources, I will deploy one for you to do some trying.

We are preparing a server for testing this. I will send you a message as soon as it's ready.

**Comment by zsinba** [comment]
> > Our servers in China, you can prepare some servers and bandwidth resources, I will deploy one for you to do some trying.
> 
> We are preparing a server for testing this. I will send you a message as soon as it's ready.

Please let me know if there is any progress.
You need a Ubuntu16.04.

**Comment by zsinba** [comment]
> > Our servers in China, you can prepare some servers and bandwidth resources, I will deploy one for you to do some trying.
> 
> We are preparing a server for testing this. I will send you a message as soon as it's ready.

anything i can support?

**Comment by Beltrando** [comment]
Not yet... We are working on it
Bien à vous,

Eric Beltrando
eric@bilog.fr
Nos *528 projets*: http://www.bilog.fr/realisations
Standard:  +331 30 21 63 92
