### ISSUE TITLE
bbb-common-message fails to build on opensdk:9

### ISSUE THREAD

**Issue by pzhuk** [bigbluebutton/bigbluebutton#7822]
I am trying to build   bbb-common-message (latest/master) with openjdk 9 and this is the only failure which is the blocking successful build

```
[error] /bbb-common-message/src/main/java/org/bigbluebutton/common2/redis/RedisStorageService.java:25:1: package com.sun.org.apache.xpath.internal.operations is not visible
[error]   (package com.sun.org.apache.xpath.internal.operations is declared in module java.xml, which does not export it)
[error] import com.sun.org.apache.xpath.internal.operations.Bool;
[error] (Compile / compileIncremental) javac returned non-zero exit code

```

**Comment by ffdixon** [comment]
Is it an option for you to use the OpenJDK 8.  RedHat will be supporting it until 2023, see

  https://developers.redhat.com/blog/2018/09/24/the-future-of-java-and-openjdk-updates-without-oracle-support/

**Comment by pzhuk** [comment]
Yes, agree - saw it too. It's just sad that single unused(?) import is breaking it.
Would it be reasonable to just remove it?

```
--- a/bbb-common-message/src/main/java/org/bigbluebutton/common2/redis/RedisStorageService.java
+++ b/bbb-common-message/src/main/java/org/bigbluebutton/common2/redis/RedisStorageService.java
@@ -22,7 +22,6 @@ package org.bigbluebutton.common2.redis;
 import java.util.HashMap;
 import java.util.Map;
 
-import com.sun.org.apache.xpath.internal.operations.Bool;
 import org.slf4j.Logger;
 import org.slf4j.LoggerFactory;
```

**Comment by ffdixon** [comment]
> Would it be reasonable to just remove it?

Not sure ... I would say give it a go and let us know the results.

**Comment by ffdixon** [comment]
OK, for the moment, support for later versions of Java is still a WIP.
