### ISSUE TITLE
whiteboard and presentation part problem

### ISSUE THREAD

**Issue by hanif74** [bigbluebutton/bigbluebutton#7826]
Dear my friend
I installed BigBlueButton version 2.2-beta exactly from the instructions. when I go to demo page I have two option:
1- Try BigBlueButton via HTML5
2- Try BigBlueButton via Flash
When I login via Html5 the presentation part is OK and I can use tools to draw and I can go navigate between slides, but when I login via flash the presentation part and it's tools don't work. I cant draw and I cant navigate.

What should I do?

**Comment by capilkey** [comment]
We disabled SWF creation by default because most people using 2.2 are using the HTML5 client and the extra time it took to create the SWFs was wasted. There's a property in bbb-web that you can change to create SWFs in bigbluebutton.properties.

**Comment by hanif74** [comment]
how can I change that?

**Comment by capilkey** [comment]
Edit /usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties and change swfSlidesRequired to true. Restart BigBlueButton (bbb-conf --restart)

**Comment by hanif74** [comment]
Thank you my friend. I did it and it works fine. Thank you for your immediate answer.
