### ISSUE TITLE
Shorten reconnect time when audio dropps

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#7828]
Currently, when the audio connection from FreeSWITCH to the browser drops, the HTML5 client receives an event after about 15 seconds.  

Is it possible to shorten this time frame (perhaps the drop could be detected on the server and a message sent immediately through mongodb)?

**Comment by Jossef-767** [comment]
maybe this is related ,,,
I noticed a weird thing when there are more than about 20 users in the list.
1 of the user's  icon change to "dial in" icon ( there is no audio Bridge connected to my server) using "remove user" on this user has no effect.
saw this also on flash client user list in the past

**Comment by pedrobmarin** [comment]
@mariogasparoni what are your thoughts on this one?

**Comment by mariogasparoni** [comment]
We can close this one, since we are doing something very close to the best effort for audio negotiation, considering freeswitch doesn't implement trickle ice.   There are alternatives to speed up the audio negotiation but i believe they can be treated in a different issue.
