### ISSUE TITLE
Too slow to install bigbluebutton use bbb-install.sh

### ISSUE THREAD

**Issue by gittester2017** [bigbluebutton/bigbluebutton#7845]
I use bbb-install.sh to install bbb on Ubuntu Server, but the network is too slow when downloading bbb component from https://ubuntu.bigbluebutton.org, I did this in China.

Do you have any methods to improve the network, so I can have enough bandwith to install bbb?

**Comment by ffdixon** [comment]
We don't have any mirrors in China (yet).  Were you able to complete the installation?

**Comment by gittester2017** [comment]
Oh,I can not complete the installation, it's need about several days to complete.
I tried to use a EC2 machine in silicon valley and I can complete the installation in about 15 minutes ^_^, but it's too expensive to use a EC2 machine.

**Comment by ffdixon** [comment]
What are the specifications of the server upon which you are trying to install BigBlueButton?

**Comment by gittester2017** [comment]
Hi Fred,

Thanks for your reply, the server is a virtual machine with 1cpu,4 core,8GB Memory。
And the good news is I solve the bandwidth  problem with ExpressVPN, they have not been tested on Ubuntu Server 16.04, but it works for me and it's not too much expensive.

Thanks.
Best Regards.

**Comment by ffdixon** [comment]
> Thanks for your reply, the server is a virtual machine with 1cpu,4 core,8GB Memory。

For the benefit of others, you need to have (at least) 4 CPU cores to install BigBlueButton.  See

   http://docs.bigbluebutton.org/2.2/install.html

> And the good news is I solve the bandwidth problem with ExpressVPN, they have not been tested on Ubuntu Server 16.04, but it works for me and it's not too much expensive.

Nice.  If you need further help to install, be sure to join our mailing list (see https://bigbluebutton.org/support/).
