### ISSUE TITLE
When deleting the current presentation, upload dialog blocks user until they select a new presentation

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#7849]
Currently, when deleting the current presentation, the UI blocks the user until they select a new presentation (this requirement is not clear to the user).

![delete](https://user-images.githubusercontent.com/290351/62019780-676a4180-b18e-11e9-9b93-331bccf8de24.gif)

Instead, after deleting the current presentation, automatically select the default slide to the user can return back to the main screen.

**Comment by antobinary** [comment]
This has been addressed recently. What version of the client did you encounter it on?

**Comment by capilkey** [comment]
Can't reproduce this anymore so I'm going to close it.
