### ISSUE TITLE
Add emoji to feedback form to make rating scale more clear

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#7851]
Currently, our feedback form shows a 1-5 star rating.  To make it more explicit, we can add some emojis to show the range.

![image](https://user-images.githubusercontent.com/290351/62045755-33b20a80-b1d4-11e9-904f-2d999b2ebd9e.png)

**Comment by GhaziTriki** [comment]
@ffdixon This is the right way to go especially when you think about RTL users too.
