### ISSUE TITLE
Enable switching between presentations using the '+' menu

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#7852]
Currently, the presenter must go into the **Upload a presentation**  dialog to switch presentations.

Make it easier to switch by adding the list of presentations at the top of the '+' button.

![image](https://user-images.githubusercontent.com/290351/62046117-21849c00-b1d5-11e9-825a-d4568f823c83.png)

**Comment by mkpelletier** [comment]
This is a great idea.  I would suggest you go even further in adding library buttons on a popout toolbar on the *left* side that lets you page between presentations.

**Comment by ffdixon** [comment]
You can try it out now on https://test23.bigbluebutton.org/.

**Comment by mkpelletier** [comment]
Very nice! This is a simple but important change.  Well done to you and your team, Fred!

**Comment by iSamof** [comment]
Really Nice! Simple but excellent addition ... AND when switching back to a presentation, it maintains its previous page/position. 

One tiny point about the upload ... however many files are queued for upload are shown as "to be uploaded" ... which is correct. But the check mark was only against one of them. I was not sure which as dominant, the check mark or the text. They 'appear' at odds ... see attached image. Not an issue to worry about though.
![Upload-HTML5Client](https://user-images.githubusercontent.com/40075900/87776365-f355fd00-c827-11ea-9fae-f8aa3dd9d3e2.PNG)

**Comment by pedrobmarin** [comment]
Done in https://github.com/bigbluebutton/bigbluebutton/pull/8552
