### ISSUE TITLE
Whiteboad mouse drawing events are not accurate when using a graphic tablet

### ISSUE THREAD

**Issue by GhaziTriki** [bigbluebutton/bigbluebutton#7854]
When I use a graphic tablet to draw on the whiteboard, I have to press on the pen, move it some distance the I can drawing. Then to stop drawnig I have to press on the pen head again.

I tested the same scenario on paint and it draws without this odd behaviour.

**Comment by vasylOstrovskyi** [comment]
I noticed the same thing with my huion tablet using firefox on windows. The solution was to disable the "windows ink" option in the tablet pen settings.
On chrome and on and browser on linux machines the same device works as expected. So this is probably a deivce settings problem but not a BBB issue.
