### ISSUE TITLE
Webcams area resizable

### ISSUE THREAD

**Issue by vitormateusalmeida** [bigbluebutton/bigbluebutton#7855]

**Comment by aogilvie** [comment]
@vitormateusalmeida This is a welcome addition!
Our presenters often complain about the presentation being too small when the webcams do not overlap and on laptops screens that have a more "square" resolution.

Just out of curiosity, have you ever tried horizontal webcams?

![example](https://user-images.githubusercontent.com/970364/64089866-1cda7700-cd83-11e9-85a4-8776e9ef3209.png)

Here is an example I made, but with the new draggable interface we are not compatible with newer BBB versions. Do you think we could have draggable side positions???

**Comment by aogilvie** [comment]
I guess, what I want to ask is, with the dragging code, how hard would horizontal cams be to implement?

**Comment by vitormateusalmeida** [comment]
Hi @aogilvie 
I'll send the resize function to test, and after that I'll start to extend webcam placement to right/left of presentation in #7850 .
