### ISSUE TITLE
TURN server config for BBB: Wrong Path in the Docs?

### ISSUE THREAD

**Issue by otdftr** [bigbluebutton/bigbluebutton#7856]
According to http://docs.bigbluebutton.org/install/install.html#configure-bigbluebutton-to-use-the-coturn-server the TURN server has to be condigured in 
`/var/lib/tomcat7/webapps/bigbluebutton/WEB-INF/spring/turn-stun-servers.xml`

Editing this file has no effect in my installation, it seems not to be read by.
The correct path seems to ve
`/usr/share/bbb-web/WEB-INF/classes/spring/turn-stun-servers.xml`

(I used the bbb-install.sh installation method).

**Comment by capilkey** [comment]
That page is the BBB 2.0 install documentation and the location is correct. The BBB 2.2 TURN document has the correct location for 2.2 http://docs.bigbluebutton.org/2.2/setup-turn-server.html.
