### ISSUE TITLE
Unable to delete non-current presentation

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#7860]
There is a bug in the Upload Presentation dialog that prevents a user from deleting a presentation unless they first make it the current presentation.

![too many steps](https://user-images.githubusercontent.com/290351/62125686-d08bab00-b29b-11e9-936c-3bac3cc04a6e.gif)

The presenter should be able to delete any presentation except default.pdf.  

Furthermore, If they delete the current presentation, then BigBlueButton should automatically select the default.pdf as the current presentation; otherwise, it's impossible for the user to leave the confirm the action until they manually select another presentation as current (and not clear that they need to do so to exit the dialog).

**Comment by jfsiebel** [comment]
Couldn't reproduce this problem anymore.
