### ISSUE TITLE
I can't display the webcam's content

### ISSUE THREAD

**Issue by zsinba** [bigbluebutton/bigbluebutton#7883]
Hello, my dear,
 I used the camera (Logitech) CC4000e. After opening the webcam, there was a black picture, maybe I did not read the content of the camera normally. I'm sure my camera is good and I'm using the flash version. 
Is it because the camera is 4K HD? 
How can I use this camera correctly? 
What parameters need to be modified?

**Comment by ffdixon** [comment]
What BigBlueButton server are you using?  Can you try it against
 
  https://test.bigbluebutton.org/

and let us know if it works there.  Try switching between FireFox and Chrome.

**Comment by zsinba** [comment]
I used bbb-install. When I use the computer's own camera or a normal camera, everything is normal. But when I used a very high-resolution camera, Logitech CC4000e, something went wrong. So I wonder if it's not possible to decode such a high-definition camera

**Comment by capilkey** [comment]
It could be the 4K causing issues. A quick search seems to suggest that the plugin somewhat supports 4K videos, but it seems spotty.
