### ISSUE TITLE
Incorrect error message with accessing with HTTP (not HTTPS)

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#7884]
After installing BigBlueButton 2.2 to only use an IP address (no HTTPS), when logging in on a Macbook Air using the latest version of Chrome, BigBlueButton shows the following warning

![image](https://user-images.githubusercontent.com/290351/62463442-03301a80-b758-11e9-8473-0a7a95560627.png)

The message is misleading.

Instead, the message should warn the user that this server is not configured with a hostname + TLS certificate and therefore doesn't support sharing of media.

**Comment by GhaziTriki** [comment]
HTTPS is endorsed in favour of HTTP.
