### ISSUE TITLE
When I used java screen sharing and H264 encoding，Program Exit

### ISSUE THREAD

**Issue by caojincool** [bigbluebutton/bigbluebutton#7885]
When I used java screen sharing and H264 encoding, I found that the server could not find ffmpeg-3.0.2-1.2-linux-x86-h264.jar; could you update this jar to the server?

**Comment by ffdixon** [comment]
This error is from the Flash version of BigBlueButton.  Is it an option for you to install the latest build of BigBlueButton 2.2-beta and use the HTML5 version (no Java required).  See

  https://github.com/bigbluebutton/bbb-install

**Comment by ffdixon** [comment]
Closing as we are no longer working on the Flash version of BigBlueButton.  Recommend you install the latest build of BigBlueButton 2.2.  See

  https://github.com/bigbluebutton/bbb-install
