### ISSUE TITLE
presenterShareOnly option missing from config.xml

### ISSUE THREAD

**Issue by TomasRezende** [bigbluebutton/bigbluebutton#7886]
Hi,
Reading the docs, on page https://docs.bigbluebutton.org/2.2/customize.html, I found this "Restrict webcam sharing to the presenter" setting which is exactly what I need, but when I opened the config.xml file this setting is not there anymore. I found some people saying to use the lock system but the problem is that the presenter might unlock other people webcam (even if I tell them not to), and that can overload my server, since some livestreams may have thousands of users online at the same time. Is there a way to disable users webcams permanently? 
Thanks
Tomas

**Comment by capilkey** [comment]
I don't think the client will hold up if you put thousands of users into one meeting. It was never designed for those numbers. Even 500 users in one meeting requires a very powerful server.

As for the property, it looks like it last existed in BBB 1.0 and it was phased out when the lock settings were implemented.

**Comment by capilkey** [comment]
Going to close this as it's not an issue.
