### ISSUE TITLE
Develop desktop versions, Windows or android devices

### ISSUE THREAD

**Issue by zsinba** [bigbluebutton/bigbluebutton#7891]
Dear，
I'm going to make a desktop version of the application, but instead of using Html5 or Flash, I want to use C++ or C# as a client.In an embedded device, how do I get these protocols, certifications, display controls, etc.
Do you have any more Suggestions for me?
Thank you very much. This is the best system available

**Comment by capilkey** [comment]
We don't have documentation on all of the messages. The best thing to do would be to either use the Flash client and bbb-apps, or HTML5 client and HTML5 server, as references for what messages to send and what goes into them. There's no generic server component that your client can connect to so you'll need to develop a client and server-side component to connect to.

Of the existing endpoints bbb-apps runs on red5 and will be retired in one of the upcoming versions, and the HTML5 client/server use Meteor and and are a black box and I don't think a third-party client is possible.

**Comment by zsinba** [comment]
thanks so much.
The flash version may be the only option.

**Comment by zsinba** [comment]
thanks so much.
The flash version may be the only option.

**Comment by capilkey** [comment]
It's a very large task to write a new client from scratch. It's even more difficult when it's in a different language. It's almost always easier to modify the existing clients to meeting the necessary needs.
