### ISSUE TITLE
Style background image in presentation area

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#7901]
For branding and customization, provide a mechanism to create a meeting with a non-black background colour to the presentation area.

**Comment by melodoi** [comment]
I wount to have it and not black. Better is a immage or even a video. Zoom do it.

**Comment by matiasilva** [comment]
I believe there is a way to specify css for this with the "new" userdata params or am I mistaken?

**Comment by matiasilva** [comment]
@melodoi Just because Zoom do something doesn't mean that's the right thing for BigBlueButton to do. They might be similar in some aspects, but very dissimilar in others.

**Comment by pedrobmarin** [comment]
https://docs.bigbluebutton.org/2.2/customize.html#examples

Something like this
```
body {
  background-color:#000 !important;
}
```
