### ISSUE TITLE
Cannot interrupt audio Connecting process

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#7903]
In some cases it stays on for ~10sec. Clicking on X or in the background does nothing. No errors in console
![Screenshot from 2019-08-09 09-13-39](https://user-images.githubusercontent.com/6312397/62782023-53281d80-ba87-11e9-97cc-9c75b2c82617.png)
`Error during WebSocket handshake: Unexpected response code: 404` was the reason why it was taking so long in my case but the process should still be cancel-able

**Comment by iMonZ** [comment]
Off-topic: A feature to skip the echo test to quickly connect and speak would be amazing too!

**Comment by PhMemmel** [comment]
You already can skip the echo test. Check

https://github.com/bigbluebutton/bigbluebutton/blob/04a8d5e35929d2fd8e470e78e63c2259ad3970ae/bigbluebutton-html5/private/config/settings.yml#L14

and

https://github.com/bigbluebutton/bigbluebutton/blob/04a8d5e35929d2fd8e470e78e63c2259ad3970ae/bigbluebutton-html5/private/config/settings.yml#L20

This won't shorten your connection time as this is the time the audio needs to connect, not to load the echo test.
