### ISSUE TITLE
BUG: breakoutrooms "Randomly assign" bug

### ISSUE THREAD

**Issue by daminebenz** [bigbluebutton/bigbluebutton#7905]
Hi everyone,

So in this bug, when accessing the Breakoutrooms creating tab, after clicking **Randomly assign**, nothing will happen until you do an other action (any other click in any other button)

example below:
![breakoutrooms-bug](https://user-images.githubusercontent.com/33185490/62787636-84aae400-ba9b-11e9-9879-61ec4d34aed3.gif)

**Comment by ffdixon** [comment]
Good catch!  And thanks for recording the video on this as well -- very easy to see the issue.

**Comment by antobinary** [comment]
Were all users in the list moderators?

**Comment by daminebenz** [comment]
@antobinary no, they were just simple viewers  !
