### ISSUE TITLE
BUG: BreakoutRooms: everybody are moderators

### ISSUE THREAD

**Issue by daminebenz** [bigbluebutton/bigbluebutton#7913]
Hi BBB,

in the GIF below, you can see that in a BreakoutRoom, everybody are Moderators, even when they are normal Viewers in the main Room, and this a serious BUG.

![Peek 2019-08-12 15-50](https://user-images.githubusercontent.com/33185490/62890107-1f642680-bd19-11e9-9e2d-ca11dc7bf9a8.gif)

**Comment by antobinary** [comment]
This is actually by design. The breakouts need to be independently operated, without the moderator from the main room's help. For this we grant them moderator access in the breakouts. The user mode remains unchanged in the main room (parent room)
