### ISSUE TITLE
Zoom problem in mobile/tablet

### ISSUE THREAD

**Issue by jfsiebel** [bigbluebutton/bigbluebutton#7917]
If the presenter is using a phone or tablet, it is possible to break the presentation when zooming, and in mobile/tablet the zoom level don't have any boundaries.

Tested using the an iPad simulator and an Android phone.

![zoom-problem-tablet](https://user-images.githubusercontent.com/2110278/62893863-dfee0800-bd21-11e9-80d7-ae1af19bb7ce.gif)

**Comment by antobinary** [comment]
Addressed in #7918
