### ISSUE TITLE
bbb-web no longer starts after update due to forcing a secret change

### ISSUE THREAD

**Issue by aogilvie** [bigbluebutton/bigbluebutton#7919]
A "feature" (and bugs) have been added to BigBlueButton 2.2.0-beta-18  that prevents BBB from starting.

I have never seen anyone ask for this feature in the forum, so I am not sure the reasoning behind this.

When installing or updating BBB it is now required to change the API secret.
Maybe what intended as a security feature has just added problems and bugs for us.

- if setSecret is used to manually set a specific secret it is not considered unless different
- a BBB update forces a user to change of secret
- because of the above BBB update will always fail to start for automated updates
- changing an API secret means changing configuration in apps that are dependent upon using this API
- if this is a security feature it's bad because you can hack around it using `sudo systemctl start bbb-web.service`

Please roll back this modification.

**Comment by capilkey** [comment]
There's no requirement to change you secret on every update. Four months ago there was a change to the bbb-conf script that checks for a very specific secret and tells you to change it, but that is all and it definitely wasn't recent.

There's no modification to roll back.
