### ISSUE TITLE
BUG: any kicked user has echo test enabled

### ISSUE THREAD

**Issue by daminebenz** [bigbluebutton/bigbluebutton#7920]
Hi BBB,

after kicking out a user from Presentation, at the 403 screen, the user will have echo test enabled.

![image](https://user-images.githubusercontent.com/33185490/62949377-740cad80-bdbc-11e9-9f11-cd2dc314e021.png)

**Comment by prlanzarin** [comment]
@daminebenq ping, I think this has been fixed by now, hasn't it?

**Comment by daminebenq** [comment]
@prlanzarin yes indeed.
