### ISSUE TITLE
Rendering of chat that is not currently displayed

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#7926]
We seem to render chat messages as they come on all "channels" -- if I currently have a private chat active (open) but there is a new incoming chat message on the public chat, some unnecessary renderings will occur for a component that is not displayed.

This was encountered while testing #7915 
![Peek 2019-08-14 14-54](https://user-images.githubusercontent.com/6312397/63049341-6fbcbf00-bea6-11e9-9929-08f47fa71556.gif)
In the gif above, incoming private messages cause rerenders while public chat is the only one open

Likely this code is rerun to allow the unread chat counters/notifications to work, however, that should not require the chat to be rerendered.
On the other hand, when switching chat channels, we may want to minimize starting from scratch every time. Likely this will have to be inspected closely to see what approach would work best.

**Comment by GhaziTriki** [comment]
@antobinary Is the issue still present?

**Comment by prlanzarin** [comment]
Has to be revisited after the work done in https://github.com/bigbluebutton/bigbluebutton/pull/11173 and siblings.
