### ISSUE TITLE
The text in the recording button is cut off on mobile phone devices. 

### ISSUE THREAD

**Issue by tylercopeland** [bigbluebutton/bigbluebutton#7934]
![Screen Shot 2019-08-15 at 10 17 19 AM](https://user-images.githubusercontent.com/1273169/63100953-1ad08580-bf46-11e9-89ff-f416e612addb.png)

One thought that comes to mind is to remove the session name on mobile phone devices (since we are only showing a few characters) to give room for the recording button. Just a thought tho, open to other suggestions. :)

**Comment by daminebenz** [comment]
or also to just shorten it to **Resume record** ?

**Comment by pedrobmarin** [comment]
Could we also remove the recording button's text from mobile? It would help avoiding this one too https://github.com/bigbluebutton/bigbluebutton/issues/11816
