### ISSUE TITLE
akka-bbb-fsesl duplicates ESL events on ESL reconnections

### ISSUE THREAD

**Issue by prlanzarin** [bigbluebutton/bigbluebutton#7941]
When there's a reconnection between akka-bbb-fsesl and fsesl, the ESL event handlers get duplicated. For each reconnection, a new event handler is set up, which makes akka-bbb-fsesl generate duplicated events (one for each reconnection).

The reconnection, specifically, seems to work properly. There aren't dangling connections to `8021` between akka-bbb-fsesl and FreeSWITCH, so I guess this is a problem with the event handler setup.

Steps to reproduce:
  - Kill the `8021` tcp connection (e.g.: using tcpkill (`tcpkill -i lo -9 port 8021`).
  - Wait for akka-bbb-fsesl to trigger a reconnection.
  - Re-join audio. Watch for redis events on redis-cli monitor (e.g.: `-i userjoinedvoiceconf`)

**Comment by ritzalam** [comment]
Fixed in https://github.com/bigbluebutton/bigbluebutton/pull/8204
