### ISSUE TITLE
Client crash after iOS user's device went in sleep mode (dimmed screen)

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#7943]
Chat/service.js

```
const sender = getUser(message.sender);
    const {
      color,
      role,
      name,
      connectionStatus,
    } = sender;
```

I20190815-10:28:30.712(-4)? error: {"logCode":"startup_error","logDescription":"TypeError: sender is null","extraInfo":{"stackTrace":"TypeError: sender is null\nmapGroupMessage@https://anton.blindside-dev.com/html5client/app/app.js?hash=674c4c34f9b3327dd7247c6e65f5cc8ab87822a0:8456:9\nreduceAndMapGroupMessages@https://anton.blindside-dev.com/html5client/app/app.js?hash=674c4c34f9b3327dd7247c6e65f5cc8ab87822a0:8495:88\ncontainer.jsx/<@https://anton.blindside-dev.com/html5client/app/app.js?hash=674c4c34f9b3327dd7247c6e65f5cc8ab87822a0:8261:50\ngetMeteorData@https://anton.blindside-dev.com/html5client/packages/react-meteor-data.js?hash=3eb71c8be34187279959ee0c4920015c6cd9556f:268:14\ncalculateData/this.computation</<@https://anton.blindside-dev.com/html5client/packages/react-meteor-data.js?hash=3eb71c8be34187279959ee0c4920015c6cd9556f:142:28\n_compute@https://anton.blindside-dev.com/html5client/packages/tracker.js?hash=a9bdf2f732520305683f894b4b4d4d49d90cbe05:332:38\nComputation@https://anton.b...

![Screenshot from 2019-08-15 10-31-42](https://user-images.githubusercontent.com/6312397/63101849-ee1d6d80-bf47-11e9-9b53-f1374dadba6d.png)

**Comment by prlanzarin** [comment]
@antobinary do you know if this is still a thing? Seems not to be the case anymore.
