### ISSUE TITLE
Invalid Bigbluebutton endpoint and secret

### ISSUE THREAD

**Issue by nilarwin** [bigbluebutton/bigbluebutton#7949]
When I login in bigbluebutton, invalid bigbluebutton endpoint and secret .
So I updated shared secret at .env file.But I get the same error.
when I run " bbb-conf --check ", the following error show.
Pls, help.Thanks

![Capture](https://user-images.githubusercontent.com/14857970/63249157-e1be4b00-c28e-11e9-88ac-434740b657c3.PNG)

**Comment by ffdixon** [comment]
Are you using GreenLight as a front-end?  If so, can you makes sure that the `.env` file has the shared secret given in `bbb-conf --secret` (with no spaces).

**Comment by nilarwin** [comment]
@ffdixon ,
I'm using greenlight. In .env file,I already add shared secret with no spaces.But I still get above error.Thanks.

**Comment by ffdixon** [comment]
What happens when you [verify the Greenlight configuration](http://docs.bigbluebutton.org/greenlight/gl-install.html#verifying-configuration)?

**Comment by nilarwin** [comment]
I installed greenlight at my local virtual machine.When I verify configuration of Greenlight, I face following error.

"
Checking environment : Passed
Checking Connection : Failed
Error: connecting to BigblueButton server - SSL_connect returned=1 errno=0 state=error: certificate verify failed (self-signed certificate) "

**Comment by ffdixon** [comment]
> Error: connecting to BigblueButton server - SSL_connect returned=1 errno=0 state=error: certificate verify failed (self-signed certificate) "

The problem is that the docker container running Greenlight is trying to make a SSL connection to your BigBlueButton server, but because you have a self-signed certificate, it can't validate it.

Is it an option for you to use a real certificate (such as one generated using Let's Encrypt)?

**Comment by nilarwin** [comment]
Thanks.
I would like ask to integrate bigbluebutton (2.2 beta) and LMS of open edX with LTI.
So, I install LTI in bigbluebutton server.When I run sudo bbb-conf --lti , nothing come out.
Pls suggest me.

**Comment by ffdixon** [comment]
> I would like ask to integrate bigbluebutton (2.2 beta) and LMS of open edX with LTI.

We've done some updates recently on `bbb-lti` with the purpose of testing it with edX.  These updates should be in the next build of BigBlueButton 2.2-beta (subscribe to the Google group [bigbluebutton-dev](https://bigbluebutton.org/support/community/) for notifications of new versions).

> So, I install LTI in bigbluebutton server.When I run sudo bbb-conf --lti , nothing come out.

We are interested in you trying it again when we release the next update to BigBlueButton 2.2-beta.

**Comment by matiasilva** [comment]
Closed due to inactivity.
