### ISSUE TITLE
Audio issue while incoming call. 

### ISSUE THREAD

**Issue by netlabs** [bigbluebutton/bigbluebutton#7956]
Hello All,

If user is attending conference from mobile and uses Chrome, all good. But when he gets a call and comes back to conference his audio will be out from earpiece but not from speaker.

To reproduce
1. Join conference with Mic
2. Call to the mobile, pick and finish the call.
3. Check back the conference, your audio will be from earpiece.

**Comment by ffdixon** [comment]
The output is determined from the operating system.  If it changed underneath the current browser session, it might mess up the output.

In the above cases, we would recommend the user refresh their browser and have it reconnect to the current speaker output as defined by the OS.
