### ISSUE TITLE
Can't locate package bbb-conf -- lti after installing the bbb-lti package in bbb 2.2 beta

### ISSUE THREAD

**Issue by aye-moh-moh** [bigbluebutton/bigbluebutton#7961]

**Comment by aye-moh-moh** [comment]
Hi
i can't locate package bbb-conf -- lti after install installing the bbb-lti package in bbb 2.2 beta

![bbb](https://user-images.githubusercontent.com/54351365/63415203-5d510100-c423-11e9-973b-2acffb28779e.png)

**Comment by ffdixon** [comment]
We recently worked on the `bbb-lti` package and `bbb-conf --lti`, and you should see them working as expected in the next update to BigBlueButton 2.2-beta (watch the [bigbluebutton-dev](https://bigbluebutton.org/support/community/) mailing list for announcements).

**Comment by GhaziTriki** [comment]
LTI is working in the 2.2.x releases.
