### ISSUE TITLE
Microphone lock affecting moderator

### ISSUE THREAD

**Issue by jfsiebel** [bigbluebutton/bigbluebutton#7966]
##### How to reproduce
- Lock Microphone for the meeting
- Try to Join Audio

##### Update
A viewer can join with microphone even when locked

![lock-mic-affect-mod](https://user-images.githubusercontent.com/2110278/63455160-9b015a00-c422-11e9-9b48-1d5fe6f3b605.gif)

**Comment by ffdixon** [comment]
Good catch!  It's affecting demo as well.
