### ISSUE TITLE
Chat messages are unnecessarily heavy to render

### ISSUE THREAD

**Issue by capilkey** [bigbluebutton/bigbluebutton#7976]
In the HTML5 client we made the decision to add the user's role and offline/online status to the rendering of every message. In order to implement this every chat message needs to look up the sender's user information to find their role and online/offline status. The extra lookup required for each rendered message leads to performance issues when there are lots of messages and lots of users.

My recommendation would be make the chat data static like it used to be to remove the need to look up additional information before rendering.

![image](https://user-images.githubusercontent.com/1395090/63619315-485ba580-c5bc-11e9-8736-6e9f1cc3acd5.png)

**Comment by franzgratzer** [comment]
We also encountered big performance penalties when there are many chat messages. The best option to keep performance at a reasonable level was deleting the chat history very frequently. It would be great to at least have the option to decide if one wants to use a plain static chat instead of one that displays the status of the users (for the performance penalty).

**Comment by ffdixon** [comment]
We are working on [BigBlueButton 2.3-dev](https://docs.bigbluebutton.org/dev/dev23.html) (under development) which improves the chat performance to use a virtualized list that only renders the visible messages.

**Comment by antobinary** [comment]
In 2.3 we only look up information for messages that are currently rendering on the screen (the visible chat messages). Additionally these `role` and `status` properties are no longer stored in the chat message structure.
https://github.com/bigbluebutton/bigbluebutton/blob/develop/bigbluebutton-html5/imports/ui/components/chat/time-window-list/time-window-chat-item/container.jsx#L48

Rendering of chat messages is much lighter on 2.3.x compared to BBB 2.2.x.
Link to a comparison of chat messages load in 2.3 vs 2.2: https://github.com/bigbluebutton/bigbluebutton/issues/8554#issuecomment-822439268
