### ISSUE TITLE
Storing offline users for the full duration of the meeting leads to performance issues

### ISSUE THREAD

**Issue by capilkey** [bigbluebutton/bigbluebutton#7977]
In the HTML5 server and client we store all users who have joined a meeting for the full life-cycle of the meeting. There's no large impact for normal meetings that have a length of 1-2 hours, but for cases where there are long running meetings (24hr or more) there might be many users who come and go throughout the life of the meeting. By storing the past users forever we run into memory and performance issues because those users that are never going to come back constantly need to be looked through.

The only reason for us storing those users that I'm aware of is so that we know their last role for rendering the chat messages. See #7976.

**Comment by pedrobmarin** [comment]
Handled in https://github.com/bigbluebutton/bigbluebutton/pull/10368 and being reworked since
