### ISSUE TITLE
Could not connect to the configured hostname/IP address

### ISSUE THREAD

**Issue by aye-moh-moh** [bigbluebutton/bigbluebutton#7984]
Hello 
i installed 2.2 beta.
when i check  **bbb-conf -- check**  after assigned hostname ,

................................................................................
# Error: Could not connect to the configured hostname/IP address
#
#    https://hostname/
#
# If your BigBlueButton server is behind a firewall, see FAQ.

# Error: Unable to reach default URL for presentation:
#
#    https://hostname/default.pdf
#
# Check value for beans.presentationService.defaultUploadedPresentation in
#   /usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties

-----------------------------------------------------------------------------------------
plz help me ......

**Comment by matiasilva** [comment]
No follow up in a year. Closing for now but feel free to follow up at https://groups.google.com/forum/#!forum/bigbluebutton-setup.
