### ISSUE TITLE
certificate verify failed

### ISSUE THREAD

**Issue by aye-moh-moh** [bigbluebutton/bigbluebutton#7985]
i don't use self-signed ssl certificate but i get this error
plz help me...
....................................................................................................................................................................................................

root@ank-Virtual-Machine:~/greenlight# docker run --rm --env-file .env bigbluebu                                                        tton/greenlight:v2 bundle exec rake conf:check

Checking environment: Passed
Checking Connection: Failed
Error connecting to BigBlueButton server - SSL_connect returned=1 errno=0 state=                                                        error: certificate verify failed (unable to get local issuer certificate)
root@ank-Virtual-Machine:~/greenlight#

**Comment by ffdixon** [comment]
Greenlight, which is running within Docker, does not have a root certificate for your self-signed certificate, so it can't validate the HTTPS call to BigBlueButton.

Is it an option for you to install BigBlueButton 2.2 on a public server (with a public IP address) and assign a hostname?  

If so, then you can use [bbb-install.sh](https://github.com/bigbluebutton/bbb-install) to install/configure BigBlueButton + Greenlight with a SSL certificate.

**Comment by jdanders** [comment]
I worked around this issue in the hackiest way possible. I added these commands to the startup script within the docker image:
```
wget -q --no-check-certificate https://[internal.site]/[myselfsigned-ca.cert.pem] && cp [myselfsigned-ca.cert.pem]  /usr/local/share/ca-certificates/ && update-ca-certificates >& /dev/null
```
On my system, the startup script file was located here:
```
/var/lib/docker/overlay2/4cdf7d3175fcb14207b0f4a217c04989d13f023a7677c8f66010261ca7d677c0/diff/usr/src/app/bin/start
```
You can use `sudo docker inspect bigbluebutton/greenlight:v2` and look at the various 'Dir' variables to find yours. I'm sure a docker expert could tell us the correct way to edit a file within the image. This hack will probably be lost on the next docker image update.

Devs: 
Would it be possible to add an environment variable to specify a location to fetch the self-signed root certificate? Then you could add a similar step to the start up process without this terrible hack.

I'm thinking all the user would need to do is add something like this to the `~/greelight/.env` file:
```
ROOT_CERTIFICATE_URL=https://[internal.site]/[myselfsigned-ca.cert.pem]
```

Note: The `--no-check-certificate` is needed because my server is using the cert that isn't trusted yet. The `-q` and redirect are needed because the startup script fails if anything is printed to stdout.

**Comment by sim0nx** [comment]
@jdanders I had the same problem as you. Here is an easier solution.
Create a *Dockerfile* with the following content:
```
FROM bigbluebutton/greenlight:v2
COPY ./ssl/mycustomsslca.crt /root/

RUN cp /root/mycustomsslca.crt /usr/local/share/ca-certificates/ \
        && /usr/sbin/update-ca-certificates
```

Customise your *docker-compose.yml* as follows:
```
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: [bin/start]
    #image: bigbluebutton/greenlight:v2
....
```

Build the container:
```
docker-compose build
```

Then start your container as described in the docs:
```
docker-compose up -d
```

That works fine for me.

**Comment by jdanders** [comment]
Thanks @sim0nx that is definitely a lot cleaner.

**Comment by mrhmrhmr** [comment]
Thanks @jdanders this was exactly the right way to fix it!
After searching for a lot of hours you found the cleanest way to solve it.

**Comment by marcoz9090** [comment]
Hi @sim0nx,
thank you for posting this.
However I'm having some issues, probably because of my n00b knowledge of docker.
I did the following:
- created ssl folder in the same folder where "docker-compose.yml" and "Dockerfile2" are
- created "Dockerfile2" with the content you wrote above
- Modified "docker-compose.yml" so that it looks like
version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile2
    entrypoint: [bin/start]
#    image: bigbluebutton/greenlight:v2
    container_name: greenlight-v2
    env_file: .env
...................
Run "docker-compose build", but I noticed nothing happened (my key has not been copied to "/usr/local/share/ca-certificates/" and "/usr/sbin/update-ca-certificates")
- Run "docker-compose down"
- Run "docker-compose up -d"

But the error is still there when I run
docker run --rm --env-file .env bigbluebutton/greenlight:v2 bundle exec rake conf:check

I'm using a certificate from a Windows CA.

Thank you and sorry to bother on this topic.

![attach](https://user-images.githubusercontent.com/64978717/81322424-3e1f0000-9094-11ea-9113-35bf0ffbc83e.PNG)

- created

**Comment by sim0nx** [comment]
> Hi @sim0nx,
> thank you for posting this.
> However I'm having some issues, probably because of my n00b knowledge of docker.
> I did the following:
> 
> * created ssl folder in the same folder where "docker-compose.yml" and "Dockerfile2" are
> * created "Dockerfile2" with the content you wrote above
> * Modified "docker-compose.yml" so that it looks like
>   version: '3'
>   services:
>   app:
>   build:
>   context: .
>   dockerfile: Dockerfile2
>   entrypoint: [bin/start]
>   #image: bigbluebutton/greenlight:v2
>   container_name: greenlight-v2
>   env_file: .env
>   ...................
>   Run "docker-compose build", but I noticed nothing happened (my key has not been copied to "/usr/local/share/ca-certificates/" and "/usr/sbin/update-ca-certificates")
> * Run "docker-compose down"
> * Run "docker-compose up -d"
> 
> But the error is still there when I run
> docker run --rm --env-file .env bigbluebutton/greenlight:v2 bundle exec rake conf:check
> I'm using a certificate from a Windows CA.
> 
> @jdanders
> by running "sudo docker inspect bigbluebutton/greenlight:v2 |grep Dir"
> I see the following, but I don't see any /bin/start Dir: which one should I use?
> 
> ```
>         "WorkingDir": "/usr/src/app",
>         "WorkingDir": "/usr/src/app",
>             "LowerDir": "/var/lib/docker/overlay2/f0527c9406f488df3c82c2ffa4746d6ec7ab668da7e459d5d498fb9f1832b4b0/diff:/var/lib/docker/overlay2/4f52e6ca3cb4f9b41d14dab1452d5116c2c8726bfa6f34c66168445e1ad7db4e/diff:/var/lib/docker/overlay2/74d90817e06625f61d76a05c5e4485671c8a9ec6b55c343e604ab844f9a53227/diff:/var/lib/docker/overlay2/aa03c3155d3f770f1f4249ef9b6a0464f45dd1639e2be65ed266adc34ea2e16b/diff:/var/lib/docker/overlay2/1e5eb333dd136158da29b5f3ce8a5fd50a13e4325cb075c3ca2ea966199d6397/diff:/var/lib/docker/overlay2/77c3f0208fcd04bf5750659d3ea318971f8b5c6354133cc545b26db4e31eacf7/diff:/var/lib/docker/overlay2/fbf05cd49f8a1b0c45ec896348fd306b1ff9a58f6ce1a80a1df8257875f7afa3/diff:/var/lib/docker/overlay2/9ba41f48fd28ee457a902cb7f9d523b42df093c5d37630282223f7de7da9f820/diff:/var/lib/docker/overlay2/fc225e0a0e694f6a0927039a26921fa4c81c38218d091c2b3af21d60caac0053/diff:/var/lib/docker/overlay2/2e9affea0fd442e4601567fd1c4eea18c5c9a2b77ed172c7cd534269eaa4f204/diff:/var/lib/docker/overlay2/2765d91cde003aec95b142db7b24fc372d62ef785be23ab9542919d0339e2659/diff:/var/lib/docker/overlay2/251a5c2817fa63f90cba27753f35b33d5a6de36e8703cacdfa35922a99c326e9/diff:/var/lib/docker/overlay2/b2643e61d824091da6b60d6d64337ed715866572c053a21bc82360b215f4de40/diff:/var/lib/docker/overlay2/57a867de49790a913f190dd3203d50273ee6311498aa47ea6e23ff01ca856fba/diff",
>             "MergedDir": "/var/lib/docker/overlay2/38340dbdf66280e8d52a0da96b8e5c0a9122570f1825e947d2d4ae9e2a643f50/merged",
>             "UpperDir": "/var/lib/docker/overlay2/38340dbdf66280e8d52a0da96b8e5c0a9122570f1825e947d2d4ae9e2a643f50/diff",
>             "WorkDir": "/var/lib/docker/overlay2/38340dbdf66280e8d52a0da96b8e5c0a9122570f1825e947d2d4ae9e2a643f50/work"
> ```
> 
> Thank you and sorry to bother on this topic.
> 
> ![attach](https://user-images.githubusercontent.com/64978717/81322424-3e1f0000-9094-11ea-9113-35bf0ffbc83e.PNG)
> 
> * created

hi @marcoz9090 hmm I can't try it right now to see for myself, but can you try with

```
docker-compose build --no-cache
```

to see if that helps ?
With the build command you should see some steps it does with copying the file etc.
My guess is that you didn't because the container was already built before.

**Comment by jdanders** [comment]
> @jdanders
> by running "sudo docker inspect bigbluebutton/greenlight:v2 |grep Dir"
> I see the following, but I don't see any /bin/start Dir: which one should I use?
> 

I ended up searching all of the `/var` ones and editing multiple places. It's an overlay system so you have to know more than I do about Docker to know which is which. 

To find if it has the file you can run a command like this: 
```bash
find /var/lib/docker/overlay2/38340dbdf66280e8d52a0da96b8e5c0a9122570f1825e947d2d4ae9e2a643f50/merged -name "start"
```
Search each of the four directories and edit any that end in `usr/src/app/bin/start`

**Comment by marcoz9090** [comment]
Thank you @jdanders.
Anyway, nevermind: I found that the certificate had been added correctly, but it was pasted in a single line and that caused it to not work.
I pasted it again in multiple lines (like all the others CA are stored) and it worked following @sim0nx procedure.

Thank you again and I hope that could help others.

**Comment by gaurav-vijayvergia** [comment]
Hello,
1. I'm running BigBlueButton 2.2 on a public server (with a public IP address) and assigned a hostname "conference.sambaash.com" 
2. Installed greenlight

It worked for around 10-15 days and then it started throwing me the ssl error. Followed the above steps to add the root ca but still no luck. Not sure why it is still throwing this error.

<img width="1177" alt="Screenshot 2020-06-08 10 56 27" src="https://user-images.githubusercontent.com/872460/83988926-55912780-a977-11ea-99e6-e8afea97394d.png">


<img width="1203" alt="Screenshot 2020-06-08 11 02 18" src="https://user-images.githubusercontent.com/872460/83988988-87a28980-a977-11ea-8e07-c8476c315250.png">


Please help. Thanks in advance. @jdanders  @ffdixon

**Comment by marcoz9090** [comment]
Hi @gaurav-vijayvergia,
I'm pretty new to bigbluebutton, but check if your root certificate is expired
https://support.sectigo.com/articles/Knowledge/Sectigo-AddTrust-External-CA-Root-Expiring-May-30-2020

**Comment by gaurav-vijayvergia** [comment]
Hi @marcoz9090 , thanks for the pointer. It actually resolved the issue. Didn't notice the certificate chain issue until u pointed out.

**Comment by matiasilva** [comment]
Good discussion. Closing now as this issue seems to be resolved for all parties.
