### ISSUE TITLE
Give presenters the option to push their current layout to viewers

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#7987]
The BigBlueButton client allows the user to make changes to their layout

  - show/hide the Users list (and the associated public/private/shared notes panes)
  - minimize the presentation (when webcams are being shared)
  - Drag the webcams to the top/bottom
  - Give focus to a particular webcam (when focus is enabled)

In the Flash client, the presenter could "push" down their current layout to other students.  In contrast, the HTML5 client does not have windows, but the above layout changes could be pushed down by the presenter.

A good use case is sign language.  There are times when a presenter wants to ensure their webcam is larger that all others and hide the presentation window.  This gives students the largest possible view of the presenter demonstrating sign language.

We need to add a similar "push" capability in the HTML5 client.

**Comment by superseby2** [comment]
Any chance to have this feature promoted ? This would make BBB a much better webinar tool if the presenter can switch from one layout to another while speaking. 

Thx !

**Comment by matiasilva** [comment]
Doesn't address the entire issue, but for presentation events, you can use the `bbb_force_restore_presentation_on_new_events=true` to the join API call, available [here](https://github.com/bigbluebutton/bigbluebutton/blob/v2.2.x-release/bigbluebutton-html5/imports/api/users-settings/server/methods/addUserSettings.js).

**Comment by ryprfpryr** [comment]
Hi @ffdixon 
For accesibility reasons this feature is very important. From this point of view, presenters should be able to push their layout for other students.

**Comment by robboho** [comment]
Hi matiasilva,
any news on "the moderator's actions to be synchronized across all participants' windows". 

In particular, the display of presentations controlled and pushed by the moderator would be an important feature for us.
Especially when a user has hidden the first (default) presentation, it is very difficult to draw attention to the appearance of the following presentations. We keep getting messages like: "Which presentation are you talking about!"

**Comment by ffdixon** [comment]
We might get to the ability to have the presenter "push" down their layout in 2.4.  At the moment, we're working towards getting another build of 2.3-dev out to the community.  https://docs.bigbluebutton.org/dev/dev23.html

**Comment by AInteriorB** [comment]
> In particular, the display of presentations controlled and pushed by the moderator would be an important feature for us.
> Especially when a user has hidden the first (default) presentation, it is very difficult to draw attention to the appearance of the following presentations. We keep getting messages like: "Which presentation are you talking about!"

I think both ways are important: We would like to hide the entire slide area if we only have a conference without presentation (e.g. discussion after presentation). So an actual option "hide presentation for everybody" is needed (better explained in #9937). And the way back, if one decides to start a presentation: "show presenation area if presentator activates a new slide show".

I have experimented with hidePresentation and autoSwapLayout in `/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml` but with no luck. Any combination either broke the presenation or the audience had to actively click on "show presentation". But even then the area was smaller as usual and thus not usable...

**Comment by einhirn** [comment]
Is this related (waiting-for?) to the layout manager refactoring #14146?

Also, I found mentions of `public.presentation.restoreOnUpdate: true` setting in `settings.yml` in other issues (Bug report for 2.2.x -> 9866, Bug report for 2.4.x -> 14168 - but I don't want to "mention" those issues here...). Maybe that would help at least a bit? (That is, if it break nothing else)

**Comment by TheJJ** [comment]
We're also running with `layout.autoSwapLayout=true` and `presentation.restoreOnUpdate: true`, so the presentation is initially hidden and one can have video calls without having to minimize the presentation.
This works nearly perfectly, except for latecomers: #14689 is a problem because screenshares are not opened, and presentations are not shown unless there's a slide change etc.

Better would be to either let the non-moderators follow the presenter's "presentation display state", or make the presentation show up even for newly connected users when a non-default presentation is loaded.

**Comment by TheJJ** [comment]
How about an implementation like this as a possible first step:
Add an "empty" presentation slot.

Whenever it is active (selectable just like a slideset which can be also configured to be the "default" presentation (additionally to the real default presentation)), the presentation/screenshare/... is empty and thus minimized.

This would mean when a new slideset is activated, it gets visible for all participants, same goes for screenshares or shared videos.

When the screenshare ends, or one selects the "empty" slot, its minimized/hidden again.

**Comment by antobinary** [comment]
Implemented as part of BBB 2.6

![Screenshot from 2022-12-14 10-39-30](https://user-images.githubusercontent.com/6312397/207640506-70d709b7-fa7e-4897-9354-23751e6c4f7b.png)


![Screenshot from 2022-12-14 10-38-59](https://user-images.githubusercontent.com/6312397/207640452-724e59ed-ad59-40b2-8a57-974352659c27.png)
