### ISSUE TITLE
Error 1020: Media could not reach the server only in safari in BBB -2.2 beta

### ISSUE THREAD

**Issue by yasithph** [bigbluebutton/bigbluebutton#7988]
I have setup BBB -2.2 beta in an aws server. I get the error 'Error 1020: Media could not reach the server' when turning on the video in safari(Both ios and macOs). It works well both in chrome and firefox. If one client is connected in the conference, the video works well in safari as well. But if there are no chrome users, safari cannot initiate the call itself.

**Comment by yasithph** [comment]
We managed to fix this with configuring a google's public STUN server.

**Comment by kevin-og** [comment]
> We managed to fix this with configuring a google's public STUN server.

Hi @yasithph can you state which configuration file you used, and STUN server so I can try to resolve using the same method?
