### ISSUE TITLE
Drag camera and alt+tab does not end to drop

### ISSUE THREAD

**Issue by GhaziTriki** [bigbluebutton/bigbluebutton#7991]
- Start dargging a camera.
- ALT+TAB to change the current window.
- Release the mouse.
- ALT+TAB again to BigBlueButton browser window.
- Move the mouse and you will see the camera still being dropped.

**Comment by PlumedArcher** [comment]
This is still reproducible with Google Chrome Version 89.0.4389.114 and BBB 2.3-beta-1.

**Comment by prlanzarin** [comment]
@PlumedArcher which OS  were you using when reproducing this issue?

Because I can't reproduce it in Chrome nor Firefox under Buster/Xfce and Mint/Cinnamon. So wondering if I'm missing any step (I sure am not) or it's an OS/display system specific issue.

**Comment by PlumedArcher** [comment]
@prlanzarin I am using Windows 10 ( Education, Version 20H2, Build 19042).
Just tested again and could reproduce on clientversion 1588.
