### ISSUE TITLE
The unread messages indicator doesn't appear when private chatting with a long name person

### ISSUE THREAD

**Issue by capilkey** [bigbluebutton/bigbluebutton#8002]
If you private chat with a person with a long name, the name is truncated and it pushes the unread message indicator out of view.

The following image is from a fresh private chat that is unopened and unviewed.

![image](https://user-images.githubusercontent.com/1395090/63795217-76e5c300-c8d1-11e9-99cd-a88d61ed740a.png)

Tested with build 687 (latest master)

**Comment by daminebenz** [comment]
one more detail:

the problem can be found in many client languages
Portuguese, Spanish, Persian..., etc...
![image](https://user-images.githubusercontent.com/33185490/63948784-a6bad500-ca4f-11e9-8fd5-f633393f59b4.png)

**Comment by capilkey** [comment]
Looks like it also happens with the "(You)" text in the users list.

![image](https://user-images.githubusercontent.com/1395090/63978878-78f08300-ca85-11e9-967a-19f317f48a58.png)

**Comment by capilkey** [comment]
I'm not seeing an option to clear the public chat from my moderator client. My viewer client can't clear either, but that's expected.
