### ISSUE TITLE
Click outside whiteboard tools menu does not close it when no tool is selected

### ISSUE THREAD

**Issue by GhaziTriki** [bigbluebutton/bigbluebutton#8004]

**Comment by PlumedArcher** [comment]
It does for me on Google Chrome, Version 89.0.4389.90 using BBB 2.3-alpha 8.
Seems to be fixed.

**Comment by schrd** [comment]
I can reproduce this on 2.3 Beta2 in Firefox 78 ESR. In Chrome it works.

**Comment by antobinary** [comment]
Can't reproduce in 2.6.0-rc.1
