### ISSUE TITLE
Manage users dropdown is missing the close button on mobile 

### ISSUE THREAD

**Issue by tylercopeland** [bigbluebutton/bigbluebutton#8011]
**Our typical dropdown experience on mobile**

![IMG_8089](https://user-images.githubusercontent.com/1273169/63806496-be784900-c8e9-11e9-80ab-5a84495d7b07.PNG)

**Manage users dropdown on mobile**
![IMG_8088](https://user-images.githubusercontent.com/1273169/63806551-d2bc4600-c8e9-11e9-8961-18110708d04a.PNG)

**Device:**
iPhone 7

**Browser:**
Mobile Safari

**OS:**
iOS 12.4.1

**Steps to reproduced:**
1) Click the gear icon found in the user's list on mobile

**Comment by prlanzarin** [comment]
Seems to be fixed as of 2.3-beta.2. Re-open if necessary.
