### ISSUE TITLE
Actions (+) dropdown is missing the close button on mobile

### ISSUE THREAD

**Issue by tylercopeland** [bigbluebutton/bigbluebutton#8015]
![IMG_8093](https://user-images.githubusercontent.com/1273169/63809076-66444580-c8ef-11e9-948e-d84aea6c5f09.PNG)
![IMG_8092](https://user-images.githubusercontent.com/1273169/63809077-66444580-c8ef-11e9-9c28-096b7dac2668.PNG)

**Comment by Tainan404** [comment]
Hey @tylercopeland, I tested it in the last build in three different devices (xiaomi redmi note 6 pro (android), iphone 8 (ios 13) and desktop browser in mobile mode) and it doesn't happen anymore. Can you confirm?

**Comment by tylercopeland** [comment]
@Tainan404 I can confirm this is no longer an issue.
