### ISSUE TITLE
Etherpad missing files

### ISSUE THREAD

**Issue by daminebenz** [bigbluebutton/bigbluebutton#8022]
Hi BBB,

to reproduce:
1) go to dev22
2) open shared notes or Closed Captions
3) look at your console

![image](https://user-images.githubusercontent.com/33185490/63889738-fe0d6680-c9b7-11e9-980c-42ebce8934a5.png)
GET https://dev22.bigbluebutton.org/pad/static/custom/pad.css net::ERR_ABORTED 404 (Not Found)
GET https://dev22.bigbluebutton.org/pad/static/custom/pad.js net::ERR_ABORTED 404 (Not Found)

**NOTE**:
it's working fine but just there are forgotten unchanged calls of pad.css and pad.js from **/pad/static/custom/** folder

**Comment by henriquebol** [comment]
It is the same with me (2.2.3). But when loading for the first time, on some servers, a different error appears and only works after f5.

![Captura de tela de 2020-04-08 12-36-53](https://user-images.githubusercontent.com/3309893/78804547-a6e06300-7996-11ea-9490-0da96411b68d.png)
![Captura de tela de 2020-04-08 12-34-44](https://user-images.githubusercontent.com/3309893/78804551-a8119000-7996-11ea-9e06-3da2fda4b475.png)
![Captura de tela de 2020-04-08 12-32-05](https://user-images.githubusercontent.com/3309893/78804553-a8aa2680-7996-11ea-9f69-0f8640d4d554.png)
![Captura de tela de 2020-04-01 08-52-46](https://user-images.githubusercontent.com/3309893/78804633-c5465e80-7996-11ea-870b-3559e46594e4.png)

**Comment by matiasilva** [comment]
Merging with #8653.
