### ISSUE TITLE
Writing direction problem

### ISSUE THREAD

**Issue by daminebenz** [bigbluebutton/bigbluebutton#8023]
How to reproduce ?
**produce-able on all devices**

1) go to dev22
2) switch the display language in settings to Arabic
3) switch back to english
4) go to **Shared Notes** or **Closed Captions**
5) you will see that the writing direction is from right to left

**Comment by GhaziTriki** [comment]
Thank you @daminebenq, there is a property that you can use for Etherpad with `rtl` value. We definitely should have it used.

**Comment by PlumedArcher** [comment]
I can still reproduce with BBB 2.3. alpha 8 on Google Chrome.

**Comment by daminebenq** [comment]
This is not anymore reproducible.
