### ISSUE TITLE
Layout - only Webcam on enter the room...

### ISSUE THREAD

**Issue by tomlp** [bigbluebutton/bigbluebutton#8024]
Dear <devels>,
i installed successfuly our BBB-Server and managed to change the layout on entering the room to a "Webcam only" view. I mean, the Menu for Participiants and the Presentation are hidden on entering the room and the moderator (or others) can activate it on her needs.
After the update yesterday (bbb-html5 from 614 to 687) the behavior of the layout changes to the default. In my opinion: the options i set are ignored (autoShareWebcam & autoSwapLayout in meteor settings.yml).

What i am missing ?

kr Tom

**Comment by capilkey** [comment]
Double check that your settings changes are still applied after the update. They might have been overwritten.

**Comment by tomlp** [comment]
Dear Capilkey,
thx for your response. I double checked the settings and they are set as before, but the behaviour is different. I searched for the source of my knowlage about the settings and found this conversation again:
[https://groups.google.com/d/msg/bigbluebutton-dev/HSagadCtXEM/5hzxy-ciAgAJ](url) 
Before the update to 687, the presentation was really minimized and the Webcams are large on the screen.
The corresponding settings: 

>   layout:
>    autoSwapLayout: true
>    hidePresentation: false

did act different as before.
I played around with the settings and it seams that autoSwapLayout did not work anymore.... :(
kr Thomas

**Comment by tomlp** [comment]
Dear Capilkey,
i played around with the settings again and i think i can figure it out what happens.
The .yml file is very - very sensible regarding TAB's and SPACES in his nature. It comes as it has to come: the editor uses TAB's so the .yml file could not interpret correctly what's in the settings.
So - in the end of the day: it's **not an issue with BBB** himself (most of the time :) ).
btw: I try to figure out where is a startup file where i can look what errors are on launching BBB. It would be convenient for administrators to see the result of the settings after reading from settings.yml. Is there a way to see what settings are in place (in the runtime !!) ?
kr Thomas

**Comment by capilkey** [comment]
Good to know that it was the indentation.

The output from HTML5 start up can be seen with "journalctl -u bbb-html5". If there's an issue with indentation then it might not show in the logs because the file might still be parse-able, but because of the indentation it doesn't mean the same thing.

**Comment by tomlp** [comment]
Dear capilkey,
thx for your response. I thing it would be the best to create a new issue with a feature request to see the parsed entry's in the logfile. This would help also by updates if some new fields are published but not covered by the (restored) settings.yml

i closed this for now and i hope it will help some others to take care of the editor (in my case midnightcommander) and indentation of the settings.yml.
kr Thomas
