### ISSUE TITLE
UI Problem: Shared Notes label off screen

### ISSUE THREAD

**Issue by daminebenz** [bigbluebutton/bigbluebutton#8027]
Hi BBB,

the problem can be found in many client languages
Portuguese, Spanish, Persian..., etc...
![image](https://user-images.githubusercontent.com/33185490/63948784-a6bad500-ca4f-11e9-8fd5-f633393f59b4.png)

**Comment by capilkey** [comment]
Looks very similar to what happens when you private chat with someone with a long name. Likely to be the same core cause.

**Comment by daminebenz** [comment]
yes, is there an open issue about that already ? i would like to merge them in one !

**Comment by capilkey** [comment]
I had opened this issue for the private chat list, https://github.com/bigbluebutton/bigbluebutton/issues/8002

**Comment by daminebenz** [comment]
okay,
i'm gonna add this issue as a comment in #8002 !
and i'm closing this issue
