### ISSUE TITLE
translation and formulation for the 401 screen in arabic

### ISSUE THREAD

**Issue by daminebenz** [bigbluebutton/bigbluebutton#8031]
Hi BBB,

**the right formulation:**
![image](https://user-images.githubusercontent.com/33185490/63963644-dd064d80-ca6b-11e9-8928-e8c9c16eb5b6.png)

![image](https://user-images.githubusercontent.com/33185490/63963386-4afe4500-ca6b-11e9-9284-6dc1e5fdfd5a.png)

**Comment by daminebenq** [comment]
There was a rework on this redirection page. This issue isn't anymore valid.
