### ISSUE TITLE
Presentation area: "Cannot read property 'length' of undefined"

### ISSUE THREAD

**Issue by MaximKhlobystov** [bigbluebutton/bigbluebutton#8032]
I was able to hit the following error that was displayed instead of the presentation area:
![error](https://user-images.githubusercontent.com/5004762/63966211-beeb1e00-ca68-11e9-8615-f664e6afa0e8.png)

**Comment by millad90s** [comment]
occurred for me as well. what is the root cause ? and what is the solution ?

**Comment by matiasilva** [comment]
@millad90s notice the date, if there were a solution then this issue would be closed ;) 

also, I believe a few things can give rise to such an error so more information is needed.

**Comment by millad90s** [comment]
So lets work on this issue.

**Comment by matiasilva** [comment]
How?

More information is needed to determine the cause of the issue.

**Comment by antobinary** [comment]
Fixed by https://github.com/bigbluebutton/bigbluebutton/pull/11650

**Comment by testprepturkey** [comment]
still persistent at 2.6.0 RC4
