### ISSUE TITLE
Text writing formatting in Shared Notes or Closed Captions problems

### ISSUE THREAD

**Issue by daminebenz** [bigbluebutton/bigbluebutton#8034]
Hi BBB,

it's different from device type to another...

on iphone devices:
![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/33185490/63974531-712fdf00-ca83-11e9-8445-a763445f0740.gif)

on android devices:
![ezgif com-video-to-gif (2)](https://user-images.githubusercontent.com/33185490/63974597-8d338080-ca83-11e9-8cce-dff65c5e4d54.gif)

on computer chrome:
![Peek 2019-08-29 17-38](https://user-images.githubusercontent.com/33185490/63974888-22367980-ca84-11e9-8cc0-287f8d181a1e.gif)

**Comment by pedrobmarin** [comment]
Moved to https://github.com/alangecker/bbb-etherpad-plugin/issues/3
