### ISSUE TITLE
Client crashes if the poll panel is open and you lose presenter

### ISSUE THREAD

**Issue by capilkey** [bigbluebutton/bigbluebutton#8036]
Steps to reproduce:
1. Join a meeting with one moderator and one viewer client
2. Make the viewer user presenter
3. Open the poll panel
4. Make the moderator user the presenter

Expected result:
The viewer's client should close the poll panel and nothing else happens.

Actual result:
The viewer's client shows that they've been kicked from the meeting and there are lots of exceptions in the browser console.

Note:
The console is much more verbose when running in development so test there rather than production.

**Comment by jfsiebel** [comment]
Couldn't reproduce this problem anymore.
