### ISSUE TITLE
erreur 1007 on some PC

### ISSUE THREAD

**Issue by fajnzilberg** [bigbluebutton/bigbluebutton#8037]
We are using the last BBB version
In the same place some user using PC under windows 7 and window 10 meets trooblesshooting on micro and web cam

An error 1007 appears on webrtc negociation.
When they use MS Teams with html5 interface no problem with webrtc, when they use BBB they have a 1007 error
A server TURN is alredy setted

Have you any idea on how to fix this ?

Best regards
Bruno

**Comment by ffdixon** [comment]
A few questions,

  * Can you confirm the version of BigBlueButton you are using (using `bbb-conf --check`)
  * Are you able to reproduce the error on https://demo.bigbluebutton.org/?

**Comment by fajnzilberg** [comment]
Hi Fredreick

Sorry for late answer i was teacher in a training for few days.
Our version is BigBlueButton Server 2.2.0-beta-17 (1256) on bbblsmfactory1
and 2.2.0-beta-17 (1260) on bbblmsfactory2

My clienst have tested on your demo server without any problems
Its only on our two servers we got these error
