### ISSUE TITLE
Problem to set current presentation

### ISSUE THREAD

**Issue by jfsiebel** [bigbluebutton/bigbluebutton#8038]
Steps to reproduce:
1. Upload another presentation
2. Remove the uploaded presentation (no current presentation selected)
3. Upload a problematic presentation
4. Try to click on confirm in presentation modal

![Peek 2019-08-30 09-05](https://user-images.githubusercontent.com/2110278/64019620-0a073e80-cb06-11e9-9828-b29ec2178d2e.gif)

**Comment by PlumedArcher** [comment]
What is a problematic presentation? Can you specify? Or is it just problematic, because it is causing this problem? In this case could you give more information about the presentation?
