### ISSUE TITLE
Unable to scroll down to see userlist in mobile devices when there are multiple privatechat tabs, breakoutrooms and multiple Closed Captions open

### ISSUE THREAD

**Issue by daminebenz** [bigbluebutton/bigbluebutton#8042]
Hi BBB,

to reproduce from any mobile device

1) open multi dev22 connections
2) open multi private chat tabs
3) open multi Closed Captions tabs
4) enable for sometime BreakoutRooms
5) you are now unable to scroll down to see the userslist in the sidebar  

![Screenshot_20190830-111506_Chrome](https://user-images.githubusercontent.com/33185490/64029387-d71b7580-cb1a-11e9-9f9d-a3efd06e9029.jpg)

**Comment by pedrobmarin** [comment]
Was this fixed, @daminebenq ?

**Comment by daminebenq** [comment]
Yes, fixed.
