### ISSUE TITLE
Breakoutrooms creation menu UI display

### ISSUE THREAD

**Issue by daminebenz** [bigbluebutton/bigbluebutton#8043]
Hi BBB,

i was trying to create breakoutrooms from mobile devices
so in the second step of the creation, i was tapping on the name of the Breakoutroom to proceed to the next step, because it was displaying in **blue** so i thought it's an action button

![image](https://user-images.githubusercontent.com/33185490/64030533-28c4ff80-cb1d-11e9-917a-66fe87ab9470.png)

**demonstration Gif** 
![ezgif com-video-to-gif (2) (2)](https://user-images.githubusercontent.com/33185490/64030546-2fec0d80-cb1d-11e9-8255-e71b554c1887.gif)

**Comment by daminebenq** [comment]
This is not anymore reproducible.
