### ISSUE TITLE
Error 1108: ICE connection failed when sharing screen

### ISSUE THREAD

**Issue by romale** [bigbluebutton/bigbluebutton#8048]
I've installed BBB in private network. It's used let'sencrypt certificates.
It's works fine, but I can't share desktop while connected from internet because of error 1108.
From private network or via VPN it's works fine.
Also, I've installed and configured TURN server, following this manual https://docs.bigbluebutton.org/2.2/setup-turn-server.html, but I not see (with tcpdump) any connections to turn server.
Could you help resolve this issue?
Thanks

BBB installation is up to date
root@meet:~# dpkg -l|grep bbb
ii  bbb-apps                              1:2.2.0-30                                      amd64        BigBlueButton applications for Red5
ii  bbb-apps-akka                         2.2.0-57                                        all          BigBlueButton Apps (Akka)
ii  bbb-apps-screenshare                  1:2.2.0-30                                      amd64        BigBlueButton screenshare module for Red5
ii  bbb-apps-sip                          1:2.2.0-11                                      amd64        BigBlueButton SIP module for Red5
ii  bbb-apps-video                        1:2.2.0-28                                      amd64        BigBlueButton video module for Red5
ii  bbb-apps-video-broadcast              1:2.2.0-8                                       amd64        BigBlueButton video broadcast module for Red5
ii  bbb-client                            1:2.2.0-33                                      amd64        BigBlueButton Flash client
ii  bbb-config                            1:2.2.0-110                                     amd64        BigBlueButton configuration utilities
ii  bbb-demo                              1:2.2.0-9                                       amd64        BigBlueButton API demos
ii  bbb-etherpad                          1:2.2.0-45                                      amd64        The EtherPad Lite components for BigBlueButton
ii  bbb-freeswitch-core                   2:2.2.0-33                                      amd64        BigBlueButton build of FreeSWITCH
ii  bbb-freeswitch-sounds                 1:1.6.7-6                                       amd64        FreeSWITCH Sounds
ii  bbb-fsesl-akka                        2.2.0-38                                        all          BigBlueButton FS-ESL (Akka)
ii  bbb-html5                             1:2.2.0-687                                     amd64        The HTML5 components for BigBlueButton
ii  bbb-mkclean                           1:0.8.7-3                                       amd64        Clean and optimize Matroska and WebM files
ii  bbb-playback-presentation             1:2.2.0-20                                      amd64        BigBluebutton playback of presentation
ii  bbb-record-core                       1:2.2.0-42                                      amd64        BigBlueButton record and playback
ii  bbb-red5                              1:1.0.10-16                                     amd64        The Red5 server for BigBlueButton
ii  bbb-swftools                          1:0.9.2-2                                       amd64        The swftools files for BigBlueButton
ii  bbb-transcode-akka                    2.2.0-8                                         all          BigBlueButton Transcoder
ii  bbb-web                               1:2.2.0-102                                     amd64        BigBlueButton API
ii  bbb-webrtc-sfu                        1:2.2.0-72                                      amd64        BigBlueButton WebRTC SFU
ii  bigbluebutton                         1:2.2.0-4                                       amd64        Open source web conferencing platform (bbb)

**Comment by romale** [comment]
from my browser (firefox) this https://test.bigbluebutton.org/ works, and my other BBB installation with public IP only, works too.

**Comment by romale** [comment]
Issue resolved after opening TCP range on corporate firewall.
I thinks BBB [documentation](https://docs.bigbluebutton.org/2.2/configure-firewall.html) should be changed from
```
Configure your firewallAnchor link for: configure your firewall

When BigBlueButton is protected behind a firewall, you need to configure the firewall to forward the following incoming connections to BigBlueButton:

    TCP ports 80, 443, 1935, and 7443
    UDP ports in the range 16384 - 32768
```
to
```
Configure your firewallAnchor link for: configure your firewall

When BigBlueButton is protected behind a firewall, you need to configure the firewall to forward the following incoming connections to BigBlueButton:

    TCP ports 80, 443, 1935, and 7443
    UDP ports in the range 16384 - 32768
    TCP ports in the range 16384 - 32768
```

**Comment by ffdixon** [comment]
We have it documented here

  http://docs.bigbluebutton.org/2.2/install.html#minimum-server-requirements

**Comment by romale** [comment]
But here also no info about TCP range.
```
Minimum server requirementsAnchor link for: minimum server requirements

The minimum requirements for a BigBlueButton server are

    Ubuntu 16.04 64-bit OS running Linux kernel 4.x
    4 GB of memory with swap enabled (8 GB of memory is better)
    4 CPU cores (8 is better)
    TCP ports 80 and 443 are accessible
    UDP ports 16384 - 32768 are accessible
    Port 80 is not in use by another application

```

**Comment by ffdixon** [comment]
You don't need TCP for 16384 - 32768, only UDP.  There is no TCP range.

**Comment by romale** [comment]
Fred, i don't know why, but only after opening tcp range 16384 - 32768 on corp firewall, i've immediately worked desktop sharing from internet :man_shrugging:
Ok, if i'm singe have this behaviour, we may to close this issue:)

**Comment by prlanzarin** [comment]
Although it's technically possible for screenshare/listen only/video to go through TCP without traversing a TURN server, it should be pretty rare. There are a couple of non-relay TCP candidates exchanged between the media server and the browser, but their priorities are *very* low, so UDP should always be preferred. Are you certain there's no UDP block somewhere in the topology, either client-side or server-side?

**Comment by prlanzarin** [comment]
Oh, I'm blabbering about non-relay TCP candidates, but you've setup a TURN server. Did you setup a TLS/443 coturn or did you make it relay media through normal TCP ports? If the TURN server is properly configured to tunnel all media through 443, then you definitely shouldn't need to open a TCP range. If UDP candidates fail due to firewalling, then non-relay TCP candidates will fail due for the same reason and the local relay candidate will be chosen and media will go through 443.

**Comment by hmahdiany** [comment]
I had exactly the same problem and after opening tcp port range 16384 - 32768 it's working fine.

**Comment by matiasilva** [comment]
Unsure whether to close this issue. @prlanzarin should I add something to docs?

**Comment by prlanzarin** [comment]
@matiasilva took a bit long, but yes. Closing it.

**Comment by defnull** [comment]
Just a guess, but maybe the connection tracking in your cooperate firewall is overwhelmed by the BBB use case and forgets about established TCP connections once the connection tables are full. Arriving packets are then dropped because they appear to be invalid. White-listing TCP high ports may be a workaround for a broken firewall.
