### ISSUE TITLE
BUG - WebCam behind the presentation

### ISSUE THREAD

**Issue by rriscado** [bigbluebutton/bigbluebutton#8055]
Starting the room as a presenter, the webcam works perfectly.

Starting the room as a listener only, the webcam is hidden behind the presentation.

**Comment by rriscado** [comment]
Presenter
![moderator](https://user-images.githubusercontent.com/14829973/64218468-2bff1900-ce98-11e9-9d87-febdf58bba59.jpg)

Listener
![viewer_presentation](https://user-images.githubusercontent.com/14829973/64218469-2d304600-ce98-11e9-8cd1-033ae64777b7.jpg)
![viewer_presentation_minimized](https://user-images.githubusercontent.com/14829973/64218471-2d304600-ce98-11e9-88ce-b5657d692381.jpg)

**Comment by rriscado** [comment]
To start the room as listener, I used the follow parameters.

userdata-enableVideo=false
userdata-forceListenOnly=true

**Comment by rriscado** [comment]
@prlanzarin 
@antobinary 
@ffdixon 

Can you help me?

**Comment by pedrobmarin** [comment]
I believe the problem here is the enableVideo. You are disabling the whole video feature from that user. What exactly were you trying to achieve with that? If you need an user to not be able to share a video you should try the lock settings. They can be defined server wide at bigbluebutton-web properties file or be passed as a parameter on a create meeting API call

**Comment by rriscado** [comment]
> I believe the problem here is the enableVideo. You are disabling the whole video feature from that user. What exactly were you trying to achieve with that? If you need an user to not be able to share a video you should try the lock settings. They can be defined server wide at bigbluebutton-web properties file or be passed as a parameter on a create meeting API call

Hi,
Thanks for help-me!

This listener configuration is to Webinar meeting.The listener doesn't can share webcam.

Whats the correct parameter? Can you show where i can search this?

**Comment by pedrobmarin** [comment]
https://groups.google.com/d/msg/bigbluebutton-users/m2pUOqgjc4k/2-jkiJ_AAgAJ

**Comment by rriscado** [comment]
> This parameter can also be passed on the create meeting API call, as I mentioned before. This could be useful if you don't want all your meetings locking viewers webcams

Perfect!!!

Can I disable a Moderator option to reenable viewer cam again during the webinar?

I try use lockSettingsLockOnJoin and lockSettingsLockOnJoinConfigurable but doen't works.

thanks!

**Comment by rriscado** [comment]
Hi @pedrobmarin,

The **lockSettingsLockOnJoin** and **lockSettingsLockOnJoinConfigurable** options aren't valid for me, because I don't want the moderator can re-enable the viewers webcam and audio.

Debugging the code, if I change the following line, I fix **_my_** problem.
https://github.com/bigbluebutton/bigbluebutton/blob/develop/bigbluebutton-html5/imports/ui/components/media/service.js

> From
```
function shouldShowOverlay() {
  return getFromUserSettings('bbb_enable_video', KURENTO_CONFIG.enableVideo);
}
```
>To
```
function shouldShowOverlay() {
  return true;
}
```

I build BBB-HTML5 with this change and it worked perfectly **_for me_**.

I don't know if this change affects other BBB features.

Could you please check?

**Comment by pedrobmarin** [comment]
Hi
I really can't tell. I would say it's possible that you will have some kind of issue. Maybe not right now but probably you will have to face your problem again when trying to update with a newer version of BBB. But if it helps you out right now, great!
