### ISSUE TITLE
iPhone 8+ and iPhone X "the page was reloaded because a problem occurred"

### ISSUE THREAD

**Issue by daminebenz** [bigbluebutton/bigbluebutton#8056]
Hi everyone,

**from iPhone 8+ (-v 12.4.1):**
![ezgif com-video-to-gif (3)](https://user-images.githubusercontent.com/33185490/64263057-6d79dd80-cf05-11e9-984c-7e9e4a0770d1.gif)

**from iPhone X (-v 12.3.1):**
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/33185490/64263102-7ff41700-cf05-11e9-9997-a30b5965a656.gif)

**Comment by prlanzarin** [comment]
Can't reproduce as of 2.3-beta.2.
I'm closing this (stale); must've been a quirk in WebKit + getUserMedia/enumerateDevices. If it's still reproducible somehow, please re-open.
