### ISSUE TITLE
iPhone 6s and 5s camera size problems (camera showing in half in Vertical screen)

### ISSUE THREAD

**Issue by daminebenz** [bigbluebutton/bigbluebutton#8058]
Hi BBB,

1) from your iphone 5s or iphone 6s
2) go to dev22 or your local BBB in your VM
3) enable webcam
4) in the presettings of the webcam, you will see full of the camera showing
5) start sharing webcam
6) after starting sharing webcam, it shows in half in Vertical screen, while when you turn the screen horizontally it shows full and fine

![Peek 2019-09-04 11-31](https://user-images.githubusercontent.com/33185490/64264446-b03cb500-cf07-11e9-8439-6dc270d49812.gif)

**Comment by prlanzarin** [comment]
@daminebenz can you confirm if this and #8100 are still issues in the latest master branch?

**Comment by daminebenz** [comment]
BBB doesn't have this problem anymore ! i'm closing this issue ! 
thanks @prlanzarin !!
