### ISSUE TITLE
Bug when trying to pause shared YouTube video while on mobile

### ISSUE THREAD

**Issue by Bortseb** [bigbluebutton/bigbluebutton#8074]
I was testing out the BBB using your demo site, and I logged into the same call on my desktop and mobile. While testing out the share YouTube video feature I found I could successfully pause the video through my desktop, but when I tried to pause the video on mobile, it would only pause for a moment and then immediately start playing again.

**Comment by daminebenz** [comment]
Hi @Bortseb 
please note that only the Presenter can pause the Youtube video sharing.
can you tell us, who was the Presenter in your test ? your Mobile User or your Desktop User ?

**Comment by Bortseb** [comment]
AH! You're right, it does seem it was trying to make it so only presenter can pause... It is still a little buggy though, since on mobile it makes it look like you can pause, and it pauses for a little bit, but then continues. THe desktop doesn't pause while testing this.

However, when i change presenter to mobile... when I pause on there, the desktop doesn't pause at all...

Also, is there a feature to enable anyone to pause? That would be desireable too.

**Comment by capilkey** [comment]
There's no option to allow everyone to control their own playback.

The previous presenter not being affected is this bug (#8044).
