### ISSUE TITLE
Bold in shared notes is very subtle

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#8076]
in the latest build of BigBlueButton 2.2, the bold is very subtle.  At normal resolutions it would be easy to miss and think it wasn't working.

![bold](https://user-images.githubusercontent.com/290351/64526422-4179a600-d2d1-11e9-815d-0a26f5e7e246.gif)

**Comment by pedrobmarin** [comment]
![Screenshot_2021-04-01 BigBlueButton - Demo Meetingsdfgsdf (44981)](https://user-images.githubusercontent.com/1778398/113346523-5205cd00-930a-11eb-92fb-3c6d58a1abc3.png)
