### ISSUE TITLE
Logout screen error in ios devices

### ISSUE THREAD

**Issue by daminebenz** [bigbluebutton/bigbluebutton#8087]
Hi BBB,

there is an error in logout screen when user isn't a Presenter

`TypeError: undefined is not an object (evaluating 'r.findOne({userId:o.userID}).presenter')
isUserPresenter — 80c3c9f94a012ff1801d722c79c1e9244fc6deda.js:125:448402
(anonymous function) — 80c3c9f94a012ff1801d722c79c1e9244fc6deda.js:125:446728
(anonymous function) — 80c3c9f94a012ff1801d722c79c1e9244fc6deda.js:85:1767
_compute — 80c3c9f94a012ff1801d722c79c1e9244fc6deda.js:47:2322
t — 80c3c9f94a012ff1801d722c79c1e9244fc6deda.js:47:1461
autorun — 80c3c9f94a012ff1801d722c79c1e9244fc6deda.js:47:4016
nonreactive — 80c3c9f94a012ff1801d722c79c1e9244fc6deda.js:47:4181
calculateData — 80c3c9f94a012ff1801d722c79c1e9244fc6deda.js:85:1342
componentWillUpdate — 80c3c9f94a012ff1801d722c79c1e9244fc6deda.js:85:2648
$a — 80c3c9f94a012ff1801d722c79c1e9244fc6deda.js:9:89053
ps — 80c3c9f94a012ff1801d722c79c1e9244fc6deda.js:9:115202
ds — 80c3c9f94a012ff1801d722c79c1e9244fc6deda.js:9:115589
Js — 80c3c9f94a012ff1801d722c79c1e9244fc6deda.js:9:122671
Zs — 80c3c9f94a012ff1801d722c79c1e9244fc6deda.js:9:122051
qs — 80c3c9f94a012ff1801d722c79c1e9244fc6deda.js:9:121072
bs — 80c3c9f94a012ff1801d722c79c1e9244fc6deda.js:9:119885
enqueueForceUpdate — 80c3c9f94a012ff1801d722c79c1e9244fc6deda.js:9:71968
forceUpdate — 80c3c9f94a012ff1801d722c79c1e9244fc6deda.js:9:10959
(anonymous function) — 80c3c9f94a012ff1801d722c79c1e9244fc6deda.js:85:1819
_compute — 80c3c9f94a012ff1801d722c79c1e9244fc6deda.js:47:2322
_recompute — 80c3c9f94a012ff1801d722c79c1e9244fc6deda.js:47:2485
_runFlush — 80c3c9f94a012ff1801d722c79c1e9244fc6deda.js:47:3496
a — 80c3c9f94a012ff1801d722c79c1e9244fc6deda.js:1:3084`

![Screen Shot 2019-09-09 at 17 50 21](https://user-images.githubusercontent.com/33185490/64565510-50d90d80-d32a-11e9-97ae-8e1f57d07d1e.png)

![Screen Shot 2019-09-09 at 17 48 09](https://user-images.githubusercontent.com/33185490/64565449-29824080-d32a-11e9-858d-f5b9d812ff7b.png)

![RPReplay_Final1568061457 (1)](https://user-images.githubusercontent.com/33185490/64565210-a5c85400-d329-11e9-82b4-7eb7ac791322.gif)

**Comment by daminebenq** [comment]
This is not anymore reproducible.
