### ISSUE TITLE
Close the presentation modal while converting and show progress in the main client

### ISSUE THREAD

**Issue by GhaziTriki** [bigbluebutton/bigbluebutton#8095]
I have an interesting use case where I was on a conference while I was uploading a document. Participants were seeing me in the users lists and asking if I was hearing them. I was on the audio conference in mute mode and I couldn't unmute myself until the document upload has finished.

**Comment by capilkey** [comment]
That's all normal. Any time a modal is up you can't interact with the other elements in the client.

**Comment by GhaziTriki** [comment]
I think we have new design proposition that we never implemented (still in discussion). When the upload is in progress that window is closed and we should see a progress bar at the bottom of the application.

**Comment by capilkey** [comment]
There are a couple different potential improvements, but they would be enhancements not a bug. A better topic would be, "Close the presentation modal while converting and show progress in the main client". Nothing about this is specific to needing to mute/unmute.

**Comment by haviduck** [comment]
The effect would be very beneficial for the moderator who is stuck watching the progress while a class is running

**Comment by matiasilva** [comment]
Does #8464 solve this?

**Comment by GhaziTriki** [comment]
Thank you @matiasilva. The fix will be available for 2.3.x
