### ISSUE TITLE
Keyboard isn't discarding in ios devices

### ISSUE THREAD

**Issue by daminebenz** [bigbluebutton/bigbluebutton#8096]
Hi BBB,

to reproduce: **from iphone and ipad devices**
1) go to dev22 from your device's browser
2) tap anywhere you can type
3) type out of the typing area
4) the keyboard isn't discarding

![RPReplay_Final1568135130 (1)](https://user-images.githubusercontent.com/33185490/64636375-f1d1d200-d3d7-11e9-9a20-161e2dec5a9a.gif)

**Comment by daminebenq** [comment]
This is not anymore reproducible.
