### ISSUE TITLE
UI long User List problem: [on user click view options]

### ISSUE THREAD

**Issue by daminebenz** [bigbluebutton/bigbluebutton#8097]
Hi guys,

![RPReplay_Final1568144745](https://user-images.githubusercontent.com/33185490/64645414-3d41ab80-d3eb-11e9-8ae8-34677ac04c18.gif)

**Comment by pedrobmarin** [comment]
Hi @daminebenq , still an issue?

**Comment by daminebenq** [comment]
This is not anymore reproducible.
