### ISSUE TITLE
Private Chat Lock: Viewer sent his last message to a Viewer before getting the Permission Violation Kick

### ISSUE THREAD

**Issue by daminebenz** [bigbluebutton/bigbluebutton#8105]
Hi BBB,

**This is a screenshot from my docker server**
![image](https://user-images.githubusercontent.com/33185490/64732687-a42d9600-d4b9-11e9-8eff-978895a7c4c0.png)

![Peek 2019-09-11 17-32](https://user-images.githubusercontent.com/33185490/64733042-5a917b00-d4ba-11e9-917e-027854b666d2.gif)

to reproduce this:

1) try logging in with a Presenter, a Moderator and a simple Viewer
2) activate private message lock
3) send a private message from Moderator to Viewer
4) demote Moderator to Viewer
5) you still can see send private message when a viewer clicks on another Viewer
6) try to close the existing open private message
7) click on the Viewer again with a Viewer
8) send him a message
9) you will get kicked from the meeting

**NOTE**

**1. There are two props warning you should see in the console**
**2. The message from 'b' (Viewer) to 'c' (Viewer) was sent before his getting kicked for permission violation**

**Comment by pedrobmarin** [comment]
Closed with https://github.com/bigbluebutton/bigbluebutton/pull/6549
