### ISSUE TITLE
See other viewers webcams isn't showing (Locked) when activated

### ISSUE THREAD

**Issue by daminebenz** [bigbluebutton/bigbluebutton#8106]
Hi BBB,

![aaaa](https://user-images.githubusercontent.com/33185490/64734410-f8864500-d4bc-11e9-8d47-e72355f96951.gif)

**Comment by daminebenq** [comment]
This is not anymore reproducible.

**Comment by daminebenq** [comment]
Viewers still can't see Locked tag under their usernames, when "See other viewers webcams" lock is enabled.

**Comment by prlanzarin** [comment]
Can't reproduce (2.4, 2.5).
