### ISSUE TITLE
Webcam Lock ON => Viewer can't click to turn off his already enabled Webcam

### ISSUE THREAD

**Issue by daminebenz** [bigbluebutton/bigbluebutton#8109]
Hi guys,

![image](https://user-images.githubusercontent.com/33185490/64805278-160fe900-d567-11e9-94f9-7314abe78cea.png)
![aaaaaaaa](https://user-images.githubusercontent.com/33185490/64805283-190ad980-d567-11e9-8d45-910d96f579e0.gif)

**Comment by prlanzarin** [comment]
Can't reproduce as of 2.3-beta.2 (webcam gets unshared after lock is enforced).
