### ISSUE TITLE
Problem to create free join breakout rooms

### ISSUE THREAD

**Issue by jfsiebel** [bigbluebutton/bigbluebutton#8111]
If you click to create breakout rooms first, and then try to allow the users to join any breakout room the create button keeps disabled.
![create-free-join-breakout](https://user-images.githubusercontent.com/2110278/64810182-4a88a280-d571-11e9-9633-53f7f532294c.gif)

**Comment by prlanzarin** [comment]
Can't reproduce as of 2.3-beta.2.
