### ISSUE TITLE
Export Shared Notes at Shared Notes Lock displaying unclickable EXPORT option

### ISSUE THREAD

**Issue by daminebenz** [bigbluebutton/bigbluebutton#8115]
Hi guys,

the problem is that there is **Export** option displaying but there is no action when you click on it

![image](https://user-images.githubusercontent.com/33185490/64885283-188f4300-d63a-11e9-977e-63b185fc3dba.png)

**Comment by pedrobmarin** [comment]
https://github.com/bigbluebutton/etherpad-lite/pull/10
