### ISSUE TITLE
extra separation line displaying in Users list at the activation of See other viewers in the Users list Lock

### ISSUE THREAD

**Issue by daminebenz** [bigbluebutton/bigbluebutton#8116]
Hi guys,

there is a small extra separation line displaying after enabling **See other viewers in the Users list** Lock

![IMG_0011](https://user-images.githubusercontent.com/33185490/64892973-3ebdde80-d64c-11e9-8add-0e866add849d.jpg)

![RPReplay_Final1568406189](https://user-images.githubusercontent.com/33185490/64892858-e4248280-d64b-11e9-83d2-60ef77b3a05d.gif)

**Comment by prlanzarin** [comment]
Can't reproduce as of 2.3-beta.2.
