### ISSUE TITLE
potential problems issues 

### ISSUE THREAD

**Issue by armornet** [bigbluebutton/bigbluebutton#8117]
Potential problems described below
# pdf2swf is not installed in /usr/bin
# jpeg2swf is not installed in /usr/bin
# png2swf is not installed in /usr/bin
# ImageMagick's convert is not installed in /usr/bin

# Error: Unable to reach default URL for presentation:
#
#    https://mediaserver.xxxxxxxxxx/default.pdf
#
# Check value for beans.presentationService.defaultUploadedPresentation in
#   /usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties

anytips how to rectify these issues

**Comment by ffdixon** [comment]
@armornet You are not providing us enough information to resolve your issues.  

1.  What version of BigBlueButton are you installing?
2.  What method are you using to install BigBlueButton (step-by-step or`bbb-install.sh`)?
3.  Does your server meet the [minimum requirements](http://docs.bigbluebutton.org/2.2/install.html#minimum-server-requirements)?
4.  Did you get any errors during the installation?
5.  Did you make any changes to the setup (other than using `bbb-conf`)?

The GitHub issues are for resolving problems with BigBlueButton.  When encountering a setup/configuration issue, please post first to the [bigbluebutton-setup](https://groups.google.com/forum/#!forum/bigbluebutton-setup) mailing list.  This way, the community can help you out.

If in helping you out we see there is a problem with BigBlueButton itself, we'll open an issue here to track and fix.
