### ISSUE TITLE
Better titles for browser tabs when joining breakout rooms

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#8119]
When joining a breakout room, the browser opens a new tab. 

![image](https://user-images.githubusercontent.com/290351/64931980-e92f3080-d809-11e9-8ef6-edac64a37aa5.png)

The problem, as shown above, is the tab names for breakout rooms appear identical to the main room.

Change the tab names for breakout rooms so they simply say

  Room 1
  Room 2
  ...

which matches the titles given when creating the breakout rooms.

![image](https://user-images.githubusercontent.com/290351/64932019-1c71bf80-d80a-11e9-85bb-2235271bc38b.png)

This way the instructor can easily see which tab corresponds to which breakout room.

**Comment by capilkey** [comment]
The start of the tab label is "BigBlueButton" for accessibility reasons. When you're going through the list of tabs you need to be able to recognize the content in the tab.

The other thing is that the second part of the tab label is the meeting name and for breakout rooms that's "<Parent Name> (Room - <N>)". The meeting name could be rearranged to have the room and number first, but it wouldn't make sense to have the room just named "Room <N>".

**Comment by ffdixon** [comment]
> The meeting name could be rearranged to have the room and number first 

That works.

**Comment by matiasilva** [comment]
I was going to make a PR for this, but it seems it has already been solved by #8172!
