### ISSUE TITLE
Lock Settings a User is able to set See other viewers webcams in case he had the Lock Settings Menu open before his demotion to a simple Viewer

### ISSUE THREAD

**Issue by daminebenz** [bigbluebutton/bigbluebutton#8124]
Hey guys,

to reproduce:

1) connect with a Presenter and a Moderator
2) open the Lock Setting Menu from the Moderator's tab and leave it open
3) demote the Moderator to Viewer
4) enable **See other viewers webcams** Lock Setting from the demoted Moderator tab
5) open Lock Settings Menu in Presenter's tab => **See other viewers webcams** has been enabled by the Viewer

![cccccc](https://user-images.githubusercontent.com/33185490/64985555-81292a80-d89b-11e9-993d-6b91a489ee51.gif)

**Comment by daminebenq** [comment]
This is not anymore reproducible.
