### ISSUE TITLE
react-player unable to start playing Dailymotion, Wistia and a video link (http.../file.mp4)

### ISSUE THREAD

**Issue by daminebenz** [bigbluebutton/bigbluebutton#8127]
Hi guys,

**from the supported list of react-playern these aren't supported by BBB:**

**1) dailymotion => after pasting a Dailymotion video link, **share a new video** button doesn't highlight**
![image](https://user-images.githubusercontent.com/33185490/65151846-46d79e80-d9fd-11e9-9fb6-b6acef429170.png)

**2) Wistia => same thing as Dailymotion**
![image](https://user-images.githubusercontent.com/33185490/65151892-5a830500-d9fd-11e9-9eea-18516af19ad5.png)

**3) any direct video link finishing with the extension of the video (http://example.com/file.mp4), doesn't have start playing button, doesn't show the controls, once you right-click and enable SHOW CONTROLS, you get able to start sharing the video file link**

NOTE: controls of the video file sharing show only on Firefox and Safari, while on android and ios devices there is no possibility to show the controls, but the synchronization works perfectly !

**Comment by DmytroMat** [comment]
I have the same problem. 
I installed & customized Greenlight (bbb-2.2 beta).
Please help me how to rebuild only html5 app(react+meteor) to use react-player instead of youtube-react.
I don't want to update all other bbb apps, only bbb-html5.
Thank you in advance.

**Comment by ffdixon** [comment]
If you can wait a few days, this will be part of the next update to BigBlueButton 2.2-beta.

**Comment by matiasilva** [comment]
Fixed in upcoming 2.2.18 :)
