### ISSUE TITLE
Not intuitive where is chat on mobile

### ISSUE THREAD

**Issue by Brullworfel** [bigbluebutton/bigbluebutton#8132]
Hello! I can't find where is chat on mobile version of HTML5 Client.

iPhone 6, iOS 12

BBB 2.2 703

**Comment by ffdixon** [comment]
You need to have iOS 12.2 (or greater).  Can you check the version you are running by going to

 Settings -> General -> About

and let us know the `Software Version` on your phone.

**Comment by Brullworfel** [comment]
Sorry, it's my mistake. I found chat. But I think that it's not very intuitive.

I think it would be better to make a separate chat button.

![IMG_1426](https://user-images.githubusercontent.com/12401672/65246894-17f22300-daf8-11e9-883c-486ae1bd548b.PNG)
