### ISSUE TITLE
iPad webcam under Presentation container

### ISSUE THREAD

**Issue by daminebenz** [bigbluebutton/bigbluebutton#8135]
hi guys,

i found this weird webcam display only on iPad (safari)

![image](https://user-images.githubusercontent.com/33185490/65253897-c9319280-dad1-11e9-947a-42631a3ba4e5.png)
![image](https://user-images.githubusercontent.com/33185490/65254136-304f4700-dad2-11e9-850f-e23f53ebf30f.png)

**Comment by prlanzarin** [comment]
Can't reproduce as of 2.3-beta.2.
