### ISSUE TITLE
iPad display drop down overflow

### ISSUE THREAD

**Issue by daminebenz** [bigbluebutton/bigbluebutton#8138]
this is happening with arabic and persian, because they are RTL languages, and this bug is an other RTL displaying problem:
 
![image](https://user-images.githubusercontent.com/33185490/65268130-e2940800-daec-11e9-83a6-e7606cad1053.png)
![image](https://user-images.githubusercontent.com/33185490/65268137-e758bc00-daec-11e9-8c82-81b4e23e0744.png)

**Comment by daminebenq** [comment]
This is not anymore reproducible.
