### ISSUE TITLE
iPad zooming possibility from the userlist cog

### ISSUE THREAD

**Issue by daminebenz** [bigbluebutton/bigbluebutton#8139]
**this is only happening on iPad**
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/33185490/65268290-3c94cd80-daed-11e9-8be4-e8ab1459cd8e.gif)

**Comment by prlanzarin** [comment]
Is this still a thing?

**Comment by daminebenq** [comment]
This is not anymore reproducible.
