### ISSUE TITLE
Screen sharing on Safari 13

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#8142]
I don't think Safari 13 supports the WebRTC screen sharing.  When trying it on the latest build of BigBlueButton 2.2-beta, the following message appears

![image](https://user-images.githubusercontent.com/290351/65365551-4bac7600-dbe8-11e9-80ce-ab17990b2375.png)

If possible, detect the user is on Safari desktop and give the following message instead
 
> Screen sharing is not supported on Safari.  Please use Chrome or FireFox instead.

**Comment by ffdixon** [comment]
Let's see if we can do this sooner as we're setting more folks try and screen share in Safari 13 (which is the latest version) and think they are doing something wrong.

**Comment by prlanzarin** [comment]
Looks like screenshare should finally be working on Safari 13. Our problem is that the getDisplayMedia call has to be binded to an user event in order to work on Safari (which currently isn't in our case). I'll  try to take a look into that and open a PR.

**Comment by aogilvie** [comment]
put in an official ticket request to track - https://github.com/bigbluebutton/bigbluebutton/issues/8576

**Comment by premmohantyagi** [comment]
Checking in every new released version
when we will get the screensharing in Safari, it will be a big big relax
