### ISSUE TITLE
BBB not working on Webview android app

### ISSUE THREAD

**Issue by feeloneness** [bigbluebutton/bigbluebutton#8144]
HI,

Kunal here, I have developed an android app, on web view over wordpress and used your wordpress plugin, also

while joining the room its shows below the message.
![WhatsApp Image 2019-09-23 at 1 37 58 AM](https://user-images.githubusercontent.com/55347564/65393791-18faad00-dda3-11e9-962f-36267f6f221a.jpeg)

How can I resolve it, also the page provided by greenlight is not responsive, can you let le know the file path so that, I can go and edit the design and make it responsive.

**Comment by ffdixon** [comment]
> Kunal here, I have developed an android app, on web view over wordpress and used your wordpress plugin, also

Cool.  Is your work open source?

> while joining the room its shows below the message.

Check `/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml`, where you'll see the browser (from the User Agent string) and the minimum version.

~~~
  minBrowserVersions:
  - browser: chrome
    version: 59
~~~

Add your browser and version here and restart BigBlueButton.  The client should then load.

**Comment by capilkey** [comment]
You'll also need to know what useragent your webview is using. You can set the useragent to a specific browser and make it look like Chrome or Firefox, or you can go to an endpoint on your BigBlueButton server and find the user agent for your browser. The endpoint to go to is "https://<your server>/html5client/useragent".

**Comment by aviavinas** [comment]
It worked in my case when i changed the **userAgentString**: 
```
        WebSettings settings = webView.getSettings();
        settings.setUserAgentString("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.97 Safari/537.36");

```

**Comment by mgulsoy** [comment]
> It worked in my case when i changed the **userAgentString**:
> 
> ```
>         WebSettings settings = webView.getSettings();
>         settings.setUserAgentString("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.97 Safari/537.36");
> ```

This also works with my app. I think this is related to how BBB classifies the mobile version of browsers.

**Comment by MudrekaBohra** [comment]
> > It worked in my case when i changed the **userAgentString**:
> > ```
> >         WebSettings settings = webView.getSettings();
> >         settings.setUserAgentString("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.97 Safari/537.36");
> > ```
> 
> This also works with my app. I think this is related to how BBB classifies the mobile version of browsers.

Hi i have also used the same string for the webview it works and everything is working except when i turn on video the select camera, drop down shows empty label i can still change the front and back camera but the name label is not visible  screenshot attached below 
![bug1](https://user-images.githubusercontent.com/63293297/79111857-f1008480-7d9a-11ea-9368-6bc6abd3029e.jpeg)
![bug2](https://user-images.githubusercontent.com/63293297/79111871-f78efc00-7d9a-11ea-817d-4d8ec8dc5d21.jpeg)

**Comment by mucavv** [comment]
hi, 
I had the same error when developing for android and fixed setting the userAgent as stated above but it works only in debug. When i build the release version the app still gives the same error. Any Idea?

**Comment by MudrekaBohra** [comment]
Hi, 
No idea actually i still haven't figured it out

**Comment by ffdixon** [comment]
To see how BigBlueButton is checking the user agent string, see

 http://docs.bigbluebutton.org/2.2/troubleshooting.html#the-browser-is-not-supported

**Comment by aolee** [comment]
hi @MudrekaBohra , good day to you, hope all is well on your end. May I please know if you manage to fix the issue with the empty camera label?

**Comment by NiceboyWiseboy** [comment]
> > > It worked in my case when i changed the **userAgentString**:
> > > ```
> > >         WebSettings settings = webView.getSettings();
> > >         settings.setUserAgentString("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.97 Safari/537.36");
> > > ```
> > 
> > 
> > This also works with my app. I think this is related to how BBB classifies the mobile version of browsers.
> 
> Hi i have also used the same string for the webview it works and everything is working except when i turn on video the select camera, drop down shows empty label i can still change the front and back camera but the name label is not visible screenshot attached below
> ![bug1](https://user-images.githubusercontent.com/63293297/79111857-f1008480-7d9a-11ea-9368-6bc6abd3029e.jpeg)
> ![bug2](https://user-images.githubusercontent.com/63293297/79111871-f78efc00-7d9a-11ea-817d-4d8ec8dc5d21.jpeg)



Hello @aolee ,

I'm also facing the same issue @MudrekaBohra . If you can please help in this.
Thanks

**Comment by anilthummar** [comment]
> HI,
Use this userAgent string its working fine 
> How can I resolve it, also the page provided by greenlight is not responsive, can you let le know the file path so that, I can go and edit the design and make it responsive.

  String strData = "Mozilla/5.0 (Windows NT 10.0; Win64; x64 ) (Linux; U; Android" + Build.VERSION.RELEASE +
                        "; en-us; " + Build.MODEL + " Build/" + Build.FINGERPRINT + ") AppleWebKit/537.36 (KHTML, like Gecko) Version/"
                        + System.getProperty("os.version") + " Mobile Chrome/" + strChromeVersion + " Safari/537.36";

**webView.getSettings().setUserAgentString(strData);**

**Comment by anilthummar** [comment]
> HI,
> 
> Kunal here, I have developed an android app, on web view over wordpress and used your wordpress plugin, also
> 
> while joining the room its shows below the message.
> ![WhatsApp Image 2019-09-23 at 1 37 58 AM](https://user-images.githubusercontent.com/55347564/65393791-18faad00-dda3-11e9-962f-36267f6f221a.jpeg)
> 
> How can I resolve it, also the page provided by greenlight is not responsive, can you let le know the file path so that, I can go and edit the design and make it responsive.

Used Below code for User-Agent 

`
 try {
            PackageInfo pInfo = null;
            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
                //starting with Android O (API 26) they added a new method specific for this
                pInfo = WebView.getCurrentWebViewPackage();
                if (pInfo != null) {
                    strChromeVersion = pInfo.versionName;
                } else {
                    strChromeVersion = "81.0.4044.117";
                }

            } else if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M) {
                try {
                    Class webViewFactory = Class.forName("android.webkit.WebViewFactory");
                    Method method = webViewFactory.getMethod("getLoadedPackageInfo");
                    pInfo = (PackageInfo) method.invoke(null);

                    if (pInfo != null) {
                        strChromeVersion = pInfo.versionName;
                    } else {
                        strChromeVersion = "81.0.4044.117";

                    }

                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

  String strData = "Mozilla/5.0 (Windows NT 10.0; Win64; x64 ) (Linux; U; Android" + Build.VERSION.RELEASE +
                        "; en-us; " + Build.MODEL + " Build/" + Build.FINGERPRINT + ") AppleWebKit/537.36 (KHTML, like Gecko) Version/"
                        + System.getProperty("os.version") + " Mobile Chrome/" + strChromeVersion + " Safari/537.36";`

**webView.getSettings().setUserAgentString(strData);**

**Comment by mgulsoy** [comment]
> hi @MudrekaBohra , good day to you, hope all is well on your end. May I please know if you manage to fix the issue with the empty camera label?

Did you implement request and grant?

I did like that:

    webView.setWebChromeClient( new WebChromeClient() {
        @Override
        public void onPermissionRequest(PermissionRequest request) {
            Log.i( TAG, "onPermissionRequest: " + request.getOrigin().toString() );
            request.grant( request.getResources() );
        }
    } );

But I don't recall if I had empty labels.

**Comment by anilthummar** [comment]
@mgulsoy 
Yes already  implement request and grant for set permission run time for WebChromeClient, but still not showing camera dialog Text

Got Log like 
**Error :libc: Access denied finding property "vendor.camera.aux.packagelist"**

**Comment by matiasilva** [comment]
Hi everyone. Excellent discussion, I just ask that you move it elsewhere, specifically to https://groups.google.com/forum/#!forum/bigbluebutton-dev where other developers can contribute and add on. Closing for now.

**Comment by khan822** [comment]
Hi i have same issue but i used bbb in to ionic 3 project where i can change websettings in my ionic 3 project

**Comment by balkrishanyadav** [comment]
> HI,
> 
> Kunal here, I have developed an ios 
> 
> while joining the room its shows below the message.
>
> 
> How can I resolve it,.

**Comment by xiaozhouboy** [comment]
BBB not working on Webview ios app? Same question

**Comment by arshad1995** [comment]
https://github.com/bigbluebutton/bigbluebutton/issues/8144#issuecomment-642605677

Anyone found the solution for above issue?

**Comment by matiasilva** [comment]
The issue has been closed, please do not revive it and discuss this in the relevant forum.

**Comment by Maspoer** [comment]
I also just built a url shortener for Indonesia, https://goads.id
we are very happy for your visit there to put a reply link, hopefully it can increase your website ranking.

greetings success friends
