### ISSUE TITLE
The polling options don't go away when the poll is ended

### ISSUE THREAD

**Issue by capilkey** [bigbluebutton/bigbluebutton#8147]
Steps to reproduce:
1. Join with two clients
2. Start a poll
3. End the poll without voting

Expected result:
The poll options should go away when there's no longer an active poll.

Actual result:
The options stay on the screen until there's possibly a global re-render.

Additional Info:
It looks like the poll fetching isn't being done in a reactive way, or the active poll isn't being reset. Make sure to test both options for ending a poll.

**Comment by prlanzarin** [comment]
Can't reproduce as of 2.3-beta.2.
