### ISSUE TITLE
BigBlueButton 2.2.0-beta-20 (1432) behind a firewall :Could not detect FreeSWITCH listening on port 5060

### ISSUE THREAD

**Issue by alcyoneus86** [bigbluebutton/bigbluebutton#8151]
I installed BigBlueButton on a fresh Ubuntu 16.04 server. The server is behind a firewall and not running on a virtual machine.  I followed the steps in the installation manual at http://docs.bigbluebutton.org/2.2/configure-firewall.html and http://docs.bigbluebutton.org/2.2/configure-firewall.html and configured BigBlueButton to load a session via HTTPS, as described in the manual. The SSL certificate in use is from symantec.

he only component that refuses to work is FreeSWITCH. When I am inside a session with the HTML5 client.I get error 1002

bbb-conf --check 

BigBlueButton Server 2.2.0-beta-20 (1432)
                    Kernel version: 4.4.0-164-generic
                      Distribution: Ubuntu 16.04.6 LTS (64-bit)
                            Memory: 8174 MB
                         CPU cores: 2
......
/opt/freeswitch/etc/freeswitch/vars.xml (FreeSWITCH)
                       local_ip_v4: 172.31.119.86
                   external_rtp_ip: 47.56.170.116
                   external_sip_ip: 47.56.170.116

/opt/freeswitch/etc/freeswitch/sip_profiles/external.xml (FreeSWITCH)
                        ext-rtp-ip: $${external_rtp_ip}
                        ext-sip-ip: $${external_sip_ip}
                        ws-binding: 47.56.170.116:5066
                       wss-binding: 47.56.170.116:7443
......
/etc/bigbluebutton/nginx/sip.nginx (sip.nginx)
                        proxy_pass: 47.56.170.116
......
# Potential problems described below
......
# Error: Could not detect FreeSWITCH listening on port 5060
......

root@chateam:~# netstat -anpt | grep 5060
root@chateam:~# 

root@chateam:~# systemctl status freeswitch.service 
● freeswitch.service - freeswitch
   Loaded: loaded (/lib/systemd/system/freeswitch.service; enabled; vendor preset: enabled)
   Active: active (running) since Thu 2019-09-26 15:00:39 CST; 15min ago
  Process: 15826 ExecStart=/opt/freeswitch/bin/freeswitch -u freeswitch -g daemon -ncwait $DAEMON_OPTS (code=exited, status=0/SUCCESS)
 Main PID: 15831 (freeswitch)
   CGroup: /system.slice/freeswitch.service
           └─15831 /opt/freeswitch/bin/freeswitch -u freeswitch -g daemon -ncwait -nonat

Sep 26 15:00:37 chateam systemd[1]: Starting freeswitch...
Sep 26 15:00:37 chateam freeswitch[15826]: 15831 Backgrounding.
Sep 26 15:00:39 chateam systemd[1]: Started freeswitch.
root@chateam:~# 

-- Logs begin at Thu 2019-06-20 16:35:10 CST, end at Thu 2019-09-26 15:17:01 CST. --
Sep 25 17:29:52 chateam systemd[1]: Starting freeswitch...
Sep 25 17:29:52 chateam freeswitch[23734]: 23736 Backgrounding.
Sep 25 17:29:54 chateam systemd[1]: Started freeswitch.
Sep 25 17:36:15 chateam systemd[1]: Stopping freeswitch...
Sep 25 17:36:20 chateam systemd[1]: Stopped freeswitch.
Sep 25 17:36:20 chateam systemd[1]: Starting freeswitch...
Sep 25 17:36:20 chateam freeswitch[13134]: 13136 Backgrounding.
Sep 25 17:36:22 chateam systemd[1]: Started freeswitch.
Sep 25 18:39:05 chateam systemd[1]: Stopping freeswitch...
Sep 25 18:39:11 chateam systemd[1]: Stopped freeswitch.
Sep 25 18:39:11 chateam systemd[1]: Starting freeswitch...
Sep 25 18:39:11 chateam freeswitch[21158]: 21172 Backgrounding.
Sep 25 18:39:14 chateam systemd[1]: Started freeswitch.
Sep 25 18:50:16 chateam systemd[1]: Stopping freeswitch...
Sep 25 18:50:21 chateam systemd[1]: Stopped freeswitch.
Sep 25 18:50:21 chateam systemd[1]: Starting freeswitch...
Sep 25 18:50:21 chateam freeswitch[24653]: 24669 Backgrounding.
Sep 25 18:50:23 chateam systemd[1]: Started freeswitch.
Sep 25 18:55:21 chateam systemd[1]: Stopping freeswitch...
Sep 25 18:55:26 chateam systemd[1]: Stopped freeswitch.
Sep 25 18:55:26 chateam systemd[1]: Starting freeswitch...
Sep 25 18:55:26 chateam freeswitch[27056]: 27090 Backgrounding.
Sep 25 18:55:28 chateam systemd[1]: Started freeswitch.
Sep 25 19:07:32 chateam systemd[1]: Stopping freeswitch...
Sep 25 19:07:38 chateam systemd[1]: Stopped freeswitch.
Sep 25 19:07:38 chateam systemd[1]: Starting freeswitch...
Sep 25 19:07:38 chateam freeswitch[30578]: 30582 Backgrounding.
Sep 25 19:07:40 chateam systemd[1]: Started freeswitch.
Sep 25 19:19:28 chateam systemd[1]: Stopping freeswitch...
Sep 25 19:19:34 chateam systemd[1]: Stopped freeswitch.
-- Reboot --
Sep 25 19:23:59 chateam systemd[1]: Starting freeswitch...
Sep 25 19:23:59 chateam freeswitch[822]: 973 Backgrounding.
Sep 25 19:24:02 chateam systemd[1]: Started freeswitch.
Sep 25 22:46:21 chateam systemd[1]: Stopping freeswitch...
Sep 25 22:46:27 chateam systemd[1]: Stopped freeswitch.
Sep 25 22:46:27 chateam systemd[1]: Starting freeswitch...
Sep 25 22:46:27 chateam freeswitch[7657]: 7659 Backgrounding.

I try clear the FreeSWITCH database   still geting the same errors

![image](https://user-images.githubusercontent.com/3810650/65666982-62801c00-e071-11e9-93d1-115080636623.png)

**Comment by ffdixon** [comment]
Can you double-check you have FreeSWITCH configured correctly for working behind a firewall, see

  http://docs.bigbluebutton.org/2.2/configure-firewall.html#update-freeswitch

and the section on error 1002.

**Comment by alcyoneus86** [comment]
@ffdixon i checkd  again and again. could u do me a fever?

  /opt/freeswitch/conf/vars.xml
  <X-PRE-PROCESS cmd="set" data="external_rtp_ip=47.56.170.116"/>
  <X-PRE-PROCESS cmd="set" data="external_sip_ip=47.56.170.116"/>
  
  /opt/freeswitch/conf/sip_profiles/external.xml
  <param name="ext-rtp-ip" value="$${external_rtp_ip}"/>
  <param name="ext-sip-ip" value="$${external_sip_ip}"/>
  
  /usr/share/red5/webapps/sip/WEB-INF/bigbluebutton-sip.properties
  bbb.sip.app.ip=172.31.119.86
  freeswitch.ip=172.31.119.86
  
  /etc/bigbluebutton/nginx/sip.nginx
  proxy_pass https://47.56.170:7443;

**Comment by coffeduong** [comment]
Hello, is there any update?

**Comment by coffeduong** [comment]
@alcyoneus86 I've tried following this article and is worked :D
 
https://freeswitch.org/confluence/display/FREESWITCH/NAT+Traversal

Updated filed:

- vars.xml
- internal.xml
- external.xml

**Comment by miqj69** [comment]
Updated filed:

/opt/freeswitch/etc/freeswitch/vars.xml
/opt/freeswitch/etc/freeswitch/sip_profiles/external.xml
/opt/freeswitch/conf/sip_profiles/external.xml
/etc/bigbluebutton/nginx/sip.nginx
/usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml
/lib/systemd/system/dummy-nic.service

Execute =>

rm -rf /opt/freeswitch/var/lib/freeswitch/db/*
systemctl start freeswitch  

systemctl daemon-reload 
systemctl restart dummy-nic

systemctl restart nginx
bbb-conf --restart

**Comment by SimonSoftware** [comment]
Works! Great!
