### ISSUE TITLE
Disable browser check

### ISSUE THREAD

**Issue by Brullworfel** [bigbluebutton/bigbluebutton#8152]
Hello! In BBB 2.2.721 a lot of our users can't enter meetings. It was ok on BBB 2.0.

There are user-agent values of users with problems:

MedinaApp/1.0.4 Mozilla/5.0 (Linux;   Android 9; HRY-LX1 Build/HONORHRY-L21; wv) AppleWebKit/537.36 (KHTML, like   Gecko) Version/4.0 Chrome/72.0.3626.121 Mobile Safari/537.36

MedinaApp/1.0.4 Mozilla/5.0 (Linux; Android 5.1.1; SM-J120F Build/LMY47X; wv)   AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/77.0.3865.92 Mobile   Safari/537.36

Mozilla/5.0 (iPhone; CPU iPhone OS 12_4_1 like Mac OS X) AppleWebKit/605.1.15   (KHTML, like Gecko) Version/12.1.2 Mobile/15E148 Safari/604.1

Mozilla/5.0 (Linux; Android 9; LLD-L31 Build/HONORLLD-L31; wv)   AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/77.0.3865.92 Mobile   Safari/537.36 [FB_IAB/Orca-Android;FBAV/233.0.0.16.158;]

MedinaApp/1.0 Mozilla/5.0 (Linux; Android 5.1.1; SM-J120F Build/LMY47X; wv)   AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/55.0.2883.91 Mobile   Safari/537.36

Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko)   Chrome/76.0.3809.132 YaBrowser/19.9.3.276 (beta) Yowser/2.5 Safari/537.36

Mozilla/5.0 (Linux; Android 8.1.0; NX563J Build/OPM1.171019.011)   AppleWebKit/537.36(KHTML,like Gecko)Version/4.0 Chrome/40.0.2214.89 Mobile   Safari/537.36

MedinaApp/1.0.4 Mozilla/5.0 (Linux; Android 8.0.0; SM-G930F Build/R16NW; wv)   AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/77.0.3865.92 Mobile   Safari/537.36

Mozilla/5.0 (Linux; U; Android 8.1.0; ru-ru; Redmi 5 Plus   Build/OPM1.171019.019) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0   Chrome/71.0.3578.141 Mobile Safari/537.36 XiaoMi/MiuiBrowser/10.9.7-g

And how we can temporary turn off browser version check on meeting enter?

Thanks!

**Comment by capilkey** [comment]
The user agent check can't be turned off without rebuilding the client with the configuration removed.

Those all look like non-standard user agents so it's not surprising that they're getting rejected. You have to pass them to the user agents to the same package that the Meteor server uses and determine the browser and then add it to the allowed list if you think it's going to work.

Every BigBlueButton HTML5 client has an endpoint to expose the detection of the browser. https://demo.bigbluebutton.org/html5client/useragent

**Comment by Brullworfel** [comment]
I rewritten part of the file /usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml , and all our users were able to connect:

  minBrowserVersions:
  - browser: chrome
    version: 1
  - browser: chromeMobileIOS
    version: Infinity
  - browser: firefox
    version: 1
  - browser: firefoxMobile
    version: 1
  - browser: edge
    version: 17
  - browser: ie
    version: Infinity
  - browser: vivaldi
    version: 1
  - browser: safari
    version:
    - 11
    - 1
  - browser: mobileSafari
    version:
    - 11
    - 1
  - browser: opera
    version: 1
  - browser: electron
    version:
    - 0
    - 36
  - browser: samsungInternet
    version: 1
  - browser: yowser
    version: 1
  - browser: yabrowser
    version: 1
  - browser: yandexBrowser
    version: 1
  - browser: facebook
    version: 1
  - browser: chromeMobileWebView
    version: 1
