### ISSUE TITLE
Append shared notes to playback

### ISSUE THREAD

**Issue by haviduck** [bigbluebutton/bigbluebutton#8161]
Id live the youtube share to be in events xml as everybody else but how about appending etherpads content aswell?

Two scenarios:
1) the content of etherpad at the end of the meeting and make it exportable in playback
2) stream everything into events and have a righthand sidebar in the playback ui showing it.

**Comment by ffdixon** [comment]
On BigBlueButton 2.2-beta-20, if you install the package `bbb-playback-notes` you'll get a new recording format called `notes` that will give you PDF of the last state of the Shared Notes.

Try it and let us know if that works for you.

**Comment by haviduck** [comment]
Awesome! Thanks.
