### ISSUE TITLE
How to make it impossible to turn on microphones and webcams for users?

### ISSUE THREAD

**Issue by Brullworfel** [bigbluebutton/bigbluebutton#8164]
I use API for creating meeting with this params:

webcamsOnlyForModerator => true,

However, users still can turn on cameras!

And I can’t disallow users from turning on microphones too!

**Comment by haviduck** [comment]
i dont think the php api has the lock options you are after.  But you can always set the default lock options in settings.yml.

**Comment by ffdixon** [comment]
In BigBlueButton 2.2, try passing`lockSettingsDisableCam=true` on the [create](http://docs.bigbluebutton.org/dev/api.html#create) API call.

**Comment by capilkey** [comment]
Don't use the lock options in settings.yml. I'm pretty certain that they don't work. There are properties in bigbluebutton.properties that can be set instead.

**Comment by haviduck** [comment]
My bad that was the one i was thinking off :)

**Comment by Brullworfel** [comment]
Problem resolved in BBB 2.2 with meeting creating via API with parameters:

'lockSettingsDisableCam'    => true,
'lockSettingsDisableMic'    => true,
'lockSettingsLockOnJoin'    =>  true
