### ISSUE TITLE
Headphone and Microphone icons have same background color

### ISSUE THREAD

**Issue by Brullworfel** [bigbluebutton/bigbluebutton#8165]
<img width="51" alt="Скриншот 2019-09-29 20 17 10" src="https://user-images.githubusercontent.com/12401672/65838382-31bb1380-e30b-11e9-98ed-291e5c243223.png">

If there are a lot of users at my meeting, it is very difficult to distinguish between users who have the microphone turned on and those who have the “listen only” mode turned on.

**Comment by tylercopeland** [comment]
@Brullworfel thanks for outlining your feedback. For us to better understand your experience using BigBlueButton would you be able to share your typical use case, the need to want to differentiate the two audio types and roughly how many individuals you have in the session?

**Comment by Brullworfel** [comment]
> @Brullworfel thanks for outlining your feedback. For us to better understand your experience using BigBlueButton would you be able to share your typical use case, the need to want to differentiate the two audio types and roughly how many individuals you have in the session?

We use BBB in 2 scenarios:

1. Foreign language lesson. At the lesson there are up to 20 people. The teacher alternately turns on the microphones for each student and works with him, the rest of the participants at this time only listen.

2. Webinar. The cameras and microphone are turned off for everyone except the teacher. The webinar is usually attended by 150-300 people. We cannot disallow of a microphone and camera for students technically, even if we block the microphone and camera, new members who join later can still use them. Some turn on microphones randomly. Our moderator constantly monitors the entire list of students and mutes students' microphones. In version 2.2, it became difficult to follow this, as the microphone and headphone icons are the same color.

**Comment by mtsonline** [comment]
as visually impaerd people alwys have difficulties with same or nearly same colours, it would be great to have clearly different background for all icons 
aspecially the Status icons (raiseHand) should be good visible for anyone.

**Comment by ffdixon** [comment]
Commenting to keep this issue open ... it's a good suggestion.
