### ISSUE TITLE
Transcoding recorded sessions

### ISSUE THREAD

**Issue by haviduck** [bigbluebutton/bigbluebutton#8169]
Hey, im trying to figure out why my webms arent being converted to mp4. Havent found a whole lot about it. Do i need to write my own post files to make that happen?

**Comment by haviduck** [comment]
whoa that was a shitty issue description and evident that past me did not bother reading docs. shame!

**Comment by pedrobmarin** [comment]
Hey @haviduck , no worries.

Sorry I didn't even mentioning why I was closing it up. We currently have 1.2k issues opened and I'm just trying to close some old ones. Hope you got your mp4 converted!

**Comment by haviduck** [comment]
> Hey @haviduck , no worries.
> 
> Sorry I didn't even mention why I was closing it up. We currently have 1.2k issues opened and I'm just trying to close some old ones. Hope you got your mp4 converted!

doing the good thing!  ah and yeah ofc. have a good easter / weekend
