### ISSUE TITLE
LDAP login not working

### ISSUE THREAD

**Issue by levigo-systems** [bigbluebutton/bigbluebutton#8173]
Hello,

we try to connect BBB to our AD.

Issue:
If a user tries to login at the WebGUI the following error occurs:
`The email and password you entered did not match our records. Try again or click Forgot Password to reset your password.`
Even then local administrator can't login anymore.

Our .env looks like:

> root@bbb:~/greenlight# cat .env 
> SECRET_KEY_BASE=SECRET_KEY_BASE=xxxxxxxxxxxxxxxxxxx
> BIGBLUEBUTTON_ENDPOINT=https://bbb.example.de/bigbluebutton/
> BIGBLUEBUTTON_SECRET=xxxxxxxxxxxxxxxxxxxxx
> GOOGLE_OAUTH2_ID=
> GOOGLE_OAUTH2_SECRET=
> GOOGLE_OAUTH2_HD=
> OFFICE365_KEY=
> OFFICE365_SECRET=
> OFFICE365_HD=
> LDAP_SERVER=dc-01.intern.example.de
> LDAP_PORT=636
> LDAP_METHOD=ssl
> LDAP_UID=sAMAccountName
> LDAP_BASE=dc=intern,dc=example,dc=de
> LDAP_BIND_DN=cn=mm.ldap.query,ou=serviceAccounts,ou=common,ou=example-gruppe,dc=intern,dc=example,dc=de
> LDAP_PASSWORD=s$mer4ndom
> LDAP_ROLE_FIELD=ou
> ALLOW_GREENLIGHT_ACCOUNTS=false
> RECAPTCHA_SITE_KEY=
> RECAPTCHA_SECRET_KEY=
> GOOGLE_ANALYTICS_TRACKING_ID=
> SMTP_SERVER=
> SMTP_PORT=
> SMTP_DOMAIN=
> SMTP_USERNAME=
> SMTP_PASSWORD=
> SMTP_AUTH=
> SMTP_STARTTLS_AUTO=
> SMTP_SENDER=
> RELATIVE_URL_ROOT=/b
> ROOM_FEATURES=mute-on-join,require-moderator-approval,anyone-can-start,all-join-moderator
> PAGINATION_NUMBER=25
> NUMBER_OF_ROWS=25
> ENABLE_GOOGLE_CALENDAR_BUTTON=
> MAINTENANCE_MODE=false
> 
> DEFAULT_REGISTRATION=open
> 

On the AD we see that the Greenlight is connecting but not asking for more information.
ldapsearch -H is working well with LDAPS.

We want to allow LDAP auth and local user auth but no registration of new users.

Any ideas?

Best regards

**Comment by romale** [comment]
I wrote script for this purpose as woraround
https://github.com/romale/sync_ldap_users_to_bbb

**Comment by matiasilva** [comment]
Thanks for the initiative. Unfortunately, this issue belongs here: https://github.com/bigbluebutton/greenlight. Feel free to open a conversation there.
