### ISSUE TITLE
ending Breakoutrooms interrupts Microphone Echo Test

### ISSUE THREAD

**Issue by daminebenz** [bigbluebutton/bigbluebutton#8175]
Hey guys,
**to reproduce**
1) go to dev22 with two users
2) enter in microphone echo test mode in one user and in the second create breakoutrooms
3) from the second user end breakoutrooms while the first user is still in Echo Test mode
4) the Echo Test was interrupted by the Breakoutrooms end event

**more details in this GIF**
![aaaaaaaaa](https://user-images.githubusercontent.com/33185490/66067256-98b21580-e521-11e9-99fb-8876fc876d86.gif)

**Comment by GhaziTriki** [comment]
@daminebenq Do you confirm it still happens? What should happen is a complete breakout room end not disconnecting from audio only.

**Comment by daminebenq** [comment]
This is still a problem.
@mariogasparoni do you know what's going here ?
This is also a 2.3 problem.
