### ISSUE TITLE
trying to create BreakoutRooms duplicated isn't giving any error messages 

### ISSUE THREAD

**Issue by daminebenz** [bigbluebutton/bigbluebutton#8177]
Hi guys,

**to reproduce**
1) go with 2 Moderators to dev22
2) open BreakoutRooms creation Menu from both of the Moderators
3) from Moderator1 create Breakoutrooms
4) from Moderator2 change the Breakoutrooms properties to be different from the first Moderator's creation and confirm the creation
5) you won't see any error or warnings messages that there are already existing Breakoutrooms, even in console

![Peek 2019-10-02 16-54](https://user-images.githubusercontent.com/33185490/66077632-b50c7d00-e536-11e9-88bb-82c1075a038a.gif)

**Comment by daminebenq** [comment]
This weird behavior is still reproducible.

**Comment by ffdixon** [comment]
The first person to click create wins, which does make sense.  The likelihood of this scenario is also very low.  It's still a bug, but its priority is correspondingly low.
