### ISSUE TITLE
in greenlight, in the profile page, the provider input is editable from element inspection

### ISSUE THREAD

**Issue by daminebenz** [bigbluebutton/bigbluebutton#8178]
hey guys,
in greenlight, in the profile page, the provider input is editable from element inspection and it saves correctly
**Try it in demo.bigbluebutton.org**
**the Provider input is editable**
![image](https://user-images.githubusercontent.com/33185490/66128143-999b8380-e5c3-11e9-95f6-55cb7551bcf0.png)

![image](https://user-images.githubusercontent.com/33185490/66128102-85578680-e5c3-11e9-959d-944b3bebfedb.png)

**Comment by matiasilva** [comment]
Thanks for pointing this out. Unfortunately, it belongs here: https://github.com/bigbluebutton/greenlight as this repository is concerned with BigBlueButton only.
