### ISSUE TITLE
Gem not installed 2.2 beta

### ISSUE THREAD

**Issue by emmarichardson** [bigbluebutton/bigbluebutton#8179]
Hi Fred,
Trying to get the 2.2 beta going.  Something appears to be going wrong with the gem install.
Am getting the bbb-record-core stall out.  I tried following steps from a similar post.

bocesadmin@bbb1:~$ sudo apt-get install ruby
[sudo] password for bocesadmin: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
ruby is already the newest version (1:2.3.0+1).
ruby set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
4 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n] y
Setting up bbb-record-core (1:2.2.0-42) ...
ERROR:  While executing gem ... (SocketError)
    getaddrinfo: Name or service not known
dpkg: error processing package bbb-record-core (--configure):
 subprocess installed post-installation script returned error exit status 1
No apport report written because the error message indicates its a followup error from a previous failure.
                          dpkg: dependency problems prevent configuration of bbb-playback-presentation:
 bbb-playback-presentation depends on bbb-record-core; however:
  Package bbb-record-core is not configured yet.

dpkg: error processing package bbb-playback-presentation (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of bbb-config:
 bbb-config depends on bbb-playback-presentation; however:
  Package bbb-playback-presentation is not configured yet.

dpkg: error processing package bbb-config (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of bigbluebutton:
 bigbluebutton depends on bbb-config; however:
  Package bbb-config is not configured yet.

dpkg: error processing package bigbluebutton (--configure):
 dependency problems - leaving unconfigured
No apport report written because the error message indicates its a followup error from a previous failure.
                          No apport report written because MaxReports is reached already
        Errors were encountered while processing:
 bbb-record-core
 bbb-playback-presentation
 bbb-config
 bigbluebutton
E: Sub-process /usr/bin/dpkg returned an error code (1)
bocesadmin@bbb1:~$ sudo gem update --system --no-document
ERROR:  While executing gem ... (SocketError)
    getaddrinfo: Name or service not known
bocesadmin@bbb1:~$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.6 LTS"
bocesadmin@bbb1:~$ 

Hope you can help!

**Comment by ffdixon** [comment]
I did a google for "getaddrinfo: Name or service not known" and found this [solution](https://github.com/puma/puma/issues/1623).  

Try the above link and let us know if it gets you going.

**Comment by emmarichardson** [comment]
Sadly that did not change anything...

Emma

Emma Richardson
Distance Learning Coordinator
Direct: 719-650-3037

**Comment by emmarichardson** [comment]
It appears however that this might be a network issue...I will check and see if my network guy got everything he was meant to open, open!  Does 2.2 use ruby differently to 2.0 because I was able to get 2.0 running..

**Comment by ffdixon** [comment]
There are differences in the gems.  

You can do a quick test on an external server, such as at Digital Ocean, and you should find it installs without error, and so it should from an internal network.

**Comment by matiasilva** [comment]
No follow up in a year + pertains to beta. Closing for now but feel free to follow up at https://groups.google.com/forum/#!forum/bigbluebutton-setup.
