### ISSUE TITLE
Breakoutrooms randomly assign focusing on another room in room selection to join screen 

### ISSUE THREAD

**Issue by daminebenz** [bigbluebutton/bigbluebutton#8180]
Hi guys,

**to reproduce**
1) connect to dev22 with a Moderator and 2 Viewers
2) from Moderator's screen create Breakoutrooms and enable **Allow users to choose a breakout room to join**, click **Randomly Assign** and click **create**
3) from the Viewers screen, the Breakoutroom joining screens are prompted out but with showing Selection options of the available rooms with normal order of the Rooms
![image](https://user-images.githubusercontent.com/33185490/66155424-f879f080-e5f5-11e9-800b-d5f565545f0e.png)

**issue described more in the GIF below**
![b](https://user-images.githubusercontent.com/33185490/66154777-9cfb3300-e5f4-11e9-9105-107ffe73090d.gif)

**Comment by daminebenq** [comment]
There was a misunderstanding of this feature. This is not an issue.
