### ISSUE TITLE
"Allow users to choose a breakout room to join" prompts to Moderator the Breakoutroom joining screen

### ISSUE THREAD

**Issue by daminebenz** [bigbluebutton/bigbluebutton#8181]
Hey guys,

**to reproduce**
1) go to dev22 with a Moderator and a Viewer
2) create Breakoutrooms with enabling **Allow users to choose a breakout room to join**
3) the Moderator is Prompted to join the Breakoutrooms

**described in the GIF below**
![a](https://user-images.githubusercontent.com/33185490/66155568-53134c80-e5f6-11e9-9f59-6c9c3e6bd515.gif)

**Comment by capilkey** [comment]
#8529 fixes this right?
