### ISSUE TITLE
updating html5 client and core when  bbb commits smaller updates

### ISSUE THREAD

**Issue by haviduck** [bigbluebutton/bigbluebutton#8184]
Hey, i use the bbb-install oneliner to get bigbluebutton up and running. when you commit new smaller stuff like last nights arc player, whats the correct way for me to update my install with your new fixes/commits?

**Comment by ffdixon** [comment]
There is currently no process for distributing smaller updates.  

After testing internally -- and on https://demo.bigbluebutton.org/ -- when we are about to make a release, we push all the updates to the BigBlueButton packaging repo, make a post to bigbluebutton-dev, and post the release notes to

   https://github.com/bigbluebutton/bigbluebutton/releases

This way, we ensure each update has been tested before it goes to the community.  Once updated, you can re-run the bbb-install.sh script and it will update your BigBlueButton 2.2 server to the latest release.

**Comment by haviduck** [comment]
But i just installed a fresh server and the arc player wasnt there. Does the installer use a separate repo or does it grab from git?

**Comment by capilkey** [comment]
The changes to the external video playback were added after 2.2-beta20 and will be included in beta21.
