### ISSUE TITLE
Download Recored session

### ISSUE THREAD

**Issue by mdm992002** [bigbluebutton/bigbluebutton#8190]
error on download the recorded session, student can download session after he go full screen, then click on download, but if downloaded the webcams.webm will start to download. 
https://drive.google.com/open?id=1Sjszoi2UwjTynI7ba1yISYewiV3KBtul

**Comment by ffdixon** [comment]
Not sure what is the error that you are reporting -- are you saying that students want to download the screen sharing but instead get the webcams?

**Comment by mdm992002** [comment]
Yes, and download file get wamb not .avi

**Comment by pedrobmarin** [comment]
Although I believe the user will always find a way to record something in her/his screen, I'm centering this discussion here https://github.com/bigbluebutton/bigbluebutton/issues/4978
