### ISSUE TITLE
Let post script run scripts other that Ruby.

### ISSUE THREAD

**Issue by namiarj** [bigbluebutton/bigbluebutton#8191]
Is it possible to let run post scripts in languages other than Ruby? That'll make it easier for administrator to customize their BBB.

**Comment by kepstin** [comment]
For the moment, the post process scripts must be ruby scripts, with a filename ending in `.rb`. However, there's nothing stopping you from making a ruby script that launches another program written in a different language.

**Comment by namiarj** [comment]
> For the moment, the post process scripts must be ruby scripts, with a filename ending in `.rb`. However, there's nothing stopping you from making a ruby script that launches another program written in a different language.

Why must? Isn't that possible to run every script under the post-publish directory?

**Comment by peterpetrov** [comment]
Hey @namiarj , you can do the following in your ruby script:

system("/your/custom/bash/script #{var1} #{var2} #{meeting_id} arg3 arg4 ")

This line says to ruby that you are executing bash script called "/your/custom/bash/script". 

#{var1}, #{var2} and #{meeting_id} are variables that are loaded by the ruby script which makes it easier to load values from the ruby environment (i.e. meeting id, meta data variables etc.). 

arg3 and arg4 are just static values that you pass to the script.

And within your script you can do whatever you want. You just need to find how to call the type of script in ruby and then you are all set.

I hope this helps.
