### ISSUE TITLE
Can't open in Chrome from mobile app (device Samsung A9)

### ISSUE THREAD

**Issue by anhtt57** [bigbluebutton/bigbluebutton#8194]
Firstly, I'm sorry that my English is not very good

I use mobile-app of Moodle. I open BBB from moodle and it redirect to Chrome.
while joining the room its shows below the message.
![65393791-18faad00-dda3-11e9-962f-36267f6f221a](https://user-images.githubusercontent.com/13230716/66362622-ba8e1b00-e9ad-11e9-863a-dd501d0aae41.jpeg)

I checked version of Chrome. It is: Chrome mobile 77.0.3865 / Android 8.0.0 (I use /html5client/useragent)

In my xiaomi mobile (same Chrome version), BBB worked perfect!!. So, I don't think the errors is "Check /usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml, where you'll see the browser (from the User Agent string) and the minimum version."

**Comment by capilkey** [comment]
Do you see the same message if load the client at https://demo.bigbluebutton.org?

**Comment by peterpetrov** [comment]
Hey there. I had the same issue and the problem is with the implementation of Chrome within (for example) FB Messanger or FB app itself. I haven't tested it completely but i think you will need to open the user agent to more options. I am planning to do it and can post some updates.
