### ISSUE TITLE
RegEx QuickPoll isn't detecting the poll options

### ISSUE THREAD

**Issue by daminebenz** [bigbluebutton/bigbluebutton#8198]
Trying to get Poll options from QuickPoll PDF file

![abc](https://user-images.githubusercontent.com/33185490/66426819-0c07cb80-e9e9-11e9-8939-998664a62e51.gif)

**Comment by GhaziTriki** [comment]
I just tested and fully working. The valid smart poll format is described here https://docs.bigbluebutton.org/legacy/10overview.html#smart-polling
