### ISSUE TITLE
After join, getting 401

### ISSUE THREAD

**Issue by vuckookv3** [bigbluebutton/bigbluebutton#8206]
So I have installed BBB with shell script (2.2).

I wanna make my own application (frontend and backend) which integrates with BBB API.

My website will be at example.com and BBB will be on other server and domain bbb.example.com (am I doing this right?)

So I successfully created a meeting (btw, is meeting a "room" in greenlight?).

Now I wanna join user, I am using join api.
Problems: 
1. When I give wrong password, I am getting html string as response.
2. When I put redirect=true, again I am getting html string
3. redirect=false is giving me XML, that I joined successfully and URL. (Docs said that for this I need redirect=true)

OK, so I get the URL to redirect to. When I redirect user to it, it gives 401 page.
Logs saying: "No session for user in conference."

So my question is:
How do I open/pass the session?

**Comment by ffdixon** [comment]
Hi there,

This issue isn't a bug with BigBlueButton; rather, a request for help in integrating BigBlueButton with a 3rd party application.

Can we get you to post this to our bigbluebutton-dev mailing list, see https://bigbluebutton.org/support.

If in the course of providing you help in the mailing list we determine there is a bug/enhancement needed with BigBlueButton, we'll open an issue here to track it.
