### ISSUE TITLE
A few users cannot connect, Error 1007

### ISSUE THREAD

**Issue by linhux** [bigbluebutton/bigbluebutton#8209]
Hi, fwe users from my site cannot connect to a meeting the webrtc fails.
But other users can connect without issues.
All configs are default,i have installed the szstem wit installscript

ICE(PC:1571075875428402 (id=6442450949 url=https://blabla.org/html5client/join?sessionToken=mtlzusersqb5pmkt)): relay/proxy only option results in ICE TCP being disabled

ICE(PC:1571075875428402 (id=6442450949 url=https://blabla.org/html5client/join?sessionToken=mtlzusersqb5pmkt)): couldn't create any valid candidates

+++++++ END ++++++++

**Comment by ffdixon** [comment]
We would recommend setting up a TURN server for your BigBlueButton server, see

  http://docs.bigbluebutton.org/2.2/setup-turn-server.html

To see if the TURN server would help, you can have your users try connecting to 
  
  https://demo.bigbluebutton.org/

and see if they can share audio (we have a TURN server setup for the above BigBlueButton server).

**Comment by linhux** [comment]
can i setup this on the same server with bbb ? or must the turn server have a own hardware

**Comment by ffdixon** [comment]
You need to setup your own TURN server -- it doesn't need to be a powerful server -- a single core CPU would be enough to get started.  See

  http://docs.bigbluebutton.org/2.2/setup-turn-server.html

**Comment by linhux** [comment]
ok i have setup the server but i have the same issue 1007 is the turn port udp ?

**Comment by linhux** [comment]
ok i have setup the system with turn, with the bbb example. but is stil the 1007 error,

**Comment by linhux** [comment]
all services are running, i can connect only in listening mode

**Comment by capilkey** [comment]
Do you see the relay candidate in the list of local candidates? Do you get the same ICE errors even with the TURN server?

**Comment by linhux** [comment]
/builds/worker/workspace/build/src/media/mtransport/third_party/nICEr/src/net/nr_socket_multi_tcp.c:173 function nr_socket_multi_tcp_create_stun_server_socket skipping UDP STUN server(addr:)

/builds/worker/workspace/build/src/media/mtransport/third_party/nICEr/src/net/nr_socket_multi_tcp.c:617 function nr_socket_multi_tcp_listen failed with error 3

ICE(PC:1571264375191640 (id=12884902045 url=https://meet1.theknowledgeseekers.org/html5client/join?sessionToken=0mfpazptvlryh5m4)): failed to create passive TCP host candidate: 3

/builds/worker/workspace/build/src/media/mtransport/third_party/nICEr/src/net/nr_socket_multi_tcp.c:173 function nr_socket_multi_tcp_create_stun_server_socket skipping UDP STUN server(addr:)

/builds/worker/workspace/build/src/media/mtransport/third_party/nICEr/src/net/nr_socket_multi_tcp.c:617 function nr_socket_multi_tcp_listen failed with error 3

ICE(PC:1571264375191640 (id=12884902045 url=https://meet1.theknowledgeseekers.org/html5client/join?sessionToken=0mfpazptvlryh5m4)): failed to create passive TCP host candidate: 3

Write buffer not empty for IP4:37.128.222.19:8585/TCP 44 - already armed (@0x15f9e9df4), not connected

Error from TCPSocketChild: type: ConnectionRefusedError, name: Network

Error from TCPSocketChild: type: ConnectionRefusedError, name: Network

Write buffer not empty for IP4:37.128.222.19:8585/TCP 44 - already armed (@0x15f9eb9f4), not connected

+++++++ END ++++++++

**Comment by linhux** [comment]
the tls is over port 8585

**Comment by linhux** [comment]
no there is nothing, but in the listening mode i can see the candidates

**Comment by linhux** [comment]
hm i have changed in the freeswitch conf the lokal ip to the external ip. and it works.
But is this the right way ?

**Comment by capilkey** [comment]
Changing FreeSWITCH to use your external IP is one of the steps that's recommended if your server is behind a firewall/NAT. http://docs.bigbluebutton.org/2.2/configure-firewall.html

**Comment by joseluisq** [comment]
[freeswitch.org](https://freeswitch.org/) quote possibly related to this issue.

> **stun.freeswitch.org** is never guaranteed to be up and running so use it in production at your own risk. There are several open source projects to run your own STUN server, e.g. STUNTMAN

https://freeswitch.org/confluence/display/FREESWITCH/NAT+Traversal#NATTraversal-STUNservers
