### ISSUE TITLE
Add "who is typing" to Shared Notes

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#8211]
Currently, when users type in the shared notes there is no indication of who is typing or who wrote the text.

We could explore adding a note in the margin on who typed the text (but the column is already pretty narrow) or colouring the text (though colour is not good for accessibility)

![image](https://user-images.githubusercontent.com/290351/66785752-cdb85380-eea3-11e9-9cd8-3cc1c783da3b.png)

**Comment by mtsonline** [comment]
please, if you add this, make it optional in the settings, as our users do want to write anonymously in the notes. :-)

**Comment by E-dk** [comment]
I would love to see this feature because currently students occasionaly misuse 'shared notes' for unwanted content.
So we had to disable this.
Any news on when this will be implemented? :)

**Comment by GhaziTriki** [comment]
Should be possible by using an Ehterpad plugin.

**Comment by SAEmam4444** [comment]
🌌🟦🟦حاجی خعلی معرکس 🟦🟦🌌
🌌🟦🟦خداییش حال کردم🟦🟦🌌

**Comment by SAEmam4444** [comment]
فروغی هستی ؟یا رفتی ؟

**Comment by SAEmam4444** [comment]
عرب شما سکوت کن

**Comment by SAEmam4444** [comment]
https://www.google.com/imgres?imgurl=https%3A%2F%2Fcdn.mos.cms.futurecdn.net%2F42E9as7NaTaAi4A6JcuFwG.jpg&imgrefurl=https%3A%2F%2Fwww.livescience.com%2F45005-banana-nutrition-facts.html&tbnid=ppaoMT73yQb4VM&vet=12ahUKEwiz1OGL547vAhWKwOAKHQdXAl4QMygBegUIARDcAQ..i&docid=aCmLYEGvNNOXNM&w=700&h=467&q=banana&ved=2ahUKEwiz1OGL547vAhWKwOAKHQdXAl4QMygBegUIARDcAQ

**Comment by SAEmam4444** [comment]
https://user-images.githubusercontent.com/79837933/109479739-f25c9d80-7a8f-11eb-9502-c024b764909d.png

**Comment by SAEmam4444** [comment]
MR.GhaziTriki, You lie like a dog.🐶🐕🐕🐩🐕‍🦺

**Comment by pedrobmarin** [comment]
Plugin enabled at v2.3

**Comment by christianwolters** [comment]
Hi,

we have used this "missing" feature as an actual feature: a place to share notes anonymously.
(Opposed to other areas in our LMS, including etherpad, where all things written are attached to an author)

Does anyone know an easy way to disable this new behaviour/plugin?
Or is it possible to make this configurable at a toplevel?

Cheers
Christian

**Comment by pedrobmarin** [comment]
https://github.com/bigbluebutton/bigbluebutton/releases/tag/v2.3-beta-1

You can disable it by uninstalling the plugin at your Etherpad deploy. Something like going to `/usr/share/etherpad-lite` and running a `npm uninstall ep_cursortrace`

**Comment by christianwolters** [comment]
Hey @pedrobmarin thank you very much for your 🚀 fast reply - totally missed that!
