### ISSUE TITLE
BBB API documentation has wrong name for bbb-recording-ready-url meta param

### ISSUE THREAD

**Issue by Brullworfel** [bigbluebutton/bigbluebutton#8216]
Hello!

When I create meeting, I send meta_bn-recording-ready-url parameter with URLEncoded API URL as in documentation ( https://docs.bigbluebutton.org/dev/api.html#recording-ready-callback-url ).

By API I can see in meetings list that the parameter has been successfully accepted by BBB:

`["metadata":protected]=> object(stdClass)#4 (4) { ["date"]=> string(16) "18.10.2019 09:42" ["presenter"]=> string(10) "Махди" ["name"]=> string(31) "Тестовый вебинар" ["bn-recording-ready-url"]=> string(56) "https%3A%2F%2Fmedinaschool.org%2Fapi%2Fbbbrecordingready" }`

But when the recording is ready, the BigBlueButton server not makes any request to this URL!

**Comment by kepstin** [comment]
There is a typo in the docs, the correct name of the parameter to use is `meta_bbb-recording-ready-url`

**Comment by ffdixon** [comment]
Updated the docs to the correct parameter name.  http://docs.bigbluebutton.org/dev/api.html
