### ISSUE TITLE
Allow for editing when entering live closed captions

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#8221]
Currently, the entering of live closed captions does not allow for editing.  The entering of "gather" and then editing it to "collect" results in "gathercollect" in the live captions.

This is a known limitation for the current implementation of captioning.  The problem will be mitigated by editing of SRT files, but we still need to support editing during the live captioning.

**Comment by pedrobmarin** [comment]
Closing since there is already a discussion over this at https://github.com/bigbluebutton/bigbluebutton/issues/7648
