### ISSUE TITLE
no audio on a recording

### ISSUE THREAD

**Issue by gurcem** [bigbluebutton/bigbluebutton#8224]
Hello,

I just noticed that there is no audio on a recording. There was audio on live stream but when i try to play the recording, i can see the presentation and webcam but there is no audio. Is there any way to fix it?

Version: 2.2

**Comment by mmhospedagem** [comment]
I also have the same problem and nobody in the community helps to solve it, if you find a solution please post here!

**Comment by ritzalam** [comment]
See https://github.com/bigbluebutton/bigbluebutton/pull/8215

**Comment by mmhospedagem** [comment]
what does that mean? and the solution to our problem?

**Comment by ffdixon** [comment]
We think that  #8215, due in the next update to BigBlueButton 2.2-beta, will fix this issue.   

You'll see this fix referenced in the release notes https://github.com/bigbluebutton/bigbluebutton/releases when BigBlueButton 2.2-beta-23 is released.

**Comment by mmhospedagem** [comment]
when will this update be released?

**Comment by ffdixon** [comment]
We don't have an exact date, but we've been releasing updates for BigBlueButton 2.2-beta every two to three weeks.  You can watch our bigbluebutton-dev mailing list

   https://groups.google.com/forum/#!forum/bigbluebutton-dev

for an announcement on when it's released.
