### ISSUE TITLE
There is a React warning when changing language

### ISSUE THREAD

**Issue by capilkey** [bigbluebutton/bigbluebutton#8228]
Steps to reproduce:
1. Launch the client
2. Switch the language in the settings
3. Check the browser console

![image](https://user-images.githubusercontent.com/1395090/67242690-087e3680-f424-11e9-88b3-c8a76d105793.png)

Note that the warning will only show up when running in development.

**Comment by pedrobmarin** [comment]
Couldn't reproduce this.
