### ISSUE TITLE
Is there any way to record externally to user's computer other than recording to server?

### ISSUE THREAD

**Issue by ycw7701** [bigbluebutton/bigbluebutton#8229]
Please answer below!

1. Is there any way to record externally to user's computer other than recording to server?

2. Can presenters adjust to maximize participant's presentation screen?

**Comment by ffdixon** [comment]
> Is there any way to record externally to user's computer other than recording to server?

In BigBlueButton's architecture -- all the video streams go to the BigBlueButton server.  There is no recording on the user's computer.

> Can presenters adjust to maximize participant's presentation screen?

Not yet, but we have an open issue for this feature https://github.com/bigbluebutton/bigbluebutton/issues/7987

**Comment by ycw7701** [comment]
Thank you for answer.
Is there a company or individual to request the development of an external recording function?

**Comment by ffdixon** [comment]
You can post this request to our bigbluebutton-dev mailing list (see https://bigbluebutton.org/support).

**Comment by ycw7701** [comment]
Thank you very much. How can I post to a mailing list?

**Comment by ffdixon** [comment]
Follow the link given above and first join the BigBlueButton-dev mailing list.  Once you've joined (be sure to answer the question on joining to show you are not a bot), you can post to the list.

**Comment by ycw7701** [comment]
Thank you very much
