### ISSUE TITLE
How to access Database 

### ISSUE THREAD

**Issue by richwebs8** [bigbluebutton/bigbluebutton#8230]
Hi

I want to get the Database access of this with PHPMyAdmin how can I do that and what is the userID password it creates from its own?

**Comment by ffdixon** [comment]
Do you mean the database in Greenlight?

**Comment by richwebs8** [comment]
yes

**Comment by richwebs8** [comment]
hello @ffdixon can I get the solution

**Comment by ffdixon** [comment]
@richwebs8 can we get you to post this to the Greenlight issues database, see

  https://github.com/bigbluebutton/greenlight

This issue tracker is for BigBlueButton-related questions.

**Comment by amarendragoap** [comment]
How can I get access to the Greenlight PostgreSQL database using the client?.

**Comment by matiasilva** [comment]
@amarendragoap did you read the comment just above yours?

Greenlight's PostgreSQL database is no different from any other. Install a frontend for PG as you wish, one of them is PHPMyAdmin. The installation instructions should help you get to where you need to be.

**Comment by amarendragoap** [comment]
Dear Sir, 

Thank you for your response. 

Can you share me some article /steps for the same? 

Thank You! 
Amarendra Goap

**Comment by matiasilva** [comment]
Article for what? This is a list of PG frontends you could use: https://wiki.postgresql.org/wiki/PostgreSQL_Clients
