### ISSUE TITLE
Shared Editor not loading over HTTPs

### ISSUE THREAD

**Issue by amette** [bigbluebutton/bigbluebutton#8237]
Browser refuses to load the shared editor because it is unencrypted while BBB itself is being served over HTTPs. I double checked the documentation, but I didn't find any mention of installing my SSL certificates into nodejs. I suppose this is just a case of missing documentation!?

**Comment by ffdixon** [comment]
How did you install BigBlueButton -- `bbb-install.sh` or step-by-step?  

   http://docs.bigbluebutton.org/2.2/install.html#installation-choices

**Comment by amette** [comment]
Step by step.

**Comment by ffdixon** [comment]
Is it an option for you to use the `bbb-install.sh` script?

**Comment by amette** [comment]
Hmmm, that would mean redoing the whole installation. I could try, if absolutely necessary. Just had a look at the install_ssh function in bbb-install.sh though and I couldn't find anything that it would do, that I didn't. On the other hand: BBB doesn't work at all any more since some of its packages were updated yesterday. So maybe worth a try.

You don't have any other idea?

**Comment by capilkey** [comment]
If you're getting a warning about shared notes then you probably missed a set in the documentation to change the URL. http://docs.bigbluebutton.org/2.2/install.html#configure-bigbluebutton-to-load-session-via-https

**Comment by ffdixon** [comment]
>  So maybe worth a try.

If this is a new setup, then yes.  For a server with a public facing IP address and a DNS name that resolves to that IP address, the `bbb-install.sh` script will pretty much do all the manual steps you found in the step-by-step guide.

You don't have to setup a new server, you can run `bbb-install.sh` on an existing server that you are setting up manually.  See
  
  https://github.com/bigbluebutton/bbb-install#install-with-ssltls

**Comment by amette** [comment]
Tried bbb-install.sh, that failed, then completely reinstalled the server and tried bbb-install.sh again. Then it worked.
