### ISSUE TITLE
Breakoutroom: join audio => onClick on Audio User shows no-needed options

### ISSUE THREAD

**Issue by daminebenz** [bigbluebutton/bigbluebutton#8240]
Hi BBB,

to reproduce:
1) join with 2 users dev22a with microphone
2) start breakoutrooms from user A and assign user B to Breakoutroom1
3) from the user A open Breakoutrooms menu and click to join Audio Breakoutroom1
4) from User B in Breakoutroom1 click on the User B in users list
5) you see that there are unuseful user options (like: send private chat message and make presenter)

![Peek 2019-10-23 16-23](https://user-images.githubusercontent.com/33185490/67427138-e3b7c980-f5b1-11e9-9e61-8818ad7715c5.gif)

![image](https://user-images.githubusercontent.com/33185490/67427122-db5f8e80-f5b1-11e9-8de0-b85c40312b45.png)

**Comment by daminebenq** [comment]
There is no more Viewer role in Breakout rooms, this issue isn't anymore valid.
