### ISSUE TITLE
Problem with webcam

### ISSUE THREAD

**Issue by marcellofornaciari** [bigbluebutton/bigbluebutton#8243]
Hi all,
i have a matter on an installation with version 2.2 beta 20.
I have fixed the mic, so now in Firefox in the tab webrtc i can see the public delegate.
In the same tab, when i click on the webcam, i see the private ip of the server, not the public one.
Is there any place where i can set up it?

Really thanks

**Comment by ffdixon** [comment]
How did you install BigBlueButton?  [Step-by-step](http://docs.bigbluebutton.org/2.2/install.html) instructions or[bbb-install.sh](https://github.com/bigbluebutton/bbb-install)?

**Comment by marcellofornaciari** [comment]
Step by step instructions

**Comment by ffdixon** [comment]
Is it an option for you to install using `bbb-install.sh`?

   https://github.com/bigbluebutton/bbb-install

There is a chance you may have missed a configuration step.  `bbb-install.sh` automates almost all of the installation steps and can also use Let's Encrypt to automate the request and installation of a SSL certificate.

**Comment by capilkey** [comment]
Does the script make changes to add a STUN server to Kurento? http://docs.bigbluebutton.org/2.2/configure-firewall.html#extra-steps-when-server-is-behind-nat

That's probably the part that you're missing @marcellofornaciari

**Comment by marcellofornaciari** [comment]
ok, after many checks, i have found the reason.
in the guide, a step is missing for ssl.
when you do the setup, the ws is called from https, not the wss, for kurento.
so, i modified the value wsUrl for kurento in '/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml' from ws to wss

Just to clarify, i used also sh installation, but same result.

Really thanks

**Comment by ffdixon** [comment]
The docs do have you modify `wsUrl` when setting up manually with SSL, see

  http://docs.bigbluebutton.org/2.2/install.html#configure-bigbluebutton-to-load-session-via-https
