### ISSUE TITLE
Wrong error message displayed when joining audio of an HTTP server

### ISSUE THREAD

**Issue by farhatahmad** [bigbluebutton/bigbluebutton#8244]
- Clean install of BigBlueButton 2.2-beta-22
- Meeting started from Greenlight
- Firefox on Ubuntu 18.04

When starting a meeting on an HTTP server, I am met with this error dialog when trying to join audio.

![image (2)](https://user-images.githubusercontent.com/35435341/67501649-a7887580-f652-11e9-81c7-d0494a11c996.png)

Since I'm not using Chrome or iOS, I should instead be shown another error describing why I am not able to join the audio.

**Comment by ffdixon** [comment]
I think we have this fixed in the next update to BigBlueButton 2.2-beta

**Comment by capilkey** [comment]
#8112 is the issue that I opened to improve the error messages and it was fixed in #8168 and will be in the next beta build
