### ISSUE TITLE
[API v2] [Experimental] : Create a new API entry to check if the meeting is alive

### ISSUE THREAD

**Issue by GhaziTriki** [bigbluebutton/bigbluebutton#8246]
**Context:**

We currently use `isMeetingRunning` API to check if the meeting has been created or not. However this API is old and does no more give use the accurate result we need. Instead developers do need to `getMeetingInfo` to check if the meeting is really alive or not.

**Issues with the current implementation:**

- The `isMeetingRunning` returns the `meeting.isRunning()` value, however it is tied to `meeting` property `users.isEmpty()`. 
> “This goes way back when red5 held the meeting state. Before akka-apps. In red5, the meeting is created when the first user joins.” Explains @ritzalam.
- `isRunning()` accessor is metaphoring a real meeting, it does not reflect its technical status.
- We generate too much data using `getMeetingInfo` for a meeting status API call.
- Third party applications do not get the real meeting running status with `isMeetingRunning`. They need it to know if they need to load meeting properties; like passwords; from their database or they need to call the `create` API.

**Solution context:**

The team discussed about an implementation of a new API v2 at multiple opportunities over few years. After a small meeting, the team thinks that it is time to start a minimal and experimental implementation of a v2 API to ensure a fluent transition.

**Suggested solution:**

For this use case we will implement a new API, `/api/v2/meetings/<external_meeting_id>/alive`

**`Technical implementation`**

It will now be a part of `bigbluebutton-web`. `nginx` will have a new redirection rule for it.

**`curl example`**
`curl -X GET -H "Content-Type: application/json" "https://demo.bigbluebutton.org/api/v2/meetings/4bdf97a468152c4-31a65ad/alive"`

**`Request Headers`**

```
Content-Type: application/json
Authorization: Bearer 6b3701cbbedb4ba88b79920d8c2955f2
```

Note that `Authorization: Bearer` is the replacement for `checksum`.

**`Response Headers`**

```
content-type: application/json; charset=utf-8
status: 200 OK
```

**`Response Body for Success`**

```
{
  "meetings": [
    {
      "id": "4bdf97a468152c4-31a65ad",
	  "status": "alive"
      "start_time": 1571937733445
    }
  ]
}
```

**`Response Body for Error`**

```
{
  "meetings": [
    {
      "id": "4bdf97a468152c4-31a65ad",
	  "status": "not_found"
      "start_time": 0
    }
  ]
}
```

**Comment by SamuelWei** [comment]
Any updates?

**Comment by GhaziTriki** [comment]
Hi @SamuelWei,
This project is still in labs, COVID-19 prevented us from updating it and myself personally from doing so. But we still have intentions to write a V2 API that is backward compatible with the existing one.
All contributions are welcome.

**Comment by pedrobmarin** [comment]
Another use case for the webhooks (https://docs.bigbluebutton.org/dev/webhooks.html). The webhooks can avoid most of those calls that the external application has to poll the API frequently.

**Comment by SamuelWei** [comment]
@GhaziTriki Could this be resolved without a complete API redesign? Otherwise this wont happen for a very long time I expect or what is the timeline for api v2? Adding a new api endpoint or second attribute to the existing api could be a non breaking change!?

**Comment by antobinary** [comment]
I will reopen the issue as I see value in the original idea and it will be better to revisit it when appropriate than to let it get closed...

@SamuelWei could you please confirm if you tried the bbb-webhooks approach @pedrobmarin wrote about?

**Comment by SamuelWei** [comment]
@antobinary I'm not using the bbb-webhooks to a consistent source of data, always polling from the frontend or callback from bbb. It also makes the setup easier as the server doesn't need to know about the frontend upfront

@ffdixon That was the issue I just related to in the bbb world conf. talk

**Comment by SamuelWei** [comment]
bump
