### ISSUE TITLE
Slow Connection indicator is displaying to other users

### ISSUE THREAD

**Issue by daminebenz** [bigbluebutton/bigbluebutton#8247]
Hi BBB,

There is a problem displaying Slow Connection Indicator to other Users also than the one who's having problems with his connection !

![image](https://user-images.githubusercontent.com/33185490/67510579-9730c480-f66b-11e9-94c7-4bd974ddd8db.png)
![Screenshot_20191024-142305_Chrome](https://user-images.githubusercontent.com/33185490/67510580-9730c480-f66b-11e9-9ec3-abf713ff17b2.jpg)

**Comment by pedrobmarin** [comment]
Closing since we continued this with a different approach
