### ISSUE TITLE
Audio not hearing

### ISSUE THREAD

**Issue by gkarthik534004** [bigbluebutton/bigbluebutton#8259]
Hi,

while in meeting some clients are unable hear voice but they able to see video this is in desktop and chrome browser.

**Comment by daminebenz** [comment]
Hi @gkarthik534004 
what version of BBB are you using for your meeting ?

**Comment by ffdixon** [comment]
Can you do a test using https://demo.bigbluebutton.org/ with one of the clients that is having problems and let us know if you can repeat the issue there.
