### ISSUE TITLE
How to fix error Error: Could not connect to the configured hostname/IP address

### ISSUE THREAD

**Issue by samuelpeixoto** [bigbluebutton/bigbluebutton#8270]
Friends, 
My installation was working correctly, but now has an error.

Here is **the error**:
```
# Potential problems described below
# Not running:  tomcat7 or grails LibreOffice
................................................................................
# Error: Could not connect to the configured hostname/IP address
#
#    https://reuniaofacilws.com.br/
#
# If your BigBlueButton server is behind a firewall, see FAQ.
```

Here is the **output from #sudo bbb-conf --check**
```
BigBlueButton Server 2.2.0-beta-23 (1509)
                    Kernel version: 4.4.0-166-generic
                      Distribution: Ubuntu 16.04.6 LTS (64-bit)
                            Memory: 30881 MB
                         CPU cores: 16

/usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties (bbb-web)
       bigbluebutton.web.serverURL: https://reuniaofacilws.com.br
                defaultGuestPolicy: ALWAYS_ACCEPT
                 svgImagesRequired: true

/etc/nginx/sites-available/bigbluebutton (nginx)
                       server name: reuniaofacilws.com.br
                              port: 80, [::]:80
                              port: 443 ssl
                    bbb-client dir: /var/www/bigbluebutton

/var/www/bigbluebutton/client/conf/config.xml (bbb-client)
                Port test (tunnel): rtmp://reuniaofacilws.com.br
                              red5: reuniaofacilws.com.br
              useWebrtcIfAvailable: true

/opt/freeswitch/etc/freeswitch/vars.xml (FreeSWITCH)
                       local_ip_v4: 162.214.68.184
                   external_rtp_ip: stun:stun.freeswitch.org
                   external_sip_ip: stun:stun.freeswitch.org

/opt/freeswitch/etc/freeswitch/sip_profiles/external.xml (FreeSWITCH)
                        ext-rtp-ip: $${local_ip_v4}
                        ext-sip-ip: $${local_ip_v4}
                        ws-binding: :5066
                       wss-binding: 162.214.68.184:7443

/usr/local/bigbluebutton/core/scripts/bigbluebutton.yml (record and playback)
                     playback_host: reuniaofacilws.com.br
                 playback_protocol: https
                            ffmpeg: 4.1.3-0york1~16.04

/etc/bigbluebutton/nginx/sip.nginx (sip.nginx)
                        proxy_pass: 162.214.68.184

/usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml (Kurento SFU)
                        kurento.ip: 162.214.68.184
                       kurento.url: ws://127.0.0.1:8888/kurento
                    localIpAddress: 162.214.68.184
               recordScreenSharing: true
                     recordWebcams: true
                  codec_video_main: VP8
               codec_video_content: VP8

/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml (HTML5 client)
                             build: 763
                        kurentoUrl: wss://reuniaofacilws.com.br/bbb-webrtc-sfu
                  enableListenOnly: true
```
Here is the output from #sudo bbb-conf --status
```
red5 ——————————————————► [✔ - active]
nginx —————————————————► [✔ - active]
freeswitch ————————————► [✔ - active]
redis-server ——————————► [✔ - active]
bbb-apps-akka —————————► [✔ - active]
bbb-transcode-akka ————► [✔ - active]
bbb-fsesl-akka ————————► [✔ - active]
mongod ————————————————► [✔ - active]
bbb-html5 —————————————► [✔ - active]
bbb-webrtc-sfu ————————► [✔ - active]
kurento-media-server ——► [✔ - active]
etherpad ——————————————► [✔ - active]
bbb-web ———————————————► [✔ - active]
```
When we try to open the URL created by the API MATE
https://reuniaofacilws.com.br/bigbluebutton/api/create?...
Here is the error:
```
404 Not Found
nginx/1.10.3 (Ubuntu)
```

Here is the output from #iptables -L -v
```
Chain INPUT (policy DROP 5 packets, 319 bytes)
 pkts bytes target     prot opt in     out     source               destination
 1311  164K ACCEPT     all  --  lo     any     anywhere             anywhere
 1290 59267 ACCEPT     all  --  any    any     anywhere             anywhere             state RELATED,ESTABLISHED
    0     0 ACCEPT     icmp --  any    any     anywhere             anywhere
    0     0 ACCEPT     tcp  --  any    any     anywhere             anywhere             tcp dpt:22022
    0     0 ACCEPT     tcp  --  any    any     anywhere             anywhere             tcp dpt:http
    2   104 ACCEPT     tcp  --  any    any     anywhere             anywhere             tcp dpt:https
    0     0 ACCEPT     tcp  --  any    any     anywhere             anywhere             tcp dpt:1935
    0     0 ACCEPT     tcp  --  any    any     anywhere             anywhere             tcp dpt:7443
    0     0 ACCEPT     tcp  --  any    any     anywhere             anywhere             tcp dpt:5066
   14  2256 ACCEPT     udp  --  any    any     anywhere             anywhere             multiport dports 16384:32768

Chain FORWARD (policy DROP 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination

Chain OUTPUT (policy ACCEPT 745 packets, 92765 bytes)
 pkts bytes target     prot opt in     out     source               destination
```

Can you please help in solving the problem?

Regards
Samuel Peixoto

**Comment by ffdixon** [comment]
Since the error is coming back from `nginx`, you can check the `bigbluebutton.access.log` and `error.log` files in `/var/log/nginx` for clues.

**Comment by jmpdsevilla** [comment]
Hi there,
How did you manage to solve the problem?

I finish installing with bb-install and everything ends correctly and everything works perfectly but when I restart the server it gives me the same error that you describe.

**Comment by rromandk** [comment]
Hello, 
      I have a similar problem but when I put the url on browser its show me the page. Before set ssl it was working ok but yesterday when i but ssl stop working.
   Thanks in advance.

**Comment by sushantdanekar** [comment]
I am getting this same error after setting up separate TURN server and using its domain into this file 
/usr/share/bbb-web/WEB-INF/classes/spring/turn-stun-servers.xml

**Comment by marove2000** [comment]
Had the same problem configurating TURN-Server. There was a syntax-error in /usr/share/bbb-web/WEB-INF/classes/spring/turn-stun-servers.xml

fixing it resulted in a normal startup.

**Comment by marove2000** [comment]
you have to replace <secret> and <turn-server>
 
    <bean id="turn0" class="org.bigbluebutton.web.services.turn.TurnServer">
        
        <constructor-arg index="0" value="<secret>"/>
        
        <constructor-arg index="1" value="turn:<turn-server>:443?transport=tcp"/>
        
        <constructor-arg index="2" value="86400"/>
    </bean>
    <bean id="turn1" class="org.bigbluebutton.web.services.turn.TurnServer">
        
        <constructor-arg index="0" value="<secret>"/>
        
        <constructor-arg index="1" value="turns:<turn-server>:443?transport=tcp"/>
        
        <constructor-arg index="2" value="86400"/>
    </bean>

And dont forget to activate turn0 and turn1:

        <property name="turnServers">
            <set>
                <ref bean="turn0" />
                <ref bean="turn1" />
                
            </set>
        </property>

More information: https://docs.bigbluebutton.org/2.2/setup-turn-server.html

**Comment by leandroportnoy** [comment]
I have the same problem... when I set a DNS with (bbb-config --setip mywebsite.com.br) I have a error.

**Comment by harika1258** [comment]
In this case please try :
bbb-conf --clean
bbb-conf --setip vc.example.com
If couldn't fix it I guess you have a problem (some of properties set comment maybe or false or true! or space ...) in the two below file :  
bigbluebutton.properties located in the /usr/share/bbb-web/WEB-INF/classes 
/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml

**Comment by gcmhyd** [comment]
> /var/lib/tomcat7

what you did please let me know iam getting same error

**Comment by hostbbb** [comment]
@gcmhyd go to google forums bigbluebutton-setup and provide more info about your install, the community can assist there.

version? was it working and just broke, any modifications?   Not here in the issue tracker..  will be ignored.

**Comment by orlipr84** [comment]
How funny, the colleague samuelpeixoto creates a post asking for help on a problem he has and it turns out that he supposedly did some checks, restarted the server and apparently everything works, but he did not say what he did to solve the problem, when there are other people having the same error and did not even bother as he himself published his topic, give the answer of how he solved it. People like these screwed up society, egotistical egoists.

**Comment by Rikarin-HesamMahmoodi** [comment]
I have this error during installation.
I want to start the service on the virtual machine. With DDNS, I set a hostname for the virtual machine's private IP.
