### ISSUE TITLE
Uploading a large pdf displays wrong error message to user

### ISSUE THREAD

**Issue by ritzalam** [bigbluebutton/bigbluebutton#8272]
Tried uploading a 16 page 44Mb pdf file. The client refuses to upload the file but displays a wrong error message.

<img width="951" alt="large-pdf-issue" src="https://user-images.githubusercontent.com/184672/67800099-1bfd5300-fa5d-11e9-8172-206ecdb82010.PNG">

**Comment by matiasilva** [comment]
I believe this has been fixed. Please close this issue.
