### ISSUE TITLE
Improve display message when pres page is too big to process

### ISSUE THREAD

**Issue by ritzalam** [bigbluebutton/bigbluebutton#8274]
<img width="331" alt="page-too-complex" src="https://user-images.githubusercontent.com/184672/67807810-e6139b00-fa6b-11e9-8959-bab3c19c8de3.PNG">

Change message to something like "Page X is too big or complex to process."

Maybe we can add a more info icon (e.g. i) that a user can hover or click to provide more information. Explaining that the page might have a gradient background, etc. etc.

**Comment by jfsiebel** [comment]
Since 2.3 we don't throw an error when the uploaded file have a big page.
