### ISSUE TITLE
Add a maximize button for presentation in presentation recording format

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#8275]
Currently, there is a maximize button for the video, but not the presentation. 

Add a maximize button to enable playback of the presentation full screen.

**Comment by girishgl** [comment]
> Currently, there is a maximize button for the video, but not the presentation.
> 
> Add a maximize button to enable playback of the presentation full screen.

This will be very helpful as most of the times, students want to see the presentation in full screen mode.

**Comment by pbdco** [comment]
Hi! any news on this?

**Comment by iSamof** [comment]
Just curios ... has anyone tried the "Ctrl +" on the reply to see if the enlargement works and if so how does it look!

**Comment by hiroshisuga** [comment]
A tentative modification for BBB 2.2 is in #9648 .
