### ISSUE TITLE
Set User Status Bug

### ISSUE THREAD

**Issue by lifeofdan** [bigbluebutton/bigbluebutton#8278]
You cannot change the user status when the public chat or shared notes are closed.

To reproduce. 

1. Leave the USERS panel open. Close both the public chat and shared notes so there is no panel open. 
2. Click your user avatar. 
3. Select Set Status.
4. The dialogue will close without allowing you to set a status.
5. Reopen one of the panels, either public chat or shared notes. 
6. Repeat steps 2 and 3. 

This time the dialogue will allow you to set a status.

**Comment by capilkey** [comment]
I can't reproduce this when testing on master. Are you able to reproduce on demo.bigbluebutton.org?

**Comment by matiasilva** [comment]
@lifeofdan updates?

**Comment by lifeofdan** [comment]
In the most recent build that I'm running, I cannot reproduce this bug either. I am going to close this issue.
