### ISSUE TITLE
Webcam, audio and microphone not working

### ISSUE THREAD

**Issue by hhuseyinpay** [bigbluebutton/bigbluebutton#8279]
Hi
I setup bbb beta-23 with ssl on my server everything is looks OK but webcam, audio and microphone not working. I used bbb-install script. (I tried demo.bigbluebutton.com and there is no problem. )
When I try to open webcam I get the Error 1020,  audio and microphone -> Error 1007 

Some outputs:

<img width="317" alt="Screen Shot 2019-10-31 at 12 13 38" src="https://user-images.githubusercontent.com/14811488/67933951-e9c43080-fbd7-11e9-90a8-64a1443f71d9.png">

<img width="718" alt="Screen Shot 2019-10-31 at 12 14 27" src="https://user-images.githubusercontent.com/14811488/67934004-01031e00-fbd8-11e9-8ead-cb71958c5c48.png">

<img width="955" alt="Screen Shot 2019-10-31 at 12 15 22" src="https://user-images.githubusercontent.com/14811488/67934059-21cb7380-fbd8-11e9-8b07-f4a933395214.png">

Some error logs:
<img width="1259" alt="Screen Shot 2019-10-31 at 12 16 15" src="https://user-images.githubusercontent.com/14811488/67934126-46275000-fbd8-11e9-82c3-4c4de0a5c898.png">

<img width="1275" alt="Screen Shot 2019-10-31 at 12 18 18" src="https://user-images.githubusercontent.com/14811488/67934239-8c7caf00-fbd8-11e9-9524-bc7866b6f3c0.png">

**Comment by ffdixon** [comment]
Hi,

A few questions to try and narrow down the issue

  * Are you installing on a public server (available on the Internet) or behind a firewall?  
  * If public, what hosting provider did you use (i.e . Amazon, Google, Microsoft, Digital Ocean, etc.)? 
  * Does your server have a public/private IP address?

**Comment by hhuseyinpay** [comment]
Thank you for your interest. 
I solved the problem. I deleted all iptable rules and it just worked. You may add some note about this issue. There is a section for the firewalls but the first look I don't thought that it means iptables.
(By the way I have physical server in the datacenter.)
