### ISSUE TITLE
How to edit SWF File 

### ISSUE THREAD

**Issue by richwebs8** [bigbluebutton/bigbluebutton#8285]
Hello,

I want some customization on Script and I want to edit the same where to edit HTML5Client.

**Comment by ffdixon** [comment]
Can we get you to post these questions to our bigbluebutton-dev mailing list.  That's the better forum for general questions.  See

  https://bigbluebutton.org/support

If in answering your question we find a bug with BigBlueButton, we'll open an issue here to track it.
