### ISSUE TITLE
Language change problem in HTML5

### ISSUE THREAD

**Issue by ycw7701** [bigbluebutton/bigbluebutton#8289]
Dear all,

When the language is changed, the language is not displayed and is displayed by variable name.

![lan01](https://user-images.githubusercontent.com/48506289/68108325-cfb58580-ff2a-11e9-819b-08e774da2d01.jpg)

I copied the language file to the following location:
/usr/share/meteor/bundle/programs/server/assets/app/locales/ko.json

/usr/share/meteor/bundle/programs/server/program.json
In the above file, I added the following source:
"locales/ko.json": "assets/app/locales/ko.json"

How can I fix it? Help me.

Thanks in advance
Ethan

**Comment by antobinary** [comment]
Hi @ycw7701 ,
Is it an option for you to join Transifex so we can add Korean locales for the HTML5 client? https://www.transifex.com/bigbluebutton/bigbluebutton-v22-html5-client/languages/

If you just want to build the client and run locally - this is a PR where we added a new language support (along with pulling locales) https://github.com/bigbluebutton/bigbluebutton/pull/7685/
You can see where in the source we connected it.

**Comment by ycw7701** [comment]
Thank you for your answer!

**Comment by salimane** [comment]
@ycw7701 @antobinary how did you add the new language on your local server without going through transifex. We would like to add a new language by just translating the English language file and uploading it to our server. is it possible to do that?

**Comment by Arthemis97** [comment]
@ycw7701 how did you solve this?
