### ISSUE TITLE
poll option overlay by presentation dock on mobile

### ISSUE THREAD

**Issue by ashishkpaul** [bigbluebutton/bigbluebutton#8306]
Sir, on BigBlueButton Server 2.2.0-beta-23 (1509), Poll option is not visible to viewers when presentation dock maximize on a mobile (tested on android version 9). presentation dock overlay poll option.

**Comment by pedrobmarin** [comment]
Handled at https://github.com/bigbluebutton/bigbluebutton/pull/11319
