### ISSUE TITLE
404 error page after install bbb 2.0

### ISSUE THREAD

**Issue by mohammadva** [bigbluebutton/bigbluebutton#8308]
I installed bbb with bbb-install.sh script, but when I click on join button, 404 error page occurred.

404 error page
nginx/1.10.3 (Ubuntu)

root@???:~# bbb-conf --check

BigBlueButton Server 2.0.0 (1684)
                    Kernel version: 4.4.0-166-generic
                      Distribution: Ubuntu 16.04.6 LTS (64-bit)
                            Memory: 4045 MB

/var/www/bigbluebutton/client/conf/config.xml (bbb-client)
                Port test (tunnel): rtmp://??.??.??.??
                              red5: ??.??.??.??
              useWebrtcIfAvailable: true

/opt/freeswitch/etc/freeswitch/sip_profiles/external.xml (FreeSWITCH)
                         websocket: :7443
                    WebRTC enabled: true

/etc/nginx/sites-available/bigbluebutton (nginx)
                       server name: ??.??.??.??
                              port: 80, [::]:80
                    bbb-client dir: /var/www/bigbluebutton

/var/lib/tomcat7/webapps/bigbluebutton/WEB-INF/classes/bigbluebutton.properties (bbb-web)
                      bbb-web host: ??.??.??.??

/usr/share/red5/webapps/bigbluebutton/WEB-INF/red5-web.xml (red5)
                  voice conference: FreeSWITCH

/usr/local/bigbluebutton/core/scripts/bigbluebutton.yml (record and playback)
                     playback host: ??.??.??.??
                            ffmpeg: 4.1.3-0york1~16.04

/usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml (Kurento)
                        kurentoUrl: ws://??.??.??.??:8888/kurento
                         kurentoIp: ??.??.??.??
                    localIpAddress: ??.??.??.??
               recordScreenSharing: true
                     recordWebcams: true
                              Node: v8.16.2
                           mongoDB: v3.4.23

** Potential problems described below **
# Warning: The voice application may not have registered with the sip server.
#   Try running: 
#
#      bbb-conf --clean
#

root@???:~# ls -al /etc/bigbluebutton/nginx
total 44
drwxr-xr-x 2 red5   red5   4096 Nov  7 16:54 .
drwxr-xr-x 3 red5   red5   4096 Nov  7 16:45 ..
-rw-r--r-- 1 meteor meteor  232 Feb 23  2019 bbb-html5.nginx
-rw-r--r-- 1 root   root    434 Feb 22  2019 client
lrwxrwxrwx 1 root   root     31 Nov  7 16:42 client.nginx -> /etc/bigbluebutton/nginx/client
-rw-r--r-- 1 root   root   1510 Feb  1  2019 presentation.nginx
-rw-r--r-- 1 root   root   2197 Jan  3  2019 presentation-slides.nginx
-rw-r--r-- 1 red5   red5    729 Sep  4  2018 screenshare.nginx
-rw-r--r-- 1 root   root    310 Nov  7 16:42 sip.nginx
-rw-r--r-- 1 red5   red5    261 Sep  4  2018 verto.nginx
-rw-r--r-- 1 root   root   2529 Feb 22  2019 web
lrwxrwxrwx 1 root   root     28 Nov  7 16:42 web.nginx -> /etc/bigbluebutton/nginx/web
-rw-r--r-- 1 root   root    318 Apr  8  2019 webrtc-sfu.nginx

**Comment by capilkey** [comment]
You don't have the "bbb-demo" package installed. I would also recommend installing 2.2 instead of 2.0 if you're just starting out with BigBlueButton.

**Comment by ffdixon** [comment]
You can also install the API demos by adding the parameter `-a` to the `bbb-install.sh` command.

You don't want the API demos running on a production server, which is why we have it as an optional parameter.

**Comment by mohammadva** [comment]
Thanks
