### ISSUE TITLE
SSL configuration issue

### ISSUE THREAD

**Issue by mohammadva** [bigbluebutton/bigbluebutton#8310]
After SSL configuration I have below issue after restart. How can I find solution?

root@vclass:~# bbb-conf --restart
# IP does not match:
#                           IP from ifconfig: ???.???.???.???
#   /etc/nginx/sites-available/bigbluebutton: my.sample.com
Restarting BigBlueButton 2.0.0 ...
Stopping BigBlueButton
Starting BigBlueButton

** Potential problems described below **
# IP does not match:
#                           IP from ifconfig: ???.???.???.???
#   /etc/nginx/sites-available/bigbluebutton:  my.sample.com
....................
# Error: Could not connect to the configured hostname/IP address
#
#    https://my.sample.com/
#
# If your BigBlueButton server is behind a firewall, see FAQ.

# Error: Unable to connect to port 1935 (RTMP) on  my.sample.com

# Error: Unable to reach default URL for presentation:
#
#    https://my.sample.com/default.pdf
#
# Check value for beans.presentationService.defaultUploadedPresentation in
#   /var/lib/tomcat7/webapps/bigbluebutton/WEB-INF/classes/bigbluebutton.properties

**Comment by ffdixon** [comment]
Hi there,

Can we get you to post this to bigbluebutton-setup mailing list, which is the place for installation/configuration issues.  See
 
  https://bigbluebutton.org/support

We can then help you there and, if in course of helping out, we see there is a problem associated with BigBlueButton that needs to be fixed, we can open an issue here.
