### ISSUE TITLE
Webcam loading animation is stretched thin

### ISSUE THREAD

**Issue by prlanzarin** [bigbluebutton/bigbluebutton#8311]
Tested on Firefox 70.0.1, current master.

![Uploading thin.gif…]()

**Comment by ffdixon** [comment]
The upload didn't come through, but I think this is what your referring to

![image](https://user-images.githubusercontent.com/290351/68513664-9c843680-0249-11ea-8970-7ae8d65676a3.png)

**Comment by prlanzarin** [comment]
Yeah, that's it. Thanks @ffdixon, didn't realize it hadn't come through.

**Comment by GhaziTriki** [comment]
The loading animation is no more present.
