### ISSUE TITLE
How to disabled whiteboard 

### ISSUE THREAD

**Issue by bijism** [bigbluebutton/bigbluebutton#8317]
We are developing a dashboard for the BBB and need to be able to build a class without the WHITEBOARD API.  We need this for webinars.  please guide us.

**Comment by capilkey** [comment]
There's no API for the whiteboard.

There are two options that I can think of. The first option is to remove all of the whiteboard tools, except hand, from the HTML5 client's settings.yml file. I'm not sure what will happen if you remove them all so I would leave one in. The other option is to comment out the toolbar and hide it.

I would recommend option 1.

**Comment by shashwatadi** [comment]
@bijism Can you share what you ended up doing?

**Comment by ajithgopi** [comment]
@shashwatadi There's a configuration where the presentation window can be disabled.
https://groups.google.com/forum/#!topic/bigbluebutton-dev/vbIPrXUeAHM
