### ISSUE TITLE
close whiteboard at strart class

### ISSUE THREAD

**Issue by khanifarahmad** [bigbluebutton/bigbluebutton#8320]
how close or hide whiteboard in bigbluebutton automatically when start my classes?

**Comment by capilkey** [comment]
This isn't an issue with the product. Please direct questions to one of the mailing lists.

https://groups.google.com/forum/#!topic/bigbluebutton-dev
https://groups.google.com/forum/#!topic/bigbluebutton-setup
https://groups.google.com/forum/#!topic/bigbluebutton-users
