### ISSUE TITLE
Talking users indicators should display from the right for RTL layouts

### ISSUE THREAD

**Issue by GhaziTriki** [bigbluebutton/bigbluebutton#8324]
![image](https://user-images.githubusercontent.com/4991088/68697912-11c07600-0580-11ea-988d-04293b2de5d3.png)

**Comment by Jossef-767** [comment]
Also,,, writing on the whiteboard, with the writing tools, aligns to the left instead of the right

**Comment by Jossef-767** [comment]
also,,, Closed captions Not aligned with the other lines 
![image](https://user-images.githubusercontent.com/2356928/68855547-1d7a7c80-06e7-11ea-88a8-5474f136827f.png)
