### ISSUE TITLE
Microphone indicator not centred in firefox

### ISSUE THREAD

**Issue by GhaziTriki** [bigbluebutton/bigbluebutton#8339]
![image](https://user-images.githubusercontent.com/4991088/69035741-9e39c100-09e4-11ea-8f85-b689ad1a75f8.png)

**Comment by capilkey** [comment]
![image](https://user-images.githubusercontent.com/1395090/69075132-cafad200-09fe-11ea-879b-08b4fb6c69ae.png)

It looks centered to me

**Comment by GhaziTriki** [comment]
Fixed in 2.2-RC5
