### ISSUE TITLE
The sound deactivate when I change the language on chrome 64bit

### ISSUE THREAD

**Issue by abszar** [bigbluebutton/bigbluebutton#8342]
Hello guys,

The sound goes off every time I change the language from the settings. And to reactivate it I have to reload the page 😕.

I use google chrome (Version 78.0.3904.97 (64 bits)) on windows 

And I am also using the demo on https://demo.bigbluebutton.org/

Nothing weird in the console as you can see : 
![image](https://user-images.githubusercontent.com/5203446/69157098-c6104e00-0ae4-11ea-8f5c-d7d3b51c89e9.png)

Thank you

**Comment by pedrobmarin** [comment]
Tackled at https://github.com/bigbluebutton/bigbluebutton/pull/8697
