### ISSUE TITLE
Weird message result (distortion ) when I see the poll result in Arabic

### ISSUE THREAD

**Issue by abszar** [bigbluebutton/bigbluebutton#8343]
Hello guys,

When the poll ends the displayed result message in Arabic gives a Weird distortion on the text (nothing wrong with other languages as far as I know).

I use google chrome (Version 78.0.3904.97 (64 bits)) on windows

And I am also using the demo on https://demo.bigbluebutton.org/

this is the result I get : 
( it should be `نعم` and `لا` for `yes` and `no` )
![image](https://user-images.githubusercontent.com/5203446/69158095-2ce23700-0ae6-11ea-8057-32133cb5aff1.png)

**Comment by pedrobmarin** [comment]
@GhaziTriki @daminebenq are https://github.com/bigbluebutton/bigbluebutton/issues/8082 and this one the same issue?

**Comment by daminebenq** [comment]
Hey @pedrobmarin, yes they are about same issue.
