### ISSUE TITLE
When the audio call hits a timeout it isn't ended and continues to connect in the background

### ISSUE THREAD

**Issue by capilkey** [bigbluebutton/bigbluebutton#8344]
There are two timeouts (1006 and 1008) that can get hit in the client if the initial invite isn't responded to or if the transfer to the conference takes a while. When these timeouts occur there's a fallback in the client to try alternate audio paths (IPv4, reconnect), but the original call isn't actually ended and sip.js is still trying to (re)connect in the background. What ends up happening is that we have two independent audio calls at the same time and it results in feedback to the user.

Need to look at the sip.js audio bridge and see if there's a way to definitively hangup the call when one of our timeouts gets hit.

I also want to see if we should increase the time before a 1006 is triggered because there seems to be an uptick in users hitting that specific error with the newer builds of FreeSWITCH that we're running.

**Comment by pedrobmarin** [comment]
@mariogasparoni is this reproducible?

**Comment by mariogasparoni** [comment]
Not really. This can be closed
