### ISSUE TITLE
There needs to be a way to define an IPv4-only TURN server

### ISSUE THREAD

**Issue by capilkey** [bigbluebutton/bigbluebutton#8345]
A while back we added an option to try audio calls with a separate IPv4-only domain because there are a lot of users that have broken IPv6 implementations and we wanted a way to force IPv4 because FreeSWITCH can't do dual-stack ICE. One missing part to this implementation is that if the TURN server can also be available from IPv6 and IPv4, and it won't be a valid option when falling back to IPv4-only because the relay candidate that is generated will be IPv6 and FS will throw it out.

We need to add an optional attribute to the turn-stun-server.xml file to allow for identifying if the TURN server is for IPv4 fallback or not and then in the client only use that TURN server when falling back.

Once this is done the TURN server will again be a valid candidate in the case of fallback.

**Comment by jodoma** [comment]
I am not into the code, but my guess is that what you describe should be doable with a the REQUESTED-ADDRESS-FAMILY attribute in TURN: https://tools.ietf.org/html/rfc6156#section-4.1.1
