### ISSUE TITLE
Display screen sharing icon on Safari desktop

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#8346]
Currently, we don't support screen sharing on Safari desktop.  Instead, we hide the icon.

This has caused some confusion with users wondering why the can't share their screen.  Instead of hiding the icon, display it instead and, when clicked, show the following message

  "Screen sharing is not currently supported in this browser (recommend Chrome or Firefox)"

**Comment by capilkey** [comment]
I think it would also be good to do the same thing with mobile browsers. They aren't ever going to support screen sharing, but if we don't tell the user that then they think that the button is broken instead of intentionally disabled.

**Comment by ffdixon** [comment]
I was thinking that as well, but there isn't a lot of space available on a portrait phone display, and, unlike desktop, there is no recommended solution we can provide.  It is simply not supported by the browser.

**Comment by aogilvie** [comment]
https://github.com/bigbluebutton/bigbluebutton/issues/8576

**Comment by prlanzarin** [comment]
Fixed by #9066.
