### ISSUE TITLE
Presentation navigation via PgUp / PgDn keys

### ISSUE THREAD

**Issue by adia** [bigbluebutton/bigbluebutton#8348]
After upgrading to BigBlueButton 2.2 and disabling the Flash interface, a user reported that they can no longer use a remote presenter/laser pointer (that previously worked) to navigate to the next / previous slide in the presentation.

It seems that the HTML5 interface supports only navigation via the Left / Right arrow keys, while this presenter sends Page Up / Page Down. Would it be possible to add support for these keys as well?

Thanks!

**Comment by antobinary** [comment]
We recently added this feature via https://github.com/bigbluebutton/bigbluebutton/pull/8128
Expect to be able to use it starting from BigBlueButton release 2.2.0-rc2 (next upcoming release)
