### ISSUE TITLE
Error: You must specify a meeting ID for the meeting.

### ISSUE THREAD

**Issue by ahmetergul35** [bigbluebutton/bigbluebutton#8351]
I installed bbb-tool on Sakai 19-SNAPSHOT. BBB alone runs smoothly. But when I started a meeting through sakai, "Error: You must specify a meeting ID for the meeting." I get an error. Attached is a screenshot. I've never seen a peoblem like this before. 

Anyone have any idea? 
Thanks in advance...

Sakai 19-SNAPSHOT 
BBB 2.2.0-rc-1 
https://github.com/sakaicontrib/bbb-tool

**Comment by ahmetergul35** [comment]
<img width="820" alt="bbb-error" src="https://user-images.githubusercontent.com/10403168/69328969-41970a00-0c61-11ea-9f1e-d80fe95f8fa0.png">

**Comment by ffdixon** [comment]
Can you check the log on your BigBlueButton server  `/var/log/bigbluebutton/bbb-web.log` and see if your getting API requests.

Also, check `/var/log/nginx/bigbluebutton.access.log` to see if the `create` API call to ensure it's passing the `meetingID` when you try and create a meeting.

**Comment by ffdixon** [comment]
Also, can you (temporarily) install the API demos via `sudo apt-get install bbb-demo` and try joining from the home page of the BigBlueButton server.  Does that work?

**Comment by ahmetergul35** [comment]
yes it has improved.

Thank you

*   Ahmet Volkan ERGÜL*
Dokuz Eylul University
DEUZEM / IT Coordinator
Linux & Network System Administration
CCNA-Security, CCNA 200-125 (R&S), CCNA Data Center, CCNP (R&S)
--
Bu e-postadan çıktı almayarak çevreye katkıda bulunabilirsiniz.


Fred Dixon <notifications@github.com>, 25 Kas 2019 Pzt, 00:06 tarihinde
şunu yazdı:

**Comment by ahmetergul35** [comment]
Hi Fred,
I don't know how the problem is solved. When I arrived the next morning it was working fine. For this reason, I could not write the solution. But when I tried to create a meeting over sakai again this morning, I encountered the same error.

**Comment by ahmetergul35** [comment]
/var/log/nginx/bigbluebutton.access.log also has:

193.140.26.22 - - [04/Dec/2019:10:43:17 +0300] "GET /bigbluebutton/api/getMeetings?random=xyz&checksum=cc019cb098e37416ca5d955234d27931556992bf HTTP/1.1" 200 171 "-" "Sakai Java/1.8.0_171"
139 193.140.26.22 - - [04/Dec/2019:10:43:20 +0300] "GET /bigbluebutton/api/getMeetings?random=xyz&checksum=cc019cb098e37416ca5d955234d27931556992bf HTTP/1.1" 200 171 "-" "Sakai Java/1.8.0_171"
140 193.140.26.22 - - [04/Dec/2019:10:43:38 +0300] "GET /bigbluebutton/api/getMeetings?random=xyz&checksum=cc019cb098e37416ca5d955234d27931556992bf HTTP/1.1" 200 171 "-" "Sakai Java/1.8.0_171"
141 193.140.26.22 - - [04/Dec/2019:10:43:39 +0300] "GET /bigbluebutton/api/getMeetingInfo?meetingID=fd05945b-0114-43b9-a254-4f5198eed43f&password=d1ed48d649dad94e&checksum=59ee1dd9668358276f4505cbf0b9f486d5d9431c HTTP/1.1" 200 171 "-" "Sakai 
    Java/1.8.0_171"
142 193.140.26.22 - - [04/Dec/2019:10:43:39 +0300] "GET /bigbluebutton/api/getRecordings?meetingID=fd05945b-0114-43b9-a254-4f5198eed43f&checksum=b8c5fdfbb9d411154fa4e68f2e6c17a44a8be83d HTTP/1.1" 200 241 "-" "Sakai Java/1.8.0_171"
143 127.0.0.1 - - [04/Dec/2019:10:43:41 +0300] "GET /client/conf/config.xml HTTP/1.1" 200 6637 "-" "Apache-HttpClient/4.5.6 (Java/1.8.0_222)"
144 127.0.0.1 - - [04/Dec/2019:10:43:41 +0300] "GET /default.pdf HTTP/1.1" 200 369690 "-" "Mozilla"
145 127.0.0.1 - - [04/Dec/2019:10:43:41 +0300] "GET /default.pdf HTTP/1.1" 200 369690 "-" "Apache-HttpAsyncClient/4.1.4 (Java/1.8.0_222)"
146 193.140.26.22 - - [04/Dec/2019:10:43:41 +0300] "GET /bigbluebutton/api/create?meetingID=fd05945b-0114-43b9-a254-4f5198eed43f&name=04122019-test1&voiceBridge=79651&attendeePW=d1f327c304fb8dae&moderatorPW=d1ed48d649dad94e&logoutURL=http%3A%
    2F%2F193.140.26.22%3A8080%2Fbbb-tool%2Fbbb-autoclose.html&record=true&duration=0&meta_originServerUrl=http%3A%2F%2F193.140.26.22%3A8080&meta_origin=Sakai&meta_originVersion=19-SNAPSHOT&meta_context=%22TEMP1%22+%28TEMP1%29&meta_originServe
    rCommonName=localhost&meta_originTag=Sakai%5B19-SNAPSHOT%5D%2Fbbb-tool%5B19-SNAPSHOT_2019042001%5D&meta_contextId=TEMP1&meta_contextActivity=04122019-test1&welcome=%3Cb%3E%25%25CONFNAME%25%25%3C%2Fb%3E+toplant%C4%B1s%C4%B1na+ho%C5%9Fgeldi
    niz%21%3Cbr%3E%3Cbr%3EBuraya+toplant%C4%B1+hakk%C4%B1nda+a%C3%A7%C4%B1klama+giriniz%3Cbr%3E%3Cbr%3EToplant%C4%B1+ara%C3%A7lar%C4%B1n%C4%B1n+kullan%C4%B1m%C4%B1+i%C3%A7in+%3Ca+href%3D%22event%3Ahttps%3A%2F%2Fbigbluebutton.org%2Fhtml5%22%3E
    %3Cu%3Evideolar%C4%B1%3C%2Fu%3E%3C%2Fa%3E+izleyiniz.%3Cbr%3E%09%3Cbr%3E%3Cbr%3E%3Cb%3EBu+toplant%C4%B1+kaydediliyor.%3C%2Fb%3E&checksum=36e584246d184af7c897a091b05a86de4cf84819 HTTP/1.1" 200 688 "-" "Sakai Java/1.8.0_171"
147 193.140.152.171 - - [04/Dec/2019:10:43:41 +0300] "GET /bigbluebutton/api/join?&fullName=Sakai+Administrator&password=d1ed48d649dad94e&checksum=8f96b5ba2fb892fffd4b5857f432e2a2e92f1782 HTTP/1.1" 302 0 "http://193.140.26.22:8080/direct/bbb-
    tool/fd05945b-0114-43b9-a254-4f5198eed43f/joinMeeting?nonce=1575445421204" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.87 Safari/537.36"
148 193.140.152.171 - - [04/Dec/2019:10:43:41 +0300] "GET /?errors=[%7B%22message%22:%22You%20must%20specify%20a%20meeting%20ID%20for%20the%20meeting.%22,%22key%22:%22missingParamMeetingID%22%7D] HTTP/1.1" 304 0 "http://193.140.26.22:8080/dir
    ect/bbb-tool/fd05945b-0114-43b9-a254-4f5198eed43f/joinMeeting?nonce=1575445421204" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.87 Safari/537.36"
149 193.140.152.171 - - [04/Dec/2019:10:43:41 +0300] "GET /css/style.css HTTP/1.1" 304 0 "https://bbb.deuzem.deu.edu.tr/?errors=[%7B%22message%22:%22You%20must%20specify%20a%20meeting%20ID%20for%20the%20meeting.%22,%22key%22:%22missingParamMe
    etingID%22%7D]" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.87 Safari/537.36"
150 193.140.152.171 - - [04/Dec/2019:10:43:41 +0300] "GET /css/font-awesome.min.css HTTP/1.1" 304 0 "https://bbb.deuzem.deu.edu.tr/?errors=[%7B%22message%22:%22You%20must%20specify%20a%20meeting%20ID%20for%20the%20meeting.%22,%22key%22:%22mis
    singParamMeetingID%22%7D]" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.87 Safari/537.36"
151 193.140.152.171 - - [04/Dec/2019:10:43:41 +0300] "GET /css/bbb-bootstrap.css HTTP/1.1" 304 0 "https://bbb.deuzem.deu.edu.tr/?errors=[%7B%22message%22:%22You%20must%20specify%20a%20meeting%20ID%20for%20the%20meeting.%22,%22key%22:%22missin
    gParamMeetingID%22%7D]" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.87 Safari/537.36"
152 193.140.152.171 - - [04/Dec/2019:10:43:41 +0300] "GET /css/bijou.min.css HTTP/1.1" 304 0 "https://bbb.deuzem.deu.edu.tr/?errors=[%7B%22message%22:%22You%20must%20specify%20a%20meeting%20ID%20for%20the%20meeting.%22,%22key%22:%22missingPar
    amMeetingID%22%7D]" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.87 Safari/537.36"
153 193.140.152.171 - - [04/Dec/2019:10:43:41 +0300] "GET /js/jquery.min.js HTTP/1.1" 304 0 "https://bbb.deuzem.deu.edu.tr/?errors=[%7B%22message%22:%22You%20must%20specify%20a%20meeting%20ID%20for%20the%20meeting.%22,%22key%22:%22missingPara
    mMeetingID%22%7D]" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.87 Safari/537.36"
154 193.140.152.171 - - [04/Dec/2019:10:43:41 +0300] "GET /js/bootstrap.min.js HTTP/1.1" 304 0 "https://bbb.deuzem.deu.edu.tr/?errors=[%7B%22message%22:%22You%20must%20specify%20a%20meeting%20ID%20for%20the%20meeting.%22,%22key%22:%22missingP
    aramMeetingID%22%7D]" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.87 Safari/537.36"
155 193.140.152.171 - - [04/Dec/2019:10:43:41 +0300] "GET /js/bigbluebutton.js HTTP/1.1" 304 0 "https://bbb.deuzem.deu.edu.tr/?errors=[%7B%22message%22:%22You%20must%20specify%20a%20meeting%20ID%20for%20the%20meeting.%22,%22key%22:%22missingP
    aramMeetingID%22%7D]" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.87 Safari/537.36"
156 193.140.152.171 - - [04/Dec/2019:10:43:41 +0300] "GET /images/bbb-logo.png HTTP/1.1" 304 0 "https://bbb.deuzem.deu.edu.tr/?errors=[%7B%22message%22:%22You%20must%20specify%20a%20meeting%20ID%20for%20the%20meeting.%22,%22key%22:%22missingP
    aramMeetingID%22%7D]" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.87 Safari/537.36"
157 193.140.152.171 - - [04/Dec/2019:10:43:41 +0300] "GET /images/bbb-setup-audio.jpg HTTP/1.1" 304 0 "https://bbb.deuzem.deu.edu.tr/?errors=[%7B%22message%22:%22You%20must%20specify%20a%20meeting%20ID%20for%20the%20meeting.%22,%22key%22:%22m
    issingParamMeetingID%22%7D]" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.87 Safari/537.36"
158 193.140.152.171 - - [04/Dec/2019:10:43:41 +0300] "GET /images/bbb-viewer-overview.png HTTP/1.1" 304 0 "https://bbb.deuzem.deu.edu.tr/?errors=[%7B%22message%22:%22You%20must%20specify%20a%20meeting%20ID%20for%20the%20meeting.%22,%22key%22:
    %22missingParamMeetingID%22%7D]" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.87 Safari/537.36"
159 193.140.152.171 - - [04/Dec/2019:10:43:41 +0300] "GET /images/bbb-presenter-overview.png HTTP/1.1" 304 0 "https://bbb.deuzem.deu.edu.tr/?errors=[%7B%22message%22:%22You%20must%20specify%20a%20meeting%20ID%20for%20the%20meeting.%22,%22key%
    22:%22missingParamMeetingID%22%7D]" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.87 Safari/537.36"
160 193.140.152.171 - - [04/Dec/2019:10:43:41 +0300] "GET /fonts/fontawesome-webfont.woff2?v=4.7.0 HTTP/1.1" 304 0 "https://bbb.deuzem.deu.edu.tr/css/font-awesome.min.css" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/537.36 (K
    HTML, like Gecko) Chrome/78.0.3904.87 Safari/537.36"

**Comment by ahmetergul35** [comment]
I installed ddd-demo. Through the demo I can log in smoothly. I only have problems with the meetings that I set up on the sakai side :(((

**Comment by ahmetergul35** [comment]
Hi Fred;
Same problem I lived again this morning. I wrote it through Github. I'd
appreciate it if you could take care of it and find a permanent solution.

Thank you...

* Ahmet Volkan ERGÜL*
Dokuz Eylul University
DEUZEM / IT Coordinator
Linux & Network System Administration
CCNA-Security, CCNA 200-125 (R&S), CCNA Data Center, CCNP (R&S)
--
Bu e-postadan çıktı almayarak çevreye katkıda bulunabilirsiniz.


Fred Dixon <notifications@github.com>, 25 Kas 2019 Pzt, 00:06 tarihinde
şunu yazdı:

**Comment by ahmetergul35** [comment]
bbb-web.log;

--- 2019-12-04T11:54:57.693+03:00 INFO  o.bigbluebutton.api.MeetingService -  --analytics-- data={"duration":0,"record":true,"logCode":"create_meeting","name":"04122019-test1","description":"Create meeting.","meetingId":"7368f2ca976de236ae039
    3c9207abd36e767924d-1575449697642","externalMeetingId":"fd05945b-0114-43b9-a254-4f5198eed43f","isBreakout":false,"webcamsOnlyForModerator":false}
--- 2019-12-04T11:54:57.722+03:00 INFO  o.bigbluebutton.api.MeetingService -  --analytics-- data={"duration":0,"record":true,"logCode":"meeting_started","name":"04122019-test1","description":"Meeting has started.","meetingId":"7368f2ca976de23
    6ae0393c9207abd36e767924d-1575449697642","externalMeetingId":"fd05945b-0114-43b9-a254-4f5198eed43f","isBreakout":false}
--- 2019-12-04T11:54:57.913+03:00 DEBUG o.b.web.controllers.ApiController - Rendering as xml
--- 2019-12-04T11:54:57.997+03:00 DEBUG o.b.web.controllers.ApiController - ApiController#join
--- 2019-12-04T11:54:57.997+03:00 DEBUG o.b.web.controllers.ApiController - ApiController#invalid You must specify a meeting ID for the meeting.
--- 2019-12-04T11:54:57.998+03:00 DEBUG o.b.web.controllers.ApiController - JSON Errors [{"message":"You must specify a meeting ID for the meeting.","key":"missingParamMeetingID"}]
--- 2019-12-04T11:54:57.999+03:00 DEBUG o.b.web.controllers.ApiController - Constructed logout URL https://bbb.deuzem.deu.edu.tr?errors=[%7B%22message%22:%22You%20must%20specify%20a%20meeting%20ID%20for%20the%20meeting.%22,%22key%22:%22missin
    gParamMeetingID%22%7D]

**Comment by ahmetergul35** [comment]
root@bbb:/# bbb-conf --check                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                  
BigBlueButton Server 2.2.0-rc-1 (1569)                                                                                                                                                                                                            
                    Kernel version: 4.4.0-170-generic                                                                                                                                                                                             
                      Distribution: Ubuntu 16.04.6 LTS (64-bit)                                                                                                                                                                                   
                            Memory: 32164 MB                                                                                                                                                                                                      
                         CPU cores: 4                                                                                                                                                                                                             
                                                                                                                                                                                                                                                  
/usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties (bbb-web)                                                                                                                                                                             
       bigbluebutton.web.serverURL: https://bbb.deuzem.deu.edu.tr                                                                                                                                                                                 
                defaultGuestPolicy: ALWAYS_ACCEPT                                                                                                                                                                                                 
                 svgImagesRequired: true                                                                                                                                                                                                          
                                                                                                                                                                                                                                                  
/etc/nginx/sites-available/bigbluebutton (nginx)                                                                                                                                                                                                  
                       server name: bbb.deuzem.deu.edu.tr                                                                                                                                                                                         
                              port: 80, [::]:80                                                                                                                                                                                                   
                              port: 443 ssl                                                                                                                                                                                                       
                    bbb-client dir: /var/www/bigbluebutton                                                                                                                                                                                        
                                                                                                                                                                                                                                                  
/var/www/bigbluebutton/client/conf/config.xml (bbb-client)                                                                                                                                                                                        
                Port test (tunnel): rtmp://bbb.deuzem.deu.edu.tr                                                                                                                                                                                  
                              red5: bbb.deuzem.deu.edu.tr                                                                                                                                                                                         
              useWebrtcIfAvailable: true                                                                                                                                                                                                          
                                                                                                                                                                                                                                                  
/opt/freeswitch/etc/freeswitch/vars.xml (FreeSWITCH)                                                                                                                                                                                              
                       local_ip_v4: 161.9.173.12                                                                                                                                                                                                  
                   external_rtp_ip: stun:stun.freeswitch.org                                                                                                                                                                                      
                   external_sip_ip: stun:stun.freeswitch.org                                                                                                                                                                                      
                                                                                                                                                                                                                                                  
/opt/freeswitch/etc/freeswitch/sip_profiles/external.xml (FreeSWITCH)                                                                                                                                                                             
                        ext-rtp-ip: $${local_ip_v4}                                                                                                                                                                                               
                        ext-sip-ip: $${local_ip_v4}                                                                                                                                                                                               
                        ws-binding: :5066                                                                                                                                                                                                         
                       wss-binding: :7443                                                                                                                                                                                                         
                                                                                                                                                                                                                                                  
/usr/local/bigbluebutton/core/scripts/bigbluebutton.yml (record and playback)                                                                                                                                                                     
                     playback_host: bbb.deuzem.deu.edu.tr                                                                                                                                                                                         
                 playback_protocol: http                                                                                                                                                                                                          
                            ffmpeg: 4.1.3-0york1~16.04                                                                                                                                                                                            
                                                                                                                                                                                                                                                  
/etc/bigbluebutton/nginx/sip.nginx (sip.nginx)                                                                                                                                                                                                    
                        proxy_pass: 161.9.173.12                                                                                                                                                                                                  
                                                                                                                                                                                                                                                  
/usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml (Kurento SFU)                                                                                                                                                                          
                        kurento.ip: 161.9.173.12                                                                                                                                                                                                  
                       kurento.url: ws://127.0.0.1:8888/kurento                                                                                                                                                                                   
                    localIpAddress: 161.9.173.12                                                                                                                                                                                                  
               recordScreenSharing: true                                                                                                                                                                                                          
                     recordWebcams: true                                                                                                                                                                                                          
                  codec_video_main: VP8                                                                                                                                                                                                           
               codec_video_content: VP8                                                                                                                                                                                                           
                                                                                                                                                                                                                                                  
/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml (HTML5 client)                                                                                                                                                            
                             build: 775                                                                                                                                                                                                           
                        kurentoUrl: wss://bbb.deuzem.deu.edu.tr/bbb-webrtc-sfu                                                                                                                                                                    
                  enableListenOnly: true                                                                                                                                                                                                          
                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                  
# Potential problems described below                                                                                                                                                                                                              
# Warning: API URL IPs do not match host:                                                                                                                                                                                                         
#                                                                                                                                                                                                                                                 
#                                IP from ifconfig: 161.9.173.12                                                                                                                                                                                   
#  /var/lib/tomcat7/demo/bbb_api_conf.jsp: bbb.deuzem.deu.edu.tr                                                                                                                                                                                  
                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                  
# Warning: The API demos are installed and accessible from:                                                                                                                                                                                       
#                                                                                                                                                                                                                                                 
#    https://bbb.deuzem.deu.edu.tr                                                                                                                                                                                                                
#                                                                                                                                                                                                                                                 
# and                                                                                                                                                                                                                                             
#                                                                                                                                                                                                                                                 
#    https://bbb.deuzem.deu.edu.tr/demo/demo1.jsp                                                                                                                                                                                                 
#                                                                                                                                                                                                                                                 
# These API demos allow anyone to access your server without authentication                                                                                                                                                                       
# to create/manage meetings and recordings. They are for testing purposes only.                                                                                                                                                                   
# If you are running a production system, remove them by running:                                                                                                                                                                                 
#                                                                                                                                                                                                                                                 
#    apt-get purge bbb-demo

**Comment by ahmetergul35** [comment]
I think there is a problem with the bbb-tool installed for sakai on the github. Now I'm going to compile again through the github ...

https://github.com/sakaicontrib/bbb-tool

**Comment by ahmetergul35** [comment]
Error: You must specify a meeting ID for the meeting.
👎 
same mistake...

**Comment by ffdixon** [comment]
Hmm ... just to be sure, does the version you have include the following commit?

  https://github.com/sakaicontrib/bbb-tool/commit/9e585cdc827213cbee700ab2b454b0ba81720b69

**Comment by ahmetergul35** [comment]
The baseBBBAPI.java file in sakai is as follows;
![image](https://user-images.githubusercontent.com/10403168/70207952-4e296100-173d-11ea-8793-04591620e02a.png)

**Comment by ahmetergul35** [comment]
What should I do?

**Comment by ffdixon** [comment]
We need to investigate further on our end why this is not working in `19-SNAPSHOT`.

**Comment by ahmetergul35** [comment]
Today I noticed the difference! It works fine when I recompile it under bbb-tool folder in Sakai and make cathalina.start. But after a while it gives this error again.

**Comment by ffdixon** [comment]
Interesting!  Do you see any error thrown in the `catalina.out` log for tomcat when you see the error on the client?

**Comment by ahmetergul35** [comment]
I'il share this with you.

**Comment by GhaziTriki** [comment]
Outdated issue.
