### ISSUE TITLE
alignments displays problems in iOS

### ISSUE THREAD

**Issue by daminebenz** [bigbluebutton/bigbluebutton#8364]
**who's talking indicator name padding problem**
![image](https://user-images.githubusercontent.com/33185490/69554731-fd697980-0f80-11ea-9e06-505ddd564103.png)

**share webcam button margin-right over scaling problem**
![image](https://user-images.githubusercontent.com/33185490/69554747-01959700-0f81-11ea-9308-eff912e580dd.png)

**Comment by ffdixon** [comment]
Is this an issue also in 2.3-dev?

**Comment by pedrobmarin** [comment]
@daminebenq can we close this one?

**Comment by daminebenq** [comment]
This is not anymore reproducible.
