### ISSUE TITLE
Audio appears connected after a refresh

### ISSUE THREAD

**Issue by capilkey** [bigbluebutton/bigbluebutton#8365]
If you join audio and reload the page the UI will show you as in the audio even though you aren't.
![AudioReconnect-1](https://user-images.githubusercontent.com/1395090/69565899-deb8b200-0f83-11ea-9ba8-b981f26ea5ca.gif)

You can then join the audio and overwrite the previous voice user.
![AudioReconnect-2](https://user-images.githubusercontent.com/1395090/69565909-e2e4cf80-0f83-11ea-91a0-25022d595165.gif)

If you leave the audio a voice-only user with your name will show up 1-40s later from the first connection because akka-fsesl re-syncs the voice users in the conference.
![AudioReconnect-3](https://user-images.githubusercontent.com/1395090/69565916-e5dfc000-0f83-11ea-8755-f3692f5da839.gif)

Or if it re-syncs and you haven't left the audio.
![AudioReconnect-4](https://user-images.githubusercontent.com/1395090/69565923-eaa47400-0f83-11ea-929b-46eb10b2a5ac.gif)

You can kick the voice-only user to force FreeSWTICH to clear it up or wait 5 minutes for FS to recognize a media timeout and end the call on its own.

```
0409167b-f97c-4ce7-a350-44aa8929b0e2 2019-11-25 09:20:29.308126 [DEBUG] switch_core_codec.c:223 sofia/external/w_xns5knlbsbkq_187-bbbID-Chad@chad22.blindside-dev.com Push codec L16:100
0409167b-f97c-4ce7-a350-44aa8929b0e2 2019-11-25 09:20:29.327686 [DEBUG] conference_loop.c:1338 Setup timer soft success interval: 20  samples: 960 from codec opus
0409167b-f97c-4ce7-a350-44aa8929b0e2 2019-11-25 09:21:00.827833 [ERR] switch_rtp.c:845 No audio stun for a long time!
0409167b-f97c-4ce7-a350-44aa8929b0e2 2019-11-25 09:21:31.148169 [ERR] switch_rtp.c:845 No audio stun for a long time!
0409167b-f97c-4ce7-a350-44aa8929b0e2 2019-11-25 09:22:01.507915 [ERR] switch_rtp.c:845 No audio stun for a long time!
0409167b-f97c-4ce7-a350-44aa8929b0e2 2019-11-25 09:22:31.827925 [ERR] switch_rtp.c:845 No audio stun for a long time!
0409167b-f97c-4ce7-a350-44aa8929b0e2 2019-11-25 09:23:02.147755 [ERR] switch_rtp.c:845 No audio stun for a long time!
0409167b-f97c-4ce7-a350-44aa8929b0e2 2019-11-25 09:23:32.488185 [ERR] switch_rtp.c:845 No audio stun for a long time!
0409167b-f97c-4ce7-a350-44aa8929b0e2 2019-11-25 09:24:02.848160 [ERR] switch_rtp.c:845 No audio stun for a long time!
0409167b-f97c-4ce7-a350-44aa8929b0e2 2019-11-25 09:24:33.287788 [ERR] switch_rtp.c:845 No audio stun for a long time!
0409167b-f97c-4ce7-a350-44aa8929b0e2 2019-11-25 09:25:03.647941 [ERR] switch_rtp.c:845 No audio stun for a long time!
0409167b-f97c-4ce7-a350-44aa8929b0e2 2019-11-25 09:25:30.768243 [NOTICE] switch_core_media.c:2930 Hangup sofia/external/w_xns5knlbsbkq_187-bbbID-Chad@chad22.blindside-dev.com [CS_EXECUTE] [MEDIA_TIMEOUT]
0409167b-f97c-4ce7-a350-44aa8929b0e2 2019-11-25 09:25:30.768243 [INFO] conference_loop.c:1665 Channel leaving conference, cause: MEDIA_TIMEOUT
0409167b-f97c-4ce7-a350-44aa8929b0e2 2019-11-25 09:25:30.768243 [DEBUG] mod_conference.c:2501 sofia/external/w_xns5knlbsbkq_187-bbbID-Chad@chad22.blindside-dev.com skip receive message [UNBRIDGE] (channel is hungup already)

```

**Comment by capilkey** [comment]
I'm not quite sure what we can do about the problem, but it might mean just lowering the media timeout so that it triggers quicker.

**Comment by pedrobmarin** [comment]
@mariogasparoni is this still an issue?

**Comment by mariogasparoni** [comment]
@pedrobmarin not in normal conditions. We gracefully close the connection before the page  refresh/close, and also there's a server side check that kicks ghost users from freeswitch. We can close this one.
