### ISSUE TITLE
Ability to set static pin/voicebridge per conference room

### ISSUE THREAD

**Issue by MedicMomcilo** [bigbluebutton/bigbluebutton#8371]
We have different meeting rooms in our setup via HTML5 client (not API).
What we would like to do is lock down few of them to have a specific PIN number for joining.

We are aware that those are created dynamically at this moment, so this might be feature request.

If, on the other hand, it is already possible to do so, please let me know how to do it.

**Comment by capilkey** [comment]
All BigBlueButton meetings are created by using the API. Something like this is much better suited to be handled by whatever front-end system you are using. Are you using an LMS, Greenlight, or something else to start your meetings?

**Comment by Radnik** [comment]
@capilkey 
we are uisng Greenlight

**Comment by wolmeh** [comment]
Is there a working solution to set a static PIN/voicebridge per conference room via greenlight frontend? I did not find a feature request and this issue is still open.

**Comment by matiasilva** [comment]
This is a front-end issue. Closing.
