### ISSUE TITLE
BBB can't recording !

### ISSUE THREAD

**Issue by bcalbatros** [bigbluebutton/bigbluebutton#8377]
Hi, I record meeting but it's give an error, can't record my session. Can you help me?

![bbb-hata](https://user-images.githubusercontent.com/12069482/69859106-8c89d080-12a4-11ea-9e4e-d92b35c0e664.png)

`1 timers listed.
--
● bbb-rap-archive-worker.service - BigBlueButton recording and playback archive worker
   Loaded: loaded (/usr/lib/systemd/system/bbb-rap-archive-worker.service; static; vendor preset: enabled)
   Active: inactive (dead) since Fri 2019-11-29 09:24:42 UTC; 19s ago
  Process: 17676 ExecStart=/usr/local/bigbluebutton/core/scripts/rap-archive-worker.rb (code=exited, status=0/SUCCESS)
 Main PID: 17676 (code=exited, status=0/SUCCESS)

Nov 29 09:24:40 BBB systemd[1]: Started BigBlueButton recording and playback archive worker.

● bbb-rap-sanity-worker.service - BigBlueButton recording and playback sanity check worker
   Loaded: loaded (/usr/lib/systemd/system/bbb-rap-sanity-worker.service; static; vendor preset: enabled)
   Active: inactive (dead) since Fri 2019-11-29 08:44:48 UTC; 40min ago
Condition: start condition failed at Fri 2019-11-29 09:24:40 UTC; 20s ago
           ConditionPathExistsGlob=/var/bigbluebutton/recording/status/archived/*.done was not met
  Process: 14694 ExecStart=/usr/local/bigbluebutton/core/scripts/rap-sanity-worker.rb (code=exited, status=0/SUCCESS)
 Main PID: 14694 (code=exited, status=0/SUCCESS)

Nov 29 08:44:47 BBB systemd[1]: Started BigBlueButton recording and playback sanity check worker.

● bbb-rap-process-worker.service - BigBlueButton recording and playback process worker
   Loaded: loaded (/usr/lib/systemd/system/bbb-rap-process-worker.service; static; vendor preset: enabled)
   Active: inactive (dead) since Fri 2019-11-29 08:46:15 UTC; 38min ago
Condition: start condition failed at Fri 2019-11-29 09:24:40 UTC; 20s ago
           ConditionPathExistsGlob=/var/bigbluebutton/recording/status/sanity/*.done was not met
  Process: 14852 ExecStart=/usr/local/bigbluebutton/core/scripts/rap-process-worker.rb (code=exited, status=0/SUCCESS)
 Main PID: 14852 (code=exited, status=0/SUCCESS)

Nov 29 08:45:27 BBB systemd[1]: Started BigBlueButton recording and playback process worker.

● bbb-rap-publish-worker.service - BigBlueButton recording and playback publish worker
   Loaded: loaded (/usr/lib/systemd/system/bbb-rap-publish-worker.service; static; vendor preset: enabled)
   Active: inactive (dead) since Fri 2019-11-29 08:46:43 UTC; 38min ago
Condition: start condition failed at Fri 2019-11-29 09:24:40 UTC; 20s ago
           ConditionPathExistsGlob=/var/bigbluebutton/recording/status/processed/*.done was not met
  Process: 15295 ExecStart=/usr/local/bigbluebutton/core/scripts/rap-publish-worker.rb (code=exited, status=0/SUCCESS)

`

**Comment by ffdixon** [comment]
The recording processed -- you can see `presentation` in the Published column.

> Condition: start condition failed at Fri 2019-11-29 09:24:40 UTC; 20s ago

The "errors" are not errors.  Each of the scripts run -- archive, sanity, process, and publish -- run every 30 seconds.  Every second `systemd` is checking to see if it's time to run the script.  A "start condition failed" really means that `systemd` hasn't reached the next 30 second interval for the script.

**Comment by bcalbatros** [comment]
I understand, thank you. But once it's done, I saw "getRecordings" with api but there is not any recordings. Response is:

`<response>
<returncode>SUCCESS</returncode>
<recordings/>
<messageKey>noRecordings</messageKey>
<message>There are no recordings for the meeting(s).</message>
</response>`

But I can see bbb-record --list my recording

**Comment by bcalbatros** [comment]
> The recording processed -- you can see `presentation` in the Published column.
> 
> > Condition: start condition failed at Fri 2019-11-29 09:24:40 UTC; 20s ago
> 
> The "errors" are not errors. Each of the scripts run -- archive, sanity, process, and publish -- run every 30 seconds. Every second `systemd` is checking to see if it's time to run the script. A "start condition failed" really means that `systemd` hasn't reached the next 30 second interval for the script.

I understand, thank you. But once it's done, I saw "getRecordings" with api but there is not any recordings. Response is:

<response> <returncode>SUCCESS</returncode> <recordings/> <messageKey>noRecordings</messageKey> <message>There are no recordings for the meeting(s).</message> </response>

But I can see bbb-record --list my recording

**Comment by ffdixon** [comment]
Are you calling `getRecordings` with the same `meetingID` that you used to create the meeting?

**Comment by bcalbatros** [comment]
> Are you calling `getRecordings` with the same `meetingID` that you used to create the meeting?

Yes, I use API Mate for testing.

![ker](https://user-images.githubusercontent.com/12069482/69865847-73d4e700-12b3-11ea-861e-6a2607171eaa.png)

**Comment by ffdixon** [comment]
Blank out the `recordID` and do `getRecordings` again -- do you see your recording?

**Comment by bcalbatros** [comment]
oow, yeah. They came. Thank you so much ♥
