### ISSUE TITLE
Split DNS config issue

### ISSUE THREAD

**Issue by vince62s** [bigbluebutton/bigbluebutton#8380]
Hi,
I am trying to have bbb working in a split DNS config scenario with no success.

If I use a config where sip.nginx contains proxy_pass: EXTERNAL_IP and external.xml contains wss-binding: EXTERNAL_IP:7443 then it works fine for external users but LAN user get a 1007 error.

If I use a config where I set the local IP instead of the EXTERNAL_IP above, it works fine for internal user but of course not for external users.

I am a bit confused by how it should be set when for external users my FQDN = external_ip and for internal LAN users FQDN = local_ip

Thanks.

NB: doc says to open 80/443 + UDP 16384-32768, but ain some other pages it also says to pen 7443, not sure for this last one, because even when closed it works in my sceanrio 1 above, with wss-binding: EXTERNAL_IP:7443, so not really sure about this parameter.

**Comment by ffdixon** [comment]
For internal users, are they able to access your BigBlueButton server using the external hostname?  

When configuring FreeSWITCH, it can only listen to one IP address (which needs to be the external IP address of the firewall).

> but ain some other pages it also says to pen 7443, not sure for this last one, because even when closed it works in my sceanrio 1 above, with wss-binding: EXTERNAL_IP:7443

I think you are right.  Did you set the dummy NIC to loopback the external IP to the local IP?
