### ISSUE TITLE
API/Create not found

### ISSUE THREAD

**Issue by besingamkb** [bigbluebutton/bigbluebutton#8381]
Hi I have a successfull installation of bigbluebutton on a fresh ubuntu 16.04 but when I tried to make an API request I got this error as a result.

```
<html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx/1.10.3 (Ubuntu)</center>
</body>
</html>
```

and on my logs (`/var/log/nginx/error.log`) I got this
```
2019/12/02 13:26:24 [error] 13875#13875: *105 open() "/var/www/bigbluebutton-default/api/create" failed (2: No such file or directory), client: 103.95.148.158, server: bbb.learnicus.online, request: "GET /api/create?name=BigBlueButton+API+Meeting&meetingID=bbb-meeting-uid-65&record=false&autoStartRecording=false&allowStartStopRecording=false&webcamsOnlyForModerator=false&lockSettingsDisableCam=false&lockSettingsDisableMic=false&lockSettingsDisablePrivateChat=false&lockSettingsDisablePublicChat=false&lockSettingsDisableNote=false&lockSettingsHideUserList=false&lockSettingsLockedLayout=false&lockSettingsLockOnJoin=true&lockSettingsLockOnJoinConfigurable=false&checksum=cf0a40b6bc76400ab181daf349064637c7150c6d HTTP/1.1", host: "bbb.learnicus.online"
2019/12/02 13:36:16 [error] 13875#13875: *107 "/var/www/bigbluebutton-default/api/index.html" is not found (2: No such file or directory), client: 103.95.148.158, server: bbb.learnicus.online, request: "GET /api/ HTTP/1.1", host: "bbb.learnicus.online"

```

**Comment by ffdixon** [comment]
Can you take a look at these steps for troubleshooting an installation

  http://docs.bigbluebutton.org/2.2/troubleshooting.html#help-installing-bigbluebutton

and let us know if you still have problems after going through above.  If you need more help, let us know

What version of BigBlueButton are you installing/running?
Did you get any errors during the install?
What installation method did you follow?
Did the problem appear after initial install, after an upgrade, or after running BigBlueButton for a while?
Did you make any changes to BigBlueButton outside of using bbb-conf or the bbb-install.sh script?
Are you running BigBlueButton within a development environment?
Post the output of sudo bbb-conf --check

**Comment by besingamkb** [comment]
i didn't notice your response. sorry for the late reply. I am able to fix the issue  while following a lot of stuff on the docs.

**Comment by abdelaziz-97** [comment]
> i didn't notice your response. sorry for the late reply. I am able to fix the issue while following a lot of stuff on the docs.

I have the same probleme but i didn't find any solution that works could you do you have any idea that can help me
