### ISSUE TITLE
Big Blue Button recording does not record audio

### ISSUE THREAD

**Issue by pclinkitalia** [bigbluebutton/bigbluebutton#8384]
Good morning, I have a problem with the audio on the recording meeting, everithing was working perfetcly until last week when I installed the last update.
Now when I record my meeting, the recording is published well but without sound. someone can helpme to find the reason of that problem?
Thank a lot.
I show below the result of bbb-conf --check for your analysis

BigBlueButton Server 2.2.0-rc-2 (1588)
                    Kernel version: 4.4.0-167-generic
                      Distribution: Ubuntu 16.04.6 LTS (64-bit)
                            Memory: 7646 MB
                         CPU cores: 4

/usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties (bbb-web)
       bigbluebutton.web.serverURL: https://aulesaf.pclinkitalia.com
                defaultGuestPolicy: ALWAYS_ACCEPT
                 svgImagesRequired: true

/etc/nginx/sites-available/bigbluebutton (nginx)
                       server name: aulesaf.pclinkitalia.com
                              port: 80, [::]:80
                              port: 443 ssl
                    bbb-client dir: /var/www/bigbluebutton

/var/www/bigbluebutton/client/conf/config.xml (bbb-client)
                Port test (tunnel): rtmp://aulesaf.pclinkitalia.com
                              red5: aulesaf.pclinkitalia.com
              useWebrtcIfAvailable: true

/opt/freeswitch/etc/freeswitch/vars.xml (FreeSWITCH)
                       local_ip_v4: 95.110.225.92
                   external_rtp_ip: 95.110.225.92
                   external_sip_ip: 95.110.225.92

/opt/freeswitch/etc/freeswitch/sip_profiles/external.xml (FreeSWITCH)
                        ext-rtp-ip: $${external_rtp_ip}
                        ext-sip-ip: $${external_sip_ip}
                        ws-binding: :5066
                       wss-binding: :7443

/var/www/bigbluebutton/check/conf/config.xml (client check)
                      client check: aulesaf.pclinkitalia.com

/usr/local/bigbluebutton/core/scripts/bigbluebutton.yml (record and playback)
                     playback_host: aulesaf.pclinkitalia.com
                 playback_protocol: https
                            ffmpeg: 4.1.3-0york1~16.04

/etc/bigbluebutton/nginx/sip.nginx (sip.nginx)
                        proxy_pass: 95.110.225.92

/usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml (Kurento SFU)
                        kurento.ip: 95.110.225.92
                       kurento.url: ws://127.0.0.1:8888/kurento
                    localIpAddress: 95.110.225.92
               recordScreenSharing: true
                     recordWebcams: true
                  codec_video_main: VP8
               codec_video_content: VP8

/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml (HTML5 client)
                             build: 798
                        kurentoUrl: wss://aulesaf.pclinkitalia.com/bbb-webrtc-sfu
                  enableListenOnly: true

# Potential problems described below
# Warning: API URL IPs do not match host:
#
#                                IP from ifconfig: 95.110.225.92
#  /var/lib/tomcat7/demo/bbb_api_conf.jsp: aulesaf.pclinkitalia.com

# Warning: The API demos are installed and accessible from:
#
#    https://aulesaf.pclinkitalia.com
#
# and
#
#    https://aulesaf.pclinkitalia.com/demo/demo1.jsp
#
# These API demos allow anyone to access your server without authentication
# to create/manage meetings and recordings. They are for testing purposes only.
# If you are running a production system, remove them by running:
#
#    apt-get purge bbb-demo

# Warning: The client self check is installed and accessible from:
#
#    https://aulesaf.pclinkitalia.com/check
#

**Comment by ffdixon** [comment]
> Good morning, I have a problem with the audio on the recording meeting, everithing was working perfetcly until last week when I installed the last update.

What steps did you do to install the update ([step-by-step](http://docs.bigbluebutton.org/2.2/install.html#upgrading) or [bbb-install.sh](https://github.com/bigbluebutton/bbb-install))?

**Comment by ffdixon** [comment]
Also, can you check that there is an audio file written to `/var/freeswitch/meetings` when you join a recorded meeting.

Next, check the processing scripts to see if there is an error processing the recordings, see

  http://docs.bigbluebutton.org/dev/recording.html#troubleshooting

**Comment by pclinkitalia** [comment]
I did the installation by bbb-install.sh,  I saw that there are some files stored in /var/freeswitch/meetings but thats file are only refered to 27 November, the recording that I made yesterday and today are not there.
I Follow the instruction suggested and from the iformation of bbb-recording --watch seems that bigbluebutton does not recording audio. What can I change or verify? thanks

Every 2,0s: bbb-record --list-recent                                                                                                          Tue Dec  3 14:24:17 2019

Internal MeetingID                                               Time                APVD APVDE RAS Slides Processed            Published           External MeetingID
------------------------------------------------------  ---------------------------- ---- ----- --- ------ -------------------- ------------------  ------------------
-
988993c6257165f10ec30294c67767f59183269f-1575376404831  mar 3 dic 2019, 13.33.24, CET  X                 52
6e35e3b2778883f5db637d7a5dba0a427f692e91-1575375487428  mar 3 dic 2019, 13.18.07, CET  X    XX X          1                      presentation        English 101
6e35e3b2778883f5db637d7a5dba0a427f692e91-1575368503345  mar 3 dic 2019, 11.21.43, CET  X    XX X          1                      presentation        English 101
d2659660e0e2de2945dbbf8987e32d78e01d03f3-1575367566321  mar 3 dic 2019, 11.06.06, CET  X    XX X          1                      presentation        f0103ab5224eea5b5
8208669658d9bc16d8df685
5c95c4dc71dc88d29c9e8689ba7d8831fba0f13b-1575366681937  mar 3 dic 2019, 10.51.21, CET  X    XX X          1                      presentation        bb223ac9b3574d3ab
a32d2e6aa0f314567b4d16f
6d01857ff531ea190c17e367477ce927e63f49bf-1575363504645  mar 3 dic 2019, 09.58.24, CET  X    XX X          1                                          81b8b4d3be2468817
4364bf024b188621293e480
3d6b571c5401e384dd85f58349f1e2be8f2d3c7c-1575363471728  mar 3 dic 2019, 09.57.51, CET  X    XX X          1                                          b64dc3c90d159198b
6fb4a399345795ce38dadeb
da83604a8125fed30a896a32076ee89ae5d23714-1575361301039  mar 3 dic 2019, 09.21.41, CET  X    XX X          1                      presentation        4cbb795fd158f773d
c330bcda79e80e0c909be17
b9988cd8af7fbf449703624552e7eaf63683aec8-1575360702676  mar 3 dic 2019, 09.11.42, CET  X    XX X          1                                          d1635d27c074256e3
e5c686ad6b327d6984437f2
ac4c7994a109ed3da75f7a0331d0a941f0e797bc-1575360667732  mar 3 dic 2019, 09.11.07, CET  X    XX X          1                                          532119a0b6febbdcf
b42484b59749990c9734d9e
988993c6257165f10ec30294c67767f59183269f-1575359788490  mar 3 dic 2019, 08.56.28, CET  X    XX X          1                                          c071601aebf99dac6
fe93cac8678e386ad5372c8

--

**Comment by ffdixon** [comment]
What is the output of the command

~~~
ls -al /var/freeswitch/meetings
~~~

**Comment by pclinkitalia** [comment]
root@ubuntu:/# ls -al /var/freeswitch/meetings
totale 5019672
drwxr-xr-x 2 freeswitch freeswitch     20480 dic  3 13:59 .
drwxr-xr-x 3 freeswitch daemon          4096 nov  5 10:18 ..
-rw-r--r-- 1 freeswitch freeswitch 387536784 nov 27 19:03 0754a731c2395f19e9bd0cc4097130e228f2d9bc-1574873776286-505506818.wav
-rw-r--r-- 1 root       root             113 dic  3 14:03 1
-rw-r--r-- 1 freeswitch freeswitch 336781584 nov 27 18:55 27f2f70872924273318f7c41fab391f8095d0391-1574873834234-505562854.wav
-rw-r--r-- 1 freeswitch freeswitch 327640464 nov 27 08:55 383a35c0388ab277af7726ed16f115709cef480d-1574837883740-469615539.wav
-rw-r--r-- 1 freeswitch freeswitch 348199824 nov 27 20:16 3dcb985fb946cd32ce301b705dd6a0446571fe5a-1574878553559-510294190.wav
-rw-r--r-- 1 freeswitch freeswitch 320444304 nov 27 21:23 44bf6a109412a0df13f7412f1475000216c7a105-1574882884744-514614207.wav
-rw-r--r-- 1 freeswitch freeswitch   3680784 nov 27 17:07 49d8cf23da8f592f0ecc9f2caa3cebd15e71e883-1574870799186-502543111.wav
-rw-r--r-- 1 freeswitch freeswitch 597867024 nov 27 19:34 49d8cf23da8f592f0ecc9f2caa3cebd15e71e883-1574873374333-505143366.wav
-rw-r--r-- 1 freeswitch freeswitch 339175824 nov 27 22:25 6e7bd5ea4310c7f25f62b6ea727229a923f815c6-1574886364906-518099220.wav
-rw-r--r-- 1 freeswitch freeswitch 412245264 nov 27 19:01 8cf2d3ed519d5c8f6aaa6adf3935764a931a056f-1574873391714-505119234.wav
-rw-r--r-- 1 freeswitch freeswitch 425810064 nov 27 20:33 8d7b021f24c6373d026497ef65b8db8cce31c054-1574878767223-510519081.wav
-rw-r--r-- 1 freeswitch freeswitch 318823824 nov 27 18:59 8fddf23472885bc5c68f6c08766fef4d26ed78ae-1574874251720-505990961.wav
-rw-r--r-- 1 freeswitch freeswitch 325315344 nov 27 19:55 9d8815544fb18126848944ebc1c01d33b762e9a3-1574877522640-509257025.wav
-rw-r--r-- 1 freeswitch freeswitch 349826064 nov 27 20:03 a1eb24a31d81e1330337eaade2fcf328d25c9e4d-1574877776662-509504886.wav
-rw-r--r-- 1 freeswitch freeswitch 320499984 nov 27 18:51 a3cdec3e377fefe5e6b5a44d9cddea9695f9d8cd-1574873724923-505465299.wav
-rw-r--r-- 1 freeswitch freeswitch 326173584 nov 27 19:51 bc7a453e91fa1a8310d7c22f09106be69ee008cd-1574877302728-509034500.wav
-rw-r--r-- 1 freeswitch freeswitch        48 ott 21 23:28 readme.txt

**Comment by ffdixon** [comment]
Are you free to chat directly for a few minutes?  Can you send me an e-mail to ffdixon .at. bigbluebutton .dot. org.

**Comment by pclinkitalia** [comment]
sure I'am available



Il giorno mar 3 dic 2019 alle ore 15:12 Fred Dixon <notifications@github.com>
ha scritto:

**Comment by ffdixon** [comment]
OK, thanks for the closer look.  You had originally installed BigBlueButton using `bbb-install.sh`, but your recent upgrade was done manually.

For some reason, you had an old version of FreeSWITCH installed.  After doing the steps here

   http://docs.bigbluebutton.org/2.2/install.html#upgrading-from-bigbluebutton-22

FreeSWITCH upgraded to the correct version and the recordings now have audio.

**Comment by jkfreij** [comment]
Good morning, I have a problem with the audio on the recording meeting, we installed BigBlueButton Server 2.2.0 (1773) by bbb-install.sh 
Now when I record my meeting, the recording is published well only with whiteboard. someone can help to find the reason of that problem?
There is can no audio file written to /var/freeswitch/meetings when you join a recorded meeting

Thank a lot.
