### ISSUE TITLE
Audio ok / cam and screen sharing not ok

### ISSUE THREAD

**Issue by vince62s** [bigbluebutton/bigbluebutton#8385]
here is the bbb-conf check:

```
BigBlueButton Server 2.2.0-rc-2 (1613)
                    Kernel version: 4.15.0-70-generic
                      Distribution: Ubuntu 16.04.6 LTS (64-bit)
                            Memory: 8157 MB
                         CPU cores: 4
/usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties (bbb-web)
       bigbluebutton.web.serverURL: https://bbb.mydomain.com
                defaultGuestPolicy: ALWAYS_ACCEPT
                 svgImagesRequired: true
/etc/nginx/sites-available/bigbluebutton (nginx)
                       server name: bbb.mydomain.com
                              port: 80, [::]:80
                              port: 443 ssl
                    bbb-client dir: /var/www/bigbluebutton
/var/www/bigbluebutton/client/conf/config.xml (bbb-client)
                Port test (tunnel): rtmp://bbb.mydomain.com
                              red5: bbb.mydomain.com
              useWebrtcIfAvailable: true
/opt/freeswitch/etc/freeswitch/vars.xml (FreeSWITCH)
                       local_ip_v4: LOCAL_IP
                   external_rtp_ip: EXTERNAL_IP
                   external_sip_ip: EXTERNAL_IP
/opt/freeswitch/etc/freeswitch/sip_profiles/external.xml (FreeSWITCH)
                        ext-rtp-ip: $${external_rtp_ip}
                        ext-sip-ip: $${external_sip_ip}
                        ws-binding: :5066
                       wss-binding: EXTERNAL_IP:7443
/usr/local/bigbluebutton/core/scripts/bigbluebutton.yml (record and playback)
                     playback_host: bbb.mydomain.com
                 playback_protocol: https
                            ffmpeg: 4.1.3-0york1~16.04
/etc/bigbluebutton/nginx/sip.nginx (sip.nginx)
                        proxy_pass: EXTERNAL_IP
/usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml (Kurento SFU)
                        kurento.ip: EXTERNAL_IP
                       kurento.url: ws://127.0.0.1:8888/kurento
                    localIpAddress: LOCAL_IP
               recordScreenSharing: true
                     recordWebcams: true
                  codec_video_main: VP8
               codec_video_content: VP8
/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml (HTML5 client)
                             build: 798
                        kurentoUrl: wss://bbb.mydomain.com/bbb-webrtc-sfu
                  enableListenOnly: true

 Potential problems described below
 IP does not match:
                           IP from ifconfig: LOCAL_IP
   /etc/nginx/sites-available/bigbluebutton: bbb.mydomain.com
 Warning: The setting of EXTERNAL_IP for proxy_pass in

    /etc/bigbluebutton/nginx/sip.nginx

 does not match the local IP address (LOCAL_IP).
 (This is OK if you've manually changed the values)
```

ip addr shows also the EXTERNAL_IP

Coonection to the bbb test envrionment works fine (webcam included)
On my configuration, up to audio everything is fine, but when activating the webcam I get a 1020 error.

I have tried 2 different STUN server in the /etc/kurento/modules/kurento/WebRtcEndpoint.conf.ini file

**Comment by vince62s** [comment]
UPDATE: if I open TCP 16384-32768 then it works fine .....
same as here https://github.com/bigbluebutton/bigbluebutton/issues/8048
But I know it should not be the case (to open TCP ports ....)

**Comment by capilkey** [comment]
The last few comments from @prlanzarin in #8048 explain it. The fact that it needs TCP candidates to work points to there being an issue with the UDP connections because UDP should be all that's needed. 

It is somewhat strange that audio works fine though. I would expect both to be failing.

**Comment by vince62s** [comment]
But I don't have a TURN server set up, just the stun config as mentioned above.

**Comment by vince62s** [comment]
in firefox about:webrtc I am getting this when activating the webcam
local_ip = my computer internal IP address
bbb_ext_ip = bbb server external IP
bbb_local_ip = bbb internal IP

État ICE | Nommé | Sélectionné | Candidat local | Candidat distant | ID du composant | Priorité | Octets envoyés | Octets reçus
-- | -- | -- | -- | -- | -- | -- | -- | --
failed | false | false | local_ip:55192/udp(host) [non-proxied] | 172.18.0.1:24815/udp(host) | 1 | 8646913470639243000 | 0 | 0
failed | false | false | local_ip:55192/udp(host) [non-proxied] | bbb_local_ip:25951/udp(host) | 1 | 8646913466344276000 | 0 | 0
failed | false | false | local_ip:55192/udp(host) [non-proxied] | bbb_local_ip:25951/udp(host) | 1 | 8646913466344276000 | 0 | 0
failed | false | false | local_ip:55192/udp(host) [non-proxied] | bbb_ext_ip:3838/udp(srflx) | 1 | 7205761602765586000 | 0 | 0
failed | false | false | local_ip:55192/udp(host) [non-proxied] | bbb_ext_ip:18560/udp(srflx) | 1 | 7205761598470619000 | 0 | 0
failed | false | false | local_ip:61877/tcp(host) [non-proxied] | bbb_local_ip:32340/tcp(host) | 1 | 4341475538259378700 | 0 | 0
failed | false | false | local_ip:61877/tcp(host) [non-proxied] | 172.18.0.1:29066/tcp(host) | 1 | 4341474438747751000 | 0 | 0
failed | false | false | local_ip:61877/tcp(host) [non-proxied] | bbb_ext_ip:32340/tcp(srflx) | 1 | 3620899597880099300 | 0 | 0
failed | false | false | local_ip:61877/tcp(host) [non-proxied] | bbb_ext_ip:29066/tcp(srflx) | 1 | 3620898498368471600 | 0 | 0

But when activating only the audio, I am getting this:
local_ip = my computer internal IP address
ext_ip = my external ip (from my firewall)
bbb_ext_ip = bbb server external IP


État ICE | Nommé | Sélectionné | Candidat local | Candidat distant | ID du composant | Priorité | Octets envoyés | Octets reçus
-- | -- | -- | -- | -- | -- | -- | -- | --
succeeded | true | true | ext_ip:41340/udp(prflx) [non-proxied] | bbb_ext_ip:22288/udp(host) | 1 | 2830971271250431 | 53960 | 62600
inprogress | false | false | local_ip:59853/udp(host) [non-proxied] | bbb_ext_ip:22288/udp(host) | 1 | 2830971808121343 | 0 | 0

**Comment by blackie333** [comment]
Hello, I have the same problem on my server, sharing is not screen working for remote clients connected via OpenVPN client.
Have you found any solution in the meantime?
Please advice.

**Comment by miromer** [comment]
I am facing the similar issue audio is working but screen share show ICE error 1108 and webcam shows ICE error 1020. for audio about:webrtc shows external IP for "remote candidate" but for screen share and webcam it shows Local IP. Any suggestions? or directions

**Comment by miromer** [comment]
> in firefox about:webrtc I am getting this when activating the webcam
> local_ip = my computer internal IP address
> bbb_ext_ip = bbb server external IP
> bbb_local_ip = bbb internal IP
> 
> État ICE	Nommé	Sélectionné	Candidat local	Candidat distant	ID du composant	Priorité	Octets envoyés	Octets reçus
> failed	false	false	local_ip:55192/udp(host) [non-proxied]	172.18.0.1:24815/udp(host)	1	8646913470639243000	0	0
> failed	false	false	local_ip:55192/udp(host) [non-proxied]	bbb_local_ip:25951/udp(host)	1	8646913466344276000	0	0
> failed	false	false	local_ip:55192/udp(host) [non-proxied]	bbb_local_ip:25951/udp(host)	1	8646913466344276000	0	0
> failed	false	false	local_ip:55192/udp(host) [non-proxied]	bbb_ext_ip:3838/udp(srflx)	1	7205761602765586000	0	0
> failed	false	false	local_ip:55192/udp(host) [non-proxied]	bbb_ext_ip:18560/udp(srflx)	1	7205761598470619000	0	0
> failed	false	false	local_ip:61877/tcp(host) [non-proxied]	bbb_local_ip:32340/tcp(host)	1	4341475538259378700	0	0
> failed	false	false	local_ip:61877/tcp(host) [non-proxied]	172.18.0.1:29066/tcp(host)	1	4341474438747751000	0	0
> failed	false	false	local_ip:61877/tcp(host) [non-proxied]	bbb_ext_ip:32340/tcp(srflx)	1	3620899597880099300	0	0
> failed	false	false	local_ip:61877/tcp(host) [non-proxied]	bbb_ext_ip:29066/tcp(srflx)	1	3620898498368471600	0	0
> But when activating only the audio, I am getting this:
> local_ip = my computer internal IP address
> ext_ip = my external ip (from my firewall)
> bbb_ext_ip = bbb server external IP
> 
> État ICE	Nommé	Sélectionné	Candidat local	Candidat distant	ID du composant	Priorité	Octets envoyés	Octets reçus
> succeeded	true	true	ext_ip:41340/udp(prflx) [non-proxied]	bbb_ext_ip:22288/udp(host)	1	2830971271250431	53960	62600
> inprogress	false	false	local_ip:59853/udp(host) [non-proxied]	bbb_ext_ip:22288/udp(host)	1	2830971808121343	0	0

Did you had any solution?

**Comment by matiasilva** [comment]
For VPN-related issues, #8627 might help. For further support issues, please post here: https://groups.google.com/forum/#!forum/bigbluebutton-setup.
