### ISSUE TITLE
Don't prompt for echo test when joining breakout room

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#8387]
When the user already has an active microphone and wishes to join a breakout room, we can short-circuit the echo test because they user has already tested their microphone on the server.

We can also do the same when they return to the main room.

**Comment by capilkey** [comment]
The breakout room wouldn't actually know if the user had joined audio in the other meeting. The other part is that the echo test is the only way for a user to select a different input device.

**Comment by ffdixon** [comment]
This would definitely make it easier to get into a breakout room and back.  I think we have the ability to add a userdata parameter in the Join URL to skip the microphone check.  

If the user is already joined with microphone in the main room, there should be a problem joining again in the breakout room (i.e. skipping the microphone check).

**Comment by ownhardy** [comment]
+1 for this important feature request!

My usecase why this is important to change: 
When I as a moderator kick all participants into many beakout rooms, and I then want to "visit" one breakout room after another to counsel the groups individually, then this "soundcheck" (each one around 30 seconds in my case) eats up most of my couseling time for the groups. Especially in this special case (a moderator joins a breakout room) I would strongly wish that these numerous soundchecks could somehow be skipped (or better be turned off by default).
