### ISSUE TITLE
Webcam overlaps user menu

### ISSUE THREAD

**Issue by aogilvie** [bigbluebutton/bigbluebutton#8391]
- start a session
- add users with webcams until webcams fill the width of presentation area
- left click on the top user

![example](https://user-images.githubusercontent.com/970364/70105604-a6e8f300-1684-11ea-920a-459f832be357.png)

probably user menu index should just be set higher?

bbb 2.2 RC 1

**Comment by ffdixon** [comment]
Hi Ally,

We can see that it doesn't overlap on 2.2 RC-2,

![image](https://user-images.githubusercontent.com/290351/70165580-e8d46200-16a1-11ea-831c-ac2060f850b1.png)

**Comment by ffdixon** [comment]
Closing this issue -- if the problem still persists in BigBlueButton 2.2 RC2 (or later), please don't hesitate to comment again and reopen this issue.
