### ISSUE TITLE
[bbb-webhooks] You did not pass the checksum security check.

### ISSUE THREAD

**Issue by besingamkb** [bigbluebutton/bigbluebutton#8406]
Hello I want to implement webhooks on our bbb server but I cant create/register a hooks. i think it regarding the checksum security issue.

I follow this step from the bbb-webhooks docs. https://docs.bigbluebutton.org/dev/webhooks.html#hookscreate

and I came up to this URL but it seems to be not work.

`https://bbb.learnicus.online/bigbluebutton/api/hooks/create?callbackURL=https%3A%2F%2Fbbb-angelfish.requestcatcher.com&checksum=ea1bc9d5e69c0d8abe8afcf4421e4d665712700b`

here is some of my code generating checksum please correct me if Im wrong

```php
$cb = urlencode("https://bbb-angelfish.requestcatcher.com");
$join_parameters = "callbackURL=".$cb;
$chcksm = sha1("create".$join_parameters.env("BBB_SECRET"));
$url = $join_parameters."&checksum=".$chcksm;
// out put below
// callbackURL=https%3A%2F%2Fbbb-angelfish.requestcatcher.com&checksum=ea1bc9d5e69c0d8abe8afcf4421e4d665712700b
```

**Comment by GhaziTriki** [comment]
@besingamkb Are you trying yo use the PHP library?

**Comment by besingamkb** [comment]
@GhaziTriki yes i am using the PHP library for create meeting using the PHP api.

**Comment by GhaziTriki** [comment]
@besingamkb Could you please use the master version of https://github.com/bigbluebutton/bigbluebutton-api-php? It has the WebHooks now implemented.

**Comment by MHZarei** [comment]
The hook use another secret that defined in this file:
/usr/local/bigbluebutton/bbb-webhooks/config/default.yml

It's differ from bbb secret.
