### ISSUE TITLE
bbb-html5 failed

### ISSUE THREAD

**Issue by sergiodn** [bigbluebutton/bigbluebutton#8408]
Hi.
I have follow the install procedure of upgrading bigbluebutton from 2.0 to 2.2 rc3. But I have stucked in bbb-html5.
When I try to install bbb-html5 it says:
Setting up bbb-html5 (1:2.2.0-812) ...
Error: Must provide <filename> <path_to_update> <value>
Usage:
  yq write [yaml_file] [path] [value] [flags]
...
15:37:50 main [ERRO] Must provide <filename> <path_to_update> <value>
dpkg: error processing package bbb-html5 (--configure):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 bbb-html5
E: Sub-process /usr/bin/dpkg returned an error code (1)
.

I already uninstall bbb-html5, bigbluebutton and try bbb-install.sh. But none seems to work.
Can anyone help me, please ?
Thanks in advance.

**Comment by antobinary** [comment]
Hi @sergiodn 
Did you follow http://docs.bigbluebutton.org/2.2/install.html#upgrading-from-bigbluebutton-20 ?

In the future please ask setup related questions in the Google groups: https://groups.google.com/forum/#!forum/bigbluebutton-setup

**Comment by sergiodn** [comment]
Yes. I follow ths instructions listed in that link. Thanks

**Comment by ffdixon** [comment]
Can you edit ` /var/lib/dpkg/info/bbb-html5.postinst` and change the first line to

~~~
#!/bin/bash -ex
~~~

and then do `sudo apt-get install -f` and let us know the output from `bbb-html5.postinst`.

**Comment by sergiodn** [comment]
Hi ffdixon and thanks for you tip. Unfortunately didn't work. The output was:
Setting up bbb-html5 (1:2.2.0-812) ...
+ LANG=c
+ ifconfig
+ grep -q venet0:0
++ hostname -I
++ sed 's/ .*//g'
+ IP=94.23.45.220
+ '[' -f /etc/redhat-release ']'
+ grep -q bionic /etc/lsb-release
+ TOMCAT_SERVICE=tomcat7
+ '[' -f /var/lib/tomcat7/webapps/bigbluebutton/WEB-INF/classes/bigbluebutton.properties ']'
+ SERVLET_DIR=/usr/share/bbb-web
+ PROTOCOL=http
+ '[' -f /usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties ']'
++ cat /usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties
++ sed -n '/^bigbluebutton.web.serverURL/{s/.*\///;p}'
+ SERVER_URL=bbb.humansoft.pt
+ cat /usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties
+ grep bigbluebutton.web.serverURL
+ grep -q https
++ cat /usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties
++ grep -v '#'
++ sed -n '/^bigbluebutton.web.serverURL/{s/.*\///;p}'
+ HOST=bbb.humansoft.pt
+ '[' '!' -L /etc/nginx/sites-enabled/bigbluebutton ']'
+ cd /usr/share/meteor
+ chown -R meteor:meteor /usr/share/meteor
+ '[' -f /usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties ']'
+ sed -i 's/^svgImagesRequired=.*/svgImagesRequired=true/' /usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties
+ '[' '!' -f /.dockerenv ']'
+ systemctl restart nginx
+ cat /usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties
+ grep -q https
+ grep bigbluebutton.web.serverURL
+ PROTOCOL=http
+ sed -i 's/^ENVIRONMENT_TYPE=.*/ENVIRONMENT_TYPE=development/' /usr/share/meteor/bundle/systemd_start.sh
+ SOURCE=/tmp/settings.yml
+ TARGET=/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml
+ '[' -f /tmp/settings.yml ']'
++ cat /usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties
++ grep -v '#'
++ sed s/https/wss/g
++ sed -n '/^bigbluebutton.web.serverURL/{s/.*=//;p}'
++ sed s/http/ws/g
+ WSURL=ws://bbb.humansoft.pt
+ yq w -i /usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml public.kurento.wsUrl ws://bbb.humansoft.pt/bbb-webrtc-sfu
+ yq w -i /usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml public.kurento.enableScreensharing true
+ yq w -i /usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml public.kurento.enableVideo true
+ yq w -i /usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml public.app.listenOnlyMode true
+ yq w -i /usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml public.note.enabled true
+ yq w -i /usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml public.note.url http://bbb.humansoft.pt/pad
+ sed -i 's/proxy_pass .*/proxy_pass http:\/\/94.23.45.220:5066;/g' /etc/bigbluebutton/nginx/sip.nginx
+ sed -i 's/server_name  .*/server_name  94.23.45.220;/g' /etc/nginx/sites-available/bigbluebutton
++ cat /usr/share/etherpad-lite/APIKEY.txt
+ APIKEY=
+ yq w -i /usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml private.etherpad.apikey
Error: Must provide <filename> <path_to_update> <value>
Usage:
  yq write [yaml_file] [path] [value] [flags]

Aliases:
  write, w

Examples:

yq write things.yaml a.b.c cat
yq write --inplace things.yaml a.b.c cat
yq w -i things.yaml a.b.c cat
yq w --script update_script.yaml things.yaml
yq w -i -s update_script.yaml things.yaml
yq w --doc 2 things.yaml a.b.d[+] foo
yq w -d2 things.yaml a.b.d[+] foo


Flags:
  -d, --doc string      process document index number (0 based, * for all documents) (default "0")
  -h, --help            help for write
  -i, --inplace         update the yaml file inplace
  -s, --script string   yaml script for updating yaml

Global Flags:
  -t, --trim      trim yaml output (default true)
  -v, --verbose   verbose mode

18:14:53 main [ERRO] Must provide <filename> <path_to_update> <value>

Thank you very much for your kindness.

**Comment by sergiodn** [comment]
Hi ffdixon. I think the problem is in defining APIKEY in /usr/share/etherpad-lite/APIKEY.txt.
Do you know, how to define it ?
Thanks

**Comment by ffdixon** [comment]
Hmm, yes -- it looks like the post install script for `bbb-html5` is running before the `bbb-etherpad`.  Try installing `bbb-etherpad-lite` first

~~~
sudo apt-get install bbb-etherpad
~~~

and then try running

~~~
sudo apt-get install -f
~~~

**Comment by sergiodn** [comment]
Ok, I think I solved the problem. I define a KEY in /usr/share/etherpad-lite/APIKEY.txt (this file was empty), and then run sudo apt-get install -f.
Now all services are active and running.

Thanks
