### ISSUE TITLE
Firefox on Safari Mobile recommends Chrome or FireFox

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#8414]
iOS users need to use Safari Mobile to access BigBlueButton. However, when running FireFox on iOS it recommends the user install Chrome or FireFox.  

See #8413

**Comment by PhMemmel** [comment]
Cannot reproduce with Firefox on test23.bigbluebutton.org (2.3-beta-2, html5 client build 1552) on iPadOS 14.4.2, Firefox Daylight 33.0 (4119). No warning about having to use Safari nor installing Chrome/Firefox. Works flawlessly on Firefox. Don't know about iOS, but I think it's the same.

**Comment by mrkeksi** [comment]
On iOS 14.5 and Firefox Daylight 33, a warning comes up that an outdated version of a supported browser is being used. "Please update the browser for full support." When i switch to Desktop Mode BBB works (mini hack ;) )
Also the text is cut off:

**Comment by PhMemmel** [comment]
Confirming @mrkeksi 's experience with iOS on my iPad: Message appears when mobile view is selected, no problem with desktop view.

**Comment by winie** [comment]
Firefox and Chrome are not working with BBB 2.3
Firefox:
<img width="568" alt="2021-04-09 10-43-10-1" src="https://user-images.githubusercontent.com/12683936/114157878-678b8000-9924-11eb-8007-8b3233b4aa17.png">
Chrome:
![IMG_0068](https://user-images.githubusercontent.com/12683936/114157899-6d816100-9924-11eb-8e26-debc138eed48.PNG)

Safari works fine.

Device: iPhone 5s (iOS 12.5.2)
Firefox: Daylight 33.0 (4119)
Chrome: 87.0.4280.163
BBB: Clientversion 1552

**Comment by pedrobmarin** [comment]
@antobinary do we recommend using something different from Safari in iOS devices?

**Comment by pedrobmarin** [comment]
@winie does that first message (from Firefox) stands for "please update your browser" or something like that? Because I believe that's the problem over here. Firefox should get the same message from Chrome and recommend using Safari.

**Comment by antobinary** [comment]
>@antobinary do we recommend using something different from Safari in iOS devices?

Afaik we still recommend only Safari on iOS devices.

@winie what version of FireFox is this (and is it FireFox, FireFox mobile , nightly, wrapper around FireFox or...?) 
Please also show what you get when you visit https://test23.bigbluebutton.org/html5client/useragent  <- grabbing the user agent

**Comment by pedrobmarin** [comment]
We fixed something like this at our end. The problem is that https://github.com/bigbluebutton/bigbluebutton/blob/ced8c35f2ed30bfff284a2a1282cc41ef60d157b/bigbluebutton-html5/imports/ui/components/legacy/component.jsx#L157-L160 only checks Chrome in iOS.

**Comment by pedrobmarin** [comment]
And https://github.com/bigbluebutton/bigbluebutton/blob/ced8c35f2ed30bfff284a2a1282cc41ef60d157b/bigbluebutton-html5/public/locales/en.json#L790 should have a different tag because this message is valid for any browser besides Safari in ios

**Comment by antobinary** [comment]
@pedrobmarin Is this something we could merge upstream?

**Comment by pedrobmarin** [comment]
I think is easier just to do it from scratch over v2.3. The locales tag change is the hard part of it.

**Comment by mrkeksi** [comment]
> @winie does that first message (from Firefox) stands for "please update your browser" or something like that? Because I believe that's the problem over here. Firefox should get the same message from Chrome and recommend using Safari.

yes it says something like: outdated supported browser, please update.  and when you turn on the desktop mode in Firefox, bbb works.

**Comment by pedrobmarin** [comment]
Besides the browser detection, someone has to take a look on that interface problem @mrkeksi reported.

**Comment by winie** [comment]
> @winie does that first message (from Firefox) stands for "please update your browser" or something like that? Because I believe that's the problem over here. Firefox should get the same message from Chrome and recommend using Safari.

@pedrobmarin I use the latest firefox from the app store.

> > @antobinary do we recommend using something different from Safari in iOS devices?
> 
> Afaik we still recommend only Safari on iOS devices.
> 
> @winie what version of FireFox is this (and is it FireFox, FireFox mobile , nightly, wrapper around FireFox or...?)
> Please also show what you get when you visit https://test23.bigbluebutton.org/html5client/useragent <- grabbing the user agent

@antobinary
user agent: Firefox iOS 33.0.0 / iOS 12.5.2
I use this variant of firefox: https://apps.apple.com/de/app/internet-browser-firefox/id989804926

**Comment by Kalimeiro** [comment]
Firefox iOS 33.1.0 / iOS 14.5.0
Bug still occur.
