### ISSUE TITLE
Improve Presentation Upload Language when checks fail.

### ISSUE THREAD

**Issue by akiwenziec** [bigbluebutton/bigbluebutton#8416]
The client does not tell the user what to do to improve their experience when the upload fails due to content restrictions. 

![Screen Shot 2019-12-11 at 2 44 35 PM](https://user-images.githubusercontent.com/18176998/70658139-601e6e80-1c2b-11ea-8c69-a49390a1393d.png)

"please try optimizing" is not end user friendly.

Recommend updating this to redirect to a best practice document or provide specific feedback as to why the file load failed or specific actions that can be taken to remedy issue.

**Comment by ffdixon** [comment]
@antobinary Can we override the language strings on the server to include a link in the message?

   Unable to convert (see _ troubleshooting uploads _)

In other words, can we add an <a href ... /> in the localization string?

**Comment by capilkey** [comment]
We can add wildcards to the localization strings. The \<a\> tag would get added in the code and the URL would be pulled from settings.yml.

I had taken a quick look at the modal code and to see if I could do it quickly, but if the error string is too long then it will result in a horizontal scrollbar so it needs word wrapping and other things.
