### ISSUE TITLE
Error 1007 ICE... Failed joining audio conf.

### ISSUE THREAD

**Issue by ikaikai** [bigbluebutton/bigbluebutton#8418]
[11:41:24:0464]  INFO: clientLogger: Audio call session accepted InviteClientContext.p (https://class.demos.cloud/html5client/23acf17a7f66feccb643e681b6de9fd0361d4c3a.js?meteor_js_resource=true:125:1167498)
sip.js?v=815:1272 SIP.EventEmitter#off is deprecated and may be removed in future SIP.js versions.
Please use removeListener or removeAllListeners instead.
See here for more details:
http://nodejs.org/api/events.html#events_emitter_removelistener_event_listener
off @ sip.js?v=815:1272
p @ 23acf17a7f66feccb643e681b6de9fd0361d4c3a.js?meteor_js_resource=true:125
EventEmitter.emit @ sip.js?v=815:115
accepted @ sip.js?v=815:5641
onSuccess @ sip.js?v=815:6854
(anonymous) @ 23acf17a7f66feccb643e681b6de9fd0361d4c3a.js?meteor_js_resource=true:1
Promise.then (async)
n.then @ 23acf17a7f66feccb643e681b6de9fd0361d4c3a.js?meteor_js_resource=true:21
receiveInviteResponse @ sip.js?v=815:6835
receiveResponse @ sip.js?v=815:3784
InviteClientTransaction.receiveResponse @ sip.js?v=815:7835
onMessage @ sip.js?v=815:8569
ws.onmessage @ sip.js?v=815:8427
sip.js?v=815:2900 Thu Dec 12 2019 11:41:29 GMT+0800 (中国标准时间) | sip.invitecontext.mediahandler | RTCIceChecking Timeout Triggered after 5000 milliseconds
23acf17a7f66feccb643e681b6de9fd0361d4c3a.js?meteor_js_resource=true:9 [11:41:39:0496] ERROR: clientLogger: ICE connection failed before success MediaHandler.g (https://class.demos.cloud/html5client/23acf17a7f66feccb643e681b6de9fd0361d4c3a.js?meteor_js_resource=true:125:1168708)
sip.js?v=815:1272 SIP.EventEmitter#off is deprecated and may be removed in future SIP.js versions.
Please use removeListener or removeAllListeners instead.
See here for more details:
http://nodejs.org/api/events.html#events_emitter_removelistener_event_listener
off @ sip.js?v=815:1272
(anonymous) @ 23acf17a7f66feccb643e681b6de9fd0361d4c3a.js?meteor_js_resource=true:125
g @ 23acf17a7f66feccb643e681b6de9fd0361d4c3a.js?meteor_js_resource=true:125
EventEmitter.emit @ sip.js?v=815:112
peerConnection.oniceconnectionstatechange @ sip.js?v=815:11580
sip.js?v=815:1272 SIP.EventEmitter#off is deprecated and may be removed in future SIP.js versions.
Please use removeListener or removeAllListeners instead.
See here for more details:
http://nodejs.org/api/events.html#events_emitter_removelistener_event_listener
off @ sip.js?v=815:1272
(anonymous) @ 23acf17a7f66feccb643e681b6de9fd0361d4c3a.js?meteor_js_resource=true:125
(anonymous) @ 23acf17a7f66feccb643e681b6de9fd0361d4c3a.js?meteor_js_resource=true:125
exitAudio @ 23acf17a7f66feccb643e681b6de9fd0361d4c3a.js?meteor_js_resource=true:125
d @ 23acf17a7f66feccb643e681b6de9fd0361d4c3a.js?meteor_js_resource=true:125
l @ 23acf17a7f66feccb643e681b6de9fd0361d4c3a.js?meteor_js_resource=true:125
g @ 23acf17a7f66feccb643e681b6de9fd0361d4c3a.js?meteor_js_resource=true:125
EventEmitter.emit @ sip.js?v=815:112
peerConnection.oniceconnectionstatechange @ sip.js?v=815:11580
sip.js?v=815:2900 Thu Dec 12 2019 11:41:39 GMT+0800 (中国标准时间) | sip.inviteclientcontext | terminating Session
sip.js?v=815:2900 Thu Dec 12 2019 11:41:39 GMT+0800 (中国标准时间) | sip.transport | sending WebSocket message:

BYE sip:919667998@44.228.244.151:5060;transport=udp SIP/2.0
Via: SIP/2.0/WSS 33jndlprjgjs.invalid;branch=z9hG4bK5167729
Max-Forwards: 70
To: <sip:919667998@class.demos.cloud>;tag=75vDUmHFpe78F
From: "w_5sia44tmkbqy_9-bbbID-Tiankai" <sip:w_5sia44tmkbqy_9-bbbID-Tiankai@class.demos.cloud>;tag=86ejcjj0gc
Call-ID: 6084n2qs56sqd3loqlrh
CSeq: 5768 BYE
Supported: outbound
User-Agent: BigBlueButton
Content-Length: 0

sip.js?v=815:2900 Thu Dec 12 2019 11:41:39 GMT+0800 (中国标准时间) | sip.inviteclientcontext | closing INVITE session 6084n2qs56sqd3loqlrhs31fkqc5q2
sip.js?v=815:2900 Thu Dec 12 2019 11:41:39 GMT+0800 (中国标准时间) | sip.invitecontext.mediahandler | closing PeerConnection

**Comment by ikaikai** [comment]
Video conf works fine.
Audio conf LISTEN ONLY works fine.
All other features work fine.
test.bigbluebutton.org tested successfully.

sip.invitecontext.mediahandler | RTCIceChecking Timeout Triggered after 5000 milliseconds
23acf17a7f66feccb643e681b6de9fd0361d4c3a.js?meteor_js_resource=true:9 [11:41:39:0496] ERROR: clientLogger: ICE connection failed before success MediaHandler.g

**Comment by ffdixon** [comment]
Thanks for checking it on `test.bigbluebutton.org` (that's usually what we ask folks to do first).

`test.bigbluebutton.org` has a TURN server to help users who are behind restricted firewalls get connected.  Is there a firewall between you and your BigBlueButton server.

You can set up one for your server as well, see

  http://docs.bigbluebutton.org/2.2/setup-turn-server.html

and let us know if your are now able to join with audio.

**Comment by capilkey** [comment]
If video works fine without a TURN server then a TURN server is unlikely to be the correct solution for the audio.

@ikaikai I would suggest checking the SDP that the server is sending back and make sure the IP address in the candidate is your server's public IP. If the IP isn't the public IP then you'll want to follow the steps to configure FreeSWITCH http://docs.bigbluebutton.org/2.2/configure-firewall#update-freeswitch

**Comment by ikaikai** [comment]
Fred and Chad, 
Thank you so much.
After I installed a coturn server for my bbb. Audio conf worked.
It is not a bug, and I must have a TURN server.

Best regards,

**Comment by Anstoliy** [comment]
I useв bbd-install.sh and had the same error. server/client behind NAT
it helped me: commented in /usr/share/bbb-web/WEB-INF/classes/spring/turn-stun-servers.xml

**Comment by joo4mart** [comment]
After many many tests I have found the easiest solution: 
> systemctl restart docker

If you have changed manually some files you should restart some bbb services and at the end docker, too:
> systemctl restart bbb-web
> systemctl restart bbb-webrtc-sfu
> systemctl restart freeswitch
> systemctl restart docker

**Comment by itmalan** [comment]
I also encountered with same issue. 1007 ICE... Failed joining audio. 
Problem is I added TCP ports 16384 - 32768 instead of UDP. Updated the firewall entry TCP to UDP which cleared the issue. Audio Test passed.

**Comment by ha3ant** [comment]
Dear users and king developers!
I have the same issue! clients can join on listen mode, can share webcam, but they cant share microphone and receive "Connection failure (ICE error 1007)"
I can't handle the issue, run turn server, open TCP ports 16384 - 32768 too, nothing change!
the only way is to use wan IP valid in free_switch: sip_ip: ... and change the value of local_ip_v4 in "/usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml" to valid wan IP, but when they set to the default of Lan local IP, we have error 1007!
Please help me, we have spent a lot of time on it! :(

**Comment by matiasilva** [comment]
Follow the guidelines for getting help at: https://docs.bigbluebutton.org/2.2/getting-help.html, please.

**Comment by ha3ant** [comment]
Thank you for your reply, I spent more than 2 weeks on that, but nothing helps me.  When I set External_Ip my freeswitch work well, but when using Internal_Ip (as default on script bbb-install.sh) I can use microphone and error 1007 raised. Also we config Turn server as said on helps. but there is no difference :(

**Comment by matiasilva** [comment]
Make sure to join the setup mailing list, as is indicated in that link.

**Comment by ritesh2590** [comment]
It works when we just open test.bigbluebutton.org in a new tab

**Comment by arnounesco** [comment]
all the links to https://docs.bigbluebutton.org/2.2 seem to be death

**Comment by caos30** [comment]
Guys i can happily share with you that i have finally solved this problem in a very simple way. I've shared the details in this other issue: https://github.com/bigbluebutton/bigbluebutton/issues/10764#issuecomment-939229402

But very briefly: 

1. deploying a STUN server in the same VM where i run BBB, thanks to a single docker command (woowww!)
2. modifying the BBB settings file to use ```127.0.0.1:3478``` as STUN server
