### ISSUE TITLE
CREATE is not idempotent in Version 2.2.0-beta-19

### ISSUE THREAD

**Issue by febincloudyuga** [bigbluebutton/bigbluebutton#8423]
**BigBlueButton version used in our server - Version 2.2.0-beta-19**

Quoting from the documentation, 

> The create call is idempotent: you can call it multiple times with the same parameters without side effects. This simplifies the logic for joining a user into a session as your application can always call create before returning the join URL to the user. This way, regardless of the order in which users join, the meeting will always exist when the user tries to join (the first create call actually creates the meeting; subsequent calls to create simply return SUCCESS).

On implementation, the first time I make a call to `create`, it returns a success and a meeting room is created. Making subsequent calls with the same parameters fails with the below mentioned error 

> A meeting already exists with that meeting ID. Please use a different meeting ID.

When this is used before every `join`, this results in major trouble with only the first user being able to join and all the subsequent users being redirected to the default page.

I could see [this issue was fixed in 2015](https://github.com/bigbluebutton/bigbluebutton/issues/2702), but it seems to be reappearing. Also, the commit fix mentioned in this link returns 404.

Please advice.

**Comment by capilkey** [comment]
What parameters are you passing with the create? I just tried to reproduce with Mconf's API Mate (https://mconf.github.io/api-mate) and I can send the create request as many times as I want and it returns a "SUCCESS" every time.

(Enter your own servers credentials, don't use the test-install ones)

**Comment by capilkey** [comment]
I am seeing the same failure message if I change one of the passwords though. Is it possible that those are being changed between calls for you?

**Comment by febincloudyuga** [comment]
@capilkey Thanks for your inputs. I was only passing meeting name and ID. On passing attendee password and moderator password, it returns me a success every time.

Maybe the documentation could be updated stating the required parameters to make create idempotent?

Thanks. Closing this.
