### ISSUE TITLE
The check for maxParticipants isn't working correctly

### ISSUE THREAD

**Issue by capilkey** [bigbluebutton/bigbluebutton#8428]
If I set maxParticipants to 3 and try to join three clients, the first two join and the third is rejected with a message about the maximum being reached. If one of the first two leaves (and waits 10s to be removed from the users list) I then can't join a second user either until some time has passed.

It looks like the check for number of participants might be `<` instead of `<=` and it might be counting users who haven't actually joined yet.

**Comment by pedrobmarin** [comment]
We had this discussion a while ago. The problem is on the user registration that runs before the maxParticipants check

**Comment by capilkey** [comment]
You're right. I just found an issue that @GhaziTriki opened a while ago (#5843). I'll close this one then.
