### ISSUE TITLE
Can't drag the progress bar while playing back of recordings on iOS 13.3

### ISSUE THREAD

**Issue by fungma** [bigbluebutton/bigbluebutton#8429]
in /usr/local/bigbluebutton/core/scripts/presentation.yml
comment out "- mp4" to Enable playback of recordings on iOS

record some session.

when playback of recordings on iOS 13.3

It's OK to click anywhere on the progress bar during playback
But you can't drag the progress bar while playing

**Comment by pedrobmarin** [comment]
Should not be a problem in the new playback.
