### ISSUE TITLE
bigbluebutton-setup] Trying to install HTML5 client from package, error

### ISSUE THREAD

**Issue by shabir-khan** [bigbluebutton/bigbluebutton#8431]
when i am trying to install bbb-html5 it gives below error.

root@live:~# sudo apt-get install bbb-html5
Reading package lists... Done
Building dependency tree
Reading state information... Done
bbb-html5 is already the newest version (1:2.2.0-815).
The following package was automatically installed and is no longer required:
  python3-jsonschema
Use 'sudo apt autoremove' to remove it.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
1 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n] y
Setting up bbb-html5 (1:2.2.0-815) ...
cat: /usr/share/etherpad-lite/APIKEY.txt: No such file or directory
dpkg: error processing package bbb-html5 (--configure):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 bbb-html5
E: Sub-process /usr/bin/dpkg returned an error code (1)

and when I am checking ther status show 2 of them failed..

root@live:~# bbb-conf --status
nginx —————————————————► [✔ - active]
freeswitch ————————————► [✔ - active]
redis-server ——————————► [✔ - active]
bbb-apps-akka —————————► [✔ - active]
bbb-transcode-akka ————► [✔ - active]
bbb-fsesl-akka ————————► [✔ - active]
red5 ——————————————————► [✔ - active]
mongod ————————————————► [✔ - active]
bbb-html5 —————————————► [✘ - failed]
bbb-webrtc-sfu ————————► [✘ - failed]
kurento-media-server ——► [✔ - active]
etherpad ——————————————► [✘ - failed]
bbb-web ———————————————► [✔ - active]

**Comment by ffdixon** [comment]
Are you upgrading an existing server or is this a new install for 2.2?

**Comment by shabir-khan** [comment]
its a new install on scaleway cloud

**Comment by shabir-khan** [comment]
i enter the commad few times as it failed that why may be its showing installed but not working

**Comment by ffdixon** [comment]
Can you try installing with [bbb-install.sh](https://github.com/bigbluebutton/bbb-install) and let us know if that gets you further.

**Comment by shabir-khan** [comment]
still i am receiving errors as below.

Errors were encountered while processing:
 bbb-html5
E: Sub-process /usr/bin/dpkg returned an error code (1)
Generating DSA parameters, 4096 bit long prime
..................+.........+......+++++++++++++++++++++++++++++++++++++++++++++++++++*
.+.+......+..+...........+.+.............+......+...............+..........................+.......+...+....+....+.........................+..+...........+.......+..+.......+.+.........+.....+.+...+......+..................+....+........+.....+......+.................+.......+.......+....+..+...........+.......+.+.+.......+.....+..........+..+........+..............+................+.............................+.....+......+..+...+.+...+............................+.......+...........+......+..............+........+...+..+..............+.+....+.......+..........+............+............................+...........................+..+..+.+....+.........+.............+.+...........+...+.............+.+..+....+.......+......+...+........+.....+........+.........+............+..+...............+........+++++++++++++++++++++++++++++++++++++++++++++++++++*
Job for nginx.service failed because the control process exited with error code. See "systemctl status nginx.service" and "journalctl -xe" for details.
usage:
  certbot [SUBCOMMAND] [options] [-d DOMAIN] [-d DOMAIN] ...

Certbot can obtain and install HTTPS/TLS/SSL certificates.  By default,
it will attempt to use a webserver both for obtaining and installing the
certificate.
certbot: error: argument -m/--email: expected one argument
bbb-install: Let's Encrypt SSL request for  did not succeed - exiting


I am new to the cloud my ethernet interface is showing private ip, not sure how to bound it to the public ip which can be one of the reason

root@live:/etc/network# ifconfig
ens2      Link encap:Ethernet  HWaddr de:1c:44:57:90:01
          inet addr:10.64.212.1  Bcast:10.64.212.1  Mask:255.255.255.254
          inet6 addr: fe80::dc1c:44ff:fe57:9001/64 Scope:Link
          inet6 addr: 2001:bc8:47a8:1a00::1/64 Scope:Global
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:58295 errors:0 dropped:0 overruns:0 frame:0
          TX packets:32564 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:1385867682 (1.3 GB)  TX bytes:4440055 (4.4 MB)

lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:14250 errors:0 dropped:0 overruns:0 frame:0
          TX packets:14250 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1
          RX bytes:3643444 (3.6 MB)  TX bytes:3643444 (3.6 MB)


 sorry to bother you guys i have deployed openedx and need it to intergrate with bbb as LTI and I am not a developer

**Comment by shabir-khan** [comment]
these are the commets from the Scaleway team for the public/private ip
“Each instance have a private network and the public ip is nated on this, avalaible on all server cloud except dedicated server that the public ip is configurated on the network card directly:

**Comment by shabir-khan** [comment]
i tried to install it with below command at the beginning but now sure why it dint worked

wget -qO- https://ubuntu.bigbluebutton.org/bbb-install.sh | bash -s -- -v xenial-220 -s live.xxx.com -e shabir@xxx.com -g

now after following all those step by step installation until upto 
sudo apt install bbb-html 
which failed as i have logged an issue for
now i applied this command and it worked.

wget -qO- https://ubuntu.bigbluebutton.org/bbb-install.sh | bash -s -- -v xenial-220 -s live.xxx.com -e shabir@xxx.com -g

 I am able to view demo cam and screen sharing but now voice has some issue ERROR 1002.
 

Any how as my developer is in the process of developing openedx and ecomm, I think I should crash this machine and 

start from the beginning BBB installation only when that is ready.

because I think you guys did it well for even a common layman , so would think about it as because of you guys i
wouldn't have to pay to keep the server up till my other deployment is ready.

and I hope you guy will be helpful in future as well if I face any issues at that time.

thanks for quick response
