### ISSUE TITLE
Send feedback after meeting end to a HTTP endpoint

### ISSUE THREAD

**Issue by GhaziTriki** [bigbluebutton/bigbluebutton#8432]
**Is your feature request related to a problem? Please describe.**
Currently there is no way to collect users feedback when the meeting ends.

**Describe the solution you'd like**
Add a new configuration to set the endpoint were user feedback is sent. Data would be sent as JSON.

**Comment by ffdixon** [comment]
It's possible to collect it from the client logs, see http://docs.bigbluebutton.org/2.2/customize.html#collect-feedback-from-the-users.

If you want only feedback sent to a specific URL, you could create a program that tails the client logs and, when it detects a feedback form, extracts it and sends it as a POST request to any endpoint you wish.

Would that work?

**Comment by GhaziTriki** [comment]
That would perfectly work.
