### ISSUE TITLE
Support UTF-8 Characters in bigbluebutton.properties

### ISSUE THREAD

**Issue by GhaziTriki** [bigbluebutton/bigbluebutton#8433]
**Describe the bug**
UTF-8 characters are not supported in bigbluebutton.properties

**To Reproduce**
Steps to reproduce the behaviour:
1. Put `eğitim.pdf` in the default presentation.
2. Put `eğitim.pdf` in welcome message.
3. Build and test.
4. Check for the wrongly encoded characters, and the presentation is not loaded.

A similar issue can be found here https://github.com/bigbluebutton/bigbluebutton/issues/3453

A linked issue https://github.com/bigbluebutton/bigbluebutton/issues/7479

**Comment by GhaziTriki** [comment]
Moving to Java 9 seems to resolve the issue https://docs.oracle.com/javase/9/docs/api/java/util/Properties.html#loadFromXML-java.io.InputStream-

**Comment by fcecagno** [comment]
Run this as sudo will reset encoding to ISO-8859-1:
```
cat /etc/bigbluebutton/bbb-web.properties | sponge | iconv -f UTF-8 -t ISO-8859-1//TRANSLIT -o /etc/bigbluebutton/bbb-web.properties
```
