### ISSUE TITLE
Font rendering issue with non latin letters

### ISSUE THREAD

**Issue by GhaziTriki** [bigbluebutton/bigbluebutton#8434]
**Describe the bug**
Currently the used font does not support non latin letters.

**To Reproduce**
1. Change the language to Turkish.

**Expected behavior**
The font should render like this
![image](https://user-images.githubusercontent.com/4991088/70934711-ca298000-203e-11ea-8c6b-99063e3149fd.png)

**Actual behavior**
You should not see characters rendered in bold
![image](https://user-images.githubusercontent.com/4991088/70934741-ddd4e680-203e-11ea-8444-d5b9045cdd61.png)

**Comment by GhaziTriki** [comment]
The screenshot shows a text in Turkish. Source Sans Pro does not support the Turkish language, https://www.fontsquirrel.com/fonts/source-sans-pro

**Comment by tylercopeland** [comment]
@GhaziTriki and I had a quick conversation about this issue. It looks like our version of "Source Sans Pro" is quite old. 

Next steps, @GhaziTriki is going to experience with updating the font locally and reporting back. 

Here is more information about the latest version of "Source Sans Pro" -> https://github.com/adobe-fonts/source-sans-pro/releases
