### ISSUE TITLE
Allow change camera resolution on HTML5 Client

### ISSUE THREAD

**Issue by lfdominguez** [bigbluebutton/bigbluebutton#8435]
**Describe the bug**
The HTML5 Client only allow set 3 profiles for the camera quality, but that change the bitrate and not the resolution of the camera

**Expected behavior**
Allow to change the camera resolution

**Additional context**
I have 1 mbps on my external network and BigBlueButton is the main VideoConference server that i need to setup, but with the default 100kbps and same camera resolution i see high lags. I was tested OpenMeetings and they allow change the resolution of the camera and i can connect 6 people over the 1 mbps. Whit BigBlueButton that have a better nice HTML5 UI with 3 participant have many lags and block.

**Comment by prlanzarin** [comment]
You can set the bitrate in the camera profiles to as low as 30kbps. Try that first in bbb-html5's settings.yml. 

ps.: We had a resolution picker in the past, but there were some problems with the implementation so we decided to shift the camera profiles to be bitrate based, which should be enough to tune the bandwidth usage.

**Comment by capilkey** [comment]
You can also still set the resolution constraints if you want to. Some devices might not match those resolutions though. You have to add a "constraints" block to the camera profile and it will be passed directly to the getUserMedia call. You can find all of the potentially supported constraints here, https://developer.mozilla.org/en-US/docs/Web/API/MediaTrackConstraints.
```
      - id: medium
        name: Medium quality
        default: true
        bitrate: 200
        constraints:
          width: X
          height: Y
```
In particular iOS and virtual webcams are pretty bad with resolution constraints.

**Comment by lfdominguez** [comment]
Ohh thanks for the quick response... The HTML5 UI of BBB is the best!!!!!

**Comment by lfdominguez** [comment]
Great... only asking, there are something to allow resize (with kurento) the media sended by clients, because i have on one conference, clients with 40 mbps of bandwidth, but i have others with only 512kbps (really), so if a client set they video to High Quality, the kurento backend scale the video or recode with low bandwidth??

**Comment by vvenkanna** [comment]
> You can also still set the resolution constraints if you want to. Some devices might not match those resolutions though. You have to add a "constraints" block to the camera profile and it will be passed directly to the getUserMedia call. You can find all of the potentially supported constraints here, https://developer.mozilla.org/en-US/docs/Web/API/MediaTrackConstraints.
> 
> ```
>       - id: medium
>         name: Medium quality
>         default: true
>         bitrate: 200
>         constraints:
>           width: X
>           height: Y
> ```
> 
> In particular iOS and virtual webcams are pretty bad with resolution constraints.

I tried setting the latest constraints width and height and I tested latest bigbluebutton-html5 - 2.2 latest version, but it is not working? Any idea I want this feature disperately.  Any help will be greatly appreciated.
Thanks
Venkanna

**Comment by matiasilva** [comment]
Hi, it should be working. Make sure you respect the right syntax for the MediaTrackConstraints as shown above. If you need further support, join the setup mailing list: https://docs.bigbluebutton.org/2.2/getting-help.html#help-installing-or-running-bigbluebutton

**Comment by vvenkanna** [comment]
matiasilva, Thanks for your reply, I didnt change much except for adding constraints width and height. Following is my settings.yml file, I tried different  width and heights, but no luck. Did I made any mistake in the config? Thanks

  cameraProfiles:
    - id: low
      name: Low quality
      default: false
      bitrate: 100
    - id: medium
      name: Medium quality
      default: true
      bitrate: 200
      constraints:
          width: 1280
          height: 720
    - id: high
      name: High quality
      default: false
      bitrate: 500
    - id: hd
      name: High definition
      default: false
      bitrate: 800
