### ISSUE TITLE
bigbluebutton-web should work with Tomcat SECURITY=YES

### ISSUE THREAD

**Issue by bigbluebutton-issue-import** [bigbluebutton/bigbluebutton#844]
Originally reported on Google Code with ID 89

```
Currently, the BigBlueButton VM runs tomcat6 with SECURITY=NO.

It's possible to create a policy file for tomcat6 that tells tomcat6 the 
minimal permissions that bigbluebutton-web needs to run -- no more, no less.

Everything is visible in the VM.  Anyone want to give a try creating this 
policy file?

```

Reported by `ffdixon` on 2009-07-04 22:55:20

**Comment by ffdixon** [comment]
Closing this issue.  With the use of Let's Encryp and nginx, all API requests to tomcat (now tomcat7) are doing through SSL.  See

  http://docs.bigbluebutton.org/install/install.html
