### ISSUE TITLE
Room option - focus presenter

### ISSUE THREAD

**Issue by Radnik** [bigbluebutton/bigbluebutton#8444]
Hi devs,

It could be that i am missing it, room option "focus presenter" would be good feature.
i guess it has something with "pushing" layout to all clients, but is it possible to glue the view so the presenter is in focus always?

best regards

**Comment by ffdixon** [comment]
Currently, if there are three or more webcams, the user can give focus to a specific webcam, but this is done by the user, not the presenter.

We already have an open request to push layout down to user.  Merging their request into https://github.com/bigbluebutton/bigbluebutton/issues/7987.
