### ISSUE TITLE
Screenshare from student side

### ISSUE THREAD

**Issue by herpsonc** [bigbluebutton/bigbluebutton#8445]
First, thanks for your work and very stable tool.

- This issue is  a feature requirement, not a bug.
- The possibility for the teacher to see a student's screen is very important to help them.
- From my point of view this feature is an "adopt or drop" point regarding any online learning tool. And I'm sure it could greetly enhance both BBB visibility and success.

Is this feature planned ?

**Comment by ffdixon** [comment]
You can do this now if you make the student presenter and then invite them to share their screen.  See tutorial video for Moderator/Presenter: https://bigbluebutton.org/html5/.

Note that the student must initiate the screen sharing and give their browser permission to share their screen.  This isn't something that the instructor can initiate.
