### ISSUE TITLE
Minified React error #185

### ISSUE THREAD

**Issue by GhaziTriki** [bigbluebutton/bigbluebutton#8446]
After joining a session I see this error in the page
```
Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings. 
```

![image](https://user-images.githubusercontent.com/4991088/71289054-68358700-236c-11ea-81d3-d179291b1b2d.png)

During the session it was not possible to share the webcam.

Kurento CPU usage went from 10% to 110%. (800% is the max on this server having 8 cores)

**Comment by ffdixon** [comment]
@GhaziTriki Are you able to reproduce this issue?

**Comment by GhaziTriki** [comment]
@ffdixon I didn't see this error for a while. Closing it. I will open it of someone reports it again.

**Comment by kittang** [comment]
Hello, 

I was using the custom polling when this error occurred. When I used Chinese input (input max allowed characters) for the polling options and publish the result, then I will see this error. 

![bbb_poll_error](https://user-images.githubusercontent.com/6780183/75507685-b88c2d80-5a1c-11ea-959d-1c8915681549.gif)

**Comment by glu000** [comment]
I had the same issue in combination with polling and without chinese characters. It was a simple Yes / No Poll with 8 participants

**Comment by GremL1N** [comment]
We got this error just in Yabdex browser.

**Comment by lonesomewalker** [comment]
We also get this in german language, 5 users, using poll.
Crash, after re-entering everything works as expected.

**Comment by sumit1528** [comment]
Same with me as well create a normal custom poll and after submission this error started with also i was creating poll in normal english

**Comment by datenzwergin** [comment]
same problem here for a custom poll with 12 people.
I guess most cases might be fixed with this:
[#8952 Fix maximum update depth exceeded in poll annotation ](https://github.com/bigbluebutton/bigbluebutton/pull/8952)

Though the simple yes/no poll of @glu000 does not really fit...

**Comment by mtiger95** [comment]
Has anyone solved the problem ？ I meet the same problem today !
