### ISSUE TITLE
Keyboard shortcuts not working

### ISSUE THREAD

**Issue by Jossef-767** [bigbluebutton/bigbluebutton#8457]
tested on test.bigbluebutton.org

Alt + O	Open Options
Alt + U	Toggle UserList
Alt + A   Open actions menu
Alt + S   Open status menu

**Desktop pc
 - OS: win 10
 - Browser  Chrome   Version 79.0.3945.88

**Comment by ffdixon** [comment]
Thanks Jossef -- always appreciate your help in testing BigBlueButton.  We'll take a closer look.
