### ISSUE TITLE
Cookies served by BigBlueButton should be marked as secure

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#8463]
**Describe the bug**
Currently, cookies served by BigBlueButton are not [marked as secure](https://www.owasp.org/index.php/SecureFlag).

**To Reproduce**
1. Setup a BigBlueButton server with a domain name without SSL and load the client.  The cookies are shared from the server and are visible in clear text when transmitted.

**Additional context**
Suggested in bigbluebutton-dev, see

  https://groups.google.com/d/msg/bigbluebutton-dev/Yd55tS2Ok2s/NRZdw5LOBQAJ

**Comment by pedrobmarin** [comment]
Done here https://github.com/bigbluebutton/bigbluebutton/pull/10511 and https://github.com/bigbluebutton/etherpad-lite/pull/7
