### ISSUE TITLE
Sreenshare button not appearing after making an attendee as presenter on Safari MacOS

### ISSUE THREAD

**Issue by GhaziTriki** [bigbluebutton/bigbluebutton#8469]

**Comment by GhaziTriki** [comment]
Test on demo server.

**Comment by ffdixon** [comment]
I think this is a usability issue -- we don't yet support screensharing on Safari (that's coming soon), and do we're not displaying the screen sharing icon.

We should still display the icon and, when selected, tell the user that screen sharing is not yet supported on Safari.

This way, they don't wonder why it's not appearing for them.

**Comment by aogilvie** [comment]
https://github.com/bigbluebutton/bigbluebutton/issues/8576

**Comment by prlanzarin** [comment]
Fixed by #9066.
