### ISSUE TITLE
Video and Sharescreen is not working HTTPS issue.

### ISSUE THREAD

**Issue by besingamkb** [bigbluebutton/bigbluebutton#8470]
Hi, 

I have installed bbb on a ubuntu 16 server using the install.sh and i also have configure everything and it is working fine except for video and sharescreen. please see below screenshot of what error i got when I try to share screen
![2020-01-08_21-20](https://user-images.githubusercontent.com/6380139/71981762-ff03ae00-325d-11ea-9d26-31b44ca0033f.png)

**Comment by pedrobmarin** [comment]
Looks like you're missing `wss` configuration here https://github.com/bigbluebutton/bigbluebutton/blob/master/bigbluebutton-html5/private/config/settings.yml#L89

**Comment by ffdixon** [comment]
Hi there,

Did you use `bbb-install.sh` from https://github.com/bigbluebutton/bbb-install and configure the server to have a SSL certificate, as described here
 
  https://github.com/bigbluebutton/bbb-install#install-with-ssltls

Just tried it on a test server and screen sharing worked out of the box.
  

 have installed bbb on a ubuntu 16 server using the install.sh

**Comment by besingamkb** [comment]
@ffdixon yes I use install.sh everyhing is working except for the video and screenshare. i might have missed something when setting up ssl. or maybe its because I only use certbot?

@pedrobmarin i might try that. can you help me where is that configuration located ?

**Comment by capilkey** [comment]
You'll find settings.yml at "/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml" and then go to the line that Pedro linked to

**Comment by besingamkb** [comment]
thanks @pedrobmarin you got it exactly. thank @capilkey for pointing out. it is working on my end now
