### ISSUE TITLE
How to test audio and video in a local area network

### ISSUE THREAD

**Issue by wangyanke520** [bigbluebutton/bigbluebutton#8471]
**Describe the bug**
I have a successful installation in a virtualized environment with virtualbox in the LAN, no SSL and domain name configured。run sudo bbb_conf -- status,All processes have started and are running. And I can tested with the demo ,but without  share video via WebRTC.
    Then I configured SSL according to the official instructions process ， No domain name used。
I run all ，but get 500 status code ,I've tried and tested it many times，but none of it was successful.
    I want to test the audio and video function in the local area network,without domain name, how to configure SSL?Must I use a domain name? Is it okay to use SSL only?

**Installation type**
Did you install manually or did you use the bbb-install script?
I installed it step by step
**Console output**
Please include the full console output from the install.

**Additional context**

**Comment by ffdixon** [comment]
>Then I configured SSL according to the official instructions process ， No domain name used。

You must have a domain name for SSL to work.

**Comment by capilkey** [comment]
You're also going to have issues if you try to use a self-signed certificate instead of an official one. It's possible to add the certificate everywhere that's required, but it's much easier to just get a real one.

I would recommend Let's Encrypt's DNS challenge if you have a domain name that you control.

**Comment by wangyanke520** [comment]
Now I have purchased a domain name, and I applied for a ssl for it. But the computer is my own Windows 10 computer, I only installed the virtual machine on it, the vm is Ubuntu 16.0.4  the same as mentioned earlier,Virtual machines and hosts are in the same IP segment，such as 192.168.0.x, but not public IP. Then I'm configured according to the official process and still can't succeed. Where's the problem? Do I have to set up a domain name server?

**Comment by ffdixon** [comment]
You can't use Let's Encrypt for creation of an SSL certificate if certbot can't reach your BigBlueButton server.

If your looking to try using BigBlueButton or developing on BigBlueButton, you'll find it easier to setup a public server (such as on Digital Ocean) and assign a DNS (such as from goDaddy) to the server's public IP address.

**Comment by capilkey** [comment]
You can use certbot with a private VM. There's a DNS challenge type where you set the given token as a DNS TXT record and it verifies with that. https://letsencrypt.org/docs/challenge-types/

@wangyanke520 Once you have the domain you can set it or a subdomain to point to a private IP. When I'm creating a VM I'll set something like mybbb.mydomain.com to point to 192.168.20.10. You need to use "bbb-conf --setip mybb.mydomain.com" and then always access BigBlueButton using the domain.

**Comment by ffdixon** [comment]
This isn't an issue to fix with BigBlueButton per se, but rather a question on setup of BigBlueButton.  In the future, please post such questions to the bigbluebutton-setup mailing list and we'll help you there.  See
  
  https://bigbluebutton.org/support

If in the discussion on the mailing list, we discover an issue to resolve or a feature to implement, we'll open an issue here to track it.
