### ISSUE TITLE
Support Ubuntu 18.04 in installation of BigBlueButton 2.3

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#8474]
We want to enable installation of BigBlueButton 2.3 on Ubuntu 18.04 (bionic).

This will enable us to update the underlying versions of

  * Meteor
  * MongoDB
  * Nodejs
  * Scala
  * Akka
  * Libreoffice
  * Java

**Comment by npettiaux** [comment]
With BBB in Docker is it possible to install it on a Ubuntu 20.04 that would be on the metal ? I have a brand new server, bought to run BBB, but today I would rather install ubuntu 20.04 than 16.04. Much thanks of your input

**Comment by ffdixon** [comment]
Ubuntu 20.04 looks pretty good.  We've been developing BigBlueButton 2.3 (the next version) on Ubuntu 18.04 for a few months.  We're going to look to see if we can skip right to 20.04.

**Comment by npettiaux** [comment]
Much thanks. Do you think it is safe that I install the server with Ubuntu 20.04 now and be able to install BBB on it as soon as possible ?

**Comment by ffdixon** [comment]
We recommend 16.04 for now.  We're planning for a beta of BigBlueButton 2.3 this summer, so it's still a ways off.

**Comment by npettiaux** [comment]
can BBB be installed in a docker and have the adequate performances ? 
Do you know a more recent set of install files than https://github.com/juanluisbaptiste/docker-bigbluebutton ?
Much thanks

**Comment by mipreuss** [comment]
Can you switch the support to 20.04 its out now.

**Comment by npettiaux** [comment]
do you mean that BBB can now be installed on ubuntu 20.04 ?

**Comment by mipreuss** [comment]
no, but they work to support 18.04 in the next version.
And maybe they use again old and unsupported stuff and than they talk about the about OS is supported with security updates. 

The next supported OS in BBB 2.3 should be ubuntu 20.04!

**Comment by slel** [comment]
Could this issue be made

    Support installing BBB on Ubuntu 18.04 and Ubuntu 20.04

and be part of the BBB 2.3 milestone?

As others have said it would be nice to support installing
on all current Ubuntu LTS releases.

**Comment by npettiaux** [comment]
as well as plain debian, which is the basis of ubuntu itself. Debian has a very large and very strong, committed community that could very well help BBB. If it runs on debian, it runs on ubuntu. So I would suggest investing in debian that is upstream.

**Comment by npettiaux** [comment]
I also wonder what kind of help and support you (the BBB team) need to go the 2.3 route. Students and colleagues of mine could help.

**Comment by jpbraun** [comment]
I totally agree. We need BBB for ubuntu 20.04 soon. We can't use BBB now because of the security issues of ubuntu 16.04.

**Comment by myymi** [comment]
> I totally agree. We need BBB for ubuntu 20.04 soon. We can't use BBB now because of the security issues of ubuntu 16.04.

While I agree that going for 20.04 is boon, I disagree with security issues of 16.04. It's still in the active support 'til the end of 2020. It would be nice if you referenced specific issues stopping you from using BBB.

**Comment by jpbraun** [comment]
That is the statement of our responsible IT company.

**Comment by mipreuss** [comment]
How long is the support for Node.js or MongoDB ?

**Comment by ckujau** [comment]
Can this report be renamed to _"Support current Ubuntu LTS in installation of BigBlueButton"_ maybe? Conferencing solutions like BBB is in high demand these days and when one orders a new machine, usually current flavours of the major Linux distributions are offered. I found it hard to get hold of a hosting provider that still offers Ubuntu 16.04 as an installation option. Also, while 16.04 is said to have "active support", the effectiveness and reliability of software backports can is debatable.

It's kinda sad that BBB relies on a specific distribution, its Docker images are [out of date](https://github.com/bigbluebutton/docker/commit/b66171f0d73ff847e2266218a98040d3c7a4d564 "Added warning that the scripts are not yet updated for 2.2") and the build process appears to be [undocumented](http://docs.bigbluebutton.org/2.2/install.html). But that's material for another bug report :-)

And yes, I know: it's FOSS, so...patches are welcome, and I do realize that my lines above are not really constructive in that regard.

**Comment by npettiaux** [comment]
What is needed to move to 20.04 or even better debian and have BBB packaged ? This would ensure that some debian developpers commit to help maintien the current version as a supporter component ?  I have somme CS students Who coule help. We could, I suppose, also find some paid developpers to step in and help résolve some of the pendant issues ? At least thé association educode.be has some money to dévote. Thanks for the guidance

**Comment by vasyugan** [comment]
> What is needed to move to 20.04 or even better debian and have BBB packaged ? 
I would absolutely support a move to Debian. Debian is much more solid. Ubuntu is really just a snapshot of Debian Testing with security support  limited to packages in main. Debian offers full security support for everything, and they now also have an LTS scheme, so that there is no apparent downside.
What I see as challenging btw, is getting FreeSwitch packaged for Debian, on which BBB relies.

**Comment by mohsen2hasani** [comment]
What makes BBB so dependent on the operating system version?

**Comment by ffdixon** [comment]
We are using Kurento as our media server, and currently the Kurento project supports 18.04, but not 20.04.  You'll see BigBlueButton 2.3-dev on 18.04, and we expect support for 20.04 to follow at some point.

**Comment by milkomeda** [comment]
bbb 2.3 as stable release is crucial. ubuntu 16.04 will lose support in 04/2021 (no more security updates in one month from now).

@ffdixon what is the current state of development? 2.3 is still on alpha 

are there any alternatives? I think we are going to see lot's of bbb installations going for security vulnerabilities again. Please also mind some time for all of the server admins to deploy.

**Comment by ffdixon** [comment]
Ubuntu Linux 16.04 LTS reaches the end of its five-year LTS window on April 30th 2021.

We (the core developers) want to move to 18.04 as well.   We had planned the release of 2.3 last year, but Covid had us focus a lot more on 2.2 (and all of the work on 2.2 has been merged into 2.3-dev).

We're working on getting a beta release of 2.3-dev (which signals its stable for wider testing) out soon, see

  https://docs.bigbluebutton.org/support/faq.html#bigbluebutton-development-process

**Comment by milkomeda** [comment]
> Ubuntu Linux 16.04 LTS reaches the end of its five-year LTS window on April 30th 2021.
> 
> We (the core developers) want to move to 18.04 as well. We had planned the release of 2.3 last year, but Covid had us focus a lot more on 2.2 (and all of the work on 2.2 has been merged into 2.3-dev).
> 
> We're working on getting a beta release of 2.3-dev (which signals its stable for wider testing) out soon, see
> 
> https://docs.bigbluebutton.org/support/faq.html#bigbluebutton-development-process

Is there anything blocking a beta/stable release atm the community could help with? Just for myself there are a lot of schools with thousands of pupils relying on bbb cause of Covid and privacy concerns on other solutions. I'm afraid of providing them an possibly insecure software solution as a basis for their communication.

**Comment by hex-m** [comment]
> Is there anything blocking a beta/stable release atm the community could help with?

You can install the current alpha version and [report bugs](https://docs.bigbluebutton.org/dev/dev23.html#giving-feedback-and-reporting-bugs). If everything works fine your feedback is still welcome. :)

There is also a public test server that runs the latest version of 2.3: https://test23.bigbluebutton.org/

**Comment by mhier** [comment]
I know it is not nice to ask "when is it ready" questions, but we have the awkward situation that Ubuntu 16.04 is running out of support end of April. To me it does not look like BBB 2.3 would be released by then (please correct me if this is wrong).

Which options do we then have to run BBB in a production environment? BBB is also heavily used in corporate environments, how does this work together?

I am running a BBB instance at my research institute for my group, but it is luckily behind a firewall - still it does not feel right to keep Ubuntu 16.04 running after EOL, so I probably need to switch to BBB 2.3 and hope it is stable enough... On the other hand, the IT department of my institute is also providing a BBB service, and I have heard they consider terminating it - which would be a real pity (using BBB through a VPN is far from ideal). How can I tell them to keep the service, if there is no perspective of running the stable version safely?

**Comment by ffdixon** [comment]
The next release of BigBlueButton 2.3-dev should be a beta release, which in our project means the features are all implemented (https://docs.bigbluebutton.org/dev/dev23.html) and it's ready for broader testing.

Given the feedback so far on 2.3-dev, we are optimistic that we'll have it stable and provide you an upgrade path (install on a new 18.04 server and migrate over your recordings) before 16.04 is EOL.  See also

  https://docs.bigbluebutton.org/support/faq.html#bigbluebutton-development-process

**Comment by vasyugan** [comment]
> The next release of BigBlueButton 2.3-dev should be a beta release, which in our project means the features are all implemented (https://docs.bigbluebutton.org/dev/dev23.html) and it's ready for broader testing.
> 
> Given the feedback so far on 2.3-dev, we are optimistic that we'll have it stable and provide you an upgrade path (install on a new 18.04 server and migrate over your recordings) before 16.04 is EOL. See also
> 
> https://docs.bigbluebutton.org/support/faq.html#bigbluebutton-development-process

Are you sure it should be 18.04, not 20.04? (and in the long run, wouldn't it be better to use Debian?)

**Comment by ffdixon** [comment]
For now, Kurento is keeping us on 18.04.  We'll get 2.3 out on 18.04 and look to move further ahead in a subsequent release.

**Comment by ffdixon** [comment]
BigBlueButton 2.3 is released!  Closing this issue.

**Comment by asim-quadri** [comment]
when to expect the realease of this version due to this many of my client are thinking to take your service due to their data privacy and lacking other security issue in 16.04 version of ubuntu becuase bbb is not supporting the 18.04 unbuntu version, Due to privacy issue i can't suggest bbb to other user's.If it take's time then i should check other web conferencing api

Asim

**Comment by NeroBurner** [comment]
@asim-quadri I thought BigBlueButton 2.3 supports Ubuntu 18.04? I don't quite see what the problem is

**Comment by dannycivi** [comment]
@asim-quadri yeah this issue is already closed and BBB does support Ubuntu 18.04 according to the readme (https://github.com/bigbluebutton/bigbluebutton#readme) and their website install page: https://docs.bigbluebutton.org/2.3/install.html
