### ISSUE TITLE
Is there a way to identify the audio locale in a meeting and capture that information?

### ISSUE THREAD

**Issue by SilentFlameCR** [bigbluebutton/bigbluebutton#8477]
As described above we need the audio language locale in a meeting to be recorded in the events.xml or any other method, so we can pass that along to the post_publish.rb and use it there. Once it is there we can send the audio to the correct language model service to transcribe the audio to text.

**Comment by pedrobmarin** [comment]
If I needed to guess the audio language, I would try to store some information about the presenter locale or fetch the most common locale between all participants of the meeting.
