### ISSUE TITLE
Error 2001 : media server offline

### ISSUE THREAD

**Issue by arbudiman** [bigbluebutton/bigbluebutton#8479]
I have installed BBM 2.2.0-rc-3. The webcam is not functioning, the message "error 2001: media server is offline" appears. I have not been able to resolve the problem. Here are the bbb-conf --check results:

root@vidcon:~# bbb-conf --check

BigBlueButton Server 2.2.0-rc-3 (1651)
                    Kernel version: 4.4.0-171-generic
                    Distribution: Ubuntu 16.04.6 LTS (64-bit)
                    Memory: 16432 MB
                    CPU cores: 4

/usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties (bbb-web)
       bigbluebutton.web.serverURL: https://vidcon.as.net.id
                defaultGuestPolicy: ALWAYS_ACCEPT
                 svgImagesRequired: true

/etc/nginx/sites-available/bigbluebutton (nginx)
                       server name: vidcon.as.net.id
                              port: 80, [::]:80
                              port: 443 ssl
                    bbb-client dir: /var/www/bigbluebutton

/var/www/bigbluebutton/client/conf/config.xml (bbb-client)
                Port test (tunnel): rtmp://vidcon.as.net.id
                              red5: vidcon.as.net.id
              useWebrtcIfAvailable: true

/opt/freeswitch/etc/freeswitch/vars.xml (FreeSWITCH)
                       local_ip_v4: 192.168.20.28
                   external_rtp_ip: 202.73.27.205
                   external_sip_ip: 202.73.27.205

/opt/freeswitch/etc/freeswitch/sip_profiles/external.xml (FreeSWITCH)
                        ext-rtp-ip: $${external_rtp_ip}
                        ext-sip-ip: $${external_sip_ip}
                        ws-binding: :5066
                       wss-binding: :7443

/usr/local/bigbluebutton/core/scripts/bigbluebutton.yml (record and playback)
                     playback_host: vidcon.as.net.id
                 playback_protocol: https
                            ffmpeg: 4.2.2-1bbb1~ubuntu16.04

/etc/bigbluebutton/nginx/sip.nginx (sip.nginx)
                        proxy_pass: 202.73.27.205

/usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml (Kurento SFU)
                        kurento.ip: 202.73.27.205
                       kurento.url: ws://127.0.0.1:8888/kurento
                    localIpAddress: 192.168.20.28
               recordScreenSharing: true
                     recordWebcams: true
                  codec_video_main: VP8
               codec_video_content: VP8

/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml (HTML5 client)
                             build: 815
                        kurentoUrl: wss://vidcon.as.net.id/bbb-webrtc-sfu
                  enableListenOnly: true

# Potential problems described below
# IP does not match:
#                           IP from ifconfig: 192.168.20.28
#   /etc/nginx/sites-available/bigbluebutton: vidcon.as.net.id

# Warning: The setting of 202.73.27.205 for proxy_pass in
#
#    /etc/bigbluebutton/nginx/sip.nginx
#
# does not match the local IP address (192.168.20.28).
# (This is OK if you've manually changed the values

result of bbb-conf --status :
root@vidcon:~# bbb-conf --status
nginx —————————————————► [✔ - active]
freeswitch ————————————► [✔ - active]
redis-server ——————————► [✔ - active]
bbb-apps-akka —————————► [✔ - active]
bbb-transcode-akka ————► [✔ - active]
bbb-fsesl-akka ————————► [✔ - active]
red5 ——————————————————► [✔ - active]
mongod ————————————————► [✔ - active]
bbb-html5 —————————————► [✔ - active]
bbb-webrtc-sfu ————————► [✔ - active]
kurento-media-server ——► [✔ - active]
etherpad ——————————————► [✔ - active]
bbb-web ———————————————► [✔ - active]

any suggestion?

thanks before...

**Comment by ffdixon** [comment]
Can you try installing using [bbb-install.sh](https://github.com/bigbluebutton/bbb-install) and let us know if your able to share video.

The [bbb-install.sh](https://github.com/bigbluebutton/bbb-install) automates the step-by-step instructions.

**Comment by arbudiman** [comment]
Thanks for you respond. I will trying to install using bbb-install.sh.

**Comment by ffdixon** [comment]
Closing this issue due.  If your still having problems with installation, please post such questions to the bigbluebutton-setup mailing list and we'll help you there.  See
  
  https://bigbluebutton.org/support

If in the discussion on the mailing list there is an issue to resolve or a feature to implement, we'll open an issue here to track it.
