### ISSUE TITLE
How to give my own name?

### ISSUE THREAD

**Issue by ugintl** [bigbluebutton/bigbluebutton#8489]
I have installed bbb 2.2 successfully on ubuntu 16 couple of days ago. However, I have not tested it. I want to self host bbb with my own company name. How can I do it?

What files I have to make changes?

**Comment by ffdixon** [comment]
Can you be more specific on what you want to change.  You can see many configuration options here

  http://docs.bigbluebutton.org/2.2/customize.html

**Comment by ugintl** [comment]
ok thanks.
