### ISSUE TITLE
Front end other than greenlight

### ISSUE THREAD

**Issue by ugintl** [bigbluebutton/bigbluebutton#8490]
Is greenlight only front-end for BBB. I intend to test bbb with Rocket Chat, but I am looking at different options.

**Comment by ffdixon** [comment]
Many systems have front-ends for BigBlueButton, see

  https://bigbluebutton.org/integrations/

There is also an API that you can use if you already have a front-end to integrate with BigBlueButton, see

  http://docs.bigbluebutton.org/dev/api.html

**Comment by ffdixon** [comment]
Closing this issue.  In the future, please post such questions to the bigbluebutton-dev mailing list.  See
  
  https://bigbluebutton.org/support

If in the discussion on the mailing list there is an issue to resolve or a feature to implement, we'll open an issue here to track it.
