### ISSUE TITLE
How would you rate following depending on the resources needed?

### ISSUE THREAD

**Issue by ugintl** [bigbluebutton/bigbluebutton#8491]
There are many good features in BBB, but it needs some good amount of server resources. I want to know what functionality/features takes the most share of the server like cpu, ram, storage etc in percentages.

For example you can say that video conferencing takes 20%, video call takes 10% etc etc or in any way you want to explain. I want to know that how having or not having a feature affects the system and what functionalities I can sacrifice for now.

This is useful for those who do not have enough starting capital and want to start their own online service.

**Comment by ffdixon** [comment]
You'll find that FreeSWITCH and Kurento -- the media servers -- will use the most CPU.  If the server is processing recordings in the background as well, that will use CPU resources.

The best way to see this is go onto a server with 10 web browsers (bring in some friends) and try sharing webcam or your screen.  You can see the incremental increase in CPU.  Doing this will give you data on the CPU capacity of your server.

You could disable webcams, for example, if you want

  http://docs.bigbluebutton.org/2.2/customize.html#disable-webcams

**Comment by ugintl** [comment]
Ok thanks
