### ISSUE TITLE
What external services I will be depending on?

### ISSUE THREAD

**Issue by ugintl** [bigbluebutton/bigbluebutton#8492]
When I was installing bbb, even though freeswitch is installed with bbb, I noticed that there is a link stun.freeswitch.org. What is it and how I can use my own?

What are other external services running along in bbb?

**Comment by ffdixon** [comment]
That's the only external service that BigBlueButton uses, and Kurento and FreeSWITH use this to help determine the server's external IP address.  See

   https://en.wikipedia.org/wiki/STUN

**Comment by capilkey** [comment]
You can also self-host your own STUN server, but it does need to be external from the network that your BigBlueButton server is on or it won't work correctly.

**Comment by ffdixon** [comment]
If you setup your own separate TURN server (which will help users behind restrictive firewalls send/receive media to the BigBlueButton server), the TURN server can also function as a STUN server, see

 http://docs.bigbluebutton.org/2.2/setup-turn-server.html

**Comment by ugintl** [comment]
@ffdixon This is good to know. Thank you for the info that turn server is responsible for send/receive media. It is just needed if user is behind firewall?

@capilkey You mean on a separate server/instance. Is it resource intensive?

**Comment by ffdixon** [comment]
> It is just needed if user is behind firewall?

Mostly yes, but the TURN server also functions as a STUN server as well. And you don't need a very powerful server for the TURN server.

And you do need to install the TURN server on a separate server (not the BigBlueButton server).

**Comment by ffdixon** [comment]
This isn't an issue to fix with BigBlueButton, but rather a question on BigBlueButton itself.  In the future, please post such questions to the bigbluebutton-dev mailing list.  See
  
  https://bigbluebutton.org/support

If in the discussion on the mailing list there is an issue to resolve or a feature to implement, we'll open an issue here to track it.
