### ISSUE TITLE
Record button missing for moderators with meetings created by API

### ISSUE THREAD

**Issue by cdg191** [bigbluebutton/bigbluebutton#8494]
**Describe the bug**
I created a meeting with the API, using the bare minimum requirements:

`name=Test+Meeting&meetingID=bookstudy`

I get a successful response from BBB with the attendeePW and moderatorPW.

I join the meeting as a moderator:

`fullName=Moderator&meetingID=bookstudy&password=ABCDEFG`

I join the meeting successfully.  However, the record button on the top isn't there.

I verified I joined as a moderator as I can upload presentations and affect other users.

I started over, this time explicitly stating allowStartStopRecording=true:

`name=Test+Meeting&meetingID=bookstudy&allowStartStopRecording=true`

Same result.  Record button on the top is missing.

Here are the versions of the BBB components we are using.  (see attachment)
[bbb.txt](https://github.com/bigbluebutton/bigbluebutton/files/4060949/bbb.txt)

Am I doing something wrong, or is something not working as intended?

Thanks BBB guys! :)

**Comment by capilkey** [comment]
You have to pass `record=true` on the create API call if you want to be able to record the meeting

**Comment by cdg191** [comment]
Ah, right you are!  I apparently overlooked that and didn't expect to have to set it as well.  Thank you!
