### ISSUE TITLE
When inviting late users into breakout rooms, show current occupants 

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#8495]
Currently, when inviting a late joiner to a breakout room (gear icon -> Breakout Room Invitation), the interface does not show the current users in breakout rooms.

For example, there is a user in Breakout room - 1, but it's now shown

![image](https://user-images.githubusercontent.com/290351/72378825-246e3d00-36e0-11ea-96f2-4d4615e71ce8.png)

The Flash client did show current paricipants in breakout rooms, which was helpful to the instructor when placing a late joiner into a breakout room.

**Comment by antobinary** [comment]
Clarification required: Users already occupying breakouts should be displayed in an inactive state showing that they cannot be moved to a different breakout, right? It would be awkward if you can move a user from room1 to room2

**Comment by ffdixon** [comment]
That's right -- I think we had the same in the previous client.
