### ISSUE TITLE
How to change the default conference audio sounds?

### ISSUE THREAD

**Issue by mabras** [bigbluebutton/bigbluebutton#8497]
My objective is replacing English audio system to Arabic. I have 4 wave sound but I could not replace the default audio system successfully. As I know "bigbluebutton" use Freeswitch to run sounds in virtual classroom.

I went to file location of the sounds which is mentioned in this xml file:
/opt/freeswitch/conf/autoload_configs/conference.conf.xml

Then I found the "muted" and "unmuted" sounds in this location
/opt/freeswitch/share/freeswitch/sounds/en/us/callie/conference

There are three folders I thought it's only bitrate issue. So, I replaced the following files:
conf-alone.wav
conf-unmuted.wav
conf-muted.wav
in those paths
/opt/freeswitch/share/freeswitch/sounds/en/us/callie/conference/48000
/opt/freeswitch/share/freeswitch/sounds/en/us/callie/conference/32000
/opt/freeswitch/share/freeswitch/sounds/en/us/callie/conference/16000
/opt/freeswitch/share/freeswitch/sounds/en/us/callie/conference/8000

After restarting "BBB" and greenlight, there is no sound anymore in conference room, neither  old or new ones.

Thanks

**Comment by ffdixon** [comment]
The first thing to check is that your new WAV files match the encoding of the older ones.  For example,

~~~
$ file /opt/freeswitch/share/freeswitch/sounds/en/us/callie/conference/8000/conf-you_are_already_muted.wav
/opt/freeswitch/share/freeswitch/sounds/en/us/callie/conference/8000/conf-you_are_already_muted.wav: RIFF (little-endian) data, WAVE audio, Microsoft PCM, 16 bit, mono 8000 Hz
~~~
