### ISSUE TITLE
BBB since 2.0 update incompatible with Yandex.Browser (Chromium based)

### ISSUE THREAD

**Issue by pokatusher** [bigbluebutton/bigbluebutton#8498]
I use Yandex.Browser, when i start room - BigBlueButton show me browserWarning about incompatibility with my browser. When i switch UserAgent to Chrome, for example, "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3835.0 Safari/537.36" - all OK.

BigBlueButton version is 2.0.5. My UserAgent: "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 YaBrowser/19.12.4.25 Yowser/2.5 Safari/537.36"

When BigBlueButton was 1.1, everything worked with this browser. The problem started after upgrading to 2.0.

Yandex.browser is the second most popular desktop browser in Russia (32% market share compared to Google Chrome, which has 40%)

**Comment by ffdixon** [comment]
Can you take the Yandex browser and point it to 

  https://demo.bigbluebutton.org/html5client/useragent

and let us know what useragent string your getting.

**Comment by GremL1N** [comment]
Yandex Browser 19.12.4 / Windows 10.0.0

**Comment by ffdixon** [comment]
Try adding your browser to `settings.yml` and restarting your BigBlueButton server.    See [The browser is not supportedAnchor](http://docs.bigbluebutton.org/2.2/troubleshooting.html#the-browser-is-not-supported) in the docs.

Let us know if the above gets you going with Yandex.

**Comment by ffdixon** [comment]
Just touching base to see if you were able to get BigBlueButton to work with Yandex by following the steps given above?

**Comment by capilkey** [comment]
Adding the browser to settings.yml will allow it to enter the client. I doubt any of the core developers test with the Yandex browser though so I don't know that I would ever set a default minimum version. I also wouldn't recommend installing it.

**Comment by antobinary** [comment]
Merging into #8101
