### ISSUE TITLE
Convert html5 bbb website to mobile app

### ISSUE THREAD

**Issue by ugintl** [bigbluebutton/bigbluebutton#8512]
I successfully installed bbb 2.2 html5 version on ubuntu 16. I also plan to install greenlight later. I want to convert my bbb website to android, ios and windows apps which can be uploaded on app stores and have native app features.

While searching for a solution, I found Phonegap and cordova. The best thing I found about phonegap is that it has a build tool where we upload the website and it converts into cross platform apps and its free.

Can I download and then upload my bbb website to phonegap build tool?

Have you people tried any of the tools out there?

Please share your experience.

**Comment by ffdixon** [comment]
This isn't an issue to fix with BigBlueButton, but rather a discussion on using phonegap.  Can we get you to post this to bigbluebutton-dev mailing list.  See
  
  https://bigbluebutton.org/support

If in the discussion on the mailing list there is an issue to resolve or a feature to implement, we'll open an issue here to track it.
