### ISSUE TITLE
Error 1006 while connecting to Echo test

### ISSUE THREAD

**Issue by Klagio** [bigbluebutton/bigbluebutton#8514]
I installed a fresh BBB using step by step instructions, and enabling the demo site.

Now when I og to 
https://xxx-bbb.duckdns.org

it presents the login screen, I put the username and it connects to the demo server. I do get the ERROR 1006 as in subject (tried Opera, Chrome and Firefox) .
The camera is sharing and working fine. The audio not

p.s. in Opera and Chrome I see the audio, video, and screen sharing. In Firefox the screen sharing is not present)

```

# bbb-conf --check

BigBlueButton Server 2.2.0-rc-3 (1651)
                    Kernel version: 4.4.0-171-generic
                      Distribution: Ubuntu 16.04.6 LTS (64-bit)
                            Memory: 4250 MB
                         CPU cores: 4

/usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties (bbb-web)
       bigbluebutton.web.serverURL: https://xxx-bbb.duckdns.org
                defaultGuestPolicy: ALWAYS_ACCEPT
                 svgImagesRequired: true

/etc/nginx/sites-available/bigbluebutton (nginx)
                       server name: xxx-bbb.duckdns.org
                              port: 80, [::]:80
                    bbb-client dir: /var/www/bigbluebutton

/var/www/bigbluebutton/client/conf/config.xml (bbb-client)
                Port test (tunnel): rtmp://xxx-bbb.duckdns.org
                              red5: xxx-bbb.duckdns.org
              useWebrtcIfAvailable: true

/opt/freeswitch/etc/freeswitch/vars.xml (FreeSWITCH)
                       local_ip_v4: 192.168.1.6
                   external_rtp_ip: stun:stun.freeswitch.org
                   external_sip_ip: stun:stun.freeswitch.org

/opt/freeswitch/etc/freeswitch/sip_profiles/external.xml (FreeSWITCH)
                        ext-rtp-ip: $${local_ip_v4}
                        ext-sip-ip: $${local_ip_v4}
                        ws-binding: :5066
                       wss-binding: :7443

/usr/local/bigbluebutton/core/scripts/bigbluebutton.yml (record and playback)
                     playback_host: xxx-bbb.duckdns.org
                 playback_protocol: https
                            ffmpeg: 4.2.2-1bbb1~ubuntu16.04

/etc/bigbluebutton/nginx/sip.nginx (sip.nginx)
                        proxy_pass: 192.168.1.6

/usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml (Kurento SFU)
                        kurento.ip: 192.168.1.6
                       kurento.url: ws://127.0.0.1:8888/kurento
                    localIpAddress: 192.168.1.6
               recordScreenSharing: true
                     recordWebcams: true
                  codec_video_main: VP8
               codec_video_content: VP8

/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml (HTML5 client)
                             build: 815
                        kurentoUrl: wss://xxx-bbb.duckdns.org/bbb-webrtc-sfu
                  enableListenOnly: true


# Potential problems described below
# IP does not match:
#                           IP from ifconfig: 192.168.1.6
#   /etc/nginx/sites-available/bigbluebutton: xxx-bbb.duckdns.org
# Warning: API URL IPs do not match host:
#
#                                IP from ifconfig: 192.168.1.6
#  /var/lib/tomcat7/demo/bbb_api_conf.jsp: xxx-bbb.duckdns.org


# Error: Unable to connect to port 1935 (RTMP) on xxx-bbb.duckdns.org

# Warning: The API demos are installed and accessible from:
#
#    https://xxx-bbb.duckdns.org
#
# and
#
#    https://xxx-bbb.duckdns.org/demo/demo1.jsp
#
# These API demos allow anyone to access your server without authentication
# to create/manage meetings and recordings. They are for testing purposes only.
# If you are running a production system, remove them by running:
#
#    apt-get purge bbb-demo

# Warning: The IMS Learning Tools Integration (LTI) is accessible from:
#
#    https://xxx-bbb.duckdns.org/lti/tool
#
# To get the access parameters for LTI, run the command
#
#    bbb-conf --lti

# Warning: You have this server defined for https, but in
#
#   /etc/bigbluebutton/nginx/sip.nginx
#
#  did not find the use of https in definition for proxy_pass
#
#            proxy_pass http://192.168.1.6:5066;
#

# Warning: You have this server defined for https, but in
#
#   /etc/bigbluebutton/nginx/sip.nginx
#
#  did not find the use of port 7443 in definition for proxy_pass
#
#            proxy_pass http://192.168.1.6:5066;
#
root@ubuntu-bbb:~/greenlight#



```

**Comment by ffdixon** [comment]
Let's keep the issues to one thread here: https://github.com/bigbluebutton/bigbluebutton/issues/8503.

Opening multiple GitHub issues (and Mattermost threads) for the same problem doesn't solve the problem faster, it just makes more work for those try to help out and solve the issue.

**Comment by srafi75** [comment]
Hi
I have same problem for error 1006 and I can not find any advise here. Could you please give me more information for this error.

**Comment by wanjauvv** [comment]
Hi,

I also got the same problem for both video and audio.
Any solution for this>?

Kind Regards

**Comment by DKabwe5** [comment]
Error: Unable to reach default URL for presentation:
#
#    https://x.x.x.x/default.pdf
#
# Check value for beans.presentationService.defaultUploadedPresentation in
#   /usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties
# Warning: You have this server defined for https, but in
#
#   /etc/bigbluebutton/nginx/sip.nginx
#
#  did not find the use of https in definition for proxy_pass
#
#            proxy_pass http://x.x.x.x:5066;
#

# Warning: You have this server defined for https, but in
#
#   /etc/bigbluebutton/nginx/sip.nginx
#
#  did not find the use of port 7443 in definition for proxy_pass
#
#            proxy_pass http://x.x.x.x:5066;

**Comment by tarafdarmansour** [comment]
Hi
I had error 1006 after some updates.
I solved my problem by editing "/etc/bigbluebutton/nginx/sip.nginx" file:
I changed 
`proxy_pass http://x.x.x.x:5066;`
to
`proxy_pass https://x.x.x.x:7443;`

I hope it works for you.

**Comment by tcg71** [comment]
The same here: after installing updates yesterday evening we got this problem too. Looks like the update sets "/etc/bigbluebutton/nginx/sip.nginx" back to defaults (and port 5066 is closed by firewall).

**Comment by DKabwe5** [comment]
Guys I need help installing on a server with two IP addresses. my domain name resolves to a public IP address, when installing bbb the domain checker finds a local IP address to which the URL doesn't resolve, the gets stuck here. I have tried installing step by step but when I change the IP address to the domain URL or public IP address I can't reach bbb on port 80 or https

**Comment by gitalm** [comment]
I had the same problem while updating from 2.2.31 to 2.2.33
The tip from tarafdarmansour didn't help but i could get it working by repeating the install script 
`wget -qO- https://ubuntu.bigbluebutton.org/bbb-install.sh | bash -s -- -w -a -v xenial-22 -s bbb.example.com -e info@example.com`

**Comment by akshayleverageedu** [comment]
You may see the error “Call timeout (Error 1006)” during the microphone echo test after starting the developing HTML5 client by “npm start”. A misconfiguration of Freeswitch may account for it, especially when BigBlueButton is set up with bbb-install.sh script. Try changing “sipjsHackViaWs” true in bigbluebutton-html5/private/config/settings.yml.

**Comment by akshayleverageedu** [comment]
If you using dev env then Try changing “sipjsHackViaWs” true in bigbluebutton-html5/private/config/settings.yml.

**Comment by ZockerBoysHD** [comment]
i have been getting erro 1006 now too.
I didnt touch the installation and it worked countless times before.
Using chrome i get an rror in the f12 consolee tho, maybe does it have someething to do with it?
https://screens.egopvp.com/files/2022/02/02/7vT3d.png

**Comment by badrow** [comment]
Same problem for me...
Solved by this : 

> Hi @Klagio I had error 1006 after some updates. I solved my problem by editing "/etc/bigbluebutton/nginx/sip.nginx" file: I changed `proxy_pass http://x.x.x.x:5066;` to `proxy_pass https://x.x.x.x:7443;`
> 
> I hope it works for you.

I dont' understand why the config was changed for another one not working...
