### ISSUE TITLE
Replace outdated browser-detect package

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#8515]
Replace the usage of `  "browser-detect": "^0.2.28",`
with the better maintained `    "react-device-detect": "^1.11.14",` introduced by @vitormateusalmeida in #8400 

This will allow us to detect iPads on iOS 13.3+ (currently not correctly detected due to incorrect userAgent)

**Comment by capilkey** [comment]
IS there a reason why we don't just use bowser? It seems to be the gold-standard for browser detection.

**Comment by vitormateusalmeida** [comment]
The main reason is IPad13 detection like bowser issue https://github.com/lancedikson/bowser/issues/329
The react-device-detect already implements that detection.
