### ISSUE TITLE
Invalid BigBlueButton Endpoint and Secret

### ISSUE THREAD

**Issue by shmelevfm** [bigbluebutton/bigbluebutton#8523]
Please. help me to understand what is wrong.
I create secret BBB and write secret and URL in .env, also I create  secret of greenlight and write it in .env.
and command 
`docker run --rm --env-file .env bigbluebutton/greenlight:v2 bundle exec rake conf:check
`
all good:

`Checking environment: Passed`
`Checking Connection: Passed`
`Checking Secret: Passed`

ssl certificate also working
BUT on home page I see error: Invalid BigBlueButton Endpoint and Secret
why?
please help!!!

**Comment by GhaziTriki** [comment]
@shmelevfm this is a help request related to https://github.com/bigbluebutton/greenlight, not an issue with https://github.com/bigbluebutton/bigbluebutton/.

Could you please follow all the steps in this documentation? https://docs.bigbluebutton.org/greenlight/gl-install.html

**Comment by shmelevfm** [comment]
2 cjmmands help me afte change bbb secret:
 docker-compose down
 docker-compose up -d

**Comment by nguyendinhdoan** [comment]
> 2 cjmmands help me afte change bbb secret:
> docker-compose down
> docker-compose up -d

Thanks shmelevfm. It works for me :)
