### ISSUE TITLE
First user message item overlap welcome message

### ISSUE THREAD

**Issue by jfsiebel** [bigbluebutton/bigbluebutton#8530]
**Describe the bug**
First user message item overlap welcome message

**To Reproduce**
1. Send a message in public chat

**Screenshots**
![image](https://user-images.githubusercontent.com/2110278/72980899-3d4eb080-3dba-11ea-9716-e4a620c87380.png)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Chrome
 - Version 79.0.3945.130

**Additional context**

**Comment by antobinary** [comment]
Introduced (and first reported) in #8522 Thanks @jfsiebel for opening an issue for it!
