### ISSUE TITLE
How to change the language for conference room?

### ISSUE THREAD

**Issue by etaddigital** [bigbluebutton/bigbluebutton#8533]
I want to change some text in conference room. what files should i edit to accomplish that?

Thanks.

**Comment by antobinary** [comment]
Hi @etaddigital 

If you want to make changes in the client look at http://docs.bigbluebutton.org/2.2/dev.html#developing-the-html5-client

The language strings are located in `bigbluebutton-html5/private/locales/` and in general the flow is: we commit to en.json the string in English and then the community helps localizing it in Transifex.
In your case you may have to add translations to the other json files in that directory.

In future please post development related questions inside the bigbluebutton-dev group, see https://bigbluebutton.org/support/community/

I will be closing this GitHub issue as it is not really representing an issue (bug) in the client
