### ISSUE TITLE
Does the current BBB API able to service native mobile apps? 

### ISSUE THREAD

**Issue by etaddigital** [bigbluebutton/bigbluebutton#8535]
I am planning to create a custom API to my customers and needs to know if the BBB API is able to serve all conference room functionality over API calls? For example: If a customer owns a native app and want to integrate BBB to their app. Is there any restriction to run it on their app or it only works if clients join a conference calls on the browser? 

Thanks in advance!

**Comment by ffdixon** [comment]
> For example: If a customer owns a native app and want to integrate BBB to their app. Is there any restriction to run it on their app or it only works if clients join a conference calls on the browser?

BigBlueButton is a HTML5 web-based application, there is no app to install.  It runs best within FireFox or Chrome.

If you want to run it within a mobile app, it's essentially running it within a webview running inside the mobile app.

On Android, the embedded webview does support WebRTC, see

  https://developer.android.com/reference/android/webkit/WebView.html

On iOS, the embedded SafariViewControl does not support WebRTC, see

  https://developer.apple.com/documentation/safariservices/sfsafariviewcontroller

This means on iOS you might get BigBlueButton client to load, but the user will not be able to send/receive any media.  On iOS, your better off launching to Safari Mobile from the app.

**Comment by etaddigital** [comment]
Dear Eng.Fred,

Would you please take a look at this issue? 
https://github.com/bigbluebutton/bigbluebutton/issues/8572

**Comment by deviprasaddayal12** [comment]
Does the latest update BBB API able to service native mobile apps?
