### ISSUE TITLE
error 1020: media cloud not reach the server server

### ISSUE THREAD

**Issue by jurado75** [bigbluebutton/bigbluebutton#8538]
install bigbluebutton in aws but the camara does not work and microphone does work 
some idea?

**Comment by prlanzarin** [comment]
Did you run through the steps detailed here https://docs.bigbluebutton.org/2.2/configure-firewall.html#updating-kurento?

**Comment by jurado75** [comment]
i dont know what is my stun server in aws
i can use default kurento setting for config my stun server?

**Comment by prlanzarin** [comment]
You can use one of Google's for testing (stun.l.google.com:19302). Ping it for the IP address beforehand and then configure it (*using the IP*) in `etc/kurento/modules/kurento/WebRtcEndpoint.conf.ini`. Then restart kurento (sudo systemctl restart kurento-media-server.
If you're going to run it in prod anytime soon, recommend setting up your own coturn server. Check https://github.com/bigbluebutton/bbb-install, it already does that.

And I do recommend reviewing the whole "server behind NAT" and firewall configuration steps in the link I mentioned above, beyond the STUN setup.

**Comment by jurado75** [comment]
ok thanks problem solve
