### ISSUE TITLE
Screen Share is not working

### ISSUE THREAD

**Issue by etaddigital** [bigbluebutton/bigbluebutton#8539]
Screenshare is not responding once click on the screen share button. Also, I tried to change lang to deduct error code of that but system is stunning! Please check out the video attached: [https://youtu.be/PceU7KKRh6A](url)

![Screenshot_2](https://user-images.githubusercontent.com/59990258/73017339-b4269080-3e30-11ea-8a66-f9b739fcac1b.jpg)

**Comment by prlanzarin** [comment]
From your video it seems you're not using HTTPS. Screenshare needs SSL in order to work.

**Comment by etaddigital** [comment]
What about changing language inside the conference room setting. It keeps flashing, any idea how to fix that?

**Comment by prlanzarin** [comment]
Have you managed to get SSL working and screen sharing running ?

`What about changing the language inside the conference room setting. It keeps flashing, any idea how to fix that?`
That area is out of my reach. Let's not pollute this issue. If you have a reproducible use case (and I see you opened a dedicated issue for the language stuff), please elaborate there with sudo bbb-conf --check and console logs.

**Comment by etaddigital** [comment]
I tried to install one but once client login, it shows this error 
![Screenshot_2](https://user-images.githubusercontent.com/59990258/73112618-540f1780-3f20-11ea-9602-b1f1a5d6cc31.jpg)
