### ISSUE TITLE
Changing language inside virtual class issue!

### ISSUE THREAD

**Issue by etaddigital** [bigbluebutton/bigbluebutton#8540]
Once tring to change language inside the virtual class, it starts flashing and not implements the order! Check out this video: [https://youtu.be/PceU7KKRh6A?t=10] (https://youtu.be/PceU7KKRh6A?t=10)

**Comment by capilkey** [comment]
Could you please post the results of "bbb-conf --check"

**Comment by etaddigital** [comment]
BigBlueButton Server 2.2.0-rc-3 (1661)
                    Kernel version: 4.4.0-171-generic
                      Distribution: Ubuntu 16.04.6 LTS (64-bit)
                            Memory: 4046 MB
                         CPU cores: 2

/usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties (bbb-web)
       bigbluebutton.web.serverURL: https://www.isync.online
                defaultGuestPolicy: ALWAYS_ACCEPT
                 svgImagesRequired: true

/etc/nginx/sites-available/bigbluebutton (nginx)
                       server name: isync.online
                              port: 808080, [::]:80
                              port: 443 ssl
                    bbb-client dir: /var/www/bigbluebutton

/var/www/bigbluebutton/client/conf/config.xml (bbb-client)
                Port test (tunnel): rtmp://www.isync.online
                              red5: www.isync.online
              useWebrtcIfAvailable: true

/opt/freeswitch/etc/freeswitch/vars.xml (FreeSWITCH)
                       local_ip_v4: 159.65.148.20
                   external_rtp_ip: stun:stun.freeswitch.org
                   external_sip_ip: stun:stun.freeswitch.org

/opt/freeswitch/etc/freeswitch/sip_profiles/external.xml (FreeSWITCH)
                        ext-rtp-ip: $${local_ip_v4}
                        ext-sip-ip: $${local_ip_v4}
                        ws-binding: :5066
                       wss-binding: 159.65.148.20:7443

/usr/local/bigbluebutton/core/scripts/bigbluebutton.yml (record and playback)
                     playback_host: www.isync.online
                 playback_protocol: https
                            ffmpeg: 4.2.1-2ubuntu1bbb3~ubuntu16.04

/etc/bigbluebutton/nginx/sip.nginx (sip.nginx)
                        proxy_pass: 159.65.148.20

/usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml (Kurento SFU)
                        kurento.ip: 159.65.148.20
                       kurento.url: ws://127.0.0.1:8888/kurento
                    localIpAddress: 159.65.148.20
               recordScreenSharing: true
                     recordWebcams: true
                  codec_video_main: VP8
               codec_video_content: VP8

/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml (HTML5 client)
                             build: 815
                        kurentoUrl: ws://192.168.1.105/bbb-webrtc-sfu
                  enableListenOnly: true


# Potential problems described below
# IP does not match:
#                           IP from ifconfig: 159.65.148.20
#   /etc/nginx/sites-available/bigbluebutton: isync.online
................................................................................
# Error: Could not connect to the configured hostname/IP address
#
#    https://www.isync.online/
#
# If your BigBlueButton server is behind a firewall, see FAQ.

# Error: Unable to connect to port 1935 (RTMP) on isync.online

# Error: Unable to reach default URL for presentation:
#
#    https://www.isync.online/default.pdf
#
# Check value for beans.presentationService.defaultUploadedPresentation in
#   /usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties
# Warning: found only 2 cores, whereas this server should have (at least) 4 CPU cores
# to run BigBlueButton in production.
#
#   https://docs.bigbluebutton.org/install/install.html#minimum-server-requirements
#
