### ISSUE TITLE
Installing SSL issue ~ Server error ((invalid endpoint and secret))

### ISSUE THREAD

**Issue by etaddigital** [bigbluebutton/bigbluebutton#8547]
Trying to installing SSL but got this error (invalid endpoint and secret). 

website: http://isync.online

![Screenshot_2](https://user-images.githubusercontent.com/59990258/73141978-b4c25f80-409a-11ea-9191-1947123d7867.jpg)

**Comment by ffdixon** [comment]
It looks like you are trying to setup Greenlight. Is it an option to try re-installing again using [bbb-install.sh](https://github.com/bigbluebutton/bbb-install) and provide parameters to configure the server with SSL (via Let's Encrypt) and setup GreenLight?
