### ISSUE TITLE
The chat performance can be further improved

### ISSUE THREAD

**Issue by capilkey** [bigbluebutton/bigbluebutton#8554]
Currently the client loops through all of the chat messages to condense messages from the same sender together. This adds unnecessary increasing load as the number of messages increases.

When a new chat message is received by the HTML5 server it should be checking the most recent chat message and determine if it's the same sender and if the time is within a certain threshold (1 min?). If the sender matches, it should flag the message as "same sender and time".

The next step is to change the chat service to no longer compress messages together on fetch.

The final step is to change the MessageListItem render to no longer loop through the sub-messages in each message. The render should not show the sender's avatar and name if the "same sender and time" flag is true. We will also want to change the fetch of user information in the message-list-item container to not fetch user data if the message is the same sender and time.

**Comment by mesutaydemir** [comment]
Hi everybody,
We're having performance issues when we enable chat module in meetings in which more than 200 participants exist. When we disable and use polling for interaction purposes, we do not have performance issue (tested with 209 concurrent user).

**Comment by capilkey** [comment]
@mesutaydemir Performance improvements are being done in the next version after 2.2. The best workaround for 2.2 is to make sure that the number of messages doesn't get too large and when it does then clear the chat.

**Comment by mesutaydemir** [comment]
Hi again,
Is there a way to auto clear chat messages through either api or a script; let's say every 1 minute? Which configuration file should be edited for this purpose?

**Comment by ffdixon** [comment]
> Is there a way to auto clear chat messages through either api or a script; let's say every 1 minute? Which configuration file should be edited for this purpose?

Such a feature would have to be written 2.2, but we are pretty much finished with this release and focusing on 2.3.  Our effort is going to be improving the performance of chat so you don't need to auto clear the chat history.

**Comment by mesutaydemir** [comment]
Fred, thank you so much for the information. Looking forward to using 2.3. Best regards

**Comment by daminebenq** [comment]
I believe that this issue is already solved in #11173.
And just to confirm #11173 did focus only 2.3.

**Comment by prlanzarin** [comment]
@daminebenq: so, question: do you have public data about the impacts of #11173?
As in: server-side and client-side CPU usage, memory usage, bandwidth usage, ..., preferably with a comparison with the previous state of things.

**Comment by pedrobmarin** [comment]
@prlanzarin maybe we should close this issue because seems a little outdated and open something else requesting a stress test comparison between v2.2 and v2.3 chat performance since https://github.com/bigbluebutton/bigbluebutton/pull/11173 didn't provide such analysis (as far as I know).

**Comment by prlanzarin** [comment]
sure.

**Comment by Tainan404** [comment]
Anton asked me to make a report on the improvement of the chat compared to 2.2, to make it easy to compare, I made some videos with the client receiving one hundred thousand messages and another loading the client with thirty thousand messages (due to the 2.2 client not able to load more than that)

Receiving messages:

2.3: 

https://user-images.githubusercontent.com/15806883/115235951-26982600-a0f1-11eb-9c15-7644c10b14cb.mp4

2.2: (the 2.2 client was unable to receive a hundred thousand messages, so I waited up to 10 minutes to see how much it is capable of rendering)

https://user-images.githubusercontent.com/15806883/115236033-43345e00-a0f1-11eb-8182-870cfc9d8b76.mp4



Reloading:

2.3:

https://user-images.githubusercontent.com/15806883/115236312-9c03f680-a0f1-11eb-8389-1d82e964d3cc.mp4

2.2:


https://user-images.githubusercontent.com/15806883/115236358-ab833f80-a0f1-11eb-8346-6cf2cc70b8f4.mp4

**Comment by Tainan404** [comment]
Also I recorded some videos using the chrome tab task manager to show the process use.

2.3:

https://user-images.githubusercontent.com/15806883/115282102-2b280300-a120-11eb-9540-57965cf2656d.mp4

2.2:

https://user-images.githubusercontent.com/15806883/115282120-30854d80-a120-11eb-88ef-f4b0a2938781.mp4

For some reason unknown in 2.2, the chat stops updating after 10k messages and the usage of the process drops to zero

**Comment by antobinary** [comment]
Thanks @Tainan404 !
