### ISSUE TITLE
Exception when trying to toggle the mute

### ISSUE THREAD

**Issue by capilkey** [bigbluebutton/bigbluebutton#8559]
**Describe the bug**
An exception is being thrown when trying to toggle microphone mute on a user that doesn't have a VoiceUser.

**To Reproduce**
The reproduction steps are unknown at this time.

**Stack trace**
```
TypeError: Cannot read property 'muted' of undefined
    at m meteor_js_resource=true:125:686401)
    at handleToggleMuteMicrophone meteor_js_resource=true:125:625899)
    at d.validateDisabled meteor_js_resource=true:125:724149)
    at d.internalClickHandler
    ....
```
I'm pretty sure `m` is `toggleMuteMicrophone` in AudioService and it's caused by trying to toggle the user's microphone mute while there's no VoiceUser. It's unclear why the button is clickable if there's no VoiceUser, but we can at least add extra protections and potentially log when it fails.

**Comment by GhaziTriki** [comment]
Too old. Closing.
