### ISSUE TITLE
Add an avatar image URL to the join API call for a user

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#8566]
**Is your feature request related to a problem? Please describe.**
Add the `avatarURL` URL for the HTML5 client.

**Describe the solution you'd like**
The Avatar image should appear in the User's list for the user instead of the icon with the first two letters in their name.

**Comment by ic-armando-1992** [comment]
It is implemented in the HTML5 Cliente or not?? because i sent the AvataraURL but does not display

**Comment by ConfMe** [comment]
It would be great to have this feature in html!

**Comment by tobka777** [comment]
Can you please implement this feature? Thank you!

**Comment by antobinary** [comment]
Related https://github.com/bigbluebutton/bigbluebutton/pull/3090

**Comment by miromer** [comment]
Anything on this it would be great thing to have from my experience it would be the first question in a demo meeting,,,and the answer would be ahh well ohh...

**Comment by mardif** [comment]
are there any chances to get this feature for html5 client?

**Comment by YoniMeidan** [comment]
This is very much needed.

**Comment by im-asad** [comment]
Need this feature on HTML5 client. Would appreciate BBB teams pushing this forward.

**Comment by ugurguray** [comment]
Dear sir. We will be very appreciated if you can implement this. In a class it is very important for Teacher to understand which student interacting. And a correct visual is best to remember the student. Regards.

**Comment by amguirado73** [comment]
Hello,

Could you confirm if finally this feature is implemented?. Can we user avatarURL parameter in API to reference to a external image for the user?.

Thanks

**Comment by matiasilva** [comment]
Hi folks. If you have tested it and it doesn't work, it means it's not implemented. I'm not sure if the dev team is working on implementing this, but if you really need this feature then reach out to the companies providing commercial support (https://bigbluebutton.org/commercial-support/), otherwise attempt to implement it in a PR.
