### ISSUE TITLE
functionality issues

### ISSUE THREAD

**Issue by cvuva** [bigbluebutton/bigbluebutton#8568]
We have the bigbluebutton 2.2-RC-5 server installed on an Ubuntu 16.0.4 server and the corresponding module v2.3.1 bigbluebuttonbn on a moodle 3.6.x. We use Firefox exclusively for all module functionality. We have the range of open ports that are needed as well as the specific recommended ports for video conferencing and recording.

Testing with the URL http://test-install.blindsidenetworks.com/bigbluebutton/ and https://demo.bigbluebutton.org/ everything works correctly but if we configure the URL of our server we find some problems that we could not solve:

• Error 1020 sometimes occurs: media server cannot be reach
• Error 1108 sometimes occurs: ICE connection failed when sharing screen
• When we manage to share the screen we see that the effect of infinite windows always occurs

Any idea what to check to correct these problems?

Thank you.

**Comment by ffdixon** [comment]
> • When we manage to share the screen we see that the effect of infinite windows always occurs

That is normal (and it shows that screen share is working correctly).

> • Error 1020 sometimes occurs: media server cannot be reach
> • Error 1108 sometimes occurs: ICE connection failed when sharing screen

Are there users that consistently get these messages?   Are you able to reproduce this issues when connecting to your BigBlueButton server.

Can you post the output of `sudo bbb-conf --check` (you can mask out the hostname).

**Comment by cvuva** [comment]
Yes, it happens from time to time to different users when you try to share your camera or screen.

When we connect the moodle module to https://test-install.blindsidenetworks.com/bigbluebutton/ repeatedly we never get these error messages

Our bbb-conf --check:

BigBlueButton Server 2.2.0-rc-1 (1569)
                    Kernel version: 4.4.0-169-generic
                      Distribution: Ubuntu 16.04.6 LTS (64-bit)
                            Memory: 8174 MB
                         CPU cores: 4

/usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties (bbb-web)
       bigbluebutton.web.serverURL: https://bbb2campusvirtual.uva.es
                defaultGuestPolicy: ALWAYS_ACCEPT
                 svgImagesRequired: true

/etc/nginx/sites-available/bigbluebutton (nginx)
                       server name: bbb2campusvirtual.uva.es
                              port: 80, [::]:80
                              port: 443 ssl
                    bbb-client dir: /XXX/XXX/bigbluebutton

/var/www/bigbluebutton/client/conf/config.xml (bbb-client)
                Port test (tunnel): rtmp://bbb2campusvirtual.uva.es
                              red5: bbb2campusvirtual.uva.es
              useWebrtcIfAvailable: true

/opt/freeswitch/etc/freeswitch/vars.xml (FreeSWITCH)
                       local_ip_v4: XXX.XXX.XXX.XXX
                   external_rtp_ip: stun:stun.freeswitch.org
                   external_sip_ip: stun:stun.freeswitch.org

/opt/freeswitch/etc/freeswitch/sip_profiles/external.xml (FreeSWITCH)
                        ext-rtp-ip: $${local_ip_v4}
                        ext-sip-ip: $${local_ip_v4}
                        ws-binding: :5066
                       wss-binding: :7443

/usr/local/bigbluebutton/core/scripts/bigbluebutton.yml (record and playback)
                     playback_host: bbb2campusvirtual.uva.es
                 playback_protocol: https
                            ffmpeg: 4.1.3-0york1~16.04

/etc/bigbluebutton/nginx/sip.nginx (sip.nginx)
                        proxy_pass: XXX.XXX.XXX.XXX

/usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml (Kurento SFU)
                        kurento.ip: XXX.XXX.XXX.XXX
                       kurento.url: ws://127.0.0.1:8888/kurento
                    localIpAddress: XXX.XXX.XXX.XXX
               recordScreenSharing: true
                     recordWebcams: true
                  codec_video_main: VP8
               codec_video_content: VP8

/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml (HTML5 client)
                             build: 775
                        kurentoUrl: wss://bbb2campusvirtual.uva.es/bbb-webrtc-sfu
                  enableListenOnly: true


# Potential problems described below
# Warning: API URL IPs do not match host:
#
#                                IP from ifconfig: XXX.XXX.XXX.XXX
#  /var/lib/tomcat7/demo/bbb_api_conf.jsp: bbb2campusvirtual.uva.es

....................# Error: Red5 log files not found

# Unavailable red5 logs (/usr/share/red5/log):  screenshare-slf.log


# Warning: The API demos are installed and accessible from:
#
#    https://bbb2campusvirtual.uva.es
#
# and
#
#    https://bbb2campusvirtual.uva.es/demo/demo1.jsp
#
# These API demos allow anyone to access your server without authentication
# to create/manage meetings and recordings. They are for testing purposes only.
# If you are running a production system, remove them by running:
#
#    apt-get purge bbb-demo

**Comment by ffdixon** [comment]
Would recommend that you also setup a TURN server, see

  http://docs.bigbluebutton.org/2.2/setup-turn-server.html

and

  https://github.com/bigbluebutton/bbb-install#install-a-turn-server

**Comment by cvuva** [comment]
Our firewall is open for the range of UDP ports mentioned in the documentation. Also, camera or screen sharing sometimes fails, not always. Isn't this proof that we don't need a STUN server for NAT? 

In addition, the server where BBB 2.2 resides has a single interface and the DNS resolves the domain bigbluebutton2.uva.es with the IP associated with that single interface. However, on the page https://kurento.readthedocs.io/en/stable/doc/admin_guide.html#installation it seems that we can use some IPs for this purpose by configuring some of them in / etc / kurento / modules / kurento / WebRtcEndpoint.conf.ini to ensure the use of a STUN server. Apart from not using a STUN server (we will configure it from IPs provided by kurento), is there any other problem that causes the mentioned errors to be able to review it?

**Comment by capilkey** [comment]
I can connect to your server with audio and video fine. Your server is sending the correct candidate(s) also so it doesn't need further STUN configuration in the server files.

The TURN server that @ffdixon mentioned is for the client to use if it's behind a restricted network which it might be in your case. I would connect to audio and video on a test-install server and check about:webrtc to see if the candidate that is selected is the relay candidate (TURN candidate).
