### ISSUE TITLE
Could not find recording!

### ISSUE THREAD

**Issue by etaddigital** [bigbluebutton/bigbluebutton#8570]
Hi,
Before 3 hours ago, finished a class. The lecture duration up to 3 hours
When tutor sign in as administrator and lunch the class I notice he forgot to start recording. So, I sign in with the same credential and our username was duplicated inside the class but I could start recording successfully. However, after the end meeting, I could not find any recording at recording section! 

![Screenshot_1](https://user-images.githubusercontent.com/59990258/73401261-dbcb9c00-42fb-11ea-9d58-28cf2775c551.jpg)

**Comment by ffdixon** [comment]
How long ago did the meeting finish?  It sometimes takes a few hours to generate recordings (depending on the server load).

**Comment by etaddigital** [comment]
Class duration is 3 hours!

**Comment by ffdixon** [comment]
You need to be a Moderator to start/stop recording.  Are you launching from Moodle? Can you try logging in with the same credentials, then starting a meeting, and see login as moderator.

Moderators have square avatars, viewers have circular avatars.

**Comment by etaddigital** [comment]
Yes I found it be it take about 20 hours to apear at recording section.
However, I am trying to download the entire lecture as mp4 but once I click
on (video camera window) it just download that part not downloading it will
the presentation! Here is the link:
https://skits.cc/38Lj0dk

**Comment by ffdixon** [comment]
The recording format is a synchronized playback of videos (webcams and screen share), audio, slides (SVG + Javascript), and chat (HTML5).  It plays back in the browser but isn't downloadable as a single file.

There is an open issue for creating a downloadable video of the recording: #1969

**Comment by etaddigital** [comment]
> How long ago did the meeting finish? It sometimes takes a few hours to generate recordings (depending on the server load).

Dear Fred,

Based on your experience what's the best server provider and plan do you recommend with BBB and can rendering recording fast and with no issue on audio and video.

**Comment by ffdixon** [comment]
There are a list of companies at our web site that can provide commercial hosting for BigBlueButton (we recommend all of them :-), see

  https://bigbluebutton.org/commercial-support/

**Comment by etaddigital** [comment]
> There are a list of companies at our web site that can provide commercial hosting for BigBlueButton (we recommend all of them :-), see
> 
> https://bigbluebutton.org/commercial-support/

I did not notice Amazon AWS, is there any issue with them?

**Comment by ffdixon** [comment]
Hmm, we misunderstood what you were asking for.  You were looking for recommendations on hosting providers for servers, not hosting providers for BigBlueButton.  

This really isn't an "issue" with BigBlueButton, but rather a general question.  Can you post this to our bigbluebutton-setup mailing list, that's a better way to engage the community.  See

  https://bigbluebutton.org/support/community/
