### ISSUE TITLE
Enable PDF and ODF options for exporting shared notes.

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#8571]
**Describe the bug**
This looks like a regression for 2.2-RC5.  Need to re-enable these options.

**Comment by rriscado** [comment]
Exists any parameters that dynamically enable the exported file formats?

**Comment by ffdixon** [comment]
The export options are set here

~~~
/usr/share/etherpad-lite/src/templates/pad.html
~~~

You can try modifying that file to see if you can get the other options present.

**Comment by toushin-taishi** [comment]
Dear Fred, 
What needs to be modified in /usr/share/etherpad-lite/src/templates/pad.html to enable the other format options in export? I also experienced the same thing in etherpad wherein only HTML and TXT formats are available but the file that I edited for the other format to be show is  /usr/share/etherpad-lite/settings.json.

**Comment by ljoets** [comment]
Hi,
To activate doc, pdf and odf export, you juste have to : 

`apt install abiword`
in `/usr/share/etherpad-lite/settings.json` file
replace `"abiword": null,` wiith `"abiword": "/usr/bin/abiword",`
`bbb-conf --stop`
`bbb-conf --start`

**Comment by mabeyj** [comment]
Changing this setting in `/usr/share/etherpad-lite/settings.json` also works, and it uses LibreOffice which is already installed:

```diff
"soffice": "/usr/bin/soffice",
```

Perhaps this change is the cause? https://github.com/bigbluebutton/etherpad-lite/commit/3c127a03807add1deb6754cf1a17349deaa9fc68#diff-8ab11a170627f11a32a1d642d7114743L224

Not sure how it was set before, but it seems like this could cause a simple find/replace to stop working.

**Comment by hex-m** [comment]
I think this is solved because of the linked [PR](https://github.com/bigbluebutton/etherpad-lite/pull/4).
