### ISSUE TITLE
iphone xs no sound issue!

### ISSUE THREAD

**Issue by etaddigital** [bigbluebutton/bigbluebutton#8572]
Hi,

Today some of students report us about iphone is sound is not working with them ever after sound setup! I tested that by myself and I noticed the same issue. Any idea how to fix that? 

youtube: https://youtu.be/XIrWDunlnXg

**Comment by capilkey** [comment]
I think this is the same as #6591.

**Comment by etaddigital** [comment]
> I think this is the same as #6591.

Yes, it's same issue! Also, I notice that IOS clients can not playback the recording video from chrome!

**Comment by capilkey** [comment]
Chrome on iOS is just a reskinned Safari. In order for recordings to playback you have to create MP4 videos for the recordings.

**Comment by capilkey** [comment]
Sorry the correct issue is #8133

**Comment by etaddigital** [comment]
> Chrome on iOS is just a reskinned Safari. In order for recordings to playback you have to create MP4 videos for the recordings.

Is that mean I have to download it and do video editing or is that a feature I have to do to activate/allow into recoding video to playback it on the browser?

**Comment by capilkey** [comment]
There's a configuration option, http://docs.bigbluebutton.org/2.2/customize.html#enable-playback-of-recordings-on-ios.

**Comment by ffdixon** [comment]
Merging this issue into  #8133

**Comment by etaddigital** [comment]
Hi,

I just end a call with Apple support and informed them I have two iPhones 
- iPhone 6+ (12.4.4)
- iPhone xs (13.3.1) 

For (6+) no issue about speaker sound at all but for (xs) no speaker sound.  

They informed me WebRTC is not fully supported for all ios and they told me if you want from us to report that to our developer we need a confirmation form web app developer about that technology is not restricted to any ios devices and support all ios devices. After that they will examine it and fix it with next update!
