### ISSUE TITLE
Perform echo test (room) 24/7 without an actual conference active

### ISSUE THREAD

**Issue by otdftr** [bigbluebutton/bigbluebutton#8574]
We would like to provide an easy way for users to test their audio and conference equipment well ahead of a conference. 

Still, it seems to me that an echo test is only possible during the procedure of joining an actual session. So presently be provided a machine which has our "test conference" room open and the audio conference on (to allow for POTS dial ins) - this has to be checked manually on a regular basis, and starting the conference can no be automated 

We think it would be nice to have a test room that exists on the server without an active conference. So users could check the URL, the firewall, the audio equipment (echo test)  with the given test URL independent of a real and existing conference id. 
This test room should require now admin / support interaction, it should merely require a configuration option to enable it on the server (and possibly to provide a custom URL).

We didn't find any means for this in BBB 2.2, I hope we didn't miss something...

**Comment by ffdixon** [comment]
I think you could put something together with the demo1.jsp test API.  When joining through the landing page, it calls demo1.jsp and joins with a meeting called "Demo Meeting", see

https://github.com/bigbluebutton/bigbluebutton/blob/master/bbb-api-demo/src/main/webapp/demo1.jsp#L91

which says

~~~
String joinURL = getJoinURL(request.getParameter("username"), "Demo Meeting", "false", null, null, null);
~~~

If you added a random five digit number to this, such as

~~~
        Random rand = new Random();
        String joinURL = getJoinURL(request.getParameter("username"), "Test Room - " + (rand.nextInt(90000) + 10000), "false", null, null, null);
~~~

then every user will go into their own individual 'Test Room'.

**Comment by otdftr** [comment]
Thanks for pointing me to https://github.com/bigbluebutton/bigbluebutton/blob/master/bbb-api-demo/src/main/webapp/demo1.jsp#L91,
I'll check it out.

**Comment by otdftr** [comment]
Dear Fred,

as I am not an experienced java developer, I chose another route for our Test Room - a shell script that is run through CGI. So I can avoid further dependencies and the leaking of the securitySalt in case of a server misconfiguration.
 
Below jou can find the script (not elegant, but leightweight) and nginx config snippet - feel free to use, share, integrate.
````
#!/bin/bash

# /srv/cgi-bin/get_personal_BBBroom.sh
#
# create personal & private test room in BBB
# and return "join" link to join as moderator
# (allows user to test screen sharing etc.)
# use 302 temp. redirect to forward client to its personal test session

# written by
# olaf schott <devel@osx.de>
# 2020-04-10


# no dependencies like php and perl
# needs openssl, curl, sha1sum
# and fcgiwrap for nginx

BBBAPI="https://your.bbbserver.here/bigbluebutton/api"
APIKEY=$( grep -i '^\s*securitySalt=' /usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties )
APIKEY=${APIKEY##*securitySalt=}

# all params URLencoded ... use an online service like https://www.urlencoder.org/
# TESTROOM="CAMPUS live: Ihr Testraum"
TESTROOM="CAMPUS%20live%3A%20Ihr%20Testraum"
TESTMAXSEATS=2
TESTDURATION=8
# TESTLOGOUTURL="https://your.other.server.here"
TESTLOGOUTURL="https%3A%2F%2Fyour.other.server.here"
TESTMEETID=$(openssl rand -hex 12)
TESTMODPW=$(openssl rand -hex 12)

CREATEQUERY="name=${TESTROOM}&meetingID=${TESTMEETID}&maxParticipants=${TESTMAXSEATS}&duration=${TESTDURATION}&logoutURL=${TESTLOGOUTURL}&moderatorPW=${TESTMODPW}"
CREATECHECKSUM=$( echo -n "create${CREATEQUERY}${APIKEY}" | sha1sum | cut -d " " -f 1 )

# create
curl -s "${BBBAPI}/create?${CREATEQUERY}&checksum=$CREATECHECKSUM" > /dev/null || exit 1

JOINQUERY="fullName=Moderator&meetingID=${TESTMEETID}&password=${TESTMODPW}"
JOINCHECKSUM=$( echo -n "join${JOINQUERY}${APIKEY}" | sha1sum | cut -d " " -f 1 )

# return CGI formatted redirect
cat - <<EOF
HTTP/1.1 302 Moved Temporarily
Content-Type: text/html
Location: ${BBBAPI}/join?${JOINQUERY}&checksum=$JOINCHECKSUM

EOF


#########################
#                       #
# nginx config snippet  #
#                       #
#########################
#
#
#        # Testraum
#        location ~* /echotest/? {
#           root /srv/cgi-bin/ ;
#           # have fastcgiwrap installed!
#           include fastcgi_params ;
#           fastcgi_param SCRIPT_FILENAME /srv/cgi-bin/get_personal_BBBroom.sh ;
#           fastcgi_pass unix:/run/fcgiwrap.socket ;
#        }
#

````
