### ISSUE TITLE
Safari and iOS Safari - Implement Screen Capture API

### ISSUE THREAD

**Issue by aogilvie** [bigbluebutton/bigbluebutton#8576]
This is to track screen sharing in Appleland.

Current status of getDisplayMedia() - https://developer.mozilla.org/en-US/docs/Web/API/Screen_Capture_API

However, tested Safari Technical Preview v99 Jan 20th on Mac 10.14, and seems like it is all there!

So this is a ticket to chase implementing screen sharing on Safari products :sparkles:

**Comment by aogilvie** [comment]
Ticket closed means it is shipped?
What version of Safari is needed?
What version of bigbluebutton is needed?
Thanks.

**Comment by prlanzarin** [comment]
@aogilvie it has been integrated into the v2.2.x branch. Next release should have it (we're now on 2.2.11, so 2.2.12 I believe).
>  What version of Safari is needed?

Safari 13+, macOS. I don't think Apple implemented screen capture on iOS. If they didn't, the code should be ready for it once they do their stuff.

**Comment by ffdixon** [comment]
Can you try it out on https://test.bigbluebutton.org/ with Safari and let us know if you can share your screen.

**Comment by aogilvie** [comment]
@prlanzarin thanks!
Thanks Fred, I'll test.

**Comment by christmart** [comment]
I just tested it on my iPad with iPad-OS 13.5 and screensharing with Safari is not working.

**Comment by ffdixon** [comment]
The mobile browsers -- Chrome Mobile and Safari Mobile -- do not implement the screen sharing APIs.

That means you won't be able to share your screen using Safari Mobile on your iPad or iPhone.  The latest updates should enable screen sharing on Safari desktop.

**Comment by snack753** [comment]
Hi all,
stumbled upon this today.
I am also having issues sharing my screen through BBB on an iPad. currently on iOS 13.6.1 with latest BBB test-system. 
The corresponding button shows up, shower shows me that screen sharing is not supported in the browser.

**Comment by matiasilva** [comment]
That's probably because Safari on iPadOS makes websites think it's a desktop but since iPadOS is just an extension of iOS it uses the same mobile Safari.

**Comment by snack753** [comment]
Is there any solution ahead?

________________________________
Von: Matias Silva <notifications@github.com>
Gesendet: Monday, September 21, 2020 8:53:32 PM
An: bigbluebutton/bigbluebutton <bigbluebutton@noreply.github.com>
Cc: Kai <kai.niethammer@gmail.com>; Comment <comment@noreply.github.com>
Betreff: Re: [bigbluebutton/bigbluebutton] Safari and iOS Safari - Implement Screen Capture API (#8576)


That's probably because Safari on iPadOS makes websites think it's a desktop but since iPadOS is just an extension of iOS it uses the same mobile Safari.

**Comment by prlanzarin** [comment]
No. You'll have to ask the webkit developers on that.
It's not up to us to make iOS/iPadOS Safari support `getDisplayMedia`. It's up to the browser vendors.

Only way around that right now is making a native app which uses the native WebRTC library and does
screen capture on its own (via ReplayKit), which we don't have (and is not on the roadmap AFAIK).

**Comment by snack753** [comment]
Okay, thanks for your replies. 

Sent from my KaiPhone

Am 21.09.2020 um 21:01 schrieb Paulo Lanzarin <notifications@github.com>:

﻿
No. You'll have to ask the webkit developers on that.
It's not up to us to make iOS/iPadOS Safari support getDisplayMedia. It's up to the browser vendors.

Only way around that right now is making a native app which uses the native WebRTC library and does
screen capture on its own (via ReplayKit), which we don't have (and is not on the roadmap AFAIK).

**Comment by sakeenashahid** [comment]
I'm facing a similar issue. BBB does not let me share my iPad screen (iOS 14.2). Any updates?

**Comment by ffdixon** [comment]
See comment above -- as soon as Apple supports the webRTC calls for `getDisplayMedia`, we can provide support for screen sharing on iPad.  Believe us, we want to do it.

**Comment by aogilvie** [comment]
We still here with sad faces in 2023, but I thought I would share this link for those also waiting/hoping...
https://caniuse.com/?search=getDisplayMedia
