### ISSUE TITLE
Loosing speaker audio after switching language 

### ISSUE THREAD

**Issue by jcherrabi** [bigbluebutton/bigbluebutton#8582]
**Describe the bug**
When switching from one language to another while in a conf call, we loose the speaker and no longer can hear the other party. But mic still works and they can hear us! To fix one has to leave the call and reconnect again!

**To Reproduce**
1. Go to '.profile..'
2. Click on '...language .'
3. Scroll down to '....choose another language and hit save'
No longer can hear anyone’s voice

**Expected behavior**

**Actual behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser [Chrome

**Comment by capilkey** [comment]
Same issue as reported in #8410

**Comment by antobinary** [comment]
Merge into #8410

**Comment by emadbagheri96** [comment]
Well it still does and only switching back to English fixes it.
