### ISSUE TITLE
Html5 missing full screen button on iPhone ios

### ISSUE THREAD

**Issue by jcherrabi** [bigbluebutton/bigbluebutton#8583]
**Describe the bug**
I cannot make the presentation full screen while connected from an iPhone iOS 13.3, I only have the minimize button and no full screen! Is this a bug? The button or icon is available from Android phone.

**Comment by jcherrabi** [comment]
![0CB4351C-BA0B-4CA9-916A-9AD371417376](https://user-images.githubusercontent.com/5914393/73583358-fcc5f580-4491-11ea-9499-71c0f38ed9fa.jpeg)
![13133AD1-4357-4589-AE58-964FDF5CC172](https://user-images.githubusercontent.com/5914393/73583359-fcc5f580-4491-11ea-8139-a86fcaad2c48.jpeg)

**Comment by antobinary** [comment]
Hi @jcherrabi 

>Is this a bug?
It's not a bug. Apple doesn't support this API, so we have had to filter which devices we can use it on. If in the future the API becomes available we will adjust this
