### ISSUE TITLE
Improve flexibility of camera layouts

### ISSUE THREAD

**Issue by jcherrabi** [bigbluebutton/bigbluebutton#8584]
**Describe the bug**
The visual aspect of things are fixed and do not give a great user experience, see how things look on an iphone 8 ios 13.3 using Safari. if you noticed the camera takes up too much space on top and the button oat the botton take up more real estate, leaving the presentation area tiny.. see screenshots below.

Why not make the camera and the buttons live on its floating Div layer on top of the presentation while on Portrait mode, and once a person flips the phone to landscape mode the camera needs to be hidden as going landscape mode means i want to view the presentation in full screen. in that mode we can show a tiny icon of the status of our mic or something else that once clicked can bring back the buttons...
![bbb1](https://user-images.githubusercontent.com/5914393/73590909-87d1da80-44e8-11ea-9ba3-e7410ef25232.jpg)
![bbb2](https://user-images.githubusercontent.com/5914393/73590912-8a343480-44e8-11ea-8381-1dc46246aed1.jpg)
![bbb3](https://user-images.githubusercontent.com/5914393/73590927-a2a44f00-44e8-11ea-8c90-b09f9bed962a.jpg)
![bbb4](https://user-images.githubusercontent.com/5914393/73590928-a7690300-44e8-11ea-8014-4caaa50c4775.jpg)

here is how MS Teams shows it, which i think is more ituitive and give back the important real estate to the presentation.

![Teams04 1](https://user-images.githubusercontent.com/5914393/73590981-4c83db80-44e9-11ea-942f-91792baeafb9.jpg)

I hope this helps..
Jay

**Comment by ffdixon** [comment]
We're working on improving the layout of webcams in BigBlueButton 2.3 (the next release) to include left/right layouts.  

Here's a screen shot I took of BigBlueButton 2.3-dev running on my browser on my laptop.

I made the window a similar aspect ratio to landscape viewing on a device.

![image](https://user-images.githubusercontent.com/290351/73593653-6f57c500-44d4-11ea-9964-304d97a7c591.png)

The plan is to allow users on the desktop to drag-and-drop the webcams to the left, right, top, or bottom, and users on mobile devices to automatically place the webcams (top/left) where it makes the presentation layout the largest.

See also #7850.

**Comment by maychine-fatima** [comment]
Thank you for the layouts fixes, i have one issue is that the camera  can't be placed on right, it's working  just on left.

**Comment by ffdixon** [comment]
Can you try it on https://test23.bigbluebutton.org/ (this has the latest builds of 2.3-dev).  You can place your camera on the right.

**Comment by maychine-fatima** [comment]
Hello, thank you ,it's working , i have updated it.
