### ISSUE TITLE
error with npm start after a fresh install of the dev v2.2.x.release

### ISSUE THREAD

**Issue by jcherrabi** [bigbluebutton/bigbluebutton#8585]
followed the instruction http://docs.bigbluebutton.org/2.2/dev.html and right after i executed npm start i got the following error.

While processing files with nathantreid:css-modules (for target web.browser):
   /home/ubuntu/dev/bigbluebutton/bigbluebutton-html5/node_modules/node-sass/lib/binding.js:15:13: Missing binding
   /home/ubuntu/dev/bigbluebutton/bigbluebutton-html5/node_modules/node-sass/vendor/linux-x64-72/binding.node
   Node Sass could not find a binding for your current environment: Linux 64-bit with Node.js 12.x

so i searched around and found many suggestions, most point to the fact that i should have meteor version 1.8 instead v1.9 so i updated it to version 1.8 and got a different error then i executed npm update  and then  meteor update --release 1.8 which solved the issue...

not sure wht meteor 1.9 gets installed when it is not compatible with Node.js 8 and looks for Node.js 12.x

**Comment by antobinary** [comment]
Hi @jcherrabi 
BBB 2.2 HTML5 client works with Node 8 and Meteor 1.8. Please navigate to the source code of the HTML5 client and run `  meteor update --allow-superuser --release 1.8 ` This command will ensure your Meteor remains 1.8.

Thank you for reporting this -- Meteor set version 1.9 to be installed by default but when we were writing the HTML5 docs version 1.8 was the default. I have now updated the docs http://docs.bigbluebutton.org/2.2/dev.html#developing-the-html5-client
