### ISSUE TITLE
Ring a small notification to all the class

### ISSUE THREAD

**Issue by GhaziTriki** [bigbluebutton/bigbluebutton#8587]
**Is your feature request related to a problem? Please describe.**
BigBlueButton is being used for memorisation courses. To test the student memorisation the teacher cannot interrupt the student with a single word. However he should be able to warn him if he did a mistake when reciting the memorised text.

**Describe the solution you'd like**
The solution to this issue could be similar to the method used in real classes. The teacher could click on a button with dull bell sound. Any custom sound notification that could triggered with a button would do the job.

**Describe alternatives you've considered**
Nothing.

**Additional context**
Nothing.

**Comment by ritzalam** [comment]
I think this would be a sufficient solution to this. The ring will be picked by teacher's mic. To dull the sound, a cloth can be put inside.

![push-bell](https://user-images.githubusercontent.com/184672/73615854-fe9ad080-45d9-11ea-91d8-a00dfa886344.PNG)

**Comment by ritzalam** [comment]
Unless a recording event is necessary to be used in the recording processing later such as for reports.

**Comment by GhaziTriki** [comment]
The event might be useful for exams. Depending on the type of exam, the number of errors of memorisation put in the class report is important.

**Comment by GhaziTriki** [comment]
Please consider this request as obsolete.
