### ISSUE TITLE
any suggestions for live webcast the whole bbb meeting room ?

### ISSUE THREAD

**Issue by dancinglone** [bigbluebutton/bigbluebutton#8593]
User case: 
I want the meeting room for several teachers could be show to the teachers or students of the whole school 

The solution I'd like :
1. rtmp stream api for webcast ?
2. some development suggestion for me?

**Comment by ffdixon** [comment]
We actually have broadcasting BigBlueButton as an RTMP stream in this issue #8295.

For now, you could use OBS to broadcast the screen of your BigBlueButton session via RTMP to a CDN.

We currently recommend BigBlueButton for sessions of 100 users (or less).  If you need to have larger sessions, we recommend using a tool like OBS or splitting the sessions into smaller groups.

**Comment by dancinglone** [comment]
Thanks for replying !
But OBS is a little complex for some teachers to use, any solutions without downloading and setting up an extra application?

**Comment by ffdixon** [comment]
Not that I know of -- but we hope to provide you such a solution within BigBlueButton at some point in the future.

**Comment by dancinglone** [comment]
As I know, there's  a Chinese product called XYLink (http://xylink.us/ ; https://www.xylink.com/), which cloud have meeting between about hundreds of  guys ( in the desktop app、mobile app 、 wechat mini program that base on similar technology stack with BS h5 app) and broadcast the meeting to a large amount of guys( in BS h5 app).   But it's not open source.  I think we could learn about how it realize the broadcast and refer to the technology stack.

**Comment by ffdixon** [comment]
Thanks -- we have a pretty good idea of how to do this in BigBlueButton with only open source components.  It's just a matter of prioritizing it over other features.  See  http://docs.bigbluebutton.org/support/faq.html#when-will-feature-x-be-implemented.

**Comment by matiasilva** [comment]
Closing to merge all issues about live streaming to #8295.
