### ISSUE TITLE
Webcam and Screenshare does not work on non-standard ssl port over NAT

### ISSUE THREAD

**Issue by fillorkill** [bigbluebutton/bigbluebutton#8594]
**Describe the bug**
**Network:**
**BBB Server (private-ip)-> NAT Firewall (public_ip)-> Internet -> Client**
Server is running on non-standard port, firewall SSL port is non standard too. They are dst-NAT correctly and I access the server by appending :1234 to the url, i.e. https://bbb.xxx.com:1234. 

I managed to get Audio to work by adding a port number in the .js file under /usr/share/meteor/bundle/programs/web.browser

TURN server is set up correctly and appears to be working.
`https://bbb.xxx.com:1234/html5client/join?sessionToken=9g50tl0oc7pxtw8i, { iceServers: [stun:gateway-01.yyy.com, turn:gateway-la01.yyy.com], iceTransportPolicy: all, bundlePolicy: balanced, rtcpMuxPolicy: require, iceCandidatePoolSize: 0, sdpSemantics: "unified-plan" }`

Webcam and Screensharing do not work when I access bbb from an external network.

As the presenter, whenever I try to screenshare I get these error messages and also Error 1108:
`[13:29:43:0926]  INFO: clientLogger: Screenshare presenter started succesfully https://bbb.xxx.com:1234/html5client/8f4e1ec1690e5c2a0a9c67253c4dbd26888c06ca.js?meteor_js_resource=true:125:1177574 8f4e1ec1690e5c2a0a9c67253c4dbd26888c06ca.js:9:342266`

`ICE failed, your TURN server appears to be broken, see about:webrtc for more details`

`[13:29:56:0804] ERROR: clientLogger: WebRTC peer for screenshare presenter failed due to ICE transitioning to failed https://bbb.xxx.com:1234/html5client/compatibility/kurento-extension.js?v=829:492:21 8f4e1ec1690e5c2a0a9c67253c4dbd26888c06ca.js:9:342266`

`[13:29:56:0805] ERROR: clientLogger: Screenshare presenter failed during working session due to iceConnectionStateError https://bbb.xxx.com:1234/html5client/8f4e1ec1690e5c2a0a9c67253c4dbd26888c06ca.js?meteor_js_resource=true:125:1175062 8f4e1ec1690e5c2a0a9c67253c4dbd26888c06ca.js:9:342266`

`[13:29:56:0807]  INFO: clientLogger: Exiting screensharing as presenter https://bbb.xxx.com:1234/html5client/compatibility/kurento-extension.js?v=829:99:38 8f4e1ec1690e5c2a0a9c67253c4dbd26888c06ca.js:9:342266`

As a client all I get is a blank window with two spinning arrows and the similar error is thrown.

>BigBlueButton Server 2.2.0-rc-5 (1685)
>
>                 Kernel version: 4.4.0-173-generic
>                      Distribution: Ubuntu 16.04.6 LTS (64-bit)
>                            Memory: 8174 MB
>                         CPU cores: 4
>
>/usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties (bbb-web)
>       bigbluebutton.web.serverURL: https://bbb.xxx.com:1234
>                defaultGuestPolicy: ALWAYS_ACCEPT
>                 svgImagesRequired: true
>
>/etc/nginx/sites-available/bigbluebutton (nginx)
>                       server name: bbb.xxx.com
>                              port: 80, [::]:80
>                              port: 443 ssl (THIS SHOULD BE 1234 BUT STILL SHOWS UP HERE AS 443, triple checked nginx config is set to listen on 1234)
>                    bbb-client dir: /var/www/bigbluebutton
>
>/var/www/bigbluebutton/client/conf/config.xml (bbb-client)
>                Port test (tunnel): rtmp://bbb.xxx.com
>                              red5: bbb.xxx.com
>              useWebrtcIfAvailable: true

>/opt/freeswitch/etc/freeswitch/vars.xml (FreeSWITCH)
>                       local_ip_v4: 172.16.10.8
>                   external_rtp_ip: ***public_ip***
>                   external_sip_ip: ***public_ip***
>
>/opt/freeswitch/etc/freeswitch/sip_profiles/external.xml (FreeSWITCH)
>                        ext-rtp-ip: $${external_rtp_ip}
>                        ext-sip-ip: $${external_sip_ip}
>                        ws-binding: :5066
>                       wss-binding: ***public_ip***:7443
>
>/usr/local/bigbluebutton/core/scripts/bigbluebutton.yml (record and playback)
>                     playback_host: bbb.xxx.com:1234
>                 playback_protocol: https
>                            ffmpeg: 4.2.2-1bbb1~ubuntu16.04
>
>/etc/bigbluebutton/nginx/sip.nginx (sip.nginx)
>                        proxy_pass: ***public_ip***
>
>/usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml (Kurento SFU)
>                        kurento.ip: ***public_ip***
>                       kurento.url: ws://127.0.0.1:8888/kurento
>                    localIpAddress: 172.16.10.8
>               recordScreenSharing: true
>                     recordWebcams: true
>                  codec_video_main: VP8
>               codec_video_content: VP8
>
>/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml (HTML5 c                                                                       lient)
>                             build: 829
>                        kurentoUrl: wss://bbb.xxx.com:1234/bbb-webrtc-sfu
>                  enableListenOnly: true
>
>
> Potential problems described below
>
> Warning: The setting of ***public_ip*** for proxy_pass in
>
>    /etc/bigbluebutton/nginx/sip.nginx
>
> does not match the local IP address (172.16.10.8).
> (This is OK if you've manually changed the values)`

It looks like ICE is still connecting to the internal local ip address which may be the issue. I can screenshare when I am in the same network as the bbb server. 
But for the life of me I cannot figure out where to change this setting.

>Remote Candidate | Component ID | Priority | Bytes sent | Bytes received
>
>failed | false | false | 10.0.0.100:64441/udp(host) [non-proxied] | 192.168.96.1:26077/udp(host) | 1 | 8646913470639243000 | 0 | 0
>failed | false | false | 10.0.0.100:64441/udp(host) [non-proxied] | **172.16.10.8:32155/udp(host)** | 1 | 8646913466344276000 | 0 | 0
>failed | false | false | 10.0.0.100:61118/tcp(host) [non-proxied] | **172.16.10.8:25067/tcp(host)** | 1 | 4341475538259378700 | 0 | 0
>failed | false | false | 10.0.0.100:61118/tcp(host) [non-proxied] | 192.168.96.1:28824/tcp(host) | 1 | 4341474438747751000 | 0 | 0

**Comment by fillorkill** [comment]
issue resolved. turned out it was a faulty setting with the double natted firewall not being able to pick up the correct public ip address. All good now.

**Comment by Uddipaan** [comment]
I am also facing the same issue. Can you please help out with your solution as to how you have solved it... My audio/video everything is working fine just screen share is not working.
