### ISSUE TITLE
Hard Disk is full

### ISSUE THREAD

**Issue by aukion1** [bigbluebutton/bigbluebutton#8596]
Hi.

Today we have 1 TB hard disk inn 95% in use (most are bbb recordings - 760 GB).

2 questions:

1) Can we delete any files for liberate memory ?
2) If we install others disks, how can we nake to work bbb if copy the latest sessions to another disk. Is mandatory that the sessions there are in /var/bigblubutton ? Can we create links or how we can solve this?

Actual disk usage

`univirtual@univirtual-ProLiant-ML350-G6:~$ sudo su
[sudo] password for univirtual: 
root@univirtual-ProLiant-ML350-G6:/home/univirtual# df -H
Filesystem      Size  Used Avail Use% Mounted on
udev             18G     0   18G   0% /dev
tmpfs           3.6G  371M  3.3G  11% /run
**/dev/sda2       679G  612G   39G  95% /**
tmpfs            18G   33M   18G   1% /dev/shm
tmpfs           5.3M     0  5.3M   0% /run/lock
tmpfs            18G     0   18G   0% /sys/fs/cgroup
tmpfs           3.6G   91k  3.6G   1% /run/user/1000
root@univirtual-ProLiant-ML350-G6:/home/univirtual# `

**Comment by ffdixon** [comment]
We have some documentation that may help.

For (1), you could run a cron job that deletes recordings older than N days, see

  http://docs.bigbluebutton.org/2.2/customize.html#delete-recordings-older-than-n-days

For (2), you can mount a larger hard disk, move all the existing files to the larger hard disk, and make a symbolic link so future recordings are placed there.  See

  http://docs.bigbluebutton.org/2.2/troubleshooting.html

**Comment by aukion1** [comment]
For (1), you could run a cron job that deletes recordings older than N days, see

http://docs.bigbluebutton.org/2.2/customize.html#delete-recordings-older-than-n-days

conservar

That is for delete the session but ¿we can keep the video processed and delete auxiliar files? for example the PDF presentation and all files needed to process the session recorded but not necesary once the sesion has processed.

**Comment by tdjac0bs** [comment]
Hello @aukion1, you can run the following command in order to understand the storage used by BigBlueButton recordings:

```
du -sh /var/bigbluebutton/recording/raw /var/bigbluebutton/published/
```

It will produce an output similar to this:
```
84G	/var/bigbluebutton/recording/raw
1.8G	/var/bigbluebutton/published/
```

The raw folder is composed by intermediate files ( not used after processing the recordings ). 
It is safe to move those files to another server / external hard drive.

**Comment by twobaker** [comment]
Thanks for this inputs. I've another harddisk for recordings and linked it with "ln" /var/bigbluebutton as mentioned above. It's working well.
But my folders 
```
/var/lib/kurento/screenshare/
/var/lib/kurento/recordings/
```
are growings fast. Are this files important after recording? Is there a possibility or an automatism to remove it or reduce space?
Thanks for help!

**Comment by aukion1** [comment]
I did the sugetted in http://docs.bigbluebutton.org/2.2/troubleshooting.html


But now i have the next problem with  permissions



`
root@univirtual-ProLiant-ML350-G6:/usr/share/red5/webapps/video# bbb-conf --restart
# IP does not match:
#                           IP from ifconfig: 192.168.15.3
#   /etc/nginx/sites-available/bigbluebutton: univirtualcescijuc.com
grep: /opt/freeswitch/etc/freeswitch/sip_profiles/external.xml: No such file or directory
# Warning: Websockets is using HTTPS in /etc/bigbluebutton/nginx/sip.nginx
# but no definition for wss-binding found in 
#
#    /opt/freeswitch/etc/freeswitch/sip_profiles/external.xml

# Warning: Detected the directory
#    /usr/share/red5/webapps/video/streams
# is not owned by red5
# Warning: Detected the directory
#    /var/bigbluebutton
# is not owned by tomcat7
Restarting BigBlueButton 2.0.0-RC6 ...
Stopping BigBlueButton
Starting BigBlueButton
Job for freeswitch.service failed because the control process exited with error code. See "systemctl status freeswitch.service" and "journalctl -xe" for details.
....................


** Potential problems described below **
# IP does not match:
#                           IP from ifconfig: 192.168.15.3
#   /etc/nginx/sites-available/bigbluebutton: univirtualcescijuc.com
grep: /opt/freeswitch/etc/freeswitch/sip_profiles/external.xml: No such file or directory
# Warning: Websockets is using HTTPS in /etc/bigbluebutton/nginx/sip.nginx
# but no definition for wss-binding found in 
#
#    /opt/freeswitch/etc/freeswitch/sip_profiles/external.xml

# Warning: Detected the directory
#    /usr/share/red5/webapps/video/streams
# is not owned by red5
# Warning: Detected the directory
#    /var/bigbluebutton
# is not owned by tomcat7
grep: /opt/freeswitch/var/log/freeswitch/freeswitch.log: No such file or directory

#
# Error: Unable to connect to the FreeSWITCH Event Socket Layer on port 8021
#
# Warning: The voice application may not have registered with the sip server.
#   Try running: 
#
#      sudo bbb-conf --clean
#

............
# Error: Could not detect FreeSWITCH listening on port 5060

# Warning: The setting of 200.236.125.42 for proxy_pass in
#
#    /etc/bigbluebutton/nginx/sip.nginx
#
# does not match the local IP address (192.168.15.3).
# (This is OK if you've manually changed the values)

cat: /opt/freeswitch/etc/freeswitch/vars.xml: No such file or directory
# Warning: The setting of  for local_ip_v4 in
#
#    /opt/freeswitch/etc/freeswitch/vars.xml
#
# does not match the local IP address (192.168.15.3).
# (This is OK if you've manually changed the values)

root@univirtual-ProLiant-ML350-G6:/usr/share/red5/webapps/video# 

`

**Comment by aukion1** [comment]
solved with 

chown -h red5:red5 /usr/share/red5/webapps/video/streams


But now we can not see the playback sessions :(

403 forbidden

For example: 
https://univirtualcescijuc.com/playback/presentation/2.0/playback.html?meetingId=e1b2d941e2088e5566b7a4312484a10b4ad9ca9c-1586239234780

**Comment by matiasilva** [comment]
Seeing as this is a support issue, please move it to https://groups.google.com/forum/#!forum/bigbluebutton-users.
