### ISSUE TITLE
Best server (Asking for recommendations)

### ISSUE THREAD

**Issue by etaddigital** [bigbluebutton/bigbluebutton#8603]
Hi,

Based on your experiments what are the best servers working well with BBB with no lag, no issue about latency and can rendering recording very fast with no issue about audio and video?

**Comment by ffdixon** [comment]
This isn't an issue/feature request for BigBlueButton, but a request for advice.  Such requests are better made to our bigbluebutton-setup mailing list.  See https://bigbluebutton.org/support.
