### ISSUE TITLE
Fix metadata.xml when updating from version 1.0 to version 2.2.

### ISSUE THREAD

**Issue by mbdeme** [bigbluebutton/bigbluebutton#8605]
Hello,
I did a BBB Upgarde from 1.0 to version 2.2.
To transfer the recording I made a rsync of the directories
/var/bigbluebutton/published 
/var/bigbluebutton/unpublished 
/var/bigbluebutton/recording/raw

I see the presentations, but it doesn't work I have an error message :

Erreur
L'état actuel n'a pas été trouvé. L'enregistrement a peut-être été supprimé ou le serveur BigBlueButton n'est pas compatible avec l'action effectuée.

Thank you for your help

**Comment by ffdixon** [comment]
Can you try creating a new recording and let's see if that processes correctly.  The first question is are some of the recordings not visible (the ones copied over) or all of the recordings not visible (even new recordings).

**Comment by mbdeme** [comment]
Thank you for your reply.
the recordings I made with the new version work well.
It is only the copied recordings that do not work.
But they are still visible.

**Comment by mbdeme** [comment]
The problem is solved,

Between version 1.0 and version 2 of BigBlueButton, there is a difference on metadatas.
After launching the following command :
**sudo bbb-record --rebuild id_recording**

We had to adapt the metadata.xml file generated in the **/var/bigbluebutton/published/presentation/id_recording/metadata.xml** directory
By adding the **<meeting />** tag present in the **metadata.xml** of version 1.0.
This was enough to solve the problem.

@ffdixon,  would it not be possible to take this missing tag into account in future versions to ensure the compatibility of the records between the different versions?

Thank you.

**Comment by ffdixon** [comment]
Thanks for sharing with others the solution!
