### ISSUE TITLE
Allow user to refresh device list when selecting microphone / speaker

### ISSUE THREAD

**Issue by TiagoJacobs** [bigbluebutton/bigbluebutton#8606]
**Is your feature request related to a problem? Please describe.**
If a user try to share microphone, and click on "No" button (on echo test), the system displays a device list. 

When seeing this list it's possible that user see that the device is not plugged (like a USB headset). 

If a new device is plugged, it does not appear in the list, we need to close popup and open again.

**Describe the solution you'd like**
I would like to see a refresh button (icon) on side of list.

![image](https://user-images.githubusercontent.com/2075267/73855279-9b47b300-4812-11ea-91c4-e215fd6ccf72.png)

**Describe alternatives you've considered**
- Maybe button is not required (if we can automatically detect when a new device is available);

**Additional context**

**Comment by pedrobmarin** [comment]
For non-safari users, this can be automated with device change envents. https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/ondevicechange
