### ISSUE TITLE
Highlight questions in chat

### ISSUE THREAD

**Issue by alfonsofernandezyf** [bigbluebutton/bigbluebutton#8615]
**Is your feature request related to a problem? Please describe.**
It would be a nice feature to be able to tell questions apart from all the chat messages

**Describe the solution you'd like**
Any message in the chat that contains a question mark "?" will be highlighted

**Describe alternatives you've considered**

if (chatMessage.indexOf('?') > -1)  highlightQuestion() 

**Additional context**
I'll try to work it out myself

**Comment by ffdixon** [comment]
Hi Alfonso,

Thanks for your suggestion.  We're also considering adding a new module called Questions to let students submit a question and have others up-vote it.

**Comment by pedrobmarin** [comment]
Duplicate of https://github.com/bigbluebutton/bigbluebutton/issues/8280
