### ISSUE TITLE
public chat area found some mistake ?

### ISSUE THREAD

**Issue by lewdon** [bigbluebutton/bigbluebutton#8619]
**Describe the bug**
I have setup BBB, that is ok but found the public chat notice seem to have some mistake ,pls help me! In  fact, I had try to fixed more than two days ! ~_~
![image](https://user-images.githubusercontent.com/10276081/74080953-414e2400-4a84-11ea-88e9-304b8e578d49.png)
.

**Comment by ffdixon** [comment]
Are you able to reproduce this issue on our demo server at https://demo.bigbluebutton.org/?

If so, can you provide the steps (and sample text) to reproduce.

**Comment by lewdon** [comment]
Got it ！ Tks  a lot ! I found the native2ascii tool to fix it !  lol

**Comment by ffdixon** [comment]
It looks like you were putting UTF-8 code in the welcome message in `bigbluebutton.properties` and needed to use `native2ascii` on the text ... is that right?

**Comment by lewdon** [comment]
that‘s  right！：）
