### ISSUE TITLE
want to replace the   VideoPlayer

### ISSUE THREAD

**Issue by lewdon** [bigbluebutton/bigbluebutton#8620]
**Describe the bug**
want to replace the video player,but can't find it

**Expected behavior**

**Actual behavior**
found the setting file show that
   externalVideoPlayer:
    enabled: true

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, Mac]
 - Browser [e.g. Chrome, Safari]

**Smartphone (please complete the following information):**
 - Browser [e.g. stock browser, Safari]

**Additional context**

**Comment by ffdixon** [comment]
This isn't an issue or bug, but more of a "how to?" question.  Can you post this to our bigbluebutton-dev mailing list, see

 https://groups.google.com/forum/#!forum/bigbluebutton-dev

and we'll help you there.  If in helping you we discover a bug or enhancement needed for BigBlueButton, we'll open a new issue to track it.
