### ISSUE TITLE
The uploaded PowerPoint Chinese content show messy code in presentation

### ISSUE THREAD

**Issue by sesame437** [bigbluebutton/bigbluebutton#8621]
**Describe the bug**
The uploaded PowerPoint Chinese content show messy code in presentation 

**To Reproduce**
1. Go to '.upload a presentation .'
2. Click on '..upload a Chinese language powerpoint file.'
#upload PDF file show correctly in presentation

![image](https://user-images.githubusercontent.com/35056873/74086472-0ff24a00-4abe-11ea-960d-9fef9b281528.png)

**Expected behavior**
The uploaded Chinese language powerpoint file show as expected.

**Screenshots**
uploaded

**Desktop (please complete the following information):**
 - OS: [Mac]
 - Browser [Chrome]
 - Version [80]

**Comment by ffdixon** [comment]
Can you try converting it to PDF first and then upload.  When saving as PDF, it will embed the fonts and they should come through perfectly.

Try the above and let us know if that works.  Also, we're looking into putting the Chinese language packs onto the BigBlueButton server.

Can you attach a sample .pptx page from your presentation that we could test with -- thanks!

**Comment by sesame437** [comment]
The converted PDF file is show properly in presentation. 

Attached a very simple pptx file with few Chinese words in it.
[Chinese.pptx](https://github.com/bigbluebutton/bigbluebutton/files/4176421/Chinese.pptx)

**Comment by ffdixon** [comment]
Thanks!

**Comment by GhaziTriki** [comment]
Hi @sesame437 

I installed a chinese font then restart BigBlueButton using `sudo bbb-conf --restart`, and the result is below.

![image](https://user-images.githubusercontent.com/4991088/74183281-f4fe1200-4c44-11ea-8a16-97b4c295b56c.png)

`DengXian Light` is the font used in the PowerPoint presentation, it seems to be a Microsoft font.

You can install any Chinese font and it should work, I found a list here https://packages.debian.org/jessie/fonts/. Look for the packages starting with `fonts-arphic`. In my case I used `fonts-arphic-gkai00mp`. Just install the font that looks like the one you need and it should be fine.

**Comment by GhaziTriki** [comment]
@ffdixon An important note, this issue is only present in 2.2. BigBlueButton 2.3 converts the slide without any issue. A screenshot from 2.3 is attached to this comment.

![image](https://user-images.githubusercontent.com/4991088/74183598-92594600-4c45-11ea-8b24-147b494a74b8.png)

**Comment by ffdixon** [comment]
Thanks Ghazi, can you provide the steps to install the fonts on 2.2.

**Comment by GhaziTriki** [comment]
A simple `sudo apt install fonts-arphic-ukai` would work. The list of the fonts is available two comments up https://github.com/bigbluebutton/bigbluebutton/issues/8621#issuecomment-584313260

**Comment by kepstin** [comment]
We should consider making the BigBlueButton packages depend on "fonts-noto" to ensure there is a fallback font installed with wide language coverage. Server administrators can then add additional fonts if needed.

**Comment by ffdixon** [comment]
Not seeing `fonts-nofo` in the current apt-get repos on a default BigBlueButton server

~~~
$ apt-cache search fonts-nofo
$ apt-cache search fonts-arphic-ukai
fonts-arphic-ukai - "AR PL UKai" Chinese Unicode TrueType font collection Kaiti style
~~~

**Comment by ritzalam** [comment]
It is "noto" with a "t"

```
$ apt-cache search noto
fonts-noto-cjk - "No Tofu" font families with large Unicode coverage (CJK)
mysql-client-5.7 - MySQL database client binaries
python-monotonic - implementation of time.monotonic() - Python 2.x
wolf4sdl - SDL-Port of Wolfenstein 3-D and Spear of Destiny
bugs-everywhere - distributed bug tracking system using VCS storage
ccrypt - secure encryption and decryption of files and streams
commit-patch - utility to commit fine grained patches to source code control repositories
diffuse - graphical tool for merging and comparing text files
drascula - classic 2D point and click adventure game -- English version
drascula-french - classic 2D point and click adventure game -- French version
drascula-german - classic 2D point and click adventure game -- German version
drascula-italian - classic 2D point and click adventure game -- Italian version
drascula-spanish - classic 2D point and click adventure game -- Spanish version
enblend - image blending tool
enfuse - image exposure blending tool
fonts-cabin - humanist sans serif font
fonts-noto - metapackage to pull in all Noto fonts
fonts-noto-hinted - "No Tofu" font families with large Unicode coverage (hinted)
fonts-noto-mono - "No Tofu" monospaced font family with large Unicode coverage
fonts-noto-unhinted - "No Tofu" font families with large Unicode coverage (unhinted)
gimp-texturize - generates large textures from a small sample
irssi-scripts - collection of scripts for irssi
libclass-dbi-fromcgi-perl - Perl module to update Class::DBI data using CGI::Untaint
libghc-stm-chans-dev - additional types of channels for STM
libghc-stm-chans-doc - additional types of channels for STM; documentation
libghc-stm-chans-prof - additional types of channels for STM; profiling libraries
libmath-convexhull-monotonechain-perl - Perl module to calculate a convex hull using Andrew's monotone chain algorithm
libpano13-bin - panorama tools utilities
libtext-greeking-perl - Perl module for generating meaningless filler text
mariadb-client-10.0 - MariaDB database client binaries
meld - graphical tool to diff and merge files
monotone - Distributed version (revision) control system
monotone-doc - Distributed version (revision) control system - documentation
monotone-extras - Distributed version (revision) control system - extras
monotone-server - Distributed version (revision) control system - server scripts
monotone-viz - visualize a monotone repository
python-pyjavaproperties - Python implementation of java.util.Properties
python3-monotonic - implementation of time.monotonic() - Python 3.x
qct - GUI commit tool
tailor - migrate changesets between version control systems
texlive-latex-extra - TeX Live: LaTeX additional packages
uwsgi-core - fast, self-healing application container server (core)

```

**Comment by DevinY** [comment]
I am using follow command to search Chinese fonts.
`apt-cache search fonts-|grep Chinese`

And then i am install follow fonts to my server, issue command as below:.

`apt-get install fonts-arphic-uming fonts-wqy-zenhei fonts-cns11643-kai fonts-cns11643-sung fonts-moe-standard-kai fonts-moe-standard-song fonts-arphic-bkai00mp fonts-arphic-bsmi00lp`

I am no problem to see this ppt on BBB 2.2 server after done steps above.
--

**Comment by ffdixon** [comment]
Thanks for sharing this!

**Comment by sesame437** [comment]
Thanks for all of your sharing, after install the fonts, the PPT show correctly now.

**Comment by ffdixon** [comment]
We've made `fonts-noto` a dependency in BigBlueButton 2.2-RC-6, so this should help others facing a similar issue.
