### ISSUE TITLE
VPN is blocking the STUN candidates and letting the TURN candidates through

### ISSUE THREAD

**Issue by daminebenq** [bigbluebutton/bigbluebutton#8627]
**Describe the bug**
many users from the countries of the Europe East, Russia, and the south of Asia, they use VPN to reach many online services, but because of that BBB doesn't allow the use of VPN, the use of Audio Chat isn't possible...
![image](https://user-images.githubusercontent.com/5144311/74272165-e79c6280-4cec-11ea-8e3a-9fb91bdb9d54.png) source: https://www.statista.com/chart/16141/top-vpn-region/

**To Reproduce**
1. Go to a server without a configured TURN server
2. Click to Join with Microphone or with Listen Only
3. See the 1004 Error 
![image](https://user-images.githubusercontent.com/5144311/74272262-1c101e80-4ced-11ea-9115-a7fe4d45b431.png)

**What we should do**
We should show a more useful message to the user about what is wrong and how to fix it

**Comment by capilkey** [comment]
It's not BigBlueButton that disallows the use of a VPN. What's happening is that the VPN is stopping WebRTC from functioning without a TURN server. The only option to us is to tell that that VPNs and firewalls can cause issues.

**Comment by matiasilva** [comment]
Follow up to this? Or should I add an entry in the docs?

**Comment by daminebenq** [comment]
@capilkey and I, we talked about it in the past, and he suggested that we can add something to warn users with VPN that the use of audio isn't allowed when there is a VPN extension in the browser.
I suggest that we discuss this more.

**Comment by prlanzarin** [comment]
VPNs are not an issue per se. A specific VPN which arbitrarily decides to block UDP traffic and forces media to go through TURN is a problem, though. But this is not BBB's problem and it's for those scenarios that a TURN server is recommended in the docs.

We can't just figure out what blocks UDP traffic. We can give a visual warning that a user is using TURN and that his connection quality might be affected, but with no explicit mentions to firewall or VPN or anything because those would be guesses.

**Comment by matiasilva** [comment]
My two cents is that we should add an entry to the "troubleshooting" or FAQs in the docs. Showing the user that they're using TURN might be scary for those who have no clue what it is.

**Comment by prlanzarin** [comment]
Actually I don't meant to explicitly say "You're using TURN". There's a connection quality indicator in 2.3 which is pretty user friendly. It'd only be a matter of enriching its heuristics to include TURN usage.

**Comment by matiasilva** [comment]
Sounds good to me then.

**Comment by ericosg** [comment]
oddly enough, this issue is replicated without using the VPN. Just having the VPN extension enabled but not in use, still seems to affect bbb. Disabling the extension allows it to work.
