### ISSUE TITLE
displayBrandingArea doesn'n work.

### ISSUE THREAD

**Issue by rriscado** [bigbluebutton/bigbluebutton#8630]
**Describe the bug**

displayBrandingArea doesn'n work.

**To Reproduce**
1. Set "displayBrandingArea" = true in /usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml

2. Restart BBB and Meteor

3. Set Custom parameters "CustomLogoUrl=https://imagens.canaltech.com.br/empresas/690.400.jpg"
*Testing with https://mconf.github.io/api-mate

4. Doesn't show image at top left.
**Screenshots**
![image](https://user-images.githubusercontent.com/14829973/74291364-6906eb80-4d13-11ea-8b15-c80d8cd3339a.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome 
 - Version 79.0.3945.130

**Additional context**
I try use this configuration, based in follow merged issue
https://github.com/bigbluebutton/bigbluebutton/issues/5237
https://github.com/bigbluebutton/bigbluebutton/pull/5267

**Comment by antobinary** [comment]
Hey @rriscado 
We added this some time ago but I have not been able to trigger it either. Looking into what is needed. We'll update this issue when we have the exact answer!

**Comment by jfsiebel** [comment]
Hi @rriscado you need to use `logo` instead of `CustomLogoUrl`.

http://docs.bigbluebutton.org/dev/api.html#create

**Comment by rriscado** [comment]
This propused solution doesn't works on HTML5 for me.

**Comment by jfsiebel** [comment]
Which BBB version are you using?

Try to pass the custom parameter without `"` and double check if the settings are right `displayBrandingArea: true`

e.g: `logo=https://www.google.com/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png`

**Comment by rriscado** [comment]
Exuse-me.

After set displayBrandingArea: true in html5 settings.yml it's working fine.

**Comment by pbdco** [comment]
> Exuse-me.
> 
> After set displayBrandingArea: true in html5 settings.yml it's working fine.

Hi @rriscado and @jfsiebel , I'm looking for the same, I have made displayBrandingArea: true already but I dont find where to put logo= 

Would you kindly explain me please? Thanks

**Comment by pbdco** [comment]
> Exuse-me.
> 
> After set displayBrandingArea: true in html5 settings.yml it's working fine.


Hi,

I'm not being able to enable hotlink protection for recordings using this lines on /etc/bigbluebutton/nginx/presentation.nginx

        location /playback/presentation {
                root    /var/bigbluebutton;
                index  index.html index.htm;
                valid_referers blocked sentirdistinto.com cursos.sentirdistinto.com
                if ($invalid_referer) {
                return   403;
           }
        }


Any information or help will be much appreciated!

**Comment by pbdco** [comment]
> Exuse-me.
> 
> After set displayBrandingArea: true in html5 settings.yml it's working fine.

Hi @rriscado could you kindle tell me more information on how you proceed to get displayBrandingArea fowrking please? Thank you

**Comment by rriscado** [comment]
Hi,

**I change this configuration in** _/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml_
![image](https://user-images.githubusercontent.com/14829973/80635285-109ddb00-8a32-11ea-8be6-43c8004e07da.png)

**Restart bbb after this change**
_bbb-conf --restart_

**In API create call, use this:**
_https://abc.com/bigbluebutton/api/create?logo=https%3A%2F%2Fwww.google.com%2Fimages%2Fbranding%2Fgooglelogo%2F1x%2Fgooglelogo_color_272x92dp.png&meetingID=test&checksum=xxxxxxxxxxxxxxxxxxxx_

Works Fine
![image](https://user-images.githubusercontent.com/14829973/80636084-41324480-8a33-11ea-8e53-44c226a229aa.png)

**Comment by pbdco** [comment]
> Hi,
> 
> **I change this configuration in** _/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml_
> ![image](https://user-images.githubusercontent.com/14829973/80635285-109ddb00-8a32-11ea-8be6-43c8004e07da.png)
> 
> **Restart bbb after this change**
> _bbb-conf --restart_
> 
> **In API create call, use this:**
> _https://abc.com/bigbluebutton/api/create?logo=https%3A%2F%2Fwww.google.com%2Fimages%2Fbranding%2Fgooglelogo%2F1x%2Fgooglelogo_color_272x92dp.png&meetingID=test&checksum=xxxxxxxxxxxxxxxxxxxx_
> 
> Works Fine
> ![image](https://user-images.githubusercontent.com/14829973/80636084-41324480-8a33-11ea-8e53-44c226a229aa.png)
> 
> You can use https://mconf.github.io/api-mate/ to test!

Thank you @rriscado this worked!

**Comment by sripathroy** [comment]
It worked fine when run through API Call. But while creating a meeting through greenilight the branding doesnt appear.

**Comment by matiasilva** [comment]
Hi @sripathroy, you need to modify the Greenlight API call for this, as the logo on Greenlight has little to do with this logo. Have a look in the part of the code that handles this, then set the logo parameter as shown above.
