### ISSUE TITLE
Change 'bigbluebutton' in the URL

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#8631]
**Is your feature request related to a problem? Please describe.**
As part of branding BigBlueButton, document the steps to change the 'bigbluebutton' portion of the URL.

**Describe the solution you'd like**
Providing steps in [these docs](http://docs.bigbluebutton.org/2.2/customize.html#html5-client-configuration)

**Comment by newsistemaxs** [comment]
Hello my friend, I would really appreciate if you can help me with a question. I have BBB installed on my server that is in the cloud and in my PC I followed the steps for setting up the development environment. I need to make little changes, for example, add a background image to the main videocall page, but my trouble is that I couldn't find the way to take this changes and deploy them to my BBB in my hosting. I spent many days tryind to find the way to make the deployment but I couldn't.

So, as I can see you know how to do it, I really ask you to guide me or indicate the step by step to take my changes to my server and to update my BBB in production.

I would really appreciate it, I am entering to this world and I need a little help to continue. Thank you very much!!!!!

**Comment by GhaziTriki** [comment]
@newsistemaxs It is possible with nginx by adding some rewrite rules.
