### ISSUE TITLE
user list is flattened on mobile landscape

### ISSUE THREAD

**Issue by Tainan404** [bigbluebutton/bigbluebutton#8633]
**Describe the bug**

On mobile landscape the user list is too small when have more itens in the side bar.

**To Reproduce**
1. open the user list
2. rotate to landscape

**Expected behavior**
be able to scroll all side bar when more items are ir or increase the hight of the user list.

**Actual behavior**
the user list is flattened to a useless height

**Screenshots**

![WhatsApp Image 2020-02-13 at 12 57 08 PM](https://user-images.githubusercontent.com/15806883/74447423-1daa2580-4e58-11ea-8f2b-f2966d27f7ba.jpeg)

![Peek 2020-02-13 11-42](https://user-images.githubusercontent.com/15806883/74446866-47af1800-4e57-11ea-8f92-34f5e7c98216.gif)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Chrome
 - Version 80.0.3987.100

**Smartphone (please complete the following information):**
 - Device: xiaomi redmi note 6 pro
 - OS: 9
 - Browser Chrome
 - Version 80.0.3987.87

**Comment by daminebenq** [comment]
#8042 same situation with this issue.
