### ISSUE TITLE
Error 2200 when sharing screen on demo version

### ISSUE THREAD

**Issue by theocharis-theocharis** [bigbluebutton/bigbluebutton#8637]
Hello!

Since this morning, I 've been trying to share my screen on the demo version but it keeps showing an error 2200 message.

Thank u in advance.

**Comment by ffdixon** [comment]
We can see the error -- we're in the process of updating demo so the video may not work for a bit longer.  We'll post a follow-up message shortly.

**Comment by ffdixon** [comment]
Resolved-- we've finished updating https://demo.bigbluebutton.org/ BigBlueButton 2.2-RC-6 and video sharing should now occur without error.

(Let us know via an issue if you see the error occur again!)

**Comment by shaditobia** [comment]
Hello! 
I have the same Problem Now . 
thank you .
