### ISSUE TITLE
Error 1020 media could reach the server

### ISSUE THREAD

**Issue by arbudiman** [bigbluebutton/bigbluebutton#8643]
Hello sir..

I have problem with webcam share, message "error 1020 media could reach the server". I was installed BBB on openstack cloud, using Public IP and bbb isn't behind the firewall. UDP port was opened. Microphone work normally but webcam share cant work. Can you help? Thanks for your attention.

Regards

**Comment by ffdixon** [comment]
A few questions to gather more information

 1. What version of BigBlueButton are you installing/running?
 2. Did you get any errors during the install?
 3. What installation method did you follow?
  4. Did you make any changes to BigBlueButton outside of using bbb-conf or the bbb-install.sh script?
  5. Are you running BigBlueButton within a development environment?
  6. Post the output of sudo bbb-conf --check

**Comment by arbudiman** [comment]
> A few questions to gather more information
> 
> 1. What version of BigBlueButton are you installing/running?
----> latest version
> 2. Did you get any errors during the install?
----> installing normally, not get error
> 3. What installation method did you follow?
----> follow doc fromhttps://docs.bigbluebutton.org/2.2/install.html, not use bbb-install.sh
> 4. Did you make any changes to BigBlueButton outside of using bbb-conf or the bbb-install.sh script?
----> no
> 5. Are you running BigBlueButton within a development environment?
----> processor 8 core, Memory 8 GB, using public ip not behind the firewall.
> 6. Post the output of sudo bbb-conf --check
root@emeeting2:~# bbb-conf --check

BigBlueButton Server 2.2.0-rc-6 (1708)
                    Kernel version: 4.4.0-173-generic
                      Distribution: Ubuntu 16.04.6 LTS (64-bit)
                            Memory: 7979 MB
                         CPU cores: 8

/usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties (bbb-web)
       bigbluebutton.web.serverURL: https://emeeting2.tasikmalayakota.go.id
                defaultGuestPolicy: ALWAYS_ACCEPT
                 svgImagesRequired: true

/etc/nginx/sites-available/bigbluebutton (nginx)
                       server name: emeeting2.tasikmalayakota.go.id
                              port: 80, [::]:80
                              port: 443 ssl
                    bbb-client dir: /var/www/bigbluebutton

/var/www/bigbluebutton/client/conf/config.xml (bbb-client)
                Port test (tunnel): rtmp://103.148.79.38
                              red5: 103.148.79.38
              useWebrtcIfAvailable: true

/opt/freeswitch/etc/freeswitch/vars.xml (FreeSWITCH)
                       local_ip_v4: 103.148.79.38
                   external_rtp_ip: stun:stun.freeswitch.org
                   external_sip_ip: stun:stun.freeswitch.org

/opt/freeswitch/etc/freeswitch/sip_profiles/external.xml (FreeSWITCH)
                        ext-rtp-ip: $${local_ip_v4}
                        ext-sip-ip: $${local_ip_v4}
                        ws-binding: :5066
                       wss-binding: :7443

/usr/local/bigbluebutton/core/scripts/bigbluebutton.yml (record and playback)
                     playback_host: 103.148.79.38
                 playback_protocol: https
                            ffmpeg: 4.2.2-1bbb1~ubuntu16.04

/etc/bigbluebutton/nginx/sip.nginx (sip.nginx)
                        proxy_pass: 103.148.79.38

/usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml (Kurento SFU)
                        kurento.ip: 103.148.79.38
                       kurento.url: ws://127.0.0.1:8888/kurento
                    localIpAddress: 103.148.79.38
               recordScreenSharing: true
                     recordWebcams: true
                  codec_video_main: ANY
               codec_video_content: ANY

/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml (HTML5 client)
                             build: 837
                        kurentoUrl: wss://103.148.79.38/bbb-webrtc-sfu
                  enableListenOnly: true


# Potential problems described below

**Comment by arbudiman** [comment]
bbb-conf --status :

root@emeeting2:~# bbb-conf --status
nginx —————————————————► [✔ - active]
freeswitch ————————————► [✔ - active]
redis-server ——————————► [✔ - active]
bbb-apps-akka —————————► [✔ - active]
bbb-transcode-akka ————► [✔ - active]
bbb-fsesl-akka ————————► [✔ - active]
red5 ——————————————————► [✔ - active]
mongod ————————————————► [✔ - active]
bbb-html5 —————————————► [✔ - active]
bbb-webrtc-sfu ————————► [✔ - active]
kurento-media-server ——► [✔ - active]
etherpad ——————————————► [✔ - active]
bbb-web ———————————————► [✔ - active]

**Comment by ffdixon** [comment]
Can you try the install using `bbb-install.sh` as it automates the installation steps.  Be sure to pass the options `-s emeeting2.tasikmalayakota.go.id -e <your-email-address>`.

Let us know if the above gets you going.

**Comment by capilkey** [comment]
The value for kurentoUrl in settings.yml should be using the domain name not the IP address.
```
kurentoUrl: wss://emeeting2.tasikmalayakota.go.id/bbb-webrtc-sfu
```

**Comment by arbudiman** [comment]
> The value for kurentoUrl in settings.yml should be using the domain name not the IP address.
> 
> ```
> kurentoUrl: wss://emeeting2.tasikmalayakota.go.id/bbb-webrtc-sfu
> ```

I will try... thanks..

**Comment by arbudiman** [comment]
> The value for kurentoUrl in settings.yml should be using the domain name not the IP address.
> 
> ```
> kurentoUrl: wss://emeeting2.tasikmalayakota.go.id/bbb-webrtc-sfu
> ```

Thanks alot.. it is working now....

**Comment by capilkey** [comment]
What was happening is that the client was trying to connect to the websocket with the IP directly and nginx is configured to only proxy requests that come in from the domain name.
