### ISSUE TITLE
bbb-freeswitch-core upgrade fails because of libopusenc0 not installable

### ISSUE THREAD

**Issue by hermannkm** [bigbluebutton/bigbluebutton#8646]
bbb-freeswitch-core is not upgraded by because of unmet dependencies on Ubuntu 16.04 LTS (Linux mirror.klocker-mark.eu 4.4.0-173-generic #203-Ubuntu SMP Wed Jan 15 02:55:01 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux)
 bbb-freeswitch-core : Depends: **libopusenc0** but it is not installable

Manual upgrade after installing from script

apt-get upgrade bbb-freeswitch-core
Reading package lists... Done
Building dependency tree
Reading state information... Done
Calculating upgrade... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 bbb-freeswitch-core : Depends: libopusenc0 but it is not installable
E: Broken packages

This message first seen after Feb. 15th, before everything ran smoothly.

**Comment by ffdixon** [comment]
Try adding the PPA for `bigbluebutton/support`, see

  http://docs.bigbluebutton.org/2.2/install.html#upgrading-from-bigbluebutton-22

and let us know if that works for you.

**Comment by hermannkm** [comment]
Worked instantly! Overlooked this part of installation docs ... Sorry. Thank you!

**Comment by ffdixon** [comment]
Nice!  BTW, if you have a twitter account and want to give back to the project, tweet a few good works to @bigbluebutton and we'll RT.
