### ISSUE TITLE
Breakout room permissions

### ISSUE THREAD

**Issue by lifeofdan** [bigbluebutton/bigbluebutton#8652]
**Is your feature request related to a problem? Please describe.**
My school is a "Distance Education" school and we utilize bigbluebutton heavily. One issue we have is that when a breakout room is created, it gives moderator status to everyone. I understand this is so that students can work together, pass presenter around etc etc. However, kids will be kids and many of them take advantage of this permission and will mute/unmute, steal presenter off of someone who is using it, etc. 

**Describe the solution you'd like**
I would like the ability to set one person as the moderator over a breakout room. This would allow the ability to put one responsible student, or a teacher or a teacher aide as "in charge" of passing around presenter, etc. 

This would also allow for the channel locks to work also, so if you wanted to open it up free-for-all you could do that. But if someone starts playing up, you can revoke the permissions. 

**Describe alternatives you've considered**
We have considered using multiple rooms for this instead of breakout rooms. This work, but it is not nearly as convenient as breakout rooms for bringing students back together as a group.

Thank you for reading my request. And thank you for this wonderful piece of software!

**Comment by ffdixon** [comment]
Thanks for the feedback and the use case!

We'll look at adding an option to breakout rooms where a moderator can specify 

  [  ] All users join as viewers

and in the interface to drag-and-drop users between rooms, extend it so it has the option to select a users as moderator for that room.

We don't have any timeline for this implementation, but we will add it to our road map for a future version.

**Comment by miztaka** [comment]
@ffdixon As Catalyst, this feature should better be implemented. How about keeping parent's meeting privilege to breakout room as an alternative solution?

https://github.com/bigbluebutton/bigbluebutton/blob/f6f4f8321b0dc0340fe5cbcac161a7de02b0edb6/akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/breakout/BreakoutHdlrHelpers.scala#L24

**Comment by matiasilva** [comment]
@miztaka are you a developer? if so, have a go at implementing this, it can much accelerate the process of this seeing the light of day!
