### ISSUE TITLE
[QUESTION] Is there a way to increase the number of breakout rooms to be more than 8?

### ISSUE THREAD

**Issue by wardnath** [bigbluebutton/bigbluebutton#8657]
I would like to host pair programming sessions on BBB, so I would need a lot of small breakout rooms. E.g. 20 students paired up would mean 10 breakout rooms. 

Is there a relatively easy way to increase the max number of breakout rooms? Are there any extra considerations I should make?

**Comment by capilkey** [comment]
The complication is the voiceBridge numbers for the audio. With a max of 8 rooms we add 1 digit to the end of the main room's voiceBridge value so 77777 becomes 777771. We could modify the voiceBridge and get to max rooms of 99, but it would take some testing to make sure it works.

**Comment by wardnath** [comment]
Thanks @capilkey. Would implementing this change be large in scope? I noticed #4389 increases the number of breakout rooms from 5 to 8, but it sounds like going from 8 to 99 would be harder.

**Comment by ritzalam** [comment]
The hardest part would be the UI and assigning the users in each breakout room. Changing the voice conf to handle more digits isn't that difficult.

As an alternative, you can create multiple meeting rooms ahead of time and tell each pair to go to their assigned meetings.

**Comment by wardnath** [comment]
Thanks @ritzalam. Yeah, ui-wise the breakout rooms modal would have to be scrollable because there would be more rows.

**Comment by alanpog** [comment]
A larger number of breakout rooms would be awesome to become a viable OSS alternative to Zoom in this area, now when so many are looking for one. Zoom offers 50 breakout rooms, BlueJeans offers 20. They have both worked out an UI that works well, especially Zoom, maybe it could be used as a starting point.

**Comment by wardnath** [comment]
My major problem with zoom was that you couldn't invite people to the breakout rooms via the browser, only via the app, this was unacceptable to me.

**Comment by trs80** [comment]
I tried doing this before I found this bug, and was halfway successful:

The limit in the UI is set at https://github.com/bigbluebutton/bigbluebutton/blob/41f19a2cd1bc7dae76cbd805cdc3ddfbf1e6ab18/bigbluebutton-html5/imports/ui/components/actions-bar/create-breakout-room/component.jsx#L113
and enforced at https://github.com/bigbluebutton/bigbluebutton/blob/41f19a2cd1bc7dae76cbd805cdc3ddfbf1e6ab18/bigbluebutton-html5/imports/api/breakouts/server/methods/createBreakout.js#L13

Something is truncating the breakout room number to a single digit in the popout, I think https://github.com/bigbluebutton/bigbluebutton/blob/41f19a2cd1bc7dae76cbd805cdc3ddfbf1e6ab18/bigbluebutton-html5/imports/ui/components/breakout-room/component.jsx#L262 is the relevant code?

The voice bridge limit makes sense with the errors I saw about not being able to join the audio when I joined breakout rooms 10 and above.

**Comment by Meth0d007** [comment]
We are also facing the issue that we need more then 8 breakout rooms. If UI is the problem it would even work for us when this could be done only by API. Hope this gets on the roadmap as its the only thing still driving people to zoom.

**Comment by ffdixon** [comment]
We can't promise anything for the next version of BigBlueButton 2.3 (currently under development), but we're aware of it and will see if we can make some increases in number of breakout rooms.

**Comment by frankkoch** [comment]
> We can't promise anything for the next version of BigBlueButton 2.3 (currently under development)
BBB v2.3.3 still allows a max of 8 breakout rooms only. Any news, when a higher max will be implemented?

**Comment by jfparmentier** [comment]
Hi,

I'm working in a French public university at Toulouse. We consider that increasing the number of breakout rooms is of primary importance and this will widely increase the use of BBB by our teachers.

If this development is not in your to-do list, could we fund this specific development ? (still making it open-source)

**Comment by ohameiri** [comment]
+1

**Comment by Richardvi** [comment]
My teachers are also requesting more breakout rooms. They would like it doubled to 16.

**Comment by ffdixon** [comment]
@jfparmentier Please reach out to any of the companies that provide commercial support

  https://bigbluebutton.org/support/

for options for funding development of this.  We need to extend the breakout number to 2 digits and then test extensively to ensure the breakout rooms all start without issue.

**Comment by agussang** [comment]
any update?

**Comment by mvasylenko** [comment]
> 
> 
> The complication is the voiceBridge numbers for the audio. With a max of 8 rooms we add 1 digit to the end of the main room's voiceBridge value so 77777 becomes 777771. We could modify the voiceBridge and get to max rooms of 99, but it would take some testing to make sure it works.

Freeswitch dialplan was updated some time ago. It accepts now 5 to 11 digit numbers.
<condition field="destination_number" expression="^(\d{5,11})$">

in  /opt/freeswitch/conf/dialplan/default/bbb_conference.xml 
and  in /opt/freeswitch/conf/dialplan/default/bbb_echo_test.xml

**Comment by matiasilva** [comment]
If I'm not mistaken, this issue can now be closed as #10434 has been implemented. Closing for now...
