### ISSUE TITLE
Provide an ability for users to add emoji to existing chat messages

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#8658]
**Is your feature request related to a problem? Please describe.**
Enable users to add emojis to existing chat messages.  

**Describe the solution you'd like**
A mechanism to select an individual chat message and choose an emoji that will then appear next to the chat message.  Similar implementations in other programs, such as Slack, will count the emojis as well (i.e. 5 people give this post a thumbs up).

**Describe alternatives you've considered**
Some research is needed on the best way to add this to BigBlueButton.   Slack already has a hover state for each chat message which gives a number of operations (such as delete message).  

It's not clear whether we build in a generic method to make a change to an existing chat message, or build a specific method for just adding emojis.

**Comment by alfonsofernandezyf** [comment]
That would be nice. To be able to react to chat messages

**Comment by rasos** [comment]
Emojis at chat messages would be also very useful for opinion polls. A moderator can e.g. post five proposals and users may give their vote. Ideally, one user may only post one emoji (e.g. thumb up or down) at one chat message.

MS Teams also allows adding emojis to each chat message and shows a counter, if an emoji has been selected more than once.

**Comment by NiceboyWiseboy** [comment]
yes, it would be a feature.
