### ISSUE TITLE
Provide proper error message for sharing video from IP address

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#8662]
**Describe the bug**
When accessing a BigBlueButton server setup with only IP address, the error message for sharing video references iOS not supported.

**To Reproduce**
1. Configure BigBlueButton 2.2 server to access IP address only
2. Attempt to share video

**Expected behavior**
When attempting to share audio, the error message is correct

![image](https://user-images.githubusercontent.com/290351/75119997-e3aa0200-5655-11ea-833b-331ed0bcd2b3.png)

However, when attempting to share video, the error message is incorrect
![image](https://user-images.githubusercontent.com/290351/75119986-d0973200-5655-11ea-98b9-c44dcfa27da0.png)

**Comment by pedrobmarin** [comment]
@prlanzarin ?

**Comment by prlanzarin** [comment]
I think was addressed (and non-SSL environments are not even a real use case anymore). Although the warning message might no be as fancy.
