### ISSUE TITLE
grep: /opt/freeswitch/var/log/freeswitch/freeswitch.log: No such file or directory

### ISSUE THREAD

**Issue by ycgq** [bigbluebutton/bigbluebutton#8663]
**Describe the bug**
After running the install.sh, freeswitch failed if run bbb-conf --status. Use bbb-conf --check. it show the error:  
# Potential problems described below
grep: /opt/freeswitch/var/log/freeswitch/freeswitch.log: No such file or directory
...........................
# Warning: The API demos are installed and accessible from:
#
#    http://192.249.126.110
#
# and
#
#    http://192.249.126.110/demo/demo1.jsp
#
# These API demos allow anyone to access your server without authentication
# to create/manage meetings and recordings. They are for testing purposes only.
# If you are running a production system, remove them by running:
#
#    apt-get purge bbb-demo

# Error: FreeSWITCH failed to start with SETSCHEDULER error, see
#
#   https://docs.bigbluebutton.org/install/install.html#freeswitch-fails-to-start-with-a-setscheduler-error
#

**Installation type**
Install using the bbb-install script

**Console output**
Please include the full console output from the install.

When I re-run the install.sh,  here is the output:

XDG_SESSION_ID=13066286
SHELL=/bin/bash
TERM=xterm
SSH_CLIENT=71.238.107.11 62533 22
SSH_TTY=/dev/pts/1
USER=root
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
MAIL=/var/mail/root
PWD=/root
LANG=en_US.UTF-8
HOME=/root
SHLVL=2
LOGNAME=root
SSH_CONNECTION=71.238.107.11 62533 192.249.126.110 22
DEBIAN_FRONTEND=noninteractive
LESSOPEN=| /usr/bin/lesspipe %s
XDG_RUNTIME_DIR=/run/user/0
LESSCLOSE=/usr/bin/lesspipe %s %s
_=/usr/bin/env
Reading package lists... Done
Building dependency tree
Reading state information... Done
grub-pc is already the newest version (2.02~beta2-36ubuntu3.23).
update-notifier-common is already the newest version (3.168.10).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.4 multiverse
Ign:1 http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.4 InRelease
Hit:2 http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.4 Release
Hit:3 http://archive.canonical.com/ubuntu xenial InRelease
Hit:4 https://deb.nodesource.com/node_8.x xenial InRelease
Get:6 http://security.ubuntu.com/ubuntu xenial-security InRelease [109 kB]
Hit:7 http://ppa.launchpad.net/ansible/ansible/ubuntu xenial InRelease
Hit:8 http://archive.ubuntu.com/ubuntu xenial InRelease
Get:9 http://archive.ubuntu.com/ubuntu xenial-updates InRelease [109 kB]
Hit:10 https://ubuntu.bigbluebutton.org/xenial-220 bigbluebutton-xenial InRelease
Hit:11 http://ppa.launchpad.net/bigbluebutton/support/ubuntu xenial InRelease
Hit:12 http://ppa.launchpad.net/rmescandon/yq/ubuntu xenial InRelease
Fetched 218 kB in 1s (117 kB/s)
Reading package lists... Done
Reading package lists...
Building dependency tree...
Reading state information...
Calculating upgrade...
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists...
Building dependency tree...
Reading state information...
The following additional packages will be installed:
  authbind libcommons-collections3-java libcommons-dbcp-java libcommons-pool-java libecj-java libservlet3.0-java libtomcat7-java tomcat7 tomcat7-common
Suggested packages:
  libcommons-collections3-java-doc libcommons-dbcp-java-doc libgeronimo-jta-1.1-spec-java ecj ant libecj-java-gcj tomcat7-docs tomcat7-admin
  tomcat7-examples tomcat7-user libtcnative-1
The following NEW packages will be installed:
  authbind bbb-demo libcommons-collections3-java libcommons-dbcp-java libcommons-pool-java libecj-java libservlet3.0-java libtomcat7-java tomcat7
  tomcat7-common
0 upgraded, 10 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/8,820 kB of archives.
After this operation, 10.3 MB of additional disk space will be used.
Preconfiguring packages ...
Selecting previously unselected package libcommons-collections3-java.
(Reading database ... 135655 files and directories currently installed.)
Preparing to unpack .../libcommons-collections3-java_3.2.2-1_all.deb ...
Unpacking libcommons-collections3-java (3.2.2-1) ...
Selecting previously unselected package libcommons-pool-java.
Preparing to unpack .../libcommons-pool-java_1.6-2_all.deb ...
Unpacking libcommons-pool-java (1.6-2) ...
Selecting previously unselected package libcommons-dbcp-java.
Preparing to unpack .../libcommons-dbcp-java_1.4-5ubuntu2_all.deb ...
Unpacking libcommons-dbcp-java (1.4-5ubuntu2) ...
Selecting previously unselected package libecj-java.
Preparing to unpack .../libecj-java_3.10.1-2ubuntu1_all.deb ...
Unpacking libecj-java (3.10.1-2ubuntu1) ...
Selecting previously unselected package libservlet3.0-java.
Preparing to unpack .../libservlet3.0-java_7.0.68-1ubuntu0.4_all.deb ...
Unpacking libservlet3.0-java (7.0.68-1ubuntu0.4) ...
Selecting previously unselected package libtomcat7-java.
Preparing to unpack .../libtomcat7-java_7.0.68-1ubuntu0.4_all.deb ...
Unpacking libtomcat7-java (7.0.68-1ubuntu0.4) ...
Selecting previously unselected package tomcat7-common.
Preparing to unpack .../tomcat7-common_7.0.68-1ubuntu0.4_all.deb ...
Unpacking tomcat7-common (7.0.68-1ubuntu0.4) ...
Selecting previously unselected package tomcat7.
Preparing to unpack .../tomcat7_7.0.68-1ubuntu0.4_all.deb ...
Unpacking tomcat7 (7.0.68-1ubuntu0.4) ...
Selecting previously unselected package authbind.
Preparing to unpack .../authbind_2.1.1+nmu1_amd64.deb ...
Unpacking authbind (2.1.1+nmu1) ...
Selecting previously unselected package bbb-demo.
Preparing to unpack .../bbb-demo_1%3a2.2.0-9_amd64.deb ...
Unpacking bbb-demo (1:2.2.0-9) ...
Processing triggers for systemd (229-4ubuntu21.27) ...
Processing triggers for man-db (2.7.5-1) ...
Setting up libcommons-collections3-java (3.2.2-1) ...
Setting up libcommons-pool-java (1.6-2) ...
Setting up libcommons-dbcp-java (1.4-5ubuntu2) ...
Setting up libecj-java (3.10.1-2ubuntu1) ...
Setting up libservlet3.0-java (7.0.68-1ubuntu0.4) ...
Setting up libtomcat7-java (7.0.68-1ubuntu0.4) ...
Setting up tomcat7-common (7.0.68-1ubuntu0.4) ...
Setting up tomcat7 (7.0.68-1ubuntu0.4) ...
Setting up authbind (2.1.1+nmu1) ...
Setting up bbb-demo (1:2.2.0-9) ...
Reloading nginx.service using systemd
Reading package lists... Done
Building dependency tree
Reading state information... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Assigning 192.249.126.110 for testing for firewall in /var/www/bigbluebutton/client/conf/config.xml
Assigning 192.249.126.110 for rtmp:// in /var/www/bigbluebutton/client/conf/config.xml
Assigning 192.249.126.110 for servername in /etc/nginx/sites-available/bigbluebutton
Assigning 192.249.126.110 for http[s]:// in /var/www/bigbluebutton/client/conf/config.xml
Assigning 192.249.126.110 for publishURI in /var/www/bigbluebutton/client/conf/config.xml
Assigning 192.249.126.110 for web application URL in /usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties
Assigning 192.249.126.110 for web application URL in /usr/share/bbb-apps-akka/conf/application.conf
Assigning 192.249.126.110 for api demos in /var/lib/tomcat7/webapps/demo/bbb_api_conf.jsp
Assigning 192.249.126.110 for record and playback in /usr/local/bigbluebutton/core/scripts/bigbluebutton.yml
Assigning 192.249.126.110 for playback of recordings:
Restarting the BigBlueButton 2.2.0-rc-6 ...
Stopping BigBlueButton

Starting BigBlueButton
Job for freeswitch.service failed because the control process exited with error code. See "systemctl status freeswitch.service" and "journalctl -xe" for details.

BigBlueButton Server 2.2.0-rc-6 (1711)
                    Kernel version: 4.4.0
                      Distribution: Ubuntu 16.04.6 LTS (64-bit)
                            Memory: 8388 MB
                         CPU cores: 48

/usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties (bbb-web)
       bigbluebutton.web.serverURL: http://192.249.126.110
                defaultGuestPolicy: ALWAYS_ACCEPT
                 svgImagesRequired: true

/etc/nginx/sites-available/bigbluebutton (nginx)
                       server name: 192.249.126.110
                              port: 80, [::]:80
                    bbb-client dir: /var/www/bigbluebutton

/var/www/bigbluebutton/client/conf/config.xml (bbb-client)
                Port test (tunnel): rtmp://192.249.126.110
                              red5: 192.249.126.110
              useWebrtcIfAvailable: true

/opt/freeswitch/etc/freeswitch/vars.xml (FreeSWITCH)
                       local_ip_v4: 192.249.126.110
                   external_rtp_ip: stun:stun.freeswitch.org
                   external_sip_ip: stun:stun.freeswitch.org

/opt/freeswitch/etc/freeswitch/sip_profiles/external.xml (FreeSWITCH)
                        ext-rtp-ip: $${local_ip_v4}
                        ext-sip-ip: $${local_ip_v4}
                        ws-binding: :5066
                       wss-binding: :7443

/usr/local/bigbluebutton/core/scripts/bigbluebutton.yml (record and playback)
                     playback_host: 192.249.126.110
                 playback_protocol: http
                            ffmpeg: 4.2.2-1bbb1~ubuntu16.04

/etc/bigbluebutton/nginx/sip.nginx (sip.nginx)
                        proxy_pass: 192.249.126.110

/usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml (Kurento SFU)
                        kurento.ip: 192.249.126.110
                       kurento.url: ws://127.0.0.1:8888/kurento
                    localIpAddress: 192.249.126.110
               recordScreenSharing: true
                     recordWebcams: true
                  codec_video_main: VP8
               codec_video_content: VP8

/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml (HTML5 client)
                             build: 837
                        kurentoUrl: ws://192.249.126.110/bbb-webrtc-sfu
                  enableListenOnly: true

# Potential problems described below
grep: /opt/freeswitch/var/log/freeswitch/freeswitch.log: No such file or directory
...........................
# Warning: The API demos are installed and accessible from:
#
#    http://192.249.126.110
#
# and
#
#    http://192.249.126.110/demo/demo1.jsp
#
# These API demos allow anyone to access your server without authentication
# to create/manage meetings and recordings. They are for testing purposes only.
# If you are running a production system, remove them by running:
#
#    apt-get purge bbb-demo

# Error: FreeSWITCH failed to start with SETSCHEDULER error, see
#
#   https://docs.bigbluebutton.org/install/install.html#freeswitch-fails-to-start-with-a-setscheduler-error
#

**Comment by ffdixon** [comment]
Did you try the steps at

  https://docs.bigbluebutton.org/install/install.html#freeswitch-fails-to-start-with-a-setscheduler-error

**Comment by ycgq** [comment]
I did not find the "freeswitch-fails-to-start-with-a-setscheduler-error" topic with that URL. Now I find it in the FAQ. 

After following the steps there, the issue is resolved. Thanks a lot!

**Comment by ffdixon** [comment]
Fixed broken link in #8664.
