### ISSUE TITLE
Move Kick User to the bottom of the options list

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#8668]
**Describe the bug**
Currently, the Remove User is very close to Make Presenter.

![image](https://user-images.githubusercontent.com/290351/75379076-c6b63e80-58a2-11ea-97f5-9238675504e5.png)

**Additional context**
We sometimes get bug reports of users who have been kicked out when the moderator made them presenter.

We had this happen in one of our test meetings -- the moderator thought they made someone presenter, but in effect kicked them out.

**Comment by antobinary** [comment]
Implemented in #8673
