### ISSUE TITLE
skipping external video possibility for other users and changing Presenter doesn't stop the sharing

### ISSUE THREAD

**Issue by daminebenq** [bigbluebutton/bigbluebutton#8670]
**Describe the bug**
If a Presenter shares an external video of a playlist, the Video player will display the **previous** and **next** control buttons
![image](https://user-images.githubusercontent.com/5144311/75383337-ece7d880-58ba-11ea-8b35-6d29d1934dbc.png)

Also on 2.2 servers, changing Presenter doesn't stop the shared external video at all.

**Expected behavior**
1- The shared external video should not be changed by other users than the Presenter
2- giving Presenter to another user, while there is an external video shared should stop it 

**Actual behavior**
(1) if a non-Presenter clicks on **previous** or **next** control buttons, it changes the video, but it synchronizes the same time of the original video.
(2) giving Presenter role to another user doesn't stop the sharing of external video

**Desktop:**
 - OS: All
 - Browser: All
 - Version: 2.2

**Suggestion to Solve this**
(1) maybe blocking displaying video controls to other users will help avoiding this problem
or also
(1) adding a listener, to listen for shared video changes by other users and block it
or also
(1) reformulating the shared external video link to just https://example.com/watch?v=VIDEO_ID, but this will not give possibility to the Presenter to play a Playlist, because he will need to stopsharing a video, get a new link of a new video to share, paste it, and start playing it, which is kinda long way to just play next video in a playlist...

**Comment by matiasilva** [comment]
I believe the first issue has been fixed in ReactPlayer and the second by the PR mentioned.
