### ISSUE TITLE
Add a lock setting for otherViewersWebcam

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#8672]
**Describe the bug**
We have [defaults ](https://github.com/bigbluebutton/bigbluebutton/blob/4c6bdebd00bb8314458f52c5f0c084acc954dff1/bigbluebutton-web/grails-app/conf/bigbluebutton.properties#L326)in `bigbluebutton.properties` to set the values for the lock settings server wide, but not for See other viewer's webcams. 

**Additional context**
Need to add a setting to enable the server to have the 

~~~
lockSettingsSeeOtherViewersWebcams=false
~~~

**Comment by PhMemmel** [comment]
The key is `webcamsOnlyForModerator` and already exists. However, I agree that it `lockSettingsSeeOtherViewersWebcams` would be easier to understand. Maybe this could be refactored/renamed.

**Comment by antobinary** [comment]
![Screenshot from 2023-02-01 06-04-42](https://user-images.githubusercontent.com/6312397/216025893-88eb269a-0046-444b-ba61-3ca453a7adfe.png)

https://docs.bigbluebutton.org/dev/api.html

The main difference between what we have and a lock setting is that lock settings could be disabled /re-enabled at any point in the session. This does not seem to be a requirement here. If it is, please reopen.
