### ISSUE TITLE
Playing hls external video is broken

### ISSUE THREAD

**Issue by zhu** [bigbluebutton/bigbluebutton#8678]
**Describe the bug**
The external video uses `react-player` which add script `hls.js` to play hls video.
Global variable 'exports' will cause `hls.js` to export it self to 'exports' instead of 'window'. But `react-player` expect it on 'window'.
Can we remove the global 'exports'?

**To Reproduce**
1. try to share a hls video

**Expected behavior**

**Actual behavior**
got an exception

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, Mac]
 - Browser [e.g. Chrome, Safari]

**Smartphone (please complete the following information):**
 - Browser [e.g. stock browser, Safari]

**Additional context**
related issue:
https://github.com/CookPete/react-player/issues/815

**Comment by zhu** [comment]
It seems that `meteor` uses `terser`  to uglify the js. The `terser` has an option `wrap` to wrap the whole app in a global variable which default to `exports`. Currently `terser` options are hardcoded [here](https://github.com/meteor/meteor/blob/master/packages/minifier-js/minifier.js#L10) .

**Comment by Rafael-Netizen** [comment]
However, this function but it did not work in our tests either. Most participants could only see the first few seconds of the video in a loop.

**Here is a workaround:**

For certain classroom uses, during video playback, being able to target specific points in time is essential. This can be done using "Share an external video", accessible via the Plus button at the bottom of the screen.

One workaround is using a playback synchronization service along with BBB, like Watch2Gether.com or  Sync-Tube.de. They typically work as follows:

1. The Moderator shares the (Youtube etc.) video URL
2. Every user retrieves the video and plays it back in her or his browser
3. During playback, the only data sent by the Moderator’s computer to the other users consists in short playback commands

**Comment by matiasilva** [comment]
Bringing in @lfzawacki for an update.

**Comment by zhu** [comment]
https://github.com/cookpete/react-player/commit/f90c7567f518082dd7a0260f21707587f679e8a5
It seems that react-player fixed the bug. But I cannot test recently.
