### ISSUE TITLE
In Canvas integration, Google Chrome gives error 1002 when attempting to use Microphone for audio

### ISSUE THREAD

**Issue by jknowlton3** [bigbluebutton/bigbluebutton#8679]

**Comment by ffdixon** [comment]
See
 
  https://groups.google.com/d/msg/bigbluebutton-dev/whcTZWe30UQ/m2SpxIlABwAJ

**Comment by GremL1N** [comment]
anover way is to change bbb canvas module source.
exactly in file app/models/big_blue_button_conference.rb change string:
```
:voiceBridge => format("%020d", self.global_id),
```
to for example
```
:voiceBridge => 5.times.map{rand(9)}.join, 
```

**Comment by ffdixon** [comment]
Thanks for sharing this @GremL1N.

**Comment by matiasilva** [comment]
Great to see this issue solved. Closing as such.
