### ISSUE TITLE
How to fix error:unsupported IE11 Browser

### ISSUE THREAD

**Issue by wgwxxx** [bigbluebutton/bigbluebutton#8684]
How can I fix this error?  
when I created a meeting and open the html5 client ,it says "It looks like you're using a browser that is not supported. Please use either chrome or firedox for full support."

**Comment by GhaziTriki** [comment]
Hello @wgwxxx,

What you are describing should not be interpreted as a bug. IE11 is very outdated and BigBlueButton is using evolved technologies; WebRTC, WebSocket...; to give you the best experience. If want to stick into a Windows product I invite you to try the latest version of Microsoft Edge which should work exactly as Google Chrome.

To find more about the supported browser I hope the following documentation topic helps http://docs.bigbluebutton.org/support/faq.html#what-are-the-minimum-requirements-for-the-bigbluebutton-client

I also invite you to post into one of the community support forums https://bigbluebutton.org/support/community/ if you need any help.

Thanks,
Ghazi

**Comment by mariamartos** [comment]
In the official page, the link proporcionated, [http://docs.bigbluebutton.org/support/faq.html#what-are-the-minimum-requirements-for-the-bigbluebutton-client] shows:

"For browser, we recommend running either FireFox or Chrome. Why? Both browsers provide excellent support for web real-time communications (WebRTC). Safari, IE, and Edge will work as well, but FireFox and Chrome will deliver better audio in lower bandwidth conditions."

I would appreciate if the browsers and compatible versions were updated
