### ISSUE TITLE
Tooltip does not disappear on iOS

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#8687]
**Describe the bug**
Selecting the text tool on iOS leaves behind the tooltip after it is selected.

**To Reproduce**
1. Open the latest build of 2.2 on a iOS phone
2. Select the text tool

**Expected behavior**
The tooltip should disappear

**Actual behavior**
The tooltip remains on the screen

**Screenshots**
See video below

![lab](https://user-images.githubusercontent.com/290351/75626584-91596b80-5b96-11ea-8c23-dc7d3e170169.gif)

**Smartphone:
 - Device: iPhone 8s
 - OS: 13.3.1
 - Browser: Stock Safari

**Additional context**
Reported here https://groups.google.com/d/msg/bigbluebutton-dev/n75ZaVGdyqc/26_FClfLAQAJ

**Comment by antobinary** [comment]
Resolved
