### ISSUE TITLE
Option to hide public chat by default

### ISSUE THREAD

**Issue by sharypovandrey** [bigbluebutton/bigbluebutton#8689]
By default, Public Chat is opened. Is there some way to hide it in configs?

**Comment by antobinary** [comment]
I see this is an old issue but given it's unanswered, let me add:

In #9658 a combined solution by @weeman1337 and @mantridereso added `chat.startClosed: false` in `bigbluebutton-html5/private/config/settings.yml

**Comment by antobinary** [comment]
Implemented in #9658
