### ISSUE TITLE
How to enable HTML5 Client on my install?

### ISSUE THREAD

**Issue by LukeStaszewski** [bigbluebutton/bigbluebutton#8690]
**Describe the bug**
I'm not sure if this is a bug - but I am unable to find the documentation for this issue. I do apologise if it is obvious or easily found, but I have genuinely been searching for it for quite awhile.

I have followed the install instructions and my server is now installed, however when I try to test it, it says Adobe Flash is not enabled (I am using Brave Browser which does not include Flash - but I have tried on Chrome and it works but I would like to enable the HTML5 client so it can be used).

**To Reproduce**
Go to server URL, enter username and click join.

**Expected behavior**
Loads HTML5 client

**Actual behavior**
Loads Flash Client

**Screenshots**
https://i.imgur.com/MdWRAkM.png

**Desktop (please complete the following information):**
Windows 10, Brave Browser & Chrome

**Additional context**
If I am correct - I believe the HTML5 client might still be in active development and that is why it is not installed along with the default, if that is true, I would like to know / be linked to documentation on how to install and enable the HTML5 client as I would love to use it in production (My use-case is not too important right now - so bugs are fine) and then contribute to this project in any way I can :)

**Comment by ffdixon** [comment]
Hi there,

You shouldn't have to enable anything to use the HTML5 client.  In BigBlueButton 2.2, the HTML5 client is installed by default.

Can you try using the [bbb-install.sh](https://github.com/bigbluebutton/bbb-install) script to install BigBlueButton 2.2 and let us know if the HTML5 client comes up.

Also, can you use the Brave Browser and test against https://demo.bigbluebutton.org/ and let us know if the HTML5 client loads for you there.

**Comment by LukeStaszewski** [comment]
Hi ffdixon,

Thank you so much for your quick reply.

I believe I know the issue now... it seems I followed the installation instructions for 1.1! Haha. Silly me.

Sorry about that, will reset the server and install 2.2.

Thanks again for your help - and sorry for the silly mistake!
