### ISSUE TITLE
meetingExpireIfNoUserJoinedInMinutes has no effect

### ISSUE THREAD

**Issue by magic-maker** [bigbluebutton/bigbluebutton#8701]
Hi,
The parameter "meetingExpireIfNoUserJoinedInMinutes" has no effect on an API create call.
The meeting is deleted after the default 5 minutes if no user has joined even when it is modified.
I use BigBlueButton Version 2.2.0-rc-6.
Thanks

**Comment by radhey7705** [comment]
Yes I also found the same issue.

**Comment by radhey7705** [comment]
I found that in the server configuration, It was set 5 min, So there was no effect if I set 10 min. through api call for create call.

**Comment by stepanBokhanov** [comment]
same issue here!

**Comment by AravindTReddy** [comment]
But the configuration in the API call should override the default properties for that specific meeting that is being created right ??

**Comment by gustavotrott** [comment]
This option `meetingExpireIfNoUserJoinedInMinutes` is available only through config file.
There are more options (e.g. `meetingExpireWhenLastUserLeftInMinutes`) that is config file only and not configurable via API.
The list of API `/create` options can be found in https://docs.bigbluebutton.org/dev/api.html#create.
