### ISSUE TITLE
Building the html5 client

### ISSUE THREAD

**Issue by nikandlv** [bigbluebutton/bigbluebutton#8702]
Hey, please provider an instruction to build and run the html5 client from the source.
I cant find any good resource for this.

I already built it with meteor build however it does not work and crashes when trying to run in production mode.

ideally provider the process of building the client and the deb file or the docker image

Thanks.

**Comment by ffdixon** [comment]
Can you try these docs and let us know if that gets you going

  http://docs.bigbluebutton.org/2.2/dev.html

**Comment by nikandlv** [comment]
> Can you try these docs and let us know if that gets you going
> 
> http://docs.bigbluebutton.org/2.2/dev.html

Yeah i followed this doc to develop however i have problems with building and deploying to a working bbb ready server

**Comment by vidukapoor** [comment]
hi @ffdixon seems some of the docs missing
http://docs.bigbluebutton.org/html/html5-overview.html

I got the above link from https://bigbluebutton.org/2017/05/17/html5-client-dev-release/

when i am using `NODE_ENV=production npm start`, it works fine but how to use create the build so that after exit also it should work, i am following the process through `/dev/bigbluebutton/bigbluebutton-html5` server path

**Comment by GhaziTriki** [comment]
The documentation moved here http://docs.bigbluebutton.org/2.2/dev.html#developing-the-html5-client

**Comment by matiasilva** [comment]
You'll need to built the meteor app and replace the files in /usr/share/meteor, haven't actually tried this, though. Does this work for you?

**Comment by suisun2015** [comment]
Hi, Have tried on the latest git source code, but it is really not working at all.

**Comment by suisun2015** [comment]
I have compared the original built directory (got from installation script from bigbluebutton team) with the one I have made from building the html5-client source according to the above document. 

First of all, they are completely different in size. 

![meteor](https://user-images.githubusercontent.com/18753299/100124654-453a1e00-2ebf-11eb-9b5b-4902cfd4ab69.png)

I am having a doubt in that the files on the public repo of the bigbluebutton github are the correct one.

**Comment by matiasilva** [comment]
Others have been able to successfully build and deploy their own versions of the client using instructions in the documentation. I'm closing this issue because the instructions are in the docs, but feel free to follow up in the developer mailing list.
