### ISSUE TITLE
/html5client path hardcoded in client, if you change path locales do not load.

### ISSUE THREAD

**Issue by hostbbb** [bigbluebutton/bigbluebutton#8717]
https://github.com/bigbluebutton/bigbluebutton/blob/0b71172e1250340e81ff5bdf67b19f36e996e3d2/bigbluebutton-html5/imports/ui/components/settings/service.js#L30

have this read from config.

**Comment by capilkey** [comment]
There's also this location that needs to be changed

https://github.com/bigbluebutton/bigbluebutton/blob/e8fc1ec444860da49cb38fdb2ac5c9cf08fcabc3/bigbluebutton-html5/imports/startup/client/intl.jsx#L124

**Comment by antobinary** [comment]
This has been adapted in https://github.com/bigbluebutton/bigbluebutton/commit/23f2df11d587306469bd4aa51e8d1f4eaab89119#diff-ff76e2e3c2685de2b69dd98aa2e190b22e046a0a9c11057981fbf9fc9d3356a4L95

Full notes on what changes need to be made to be able to change paths
https://groups.google.com/g/bigbluebutton-dev/c/6WRBwpOhMpg/m/nsc74jeYAQAJ
https://github.com/bigbluebutton/bigbluebutton.github.io/pull/236
