### ISSUE TITLE
Error if use URLEncoded

### ISSUE THREAD

**Issue by jibon57** [bigbluebutton/bigbluebutton#8727]
**Describe the bug**
I was following http://docs.bigbluebutton.org/dev/api.html#end-meeting-callback-url to add meta_endCallbackUrl by URLEncoded using PHP (urlencode()) but I am getting this error return from BBB server:

```
ERROR o.bigbluebutton.api.MeetingService - Error in callback url=[https%3A%2F%2Fwww.mynaparrot.com%2Flabs%2Fcallback.php%3FmeetingID%3Ddemoapp_test1]
java.lang.IllegalArgumentException: URI is not absolute
    at java.net.URI.toURL(URI.java:1088)
    at org.bigbluebutton.api.MeetingService.meetingEnded(MeetingService.java:724)
    at org.bigbluebutton.api.MeetingService.access$200(MeetingService.java:93)
    at org.bigbluebutton.api.MeetingService$1.run(MeetingService.java:935)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)
```

If I use without URLEncoded then it's working. Same for meta_bbb-recording-ready-url

**To Reproduce**
Try PHP SDK

**Comment by ffdixon** [comment]
I'm going to take a guess, but the `https://<hostname>/` portion shouldn't be URL encoded, just the payload after the last '/'.

**Comment by jibon57** [comment]
But in the example it was for full URL:

![image](https://user-images.githubusercontent.com/6080277/76144388-fd156a00-60a9-11ea-9d4a-f05b535e6523.png)

**Comment by ffdixon** [comment]
Ahh .. right.  I'll let one of the other developers chime in with their feedback.

**Comment by ritzalam** [comment]
It's an issue with the PHP SDK. I don't know PHP. Perhaps it is double encoding?

I tested with API Mate and it works fine.

in ```/var/log/bigbluebutton/bbb-web.log```

```
2020-03-07T07:38:31.586-08:00 INFO  o.bigbluebutton.api.MeetingService -  --analytics-- data={"duration":0,"record":false,"logCode":"meeting_removed_from_running","name":"random-7772094","description":"Meeting removed from list of running meetings.","meetingId":"f680ed27420c7c99299c2f3e495ff5081b51c23b-1583595468601","externalMeetingId":"random-7772094"}
2020-03-07T07:38:32.812-08:00 INFO  o.b.w.s.callback.CallbackUrlService -  --analytics-- data={"logCode":"callback_success","name":"random-7772094","callback":"https://bbbcallback.requestcatcher.com/test?meetingid\u003dfoo\u0026recordingmarks\u003dfalse\u0026meetingID\u003drandom-7772094","description":"Callback successful.","meetingId":"f680ed27420c7c99299c2f3e495ff5081b51c23b-1583595468601","externalMeetingId":"random-7772094","attempts":1}
```

Here is the callback endpoint on https://requestcatcher.com/

![request-catcher-callback](https://user-images.githubusercontent.com/184672/76146398-683a4e80-6060-11ea-841d-66a0fc06b80b.PNG)

**Comment by jibon57** [comment]
@ritzalam this is happening if you send request with [urlencode()](https://www.php.net/manual/en/function.urlencode.php) in PHP. Have you tried to encoded URL before sending as end-meeting-callback-url value?

**Comment by ritzalam** [comment]
No I haven't. 

I rely on https://mconf.github.io/api-mate/ for testing.

**Comment by jibon57** [comment]
I think, in PHP SDK it's doing encoding one time:

https://github.com/bigbluebutton/bigbluebutton-api-php/blob/92c370690be0c880bb1922591049918185362e4d/src/Parameters/CreateMeetingParameters.php#L756

https://github.com/bigbluebutton/bigbluebutton-api-php/blob/92c370690be0c880bb1922591049918185362e4d/src/Parameters/CreateMeetingParameters.php#L767

**Comment by jibon57** [comment]
@ritzalam according to documentation it has instructed to use url encoding before use but if I use encoded URL then get error.

**Comment by ritzalam** [comment]
Can you paste the complete request you are sending on the create api call?

**Comment by ritzalam** [comment]
Here is what I get when sending the request to https://requestcatcher.com/

![request-catcher-callback](https://user-images.githubusercontent.com/184672/76147016-43e17080-6066-11ea-934c-ac97378b6031.PNG)

**Comment by jibon57** [comment]
I think I didn't explain the problem property. The meeting is creating without any problem but when the meeting end that time no GET request was sending to the url that was sent as a value of meta_endCallbackUrl. When I saw the log I have found above error. Same for meta_bbb-recording-ready-url

**Comment by ritzalam** [comment]
Yes, I understand the issue. The endcallbackurl is passed to the bbb server on the create api call. I'd like to see what are you sending on the create api call.

**Comment by jibon57** [comment]
@ritzalam 

`https://test-install.blindsidenetworks.com/bigbluebutton/api/create?name=Cale+Rice&meetingID=372c9d96-5835-325f-a1a4-573a445c1aa3&attendeePW=h%24%3C_%23v%3C&moderatorPW=%24cc%26Y%3DTomqR&dialNumber=919.923.8979+x0825&voiceBridge=70899&webVoice=ut&logoutURL=https%3A%2F%2Fgrant.com%2Foccaecati-nihil-placeat-autem-ut-accusantium.html&record=true&duration=1829&maxParticipants=35&autoStartRecording=false&allowStartStopRecording=true&welcome=Dolores+aliquid+recusandae+ipsa+dicta.&moderatorOnlyMessage=Est+natus+laudantium+dignissimos+aut.&webcamsOnlyForModerator=false&logo=https%3A%2F%2Florempixel.com%2F330%2F70%2F%3F60843&copyright=Sit+expedita+alias+aspernatur+odio+asperiores.+Odit+iure+et+praesentium+non+velit+eaque+nobis+culpa.+Dolorem+nam+tenetur+omnis.+Facere+labore+ratione+voluptatem+sed+pariatur.&muteOnStart=1&lockSettingsDisableCam=false&lockSettingsDisableMic=true&lockSettingsDisablePrivateChat=true&lockSettingsDisablePublicChat=false&lockSettingsDisableNote=true&lockSettingsHideUserList=false&lockSettingsLockedLayout=false&lockSettingsLockOnJoin=true&lockSettingsLockOnJoinConfigurable=true&meta_endCallbackUrl=http%253A%252F%252Fwilliamson.com%252Fvero-totam-sit-molestiae-temporibus&meta_presenter=Meghan+Kerluke&checksum=e75b9d2c83625d04a25a7fe2291c89b786be624d`

**Comment by ritzalam** [comment]
The endcallbackurl is double enconded.

http%253A%252F%252Fwilliamson.com%252Fvero-totam-sit-molestiae-temporibus

The PHP SDK should remove the urlencode because the http lib I think already encodes the request.

You can confirm by decoding the url here.

https://www.urldecoder.org/

**Comment by jibon57** [comment]
@ritzalam yes, you are right

https://github.com/bigbluebutton/bigbluebutton-api-php/blob/92c370690be0c880bb1922591049918185362e4d/src/Parameters/BaseParameters.php#L33

There it's calling `http_build_query` which will encoded. I'll send pull request. Thank you!

**Comment by GhaziTriki** [comment]
The master of the PHP library contained a wrong PR. A second PR was merged to revert the changes.
