### ISSUE TITLE
Chrome Audio Connection

### ISSUE THREAD

**Issue by DrTamimi** [bigbluebutton/bigbluebutton#8736]
Dear Friends,

I have been using BBB for 5 years now the old version(flash) and it runs beautiful with some hiccups sometimes. However, I have recently changed to HTML5 BBB which looks great.

my setup is as follows

200MB upload and 400MB Download with 2 static IP addresses 

Installed BBB and TURN server using  bbb-install.sh. installations went smoothly without errors.

I setup both BBB and coturn servers  each on dedicated physical server and each has static public IP.. all recommended ports are open as advised by the installation setup.

I had few issues and seeking guidance or pointers if possible:
**First** I can connect from outside the local area network without issues.  but I **can not** connect to the server if I'am on the same local network although the old VC (flash server) works without this issue, to overcome this issue I had to add the domain name and local IP address to the hosts file in windows. is there any other way to solve this problem? .. although I have another web servers on the same network and on different ports and can be accessible without issues externally and internally. (I assume this is DNS issue) but it only came up with the HTML5 Installation not the old FLASH BBB

2nd Issue **Chrome** browser is not connecting to Audio (error 1007) without disabling windows firewall? 
Firefox is working normally without problems or disabling windows firewall.

I would appreciate some help with regard my issue.. Thank you

P.S test.bigbluebutton.org and demo both working for me without any issue

**Comment by matiasilva** [comment]
No follow up in three months. Closing for now but feel free to follow up at https://groups.google.com/forum/#!forum/bigbluebutton-setup.
