### ISSUE TITLE
Big Blue Button recording only the whiteboard

### ISSUE THREAD

**Issue by jkfreij** [bigbluebutton/bigbluebutton#8737]
Good morning, I have a problem with the audio on the recording meeting, we installed BigBlueButton Server 2.2.0 (1773) by bbb-install.sh 
Now when I record my meeting, the recording is published well only with whiteboard. someone can help to find the reason of that problem?
There is can no audio file written to /var/freeswitch/meetings when you join a recorded meeting

Thank a lot.

**Comment by GhaziTriki** [comment]
The BigBlueButton team released some updates few hours ago. https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!topic/bigbluebutton-dev/8pakzlnMkgs
Which version do you currently have?
You should be able to fix the issues if you update to `2.2.2`. Please let us know if it works.

**Comment by jkfreij** [comment]
Thank you for your reply, I'm using BigBlueButton version 2.2.0

**Comment by ffdixon** [comment]
Can you upgrade you server and make sure your version is 2.2.2

After the upgrade, let us know if audio now recordings again for you.

**Comment by jkfreij** [comment]
Thank you, the upgrade fix this issues.

**Comment by german2209** [comment]
Hi Fred,
If I installed a new server following the step by step procedure do I
upgrade using apt-get dist-upgrade or can I use the install.sh script?
Regards,
German Acevedo

**Comment by ffdixon** [comment]
Recommend you use the [bbb-install.sh](https://github.com/bigbluebutton/bbb-install) as it automates pretty much all the install steps and is much less error prone.

**Comment by german2209** [comment]
I'll do this way on the weekend. Thanks for your support.
Regards,
German
