### ISSUE TITLE
Installation on Ubuntu higher than 16.04

### ISSUE THREAD

**Issue by LuigiElleBalotta** [bigbluebutton/bigbluebutton#8738]
Sorry for not using a template, but i'm opening this issue since bigbluebutton.org is offline:
![Schermata 2020-03-09 alle 10 02 42](https://user-images.githubusercontent.com/16773213/76197810-225ec100-61ed-11ea-9200-29a3380e73a7.png)

The problem is:
in Italy we have CoronaVirus, some of us can't move so we need to do "Smart Working".
In my company we found your tool very useful, but most of the companies in italy have Windows Server or (like us) Ubuntu server at latest version.
So the question is: is there a way to install this software on Ubuntu 18.04 or 19.10?
Thanks for the help!

**Comment by GhaziTriki** [comment]
Hello @LuigiElleBalotta,

The BigBlueButton team is aware of it, our monitoring system alerted few hours ago. All the team is putting their efforts into getting it up very soon.

Thank you

**Comment by GhaziTriki** [comment]
And regarding BigBlueButton server, the 2.2.0 release works only on 16.04. Ubuntu 18.04 is planned to be used for 2.3.0.

**Comment by LuigiElleBalotta** [comment]
Hello @GhaziTriki 

Do you have an estimated time when it will be ready?

**Comment by GhaziTriki** [comment]
You can find an answer here https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!searchin/bigbluebutton-dev/release$20on$20quality%7Csort:date/bigbluebutton-dev/m4AmLv7Y5No/_HvrgkqFAgAJ

If you have any suggestion don't hesitate to share it with the community https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!searchin/bigbluebutton-dev/2.3|sort:date/bigbluebutton-dev/c4Pl84-DQY0/unBBYD9DDAAJ

BigBlueButton 2.3 is bringing a some interesting surprises. @ffdixon The product manager will share more piece of information when it is time. Stay tuned !!

**Comment by ffdixon** [comment]
@LuigiElleBalotta  Can you try bigbluebutton.org now and let us know if you can access it.

**Comment by LuigiElleBalotta** [comment]
@ffdixon yes sir, it is available now

**Comment by mipreuss** [comment]
is BigBlueButton 2.3 published with support for Ubuntu 20.04? And is it possible to get BigBlueButton 2.3 now?

**Comment by slel** [comment]
Should this be closed in favour of #8474?

**Comment by ffdixon** [comment]
Merged into https://github.com/bigbluebutton/bigbluebutton/issues/8474.

**Comment by mipreuss** [comment]
Not closing, it has different goals!

Wie tolken about support for 20.04 and not only the old 18.04!
