### ISSUE TITLE
Duplicate users on (large?) meetings

### ISSUE THREAD

**Issue by ritzalam** [bigbluebutton/bigbluebutton#8740]
**Describe the bug**
Users are duplicated in the users list. It's probably the client reconnected and the user tied to that old connection doesn't get cleaned up.

**To Reproduce**
1. Cannot reproduce the issue. Observed on meetings with large number of users. Although haven't really looked if this happens too on small meetings.

**Expected behavior**
Users shouldn't be duplicated. We also need to provide a way to double check the users list to confirm that these are duplicates. 

**Actual behavior**

**Screenshots**
<img width="150" alt="duplicate-users" src="https://user-images.githubusercontent.com/184672/76226977-fba48880-61f4-11ea-913c-655c655abd9b.PNG">

**Comment by helios-ventures** [comment]
Hello, @ritzalam This duplicate user issue arises when your clients/users have a poor connection and they try to re-login again into the meeting, the previous session is not canceled and continues to exist. It can also be attributed to your server nearing its maximum number of sessions it can handle, after this, your current and new users will be unable to join the ongoing meeting.

I've encountered this and I overcame it by changing the "allowDuplicateExtUserid=false" to false in the "File: /usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties".

Also, keep your maximum concurrent session at below 100 as stipulated on the "system requirements" by BBB team

If you have more than 200 sessions actively running on the server, It's time to implement scalelite.



I don't have any duplicate users now.

**Comment by mailalaki** [comment]
But in our experience this does not happen only when the connection of users is poor! Because it happens to most people. Those who usually do not have a problem!

**Comment by sureronald** [comment]
@mailalaki , you still experience this with this setting in place: **"allowDuplicateExtUserid=false"**?

**Comment by SeniorTigr** [comment]
We have similar problem in our BBB environment and setting the option allowDuplicateExtUserid=false didn't help. I suppose it is because of the problem described in #9354

**Comment by jklindzic** [comment]
We have the same issue, not necessarily related to user's poor connection. Version 2.2.28

**Comment by MattiaMunari** [comment]
We are currently experiencing this issue, not related to user's poor connection nor server capacity. It appeared after upgrading to 2.2.31 and it make session end for users without making them able to reconnect again.

**Comment by GhaziTriki** [comment]
I confirm we had that issue a week ago on a server with version 2.2.31

**Comment by ffdixon** [comment]
There has been a substantial amount of work in 2.3 to rewrite the connection manager to resolve this issue.

**Comment by antobinary** [comment]
Please open a new issue (with as lots of background info) if this is encountered on BBB 2.3.15+ or 2.4+

**Comment by epabitra3** [comment]
I am using Big Blue Button 2.4.5 and I also got the same issue while re-joining the meeting, everytime a new user added to the user list while i am re-joining with the same user.

While i am calling the API everytime i pass the same url but while it return it create different sessionToken everytime and a new user with same user name added to the user's list.

**Comment by antobinary** [comment]
Hi @epabitra3 
BigBlueButton 2.4 is already unsupported for several months. Please upgrade to 2.6. That should also resolve the issue you're hitting.

**Comment by epabitra3** [comment]
Hii @Anton Georgiev

Thank you so much for your help, I will update our version as soon as
possible.

Best regards,

E Pabitra
7377618313

**Comment by epabitra3** [comment]
Subject : Issue with Microphone Enablement in BBB 2.6.x

Dear Mr. Georgiev,

I hope this email finds you well. As per your instructions, I have
successfully upgraded BBB to version 2.6.x, which resolved the duplicate
user creation problem. However, we are now encountering a new issue with
enabling the microphone. The error message displayed is "Failure on call
(reason=ICE error) (error 1004)."

I kindly request your assistance in addressing this matter. I have attached
detailed screenshots for your reference, which may provide additional
insights into the issue.

Your guidance and support in resolving this matter are greatly appreciated.

Thank you for your time and consideration.

[image: step 1.png]
[image: step 2.png]
[image: step 3.png]


Sincerely,

E Pabitra

**Comment by paulmenzel** [comment]
@epabitra3, this issue is closed, and the new issue in your comment is a *new* issue. Please create a new issue.
