### ISSUE TITLE
Mute/Unmute button no longer to be seen

### ISSUE THREAD

**Issue by tejaskarelia17** [bigbluebutton/bigbluebutton#8745]
Hi,

I am using BigBlueButton 2.2.0-beta-18 with greenlight. I have configured the software and SIP behind a NAT firewall. When I join/create a room, I am unable to see the mute/unmute button nor am I able to mute others. How can I fix this? Following attached are screenshots for better understanding.

<img width="1680" alt="Mute:unmute" src="https://user-images.githubusercontent.com/11533007/76272197-f3217180-6237-11ea-9853-8f4339a8e50c.png">

**Comment by ffdixon** [comment]
Hi there,

Can you upgrade to BigBlueButton 2.2.2 and let us know if the problem still persists.   If you installed BigBlueButton using `bbb-install.sh`, just re-run the command you used to do the initial install and it will take care of upgrading you to the latest release.

**Comment by tejaskarelia17** [comment]
Hi Fred,

Updating it to 2.2.2 worked. Thanks for your quick response to the issue 😁 👍
