### ISSUE TITLE
Fix layout in browser incompatibility message on mobile

### ISSUE THREAD

**Issue by Brullworfel** [bigbluebutton/bigbluebutton#8749]
Please fix layout in browser incompatibility message on mobile devices. The message does not fit the screen.

**To Reproduce**
1. Go to http://demo.bigbluebutton.org/ with Google Chrome on iPhone;
2. Enter any room.

**Screenshots**
![IMG_2563](https://user-images.githubusercontent.com/12401672/76298042-85218c80-62c1-11ea-8866-2f376c0514e5.PNG)

**Smartphone:**
 - Device: iPhone 7
 - OS: iOS 13.3.1
 - Browser: Google Chrome
 - Version: 80

**Comment by pedrobmarin** [comment]
Being covered at https://github.com/bigbluebutton/bigbluebutton/issues/8414
