### ISSUE TITLE
Could not connect to the configured hostname/IP address

### ISSUE THREAD

**Issue by likai3016218058** [bigbluebutton/bigbluebutton#8763]
Hello!
In the process of manually configuring SSL, I use self signed certificate, local IP, and only want to develop and test locally. However, after the certificate is configured, the display cannot open the default web site. Before SSL was configured, the site worked well.

# Error: Could not connect to the configured hostname/IP address
#
#    https://192.168.18.2/
#
# If your BigBlueButton server is behind a firewall, see FAQ.

# Error: Unable to reach default URL for presentation:
#
#    https://192.168.18.2/default.pdf
#
# Check value for beans.presentationService.defaultUploadedPresentation in

**Comment by alejandrohdo** [comment]
I get the same error, can someone know what is the cause?
