### ISSUE TITLE
Confirm button for "Back" key

### ISSUE THREAD

**Issue by rogercong** [bigbluebutton/bigbluebutton#8764]
Hello,

Is there possible to put confirm message if a person pressed "Back key" during the conference.  Sometimes, people attend the conference and accidentally press BACK KEY, and s/he will be out of conference room and have to re-sign in again.  So can we place a confirmation message, and need to confirm they want to exit.

Roger

**Comment by rogercong** [comment]
This problem is happening quite often when people are using mobile access conference, whenever they went to public chat and instead of press chat icon and pressed back button from mobile phone.

**Comment by mjohenneken** [comment]
I was just about to open an issue for this I first posted [here](https://github.com/bigbluebutton/greenlight/issues/1325) 

 I'm thinking of displaying a dialog "Do you really want to leave the active conference?", with answers leave / stay.

sample impl. - https://stackoverflow.com/questions/7317273/warn-user-before-leaving-web-page-with-unsaved-changes

**Comment by matiasilva** [comment]
The user should just be able to go back again and access the session rather than having to access via the frontend, the session token will not expire that quickly. Is anyone interested in giving development of this a go? Otherwise, I'll close this as nobody has shown much interest.

**Comment by mjohenneken** [comment]
I think in a mobile browser it's still a usability issue, as it reduces explorability of the UI. I fixed it as part of a native Android App.  I won't mind if you close it for now, though I'm not OP

**Comment by matiasilva** [comment]
Sounds cool. Could you share that with the community?

**Comment by mjohenneken** [comment]
The idea is to Intercept the request using [WebViewClient.shouldInterceptRequest](https://developer.android.com/reference/android/webkit/WebViewClient.html#shouldInterceptRequest(android.webkit.WebView,%20java.lang.String)) checking if the URL matches that of a conference session (i think it was `html5client`). Based on that you display a native Dialog and proceed to load the previous page if the user confirms it.

The app I'm working on is currently suited to a specific BBB Instance, however it is in the discussion whether we start working on a more general native BBB Client for Android and if it is open-sourced.

**Comment by matiasilva** [comment]
Sounds great. Please keep us updated, we encourage you to open source it so others can chip in and help :)

**Comment by matiasilva** [comment]
Merging with #10036
