### ISSUE TITLE
bigbluebutton Installation error ?

### ISSUE THREAD

**Issue by mohamedsalman** [bigbluebutton/bigbluebutton#8769]
**Describe the bug**
After install bigbluebutton not working with Error 

# Potential problems described below
# Not running:  LibreOffice
................................................................................
# Error: Could not connect to the configured hostname/IP address
#
#    http://192.64.113.178/
#
# If your BigBlueButton server is behind a firewall, see FAQ.

# Warning: The API demos are installed and accessible from:
#
#    http://192.64.113.178
#
# and
#
#    http://192.64.113.178/demo/demo1.jsp
#
# These API demos allow anyone to access your server without authentication
# to create/manage meetings and recordings. They are for testing purposes only.
# If you are running a production system, remove them by running:
#
#    apt-get purge bbb-demo

**Expected behavior**
bigbluebutton server run 

**Actual behavior**
Server error output and not working

**Comment by german2209** [comment]
Try sudo bbb-conf --setip your.domain.com

**Comment by matiasilva** [comment]
Closed due to inactivity. Feel free to follow up on https://groups.google.com/forum/#!forum/bigbluebutton-setup.
