### ISSUE TITLE
speed up recordings process 

### ISSUE THREAD

**Issue by freehussain** [bigbluebutton/bigbluebutton#8770]
we have an university that use virtual classroom , we have a lot of recording every hour and our server need long time to process these recording. is there any way to make it faster ? 

i have cpu with 16 core , also i tried to increase number of thread on ffmpeg command, but it still the same .

anyone have an idea to do it

**Comment by ffdixon** [comment]
BigBlueButton 2.3 (next version) will have a proper queue system for handling processing of recordings and you'll be able to allocate more than one worker to have recordings processed in parallel.

**Comment by hhuseyinpay** [comment]
@ffdixon Do you have an estimated release date for 2.3?

**Comment by davidrojo** [comment]
We are experiencing the same problem, due to COVID-19 all teachers of our school are doing online classes to the students so recording is being too slow.

In fact currently we have a recoring that has been 2 and a half hours running and is not finished yet

```
# ps aux | grep ffmpeg
bigblue+  5335  163  0.2 1275300 95000 ?       Sl   14:25 241:41 ffmpeg -y -v warning -nostats -max_error_rate 1.0 -i /var/bigbluebutton/recording/process/presentation/9fea632cdb21625185d5e9cea5e8e90ea0a63c61-1584356268050/webcams.ts -i /var/bigbluebutton/recording/process/presentation/9fea632cdb21625185d5e9cea5e8e90ea0a63c61-1584356268050/recording.flac -c:v libvpx-vp9 -b:v 750K -minrate 375K -maxrate 1088K -crf 33 -quality good -speed 1 -g 240 -tile-columns 1 -threads 2 -c:a libopus -b:a 48K -f webm -passlogfile /var/bigbluebutton/recording/process/presentation/9fea632cdb21625185d5e9cea5e8e90ea0a63c61-1584356268050/webcams /var/bigbluebutton/recording/process/presentation/9fea632cdb21625185d5e9cea5e8e90ea0a63c61-1584356268050/webcams.encode.webm
```
It is processing a webcams.ts file that is almost 1Gb (1,5 hour of class).

@ffdixon is it normal the .ts file and the length of the file? I'ts the first time I see this extension in BBB.

**Comment by akasarov** [comment]
Modifying the ffmpeg parameters should help. I found them set in this file
"/usr/local/bigbluebutton/core/lib/recordandplayback/generators/video.rb"

https://github.com/bigbluebutton/bigbluebutton/blob/v2.2.x-release/record-and-playback/core/lib/recordandplayback/generators/video.rb#L58
https://github.com/bigbluebutton/bigbluebutton/blob/v2.2.x-release/record-and-playback/core/lib/recordandplayback/generators/video.rb#L124

You can check this guide 
https://trac.ffmpeg.org/wiki/Encode/VP9

Setting threads to 4 should speed things up a bit.  Setting quality to realtime should speed it up alot.

BUT I haven't tried any of this yet because I need to shut down the server and increase cpu cores. 
Does anyone know what happens with the recording being processed and those waiting if the server is shut down during processing(ffmpeg)?

**Comment by davidrojo** [comment]
@akasarov I've played with the video.rb, increasing threads didn't did any performance improvements, the only parameter that improved the perofrmance was the -speed, setting a value of 5 did improve, but not enough.

@freehussain I've been able to speedup processing time from 3 hours to 20 minutes for a video changing webm to mp4.

https://docs.bigbluebutton.org/2.2/customize.html#enable-playback-of-recordings-on-ios

Commenting webm and uncommenting mp4 did the trick

@ffdixon Is there any license issue using mp4?

**Comment by akasarov** [comment]
Yes, I also tested it, increasing only threads didn't do anything, but
"-quality realtime -speed 5 -tile-columns 2 -threads 4" 
like this, the encoding speed incresed 5-6 times.

Very good guide - https://developers.google.com/media/vp9/live-encoding

**Comment by lonesomewalker** [comment]
This also depends a lot on the cpu.

**Comment by relecand** [comment]
Hi,

first of all: Thank you for BBB - it is great! We have a server with 24 CPU and 32 GB RAM.

Currently there is a problem that the recordings are not rendered. The process appears to have stopped.

![grafik](https://user-images.githubusercontent.com/5286499/77435963-3278c200-6de3-11ea-8201-e6b06b33a31e.png)

![grafik](https://user-images.githubusercontent.com/5286499/77436169-72d84000-6de3-11ea-8b41-f4d4b9dea677.png)

We are using the Moodle plugin to start and record BBB sessions.

I transfered some recordings to a test server - and there were rendered without problem. Does the processing start when there are currently no recordings?

![grafik](https://user-images.githubusercontent.com/5286499/77436648-0742a280-6de4-11ea-8ef4-deabf601c949.png)

Thank you in advance and all the best,

Christian

**Comment by relecand** [comment]
Just an update to my post above: Recording processing is running again.

I checked the presentation logs:

```
ls -gt /var/log/bigbluebutton/presentation

process-4eb9092905d416443083252057841xxxx.log
```

There I found a process log. The rendering of that recoring caused the stop. 

Then I did a backup of that recoring:

```
cp -r /var/bigbluebutton/recording/raw/a6aa58bc771ba465f87d2d906dcdcxxxx /home/xxx/
```

and deleted it:

```
bbb-record --delete a6aa58bc771ba465f87d2d906dcdc25bbxxxxx
```

The restarted bbb
```
bbb-conf --restart
```

**Comment by marializ** [comment]
We used recommendations from akasarov "-speed 5 -tile-columns 2 -threads 4" now records are being processed much faster, as akasarov mentioned ~5-6 times faster.

**Comment by caglaroflazoglu** [comment]
"-speed 5 -tile-columns 2 -threads 4" is very good solution.

**Comment by relecand** [comment]
Yes, but be carefull, because it uses a more CPU which can influence the performance of BBB.

**Comment by caglaroflazoglu** [comment]
> Yes, but be carefull, because it uses a more CPU which can influence the performance of BBB.

I changed the code and started working with 30 cpu and 13 parallel workers(worker watch sanity done files which not processing or processed). This solved the problem of time. Currently, each video recording is processed very fast. The tail completes very quickly. This reduced the continuous use of CPUs. This process is very performance compared to the previous one. Parameters can be adapted for cpu/ram usage

**Comment by coffeduong** [comment]
Hi @caglaroflazoglu what's your server spec?

**Comment by caglaroflazoglu** [comment]
2 socket x 15 CPUs (totaly 30 CPUs) + 40(min) to 120(max) GB RAM, Ubuntu 16.04

We work with 13(max) parallel workers (bbb-rap-process-worker-[0-12].service --> rap-process-worker-[0-12].rb, with this we can change dynamically the number of workers). Ruby watches sanity done files. I replaced the code for watching processing sanity files, too. The default ruby script gets all done files and processes one by one. In our code breaks the loop after processing the file (or when not found a valid file) to get another one with the service execs. 

For example, 
22 sessions (total 92 users (Webcam:35, Mic:53)) + 9 bbb-rap-process-workers max cpu usage %67-73

"Sanity files" are finished very fast with this code change by bbb-rap-process-workers. CPUs will be free earlier than before

**Comment by iSamof** [comment]
@caglaroflazoglu - are you using VMs or bare metal dedicated servers?

**Comment by caglaroflazoglu** [comment]
VM on Proxmox

**Comment by iSamof** [comment]
@caglaroflazoglu - Thank you for all the info and this response.

**Comment by bigbluemeeting** [comment]
@caglaroflazoglu please share code.

**Comment by edmilsonaj** [comment]
> 2 socket x 15 CPUs (totaly 30 CPUs) + 40(min) to 120(max) GB RAM, Ubuntu 16.04
> 
> We work with 13(max) parallel workers (bbb-rap-process-worker-[0-12].service --> rap-process-worker-[0-12].rb, with this we can change dynamically the number of workers). Ruby watches sanity done files. I replaced the code for watching processing sanity files, too. The default ruby script gets all done files and processes one by one. In our code breaks the loop after processing the file (or when not found a valid file) to get another one with the service execs.
> 
> For example,
> 22 sessions (total 92 users (Webcam:35, Mic:53)) + 9 bbb-rap-process-workers max cpu usage %67-73
> 
> "Sanity files" are finished very fast with this code change by bbb-rap-process-workers. CPUs will be free earlier than before

can you share your modified scripts?

**Comment by ostasevych** [comment]
Are any estimations of the time needed to convert and publish the file depending on the hardware and the length of the recorded session?

**Comment by runout-at** [comment]
After upgrading BBB the changed ffmpeg arguments in `/usr/local/bigbluebutton/core/lib/recordandplayback/generators/video.rb` are lost.

should this go to a different issue?

**Comment by ffdixon** [comment]
To avoid loosing any custom configurations after package updates, see http://docs.bigbluebutton.org/2.2/customize.html#automatically-apply-configuration-changes-on-restart

**Comment by runout-at** [comment]
Thanks! But this was just an `apt update; apt upgrade`. Not running the install script.

Normally on Debian based systems it is not expected to overwrite config changes. But in this case it seems to be a patch in the code when changing the arguments. Thats why i'd prefer a solution with a config file in /etc/...

**Comment by AkeMake** [comment]
> "-quality realtime -speed 5 -tile-columns 2 -threads 4" is very good solution.

I am planning to use this to speed up recordings process, but isn't this permanent change? What if I want to change back to original settings, what parameters should I choose?

**Comment by AnthonyVidal** [comment]
> @ffdixon Do you have an estimated release date for 2.3?

@ffdixon  Do you have a date? because the same thing is happening to me for the university that we implement despite the fact that it has a good server, the recordings are taking time to show in Moodle.

Is there a way to improve this with the current version of BBB 2.2?

Very thankful

**Comment by hmahdi-s** [comment]
@akasarov @caglaroflazoglu 
'-quality realtime -speed 5 -tile-columns 2 -threads 4'
can u explain it simple?
how should we use it?
is it a command or we should edit a file with that code?

**Comment by akasarov** [comment]
@hmahdi-s 
In /usr/local/bigbluebutton/core/lib/recordandplayback/generators/video.rb you can replace the ffmpeg parameters with those.
Read my first post, there are links to the lines you want to change. Just change them and save the file, you dont even need to restart bbb. Instead of the defaults "-quality good" put "-quality realtime", instead of "-speed 1", put "speed 5", etc. It will reduce the video quality a little and use 4 cores instead of 2, but it will speed up processing alot.

But with updates, they might be overwritten back to default, so figure out how to make them persistent or check that file after every update.

**Comment by hmahdi-s** [comment]
@akasarov 
thank you
I changed it and hope it will effective.

but in the comment says: "Increase -threads to max of 4 or increase -speed to max of 4 to speed up processing"
despite, Is it true option to change it more than 4?

**Comment by zakachkin** [comment]
After the changes made, the situation has not changed. Restarting BBB and server completely. Still no more than 2 streams. BBB version 2.2.28

**Comment by cod3r0k** [comment]
I want to speedup the processing of the recording with Full CPU usage ASAP in midnight. How can I implement my idea?
The solution which mentioned in this thread, is not responsible well. Please help me. (My BBB is 2.2)

It is just use 20% of my 8 core cpu.

@ffdixon @freehussain

**Comment by Davka** [comment]
@cod3r0k you could try edit /usr/lib/systemd/system/bbb-record-core.timer

```
[Unit]
Description=BigBlueButton record & playback processing timer

[Timer]
#OnActiveSec=0
#OnUnitInactiveSec=30s
OnCalendar=*-*-* 0-5,21-23:*:00
Unit=bbb-record-core.target

[Install]
WantedBy=timers.target
```


```
systemctl daemon-reload
systemctl restart bbb-record-core.timer
```

**Comment by poncesanchez** [comment]
> @akasarov I've played with the video.rb, increasing threads didn't did any performance improvements, the only parameter that improved the perofrmance was the -speed, setting a value of 5 did improve, but not enough.
> 
> @freehussain I've been able to speedup processing time from 3 hours to 20 minutes for a video changing webm to mp4.
> 
> https://docs.bigbluebutton.org/2.2/customize.html#enable-playback-of-recordings-on-ios
> 
> Commenting webm and uncommenting mp4 did the trick
> 
> @ffdixon Is there any license issue using mp4?

Hi/Hola @davidrojo , can you give more detail in what line are you commenting/uncommenting web/mp4?

(https://github.com/bigbluebutton/bigbluebutton/blob/v2.2.x-release/record-and-playback/core/lib/recordandplayback/generators/video.rb#L58)
