### ISSUE TITLE
No Audio at all after 30 minutes (also after emergency restart....)

### ISSUE THREAD

**Issue by tomlp** [bigbluebutton/bigbluebutton#8774]
**Describe the bug**
we had a conference today (regarding Corona) and many participants of the company log in into to the room (> 300 session - the count after encoding the session show 147 Participants ?!).
After 30 minutes running of the meeting (primary the phase of preparations) the sound stops unexpected.
The load grows up to 500.00 (really) and we decide to restart the VM.
After the successful restart, we had no more audio if we connect to the room. The Audio indicator on the bottom shows no more activity....

**To Reproduce**
Invite enough Participiants

**Expected behavior**
the Audio will be heard by all participants 
after restart - the sound should work again

**Actual behavior**
no one hears anything after minute 30

**Screenshots**

**Desktop (please complete the following information):**
 - OS: win10; Fedora 31
 - Browser Firefox
 - Version 73.0.1

**Server**
- Ubuntu 16.04
- BBB 2.2.2
- 8 vCores
- 10GB RAM
- 1,3 TB of storage (300GB used)

**Additional context**
one of the error messages in the red5-logs they is unexpected:
WARN  o.s.w.s.h.SimpleUrlHandlerMapping - Neither 'urlMap' nor 'mappings' set on SimpleUrlHandlerMapping

After this failure happens, i investigate depp and depper. I cleared all logs an restart to get a clearer picture of the failure. 
I installed java-8-jdk, as suggested by a other ticket.
At least i restored the Image from a snapshot - BUT i give it a last try and it works now as before....
My question is : Is there a limit with opus ? It seams that opus is new as recording audio solution....
Iam aware that this amount of session is very high, but the video and chat are very smooth in the enconding until minute 47 (stop of the conference and restarting the server).
Only the audio is fail after minute 30... 
kr Tom

**Comment by capilkey** [comment]
I doubt OPUS factors in here. It's likely just the load on the server causing strange issues. BigBlueButton isn't designed for 300 users in one conference.

The output from "bbb-conf -check" will warn you of basic issues and should be run after "bbb-conf --clean" or "bbb-conf --restart". Also both of those options should be used to restart rather than turning off the VM and turning it back on again.

**Comment by tomlp** [comment]
I am aware of the "strange" against a power off, but the system whose not responsible on any other way (by a load of 500.00). 
It whose not our intention to invite 300 Users  !!!! It happens regarding the topic where the conference is announced. 
By the way : could anywhere set a upper Limit for a Room ? 
I think the main problem comes with some users they are kicked out and try to re-establish the connection. So the old connection whose on and the new one also (i saw in a count usage statistic - based on the number of current SSL-connections) that one user had 6 connections.
So not really 300 Users where there, but 300 Connections. Of course : if the count of participiants after the encoding is true (147) there are also over the recommended Count. How can we control it ?

by the way : after the server comes up again, i try all of your suggested commands. I saw that tomcat7 is not started and i investigate that. Regarding a other Ticket i reinstalled jdk-8 and tomcat7 is back.
But on this time the Audio is not back (as i checked at this time)....
The downfall and the reparation is not currently my issue:
-) What happend in general ? (maybe Opus ?)
-) How can i avoid of this ? (how we set a maximum per Room/per Server)
-) How many Users can connect to the Server ? (NOT to one conference - i mean in summary : for example we have 10 conferences at the same time and every conference had between 8 and 15 participiants. I am aware of the recommendations of the max of 50 participiants, but per conference or per server ?
kr Tom

**Comment by capilkey** [comment]
I don't know what front-end you're using, but there is a `maxParticipants` property that can be set on the meeting create API call. Some front-ends have a configuration to set it and some don't. It can also be configured server-wide in bigbluebutton.properties.

You can ease resource usage by enabling the microphone lock, and webcam lock (or webcamsOnlyForModerator).

Regarding tomcat7 not running. That only matters if you're using the API demos which shouldn't be installed on a production server anyways.

The original issue of sound stopping could be FreeSWITCH crashing or the person talking losing connection. Enabling the microphone lock should cut down on resource usage on the server.

The amount of users on a server depends on the power of the server and what is happening in those meetings. I don't think the specs you listed could handle 1500 concurrent users. I would recommend 500 or less on one server even if it's a beefy one. Restricting webcams and microphone goes a long way for helping with this.

Regarding the sound not working after restart, you'll need to post the full output from `bbb-conf --check` and `bbb-conf --status`.

**Comment by tomlp** [comment]
thank you - you helped with your suggestions. Stupid don't think about by ourself (i am called for help where its to late...)
I use Greenlight as Portal to BBB - but there is only a limit how many rooms a moderator can create. Not the participants he can invite/hold in room
I will create a enhancement issue to Greenlight....
bbb-conf --check and --status show no unexpected results. 
I run bbb-conf --setip (as suggested by the upgradenotes to 2.2.0). but this didn't also help. 
I am not sure in the end what brings the audio back, but for now it is working again....
Hopefully its not happens again :D 
kr Tom

**Comment by matiasilva** [comment]
Good discussion. Closing as the issue has been solved.
