### ISSUE TITLE
BBB-Farm

### ISSUE THREAD

**Issue by tomlp** [bigbluebutton/bigbluebutton#8777]
**Describe the bug**
i see only scenarios that describes installing one server

**Installation type**
.n.a.

**Console output**
n.a.

**Additional context**
In my mind comes up the possibility to install more than one server, controlled by one instance of Greenlight.
It has the advantage that the resources can be expand on there needs (currently the awareness of Home-Working and the lake of a stable conferencing solution). If the servers are overloaded it would nice to "enable" the next server where the next conferences can run. I don´t think currently on a "balancing" of conferences, but this would be a nice idea too :) 
kr Tom

PS: i love the idea and the concept of BBB - it´s a really great solution and all of you do a awesome job...

**Comment by capilkey** [comment]
A load balanced service is the recommended way to scale BigBlueButton. Lots of 8 core 16-32GB machines.

There was a post on the mailing list that might be of interest to you, https://groups.google.com/forum/#!topic/bigbluebutton-dev/T3WKHrwpTnQ. There are also companies that have created their own environments.

**Comment by tomlp** [comment]
THX - you are a genius - exactly what i search/need ....
i give it a try and report back soon.
Have a nice day - a stay healthy ;)

**Comment by tomlp** [comment]
Dear capilkey,
big thx for your suggestion - i installed all components and it seams that all of them are connected.
It was very hard to set it up (the documentation is very poor .... the first impression of the documentation is awesome, but in details there are some missing parts)
**In the end : The guys do a great job !!!**

kr Tom

**Comment by iSamof** [comment]
I've been watching this thread with interest. Indeed, thanks to the entire BBB team for their superb work. 

And thanks to @tomlp for stating that he has already had success in implementing the load balancing structure. 

Hey Tomlp ... how about documenting the missing parts of the documentation and contributing the full working installation process to the community :-)    THAT would be fabulous.

**Comment by ffdixon** [comment]
@tomlp Send us a pull request with your improvements to the docs and we'll review & merge.

**Comment by tomlp** [comment]
@iSamof,
i am so sorry - i was so impressed that it run´s in the end :)

The first think that is not pointed out: The connection from redis & postgresql.
The connection URL's has to be the IP-addresses of the machine (in my experience) while the connection comes from the docker-container (172.xx.xx.xx) and not localhost !
and the corresponding configurations in postgres have the IP-Adresses of the Docker too, to get a prober connection.
How to efficient set up the NFS-Server whould be helpfull to (regarding the needs of scalelite).
in the exports i addes "(rw,async,all_squash,anonuid=1000,anongid=2000,nohide)" as options to the share, the permission are allways set to the proper permission for the (fixed uid in the)  container.

And yes - i will do my best to bring in my little experience into to documentation :)
kr Tom

**Comment by iSamof** [comment]
Excellent thank you Tom - I worked on IBM systems since the 90's ... I get lost in the details of these other technologies. But my team will be able to follow and also implement your process, when we come to scaling up, which is little further down the line for us. 

MANY THANKS Tom & BBB Team

**Comment by tomlp** [comment]
@all 
i read about contributing and needs some time to go into this.
A first shoot : 

I assume you installed PostgreSQL 10 ( from https://www.liquidweb.com/kb/install-and-connect-to-postgresql-10-on-ubuntu-16-04/ )
Afterwards you edit `/etc/postgresql/10/main/pg_hba.sql` : 
`host    scalelite       scalelite       172.18.0.2/32           trust
host    postgres        scalelite       172.18.0.2/32           trust`
The IP-Adress comes from the Docker-Container !!!
It´s connects over the docker network and NOT from localhost !! (<= Mindbreaker :) )

After them you should bind PostgrSQL to the corresponting IP-Address/Interface. 
In `/etc/postgresql/10/main/postgresql.conf` you look for the line `listen_address` and remove the # in front. You have also change the value to the IP-Address or to bind an all interfaces to * : 
`listen_addresses = '*'`

After restarting postgresql you should be able to connect via : 
`DATABASE_URL=postgresql://bbb-cluster.xxx-yyy.com:5432`

I used the FQDN but the IP-Address should be enough to connect....

kr Tom

**Comment by matiasilva** [comment]
Hello. Have you been able to submit these changes to the Scalelite repository READMEs?

**Comment by prlanzarin** [comment]
Closing this due to lack of feedback. If it's still a thing, recommend re-directing it to Scalelite's repo.
