### ISSUE TITLE
BigBlueButton 401 No autorizado

### ISSUE THREAD

**Issue by JohnOfAllTrades** [bigbluebutton/bigbluebutton#8780]
Hi, I'm trying to set up my classroom as a virtual classroom and upon testing BigBlueButton every time I try to start a new session three dots appear and then after a while it gives a 401 No autorizado (Not authorised) message. I have tried many times and with different classes. This was the second time I was testing. The first time I connected fine and my wife was able to connect to the class on her phone. The second time some hours later we tried the same on her mac computer and the 401 Not Authorised message is the only result I get. 

I have no idea about coding or programming unfortunately so I have no clue how I can resolve this issue or why it is going wrong. 

Any help would be greatly appreciated!

**Comment by alfonsofernandezyf** [comment]
Hi, that error shows when you are using a link that has expired or when you
are not authorized.

Autentication Is controled by the frontend like Greenlight ir Moodle.

It Is normal to ver that message when you are using an old link. It Is
suposed yo block unwanted visitors.

**Comment by JohnOfAllTrades** [comment]
Hi and thank you,

I created a new classroom and this worked. How do I create a new link for a classroom that I created before? I have closed the browser, updated my computer and opened BigBlueButton again and this did not provide a new link to share. I dont see any way to refresh this other than in configuration > generate new access code > Update Room but this only created a number (I suppose to give to students to enter the room?) but the link of the classroom remained the same.

It's probably something obvious right in front of my eyes but I'm not seeing it. I can work around it by creating new rooms every time, but I would guess there is a more efficient way to avoid this problem?

Thanks again for such a quick reply!!

**Comment by alfonsofernandezyf** [comment]
How are you creating the rooms? Which front end are you using?

The front end on which you are creating the rooms manages the sessions 
and authorizes users to either start or enter a certain room.

**Comment by JohnOfAllTrades** [comment]
At the moment I am just clicking on the + Create Room  and naming the room eg. Test and then sharing the link with my wife to see if she is able to join. After closing the session after the first test I shared the link that appeared for that room again and that's when I ran into the problem. So at the moment no authorisation is being required to join the room other than having the link. 

Sorry I dont know what a front end is. I'm just testing things out for the first time really, so very clueless. Does that mean another app which combines with Big Blue Button somehow to manage things? I'm just directly on the Big Blue Button start page.

**Comment by JohnOfAllTrades** [comment]
Hi, so I've done some reading and realised that is going to be far less simple than I had hoped (which is what drew me to Big Blue Button in the first place). I am using the public server (demo version I guess). Now I am getting the 401 error constantly even when I create a new room and try to enter which is hugely frustrating. I deleted all rooms (main room cant be deleted) and created a new room > start session > 401 error. Rebooted computer and done it again > same 401 error. 

Will I not be able to host sessions on the public server (demo version)? I have no interest in recording or keeping sessions. I just want an easy way to connect to my students that they just click on a link and join the virtual classroom with me. 

Thanks again for any light that can be shed regarding the limitations of the public server (demo version)

**Comment by JohnOfAllTrades** [comment]
Now when I do get in ... which seems random ... It will disconnect me, and I can no longer get in > error 401.

Could this be a anti-virus issue?

**Comment by JohnOfAllTrades** [comment]
The disconnection issue is recurring now. Is this because it's the demo version and there could be a surge in users (due to the corona virus) which is causing it to become unstable?

Would this stability issue be solved if I dove into setting up my own 'web page?' as described in the very scary looking 'How to' pages?

**Comment by haeferer** [comment]
Look for a possible solution  https://github.com/bigbluebutton/bigbluebutton/issues/9466

401 can mean , you have create a JOIN Link over API without using a JSession Cookie (like greenlight).

**Comment by matiasilva** [comment]
Hello. I'll close this due to inactivity but do feel free to follow up at https://groups.google.com/forum/#!forum/bigbluebutton-setup if you run into any further issues.
