### ISSUE TITLE
Error 1002 and Error 1020

### ISSUE THREAD

**Issue by yakarsu** [bigbluebutton/bigbluebutton#8784]
Hello

I can use moodle with bilgbluebutton  but when i can open sessıion but i can see 1002 and 1020 error we didnt use microphone and web cam how am i fix tihis errors

**Comment by ffdixon** [comment]
There is a firewall between you and the BigBlueButton server.  Did you setup your own BigBlueButton server or are you using the BigBlueButtonBN plugin with the default server (test-install).

If you have setup your own BigBlueButton server, see

   http://docs.bigbluebutton.org/2.2/configure-firewall.html

**Comment by KaaeWagner** [comment]
I have the same isue, but my server was running before. and I've never touch the firewall. It's my own server, but I have currently updatet to bbb server 2.2.2

**Comment by yakarsu** [comment]
thank you for answer but  No solution to the 1002 error?

**Comment by yakarsu** [comment]
> There is a firewall between you and the BigBlueButton server. Did you setup your own BigBlueButton server or are you using the BigBlueButtonBN plugin with the default server (test-install).
> 
> If you have setup your own BigBlueButton server, see
> 
> http://docs.bigbluebutton.org/2.2/configure-firewall.html

hello yes i installed own bbb server

**Comment by ffdixon** [comment]
For steps on troubleshooting (and the information you need to share for others to try and help), see

  http://docs.bigbluebutton.org/2.2/troubleshooting.html#help-installing-bigbluebutton

**Comment by yakarsu** [comment]
thank you fred for help i will try your message

**Comment by anvycn** [comment]
try `/etc/bigbluebutton/bbb-conf/apply-lib.sh` 
` 14 if LANG=c ifconfig | grep -q 'venet0:0'; then
 15   # IP detection for OpenVZ environment
 16   IP=$(ifconfig | grep -v '127.0.0.1' | grep -E "[0-9]*\.[0-9]*\.[0-9]*\.[0-9]*" | tail -1 | cut -d: -f2 | awk '{ print $1}')
 17 else
 18   IP=$(hostname -I | sed 's/ .*//g')
 19 fi
 20 
 21 IP='Your external IP' #add this line`

**Comment by matiasilva** [comment]
No follow up in a year. Closing for now but feel free to follow up at https://groups.google.com/forum/#!forum/bigbluebutton-setup.
