### ISSUE TITLE
Allow scheduling of recording processing

### ISSUE THREAD

**Issue by relecand** [bigbluebutton/bigbluebutton#8786]
Hi,

this is not a bug. I want the recordings to be processed at night and not during the day (when the traffic is high). Where can I change it? I thought I've read about it, but can't find it anymore.

All the best,

Christian

**Comment by dhaval-bhimani** [comment]
@relecand 
Any luck on your question?

Can anyone help me on it?

**Comment by cod3r0k** [comment]
Is there any solution for this scheduling? Because the processing is very massive and highly gets computational cost. (Maybe it missed for the next concurrent meeting -- when some previous recording is running, another session creation is having some CPU limit problems.
is there any update?

**Comment by matiasilva** [comment]
There's no update to this so far. For latest development updates, I encourage you to look at the commit log to the main develop branch. It's been suggested by some before, so I'll give this a better name.
