### ISSUE TITLE
error 2001 Media Server is offline

### ISSUE THREAD

**Issue by yakarsu** [bigbluebutton/bigbluebutton#8787]
Hello

i give error 2001 Media Server is offline what am i do?

**Comment by Vladius25** [comment]
Have the same problem.

**Comment by ritzalam** [comment]
Kurento might have crashed or hug.

sudo systemctl restart kurento-media-server bbb-webrtc-sfu

**Comment by prlanzarin** [comment]
If you're consistently getting this error after a restart or anything else, it's probably a configuration error. Please paste the output of `sudo bbb-conf --check` @yakarsu  and @Vladius25.

**Comment by Vladius25** [comment]
I just hadn't `127.0.0.1 localhost` in hosts file.

**Comment by prlanzarin** [comment]
@Vladius25 k, glad to hear it's solved.

**Comment by matiasilva** [comment]
Seems like a solution has been provided (OP hasn't followed up in 3 months, assuming all OK). Closing for now but feel free to follow up at https://groups.google.com/forum/#!forum/bigbluebutton-setup
