### ISSUE TITLE
Converge all the setup options (cross-repo issue)

### ISSUE THREAD

**Issue by someone-somenet-org** [bigbluebutton/bigbluebutton#8789]
You seriously need to converge all the different setup options.

[Here](https://github.com/bigbluebutton/bigbluebutton/tree/develop/labs/docker) is another - `not working` docker-compose setup.

[There](https://github.com/bigbluebutton/docker) is this - `not working `- Docker setup.

And your bbb-install.sh is just a pure clusterfuck - do you seriously expect anyone to run that OUTSIDE of a container?

### So how do you install this?
I already spent like 12 hours on trying to figure out, how to install this and I am getting frustrated by now ...

**Comment by capilkey** [comment]
You linked to the same thing twice. Also please take note of the first line of the README. The docker containers are not ready for production use and they are incomplete.

The recommended way to install is with the install script on a bare-metal server (AWS, Digital Ocean, or other large cloud provider is also fine). If there's something you're struggling with when using the bbb-install script post with logs and someone might be able to help.

**Comment by someone-somenet-org** [comment]
ninja-edited it :P

**Comment by capilkey** [comment]
Both of those docker setups were tests by different people. The core problem with docker and BigBlueButton is that docker still hasn't figured out how to handle forwarding large blocks of ports. Large blocks of ports are required for WebRTC to function and we need WebRTC for audio and video.

The only way I would recommend installing BBB is on a single Ubuntu 16.04 server. It's possible to reverse engineer it and install in different ways, but it will take a long time and likely be pretty broken.

**Comment by someone-somenet-org** [comment]
Interesting. Maybe take a look at jitsi-meet ... they seem to have managed to bring webrtc to life.

**Comment by matiasilva** [comment]
Linking a working installation with docker here: https://github.com/alangecker/bigbluebutton-docker and closing this issue. Please be polite, nobody intentionally designed this to anger you.
