### ISSUE TITLE
2.3 Recordings are being processed even though recording was never started

### ISSUE THREAD

**Issue by farhatahmad** [bigbluebutton/bigbluebutton#8790]
Not sure exactly which component is causing this. 

Greenlight has a hardcoded "record=true" passed on all create calls. In BigBlueButton 2.3, a recording is being processed for every meeting even though the recording button was never pressed. 

bigbluebutton.properties has "autoStartRecording=false" 

(This is not the case for BigBlueButton 2.2.2)

**Comment by capilkey** [comment]
What step is the recording procedure getting to? Everything is recorded whether the button in the client is pressed or not. Some of the processing happens no matter what and then it should be looking for whether there are any start/stop marks.

Do the recording publish or just process?

**Comment by farhatahmad** [comment]
The recordings publish, which means they get returned in a getRecordings call, so they end up displaying in the recordings table in Greenlight

**Comment by capilkey** [comment]
Gotcha. Just wanted to clarify.

**Comment by farhatahmad** [comment]
Was also able to replicate the bug through API Mate as well by selecting the record checkbox and then creating a meeting, joining, then ending a couple seconds later

**Comment by kepstin** [comment]
this is probably an issue in the new resque based recording processing system
the old one checked if the meeting had record events and skipped it if not
that code might be missing now
