### ISSUE TITLE
Screensharing/File upload doesn't work

### ISSUE THREAD

**Issue by tejaskarelia17** [bigbluebutton/bigbluebutton#8792]
Hi, 

I recently updated the bigbluebutton server from 2.2-beta to 2.2.2. I have the server installed behind a NAT firewall. 

After the update, I am unable to share my screen or upload a file when using the system. I am getting the following error: **Connection failed when sharing the screen (ICE error 1108)**.

**BBB version:** 2.2.2
**Browser:** Mozilla Firefox 74.0
**OS:** Mac OS Catalina

Following is the screenshot of the error.

<img width="1680" alt="ICE-error-1108" src="https://user-images.githubusercontent.com/11533007/76807292-1badec00-67a1-11ea-9c3f-035a168c0dad.png">

Where can I find detailed logs for me to help you in diagnosing the problem. 

Thanks.

**Comment by prlanzarin** [comment]
About screen sharing: since your server is behind NAT, did you confirm that a STUN server was set up for Kurento as described in https://docs.bigbluebutton.org/2.2/configure-firewall.html#updating-kurento ?

The file upload stuff is out of my reach, so I'll let others chime in.

**Comment by capilkey** [comment]
For presentation uploading, what error do you get in the client?

**Comment by tejaskarelia17** [comment]
> About screen sharing: since your server is behind NAT, did you confirm that a STUN server was set up for Kurento as described in https://docs.bigbluebutton.org/2.2/configure-firewall.html#updating-kurento ?
> 
> The file upload stuff is out of my reach, so I'll let others chime in.

Does the STUN server have to be publicly accessible or can it be in the same network as BBB? Can it be behind a NAT as well?

**Comment by tejaskarelia17** [comment]
> For presentation uploading, what error do you get in the client?

Hi Chad,
It's just a white screen that appears.

**Comment by prlanzarin** [comment]
@tejaskarelia17 

> Does the STUN server have to be publicly accessible or can it be in the same network as BBB? Can it be behind a NAT as well?

The STUN server has to be publicly accessible. You can use one of Google's open STUN servers for testing (ie 64.233.186.127:19302, stun.l.google.com, or any of the others that's listed in the docs link I sent before), or you can setup one yourself (see https://docs.bigbluebutton.org/2.2/setup-turn-server.html#Configure_TURN_ ) for more reliability.

**Comment by tejaskarelia17** [comment]
> > For presentation uploading, what error do you get in the client?
> 
> Hi Chad,
> It's just a white screen that appears.

Is there a size limitation for the presentation? It looks like larger presentations appear as a white screen and smaller ones work just perfectly.

**Comment by tejaskarelia17** [comment]
Hi @prlanzarin,

After testing out different scenarios, I found out that I am able to share my screen when I am in the same network as the bbb system. When I try to share my screen from outside the network it doesn't work. Any configuration I might be missing?

Thanks 🙂 👍

**Comment by prlanzarin** [comment]
@tejaskarelia17  This is typical connectivity issue scenario. Did you setup the STUN configuration in KMS I mentioned before? Also, for the best experience possible, be sure to set up STUN and TURN servers for the browsers as well. See in the docs:
 - For when the server is behind NAT (re-linking): https://docs.bigbluebutton.org/2.2/configure-firewall.html#updating-kurento
 - Setting up a TURN/STUN server for the HTML5 clients: https://docs.bigbluebutton.org/2.2/setup-turn-server.html

Try it out and let me know if you have any problems.

**Comment by tejaskarelia17** [comment]
Hi @prlanzarin,

I added the following STUN server address and port in WebRtcEndpoint.conf.ini file.
- stunServerAddress=173.194.71.127
- stunServerPort=19302

I also installed a TURN server on GCP and applied the firewall rules that were required for the TURN server to work. I tested that TURN server with trickle-ice and I got the following results:

<img width="1026" alt="turn" src="https://user-images.githubusercontent.com/11533007/77511735-f53a2180-6e2e-11ea-8bae-5f4f2467a186.png">
<img width="986" alt="turns" src="https://user-images.githubusercontent.com/11533007/77511742-f703e500-6e2e-11ea-9a14-5eb8a86f5862.png">

It looks like the GCP TURN server works as expected but I still couldn't get it to work. It's definitely a connectivity issue as I am able to screenshare/video when in the same network as bbb and not when using it from outside the network. I enabled client logs and error log and found the following errors:

[html5-client.log](https://github.com/bigbluebutton/bigbluebutton/files/4379559/html5-client.log)
[error.log](https://github.com/bigbluebutton/bigbluebutton/files/4379558/error.log)

Thanks a lot for helping me debug this issue. 🙂

**Comment by prlanzarin** [comment]
@tejaskarelia17 That STUN server you configured doesn't seem to work, testing from my machine with the stun-client package:
```
$ stun 173.194.71.127:19302
STUN client version 0.97
Primary: Blocked or could not reach STUN server	
```

It might be an old STUN server. If it was a Google one, be aware that they DNS round robin (or load balance somehow) them and there's no guaranteed availability via IP.

You can set your coturn server in Kurento's stun config instead of this one. coturn acts as both STUN and TURN (as you  might've seen in ice-trickle test with the srflx/relay candidates). Try it out and let me know if it works. You can use the command I pasted above to test if the STUN server is working from your BBB server.

**Comment by prlanzarin** [comment]
@tejaskarelia17 btw the STUN server needs to be in an external network, not the same internal network as the BBB server. Otherwise it'll only return srflx candidates with internal network IPs.

**Comment by matiasilva** [comment]
Closed due to lack of follow up from OP. Good reference issue for network-related debug.
