### ISSUE TITLE
Add Google Analytics or any Javascript file to HTML5 Client

### ISSUE THREAD

**Issue by baoc75** [bigbluebutton/bigbluebutton#8794]
Hi everyone,
While Greenlight supports Google Analytics, the HTML5 client seems can't customize anything. I have read all documentation but couldn't find any way to add my tracking code or a javascript spinnet to it. 
Am I missing something?
Thanks for reading!

It is similar to this issue #5836

**Comment by acner** [comment]
Hi, it is similar to this solution #5836 
sudo vim /etc/bigbluebutton/nginx/bbb-html5.nginx

```
location /html5client {

  proxy_pass http://127.0.0.1:3000;
  proxy_http_version 1.1;
  proxy_set_header Upgrade $http_upgrade;
  proxy_set_header Connection "Upgrade";

  proxy_set_header Accept-Encoding "";
  sub_filter_types *;
  sub_filter_once off;

# add the script before the </body> closes
sub_filter '</body>' '<script async src="https://www.googletagmanager.com/gtag/js?id=YOURANALYTICSCODE"></script>
<script>window.dataLayer = window.dataLayer || [];function gtag(){dataLayer.push(arguments);}gtag("js", new Date());gtag("config", "YOURANALYTICSCODE");</script></body>';


}

location /_timesync {
  proxy_pass http://127.0.0.1:3000;
}`

```

restart nginx
sudo /etc/init.d/nginx restart

start a new conference

best regards,
Acner Pinazo

**Comment by baoc75** [comment]
Thanks for your approach! I really appreciate that and it just works!

**Comment by prakas24** [comment]
I tried this but not able to restart nginx.

**Comment by matiasilva** [comment]
Please do not revive this issue. If you need support, please read https://docs.bigbluebutton.org/2.2/getting-help.html.
