### ISSUE TITLE
Typo in BBB Docs

### ISSUE THREAD

**Issue by aakatev** [bigbluebutton/bigbluebutton#8797]
I know it is minor thing, but it is on landing page, and is really noticeable.

1. Go to [BBB docs](https://docs.bigbluebutton.org/)
2. 2nd paragraph 2 sentence.
3. Reads `With the source code, installation steps, and community support, you can easily your own BigBlueButton server`. Missing a word deploy?

![typo](https://user-images.githubusercontent.com/38078131/76880605-23b76b80-6835-11ea-8c4f-4c763e5a5151.png)

**Comment by ffdixon** [comment]
Fixed -- thanks!
