### ISSUE TITLE
Videoconference performance 

### ISSUE THREAD

**Issue by erotavlas-turbo** [bigbluebutton/bigbluebutton#8798]
Hi,
I’m currently testing different platforms for videoconferencing. In particular, I’m comparing bigBlueButton, mega.nz, hangouts, teams and jitsi.
My setting is one sender/speaker that shares its desktop so just one video at low definition and 20-40 users audio only (muted if they do not talk).
In particular, bandwidth requirements are: [hangouts](https://support.google.com/hangouts/answer/2944865) has minimum of 300 kbit/s, [teams](https://docs.microsoft.com/en-US/microsoftteams/prepare-network) has a minimum of 500 kbit/s while jitsi is close to teams.
Hangout is using [VP9](https://developers.google.com/web/updates/2016/01/vp9-webrtc), teams [h.264](https://docs.microsoft.com/en-us/skypeforbusiness/plan-your-deployment/network-requirements/network-requirements) codec while jitsi VP8. VP9 is comparable to h.265 and one step ahead to both VP8 and h.264.
What are the codecs used by bigBlueButton? Does bigBlueButton allow to adjust video quality (LD, SD, HD)? What is the maximum number of conference users (audio and video)?
I would like to use bigBlueButton since it integrates perfectly with moodle.
Thank you

**Comment by erotavlas-turbo** [comment]
I found some answers to my questions.
[BigBlueButton](http://docs.bigbluebutton.org/support/faq.html#how-many-simultaneous-users-can-bigbluebutton-support) advises to setup up to 100 users per room and, with minimum server specifications, up to 150 total users divided into different rooms 3*50, 6*25.
A single student/user needs at least 500 kbit/s uplink and 1 Mbit/s downlink while the presenter/teacher needs as much bandwidth as possible [link](http://docs.bigbluebutton.org/support/faq.html#what-are-the-minimum-bandwidth-requirements-for-a-user).
BigBlueButton automatically adjusts the video quality: a presenter/teacher video stream requires between a minimum of 0.2 Mbits/sec (low content change) and a maximum of 1.0 Mbits/sec (high content change).
I could not find any information about the codecs into the documentation. However, by analysing the source code [VP8](https://github.com/bigbluebutton/bigbluebutton/search?q=VP8&unscoped_q=VP8) and [VP9](https://github.com/bigbluebutton/bigbluebutton/search?q=vp9&unscoped_q=vp9) it seems that video recording uses VP9 codec while webcam/screen sharing can use VP8 and the new AV1.
Can you confirm about the codecs?

**Comment by jranke** [comment]
Hi, I was also wondering about the codecs, but for a different reason, see #8803

**Comment by erotavlas-turbo** [comment]
I confirm that the codec used for webcam and video sharing is [VP8](https://docs.bigbluebutton.org/support/faq.html).
If you have your own instance of BBB you can adjust video quality as described [here](https://docs.bigbluebutton.org/2.2/customize.html).
