### ISSUE TITLE
The number for joining BigBlueButton via call is not in service.

### ISSUE THREAD

**Issue by sam5789** [bigbluebutton/bigbluebutton#8799]
The number to call for USA 18632080022 given upon joining a conference for audio is not in service.

**Comment by ritzalam** [comment]
Are you by any chance on ATT? We've heard that it doesn't work with them. Just tried on my phone (Rogers Canada) and it is working.

**Comment by matiasilva** [comment]
Closing due to lack of follow up by OP in 3 months. Feel free to follow up at https://groups.google.com/forum/#!forum/bigbluebutton-users.
