### ISSUE TITLE
Transparently disable H264 to avoid licence issues

### ISSUE THREAD

**Issue by jranke** [bigbluebutton/bigbluebutton#8803]
If I read the [openh264 binary licence](http://www.openh264.org/BINARY_LICENSE.txt) correctly, cisco only covers private uses or uses which are not being paid for.

I would like to use bigbluebutton with the greenlight frontend for teaching seminars that I get paid for. In order to avoid discussing with MPEG LA about licencing costs, I have disabled h264 in the profiles.xml configuration file (found in /var/www/bigbluebutton/client/conf/profiles.xml).

I have then restarted the server - videoconferencing appears to work as before. How can I verify that I successfully disabled H264? Do I need to take further steps?

**Comment by prlanzarin** [comment]
I suppose you're using the HTML5 client. If so, H.264 usage is disabled by default in the normal BBB installation.

That file you referred to applies to the Flash client. The codec configuration that applies to the HTML5 client can be found in /usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml, fields `codec_video_main` and `codec_video_content`.

You can check those fields with `sudo bbb-conf --check`. It should display as follows:
```
[...]
codec_video_main: VP8
codec_video_content: VP8
[...]
```

This will force VP8 and refuse H.264 negotiation.

**Comment by jranke** [comment]
Ah, great, thanks for the quick answer. Yes, I am using the HTML5 client. So it seems to me it would be beneficial to remove the flash client and H.264 to avoid others to spend the time I did in order to try to understand the OpenH264 licence when it is really not relevant for the standard installation. I got prompted to do so by the OpenH264 licence terms being displayed during installation of the openh264 package.

**Comment by prlanzarin** [comment]
The OpenH264 installation is there because H.264 is optional even for the HTML5 client (you can set it up in the config I mentioned). Can't install it on demand right now, though, even if its disabled by default, so it goes upfront. We could make this clearer in the docs, though.

**Comment by tarunb999** [comment]
In the above file can I also use ANY option so as not to enforce any particular type of codec?

**Comment by prlanzarin** [comment]
@tarunb999 Yes. Might cause transcoding though.

**Comment by sharypovandrey** [comment]
@prlanzarin I changed VP8 to H264 in `/usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml`
```
conference-media-specs:
  codec_video_main: H264
  codec_video_main_priority: H264
  codec_video_content: H264
  codec_video_content_priority: H264
```
restarted bbb and got `server could not find an appropriate codec`
tested on Android
do I need to add the h.264 codec somewhere on the server?

**Comment by basisbit** [comment]
@sharypovandrey  please ask your question at the support forum / miling list instead of hijacking a different support issue. Thank you! https://groups.google.com/forum/#!forum/bigbluebutton-setup
