### ISSUE TITLE
No sound on recordings

### ISSUE THREAD

**Issue by ittrainingdev** [bigbluebutton/bigbluebutton#8805]
Recordings worked fine. Now the sound does not get recorded

The output of bbb-record --watch says that the bbb-rap-archive-worker service is down.

Is this the cause of the problem ?

If so how can I fix it ?

root@ittraining:/var/freeswitch/meetings# systemctl status bbb-rap-archive-worker
● bbb-rap-archive-worker.service - BigBlueButton recording and playback archive worker
   Loaded: loaded (/usr/lib/systemd/system/bbb-rap-archive-worker.service; static; vendor preset: enabled)
   Active: inactive (dead) since Wed 2020-03-18 12:23:06 UTC; 1h 24min ago
Condition: start condition failed at Wed 2020-03-18 13:47:26 UTC; 13s ago
           ConditionPathExistsGlob=/var/bigbluebutton/recording/status/recorded/*.done was not met
  Process: 92182 ExecStart=/usr/local/bigbluebutton/core/scripts/rap-archive-worker.rb (code=exited, status=0/SUCCESS)
 Main PID: 92182 (code=exited, status=0/SUCCESS)

Mar 18 12:23:05 ittraining.network systemd[1]: Started BigBlueButton recording and playback archive worker.

root@ittraining:/var/freeswitch/meetings# ls -l
total 8
-rw-r--r-- 1 root       root       99 Mar 18 13:35 1
-rw-r--r-- 1 freeswitch freeswitch 48 Sep 10  2019 readme.txt

Thanks

**Comment by mouhsinelonly** [comment]
I am facing the same issue, any idea what is causing this?

`
ii  bbb-apps                              1:2.2.0-36                                      amd64        BigBlueButton applications for Red5
ii  bbb-apps-akka                         2.2.0-69                                        all          BigBlueButton Apps (Akka)
ii  bbb-apps-screenshare                  1:2.2.0-36                                      amd64        BigBlueButton screenshare module for Red5
ii  bbb-apps-sip                          1:2.2.0-11                                      amd64        BigBlueButton SIP module for Red5
ii  bbb-apps-video                        1:2.2.0-33                                      amd64        BigBlueButton video module for Red5
ii  bbb-apps-video-broadcast              1:2.2.0-8                                       amd64        BigBlueButton video broadcast module for Red5
ii  bbb-client                            1:2.2.0-33                                      amd64        BigBlueButton Flash client
ii  bbb-config                            1:2.2.0-144                                     amd64        BigBlueButton configuration utilities
ii  bbb-etherpad                          1:2.2.0-48                                      amd64        The EtherPad Lite components for BigBlueButton
ii  bbb-freeswitch-core                   2:2.2.0-30                                      amd64        BigBlueButton build of FreeSWITCH
ii  bbb-freeswitch-sounds                 1:1.6.7-9                                       amd64        FreeSWITCH Sounds
ii  bbb-fsesl-akka                        2.2.0-53                                        all          BigBlueButton FS-ESL (Akka)
ii  bbb-html5                             1:2.2.0-829                                     amd64        The HTML5 components for BigBlueButton
ii  bbb-mkclean                           1:0.8.7-4                                       amd64        Clean and optimize Matroska and WebM files
ii  bbb-playback-presentation             1:2.2.0-28                                      amd64        BigBluebutton playback of presentation
ii  bbb-record-core                       1:2.2.0-54                                      amd64        BigBlueButton record and playback
ii  bbb-red5                              1:1.0.10-16                                     amd64        The Red5 server for BigBlueButton
ii  bbb-swftools                          1:0.9.2-2                                       amd64        The swftools files for BigBlueButton
ii  bbb-transcode-akka                    2.2.0-8                                         all          BigBlueButton Transcoder
ii  bbb-web                               1:2.2.0-107                                     amd64        BigBlueButton API
ii  bbb-webrtc-sfu                        1:2.2.0-82                                      amd64        BigBlueButton WebRTC SFU
ii  bigbluebutton                         1:2.2.0-5                                       amd64        Open source web conferencing platform (bbb)
ii  ffmpeg                                7:4.2.2-1bbb1~ubuntu16.04                       amd64        Tools for transcoding, streaming and playing of multimedia files
ii  libavcodec58:amd64                    7:4.2.2-1bbb1~ubuntu16.04                       amd64        FFmpeg library with de/encoders for audio/video codecs - runtime files
ii  libavdevice58:amd64                   7:4.2.2-1bbb1~ubuntu16.04                       amd64        FFmpeg library for handling input and output devices - runtime files
ii  libavfilter7:amd64                    7:4.2.2-1bbb1~ubuntu16.04                       amd64        FFmpeg library containing media filters - runtime files
ii  libavformat58:amd64                   7:4.2.2-1bbb1~ubuntu16.04                       amd64        FFmpeg library with (de)muxers for multimedia containers - runtime files
ii  libavresample4:amd64                  7:4.2.2-1bbb1~ubuntu16.04                       amd64        FFmpeg compatibility library for resampling - runtime files
ii  libavutil56:amd64                     7:4.2.2-1bbb1~ubuntu16.04                       amd64        FFmpeg library with functions for simplifying programming - runtime files
ii  libpostproc55:amd64                   7:4.2.2-1bbb1~ubuntu16.04                       amd64        FFmpeg library for post processing - runtime files
ii  libswresample3:amd64                  7:4.2.2-1bbb1~ubuntu16.04                       amd64        FFmpeg library for audio resampling, rematrixing etc. - runtime files
ii  libswscale5:amd64                     7:4.2.2-1bbb1~ubuntu16.04                       amd64        FFmpeg library for image scaling and various conversions - runtime files
`

**Comment by ffdixon** [comment]
Make sure your running BigBlueButton 2.2.2 (use `bbb-conf --check`).

**Comment by ittrainingdev** [comment]
I am running 2.2.0-rc-6 with Greenlight

I have done a lot of tweeks. It is my understanding that going to 2.2.2 will break my changes.

Do I really need to upgrade just to fix the sound issue ? It did work before.

Is there not a simpler way ?



root@ittraining:~# bbb-conf --check

BigBlueButton Server 2.2.0-rc-6 (1656)
                    Kernel version: 4.4.0-174-generic
                      Distribution: Ubuntu 16.04.6 LTS (64-bit)
                            Memory: 8157 MB
                         CPU cores: 4

/usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties (bbb-web)
       bigbluebutton.web.serverURL: https://ittraining.institute
                defaultGuestPolicy: ALWAYS_ACCEPT
                 svgImagesRequired: true

/etc/nginx/sites-available/bigbluebutton (nginx)
                       server name: ittraining.institute
                              port: 80, [::]:80
                              port: 443 ssl
                    bbb-client dir: /var/www/bigbluebutton

/var/www/bigbluebutton/client/conf/config.xml (bbb-client)
                Port test (tunnel): rtmp://ittraining.institute
                              red5: ittraining.institute
              useWebrtcIfAvailable: true

/opt/freeswitch/etc/freeswitch/vars.xml (FreeSWITCH)
                       local_ip_v4: 109.228.56.52
                   external_rtp_ip: stun:stun.freeswitch.org
                   external_sip_ip: stun:stun.freeswitch.org

/opt/freeswitch/etc/freeswitch/sip_profiles/external.xml (FreeSWITCH)
                        ext-rtp-ip: $${local_ip_v4}
                        ext-sip-ip: $${local_ip_v4}
                        ws-binding: :5066
                       wss-binding: 109.228.56.52:7443

/usr/local/bigbluebutton/core/scripts/bigbluebutton.yml (record and playback)
                     playback_host: ittraining.institute
                 playback_protocol: https
                            ffmpeg: 4.2.2-0york0~16.04

/etc/bigbluebutton/nginx/sip.nginx (sip.nginx)
                        proxy_pass: 109.228.56.52

/usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml (Kurento SFU)
                        kurento.ip: 109.228.56.52
                       kurento.url: ws://127.0.0.1:8888/kurento
                    localIpAddress: 109.228.56.52
               recordScreenSharing: true
                     recordWebcams: true
                  codec_video_main: VP8
               codec_video_content: VP8

/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml (HTML5 client)
                             build: 837
                        kurentoUrl: wss://ittraining.institute/bbb-webrtc-sfu
                  enableListenOnly: true

**Comment by capilkey** [comment]
What does `ls -al /var/freeswitch/meetings` output? The meetings directory should be owned by `freeswitch:freeswitch`.

**Comment by ittrainingdev** [comment]
root@ittraining:~# ls -al /var/freeswitch/meetings
total 16
drwxr-xr-x 2 freeswitch freeswitch 4096 Mar 18 13:35 .
drwxr-xr-x 3 freeswitch daemon     4096 Sep 29 11:48 ..
-rw-r--r-- 1 root       root         99 Mar 18 13:35 1
-rw-r--r-- 1 freeswitch freeswitch   48 Sep 10  2019 readme.txt

**Comment by iamgurwinderdubb** [comment]
I have the same issue, when I click on the microphone, call timed out error display on the screen.

**Comment by rasmuoy** [comment]
I have the same issue, everything works fine in a meeting - but recording does not save audio. It used to work before.

I am running BBB 2.2.2.

I get "WARN -- : No audio found for <meeting-id>" in my logs for the meetings.

No folders under /var/freeswitch/meetings, but /var/freeswitch/meetings itself is owned by freeswitch:freeswitch.

**Comment by ittrainingdev** [comment]
Glad to hear it is not just me - but who has the solution then ?
We are in Coronavirus lock down here. This is getting critical !!!!

**Comment by haviduck** [comment]
i doubt its the sanity workers etc, ive got rasmuoys rig and mine running side-by-side here.  trying to compare differences. so far all ive seen is a freeswitch issue with misconfed dialin (which isnt even flagged as enabled). will post findings.

**Comment by ittrainingdev** [comment]
Not quite sure I follow you there. Nothing to do with sanity workers. What I said was is that we are in a lock down. We provide paid services to commercial companies but in view of what is happening we are also supplying FREE services to any medical institution that requires online meetings with infected patients. My point is that not having sound on recordings does not help. I look forward to your feedback. Not sure where you are based but I am in Europe and here it is becoming a real mess.

**Comment by mouhsinelonly** [comment]
i have upgraded to latest version yesterday and I am getting audio now in recordings

**Comment by ittrainingdev** [comment]
OK thanks for the input. I will do it over the week-end and let you know

**Comment by matiasilva** [comment]
No follow up in three months. Closing for now but feel free to follow up at https://groups.google.com/forum/#!forum/bigbluebutton-users.
