### ISSUE TITLE
building docker bbb-webrtc-sfu image fails because no source

### ISSUE THREAD

**Issue by dkrenn** [bigbluebutton/bigbluebutton#8806]
**Describe the bug**
`make release` calls
```
cd /home/bbb/bigbluebutton/.git/../labs/bbb-webrtc-sfu && docker build -t bbb-webrtc-sfu:latest  .
```
but there is no such directory. 

**Installation type**
Docker installation

**Console output**
```
cd /home/bbb/bigbluebutton/.git/../labs/bbb-webrtc-sfu && docker build -t bbb-webrtc-sfu:latest  .
/bin/bash: line 0: cd: /home/bbb/bigbluebutton/.git/../labs/bbb-webrtc-sfu: No such file or directory
```

**Additional context**
On `v2.2.2` and current `develop`.

**Comment by capilkey** [comment]
The bbb-webrtc-sfu code was split into its own repository and it can be found here, https://github.com/bigbluebutton/bbb-webrtc-sfu/.

The SFU 2.3 branch is used with BBB 2.2 and the SFU master branch is used with the BBB develop branch.
