### ISSUE TITLE
Forcing client devices to not sleep would be a welcome feature.

### ISSUE THREAD

**Issue by Thanzex** [bigbluebutton/bigbluebutton#8807]
My university is using Big Blue Button for its on-line lesson streaming. Whether I watch them on my laptop, desktop or smartphone after a few minutes the screen of my devices goes to sleep. This is very inconvenient since all of our lessons are not interactive and do not require any input from students.

It would be very easy to have the browser force the device to stay awake. There are multiple js tools already for this purpose.

It should be noted that our lessons do not involve any video stream, neither the professor nor the students have their webcam enabled, our lessons involve presentations and the virtual pointer.

**Comment by capilkey** [comment]
It would be nice to have, but it seems like most of the potential solutions are really just hacks to try and trick the browsers. There's a draft for a WakeLock API, but there doesn't seem to be much browser support for it.

**Comment by matiasilva** [comment]
Is there still interest in this? It seems like as the above solutions are indeed hacks, it might not be worth pursuing.

**Comment by antobinary** [comment]
Merging with https://github.com/bigbluebutton/bigbluebutton/issues/9572
