### ISSUE TITLE
getRecordings verry slow

### ISSUE THREAD

**Issue by vetsolution** [bigbluebutton/bigbluebutton#8810]
**Describe the bug**
I migrate my bigbluebutton installation from a old server to a new one, and transfert the recordings.
But now when I use the api to list all recording the request last more that 30 seconds, on my old server it was about 5 seconds. When I query for a specific records it's quick.
Do you have an idea of what I can do to debug this situation? 

**To Reproduce**
time curl http://yourserver.com/bigbluebutton/api/getRecordings?[parameters]&checksum=[checksum]

**Expected behavior**
List all record in a couple of seconds.

**Actual behavior**
Hang up for 30 seconds before receiving the result

I use  BigBlueButton 2.2 on a virtual machine and I check the entropy note, I install the tool, entropy is good but it still not working

Many thanks

**Comment by basisbit** [comment]
If this issue is still not fixed in the mean time by updating to the newest BigBlueButton version, please use the support forum / mailing list to get further help. Thank you.
https://groups.google.com/forum/#!forum/bigbluebutton-setup
