### ISSUE TITLE
Meeting start_time not unix time

### ISSUE THREAD

**Issue by lonesomewalker** [bigbluebutton/bigbluebutton#8811]
**Describe the bug**
Currently the timestamp is somewhat like this:
`  <start_time>1584544439586</start_time>
  <end_time>1584544617556</end_time>`

**To Reproduce**
Record a session, open metadata.xml

**Expected behavior**
timestamp should be unix conform, these timestamps have 3 digits more at the end

**Actual behavior**
timestamp is somewhat mixed, should be conform for further processing of data/scripting.

**Desktop (please complete the following information):**
 - Version: bbb latest

**Comment by GremL1N** [comment]
it's just with milliseconds. 
`1584544439586/1000` to get in seconds for any data/scripting

**Comment by lonesomewalker** [comment]
Uh, yeah, my mistake!
We have live data, so miliseconds are relevant!
Closing, thanks.
