### ISSUE TITLE
The Spanish translation contains many mistakes.

### ISSUE THREAD

**Issue by mpellicer** [bigbluebutton/bigbluebutton#8813]
The spanish translation contains many typos and grammar mistakes, contributed a review here:

https://github.com/bigbluebutton/bigbluebutton/pull/8812

Thanks to all for the hard work.

Hi @ffdixon and @jfederico, happy to talk to you again!

**Comment by basisbit** [comment]
closing this issue, see answer of the pull request. Please help improving the translations by joining the transifex translation project and suggesting improved translations there. Thank you!
