### ISSUE TITLE
I constantly get error 1006 when I try to connect to Bigblubutton. 

### ISSUE THREAD

**Issue by cyasar** [bigbluebutton/bigbluebutton#8816]
**Describe the bug**
I constantly get error 1006 when I try to connect to Bigblubutton. Occasionally it opens up as soon as possible. When I constantly try to establish a connection with microphone, I get 1006 error. I need your help for the solution.
Thank you.
**Describe the bug**
BigBlueButton Server 2.2.2 (1797)
                    Kernel version: 4.15.0-91-generic
                      Distribution: Ubuntu 16.04.6 LTS (64-bit)
                            Memory: 32799 MB
                         CPU cores: 8

/usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties (bbb-web)
       bigbluebutton.web.serverURL: https://sanalkonferans.gen.tr
                defaultGuestPolicy: ALWAYS_ACCEPT
                 svgImagesRequired: true

/etc/nginx/sites-available/bigbluebutton (nginx)
                       server name: sanalkonferans.gen.tr
                              port: 80, [::]:80
                              port: 443 ssl
                    bbb-client dir: /var/www/bigbluebutton

/var/www/bigbluebutton/client/conf/config.xml (bbb-client)
                Port test (tunnel): rtmp://sanalkonferans.gen.tr
                              red5: sanalkonferans.gen.tr
              useWebrtcIfAvailable: true

/opt/freeswitch/etc/freeswitch/vars.xml (FreeSWITCH)
                       local_ip_v4: 85.10.192.189
                   external_rtp_ip: stun:stun.freeswitch.org
                   external_sip_ip: stun:stun.freeswitch.org

/opt/freeswitch/etc/freeswitch/sip_profiles/external.xml (FreeSWITCH)
                        ext-rtp-ip: $${local_ip_v4}
                        ext-sip-ip: $${local_ip_v4}
                        ws-binding: :5066
                       wss-binding: 85.10.192.189:7443

/usr/local/bigbluebutton/core/scripts/bigbluebutton.yml (record and playback)
                     playback_host: sanalkonferans.gen.tr
                 playback_protocol: https
                            ffmpeg: 4.2.2-1bbb1~ubuntu16.04

/etc/bigbluebutton/nginx/sip.nginx (sip.nginx)
                        proxy_pass: 85.10.192.189

/usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml (Kurento SFU)
                        kurento.ip: 85.10.192.189
                       kurento.url: ws://127.0.0.1:8888/kurento
                    localIpAddress: 85.10.192.189
               recordScreenSharing: true
                     recordWebcams: true
                  codec_video_main: VP8
               codec_video_content: VP8

/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml (HTML5 client)
                             build: 862
                        kurentoUrl: wss://sanalkonferans.gen.tr/bbb-webrtc-sfu
                  enableListenOnly: true

# Potential problems described below
# Warning: API URL IPs do not match host:
#
#                                IP from ifconfig: 85.10.192.189
#  /var/lib/tomcat7/demo/bbb_api_conf.jsp: sanalkonferans.gen.tr

# Warning: The API demos are installed and accessible from:
#
#    https://sanalkonferans.gen.tr
#
# and
#
#    https://sanalkonferans.gen.tr/demo/demo1.jsp
#
# These API demos allow anyone to access your server without authentication
# to create/manage meetings and recordings. They are for testing purposes only.
# If you are running a production system, remove them by running:
#
#    apt-get purge bbb-demo

**Comment by ffdixon** [comment]
The error might be caused by a firewall between your computer and the server.  I just did a quick test with your server and I was able to join with microphone without error.

Can you try connecting to

  https://test.bigbluebutton.org/

and let us know if you get the same 1006 error with this server.

**Comment by cyasar** [comment]
The problem was caused by the microphone of the browser. I solved the problem. I allowed the microfon through the browser. No problem.

**Comment by cyasar** [comment]
When i try to watch the bbb recordings, i get "Script node data failure". how do i solve this issue? 


![izlemehatasielazig](https://user-images.githubusercontent.com/1035193/77468915-5823bc80-6e1f-11ea-8a4f-3ae7c1574cc3.PNG)


![bbb_record_elezig](https://user-images.githubusercontent.com/1035193/77468787-2579c400-6e1f-11ea-8b4f-ac631cf1ca4e.PNG)

**Comment by basisbit** [comment]
closed this issue because the original support question was solved. For further questions, please use the support forum / mailing list at https://groups.google.com/forum/#!forum/bigbluebutton-setup
