### ISSUE TITLE
An error occured: it has been logged. Please try reloading the page.

### ISSUE THREAD

**Issue by daminebenq** [bigbluebutton/bigbluebutton#8818]
### Cannot destructure property `width` of 'undefined' or 'null'
for unknown reasons, more than 50% of running automated tests fail at displaying the presentation

![image](https://user-images.githubusercontent.com/5144311/77099563-e8629b80-69f2-11ea-91d2-706fb132b00b.png)

**Comment by dolevu** [comment]
I got the same problem

`ii  bbb-apps                               1:2.2.0-50                                      amd64        BigBlueButton applications for Red5
ii  bbb-apps-akka                          2.2.0-96                                        all          BigBlueButton Apps (Akka)
ii  bbb-apps-screenshare                   1:2.2.0-50                                      amd64        BigBlueButton screenshare module for Red5
ii  bbb-apps-sip                           1:2.2.0-11                                      amd64        BigBlueButton SIP module for Red5
ii  bbb-apps-video                         1:2.2.0-48                                      amd64        BigBlueButton video module for Red5
ii  bbb-apps-video-broadcast               1:2.2.0-8                                       amd64        BigBlueButton video broadcast module for Red5
ii  bbb-client                             1:2.2.0-40                                      amd64        BigBlueButton Flash client
ii  bbb-config                             1:2.2.0-220                                     amd64        BigBlueButton configuration utilities
ii  bbb-etherpad                           1:2.2.0-63                                      amd64        The EtherPad Lite components for BigBlueButton
ii  bbb-freeswitch-core                    2:2.2.0-113                                     amd64        BigBlueButton build of FreeSWITCH
ii  bbb-freeswitch-sounds                  1:1.6.7-6                                       amd64        FreeSWITCH Sounds
ii  bbb-fsesl-akka                         2.2.0-72                                        all          BigBlueButton FS-ESL (Akka)
ii  bbb-html5                              1:2.2.0-1081                                    amd64        The HTML5 components for BigBlueButton
ii  bbb-mkclean                            1:0.8.7-3                                       amd64        Clean and optimize Matroska and WebM files
ii  bbb-playback-presentation              1:2.2.0-33                                      amd64        BigBluebutton playback of presentation
ii  bbb-record-core                        1:2.2.0-71                                      amd64        BigBlueButton record and playback
ii  bbb-red5                               1:1.0.10-16                                     amd64        The Red5 server for BigBlueButton
ii  bbb-transcode-akka                     2.2.0-8                                         all          BigBlueButton Transcoder
ii  bbb-web                                1:2.2.0-148                                     amd64        BigBlueButton API
ii  bbb-webrtc-sfu                         1:2.2.0-107                                     amd64        BigBlueButton WebRTC SFU
ii  bigbluebutton                          1:2.2.0-5                                       amd64        Open source web conferencing platform (bbb)
ii  ffmpeg                                 7:4.2.4-1ubuntu0.1bbb1~16.04.1                  amd64        Tools for transcoding, streaming and playing of multimedia files
ii  libavcodec58:amd64                     7:4.2.4-1ubuntu0.1bbb1~16.04.1                  amd64        FFmpeg library with de/encoders for audio/video codecs - runtime files
ii  libavdevice58:amd64                    7:4.2.4-1ubuntu0.1bbb1~16.04.1                  amd64        FFmpeg library for handling input and output devices - runtime files
ii  libavfilter7:amd64                     7:4.2.4-1ubuntu0.1bbb1~16.04.1                  amd64        FFmpeg library containing media filters - runtime files
ii  libavformat58:amd64                    7:4.2.4-1ubuntu0.1bbb1~16.04.1                  amd64        FFmpeg library with (de)muxers for multimedia containers - runtime files
ii  libavresample4:amd64                   7:4.2.4-1ubuntu0.1bbb1~16.04.1                  amd64        FFmpeg compatibility library for resampling - runtime files
ii  libavutil56:amd64                      7:4.2.4-1ubuntu0.1bbb1~16.04.1                  amd64        FFmpeg library with functions for simplifying programming - runtime files
ii  libopusenc0                            0.2.1-1bbb1                                     amd64        High-level API for encoding Ogg Opus audio streams
ii  libpostproc55:amd64                    7:4.2.4-1ubuntu0.1bbb1~16.04.1                  amd64        FFmpeg library for post processing - runtime files
ii  libswresample3:amd64                   7:4.2.4-1ubuntu0.1bbb1~16.04.1                  amd64        FFmpeg library for audio resampling, rematrixing etc. - runtime files
ii  libswscale5:amd64                      7:4.2.4-1ubuntu0.1bbb1~16.04.1                  amd64        FFmpeg library for image scaling and various conversions - runtime files
`

**Comment by rankitt1123** [comment]
Hi can you please let me know how were you able to resolve the issue

**Comment by vNa3006** [comment]
> Hi can you please let me know how were you able to resolve the issue

Please use the latest BBB version.
