### ISSUE TITLE
Pop up a notification when admin shut down the meeting if the meeting is recording.

### ISSUE THREAD

**Issue by sesame437** [bigbluebutton/bigbluebutton#8820]
**Is your feature request related to a problem? Please describe.**
Pop up a notification when admin shut down the meeting if the meeting is recording.

**Describe the solution you'd like**
Sometimes, the admin might forget to stop the recording and the BigBlueButton could pop up a notification for admin, such as, "the BigBluebutton is generate the record, please wait about 30 mins, balabala.' 

**Describe alternatives you've considered**
the notification word could be customized like the welcome message.

**Additional context**

**Comment by ffdixon** [comment]
Actually, this is OK.  Ending the meeting will properly end the recording as well.

In other words, the moderator does not have to stop recording before ending the meeting.  It happens automatically when the meeting finished.

**Comment by sesame437** [comment]
Sometimes, the new moderator might want to see the record immediately after the meeting end, the admin of BigBlueButton could give the moderator a notification when they end meeting, the record need time to generate to control the user's exception.
