### ISSUE TITLE
Download the record from the playback

### ISSUE THREAD

**Issue by sesame437** [bigbluebutton/bigbluebutton#8821]
**Is your feature request related to a problem? Please describe.**
Currently, the meeting record saved in the BigBlueButton server, only the front-end system(LMS/Greenlight) could read it directly. 
Sometimes, end users want to download their own record in playback and share the record to outside. 
The admin also unable to know how to  map the record ID & meeting ID and download the end users need record files.

Currently, download the specified meeting record looks unachievable.

**Describe the solution you'd like**
So, please create a function to make the end users could download the record in playback directly.

**Describe alternatives you've considered**
There is a system or DB table, the admin could know which meeting ID map the record ID at backend. At least, the admin could help end users to export the record which they need.

**Comment by lonesomewalker** [comment]
This can all be done by using Greenlight OR the API.

**Comment by sesame437** [comment]
> This can all be done by using Greenlight OR the API.

Are you sure? I can't find download option in Greenlight. What is version are you using?

**Comment by ppisa** [comment]
The first, thanks much for BBB, it is great help and tool for us when we have forced to switch to distance education at whole CTU. Our colleague integrated BBB into our system homeworks submission system, there is some discussion of alternatives etc https://cw.fel.cvut.cz/wiki/help/common/distant_teaching .

BBB works great and recording viewer is nice too (the possibility to click to urls in chat, etc. is great). But it we want to bublish some recordings of meetings to YouTube as well. Ideally with possibility to cut out some pauses and add some notes for offline view etc.

I am looking for some option to convert BBB recording to some screenplay, for example import to kdenlive as the set of streams, PNGs and cuts between them. But even less comfortable way to get recordings, remix them and create video is of my interest.

**Comment by ostasevych** [comment]
I tried to use videodownloader extensions of my browser. It works, however, partially: sadly, the only video may be downloaded, while shared screen, whiteboard, chat and shared notes cannot be seen in the file. 
Please, add the feature to download all the recorded content, incl. audio, video, chat, whiteboard and shared notes in the form either 1 file or several separate files.

**Comment by hex-m** [comment]
Is this different from #1969?

**Comment by matiasilva** [comment]
Nope, merging with #1969.
