### ISSUE TITLE
Disable help/about in chat

### ISSUE THREAD

**Issue by tehseensagar** [bigbluebutton/bigbluebutton#8822]
Greetings,

I want to hide About and Help option in chat windows with appears under on top right 3dots. below is an image 

[https://i.ibb.co/82RVvhx/menu.png](https://i.ibb.co/82RVvhx/menu.png)

Regards

**Comment by KDSBrowne** [comment]
There is an option in the config to hide the help button `showHelpButton`:
https://github.com/bigbluebutton/bigbluebutton/blob/v2.2.x-release/bigbluebutton-html5/private/config/settings.yml#L77

No option to hide the About button, You would have to remove it from the code here:
https://github.com/bigbluebutton/bigbluebutton/blob/v2.2.x-release/bigbluebutton-html5/imports/ui/components/nav-bar/settings-dropdown/component.jsx#L237

**Comment by tehseensagar** [comment]
Thanks @KDSBrowne 
in my case it's done via following path :

`nano /usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml`

Where I'm able to change About info and disable help butting.

Regards
