### ISSUE TITLE
Uploading files

### ISSUE THREAD

**Issue by WizardKid** [bigbluebutton/bigbluebutton#8823]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
I am requesting a feature to be added to this due to me being part of the cybersecurity community. Detection of backdoor pdf files under the guise of presentation

**Comment by basisbit** [comment]
@WizardKid any suggestion on how this could done? There are considerations to move LibreOffice and the PDF conversion tools into an unprivileged/root-less docker container which could be thrown away after each file conversion. Besides this, the app-armor profile docker-default maybe could be locked down further if someone has the required skills and free time to do that. Anything else we might be missing?
