### ISSUE TITLE
BigBlueButton stop working after rebooting the server

### ISSUE THREAD

**Issue by aashon** [bigbluebutton/bigbluebutton#8828]
Hi there, 

I Do have fresh Unbuntu 16.04 installed with the automated script to install the bbb-install.sh

after finishing the installation I do see that everything working perfectly.
but when I do a reboot to my server and check the bbb it seems does not work and got "404 Not Found"

root@me:~# bbb-conf -status
nginx —————————————————► [✔ - active]
freeswitch ————————————► [✔ - active]
redis-server ——————————► [✔ - active]
bbb-apps-akka —————————► [✔ - active]
bbb-transcode-akka ————► [✔ - active]
bbb-fsesl-akka ————————► [✔ - active]
red5 ——————————————————► [✔ - active]
mongod ————————————————► [✔ - active]
bbb-html5 —————————————► [✔ - active]
bbb-webrtc-sfu ————————► [✔ - active]
kurento-media-server ——► [✔ - active]
etherpad ——————————————► [✔ - active]
bbb-web ———————————————► [✔ - active]
root@me:~#

root@me:~# bbb-conf --check

BigBlueButton Server 2.2.2 (1781)
                    Kernel version: 4.4.0-176-generic
                      Distribution: Ubuntu 16.04.6 LTS (64-bit)
                            Memory: 24689 MB
                         CPU cores: 8

/usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties (bbb-web)
       bigbluebutton.web.serverURL: https://my.domain.com
                defaultGuestPolicy: ALWAYS_ACCEPT
                 svgImagesRequired: true

/etc/nginx/sites-available/bigbluebutton (nginx)
                       server name: my.domain.com
                              port: 80, [::]:80
                              port: 443 ssl
                    bbb-client dir: /var/www/bigbluebutton

/var/www/bigbluebutton/client/conf/config.xml (bbb-client)
                Port test (tunnel): rtmp://my.domain.com
                              red5: my.domain.com
              useWebrtcIfAvailable: true

/opt/freeswitch/etc/freeswitch/vars.xml (FreeSWITCH)
                       local_ip_v4: xxx.xxx.xxx.xxx
                   external_rtp_ip: stun:stun.freeswitch.org
                   external_sip_ip: stun:stun.freeswitch.org

/opt/freeswitch/etc/freeswitch/sip_profiles/external.xml (FreeSWITCH)
                        ext-rtp-ip: $${local_ip_v4}
                        ext-sip-ip: $${local_ip_v4}
                        ws-binding: :5066
                       wss-binding: xxx.xxx.xxx.xxx:7443

/usr/local/bigbluebutton/core/scripts/bigbluebutton.yml (record and playback)
                     playback_host: my.domain.com
                 playback_protocol: https
                            ffmpeg: 4.2.2-1bbb1~ubuntu16.04

/etc/bigbluebutton/nginx/sip.nginx (sip.nginx)
                        proxy_pass: xxx.xxx.xxx.xxx

/usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml (Kurento SFU)
                        kurento.ip: xxx.xxx.xxx.xxx
                       kurento.url: ws://127.0.0.1:8888/kurento
                    localIpAddress: xxx.xxx.xxx.xxx
               recordScreenSharing: true
                     recordWebcams: true
                  codec_video_main: VP8
               codec_video_content: VP8

/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml (HTML5 client)
                             build: 862
                        kurentoUrl: wss://my.domain.com/bbb-webrtc-sfu
                  enableListenOnly: true

# Potential problems described below

root@me:~#

from the logs, I don't see any errors.

any help ?

**Comment by aashon** [comment]
ok here after debugging this, I did find the solution

after reboot, the Docker does not run automatically the greenligh, and need to run it from the greenlight folder as typing this command " docker-compose up -d " and then type " bbb-conf --restart "

**Comment by Salamit** [comment]
@aashon Thank you. It worked.
