### ISSUE TITLE
when upgrade mongodb to 3.6+ error 404 occured for html5 client 

### ISSUE THREAD

**Issue by headria** [bigbluebutton/bigbluebutton#8829]
When I upgrade mongodb to 3.6+then the html5 client not wotking and show me the 404 error. 

[https://filebin.net/hebp69l1tn2hnu8v/8.jpg?t=63k8wztr](url)

[https://filebin.net/d9vac0hjm2szmi1z/9.jpg?t=3vtk6j7u](url)

**Comment by basisbit** [comment]
The two uploaded files do not exist any more.
If this problem still occurs, please ask for support at https://groups.google.com/forum/#!forum/bigbluebutton-dev
