### ISSUE TITLE
It' running !!! :-), but openssl dhparam -out /etc/nginx/ssl/dhp-4096.pem 4096

### ISSUE THREAD

**Issue by tpk109** [bigbluebutton/bigbluebutton#8832]
Hi there,
thanks a lot for the great documentation on how to install. Can't believe it is actually working ...

I got lost at the Let's encrypt part though. After installing it one still needs to run

openssl dhparam -out /etc/nginx/ssl/dhp-4096.pem 4096

right?

But there is only the sentence:
"To finish the SSL configuration, continue with the steps at Configure FreeSWITCH to user WebRTC."

But then one still has to do the stuff under the heading
"Configure BigBlueButton to load session via HTTPSAnchor link for: configure bigbluebutton to load session via https", right?

And one has missed the
openssl dhparam -out /etc/nginx/ssl/dhp-4096.pem 4096
which is only mentioned in the SSL instruction not using Let's Encrypt.

So at the end of Let's encrypt it could read something like this:

Run:
openssl dhparam -out /etc/nginx/ssl/dhp-4096.pem 4096

Continue with "Configure FreeSWITCH for using SSLAnchor link for: configure freeswitch for using ssl" and the chapters following that.

**Comment by basisbit** [comment]
The Let's encrypt installation instructions already include this just after `Next, generate a set of 4096-bit diffie-hellman parameters to improve security for some types of ciphers.` here: https://docs.bigbluebutton.org/2.2/install.html#using-lets-encrypt
