### ISSUE TITLE
Wrong parsing for unicode when creating a custom poll

### ISSUE THREAD

**Issue by mabras** [bigbluebutton/bigbluebutton#8833]
<img width="1280" alt="Screenshot_2020-03-22_at_7_31_14_PM" src="https://user-images.githubusercontent.com/9248917/77256916-b6169f80-6c79-11ea-9255-51a30e2f5ada.png">

When creating a custom poll using Arabic, the characters are not show correctly.
لا ===> ن لا
نعم ===> عم

The characters are just wrong and mixed. The order of choices is also wrong.
This test is from demo.bigbluebutton.org. My BBB is Arabic only and this make the poll unusable.

Thanks.

**Comment by mosallaei** [comment]
Hi, 
![poll](https://user-images.githubusercontent.com/13038276/78861193-7279af00-7a49-11ea-8afc-a8d1197af964.PNG)

same problem,
every thing is OK during polling, but after publishing result, Unicode characters just shift and mix together .

**Comment by mailalaki** [comment]
hi
same problem
in Firefox everything is fine, but in Chrome, the options are reversed and incorrect.
@ffdixon 
![Capturezxczxc](https://user-images.githubusercontent.com/13551603/80273719-04401800-86ea-11ea-8345-b08adc5ebf1e.PNG)
