### ISSUE TITLE
[quick fix] typo on website

### ISSUE THREAD

**Issue by threeninefour** [bigbluebutton/bigbluebutton#8834]
"Polling" is misspelled as " poling" on the page for teachers. 

**To Reproduce**
1. Go to https://bigbluebutton.org/teachers/
2. Scroll down to 'BigBlueButton Features'
4. See typo

**Screenshot**
![Screenshot_20200322-144419__01](https://user-images.githubusercontent.com/20506454/77257621-e34c5900-6c4b-11ea-9e5f-4774afd0a7b7.jpg)

**Additional context**
I know this isn't a traditional issue, but I am unsure of how else to reach the people managing the website. I'm trying to convince people to use an open source option and I think the typo could reflect poorly on the service. Please let me know if there is a better way to reach out about the kind of problem; I know I'm opening an issue on the actual product and not the website.

**Comment by ffdixon** [comment]
Fixed!
