### ISSUE TITLE
add google analytics 

### ISSUE THREAD

**Issue by freehussain** [bigbluebutton/bigbluebutton#8837]
hello,

can we add google analytics to bbb?

**Comment by haviduck** [comment]
you can add it via the html snippets found within the meteor structure i believe. but i think its overwritten as soon as you --restart.

**Comment by GremL1N** [comment]
`--restart` don't overwrite it.
you can add it here `/usr/share/meteor/bundle/programs/web.browser/head.html`
But remember update/reinstall of BBB rewrite it.
Also i think you need to add analitics to Greenlite using `.env` file.  [sample.env](https://github.com/bigbluebutton/greenlight/blob/master/sample.env)

**Comment by petterreinholdtsen** [comment]
I notice the demo.bigbluebutton.org site already feed user information to Google according to
https://webbkoll.dataskydd.net/en/results?url=http%3A%2F%2Fdemo.bigbluebutton.org%2Fgl%2F , using several URLs.  It would be a lot easier to recommend using BigBlueButton if information about its users did not leak to Google and other third parties.

But it is very nice if Google is not fed user information in the default installation setup. :)

**Comment by basisbit** [comment]
Thank you @GremL1N for answering this support question!
