### ISSUE TITLE
Audio Encoding for Music Lessons

### ISSUE THREAD

**Issue by hybridpicker** [bigbluebutton/bigbluebutton#8838]
Video Conferencing software is naturally optimized for voice/people talking with each other.
Given the actual crisis, we're investigating the use of Big Blue Button (BBB) for music teaching sessions. Therefore I'm wondering if it would be somehow possible to introduce a different "mode" to optimize the (audio) stream for (instrumental) music [1]. I'm not sure if this requires another (audio) codec and or if this is possible at all. However, I'd like to raise the awareness that such a feature would be highly appreciated and might lead to a pretty unique position in the market, since I'm not aware any of the current solutions offers this.

[1] Like: guitar, piano, trumpet, et cetera.

**Comment by maikmerten** [comment]
I think BigBlueButton uses the Opus audio codec, which is a low-latency general-purpose audio codec. Opus is quite amazing, actually, and no other codec should be necessary - only configuration, if the default settings employed by BBB are insufficient for your needs.

Did you try BBB for your purpose and found quality lacking?

**Comment by hybridpicker** [comment]
Did some test-lessons yesterday. Sound is great when talking to my student but really not satisfying while playing/listening to an instrument.

**Comment by hybridpicker** [comment]
After comparing Team Speak to BBB I can be more precise. 
It would help a lot, if we could disable the noise-canceling while teaching music. So that is possible to hear silent parts on an instrument as well instead of the signal that is muted for noise-canceling-reasons...

**Comment by pabloapico** [comment]
i have done a research related to bigbluebutton audio quality.
What you mention is possible with a few tweaks:
With enough bandwith you may adjust opus.conf and conference.conf.xml to get better audio quality.
Also you may change the confort noise and energy level to tell bbb to send the "silent parts".

**Comment by mariogasparoni** [comment]
More information can be found in:
- #13299
