### ISSUE TITLE
Some praise

### ISSUE THREAD

**Issue by haviduck** [bigbluebutton/bigbluebutton#8839]
Hello,
This is not an issue nor a bug. 
Just wanted to let you know, if you are not already aware, that in these corona days, bigcorp lms systems are failing to provide videocoms to schools etc. i have deployed a 
 huge, free  instance of bbb available to everyone from norways schools, companies and private users to alleviate their non-functioning communication systems. Its not the lms fault, noone could expect the current loads, but alot of schools and companies here are now saved by having bbb available.  so thank you for the efforts youve put into this.

Hopefully hosting companies will see this soon and start jumping in with hw and bandwidth (Currently doing fine, but exponentially growing)

**Comment by mountainfly** [comment]
Same here, praise to you for all the hard work put into this! Incredible whats already working.

**Comment by ffdixon** [comment]
@haviduck So glad to hear this!  Can you send a tweet on this to @bigbluebutton and we'll RT.

**Comment by haviduck** [comment]
@ffdixon did it, but had to signup, never used that twitterotron. it had an awful char limitation so hopefully i crammed enough in there.

**Comment by Salamit** [comment]
> @haviduck So glad to hear this! Can you send a tweet on this to @bigbluebutton and we'll RT.

We did the same to @ffdixon.
