### ISSUE TITLE
Cannot change default Home Room name in 2.2.2 and latest Greenlight

### ISSUE THREAD

**Issue by ittrainingdev** [bigbluebutton/bigbluebutton#8840]
**Describe the bug**
Cannot change default Home Room name in 2.2.2 using latest Greenlight

**To Reproduce**
Install latest BBB using script. Then install Greenlight as per instructions on BBB site.
Change home room name by editing the language file in ~/greenlight/config/locales
Restart BBB
Regenerate a container

**Expected behavior**
Should be able to change the name of the home room by editing the language file in ~/greenlight/config/locales

**Actual behavior**
Changing the name does not get picked up despite restarting BBB and regenerating a container

**Additional context**
This was possible under previous version

**Comment by GremL1N** [comment]
This is Greenlight issue, not BBB.
this https://github.com/bigbluebutton/greenlight/pull/951 change behavior. Looks around  `t("home_room")`

**Comment by basisbit** [comment]
Thank you GremL1N for answering this issue!
