### ISSUE TITLE
Use HTTPS URL in GitHub description

### ISSUE THREAD

**Issue by paulmenzel** [bigbluebutton/bigbluebutton#8841]
Please use https://bigbluebutton.org/ in the GitHub description of https://github.com/bigbluebutton/bigbluebutton/ to save at least one Web request and to avoid certain attack vectors.

```
$ curl -I http://www.bigbluebutton.org/
HTTP/1.1 301 Moved Permanently
Date: Mon, 23 Mar 2020 16:29:03 GMT
Server: Apache/2.4.18 (Ubuntu)
X-Pingback: http://bigbluebutton.org/xmlrpc.php
X-Redirect-By: WordPress
Location: https://bigbluebutton.org/
Content-Type: text/html; charset=UTF-8
```

**Comment by basisbit** [comment]
@ffdixon could you please do this change in the `Edit` button on the top right of https://github.com/bigbluebutton/bigbluebutton and then adding the missing `s` to the `http://` so we can close this issue?

**Comment by antobinary** [comment]
Just made the change. Thank you guys for noticing and bringing attention to it!
![Screenshot from 2021-04-14 08-52-51](https://user-images.githubusercontent.com/6312397/114713160-db4fd300-9cfe-11eb-9446-4ebedc949721.png)
