### ISSUE TITLE
Restrict maximum webcam sharing on Create

### ISSUE THREAD

**Issue by samuelpeixoto** [bigbluebutton/bigbluebutton#8844]
**Is your feature request related to a problem? Please describe.**
When creating the classroom, it would be very interesting if we could restrict the number of users who can share the webcam in one session. The sharing of webcam is one of the resources that most require processing on the server, we would do a better management and avoid abuse.

**Describe the solution you'd like**
In the creation call, we could send the parameters or something:
` maxAttendeeWebcam '=>' 5 ',
'maxModeratorWebcam' => '5' '`
or
` maxParticipantsWebcam '=>' 5 ''`

**Describe alternatives you've considered**
We looked for a solution at (https://docs.bigbluebutton.org/dev/api.htm) and also in groups and today we don't have a solution for that.

**Comment by GremL1N** [comment]
maybe this one `viewersInWebcam: 16` in settings.yml of html-5 client may help you. But i'm not sure.

**Comment by mabeyj** [comment]
I have tried the following settings:

```
enableLimitOfViewersInWebcam: true
viewersInWebcam: 2
```

This only triggers a popup for the presenter when the number of webcams for viewers reaches the limit:

![image](https://user-images.githubusercontent.com/773401/79369233-01de0100-7f27-11ea-9b8b-e82569a502bd.png)

Clicking enable in this popup doesn't seem to do anything.

+1 for having the ability to set a hard limit on webcams.

The [minimum server requirements recommend a c5.xlarge instance](http://docs.bigbluebutton.org/2.2/install.html#minimum-server-requirements), and the [FAQ says this can support up to 150 users](https://docs.bigbluebutton.org/support/faq.html#how-many-simultaneous-users-can-bigbluebutton-support). I'm using a c5.2xlarge (double the minimum requirements), and we had a session with 40 users all trying to enable webcams at once. This maxed out the CPU after 20-30 webcams.

We sometimes have multiple sessions of unpredictable sizes running at the same time, and it's a concern that everything can be disrupted by someone having a big webcam session. I'd rather be able to set a limit than always be at risk of a single session hogging the entire server.

**Comment by Jossef-767** [comment]
I also suffer from this bug.
For me, it's really important to  restrict the number of  cameras,
It would be better not to ask the teacher,
The teacher doesn't understand the meaning of the message that suddenly pops up on the screen.
Simply limit cameras by the number set in the file ( or In the creation call if this will be implemented )

**Comment by tncoltd** [comment]
I also suffer from this bug.

?

**Comment by ConfMe** [comment]
This restriction is very important to me too.

?

**Comment by manish-yadav** [comment]
The restriction could be implemented e.g only 6 most active webcam.  Rest could see on using next button.

**Comment by ahasanaki** [comment]
There is now a way to limit the maximum number of shared webcams?

**Comment by matiasilva** [comment]
Hi @ahasanaki, there always has been the two options in the settings.yml file.

**Comment by ahasanaki** [comment]
hi @matiasilva 
yes i did;  
settings.yml:
  enableLimitOfViewersInWebcam: true 
  viewersInWebcam: 2
and restart bbb(v2.2.21) and greenlight(v2.7.1)
but still more than 2 user(i test with 4 user) can share their webcam, and all of them can view each other

**Comment by Jossef-767** [comment]
see this answer from Chad Pilkey
https://groups.google.com/forum/?fromgroups#!searchin/bigbluebutton-dev/Limit$20webcam|sort:date/bigbluebutton-dev/oHq4_zz7eGM/sQinX0SHAgAJ

**Comment by ffdixon** [comment]
The work to implement this is underway.  See https://github.com/bigbluebutton/bigbluebutton/pull/10213.

**Comment by Jossef-767** [comment]
Hi Fred
Will this RP include a simple option to limit the number of open cameras.?
The reason is that the infrastructure of the client should also be considered.
In my server, I only allow one cameraProfiles. Which includes minimal constraints settings.
option to limit the number of open cameras Is really needed.

**Comment by prlanzarin** [comment]
Not in that PR, but in a subsequent one, yes. There are a set of things being done to video in 2.2 which will be detailed in due time.

**Comment by mnjsnj** [comment]
settings.yml:
enableLimitOfViewersInWebcam: true
viewersInWebcam: 2 not working

**Comment by hex-m** [comment]
> settings.yml:
> enableLimitOfViewersInWebcam: true
> viewersInWebcam: 2 not working

This issue is about extending the API to limit the number of cams when creating a meeting. Please create a new issue if the available settings to limit the number of webcams does not work for you. (It seems like you are not the only person with this problem, see e.g. https://github.com/bigbluebutton/bigbluebutton/issues/9657)

**Comment by alialic** [comment]
@samuelpeixoto 
Hi. Has your solution been implemented?

**Comment by prlanzarin** [comment]
Fixed in #14505

**Comment by iamwil98** [comment]
Greetings, I have the same problem, any solution where we can change the number of active cameras in a session?
