### ISSUE TITLE
huge concurrent user per session

### ISSUE THREAD

**Issue by freehussain** [bigbluebutton/bigbluebutton#8845]
hello,

is there way to support 8000 concurrent user on single session? 

it was written there "We recommend no single sessions exceed one hundred (100) users"

any one have an idea please

**Comment by basisbit** [comment]
No, sorry, this is not supported and can't be done with BigBlueButton without a major rewrite of the event handling system and also some architecture changes to allow for connecting external freeswitch + kurento servers. The UI also would have to be reworked quite extensively for this.

In general, you would not want 8000 people in one real room all with microphones and being able to turn on webcam and all the other features. That is not what such webinar + typical school setting software is designed for. Instead, consider only having the main active participants in the BBB meeting room, then do a video stream to some video streaming service (for example Twitch or YouTube and then have viewers watch there.
