### ISSUE TITLE
Allow custom poll with more than 5 options

### ISSUE THREAD

**Issue by ianme** [bigbluebutton/bigbluebutton#8847]
Although 5 choices seems a reasonable max number for custom polls, it could be useful to be able to override somehow this limit.
For example, some teachers use physical clickers to poll in a classroom and have multiple-choice questions with up to 10 choices.

**Comment by frank-miller9** [comment]
You can update the settings in:
```/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml ```
```
  poll:
    enabled: true
    max_custom: 10
```

**Comment by Sohalt** [comment]
Is there any reason why there is a limit at all?

**Comment by D33M0N** [comment]
is there a better place to change this setting, so it doesn't get overwritten by BBB update or some automate settings generation?

**Comment by antobinary** [comment]
Looks like @frank-miller9 provided the answer.
There's need for some limit for practical purposes - be able to display the results without much scrolling (if any), construct annotation of results, display on small screens, etc
