### ISSUE TITLE
zoom video in live

### ISSUE THREAD

**Issue by javadhadinezhad** [bigbluebutton/bigbluebutton#8849]
Hi I need to zoom in when sending videos with the mobile camera on my back. Is this possible?

**Comment by javadhadinezhad** [comment]
navigator.mediaDevices.getUserMedia({
				video : videoConstraints,
				audio : audioConstraints
			})
			.then(async mediaStream => {
				input_range.style.display = '';
				var video = document.createElement('video');
				video.muted = true;
				video.srcObject = mediaStream;
				await sleep(1000);
				const track = mediaStream.getVideoTracks()[0];
				const capabilities = track.getCapabilities();
				const settings = track.getSettings();
				if ('zoom' in capabilities) {
					input_range.min = capabilities.zoom.min;
					input_range.max = capabilities.zoom.max;
					input_range.step = capabilities.zoom.step;
					input_range.value = settings.zoom;
					input_range.oninput = function(event) {
						track.applyConstraints({
							advanced: [{
								zoom: event.target.value
							}]
						});
					}
					
				} else {
					alert("not zoom");
				}
				video.setAttribute('autoplay', true);
				video.setAttribute('playsinline', true);
				video.setAttribute('controls', true);
				video.setAttribute('muted', false);
				video.setAttribute('volume', 1);
				video.setAttribute('id', mediaStream.id);
				mediaStream.streamid = mediaStream.id;
				connection.attachStreams.push(mediaStream);

				var event = {
					type: 'local',
					mediaElement: video,
					stream: mediaStream,
					streamid: mediaStream.id,
					userid : connection.userid,
					isVideo : true
				  };
				  connection.addStream(mediaStream);
				 
			});
		function sleep(ms = 0) {
			return new Promise(r => setTimeout(r, ms));
		}

**Comment by matiasilva** [comment]
Hi @javadhadinezhad, are you proposing an addition to the code above? If so, please go ahead and submit a pull request!
