### ISSUE TITLE
unable to share audio/webcam

### ISSUE THREAD

**Issue by ssilayaraja** [bigbluebutton/bigbluebutton#8851]
Hi All,
I installed BBB2.2 in ubuntu 16.04 behind hardware firewall with below command
wget -qO- https://ubuntu.bigbluebutton.org/bbb-install.sh | bash -s -- -v xenial-220 -s bbb.xxxx.com -e info@xxxx.com -x 

After installation done unable to join Audio or share webcam. getting 1002 and 1020 error respectively. Can anybody tell me what else need to be done.

I have allowed below ports in firewall. 
80, 443
tcp -7443
udp- 16384 - 32768

Thanks in Advance.

**Comment by jibon57** [comment]
Have you followed this doc?
http://docs.bigbluebutton.org/2.2/configure-firewall.html

**Comment by ssilayaraja** [comment]
Thank you @jibon57.  
Error fixed after adding public ip as below in "/etc/kurento/modules/kurento/WebRtcEndpoint.conf.ini"
 
externalAddress=219.91.219.36
