### ISSUE TITLE
Using öäü in chat leads to seemingly full dataloss: `tr': invalid byte sequence in US-ASCII (ArgumentError)

### ISSUE THREAD

**Issue by someone-somenet-org** [bigbluebutton/bigbluebutton#8860]
**Describe the bug**
Using normal german `öäü` characters, will lead to the following error message and a loss of the event infos, making the conference recording especially the whireboard seemingly total dataloss.

```
I, [2020-03-24T20:19:39.150591 #4653]  INFO -- : /usr/local/bigbluebutton/core/lib/recordandplayback/events_archiver.rb:320:in `tr': invalid byte sequence in US-ASCII (ArgumentError)
E, [2020-03-24T20:19:39.214977 #4653] ERROR -- : Failed to archive acbc976dd89c491915b106240937dc97c41cc683-1585072096455
```
and follow-up
```
I, [2020-03-24T20:21:37.113376 #6125]  INFO -- : Starting sanity check for recording fcbc64fdbfd6e71830e061c35f2f00cfb7a7d71d-1584951149171
I, [2020-03-24T20:21:37.113444 #6125]  INFO -- : Checking events.xml
I, [2020-03-24T20:21:37.130252 #6125]  INFO -- : Repairing webcam videos
I, [2020-03-24T20:21:37.130517 #6125]  INFO -- : Repairing red5 serialized streams
I, [2020-03-24T20:21:37.131794 #6125]  INFO -- : Repairing deskshare videos
I, [2020-03-24T20:21:37.131976 #6125]  INFO -- : Repairing red5 serialized streams
I, [2020-03-24T20:21:37.132124 #6125]  INFO -- : Deleting keys
I, [2020-03-24T20:21:37.135195 #6125]  INFO -- : creating sanity done files
I, [2020-03-24T20:21:37.546505 #6127]  INFO -- : Starting sanity check for recording acbc976dd89c491915b106240937dc97c41cc683-1585072096455
I, [2020-03-24T20:21:37.546597 #6127]  INFO -- : Checking events.xml
E, [2020-03-24T20:21:37.546673 #6127] ERROR -- : error in sanity check: Events file doesn't exists.
E, [2020-03-24T20:21:37.546750 #6127] ERROR -- : sanity/sanity.rb:55:in `check_events_xml'
sanity/sanity.rb:99:in `<main>'
```

**To Reproduce**
1. Start a meeting
2. type öäü in the chat
3. start recording
4. stop recording
5. end meeting
6. run ``bbb-record --debug``
7. see errors.

**Expected behavior**
1: The archiver not failing the "cleanup" operation. Why is that even needed?
```
# Apply a cleanup that removes certain ranges of special
# control characters from user-provided text
```

2: sanity checker not failing to check for sanity and deleting the data from redis before verifying that everything is sane...

**Actual behavior**
Errors, see above and as it seems a total dataloss of said meeting, as it seems without the events xml it wont be possible to do anything?

**Desktop (please complete the following information):**
 - debian10 stable + bpo.
 - Chromium 80.0.3987.149

**Comment by someone-somenet-org** [comment]
First issue is fixed by setting the locale via `/etc/locale.conf` and not via `/etc/default/locale`.

Second still persists: sanity checker should not delete data unless it has verified that data were sucessfully written to disk.

**Comment by lonesomewalker** [comment]
Please read readme.md:
You can install on a Ubuntu 16.04 64-bit server.
This will work as expected ;-)

**Comment by someone-somenet-org** [comment]
This starts to feel like a cult here ... `use ubuntu 16` seems to be the one only response for everything here ... does that make inexistent code magically appear? (This issue) Does that magically rename network interfaces? Will this fix all the obvious architectural/design and QA issues?

Obviously the answer is no to all of them and its not usefuk to not even consider moving forward from the legacy software corner. I mean: yeah, its frustrating that even seemingly trivial things dont work with bbb's architecture, but thats no reason to go cultish and `ubuntu 16!` all the issues.

Im starting to wonder if bbb will close doors in 13 months?

**Comment by lonesomewalker** [comment]
Calm down...
You want a running system, go for the recommendations.
If you leave this path, you have to know what you are doing.
BBB is tested well with Ubuntu 16, the next BBB version will hopefully give other choices...

Greetings from a Debian lover :P

**Comment by kepstin** [comment]
We very clearly state in the install directions that we require a UTF-8 system locale, and provide instructions for setting that and verifying it on our supported Ubuntu install environment. If you're on a different system, it's up to you to enforce this and test the system as needed.

That said, we will happily accept patches which correct places like this where we make implicit assumptions about the system locale encoding.

**Comment by someone-somenet-org** [comment]
Will re-formulate, as obviously i did not bring the issue across.
