### ISSUE TITLE
WebCam Doesn't work on IOS (BBB 2.2.2)

### ISSUE THREAD

**Issue by rriscado** [bigbluebutton/bigbluebutton#8862]
**Describe the bug**

When I connect on meeting room using an Apple device, the WebCam doesn't send image to server. I receive error 1020

If I don't use Apple devices, it's working fine.

**Additional context**
If I don't use Apple devices, it's working fine.
We use TURN server (https://docs.bigbluebutton.org/2.2/setup-turn-server.html)

**To Reproduce**
1. Enter on meeting
2. Chose webcam and quality (In this moment i see my image on webcam)
3. Wait webcam loading
4. See error 1020

**Expected behavior**
When i can share webcam on any devices, Android, IOS etc

**Screenshots**

![WhatsApp Image 2020-03-16 at 19 17 50](https://user-images.githubusercontent.com/14829973/77482320-687a6e00-6e04-11ea-8a2b-95cdbdf69fb9.jpeg)
![WhatsApp Image 2020-03-16 at 19 17 48](https://user-images.githubusercontent.com/14829973/77482291-5698cb00-6e04-11ea-8cc2-b08f6b9f0fd5.jpeg)
![WhatsApp Image 2020-03-16 at 19 17 52](https://user-images.githubusercontent.com/14829973/77482304-5d274280-6e04-11ea-8d8d-8a227a3d60de.jpeg)

**Desktop (please complete the following information):**
 - OS: IMac
 - IOS 10.12.6
 - Browser: Safari
 - Version: 12.1.2
 - Browser: Firefox
 - Version: 74.0

**Smartphone (please complete the following information):**
 - Device: IPhone 8Plus
 - OS: IOS 13.3.1
 - Browser: Safari
 - Version: 13.0

**Comment by prlanzarin** [comment]
Can you confirm the TURN configurations in bbb-web have both `turn:etc?transport=tcp` and `turns:etc?transport=tcp` entries?

**Comment by rriscado** [comment]
> Can you confirm the TURN configurations in bbb-web have both `turn:etc?transport=tcp` and `turns:etc?transport=tcp` entries?

Yes....


<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://www.springframework.org/schema/beans
        http://www.springframework.org/schema/beans/spring-beans-2.5.xsd">

    <bean id="stun0" class="org.bigbluebutton.web.services.turn.StunServer">
        <constructor-arg index="0" value="stun:turn.XXX.com"/>
    </bean>


    <bean id="turn0" class="org.bigbluebutton.web.services.turn.TurnServer">
        <constructor-arg index="0" value="93be134f9cfaeb73be7f5246618ed62d"/>
        <constructor-arg index="1" value="turns:turn.XXX.com:443?transport=tcp"/>
        <constructor-arg index="2" value="86400"/>
    </bean>

    <bean id="turn1" class="org.bigbluebutton.web.services.turn.TurnServer">
        <constructor-arg index="0" value="93be134f9cfaeb73be7f5246618ed62d"/>
        <constructor-arg index="1" value="turn:turn.XXX.com:443?transport=tcp"/>
        <constructor-arg index="2" value="86400"/>
    </bean>

    <bean id="stunTurnService"
            class="org.bigbluebutton.web.services.turn.StunTurnService">
        <property name="stunServers">
            <set>
                <ref bean="stun0"/>
            </set>
        </property>
        <property name="turnServers">
            <set>
                <ref bean="turn0"/>
                <ref bean="turn1"/>
            </set>
        </property>
    </bean>
</beans>

**Comment by prlanzarin** [comment]
@rriscado Can you please test the same scenario on test.bigbluebutton.org?
Just so that I can rule out some stuff before further debugging. Thanks.

**Comment by rriscado** [comment]
> @rriscado Can you please test the same scenario on test.bigbluebutton.org?
> Just so that I can rule out some stuff before further debugging. Thanks.

In test.bigbluebutton.org works fine.

I installed bbb 2.2.2 with bbb-instal.sh and I installed TURN following the documentation in https://docs.bigbluebutton.org/2.2/setup-turn-server.html

Can I check in some other configuration and log why this error occurs?

**Comment by prlanzarin** [comment]
Did you configure an UDP range in your coturn's instance firewall? Try opening all the UDP range
on it as a testing measure.
Then try to adjust `min-port` and `max-port` in /etc/turnserver.conf to adjust the TURN allocation port range to what you had in mind.

**Comment by Natureshadow** [comment]
Could this be the documentation issue pointed out by me in #8875?

**Comment by rriscado** [comment]
> max-port

Thanks for help-me @prlanzarin !!!!

I open UDP Range (49152-65535) in my firewall.
The documentation contains this information, but I forgot to apply. Sorry!!!

Works Fine now!!!!

**Comment by iiiich** [comment]
I got the same issue here, even if I disable my ubuntu ufw-firewall of the coturn-server, I got no connection with ios devices. Everywhere else (chrome, firefox) it works wonderful.
