### ISSUE TITLE
bbb-conf --secret shows empty server and shared secret

### ISSUE THREAD

**Issue by lonesomewalker** [bigbluebutton/bigbluebutton#8866]
**Describe the bug**
After restarting a server, the output line from server is incomplete and the shared secret is empty (no secret shown)

Using latest BBB setup by bash script, Greenlight.

Greenlight .env holds the correct secret and is also able to connect.

![bbb](https://user-images.githubusercontent.com/856110/77515215-6d790500-6e78-11ea-82ea-4bce4ad95c30.jpg)

**Comment by prlanzarin** [comment]
@lonesomewalker try appending LC_ALL= before the command (eg `LC_ALL=bbb-conf --secret`)

**Comment by lonesomewalker** [comment]
Bug closed.
Reason: properties file was not edited the right way so the next --setip call wrote empty settings everywhere.
BBB still worked untill restart.
