### ISSUE TITLE
greenlight fails to load properly after OS reboot

### ISSUE THREAD

**Issue by mountainfly** [bigbluebutton/bigbluebutton#8872]
Hi,

I did a fresh install with bbb-install on a fresh virtual Ubuntu16.04 running in KVM on a Debian10 host. No firewalls (not on the host, nor the guest). Everything was working wonderfully until I rebootet the guest. I get a 404 instead of the greenlight frontend page.

my findings:
1. restarting nginx does NOT solve the problem
2. greenlight docker container is up and running, still 404
3. recomposing dockerized greenlight and THEN restarting nginx, does the trick.
So, what brings my frontend back up is:
cd ~/greenlight
docker-compose down
docker-compose up -d
systemctl restart nginx

Does anybody know what to do to prevent this and have the whole thing up and running even after OS reboot?

The logs only show a ton of those warnings:

Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Verbindungsaufbau abgelehnt: /127.0.0.1:6379

I confirmed that redis-server is the only one listening to 127.0.0.1:6379

**Comment by hmahdi-s** [comment]
Hi
I faced the same issue and i tried several way but eventually with update/rewrite command i fix it!
I don't know what was the problem exactly

**Comment by mountainfly** [comment]
Hi hmadi-s, would you give me the exact commands you used, I am a total docker noob. THX

**Comment by hmahdi-s** [comment]
just use same bbb-install command that you used for install.
it will update and rebuild project again and problem will be solve.

**Comment by matiasilva** [comment]
If you still have any more issues, please open a topic for discussion in the group: https://groups.google.com/forum/#!forum/bigbluebutton-greenlight.
