### ISSUE TITLE
Allow change camera resolution 

### ISSUE THREAD

**Issue by tehseensagar** [bigbluebutton/bigbluebutton#8874]
Hello,

How do I set the the resolution of camera to low for all who ever join the meeting ? 

Regards

**Comment by capilkey** [comment]
The profiles are in settings.yml.

/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml

**Comment by tehseensagar** [comment]
@capilkey thank you for your prompt response. It worked .

Regards
