### ISSUE TITLE
Packaging instructions

### ISSUE THREAD

**Issue by KoviRobi** [bigbluebutton/bigbluebutton#8876]
Hi,

I and possibly some others would like to package this to Nix, and I don't seem to be able to find any instructions as to how to package this. I have found https://docs.bigbluebutton.org/2.2/install.html but that has a `sudo apt-get install bigbluebutton` step, not sure how that package gets configured. Either just the debian package source or high level instructions would probably be super helpful if anyone could help me out.

Nix/NixOS/NixOps is a set of software that could potentially make spinning up Amazon EC2/Google Compute Engine/Hetzner/Azure instances very easy. For more explanation, Nix is a functional language which describes packages, NixOS is a whole OS (as a Nix package) which has a declarative configuration and a NixOS module could take care of servers and all as in the install instructions; while NixOps is the infrastructure deployment which does the configuring Amazon EC2/etc for machines, firewalls, etc. (Disclaimer, I have only used NixOps with Amazon EC2 but I believe it supports the others as well.)

For cross-linking, here is the in-progress Nix package https://github.com/NixOS/nixpkgs/pull/83072

Thanks,
Robert

**Comment by ffdixon** [comment]
This is a good suggestion.  For a script implementation of the installation of BigBlueButton, see 

  https://github.com/bigbluebutton/bbb-install

At the moment, the core devs are all pretty busy at their respective employers as a lot more people suddenly want to use BigBlueButton.

Not sure how much we can provide, but we think it's a good idea.

**Comment by KoviRobi** [comment]
Thanks, I think the script is the same as the manual install [2] in that they both have a 'magic' `apt-get install bigbluebutton` [1] and I was just wondering if anyone knows how that package is constructed.

I appreciate everyone is busy with all the lockdowns, that's the reason we are trying to package stuff like this, so that we can get people to easily spin up their own instances (hopefully) :)

[1] https://github.com/bigbluebutton/bbb-install/blob/master/bbb-install.sh#L293
[2] https://docs.bigbluebutton.org/2.2/install.html

**Comment by trs80** [comment]
I too have this question. The apt repository has no source packages either.
