### ISSUE TITLE
disable user to unmet his/her mic

### ISSUE THREAD

**Issue by tehseensagar** [bigbluebutton/bigbluebutton#8877]
Hellow,

I would like to disable users to unmet themselves so they wont disturb and listen the presenter.

Regards

**Comment by tehseensagar** [comment]
any one can help me in this ?

**Comment by Tainan404** [comment]
Hello @tehseensagar, what you can do is use the 'Share microphone' lock setting, which mute all users and doesn't allow unmute.

Follow GIF with example:
![Peek 2020-03-26 14-04](https://user-images.githubusercontent.com/15806883/77675244-71398400-6f6b-11ea-8424-ea8addf412c4.gif)

**Comment by tehseensagar** [comment]
dear you didnt get my point, I know about this option. If I turned it off, I may not be able to unmute it as well. I did enable modrator to turn mic of user. If I locked out from chat setting. even moderator can not unlock the mic unless he has to disable the option .

Regards

**Comment by capilkey** [comment]
Tainan gave you the answer to your question. The lock settings are how you restrict users from unmuting themselves. If you want to unmute a specific user, you unlock that one user and unmute them.
