### ISSUE TITLE
Maximum Server capacity

### ISSUE THREAD

**Issue by SebastianZiegler** [bigbluebutton/bigbluebutton#8878]
We set up a bbb server through the install script, we want that our teacher use bbb for teaching. So we set up a virtual server with 64 cores and 128 GB. But unfortunately the api of bbb doesn't came up. During troubleshooting we reduced the number of cores in steps of 12 cores and with a setup of 32 Cores ist runs perfect. 
Is there a component that couldn't not handle more than 32 cores?

BigBlueButton Server 2.2.2 (1796)
                    Kernel version: 4.4.0-176-generic
                    Distribution: Ubuntu 16.04.6 LTS (64-bit)
                    Memory: 132033 MB
                    CPU cores: 32

Can someone help?

**Comment by ffdixon** [comment]
We would recommend setting up 8 servers with 8 CPU cores instead and use Scalelite to load balance between them, see

  https://github.com/blindsidenetworks/scalelite

Your going to get *much* better performance.

**Comment by mclegrand** [comment]
I ran into the same issue, and it would be fixed by https://github.com/bigbluebutton/bbb-install/pull/108/files : increase greatly `LimitNOFILE` in `/lib/systemd/system/bbb-web.service`

**Comment by matiasilva** [comment]
Resolved and closed.
