### ISSUE TITLE
Breakout Room Recording - Not there/No Checkbox?

### ISSUE THREAD

**Issue by simpsonnth** [bigbluebutton/bigbluebutton#8880]
Reading back on some of the issues i see that it is possible to record breakout rooms. Once you have installed BBB and are in a live environment where would the file be to edit to add the ability to record breakout rooms? And would the recording be merged into the parent recording/appear under room recordings?

**Comment by simpsonnth** [comment]
Further to this i have changed the \var\www\bigbluebutton\client\conf\config.xml on the breakout room record = true but still no success

**Comment by GhaziTriki** [comment]
@simpsonnth You are checking the Flash client configuration. I think recording breakout rooms recording in the HTML5 client is not implemented yet.

**Comment by simpsonnth** [comment]
Yep on the HTML 5 client. There's the option there to do it and it can be done through Moodle but not on the standard BBB? @GhaziTriki

**Comment by matiasilva** [comment]
I believe recording of breakout rooms hasn't yet been implemented, there's a setting in bigbluebutton.properties but it doesn't seem to have any effect on the final published recording folder from what I've seen in a few of the google groups topics. Open a feature request if there isn't already one.
