### ISSUE TITLE
BBB HTML5 stops working

### ISSUE THREAD

**Issue by marializ** [bigbluebutton/bigbluebutton#8882]
We are using BigBlueButton 2.2 on Ubuntu VM, running for almost 2 weeks.
Students and teachers connect to video conference room in Moodle using BigBlueButtonBN plugin.

Two days in a row we had issue that video conferences stopped working. When we try to load conference room (https://xx.yyyyy.com/html5client/join?sessionToken=zzzzzzzzzz) it just tries to load but nothing happens.
Teachers & students who are using BBB are kicked out of the room and cannot connect again.

However server it self working, it is possible to open a record and watch it, main BBB page works, but if we try to connect to conference room it doesn't load.
There is enough free space in disk. Also processes: freeswitch, kurento-media-server, ffmpeg are running.

After bbb-conf --restart everything works ok.

This is the errors we found:
**/var/log/bigbluebutton/bbb-rap-worker.log**
E, [2020-03-24T11:36:39.413114 #41617] ERROR -- : SIGTERM
E, [2020-03-24T11:36:39.413271 #41617] ERROR -- : /usr/local/bigbluebutton/core/lib/recordandplayback.rb:123:in `each_line'
E, [2020-03-24T11:36:39.413290 #41617] ERROR -- : /usr/local/bigbluebutton/core/lib/recordandplayback.rb:123:in `block in exec_ret'
E, [2020-03-24T11:36:39.413303 #41617] ERROR -- : /usr/local/bigbluebutton/core/lib/recordandplayback.rb:122:in `popen'
E, [2020-03-24T11:36:39.413313 #41617] ERROR -- : /usr/local/bigbluebutton/core/lib/recordandplayback.rb:122:in `exec_ret'
E, [2020-03-24T11:36:39.413322 #41617] ERROR -- : /usr/local/bigbluebutton/core/scripts/rap-process-worker.rb:81:in `block (2 levels) in process_archived_meetings'
E, [2020-03-24T11:36:39.413332 #41617] ERROR -- : /usr/local/bigbluebutton/core/scripts/rap-process-worker.rb:57:in `each'
E, [2020-03-24T11:36:39.413342 #41617] ERROR -- : /usr/local/bigbluebutton/core/scripts/rap-process-worker.rb:57:in `block in process_archived_meetings'
E, [2020-03-24T11:36:39.413351 #41617] ERROR -- : /usr/local/bigbluebutton/core/scripts/rap-process-worker.rb:31:in `each'
E, [2020-03-24T11:36:39.413361 #41617] ERROR -- : /usr/local/bigbluebutton/core/scripts/rap-process-worker.rb:31:in `process_archived_meetings'
E, [2020-03-24T11:36:39.413371 #41617] ERROR -- : /usr/local/bigbluebutton/core/scripts/rap-process-worker.rb:156:in `<main>'

**/var/log/bigbluebutton/sanity.log**
`E, [2020-03-24T11:37:23.605880 #48253] ERROR -- : error in sanity check: LOADING Redis is loading the dataset in memory
E, [2020-03-24T11:37:23.605958 #48253] ERROR -- : /var/lib/gems/2.3.0/gems/redis-4.1.2/lib/redis/client.rb:126:in `call'
/var/lib/gems/2.3.0/gems/redis-4.1.2/lib/redis.rb:2280:in `block in hgetall'
/var/lib/gems/2.3.0/gems/redis-4.1.2/lib/redis.rb:52:in `block in synchronize'
/usr/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/var/lib/gems/2.3.0/gems/redis-4.1.2/lib/redis.rb:52:in `synchronize'
/var/lib/gems/2.3.0/gems/redis-4.1.2/lib/redis.rb:2279:in `hgetall'
/usr/local/bigbluebutton/core/lib/recordandplayback/events_archiver.rb:56:in `metadata_for'
/usr/local/bigbluebutton/core/lib/recordandplayback/events_archiver.rb:370:in `delete_events'
sanity/sanity.rb:113:in `<main>'`

What could be the problem?

Thanks.

**Comment by marializ** [comment]
capilkey, I have SSH access, I noticed that during day time most CPU takes freeswitch process, which I suppose is the main process for video conference session?
As we are running VM with 25CPU, 20GB RAM, so freeswitch process hitting ~700% CPU on top command.
I haven't noticed node process taking high CPU.

Is there any way to check many users connected to the server by using SSH?
Because it's hard to estimate how many students and teachers could be connected to BBB sessions.

Maybe each individual BBB session participant runs individual freeswitch process and we can count number of freeswitch processes and this would be total users connected to the server?

Thanks.

**Comment by capilkey** [comment]
A couple things.
* FreeSWITCH taking that much CPU likely means that there were a lot of people on the server.
* For the node CPU I was specifically looking for whether it was near to 100%. The HTML5 server-side process is single threaded so it will never take more than 100% CPU. If it's at or near to 100% then you've found the cause of your login slowdowns.
* Due to the HTML5 process being single threaded, the 25 CPUs (I think this means cores) on your server won't see full utilization because you'll hit a bottleneck before that

BigBlueButton scales best when there are many servers that are about 8 cores and 16 GB of RAM. You could have 3 BBB servers that are smaller and then put a BigBlueButton load balancer in-front of them to distribute the load. One example of a load balancer is Scalelite that we released https://github.com/blindsidenetworks/scalelite

**Comment by emostoyanov** [comment]
I am also running highly loaded BBB servers with lot's of RAM and CPUs. Have you tried this 👍 
https://groups.google.com/forum/?fbclid=IwAR0r4JaCWUc1b3-JM4DAEmG2csrnImuvgUwxFLrGuzXoliG8BWUyIda4WKY#!msg/bigbluebutton-dev/fLxENWbz238/5NkTni-7DwAJ
e.g. increase LimitNOFILE=8024 or more in   /lib/systemd/system/bbb-web.service
There are some Ubuntu OS tweaks that need to be made to optimize for such high loads. I am also increasing fs.file-max in /etc/sysctl.conf and reducing vm.swappiness as much as I can - it is set to 1 in my case with a  server with 128G RAM.

**Comment by matiasilva** [comment]
Good responses have been provided + two months of inactivity. The LimitNOFILE suggestion has now  been added to the `develop` branch. Closing now...
