### ISSUE TITLE
Greenlight install documentation proposes creation of insecure password

### ISSUE THREAD

**Issue by hannob** [bigbluebutton/bigbluebutton#8883]
**Describe the bug**
The documentation for Greenlight installation proposes to create an 8 byte hexadecimal password for postgresql with openssl. This is dangerously short.

See:
https://docs.bigbluebutton.org/greenlight/gl-install.html

The command
```
openssl rand -hex 8
```
creates a hexadecimal password, i.e. it restricts the characters to 0-9/A-F, making it needlessly insecure.

I propose changing this to something like:
```
openssl rand -base64 24
```
This will use base64, which is all characters and numbers as well as + and / (should be safe to use within a password) and use enough bytes to be safe.

**Comment by matiasilva** [comment]
Hello, thanks for raising this point. This issue belongs here https://github.com/bigbluebutton/greenlight as this repository is concerned solely with BBB.
