### ISSUE TITLE
ICE negotiation failed from internal networks with "no hairpin" NAT configuration

### ISSUE THREAD

**Issue by icyground** [bigbluebutton/bigbluebutton#8886]
**Describe the bug**
We have a running setup of BBB which is working well either in local or NAT mode, unfortunately it is not possible to connect from internal networks, when BBB is configured for NAT access.

**To Reproduce**
We have the following network setup:
![image](https://user-images.githubusercontent.com/1493116/77665744-5d4c4d00-6f80-11ea-9a50-0030aef41f07.png)
The Firewall is a Cisco ASA, which doesn't support hairpin NAT, so I followed the configuration guide and added the additional dummy NIC.

**Expected behavior**
BBB should work for users from internal networks and outside users.

**Actual behavior**
We tested the setup quite well before changing it to "NAT mode" and it was working well from internal networks and is now working well for everyone outside the firewall.
Unfortunately after setting up the NAT configuration, internal users can't get past the echo test, because its failing with Error 1007: ICE negotiation failed.
Having a look into `about:webrtc` shows, that the external IP is delivered as endpoint for external and internal clients. As the ASA doesn't support hairpin NAT, the internal clients can't connect.
Is there any way to get BBB to deliver different WebRTC endpoints depending on client location?

**Comment by tehseensagar** [comment]
have you tried with sturn / turn server behind NAT BBB server . 

https://docs.bigbluebutton.org/2.2/configure-firewall.html#configure-bigbluebutton-to-work-with-your-firewall

https://docs.bigbluebutton.org/2.2/setup-turn-server.html

**Comment by icyground** [comment]
I'm using a public available Turn Server for Kurento, as this is mentioned necessary for handling IP issues. This works proven well, as I had initially a wrong one entered and therefore Video was not working.
Using a Turn Server for BBB is not planed, as I don't have users behind restrictive firewalls.

**Comment by agutuyen-dev** [comment]
I have the same problem. When Free Switch configed with external IP, audio work well with public ip, but internal don't, and vice versa

**Comment by arpsyapathy** [comment]
@icyground  Hello!
You have solved the problem?
We have the same problem and we are looking for a solution.

**Comment by icyground** [comment]
@arpsyapathy Hi, we basically solved this, by enabling hairpin NAT for this service. It seems like, theres no other way around.

**Comment by arpsyapathy** [comment]
@icyground  Thank you, The good news is that you did it! Can I get a little more information? What is hairpin NAT?

**Comment by icyground** [comment]
@arpsyapathy It enables you clients in the network before the nat to reach the service on his nat address (in most cases the public ip). See this for more information: https://en.wikipedia.org/wiki/Hairpinning
