### ISSUE TITLE
feature request for common storage and per-admin permanent storage

### ISSUE THREAD

**Issue by hippylover** [bigbluebutton/bigbluebutton#8889]
Hello. I am working for a client of mine with a private school. The teachers often find themselves in the situation where they have to reupload teaching material that they commonly use. I realise new code will land in the next(?) release that makes the uploading process more painless. Nevertheless there is the desire that the teachers can have a place in the interface where they can upload common teaching material and also a drop-down list in "meeting"(i am talking greenlight here) where they can quickly open previously uploaded material.

So common permanent storage and per-teacher permanent storage.

I don't know if anyone would like to implement this. If not, i will do it for myself but i have to familiarise myself with a lot of the technologies you use. Like ruby, erb, probably everything else.

I will take a stab at just making the common upload widget. My plan is to just drop stuff in a subdir of public and make a dropdown inside "meeting" be able to open files quickly. Where on earth do i start? All hints welcome :-)

**Comment by hippylover** [comment]
Ok then. First i thought i would add another button inside the Organization page of Greenlight and upload files from there(inside: app/views/admins/components/_menu_buttons.html.erb).
```
<% if highest_role.get_permission("can_edit_roles")  || highest_role.name == "super_admin" %>
    <%= redirect_to "file_upload.html", class: "list-group-item list-group-item-action dropdown-item #{"active" if active_page == "file_uploads"}" do %>
      <span class="icon mr-4"><i class="fas fa-user-tag"></i>File Upload</span>
    <% end %>
  <% end %>
```
This is my first attempt. Although this gives me a:
![screen1](https://user-images.githubusercontent.com/28787979/77795627-31a79080-706e-11ea-9d6e-0fd181ce0aea.png)

on the Organization page. What is the proper way to fix this?

**Comment by hippylover** [comment]
I did: cp app/views/admins/roles.html.erb app/views/admins/file_uploads.html.erb and then copied the resultant code displayed to chrome instead of the auto-ruby erb thing which now gives me a nice "file uploads" button. However when i click that i get a 404 error. How to fix?

**Comment by matiasilva** [comment]
Hello. Thanks for showing great initiative. Unfortunately, this issue belongs here: https://github.com/bigbluebutton/greenlight. You can open a feature request there and collaborate with other developers there too.
