### ISSUE TITLE
Infinite canvas for whiteboard

### ISSUE THREAD

**Issue by Sohalt** [bigbluebutton/bigbluebutton#8892]
**Is your feature request related to a problem? Please describe.**
I'm frustrated when I start drawing something on the whiteboard and run out of space.

**Describe the solution you'd like**
It would be nice if the whiteboard extended infinitely beyond the slide.

**Comment by matiasilva** [comment]
Hi Sohalt, this doesn't really make a lot of sense for users who want to later save their annotated presentation afterwards. The whiteboard is in reality a blank slide on a PDF or presentation. I suggest you use existing online whiteboards and share your screen to those.
