### ISSUE TITLE
How do i remove the 'sign in' and 'sign up' button on the invite screen?

### ISSUE THREAD

**Issue by hippylover** [bigbluebutton/bigbluebutton#8893]
![invitedscreen](https://user-images.githubusercontent.com/28787979/77704048-8d194600-6fbc-11ea-8463-477a5b56d114.png)

Hello, i'd like to make a small tweak on my server. How would i remove the sign in and sign up button solely on this screen? It is just a small improvement since some students that don't speak english get confused.

If a hack is neccesary that's fine by me!

**Comment by cbares** [comment]
Hi,
If you are using the docker version, this line do the job:
```
docker exec -it greenlight-v2 sed -i "s/<%=\( link_to t\)/<%#\1/"  app/views/shared/_header.html.erb
```
Beware, it will be erase if you update the docker image... so I execute it each time I start docker-compose.

**Comment by hippylover** [comment]
Thanks a bunch!

**Comment by hippylover** [comment]
Well that solves the problem... somehow. but i specifically said only to remove the 'sign in' and 'sign up' buttons _on that specific page_, while this removes it for everyone not "current user"(whatever that is) on _whichever_ page(including frontpage). Edit: I managed to hack it away with css in: app/views/rooms/components/_room_event.html.erb
but i suppoose i could have done it like this too:

```<% elsif page == "invited">
                <% allow_greenlight_accounts = allow_greenlight_accounts? %>
          <% if allow_greenlight_accounts %>
            <%= link_to t("login"), signin_path, :class => "btn btn-outline-primary mx-2 sign-in-button" %>
          <% elsif Rails.configuration.loadbalanced_configuration %>
            <%= link_to t("login"), omniauth_login_url(:bn_launcher), :class => "btn btn-outline-primary mx-2 sign-in-button" %>
          <% else %>
            <%= link_to t("login"), signin_path, :class => "btn btn-outline-primary mx-2 sign-in-button" %>
          <% end %>

          <% if allow_user_signup? && allow_greenlight_accounts %>
            <%= link_to t("signup.title"), signup_path, :class => "btn btn-outline-primary mx-2 sign-in-button" %>
          <% end %>
        <% end %>```

in: 
app/views/shared/_header.html.erb

However. The code elsif == "invited" is obviously pseudo-code. I still don't know how to access the keywords ruby uses here.

**Comment by GhaziTriki** [comment]
This is a configuration help request for greenlight.
Grennlight issues should go to https://github.com/bigbluebutton/greenlight
Help requests are more effective when shared with the community https://groups.google.com/forum/#!forum/bigbluebutton-dev

**Comment by siavash79** [comment]
> Well that solves the problem... somehow. but i specifically said only to remove the 'sign in' and 'sign up' buttons _on that specific page_, while this removes it for everyone not "current user"(whatever that is) on _whichever_ page(including frontpage). Edit: I managed to hack it away with css in: app/views/rooms/components/_room_event.html.erb
> but i suppoose i could have done it like this too:
> 
> ```
> <% elsif page == "invited" %>
>                 <% allow_greenlight_accounts = allow_greenlight_accounts? %>
>           <% if allow_greenlight_accounts %>
>             <%# link_to t("login"), signin_path, :class => "btn btn-outline-primary mx-2 sign-in-button" %>
>           <% elsif Rails.configuration.loadbalanced_configuration %>
>             <%# link_to t("login"), omniauth_login_url(:bn_launcher), :class => "btn btn-outline-primary mx-2 sign-in-button" %>
>           <% else %>
>             <%= link_to t("login"), signin_path, :class => "btn btn-outline-primary mx-2 sign-in-button" %>
>           <% end %>
> 
>           <% if allow_user_signup? && allow_greenlight_accounts %>
>             <%# link_to t("signup.title"), signup_path, :class => "btn btn-outline-primary mx-2 sign-in-button" %>
>           <% end %>
>         <% end %>
> ```
> 
> in:
> app/views/shared/_header.html.erb
> 
> However. The code elsif == "invited" is obviously pseudo-code. I still don't know how to access the keywords ruby uses here.

Hi

Can you please share with us how you managed to hide it with css? (or any other way you've now actually implemented. I can use some help here
