### ISSUE TITLE
bbb-html5 to listen to 127.0.0.1 only

### ISSUE THREAD

**Issue by lkiesow** [bigbluebutton/bigbluebutton#8894]
The default installation makes you set up Nginx as a reverse proxy which means that it is completely unnecessary for bbb-html5 to listen to anything else than 127.0.0.1.

A simple fix is to modify `/usr/share/meteor/bundle/systemd_start.sh` and set:

```
…
export BIND_IP=127.0.0.1
PORT=3000 /usr/share/$NODE_VERSION/bin/node main.js
```

…right at the end of the file.

**Comment by matiasilva** [comment]
Seems like an appropriate change. Any way you could submit a pull request for this?

**Comment by lkiesow** [comment]
Unfortunately, no. The script in question seems to be part of the non-public packaging, not the codebase. My hope was that @ffdixon may be able to include it in one of the next builds.

**Comment by antobinary** [comment]
I applied this in the packaging of 2.2.29
`export BIND_IP=127.0.0.1`

Thanks for the recommendation!
