### ISSUE TITLE
Html5 customize problem

### ISSUE THREAD

**Issue by andreabasso39** [bigbluebutton/bigbluebutton#8898]
Hi,
I’ve installed bbb with bbb-install.sh and all work fine. But now I want customize also primary color of bbb-html5 client but I cannot find where is the file described in my server. Can you help me?

**Comment by vidukapoor** [comment]
for this you have to create the complete development build, on your server https://docs.bigbluebutton.org/2.2/dev.html

**Comment by GhaziTriki** [comment]
You can find more documentation here http://docs.bigbluebutton.org/2.2/dev.html#developing-the-html5-client

**Comment by matiasilva** [comment]
Closed as sufficient help has been provided.

**Comment by borhanreo** [comment]
> You can find more documentation here http://docs.bigbluebutton.org/2.2/dev.html#developing-the-html5-client

I have also flow this instruction. It's working well as customize html5. But showing an error **call timeout 1006** when i am trying to connect with audio. 

![image](https://user-images.githubusercontent.com/11036088/108814771-94d2d780-75dd-11eb-9e9b-a88b8b41919f.png)
Could you help me please

**Comment by ffdixon** [comment]
@borhanreo Can you post this to bigbluebutton-dev with more information (see https://docs.bigbluebutton.org/2.2/getting-help.html#help-installing-or-running-bigbluebutton).
