### ISSUE TITLE
Function returning undefined in the first state if 'bbb_preferred_camera_profile' isn't set.

### ISSUE THREAD

**Issue by Tainan404** [bigbluebutton/bigbluebutton#8899]
**Describe the bug**
[This](https://github.com/bigbluebutton/bigbluebutton/blob/develop/bigbluebutton-html5/imports/ui/components/video-provider/service.js#L336) function returns undefined when the settings 'bbb_preferred_camera_profile' isn't setted, because [this](https://github.com/bigbluebutton/bigbluebutton/blob/develop/bigbluebutton-html5/imports/ui/components/video-provider/service.js#L35) that code try to get the id from a array, it's doesn't throw any error because if it doesn't exist the js returns undefined.

**To Reproduce**
1. Add a log bellow the [this](https://github.com/bigbluebutton/bigbluebutton/blob/develop/bigbluebutton-html5/imports/ui/components/video-provider/service.js#L35) logging the property 'userParameterProfile'
2. See error

**Expected behavior**
Returns the profile setted as default in setting.yml

**Actual behavior**
Returns undefined

**BBB version (optional): 2.2

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser Chrome
 - Version 80

**Comment by matiasilva** [comment]
Closed for now as this issue has gone stale, feel free to follow up.
