### ISSUE TITLE
Webcam inconsistency on mobile

### ISSUE THREAD

**Issue by Tainan404** [bigbluebutton/bigbluebutton#8902]
**Describe the bug**
On mobile when is sharing webcam and lock the screen the user will be disconnected from the meeting, if the user unlock the screen the client reconnects the user easily, but is showed to user that he's in webcam connection, but it just showhist locl strem and his webcam isn't shared to other users.

**To Reproduce**
1. Join to the meeting
2. Share webcam
3. Lock the screen
4. wait until be disconnected
5. unlock the screen
6. look the inconsistency

**Expected behavior**
Share the webcam with the other users

**Actual behavior**
Just shows the local stream

**Screenshots**
![Chrome-compressed](https://user-images.githubusercontent.com/15806883/77799197-095e6880-7053-11ea-8d03-9858a2e4d5a6.gif)

**BBB version: 2.3

**Smartphone (please complete the following information):**
 - Device: xiaomi redmi note 6 pro
 - OS: android 8
 - Browser Chrome
 - Version 80

**Comment by addy90** [comment]
I cannot confirm this on a Samsung smartphone,
but what you describe happens to me when I disable or enable WLAN and switch to mobile data while having video running. Then exactly this happens! Audio reconnects, presentation too, screenshare hangs like video.
Can you confirm that it happens with switch of WLAN to mobile data and back?

**Comment by hmahdi-s** [comment]
I had the same problem and i think it should have two solution.
1- bigbluebutton must get permission to awake screen from locking.
2- find the problem when the screen lock.

**Comment by matiasilva** [comment]
Can you confirm that this issue still persists on the latest version of BBB, 2.2.17?

**Comment by Tainan404** [comment]
It doesn't happens anymore
