### ISSUE TITLE
change settings.yml not effected

### ISSUE THREAD

**Issue by hmahdi-s** [bigbluebutton/bigbluebutton#8911]
I change helpLink in  settings.yml  and restart by these command but not effected.
bbb-conf --restart
bbb-conf --clean

what is the viewersInWebcam?
Is there any limitation for number of webcam in a class?

**Comment by antobinary** [comment]
Hi @hmahdi-s 
The only thing I can come up with is browser caching. Clear your browser cache and try again. I have had good success restarting bbb to pick up the modified settings.yml

**Comment by matiasilva** [comment]
As stated above, these settings take effect on a restart of BBB. Closed.
