### ISSUE TITLE
html5 jitter buffer configuration

### ISSUE THREAD

**Issue by mreza73** [bigbluebutton/bigbluebutton#8913]
in some conditions voices have some jitter and shattering 
i think it's need some jitter buffer on client side
it will be very good if have such option on freeswitch and html5 client

**Comment by matiasilva** [comment]
I'm not sure what the FreeSWITCH configs are for this but in any case I have not been able to experience any jittering or shattering during any of my calls. Closed for now but feel free to follow up.
