### ISSUE TITLE
Can't Visualize PDF or PPT

### ISSUE THREAD

**Issue by UnderFenex** [bigbluebutton/bigbluebutton#8915]
**Describe the bug**
Can't visualize pdf or ppt, whether they area already on the server or uploaded

**To Reproduce**
![image](https://user-images.githubusercontent.com/3832413/77847993-dd440400-7186-11ea-9f4b-18ab7c389c4d.png)

**Expected behavior**
Should see the PDF o PPT

**Actual behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 16.04
 - Browser Chrome, Opera

**Comment by MarkusH-BT** [comment]
I see the same problem. A screenshot would exactly look like the one in the previous message.

Starting with a new and naked Ubuntu 16.04.6 LTS (installed today, just with openSSH server and latest updates), I installed the latest BBB 2.2.3 with demos and latest Greenlight 2.5.2 with the script bbb-install.sh (parameter -s <aliasname.mydomain.de> -a -g).

Also when I upload another pdf or pptx file, I don't see any slide on the screen. 

On the filesystem, the svg files do exist (e.g. /var/bigbluebutton/954f53fa21a9695edeeff44d4dc0002fd39d0e14-1585476002941/954f53fa21a9695edeeff44d4dc0002fd39d0e14-1585476002941/d2d9a672040fbde2a47a10bf6c37b6a4b5ae187f-1585476004636/svgs/slide1.svg, etc.) but they are not displayed on the screen.

Thanks a lot for any help.

**Comment by iSamof** [comment]
We have the same problem on R2.2.2

**Comment by matiasilva** [comment]
Please update to the latest version and open a new issue if this persists. I'm assuming it has been solved over 2 months of inactivity.
