### ISSUE TITLE
Documentation for appLogLevel

### ISSUE THREAD

**Issue by lonesomewalker** [bigbluebutton/bigbluebutton#8916]
**Is your feature request related to a problem? Please describe.**
It would be nice, if there is a short documentation for appLogLevel

**Describe the solution you'd like**
appLogLevel=DEBUG # INFO,ERROR,DEBUG,OFF

**Comment by matiasilva** [comment]
Hi @lonesomewalker. Could you either go more in depth as to where you would like to see this change or submit a pull request?

**Comment by lonesomewalker** [comment]
As i wrote:
it would be a good idea to see all the available options.

Like Apache does:
```
# ServerTokens
# This directive configures what you return as the Server HTTP response
# Header. The default is 'Full' which sends information about the OS-Type
# and compiled in modules.
# Set to one of:  Full | OS | Minimal | Minor | Major | Prod
# where Full conveys the most information, and Prod the least.
#ServerTokens Minimal
ServerTokens Prod
```

To submit a pull request, it would be neccessary to know all options :-)
(and i am not sure if i know them all...)

**Comment by matiasilva** [comment]
What file is this?

**Comment by gerlos** [comment]
> What file is this?

It's in /usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties

**Comment by klepptor** [comment]
I just encountered the same problem, no documentation about the different log levels.

I would like to configure my BBB for privacy as described [here](https://docs.bigbluebutton.org/admin/privacy.html), but...

**Comment by lonesomewalker** [comment]
Maybe it is:
CRIT, ERROR, WARN, INFO, DEBUG

But who knows...
For GDPR you should set it to ERROR

**Comment by hostbbb** [comment]
https://docs.bigbluebutton.org/admin/privacy.html#bigbluebutton-logging

 

bbb is using bunch of open source module.. this part provides you with locations of most of the configs for logs files.

 

Do you want to turn all the logs off for privacy?

 

Others on the forum have done some good work around GDPR compliance and may have some other documentation that can be added.

Or even better apply-config rules to automate configuration of a standard build.

 

Regards,

Stephen

**Comment by lonesomewalker** [comment]
Please Stephen, edit your post.
This is somewhat unprofessional (as your customer support).

**Comment by hostbbb** [comment]
@lonesomewalker not sure what you mean...

**Comment by lonesomewalker** [comment]
> @lonesomewalker not sure what you mean...

Totally off topic:
I didn't want to write that in public, but you should respond to emails, especially from "not your customers anymore because the service was not that good" from Belgium...
This is somewhat embarrassing for BigBlueButton, because more and more people associate a "not that good working" BBB server with BBB instead of the company which runs this.

**Comment by lonesomewalker** [comment]
bump
