### ISSUE TITLE
Change or Mute Noisegate Parameters

### ISSUE THREAD

**Issue by hybridpicker** [bigbluebutton/bigbluebutton#8919]
For teaching music-lessons it would be really a great feature to have settings included, where the moderators can handle the noise-gate/compression for others in the video-conference. Otherwise, it is really hard to hear silent parts on an instrument while giving a music-lesson. You're hearing the instrument playing and then getting muted by BBB. So if the moderator could disable that muting-function it would really solve a huge problem for music-teachers around the world.
Till now, I don't see any tool where this is possible - so it would be a unique feature.

**Comment by cortot** [comment]
Same problem here. There are many important details in teaching piano lessons, which would benefit from this feature.

**Comment by Lenny-git** [comment]
I didn´t solve the problem, but i have a solution. I created a Soundfile with an 18Khz tone. Nearly nobody can hear this but the noisegate didn´t close. So the Sound doesn´t fail.

**Comment by cgruber-uos** [comment]
Is this issue done with the introduction of "disable Filters"? via https://github.com/bigbluebutton/bigbluebutton/blob/080fd3e86d7c30b18bee42870f97a3131f1777c5/bigbluebutton-html5/imports/ui/components/settings/submenus/application/component.jsx#L202-L206 in our case

`noiseSuppression` enabled or disabled or do we have any other functionality 

I have seen still some "muted" parts in my test on https://www.youtube.com/watch?v=5z_svWHS6f8 but not sure if it is a filter issue or a test issue (recording from YT, saving for YT, nor a real BBB setting), see also https://github.com/bigbluebutton/bigbluebutton/issues/16386
