### ISSUE TITLE
echo issue on some participent

### ISSUE THREAD

**Issue by tehseensagar** [bigbluebutton/bigbluebutton#8920]
Dear Community,

Some of my participant having sound echo issue is there any option to look into it to resolve this problem on those users, and I also put my server on internet and having 200Mbps up/down . Yet it does not use full bandwidth why? I'm continue monitoring my wan traffic , do I need to make any changes to use full maximum traffic .  

Regards

**Comment by matiasilva** [comment]
No follow up in two months. Closing for now but feel free to follow up at https://groups.google.com/forum/#!forum/bigbluebutton-users.
