### ISSUE TITLE
After everything is installed, I restart the server and it no longer works.

### ISSUE THREAD

**Issue by jmpdsevilla** [bigbluebutton/bigbluebutton#8925]
Hi there,

I install with
wget -qO- https://ubuntu.bigbluebutton.org/bbb-install.sh | bash -s - -v xenial-220 -s videocom.online -e jmpdsevilla@gmail.com -g

When it finishes it has no problems and works perfectly.

If I restart the server it gives me an error:
**404 Not Found
nginx / 1.10.3 (Ubuntu)**

I check everything and it seems to be fine.

I have done the same procedure several times and the same thing always happens.

If I access bbb, that is to say to some room with (the link that I have from before the restart that) if it worked I can enter and everything works well, the problem is in the front-end

Excuse my English and thanks for the help you can give me

**root@ns521527:~# sudo bbb-conf --status**
nginx —————————————————► [✔ - active]
freeswitch ————————————► [✔ - active]
redis-server ——————————► [✔ - active]
bbb-apps-akka —————————► [✔ - active]
bbb-transcode-akka ————► [✔ - active]
bbb-fsesl-akka ————————► [✔ - active]
red5 ——————————————————► [✔ - active]
mongod ————————————————► [✔ - active]
bbb-html5 —————————————► [✔ - active]
bbb-webrtc-sfu ————————► [✔ - active]
kurento-media-server ——► [✔ - active]
etherpad ——————————————► [✔ - active]
bbb-web ———————————————► [✔ - active]

**root@ns521527:~# bbb-conf  --check**

BigBlueButton Server 2.2.3 (1833)
                    Kernel version: 4.19-ovh-xxxx-std-ipv6-64
                      Distribution: Ubuntu 16.04.6 LTS (64-bit)
                            Memory: 32865 MB
                         CPU cores: 8

/usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties (bbb-web)
       bigbluebutton.web.serverURL: https://videocom.online
                defaultGuestPolicy: ALWAYS_ACCEPT
                 svgImagesRequired: true

/etc/nginx/sites-available/bigbluebutton (nginx)
                       server name: videocom.online
                              port: 80, [::]:80
                              port: 443 ssl
                    bbb-client dir: /var/www/bigbluebutton

/var/www/bigbluebutton/client/conf/config.xml (bbb-client)
                Port test (tunnel): rtmp://videocom.online
                              red5: videocom.online
    <logging enabled="true" logTarget="trace" level="info" format="{dateUTC} {timeUTC} :: {name} :: [{logLevel}] {message}" uri="https:
videocom.online
videocom.online
videocom.online
videocom.online
videocom.online
videocom.online
videocom.online
videocom.online
videocom.online
videocom.online
videocom.online
videocom.online
              useWebrtcIfAvailable: true

/opt/freeswitch/etc/freeswitch/vars.xml (FreeSWITCH)
                       local_ip_v4: 158.69.120.241
                   external_rtp_ip: stun:stun.freeswitch.org
                   external_sip_ip: stun:stun.freeswitch.org

/opt/freeswitch/etc/freeswitch/sip_profiles/external.xml (FreeSWITCH)
                        ext-rtp-ip: $${local_ip_v4}
                        ext-sip-ip: $${local_ip_v4}
                        ws-binding: :5066
                       wss-binding: 158.69.120.241:7443

/usr/local/bigbluebutton/core/scripts/bigbluebutton.yml (record and playback)
                     playback_host: videocom.online
                 playback_protocol: https
                            ffmpeg: 4.2.2-1bbb1~ubuntu16.04

/etc/bigbluebutton/nginx/sip.nginx (sip.nginx)
                        proxy_pass: 158.69.120.241

/usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml (Kurento SFU)
                        kurento.ip: 158.69.120.241
                       kurento.url: ws://127.0.0.1:8888/kurento
                    localIpAddress: 158.69.120.241
               recordScreenSharing: true
                     recordWebcams: true
                  codec_video_main: VP8
               codec_video_content: VP8

/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml (HTML5 client)
                             build: 870
                        kurentoUrl: wss://videocom.online/bbb-webrtc-sfu
                  enableListenOnly: true

# Potential problems described below
# Not running:  tomcat7 or grails LibreOffice
................................................................................
# Error: Could not connect to the configured hostname/IP address
#
#    https://videocom.online/
#
# If your BigBlueButton server is behind a firewall, see FAQ.

**Comment by ffdixon** [comment]
How are you accessing BigBlueButton?

**Comment by jmpdsevilla** [comment]
**Work done step by step**

Served clean
New installation from 0

--------------------------------------

sudo apt-get update
sudo apt-get dist-upgrade

sudo reboot

wget -qO- https://ubuntu.bigbluebutton.org/bbb-install.sh | bash -s -- -v xenial-220 -s videocom.online -e jmpdsevilla@gmail.com -g


root@ns521527:~# bbb-conf --check

BigBlueButton Server 2.2.3 (1833)
                    Kernel version: 4.19-ovh-xxxx-std-ipv6-64
                      Distribution: Ubuntu 16.04.6 LTS (64-bit)
                            Memory: 32865 MB
                         CPU cores: 8

/usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties (bbb-web)
       bigbluebutton.web.serverURL: https://videocom.online
                defaultGuestPolicy: ALWAYS_ACCEPT
                 svgImagesRequired: true

/etc/nginx/sites-available/bigbluebutton (nginx)
                       server name: videocom.online
                              port: 80, [::]:80
                              port: 443 ssl
                    bbb-client dir: /var/www/bigbluebutton

/var/www/bigbluebutton/client/conf/config.xml (bbb-client)
                Port test (tunnel): rtmp://videocom.online
                              red5: videocom.online
    <logging enabled="true" logTarget="trace" level="info" format="{dateUTC} {timeUTC} :: {name} :: [{logLevel}] {message}" uri="https:
videocom.online
videocom.online
videocom.online
videocom.online
videocom.online
videocom.online
videocom.online
videocom.online
videocom.online
videocom.online
videocom.online
videocom.online
              useWebrtcIfAvailable: true

/opt/freeswitch/etc/freeswitch/vars.xml (FreeSWITCH)
                       local_ip_v4: 158.69.120.241
                   external_rtp_ip: stun:stun.freeswitch.org
                   external_sip_ip: stun:stun.freeswitch.org

/opt/freeswitch/etc/freeswitch/sip_profiles/external.xml (FreeSWITCH)
                        ext-rtp-ip: $${local_ip_v4}
                        ext-sip-ip: $${local_ip_v4}
                        ws-binding: :5066
                       wss-binding: 158.69.120.241:7443

/usr/local/bigbluebutton/core/scripts/bigbluebutton.yml (record and playback)
                     playback_host: videocom.online
                 playback_protocol: https
                            ffmpeg: 4.2.2-1bbb1~ubuntu16.04

/etc/bigbluebutton/nginx/sip.nginx (sip.nginx)
                        proxy_pass: 158.69.120.241

/usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml (Kurento SFU)
                        kurento.ip: 158.69.120.241
                       kurento.url: ws://127.0.0.1:8888/kurento
                    localIpAddress: 158.69.120.241
               recordScreenSharing: true
                     recordWebcams: true
                  codec_video_main: VP8
               codec_video_content: VP8

/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml (HTML5 client)
                             build: 870
                        kurentoUrl: wss://videocom.online/bbb-webrtc-sfu
                  enableListenOnly: true


# Potential problems described below

root@ns521527:~#


root@ns521527:~# sudo bbb-conf --status
nginx —————————————————► [✔ - active]
freeswitch ————————————► [✔ - active]
redis-server ——————————► [✔ - active]
bbb-apps-akka —————————► [✔ - active]
bbb-transcode-akka ————► [✔ - active]
bbb-fsesl-akka ————————► [✔ - active]
red5 ——————————————————► [✔ - active]
mongod ————————————————► [✔ - active]
bbb-html5 —————————————► [✔ - active]
bbb-webrtc-sfu ————————► [✔ - active]
kurento-media-server ——► [✔ - active]
etherpad ——————————————► [✔ - active]
bbb-web ———————————————► [✔ - active]

I access from
https://videocom.online/b

**All perfect
Works without errors**

Registration account:
Pruebas
jmpdsevilla@gmail.com
BigBlueButton2020

Correct oil
Works without errors

Link to the room:
https://videocom.online/b/pru-qge-azu

access from another PC
Works without errors

-------------------------------------
**Reboot Server**
-------------------------------------

I access again from
https://videocom.online/b

**404 Not Found
nginx/1.10.3 (Ubuntu)**

root@ns521527:~# bbb-conf --check

BigBlueButton Server 2.2.3 (1833)
                    Kernel version: 4.19-ovh-xxxx-std-ipv6-64
                      Distribution: Ubuntu 16.04.6 LTS (64-bit)
                            Memory: 32865 MB
                         CPU cores: 8

/usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties (bbb-web)
       bigbluebutton.web.serverURL: https://videocom.online
                defaultGuestPolicy: ALWAYS_ACCEPT
                 svgImagesRequired: true

/etc/nginx/sites-available/bigbluebutton (nginx)
                       server name: videocom.online
                              port: 80, [::]:80
                              port: 443 ssl
                    bbb-client dir: /var/www/bigbluebutton

/var/www/bigbluebutton/client/conf/config.xml (bbb-client)
                Port test (tunnel): rtmp://videocom.online
                              red5: videocom.online
    <logging enabled="true" logTarget="trace" level="info" format="{dateUTC} {timeUTC} :: {name} :: [{logLevel}] {message}" uri="https:
videocom.online
videocom.online
videocom.online
videocom.online
videocom.online
videocom.online
videocom.online
videocom.online
videocom.online
videocom.online
videocom.online
videocom.online
              useWebrtcIfAvailable: true

/opt/freeswitch/etc/freeswitch/vars.xml (FreeSWITCH)
                       local_ip_v4: 158.69.120.241
                   external_rtp_ip: stun:stun.freeswitch.org
                   external_sip_ip: stun:stun.freeswitch.org

/opt/freeswitch/etc/freeswitch/sip_profiles/external.xml (FreeSWITCH)
                        ext-rtp-ip: $${local_ip_v4}
                        ext-sip-ip: $${local_ip_v4}
                        ws-binding: :5066
                       wss-binding: 158.69.120.241:7443

/usr/local/bigbluebutton/core/scripts/bigbluebutton.yml (record and playback)
                     playback_host: videocom.online
                 playback_protocol: https
                            ffmpeg: 4.2.2-1bbb1~ubuntu16.04

/etc/bigbluebutton/nginx/sip.nginx (sip.nginx)
                        proxy_pass: 158.69.120.241

/usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml (Kurento SFU)
                        kurento.ip: 158.69.120.241
                       kurento.url: ws://127.0.0.1:8888/kurento
                    localIpAddress: 158.69.120.241
               recordScreenSharing: true
                     recordWebcams: true
                  codec_video_main: VP8
               codec_video_content: VP8

/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml (HTML5 client)
                             build: 870
                        kurentoUrl: wss://videocom.online/bbb-webrtc-sfu
                  enableListenOnly: true


# Potential problems described below
# Not running:  tomcat7 or grails LibreOffice
................................................................................
# Error: Could not connect to the configured hostname/IP address
#
#    https://videocom.online/
#
# If your BigBlueButton server is behind a firewall, see FAQ.

root@ns521527:~#


root@ns521527:~# ^C
root@ns521527:~# bbb-conf --status
nginx —————————————————► [✔ - active]
freeswitch ————————————► [✔ - active]
redis-server ——————————► [✔ - active]
bbb-apps-akka —————————► [✔ - active]
bbb-transcode-akka ————► [✔ - active]
bbb-fsesl-akka ————————► [✔ - active]
red5 ——————————————————► [✔ - active]
mongod ————————————————► [✔ - active]
bbb-html5 —————————————► [✔ - active]
bbb-webrtc-sfu ————————► [✔ - active]
kurento-media-server ——► [✔ - active]
etherpad ——————————————► [✔ - active]
bbb-web ———————————————► [✔ - active]
root@ns521527:~#

This happens without having done anything, just restart the server

I also cannot access the room "https://videocom.online/b/pru-qge-azu"r

SERVER PARAMETERS:

- IP address: 158.69.120.241
- Server name: ns521527.ip-158-69-120.net
   The following administrator account has been configured on the server:
- Username: root
- Password: BigBlueButton2020


I have done this process several times yesterday and the same thing always happens.
Now I will do nothing to follow your help instructions with the current installation.
Thanks a lot

**Comment by eiscan** [comment]
Hi,
I have the same error.

**Comment by StuartBall-Scouts** [comment]
I have had the same issue. I know the server is working because my WOrdpress integration is working, but once I have rebooted from the first installation (on Azure VM) then Greenlight stops working.

I have tried reinstalling Greenlight, no joy.

It is upset about public and private IPs not matching. Is this the same issue as above? or a new one?

**Comment by jmpdsevilla** [comment]
> I have had the same issue. I know the server is working because my WOrdpress integration is working, but once I have rebooted from the first installation (on Azure VM) then Greenlight stops working.
> 
> I have tried reinstalling Greenlight, no joy.
> 
> It is upset about public and private IPs not matching. Is this the same issue as above? or a new one?

I have re-registered from 0 to 4 times and the same thing always happens, before restarting everything is fine and after the first restart it no longer works.

In this last installation, the BBB server does not work but in previous ones the same thing happened to me, from Wordpress if it worked for me but greenlihgt did not, it also reinstalled it and it still did not work.

All this without doing anything, just finishing installing and rebooting no longer works, and apparently nothing changes but gives problems with the IP.

I have spent 2 days looking for the fault but I have not succeeded, to see if anyone can help with this. Thank you

**Comment by server142** [comment]
i got 2 weeks trying of resolve the same problem,  without results..., this is the error log on nginx 

![image](https://user-images.githubusercontent.com/160101/78070934-d7eae300-7359-11ea-94e3-85ef29eb5b06.png)
 Help please!  is there solution?

**Comment by server142** [comment]
this solution works for me... thank you!
https://github.com/bigbluebutton/bigbluebutton/issues/8828

**Comment by jmpdsevilla** [comment]
I have applied the solution found by server142 [#8828](https://github.com/bigbluebutton/bigbluebutton/issues/8828)  and it works again but every time the server is restarted it gives the same problem and it has to be done again.

Does anyone know of a way to automate this or what is the definitive solution?

In production if for any reason the server is restarted it would be without service

**Comment by StuartBall-Scouts** [comment]
OK #8828 works as a fix, but like others every restart means I have to go in and redo.

We're using Azure and don't need the VM all the time costing credits, so we're scheduling shutdowns and restarts daily to keep costs down (we only need it in the evenings).

**Comment by DA-Michael** [comment]
@jmpdsevilla, are you using postgres as your database for greenlight? If so, can you check your docker-compose.yml file and ensure that the restart type for the postgres container is set to `unless-stopped`? It used to be set to only restart on errors, and got changed recently to be `unless-stopped` to resolve the reboot issue, if I remember correctly.
You can check to see if both containers are running after a reboot by running `docker ps`, and you should see 2 containers. If you only see one, check that restart line

**Comment by StuartBall-Scouts** [comment]
> 
> 
> @jmpdsevilla, are you using postgres as your database for greenlight? If so, can you check your docker-compose.yml file and ensure that the restart type for the postgres container is set to `unless-stopped`? It used to be set to only restart on errors, and got changed recently to be `unless-stopped` to resolve the reboot issue, if I remember correctly.
> You can check to see if both containers are running after a reboot by running `docker ps`, and you should see 2 containers. If you only see one, check that restart line

Thanks for that, it worked.

**Comment by jmpdsevilla** [comment]
I have checked and it seems to be ok but when I reboot there is only one container and I continue with the same problem, I have to do:

cd greenlight
docker-compose up -d
bbb-conf --restart

---------------------------------
After reboot

root@ns521527:~# docker ps
CONTAINER ID        IMAGE                     COMMAND             CREATED             STATUS              PORTS                    NAMES
5fe0c5b4679d        migreenlight:release-v2   "bin/start"         7 minutes ago       Up About a minute   127.0.0.1:5000->80/tcp   greenlight-v2
root@ns521527:~#

my docker-compose.yml file

version: '3'

services:
  app:
    entrypoint: [bin/start]
    image: migreenlight:release-v2
    container_name: greenlight-v2
    env_file: .env
    restart: unless-stopped
    ports:
      - 127.0.0.1:5000:80
# When using external logging
#    logging:
#      driver: $LOG_DRIVER
#      options:
#        syslog-address: $LOG_ADDRESS
#        tag: $LOG_TAG
    volumes:
      - ./log:/usr/src/app/log
# When using sqlite3 as the database
#      - ./db/production:/usr/src/app/db/production
# When using postgresql as the database
    links:
      - db
  db:
    image: postgres:9.5
    restart: on-failure
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - ./db/production:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password

**Comment by DA-Michael** [comment]
@jmpdsevilla , in the block at the bottom of the docker-compose.yml file:
`db:`
`image: postgres:9.5`
`restart: on-failure`
`ports:`
`- 127.0.0.1:5432:5432`
`volumes:`
`- ./db/production:/var/lib/postgresql/data`

Can you change `restart: on-failure` to `restart: unless-stopped`?
There are 2 places in the docker-compose file where that line will be, and you want both of them (One for each container) to be `unless-stopped`

That should fix your issue.

Also, as an fyi, you don't need to run `bbb-conf --restart` when you restart Greenlight with `docker compose up -d`, it does take a minute or 2 to come back up, but the BBB restart is unnecessary.

**Comment by jmpdsevilla** [comment]
> @jmpdsevilla , en el bloque en la parte inferior del archivo docker-compose.yml:
> `db:`
> `image: postgres:9.5`
> `restart: on-failure`
> `ports:`
> `- 127.0.0.1:5432:5432`
> `volumes:`
> `- ./db/production:/var/lib/postgresql/data`
> 
> ¿Se puede cambiar `restart: on-failure`a `restart: unless-stopped`?
> Hay 2 lugares en el archivo docker-compose donde estará esa línea, y desea que estén ambos (uno para cada contenedor)`unless-stopped`
> 
> Eso debería solucionar tu problema.
> 
> Además, para su información, no es necesario que se ejecute `bbb-conf --restart`cuando reinicia Greenlight `docker compose up -d`, tarda un minuto o 2 en volver a funcionar, pero el reinicio de BBB no es necesario.

Nothing, I have done what you tell me but it still does not work if I restart the server.


root@ns521527:~# docker ps
CONTAINER ID        IMAGE                     COMMAND             CREATED             STATUS              PORTS                    NAMES
6d2c6b0e5b75        migreenlight:release-v2   "bin/start"         2 hours ago         Up 46 seconds       127.0.0.1:5000->80/tcp   greenlight-v2
root@ns521527:~#


version: '3'

services:
  app:
    entrypoint: [bin/start]
    image: migreenlight:release-v2
    container_name: greenlight-v2
    env_file: .env
    restart: unless-stopped
    ports:
      - 127.0.0.1:5000:80
# When using external logging
#    logging:
#      driver: $LOG_DRIVER
#      options:
#        syslog-address: $LOG_ADDRESS
#        tag: $LOG_TAG
    volumes:
      - ./log:/usr/src/app/log
# When using sqlite3 as the database
#      - ./db/production:/usr/src/app/db/production
# When using postgresql as the database
    links:
      - db
  db:
    image: postgres:9.5
    restart: unless-stopped
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - ./db/production:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password

**Comment by DA-Michael** [comment]
ahh, your last post still had on-failure.

After changing the file, you'll need to go back into the greenlight directory and run docker-compose up -d to apply the change. If you made the change and then rebooted, the new docker-compose file won't have taken effect yet. Did you run that to apply the changes already?

**Comment by jmpdsevilla** [comment]
> ahh, tu última publicación aún tuvo fallas.
> 
> Después de cambiar el archivo, deberá volver al directorio de luz verde y ejecutar docker-compose up -d para aplicar el cambio. Si realizó el cambio y luego reinició, el nuevo archivo docker-compose aún no tendrá efecto. ¿Lo ejecutaste para aplicar los cambios ya?

Ahh right, now yes !, I had not done this last thing you tell me.

I am very grateful, really thank you

**Comment by GhaziTriki** [comment]
@jmpdsevilla Is it working now?

**Comment by jmpdsevilla** [comment]
Hello, after doing this last when I restart if the greenlight page opens but when I enter it appears:

Error del servidor
La URL o clave secreta del servidor son inválidos
Asegúrese de que los pasos han sido seguidos correctamente. Saber más

I have to do bbb-conf --restart so that when entering it it goes well.
??

**Comment by DA-Michael** [comment]
@jmpdsevilla I'm assuming that means invalid secret? I usually see that when I first boot up as well, as Greenlight finishes booting before BBB does, and gives that error until BBB is fully up. BBB takes about 1 minute to 1.5 minutes (Never actually timed it, just a guess) to fully startup, so you could try restarting the machine and waiting a couple minutes. I've never needed to restart BBB after restarting Greenlight, so I think you just need to give it a bit more time. 

If that doesn't work, does a `bbb-conf --status` before you restart bbb show any errors?

**Comment by jmpdsevilla** [comment]
> @jmpdsevilla Supongo que eso significa secreto no válido? Por lo general, veo eso cuando inicio por primera vez también, ya que Greenlight termina el inicio antes de BBB, y da ese error hasta que BBB esté completamente activo. El BBB tarda aproximadamente 1 minuto a 1.5 minutos (nunca lo cronometrado, solo una suposición) para iniciarse por completo, por lo que podría intentar reiniciar la máquina y esperar un par de minutos. Nunca he necesitado reiniciar BBB después de reiniciar Greenlight, así que creo que solo necesitas darle un poco más de tiempo.
> 
> Si eso no funciona, ¿ `bbb-conf --status`antes de reiniciar bbb muestra algún error?

I wait for more than 10 minutes and the same error continues

root@ns521527:~# bbb-conf --status
nginx —————————————————► [✔ - active]
freeswitch ————————————► [✔ - active]
redis-server ——————————► [✔ - active]
bbb-apps-akka —————————► [✔ - active]
bbb-transcode-akka ————► [✔ - active]
bbb-fsesl-akka ————————► [✔ - active]
red5 ——————————————————► [✔ - active]
mongod ————————————————► [✔ - active]
bbb-html5 —————————————► [✔ - active]
bbb-webrtc-sfu ————————► [✔ - active]
kurento-media-server ——► [✔ - active]
etherpad ——————————————► [✔ - active]
bbb-web ———————————————► [✔ - active]
root@ns521527:~#

after
I execute:

bbb-conf --restart

And it already works

**Comment by matiasilva** [comment]
Seems to be resolved. In any case for future troubleshooting, see the docs or => https://groups.google.com/forum/#!forum/bigbluebutton-setup
