### ISSUE TITLE
Error ICE 1010

### ISSUE THREAD

**Issue by tehseensagar** [bigbluebutton/bigbluebutton#8928]
Greetings ,

one of my attendee facing a strange issue , when ever he try to join the meeting room he keep getting ICE error 1010 . What it is and how do I fix this issue. 

Regards

**Comment by matiasilva** [comment]
No follow up in two months. See the "troubleshooting" section of the docs. Closing for now but feel free to follow up at https://groups.google.com/forum/#!forum/bigbluebutton-setup.
