### ISSUE TITLE
Follow Presenter or Moderator Feature

### ISSUE THREAD

**Issue by BigApfel** [bigbluebutton/bigbluebutton#8931]
Hello not sure if this was asked already. Is there an option/feature where all guest can be forced to follow the presenter. Lets say if the presenter/moderator opens up the whiteboard that it will do the same for the rest of the viewers. Or if he makes a camera screen of someone bigger it will do so for the rest as well? Thank you

**Comment by iSamof** [comment]
A comprehensive version of your request is already being discussed here:
[https://github.com/bigbluebutton/bigbluebutton/issues/7987](https://github.com/bigbluebutton/bigbluebutton/issues/7987)
