### ISSUE TITLE
Error 1007 

### ISSUE THREAD

**Issue by ShiftyMLG** [bigbluebutton/bigbluebutton#8935]
**Describe the bug**
When I start a meeting and connect the microphone, sometimes I get the error 1007 and sometimes I don't. I have no idea as to what causes this. Anyone an idea?
**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**
No error
**Actual behavior**
Error 1007 and no mic.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser Chrome
 - Version 80.0.3987.132

**Comment by matiasilva** [comment]
Does this issue still persist? This looks like an error specific to your installation as nobody has followed up. If you still encounter this issue, I suggest you post a topic in https://groups.google.com/forum/#!forum/bigbluebutton-users where your question is better handled.
