### ISSUE TITLE
Error 1020

### ISSUE THREAD

**Issue by lonesomewalker** [bigbluebutton/bigbluebutton#8936]
**Describe the bug**
HTML5 clients get randomly error 1020.

**To Reproduce**
unreproducable, but mostly with Safari

**Desktop (please complete the following information):**
 - OS: Mac & iOS 13
 - Browser Safari
 - Version 2.2.2 and 2.2.3

**Additional context**
server has ipv4 and ipv6 connection, and is NOT behind a firewall.
ufw already disabled.
Name resolution works both IPv4 and IPv6.
And due the fact that the SAME browser/client can connect a few seconds later seamlessly...
TURN server is implemented already like in the docs specified.
Port 443 is used, and already tested by:
https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/
and is responding with no error so far.
Setup is done by install script, so manual misconfiguration can be denied.

**Comment by prlanzarin** [comment]
I'll skip the config checks on this one. Please attach the whole bbb-webrtc-sfu (/var/log/bbb-webrtc-sfu/) and kurento (/var/log/kurento-media-server/) logs for a session where the problem was reproduced. Preferably version 2.2.3 logs.

**Comment by prlanzarin** [comment]
Also attach the userId of the failure session, if possible, so I can trim the logs @lonesomewalker.

**Comment by lonesomewalker** [comment]
Will --clean the log before, so we get a nice overview.
But actually have to wait 1-2h...

**Comment by prlanzarin** [comment]
@lonesomewalker nice, no worries. If you're going to --clean, can you please bump bbb-webrtc-sfu' log level to `trace` before the testing session, then? You can change that in /usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml @ `log.level`. Then sudo systemctl restart bbb-webrtc-sfu.

If you do it, don't forget to change it back after the testing session since they're very verbose to be left on trace in prod.

**Comment by lonesomewalker** [comment]
Here we go :-)

[2020-03-31T194520.00000.pid24750.log](https://github.com/bigbluebutton/bigbluebutton/files/4410674/2020-03-31T194520.00000.pid24750.log)
[bbb-webrtc-sfu.log](https://github.com/bigbluebutton/bigbluebutton/files/4410675/bbb-webrtc-sfu.log)

**Comment by prlanzarin** [comment]
@lonesomewalker can you `$ cat /usr/share/bbb-web/WEB-INF/classes/spring/turn-stun-servers.xml` ?
Please redact sensitive info (eg TURN creds, IPs).

**Comment by lonesomewalker** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://www.springframework.org/schema/beans
        http://www.springframework.org/schema/beans/spring-beans-2.5.xsd">

    <bean id="stun0" class="org.bigbluebutton.web.services.turn.StunServer">
        <constructor-arg index="0" value="stun:servername.domain.tld"/>
    </bean>


    <bean id="turn0" class="org.bigbluebutton.web.services.turn.TurnServer">
        <constructor-arg index="0" value="password"/>
        <constructor-arg index="1" value="turns:servername.domain.tld:443?transport=tcp"/>
        <constructor-arg index="2" value="86400"/>
    </bean>
    
    <bean id="turn1" class="org.bigbluebutton.web.services.turn.TurnServer">
        <constructor-arg index="0" value="password"/>
        <constructor-arg index="1" value="turn:servername.domain.tld:443?transport=tcp"/>
        <constructor-arg index="2" value="86400"/>
    </bean>

    <bean id="stunTurnService"
            class="org.bigbluebutton.web.services.turn.StunTurnService">
        <property name="stunServers">
            <set>
                <ref bean="stun0"/>
            </set>
        </property>
        <property name="turnServers">
            <set>
                <ref bean="turn0"/>
                <ref bean="turn1"/>
            </set>
        </property>
    </bean>
</beans>

**Comment by lonesomewalker** [comment]
I also tend to say it is the stun/turn server, but the same config works on other servers pretty well :-(

Should i hardcode the ip to kurento config for testing purposes?

**Comment by prlanzarin** [comment]
It's not config neither IP it seems. It's Safari choking on the peer connection setup. If you look at bbb-webrtc-sfu's log, the WS session is open but nothing comes through, which indicates Safari's PC froze.

I've seen it happen before when there's a faulty TURN server: it just freezes on the ICE gathering procedure if it has problem with the STUN or TURN server it was told to use, so it won't go past the initial phase and the negotiation won't advance. Most common cause of that happening was bbb-web distributing one variation of `turn:` with no ;transport=tcp appended. Since the order is random, if that was the first one in the list, it'd choke. 

One thing I'll suggest is you trying two variations of your bbb-web config: comment turn0, restart bbb-web, try to reproduce it. Then comment turn1, uncomment turn0, restart bbb-web, try reproduce it.

If that ^ doesn't work, any chance you can hook that iOS in a desktop Safari to look at the console logs and see if there's any complaints there?

**Comment by lonesomewalker** [comment]
Okay, after changing the server from Debian 10 to Ubuntu everything works as expected.
Strange, but solves this issue so far.

Thank you for your effort!

**Comment by zner0L** [comment]
I have the exact same problem, but I already use Ubuntu for the turn server. For me the connection always seems to fail. I have the same config and I can confirm that in the logs, nothing is passing through the webRTC connection. I tried commenting out the servers with errors in both tests.

My Safari on iOS logs:

```
[Log] [11:51:14:0442]  INFO: clientLogger: Sharing webcam https://meetings.domain.de/html5client/e438134a1dbc31c93d665b22433904df4108a414.js?meteor_js_resource=true:121:352169 (e438134a1dbc31c93d665b22433904df4108a414.js, line 9)
[Log] [11:51:14:0805]  INFO: clientLogger: Camera has a new reconnect timer of 15000 ms for w_imqzvnhafwbs https://meetings.domain.de/html5client/e438134a1dbc31c93d665b22433904df4108a414.js?meteor_js_resource=true:121:345346 (e438134a1dbc31c93d665b22433904df4108a414.js, line 9)
[Log] [11:51:14:0807] DEBUG: clientLogger: video-provider client-side candidate queued for w_imqzvnhafwbs https://meetings.domain.de/html5client/e438134a1dbc31c93d665b22433904df4108a414.js?meteor_js_resource=true:121:345754 (e438134a1dbc31c93d665b22433904df4108a414.js, line 9)
[Log] Mon Apr 27 2020 11:51:19 GMT+0200 (CEST) | sip.transaction.ict | Timer B expired for INVITE client transaction z9hG4bK3393935 (sip.js, line 2900)
[Log] Mon Apr 27 2020 11:51:19 GMT+0200 (CEST) | sip.transaction.ict | Timer M expired for INVITE client transaction z9hG4bK3393935 (sip.js, line 2900)
[Log] [11:51:29:0817] ERROR: clientLogger: Camera SHARER has not succeeded in 15000 for w_imqzvnhafwbs https://meetings.domain.de/html5client/e438134a1dbc31c93d665b22433904df4108a414.js?meteor_js_resource=true:121:344185 (e438134a1dbc31c93d665b22433904df4108a414.js, line 9)
[Log] [11:51:29:0820]  INFO: clientLogger: Sending unshare webcam notification to meteor https://meetings.domain.de/html5client/e438134a1dbc31c93d665b22433904df4108a414.js?meteor_js_resource=true:121:352315 (e438134a1dbc31c93d665b22433904df4108a414.js, line 9)
[Log] [11:51:29:0823]  INFO: clientLogger: Sending stop request to SFU. Camera: w_imqzvnhafwbs, role share and flag restarting false https://meetings.domain.de/html5client/e438134a1dbc31c93d665b22433904df4108a414.js?meteor_js_resource=true:121:341569 (e438134a1dbc31c93d665b22433904df4108a414.js, line 9)
[Log] [11:51:29:0825]  INFO: clientLogger: Disposing WebRTC peer w_imqzvnhafwbs https://meetings.domain.de/html5client/e438134a1dbc31c93d665b22433904df4108a414.js?meteor_js_resource=true:121:342015 (e438134a1dbc31c93d665b22433904df4108a414.js, line 9)
```

**Comment by marove2000** [comment]
I had the same Problem. Following the hint from @prlanzarin and deactivating the "turns" configuration, it works perfectly fine! My configuration right now:

    <bean id="turn1" class="org.bigbluebutton.web.services.turn.TurnServer">
        <constructor-arg index="0" value="[secret]"/>
        <constructor-arg index="1" value="turn:[turn-url]:443?transport=tcp"/>
        <constructor-arg index="2" value="86400"/>
    </bean>

Regards

**Comment by gilles5588** [comment]
Bonjour,
please, may you tell me where this file is located ?
Thank you

**Comment by gilles5588** [comment]
is it /usr/share/bbb-web/WEB-INF/classes/spring/turn-stun-servers.xml ?
because I also have a copy of this file in the parent directory.

**Comment by gilles5588** [comment]
Hi again.
I never activated turn, and bbb was running properly before the summer vacations but now, I face the same issue (timeout for the microphone echo test).

**Comment by matiasilva** [comment]
Please don't keep reviving this old issue. Follow the instructions on https://docs.bigbluebutton.org/2.2/getting-help.html for getting help.
