### ISSUE TITLE
Can't disable/lock private chat 

### ISSUE THREAD

**Issue by lalyos** [bigbluebutton/bigbluebutton#8938]
**Describe the bug**

Moderator is trying to lock private chat, But participants are still able to start a chat.

**To Reproduce**
1. Go to a live room as Moderator
2. Click on the Settings icon
3. Disable private Chat
4. In a Participant browser start a private chat.

**Expected behavior**

Private chat should be disabled. (with a similar red message like the publich chat does)

**Actual behavior**
Participants can freely start new provte chats.

**Screenshots**

I'm trying to lock all chat both public and private:

<img width="552" alt="Screenshot 2020-03-30 at 11 16 08" src="https://user-images.githubusercontent.com/464122/78030416-58154680-7362-11ea-8632-ec383e43bfd5.png">

Public chat is lockable:
<img width="341" alt="Screenshot 2020-03-31 at 15 16 20" src="https://user-images.githubusercontent.com/464122/78030582-9ca0e200-7362-11ea-9f57-fb2b6c06f099.png">

But the private chat is still available:
<img width="320" alt="Screenshot 2020-03-31 at 15 17 03" src="https://user-images.githubusercontent.com/464122/78030680-c35f1880-7362-11ea-8540-c25d6c48c336.png">

I wasn't able to find anything related to chat enable/disable in the code ... 
Maybe its in a different repo?

**BBB version (optional):**

BigBlueButton Server 2.2.0

**Desktop (please complete the following information):**
 - OS:  Mac
 - Browser Chrome
 - Version 80.0.3987.149 (Official Build) (64-bit)

**Comment by capilkey** [comment]
When private chat is locked it's intended that locked viewers can still private chat with moderators. If you join the meeting with two viewers you shouldn't be able to chat between them.

**Comment by lalyos** [comment]
Thanks the explanation. It make sense.
