### ISSUE TITLE
Kurento 300%

### ISSUE THREAD

**Issue by agustinmono** [bigbluebutton/bigbluebutton#8939]
Im having this truble

http://prntscr.com/rqgwzh

And no one can share the webcam, maybe is related to that, i had 80 atendees and then that happend.
Also Ive set the maximum ammount of users per room to 50, but 80 persons where able to enter.
Digitalocean

Standard
Shared CPU
4 vCPUs
8 GB
160 GB
5 TB
$40/mo

**Comment by prlanzarin** [comment]
Output of `sudo bbb-conf --check`, please.

**Comment by agustinmono** [comment]
BigBlueButton Server 2.2.2 (1781)
                    Kernel version: 4.4.0-174-generic
                      Distribution: Ubuntu 16.04.6 LTS (64-bit)
                            Memory: 8174 MB
                         CPU cores: 4

/usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties (bbb-web)
       bigbluebutton.web.serverURL: https://elaula.com.ar
                defaultGuestPolicy: ALWAYS_ACCEPT
                 svgImagesRequired: true

/etc/nginx/sites-available/bigbluebutton (nginx)
                       server name: elaula.com.ar
                              port: 8080, [::]:80
                              port: 443 ssl
                    bbb-client dir: /var/www/bigbluebutton

/var/www/bigbluebutton/client/conf/config.xml (bbb-client)
                Port test (tunnel): rtmp://elaula.com.ar
                              red5: elaula.com.ar
              useWebrtcIfAvailable: true

/opt/freeswitch/etc/freeswitch/vars.xml (FreeSWITCH)
                       local_ip_v4: 165.227.93.255
                   external_rtp_ip: stun:stun.freeswitch.org
                   external_sip_ip: stun:stun.freeswitch.org

/opt/freeswitch/etc/freeswitch/sip_profiles/external.xml (FreeSWITCH)
                        ext-rtp-ip: $${local_ip_v4}
                        ext-sip-ip: $${local_ip_v4}
                        ws-binding: :5066
                       wss-binding: 165.227.93.255:7443

/usr/local/bigbluebutton/core/scripts/bigbluebutton.yml (record and playback)
                     playback_host: elaula.com.ar
                 playback_protocol: https
                            ffmpeg: 4.2.2-1bbb1~ubuntu16.04

/etc/bigbluebutton/nginx/sip.nginx (sip.nginx)
                        proxy_pass: 165.227.93.255

/usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml (Kurento SFU)
                        kurento.ip: 165.227.93.255
                       kurento.url: ws://127.0.0.1:8888/kurento
                    localIpAddress: 165.227.93.255
               recordScreenSharing: true
                     recordWebcams: true
                  codec_video_main: VP8
               codec_video_content: VP8

/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml (HTML5 client)
                             build: 862
                        kurentoUrl: wss://elaula.com.ar/bbb-webrtc-sfu
                  enableListenOnly: true


# Potential problems described below

**Comment by prlanzarin** [comment]
Can you please update to 2.2.3 (latest version)? A couple of fixes for Kurento CPU hogs have been included in that release.

**Comment by agustinmono** [comment]
how can I do that update? thanks a lot for the promp response

**Comment by prlanzarin** [comment]
You can use [bbb-install](https://github.com/bigbluebutton/bbb-install).

**Comment by agustinmono** [comment]
If i have installed greenlight do i have to run this command
`wget -qO- https://ubuntu.bigbluebutton.org/bbb-install.sh | bash -s -- -v xenial-220 -s bbb.example.com -e info@example.com -g
`

or  whit this is enough

`wget -qO- https://ubuntu.bigbluebutton.org/bbb-install.sh | bash -s -- -v xenial-220 -a
`

**Comment by capilkey** [comment]
You want to run the same command you used when you installed originally.

**Comment by agustinmono** [comment]
i will at noon, and report how its going, thanks guys!

**Comment by basisbit** [comment]
@agustinmono is the problem still showing up with the bbb 2.2.3? 
Also, when the high kurento CPU usage is happening, is there maybe a meeting happening at that time with lots of participants who have Webcam sharing enabled? What do network traffic stats (for example using "nload") show?

**Comment by agustinmono** [comment]
I cant tell you becouse I didnt stress the server in the same way, the past few meetings were about 50 people, so im still waiting for more people to stress the server. In the other hand I installed Scalelite in a different server, so now I think it will be more balanced the load between many rooms. if happens again ill let you know. 

right now im fighting with the recording not showin up, LOL

**Comment by basisbit** [comment]
if you don't see the record button after starting and joining the meeting, check that `allowStartStopRecording` is set to true in `/usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties`. Anyways, if the high CPU usage only happens when there are lots of people sharing their webcam, well, thats normal. The easiest solution to that are 
- ask moderators to not use webcam sharing too much in big meetings (by the way 30 people sharing 1Mb/s webcam stream to 30 participants already hogs 29*30 = 870Mb/s of outbound network bandwidth of the server)
- reduce maximum allowed webcam recording bandwidth
- limit the max amount of people in a meeting
- add more CPU cores to the machine

**Comment by sbellm** [comment]
Same issue here (BBB Version 2.2.6), only 1 meeting with 2 videos and 2 listeners.  One Client tried to acess video with safari, but failed. Following happened until Room was closed.
200% on 2 Process /usr/bin/kurneto-media-server --gst -debug-level=3 --gst-debug=3, Kurentor*=4,kms*:4KurentoWebSocketTransport:5

**Comment by prlanzarin** [comment]
@sbellm: Kurento logs (/var/log/kurento-media-server/) and bbb-webrtc-sfu logs (/var/log/bbb-webrtc-sfu) that showcase that scenario, please.

**Comment by basisbit** [comment]
@sbellm were you able to resolve your problem in the meantime?
