### ISSUE TITLE
DefaultMaxUsers not working

### ISSUE THREAD

**Issue by agustinmono** [bigbluebutton/bigbluebutton#8940]
I had an issue where the room reachs the maximum users 50 and then no one can enter, even if 10 people leave the meeting, it redirects with no error to the homepage of greenlight

http://prntscr.com/rqjxxo

Thank you

Edit: Its working but its wierd, if i put the maximum participants to 5 for example, this is what happens:

4 people in the room, 5th cant enter, if a person logs out (3 remains in the room) I still cant enter, so what I think what happens is that its not updating when someone logout, also I saw 80 people in the room when the limit was 50, I dont know why

Thanks a lot guys

**Comment by kinimodmeyer** [comment]
it is a problem on "greenlight" that there is no message. i created a but there i guess you can close this here.

https://github.com/bigbluebutton/greenlight/issues/1108

**Comment by agustinmono** [comment]
but when thet leave the room in your case, does it coun as -1 user? 
example, you have a limit of 100 , and the room its full, 4 people left the room, so now we have 96/100 , that means 4 new people will be able to enter the room, right? its working like that or not?

**Comment by mabras** [comment]
Same here. It is just as you described. The difference is If I wait around five minutes, it will allow the users to login in.

**Comment by matiasilva** [comment]
Any updates to this?

**Comment by mabras** [comment]
This issue and https://github.com/bigbluebutton/bigbluebutton/issues/8990 is somehow dup of https://github.com/bigbluebutton/bigbluebutton/issues/8510
Maybe you should close both in favor of 8510.

**Comment by matiasilva** [comment]
Agreed.
