### ISSUE TITLE
Request - Annotation by user

### ISSUE THREAD

**Issue by agustinmono** [bigbluebutton/bigbluebutton#8941]
Be able to select which user can write on the presentation, I was in a room with 100 users and when the moderator enable to share the board its a mess! also it consume A LOT of CPU. So my idea was to be able to select a few to write, it would be a nice improvement.

Nice work guys!

**Comment by matiasilva** [comment]
Closed due to lack of interest for this enhancement. If you wish the start a conversation with other developers, use our dev group: https://groups.google.com/forum/#!forum/bigbluebutton-dev
