### ISSUE TITLE
bigbluebutton cannot run in the webview of android , Who knows how to solve it?

### ISSUE THREAD

**Issue by hhqq5376402** [bigbluebutton/bigbluebutton#8942]
![76b49193e76a4fcdb3519aa1aca1aab4](https://user-images.githubusercontent.com/16266500/78114143-61baaf00-7433-11ea-800d-2902b3f0b1d3.jpg)

**Comment by GremL1N** [comment]
Browser version (WebView) is not in allowed versions.
WebView can webRTC?

**Comment by GhaziTriki** [comment]
@hhqq5376402 This is not an issue. The right place for developers questions is the forums. You might find the following thread interesting https://groups.google.com/forum/#!searchin/bigbluebutton-dev/WebView%7Csort:date/bigbluebutton-dev/o2q6JR00ulI/OtpK-JyaAQAJ
