### ISSUE TITLE
How to start developing for the HTML5 client?

### ISSUE THREAD

**Issue by hippylover** [bigbluebutton/bigbluebutton#8943]
I see in the [https://docs.bigbluebutton.org/html5-overview.html#architecture](https://docs.bigbluebutton.org/html5-overview.html#architecture) page that you use a bunch of technologies:

meteor.js
mongoDB
react.js
webrtc
akka
redis

all of these technologies are new to me, but i can learn. However i am at loss where to begin. What i am trying to do is just to add a dropdown next to the action button that will list pdf's and pictures in 'public/uploaded' and upon clicking a file it should be loaded in "the viewer"(don't know the terminology). That way the teachers don't have to spend time uploading things and can just run the conversion process usually ran after an upload.

If there was a simple guide just to start doing a simple thing like this for new devs it would make my and others life a lot simpler and perhaps youd get more developers :-) !

**Comment by hippylover** [comment]
Well im learning meteor now. Turns out this is a meteor app. and also a react app i guess, but im not quite sure what that means yet. Anyway i didnt set up this server and i can't find where the html5 client is located! Any find or grep command or something i can use?

I see in http://docs.bigbluebutton.org/html5-best-practices.html#project-structure folders like "startup", "imports" etc are supposed to exist but a find looking for them return nothing... yet, the html5client exists on the server, evidenced by the fact i can do servername.com/html5client/check and regular meetings of course, so how to find the code?

**Comment by einhirn** [comment]
I did a "locate html5". After following a few clues that came up with nothing I finally ended up with "less /var/lib/dpkg/info/bbb-html5.list"
Since the HTML5 Client seems to have it's own web server, you probably need restart/reload "bbb-html5" service after changes... Not sure whether there is a standalone github repo for the bbb-html5 client...

**Comment by antobinary** [comment]
This is the HTML5 client code: https://github.com/bigbluebutton/bigbluebutton/tree/v2.2.x-release/bigbluebutton-html5
The best spot to start the journey is currently http://docs.bigbluebutton.org/2.2/dev.html

**Comment by hippylover** [comment]
Seems like the interesting stuff in imports doesn't exist in the package. So i guess i am supposed to develop locally and then create some kind of distro and then install it on the server?

**Comment by GhaziTriki** [comment]
@hippylover It would be more helpful for the community if you the discussion to the right forums https://groups.google.com/forum/#!forum/bigbluebutton-dev. Can you do that please?
