### ISSUE TITLE
Bandwidth control (important for upload)

### ISSUE THREAD

**Issue by guerby** [bigbluebutton/bigbluebutton#8944]
Hi,

While evaluating various tools for audio/video conferencing and testing bigbluebutton one weakness we found is that if the presenter doesn't have a good upload when sharing desktop the audio quality drops a lot for example (and things don't generally work smoothly).

Researching a bit the issue it looks like webRTC has knobs to select bandwidth, we found a great demo website:
https://webrtc.github.io/samples/src/content/peerconnection/bandwidth/

Magic seems to be there:

https://github.com/webrtc/samples/blob/gh-pages/src/content/peerconnection/bandwidth/js/main.js#L225

sdp = sdp.replace(/c=IN (.*)\r\n/, 'c=IN $1\r\nb=' + modifier + ':' + bandwidth + '\r\n');

So feature request would be to add drop down menu for upload and download bandwith in bigbluebutton just like in the web site above. I'm not familiar with bbb code base, looking at "sdp" in the js code on where to hack this to be able to test if it works or not. Do not hesitate to tell me where to look for and I can experiment.

In a perfect world I assume browser should do so by themselves but well ... :)

Thanks for this great free software and keep up the good work!

**Comment by guerby** [comment]
normal case (the sdp.replace is a fallback)
const sender = pc1.getSenders()[0];
    const parameters = sender.getParameters();
 if (bandwidth === 'unlimited') {
      delete parameters.encodings[0].maxBitrate;
    } else {
      parameters.encodings[0].maxBitrate = bandwidth * 1000;
    }
    sender.setParameters(parameters)
        .then(() => {
          bandwidthSelector.disabled = false;
        })

**Comment by prlanzarin** [comment]
We already implement this for cameras. Check HTML5's settings.yml for cameraProfiles, where you can configure profiles and their bitrates. Those profiles appear in a dropdown in the video preview. They're not dynamic, though, since browser's will handle their end at throttling stuff mid call.

We probably can do something similar as far as profiles go for screensharing. You can also control upfront bitrate ceiling for screensharing in /usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml, tias_content and as_content fields.

**Comment by guerby** [comment]
> We already implement this for cameras. Check HTML5's settings.yml for cameraProfiles, where you can configure profiles and their bitrates. Those profiles appear in a dropdown in the video preview. They're not dynamic, though, since browser's will handle their end at throttling stuff mid call.

Ok found them:

https://docs.bigbluebutton.org/2.2/customize.html#reduce-bandwidth-from-webcams

/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml


> We probably can do something similar as far as profiles go for screensharing. You can also control upfront bitrate ceiling for screensharing in /usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml, tias_content and as_content fields.

First test in lab : looks like the bitrate settings work if I put 300 kbit/s with audio it gets to 400 kbit/s which is fine. Will report real world test ASAP.

Default camera settings are conservative at 100/200/500/800 while screensharing is by default at a much higher 1500000, may be settting it more conservatively would prevent user to experience poor audio when sharing their desktop (DSL with < 1 Mbit/s is still very common, same for 3G/4G). Or setting screen sharing bandwidth to the same value as webcam choice?

Still it would be great to be able to set screen sharing bandwidth interactively like camera.

Thanks again for your very quick response and for bbb!

**Comment by prlanzarin** [comment]
I'd say that 1.5mbps max is already a bit conservative since 1080p displays are widespread these days. I wouldn't go much lower than 1mbps or 800kbps (bare minimum). You can try those values as they should stress network a bit less, but going lower than that will probably make screensharing a garbled mess (unless you share a smaller application window).

Also note that the screenshare configs are server wide.

**Comment by guerby** [comment]
We just did a test 

> I'd say that 1.5mbps max is already a bit conservative since 1080p displays are widespread these days. I wouldn't go much lower than 1mbps or 800kbps (bare minimum). You can try those values as they should stress network a bit less, but going lower than that will probably make screensharing a garbled mess (unless you share a smaller application window).
> 
> Also note that the screenshare configs are server wide.

We just did a test with a real life connections where we had audio issue before and it worked perfectly. Just a bit of bad audio when resizing the shared window or large window content change but that's it.

The quality is surprisingly good with the setting at 250 kbps : sharing a full HD terminal and a few other high screen density apps we tested were readable / good enough even if not pixel perfect.  

We even shared a browser tab playing a youtube video to stress test the setting and it was not that bad (of course it's better to use the integrated feature for that in real life :).

The issue we're facing is that when we propose a new tool to our users they test it and if at least audio doesn't work they don't want to use the tool anymore and end up with Zoom which does manage quite well low bandwidth ... Leaving the bbb default setting a 1.5 Mbps will have this "bad" effect on all ADSL user in the world since ADSL upload  max out at 1 Mbit/s so everyone trying to share a desktop over an ADSL will have the same bad experience of bbb and just stop using it.

Anyway thanks for the help, even if not perfect (and a bit unsatisfying for users with > 1 Mbit/s upload who cannot tune up the quality), it does make bbb competitive with Zoom in our use case IMHO. We'll see if our users overcome their first very bad impression of bbb.

**Comment by prlanzarin** [comment]
Agreed. Best to see which value best suits your users and then adjust it at your will (that's why they're configurable).
You can also change the values for cameras in settings.yml. They can go as low as 30kbps. Feel free to experiment with it as well.

**Comment by bilias** [comment]
> We just did a test with a real life connections where we had audio issue before and it worked perfectly. Just a bit of bad audio when resizing the shared window or large window content change but that's it.
> 
> The quality is surprisingly good with the setting at 250 kbps : sharing a full HD terminal and a few other high screen density apps we tested were readable / good enough even if not pixel perfect.

Hi guerby,

I have the exact same issues. When screen sharing is on the audio is bad on people with DSL connections.

Just to be sure, your change was on 
/usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml
    tias_content: "1500000"
    as_content: "1500"

for H264 and VP8?
What about frames per second?

thanks
ps. How they manage this in zoom? According to https://support.zoom.us/hc/en-us/articles/204003179-System-Requirements-for-Zoom-Rooms
For screen sharing only: 150-300kbps

**Comment by guerby** [comment]
> > We just did a test with a real life connections where we had audio issue before and it worked perfectly. Just a bit of bad audio when resizing the shared window or large window content change but that's it.
> > The quality is surprisingly good with the setting at 250 kbps : sharing a full HD terminal and a few other high screen density apps we tested were readable / good enough even if not pixel perfect.
> 
> Hi guerby,
> 
> I have the exact same issues. When screen sharing is on the audio is bad on people with DSL connections.
> 
> Just to be sure, your change was on
> /usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml
> tias_content: "1500000"
> as_content: "1500"
> 
> for H264 and VP8?

Our settings are described here (text in french but settings in bash / diff :) : 

https://lists.tetaneutral.net/pipermail/technique/2020-April/003855.html

```
CODEC_CONFIG=/usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml
yq w -i $CODEC_CONFIG conference-media-specs.H264.tias_content "250000"
yq w -i $CODEC_CONFIG conference-media-specs.H264.as_content "250"
yq w -i $CODEC_CONFIG conference-media-specs.VP8.tias_content "250000"
yq w -i $CODEC_CONFIG conference-media-specs.VP8.as_content "250"
```

We found out we get readable results with 250 kbit/s for full HD screen sharing, no need to go higher and 250 kbit/s plays fine with even poor ADSL upload.

> What about frames per second?

We just adjusted bandwidth as above.

**Comment by mhier** [comment]
It would also be great if one could control the frame rate separately. Usually it is much more important to have readable text than fast updates. Lowering the frame rate would allow to go further down with the bit rate while having the same image quality (given that usually mostly stills are shown in screen sharing).

**Comment by hex-m** [comment]
There is a section in `/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml` now.

```
    screenshare:
      constraints:
        video:
          frameRate:
            ideal: 5
            max: 10
          width:
            max: 2560
          height:
            max: 1600
```

**Comment by mokazemi** [comment]
There's an property in `/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml` which is 'bitrate'. 

There are also some `tias_content` and `as_content` properties for H264 and VP8 inside `/usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml`, As described in previous comments. 

Should I reduce both these values to optimize screen share for lower bandwidths? Or the first one is enough?
