### ISSUE TITLE
Audio Quality Improvements

### ISSUE THREAD

**Issue by Lukas2000** [bigbluebutton/bigbluebutton#8946]
Is there a way to improve the audio by allocating more bandwidth for it? For many of our sessions the audio cuts in and out. We're using the recommended hardware and the load is no where near capacity (around 30 people). It happens often enough that it can't be blamed on a single person's network or computer. S

**Comment by mtsonline** [comment]
this could help you 
#7007

**Comment by Lukas2000** [comment]
Duplicate of #7007
