### ISSUE TITLE
bbb lti integration with edx doesn't display names properly

### ISSUE THREAD

**Issue by hoang000147** [bigbluebutton/bigbluebutton#8948]
When I join a room (using bbb integrates with edx through lti), everyone's names are Attendee and one is Moderator. How should I fix this?

I know there is a closed topic about this problem and look through that, but nothing is changed for my situation.

Thanks in advance.

**Comment by akinomeroglu** [comment]
Hi,

Did you try the edX share username function? As far as I understand edX doesn’t share username or user detail via LTI and you need to configure it manually

**Comment by hoang000147** [comment]
If you mean "Request user's username" and "Request user's email" features in edX, then yes. But it still doesn't change anything.

**Comment by Nellymandela** [comment]
@hoang000147 how were you able to set this up. I need help link on configuring the LTI Consumer

**Comment by hoang000147** [comment]
@Nellymandela I used this link for configuring LTI Consumer: https://edx.readthedocs.io/projects/edx-partner-course-staff/en/latest/exercises_tools/lti_component.html

**Comment by nikhilkanta** [comment]
@hoang000147 Did you find a fix for this issue. If so, Can you share how you fixed this?

**Comment by hoang000147** [comment]
> 
> 
> @hoang000147 Did you find a fix for this issue. If so, Can you share how you fixed this?

Yes, I have a solution for this issue which is xblock.

**Comment by kerrigan42** [comment]
@hoang000147 Could you describe in more detail how you solved this issue, please?

**Comment by hoang000147** [comment]
> 
> 
> @hoang000147 Could you describe in more detail how you solved this issue, please?

Hi, for using xblock I used this repo (https://github.com/edx/xblock-lti-consumer) and using this docs to enable it: https://edx.readthedocs.io/projects/edx-installing-configuring-and-running/en/latest/configuration/install_xblock.html
