### ISSUE TITLE
No microphone / Error 1007 for Firefox 68 via turn server

### ISSUE THREAD

**Issue by hbruch** [bigbluebutton/bigbluebutton#8955]
**Describe the bug**
Users behind a firewall using FF68 were not able to join with microphone to a bbb instance with separate turn server. Switching to chrome solved this issue.

The docs states as prerequisite for the client "latest" firefox. Is this microphone issue a well known issue and if yes, is the a firefox version from which on it is reportedly working?

**To Reproduce**
1. Connect to session
2 Select Microphone

**Expected behavior**
User can join with microphone

**Actual behavior**
Connect with microphone times out and shows 1007 error

**BBB version (optional):**
BigBlueButton continually evolves. Providing the version/build helps us to pinpoint when an issue was introduced.
Example:
$ sudo bbb-conf --check | grep BigBlueButton
BigBlueButton Server 2.2.3 (1833)

**Desktop (please complete the following information):**
 - Windows10
 - Firefox
 - Version 68.2.0esr 32bit

**Additional context**
Clients are behind a restrictive firewall, turn server is configured and working when chrome is used

**Comment by GhaziTriki** [comment]
@hbruch The 1007 error happens in Firefox when the microphone is being used by another application. Can you please test again?

**Comment by pnijjar** [comment]
Is your BBB server also behind a NAT firewall?

**Comment by hbruch** [comment]
@GhaziTriki Will ask the user to check this, though not sure how he can verify...
@pnijjar No it is not.

With Chrome and turn server, they can connect.

**Comment by matiasilva** [comment]
Closing this issue due to lack of follow up. Please feel free to follow up here or on https://groups.google.com/forum/#!forum/bigbluebutton-setup if you run into further issues.

**Comment by MeinhartEsrohr** [comment]
hey, i have the same problem, do you have a solution ?

**Comment by matiasilva** [comment]
@MeinhartEsrohr please see the last sentence of my comment: 

> "Please feel free to follow up here or on https://groups.google.com/forum/#!forum/bigbluebutton-setup if you run into further issues."
