### ISSUE TITLE
Support more distros like Arch Linux

### ISSUE THREAD

**Issue by KeithCu** [bigbluebutton/bigbluebutton#8956]
I'm doing the manual install. The installation page:
http://docs.bigbluebutton.org/2.2/install.html#minimum-server-requirements

recommends Ubuntu from 2016, and uses Ubuntu specific packages, instead of Debian, which is [the rock that Ubuntu builds on](http://keithcu.com/wordpress/?page_id=558).

It would also be good if there was an install mechanism for other distros like Arch. Arch is an awesome distro for servers because it grabs the latest packages and security fixes within a few days. You don't need custom PPA's for ffmpeg, etc Your install process would be half the size if were ported to Arch (because it already has newest versions of all the packages, including selected old ones like OpenJDK 8). It would also be running a more reliable, secure, feature-rich system compared to Ubuntu from 2016-2018.

People say that Arch is not reliable enough for servers, but that's just saying that the free software community is not releasing reliable code today. Is that really true? Arch has multiple kernels, so it doesn't take your freedom away to run the older ones, or have a backup just in case, but most packages only have one version, the latest. You can always go back if you want. I've done that twice. 

I've been running Arch since 2013, and I can maintain a Debian again if I need to, but the decision to support only 2-4 year old Ubuntus is not great. I read BBB is soon going to Ubuntu 18.04 for the next version which is better but still about 2 years old, and therefore missing 2 years of work in the FOSS community. If I run into a problem, it's almost impossible to get support from a team on old code. Many teams wants bug reports filed only against the newest version.

Arch has the ability to install DEB packages with DebTap, but it should be easy to create zip file or something usable for any distro. It would also be good if there was an AUR package:
https://aur.archlinux.org/

I've read of people wanting BigBlueButton in the AUR since 2011:
https://bbs.archlinux.org/viewtopic.php?id=112024

Here's a set of server-oriented distros you could consider supporting:
https://www.linode.com/distributions/

I know people worry about the increased cost of supporting more distros, but what they don't realize is that, for example, Arch creates better Linux users. They read the wiki, and learn what they are doing. I learned more about Linux, systemd, etc. installing Arch than running Ubuntu for 5 years. Ubuntu historically "created" more helpless users, which makes your support job more difficult, and causes you to get discouraged in supporting any more. That's a vicious cycle.

Adding support for more distros like Arch will not greatly increase your burden. Their questions will be better. They may even send patches, which decreases it. They send patches to every other upstream. Much of this applies to Debian users as well ;-) Thanks for reading this.

**Comment by runout-at** [comment]
+1 for Debian Stable

**Comment by alangecker** [comment]
there are already multiple issues related to supporting more distributions
- Please support current Debian (or help current Debian support BBB) #8861
- How to create BigblueButton Debian Package #3722
- Support of installation on other operating systems? #3416
- Debian packages #2104 
- Please provide debian source packages in your repositories #1200
- Installation on Ubuntu higher than 16.04 #8738
- Support Ubuntu 18.04 in installation of BigBlueButton 2.3 #8474
- Create RPM packages for BigBlueButton #1379

**Comment by KeithCu** [comment]
Thanks for the info. I don't see any bugs about an Arch package, so I changed the title about that.

**Comment by trs80** [comment]
Even Ubuntu you can't recreate the .debs since there's no source packages (#8876) so any change I make has to be manually copied across to the production server after building in a dev environment.
