### ISSUE TITLE
"set status" and other features do nothing on click if camera is enabled and chat is collapsed

### ISSUE THREAD

**Issue by WorldCodeCentral** [bigbluebutton/bigbluebutton#8957]
Hello, love BBB, found a bug and tracked down a minimal way to reproduce it. Here is my report:

**Describe the bug**
"set status" and other features like sending private messages do nothing on click if camera is enabled and chat is collapsed

**To Reproduce**
1. Log in with password admin at the testing domain by distancelearning.
2. When you're in, enable camera.
3. Collapse the chat.
4. Click on yourself to set the status/click on another user to send a private message.
5. The blue-mousehover effect doesn't show up and nothing happens if you click on the option.

**Expected behavior**
Interface should work as intended like when chat is shown.

**Actual behavior**
Nothing happens if menu options are clicked.

**Screenshots**
Not needed and wouldn't help

**BBB version (optional):**
The one that is in use at the testing instance on distancelearning

**Desktop (please complete the following information):**
 - OS: GNU+Linux
 - Browser: Firefox
 - Version 75.0b11

**Smartphone (please complete the following information):**
Did not test with phone

**Additional context**
I will probably install BBB on a Debian Server, because I like it so much.
Thanks a lot for your contributions to freedom respecting software!
(Also a minor nitpick that isn't worth its own issue IMO: Enabling the camera asks me 3 times or more for permission if I don't click "always allow". I could of course click that, but it's a click more and it's nice to get asked everytime so I won't have my camera enabled by accident.)

**Comment by simonschweizer** [comment]
Using BBB 2.2.3 (on our own server) both scenarios are working fine (using the steps in "To reproduce") using the latest version of Chrome on MacOS.

**Comment by WorldCodeCentral** [comment]
I was using Firefox and GNU+Linux.

Can you confirm the problem on the official demo server https://distancelearning.cloud/demo-bigbluebutton-for-yourself/ ? Also do you know whether it's possible to see which version the server runs? I could only get the client info which says "Clientversion: 815".

**Comment by matiasilva** [comment]
Tested on 2.2.17 on the official BigBlueButton demo server. Seems to work fine. Closed for this reason. You can follow up here if this persists.
