### ISSUE TITLE
Lost records after update and Echo test dont appears

### ISSUE THREAD

**Issue by GrosQuicKFR** [bigbluebutton/bigbluebutton#8958]
I'm working on a Virtual Proxmox BigBlueButton Server with Greenlight.
This morning after updating this packages ;  bbb-apps bbb-apps-akka bbb-apps-screenshare bbb-apps-video bbb-config bbb-etherpad bbb-freeswitch-core bbb-fsesl-akka bbb-html5
  bbb-record-core bbb-web bbb-webrtc-sfu , no records were found on the  GreenLight interface. yet they are on the server. Should I do  something ?

Another problem after this update seems to be the echo test which doesn't allow us to either validate or not.

**Comment by basisbit** [comment]
Please use the apply-config.sh script to apply your customization after each bbb update. See https://docs.bigbluebutton.org/2.2/customize.html#automatically-apply-configuration-changes-on-restart
