### ISSUE TITLE
Orphan Room not Closing -- Even with API Mate

### ISSUE THREAD

**Issue by Lukas2000** [bigbluebutton/bigbluebutton#8961]
I have an orphan room that's not closing. I believe the room was incorrectly set to allow anyone to start it and was therefore started by someone who was not logged in. I think also the room was left "improperly" by the user just closing the browser.

It's been about 8 hours since the room was emptied but it's still listed as open with 0 viewers. As a super admin, when I try to join it I get the 3 dots that don't move on the screen and the loading freezes. So I turned to API-MATE and tried to end the meeting from there. Still the meeting does not close.  Here's some more info from API-MATE

```
<meeting>
<meetingName>level 5</meetingName>
<meetingID>b418e60302d9b9a8d02e18643c5b616783dd9544</meetingID>
<internalMeetingID>
ae6befb866168587de62e65a63c0588e1c088019-1585797058247
</internalMeetingID>
<createTime>1585797058247</createTime>
<createDate>Thu Apr 02 03:10:58 UTC 2020</createDate>
<voiceBridge>71580</voiceBridge>
<dialNumber>613-555-1234</dialNumber>
<attendeePW>cXAGHMmVKazG</attendeePW>
<moderatorPW>BaZpuMvRZNQX</moderatorPW>
<running>false</running>
<duration>0</duration>
<hasUserJoined>false</hasUserJoined>
<recording>true</recording>
<hasBeenForciblyEnded>false</hasBeenForciblyEnded>
<startTime>0</startTime>
<endTime>0</endTime>
<participantCount>0</participantCount>
<listenerCount>0</listenerCount>
<voiceParticipantCount>0</voiceParticipantCount>
<videoCount>0</videoCount>
<maxUsers>0</maxUsers>
<moderatorCount>0</moderatorCount>
<attendees> </attendees>
<isBreakout>false</isBreakout>
</meeting>
```

Is there a way to force close this with SSH?

**Comment by matiasilva** [comment]
Closed due to inactivity.
