### ISSUE TITLE
Error: Could not connect to the configured hostname/IP address

### ISSUE THREAD

**Issue by Hredoy** [bigbluebutton/bigbluebutton#8962]
Hello,
I installed bigbluebutton in google cloud . setting-up everything whatever you ware said in docs. but when i changed everything for https i'm getting an issue which is 

#
#    https://34.87.60.178/
#
# If your BigBlueButton server is behind a firewall, see FAQ.

# Warning: The setting of 34.87.60.178 for proxy_pass in
#
#    /etc/bigbluebutton/nginx/sip.nginx
#
# does not match the local IP address (10.148.0.9).
# (This is OK if you've manually changed the values)

# Warning: The API demos are installed and accessible from:
#
#    https://34.87.60.178
#
# and
#
#    https://34.87.60.178/demo/demo1.jsp
#
# These API demos allow anyone to access your server without authentication
# to create/manage meetings and recordings. They are for testing purposes only.
# If you are running a production system, remove them by running:
#
#    apt-get purge bbb-demo

# Error: Unable to reach default URL for presentation:
#
#    https://34.87.60.178/default.pdf
#
# Check value for beans.presentationService.defaultUploadedPresentation in
#   /usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties

how can i solved it please assist me or help me.

Thank You
Hridoy

**Comment by rromandk** [comment]
Hello,  I have exactly the same problem.  
          Did you find a solution ?   Thanks

**Comment by daddycool808** [comment]
Hi All,
for me it's exactly the same - i did my first installation step-by-step, and i experienced the error after changing to SSL. Nginx won't start anymore. Now i did the installation by install-script and it's nearly all the same:
Ubuntu 16.04 LTS  installation was done with a (static) DHCP-Adress: 192.168.0.xx. I am using a Public-IP from NoIP.com and i tried bbb-conf --setip with a name like bbb-demo.ddns.net.
 
The IP-Updater (DUC 4.1.1) tells me it can see my Server from the internet, but i can't login - all i got is a network-timeout when trying to reach the adress bbb-demo.ddns.net

bbb-conf --check tells me all modules are working fine but what i can see from here is that some entrys still points to the public ip and not to bbb-demo.ddns.net.

anybody got an idea?

Thanks in advance

**Comment by basisbit** [comment]
@daddycool808 noip.com only gives you a domainname for your dynamic IP address. For running BigBlueButton, you will need a static IPv4 address.

@Hredoy for your support request, please ask at https://groups.google.com/forum/#!forum/bigbluebutton-setup . This issue tracker here in only for BigBlueButton development related issues, sorry.
