### ISSUE TITLE
Turn server with user and password

### ISSUE THREAD

**Issue by samtux** [bigbluebutton/bigbluebutton#8963]
Hi. I really love this software, it's very simple and has all the facilities for virtual classes. 
For the use of free turn servers (numb.viagenie.ca, webrtc.tools), the services usually provide a username and password, is it possible to configure these parameters in the BBB configuration file?

http://docs.bigbluebutton.org/2.2/setup-turn-server.html#configure-bigbluebutton-to-use-the-coturn-server

I have tried:

turn:user:password@numb.viagenie.ca

But I can't succeed in this configuration.

**Comment by GhaziTriki** [comment]
@samtux The right place to ask for help are the forums. You can find some topic discussing about your issue. You should try installing coturn using bbb-install https://github.com/bigbluebutton/bbb-install#install-a-turn-server
