### ISSUE TITLE
Change "Lock Viewers" menu to "Guest Permissions" or other more descriptive name

### ISSUE THREAD

**Issue by nioroso-x3** [bigbluebutton/bigbluebutton#8966]
I'm getting a lot of presenters asking where to set the camera, microphone, etc permissions for the guests, some are even afraid of clicking this menu because they think it will block everyone.
Can this be fixed? I changed it on my instances to Guest Permissions, now I get a lot less questions.

**Comment by GhaziTriki** [comment]
@nioroso-x3 Guests is another feature in BigBlueButton completely different from the Viewers role.

**Comment by matiasilva** [comment]
Lack of follow up in two months +  response above, closing.
