### ISSUE TITLE
I am getting 404 Not Found nginx/1.10.3 (Ubuntu)

### ISSUE THREAD

**Issue by rfendidjaja** [bigbluebutton/bigbluebutton#8967]
**/var/www/nginx-default/50x.html" failed**
I am getting this messages out of a fresh install on my ubuntu 16.0.4 LTS 64bit.

[error] 1006#1006: *9 open() "/var/www/nginx-default/50x.html" failed (2: No such file or directory), client: 110.138.116.120, server: meet.victorysolusi.com, request: "GET /b HTTP/1.1", upstream: "http://127.0.0.1:5000/b", host: "meet.victorysolusi.com"

I got the same error message on my previous server that was running fine for 2 days after the installation and all of a sudden I got the 404 not found message when I tried to hit the web.

FYI, the demo site is working fine. The landing page seems to be missing. 

My 50x.html file in /var/www/nginx-default/ is not exist for some reason. 

Thanks

**Comment by basisbit** [comment]
1. `cd ~/greenlight`
2. `docker-compose up -d`
3. docker run --rm --env-file .env bigbluebutton/greenlight:v2 bundle exec rake conf:check

For more information about Greenlight, please see https://docs.bigbluebutton.org/greenlight/gl-install.html#5-start-greenlight-20

**Comment by DocEpsilon** [comment]
Hmm, I saw the same error message in my log after bbb suddenly timed out with nginx/404 Except for IP and URL of course.

What worked for me was to do an update of docker:
1. `cd ~/greenlight`
2. `docker pull bigbluebutton/greenlight:v2`
3. `docker-compose down`
4. `sudo docker-compose up -d`
5. `docker run --rm --env-file .env bigbluebutton/greenlight:v2 bundle exec rake conf:check`
6.  failed -> wait
7. `sudo bbb-conf --set-ip`
8.  `docker run --rm --env-file .env bigbluebutton/greenlight:v2 bundle exec rake conf:check`
9.  succeeded -> running
