### ISSUE TITLE
Toast notification overlaps dropdowns on mobile 

### ISSUE THREAD

**Issue by Tainan404** [bigbluebutton/bigbluebutton#8968]
**Describe the bug**
The toast notifications are overlapping the dropdowns on mobile, not allowing user interact with some buttons.

**To Reproduce**
1. Upload a new presentation 
2. Change the presentation
3. see the notification of presentation change
4. Open any dropdown before the notification close
5. See the error

**Expected behavior**
Dropdown overlaps the notifications to have all buttons to interact.

**Actual behavior**
The notification overlaps the dropdowns blocking some buttons.

**Screenshots**
![Peek 2020-04-02 14-02](https://user-images.githubusercontent.com/15806883/78279548-11ecee00-74ee-11ea-93c3-3b712f9bfa1e.gif)

**BBB version (optional): 2.3

**Desktop:**
 - OS: Linux
 - Browser Chrome (dev tools mobile mode)
 - Version 80.0.3987.149

**Smartphone:**
 - Device: Xiaomi redmi note 6 pro
 - OS: android 9
 - Browser Chrome
 - Version 80

**Comment by matiasilva** [comment]
Unsure why this is troubling: close the toast and proceed as usual. Closing for now.
