### ISSUE TITLE
ffmpeg hwaccel flags for vaapi

### ISSUE THREAD

**Issue by wmchris** [bigbluebutton/bigbluebutton#8969]
as far as i can see, the bbb-encoder is using ffmpeg for transcoding purpose. ffmpeg does support hardware acceleration, which can be easily enabled by setting some flags. this could reduce the cpu load a lot for recording postprocessing.

is there a roadmap for enabling hwacceleration in bbb? or is it possible to add custom flags for the ffmpeg transcoder?

**Comment by mvasylenko** [comment]
> or is it possible to add custom flags for the ffmpeg transcoder?

You can edit ffmpeg parameters in
/usr/local/bigbluebutton/core/lib/recordandplayback/generators/video.rb

**Comment by wmchris** [comment]
well, for intel quicksync vp9_vaapi looks like a candidate to do this job. Unless there is another catch i dont realize, yet.

**Comment by basisbit** [comment]
@wmchris got any success/progress regarding ffmpeg using vaapi?

**Comment by wmchris** [comment]
i changed the variables and used a custom build of ffmpeg. seems to work, but never checked if it is really using the hwaccel.

**Comment by basisbit** [comment]
could you maybe provide a small tutorial on how to do this?

**Comment by wmchris** [comment]
not really, compile/download ffmpeg with enabled vaapi, activate the intel driver in ubuntu and set the ffmpeg flags (https://trac.ffmpeg.org/wiki/Hardware/VAAPI).

**Comment by prlanzarin** [comment]
Since it's "configurable" (hence doable, hence not an issue), I'm closing this.

Thanks for sharing your findings.
