### ISSUE TITLE
Android/IOS phone BBB using earpiece instead of speaker

### ISSUE THREAD

**Issue by kevev** [bigbluebutton/bigbluebutton#8971]
Is it possible to have the html5 client on Android/IOS use speakerphone instead of earpiece? Not all users have headphones.

**Comment by kevev** [comment]
I figured out that this issue only happens when using FireFox on Android. Also the screen does not stay awake using FireFox on Android. Is there a way to fix this?

**Comment by secretreal26** [comment]
same here in android/firefox  bur android/chrome can user speakerphone

**Comment by matiasilva** [comment]
This seems like something you need may configure on your end. Closed due to inactivity.

**Comment by cod3r0k** [comment]
Hi, How can we switch during the session in android phone? (earpiece and speaker) ?
