### ISSUE TITLE
favicon loaded over non-HTTPS on demo server

### ISSUE THREAD

**Issue by paulmenzel** [bigbluebutton/bigbluebutton#8974]
Firefox 74.0 shows a certificate error accessing the [demo server](https://demo.bigbluebutton.org/gl) due to the favicon being included by a plain HTTP URL and not HTTPS.

> Loading mixed (insecure) display content “http://demo.bigbluebutton.org/gl/favicon.ico” on a secure page

**Comment by GhaziTriki** [comment]
@paulmenzel Could you please post this into https://github.com/bigbluebutton/greenlight. It looks like an asset policy loading issue.
