### ISSUE TITLE
BigBlue by script does not use coturn or wrong turn credentials?

### ISSUE THREAD

**Issue by butchooka** [bigbluebutton/bigbluebutton#8975]
**Describe the bug**
I configured 2 server this week: 
Bigbluebutton (Ubuntu 16.04) + Turn (18.04) both via installation script following instructions on https://github.com/bigbluebutton/bbb-install. 
Made no changes so far depending this configuration.
Booth work fine for themself, but when turn comes into play it does not take the right credentials comming from BigBlueButton.
Comfirmed that with another install for bigbluebutton

Turn was verified via https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/ (got configured user:password credentials for this) --ok.

Scripts used for install were from https://ubuntu.bigbluebutton.org/:
Big Blue ./bbb-install.sh -v xenial-220 -s 3b.domain.org -e my@email.com -g -c 3bturn.domain.org:SECRETPHRASE
Turn ./bbb-install.sh -e my@email.com -c 3bturn.domain.org:SECRETPHRASE

**To Reproduce**
install servers with scripts
1. To simulate Firewall i denied UDP connections for my Firefox in Windows Firewall, we have a hard firewall at the office and there are also blocks on UDP so a 443 TCP to turn should solve that
2. When starting a audio connection i get a 1007 error 
3. checking F12 developter Tools /Console Filter "turn" shows me strange credentials to my turn server used by sip.js (screenshot) -> connection to turn cannot be established.
Error: ICE failed, your TURN server appears to be broken, see about:webrtc for more details
4. about:webrtc tells me connections were attemped to my 3B server instead of turn ?! and they fail
5. also checking F12 - network analysis and it even ssems not do a connection to mit 3bturn server
What is going wrong here? Is there a way to log/check/test where configuration is not ok?

**Expected behavior**
BigBlueButton fills my choosen secret i provided in the script und can establish a connection, when needed

**Actual behavior**
Turn is not used / cannot be used and so no audio behind firewall

**Screenshots**
F12 Tools:
![image](https://user-images.githubusercontent.com/43138972/78360769-96f00a00-75b7-11ea-8132-eb7cc89e01a5.png)
about.webrtc:
![image](https://user-images.githubusercontent.com/43138972/78361037-02d27280-75b8-11ea-90ea-0bd5df688a5a.png)

**Additional context**

**Comment by butchooka** [comment]
Rechecked: 
CoTurn itself works, it seems install.sh script does tasks mentioned in manual install depending turn installation:
It fills /usr/share/bbb-web/WEB-INF/classes/spring/turn-stun-servers.xml with values that seem correct, too.
But it cannot be utilised when needed with errors posted abouve.

**Comment by butchooka** [comment]
Firefox Version: 74.0.1
Chrome Version: 80.0.3987.163
I've seen https://groups.google.com/forum/m/#!topic/bigbluebutton-setup/8pHzwsrNlB8 who someone also has such a problem, unfortunately i have no system up with older Browser Versions to check if this problem is related to browser version

**Comment by butchooka** [comment]
after some restarts it takes now right "3bturn" server to connect when behind Firewall.
Still shows this weird credentials, but:
checked with Firefox ESR 68.6.1esr and confirm working, seems that some browsers have problems with turn at the moment.

**Comment by butchooka** [comment]
Firefox 74.0.1 Changelog(https://www.mozilla.org/en-US/firefox/74.0/releasenotes/) says following Change, can BBB work with this?
Firefox now provides better privacy for your web voice and video calls through support for mDNS ICE by cloaking your computer’s IP address with a random ID in certain WebRTC scenarios.

**Comment by GhaziTriki** [comment]
@butchooka Did you update your BigBlueButton server configuration https://docs.bigbluebutton.org/2.2/setup-turn-server.html#configure-bigbluebutton-to-use-the-coturn-server then restart?

**Comment by butchooka** [comment]
Seems issue was on strato v-server, using "another" server worked instantly.
Not possible to get it runnng on strato
