### ISSUE TITLE
New breakout room not added to HTML5 "breakout rooms" list when added via API

### ISSUE THREAD

**Issue by wardnath** [bigbluebutton/bigbluebutton#8977]
**Describe the bug**
When I add a breakout room via API the room does not show up in the HTML5 UI "breakout rooms" list

**To Reproduce**

(1) Create a meeting (I'm doing this via greenlight but I suspect it doesn't matter how the meeting is created)
(2) Join the meeting
(3) create 2 breakout rooms
(4) verify breakout rooms have been created by looking at the HTML5 UI "breakout rooms" list, should expect to see "Breakout Room - 1 (0)", "Breakout Room - 2 (0)" 
(5) in the API create a new breakout room with Parent ID equal to the Internal ID of the parent meeting created in step (1), see: https://docs.bigbluebutton.org/dev/api.html#create
eg: 
```
http://<hostname>/api/create?meetingID=<breakoutMeetingID>&isBreakout=true&parentMeetingID=<parentInternalMeetingID>&sequence=3&duration=999
```

**Expected behavior**
New breakout room created, breakout room stays active and appears in the HTML5 UI "breakout rooms" list. 

**Actual behavior**

Breakout immediately becomes inactive, does not appear in the HTML5 UI "breakout rooms" list

**Screenshots**

**Desktop (please complete the following information):**
 - OS: OS X
 - Browser: Chrome
 - Version: v2.2.x-release

**Smartphone (please complete the following information):**
 None

**Additional context**
None that I can think of, can provide logs or API responses if those would be of use. Thanks for the support!

**Comment by capilkey** [comment]
Why are you trying to create breakout rooms by calling the create API? There is internal messaging that is sent along with the creation of the breakout rooms and it's all directed by bbb-akka-apps so just calling the create API on its own won't and shouldn't work.

**Comment by wardnath** [comment]
Thanks @capilkey for the response. Much appreciated! BigBlueButton is immensely helpful for me in moving my lectures online.

My use case is that I want to create new breakout rooms when students enter the conference without disturbing previous ongoing sessions (via closing and recreating). I'm also trying to automate some of the group assignment programmatically. 

I notice when I end a breakout room via the `/end` endpoint, that works just fine, the changes are reflected in the UI. Is this because the message `BreakoutRoomEndedEvtMsg` is sent? 
see: https://github.com/bigbluebutton/bigbluebutton/blob/41f19a2cd1bc7dae76cbd805cdc3ddfbf1e6ab18/akka-bbb-apps/src/main/scala/org/bigbluebutton/core2/message/handlers/meeting/DestroyMeetingSysCmdMsgHdlr.scala#L23-L24

Would a `BreakoutRoomStartedEvtMsg` need to be sent out upon a successful `/create` endpoint call with the `isBreakout` query parameter set to `true`?

**Comment by wardnath** [comment]
Thanks @capilkey that's very helpful!

I've considered just creating a lot of breakout rooms up front, but ultimately I think I want to do more automation with my student groups so I think it's worth it to explore your first suggestion. I'll dig into that scala file to see if I can make headway and post my progress.

**Comment by wardnath** [comment]
Update: seems like sending a BreakoutRoomStartedEvtMsg isn't enough for everything to work. I send an API `create` call, and with some modified code akka apps sends out a BreakoutRoomStartedEvtMsg.

The good news is that this does populate the breakout rooms in the UI, however, I can't seem to click join and have the browser redirect. also clicking on "end all breakout rooms" does not close these API created rooms. 

I suspect I will need to add in more calls beyond the BreakoutRoomStartedEvtMsg one. Such as the "CreateBreakoutRoomsCmdMsg"? I noticed even if I create a breakout with the `create` api call, it does not trigger "CreateBreakoutRoomsCmdMsg" only the "CreateMeetingRequest" here: https://github.com/bigbluebutton/bigbluebutton/blob/v2.2.x-release/bbb-common-web/src/main/scala/org/bigbluebutton/api2/BbbWebApiGWApp.scala#L213

**Comment by wardnath** [comment]
Another update: it seems like the trick is providing the userId here:
https://github.com/bigbluebutton/bigbluebutton/blob/develop/akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/breakout/CreateBreakoutRoomsCmdMsgHdlr.scala#L18

Unfortunately it doesn't seem like there's a way to get the InternalUserId via the API, so I'll need to figure that out.

**Comment by matiasilva** [comment]
Hi @wardnath, this seems like a potentially useful application for all. I have found that not being allowed to create breakout rooms after existing ones have been created is somewhat limiting. Could you perhaps give us an update? We'd be glad to hear about your experience and your automation plans in https://groups.google.com/forum/#!forum/bigbluebutton-dev for other developers to contribute.

**Comment by wardnath** [comment]
Hey @matiasilva, yeah it's a work in progress. The automation is coming from a mix of api calls + puppeteer to automatically click around in the javascript and assign users to rooms. Once I have something more finalized I can create a PR and share my use case on the forum!

**Comment by econHailey** [comment]
Hi @wardnath,
Did you end up figuring this out? I'm encountering a similar problem and would love to see what you've come up with!
