### ISSUE TITLE
How to customize the about and help link in the menu?

### ISSUE THREAD

**Issue by hassanayoub85** [bigbluebutton/bigbluebutton#8979]
**Describe the bug**
I cant find where to change the about text and the help link inside the menu

**To Reproduce**
1. Go to room
2. Click on menu
3. You will find 2 menu items: Help and About

**Comment by GhaziTriki** [comment]
@hassanayoub85 Please don't double post here and in the forums. The forums are the right place to ask for help. The community is active you will get your answer.
