### ISSUE TITLE
Kurento media service crashes often

### ISSUE THREAD

**Issue by seancodev** [bigbluebutton/bigbluebutton#8982]
Hello,

When in an active session or class, with around 20-30 users, suddenly the media cuts out entirely (webcams off and screenshare off), and no one is able to reconnect. They get an error 2003 'cannot connect to media server'. This happens very consistently. The server hardware is brand new, with 64GB memory, 12 cores (double threaded), 1Gbps bandwidth and solid state drives. I know the hardware is working well.

When this happens we have to re-start BBB, which is an annoyance to everyone using it, and they are losing faith in the software and switch to Zoom.... which isn't good! I like BBB :) 

Any advice would be appreciated. Maybe updating Kurento?

Thank you!

**Comment by prlanzarin** [comment]
What version of BBB are you using?

**Comment by seancodev** [comment]
Html 5 - 2.2 rc

**Comment by prlanzarin** [comment]
Is it a possiblity for you to update to the latest version (2.2.3)? There was a set of fixes and updates to the media stuff (and Kurento specifically) which I believe will make your experience a bit smoother. If you do update and still see problems, please ping me and attach /var/log/kurento-media-server/ logs and /var/log/bbb-webrtc-sfu/ logs.

A question regarding your scenario, though: how many cameras are being shared?

**Comment by seancodev** [comment]
Hello,

I am sending you the logs in a minute. In this case there were around 30 people sharing their webcams and a screenshare happening at the same time. It was a real lesson for an institution.

Will update to 2.2.3 from 2.2.2 next chance we get.

Thank you for looking into this.

**Comment by seancodev** [comment]
I've put the logs here (too big to upload):
http://www.scdevelop.ca/bbblogs/

**Comment by prlanzarin** [comment]
I've downloaded them. You may remove them from the domain if you wish.
I'll take a look as soon as I can.

About your scenario: 30 webcams + screensharing is a lot. That's roughly 960+ streams (including recording streams) for a single server. The updates on 2.2.3 make things smoother, but I can't guarantee it'll all work properly because that's over what's healthy for KMS to handle, unfortunately. You can take a look at https://docs.bigbluebutton.org/2.2/customize.html#reduce-bandwidth-from-webcams to reduce CPU stress a bit, but that's still a bit over what has been tested.

**Comment by HeatonTj** [comment]
> 
> 
> Is it a possiblity for you to update to the latest version (2.2.3)? There was a set of fixes and updates to the media stuff (and Kurento specifically) which I believe will make your experience a bit smoother. If you do update and still see problems, please ping me and attach /var/log/kurento-media-server/ logs and /var/log/bbb-webrtc-sfu/ logs.
> 
> A question regarding your scenario, though: how many cameras are being shared?

Hello sir, 
Could you please write how to do it?

**Comment by seancodev** [comment]
Just to comment on the upgraded results of BBB 2.2.3:

Kurento still does crashed, but supported a LOT more users (up to 200). The service self-revives itself now and returns more valid errors (ie. no more resources), which is a bonus. Prior, a restart of BBB was required and this is no longer the case it seems. As the next step, we've changed the settings so BBB only shows the webcams to the moderators/presenters and not to each viewer, and lowered the bitrate considerably. We also disabled all logging, because these log files were getting massive, and we need as many resources as we can get :) Will update this thread with how this works out.

We have also changed the Moodle plugin so you can add multiple BBB servers to the configuration and using the datestamps in the database, created a round-robin approach for conferences that take place at the same time to determine the best server to join based on number of students in the classes, as we are getting a high demand for webcam sharing from several institutions we work with.

Will provide update on how this all works out.

**Comment by beatwiz** [comment]
Hey @seancodev, thanks for sharing your experience! Im on the same boat. Around 200 users using voice and maybe (~40 webcams) on 16c Xeon 32GB RAM servers. But loads go pretty high above maximum if there are more webcams being shared.

I wish there was a way to stop mods from changing the "sharing webcam with others" option after the room is started with that option disabled. As they seem to miss that they dont need students to see each other, and they do see the students with that option off.

Also, if you mind me asking. How did you go about disabling logs? Disabling all log options in settings.yml? Or am I missing something else? Thanks again for sharing and for any update.

**Comment by seancodev** [comment]
@beatwiz Oi!

You can edit the settings in this file:
/etc/default/kurento-media-server

You can also change 'appLevelLog' in the main BBB configuration file to 'NONE'.

Today went very well by making these settings the default. We setup a Turn server as well, which solved all voice issues clients were having connecting from restrictive networks.

**Comment by meuhland** [comment]
It seems the cron.hourly that was added in 2.2.3 is a good start but for some use cases it needs to be more aggressive.

From what I gathered it will force-restart the kms and kms-sfu service every 24+ hours
+ meaning it will start trying to restart it 24 hours after last restart but only if during the hourly check and only if there is no user connected.

Which if you have "stable" schedule (think office hours 9 to 5) would cause it to more or less try to restart the service only at 6 the next day which at that point it is already crashed for a while.

Until there is a more bulletproof solution to this adjusting the 24h delay might work for you.

**Comment by runout-at** [comment]
I'm running on AMD7282 with Debian-XEN-dom0 and Ubuntu-VM with 12 core, 18G RAM.

We have no problems with ~350 participants in ~15 meetings. We do recording of all sessions.

CPU-problems with lots of cameras i have seen mostly on the clients - not on the server. But normally our teachers do not use cameras. My own tests showed me, that before i get in trouble on the server the clients can not handle the cams anymore #8897 

CPU and RAM is needed mostly for post-rendering of the sessions.

**Comment by basisbit** [comment]
Thank you seancodev for reporting back your results!
Closing this issue now because the initially reported issue was resolved. For any further support request, please use our support forum / mailing list at https://groups.google.com/forum/#!forum/bigbluebutton-setup
