### ISSUE TITLE
install missing intermediate certificates

### ISSUE THREAD

**Issue by FloydZ** [bigbluebutton/bigbluebutton#8984]
**Describe the bug**
I installed BBB with a own certificate. This certificate was issued by a research association which is in the Firefox CA DB but _not_ the standard Debian/Ubuntu CAs. 
After setting the correct certificate path in the `/etc/nginx/sites-available/bigbluebutton` config file and adding my intermediate certificates to the greenlight docker image i was able to login into BBB over https. But i was not able to see any pdf presentations.

After some digging i found the following error
```
journalctl -xef -u bbb-html
Apr 04 14:04:59 bbb systemd_start.sh[9458]: error: Error parsing image size. Error: unable to verify the first certificate. uri=https://MYDOMAIN.com/bigbluebutton/presentation/8e1a37f0e56822e7d3eb088c014987646f245ea6-1586001891779/8e1a37f0e56822e7d3eb088c014987646f245ea6-1586001891779/d2d9a672040fbde2a47a10bf6c37b6a4b5ae1876-1586001892684/svg/6
```
So some intermediate certificates are missing. After some more googling i found [this](https://github.com/bigbluebutton/bigbluebutton/issues/6139) issue, which is exactly the same error. I tried to "install" my intermediate certificate to nodejs via
```
export NODE_EXTRA_CA_CE=/path/to/my/per/file.pem
bbb-conf --restart
```
But still got the same error.
So i also added my certificates to the java keystore via the `keystore -import ...` tool. But now i need to add this keystore password somewhere to the bbb config files. But i dont know where.

Hope you can help me. 

is used the `bbb-install.sh` script to install bbb.
**BBB version (optional):**
BigBlueButton Server 2.2.3 (1833)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Chromium, Firefox
 - Version  Newest

**Comment by jdanders** [comment]
I came to add what I think is the same issue. I am also using a self-signed root certificate and got everything to work except the whiteboard/presentation feature. I followed the same steps to fix as @FloydZ and also have not gotten it to work yet. I have a six occurrences of these two errors. 
```
journalctl -u bbb-html5
Apr 06 08:56:57 meeting systemd_start.sh[8975]: error: No file found. Error: self signed certificate in certificate chain
Apr 06 08:56:57 meeting systemd_start.sh[8975]: error: Error parsing image size. Error: self signed certificate in certificate chain. uri=https://meeting.corp.net/bigbluebutton/presentation/164c7a569757b7a390a27c2a46914704b24c9ad0-1586185009246/164c7a569757b7a...
```

**Comment by capilkey** [comment]
You have to add the cert to node by setting an environment variable, or edit settings.yml and change `loadSlidesFromHttpAlways` to true and restart bbb-html5.

**Comment by jdanders** [comment]
Is there some way of setting the environment variable that works? I have tried this as root:
```
export NODE_EXTRA_CA_CERTS=/path/to/my/per/file.pem
bbb-conf --restart
```
And that doesn't help.

Also, which is the path to settings.yml? I see several:
```
/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml
/usr/share/meteor/bundle/programs/server/node_modules/npm-normalize-package-bin/.github/settings.yml
/usr/lib/node_modules/npm/node_modules/npm-normalize-package-bin/.github/settings.yml
```
(I would guess the first one, but would like to be sure.)

Adding the cert is the better option, so I hope to make that one work.

**Comment by capilkey** [comment]
The correct location is /usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml.

As for the environment variable. It needs to be set as mentioned in this thread, https://groups.google.com/forum/#!topic/bigbluebutton-setup/S7XWB96MlU0.

**Comment by jdanders** [comment]
Thanks for the help, it's working now. That [Google groups](https://groups.google.com/forum/#!topic/bigbluebutton-setup/S7XWB96MlU0) page is wrong though, because the environment variable is wrong (`NODE_NEW_CA_CERTS` should be `NODE_EXTRA_CA_CERTS`)

To get it to work, in `/usr/share/meteor/bundle/systemd_start.sh` I changed towards the end of the file:
```shell
cd /usr/share/meteor/bundle
export ROOT_URL=http://127.0.0.1/html5client
export MONGO_OPLOG_URL=mongodb://127.0.1.1/local
```
to
```shell
# per https://groups.google.com/forum/#!topic/bigbluebutton-setup/S7XWB96MlU0
export NODE_EXTRA_CA_CERTS='/etc/ssl/certs/[myrootcert].pem'
cd /usr/share/meteor/bundle
export ROOT_URL=http://127.0.0.1/html5client
export MONGO_OPLOG_URL=mongodb://127.0.1.1/local
```
And after a reboot, I have working slides and whiteboard.

This should really be added to the SSL wiki instructions -- many of us need to use self-signed certs, and it's been an adventure getting them working. The other thing I had to hack I documented in issue #7985 to get the greenlight docker image to work.

**Comment by FloydZ** [comment]
thx @jdanders  it worked!
```
export NODE_EXTRA_CA_CERTS='/etc/ssl/certs/[myrootcert].pem'
bbb-conf --restart
```
did it!

**Comment by MeinhartEsrohr** [comment]
> thx @jdanders it worked!
> 
> ```
> export NODE_EXTRA_CA_CERTS='/etc/ssl/certs/[myrootcert].pem'
> bbb-conf --restart
> ```
> 
> did it!

Thank you so much, this worked for me , now my problem with the presentation is fixed, but i still got the problem with the microphone

**Comment by nine1zero** [comment]
> 
> 
> Thanks for the help, it's working now. That [Google groups](https://groups.google.com/forum/#!topic/bigbluebutton-setup/S7XWB96MlU0) page is wrong though, because the environment variable is wrong (`NODE_NEW_CA_CERTS` should be `NODE_EXTRA_CA_CERTS`)
> 
> To get it to work, in `/usr/share/meteor/bundle/systemd_start.sh` I changed towards the end of the file:
> 
> ```shell
> cd /usr/share/meteor/bundle
> export ROOT_URL=http://127.0.0.1/html5client
> export MONGO_OPLOG_URL=mongodb://127.0.1.1/local
> ```
> 
> to
> 
> ```shell
> # per https://groups.google.com/forum/#!topic/bigbluebutton-setup/S7XWB96MlU0
> export NODE_EXTRA_CA_CERTS='/etc/ssl/certs/[myrootcert].pem'
> cd /usr/share/meteor/bundle
> export ROOT_URL=http://127.0.0.1/html5client
> export MONGO_OPLOG_URL=mongodb://127.0.1.1/local
> ```
> 
> And after a reboot, I have working slides and whiteboard.
> 
> This should really be added to the SSL wiki instructions -- many of us need to use self-signed certs, and it's been an adventure getting them working. The other thing I had to hack I documented in issue #7985 to get the greenlight docker image to work.

please add this to the documentation really important whose have custom CA

**Comment by matiasilva** [comment]
@nine1zero The documentation repository is available at https://github.com/bigbluebutton/bigbluebutton.github.io if you don't mind. If you lack the time, let me know and I can add it.

**Comment by nine1zero** [comment]
@matiasilva opened fork nine1zero-customca
