### ISSUE TITLE
Fix phone number display in RTL

### ISSUE THREAD

**Issue by GhaziTriki** [bigbluebutton/bigbluebutton#8985]
There is two issues here:

- The phone number div in RTL mode must stay in LTR.
- The phone number should be formatted. The value we put in `bigbluebutton.properties` must be displayed as-it-is.

![image](https://user-images.githubusercontent.com/4991088/78459682-6c8b7300-76c3-11ea-92ff-b98b94027738.png)

**Comment by prlanzarin** [comment]
@GhaziTriki is this still an issue?
