### ISSUE TITLE
bbb-web is unable to fetch the recordings

### ISSUE THREAD

**Issue by GhaziTriki** [bigbluebutton/bigbluebutton#8986]
Sometimes `bbb-web` enters an invalid state, probably after an update.

When we use `getRecordings` we have this message in the sever.

```
2020-04-05T11:13:55.537+03:00 INFO  o.b.api2.util.RecMetaXmlHelper - Exception while loading /var/bigbluebutton/published/presentation/6be47b16cd5dbb3f2ecaa101f1ccb4fa16d234bd-1585574899195/metadata.xml
2020-04-05T11:13:55.537+03:00 INFO  o.b.api2.util.RecMetaXmlHelper - Exception details: java.io.FileNotFoundException: /usr/share/bbb-web/WEB-INF/lib/bbb-common-message_2.12-0.0.1583347698-SNAPSHOT.jar (No such file or directory)
```

The right filename is `bbb-common-message_2.12-0.0.1585168354-SNAPSHOT.jar`. It might be an issue in the unpackaging.

**Comment by enaut** [comment]
probably you mean "unable" in the headline...
I have the same problem.
After a restart with `bbb-conf --restart` the recordings are visible again.

**Comment by GhaziTriki** [comment]
Thank you @enaut typo fixed. Yes a `bbb-conf --restart` makes them visible, but we need to find the root cause.

**Comment by enaut** [comment]
I completely agree - its just that some systems run in production and sometimes a quick "hack" helps the admins that stumbled upon a bugreport ;)

**Comment by wemakefuture** [comment]
Same issue videos disappear after i updated the greenlight and build the docker again. Please add this to the docs. Ty

**Comment by Chewie9999** [comment]
I have the same problem, and the restart fix works, but I do not see any exceptions in my `/var/log/bigbluebutton/bbb-web.log` file.
This is after installing a new server from scratch using the official installation documents 2 days ago.
The recording was done during the first test meeting we tried.

**Comment by nexusVI** [comment]
We are seeing the same issue. Recordings are only visible after issueing `bbb-confg --restart`, which is problematic during daily usage.
