### ISSUE TITLE
Cannot join room that was shared with you

### ISSUE THREAD

**Issue by fefrei** [bigbluebutton/bigbluebutton#8987]
**Describe the bug**
When trying to join a room that is shared with you, you are redirected to the home page.

**To Reproduce**
1. Have someone else create a room and share it with you.
2. Have someone else start that room.
3. Go to the room's URL.
4. Click the big blue _Join_ button.

**Expected behavior**
I join the room.

**Actual behavior**
The button sends me to the `/b/` URL, i.e. the Greenlight start page.

**Screenshots**
Clicking _Join_ here:
![image](https://user-images.githubusercontent.com/3078885/78502078-795da480-775f-11ea-9092-c23411af6319.png)
Sends me here:
![image](https://user-images.githubusercontent.com/3078885/78502094-8da1a180-775f-11ea-8f46-55c0aa2edda5.png)

**BBB version (optional):**
`BigBlueButton Server 2.2.2 (1781)`

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Microsoft Edge (the new Chrome one)
 - Version 80

**Comment by GhaziTriki** [comment]
Hello @fefrei 
You are describing a GreenLight issue. Could you please report it here https://github.com/bigbluebutton/greenlight ?

**Comment by fefrei** [comment]
Looks like the issue was fixed in GreenLight 2.5.2.
