### ISSUE TITLE
How to set up CDN to my BBB server in Alibaba web host? 

### ISSUE THREAD

**Issue by yayaxueyu2019** [bigbluebutton/bigbluebutton#8988]
**Is your feature request related to a problem? Please describe.**
No, it's sort of a question that I'm confusing about how to set up a CDN to my bbb server.

**Describe the solution you'd like**
Today, when I looked into the setting file "settings.yml" and I found a place with "CDN" which has no value yet(cdn: "") and this reminds me my efforts trying to set up a CDN service to my bbb server which is hosted in aliyun.com (China version of Alibaba Cloud) . It asks me to resolve my bbb domain to a CNAME before I can enable the CDN service. Please see the image attached. 
I just can't do it, since my bbb domain is pointing to an IP address, if I point it to a CNAME, my bbb server won't work, quite confusing.  Anyone can help? Thank. 

![Screen Shot 2020-04-06 at 10 51 26 AM](https://user-images.githubusercontent.com/56071188/78522253-597dbd80-77ff-11ea-9962-8b102907d581.png)
![Screen Shot 2020-04-06 at 11 47 11 AM](https://user-images.githubusercontent.com/56071188/78522258-613d6200-77ff-11ea-929c-508770a9a665.png)

**Describe alternatives you've considered**

**Additional context**

**Comment by jibon57** [comment]
If you wish to setup CDN to a domain then the value of CNAME will be that domain. For example: you want to set CDN for `example.com` as `cdn.example.com` then CNAME should point to `example.com`.
But does BBB really work with CDN or that's only for js or images only.

**Comment by yayaxueyu2019** [comment]
thanks, I'm not sure yet, just raising the question here and see if there is some possibility.  We deployed our bbb on Singapore server and our students are in China, and have a slow connection to it sometimes. We didn't deployed it in China was because our English teachers are from the US or the UK.

**Comment by GhaziTriki** [comment]
Hello @yayaxueyu2019 
The CDN feature here is only for the HTML5 assets. It was implemented a year ago but not sure how many servers are using it.
Could you check the config steps in the PR https://github.com/bigbluebutton/bigbluebutton/pull/7062 ?
Can you also check your HTML5 server logs and confirm that you see the `SERVER STARTED` with the CDN value you provided in configuration?

**Comment by yayaxueyu2019** [comment]
Thanks@GhaziTriki, I will try to check and test.
