### ISSUE TITLE
maxParticipants not counting properly

### ISSUE THREAD

**Issue by jibon57** [bigbluebutton/bigbluebutton#8990]
**Describe the bug**
During create meeting I am using `maxParticipants` value but it's allowing (maxParticipants - 1). I mean if I used value for maxParticipants = 5 then it's allowing only 4. When 5th person try to join that time showing error message regarding :

`errors=[{"message":"The number of participants allowed for this meeting has been reached.","key":"maxParticipantsReached"}]`

**To Reproduce**
Use API to create meeting put value in `maxParticipants` 

**Expected behavior**
It should allow the number of users that was specified in `maxParticipants`

**Actual behavior**
It's allowing one user less.

**Comment by pedrobmarin** [comment]
#8510

**Comment by matiasilva** [comment]
Closing per suggestion in the above issue.
