### ISSUE TITLE
freeswitch.service failed because the control process exited with error code

### ISSUE THREAD

**Issue by muchlisre** [bigbluebutton/bigbluebutton#8991]
Hi.
please help

I just finished installing bbb. after I check the status of the FreeSwitch it is not active. I followed the command that appeared on the screen. and it's still not the same way.

This is when I run the check status:
nginx —————————————————► [✔ - active]
freeswitch ————————————► [✘ - failed]
redis-server ——————————► [✔ - active]
bbb-apps-akka —————————► [✔ - active]
bbb-transcode-akka ————► [✔ - active]
bbb-fsesl-akka ————————► [✔ - active]
red5 ——————————————————► [✔ - active]
tomcat7 ———————————————► [✔ - active]
mongod ————————————————► [✔ - active]
bbb-html5 —————————————► [✔ - active]
bbb-webrtc-sfu ————————► [✔ - active]
kurento-media-server ——► [✔ - active]
etherpad ——————————————► [✔ - active]
bbb-web ———————————————► [✔ - active]

its when i run check

BigBlueButton Server 2.2.3 (1833)
                    Kernel version: 5.3.10-1-pve
                      Distribution: Ubuntu 16.04.5 LTS (64-bit)
                            Memory: 16384 MB
                         CPU cores: 32

/usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties (bbb-web)
       bigbluebutton.web.serverURL: https://xx.xxxxx.com
                defaultGuestPolicy: ALWAYS_ACCEPT
                 svgImagesRequired: true

/etc/nginx/sites-available/bigbluebutton (nginx)
                       server name: xx.xxxxx.com
                              port: 80, [::]:80
                              port: 443 ssl
                    bbb-client dir: /var/www/bigbluebutton

/var/www/bigbluebutton/client/conf/config.xml (bbb-client)
                Port test (tunnel): rtmp://xx.xxxxx.com
                              red5: xx.xxxxx.com
              useWebrtcIfAvailable: true

/opt/xx.xxxxx.comitch/etc/xx.xxxxx.comitch/vars.xml (xx.xxxxx.comITCH)
                       local_ip_v4: xx.xx.xx.xx
                   external_rtp_ip: stun:stun.xx.xxxxx.comitch.org
                   external_sip_ip: stun:stun.xx.xxxxx.comitch.org

/opt/xx.xxxxx.comitch/etc/xx.xxxxx.comitch/sip_profiles/external.xml (xx.xxxxx.comITCH)
                        ext-rtp-ip: $${local_ip_v4}
                        ext-sip-ip: $${local_ip_v4}
                        ws-binding: :5066
                       wss-binding: :7443

/usr/local/bigbluebutton/core/scripts/bigbluebutton.yml (record and playback)
                     playback_host: xx.xxxxx.com
                 playback_protocol: https
                            ffmpeg: 4.2.2-1bbb1~ubuntu16.04

/etc/bigbluebutton/nginx/sip.nginx (sip.nginx)
                        proxy_pass: xx.xx.xx.xx

/usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml (Kurento SFU)
                        kurento.ip: xx.xx.xx.xx
                       kurento.url: ws://127.0.0.1:8888/kurento
                    localIpAddress: xx.xx.xx.xx
               recordScreenSharing: true
                     recordWebcams: true
                  codec_video_main: VP8
               codec_video_content: VP8

/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml (HTML5 client)
                             build: 870
                        kurentoUrl: wss://xx.xxxxx.com/bbb-webrtc-sfu
                  enableListenOnly: true

# Potential problems described below
# Warning: API URL IPs do not match host:
#
#                                IP from ifconfig: xx.xx.xx.xx
#  /var/lib/tomcat7/demo/bbb_api_conf.jsp: xx.xxxxx.com

grep: /opt/xx.xxxxx.comitch/var/log/xx.xxxxx.comitch/xx.xxxxx.comitch.log: No such file or directory

#
# Error: Unable to connect to the xx.xxxxx.comITCH Event Socket Layer on port 8021
#
# Warning: The voice application may not have registered with the sip server.
#   Try running: 
#
#      bbb-conf --clean
#

# Error: Could not detect xx.xxxxx.comITCH listening on port 5060

# Warning: The API demos are installed and accessible from:
#
#    https://xx.xxxxx.com
#
# and
#
#    https://xx.xxxxx.com/demo/demo1.jsp
#
# These API demos allow anyone to access your server without authentication
# to create/manage meetings and recordings. They are for testing purposes only.
# If you are running a production system, remove them by running:
#
#    apt-get purge bbb-demo

# Warning: You have this server defined for https, but in
#
#   /etc/bigbluebutton/nginx/sip.nginx
#
#  did not find the use of https in definition for proxy_pass
#
#            proxy_pass http://xx.xx.xx.xx:7443;

and this when i run systemctl status freeswitch.service

freeswitch.service - freeswitch
   Loaded: loaded (/lib/systemd/system/freeswitch.service; enabled; vendor preset: ena
   Active: failed (Result: start-limit-hit) since Mon 2020-04-06 08:02:12 UTC; 29s ago
  Process: 2261 ExecStart=/opt/freeswitch/bin/freeswitch -u freeswitch -g daemon -ncwa

Apr 06 08:02:12 bbb systemd[1]: Failed to start freeswitch.
Apr 06 08:02:12 bbb systemd[1]: freeswitch.service: Unit entered failed state.
Apr 06 08:02:12 bbb systemd[1]: freeswitch.service: Failed with result 'exit-code'.
Apr 06 08:02:12 bbb systemd[1]: freeswitch.service: Service hold-off time over, schedu
Apr 06 08:02:12 bbb systemd[1]: Stopped freeswitch.
Apr 06 08:02:12 bbb systemd[1]: freeswitch.service: Start request repeated too quickly
Apr 06 08:02:12 bbb systemd[1]: Failed to start freeswitch.
Apr 06 08:02:12 bbb systemd[1]: freeswitch.service: Unit entered failed state.
Apr 06 08:02:12 bbb systemd[1]: freeswitch.service: Failed with result 'start-limit-hi

**Comment by paulmenzel** [comment]
What does `journalctl -u freeswitch.service -b` show?

**Comment by basisbit** [comment]
There was no response for this support issue for almost two months, thus closing this issue. The original problem was probably already solved by one of the recent FreeSWITCH updates.

**Comment by Numanraza9** [comment]
just try using debian 11
