### ISSUE TITLE
Cannot unlock muted phone user

### ISSUE THREAD

**Issue by GhaziTriki** [bigbluebutton/bigbluebutton#8992]
**Describe the bug**
The moderator cannot unlock muted phone user.

**To Reproduce**
1. Create a meeting.
2. Join the audio conference via the web client.
3. Join the audio conference via phone.
4. Mute all participants.
5. Lock microphone.
6. Unlock microphone of the phone user. (Won't work)

**Expected behavior**
The phone user audio should be unlocked.

**Actual behavior**
The phone use audio stays locked.

**Screenshots**
![image](https://user-images.githubusercontent.com/4991088/78545080-d743c800-7803-11ea-8817-9da3c5adec4a.png)

**BBB version (optional):**
BigBlueButton Server 2.2.3 (1848)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Firefox Nightly
 - Version: 76.0a1 (2020-04-05) (64 bits)

**Comment by matiasilva** [comment]
Does this issue still persist in the newest version of BBB?

**Comment by gustavotrott** [comment]
Hey @GhaziTriki, can you check if this issue persist in current 2.6 release?

**Comment by antobinary** [comment]
Nvm, @zhem0004 corrected me that he is able to reproduce it on 2.6.
