### ISSUE TITLE
Misleading statement about Hardware Requirements in documentation

### ISSUE THREAD

**Issue by einhirn** [bigbluebutton/bigbluebutton#8993]
The documentation states that you should not run BBB on a VM and explains the why by referring to Freeswitch requirements. But the page you are referring to is about Freeswitch **Performance Testing**, not about **basic requirements** or **recommendations for production**.

So while there sure are benefits in running this on a bare metal server, I don't think that you really need one. Depending on how many video streams you expect you can very well use a VM without any problem. But still, at my workplace we have this discussion all the time "but the docs say it should be on bare metal"... 

Whats your stance on this?

**Comment by capilkey** [comment]
The bare metal recommendation isn't for the videos, it's for the audio. You'll experience more desync between audio and video in recordings and poor quality audio in a live session with a virtual server (usually). You can get close to bare metal if you get a compute optimized instance that has dedicated CPUs.

**Comment by einhirn** [comment]
Ok, so the second part of my Post wasn't precise. But the important thing for me still is that what the BBB docs call "FreeSWITCH recommended configurations" here

> Why do we recommend a bare metal server? BigBlueButton uses FreeSWITCH for processing of incoming audio packets and FreeSWITCH works best in a non-virtualized environment (see FreeSWITCH recommended configurations).

are only recommended in an article about performance-testing FreeSWITCH. You can easily find that out, when clicking on the link - but you don't know about this when just reading the BBB docs.

Maybe it's a thing in German thinking that makes "works best" to sound like "you absolutely need", but still I'd like to see a more differentiated information here.

Sure, maybe you're just writing that because people will complain that BBB doesn't work well on their 1 vCPU-Instance that already is overloaded before installing BBB... But for those of us who run a big on premise virtualization infrastructure with quite some CPU headroom this passage in the docs creates unneccessary grief. And most of us don't have the luxury (especially now) to just order a new big box to run BBB on. We need to use what we already have. And I somehow doubt that BBB will perform better on the retired, 7 year old hardware we keep around just because it would be a pity to throw it away than on a VM hosted on a modern Server that has enough ressources left...

Ok, now I have said my piece - feel free to close this issue...

**Comment by gnaegi** [comment]
I totally agree. We rented additional bare-metal server because of this article, however the BBB instance that we run on our own virtualized server runs much smoother than on the bare-metal hardware. It also thought that the actual specs of a server matter less than opting for a bare-metal solution. In the end it seems to be more complicated (as usual ;-)

But: in general the BBB documentation it outstanding! There are not so many other project that offer that level of help and details right in the manual! Partially it seems a bit outdated regarding the HTML5 client, but anyway, thank you!

**Comment by iSamof** [comment]
Team - fascinating discussion. Thank you for sharing experiences and insights.

@capilkey - you mentioned potential for audio desync in recordings and poor audio in live sessions. Is there the same potential if there is no webcam, just audio plus a presentation?

Context: We are looking at letting room creators select whether they need webcams or just audio plus presentation. Then we can push the latter onto VMs and push meetings when webcams are required to bare metal. This lets us create multiple 8-dedicated-core VMs on our bigger servers (16 cores and more) which at present have spare resources that BBB rooms cannot fully benefit from.  

If your answer is "no, no dysync" or "minimal potential" or "lesser audio deterioration in live sessions" with audio+presentation only rooms ... we are good to go.

P.S. I have noted the various conversations about turining the settings, reducing webcam resolution, limiting attendees etc all of which can help bring acceptable VM quality and close to bare metal.

**Comment by lonesomewalker** [comment]
We are actually running about 2k instances of BBB now.
From our support requests: bare metal is less problematic than virtual machines with dedicated CPUs.

**Comment by einhirn** [comment]
Hi @lonesomewalker, thanks for sharing your insight. Does your statistic contain information about the usage scenario? Some scenarios that work better on a hardware seem to be, but not limited to, the following:

- By now I learned about the audio desync issue being real for video recordings, because of the streams not being muxed on the client but on the server, the smaller latency of a hardware server is beneficial. Trimming a BBB-VM's latency down to the required levels usually is complicated, if at all possible.
- Having a lot of Video streams (upwards of 20 Users is hard, even with low video quality) requires raw compute power - which may not be feasible in a virtual environment, because you usually want to share the compute power with other instances, so you probably don't like VMs hogging 20-upwards CPU Cores.

On the other hand there seem to be some scenarios that work well on VMs - well enough to consider it for production, especially because it is easier to have multiple VMs to share the load of a number of lectures running at the same time than it is to have multiple hardware. I for one have only heard of breakdowns with "single big (hardware) machine" instead of "many (smaller) VMs". But of course my sample size is relatively small compared to your 2000 instances...

Some of the scenarios that work well (enough) on VMs with 8core@2GHz Xeon Gold 6000s series / 16GB RAM are (but not limited to): 

- Lectures with only one or two Videos, maybe a screenshare and up to some hundred "Listen-Only" participants. At some point the server component of the HTML5 client UI might become the bottle neck...
- Video Conferences up to maybe 15 videos, but usually the client PCs max out before the server breaks down hard.

**Comment by matiasilva** [comment]
@iSamof your solutions sounds quite interesting, did you end up pushing it to prod? Everyone else, I'd recommend updating the documentation where you see fit.

**Comment by iSamof** [comment]
@matiasilva - I never got a response from @capilkey ... but we have "something" working and currently being extended, along those lines though not quite what I stated above, yet. Here is a quick summary:

We are working a number of streams with a _very_ small team, so progress is slow. We have built parameters to match server specs to session requirements (listen only, audio only, few/lots of webcams, etc). These have not been tested as yet. 

Using this setup will be able to load balance between different servers based on user requirements. Currently, we use bare metal servers but once we get the opportunity to set up our VMs we can add those into the server pool. At that point I will be able to answer your question properly.

Yes, we are aware of the BBB load balancer. But our Joomla installation also benefits from the option to integrate a large pool of Joomla/PHP experts at reasonable prices and a huge supply of well established add-ons, all at a very low cost ... e.g. thousands of UI templates, membership managers, security tools, data visulaisation components and more. This is a similar situation to using WP as the UI which I think others are doing.

NOTE: all our services are free and open to the public which limits our resources and therefore our ability to service a large user base. Currently, some universities and businesses are using our bare metal BBB installations, without any fees or advertising.

I hope this helps.

**Comment by prlanzarin** [comment]
> you mentioned potential for audio desync in recordings and poor audio in live sessions. Is there the same potential if there is no webcam, just audio plus a presentation?
=====
> I never got a response from \capilkey ... but we have "something" working and currently being extended, along those lines though not quite what I stated above, yet. Here is a quick summary:

@iSamof just to tie this knot: yes, desync MAY happen with audio even if there's no video. Presentation timestamps are usually pretty on spot on recordings and FreeSWITCH might drift audio if clock is sufficiently botched, so it'll be "desynched" no matter what you're using in the conference. Audio drifts by itself.

**Comment by iSamof** [comment]
@prlanzarin - many thanks for clearing that up.
