### ISSUE TITLE
Wrong path in "Root partition too small" troubleshooting documentation

### ISSUE THREAD

**Issue by mabeyj** [bigbluebutton/bigbluebutton#8996]
**Describe the bug**
https://docs.bigbluebutton.org/2.2/troubleshooting.html#root-partition-too-small

This says the path for FreeSWITCH audio files is at `/var/freeswitch/meetings`. But in the example commands for moving this folder and creating the symbolic link, it uses the path `/opt/freeswitch/recordings`. The commands should use `/var/freeswitch/meetings` which is the correct path.

I would also suggest adding `/var/lib/kurento/recordings` and `/var/lib/kurento/screenshare` to the example since videos are stored there. They would also be a concern when using a small root partition.

**Screenshots**
![image](https://user-images.githubusercontent.com/773401/78566852-37337200-77f6-11ea-8592-f247879325e0.png)

**Comment by GhaziTriki** [comment]
@mabeyj Documentation fixed.

**Comment by GremL1N** [comment]
is there an easy way to understand which recordings file not nesessary after publish record?
it only grows up and not cleaning/
