### ISSUE TITLE
Failed to call setConfigXML api checksumerror

### ISSUE THREAD

**Issue by mohgh** [bigbluebutton/bigbluebutton#8998]
**Describe the bug**
I've installed BBB on my server and everything is working as it should. Now I tried bbb-demo project to test setConfigXml API in demo12.jsp but I get "request did not pass the checksum security check" error. Previous demos are working fine. 

**To Reproduce**
1. Install bbb-demo
2. Go to /demo/demo12.jsp
3. Enter a name and submit form
4. Get the error.

**Expected behavior**
The user should be navigated to the customized session.

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [Chrome]

**Additional context**
I've also tested the api via C# code and the same problem happened. I was expected the actual test code to work but I get the error. I could provide you the live version if you need to investigate better.

**Comment by GhaziTriki** [comment]
@mohgh `setConfigXML` is only for the Flash client which is no more supported. Are you using it? If yes, is it an option for you to move to the HTML5 client?

**Comment by mohgh** [comment]
No, I'm not using the flash client and I have no idea about that being for only flash client. I want to accomplish the same functionality for html5 meaning each meeting has customized options (max participants, custom lock setting,s ...). How can I achieve this?

**Comment by matiasilva** [comment]
You can achieve this by passing custom parameters to the join API call. The full list of available parameters are [here](https://github.com/bigbluebutton/bigbluebutton/blob/develop/bigbluebutton-html5/imports/api/users-settings/server/methods/addUserSettings.js). An example parameter would look like this: `userdata-bbb_enable_video_stats=true`. Closing for now as this fully accomplishes the issue goal. For further questions, open a topic in our users group: https://groups.google.com/forum/#!forum/bigbluebutton-users.
