### ISSUE TITLE
IT'S OVER 9000!!!

### ISSUE THREAD

**Issue by Tainan404** [bigbluebutton/bigbluebutton#9001]
It’s not a issue, just to say that we've gone over 9000 PRs and issues opened. :)

![its-over-9000](https://user-images.githubusercontent.com/15806883/78587929-1f6ae680-7814-11ea-8125-591252b09ce5.gif)

**Comment by Arthus** [comment]
Fun fact: This line was actually translated wrong. In the japanese original it is: "It's over 8000!" :)

**Comment by basisbit** [comment]
Thank you! This made my day! 🤣
