### ISSUE TITLE
Restrict moderator from changing lock settings

### ISSUE THREAD

**Issue by mohgh** [bigbluebutton/bigbluebutton#9003]
Is it possible to restrict the moderator from changing the initial lock settings after the meeting has created?

**Comment by capilkey** [comment]
There's no system to lock the lock settings.

**Comment by matiasilva** [comment]
I don't see this being useful as an extra feature. By definition a moderator is someone with additional privileges. You can do this however by passing in extra parameters to the create call in the API: https://docs.bigbluebutton.org/dev/api.html#create
