### ISSUE TITLE
Disable upload slide function for student presenter

### ISSUE THREAD

**Issue by Screamer89** [bigbluebutton/bigbluebutton#9004]
Can I disable the ability to upload files for a student presenter? Leave whiteboard only.
I do not use a multiuser board, since I need to ask only one student.

**Comment by capilkey** [comment]
There's no way to do that. Whoever is presenter can upload and there are no checks for their role (moderator or viewer) when performing presenter functions.

**Comment by matiasilva** [comment]
You can add custom parameters on the join API call. A full list is [here](https://github.com/bigbluebutton/bigbluebutton/blob/develop/bigbluebutton-html5/imports/api/users-settings/server/methods/addUserSettings.js). An example would be `userdata-bbb_multi_user_pen_only=true`. By playing around with the three available settings, you should be able to achieve what you want. 

In any case, it should be as easy as asking your student not to upload random files. Or keeping yourself as the presenter but allowing multi-user whiteboard access. Closing for now as I've provided two adequate solutions.
