### ISSUE TITLE
Room created with running false

### ISSUE THREAD

**Issue by matrpedreira** [bigbluebutton/bigbluebutton#9009]
**Describe the bug**
When I create a room it is created with running = false.

**To Reproduce**
After installing BigBlueButton and trying the API it was working perfectly. However, I decided to try setting the parameters recommended in http://docs.bigbluebutton.org/dev/api.html in bigbluebutton.properties. After I did that when I create a room it is created with running = false and I can't join anymore, it takes a while and then the error 404 appears. This keeps happening even if I set the parameters as they came in the file and restart using `sudo bbb-conf --restart`

**Expected behavior**
I expected to change the parameters in bigbluebutton.properties without much of an issue.  

**Actual behavior**
After I changed only once all my rooms are created with running false. 

**Screenshots**
[Creating room](https://ibb.co/vk16Wk4)
[Meeting info](https://ibb.co/YPjfwRn)

**Desktop (please complete the following information):**
 - OS:  MacOS 10.15.4
 - Browser Microsoft Edge 
 - Version 80.0.361.106 [](url)

**Comment by matiasilva** [comment]
Thanks for posting an issue. We ask you to forward your query to https://groups.google.com/forum/#!forum/bigbluebutton-setup where your questions are better answered. Include more detail in your post so we can better assist you. Closing for now.
