### ISSUE TITLE
ICE Error 1007

### ISSUE THREAD

**Issue by agustinmono** [bigbluebutton/bigbluebutton#9013]
Im having this error when connecting to eco test..

http://prntscr.com/rv16r3

**BBB Check **

BigBlueButton Server 2.2.3 (1833)
                    Kernel version: 4.4.0-177-generic
                      Distribution: Ubuntu 16.04.6 LTS (64-bit)
                            Memory: 16431 MB
                         CPU cores: 8

/usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties (bbb-web)
       bigbluebutton.web.serverURL: https://a1.ofmperu.com
                defaultGuestPolicy: ALWAYS_ACCEPT
                 svgImagesRequired: true

/etc/nginx/sites-available/bigbluebutton (nginx)
                       server name: a1.ofmperu.com
                              port: 80, [::]:80
                              port: 443 ssl
                    bbb-client dir: /var/www/bigbluebutton

/var/www/bigbluebutton/client/conf/config.xml (bbb-client)
                Port test (tunnel): rtmp://a1.ofmperu.com
                              red5: a1.ofmperu.com
              useWebrtcIfAvailable: true

/opt/freeswitch/etc/freeswitch/vars.xml (FreeSWITCH)
                       local_ip_v4: MY_LOCAL_IP
                   external_rtp_ip: stun:stun.freeswitch.org
                   external_sip_ip: stun:stun.freeswitch.org

/opt/freeswitch/etc/freeswitch/sip_profiles/external.xml (FreeSWITCH)
                        ext-rtp-ip: $${local_ip_v4}
                        ext-sip-ip: $${local_ip_v4}
                        ws-binding: :5066
                       wss-binding: MY_LOCAL_IP:7443

/usr/local/bigbluebutton/core/scripts/bigbluebutton.yml (record and playback)
                     playback_host: a1.ofmperu.com
                 playback_protocol: https
                            ffmpeg: 4.2.2-1bbb1~ubuntu16.04

/etc/bigbluebutton/nginx/sip.nginx (sip.nginx)
                        proxy_pass: MY_LOCAL_IP

/usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml (Kurento SFU)
                        kurento.ip: MY_LOCAL_IP
                       kurento.url: ws://127.0.0.1:8888/kurento
                    localIpAddress: MY_LOCAL_IP
               recordScreenSharing: true
                     recordWebcams: true
                  codec_video_main: VP8
               codec_video_content: VP8

/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml (HTML5 client)
                             build: 870
                        kurentoUrl: wss://a1.ofmperu.com/bbb-webrtc-sfu
                  enableListenOnly: true

# Potential problems described below

**Comment by agustinmono** [comment]
UPDATE: I did as follows
https://docs.bigbluebutton.org/2.2/configure-firewall.html#update-freeswitch
 and now i have this error

http://prntscr.com/rv26jg


i dont have TURN server, can I install it on the Scalelite server? or i nedd another server too? what will be the specs for that

**Comment by adishare** [comment]
How :')

**Comment by matiasilva** [comment]
Don't revive an old issue. Follow the instructions on getting help: https://docs.bigbluebutton.org/2.2/getting-help.html
