### ISSUE TITLE
Weird external video sharing loop

### ISSUE THREAD

**Issue by beatwiz** [bigbluebutton/bigbluebutton#9014]
Please bear with me, as this only happens with a single presenter, but I have wasted so much time already, that I'm posting here, desperatly looking for anyone with a similar experience.

What happens is that when this particular presenter shares an external video, the entire class gets the video and it starts playing, but automatically rewinds after 5 seconds, and keeps looping like that, altough on the presenter side it plays normally.

The presenter is sharing a regular youtube video, and has tested with many other videos, and the same behavior happens.

It is definetly something on the presenter side, because if any other presenter joins the same, or any other room, and does the external video sharing, everything works correctly. Ive been there, sharing videos aswell and that particular presenter was able to watch the videos I shared and that others shared. But everytime she shared... We got a looping video.

I have even remote  connected to the presenter computer, and tested on different browsers (latest chrome and firefox), and video links, checked antivirus and installed software (its a pretty bare computer), and despite believing that the computer / OS is the culprit, for the life of me I cannot understand what causes this. The connection was also capable.

Again, the video plays regularly on the presenters side, but on the class attendees screens, it keeps looping the first 5 seconds.

I'm going to end up asking the presenter to reformat the computer and start anew to sort it out. Altough thats a terrible thing to ask a teacher :-)

Anyone else saw this or anything similar?
Many thanks in advance!

**Comment by Balranaldpresy** [comment]
Not quite sure if this helps, but last Sunday morning (5th April) the same problem was reported in a couple of our services when presenters were sharing videos. The videos would be shared ok and play on the presenters computer but on the receiving computer it would loop the first 5 seconds or so, and it turned out to be an issue related to when our state (NSW Australia) turned over from Daylight savings, some computers automatically changed time and others didn't. The time anomaly triggered something in YouTube which caused the loop effect.

**Comment by beatwiz** [comment]
@Balranaldpresy  That was exactly the problem! Just fixed her timezone settings and all is working perfctly now. Thank you so much for pointing me in the right direction. I owe you one.

**Comment by Rafael-Netizen** [comment]
This function but it did not work in our tests either. Just in case changing the timezone settings does not work, here is a workaround:

One workaround is using a playback synchronization service along with BBB, like Watch2Gether.com or  Sync-Tube.de. They typically work as follows:

1. The Moderator shares the (Youtube etc.) video URL
2. Every user retrieves the video and plays it back in her or his browser
3. During playback, the only data sent by the Moderator’s computer to the other users consists in short playback commands
