### ISSUE TITLE
Mute status is reset after connection recovery

### ISSUE THREAD

**Issue by chekoopa** [bigbluebutton/bigbluebutton#9016]
**Describe the bug**
HTML5 client doesn't keep mute status if connection problems forced client to reconnect and rejoin the audio session.

**To Reproduce**
1. Open a session, join audio in microphone mode
2. Mute your mic
3. Do some network interference

**Expected behavior**
After reconnection, mic is still turned off.

**Actual behavior**
After reconnection, mic is automatically turned on.

**Desktop**
 - OS: NixOS Linux
 - Browser: Firefox 70
 - BBB Client Build: 870

**Comment by stephanepoinsart** [comment]
Hello,

I was about to report the same bug. It looks like an important privacy issue. Unmuting an user without his consent or knowledge can lead to private information beeing exposed.

Some reason why a user would mute during a meeting : 
* He have a personal emergency and must talk in private to someone IRL
* He is in a noisy environment and that noise would disturb other participants
* He is about to fart really loud

I would not know how to rank them from "best to worst" but in none of those scenario I would like the user to be unmuted without his consent.

You can also reproduce the problem on https://demo.bigbluebutton.org

**Comment by Subdarub** [comment]
This is still an issue.

Tested on 2.2.30 and 2.3 alpha 3 with the new Edge Browser on Windows 10 2004.

To reproduce, connecting to a VPN will suffice.
