### ISSUE TITLE
Redirect from 401 error page

### ISSUE THREAD

**Issue by eiscan** [bigbluebutton/bigbluebutton#9018]
Hello,

Can I type a different url address in the Log Again button when the 401 error or other error pages appear? I want to redirect to a different url address. Where can I change the link of the button?

**Comment by capilkey** [comment]
There's a default logoutURL in bigbluebutton.properties. That value should be used if no value is passed on the user's join API call or if the client can't retrieve the user's information from bbb-web.

**Comment by eiscan** [comment]
Hello,

Sorry, logoutURL does not work on error pages.

**Comment by capilkey** [comment]
It depends on what the cause of the error is.

Did you try to set the default logoutURL as I said? It's in bigbluebutton.properties and it's called `bigbluebutton.web.logoutURL`

**Comment by eiscan** [comment]
Hi,
Yes I tried.
This redirect works when logged out. It does not redirect on error pages.

**Comment by matiasilva** [comment]
Hello. Have you managed to find a solution to this? By quickly digging around in the HTML5 client source, it doesn't seem that there's support for a redirect on error. It's useful for users to know that there was an error and redirecting might not be the best solution.
