### ISSUE TITLE
Autoscaling environment with externalized mongo and redis

### ISSUE THREAD

**Issue by sukrit007** [bigbluebutton/bigbluebutton#9020]
I am trying to see if we can setup bigbluebutton in an autoscalable environment with data services like redis and mongodb externalized.

We possibly want to use AWS with elasticache redis, amazon document db and fargate or beanstalk.

**Comment by sukrit007** [comment]
Looks like there was already an issue. https://github.com/bigbluebutton/bigbluebutton/issues/8685  . However, it got closed. 

ALso came across https://github.com/blindsidenetworks/scalelite which might be a solution for now.

**Comment by capilkey** [comment]
Everything that @ffdixon and I mentioned in that other issue still applies. The various services on a server are not designed to be split out like that and it won't work. You can't just externalize a service and expect it to just work. The underlying code would need to be heavily modified.

If you're looking to scale you get lots of 8 core 16GB machines and put them behind a BigBlueButton load balancer like Scalelite. Also try to keep your individual meetings to below 100 users.

**Comment by basisbit** [comment]
Closing this issue because it is not a supported configuration and is also not a BigBlueButton development related issue. For further support questions, please use the forum / mailing list at https://groups.google.com/forum/#!forum/bigbluebutton-setup
