### ISSUE TITLE
1020 media could not reach the server 

### ISSUE THREAD

**Issue by Salamit** [bigbluebutton/bigbluebutton#9021]
**Describe the bug**

I get the media could not reach the server 1020 error in Safari on iOS and Mac (Chrome works fine). 

It was working yesterday but stopped working all of a sudden) 

**To Reproduce**
Get into BBB virtual classroom
Try to turn on camera. 

**Expected behavior**
I expected web cam to work.

**Actual behavior**
`the media could not reach the server 1020 error 
`
**Desktop (please complete the following information):**
 - OS: Mac
 - Browser Safari
 - Version 13.1

**Smartphone (please complete the following information):**
 - Device: iPhone XR
 - OS: 13.4
 - Browser Safari
 

**IPad (please complete the following information):**
 - Device: iPad Pro
 - OS: 13.3.1
 - Browser Safari

**Additional context**

On my bbb server, running `stun stunAddressAsInKurento:stunPortAsInKurento -v` to a publicly available STUN server results in a mapped IP address that reflects my server's public IP

```
Received stun message: 88 bytes
MappedAddress = <SAME AS MY PUBLIC IP>:32184
```

However using my turn server as my stun instance and running `stun stunAddressAsInKurento:stunPortAsInKurento -v` results in an error. Please see below.

```
About to send msg of len 28 to <coturn instance ip>:3478
Encoding stun message:
Encoding ChangeRequest: 2

About to send msg of len 28 to <coturn instance>:3478
test I = 0
test II = 0
test III = 0
test I(2) = 0
is nat  = 0
mapped IP same = 1
hairpin = 0
preserver port = 0
Primary: Blocked or could not reach STUN server
Return value is 0x00001c
```

Turn server is on an AWS t2.micro instance
Turn server firewall permissions below: I've opened all UDP ports I think. 

```
OpenSSH                    ALLOW       Anywhere
443/tcp                    ALLOW       Anywhere
443/udp                    ALLOW       Anywhere
49152:65535/udp            ALLOW       Anywhere
3478                       ALLOW       Anywhere
Anywhere                   ALLOW       <From BBB server Public IP>
1:65535/udp                ALLOW       Anywhere
OpenSSH (v6)               ALLOW       Anywhere (v6)
443/tcp (v6)               ALLOW       Anywhere (v6)
443/udp (v6)               ALLOW       Anywhere (v6)
49152:65535/udp (v6)       ALLOW       Anywhere (v6)
3478 (v6)                  ALLOW       Anywhere (v6)
1:65535/udp (v6)           ALLOW       Anywhere (v6)
```

Turn server seems to be working fine according to https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/
<img width="864" alt="Screen Shot 2020-04-09 at 11 40 29" src="https://user-images.githubusercontent.com/12544262/78855545-246fa600-7a5f-11ea-84ee-6d7f58720033.png">

Requests to help Debug from [6797](https://github.com/bigbluebutton/bigbluebutton/issues/6797#issuecomment-607866043) 

**Did the same test scenario work on https://test.bigbluebutton.org?**
No issues on https://test.bigbluebutton.org while on Safari. 

**Please state if this is happening consistently or intermittently.**
Consistently from today. Worked fine yesterday.

**Please explain if your server is behind NAT. If possible, which type of NAT. The more details, the better.**
Yes, behind an NAT
`ufw status` yields the following. 
```
Nginx Full                 ALLOW       Anywhere
OpenSSH                    ALLOW       Anywhere
16384:32768/udp            ALLOW       Anywhere
22                         ALLOW       Anywhere
5066                       ALLOW       Anywhere
1935                       ALLOW       Anywhere
7443                       ALLOW       Anywhere
49152:65535/udp            ALLOW       Anywhere
Nginx Full (v6)            ALLOW       Anywhere (v6)
OpenSSH (v6)               ALLOW       Anywhere (v6)
16384:32768/udp (v6)       ALLOW       Anywhere (v6)
22 (v6)                    ALLOW       Anywhere (v6)
5066 (v6)                  ALLOW       Anywhere (v6)
1935 (v6)                  ALLOW       Anywhere (v6)
7443 (v6)                  ALLOW       Anywhere (v6)
49152:65535/udp (v6)       ALLOW       Anywhere (v6)
```

**Send the output of sudo bbb-conf --check. Please redact sensitive info.**
```
BigBlueButton Server 2.2.3 (1833)
                    Kernel version: 4.4.0-1104-aws
                      Distribution: Ubuntu 16.04.6 LTS (64-bit)
                            Memory: 32946 MB
                         CPU cores: 8

/usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties (bbb-web)
       bigbluebutton.web.serverURL: https://HOSTNAME
                defaultGuestPolicy: ALWAYS_ACCEPT
                 svgImagesRequired: true

/etc/nginx/sites-available/bigbluebutton (nginx)
                       server name: HOSTNAME
                              port: 80, [::]:80
                              port: 443 ssl
                    bbb-client dir: /var/www/bigbluebutton

/var/www/bigbluebutton/client/conf/config.xml (bbb-client)
                Port test (tunnel): rtmp://HOSTNAME
                              red5: HOSTNAME
              useWebrtcIfAvailable: true

/opt/freeswitch/etc/freeswitch/vars.xml (FreeSWITCH)
                       local_ip_v4: XXX.XXX.XXX.XXX
                   external_rtp_ip: PUBLIC IP ADDRESS
                   external_sip_ip: PUBLIC IP ADDRESS

/opt/freeswitch/etc/freeswitch/sip_profiles/external.xml (FreeSWITCH)
                        ext-rtp-ip: $${external_rtp_ip}
                        ext-sip-ip: $${external_sip_ip}
                        ws-binding: :5066
                       wss-binding: PUBLIC IP ADDRESS:7443

/usr/local/bigbluebutton/core/scripts/bigbluebutton.yml (record and playback)
                     playback_host: HOSTNAME
                 playback_protocol: https
                            ffmpeg: 4.2.2-1bbb1~ubuntu16.04

/etc/bigbluebutton/nginx/sip.nginx (sip.nginx)
                        proxy_pass: PUBLIC IP ADDRESS

/usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml (Kurento SFU)
                        kurento.ip: PUBLIC IP ADDRESS
                       kurento.url: ws://127.0.0.1:8888/kurento
                    localIpAddress: XXX.XXX.XXX.XXX
               recordScreenSharing: true
                     recordWebcams: true
                  codec_video_main: VP8
               codec_video_content: VP8

/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml (HTML5 client)
                             build: 870
                        kurentoUrl: wss://HOSTNAME/bbb-webrtc-sfu
                  enableListenOnly: true


# Potential problems described below
# IP does not match:
#                           IP from ifconfig: XXX.XXX.XXX.XXX
#   /etc/nginx/sites-available/bigbluebutton: HOSTNAME
# Warning: API URL IPs do not match host:
#
#                                IP from ifconfig: XXX.XXX.XXX.XXX
#  /var/lib/tomcat7/demo/bbb_api_conf.jsp: PUBLIC IP ADDRESS


# Warning: The setting of PUBLIC IP ADDRESS for proxy_pass in
#
#    /etc/bigbluebutton/nginx/sip.nginx
#
# does not match the local IP address (XXX.XXX.XXX.XXX).
# (This is OK if you've manually changed the values)

# Warning: The API demos are installed and accessible from:
#
#    https://HOSTNAME
#
# and
#
#    https://HOSTNAME/demo/demo1.jsp
#
# These API demos allow anyone to access your server without authentication
# to create/manage meetings and recordings. They are for testing purposes only.
# If you are running a production system, remove them by running:
#
#    apt-get purge bbb-demo
```

**Send the output of cat /usr/share/bbb-web/WEB-INF/classes/spring/turn-stun-servers.xml. Please redact sensitive info.**
```
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://www.springframework.org/schema/beans
        http://www.springframework.org/schema/beans/spring-beans-2.5.xsd">

    <bean id="stun0" class="org.bigbluebutton.web.services.turn.StunServer">
        <constructor-arg index="0" value="stun:turn.hostname.me"/>
    </bean>


    <bean id="turn0" class="org.bigbluebutton.web.services.turn.TurnServer">
        <constructor-arg index="0" value="SECRET"/>
        <constructor-arg index="1" value="turns:turn.hostname.me:443?transport=tcp"/>
        <constructor-arg index="2" value="86400"/>
    </bean>

    <bean id="turn1" class="org.bigbluebutton.web.services.turn.TurnServer">
        <constructor-arg index="0" value="SECRET"/>
        <constructor-arg index="1" value="turn:turn.hostname.me:443?transport=tcp"/>
        <constructor-arg index="2" value="86400"/>
    </bean>

    <bean id="stunTurnService"
            class="org.bigbluebutton.web.services.turn.StunTurnService">
        <property name="stunServers">
            <set>
                <ref bean="stun0"/>
            </set>
        </property>
        <property name="turnServers">
            <set>
                <ref bean="turn0"/>
                <ref bean="turn1"/>
            </set>
        </property>
    </bean>

```

 **Output of cat /etc/kurento/modules/kurento/WebRtcEndpoint.conf.ini**
;; External (public) IP address of the media server.
;;
;; If you know what will be the external or public IP address of the media server
;; (e.g. because your deployment has an static IP), you can specify it here.
;; Doing so has the advantage of not needing to configure STUN/TURN for the media
;; server.
;;
;; STUN/TURN are needed only when the media server sits behind a NAT and needs to
;; find out its own external IP address. However, if you set a static external IP
;; address with this parameter, then there is no need for the STUN/TURN
;; auto-discovery.
;;
;; The effect of this parameter is that ALL local ICE candidates that are
;; gathered (for WebRTC) will contain the provided external IP address instead of
;; the local one.
;;
;; <externalAddress> is an IPv4 or IPv6 address.
;;
;; Examples:
;; externalAddress=10.20.30.40
;; externalAddress=2001:0db8:85a3:0000:0000:8a2e:0370:7334
;;
;externalAddress=PUBLIC IP ADDRESS

;; Local network interfaces used for ICE gathering.
;;
;; If you know which network interfaces should be used to perform ICE (for
;; WebRTC connectivity), you can define them here. Doing so has several
;; advantages:
;;
;; * The WebRTC ICE gathering process will be much quicker. Normally, it needs
;;   to gather local candidates for all of the network interfaces, but this step
;;   can be made faster if you limit it to only the interface that you know will
;;   work.
;;
;; * It will ensure that the media server always decides to use the correct
;;   network interface. With WebRTC ICE gathering it's possible that, under some
;;   circumstances (in systems with virtual network interfaces such as
;;   "docker0") the ICE process ends up choosing the wrong local IP.
;;
;; <networkInterfaces> is a comma-separated list of network interface names.
;;
;; Examples:
;; networkInterfaces=eth0
;; networkInterfaces=eth0,enp0s25
;;
;networkInterfaces=eth0

;; STUN server IP address.
;;
;; The ICE process uses STUN to punch holes through NAT firewalls.
;;
;; <stunServerAddress> MUST be an IP address; domain names are NOT supported.
;;
;; You need to use a well-working STUN server. Use this to check if it works:
;; https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/
;;
;; From that check, you should get at least one Server-Reflexive Candidate
;; (type "srflx").
;;
;; Personal stun/turn server(stun not reaching it, producing errors)
;;stunServerAddress=XXX.XXX.XXX.XXX
;;stunServerPort=3478

;;Public stun server 
stunServerAddress=203.183.172.196
stunServerPort=3478
;; TURN server URL.
;;
;; When STUN is not enough to open connections through some NAT firewalls,
;; using TURN is the remaining alternative.
;;
;; Note that TURN is a superset of STUN, so you don't need to configure STUN
;; if you are using TURN.
;;
;; The provided URL should follow one of these formats:
;;
;;   * user:password@ipaddress:port
;;   * user:password@ipaddress:port?transport=[udp|tcp|tls]
;;
;; <ipaddress> MUST be an IP address; domain names are NOT supported.
;; <transport> is OPTIONAL. Possible values: udp, tcp, tls. Default: udp.
;;
;; You need to use a well-working TURN server. Use this to check if it works:
;; https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/
;;
;; From that check, you should get at least one Server-Reflexive Candidate
;; (type "srflx") AND one Relay Candidate (type "relay").
;;
;turnURL=user:password@127.0.0.1:3478?transport=udp

;pemCertificate is deprecated. Please use pemCertificateRSA instead
;pemCertificate=<path>
;pemCertificateRSA=<path>
;pemCertificateECDSA=<path>

**If possible, and this is the most important, reproduce the issue in either Chrome or Firefox and get Chrome's chrome://webrtc-internals or Firefox about:webrtc dump.**

Can't reproduce the issue on Chrome. Only occurs in Safari. Sorry.

**Comment by agustinmono** [comment]
Did you solve the issue? How?
I have the same problem

**Comment by krowdlearn** [comment]
Same issue here.

**Comment by basisbit** [comment]
This issue can usually be solved by installing a TURN+STUN server. See https://docs.bigbluebutton.org/2.2/setup-turn-server.html

**Comment by swap83** [comment]
we have same problem with carrier operator.
TIM work!
Wind/Vodafone doesn't work!!

**Comment by SimonSoftware** [comment]
Me too, with Fastweb all is ok, Wind/Vodafone doesn't work! On thursday Jul 2 all is ok, but from friday 3 all is blocked.

**Comment by basisbit** [comment]
What does https://test.webrtc.org show? Please post a screenshot.

**Comment by SimonSoftware** [comment]
I'm on Fastweb (IT), all is ok. With Wind/Vodafone 1020 error but the audio is ok.
[testrtc-2020-07-06T06_31_49.605Z.log](https://github.com/bigbluebutton/bigbluebutton/files/4877121/testrtc-2020-07-06T06_31_49.605Z.log)
<img width="550" alt="Schermata 2020-07-06 alle 08 31 05" src="https://user-images.githubusercontent.com/6181879/86562590-3b8d3980-bf63-11ea-96a4-1000d3d95d9a.png">

**Comment by swap83** [comment]
Problem with stun server on documentation! The IP SERVER On installation documentation doesn’t work! Now we use a google stun server

Scarica Outlook per iOS<https://aka.ms/o0ukef>
________________________________
Da: Paolo <notifications@github.com>
Inviato: Monday, July 6, 2020 8:18:59 AM
A: bigbluebutton/bigbluebutton <bigbluebutton@noreply.github.com>
Cc: swap83 <swap83@msn.com>; Comment <comment@noreply.github.com>
Oggetto: Re: [bigbluebutton/bigbluebutton] 1020 media could not reach the server (#9021)


Me too, with Fastweb all is ok, Wind/Vodafone doesn't work! On thursday Jul 2 all is ok, but from friday 3 all is blocked.

**Comment by basisbit** [comment]
@swap83 which `IP SERVER` are you referring to? You mean `turn.example.com`? If yes, well, duh, you have to set up your own system and put that in there. Google stun server does not do TURN / TURNS for you.

**Comment by ffdixon** [comment]
See

  https://groups.google.com/g/bigbluebutton-setup/c/952i2nF05GY/m/5ncdHCDPAQAJ

**Comment by promisan** [comment]
> Same issue here.

I think the issue @Salamit was facing is/was related to this : https://groups.google.com/forum/#!msg/bigbluebutton-setup/952i2nF05GY/es5I7dEfBgAJ. Refer to the Turn port TCP (not only UDP) to be open.
