### ISSUE TITLE
freeswitch use More than 200% in my bigbluebutton server

### ISSUE THREAD

**Issue by TivanDev** [bigbluebutton/bigbluebutton#9023]
![Untitled](https://user-images.githubusercontent.com/6270065/78875270-dfe60980-7a62-11ea-8df8-ba8300161a74.png)
this is my ubuntu monitor
but my freeswitch service mostly use more than 200% of cpu and my server hang on
please help me

**Comment by jibon57** [comment]
You haven't mentioned the number of users are using BBB at that time. Also how many core do you have? From load average `1.11, 0.97, 1.02` doesn't look like it's overloaded.

**Comment by TivanDev** [comment]
i have 60 user in 3 meeting and this is my server configuration :
8 core CPU
32 GB RAM

**Comment by defnull** [comment]
Your server is 77% idle. CPU and RAM usage is fine. Perhaps you are hitting a bandwidth limit?

**Comment by TivanDev** [comment]
> Your server is 77% idle. CPU and RAM usage is fine. Perhaps you are hitting a bandwidth limit?

no my server now use 300% of my cpu

**Comment by defnull** [comment]
You have 8 cores. 300% CPU usage means only 3 of them are busy, and 5 are still idling. 
Look at the normalized values in line three. 77.8% idle.

**Comment by TivanDev** [comment]
![1](https://user-images.githubusercontent.com/6270065/78890076-37dc3a80-7a7a-11ea-98af-9e82eacb8453.png)
this my server monitoring

**Comment by jibon57** [comment]
Still you have 75.3% ideal. Press `1` when open `top`. You'll get your full CPU process list.

**Comment by TivanDev** [comment]
![Capture](https://user-images.githubusercontent.com/6270065/78890497-044de000-7a7b-11ea-87d9-e28270a9bf81.JPG)
thanks for your response 
but my freeswitch use 337.1% of my cpu

**Comment by TivanDev** [comment]
![2](https://user-images.githubusercontent.com/6270065/78890631-3eb77d00-7a7b-11ea-9048-427260a23c7e.JPG)
this is my datacenter cpu usage report

**Comment by jibon57** [comment]
I can't see anything serious. Looks OK for me.

**Comment by TivanDev** [comment]
> I can't see anything serious. Looks OK for me.

so this 337.1% cpu usage and datacenter cpu usage is normal ?

**Comment by defnull** [comment]
Again, you have 8 CPU Cores. The usage can go up to 800%.

**Comment by TivanDev** [comment]
ok thank you man

**Comment by mailalaki** [comment]
in top command, use SHIFT+i

**Comment by ziegenberg** [comment]
imho: this can be closed as a non-issue
