### ISSUE TITLE
fixed docker-compose file to build BBB, but bbb-web does not start properly

### ISSUE THREAD

**Issue by MaxEmanuel** [bigbluebutton/bigbluebutton#9026]
forked the repository of tauu and fixed some addresses: [dockerfile-fix](https://github.com/MaxEmanuel/bigbluebutton/tree/dockerfile-fix)
now, creating the docker images is possible, but `docker-compose up` does not start properly as I cannot open the start page (`404 page not found`) and bbb-web throws an error:
`2020-04-09T18:34:08.961Z ERROR o.a.tomcat.jdbc.pool.ConnectionPool - Unable to create initial connections of pool.
java.sql.SQLException: org.h2.Driver at org.apache.tomcat.jdbc.pool.PooledConnection.connectUsingDriver(PooledConnection.java:254)`

`cd labs/docker && docker-compose up`

Thanks in advance for help or double-checking dockerfile-fix pull request ! :)

**Comment by hoang000147** [comment]
Did you find a way to solve this problem?

**Comment by MaxEmanuel** [comment]
Sorry, but I couldn't. I tried also another pull request: https://github.com/bigbluebutton/bigbluebutton/pull/8858
but it didn't work neither. The most promising approach so far was:
https://github.com/bigbluebutton/docker/pull/43

**Comment by Rqfc** [comment]
I have the same problem. Have you been able to solve it?

**Comment by prlanzarin** [comment]
Stale. https://github.com/bigbluebutton/docker for up-to-date docker stuff.
