### ISSUE TITLE
Shared notes desappear

### ISSUE THREAD

**Issue by agustinmono** [bigbluebutton/bigbluebutton#9027]
I have 2 servers working behind firewall and scalelite, but for some reason one of them is not showing the Notes!

I really dont know why, no errors shown anywere

http://prntscr.com/rwc3k9

config its ok
http://prntscr.com/rwc51q

`BigBlueButton Server 2.2.3 (1833)
                    Kernel version: 4.4.0-142-generic
                      Distribution: Ubuntu 16.04.6 LTS (64-bit)
                            Memory: 16431 MB
                         CPU cores: 8

/usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties (bbb-web)
       bigbluebutton.web.serverURL: https://franciscanitos.ofmperu.com
                defaultGuestPolicy: ALWAYS_ACCEPT
                 svgImagesRequired: true

/etc/nginx/sites-available/bigbluebutton (nginx)
                       server name: franciscanitos.ofmperu.com
                              port: 80, [::]:80
                              port: 443 ssl
                    bbb-client dir: /var/www/bigbluebutton

/var/www/bigbluebutton/client/conf/config.xml (bbb-client)
                Port test (tunnel): rtmp://franciscanitos.ofmperu.com
                              red5: franciscanitos.ofmperu.com
              useWebrtcIfAvailable: true

/opt/freeswitch/etc/freeswitch/vars.xml (FreeSWITCH)
                       local_ip_v4: 217.79.240.35
                   external_rtp_ip: 217.79.240.35
                   external_sip_ip: 217.79.240.35

/opt/freeswitch/etc/freeswitch/sip_profiles/external.xml (FreeSWITCH)
                        ext-rtp-ip: $${external_rtp_ip}
                        ext-sip-ip: $${external_sip_ip}
                        ws-binding: :5066
                       wss-binding: 217.79.240.35:7443

/usr/local/bigbluebutton/core/scripts/bigbluebutton.yml (record and playback)
                     playback_host: franciscanitos.ofmperu.com
                 playback_protocol: https
                            ffmpeg: 4.2.2-1bbb1~ubuntu16.04

/etc/bigbluebutton/nginx/sip.nginx (sip.nginx)
                        proxy_pass: 217.79.240.35

/usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml (Kurento SFU)
                        kurento.ip: 217.79.240.35
                       kurento.url: ws://127.0.0.1:8888/kurento
                    localIpAddress: 217.79.240.35
               recordScreenSharing: true
                     recordWebcams: true
                  codec_video_main: VP8
               codec_video_content: VP8

/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml (HTML5 client)
                             build: 870
                        kurentoUrl: wss://franciscanitos.ofmperu.com/bbb-webrtc-sfu
                  enableListenOnly: true`

**Comment by pedrobmarin** [comment]
You could try as @hostbbb suggested here https://groups.google.com/forum/#!msg/bigbluebutton-dev/3sS-GL4R8Ic/ZAPcznOLEQAJ

**Comment by agustinmono** [comment]
Awesome @pedrobmarin  but where can i locate that API KEY ?

**Comment by agustinmono** [comment]
I found the api key

nano /usr/share/etherpad-lite/APIKEY.txt

buit its the same as here

nano /usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml

How can i generate a new one??

**Comment by pedrobmarin** [comment]
Delete the current API key file and restart etherpad's systemd service

Em qui, 9 de abr de 2020 21:29, agustinmono <notifications@github.com>
escreveu:

**Comment by agustinmono** [comment]
Now it works
thanks a lot!

**Comment by Salamit** [comment]
@pedrobmarin Hi, how do you restart etherpad's systemd service?

**Comment by pedrobmarin** [comment]
sudo systemctl restart etherpad

Em seg, 4 de mai de 2020 05:33, T.Salami <notifications@github.com>
escreveu:

**Comment by Salamit** [comment]
@pedrobmarin Thanks a million. 

I tried changing the api key and restarting but shared notes still isn't showing. :(

**Comment by Salamit** [comment]
I see this error. Please see the pdf below. 
[sharedNotes.log.pdf](https://github.com/bigbluebutton/bigbluebutton/files/4574840/sharedNotes.log.pdf)

**Comment by pedrobmarin** [comment]
@Salamit I'm not sure what's the issue. You are not able to see the shared notes item at the HTML5 client user's list? If thats the problem, make sure Etherpad API KEY matches HTML5 client's settings at `/usr/share/meteor/bundle/programs/server/app/assets/config`. You will also need to restart the html5 client service if anything changed at it's settings file
`sudo systemctl restart bbb-html5`
After that, try creating a new meeting

**Comment by Salamit** [comment]
@pedrobmarin you said settings file in  /usr/share/meteor/bundle/programs/server/**app/assets**/config

Do you mean
/usr/share/meteor/bundle/programs/server/**assets/app**/config/settings.yml ? (I found this:  ```
etherpad:
    apikey: **ETHERPAD_APIKEY** <=== API key was written like that. I will switch for my api key. 
```

**Comment by Salamit** [comment]
I did the following 

```
etherpad:
       apikey: XXXXXXXXXXXXXXXXXXXXXXX  (I replaced XXXXXXXXXXXXXXXXXXXXXXX with my api key found here: /usr/share/etherpad-lite/APIKEY.txt"
```

I tried it and it didn't work.

**Comment by pedrobmarin** [comment]
> you said settings file in /usr/share/meteor/bundle/programs/server/**app/assets**/config
> 
> Do you mean
> /usr/share/meteor/bundle/programs/server/**assets/app**/config/settings.yml ?

Yeah, that's the one, sry.

Are your notes enabled at the same `settings.yml` file? If you are running the correct API_KEY with `notes` settings enabled I can't see what could be the issue here. The next thing I would try finding is warning or error messages at the HTML5 client log (`/var/log/syslog`). Try finding something like:
`Could not get note` or `Could not create note`

**Comment by Salamit** [comment]
Thank you @pedrobmarin and no worries.

I took a look at `/var/log/syslog`

and saw this line of interest : 

`May  4 08:17:56 ip-172-31-23-70 systemd_start.sh[12950]: #033[33mwarn#033[39m: Notes are disabled for 3c34a0fe9785d4ca2ca1e2d9f154e48e7f7649ce-1588580275806`

**Comment by Salamit** [comment]
I saw that notes was disabled in my settings.yml file. I will change 
```
note:
    enabled: false <=== will change this to true
    url: ETHERPAD_HOST
    config:
      showLineNumbers: false
```

**Comment by agustinmono** [comment]
> I tried it and it didn't work.
> 
> I did the following
> 
> ```
> etherpad:
>        apikey: XXXXXXXXXXXXXXXXXXXXXXX  (I replaced XXXXXXXXXXXXXXXXXXXXXXX with my api key found here: /usr/share/etherpad-lite/APIKEY.txt"
> ```

Did you restarted Bigbluebutton after that change?
try with

`bbb-conf --clean`

Check
https://docs.bigbluebutton.org/admin/bbb-conf.html#options

**Comment by Salamit** [comment]
@pedrobmarin @agustinmono 

Thanks a million. It worked. I hope this helps someone out there.

**Comment by Salamit** [comment]
@pedrobmarin @agustinmono 

Sorry. More problems. Now this happens. 

![IMG_2416](https://user-images.githubusercontent.com/12544262/80990782-e6a14a00-8e71-11ea-9bed-fed043e0826a.jpg)

**Comment by Salamit** [comment]
Okay, I fixed it.

I ran `bbb-conf --setip <HOSTNAME HERE>`

**Comment by basisbit** [comment]
All the mentioned issues were resolved. Closing this issue now.
