### ISSUE TITLE
Installing BBB on VM with no SSL

### ISSUE THREAD

**Issue by Patira** [bigbluebutton/bigbluebutton#9029]
**Describe the bug**

I installed Ubuntu 16.04 on VMWare fusion (mac) and then installed the BBB through bbb-install bash script, and I got a local IP address at the end, but obviously I can't apply SSL on that. So how can I run BBB on a dev environment with SSL so that I can have access to microphone and webcam?

**Installation type**
Did you install manually or did you use the bbb-install script?

bbb-install

**Additional context**

In the documentation for development, there is this note:

> We emphasize that your BigBlueButton server must be working before you start setting up the development environment. Be sure that you can login, start sessions, join the audio bridge, share your webcam, and record and playback sessions – all using the built-in API demos.

Now I can log in, and start a session, but I can't join the audio bridge, share my webcam, and any other HTML5 API related thing that requires SSL.

**Comment by Patira** [comment]
I tried a self-signed certificate on the local IP and it kinda did work, but still, there are problems!

I can open the ```/demo/demo1.jsp``` endpoint, but after I enter my full name, I redirect to the following endpoint:

```/demo/demo1.jsp?username=Patira&action=create```

and I get a page with the title **An Error has occured:** with the status code of 500.

Now I think it's because of the self-signed certificate that I have, and I think tomcat can't handle that, but I'm not quite sure about that.

I've tried this command too:

```wget https://192.168.70.130/default.pdf```

I couldn't download the PDF file, so I used the following flag along with the mentioned command:

```--no-check-certificate```

and this time, no surprise, it worked and I could download the PDF file.

Here's the result of my ```bbb-conf --check```:

```
BigBlueButton Server 2.2.4 (1846)
                    Kernel version: 4.15.0-45-generic
                      Distribution: Ubuntu 16.04.6 LTS (64-bit)
                            Memory: 4015 MB
                         CPU cores: 4

/usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties (bbb-web)
       bigbluebutton.web.serverURL: https://192.168.70.130
                defaultGuestPolicy: ALWAYS_ACCEPT
                 svgImagesRequired: true

/etc/nginx/sites-available/bigbluebutton (nginx)
                       server name: 192.168.70.130
                              port: 80, [::]:80
                              port: 443 ssl
                    bbb-client dir: /var/www/bigbluebutton

/var/www/bigbluebutton/client/conf/config.xml (bbb-client)
                Port test (tunnel): rtmp://192.168.70.130
                              red5: 192.168.70.130
              useWebrtcIfAvailable: true

/opt/freeswitch/etc/freeswitch/vars.xml (FreeSWITCH)
                       local_ip_v4: 192.168.70.130
                   external_rtp_ip: stun:stun.freeswitch.org
                   external_sip_ip: stun:stun.freeswitch.org

/opt/freeswitch/etc/freeswitch/sip_profiles/external.xml (FreeSWITCH)
                        ext-rtp-ip: $${local_ip_v4}
                        ext-sip-ip: $${local_ip_v4}
                        ws-binding: :5066
                       wss-binding: :7443

/usr/local/bigbluebutton/core/scripts/bigbluebutton.yml (record and playback)
                     playback_host: 192.168.70.130
                 playback_protocol: https
                            ffmpeg: 4.2.2-1bbb1~ubuntu16.04

/etc/bigbluebutton/nginx/sip.nginx (sip.nginx)
                        proxy_pass: 192.168.70.130

/usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml (Kurento SFU)
                        kurento.ip: 192.168.70.130
                       kurento.url: ws://127.0.0.1:8888/kurento
                    localIpAddress: 192.168.70.130
               recordScreenSharing: true
                     recordWebcams: true
                  codec_video_main: VP8
               codec_video_content: VP8

/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml (HTML5 client)
                             build: 873
                        kurentoUrl: wss://192.168.70.130/bbb-webrtc-sfu
                  enableListenOnly: true


# Potential problems described below
................................................................................
# Error: Could not connect to the configured hostname/IP address
#
#    https://192.168.70.130/
#
# If your BigBlueButton server is behind a firewall, see FAQ.

# Warning: The API demos are installed and accessible from:
#
#    https://192.168.70.130
#
# and
#
#    https://192.168.70.130/demo/demo1.jsp
#
# These API demos allow anyone to access your server without authentication
# to create/manage meetings and recordings. They are for testing purposes only.
# If you are running a production system, remove them by running:
#
#    apt-get purge bbb-demo

# Error: Unable to reach default URL for presentation:
#
#    https://192.168.70.130/default.pdf
#
# Check value for beans.presentationService.defaultUploadedPresentation in
#   /usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties
```

**I still don't know how to start this project in a dev environment without the need for a public domain name, and a public IP address.**

**Comment by weeman1337** [comment]
Facing the same problem. There should be an option to disable certificate checks for development.

**Comment by weeman1337** [comment]
Maybe this could be the solution:
```
cp self-signed.crt /usr/share/ca-certificates
dpkg-reconfigure ca-certificate
```
It would be nice to see that in the dev docs somewhere.

**Comment by laughing2** [comment]
apt-get purge bbb-demo
apt-get install bbb-demo

open. https://127.0.0.1 is ok.
