### ISSUE TITLE
Randomly disconnections of meeting members when meeting is recording

### ISSUE THREAD

**Issue by tvitas** [bigbluebutton/bigbluebutton#9030]
**Describe the bug**
Strange beahavior of BBB running behind scalelite balancer:
if meeting is running with recording, some meeting members (often moderator)  is randomly disconnected from it. No errors in log.
**To Reproduce**
Create meeting
Join
Record
Ups - disconnect
Connect (join)  again

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome or FireFox

**Comment by basisbit** [comment]
Could you please monitor CPU usage and network connection quality when reproducing this issue? Also, what does the console log of your webbrowser developer tool (press F12 in chrome) show when that problem is happening?

Pressing the recording button in the web interface only sets the marker for where to start/stop processing of the recorded session, so that should not cause the client to reconnect.

**Comment by ffdixon** [comment]
@tvitas Can you reproduce this on https://demo.bigbluebutton.org/?

**Comment by tvitas** [comment]
@basisbit CPU and network load on which side? Client (browser) or bbbserver?

**Comment by tvitas** [comment]
After lot of debuging, our team thinks, where is maybe webrtc protocol issue, based on turn server selection. But why this happened only to our organisation?

**Comment by Mohavior** [comment]
i am working together with tvitas and I can tell you more details about when it happens.

Bug reproducing site:
Affected OS so far: Windows, MAC, (Linux currently testing).
Affected browsers: Chrome, Firefox, Safari (didin't tested more).
Affected network type: LAN,  WLAN and VPN.
Time is kinda random 6-30 min.
Tested routers: TL-WR1043ND (affected), di-524 (affected), pfsense (not affected so far).

What happens?

For testing I did it with 2-3 users in room, after sharing screen or painting on white board either one person gets removed from room or two. 
At the moment I am running with 5 users (all of them is me) 4 located at home and one remote in office. TP-Link And Dlink routers computers got removed from session.

Below is a fragment (client: mac, safari) of a wireshark log when client disconnects
![wireshark](https://user-images.githubusercontent.com/63591015/79120092-aaab2580-7d9a-11ea-8fd4-56d856502513.png)

I am gona make you more logs and scenario explanations when I'll finish more testing.

**Comment by basisbit** [comment]
Could you please provide the console output from your webbrowsers developer tools (press F12 to open in chrome) - that should help us understand what is happening when the users disconnect

**Comment by Mohavior** [comment]
Okay, gona repeat the process and wait for F12 log then post it.

**Comment by Mohavior** [comment]
[chrome console censored.log](https://github.com/bigbluebutton/bigbluebutton/files/4469579/chrome.console.censored.log)

happened in about ~17 minutes

**Comment by Mohavior** [comment]
[chrome console censored.log](https://github.com/bigbluebutton/bigbluebutton/files/4469595/chrome.console.censored.log)

happened in about 17 minutes

**Comment by Mohavior** [comment]
Got 3 more disconnects and it seems that it is related to computers that are using microphones. Hm??? Other ones that were just watching stream (shared screen) were not affected. 

Now trying to use microphones on other computers to see results.

**Comment by Mohavior** [comment]
Even linux+firefox with microphone got kicked in like 1 minute.

**Comment by basisbit** [comment]
is the bbb server or the stun/turn server behind a firewall which might have issues with secure websocket or UDP connections?

**Comment by texh2s00** [comment]
Hi there no. No FW. Direct output to internet.

**Comment by Mohavior** [comment]
[presenter_screenshare_5users.log](https://github.com/bigbluebutton/bigbluebutton/files/4469762/presenter_screenshare_5users.log)

Different log. Might help.

**Comment by basisbit** [comment]
could you change back the turn/stun server address back to bbb default and see if that fixes the problem for you?

**Comment by Mohavior** [comment]
We added STUN/TURN server because of this problem, we thought that it might help, but it didin't.. I have to mention that we have BBB load balancer Scalelite from blindsidenetworks. Could that have any impact?

**Comment by Mohavior** [comment]
Tomorrow we will double check our path from server to outside if there are any issues and report back to you. Thanks for helping :)

**Comment by texh2s00** [comment]
@basisbit - actualy, 4 weeks ago we had 2.0 BBB version. Before cuarantine updated to 2.3 and whant things started. As for first point we had one server ant it started to crash actualy we didn't looked at disconnection issues. After LoadBalancing now we have 6 BBB servers, with totaly same config. Couping quite alot sessions and people. And know issues of being disconected started to show up more as more users are being kicked out. The kick out time totaly varies. for some 8-10 minutes, for others 20-25 minutes. Actualy we have god some pattern, than one client with quite weak internet connections kicks out in 8 minutes ar takes all whom was mic enabled from the session as well. All serves connected directy to L2 Network. Static IP's. By browsing in forums, we installed TURN/STUN server. Changed config. But no help.

**Comment by basisbit** [comment]
To figure out the problem, I'd suggest you to set up bbb + greenlight on another vanilla ubuntu 16.04 in the same network using the bbb-install script. Then you can try to reproduce the problem. It it happens, then the environment or the clients might be the source of the problem. If the problem can not be reproduced, try applying your custom changes step by step until the problem can be reproduced. This should allow you to figure out what change introduces the problem.

If the problem happens even with the fresh install using plain ubuntu 16.04 (+ updates installed) plus bbb-install, then please test if you can reproduce the problem on another public instance of bbb, for example https://meeten.statt-drosseln.de/b or https://yolo-bbb.starletp9.de/b to figure out if the problem is caused by server configuration/network or client configuration/network

**Comment by texh2s00** [comment]
Well actually all nodes are fresh install. On 16.04 + TLS. From bbb-install.sh
Only custom settings: 
defaultMaxUsers=48
defaultMeetingDuration=0
maxInactivityTimeoutMinutes=90
clientLogoutTimerInMinutes=70
warnMinutesBeforeMax=5
meetingExpireIfNoUserJoinedInMinutes=35
meetingExpireWhenLastUserLeftInMinutes=5
userInactivityInspectTimerInMinutes=10
userInactivityThresholdInMinutes=50
userActivitySignResponseDelayInMinutes=5

And Yes it happens not for all users. Sometimes VPN helps. can it be related to p2p connectivity? If yes maiby we can use something else?

**Comment by texh2s00** [comment]
UPDATE:
Seems like issue is here: 
When in meeting recording is started. WEB cam share or screen share or whiteboard. From client side reconnecting from source to server takes more than 1-2 seconds. SFU gets AbortError, whats for: "The time of a video element is adjusted."
 And than gracefully logouts client from session.

**Comment by tvitas** [comment]
The issue appears to have been resolved by upgrading to version 2.2.5 and fresh installation of all BBB nodes.
But what reason was for the issue?
