### ISSUE TITLE
Download presentation file error

### ISSUE THREAD

**Issue by heavenknows1978** [bigbluebutton/bigbluebutton#9031]
Dear Sir/Madam

I install latest BBB version with html5 clien, after user enter a room and download the presentation file at bottom left corner , the browser return error 404 as image.

Can you help me on this bug, my server publish to internet, server behind NAT and all function working well. 
![image](https://user-images.githubusercontent.com/34310938/78972107-3290f580-7b37-11ea-9a2c-659e44794d07.png)
![image](https://user-images.githubusercontent.com/34310938/78972119-391f6d00-7b37-11ea-8b4c-0449f6d43a28.png)

**Comment by scaredmushroom** [comment]
I have the same issue:

### Bug description:
When I click on the "Download"-Icon of a presentation a new tab opens with an "404 Not Found" Error.

### Steps to reproduce:
1. Install BBB on Ubuntu 16.4 with bbb-setup.sh
2. Create admin account and login
3. Create room and join
4. Upload PDF and mark it downloadable
5. Click on the "Download"-Icon

### Expected behavior
The PDF gets downloaded.

Since I'm not sure how to debug this problem properly pleas instruct me to do so.
I would be glad to fix this problem.
I haven't noticed any other errors.

**Comment by jdepi** [comment]
Hi all,
I have got the same issue with bbb 2.2.4. 
In 2.2.3 it worked well.

**Comment by ffdixon** [comment]
Good catch -- it's a regression that we introduced BigBlueButton 2.2.4.  Look for the release shortly of 2.2.5 with a fix.

**Comment by heavenknows1978** [comment]
> Good catch -- it's a regression that we introduced BigBlueButton 2.2.4. Look for the release shortly of 2.2.5 with a fix.

Dear Brother, please add an option that allow administrator disable /enable presentation file download because of security policy of different org.

Thanks

**Comment by jibon57** [comment]
@heavenknows1978 this feature already there. During upload you can set whether user be able to download or not

**Comment by heavenknows1978** [comment]
> @heavenknows1978 this feature already there. During upload you can set whether user be able to download or not

Dear Brother
that option is for room owner and controlled by them, I think that BBB should  has an option for site admin to disable /enable this function so one can allow presentation file file download .
It's ok that site admin can set this enable/disable on each room and can set default enable/disable for BBB
Thanks bro

**Comment by heavenknows1978** [comment]
> Good catch -- it's a regression that we introduced BigBlueButton 2.2.4. Look for the release shortly of 2.2.5 with a fix.

Dear Brother
Today my server automatic update new bbb-html5 client and this bug fixed.
But can your team add an option for site admin to disable room owner to allow other user download presentation file? this is very important for security policies.

Thanks

**Comment by flipreverse** [comment]
Has this fix been pushed to the Ubuntu repository?

`Package: bbb-html5                       
New: yes
State: installed
Automatically installed: no
Version: 1:2.2.0-874
Priority: extra
Section: default
Maintainer: ffdixon@bigbluebutton.org
Architecture: amd64
Uncompressed Size: 141 M
Depends: bbb-webrtc-sfu, bbb-apps-video-broadcast, yq, bbb-etherpad
Description: The HTML5 components for BigBlueButton`

**Comment by uft-dti** [comment]
I install 2.2.9 update and now fail to download presentation show 404 error

**Comment by vidukapoor** [comment]
hi team, i am facing the same 404 error issue, 
made a custom branch from https://github.com/bigbluebutton/bigbluebutton/commit/c69c891cf1b6aa37a4d145072185776f2b8bfc82

seems link generation part is wrong
https://github.com/bigbluebutton/bigbluebutton/blob/c69c891cf1b6aa37a4d145072185776f2b8bfc82/bigbluebutton-html5/imports/ui/components/presentation/service.js#L13

**Comment by basisbit** [comment]
@vidukapoor can you reproduce this on https://test.bigbluebutton.org ?

**Comment by vidukapoor** [comment]
hi @basisbit i updated the server with 82e9fd15267a468e3fa3070719fec6b2d7162e05, its working fine now.
