### ISSUE TITLE
Client screenshare

### ISSUE THREAD

**Issue by ShiftyMLG** [bigbluebutton/bigbluebutton#9032]
**Is your feature request related to a problem? Please describe.**
It is really annoying that my colleagues can’t share their screen with me. This platform performs almost perfectly, but this is the 1 feature that I al missing to make it a standard across the whole company...

**Describe the solution you'd like**
I would like the possibility that clients can also share their screen, possibly after the host has enables this for the room.

**Comment by mamhoff** [comment]
@ShiftyMLG Your colleagues CAN share their screen with you. You can give make them presenters without giving them moderator rights, and then they can. 

However, screensharing only works on Firefox and Chrome and does NOT work on Safari. So your colleagues might be using Firefox. Here's a quick video demonstration: 


![guest-screenshare](https://user-images.githubusercontent.com/703401/79040942-4d717180-7bec-11ea-80aa-1750118847c4.gif)
