### ISSUE TITLE
Cron Job doesn't delete recordings

### ISSUE THREAD

**Issue by aletherian** [bigbluebutton/bigbluebutton#9033]
Hey, guys.

I have followed all the instructions in docs.bugbluebutton to set deletion of data and recordings.
I set the following:
`history=1
unrecorded_days=1
published_days=1
log_history=1
`

I also added: 'bbb-recording-cleanup' and 'delete-old-recordings' with codes from the instruction to /etc/cron.daily/ with MAXAGE=1.

It doesn't delete anything after 1 day. Could you help me with that? Thank you so much in advance!!!

**Comment by schmidf** [comment]
Did you check the logfile in ```/var/log/bigbluebutton/bbb-recording-cleanup.log``` to see if the script was actually run? Maybe you forgot to make it executable (```chmod +x /etc/cron.daily/bbb-recording-cleanup```).

**Comment by aletherian** [comment]
> Did you check the logfile in `/var/log/bigbluebutton/bbb-recording-cleanup.log` to see if the script was actually run? Maybe you forgot to make it executable (`chmod +x /etc/cron.daily/bbb-recording-cleanup`).

I've seen the logs, it seems it deletes.
I will check it and will get back with it.
Thank you so much!!!
Have a WONDERFUL day/evening (^_^)

**Comment by aletherian** [comment]
Okay. Everything is working now.
Thank you very much, @schmidf!
You are THE BEST (^_^)
