### ISSUE TITLE
installed bbb using bbb-install, site shows demo site only

### ISSUE THREAD

**Issue by xtien** [bigbluebutton/bigbluebutton#9034]
**Describe the bug**
I installed BigBlueButton on a server, but the site only shows a demo site. see bbb.hetnet.org

**Installation type**
 bbb-install script?

**Console output**

root@bbb:~/bbb# wget https://ubuntu.bigbluebutton.org/bbb-install.sh
--2020-04-10 11:14:31--  https://ubuntu.bigbluebutton.org/bbb-install.sh
Resolving ubuntu.bigbluebutton.org (ubuntu.bigbluebutton.org)... 167.99.180.121
Connecting to ubuntu.bigbluebutton.org (ubuntu.bigbluebutton.org)|167.99.180.121|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 36687 (36K) [application/octet-stream]
Saving to: ‘bbb-install.sh’

root@bbb:~/bbb# ./bbb-install.sh -v xenial-220 -s bbb.hetnet.org -e christine@christine.nl 
+ main -v xenial-220 -s bbb.hetnet.org -e christine@christine.nl
+ export DEBIAN_FRONTEND=noninteractive
+ DEBIAN_FRONTEND=noninteractive
+ PACKAGE_REPOSITORY=ubuntu.bigbluebutton.org
+ LETS_ENCRYPT_OPTIONS='--webroot --non-interactive'
+ need_x64
++ uname -m
+ UNAME=x86_64
+ '[' x86_64 '!=' x86_64 ']'
+ builtin getopts hs:r:c:v:e:p:m:lxgtad opt -v xenial-220 -s bbb.hetnet.org -e christine@christine.nl
+ case $opt in
+ VERSION=xenial-220
+ check_version xenial-220
+ egrep -q 'xenial|bionic'
+ echo xenial-220
++ sed 's/-.*//g'
++ echo xenial-220
+ DISTRO=xenial
+ wget -qS --spider https://ubuntu.bigbluebutton.org/xenial-220/dists/bigbluebutton-xenial/Release.gpg
+ check_root
+ '[' 0 '!=' 0 ']'
+ need_pkg apt-transport-https
+ check_root
+ '[' 0 '!=' 0 ']'
+ dpkg -s apt-transport-https
+ grep -q 'BigBlueButton apt-get'
+ apt-key list
+ apt-key add -
+ wget https://ubuntu.bigbluebutton.org/repo/bigbluebutton.asc -O-
--2020-04-10 11:15:34--  https://ubuntu.bigbluebutton.org/repo/bigbluebutton.asc
Resolving ubuntu.bigbluebutton.org (ubuntu.bigbluebutton.org)... 167.99.180.121
Connecting to ubuntu.bigbluebutton.org (ubuntu.bigbluebutton.org)|167.99.180.121|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 3112 (3.0K) [application/octet-stream]
Saving to: ‘STDOUT’

-                                                        100%[==================================================================================================================================>]   3.04K  --.-KB/s    in 0s      

2020-04-10 11:15:34 (243 MB/s) - written to stdout [3112/3112]

OK
+ '[' -f /etc/apt/sources.list.d/bigbluebutton.list ']'
+ echo 'deb https://ubuntu.bigbluebutton.org/xenial-220 bigbluebutton-xenial main'
+ builtin getopts hs:r:c:v:e:p:m:lxgtad opt -v xenial-220 -s bbb.hetnet.org -e christine@christine.nl
+ case $opt in
+ HOST=bbb.hetnet.org
+ '[' bbb.hetnet.org == bbb.example.com ']'
+ check_host bbb.hetnet.org
+ '[' -z '' ']'
+ need_pkg dnsutils apt-transport-https net-tools
+ check_root
+ '[' 0 '!=' 0 ']'
+ dpkg -s dnsutils apt-transport-https net-tools
++ tail -n1
++ grep '^[.0-9]*$'
++ dig +short bbb.hetnet.org
+ DIG_IP=159.89.53.43
+ '[' -z 159.89.53.43 ']'
+ get_IP bbb.hetnet.org
+ '[' '!' -z '' ']'
+ grep -q venet0:0
+ LANG=c
+ ifconfig
++ cut -f1 '-d '
++ hostname -I
+ IP=159.89.53.43
+ '[' -r /sys/devices/virtual/dmi/id/product_uuid ']'
++ head -c 3 /sys/devices/virtual/dmi/id/product_uuid
+ '[' F31 == EC2 ']'
+ '[' -f /var/lib/dhcp/dhclient.eth0.leases ']'
+ '[' -f /run/scw-metadata.cache ']'
+ which dmidecode
+ grep -q Google
+ dmidecode -s bios-vendor
+ '[' '!' -z bbb.hetnet.org ']'
+ need_pkg dnsutils
+ check_root
+ '[' 0 '!=' 0 ']'
+ dpkg -s dnsutils
++ tail -n1
++ grep '^[.0-9]*$'
++ dig +short bbb.hetnet.org @resolver1.opendns.com
+ local external_ip=64.227.18.154
+ '[' '!' -z 64.227.18.154 ']'
+ '[' 159.89.53.43 '!=' 64.227.18.154 ']'
+ which nginx
+ need_pkg netcat-openbsd
+ check_root
+ '[' 0 '!=' 0 ']'
+ dpkg -s netcat-openbsd
+ nc_PID=15122
+ nc -zvw3 64.227.18.154 443
+ nc -l -p 443
+ kill 15122
+ which nginx
./bbb-install.sh: line 386: 15122 Terminated              nc -l -p 443 > /dev/null 2>&1
+ '[' -z 159.89.53.43 ']'
+ '[' 159.89.53.43 '!=' 159.89.53.43 ']'
+ builtin getopts hs:r:c:v:e:p:m:lxgtad opt -v xenial-220 -s bbb.hetnet.org -e christine@christine.nl
+ case $opt in
+ EMAIL=christine@christine.nl
+ '[' christine@christine.nl == info@example.com ']'
+ builtin getopts hs:r:c:v:e:p:m:lxgtad opt -v xenial-220 -s bbb.hetnet.org -e christine@christine.nl
+ check_apache2
+ grep -q apache2-bin
+ dpkg -l
+ '[' '!' -z '' ']'
+ '[' -z xenial-220 ']'
+ '[' -z xenial-220 ']'
+ '[' -z xenial-220 ']'
+ env
LC_PAPER=en_US.UTF-8
LC_ADDRESS=en_US.UTF-8
XDG_SESSION_ID=1
LC_MONETARY=en_US.UTF-8
SHELL=/bin/bash
TERM=xterm-256color
SSH_CLIENT=92.111.76.146 41330 22
LC_NUMERIC=en_US.UTF-8
SSH_TTY=/dev/pts/0
USER=root
LC_TELEPHONE=en_US.UTF-8
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
MAIL=/var/mail/root
LC_IDENTIFICATION=en_US.UTF-8
PWD=/root/bbb
LANG=en_US.UTF-8
LC_MEASUREMENT=en_US.UTF-8
HOME=/root
SHLVL=2
LOGNAME=root
SSH_CONNECTION=92.

console output is too long to paste into this window.

**Comment by xtien** [comment]
root@bbb:/etc/nginx/sites-enabled# bbb-conf -check

BigBlueButton Server 2.2.4 (1846)
                    Kernel version: 4.4.0-177-generic
                      Distribution: Ubuntu 16.04.6 LTS (64-bit)
                            Memory: 8174 MB
                         CPU cores: 4

/usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties (bbb-web)
       bigbluebutton.web.serverURL: https://bbb.hetnet.org
                defaultGuestPolicy: ALWAYS_ACCEPT
                 svgImagesRequired: true

/etc/nginx/sites-available/bigbluebutton (nginx)
                       server name: bbb.hetnet.org
                              port: 
                              port: 443 ssl
                    bbb-client dir: /var/www/bigbluebutton

/var/www/bigbluebutton/client/conf/config.xml (bbb-client)
                Port test (tunnel): rtmp://bbb.hetnet.org
                              red5: bbb.hetnet.org
              useWebrtcIfAvailable: true

/opt/freeswitch/etc/freeswitch/vars.xml (FreeSWITCH)
                       local_ip_v4: 159.89.53.43
                   external_rtp_ip: stun:stun.freeswitch.org
                   external_sip_ip: stun:stun.freeswitch.org

/opt/freeswitch/etc/freeswitch/sip_profiles/external.xml (FreeSWITCH)
                        ext-rtp-ip: $${local_ip_v4}
                        ext-sip-ip: $${local_ip_v4}
                        ws-binding: :5066
                       wss-binding: 159.89.53.43:7443

/usr/local/bigbluebutton/core/scripts/bigbluebutton.yml (record and playback)
                     playback_host: bbb.hetnet.org
                 playback_protocol: https
                            ffmpeg: 4.2.2-1bbb1~ubuntu16.04

/etc/bigbluebutton/nginx/sip.nginx (sip.nginx)
                        proxy_pass: 159.89.53.43

/usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml (Kurento SFU)
                        kurento.ip: 159.89.53.43
                       kurento.url: ws://127.0.0.1:8888/kurento
                    localIpAddress: 159.89.53.43
               recordScreenSharing: true
                     recordWebcams: true
                  codec_video_main: VP8
               codec_video_content: VP8

/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml (HTML5 client)
                             build: 873
                        kurentoUrl: wss://bbb.hetnet.org/bbb-webrtc-sfu
                  enableListenOnly: true


# Potential problems described below

root@bbb:/etc/nginx/sites-enabled#

**Comment by basisbit** [comment]
what exactly is the problem here? As mentioned at the end of the bbb-install script execution, please either install [bbb-demo](https://docs.bigbluebutton.org/2.2/install.html#5-install-api-demos-optional) or greenlight as described [here](https://docs.bigbluebutton.org/greenlight/gl-install.html)

**Comment by xtien** [comment]
I thought that bbb-install.sh would install BigBlueButton for me. I don't want the demo, I want a bbb installation. I didn't see a reference to greenlight in the bbb-isntall script. I don't know what greenlight is.

**Comment by basisbit** [comment]
bbb-install installs the bbb server for you. What frontend you want to use is your choice. The one you mentioned the screenshot of is Greenlight.

**Comment by xtien** [comment]
I have re-installed bbb. If I install greenlight now, can I use my bbb installation for conferencing at a school?

**Comment by xtien** [comment]
right, I have a videoconference and chat and such. I assume I can change screens and adjust login to require a password, and such things. 
Thank you.
