### ISSUE TITLE
Accept self-signed certificates in Greenligth

### ISSUE THREAD

**Issue by sigedav** [bigbluebutton/bigbluebutton#9036]
I have BigBlueButton installed and running over https, but with a self-signed certificate, it cannot be otherwise because it is on a closed network.
when I run:
`docker run --rm --env-file .env bigbluebutton/greenlight:v2 bundle exec rake conf:check`
I get this error:
`Checking environment: Passed`
`Checking Connection: Failed`
`Error connecting to BigBlueButton server - SSL_connect returned = 1 errno = 0 state = SSLv3 read server certificate B: certificate verify failed (unab le to get local issuer certificate)`
I can see that the problem is the self-signed certificate, my question is. How can I make the greenligth certified or make it default?

**Comment by basisbit** [comment]
This here is the issue tracker of the BigBlueButton server software. For Greenlight related issues, please create a support issue in the [Greenlight issue tracker](https://github.com/bigbluebutton/greenlight/issues/) - or even better - ask at the BigBlueButton setup mailing list / forum.
