### ISSUE TITLE
breakout rooms not working after upgrade 873

### ISSUE THREAD

**Issue by elemhsb** [bigbluebutton/bigbluebutton#9037]
**Describe the bug**
Breakout rooms not working after update 873
- Homepage /b is shown in browser tab not the breakout room

**To Reproduce**
- upgrade from 870 to 873 breaks breakout rooms 

- Upgraded to these updates:

The following packages will be upgraded:
  bbb-config [1:2.2.0-170 -> 1:2.2.0-171]  bbb-html5 [1:2.2.0-870 -> 1:2.2.0-873]  
  bbb-record-core [1:2.2.0-62 -> 1:2.2.0-63]  bbb-web [1:2.2.0-117 -> 1:2.2.0-119]  
  bbb-webrtc-sfu [1:2.2.0-93 -> 1:2.2.0-99]  
5 packages upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

- Test breakout rooms

**Expected behavior**
- Breakout rooms should run and browser tab point to them

**Actual behavior**
- Breakout rooms not show, only Homepage is in browser tab.

**Screenshots**
no

**Desktop (please complete the following information):**
- Same on all Desktops

**Additional context**

**Comment by elemhsb** [comment]
The issue only exists while **upgrade** the packages on my system.

A **fresh** installation run's fine as expected, so i will close this issue.

**Comment by flyinghuman** [comment]
we have also a problem after upgrade with breakout-rooms:

you can create the rooms and invite people; but they cannot join the rooms due a wrong URL provided. It refers to IP 192.168.23.33/bigbuebutton/api... instead of the real URL DNS-name/bigbluebutton/api....

where can i change this behaviour? must i really reinstall bbb?

**Comment by ffdixon** [comment]
Did you do `bbb-conf --setip` after the upgrade?  See http://docs.bigbluebutton.org/2.2/install.html#upgrading

**Comment by flyinghuman** [comment]
> Did you do `bbb-conf --setip` after the upgrade? See http://docs.bigbluebutton.org/2.2/install.html#upgrading

Thanks a lot, that did the trick. i must remember this.
