### ISSUE TITLE
No microphone work with BigBlueButton Server 2.2.0-beta-21 on iOS 13.1

### ISSUE THREAD

**Issue by TivanDev** [bigbluebutton/bigbluebutton#9039]
dear friend i run BigBlueButton Server 2.2.0-beta-21 on ubuntu 16 
all of platforms such as windows and android work correctly
but in all of ios iphone's microphone not work correctly
please help me

``

**Comment by ffdixon** [comment]
You need to first update to the latest release (which is running on https://demo.bigbluebutton.org).

**Comment by TivanDev** [comment]
thank you ,
how to update to latest version

Sent from Outlook Mobile<https://aka.ms/blhgte>

________________________________

**Comment by basisbit** [comment]
Use bbb-install script or apt update & apt upgrade (see installation instructions from https://docs.bigbluebutton.org/2.2/install.html ). By the way, where did you find the stuff for installing 2.2.0-beta-21?

**Comment by TivanDev** [comment]
I install big blue button from greenlight install and customize html5 language and greenlight, now if update to new version,
Will my changes be deleted?

Sent from Outlook Mobile<https://aka.ms/blhgte>

________________________________

**Comment by basisbit** [comment]
Sadly, yes, many changes will be deleted. See http://docs.bigbluebutton.org/2.2/customize.html#automatically-apply-configuration-changes-on-restart

**Comment by basisbit** [comment]
when using a current version of BBB and this problem still occurs, make sure you correctly installed your stun and turn server, and also check your firewall configuration.
