### ISSUE TITLE
Share an external video / Playback synchronization (instead of video streaming)

### ISSUE THREAD

**Issue by Rafael-Netizen** [bigbluebutton/bigbluebutton#9040]
For certain classroom uses, during video playback, being able to target specific points in time is essential. This can be done using "Share an external video", accessible via the Plus button at the bottom of the screen.

However, this function but it did not work in our tests. Most participants could only see the first few seconds of the video in a loop.

One workaround is using a playback synchronization service along with BBB, like Watch2Gether.com or  Sync-Tube.de. They typically work as follows:

1. The Moderator shares the (Youtube etc.) video URL
2. Every user retrieves the video and plays it back in her or his browser
3. During playback, the only data sent by the Moderator’s computer to the other users consists in short playback commands

However, using those is only a workaround. Improving the "Share an external video" function might contribute to enlarge BBB’s user base.

**Comment by Rafael-Netizen** [comment]
Comment moved to [https://github.com/bigbluebutton/bigbluebutton/issues/8678](url)

**Comment by dbitouze** [comment]
> Thread moved to [https://github.com/bigbluebutton/bigbluebutton/issues/9014](url).
> Another possibly related thread: [https://github.com/bigbluebutton/bigbluebutton/issues/8678](url)

@Nick-Netizen Be careful: wrong links. Should be:
```
Thread moved to https://github.com/bigbluebutton/bigbluebutton/issues/9014.
Another possibly related thread: https://github.com/bigbluebutton/bigbluebutton/issues/8678
```
instead of:
```
Thread moved to [https://github.com/bigbluebutton/bigbluebutton/issues/9014](url).
Another possibly related thread: [https://github.com/bigbluebutton/bigbluebutton/issues/8678](url)
```
