### ISSUE TITLE
Per Room user permissions?

### ISSUE THREAD

**Issue by rory** [bigbluebutton/bigbluebutton#9043]
Is it possible to have per room permissions for users? We have a BBB server (Greenlight v2.5.2), we want it to be "open" to members of our community to use, but for some ("official") rooms we want to have more control. But as far as I can see, all the user permissions can only be set for the entire website.

I'd like each room to have it's own settings about who can join. I want it to be possible for one room to be open to everyone to join, without registration, and for another room to require that users be registered in order to join. Is this possible now?

**Comment by iSamof** [comment]
We have a similar set of requirements. For entry and user management, we are developing our own front end controls. In your case you would have to customise Greenlight. 

Then there are controls that are in the settings and are truly server wide. An example is the recording format of Webm vs MP4. We wish this could be set per room so our presenters could decide which they prefer.

**Comment by matiasilva** [comment]
This is a useful feature worth pursuing, however it doesn't belong here. This should live in https://github.com/bigbluebutton/greenlight or you can start a discussion in the new group: https://groups.google.com/forum/#!forum/bigbluebutton-greenlight

**Comment by stefantruehl** [comment]
Recently we released an alternative BigBlueButton frontend/scaling solution called BBB@Scale. Basically it is combining the features of Greenlight and Scalelite (not using these, but reimplementing their features) + some additional stuff. Finde infos here: https://gitlab.com/bbbatscale/bbbatscale

I feature of the solution is, that rooms have different permissions e.g. everyone is moderator; only the schools teachers are moderators, you may invite extiernal people without a account, and many more settings.

Maybe that is what you are looking for. Feel free to check out the project.
