### ISSUE TITLE
The voice application may not have registered with the sip server.

### ISSUE THREAD

**Issue by TivanDev** [bigbluebutton/bigbluebutton#9044]
i have this error : The voice application may not have registered with the sip server.
this is my bbb-conf --check

`BigBlueButton Server 2.2.0-beta-21 (1473)
                    Kernel version: 4.4.0-165-generic
                      Distribution: Ubuntu 16.04.6 LTS (64-bit)
                            Memory: 32172 MB
                         CPU cores: 8

/usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties (bbb-web)
       bigbluebutton.web.serverURL: https://lms.adakservice.ir
                defaultGuestPolicy: ALWAYS_ACCEPT
                 svgImagesRequired: true

/etc/nginx/sites-available/bigbluebutton (nginx)
                       server name: lms.adakservice.ir
                              port: 80, [::]:80
                              port: 443 ssl
                    bbb-client dir: /var/www/bigbluebutton

/var/www/bigbluebutton/client/conf/config.xml (bbb-client)
                Port test (tunnel): rtmp://lms.adakservice.ir
                              red5: lms.adakservice.ir
              useWebrtcIfAvailable: true

/opt/freeswitch/etc/freeswitch/vars.xml (FreeSWITCH)
                       local_ip_v4: 116.203.137.186
                   external_rtp_ip: stun:stun.freeswitch.org
                   external_sip_ip: stun:stun.freeswitch.org

/opt/freeswitch/etc/freeswitch/sip_profiles/external.xml (FreeSWITCH)
                        ext-rtp-ip: $${local_ip_v4}
                        ext-sip-ip: $${local_ip_v4}
                        ws-binding: :5066
                       wss-binding: 116.203.137.186:7443

/usr/local/bigbluebutton/core/scripts/bigbluebutton.yml (record and playback)
                     playback_host: lms.adakservice.ir
                 playback_protocol: https
                            ffmpeg: 4.1.3-0york1~16.04

/etc/bigbluebutton/nginx/sip.nginx (sip.nginx)
                        proxy_pass: 116.203.137.186

/usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml (Kurento SFU)
                        kurento.ip: 116.203.137.186
                       kurento.url: ws://127.0.0.1:8888/kurento
                    localIpAddress: 116.203.137.186
               recordScreenSharing: true
                     recordWebcams: true
                  codec_video_main: VP8
               codec_video_content: VP8

/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml (HTML5 client)
                             build: 750
                        kurentoUrl: wss://lms.adakservice.ir/bbb-webrtc-sfu
                  enableListenOnly: true

# Potential problems described below
# Warning: The voice application may not have registered with the sip server.
#   Try running:
#
#      bbb-conf --clean
#
`

**Comment by TivanDev** [comment]
when run bbb-conf --clean server hang on bigbluebutton stopping

**Comment by MrCapitalist** [comment]
To solve this problem you can add your server IP to:

`/opt/freeswitch/etc/freeswitch/sip_profiles/external.xml`

where this code presents:
`<param name="wss-binding" value="YOUR_IP_ADDRESS:7443"/>`

**Comment by mrkeksi** [comment]
We also just had the problem for unexplainable reasons. If you wanted to join the conference with a microphone, you only got Error 1004.
But before that we had already entered the IP in WSS-Binding.
What could be the reason for this?

**Comment by ffdixon** [comment]
@mrkeksi What version of BigBlueButton are you running?

**Comment by mrkeksi** [comment]
At that time it was 2.2.10. But we updated to version 2.2.11 tonight. Could it be the old version?

**Comment by jesusvaldivia** [comment]
I have the same issue with 2.2.14, after run `sudo bbb-conf --clean` problem temporarily fixed

**Comment by Davka** [comment]
Same problems with 2.2.14

**Comment by jesusvaldivia** [comment]
this is a random issue, apparently the FreeSWITCH rejects SIP registration requests.

<img width="1210" alt="Screen Shot 2020-05-30 at 12 14 16 AM" src="https://user-images.githubusercontent.com/7368641/83321135-29f19d00-a213-11ea-923f-3bd8362db744.png">

**Comment by basisbit** [comment]
closing this because there was no reply from TivanDev regarding the original issue. For the other problem reports that people posted here, please post your support request in the [forum / mailing list](https://groups.google.com/forum/#!forum/bigbluebutton-setup). This issue tracker is for BigBlueButton development, not for support, sorry. 
@jesusvaldivia regarding freeswitch 1002 occasionally happening, see #9667
