### ISSUE TITLE
Error: Unable to connect to the FreeSWITCH Event Socket Layer on port   8021

### ISSUE THREAD

**Issue by Jessica7015** [bigbluebutton/bigbluebutton#9047]
Olá estou com o seguinte problema de instalação. ao executar o comando "sudo bbb-conf --restart"
BigBlueButton Server 1.1.0 (565)
                    Kernel version: 4.4.0
                      Distribution: Ubuntu 16.04.6 LTS (64-bit)
                            Memory: 1048 MB

/var/www/bigbluebutton/client/conf/config.xml (bbb-client)
                Port test (tunnel): http
                              red5: http
              useWebrtcIfAvailable: true

/opt/freeswitch/etc/freeswitch/sip_profiles/external.xml (FreeSWITCH)
                    websocket port: 5066
                    WebRTC enabled: true

/etc/nginx/sites-available/bigbluebutton (nginx)
                       server name: http
                              port: 80, [::]:80
                    bbb-client dir: /var/www/bigbluebutton

/var/lib/tomcat7/webapps/bigbluebutton/WEB-

INF/classes/bigbluebutton.properties (bbb-web)
                      bbb-web host: http

/usr/share/red5/webapps/bigbluebutton/WEB-INF/red5-web.xml (red5)
                  voice conference: FreeSWITCH

/usr/local/bigbluebutton/core/scripts/bigbluebutton.yml (record and 

playback)
                     playback host: http

** Potential problems described below **
# IP does not match:
#                           IP from ifconfig: 45.132.241.201
#   /etc/nginx/sites-available/bigbluebutton: http

#
# Error: Unable to connect to the FreeSWITCH Event Socket Layer on port 

8021
#
# Warning: The voice application may not have registered with the sip 

server.
#   Try running:
#
#      sudo bbb-conf --clean
#

....................
# Error: Could not connect to the configured hostname/IP address
#
#    http://http/
#
# If your BigBlueButton server is behind a firewall, see FAQ.

nc: getaddrinfo: Name or service not known
# Error: Unable to connect to port 1935 (RTMP) on http

# Error: Could not detect FreeSWITCH listening on port 5060

# Warning: You are running BigBlueButton on a server with less than 4G of 

memory.  Your
# performance may suffer.

# Error: Unable to reach default URL for presentation:
#
#    http://http/default.pdf
#
# Check value for beans.presentationService.defaultUploadedPresentation 

in
#   /var/lib/tomcat7/webapps/bigbluebutton/WEB-

INF/classes/bigbluebutton.properties

**Comment by basisbit** [comment]
How did you install bigbluebutton? You might want to start over and reinstall using the bbb-install.sh script as mentioned here: http://docs.bigbluebutton.org/2.2/install.html#bbb-installsh

**Comment by basisbit** [comment]
closing this because there was no reply and thus I assume the issue was already resolved.

**Comment by Catwoolfii** [comment]
Maybe someone else will come in handy: I got such a problem and in my case the reason was disabled ipv6. I enabled net.ipv6.conf.all.disable_ipv6 system variable and it worked.
