### ISSUE TITLE
Missing source for cron.hourly kurento restart task introduced in 2.2.3

### ISSUE THREAD

**Issue by robbi5** [bigbluebutton/bigbluebutton#9048]
In [Release 2.2.3](https://github.com/bigbluebutton/bigbluebutton/releases/tag/v2.2.3) the following feature was introduced:
> * Added a cron.hourly task to restart Kurento every 24+ hours when the server is idle (no users are connected to BigBlueButton)

In this repository (and others in the bbb github org) the cron.hourly task is nowhere to be found. 

Currently the only way to find out how this works is to manually download the bbb-webrtc-sfu package (https://ubuntu.bigbluebutton.org/xenial-220/pool/main/b/bbb-webrtc-sfu/bbb-webrtc-sfu_2.2.0-99_amd64.deb), extract it and find the `etc/cron.hourly/bbb-restart-kms` file in there.

It would be great - especially for linking to them, opening issues or pull requests - that files like these are also checked in.

**Comment by dasJ** [comment]
For future reference: https://github.com/bigbluebutton/bigbluebutton/blob/develop/bigbluebutton-config/cron.hourly/bbb-restart-kms
