### ISSUE TITLE
SDP parsing error

### ISSUE THREAD

**Issue by miguellopes** [bigbluebutton/bigbluebutton#9050]
**Describe the bug**
Connecting to freeswitch on multiple firefox versions doesn't seem to work.
The most significant error I could gather is SIP.js throwing this error:
DOMException: "SIPCC Failed to parse SDP: SDP Parse Error on line 4:  Error parsing address edu for mcast.

**Expected behavior**
WebKit based browsers seem to work well.

**BBB version (optional):**
BigBlueButton 2.2.4 (1846)

**Desktop (please complete the following information):**
 - OS: Linux, Mac OS X, Windows 10
 - Firefox
 - Version 74.0.1, 75, ?

**Smartphone (please complete the following information):**
 - Device: Android
 - OS: Android 10
 - Browser: Firefox
 - Version: 68.6.0esr

**Additional context**
I'm sending a domain instead of an IP to be able to serve clients outside of the nat (exclusively).
I made a gist with what I think are the relevant SIP reply
https://gist.github.com/miguellopes/2e219d326759d01f648fa791b15392cb

**Comment by texh2s00** [comment]
https://github.com/bigbluebutton/bigbluebutton/issues/9030

**Comment by basisbit** [comment]
@miguellopes this seems to be a configuration problem of your install. Please use the [support forum](https://groups.google.com/forum/#!forum/bigbluebutton-setup) to ask for help - this issue tracker here is only for BigBlueButton related development, we can't handle support requests here, sorry.
