### ISSUE TITLE
Camera name not visible in android webview  

### ISSUE THREAD

**Issue by MudrekaBohra** [bigbluebutton/bigbluebutton#9053]
Hi everyone, 
I hope you all are doing well and wish you good health.
I was able to successfully implement the BBB in android webview and it works fine and all components are also working fine but when i turn on video the select camera and video quality popup appears the error is that the camera name label are not visible, i can still switch between the front and back camera but the name of the camera in select tag is not visible screenshots attached bellow  
please suggest any quick and dirty way of solving this maybe by providing generic name like camera 1 and camera 2  ......

![bug1](https://user-images.githubusercontent.com/63293297/79112336-f3171300-7d9b-11ea-9b06-c98e26eaf0c5.jpeg)
![bug2](https://user-images.githubusercontent.com/63293297/79112340-f6120380-7d9b-11ea-930c-25fdeab226d3.jpeg)

**Comment by mjohenneken** [comment]
Hi, I'm trying exactly the same and run into the same problem. I'm not sure if this is a problem of BBB, as on other devices it works as expected. I assume BBB is using the outputs of `navigator.mediaDevices.enumerateDevices()`  for the dialog?

**Comment by mjohenneken** [comment]
If that is the case the problem is probably caused by this bug in WebView https://bugs.chromium.org/p/chromium/issues/detail?id=669492

**Comment by mjohenneken** [comment]
From the bug report:
> The enumerateDevices spec states that when the origin does not have access to the devices, enumerateDevices should return empty labels.

As empty labels could be a valid case I would suggest enumerating the choices so that the user can differ them better.

**Comment by MudrekaBohra** [comment]
yes is there a way so that when an empty label is given we can assign generic value to it such as camera 1  for front and camera 2 for back

**Comment by aolee** [comment]
Hi everyone, anyone manage to at least successfully set the camera label as a workaround?

**Comment by pablogeek** [comment]
Hello, I'm also having this issue. any thoughts if we can actually do anything from our side?

**Comment by mjohenneken** [comment]
Looks like a easy fix in UI code of the html5client. From the bare number of issues open in this project i would assume someone digs into code, finds where the API call to the device enumeration is, inserts a provides default labels in case of empty labels and creates a pull request for the community. 

In Android you could try to check if the WebViewClient or ChromeClient has methods to intercept the construction of the native views somhow and provide default labels that way. But that's not a nice solution and doesn't help other people also having this problem.

**Comment by prlanzarin** [comment]
> i would assume someone digs into code, finds where the API call to the device enumeration is, inserts a provides default labels in case of empty labels and creates a pull request for the community.

Yes.
Should be a straightforward fix. If someone wants to submit a label fallback, I'd gladly review it.
See:
https://github.com/bigbluebutton/bigbluebutton/blob/v2.2.x-release/bigbluebutton-html5/imports/ui/components/video-preview/component.jsx#L525
This is where the label is rendered. It'd suffice to add a fallback method (ie generateFallbackCameraLabel) which gets a localized placeholder name (ie `Camera {0}`) and assigns the camera index+1 (ie Camera 1, Camera 2, Camera 3...) to the label.

**Comment by phamquocthinh** [comment]
@mjohenneken 
Hello, could you please tell me where's the file i need to edit to do that trick on bbb server? I work around but still not found where the folder bbb-html5 located in.
Many thanks.

**Comment by mjohenneken** [comment]
The comment by prlanzarin should guide you in the right direction.
