### ISSUE TITLE
Define an Audio priority on other network usage

### ISSUE THREAD

**Issue by PatLemaire** [bigbluebutton/bigbluebutton#9054]
It is a feature that exist on other (commercial) products. Without any action of users, there is a **priority on audio usage of bandwidth**. Clearly, it is more important to hear your peers than see them speaking or showing things on screen.
I think it's going to be difficult to implement because of aggregation of softwares in BBB (Freeswitch/Kurento/Red5...). How to coordonate all those?
Some kind of buffer, maybe ?

**Comment by Oli72** [comment]
I would very much appreciate a higher priority for audio data over video data. I had a BBB session yesterday on which one participant had perfect audio without his camera turned on, but his voice was interrupted by cracks every few seconds with his camera on.

**Comment by PatLemaire** [comment]
Commercial solutions automatically handle this kind of situation. It's more than just comfort, it's essential in my opinion. I'm not a expert on QoS but maybe this could be implemented?

**Comment by mreichh** [comment]
an audio prioritization option would be really helpful resp. crucial for us as well.

**Comment by a-ttila** [comment]
+1

**Comment by ffdixon** [comment]
Keeping this issue open -- we need to investigate if it's possible to make this determination within the client as the audio and video go through different paths (which makes it easy to turn off the webcams independent of audio).
