### ISSUE TITLE
Add shortcut keys for editing tools like Text, Line and Pen

### ISSUE THREAD

**Issue by sfkeller** [bigbluebutton/bigbluebutton#9056]
**Current situation:**
* For editing a presentation in a web conference, there's a nifty tool set dialog to the right with text writing, line drawing etc.  
* In order to start editing an author has to click on the tool dialog and choose a tool. Then, when he/she want's to change the tool (say from text to pen), one has to point to the tool set in order to finally select the pen. Then again, when she/he wants to switch back, two precise clicks are required.
* While presenting a prepared instructional text & figures, this switching forth and back is tedious and error prone.  

![grafik](https://user-images.githubusercontent.com/43340/79074816-bd682080-7cee-11ea-826f-bae953ec8161.png)

**Expected behaviour:**
Add shortcut keys for editing tools, e.g.
```
Alt-Shift-T Text Tool
Alt-Shift-R Line Tool
Alt-Shift-W Pen Tool
```
I didn't check for coincidences nor know what's the logic behind currently available short keys.

**Additional context:**
Adding more shortcut keys could also be a contribution to an even better accessible UX: https://bigbluebutton.org/accessibility/ .

Perhaps related to #6296 .

**Comment by matiasilva** [comment]
I can see this being useful. If you wish to implement this, you just need to add the shortcuts to the setting.yml file and then load those in a similar fashion to how other shortcuts have been created.

**Comment by sfkeller** [comment]
Ok. Note to self: Just add shortcuts using commands similar to other shortcuts at https://github.com/bigbluebutton/bigbluebutton/blob/master/bigbluebutton-html5/private/config/settings.yml

**Comment by matiasilva** [comment]
Yep :) Am I fine to close this issue or are you looking to contribute a PR?

**Comment by pedrobmarin** [comment]
Merging with https://github.com/bigbluebutton/bigbluebutton/issues/5563
