### ISSUE TITLE
no user list recorded/ Strongly need to see user list in recording.

### ISSUE THREAD

**Issue by Linktuner** [bigbluebutton/bigbluebutton#9058]
Actually 2.3.3 version plugin to Moodle. There is no user list while viewing recording of a session. Strongly need to see user list in recording. 
![image](https://user-images.githubusercontent.com/10487460/79131415-3b8cfb80-7db1-11ea-96b0-b4d33e69fe0c.png)

**Comment by matiasilva** [comment]
Closing as new update in 2 months + this doesn't quite belong here. There's a repository for the moodle plugin.
