### ISSUE TITLE
Plug-in "no beuno" with BBB install script. Greenlight works.

### ISSUE THREAD

**Issue by eyebank** [bigbluebutton/bigbluebutton#9061]
**Describe the bug**
I performed a solid bbb install using the install script with ssl. I also included the Greenlight front end (-g). This install is within a dmz and works perfectly via greenlight no errors.
Installed the plug-in (both versions) in MM. when i attempt to run the plug-in the the plug-in launches the greenlight front end.
When the greenlight front-end is removed the plug-in does not launch any meeting.

**Expected behavior**
I expect when the the plug-on launched in MM the BBB interface should be launched.

**Actual behavior**
Greenlight interface is launched

**Screenshots**

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser chrome, firefox and all others

**Comment by matiasilva** [comment]
Looks either like an nginx location block problem or perhaps you passed in the wrong endpoint somewhere. If you still require assistance with this, please post your question to https://groups.google.com/forum/#!forum/bigbluebutton-setup. Closing this issue for now.
