### ISSUE TITLE
Errors in user-feedback-script

### ISSUE THREAD

**Issue by thoschi** [bigbluebutton/bigbluebutton#9065]
Not sure, if this is the correct place to post:

There seems to be at least two errors in the script mentioned at
https://docs.bigbluebutton.org/2.2/customize.html#collect-feedback-from-the-users

There seems to be a `HERE` missing before the second `cat` (about line 19).

Also the variable `$PROTOCOL` is used but not defined. The address created in `/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml` is therefore garbled and there is no output in `html5-client.log`.

Changing the address manually (e.g. `https://...`) solves the problem. So the script should do sth. like

    PROTOCOL=$(cat` /usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties | grep -v '#' | grep '^bigbluebutton.web.serverURL' | sed 's/.*\(http[s]*\).*/\1/')

_Enjoying BBB very much! Best regards, Thomas_

**Comment by mleu77** [comment]
Thank you for that hint.
After running the script (original and modified) I can't start nginx anymore.
Error message 
` nginx: [emerg] unknown log format "postdata" in /etc/bigbluebutton/nginx/html5-client-log.nginx`

Do you have a solution for that problem?
Regards

**Comment by thoschi** [comment]
Yes this is exactely what happens, if you just execute the script as it is shown in the documentation.

First, edit `/etc/bigbluebutton/nginx/html5-client-log.nginx`. It should just contain:

```
location /html5log {
        access_log /var/log/nginx/html5-client.log postdata;
        echo_read_request_body;
}
```
remove anything else (there might be a block starting with `cat`).

Then check `/etc/nginx/conf.d/html5-client-log.conf` to have this line:
```
log_format postdata '\$remote_addr [\$time_iso8601] \$request_body';
```

Afterwards restart the nginx service.

Best regards
Thomas

**Comment by mleu77** [comment]
Thank you very much - now it's working.
I think the tail - command for monitoring should also be improved.
`tail -f /var/log/nginx/html5-client.log | sed -u 's/\\x22/"/g' | sed -u 's/\\x5C//g'`

The command should reduce information e.g. just to "timestamp" and the "feedback": {rating.....}

Best regards
Martin

**Comment by matiasilva** [comment]
I've submitted a pull request that fixes the above changes.

**Comment by matiasilva** [comment]
PR now merged. Closing.

**Comment by Helyux** [comment]
[This Script](https://github.com/Helyux/BBB-Readable-Feedback) i made may be helpful to some of you.
