### ISSUE TITLE
Kurento call timeout html5 client after update

### ISSUE THREAD

**Issue by jesusvaldivia** [bigbluebutton/bigbluebutton#9068]
After update from 2.2.2 to 2.2.3 htmlt5 client does not connect via kurento media server instead it does it via SIP (FreeSWITCH)

This happens even when the server is idle (CPU 1% Utilization)

Chrome developer console
<img width="675" alt="Screen Shot 2020-04-13 at 10 56 39 PM" src="https://user-images.githubusercontent.com/7368641/79184587-2f696400-7dda-11ea-9d76-85da14a1f825.png">

<img width="591" alt="Screen Shot 2020-04-13 at 10 56 59 PM" src="https://user-images.githubusercontent.com/7368641/79184594-342e1800-7dda-11ea-9e96-aa6d810b507e.png">

Thanks.

**Comment by texh2s00** [comment]
https://github.com/bigbluebutton/bigbluebutton/issues/9030

**Comment by Jossef-767** [comment]
I have the same problem,
my 2.2.9 (1891) server is behind NAT. 
installed using bbb-install.sh +Greenlight.
I did as per the instructions in the "Extra steps when server is behind NAT" document.
All my other servers are not behind NAT and have no problem

**Comment by jesusvaldivia** [comment]
If my server is behind NAT, the strange thing is that version 2.2.2 if it works well, the problem is in higher versions.

**Comment by texh2s00** [comment]
If you have updated to 2.2.9 than problems, starts...No uPDATES! Only fresh installs.

**Comment by Jossef-767** [comment]
fresh installed using bbb-install.sh  2.2.9 with Greenlight.

**Comment by prlanzarin** [comment]
Those having the same issue (@jesusvaldivia, @Jossef-767)
- Send the output of sudo bbb-conf --check. Please redact sensitive info.
- Send the output of cat /etc/kurento/modules/kurento/WebRtcEndpoint.conf.ini
- Send the output of cat /usr/share/bbb-web/WEB-INF/classes/spring/turn-stun-servers.xml. Please redact sensitive info.
- Tune bbb-webrtc-sfu logs (/usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml, log.level) to "trace". Restart it (sudo systemctl restart bbb-webrtc-sfu).
 - Reproduce the problem and then attach, compressed:
   * If possible, a dump of chrome://webrtc-internals on Chrome. Just open it before trying listen only, reproduce the problem and then use the Create dump button in the top left corner of the page.
   * Current bbb-webrtc-sfu log (/var/log/bbb-webrtc-sfu)
   * Current kurento-media-server logs (all from the day, /var/log/kurento-media-server/)
   * Current akka-bbb-fsesl log (/var/log/bbb-fsesl-akka)

**Comment by jesusvaldivia** [comment]
> If you have updated to 2.2.9 than problems, starts...No uPDATES! Only fresh installs.

Happens even with a fresh install, is there any way to install version 2.2.3 using bbb-install?

**Comment by Jossef-767** [comment]
Hi Paulo
see:  error","message":"[audio] User not found on getUser for connectionId 0" in
** **bbb-webrtc-sfu.log****    
when trying to connect "Listen-only" the first time.
(I changed my external server ip to 000.000.254.73)


-----------------------------

{"level":"info","message":"[WebsocketConnectionManager] New connection with id [ 0 ]","timestamp":"2020-05-06T15:59:46.201Z"}
{"roomId":"72561","internalMeetingId":"183f0bf3a0982a127bdb8161e0c44eb696b3e75c-1588780778703","status":"MEDIA_STOPPED","level":"info","message":"[audio] Starting RTP source audio/GLOBAL_AUDIO for 72561","timestamp":"2020-05-06T15:59:46.233Z"}
{"coreRoomInfo":{"memberType":"room","roomId":"72561","strategy":"freewill"},"level":"info","message":"[mcs-controller] New room created: 72561","timestamp":"2020-05-06T15:59:46.244Z"}
{"roomId":"72561","userId":"patient-sunset-0CLtnXC","externalUserId":"patient-sunset-0CLtnXC","level":"info","message":"[mcs-controller] New user created at room 72561 with id patient-sunset-0CLtnXC","timestamp":"2020-05-06T15:59:46.250Z"}
{"level":"info","message":"[mcs-controller] User patient-sunset-0CLtnXC joined room 72561 as SFU","timestamp":"2020-05-06T15:59:46.251Z"}
{"roomId":"72561","internalMeetingId":"183f0bf3a0982a127bdb8161e0c44eb696b3e75c-1588780778703","status":"MEDIA_STOPPED","userId":"patient-sunset-0CLtnXC","level":"info","message":"[audio] MCS join for PROXY_GLOBAL_AUDIO_72561 returned patient-sunset-0CLtnXC","timestamp":"2020-05-06T15:59:46.254Z"}
{"level":"info","message":"[mcs-controller] Publish from user patient-sunset-0CLtnXC in room 72561","timestamp":"2020-05-06T15:59:46.256Z"}
{"level":"info","message":"[mcs-sdp-session] New session created {\"type\":\"RtpEndpoint\",\"memberType\":\"mediaSession\",\"mediaSessionId\":\"proud-surf-iUkGJzP\",\"mediaId\":\"proud-surf-iUkGJzP\",\"medias\":[],\"roomId\":\"72561\",\"userId\":\"patient-sunset-0CLtnXC\",\"name\":\"GLOBAL_AUDIO_72561\",\"mediaTypes\":{\"video\":false,\"audio\":false,\"text\":false,\"content\":false,\"application\":false,\"message\":false},\"isMuted\":false,\"volume\":50,\"strategy\":\"freewill\"}","timestamp":"2020-05-06T15:59:46.259Z"}
{"level":"info","message":"[mcs-sfu-user] Added new SDP session proud-surf-iUkGJzP to user patient-sunset-0CLtnXC","timestamp":"2020-05-06T15:59:46.260Z"}
{"level":"info","message":"[mcs-freeswitch] Created new user agent for endpoint GLOBAL_AUDIO_72561","timestamp":"2020-05-06T15:59:46.322Z"}
{"level":"info","message":"[mcs-freeswitch] Making SIP call to: sip:72561@000.000.254.73:5066 from: GLOBAL_AUDIO_72561","timestamp":"2020-05-06T15:59:46.324Z"}
{"level":"info","message":"[WebsocketConnectionManager] Closed connection on [0]","timestamp":"2020-05-06T16:00:00.885Z"}
{"level":"info","message":"[AudioManager] Connection 0 closed","timestamp":"2020-05-06T16:00:00.887Z"}
{"level":"info","message":"[AudioManager] Stopping viewer 72561","timestamp":"2020-05-06T16:00:00.888Z"}
{"roomId":"72561","internalMeetingId":"183f0bf3a0982a127bdb8161e0c44eb696b3e75c-1588780778703","status":"MEDIA_STOPPED","level":"error","message":"[audio] User not found on getUser for connectionId 0","timestamp":"2020-05-06T16:00:00.888Z"}
{"roomId":"72561","internalMeetingId":"183f0bf3a0982a127bdb8161e0c44eb696b3e75c-1588780778703","status":"MEDIA_STOPPED","connectionId":0,"level":"info","message":"[audio] Sending global audio disconnection for user undefined","timestamp":"2020-05-06T16:00:00.890Z"}
{"roomId":"72561","internalMeetingId":"183f0bf3a0982a127bdb8161e0c44eb696b3e75c-1588780778703","status":"MEDIA_STOPPED","level":"error","message":"[audio] User not found on remove for connectionId 0","timestamp":"2020-05-06T16:00:00.891Z"}

**Comment by prlanzarin** [comment]
@Jossef-767 can you get the output of `sudo netstat -putan | grep -i 5066` in the server, please?
Issue is that bbb-webrtc-sfu isn't able to connect to FreeSWITCH on port 5066 which is needed for the listen only bridge, so there's some sort of misconfig going on.

**Comment by Jossef-767** [comment]
![image](https://user-images.githubusercontent.com/2356928/81224535-88e73c00-8ff0-11ea-8a80-417f695bb2ff.png)

![image](https://user-images.githubusercontent.com/2356928/81224624-a9af9180-8ff0-11ea-8aa3-2409679a5f6b.png)

**Comment by prlanzarin** [comment]
@Jossef-767 try setting `freeswitch.sip_ip` to `192.168.114.1` at `/usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml`, then `sudo systemctl restart bbb-webrtc-sfu`. Then check listen only.

The aforementioned config should already be set to the address FreeSWITCH is listening to 5066 on by the packaging. Did you do any manual config changes?

**Comment by Jossef-767** [comment]
Hi Paulo, 👍 setting freeswitch.sip_ip to 192.168.114.1 Fixed the problem completely,  it works fine now.
I am amazed at how quickly you solved the problem.
I probably changed the configuration by mistake.
I am very grateful for your help.

**Comment by prlanzarin** [comment]
@jesusvaldivia please follow the same steps @Jossef-767 did. If it doesn't work for you as well, please send the requested infos. Forget about the update vs fresh install thing for now, it probably has nothing to do with your current problem.

**Comment by jesusvaldivia** [comment]
Thanks @prlanzarin , I followed the steps and the problem was solved, my final question would be Why does this happen if it is a fresh installation?, I have a server with version 2.2.2 where freeswitch.sip_ip points to the public IP and it works without problems.

**Comment by prlanzarin** [comment]
@jesusvaldivia  I'll double check our packaging configuration steps. There was a significant leap forward in the media components between 2.2.2 and 2.2.3 (and that specific configuration changed in that gap) and we might have missed something on NAT'ed environments. Anyways, good to hear you got it working.

**Comment by jesusvaldivia** [comment]
Do you think it is necessary to make any changes to the installation file (bbb-install) to correct this problem in NAT environments?

**Comment by prlanzarin** [comment]
@jesusvaldivia We're going to check that.

**Comment by matiasilva** [comment]
Can I assume that this issue has been solved? Apologies for bumping this.

**Comment by prlanzarin** [comment]
Yes, bbb-install and bbb-config have been corrected.

**Comment by ajesina** [comment]
Apologies for resurrecting this, but I did a fresh install of 2.2.18 yesterday, and I'm running into the same problem while being behind NAT. I've followed the firewall configuration article, but the internal IP still is the only one that's used as a connection candidate according to about:webrtc. Interestingly, I'm also seeing the internal IPv6 address as a candidate in the connection logs.

Here is my bbb-conf at the moment:

![bbbconf](https://user-images.githubusercontent.com/8887920/85685819-b470d380-b6cf-11ea-99c5-e818ed381f63.png)

I've tried explicitly setting ext-rtp-ip and ext-sip-ip instead of the variables, I've tried setting the kurento URL to the external IP address (as it is in the linked config above), I've tried additionally forwarding ports 7443 and 5066 on the firewall.

There is a STUN server configured in WebRtcEndpoint.conf.ini (picked from the list of public ones, it works well according to the test linked in the config):
![kurentoconf](https://user-images.githubusercontent.com/8887920/85686519-5395cb00-b6d0-11ea-9a9d-c478c713f24c.png)

I also tried explicitly setting the external IP in that config.
I'm not sure if there's something missing in the following part of the firewall configuration article that I additionally should have done, since the sentence seems incomplete:
![image](https://user-images.githubusercontent.com/8887920/85690319-c0f72b00-b6d3-11ea-81f6-c57f16ede70a.png)

Please let me know what additional information I should provide.
Thanks.

**Comment by matiasilva** [comment]
For support requests, you might be better helped at https://groups.google.com/forum/#!forum/bigbluebutton-setup
