### ISSUE TITLE
bbb-conf --network

### ISSUE THREAD

**Issue by mauser8004** [bigbluebutton/bigbluebutton#9069]
Pls update /usr/bin/bbb-conf

Show 443 port connect, and rm /tmp/t_net

if [ $NETWORK ]; then
  +++ netstat -ant | egrep ":1935|:80|:443\ " | egrep -v ":::|0.0.0.0" > /tmp/t_net
    REMOTE=$(cat /tmp/t_net | cut -c 45-68 | cut -d ":" -f1 | sort | uniq)

    if [ "$REMOTE" != "" ]; then
 +++       echo -e "netstat\t\t\t80\t1935\t443"
        for IP in $REMOTE ; do
            PORT_1935=$(cat /tmp/t_net | grep :1935 | cut -c 45-68 | cut -d ":" -f1 | grep $IP | wc -l)
            PORT_80=$(cat /tmp/t_net | grep :80 | cut -c 45-68 | cut -d ":" -f1 | grep $IP | wc -l )
+++           PORT_443=$(cat /tmp/t_net | grep :443 | cut -c 45-68 | cut -d ":" -f1 | grep $IP | wc -l )

 +++         echo -e "$IP\t\t$PORT_80\t$PORT_1935\t$PORT_443"
        done
    fi
#it can also be queried by a simple zabbix agent because if I run it as root it can't overwrite it
 +++   rm /tmp/t_net
fi

**Comment by nough** [comment]
#9332

**Comment by nough** [comment]
The main part of this request is now merged. If my second pull request is successful then this issue can be closed.

**Comment by mauser8004** [comment]
Thank you very much

**Comment by nough** [comment]
This issue can now be closed.
