### ISSUE TITLE
External Youtube video repeats the few first seconds

### ISSUE THREAD

**Issue by GhaziTriki** [bigbluebutton/bigbluebutton#9070]
**Describe the bug**
When a Youtube external video is shared, sometimes it just repeats the first seconds instead of advancing normally.

**Expected behavior**
The video should play to the end.

**Actual behavior**
The video only plays the first seconds and repeats from the start.

**BBB version (optional):**
2.2.5

**Comment by rinjus** [comment]
I can confirm same behavior, when video is shared from pc runing Windows 10 Home (tried Chrome, Firefox, Edge). While other PC's works as expected(on same BBB server).  Seems, that this issue is more client PC(OS) related.

**Comment by Nick-Netizen** [comment]
Try synchronizing your system’s clock with an Internet time server.
In Windows: Control Panel > Date and time > Internet time (exact path may vary with your version of Windows).
Hope this helps.

**Comment by ffdixon** [comment]
This is a known issue that we've been trying to resolve.  

One of the main challenges is reproducibility.  @GhaziTriki are you able to reliability reproduce it on your end?

**Comment by nguyentruong0212** [comment]
@Nick-Netizen n
I have changed as your guide but it didn't work. Hope to have any workaround solution soon. Thanks

**Comment by anasalsurmi** [comment]
looking for fix

**Comment by mtsonline** [comment]
just had the same issue here 
some comments of the users:

14:17
smth wrong with the video, it is shonw in a loop
14:21
just need to click on "what is SEO" so it goes to youtube
14:21
the first 4 seconds are in a loop
14:21
doesn't work
14:21
it doesn't work for me
14:21
loop again
14:21
it's watchable by opening in a new tab

if user feedback is correct, it worked for some and others had the loop at the same time.
unfortunately I have no details though.

**Comment by rriscado** [comment]
I had the same behavior!!

Usually when the teacher/student's computer or internet isn't very good.

+1

**Comment by prlanzarin** [comment]
@rriscado just to be sure: what version are you running?

**Comment by rriscado** [comment]
I'm now using version 2.2.15.

I think the last time I had this error, I used version 2.2.10. But I'm not sure!

**Comment by prlanzarin** [comment]
I believe this has been fixed for a while now? @lfzawacki

**Comment by lfzawacki** [comment]
Yes, this has been fixed for a while. If there are more recent reports with more data we could re-open the issue.
