### ISSUE TITLE
Cannot join audio with Krisp chrome extension

### ISSUE THREAD

**Issue by repomaa** [bigbluebutton/bigbluebutton#9073]
Having the krisp chrome extension prevents you from joining audio on a conference. The error is "There was an issue with your media devices"

**To Reproduce**
1. Get [Krisp](https://krisp.ai)
2. Install Chrome extension
3. Join conference audio

**Expected behavior**
I'd expect to be able to use the krisp extension to block background noise.

**Desktop:**
 - OS: arch linux
 - Browser: Chromium
 - Version: 81.0.4044.92

**Comment by matiasilva** [comment]
Any update to this?

**Comment by repomaa** [comment]
Latest version seems to be working, but sounds horrible :+1: Closing this, since it doesn't seem to be a BBB problem.
