### ISSUE TITLE
Was trying to customize Greenlight landing page..screwed it up..want to revert to old install.

### ISSUE THREAD

**Issue by tarunb999** [bigbluebutton/bigbluebutton#9075]
Installed BBB and Greenlight 2.5.3. through bbb-install.sh

I wanted to customize the Landing page but screwed up while following http://docs.bigbluebutton.org/greenlight/gl-install.html#switching-from-install-to-customize

I'm fed up and want to revert to my standard install. Can anyone please guide me on how to go back ( I have the old greenlight in greenlight-old directory)

Thanks,
Tarun

**Comment by svoeth** [comment]
this should be as easy as

```
cd ~/greenlight #or wherever your greenlight folder ist
docker-compose down
cd..
rm -r greenlight #you could also just move it somewhere else, like "mv greenlight greenlight-older" ;)
mv greenlight-old greenlight
cd greenlight
docker-compose up -d
```

**Comment by tarunb999** [comment]
Thanks Stephan. I successfully reverted to my old self :-)
Would it be possible for spelling out simple steps for achieving the
customization of Landing page in Greenlight?
I religiously followed the steps mentioned in
http://docs.bigbluebutton.org/greenlight/gl-install.html#switching-from-install-to-customize
but could not restart the Greenlight.

Anyhow perhaps Fred et al might make it easy to edit the landing page in
the future versions..so waiting for that time.

Thanks again.

...
Tarun

**Comment by tarunb999** [comment]
Don't know but I'm just not able to do it..have tried several times [Ruby is not my strong points either :( ]
Now I'm in the fear of losing my user-accounts and recordings in case some thing goes wrong !!

**Comment by tarunb999** [comment]
Finally I achieved it ..
https://github.com/bigbluebutton/greenlight/issues/1360
