### ISSUE TITLE
The voice application may not have registered with the sip server

### ISSUE THREAD

**Issue by TivanDev** [bigbluebutton/bigbluebutton#9079]
In my bbb server
every 2 hours i have this error in bbb-conf --check
The voice application may not have registered with the sip server.
and when i have this error bbb html5client didn't work.

**Comment by basisbit** [comment]
please check the freeswitch log and the red5 log for more details on the problem. also, try `bbb-conf --clean` and see what issues it reports.

**Comment by TivanDev** [comment]
how to check freeswitch log and red5 log
when i run bbb-conf --clean my service fixed but after 2 ,3 hours server down again

Sent from Outlook Mobile<https://aka.ms/blhgte>

________________________________

**Comment by basisbit** [comment]
various log files can be found in `/var/log/`
you might also want to run `bb-conf --watch` until the problem happens again, and then you might figure out what the problem is

**Comment by TivanDev** [comment]
when i run bbb-conf --watch
i have this error's
/var/log/bigbluebutton/bbb-web.log:org.jodconverter.office.OfficeException: Office process died with exit code 77
/var/log/bigbluebutton/bbb-web.log:Caused by: org.jodconverter.office.OfficeConnectionException: Connection failed: 'socket,host=127.0.0.1,port=8100,tcpNoDelay=1'; java.net.ConnectException: Connection refused (Connection refused)
/var/log/bigbluebutton/bbb-web.log:Caused by: com.sun.star.connection.NoConnectException: java.net.ConnectException: Connection refused (Connection refused)
/var/log/bigbluebutton/bbb-web.log:Caused by: java.net.ConnectException: Connection refused (Connection refused)
/var/log/bigbluebutton/bbb-web.log:org.jodconverter.office.OfficeException: Office process died with exit code 77
/var/log/bigbluebutton/bbb-web.log:Caused by: org.jodconverter.office.OfficeConnectionException: Connection failed: 'socket,host=127.0.0.1,port=8104,tcpNoDelay=1'; java.net.ConnectException: Connection refused (Connection refused)
/var/log/bigbluebutton/bbb-web.log:Caused by: com.sun.star.connection.NoConnectException: java.net.ConnectException: Connection refused (Connection refused)
/var/log/bigbluebutton/bbb-web.log:Caused by: java.net.ConnectException: Connection refused (Connection refused)
/var/log/bigbluebutton/bbb-web.log:org.jodconverter.office.OfficeException: Office process died with exit code 77
/var/log/bigbluebutton/bbb-web.log:Caused by: org.jodconverter.office.OfficeConnectionException: Connection failed: 'socket,host=127.0.0.1,port=8101,tcpNoDelay=1'; java.net.ConnectException: Connection refused (Connection refused)
/var/log/bigbluebutton/bbb-web.log:Caused by: com.sun.star.connection.NoConnectException: java.net.ConnectException: Connection refused (Connection refused)
/var/log/bigbluebutton/bbb-web.log:Caused by: java.net.ConnectException: Connection refused (Connection refused)

**Comment by matiasilva** [comment]
Thanks for posting. If you continue to have the same issue,  please post here: https://groups.google.com/forum/#!forum/bigbluebutton-setup as this issue trackers if for bugs and development.
