### ISSUE TITLE
Checksum Error when connecting to Breakout Rooms with greenlight

### ISSUE THREAD

**Issue by svoeth** [bigbluebutton/bigbluebutton#9080]
**Describe the bug**
Hey,

i have a problem using Breakout Rooms with Greenlight. Everything else is working fine.
The error is reproducible in our environment with Firefox, Chrome and Chromium.

If i try to join a breakout room i get redirected to the main page without any warning. 
The greenlight production.log only shows the redirection to /b (after not beeing connected to the breakout room)

In syslog i found these errors, stating that i have some sort of checksum error.

```
Apr 14 01:56:10 bbb run-prod.sh[5854]: 2020-04-14T01:56:10.505+02:00 DEBUG o.b.web.controllers.ApiController - ApiController#join
Apr 14 01:56:10 bbb run-prod.sh[5854]: 2020-04-14T01:56:10.506+02:00 INFO  o.b.api.ParamsProcessorUtil - CHECKSUM=517d558343936555bdb35200835a811b270608e32d17df79438c92ab3db7ce08 length=64
Apr 14 01:56:10 bbb run-prod.sh[5854]: 2020-04-14T01:56:10.506+02:00 INFO  o.b.api.ParamsProcessorUtil - SHA256 d99d6d059b64351afe5826ac398958c233db59ce37f38694d532a1112a0e367b
Apr 14 01:56:10 bbb run-prod.sh[5854]: 2020-04-14T01:56:10.506+02:00 INFO  o.b.api.ParamsProcessorUtil - query string after checksum removed: [fullName=User+Name&isBreakout=true&joinViaHtml5=true&meetingID=e9a277611cc6a06b50b006eb05a286fd7e5f1100-1586822158431&password=slidgEbTQxMF&redirect=true&userID=w_od8e4v5awevw-2]
Apr 14 01:56:10 bbb run-prod.sh[5854]: 2020-04-14T01:56:10.507+02:00 INFO  o.b.api.ParamsProcessorUtil - checksumError: query string checksum failed. our: [d99d6d059b64351afe5826ac398958c233db59ce37f38694d532a1112a0e367b], client: [517d558343936555bdb35200835a811b270608e32d17df79438c92ab3db7ce08]
Apr 14 01:56:10 bbb run-prod.sh[5854]: 2020-04-14T01:56:10.507+02:00 DEBUG o.b.web.controllers.ApiController - ApiController#invalid You did not pass the checksum security check
Apr 14 01:56:10 bbb run-prod.sh[5854]: 2020-04-14T01:56:10.507+02:00 DEBUG o.b.web.controllers.ApiController - JSON Errors [{"message":"You did not pass the checksum security check","key":"checksumError"}]
Apr 14 01:56:10 bbb run-prod.sh[5854]: 2020-04-14T01:56:10.507+02:00 DEBUG o.b.web.controllers.ApiController - Constructed logout URL https://bbb.computerwerk.org?errors=[%7B%22message%22:%22You%20did%20not%20pass%20the%20checksum%20security%20check%22,%22key%22:%22checksumError%22%7D]
```

So it seems the client is providing the mentioned checksum but bbb is expecting the sha256?!

Any idea of what is wrong here?

**To Reproduce**
1. use greenlight
2. start a conference
3. create breakout rooms
4. try to join a breakout room

**Expected behavior**
Joining the breakout room

**Actual behavior**
Landing on startpage without error (checksum error in logfile)

**BBB version**
BigBlueButton Server 2.2.5 (1848)
Greenlight v2: Docker - current upstream version from git 
(i checked for updates of both systems before posting this issue)

**Desktop**
 - OS: Linux
 - Browser: Chrome, Chromium, Firefox

**Smartphone**
 - Device: Pixel3a
 - OS: Android 10
 - Browser: Chrome

**Additional context**
I was redirected by the greenlight-team. They suspect it to be a bbb issue: https://github.com/bigbluebutton/greenlight/issues/1289

**Comment by svoeth** [comment]
might be related to #9037 

reinstalling might resolve the problem (might test that later) but it is not a bugfix. Updating should work

**Comment by svoeth** [comment]
apt install --reinstall bbb-webrtc-sfu bbb-transcode-akka bbb-web bbb-html5 bbb-fsesl-akka bbb-apps-akka bbb-apps

fixed the problem for the moment. But update breaking installation is still a bug

**Comment by serior** [comment]
I hat the same problem. After i set a new secret, the problem was solved.
