### ISSUE TITLE
Unable to connect

### ISSUE THREAD

**Issue by sarzali07** [bigbluebutton/bigbluebutton#9083]
**Describe the bug**
Whenever I send room link to someone in messenger or Whatsapp it shows unable to connect 

**To Reproduce**
1. Go to facebook messenger and share session link
2. Click on when someone click on it 
3. Scroll down to

I do not know how to deal with it.
![WhatsApp Image 2020-04-14 at 9 49 55 PM](https://user-images.githubusercontent.com/10739321/79253141-2ccf4300-7e9c-11ea-9b13-d17c95735586.jpeg)
Regards

**Comment by Tainan404** [comment]
Hello @sarzali07, could you inform your browser and its version?

**Comment by ffdixon** [comment]
Are you copying the URL from your session?  This won't work (you can see this if you copy the URL from a live session and then try to open it in a different browser).

User's must login properly login to a BigBlueButton session through the front-end -- such as Moodle or Greenlight -- to be authenticated.

**Comment by sarzali07** [comment]
Hi @Tainan404  and @ffdixon it is common to practise, I noticed that whenever I send URL over messenger and Whatsapp even educated people to click on a link.
