### ISSUE TITLE
Feature request: Prevent users from downloading presentations (bigbluebutton.properties)

### ISSUE THREAD

**Issue by Sea444** [bigbluebutton/bigbluebutton#9086]
**Is your feature request related to a problem? Please describe.**
With regard to IT security and data protection, there should by a general setting to prevent users from downloading presentations. Otherwise BBB could be used for dangerous filetransfers internet<->intranet.

**Describe the solution you'd like**
New setting in /usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties to generally disallow download of presentations:
`# Allow or diallow users to download presentations.`
`# "True": presenter can chose if a presentation is downloadable when uploading the presentation -> current default`
`# "False": download of presentations is generally disabled -> no download button`
`AllowPresentationDownload=True`

**Describe alternatives you've considered**
No alternative.

**Additional context**
This feature is also requested by user heavenknows1978 in #9031 and #9045.

**Comment by Sea444** [comment]
For clarification: The download of the displayed individual SVG files or PNG files cannot be prevented, of course. But it must not be possible to download the original complete PDF or Office documents (possibly .doc with a malicious macro!).

**Comment by ffdixon** [comment]
It's a good suggestion, and makes sense to have this feature behind a flag.  

We'll look at how easy it would be to add to an update in the near-term.

**Comment by matiasilva** [comment]
There is a current setting in the HTML5 client that disallows participants to download the presentation via the upload screen. Is this inadequate for your purposes?

**Comment by talhaimam** [comment]
@matiasilva Hello, I need to make sure that part time teachers using my platform can't download the presentations either because the presentations are proprietary and it would violate ISO standards if we allowed part-time teachers to download the presentations. Is there a way to disable the download of presentations altogether?

**Comment by lonesomewalker** [comment]
Very strange...
https://support.bigbluebutton.org/hc/en-us/articles/1500005216321-Upload-a-presentation-enable-for-download

This shows that it is possible, but with the current 2.6 it is not...
