### ISSUE TITLE
Error 1004 (reason=Incompatible SDP) (error 1004)

### ISSUE THREAD

**Issue by KeroQuero** [bigbluebutton/bigbluebutton#9088]
Hi guys, I use BBB from Chrome (Moodle). I was not occuring an error but since yesterday it started to give error 1004 reason Incompatibe SDP. What should I do?

**Comment by basisbit** [comment]
Please open https://test.webrtc.org/ and start the test.
Are you the administrator of that BigBlueButton server? If yes, please run `bbb-conf --check`.
Additionally, can you test again on https://demo.bigbluebutton.org/ and let us know if you still encounter the error?

**Comment by sebaro11** [comment]
Hi, I am getting the same error on my fresh setup. Webcam works fine, but no voice is possible.

The test with https://test.bigbluebutton.org/ is fine, so it seems that I need to change something in my setup. I did not change any config files, just took a quick out-of-the-box test and noticed the problem.
BTW: Took a Scaleway Instance to run BBB, if that helps in any way. Used the bbb-install.sh script with Greenlight and my own domain.

`bbb-conf --check` output

`# Potential problems described below
# IP does not match:
#                           IP from ifconfig: 10.18.32.77
#   /etc/nginx/sites-available/bigbluebutton: bbb.mydomain.net (change for privacy)

# Warning: The setting of 51.15.88.XXX for proxy_pass in
#
#    /etc/bigbluebutton/nginx/sip.nginx
#
# does not match the local IP address (10.18.32.77).
# (This is OK if you've manually changed the values)

`
I changed the Domain and Public IP Adress for privacy reasons.

On the test environment I checked the console in Chrome an received two candidates for the connection.
`sip.invitecontext.mediahandler | ICE candidate received:`

But on my own instance there is no message like that in the console.

It seems that I missed something. In my Scaleway Dashboard I set the Security Group for my bbb instance to allow all udp and tcp connections/ports.

**Comment by sebaro11** [comment]
When I use Firefox 75 instead of Chrome 81.0.4044.113 the sound/microphone works fine.

**Comment by agowa338** [comment]
This error apparently means that there is an issue with webrtc querying your ip address.
If you have uBlock origin or Privacy Badger, check there settings and make sure the option to block sharing your local ip is *not* set.

**Comment by sebaro11** [comment]
Thank you for the answer. Indeed it was that little checkbox in my uBlock settings I activated some time ago. With that unchecked the connection works flawless.

**Comment by agowa338** [comment]
But mind the consequences. Every participant of the meeting might therefore know your IP and if there is someone not playing nicely that one might DDOS you...
It might not be important to you when doing this in limited scope, but if it is a public meeting or something like that it could be relevant.

**Comment by ostasevych** [comment]
> This error apparently means that there is an issue with webrtc querying your ip address.
> If you have uBlock origin or Privacy Badger, check there settings and make sure the option to block sharing your local ip is **not** set.

I am using fair adblocker. I switched it off completely and that didn't help with the https://demo.bigbluebutton.org, but it works with https://test.bigbluebutton.org. I also checked with another browser - the same issue. My IP address is gray, might it be the reason... So, what to do?

**Comment by agowa338** [comment]
Maybe you're behind a CGN, the demo.bigbluebutton.org site is IPv4 only. The test.bigbluebutton.org one has IPv6:
![image](https://user-images.githubusercontent.com/2544867/81437343-4d24b180-916b-11ea-9c32-d5a945c64a5a.png)

**Comment by GokulDas027** [comment]
I have to say, this is a "feature at times"
had an online class today, this error occurred, got the attendance with less internet usage and no disturbance to other works.. It was convenient😁😜

**Comment by agowa338** [comment]
It should be noted however, that this issue could be solved by the Bigbluebutton provider configuring a TUN Server, but that would increase traffic that passes through there infrastructure, as participants would than use the TUN Server as rendezvous point.

**Comment by basisbit** [comment]
KeroQuero were you able to resolve your server configuration issue in the mean time? If not please ask for support in our mailing list / forum at https://groups.google.com/forum/#!forum/bigbluebutton-setup

**Comment by yashpalgoyal1304** [comment]
coming from https://github.com/bigbluebutton/bigbluebutton/issues/9088#issuecomment-624206690
> This error apparently means that there is an issue with webrtc querying your ip address.
> If you have uBlock origin or Privacy Badger, check there settings and make sure the option to block sharing your local ip is **not** set.

![image](https://user-images.githubusercontent.com/19423063/90322094-aa4fb080-df6d-11ea-8221-2b024098bc29.png)

Enabling that setting played the audio for me at https://test.bigbluebutton.org/
