### ISSUE TITLE
BBB behind nat, local users has 1007

### ISSUE THREAD

**Issue by RasimKalimullin** [bigbluebutton/bigbluebutton#9089]
Hi! 
I installed and configured BBB behind NAT, everything works for external users. But local users get error 1007. In about:webrtc I see an external address that is not accessible to this users.  Is it possible to configure the BBB(freeswitch?) so that local users receive a local address for webrtс?
Thanks!

**Comment by AdrianMaslowskiAMTL** [comment]
Hi!
Please read about Hairpin NAT ( NAT Reflection or NAT Loopback)
I solve this problem slightly adjusting NAT settings. ( Pfsense appliance)

**Comment by RasimKalimullin** [comment]
Ok, will try, thx
For https i use vhosts/dns view and etc. In freeswitch external_ip is hardcoded. I think there is a solution like this https://freeswitch.org/confluence/display/FREESWITCH/Multi+Homed+Dual+NIC+How+To, but could not adapt

**Comment by RasimKalimullin** [comment]
yes, it works. thx!

**Comment by arpsyapathy** [comment]
@RasimKalimullin Hi! How you solve this problem? I have same problem

**Comment by RasimKalimullin** [comment]
> @RasimKalimullin Hi! How you solve this problem? I have same problem
Yes. Use Hairpin NAT. Your settings depend on your hardware and network configuration. There is no universal solution
