### ISSUE TITLE
Improve german translation for uploading files

### ISSUE THREAD

**Issue by Sea444** [bigbluebutton/bigbluebutton#9093]
**Situation**
When you select a file for uploading, it's put in the list. Now you can decide wheter to allow downloading of this file. To start the upload process, you have to klick on "Upload" at the top oft the page. But in german translation it shows "wird hochgeladen..." (=Upload in progress) before the upload process starts. So users are waiting for this text to change to "fertig" (suceed) - and wait, and wait...

![grafik](https://user-images.githubusercontent.com/63501663/79341578-520b9200-7f2c-11ea-84c5-58a718ddff90.png)

**Proposal**
Change "wird hochgeladen...."  in language file to "Bereit zum Hochladen..."

![grafik](https://user-images.githubusercontent.com/63501663/79342754-cdba0e80-7f2d-11ea-849e-1273f261852a.png)

(Unfortunately I don't know yet how to do a pull request for this proposal as I'm new to github)

**Comment by basisbit** [comment]
#9096 was closed, so @Sea444 could you please close this issue if there is nothing else left to do? Thanks!
