### ISSUE TITLE
Black screen when uploading a file larger then "maxFileSizeUpload" when "maxFileSizeUpload" is below 1000000

### ISSUE THREAD

**Issue by Sea444** [bigbluebutton/bigbluebutton#9094]
**Describe the bug**
When "maxFileSizeUpload" is set to a value below 1000000 and you try to upload a file that is larger, you get a black screen.

**To Reproduce**
1. Set "maxFileSizeUpload" in /usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties to a value under 1000000
2. Upload a file larger than 1000000 bytes
3. You get a black screen -> BUG
4. Set "maxFileSizeUpload" in /usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties to default (30000000) or a value of 1000000 or larger 
5. Upload a file larger than the value
6. You get a "nice" error message that file is too big

**Expected behavior**
A "nice" error message should appear, that the file is too big. 

![grafik](https://user-images.githubusercontent.com/63501663/79345116-fdb6e100-7f30-11ea-8f76-1c4a5c04ad2f.png)

**Actual behavior**
Only a black screen appears

![grafik](https://user-images.githubusercontent.com/63501663/79344661-681b5180-7f30-11ea-8597-535e1ee7a190.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Firefox
 - Version: 75.0

**Additional context**
Tried setting maxFileSizeUpload to 0 or 1 as makeshift workaround for #9086 (block upload of presentations so that nobody can download one), as long as there is no solution for #9086...

**Comment by lnoSlevin** [comment]
Hi i have same problem, but, i have presentation, 
i uploaded it once on first time testing of BBB, everything was ok, 
but after i left session, or restarted id, when im trying to upload presentation, after pressing upload button, i see only black screen, i hear audio, but nothing else. Please help.

**Comment by jfsiebel** [comment]
I couldn't reproduce this problem in the recent build.
