### ISSUE TITLE
Invite Link 

### ISSUE THREAD

**Issue by hsssystems** [bigbluebutton/bigbluebutton#9098]
Hi,

when a moderator joins a room from greenlight we see a message with an invite link 

![image](https://user-images.githubusercontent.com/25076676/79365877-893d6b80-7f4b-11ea-8dc8-def6e17896a6.png)

However, the link does not appear when a room has been started from moodle. Is there a way to display the link even in sessions started from moodle?

br

Harald

**Comment by toto4ds** [comment]
greenlight send "moderatorOnlyMessage" https://docs.bigbluebutton.org/dev/api.html
moodle don't
And bbb.host/b/444-444-44 it's greenlight only url

**Comment by hsssystems** [comment]
thx!
so no way to implement this from moodle? We could do this, we have a lot of experience in moodle plugin implementation...

**Comment by toto4ds** [comment]
If U need static urls for rooms, bbb get great "official and easy to use BigBlueButton API for PHP" https://github.com/bigbluebutton/bigbluebutton-api-php
Moderator create room by https://github.com/bigbluebutton/bigbluebutton-api-php/wiki/API-Create
User join by https://github.com/bigbluebutton/bigbluebutton-api-php/wiki/API-Join
U only need to associate the desired URL with $meetingID

**Comment by hsssystems** [comment]
thx a lot!

**Comment by MrCapitalist** [comment]
Hi
I have same question
How can I remove invitation box from BigBlueButtun when user come from greenlight?

**Comment by matiasilva** [comment]
Fork Greenlight and remove the `moderatorOnlyMessage` as indicated above.
