### ISSUE TITLE
Moderator approval feature

### ISSUE THREAD

**Issue by miriyusifli** [bigbluebutton/bigbluebutton#9099]
**Describe the bug**

I performed the test on https://demo.bigbluebutton.org/.  If **require moderator approval** option is enabled on a room,  **Allow all authenticated** option doesn't perform anything on a meeting. It does nothing. What is the problem? 

**To Reproduce**
1. Create a room which requires moderator approval
2. Start the meeting
3. Join the meeting from another account (as 2nd participant)
4. Click **Allow all authenticated** option and see error.

**Expected behavior**
Allow or deny the user who wants to join the meeting

**Actual behavior**
It doesn't perform anything. There is no feedback.

**Screenshots**
![screen](https://user-images.githubusercontent.com/18422143/79384627-89e3fb00-7f67-11ea-987b-1cb33a24112d.png)

**Additional context**
I don't understand who is included in the "**Allow all authenticated** " option. What is the difference between **guest** and **everyone**?  Because **Allow guest** option allows everyone (authenticated users and unauthenticated users)

As far as I understand, each user who has an account on greenlight is an authenticated user. Others are guest users.

**Comment by matiasilva** [comment]
Your last statement is correct. Greenlight and other frontends provide users with some level of authentication, which is then passed forward to BBB. Closing this as it seems it has been resolved.

**Comment by SamuelWei** [comment]
@matiasilva I think I have the same or similar question as @miriyusifli . I don't userstand what the difference between 'Allow all guests' and 'Allow all authenticated' is. I found some sections in the code that looks like there is a fourth option for the guest policy setting that isn't documented: 'ALWAYS_ACCEPT_AUTH' and another  undocumented parameter on joing a meeting: 'auth'.

https://github.com/bigbluebutton/bigbluebutton/blob/41f19a2cd1bc7dae76cbd805cdc3ddfbf1e6ab18/bigbluebutton-client/src/org/bigbluebutton/main/model/GuestPolicy.as#L29 , https://github.com/bigbluebutton/bigbluebutton/blob/dfbc1ef9b49e2297bb5cc6c3620fa481fb652f5a/bbb-common-web/src/main/java/org/bigbluebutton/api/domain/Meeting.java#L354 and https://github.com/bigbluebutton/bigbluebutton/blob/c33ed683f37340e6a9d3585339fa04711cde7420/bigbluebutton-web/grails-app/controllers/org/bigbluebutton/web/controllers/ApiController.groovy#L258

Could you please explain the parameters, what they are doing and what the buttons are for.

Thank you for this amazing product!

**Comment by matiasilva** [comment]
Hi, I'm not too sure of the distinction myself as I haven't tested this out. My last comment pretty much sums up all I know guests and authenticated users. I see you have posted on 3 other forum posts, so I'll leave this one closed. Feel free to also ask the users mailing list as they may be able to help you better.
