### ISSUE TITLE
Survey: New profile yes/no/abstention

### ISSUE THREAD

**Issue by Sea444** [bigbluebutton/bigbluebutton#9101]
**Is your feature request related to a problem? Please describe.**
There are six profiles for surveys, like yes/no, right/wrong, A/B, A/B/C, ... Unfortunately there is no profile for yes/no/abstention, what is often used in offical gremiums. 

**Describe the solution you'd like**
Add survey profile yes/no/abstention.

**Describe alternatives you've considered**
When you use survey profile yes/no, you can't know if that persons, that didn't select yes or no received the survey or missed it. So this isnÄt an alternative.
Also it's not an alternative to config user-defined settings in each conference.

**Additional context**
Is there a config file where I can set the survey profiles on my own?

**Comment by Tainan404** [comment]
Hello @Sea444, I think you could use the custom poll for your case, it let you define a label for the poll option.
![Peek 2020-04-16 08-21](https://user-images.githubusercontent.com/15806883/79450723-a873e180-7fbb-11ea-83d0-c09e78d195fa.gif)

**Comment by Sea444** [comment]
@Tainan404 : Thanks for your comment. I know this option, but unfortunately for each poll you have to enter the 3 labels again. That is not useful for a meeting with many polls. :-/

**Comment by einhirn** [comment]
Hmm... Perhaps the custom poll labels could persist between polls - at least in one session?

**Comment by grinapo** [comment]
Why not let the user to create his/her own poll templates? I'd be fine with `settings.yaml`....
