### ISSUE TITLE
Get 1002/1007 error while the bbb server is NOT behind firewall/NAT

### ISSUE THREAD

**Issue by fweng322** [bigbluebutton/bigbluebutton#9103]
**Describe the bug**
I set up a bbb server and greenlight at: bbb.slat.org.
This server uses pppoe to get a public ip, but a dynamic one, therefore I used no-ip ddns to get the ip of the hostname updated.
Many of the installation guide and troubleshooting guide want me to set up external IP, but in this case I don't know the exact external IP I got.

I set up it successfully and when connecting it from my home (though different public IP, but got from the same modem and the connection was within the same switch) I can get both audio/video work well.  However, connection from outside the modem (for example, my laptop connecting to my cell phone's 4G network) I got 1002 when creating a meeting room.  Other users from outside got 1007 error when joining the room.

I'm sure that no firewall is running either on the bbb server, or on the client part.  The server is not behind NAT since its default gateway is through pppoe and got a public ip.  Only that it is using dynamic DNS and I wonder if some of the configurations may not work with such scenario.

**To Reproduce**
1. Setup BBB and greenlight server with external IPv4 got from PPPoE modem and set up ddns for hostname.

**Expected behavior**
Clients should be able to connect correctly

**Actual behavior**
Clients from outside got 1007 error when joining the meeting room. 
My admin account got 1002 error when creating the meeting room. 

**Screenshots**

**Desktop (please complete the following information):**
My own desktop:
 - OS: Debian testing
 - Browser: Chromium
 - Version: 80.0.3987
A client's desktop: Mac, Google chrome, version unknown

**Smartphone (please complete the following information):**
 - Browser [e.g. stock browser, Safari]

**Additional context**

**Comment by fweng322** [comment]
The result of bbb-conf --check:

https://pastebin.com/ViYarjgg

bbb-conf --status

https://pastebin.com/KZvEqrqK

**Comment by fweng322** [comment]
For example, in document 
https://docs.bigbluebutton.org/2.2/configure-firewall.html
Update FreeSwitch section

```
Edit /etc/bigbluebutton/nginx/sip.nginx to connect to the external IP address.

If you have configured SSL, use port 7443:

location /ws {
        proxy_pass https://EXTERNAL_IP_ADDRESS:7443;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_read_timeout 6h;
        proxy_send_timeout 6h;
        client_body_timeout 6h;
        send_timeout 6h;
}
```
However this "EXTERNAL_IP_ADDR" is undetermined at every reboot (or even sometimes the ppp would be dropped).  Originally it was set to my internal IP (192.168.x.x).  It doesn't work when assigning to hostname bbb.slat.org either.

There are several configurations like this and I don't know if they would cause problems in my scenario.

**Comment by basisbit** [comment]
You'll have to update bunch of config-files every time your IPv4 changes. I'd suggest you to host the BBB server on a dedicated server with gigabit internet connection in a datacenter.

**Comment by fweng322** [comment]
> You'll have to update bunch of config-files every time your IPv4 changes. I'd suggest you to host the BBB server on a dedicated server with gigabit internet connection and static IPv4 in a datacenter.

If I can of course I will :(

Is there any guide for such cases?  Besides bbb-conf --setip and /etc/bigbluebutton/nginx/sip.nginx, what else config files do I have to change?

**Comment by pnijjar** [comment]
I ran into this as well. I solved it by using configuration management (Saltstack) that would update all the relevant config files. You can simulate this with a shell script -- the script would use `dig +short your-external-alias.site | last` to get the IP corresponding to your alias (or maybe wget icanhazip.com) . Then it uses sed to paste that IP to each of the affected files, and copies those files to the right locations. This is ugly (and I do not have such a script written out in bash) but it can be done. 

 As far as I know the config files are those specified in the "set up behind a firewall" page. You really have to follow those instructions, or BBB audio will not work.

**Comment by fweng322** [comment]
> I ran into this as well. I solved it by using configuration management (Saltstack) that would update all the relevant config files. You can simulate this with a shell script -- the script would use `dig +short your-external-alias.site | last` to get the IP corresponding to your alias (or maybe wget icanhazip.com) . Then it uses sed to paste that IP to each of the affected files, and copies those files to the right locations. This is ugly (and I do not have such a script written out in bash) but it can be done.
> 
> As far as I know the config files are those specified in the "set up behind a firewall" page. You really have to follow those instructions, or BBB audio will not work.

Thanks for the hint.  I'll try it later.

So far the main problem I saw was the /etc/bigbluebutton/nginx/sip.nginx (freeswitch).  The Freeswitch bound to my internal IP interface (eth0) and the ProxyPass in sip.nginx is set to internal IP too (https://192.168.xxx.66:7443).  That explained why only machines at my home (in this IP range) could connect and use audio in bbb room.

However when connecting from outside (to my interface ppp0) they got 1007 (I guess) because the sip proxy is 192.168.xxx.66.  I tried to set ip in sip.nginx to https://bbb.slat.org:7443 but in vain.  I guess (again) it's because Freeswitch sip is bound to eth0 not ppp0, and it **requires** ip **not** hostname.

I also tried to get the public ip from ppp0 interface (using ip addr | grep ppp0 | awk ...) and used sed to replace everything (bbb-conf --setip, sip.nginx, ... etc).  The problem now becomes that I couldn't connect to sip because it couldn't get the SSL certification of "https://<my_public_ip>:7443" .

**Comment by matiasilva** [comment]
No update in two months. For follow up please use https://groups.google.com/forum/#!forum/bigbluebutton-setup and your support issue will be better handled there.
