### ISSUE TITLE
Unlock individual settings for a viewer

### ISSUE THREAD

**Issue by hasahmad** [bigbluebutton/bigbluebutton#9105]
Is it possible to edit/update lock setting for individual viewer?

I've locked all viewers from sharing webcam, chat, users list and mic. Now, I want to unmute the viewer, but not unlock all the other settings like (webcam, chat and users list) for that specific viewer. So, not fully unlocking, rather individually unlocking a specific settings for a specific viewer.

**Comment by sujaysreedhar** [comment]
+1

**Comment by iSamof** [comment]
Your issue is very similar to this one [8934](https://github.com/bigbluebutton/bigbluebutton/issues/8934)

In the end there will be only one solution implemented. It may be worth contributing to one conversation. But yes it seems everyone has this issue and a good solution is needed.
