### ISSUE TITLE
BBB-html5  chat limit msg length not work

### ISSUE THREAD

**Issue by heavenknows1978** [bigbluebutton/bigbluebutton#9106]
Dear Brothers

On latest html5-client  of bbb, this limit not work anymore, everything is limited to 5000 , not as we configured, please check this bug, i rmemebered that this bug only happen after upgraing to latest bb html5 via automatic update.

<module name="ChatModule" url="https://xxx.yyyy/ChatModule.swf?v=583"
			uri="rtmp://xxx.yyy/bigbluebutton"
			dependsOn="UsersModule"
			privateEnabled="true"
			groupEnabled="false"
			fontSize="14"
			baseTabIndex="801"
			colorPickerIsVisible="false"
			maxMessageLength="200"
			maxNumWindows="9"
		/>

<module name="SharedNotesModule" url="https://xxx.yyy/client/SharedNotesModule.swf?v=583"
			uri="rtmp://xxx.yyy/bigbluebutton"
			dependsOn="UsersModule"
			refreshDelay="500"
			toolbarVisibleByDefault="false"
			showToolbarButton="true"
			fontSize="14"
			maxMessageLength="400"
			maxNoteLength="400"
			enableDeleteNotes="false"
			hideAdditionalNotes="false"
		/>

root@BBB:~# bbb-conf --version

ii  bbb-apps                                   1:2.2.0-42                                      amd64        BigBlueButton applic                                                                                                             ations for Red5
ii  bbb-apps-akka                              2.2.0-77                                        all          BigBlueButton Apps (                                                                                                             Akka)
ii  bbb-apps-screenshare                       1:2.2.0-42                                      amd64        BigBlueButton screen                                                                                                             share module for Red5
ii  bbb-apps-sip                               1:2.2.0-11                                      amd64        BigBlueButton SIP mo                                                                                                             dule for Red5
ii  bbb-apps-video                             1:2.2.0-39                                      amd64        BigBlueButton video                                                                                                              module for Red5
ii  bbb-apps-video-broadcast                   1:2.2.0-8                                       amd64        BigBlueButton video                                                                                                              broadcast module for Red5
ii  bbb-check                                  1:2.2.0-5                                       amd64        Client check package                                                                                                              for BigBlueButton
ii  bbb-client                                 1:2.2.0-33                                      amd64        BigBlueButton Flash                                                                                                              client
ii  bbb-config                                 1:2.2.0-172                                     amd64        BigBlueButton config                                                                                                             uration utilities
ii  bbb-etherpad                               1:2.2.0-50                                      amd64        The EtherPad Lite co                                                                                                             mponents for BigBlueButton
ii  bbb-freeswitch-core                        2:2.2.0-97                                      amd64        BigBlueButton build                                                                                                              of FreeSWITCH
ii  bbb-freeswitch-sounds                      1:1.6.7-6                                       amd64        FreeSWITCH Sounds
ii  bbb-fsesl-akka                             2.2.0-61                                        all          BigBlueButton FS-ESL                                                                                                              (Akka)
ii  bbb-html5                                  1:2.2.0-874                                     amd64        The HTML5 components                                                                                                              for BigBlueButton
ii  bbb-mkclean                                1:0.8.7-3                                       amd64        Clean and optimize M                                                                                                             atroska and WebM files
ii  bbb-playback-presentation                  1:2.2.0-28                                      amd64        BigBluebutton playba                                                                                                             ck of presentation
ii  bbb-record-core                            1:2.2.0-63                                      amd64        BigBlueButton record                                                                                                              and playback
ii  bbb-red5                                   1:1.0.10-16                                     amd64        The Red5 server for                                                                                                              BigBlueButton
ii  bbb-transcode-akka                         2.2.0-8                                         all          BigBlueButton Transc                                                                                                             oder
ii  bbb-web                                    1:2.2.0-119                                     amd64        BigBlueButton API
ii  bbb-webhooks                               1:2.2.0-16                                      amd64        BigBlueButton Webhoo                                                                                                             ks
ii  bbb-webrtc-sfu                             1:2.2.0-99                                      amd64        BigBlueButton WebRTC                                                                                                              SFU
ii  bigbluebutton                              1:2.2.0-5                                       amd64        Open source web conf                                                                                                             erencing platform (bbb)
ii  ffmpeg                                     7:4.2.2-1bbb1~ubuntu16.04                       amd64        Tools for transcodin                                                                                                             g, streaming and playing of multimedia files
ii  libavcodec58:amd64                         7:4.2.2-1bbb1~ubuntu16.04                       amd64        FFmpeg library with                                                                                                              de/encoders for audio/video codecs - runtime files
ii  libavdevice58:amd64                        7:4.2.2-1bbb1~ubuntu16.04                       amd64        FFmpeg library for h                                                                                                             andling input and output devices - runtime files
ii  libavfilter7:amd64                         7:4.2.2-1bbb1~ubuntu16.04                       amd64        FFmpeg library conta                                                                                                             ining media filters - runtime files
ii  libavformat58:amd64                        7:4.2.2-1bbb1~ubuntu16.04                       amd64        FFmpeg library with                                                                                                              (de)muxers for multimedia containers - runtime files
ii  libavresample4:amd64                       7:4.2.2-1bbb1~ubuntu16.04                       amd64        FFmpeg compatibility                                                                                                              library for resampling - runtime files
ii  libavutil56:amd64                          7:4.2.2-1bbb1~ubuntu16.04                       amd64        FFmpeg library with                                                                                                              functions for simplifying programming - runtime files
ii  libopusenc0                                0.2.1-1bbb1                                     amd64        High-level API for e                                                                                                             ncoding Ogg Opus audio streams
ii  libpostproc55:amd64                        7:4.2.2-1bbb1~ubuntu16.04                       amd64        FFmpeg library for p                                                                                                             ost processing - runtime files
ii  libswresample3:amd64                       7:4.2.2-1bbb1~ubuntu16.04                       amd64        FFmpeg library for a                                                                                                             udio resampling, rematrixing etc. - runtime files
ii  libswscale5:amd64                          7:4.2.2-1bbb1~ubuntu16.04                       amd64        FFmpeg library for i                                                                                                             mage scaling and various conversions - runtime files
root@BBB:~#

**Comment by matiasilva** [comment]
Thanks for posting. If you still face an issue with this, please forward it to https://groups.google.com/forum/#!forum/bigbluebutton-setup where it can be better handled.
