### ISSUE TITLE
Browsers save URL with session token

### ISSUE THREAD

**Issue by paulmenzel** [bigbluebutton/bigbluebutton#9108]
bbb-html5 2.2.0-874

If users close their browsers, by for example shutting down their system, and wanting to join a room, they normally choose the URL from the browser history, or restore the tab. But, as the `sessionToken` is in the URL and it has expired, that fails.

It’d be great to have URLs, which allow to rejoin a room.

**Comment by Lukas2000** [comment]
Yes, I agree with @paulmenzel that this would improve the user experience.

**Comment by matiasilva** [comment]
Closing as no update in 2 months + the fact that the session token doesn't immediately expire and also you can just rejoin via the frontend.
