### ISSUE TITLE
Recording workflow breaks when on NFS

### ISSUE THREAD

**Issue by JF3** [bigbluebutton/bigbluebutton#9110]
**Describe the bug**
The publish-presentation script (i.e. `/usr/local/bigbluebutton/core/scripts/publish/presentation.rb` / `record-and-playback/presentation/scripts/publish/presentation.rb`) breaks, when `recording_dir` is on NFS.

**To Reproduce**
1. Move `/var/bigbluebutton` to NFS.
2. Record a meeting.
3. Wait until the publish workflow starts
4. See error in `/var/log/bigbluebutton/presentation/publish...log`:
```
ERROR -- : Directory not empty @ dir_s_rmdir - /var/bigbluebutton/recording/publish/presentation/3c97d8b95c28bf502989ad0b72860d371b2eeb0f-1587027100454/3c97d8b95c28bf502989ad0b72860d371b2eeb0f-1587027100454
ERROR -- : /usr/lib/ruby/2.3.0/fileutils.rb:1448:in `rmdir'
ERROR -- : /usr/lib/ruby/2.3.0/fileutils.rb:1448:in `block in remove_dir1'
ERROR -- : /usr/lib/ruby/2.3.0/fileutils.rb:1459:in `platform_support'
ERROR -- : /usr/lib/ruby/2.3.0/fileutils.rb:1447:in `remove_dir1'
ERROR -- : /usr/lib/ruby/2.3.0/fileutils.rb:1437:in `remove'
ERROR -- : /usr/lib/ruby/2.3.0/fileutils.rb:779:in `block in remove_entry'
ERROR -- : /usr/lib/ruby/2.3.0/fileutils.rb:1497:in `postorder_traverse'
ERROR -- : /usr/lib/ruby/2.3.0/fileutils.rb:777:in `remove_entry'
ERROR -- : /usr/lib/ruby/2.3.0/fileutils.rb:635:in `block in rm_r'
ERROR -- : /usr/lib/ruby/2.3.0/fileutils.rb:631:in `each'
ERROR -- : /usr/lib/ruby/2.3.0/fileutils.rb:631:in `rm_r'
ERROR -- : publish/presentation.rb:1377:in `<main>'
ERROR -- : exit
ERROR -- : publish/presentation.rb:1383:in `exit' 
ERROR -- : publish/presentation.rb:1383:in `rescue in <main>'
ERROR -- : publish/presentation.rb:1203:in `<main>'
```

**Expected behavior**
The publish workflow is expected not to fail and recordings should get published.

**Actual behavior**
The publish workflow fails and the recordings are not published.

** Proposed solution **
The `publish/presentation.rb` script is the only one in `/usr/local/bigbluebutton/core/scripts` employing `FileUtil.rm_r`, all other use `FileUtil.rm_rf`. Replacing `rm_r` with `rm_rf` solves the problem. Or formulated as diff:
```
1374c1374
<         FileUtils.rm_r(Dir.glob("#{$process_dir}/*"))
---
>         FileUtils.rm_rf(Dir.glob("#{$process_dir}/*"))
1377c1377
<         FileUtils.rm_r(Dir.glob("#{target_dir}/*"))
---
>         FileUtils.rm_rf(Dir.glob("#{target_dir}/*"))
```

**Comment by jibon57** [comment]
Already opened here: https://github.com/bigbluebutton/bigbluebutton/issues/9062
Possible solution: 
`sed -e 's|FileUtils\.rm_r(|FileUtils\.rm_rf(|g' -i /usr/local/bigbluebutton/core/scripts/publish/presentation.rb`

**Comment by Davka** [comment]
> Already opened here: #9062
> Possible solution:
> `sed -e 's|FileUtils\.rm_r(|FileUtils\.rm_rf(|g' -i /usr/local/bigbluebutton/core/scripts/publish/presentation.rb`

This solution works

**Comment by matiasilva** [comment]
Should be solved with the latest PR guys. Wait for the minor release or patch it in yourselves to test. Closing for now.
