### ISSUE TITLE
Short cut not working without clicking on icon to apply focus

### ISSUE THREAD

**Issue by paulmenzel** [bigbluebutton/bigbluebutton#9116]
bbb-html5 1:2.2.0-874, GNU/Linux, Microsoft Windows; Mozilla Firefox 74.0.1, Chrome

Trying to use the short cut *Space* to mute/unmute the microphone, it only works once pressing the icon/button with the mouse as otherwise the key press is ignored because of a wrong focus. To reproduce, just go to another window, and switch back to the conference window, and press *Space*. Note, the microphone setting is not toggled.

**Comment by antobinary** [comment]
Just seeing this now...
Alt+M is the shortcut for mute toggle. Space is just tied to the last focus item.

I use Alt+M regularly and it's independent from the focus.

You may find https://github.com/bigbluebutton/bigbluebutton/pull/9114 interesting

Closing as this functions as designed. We can reopen if anyone would like to discuss this in future
