### ISSUE TITLE
bbb-apps-akka Download too slow

### ISSUE THREAD

**Issue by likai3016218058** [bigbluebutton/bigbluebutton#9117]
Hello!
I configure BBB on a cloud server, but the download speed is very slow when I install it. Is there any good solution? Coordinate China.

**Console output**
42% [1 bbb-apps-akka 458 kB/38.9 MB 1%]                                                                                                          2,727 B/s 3d 6h 14min 16s

**Comment by trs80** [comment]
#9206 says to try https://packages-eu.bigbluebutton.org

**Comment by matiasilva** [comment]
No follow up, assumed to be fixed. Please use https://groups.google.com/forum/#!forum/bigbluebutton-setup for further support queries.

**Comment by OmidAhmadyani** [comment]
packages-eu is slow too
