### ISSUE TITLE
Translation on html5client invite area

### ISSUE THREAD

**Issue by sr33rajv** [bigbluebutton/bigbluebutton#9120]
Hello,
How can I add a translation or modify the "To invite someone to the meeting, send them this link" text on BBB html5client?

![Screenshot 2020-04-17 at 3 07 07 PM](https://user-images.githubusercontent.com/54975410/79555373-1d7b1000-80bd-11ea-800e-d06771fbc037.png)

**Comment by Sea444** [comment]
Hm, the text above and below can be set in \usr\share\bbb-web\WEB-INF\classes\bigbluebutton.properties (defaultWelcomeMessage and defaultWelcomeMessageFooter). But this one?

**Comment by matiasilva** [comment]
That's a Greenlight property. Please ask here: https://groups.google.com/forum/#!forum/bigbluebutton-greenlight for support.

**Comment by MeinhartEsrohr** [comment]
Hello, do you have a solution to your problem? I would like to add a new line after Link: 
Like this:
Link:
https://domain.com/b/fdh-434-fdsf
