### ISSUE TITLE
Breakoutrooms

### ISSUE THREAD

**Issue by jfssystems** [bigbluebutton/bigbluebutton#9122]
I have two bbb server. Using breakout rooms through joining from moodle does work on one bbb server but not on the other bbbserver. 
On the server where the it does not work, i get redirected to greenlight, whereas on the other server, i get redirected into the breakout room - as aspected.

What might be the issue?

Thx in advance.

**Comment by svoeth** [comment]
possible duplicate of #9080

**Comment by jfssystems** [comment]
As of the related Ticket i could also find an Checksum error.
o.b.api.ParamsProcessorUtil - checksumError: query string checksum failed. our: [c283e8abf3def753c5a1b63c818124ff27eaae261521a2d69794dad5acd23571], client: [38bcd
21769c57b1709ad2e2a46b70fdab62b281ca0d52a3354b374badab23ad2]


The only diffrence bettween my 2 bbb server which i saw right now is a difference in the version build of meteor :

bbb-conf --check

/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml (HTML5 client)
                             build: 862

/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml (HTML5 client)
                             build: 870


As an Workaround i did enable LDAP Auth, logged in via greenlight and can then join the breakout room from the moodle initialized meeting room.

**Comment by jfssystems** [comment]
update, workaround does not work (anymore?)

**Comment by jfssystems** [comment]
is not related to moodle.  also creating meeting rooms and creating breakout rooms via greenlight doesnt work.  Logs:

`
Apr 19 18:53:16 vc00 run-prod.sh[1103]: 2020-04-19T18:53:16.673+02:00 INFO o.b.api.ParamsProcessorUtil - CHECKSUM=f6532260e6e4cf2cfdba0bb2027d30c462c4416666edcc35f40f8c21c7cfa150 length=64
Apr 19 18:53:16 vc00 run-prod.sh[1103]: 2020-04-19T18:53:16.673+02:00 INFO o.b.api.ParamsProcessorUtil - SHA256 d94d3fbede43a7d1361785ee5e527e00379f94c6181d343803d5973762df6056
Apr 19 18:53:16 vc00 run-prod.sh[1103]: 2020-04-19T18:53:16.673+02:00 INFO o.b.api.ParamsProcessorUtil - query string after checksum removed: [fullName=Bob+Random&isBreakout=true&joinViaHtml5=true&meetingID=41659e4c844bc8077303639798becd8ff9bd5426-1587314955644&password=K._OLRo0e-UH&redirect=true&userID=w_y3vrb44tfgjk-2]
Apr 19 18:53:16 vc00 run-prod.sh[1103]: 2020-04-19T18:53:16.673+02:00 INFO o.b.api.ParamsProcessorUtil - checksumError: query string checksum failed. our: [d94d3fbede43a7d1361785ee5e527e00379f94c6181d343803d5973762df6056], client: [f6532260e6e4cf2cfdba0bb2027d30c462c4416666edcc35f40f8c21c7cfa150]
Apr 19 18:53:16 vc00 run-prod.sh[1103]: 2020-04-19T18:53:16.673+02:00 DEBUG o.b.web.controllers.ApiController - ApiController#invalid You did not pass the checksum security check
Apr 19 18:53:16 vc00 run-prod.sh[1103]: 2020-04-19T18:53:16.673+02:00 DEBUG o.b.web.controllers.ApiController - JSON Errors [{"message":"You did not pass the checksum security check","key":"checksumError"}]`


Reinstalling Packages as suggested  in #9080 
did not work. Also recordings in Moodle where lost. So i did roll back to the latest snapshot.

**Comment by jfssystems** [comment]
solved setting new secret.
bbb-conf --setsecret
