### ISSUE TITLE
Copies of a user

### ISSUE THREAD

**Issue by Yzoop** [bigbluebutton/bigbluebutton#9124]
**Describe the bug**
Recently I've faced a strange bug: if I click (a single left mouse click) on a button to connect to a conversation (bbb conference) several pages of a conference are being opened, so as a result several copies of a student are connected to the conference.
**To Reproduce**
1. Run a browser-1 (Edge, for example), go to a page where a button to connect to a conversation is
2. Run browser-2(Google Chrome), go to the same page with the same button
3. Click on the button in browser-2
4. See several pages opened in the browser-1

**Expected behavior**
Open a single page in the browser-2, where the button was clicked

**Desktop (please complete the following information):**
 - OS: Windows 
 - Browser Google Chrome, Microsoft Edge
 - GC: 81.0.4044.111

**Comment by basisbit** [comment]
what version of BigBlueButton are you using? run `bbb-conf --check` to get the version number and more details.

**Comment by matiasilva** [comment]
Might be a frontend issue. No follow up in two months, so I'm closing this. Feel free to follow up in the support group:https://groups.google.com/forum/#!forum/bigbluebutton-setup
