### ISSUE TITLE
add custom audio / video live stream to "Share an external video" dialog

### ISSUE THREAD

**Issue by vukbgit** [bigbluebutton/bigbluebutton#9129]
Hello, I can't find any documentation about adding a custom stream to the "Share an external video" dialog, is it currently possible?

I would like to embed into room videos from other sources than the ones specified (YouTube, Vimeo, Instructure Media, Twitch and Daily Motion), in particular not from video sharing platforms but - for example - a custom .m3u8 stream.

Thanks and keep up the good work

**Comment by peterjiz** [comment]
Could we use the existing WebRTC websockets to stream external content into a room? If so, how? I was able to connect to the websocket but not dump any video/audio dump..

**Comment by kaffeeknecht** [comment]
That would be great. We use Wowza Streaming Server to deliver Videostreams to our students. If one could just take the .m3u8 from the Wowza to play the video in BBB would be great

**Comment by gnaegi** [comment]
I second this. Would be usefull to stream the cam for chemical experiments, I see many other usefull scenarios. E.g. by using OBS Software (also open source).

**Comment by Cicciodev** [comment]
I "third" this! 
Anyhow is there already any way to stream from hardware? My university has some epiphan pearl mini, they have a dozen of option for hardware streaming, I would like to know if any of this can be used on BBB.
(yeah I could stream on youtube and then take it in BBB but I cannot make my stream public or accessible with a particular link)

**Comment by matiasilva** [comment]
The HTML5 client uses react-player which should allow for playing of .m3u8 files with `hls.js`, see http://cookpete.com/react-player/

**Comment by lonesomewalker** [comment]
Unfortunately not, this player is broken.
I tried it now with several streams, both commercial and self-streamed.
Sometimes they work, sometimes not. Especially the live-streamed ones are not loading.

**Comment by pedrobmarin** [comment]
Merging this with https://github.com/bigbluebutton/bigbluebutton/issues/8678 to improve any updates on this subject.
