### ISSUE TITLE
File upload returns a 500 error

### ISSUE THREAD

**Issue by fabriziomanunta** [bigbluebutton/bigbluebutton#9130]
**Uploading a presentation returns a 500 error and does not return to the room**
I'm in the room as moderator and when I try to upload a pdf of 1.6MB (~50 pages) 
with short name (dispensa.pdf) the upload fails not showing just the page background and I have to refresh the page back to the meeting room.

Here is a snippet of the server log:
```2020-04-17T13:16:11.301Z ERROR o.a.c.c.C.[.[.[.[grailsDispatcherServlet] - Servlet.service() for servlet [grailsDispatcherServlet] in context with path [] threw exception [Could not resolve view with name 'upload' in servlet with name 'grailsDispatcherServlet'] with root cause
javax.servlet.ServletException: Could not resolve view with name 'upload' in servlet with name 'grailsDispatcherServlet'
	at org.springframework.web.servlet.DispatcherServlet.render(DispatcherServlet.java:1266)
```
the post request is:
```
[my_domain]/bigbluebutton/presentation/PresUploadToken-7whvlo9hDEFAULT_PRESENTATION_POD-w_7hzejknfde46/upload 
```
**Desktop:**
 - OS:  Ubuntu 18.04.4 LTS
 - Browser: Chrome
 - Version: 80.0.3987.163

**BigBlueButton Server 2.2.5 (1848)**
Kernel version: 4.15.0-1060-gcp
Distribution: Ubuntu 16.04.6 LTS (64-bit)
Memory: 16424 MB
CPU cores: 4

The server is on GCP

**Comment by fabriziomanunta** [comment]
It's fixed now.
Probably a folder permission issue, after I moved the recording to a different location as shown in [http://docs.bigbluebutton.org/2.2/customize.html#move-recordings-to-a-different-partition](http://docs.bigbluebutton.org/2.2/customize.html#move-recordings-to-a-different-partition) the whole folder was owned by root so I did ```chown -R bigbluebutton:bigbluebutton /var/bigbluebutton``` and then ```chown -R red5:red5 /var/bigbluebutton/screenshare```

**Comment by basisbit** [comment]
@fabriziomanunta could you please close this issue if it is fixed for you? Thanks!

**Comment by fabriziomanunta** [comment]
It seems like it was a folder permission issue

**Comment by fabriziomanunta** [comment]
@basisbit sure, sorry :)
