### ISSUE TITLE
Virtual Background for Webcam Users

### ISSUE THREAD

**Issue by DA-Michael** [bigbluebutton/bigbluebutton#9131]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
When sharing your webcam, you should be able to choose from a few example backgrounds, or upload a custom background for your webcam, so that the other attendees only see you, not where you are.

**Describe alternatives you've considered**
Only alternative is keeping webcams off for those who are concerned about the privacy of their environment

**Additional context**
I run a number of BBB servers, and especially with everyone working from home, I'm getting requests for a 'virtual background,' something that only shows the user, and not their surroundings. Example here: https://support.zoom.us/hc/en-us/articles/210707503-Virtual-Background
I'm not sure what's involved in getting this implemented, but it is a feature that would get a lot of use during this time with everyone working from home.

**Comment by Jossef-767** [comment]
Jitsi also allows "background blur"

**Comment by rmmur** [comment]
users demand to create corporate funds in the meetings.

**Comment by trs80** [comment]
https://medium.com/@jmlbeaujour/real-time-matting-of-webcam-video-on-the-browser-part-1-2c71a330ed08

**Comment by jvfiel** [comment]
hi is someone working on this?

**Comment by ffdixon** [comment]
At the time of this writing, we (the core developers) are pretty focused on the current release (2.2) and next (2.3).  There is no plans to add blur or background, but this is a fairly isolated feature (aside from some UI), so if anyone wants to take a shot at it and sending us a pull request, we would welcome your help.

**Comment by sadn1ck** [comment]
How would one go about implementing this?

**Comment by matiasilva** [comment]
I believe someone posted an article above. It seems you have two options, do the video manipulation client side or server side. I think the existing implementations do it all client side (guessing from how much slower my computer gets). Worth searching around online what existing implementations do and seeing how that can fit into the HTML5 client. For further development talk, you'd probably get more feedback in the developer group forum.

**Comment by agussang** [comment]
> At the time of this writing, we (the core developers) are pretty focused on the current release (2.2) and next (2.3). There is no plans to add blur or background, but this is a fairly isolated feature (aside from some UI), so if anyone wants to take a shot at it and sending us a pull request, we would welcome your help.

When 2.3 rellease?

**Comment by iam-TJ** [comment]
I'm investigating and working on integrating [bodyPix](https://ml5js.org/reference/api-BodyPix/) into the HTML5 client. Due to other commitments it might take a couple of months so any collaborators are welcome.

**Comment by shubsengupta** [comment]
Just bumping up an old issue - Google just announced some changes to https://github.com/google/mediapipe that may help with this? https://ai.googleblog.com/2020/10/background-features-in-google-meet.html

**Comment by ffdixon** [comment]
We saw that announcement from Google.  We pretty focused on 2.2 and 2.3-dev at the moment, but we would be interested if anyone in the community wants to explore Google's work further.  Ideally, just create a stand-alone prototype showing the background blur in a single camera.  

Such as prototype (and maybe Google already provides it) would help us see how easy it would be to incorporate this into BigBlueButton.

**Comment by sadn1ck** [comment]
@ffdixon I had actually done a small prototype using bodypix, links given below, I had made it up in a few hours so it only works with one camera (no switching to front), but it works on my laptop at least. 

To be noted, isn't exactly blurring because I am replacing the background as well. But blurring would just need another function in bodypix instead of the one I implemented.

https://github.com/sadn1ck/bg-removal-bodypix

**Comment by Dimitrie23** [comment]
> 
> 
> @ffdixon I had actually done a small prototype using bodypix, links given below, I had made it up in a few hours so it only works with one camera (no switching to front), but it works on my laptop at least.
> 
> To be noted, isn't exactly blurring because I am replacing the background as well. But blurring would just need another function in bodypix instead of the one I utilised.
> 
> https://github.com/sadn1ck/bg-removal-bodypix
> 
> And yes, google also has a couple prototypes on their bodypix page here https://github.com/tensorflow/tfjs-models/tree/master/body-pix

Isn't this the same technology that Jitsi Meet uses for their background blurring? The Jitsi Meet integration does not work well for me on my T460p from lenovo and utilises 100% CPU load with very few frames. So the performance with bodypix is very low. Utilising the media pipe of google seems more promising if their benchmarks are correct.

**Comment by ffdixon** [comment]
Not sure if Google has open sourced all the components, but their recent work looks very promising with WebAssembly.  https://ai.googleblog.com/2020/10/background-features-in-google-meet.html

**Comment by fm-sys** [comment]
[jitsi-meet](https://github.com/jitsi/jitsi-meet) has a virtual background functionality. Maybe we can cooperate with them...

**Comment by uka-support** [comment]
Jitsi only has blurred background functionality which is really expensive on the client (my fan starts spinning immediatly when I activate this and I've got no bad machine). At least that's the only available option on https://meet.jit.si

**Comment by drlight17** [comment]
> I'm investigating and working on integrating [bodyPix](https://ml5js.org/reference/api-BodyPix/) into the HTML5 client. Due to other commitments it might take a couple of months so any collaborators are welcome.

I did something in this direction too. I don't have experience of meteor programming, so I did bodyPix integration using some jquery for GUI mainly. See this [branch](/drlight17/bigbluebutton/tree/bodypix_support)

**Comment by drlight17** [comment]
Also waiting when google mediapipe models for background processing will be available for everyone as they use modified MobileNetV3 and other magic with very promising performance/quality ratio

**Comment by hschlender** [comment]
This is a very important feature. We are using BBB in education (university and schools) and also for exams and we have lot's of discussion about that.

The way Google does it with Google Meet is very interesting and works like a charm on my "old" ThinkPad, while other client sided solutions don't. I'm pretty sure that's the goto.

**Comment by Kittenhunter** [comment]
Hello, we have a customer who had us evaluate several solutions for background removal/swapping for BBB recently.
They're checking for a third party app, but are also interested in having such a feature directly built-in in BBB.
Since it doesn't make sense for them to maintain a custom version of BBB and they're using BBB for some time now, they wanted to give back to the community and asked, if the feature for background bluring/swapping would be maintained by the community in future releases?
They also want to swap the background and not just blur it, so maybe some of you have an idea where the images could be stored? Does BBB support storing such images server side? They have 3 BBB servers, where 2 of them are behind a load balancer.

@drlight17 We have also tried your solution and it works really good but is quite heavy on performance. If we would develop such a feature, are we allowed to use your current solution as basis for future development?

**Comment by drlight17** [comment]
> @drlight17 We have also tried your solution and it works really good but is quite heavy on performance. If we would develop such a feature, are we allowed to use your current solution as basis for future development?

As I said before it is heavy because it depends on current bodyPix models that are not good enough in terms of optimization. Maybe[ Google mediapipe models](https://ai.googleblog.com/2020/10/background-features-in-google-meet.html) will be free to use someday - they showed a very fast and qualitative results.
As for use of my solution - yes, of course. You may freely use it. Just mention me as a contributor =)

**Comment by hex-m** [comment]
As Jitsi Meet was mentioned multiple times: They have a [new Version](https://jitsi.org/blog/march-update-new-toolbar-ui-virtual-backgrounds-and-more/) and replaced the old "background blur" with "virtual backgrounds".

> we are using TFLite with the MediaPipe Meet Segmentation model as outlined in their [blog post](https://ai.googleblog.com/2020/10/background-features-in-google-meet.html). This, paired with WebAssembly SIMD instructions provided the performance boost we needed to improve blur and implement virtual backgrounds

**Comment by ffdixon** [comment]
Nice!  It looks like Jitsi managed to build upon the work of Google.  

@Kittenhunter this would be a good project if you (and others) wanted to do a deep dive into this and port this to BigBlueButton.  Everyone in the community would benefit.

**Comment by wruppelx** [comment]
> Hello, we have a customer who had us evaluate several solutions for background removal/swapping for BBB recently.
> 
> They're checking for a third party app, but are also interested in having such a feature directly built-in in BBB.
> 
> Since it doesn't make sense for them to maintain a custom version of BBB and they're using BBB for some time now, they wanted to give back to the community and asked, if the feature for background bluring/swapping would be maintained by the community in future releases?
> 
> They also want to swap the background and not just blur it, so maybe some of you have an idea where the images could be stored? Does BBB support storing such images server side? They have 3 BBB servers, where 2 of them are behind a load balancer.
> 
> 
> 
> @drlight17 We have also tried your solution and it works really good but is quite heavy on performance. If we would develop such a feature, are we allowed to use your current solution as basis for future development? 

@Kittenhunter Are your extensions available in one of the forked repositories? Can you share some more information? Thx.

**Comment by Kittenhunter** [comment]
@wruppelx Haven't developed anything yet. Still in evaluation phase.

**Comment by HeavyHorst** [comment]
Here is another interesting model: https://github.com/Volcomix/virtual-background#ml-kit-selfie-segmentation
Here is a demo: https://volcomix.github.io/virtual-background/

It is much faster than bodyPix on my machine (13 FPS vs 60 FPS).

**Comment by drlight17** [comment]
> Here is another interesting model: https://github.com/Volcomix/virtual-background#ml-kit-selfie-segmentation
> Here is a demo: https://volcomix.github.io/virtual-background/
> 
> It is much faster than bodyPix on my machine (13 FPS vs 60 FPS).

Very promising! Looks like it is Google MediaPipe based model. I'll look forward to use it in my repo. Thanks!

**Comment by greenycat** [comment]
How to disable in the root this great "feature"?
