### ISSUE TITLE
Firewall ports. Documentation vs FAQ

### ISSUE THREAD

**Issue by jsalatiel** [bigbluebutton/bigbluebutton#9132]
What are the ports needed to run BBB.
In documentation ( https://docs.bigbluebutton.org/2.2/configure-firewall.html )  I read:
```
When BigBlueButton is protected behind a firewall, you need to configure the firewall to forward the following incoming connections to BigBlueButton:

    TCP/IP port 22 (for SSH)
    TCP/IP ports 80/443 (for HTTP/HTTPS)
    UDP ports in the range 16384 - 32768 (for FreeSWITCH/HTML5 RTP streams)
```

On FAQ ( https://docs.bigbluebutton.org/support/faq.html ) I read:
```
For TCP ports, clients must be able to connect to the BigBlueButton server on port 80/443 (HTTP/HTTPS), 7443 (audio), and 1935 (RTMP).
For UDP ports, clients must be able to connect on a port within the range 16384-32767 for WebRTC-based audio.
```

Are 7443 (audio), and 1935 (RTMP) needed or not ?

**Comment by basisbit** [comment]
7443 and 1935 should not be opened in your firewall when using default BigBlueButton installations with the usual setup. I'll create a pull request to update the documentation.
