### ISSUE TITLE
HTML replied "success" but BBB is not working

### ISSUE THREAD

**Issue by LimAloysius** [bigbluebutton/bigbluebutton#9133]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Actual behavior**

**Screenshots**

**BBB version (optional):**
BigBlueButton continually evolves. Providing the version/build helps us to pinpoint when an issue was introduced.
Example:
$ sudo bbb-conf --check | grep BigBlueButton
BigBlueButton Server 2.2.2 (1816)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, Mac]
 - Browser [e.g. Chrome, Safari]

**Smartphone (please complete the following information):**
 - Browser [e.g. stock browser, Safari]

**Additional context**

**Comment by LimAloysius** [comment]
Hi,
BBB installation completed successfully. But when I accessed my website: https://u12b.tech. The browser replied "success",but not able to login into BBB. I can login with the Demo API and see all features are available though. I tried to access with API through Moodle, also not working.

Am i missing something here. Is there any documentation on how to access BBB after a successful installation. Thank you.

**Comment by LimAloysius** [comment]
Hi,

Besides, i using Ubuntu server 16.04 and MacOS for desktop.

**Comment by lonesomewalker** [comment]
BBB can't be "accessed", because it is API controlled.
If you want to have a graphical interface, you can try Greenlight.

**Comment by LimAloysius** [comment]
Besides, how do i use API to connect BBB to Moodle? Must Moodle goes through Greenlight to reach BBB?

**Comment by lonesomewalker** [comment]
No, Moodle is using the API.
But if you have entered the wrong credentials or the wrong URL, you won't be able to access BBB.

This here:
https://u12b.tech/bigbluebutton/

looks okay to me.
What did you enter in your Moodle plugin?

https://u12b.tech/bigbluebutton/ or https://u12b.tech/

Try both ;-)

**Comment by LimAloysius** [comment]
i have been using https://u12b.tech/bigbluebutton/ or https://u12b.tech/. 

The reply has been "success 2.0".

**Comment by LimAloysius** [comment]
Reply has been "success 2.0" but BBB does not opened up. Does it means https://u12b.tech/ is reached but some settings must be done either in Moodle or BBB?

**Comment by LimAloysius** [comment]
sudo bbb-conf --status
nginx —————————————————► [✔ - active]
freeswitch ————————————► [✔ - active]
redis-server ——————————► [✔ - active]
bbb-apps-akka —————————► [✔ - active]
bbb-transcode-akka ————► [✔ - active]
bbb-fsesl-akka ————————► [✔ - active]
red5 ——————————————————► [✔ - active]
tomcat7 ———————————————► [✔ - active]
mongod ————————————————► [✔ - active]
bbb-html5 —————————————► [✔ - active]
bbb-webrtc-sfu ————————► [✔ - active]
kurento-media-server ——► [✔ - active]
etherpad ——————————————► [✔ - active]
bbb-web ———————————————► [✔ - active]
bbb-lti ———————————————► [✔ - active]

I have the above status from BBB - everything needed is working - but Moodle cannot call on BBB but return a "success" reply. 

Also did this :wget -O --quiet https://u12b.tech/bigbluebutton/api

Moodle still not connecting to BBB.

**Comment by LimAloysius** [comment]
1. What version of Moodle are you using? 3.8
  2.  What version of the Moodle BigBlueButtonBN integration are you using? BBB v2.2
  3.  What BigBlueButton server are you using (your or test-install)? BBB server running on Ubuntu
   4. If yours, is it behind a firewall? Yes - behind a firewall.

**Comment by prlanzarin** [comment]
Closing this as stale. Re-open if it's an actual issue.
Mailing lists for setup debugging.
