### ISSUE TITLE
Using Moodle Mobile App - BBB Waiting for Moderator = Yes (Checked) -- never can join meeting

### ISSUE THREAD

**Issue by tallthom** [bigbluebutton/bigbluebutton#9134]
**Describe the bug**
Even after the moderator starts the meeting, the users in the Mobile App are not shown the "Join Session" button. If I don't use that setting in the BBB activity, then they can join the session without an issue.

Even clearing the mobile cache, uninstalling the app... doesn't show the meeting has been started.
NOTE: In the browser, it works fine although I have to refresh the page in order to see the meeting is ready.

**To Reproduce**
1. Create a BBB activity in your course.
2. Check the "Wait for moderator" setting. 
3. Perform a "join session" before the moderator FROM THE MOODLE MOBILE APP.
4. The app reports "waiting for moderator" to the student.
5. Then start the meeting as the moderator. 
6. The student won't be told the meeting has started. Even after changing the setting in BBB not to wait, the Mobile App gets "stuck"

**Expected behavior**
When the moderator joins the meeting, the student should see the "join session" button appear in the Mobile app screen.

**Actual behavior**
Student gets stuck waiting for the moderator.

**Screenshots**

**Desktop (please complete the following information):**
Not an issue on the desktop.

**Smartphone (please complete the following information):**
Either iOS or Android mobile has the same issue. Latest version of the Moodle Mobile application.

**Additional context**
Given the move online due to coronavirus, it is critical for our students to be able to access BBB from the mobile app. The workaround we have used is to force "wait for moderator" to always be unchecked.

**Comment by Sea444** [comment]
related to https://github.com/bigbluebutton/greenlight/issues/1259 ?

**Comment by tallthom** [comment]
Thanks for the reply @Sea444 -- we don't have Greenlight installed. We're using Moodle for our frontend.

**Comment by elbissat** [comment]
Hello, we have the same issue

**Comment by partecipazionelab** [comment]
I'm experiencing the same behaviour as well
