### ISSUE TITLE
Using Moodle Mobile App - Previous Recordings/Presentations not visible

### ISSUE THREAD

**Issue by tallthom** [bigbluebutton/bigbluebutton#9135]
**Describe the bug**
If a few sessions are recorded in a BBB activity in Moodle, the students using the Moodle Mobile App cannot see the links to those sessions. They just don't appear.

**To Reproduce**
1. Create a BBB activity with recordings.
2. Launch the activity and record a session.
3. After the session is processed, view the presentation in a browser to confirm it works.
4. Try to view the same presentation using the Moodle Mobile App -- no presentation appears.

**Expected behavior**
Underneath the "Join Session" button should appear a list of presentation recordings which a student can access.

**Actual behavior**
No presentations are visible.

**Screenshots**
(will add later)

**Desktop (please complete the following information):**
 Not an issue on desktop computers or browsers.

**Smartphone (please complete the following information):**
 Either iOS or Android versions of the Moodle Mobile application show this issue.

**Additional context**
Critical due to the move to online classes at many institutions due to the pandemic. Not having access to the recordings in the Mobile App requires students to be redirected to browsers for viewing recordings.

**Comment by tallthom** [comment]
![photo_2020-04-19_17-24-54](https://user-images.githubusercontent.com/1357329/79683112-b5fec500-8262-11ea-8be1-94c9d45f5c90.jpg)
![photo_2020-04-19_17-24-59](https://user-images.githubusercontent.com/1357329/79683116-b8f9b580-8262-11ea-8635-91dad6592d66.jpg)
Here are two screenshots -- one from the Mobile browser (Safari) and one from the Moodle Mobile App -- same activity, doesn't show recordings.

**Comment by matiasilva** [comment]
Closing as no update in two months + support belongs elsewhere (https://groups.google.com/forum/#!forum/bigbluebutton-setup) or even the moodle plugin repository.
