### ISSUE TITLE
Video pinning possible?

### ISSUE THREAD

**Issue by irmhild314** [bigbluebutton/bigbluebutton#9136]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
When sharing webcams, it should be possible to select and pin one (to fix place and size) and to change pinning after some time (for user, and moderator)  

**Describe alternatives you've considered**
Don't know, splitting BBB over two (or more) monitors could also be helpful.

**Additional context**
I'm deaf and online I'm always working with two or more sign language interpreters. For me it is very important to see the right (active) interpreter all the time and to change between my different interpreters. Furthermore, I need to see my interpreters large enough for being able to understand over time.

**Comment by iSamof** [comment]
In the old flash client we had the option of switching to one of many layouts. That was very useful.

I think there is currently a project for creating a "Layout Editor" for the HTML5 client. Such a layout editor will hopefully enable us to do what you are suggesting and give us the ability to create all kinds of application specific UI variations and functions.

**Comment by irmhild314** [comment]
Thank you very much for this helpful information! 
Do you have any idea, how long it will be before then? Like a month, one year, more than a year?

**Comment by iSamof** [comment]
You are most welcome. I am not involved with the project and have not seen any expected release info. 

It has been a principle at BBB to focus on reliable and stable code rather than be pressured by a release schedule. 

But I am hoping a relevant team member can give us some progress info just to excite us (some more) ... @ffdixon  ... not naming names of course :-)

BBB is a breath of fresh air ... no, it is air :-)

**Comment by iSamof** [comment]
My One Great Wish (re the layout editor): **Totally or mostly JS/CSS based**

Using Ruby etc would severely impede our own custom developments.

**Comment by nickpl456** [comment]
As a temporary work around if you are using Chrome on a Mac or PC you can right click on the webcam that you want to pin and from the menu select Picture-In-Picture. This will give you a floating video window you can move around and resize as needed.

**Comment by pavansaisp** [comment]
Is there any script to activate  Picture in Picture automatically in Big Blue Button .

**Comment by matiasilva** [comment]
@pavansaisp Use Firefox!

**Comment by prlanzarin** [comment]
Merging into https://github.com/bigbluebutton/bigbluebutton/issues/13702
