### ISSUE TITLE
Iphone microphone is not working

### ISSUE THREAD

**Issue by mesoshqip** [bigbluebutton/bigbluebutton#9137]
Hi

I have installed BigBlueButton Server 2.2.0-rc-6 (1710)
I have some problems with the iPhone microphone. When I am connecting to my server I can't hear myself, but when I test in the test.bigbluebutton.org  is working..
Can you help me? What I did wrong?

**Comment by jibon57** [comment]
You should upgrade your server to latest stable version of BBB which is 2.2.5. It should work

**Comment by mesoshqip** [comment]
Thank you... Its work
