### ISSUE TITLE
Invalid BigBlueButton Endpoint and Secret....which fix itself on conference starting!

### ISSUE THREAD

**Issue by marcocattaneogotam** [bigbluebutton/bigbluebutton#9138]
Hi,

I get an "Invalid BigBlueButton Endpoint and Secret" error when I start a meeting, but if I reload the same page twice it fix itself and start correctly.

This used to happen every time I start a new meeting.

I've already open an issue for Greenlight (this is the full thread: https://github.com/bigbluebutton/greenlight/issues/1283), but they tell me to open a new issue here for this log line:

> @marcocattaneogotam Looks like your BigBlueButton server is sometimes returning an error when it tries to start
> 
> > ERROR: [e93babcb-816c-41ca-8536-c58bdb4008cd] BigBlueButtonException: Impossible to convert XML to hash. Error: Declarations can only occur in the doctype declaration.
> 
> I'm not quite sure what would cause that. You might have more luck posting in the forums or the BigBlueButton repo

Thanks

**Comment by marcocattaneogotam** [comment]
Help!

**Comment by fernandoheb** [comment]
@marcocattaneogotam did you find a solution?

**Comment by marcocattaneogotam** [comment]
No :-(

**Comment by matiasilva** [comment]
Try asking on https://groups.google.com/forum/#!forum/bigbluebutton-setup where others may have run into the same error. I'll close this issue for now but if this turns into a bug you'll need to submit a new one.
