### ISSUE TITLE
/usr/share/bbb-web/WEB-INF/classes/spring/turn-stun-servers.xml

### ISSUE THREAD

**Issue by LimAloysius** [bigbluebutton/bigbluebutton#9140]
**Describe the bug**

**Installation type**
Did you install manually or did you use the bbb-install script?

**Console output**
Please include the full console output from the install.

**Additional context**

**Comment by LimAloysius** [comment]
Hi,

Can someone share the original file for :/usr/share/bbb-web/WEB-INF/classes/spring/turn-stun-servers.xml? 

i need to know what is the URL for :<!--bean id="iceCandidate1" class="org.bigbluebutton.web.services.turn.RemoteIceCandidat$
        <constructor-arg index="0" value="???"/>
What is the purpose of the iceCandidate1?

**Comment by svoeth** [comment]
https://github.com/bigbluebutton/bigbluebutton/blob/develop/bigbluebutton-web/grails-app/conf/spring/turn-stun-servers.xml

**Comment by DmytrijUa** [comment]
Also interested in string assignment bean id="iceCandidate1", there is no explanation in the documentation, would like to see an example.

**Comment by GhaziTriki** [comment]
Not an issue.
