### ISSUE TITLE
Organization menu in Greenlight

### ISSUE THREAD

**Issue by Magnou17** [bigbluebutton/bigbluebutton#9141]
I had created my administrator user using : "docker exec greenlight-v2 bundle exec rake user:create["Administrateur EGEON","egeon91@free.fr","MMMNNNNN","adminbbb"]"
Connection to my account is fine but when i look at my menu on to right "organization menu is missing"!
Something more to do in configuration?
Rgds
Chris

[Print menu.pdf](https://github.com/bigbluebutton/bigbluebutton/files/4498514/Print.menu.pdf)

**Comment by mrkeksi** [comment]
The last option should be only „admin“ not adminbbb. That’s the role that the user became.

**Comment by Magnou17** [comment]
Ok thanks, that's rights now!
Rgds
Chris
