### ISSUE TITLE
iPhone Browser

### ISSUE THREAD

**Issue by Magnou17** [bigbluebutton/bigbluebutton#9143]
My platform is working fine with mobiles phones Android using Google Chrome or Vivaldi Browser but it's don't work with firefox.
iPhone using Safari browser don't work to. 
Is there some configurations to do inside BigBlueButton?
Rgds
Chris

**Comment by Patira** [comment]
As you can see here:
http://docs.bigbluebutton.org/support/faq.html#support-for-mobile-devices

BBB runs within the default Chrome browser on Android 6.0+ and the default Safari Mobile browser on iOS 12.2+. All the features of BigBlueButton are available on Android and iOS except screen sharing.

Now, can you elaborate more on the problem with Safari on iOS?

**Comment by Magnou17** [comment]
When i use Firefox on Android Smartphone or iPhone using Safari (v5.1.7) i get "error 1007".
To inform i have installed stun-turn platform to avoid NATP problem. Today it's solved restrictions but only with Chrome and Vivaldi! I don't know if there is a relation between there.
Rgds
Chris

**Comment by Patira** [comment]
Error 1007 happens when the browser and FreeSWITCH try to negotiate ports to use to stream the media. When the negotiation fails, you get that 1007 error.

Now, according to the documentation, the possible causes of this error, is that either NAT is blocking the connection, or firewall is blocking the UDP connection/ports.

What's the result of `bbb-conf --check`?

**Comment by Magnou17** [comment]
See below results :
BigBlueButton Server 2.2.5 (1848)
                    Kernel version: 4.15.0-96-generic
                      Distribution: Ubuntu 16.04.6 LTS (64-bit)
                            Memory: 4029 MB
                         CPU cores: 2

/usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties (bbb-web)
       bigbluebutton.web.serverURL: https://webconfegeon.best
                defaultGuestPolicy: ALWAYS_ACCEPT
                 svgImagesRequired: true

/etc/nginx/sites-available/bigbluebutton (nginx)
                       server name: webconfegeon.best
                              port: 80, [::]:80
                              port: 443 ssl
                    bbb-client dir: /var/www/bigbluebutton

/var/www/bigbluebutton/client/conf/config.xml (bbb-client)
                Port test (tunnel): rtmp://webconfegeon.best
                              red5: webconfegeon.best
              useWebrtcIfAvailable: true

/opt/freeswitch/etc/freeswitch/vars.xml (FreeSWITCH)
                       local_ip_v4: 192.168.0.10
                   external_rtp_ip: stun:stun.freeswitch.org
                   external_sip_ip: stun:stun.freeswitch.org

/opt/freeswitch/etc/freeswitch/sip_profiles/external.xml (FreeSWITCH)
                        ext-rtp-ip: $${local_ip_v4}
                        ext-sip-ip: $${local_ip_v4}
                        ws-binding: :5066
                       wss-binding: :7443

/usr/local/bigbluebutton/core/scripts/bigbluebutton.yml (record and playback)
                     playback_host: webconfegeon.best
                 playback_protocol: https
                            ffmpeg: 4.2.2-1bbb1~ubuntu16.04

/etc/bigbluebutton/nginx/sip.nginx (sip.nginx)
                        proxy_pass: 82.64.250.65

/usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml (Kurento SFU)
                        kurento.ip: 192.168.0.10
                       kurento.url: ws://127.0.0.1:8888/kurento
                    localIpAddress: 192.168.0.10
               recordScreenSharing: true
                     recordWebcams: true
                  codec_video_main: VP8
               codec_video_content: VP8

/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml (HTML5 client)
                             build: 874
                        kurentoUrl: wss://webconfegeon.best/bbb-webrtc-sfu
                  enableListenOnly: true


# Potential problems described below
# IP does not match:
#                           IP from ifconfig: 192.168.0.10
#   /etc/nginx/sites-available/bigbluebutton: webconfegeon.best

# Warning: The setting of 82.64.250.65 for proxy_pass in
#
#    /etc/bigbluebutton/nginx/sip.nginx
#
# does not match the local IP address (192.168.0.10).
# (This is OK if you've manually changed the values)

# Warning: found only 2 cores, whereas this server should have (at least) 4 CPU cores
# to run BigBlueButton in production.
#
#   https://docs.bigbluebutton.org/install/install.html#minimum-server-requirements
#
Rgds
Chris

**Comment by Patira** [comment]
I guess your server is behind a firewall, that's why it's recommended to use your external IP address instead of your local one.

Follow the steps below:
http://docs.bigbluebutton.org/2.2/configure-firewall.html#configure-bigbluebutton-to-work-with-your-firewall

And BTW, it's best if you follow the minimum server requirements (e.g. at least 4 CPU core), not that it has anything to do with your 1007 error, but rather just a suggestion in order to reduce the number of issues you're getting along the way.

**Comment by relecand** [comment]
You need to install and configure a TURN server to manage the 1007 error: https://github.com/bigbluebutton/bbb-install#install-a-turn-server

**Comment by Magnou17** [comment]
I have done it. Thanks
Rgds
Chris
