### ISSUE TITLE
Cannot change default locale

### ISSUE THREAD

**Issue by nguyendinhdoan** [bigbluebutton/bigbluebutton#9145]
I changed the `localeChain` to my language like this:
```
// File: /var/www/bigbluebutton/client/lib/bbb_localization.js
var localeChain = "vi_VN";
function getLanguage(){
        //return localeChain;
        return "vi_VN";
}
```
<img width="1279" alt="Screen Shot 2020-04-20 at 01 13 21" src="https://user-images.githubusercontent.com/7067817/79696005-427da780-82a4-11ea-9e84-c5550faec298.png">

After changing the code, I ran: `bbb-conf --restart`
I also changed nginx root path pointing to `/var/www/bigbluebutton` and `/var/www/bigbluebutton-default` then restarted nginx but both cases didn't work.

**Comment by Patira** [comment]
Open the following file:
`/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml`

Set `overrideLocale: null` to `overrideLocale: vi_VN` to **hard-set** the default locale for the users.
Also, change the value of `fallbackLocale` to your desired locale, which is in your case "vi_VN".

Make sure you restart BBB after the changes.

**Comment by nguyendinhdoan** [comment]
It works perfectly! Thanks @Patira
