### ISSUE TITLE
What are the differences between bigbluebutton and bigbluebutton-default

### ISSUE THREAD

**Issue by nguyendinhdoan** [bigbluebutton/bigbluebutton#9146]
There are 2 directories and both of them works well when I change the root path in nginx. Can anyone explain to me what the differences are?

**Comment by basisbit** [comment]
`/var/www/bigbluebutton` is the location of the Adobe flash based client (old / replaced by the HTML 5 client / will be removed soon) and `/var/www/bigbluebutton-default` is the location of the splash page what users see when they open `https://yourdomain.tld/`. Usually you'll want to replace the `/var/www/bigbluebutton-default` content by your customized content or a forward to `https://yourdomain.tld/` in the index.html file.
Bear in mind that any change to the files in these paths might be overwritten at the next update, see [this](https://docs.bigbluebutton.org/2.2/customize.html#automatically-apply-configuration-changes-on-restart)

**Comment by ffdixon** [comment]
Thanks @basisbit!

> /var/www/bigbluebutton is the location of the Adobe flash based client (old / replaced by the HTML 5 client / will be removed soon)

Your exactly right -- we'll be removing a good chunk of the legacy Flash code as part of the work on BigBlueButton 2.3 (next release).

**Comment by nguyendinhdoan** [comment]
Thanks for your explanation @basisbit
