### ISSUE TITLE
Documentation mistake

### ISSUE THREAD

**Issue by Magnou17** [bigbluebutton/bigbluebutton#9147]
I made a mistake about about administrator name because i use adminbbb instead admin. Some body answer to me and i correct it. I suggest in the documentation https://docs.bigbluebutton.org/greenlight/gl-admin.html to change :

docker exec greenlight-v2 bundle exec rake user:create["name","email","password","admin"]
to
docker exec greenlight-v2 bundle exec rake user:create["name","email","password",admin]

Rgds
Chris

**Comment by mrkeksi** [comment]
For the documentation there is a thread here: https://github.com/bigbluebutton/bigbluebutton.github.io

It's a bit confusing, but if you read the point about it, you can see that it's the role that should not be changed.
