### ISSUE TITLE
Not able to join the meeting from this afternoon(IST). Morning it went well.

### ISSUE THREAD

**Issue by IAmMukeshKumar** [bigbluebutton/bigbluebutton#9149]
I am not able to join the meeting with BBB. It is showing a blank screen only.

![image](https://user-images.githubusercontent.com/13366065/79738343-3e8c6c80-831a-11ea-9740-c5886ea38e84.png)

Please look into the issue.

**Comment by IAmMukeshKumar** [comment]
Can anyone update the issue please.
Our classes get stopped. PLease

**Comment by matiasilva** [comment]
Support forum here: https://groups.google.com/forum/#!forum/bigbluebutton-setup.
