### ISSUE TITLE
about us and remove help link

### ISSUE THREAD

**Issue by eiscan** [bigbluebutton/bigbluebutton#9150]
Hello,

How can I remove the link about us and the help link from the drop-down menu on the conference page on the right?

https://imgur.com/RO0zweN

Thank you.

**Comment by jfsiebel** [comment]
Good morning @eiscan to remove the help link you can edit `/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml` file and change `showHelpButton` property, for about us option you can't remove it, only if you change the code and build or run html5 client from the source code.

**Comment by eiscan** [comment]
> Good morning @eiscan to remove the help link you can edit `/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml` file and change `showHelpButton` property, for about us option you can't remove it, only if you change the code and build or run html5 client from the source code.

Hi @jfsiebel ,

Thanks for your answer. I removed the help button. But why can't the about button be removed?

**Comment by eiscan** [comment]
Hi @jfsiebel,

Also, can't the link to end the session be removed?

**Comment by dpx2016** [comment]
upadate /usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml and restart bbb
