### ISSUE TITLE
iOS 13.4 with BBB2.2.5: audio stops working from time to time

### ISSUE THREAD

**Issue by jast1982** [bigbluebutton/bigbluebutton#9151]
Hi!

I'm using BBB for remote class room conferences and generally it is working great! Thank you for your great work!

Unfortunately I have an issue with several iOS clients running iOS 13.4.x: From time to time the sound stops suddenly and the clients can't hear anything from BBB including the conference. Even the "mute" and "unmute" sounds stop working. The microphone is still working. The situation can be solved by restarting Safari and rejoining the conference. Stopping audio/Starting audio doesn't solve the issue. It can be provoked by putting Safari in the background and back sometimes and by connecting/disconnecting AirPods.

I'm running the most recent BBB V2.2.5 with Greenlight 2.5.3 and FreeSWITCH Core 2.2.0-97 and Sounds 1.6.7-6 on a Hetzner CX21 with 4 dedicated vCPUs and 16GB RAM. The server is only doing this one job and there was only a single conference with 16 users at ~150%/400% server load. Audio quality is great and clear unless it stops working, so I assume it's not an issue that it's not a bare metal server. However when it happened to me I had the impression that the sounds first garbles before it stops. 

Interestingly enough on an older iPad running iOS 13.0 this does not happen. 

I have client logs enabled, but I just get an "Audio ended" messages which seems to be user triggered when he leaves the room + a normal rejoin.

Any help is greatly appreciated since I am trying to help our school to have some e-learning possibilities during the corona lock down.

Regards,
Jan

**Comment by luckydonald** [comment]
Just throwing around some general ideas:
- Does a normal page refresh make it work again?
- Does switching to the music app and playing something there + pausing again and then switching back to safari make it work again?

**Comment by jast1982** [comment]
Yes, a page refresh with a new login brings audio back.
I have to verify the music hack again, but I think I tried it once and it didn't help.

**Comment by matiasilva** [comment]
It's been a while, perhaps update to the latest version and see if this persists. If so, please follow up in the support group: https://groups.google.com/forum/#!forum/bigbluebutton-setup
