### ISSUE TITLE
Problem with breakout rooms and Mac

### ISSUE THREAD

**Issue by verrain** [bigbluebutton/bigbluebutton#9157]
**Describe the bug**
A student with Mac and IOS joined a breakout room, but after that she had no audio in the main room anymore, after closing the breakout rooms. When I reopened new breakout rooms, she has again an audio connection within the breakout room, but still not in the main room. Logout and Login doesn't help. Only the hard reset / restart of the Mac activate again the audio connection for the student.

Regards
Ricardo Rose

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser: Safari
 - Version: updated version

**Comment by frank-miller9** [comment]
See: https://github.com/bigbluebutton/bigbluebutton/issues/8857
