### ISSUE TITLE
Change color of talking webcam frame

### ISSUE THREAD

**Issue by Sea444** [bigbluebutton/bigbluebutton#9159]
**Is your feature request related to a problem? Please describe.**
In BBB the webcam of the speaker is highlighted with a white frame. But: It's difficult to find the webcam of the person that is speaking, when webcam background is white (white walls)

**Describe the solution you'd like**
Possibility to change color of frame of "talking" webcam via bigbluebutton.properties to another color, for example red, blue or yellow

**Describe alternatives you've considered**
Individual CSS-Hack. 

**Additional context**
It seems that css div class "talking--26lGzY" is the one to adjust. But where can I find CSS settings for this class? I couldn't find the nedded css-file. :-/ Does anybody know?

![grafik](https://user-images.githubusercontent.com/63501663/79768471-207b3800-832b-11ea-963f-abe28e1929db.png)

**Comment by luckydonald** [comment]
The `--26lGzY` part looks like it could be something dynamically generated.
Maybe search for just `.content` and `.talking`.

**Comment by KDSBrowne** [comment]
You can add a `border-color` here https://github.com/bigbluebutton/bigbluebutton/blob/v2.2.x-release/bigbluebutton-html5/imports/ui/components/video-provider/video-list/styles.scss#L75

**Comment by luckydonald** [comment]
Permanent link: https://github.com/bigbluebutton/bigbluebutton/blob/f6f4f8321b0dc0340fe5cbcac161a7de02b0edb6/bigbluebutton-html5/imports/ui/components/video-provider/video-list/styles.scss#L75

**Comment by Sea444** [comment]
Thank you @luckydonald and @KDSBrowne !
But: Where do I find this file on my server?

**Comment by andiwiryawan7** [comment]
you can find in server location :
/usr/share/meteor/bundle/programs/web.browser/head.html

and add css like this

div[class*="talking--"]::after {
   border: 5px solid #094C8F !important;
}
