### ISSUE TITLE
Request: shortcut for setting status

### ISSUE THREAD

**Issue by wolftune** [bigbluebutton/bigbluebutton#9166]
**Is your feature request related to a problem? Please describe.**

Hand-raising is tedious because of the many steps to click in the right place, choose it from a menu etc.

**Describe the solution you'd like**

I'd prefer a shortcut / hotkey for hand-raising and/or to open the status menu for myself.

**Comment by Sea444** [comment]
linked to #9072

**Comment by wolftune** [comment]
I see a tag and link was added to this, but no other attention. It's still important. Please keep it open.

**Comment by ffdixon** [comment]
Added this in 2.4.

![image](https://user-images.githubusercontent.com/290351/147824730-4ec0edf9-4c63-4000-bf3e-99756746c355.png)

**Comment by wolftune** [comment]
Great, but no shortcut for opening the other status options?
