### ISSUE TITLE
Missing settings option for locksettings"moderatoronlyviewscams"

### ISSUE THREAD

**Issue by enaut** [bigbluebutton/bigbluebutton#9167]
I want to change the default setting of the `see other viewers webcams` (second option) in the config file.
However every option except that one seems to be in the `/usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties` file.

![](http://docs.bigbluebutton.org/images/html5-lock-webcam.png)

**Comment by cnet24** [comment]
Same file;
Allow webcams streaming reception only to and from moderators
webcamsOnlyForModerator=true

**Comment by enaut** [comment]
Oh I see... Thank you!
