### ISSUE TITLE
mongod "failed" status.

### ISSUE THREAD

**Issue by arsalan342** [bigbluebutton/bigbluebutton#9169]
I've installed bbb using bbb-install.sh without any error:
wget -qO- https://ubuntu.bigbluebutton.org/bbb-install.sh | bash -s -- -v xenial-220 -a
.
.
.
.

 When I try to join a room I get this error:
404 Not Found
nginx/1.10.3 (Ubuntu)
.
.
.
I think the error is because of mongod service as I get this output:

$ sudo bbb-conf --status

nginx —————————————————► [✔ - active]
freeswitch ————————————► [✔ - active]
redis-server ——————————► [✔ - active]
bbb-apps-akka —————————► [✔ - active]
bbb-transcode-akka ————► [✔ - active]
bbb-fsesl-akka ————————► [✔ - active]
red5 ——————————————————► [✔ - active]
tomcat7 ———————————————► [✔ - active]
mongod ————————————————► [✘ - failed]
bbb-html5 —————————————► [✔ - active]
bbb-webrtc-sfu ————————► [✔ - active]
kurento-media-server ——► [✔ - active]
etherpad ——————————————► [✔ - active]
bbb-web ———————————————► [✔ - active]
.
.
.
Also I get this output:

$ sudo systemctl status mongod
● mongod.service - High-performance, schema-free document-oriented database
   Loaded: loaded (/etc/systemd/system/mongod.service; disabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Tue 2020-04-21 00:07:49 +0430; 37min ago
     Docs: https://docs.mongodb.org/manual
  Process: 1152 ExecStartPre=/usr/share/meteor/bundle/mongod_start_pre.sh (code=exited, status=217/USER
Apr 21 00:07:49 b1 systemd[1]: Starting High-performance, schema-free document-oriented database...
Apr 21 00:07:49 b1 systemd[1]: mongod.service: Control process exited, code=exited status=217
Apr 21 00:07:49 b1 systemd[1]: Failed to start High-performance, schema-free document-oriented database
Apr 21 00:07:49 b1 systemd[1]: mongod.service: Unit entered failed state.
Apr 21 00:07:49 b1 systemd[1]: mongod.service: Failed with result 'exit-code'.
.
.
.
.
I reinstalled mongod using the following command:

$ wget -qO - https://www.mongodb.org/static/pgp/server-3.4.asc | sudo apt-key add -
$ echo "deb [ arch=amd64,arm64 ] http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.4 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.4.list
$ sudo apt-get update
$ sudo apt-get install -y mongodb-org curl
.
.
.
But still the problem exist and mongod status is "failed".
How can I resolve this issue?

**Comment by Etrendapps** [comment]
I have the same issue. Can anyone help with the possible steps to resolve this?

Thanks for your help.

**Comment by arsalan342** [comment]
I reinstalled ubuntu and bbb using a US VPN connection. And the problem resolved.

**Comment by MakeTooRRSS** [comment]
Hello, is there any solution to the problem? The admin panel works correctly but when I try to start a room I get error 502 Bad Gateway nginx. And in the admin panel appears as online room if anyone knows how to solve this problem. Running the following command I get that mongod is failed.

sudo bbb-conf --status
nginx ————————————————————————► [✔ - active]
freeswitch ———————————————————► [✔ - active]
redis-server —————————————————► [✔ - active]
bbb-apps-akka ————————————————► [✔ - active]
bbb-fsesl-akka ———————————————► [✔ - active]
mongod ———————————————————————► [✘ - failed]
bbb-html5 ————————————————————► [✔ - active]
bbb-html5-backend@1 ——————————► [✔ - active]
bbb-html5-backend@2 ——————————► [✔ - active]
bbb-html5-frontend@1 —————————► [✔ - active]
bbb-html5-frontend@2 —————————► [✔ - active]
bbb-webrtc-sfu ———————————————► [✔ - active]
bbb-webrtc-recorder ——————————► [✔ - active]
kurento-media-server —————————► [✔ - active]
etherpad —————————————————————► [✔ - active]
bbb-web ——————————————————————► [✔ - active]
bbb-pads —————————————————————► [✔ - active]
bbb-export-annotations ———————► [✔ - active]
bbb-rap-caption-inbox ————————► [✔ - active]
bbb-rap-resque-worker ————————► [✔ - active]
bbb-rap-starter ——————————————► [✔ - active]
