### ISSUE TITLE
Errors after editing bigbluebutton.properties

### ISSUE THREAD

**Issue by vadimluminous** [bigbluebutton/bigbluebutton#9170]
Hi all,

I keep getting error after I simply edit bigbluebutton.properties.

I don't do much in the file except edit the welcome message to 
`defaultWelcomeMessage=Welcome to <b>%%CONFNAME%%</b>!`

So I don't even add anything, I just take away the filler. And then I edit the 'defaultWelcomeMessageFooter' and replace it with my own URL.

After those simple edits, when I restart BBB I get these errors

```

the setting for svgImagesRequired is false. To fix, run the commnad

 sed -i 's/^svgImagesRequired=.*/svgImagesRequired=true/' /usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties

Restarting BigBlueButton 2.2.5 (and cleaning out all log files) ...
Stopping BigBlueButton
 ... cleaning log files
Starting BigBlueButton
...............


# Potential problems described below
# ImageMagick's convert is not installed in /usr/bin
# IP does not match:
#                           IP from ifconfig: 172.31.22.77
#   /etc/nginx/sites-available/bigbluebutton: start.instantonlinemeetings.com

# Warning: You have the HTML5 client installed but in
#
#    /usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties
#
# the setting for svgImagesRequired is false. To fix, run the commnad
#
# sed -i 's/^svgImagesRequired=.*/svgImagesRequired=true/' /usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties
#
#       Log file too short (less than 100 lines): /usr/share/red5/log/bigbluebutton.log (red5)
................................................................................
# Error: Could not connect to the configured hostname/IP address
#
/    https://start.instantonlinemeetings.com
#
# If your BigBlueButton server is behind a firewall, see FAQ.

# Warning: The setting of 18.144.159.66 for proxy_pass in
#
#    /etc/bigbluebutton/nginx/sip.nginx
#
# does not match the local IP address (172.31.22.77).
# (This is OK if you've manually changed the values)

# Error: Unable to reach default URL for presentation:
#
/default.pdf/start.instantonlinemeetings.com
#
# Check value for beans.presentationService.defaultUploadedPresentation in
#   /usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties
```

The thing is, even after these error. My BBB works perfectly fine. Checking my SVG images, it's true, my default.pdf exists and works fine, and the beans.presentation value is fine.

So why would it complain about these problems? And notice my URL 
`/default.pdf/start.instantonlinemeetings.com`

Why is it formatted like that?

I am running 2.2.5 which I believe is the most recent version.

**Comment by Patira** [comment]
Can you send the value that you've used for the `defaultWelcomeMessage` property?

**Comment by vadimluminous** [comment]
Yes

ORIGINAL:
```
defaultWelcomeMessage=Welcome to <b>%%CONFNAME%%</b>!<br><br>For help on using BigBlueButton see these (short) <a href="event:http://www.bigbluebutton.org/html5"><u>tutorial videos</u></a>.<br><br>To join the audio bridge click the phone button.  Use a headset to avoid causing background noise for others.
defaultWelcomeMessageFooter=This server is running <a href="http://docs.bigbluebutton.org/" target="_blank"><u>BigBlueButton</u></a>.
```

EDITED:
```
defaultWelcomeMessage=Welcome to <b>%%CONFNAME%%</b>!
defaultWelcomeMessageFooter=<a href="http://myurl.com/" target="_blank"><u>MyUrl.com</u></a>.
```

As you can see for the Welcomemessage I actually didn't change anything, just removed the majority of the text

**Comment by Patira** [comment]
It's a little bit odd because everything in that area seems to be right, but just in case, select all the code from the `bigbluebutton.properties` file, copy that into the native box of the following URL:
https://native2ascii.net/
Select all the code from the ASCII box of that URL and put it back into the `bigbluebutton.properties` file.
I had a similar issue just like you, and that did the trick. Hopefully, it works for you as well.

**Comment by vadimluminous** [comment]
Thank you for responding Patira,

I did what you asked and still got the same error. It's weird, one of my errors is 

```
# Warning: You have the HTML5 client installed but in
#
#    /usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties
#
# the setting for svgImagesRequired is false. To fix, run the commnad
```
But after checking that setting in that file, it's set to true... Very odd.

**Comment by Patira** [comment]
I imagine you've changed something unintentionally, and that's why you're getting that error.
Compare your file with this file:
https://github.com/bigbluebutton/bigbluebutton/blob/develop/bigbluebutton-web/grails-app/conf/bigbluebutton.properties
The only differences must be in these properties:
- `bigbluebutton.web.serverURL` on line 222
- `securitySalt` on line 262
- `screenshareRtmpServer` on line 322

**Comment by vadimluminous** [comment]
I actually did not change anything other than the Welcome Message and Footer message

**Comment by kingofnull** [comment]
I have same problem it seems the editor mess up encoding of file.
