### ISSUE TITLE
Config has changed automatically, no recordings available

### ISSUE THREAD

**Issue by ShiftyMLG** [bigbluebutton/bigbluebutton#9176]
**Describe the bug**
I logged into my dashboard today, users can't see their recordings anymore, the favicon has changed by itself and the default presentation was reset to the bigbluebutton default presentation aswell. All these files have been modified on the exact same time (00:06:16). The recordings are still on the server, but not accessible by the users on the greenlight application.
**To Reproduce**
I have no idea

**Expected behavior**
The opposite of what happened here.

**Screenshots**
![image](https://user-images.githubusercontent.com/36298934/79857067-83bda680-83cd-11ea-87f1-c9dfe9099c66.png)

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser Chrome and safari

**Comment by ichdasich** [comment]
See  Ticket #9111 ; Probably there was an automatic update installed.

**Comment by ShiftyMLG** [comment]
@ichdasich thanks for the response. This explains why this happened. But I don't know how I would have to restore the recordings... I'll create the script for the config, but how do I make the recordings available then?

**Comment by alexanderjackson** [comment]
@ShiftyMLG We are also facing this issue after BBB updates with `apt upgrade`. Not sure if it's related to the usage of a customized Greenlight frontend. Nevertheless, we are able to solve the issue by running `bbb-conf --restart`, `bbb-conf --clean` or `systemctl restart bbb-web.service`. It's odd that it only looses/hides the recordings occasionally..
