### ISSUE TITLE
Moderator approval -> Unable to give approved users Moderator  

### ISSUE THREAD

**Issue by Subdarub** [bigbluebutton/bigbluebutton#9181]
**Describe the bug**
If a room in Greenlight has the option "Require moderator approval before joining". You are unable give approved users moderator permissions in your BigBlueButton session. You are able to see "Promote to Moderator" but it doesnt do anything. 

On a second note, the session does not distinguish between authenticated users and guest users. Even if the user was authenticated via LDAP in Greenlight when he joined the session. Every user is just a "Guest". I tried to reproduce the issue at demo.bigbluebutton.org and got the same results.  

**To Reproduce**
1. Go to the Greenlight frontend tick "Require moderator approval before joining" in the room you are testing it in 
2. Start the session
3. Get somebody else to join the session
4. Approve the person
5. Try promote the person to moderator

**Expected behavior**
Person becomes a moderator

**Actual behavior**
Person does not become moderator, even tho the option gets displayed and is clickable. 

**BBB version (optional):**
2.2.4 
Also happens on your demo server tho. 

**Desktop (please complete the following information):**
 - OS: Windows 10 1903
 - Browser: Chrome 80. Firefox 
 - Version 80, 75

**Additional context**

**Comment by pedrobmarin** [comment]
#7460

**Comment by mabras** [comment]
Same in BBB `2.2.6`

**Comment by pedrobmarin** [comment]
Closing in favor of https://github.com/bigbluebutton/bigbluebutton/issues/7460
