### ISSUE TITLE
Choose microphone likewise webcam

### ISSUE THREAD

**Issue by debuglevel** [bigbluebutton/bigbluebutton#9184]
**Describe the bug**
When you *activate* the webcam, you can *choose* which webcam you want to use.

When you *activate* the microphone, you *cannot choose* your microphone. You go straight to the Echo-Test and have to press "no" to choose another microphone. But you have to *know* that a "no" offers you a list of microphones and sound cards. There is no hint what "no" will actually do. Most users will hear themselves in the echo test, even if through their built-in laptop microphone, and therefore press "yes".

**Expected behavior**
Like in the webcam dialog, I would expect similar behavior for sound devices.

**Actual behavior**
Choosing audio input and output is kind of a hidden feature.

**Screenshots**
![image](https://user-images.githubusercontent.com/2401265/79901250-d91aa780-840f-11ea-8b27-733ba1471128.png)
![image](https://user-images.githubusercontent.com/2401265/79901291-ea63b400-840f-11ea-8aee-8caf9af9967a.png)

**Desktop (please complete the following information):**
Chrome and Firefox on Windows 10.

**Smartphone (please complete the following information):**
Did not test.

**Comment by runout-at** [comment]
this depends on your browser. firefox asks for choosing the input device and lists 4 devices for my hardware/software (linux, debian)

**Comment by matiasilva** [comment]
This is browser-specific. I can select my microphone before the echo test. 
<img width="266" alt="Untitled" src="https://user-images.githubusercontent.com/23108156/85021025-234aab80-b169-11ea-81f5-62ae479843e1.png">
Closing...

**Comment by debuglevel** [comment]
Well, then the suggestion would be to implement this browser specific. But it's akward user experience design to say "Hello dear Chrome user, you have to select 'no' in Echo test to be able to chose a microphone"

**Comment by matiasilva** [comment]
Hi @debuglevel. As shown above, I can choose my microphone before proceeding to the echo test when the browser asks permission to use my microphone. Does the same not show up for you?

**Comment by debuglevel** [comment]
Nope, not for Chrome maybe. But #9698 is the more recent and detailed issue about the same thing.

**Comment by matiasilva** [comment]
I see. I left the other issue open on purpose so we could continue discussing this UX change.
