### ISSUE TITLE
Whitebord writing trim issue

### ISSUE THREAD

**Issue by testprepturkey** [bigbluebutton/bigbluebutton#9185]
**Describe the bug**
When I try to write a sentence with the pen tool, the whiteboard trims the letters, curves, shapes, etc. This causes the lag and some letters are not written.

**To Reproduce**

**Expected behavior**
Being able to write fast without the trim.

**Actual behavior**
Unable to write fast (normal writing speed).

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [Windows, Mac]
 - Browser [Chrome, Safari, Edge]
 - Version [Latest]

**Comment by basisbit** [comment]
could you maybe provide a video recording of the problem?

**Comment by testprepturkey** [comment]
Hi basisbit,
Thank you for the reply.
https://easyupload.io/4vohik
Here is the video including the comparison with paint.

**Comment by tarunb999** [comment]
I actually asked this exact point a few years ago and asked if the whiteboard can be like non-sync types as used in other sites. At that time I got a reply that they don't intend to change it to non-sync types which can make drawing much faster.
This BBB type whiteboard, which syncs all whiteboards actually becomes very frustrating for teachers to write freehand as for a fraction of a second you just can't see what you've written, hence hampering the drawing speed.

**Comment by ffdixon** [comment]
We've been working on whiteboard performance improvements for BigBlueButton 2.3 (currently in development).  You can see some of the work here #9019.
