### ISSUE TITLE
ICE 1007 error after installing Turn Server

### ISSUE THREAD

**Issue by TheJan2020** [bigbluebutton/bigbluebutton#9186]
Hello, I have a BBB 2.2.4 installation with Turn Server

Lots of users have ICE 1007 error, i have the Turn Server installation and below are the --check results.

Could you please guide me as i have created a new VM and same issues.

BigBlueButton Server 2.2.4 (1846)
                    Kernel version: 4.4.0-177-generic
                      Distribution: Ubuntu 16.04.6 LTS (64-bit)
                            Memory: 32946 MB
                         CPU cores: 8

/usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties (bbb-web)
       bigbluebutton.web.serverURL: https://vrc11.eduzee.com
                defaultGuestPolicy: ALWAYS_ACCEPT
                 svgImagesRequired: true

/etc/nginx/sites-available/bigbluebutton (nginx)
                       server name: vrc11.eduzee.com
                              port: 80, [::]:80
                              port: 443 ssl
                    bbb-client dir: /var/www/bigbluebutton

/var/www/bigbluebutton/client/conf/config.xml (bbb-client)
                Port test (tunnel): rtmp://vrc11.eduzee.com
                              red5: vrc11.eduzee.com
              useWebrtcIfAvailable: true

/opt/freeswitch/etc/freeswitch/vars.xml (FreeSWITCH)
                       local_ip_v4: 167.172.23.50
                   external_rtp_ip: 167.172.23.50
                   external_sip_ip: 167.172.23.50

/opt/freeswitch/etc/freeswitch/sip_profiles/external.xml (FreeSWITCH)
                        ext-rtp-ip: $${external_rtp_ip}
                        ext-sip-ip: $${external_sip_ip}
                        ws-binding: :5066
                       wss-binding: 167.172.23.50:7443

/usr/local/bigbluebutton/core/scripts/bigbluebutton.yml (record and playback)
                     playback_host: vrc11.eduzee.com
                 playback_protocol: https
                            ffmpeg: 4.2.2-1bbb1~ubuntu16.04

/etc/bigbluebutton/nginx/sip.nginx (sip.nginx)
                        proxy_pass: 167.172.23.50

/usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml (Kurento SFU)
                        kurento.ip: 167.172.23.50
                       kurento.url: ws://167.172.23.50:8888/kurento
                    localIpAddress: 167.172.23.50
               recordScreenSharing: true
                     recordWebcams: true
                  codec_video_main: VP8
               codec_video_content: VP8

/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml (HTML5 client)
                             build: 873
                        kurentoUrl: wss://vrc11.eduzee.com/bbb-webrtc-sfu
                  enableListenOnly: true

# Potential problems described below
# Warning: The voice application may not have registered with the sip server.
#   Try running:
#
#      bbb-conf --clean
#

**Comment by TheJan2020** [comment]
Results from FireFox about:webRTC


failed | false | false | 192.168.0.164:55201/udp(host) [non-proxied] | 167.172.23.50:23476/udp(host) | 1 | 2830971808121343 | 0 | 0
-- | -- | -- | -- | -- | -- | -- | -- | --
inprogress | false | false | 192.168.0.164:55201/udp(host) [non-proxied] | 167.172.23.50:23476/udp(host) | 1 | 2830971808121343 | 0 | 0

**Comment by GunFood** [comment]
So you installed the turn server on the same host as BBB? This should be an extra machine, as freeswitch and coturn use similar udp ports.

**Comment by matiasilva** [comment]
Can be resolved by changing the TLS port to 5349 and hosting another TURN on 443. See #8875
