### ISSUE TITLE
redis connection error

### ISSUE THREAD

**Issue by alfianazizi** [bigbluebutton/bigbluebutton#9187]
The external video is not showing, but the option to Start and Stop share is working. This is the screenshot of the problem:
![image](https://user-images.githubusercontent.com/25798004/79929892-5591a280-8471-11ea-8f9a-0abd6b40d458.png)

This is the last output of **bbb-conf --debug**:

/var/log/bigbluebutton/bbb-web.2020-04-21.log:org.bigbluebutton.presentation.imp.CountingPageException: Exception while trying to determine number of pages.
/var/log/bigbluebutton/bbb-web.2020-04-21.log:2020-04-21T19:31:11.674+07:00 ERROR o.b.p.h.PdfPageCounterHandler - Exception counting images
/var/log/bigbluebutton/bbb-web.2020-04-21.log:java.lang.IllegalStateException: No match found
/var/log/bigbluebutton/bbb-web.2020-04-21.log:org.bigbluebutton.presentation.imp.CountingPageException: Exception while trying to determine number of pages.
/var/log/bigbluebutton/bbb-web.2020-04-21.log:2020-04-21T19:40:49.883+07:00 ERROR o.b.p.h.PdfPageCounterHandler - Exception counting images
/var/log/bigbluebutton/bbb-web.2020-04-21.log:java.lang.IllegalStateException: No match found
/var/log/bigbluebutton/bbb-web.2020-04-21.log:org.bigbluebutton.presentation.imp.CountingPageException: Exception while trying to determine number of pages.
/var/log/bigbluebutton/bbb-web.log:2020-04-22T03:24:12.167+07:00 ERROR o.b.p.h.PdfPageCounterHandler - Exception counting images
/var/log/bigbluebutton/bbb-web.log:java.lang.IllegalStateException: No match found
/var/log/bigbluebutton/bbb-web.log:org.bigbluebutton.presentation.imp.CountingPageException: Exception while trying to determine number of pages.
/var/log/bigbluebutton/bbb-web.log:2020-04-22T06:51:40.499+07:00 ERROR o.b.p.h.PdfPageCounterHandler - Exception counting images
/var/log/bigbluebutton/bbb-web.log:java.lang.IllegalStateException: No match found
/var/log/bigbluebutton/bbb-web.log:org.bigbluebutton.presentation.imp.CountingPageException: Exception while trying to determine number of pages.
/var/log/bigbluebutton/bbb-web.log:2020-04-22T06:57:15.565+07:00 WARN  i.l.c.protocol.ConnectionWatchdog - Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: /127.0.0.1:6379
/var/log/bigbluebutton/bbb-web.log:2020-04-22T06:57:15.567+07:00 WARN  i.l.c.protocol.ConnectionWatchdog - Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: /127.0.0.1:6379
/var/log/bigbluebutton/bbb-web.log:2020-04-22T06:57:15.642+07:00 WARN  i.l.c.protocol.ConnectionWatchdog - Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: /127.0.0.1:6379
/var/log/bigbluebutton/bbb-web.log:2020-04-22T06:57:15.649+07:00 WARN  i.l.c.protocol.ConnectionWatchdog - Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: /127.0.0.1:6379
/var/log/bigbluebutton/bbb-web.log:2020-04-22T06:57:15.642+07:00 WARN  i.l.c.protocol.ConnectionWatchdog - Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: /127.0.0.1:6379
/var/log/bigbluebutton/bbb-web.log:2020-04-22T07:02:34.420+07:00 ERROR o.b.p.h.PdfPageCounterHandler - Exception counting images
/var/log/bigbluebutton/bbb-web.log:java.lang.IllegalStateException: No match found
/var/log/bigbluebutton/bbb-web.log:org.bigbluebutton.presentation.imp.CountingPageException: Exception while trying to determine number of pages.
/var/log/bigbluebutton/bbb-web.log:2020-04-22T07:22:31.692+07:00 ERROR o.b.p.h.PdfPageCounterHandler - Exception counting images
/var/log/bigbluebutton/bbb-web.log:java.lang.IllegalStateException: No match found
/var/log/bigbluebutton/bbb-web.log:org.bigbluebutton.presentation.imp.CountingPageException: Exception while trying to determine number of pages.
/var/log/bigbluebutton/bbb-web.log:2020-04-22T07:29:42.399+07:00 ERROR o.b.p.h.PdfPageCounterHandler - Exception counting images
/var/log/bigbluebutton/bbb-web.log:java.lang.IllegalStateException: No match found
/var/log/bigbluebutton/bbb-web.log:org.bigbluebutton.presentation.imp.CountingPageException: Exception while trying to determine number of pages.
/var/log/bigbluebutton/bbb-web.log:2020-04-22T07:38:07.468+07:00 WARN  i.l.c.protocol.ConnectionWatchdog - Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: /127.0.0.1:6379
/var/log/bigbluebutton/bbb-web.log:2020-04-22T07:38:07.479+07:00 WARN  i.l.c.protocol.ConnectionWatchdog - Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: /127.0.0.1:6379
/var/log/bigbluebutton/bbb-web.log:2020-04-22T07:38:07.488+07:00 WARN  i.l.c.protocol.ConnectionWatchdog - Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: /127.0.0.1:6379
/var/log/bigbluebutton/bbb-web.log:2020-04-22T07:38:07.487+07:00 WARN  i.l.c.protocol.ConnectionWatchdog - Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: /127.0.0.1:6379
/var/log/bigbluebutton/bbb-web.log:2020-04-22T07:38:07.491+07:00 WARN  i.l.c.protocol.ConnectionWatchdog - Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: /127.0.0.1:6379
/var/log/bigbluebutton/bbb-web.log:2020-04-22T07:43:02.253+07:00 WARN  i.l.c.protocol.ConnectionWatchdog - Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: /127.0.0.1:6379
/var/log/bigbluebutton/bbb-web.log:2020-04-22T07:43:02.253+07:00 WARN  i.l.c.protocol.ConnectionWatchdog - Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: /127.0.0.1:6379
/var/log/bigbluebutton/bbb-web.log:2020-04-22T07:43:02.301+07:00 WARN  i.l.c.protocol.ConnectionWatchdog - Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: /127.0.0.1:6379
/var/log/bigbluebutton/bbb-web.log:2020-04-22T07:53:42.791+07:00 WARN  i.l.c.protocol.ConnectionWatchdog - Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: /127.0.0.1:6379
/var/log/bigbluebutton/bbb-web.log:2020-04-22T07:53:42.794+07:00 WARN  i.l.c.protocol.ConnectionWatchdog - Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: /127.0.0.1:6379
/var/log/bigbluebutton/bbb-web.log:2020-04-22T07:53:42.796+07:00 WARN  i.l.c.protocol.ConnectionWatchdog - Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: /127.0.0.1:6379
/var/log/bigbluebutton/bbb-web.log:2020-04-22T07:53:42.798+07:00 WARN  i.l.c.protocol.ConnectionWatchdog - Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: /127.0.0.1:6379
/var/log/bigbluebutton/bbb-web.log:2020-04-22T07:53:42.822+07:00 WARN  i.l.c.protocol.ConnectionWatchdog - Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: /127.0.0.1:6379
/var/log/bigbluebutton/bbb-web.log:2020-04-22T07:58:20.363+07:00 ERROR o.b.p.h.PdfPageCounterHandler - Exception counting images
/var/log/bigbluebutton/bbb-web.log:java.lang.IllegalStateException: No match found
/var/log/bigbluebutton/bbb-web.log:org.bigbluebutton.presentation.imp.CountingPageException: Exception while trying to determine number of pages.
/var/log/bigbluebutton/bbb-web.log:2020-04-22T07:59:31.196+07:00 ERROR o.b.p.h.PdfPageCounterHandler - Exception counting images
/var/log/bigbluebutton/bbb-web.log:java.lang.IllegalStateException: No match found
/var/log/bigbluebutton/bbb-web.log:org.bigbluebutton.presentation.imp.CountingPageException: Exception while trying to determine number of pages.

it says **i.l.c.protocol.ConnectionWatchdog - Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: /127.0.0.1:6379**

i thought there's a problem with redis connection, but bbb-conf --status showing no problem:

$ bbb-conf --status
nginx —————————————————► [✔ - active]
freeswitch ————————————► [✔ - active]
redis-server ——————————► [✔ - active]
bbb-apps-akka —————————► [✔ - active]
bbb-transcode-akka ————► [✔ - active]
bbb-fsesl-akka ————————► [✔ - active]
red5 ——————————————————► [✔ - active]
mongod ————————————————► [✔ - active]
bbb-html5 —————————————► [✔ - active]
bbb-webrtc-sfu ————————► [✔ - active]
kurento-media-server ——► [✔ - active]
etherpad ——————————————► [✔ - active]
bbb-web ———————————————► [✔ - active]

i ran **netstat -ntlp | grep 6379 | grep LISTEN**

tcp        0      0 127.0.0.1:6379          0.0.0.0:*               LISTEN      -

it shows no problem with my open port.

The other features seems to work properly.

Anyone have the same issue regarding sharing external video and/or redis connection with bbb-web and have resolved it? 

I hope it explain my question since i am new to github and just recently using this software. 
anyway, the software is great!

**Comment by alfianazizi** [comment]
well, it turns out my configuration regarding CSP Header is blocking the external video to show. I have managed to solve the external video share issue.

is there any suggestion on the redis connection issue on bbb log?

**Comment by intereal** [comment]
Same error, installed from stock

**Comment by matiasilva** [comment]
Hi, thanks for posting this support issue. Could you please follow the instructions for getting help? https://docs.bigbluebutton.org/2.2/getting-help.html. Thanks.
