### ISSUE TITLE
Polling Buttons too big for Mobile users, how to reduce their size?

### ISSUE THREAD

**Issue by tarunb999** [bigbluebutton/bigbluebutton#9191]
Hi,
Many of our students use BBB on mobiles and when they are presented by a Poll, the buttons take up all the space and they are not able to see the questions.
Can I edit the buttons so that they are smaller in size pls ? and are shown in a horizontal line instead of vertical alignment?

Thanks.

**Comment by tarunb999** [comment]
Can anyone point me to images directory where these button images are placed ?? Perhaps I can upload smaller images.

**Comment by matiasilva** [comment]
They're part of the icon library. See the stylesheets in `bigbluebutton-html5`. Alternatively, you can specify custom css in a customized version of the HTML5 client. Closing for now. If you need further support, head on over to https://groups.google.com/forum/#!forum/bigbluebutton-setup.
