### ISSUE TITLE
HTML5 client sends invalid srflx records to FreeSWITCH, resulting in ICE error 1007

### ISSUE THREAD

**Issue by pnijjar** [bigbluebutton/bigbluebutton#9192]
**Describe the bug**
If a client is using symmetric NAT and the BBB server is behind a NATted firewall, the client will get ICE error 1007 and not be able to connect to audio even with a TURN server configured, if the HTML5 client sends any srflx records at all. This appears to be because neither BBB nor FreeSWITCH does proper connectivity checks to make sure STUN actually works.

This bug is transcribing what I documented here: <https://groups.google.com/forum/#!topic/bigbluebutton-setup/0vtARlm3lCQ> . 

**To Reproduce**

- Install a BBB server behind a NAT. I had 2.2.2 and 2.2.5 . I used install.sh with Let's Encrypt and Greenlight.

- Follow the instructions from <http://docs.bigbluebutton.org/2.2/configure-firewall.html#configure-bigbluebutton-to-work-with-your-firewall> , including setting up a loopback alias for hairpin NAT.

- Follow the instructions to set up and configure a Coturn TURN server from <http://docs.bigbluebutton.org/2.2/setup-turn-server.html> . Add a turns: entry for your coturn server in `/usr/share/bbb-web/WEB-INF/classes/spring/turn-stun-servers.xml`. (Note that I did not use port 443 and I did not enable the non-ssl turn: // entry, but I think neither of these changes the outcome)

- In `/opt/freeswitch/conf/sip_profiles/external.xml` comment out the following lines: 
```
    <!-- Added for Microsoft Edge browser -->
    <param name="apply-candidate-acl" value="localnet.auto"/>
    <param name="apply-candidate-acl" value="wan_v4.auto"/>
    <param name="apply-candidate-acl" value="rfc1918.auto"/>
    <param name="apply-candidate-acl" value="any_v4.auto"/>
```
(I found that I needed this for TURN to work, but maybe I am wrong.)

- To simulate symmetric NAT, take a client machine and block outgoing UDP to the BBB server: `ufw deny out to S.S.S.S proto udp port 1024:65535`

- Attempt to connect to a meeting. Observe audio fails. I tested with Firefox 68.7.0 on Linux, and Chromium 80.0.3897.163 on Linux. Both are 64-bit.

- Comment out the STUN entry in `/usr/share/bbb-web/WEB-INF/classes/spring/turn-stun-servers.xml` and restart BBB. Now retry the client machine (still with UDP blocked). Note that audio now works (but that it will use TURN for EVERY client, whether that is necessary or not.) 

**Expected behavior**

Because UDP is blocked from the client to the server, no srflx entries should be used. Either the client or FreeSWITCH (I am not 100% sure which) should be smart enough to do a connectivity test and only use ICE candidates that work, which in this case means using TURN. 

**Actual behavior**

The HTML5 client connects ICE candidates and sends them along (I think blindly, based upon the comments in the `analyzeSdp` function of the HTML5 client). This includes the STUN candidates that do not work. FreeSWITCH then collects that list of candidates and chooses the "best" ones, which are the STUN ones. I think it just does subnet filters, and does not consider connectivity checks either. 

**Screenshots**

In what follows I use the following redactions:

S.S.S.S : The BBB server's public IP.
L.L.L.L : The BBB server's local IP behind the NAT
C.C.C.C : The Coturn's server IP (it is NOT behind a NAT)
M.M.M.M : My client public IP
bbb.example.com : the hostname of my server
192.168.155.130 : My client IP behind the firewall
172.26.135.254 : A VPN IP. Note that this is also in the private range. 

In `about:webrtc`, Firefox shows that the client sends the following SDP:
```
SDP
Local SDP (Offer)
v=0
o=mozilla...THIS_IS_SDPARTA-75.0 4260760932109251014 0 IN IP4 0.0.0.0
s=-
t=0 0
a=sendrecv
a=fingerprint:sha-256 17:56:DD:C8:35:C9:5E:D5:AB:23:CE:D4:46:DE:94:E1:C3:E4:24:04:BA:56:8D:2B:6B:60:02:5B:79:1F:35:EF
a=group:BUNDLE 0
a=ice-options:trickle
a=msid-semantic:WMS *
m=audio 21796 UDP/TLS/RTP/SAVPF 109 9 0 8 101
c=IN IP4 C.C.C.C
a=candidate:0 1 UDP 2122252543 192.168.155.130 40202 typ host
a=candidate:2 1 UDP 2122187007 172.26.135.254 37828 typ host
a=candidate:4 1 TCP 2105524479 192.168.155.130 9 typ host tcptype active
a=candidate:6 1 TCP 2105458943 172.26.135.254 9 typ host tcptype active
a=candidate:0 2 UDP 2122252542 192.168.155.130 39985 typ host
a=candidate:2 2 UDP 2122187006 172.26.135.254 42766 typ host
a=candidate:4 2 TCP 2105524478 192.168.155.130 9 typ host tcptype active
a=candidate:6 2 TCP 2105458942 172.26.135.254 9 typ host tcptype active
a=candidate:1 1 UDP 1686052863 M.M.M.M 40202 typ srflx raddr 192.168.155.130 rport 40202
a=candidate:1 2 UDP 1686052862 M.M.M.M 39985 typ srflx raddr 192.168.155.130 rport 39985
a=candidate:5 2 UDP 8331262 C.C.C.C 29452 typ relay raddr C.C.C.C rport 29452
a=candidate:5 1 UDP 8331263 C.C.C.C 21796 typ relay raddr C.C.C.C rport 21796
a=sendrecv
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=extmap:2/recvonly urn:ietf:params:rtp-hdrext:csrc-audio-level
a=extmap:3 urn:ietf:params:rtp-hdrext:sdes:mid
a=fmtp:109 maxplaybackrate=48000;stereo=1;useinbandfec=1
a=fmtp:101 0-15
a=ice-pwd:7ecb8e07a51a7ae141dc38b87b1fe3cb
a=ice-ufrag:9444e3fb
a=mid:0
a=msid:{499fcfd3-ba56-4b69-95ab-2ec8303f1e0c} {b34c6657-26b2-45ce-88c0-71e15ee1eeff}
a=rtcp:29452 IN IP4 C.C.C.C
a=rtcp-mux
a=rtpmap:109 opus/48000/2
a=rtpmap:9 G722/8000/1
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:101 telephone-event/8000
a=setup:actpass
a=ssrc:3791258780 cname:{df56015b-2953-4f3e-91c4-b745c6a5c257}
```

and FreeSWITCH returns with the following:

```
Remote SDP (Answer)
v=0
o=FreeSWITCH 1586795476 1586795477 IN IP4 S.S.S.S
s=-
t=0 0
a=sendrecv
a=msid-semantic:WMS UqgPNluIbyxH1Azza7cYCyCPjrIxttfd
m=audio 22816 RTP/SAVPF 109 101
c=IN IP4 S.S.S.S
a=candidate:6174971931 1 udp 659136 S.S.S.S 22816 typ host generation 0
a=sendrecv
a=end-of-candidates
a=fingerprint:sha-256 B5:EE:01:13:83:2B:B6:14:74:75:2B:84:65:08:81:61:C6:47:AE:CF:F1:1C:3C:4B:02:3A:5E:B7:ED:1F:60:DA
a=fmtp:109 maxplaybackrate=0;stereo=1;useinbandfec=1
a=ice-pwd:7pgvs2UTcQbMdTnwEMiNEJ5N
a=ice-ufrag:tUzWi1Bsj9PCtVG3
a=ptime:20
a=rtcp:22816 IN IP4 S.S.S.S
a=rtcp-mux
a=rtpmap:109 opus/48000/2
a=rtpmap:101 telephone-event/8000
a=setup:active
a=ssrc:848923580 cname:JmSnxcWyBj6sKwRL
a=ssrc:848923580 msid:UqgPNluIbyxH1Azza7cYCyCPjrIxttfd a0
a=ssrc:848923580 mslabel:UqgPNluIbyxH1Azza7cYCyCPjrIxttfd
a=ssrc:848923580 label:UqgPNluIbyxH1Azza7cYCyCPjrIxttfda0
```

This is a bit difficult to intepret (for me) but it shows that FreeSWITCH is not trying to go to the TURN server, but is rather using STUN server information to ask my client to connect to the BBB server's external IP. This is the wrong thing to do, because there is no connectvity there. 

The corresponding logs in FreeSWITCH look like this:

```
ae237ad8-cd20-45e8-b2ff-9071f6e39339 2020-04-13 18:51:32.376439 [DEBUG] switch_core_media.c:4282 Save audio Candidate cid: 1 proto: UDP type: host addr: 192.168.155.130:40202
ae237ad8-cd20-45e8-b2ff-9071f6e39339 2020-04-13 18:51:32.376439 [DEBUG] switch_core_media.c:4282 Save audio Candidate cid: 1 proto: UDP type: host addr: 172.26.135.254:37828
ae237ad8-cd20-45e8-b2ff-9071f6e39339 2020-04-13 18:51:32.376439 [DEBUG] switch_core_media.c:4282 Save audio Candidate cid: 2 proto: UDP type: host addr: 192.168.155.130:39985
ae237ad8-cd20-45e8-b2ff-9071f6e39339 2020-04-13 18:51:32.376439 [DEBUG] switch_core_media.c:4282 Save audio Candidate cid: 2 proto: UDP type: host addr: 172.26.135.254:42766
ae237ad8-cd20-45e8-b2ff-9071f6e39339 2020-04-13 18:51:32.376439 [DEBUG] switch_core_media.c:4282 Save audio Candidate cid: 1 proto: UDP type: srflx addr: M.M.M.M:40202
ae237ad8-cd20-45e8-b2ff-9071f6e39339 2020-04-13 18:51:32.376439 [DEBUG] switch_core_media.c:4282 Save audio Candidate cid: 2 proto: UDP type: srflx addr: M.M.M.M:39985
ae237ad8-cd20-45e8-b2ff-9071f6e39339 2020-04-13 18:51:32.376439 [DEBUG] switch_core_media.c:4282 Save audio Candidate cid: 2 proto: UDP type: relay addr: C.C.C.C:29452
ae237ad8-cd20-45e8-b2ff-9071f6e39339 2020-04-13 18:51:32.376439 [DEBUG] switch_core_media.c:4282 Save audio Candidate cid: 1 proto: UDP type: relay addr: C.C.C.C:21796
ae237ad8-cd20-45e8-b2ff-9071f6e39339 2020-04-13 18:51:32.376439 [DEBUG] switch_core_media.c:4327 Searching for rtp candidate.
ae237ad8-cd20-45e8-b2ff-9071f6e39339 2020-04-13 18:51:32.376439 [DEBUG] switch_core_media.c:4336 Choose rtp candidate, index 2, M.M.M.M:40202
```

You can see that it chooses M.M.M.M, which are the srflx entries. I did not document the situation where STUN is disabled and only TURN exists, but in this case the HTML5 client sends only host and relay entries, and then FreeSWITCH chooses the relay instead. This is similar to the solution proposed in #8418 , which I think might be the same bug. (Feel free to merge/close this bug if that is the case.) 

**Desktop (please complete the following information):**
 - OS: Xubuntu 18.04
 - Browser: See above. I tried up to date Firefox and Chromium on Linux.
 
**Additional context**

The following comment is informative (from `bigbluebutton-html5/imports/utils/sdpUtils.js`):

```
const analyzeSdp = (sdp, sendLogs = true) => {
  // For now we just need to parse and log the different pieces. In the future we're going to want
  // to be tracking whether there were TURN candidates and IPv4 candidates to make informed
  // decisions about what to do on fallbacks/reconnects.
  const parsedSDP = transform.parse(sdp);
```

I was trying to figure out if there was an easy way to validate ICE candidates (maybe by making a sip.js call?) but I did not see one. I also note that the audio connection never makes a second attempt if the first one fails. If it did then the `relayOnlyOnReconnect` setting in `/usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties` might do something sensible. Maybe that would be the easiest workaround?

**Comment by matiasilva** [comment]
Hi. Any updates to this?

**Comment by pnijjar** [comment]
As far as I know the issue is still outstanding.

**Comment by ffdixon** [comment]
Thanks @pnijjar for the very detailed bug report.  We will investigate further.

**Comment by ha3ant** [comment]
Is there any update? :(

**Comment by ffdixon** [comment]
There is work underway to update BigBlueButton's SIP handling with stun/turn.  See

  https://github.com/bigbluebutton/bigbluebutton/issues/10569

@pnijjar  This work should merge into 2.2.27 and, as soon as we release, we'd be interested to hear if fixes the issue you reported.

(this was a very well written bug report!)

**Comment by basisbit** [comment]
Issue does not seem to occur any more in current versions. Thus closing this issue.
