### ISSUE TITLE
The following packages have unmet dependencies

### ISSUE THREAD

**Issue by deonvisser** [bigbluebutton/bigbluebutton#9193]
Hi
I have seen a few posts on this issue, however none solve my problem....

I am running Ubuntu 18.04. This the error I start off with trying to install the dependency bbb-config.
 bbb-config : Depends: bbb-apps but it is not going to be installed
              Depends: bbb-apps-sip but it is not going to be installed
              Depends: bbb-apps-video but it is not going to be installed
              Depends: bbb-apps-screenshare but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

I then start eliminating the dependencies by installing each dependency on its own....
This seems to go well until bbb-red5 that requires libcurl3. I install this dependency but then notice that even though bbb-apps dissapear as a dependency a new depency pops up requiring libcurl4.
I run through all the depencies untill the only dependency left is libcurl4. As soon as I install it, it overwrites libcurl3 and all the other dependencies show up again. So I cant actually install the dependencies. It is a vicious cirle.

Please can you assist?
I BBB Ubuntu 18.04 friendly? 
Thank you

**Comment by deonvisser** [comment]
This post allowed me to install both versions of curl...
https://launchpad.net/~xapienz/+archive/ubuntu/curl34

Now the problem is that Tomcat7 is failing install with error Failed to start LSB: Start Tomcat...

**Comment by basisbit** [comment]
Ubuntu 18.04 is not yet supported. Please use Ubuntu 16.04.

**Comment by deonvisser** [comment]
Thx u.

**Comment by basisbit** [comment]
Could you please close this issue if that answered your question?
