### ISSUE TITLE
Request: Option to turn off voice-over sound when you turn on/off the microphone

### ISSUE THREAD

**Issue by antonkhvorov** [bigbluebutton/bigbluebutton#9194]
**Is your feature request related to a problem? Please describe.**
The voice-over might be loud for someone and can be annoying sometimes.

**Describe the solution you'd like**
An option can be added in Options -> Settings -> "Voice over when turn on/off the microphone"

**Comment by basisbit** [comment]
do you mean the echo-test? It can already be enabled/disabled in the server configuration by the administrator.

**Comment by basisbit** [comment]
You might want to give these alternative mute/unmute sounds a try - they have much better user acceptance. https://gitlab.senfcall.de/senfcall-public/mute-and-unmute-sounds

**Comment by PhilippeAccorsi** [comment]
Thanks for you're link @basisbit \o/

We search also how change some other voice and the solution purpose in the link is the perfect solution to understand what we can do.
