### ISSUE TITLE
API getRecordings playback length in minutes(?)

### ISSUE THREAD

**Issue by aogilvie** [bigbluebutton/bigbluebutton#9195]
**Describe the bug**
recording playback length is listed in minutes, this should probably be seconds.

**To Reproduce**
1. Create session
2. Start recording
3. End recording after 30 seconds
4. make getRecordings API request

**Expected behavior**
30 seconds should show as the length value

**Actual behavior**
0 is shown.

**Screenshots**
```
    "playback": [{
        "format": [{
            "type": ["presentation"],
            "url": ["https://xxxx.xxxxx.jp/playback/presentation/2.0/playback.html?meetingId=be16d0f6f06074c3d5790f4ce902aa8caf3bdf9e-1587543641938"],
            "processingTime": ["34885"],
            "length": ["0"],
```

**Additional context**
After checking the bbb-recording-api, it just grabs `duration` from redis. I think redis is probably just writing seconds from somewhere.

https://github.com/bigbluebutton/bbb-recording-api/blob/98626056d20fa93a2ccb6ab75ff94ebcb897fdce/app/models/recording.rb#L59

**Comment by pedrobmarin** [comment]
Although I agree that minutes does not fit common patterns for this type of data I'm afraid we can't just change this right now since affects everyone that's using the API.

Letting this opened to be considered for a newer API version.
