### ISSUE TITLE
Bigbluebutton SSL issue

### ISSUE THREAD

**Issue by wamiqueL** [bigbluebutton/bigbluebutton#9196]
Hi,

I'm at the end of the installation, implemented SSL and after that its throwing the below error:

BigBlueButtonException: Impossible to convert XML to hash. Error: Missing end tag for 'hr' (got "body")

can you guide me please #ffdixon

**Comment by basisbit** [comment]
When you edited the configuration files, you probably accidentally removed a </hr> somewhere. Check the last files which you just changed.

**Comment by moonlies** [comment]
To everyone finding this in search for help:
You can run into this error if you have IPv6 disabled on your machine, but redis still binding on ::1.
One solution would be to remove `::1` from the bind statement in `/etc/redis/redis.conf`.
