### ISSUE TITLE
Recordings not playing back on iPadOS in desktop mode

### ISSUE THREAD

**Issue by cnapier** [bigbluebutton/bigbluebutton#9200]
Hi there,

I have just set up a BBB server for use at our school. It is integrated with Moodle. The sessions work fine, students and staff can log in and use it etc. Using latest version 2.2.5 on Ubuntu 16.04LTS

When the recordings make their way onto Moodle I can watch them fine on Mac and PC, and on iPhone. But on iPadOS 13.4 I just sit at the flashing BBB logo indefinitely. When I go into Website Settings and choose to request the Mobile version of the site it will work on the iPad. 

Safari on desktop Mac works fine so I suspect there is something in iOS safari in desktop browser mode that does not play nicely with the recording playback interface. If I can be of any assistance in tracking this down by providing logs please let me know.

Thanks!
Colin

**Comment by pedrobmarin** [comment]
Hi Colin, thanks for the report.
Are you able to collect iPadOS's browser Web Console logs and Network Monitor details?
Here's some help if needed https://developer.apple.com/safari/tools

**Comment by cnapier** [comment]
[raptor.legacy.whsict.net.har.zip](https://github.com/bigbluebutton/bigbluebutton/files/4516700/raptor.legacy.whsict.net.har.zip)

**Comment by pedrobmarin** [comment]
I'll take a better look as soon as possible. Right now I would just recommend users to use the mobile version at this new iPadOS.
Something I noticed is that you left both `webm` and `mp4` video formats at your record processing. I'm not 100% sure but `mp4` should be enough. So you can save on CPU and disk usage. I would give this a try.

**Comment by cnapier** [comment]
Hi Pedro.

I had originally only mp4 selected and it didn’t work so I enabled webm to
see if it would help. I will remove webm and rebuild all recordings and let
you know if it helps

**Comment by davidpesce** [comment]
I can't get recording playback to work on any mobile (iOS or Android) devices.

Environment:
- Scalelite v1.0.1
- Greenlight v2.5.4
- BBB 2.2.5

**Comment by cnapier** [comment]
Pedro,

Just to update you. I dropped Webm as you suggested and rebuilt the recordings. All seems to be working now! Thank you!
