### ISSUE TITLE
Docs: Missing HERE in customize.html#apply-custom-settings-for-turn-server 

### ISSUE THREAD

**Issue by hbruch** [bigbluebutton/bigbluebutton#9204]
**Describe the bug**
Not sure if there is another repo to file documentation issues.

In section
https://docs.bigbluebutton.org/2.2/customize.html#apply-custom-settings-for-turn-server 

```sh
echo "  - Update TURN server configuration turn-stun-servers.xml"
  cat <<HERE > /usr/share/bbb-web/WEB-INF/classes/spring/turn-stun-servers.xml
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://www.springframework.org/schema/beans
        http://www.springframework.org/schema/beans/spring-beans-2.5.xsd">
  ...
</beans>
```

the EOF delimiter HERE is missing.

**Comment by basisbit** [comment]
Thank you for the issue report! Could you maybe create a pull request at https://github.com/bigbluebutton/bigbluebutton.github.io to correct this?

**Comment by hbruch** [comment]
Closed via bigbluebutton/bigbluebutton.github.io#133
