### ISSUE TITLE
Too Slow Downloading Package BigBlueButton

### ISSUE THREAD

**Issue by bankos06** [bigbluebutton/bigbluebutton#9206]
I am installing the bbb but downloading the packages from https://ubuntu.bigbluebutton.org is very slow. 
Do you have another link?

![repo](https://user-images.githubusercontent.com/64150654/79997911-43048100-84e4-11ea-9a41-74ed082d5cd7.jpg)

Thanks

**Comment by ffdixon** [comment]
Try https://packages-eu.bigbluebutton.org

**Comment by matiasilva** [comment]
No follow up + good solution given.

**Comment by OmidAhmadyani** [comment]
Im from iran. packages-ue is slow too
