### ISSUE TITLE
Running bigbluebutton under haproxy

### ISSUE THREAD

**Issue by abhijitdaas** [bigbluebutton/bigbluebutton#9209]
Hello,

I am trying to setup setup bigbluebutton on a local server under haproxy with SSL certificate from letsencrypt

 www ----|Router w/ firewall|-------|haproxy|----------|bigbluebutton|

I have portforwarded the required ports following the setup guide in bigbluebuttons. All ssl certificate checks are done at haproxy and I am passing simple http to nginx. Things were looking good except one problem which I could not resolve. I see connection error in nginx/error.log

Error:  nginx/error.log
=========================================================================
2020/04/22 23:00:28 [error] 10572#10572: *43 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.1.101, server: vcr.XXXX.in, request: "GET /bigbluebutton/api HTTP/1.1", upstream: "http://127.0.0.1:8090/bigbluebutton/api", host: "vcr.XXXX.in"
2020/04/22 23:00:28 [error] 10572#10572: *43 open() "/var/www/nginx-default/50x.html" failed (2: No such file or directory), client: 192.168.1.101, server: vcr.XXXX.in, request: "GET /bigbluebutton/api HTTP/1.1", upstream: "http://127.0.0.1:8090/bigbluebutton/api", host: "vcr.XXXX.in"
========================================================================
As a result the Audio and video is not working from outside the firewall.
video and listenOnly mode works locally within the firewall but the Microphone is not working.

bbb status:
nginx —————————————————► [✔ - active]
freeswitch ————————————► [✔ - active]
redis-server ——————————► [✔ - active]
bbb-apps-akka —————————► [✔ - active]
bbb-transcode-akka ————► [✔ - active]
bbb-fsesl-akka ————————► [✔ - active]
red5 ——————————————————► [✔ - active]
tomcat7 ———————————————► [✔ - active]
mongod ————————————————► [✔ - active]
bbb-html5 —————————————► [✔ - active]
bbb-webrtc-sfu ————————► [✔ - active]
kurento-media-server ——► [✔ - active]
etherpad ——————————————► [✔ - active]
bbb-web ———————————————► [✔ - active]

bbb check:
BigBlueButton Server 2.2.5 (1848)
                    Kernel version: 4.4.0-177-generic
                      Distribution: Ubuntu 16.04.6 LTS (64-bit)
                            Memory: 16329 MB
                         CPU cores: 4

/usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties (bbb-web)
       bigbluebutton.web.serverURL: https://vcr.XXXX.in
                defaultGuestPolicy: ALWAYS_ACCEPT
                 svgImagesRequired: true

/etc/nginx/sites-available/bigbluebutton (nginx)
                       server name: vcr.XXXX.in
                              port: 80, [::]:80
                    bbb-client dir: /var/www/bigbluebutton

/var/www/bigbluebutton/client/conf/config.xml (bbb-client)
                Port test (tunnel): rtmp://vcr.XXXX.in
                              red5: vcr.XXXX.in
              useWebrtcIfAvailable: true

/opt/freeswitch/etc/freeswitch/vars.xml (FreeSWITCH)
                       local_ip_v4: 192.168.1.91
                   external_rtp_ip: host:vcr.XXXX.in
                   external_sip_ip: host:vcr.XXXX.in

/opt/freeswitch/etc/freeswitch/sip_profiles/external.xml (FreeSWITCH)
                        ext-rtp-ip: $${external_rtp_ip}
                        ext-sip-ip: $${external_rtp_ip}
                        ws-binding: :5066
                       wss-binding: :7443

/usr/local/bigbluebutton/core/scripts/bigbluebutton.yml (record and playback)
                     playback_host: vcr.XXXX.in
                 playback_protocol: https
                            ffmpeg: 4.2.2-1bbb1~ubuntu16.04

/etc/bigbluebutton/nginx/sip.nginx (sip.nginx)
                        proxy_pass: 192.168.1.91

/usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml (Kurento SFU)
                        kurento.ip: 192.168.1.91
                       kurento.url: ws://127.0.0.1:8888/kurento
                    localIpAddress: 192.168.1.91
               recordScreenSharing: true
                     recordWebcams: true
                  codec_video_main: VP8
               codec_video_content: VP8

/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml (HTML5 client)
                             build: 874
                        kurentoUrl: wss://vcr.XXXX.in/bbb-webrtc-sfu
                  enableListenOnly: true

# Potential problems described below
# IP does not match:
#                           IP from ifconfig: 192.168.1.91
#   /etc/nginx/sites-available/bigbluebutton: vcr.XXXX.in

# Warning: You have this server defined for https, but in
#
#   /etc/bigbluebutton/nginx/sip.nginx
#
#  did not find the use of https in definition for proxy_pass
#
#            proxy_pass http://192.168.1.91:5066;
#

# Warning: You have this server defined for https, but in
#
#   /etc/bigbluebutton/nginx/sip.nginx
#
#  did not find the use of port 7443 in definition for proxy_pass
#
#            proxy_pass http://192.168.1.91:5066;

Need your expert help to resolve this problem. Thank you.

**Comment by haviduck** [comment]
"you have this server defined for https but conf says http" 
"did not find the use of https in definition for proxy_pass"

Could u paste your nginx conf?

**Comment by abhijitdaas** [comment]
Nginx is setup for http. Haproxy absorbs the https requests, verifies the ssl certificates and passes the http request to Nginx. I noticed the warning but I did not change it as I am using default Nginx configuration for http.

**Comment by abhijitdaas** [comment]
The Mic and speaker is now working after I directly forwarded port 7443 to the server, bypassing haproxy. Only one thing that does not work is the webcam sharing. Although it is working within LAN. Any suggestion what may be amiss in the configuration?

**Comment by abhijitdaas** [comment]
Fixed the problem. It was a syntax error in coturn server that was causing trouble. Works great. Thank you BBB team for the great documentation.
