### ISSUE TITLE
Easy way to view the version

### ISSUE THREAD

**Issue by somuelle-tmt** [bigbluebutton/bigbluebutton#9212]
Hello,

what is the easiest way to view the version? On the start page it seems to always say 2.2 no matter if it is 2.2.0 or 2.2.5.

Background: Our customers have partly self-hosted and partly rented BBBs in our LMS and we would like to check if they already have all the fixes from 2.2.3 in case of error messages.

With kind regards
Sören

**Comment by mtelgkamp** [comment]
You can use `bbb-conf --check` on the server to show the version number (and other information).
If you only want to see the version use `bbb-conf --check | head -n2`.

**Comment by somuelle-tmt** [comment]
Thanks for your answer, but most of our costumers (including us) are renting a BBB as SaaS and don't have "access" to their servers nor want it.
Many of our costumers now think they have versions like 874 because that's what displayed in the browser, but this number is something different, right? It's a bit confusing

**Comment by mtelgkamp** [comment]
My comment was the only way I figured out to get the current version of BBB as even `bbb-config --version` does not give you this version number. I second that it is confusing and also support #9264 and. I am also "just a user" but we installed BBB on one dedicated virtual server and do not use it as SaaS, thus I was able to get the version info using the command mentioned above and shared my knowledge.

**Comment by frank-miller9** [comment]
You can use: ```sudo bbb-conf --check | grep BigBlueButton```

**Comment by somuelle-tmt** [comment]
@frank-miller9 I can not. Please read my comment

**Comment by matiasilva** [comment]
The "version" shown in the HTML5 client is the build number of the bbb-html5 package. You can change this to whatever you wish in `/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml`. It makes more sense to display the build number of the package than the overall version of BBB in my opinion. For end users, this doesn't really make a difference. Those who should care about this, should probably also have access to the console commands explained above. Closing for now as an adequate response has been provided.

**Comment by somuelle-tmt** [comment]
Unfortunately not a single adequate answer was given here. We now rent a BBB from a hoster, and (logically) have no access to the server, as with all other SaaS services.

I don't understand why we should be interested in the build number of a package, I would like to know right now if we already have 2.2.9 and can therefore forbid private chats in breakout rooms. I don't think I can force our service provider to edit some yaml files after every update?

**Comment by matiasilva** [comment]
I see. I'll reopen this issue seeing as it is something that could be fixed with relative ease and there seems to be demand for it as I closed two similar issues. For now, you can cross reference the build number for the bbb-html5 package in [this](https://github.com/bbb-pkg/bbb-html5/commits/master) unofficial repo with the current release at the moment which is 2.2.17.

**Comment by romale** [comment]
it seems to me more logical to show the version, for example 2.2.29,
in this command or some where on web interface
`bbb-conf --version`

**Comment by christmart** [comment]
My solution is to place the BBB version into this field via apply-config.sh:

    BBBVER=$(bbb-conf --check | egrep ^BigBlueButton)
    HTML5VER=$(dpkg -l bbb-html5 | awk 'BEGIN { FS = "[ \t-]+" }; /bbb-html5/ { print "HTML5Client " $5 }')

    yq w -i $HTML5_CONFIG public.app.html5ClientBuild "$BBBVER, $HTML5VER"

This results in this in the version info menu:

  Clientversion: BigBlueButton Server 2.2.28 (2184), HTML5Client 1032

**Comment by aguerson** [comment]
`cat /etc/bigbluebutton/bigbluebutton-release`

**Comment by rastarasta** [comment]
Does apply-config.sh still work with BBB v2.4?  I used the following  (created an apply-config.sh, made it executable and rebooted) and it did not change the BBB About box.  The customization's purpose is to display both the BBB server version (e.g. 2.4.0) and the build number.  

christmart wrote:

> My solution is to place the BBB version into this field via apply-config.sh:
> 
> BBBVER=$(bbb-conf --check | egrep ^BigBlueButton)
> HTML5VER=$(dpkg -l bbb-html5 | awk 'BEGIN { FS = "[ \t-]+" }; /bbb-html5/ { print "HTML5Client " $5 }')
> 
> yq w -i $HTML5_CONFIG public.app.html5ClientBuild "$BBBVER, $HTML5VER"
> This results in this in the version info menu:
> 
> Clientversion: BigBlueButton Server 2.2.28 (2184), HTML5Client 1032 
>

**Comment by antobinary** [comment]
As of BBB 2.5-alpha-2 (coming out)
![Screenshot from 2022-02-25 11-31-15](https://user-images.githubusercontent.com/6312397/155759544-ec668867-e952-4e23-aa41-993f9a9432ed.png)
