### ISSUE TITLE
nginx can't run after run "Collect feedback from the users" script

### ISSUE THREAD

**Issue by MrCapitalist** [bigbluebutton/bigbluebutton#9217]
Hello
I installed BBB using step by step instruction. At end, I added a feedback.sh in my host and put script in [this link](https://docs.bigbluebutton.org/2.2/customize.html#collect-feedback-from-the-users) on that. Then ran it in terminal. 

After that, I used `bbb-conf --restart` but it didn't start correctly. How can I resolve this problem or get changes back?!

These are some codes to debug:

```
root@bigbluebutton:~# bbb-conf --restart
Restarting the BigBlueButton 2.2.5 ...
Stopping BigBlueButton

Starting BigBlueButton
Job for nginx.service failed because the control process exited with error code. See "systemctl status nginx.service" and "journalctl -xe" for details.
```

```
root@bigbluebutton:~# bbb-conf --status
nginx —————————————————► [✘ - failed]
```

```
root@bigbluebutton:~# bbb-conf --check
Potential problems described below
Not running:  Nginx
root@bigbluebutton:~# nginx -t
nginx: [emerg] unknown log format "postdata" in /etc/bigbluebutton/nginx/html5-client-log.nginx:2
nginx: configuration file /etc/nginx/nginx.conf test failed
```

Data in `/etc/bigbluebutton/nginx/` is:

```
location /html5log {
        access_log /var/log/nginx/html5-client.log postdata;
        echo_read_request_body;
}

cat > /etc/nginx/conf.d/html5-client-log.conf << HERE
log_format postdata '$remote_addr [$time_iso8601] $request_body';
```

**Comment by SasanGF** [comment]
I resolved this problem!
Unfortunatly the script has been added this code directly to `/etc/bigbluebutton/nginx/html5-client-log.nginx`

`cat > /etc/nginx/conf.d/html5-client-log.conf << HERE
log_format postdata '\$remote_addr [\$time_iso8601] \$request_body';`

I removed that code from file and create a `html5-client-log.conf` file in `/etc/nginx/conf.d` manualy and added other part of code in it. Then restarted nginx and problem solved.

This is a bug in the script. Please check it. Thank you

**Comment by SasanGF** [comment]
But I still have problem in save feedback result. I changed `askForFeedbackOnLogout: true` in `/usr/share/meteor/bundle/programs/server/assets/app/config` and restarted my server. I Opened a meeting, ended it and entered a feedback. Then checked `/var/log/nginx/html5-client.log` but there wasn't anything in this file!

**Comment by niketnaik** [comment]
@SasanGF  i am facing the same issue as yours. Firstly i had to remove the code from html5-client-log.nginx and then i tried to start the nginx and it worked.
Now it is working but after adding the feedback the log file is blank.

**Comment by mleu77** [comment]
#9065 
This script should do it in the right way
`#!/bin/bash

HOST=$(cat /usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties | grep -v '#' | sed -n '/^bigbluebutton.web.serverURL/{s/.*\///;p}')
PROTOCOL=$(cat /usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties | grep -v '#' | grep '^bigbluebutton.web.serverURL' | sed 's/.*\(http[s]*\).*/\1/')
HTML5_CONFIG=/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml

apt-get install -y nginx-full

yq w -i $HTML5_CONFIG public.clientLog.external.enabled true
yq w -i $HTML5_CONFIG public.clientLog.external.url     "$PROTOCOL://$HOST/html5log"
yq w -i $HTML5_CONFIG public.app.askForFeedbackOnLogout true
chown meteor:meteor $HTML5_CONFIG

cat > /etc/bigbluebutton/nginx/html5-client-log.nginx << HERE
location /html5log {
        access_log /var/log/nginx/html5-client.log postdata;
        echo_read_request_body;
}
HERE
cat > /etc/nginx/conf.d/html5-client-log.conf << HERE
log_format postdata '\$remote_addr [\$time_iso8601] \$request_body';
HERE

if ! dpkg -l | grep -q nginx-full; then
  apt-get install -y nginx-full
fi

touch /var/log/nginx/html5-client.log
chown bigbluebutton:bigbluebutton /var/log/nginx/html5-client.log`

**Comment by SasanGF** [comment]
Thanks. It applied without any problem but it still doesn't save feedbacks! My `/var/log/nginx/html5-client.log` is empty

**Comment by niketnaik** [comment]
@mleu77 not working for me either

**Comment by htwmehdi** [comment]
Hi,

got same issue with the script.

I solved by doing this :

Content of /etc/bigbluebutton/nginx/html5-client-log.nginx   :

```
 location /html5log {
         access_log /var/log/nginx/html5-client.log postdata;
         echo_read_request_body;
 }
```
Create a file /etc/nginx/conf.d/html5-client-log.conf with following content :

`log_format postdata '\$remote_addr [\$time_iso8601] \$request_body';`

Then, in /usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml

you will find that external: {enabled: true, level: info, url: ' is missing the protocol and looks like this :

external: {enabled: true, level: info, url: '://domain.com/html5log', method: POST,
simply add https so it looks like :

{enabled: true, level: info, url: 'https://domain.com/html5log', method: POST,

**Comment by ffdixon** [comment]
We would welcome a pull request to update the script.  The code is also here

  https://github.com/bigbluebutton/bigbluebutton/blob/develop/bigbluebutton-config/bin/apply-lib.sh#L43

See also

  http://docs.bigbluebutton.org/2.2/customize.html#automatically-apply-configuration-changes-on-restart

**Comment by niketnaik** [comment]
Thank you @ffdixon  i resolved the issue. :)

**Comment by amishbhavsar** [comment]
I ran the  #following commands and the breakout rooms started working.
```
sudo bbb-record --deleteall
sudo bbb-conf --stop
sudo bbb-conf --start
```

**Comment by mbile** [comment]
Hello everyone,

@ffdixon, @MrCapitalist I have enabled the feedback on my BBB server, now I am looking ways to customize the text that is being shown to the participants when they leave the session. I would be happy if anyone can help me locate which file the text "We'd love to hear about your experience with BigBlueButton (optional)" is in. 
Regards,

**Comment by mbile** [comment]
Thank you guys,

I found it. The text is in this file,in my case,:
/usr/share/meteor/bundle/programs/server/assets/app/locales/en.json

**Comment by amishbhavsar** [comment]
Hi guys,
I have a simple request. I am not familiar with Ubuntu server and how to run the script for feedback. If there a help doc or step by step video that anyone can point me to?
