### ISSUE TITLE
Support playing videos hosted on peertube servers 

### ISSUE THREAD

**Issue by dranjor** [bigbluebutton/bigbluebutton#9226]
Peertube is a great alternative to centralized video platforms (https://en.wikipedia.org/wiki/PeerTube)

**Comment by matiasilva** [comment]
The HTML5 client uses ReactPlayer to embed videos. If you can somehow find a way to link the two, that'd be great.

**Comment by hex-m** [comment]
There is an issue about PeerTube in the react-player repo (I hope I found the right one): https://github.com/CookPete/react-player/issues/570

**Comment by ljoets** [comment]
It's a very needed feature for us ! :-)

**Comment by matiasilva** [comment]
@ljoets 

> I'm wary of adding built-in support for more players that aren’t likely to be needed by the majority of users, as it bloats the package size. Custom players are supported, though.

**Comment by rzr** [comment]
This is desirable I was unable to share this video
https://peertube.qtg.fr/videos/watch/d4aab174-50ca-4455-bb32-ed463982e943
to my OpenFest2020 friends :-)

**Comment by guidtz** [comment]
I think so it will be a good features in BBB. We try to provided to our users opensource sorftware and when we provide BBB + Peertube It will be a good features to play videos from Peertube in BBB.

Regards

**Comment by tuxayo** [comment]
> I'm wary of adding built-in support for more players that aren’t likely to be needed by the majority of users, as it bloats the package size.

It's the main libre video platform it's worth it to have a least one libre option.

> Custom players are supported, though.

What do you mean?

**Comment by tuxayo** [comment]
On the technical side, PeerTube has an Embed API that should provide everything needed.
https://docs.joinpeertube.org/#/api-embed-player

**Comment by ThierryM** [comment]
Hi,
Peertube is the tool recommanded for schools in France (but not only) because it respects the privacy rights.
So BBB should allow to display video hosted on a peertube instance.
Regards

**Comment by rzr** [comment]
I'll be curious to know why peertube satisfied the "privacy rights" by French institutions?

Not that I want to promote alternative platform but I think peertube privacy model could be improved (like any other p2p without EEE) 


An other suggestion would be to allow embedding any video file hosted on plain HTTP (Peertube allows file to be downloaded this way).


But I suspect that bigbluebutton hardcoded a couple to "trusted" websites to avoid downloading potential malware hosted on any random places.


May this discussion relocated elsewhere.

**Comment by ThierryM** [comment]
> I'll be curious to know why peertube satisfied the "privacy rights" by French institutions?

For the french pupils and the teachers, the privacy rights are satisfied because the peertube instances for the schools are "hosted" by the French institution Éducation nationale.

**Comment by matiasilva** [comment]
> > Custom players are supported, though.
> 
> What do you mean?

React player supports custom players that can parse and display video feeds coming from a variety of sources. The inclusion of Panopto for BBB is one example.

**Comment by ljorzick** [comment]
As we are currently running both Peertube and BBB hosted locally, this would be a welcome feature for us as well!

**Comment by hex-m** [comment]
It was mentioned on the [mailing list](https://groups.google.com/g/bigbluebutton-dev/c/c8pj73bWHww/m/X9XB0Op-AgAJ) that this was implemented. I just tested it on a local deployment (2.2.32) and on https://test.bigbluebutton.org. Works fine.

**Comment by rzr** [comment]
Funkwhale could be next ? any open ticket for fediverse related features ?

**Comment by dranjor** [comment]
Peertube support seems to be removed. Please re-implement it.

**Comment by tuxayo** [comment]
What do you mean? I just tried with
https://peertube.f-si.org/videos/watch/7f0d58b4-ef95-4f9c-ba68-7f9c8a03e91d?api=1&controls=true&start=36s
on
https://test.bigbluebutton.org
and it worked.
It's just a quick test alone though.

**Comment by dranjor** [comment]
I tested with https://tube.tchncs.de/w/kkGMgK9ZtnKfYAgnEtQxbv on https://test.bigbluebutton.org

It seems to me, that it depends on the peertube version:
- https://peertube.f-si.org  -- v1.2.1
- https://tube.tchncs.de -- 3.4.0

On https://demo.bigbluebutton.org/ (currently client version 2326) I have no issues, so maybe I  just have to wait for 2.4 ...

**Comment by Chocobozzz** [comment]
Hello,

Another URL format is supported by PeerTube >= 3.3 (`/w/:id` instead of `/videos/watch/:uuid`). It's the reason why some URLs work and others don't. It seems it will be fixed in next BBB version: https://github.com/bigbluebutton/bigbluebutton/commit/bdb8c72d79f1128ee0dfb80244a03b8fb424698c#diff-65d9470df4c4e4297825e98fe0649617edee69f158ff399cccfb6e1641cbbcdc

So I think this issue can be closed.
