### ISSUE TITLE
access room with "moderator pin"

### ISSUE THREAD

**Issue by dranjor** [bigbluebutton/bigbluebutton#9227]
Currently rooms can be protected by a pin. Guests who know this key can enter. 
It would be nice if an additional "moderator pin" could be defined. Guests who know this key will be promoted to moderator role.

**Comment by Sea444** [comment]
This exists. When you use API getMeetings you see moderator Pin for your active sessions:

<attendeePW>jExISZJITFRW</attendeePW>
<moderatorPW>WeaBtgHgDZV</moderatorPW>
