### ISSUE TITLE
Differnt volumes of members of a meeting

### ISSUE THREAD

**Issue by ejgutierrez74** [bigbluebutton/bigbluebutton#9228]
Describe the bug
In meetings, there is different volume of voices of different memebers. Some of them are very low, and usuarlly one is very high, which is annoying. 
Id like to control and low the volume of members in my system, as said, some can be put with top volume, because they sound very low, and some of them have to be put the volume very low, because their volume is annoying high.
The volume of my system and speakers are not modified.

To Reproduce

1- Enter in a meeting with different members'
2 - Begin to tlak with members
3 - See error

Expected behavior
All the members with same or reasonably similar volume, as you can hear in your system controlling  volume and/or speakers level.

Actual behavior
Different volumes. Some are very annoying.

    OS: Ubuntu 18.04, Windows 10
    Browser [e.g. Chrome, Safari] Firefox
    Version [e.g. 22] 75

**Comment by iSamof** [comment]
This is already being discussed and you may wish to contribute this: https://github.com/bigbluebutton/bigbluebutton/issues/9046
