### ISSUE TITLE
Audio stream settings

### ISSUE THREAD

**Issue by solblade** [bigbluebutton/bigbluebutton#9229]
How can i edit audio stream quality settings? I want to have CBR in translation about 160kBit/s. It's possible? And how this realised? 
We create musicants conference and sound when we play is not good quality. Video settings we changing, and with this options no problem, but audio settings (bitrate, quality and other) we can't find. Please help with this.
Thank you.

**Comment by mtsonline** [comment]
Hi,

if you get music running please let us know, we where not able to improve audio quality as much as would be needed to have music played without distortion.

to disable variable bittrate and set a defined rate have a look at the opus conf:
https://pastebin.com/raw/SKbBAe2n
and follow this thread:
https://groups.google.com/d/msgid/bigbluebutton-setup/aea2e811-7d9a-0237-a08f-2e357313080f%40mtsonline.at

cheers
Martin

**Comment by basisbit** [comment]
FreeSWITCH allows for fine grained adjustment of audio quality, microphone sensitivity, channel count, bitrate, compress types and more. These settings affect audio quality, required bandwidth usage, how fault-tolerant audio transmission to/from the clients is and how much CPU resources are required, so make sure to test any changes of the default settings.

- For example, in `/usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml` you can configure the `maxaveragebitrate` and `maxplaybackrate` of the selective forwarding unit (how BBB mixes and forwards audio to listen-only clients).
- In `/opt/freeswitch/etc/freeswitch/autoload_configs/conference.conf.xml` you can change `cdquality` (or whichever profile you use) -> `channel` to 2 for stereo audio.
- In `/opt/freeswitch/etc/freeswitch/dialplan/default/bbb_conference.xml` you can adjust general audio settigns of FreeSWITCH like jitter-buffer size and which audio profile to use from the conference.conf.xml. 
- In `/opt/freeswitch/etc/freeswitch/autoload_configs/opus.conf.xml` you can configure settings for the audio codec opus - notable are `use-vbr` where you can choose between 0 for coded-bit-rate and 1 for variable-bit-rate, `sprop-stereo` for switching between mono and stereo and `sprop-maxcapturerate` + `maxplaybackrate` + `maxaveragebitrate` for setting the desired audio bitrate.

For more details see the [FreeSWITCH documentation](https://freeswitch.org/confluence/display/FREESWITCH/mod_opus).


---

Here is a sample change from a friend who cares about high quality audio/music quality (@schrd):
In `/opt/freeswitch/etc/freeswitch/dialplan/default/bbb_conference.xml`:
```
...
      <condition field="destination_number" expression="^(\d{5,11})$">
        <action application="set" data="jitterbuffer_msec=60:120:20" />
        <action application="set" data="rtp_jitter_buffer_plc=true" />
        <action application="set" data="rtp_jitter_buffer_during_bridge=true" />
        <action application="set" data="suppress_cng=true" />
        <action application="answer"/>
        <action application="conference" data="$1@cdquality"/>
      </condition>
    </extension>
    <extension name="bbb_conferences">
      <condition field="${bbb_authorized}" expression="true" break="on-false"/>
      <condition field="destination_number" expression="^(\d{5,11})$">
        <action application="jitterbuffer" data="60:120"/>
        <action application="set" data="jitterbuffer_msec=60:120:20" />
        <action application="set" data="rtp_jitter_buffer_plc=true" />
        <action application="set" data="rtp_jitter_buffer_during_bridge=true" />
        <action application="set" data="suppress_cng=true" />
        <action application="answer"/>
        <action application="conference" data="$1@cdquality"/>
      </condition>
    </extension>
...
```

In `/opt/freeswitch/etc/freeswitch/autoload_configs/opus.conf.xml`
```
<configuration name="opus.conf">
      <settings>
        <param name="use-vbr" value="0"/>
        <param name="use-dtx" value="0"/>
        <param name="complexity" value="10"/>
        <param name="packet-loss-percent" value="15"/>
        <param name="keep-fec-enabled" value="1"/>
        <param name="use-jb-lookahead" value="1"/>
        <param name="advertise-useinbandfec" value="1"/>
        <param name="adjust-bitrate" value="1" />
        <param name="maxaveragebitrate" value="160000" />
        <param name="maxplaybackrate" value="48000" />
        <param name="sprop-maxcapturerate" value="48000" />
        <param name="sprop-stereo" value="1" />
        <param name="negotiate-bitrate" value="1" />
      </settings>
</configuration>
```

I'll close this issue for now, if there is more to be discussed, we can reopen the issue.
If you use this (or a similar config) in production, it would be nice if you could comment on the results of this change.

**Comment by soheilrahsaz** [comment]
I have also found this link helpful:
https://git.fairkom.net/hosting/fairteaching/-/issues/29
