### ISSUE TITLE
dark background presentations uploaded disrupted by white clearing flash

### ISSUE THREAD

**Issue by ReimarBauer** [bigbluebutton/bigbluebutton#9231]
**Is your feature request related to a problem? Please describe.**

We have used  a dark background color and have recognized that we now have after uploading and using it always between two slides a white colored clearing flash.
Something like a white page is shown after each slide just before the next slide shows up.

**Describe the solution you'd like**
The seperating page color which is shown just before the next slide should have same color as the background of the slides. 

Alternativly the user should be able to upload the background slide.

**Describe alternatives you've considered**
use only white background

**Additional context**
Example background black:
[dark_slides.pdf](https://github.com/bigbluebutton/bigbluebutton/files/4526747/dark_slides.pdf)

**Comment by dexteritas** [comment]
I had the same problem with dark slides. I think the best solution would be to buffer the next slides and show the current slide until the next slide is ready. So there would be no need to define a background color. This would also reduce the waiting time for a slide change.

**Comment by dexteritas** [comment]
I just noticed that my idea to buffer the next slides has already been mentioned in [#9011](https://github.com/bigbluebutton/bigbluebutton/issues/9011) and might be resolved by [#9012](https://github.com/bigbluebutton/bigbluebutton/issues/9011). The white flash may also be fixed by this.
