### ISSUE TITLE
High CPU usage by client with many webcams

### ISSUE THREAD

**Issue by mikhailnov** [bigbluebutton/bigbluebutton#9233]
First of all thanks for developing the HTML 5 version of BBB, it works well in general.

There is an issue: when there are 6-8 webcams being showed at the same time, CPU usage by the client is very high and may be near or above the top of opportunities of the hardware.
Bellow are screenshots of 3 different machines (mine and 2 else via SSH) during a video conference call. In all cases CPU usage is very high.

![DeepinScreenshot_Desktop_20200424103024](https://user-images.githubusercontent.com/15802528/80190947-b3fb8400-861d-11ea-8417-eb620a40fc13.png)

![DeepinScreenshot_Desktop_20200424103230](https://user-images.githubusercontent.com/15802528/80190967-b9f16500-861d-11ea-97c8-012d751c4fca.png)

![DeepinScreenshot_Desktop_20200424110427](https://user-images.githubusercontent.com/15802528/80190982-bfe74600-861d-11ea-89f7-a32a1b810604.png)

If the number of active webcams is reduced, than CPU usage is reduced dramatically. Seems that it happens with both Chromium and Firefox clients, but sometimes CPU usage is not so high for some reasons. All webcams are using the default "medium" bitrate.

That means that decoding of one video stream cosumes too much CPU power.
Now the only recommened solution of this problem is reducing the bitrate (https://docs.bigbluebutton.org/2.2/customize.html#reduce-bandwidth-from-webcams). Seems that the default bitrate can be reduced in this situation, but maybe there are other ways of reducing CPU load by video decoder and javascript code?

Which codec is used now? Is there are a way to switch to use H264 if US patents do not bother me when the client supports it and fallback to vp8 otherwise? H264 can at least by decoded by GPU in _some_cases, more often than VP8.
According to @prlanzarin in  https://github.com/bigbluebutton/bigbluebutton/issues/8803#issuecomment-600578293 , `/usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml` can be edited, but I did not understand if it is possible to configure "use h264, if possible, fallback to vp8 otherwise".

From the point of view of javascript code, can the load be reduced?

**Comment by mikhailnov** [comment]
Seems that CPU usage by so many webcams in the Flash client is less.

**Comment by Daedalus3** [comment]
Cant help you but do have exactly the same problem. Right now this makes us stick to zoom (which I really don't want to but CPU Usage problems on both the server (8 cores, 32 GB ram) and older client pcs are just too big. :-( )

**Comment by prlanzarin** [comment]
@mikhailnov setting `ANY` in `codec_video_main` will make it not enforce a specific codec. `  codec_video_main_priority` can be used alongside the aformentioned ANY options to define a preferred one in that lenient model (ie setting `  codec_video_main_priority` to H264 will make it prefer H.264 over VP8 if both are available, but will still use VP8 if H264 isn't available).

I don't recommend H.264, though. It's known for causing some problems client and server side. I know you're looking for HW acceleration for decoding, and you can try it out, but I don't think it'll be worth the tradeoff.

As for the client side CPU usage, raw decoding usage is kind of out of our reach since it's a browser thing. Best you can do right now is lower bitrate as suggested. We do have some performance issues with how the video UI is managed on 2.2, though, which is on us, but there are some improvements for that in the works for the next version.

**Comment by mikhailnov** [comment]
@prlanzarin thanks. Yes, I am looking for HW acceleration for decoding, HW decoding of H264 is available much more often than of VP8, that is why I will probably give a try to make H264 a first choice based on your recommendations.

> but I don't think it'll be worth the tradeoff
Why do you think so?

**Comment by prlanzarin** [comment]
> Why do you think so?

- Licensing
- Current version of gstreamer BBB uses has some issues with H.264 under high load scenarios (ie the H264 parser gets CPU pegged for some reason, higher CPU usage than normal, etc).
- Client-side: there were some pretty weird problems with green artifacts on low bitrate streams and Firefox having its H.264 components deadlocked. I don't know if the client-side problems persist because I haven't looked at them in the last couple of months.

But, as I said, try it out if you wish. If you end up testing it, are willing to put up with licensing stuff and see the aforementioned problems are rare in your use cases and/or are worth the trouble, go for it.

**Comment by mikhailnov** [comment]
Is there a way to check which codec is really being used? `chrome://media-internals` does not show codecs for webcams...

**Comment by mikhailnov** [comment]
I have filed a Chromium bug about that it does not show the codec: https://bugs.chromium.org/p/chromium/issues/detail?id=1079305

**Comment by prlanzarin** [comment]
@mikhailnov Hmm... You might wanna close that bug entry. You're looking at the wrong place.
You should go to chrome://webrtc-internals to look at the codec currently being used.
i.e.:
 1. open chrome://webrtc-internals
 2. share camera in a BBB session
 3. a new RTCPeerConnection entry will be in chrome://webrtc-internals. Look for a `RTCOutboundRTPVideoStream_<number> (outbound-rtp)` entry, expand it. There'll be a `codec` field that states the codec in use for that track. If it's not precisely in the RTCOutboundRTPVideoStream entry, skim through the other entries. There will be at least one with the `codec` field.

**Comment by mikhailnov** [comment]
Thanks! But it does show "H264" and "ExternalDecoder" which probably means GPU decoding, because I saw "FFmpeg" on machines without enabled VA-API.
![image](https://user-images.githubusercontent.com/15802528/81311828-8d623200-908e-11ea-884f-b12e04e82723.png)

There are client-side problems at least in Chromium-based browsers (did not try other): random webcams randomly become covered with green artefacts for some time. Screenshots:
![DeepinScreenshot_выберите-область_20200507173111](https://user-images.githubusercontent.com/15802528/81312177-02356c00-908f-11ea-93f4-2200c78d2db3.png)
![DeepinScreenshot_выберите-область_20200507174602](https://user-images.githubusercontent.com/15802528/81312386-4294ea00-908f-11ea-97d4-250e30226ce1.png)

I am not sure yet if H264 + VA-API really gives measurable benefits on that specific hardware:
https://linux-hardware.org/index.php?probe=0bc279404d
(vainfo: https://linux-hardware.org/index.php?probe=0bc279404d&log=vainfo - H264 is supported for hardware acceleration, but VP8 is not)

So, I will have to rollback to VP8, but, if VA-API + H264 do help, H264 will have to be forced on that client (presenter) machine. Maybe it will be possible to edit h264ify extension (https://github.com/erkserkserks/h264ify/blob/master/manifest.json#L21) and add BBB server to that least alongside youtube, but I am not sure that it will work for WebRTC (https://github.com/erkserkserks/h264ify/blob/master/src/inject/inject.js#L40)

**Comment by aljubaoc** [comment]
Tuve el mismo problema y lo solucioné cambiando el ancho de banda en el archivo /usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml).  Así:  low:50, medium: 80 default, high:200, hd:500

**Comment by raoulkramer** [comment]
It would be great if the amounts of webcams could be reduced automatically to the amount of speakers like this option in issue https://github.com/bigbluebutton/bigbluebutton/issues/9392

**Comment by prlanzarin** [comment]
Merging with https://github.com/bigbluebutton/bigbluebutton/issues/9392.

**Comment by adam-op** [comment]
Hi

I confirm that with the current version of BBB
...frozen webcams in meetings with 20 to 25 members
...load up to 8(!) on a two core CPU, 2 would be aimed at

Ubuntu 22.04
Firefox 106.03
Hp Elitebook G3 1040
16 GB RAM
Intel(R) Core(TM) i5-7300U CPU @ 2.60GHz
Copyright: ©2022 BigBlueButton Inc.
Client build: 2857
BigBlueButton version: 2.5.6

I will check in Chromium, too, later...
