### ISSUE TITLE
Networking: Dummy NIC results in Could not connect to the configured hostname/IP address

### ISSUE THREAD

**Issue by DOCS-kdu3** [bigbluebutton/bigbluebutton#9237]
Presently I am trying to configure BigBlueButton to accept external IP audio / video connections on an instance behind a firewall.

I have an issue where I receive the ICE 1007 error when not on the local network. The `about:webrtc` shows the remote candidate binding to the local ip.

Setting up the dummy NIC loopback allows freeswitch to successfully bind the external profile wss traffic to the external ip of the server, told by 

```
/opt/freeswitch/bin/fs_cli
sofia status profile external
```

as described [here.](https://groups.google.com/forum/#!topic/bigbluebutton-setup/cw4v1DK-xzY)

The problem I face is: When the dummy loopback rule is established, BigBlueButton fails to be served properly and `bbb-conf --check` results with: Could not connect to the configured hostname/IP address

`wget -qO- https://HOSTNAME` stops returning an html page.

My nginx log `/var/log/nginx/error.log` presents the following error:
```
2020/04/24 09:54:13 [error] 28752#28752: *23 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.22.225, server: HOSTNAME, request: "GET /bigbluebutton/api HTTP/1.1", upstream: "http://127.0.0.1:8090/bigbluebutton/api", host: "HOSTNAME"
```

`netstat -atnp | grep 8090`
```
tcp        0      0 127.0.0.1:54844         127.0.0.1:8090          TIME_WAIT   -               
tcp6       0      0 :::8090                 :::*                    LISTEN      11054/java 
```

`bbb-conf --status`
```
nginx —————————————————► [✔ - active]
freeswitch ————————————► [✔ - active]
redis-server ——————————► [✔ - active]
bbb-apps-akka —————————► [✔ - active]
bbb-transcode-akka ————► [✔ - active]
bbb-fsesl-akka ————————► [✔ - active]
red5 ——————————————————► [✔ - active]
tomcat7 ———————————————► [✔ - active]
mongod ————————————————► [✔ - active]
bbb-html5 —————————————► [✔ - active]
bbb-webrtc-sfu ————————► [✔ - active]
kurento-media-server ——► [✔ - active]
etherpad ——————————————► [✔ - active]
bbb-web ———————————————► [✔ - active]
```

I'm thinking this might be a firewall issue, but I am not sure how to solve it.

**Comment by matiasilva** [comment]
No follow up in two months. Feel free to post at https://groups.google.com/forum/#!forum/bigbluebutton-setup where your request for help can be better handled.
