### ISSUE TITLE
Freeswitch 

### ISSUE THREAD

**Issue by agustinmono** [bigbluebutton/bigbluebutton#9238]
I have this erros in the .log

`f37197c0-0919-411e-b6d8-4d2f26f07a70 2020-04-23 09:56:09.281227 [ERR] switch_rtp.c:6027 RTCP UNPROTECT ERR`
`f37197c0-0919-411e-b6d8-4d2f26f07a70 2020-04-23 10:00:41.061221 [ERR] switch_rtp.c:6027 RTCP UNPROTECT ERR`

Whats wrong?

**Comment by prlanzarin** [comment]
Does this translate to an actual audio failure or you just noticed it amid the logs without a visible user-side problem?

That error means the encrypted RTCP packets going from a client to FS got botched somehow and FS couldn't decrypt it. Might be an accidentally replayed RTCP which will make libsrtp reject it. Might be that the packet got corrupted. Might be a bunch of other stuff.

Point being: occasional SRTP unprotect failures can happen and shouldn't be fatal. Too frequent unprotect failures, though, shouldn't happen. So it'd be good to know how frequent you're seeing those in for a single channel (wc -l the log for that error isolating the counts by uuid, which is the first log parameter ie `f37197c0-0919-411e-b6d8-4d2f26f07a70` in the log you pasted).

**Comment by agustinmono** [comment]
Honestly i dont remember, I dont think that the problem persist. I used to have one big server for too many users. Now I splitted the server into 6 Virtual machine and using scalelite as loadbalancer

It works fine at the moment.

Best,
Agustin
