### ISSUE TITLE
bbb-conf --debug

### ISSUE THREAD

**Issue by crog3ar** [bigbluebutton/bigbluebutton#9242]
bbb-conf --status
display ALL active

-- Errors found in /var/log/nginx/error.log --
2020/04/24 12:12:37 [error] 2333#2333: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 93.143.222.117, server: bigblue.ferit.hr, request: "GET /html5client/sockjs/info?cb=1b2xaz1gmf HTTP/1.1", upstream: "http://127.0.0.1:300                                    0/html5client/sockjs/info?cb=1b2xaz1gmf", host: "bigblue.ferit.hr", referrer: "https://bigblue.ferit.hr/html5client/join?sessionTo                                                                            ken=82fmlppras6rw9o4"

-- Errors found in /var/log/syslog --
Apr 24 09:25:21 bigblue systemd_start.sh[7115]: Exception while invoking method 'stopUserTyping' { Error: Match error: Expected string, got undefined Apr 24 12:11:50 bigblue bbb-webrtc-sfu[31299]: 2020-04-24T10:11:50.651Z - error: [VideoProcess] TODO => Uncaught exception Error:                                                                             
 Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379

 netstat -antp | grep 6379 | grep LISTEN
tcp        0      0 127.0.0.1:6379          0.0.0.0:*               LISTEN      2038/redis-server 1

The hostname in <link> .. </link> (    <link>)
    /var/bigbluebutton/published/presentation/59a49dc7b260146bd338b9f9f483051eb581750c-1587561146219/metadata.xml
do not match the hostname for bigbluebutton.web.serverURL (bigblue.ferit.hr)
  /usr/share/red5/webapps/bigbluebutton/WEB-INF/bigbluebutton.properties

Any suggestions ?

**Comment by crog3ar** [comment]
No one has similiar errors ?

**Comment by niketraut** [comment]
I am facing similar error after i re run the bbb script . initially it went fine. and all was working. but after i restarted the machine, i am getting this error

**Comment by ahasanaki** [comment]
same error:
Jun 25 10:17:49 w2 systemd_start.sh[26657]: Exception while invoking method 'setUserEffectiveConnectionType' { Error: Match error: Expected string, got undefined
Jun 25 10:19:39 w2 systemd_start.sh[1559]: Exception while invoking method 'setUserEffectiveConnectionType' { Error: Match error: Expected string, got undefined
Jun 25 10:19:43 w2 systemd_start.sh[1559]: Exception while invoking method 'setUserEffectiveConnectionType' { Error: Match error: Expected string, got undefined
Jun 25 10:19:48 w2 systemd_start.sh[1559]: Exception while invoking method 'setUserEffectiveConnectionType' { Error: Match error: Expected string, got undefined
Jun 25 10:19:53 w2 systemd_start.sh[1559]: Exception while invoking method 'setUserEffectiveConnectionType' { Error: Match error: Expected string, got undefined
Jun 25 10:19:59 w2 systemd_start.sh[1559]: Exception while invoking method 'setUserEffectiveConnectionType' { Error: Match error: Expected string, got undefined
Jun 25 10:20:03 w2 systemd_start.sh[1559]: Exception while invoking method 'setUserEffectiveConnectionType' { Error: Match error: Expected string, got undefined
Jun 25 10:20:08 w2 systemd_start.sh[1559]: Exception while invoking method 'setUserEffectiveConnectionType' { Error: Match error: Expected string, got undefined
Jun 25 10:20:13 w2 systemd_start.sh[1559]: Exception while invoking method 'setUserEffectiveConnectionType' { Error: Match error: Expected string, got undefined
Jun 25 10:20:18 w2 systemd_start.sh[1559]: Exception while invoking method 'setUserEffectiveConnectionType' { Error: Match error: Expected string, got undefined
Jun 25 10:20:23 w2 systemd_start.sh[1559]: Exception while invoking method 'setUserEffectiveConnectionType' { Error: Match error: Expected string, got undefined
Jun 25 10:20:28 w2 systemd_start.sh[1559]: Exception while invoking method 'setUserEffectiveConnectionType' { Error: Match error: Expected string, got undefined
Jun 25 10:20:33 w2 systemd_start.sh[1559]: Exception while invoking method 'setUserEffectiveConnectionType' { Error: Match error: Expected string, got undefined
Jun 25 10:20:38 w2 systemd_start.sh[1559]: Exception while invoking method 'setUserEffectiveConnectionType' { Error: Match error: Expected string, got undefined
Jun 25 10:20:43 w2 systemd_start.sh[1559]: Exception while invoking method 'setUserEffectiveConnectionType' { Error: Match error: Expected string, got undefined
Jun 25 10:20:48 w2 systemd_start.sh[1559]: Exception while invoking method 'setUserEffectiveConnectionType' { Error: Match error: Expected string, got undefined
Jun 25 10:20:53 w2 systemd_start.sh[1559]: Exception while invoking method 'setUserEffectiveConnectionType' { Error: Match error: Expected string, got undefined
Jun 25 10:20:58 w2 systemd_start.sh[1559]: Exception while invoking method 'setUserEffectiveConnectionType' { Error: Match error: Expected string, got undefined
Jun 25 10:21:03 w2 systemd_start.sh[1559]: Exception while invoking method 'setUserEffectiveConnectionType' { Error: Match error: Expected string, got undefined
Jun 25 10:21:08 w2 systemd_start.sh[1559]: Exception while invoking method 'setUserEffectiveConnectionType' { Error: Match error: Expected string, got undefined
Jun 25 10:21:13 w2 systemd_start.sh[1559]: Exception while invoking method 'setUserEffectiveConnectionType' { Error: Match error: Expected string, got undefined
Jun 25 10:21:18 w2 systemd_start.sh[1559]: Exception while invoking method 'setUserEffectiveConnectionType' { Error: Match error: Expected string, got undefined
Jun 25 10:21:25 w2 systemd_start.sh[1559]: Exception while invoking method 'setUserEffectiveConnectionType' { Error: Match error: Expected string, got undefined
Jun 25 10:21:28 w2 systemd_start.sh[1559]: Exception while invoking method 'setUserEffectiveConnectionType' { Error: Match error: Expected string, got undefined
Jun 25 10:22:03 w2 systemd_start.sh[1559]: Exception while invoking method 'stopUserTyping' { Error: Match error: Expected string, got undefined
Jun 25 10:22:21 w2 systemd_start.sh[1559]: Exception while invoking method 'stopUserTyping' { Error: Match error: Expected string, got undefined
Jun 25 10:22:22 w2 systemd_start.sh[1559]: Exception while invoking method 'stopUserTyping' { Error: Match error: Expected string, got undefined
Jun 25 10:23:51 w2 systemd_start.sh[1559]: Exception while invoking method 'stopUserTyping' { Error: Match error: Expected string, got undefined
Jun 25 10:24:18 w2 systemd_start.sh[1559]: Exception while invoking method 'stopUserTyping' { Error: Match error: Expected string, got undefined
Jun 25 10:25:38 w2 systemd_start.sh[1559]: Exception while invoking method 'stopUserTyping' { Error: Match error: Expected string, got undefined
Jun 25 10:26:23 w2 systemd_start.sh[1559]: Exception while invoking method 'stopUserTyping' { Error: Match error: Expected string, got undefined
Jun 25 10:26:37 w2 systemd_start.sh[1559]: Exception while invoking method 'stopUserTyping' { Error: Match error: Expected string, got undefined
Jun 25 10:28:07 w2 systemd_start.sh[1559]: Exception while invoking method 'stopUserTyping' { Error: Match error: Expected string, got undefined
Jun 25 10:28:46 w2 systemd_start.sh[1559]: Exception while invoking method 'stopUserTyping' { Error: Match error: Expected string, got undefined
Jun 25 10:33:41 w2 systemd_start.sh[1559]: Exception while invoking method 'stopUserTyping' { Error: Match error: Expected string, got undefined
Jun 25 10:34:29 w2 systemd_start.sh[1559]: Exception while invoking method 'stopUserTyping' { Error: Match error: Expected string, got undefined

**Comment by matiasilva** [comment]
Hi guys. Please post this in the setup mailing list https://groups.google.com/forum/#!forum/bigbluebutton-setup where it can be better handled. If it turns out to be a bug, we can open a new issue for that with more information.
