### ISSUE TITLE
Show poll results outside presentation frame

### ISSUE THREAD

**Issue by Sea444** [bigbluebutton/bigbluebutton#9246]
**Is your feature request related to a problem? Please describe.**
Whe you publish poll results they are shown at right bottom oft the presentation. When participants have minimized the presentation, they don't see the results.

**Describe the solution you'd like**
Poll results should be shown in a own toast, like the poll questions

**Describe alternatives you've considered**
Presentation opens automatically when poll results are published.

**Comment by runout-at** [comment]
The moderator has the poll results in the upper part of the Chat-Column. I think that would be a good solution for all participants. Even it would be great to have a list of all polls and a possibility to review them later and an option to export poll results (maybe i just didn't see that option).

**Comment by tarunb999** [comment]
Also reduce the Buttons size(A,B,C etc) that users are presented with for selecting an option. 
In a mobile device the buttons take up the whole screen and users are not able to view the question.

**Comment by gfeller** [comment]
A survey is also not possible during screenshare

**Comment by matiasilva** [comment]
In my case, it works but a presentation needs to be uploaded. The default one works fine.

**Comment by antobinary** [comment]
I believe this was addressed in https://github.com/bigbluebutton/bigbluebutton/pull/8525 - one of the enhancements to be released in 2.3.x.

Please comment here if there is anything missing in that work

**Comment by wolframd** [comment]
@antobinary 
I think it's not exactly related. 
Today I shared a video from youtube and conducted a poll to one of its aspects. The result did not show for my students since video sharing was active and results are only shown if the whiteboard is open. Therefore a real floating box showing the polling result independently would be really great!
(Mozilla Firefox 86.0.1, Win 7 Pro x64)

**Comment by antobinary** [comment]
@wolframd Were the poll results not posted in the public chat?
