### ISSUE TITLE
Not able to find any option to change the root of GreenLight

### ISSUE THREAD

**Issue by niketnaik** [bigbluebutton/bigbluebutton#9247]
I don't know if this is right place to post the issue but i don't find anyway to resolve my question.
I have installed BBB with **bbb-install.sh** with domain name and SSL and it is working fine on it's default root path i.e. example.com/b

1). i want to add sub directories/other websites in nginx server (www directory) so that when the BBB is not running my other website/apps can use the server. I tried to place the directory in var/www directory and tried to access via example.com/directory_name but it gives 404 error.  How to resolve that?
2). How can i change the default redirect from greenlight to my own directory i.e. when we open example.com it redirects to example.com/b, but i want to redirect to example.com/directory_name .

I tried following steps from here http://docs.bigbluebutton.org/greenlight/gl-install.html#4-configure-nginx-to-route-to-greenlight but can't find any `location = / {
  return 307 /b;
}`   block.

**Comment by dseral** [comment]
Take a look /etc/bigbluebutton/nginx/greenlight.nginx

**Comment by niketnaik** [comment]
@dseral i checked the file but not able to find my answer how to setup sub webistes and routes.

**Comment by matiasilva** [comment]
=> https://groups.google.com/forum/#!forum/bigbluebutton-greenlight
