### ISSUE TITLE
Working with BBB from mobile devices

### ISSUE THREAD

**Issue by ostasevych** [bigbluebutton/bigbluebutton#9252]
I am often working from mobile phone with different videoconferencing apps. I found that BBB doesn't have its mobile app, but uses a locally installed browser. What I discovered that when the screen is switched off by timeout or manually the conversation terminates. Is any possibility to avoid this by providing special settings to Chrome? Or even better, is any possibility to develop PWA or some other wrap up for BBB to adjust working in background?

**Comment by ostasevych** [comment]
As a workaround, I created manually an Android package (based on webView) for accessing greenlight, so I may start the meeting and hold it. How to create a package specifically for joining the meeting, eg, when there's the field where I may insert the string of meeting?

**Comment by arsenieciprian** [comment]
> As a workaround, I created manually an Android package (based on webView) for accessing greenlight, so I may start the meeting and hold it. How to create a package specifically for joining the meeting, eg, when there's the field where I may insert the string of meeting?

Can u give us the source for android

**Comment by amkyp** [comment]
trying to access the session via Firefox 68.8.0 in Android 8.0 doesn't respond but on the same phone I can open the BBB session with Chrome 81.0.4044.138.
Any Idea why there is a problem working with firefox?

**Comment by ostasevych** [comment]
> > As a workaround, I created manually an Android package (based on webView) for accessing greenlight, so I may start the meeting and hold it. How to create a package specifically for joining the meeting, eg, when there's the field where I may insert the string of meeting?
> 
> Can u give us the source for android
There's not possible to provide the source, only apk file. Yesterday, I found that one function is not properly: when you break out into roons, the html5 initiate new environment, and my smartphone says, that there are issues with the access rights to  multimedia devices. Bump. Only text.
