### ISSUE TITLE
401 after 60 seconds caused by "Too many open files" in bbb-apps-akka

### ISSUE THREAD

**Issue by defnull** [bigbluebutton/bigbluebutton#9253]
**Describe the bug**
The `bbb-apps-akka` process runns into `java.io.IOException: Too many open files` and stops working. The user sees this as a 401 error after 60 seconds of waiting, when joining a meeting with the html5client. An `lsof -p <pid-of-bbb-apps-akka>` shows a lot of `a_inode [eventpoll]` and `FIDO pipe` entries. Increasing the open file limit solves the issue (but only for new meetings). For a more or less idling BBB instance, the actual open files hover around 1286 (which is more than 1024 unfortunately). The server has a lot of CPU cores (`32*2*2=128`), so perhaps some thread pool goes crazy on machines with high core count?

**Expected behavior**
`bbb-apps-akka` not crashing.

**Actual behavior**
`bbb-apps-akka` prints `java.io.IOException: Too many open files` to its log, then silence. Joining a room with the html5client will show three dots for 60 seconds, then a 401 error.

**Comment by basisbit** [comment]
there exists a [workaround](https://github.com/bigbluebutton/bbb-install/blob/abc3a32f9c76657cdf2a29a54531baf12d988856/bbb-install.sh#L628) in the `bbb-install.sh` script for this problem for the `bbb-web.service`. Does that already resolve the problem you mentioned?
