### ISSUE TITLE
Can't activate microphone without rejoining when restricting user rights

### ISSUE THREAD

**Issue by BartMitTyp** [bigbluebutton/bigbluebutton#9260]
**Describe the bug**
When a mod restricts users to activate their microphone, but unlocks someone for this, the user needs to deactivate sound, rejoin the call and select their microphone, because this option is missing when joining a room which has restricted user rights.

**To Reproduce**
1. Create a room, restrict users to enable their microphone
2. Join the room with a new user and try to find "join with microphone"

**Expected behavior**
On every join, give the users the option to join with a microphone.

**Actual behavior**
When joining a restricted room, only the option to join with sound appears.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox 75
 - Version 2.2.5

**Comment by Jossef-767** [comment]
a "listen-only" student must Somehow realize that he  should double-click the "connect to the voice server" button To connect his microphone.
its not very intuitive.

For that "listening only" student ,  It might be a good idea to automatically pop up the microphone connection window on the screen every time a teacher Specificly unlocks him.
