### ISSUE TITLE
How can I block direct access to records playback links?

### ISSUE THREAD

**Issue by MrCapitalist** [bigbluebutton/bigbluebutton#9261]
Hi
As you know, everyone can share the playback link of the meeting with another person
I made access limitation for users who haven't been authenticated by Wordpress. But I want to block direct access of playback links.
 
For example, to handle it, we can use htaccess and check page HTML Referer Header! If it has been comes from our sites, it is allow, otherwise it should be block!

Can anyone help me?

**Comment by ichdasich** [comment]
The nginx configs here might help you in finding out how to add custom .htacces: https://github.com/ichdasich/bbb-rec-perm

**Comment by MrCapitalist** [comment]
Excuse me, I checked that link but I didn't catch your mean. How can I use that?! I don't use Greenlight

**Comment by ichdasich** [comment]
See the nginx configuration files in https://github.com/ichdasich/bbb-rec-perm/tree/master/nginx-config/etc/bigbluebutton/nginx where the auth-statement is added. These are the ones where you want to, e.g., apply a custom htaccess or other access restriction.

**Comment by basisbit** [comment]
Thank you @ichdasich for answering this support question!
