### ISSUE TITLE
Change symbol for toggle participant list to "<<" respectively ">>"

### ISSUE THREAD

**Issue by Sea444** [bigbluebutton/bigbluebutton#9263]
**Is your feature request related to a problem? Please describe.**
New BBB users do not know how to open and close the area on the left side (chat, notes, participant list). It is for them not comprehensible why this should be done via the person symbol. Usually, the person icon hides the own profile.

**Describe the solution you'd like**
Change the person symbol against "<<" (=close) and ">>" (open)

**Describe alternatives you've considered**
New symbol with chat symbol and person symbol. But I think "<<" and ">>" would be easier to understand

**Additional context**
![grafik](https://user-images.githubusercontent.com/63501663/80290854-b8708b80-8748-11ea-9943-0503cd60ef0d.png)

**Comment by ffdixon** [comment]
Good suggestion -- it's a very small change in the icon.  We'll see if we can get it into an upcoming iteration of 2.2

**Comment by tylercopeland** [comment]
I also agree this is great feedback. I've put together a simple mockup to illustrate this idea. 

![Screen Shot 2020-04-27 at 2 31 59 PM](https://user-images.githubusercontent.com/1273169/80407707-0940cb00-8894-11ea-948b-1e17ea3c6d65.png)

![Screen Shot 2020-04-27 at 2 33 52 PM](https://user-images.githubusercontent.com/1273169/80407766-22e21280-8894-11ea-89f5-a64bcd69a11a.png)

**Comment by Sea444** [comment]
Well, for me a simple"<<" respective">>" would be enough:

![grafik](https://user-images.githubusercontent.com/63501663/80416491-82601280-88d4-11ea-9a7e-8c34b8906bf0.png)

**Comment by weeman1337** [comment]
Hi, maybe the solution for this button could be different:  
Actually it says "toggle user list" but in fact this is now a full featured side bar / side menu.

I've tested with some users, the best thing working is a menu icon because that is what they expect.

![image](https://user-images.githubusercontent.com/6216686/80461676-eebf2e00-8935-11ea-99b1-e2cca53638b8.png)

The solution I would prefer is:
* Changing to a burger menu icon
* Changing the tooltip to "toggle sidebar"

If you want code is ready for a PR including the new glyph in the icon font ;)

**Comment by iSamof** [comment]
I think @weeman1337 has a good suggestion.
Although the burger menu is generally used for site and app menus, it still seems to be a better representation of the left sidebar.

**Comment by Sea444** [comment]
Well, I see the problem, that we will have two menus symbols: one on the top left corner (burger menu: 3 lignes) and one on the top right corner (minimized burger menu: 3 dots). I think that will be irritating for users.

**Comment by weeman1337** [comment]
> Well, I see the problem, that we will have two menus symbols

Yes. But the burger icons opens a menu like sidebar and the three dots a drop down menu.

**Comment by Sea444** [comment]
solved by 2.2.11
