### ISSUE TITLE
Show BBB-Version in HTML5-Client

### ISSUE THREAD

**Issue by Sea444** [bigbluebutton/bigbluebutton#9264]
**Describe the bug**
In the BBB-HTML5 client the BBB version should be displayed. But instead it shows only an old copyright year and a unknown client version:
`Copyright: ©2019 BigBlueButton Inc.`
`Clientversion: 882`

**To Reproduce**
1. Klick on men in top right corner
2. Click on 'version info'

**Expected behavior**
`Copyright: ©2020 BigBlueButton Inc.`
`Serverversion 2.2.6, Clientversion: 882`

**Actual behavior**
`Copyright: ©2019 BigBlueButton Inc.`
`Clientversion: 882`

**Screenshots**
![grafik](https://user-images.githubusercontent.com/63501663/80291111-0ab2ac00-874b-11ea-8829-fc9d32b94c70.png)

**Comment by toehold** [comment]
I don't get the version info as an Admin user. I only get:

Profile
Organisation
-----
? Need help?
! Report Issue
--> Sign out

**Comment by Sea444** [comment]
@toehold : You  talk about Greenlight frontend, I talk abour Bigbluebutton-HTML5-Client

**Comment by toehold** [comment]
> @toehold : You talk about Greenlight frontend, I talk about Bigbluebutton-HTML5-Client

For Greenlight I get on the main bbb site at the bottom this: Powered by Greenlight. 2.5.4
Now I found out where you found the Info: You join a Session/Room and then I also get
this: (here it is called: **About** and not version info

About
Copyright: ©2019 BigBlueButton Inc.
Client build: 882

I think the Version Info should appear under the Menu in the top right corner, without needing to start a session.

**Comment by Sea444** [comment]
comnnected to #9212

**Comment by matiasilva** [comment]
See the above issues for more information. Closing for now but feel free to follow up on our dev group: https://groups.google.com/forum/#!forum/bigbluebutton-dev.
