### ISSUE TITLE
Add ability to have device selector before echo test

### ISSUE THREAD

**Issue by invokablegmbh** [bigbluebutton/bigbluebutton#9266]
**Is your feature request related to a problem? Please describe.**
I am happy with the echo test, as such. However, today, most of the systems out there have multiple microphones and speakers. Think of a notebook with a headset attached. You have at least two speakers and two mics. It would be better, to not rely on the hope that there "might" be the right microphone + spreaker selcted on pageload.

**Describe the solution you'd like**
Add an option, so that users go to device selctor automatically at first and then have them run through the echo test. In 80% of the time when using BigBlueButton this would save me ca. 10-20 seconds during the connection process, because echo test lasts for some time and this is frustrating.

**Describe alternatives you've considered**
I do not know any alternatives.

**Additional context**
Nothing special here.

**Comment by prlanzarin** [comment]
Addressed by [#14736](https://github.com/bigbluebutton/bigbluebutton/pull/14736) (and follow-ups) in 2.6.
