### ISSUE TITLE
new 2.2.6 version - using jsp pages and after  #9188

### ISSUE THREAD

**Issue by Jossef-767** [bigbluebutton/bigbluebutton#9270]
Hi Fred
there are many of us in the community that use customized jsp pages.
 #9188 (Prevent removed users from rejoining ) created a critical problem for 
 using api to Logan to meetings,
it is opening new meeting for every user.

**Comment by ffdixon** [comment]
Are you passing in a `userID` for each user?

**Comment by Jossef-767** [comment]
I simply used the https://test.bigbluebutton.org/demo/demoHTML5.jsp 
and tryed to login from difrent pc's
i think there is only username, no userid

**Comment by ffdixon** [comment]
Ahh -- it's OK.  

We've modified the API examples on https://test.bigbluebutton.org/ to always put you in a random room.  

This way, it's easy to point users to test and have them check their webcam and microphone to see if it works with that server (and compare the results to their own server).

**Comment by Jossef-767** [comment]
😅 Thanks Fred
I was worried for a moment.
Sorry for bothering, in these busy days
