### ISSUE TITLE
Poll published result for RTL Languages shows wrong order on chrome based browser

### ISSUE THREAD

**Issue by emadbagheri96** [bigbluebutton/bigbluebutton#9273]
hi
**Describe the bug**
when you create a custom poll with persian options and then publish the result, it is showed correctly on the firefox but on the chrome based browsers (tested opera and the new ms edge) the order of options are wrong

**Screenshots**
this is in the firefox which is correct: (actually it shows and extra character at the end of each answers like the first one in our language. it should be `بله `not `بلهـ ` but we don't mind it for now)
![f](https://user-images.githubusercontent.com/21096918/80318794-d100a480-8821-11ea-80bc-44213b5ed099.JPG)

and this is in the opera and edge which strangely the last character of the third option remains there but other characters are swapped for first and third options:
![o](https://user-images.githubusercontent.com/21096918/80318842-22a92f00-8822-11ea-9851-c4875d34c73e.JPG)

**BBB client version** (tested on both)
874
882

**Firefox:**
 - Version 75.0 (64-bit)

**Opera:**
 - Browser identification
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36 OPR/67.0.3575.137

**Edge:**
 - Version 81.0.416.64 (Official build) (64-bit)

**Comment by ohameiri** [comment]
Can confirm this bug. Very easy to reproduce..
Would be happy if this will be fixed, causes a lot of troubles for us..

thanks !

**Comment by ohameiri** [comment]
This only happens in chrome.
in firefox it works great

**Comment by ha3ant** [comment]
Is there any news about this bug? :(
It shows the wrong result when clients use chrome. The firefox is ok.
