### ISSUE TITLE
external video player not sync

### ISSUE THREAD

**Issue by mohammad2319** [bigbluebutton/bigbluebutton#9274]
external video player not sync for client

bigbluebutton 2.2.6

**Comment by ihsankarakas** [comment]
This problem should be about the presenter's computer time settings.

**Comment by mohammad2319** [comment]
tanks
Computer time settings is ok
on client show message:
play the video to enable media synchronizaition

**Comment by pawan-fls** [comment]
Shouldn't we use server time instead of the System time?

**Comment by matiasilva** [comment]
I'm tempted to close this issue, it's very lacking in purpose at the moment.

**Comment by jamesexperts** [comment]
Yes, i am facing the issue

**Comment by matiasilva** [comment]
Are you running the latest version of BigBlueButton? Can reproduce it on test.bigbluebutton.org?

**Comment by sam-fls** [comment]
Yes I am also facing the same issue

**Comment by jamesexperts** [comment]
@matiasilva 
I am using
BigBlueButton Configuration Utility - Version 2.2.17

**Comment by jamesexperts** [comment]
@matiasilva 
test.bigbluebutton.org
every user goes to the individual test room how we can test it with multiple users in test envirnment

**Comment by matiasilva** [comment]
I see. Can you try demo.bigbluebutton.org instead? Just to be sure, the issue you guys are having is with the external video player not being synced across multiple users? What video provider are you using? YouTube? Describe your issue in more details please.

**Comment by jamesexperts** [comment]
@matiasilva 
What is the version on demo.bigbluebutton.org

**Comment by matiasilva** [comment]
@jamesexperts  Can you provide an example case where you run into the problem? The version on demo is the latest.

**Comment by jamesexperts** [comment]
@matiasilva Yes i think issue is in 2.2.10, in latest 2.2.19 it's resolved
Thanks

**Comment by matiasilva** [comment]
Thanks, then. Closing for now.
