### ISSUE TITLE
can I auto join a microhone when joining a meeting

### ISSUE THREAD

**Issue by wiliarko** [bigbluebutton/bigbluebutton#9275]
can I auto join a microhone when joining a meeting with api ?

**Comment by frank-miller9** [comment]
Not sure, if I understood your question correctly but in ```/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml``` you can set:
```
    autoJoin: true
    listenOnlyMode: false
    forceListenOnly: false
    skipCheck: true
```
To skip echo chat and start directly with the chat. For the camera settings some lines below you have:
```
    autoShareWebcam: true
    skipVideoPreview: true
```

**Comment by wiliarko** [comment]
thnaks, its work
