### ISSUE TITLE
Add/Remove new slide at whiteboard

### ISSUE THREAD

**Issue by masums** [bigbluebutton/bigbluebutton#9276]
Whenever a teacher uploaded a class presentation then he needs to elaborate on the topic to his students. Sometimes it requires an extra slide for writing/drawing examples immediately after that slide. It might not be predictable on slide design time. If the teacher can add extra slides at presentation time then students will be able to see the slides after class ended by downloading the presentation file with teacher's extra writing and slides. 
 
Provide a button to adding a new slide after the current slide. And also a remove button on extra slides. So that any time teacher can remove extra slides if required. 

It will be better if the teacher can add new slides without uploading any presentation file. Then he will be able to start a class immediately on topics with any pre-prepared presentation file. Also after writing three more slides if the teacher feels that he missed something at first slide then it will be more convenient to add a new slide immediately after the first slide. 

At the end of a class, the presentation slides with teacher's writing and drawing are very important to students. So if there have any button for download the complete presentation slides as pdf file then that will be very helpful for students. Though it is subject to giving permission.

**Comment by vitovt** [comment]
Useful feature. Vote up for it.

**Comment by Kconseil** [comment]
Teachers using BBB suggest to have ability to reduce size of the document but not the size the area of whiteboard to be able to write next to the content. Close to what you suggest but even better i think.

**Comment by nibah** [comment]
I would like to take this up and work on this feature in the next 6 months.

**Comment by nibah** [comment]
Unfortunately my plans had to change, and I will not be able to work on this after all.

**Comment by a3nm** [comment]
Hi, do you think it would make sense to reopen this issue? The issue was closed as inactive back in 2021, but as far as I can tell, adding new blank slides is still not proposed in recent versions (and would be quite useful to me at least).
