### ISSUE TITLE
About HTML5 Client Layout

### ISSUE THREAD

**Issue by masums** [bigbluebutton/bigbluebutton#9277]
Newly designed HTML5 layout is smart enough. But it did not utilize all spaces by default. Especially spaces are important for small screens. Most important area is whiteboard aria at teaching time and camera views at meeting time. It allows us to rearrange but every time rearrangement is problematic and time-consuming. So there should have at least two layout modes with an **easily switchable** button. 

**Suggestion for teaching mode:**
There will have two columns, first column will have full whiteboard with expanded drawing toolbar at top, and second column will be collapsable. 
At the top of 2nd column can take place all button for mic/cam/audio/screen share
Below that can take place active speaker's webcam view. Also a button for stop receiving video
Below that 
Below that cam view at tabbed view can contain, User list/Public chat/Private chat/ Shared note

**Suggestion for meeting mode:**
Meeting mode will have also two columns.
First column will take place all active webcams
Collapsable 2nd column will have user's list/public chat/private chat/shared note

These are very few points of the design suggestion. There have many other controls for appropriate positioning. I think your UX teams are able to do those things very well. Still, I can discuss those if it requires.

**Comment by iSamof** [comment]
Pls take a look at this and especially the one issue that it links to: https://github.com/bigbluebutton/bigbluebutton/issues/8922

**Comment by marcarneg** [comment]
As well as #9256 

General question: Should UX/UI Design-suggestions be collected in a single issue, or should every suggestion be a single issue? Since I accompany some "first-time-BBB-teachers", I can gather some impressions, especially from non-IT-folks.
