### ISSUE TITLE
iPad stuck on uploading a presentation

### ISSUE THREAD

**Issue by SebastianZiegler** [bigbluebutton/bigbluebutton#9278]
Some of our teachers uses iPads, in some cases when I upload a presentation, I can press the upload button then the convertings starts but nothing happend anymore. I cannot go back to the conference and the converting doesn't seems to finish. 
If I do a reload on the page, and go back to the conference. The presentation has been succesfully uploaded but is not active.
When I tried to upload the same file from an PC everything works as expected.

iPad with latest iOS
BBB version 2.2.5
Uploaded file: pdf with two scanned pages (file size under 1 MB)

Tested on iPhone too without problems

greetings
Sebastian

**Comment by chrispiel** [comment]
Hi,

I can confirm this behaviour. It appears to work fine on MacOS with Safari. Firefox and Chromium don't work if you are the only user. 

If other users already did something in the room (e.g. chatting, sharing webcam/presentations) everything works out fine regardless of the browser.

Bluescreen disapppears by itself once another mod does an upload.

Ubuntu Linux 16.04 and Windows 8.1
Firefox and Chromium (both OS)
Uploaded file: odp (140kb) or pdf (1 or 2 pages, max 100kb)

Greetings
Chris
