### ISSUE TITLE
How to upgrade to latest patch version

### ISSUE THREAD

**Issue by cdir** [bigbluebutton/bigbluebutton#9280]
I do not find how to correctly upgrade BBB to the latest patch release.

I have read http://docs.bigbluebutton.org/2.2/install.html but it seems like the packages at https://ubuntu.bigbluebutton.org/xenial-22 are still version 2.2.0.

At https://github.com/bigbluebutton/bigbluebutton/releases I found some very interesting patches which I like to install but I do not find any information how.

The latest release notes at http://docs.bigbluebutton.org/support/release-notes.html#Release_Notes_ are still 2.2.0 RC. I think it is absolutely ok to only have release notes in GitHub but it would be helpful to have a link to https://github.com/bigbluebutton/bigbluebutton/releases .

**Comment by wolbernd** [comment]
@cdir For Minor updates you should be able to update using `apt upgrade`. The current BBB version can be found in the file `/etc/bigbluebutton/bigbluebutton-release` on your BBB server.

**Comment by cdir** [comment]
Ok, I see. the version pattern of the packackes simply does not match the version pattern in github. The package version is 2.2.0-5, but the installed version is 2.2.6. Would be nice to document this anywhere to avoid misunderstandings :)

**Comment by odenbach** [comment]
I have exactly the same issue. Someone pointed out that there is a security issue in BBB versions < 2.2.5, and I have no idea which version we are running as package versions seem unrelated to BBB versions.

**Comment by Sea444** [comment]
see #9107

**Comment by matiasilva** [comment]
You can verify the minor release that you are running by following the instructions above or running `sudo bbb-conf --restart` and noting the release shown. Closed as this has been solved.

**Comment by needleshaped** [comment]
I second the thought, that explicitly documenting update process is a must.

After update, I encountered #8824 problem, which was solved by `bbb-conf --setip <hostname>`. That is becoming part of my update process. This is my attempt to describe:

## Update BBB

- https://github.com/bigbluebutton/bigbluebutton/releases
- https://docs.bigbluebutton.org/2.2/install.html#upgrading

```sh
# check version
bbb-conf --check
bbb-conf --version
cat /etc/bigbluebutton/bigbluebutton-release

# check installed packages
ls /etc/apt/sources.list.d/
apt list --installed | grep -e bbb -e bigblue

# update
apt update
apt list --upgradable
apt upgrade
bbb-conf --setip <hostname> # otherwise "Connecting to echo test ..." is neverending

# check status
bbb-conf --status
```

## Update Greenlight

- https://github.com/bigbluebutton/greenlight/releases
- https://hub.docker.com/r/bigbluebutton/greenlight

```sh
cd ~/greenlight
# update
docker-compose pull
docker-compose down
docker-compose up -d
# check
docker-compose logs -f
# cleanup
docker system prune -f
```
