### ISSUE TITLE
recording not available

### ISSUE THREAD

**Issue by crog3ar** [bigbluebutton/bigbluebutton#9281]
![Untitled](https://user-images.githubusercontent.com/45625086/80356530-df7aaa80-8879-11ea-8737-e091ad6832e9.jpg)

Is it possible to publish rebuild this meeting. I tried but files doesn't exist ?

bbb-record --rebuild 10477aa16ce80f3c8c1f7c070690663a36be9f17-1587709861834
Marking for rebuild 10477aa16ce80f3c8c1f7c070690663a36be9f17-1587709861834
Raw files for 10477aa16ce80f3c8c1f7c070690663a36be9f17-1587709861834 do not exist, can't rebuild

 bbb-record --republish
Marking for republish: 04d3e52441be5749c84ac1a0ae230b033793e22d-1587897248486
Marking for republish 04d3e52441be5749c84ac1a0ae230b033793e22d-1587897248486
Processed files for 04d3e52441be5749c84ac1a0ae230b033793e22d-1587897248486 do not exist, can't republish
Try rebuilding the recording instead.

bbb-rap-worker.log
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated

bbb-record --debug
doesn't show anything ?

**Comment by dmunozvenegas** [comment]
estoy teniendo los mismos problemas, el dia de ayer no se publicaron las grabaciones, hice un rebuild y ya no tengo publicaciones.

**Comment by duquedealba** [comment]
Same problem with recording, someone could fix it?

**Comment by pedrobmarin** [comment]
More about ConfigMap warning at https://github.com/bigbluebutton/bigbluebutton/issues/8455
