### ISSUE TITLE
Exception when doing a poll with presentation area closed

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#9287]
**Describe the bug**
Exception when doing a poll with presentation area closed

**To Reproduce**
1. To reproduce the error just start a survey with the presentation closed, 
2. publish the results,  and 
3. reopen the presentation. 

**Screenshots**
![image](https://user-images.githubusercontent.com/290351/80392661-709f5080-887d-11ea-9e2c-7fc9b867ca0e.png)

**Comment by antobinary** [comment]
Related to https://github.com/bigbluebutton/bigbluebutton/pull/8952

**Comment by palimm** [comment]
I am able to reproduce this error on 2.2.9. Is anybody else affected?

**Comment by froettger** [comment]
Me too. On publishing polling results exception occurs.
Competing issue with backported fix #9289 ?
