### ISSUE TITLE
Presentation upload in sidebar

### ISSUE THREAD

**Issue by dexteritas** [bigbluebutton/bigbluebutton#9288]
**Is your feature request related to a problem? Please describe.**
Currently, a separate view for uploading is displayed and thus "hides" the actual conference (participants, chat, videos, slides) during the entire upload and conversion. This time could otherwise be used to answer questions from the chat or to continue the current presentation.

**Describe the solution you'd like**
It would be good to move the selection of PDFs to a separate area within the conference view, just as it is done when creating a poll (see mockup below). The file should then simply be uploaded in the background, even if the sidebar is minimized.

**Describe alternatives you've considered**
Several presentations can be uploaded at the beginning as long as it is already known what exactly is to be shown and there is enough time.

**Additional context**
<img width="575" alt="bbb_presentation_upload" src="https://user-images.githubusercontent.com/19909936/80392443-6f871700-88af-11ea-9745-ff87d37afb4d.png">

**Comment by dexteritas** [comment]
I just found out, the Presentation Upload View can be closed and the uploads goes on in background! So a part of the desired feature is already available. Unfortunately it is not so intuitively recognizable. I had expected that the upload would abort when I clicked on "close". Maybe a button "minimize" would be good instead. But still I think it would be nice to see the progress bar in parallel.

**Comment by matiasilva** [comment]
Merging with #8464.
