### ISSUE TITLE
Availability of deb-packages with previous versions

### ISSUE THREAD

**Issue by iljalukin** [bigbluebutton/bigbluebutton#9290]
I've tried to upgrade my instances to bbb 2.2.6 yesterday via apt-get upgrade and had some issues with the echo test not working properly after that (green and red buttons not appeared). I wanted to roll back and investigate the problem later, but I couldn't due to the fact, that packages of previous versions are not available neither in /var/cache/apt on the filesystem, nor in the package repository. 
Why? 
Luckily I had another test instance running and had to replace folders of freeswitch, akka and client to get it running again, but it's very annoying and not in sense of production environment not to have a possibility to go back to previous state. At least there should be a possibility to build the deb packages on my own, if the package repository owner tends to delete previous versions.
Could you share those scripts?

Thank you in advance for your work

**Comment by basisbit** [comment]
regarding the sources: Duplicate of #8978

**Comment by iljalukin** [comment]
@basisbit thank you for your answer. With a backup I would restore the same previous versions of files with critical issues, that you mentioned, but with an enormous effort. With proper deb-packages it would be a one-liner to restore the previous state with apt-get.

**Comment by basisbit** [comment]
I agree on that. Unfortunately, we'll have to wait a couple of months for build/package-system improvements, as there are currently other issues which the core team is working on, and sadly the build system is not open sourced, thus people who are not part of the core-team can't work on that.
