### ISSUE TITLE
Users Limit

### ISSUE THREAD

**Issue by armornet** [bigbluebutton/bigbluebutton#9291]
Hello, If i conduct a live webinar with only the presenter / moderator to share webcam, audio and presentation to 500 participants will it work. Please advise me..

**Comment by basisbit** [comment]
500 people in one BigBlueButton session should not be done. But it can be done maybe (with different rates of success and amounts of angry users)
Bare metal hardware with lots of current CPU cores that are especially fast for single-threaded load (nodejs / meteor event handling is mostly single-threaded), and disabling the features Webcam sharing, whiteboard, participant list, chat and room recording.

Anyways, bbb is not designed for so many participants in one room. You might want to consider using a video streaming solution instead.

**Comment by tarunb999** [comment]
Just curious @basisbit  ...even if all the viewers are muted and not sharing their webcams.. will it even then be difficult for a standard conf server(..i.e 4 cores, 8 GB RAM etc, 500 MBPS ) to broadcast to 500 or even 300??

**Comment by basisbit** [comment]
yes, it will still be difficult, because the problem here is that all the events for users joining/leaving/heartbeat, participant list, whiteboard, chat and recording is handled by the mostly single-threaded nodejs/meteor server. As far as I know there are plans for improving this, but it is not done so easy because all these events change the shared state of that one single session/room.

For the [hardware which you mentioned](https://docs.bigbluebutton.org/2.2/install.html#minimum-server-requirements), the [docs.bigbluebutton.org](https://docs.bigbluebutton.org/support/faq.html#how-many-simultaneous-users-can-bigbluebutton-support) mentions 150 participants as suggestion.

**Comment by iSamof** [comment]
Just FYI - We have been testing a bare metal 16 core, 32 GB RAM, SSD, 1GBPS port with the standard BBB 2.2.5 and no optimisation (no reduction of webcam resolution ... therefore webcams run in the default resolution ):

As few as 30 users running just 5 or 6 webcams can load the CPU to as much as 30%

As few as 30 users and 10 or 12 webcams have produced CPU loads peaks as high as 60% -70%

In all cases recording was off. We did not monitor whether they were screen sharing at any time or not. 

We are building more monitoring and analysis and collecting more data for capacity planning and resource allocation.

**Comment by basisbit** [comment]
@iSamof are you sure that system is not a 8 core CPU plus Hyper Threading? also, if you are looking at top/htop then those numbers would be 30%/60-70% of a single core. Then 100% usage of all cores would be 16 cores*100% = 1600%.

**Comment by iSamof** [comment]
@basisbit - we have multiple bare metal servers mostly 16 cores and one 8 core. But good catch sir, the data was in fact from the one 8-core server with this spec:

Intel Core i7 6700K, 64 GB DDR4, 512 GB SSD, 2 TB HD 

As for the CPU, the data is from Netdata and the value of 30% is from the CPU summary graph for all CPUs (unless I am misreading it) and I just checked ... the individual CPU's are all showing about 30% usage with few webcams: 

![image](https://user-images.githubusercontent.com/40075900/80496306-4d51cf80-8969-11ea-95e3-ece19dae0d59.png)

**Comment by armornet** [comment]
Now this is what i found on the below url regarding 100 users and only one person share webcam if users above 100 or for large host..
https://support.blindsidenetworks.com/hc/en-us/articles/360042272991-How-many-users-can-I-have-in-a-BigBlueButton-session-

I am a bit confused now about different documentation at different pages and different users..

Please advise.. bcoz my need is to allow only one person share their webcam and disable everything only for participants to listen... users upto 250.. can i do it..

**Comment by dseral** [comment]
Hi armonet,
My personal experiment is with very fine tune server even 16 core 32 GB ram.. Just audio now webcam can work up to 500 (total)  users. However public chat and other functions desk share start struggle after 450 user. Even some meetings over 150 users..  
CPU's not all of them utilize but as basisbit mention nodejs/meteor server utilize one processor 100%.  So in this case voice still working (freeswitch utilize 4-5 processor well) but systems start to not responsive. 
So simply if you want to make very big event don't try to put them in one meeting room!
Devrim

**Comment by GhaziTriki** [comment]
Hello,

Have been discussed later in #9421. This is not a bug or a feature request. We would love to see those questions and answers shared with the community in the forums https://groups.google.com/forum/#!forum/bigbluebutton-dev

Thank you

**Comment by ha3ant** [comment]
> Hi @armornet,
> My personal experiment is with very fine tune server even 16 core 32 GB ram.. Just audio not webcam can work up to 500 (total) users. However public chat and other functions desk share start struggle after 450 user. Even some meetings over 150 users..
> Not all CPU's utilized but as @basisbit mention nodejs/meteor server utilize one processor 100%. So in this case voice still working (freeswitch utilize 4-5 processor well) but systems start to not responsive.
> So simply if you want to make very big event don't try to put them in one meeting room!
> Devrim

Dear dseral,
I have 16 core CPU Intel 2650 and 41GB Ram, when I have 10 meetings with 25 people on each (total concurrent users 250) the users get the error and waiting much time to enter rooms, the current users just kicked out of meetings, and audio gets reduce quality and like robots!
I checked Nginx log files and see this error:
connect() failed (111: Connection refused) while connecting to upstream, client:

Is there any extra config for Nginx or Esxi virtualization or other things?!

**Comment by matiasilva** [comment]
Please don't revive this issue. There are plenty of other discussion threads on this topic.
