### ISSUE TITLE
Users Limit to join session

### ISSUE THREAD

**Issue by anilnetmente** [bigbluebutton/bigbluebutton#9294]
I need to find how many users can join a meeting in BigBlueButton and on green light also.

**Comment by crog3ar** [comment]
https://docs.bigbluebutton.org/support/faq.html#configuration

Looks like that only depends on your hardware & network

**Comment by anilnetmente** [comment]
thank you  @crog3ar

**Comment by basisbit** [comment]
next time please use the search to check if others already asked the same question. There exist many many issues and forum posts which answer this exact question already. thanks.

**Comment by anilnetmente** [comment]
Okay @basisbit
