### ISSUE TITLE
v2.2.6 - nginx error.log: webcams.mp4 failed (but have a .webm in the folder)

### ISSUE THREAD

**Issue by lakano** [bigbluebutton/bigbluebutton#9296]
**Describe the bug**
We've found this error in bbb-conf --debug : 
`2020/04/28 11:56:18 [error] 1598#1598: *4988 open() "/var/bigbluebutton/published/presentation/3fc2c587057ca98bc767aaf26cf85c57c546eeee-1587554720040/video/webcams.mp4" failed (2: No such file or directory), client: 78.213.75.219, server: XXX, request: "HEAD /presentation/3fc2c587057ca98bc767aaf26cf85c57c546eeee-1587554720040/video/webcams.mp4 HTTP/1.1", host: "XXX", referrer: "https://XXX/playback/presentation/2.0/playback.html?meetingId=3fc2c587057ca98bc767aaf26cf85c57c546eeee-1587554720040"
`

**To Reproduce**
I really don't known, the solution is used per multiple users, I don't known in which conditions this happen. But I suppose it's about recording because of the name of the file « webcams.mp4 ».

**Expected behavior**
No error message because the file requested is correct ( .webm rather than .mp4 may be ?)

**Actual behavior**
Nginx error because the file webcams.mp4 doesn't exists 

**Screenshots**
None

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, Mac]
 - Browser [e.g. Chrome, Safari]
No idea, but we've requested to our users to uses Google Chrome. Some have Windows, some other MacOS, and Linux.

**Smartphone (please complete the following information):**
 - Browser [e.g. stock browser, Safari]

**Additional context**
May be you've changed webcams.mp4 to webcams.webm and so the Greenlight ( last version 2.5.4 ) haven't yet updated theses changes, or may be we should have theses 2 files on the harddrive, in this case there is a crash/bug somewhere I supposed.
Thanks for your help :)

**Comment by toto4ds** [comment]
https://docs.bigbluebutton.org/2.2/customize.html#enable-playback-of-recordings-on-ios
