### ISSUE TITLE
Lock Viewers settings 'See other viewers in the Users list' lock enforce lock on 'See other viewers webcams'

### ISSUE THREAD

**Issue by thifranc** [bigbluebutton/bigbluebutton#9297]
**Describe the bug**
During room session, as moderator, I would like to disable viewers from seeing other viewers in the users list. When this lock is enabled, viewers cannot see other viewers webcams anymore, as if the lock on  'see other viewers webcams' is enabled

**To Reproduce**
1. Start a room session
2. Get 3 people in there, one moderator, two simple viewers (lets say alice and bob)
3. Alice starts to share her webcam, everything is okay as nothing is locked so far, so Bob sees Alice webcam stream
4. Moderator toggle on the lock 'See other viewers in the Users list', so Alice and Bob cannot see one another in the Users list, that is expecte behviour, but Bob cannot see Alice webcam stream anymore

**Expected behavior**
On step 4 of the reproduce process, Bob should still be able to see Alice webcam stream to my opinion

**Actual behavior**
On step 4 of the reproduce process, Bob cannot see Alice webcam stream

**Screenshots**

**BBB version (optional):**
BigBlueButton continually evolves. Providing the version/build helps us to pinpoint when an issue was introduced.
Example:
$ sudo bbb-conf --check | grep BigBlueButton
BigBlueButton Server 2.2.5 (1848)

**Desktop (please complete the following information):**
 - OS: Debian 9 Stretch
 - Browser : firefox-esr V68
 - Browser2 : chromium V79

**Additional context**
I tried to track down the bug until getting onto file 
`bigbluebutton-html5/imports/api/meetings/server/methods/toggleLockSettings.js`
But I don't really get where the code goes next, I'd be glad to learn more about and make a PR

Thanks for this amazing tool and great designed software !

**Comment by antobinary** [comment]
Hi @thifranc ,

I'm just trying to understand why you want to hide the users from the viewers' userlist but allow them to see their names + stream in the webcam area. Maybe you're trying to restrict chatting (achievable via lock settings) or you're hiding the userlist altogether and want to have meetings where users only appear in the webcam area...

Please comment so we see what the full picture is. Otherwise it's difficult to change the behavior of an existent feature, causing everyone utilizing it to have to adapt to this change (the effect of which is not immediately obvious to the moderators in a meeting)

**Comment by SamuelWei** [comment]
I think it is more general issue. The naming of the permissions isn't really clear.
I had the problem myself, where I wondered why the students can't see each other, even though the restriction "See other viewers webcams" wan't enabled.

It would be better to limit the restriction to what it claims to restrict.
If the wording is 'See other viewers in the Users list' it should only limit the visibility of the other users in the list without any side effects.

**Comment by thifranc** [comment]
Well it appears that @KDSBrowne as already proposed a fix and PR for this bug, thks !

**Comment by antobinary** [comment]
I just merged #9407 implementing this requested change.
