### ISSUE TITLE
Any chance sound gets routed to the wrong conference on same BBB Server?

### ISSUE THREAD

**Issue by ironiemix** [bigbluebutton/bigbluebutton#9299]
**Users claim, they could hear the sound of another conference**

We got a mail from some users who claim, they could hear the sound of a different conference on the same BBB Server. 

**To Reproduce**

It was not possible for us to reproduce the problem.

My request is solely to verify if the developers can think of any circumstance this could happen. We have a cluster of  BBBs running in Germany and to us it is unclear if or under what circumstances this could happen. It would be a major data protection problem which we had to mitigate.

It would be great to hear back from you on this issue - thanks a lot for your great work.

Frank

**Comment by ritzalam** [comment]
Two meetings have probably the same conference numbers. 

We made a change to allow conf number between 5-10 digits in this PR (https://github.com/bigbluebutton/bigbluebutton/commit/a63f7df4bbb4b4bba1d5356703bbf30edc6719e3) It is available in 2.2.6 release.

**Comment by ironiemix** [comment]
Thanks für your quick reply! Sorry I have to ask - I understand, that the sound can be "misrouted" when the conference numbers are identical, I understand, that there is a smaller chance for identical numbers when the numbers are longer.

However I dont fully understand the implications:  Is there something I can or must do to avoid sound mismatch completely? Or is updating to 2.2.6 enough?

**Comment by ritzalam** [comment]
It depends on how you are assigning the conf numbers. There is a PR (https://github.com/bigbluebutton/bigbluebutton/pull/9251) that prevents collision of conf numbers if no voiceBridge param is passed on the api call.

If you are using your own front end, you can allocate the conf numbers there to make sure it is unique across your servers.

**Comment by ironiemix** [comment]
Thank you very much, closing this issue as "solved for me". Stay safe and healty!
