### ISSUE TITLE
Translated poll default option width not adjusted

### ISSUE THREAD

**Issue by frank-miller9** [bigbluebutton/bigbluebutton#9302]
**Describe the bug**
When creating a default poll in a non-english language, the entries could overlap the result:

**To Reproduce**
1. Change the language to e.g. German
2. Start a yes/no poll
3. Publish the poll

**Expected behavior**
The poll adjust to the text

**Actual behavior**
The poll does not adjust

**Screenshots**
![grafik](https://user-images.githubusercontent.com/62706264/80520182-56529900-8989-11ea-8151-d5eab2b8600d.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Firefox
 - Version: latest

**Comment by Sea444** [comment]
I noticed that the poll adjusts to first entry. 
So with "Zustimmung" and "Ablehnung" everything would be fine because first word is longer than second word.

**Comment by frank-miller9** [comment]
Hello @Sea444 thanks for testing. I can't confirm this. When I use a custom poll, then the size is adjusted:
![grafik](https://user-images.githubusercontent.com/62706264/80545228-21f3d280-89b3-11ea-9602-a6d43c03dc67.png)
or:
![grafik](https://user-images.githubusercontent.com/62706264/80545279-3fc13780-89b3-11ea-8d60-e1e0c3a8f2fd.png)

But it does not work for the predefined polls.

**Comment by wolbernd** [comment]
I can confirm this. It seems that the UI takes the width from the english words when using the predefined polls.

**Comment by antobinary** [comment]
@KDSBrowne addressed this in #9477 
![Screenshot from 2020-05-11 14-45-40](https://user-images.githubusercontent.com/6312397/81599054-4037d600-9396-11ea-9300-618e8d9a9484.png)
This is from the Default Yes/No option when on a client with locale switched to German (Presenter locale was English)
