### ISSUE TITLE
2nd poll does not remove first poll

### ISSUE THREAD

**Issue by frank-miller9** [bigbluebutton/bigbluebutton#9303]
**Describe the bug**
When publishing a 2nd poll, the first poll is not removed.

**To Reproduce**
1. Create a poll with 3 options
2. Publish the poll
3. Create a poll with two options
4. Publish the poll

**Expected behavior**
Only one poll visible

**Actual behavior**
Part of the first poll is still visible

**Screenshots**
![grafik](https://user-images.githubusercontent.com/62706264/80520662-0d4f1480-898a-11ea-8baa-287398607a83.png)

**Comment by FreeScholar** [comment]
How can we remove the polls from screen after it has been seen? The poll remains on screen as well as in the public chat.
