### ISSUE TITLE
More expressive hand rising

### ISSUE THREAD

**Issue by ostasevych** [bigbluebutton/bigbluebutton#9306]
**Is your feature request related to a problem? Please describe.**
It is not so easy to dig in and find the place where I may raise my hand or support someone's opinion. Raising of the hand should be separated from my state.

**Describe the solution you'd like**
Please, add separate buttons for users to express their opinion easily or request a voice to talk.

**Describe alternatives you've considered**
The raised hand and expressions of support should be shown explicitly and visually big on the screen. Now it is hidden very deeply with some additional not so important emotions.

**Additional context**
Have a look how Zoom implemented this.

**Comment by iSamof** [comment]
You may wish to add your voice and thoughts here to avoid fragmentation of ideas: https://github.com/bigbluebutton/bigbluebutton/issues/9072
