### ISSUE TITLE
Any command to see the no. of Running rooms?

### ISSUE THREAD

**Issue by tarunb999** [bigbluebutton/bigbluebutton#9319]
Hi all,

We have quite a few rooms and thus when we want to see how many rooms are running we have to scroll through the whole list in Greenlight->Organizattion-> Server Rooms. (and unfortunately the list cannot be sorted according to Running & Not Running)
Is there any command which can give us the list of all running rooms?

Thanks.

**Comment by frank-miller9** [comment]
Probably: https://docs.bigbluebutton.org/dev/api.html#ismeetingrunning ?

**Comment by tarunb999** [comment]
Thanks Frank..but it'll give me the info of one particular meeting, whereas I need a list of all the meetings which are running at the moment. (if only sort function was available for the column listing 'Running' and 'Not Running' server rooms in Greenlight)

**Comment by frank-miller9** [comment]
See: https://docs.bigbluebutton.org/dev/api.html#getmeetings

**Comment by tarunb999** [comment]
Thanks again !!! But I wanted somewhat of a list of Server rooms which are currently running.

**Comment by iangilmour** [comment]
FYI - I requested some Greenlight feature changes to the admin "Server Room" view. One of these includes sorting rooms by status - see https://github.com/bigbluebutton/greenlight/issues/1147. If you are using Greenlight you might want to add a vote.

**Comment by frank-miller9** [comment]
> 
> 
> Thanks again !!! But I wanted somewhat of a list of Server rooms which are currently running.

I did not test it, but does a combination work? Like: loading all meetings and then loop through it and check isMeetingRunning...

**Comment by tarunb999** [comment]
@frank-miller9 ..well this is already there in Greenlight through Server Rooms. But if an organisation has a few hundred rooms, then looking from the list might become a headache for dumbos like me ;-)
Anyhow lets wait for the next upgrade and we might in fact see such a feature of sorting the rooms and seeing the number of participants etc.
