### ISSUE TITLE
Ubuntu-Repos broken

### ISSUE THREAD

**Issue by to-kn** [bigbluebutton/bigbluebutton#9321]
**Describe the bug**
Hi, since some very short time, the repos for ubuntu return a 404:
`E: Failed to fetch https://ubuntu.bigbluebutton.org/xenial-22/dists/bigbluebutton-xenial/main/binary-amd64/Packages  404  Not Found`
Tested it also with the original one: 
`E: Failed to fetch https://ubuntu.bigbluebutton.org/xenial-220/dists/bigbluebutton-xenial/main/binary-amd64/Packages  404  Not Found
`
Thank you for alle the great work!
@ffdixon 

**Installation type**
bbb-install

**Console output**
see above

**Comment by to-kn** [comment]
see also: https://github.com/bigbluebutton/bbb-install/issues/183

**Comment by FPrefect42** [comment]
`sudo wget -qO- https://ubuntu.bigbluebutton.org/bbb-install.sh | bash -s -- -r packages-eu.bigbluebutton.org -v xenial-22 -a` works for me

**Comment by to-kn** [comment]
@FPrefect42 thank you for pointing to the alternate-repo (packages-eu.bigbluebutton.org) with this it is working!
I am closing this issue then

**Comment by defnull** [comment]
The official repositories are still broken, though. Please reopen this issue?

**Comment by ffdixon** [comment]
Try it now.

**Comment by nfc036** [comment]
Works! Thank you!

**Comment by nfc036** [comment]
apt update works now, apt upgrade gives 404's:

```
Ign:1 https://ubuntu.bigbluebutton.org/xenial-220 bigbluebutton-xenial/main i386 bbb-apps-akka all 2.2.0-81
Fehl:2 https://ubuntu.bigbluebutton.org/xenial-220 bigbluebutton-xenial/main amd64 bbb-config amd64 1:2.2.0-174
  404  Not Found
Fehl:3 https://ubuntu.bigbluebutton.org/xenial-220 bigbluebutton-xenial/main amd64 bbb-html5 amd64 1:2.2.0-886
  404  Not Found
Fehl:4 https://ubuntu.bigbluebutton.org/xenial-220 bigbluebutton-xenial/main amd64 bbb-record-core amd64 1:2.2.0-64
  404  Not Found
Fehl:1 https://ubuntu.bigbluebutton.org/xenial-220 bigbluebutton-xenial/main i386 bbb-apps-akka all 2.2.0-81
  404  Not Found
E: Fehlschlag beim Holen von https://ubuntu.bigbluebutton.org/xenial-220/pool/main/b/bbb-apps-akka/bbb-apps-akka_2.2.0-81_all.deb  404  Not Found

E: Fehlschlag beim Holen von https://ubuntu.bigbluebutton.org/xenial-220/pool/main/b/bbb-config/bbb-config_2.2.0-174_amd64.deb  404  Not Found

E: Fehlschlag beim Holen von https://ubuntu.bigbluebutton.org/xenial-220/pool/main/b/bbb-html5/bbb-html5_2.2.0-886_amd64.deb  404  Not Found

E: Fehlschlag beim Holen von https://ubuntu.bigbluebutton.org/xenial-220/pool/main/b/bbb-record-core/bbb-record-core_2.2.0-64_amd64.deb  404  Not Found
```

**Comment by Davka** [comment]
> Try it now.

Works for me

**Comment by defnull** [comment]
Yes, works again. Thanks!

**Comment by defnull** [comment]
This can be closed
