### ISSUE TITLE
Microphone and webcam not working after customizing BBB-html5

### ISSUE THREAD

**Issue by mohgh** [bigbluebutton/bigbluebutton#9324]
I'm customizing the html5 client according to the development guide. I've cloned the repo and built and ran the client via npm start and everything is running without errors but the microphone and screen sharing etc are not working. All these options are working when I use the packaged version but the version that I built from the code has this problem. I even started the app in production via NODE_ENV=production npm start cmd and the issue is still there. The browser is showing ERROR: clientLogger: Audio error - errorCode=1004, cause=Not Found error. 
Here are the steps I took.
1. Following the step-by-step guide to set up a working BBB server with https and domain.
2. Everything is working.
3. Cloning the project source code.
4. Building the html5 client using meteor.
5. Updating wsUrl using the guide.
6. Stoping the packaged version and running the html5 client using NODE_ENV=production npm start.

Is there any additional step I should do for customizing the client?

**Comment by basisbit** [comment]
are you sure you used the `v2.2.x-release` branch instead of `develop`?

**Comment by mohgh** [comment]
Yes, I'm sure. Here is the output of `git log --graph --decorate`.

* commit 07b76fc103266f4e4b33409d85bbc5d36ad173d7 (HEAD -> custom, origin/custom)
| Author: MyName <myemail>
| Date:   Tue Apr 28 11:25:06 2020 -0400
| 
|     change font
|  
* commit cee6fa3137392a5db17b66caeeb9090fbf1770ad
| Author: MyName <myemail>
| Date:   Tue Apr 28 11:13:37 2020 -0400
| 
|     add setstatus button
|    
*   commit ddb1b198879eb6d86b9e43e7f295e901d1f0593f (origin/v2.2.x-release)
|\  Merge: 7be4718 e805e7a
| | Author: Richard Alam <ritzalam@gmail.com>
| | Date:   Fri Apr 24 18:07:46 2020 -0400
| | 
| |     Merge pull request #9245 from ritzalam/make-bbb-web-localhost
| |     
| |      Bind to localhost
| |   
| * commit e805e7a3d29b5ec3c7adff6a8480b5de7e52bbbe
:

**Comment by mohgh** [comment]
I've found the bug.
In the settings.yml file, the value of `public/media/echoTestNumber` is 'echo' but it should be changed to the one in the packaged version.
Also in the `note` section, the configuration of Etherpad should be done also (both public and private).
These points should be included in the development docs.

**Comment by basisbit** [comment]
> In the settings.yml file

In which settings file? BBB has a couple of these :-\

**Comment by mohgh** [comment]
The settings file of the BBB html5 client. 
Address of the file in html5 client source code: `bigbluebutton/bigbluebutton-html5/private/config/settings.yml`
Address of the packaged html5 client: `/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml`

**Comment by jakiro2017** [comment]
> I've found the bug.
> In the settings.yml file, the value of `public/media/echoTestNumber` is 'echo' but it should be changed to the one in the packaged version.
> Also in the `note` section, the configuration of Etherpad should be done also (both public and private).
> These points should be included in the development docs.

So you mean `public/media/echoTestNumber = echo` is wrong and should be a number?

If that was true, it would be opposite my experience, the bundled (built from source) version should use echo, just change kurento_url,note, APIKEY... I backup the working config from apt and restore, there're so many anomalies with bbb-html5

It was a headache :(

**Comment by basisbit** [comment]
`public/media/echoTestNumber` should be `echo`. That did probably not work for the thread starter because of custom file modifications or using some files form an older BBB version.

**Comment by basisbit** [comment]
instead of backing up and restoring configuration files after update install, you'll want to use the [`apply-config.sh`](https://docs.bigbluebutton.org/2.2/customize.html#automatically-apply-configuration-changes-on-restart) script to modify the new configuration files after each update.
