### ISSUE TITLE
Avatar img doesn't shows up by passing it throught php api

### ISSUE THREAD

**Issue by shiwamavg** [bigbluebutton/bigbluebutton#9325]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Actual behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, Mac]
 - Browser [e.g. Chrome, Safari]

**Smartphone (please complete the following information):**
 - Browser [e.g. stock browser, Safari]

**Additional context**

**Comment by frank-miller9** [comment]
See: https://github.com/bigbluebutton/bigbluebutton/issues/8566

**Comment by GhaziTriki** [comment]
Duplicate of #8566. The avatar image was in the Flash client and it is planned to be implemented in the HTML5 client.
