### ISSUE TITLE
PHP API GetMeetingInfo, IsMeetingRunning always returns {} whether its running or not.

### ISSUE THREAD

**Issue by Happy-2020** [bigbluebutton/bigbluebutton#9326]
**Describe the bug**
I need to know if a meeting room is still available or no, so i have tried with isMeetingRunning api, but it fails, always return {}, so i moved to GetMeetingInfo Api, but same goes with this.

**Desktop (please complete the following information):**
I have rent a dedicated hosting server, and have installed bbb on it.
Meeting is fine, but can't get any meeting information.

 - OS: Windows
 - Browser Chrome
 - Version 22

**Additional context**

Still its giving me {} response only. I checked this community, and found a comment saying.. execute this command on the server, bbb-conf --clean, bbb-conf -- check...
But unfortunately, I am still getting the same response {}, Do I have to touch some configuration files? Please kindly refer my issue, and give me your advice.

//-------CODE FOR CREATING MEETING ROOM---------
$meetingID = $meetID;
$meetingName = $meetName;
$attendee_password = 'zxcewef';
$moderator_password = 'ddwqas';
$duration = 60 * 1000 * 60;

$urlLogout = url('/')."xxx";
$isRecordingTrue = true;

$createMeetingParams = new CreateMeetingParameters($meetingID, $meetingName); $createMeetingParams->setAttendeePassword($attendee_password);
$createMeetingParams->setModeratorPassword($moderator_password);
$createMeetingParams->setDuration($duration);
$createMeetingParams->setLogoutUrl($urlLogout);
if ($isRecordingTrue) {
$createMeetingParams->setRecord(true);
$createMeetingParams->setAllowStartStopRecording(true);
$createMeetingParams->setAutoStartRecording(true);
}

$response = $bbb->createMeeting($createMeetingParams);

//--------CODE FOR CHECKING ROOMINFOR---------------
$bbb = new BigBlueButton();
$meetingRunningParameters = new GetMeetingInfoParameters($meetingID, $moderator_password);
$meetStatus = $bbb->getMeetingInfo($meetingRunningParameters);

Can anyone please give me your experiences and advice.
Thanks!

**Comment by route95-technologies** [comment]
Hello, I experience the same problem! already created an issue #9318

**Comment by frank-miller9** [comment]
Same page: https://docs.bigbluebutton.org/dev/api.html#getmeetings

**Comment by Happy-2020** [comment]
Hi route95-technologies,
I checked on your issue contents, you are saying you can get meeting information while the meeting happens, but for me, I can never get any information while it is running or not.

I think, your issue can be solved when you check on the bbb-conf setting, there you can see a clear timer, originally it is set to 1 minute. Means, after 1 minute, all the meeting information gets cleared from the server history. I believe you can solve it easily when you make it longer in the setting file.
But I am having more serious issue, I always get response {}. 

I will be happy if you give me any advice.

**Comment by route95-technologies** [comment]
@Happy-2020 thanks for the info, but actually, i only get the information from the calls for a few minutes from **START** of meeting after that, it is always {}, even though the meeting is running actually.

**Comment by Happy-2020** [comment]
Thanks for your advice.
So, eventually, our issue can be solve if the bigbluebutton team gives us support and sort this out.
How can we push them to solve this for quick?

**Comment by route95-technologies** [comment]
Hey @Happy-2020 I keep bbb server on UTC and server that uses the api on Europe\Helsinki 
this should't be an issue as i thing that bbb uses UNIX timestamps

**Comment by Happy-2020** [comment]
Thanks!

**Comment by hus3h** [comment]
> check on the bbb-conf setting, there you can see a reset timer

@Happy-2020 Hello, can you please tell me the location of the file and the setting you mentioned? I only found a setting for inactivity timeout before ending the meeting in `bigbluebutton.properties`, but nothing about keeping the meeting info for few minutes before cleaning them.

**Comment by matiasilva** [comment]
Hi guys, can we move this discussion to the developer mailing list where it belongs?
