### ISSUE TITLE
Bad anonymous writers to shared notes

### ISSUE THREAD

**Issue by Justarone** [bigbluebutton/bigbluebutton#9328]
**not a bug, but** we have our lections (university, BMSTU, Moscow) on your platform but we have some freaks in our academic group who is writing bad things in shared notes. 
The question is: is there any possibility to know, who is writing to shared notes Or is there any possibility to disable them at all?

**Comment by ffdixon** [comment]
Any moderator can prevent viewers from writing on the Shared notes via the Lock settings (as Moderator, click the gear icon next to the title of the Users list).

![image](https://user-images.githubusercontent.com/290351/80589522-5766e300-89e8-11ea-9c2c-6fe262e4708c.png)

**Comment by Justarone** [comment]
Thanks!
