### ISSUE TITLE
Set mute by clicking speaking user behaviour

### ISSUE THREAD

**Issue by weeman1337** [bigbluebutton/bigbluebutton#9329]
This isn't a bug report - more a report from user tests.

What happened: I showed BBB to some users. Technically it is working great! :+1: 

One issue while testing was: Users (presenters) are clicking around. In the talking area names are blinking if someone speaks. This attracts users. They click on it. Result: user is muted. Clicking again doesn't unmute the user. They don't find the option in the users list for unmute.

Maybe one of this could improve the experience:
* Click on the name should toggle instead of being one way mute only
* Removing the mute function from the talking users list and only provide the way to mute on the left

**Comment by frank-miller9** [comment]
I see your point and we discussed this in our company, too if this is a needed feature....the problem is, that you as the muted user sometimes do not want to get unmuted.

So in our use case we would prefere your 2nd point but no unmute by a "admin" because of privacy reasons.
