### ISSUE TITLE
Deploy html5 changes to server

### ISSUE THREAD

**Issue by jainvipin69** [bigbluebutton/bigbluebutton#9330]
We have done some changes to the UI layout of the html5 client. We want to know how to push those changes to the server, as we tried running the meteor for production but it did not load the new changes.

Does this means that we cannot modify html5 UI?

**Comment by frank-miller9** [comment]
Did you read: http://docs.bigbluebutton.org/2.2/dev.html#developing-the-html5-client ?

**Comment by jainvipin69** [comment]
Yes Frank, have followed the steps untill NODE_ENV=production npm start, but it does not load the changes to the bbb server.

**Comment by jainvipin69** [comment]
Can you guide what i am not following right?

**Comment by matiasilva** [comment]
Hi, the guide has been updated. Please follow the instructions there and then seek help in the forums.
