### ISSUE TITLE
Some keyboard shortcuts don't seem to work in macOS

### ISSUE THREAD

**Issue by muello** [bigbluebutton/bigbluebutton#9331]
Some keyboard shortcuts, for example mute/unmute, don't seem to work in macOS.

**To Reproduce**
1. Join a meeting with microphone
2. Press Command + Shift + M, Option (alt) + Shift + M, Control + Shift + M

**Expected behavior**
Mute toggles on/off as when clicking the mute button.

**Actual behavior**
Nothing happens.

Other interactions with the keyboard are possible, e.g. participating in chat or, as presenter, advancing slides with arrow keys when slide menu is active. Similarly, it is possible to tab through to the mute button and use Enter to toggle it (works fine). However, this is only useful in very limited circumstances (not wanting to access other functions via the keyboard, e.g. chat, other keyboard shortcuts).

**Desktop**
 - OS: MacOS 10.12
 - Browser: Firefox 75.0

**Comment by ubahnverleih** [comment]
Maybe should fixed with https://github.com/bigbluebutton/bigbluebutton/pull/9081 in 2.2.7?
Can you try if control + option + M works?

**Comment by muello** [comment]
Thanks for the pointer, I hadn't seen the change.

Control + Option + M works.

Some other shortcuts work too, for example
Open actions menu: Control + Option + A
Toggle public chat: Control + Option + P

For what it's worth, I can't get
Toggle user list: Control + Option + U
to work.

**To Reproduce**
Control + Option + M, then Control + Option + M again,
Control + Option + P, then Control + Option + P again,
Control + Option + U.

**Expected behavior**
Mute toggles off and then on again; public chat appears, and then disappears again; user list disappears.

**Actual behavior**
Mute toggles off and then on again; public chat appears, and then disappears again; but user list does not disappear.
