### ISSUE TITLE
Customize the Layout of HTML5Client

### ISSUE THREAD

**Issue by NiceboyWiseboy** [bigbluebutton/bigbluebutton#9333]
Hello,
 
I want to customize the layout of HTML5Client. Is there a way to do it?

Thank you,
Best Regards

**Comment by frank-miller9** [comment]
See: http://docs.bigbluebutton.org/2.2/dev.html#developing-the-html5-client

**Comment by Entretoize** [comment]
Is there anything more complicated ?

**Comment by NiceboyWiseboy** [comment]
> See: http://docs.bigbluebutton.org/2.2/dev.html#developing-the-html5-client

Followed the guide, but the meeting doesn't start.
Also tried to build the code into METEOR PRODUCTION APP, but  also didn't got worked out as well.

**Comment by iSamof** [comment]
Just FYI - the dev team are working on a Layout Editor. If your requirement is not super urgent and critical, you may want to wait for the Layout Editor. That is what we are doing.

**Comment by basisbit** [comment]
Duplicate of #5836
