### ISSUE TITLE
Screen sharing not working on Wayland

### ISSUE THREAD

**Issue by hex-m** [bigbluebutton/bigbluebutton#9338]
Sharing the entire screen does not work on Wayland systems.

**To Reproduce**
Server: BBB 2.2.5
Client: Debian Bullseye (testing) with GNOME on Wayland, AMD64, two monitors

Tested in Firefox 68.7.0esr(64-bit)
1. Click on 'Share your Screen'
2. Firefox offers different Options of what to share. "Your Entire Screen" is black in the preview. Share this.
3. The screen is shared but it's black except for the mouse pointer.

The same problem appears in Chromium 81

**Additional context**
This problem seems to be know, as it was [mentioned](https://groups.google.com/d/msg/bigbluebutton-dev/v81jZjBMOkI/AAJXeFSwCwAJ) on the developer mailing list.

**update**
I tested on a "GNOME on X.ORG"-Session and can confirm that it's working as expected there.

I also noticed that in a Wayland session not all open windows are available to be shared. Not sure it that should be a separate issue.

**Comment by basisbit** [comment]
Does it work for you using this [WebRTC screen sharing sample](https://www.webrtc-experiment.com/Pluginfree-Screen-Sharing/#9514356012950654)?

**Comment by hex-m** [comment]
> Does it work for you using this [WebRTC screen sharing sample](https://www.webrtc-experiment.com/Pluginfree-Screen-Sharing/#9514356012950654)?

Same problem here (with both browsers). So I guess that's not something that bbb can fix.

**Comment by basisbit** [comment]
Indeed. In this case, please report the problem to the browser developers. Might be some problem with how chrome/firefox use X server API.

**Comment by ann0see** [comment]
I think wayland doesn't support screen sharing. This "Bug" was also present in jitsi meet.

**Comment by basisbit** [comment]
I guess this issue can be closed in this case, because technically this is not a big in BigBlueButton?

**Comment by hex-m** [comment]
Yes, let's close this.
As a reference for others this limitation should be mentioned in the [documentation](https://docs.bigbluebutton.org/support/faq.html#what-are-the-minimum-requirements-for-the-bigbluebutton-client) imo.
It seems the there is work in the Pipewire project to solve this problem but the [proposed solution](https://wiki.archlinux.org/index.php/PipeWire#WebRTC_screen_sharing) didn't work on my system.

Feel free to use this issue to document your level of success.
