### ISSUE TITLE
post_archive script not being executed

### ISSUE THREAD

**Issue by OskarCarl** [bigbluebutton/bigbluebutton#9342]
**Describe the bug**
Hello, I'm trying to create a `post_archive` script that deletes all temporary files right after the session ends if no recording was requested.

It works fine if a recording *is* requested but is not executed if the button *is not* pressed while the meeting was held.
From the documentation I'd expect the `post_archive` scripts to be executed irrespective of the actual recording.

**To Reproduce**
1. Place a Ruby script writing log output into the `post_recording` directory and make it executable
2. Create and finish a meeting
3. Watch log output of the script

**Expected behavior**
The script should *always* be executed after archiving is done.

**Actual behavior**
The script is only run if the _recording_ button was pressed in the meeting.

**Additional context**
I'm basing this on the premise that Greenlight is used and the recording feature is needed for at least _some_ rooms on the instance. As long as this cannot be configured on a per-room basis, I intend to use this script as a workaround that is non-invasive. I do not want to change the `archive.rb` script.

**Comment by paul1278** [comment]
Got the same problem, but when looking at the charts [here](https://docs.bigbluebutton.org/dev/recording.html#sanity), you can see that these scripts run only after the sanity-phase. But the sanity-phase only starts when an `archived.done`-file is generated, and when a meeting has no recordings the archive-phase only creates a `*.norecord`-file

**Comment by Kalagon** [comment]
You're right, it does show that the `post_archive` script is not executed.
But it's actually the other way around if I understand correctly. If there was no recording requested, the `archived.done` file _is_ created, which causes the sanity phase to be skipped entirely, including the post scripts.

**Comment by paul1278** [comment]
Really? Maybe I misunderstood something there..

But when I look into the `/var/bigbluebutton/recording/status/archived`-folder, I always get a .norecord-file when no recording was created.

Because when the sanity-phase is skipped, the whole process ends, right? 
When looking at the run-condition of the `bbb-rap-sanity-worker`, it shows that it only runs when a .done-file is created by the archive-worker.
The condition looks like this:
`ConditionPathExistsGlob=/var/bigbluebutton/recording/status/archived/*.done`

**Comment by Kalagon** [comment]
I haven't looked into the code yet. Your reasoning seems solid, though contradictory to the schematic. There the sanity phase is skipped entirely if the `archived.done` file exists.

**Comment by paul1278** [comment]
Yes, I agree with you that if we follow the schematic, the condition looks different

**Comment by mabras** [comment]
Hi @Kalagon,
Did you manage to fix this somehow?

Thanks

**Comment by Kalagon** [comment]
No, probably because it's intentional.
I've added a line into the `archive.rb` that explicitly calls my post_archive script
