### ISSUE TITLE
To create join url via API the url do not start conferance as expected but give us greenlight page

### ISSUE THREAD

**Issue by alimashalkpu** [bigbluebutton/bigbluebutton#9346]
I checked the meeting with the same parameter vi https://mconf.github.io/api-mate/ but my local is not working

**Comment by NiceboyWiseboy** [comment]
Hello,
I'm having also the same issue.

**Comment by alimashalkpu** [comment]
> Hello,
> I'm having also the same issue.

I find out that in new version your api url should something like this BBB_SERVER_BASE_URL=https://test.com/bigbluebutton/
final url is BBB_SERVER_BASE_URL=https://test.com/bigbluebutton/api   this worked for me
