### ISSUE TITLE
Show notice about muted microphone if user speaks

### ISSUE THREAD

**Issue by debuglevel** [bigbluebutton/bigbluebutton#9351]
**Is your feature request related to a problem? Please describe.**
On large conferences, users usually mute themselves. If they speak, they sometimes forget to unmute themselves.

**Describe the solution you'd like**
MS Teams shows a notice if it the suers speaks but the microphone is muted ("Your microphone is muted")

**Comment by ostasevych** [comment]
The same about Jitsi: there's a reminder.

**Comment by pedrobmarin** [comment]
Implemented in https://github.com/bigbluebutton/bigbluebutton/pull/9851
