### ISSUE TITLE
User able to join into a meeting from multiple devices or browser tabs in spite of allowDuplicateExtUserId is set to false

### ISSUE THREAD

**Issue by krishnateja-ct** [bigbluebutton/bigbluebutton#9354]
**Describe the bug**
A user is able to join the same meeting from multiple devices or browser tabs in spite of **allowDuplicateExtUserId** is set to **false** after upgrading BBB from 2.2.5 to 2.2.8.

**To Reproduce**
1. Update **allowDuplicateExtUserId** in /usr/share/bbb-web/WEB-INF/classes/**bigbluebutton.properties** and /usr/local/bigbluebutton/bbb-webrtc-sfu/config/**default.yml** to **false** and restart bbb-conf.
2. Join as a user with the same **extId** from multiple browser tabs or devices.
3. A user now has multiple presences in a meeting.

**Expected behavior**
Before I updated BBB from 2.2.5 to 2.2.8, with the above-mentioned customization, I could restrict the presence of a user with a particular **extId** in a meeting to one.

**Actual behavior**
I would like the functionality of the **allowDuplicateExtUserId** customization to be restored to its original implementation as in 2.2.5

**Desktop (please complete the following information):**
 - OS: [Observed on mutiple OS like Ubuntu 18.04, Windows]
 - Browser [All browsers]
 - Version [Latest]

**Comment by prlanzarin** [comment]
@krishnateja-ct the correct option is the one @pedrobmarin linked. You're mixing things up, the bbb-webrtc-sfu one has nothing to do with what you're trying to achieve (or BBB users themselves).

**Comment by krishnateja-ct** [comment]
> https://github.com/bigbluebutton/bigbluebutton/blob/4f786f7f033d708fdd3f8d21ed44e3f7acfd4739/bigbluebutton-web/grails-app/conf/bigbluebutton.properties#L347



> @krishnateja-ct the correct option is the one @pedrobmarin linked. You're mixing things up, the bbb-webrtc-sfu one has nothing to do with what you're trying to achieve (or BBB users themselves).

@pedrobmarin  @prlanzarin Apologies, I made customization in bigbluebutton.properties files as well originally (issue description corrected). I have another server running on 2.2.5 version with this customization and I am seeing the expected behaviour.

**Comment by krishnateja-ct** [comment]
Any update on the allowDuplicateExtUserid issue I am facing in version 2.2.8.

Is there a way I can roll back the BBB version to 2.2.5?

**Comment by krishnateja-ct** [comment]
The issue still persists after updating BBB server to 2.2.9

**Comment by ravi-ct** [comment]
This is definitely a regression. It works fine in 2.2.5 but breaks in 2.2.7 or 2.2.9.

I diffed the sources of 2.2.5 and 2.2.9 and noticed the following.

Not sure if reverting this breaks something else as I am entirely new to this and haven't spent enough time to understand the difference between RegisteredUsers.remove and RegisteredUsers.eject

```bash
$ diff -U 7 bigbluebutton-2.2.5/akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/UsersApp.scala bigbluebutton-2.2.9/akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/UsersApp.scala 
--- bigbluebutton-2.2.5/akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/UsersApp.scala	2020-04-13 03:34:03.000000000 +0530
+++ bigbluebutton-2.2.9/akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/UsersApp.scala	2020-05-01 05:19:24.000000000 +0530
@@ -89,15 +89,15 @@
   def ejectUserFromMeeting(outGW: OutMsgRouter, liveMeeting: LiveMeeting,
                            userId: String, ejectedBy: String, reason: String, reasonCode: String): Unit = {
 
     val meetingId = liveMeeting.props.meetingProp.intId
 
     for {
       user <- Users2x.ejectFromMeeting(liveMeeting.users2x, userId)
-      reguser <- RegisteredUsers.remove(userId, liveMeeting.registeredUsers)
+      reguser <- RegisteredUsers.eject(userId, liveMeeting.registeredUsers, ejectedBy)
     } yield {
       sendUserEjectedMessageToClient(outGW, meetingId, userId, ejectedBy, reason, reasonCode)
       sendUserLeftMeetingToAllClients(outGW, meetingId, userId)
       if (user.presenter) {
         automaticallyAssignPresenter(outGW, liveMeeting)
       }
     }
```

**Comment by ravi-ct** [comment]
In `bigbluebutton-2.2.9/akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/users/EjectDuplicateUserReqMsgHdlr.scala`, `ejectedBy` is set to `SystemUser.ID`.

In the following code in `./bigbluebutton-2.2.9/akka-bbb-apps/src/main/scala/org/bigbluebutton/core/models/RegisteredUsers.scala`,  while attempting to ban, the condition `ejectedUser.externId != ejectedByUser.externId` will always evaluate to true as `ejectedByUser` is `SystemUser` and would never go into the else state where the user deletion happens.

```scala
  private def banUser(ejectedUser: RegisteredUser, users: RegisteredUsers, ejectedByUser: RegisteredUser): RegisteredUser = { 
    // Some users join with multiple browser to manage the meeting.
    // Don't black list a user ejecting oneself.
    // ralam april 23, 2020
    if (ejectedUser.externId != ejectedByUser.externId) {
      // Set a flag that user has been ejected. We flag the user instead of
      // removing so we can eject when user tries to rejoin with the same
      // external userid.
      // ralam april 21, 2020
      val u = ejectedUser.modify(_.ejected).setTo(true)
      users.save(u)
      u   
    } else {
      users.delete(ejectedUser.id)
      ejectedUser
    }   
  }
  def eject(id: String, users: RegisteredUsers, ejectedBy: String): Option[RegisteredUser] = { 
    for {
      ru <- findWithUserId(id, users)
      eu <- findWithUserId(ejectedBy, users)
    } yield {
      banUser(ru, users, eu)
    }
  }
```

**Comment by ravi-ct** [comment]
In `RegisteredUsers.scala`, changing the following line in the `banUser` method as proposed below may be the solution:

```scala
if (ejectedUser.externId != ejectedByUser.externId) {
```

to

```scala
if (SystemUser.ID != ejectedByUser.ID && ejectedUser.externId != ejectedByUser.externId) {
```

**Comment by pedrobmarin** [comment]
Thanks for pointing that out.
@ritzalam it's related with this changes https://github.com/bigbluebutton/bigbluebutton/commit/58fed457541e9282fb7556aa606e52112ce89d98

**Comment by hex-m** [comment]
I tried setting `allowDuplicateExtUserid=false` on a `2.5.5`-Instance and it works fine for me.
