### ISSUE TITLE
Application screen share shows no "sub-windows" on Linux KDE

### ISSUE THREAD

**Issue by LaumiH** [bigbluebutton/bigbluebutton#9356]
I have the following problem on Manjaro Linux with KDE 5.69.0 / Plasma 5.18.4 :

When I share a single application, the participants can only see the main window of it. So when I open a menu or the application opens a second window (e.g. in Wireshark the packet window), then this is invisible.

It seems to work on Windows. 

It is not something there is no workaraound for, because you can always share the whole screen, but this gets incomfortable when you have multiple monitors attached.

I have not tested it on other desktops or distros and am curious if it happened to others aswell.

**Comment by defnull** [comment]
That would be a browser limitation and not something BBB could fix or influence in any way.

**Comment by LaumiH** [comment]
Thank you for the quick answer and the clarification! I'll investigate and see if I can get it to work somehow. I am using Chromium.
Is this behavior documented somewhere, or is there by any chance a correct place where I can add it?
