### ISSUE TITLE
Media controls not visible in Chrome for external video files

### ISSUE THREAD

**Issue by sklamt** [bigbluebutton/bigbluebutton#9358]
**Describe the bug**
The player controls for external video files are not visible in Chrome and Chromium.

**To Reproduce**
1. Open Big Blue Button in Chrome
2. Create a Meeting.
3. Share an audio file, for example an ".mp3" via URL.
4. There are no media controls visible

**Expected behavior**
The media controls should be visible to the presenter.

**Actual behavior**
The media controls are not visible to the presenter.

**BBB version (optional):**
BigBlueButton Server 2.2.6 (1871)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Chrome
 - Version 81

It seems that the Option:
```
:root {
  ::-webkit-media-controls {
    display: none !important;
  }
}
```
in the file `bigbluebutton-html5/imports/ui/components/fullscreen-button/styles.scss` and `bigbluebutton-html5/imports/ui/components/presentation/download-presentation-button/styles.scss` 
causes this behavior.
I am not sure whether this option is needed elsewhere or if it could be removed globally.

**Comment by basisbit** [comment]
can you reproduce this on https://test.bigbluebutton.org ?

**Comment by sklamt** [comment]
Yes, I can reproduce this on https://test.bigbluebutton.org/ .

**Comment by abias** [comment]
I can confirm this issue on 2.2.9 and would like to add that we have seen two different sub-behaviours:

* One cluster of videos will, when shared with the "Share an external video" function, be displayed in Chrome with their first frame only. If you click onto the video and press the space key on your keyboard, the video is played just like it's expected. This indicates that really only the video control widgets are missing.

* The other cluster of videos will, when shared with the "Share an external video" function, not be displayed at all in Chrome. Clicking onto the video and pressing the space key does not do anything. A public example for this cluster is http://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4. This is especially weird as this video plays fine in Chrome when loaded directly in a Chrome tab.

Cheers,
Alex

**Comment by Farshid928** [comment]
Is there a solution to this problem?

**Comment by pedrobmarin** [comment]
I believe this was fixed https://github.com/bigbluebutton/bigbluebutton/pull/9966

**Comment by abias** [comment]
I just tested this again on BBB 2.2.28.

Steps to reproduce:
* Open the same BBB session in Chrome and in Firefox
* In Chrome, share the external video http://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4.

Expected result:
* The video is visible in Chrome
* The video is played in Chrome automatically
* The video is visible in Firefox as well
* As soon as the playback is started in Chrome, the video also starts playing in Firefox.

Actual result:
* An empty video player is shown in Chrome
* The video cannot be played in Chrome 
* The video is visible in Firefox
* The video starts to play automatically in Firefox, but pauses after approx. 4 seconds.

----

Steps to reproduce:
* Open the same BBB session in Chrome and in Firefox
* In Firefox, share the external video http://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4.

Expected result:
* The video is visible in Firefox
* The video is played in Firefox automatically
* The video is visible in Chrome as well
* As soon as the playback is started in Firefox, the video also starts playing in Chrome.

Actual result:
* The video is visible in Firefox
* The video is played in Firefox automatically
* An empty video player is shown in Chrome
* The video is not played in Chrome

----

So, I assume that #9966 might have improved this issue as there wasn't any player shown in Chrome when I tested last time, but the feature is still broken on Chrome.

**Comment by pedrobmarin** [comment]
My best guess would be the unsecure http protocol from your media.

**Comment by abias** [comment]
Oh, shame on me!
You are right. If I use a video file from a secure URL, this feature works like a charm now in Chrome!

So this issue can be closed. Thanks for your work!
