### ISSUE TITLE
Wordpress plugin start rooms only in flash, I want html5

### ISSUE THREAD

**Issue by atrex123** [bigbluebutton/bigbluebutton#9360]
Hi friends, I installed BBB, I wanna use this in my word press site. WP BBB plugin starts rooms just in flash mode. how could i modify plugin or BBB to process all requests to HTML5  only. Please

**Comment by atrex123** [comment]
No no, if you set your bbb to start just in html5, the wordpress plugin
will always start with html5, I did if for me i can show you

**Comment by GhaziTriki** [comment]
@atrex123 Do you mean it is still an issue? The Flash client is no more supported.

**Comment by atrex123** [comment]
modify these lines in this address such as me
/usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties.


# Force all attendees to join the meeting using the HTML5 client
attendeesJoinViaHTML5Client=true

# Force all moderators to join the meeting using the HTML5 client
moderatorsJoinViaHTML5Client=true
