### ISSUE TITLE
ipv4.test.bigbluebutton.org uses invalid SSL Certificate

### ISSUE THREAD

**Issue by Flole998** [bigbluebutton/bigbluebutton#9361]
I tried to use test.bigbluebutton.org but I am getting an error in the Console about an invalid Certificate being used for wss://ipv4.test.bigbluebutton.org/ws. Testing manually with https://ipv4.test.bigbluebutton.org/ shows that it does indeed return a certificate for test.bigbluebutton.org which is obviously invalid for ipv4.test.bigbluebutton.org.

**Comment by ffdixon** [comment]
Thanks -- we need to fix that!

**Comment by Flole998** [comment]
@ffdixon Can we mark this one as "important" or "high priority" or something like that? This issue prevents users from testing if an issue is with a specific installation or a general issue, the test installation should be in a usable state as that is the best way to locate problems.

**Comment by ffdixon** [comment]
Thanks for the ping ... we'll take a look

**Comment by ffdixon** [comment]
Can you try it now and let us know if you still get an error.

**Comment by Flole998** [comment]
Thanks, that issue is solved. I just noticed something that might be another issue though: on http://ipv4.test.bigbluebutton.org/ (without https) there is an nginx welcome page while on http://test.bigbluebutton.org/ and https://ipv4.test.bigbluebutton.org/ (with https) there is the BigBlueButton welcome screen. I assume this is not intended and you just missed that servername in the nginx config?

**Comment by basisbit** [comment]
can confirm that http://ipv4.test.bigbluebutton.org/ (not https) only shows an empty default nginx server page. -> fyi @ffdixon

**Comment by Flole998** [comment]
Seems to be fixed
