### ISSUE TITLE
cannot start bigbluebutton html5. Im try install "npm start" with "meteor npm install" and it does not work...

### ISSUE THREAD

**Issue by alexperdo** [bigbluebutton/bigbluebutton#9366]
This is the message that generate the command "npm start" when im trying running 
 the Development environment of bigblubutton-html5

**this is the tutorial i followed " https://docs.bigbluebutton.org/2.2/dev.html "**

The messages error:

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bbb-html5-client@ start:dev: `ROOT_URL=http://127.0.0.1/html5client NODE_ENV=development meteor`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bbb-html5-client@ start:dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-04-30T23_28_17_291Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bbb-html5-client@ start: `if test "$NODE_ENV" = "production" ; then npm run start:prod; else npm run start:dev; fi`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bbb-html5-client@ start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-04-30T23_28_17_304Z-debug.log

**Comment by tarekwelaya** [comment]
I'm having the same issue were you able to solve?

**Comment by alexperdo** [comment]
@tarekwelaya not yet...

**Comment by tarekwelaya** [comment]
try running this command `METEOR_ALLOW_SUPERUSER=true` then `npm start` it solved the issue for me

**Comment by alexperdo** [comment]
@tarekwelaya  Yes, the command `export METEOR_ALLOW_SUPERUSER=true`, it solved the issue for me too <3 =D. Thanks

**Comment by emaalouf** [comment]
alexperdo, you sir are a life saver, thank you very much!
