### ISSUE TITLE
Escaped unicode characters problem in bigbluebutton.properties

### ISSUE THREAD

**Issue by RealLordK1** [bigbluebutton/bigbluebutton#9370]
**Describe the bug**
After the last update, the escaped unicode characaters int the defaultWelcomeMessage and defaultWelcomeMessageFooter of bigbluebutton.properties have seen their \u removed.

**To Reproduce**
Apt upgrade a server with escaped unicode characters in defaultWelcomeMessage and defaultWelcomeMessageFooter.

**Expected behavior**
defaultWelcomeMessage and defaultWelcomeMessageFooter remains the same.

**Comment by rasos** [comment]
Confirmed, all backslashes are removed. Luckily, I had a backup of bigbluebutton.properties.

**Comment by RealLordK1** [comment]
backslashes and the following U in my case.

**Comment by GhaziTriki** [comment]
@RealLordK1 Did you use `native2ascii` to escape the characters?

**Comment by RealLordK1** [comment]
No, I did it in an extern app, then copy/pasted it in the file.
After the upgrade, only \u were removed.

**Comment by GhaziTriki** [comment]
As Java 8 does only support ASCII characters in properties files you need to force the file conversion. You put your UTF-8 code into the configuration file then convert it.

```
sudo apt-get install -y openjdk-8-jdk-headless
sudo native2ascii "/usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties" "/usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties"
```

Can you please tell us if it works after restarting BigBlueButton?

**Comment by RealLordK1** [comment]
I will test it and report, but I already did the modifications by hand, and all is perfectly working.
Only the upgrade seems to have removed something.

**Comment by GhaziTriki** [comment]
Using `native2ascii` is the right solution with Java 8.

**Comment by RealLordK1** [comment]
Sorry but it isn't, as the first \u of every special character is removed.
You have to remodify by hand every time.

**Comment by BaseMax** [comment]
I am using **native2ascii** tool for more then 2 years and its perfect for supporting UTF8 text.
Thanks all.
