### ISSUE TITLE
after update package 404  Not Found

### ISSUE THREAD

**Issue by djoudi** [bigbluebutton/bigbluebutton#9373]
After this operation, 314 kB of additional disk space will be used.
Do you want to continue? [Y/n] Y
Err:1 https://ubuntu.bigbluebutton.org/xenial-220 bigbluebutton-xenial/main amd64 bbb-web amd64 1:2.2.0-123
  404  Not Found
Err:2 https://ubuntu.bigbluebutton.org/xenial-220 bigbluebutton-xenial/main amd64 bbb-freeswitch-core amd64 2:2.2.0-103
  404  Not Found
Err:3 https://ubuntu.bigbluebutton.org/xenial-220 bigbluebutton-xenial/main amd64 bbb-config amd64 1:2.2.0-175
  404  Not Found
Err:4 https://ubuntu.bigbluebutton.org/xenial-220 bigbluebutton-xenial/main amd64 bbb-html5 amd64 1:2.2.0-887
  404  Not Found
Err:5 https://ubuntu.bigbluebutton.org/xenial-220 bigbluebutton-xenial/main amd64 bbb-record-core amd64 1:2.2.0-64
  404  Not Found
E: Failed to fetch https://ubuntu.bigbluebutton.org/xenial-220/pool/main/b/bbb-web/bbb-web_2.2.0-123_amd64.deb  404  Not Found

E: Failed to fetch https://ubuntu.bigbluebutton.org/xenial-220/pool/main/b/bbb-freeswitch-core/bbb-freeswitch-core_2.2.0-103_amd64.deb  404  Not Found

E: Failed to fetch https://ubuntu.bigbluebutton.org/xenial-220/pool/main/b/bbb-config/bbb-config_2.2.0-175_amd64.deb  404  Not Found

E: Failed to fetch https://ubuntu.bigbluebutton.org/xenial-220/pool/main/b/bbb-html5/bbb-html5_2.2.0-887_amd64.deb  404  Not Found

E: Failed to fetch https://ubuntu.bigbluebutton.org/xenial-220/pool/main/b/bbb-record-core/bbb-record-core_2.2.0-64_amd64.deb  404  Not Found

E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

**Comment by alangecker** [comment]
the repository was broken, but got fixed: https://github.com/bigbluebutton/bigbluebutton/issues/9321

maybe retry `apt-get update` and `apt-get upgrade`.
Is the issue still there for you?

**Comment by djoudi** [comment]
now is ok thanks @alangecker
