### ISSUE TITLE
Welcome message not updating

### ISSUE THREAD

**Issue by devashish-laitkor** [bigbluebutton/bigbluebutton#9374]
Hi,

I am trying to update welcome message on BBB https://www.screencast.com/t/lmD3HgQO

I have followed the documentation https://docs.bigbluebutton.org/2.2/customize.html#change-the-default-welcome-message. 
And updated file ```/usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties```
for the variable ```defaultWelcomeMessage``` and ```defaultWelcomeMessageFooter```

After that i have restarted BBB as well ```sudo bbb-conf --restart```

After restart i found that ```defaultWelcomeMessageFooter``` changes are reflecting on frontend.
**But the the changes for ```defaultWelcomeMessage``` is not reflecting  on the**

File : https://www.screencast.com/t/nlYLKtEy
Frontend : https://www.screencast.com/t/lmD3HgQO

Regards

**Comment by GhaziTriki** [comment]
In your case the welcome message have been set by your integration, as example if you are using Greenlight. In order to force the BigBlueButton server values the `create` call has to not contain the `welcomeMessage` property.
