### ISSUE TITLE
Userdata Parameter Don't work in version 2.2.9

### ISSUE THREAD

**Issue by rriscado** [bigbluebutton/bigbluebutton#9375]
**Describe the bug**
The following parameters don't work in version 2.2.9  when join as attendee.
userdata-enableVideo=false
userdata-forceListenOnly=true

Fyi: I used version 2.2.3 where it works. Between version 2.2.4 and 2.2.9 this problem started to happen.

**To Reproduce**

After installing a clean version 2.2.9, these parameters are no longer accepted

I also tested using https://mconf.github.io/api-mate/ with the server/LB http://test-install.blindsidenetworks.com/bigbluebutton/api

The behavior is the same.

1- Create a room 
`http://test-install.blindsidenetworks.com/bigbluebutton/api/create?allowStartStopRecording=true&attendeePW=ap&autoStartRecording=false&meetingID=random-5676280&moderatorPW=mp&name=random-5676280&record=false&voiceBridge=73740&welcome=%3Cbr%3EWelcome+to+%3Cb%3E%25%25CONFNAME%25%25%3C%2Fb%3E%21&checksum=b023833c46de5bf5bbaf94a1648369bd5d1ded60`

2-join as moderator
`http://test-install.blindsidenetworks.com/bigbluebutton/api/join?fullName=User+3342843&meetingID=random-5676280&password=ap&redirect=true&checksum=5b8ee468d6a87dd3e7405e4aa36a6f659d16facd`

3- join as attendee with parameters
`http://test-install.blindsidenetworks.com/bigbluebutton/api/join?fullName=User+3342843&meetingID=random-5676280&password=ap&redirect=true&checksum=5b8ee468d6a87dd3e7405e4aa36a6f659d16facd`

**Screenshots**
![image](https://user-images.githubusercontent.com/14829973/80808471-05fc5680-8b96-11ea-9644-419b64fb39f2.png)

In this test server we have the problem. https://m023.rna1.blindsidenetworks.com/html5client/join?sessionToken=rt3n4jv6ghf3myid
![image](https://user-images.githubusercontent.com/14829973/80809898-0a763e80-8b99-11ea-9a28-943e6c59db12.png)
![image](https://user-images.githubusercontent.com/14829973/80809972-34c7fc00-8b99-11ea-9e2b-a7253ff6bf21.png)
![image](https://user-images.githubusercontent.com/14829973/80810046-5a550580-8b99-11ea-9336-400a8fd74a32.png)

In this test server we don't have the problem. https://t023.rna1.blindsidenetworks.com/html5client/join?sessionToken=rt3n4jv6ghf3myid
![image](https://user-images.githubusercontent.com/14829973/80809172-7ce61f00-8b97-11ea-801b-405efc684629.png)

**Comment by rriscado** [comment]
Reviewing the commits from version 2.2.4 to version 2.2.9, I believe the problem was introduced in version 2.2.7, by the commit https://github.com/bigbluebutton/bigbluebutton/commit/7eb935f244bddb1d4ac4af63362de6be910037ee.

In line 240 of the following Log file, we can observe an error in the call to the addUserSettings function.
[error.txt](https://github.com/bigbluebutton/bigbluebutton/files/4577683/error.txt)

**Comment by tdjac0bs** [comment]
Hello @jfsiebel it seems we need to make client wait for the validateAuthToken response before calling the addUserSettings.

Can you fix this ASAP?
