### ISSUE TITLE
user settings in freeswitch should be persistant independent from new versions

### ISSUE THREAD

**Issue by ReimarBauer** [bigbluebutton/bigbluebutton#9376]
**Is your feature request related to a problem? Please describe.**
on each update based on freeeswitch my comments gets cleared to enabeld
e.g. 
```
 
      <!-- <param name="muted-sound" value="conference/conf-muted.wav"/> -->
      <!-- <param name="unmuted-sound" value="conference/conf-unmuted.wav"/> -->
```

**Describe the solution you'd like**
User configs separated from system default settings or an additonal user config file which will be respected on writing a new config file.

Also an option in  the properties file would be great to just setup this feature.

**Describe alternatives you've considered**
Currently I always have to repeat my changes in /opt/freeswitch/etc/freeswitch/autoload_configs/conference.conf.xml

**Comment by bwurst** [comment]
Persistent config files would be good for some sort of configs from BBB. But the way to go at the moment is a script named apply-config.sh as described here: https://docs.bigbluebutton.org/2.2/customize.html#automatically-apply-configuration-changes-on-restart

**Comment by antobinary** [comment]
Merging into https://github.com/bigbluebutton/bigbluebutton/issues/12791
