### ISSUE TITLE
Style `guest-wait.html`

### ISSUE THREAD

**Issue by MarcelWaldvogel** [bigbluebutton/bigbluebutton#9378]
**Is your feature request related to a problem? Please describe.**
When a guest joins a room with moderator approval, she only sees a 1990's-style "Please wait for a moderator to approve you joining the meeting" message without any styling. On bigger screens, this will look as if the screen went blank. Independent of the screen size, it looks pretty uninviting, not what a lobby should look like.

**Describe the solution you'd like**
Have the room styled at least minimally, with both the title visible (e.g., should go to the `banner` `div`) and the message.

**Describe alternatives you've considered**
The style could be hard-coded or referenced to an external CSS file.

**Additional context**
Sketch idea for which I could provide a pull request, if desired:
![styled guest-wait with spinner](https://user-images.githubusercontent.com/3014737/80820147-a4101100-8bd6-11ea-8349-aa99eec1baff.png)

**Comment by mrkeksi** [comment]
See here: #9271
