### ISSUE TITLE
How to change/add new fonts in html5

### ISSUE THREAD

**Issue by mosyBG** [bigbluebutton/bigbluebutton#9381]
Hello
i need to help to add some fonts persian for HTML5 client.
anyone knows that how could be do that?
webpack fonts like ttf,eot,woff files.
its Great to change it.

Thanks alot.

**BBB version (2.2.6 (1871)):**

 - OS: [ Windows]
 - Browser [ Chrome]
 - Version [71]

**Comment by mosyBG** [comment]
any idea ?

**Comment by 19chetan** [comment]
I too have also have same issue any idea ?

**Comment by emadbagheri96** [comment]
same here

**Comment by emadbagheri96** [comment]
Found this one:
https://github.com/bigbluebutton/bigbluebutton/issues/5836#issuecomment-612542144
If you tried it for changing font, tell me if it worked or not!
