### ISSUE TITLE
HOW TO STREAM SINGLE WEBCAM VIA RTMP

### ISSUE THREAD

**Issue by SUONOVIVO** [bigbluebutton/bigbluebutton#9382]
Hi, i install bbb in one of my server and now I’m starting interesting on it. I want to stream singolar webcam via rtmp to create a personal streaming layout.

**Comment by lonesomewalker** [comment]
Writing everything in CAPS is kinda rude...

Also, if you want to stream only a single cam, there are other projects which might fit better.

**Comment by basisbit** [comment]
For support requests, please use the [forum / mailing list](https://groups.google.com/forum/#!forum/bigbluebutton-users). This issue tracker here is only for BBB development related issues. Sorry.
