### ISSUE TITLE
Impossible to have more than 21 shared webcams 

### ISSUE THREAD

**Issue by EdwinZuck** [bigbluebutton/bigbluebutton#9384]
I have a good bbb server with 8 cores, 8  GB RAM, and 2 Gbps symetric line.
With 30 users, we can only reach a max of 21 visible shared webcams.
The 22th, 23th, ... users can not launch camera.

In the server, Bandwidth, RAM and CPU are not full at all. Only 2 cores on 8 are used.

How can I increase the visible webcams ?
I put a bitrate of 50 for : low, medium, high and high definition, but I still can not have more than 21 webcams.

Thanks for your help

**Comment by Sea444** [comment]
We noticed that only 15-20 webcams are possible in normal use. Maybe the server could handle more webcams, but client hardware cant't. With only 10 Webcams many notebooks are at 100 % CPU. BBB isn't optimized for showing many webcams at same time. I'm telling my collegues: It's a webinar software with videoconference function, not a real videoconference software.

**Comment by ffdixon** [comment]
Don't tell these guys :-)

  https://twitter.com/maemst/status/1254001842679357440

**Comment by Sea444** [comment]
> Don't tell these guys :-)
> 
> https://twitter.com/maemst/status/1254001842679357440

Hehe, yeah, know this screenshot. I asked them how they managed to show 50 webcams in BBB. They told me it was just last minute for the screenshot. But still impressive. :-)

**Comment by EdwinZuck** [comment]
Concretely, if I have a group of 30 people who want to share webcam, they all need to have a good hardware client ? Which kind of hardware do they need ?

**Comment by kinimodmeyer** [comment]
yeah and a really good bandwidth

**Comment by raoulkramer** [comment]
A applicable solution to have bigger conferences could be this option https://github.com/bigbluebutton/bigbluebutton/issues/9392

**Comment by prlanzarin** [comment]
Merging with https://github.com/bigbluebutton/bigbluebutton/issues/9392.
