### ISSUE TITLE
Webcam Configuration Question

### ISSUE THREAD

**Issue by itr001** [bigbluebutton/bigbluebutton#9385]
I'm trying to remove the camera on the students view to make the presentation the maximum size upon entering the classroom. I already set it up to restrict them from seeing eachother's webcameras so I just need to remove the last camera view which is their own. Can someone help me with this?

**Comment by rriscado** [comment]
TurnOff or Disable your webcam.

**Comment by itr001** [comment]
It is not my camera that I'm trying to remove from their view. It is their
own. I need to be able to see them so their camera automatically turns on.
On their view they can see themselves at the top. However this decreases
the presentation size. How do I turn it off on their screen? So the
presentation is maximized upon start.
