### ISSUE TITLE
Audio Conferencing Issue - 1004, Working fine a few days ago, but not for now!

### ISSUE THREAD

**Issue by Happy-2020** [bigbluebutton/bigbluebutton#9389]
Hi,
I have rent my own dedicated hosting server and have installed BBB on it. Everything was fine till today, but morning, I am seeing it is giving me Issue-1004, and don't allow me to do audio call.
I searched this forum and couldn't solve this issue till now.
From my laptop, its working fine to demo app provided by BBB team, So its no problem related to an firewall or so.
Its only issue related to my own server.

Please someone kindly give me advice how I can sort this out!
Thanks

**Comment by sebaro11** [comment]
Hey I had the same error 1004 some time ago and that helped me fixing it:
https://github.com/bigbluebutton/bigbluebutton/issues/9088#issuecomment-624206690
