### ISSUE TITLE
Use Internal FreeSwitch for bbb in local interanet

### ISSUE THREAD

**Issue by ghaseminya** [bigbluebutton/bigbluebutton#9390]
Hi,
Can use BBB in internet without internet access?
I think this can be done if run Freeswitch in local network?
Is this idea true?
Thanks

**Comment by m-nik** [comment]
Hi,
Yes, I practiced it. but for first practice you must resolve some annoying problems in this way.

**Comment by klepptor** [comment]
@m-nik Could you share your information on using BBB in an intranet only, please? There's no official documentation about this and I can't figure out some of the problems. In my environment (BBB 2.2.17 in a VMware 6.7 VM with certs from own local CA) audio/video works fine, but no presentation (not even the default) is shown in the browser althought it's successfully converted and the number of pages/slides is correct).

**Comment by klepptor** [comment]
bbb-conf --debug shows a lot of this:

`Jun 10 08:50:03 zpsbbbt02 run-prod.sh[6312]: 2020-06-10T08:50:03.084+02:00 WARN  i.l.c.protocol.ConnectionWatchdog - Cannot reconnect: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: /127.0.0.1:6379`

**Comment by klepptor** [comment]
Ok, I solved my problems and now BBB and Greenlight work like a charm in my LAN with our own CA. All problems were about own certs and how to tell nginx, node.js and Ruby (GL) how to use them.

There is a nice howto [here](https://wiki.linuxmuster.net/community/anwenderwiki:webapps:bigbluebutton), but in german.
