### ISSUE TITLE
ffmpeg parsed movie not found

### ISSUE THREAD

**Issue by bluemmb** [bigbluebutton/bigbluebutton#9393]
**Describe the bug**
Some of our recordings keep giving the same error in log even after trying to rebuild them.

**To Reproduce**
( It happens some times for recorded classes )

**Expected behavior**
The recordings get published

**Actual behavior**
Some of them are giving the same error

**Screenshots**
![Screenshot from 2020-05-03 02-08-59 - 1](https://user-images.githubusercontent.com/7195720/80892931-3f8ea800-8ce3-11ea-882b-2d0fc571d8c7.png)

**Server (please complete the following information):**
 - OS: Ubunut 16.04.6
 - Version: 2.2.0-rc-3

**More description**
The same error at the same line of codes keeps happening for some other recordings

**Comment by amkyp** [comment]
Hi
- How did you try to build the videos agian?
- Try to use the installation of BBB-Script one more time and It should be okay, I think.
`wget -qO- https://ubuntu.bigbluebutton.org/bbb-install.sh | bash -s -- -v xenial-220 -s example.com -e example@example.example -g`
It works for me.

**Comment by bluemmb** [comment]
> Hi
> 
>     * How did you try to build the videos agian?
> 
>     * Try to use the installation of BBB-Script one more time and It should be okay, I think.
>       `wget -qO- https://ubuntu.bigbluebutton.org/bbb-install.sh | bash -s -- -v xenial-220 -s example.com -e example@example.example -g`
>       It worked for me.

Hi

* With command `bbb-record --rebuild ID`
* You mean I should upgrade to newer versions? (we have customized UI and it may cause problems)

Did you have the same error ?

**Comment by amkyp** [comment]
Hi
- Version 2.2.10 is out now, So and they are some improvements, I recommend you to upgrade with that script, I had the same error,  and just Fixed by bootstrapping once again with an upgrade.
- for UI, you can backup the pages you made some changes to and replace them after upgrading.

**Comment by GhaziTriki** [comment]
Considered as resolved.
