### ISSUE TITLE
Playback speed control

### ISSUE THREAD

**Issue by aozalevsky** [bigbluebutton/bigbluebutton#9395]
It would be very nice to have the ability to switch the records playback rate (at least our students asked it to be youtube like). 

![playback_rate](https://user-images.githubusercontent.com/578484/80908043-2c043100-8d25-11ea-98c3-85f0ce050a10.png)

Maybe you could point me towards the point, where I should inject standard HTML5 speed control, so that presentation and chat will still be synced with the video?

**Comment by pedrobmarin** [comment]
We have a new playback beta that support that feature:
![full](https://user-images.githubusercontent.com/1778398/81025008-a29b4e80-8e4b-11ea-8e87-6873bbf5b275.png)
https://github.com/pedrobmarin/bbb-playback if anyone wants to try it out

**Comment by aozalevsky** [comment]
@pedrobmarin looks awesome! I think it resolves the request for me. I have one critical issue, though.  But I'll report it to your repo.

**Comment by NeuroAnna** [comment]
@pedrobmarin Thank you for implementing, it is really very important feature (my students are crying for it). Will it be integrated in the next BBB release? (When?) I am using a University instance and they probably will only update to an official release.

**Comment by pedrobmarin** [comment]
@NeuroAnna this might be released with bigbluebutton version 2.3 but I can't really tell you a precise date for that.

**Comment by tom-doerr** [comment]
Hi, is this already released? Would be amazing to get this soon.

**Comment by pedrobmarin** [comment]
https://github.com/bigbluebutton/bbb-playback/releases/tag/v2.3.1 should be good to go for BigBlueButton 2.2.X recordings. With some extra nginx juggling you can set it up to work with 2.2 recordings URLs. Something like:
```
location /playback/presentation/2.0/playback.html {
  return 301 /playback/presentation/2.3/$arg_meetingId?$query_string;
}

location /playback/presentation/2.3 {
  root /var/bigbluebutton;
  try_files $uri /playback/presentation/2.3/index.html;
}
```

**Comment by canklot** [comment]
You can install this extension and speed up the playback : [](https://chrome.google.com/webstore/detail/html5-video-speed-control/ibgbkojmhhoobdapmkofkbhglahnpddk/related?hl=tr)

**Comment by antobinary** [comment]
The playback @pedrobmarin mentioned is included in https://github.com/bigbluebutton/bigbluebutton/releases/tag/v2.3-alpha-4
