### ISSUE TITLE
Question: Disabling presentation component in HTML5 client

### ISSUE THREAD

**Issue by sviva** [bigbluebutton/bigbluebutton#9397]
Hello,
I am trying to configure BBB for a use-case where a presentation is not needed and the content that the students will need to see is provided over webcam.  

I have accessed the configuration file at `/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml`
and set `hidePresentation: true`. 
This helps, but the meeting still shows a dotted outline with the text "Your presentation will begin shortly...".  This dotted outline always seems to take up space on the screen, even when the webcam is pulled as large as possible.  Is there anyway to completely disable this presentation module and make the webcam front-and-center?  

Additionally, it would be great if I could set the default webcam view size on client startup, so that clients see the webcam image larger without having to resize the module.

I would really appreciate any help with these issues, and I can imagine there are others who have use-cases like mine who could also benefit from this.

My apologies if I've missed something in the docs.

Thank you in advance for any help,
Sam

**Comment by basisbit** [comment]
Set `autoSwapLayout: true` - that should solve your problem when you already have `hidePresentation: true`.

**Comment by sviva** [comment]
> Set `autoSwapLayout: true` - that should solve your problem when you already have `hidePresentation: true`.

Thank you for the reply.  I have set autoSwapLayout to true, and this has resulted in my webcam being larger by default which is good.  However, I still see this outline for the presentation and it is now overlayed on top of the webcam stream (see the attached picture).
![remove-pres-2](https://user-images.githubusercontent.com/55019386/80963553-719d2880-8e0f-11ea-86de-d685cfc294ad.PNG)

Thanks in advance for any further help,
Sam

**Comment by basisbit** [comment]
As far as I know, that should be fixed in the latest release of BigBlueButton (v2.2.9) what version of BigBlueButton are you using? `bbb-conf --check | grep "BigBlueButton Server"`

**Comment by sviva** [comment]
> As far as I know, that should be fixed in the latest release of BigBlueButton (v2.2.9) what version of BigBlueButton are you using? `bbb-conf --check | grep "BigBlueButton Server"`

`BigBlueButton Server 2.2.9 (1891)`

**Comment by basisbit** [comment]
In that case, this is a regression -> bug.
Could you please close this issue here (as it was solved with `autoSwapLayout`), then create a new issue for that bug report and also mention in the title that it is a regression?

**Comment by sviva** [comment]
> In that case, this is a regression -> bug.
> Could you please close this issue here (as it was solved with `autoSwapLayout`), then create a new issue for that bug report and also mention in the title that it is a regression?

I will do that. Thanks.
