### ISSUE TITLE
bbb ldap roles

### ISSUE THREAD

**Issue by bseidenspinner** [bigbluebutton/bigbluebutton#9401]
With every login the role is assigned to the user again, but this should only be assigned once.

![Selection_185](https://user-images.githubusercontent.com/38077237/80952541-1a408d80-8dfa-11ea-91cc-508340c8e6bf.jpg)

**Comment by amkyp** [comment]
Hi
- Can u give me any instruction of connecting BBB to LDAP? (or give me any way to contact you for response)
- There is another modern solution out there, called KeyCloak, Any idea of how to integerate that with BBB?

**Comment by bseidenspinner** [comment]
http://docs.bigbluebutton.org/greenlight/gl-config.html#ldap-auth

**Comment by GhaziTriki** [comment]
Related to https://github.com/bigbluebutton/greenlight
