### ISSUE TITLE
Two more entries for "bbb-conf --setip"

### ISSUE THREAD

**Issue by testerik** [bigbluebutton/bigbluebutton#9403]
While moving a BBB server to an other subnet I had to update to the new IP address in two files even after the command "bbb-conf --setip [new.name.domain]":

/etc/bigbluebutton/nginx/sip.nginx
        proxy_pass https://[old IP address]:7443;

/opt/freeswitch/etc/freeswitch/vars.xml
       &lt;X-PRE-PROCESS cmd="set" data="local_ip_v4=[old IP address]"/&gt;

I think it would be a good idea if "bbb-conf --setip" updates these entries (or at least emphasizes this for the admin).

**Comment by ikanashov** [comment]
And another two place

/usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml
localIpAddress: [oldip -> newip]

/usr/share/red5/webapps/sip/WEB-INF/bigbluebutton-sip.properties
bbb.sip.app.ip=[oldip -> newip]
freeswitch.ip=[oldip -> newip]

**Comment by matiasilva** [comment]
Do feel free to submit a pull request if you can. The file is this one: https://github.com/bigbluebutton/bigbluebutton/blob/develop/bigbluebutton-config/bin/bbb-conf
