### ISSUE TITLE
apply-config.sh does not run on reboot, only on bbb-conf --restart

### ISSUE THREAD

**Issue by odenbach** [bigbluebutton/bigbluebutton#9409]
**Describe the bug**
We use a cluster of BBB servers. We use a config deployment tool to make sure all servers have the same config (using apply-config.sh in this case). If however apply-config.sh gets changed and the server reboots, the new config still does not take place. We still need to run bbb-conf --restart.

**To Reproduce**
Change apply-config.sh
Reboot

**Expected behavior**
Configs are updated according to apply-config.sh

**Actual behavior**
Configs are NOT updated until one runs bbb-conf --restart

**Comment by basisbit** [comment]
where did you read that `apply-config.sh` is supposed to run on reboot? That documentation probably just has to be changed. As far as I know, the `apply-config.sh` script gets executed each time you run `bbb-conf --restart` or `bbb-conf --setip your.domainname.tld`.
After every update-install you should execute `bbb-conf --setip your.domainname.tld` as mentioned in the documentation.
Hope this helps.

**Comment by odenbach** [comment]
I did not read that, I just expected it. bbb-conf --restart seems to handle starting the service, so I expected the same mechanism being called at a reboot. If that is not the case, then I just got my expectations wrong.

Thanks,

Christopher

**Comment by GremL1N** [comment]
you can use crontab
`@reboot root /patho/to/apply-config.sh`
