### ISSUE TITLE
Regression: outline for presentation still appearing with hidePresentation: true and autoSwapLayout: true

### ISSUE THREAD

**Issue by sviva** [bigbluebutton/bigbluebutton#9410]
**Describe the bug**
An outline for a presentation is obstructing the webcam view with
`hidePresentation: true` and `autoSwapLayout: true`

**To Reproduce**
1. Edit `/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml`,
    setting `hidePresentation: true` and `autoSwapLayout: true`
2. Save file, restart entire server
3. Start a session and enable webcam
4. See error (see screenshot below)

**Expected behavior**
My use-case does not need the presentation function, only the webcam function.
I was trying to disable the presentation module so that it would not take up space in the client 
and so that the webcam views could be larger.
I would expect the presentation outline to be removed when `hidePresentation: true` and `autoSwapLayout: true`

**Actual behavior**
Please see description above and screenshot below

**Screenshots**
![remove-pres-2](https://user-images.githubusercontent.com/55019386/80976777-24778180-8e24-11ea-8e1a-879e170d1207.PNG)

**BBB version:**
$ sudo bbb-conf --check | grep BigBlueButton
BigBlueButton Server 2.2.9 (1891)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 81.0.4044.129

**Comment by pcburcham** [comment]
I can confirm this same behavior running the same BBB server build, using the same desktop client and  Chrome build. Mobile client running Android 10 on Chrome 81.4044.117 as well.

**Comment by sviva** [comment]
Thanks for providing additional info.

If anyone has any ideas for a workaround in the short-term I would appreciate it, as this issue is affecting the client experience on my server.

**Comment by pcburcham** [comment]
> Thanks for providing additional info.
> 
> If anyone has any ideas for a workaround in the short-term I would appreciate it, as this issue is affecting the client experience on my server.

Not a proper solution, as I'm sure you understand, but if you are in a fix you could add:
`[class*="hideOverlay--"] {
        display: none !important;
    }`
just before the </style> tag to head.html in /usr/share/meteor/bundle/programs/web.browser 
then restart and verify

I'll have to get home so I can load up the client in dev environment, but it looks like a styling issue at a glance

**Comment by sviva** [comment]
> Not a proper solution, as I'm sure you understand, but if you are in a fix you could add:
> [class*="hideOverlay--"] { display: none !important; }
> just before the </style> tag to head.html in /usr/share/meteor/bundle/programs/web.browser -- yes, include the [ ] above
> then restart and verify

This worked for me, thank you very much.

**Comment by antobinary** [comment]
The issue is resolved if these are settings.yml changes but it is still an issue if the following params are passed: 
userdata-bbb_hide_presentation=true
userdata-bbb_auto_swap_layout=true
