### ISSUE TITLE
Secret changes after upgrade

### ISSUE THREAD

**Issue by odenbach** [bigbluebutton/bigbluebutton#9412]
**Describe the bug**
After upgrading our BBB servers from 2.2.6 to 2.2.9 the secret has changed. This requires re-registration in greenlight or scalelite.

**To Reproduce**
Upgrade bbb

**Expected behavior**
Secret stays the same

**Actual behavior**
Secret changes

**Comment by bwurst** [comment]
This is not reproducable with a setup installed by bbb-install.sh. I upgraded some steps via apt-get upgrade and did bbb-conf --restart afterwards and everything is fine. Secret did not change.

Please clarify which steps you took for install and upgrade.

**Comment by odenbach** [comment]
Hi,

I think I upgraded all packages via apt-get upgrade. As there also was a kernel update I rebooted first, then ran `bbb-conf --setip`. Maybe that was the problem.

Couldn't you include `bbb-conf --restart `in the postinst script of the last package? That would make the upgrade foolproof.

**Comment by lonesomewalker** [comment]
We have several installations and this never happened.
Maybe you plan your upgrades better next time...?

**Comment by basisbit** [comment]
@odenbach thank you for this bug report! Did this problem happen again for the other recent BBB updates?

**Comment by odenbach** [comment]
Not the recent ones. I remember one more time this happened on another server but I don't remember which version this server had before. Since I always do a `bbb-conf --setip` after upgrading the packages, everything is fine.
