### ISSUE TITLE
Whiteboard Pencil/pen lines disappear

### ISSUE THREAD

**Issue by Salamit** [bigbluebutton/bigbluebutton#9413]
**Describe the bug**
I try to write with the pencil. I hold down the mouse and draw a line and after releasing the mouse, the line I just drew disappears.

**To Reproduce**
1. Select the pencil tool 
2. Hold the mouse down to draw a line. 
3. Release the mouse 
4. Line you just drew disappears

**Expected behavior**
I expected the line I just drew to stay on the whiteboard after releasing the mouse.

**Actual behavior**
The line I drew disappeared just after drawing it and releasing the mouse.

**Screenshots**

**BBB version (optional):**
BigBlueButton Server 2.2.9 (1891)

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser: Chrome
 - Version: 10.15.4 

Thank you!

**Comment by Salamit** [comment]
![F1A7E87D-4A5E-48A0-BF87-B4CB790E9C51](https://user-images.githubusercontent.com/12544262/81122365-b50ca980-8f6b-11ea-8eaa-89cf22a58399.GIF)

**Comment by aakatev** [comment]
Seems like same issue as #9067.
@ffdixon Is there any updates on when 2.3 is going to be released?

**Comment by Salamit** [comment]
@aakatev Thanks a mil!

**Comment by dev-1996** [comment]
@ffdixon @aakatev  I am facing the same issue. Lines drawn from pencil tool are not sticking. BigBlueButton Server 2.2.3 (1833) and in bbb-html5's settings.yml file bbbServerVersion: 2.2-dev
Thanks in advance.
