### ISSUE TITLE
Error: 1020 while sharing camera

### ISSUE THREAD

**Issue by kGolsky** [bigbluebutton/bigbluebutton#9416]
**Describe the bug**
After installing BigBlueButton (_fresh installation_) it is not possible to share my WebCam. Every time "share webcam" is invoked, after a while there is a notification saying: "_Media could not reach the server (error 1020)_". This is also worth to mention that audio works fine in Opera, Chrome and Edge Chromium but it does not in Firefox returning the error: "_Call timed out (error 1006)_" but lets focus first on the camera.

**To Reproduce**
At the beginning i would like to mention that all instructions i followed come from: _https://docs.bigbluebutton.org_
 - I started my journey with BBB from "_Step-by-step_" (installed BBB and configured a domain name, ssl etc.) 
 - Then, as my server is placed behind  NAT & firewall I followed the instruction: "_Configure Firewall_"
 - Next, because Firewall configuration & directing to a proper StunServer were not helped me with sorting out the error 1020, i followed: "_Configure TURN_" to install and set up the Coturn server.

**Expected behavior**
Sharing audio & video works for internal and external clients without showing any errors / notifications

**Desktop (please complete the following information):**
Server: 4 Cores 8GB RAM, OS:
- Ubuntu 16.04 xenial LTS
- Build-in Firewall disabled

Firewall (opened ports):
- TCP/IP ports 80/443
- TCP/UDP: 3478, 5349, 7443
- UDP/TCP ports in the range 16384 - 65535 (for FreeSWITCH/HTML5 RTP streams and Coturn, TCP included to make sure 1020 is not related to FW)
	
Browsers (client side):
- Microsoft Edge Version 83.0.478.18 (Official build) beta (64-bit)
- Opera Version:68.0.3618.63
- Firefox 75.0 (64-bit)

**Additional context**
Based upon bbb-webrtc-sfu posted below, it looks like Candidate's pair was picked up and then after a while the session was stopped (can not figure out why it happened). The same happens if I use public Stun only without using my Stun / Turn. 
In addition, BBB & Coturn were installed on the same server. I read that they may use similar port ranges, what do you think? Should i moved COturn out to a dedicated client?
I am happy to share more configuration, traces or data  if needed. Thank you in advance. 

**Screenshots**
My configuration:
 - WebRtcEndpoint.conf.ini : 
          externalAddress=external_ip
          stunServerAddress=64.233.164.127
          stunServerPort=19302

- turnserver.conf
          listening-port=3478
          tls-listening-port=5349
          external-ip=external_ip
          fingerprint
          lt-cred-mech
          use-auth-secret
          static-auth-secret=my_secret
          realm=mydomain.name
          cert=/etc/letsencrypt/live/mydomain.name/fullchain.pem
          pkey=/etc/letsencrypt/live/mydomain.name/privkey.pem
          cipher-list="ECDH+AESGCM:ECDH+CHACHA20:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:RSA+AESGCM:RSA+AES:!aNULL:!MD5:!DSS"
          dh2066
          log-file=/var/log/turn.log
          simple-log
          no-tlsv1
          no-tlsv1_1

Output of bbb-conf --check

	BigBlueButton Server 2.2.5 (1864)
						Kernel version: 4.4.0-178-generic
						  Distribution: Ubuntu 16.04.6 LTS (64-bit)
								Memory: 16615 MB
							 CPU cores: 8

	/usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties (bbb-web)
		   bigbluebutton.web.serverURL: https://mydomain.name
					defaultGuestPolicy: ALWAYS_ACCEPT
					 svgImagesRequired: true

	/etc/nginx/sites-available/bigbluebutton (nginx)
						   server name: mydomain.name
								  port: 80, [::]:80
								  port: 443 ssl
						bbb-client dir: /var/www/bigbluebutton

	/var/www/bigbluebutton/client/conf/config.xml (bbb-client)
					Port test (tunnel): rtmp://mydomain.name
								  red5: mydomain.name
				  useWebrtcIfAvailable: true

	/opt/freeswitch/etc/freeswitch/vars.xml (FreeSWITCH)
						   local_ip_v4: local_ip
					   external_rtp_ip: external_ip
					   external_sip_ip: external_ip

	/opt/freeswitch/etc/freeswitch/sip_profiles/external.xml (FreeSWITCH)
							ext-rtp-ip: external_ip
							ext-sip-ip: external_ip
							ws-binding: :5066
						   wss-binding: :7443

	/usr/local/bigbluebutton/core/scripts/bigbluebutton.yml (record and playback)
						 playback_host: mydomain.name
					 playback_protocol: https
								ffmpeg: 4.2.2-1bbb1~ubuntu16.04

	/etc/bigbluebutton/nginx/sip.nginx (sip.nginx)
							proxy_pass: external_ip

	/usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml (Kurento SFU)
							kurento.ip: external_ip
						   kurento.url: ws://127.0.0.1:8888/kurento
						localIpAddress: local_ip
				   recordScreenSharing: true
						 recordWebcams: true
					  codec_video_main: VP8
				   codec_video_content: VP8

	/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml (HTML5 client)
								 build: 874
							kurentoUrl: wss://mydomain.name/bbb-webrtc-sfu
					  enableListenOnly: true

	# Potential problems described below
	# IP does not match:
	#                           IP from ifconfig: local_ip
	#   /etc/nginx/sites-available/bigbluebutton: mydomain.name
	# Warning: API URL IPs do not match host:
	#
	#                                IP from ifconfig: local_ip
	#  /var/lib/tomcat7/demo/bbb_api_conf.jsp: mydomain.name

	# Warning: The setting of external_ip for proxy_pass in
	#
	#    /etc/bigbluebutton/nginx/sip.nginx
	#
	# does not match the local IP address (local_ip).
	# (This is OK if you've manually changed the values)

	# Warning: The API demos are installed and accessible from:
	#
	#    https://mydomain.name
	#
	# and
	#
	#    https://mydomain.name/demo/demo1.jsp
	#
	# These API demos allow anyone to access your server without authentication
	# to create/manage meetings and recordings. They are for testing purposes only.
	# If you are running a production system, remove them by running:
	#
	#    apt-get purge bbb-demo

While i am trying to share my camera the following lines are written in bbb-webrtc-sfu/bbb-webrtc-sfu.log and turn.log, I have attached both files:
 - [bbb-webrtc-sfu.log](https://github.com/bigbluebutton/bigbluebutton/files/4577087/bbb-webrtc-sfu.log)
 - [turn.log](https://github.com/bigbluebutton/bigbluebutton/files/4577088/turn.log)
- [turn-stun-servers.txt](https://github.com/bigbluebutton/bigbluebutton/files/4577103/turn-stun-servers.txt)

**Comment by prlanzarin** [comment]
Can you please trim down your turn-stun-servers's TURN config to use only turn1 and turn2 or turn3 and turn4, restart bbb-web and try it again? Just to trim down some stuff before further debugging.

**Comment by PatrickHurley75** [comment]
This is a known issue that happens to a very small minority of BBB servers. It is becuase your server is behind some weird double NAT, like mine. 

There is a relatively easy solution to this but it will require the use of a second turnserver.

You must point the turnserver from turn-stun-server to one turn server using lt-cred-mech and  the WebRTCEndpoint file to the other turn server on use-auth-secret.

Unfortunately, it seems to be the only solution for those of us behind double NAT with users also behind firewalls. 

I have suggested a solution of sharing turnservers, for users who find themselves in this situation.

Any other potential sharers would be most welcome to contact me., or comment here.

It would solve the immediate issue.

**Comment by kGolsky** [comment]
> Can you please trim down your turn-stun-servers's TURN config to use only turn1 and turn2 or turn3 and turn4, restart bbb-web and try it again? Just to trim down some stuff before further debugging.

Hi prlanzarin, 

Many thanks for the prompt reply. Stun's lines commented. Keep getting the error 1020 while sharing the camera. I have attached two logs

- [bbb-webrtc-sfu.log](https://github.com/bigbluebutton/bigbluebutton/files/4582386/bbb-webrtc-sfu.log)

- [turn.log](https://github.com/bigbluebutton/bigbluebutton/files/4582387/turn.log)

This is what i see now in the http request to confirm that Stun's configuration was excluded: 

stunServers: [],…}
remoteIceCandidates: []
stunServers: []
turnServers: [{username: "1588783910:w_vweoxwmexozq", password: "4j05n0v4NRUn4ID/h9yDu5ssmxY=",…},…]

- 0: {username: "1588783910:w_vweoxwmexozq", password: "4j05n0v4NRUn4ID/h9yDu5ssmxY=",…}
password: "4j05n0v4NRUn4ID/h9yDu5ssmxY="
ttl: 86400
url: "turns:external_ip:5349?transport=tcp"
username: "1588783910:w_vweoxwmexozq"

- 1: {username: "1588783910:w_vweoxwmexozq", password: "4j05n0v4NRUn4ID/h9yDu5ssmxY=",…}
password: "4j05n0v4NRUn4ID/h9yDu5ssmxY="
ttl: 86400
url: "turn:external_ip:5349?transport=tcp"
username: "1588783910:w_vweoxwmexozq"

- 2: {username: "1588783910:w_vweoxwmexozq", password: "4j05n0v4NRUn4ID/h9yDu5ssmxY=",…}
password: "4j05n0v4NRUn4ID/h9yDu5ssmxY="
ttl: 86400
url: "turns:external_ip:3478?transport=tcp"
username: "1588783910:w_vweoxwmexozq"

- 3: {username: "1588783910:w_vweoxwmexozq", password: "4j05n0v4NRUn4ID/h9yDu5ssmxY=",…}
password: "4j05n0v4NRUn4ID/h9yDu5ssmxY="
ttl: 86400
url: "turn:external_ip:3478?transport=udp"
username: "1588783910:w_vweoxwmexozq"

Thank you in advance

**Comment by prlanzarin** [comment]
Sorry, I was not clear enough @kGolsky. I meant for you to remove one of the two TURN pairs you were using (and leave the STUN on). Can you try it again, please, following the example below? Thanks.
Example: 
```
			<property name="stunServers">
				<set>
					<ref bean="stun1" />
				</set>
			</property>
			<property name="turnServers">
				<set>
					<ref bean="turn1" />
					<ref bean="turn2" />
```

**Comment by kGolsky** [comment]
> Sorry, I was not clear enough @kGolsky. I meant for you to remove one of the two TURN pairs you were using (and leave the STUN on). Can you try it again, please, following the example below? Thanks.
> Example:
> 
> ```
> 			<property name="stunServers">
> 				<set>
> 					<ref bean="stun1" />
> 				</set>
> 			</property>
> 			<property name="turnServers">
> 				<set>
> 					<ref bean="turn1" />
> 					<ref bean="turn2" />
> ```

ohh my bad, I am sorry.. doing that now

**Comment by kGolsky** [comment]
I apologize once again, i have attached fresh logs below , this is what was recorded in the http request:

        {stunServers: [{url: "stun:external_ip"}],…}
        remoteIceCandidates: []
                stunServers: [{url: "stun:external_ip"}]
                        0: {url: "stun:external_ip"}
                                url: "stun:external_ip"
                turnServers: [{username: "1588785538:w_tbr55y0ybjin", password: "weu9wVzQwB+z/Y/ngtig1HqkW44=",…},…]
                        0: {username: "1588785538:w_tbr55y0ybjin", password: "weu9wVzQwB+z/Y/ngtig1HqkW44=",…}
                                password: "weu9wVzQwB+z/Y/ngtig1HqkW44="
                                ttl: 86400
                                url: "turn:external_ip:5349?transport=tcp"
                                username: "1588785538:w_tbr55y0ybjin"

                        1: {username: "1588785538:w_tbr55y0ybjin", password: "weu9wVzQwB+z/Y/ngtig1HqkW44=",…}
                                password: "weu9wVzQwB+z/Y/ngtig1HqkW44="
                                ttl: 86400
                                url: "turns:external_ip:5349?transport=tcp"
                                username: "1588785538:w_tbr55y0ybjin"
[bbb-webrtc-sfu.log](https://github.com/bigbluebutton/bigbluebutton/files/4582638/bbb-webrtc-sfu.log)
[turn.log](https://github.com/bigbluebutton/bigbluebutton/files/4582639/turn.log)

**Comment by kGolsky** [comment]
> This is a known issue that happens to a very small minority of BBB servers. It is becuase your server is behind some weird double NAT, like mine.
> 
> There is a relatively easy solution to this but it will require the use of a second turnserver.
> 
> You must point the turnserver from turn-stun-server to one turn server using lt-cred-mech and the WebRTCEndpoint file to the other turn server on use-auth-secret.
> 
> Unfortunately, it seems to be the only solution for those of us behind double NAT with users also behind firewalls.
> 
> I have suggested a solution of sharing turnservers, for users who find themselves in this situation.
> 
> Any other potential sharers would be most welcome to contact me., or comment here.
> 
> It would solve the immediate issue.

Thanks @PatrickHurley75 
I believe you are right saying "weird double NAT". In our case, these are 3 internal sites connected over VPN. 

Regarding the second TURN server, are there any public (working & reliable) severs available for testing? If not, do you have any recommendations whether that server should be exposed to internet without NAT (VPS) or this can be a client maintained locally with access to internet? 

Thanks

**Comment by marcohald** [comment]
@PatrickHurley75 Can you paste a example config for the two turn servers ?

**Comment by PatrickHurley75** [comment]
Sorry for the delay in getting back. Out of action for a few days. 

I have two turn servers. turn.mydomain.com and turn1.mydomain.com.
The first one has use-auth-secret with secretpassword defined as per setup of turn server with bbb-install.sh
The turn-stun-server.xml file points to this.
I used 
turns:turn.mydomain.com:443?transport=tls for bean 0
turn:turn.mydomain.com:3478?transport=tcp for bean 1
turn:turn.mydomain.com:3478?transport=udp for bean 2

The second turn server has lt-cred-mech defined.
WebRTCEndpoint points to this with newuser:password@turn1.mydomain.com:3478?transport=[tcp,udp,tls]
Use turnadmin to creata a new user:password
turnadmin-a -u newuser -p newpassword -r mydomain.com
Delete the use-auth-secret and secretpassword in turnserver.conf.
use turnserver -c turnserver.conf to check for errors in turnserver.conf
I found that I had to define a cli-password to avoid an error in the configuration. 

so add to turnserver.conf
no-cli
cli-password=anythingatall
 Hope that helps.

**Comment by kGolsky** [comment]
Thank you all for the suggestions submitted so far. It seems that thanks to @PatrickHurley75 we took a step forward with the error 1020. 
I still want to test if adding the second TURN will work however as of now after moving the BBB server to the site with direct access to the gateway (one NAT only) the error 1020 has gone. I assume that in my case error 1020 was caused by as @PatrickHurley75 suggested double NAT or even mistakes in routing.

There is one more question I would like to ask as maybe some of you went already through the similar issue and know how it can be sorted out.
So, after moving the BBB server all browsers started to work except the Firefox (i have the version: 76.0.1 64-bit). FF does not work for both sides: internal and external clients. Again, other browser works fine with the same BBB server. I also tested my FF against https://test.bigbluebutton.org where all tests passed. 
What i noticed was that when i commented configuration set for STUN and TURN in:
- turn-stun-servers.xml
- WebRtcEndpoint.conf.ini
it made that FF started to work for those connecting from LAN. Then i performed another test where only STUN was enabled by changing turn-stun-servers.xml. That resulted that FF and other browsers also worked for local clients however clients (all browser types) trying to connect from WAN kept getting the error ICE 1007.

Based upon the above my conclusion is that my network requires to set both TURN and STUN to get WEBRTC working but for a reason FF does not like or even ignoring TURN servers. 
Another "_finding_" is that when i was initiating connection from FF my Coturn did not log anything. 
 Instead of that i could notice many tries of staring and ending the call. I have attached a few samples captured for that event: 
- [bbb-apps-akka.log](https://github.com/bigbluebutton/bigbluebutton/files/4603547/bbb-apps-akka.log)

Do you know what this would mean? Do you have similar experiences with FF? Does FF really require something more to be configured than this what works for other browsers?

Thank you in advance.

**Comment by congyijun** [comment]
Previously, i have some issue. Now enable the  **externalAddress=public IP address** in **webRtcEndpoint.conf.ini.** And then share the webcam successful.

**Comment by basisbit** [comment]
closing this issue because all the question from the start post were answered. For any further support requests, please use the [forum / mailing list](https://groups.google.com/forum/#!forum/bigbluebutton-setup).

**Comment by werk21** [comment]
I know this ticket is closed. But we had the same problem and the solution was unexpected:

In /etc/kurento/modules/kurento/WebRtcEndpoint.conf were 2 identical lines with externalAddress.
Deleting one of this lines fixed our problem.

We do not know how 2 identical lines were in this file written.
