### ISSUE TITLE
Mouse hover on user list

### ISSUE THREAD

**Issue by jfsiebel** [bigbluebutton/bigbluebutton#9420]
**Describe the bug**
Mouse icons doesn't change when you hover 

**To Reproduce**
1. Hover the mouse on user list

**Expected behavior**
It's expected to behaviour like Shared Notes

**Actual behavior**

**Screenshots**
![mouse-icon](https://user-images.githubusercontent.com/2110278/81028363-68d04500-8e57-11ea-8e2b-28a7c6a0da36.gif)

**BBB version (optional):**
Client build: 894

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Chrome
 - Version: 81.0.4044.129 (Official Build) (64-bit)

**Comment by KDSBrowne** [comment]
#9408 Fixes this
