### ISSUE TITLE
How many users can join a BigBlueButton session and how many rooms can i have open?

### ISSUE THREAD

**Issue by alexperdo** [bigbluebutton/bigbluebutton#9421]
How many people can be in a room of Bigbluebutton, with all users having cameras and audios on ?
Also how many rooms can I have open simultaneously ? With a number X of people in the room

I have in GCP(Google Cloud Plataform) one VM with these characteristics:

**Machine type**
`e2-standard-4 (4 vCPUs, 16 GB memory)`

**Comment by iSamof** [comment]
https://github.com/bigbluebutton/bigbluebutton/issues/9180
https://github.com/bigbluebutton/bigbluebutton/issues/9142
https://github.com/bigbluebutton/bigbluebutton/issues/8801
... and many more

**Comment by texh2s00** [comment]
MAX 5 x 50 people = 250 people. acutaly even with 4vcus 8 gb ram is enougth. We user 5 pcs of  8vcpu 12gb ram server: max good load 20 channel x 40 people per server. No lag,, no disruptions.

**Comment by GhaziTriki** [comment]
Hello,

This is not a bug or a feature request. We would love to see those questions and answers shared with the community in the forums https://groups.google.com/forum/#!forum/bigbluebutton-dev

Thank you
