### ISSUE TITLE
translation of waiting user actions

### ISSUE THREAD

**Issue by mardif** [bigbluebutton/bigbluebutton#9422]
**Describe the bug**
Actions "Accept" and "Deny" are not translated

**To Reproduce**
1. Setting a room with ASK_MODERATOR in guestDefaultPolicy
2. Join as moderator
3. join another session as attendee
4. in the moderator session, watching the waiting list users, for each user there are 2 links: Accept | Deny

**Expected behavior**
These 2 links should be translated

**Actual behavior**
These 2 links are not translated

**BBB version (optional):**
BigBlueButton Server 2.2.9

**Desktop (please complete the following information):**
 - OS: vagrant on windows 10
 - Browser Chrome
 - Version 80

**Additional infos**
I see that in the master branch these 2 words are translated in bigbluebutton-html5/private/locales/en.json as
    "app.userList.guest.acceptLabel": "Accept",
    "app.userList.guest.denyLabel": "Deny",

and in imports/ui/components/waiting-users/component.jsx the links are using 
label={intl.formatMessage(intlMessages.accept)}

But in version 2.2.x these changes are not present.
Is it possible to apply these changes in the next release, as 2.2.10 ?

Thank,
Mariano

**Comment by hhuseyinpay** [comment]
Any progress on this? And also I wonder if will guest-wait.html localized? I edit the files in place for now.

**Comment by pedrobmarin** [comment]
Localized in v2.3
