### ISSUE TITLE
2.2.5 to 2.2.9 Version Update BrakeOUT rooms bad URL link to rooms.

### ISSUE THREAD

**Issue by texh2s00** [bigbluebutton/bigbluebutton#9423]
**Describe the bug**
Updated from 2.2.5 to 2.2.9 Brake out rooms is creating, but then trying to join them it gots bad URL link. shout be: https://{server_name}/... but it shows http://<b>192.168.23.33</b>/....... with strange IP with is not on server in any conf.

**To Reproduce**
1. Go to 'meeting
2. Click on 'brakeout ROOMS invitation'
3. Join room
4. On next popup windows : http://<b>192.168.23.33</b>/bigbluebutton/api/join?fullName=

**Expected behavior**
Should Join brake out room

**Actual behavior**
Loading page error

Should be:
https://{server_name}/...

** 2.2.5 Worked perfect after update apt update ; apt upgrade error.

**Comment by GhaziTriki** [comment]
Hello @texh2s00 

After updating BigBlueButton, did you do a `sudo bbb-conf --setip yourip` then `sudo bbb-conf --restart`? I think you missed the first one.

Can you please retry it and tell us if it works?

**Comment by texh2s00** [comment]
Yep it worked... thanks ;)
