### ISSUE TITLE
Shared notes disabled by default?

### ISSUE THREAD

**Issue by Salamit** [bigbluebutton/bigbluebutton#9424]
Just letting you know that in the source code shared notes has been disabled by default in the settings.yml file since a couple of updates ago. It didn't use to be this way. I spent days trying to figure out why my shared notes wasn't working. 

May I suggest that it is changed?
Or maybe I can create a pull request

If someone reads this, my pencil isn't working well either since the update. Much help is appreciated.

https://github.com/bigbluebutton/bigbluebutton/blob/develop/bigbluebutton-html5/private/config/settings.yml

**Comment by amkyp** [comment]
Try to restart etherpad with 
`systemctl restart etherpad`
