### ISSUE TITLE
Cant Upload files - Request upload token timeout.

### ISSUE THREAD

**Issue by agustinmono** [bigbluebutton/bigbluebutton#9425]
When i try to upload a file I get this error

http://prntscr.com/sbd618

`BigBlueButton Server 2.2.9 (1891)
                    Kernel version: 4.4.0-178-generic
                      Distribution: Ubuntu 16.04.6 LTS (64-bit)
                            Memory: 8174 MB
                         CPU cores: 4

/usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties (bbb-web)
       bigbluebutton.web.serverURL: https://DOMAIN
                defaultGuestPolicy: ALWAYS_ACCEPT
                 svgImagesRequired: true

/etc/nginx/sites-available/bigbluebutton (nginx)
                       server name: DOMAIN
                              port: 80, [::]:80
                              port: 443 ssl
                    bbb-client dir: /var/www/bigbluebutton

/var/www/bigbluebutton/client/conf/config.xml (bbb-client)
                Port test (tunnel): rtmp://DOMAIN
                              red5: DOMAIN
              useWebrtcIfAvailable: true

/opt/freeswitch/etc/freeswitch/vars.xml (FreeSWITCH)
                       local_ip_v4: IP
                   external_rtp_ip: IP
                   external_sip_ip: IP

/opt/freeswitch/etc/freeswitch/sip_profiles/external.xml (FreeSWITCH)
                        ext-rtp-ip: $${local_ip_v4}
                        ext-sip-ip: $${local_ip_v4}
                        ws-binding: :5066
                       wss-binding: IP:7443

/usr/local/bigbluebutton/core/scripts/bigbluebutton.yml (record and playback)
                     playback_host: DOMAIN
                 playback_protocol: https
                            ffmpeg: 4.2.2-1bbb1~ubuntu16.04

/etc/bigbluebutton/nginx/sip.nginx (sip.nginx)
                        proxy_pass: IP

/usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml (Kurento SFU)
                        kurento.ip: IP
                       kurento.url: ws://127.0.0.1:8888/kurento
                    localIpAddress: 217.79.240.37
               recordScreenSharing: true
                     recordWebcams: true
                  codec_video_main: VP8
               codec_video_content: VP8

/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml (HTML5 client)
                             build: 894
                        kurentoUrl: wss://DOMAIN/bbb-webrtc-sfu
                  enableListenOnly: true

Potential problems described below`

**Comment by lukascelinak** [comment]
Hi, have you solution, because i have same issue.

**Comment by ffdixon** [comment]
Can you update to 2.2.11 and let us know if you still get the same error.

**Comment by aliraza170** [comment]
Hi ffdixon, 

I have BigBlueButton Server 2.2.31 (2307) version installed and I am having the same issue

**Comment by aliraza170** [comment]
@ffdixon can you help me out ? I am having Request upload token timeout. when I try to upload any document is it any setting issue ? I have good health server dedicated with extra resources

**Comment by benwul** [comment]
same issue...
BigBlueButton Server 2.3.0-alpha5 (1527)
                    Kernel version: 4.15.0-135-generic
                      Distribution: Ubuntu 18.04.5 LTS (64-bit)
                            Memory: 8167 MB
                         CPU cores: 4

**Comment by ffdixon** [comment]
> CPU cores: 4

The minimum required CPU cores is 8.  Is it an option for you install on a server that meets the [minimum requirements](https://docs.bigbluebutton.org/2.2/install.html#minimum-server-requirements)?

Otherwise, BigBlueButton will fail in unpredictable ways, and the inability to upload presentations is one of them.

**Comment by benwul** [comment]
> > If you are setting up BigBlueButton for local development on your workstation, you can relax some of the requirements because you’ll be the only one using the server. Starting with the above requirements, you can reduce them as follows
> 
> 4 CPU cores/8 GB of memory
> Installation on a local VM or LXC container
> 50G of disk space
> IPV4 address only

Under a DEV workstation it should be able to upload a presentation...

**Comment by benwul** [comment]
@ffdixon 
I changed the permissions to 777 and uploading is working...
> root@bbb:~/greenlight/storage# ls -la
> total 8
> drwxr-xr-x 2 root root 4096 Feb  7 20:09 .
> drwxr-xr-x 5 root root 4096 Feb  7 20:12 .
to 

> drwxrwxrwx 2 root root 4096 Feb  7 20:09 .
> drwxr-xr-x 5 root root 4096 Feb  7 20:12 ..
