### ISSUE TITLE
Client shows incorrect audio state after network interference

### ISSUE THREAD

**Issue by KDSBrowne** [bigbluebutton/bigbluebutton#9426]
**Describe the bug**
If a user joins audio in a meeting and there is network interference that causes a disconnection, the client does not always display the correct audio state for that users.

**To Reproduce**
1) Join mic audio in a meeting.
2) Disconnect network connection.
3) Reconnect network connection.
4) Try to speak

**Expected behavior**
The audio state displayed in the client should be in sync with the user's actual audio state.

**Actual behavior**
When the network connection is restored, the client shows the state of the user's audio at 
the time of the disconnection when they are not actually in the audio. If joined with Mic, the mute / un-mute functionality will still function as though the user is still in the audio.

**BBB version (optional):**
BigBlueButton Server 2.2.10 (1885)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 81.0.4044.129 (Official Build) (64-bit)

**Additional context**
1) If joined via Listen-only, when the reconnect happens there is a 30 second delay before the client audio reflects the correct state for that user.

2) When connected with a Mic, If the network connection is established before the client tries to reconnect all is fine. It's only when the client attempts to reconnect before the network connection is reestablished that this issue occurs.

**Comment by mariogasparoni** [comment]
Thanks @KDSBrowne , this was already fixed in recent audio /sip.js changes, specially in 2.2.31, and current's 2.3 HEAD (2.3-alpha + recent audio patches).
This issue can be closed.
