### ISSUE TITLE
Limit number of concurrent rooms instead of number of rooms

### ISSUE THREAD

**Issue by ostasevych** [bigbluebutton/bigbluebutton#9427]
In the settings it is possible to limit number if rooms which users may create. This is called, as far as I understand, to help to balance the system.

However, users may create separate rooms for special tasks, but use at the same time only few of them.

Would that be possible to limit not the number of the rooms a user may create, but the number of rooms, which user may start concurrently. So, if I limit a user to 5 rooms, one may start only 5 of them, and if one wants to start the 6 one, he/she has to close one of first five rooms.

**Comment by Sea444** [comment]
Could it be that you're talking about Greenlight frontend? Then you're here wrong. You are looking for https://github.com/bigbluebutton/greenlight/issues

**Comment by ostasevych** [comment]
> Could it be that you're talking about Greenlight frontend? Then you're here wrong. You are looking for https://github.com/bigbluebutton/greenlight/issues

Actually this is the question to developers: where it is already implemented by now?

**Comment by GhaziTriki** [comment]
Should be in Greenlight issues.
