### ISSUE TITLE
Erreur 1002 : Unexpected response code: 404

### ISSUE THREAD

**Issue by Entretoize** [bigbluebutton/bigbluebutton#9430]
When joining a session and selecting Microphone for audio, I receive a Erreur 1002. Camera is working.
javascript error:
```
sip.js?v=894:8404 WebSocket connection to 'wss://classe.domain.fr/ws' failed: Error during WebSocket handshake: Unexpected response code: 404
connect @ sip.js?v=894:8404
```

BBB has been installed with bbb-install.sh on an Ubuntu 16 server.

**Comment by MortezaTaghaddomi99** [comment]
Are you sure the server isn't behind a firewall? 
https://docs.bigbluebutton.org/2.2/configure-firewall.html

**Comment by mrmookie** [comment]
Same issue today from fresh install, firewall is stopped/disabled/open.

sip.js?v=894:8404 WebSocket connection to 'wss://bbb.mydomain.com/ws' failed: Error during WebSocket handshake: Unexpected response code: 404
connect @ sip.js?v=894:8404
Transport @ sip.js?v=894:8292
UA.start @ sip.js?v=894:8994
(anonymous) @ c86276c602f80e1c39e9064918149b6eade2642d.js?meteor_js_resource=true:121
createUserAgent @ c86276c602f80e1c39e9064918149b6eade2642d.js?meteor_js_resource=true:121
(anonymous) @ c86276c602f80e1c39e9064918149b6eade2642d.js?meteor_js_resource=true:1

**Comment by Entretoize** [comment]
Yes no firewall for me.

**Comment by Entretoize** [comment]
I just checked nginx log:

```
2020/05/06 05:40:32 [error] 5354#5354: *342 connect() failed (111: Connection refused) while connecting to upstream, client: 109.21.149.24, server: classe.creforma.fr, request: "GET /ws HTTP/1.1", upstream: "https://15.188.193.0:7443/ws", host: "classe.creforma.fr"
2020/05/06 05:40:32 [error] 5354#5354: *342 open() "/var/www/nginx-default/50x.html" failed (2: No such file or directory), client: 109.21.149.24, server: classe.creforma.fr, request: "GET /ws HTTP/1.1", upstream: "https://15.188.193.0:7443/ws", host: "classe.creforma.fr"
```
15.188.193.0 is not my server ip at all, is it normal ?

**Comment by basisbit** [comment]
Try `bbb-conf --setip your.domainname.tld` if that does not help, take a look at the result of `bbb-conf --check`

**Comment by Entretoize** [comment]
already tried that it didn't solve the problem, I restarted with a fresh ubuntu it worked, now I have other random issues, maybe because I'm on a 2 vcores server ?

**Comment by ffdixon** [comment]
> already tried that it didn't solve the problem, I restarted with a fresh ubuntu it worked, now I have other random issues, maybe because I'm on a 2 vcores server ?

You need at least 4 CPU cores (8 is better).

With only 2, your BigBlueButton server is going to not work in unpredictable ways.

**Comment by Entretoize** [comment]
I upgraded to a 4 core server, and installed bigbluebutton and the issue has came back.
I ran the install script before the DNS propagation as ended then I reran it later, but the old ip is still somewhere.
I did the bbb-conf --setip mydomainname.tld with no success.

bbb-conf -check result:

BigBlueButton Server 2.2.9 (1895)
                    Kernel version: 4.19-ovh-xxxx-std-ipv6-64
                      Distribution: Ubuntu 16.04.6 LTS (64-bit)
                            Memory: 16399 MB
                         CPU cores: 4

/usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties (bbb-web)
       bigbluebutton.web.serverURL: https://mydomain.fr
                defaultGuestPolicy: ALWAYS_ACCEPT
                 svgImagesRequired: true

/etc/nginx/sites-available/bigbluebutton (nginx)
                       server name: mydomain.fr
                              port: 80, [::]:80
                              port: 443 ssl
                    bbb-client dir: /var/www/bigbluebutton

/var/www/bigbluebutton/client/conf/config.xml (bbb-client)
                Port test (tunnel): rtmp://mydomain.fr
                              red5: mydomain.fr
              useWebrtcIfAvailable: true

/opt/freeswitch/etc/freeswitch/vars.xml (FreeSWITCH)
                       local_ip_v4: 91.121.XXX.XXX
                   external_rtp_ip: 37.187.XXX.XXX
                   external_sip_ip: 37.187.XXX.XXX

/opt/freeswitch/etc/freeswitch/sip_profiles/external.xml (FreeSWITCH)
                        ext-rtp-ip: $${local_ip_v4}
                        ext-sip-ip: $${local_ip_v4}
                        ws-binding: :5066
                       wss-binding: 37.187.XXX.XXX:7443

/usr/local/bigbluebutton/core/scripts/bigbluebutton.yml (record and playback)
                     playback_host: mydomain.fr
                 playback_protocol: https
                            ffmpeg: 4.2.2-1bbb1~ubuntu16.04

/etc/bigbluebutton/nginx/sip.nginx (sip.nginx)
                        proxy_pass: 91.121.XXX.XXX

/usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml (Kurento SFU)
                        kurento.ip: 91.121.XXX.XXX
                       kurento.url: ws://127.0.0.1:8888/kurento
                    localIpAddress: 91.121.XXX.XXX
               recordScreenSharing: true
                     recordWebcams: true
                  codec_video_main: VP8
               codec_video_content: VP8

/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml (HTML5 client)
                             build: 894
                        kurentoUrl: wss://mydomain.fr/bbb-webrtc-sfu
                  enableListenOnly: true

**Comment by Entretoize** [comment]
I modified manually and it works again.

**Comment by will0225** [comment]
HI
How did you modify code?
I am getting such error 
it is 502 error
Please
