### ISSUE TITLE
html5client: Prevent white flash when switching to next page in a PDF presentation

### ISSUE THREAD

**Issue by MazeChaZer** [bigbluebutton/bigbluebutton#9431]
**Describe the bug**
When going to the next page in a PDF presentation, the canvas goes all white while the next page is loading, this is very irritating especially when it only reveals new bullet points on the same page (e.g. LaTeX `\pause`).

**To Reproduce**
1. Upload PDF presentation
2. Click on next page button

**Expected behavior**
As long as the next page is not fully loaded, the previous page should stay on the canvas. After the next page is loaded, it should replace the previous page instantaneously.

**Actual behavior**
As soon as the one clicks the "next page" button the canvas is cleared, giving a white flash until the next page is loaded.

**BBB version (optional):**
Client version: 894

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Browser Firefox 75.0, Chromium 81.0.4044.113

**Comment by pbdco** [comment]
👍 agree on this

**Comment by jfsiebel** [comment]
Related to #9011, maybe the changes in #9012 can mitigate the problem.

**Comment by antobinary** [comment]
Merging into https://github.com/bigbluebutton/bigbluebutton/issues/9231
