### ISSUE TITLE
Make video downloadable

### ISSUE THREAD

**Issue by FedeLux** [bigbluebutton/bigbluebutton#9432]
Hi,
if there is a way to download BBB video tell me how, thank you.

**Comment by ostasevych** [comment]
By now using 3rd party extensions of your browser only. There's already request to add this feature directly to the interface.

**Comment by lonesomewalker** [comment]
right click, save as...?

**Comment by FedeLux** [comment]
The problem is that I can only find multiple .mp4 videos, one for audio and one for the video.

It will be nice if I can download a single .mp4 with audio and video. Is it possible?

**Comment by ostasevych** [comment]
> right click, save as...?

Sorry, right/left click where?

**Comment by ostasevych** [comment]
> The problem is that I can only find multiple .mp4 videos, one for audio and one for the video.
> 
> It will be nice if I can download a single .mp4 with audio and video. Is it possible?

I suggest that all the media docs are combined and converted into one video file and send to a user for downloading.

**Comment by olberger** [comment]
We have experimented with several options in https://github.com/trahay/bbb-downloader/

I hope you'll find it useful

**Comment by matiasilva** [comment]
There's an existing issue about this and adequate responses have been provided. Please close the issue.

**Comment by olberger** [comment]
@matiasilva, care to reference that issue ?

**Comment by matiasilva** [comment]
#1969, the most commented issue in this repository :)
