### ISSUE TITLE
Hyphens in %%CONFNUM%% are very confusing for users

### ISSUE THREAD

**Issue by mclegrand** [bigbluebutton/bigbluebutton#9434]
**Describe the bug**
A recent change ( https://github.com/bigbluebutton/bigbluebutton/pull/9311/files )  introduced hyphens in the middle of %%CONFNUM%% variable in the html frontend that users see when connecting. While I have no idea if separating pin numbers by a dash is normal in the USA (since they already separate phone numbers with a dash), I don't think anyone in France would make a separation inside a 5-digit pin and the dash is never used as a number separator (spaces or dots for 10-digits phone numbers), so this looks like either "enter 55 minus 183" or "litteraly enter a hyphen". Some people also looked for the hyphen character on their phone, which does not exist.

Please revert this change for the 5-number pins

**To Reproduce**
1. Setup bbb with a phone integration
2. Join a meeting

**Expected behavior**
People would understand the PIN they have to enter

**Actual behavior**
People are confused

**Screenshots**

**BBB version (optional):**
2.2.9

**Additional context**
I understand that this change might make sense for 9-digit PINs, but please make it configurable at the configuration-level (for instance, where one can choose between no-separator, spaces, or hyphens) and not hardcoded

**Comment by ffdixon** [comment]
We'll look at adding a separator character to make this more configuable.

**Comment by steffen-moser** [comment]
It also seems that the hypen is only shown in the welcome message. It is not shown in the dialog box which appears when someone clicks "Join using your phone":

![Screenshot 2020-05-07 at 13 44 46 ed](https://user-images.githubusercontent.com/4097996/81292557-161ba680-906c-11ea-89b1-a32ca32f5522.png)

**Comment by Sea444** [comment]
Yes, the hyphens confuse, they should be replaced by spaces (if more than 6 characters), or removed completely.

**Comment by aguerson** [comment]
Hello. +1
Could you put a space or something else ?
a '-' is very strange for a pin number in France...
Regards,
Aurélien.

**Comment by DirkVieregg** [comment]
+1 from here.
Five digits are not that long and most people will be able to read it without any separator.

**Comment by legrex** [comment]
Same problem here (Germany), i got constant bug reports, that the phone pin is not working, which turns out that user are trying to enter a "minus" via there phone or just not finding it of course.
I would say i never had to answer so much "bug reports" since this hyphen was included.

**Comment by antobinary** [comment]
This was addressed in https://github.com/bigbluebutton/bigbluebutton/pull/9627
