### ISSUE TITLE
Increase time of breakout session AFTER session has started

### ISSUE THREAD

**Issue by glu000** [bigbluebutton/bigbluebutton#9435]
**Is your feature request related to a problem? Please describe.**
There is no possibility to expand the time of a breakout session. Sometimes it happens, that the participants need more time. 

**Describe the solution you'd like**
It would be helpful, to have an option to increase the time of a breakout-session after the session has started

**Describe alternatives you've considered**
The only alternative is, to start a new breakout session with the same participants. To arrange the users to the same breakout-rooms is very time-consuming. Also results of the previous breakout sessions (eg shared notes) are gone when starting a new one.

**Comment by SamuelWei** [comment]
Looking for the same feature.

**Comment by MistyNikula** [comment]
Also looking for the same feature!
