### ISSUE TITLE
Tooltip which indicates if a presentation can be downloaded or not can be confusing

### ISSUE THREAD

**Issue by abias** [bigbluebutton/bigbluebutton#9436]
**Describe the bug**
On the "Upload a presentation" screen, the tooltip which indicates if a presentation can be downloaded or not can be confusing.

**To Reproduce**
1. Go to a BBB meeting room
2. Get presenter rights
3. Click on the plus sign
4. Click on "Upload a presentation"
5. Upload an arbitrary presentation file
6. Have a look at the file "download presentation" icon and toggle it to see the two different states

**Expected behavior**
* When the icon is gray and stroke through, the tool tip of the icon says "Presentation download is not allowed - click to allow presentation to be downloaded"
* When the icon is green and not stroke through, the tool tip of the icon says "Presentation download is allowed - click to disallow presentation to be downloaded"

**Actual behavior**
* When the icon is gray and stroke through, the tool tip of the icon says "Do not allow presentation to be downloaded"
* When the icon is green and not stroke through, the tool tip of the icon says "Allow presentation to be downloaded"

**Screenshots**
![Ulm_University__BigBlueButton_deployed_by_OMI_-_Startraum](https://user-images.githubusercontent.com/1092118/81160807-daf57680-8f8a-11ea-802c-f2d665c06008.png)

**Additional context**
The question here is if a toggle button should show its current state or the state to which it will change. See https://ux.stackexchange.com/questions/1318/should-a-toggle-button-show-its-current-state-or-the-state-to-which-it-will-chan for an in-depth discussion.

A clean solution would be to modify the switch design to make clear what the status _and_ the action is.

A quick solution here would be to rephrase the tooltip to cover both needs as I have proposed it in the "Expected behavior" section

**Comment by matiasilva** [comment]
Seems like a reasonable change. Can you try implementing it yourself, since it is after all a simple string modification and then submit a pull request?
