### ISSUE TITLE
Safari and microphone

### ISSUE THREAD

**Issue by guwek** [bigbluebutton/bigbluebutton#9437]
I just hosted a session from Safari. The microphone stopped working after disconnecting the headphones (they do not have a mic, I have only one built-in mic). Later (after a couple of minutes), it came back. Yesterday, I observed a similar erratic behaviour.

**Comment by matiasilva** [comment]
Does this still persist with the latest version of BBB? If not, please close this issue.

**Comment by matiasilva** [comment]
@guwek updates?

**Comment by guwek** [comment]
Difficult to say. We observed a lot of not so easy to reproduce issues related to audio/video. Sometimes exiting or restarting the browser helps.

**Comment by antobinary** [comment]
Can no longer reproduce
