### ISSUE TITLE
Not working correctly with iOS

### ISSUE THREAD

**Issue by ostasevych** [bigbluebutton/bigbluebutton#9438]
Not working correctly on iPhones (iOS 13.3.3). All browsers (Chrome, Firefox) are complaining that the version is not supported, though updated to the last one. Safari says that it is not fully supported and suggests to use Chrome or FF.

**Comment by basisbit** [comment]
This seems to be a problem with your setup. There are many users successfully participating in BBB sessions from Safari browser on iOS 12.2 or newer. You can test this at https://test.bigbluebutton.org .
For support requests, please use the mailing list / Google Forum at https://groups.google.com/forum/#!forum/bigbluebutton-users

**Comment by supadupa2** [comment]
im facing the same issue #9444, there is definitely a problem in the instructions. Have applied to the google group as well to see if it can be sorted out there.

**Comment by antobinary** [comment]
Can no longer reproduce
