### ISSUE TITLE
I need html5 client build script

### ISSUE THREAD

**Issue by jakiro2017** [bigbluebutton/bigbluebutton#9442]
**Describe the bug**
I modified the client as follow (basically just filter unused languages)
https://github.com/jakiro2017/bigbluebutton/commit/dd3751eafb962028cc6ad21d663b84e94f2cc4ec

I expect the client work as  usual but it has many "anomalies" like: not display voice echo completed, video lags or can't login.

IMHO, no way those codes change can create a drastic effect on the client

**Installation type**
Manually build as follow:
```
meteor update --allow-superuser --release 1.8.1
rm -rf node_modules
meteor npm install
meteor build --allow-superuser --verbose --server-only --directory /tmp/build0605-3 #4
```
then I overwrite the /usr/share/meteor/bundle with the result of #4 command
**Firewall and IP address type**
Is your server behind a NAT or firewall? Does your BBB server have its own IPv4 addres?
Yes
**Console output**
No error log.

**Additional context**
If run apt-get install --resinstall bbb-html5 the problem is gone, so I think I had a mistake on the build steps?

**Comment by basisbit** [comment]
are you maybe trying to deploy a develop-branch html5 client on a 2.2.x-branch based server?

**Comment by jakiro2017** [comment]
> are you maybe trying to deploy a develop-branch html5 client on a 2.2.x-branch based server?

Hi, I upgraded the server to 2.2.9 version and checkout the tag 2.2.9 before edit the code. Did I do something wrong?

PS: The Ubuntu packages show 2.2.0, while `bbb-conf --check `show 2.2.9 which confuse me as well.

**Comment by basisbit** [comment]
That sounds correct. 2.2.0 as ubuntu package is alwo okay for any 2.2.x bbb version.

**Comment by jakiro2017** [comment]
> That sounds correct. 2.2.0 as ubuntu package is alwo okay for any 2.2.x bbb version.

Do you know where is the shell script to build deb packages? I searched the repo but can't find the one...

I feel I missed something in the build step

**Comment by jakiro2017** [comment]
Summary, if you use a self-built version don't backup-restore the old settings from the package downloaded from apt-get

Instead, moving necessary value from there to the dev config.

It takes me like a week to figure it out :(
