### ISSUE TITLE
Disable browser check instructions not working

### ISSUE THREAD

**Issue by supadupa2** [bigbluebutton/bigbluebutton#9444]
**Describe the bug**
This issue is similar to #8152 however its ending is different. 
Many browsers from ios and android phones are seeing "It looks like you're using an older version of a supported browser. Please upgrade your browser for full support."
bbbServerVersion: 2.2-dev

**To Reproduce**
1. Change /usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml for the browsers affected by afew digits or even to 1
2. sudo bbb-conf --restart or recompile the whole app
3. Change browser tag to Safari 10 (or any browser supported less 1) for example using chromes User Agent Switcher
4. Enter a room, after entering room password it will prompt "It looks like you're using an older version of a supported browser. Please upgrade your browser for full support."

http://docs.bigbluebutton.org/2.2/troubleshooting.html#the-browser-is-not-supported has been followed but is not working
**Expected behavior**
.Should have allowed the page to load without error

**Actual behavior**
Despite multiple restarts to config, server and recompilation the system is not picking up the values entered for the browser versions, rest of the settings work when changed

**Screenshots**

**Desktop (please complete the following information):**
This issue affects all OS and browsers including phones below the originally supported versions

**Smartphone (please complete the following information):**

**Additional context**
Here is the extract of the latest file (tried playing with brackets, -'s and 0's):
    ignored:
    - CheckAlivePongSysMsg
    - DoLatencyTracerMsg
  serverLog:
    level: info
    streamerLog: false
  memoryMonitoring:
    stat:
      enabled: false
    leak:
      enabled: false
    heapdump:
      enabled: false
  minBrowserVersions:
  - browser: chrome
    version: 0
  - browser: chromeMobileIOS
    version: Infinity
  - browser: firefox
    version: 0
  - browser: firefoxMobile
    version: 0
  - browser: edge
    version: 0
  - browser: ie
    version: Infinity
  - browser: vivaldi
    version: 0
  - browser: safari
    version: 
    - 0
    - 1
  - browser: mobileSafari
    version: 0
  - browser: opera
    version: 0
  - browser: electron
    version: [0, 36]
  - browser: samsungInternet
    version: 0
  - browser: yowser
    version: 0
  - browser: yabrowser
    version: 0
  - browser: yandexBrowser
    version: 0
  - browser: facebook
    version: 0
  - browser: chromeMobileWebView
    version: 10

**Comment by jakiro2017** [comment]
From my experiences, you should modify meteor package 'modern-browsers' to see the user agent string, it tends to change it a camel case name.

**Comment by supadupa2** [comment]
thanks for that, i changed those files to 1 as well but seems they are not it. As a test i tried testing by changing my user agent, i found that anything below chrome 55 would return the message of an older browser. 55 and above would be fine. Nowhere in the settings could i find what is making it determine 55 as the default settings were way higher.

**Comment by jakiro2017** [comment]
> thanks for that, i changed those files to 1 as well but seems they are not it. **As a test i tried testing by changing my user agent, i found that anything below chrome 55 would return the message of an older browser. 55 and above would be fine.** Nowhere in the settings could i find what is making it determine 55 as the default settings were way higher.

I don't get it. It's a correct behaviour. You shouldn't modify it since meteor backend need at least that version to work properly

**Comment by supadupa2** [comment]
i need to enable browsers from phones which have different agents, using this way of troubleshooting is just to find where is the checking happening quickly so i dont have to keep trying from the different phones.
mobile agents are up to date but because they are not in the file they are being detected as unsupported. This is happening in android phones quite abit as they send agents like SamsungBrowser

**Comment by supadupa2** [comment]
i tried adding facebook to the alias for safarimobile in/usr/share/meteor/bundle/programs/server/packages/modern-browsers.js but its still not loading... :(

**Comment by jakiro2017** [comment]
if you make sure in the config, the name of your browser is matched here
https://github.com/meteor/meteor/blob/71f67d9dbac34aba34ceef733b2b51c2bd44b665/packages/modern-browsers/modern.js#L68

then I have no idea what's wrong. I remember it different from `useragent` returned by bbb server itself, which cost me sometime.

**Comment by supadupa2** [comment]
is it possible to get a peek at what you changed in your file? I still cant seem to figure this out :(

**Comment by jakiro2017** [comment]
I just log the `browser` name at https://github.com/meteor/meteor/blob/71f67d9dbac34aba34ceef733b2b51c2bd44b665/packages/modern-browsers/modern.js#L68

and add that exactly name to the `/usr/share//meteor/bundle/programs/server/assets/app/config/settings.yml`

**Comment by quendi1985** [comment]
Thank you for the continuous work. It would be really great to have the streaming feature in the future. It would be a game changer. For now, we use OBS (browser capture) to stream on YouTube Live or Facebook Live, I would say with really good results, with scenes transitions, customized backgrounds with chroma key filter etc. Give it a try. :)

Panos

**Comment by mcferdev** [comment]
I am facing the same problem. Some Android webview navigators are not working because of this minimium version check and when I alter the setting.yml and restart the BBB, still not working

**Comment by jakiro2017** [comment]
> I am facing the same problem. Some Android webview navigators are not working because of this minimium version check and when I alter the setting.yml and restart the BBB, still not working

Make sure you get the correct agent string, it's not the same as *user agent* route detected by webclient

**Comment by sor88** [comment]
Thank's. This method is working!

**Comment by ffdixon** [comment]
Updated docs 

  https://docs.bigbluebutton.org/2.2/troubleshooting.html#the-browser-is-not-supported

to now point to https://test.bigbluebutton.org/html5client/useragent to determine `useragent`.

**Comment by Mohamed-Gibreel** [comment]
Could you please re-explain what you guys did to make it work, I am working on an iphone 6s, I tried changing the useragent in flutter web view to whatever string I got from https://test.bigbluebutton.org/html5client/useragent, but I still get the same issue. Any help is appreciated. Thanks
