### ISSUE TITLE
Error 1007: a few users could not connect to audio video or media

### ISSUE THREAD

**Issue by atrex123** [bigbluebutton/bigbluebutton#9448]
I installed BBB, this works correctly, some times, some students can not use media files, always error 1007, sometimes this works sometimes not

**Comment by atrex123** [comment]
I recently found out that with my  4g internet and some specific Internet Providers, this error exist and by some others this doesn't.

**Comment by ffdixon** [comment]
You may need to support IPV6, see

 http://docs.bigbluebutton.org/2.2/troubleshooting.html#configure-bigbluebuttonfreeswitch-to-support-ipv6

**Comment by atrex123** [comment]
> 
> 
> You may need to support IPV6, see
> 
> http://docs.bigbluebutton.org/2.2/troubleshooting.html#configure-bigbluebuttonfreeswitch-to-support-ipv6

**Hi Fred, this doesn't work. after this bbb doesn't running right now. the error is** 

Potential problems described below
# IP does not match:
#                           IP from ifconfig: 188.***.*.***
#   /etc/nginx/sites-available/bigbluebutton: edu.khwarizmi-foundation.com
# Not running:  Nginx
................................................................................
# Error: Could not connect to the configured hostname/IP address

**i am using ssl and hostname**

**for restarting bbb:**          

Job for nginx.service failed because the control process exited with error code. See "systemctl status nginx.service" and "journalctl -xe" for details.

**what i did was as you said:** 
map $remote_addr $freeswitch_addr {
    "~:"    [2001:db8::1];
    default    192.0.2.1;
}
**and adding this to xml.**

enable-3pcc

**Comment by atrex123** [comment]
nginx —————————————————► [✘ - failed]
freeswitch ————————————► [✔ - active]
redis-server ——————————► [✔ - active]
bbb-apps-akka —————————► [✔ - active]
bbb-transcode-akka ————► [✔ - active]
bbb-fsesl-akka ————————► [✔ - active]
red5 ——————————————————► [✔ - active]
tomcat7 ———————————————► [✔ - active]
mongod ————————————————► [✔ - active]
bbb-html5 —————————————► [✔ - active]
bbb-webrtc-sfu ————————► [✔ - active]
kurento-media-server ——► [✔ - active]
etherpad ——————————————► [✔ - active]
bbb-web ———————————————► [✔ - active]

**Comment by atrex123** [comment]
> 
> 
> > You may need to support IPV6, see
> > http://docs.bigbluebutton.org/2.2/troubleshooting.html#configure-bigbluebuttonfreeswitch-to-support-ipv6
> 
> **Hi Fred, this doesn't work. after this bbb doesn't running right now. the error is**
> 
> Potential problems described below
> # IP does not match:
> # IP from ifconfig: 188.**_._.***
> # /etc/nginx/sites-available/bigbluebutton: edu.khwarizmi-foundation.com
> # Not running: Nginx
> 
> ................................................................................
> # Error: Could not connect to the configured hostname/IP address
> 
> **i am using ssl and hostname**
> 
> **for restarting bbb:**
> 
> Job for nginx.service failed because the control process exited with error code. See "systemctl status nginx.service" and "journalctl -xe" for details.
> 
> **what i did was as you said:** by replacing the ipv4 and ipv6
> map $remote_addr $freeswitch_addr {
> "~:" [2001:db8::1];
> default 192.0.2.1;
> }
> **and adding this to xml.**
> 
> enable-3pcc

**Comment by atrex123** [comment]
i did it, but nothings changed.

i still have error 1007 ice through some internet providers

**Comment by atrex123** [comment]
with android, just me can speak, others through all devices, android IOS ... have error 1007 ICE

**Comment by mosyBG** [comment]
not solved for me.

**Comment by ffdixon** [comment]
If you have IPV6 configured on your server and some users are only on IPV6, see https://docs.bigbluebutton.org/2.2/troubleshooting.html#configure-bigbluebuttonfreeswitch-to-support-ipv6
