### ISSUE TITLE
Publishing poll results might break presentation area.

### ISSUE THREAD

**Issue by palimm** [bigbluebutton/bigbluebutton#9451]
**Describe the bug**
On poll result publish the presentation area becomes unusable while a certain pdf is being used as presentation.

**To Reproduce**
1. Upload and set the attached pdf as presentation
2. Initiate a poll
3. publish poll results

**Expected behavior**
Poll results being displayed and presentation stays usable.

**Actual behavior**
No poll results and presentation area becomes unusable.
Error: `Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings`

**BBB version (optional):**
BigBlueButton Server 2.2.15
[default.pdf](https://github.com/bigbluebutton/bigbluebutton/files/4708063/default.pdf)

**Comment by basisbit** [comment]
Can not reproduce this on https://test.bigbluebutton.org/ . @palimm could you please test if you can reproduce the problem at the test server, and if you succeed reproducing the problem, add the required steps to cause the issue?

**Comment by palimm** [comment]
@basisbit No, I cannot reproduce it on https://test.bigbluebutton.org/. That's good and bad...
Here we are at BBB 2.2.9 with html5 client 894 and the moment a poll result is published
`Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings. `
pops up.

**Comment by palimm** [comment]
Ok, I guess I figured it out. We recently switched out the default presentation for a new pdf document.
I just replaced that new document with a much smaller version and voila, the poll results show up. 

On the one hand sorry for the inconvenience, on the other hand having an unreasonably large presentation should not raise and error at this stage. Maybe a sanity-check yould be performed right after the upload?!

I'll check if I am allowed to publish the document and come back if anybody is interested in taking a closer look at this.

**Comment by basisbit** [comment]
@palimm any news regarding the presentation file?

**Comment by palimm** [comment]
@basisbit
Here it is.
[default.pdf](https://github.com/bigbluebutton/bigbluebutton/files/4707144/default.pdf)

**Comment by basisbit** [comment]
Indeed, can confirm the bug. 
Steps to reproduce:
1. upload the presentation
2. minimize the presentation
3. create a new poll, then publish the result
-> 'Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings'

Reloading the page does not help, presentation area is still broken.

@palimm please change the title and issue description, so that this issue can be worked on without requiring the developer to read about the other issue again.

**Comment by palimm** [comment]
@basisbit done, ty

**Comment by ranevaibhav95** [comment]
Hi, i was trying to reproduce this bug, i uploaded the pdf and then started a poll, after publishing poll i got the error as below:
![MicrosoftTeams-image](https://user-images.githubusercontent.com/25950153/86212670-18930c00-bb96-11ea-824e-34ec95a6efb7.png)

**Comment by basisbit** [comment]
@ranevaibhav95 what version of Bigbluebutton do you use? Can you reproduce that problem at https://test.bigbluebutton.org ?

**Comment by ranevaibhav95** [comment]
I am using 2.2.19

**Comment by ranevaibhav95** [comment]
Hey i got the error reason, it was because i didnt update my custom html5 package to 2.2.19..sorry for raising a non-existent issue

**Comment by ranevaibhav95** [comment]
Oops soory to bother again..after updating the bbb-html5 custom development package, i am still getting the error

**Comment by ranevaibhav95** [comment]
> @ranevaibhav95 what version of Bigbluebutton do you use? Can you reproduce that problem at https://test.bigbluebutton.org ?

It is working fine on https://test.bigbluebutton.org
