### ISSUE TITLE
Microphone not working. SIP Error Code 1004

### ISSUE THREAD

**Issue by FirstUserBBB** [bigbluebutton/bigbluebutton#9452]
Hi 
we are new to BigBlueButton and just tried to held a conference. But it didn't work. Everytime we tried to connect with microphone, we got the error code SIP error code 1004. I tried with different browsers (Firefox and Chrome) and also the other participants, but we all got the same error. Is this an actual issue at BigBlueButton as I couldn't find anything similar in the internet yet. 
Video did work, just microphone was the problem.

**Comment by sebaro11** [comment]
I had the same error some time ago and finally got the answer:
https://github.com/bigbluebutton/bigbluebutton/issues/9088#issuecomment-624206690

**Comment by FirstUserBBB** [comment]
Thanks a lot, but this checkbox is unchecked and I face this error anyway. So is there an overall problem with BBB at the moment? I run BBB from this webpage: https://demo.bigbluebutton.org/gl/, not from a server by myself. So could this be the problem? Or is anybody else facing the same problem today?

**Comment by basisbit** [comment]
This issue tracker here is only for BBB development related issues. For BBB server setup, please use the support forum at https://groups.google.com/forum/#!forum/bigbluebutton-setup
