### ISSUE TITLE
PDF presentation: some pages are not rendered

### ISSUE THREAD

**Issue by khumarahn** [bigbluebutton/bigbluebutton#9453]
Hi.
I use BBB-2.2.9 on a Ubuntu 16.04, installed by bbb-install with default settings.
I found that on some pdf presentations, some pages are not rendered, and are displayed blank.

Example of a presentation pdf file is below. It was made in Xournal++ with a picture of a blackboard on the background and some hand drawing on top. I observe that the pages with very little handwriting display well, but those with more than a few words do not display.

Screenshots:
![Screenshot_2020-05-07 BigBlueButton - Meeting Room 1](https://user-images.githubusercontent.com/5206045/81280239-17d77100-9050-11ea-8146-0dcb168f871b.png)
![Screenshot_2020-05-07 BigBlueButton - Meeting Room 2](https://user-images.githubusercontent.com/5206045/81280242-18700780-9050-11ea-8b72-90f32f24de84.png)
![Screenshot_2020-05-07 BigBlueButton - Meeting Room 3](https://user-images.githubusercontent.com/5206045/81280243-18700780-9050-11ea-89fa-50e6fb5c1f3c.png)
![Screenshot_2020-05-07 BigBlueButton - Meeting Room 4](https://user-images.githubusercontent.com/5206045/81280247-19089e00-9050-11ea-911a-9bab263a0250.png)

PDF file:
[bbb-pdf.pdf](https://github.com/bigbluebutton/bigbluebutton/files/4592152/bbb-pdf.pdf)

**Comment by pedrobmarin** [comment]
Likely related with https://github.com/bigbluebutton/bigbluebutton/pull/11828 . Verified that all pages rendered in v2.3
