### ISSUE TITLE
Firefox v76.0 on Debian: echo test plays no audio and sharing camera produces error 1020

### ISSUE THREAD

**Issue by tobiasjj** [bigbluebutton/bigbluebutton#9454]
**Describe the bug**
After an upgrade of Firefox to version 76.0, there is no audio when trying to connect to an audio conference. When trying to share the camera `Media could not reach the server (error 1020)` is displayed after few seconds. Other Browsers on the same computer and other computers/smartphones on the same network can properly join conferences on different BBB servers.

**To Reproduce**
1. Upgrade to Firefox 76.0
2. Try to join an audio/video conference on a BBB server

**Expected behavior**
The audio should be heard upon echo test and the video should be shared.

**Actual behavior**
Audio and video are not shared.

**BBB version:**
Tested servers:
* BigBlueButton Server 2.2.9 (1891)
* https://test.bigbluebutton.org/

**Desktop:**
 - OS: Debian bullseye GNOME
 - Browser Firefox
 - Version 76.0

**Additional context**
As different browsers and computers work with differen BBB servers, I'm wondering, if this is an issue introduced with the new Firefox? Has anybody else with Firefox v76.0 experienced the same issues?

**Comment by ffdixon** [comment]
Can you use about:webrtc in FireFox to see what ICE candidates it tried to connect.  Can you also post the output of the Javascript console.

**Comment by prlanzarin** [comment]
@tobiasjj Do you have a stable Debian installation you can try FF76 on? Just tried FF76 on stretch and buster and both seemed good, so it might be something localized to bullseye and/or your box.

Also please send the info Fred mentioned (full about:webrtc dump if possible), very important. Thanks.

**Comment by tobiasjj** [comment]
ICE candidates, accepting the echo test, despite no sound heard, and trying to share the webcam:

PeerConnection ID: 1588855750829709 (id=38654705737 url=https://test.bigbluebutton.org/html5client/join?sessionToken=kbfeubepvve6nonv)
ICE Stats
ICE State | Nominated | Selected | Local Candidate | Remote Candidate | Component ID | Priority | Bytes sent | Bytes received
-- | -- | -- | -- | -- | -- | -- | -- | --
succeeded | true | true | 2a02:8070:88ab:6b00:2513:c2df:288a:e93:56912/udp(host) [non-proxied] | 2607:5300:60:3118:::19392/udp(host) | 1 | 2830971808121343 | 1545 | 306954
succeeded | true | true | 2a02:8070:88ab:6b00:2513:c2df:288a:e93:56912/udp(host) [non-proxied] | 2607:5300:60:3118:::19392/udp(host) | 1 | 2830971808121343 | 1545 | 306954
succeeded | true | false | 2a02:8070:88ab:6b00:7f3d:75e5:111b:4e8a:56370/udp(host) [non-proxied] | 2607:5300:60:3118:::19392/udp(host) | 1 | 2830971807990271 | 0 | 0
succeeded | true | false | 2a02:8070:88ab:6b00:7f3d:75e5:111b:4e8a:56370/udp(host) [non-proxied] | 2607:5300:60:3118:::19392/udp(host) | 1 | 2830971807990271 | 0 | 0
failed | false | false | 2a03:b0c0:3:d0::58:1001:59078/udp(relay) [non-proxied] | 2607:5300:60:3118:::19392/udp(host) | 1 | 2830967580278783 | 0 | 0
failed | false | false | 2a03:b0c0:3:d0::58:1001:59078/udp(relay) [non-proxied] | 2607:5300:60:3118:::19392/udp(host) | 1 | 2830967580278783 | 0 | 0
failed | false | false | 2a03:b0c0:3:d0::58:1001:37745/udp(relay) [non-proxied] | 2607:5300:60:3118:::19392/udp(host) | 1 | 2830967580147711 | 0 | 0
failed | false | false | 2a03:b0c0:3:d0::58:1001:37745/udp(relay) [non-proxied] | 2607:5300:60:3118:::19392/udp(host) | 1 | 2830967580147711 | 0 | 0

and

PeerConnection ID: 1588855768508050 (id=38654705737 url=https://test.bigbluebutton.org/html5client/join?sessionToken=kbfeubepvve6nonv)
ICE Stats
ICE State | Nominated | Selected | Local Candidate | Remote Candidate | Component ID | Priority | Bytes sent | Bytes received
-- | -- | -- | -- | -- | -- | -- | -- | --
succeeded | true | true | 2a02:8070:88ab:6b00:2513:c2df:288a:e93:40175/udp(host) [non-proxied] | 2607:5300:60:3118:::28660/udp(host) | 1 | 8646913479229178000 | 1543 | 3777
succeeded | true | false | 2a02:8070:88ab:6b00:7f3d:75e5:111b:4e8a:36296/udp(host) [non-proxied] | 2607:5300:60:3118:::28660/udp(host) | 1 | 8646913479229047000 | 0 | 0
inprogress | false | false | 192.168.0.20:44447/udp(host) [non-proxied] | 192.99.0.24:31291/udp(host) | 1 | 8646913474933948000 | 0 | 0
succeeded | true | false | 46.5.255.250:58155/udp(srflx) [non-proxied] | 192.99.0.24:31291/udp(host) | 1 | 7240978959985280000 | 0 | 0
failed | false | false | 192.168.0.20:52711/tcp(host) [non-proxied] | 192.99.0.24:25589/tcp(host) | 1 | 4341473339235861000 | 0 | 0
failed | false | false | 2a02:8070:88ab:6b00:2513:c2df:288a:e93:55338/tcp(host) [non-proxied] | 2607:5300:60:3118:::28051/tcp(host) | 1 | 4341472239724495400 | 0 | 0
failed | false | false | 2a02:8070:88ab:6b00:7f3d:75e5:111b:4e8a:49894/tcp(host) [non-proxied] | 2607:5300:60:3118:::28051/tcp(host) | 1 | 4341472239724364300 | 0 | 0
cancelled | false | false | 2a03:b0c0:3:d0::58:1002:49203/udp(relay) [non-proxied] | 2607:5300:60:3118:::28660/udp(host) | 1 | 35501031169197052 | 0 | 0
cancelled | false | false | 46.101.180.168:60209/udp(relay) [non-proxied] | 192.99.0.24:31291/udp(host) | 1 | 35219556192486390 | 0 | 0
cancelled | false | false | 46.101.180.168:63016/udp(relay) [non-proxied] | 192.99.0.24:31291/udp(host) | 1 | 35219556192486390 | 0 | 0

And the Javascript Console output, accepting the echo test, despite no sound heard, and trying to share the webcam:
[console-export-2020-5-7_15-8-32.txt](https://github.com/bigbluebutton/bigbluebutton/files/4593095/console-export-2020-5-7_15-8-32.txt)

**Comment by tobiasjj** [comment]
@prlanzarin Unfortunately, I do not have a running buster. I could setup a virtual machine (VirtualBox). However, this would take me some time.

**Comment by Findus23** [comment]
Just to confirm this: For me (Debian Testing, Firefox 76 from Sid), Audio also doesn't work anymore.

I can provide more details later.

**Comment by tobiasjj** [comment]
I tested two different Firefox versions with Debian Buster in a VirtualBox:
* Firefox 76 from Sid shows the same issue as described above.
* Firefox ESR works as expected.

**Comment by flipreverse** [comment]
I tested two different systems showing different results:
- Ubuntu 20.04 FF 76.0 works
- Debian Sid FF 76.0 shows the same issue as described at the beginning.

**Comment by gaudenz** [comment]
I have the same issue with FF 76 from Debian Sid on a system otherwise running Debian testing.

**Comment by GrosQuicKFR** [comment]
Same issue on Debian Sid+FF76
I use Chromium for now.
br

**Comment by tobiasjj** [comment]
The [bug](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=960012) was resolved with the firefox package version 76.0.1-1 in debian sid. I tested it and everything works again. I'll therefore close this issue.
