### ISSUE TITLE
The microphone no show for  viewer role

### ISSUE THREAD

**Issue by dfsandoval** [bigbluebutton/bigbluebutton#9456]
I created a room by medium of the api and the moderador role have microphone but viewer role no have microphone. How i can do that the viewer role have the option of microphone, by medium of the api with of create or join

example api create:

https://example.com/bigbluebutton/api/create?name=Test+Meeting&meetingID=abc123&attendeePW=111222&moderatorPW=333444&checksum=12345

example api join:

https://example.comt/bigbluebutton/api/join?fullName=John2&meetingID=abc123&password=111222&redirect=false&joinViaHtml5=true&checksum=12345

**Comment by basisbit** [comment]
This issue tracker is only for BBB development related issues. For API questions, please use the development support forum at https://groups.google.com/forum/#!forum/bigbluebutton-dev

**Comment by matiasilva** [comment]
Please close this issue since you have been provided a response. Additionally, I recommend the users forum https://groups.google.com/forum/#!forum/bigbluebutton-users for support.
