### ISSUE TITLE
sip.nginx - did not find the use of port 7443 in definition for proxy_pass

### ISSUE THREAD

**Issue by marcoz9090** [bigbluebutton/bigbluebutton#9457]
I followed the steps here to use https
https://docs.bigbluebutton.org/2.2/install.html#configure-nginx-to-use-https

Running "sudo bbb-conf --check" I get the following error:
# Potential problems described below
# Warning: You have this server defined for https, but in
#
#   /etc/bigbluebutton/nginx/sip.nginx
#
#  did not find the use of port 7443 in definition for proxy_pass
#
#            proxy_pass https://192.168.128.76:7433;
#

This is the configuration of my "sip.nginx":
location /ws {
        proxy_pass https://192.168.128.76:7433;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_read_timeout 6h;
        proxy_send_timeout 6h;
        client_body_timeout 6h;
        send_timeout 6h;
}

Is there anything else I need to change?

Thank you,
Marco.

**Comment by pedrobmarin** [comment]
7443

**Comment by basisbit** [comment]
This issue tracker here is for development issues and feature requests, not for support. Please use https://groups.google.com/forum/#!forum/bigbluebutton-setup instead.

**Comment by marcoz9090** [comment]
@pedrobmarin 
omg you are right, I just wrote the wrong port.
Thank you for pointing that out, it works now!

**Comment by Mylinuxforyou** [comment]
```
location /ws {
        proxy_pass https://myip :7443;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_read_timeout 120s;
        proxy_send_timeout 120s;
        client_body_timeout 120s;
        send_timeout 120s;

        auth_request /bigbluebutton/connection/checkAuthorization;
        auth_request_set $auth_status $upstream_status;
}
```

---------------
Warning: The setting of -------ip ------or proxy_pass in
#
#    /usr/share/bigbluebutton/nginx/sip.nginx
#
# does not match the local IP address (1.10.19.63).
# (This is OK if you've manually changed the values)
