### ISSUE TITLE
End/leave meeting button

### ISSUE THREAD

**Issue by sdekock** [bigbluebutton/bigbluebutton#9459]
We are embedding the BBB HTML5 client into our application. After a meeting ends we want to redirect the users back our application to continue using it.

Currently this is a achievable by the end meeting/logout links in the options menu. But this is hidden out of sight for users that might not be familiar with BBB. They rather might just close the app/browser.

We want to have a big "End meeting" button somewhere clearly visible.

**Comment by haviduck** [comment]
when the moderator ends the meeting all participants are sent to the logout url, bbbs webhooks canalso  inform your system that inturn redirects your users.

they do have some docs on editing the html5 client, but i found it alot easier to Just inject html through js.

**Comment by Migu5499** [comment]
> when the moderator ends the meeting all participants are sent to the logout url, bbbs webhooks canalso inform your system that inturn redirects your users.
> 
> they do have some docs on editing the html5 client, but i found it alot easier to Just inject html through js.

Hi im new, how i can change html with that, i try make the changes in inspect element, the call end button, works. how i can change that directly on my server ?

**Comment by haviduck** [comment]
edit This file and add whatever js lib you like along with your custom js. when dom is ready you can alter it how you like. id probably try the onbeforeunload eventhandler along with a Nice dialog as its less likely to break your ui. 
im trying my best to read up and learn as much as i can on bbb, the prs are amazing and we should strive for that level of quality, my humble approach here is pretty hackish. 
`usr/share/meteor/bundle/programs/web.browser/head.html`

-restart after edit.

**Comment by Migu5499** [comment]
> edit This file and add whatever js lib you like along with your custom js. when dom is ready you can alter it how you like. id probably try the onbeforeunload eventhandler along with a Nice dialog as its less likely to break your ui.
> im trying my best to read up and learn as much as i can on bbb, the prs are amazing and we should strive for that level of quality, my humble approach here is pretty hackish.
> `usr/share/meteor/bundle/programs/web.browser/head.html`
> 
> -restart after edit.

thank you! but i was serarching more to change the button, like waht the button do and add a text dow, change button color, etc. hope u can help me i learn little more today!

**Comment by matiasilva** [comment]
Hi guys. Merging this with #9938 seeing as the discussion here sort of went off topic.  If you need further help with developing the client, use https://groups.google.com/forum/#!forum/bigbluebutton-dev. See you there.
