### ISSUE TITLE
Unstable Audio and Video mostly error 1007 with some internet providers

### ISSUE THREAD

**Issue by atrex123** [bigbluebutton/bigbluebutton#9460]
I have problems some times i can use microphone sometimes not.

error 1007 with me sometimes and with some internet providers always. both WiFi and 4g

sometimes error 1020 about webcam.

**Comment by basisbit** [comment]
Hi, this issue tracker here is for development related issues, not for support questions. Please instead use the community forum at https://groups.google.com/forum/#!forum/bigbluebutton-users
