### ISSUE TITLE
Error 1004 on demo server

### ISSUE THREAD

**Issue by ostasevych** [bigbluebutton/bigbluebutton#9461]
When I try to use demo.bigbluebutton.org and changing the headphones I am getting error  1004 without any chance to start the meeting.

![image](https://user-images.githubusercontent.com/5199030/81345144-979d2400-90c0-11ea-83d6-cfbfcc040d34.png)

**Comment by defnull** [comment]
Same issue with Firefox 75. Chrome works. Firefox worked, too, a couple of days ago. A recent Firefox upgrade might have broken something? The `sip.js` shipped with BBB is quite old.

**Comment by matiasilva** [comment]
Do you experience the same error still? If not, close the issue.

**Comment by wwwsbox24ru** [comment]
Have the same issue!
Please help

**Comment by matiasilva** [comment]
@wwwsbox24ru please use the mailing lists for support requests

I'm going to close this issue due to lack of follow up.
