### ISSUE TITLE
Welcoming message in the common chat

### ISSUE THREAD

**Issue by ostasevych** [bigbluebutton/bigbluebutton#9462]
I found that the welcoming text which appears in Common chat is partially not localised (translated).
My suggestion is to get rid of it at all and place the link and the button on copying the link somewhere under the newly created icon (i), eg like in Jitsi.

![image](https://user-images.githubusercontent.com/5199030/81348623-11d0a700-90c7-11ea-8c89-7c726f43dc30.png)

**Comment by TivanDev** [comment]
you can change message 
```
defaultWelcomeMessage=
defaultWelcomeMessageFooter=
```
in this file
`/usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties`

**Comment by matiasilva** [comment]
An adequate response to this issue has been provided. Please close it.

**Comment by amohideen** [comment]
@matiasilva after changing values for the 
defaultWelcomeMessage=
defaultWelcomeMessageFooter=
configs, I could still see the links to the tutorial videos. Can this be changed in html5client ?

**Comment by matiasilva** [comment]
The HTML5 client receives this information from bbb-web. Try restarting the server that should do it.
