### ISSUE TITLE
Using a management Server to manage different BBB Servers

### ISSUE THREAD

**Issue by haeferer** [bigbluebutton/bigbluebutton#9466]
Hi, 

nice and cool work,

thanx to corona we try to use BBB on our school (800 users) . But we need to use more than ONE BBB server. 

1. We made a central managment server (management.someschool.com)

2. We use the API at one of our BBB Server (bbb05.someschool.com) from the central management Server  to create a meeting (works)
3. We use the API to create a JOIN url  at the  management server  (works)

if we redirect the user to the URL https://bbb05.someschool.com/html5client/join?sessionToken=tokencreated

401 => Session not found

It seems that the management server must always be at the same session management system on the same server ?

so the api cant be used from a central server...

Thx again for your great work. 

Would be fine, if it's a bug from our site

**Comment by basisbit** [comment]
You might want to take a look at [Scalelite](https://github.com/blindsidenetworks/scalelite).
If that is exactly what you were searching for, please don't forget to close this issue here.

**Comment by haeferer** [comment]
Thx four your support. Will have a look on this.

**Comment by haeferer** [comment]
Solved the Problem.

BBB Accepts Join Request only if there is a valid JSEssionID available (managed by greenlight). This is some kind of counterproductive, if you want to manage the BBB without a frontend like GreenLight to create and share a JSessinID.
 
Solution

Since BBB 2.2 you can change this behaviour using a property called

`allowRequestsWithoutSession`

in ` /usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties`

(you need to restart for this to take effect)
