### ISSUE TITLE
Man-in-the-middle protection for webrtc/dtls

### ISSUE THREAD

**Issue by pRiVi** [bigbluebutton/bigbluebutton#9467]
Please address man-in-the-middle attacks on the video/audio data.

Please understand me correctly: Yes, data is encrypted with SRTP, but currently I cannot see any protection against man in the middle attacks, like the one descriped on

https://webrtchacks.com/webrtc-and-man-in-the-middle-attacks/

Further, if you have done work for securing and I did not find so far, like certificate pinning, don't use SHA1 for this, cause it has [security weakness](https://de.wikipedia.org/wiki/Secure_Hash_Algorithm#SHA-1):

> root@bkssrv1:/opt/freeswitch/conf/tls# openssl x509 -in wss.pem -noout -text
> Certificate:
>     Data:
>         Version: 1 (0x0)
>         Serial Number: 0 (0x0)
>     **Signature Algorithm: sha1WithRSAEncryption**
>         Issuer: C=US, CN=FreeSWITCH
>         Validity
>             Not Before: May  1 07:38:45 2020 GMT
>             Not After : Apr 14 07:38:45 2120 GMT
>         Subject: C=US, CN=FreeSWITCH
>         Subject Public Key Info:
>             Public Key Algorithm: rsaEncryption
>                 Public-Key: (4096 bit)
>                 Modulus:
> ...

**Is your feature request related to a problem? Please describe.**
Passive monitoring of traffic seems to be save, but if you have an attacker which can do man-in-the-middle, if I have not overseen a securing of you, a self signed certificate cannot help about that cause the client cannot verify to be connected to a trusted service and the server never is doing that.

**Describe the solution you'd like**
Maybe it is possible to use the SSL certificates from the web server?

**Describe alternatives you've considered**
Maybe you can verify via certificate pinning?

**Additional context**
Sorry if I have overseen a securing method from you against man-in-the-middle attacks. And please differ: I am not saying that video and/or audio is unencrypted transported, I just say that a man-in-the-middle attack can lead to allow an attacker to access the audio and/or video data.

**Comment by basisbit** [comment]
Shouldn't the webbrowser handle that already when WebRTC traffic is transmitted over TLS / WSS?

**Comment by pRiVi** [comment]
No, look and the end of https://docs.bigbluebutton.org/2.2/architecture.html video and audio is transmitted via UDP on own ports, via DTLS, which seems to currently cannot be secured by certificates... On any solution and any browser...

**Comment by basisbit** [comment]
It should be rather easy to transfer "trusted" fingerprints over the signalling path, which is done over SIP over WSS and then hope that WebRTC HTML5 API offers something to set a trusted fingerprint for DTLS.

**Comment by basisbit** [comment]
Actually, https://tools.ietf.org/html/rfc5763 describes this:
> how to use the Session Initiation Protocol
   (SIP) to establish a Secure Real-time Transport Protocol (SRTP)
   security context using the Datagram Transport Layer Security (DTLS)
   protocol.  It describes a mechanism of transporting a fingerprint
   attribute in the Session Description Protocol (SDP) that identifies
   the key that will be presented during the DTLS handshake.  The key
   exchange travels along the media path as opposed to the signaling
   path.  The SIP Identity mechanism can be used to protect the
   integrity of the fingerprint attribute from modification by
   intermediate proxies.

@pRiVi wouldn't this solve exactly the problem which you mentioned?

**Comment by pRiVi** [comment]
Hm... If you can implement this in this way: Of course. But war are not talking about a API where you can simply access the encryption key. Or are we?

The mentioned document tells that it is currently not possible to do that... So... can you anyway?

**Comment by pRiVi** [comment]
To resolve this problem there seems only to exist a now expired draft from 2019: https://tools.ietf.org/html/draft-ietf-rtcweb-security-arch-20

**Comment by znerol** [comment]
This is covered by [RFC 4572](https://tools.ietf.org/html/rfc4572). You can look at SIP/SDP messages passed between the browser and FreeSWITCH using your browsers console.

Look for a line starting with `a=fingerprint` during echo test in the SDP answer from FreeSWITCH. In my case this is a SHA256 fingerprint. Then find the `dtls-srtp.pem` file inside the `tls` subdirectory of your freeswitch config on the server. Examine that file using the following `openssl` command:

```
openssl x509 -noout -fingerprint -sha256 -in dtls-srtp.pem
```

Note that the SIP/SDP messages are passed via websocket between the browser and FreeSWITCH via Nginx proxy. This requires a valid/trusted certificate in Nginx. Note that you can apply as much hardening as necessary on your nginx config (such as HSTS, HKPK and whatever you desire).

I haven't checked the video part though. I guess this requires some digging in kurento. I also did not perform a MITM attempt myself.

**Comment by pRiVi** [comment]
@znerol Nice, I will try to verify this, and also do a man-in-the-middle attempt... Maybe we want to close this until I get a result about that?

**Comment by prlanzarin** [comment]
@znerol Kurento can be configured to use specific .pem files for DTLS-SRTP in `/etc/kurento/modules/kurento/WebRtcEndpoint.conf.ini` -> `pemCertificateRSA/pemCertificateECDSA`. If they're not set, it'll generate self-signed certificates to use. It uses the fingerprinting mechanism as you described with SHA-256.

The signalling for the Kurento stuff does not use SIP, but it does use a custom protocol that goes over WSS via the nginx reverse proxy, so it's secured.

**Comment by erotavlasme** [comment]
What about e2e encryption with WebRTC insertable streams as [jitsi is currently testing](https://jitsi.org/blog/e2ee/)?

**Comment by basisbit** [comment]
erotavlasme that would not solve the issue mentioned in this here issue (which by the way is probably not even a valid issue - we just wait for pRiVi to post test results). Also, e2e encryption would effectively break the server side recirding feature and reduce performance of video sharing. Thus, e2ee doesn't work as a solution for this issue here and is another issue.

**Comment by erotavlasme** [comment]
Ok thank you. It would be good at least to have an option to select between e2e and client-server encryption. Moreover, client side recording is still possible, for instance via recordRTC plugin.

**Comment by basisbit** [comment]
@erotavlasme please do not spam this issue with off-topic requests.

**Comment by prlanzarin** [comment]
@erotavlasme  Insertable streams and E2E encryption are all hip and good looking due to the Zoom misconception debacle, but the first one is highly experimental and has reduced browser support and it'd require a lot of time on our side to make it work for too little return ATM. That time might as well be spent on actual polish and improvements that make the platform more stable and easy to use. So not a thing that will be in the plans anytime soon (but feel free to try to do it).

**Comment by erotavlasme** [comment]
@prlanzarin I do not what are BBB roadmap and priorities. However, e2ee is not important just a due to Zoom security holes, but to protect user privacy in whatever communication service.
However, we can comment [here](https://github.com/bigbluebutton/bigbluebutton/issues/9893), since apparently we are off-topic.

**Comment by prlanzarin** [comment]
Closing this because 1) stale 2) DTLS-SRTP works, certs are configurable, fingerprinting mechanisms are in place for both FS and KMS
