### ISSUE TITLE
How can i set the log level to CRIT AND ERROR

### ISSUE THREAD

**Issue by agustinmono** [bigbluebutton/bigbluebutton#9471]
My log files are too large, how can i set the log level to ERR
http://prntscr.com/sdh5qh

I have this :
http://prntscr.com/sdh65b

but keeps debuggin me

thanks

**Comment by basisbit** [comment]
please see https://docs.bigbluebutton.org/admin/privacy.html

**Comment by fireba11** [comment]
please don't ship things with loglevel set on debug ...

**Comment by basisbit** [comment]
@fireba11 if you are good with bash and got some spare time, please help improve the bbb-install script to also set the log level and all the other privacy stuff: https://github.com/bigbluebutton/bbb-install/issues/202

**Comment by fireba11** [comment]
i'll have a look when i find time ..
loglevel debug in freeswitch is not so much a privacy issue but a production setting issue. i got >4 GB logs in 2 weeks and was running out of disk space. log rotation is set to 45 files with 1GB each if i remember correcty. that is just not how that code should be shipped. where is that config from?

**Comment by basisbit** [comment]
those configs are mostly the defaults from the various projects that BigBlueButton makes use of. Thus, it probably would be easiest to just adjust the logging settings after installation of these components using for example sed.

**Comment by fireba11** [comment]
i don't know my way around the freeswitch project .. can somone double-check the default loglevel are from there and raise an issue there then?
their config is rather convoluted with different loggers set up etc. so i'm not quite sure what's the minimal change to get it to quiet down (and have the installer script set it like that) :-(
