### ISSUE TITLE
Server completely crash, many users in one room

### ISSUE THREAD

**Issue by MathieuPre** [bigbluebutton/bigbluebutton#9473]
Hello,
We face a big issue with bbb server 2.2.9.
We have offer a conference with many people connected in one room.
It was all fine since 250 people connected in. But after some time the amount of users have increased and the BBB service completely crash.
I there any way to improve the amount of users take in charge into a single room ?
I am open to share logs and chat with helpful people or devs. 
For information it was a dedicated server with huge performance and lot of bandwidth.
Thanks

**Comment by ffdixon** [comment]
We recommend for the current version of BigBlueButton that no single room have more than 100 users.  See

  http://docs.bigbluebutton.org/support/faq.html#how-many-simultaneous-users-can-bigbluebutton-support

A larger server will not make a difference as there are architectural limitations (such as nodejs running on only a single CPU core) that limit the number of users in a session.

We're working on raising the number of users in a session in the next release, which will be BigBlueButton 2.3.

**Comment by matiasilva** [comment]
Seeing as this issue has received an adequate response, please close it.
