### ISSUE TITLE
Stopped: BigBlueButton recording and playback sanity check worker (recordings not being processed)

### ISSUE THREAD

**Issue by Buda9** [bigbluebutton/bigbluebutton#9476]
I have installed 2.2.2 version of BBB using install.sh. When I run a meeting through moodle and record it that recoding is not being published. When I come back to the command line I can see the following error when running bbb-record --list

# bbb-record --list 

... **Stopped** BigBlueButton recording and playback sanity check worker.

or here: [last 3 screenshots](https://postimg.cc/gallery/d0MRX66)

No meetings in the last month have been processed or published, not even short 1min meetings.

And when I use "rebuild #specific-ID" on not processed/publishe recordings I got this error:

bbb-record rebuild #ID shows: "Raw files for #ID do not exist, can't rebuild"

And when I use bbb-record --debug I got this error messages: http://prntscr.com/sdq5wa

Note:

bbb-conf --check shows no problems
bbb-conf --status shows everything is active
bbb-conf --restart does nothigs to fix issues

**Comment by ffdixon** [comment]
Recommend you first update to the latest version of BigBlueButton (at the time of this writing it's 2.2.9).

**Comment by Buda9** [comment]
Hi Fred. Thank you very much for your reply. I've just upgraded to 2.2.9 and I the issue still persist.: https://postimg.cc/gallery/Fr2jZDX

What I'm curious about is this: "Active: inactive (dead) since Fri 2020-04-10 09:32:17 EDT; 4 weeks 2 days ago".

Also, should I be consired about this line: "ConditionPathExistsGlob=/var/bigbluebutton/recording/status/archived/*.done was not met" Screenshot here: https://i.postimg.cc/ZKwchdh2/Screenshot-23.png

Few notes:

- bbb-conf --check: https://i.postimg.cc/vBw7v7Wg/Screenshot-24.png
- bbb-conf --status: https://i.postimg.cc/Y0p15pDt/Screenshot-25.png
- bbb-record --debug: http://prntscr.com/se7kcc
- /var/log/bigbluebutton/bbb-rap-worker.log: https://postimg.cc/gallery/vy39Z81

I have enough free disk space, it's 8 cpu/32gb ram dedicated server and no errors during the installation or upgrade. However server (from interserver dot net) is probably virtualized. Could that be an issue?

**Comment by matiasilva** [comment]
Have you solved this issue? If so, please close this issue.

A few observations:

* FreeSWITCH has nothing to do with this and its performance under a virtualized environment even less so
* Which worker is displaying as inactive? 
* The issue with the .done file seems to suggest that the archiving failed.

I suggest you read the documentation on recording and see if that helps.

**Comment by nefester000** [comment]
@Buda9 Hi, I am facing the same issue. Did you find a way to resolve this?

**Comment by Buda9** [comment]
Nope, I still have the same issue. No matter what version or update I install. However, I didn't try with 2.3-alpha yet

**Comment by eledia** [comment]
I running version 2.2.14.
Before I update my ubuntu- packages and restart my server, everything works well.
After restarting my server und restart bbb once more, with  
bbb-record watch
I see all services are stopped
Stopped BigBlueButton recording and playback archive worker.
Stopped BigBlueButton recording and playback sanity check worker.
Stopped BigBlueButton recording and playback process worker.
Stopped BigBlueButton recording and playback publish worker.
Any ideas how I can fix this ?

**Comment by ffdixon** [comment]
If the recordings are not processing, the log files should tell you why.  For the record and playback, the following systemd unit files are used

 * bbb-rap-archive-worker.service 
 * bbb-rap-sanity-worker.service 
 * bbb-rap-process-worker.service 
 * bbb-rap-publish-worker.service 
 * bbb-rap-events-worker.service

Each unit file has a log that you can follow.

  sudo journalctl -f -u bbb-rap-archive-worker.service

Also, each recording that processed has it's own log.  See

 https://docs.bigbluebutton.org/dev/recording.html#troubleshooting
