### ISSUE TITLE
Enable phone users to be moved to breakout rooms by moderators, or by themselves without re-dialing.

### ISSUE THREAD

**Issue by lekker-xr** [bigbluebutton/bigbluebutton#9480]
**Is your feature request related to a problem? Please describe.**  
Participants who are dialed in by phone cannot be moved to breakout rooms by moderators or by phone keys. It is frustrating to hang up and re-dial. (And up for now, even this does not work, see \[[issue 9478](/bigbluebutton/bigbluebutton/issues/9478)\]).

**Describe the solution you'd like**  
Add the ability for moderators to move phoned-in participants to breakout rooms. Even if normal participants cannot be moved by moderators, for phoned-in participants this is a good service since they do not have the GUI.

Also add *or document* (I don't know if they are) the possibility to move yourself to breakout rooms or to the main room by pressing a number key.

**Additional context**  
Related issue (bug):  \[[Issue 9478: "Not possible to dial into breakout rooms via telephohe"](/bigbluebutton/bigbluebutton/issues/9478)\].

**Comment by pedrobmarin** [comment]
Merging with https://github.com/bigbluebutton/bigbluebutton/issues/8586
