### ISSUE TITLE
Make the telephone-PIN static per room.

### ISSUE THREAD

**Issue by lekker-xr** [bigbluebutton/bigbluebutton#9482]
**Is your feature request related to a problem? Please describe.**  
When having only the telephone available, it is difficult to join a conference, because the telephone PIN get's dynamically created when a conference is started. It cannot be shared straig after room creation and configuration.

**Describe the solution you'd like**  
The possibility to have a fixed telephone PIN, easiest to equal the online room access code (if one is configured), which can be pre-shared when people get invited to the meeting.

**Describe alternatives you've considered**    
Phoning friends to quickly log in and retrieve the PIN for me, asking other participants to SMS the pin, ...

**Additional context**  
As it is now, it excludes people who do _not_ have (easy) internet access when the conference starts.

**Comment by wmchris** [comment]
the pin can be set from the frontend. greenlight just doesnt do it. use another frontend.

**Comment by lekker-xr** [comment]
> the pin can be set from the frontend. greenlight just doesnt do it. use another frontend.

Thanks.

Can it be seen as a feature request for greenlight?

Changing the frontend would be some trouble for quite a user base of our server.

**Comment by lekker-xr** [comment]
> Can it be seen as a feature request for greenlight?

Filed as an issue for greenlight: https://github.com/bigbluebutton/greenlight/issues/1572

And closing it hereby at this spot.

**Comment by npsimons** [comment]
>  use another frontend.

What other frontend supports this?
