### ISSUE TITLE
Changer server ip to a new one

### ISSUE THREAD

**Issue by atrex123** [bigbluebutton/bigbluebutton#9485]
Is there a guideline to change all VPS server IP to a new one without any problem?

my previous IP must change to a new one

**Comment by MrCapitalist** [comment]
Hi
You can use `bbb-conf` command:

use `bbb-conf --setip` to re-assign your servers IP address or hostname to BigBlueButton’s configuration files.

`$ sudo bbb-conf --setip <IP_or_hostname>
$ sudo bbb-conf --check`

or if you had configured your server with hostname `bbb.example.com,` you would do

`$ sudo bbb-conf --setip bbb.example.com
$ sudo bbb-conf --check`

**Comment by atrex123** [comment]
salam bar shoma. merci baray pasokh

Yes. but this exclusively changes the BBB config, it seems that some other modifications in client XML and API should occurs

**Comment by atrex123** [comment]
> 
> 
> Hi
> You can use `bbb-conf` command:
> 
> use `bbb-conf --setip` to re-assign your servers IP address or hostname to BigBlueButton’s configuration files.
> 
> `$ sudo bbb-conf --setip <IP_or_hostname>`
> `$ sudo bbb-conf --check`
> 
> or if you had configured your server with hostname `bbb.example.com,` you would do
> 
> `$ sudo bbb-conf --setip bbb.example.com`
> `$ sudo bbb-conf --check`
> 
> Note that you must edit subdomain A record to your new IP
salam mamnoon. take a look at this
https://github.com/ehomework/bigbluebutton-fork/wiki/Instructions-for-changing-IP

**Comment by MrCapitalist** [comment]
سلام وقتتون بخیر. نه مشکلی نداره همون کامند خودش تمام کارها رو انجام میده نگران نباشید

**Comment by bwurst** [comment]
I can confirm that this is not true. I changed via bbb-conf --setip [newhostname] and after that checked via bbb-conf --check and there were some places left with the old ip address. Used an editor to replace the remaining one by one.

**Comment by MrCapitalist** [comment]
> I can confirm that this is not true. I changed via bbb-conf --setip [newhostname] and after that checked via bbb-conf --check and there were some places left with the old ip address. Used an editor to replace the remaining one by one.

I think you need to upgrade your BBB to latest version. I changed my hostname few times and I didn't have any problem. Try [bbb-install](https://github.com/bigbluebutton/bbb-install) script

**Comment by taikedz** [comment]
In parallel, I can confirm that not only does it leave old IP addresses in place, it changes some FQDN entries to the explicit IP

The net result is that when starting a conference after using `bbb-conf --setip` has been invoked make the conference attempt to redirect to the site's IP - and the TLS certificate is then invalid and the user rightly gets a big fat warning.

FWIW, simply re-running `install.sh` from https://github.com/bigbluebutton/bbb-install sets up new IPs etc correctly. You can omit using the `-g` option in this scenario, if you had greenlight already installed on your instance.

**Comment by atrex123** [comment]
> I can confirm that this is not true. I changed via bbb-conf --setip [newhostname] and after that checked via bbb-conf --check and there were some places left with the old ip address. Used an editor to replace the remaining one by one.

Exactly  this is how it works for me

**Comment by atrex123** [comment]
> > I can confirm that this is not true. I changed via bbb-conf --setip [newhostname] and after that checked via bbb-conf --check and there were some places left with the old ip address. Used an editor to replace the remaining one by one.
> 
> I think you need to upgrade your BBB to latest version. I changed my hostname few times and I didn't have any problem. Try [bbb-install](https://github.com/bigbluebutton/bbb-install) script

No my friends, we are not talking about hostname or setting IP for first time, for changing vps ip after bbb-conf --setip, a check command will show us other files that need to change, after nano ...change manually and request for renewal of LTS  SSL this works for me

**Comment by systemcon** [comment]
Guys, I have an A record pointing at my BBB server. The IP address is still the same but i want to change the domain name. I had install BBB with install script using SSL.

Is there any easy way to update the domain name from bbb.example.com to xxx.example.com and have SSL configured corectly? 

It would be perfect if it is possible to change the domain name without losing my custom configuration at the BBB server files.

What is the best way to handle the change?

**Comment by taikedz** [comment]
@systemcon You can re-run the install script, it will take care of that on its own.

Otherwise, use certbot to get a new cert and update nginx

```sh
git clone https://github.com/certbot/certbot
cd certbot
sudo ./certbot-auto -d xxx.example.com
sudo sed -i 's/bbb.example.com/xxx.example.com/g' /etc/nginx/sites-available/<your bbb site>
sudo bbb-conf restart
```

(off the top of my head ; double-check)

**Comment by systemcon** [comment]
Thanks for the reply, re running the script with the new domain name will it replace my BBB configuration? For example html5 client settings, favicon, some custom settings at camera quality levels etc?
________________________________

**Comment by basisbit** [comment]
@systemcon yes, any reinstall and also most updates will overwrite your BBB configuration. Please use the `apply-config.sh` script to reapply your modifications after each update - see https://docs.bigbluebutton.org/2.2/customize.html#automatically-apply-configuration-changes-on-restart

@atrex123 were all your questions answered? Can we close this issue here?

**Comment by asim-quadri** [comment]
while installation how to assign ip address instead of domain name
