### ISSUE TITLE
Remove/Replace the Help Section Link From BBB

### ISSUE THREAD

**Issue by hackzie** [bigbluebutton/bigbluebutton#9487]
Hi, I have installed bbb in my server but i want to change the url of the help section button. Please help me. I have attached 2 images , Please have a look on them.
![s1](https://user-images.githubusercontent.com/35571313/81501176-7886d800-92f4-11ea-9b42-64efecf46ec3.png)
![s2](https://user-images.githubusercontent.com/35571313/81501180-7ae93200-92f4-11ea-9cf7-e60f80755294.png)

**Comment by frank-miller9** [comment]
```/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml```

Either

```helpLink: https://bigbluebutton.org/html5/```

or 

```showHelpButton: true```

**Comment by hackzie** [comment]
Thanks for the solution! It worked fine in the meeting page but this command did not change the url in user page (see first screenshot)

**Comment by frank-miller9** [comment]
As I don't know the first screen, is this greenlight then?
