### ISSUE TITLE
Long list of errors after bbb-conf --clean

### ISSUE THREAD

**Issue by ralferlebach** [bigbluebutton/bigbluebutton#9488]
**Describe the bug**
Getting a long list of errors after a  successful start of the server when tying to clear all error logs via bbb-conf --clean.

**To Reproduce**
1. Clear the logs and restart BBB (bbb-conf --clean)
2. Pull error and warnings out from the log files (bbb-conf --debug)
3. Get error list

**Expected behavior**
A rather short or even empty error and warnings list when the server runs smoothly and without any troubles.

**Actual behavior**
A long and repretitive list of connection errors with the alternating pattern:

   -- Errors found in /var/log/nginx/error.log --
(1) 2020/05/10 17:09:17 [error] 7750#7750: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 89.163.224.132, server: *HOSTNAME*, request: "GET /bigbluebutton/api HTTP/1.1", upstream: "http://127.0.0.1:8090/bigbluebutton/api", host: "*HOSTNAME*"
(2) 2020/05/10 17:09:17 [error] 7750#7750: *1 open() "/var/www/nginx-default/50x.html" failed (2: No such file or directory), client: 89.163.224.132, server: *HOSTNAME*, request: "GET /bigbluebutton/api HTTP/1.1", upstream: "http://127.0.0.1:8090/bigbluebutton/api", host: "*HOSTNAME*"
Line (1) and (2) alternates for several rounds and pile up to a long list of error warnings.

**Server configuration:**
Ubuntu 16.04 as suggested
Used the installion skript
BBB 2.2.9 (updated from a fresh installed 2.2.5)

**Proposed solutions**
I suppose that those error messages occure when services are still not running at tjhe process of starting up the server. However I understand that logging the start up phase is a crucial action in order to trouble shoot.
Therefore I recommend to:
1) Implement a bbb-conf command like --clear-logs that clear (and/or archive) all log files WITHOUT restarting BBB or any sub services so that warnings and errors can be tracked down when troubleshooting and reproducing errors in an easier way. (That would get rid of the first line in the error list for administrators.)
2) Make a directory "/var/www/nginx-default" and a file "50x.html" as part of the installation skript. (This solves the second line, even applying bbb-con --clean with a restart of the server.)

**Comment by matiasilva** [comment]
If this is an enhancement, please add the enhancement tag to your issue.
