### ISSUE TITLE
Add a setting for number of cameras to be displayed

### ISSUE THREAD

**Issue by tdjac0bs** [bigbluebutton/bigbluebutton#9490]
**Is your feature request related to a problem? Please describe.**
When we have a large meeting ( 40 users ) and all sharing webcam, we get a very high bandwidth usage in server ( 300 mbps ). 

And the webcams get super small, not providing the best communication.

**Describe the solution you'd like**
I would like to limit number of webcams displayed in browser ( a config parameter ). Let's say 8 webcams. So even if 40 webcams in the room, we would see a maximum of 8 cameras.

In order to choose who would be displayed, system could use the information of the 8 users that was talking more recently. So when a user start talking it get promoted to be displayed, and the last one get demoted.

**Describe alternatives you've considered**
One alternative would be to handle it in server side, but it seems much easier in terms of resources to handle it on client side, choosing what streams to subscribe/unsubscribe.

**Comment by ffdixon** [comment]
We have a lot customers using BigBlueButton for K12, and in the early grades it's really important that the kids see each other in the session.   

Consider a class of 25 students, all sharing their webcam, that would normally create 25*25=625 streams.  If there are only 8 active webcams, what to show for the other 17?

One idea would be to have the user take a snapshot of themselves when previewing the webcam.  This would give an image that BigBlueButton could use as the user's avatar when their stream is not active.

This way, each user would see 25 images, but only 8 would be updating at one time.

**Comment by iSamof** [comment]
It seems, the biggest challenge to scaling up and maximising server resources is performance and performance is heavily impacted by the number of webcams. This webcam config/limit solution will help enormously. Two points:

1. It would be best, if this control should be configurable per meeting (not server wide), so priority can be given to some users and their meetings/classes. This allows custom distribution of resources. 

2. Based on feedback from our beta users, this issue of webcams and performance is our (BBB's) biggest apparent disadvantage when compared to Zoom etc. 

Side Note: Behind the scenes, bare metal vs cloud, attendees/meeting (yes improvement coming) and total users per server, are our biggest challenges in terms of cost per meeting. But those are for other threads (being discussed).

**Comment by raoulkramer** [comment]
A kind of applicable solution is noted in this issue, it could be help full to merge these options https://github.com/bigbluebutton/bigbluebutton/issues/9392

**Comment by prlanzarin** [comment]
Merging with https://github.com/bigbluebutton/bigbluebutton/issues/9392.
