### ISSUE TITLE
Failed recordings - error in events_archiver.rb - strip_control_chars

### ISSUE THREAD

**Issue by lightweight** [bigbluebutton/bigbluebutton#9491]
Following the upgrade to BBB 2.2.9 (in which events_archiver.rb changed, introducing the strip_control_chars function, presumably to address a security vulnerability), when attempting to process recordings on BBB workers (created via bbb-install) on two Ubuntu 16.04 instances (behind a Scalelite front end, although I don't think this is relevant), I'm getting a consistent error that's halting the archiving process:

```
INFO -- : /usr/local/bigbluebutton/core/lib/recordandplayback/events_archiver.rb:232:in `strip_control_chars': undefined method `tr' for nil:NilClass (NoMethodError)
INFO -- :       from /usr/local/bigbluebutton/core/lib/recordandplayback/events_archiver.rb:267:in `store_events'
INFO -- :       from archive/archive.rb:39:in `archive_events'
INFO -- :       from archive/archive.rb:198:in `<main>'
INFO -- : Exit status: 1
ERROR -- : Failed to archive 6231ed2959a41d7f50e27a9b6df417ded67dfe29-1588566362330
```

**To Reproduce**
1. upgrade to BBB 2.2.9
2. Record a BBB session
3. Watch /var/log/bigbluebutton/bbb-rap-worker.log
4. When the recording is processed, it fails with this message, suggesting a problem with casting the variable 'str' to a string, so that it has the 'tr' method.

**Expected behavior**
Recording is processed to an archive and subsequently published.

**Actual behavior**
Archiving of recordings consistently fails.

**Further Notes**
Prior versions of the events_archiver.rb file (e.g. on another instance of BBB I haven't upgraded yet) do not exhibit this behaviour, because the strip_control_chars function doesn't exist (yet).

**Comment by matiasilva** [comment]
Does this error still persist? If not, post your solution and close this issue.

**Comment by lightweight** [comment]
It still occurs, and I've been tracking updates (now on 2.2.17). The current error has a different line number (suggesting a change to the script further up :) ):
'''
 INFO -- : /usr/local/bigbluebutton/core/lib/recordandplayback/events_archiver.rb:232:in `strip_control_chars': undefined method `tr' for nil:NilClass (N
oMethodError)
I, [2020-06-12T05:42:41.882528 #28226]  INFO -- :       from /usr/local/bigbluebutton/core/lib/recordandplayback/events_archiver.rb:267:in `store_events'
I, [2020-06-12T05:42:41.882545 #28226]  INFO -- :       from archive/archive.rb:38:in `archive_events'
I, [2020-06-12T05:42:41.882559 #28226]  INFO -- :       from archive/archive.rb:197:in `<main>'
I, [2020-06-12T05:42:41.884622 #28224]  INFO -- : Exit status: 0
I, [2020-06-12T05:42:41.884753 #28224]  INFO -- : Executing: ruby utils/captions.rb -m c9c5b752be70b4559f23c358883c18b51e446761-1591054323349
I, [2020-06-12T05:42:41.888277 #28226]  INFO -- : Exit status: 1
E, [2020-06-12T05:42:41.888565 #28226] ERROR -- : Failed to archive 60347d662c74c7f810ec7f05cb9168be66738370-1591938022736
'''

**Comment by techie-explorer** [comment]
Still facing this issue in v.2.2.20...

**Comment by matiasilva** [comment]
Hi, make sure to post more information on your setups and custom changes to debug. I haven't seen many others experiencing this issue, so it is likely due to how your servers are set up.

**Comment by aogilvie** [comment]
I also still have this issue in 2.2.23

**Comment by pedrobmarin** [comment]
Handled in https://github.com/bigbluebutton/bigbluebutton/pull/8950 & https://github.com/bigbluebutton/bigbluebutton/pull/10238
