### ISSUE TITLE
Recording Result : Whiteboard Tools Misses away from Presentation 

### ISSUE THREAD

**Issue by rezaervani** [bigbluebutton/bigbluebutton#9492]
**Describe the bug**
We manage about 1 hour presentation for class, use pdf uploaded to presentasion and whiteboard tools (pen, text etc). Everything going well in live session. Use BBB 2.2.9 and GreenLight 2.0

But recording result is different, all text, boundaries, line around presentation misses away from the place, not the same as what appears at the live presentation. It shown in screeshot below

![Screenshot from 2020-05-11 12-17-53](https://user-images.githubusercontent.com/5996010/81526722-9e5abe00-9382-11ea-9b4c-a319568a8c9b.png)

Is this client or server issues ?

**Comment by rezaervani** [comment]
We've changed and upgraded server. The problem still exist.

All I see was y position misses away, but x position is match. If I want to try reproduce cursor.xml to fix y position, what should I do ?

Thank your very much

**Comment by pedrobmarin** [comment]
Can we close this one, @kepstin ?

**Comment by kepstin** [comment]
I'm pretty sure this isn't a recording processing issue. It seems like incorrect positions/offsets might have been sent by the client when doing drawing? I seem to recall that we may have had issues like this relating to use of the fit to width mode on portrait documents.

**Comment by antobinary** [comment]
Resolved in BBB 2.6
