### ISSUE TITLE
Chrome screenshare extension key

### ISSUE THREAD

**Issue by hbruch** [bigbluebutton/bigbluebutton#9493]
In various places the key of the chrome-screencast-extension is declared as `akgoaoikmbmhcopjgakkcepdgdgkjfbc`.
This currently results a [404 error response](https://chrome.google.com/webstore/detail/bigbluebutton-screenshare/akgoaoikmbmhcopjgakkcepdgdgkjfbc). Only available plugin seems to be

`https://chrome.google.com/webstore/detail/bigbluebutton-screenshare/ldjhogfpafjhgbhcgccghdjdnjmoaafi`

Is this the official plugin all references should be corrected to?

**BBB version (optional):**
BigBlueButton Server 2.2.9
 
**Desktop (please complete the following information):**
 - OS: Win10
 - Browser Bromium (Chrome based)

**Comment by basisbit** [comment]
There is no need for any screen sharing plugin. The HTML5 based web-client of BigBlueButton supports screen-sharing out of the box since about a year ago.
Screen sharing currently only work from desktop webbrowsers as source, because Chrome/Firefox/Safari don't support this yet on Android or iOS - there are people currently working at this.

If this answered your question, please don't forget to close this issue here.

**Comment by hbruch** [comment]
When users using the Chromium derived browser Bromium (desktop, Version 68.0.3440.136 (Official Build) (64-Bit)) want to share their screen, they get a notice telling them they should install this plugin.

On the server BBB 2.2.9 is installed. Maybe the html5 requires a browser feature not included in that version(?). As the users can't upgrade easily themselves, is there any additional information which could be helpful when approaching their IT departement/the browser vendor, e.g. min Chromium version, or enabled features?

**Comment by ffdixon** [comment]
That version of Chromium is very old -- Chrome is currently at version 81.  

The older versions of Chrome did require the addition of an extension for supporting screen sharing, but later versions dropped the requirement.

Is there a newer version of Bromium that uses a later version of Chromium?

**Comment by prlanzarin** [comment]
@hbruch although the recommended thing to do would be to just update the browsers, I reckon locked down enterprise-grade setups can be hard to update. We have not depreciated support for extension-based screen sharing (**_yet_**). You just have to set up your own screen sharing extension for your company/domain as detailed in https://github.com/bigbluebutton/screenshare-chrome-extension.

**Comment by hbruch** [comment]
@prlanzarin Thanks for this hint. I wasn't aware that the plugin needs to be customized to support server domains. I'll check with the IT department, if updating the browser or installing a customized plugin is possible.
