### ISSUE TITLE
No iOS Camera with 2.2.9 Error 1020

### ISSUE THREAD

**Issue by marcohald** [bigbluebutton/bigbluebutton#9494]
**Describe the bug**
Since the latest Update the Camera share is broken on iOS.
Everything else is working except the Camera share.

**To Reproduce**
1. Update to latest version
2. Connect via iOS and share camera

**Expected behavior**
Video Stream

**Actual behavior**
Error 1020

**BBB version:**
$ sudo bbb-conf --check | grep BigBlueButton
BigBlueButton Server 2.2.9 (1891)

**Smartphone (please complete the following information):**
 - Device: iPhone 8
 - OS:  iOS 13.4.1
 - Browser Safari

**Additional context**
Same Phone is working on demo2.bigbluebutton.org
Server is full dual stack. No Nat.
Turn Server is configured and working
The Problem is on all tested iOS devices since the lat BBB Update.
No difference if using LTE or WiFi

**Comment by marcohald** [comment]
Here is the log from /var/log/apt/history.log
Start-Date: 2020-05-07  15:01:42
Commandline: apt full-upgrade
Upgrade: bbb-html5:amd64 (1:2.2.0-882, 1:2.2.0-894), bbb-record-core:amd64 (1:2.2.0-63, 1:2.2.0-65), bbb-web:amd64 (1:2.2.0-123, 1:2.2.0-124), bbb-freeswitch-core:amd64 (2:2.2.0-103, 2:2.2.0-104), bbb-apps-akka:amd64 (2.2.0-80, 2.2.0-81), bbb-config:amd64 (1:2.2.0-173, 1:2.2.0-176)
End-Date: 2020-05-07  15:02:04

**Comment by basisbit** [comment]
works fine here, so this is a configuration problem. Check your TURN server configuration and consider using the [`apply-config.sh`](https://docs.bigbluebutton.org/2.2/customize.html#automatically-apply-configuration-changes-on-restart) script to reapply all your customization after each update. Also make sure to always run `bbb-conf --setip bbb.yourdomain.tld`

**Comment by olivierDevin** [comment]
Hi everyone,
Same issue here.
My stun server is ok :
test I = 1
test II = 1
test III = 1
test I(2) = 0
is nat  = 0
mapped IP same = 1
hairpin = 0
preserver port = 0
Primary: Open
Return value is 0x000010

bbb-conf --setip is ok too.

Any idea ?

**Comment by marcohald** [comment]
@basisbit sorry for that. I was sure that it is a bug and not a config Problem.
Indeed i have missed the step "bbb-conf --setip ".
It was driving me crazy that only our ios devices had this problem.
Now everything works again.
It might be a good idea to add Warning in bbb-conf --check which indicates that bbb-conf --setip was not run after an update.
For example add a comment in the config file like "#setip" and delete that when bbb-conf --setip is called.
