### ISSUE TITLE
bbb-record --watch table output is misaligned

### ISSUE THREAD

**Issue by debuglevel** [bigbluebutton/bigbluebutton#9496]
**Describe the bug**
Output of `bbb-record --list/--watch` is misaligned. Maybe because of 4-letter "`CEST`"?

![image](https://user-images.githubusercontent.com/2401265/81568995-e7207000-939e-11ea-8ff5-e24f137fb71d.png)

**Comment by debuglevel** [comment]
Or it is due to 2-digit day?
![image](https://user-images.githubusercontent.com/2401265/81569244-526a4200-939f-11ea-8195-c55c8ca16558.png)

**Comment by matiasilva** [comment]
Any progress or updates? Does this issue still persist? If not, close the issue.

**Comment by ffdixon** [comment]
It's the four letter CEST that is throwing off the formatting.  Should be an easy fix.

**Comment by hex-m** [comment]
Still happening in `2.3.9`.

**Comment by hex-m** [comment]
@crosscodr The chances of inclusion are probably higher, if you create a PR out of your patch. But either way: thanks for the effort!
