### ISSUE TITLE
Disable audio check on entering or leaving of a breakout room. [HTML5 Client]

### ISSUE THREAD

**Issue by lekker-xr** [bigbluebutton/bigbluebutton#9502]
**Annoying:**  
Each time a participants switches to a breakout room or back, an audio test is forced.  
This interrupts the conference flow, also because it needs some time.  
It is contra-intuitively to the user, since the audio test was alrady done when beginning the conference, and thus the system should "remember" that it works.

**Describe the solution you'd like**  
Audio test only once when initially joining the conference via audio; remember the results also for switching between breakout rooms and main room; no repeated audio tests.

**Comment by alangecker** [comment]
there is already a related issue https://github.com/bigbluebutton/bigbluebutton/issues/8387 and an open Pull Request https://github.com/bigbluebutton/bigbluebutton/pull/8696 which, apparently, is going to resolve this with the v2.3 release.

**Comment by lekker-xr** [comment]
> there is already a related issue #8387 and an open Pull Request #8696 which, apparently, is going to resolve this with the v2.3 release.

So I close this issue hereby.
