### ISSUE TITLE
Per-room configurable default presentations ("warm greetings" for the room, on a per room basis).

### ISSUE THREAD

**Issue by lekker-xr** [bigbluebutton/bigbluebutton#9503]
**Annoying:**  
We have a BigBlueButton server with different conference rooms with different purposes. We want a warm greeting on the rooms (default presntations's first slide), but different rooms should have different greetings.

But for now, the default presentation can only be changed server-wide, and individual presentations get deleted after the conference ends.

(greenlight frontend)

**Describe the solution you'd like**  
Possibility to configure default presentations on a _per room_ basis,

**Comment by frank-miller9** [comment]
I do not use greenlight, but this is possible with the API. So the question is: can greenlight be extended in that way.

(reference: https://docs.bigbluebutton.org/dev/api.html#create search for "welcome")

**Comment by lekker-xr** [comment]
> but this is possible with the API. So the question is: can greenlight be extended in that way.

So I posted this as \[[a feature-request for greenlight (#1579)](https://github.com/bigbluebutton/greenlight/issues/1579)\] and closing the issue hereby at this location.
