### ISSUE TITLE
How do I specify to install the bigbluebutton version?

### ISSUE THREAD

**Issue by z-j-j** [bigbluebutton/bigbluebutton#9508]
wget -qO- https://ubuntu.bigbluebutton.org/bbb-install.sh | bash -s -- -v xenial-22 -a

This command can automatically install the latest version of bigbluebutton. If I want to install version 2.2.5, how can I specify to install version 2.2.5?

**Comment by mabras** [comment]
This is not supported right now.

**Comment by matiasilva** [comment]
Doesn't seem like a feature that makes much sense either. BBB is a constantly changing piece of software, with important critical fixes. It's recommended that you update to the latest version. Please close this issue.

**Comment by deepeshs** [comment]
I am also looking for the way to install specific version (lets say 2.2.10 instead of always latest release) of bigbluebutton server. My use case is to keep sync of versions between different development stages like qa server and prod server.

Let us know if there is a way to achieve this or please see if this feature can be supported on bigbluebutton.

**Comment by matiasilva** [comment]
There is a way to do this by specifying a -v option for bbb-install.sh but you'd have to know the package name. For example `-v  xenial-220`. I'm not aware of a way to find this out easily nor do I know if old releases are kept in the repositories.

**Comment by matiasilva** [comment]
Ah, after further digging you can install versions as so: `-v xenial-220-2.2.9` for 2.2.9. I'm closing this issue as I've answered the original question that was posed.

**Comment by jakiro2017** [comment]
> Ah, after further digging you can install versions as so: `-v xenial-220-2.2.9` for 2.2.9. I'm closing this issue as I've answered the original question that was posed.

I tested this on a 2.2.17 instance and it doesn't work :(
`wget -qO- https://ubuntu.bigbluebutton.org/bbb-install.sh | bash -s -- -w -v xenial-220-2.2.9 -a -w`

**Comment by matiasilva** [comment]
Oh. You can read [this](https://groups.google.com/forum/#!searchin/bigbluebutton-dev/xenial-220-2.2.9%7Csort:date/bigbluebutton-dev/BKCT_Ydi-n8/6isr05OWAgAJ) for more info on where I got it from. I'll see if it works for others.

**Comment by jakiro2017** [comment]
> Oh. You can read [this](https://groups.google.com/forum/#!searchin/bigbluebutton-dev/xenial-220-2.2.9%7Csort:date/bigbluebutton-dev/BKCT_Ydi-n8/6isr05OWAgAJ) for more info on where I got it from. I'll see if it works for others.

Hi, after a wipe, that's command work.
Summary:

```
apt-get purge bbb-apps bbb-apps-akka bbb-apps-screenshare bbb-apps-sip bbb-apps-video bbb-apps-video-broadcast bbb-client bbb-config bbb-freeswitch-core bbb-freeswitch-sounds bbb-fsesl-akka bbb-html5 bbb-mkclean bbb-playback-presentation bbb-record-core bbb-red5 bbb-swftools bbb-transcode-akka bbb-web bbb-webrtc-sfu bigbluebutton
wget -qO- https://ubuntu.bigbluebutton.org/bbb-install.sh | bash -s -- -w -v xenial-220-2.2.9 -a -w
```

**Comment by testprepturkey** [comment]
> 

Does it delete the recordings also?
