### ISSUE TITLE
Video Quality Changes don’t seem to do anything

### ISSUE THREAD

**Issue by Maxpower7847** [bigbluebutton/bigbluebutton#9509]
**Describe the bug**
I habe been trying to improve the quality of the camera picture in the bbb-html5-client but i noticed that there doesn't seem to be any perceivable difference between the medium and the high definition option. For testing purposes i cranked the bitrate of the high definition profile in settings yml up to 5000 but it still looks the same. is there anything I am missing ? 

**To Reproduce**
1. start meeting
2. select medium canera quality
3. select high definition quality
4. see no difference
5. change high def bitrate in settings.yml to 5000
6. still see no difference

**Expected behavior**
See better inage quality with higher bitrate

**Actual behavior**
Picture still not great

**Screenshots**

**BBB version (optional):**
BigBlueButton Server 2.2.6 (1871)

**Desktop (please complete the following information):**
 - OS: Android, iOS and Windows
 - Browser Firefox, Chrome and Safari (iOS)
 - Version all updated to the respective latest Versions

**Additional context**
The network Speed is high enough for loads of more data and the server it is running on never goes above 12% cpu and ~40% memory usage

**Comment by ffdixon** [comment]
Can you try changing the settings as per the docs

  http://docs.bigbluebutton.org/2.2/customize.html#reduce-bandwidth-for-webcams

Try dropping it to 50 to see if the quality reduces -- that way you know your changes are taking effect, and then try raising the quality again.  

You can also see the effect of change by choosing a different level of quality in the client when sharing the webcam as well.  The above is really just setting the default values for each quality choice.

**Comment by Maxpower7847** [comment]
> Can you try changing the settings as per the docs
> 
> 
> 
>   http://docs.bigbluebutton.org/2.2/customize.html#reduce-bandwidth-for-webcams
> 
> 
> 
> Try dropping it to 50 to see if the quality reduces -- that way you know your changes are taking effect, and then try raising the quality again.  
> 
> 
> 
> You can also see the effect of change by choosing a different level of quality in the client when sharing the webcam as well.  The above is really just setting the default values for each quality choice.

First off thank you for your reply!
I tried that and setting the bitrate to 50 significantly reduces the image quality further. But at around 500 kbps it seems to cap out and doesnt improve any further. 
Interestingly enough the load on the server however does goe higher. I created a bunch of custom profiles and did the following measuremnts using nload and taking an rough average over about 20 seconds:
 
format is "stream quality-setting:  incoming(kbit/s)/outgoing(kbit/s)"

no stream running: 50/130
50: 85/200
200: 230/360
500: 550/680
2000: 1600/1700

so it seems to me that the client is transsmitting a higher bitrate video but that the higher bitrate doesnt translate to a higher quality (again the image doesnt get any better after about the 500 kbit setting).
I tested this using a surface pro 7, the camera ob the device is normaly quite good. 


But what I also realized: while the camera quality on the sending device is significantly better than the one on client-side it is also nowhere near as good as it is when i am using the integrated camera app. 

It semms like the image is lowered to about an 480p-resolution. is there maybe some limitation on the resolution side as well  ?

**Comment by Maxpower7847** [comment]
Update:
the Problem really seems to have been the video resolution not improving properly. By introducing constraints for width and height I can improve the camera quality to be much better and it is really good now (although it would be better if it changed through the resolutions on its own if anyone knows a way for that that would be great. Otherwise it is much better now than before

**Comment by TheJJ** [comment]
How did you set width/height constraints to improve the video quality?

**Comment by prlanzarin** [comment]
The configuration accepts a regular constraints dictionary.
See MDN docs: https://developer.mozilla.org/en-US/docs/Web/API/MediaStreamConstraints/video, https://developer.mozilla.org/en-US/docs/Web/API/MediaTrackConstraints.

**Comment by einhirn** [comment]
Here is what worked for us when testing it:
```
    cameraProfiles:
    - id: HighDef
      name: HighDef
      default: false
      bitrate: 1500
        constraints:
        width: 1280
        height: 720
        frameRate: 30
```
Interestingly we weren't able to get the Bitrate above 1500 even when setting the value here to e.g. 3000. Still trying to find out why.

**Comment by herzkerl** [comment]
Is anyone able to stream 1080p with BigBlueButton?

> Interestingly we weren't able to get the Bitrate above 1500 even when setting the value here to e.g. 3000 (would like to do that for Full HD 1080). Still trying to find out why.

@einhirn Have you made any progress?

**Comment by einhirn** [comment]
We haven't looked into it any further yet.

So, we can stream 1080p, but the quality, i.e. calculated BPP value isn't up to our standards. YMMV, maybe you can decide on how it looks (subjective) instead of what a spreadsheet says (objective)... Also you need to keep the bandwidth and CPU usage on the server in mind.

**Comment by herzkerl** [comment]
@prlanzarin Sorry for mentioning you, but since I wasn't able to find any information on max. bitrate regarding camera quality, I'd hope you could elaborate why it seems the bitrate won't go above around 1500, hence "1080p quality" doesn't seem to be viable. Thank you!

**Comment by prlanzarin** [comment]
Probably the built in congestion control algorithms kicking in on both ends (via REMB), thus effectively lowering the upper bitrate limits.
I suppose you could go over 1.5mbps and ignore packet loss/re-transmissions from receiving ends by tuning the REMB params to make the cc inflexible enough. The parameters I'm talking about are https://github.com/bigbluebutton/bbb-webrtc-sfu/blob/v2.4.x-release/config/default.example.yml#L149-L151.

Don't need to change rembOnConnect (kbps) since it gets overwritten with the source camera profile bitrate (ie 300 gets overwritten with 3000).
My memory falters me a bit on how to better tune those other three configs, though, because they're kind of tricky to work with. I had a hard time back then coming up with those values. I'll experiment with them a bit on my free time to see if there are values that make it work a bit less strictly and get back to you.

**Comment by prlanzarin** [comment]
btw I'm closing this issue since there's no point in it being open (the OP report is not an issue).

**Comment by prlanzarin** [comment]
@herzkerl Ran some tests over the weekend.
It's the congestion control being finicky for sure. And I couldn't constraint it via the REMB parameters.
Only way I guaranteed a packet-loss ignoring stream was when re-compiled Kurento with the REMB code commented out (which granted me, for instance, a stable 2mbps stream).

Now: the CC being finicky isn't bad per se. We don't have simulcasting so, as a baselne, we need congestion control to be as zealous as possible (in detriment of stream quality).
I'll run some more tests later on the week to see what's up with the congestion control parameters; they should be working but they seem unresponsive at best.

**Comment by herzkerl** [comment]
> I'll run some more tests later on the week to see what's up with the congestion control parameters; they should be working but they seem unresponsive at best.

@prlanzarin No pressure, but do you have any news to share?

**Comment by DDQW** [comment]
I also habe this problem. We do have a shitton of bandwith available (25 Gigabits) and we have at most 2 camers going on at the same time (audience has cam disabled) so in theory we could go extremly nuts. So i set bitrate to 10000 at high definition (that is a bit above youtube for FullHD 60FPS) but it kinda looks not that great. And yes HD was selected and i also made it the default.

So is there maybe any news in bbb 2.3 (we are running 2.3.3) to make stuff look good or even better than zoom 1080p?

**Comment by Nuxij** [comment]
Same here, higher bitrates still lead to terrible compression. Is the server reencoding it or something?

**Comment by jacquesdupontd** [comment]
I've been exploring nearly every line of code to find an answer to this as well. I can't believe nobody can give an answer ? Bigbluebutton is amazing, i don't understand why we can't decide to only share one camera and have it in Full HD 60 fps without any compression as it is possible with Webrtc. If someone found a solution i'd be happy to learn about it, thanks

**Comment by prlanzarin** [comment]
> I've been exploring nearly every line of code to find an answer to this as well. I can't believe nobody can give an answer ? Bigbluebutton is amazing, i don't understand why we can't decide to only share one camera and have it in Full HD 60 fps without any compression as it is possible with Webrtc. If someone found a solution i'd be happy to learn about it, thanks

I gave an "answer" a few comments back and in other issues as well: we don't have simulcast, congestion control with KMS is(was) overzealous (+ I think there is/was a bug with how lost packets are accounted for via RTCP with video-only endpoints in KMS which made it overzealous). That's just how it is. Moreover, BigBlueButton currently targets accessibility over quality, so things _will_ be scaled down.

You'll probably have better luck achieving higher bitrate/qualities by trying out mediasoup: https://docs.bigbluebutton.org/2.4/new.html#mediasoup. It's congestion control is significantly more predictable and stable than KMS's.

Finally: I'm happy to engage in discussions about this _in the mailing lists_, preferably. Try not to revive _closed_ issue, please.

**Comment by jacquesdupontd** [comment]
> > I've been exploring nearly every line of code to find an answer to this as well. I can't believe nobody can give an answer ? Bigbluebutton is amazing, i don't understand why we can't decide to only share one camera and have it in Full HD 60 fps without any compression as it is possible with Webrtc. If someone found a solution i'd be happy to learn about it, thanks
> 
> I gave an "answer" a few comments back and in other issues as well: we don't have simulcast, congestion control with KMS is(was) overzealous (+ I think there is/was a bug with how lost packets are accounted for via RTCP with video-only endpoints in KMS which made it overzealous). That's just how it is. Moreover, BigBlueButton currently targets accessibility over quality, so things _will_ be scaled down.
> 
> You'll probably have better luck achieving higher bitrate/qualities by trying out mediasoup: https://docs.bigbluebutton.org/2.4/new.html#mediasoup. Its congestion control is significantly more predictable and stable than KMS's.
> 
> Finally: I'm happy to engage in discussions about this _in the mailing lists_, preferably. Try not to revive _closed_ issues, please.

Thanks a lot for you reply (i was about to digg the mediasoup road) and really sorry to make an ultimate message but i think i've just found a workaround thanks to your previous answer. If you modify `kurentoRemoveRembRtcpFb:` from `false` to `true`
in `/usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml` i have the impression that the quality gets way better and seemingly without compression after a minute or so (taking into account your settings in VP8 or H264 just above), and it does impact also the recording which was based on the stream. I have made the test multiple times to be sure but you might want to try it yourself to confirm i'm not hallucinating (which happens when you've been trying so many different things). Don't hesitate to delete my message or to tell me to delete it if you feel it is not relevant to other users.

ps: maybe you also need to change the value of `rembOnConnect:`

**Comment by prlanzarin** [comment]
> > > I've been exploring nearly every line of code to find an answer to this as well. I can't believe nobody can give an answer ? Bigbluebutton is amazing, i don't understand why we can't decide to only share one camera and have it in Full HD 60 fps without any compression as it is possible with Webrtc. If someone found a solution i'd be happy to learn about it, thanks
> > 
> > 
> > I gave an "answer" a few comments back and in other issues as well: we don't have simulcast, congestion control with KMS is(was) overzealous (+ I think there is/was a bug with how lost packets are accounted for via RTCP with video-only endpoints in KMS which made it overzealous). That's just how it is. Moreover, BigBlueButton currently targets accessibility over quality, so things _will_ be scaled down.
> > You'll probably have better luck achieving higher bitrate/qualities by trying out mediasoup: https://docs.bigbluebutton.org/2.4/new.html#mediasoup. Its congestion control is significantly more predictable and stable than KMS's.
> > Finally: I'm happy to engage in discussions about this _in the mailing lists_, preferably. Try not to revive _closed_ issues, please.
> 
> Thanks a lot for you reply (i was about to digg the mediasoup road) and really sorry to make an ultimate message but i think i've just found a workaround thanks to your previous answer. If you modify `kurentoRemoveRembRtcpFb:` from `false` to `true` in `/usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml` i have the impression that the quality gets way better and seemingly without compression after a minute or so (taking into account your settings in VP8 or H264 just above), and it does impact also the recording which was based on the stream. I have made the test multiple times to be sure but you might want to try it yourself to confirm i'm not hallucinating (which happens when you've been trying so many different things). Don't hesitate to delete my message or to tell me to delete it if you feel it is not relevant to other users.
> 
> ps: maybe you also need to change the value of `rembOnConnect:`

Yes. I've implemented that REMB override somewhere along the BBB 2.3 timeline to atenuate this issue. I think it was discussed in another issue? Can't remember. 

Feel free to use it, prefer setting it as an override /etc/bigbluebutton/bbb-webrtc-sfu/production.yml. Enjoy.
