### ISSUE TITLE
Create API example for integration with LDAP

### ISSUE THREAD

**Issue by bigbluebutton-issue-import** [bigbluebutton/bigbluebutton#951]
Originally reported on Google Code with ID 196

```
LDAP integration for company / university integration would be nice. It
would allow a single sign-in environment. The only competitor for AD / LDAP
integration is dimdim as far as I know. 
```

Reported by `jonathon.klobucar` on 2009-09-25 13:07:21

**Comment by ffdixon** [comment]
The integration with LDAP would be handed by a front-end application that connects to BigBlueButton.

We've released GreenLight, which can be used with LDAP, as a sample (and highly configurable) front-end for BigBlueButton.  See

   http://docs.bigbluebutton.org/install/green-light.html#ldap-oauth

While there are other applications that can also integrate with BigBlueButton and LDAP, the above will get anyone going who is interested in using LDAP with BigBlueButton.
