### ISSUE TITLE
Change behaviour of locking Shared Notes

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#9511]
Currently, when shared notes are locked, the viewers have "Locked" indicator next to their name.

Change this so when Shared Notes are locked,

1. Don't show the "Locked" indicator
2. Change the title of the Shared notes panel from "< Shared Notes" to "< Shared notes (locked for viewers)"

This makes it easier to set the shared notes locked by default, and doesn't make any overt change in the main use cases.

Most deployments do not lock Shared Notes, but the above is very useful for K12 use of BigBlueButton.

**Comment by antobinary** [comment]
Revised list of requirements:
1. Do not display Locked if the only lock is Shared notes
2. Change the title of the Shared notes panel from "< Shared Notes" to "< Shared notes (locked for viewers)"
3. Disable the menu for Unlock user if the only lock is on Shared notes
4. If there are SharedNotes and [one] more locks and you unlock a user, shared notes should still be locked for that user (essentially for all)

We may also want to look into dividing the Lock Settings modal into Locking users and Locking features in the future to try to avoid confusion - why Locked is not applied if this setting is locked, why is it not unlocked if we unlock a user. This would be for later. Any thoughts @tylercopeland ?

**Comment by tylercopeland** [comment]
@antobinary this all makes sense. I'm working through adjustments to the lock settings experience, that I will share in the upcoming weeks. 

One recommendation I have is to display "[lock icon] Locked]" below the shared notes sidebar item. We can keep the suggestion of adding the locked to the title as well, but having it in the sidebar makes it clear to the user before they dive into the experience. 

![Screen Shot 2020-05-12 at 2 16 04 PM](https://user-images.githubusercontent.com/1273169/81730357-65424c80-945b-11ea-96fb-cafb74c0a288.png)
