### ISSUE TITLE
Disable shared notes or only enable for teacher

### ISSUE THREAD

**Issue by lipsmega** [bigbluebutton/bigbluebutton#9512]
Hi. 

Im having trouble with shared notes, as its anonymous and available for all in a session. Id like to disable it or allow it only for teacher,moderator,etc. Can I solve it already? I didnt find any way to do it. tnks!

**Comment by antobinary** [comment]
Hi @lipsmega ,
You can lock shared notes for viewers, see the images below

![Screenshot from 2020-05-12 13-52-13](https://user-images.githubusercontent.com/6312397/81728081-e13a9580-9457-11ea-9277-80a2b4a57b92.png)
![Screenshot from 2020-05-12 13-52-32](https://user-images.githubusercontent.com/6312397/81728087-e4ce1c80-9457-11ea-8c93-91355aba9a0d.png)

Also keep an eye on https://github.com/bigbluebutton/bigbluebutton/issues/9511 which tweaks this slightly - aimed at BigBlueButton 2.2.10 (next minor release)

Also on your server you could set the lock to be on by default, see


```
$ grep "lockSettingsDisableNote=false" /usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties
lockSettingsDisableNote=false
```
+restart of BBB

If you want it set on specific meetings only, you can pass a create [meeting] parameter to specify the desired lock settings search "lockSettings" in http://docs.bigbluebutton.org/dev/api.html#create

**Comment by lipsmega** [comment]
Thanks a lot man!! I didnt find it by myself :)

**Comment by mtcsathya** [comment]
Thank you
