### ISSUE TITLE
css pollingAnswers 

### ISSUE THREAD

**Issue by nguyenxuanhoa493** [bigbluebutton/bigbluebutton#9519]
hi
in mobile pollingAnswers  so big and student cannot focus to slide
i created file custom.css for pollingAnswers 
[class*="pollingAnswers"]{
display:flex !important;
}
[class*="pollingButton"]{
	width:auto !important;
}

[class*="pollingContainer"]{
	top:90% !important;
	height: fit-content !important; 
}

@media only screen and (max-width: 768px) {
  /* For mobile phones: */
  [class*="pollingContainer"]{
	top:78% !important;
  }
}
before
![before](https://user-images.githubusercontent.com/65268672/81768183-8f9c1480-9504-11ea-9e26-cc61b0a4690a.jpg)
after
![after](https://user-images.githubusercontent.com/65268672/81768177-8dd25100-9504-11ea-86c2-467a3572f3a4.jpg)

**Comment by matiasilva** [comment]
Hi. This seems like a great addition. Could you turn this into a pull request and submit it?
