### ISSUE TITLE
Need a way to share files within a conference

### ISSUE THREAD

**Issue by bigbluebutton-issue-import** [bigbluebutton/bigbluebutton#952]
Originally reported on Google Code with ID 197

```
Right now there is no way to share any kind of file between conference
participant, which may be useful in many cases.

Suggest developing a way for a presenter to upload a file to the server so
that participants can downloaded it while in conference
```

Reported by `Me.Snap` on 2009-09-29 13:30:39

**Comment by ffdixon** [comment]
In the latest build of BigBlueButton 2.2-beta, the presenter can upload a presentation and mark it as available for download.

![image](https://user-images.githubusercontent.com/290351/57973838-e536f300-797c-11e9-8a85-22a116238e17.png)

Any presentation marked as available for download has a download icon in the lower left-hand corner.

![image](https://user-images.githubusercontent.com/290351/57973835-dc462180-797c-11e9-859a-bdba3ac7614f.png)

**Comment by samuelpeixoto** [comment]
It's a great idea! 
We already have the ability to upload files for presentations, however, this would allow uploading files to support learning such as: Excel, PPT, Word, video, MP3, any type of file you want to provide to participants during the conference.
Any news?

**Comment by gabrielestella** [comment]
There is something to prevent the deletion of file inside a room?

**Comment by hex-m** [comment]
> this would allow uploading files to support learning such as: Excel, PPT, Word, video, MP3, any type of file you want to provide to participants during the conference.

There is work going on: https://github.com/bigbluebutton/bigbluebutton/pull/8753
