### ISSUE TITLE
Ask for confirmation when pressing F5 (Refresh)

### ISSUE THREAD

**Issue by cdir** [bigbluebutton/bigbluebutton#9521]
**Describe the bug**
When I accidently press F5 (refresh) the meeting is restarted and I have to wait for the echo test again. Most time I pressed F5 because I want to refresh another browser which is in my screen share but I had the focus in wrong application. I think the behavior to restart the meeting is fine but just ask the user "Do you realy want to reconnect?"

**To Reproduce**
1. Start a meeting
2. press F5 on your keyboard
3. wait for echo test

**Expected behavior**
When pressing F5 a confirmation dialog appears asking for "Do you realy want to reconnect?"

**Actual behavior**
The conference is restarting immediately when pressing F5.

**Comment by trs80** [comment]
Fairly simple, just need to add https://developer.mozilla.org/en-US/docs/Web/API/Window/beforeunload_event Note that modern browsers don't support customising the prompt.

**Comment by matiasilva** [comment]
Not sure how important this is to most users. Seems like a nuisance is someone actually wants to reload the page. Close this issue as discussion has gone stale.

**Comment by einhirn** [comment]
Please keep this open - I have lost count on how often I dropped out of a conference by accidentially sending a CTRL-R to the BBB Browser tab that was intended for some other App while multitasking. Also: I really like mouse gestures for browser navigation, but this also creates a risk of unwanted "history.back()" during a BBB session.

**Comment by pedrobmarin** [comment]
@antobinary does BBB wants this feature? If it does, ask @frankemax more about it.

**Comment by ffdixon** [comment]
It's very easy to reload a BigBlueButton session to renew all the connections, which is good.  Adding a confirmation dialog could be done, but I would recommend putting it behind a feature flag (in bbb-web.properties) so those that really want it can have it, but the default behaviour is the current behaviour.

**Comment by antobinary** [comment]
Implemented in BBB 2.6 via https://github.com/bigbluebutton/bigbluebutton/pull/15842
![Screenshot from 2022-12-14 10-12-21](https://user-images.githubusercontent.com/6312397/207633791-5d9dcaf9-62ed-4e6f-8378-8be8cfc38cef.png)
