### ISSUE TITLE
Make Easy to set status

### ISSUE THREAD

**Issue by hhamed1989** [bigbluebutton/bigbluebutton#9522]
Hi Dears

**Set Status**
I'm searching for the way that make set status easy. for exp the icons on main page and when user want to raise hand just click on it. (not need to go user menu click on username and set status.)

**Show Status**
When a user set status, in long user list is difficult to find it. and many times the teacher can't see that student raise his hand. it's nice that show user status on users webcam or top of the whiteboard show the users that change their status. (for examples raise hands).

I appreciate it if let me know if there is any way to do these or add the futures to change the location of status (set and show).

Best Regards,
Hamed Haghshenas

**Comment by SamuelWei** [comment]
Duplicate #9072 
Please contribute to our discussion

**Comment by matiasilva** [comment]
Closing as it's a duplicate.
