### ISSUE TITLE
Accepted by moderator users are guests

### ISSUE THREAD

**Issue by matiasilva** [bigbluebutton/bigbluebutton#9523]
**Describe the bug**
If the wait room is on to only allow people in via moderator approval, they join as guests. I can't promote users to moderator if they are in this mode and this name "guest" never disappears.

**To Reproduce**
1. Enable wait room
2. Approve an incoming request to join the room
3. Click on the user and try to promote to moderator

**Expected behavior**
The user would be promoted to moderator

**Actual behavior**
Clicking the promote to moderator button does nothing.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Firefox
 - Version 76.0.1

**Comment by pedrobmarin** [comment]
I'll be closing this one since is a duplication of https://github.com/bigbluebutton/bigbluebutton/issues/7460
