### ISSUE TITLE
hide individual vote to a presenter/moderator

### ISSUE THREAD

**Issue by hvdort** [bigbluebutton/bigbluebutton#9524]
The current implementation (2.2.9) of the Poll functionality is not usable for voting. while the moderator/presenter sees the individual votes. Is it possible to suppress this (option)? (privacy/election secrecy)

**Comment by ichdasich** [comment]
All the voting implications apart... 

This is also a thing for lecturing. I also like to collect student feedback via the poll function, and would like to be able to offer anonymous feedback so students are not afraid of giving negative feedback.

**Comment by frank-miller9** [comment]
Not that it is a 100% secure way, but editing the CSS and add:

```
/* Anonymous poll */
.poll--Z1w6wQt table {
	display: none;
}
```
hides the result...It's still visible via e.g. the browser developer inspector.

**Comment by fingolfin** [comment]
This would be really, really nice to have. Perhaps the "Start a poll" dialog could have a checkbox "Make results anonymous".

**Comment by ha3ant** [comment]
We need that option too

**Comment by MortezaTaghaddomi99** [comment]
> poll--Z1w6wQt

This is a good idea :) 
Where's the CSS file?

**Comment by lebechec** [comment]
A very good idea ! 
it would be a really interesting feature. To allow really anonymous voting of people in sessions. For council elections for example

**Comment by cyfrax** [comment]
In addition to the sometimes existing requirement to be able to vote anonymously, there could be an option for all participants to take part ina a poll, including the presenter / poll starter.
Ideally two options are added to the poll, one for "poll is anonymous" and "presenter can participate".

This would allow for handling of voting in official club business for example holding annual general meetings.
