### ISSUE TITLE
deep link

### ISSUE THREAD

**Issue by freehussain** [bigbluebutton/bigbluebutton#9528]
i already created mobile app for bbb, all i need now is deep link to open my app instead of browser

is there anyway to do it?

**Comment by hackzie** [comment]
Can you help me too . I am also in problem in making mobile app.

My email - vatsalnigam8@gmail.com
Please contact me or give me your email.

**Comment by freehussain** [comment]
hello,

please send me your whatsapp @hackzie

**Comment by hackzie** [comment]
Hi ! Please Ping me here , wa.me/919140014479

**Comment by hackzie** [comment]
Hi ! Please Ping me here , [wa.me/919140014479](https://api.whatsapp.com/send?phone=919140014479&text=&source=&data=&app_absent=)
