### ISSUE TITLE
Rooms style doesn't work correctly 

### ISSUE THREAD

**Issue by Nicolas9877** [bigbluebutton/bigbluebutton#9530]
Hello everybody. 
i have a problem when i want to create a room in bigbluebutton.
when i created a room in http:myipaddress/b i see this:
![BBB](https://user-images.githubusercontent.com/48104662/81850436-35836980-956d-11ea-9bb0-196c470b68f7.png)

does it for https?
it seems room css doesn't work.
here is my bbb-conf --status
nginx —————————————————► [✔ - active]
freeswitch ————————————► [✔ - active]
redis-server ——————————► [✔ - active]
bbb-apps-akka —————————► [✔ - active]
bbb-transcode-akka ————► [✔ - active]
bbb-fsesl-akka ————————► [✔ - active]
red5 ——————————————————► [✔ - active]
tomcat7 ———————————————► [✔ - active]
mongod ————————————————► [✔ - active]
bbb-html5 —————————————► [✔ - active]
bbb-webrtc-sfu ————————► [✔ - active]
kurento-media-server ——► [✔ - active]
etherpad ——————————————► [✔ - active]
bbb-web ———————————————► [✔ - active]

**Comment by frank-miller9** [comment]
And what would be your expected layout? Did you check, that you load the HTML5 client (and do you have the latest version from BBB?)

**Comment by ffdixon** [comment]
We're not supporting the Flash client anymore in the BigBlueButton project.  We've not done any development on Flash for over a year, and we've been focusing purely on the HTML5 client.

The next release of BigBlueButton, which is 2.3, will shed the HTML5 client and much of the back-end components (such as red5) as well.

**Comment by Nicolas9877** [comment]
> 
> 
> And what would be your expected layout? Did you check, that you load the HTML5 client (and do you have the latest version from BBB?)

yeah i am sure about that i install BBB from this link https://docs.bigbluebutton.org/2.2/install.html
i expected something like this , like demo one 
![BBB](https://user-images.githubusercontent.com/48104662/81896631-40b8b280-95ca-11ea-8248-5396e70342ae.png)

**Comment by Nicolas9877** [comment]
> 
> 
> We're not supporting the Flash client anymore in the BigBlueButton project. We've not done any development on Flash for over a year, and we've been focusing purely on the HTML5 client.
> 
> The next release of BigBlueButton, which is 2.3, will shed the HTML5 client and much of the back-end components (such as red5) as well.

So you think it must be for flash client? Could you tell me please what should i do now?

**Comment by Nicolas9877** [comment]
> 
> 
> We're not supporting the Flash client anymore in the BigBlueButton project. We've not done any development on Flash for over a year, and we've been focusing purely on the HTML5 client.
> 
> The next release of BigBlueButton, which is 2.3, will shed the HTML5 client and much of the back-end components (such as red5) as well.

yay that's fix now i try via from this link http://docs.bigbluebutton.org/2.2/customize.html#make-the-html5-client-default and its working correctly now. thanks a lot @ffdixon
