### ISSUE TITLE
Require Moderator Approval not Enforced for Dial-In Users

### ISSUE THREAD

**Issue by ichdasich** [bigbluebutton/bigbluebutton#9531]
**Describe the bug**
When moderator approval is required for joining a room, phone dial-in users still join the audio bridge directly.

**To Reproduce**
1. Create a room requirering moderator approval (via the api or by setting the default), with phone-dialin enabled
2. Dial into the conference
3. Directly participate/listen to audio

**Expected behavior**
Dial-In users are also placed in the moderator queue.

**Actual behavior**
Dial-In users can directly enter the conference.

**Additional context**
Given that conference IDs are relatively enumerable (100k options) this is an issue for (semi) confidential activities like oral examinations.

**Comment by ffdixon** [comment]
Agreed in that we want to have moderators approve dial-in users as well.

**Comment by wolbernd** [comment]
Is there any update on this? We have BBB 2.2.19 installed and the problem still exists. 

As we do have some confidential meetings on our servers this is problematic for us.
