### ISSUE TITLE
Do not auto-remove `events.xml` files for published recordings (GDPR issue) 

### ISSUE THREAD

**Issue by defnull** [bigbluebutton/bigbluebutton#9535]
PR #9483 enabled automatic removal of archived recoding files, even for published recordings. This destroys the `events.xml` file needed by the official bigbluebutton/gdpr tool to answer GDPR requests. Without an `events.xml`, it is no longer possible to tell if a specific user was recorded or not.

**To Reproduce**
1. Upgrade do BBB 2.2.10
2. Wait two weeks and one day
3. Get a GDPR request (e.g. user wants to know if he/she was recorded in any meeting)
4. ...
5. Get sued.

**Expected behavior**
Data that is absolutely necessary to comply with EU laws should not be unnecessarily deleted.

**Actual behavior**
Data that is absolutely necessary to comply with EU laws is automatically deleted by default.

**Comment by basisbit** [comment]
I'd vote against keeping the events.xml by default. Keeping this file makes it much more difficult to have a GDPR compliant setup, requires anonymization and does contain much more person-related data than what devnull tries to archieve.

**Comment by defnull** [comment]
Our plan is to write post_archive and post_publish scripts that extract the required information and immediately remove unneeded raw data. Keeping that meta-data about recordings is covered by GDPR, and I'd argue it is actually required to keep, since it is required to answer user requests regarding their data.

But that PR is not ready yet. In the meantime, it should be clear for users in countries with actual privacy laws that the current BBB default installation removes data required to identify users in recordings, but not the recordings, after 14 days.
