### ISSUE TITLE
allowDuplicateExtUserid issue

### ISSUE THREAD

**Issue by ghes86** [bigbluebutton/bigbluebutton#9540]
**Describe the bug**
If I set to false the property allowDuplicateExtUserid in file /usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties, the related function doesn't work

**To Reproduce**
1. Set to false the property allowDuplicateExtUserid in file /usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties
2. reload bbb
3. start meeting
4. join meeting
5. join meeting with another browser with the same userId of before

**Expected behavior**
The user who entered first should be kicked out of the meeting, like in 2.2.4 version

**Actual behavior**
Since 2.2.10 version, the user who entered first remains inside the meeting, without being able to write in chat

**Comment by pedrobmarin** [comment]
Duplicated https://github.com/bigbluebutton/bigbluebutton/issues/9354
