### ISSUE TITLE
Change Css of the background

### ISSUE THREAD

**Issue by Nicolas9877** [bigbluebutton/bigbluebutton#9541]
Hello Everybody i want to change the CSS of the Background here:
![Screenshot (10)](https://user-images.githubusercontent.com/48104662/81967546-51037880-9630-11ea-8a40-714d1150ead5.png)
To something like this:
![Screenshot (11)](https://user-images.githubusercontent.com/48104662/81967572-5fea2b00-9630-11ea-9457-16de4293aa63.png)
is there anyway to do this? thanks in advance

**Comment by basisbit** [comment]
This issue tracker isonly for BBB development issues. For customization and setup, please closethis issue here and use the forum/mailinglist:
https://groups.google.com/forum/#!forum/bigbluebutton-setup

**Comment by Nicolas9877** [comment]
@ffdixon could you advise me please?

**Comment by iSamof** [comment]
@Nicolas9877 - if we don't follow the community guidelines, we will not have a community left. Perhaps you did not see basisbit's reasonable suggestion!?

**Comment by Nicolas9877** [comment]
> 
> 
> @Nicolas9877 - if we don't follow the community guidelines, we will not have a community left. Perhaps you did not see basisbit's reasonable suggestion!?

sure i checked it and found something :
http://docs.bigbluebutton.org/dev/20branding.html
but the page didn't found.

**Comment by iSamof** [comment]
That's great that you tried somewhere else. So how about discussing your requirement at the Google Groups as basisbit suggested.

**Comment by Nicolas9877** [comment]
> 
> 
> That's great that you tried somewhere else. So how about discussing your requirement at the Google Groups as basisbit suggested.

thanks iSamof i'll try it there too, and thanks a lot for your reply and basisbit reply🙏

**Comment by iSamof** [comment]
You are most welcome Ali. Also please search for the "layout editor" which is being worked on. I think it may help CSS settings. 

If you are done with this thread, please kindly close, to reduce the load on the dev team.

**Comment by GhaziTriki** [comment]
@basisbit Thank you for pointing to the forums.

**Comment by d471d** [comment]
Hello 
How can I change the font?
Is there a CSS file to change?
I tried different ways but it didn't work

please guide me

**Comment by matiasilva** [comment]
@d471d if you found this thread, surely you must have read the very helpful suggested at the top ;)

**Comment by d471d** [comment]
> 
> 
> @d471d if you found this thread, surely you must have read the very helpful suggested at the top ;)

I tried, But none of them were practical... And it doesn't change the interface!

**Comment by matiasilva** [comment]
@d471d What exactly did you check? Did you read basisbit's suggestion to look in the forums? There are many many people who have asked the same question before. In addition to that, you can use your favorite search engine and ask it the question as the groups, the documentation, and this issue tracker are all indexed. And lastly, we have the documentation which should be enough for your needs: https://docs.bigbluebutton.org/2.2/customize.html
