### ISSUE TITLE
Empty $IP in bbb-client.postinst

### ISSUE THREAD

**Issue by SeniorTigr** [bigbluebutton/bigbluebutton#9544]
Variable IP in the postinstall script of bbb-client package is empty. This causes the /etc/nginx/sites-available/bigbluebutton file have server_name directive without the argument, which causes error on nginx restart during the bbb-html5 postint script.

Problem occurs because of the definition of the IP variable during the bbb-client script.
`IP=$(cat /tmp/nginx-bigbluebutton | grep -v '#' | head -n 1 | sed -n '/server_name/{s/.*name[ ]*//;s/;//;p}')`
The order of sed and head is reversed, so the sed is run on the fisrt line of the /tmp/nginx-bigbluebutton file which does not have of course any server_name directive. If the order is reversed, it correctly sets the IP variable to the server name.
BTW in the bbb-client.postinst exists another definition of the IP variable in another part of the code:
`IP=$(cat /tmp/nginx-bigbluebutton | grep -v '#' | sed -n '/server_name/{s/.*name[ ]*//;s/;//;p}')`
It also should be fixed by adding the `head -n 1` at the end of the called expression, as it faults if somebody will use a nginx configuration with more than one server_name directive (for example adding the autoredirect from http to https) and in such case the IP variable will contain `\n` characters which will cause problems down the script.

Problem occured when upgrading by apt to BBB 2.2.10 from 2.2.9

**Comment by ffdixon** [comment]
Thanks for catching this error -- we're going to try and get a update 2.2.11 out soon to fix this.

For anyone installing via [bbb-install.sh](https://github.com/bigbluebutton/bbb-install), they won't hit this as

**Comment by SeniorTigr** [comment]
Yes, it was not hard to correct the problem manually but I was trying to make an upgrade by a script (which by the way had the `sudo bbb-conf --setip <hostname>` just after the part of upgrading) but it ended prematurely when apt reported the error.

Thank you for the quick reaction and keep up the good work!

**Comment by antobinary** [comment]
Starting with BBB 2.3, there is no bbb-client package (former Flash client)
