### ISSUE TITLE
WebCam Error Code 1020, STUN connect to Private IP Address (BBB behind firewall)

### ISSUE THREAD

**Issue by congyijun** [bigbluebutton/bigbluebutton#9545]
**Describe the bug**
I refer to bigbluebutton official guideline and setup bbb server step by step. Now already finish the two steps, "Installation" and "Configure Firewall". But just found one issue couldn't be resolved. The client (firefox, chrome or Safari) could join the audio conference call successful. And then I try to enable or share the camera. After 10 seconds, the browser prompt "couldn't connect to media server error code: 1020". I also try it on   firefox, chrome or Safari, and get same reminder error code 1020.

Next, i try to capture the network packet on windows PC. I can see the PC connect to public IP address for audio join conference call.    But but the PC connect to my bbb server private IP address when i click share webcamera. 

that's what is my confuse, why the PC browser (firefox) connect to bbb private IP address suddenly.

I am not sure which step setting missing. 

By the way,  my bbb server behind firewall. And i already setup rules allow all incoming traffic.

**To Reproduce**
1. PC firefox or iOS Safari join conference by audo
2. Check audio conference call working fine
3. Click the share Camera, allow browser connect to devices camera
4. Finally, the browser reminder Error Code: 1020 - couldn't connect to media server

**Expected behavior**
Share webcam and join video conference call successful

**Actual behavior**
Share webcam and join video conference call successful

**Screenshots**
![07](https://user-images.githubusercontent.com/62802149/82015787-29ed8b00-96b2-11ea-8125-8f8b64616e5d.PNG)

**BBB version (optional):**

BigBlueButton Server 2.2.10 (1921)

**Desktop (please complete the following information):**
 - Windows, Apple iOS
 - Firefox, Safari
 - Firefox 68.7

**Smartphone (please complete the following information):**
 - iPhone 8
 - iOS13.4.1
 - Safari
 - Version Unknow

**Comment by znerol** [comment]
Webcams are handled by Kurento. Make sure to configure a working STUN server for kurento as explained in the [Firewall Docs](http://docs.bigbluebutton.org/2.2/configure-firewall.html#extra-steps-when-server-is-behind-nat). If Kurento is not able to determine the external address, then it will just fall back to the internal one.

**Comment by congyijun** [comment]
@znerol 

I already refer to guideline change something for **WebRtcEndpoint.conf.ini**

Could you help me verify it? Which one missing or incorrect. Thanks!


;; External (public) IP address of the media server.
;;
;; If you know what will be the external or public IP address of the media server
;; (e.g. because your deployment has an static IP), you can specify it here.
;; Doing so has the advantage of not needing to configure STUN/TURN for the media
;; server.
;;
;; STUN/TURN are needed only when the media server sits behind a NAT and needs to
;; find out its own external IP address. However, if you set a static external IP
;; address with this parameter, then there is no need for the STUN/TURN
;; auto-discovery.
;;
;; The effect of this parameter is that ALL local ICE candidates that are
;; gathered (for WebRTC) will contain the provided external IP address instead of
;; the local one.
;;
;; <externalAddress> is an IPv4 or IPv6 address.
;;
;; Examples:
;; externalAddress=10.20.30.40
;; externalAddress=2001:0db8:85a3:0000:0000:8a2e:0370:7334
;;
;externalAddress=10.20.30.40

;; Local network interfaces used for ICE gathering.
;;
;; If you know which network interfaces should be used to perform ICE (for
;; WebRTC connectivity), you can define them here. Doing so has several
;; advantages:
;;
;; * The WebRTC ICE gathering process will be much quicker. Normally, it needs
;;   to gather local candidates for all of the network interfaces, but this step
;;   can be made faster if you limit it to only the interface that you know will
;;   work.
;;
;; * It will ensure that the media server always decides to use the correct
;;   network interface. With WebRTC ICE gathering it's possible that, under some
;;   circumstances (in systems with virtual network interfaces such as
;;   "docker0") the ICE process ends up choosing the wrong local IP.
;;
;; <networkInterfaces> is a comma-separated list of network interface names.
;;
;; Examples:
;; networkInterfaces=eth0
;; networkInterfaces=eth0,enp0s25
;;
;networkInterfaces=eth0

;; STUN server IP address.
;;
;; The ICE process uses STUN to punch holes through NAT firewalls.
;;
;; <stunServerAddress> MUST be an IP address; domain names are NOT supported.
;;
;; You need to use a well-working STUN server. Use this to check if it works:
;; https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/
;;
;; From that check, you should get at least one Server-Reflexive Candidate
;; (type "srflx").
;;
;stunServerAddress=208.97.25.20
;stunServerPort=3478

;; TURN server URL.
;;
;; When STUN is not enough to open connections through some NAT firewalls,
;; using TURN is the remaining alternative.
;;
;; Note that TURN is a superset of STUN, so you don't need to configure STUN
;; if you are using TURN.
;;
;; The provided URL should follow one of these formats:
;;
;;   * user:password@ipaddress:port
;;   * user:password@ipaddress:port?transport=[udp|tcp|tls]
;;
;; <ipaddress> MUST be an IP address; domain names are NOT supported.
;; <transport> is OPTIONAL. Possible values: udp, tcp, tls. Default: udp.
;;
;; You need to use a well-working TURN server. Use this to check if it works:
;; https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/
;;
;; From that check, you should get at least one Server-Reflexive Candidate
;; (type "srflx") AND one Relay Candidate (type "relay").
;;
;turnURL=user:password@127.0.0.1:3478?transport=udp

;pemCertificate is deprecated. Please use pemCertificateRSA instead
;pemCertificate=<path>
;pemCertificateRSA=<path>
;pemCertificateECDSA=<path>

**Comment by znerol** [comment]
The semicolon denotes a comment. Every line starting with a semicolon is ignored.

That said, remove the semicolon before `stunServerAddress` and `stunServerPort`.

**Comment by congyijun** [comment]
> 
> 
> The semicolon denotes a comment. Every line starting with a semicolon is ignored.
> 
> That said, remove the semicolon before `stunServerAddress` and `stunServerPort`.
> 
> **Edit**: After that restart kurento `systemctl restart kurento-media-server`


Hello Znerol

Many thanks for your replay. 

Finally, I found enable  **externalAddress=<public IP address>** could resolve this is issue. Because my BBB sever behind firewall.
