### ISSUE TITLE
Presentation text displayed twice if math formula is present (pptx)

### ISSUE THREAD

**Issue by timm2k** [bigbluebutton/bigbluebutton#9550]
Hi there,

If I upload a pptx with math formulas, text of pages with math formulas is displayed twice with a little shift.

**To Reproduce**
1. Start a meeting
2. upload presentation from https://cloud.uol.de/s/Pa6NaEX4y2wpbYW/download
3. have a look at the presentation

**Expected behavior**
Text should be displayed once 

**Actual behavior**
Text is displayed twich after converting pptx with math formula
Screenshot: https://cloud.uol.de/s/MREg7H2LqTcNF67

**Workaround**
Export presentation as PDF with PowerPoint

Created with 
 - OS: Office 2019
 - BBB 2.2.10

I hope you are able to fix this with my provided informations.

Kind regards
Timm

**Comment by basisbit** [comment]
Provided powerpoint file attached for documentation: [defect.pptx]
And the provided screenshot:
(https://github.com/bigbluebutton/bigbluebutton/files/4635302/defect.pptx)
![1024-786](https://user-images.githubusercontent.com/10870269/82067786-75fbf800-96d1-11ea-89a8-c6c51dae5a5d.png)

As a workaround, you can export the file from LibreOffice/PowerPoint to PDF and then upload that file in BigBlueButton.
