### ISSUE TITLE
Packaging version mismatch

### ISSUE THREAD

**Issue by lkiesow** [bigbluebutton/bigbluebutton#9555]
Installing BigBlueButton from the project's package repository for Ubuntu will gibe you a non-existing version:

```
% cat /etc/bigbluebutton/bigbluebutton-release
BIGBLUEBUTTON_RELEASE=2.2.11
```

…which is weird since [the latest release here is 2.2.10](https://github.com/bigbluebutton/bigbluebutton/releases).
Obviously, there is something wrong with the packaging.
How can you package a non-existing version.

**Comment by ffdixon** [comment]
We just released 2.2.10 (and tagged it), and then after bumped the version to 2.2.11 which is currently under development.

We did this in part as we published the dev packages for 2.2.11 for anyone to install at 

https://ubuntu.bigbluebutton.org/xenial-22-dev

We did this to help others test the websocket fix in FreeSWITCH that is pending in 2.2.11, see

  https://groups.google.com/d/msg/bigbluebutton-dev/u7C3o0q3IJo/ufCoCHEpAQAJ

**Comment by lkiesow** [comment]
Hi @ffdixon, I'm not speaking about the testing/dev repository. Maybe it was accidental, but you seemingly pushed this into the production repository as well. Hence, if you have the repository recommended for production [1] enabled, you get an experimental version. That clearly shouldn't happen, should it?

I noticed this when updating one of the test clusters I help to maintain but it could have easily happened on production as well.

[1] https://ubuntu.bigbluebutton.org/xenial-220/

**Comment by ffdixon** [comment]
Hi Lars, it was accidental.  We've released BigBlueButton 2.2.11 so the repository for `xenial-220` and release are now in sync.

**Comment by lkiesow** [comment]
Thanks. Than. let's close this.

**Comment by aogilvie** [comment]
@ffdixon Sorry for thread hiijack, but seemed relevant.

What is the package name for packages post RCs?
I have xenial-220-rc6 and im looking for 2.2.15. Thanks.

**Comment by ffdixon** [comment]
Here you go

~~~
ii  bbb-apps                   1:2.2.0-44   amd64   BigBlueButton applications for Red5
ii  bbb-apps-akka              2.2.0-86     all     BigBlueButton Apps (Akka)
ii  bbb-apps-screenshare       1:2.2.0-44   amd64   BigBlueButton screenshare module for Red5
ii  bbb-apps-sip               1:2.2.0-11   amd64   BigBlueButton SIP module for Red5
ii  bbb-apps-video             1:2.2.0-41   amd64   BigBlueButton video module for Red5
ii  bbb-apps-video-broadcast   1:2.2.0-8    amd64   BigBlueButton video broadcast module for Red5
ii  bbb-check                  1:2.2.0-5    amd64   Client check package for BigBlueButton
ii  bbb-client                 1:2.2.0-40   amd64   BigBlueButton Flash client
ii  bbb-config                 1:2.2.0-188  amd64   BigBlueButton configuration utilities
ii  bbb-demo                   1:2.2.0-9    amd64   BigBlueButton API demos
ii  bbb-etherpad               1:2.2.0-50   amd64   The EtherPad Lite components for BigBlueButton
ii  bbb-freeswitch-core        2:2.2.0-112  amd64   BigBlueButton build of FreeSWITCH
ii  bbb-freeswitch-sounds      1:1.6.7-9    amd64   FreeSWITCH Sounds
ii  bbb-fsesl-akka             2.2.0-64     all     BigBlueButton FS-ESL (Akka)
ii  bbb-html5                  1:2.2.0-933  amd64   The HTML5 components for BigBlueButton
ii  bbb-mkclean                1:0.8.7-4    amd64   Clean and optimize Matroska and WebM files
ii  bbb-playback-presentation  1:2.2.0-30   amd64   BigBluebutton playback of presentation
ii  bbb-record-core            1:2.2.0-66   amd64   BigBlueButton record and playback
ii  bbb-red5                   1:1.0.10-16  amd64   The Red5 server for BigBlueButton
ii  bbb-transcode-akka         2.2.0-11     all     BigBlueButton Transcoder
ii  bbb-web                    1:2.2.0-128  amd64   BigBlueButton API
ii  bbb-webrtc-sfu             1:2.2.0-99   amd64   BigBlueButton WebRTC SFU
~~~

**Comment by aogilvie** [comment]
So sorry, I mean repository name not packages! 🙏

**Comment by aogilvie** [comment]
@ffdixon 
xenial-2215 ?

**Comment by ffdixon** [comment]
`xenial-220-2.2.15`

**Comment by aogilvie** [comment]
@ffdixon FYI, could not find any packages on xenial-220-2.2.17 
Assuming no updates packages at the moment.
