### ISSUE TITLE
Microphone in Safari stops working after video sharing stops

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#9556]
**Describe the bug**
When on Safari and connected with microphone, after the instructor plays and stops a video (such as YouTube), Safari does not pick up the microphone.

**To Reproduce**
1. Join a session with an iPhone with microphone
2. Confirm that the microphone is working
3. Share a YouTube video from another user
4. No more audio hear from the user on the iPhone.

**Smartphone (please complete the following information):**
 - Device: iPhone 8s
 - iOS 13.4.1

**Additional context**
What's interesting is that if you manually leave the audio and rejoin with the microphone, the microphone works again.  It might be possible to do this automatically to get the audio back.

**Comment by pedrobmarin** [comment]
@mariogasparoni found another one that you might have an opinion on it

**Comment by mariogasparoni** [comment]
I am not able to reproduce this on iPad Mini (iOS 12), iPhone 8 (iOS 13) , neither iPhone 12 (iOS 14).
This can be closed, due to no evidences this is happening in recent versions (2.2.36, neither 2.3beta-2)
