### ISSUE TITLE
Yandex Browser in Meteor

### ISSUE THREAD

**Issue by squid46** [bigbluebutton/bigbluebutton#9557]
Good day.
Please add to "Meteor" in "settings.yml"

  - browser: yandexbrowser
    version: 18

https://en.wikipedia.org/wiki/Yandex_Browser
Thank you.

**Comment by GremL1N** [comment]
already here
https://github.com/bigbluebutton/bigbluebutton/blob/231c962029f318a67239ea9c091410292e8dd7ed/bigbluebutton-html5/private/config/settings.yml#L375-L376

**Comment by basisbit** [comment]
@squid46 this was already added in the develop branch and will be part of the version 2.3 once it is released.
