### ISSUE TITLE
Make /etc/cron.daily/bigbluebutton configurable using another source/file

### ISSUE THREAD

**Issue by gilou** [bigbluebutton/bigbluebutton#9558]
**Is your feature request related to a problem? Please describe.**
Whenever there is an upgrade, dpkg will complain if /etc/cron.daily/bigbluebutton has changed, and it's always annoying to have to go through the diff to make sure nothing is going to break.

**Describe the solution you'd like**
Let's have a configuration file sourced from the script, either in /etc/default/bigbluebutton or somewhere in /etc/bigbluebutton. The former seems more appropriate, but I have no idea what the policy is.

**Comment by basisbit** [comment]
"dpkg will complain if /etc/cron.daily/bigbluebutton has changed"
As far as I know, this is absolutely desired behaviour for any debian/apt based system and actually should be the case for any such configuration file when it gets changed by the package maintainer.

**Comment by gilou** [comment]
Indeed it is. And that's a good reason to have configurable setup done outside of it, so we don't get nagged if it's an actual update of the script/code rather than default variable changing (or adding new ones). In that case, if default file is not there, it doesn't matter, and it does not need to be shipped in the package. If we want to ship one, then a good way is to source yet another file for site configuration (whether a conf.d or a .local, I'm not sure there really is a norm there)
