### ISSUE TITLE
Not connecting to echo server 

### ISSUE THREAD

**Issue by soheilrahsaz** [bigbluebutton/bigbluebutton#9560]
I have an error connecting to a meeting
it doesn't connect to echo server after updating to 2.2.10

after joining the session, it tries to connect to the echo server but it fails and shows 1005 error and therefore I cant have microphone.
it happens in all browsers and devices.
I also have 3 BBB servers in different vpses and it happens everywhere

**Comment by Ahmet-Kaplan** [comment]
Can you try [that](https://groups.google.com/d/msg/bigbluebutton-dev/o1ZIj3JXdiY/rjqB-MCyAQAJ) solution ?

**Comment by ffdixon** [comment]
Did you do follow the steps here
  
  http://docs.bigbluebutton.org/2.2/install.html#upgrading-from-bigbluebutton-22

and check the output of `sudo bbb-conf --check`, especially regarding the settings of `/etc/bigbluebutton/nginx/sip.nginx`.

**Comment by soheilrahsaz** [comment]
> Can you try [that](https://groups.google.com/d/msg/bigbluebutton-dev/o1ZIj3JXdiY/rjqB-MCyAQAJ) solution ?

Now the error changed to 1010 time out.

> Did you do follow the steps here
> 
> http://docs.bigbluebutton.org/2.2/install.html#upgrading-from-bigbluebutton-22
> 
> and check the output of `sudo bbb-conf --check`, especially regarding the settings of `/etc/bigbluebutton/nginx/sip.nginx`.

And yes I did follow the steps in the given link.
I've been using BBB for 3 months now and I didn't have any problems with updating until now.
I had to downgrade some of my servers to work again and it did.
The problem only exists in the new update.

**Comment by ffdixon** [comment]
If you have a server that is working and one that is not, you should be able to narrow down the configuration difference.

Can you do a compare of the configuration files in /opt/freeswitch/etc/freeswitch between the two servers.

Also, check the output of `sudo bbb-conf --check` on both servers -- do you see any difference in the FreeSWITCH configuration?

And check the contents of `sip.nginx`.

**Comment by soheilrahsaz** [comment]
This problem was fixed in new versions
