### ISSUE TITLE
MongoDB Default Path

### ISSUE THREAD

**Issue by NiceboyWiseboy** [bigbluebutton/bigbluebutton#9562]
Hello,

Need to know the MongoDB default install path and URL and port.
Tried to find but couldn't found any way.

Thank you,
Best Regards

**Comment by basisbit** [comment]
This issue tracker here is only for development of the BigBlueButton software itself. Please do not post support questions here. Instead, please ask at https://groups.google.com/forum/#!forum/bigbluebutton-setup

**Comment by NiceboyWiseboy** [comment]
ok thanks for the info.
