### ISSUE TITLE
Pending recordings on  bigbluebutton 

### ISSUE THREAD

**Issue by Bhargesh11** [bigbluebutton/bigbluebutton#9563]
We have a lot of recording every hour and our server. This recordings takes take a long time to get published is there any way to make it faster ?
And how can we get the list of pending recordings which are yet to be published?

**Comment by iSamof** [comment]
There are many threads already about recording and rendering performance. Some may help you. 

Here is an example: [#8770](https://github.com/bigbluebutton/bigbluebutton/issues/8770)

**Comment by Bhargesh11** [comment]
The thread #8770 answers my 1st question but how can we get the list of pending recordings which are yet to be published?

**Comment by iSamof** [comment]
I don't remember where but I think I have seen this in other threads. Pls search the Issues.

**Comment by jibon57** [comment]
`bbb-record --list`
If you see `X` mark under `RAS` column then that is under process. http://docs.bigbluebutton.org/dev/recording.html#troubleshooting

**Comment by jesusvaldivia** [comment]
> We have a lot of recording every hour and our server. This recordings takes take a long time to get published is there any way to make it faster ?
> And how can we get the list of pending recordings which are yet to be published?

you can check my answer in this thread #9613

**Comment by basisbit** [comment]
Thank you all for helping answer the support questions!

**Comment by AnthonyVidal** [comment]
> To get support, please ask at the [mailing list / forum](https://groups.google.com/forum/#!forum/bigbluebutton-setup). This issue tracker here is for BigBlueButton development issues only.

Okay. I already requested access to the group. Thanks

**Comment by Mrhalix** [comment]
Did you solve it ?

**Comment by Mrhalix** [comment]
Could you solve it? I have the same problem where there is just one single X under RAS and no archived files available!

**Comment by matiasilva** [comment]
> To get support, please ask at the [mailing list / forum](https://groups.google.com/forum/#!forum/bigbluebutton-setup). This issue tracker here is for BigBlueButton development issues only.

See the response only two comments above yours.
