### ISSUE TITLE
Upload and play audio files/I want to know how to upload and play audio files on BBB

### ISSUE THREAD

**Issue by Mary260** [bigbluebutton/bigbluebutton#9566]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Actual behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, Mac]
 - Browser [e.g. Chrome, Safari]

**Smartphone (please complete the following information):**
 - Browser [e.g. stock browser, Safari]

**Additional context**

**Comment by Mary260** [comment]
Hello, there

I need to upload and play audios on BBB, but I cannot.

Any advice?

-M

**Comment by basisbit** [comment]
This issue tracker here is only for development of the BigBlueButton software itself. Please do not post support questions here. Instead, please ask at https://groups.google.com/forum/#!forum/bigbluebutton-setup

**Comment by basisbit** [comment]
hosting / playing audio files is currently not supported in BigBlueButton.
The usual workflow for sharing / playing media files is to upload them to a video streaming server and the use the "play/share video" integration using the URL to the playable Media website
