### ISSUE TITLE
Different font size of titles Public Chat and Shared Notes

### ISSUE THREAD

**Issue by ostasevych** [bigbluebutton/bigbluebutton#9569]
I found that there's different font size in titles of Public Chat and Shared Notes. Please, make it the same.

![image](https://user-images.githubusercontent.com/5199030/82127724-7a520f00-97be-11ea-8a19-0c0d4dc0d6a3.png)

**Comment by IBROF** [comment]
Hi,

What is the point of changing the font? Sorry for my question but I do not see it worth to change. May I understand your point of view?
