### ISSUE TITLE
After update ngnix error

### ISSUE THREAD

**Issue by kaffeeweisser2020** [bigbluebutton/bigbluebutton#9571]
Hi 
My bbb server was running well, but  while updating via "apt update && apt upgrade", I've got this 
message:

Reloading nginx.service using systemd
Adding nginx.service to autostart using systemd
Synchronizing state of nginx.service with SysV init with /lib/systemd/systemd-sy                                                                                                             sv-install...
Executing /lib/systemd/systemd-sysv-install enable nginx
Job for nginx.service failed because the control process exited with error code.                                                                                                              See "systemctl status nginx.service" and "journalctl -xe" for details.
dpkg: error processing package bbb-record-core (--configure):
 subprocess installed post-installation script returned error exit status 1
dpkg: dependency problems prevent configuration of bbb-playback-presentation:
 bbb-playback-presentation depends on bbb-record-core; however:
  Package bbb-record-core is not configured yet.

dpkg: error processing package bbb-playback-presentation (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of bbb-config:
 bbb-config depends on bbb-playback-presentation; however:
  Package bbb-playback-presentation is not configured yet.

dpkg: error processing package bbb-config (--configure):
 dependency problems - leaving unconfigured
Setting up bbb-html5 (1:2.2.0-910) ...
Job for nginx.service failed because the control process exited with error code.                                                                                                              See "systemctl status nginx.service" and "journalctl -xe" for details.
dpkg: error processing package bbb-html5 (--configure):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 bbb-record-core
 bbb-playback-presentation
 bbb-config
 bbb-html5
E: Sub-process /usr/bin/dpkg returned an error code (1)

How can I resolve this?

Thanks for your help.

CU

U

**Comment by PierreHentges** [comment]
Were you able to resolve this? I have the same issue.

**Comment by ffdixon** [comment]
You need to also run `bbb-conf --setip <hostname>` as part of the upgrade

  http://docs.bigbluebutton.org/2.2/install.html#upgrading-from-bigbluebutton-22

**Comment by PierreHentges** [comment]
many thanks, that worked!
