### ISSUE TITLE
Poll Option Overlapping and Not Showing in full screen

### ISSUE THREAD

**Issue by gitisara** [bigbluebutton/bigbluebutton#9573]
Describe the bug**
i) Poll option covers the Screen and Hides the presentation area.
ii) Poll options not showing when on fullscreen.

**To Reproduce**
i) POLL OPTION NOT SHOWING UP IN FULL SCREEN
1. Join Meeting
2. Start a Poll from Presenter's side
3. Switch to Full screen Presentation Area from Client Side
4. See error : POLL OPTION NOT Showing up

ii) i) POLL OPTION NOT SHOWING UP IN FULL SCREEN
1. Join Meeting
2. Start a Poll from Presenter's side
3. View from Client Side
4. ERROR : Poll option covers full area , hiding presentation screen behind

**Expected behavior**
i ) Poll option should show on FULL SCREEN
ii) Poll Option should not cover the Presentation Area

**BBB version (optional):**
BigBlueButton continually evolves. Providing the version/build helps us to pinpoint when an issue was introduced.
Example:
$ sudo bbb-conf --check | grep BigBlueButton
BigBlueButton Server 2.2.2 (1816)

**Smartphone (please complete the following information):**
 - Device: Android & iPhone
 - Browser : Chrome & iOS

**Comment by antobinary** [comment]
Fixed by https://github.com/bigbluebutton/bigbluebutton/pull/11408
