### ISSUE TITLE
Picture In Picture Mode on Mobile Device FULL SCREEN.

### ISSUE THREAD

**Issue by gitisara** [bigbluebutton/bigbluebutton#9574]
**Is your feature request related to a problem? Please describe.**
Its difficult to view on Moble , both the presentation area and Camera of Teacher

**Describe the solution you'd like**
Picture in Picture mode in presentation area , will make it fantastically fit for Student's experience on Mobile devices in full screen..

**Comment by samtech09** [comment]
Yes, it will improve the usabillity. Right now if we make presentation full screen then it hides all vides. Presenter's video should be in PiP.

**Comment by jingwenw** [comment]
I second this feature request - it would be very useful! Camera video is a the key element for any video conference system - it should be always visible once enabled, especially for the presenter.
