### ISSUE TITLE
Remove weird 2.2.11 tags/releases

### ISSUE THREAD

**Issue by lkiesow** [bigbluebutton/bigbluebutton#9575]
There are a number of different, totally confusing 2.2.11 releases:

![Screenshot from 2020-05-17 12-37-37](https://user-images.githubusercontent.com/1008395/82143644-a06ec200-9845-11ea-92be-87e7184b84fb.png)

- Wouldn't it make sense to remove those releases and tags which are broken? E.g. having a release called “ignore” is somewhat weird.
- Does this affect the packages in any way? E.g. is the 2.2.11 package good? Was there a beoken version at some point?

**Comment by ffdixon** [comment]
I had mistakenly tagged 2.2.11 against `develop` (not `v2.2.x-release`).  We just removed all the ignore tags, and we're left with `2.2.11-good` as the tag for 2.2.11. 

We'll get back to normal order for 2.2.12.

**Comment by lkiesow** [comment]
Great, thanks.
Did the packaging stay the same or are there any versions to check for, to make sure they are not installed?

**Comment by ffdixon** [comment]
BigBlueButton 2.2.11 (tagged 2.2.11-good) was a proper release that was pushed to the public repositories.  

For the release of 2.2.11, you should see the following two versions

~~~
bbb-freeswitch-core                   2:2.2.0-109
bbb-html5                             1:2.2.0-910
~~~
