### ISSUE TITLE
Client HTML5 Enhancement Recommend

### ISSUE THREAD

**Issue by mosyBG** [bigbluebutton/bigbluebutton#9577]
Hello
We've been using BigBlueButton for almost a few months now.
The software mentioned was very powerful and we are really happy that we were able to use this program for virtual learning.
In fact, we are an e-commerce development company with a collection of user experience and customer experience professionals and app develo
![Design Enhancements_edit](https://user-images.githubusercontent.com/29355307/82149020-1174a080-986b-11ea-9b01-3834dbf9b2b3.jpg)
pers.
An offer in the form of a plan that will have a simpler user experience than the current plan and we will share it with you for the progress of this great project.
Please check this simple homepage and share your thoughts with us and we can give you better suggestions if you wish.

Thanks

**Comment by mosyBG** [comment]
Hello @ffdixon 
web want to know your comment about our idea. please check it and support us to send our UX/UI team idea for BBB.
thanks alot.

**Comment by basisbit** [comment]
I'd suggest you to write a summary of what you'd like to change how and for what reason. That would make it much easier for others to join the discussion and actually get some progress done.
It is not really clear what you want to change from just the provided screenshot.
