### ISSUE TITLE
Change number of digits for dial-in leads to non-working dial-in

### ISSUE THREAD

**Issue by Sea444** [bigbluebutton/bigbluebutton#9581]
**Describe the bug**
In bigbluebutton.properties you can adjust the default number of digits for dial-in pin. Changing the number leads to non-working dial-in.

**To Reproduce**
1. Change `defaultNumDigitsForTelVoice=` in bigbluebutton.properties from 5 to 6
2. Restart `bbb-conf --restart`
3. Start a conference and join with microphone
4. Call the shown dial-in number
5. Enter the shown conference pin

**Expected behavior**
You get connected to the conference.

**Actual behavior**
After entering 5th digit FREESWITCHS hangs up.

**Smartphone (please complete the following information):**
 - Version: 2.2.5

**Additional context**
Obviously when changing `defaultNumDigitsForTelVoice=` in bigbluebutton.properties, you have to change another setting in FREESWITCH. But where?
-> In bigbluebutton.properties a note should be added that a setting must be adjusted accordingly at another point and where this setting is.

**Comment by ichdasich** [comment]
Heho,
Freeswitch limits the number of digits (min 5 max 5) in this line:
<action application="play_and_get_digits" data="5 5 3 7000 # conference/bbb-surfcloud.wav ivr/ivr-that_was_an_invalid_entry.wav pin \d+"/>
