### ISSUE TITLE
Microphone button shows active state, but the user is muted automatically during join

### ISSUE THREAD

**Issue by tmatthaeus** [bigbluebutton/bigbluebutton#9582]
**Describe the bug**
The room is created with "Mute users when they join". I disabled the listenOnlyMode and I skip the audiocheck:

/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml

```
    autoJoin: true
    listenOnlyMode: false
    forceListenOnly: false
    skipCheck: true
```
When the participant join the user will be muted. In the participant list the user is shown as muted. But the microphone button looks like he is not muted.
The first click on the microphone button unmute the user, the second one mute the user. And then the button looks like I would suggest: white and stroked.

The screenshots shows the user list and the button directly after joining the conference.

**To Reproduce**
1. Disable Listen Only Modus and disable the echo test
2. Create a room where the conference members join muted
3. Join the conference as participant
4. You are muted but the microphone button in the presentation window looks like you are not muted

**Expected behavior**
Microphone should show the muted state

**Actual behavior**
Microphone button shows the activated state

**Screenshots**

**BBB version (optional):**
BigBlueButton Server 2.2.10 (1916)

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser Chrome
 - Version 81.0.4044.138

But I think other browser and OS are affected.

<img width="1437" alt="82042952-0ecb4d00-96ab-11ea-81fd-75916a32c737" src="https://user-images.githubusercontent.com/1618310/82157551-6f60b280-9882-11ea-94a9-35090eb152d4.png">

**Comment by sripathroy** [comment]
@tmatthaeus We are facing the similar issue. Its working fine when meetings are created through API and we tried through Moodle plugin as well. But meetings created through Greenlight, the problem seems to persist.When i try to rejoin the same meeting its working well again.
