### ISSUE TITLE
Recoding not being published

### ISSUE THREAD

**Issue by ShiftyMLG** [bigbluebutton/bigbluebutton#9589]
**Describe the bug**
A while ago I had a meeting recorded (about 2 hours long). I can't seem to find the recording. In the bbb-record --list I can see the recording, but I can't seem to get it published.

The archive .log file ends with this:
![image](https://user-images.githubusercontent.com/36298934/82225490-902e1400-9925-11ea-89f2-a3cba76450cb.png)
 Any idea on how to publish these recordings so users can see it in the greenlight dashboard?

**Comment by basisbit** [comment]
This issue tracker here is not for support requests. This was also part of the issue template which you deleted.
To get support, please ask at https://groups.google.com/forum/#!forum/bigbluebutton-setup
