### ISSUE TITLE
i installed BBB on my VPS, is this possible to install ISPCONFIG also.

### ISSUE THREAD

**Issue by atrex123** [bigbluebutton/bigbluebutton#9590]
I installed bbb on my VPS server, now i need to install a WordPress to manage my BBB. how can i do this.

how can i install bbb and a host management server to install WordPress

**Comment by basisbit** [comment]
This issue tracker here is not for support requests. This was also part of the issue template whcih you deleted.
To get support, please ask at https://groups.google.com/forum/#!forum/bigbluebutton-setup

Also, running BigBlueButton on a VPS is usually not supported. VPS usually do not provide the dedicated CPU cores which you will need for a usable videoconferening system. See https://docs.bigbluebutton.org/2.2/install.html#minimum-server-requirements
Please close this issue to reduce work load on repository maintainers.
