### ISSUE TITLE
Reuse breakout rooms

### ISSUE THREAD

**Issue by Beiri22** [bigbluebutton/bigbluebutton#9591]
I'd like to reuse breakout rooms.
Part 1 in small groups.
Part 2 all in plenum.
Part 3 in same small groups as Part 1 --> Move them by hand. It would be nice to just reopen the rooms of Part 1.

btw. is there a way to change the breakout-time-limit while running?

**Comment by rasos** [comment]
We would like to have a setting, where members of breakout rooms stay either the same (to continue a breakout room session after an intermediate reporting session for all) or are always different. 

Use case for mixing up: Let 50 people talk 1-1 in in 25 breakout rooms. In a second round, make sure, that they meet somebody else.

**Comment by matiasilva** [comment]
@rasos, please use another issue to add your feature request as it's unrelated to this one

@Beiri22 no, you can't extend the time limit of the breakout room. As for "reopening the rooms", I think you probably want to just save a certain user configuration as the concept of a permanent room doesn't exist. How do you propose this work for users that leave halfway through the meeting?

**Comment by Beiri22** [comment]
Just having an outside-perspective, I think that would not be a big problem. If you save a map of User->Room on the first assignment, you can provide a button "As last time" that just preassigns all remaining users according to that mapping. Missing users could be ignored, new users have to be assigned manually as usual.

**Comment by antobinary** [comment]
Implemented in BBB 2.5 https://github.com/bigbluebutton/bigbluebutton/pull/13678
