### ISSUE TITLE
Set default log-level of all core applications to WARN (or better: ERROR) in releases

### ISSUE THREAD

**Issue by ichdasich** [bigbluebutton/bigbluebutton#9596]
At the moment, most components of BBB in the official release ship either with the loglevel set to "DEBUG" or "INFO".

Privacy considerations aside (which have been extensively discussed):

- This consumes a lot of storage on systems which---in most cases---is simply not necessary. If it becomes necessary, an operator can change the log level up
- Shipping DEBUG as a default loglevel to prod is simply bad practice
- Most relevant access statistics are already collected by the nginx proxy in front of the system
- A system upgrade most likely overwrites many of the files used to configure the log level. Taking precautions to fix that is a mess in itself (e.g., when the corresponding files are changed by the update a copy is not enough, str replace comes with its own caveats, as all files differ)

While I get the argument that 'this might be useful' and 'operators can change it', it would still be a cleaner system integration.

Given the connection to ongoing discussions on privacy I am filing this not as an enhancement but a bug ticket. Will add a dedicated improvement ticket for a central place to configure the log-level of all components.

**Comment by basisbit** [comment]
this is kind of a dupicate of https://github.com/bigbluebutton/bbb-install/issues/202
The bbb-install repository is probably also the better place to discuss this.

**Comment by ichdasich** [comment]
Whops. Missed that even though I am following it. Closing.
