### ISSUE TITLE
The External meeting ID ar not shown in my server and the recording for respective meeting are is not processed

### ISSUE THREAD

**Issue by Perilous-Programmer** [bigbluebutton/bigbluebutton#9601]
**Describe the bug**
I am using the BBB for my institutions online classes. I am using the demos api to create the record every class. initially it was fine but from past 1 week there are meetings with no external ID and their recording is also not processed.

**To Reproduce**
can't tell because it is random. out of 20 daily meetings 5 or 8 have this problem.

**Screenshots**
![image](https://user-images.githubusercontent.com/5723430/82290378-39c1e380-99c0-11ea-9d69-f5be9db4d72f.png)

**Desktop (please complete the following information):**
 - OS: windows 10, Mac
 - Browser Chrome, Safari, firefox

**Smartphone (please complete the following information):**
 - Device: all smart phones
 - OS: IOS and android
 - Browser chrome browser, Safari

**Comment by aogilvie** [comment]
We also have this problem

bbb 2.2.15

API shows create call coming in, including externalMeetingId
```
/var/log/bigbluebutton/bbb-web.log:2020-10-22T00:17:27.129Z INFO  o.bigbluebutton.api.MeetingService -  --analytics-- data={"duration":0,"record":true,"logCode":"create_meeting","name":"test","description":"Create meeting.","meetingId":"f645fca0e8d86bafc88d4a7a059c468a862dfba5-1603325847076","externalMeetingId":"f6fa4d1013fb11eb94d70dadb1702a50","isBreakout":false,"webcamsOnlyForModerator":false}

```

bbb-record --watch

![example](https://user-images.githubusercontent.com/970364/96804260-78fdd000-1449-11eb-966a-cf6cbaced58a.png)

No external Id.

then the meeting finished the webhook for meeting-ended also does not have the external-meeting-id. Therefore, one can assume the create API is not storing the external-meeting-id in the database.

@Perilous-Programmer any update?

**Comment by mahmoudabdelhalim** [comment]
I have the same issue, I used BigBlueButton v 2.3, Any update about solving it?
@Perilous-Programmer @aogilvie @ffdixon 

![error big](https://user-images.githubusercontent.com/16545049/104059373-e83fc080-51fd-11eb-8122-1c0150c380ab.PNG)
![error big 2](https://user-images.githubusercontent.com/16545049/104059378-eaa21a80-51fd-11eb-9fc1-2ccdeabe7d56.PNG)

**Comment by aogilvie** [comment]
No updates yet. Do you have recording marks in your events.xml ?
Are you using a the API to create sessions or greenlight?

**Comment by mahmoudabdelhalim** [comment]
What do you meaning marks in events.xml?
Yes, I used API to handling the sessions, and when I tried to using greenlight the record working and I got it but in found it in Greenlight Dashboard.

**Comment by aogilvie** [comment]
The recordings are generated from stitching various information together from the events.xml file. Each session creates an events.xml. You can find them in /var/bigbluebutton/recordings/raw/<internal sessionId>/
Do it you see a difference in the event files if they are created by API Vs greenlight?

**Comment by fra967** [comment]
I had a similar problem, twice, using Greenlight. Nothing saved in `/var/bigbluebutton/recording/raw/ID`, actually the directory was not present at all. This is also discussed in #9175
The possible causes I could think of - but I haven't managed to reproduce - are:
- the user who started the recording exited the meeting before its end
- the server was been shut down shortly after the end of the meeting (not allowing enough time to process the recording)

In the end, it seems that the `events.xml` file is not committed to disk. For the failed recordings, there is no directory `/var/bigbluebutton/events/ID`

The only workaround, in case you are desperate to recover the recording and all you are interested into is the audio and the deskshare (like in my case), is to recover the following files
- `/var/freeswitch/meetings/ID-*.opus` for the audio recording
- `/var/kurento/screenshare/ID/*.webm` for the deskshare video files
- `/var/kurento/recordings/ID/*.webm` for the webcam video files
then transcode them into something usable in a video editing app, and manually stitch everything together.

**Comment by Perilous-Programmer** [comment]
I am using the Moodle and BBB for virtual Classrooms. 
@fra967 is right this happens when the server / services crash due to any reason. 

All the raw recording and data is there and in 50% cases events.xml had recording mark. but for some reason the ID is lost. Probably due to redis.

**Comment by Perilous-Programmer** [comment]
for now I have upgraded the servers to 40 cores and 

1. updated the trans-coding service code for faster encoding
2. set the cores affinity 20 for BBB and 20 for trans-coding and other stuff

after this the server seems to be stabilized.

**Comment by sripathroy** [comment]
I am facing this issue on one of my instance where recordings are not listed and processed.

Is the below error related to it. As both things happened on a similiar timeline.

![image](https://user-images.githubusercontent.com/5587362/121563914-85668580-ca38-11eb-925b-b1643c518bca.png)

**Comment by maaami98** [comment]
I'm solved this problem!! 
This problem was caused by an unfinished meeting.

Solving step

cd /usr/local/bigbluebutton/core/scripts

 ruby events/events.rb -m 9eb8eb719bf7fad8856f415006b287028c090104-1624190427084
 
 
![image](https://user-images.githubusercontent.com/35247648/123319078-9df69580-d538-11eb-9495-f44630a9a6c3.png)
if you get an error like this try :
touch  /var/bigbluebutton/recording/status/ended/9eb8eb719bf7fad8856f415006b287028c090104-1624190427084.do
ne

again run 
ruby events/events.rb -m 9eb8eb719bf7fad8856f415006b287028c090104-1624190427084
ruby archive/archive.rb -m 9eb8eb719bf7fad8856f415006b287028c090104-1624190427084
ruby sanity/sanity.rb -m 9eb8eb719bf7fad8856f415006b287028c090104-1624190427084

and wait :)

**Comment by apollo-010001010** [comment]
Yes!!! Found a Workaround. Not sure if it's the appropriate way though, Nothing else on the internet works for me so...
BigBlueButton Version 2.6.11

To rebuild a Record for which `bbb-record --rebuild <internal-meeting-id>` doesn't work
Step1. Go to `/var/bigbluebutton/recording/status/recorded`
Step2. Make a file `<internal-record-id>.done`, and save it obviously

That's pretty much it. The rebuilding should start. Make sure you have `bbb-rap-starter` and `bbb-rap-resque-worker` started. To verify if it's rebuilding, use the `htop` and check if ffmpeg process start for the <internal-record-id> you used (while making the .done file)

You won't be able to see the `.done` file by `ls` command or such, I think because bigbluebutton instantly reads and deletes the file (and starts to rebuild it)

**Comment by Hernandc13** [comment]
alguien que le salga esto, no reconoce el id de la grabación supuestamente es error de Moodle al agregar al id "[0], por lo que de manera interna bbb no reconoce ese id y no procesa las grabaciones.
![Uploading Captura de pantalla 2024-09-25 192110.png…]()

**Comment by Hernandc13** [comment]
`
![image](https://github.com/user-attachments/assets/f8211b67-26e7-4396-9b32-c44c6d965f72)
`

**Comment by Hernandc13** [comment]
alguien que le salga esto, no reconoce el id de la grabación supuestamente es error de Moodle al agregar al id "[0], por lo que de manera interna bbb no reconoce ese id y no procesa las grabaciones.
![Uploading Captura de pantalla 2024-09-25 192110.png…]()

**Comment by Hernandc13** [comment]
------------------
2a5622ee9ad0a1dec0d9dc690e521e654ecc7c4f-1727304640960  Wed 25 Sep 2024 10:50:40 PM UTC  X   XXXXX  XX      0 presentation         presentation        f9c88e591fcb2a7c68ad7b04816bb127dba9b48f-53-47[0]
ff825430d93b61819edbcd1443506dbe463ec197-1727147988226  Tue 24 Sep 2024 03:19:48 AM UTC  X   XXX X  XX      0 presentation         presentation        n9zmcmak56lwgeyzyc3s8mgwqsvpur6q6iofnydp
2a5622ee9ad0a1dec0d9dc690e521e654ecc7c4f-1727145685893  Tue 24 Sep 2024 02:41:25 AM UTC  X   XXX X  XX      0 presentation         presentation        f9c88e591fcb2a7c68ad7b04816bb127dba9b48f-53-47[0]
33577a3151a93260a361ed870c4349485ab97872-1727142859697  Tue 24 Sep 2024 01:54:19 AM UTC  X   XXX X  XX      0 presentation         presentation        067625a5135454f51bbe31b602a91f7c7694eefc-298-91[0]
bb6e403fae16e833baa1e30f5b057367f4c9f187-1726505432219  Mon 16 Sep 2024 04:50:32 PM UTC  X   XXX X  XX      0 presentation         presentation        ba7a59d7febbce5c7d23c86cbac910bc2a5b67fd-177-86[0]
ab0898c5eede7388dff638927b8d35809bf5e663-1726239684180  Fri 13 Sep 2024 03:01:24 PM UTC  X   XXX X  XX      0 presentation         presentation        c9473a68c191684d9c6f63e85ed930b5e42ee6ee-2-85[0]
c4d14c8eca19c67b07bf89d8e67a2c8e7eef89e6-1726230088283  Fri 13 Sep 2024 12:21:28 PM UTC  X   XXX X  XX      0 presentation         presentation        6885c2140ef160207573bcd2f0b5a5fd0db1e7b2-53-89[0]
ab0898c5eede7388dff638927b8d35809bf5e663-1726180193539  Thu 12 Sep 2024 10:29:53 PM UTC  X    XXXX  XX      0 presentation         presentation        c9473a68c191684d9c6f63e85ed930b5e42ee6ee-2-85[0]
c4d14c8eca19c67b07bf89d8e67a2c8e7eef89e6-1726149976746  Thu 12 Sep 2024 02:06:16 PM UTC  X    XX X          0                                          6885c2140ef160207573bcd2f0b5a5fd0db1e7b2-53-89[0]
c4d14c8eca19c67b07bf89d8e67a2c8e7eef89e6-1726149672500  Thu 12 Sep 2024 02:01:12 PM UTC  X    XX X          0                                          6885c2140ef160207573bcd2f0b5a5fd0db1e7b2-53-89[0]
271959e917ca697833ea87498c7fa8da0c3456f0-1726149260965  Thu 12 Sep 2024 01:54:20 PM UTC  X    XX X          0                                          9a6180b73c920286f40a0c915168deb9a67c8352-53-90[0]
c4d14c8eca19c67b07bf89d8e67a2c8e7eef89e6-1726149050751  Thu 12 Sep 2024 01:50:50 PM UTC  X    XX X          0                                          6885c2140ef160207573bcd2f0b5a5fd0db1e7b2-53-89[0]
6fe9273eca27c345a7613b068d6d3b4f62adba15-1726091544724  Wed 11 Sep 2024 09:52:24 PM UTC  X    XX X          0                                          3242d6e0377e0b9c852eb76c541017077af1f08f-21-88[0]
3bddd8ba89dc77661362ad624a8f784832ce2f69-1726089420226  Wed 11 Sep 2024 09:17:00 PM UTC  X    XX X          0                                          815a7536ee908aa8a030be97d75e2129eba7b113-58-23[0]
ab0898c5eede7388dff638927b8d35809bf5e663-1726088749005  Wed 11 Sep 2024 09:05:49 PM UTC  X    XX X          0                                          c9473a68c191684d9c6f63e85ed930b5e42ee6ee-2-85[0]
3bddd8ba89dc77661362ad624a8f784832ce2f69-1726088307575  Wed 11 Sep 2024 08:58:27 PM UTC  X    XX X          0                                          815a7536ee908aa8a030be97d75e2129eba7b113-58-23[0]
5d7748dc56b956b404c555a2fb645b1fe53575e7-1726088168118  Wed 11 Sep 2024 08:56:08 PM UTC  X    XX X          0                                          ae537fd1c54360c656934535e9b3556848e6650d-84-82[0]
ab0898c5eede7388dff638927b8d35809bf5e663-1726085984564  Wed 11 Sep 2024 08:19:44 PM UTC  X   XXX X  XX      0 presentation         presentation        c9473a68c191684d9c6f63e85ed930b5e42ee6ee-2-85[0]
2a5622ee9ad0a1dec0d9dc690e521e654ecc7c4f-1725648430364  Fri 06 Sep 2024 06:47:10 PM UTC  X    XX X          0
