### ISSUE TITLE
BigBlueButton Core flies out every minute

### ISSUE THREAD

**Issue by dsobit** [bigbluebutton/bigbluebutton#9603]
**Describe the bug**
Recently I faced problem that bigbluebutton server constantly flies out practically every minute.  When I checked bbb-conf debug it shows no errors. With networking is everything ok and firewall configured correctly, because server was working before fine. What problem it may be?

If you require additional information, please contact me

**To Reproduce**
Steps to reproduce the behavior: I do not know how to reproduce this problem

**Screenshots**
![image](https://user-images.githubusercontent.com/64262515/82318587-c7113200-99d8-11ea-9546-9805a4dd7a8c.png)

**Comment by basisbit** [comment]
this issue tracker here is not for support questions. Please use the support forums / mailing lists instead. thanks.
