### ISSUE TITLE
adjust sound level per user

### ISSUE THREAD

**Issue by holgersson32644** [bigbluebutton/bigbluebutton#9604]
**Is your feature request related to a problem? Please describe.**
The sound resp. loudness input levels of different users in BBB sessions can differ quite a lot depending on the audio setups used.

**Describe the solution you'd like**
I would appreciate a sound level configuration interface on a per user basis. This could e.g. be added to the small popup/overlay which appears when a user name is clicked on.

**Describe alternatives you've considered**
A server side sound level normalization would be another workaround, but occasionally you actually want to hear people at different levels, so I'd prefer the client approach. Besides, normalization might add more load server-side.

**Comment by AbcAeffchen** [comment]
Just to suggest an other option: 

As I understand it, currently audio gets mixed on the server and everyone gets only one audio stream which makes client side per user volume adjustments impossible. 
A moderator could set the volume level, such that the server mixes them accordingly instead of normalizing the audio.

**Comment by keunes** [comment]
Related to #9046

**Comment by matiasilva** [comment]
Not only related, it is entirely a duplicate. Merging with #9046.

**Comment by keunes** [comment]
Before posting I was thinking whether it was a duplicate or not. In my mind one was about allowing admins (hosts? I'm not into BBB lingo yet) to adjust mic volume of others (affecting all viewers), where the other issue was about allowing regular users to adjust the volume of a specific person (only affecting this specific viewer's device). But rereading both I guess you're right :)
