### ISSUE TITLE
recording speed

### ISSUE THREAD

**Issue by mohammad2319** [bigbluebutton/bigbluebutton#9613]
Hi
Recording session very slow publishing.
im require use all cpu core for speedup process of recording.

customized video.rb:
 extension: 'webm',
        parameters: [
          %w[-r 30 -g 90 -s 640x360 -quality realtime -speed 7 -threads 4 -row-mt 1 -tile-columns 1 -frame-parallel 0 -qmin 4 -qmax 48 -b:v 730k -c:v libvpx-vp9
             -c:a libopus -b:a 48K
             -f webm]

default:
extension: 'webm',
        parameters: [
          %w[-c:v libvpx-vp9 -b:v 750K -minrate 375K -maxrate 1088K -crf 33 -quality good -speed 4 -g 240 -tile-columns 2 -threads 4
             -c:a libopus -b:a 48K
             -f webm]

**Comment by mohammad2319** [comment]
please send me video.rb file for speed up recording process with low quality

**Comment by jesusvaldivia** [comment]
Hi @mohammad2319 a good choose to speed up the processing time of the recording files is to activate the mp4 format and disable webm you can change this setting in the file **/usr/local/bigbluebutton/core/scripts/presentation.yml**
```yaml
# For PRODUCTION
publish_dir: /var/bigbluebutton/published/presentation
video_formats:
#- webm
- mp4
```
The webm format uses the VP8 codec which takes a long time to process compared to mp4, if you still want to speed up the encoding time  you can change the parameter `-present` to `veryfast`.

make sure to change the parameters in `process_webcam_videos` and `process_deskshare_videos`.

**Comment by pedrobmarin** [comment]
Amazing work by @abautu covered this issue https://github.com/bigbluebutton/bigbluebutton/pull/11589
