### ISSUE TITLE
I want to talk specific user with audio communication in bigbluebutton

### ISSUE THREAD

**Issue by dharmendravirasat** [bigbluebutton/bigbluebutton#9615]
I want to talk specific user with audio communication in bigbluebutton like:
The moderator/teacher wants to hear a specific user/student with audio. 
At present student audio, all students listening.

**Comment by mrkeksi** [comment]
Whats about Breakout Rooms? Otherwise it would be confusing. Then how would the listener know that the conversation is private?

**Comment by dharmendravirasat** [comment]
teacher wants one to one conversation with students

**Comment by dharmendravirasat** [comment]
my query 
->teacher wants one to one conversation with students  and with audio/voice
->I know that we have a private chat feature.
but, want to private audio conversation feature. 
@mrkeksi 
plz reply
thanks

**Comment by basisbit** [comment]
@dharmendravirasat just create another BigBlueButton room or a bunch of them and have the teacher do the one on one talks there. No need to add yet another feature to the UI and thus cause feature creep...

**Comment by ralferlebach** [comment]
+1

As a teacher, there are situations in a conference, whre private speech or talk back is necessary. As a "cool" solution, I suggst the feature to open a new room out of the user list that send this particualr user a private cat-message with the link to join this room.

Maybe some option like that:
![BBB-Mock_up](https://user-images.githubusercontent.com/12737344/82660042-ec48af00-9c29-11ea-999d-40068370a732.png)

**Comment by matiasilva** [comment]
Merging with #4047
