### ISSUE TITLE
Shared notes is constantly switching to public chat after upgrade to v2.2.11

### ISSUE THREAD

**Issue by MrCapitalist** [bigbluebutton/bigbluebutton#9618]
Hi. I have a problem in using shared notes feature in new version of BBB
After I upgrade from v2.2.9 to 2.2.11 using bbb-install shell, when a presenter open shared notes and start typing, after a few second the note section automatically switch to public chat and presenter forces to click on share notes title and waits to open it again. It doen't have any regular rule in switching. Sometimes it happen when he type one or two words, sometime it happen every 1 or 2 minutes, sometimes it doesn't happen!! For some users it happen, for some other it doesn't happen!

I ran `bbb-install` again but it didn't affect anything

Please help me to resolve it. Thanks

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [Chrome]
 - Version [81.0.4044.138 (Official Build) (64-bit)]

**Comment by MrCapitalist** [comment]
UP

**Comment by antobinary** [comment]
Hi @MrCapitalist 
I just tried it locally and did not encounter it. Could you please re-test on test.bigbluebutton.org and let us know if you hit it. 

Any other info to help narrow down the issue would be useful!
