### ISSUE TITLE
Disabling auto correct in whiteboard

### ISSUE THREAD

**Issue by soheilrahsaz** [bigbluebutton/bigbluebutton#9622]
In HTML5 whiteboard, when you draw something, it tries to fix it's drawing and make it better.
Is it possible to disable this feature?
Because teachers have reported that they cannot write with a light pen smoothly because it keeps changing the drawings.

**Comment by basisbit** [comment]
The whiteboard draw event handling has been improved already as part of the upcoming release 2.3. That should solve your problem.
