### ISSUE TITLE
BigBlueButton

### ISSUE THREAD

**Issue by shivpatel779** [bigbluebutton/bigbluebutton#9624]
@ffdixon 
I have install bigbluebutton successfully on my server,
But when we run this command 
sudo bbb-conf --check

Its ourput

BigBlueButton Server 1.1.0 (565)
                    Kernel version: 4.4.0-1102-aws
                      Distribution: Ubuntu 16.04.6 LTS (64-bit)
                            Memory: 4044 MB

/var/www/bigbluebutton/client/conf/config.xml (bbb-client)
  		Port test (tunnel): chatx.live
                              red5: chatx.live
              useWebrtcIfAvailable: true

/opt/freeswitch/etc/freeswitch/sip_profiles/external.xml (FreeSWITCH)
                    websocket port: 5066
                    WebRTC enabled: true

/etc/nginx/sites-available/bigbluebutton (nginx)
                       server name: chatx.live
meetings.chatx.live
                              port: 80, [::]:8080
                    bbb-client dir: /var/www/bigbluebutton

/var/lib/tomcat7/webapps/bigbluebutton/WEB-INF/classes/bigbluebutton.properties (bbb-web)
                      bbb-web host: chatx.live

/usr/share/red5/webapps/bigbluebutton/WEB-INF/red5-web.xml (red5)
                  voice conference: FreeSWITCH

/usr/local/bigbluebutton/core/scripts/bigbluebutton.yml (record and playback)
                     playback host: chatx.live

** Potential problems described below **
# IP does not match:
#                           IP from ifconfig: 172.31.35.25
#   /etc/nginx/sites-available/bigbluebutton: chatx.live
meetings.chatx.live

/usr/bin/bbb-conf: line 1258: [: chatx.live: binary operator expected

Please help me how to fixed this issue and when we join the meeting unable to hear other person

**Comment by basisbit** [comment]
This issue tracker here is for bbb development related issues only. Please instead ask your support question at https://groups.google.com/forum/#!forum/bigbluebutton-setup

**Comment by mosyBG** [comment]
Hello. why you dnt install BBB 2.2 ?
