### ISSUE TITLE
how to hide side bar and more customisation in Join url UI

### ISSUE THREAD

**Issue by anupkumrawat** [bigbluebutton/bigbluebutton#9625]
Hello Everyone,
I am done with installing BBB on dedicated server and everything is working well. Using API I have created meeting and sending join URL to participants. But in default UI after join, I want to do some customisation like I dont want to display side bar for chat, users etc. permanently. Also at bottom + icon I dont want to allow user to create polls. Instead of BBB chat, I want to use my own chat system which is developed separately. So can you help me with this issue as even I am unable to locate html5 directory which is showing in my join url https://mydomain.com/html5client/join?sessionToken=gh2doas9plh5iyxu . So please help me.
Thanks in Advance,
Anup Kumrawat

**Comment by basisbit** [comment]
This issue tracker here is for bbb project development issues only. Please instead ask your support /custonization questions at https://groups.google.com/forum/#!forum/bigbluebutton-setup
