### ISSUE TITLE
[Security] BBB still allows SHA1 for authenticating API requests

### ISSUE THREAD

**Issue by ichdasich** [bigbluebutton/bigbluebutton#9634]
At the moment, BBB still supports SHA1 to hash the auth-token+request specifics for authentication of clients for API endpoints. While this is practically a limited issue (communication should be via TLS anyway), SHA-1 is considered deprecated for security mechanics (since 2011 by NIST, since 2015 they advice federal agencies in the US to no longer use it, see: https://csrc.nist.gov/Projects/Hash-Functions/NIST-Policy-on-Hash-Functions ; This might be relevant given specific users of BBB). 

Given that practical attacks on SHA1 are now feasible (see https://eprint.iacr.org/2020/014.pdf) this should be deprecated in BBB, e.g., by SHA256 (which is already supported).

**Comment by ichdasich** [comment]
Hold on this might be self solving...

**Comment by KimBrodowski** [comment]
Didn't even know SHA256 was supported at all. This is excellent news, especially because clients get in contact with checksums regularly. TLS doesn't protect against clients potentially learning the server's secret.

**Comment by pedrobmarin** [comment]
I'm closing this one since it was propagated to the documentation

**Comment by ichdasich** [comment]
Uhm... given the state of SHA1 I would argue that the underlying issue is not the documentation but the continued support of SHA1 at all (besides all the other issues with your use of a simple hash in authentication).

**Comment by pedrobmarin** [comment]
Never mentioned the problem was restricted to the documentation. We'll keep track of it from there.

**Comment by anoadragon453** [comment]
It appears that support was added by https://github.com/bigbluebutton/bigbluebutton/pull/6605, and landed in BigBlueButton v2.2.0.
