### ISSUE TITLE
401 Error. Not autorized.

### ISSUE THREAD

**Issue by plastilincheg** [bigbluebutton/bigbluebutton#9635]
Hello. Have a problem BigBlueButton Server 2.2.9 (1891) + Greenlight 2.5.2. In room over 17 participants. In admin mode i can try join to room, but see error 401. What is it mean. Maybe some limits?

bbb-conf status result

nginx —————————————————► [✔ - active]
freeswitch ————————————► [✔ - active]
redis-server ——————————► [✔ - active]
bbb-apps-akka —————————► [✔ - active]
bbb-transcode-akka ————► [✔ - active]
bbb-fsesl-akka ————————► [✔ - active]
red5 ——————————————————► [✔ - active]
mongod ————————————————► [✔ - active]
bbb-html5 —————————————► [✔ - active]
bbb-webrtc-sfu ————————► [✔ - active]
kurento-media-server ——► [✔ - active]
etherpad ——————————————► [✔ - active]
bbb-web ———————————————► [✔ - active]

bbb-conf --check result

BigBlueButton Server 2.2.9 (1891)
Kernel version: 4.4.0-178-generic
Distribution: Ubuntu 16.04.6 LTS (64-bit)
Memory: 10237 MB
CPU cores: 16

/usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties (bbb-web)
bigbluebutton.web.serverURL: https://online.domain.tld
defaultGuestPolicy: ALWAYS_ACCEPT
svgImagesRequired: true

/etc/nginx/sites-available/bigbluebutton (nginx)
server name: online.domain.tld
port: 80, [::]:80
port: 443 ssl
bbb-client dir: /var/www/bigbluebutton

/var/www/bigbluebutton/client/conf/config.xml (bbb-client)
Port test (tunnel): rtmp://online.domain.tld
red5: online.domain.tld
useWebrtcIfAvailable: true

/opt/freeswitch/etc/freeswitch/vars.xml (FreeSWITCH)
local_ip_v4: XXX.XXX.XXX.26
external_rtp_ip: stun:stun.freeswitch.org
external_sip_ip: stun:stun.freeswitch.org

/opt/freeswitch/etc/freeswitch/sip_profiles/external.xml (FreeSWITCH)
ext-rtp-ip: $${local_ip_v4}
ext-sip-ip: $${local_ip_v4}
ws-binding: :5066
wss-binding: XXX.XXX.XXX.26:7443

/usr/local/bigbluebutton/core/scripts/bigbluebutton.yml (record and playback)
playback_host: online.domain.tld
playback_protocol: https
ffmpeg: 4.2.2-1bbb1~ubuntu16.04

/etc/bigbluebutton/nginx/sip.nginx (sip.nginx)
proxy_pass: XXX.XXX.XXX.26

/usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml (Kurento SFU)
kurento.ip: XXX.XXX.XXX.26
kurento.url: ws://127.0.0.1:8888/kurento
localIpAddress: XXX.XXX.XXX.26
recordScreenSharing: true
recordWebcams: true
codec_video_main: VP8
codec_video_content: VP8

/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml (HTML5 client)
build: 894
kurentoUrl: wss://online.domain.tld/bbb-webrtc-sfu
enableListenOnly: true

Potential problems described below

**Comment by basisbit** [comment]
This issue tracker here is for bbb development related issues only. Please instead ask your support question at https://groups.google.com/forum/#!forum/bigbluebutton-setup

**Comment by basisbit** [comment]
401 on the bbb server means that the session that you want to join was not created/registered. Greenlight should have done that. Please ask at the setup forum for help on how to resolve this problem.
