### ISSUE TITLE
html5 development and production errors

### ISSUE THREAD

**Issue by hoang000147** [bigbluebutton/bigbluebutton#9639]
Hi everyone,

I followed this document: https://docs.bigbluebutton.org/2.2/dev.html#developing-the-html5-client to try to develop html5 client. I've only followed the steps in the document without any changes to the code, i.e. stop service, run meteor npm install and npm start (both development and production environment). However, there are some errors like 1004 (Failure on call - Can't use micro) or the annotations on presentation board is not saved (when I drew it showed up but after release mouse button it disappeared immediately although the log showed it has been added). Are these errors common or I failed setting up the environment?

In addition, can I make html5 a service like bbb-html5.service to run with systemctl instead of using NODE_ENV=production npm start? If so, can someone show me how since I'm only new to this.

Best regards,
Hoang

**Comment by basisbit** [comment]
This issue tracker here is only for the projects' software development related issues, not for support requests. Please ask at the support forum / mailing list instead and close this issue here. https://groups.google.com/forum/#!forum/bigbluebutton-dev
