### ISSUE TITLE
Translate BigBlueButton into other languages

### ISSUE THREAD

**Issue by bigbluebutton-issue-import** [bigbluebutton/bigbluebutton#964]
Originally reported on Google Code with ID 209

```
We're getting more people asking for the ability to run BigBlueButton in 
other languages.

Perhaps one of the open source developers wants to take on this project.  

```

Reported by `ffdixon` on 2009-10-09 00:44:55

**Comment by emadbagheri96** [comment]
it seems that in the newer versions, this string for disconnecting popup was left out from translation which says:
"Are you sure you want to end this meeting for everyone (all users will be disconnected)?"
![WhatsApp Image 2020-08-17 at 20 08 38](https://user-images.githubusercontent.com/21096918/90472182-3233e700-e135-11ea-89a4-ba97a4b657d3.jpeg)
I searched and saw that there is no string left at transifex to be translated for persian. how can we fix it?
