### ISSUE TITLE
Presentation image parse error timeout

### ISSUE THREAD

**Issue by akshaykatale99** [bigbluebutton/bigbluebutton#9645]
After the presentation upload, html5 client log shows this error 

ubuntu systemd_start.sh[1463]: error: Error parsing image size. Error: ETIMEDOUT. uri=<server_url>/bigbluebutton/presentation/58faebeb21b6014af28b328cf7378b5484363ef5-1590178356847/58faebeb21b6014af28b328cf7378b5484363ef5-1590178356847/9e11366b63247c99059256ec22e12323b097a3eb-1590178500135/svg/7

**Comment by ffdixon** [comment]
Can you reproduce this on https://test.bigbluebutton.org/?

**Comment by akshaykatale99** [comment]
On  https://test.bigbluebutton.org its working fine. 

also, this error appears only when I upload 17-20MB pdf with 100+ pages. for small size and few page pdf, it's working.

**Comment by GhaziTriki** [comment]
@akshaykatale99 Can you please share the file you were testing?
