### ISSUE TITLE
Option to restrict the the number of user's video on screen during a meeting or pagination on ui for showing user video.

### ISSUE THREAD

**Issue by sarita05** [bigbluebutton/bigbluebutton#9655]
I have joined the meeting using url and can not to restrict count of participant video. I want to see only 5 person videos at a time . Pagination will be an good idea in case of more participants as a chunk of n ( say 5 or 8).

For example. After joining meeting based on parameter ( set as 5), I can set the count of video to come on screen and ui slide button should be there as If I will click on it, next 5 will appear and so on.

Showing n number of user video or more than that is hardly visible and not making any sense.
Using the parameter, user can set the count of video coming on screen with pagination support.
At first only 5 video will come on screen and for next, call will land on back-end. Just a thought, if it will reduce the load on back-end server to download the stream. Earlier it was total but using pagination only 5/n that is surely going to be less than total.

**Comment by ichdasich** [comment]
It think that this would make a lot of sense; Either pagination, or focus on talking users, esp. with client load (which, so far, I experienced as the major bottleneck when everyone wants to share their camera).

**Comment by matiasilva** [comment]
This is currently available but as a global setting. See #9657. Would be cool to have this as userdata-bbb_* parameter that can be passed to the join request.
