### ISSUE TITLE
Unable to accept participant to join the room

### ISSUE THREAD

**Issue by srnutthapon** [bigbluebutton/bigbluebutton#9656]
Hi Team,
I'm using BBB 2.2.12, when i try using join api with **'guest=false'** the moderator unable to click accept participant to join the room due to the **Waiting Users** window not shown.

Could you please advice?

Thanks & Best regards
Nutthapon

**Comment by pedrobmarin** [comment]
@antobinary I would check if https://github.com/bigbluebutton/bigbluebutton/issues/7561 and https://github.com/bigbluebutton/bigbluebutton/pull/9189 are somehow related with this issue

**Comment by pedrobmarin** [comment]
@srnutthapon could you just not include the guest param if the user is not a guest? I'm guessing this is related with that old issue I post above.

**Comment by srnutthapon** [comment]
Hi @pedrobmarin I have try exclude the guest param then the participant will able to join the room with no need moderator approval. But in my opinion the participant should still need approval from moderator. Thanks

**Comment by pedrobmarin** [comment]
Sorry , @srnutthapon I'm having some trouble trying to understand the full picture. Couldn't you include the guest param only when it's value wll be true?

**Comment by christophkarls** [comment]
Hi, we use the defaultGuestPolicy=ASK_MODERATOR to ensure, a moderator always has to accept new conference-members. This was a great option to ensure no one can sneak into a running (bigger) conference.
We use the moodle-integration for bbb.
After apdating to the latest version, people can join without moderator-approval. We did not make any changes to the configuration-files. Thanks for your work on this great tool!

**Comment by superseby2** [comment]
Same here, running 2.2.14, creating a room specifically asking for moderation. No permission is ever asked to Presenter or Moderator.
