### ISSUE TITLE
 viewersInWebcam parameter is not working as expected

### ISSUE THREAD

**Issue by manish-yadav** [bigbluebutton/bigbluebutton#9657]
The parameter "viewersInWebcam" placed under /meteor/bundle/programs/server/assets/app/config is not working as expected. What is the role of this parameter? As the name suggested it is controlling viewers webcam in a meeting. I have set it as 2 but all 6 viewers who have joined meetings are able to see video of all users.

Do we have any setting where we can say only the current user and presenter video will be shown? If yes, where we can do that (filename and path)?

**Comment by antobinary** [comment]
Hi @manish-yadav 

These two parameters go hand-in-hand

```
    enableLimitOfViewersInWebcam: false
    viewersInWebcam: 8
```


You may want to see https://github.com/bigbluebutton/bigbluebutton/issues/7556 and https://github.com/bigbluebutton/bigbluebutton/issues/7606

**Comment by matiasilva** [comment]
Seeing as an adequate response has been provided, please close this issue.
