### ISSUE TITLE
Please add official statement on reverse proxies to the documentation and any technical reasons why it doesn't work if possible.

### ISSUE THREAD

**Issue by marshalleq** [bigbluebutton/bigbluebutton#9659]
**Describe the bug**
The google support group and other sources online are littered with a lot of requests to get a reverse proxy setup working.  It took some effort to even find that this is not officially supported, nevertheless with the difficulty in obtaining even one IPv4 address these days, the requests will keep on coming.

Could we please have the official documentation updated to reflect the official position on reverse proxies and also why this is not possible technically would be extremely helpful to many whom have spent hours researching this issue, only to vaguely find out it probably can't be done, but being there is nothing official, it's hard to really know.

**Installation type**
bbb-setup
**Firewall and IP address type**
Server has own private IPv4, public host name,  behind NAT, behind reverse proxy.  Due to the way certificates are authenticated with letsencrypt, I can only have one HTTPS authority inside my network.

Self signed HTTPS cert on BBB could also help.

As an aside, the lack of reverse proxy support means we will probably be forced to look at another product, even though we would prefer to use bbb.

**Comment by ffdixon** [comment]
We would welcome a pull request if anyone who has completed this setup would like to contribute to the documentation.  See

  https://github.com/bigbluebutton/bigbluebutton.github.io

**Comment by ichdasich** [comment]
Heho,
This should be rather easily doable (I assume not with bbb-install.sh straight out of the box, though). The only hard requirement I see is having a hole in your NAT for TURN (which can also be on any port != 443).

- configure the reverse proxy on your web host, obtain the certificate there. 
- setup BBB manually (follow install.sh/the manual documentation at https://docs.bigbluebutton.org/2.2/install.html#installation), and use whatever certificates your reverse proxy accepts (or use LE with DNS auth); Afterall, TLS for users is terminated at the reverse proxy.
- setup a TURN server behind the NAT with a portforward, e.g., on 8443 to not conflict with you main rev-proxy/http host (make sure to put that box into its own zone, so it does not expose your local network)

**Comment by marshalleq** [comment]
Thanks, haven't set up the TURN for NAT yet, I did read that would be required somewhere.  

So, if I have https://bbb.example.com at my reverse proxy and https://bbb.example.com in the mattermost bbb plugin (this internally requires the bbb url which sets a) the client url and b) the bbb connection), this will need to connect through the reverse proxy for both things.  So I create internal dns for bbb.example.com and point that at the internal IP of the reverse proxy. 

Setting it this way, means all traffic from the reverse proxy to bbb is unencrypted and traversing on http as I can only choose to point bbb.example.com at the reverse proxy OR the bbb host obviously.

So. on the bbb host I'd need to set a manual DNS record in /etc/hosts so that bbb itself can see that bbb.example.com does not go to the reverse proxy for internally initiated connections.  

All of this I've done already, without the TURN server / port.  So you're saying TURN cannot be reverse proxied.  To that end I also assume you're also saying TURN does not need https (I haven't looked into TURN yet so forgive me for not knowing that answer yet).  If it does need https it will either need to go through the reverse proxy or connect via another public host name and a self. signed certificate.   (Self signed because I don't think I can have lets encrypt auto renewing certificates on two servers behind a single IP).

Does that sound right?

Thanks.

**Comment by marshalleq** [comment]
Sorry guys, thought I was replying to the discussion thread - not after support here.  If the comment above is not useful, please delete.

**Comment by hanserasmus** [comment]
> * reverse proxy accepts (or use LE with DNS auth);

Thank you for this answer. I have asked about it on the forums, that is possibly why it was created here. My question is: If I run this on NATed network where BBB is running without a HAProy in front of it, all seems to work without a TURN server. So why is a turn server needed if a HAProxy is put in front of BBB if the HAProxy is only caring for the web connections (80 and 443)? I am not trying to  be a smart ass, I am really trying to understand this better and hopefully leave a reference for any newbie out there stumbling onto this by having the same question.

**Comment by ichdasich** [comment]
- Reverse proxy not HA proxy
- NAT without STUN will only work if you do the appropriate port forwards on the NAT router, and the remote client is not behind a NAT

If i see this correctly, the question is: Reverseproxy only, BBB behind that. As soon as my new toys(tm) show up (mem/cpu etc.), I will give this a shot and write the docs.

**Comment by hanserasmus** [comment]
HAProxy is a product, which is a reverse proxy. So was not referring to high availability.

My install without HAProxy did not have any STUN or TURN set up. Only forwarded the ports as per "configuring firewall" docs, and it worked. (80,443 and range of UDP) With clients behind NAT as well.

**Comment by marshalleq** [comment]
>>* Thank you for this answer. I have asked about it on the forums, that is possibly why it was created here. 

Well, indirectly, I created this ticket because of your questions, my question, and everyone else's question because there doesn't appear to be any documentation available to explain, and as such the questions will keep on coming.  (I don't understand why a reverse proxy won't work yet either, and certainly they're a necessary thing for many these days).  But if we can't do it, we should know why and it should be explicitly listed in the documentation so that this question can have an official answer.  To my thinking, the official bbb install has nginx on it exposed over port 80 and that should be able to have a reverse proxy connected to it, but I'm a junior when it comes to reverse proxies, so what do I know.

Perhaps, it will work reverse proxy for most things, then nat for one or two ports, that would be acceptable I'd say.

**Comment by ichdasich** [comment]
Thing with reverse proxy vs. ha proxy: If you say HAproxy, I thoughtTCP hand-off or HTTP/tun or /kal, which is a little less intrusive than a (potentially mingeling) reverse proxy with virtual hosts etcetc.;

Anyway, point being, let's wait for my hardware to arrive, and then I'll see what has to be done and write the docs.

**Comment by marshalleq** [comment]
Thanks @ichdasich what I'd like to stress is that however it works, it needs to work via one url that's the same internally and externally.  Mattermost integration requires this (as would any other).  I suspect the only way will be a self signed cert on bbb, or bbb create a reverse proxy option along with a trusted proxy option to allow unencrypted traffic on https url for that trusted proxy.  That's what gitlab does to get reverse proxies to work.

It makes sense too, If your reverse proxy is presenting https://conf.bbb.com to a client, and you have 3rd party tool like mattermost that requires a url for the address of bbb, it will pass https://conf.bbb.com to the client and also try to connect to bbb internally via https://conf.bbb.com. If I understand how bbb works now, this isn't going to be possible unless bbb is 100% accessible via the reverse proxy via IP only, or under a different unencrypted URL. i.e. http://conf2.bbb.com.  Because you can't point one url to two internal locations (i.e. you can't point httpx://conf.bbb.com to your internal reverse proxy and bbb host).  Remember 3rd party integration only accepts ONE url.

Hope that's clear - sorry to go on. :)

**Comment by ichdasich** [comment]
Ok, got it going on an nginx reverse proxy behind nat. The only thing that is boggering is turn, which needs a dedicated portforward for port 8443 (and rev. proxy settings for the LE challenges, obviously). Will now try to write it down in a more or less documentation like form. We can then think about how to get this into the BBB docs.

**Comment by ichdasich** [comment]
Ok, see here: https://github.com/ichdasich/bbb-rev-prox 

Will explore turn via the rev-proxy and fixing the names (currently from my testsetup) to actual documentation naming later.

**Comment by ffdixon** [comment]
Thanks for sharing this!  We would welcome a pull request to the documentation if you wanted to add a section on this topic.

**Comment by ichdasich** [comment]
Ok, will put that on my todo.

However, before that, it would be nice if somebody could test this, because currently it is all 'works on my machine'. @ffdixon , can you maybe ask one of your engineers to try to set this up as a test-case? Alternatively, any other volunteers?

**Comment by marshalleq** [comment]
OK, since I asked for this, I can do up a test.  I'll try get onto that soon.

**Comment by ichdasich** [comment]
Sounds like a plan. Let me know if something does not work/has to be adapted for other software.

**Comment by marshalleq** [comment]
Cool, second in the queue of IT things, taiga events first, which is turning into a nightmare...

**Comment by marshalleq** [comment]
OK, so first and foremost, thanks so much for giving this a go and making a functioning solution.

Before I start though, I read through your documentation so that I get things right and have some questions / concerns.

As a side note first though: Obviously these instructions are working around lacking application design, Specifically in how it's referencing DNS and how it requires HTTPS internally to work behind a reverse proxy.  I suppose you can argue that https should be everywhere including internally, but I'd argue back that that's an individual choice, just one that doesn't seem to be possible with bbb due to it's design.  So when I read in your instructions to copy certs from LE to bbb I'm both impressed and concerned.  Impressed with your work but concerned that we shouldn't have to do unnecessarily complicated things to work around design issues.  It feels like something that's going to break (I'd already dropped bbb due to this issue, but had hoped it could become an option again, but now I'm thinking not). So to that end perhaps we can add a  new request to bbb to address the cause of the above once we confirm this is working? (As I had mentioned previously regarding adding a trusted proxy setting to avoid all the pain).

Anyway, some questions:

Step 1: (/etc/hosts)

Does this all have to be done manually in /etc/hosts?  I mean, I assume I can just set in my internal DNS server?  

Step 3:  Does this need to be on port 8443?   I assume that's just a suggestion, Since this is a separate host I've just used a docker container.  Default turn ports are 3478 for UDP / TCP plain http and 5349 (TLS).

Step 4: Must I really install all of bbb again, or can this be done over the top of my existing installation?

Many thanks.

**Comment by ichdasich** [comment]
Heho,

Concerning design issues: Using HTTPS everywhere in my (kind of professional ;-)) opinion is actually one of the few spots where BBB does actually do a good job in terms of security by
default. Also keep in mind that most likely within the next 1-2 years HTTP only sites will most likely be marked as 'security issues' by browsers. So getting HTTPS rolling internally is also a thing to do to keep users from complaining. 

Furthermore, there are some ways to not have to do the certificate syncing; I know at least cloudflare does something like that to have rev-proxies which can work with only the origin host having the cert/keys. However, as my objective was making it work, not preventing the syncing of TLS certs, I did not look into this. Will maybe take a look later on whether (at least nginx) has a feature for that.

Step 1: If you have splitview DNS, you can also go for that; If you do that, you probably would not have to patch bbb-install.sh and set the NAT rules for internal hosts; I just went for the /etc/hosts sollution, as it removes the complexity of having split view DNS.

Step 3: Nope, does not have to be 8443; Just make sure to use 5349 in the sed statement, instead of
8443/change the file manually.

Step 4: No, as long as you ensure the config is as it would be after running that command. Technically, just running the bbb-install.sh line on an existing BBB server should just reconfigure things (and update bbb in the process). Most of the 'real' magic is Step 5 anyway.

I took your comments and integrated them into the howto already.

**Comment by marshalleq** [comment]
Hey thanks for that.  Firstly regarding HTTPS, I'm not for one second suggesting plain http should be exposed to the internet, just internally in my own secure dmz / vlan.  That's how everything else I've got is done and how it's been recommended to be done when there is only one IP address.  But this copying of certs is intriguing.  In my case the LE is in a docker behind NAT already, so it's probably going to be difficult, unless I can expose it to the host somehow and go that route.

I think splitview / dual homed DNS will work, but probably still need /etc/hosts on bbb just need to think about that.  It would be hugely helpful once this is done to do a small architecture diagram for people I think.  Perhaps I can make one.

Thanks for updating howto.  While we're on that subject, something that confused me for a moment was in DNS section where it's got web.nat.example.com 10.23.42.4 then it says below it two other domains / IP's 10.23.42.3 and 5.  I think this could be made clearer.

For example, update the DNS configuration to point out clearly this is an external internet registered IP address at your registrar, not in the same range as the  internal, then in section 1 point out the other two addresses are internal private addresses.

You get what I mean right?  Sorry if I'm not explaining that well.

**Comment by ichdasich** [comment]
10.23.42.4 is the internal address of the host running the reverse proxy; Only the external NAT gateway has a public IP address which is also clearly marked as such. The NAT gateway forward tcp/80 and tcp/443 to 10.23.42.4.

**Comment by marshalleq** [comment]
Ah OK, I get what you're saying now.  I definitely need an architecture doc to make it clear :)

**Comment by matiasilva** [comment]
Please close this issue as this has been resolved. If you could submit a PR to the docs, even better.

**Comment by ichdasich** [comment]
@matiasilva good to see new people joining the PM team. Still, I am still waiting for feedback from @marshalleq on whether there are any bugs in the documentation, hence i'd like to keep this open.

**Comment by marshalleq** [comment]
Hi everyone, sorry I don't seem to have noticed the last few comments, until now and as such haven't validated it as working.  I ended up going for a paid product for now (though I suspect BBB is much better and will revisit in future) - so I don't have BBB installed at present.  My task list is very long - not sure when I could get to it, but surely there are plenty of people using reverse proxy's that could validate this?  Many thanks.

Marshalleq
