### ISSUE TITLE
Update bbb-web

### ISSUE THREAD

**Issue by squid46** [bigbluebutton/bigbluebutton#9660]
Hello.

File "bigbluebutton.properties" parameter defaultWelcomeMessage. 
Before update
defaultWelcomeMessage=\u0414\u043e\u0431\u0440\u043e \u043f\u043e\u0436\u0430\u043b....
after update
defaultWelcomeMessage=0414043e04310440043e 043f043....

**Comment by basisbit** [comment]
Please use the `appy-config.sh` script to apply your customization after each bbb update. See https://docs.bigbluebutton.org/2.2/customize.html#automatically-apply-configuration-changes-on-restart

**Comment by squid46** [comment]
It's easier to prescribe with your hands than to sort it out.

**Comment by rasos** [comment]
Duplicate of #9370 - upgrading removes the `\u` from escaped characters

**Comment by basisbit** [comment]
Thank you @rasos!
