### ISSUE TITLE
draggin files to running session quits the session

### ISSUE THREAD

**Issue by rottaran** [bigbluebutton/bigbluebutton#9661]
**Describe the bug**
Some users tried to upload a new presentation by simply dragging it onto the presentation area in the conference. Then, Firefox kicks the user out of the conference in order to show the contents of the file. This is a quite unexpected behaviour. 

**To Reproduce**
1. enter a conference session
2. become presenter
3. drag a file into the session window
4. browser loads now page in that window

**Expected behavior**
Do not leave the conference session. Show a warning or a hint about how to upload presentations. Ideally, directly upload and show the document if the user is the presenter currently.

**Actual behavior**
No warning. User has to reconnect.

**BBB version (optional):**
BigBlueButton Server 2.2.9 (1933)

**Desktop (please complete the following information):**
 - OS: Windows, Mac
 - Browser: Firefox

Many thanks for your awesome great work! BigBlueButton rocks!

**Comment by ffdixon** [comment]
This is the expect behavior -- to support drag and drop, you need to be in the upload presentation screen.

![image](https://user-images.githubusercontent.com/290351/82757244-27bfb680-9dad-11ea-9d46-047d9567a58f.png)

and from there you can drag-and-drop a presentation for upload.

**Comment by rottaran** [comment]
Many thanks for your reply! Yes, I know. This is the expected workflow from the a developers point of view and I am fine with that personally. Some users, on the other hand, seem to have a natural expectation that dragging a file onto the browser window does something reasonable. Instead, this kicks them out of the session surprisingly without any warning. 

At least, a dummy drag&drop handler that does nothing, just to prevent the browser from opening the document, would be super helpful.

**Comment by ffdixon** [comment]
Agreed.  Ideally, we can allow drag-and-drop of presentation over the main BigBlueButton area in a future version.
