### ISSUE TITLE
BUG - Error processing large recorded meetings

### ISSUE THREAD

**Issue by rriscado** [bigbluebutton/bigbluebutton#9664]
BBB-2.2.11

When a large record meet are processed, many events are generated with data error (blank) in events.xml

Event file
```
<event timestamp="" module="" eventname=""/>
<event timestamp="" module="" eventname=""/>
<event timestamp="" module="" eventname=""/>
<event timestamp="" module="" eventname=""/>
<event timestamp="" module="" eventname=""/>
<event timestamp="" module="" eventname=""/>
<event timestamp="" module="" eventname=""/>
<event timestamp="" module="" eventname=""/>
<event timestamp="" module="" eventname=""/>
<event timestamp="" module="" eventname=""/>
<event timestamp="" module="" eventname=""/>
<event timestamp="" module="" eventname=""/>
<event timestamp="" module="" eventname=""/>
<event timestamp="" module="" eventname=""/>
<event timestamp="" module="" eventname=""/>
<event timestamp="" module="" eventname=""/>
<event timestamp="" module="" eventname=""/>
```

Event Log
```
I, [2020-04-04T13:12:00.069104 #32089] INFO -- : Reordered event timestamp= module= eventname= by 1 positions
I, [2020-04-04T13:12:00.069171 #32089] INFO -- : Reordered event timestamp= module= eventname= by 1 positions
I, [2020-04-04T13:12:00.069236 #32089] INFO -- : Reordered event timestamp= module= eventname= by 1 positions
I, [2020-04-04T13:12:00.069319 #32089] INFO -- : Reordered event timestamp= module= eventname= by 1 positions
I, [2020-04-04T13:12:00.069385 #32089] INFO -- : Reordered event timestamp= module= eventname= by 1 positions
I, [2020-04-04T13:12:00.069448 #32089] INFO -- : Reordered event timestamp= module= eventname= by 1 positions
I, [2020-04-04T13:12:00.069511 #32089] INFO -- : Reordered event timestamp= module= eventname= by 1 positions
I, [2020-04-04T13:12:00.069585 #32089] INFO -- : Reordered event timestamp= module= eventname= by 1 positions
I, [2020-04-04T13:12:00.069652 #32089] INFO -- : Reordered event timestamp= module= eventname= by 1 positions
```

**Comment by jesusvaldivia** [comment]
I have a similar problem with events with null parameters #9621

**Comment by kepstin** [comment]
This is unrelated to #9621.

This could only happen if the event list for the recording has events in it, but the events themselves are missing. I'm not sure what could cause it - perhaps the events themselves were never saved into redis? Perhaps they were saved, but have expired (maybe the recording processing didn't happen until a long time after the meeting started?)

Can you provide more information about when the meeting started and ended, and when the recording processing was run?

**Comment by rriscado** [comment]
> maybe the recording processing didn't happen until a long time after the meeting started?

YES

This was a 6 hour class.
We had other classes on the same server, and the processing of that class took place 4 hours after the end. After processing other classes.

**Comment by rriscado** [comment]
@kepstin 

I Get TTL Info in BBB Redis.

6 hours!!!

![image](https://user-images.githubusercontent.com/14829973/82959090-51cfcf00-9f8d-11ea-9df3-c3c5acec7c11.png)

**Comment by rriscado** [comment]
Sorry guys!

We have one script for customize the BBB.
I don't know why, but I changed TTL a long time ago using this script!
