### ISSUE TITLE
How to edit Title Bar of Html5Client

### ISSUE THREAD

**Issue by rohitcoder** [bigbluebutton/bigbluebutton#9665]
After joining any session, we can see a title like "BigBlueButton - MEETING_NAME_HERE".

![Screenshot 2020-05-25 at 2 22 10 AM](https://user-images.githubusercontent.com/17665703/82764745-c0e2e180-9e2e-11ea-9774-31670ffb710e.png)

How, can i remove this one?

**Comment by jibon57** [comment]
Have a look here: http://docs.bigbluebutton.org/2.2/customize.html#change-title-in-the-html5-client

**Comment by rohitcoder** [comment]
Thanks @jibon57 this solved my issue! :)
