### ISSUE TITLE
Installation of bbb-freeswitch-core creates empty file in / (/1)

### ISSUE THREAD

**Issue by ichdasich** [bigbluebutton/bigbluebutton#9666]
**Describe the bug**
The installation of bbb-freeswitch-core leads to an empty file, /1, on the FS root. 

**Cause**
Lines 297 and 301 in postinst for bbb-freeswitch-core both read:  
`      if xmlstarlet sel -t -v '//param[@name="ws-binding"]/@value' $SOURCE > /dev/null 2>1; then`  
This redirects STDERR to ./1, which is / during the installation. Instead, they should read:  
`      if xmlstarlet sel -t -v '//param[@name="ws-binding"]/@value' $SOURCE > /dev/null 2>&1; then`  
To redirect to STDOUT.

**Additional Context**
This just got me panting quite a lot as I was fearing a compromise... -.-'

**Comment by ffdixon** [comment]
Thanks!  We'll have this fixed in 2.2.15.
