### ISSUE TITLE
Video/webcam goes blank for users

### ISSUE THREAD

**Issue by vinaypri** [bigbluebutton/bigbluebutton#9669]
We are using BBB on a 4CPU/8GB server for upto 50 users with 2-3 users sharing webcam at a time. However viewers often complain that the webcam portion goes blank for them after a while and never seems to come back. Refreshing the browser (essentially rejoining the session) sometimes helps. The server and memory parameters are all fine and some users can still see the camera, which means the sender's cam is working fine then. Any suggestions?

**Comment by basisbit** [comment]
Sorry, but this issue tracker here is only for BigBlueButton software development related issues. Please use this mailing list / forum for your support request: https://groups.google.com/forum/#!forum/bigbluebutton-setup
