### ISSUE TITLE
Trying to develop live stream support for BBB.  Trying to understand the right approach.

### ISSUE THREAD

**Issue by esafwan** [bigbluebutton/bigbluebutton#9670]
**Is your feature request related to a problem? Please describe.**
I have been using BBB for the last 3 months and extensively helping COVID affected schools to get back on foot with the help of support provided by DigitalOcean. However, many institutions are having the need to broadcast their class to larger audience and don't really need much interaction from students. 

**Describe the solution you'd like**
I have decided to contribute a solution to solve this and make it available in the public domain. I wish to do it by following the great standard BBB has followed till date. If possible, it would be great to see it as a core feature or a module of BBB in the near future.

**I am trying to understand the following:**

1. Is there a standard way or method we should follow when extending BBB?
2. Is there any effort already in progress?

**Two methods I am exploring.** 

1. Figure out a way to get the video, audio & whiteboard stream from the server and then mix it with something like FFmpeg and create an RTMP stream. 
2. Use a headless chrome and join the call. And the use, something like `chrome.tabCapture` to capture the screen frames and the get audio from the audio bridge. 

I have not progressed beyond the research I am doing.  I tried joining the developer group a few times but never got approval.

**Comment by basisbit** [comment]
you might want to take a look at https://github.com/aau-zid/BigBlueButton-liveStreaming and https://github.com/bigbluebutton/bigbluebutton/issues/8295

Regarding the Google forum/mailing list: you have to provide a good reason in the signup form. Any join request without a reason will be declined to reduce amount of automated spam.

**Comment by esafwan** [comment]
Thanks, I got into the forum. I think it was some temp issue. Thanks for the link.
