### ISSUE TITLE
Webcam anomaly - Suggestions appreciated

### ISSUE THREAD

**Issue by Faraglioni** [bigbluebutton/bigbluebutton#9675]
Seeking suggestions to resolve the following webcam/server anomaly:

**i)**  from computer X to server A - webcam Y works
**ii)** from computer V to server A - webcam Y doesn't work _Media could not reach the server (error 1020)_
**iii)** from computer X to server B - webcam Y works
**iv)** from computer V to server B - webcam Y works

N.B.  all setups are using the same internet connection/WiFi router

Consequently:
- server A has been set up correctly as the webcam can access it from at least 1 computer
- webcam is functional as it works on both servers in _some_ situations
- both computers and webcam are working on server B
- Only one of two computers is working with webcam on server A

Question:
Why is the webcam not working with server A in situation **ii**?

Thanks for any help on this. I'm stumped.

**Comment by basisbit** [comment]
This issue tracker here is not for support requests, but instead only for development of the BigBlueButton project itself.
To get support, please ask at https://groups.google.com/forum/#!forum/bigbluebutton-setup

Regarding your problem, check if there is any special firewall software /configuration on that client. Maybe use https://test.webrtc.org/
