### ISSUE TITLE
Invalid Conference code when dialing throgh sip.

### ISSUE THREAD

**Issue by manish-yadav** [bigbluebutton/bigbluebutton#9677]
BBB server hosted in DMZ Zone along with the Asterix server. BBB server configured as per DMZ zone with one to one natting.  

Case -1: BBB server configured on private L3 network freeswitch local and external IP same. SIP trunk server is also on L3 Network, its  working and user could join call using SIP phone.

**BUG:** 
 Case: 2: BBB server configured in DMZ network, freeswitch local ip and external ip different. Asterix server  running on same dmz network.   able to join thrigh web but not able to join the room using sip phone.  error msg "Join code invalid".

**Success Log :** 5b6d7242-9181-4ecd-b1a8-abf14048b3ff Dialplan: sofia/external/6704@192.168.X.X Action transfer(${pin} XML default)
5b6d7242-9181-4ecd-b1a8-abf14048b3ff EXECUTE [depth=0] sofia/external/6704@192.168.X.X _transfer (28640 XML default)_

**Fail join Log:** : 55992273-8b1c-4e78-8170-8fdb7b8dd69a Dialplan: sofia/external/6704@100.64.0.1 Action transfer(${pin} XML default)
55992273-8b1c-4e78-8170-8fdb7b8dd69a EXECUTE [depth=0] sofia/external/6704@100.64.0.1 _transfer( XML default)_

Observation:  join pin missing in faillog

**Comment by manish-yadav** [comment]
its bug with SIP server and BBB server in same DMZ zone.

**Comment by zarip0v** [comment]
> its bug with SIP server and BBB server in same DMZ zone.

Hi there,

I have the same bug, but my SIP server is external. Freeswitch local ip and external ip are different too.

Any suggestions how to deal with it?

Thanks

**Comment by matiasilva** [comment]
Hi @zarip0v, you're probably best asking for support in https://groups.google.com/forum/#!forum/bigbluebutton-setup
