### ISSUE TITLE
Rotate FreeSWITCH logs for every start

### ISSUE THREAD

**Issue by paulmenzel** [bigbluebutton/bigbluebutton#9678]
To avoid misleading output of `  sudo bbb-conf --check`, similar to https://github.com/bigbluebutton/bigbluebutton/issues/4595, instead of weekly rotating the logs, it’d be great to rotate the logs additionally for each FreeSWITCH start.

**Comment by matiasilva** [comment]
This is something that can be configured on your side as not all may want this option. If you have managed to solve a pesky bug, you can run `sudo bbb-conf --clean` to clear out existing logs. Please close this issue.

**Comment by paulmenzel** [comment]
Yes, I can configure logrotate myself.

The main problem is, that it’s not clear, why you check delete all log files, as the user may want to keep them. Users expect, that `bbb-conf --check` would only somehow check the currently running configuration.

**Comment by matiasilva** [comment]
Ah I see. So from your experience `bbb-conf --check` checks all previous logs? I believe this is valuable to most and in this case I would recommend backing up the log files elsewhere and then running clean. Thanks for following up.
