### ISSUE TITLE
Shortcut for muting the microphone not working (Debian, Firefox)

### ISSUE THREAD

**Issue by flipreverse** [bigbluebutton/bigbluebutton#9679]
**Describe the bug**
Shortcut for muting the microphone (Shift+Alt+M) does not work.

**To Reproduce**
Press Shift+Alt+M in a running session.
*edit* Audio-related shortcuts do not work. Shift+Alt+J/L for entering/leaving the audio conference do not work either.

**Expected behavior**
Expecting the microphone to be muted.

**Actual behavior**
Nothing happens.

**BBB version (optional):**
BigBlueButton Server 2.2.14 (1964)

**Desktop (please complete the following information):**
 - OS: Debian Sid
 - Browser Firefox
 - Version 76.0.1

**Additional information:**
Other shortcuts, e.g., Shift+Alt+P (-> toogle public chat), work.

**Comment by schirmeier** [comment]
Same on Ubuntu 20.04, Google Chrome 83.0.4103.61-1: Shortcut Alt-M doesn't mute/unmute anymore.

**Comment by antobinary** [comment]
Addressed in #9683 
Should be rolled out with BBB 2.2.14
