### ISSUE TITLE
lockSettingsHideUserList in API

### ISSUE THREAD

**Issue by amguirado73** [bigbluebutton/bigbluebutton#9682]
Hi,

We are designing types of rooms for our users. We are interested in lockSettingsHideUserList option for a type of rooms. Now this option is not allowed by API and it is global for server. Is very difficult to add this option to API to be used when room is created?.

Thanks

**Comment by Erika31** [comment]
Are you sure it is not allowed by the API ?
I agree that the docs does not mention it , but I believe you can use it...

**Comment by amguirado73** [comment]
Hello,

I confirm you that it works at least in version 2.2.14.

Thank you.
Regards.
