### ISSUE TITLE
What is location for uploaded pdf / pptx files for each meetings?

### ISSUE THREAD

**Issue by rohitcoder** [bigbluebutton/bigbluebutton#9684]
I want to grab all uploaded pdf / pptx from BBB server to my s3 programmatically using python script.

I just want to know, what is the location for each uploaded / converted documents in BBB server?

Thanks for thi awesome open source tool!

**Comment by jfsiebel** [comment]
Good morning @rohitcoder,

you can access the meetings recordings in `/var/bigbluebutton`.

**Comment by rohitcoder** [comment]
@jfsiebel ,

But this folder doesn't contains any pdf/pptx files.

Can you please tell me where uploaded pdf/pptx are uploaded.

**Comment by antobinary** [comment]
@rohitcoder This is not an issue. The right place for developers questions is the forums: https://groups.google.com/forum/#!forum/bigbluebutton-dev

Additionally, it's best to show what you have tried when asking for help - did you upload a file and then use `mlocate` command to find it in the system? Did you look through the directory @jfsiebel pointed out?
