### ISSUE TITLE
Cant promote to moderator

### ISSUE THREAD

**Issue by agustinmono** [bigbluebutton/bigbluebutton#9689]
Sometimes I cant promote to moderator
I really dont know why
http://prntscr.com/so5je0

**The server specs:**

`BigBlueButton Server 2.2.11 (1928)
                    Kernel version: 4.4.0-179-generic
                      Distribution: Ubuntu 16.04.6 LTS (64-bit)
                            Memory: 6110 MB
                         CPU cores: 4

/usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties (bbb-web)
       bigbluebutton.web.serverURL: https://domain.com
                defaultGuestPolicy: ALWAYS_ACCEPT
                 svgImagesRequired: true

/etc/nginx/sites-available/bigbluebutton (nginx)
                       server name: domain.com
                              port: 80, [::]:80
                              port: 443 ssl
                    bbb-client dir: /var/www/bigbluebutton

/var/www/bigbluebutton/client/conf/config.xml (bbb-client)
                Port test (tunnel): rtmp://domain.com
                              red5: domain.com
              useWebrtcIfAvailable: true

/opt/freeswitch/etc/freeswitch/vars.xml (FreeSWITCH)
                       local_ip_v4: External-IP
                   external_rtp_ip: External-IP
                   external_sip_ip: External-IP

/opt/freeswitch/etc/freeswitch/sip_profiles/external.xml (FreeSWITCH)
                        ext-rtp-ip: $${local_ip_v4}
                        ext-sip-ip: $${local_ip_v4}
                        ws-binding: :5066
                       wss-binding: External-IP:7443

/usr/local/bigbluebutton/core/scripts/bigbluebutton.yml (record and playback)
                     playback_host: domain.com
                 playback_protocol: https
                            ffmpeg: 4.2.2-1bbb1~ubuntu16.04

/etc/bigbluebutton/nginx/sip.nginx (sip.nginx)
                        proxy_pass: External-IP

/usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml (Kurento SFU)
                        kurento.ip: External-IP
                       kurento.url: ws://127.0.0.1:8888/kurento
                    kurento.sip_ip: External-IP
                    localIpAddress: External-IP
               recordScreenSharing: true
                     recordWebcams: true
                  codec_video_main: VP8
               codec_video_content: VP8

/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml (HTML5 client)
                             build: 910
                        kurentoUrl: wss://domain.com/bbb-webrtc-sfu
                  enableListenOnly: true

# Potential problems described below`

Im using Greenlight to acces if it matters..

Thanks!

**Comment by pedrobmarin** [comment]
Hi @agustinmono . We have been talking about this for a while now. As far as it goes, guests can't be promoted and that's the correct behaviour. If you could verify, are guests the only participants that can't be promoted at the issue you described? There is already an UI fix for that at newer versions of BBB.

**Comment by agustinmono** [comment]
So it means that if the person wants to be promoted he needs to be registered?
If its like that would be great to display a message like "Guests cant be promoted".

Thanks a lot

**Comment by pedrobmarin** [comment]
Yeah, this is something we are trying to improve right now

**Comment by agustinmono** [comment]
I tried to promote a registered user, but when it joins the session its labeled as Guest too.
Any reason why? He has "User" rol, and the room have the waiting room enable

Thanks a lot

**Comment by pedrobmarin** [comment]
The only reason I see him to be labeled as guest is if the join url he's using to get in is added the guest=true param.

**Comment by agustinmono** [comment]
The join URL is generated by Greenlight , can I set it to False?

**Comment by pedrobmarin** [comment]
I see. At the moment Greenlight includes guest=true for every viewer in a ASK_MODERATOR room and you should avoid passing the guest param if it's value is false (some different issues may occur). I believe this will be modified for the next Greenlight release

**Comment by matiasilva** [comment]
Seeing as this has been resolved, please close this issue.
