### ISSUE TITLE
User doesn't connect to audio when he doesnt have microphone on listenOnlyMode=false

### ISSUE THREAD

**Issue by emadbagheri96** [bigbluebutton/bigbluebutton#9694]
Hello
When you change the file `/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml` and `listenOnlyMode` from `true` to `false`, on systems which they don't have any microphone (Mostly PCs without mics) it can't  connect to the audio to listen to others.
Should we give up on `listenOnlyMode=false` for these users or instead of just having microphone enabled and having `listenOnlyMode=false` can we have them connected to microphone as default without any interaction on entrance to the room and then connect to headphone mode and listen only for users which don't have microphone

**BBB version:**
BigBlueButton Server 2.2.14
HTML Client v925

Tested with different browsers

**Comment by antobinary** [comment]
Hi @emadbagheri96 

`listenOnlyMode` actually means whether to *allow* listenOnly. To force it there is a different parameter. Try this set of values:

```
    autoJoin: true
    listenOnlyMode: true
    forceListenOnly: true
    skipCheck: true
```

and make sure to restart BBB so the new values take effect

**Comment by emadbagheri96** [comment]
> 
> 
> Hi @emadbagheri96
> 
> `listenOnlyMode` actually means whether to _allow_ listenOnly. To force it there is a different parameter. Try this set of values:
> 
> ```
>     autoJoin: true
>     listenOnlyMode: true
>     forceListenOnly: true
>     skipCheck: true
> ```
> 
> and make sure to restart BBB so the new values take effect

Hi @antobinary , Thank you for your reply
I tested what you suggested and that is kinda opposite of what i want. 
When i use `forceListenOnly: true` viewers force to the headphone on entrance and they can't connect to microphone any more.
I understood my misunderstanding about `listenOnlyMode`, but what I wanted is to force the viewer to **get connected with microphone on entrance**. I'm kinda requesting 'forceMicrophone` option.
Is there any way to do that with current options?

**Comment by antobinary** [comment]
Try the following:

```
    autoJoin: true
    listenOnlyMode: false
    forceListenOnly: false
    skipCheck: true
```

**Comment by emadbagheri96** [comment]
> 
> 
> Try the following:
> 
> ```
>     autoJoin: true
>     listenOnlyMode: false
>     forceListenOnly: false
>     skipCheck: true
> ```

now we are back to my first post :)
it works fine for most of the times but for users like those whom connect with pc and have no mic cannot listen to any voice either.

**Comment by ankushnayak** [comment]
Same issue here. With the following settings:
```
    autoJoin: true
    listenOnlyMode: false
    forceListenOnly: false
    skipCheck: true
```
and if the user logs in from a PC that does not have a microphone connected (or a built-in microphone), then they cannot hear audio as well. A fallback to Listen Only when there is no microphone detected would be great. It is weird explaining to users that they cannot hear audio if they do not have a microphone (which should only depend ideally on the user having a speaker/headphone).

**Comment by halilb** [comment]
We are experiencing a similar problem with BBB 2.4.2. We want our users to join with their microphone to the meeting by default so setting `listenOnlyMode: false`. But we still would like to let users without a microphone listen to the meeting.

I guess a solution could be having users join the meeting with `listenOnly` mode by default and asking for their microphone permission later. This way they could at least participate to the meeting by listening even if they don't have a microphone.

Is there a way to support this flow @antobinary? I'd like to try contributing if there isn't a way to do this and you think this is a feature worth considering.
