### ISSUE TITLE
Joining BBB session with mobile phones is very instable

### ISSUE THREAD

**Issue by florisvt** [bigbluebutton/bigbluebutton#9695]
Hello,
We've experienced problems when people use our BBB server with their mobile phones. Yesterday we tested it with 40 users. Some on their laptops  and pc's and some on their mobile phones. The CPU on some of the laptops was very high (i read another issue about that on this github). I think its because of that that the mobile users have problems to stay in the conference because their mobiles could not process all that CPU. Only mobile users with the newest phones with good hardwarespecs are able to stay in the conference.

In a smaller test we tested with only laptops and pc's: a very stable conference. When we test it with only mobile users it gets more instable (with in most cases broken audio or very noisy cracky audio). 

Our server had 1 gig guaranteed bandwith, 128 gb Ram, 32 cores

Tips/help would be appreciated

**Comment by antobinary** [comment]
Did you use any webcams? On mobile device I make sure to use the Settings ->Data savings  and disable webcams usage.

**Comment by florisvt** [comment]
Hi, thanks for your reply! But when webcam usage is disabled on the device the participant isnt able to share his face with the other people in the conference?

**Comment by basisbit** [comment]
Please see this documentation for how to reduce video bitrate - that will help a lot especially with mobile devices which tend to have bad network connection, weak CPU and no VP8 hardware acceleration: https://docs.bigbluebutton.org/2.2/customize.html#reduce-bandwidth-for-webcams

**Comment by matiasilva** [comment]
Please close this issue or further your request at https://groups.google.com/forum/#!forum/bigbluebutton-users

**Comment by basisbit** [comment]
@matasilva I also considered closing this issue, but looking at the issue report in general, it is an actual problem which is not solved yet for most typical bbb setups.
This can maybe be closed when bbb 2.3 is released and the update events for user list, whiteboard and chat are handled better?

It would also be nice to automatically adjust a maximum webcam quality depending on amount of session participants - but that should probably be tracked as a separate issue.

**Comment by matiasilva** [comment]
Good point. I guess my goal was to move this from "help, I can't do this" to a concrete feature request that devs can work on.
