### ISSUE TITLE
Allow sorting by Status in Server room view

### ISSUE THREAD

**Issue by toehold** [bigbluebutton/bigbluebutton#9696]
Hi,

**Is your feature request related to a problem? Please describe.**
Cannot sort the room session by Status. It would help to see which room is running.

**Describe the solution you'd like**
It is already possible to sort by Name, Owner and ID

Thanks a lot

**Comment by mabras** [comment]
Are you in wrong repo? This part of Greenlight and fixed here:
https://github.com/bigbluebutton/greenlight/issues/1147

**Comment by toehold** [comment]
Yes, sorry, got confused! You can close the issue.

Thanks a lot!
