### ISSUE TITLE
How can i share screen as attendee in bigbluebutton

### ISSUE THREAD

**Issue by dharmendravirasat** [bigbluebutton/bigbluebutton#9697]
How can i share the screen as an attendee in bigbluebutton.
I know that we have this feature screen share as Moderators.
but, want to access screen share as an attendee.

it's possible?
plz reply

**Comment by jfsiebel** [comment]
Good morning @dharmendravirasat,

only presenters can share they screen, at the moment the only option available is to make attendee presenter.

**Comment by dharmendravirasat** [comment]
solved
we have option for assign modirator roles
![image](https://user-images.githubusercontent.com/44469219/83136220-bbbeb480-a104-11ea-8ebd-61b6abd59aa7.png)
