### ISSUE TITLE
Show link "Change audio device" in echo test window

### ISSUE THREAD

**Issue by Sea444** [bigbluebutton/bigbluebutton#9698]
**Is your feature request related to a problem? Please describe.**
Today often several audio devices are conncted to a computer (internal microphone, internal speakers, external webcam with microphone and speakers, headset,...). BBB participants don't know how to chose the right device. It's noch clear, that you have to klick "no" in echo test to get the possibility to select another device.

At the moment:
![grafik](https://user-images.githubusercontent.com/63501663/83013022-98b8d580-a01c-11ea-87c0-7fb2362bf196.png)

**Describe the solution you'd like**
Simply add a text ligne "Change audio device" in echo test window. Same target as "no"-Button

![grafik](https://user-images.githubusercontent.com/63501663/83013634-a1f67200-a01d-11ea-9050-7b123d0a0db7.png)

**Describe alternatives you've considered**
Later audio device option could be integrated in normal BBB-frontend, so that device can easily changed.

**Comment by Sea444** [comment]
related to #9184 and #9090

**Comment by matiasilva** [comment]
This already exists if you click the "Nein" option. By default the echo test picks a microphone and sees if that works. I don't see a need for having this option be more explicit when the first microphone works.

**Comment by Sea444** [comment]
Neither my colleagues nor my friends came up with the idea that you have to click "No" in the echo test to select a different audio device (e.g. headset instead of built-in notebook microphone). This is absolutely not intuitive. 
I have experienced it several times that participants in BBB-conferences had a headset on their head, but the sound obviously didn't go through the headset because of echo effects. This creates a bad user experience and motivates participants of such conferences to switch to other tools (MS teams, zoom, ...).

I really think that the echo test interface needs to be reworked. Ideally, as with the webcam, the audio device should be directly selectable via the echo test interface - without having to click "No" first.

My suggestion with the note in this issue was only intended as a quick temporary solution.

**Comment by matiasilva** [comment]
Yes, absolutely. I do fear that if we include those options, less tech-savvy users might get confused. Tools like you mentioned usually select the default system microphone and speaker, and this is the default behavior of the HTML5 client. In the cases you mentioned above, perhaps it would be useful to show some sort of variable volume component that changed as you spoke, to show the user their microphone worked. If you suggest what you would like to see out of the echo test, it is easier for myself and others to begin implementing this.

**Comment by debuglevel** [comment]
As @Sea444 suggested, it could just be as it is already implemented for webcams:

If you want to enable a webcam, BBB let's you choose which one:
![image](https://user-images.githubusercontent.com/2401265/85174481-c4bf2380-b275-11ea-93db-68adf8c58f68.png)

So maybe, if you want to enable a microphone, BBB could let you chose, which one:
![image](https://user-images.githubusercontent.com/2401265/85174697-297a7e00-b276-11ea-81c8-15d9be592b1c.png)

**Comment by rasos** [comment]
Change wording form "No" to "No, try to change mic input?"

**Comment by rasos** [comment]
We also need to consider those who have switched off echo testing completely, which we did on all BBB servers as it is annoying to frequent users. 

I suggest to add a small button to the audio selection dialog window both at the first dialog "How do you want to attend" below the "With microphone" button and on the echo test dialog window.

**Comment by raptorblue** [comment]
Hi,

I totally agree. We need a more obvious way the change the audio devices. I've just had a call where the other person could hear herself via the notebook speakers and therefore clicked on green. It was not clear to her that she has to click on "No, I don't hear myself" despite hearing herself.

As I have seen, Jitsi even allows changing the audio devices during a running call, so does Zoom. From my point of view having this in BBB as well would be a major boost in user experience!

Best regards,
Raptor

**Comment by svilenkov** [comment]
Also if you use a virtual microphone devices (like with special audio noise cancelling tools), it's very annoying to always have to `(wait for the echo) -> (click No) -> (change the device) -> (wait for another echo test) -> (click Yes) -> (talk)`. 

After I've made a selection once, usually I use the same audio I/O device selection in every conference. And waiting echo test only to be able to select a non-default audio input device, is a complete PITA.

So this ability to choose, and hopefully can be stored in the browser storage as preference, would reduce repetitive steps like this:
**from:**
`(echo test) -> (click No) -> (change device) -> (echo test) -> (click Yes) -> (talk)`.
**to:**
`(talk)`

**Comment by peter-lernyx** [comment]
I have been working with BBB for hundreds of hours now and it never occured to me that I could change the audio input via the thumbs down button. Maybe that is because we have echo test disabled altogether as it drives heavy users crazy. Every other VC system that I use has an option to change input-output devices mid session from the main user interface and that is what people expect. So I am getting complaints literally in every single session about that feature missing. BBB needs a dropdown for selecting audio inputs and outputs mid-session like it is the industry standard now.

![image](https://user-images.githubusercontent.com/75390480/121679442-9ce55300-cab8-11eb-8634-b67254c02c1e.png)

**Comment by uka-support** [comment]
Have you tried BBB 2.3?

When I click on the phone symbol I get this:
![image](https://user-images.githubusercontent.com/6216577/121720974-0464c800-cae4-11eb-833e-6f036e33aec9.png)
(of course, it's not obvious that one can do that). I didn't try with echo test disabled.

**Comment by peter-lernyx** [comment]
Oh well, that's how one makes oneself look like a complete idiot, doesn't one? It checked and was told that we are not yet on 2.3 and that that migration is scheduled for the summer slow. Excellent news though, real progress, a bit un-obvious maybe, but functional, that's the main thing. Kudos to the development team, BBB just got a lot better.

**Comment by ffdixon** [comment]
No worries Peter!  We appreciate the feedback and you'll see us iterating on the pop-up audio selector (making it a bit more obvious it's a menu) in subsequent updates.
