### ISSUE TITLE
is there any way to get user join and leave callbacks?

### ISSUE THREAD

**Issue by sijuthankachan** [bigbluebutton/bigbluebutton#9700]
Once meeting starts, is there any way to get a callback for user(attendees) join and leave event. or can i query from mongo DB

**Comment by jibon57** [comment]
You can have a look webhooks from here: http://docs.bigbluebutton.org/dev/webhooks.html

This issue tracker here is not for support issues. Please instead ask your support questions at the mailing lists / forum at https://groups.google.com/forum/#!forum/bigbluebutton-setup

**Comment by basisbit** [comment]
Thank you @jibon57 for answering this question!

**Comment by sijuthankachan** [comment]
Thanks @jibon57
