### ISSUE TITLE
Easier keyboard shortcuts

### ISSUE THREAD

**Issue by GabZach** [bigbluebutton/bigbluebutton#9703]
BBB has keyboard shortcuts for many actions, which is good.

However, the key combinations are not good. In a video meeting, you don't have a lot of time.
So, first of all, you don't have time to look up the shortcut.
Second, they are cumbersome to produce.

So, there are a number of solutions to address this.

First of all, make very simple keyboard shortcuts; other video tools just use the key "m" for mute/unmute, for instance. That's something you can remember and hit very easily.

Second, make button that pops up a quick help showing the keyboard shortcuts.
(Right now, yo need a number of mouse clicks to bring it up and dismiss it.)

Third, make the shortcuts configurable, ideally by the users themselves.

**Comment by antobinary** [comment]
Hi @GabZach ,

The current shortcuts were selected so they do not conflict with browser / screen reader shortcuts.
Also, since this is an open source project, you can change them in your deployment (see settings.yml in bigbluebutton-html5/private/config)

**Comment by antobinary** [comment]
See https://github.com/bigbluebutton/bigbluebutton/pull/9114#pullrequestreview-401954651 for example of reserved keys

**Comment by GabZach** [comment]
> The current shortcuts were selected so they do not conflict with browser / screen reader shortcuts.

Yes, but I think none of the standard browsers uses "m" for a shortcut.
and I'd like to have more single-key shortcuts, e.g., "c" for camera on/off.

> Also, since this is an open source project, you can change them in your deployment (see settings.yml in bigbluebutton-html5/private/config)

Thanks. Is there documentation about the format of the file? It is not obvious to me.
For instance, I found the lines
```
      toggleMute:
        accesskey: M
        descId: toggleMute
```
which seems to be exactly what I want.
However, I doubt this is it, because in our installation, the keyboard shortcut is CTRL-OPTION-M.
But I would like to change it to just "M".

**Comment by KDSBrowne** [comment]
@GabZach, 

None of the browsers may use "m" for a shortcut but the screen readers do.
NVDA (Non-Visual Desktop Access) uses "M" for Next Frame and "C" for Next combo box.

The shortcuts in the client are provided using the `accessKey` property. https://www.w3schools.com/tags/att_global_accesskey.asp.
This doesn't support the ability to omit or change the modifier used with the accessKey values in the settings.yml.

**Comment by GabZach** [comment]
I see.  Is there a stand-alone app of BBB? (I'd prefer that in any case)

**Comment by matiasilva** [comment]
Chiming in here to say that you can specify keyboard shortcuts to the HTML5 client via the API request on `join` via the `userdata-bbb_shortcuts=` parameter. Note that it has to be URL encoded. You can also view all of the existing shortcuts in the `settings.yml` file located in `/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml`.

There is no standalone app of the BBB client. That would make little sense when the whole philosophy of the HTML5 client was to standardize and make the platform equal across all devices.

**Comment by GabZach** [comment]
> Chiming in here to say that you can specify keyboard shortcuts to the HTML5 client via the API request on join via the userdata-bbb_shortcuts= parameter. Note that it has to be URL encoded. 
> 

It would be cool if that could be done in a user-friendly manner.

**Comment by matiasilva** [comment]
It sounds like a very niche feature, most are fine with the current shortcuts. Something that those who want to do this, develop and customize their own version of the HTML5 client.

**Comment by GabZach** [comment]
> It sounds like a very niche feature, most are fine with the current shortcuts.
> 

With all due respect, I doubt that.  How do you know that "most are fine"?
How many people actually know what the shortcuts are?

**Comment by matiasilva** [comment]
That's fair. Perhaps what I meant to say was that this is not an issue that warrants full integration into the HTML5 client, to the point where an interface is developed for people to create their own shortcuts. My observation that "most are fine" stems from the fact that this issue hasn't been raised very frequently neither here nor in the Google groups. 

>How many people actually know what the shortcuts are?

The shortcuts are easily accessible via the settings drop-down in the client.

**Comment by rasos** [comment]
Where can I change the modifier of the shortcut keys. At our installation it is `Alt-Shift`, so all shortcuts need to be pushed with three fingers. We would like to test with `Shift` only.

**Comment by hex-m** [comment]
There are some very commonly used features that are not available via shortcuts. e.g. toggle mute, toggle video, push-to-talk, raise hand, toggle full-screen.

Here is a comparison of the default shortcuts of BigBlueButton and Jitsi Meet.
![Screenshot from 2020-08-26 11-19-10](https://user-images.githubusercontent.com/16013327/91286688-0b0d9300-e78f-11ea-9ddd-b7916446850f.png)![Screenshot from 2020-08-26 11-18-08](https://user-images.githubusercontent.com/16013327/91286707-11037400-e78f-11ea-89e1-2d3589a1275b.png)

**Comment by matiasilva** [comment]
@hex-m:

> There are some very commonly used features that are not available via shortcuts. e.g. toggle mute, toggle video, push-to-talk, raise hand, toggle full-screen.

The screenshot you attached has toggle mute. There's a PR for push-to-talk (#9114). I believe the reason shortcuts are as they are is in that PR as well, there are some concerns with screenreaders and keys used by them.

**Comment by Jan-Weigang** [comment]
I would just like to chime in, firstly just to add my voice as not being entirely happy with the shortcuts.

Secondly: One of the reasons of not complaining about the hotkeys/shortcuts until now, for me at least, is that they are completely useless to me. Don't get me wrong I would love to use them. But as this all runs in browser and the browser (and the tab with the video conference specifically) is almost never active, I have to switch programs/tabs/screens anyway and might as well use a mouse click.
So if not making them completely client-changeable then having them global (or a way to access them globally) would be highly beneficial. The rest could be done by client software like autohotkey.

**Comment by sIm0ny** [comment]
> Hi @GabZach ,
> 
> The current shortcuts were selected so they do not conflict with browser / screen reader shortcuts.
> Also, since this is an open source project, you can change them in your deployment (see settings.yml in bigbluebutton-html5/private/config)

Hello I am new at GitHub and in Coding how do I open the settings.yml? Do I need to download something?
Thanks for Answers

**Comment by sIm0ny** [comment]
> Hi @GabZach ,
> 
> The current shortcuts were selected so they do not conflict with browser / screen reader shortcuts.
> Also, since this is an open source project, you can change them in your deployment (see settings.yml in bigbluebutton-html5/private/config)

Hi
I found now the Code settings.yml but how can i change them that its saved when I use BigBlueButton for School

**Comment by antobinary** [comment]
There has been some development on the shortcuts area: https://github.com/bigbluebutton/bigbluebutton/pull/15473 - this is the latest afaik. Other than that I believe the comment above stating the restrictions we had is still valid. The comment with how to override it on your depoyment (not as an end user), also appears to be up to date.
