### ISSUE TITLE
private chat messages displayed in the room chat

### ISSUE THREAD

**Issue by andreaappendino** [bigbluebutton/bigbluebutton#9704]
**Describe the bug**

private chat messages, sent to a user which has joined with two browser and has closed one of them, are displayed in the main chat.

**To Reproduce**

1.  join an existing room with a user
2.  join the same room with the same user in another browser, now the user is listed twice in the users list (pic 1)
3. close one of the two browsers, now the name is displayed once in the users list
4. with the moderator of the room, send a private message to the test user (pic 2)
5. the private message is displayed in the main chat (pic 3)

**BBB version (optional):**
2.2.10
**Desktop (please complete the following information):**
 any 

![1](https://user-images.githubusercontent.com/65360254/83149989-0e936e80-a0fb-11ea-8083-946d04ce2b12.PNG)
![2](https://user-images.githubusercontent.com/65360254/83149992-0fc49b80-a0fb-11ea-8ec0-cc8ea79cd0fd.PNG)
![3](https://user-images.githubusercontent.com/65360254/83149993-0fc49b80-a0fb-11ea-9cd9-83cb1cad6eb6.PNG)

**Comment by antobinary** [comment]
Hi @andreaappendino 
Are you able to reproduce this on test.bigbluebutton.org? This might be related to a regression which was fixed in the next minor version. You can currently update your server to BigBlueButton v2.2.14

**Comment by andreaappendino** [comment]
> Hi @andreaappendino
> Are you able to reproduce this on test.bigbluebutton.org? This might be related to a regression which was fixed in the next minor version. You can currently update your server to BigBlueButton v2.2.14

hello, to reproduce it i need to join the same room with at leat 3 users.
joining the test session brings me to different rooms

**Comment by pedrobmarin** [comment]
I wasn't able to reproduce it in v2.3
