### ISSUE TITLE
Security issue : Good way to detect brute force or stange connections

### ISSUE THREAD

**Issue by aguerson** [bigbluebutton/bigbluebutton#9705]
Hi bbb team,
I search a tool or a such of command to detect brute force or stange connections.
There is so many log, and so many entries inside them.
What is the good way ?
Have you got a tool to trap this ? Could you create something ?
Regards,
Aurélien.

**Comment by jibon57** [comment]
Have a look here: http://docs.bigbluebutton.org/2.2/customize.html#secure-your-system--restrict-access-to-specific-ports

This issue tracker here is not for support issues. Please instead ask your support questions at the mailing lists / forum at https://groups.google.com/forum/#!forum/bigbluebutton-setup

**Comment by GhaziTriki** [comment]
@aguerson It is not possible to find security issues in BigBlueButton without knowing its internal architecture. If you have found anything regarding security we invite you to directly share it in private with one of the core team members.
