### ISSUE TITLE
Audio problem - Multiple opened tabs on mobile phones

### ISSUE THREAD

**Issue by EdwinZuck** [bigbluebutton/bigbluebutton#9707]
The Html5 interface is not practical on mobile phones. Some users open sometimes several tabs on mobile phones for one same meeting. They don't notice that several tabs are opened, and the effect sides are that you have echo problems when someone is speaking.

Is it possible to have only one active tab for one meeting, especially for mobile phones ?

**Comment by pedrobmarin** [comment]
You can try setting https://github.com/bigbluebutton/bigbluebutton/blob/7c9286ef19589b660ec8489e093e783a2c43b238/bigbluebutton-web/grails-app/conf/bigbluebutton.properties#L354 to `false` to avoid the same user to join multiple times.
