### ISSUE TITLE
Audio with bluetooth headset not working properly

### ISSUE THREAD

**Issue by GabZach** [bigbluebutton/bigbluebutton#9712]
I have just had a problem with BBB when using (for the first time) my bluetooth headset.

Platform: MacbookPro, macOS Catalina 10.15.4, Chrome browser 83.0.4103.61
Headset: Bowers and Wilkins P5.
The headset works fine with my MacBook Pro , input and output.

I switched on the headset (Bowers and Wilkins P5) and connected it via the bluetooth top right menu, as usual. The headset responded with the usual audio feedback sound indicating it is connected.

First, the other participants in the BBB room could not hear me, but I could hear them.
Then, I left the room, the others stayed in it, I switched the headset off and on, connected via bluetooth again, joined the BBB room. Then, they could hear me, but I could not hear them.

It seems to me that reliability of BBB with bluetooth headsets should be investigated. (Yes, I know, bluetooth is always a nightmare for developers.)

**Comment by basisbit** [comment]
This issue tracker is only for BBB development issues, not for support requests. Please instead ask your question at https://groups.google.com/forum/#!forum/bigbluebutton-setup and close this issue. Thanks.

Usually the problem with bluetooth speakers is that they by default connect in a mode where the microphone and the speaker can not be used at the same time. You should be able to change this the audio device settings.
