### ISSUE TITLE
IP Log of Users

### ISSUE THREAD

**Issue by lastwall** [bigbluebutton/bigbluebutton#9714]
Hi
Is there any way to check the IP of users joining a meeting? 
we want to check every specific IP of users joining a session and maybe is there any feature to block IP temporary or permanent.
what about Public Chat? is there any log to check users IP chatting there?

**Comment by basisbit** [comment]
Sorry, but this issue tracker is only for BigBlueButton development related issues.
For support questions, please ask at https://groups.google.com/forum/#!forum/bigbluebutton-users or https://groups.google.com/forum/#!forum/bigbluebutton-setup
