### ISSUE TITLE
Keyboard shortcuts broken after updating from 2.2.11 to 2.2.14

### ISSUE THREAD

**Issue by lkiesow** [bigbluebutton/bigbluebutton#9717]
After updating from 2.2.11 to 2.2.14, the keyboard shortcuts in the HTML5 front-end are broken. For example, pressing `<Shift> + <Alt> + M` does not work for muting/unmuting yourself.

*Edit:* Seems like the problem only affects `<Shift> + <Alt> + M`. Other shortcuts still work.

**Comment by antobinary** [comment]
Likely addressed by https://github.com/bigbluebutton/bigbluebutton/pull/9683

**Comment by mabras** [comment]
I can confirm that is working now (`2.2.15`).

**Comment by lkiesow** [comment]
Yep, does fix the problem.
Closing this issue.
