### ISSUE TITLE
Allow users to select microphone mode when microphone is locked instead of autochoose listen only

### ISSUE THREAD

**Issue by cipi1965** [bigbluebutton/bigbluebutton#9719]
**Is your feature request related to a problem? Please describe.**
I think this is easier for users to just be unlocked and unmute instead of disconnecting from call and reconnecting with microphone.

**Describe the solution you'd like**
I think when lockSettingsDisableMic is enabled users should be able to choose microphone mode for subsequent usage.

**Comment by basisbit** [comment]
The disablemic setting is supposed to disable the microphone. No need to change this. What you actually want is to mute people after joining. See here https://docs.bigbluebutton.org/2.2/customize.html#mute-all-users-on-startup

Also, please do not use this development-only issue tracker for support questions.

**Comment by cipi1965** [comment]
If you just set mute after join people can unmute itself, i want to lock it.
Some participants are not computer savy and it's difficult to explain every time they need to disconnect from audio conversation and reconnect with microphone, it would be simpler in the way i explained.

**Comment by Jossef-767** [comment]
True, it is currently creating difficulty for users.
Microphone locking should not disconnect a microphone to connected users,, only prevent unmute from connected users.
An alternative solution would be to not allow unmute when using "mute all users except presentor" from the geer button.
This avoids the need to "lock" microphones,
And will leave the "lock" option only for Webinar sessions, with many users

**Comment by basisbit** [comment]
This imho is a valid bugreport which should be kept open. Jossef-767 explained the problem above.

**Comment by hex-m** [comment]
The stale-bot has a high false-positive rate. :/

**Comment by basisbit** [comment]
![image](https://user-images.githubusercontent.com/10870269/139822891-612d9ae3-10ab-43a9-be25-3e9643620d66.png)

**Comment by cipi1965** [comment]
Probably not required anymore since #14021
