### ISSUE TITLE
Load modules dynamically at run time

### ISSUE THREAD

**Issue by bigbluebutton-issue-import** [bigbluebutton/bigbluebutton#972]
Originally reported on Google Code with ID 217
```
Hi

Is there a way to load components in BBB incrementally? 

In a scenario where I just want to chat with a person and then, if 
necessary, progress to voice/video/desktop conferencing.

If possible, are we allowed to do that, i.e. tweak BBB into an 
incrementally loading modular design to suit our needs?

If yes, any suggestions how to go about it?


Thanks,

```

Reported by `yeleti` on 2009-10-21 05:16:00

**Comment by ffdixon** [comment]
Using the layouts.xml module 

   http://docs.bigbluebutton.org/dev/client-configuration.html#layouts

and dynamic config.xml

   http://docs.bigbluebutton.org/dev/api.html#setconfigxml

a developer can control the features (from config.xml) and the layout (from layouts.xml).
