### ISSUE TITLE
Breakout rooms

### ISSUE THREAD

**Issue by itr001** [bigbluebutton/bigbluebutton#9720]
**Describe the bug**
We disabled breakout rooms. But realized we want them back. We changed the parameter back to true however the breakout rooms are still not available.

/var/www/bigbluebutton/client/conf/config.xml

<breakoutRooms enabled="true" record="false" privateChateEnabled="false"/>

This hasn't allowed us to use breakoutrooms. Is there another location we may have disabled?

**Installation type**
Installed on digitalocean using the instructions on the website.

**Comment by basisbit** [comment]
This issue tracker is only for BBB development issues, not for support requests. Please instead ask your question at https://groups.google.com/forum/#!forum/bigbluebutton-setup and close this issue. Thanks.

**Comment by antobinary** [comment]
I will echo what @basisbit said about bigbluebutton-setup.
Also look for `bigbluebutton.properties` for breakout room settings in 2.0 (I assume that's what you're using, as in the more recent versions of BBB we use HTML5 client, not Flash (config.xml))
