### ISSUE TITLE
More accessible data saving option

### ISSUE THREAD

**Issue by hiroshisuga** [bigbluebutton/bigbluebutton#9721]
Students with poor connection may want to toggle the data-saving options frequently even during the session. 

The current implementation only allows it by pushing 1) the three dot button on upper right, 2) setting button, 3) data saving button, 4) disable webcam button and 5) save the setting, taking 5 steps, which I think too much.

In normal lecture format, I cannot imagine the situation that students switch off the screen share, because the teacher shows something necessary for his lecture there. But it may not be the case for the videos of speakers. Therefore, I would suggest the "disabling webcam video" switch be more accessible. A button on the bottom of the screen would be ideal (see the attachment).

Hiroshi Suga
![data-saving](https://user-images.githubusercontent.com/45039819/83318080-6ac9d000-a26c-11ea-8146-db15cfa1243c.png)

**Comment by simrank0** [comment]
Can i start working on this issue?

**Comment by hiroshisuga** [comment]
I would appreciate if you start working. I assume only toggling the "viewParticipantsWebcams" variable will work.

**Comment by Jossef-767** [comment]
in the old flash client we simply closed each video window by clicking on  x button on each video window frame.
 to re open the video window, a new  menu item can be added to the menu showen when clicking the user name

**Comment by hiroshisuga** [comment]
Hello Jossef-767,

That would be ideal.

However I also think that the right to turn on/off individual video should be left to individuals that broadcast it. For the purpose of saving data, a button to turn off/on all videos would be more useful for the students.  You cannot turn off the videos of e.g. 30 students by clicking X of each small screen.

I still do not find out how to implement this button as I am not familiar with HTML5. Would anyone give us a hint, for instance, which function to be run to turn off all videos?

Hiroshi

**Comment by pedrobmarin** [comment]
After this can we consider this resolved? https://github.com/bigbluebutton/bigbluebutton/pull/11758

**Comment by hiroshisuga** [comment]
@pedrobmarin , absolutely! I am closing the issue.
