### ISSUE TITLE
Change bigbluebutton logo in recording web pages

### ISSUE THREAD

**Issue by mohgh** [bigbluebutton/bigbluebutton#9722]
**Describe the bug**
How can I change BigBlueButton logo in recording web page?

**Screenshots**
![21](https://user-images.githubusercontent.com/8774487/83329506-30c5f180-a29f-11ea-8abe-5b87590bd918.png)

**Comment by basisbit** [comment]
This issue tracker is only for BBB development issues, not for support requests. Please instead ask your question at https://groups.google.com/forum/#!forum/bigbluebutton-setup and close this issue. Thanks.
