### ISSUE TITLE
Time formats in recordings

### ISSUE THREAD

**Issue by daigonstar** [bigbluebutton/bigbluebutton#9727]
I was wondering if there is any way to change the time formats in recordings from mm:ss to hh:mm:ss?

**Comment by pedrobmarin** [comment]
At least in for the playback time format is configured here https://github.com/bigbluebutton/bbb-playback/blob/8cde8e2a3b5bb353e8838f73f4dab79f70f6b95f/src/components/chat/message.js#L68-L75
