### ISSUE TITLE
talking indicator bugs

### ISSUE THREAD

**Issue by daminebenq** [bigbluebutton/bigbluebutton#9731]
the following bugs were found on 2.2.15:

**first bug**
when you click mute and unmute quickly on a talking user even if you are a Presenter, you get removed from the meeting (sometimes it happens)

to reproduce:
1) go to bbb 2.2.15 meeting room with 2 users and enable microphone in one of them
2) when the talking indicator is highlighting, click and spam clicks to mute the other user 
3) the second user gets removed from the meeting (the one who clicked to mute the other talking user gets kicked)
![Peek](https://user-images.githubusercontent.com/5144311/83440667-b2428e80-a41b-11ea-851b-8ff26253cbe7.gif)

**second bug**
if you talk and you see your talking indicator highlighting, if you spam clicks on it, you will mute and unmute yourself many times

to reproduce:
1) go to bbb 2.2.15 meeting room with only one user with microphone enabled
2) when the talking indicator highlights, clicks and spam the talking indicator button to mute/unmute yourself
3) you are muting and unmuting yourself in a way that spams the client and makes it mute you and unmute x times of your clicks
![Peek](https://user-images.githubusercontent.com/5144311/83440095-b91cd180-a41a-11ea-82b2-2bacf8e9b970.gif)

**Comment by basisbit** [comment]
(not entirely sure if this is a bug or a feature, but thanks for reporting anyway!)

**Comment by daminebenq** [comment]
This issue was described again by another user.
The issue is still happening, but closing this issue to avoid having duplications.

**Comment by prlanzarin** [comment]
Related to #11226.

Notice that I don't consider #11226 to be a duplicate of this because there I'm specifically talking about the current state of the debouncing in the talking-indicator, which was introduced to fix this.

**Comment by daminebenq** [comment]
After testing #11230, I wasn't able to reproduce this issue at all.
Closing it.
