### ISSUE TITLE
Animation doesn't work for Microsoft PPT

### ISSUE THREAD

**Issue by rajeekum** [bigbluebutton/bigbluebutton#9734]
**Describe the bug**
When Presentation uploaded as Microsoft PPT, Any Animation incorporated in PPT doesn't work.
For Example: You have 6 bullet points. All shouldn't be visible at once. Each point comes with the click of the mouse.

**To Reproduce**
1. Start Conference
2. Click on upload presentation and select Microsoft ppt format which has animation
3. Observed that Animations are disabled and not working.

**Expected behavior**
With Microsoft PPT - Animation should work as it works in normal presentation

**Actual behavior**
When Presentation uploaded as Microsoft PPT, Any Animation incorporated in PPT doesn't work.

**Screenshots**
NA

**BBB version (optional):**
BIGBLUEBUTTON_RELEASE=2.2.15

**Desktop (please complete the following information):**
 - OS: Ubuntu 16.04
 - Browser: Chrome, Safari. Mozilla

**Smartphone (please complete the following information):**
NA

**Comment by ffdixon** [comment]
When you upload PPT slides, they get converted to PPT(X) -> PDF -> SVG, so all animations get flattended into a single slide.

We're using Libreoffice for the conversion, and, unfortunately, we don't expect to have support for the animations in the above process.

If you really need the animations, we recommend sharing the screen.

**Comment by rajeekum** [comment]
@ffdixon Thanks for your quick reply. with screen share option, I will lose out control on other conferencing features. 
Also it is observed that there is mirroring effect for "screen share" option. Do we have fix for mirror effect or workaround to minimize the visual impact ?

**Comment by basisbit** [comment]
regarding the mirror effect, please see #7183. As long as your teachers/presenters understand why this is happening, it should usually not be a problem. You can also reduce the effect by attaching a second screen and then only sharing that second screen or only sharing a certain application / website.

**Comment by hiroshisuga** [comment]
A decent option is to split an animated PP slide into multiple slide. See 

http://www.maxonthenet.altervista.org/ppsplit.php
or
https://nshi.jp/contents/other/separateAnimation/    (Japanese)

In my experience, these add-ins do not always work correctly, but you can still modify the slides manually afterwards. 

Showing PP screen by screenshare costs a lot of network traffic compared to the normal PDF presentation, as screenshare is almost like broadcasting video. Sometimes the pointer tragically delays. I recommend using screenshare only for supplementary purpose (e.g. when you need to show the Internet browser). 

Hope it helps.

Hiroshi

**Comment by basisbit** [comment]
Sorry, but that these tools you mentioned do not help because
a) imcompatible licensed
b) they require Windows
C) they require a MS Office license

If you find out how to do this fast using LibreOffice, that would be interesting.

**Comment by hiroshisuga** [comment]
Sorry for the confusion. I did not intend to suggest incorporating these tools into BBB (if it's what you mean). What I wanted to say is that as a user, one can still use an animated PP file by splitting the slides using MS Office. 

But your comment is very interesting. I would not be surprised if there is already a similar tool in Libreoffice, which may be incorporated into BBB relatively easily!

Hiroshi

**Comment by hiroshisuga** [comment]
Found:
https://github.com/monperrus/ExpandAnimations

**Comment by rajeekum** [comment]
@hiroshisuga, Are you able to figure out on how to implement this with BigBlueButton ? If you have working patch/code which I can try.

**Comment by hiroshisuga** [comment]
Hi @rajeekum,
Still trying. Need to know how to run a LibreOffice add-ons from the command line. It seems not easy, if not impossible. We may need to translate the add-on into macro, which I need to learn more.

A good news is that this add-on works very well to convert the animated PP file into a PDF with a split animation "on LibreOffice", as long as the animation is simple, just showing and hiding elements.

**Comment by matiasilva** [comment]
Related #2489

**Comment by pavlukivan** [comment]
still relevant
