### ISSUE TITLE
Screen sharing view does not resize properly when sharing webcam

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#9735]
**Describe the bug**
When viewing the presenter's screen sharing, starting a webcam will crop the screen sharing view.

**To Reproduce**
1. Start a session as presenter
2. Share your screen (the aspect ratio is correct)
3. Share your webcam
4. The screen sharing preview is cropped

**Expected behavior**
The screen sharing preview would scale proportionally so you still could see the entire screen.

**Actual behavior**
Tops and bottom of the screen share view are cut off.  This happens for viewers as well -- so they are not seeing the presenter's screen.

**Screenshots**
https://youtu.be/sS4tyNgmxOo

*BBB version (optional):**
BigBlueButton 2.2.15

**Comment by Beiri22** [comment]
I got the same problem; this is not ideal when you have to perform an online examination - video video and screen share.

**Comment by ryprfpryr** [comment]
Hi @ffdixon any update on this? We have lots of affected users because of the latest Chrome release

**Comment by matiasilva** [comment]
Hi @ryprfpryr, note the PR linked above :)

**Comment by prlanzarin** [comment]
Addressed in [2.2.21](https://github.com/bigbluebutton/bigbluebutton/releases/tag/v2.2.21).
