### ISSUE TITLE
Recording with PHP API

### ISSUE THREAD

**Issue by taufardh** [bigbluebutton/bigbluebutton#9736]
Hi,
I have some question about recording feature from API (PHP in my case),
I already create a dashboard for doing all API function available in [bigbluebutton-api-php](https://github.com/bigbluebutton/bigbluebutton-api-php) then I create a room with auto record true like in sample API : 
`if ($isRecordingTrue) {`
`	$createMeetingParams->setRecord(true);`
`	$createMeetingParams->setAllowStartStopRecording(true);`
`	$createMeetingParams->setAutoStartRecording(true);`
`}`
And it's working fine and there is show that the meeting is recording. After I end the meeting and execute get Recording I don't get my record meeting (noRecordings in API response). How I can get all recorded meetings available in my bbb server with API? And there is record-id where I can get that? or that is declared in create meeting process? but I can't find that in [bigbluebutton-api-php](https://github.com/bigbluebutton/bigbluebutton-api-php) for declare record-id parameter...

Thanks

**Comment by jibon57** [comment]
Have a look here: https://github.com/bigbluebutton/bigbluebutton-api-php/blob/master/src/Parameters/GetRecordingsParameters.php

```
$bbb = new BigBlueButton();
$recordingParams = new GetRecordingsParameters();
$recordingParams->setMeetingId($meetingID);
$response = $bbb->getRecordings($recordingParams);
```
You should use forum https://groups.google.com/forum/#!forum/bigbluebutton-dev for asking questions not in issue tracker.

**Comment by GhaziTriki** [comment]
https://groups.google.com/forum/#!forum/bigbluebutton-dev is the right place for the questions.
