### ISSUE TITLE
Allow create a separate room for meetings apart of break out rooms

### ISSUE THREAD

**Issue by ostasevych** [bigbluebutton/bigbluebutton#9739]
By now it is possible to break out a bigger room in smaller ones. In some cases, during the group work, it is necessary to create a new room for negotiations or a special space, where you may invite the participants from broken out rooms. 

Please, add the functionality of manual creation of the room and adding participants to it from broken out rooms.

**Comment by matiasilva** [comment]
You can do this already by clicking on the gear icon. Please close this issue.

**Comment by ostasevych** [comment]
> You can do this already by clicking on the gear icon. Please close this issue.

Would you be so kind to explain, how it works? Eg, when the bigger room is broken out, participants assigned to the rooms, and I would like to add one more room. What should I do?

**Comment by matiasilva** [comment]
Ah I see what you mean. That's not possible at this point and neither do any of the existing platforms offer this. Once you create the rooms, you are limited to the number of rooms you had created. What you can do is keep an empty room or two and then invite participants to hop into those by going to them main room, clicking on the gear icon and then clicking on breakout room invitation.

**Comment by ostasevych** [comment]
> Ah I see what you mean. That's not possible at this point and neither do any of the existing platforms offer this. Once you create the rooms, you are limited to the number of rooms you had created. What you can do is keep an empty room or two and then invite participants to hop into those by going to them main room, clicking on the gear icon and then clicking on breakout room invitation.

Thank you for this hint. So, may I create empty rooms?.. Is that possible?

**Comment by matiasilva** [comment]
Yes, you can. Sorry for the late response. Closing this for now as I believe you have solved the issue.
