### ISSUE TITLE
Let make break out rooms be unlimited in time

### ISSUE THREAD

**Issue by ostasevych** [bigbluebutton/bigbluebutton#9742]
In some cases, there's a need to not limit the break out room in time, especially if the group work intended to last during the whole meeting. By now break out rooms are limited with specifically indicated time when creating them,

Please, add checkbox to the selector of the length of existence of broken rooms "Unlimited" which means till the end and disables the field where you have to indicate the length in minutes. In this case, the break out rooms may be terminated either manually by moderator from the break out rooms menu or the meeting ends.

**Comment by matiasilva** [comment]
Hi. This can already be done by specifying a 0 for the breakout room time. Please close this issue and avoid posting future ones until you are sure that the feature doesn't exist. This discussion belongs on the Google groups.

**Comment by ostasevych** [comment]
Thank you! However, I din't find this information earlier...
