### ISSUE TITLE
Let participants to join other rooms

### ISSUE THREAD

**Issue by ostasevych** [bigbluebutton/bigbluebutton#9743]
In some cases participants may wish to join other break out room or quit existing when they have already selected one. By now only moderator may join other rooms.

Please, add the explicit possibility a participant to quit from the room and join another room.

**Comment by Tainan404** [comment]
Hello @ostasevych, currently in BBB 2.2 we can set the breakout rooms as `Free Join`, it allows users join in another breakout room from the main room.

![Peek 2020-06-02 17-02](https://user-images.githubusercontent.com/15806883/83564564-47fd1d00-a4f3-11ea-89ed-6d84b18aa849.gif)

**Comment by ostasevych** [comment]
> Hello @ostasevych, currently in BBB 2.2 we can set the breakout rooms as `Free Join`, it allows users join in another breakout room from the main room.
> 
> ![Peek 2020-06-02 17-02](https://user-images.githubusercontent.com/15806883/83564564-47fd1d00-a4f3-11ea-89ed-6d84b18aa849.gif)

I mean, after they have already joined some room. So, they may quit one and join another.

**Comment by nplesa** [comment]
Hi guys,

I use the php api for the bigbluebutton and I try to make a camera using a guest policy, usually ASK_MODERATOR

		$createParams = new CreateMeetingParameters($meetingId, $room_name);
		$createParams = $createParams
						->setModeratorPassword($mod_pass)
						->setAttendeePassword($stu_pass)
						->setGuestPassword(getenv("DEFAULT_GUEST_PASSWORD"));
		$createParams->setRecord(true);
		$createParams->setAllowStartStopRecording(true);
		$createParams->setAutoStartRecording(false);
		$createParams->setGuestPolicy("ALWAYS_ACCEPT");

		$response = $bbb->createMeeting($createParams);

The camera is created, response ok, but still no guest policy in xml.
(For this, do you have to recompile everything, or just modify the file or files?)

And i tried to join at this room as guest:
	$joinMeetingParams = new JoinMeetingParameters($meetingID,"JD" , getenv("DEFAULT_GUEST_PASSWORD"));
				$joinMeetingParams->setRedirect(true);
				// $joinMeetingParams->setGuestStatus(true);
				$joinGuestURL = $bbb->getJoinMeetingURL($joinMeetingParams);

If i try open url defined as $joinGuestURL, i have like response:
"You either did not supply a password or the password supplied is neither the attendee or moderator password for this conference."

This means that something is wrong about password.

PS: I see on bigbluebutton github small pats about guest and guest policy..but in php api , still nothing.

Can you help me, any advice?

Thanks in advance,

**Comment by antobinary** [comment]
@nplesa please open a new issue for this to attract the right audience. Do not hijack other people's topics

**Comment by matiasilva** [comment]
Hi. This already exists. You can click on the gear icon during the meeting. Please close this issue and avoid posting feature requests that already exist.
