### ISSUE TITLE
Wrong bbb-common-web bundled in release 2.2.15

### ISSUE THREAD

**Issue by lepokle** [bigbluebutton/bigbluebutton#9745]
**Describe the bug**
It seems like an old version of bbb-common-web is bundled with the latest release 2.2.15. It contains file `bbb-common-web-0.0.1590163241-SNAPSHOT.jar` which, as seen by decompiling, does not contain the fix from #9687 (in addition, my filesystem reports that the file is from May, 22th, which is before the fix was even made).

**To Reproduce**
Install BBB 2.2.15, start a webinar with guest policy ASK_MODERATOR, join an authenticated attendee.

**Expected behavior**
The actual version of bbb-common-web is bundled so that the moderator is asked, if the attendee is allowed to join.

**Actual behavior**
An old version of bbb-commin-web is bundled so the attendee is added to the meeting without confirmation.

**Screenshots**
Screenshot of decompiled code of the bundled artifact. Note the negotation of parameter paramBoolean2 in the if clause in row 358
![image](https://user-images.githubusercontent.com/499823/83570493-70523f00-a526-11ea-9aba-c26b04820bd9.png)

**Desktop (please complete the following information):**
not relevant

**Smartphone (please complete the following information):**
not relevant

**Additional context**
Building bbb-common-web from tag 2.215 and deploying the artifact fixes the issue.

**Comment by ffdixon** [comment]
Your right -- we're working on 2.2.16 release to update this with the correct build of `bbb-common-web`.

**Comment by lepokle** [comment]
Thanks for the quick answer!

**Comment by antobinary** [comment]
https://groups.google.com/forum/#!topic/bigbluebutton-dev/fe0qGFkKi2A

We have corrected this in 2.2.16
