### ISSUE TITLE
Issue upgrading to 2.2.16

### ISSUE THREAD

**Issue by matiasilva** [bigbluebutton/bigbluebutton#9751]
**Describe the bug**
When updating and upgrading packages to the new 2.2.16 I obtain the following error:
```

Setting up bbb-web (1:2.2.0-130) ...
sed: -e expression #1, char 407: unterminated `s' command
dpkg: error processing package bbb-web (--configure):
 subprocess installed post-installation script returned error exit status 1
dpkg: dependency problems prevent configuration of bbb-config:
 bbb-config depends on bbb-web; however:
  Package bbb-web is not configured yet.
```

**Installation type**
Using an Ansible role

**Firewall and IP address type**
Behind a firewall and has its own IP address.

**Console output**
As above.

**Comment by matiasilva** [comment]
Turns out a faulty parameter led to bbb-web's fragile postint script getting confused.

**Comment by ffdixon** [comment]
> bbb-web's fragile postint script getting confused.

:-) 

We're working on making them less "fragile" over time

**Comment by matiasilva** [comment]
Yes! Highly appreciated
