### ISSUE TITLE
Wrap ip finder to allow IP setting from environment variable

### ISSUE THREAD

**Issue by aleixq** [bigbluebutton/bigbluebutton#9761]
Running `bbb-conf --setip` to change hostname or ip and also setting the hostname when installing gets the first device not being loopback(as said in http://docs.bigbluebutton.org/2.2/configure-firewall#overview ) , so if you have for example an ip for lan and other ip for wan it takes a little to configure everything. it would be great to accept IP from environment variable, just adding as this would solve it:

```
if [ -z "$IP" ]; then
        if LANG=c ifconfig | grep -q 'venet0:0'; then
            IP=$(ifconfig | grep -v '127.0.0.1' | grep -E "[0-9]*\.[0-9]*\.[0-9]*\.[0-9]*" | tail -1 | cut -d: -f2 | awk '{ print $1}')
        else
            IP=$(hostname -I | cut -f1 -d' ')
        fi
fi
```
in https://github.com/bigbluebutton/bigbluebutton/blob/32c741cef1c701e73bc40a3f1ec8045d41b7f836/bigbluebutton-config/bin/bbb-conf#L170

so then one can use:

`# IP=x.x.x.x bbb-conf --setip bbb.example.org`

just a proposal. thanks!

**Comment by matiasilva** [comment]
Hi Aleix. This looks great. Perhaps you can make a pull request that would integrate this as well as adding the appropriate documentation support to your PR?
