### ISSUE TITLE
audio/video does not work anymore after upgrade to 2.2.16

### ISSUE THREAD

**Issue by jelmd** [bigbluebutton/bigbluebutton#9764]
After upgrading to 2.2.16 audio and video via TURN do not work anymore:
- Video: Media could not reach the server (error 1020)
- Audio: Connection failure (ICE error 1007)

The STUN/TURN server is external, was not changed. Even tried with firewall disabled on the STUN/TURN and BBB server - w/o success.

The delta to the working version (from 2020-04-29, Ubuntu 16.04) is:
``` 
- bbb-apps                              1:2.2.0-42                           
- bbb-apps-akka                         2.2.0-80                             
- bbb-apps-screenshare                  1:2.2.0-42                           
+ bbb-apps                              1:2.2.0-45                           
+ bbb-apps-akka                         2.2.0-87                             
+ bbb-apps-screenshare                  1:2.2.0-45                           
  bbb-apps-sip                          1:2.2.0-11                           
- bbb-apps-video                        1:2.2.0-39                           
+ bbb-apps-video                        1:2.2.0-42                           
  bbb-apps-video-broadcast              1:2.2.0-8                            
- bbb-client                            1:2.2.0-33                           
- bbb-config                            1:2.2.0-173                          
- bbb-etherpad                          1:2.2.0-50                           
- bbb-freeswitch-core                   2:2.2.0-103                          
+ bbb-client                            1:2.2.0-40                           
+ bbb-config                            1:2.2.0-189                          
+ bbb-etherpad                          1:2.2.0-51                           
+ bbb-freeswitch-core                   2:2.2.0-112                          
  bbb-freeswitch-sounds                 1:1.6.7-6                            
- bbb-fsesl-akka                        2.2.0-62                             
- bbb-html5                             1:2.2.0-882                          
+ bbb-fsesl-akka                        2.2.0-65                             
+ bbb-html5                             1:2.2.0-934                          
  bbb-mkclean                           1:0.8.7-3                            
- bbb-playback-presentation             1:2.2.0-28                           
- bbb-record-core                       1:2.2.0-63                           
+ bbb-playback-presentation             1:2.2.0-30                           
+ bbb-record-core                       1:2.2.0-66                           
  bbb-red5                              1:1.0.10-16                          
  bbb-transcode-akka                    2.2.0-8                              
- bbb-web                               1:2.2.0-123                          
+ bbb-web                               1:2.2.0-130                          
  bbb-webrtc-sfu                        1:2.2.0-99                           
  bigbluebutton                         1:2.2.0-5                            
  ffmpeg                                7:4.2.2-1bbb1~ubuntu16.04            
```

Unfortunately the old packages are not available anymore, so at least for me it is not easy to puzzle out, where the problem got introduced.

The change I see in Mozilla FF is, that the stun/turn server does not show up anymore as local candidate in the `Trickled candidates` list in `about:webrtc`.

**Comment by wolbernd** [comment]
did you reapply all the config-changes you made to your configuration files? Those might get overwritten by an update. See also here: https://docs.bigbluebutton.org/2.2/customize.html#automatically-apply-configuration-changes-on-restart

**Comment by jelmd** [comment]
IIRC, yes. Went through https://docs.bigbluebutton.org/2.2/install.html#7--final-steps again.

**Comment by jelmd** [comment]
Hah, got it: `/usr/share/bbb-web/WEB-INF/classes/spring/turn-stun-servers.xml` was overwritten as well :(

Wondering, whether it is really needed to overwrite the config files of a running instance. Perhaps something clever could be used in the future. E.g. install recent config files always as ${cfg}.example and let `bbb-conf --check` copy it to ${cfg} if this file does not exist, otherwise ask what to do (show diffs, keep as is, copy over, decide later). A version number in the "head" of ${cfg} and ${cfg}.example could be used, to detect, whether a user already went through these questions. Something like that ...

**Comment by vince62s** [comment]
@jelmd what did you put in your /usr/share/bbb-web/WEB-INF/classes/spring/turn-stun-servers.xml to make it work ? I don't recall to have changed this one before.

**Comment by jelmd** [comment]
That's my config:
```
cli-password = my_secret
acme-redirect = "http://my.le.do.main/.well-known/acme-challenge/"
userdb=/data/coturn/db
log-file=/var/log/coturn.log
simple-log
proc-user=webservd
proc-group=webservd
listening-port=80
tls-listening-port=443
external-ip=a.b.c.d
min-port=49152
max-port=65535
no-multicast-peers
fingerprint
static-auth-secret=............
realm=my.do.main
cert=/data/coturn/server.crt
pkey=/data/coturn/server.key
cipher-list="ECDH+AESGCM:ECDH+CHACHA20:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:RSA+AESGCM:RSA+AES:!aNULL:!MD5:!DSS"
no-tlsv1
no-tlsv1_1
```
The IP is directly reachable, uses its own firewall (iptables). So external-IP == internal-IP == relay-ip.

**Comment by vipin-dev** [comment]
Same issue but doesn't work for me

**Comment by ousat** [comment]
> Hah, got it: `/usr/share/bbb-web/WEB-INF/classes/spring/turn-stun-servers.xml` was overwritten as well :(
> 
> Wondering, whether it is really needed to overwrite the config files of a running instance. Perhaps something clever could be used in the future. E.g. install recent config files always as ${cfg}.example and let `bbb-conf --check` copy it to ${cfg} if this file does not exist, otherwise ask what to do (show diffs, keep as is, copy over, decide later). A version number in the "head" of ${cfg} and ${cfg}.example could be used, to detect, whether a user already went through these questions. Something like that ...

I am facing the same issue, despite all these , 1002 error 
is says sip.parser error
