### ISSUE TITLE
assigned breakout rooms not selected if checkbox selected for choosing own rooms

### ISSUE THREAD

**Issue by Puschek** [bigbluebutton/bigbluebutton#9767]
**Describe the bug**
While setting up the breakout rooms, you can assign users to specific rooms. If you give them the power to chose their room which they can join, all users are giving a default room at start, not the assigned room from the setup.

**To Reproduce**
1. Klick create breakout rooms
2. Assign users to rooms
3. Activate checkbox for self choosing rooms
4. Klick create button
5. See the error

**Expected behavior**
If I assign users to a breakout room and give them the power to choose their own room, I expect the dropdown menu to show the first assigned room as selected option.

**Actual behavior**
If I assign users to a breakout room and give them the power to choose their own room, the first selected option is - for 4 breakout rooms room 1, for 8 breakout rooms room 4.

**BBB version (optional):**
2.2.14 

**Desktop (please complete the following information):**
 - OS: Windows, Mac, Linux
 - Browser Chrome, Firefox

**Comment by antobinary** [comment]
Merging into https://github.com/bigbluebutton/bigbluebutton/issues/13250
