### ISSUE TITLE
Conference PIN number is displayed without leading zeros

### ISSUE THREAD

**Issue by schrd** [bigbluebutton/bigbluebutton#9769]
**Describe the bug**
If the randomly generated voiceBridge has less digits than the configured number of digits, then in the welcome message leading zeros are not displayed. Example: 6 digits configured, the random number generator produces 12345. The %%CONFNUM%% in the welcome text is replaced by "12 345", it should be "012 345". Freeswitch expects 012345 as conference number.

**Expected behavior**

Welcome message should be:

    To join this meeting by phone, dial:<br>  +1234567890<br>Then enter 012 345 as the conference PIN number

**Actual behavior**
Welcome message currently is:

    To join this meeting by phone, dial:<br>  +1234567890<br>Then enter 12 345 as the conference PIN number

**Comment by antobinary** [comment]
#9792 was merged and included in BBB 2.2.20

**Comment by symptog** [comment]
@antobinary there is no updated bbb-web package in 2.2.20 and the fix is stil missing
