### ISSUE TITLE
External people cannot create or join a room

### ISSUE THREAD

**Issue by NBBBN21** [bigbluebutton/bigbluebutton#9770]
Hello everyone, 

unfortunately I can't get any further. External people cannot create or join a room. But you can register and choose a room.

I hope somebody can help me.

best regards

Noah

some information:

 

(External IP=82.100.224.XX; Internal IP=172.16.XX.X)

 

root@BBBunbuntu:~# bbb-conf --check

 

BigBlueButton Server 2.2.9 (1891)

                    Kernel version: 4.4.0-178-generic

                      Distribution: Ubuntu 16.04.6 LTS (64-bit)

                            Memory: 8446 MB

                         CPU cores: 4

 

/usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties (bbb-web)

       bigbluebutton.web.serverURL: https://82.100.224.XX

                defaultGuestPolicy: ALWAYS_ACCEPT

                 svgImagesRequired: true

 

/etc/nginx/sites-available/bigbluebutton (nginx)

                       server name: 172.16.XX.X

                              port: 80, [::]:80

                              port: 443 ssl

                    bbb-client dir: /var/www/bigbluebutton

 

/var/www/bigbluebutton/client/conf/config.xml (bbb-client)

                Port test (tunnel): rtmp://82.100.224.XX

                              red5: 82.100.224.XX

              useWebrtcIfAvailable: true

 

/opt/freeswitch/etc/freeswitch/vars.xml (FreeSWITCH)

                       local_ip_v4: 172.16.XX.X

                   external_rtp_ip: 82.100.224.XX

                   external_sip_ip: 82.100.224.XX

 

/opt/freeswitch/etc/freeswitch/sip_profiles/external.xml (FreeSWITCH)

                        ext-rtp-ip: $${external_rtp_ip}

                        ext-sip-ip: $${external_sip_ip}

                        ws-binding: :5066

                       wss-binding: :7443

 

/usr/local/bigbluebutton/core/scripts/bigbluebutton.yml (record and playback)

                     playback_host: 82.100.224.XX

                 playback_protocol: https

                            ffmpeg: 4.2.2-1bbb1~ubuntu16.04

 

/etc/bigbluebutton/nginx/sip.nginx (sip.nginx)

                        proxy_pass: 82.100.224.XX

 

/usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml (Kurento SFU)

                        kurento.ip: 82.100.224.XX

                       kurento.url: ws://82.100.224.XX:8888/kurento

                    localIpAddress: 172.16.XX.X

               recordScreenSharing: true

                     recordWebcams: true

                  codec_video_main: VP8

               codec_video_content: VP8

 

/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml (HTML5 client)

                             build: 894

                        kurentoUrl: wss://82.100.224.XX/bbb-webrtc-sfu

                  enableListenOnly: true

 

 

# Potential problems described below

................................................................................

# Error: Could not connect to the configured hostname/IP address

#

#    https://82.100.224.XX/

#

# If your BigBlueButton server is behind a firewall, see FAQ.

 

# Warning: The setting of 82.100.224.XX for proxy_pass in

#

#    /etc/bigbluebutton/nginx/sip.nginx

#

# does not match the local IP address (172.16.XX.X).

# (This is OK if you've manually changed the values)

**Comment by basisbit** [comment]
For support requests, please use the [forum / mailing list](https://groups.google.com/forum/#!forum/bigbluebutton-setup). This issue tracker here is only for BBB development related issues. Sorry.
