### ISSUE TITLE
Error 1004 on open a breakout room 

### ISSUE THREAD

**Issue by 6584987496486516123** [bigbluebutton/bigbluebutton#9776]
**Describe the bug**
on the server is working perfectly, however when creating the brakoutroom, we encounter the error: call failure (reason = Not Found) (error 1004)

I had this problem when installing the server on amazon, however I decided to create a stun / turn server which solved the problem, I can't find anything related to the breakout room configuration, please help me.

**To Reproduce**
when entering the breakoutroom

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome and Firefox
 - Version 22

**Comment by 6584987496486516123** [comment]
![error_bbb](https://user-images.githubusercontent.com/54856498/83807247-c2a77300-a680-11ea-94ab-a6a139373adc.PNG)

**Comment by basisbit** [comment]
This here is the issue tracker for BigBlueButton development related issues. For support requests, please use the forum / mailing list at https://groups.google.com/forum/#!forum/bigbluebutton-setup
