### ISSUE TITLE
Presentation invisible

### ISSUE THREAD

**Issue by CalvinSchulze** [bigbluebutton/bigbluebutton#9777]
Hi, 
I've got the latest version installed and can't see the presentation pages during a conference. The layout is there, but the presentation isn't. I double-checked if the files are accesible (via browser). The recordings show the pages as well.
SSL encryption is enabled, but with a self created certificate. Could this be the problem?

![image](https://user-images.githubusercontent.com/15137329/83843130-a0efcf80-a704-11ea-93e5-0314f8f02ff2.png)

**Comment by wcchien** [comment]
Please check your web server cert SSL is Expired, or it's ca root certificate  is Expired.

Sectigo AddTrust External CA Root Expiring May 30, 2020.

https://support.sectigo.com/articles/Knowledge/Sectigo-AddTrust-External-CA-Root-Expiring-May-30-2020

**Comment by wcchien** [comment]
https://groups.google.com/forum/#!topic/bigbluebutton-dev/ZC88kkTuZpg

**Comment by basisbit** [comment]
For support requests, please use the [forum / mailing list](https://groups.google.com/forum/#!forum/bigbluebutton-setup). This issue tracker here is only for BBB development related issues.
