### ISSUE TITLE
Poor quality in html5 shared screen

### ISSUE THREAD

**Issue by amguirado73** [bigbluebutton/bigbluebutton#9784]
Hi,

we are using BBB 2.2.14 and we have problems to shared screen. Some browser (Chrome Versión 83.0.4103.61) can't do it (browser crash). Besides, when we can share the screen the quality is poor. I suppose that If you see the screen in default BBB layout, you must resize the screen but our users complain about quality.  We use only HTM5 client.

Are there some requirements for browsers (java installed or something)?. Can we increase the quality for screen shared by configuration?.

Thank you.

**Comment by basisbit** [comment]
For support requests, please use the [forum / mailing list](https://groups.google.com/forum/#!forum/bigbluebutton-setup). This issue tracker here is only for BBB development related issues. Sorry.
