### ISSUE TITLE
Meta parameters for every new participant (Join meeting)

### ISSUE THREAD

**Issue by aloisogomes** [bigbluebutton/bigbluebutton#9786]
**Is your feature request related to a problem? Please describe.**
i'm looking at api and i miss something when we call joinMeeting. I think that Meta params can be very useful for many propuses. 

**Describe the solution you'd like**
Pass meta params for new participants

**Describe alternatives you've considered**
No one

**Additional context**
Who start with cam, mic, who not, who can join public chat who not. meta params can tell to application many things about new participants.

**Comment by pedrobmarin** [comment]
https://docs.bigbluebutton.org/2.2/customize.html#passing-custom-parameters-to-the-client-on-join
