### ISSUE TITLE
Problem with recording

### ISSUE THREAD

**Issue by rajuareraju** [bigbluebutton/bigbluebutton#9788]
I have installed bbb 2.2 using bbb-install.sh on Ubuntu 16.04. Everything worked fine except recording. The audio was not heard in recording. 
On checking archive log, I found 
`"rsync: send_files failed to open "/var/freeswitch/nmeetings/9e003e928268e5744718ff6b1cc579c4d20b3e6a-1591546273139-3739111650.opus": Permission denied (13)"`
I think the issue was because freeswitch is creating all files with read only permission for the user.
```
ubuntu:~$ ls -lat /var/freeswitch/meetings/ | head -n 5
total 3435836
-rw-------+ 1 freeswitch daemon   2875200 Jun  7 18:13 9e003e928268e5744718ff6b1cc579c4d20b3e6a-1591553482901-728665.opus
drwxr-xr-x+ 2 freeswitch daemon     20480 Jun  7 18:12 .
-rw-------+ 1 freeswitch daemon   1847040 Jun  7 17:43 9e003e928268e5744718ff6b1cc579c4d20b3e6a-1591551773670-3744604184.opus
-rw-------  1 freeswitch daemon   1402560 Jun  7 17:17 9e003e928268e5744718ff6b1cc579c4d20b3e6a-1591550203164-3743035788.opus
```
How to change the meeting file permissions? chmod does not work for new files.

**Comment by ffdixon** [comment]
Can you post the output of the command `groups bigbluebutton`.  Here's what it should show

~~~
$ groups bigbluebutton
bigbluebutton : bigbluebutton freeswitch kurento
~~~

**Comment by rajuareraju** [comment]
> Can you post the output of the command `groups bigbluebutton`. Here's what it should show
> 
> ```
> $ groups bigbluebutton
> bigbluebutton : bigbluebutton freeswitch kurento
> ```
```
Hi, here it is 
ubuntu@:~$ sudo groups bigbluebutton
bigbluebutton : bigbluebutton freeswitch kurento
```

**Comment by nough** [comment]
Are you still getting new audio recordings in /var/freeswitch/meetings?

This could also be related to https://github.com/bigbluebutton/bigbluebutton/issues/9599 and https://github.com/bigbluebutton/bigbluebutton/issues/9762

**Comment by rajuareraju** [comment]
Hi,
The issue is happening in my test server which had only two cores and
4 GB RAM which is below BBB's minimum requirements.
Everything works fine on my production server which has everything
same except the hardware. So I decided to reinstall my testserver
after upgrading the hardware instead of debugging it.
Thanks for the help.
- Regards,
Rajeev K

**Comment by nough** [comment]
Rajeev, 
Can you confirm who owns the /var/freeswitch/meetings folder now?

**Comment by rajuareraju** [comment]
Hi,

Thanks for the help. We reinstalled everything on a slightly more  powerful
machine which meets minimum requirements of bbb. And the issue does not see
in the new machine.

- Regards,
Rajeev K
