### ISSUE TITLE
Thumbnail selection dropdown

### ISSUE THREAD

**Issue by hiroshisuga** [bigbluebutton/bigbluebutton#9790]
**Is your feature request related to a problem? Please describe.**
I am sometimes frustrated that in the recording list the thumbnails are always generated from the first three slides. 

**Describe the solution you'd like**
As the room owner, I would like to change the thumbnail picture by clicking the default slide picture, which then gives rise to a dropdown list from which I can choose the slide that represents the presentation better. 

**Describe alternatives you've considered**
A png selector window, instead of the dropdown list, can pop up. 

**Additional context**
I wonder if this is already planned for future release. If not, would this interest users?

A problem would be that greenlight should be modified in parallel. Actually I have already started working on this issue, but I am lost with the sentence:
<%= button_to update_recording_path(.........) do %>
in the greenlight/app/views/shared/components/_recording_row.html.
I guess this is a Ruby on Rails command. I would appreciate if somebody let me know where is actually the ruby script that deals "update_recording_path".

**Comment by matiasilva** [comment]
Hi. This is the GitHub page for BigBlueButton NOT Greenlight. Please close this issue and post elsewhere.
