### ISSUE TITLE
Sites recordings are disappeared

### ISSUE THREAD

**Issue by CIECT** [bigbluebutton/bigbluebutton#9793]
Hi guys,

We are having issues with the recording tab, for some sites (course/project) the recording tab displays a message " unreachableServerError:null ". 

![Sakai BBB-Recordings error (1)](https://user-images.githubusercontent.com/66317071/84016715-f551b400-a97d-11ea-839f-89b619f17958.jpg)
]()

On the BBB server we ran a check and no "potetntial problems" were detected, additionally we ran a status check and everything is active.

'bbb-conf --Status'
nginx —————————————————► [✔ - active]
freeswitch ————————————► [✔ - active]
redis-server ——————————► [✔ - active]
bbb-apps-akka —————————► [✔ - active]
bbb-transcode-akka ————► [✔ - active]
bbb-fsesl-akka ————————► [✔ - active]
red5 ——————————————————► [✔ - active]
mongod ————————————————► [✔ - active]
bbb-html5 —————————————► [✔ - active]
bbb-webrtc-sfu ————————► [✔ - active]
kurento-media-server ——► [✔ - active]
etherpad ——————————————► [✔ - active]
bbb-web ———————————————► [✔ - active]

'bbb-conf --check'
BigBlueButton Server 2.2.16 (1991)
                    Kernel version: 4.4.0-165-generic
                      Distribution: Ubuntu 16.04.6 LTS (64-bit)
                            Memory: 32946 MB
                         CPU cores: 12

/usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties (bbb-web)
       bigbluebutton.web.serverURL: https://bigblue2.uwc.ac.za
                defaultGuestPolicy: ALWAYS_ACCEPT
                 svgImagesRequired: true

/etc/nginx/sites-available/bigbluebutton (nginx)
                       server name: bigblue2.uwc.ac.za
                              port: 80, [::]:80443
                    bbb-client dir: /var/www/bigbluebutton

/var/www/bigbluebutton/client/conf/config.xml (bbb-client)
                Port test (tunnel): rtmp://bigblue2.uwc.ac.za
                              red5: bigblue2.uwc.ac.za
              useWebrtcIfAvailable: true

/opt/freeswitch/etc/freeswitch/vars.xml (FreeSWITCH)
                       local_ip_v4: 196.21.45.55
                   external_rtp_ip: 196.21.45.55
                   external_sip_ip: 196.21.45.55

/opt/freeswitch/etc/freeswitch/sip_profiles/external.xml (FreeSWITCH)
                        ext-rtp-ip: $${local_ip_v4}
                        ext-sip-ip: $${local_ip_v4}
                        ws-binding: :5066
                       wss-binding: :7443

/usr/local/bigbluebutton/core/scripts/bigbluebutton.yml (record and playback)
                     playback_host: bigblue2.uwc.ac.za
                 playback_protocol: https
                            ffmpeg: 4.2.2-1bbb1~ubuntu16.04

/etc/bigbluebutton/nginx/sip.nginx (sip.nginx)
                        proxy_pass: 196.21.45.55

/usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml (Kurento SFU)
                        kurento.ip: 196.21.45.55
                       kurento.url: ws://127.0.0.1:8888/kurento
                    kurento.sip_ip: 196.21.45.55
                    localIpAddress: 196.21.45.55
               recordScreenSharing: true
                     recordWebcams: true
                  codec_video_main: VP8
               codec_video_content: VP8

/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml (HTML5 client)
                             build: 934
                        kurentoUrl: wss://bigblue2.uwc.ac.za/bbb-webrtc-sfu
                  enableListenOnly: true

I ran: 'groups bigbluebutton'
bigbluebutton : bigbluebutton freeswitch kurento

I ran: 'bbb-record --rebuildall'
and the recordings are still not appearing.

I ran: 'bbb-record --list'
● bbb-rap-archive-worker.service - BigBlueButton recording and playback archive worker
   Loaded: loaded (/usr/lib/systemd/system/bbb-rap-archive-worker.service; static; vendor preset: enabled)
   Active: inactive (dead) since Mon 2020-06-08 10:48:55 SAST; 8min ago
Condition: start condition failed at Mon 2020-06-08 10:56:59 SAST; 21s ago
           ConditionPathExistsGlob=/var/bigbluebutton/recording/status/recorded/*.done was not met
  Process: 22593 ExecStart=/usr/local/bigbluebutton/core/scripts/rap-archive-worker.rb (code=exited, status=0/SUCCESS)
 Main PID: 22593 (code=exited, status=0/SUCCESS)

Jun 08 10:48:53 bigblue2.uwc.ac.za systemd[1]: Started BigBlueButton recording and playback archive worker.

● bbb-rap-sanity-worker.service - BigBlueButton recording and playback sanity check worker
   Loaded: loaded (/usr/lib/systemd/system/bbb-rap-sanity-worker.service; static; vendor preset: enabled)
   Active: inactive (dead) since Mon 2020-06-08 10:49:54 SAST; 7min ago
Condition: start condition failed at Mon 2020-06-08 10:56:59 SAST; 21s ago
           ConditionPathExistsGlob=/var/bigbluebutton/recording/status/archived/*.done was not met
  Process: 24691 ExecStart=/usr/local/bigbluebutton/core/scripts/rap-sanity-worker.rb (code=exited, status=0/SUCCESS)
 Main PID: 24691 (code=exited, status=0/SUCCESS)

Jun 08 10:49:53 bigblue2.uwc.ac.za systemd[1]: Started BigBlueButton recording and playback sanity check worker.

● bbb-rap-process-worker.service - BigBlueButton recording and playback process worker
   Loaded: loaded (/usr/lib/systemd/system/bbb-rap-process-worker.service; static; vendor preset: enabled)
   Active: active (running) since Sat 2020-06-06 14:17:53 SAST; 1 day 20h ago
 Main PID: 8162 (rap-process-wor)
   CGroup: /bbb_record_core.slice/bbb-rap-process-worker.service
           ├─ 8162 /usr/bin/ruby /usr/local/bigbluebutton/core/scripts/rap-process-worker.rb
           ├─15474 ruby process/presentation.rb -m ac8907f0d7d4d16b6e3cd74ac334c8355c088fb3-1590506673595
           └─21684 ffmpeg -y -v warning -nostats -max_error_rate 1.0 -i /var/bigbluebutton/recording/process/presentation/ac8907f0d7d4d16b6e3cd74ac334c8355c088fb3-1590506673595/deskshare.ts -c:v libvpx-vp9 -b:v 1024K -minrate 512K -ma...

Jun 06 14:17:53 bigblue2.uwc.ac.za systemd[1]: Started BigBlueButton recording and playback process worker.

● bbb-rap-publish-worker.service - BigBlueButton recording and playback publish worker
   Loaded: loaded (/usr/lib/systemd/system/bbb-rap-publish-worker.service; static; vendor preset: enabled)
   Active: inactive (dead) since Mon 2020-06-08 09:10:55 SAST; 1h 46min ago
Condition: start condition failed at Mon 2020-06-08 10:56:59 SAST; 21s ago
           ConditionPathExistsGlob=/var/bigbluebutton/recording/status/processed/*.done was not met
  Process: 15476 ExecStart=/usr/local/bigbluebutton/core/scripts/rap-publish-worker.rb (code=exited, status=0/SUCCESS)
 Main PID: 15476 (code=exited, status=0/SUCCESS)

Jun 08 09:10:53 bigblue2.uwc.ac.za systemd[1]: Started BigBlueButton recording and playback publish worker.
--

I ran: 'bbb-record --debug'
/var/log/bigbluebutton/bbb-rap-worker.log.1:E, [2020-06-05T19:49:43.660640 #20496] ERROR -- : SIGTERM
/var/log/bigbluebutton/bbb-rap-worker.log.1:E, [2020-06-05T19:49:43.660865 #20496] ERROR -- : /usr/local/bigbluebutton/core/lib/recordandplayback.rb:124:in `each_line'
/var/log/bigbluebutton/bbb-rap-worker.log.1:E, [2020-06-05T19:49:43.660907 #20496] ERROR -- : /usr/local/bigbluebutton/core/lib/recordandplayback.rb:124:in `block in exec_ret'
/var/log/bigbluebutton/bbb-rap-worker.log.1:E, [2020-06-05T19:49:43.660943 #20496] ERROR -- : /usr/local/bigbluebutton/core/lib/recordandplayback.rb:123:in `popen'
/var/log/bigbluebutton/bbb-rap-worker.log.1:E, [2020-06-05T19:49:43.660976 #20496] ERROR -- : /usr/local/bigbluebutton/core/lib/recordandplayback.rb:123:in `exec_ret'
/var/log/bigbluebutton/bbb-rap-worker.log.1:E, [2020-06-05T19:49:43.661009 #20496] ERROR -- : /usr/local/bigbluebutton/core/scripts/rap-process-worker.rb:81:in `block (2 levels) in process_archived_meetings'
/var/log/bigbluebutton/bbb-rap-worker.log.1:E, [2020-06-05T19:49:43.661070 #20496] ERROR -- : /usr/local/bigbluebutton/core/scripts/rap-process-worker.rb:57:in `each'
/var/log/bigbluebutton/bbb-rap-worker.log.1:E, [2020-06-05T19:49:43.661111 #20496] ERROR -- : /usr/local/bigbluebutton/core/scripts/rap-process-worker.rb:57:in `block in process_archived_meetings'
/var/log/bigbluebutton/bbb-rap-worker.log.1:E, [2020-06-05T19:49:43.661146 #20496] ERROR -- : /usr/local/bigbluebutton/core/scripts/rap-process-worker.rb:31:in `each'
/var/log/bigbluebutton/bbb-rap-worker.log.1:E, [2020-06-05T19:49:43.661179 #20496] ERROR -- : /usr/local/bigbluebutton/core/scripts/rap-process-worker.rb:31:in `process_archived_meetings'
/var/log/bigbluebutton/bbb-rap-worker.log.1:E, [2020-06-05T19:49:43.661212 #20496] ERROR -- : /usr/local/bigbluebutton/core/scripts/rap-process-worker.rb:156:in `<main>'
/var/log/bigbluebutton/bbb-rap-worker.log.1:E, [2020-06-05T19:52:22.603251 #7069] ERROR -- : SIGTERM
/var/log/bigbluebutton/bbb-rap-worker.log.1:E, [2020-06-05T19:52:22.603449 #7069] ERROR -- : /usr/local/bigbluebutton/core/lib/recordandplayback.rb:124:in `each_line'
/var/log/bigbluebutton/bbb-rap-worker.log.1:E, [2020-06-05T19:52:22.603491 #7069] ERROR -- : /usr/local/bigbluebutton/core/lib/recordandplayback.rb:124:in `block in exec_ret'
/var/log/bigbluebutton/bbb-rap-worker.log.1:E, [2020-06-05T19:52:22.603542 #7069] ERROR -- : /usr/local/bigbluebutton/core/lib/recordandplayback.rb:123:in `popen'
/var/log/bigbluebutton/bbb-rap-worker.log.1:E, [2020-06-05T19:52:22.603580 #7069] ERROR -- : /usr/local/bigbluebutton/core/lib/recordandplayback.rb:123:in `exec_ret'
/var/log/bigbluebutton/bbb-rap-worker.log.1:E, [2020-06-05T19:52:22.603613 #7069] ERROR -- : /usr/local/bigbluebutton/core/scripts/rap-process-worker.rb:80:in `block (2 levels) in process_archived_meetings'
/var/log/bigbluebutton/bbb-rap-worker.log.1:E, [2020-06-05T19:52:22.603646 #7069] ERROR -- : /usr/local/bigbluebutton/core/scripts/rap-process-worker.rb:56:in `each'
/var/log/bigbluebutton/bbb-rap-worker.log.1:E, [2020-06-05T19:52:22.603679 #7069] ERROR -- : /usr/local/bigbluebutton/core/scripts/rap-process-worker.rb:56:in `block in process_archived_meetings'
/var/log/bigbluebutton/bbb-rap-worker.log.1:E, [2020-06-05T19:52:22.603713 #7069] ERROR -- : /usr/local/bigbluebutton/core/scripts/rap-process-worker.rb:30:in `each'
/var/log/bigbluebutton/bbb-rap-worker.log.1:E, [2020-06-05T19:52:22.603748 #7069] ERROR -- : /usr/local/bigbluebutton/core/scripts/rap-process-worker.rb:30:in `process_archived_meetings'
/var/log/bigbluebutton/bbb-rap-worker.log.1:E, [2020-06-05T19:52:22.603803 #7069] ERROR -- : /usr/local/bigbluebutton/core/scripts/rap-process-worker.rb:155:in `<main>'
/var/log/bigbluebutton/bbb-rap-worker.log.1:E, [2020-06-05T20:27:16.373582 #15722] ERROR -- : SIGTERM
/var/log/bigbluebutton/bbb-rap-worker.log.1:E, [2020-06-05T20:27:16.373767 #15722] ERROR -- : /usr/local/bigbluebutton/core/lib/recordandplayback.rb:124:in `each_line'
/var/log/bigbluebutton/bbb-rap-worker.log.1:E, [2020-06-05T20:27:16.373809 #15722] ERROR -- : /usr/local/bigbluebutton/core/lib/recordandplayback.rb:124:in `block in exec_ret'
/var/log/bigbluebutton/bbb-rap-worker.log.1:E, [2020-06-05T20:27:16.373845 #15722] ERROR -- : /usr/local/bigbluebutton/core/lib/recordandplayback.rb:123:in `popen'
/var/log/bigbluebutton/bbb-rap-worker.log.1:E, [2020-06-05T20:27:16.373879 #15722] ERROR -- : /usr/local/bigbluebutton/core/lib/recordandplayback.rb:123:in `exec_ret'
/var/log/bigbluebutton/bbb-rap-worker.log.1:E, [2020-06-05T20:27:16.373913 #15722] ERROR -- : /usr/local/bigbluebutton/core/scripts/rap-process-worker.rb:80:in `block (2 levels) in process_archived_meetings'
/var/log/bigbluebutton/bbb-rap-worker.log.1:E, [2020-06-05T20:27:16.373990 #15722] ERROR -- : /usr/local/bigbluebutton/core/scripts/rap-process-worker.rb:56:in `each'
/var/log/bigbluebutton/bbb-rap-worker.log.1:E, [2020-06-05T20:27:16.374028 #15722] ERROR -- : /usr/local/bigbluebutton/core/scripts/rap-process-worker.rb:56:in `block in process_archived_meetings'
/var/log/bigbluebutton/bbb-rap-worker.log.1:E, [2020-06-05T20:27:16.374061 #15722] ERROR -- : /usr/local/bigbluebutton/core/scripts/rap-process-worker.rb:30:in `each'
/var/log/bigbluebutton/bbb-rap-worker.log.1:E, [2020-06-05T20:27:16.374094 #15722] ERROR -- : /usr/local/bigbluebutton/core/scripts/rap-process-worker.rb:30:in `process_archived_meetings'
/var/log/bigbluebutton/bbb-rap-worker.log.1:E, [2020-06-05T20:27:16.374139 #15722] ERROR -- : /usr/local/bigbluebutton/core/scripts/rap-process-worker.rb:155:in `<main>'
/var/log/bigbluebutton/bbb-rap-worker.log.1:E, [2020-06-05T21:04:53.816639 #23517] ERROR -- : SIGTERM
/var/log/bigbluebutton/bbb-rap-worker.log.1:E, [2020-06-05T21:04:53.816814 #23517] ERROR -- : /usr/local/bigbluebutton/core/lib/recordandplayback.rb:124:in `each_line'
/var/log/bigbluebutton/bbb-rap-worker.log.1:E, [2020-06-05T21:04:53.816855 #23517] ERROR -- : /usr/local/bigbluebutton/core/lib/recordandplayback.rb:124:in `block in exec_ret'
/var/log/bigbluebutton/bbb-rap-worker.log.1:E, [2020-06-05T21:04:53.816891 #23517] ERROR -- : /usr/local/bigbluebutton/core/lib/recordandplayback.rb:123:in `popen'
/var/log/bigbluebutton/bbb-rap-worker.log.1:E, [2020-06-05T21:04:53.816925 #23517] ERROR -- : /usr/local/bigbluebutton/core/lib/recordandplayback.rb:123:in `exec_ret'
/var/log/bigbluebutton/bbb-rap-worker.log.1:E, [2020-06-05T21:04:53.816959 #23517] ERROR -- : /usr/local/bigbluebutton/core/scripts/rap-process-worker.rb:80:in `block (2 levels) in process_archived_meetings'
/var/log/bigbluebutton/bbb-rap-worker.log.1:E, [2020-06-05T21:04:53.816996 #23517] ERROR -- : /usr/local/bigbluebutton/core/scripts/rap-process-worker.rb:56:in `each'
/var/log/bigbluebutton/bbb-rap-worker.log.1:E, [2020-06-05T21:04:53.817052 #23517] ERROR -- : /usr/local/bigbluebutton/core/scripts/rap-process-worker.rb:56:in `block in process_archived_meetings'
/var/log/bigbluebutton/bbb-rap-worker.log.1:E, [2020-06-05T21:04:53.817114 #23517] ERROR -- : /usr/local/bigbluebutton/core/scripts/rap-process-worker.rb:30:in `each'
/var/log/bigbluebutton/bbb-rap-worker.log.1:E, [2020-06-05T21:04:53.817184 #23517] ERROR -- : /usr/local/bigbluebutton/core/scripts/rap-process-worker.rb:30:in `process_archived_meetings'
/var/log/bigbluebutton/bbb-rap-worker.log.1:E, [2020-06-05T21:04:53.817247 #23517] ERROR -- : /usr/local/bigbluebutton/core/scripts/rap-process-worker.rb:155:in `<main>'

There are 6 course sites that are currently being affected and the recordings that were previously visible and available are for upcoming exams. Your assistance is greatly appreciated.

**Comment by basisbit** [comment]
For support requests, please use the [forum / mailing list](https://groups.google.com/forum/#!forum/bigbluebutton-setup). This issue tracker here is only for BBB development related issues. Sorry.
