### ISSUE TITLE
bbb_api_conf.jsp file not found error, 

### ISSUE THREAD

**Issue by ksamygit** [bigbluebutton/bigbluebutton#9795]
type Exception report

message /demo1.jsp (line: 38, column: 1) /bbb_api.jsp (line: 35, column: 1) File "bbb_api_conf.jsp" not found

description The server encountered an internal error that prevented it from fulfilling this request.

exception

org.apache.jasper.JasperException: /demo1.jsp (line: 38, column: 1) /bbb_api.jsp (line: 35, column: 1) File "bbb_api_conf.jsp" not found
	org.apache.jasper.compiler.DefaultErrorHandler.jspError(DefaultErrorHandler.java:42)
	org.apache.jasper.compiler.ErrorDispatcher.dispatch(ErrorDispatcher.java:443)
	org.apache.jasper.compiler.ErrorDispatcher.jspError(ErrorDispatcher.java:89)
	org.apache.jasper.compiler.Parser.processIncludeDirective(Parser.java:333)
	org.apache.jasper.compiler.Parser.parseIncludeDirective(Parser.java:366)
	org.apache.jasper.compiler.Parser.parseDirective(Parser.java:476)
	org.apache.jasper.compiler.Parser.parseFileDirectives(Parser.java:1773)
	org.apache.jasper.compiler.Parser.parse(Parser.java:135)
	org.apache.jasper.compiler.ParserController.doParse(ParserController.java:242)
	org.apache.jasper.compiler.ParserController.parseDirectives(ParserController.java:119)
	org.apache.jasper.compiler.Compiler.generateJava(Compiler.java:194)
	org.apache.jasper.compiler.Compiler.compile(Compiler.java:374)
	org.apache.jasper.compiler.Compiler.compile(Compiler.java:354)
	org.apache.jasper.compiler.Compiler.compile(Compiler.java:341)
	org.apache.jasper.JspCompilationContext.compile(JspCompilationContext.java:662)
	org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:364)
	org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:395)
	org.apache.jasper.servlet.JspServlet.service(JspServlet.java:339)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)

MacOS local setup of bbb-api-demo in tomcat 7 and java 1.8
Chrome browser

**Comment by basisbit** [comment]
what did you try to do? How to reproduce this problem? Why did you not use the issue template?
It sounds like you tried to run bbb server software on MacOS within tomcat - which is not a supported configuration. If you want to test your own code changes, set up a BBB server on a Ubuntu 16.04.6 install.

**Comment by ksamygit** [comment]
I'm not trying to use the bbb in Mac. I'm trying to check the API (using tomcat for JSP) how it works. Already running bbb server in ubuntu.

**Comment by basisbit** [comment]
In that case, please use the [development mailing list / forum](https://groups.google.com/forum/#!forum/bigbluebutton-dev). This issue tracker here is only for BBB development related issues. Sorry.

bbb-demo is not installed on the demo server, only on the test server: https://test.bigbluebutton.org/demo/demo1.jsp

**Comment by ksamygit** [comment]
Thanks
