### ISSUE TITLE
Support for youtube-nocookie-URLS

### ISSUE THREAD

**Issue by stonerl** [bigbluebutton/bigbluebutton#9797]
At the moment it is only possible to share standard YouTube-links like:

https://www.youtube.com/watch?v=FFxkL6DVSgg

YouTube also provides a URL that minimizes the used cookies.

https://www.youtube-nocookie.com/embed/FFxkL6DVSgg

Sharing such links is more privacy-friendly IMHO.

**Comment by matiasilva** [comment]
I agree. This is definitely a feature worth pursuing for the more privacy-concerned folks.

**Comment by matiasilva** [comment]
This has now been solved in the latest version of bbb-html5. See this for more information: https://github.com/CookPete/react-player/issues/896 Please close this issue.
