### ISSUE TITLE
Handle banned user re-attempting to join

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#9798]
Currently if a banned user re-attempts to join, they wait 1minute in (...) screen while repeatedly sending requests to validate auth token, get timed out and end up on 401 screen

Reproduce via:
API Mate:
create a meeting
join as moderator
then
set `userID`: `constant`
then hit the join as attendee link

From the moderator's client eject and :white_check_mark: on also prevent the user from joining again (aka ban this userID)

The attendee was ejected, Use the same URI to try to rejoin a session. Now you've hit the problem.

Potential solution path:
We have

```
object EjectReasonCode {
  val DUPLICATE_USER = "duplicate_user_in_meeting_eject_reason"
  val PERMISSION_FAILED = "not_enough_permission_eject_reason"
  val EJECT_USER = "user_requested_eject_reason"
  val SYSTEM_EJECT_USER = "system_requested_eject_reason"
  val VALIDATE_TOKEN = "validate_token_failed_eject_reason"
  val USER_INACTIVITY = "user_inactivity_eject_reason"
  val EJECTED_USER_REJOINING = "ejected_user_rejoining_reason"
}
``` 

in akka-apps and I see `user_requested_eject_reason` utilized when kicking out. 

1) when a banned user is trying to join again, send out a json on redis saying that the user is banned
2) end the repeated requests for auth validation
3) when the client receives info that the user is banned, do not redirect to 401. Or if you do, make sure there is wording about the user being banned from the meeting. Do not offer to "login again"

**Comment by krishnateja-ct** [comment]
@antobinary Apart from the bug reported on client-side, I observed when a user after getting banned, re-attempts to join again in the same meeting, the response for JOIN API request is 
```
<returncode>SUCCESS</returncode>
<messageKey>successfullyJoined</messageKey>
<message>You have joined successfully.</message>
```
The BBB server we used for this meeting is configured with allowDuplicateExtUserid=false in bigbluebutton.properties

Is this the expected behavior?
