### ISSUE TITLE
Change the ordering of items on 401 page

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#9799]
Current:

![Screenshot from 2020-06-08 11-56-22](https://user-images.githubusercontent.com/6312397/84052883-2a123b00-a97f-11ea-8624-160633ee9fb8.png)

1) remove the Log in again button - in real world scenario the user comes from LMS (or other app and the button offers no benefit - we don't know where to send them to)
2) Use the following order:

Unauthorized
description
401

Where the error code uses small font.

**Comment by basisbit** [comment]
Would be nice to offer a setting for a landing page URL

**Comment by matiasilva** [comment]
@basisbit landing page where? on the BBB hosts? or a redirect on this page?

**Comment by antobinary** [comment]
We have this in bigbluebutton.properties in bbb-web

```
#----------------------------------------------------
# Assign URL where the logged-out participant will be redirected after sign-out.
# If "default", it returns to bigbluebutton.web.serverURL
bigbluebutton.web.logoutURL=default
```

**Comment by matiasilva** [comment]
For a load balanced deployment, I've found this works great if you add a redirect on each BBB host to your front-end. That way you avoid touching the settings on each host and just add a simple redirect.
