### ISSUE TITLE
Fullscreen for playback doesn't work

### ISSUE THREAD

**Issue by amguirado73** [bigbluebutton/bigbluebutton#9800]
Hello,

in BBB 2.2.14 when you see a recorded meeting and press  fullscreen button, nothing is showed  (no presentation, no video, nothing).

Regards.
Thank you.

bbb-conf --version

ii  bbb-apps                              1:2.2.0-44                                      amd64        BigBlueButton applications for Red5
ii  bbb-apps-akka                         2.2.0-86                                        all          BigBlueButton Apps (Akka)
ii  bbb-apps-screenshare                  1:2.2.0-44                                      amd64        BigBlueButton screenshare module for Red5
ii  bbb-apps-sip                          1:2.2.0-11                                      amd64        BigBlueButton SIP module for Red5
ii  bbb-apps-video                        1:2.2.0-41                                      amd64        BigBlueButton video module for Red5
ii  bbb-apps-video-broadcast              1:2.2.0-8                                       amd64        BigBlueButton video broadcast module for Red5
ii  bbb-client                            1:2.2.0-40                                      amd64        BigBlueButton Flash client
ii  bbb-config                            1:2.2.0-185                                     amd64        BigBlueButton configuration utilities
ii  bbb-etherpad                          1:2.2.0-50                                      amd64        The EtherPad Lite components for BigBlueButton
ii  bbb-freeswitch-core                   2:2.2.0-112                                     amd64        BigBlueButton build of FreeSWITCH
ii  bbb-freeswitch-sounds                 1:1.6.7-6                                       amd64        FreeSWITCH Sounds
ii  bbb-fsesl-akka                        2.2.0-64                                        all          BigBlueButton FS-ESL (Akka)
ii  bbb-html5                             1:2.2.0-925                                     amd64        The HTML5 components for BigBlueButton
ii  bbb-mkclean                           1:0.8.7-3                                       amd64        Clean and optimize Matroska and WebM files
ii  bbb-playback-presentation             1:2.2.0-29                                      amd64        BigBluebutton playback of presentation
ii  bbb-record-core                       1:2.2.0-65                                      amd64        BigBlueButton record and playback
ii  bbb-red5                              1:1.0.10-16                                     amd64        The Red5 server for BigBlueButton
ii  bbb-transcode-akka                    2.2.0-8                                         all          BigBlueButton Transcoder
ii  bbb-web                               1:2.2.0-128                                     amd64        BigBlueButton API
ii  bbb-webrtc-sfu                        1:2.2.0-99                                      amd64        BigBlueButton WebRTC SFU
ii  bigbluebutton                         1:2.2.0-5                                       amd64        Open source web conferencing platform (bbb)
ii  ffmpeg                                7:4.2.2-1bbb1~ubuntu16.04                       amd64        Tools for transcoding, streaming and playing of multimedia files
ii  libavcodec58:amd64                    7:4.2.2-1bbb1~ubuntu16.04                       amd64        FFmpeg library with de/encoders for audio/video codecs - runtime files
ii  libavdevice58:amd64                   7:4.2.2-1bbb1~ubuntu16.04                       amd64        FFmpeg library for handling input and output devices - runtime files
ii  libavfilter7:amd64                    7:4.2.2-1bbb1~ubuntu16.04                       amd64        FFmpeg library containing media filters - runtime files
ii  libavformat58:amd64                   7:4.2.2-1bbb1~ubuntu16.04                       amd64        FFmpeg library with (de)muxers for multimedia containers - runtime files
ii  libavresample4:amd64                  7:4.2.2-1bbb1~ubuntu16.04                       amd64        FFmpeg compatibility library for resampling - runtime files
ii  libavutil56:amd64                     7:4.2.2-1bbb1~ubuntu16.04                       amd64        FFmpeg library with functions for simplifying programming - runtime files
ii  libopusenc0                           0.2.1-1bbb1                                     amd64        High-level API for encoding Ogg Opus audio streams
ii  libpostproc55:amd64                   7:4.2.2-1bbb1~ubuntu16.04                       amd64        FFmpeg library for post processing - runtime files
ii  libswresample3:amd64                  7:4.2.2-1bbb1~ubuntu16.04                       amd64        FFmpeg library for audio resampling, rematrixing etc. - runtime files
ii  libswscale5:amd64                     7:4.2.2-1bbb1~ubuntu16.04                       amd64        FFmpeg library for image scaling and various conversions - runtime files

**Comment by abhilash26** [comment]
Hello BBB Team,
I am facing the same issue. When watching the recording in the fullscreen mode we get the white video fullscreen which doesn't work.
Please tell me how I can resolve this issue.

Thanks and Regards,
Abhilash

![Screenshot from 2020-06-20 19-28-52](https://user-images.githubusercontent.com/28080925/85203695-15458800-b32d-11ea-84b0-169de69c742c.png)
![Screenshot from 2020-06-20 19-29-05](https://user-images.githubusercontent.com/28080925/85203697-170f4b80-b32d-11ea-83f7-c119ebfbd5f4.png)

**Comment by rmallah** [comment]
The issue is important as it affects the readability of screencasts.

**Comment by amguirado73** [comment]
Hello,

fullscreen only work for video notmfor presentations. Check fullscreen when
there os video and the works. I don't know if this is a issue ir normal
behaviour.

Regards

**Comment by matiasilva** [comment]
Yes @amguirado73 is correct. If you're just viewing a recorded presentation then fullscreen does nothing. See #9052.

**Comment by matiasilva** [comment]
Merging with #8275.
