### ISSUE TITLE
Post-install, audio fixed but screen share and webcam not working for users outside of firewall...

### ISSUE THREAD

**Issue by derek-shnosh** [bigbluebutton/bigbluebutton#9804]
**Describe the bug**
When accessing my BBB server from _outside_ my firewall, I'm receiving **Connection failure (ICE error 1007)**. All works fine when connected via VPN or while connected _inside_ of the firewall, but I cannot get audio while coming from _outside_ the firewall.

I have read through and scoured all of the configuration files, walked through the install process numerous times to verify I didn't misread an instruction.

**Installation type**
Manual Installation.

**Firewall and IP address type**
Server is behind a Cisco Firewall, has a dedicated public IP address with NAT.

**Additional context**
This is a new deployment... When accessing my BBB server from _outside_ my firewall, I'm receiving **Connection failure (ICE error 1007)**. All works fine when connected via VPN or while connected _inside_ of the firewall, but I cannot get audio while coming from _outside_ the firewall.

Firewall is Cisco, configured to permit `TCP 80, 443, 7443` and `UDP 16384-32768`; config below...

```
access-list outside-in extended permit object-group WEB-Services any4 object BBB
access-list outside-in extended permit object-group Meet-Services any4 object BBB
access-group outside-in in interface outside
!
object-group service WEB-Services
 service-object tcp destination eq www 
 service-object tcp destination eq https 
!
object-group service Meet-Services
 service-object udp destination range 16384 32768 
 service-object tcp destination eq 7443 
!
object network BBB
 host 10.1.1.1
 nat {inside,outside) static 12.34.56.78
```

NAT config is static `IP`:`IP`, so any packet on any port to `12.34.56.78` (external IP) will be forwarded to `10.1.1.1` (internal IP).

I have even tried temporarily permitting **all** traffic and still don't get audio when connecting from _outside_ of the firewall.

```
access-list outside-in extended permit ip any4 object BBB
```

I'm not super savvy with SDP, but checked `about:webrtc` and see the following:
- Local SDP (Offer) > `c=IN IP4 12.34.56.78`
- Remote SDP (Answer) > `c=IN IP4 10.1.1.1`

Curious if this expected, since it lists `10.1.1.1` under the **Remote Candidate** column of the **ICE Stats** table within `about:webrtc` in Firefox.

I noticed that if I configure `12.34.56.78` as `proxy_pass` in **/etc/bigbluebutton/nginx/sip.nginx**, I get the following message when I restart via `bbb-conf --restart`.

```
# Warning: The setting of 12.34.56.78 for proxy_pass in
#
#    /etc/bigbluebutton/nginx/sip.nginx
#
# does not match the local IP address (10.1.1.1).
# (This is OK if you've manually changed the values)
```

Then I get **1002** errors no matter where I try to connect from; also, the **Remote Candidate** still shows `10.1.1.1` in `about:webrtc`.

If I change `proxy_pass` to `10.1.1.1`, I don't get that warning but I can only connect to audio while on VPN or _inside_ the firewall.

**Comment by matiasilva** [comment]
This might be a TURN error. Have you installed a TURN server? The bbb-install.sh script does this for you if you so choose but you may have installed in a different way.

**Comment by derek-shnosh** [comment]
Got over the dance, redeployed the server with an IP directly in our external subnet and setup UFW accordingly so we can lab and validate that its viable and get CTO signoff.
