### ISSUE TITLE
Bug - Private room - createBreakoutRoom - randomlyAssign - does not work

### ISSUE THREAD

**Issue by aguerson** [bigbluebutton/bigbluebutton#9805]
**Is your feature request related to a problem? Please describe.**
The button "randomlyAssign" to create private room ( BreakoutRoom ) seems to not working

**Describe the solution you'd like**
Create a conf with n users
Create private room ( BreakoutRoom )
Populate the private with the button "randomlyAssign"
Assign an user in the different private room randomly

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by matiasilva** [comment]
Seems to work for me. In any case, this is not an enhancement. It is a bug.

**Comment by aguerson** [comment]
"Seems to work for me. " With auth user ? guest user ?

**Comment by matiasilva** [comment]
I've only tested with auth users as guest users are limited in functionality. Tested by starting the room with Greenlight. Also, change the tag to be "bug".

**Comment by aguerson** [comment]
Seems OK with 2.2.25
