### ISSUE TITLE
Private room ( BreakoutRoom ) - Capabilities with users connected with their phone number only

### ISSUE THREAD

**Issue by aguerson** [bigbluebutton/bigbluebutton#9806]
**Is your feature request related to a problem? Please describe.**
You can't create/use the private room with a phone number connected throught freeswitch to a conf

**Describe the solution you'd like**
Create a conf with user connected with their browser and user connected with their phone number throught freeswitch
Create private rooms
Assign user ( from browser ) and user ( with phone number ) to a private room

**Describe alternatives you've considered**
You could create a specific context ( freeswitch/asterisk specifications ) to isolate the private room. The user who came with his phone will be redirected automaticaly on this private room with the switch of the context ( diaplan ).

**Additional context**
-

**Comment by pedrobmarin** [comment]
Merging with https://github.com/bigbluebutton/bigbluebutton/issues/8586
