### ISSUE TITLE
Screen share does not do anything at all, on firefox or chome. New install on Ubuntu 16 VM

### ISSUE THREAD

**Issue by nigel-dewar** [bigbluebutton/bigbluebutton#9808]
**Describe the bug**
Brand new install, run fine, log in as presenter, hit screen share.... and nothing. No warning, no error, but certainly no pop up to select screen to share. 

**To Reproduce**
Run up a fresh BBB server using a VM, and login as a presenter into one of the tests, try to share screen.

**Expected behavior**
Should fire up a pop up window in browser to allow presenter to select thier share screen options

**Actual behavior**
absolutely nothing, on either chrome or firfox, from either a Mac OS PC, or an Ubuntu 20.04 desktop. 

**Screenshots**
Dont really need to provide screen shots, its pretty well explained

**BBB version (optional):**
Brand new version just run up tonight

**Desktop (please complete the following information):**
 - OS: Ubuntu Desktop 20.04, Mac Catalina 
 - Browser [Chrome, firefox] on both Ubuntu and Mac

**Additional context**
New to BBB, trying it out, I googled expecting to find the answer to this but found nothing. Every indication and article and video I found says this just works, and no-one says anything about any special changes required to the install to have this feature working.

If there is some special setup required, the software should say so. It should show an error saying you need to do this or that, or install extra stuff in the browser or whatever. As it is, it just doesnt work, it fails silently with no reason

soooo, Im logging this as a bug. 

cheers

**Comment by basisbit** [comment]
For support requests, please use the [forum / mailing list](https://groups.google.com/forum/#!forum/bigbluebutton-setup). This issue tracker here is only for BBB development related issues. Sorry.
