### ISSUE TITLE
Attendee made presenter minimises the presentation makes the moderator disconnect

### ISSUE THREAD

**Issue by GhaziTriki** [bigbluebutton/bigbluebutton#9810]
**Describe the bug**
When an attendee is made presenter, minimising the presentation show an error the to moderator and disconnects him from the audio conference. Impossible to rejoin the audio without reloading the page.

**To Reproduce**
1. Connect 1 user as moderator.
2. Connect 2nd user as attendee.
3. Moderator makes the attendee presenter.
4. The presenter attendee minimises the presentation.
5. The described error occurs.

**Expected behavior**
The moderator should not be disconnected from audio.

**Actual behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/4991088/84296422-aca02380-ab54-11ea-8522-3b3873773073.png)

**BBB version (optional):**
BigBlueButton Server 2.2.16

**Additional context**
I don't have an HTML5 console logs right now but I will provide it as soon as I have it.

**Comment by antobinary** [comment]
@JoVictorNunes are you able to reproduce this on 2.4.4+?

**Comment by JoVictorNunes** [comment]
@antobinary I was not able to reproduce on 2.4.4+. Everything working properly.
