### ISSUE TITLE
Report Bug: unable to share screenshot after some time switch between users

### ISSUE THREAD

**Issue by BaseMax** [bigbluebutton/bigbluebutton#9812]
Hello friends,

Sorry for my typo problem, screenshot means screen sharing...

**Actual behavior**

Two people enter a room.
- The master is with Chromium (Linux)
- And student with Firefox browser (Windows)

They share their monitor screen. They are working on the article, so they switch sharescreen of each other to see his screen.
One time master sharescreen and another time student sharescreen... This will repeat...

**Describe the bug**

Master maybe grant access present to student without stopping his screenshareing.
And it's exactly bug of this system, we did find this after some many tests...

**Screenshots**
Student will not able to share screen after some times.

![1](https://user-images.githubusercontent.com/2658040/84381485-5d163200-abfe-11ea-9468-3d2c55c26226.jpg)

And this will solve by clicking on red place.

![2](https://user-images.githubusercontent.com/2658040/84381566-7a4b0080-abfe-11ea-92ad-1887c522b2a8.jpg)

**BBB version (optional):**

$ sudo bbb-conf --check | grep BigBlueButton
```
BigBlueButton Server 2.2.6 (1871)
```

----------

Thanks to your excellent system, we used this project for a university.

Regards,
Max Base

**Comment by basisbit** [comment]
This looks like some security setting of your webbrowser or a bug in firefox. There is nothing BigBlueButton can do about this. Please instead create a bug report at the firefox issue tracker.
https://bugzilla.mozilla.org/describecomponents.cgi?product=Firefox

I can not reproduce the problem using Google Chrome or Chromium or Microsoft Edge.
