### ISSUE TITLE
systemd_start.sh and bbb-apps-akka error

### ISSUE THREAD

**Issue by ahasanaki** [bigbluebutton/bigbluebutton#9813]
[log-error.txt](https://github.com/bigbluebutton/bigbluebutton/files/4764901/log-error.txt)
hi;
when room is running with multiple participant, some error logs on syslog (See attach);
After an hour of Running the room, the server is very slow and new users cannot log in. Finally, after a while, all users fall out (the speed of sending chat slows down and ...)
server resources(RAM-CPU-Disk) is free
 and this commands does not show any error
bbb-conf --check
bbb-conf --status

my BigBlueButton Version is 2.2.4

**Comment by basisbit** [comment]
For support requests, please use the [forum / mailing list](https://groups.google.com/forum/#!forum/bigbluebutton-setup). This issue tracker here is only for BBB development related issues. Sorry.

Before asking for support in the forum, please first update your BigBlueButton install.
