### ISSUE TITLE
PDF processing file stuck

### ISSUE THREAD

**Issue by jesusvaldivia** [bigbluebutton/bigbluebutton#9815]
When a PDF file of a recording is processed, the process remains stuck for hours

<img width="967" alt="Screen Shot 2020-06-11 at 2 43 09 PM" src="https://user-images.githubusercontent.com/7368641/84434117-0bb57500-abf5-11ea-8a4c-6d1995e3a12b.png">
Log file: 

<img width="909" alt="Screen Shot 2020-06-11 at 3 03 27 PM" src="https://user-images.githubusercontent.com/7368641/84434108-09531b00-abf5-11ea-8966-4ef73e1fe0e1.png">

**Comment by basisbit** [comment]
For support requests, please use the [forum / mailing list](https://groups.google.com/forum/#!forum/bigbluebutton-setup). This issue tracker here is only for BBB development related issues. Sorry.

**Comment by jesusvaldivia** [comment]
The problem is related to the metadata of the pdf file, when deleting the metadata the file is processed.

It is possible to add this functionality directly in Bigbluebutton?

**Comment by matiasilva** [comment]
Sorry, exactly what functionality do you want to add?

**Comment by basisbit** [comment]
@jesusvaldivia could you please provide a sample file which causes the problem?

**Comment by jesusvaldivia** [comment]
> Sorry, exactly what functionality do you want to add?

Clean file metadata before it is processed

**Comment by matiasilva** [comment]
Please do share an example of a problematic file.

**Comment by jesusvaldivia** [comment]
I cannot share a private file here, but I followed these instructions:
 https://blog.joshlemon.com.au/protecting-your-pdf-files-and-metadata/

**Comment by jesusvaldivia** [comment]
Here, some metadata details:

<img width="795" alt="Screen Shot 2020-07-07 at 12 45 46 AM" src="https://user-images.githubusercontent.com/7368641/86721144-51464180-bfeb-11ea-9d04-19ade558b952.png">
