### ISSUE TITLE
Be Able To Move Around Webcams On Left Or Right of Presentation

### ISSUE THREAD

**Issue by jingwenw** [bigbluebutton/bigbluebutton#9816]
**Is your feature request related to a problem? Please describe.**
Currently, with 2 or more webcams, the webcams are only be placed on top or bottom. When the presenter upload a portrait file, the presentation looks very vertically squeezed. Meanwhile, there will be plenty blank space on left or right to the presentation. - The webcams should be able to moved to those space, and should be able to floating over the presentation to make best use of it.

**Describe the solution you'd like**
The users should be able to move around the webcams to wherever is convenient, to get the best view of the screen. And the system should be able to automatically figure out the best positions, based on the presentation area, by default.

**Describe alternatives you've considered**
No workaround found

**Additional context**
This feature request is to make the best use of the available view space.

**Comment by ffdixon** [comment]
In the upcoming BigBlueButton 2.3, you'll have the ability to move the webcams to left/right as well.

**Comment by jingwenw** [comment]
Great - thanks for the heads-up!

**Comment by antobinary** [comment]
This behaviour exists onBigBlueButton 2.3
