### ISSUE TITLE
Modify only the html5 client 

### ISSUE THREAD

**Issue by acevedo93** [bigbluebutton/bigbluebutton#9818]
Hello I need to make some visual changes to the html5 client, how can I do this quickly without having to install the whole development environment, we already have a server with big blue button installed, I would like to connect remotely to that server, what configurations should I have? should I have the whole environment installed on my local machine to make only some visual changes?

Thank you all.

**Comment by basisbit** [comment]
For support requests, please use the [forum / mailing list](https://groups.google.com/forum/#!forum/bigbluebutton-setup). This issue tracker here is only for BBB development related issues. Sorry.

Also, please use the search to find answers to the same question which was answered already a couple of times.

**Comment by FarzadKarkhani** [comment]
@basisbit  Can you please share a link to the correct answer? I really couldn't find anything!
