### ISSUE TITLE
web cam dialog text not showing using android native webview 

### ISSUE THREAD

**Issue by anilthummar** [bigbluebutton/bigbluebutton#9819]
When we have an open camera from BBB meeting in a web view in android that time getting Error like 

**Error :libc: Access denied finding property "vendor.camera.aux.packagelist"**

and also check the screenshot:

![image_2020_06_12T07_23_21_735Z](https://user-images.githubusercontent.com/7361686/84476549-f18a9e00-acab-11ea-9695-49846274e0ff.png)
![image_2020_06_12T07_24_02_437Z](https://user-images.githubusercontent.com/7361686/84476556-f3546180-acab-11ea-980e-f277de10fa5b.png)

**Comment by aolee** [comment]
Not a BBB issue. 

This is an Android Webview bug since 2016 and no fix yet till now => https://bugs.chromium.org/p/chromium/issues/detail?id=669492

However, you can do a quick hack to force a label in js file.

**Comment by anilthummar** [comment]
@aolee 
thanks for your updates  and let me check and update you

**Comment by anilthummar** [comment]
@aolee 
its not working

**Comment by anilthummar** [comment]
> Not a BBB issue.
> 
> This is an Android Webview bug since 2016 and no fix yet till now => https://bugs.chromium.org/p/chromium/issues/detail?id=669492
> 
> However, you can do a quick hack to force a label in js file.
> 
> ![edited](https://user-images.githubusercontent.com/700718/84488232-77b9db00-acd2-11ea-84b3-f67aa9d56fff.png)

ok Thank you @aolee ,
can you tell me Where I can add this code in an android side or in the web side

**Comment by basisbit** [comment]
closing this because it is not a bbb development issue. You can continue using this issue to exchange information, it just won't show up as a TODO / new issue any more.

**Comment by MJahanzaibKhan** [comment]
where I writing a code basically I'm facing the same issue
