### ISSUE TITLE
Make mailing lists more accessible to users without google accounts

### ISSUE THREAD

**Issue by decentral1se** [bigbluebutton/bigbluebutton#9820]
**Is your feature request related to a problem? Please describe.**

I've tried twice to sign up on bigbluebutton-setup mailing list and have been rejected. I don't have a google account so it is basically very hard to find out how to sign up and then there is no way to tell the admin that I am not a spammer, so I simply can't get access.

Have you all considered using a Discourse or something that is more accessible?

(Yeah, sorry to abuse the issues like this but how else can I raise this point!?)

**Describe the solution you'd like**

More accessible community support channels.

**Describe alternatives you've considered**

Discourse and Flarum are excellent free software forums.

**Additional context**

If someone could add me on the bigbluebutton-setup mailing list that would be nice :sweat_smile:

**Comment by basisbit** [comment]
> tried twice to sign up on bigbluebutton-setup mailing list and have been rejected

Join requests without any reason text get declined to reduce spam. Majority of people have Google accounts. Any further discussion about this should happen on the developer mailing list. This issue tracker is only for bbb development tasks/issues. Sorry.

**Comment by decentral1se** [comment]
Another person who got locked out https://meta.discourse.org/t/bigbluebutton-video-conference/148050/10.

**Comment by antobinary** [comment]
I think this is a very valid point @decentral1se 
The main issue I see is filtering spam if we do not tie the posts to an account.
If we were to allow questions coming from Discourse or Flarum, how do we prevent duplication of info/responding effort...

I would like to see progress in this direction, so I think I will re-open this issue even though this is not a direct development issue.

**Comment by basisbit** [comment]
Is it possible to edit the description text of the google groups so people know that they have to fill in the join request description? Is it possible to set up google forum so that it sends emails to those who were declined?

**Comment by antobinary** [comment]
I only have partial visibility on the settings of that group. Pinging @ffdixon to try to address/comment

**Comment by matiasilva** [comment]
This is a tricky issue but one worth tackling. The description is in my opinion as clear as can be. It has loads of >>>>>  <<<<<<< to direct people's attention to what they need to fill in. Perhaps what we should do is provide a space for people to email in case they get rejected by accidentally missing something. I'm not sure adding a new tool to the basket is the right way to go, it might lead to further confusion.

**Comment by decentral1se** [comment]
Just to clarify, if you don't have a Google account then it is a Pain In The Ass to sign-up. It is not clear at all. You need to search around online for a bit and then for a specific email address which you can figure out to add a `+subscribe` and then which URL works? (`@googlegroups.com` or `groups.google.com`?) and so on. I would appreciate an addition to https://bigbluebutton.org/support/community/ to clarify how to sign-up without a Google account. I think the mail is `bbb-setup+subscribe@googlegroups.com` (and then include a body text as noted above).

As an example of a successful use of Discourse as a community forum alongside the issue development tracker, see https://discourse.drone.io, which uses Github login details but there are other options. Instead of having multiple mailing lists and all that permissions situation, you could consolidate the place where people come to talk about BBB.

:+1:

**Comment by basisbit** [comment]
Please sign up with a Google account - that ensures that there is only very little amount of spam.... This is mostly a decision made to reduce workload on project maintainers.
(Of course, you won't like this answer because your religion is that everything should be decentralized according to your name 😄 )

**Comment by decentral1se** [comment]
Please allow to easily sign up without a Google account, that's why the ticket exists, that is why the ticket was re-opened. It is not religious dogma for community members to want to avoid a vendor locked in discussion platform.

**Comment by mtsonline** [comment]
hi,

I signed up for all groups without google account and can tell that it really is not easy to find the correct form ... so it would make sense to add the url to the subscription form directly to the description.
generally it is not a problem to subscribe without google account if you got to the right form.

**Comment by matiasilva** [comment]
Hi @mtsonline, could you share what steps you took so those who don't have Google accounts know where to start?

**Comment by mtsonline** [comment]
sure :-)
You open ...
https://groups.google.com/group/bigbluebutton-dev/subscribe
which redirects to...
https://groups.google.com/forum/#!forum/bigbluebutton-dev/join

additionally you have to make sure that the language still is EN - because other languages seem to have a bug when subscribing to the list. At my first attempt to subscribe I did not realize this and had several declines from the moderators which could not approve me.

hth
Martin
