### ISSUE TITLE
Problems with recordings

### ISSUE THREAD

**Issue by Mdmx-max** [bigbluebutton/bigbluebutton#9821]
**Describe the bug**
Recordings aren't publishing now. Two days ago after blackout in our server room, I've noticed, that recordings stopped publish automatically and even after --rebuild records are don't viewed correctly. I mean some records are published without audio stream, some have problems with recorded cameras. Even though all required files are on their places (/var/bigbluebutton/recording/raw/ audio, video, screenshare, events.xml). On screenshots there is information during --rebuild
I have no idea, where to start from.

**To Reproduce**
Start any room and record, complete both. Receive no output (record)

**Expected behavior**
I expect that new record will publish automatically and without bugs

**Actual behavior**
But it didn't

**Screenshots**
![RUZhymB-mJ4](https://user-images.githubusercontent.com/66405582/84502467-0c1b4200-acc1-11ea-9007-1241037d9959.jpg)
![_yswKa7AnW8](https://user-images.githubusercontent.com/66405582/84502473-0de50580-acc1-11ea-9573-147ac6a6ae2b.jpg)

**Comment by WhiteAls** [comment]
I have similar issue with sudden power loss. Files are stuck in /var/kurento and /var/freeswitch and eventually during other meetings I faced 0 usable free space on the drive.
I'm not sure how this are affect BBB (besides broken recordings), but files definitely SHOULD NOT jam this folder - they need to be moved or deleted.

**Comment by matiasilva** [comment]
Have you checked if the bbb-rap-* workers are running? Is the bbb-record-core.timer running? Are there any .done files in /var/bigbluebutton/<relevant directory>?

**Comment by ffdixon** [comment]
See also

 https://docs.bigbluebutton.org/dev/recording.html#troubleshooting
