### ISSUE TITLE
Installation bbb2.2.17 problem connection

### ISSUE THREAD

**Issue by labretagne** [bigbluebutton/bigbluebutton#9822]
Hello,
I installed bbb2.2.17. When I launch my browser with the url, the presentation page is displayed correctly. By cons, when I click on "join" then appears ... and later "Error 404".
Likewise, I started the greenlight installation procedure and when I place the order:
docker run --rm --env-file .env bigbluebutton / greenlight: v2 bundle exec rake conf: check
Checking environment: Passed
Checking Connection: Failed
The connection with bigbluebutton is not done.
I tried several solutions but nothing works and I can't find it.

Here is the status of my installation:

# bbb-conf --check

BigBlueButton Server 2.2.17 (1759)
                    Kernel version: 4.4.0-184-generic
                      Distribution: Ubuntu 16.04.6 LTS (64-bit)
                            Memory: 16431 MB
                         CPU cores: 8

/usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties (bbb-web)
       bigbluebutton.web.serverURL: https://bigbluebutton2.xxxxxxxxxxx
                defaultGuestPolicy: ALWAYS_ACCEPT
                 svgImagesRequired: true

/ etc / nginx / sites-available / bigbluebutton (nginx)
                       server name: $ request_uri
                              port: 80, [::]: 80
                              port: 443 ssl
                    bbb-client dir: / var / www / bigbluebutton

/var/www/bigbluebutton/client/conf/config.xml (bbb-client)
                Test port (tunnel): rtmp: //bigbluebutton2.xxxxxxxxxxx
                              red5: bigbluebutton2.xxxxxxxxxxx
              useWebrtcIfAvailable: true

/opt/freeswitch/etc/freeswitch/vars.xml (FreeSWITCH)
                       local_ip_v4: 127.0.0.1
                   external_rtp_ip: stun: stun.freeswitch.org
                   external_sip_ip: stun: stun.freeswitch.org

/opt/freeswitch/etc/freeswitch/sip_profiles/external.xml (FreeSWITCH)
                        ext-rtp-ip: $$ {local_ip_v4}
                        ext-sip-ip: $$ {local_ip_v4}
                        ws-binding:
                       wss-binding:: 7443

/var/www/bigbluebutton/check/conf/config.xml (client check)
                      client check: bigbluebutton2.xxxxxxxxxxx

/usr/local/bigbluebutton/core/scripts/bigbluebutton.yml (record and playback)
                     playback_host: bigbluebutton2.xxxxxxxxxxx
                 playback_protocol: http
                            ffmpeg: 4.2.2-1bbb1 ~ ubuntu16.04

/etc/bigbluebutton/nginx/sip.nginx (sip.nginx)
                        proxy_pass: 10.192.211.34

/usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml (Kurento SFU)
                        kurento.ip: 10.192.211.34
                       kurento.url: ws: //127.0.0.1: 8888 / kurento
                    kurento.sip_ip: 127.0.0.1
                    localIpAddress: 10.192.211.34
               recordScreenSharing: true
                     recordWebcams: true
                  codec_video_main: VP8
               codec_video_content: VP8

/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml (HTML5 client)
                             build: 937
                        kurentoUrl: wss: //bigbluebutton2.xxxxxxxxxxx/bbb-webrtc-sfu
                  enableListenOnly: true

# Potential problems described below
# IP does not match:
# IP from ifconfig: 10.192.211.34
# / etc / nginx / sites-available / bigbluebutton: $ request_uri
# Warning: API URL IPs do not match host:
#
# IP from ifconfig: 10.192.211.34
# /var/lib/tomcat7/demo/bbb_api_conf.jsp: bigbluebutton2.xxxxxxxxxxx

.................................................. ..............................
# Error: Could not connect to the configured hostname / IP address
#
# https://bigbluebutton2.xxxxxxxxxxx/
#
# If your BigBlueButton server is behind a firewall, see FAQ.

nc: getaddrinfo: Temporary failure in name resolution
# Error: Unable to connect to port 1935 (RTMP) on $ request_uri

# Warning: The API demos are installed and accessible from:
#
# https://bigbluebutton2.xxxxxxxxxxx
#
# and
#
# https://bigbluebutton2.xxxxxxxxxxx/demo/demo1.jsp
#
# These API demos allow anyone to access your server without authentication
# to create / manage meetings and recordings. They are for testing purposes only.
# If you are running a production system, remove them by running:
#
# apt-get purge bbb-demo

# Warning: The client self check is installed and accessible from:
#
# https://bigbluebutton2.xxxxxxxxxxx/check
#

# Error: Unable to reach default URL for presentation:
#
# https://bigbluebutton2.xxxxxxxxxxx/default.pdf
#
# Check value for beans.presentationService.defaultUploadedPresentation in
# /usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties

bbb-conf --status -> everything is active

Please help me run BBB2

**Comment by labretagne** [comment]
in the logs I have this:

   - Exceptions found in / var / log / bigbluebutton -
/var/log/bigbluebutton/bbb-web.log:2020-06-12T15:46:14.871+02:00 WARN ilcprotocol.ConnectionWatchdog - Cannot reconnect: io.netty.channel.AbstractChannel $ AnnotatedConnectException: Connection refused: /127.0 .0.1: 6379
/var/log/bigbluebutton/bbb-web.log:2020-06-12T15:46:14.872+02:00 WARN ilcprotocol.ConnectionWatchdog - Cannot reconnect: io.netty.channel.AbstractChannel $ AnnotatedConnectException: Connection refused: /127.0 .0.1: 6379
/var/log/bigbluebutton/bbb-web.log:2020-06-12T15:46:14.872+02:00 WARN ilcprotocol.ConnectionWatchdog - Cannot reconnect: io.netty.channel.AbstractChannel $ AnnotatedConnectException: Connection refused: /127.0 .0.1: 6379
/var/log/bigbluebutton/bbb-web.log:2020-06-12T15:46:14.875+02:00 WARN ilcprotocol.ConnectionWatchdog - Cannot reconnect: io.netty.channel.AbstractChannel $ AnnotatedConnectException: Connection refused: /127.0 .0.1: 6379
/var/log/bigbluebutton/bbb-web.log:2020-06-12T15:46:14.875+02:00 WARN ilcprotocol.ConnectionWatchdog - Cannot reconnect: io.netty.channel.AbstractChannel $ AnnotatedConnectException: Connection refused: /127.0 .0.1: 6379

**Comment by basisbit** [comment]
For support requests, please use the [forum / mailing list](https://groups.google.com/forum/#!forum/bigbluebutton-setup). This issue tracker here is only for BBB development related issues. Sorry.
