### ISSUE TITLE
Can't hear audio in main room after using audio in breakout

### ISSUE THREAD

**Issue by antobinary** [bigbluebutton/bigbluebutton#9826]
Easiest steps to reproduce:

I am in Demo room with 2 users: Anton-computer and Anton-phone. I will create breakouts and only bring Anton-computer to Room 1
￼
I join full audio with Anton-phone in main room and full audio with Anton-computer in Room 1
Then I join full audio for Anton-computer in main room (and I mute myself) -- note: here listenOnly will also hit the issue
Now in main room I hear Anton-phone speak
I will end breakouts and I will no longer hear Anton-phone even though he speaks

Result - in the main room you cannot hear anybody's audio.
Note: I tried many different versions of this.
** If I close the tab for the breakout rather than end the meeting, the audio in the main room is not damaged**
Other types of audio in the main room can still be heard, for example the audio of a shared youtube video

Relevant sections of code
https://github.com/bigbluebutton/bigbluebutton/blob/v2.2.x-release/bigbluebutton-html5/imports/ui/components/audio/container.jsx#L131

I do not see any AudioManager function get executed in the main room on Breakout closing

**Comment by mariogasparoni** [comment]
@antobinary , this can be closed. Breakout audio has been improved in 2.3.0 and there are no reports of this.

**Comment by prlanzarin** [comment]
This is still reproducible in Chrome.

Then again, it's a Blink issue.

**Comment by ffdixon** [comment]
@MaximKhlobystov Can we test this in 2.5 to see if its still an issue.
