### ISSUE TITLE
ios native support for bbb using kurento ios sdk 

### ISSUE THREAD

**Issue by piyusharorawork** [bigbluebutton/bigbluebutton#9830]
**No support for webview for ios**
When I went though the docs of bbb , I realize that bbb video conferencing  is built on top of kurento . Currently bbb doesnot have support any native platform other than web . We tried using webview but for ios webview doesnot support webrtc and hence we cannot give native ios experience to our users. 

**Kurento ios sdk with bbb**
Since kurento has the ios sdk (https://kurento-ios.readthedocs.io/_/downloads/en/latest/pdf/)
Is there any way to make kuernto ios sdk work with big blue button . 

Any help will be appreciated

**Comment by basisbit** [comment]
Kurento is only used for webcam and screen sharing. Thus, the kurenro sdk won't be of much help. Anyways, this discussion should be done in the developer forum / mailing list, not here in the issue tracker of bbb.
