### ISSUE TITLE
404 error after bbb installation in nginx/1.10.3 (Ubuntu)

### ISSUE THREAD

**Issue by reza-ba99** [bigbluebutton/bigbluebutton#9839]
i was tried because in install 4 setup
i installed Greenlight with command in github, but after install in get error 404 in nginx/1.10.3 (Ubuntu) and on url have https://bbb.test.com/b, 

BigBlueButton Server 2.2.17 (1992)
                    Kernel version: 4.4.0-184-generic
                      Distribution: Ubuntu 16.04.6 LTS (64-bit)
                            Memory: 8174 MB
                         CPU cores: 4

/usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties (bbb-web)
       bigbluebutton.web.serverURL: https://45.92.94.78
                defaultGuestPolicy: ALWAYS_ACCEPT
                 svgImagesRequired: true

/etc/nginx/sites-available/bigbluebutton (nginx)
                       server name: kbb.karinotech.com
                              port: 80, [::]:80
                              port: 443 ssl
                    bbb-client dir: /var/www/bigbluebutton

/var/www/bigbluebutton/client/conf/config.xml (bbb-client)
                Port test (tunnel): rtmp://45.92.94.78
                              red5: 45.92.94.78
              useWebrtcIfAvailable: true

/opt/freeswitch/etc/freeswitch/vars.xml (FreeSWITCH)
                       local_ip_v4: 45.92.94.78
                   external_rtp_ip: stun:stun.freeswitch.org
                   external_sip_ip: stun:stun.freeswitch.org

/opt/freeswitch/etc/freeswitch/sip_profiles/external.xml (FreeSWITCH)
                        ext-rtp-ip: $${local_ip_v4}
                        ext-sip-ip: $${local_ip_v4}
                        ws-binding: :5066
                       wss-binding: 45.92.94.78:7443

/usr/local/bigbluebutton/core/scripts/bigbluebutton.yml (record and playback)
                     playback_host: 45.92.94.78
                 playback_protocol: https
                            ffmpeg: 4.2.2-1bbb1~ubuntu16.04

/etc/bigbluebutton/nginx/sip.nginx (sip.nginx)
                        proxy_pass: 45.92.94.78

/usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml (Kurento SFU)
                        kurento.ip: 45.92.94.78
                       kurento.url: ws://127.0.0.1:8888/kurento
                    kurento.sip_ip: 45.92.94.78
                    localIpAddress: 45.92.94.78
               recordScreenSharing: true
                     recordWebcams: true
                  codec_video_main: VP8
               codec_video_content: VP8

/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml (HTML5 c                                                                                        lient)
                             build: 937
                        kurentoUrl: wss://45.92.94.78/bbb-webrtc-sfu
                  enableListenOnly: true

# Potential problems described below
................................................................................
# Error: Could not connect to the configured hostname/IP address
#
#    https://45.92.94.78/
#
# If your BigBlueButton server is behind a firewall, see FAQ.

# Error: Unable to reach default URL for presentation:
#
#    https://45.92.94.78/default.pdf
#
# Check value for beans.presentationService.defaultUploadedPresentation in
#   /usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties

**Comment by ffdixon** [comment]
Can we get you to post this question to the bigbluebutton-greenlight mailing list, see

  https://groups.google.com/g/bigbluebutton-greenlight

(Be sure to give a reason when you join so we can distinguish your application from that of a SPAM bot).

The community can help you in the mailing list.  If in helping out we find there is a problem with Greelight or BigBlueButton, we can open an issue to track and fix it.
