### ISSUE TITLE
Microphone not working when privacy.resistFingerprinting is set (Firefox)

### ISSUE THREAD

**Issue by Socob** [bigbluebutton/bigbluebutton#9841]
**Describe the bug**
On Firefox, if the setting `privacy.resistFingerprinting` is set to `true` (`about:config`), BigBlueButton fails to use the microphone even though microphone access is granted when the permissions prompt appears. When `privacy.resistFingerprinting` is `false`, everything works correctly.

**To Reproduce**
1. Join a room on https://test.bigbluebutton.org/
2. Click on “Microphone”.
3. Click “Allow” in the browser prompt requesting access to the microphone.

**Expected behavior**
The echo test should appear and microphone input should be played back to the user.

**Actual behavior**
After allowing access to the microphone, the error message

> There was an issue with your media devices
> 
> Did you give permission for access to your microphone? Note that a dialog should appear when you try to join audio, asking for your media device permissions, please accept that in order to join the audio conference. If that is not the case, try changing your microphone permissions in your browser's settings.

appears.

The JavaScript console output shows the following:

> [14:29:12:0400] DEBUG: clientLogger: Initial connection status change. status: connecting, connected: false https://test.bigbluebutton.org/html5client/3ebaf78536a9522e1434e5d9b0d3923337df5707.js?meteor_js_resource=true:121:1028897 3ebaf78536a9522e1434e5d9b0d3923337df5707.js:9:342209
> [14:29:14:0300] DEBUG: clientLogger: Initial connection status change. status: connected, connected: true https://test.bigbluebutton.org/html5client/3ebaf78536a9522e1434e5d9b0d3923337df5707.js?meteor_js_resource=true:121:1028897 3ebaf78536a9522e1434e5d9b0d3923337df5707.js:9:342209
> [14:29:14:0300]  INFO: clientLogger: Connection to Meteor took 1.90s https://test.bigbluebutton.org/html5client/3ebaf78536a9522e1434e5d9b0d3923337df5707.js?meteor_js_resource=true:121:1029068 3ebaf78536a9522e1434e5d9b0d3923337df5707.js:9:342209
> [14:29:14:0700]  INFO: clientLogger: Log information about the client https://test.bigbluebutton.org/html5client/3ebaf78536a9522e1434e5d9b0d3923337df5707.js?meteor_js_resource=true:121:1030239 3ebaf78536a9522e1434e5d9b0d3923337df5707.js:9:342209
> [14:29:14:0700]  INFO: clientLogger: User successfully went through main.joinRouteHandler https://test.bigbluebutton.org/html5client/3ebaf78536a9522e1434e5d9b0d3923337df5707.js?meteor_js_resource=true:121:1031107 3ebaf78536a9522e1434e5d9b0d3923337df5707.js:9:342209
> [14:29:14:0800]  INFO: clientLogger: re-send validateAuthToken for delayed authentication https://test.bigbluebutton.org/html5client/3ebaf78536a9522e1434e5d9b0d3923337df5707.js?meteor_js_resource=true:121:1159124 3ebaf78536a9522e1434e5d9b0d3923337df5707.js:9:342209
> [14:29:15:0300]  INFO: clientLogger: re-send validateAuthToken for delayed authentication https://test.bigbluebutton.org/html5client/3ebaf78536a9522e1434e5d9b0d3923337df5707.js?meteor_js_resource=true:121:1159124 3ebaf78536a9522e1434e5d9b0d3923337df5707.js:9:342209
> [14:29:15:0600]  INFO: clientLogger: Calling init streamers functions https://test.bigbluebutton.org/html5client/3ebaf78536a9522e1434e5d9b0d3923337df5707.js?meteor_js_resource=true:121:1159415 3ebaf78536a9522e1434e5d9b0d3923337df5707.js:9:342209
> [14:29:15:0600]  INFO: clientLogger: initCursorStreamListener called https://test.bigbluebutton.org/html5client/3ebaf78536a9522e1434e5d9b0d3923337df5707.js?meteor_js_resource=true:121:1007212 3ebaf78536a9522e1434e5d9b0d3923337df5707.js:9:342209
> [14:29:15:0900] DEBUG: clientLogger: initCursorStreamListener called https://test.bigbluebutton.org/html5client/3ebaf78536a9522e1434e5d9b0d3923337df5707.js?meteor_js_resource=true:121:1007627 3ebaf78536a9522e1434e5d9b0d3923337df5707.js:9:342209
> [14:29:16:0300]  INFO: clientLogger: Subscriptions are ready https://test.bigbluebutton.org/html5client/3ebaf78536a9522e1434e5d9b0d3923337df5707.js?meteor_js_resource=true:121:1201920 3ebaf78536a9522e1434e5d9b0d3923337df5707.js:9:342209
> [14:29:16:0900]  INFO: clientLogger: Client loaded successfully https://test.bigbluebutton.org/html5client/3ebaf78536a9522e1434e5d9b0d3923337df5707.js?meteor_js_resource=true:121:978476 3ebaf78536a9522e1434e5d9b0d3923337df5707.js:9:342209
> [14:29:33:0700] ERROR: clientLogger: Error getting microphone - {TypeError: n is undefined} https://test.bigbluebutton.org/html5client/3ebaf78536a9522e1434e5d9b0d3923337df5707.js?meteor_js_resource=true:121:1153083 3ebaf78536a9522e1434e5d9b0d3923337df5707.js:9:342209

**BBB version (optional):**
Whatever version is installed on https://test.bigbluebutton.org/ as of today (it says “Version 2.2-RC” at the bottom).

**Desktop:**
 - OS: Linux (Ubuntu)
 - Browser: Firefox v77.0.1

**Comment by ffdixon** [comment]
> Whatever version is installed on https://test.bigbluebutton.org/ as of today (it says “Version 2.2-RC” at the bottom).

https://test.bigbluebutton.org/ is actually running the latest build, but we have a custom landing page for it that was still referencing the `2.2-RC`.  Fixed.

**Comment by prlanzarin** [comment]
Seems like the anti fingerprinting setting obfuscates capture device labels. There's some code that rely on the audio device label to match the media stream to the input device (bad). Correct way would be to fetch the deviceId via the stream's track getSettings return (if available).
So this is something to be tackled in 2.2 I think.
