### ISSUE TITLE
Add a timer and stopwatch to the HTML5 client

### ISSUE THREAD

**Issue by matiasilva** [bigbluebutton/bigbluebutton#9844]
**Describe the solution you'd like**
Add a timer to the presenter toolkit which includes a stopwatch and a conventional count-down timer. A presenter could very easily start this timer via the "+" button in the bottom left hand corner and could choose whether it is visible to all participants or just moderators.

**Describe alternatives you've considered**
There don't seem to be any alternatives that could quite match this level of functionality. One could just start a timer on their phone, but for a seminar/Q&A this doesn't work.

Added this in response to a few issues I've seen and talk on the dev forum.

**Comment by Jossef-767** [comment]
implemented in  https://elos.vc/

![image](https://user-images.githubusercontent.com/2356928/85370963-37f7bc80-b538-11ea-9cd6-cbddff9a5bd0.png)

**Comment by danfelbm** [comment]
> implemented in https://elos.vc/
> 
> ![image](https://user-images.githubusercontent.com/2356928/85370963-37f7bc80-b538-11ea-9cd6-cbddff9a5bd0.png)

Is this development available anywhere?

**Comment by ffdixon** [comment]
Good suggestion and one that we'd like to see in BigBlueButton as well (probably sometime after the upcoming 2.3 release).

**Comment by manavortex** [comment]
@ffdixon: Great! Is there an issue/branch/whatever I can watch so I can be excited more efficiently?

**Comment by parrajeremy** [comment]
Update on this one? Did this make it into 2.3?

**Comment by harika1258** [comment]
> > implemented in https://elos.vc/
> > ![image](https://user-images.githubusercontent.com/2356928/85370963-37f7bc80-b538-11ea-9cd6-cbddff9a5bd0.png)
> 
> Is this development open-source and available for users?

Thank you so much @ffdixon @matiasilva @danfelbm
 I couldn't find how can I set up this feature. could you please help me?
Thanks in advance.

**Comment by antobinary** [comment]
Implemented in BBB 2.7 (currently in release candidate 1 stage)
