### ISSUE TITLE
[Bug] [HTML5] [ipad] Dragging One or More Webcams Does Not Stick To Drop Areas

### ISSUE THREAD

**Issue by aogilvie** [bigbluebutton/bigbluebutton#9847]
**Describe the bug**
Tap and hold a webcam allows drag. User can see the drag zones, but the webcam does not stick to the zone or show the zone highlight.

**To Reproduce**
1. Go to https://test.bigbluebutton.org via iPad (I tested with iOS 13.4.1)
2. Start webcam
3. Drag webcam
4. webcam now floats, and cannot be docked again.

**Expected behavior**
- Should see drop zone or
- At least drop into the zone on hover over.

**Actual behavior**
- webcam now floats above presentation

**Additional context**
When soft debugging noticed:

`./imports/ui/components/media/webcam-draggable-overlay/component.jsx`

```
handleWebcamDragStop(e) {
    const { webcamDraggableDispatch } = this.props;
    const targetClassname = JSON.stringify(e.target.className);
   // targetClassname usually contains 'Top' or 'Bottom'
   // when using touch events it seems the classname is equal to the actual element being dragged, not the zone target element.

    if (targetClassname) {
      // The following fails.
      if (targetClassname.includes('Top')) {
        webcamDraggableDispatch({ type: 'setplacementToTop' });
```

**Comment by matiasilva** [comment]
On desktop, if you have only one camera, it will permanently float once you detach it. I expect the same to be for mobile. Can you try with two cameras?

**Comment by aogilvie** [comment]
On desktop you can re-dock. iPad you cannot.

It is not possible to add two people to the same meeting on https://test.bigbluebutton.org AFAIK.

**Comment by matiasilva** [comment]
My bad, I've just checked and you indeed can redock. Try the same on the demo server: https://demo.bigbluebutton.org

**Comment by aogilvie** [comment]
I won't be using that site, because it requires a signup. However, we ran the code base 2.2.17 on our own servers and can verify the same issues. I was just highlighting test.bigbluebutton.org because that is running the latest codebase AFAIK.

**Comment by prlanzarin** [comment]
Yeah, test is running latest. @aogilvie you were running RC-5/6 before, right? Did it happen back then? Knowing that helps doing a bisect.

**Comment by aogilvie** [comment]
I tested the iPad on RC 5/6 iPad drag is not possible or disabled (not sure which, I have not checked this codebase). Nothing happens if I tap and hold.

**Comment by aogilvie** [comment]
A drag issue this specific looks deeper that then webcam-draggable-overlay component itself. One thing I noticed between `v2.2.x-release` (tag 2.2.17) and `master/develop` (2.2RC6), is that code on `mater/develop` uses `PureComponent`. I don't know anything about React myself, but maybe something in that.

https://github.com/bigbluebutton/bigbluebutton/blob/2.2-rc-6/bigbluebutton-html5/imports/ui/components/media/webcam-draggable-overlay/component.jsx#L37

**Comment by matiasilva** [comment]
No worries. Can you instead try on the test-install server using [this](https://mconf.github.io/api-mate/)? I'm curious if the same problem persists with two or more cameras as you can't freely drag two cameras around.

**Comment by prlanzarin** [comment]
Well, actually, any flavor of mobile (tablets of smartphones) shouldn't have drag-and-drop for webcams enabled (because it was always flaky). Am thinking that maybe the mobile check started failing due to some UA change. Will have to check that.

**Comment by aogilvie** [comment]
Could be, I recall the ISMOBILE variable also changed in the same file.
