### ISSUE TITLE
How To Avoid The Tunneling Effect When Sharing Screen

### ISSUE THREAD

**Issue by manish-yadav** [bigbluebutton/bigbluebutton#9849]
Want to avoid seeing that tunneling effect while sharing your screen? jitsi implemented the same in there screen sharing. could we remove it in BBB.

**Comment by matiasilva** [comment]
The tunneling effect cannot be "solved" as you suggest Jitsi has done. It is simply a consequence of you sharing the same screen as the live meeting. A quick Google search yields this: https://support.newrow.com/en/article/how-to-avoid-the-tunneling-effect-when-sharing-your-screen
