### ISSUE TITLE
What BBB release support webcamsDefaultPlacement?

### ISSUE THREAD

**Issue by amguirado73** [bigbluebutton/bigbluebutton#9858]
Hello,

we would like to move from top to left side the webcams area in layout to make the presentation area bigger. We have started to develop a new HTML5 client but we have noted that in the cloned release from git, the config.yml file includes a new variable called webcamsDefaultPlacement(top|left|right|botton). Can anyone explain this feature?. I have seen #9532 issue but is not very well explained. Which BBB version include this feature?.

Thank in advanced.
Regards.

**Comment by basisbit** [comment]
You probably cloned the develop branch, which contains bunch of changes which will be part of bbb 2.3 but are not part of bbb 2.2.x and thus will break compatibility.
If you take a look at [git blame](https://github.com/bigbluebutton/bigbluebutton/blame/41f19a2cd1bc7dae76cbd805cdc3ddfbf1e6ab18/bigbluebutton-html5/imports/ui/components/media/webcam-draggable-overlay/context.jsx), you will find the pull requests for those changes and then understand what these are for.

Please do not post such questions & support requests here in the bbb development issue tracker. Please use the [mailing lists](https://groups.google.com/forum/#!forum/bigbluebutton-users) for such questions instead. Sorry.
