### ISSUE TITLE
entry and exit log

### ISSUE THREAD

**Issue by mailalaki** [bigbluebutton/bigbluebutton#9859]
hi,
is there way to logs entry and exit times of each participant in sessions?

**Comment by svergata** [comment]
BBB has a extensive Log mechanism take a look at /var/log/bbb-apps-akka/bbb-apps-akka.log for example.

**Comment by basisbit** [comment]
For support requests, please use the [forum / mailing list](https://groups.google.com/forum/#!forum/bigbluebutton-users). This issue tracker here is only for BBB development related issues. Sorry.
