### ISSUE TITLE
Hide presentation if the moderator minimizes it

### ISSUE THREAD

**Issue by pbdco** [bigbluebutton/bigbluebutton#9862]
I couldn't find this enhancement request open. 

It would be great if the presentation minimizes/hides for all the connected users in the meeting, if the moderator does it. This feature would work similarly to the zoom/pan functions (if moderator changes them, all the users see the changes).

We have several meetings on wich the presentation is not used or needed at all, and if users that are new into BBB system have to figure out how to minimize it to change the full screen / gallery view to see all the participants. 

Frequently several users doesn't figure out at all how to minimize it and they watch the whole meeting with the presentation unnecessarily on. This happens mostly when they enter to the meeting late so they missed the explanation/recommendation from the moderator to do it. 

Turning it off completely ( autoSwapLayout: true // hidePresentation ) is not an option for us because we have the opposite scenario on which we need to the meetings to start with the presentation on. So having this feature would be the best for each meeting requirement and very useful. 

Thank you in advance @ffdixon

**Comment by matiasilva** [comment]
Exists already: https://docs.bigbluebutton.org/2.2/customize.html#whiteboard-parameters

**Comment by pbdco** [comment]
Hi @matiasilva , could you explain which of these should activate this feature?

```
userdata-bbb_multi_user_pen_only=	
userdata-bbb_presenter_tools=	
userdata-bbb_multi_user_tools=	
```

Thanks!

**Comment by matiasilva** [comment]
My apologies, it's the one right above it.

**Comment by pbdco** [comment]
Thank you @matiasilva 

Actually I found a bug here. When I set restoreOnUpdate: true on setting.yml; if the moderator minimizes the presentation, the participants gets a "blink" (it minimizes for a second and maximizes again). Just the moderator gets the presentation minimized. 

This should be reported @ffdixon

**Comment by KDSBrowne** [comment]
@pbdco  the `resoreOnUpdate` property was only intended to restore minimized presentations of viewers. Having other user presentation's minimize based on the state of the moderators presentation is not part of what this prop currently handles.

The "blink" looks like a bug though.

**Comment by matiasilva** [comment]
Ah I see. My apologies as I had not personally tested this and just read the PR + used the text that was already there in the WIP docs.

**Comment by pbdco** [comment]
Thank you @matiasilva you have been of great help. 

Opened this issue on https://github.com/bigbluebutton/bigbluebutton/issues/9866

Regards

**Comment by matiasilva** [comment]
Closing this issue then as a bug report has been submitted.

**Comment by pbdco** [comment]
> @pbdco the `resoreOnUpdate` property was only intended to restore minimized presentations of viewers. Having other user presentation's minimize based on the state of the moderators presentation is not part of what this prop currently handles.
> 
> The "blink" looks like a bug though.

Hi @KDSBrowne , would it possible to add this feature? This would be a very useful feature in many scenarios.

**Comment by KDSBrowne** [comment]
Hey @pbdco, I would suggest you create a Feature request. The link below should provide some useful information  

https://docs.bigbluebutton.org/support/faq.html#when-will-feature-x-be-implemented

**Comment by pbdco** [comment]
> Hey @pbdco, I would suggest you create a Feature request. The link below should provide some useful information
> 
> https://docs.bigbluebutton.org/support/faq.html#when-will-feature-x-be-implemented

Opened at #9937 @KDSBrowne thanks
