### ISSUE TITLE
Change Feedback Text

### ISSUE THREAD

**Issue by agustinmono** [bigbluebutton/bigbluebutton#9864]
I ve enabled the feedback section when you finish the session, where can I edit the text? I want to add more text or change it to make it more friendly.

Here are some screenshots

http://prntscr.com/t1ivp4
http://prntscr.com/t1ivx7

Thanks

**Comment by matiasilva** [comment]
Hello, thanks for posting. Please move this to https://groups.google.com/forum/#!forum/bigbluebutton-users where your query can be better handled. Thanks.
