### ISSUE TITLE
Generate multiple shared (salt) keys

### ISSUE THREAD

**Issue by pbdco** [bigbluebutton/bigbluebutton#9865]
It would be great to generate multiple salt keys and have the option to manage them (delete/change). This could bring more control to servers that are being used for multiple external plugins like Moodle or Wordpress, etc. 

We are currently using a single BBB server for multiple external plugins like mentioned. If we could generate one key for each external app, we could manage specific shared keys without the need to update all the endpoints / plugins using this server.

**Comment by prashanttalele** [comment]
@pbdco : Have you got any solution to this requirement?
I am also looking for this kind of logical bifurcation between multiple implementations.
This is especially more important when Europe region implementations are targeted.
Anyone from the community, please do let me know if there is any such provision?

Thanks
Prashant
