### ISSUE TITLE
Strings: change "Logout" to "Leave Meeting"

### ISSUE THREAD

**Issue by hex-m** [bigbluebutton/bigbluebutton#9868]
**Is your feature request related to a problem? Please describe.**
Users (especially new once) accidentally end a meeting, when they only want to leave it. Also the "Logout"-Button does not actually perform a logout. It just redirects to the frontend (Greenlight in my case) where the user is still logged in.

**Describe the solution you'd like**
Change the string "Logout" to "Leave Meeting" to make it easier to understand.

**Additional context**
I singled out this request from #9750 to have one feature request per issue. Find additional context and arguments there.

**Comment by gnaegi** [comment]
I add an image to what I think would improve usability of the "end meeting" dialog on request of @matiasilva. The discussion was starte in #9856.

I think renaming "Logout" to "Leave Meeting" is not enough. The problem is IMO that "End meeting" does not imply that the meeting will also be ended for other users. 

What do you think about my mockup?

![better end meeting dialog](https://user-images.githubusercontent.com/53508/85068603-0044e980-b1b3-11ea-9ae9-c0170f28cd96.png)

**Comment by matiasilva** [comment]
Wow. I think that's excellent. It's simple and communicates the consequences of ending the meeting. I would definitely be in favor of this feature. Great work! Are you a developer? You can set up a dev environment here: https://docs.bigbluebutton.org/2.2/dev.html and quickly add this in seeing as an existing confirmation screen already exists. You would simply have to get the names of the participants but other than that, it should be fine to implement. What are other people's thoughts?

**Comment by gnaegi** [comment]
Well, I used to be a more active dev, but in the last few years I am more busy running the business than do actual coding. My company develops OpenOlat, a large Java based learning management system. BBB is our first-class VC (besides others that we support). 

I am very tempted digging into the BBB code base but unfortunately I just don't have the time for it. But I am willing to pay for it. You seem like someone who could do the job, what do you think? Please contact me privately if you are interested!

**Comment by antobinary** [comment]
I am growing on the idea of 'Leave Meeting'. I am tagging it for BBB 2.3 where I would like to see it land. 

@gnaegi - feel free to include this screenshot in 9856 (or better - open a new issue since it's the moderator's POV) - I don't see it there and it's a bit off-topic here.
If there is a taker for the implementation work, please state it somewhere so we know that work is underway and no new takers are needed

**Comment by antobinary** [comment]
And again, I mark it for 2.3 because...

> In all cases, I would recommend renaming considerations to be postponed to BigBlueButton 2.3 since we are very far ahead into version 2.2 (2.2.16 preceded by numerous beta's) and updates to user documentation is likely untimely.

**Comment by matiasilva** [comment]
I'll take this up as a learning exercise in React :)

**Comment by hiroshisuga** [comment]
In Japanese language translation, "Logout" is currently translated to "退室", which means "leave the room". To just avoid the user's confusion, you can simply change the translation to e.g. "verlassen den Raum". I know it's a silly trick but works.

**Comment by mrkeksi** [comment]
@hiroshisuga I had already done that. But then someone else came and reversed that change. It was a nice trick but it does not work forever. Therefore you have to tackle the problem at the root.

I had also rewritten other changes that I think make more sense. (Restrict viewer rights) These were also completely rewritten, which completely represents the meaning of this button and so is not true at all. In german this phrase currently means to restrict participants which includes moderators as well. Which is so however contentwise wrong.

**Comment by hiroshisuga** [comment]
I agree @mrkeksi . The word "Logout" can also be confused with "Sign out".
In japanese transifex, there are only two active translators, thus we discussed and sort of agreed in keeping the "intentionally wrong" translation (at least that's what I understood). 
Another trick is to personally customize the html5 client, which is relatively easy and persistent. 
https://docs.bigbluebutton.org/2.2/dev.html#developing-the-html5-client
I am afraid that your proposal would not be reflected in version 2.2 anyway. Tweaking the app in your own server until 2.3 gets stable is a decent option.
