### ISSUE TITLE
User can talk and hear session, after he left.

### ISSUE THREAD

**Issue by inDane** [bigbluebutton/bigbluebutton#9870]
**Describe the bug**
The GUI shows, that a person left, that person is not in the user list anymore, but can still hear everything and talk in the session.

**To Reproduce**
Unfortunately I cannot state how to reproduce this. I will update this, if I know more.

**Expected behavior**
If a person leaves a conference, that person should not be able to speak or hear the conference.

**Actual behavior**
See the screenshot, the person who is talking, is not part of the user list! He tried to leave the conference, but the Browser seemed to hang. After that, he was not shown anymore, but was able to listen and talk.

**Screenshots**
![bbb_anon](https://user-images.githubusercontent.com/5693407/85015127-bf73b300-b167-11ea-9b93-26c54638654d.jpg)

**BBB version (optional):**
BigBlueButton Server 2.2.17 (1992)

**Additional context**
I've heard of this issue several times since upgrading from 2.2.15. to 2.2.17. It seems like 2.2.15 was working, while 2.2.17 has got this bug.

**Comment by matiasilva** [comment]
Intriguing. Do let us know if you can reproduce this or if it continues to happen.

**Comment by basisbit** [comment]
can confirm that this issue was already reported by a bunch of different server operators. Probably happened by the HTML5 client having a broken state, so that the user session is already removed by meteor, but the freeswitch connection is still alife.

**Comment by steffen-moser** [comment]
I've seen this one time, but months before 2.2.15 or 2.2.17 came out. Most probably between the mid of February and the mid of March 2020. I don't know by heart which version of BBB was active this time. One user with an unstable internet connection (most probably caused by sudden packet loss in a congested 2.4 GHz WiFi channel) has been ejected from the conference several times. One time, when it has happened, he could still hear and speak to us, but his name was not on the other users' lists anymore. I am quite sure that it is related to a broken state caused by sudden packet loss.

**Comment by jibon57** [comment]
Yes, I also faced this problem. As @steffen-moser explain, this happened for me due to sudden connection dropped. I was able to hear everyone but I wasn't in the listed. During my case all the webcams from my end were freezes.

**Comment by einhirn** [comment]
We are actually seeing something like this on 2.2.14 when a user has left the conference, but instead of getting the "You are being forwarded"-Message, they only see the 3 pulsating dots, while they can still hear the session - I don't know about talking.
Not sure whether it's the same issue...

**Comment by basisbit** [comment]
@einhirn thats probably fixed in 2.2.19. Could you please test with that version? Also, when that problem happens, please try tocheck the webbrowser developer console log.

**Comment by maximilianhoecker** [comment]
I can tell this is not fixed in 2.2.20. I got a user report today, that one of my colleagues had a situation were BBB dropped a user from the user list due to a bad connection, but he was still able to hear and talk, as described above. I'll try to get the logs from this timeperiod.

**Comment by maximilianhoecker** [comment]
My team **could actually reproduce this error**. Since I see this as a security problem I'd like not to publish it before resolution. If a BBB-developer wants to investigate this with us, feel free to contact. @ffdixon

**Comment by basisbit** [comment]
@maximilianhoecker please send details to security@bigbluebutton.org

**Comment by steffen-moser** [comment]
I've seen it occurring on BBB-2.2.20 last Wednesday during an oral online exam. The professor had a packet-lossy internet connection due to a congested WiFi link between his computer and his WiFi access point (due to a parallel running Apple Time-Machine backup to a local NAS device). He somehow got BBB into a strange state when trying to reload the browser. He was no visible on the users' list anymore but could still listen and talk. We were not able to reproduce this in a lab setup, yet.

**Comment by ichdasich** [comment]
Just received a similar report by a user; Again, funny loading condition of the webinterface leading to this, issue not reproducible.

**Comment by ffdixon** [comment]
@ichdasich Can you confirm which version you are running.

**Comment by ichdasich** [comment]
Sadly no; Upon re-poking the user he said 'some time ago'. -.-' 

So not really helpful.

Prompted the user to notify me immediately in case it happens again. In case I have some time and motivation in the coming weeks I'll try to make this reproducible.

**Comment by maximilianhoecker** [comment]
We can still reproduce it with version 2.2.29 and the procedure described via mail to security@bigbluebutton.org.

**Comment by steffen-moser** [comment]
In the meanwhile, we are also able to reproduce the problem - even in version 2.2.30. We see it sporadically and when we do, it is always linked to users with bad network connectivity, mainly produced by lossy WLAN. 

I will also send an e-mail to security@bigbluebutton.org.

**Comment by mariogasparoni** [comment]
#11414 fixes this problem for sure. This PR checks if a voice user is also present in the webconference. If not, the user is ejected.

We also improved the way client finished the audio connection, making it close gracefully.
