### ISSUE TITLE
naming for breakout rooms

### ISSUE THREAD

**Issue by deLinhuberin** [bigbluebutton/bigbluebutton#9871]
**Is your feature request related to a problem? Please describe.**
Many of our participants had problems finding the right breakout room. E. g. Assignment by place of residence could not be done by the moderator

**Describe the solution you'd like**
The possibility to give breakout rooms a meaningful name

**Describe alternatives you've considered**

**Additional context**

**Comment by ffdixon** [comment]
This is a good suggestion and has been asked by others.  Thanks for opening an enhancement issue for it.

**Comment by matiasilva** [comment]
I have a rough idea of how to implement this. The breakout rooms are created via the same API command, `create`, so we just have to implement the `name` parameter and connect that to the same UI that pops up for breakout room creation only with extra fields for names. I might look into this.

**Comment by FreeScholar** [comment]
Thank you for looking at this awesome request for an enhancement!

**Comment by aloisogomes** [comment]
@matiasilva API have mention for creation of breakout room, but it aren't created. I don't know why use.

**Comment by matiasilva** [comment]
Well, because currently there's no UI for setting room names.

**Comment by Beltrando** [comment]
> Well, because currently there's no UI for setting room names.

In this case, would it be possible to name it with the name of the first person who joins the breakout room ? This is normally the name of the teacher (or the moderator).

**Comment by rasos** [comment]
UX proposal for thsi feature: The moderator is allowed to set the room names when clicking on one of the rooms in the list: 

![Screenshot_2021-02-10_14-22-15](https://user-images.githubusercontent.com/485723/107515654-9ba82600-6bab-11eb-87a1-01afbf59a9fa.png)

**Comment by rachellawson** [comment]
This sounds very interesting enhancement - we could certainly have benefitted from this feature today at DrupalCon!
