### ISSUE TITLE
external video not syncing 

### ISSUE THREAD

**Issue by Maxpower7847** [bigbluebutton/bigbluebutton#9874]
**Describe the bug**
Videos from external source are not syncing. when the presenter shares video clients can see the video (and are synced) but when the presenter pauses the video it just keeps playing on the client side. Also if the client stops the video it has no effect on other viewers.

**To Reproduce**
1. start sharing externalt video
2. click on different time frame in the video 
3. video keeps playing on client side as if nothing happened 

**Expected behavior**
Video should sync with presenter video 

**Actual behavior**
video does not sync

**Comment by basisbit** [comment]
can you reproduce this problem on https://demo.bigbluebutton.org ?

**Comment by matiasilva** [comment]
Yeah, the client stopping the video will not restart it for anyone else. That's good. Imagine teaching a class with 20 kids and each of them constantly playing and pausing the videos. The presenter can play/pause and that's ideal.

**Comment by Maxpower7847** [comment]
thank you for your replies. It turned out to be a network problem. We haven't quite figured out what the source is, but we noticed that the videos behave correctly when connecting to the server from a different network than what we are using here. I am going to open a new issue for that since the descritpion here doesn't seem appropriate anymore

**Comment by basisbit** [comment]
@Maxpower7847 Please do not open another issue for that. It is a support Request. For support requests, please use the [forum / mailing list](https://groups.google.com/forum/#!forum/bigbluebutton-setup). This issue tracker here is only for BBB development related issues. Sorry.
