### ISSUE TITLE
reply to comments

### ISSUE THREAD

**Issue by cod3r0k** [bigbluebutton/bigbluebutton#9877]
Dear All, Is there any option to reply to each comment in BBB? How can we reply to a specific comment on BBB conversation section?
Also, could we add emoji ?
![image](https://user-images.githubusercontent.com/36899025/85053235-734c6100-b1af-11ea-8032-d8e1a44835cb.png)

**Comment by matiasilva** [comment]
I'm assuming by "comment" you mean chat message. Also, emoji is supported already. If you're on Windows, press the windows key + . and you get the emoji window.

**Comment by antobinary** [comment]
Hi @cod3r0k ,

There is currently no support for message threads and I am not aware of near-future plans of adding it.

**Comment by cod3r0k** [comment]
> I'm assuming by "comment" you mean chat message, right? Also, emoji is supported already. If you're on Windows, press the windows key + . and you get the emoji window.

Thanks great!. Thank you. It was working for me!.
But could you help me to add one button beside the post button for this purpose?

**Comment by cod3r0k** [comment]
> Hi @cod3r0k ,
> 
> There is currently no support for message threads and I am not aware of near-future plans of adding it.

Could you help me, if I can collaborate and done this task. because I want this option and when I check the @matiasilva 's answer, it was correctly worked for me. I think that if I can embed a button for it, this task could be solved soon!

**Comment by matiasilva** [comment]
As for adding and changing things, you can set up a development version of the HTML5 client here: https://docs.bigbluebutton.org/2.2/dev.html. The client is built with React. If you are a developer, then you can make a pull request to add this. Otherwise, it seems there are other more pressing features to add and issues to solve, unfortunately.
