### ISSUE TITLE
Logo in BBB's session

### ISSUE THREAD

**Issue by cod3r0k** [bigbluebutton/bigbluebutton#9880]
Dear All, How can I embed a logo in BBB session (e.g. upside of the conversation button)?
I check the BBB setting, It has one option for logo but it doesn't work for me. Is there any solution to embed it upside of the conversation button?

**Comment by matiasilva** [comment]
Hi, this issue tracker is for development only. Please post this to https://groups.google.com/forum/#!forum/bigbluebutton-setup.
