### ISSUE TITLE
BBB timeout session (which we have in breakout session)

### ISSUE THREAD

**Issue by cod3r0k** [bigbluebutton/bigbluebutton#9881]
Dear All, we have an option in BBB which we can devote a breakout room with some limitation (e.g. the time, number of participants and so on).

Could we use this breakout session as our main session with their wonderful options (e.g. duration of each session or number of participants)? 

I check the documentation, and I found that if we want to have some limitation for the BBB concurrent participants, we must have different VPS and different setting (number of current participants in `bigblubutton.properties`) and so on. Is there any better economical solution?

**Comment by matiasilva** [comment]
You can set the number of participants in the API call when creating the session. The duration can be likewise done. For all further support, please post in https://groups.google.com/forum/#!forum/bigbluebutton-setup.
