### ISSUE TITLE
Increase number of breakout rooms

### ISSUE THREAD

**Issue by Richardvi** [bigbluebutton/bigbluebutton#9883]
Teachers are requesting more breakout rooms to work with smaller groups. The request is for 16 breakout rooms in stead of 8.

How can we support by funding?  I think many would be willing to donate for this

**Comment by matiasilva** [comment]
Duplicate of #8657. If you would like to see a certain feature in BigBlueButton with relative swiftness, it's best to reach out to the commercial companies that provide support: https://bigbluebutton.org/commercial-support/.
