### ISSUE TITLE
Clients/Users get WebRTC error 1002 when *they* are behind firewall & proxy

### ISSUE THREAD

**Issue by MJ-LAMARC** [bigbluebutton/bigbluebutton#9886]
**Describe the bug**
Users which are working from an network that is guarded by a firewall and proxy server cannot connect properly to WebRTC socket - error 1002 is shown to them when connecting by microphone

**To Reproduce**
1. BBB server ist directly connected to the Internet (official IPv4 and IPv6 addresses) - Only local firewall with open-TCP: 22,80,443,5066,7443 and open-UDP: 16384:32768
2. TURN-server is set-up and working, as installation manual.
3. User behind firewall/proxy (corporate office network) ist trying to connect via https:// is getting error 1002
4. User directly connectted to Internet succeeds

**Expected behavior**
Users from corporated network should connect to BBB-server

**Actual behavior**
Users cannot connect using audio/video.

**BBB version (optional):**
BigBlueButton Server 2.2.16 (1987)

**Desktop (please complete the following information):**
 - OS: Linux and "Windows"
 - Browser Chrome, Firefox
 - Version 83.0, 77.0

**Comment by matiasilva** [comment]
Hi, thanks for posting. Have you tried searching around the issue tracker for a similar error?

**Comment by basisbit** [comment]
Get their firewall administrator to allow websocket connections.

**Comment by MJ-LAMARC** [comment]
So, what if they refuse to do so? Usually outgoing ports are resticted to 80/tcp and 443/tcp.
This would be a big disadvantage for BBB in comparioson to WebEx & Co.

**Comment by basisbit** [comment]
This is a free/libre open source software project, feel free to submit a pull request which implements some fallback mechanism for the websocket based signalling communication.
Currently BBB requires websocket to work. Websocket uses TLS over tcp/443. Usually the reason for not supporting websocket communication are very old firewalls or wrong configured firewalls.

**Comment by basisbit** [comment]
@MJ-LAMARC by the way, I suggest you to close your firewall ports 5066 and 7443 as described in the install instructions, otherwise your server will get used for denial of service attacks on other servers.
