### ISSUE TITLE
Add a visual indicator of breakout-rooms in the main BigBlueButton session

### ISSUE THREAD

**Issue by tylercopeland** [bigbluebutton/bigbluebutton#9887]
Today, a  BigBlueButton session prompts a user to join a Breakout Room, but if they chose not to join or they enter the session after a breakout room has started, it may not be obvious where to go. 

Please find below a simple mockup that looks to improve this experience. 

![Screen Shot 2020-06-18 at 12 39 05 PM](https://user-images.githubusercontent.com/1273169/85167221-79395500-b236-11ea-924a-7ca2d59acf64.png)

The thinking here is to introduce a new principle to BigBlueButton, where any new item that gets added to the sidebar gets a bolded text and a blue dot treatment.

In terms of Breakout Rooms, a nice to have feature would also be to include the duration. This is a moving visual cue that would also help with indicating this new item in the sidebar. 

As always, I'd love to hear thoughts from the community on these enhancements.

**Comment by matiasilva** [comment]
I quite like this. It's going to be helpful for future additions to the sidebar too.

**Comment by antobinary** [comment]
In BigBlueButton 2.5.x let's add the duration indicator and let's check afterwards about the blue dot

**Comment by antobinary** [comment]
Checking with @tylercopeland on the blue dot. We can create a new issue on the blue dot with more details

**Comment by antobinary** [comment]
Postponing after checking with Tyler
