### ISSUE TITLE
join audio room breakout for listen only user doesnt work

### ISSUE THREAD

**Issue by maychine-fatima** [bigbluebutton/bigbluebutton#9889]
as we can join audio just as moderator i changed something to have join audio for listen only users too so when i tried with that it doesnt give any result and the user its not joined , can someone explain me the problem.

**Comment by matiasilva** [comment]
Hi @maychine-fatima. This feature request has been opened here: #4047. If you want help with developing this feature, the community is most glad to help. Post in the developer group for help: https://groups.google.com/forum/#!forum/bigbluebutton-dev.
