### ISSUE TITLE
SIP dialin access can't unmute

### ISSUE THREAD

**Issue by ReimarBauer** [bigbluebutton/bigbluebutton#9890]
Recently we found a "design" problem for users connecting by audio over a phone number.

If the room is configured for a muted microphone than unmute is impossible for those joining by a phone number.

A solution may be to disable this feature for dialin users or to give a moderator the option to unmute those users.

Or is there a key code which can be send over the phone?

**Comment by matiasilva** [comment]
See #9884. Does this help?

**Comment by Daedalus3** [comment]
Problem still exists in 2.2.26.

**Comment by svoeth** [comment]
Can't reproduce in 2.2.36. Mute/Unmute can be achieved by pressing 0 on the phone.

Unmuting a user by the admin is imho not a desired feature and tehrefore the possibilty to unmute one by themself should be prefered.

**Comment by zhem0004** [comment]
Could not reproduce on 2.4.2, this functionality worked as expected.
