### ISSUE TITLE
Presentation message is displayed twice

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#9892]
**Describe the bug**
New users joining a session are getting two message about the current presentation

**To Reproduce**
1. Go to https://demo.bigbluebutton.org/
2. Start a session and invite a second user

**Expected behavior**
User joins without notifications of presentation

**Actual behavior**
Two current presentation messages are shown

**Screenshots**

![image](https://user-images.githubusercontent.com/290351/85224993-0a760c00-b39c-11ea-9519-7b58aa5517a0.png)

**BBB version (optional):**
2.2.18

**Comment by antobinary** [comment]
Fixed in 2.3 https://github.com/bigbluebutton/bigbluebutton/pull/8855
