### ISSUE TITLE
HTML5 Client : Audio cutting out on APU machine

### ISSUE THREAD

**Issue by visiojd** [bigbluebutton/bigbluebutton#9894]
Hi,
We are using BBB since a while now. 

Since few weeks we observed issues on client machine running windows 10 with APU processors or equivalent : 

Here are the processors with which we reproduced the issue from now:

- AMD E1 7070
- AMD E2
- CELERON N2080

We are using BBB 2.2.17 with exclusivelly HTML5 Client.

I tried and reproduced the issue on demo.bigblubutton.org 

Symptoms : Audio cutting out - huge lags - which become even worst with webcam sharing.

**Comment by matiasilva** [comment]
How is CPU usage? Looks like a performance issue where the client can't handle the incoming media streams, especially video. Are you also using video?

**Comment by visiojd** [comment]
Hard to tell as these are different client machine from different people. 

For sure most of low cost computers actually sold are just to bad to run properly webrtc.

The problem is that they don't have the same issue when using skype or zoom which are not using web interface.

The reason I decided to post an issue or an eventual enhancement is that there is there are more and more of these machines being sold.

**Comment by matiasilva** [comment]
Hm, perhaps it's worth having them test the web interfaces in the software you've mentioned.

**Comment by visiojd** [comment]
I could try.
I never had such issues before and by asking more infos I observed that it was always these kind of machine that are very low configured. I noticed that they seems on benchmark being less powerfull than 10 years old CPU. 
The only way I got a good connection is for them to connect with both the smartphone and the computer because it's easier to use the computer for sharing material.

**Comment by visiojd** [comment]
But I'm sure it's worth also to imagine some tunning in order to keep the purpose of Bigbluebutton : Offer the best web videoconference exerience

**Comment by matiasilva** [comment]
Agreed, perhaps something that needs some more investigation. Also worth nothing BigBlueButton has its mission as "provide remote students a high-quality **online learning experience**". The distinction from general videoconferencing system is important.

**Comment by visiojd** [comment]
Of course. This is actually the way I use it, for online learning.

**Comment by basisbit** [comment]
For support requests, please use the [forum / mailing list](https://groups.google.com/forum/#!forum/bigbluebutton-setup). This issue tracker here is only for BBB development related issues. Sorry.

**Comment by basisbit** [comment]
@visiojd could you please try to get your hands on one of these machines, then make sure there is not other process hogging the CPU (like the typical failed windows .net framework updates /...) and then in Google Chrome / Chromium developer tools in the tab "Performance" create an analysis by pressing the record button in the top left and then stop it after half a minute or so, while you are connected to a videoconference where audio it cutting out?

**Comment by visiojd** [comment]
Hi,
Yes I can try to do that and let you know, but if I take the hand with team viewer for instance there will be at least this process which will for sur hogg the CPU don’t you think?

**Comment by basisbit** [comment]
Teamviewer should be fine - it even works on a raspberry pi 2.

**Comment by prlanzarin** [comment]
While you are at it @visiojd, please try to extract a dump from chrome://webrtc-internals or about:webrtc (firefox) and share it here. Please redact IPs, I'm only interested in the WebRTC stats info. Try to mark the time diff from start where the cutting/jitter/stuttering begins.

**Comment by ravi-ct** [comment]
Just adding my observations based on our clients who report similar issues - the CPU is generally pegged at 80-100% the moment even a single video stream turns on (incoming or outgoing, deskshare or webcam, even if the stream is at a bit rate of only 50 Kbps).

Changing the encoding on Kurento to H264 causes other issues but improves the situation for these folks, likely indicating lack of support for hardware encoding for VP8. What's surprising is not that they can use Zoom, Teams well. They actually are able to use Google Meet in the browser quite well. I hadn't gotten my hands on the data to see if it was some other codec that Google uses.

I will ask my support organization to keep an eye out for cooperative customers and gather some webrtc logs from the browser along with the perf stats on the machine.

**Comment by matiasilva** [comment]
As far as I understand it, isn't there some licensing complications with using H264?

**Comment by visiojd** [comment]
Hi there.

Great to here that the issue has been reproduced somewhere. 
You went further that I had the chance to go by testing with google Meet. 

I would be thankful if someone find the bottleneck and some possibilities to make the situation better. 

As I told there are more and more client machines under this type of low CPU supposed to work well on windows 10. 

I becomes to be a real issue if all other platforms works.

Thanks.

**Comment by visiojd** [comment]
> Just adding my observations based on our clients who report similar issues - the CPU is generally pegged at 80-100% the moment even a single video stream turns on (incoming or outgoing, deskshare or webcam, even if the stream is at a bit rate of only 50 Kbps).
> 
> Changing the encoding on Kurento to H264 causes other issues but improves the situation for these folks, likely indicating lack of support for hardware encoding for VP8. What's surprising is not that they can use Zoom, Teams well. They actually are able to use Google Meet in the browser quite well. I hadn't gotten my hands on the data to see if it was some other codec that Google uses.
> 
> I will ask my support organization to keep an eye out for cooperative customers and gather some webrtc logs from the browser along with the perf stats on the machine.

Hi.Any news on your side ? We keeps having the same issue on every APU computer. Lately AMD A6-9125

**Comment by ffdixon** [comment]
We've been steadily improving the video over the past few months.  Are you running the latest build of BigBlueButton (which is [2.2.31](https://github.com/bigbluebutton/bigbluebutton/releases/tag/v2.2.31) at the time of this post), and enabled [multiple kurento servers](https://docs.bigbluebutton.org/2.2/customize.html#run-three-parallel-kurento-media-servers).

**Comment by visiojd** [comment]
Not Yet but I will definitively give a try. I run 2.2.29 but many sessions are running at this very moment. I'll give a try this evening and let you know.
Do I just have to run install.sh and setup ip to get it working or is there a specific setting to enable multiple kurento servers ?

**Comment by ffdixon** [comment]
Definitely recommend you update to 2.2.31 and enable multiple Kurento servers.  To upgrade, just re-run the same [bbb-install.sh](https://github.com/bigbluebutton/bbb-install) command again.

**Comment by visiojd** [comment]
Hi,
I did the update and enabled multi curent servers but nothing changed.
It becomes a real big issue as many actual computers have these low range APU inside.

Cordialement

Jean-Daniel Yadan
Directeur Adjoint
jd.yadan@visiolang.net
06 13 45 74 77

**Comment by prlanzarin** [comment]
Multiple Kurento servers won't make any difference at all. This is a client side problem.

It **really shouldn't** peg at 100% with a single stream (even low end smartphones do better than that with BBB, tbh), so this is highly abnormal. Even when it still chokes on 50kbps VP8 streams.

I don't have any sort of AMD APU that looks like that to hunt the problem down, which makes things difficult. So we'd have to come up with a minimal WebRTC application so you can poke at it, experiment with codecs and rule out badly optimized react stuff. Then we can gather info and work on that. I'll try to think something up.

PS.: FYI GMeet can use anything from hardware accelerated H.264 to VP9.

**Comment by prlanzarin** [comment]
@visiojd First test: trying to reproduce it in https://appr.tc/.
Join with two different endpoints in the same room. See how it does.

**Comment by visiojd** [comment]
I'll do italien with one of m'y teacher hwo has this kind of computer ---- On mar., 12 janv. 2021 13:35:20 +0100  notifications@github.com  wrote ----
@visiojd First test: trying to reproduce it in https://appr.tc/.
Join with two different endpoints in the same room. See how it does.

**Comment by visiojd** [comment]
I'm testing now with the link you mentionned and it's as bad as in bigbluebutton perhaps even worst.
Actually those low end APU combined with windows 10 are really bad for Webrtc I guess.

**Comment by visiojd** [comment]
@prlanzarin I did some research on different kind of videoconference tools. By the way I'm using BBB since 0.81 version. They all have issues with more or less kind of client configuration as soon as it is a web based videoconferencing. Jitsi is probably the worst I red about. Zoom too experience issues on web based version. 
We actually never experienced big issues but since a year now budget laptops bought as new seems not being powerfull enough and run almost 1000% of `CPU as soon they enter the conference rooms.(even worst when trying https://appr.tc/).

**Comment by prlanzarin** [comment]
@visiojd I stumbled back into this. Can this issue be closed based on our discussion?

https://github.com/bigbluebutton/bigbluebutton/issues/11582 also has a good discussion on this and possible workarounds. Be sure to take a peek at it.

**Comment by visiojd** [comment]
> @visiojd I stumbled back into this. Can this issue be closed based on our discussion?
> 
> #11582 also has a good discussion on this and possible workarounds. Be sure to take a peek at it.

Hard to say? I actually get this issue on budget laptop running on windows 10. This same machine works perfectly with linux installed. I would say the problem comes more from windows 10 installed on these budget AMD cpu. The other post is I guess talking about server side. My issue is on client side and becomes a critical issue for us as it occurs quite often these last months.

**Comment by prlanzarin** [comment]
> The other post is I guess talking about server side.

It's not. It's about a budget/small form factor PC getting CPU restricted (which is pretty much the same as this, the differences being the CPU vendor and OS).
So the advice still stands: be sure to take another peek at it. There are a few tools you could use and check to see if it improves the situation (dynamic camera profiles, video pagination, **data savings**).
