### ISSUE TITLE
Make the end meeting screen clearer

### ISSUE THREAD

**Issue by matiasilva** [bigbluebutton/bigbluebutton#9898]
**Describe the issue**

Presently, when a user ends a meeting it might not be immediately clear that they will end the meeting for all. The text has been modified to improve this and also the "logout" button is planning on changing to "leave meeting" but as one user has stated, this can be further improved. I've worked on improving this by including a list of users that will be kicked from the meeting. This makes it much *much* clearer what the user is about to do. I'd like to get the community's thoughts.

**Screenshots**

<img width="463" alt="Annotation 2020-06-20 121630" src="https://user-images.githubusercontent.com/23108156/85321871-4eacfd80-b4bd-11ea-823f-d2327caf873e.png">

**Additional context**

Related PRs and issues: #9897 and #9868

**Comment by antobinary** [comment]
Hi @matiasilva,
Is this the enhancement you were planning on implementing (looking at the chat in #9868)

**Comment by matiasilva** [comment]
Yep!

**Comment by antobinary** [comment]
Marked you as assigned! Are you implementing this on 2.2.x or BBB 2.3.x?

**Comment by matiasilva** [comment]
The only distinction is that this has actually been developed, as opposed to the mock-up that was posted in the other issue.

**Comment by matiasilva** [comment]
Oh, hm. Well I suppose a change like this probably belongs in 2.3.x?

**Comment by antobinary** [comment]
If I were you I'd base it off from 2.2.x.
If the changes are not too invasive(I don't think it will be) && you are able to implement it in within a few days (like your previous PR) && if it does not introduce issues, very high likelihood it will make it in 2.2.x... Plan B is to merge it in 2.3 later (little has changed in that area in 2.3)

**Comment by ffdixon** [comment]
For the near-term, we made some minor improvements to the alert text in the dialog (this is in 2.2.19).

![image](https://user-images.githubusercontent.com/290351/85968016-db5e2c80-b991-11ea-9221-dd7182f7eef9.png)

**Comment by antobinary** [comment]
@matiasilva your PR was merged into 'develop' via https://github.com/bigbluebutton/bigbluebutton/pull/11194
