### ISSUE TITLE
Shared notes gone with 2.2.17 update

### ISSUE THREAD

**Issue by Braehler** [bigbluebutton/bigbluebutton#9904]
**Describe the bug**
Since we updated our srver to the version 2.2.17 the shared notes are gone.
Our teachers can not use this feature.
Any solution for that? Whtat did we miss? 

**To Reproduce**

**Expected behavior**

**Actual behavior**

**Screenshots**

**BBB version (optional):**
BigBlueButton continually evolves. Providing the version/build helps us to pinpoint when an issue was introduced.
Example:
$ sudo bbb-conf --check | grep BigBlueButton
BigBlueButton Server 2.2.2 (1816)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, Mac]
 - Browser [e.g. Chrome, Safari]

**Smartphone (please complete the following information):**
 - Browser [e.g. stock browser, Safari]

**Additional context**

**Comment by ffdixon** [comment]
What is the output of

~~~
sudo bbb-conf --check
~~~

**Comment by Braehler** [comment]
BigBlueButton Server 2.2.2 (1992)
                    Kernel version: 4.4.0-176-generic
                      Distribution: Ubuntu 16.04.6 LTS (64-bit)
                            Memory: 65755 MB
                         CPU cores: 8

/usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties (bbb-web)
       bigbluebutton.web.serverURL: https://lms-duesseldorfer-akademie.de
                defaultGuestPolicy: ALWAYS_ACCEPT
                 svgImagesRequired: true

/etc/nginx/sites-available/bigbluebutton (nginx)
                       server name: lms-duesseldorfer-akademie.de
                              port: 80, [::]:80
                              port: 443 ssl
                    bbb-client dir: /var/www/bigbluebutton

/var/www/bigbluebutton/client/conf/config.xml (bbb-client)
                Port test (tunnel): rtmp://lms-duesseldorfer-akademie.de
                              red5: lms-duesseldorfer-akademie.de
              useWebrtcIfAvailable: true

/opt/freeswitch/etc/freeswitch/vars.xml (FreeSWITCH)
                       local_ip_v4: 5.9.31.198
                   external_rtp_ip: stun:stun.freeswitch.org
                   external_sip_ip: stun:stun.freeswitch.org

/opt/freeswitch/etc/freeswitch/sip_profiles/external.xml (FreeSWITCH)
                        ext-rtp-ip: $${local_ip_v4}
                        ext-sip-ip: $${local_ip_v4}
                        ws-binding: :5066
                       wss-binding: :7443

/usr/local/bigbluebutton/core/scripts/bigbluebutton.yml (record and playback)
                     playback_host: lms-duesseldorfer-akademie.de
                 playback_protocol: https
                            ffmpeg: 4.2.2-1bbb1~ubuntu16.04

/etc/bigbluebutton/nginx/sip.nginx (sip.nginx)
                        proxy_pass: 5.9.31.198

/usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml (Kurento SFU)
                        kurento.ip: 5.9.31.198
                       kurento.url: ws://127.0.0.1:8888/kurento
                    kurento.sip_ip: 5.9.31.198
                    localIpAddress: 5.9.31.198
               recordScreenSharing: true
                     recordWebcams: true
                  codec_video_main: VP8
               codec_video_content: VP8

/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml (HTML5 client)
                             build: 937
                        kurentoUrl: wss://lms-duesseldorfer-akademie.de/bbb-webrtc-sfu
                  enableListenOnly: true


# Potential problems described below

**Comment by Braehler** [comment]
Think I found it in the /usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml
The settings of note were set to false instead of true

**Comment by matiasilva** [comment]
Glad to hear you solved it.
