### ISSUE TITLE
defaultLayout doesnt work 

### ISSUE THREAD

**Issue by misisol** [bigbluebutton/bigbluebutton#9911]
**Describe the bug**
As I change defaultLayout in join API request, it doesn't have any effect on Html client appearance.

**To Reproduce**
Calling join API with the link below : 
`/bigbluebutton/api/join?fullName=Meri&meetingID=ae676f88-b850-3b52-89cd-7d75135e6927&password=345&userID=5c1a0d22ce7b2f749888e76b&defaultLayout=bbb.layout.name.closedcaption&joinViaHtml5=true&checksum=321`

**Expected behavior**
As its stated in BBB documentation the HTML layout should change over passing defaultLayout parameter.

$ sudo bbb-conf --check | grep BigBlueButton
BigBlueButton Server 2.2.17 (1816)

**Comment by Tech-AJ** [comment]
Did you try changing create meeting default parameters like chat disabled or automute on start? Are these working? Because while I am trying to change these, changes are not getting reflected.
I have also filled issue here.
https://github.com/bigbluebutton/bigbluebutton/issues/9930

**Comment by misisol** [comment]
@Tech-AJ Yes I did and works for me.

**Comment by matiasilva** [comment]
For user parameters, you might also be interested in https://docs.bigbluebutton.org/2.2/customize.html#passing-custom-parameters-to-the-client-on-join

**Comment by Tech-AJ** [comment]
> @Tech-AJ Yes I did and works for me.

@misisol  I have updated the log file. Kindly review it.

**Comment by misisol** [comment]
@matiasilva thanks for that document, great tool for join call customization. But still didnt find an alternative way to change defaultLayout, I think it a real bug.
