### ISSUE TITLE
bbb-webrtc-sfu logfiles are generated with year-month-day format after update to 2.2.18

### ISSUE THREAD

**Issue by levigo-systems** [bigbluebutton/bigbluebutton#9912]
**Describe the bug**
After a BigBlueButton update to version 2.2.18 the logfile /var/log/bbb-webrtc-sfu/bbb-webrtc-sfu.log is created with year-month-day format -> bbb-webrtc-sfu.log.2020-06-24.
This is a problem because the logrotate job can no longer do its job.
The file of the current day should always be named bbb-webrtc-sfu.log, as before.

**To Reproduce**
1. Update to BigBlueButton version 2.2.17

**Expected behavior**
The file of the current day should always be named bbb-webrtc-sfu.log, as before.

**Actual behavior**
The logfile /var/log/bbb-webrtc-sfu/bbb-webrtc-sfu.log is created with year-month-day format -> bbb-webrtc-sfu.log.2020-06-24.

**Comment by antobinary** [comment]
@prlanzarin Is this intentional?

**Comment by ffdixon** [comment]
Thanks for reporting this -- we discovered that 2.2.18 inadvertently included an older build of `bbb-webrtc-sfu`.  We just released [2.2.19](https://github.com/bigbluebutton/bigbluebutton/releases/tag/v2.2.19).  

Can you update to 2.2.19 and let us know if you still encounter this issue.

**Comment by levigo-systems** [comment]
Yeah, it's fixed!
`root@bbb:/var/log/bbb-webrtc-sfu# logrotate /etc/logrotate.d/bbb-webrtc-sfu.logrotate --force
root@bbb:/var/log/bbb-webrtc-sfu# ls -la
total 20
drwxr-xr-x  2 bigbluebutton bigbluebutton   63 Jun 25 18:41 .
drwxrwxr-x 21 root          syslog        8192 Jun 25 06:26 ..
-rw-r--r--  1 bigbluebutton bigbluebutton    0 Jun 25 18:41 bbb-webrtc-sfu.log
-rw-r--r--  1 bigbluebutton bigbluebutton 5538 Jun 25 18:40 bbb-webrtc-sfu.log.1.gz
root@bbb:/var/log/bbb-webrtc-sfu# cat /etc/logrotate.d/bbb-webrtc-sfu.logrotate
/var/log/bbb-webrtc-sfu/*.log {
        daily
        missingok
        rotate 7
        compress
        notifempty
        copytruncate
}
`

**Comment by prlanzarin** [comment]
Cool.
