### ISSUE TITLE
New look setting: Ear other viewers audio

### ISSUE THREAD

**Issue by parreitu** [bigbluebutton/bigbluebutton#9915]
There's a lock setting called **See** other viewers webcams that moderators can use to control that. It'll allow viewers to share their webcams, but they'll only **see** their own camera and the moderator's. Only a moderator is able to **see** everyone. With this lock setting viewers are able to **ear** each other.

It would be a very practical option when you take an online exam with many students, and you don't want the students to see **and hear** each other, but you do want the teacher to be able to see and hear all the students.

Right now you can lock the video so that one student does not see another student's video, but the sound of one student is heard by everyone else.

**Comment by matiasilva** [comment]
This sounds like an interesting idea, though ideally for such an exam, they would be muted?

**Comment by parreitu** [comment]
The idea would be that the students audio would be muted only for the other students.

In these case, the teacher would be able to see and hear all the students, but each student only would be able to see and hear the teacher.
