### ISSUE TITLE
BigBlueButton: Error 1020: media cloud not reach the server

### ISSUE THREAD

**Issue by haykelbensalha** [bigbluebutton/bigbluebutton#9916]
I installed BBB on my server with public ip and name server , everthings work correctly  but i have 1020 error if i want start webcam , How i can connect my BBB server with google stun server

**Comment by prlanzarin** [comment]
There's a dozen posts in the mailing list explaining how to debug this. There's also a dozen closed issues in here (eg https://github.com/bigbluebutton/bigbluebutton/issues/6797#issuecomment-607866043) with the same stuff. And, finally, there's a good chunk of docs on this as well (https://docs.bigbluebutton.org/2.2/configure-firewall, https://docs.bigbluebutton.org/2.2/configure-firewall). 

**Please** do some researching before opening an issue like this.
