### ISSUE TITLE
Allow visibility of long user names

### ISSUE THREAD

**Issue by MWWorks** [bigbluebutton/bigbluebutton#9917]
**Describe the bug**
Especially in light of the avatar currently missing in the HTML5 client, I am using long user names, indicating their name, and their location and company name. Eg 'Sherlock Holmes [GB] Consulting Detectives Ltd' so that visitors can see a little more about other attendees. But much of this is cropped off by the maximum width of the LHS panel.

**To Reproduce**
Join meeting with a long user name

**Expected behavior**
Ideally some way for others to see the full user name

**Actual behavior**
Long user name gets truncated with an ellipsis, even when resizing the LHS panel

**Additional context**
Looking at the HTML, it seems a quick fix (even if not fully accessible) for this would be to set the user name as the title attribute for the element, so it would appear when hovering over it.

**Comment by matiasilva** [comment]
I think work on the avatar should take priority, but this seems like something a small addition that could come with it.

**Comment by antobinary** [comment]
Implemented in https://github.com/bigbluebutton/bigbluebutton/pull/14404
