### ISSUE TITLE
weird tcp port requests.

### ISSUE THREAD

**Issue by Maxpower7847** [bigbluebutton/bigbluebutton#9918]
**Describe the bug**
We have been having some connection problems with our BBB installation (very long time to establish connectiong and some stutters during video playback). I tried figuring them out with one of our network administrators and what we observed was that before a connection was established over the udp ports specified in the documentation, there were multiple requests to high tcp ports (approximatly port 20.000-25.000) coming in when establishing a camera connection. 
I couldn't find anything about those ports being used in BBB. We are not running a STUN or TURN server since all users in our usecase are in the same network with their own dedicated external IPs. When we allowed access to all ports on the machine the connection times sped up so I assume the problems are somehow connected to this problem

**To Reproduce**
1. Go to your bigbluebuttonserver
2. establish a camera connection
3. Monitor  Port requests

**Comment by basisbit** [comment]
what version of BBB do you use? I heard similar stories from some people, but they all said that this was not the case any more with a current version of BigBlueButton.

**Comment by Maxpower7847** [comment]
> what version of BBB do you use? I heard similar stories from some people, but they all said that this was not the case any more with a current version of BigBlueButton.


Thank you for your reply.
Server is running 2.2.6 (1871)
I am going to try and update it over the weekend if you think this might be the root of the problem (server is currently in use so can‘t do it sooner). Will report back once thats done.
