### ISSUE TITLE
redis pub/sub event list 

### ISSUE THREAD

**Issue by sadeghpro** [bigbluebutton/bigbluebutton#9926]
How can I find list of redis pub/sub event list and their usage?
I found `AllowedMessageNames.scala` file and I think this is a event list. if it's ok how can I create body of each event?

**Comment by matiasilva** [comment]
Hello there. It seems like your question is development related. Please post here along with an idea of what you're trying to accomplish: https://groups.google.com/forum/#!forum/bigbluebutton-dev
