### ISSUE TITLE
shared notes hidden after upgrading to 2.2.19

### ISSUE THREAD

**Issue by aguerson** [bigbluebutton/bigbluebutton#9928]
**Describe the bug**
The shared notes are hidden after upgrading to 2.2.19

**To Reproduce**
upgrade to 2.2.19

**Expected behavior**
I would like to see the shared note again

**Desktop (please complete the following information):**
 - OS: Linux CentOS 7
 - Browser Firefox
 - Version 68.9.0esr (64 bits)

**Comment by matiasilva** [comment]
Have you checked `/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml` to see if the relevant setting is true/false?

**Comment by aguerson** [comment]
Did I lose something in the conf ?

Is that the result of the modify in the javascript in version 2.2.18 ?

**Comment by aguerson** [comment]
To reproduce

I was in version 2.2.17
I upgraded to 2.2.18
and in I upgraded again to 2.2.19 ....

A issue ?

**Comment by matiasilva** [comment]
Shouldn't be an issue seeing as this issue hasn't popped up for others. Can you dig around some more, perhaps by looking in the browser console or the meteor server logs?

**Comment by aguerson** [comment]
Yes sure. I will find it.
A first return.
I tried with different version of greenlight in frontend : it is not the problem. I prefered to be sure !

The source of the problems is inside bbb, somewhere... I continue my investigation.

**Comment by pedrobmarin** [comment]
Take a look if your Etherpad instance is running
`sudo systemctl status etherpad`
If not, `sudo systemctl start etherpad`
Check if the apikey that is inside `/usr/share/etherpad-lite/APIKEY.txt` is the same as configured https://github.com/bigbluebutton/bigbluebutton/blob/40465e7c00247a2f6c01b03ebbc5be3ee8585e29/bigbluebutton-html5/private/config/settings.yml#L362 at `/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml`
If you needed to make that change, restart your html5 client to reload the modifications

**Comment by aguerson** [comment]
Not the same.

I searched between differents bbb versions and I didn't find any modification on it on the repository

Where came from the problem ? Introduced in a package ?

Thx so much again ;)
regards,
Aurélien
