### ISSUE TITLE
Create meeting API call won't change default parameters.

### ISSUE THREAD

**Issue by Tech-AJ** [bigbluebutton/bigbluebutton#9930]
**Describe the bug**
I have installed BBB on AWS EC2 instance. I am replacing greenlight with Drupal. When create meeting Api call is made with changed parameters like everyone auto mute on start or chat disabled, these changes won't reflect when meeting starts in HTML5 client. Create meeting/join meeting api calls are successful

**Expected behavior**
Default features should change via Api call parameters.

**Actual behavior**
Meeting always start with default parameters irrespective of what values are passed in Api call.

**BBB version (optional):**
BigBlueButton Server 2.2.2 

**Additional context**

Request object  --

array(6)
'meetingID' => string(13) "5ef30c50b0c1d"
'name' => string(14) "Test Meeting 2"
'welcome' => string(25) "Welcome to Test Meeting 2"
'muteOnStart' => boolTRUE
'lockSettingsDisablePrivateChat' => boolTRUE
'lockSettingsDisablePublicChat' => boolTRUE

Response object from create meeting api call -

public returncode -> string(7) "SUCCESS"
public meetingID -> string(13) "5ef30c50b0c1d"
public internalMeetingID -> string(54) "0c66c00bf55c058c088ba22cebfab33eba7ad21a-1592986707248"
public parentMeetingID -> string(8) "bbb-none"
public attendeePW -> string(8) "mjDAT4e3"
public moderatorPW -> string(8) "50NI3b5I"
public createTime -> string(13) "1592986707248"
public voiceBridge -> string(5) "00576"
public dialNumber -> string(12) "613-555-1234"
public createDate -> string(28) "Wed Jun 24 08:18:27 UTC 2020"
public hasUserJoined -> string(5) "false"
public duration -> string(1) "0"
public hasBeenForciblyEnded -> string(5) "false"
public messageKey -> stdClass(0)
public message -> stdClass(0)

But when I start/join meeting these settings-
'muteOnStart' => boolTRUE
'lockSettingsDisablePrivateChat' => boolTRUE
'lockSettingsDisablePublicChat' => boolTRUE
are not enforced. They remain as default.

**Comment by misisol** [comment]
I've tested and it works for me. (V2.2.17) 
Can you also send bbb-web log output dedicated to this api call? It's located in /var/log/bigbluebutton/bbb-web.log.

**Comment by matiasilva** [comment]
Hello, thanks for posting. Please move this discussion to: https://groups.google.com/forum/#!forum/bigbluebutton-dev the developer group where it can be better handled.

**Comment by Tech-AJ** [comment]
> 
> 
> I've tested and it works for me. (V2.2.17)
> Can you also send bbb-web log output dedicated to this api call? It's located in /var/log/bigbluebutton/bbb-web.log.

@misisol 
[bbb-web.log](https://github.com/bigbluebutton/bigbluebutton/files/4830840/bbb-web.log)

Hey, I have updated the logs in the issue description. Request is coming correctly, kindly check.
Thanks for the help.

**Comment by misisol** [comment]
@Tech-AJ as you can see in the log,
`2020-06-25T10:48:14.079Z DEBUG o.b.web.controllers.ApiController - [meetingID:[5ef480ea39a07], name:[ABC], welcome:[Welcome to ABC], muteOnStart:[1], lockSettingsDisablePrivateChat:[1], lockSettingsDisablePublicChat:[1]`
the boolean values you're passing are converted to its number value.
It should be passed as String ( true | false ). for example : `lockSettingsDisablePrivateChat=true `( in your create querystring)

**Comment by Tech-AJ** [comment]
@misisol Thanks for the help.
For those who might visit later,
I was passing it as Boolean only but the serialization module in Drupal to create query is automatically converting it to int. So the bug lies there.

**Comment by Tech-AJ** [comment]
@misisol 
Just a small help required -
https://github.com/php-mod/curl/issues/7#issuecomment-68852076
Here it says that we can't post boolean data. All data is treated as strings So boolean data will be converted to strings before to send them via POST. http_build_query convert false to 0, true to 1. If we suppose another function which converts them to "true" and "false", how can guest that were boolean and not a simple strings? 

Thus if you send boolean values it transform in integer :

$a = [teste1= true,teste2=false];
echo http_build_query($a)

//result will be teste1=1&teste2=0

So how to deal with this? 
Do the coversion from 0 back to boolean false needs to be done at server where bbb is installed or it can be done at cliet side?

I also checked bigbluebutton php example 
https://github.com/bigbluebutton/bigbluebutton-api-php/blob/48aa35340213fd3a6f3d6d81eb54d7b4eebef141/src/Parameters/BaseParameters.php#L31

Here it is also using http_build_query as
http_build_query(array_filter($array));

I am new to this. Kindly help.
