### ISSUE TITLE
1004 Error (Not Found) MICROPHONE in HTML5-Client

### ISSUE THREAD

**Issue by NiceboyWiseboy** [bigbluebutton/bigbluebutton#9931]
Hello,

I'm facing the **Microphone Not Found** issue when I try to build the HTML5-Client by following this [guide](https://docs.bigbluebutton.org/2.2/dev.html#setup-a-development-environment).

I know that this type of issues are to be posted in Google Groups of BigBlueButton, but didn't found my solution there. So, I'm posting this issue here. Maybe, you can help me figure out this issue. 'Cause I' stuck here since a month, tried out every possible solution given in Google Groups still my issue persists.

Hope you'll help me solve this issue.

Thank you,
Best Reagrds

**Comment by matiasilva** [comment]
This is a developer issue, so you should post in the developer group. Please give that a try, someone will answer and help you there: https://groups.google.com/forum/#!forum/bigbluebutton-dev

**Comment by NiceboyWiseboy** [comment]
Hello @matiasilva ,
thanks for your response. But I can't find any solution there. Been stuck here for a month now.
Please help me if you can.

Also sorry for replying in the closed issue. But I don't have any choice. I've tried every possible solution, please look into it.

Thank you,
Best Regards

**Comment by prlanzarin** [comment]
@NiceboyWiseboy link your mailing list post about this and I'll help you there.

**Comment by matiasilva** [comment]
@NiceboyWiseboy No worries, my goal was not to deny you help but rather help people distinguish between real bugs, feature improvements and support questions. Closing issues like these helps accomplish that.
