### ISSUE TITLE
[enhancement] Allow presentations sorting

### ISSUE THREAD

**Issue by mediaxtend** [bigbluebutton/bigbluebutton#9932]
**Enhancement description**
When a presentation is uploaded, it's been added to the bottom of the list when the file conversion is completed.
After that, we can't change the order of those presentations.
It would be useful to sort them using filename, the moment it has been uploaded or, better, using a manual sorting (drag and dropping files in the list).
This sorting mode should be saved to keep the order when presenter is changed.

When you have a webinar with multiple speakers, if you named the files to follow the schedule or if you use manual ordering, this feature will help:
- organizers to check that every presentations are uploaded and ready to be shown;
- speakers find their presentation, following the meeting schedule.

**To Reproduce**
1. Click "+" button at bottom left of the main screen, choose "Upload a presentation"
2. Upload a presentation file (or best: multiple files)
3. Wait file conversion end
4. See presentations list

**Expected behavior**
For example, have a table with 3 columns:
- file name: sortable
- upload date: sortable
- actions (buttons): not sortable

**Actual behavior**
Files list can't be sorted, files are added to the end when conversion is completed.

**Screenshots**

**BBB version**
BigBlueButton Server 2.2.17 (1992)
Client build: 937

**Desktop**
 - OS: Mac
 - Browser: Chrome
 - Version: 85.0.4173.2 dev (64 bits)

**Comment by basisbit** [comment]
how many files do you upload into that one session, so that such a feature is required? You might want to clean up your workflow there.

Personally I like to be able to just add an image file from somewhere on my harddrive and then seeing it as the latest added file at the bottom of the list. Adding alphabetic sorting would make it difficult to choose the correct file after adding files with the same filename but from different directories.

**Comment by mediaxtend** [comment]
For a 3 speakers / 2 hours webinar, we have 11 presentations.
At begging, we have one for introduction (speakers biography).
For each speaker (x3), we have:
- 1 for questions before course;
- 1 for the course;
- 1 for questions after course (to check that participants correctly understood the course);
And then 1 for conclusion.
To have a list where it's easy to find a presentation, we prefix files with numbers and upload it in the same order as the event's program.

I never said it must be sorted alphabetically, I just say it would be a nice possibility to give the possibility to sort presentations using an other way (filename, manually) than upload date.

**Comment by PhMemmel** [comment]
I think I fixed this issue with #11927, so can be closed
