### ISSUE TITLE
Moderator is automatically included in 2 different MeetingID valuable meetings.

### ISSUE THREAD

**Issue by mesutcakir** [bigbluebutton/bigbluebutton#9933]
Hello I think there is a vulnerability problem. My bbb version 2.2.3.

The situation is as follows. I have customized all the parameters.

Meeting1 - Different MeetingID, ParentId, Name, Passwords, and callbackUrls
Meeting2 - Different MeetingID, ParentId, Name, Passwords, and callbackUrls

The participant attending the Meeting1 meeting attends the meeting2 meeting. (Without "Join" operation)

How do we prevent two meeting moderators from attending automatic meetings?

My Codes and versions.
var qb = new QueryStringBuilder
            {
                {"meetingID", meetingId},
                {"parentMeetingID", meetingId + "parent"},
                {"name", name},
                {"attendeePW", attendeePassword},
                {"moderatorPW", moderatorPassword},
                {"record", record.ToString ()},
                {"allowStartStopRecording", allowStartStopRecording.ToString ()},
                {"autoStartRecording", autoStartRecording.ToString ()},
                {"voiceBridge", voiceBridge.ToString ()},
                {"welcome", welcome},
                {"recordingmarks", "false"},
                {"logoutURL", logoutUrl},
                {"meta_endCallbackUrl", (meetingEndUrl)},
                { "Meta_bbb-recording-ready-url" (recordingendurl)}
            };
            qb.Add ("checksum", GenerateChecksum ("create", qb.ToString ()));
            return Response.Parse <MeetingCreateResponse> (HttpGet (Url + "create?" + qb));

root@ip-10-0-2-235:/home/ubuntu#   bbb-conf --version
--
ii bbb-apps   1:2.2.0-42 amd 64 BigBlueButton applications for Red5
ii bbb-apps-akka   2.2.0-77 all BigBlueButton Apps (Akka)
ii   bbb-apps-screenshare 1:2.2.0-42 amd 64 BigBlueButton screenshare module for   Red5
ii bbb-apps-sip   1:2.2.0-11 amd 64 BigBlueButton SIP module for Red5
ii bbb-apps-video   1:2.2.0-39 amd 64 BigBlueButton video module for Red5
ii   bbb-apps-video-broadcast 1:2.2.0-8 amd 64 BigBlueButton video broadcast   module for Red5
ii bbb-client   1:2.2.0-33 amd 64 BigBlueButton Flash client
ii bbb-config   1:2.2.0-170 amd 64 BigBlueButton configuration utilities
rc bbb-demo   1:2.2.0-9 amd 64 BigBlueButton API demos
ii bbb-etherpad   1:2.2.0-50 amd 64 The EtherPad Lite components for BigBlueButton
ii   bbb-freeswitch-core 2:2.2.0-97 amd 64 BigBlueButton build of FreeSWITCH
ii   bbb-freeswitch-sounds 1:1.6.7-6 amd 64 FreeSWITCH Sounds
ii bbb-fsesl-akka   2.2.0-61 all BigBlueButton FS-ESL (Akka)
ii bbb-html5   1:2.2.0-870 amd 64 The HTML5 components for BigBlueButton
ii bbb-mkclean   1:0.8.7-3 amd 64 Clean and optimize Matroska and WebM files
ii   bbb-playback-presentation 1:2.2.0-28 amd 64 BigBluebutton playback of   presentation
ii bbb-record-core   1:2.2.0-62 amd 64 BigBlueButton record and playback
ii bbb-red5   1:1.0.10-16 amd 64 The Red5 server for BigBlueButton
ii   bbb-transcode-akka 2.2.0-8 all BigBlueButton Transcoder
ii bbb-web   1:2.2.0-117 amd 64 BigBlueButton API
ii bbb-webrtc-sfu   1:2.2.0-93 amd 64 BigBlueButton WebRTC SFU
ii bigbluebutton   1:2.2.0-5 amd 64 Open source web conferencing platform (bbb)
ii ffmpeg   7:4.2.2-1bbb1~ubuntu16.04 amd 64 Tools for transcoding, streaming and playing   of multimedia files
ii   libavcodec58:amd64 7:4.2.2-1bbb1~ubuntu16.04 amd 64 FFmpeg library with   de/encoders for audio/video codecs - runtime files
ii   libavdevice58:amd64 7:4.2.2-1bbb1~ubuntu16.04 amd 64 FFmpeg library for   handling input and output devices - runtime files
ii   libavfilter7:amd64 7:4.2.2-1bbb1~ubuntu16.04 amd 64 FFmpeg library containing   media filters - runtime files
ii   libavformat58:amd64 7:4.2.2-1bbb1~ubuntu16.04 amd 64 FFmpeg library with   (de)muxers for multimedia containers - runtime files
ii   libavresample4:amd64 7:4.2.2-1bbb1~ubuntu16.04 amd 64 FFmpeg compatibility   library for resampling - runtime files
ii   libavutil56:amd64 7:4.2.2-1bbb1~ubuntu16.04 amd 64 FFmpeg library with   functions for simplifying programming - runtime files
ii libopusenc0   0.2.1-1bbb1 amd 64 High-level API for encoding Ogg Opus audio streams
ii   libpostproc55:amd64 7:4.2.2-1bbb1~ubuntu16.04 amd 64 FFmpeg library for post   processing - runtime files
ii   libswresample3:amd64 7:4.2.2-1bbb1~ubuntu16.04 amd 64 FFmpeg library for   audio resampling, rematrixing etc. - runtime files
ii   libswscale5:amd64 7:4.2.2-1bbb1~ubuntu16.04 amd 64 FFmpeg library for image   scaling and various conversions - runtime files

**Comment by basisbit** [comment]
For such support requests, please use the [forum / mailing list](https://groups.google.com/forum/#!forum/bigbluebutton-dev). This issue tracker here is only for development of BBB itself. Sorry.
