### ISSUE TITLE
Low quality video with 4k panoramic cam 

### ISSUE THREAD

**Issue by EvgeniyNeytman** [bigbluebutton/bigbluebutton#9934]
Hi! When using Jabra Panacast camera in 3840-1920 mode the video is low quality in all video quality presets.

Seems because of unsupported video res of aspect ratio

**Comment by basisbit** [comment]
For support requests, please use the [forum / mailing list](https://groups.google.com/forum/#!forum/bigbluebutton-users). This issue tracker here is only for BBB development related issues. Sorry.
