### ISSUE TITLE
FreeSWITCH ESL connection authentication error

### ISSUE THREAD

**Issue by bilias** [bigbluebutton/bigbluebutton#9935]
Hi,
after upgrading to 2.2.19 I contantly get this to 2/3 of my updated servers:

Jun 25 14:43:02 bbb-webrtc-sfu[6681]: 2020-06-25T11:43:02.725Z - error: [mcs-freeswitch-esl-wrapper] FreeSWITCH ESL connection authentication error
Jun 25 14:43:02 bbb-webrtc-sfu[6681]: 2020-06-25T11:43:02.725Z - error: [mcs-freeswitch-esl-wrapper] FreeSWITCH ESL connection received error EPIPE errno=EPIPE, code=EPIPE, syscall=write

**Comment by bilias** [comment]
I think I've solved it by adding the esl_password in /usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml
which was missing.
I got the value from /opt/freeswitch/etc/freeswitch/autoload_configs/event_socket.conf.xml

**Comment by M1337** [comment]
Hey there i ran into the same problem- there is more to it: The password gets configured at two places if you look at the config script:
       sudo sed -i "s/ClueCon/$NEW_ESL_PASSWORD/g" /opt/freeswitch/etc/freeswitch/autoload_configs/event_socket.conf.xml
       sudo sed -i "s/ClueCon/$NEW_ESL_PASSWORD/g" /usr/share/bbb-fsesl-akka/conf/application.conf
       sudo yq w -i /usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml freeswitch.esl_password "$NEW_ESL_PASSWORD"

**Comment by j0wns** [comment]
> Hey there i ran into the same problem- there is more to it: The password gets configured at two places if you look at the config script:
> sudo sed -i "s/ClueCon/$NEW_ESL_PASSWORD/g" /opt/freeswitch/etc/freeswitch/autoload_configs/event_socket.conf.xml
> sudo sed -i "s/ClueCon/$NEW_ESL_PASSWORD/g" /usr/share/bbb-fsesl-akka/conf/application.conf
> sudo yq w -i /usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml freeswitch.esl_password "$NEW_ESL_PASSWORD"

This is still an issue in 2.2.2*
freeswitch.esl_password did not exist in default.yml after upgrade
The last line of your comment made my day.

**Comment by bilias** [comment]
This is fixed in https://github.com/bigbluebutton/bigbluebutton/releases/tag/v2.2.20
with #9962

**Comment by abautu** [comment]
I got the same problem today, after "apt upgrade" from 2.2.26 to 2.2.29. More precisely:
- /opt/freeswitch/etc/freeswitch/autoload_configs/event_socket.conf.xml was missing esl_password
- /opt/freeswitch/etc/freeswitch/autoload_configs/event_socket.conf.xml kept the old password (from 2.2.26)
- /usr/share/bbb-fsesl-akka/conf/application.conf had the ClueCon password
None of these files was changed by me (manually) before the upgrade.

**Comment by ffdixon** [comment]
After `apt upgrade`, you need to do `sudo bbb-conf --setip <hostname>` to update the configuration files.  See

   https://docs.bigbluebutton.org/2.2/install.html#upgrading-from-bigbluebutton-22

Doing this will update the FreeSWITCH ESL password.  See

  https://github.com/bigbluebutton/bigbluebutton/blob/develop/bigbluebutton-config/bin/bbb-conf#L1571
