### ISSUE TITLE
FreeSWITCH ESL connection dropped unexpectedly

### ISSUE THREAD

**Issue by SebastianZiegler** [bigbluebutton/bigbluebutton#9936]
Sometimes user gets disconnected, here the syslogs

Jun 25 13:27:33 bbb1 bbb-fsesl-akka[1085]: 2020-06-25T13:27:33.636+02:00 INFO  o.b.f.v.f.FreeswitchApplication - Queue message: conference 81689 xml_list
Jun 25 13:27:33 bbb1 bbb-fsesl-akka[1085]: 2020-06-25T13:27:33.636+02:00 INFO  o.b.f.v.f.FreeswitchApplication - Sending message: conference 81689 xml_list
Jun 25 13:27:35 bbb1 bbb-fsesl-akka[1085]: 2020-06-25T13:27:35.345+02:00 INFO  o.b.f.v.freeswitch.ESLEventListener - Received Heartbeat from Freeswitch.
Jun 25 13:27:36 bbb1 bbb-fsesl-akka[1085]: 2020-06-25T13:27:36.416+02:00 INFO  o.b.f.v.f.FreeswitchApplication - Queue message: conference 07974 xml_list
Jun 25 13:27:36 bbb1 bbb-fsesl-akka[1085]: 2020-06-25T13:27:36.416+02:00 DEBUG o.b.freeswitch.RxJsonMsgHdlrActor - handling to-voice-conf-redis-channel - {"envelope":{"name":"CheckRunningAndRecordingToVoiceConfSysMsg","routing":{"sender":"bbb-apps-akka"},"timestamp":1593084456414},"core":{"header":{"name":"CheckRunningAndRecordingToVoiceConfSysMsg","meetingId":"92647f0aa038626d3f2624f32351322e53cc330d-1593081691290"},"body":{"voiceConf":"07974","meetingId":"92647f0aa038626d3f2624f32351322e53cc330d-1593081691290"}}}
Jun 25 13:27:36 bbb1 bbb-fsesl-akka[1085]: 2020-06-25T13:27:36.417+02:00 INFO  o.b.f.v.f.FreeswitchApplication - Sending message: conference 07974 xml_list
Jun 25 13:27:36 bbb1 systemd[1]: freeswitch.service: Main process exited, code=killed, status=9/KILL
Jun 25 13:27:36 bbb1 bbb-webrtc-sfu[9695]: 2020-06-25T11:27:36.862Z - error: [mcs-freeswitch-esl-wrapper] FreeSWITCH ESL connection dropped unexpectedly
Jun 25 13:27:36 bbb1 systemd[1]: freeswitch.service: Unit entered failed state.
Jun 25 13:27:36 bbb1 systemd[1]: freeswitch.service: Failed with result 'signal'.
Jun 25 13:27:36 bbb1 systemd[1]: Started BigBlueButton recording and playback archive worker.
Jun 25 13:27:36 bbb1 systemd[1]: Reached target BigBlueButton recording & playback processing.
Jun 25 13:27:36 bbb1 systemd[1]: bbb-record-core.target: Unit not needed anymore. Stopping.
Jun 25 13:27:36 bbb1 systemd[1]: Stopped target BigBlueButton recording & playback processing.
Jun 25 13:27:37 bbb1 rap-archive-worker.rb[5900]: /usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
Jun 25 13:27:37 bbb1 rap-archive-worker.rb[5900]: /usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
Jun 25 13:27:37 bbb1 rap-archive-worker.rb[5900]: /usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:29: warning: constant Gem::ConfigMap is deprecated
Jun 25 13:27:37 bbb1 rap-archive-worker.rb[5900]: /usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:30: warning: constant Gem::ConfigMap is deprecated
Jun 25 13:27:37 bbb1 rap-archive-worker.rb[5900]: /usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
Jun 25 13:27:37 bbb1 systemd[1]: freeswitch.service: Service hold-off time over, scheduling restart.
Jun 25 13:27:37 bbb1 systemd[1]: Stopped freeswitch.
Jun 25 13:27:37 bbb1 systemd[1]: Starting freeswitch...
Jun 25 13:27:37 bbb1 freeswitch[5904]: 5905 Backgrounding.
Jun 25 13:27:37 bbb1 rap-archive-worker.rb[5900]: /usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
Jun 25 13:27:37 bbb1 rap-archive-worker.rb[5900]: message repeated 5 times: [ /usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated]
Jun 25 13:27:37 bbb1 systemd_start.sh[1288]: #033[32minfo#033[39m: Added annotation id=w_8qdmbzhwdhzq-5-1593084457736 whiteboard=a7d2b7af0c776caf6307beb05abc385507a2b763-1593081748504/16
Jun 25 13:27:38 bbb1 systemd_start.sh[1288]: #033[32minfo#033[39m: Updated joined users in breakout id=df231cc19828555571d7ca3d6a17d3f9925a7bbe-1593084293106
Jun 25 13:27:38 bbb1 systemd_start.sh[1288]: #033[32minfo#033[39m: Updated joined users in breakout id=f3ab0ed3559d0b0398bfa735b3ad12946366d0ae-1593084293105
Jun 25 13:27:38 bbb1 systemd_start.sh[1288]: #033[32minfo#033[39m: Updated joined users in breakout id=df231cc19828555571d7ca3d6a17d3f9925a7bbe-1593084293106
Jun 25 13:27:38 bbb1 systemd_start.sh[1288]: #033[32minfo#033[39m: Updated joined users in breakout id=f3ab0ed3559d0b0398bfa735b3ad12946366d0ae-1593084293105
Jun 25 13:27:38 bbb1 systemd_start.sh[1288]: #033[32minfo#033[39m: Updated breakout time remaining for breakouts where parentMeetingId=33c2155da24ff70319f2c5622f8b40161beb41fe-1593078113368
Jun 25 13:27:38 bbb1 bbb-fsesl-akka[1085]: 2020-06-25T13:27:38.928+02:00 INFO  o.b.f.v.f.ConnectionManager - Attempting to connect to FreeSWITCH ESL
Jun 25 13:27:38 bbb1 bbb-fsesl-akka[1085]: 2020-06-25T13:27:38.945+02:00 WARN  o.f.esl.client.inbound.Client - Failed to connect to [127.0.0.1:8021]
Jun 25 13:27:38 bbb1 bbb-fsesl-akka[1085]: 2020-06-25T13:27:38.947+02:00 WARN  o.f.esl.client.inbound.Client -   * reason: {}
Jun 25 13:27:38 bbb1 bbb-fsesl-akka[1085]: java.net.ConnectException: Connection refused
Jun 25 13:27:38 bbb1 bbb-fsesl-akka[1085]: #011at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
Jun 25 13:27:38 bbb1 bbb-fsesl-akka[1085]: #011at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:714)
Jun 25 13:27:38 bbb1 bbb-fsesl-akka[1085]: #011at org.jboss.netty.channel.socket.nio.NioClientSocketPipelineSink$Boss.connect(NioClientSocketPipelineSink.java:401)
Jun 25 13:27:38 bbb1 bbb-fsesl-akka[1085]: #011at org.jboss.netty.channel.socket.nio.NioClientSocketPipelineSink$Boss.processSelectedKeys(NioClientSocketPipelineSink.java:370)
Jun 25 13:27:38 bbb1 bbb-fsesl-akka[1085]: #011at org.jboss.netty.channel.socket.nio.NioClientSocketPipelineSink$Boss.run(NioClientSocketPipelineSink.java:292)
Jun 25 13:27:38 bbb1 bbb-fsesl-akka[1085]: #011at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
Jun 25 13:27:38 bbb1 bbb-fsesl-akka[1085]: #011at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:44)
Jun 25 13:27:38 bbb1 bbb-fsesl-akka[1085]: #011at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
Jun 25 13:27:38 bbb1 bbb-fsesl-akka[1085]: #011at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
Jun 25 13:27:38 bbb1 bbb-fsesl-akka[1085]: #011at java.lang.Thread.run(Thread.java:748)
Jun 25 13:27:38 bbb1 bbb-fsesl-akka[1085]: 2020-06-25T13:27:38.949+02:00 WARN  o.f.e.c.i.InboundClientHandler - Connection refused
Jun 25 13:27:38 bbb1 bbb-fsesl-akka[1085]: 2020-06-25T13:27:38.954+02:00 ERROR o.b.f.v.f.ConnectionManager - Failed to connect to ESL
Jun 25 13:27:39 bbb1 systemd_start.sh[1288]: #033[32minfo#033[39m: Added annotation id=w_8qdmbzhwdhzq-6-1593084459098 whiteboard=a7d2b7af0c776caf6307beb05abc385507a2b763-1593081748504/16
Jun 25 13:27:39 bbb1 bbb-fsesl-akka[1085]: 2020-06-25T13:27:39.315+02:00 DEBUG o.b.freeswitch.RxJsonMsgHdlrActor - handling to-voice-conf-redis-channel - {"envelope":{"name":"CheckRunningAndRecordingToVoiceConfSysMsg","routing":{"sender":"bbb-apps-akka"},"timestamp":1593084459314},"core":{"header":{"name":"CheckRunningAndRecordingToVoiceConfSysMsg","meetingId":"f3ab0ed3559d0b0398bfa735b3ad12946366d0ae-1593084293105"},"body":{"voiceConf":"964551","meetingId":"f3ab0ed3559d0b0398bfa735b3ad12946366d0ae-1593084293105"}}}
Jun 25 13:27:39 bbb1 bbb-fsesl-akka[1085]: 2020-06-25T13:27:39.316+02:00 INFO  o.b.f.v.f.FreeswitchApplication - Queue message: conference 964551 xml_list
Jun 25 13:27:39 bbb1 bbb-fsesl-akka[1085]: 2020-06-25T13:27:39.316+02:00 INFO  o.b.f.v.f.FreeswitchApplication - Sending message: conference 964551 xml_list
Jun 25 13:27:39 bbb1 bbb-fsesl-akka[1085]: 2020-06-25T13:27:39.316+02:00 INFO  o.b.f.v.f.FreeswitchApplication - Queue message: conference 964552 xml_list
Jun 25 13:27:39 bbb1 bbb-fsesl-akka[1085]: 2020-06-25T13:27:39.316+02:00 DEBUG o.b.freeswitch.RxJsonMsgHdlrActor - handling to-voice-conf-redis-channel - {"envelope":{"name":"CheckRunningAndRecordingToVoiceConfSysMsg","routing":{"sender":"bbb-apps-akka"},"timestamp":1593084459314},"core":{"header":{"name":"CheckRunningAndRecordingToVoiceConfSysMsg","meetingId":"df231cc19828555571d7ca3d6a17d3f9925a7bbe-1593084293106"},"body":{"voiceConf":"964552","meetingId":"df231cc19828555571d7ca3d6a17d3f9925a7bbe-1593084293106"}}}
Jun 25 13:27:39 bbb1 bbb-fsesl-akka[1085]: 2020-06-25T13:27:39.316+02:00 INFO  o.b.f.v.f.FreeswitchApplication - Sending message: conference 964552 xml_list

any ideas?

version: 2.2.17

**Comment by prlanzarin** [comment]
That's a FreeSWITCH crash. It automatically restarts so apart from the momentarily loss of audio, things should keep going.

For further debugging: point the core file default location to somewhere else other than the default ubuntu apport. Next time it happens, get it, compress and send for further debugging along with the output of `journalctl -u freeswitch.service`.

**Comment by SebastianZiegler** [comment]
no Problem:

Jun 24 10:08:57 bbb1 systemd[1]: freeswitch.service: Main process exited, code=killed, status=9/KILL
Jun 24 10:08:57 bbb1 systemd[1]: freeswitch.service: Unit entered failed state.
Jun 24 10:08:57 bbb1 systemd[1]: freeswitch.service: Failed with result 'signal'.
Jun 24 10:08:57 bbb1 systemd[1]: freeswitch.service: Service hold-off time over, scheduling restart.
Jun 24 10:08:57 bbb1 systemd[1]: Stopped freeswitch.
Jun 24 10:08:57 bbb1 systemd[1]: Starting freeswitch...
Jun 24 10:08:57 bbb1 freeswitch[14624]: 14625 Backgrounding.
Jun 24 10:09:00 bbb1 systemd[1]: Started freeswitch.
Jun 24 10:39:31 bbb1 systemd[1]: freeswitch.service: Main process exited, code=killed, status=9/KILL
Jun 24 10:39:31 bbb1 systemd[1]: freeswitch.service: Unit entered failed state.
Jun 24 10:39:31 bbb1 systemd[1]: freeswitch.service: Failed with result 'signal'.
Jun 24 10:39:31 bbb1 systemd[1]: freeswitch.service: Service hold-off time over, scheduling restart.
Jun 24 10:39:31 bbb1 systemd[1]: Stopped freeswitch.
Jun 24 10:39:31 bbb1 systemd[1]: Starting freeswitch...
Jun 24 10:39:31 bbb1 freeswitch[15982]: 15983 Backgrounding.
Jun 24 10:39:33 bbb1 systemd[1]: Started freeswitch.
Jun 24 12:29:13 bbb1 systemd[1]: freeswitch.service: Main process exited, code=killed, status=9/KILL
Jun 24 12:29:13 bbb1 systemd[1]: freeswitch.service: Unit entered failed state.
Jun 24 12:29:13 bbb1 systemd[1]: freeswitch.service: Failed with result 'signal'.
Jun 24 12:29:13 bbb1 systemd[1]: freeswitch.service: Service hold-off time over, scheduling restart.
Jun 24 12:29:13 bbb1 systemd[1]: Stopped freeswitch.
Jun 24 12:29:13 bbb1 systemd[1]: Starting freeswitch...
Jun 24 12:29:13 bbb1 freeswitch[23391]: 23392 Backgrounding.
Jun 24 12:29:16 bbb1 systemd[1]: Started freeswitch.
Jun 24 13:42:49 bbb1 systemd[1]: freeswitch.service: Main process exited, code=killed, status=9/KILL
Jun 24 13:42:49 bbb1 systemd[1]: freeswitch.service: Unit entered failed state.
Jun 24 13:42:49 bbb1 systemd[1]: freeswitch.service: Failed with result 'signal'.
Jun 24 13:42:49 bbb1 systemd[1]: freeswitch.service: Service hold-off time over, scheduling restart.
Jun 24 13:42:49 bbb1 systemd[1]: Stopped freeswitch.
Jun 24 13:42:49 bbb1 systemd[1]: Starting freeswitch...
Jun 24 13:42:49 bbb1 freeswitch[29876]: 29877 Backgrounding.
Jun 24 13:42:52 bbb1 systemd[1]: Started freeswitch.
Jun 24 15:21:31 bbb1 systemd[1]: freeswitch.service: Main process exited, code=killed, status=9/KILL
Jun 24 15:21:32 bbb1 systemd[1]: freeswitch.service: Unit entered failed state.
Jun 24 15:21:32 bbb1 systemd[1]: freeswitch.service: Failed with result 'signal'.
Jun 24 15:21:32 bbb1 systemd[1]: freeswitch.service: Service hold-off time over, scheduling restart.
Jun 24 15:21:32 bbb1 systemd[1]: Stopped freeswitch.
Jun 24 15:21:32 bbb1 systemd[1]: Starting freeswitch...
Jun 24 15:21:32 bbb1 freeswitch[14735]: 14736 Backgrounding.
Jun 24 15:21:34 bbb1 systemd[1]: Started freeswitch.
Jun 24 19:49:40 bbb1 systemd[1]: freeswitch.service: Main process exited, code=killed, status=9/KILL
Jun 24 19:49:40 bbb1 systemd[1]: freeswitch.service: Unit entered failed state.
Jun 24 19:49:40 bbb1 systemd[1]: freeswitch.service: Failed with result 'signal'.
Jun 24 19:49:40 bbb1 systemd[1]: freeswitch.service: Service hold-off time over, scheduling restart.
Jun 24 19:49:40 bbb1 systemd[1]: Stopped freeswitch.
Jun 24 19:49:40 bbb1 systemd[1]: Starting freeswitch...
Jun 24 19:49:40 bbb1 freeswitch[32562]: 32567 Backgrounding.
Jun 24 19:49:43 bbb1 systemd[1]: Started freeswitch.
Jun 25 09:51:39 bbb1 systemd[1]: freeswitch.service: Main process exited, code=killed, status=9/KILL
Jun 25 09:51:39 bbb1 systemd[1]: freeswitch.service: Unit entered failed state.
Jun 25 09:51:39 bbb1 systemd[1]: freeswitch.service: Failed with result 'signal'.
Jun 25 09:51:39 bbb1 systemd[1]: freeswitch.service: Service hold-off time over, scheduling restart.
Jun 25 09:51:39 bbb1 systemd[1]: Stopped freeswitch.
Jun 25 09:51:39 bbb1 systemd[1]: Starting freeswitch...
Jun 25 09:51:39 bbb1 freeswitch[26934]: 26936 Backgrounding.
Jun 25 09:51:42 bbb1 systemd[1]: Started freeswitch.
Jun 25 11:21:54 bbb1 systemd[1]: freeswitch.service: Main process exited, code=killed, status=9/KILL
Jun 25 11:21:54 bbb1 systemd[1]: freeswitch.service: Unit entered failed state.
Jun 25 11:21:54 bbb1 systemd[1]: freeswitch.service: Failed with result 'signal'.
Jun 25 11:21:54 bbb1 systemd[1]: freeswitch.service: Service hold-off time over, scheduling restart.
Jun 25 11:21:54 bbb1 systemd[1]: Stopped freeswitch.
Jun 25 11:21:54 bbb1 systemd[1]: Starting freeswitch...
Jun 25 11:21:54 bbb1 freeswitch[31036]: 31038 Backgrounding.
Jun 25 11:21:57 bbb1 systemd[1]: Started freeswitch.
Jun 25 13:27:36 bbb1 systemd[1]: freeswitch.service: Main process exited, code=killed, status=9/KILL
Jun 25 13:27:36 bbb1 systemd[1]: freeswitch.service: Unit entered failed state.
Jun 25 13:27:36 bbb1 systemd[1]: freeswitch.service: Failed with result 'signal'.
Jun 25 13:27:37 bbb1 systemd[1]: freeswitch.service: Service hold-off time over, scheduling restart.
Jun 25 13:27:37 bbb1 systemd[1]: Stopped freeswitch.
Jun 25 13:27:37 bbb1 systemd[1]: Starting freeswitch...
Jun 25 13:27:37 bbb1 freeswitch[5904]: 5905 Backgrounding.
Jun 25 13:27:39 bbb1 systemd[1]: Started freeswitch.

**Comment by SebastianZiegler** [comment]
seems only to happend on the real hardware devices. no problem on virtual mashines

**Comment by prlanzarin** [comment]
Weird. It's ending with SIGKILL, probably won't generate a core dump. Can you dig further in your system to see what is firing the signal (ie systemd)?

**Comment by basisbit** [comment]
did you maybe install the freeswitch-watchdog on your bbb server, while `hostname -f` does not point to your correct server fqdn?

**Comment by SebastianZiegler** [comment]
hostname -f point to the fqdn

I installed bbb via script, so I did install anything extra

@prlanzarin: in my first post is the syslog, where else should I look at?

**Comment by rfakit** [comment]
i had this problem and i reinstall bbb-freeswitch-core and it works for me

## apt install bbb-freeswitch-core --reinstall

**Comment by freescape** [comment]
> 
> 
> i had this problem and i reinstall bbb-freeswitch-core and it works for me
> ## apt install bbb-freeswitch-core --reinstall

This also just worked for me after a regular apt-get update broke it.

**Comment by alexanderjackson** [comment]
> i had this problem and i reinstall bbb-freeswitch-core and it works for me
> 
> ## apt install bbb-freeswitch-core --reinstall

In addition I had to run `apt install bbb-fsesl-akka --reinstall` to solve the issue.

**Comment by abraxaswd** [comment]
> 
> 
> > i had this problem and i reinstall bbb-freeswitch-core and it works for me
> > ## apt install bbb-freeswitch-core --reinstall
> 
> In addition I had to run `apt install bbb-fsesl-akka --reinstall` to solve the issue.

Thanks and confirmed after a regular update the freeswitch was not working. Doing the audio echo test did never stop and entering a room was not possible. After updating bbb-freeswitch-core AND bbb-fsesl-akka as described above no more errors in the log files and echo test no longer stuck. Perfect.

**Comment by MortezaTaghaddomi99** [comment]
I have the [same issue](https://github.com/bigbluebutton/bigbluebutton/issues/10409#issue-695824209).

**Comment by matiasilva** [comment]
Then please seek help in the standard way :)

**Comment by alexanderjackson** [comment]
> > i had this problem and i reinstall bbb-freeswitch-core and it works for me
> > ## apt install bbb-freeswitch-core --reinstall
> 
> In addition I had to run `apt install bbb-fsesl-akka --reinstall` to solve the issue.

In the meantime this will cause the echo test to stall/fail for new BBB installations performed after commit https://github.com/bigbluebutton/bigbluebutton/commit/8c21eca5dd538c1bd0a05733bf8c123f8896f1cc (properly update ESL password).

To solve this we added the following to `/etc/bigbluebutton/bbb-conf/apply-config.sh`:

```bash
[...]
#
# HOTFIX: Fix incorrect ESL password in /usr/share/bbb-fsesl-akka/conf/application.conf
#
ESL_PASSWORD=$(xmlstarlet sel -t -m 'configuration/settings/param[@name="password"]' -v @value /opt/freeswitch/etc/freeswitch/autoload_configs/event_socket.conf.xml)
sudo sed -i "s/ClueCon/$ESL_PASSWORD/g" /usr/share/bbb-fsesl-akka/conf/application.conf
```

@ffdixon FWIW: I don't think existing files in `/etc/bigbluebutton/` and ` /usr/share/bbb-fsesl-akka/conf/` should get overwritten without asking.

**Comment by kkplein** [comment]
ok, since upgrading to latest today, we are seeing this, and the echo test no longer works. :-( 
We do NOT have the file mentioned to edit above (/etc/bigbluebutton/bbb-conf/apply-config.sh) and we have reinstalled both bbb-freeswitch-core and bbb-fsesl-akka.

Fortunately it's dec 31, and the system is not heavily used now. But anyone with a tip on how to proceed now?

**Comment by ffdixon** [comment]
You should always run `sudo bbb-conf --setip` after each upgrade.  See https://docs.bigbluebutton.org/2.2/install.html#upgrading-from-bigbluebutton-22.

**Comment by Commifreak** [comment]
When this is required, why does the upgrade process doesnt run it automatically?

Gruß,
R. Kluth

**Comment by ffdixon** [comment]
There are three places to upgrade the ESL password, so rather than put it in individual .postinst files, we placed it in the `bbb-conf --setip` which is needed to upgrade other configuration files after each upgrade.

**Comment by kkplein** [comment]
Thank you Fred, @ffdixon! We updated our internal notes, and emphasized the importance of running sudo bbb-conf --setip xxx

(we never linked an auth error to "setip", but it helped!)

Happy new year to all! :-)

**Comment by badrelmers** [comment]
for me all your solutions did not work for me, but thanks to God I found the problem and solution.
I installed bbb in a container (nspawn+host network) with enabled ipv6, then I disabled ipv6 and forgot about it, this caused bbb to not listen at 8021. the logs were useless but looking in the config files cited by a user [here ](https://groups.google.com/g/bigbluebutton-setup/c/JdMuu8p8DbA) helped me to diagnose the problem:
this file ` /opt/freeswitch/conf/autoload_configs/event_socket.conf.xml` had this
`<param name="listen-ip" value="::"/>
`
value= should be 127.0.0.1 and not :: (ipv6 localhost)
 so I renabled ipv6 again and bbb worked again. I hope this helps someone.

**Comment by ffdixon** [comment]
Thanks for sharing this @badrelmers -- it will likely help others.

**Comment by bits-fritz** [comment]
Had to apply this fix, as after Update tonight. had to replace "ClueCon".
bbb-config --setip didn't do the job. 

> # HOTFIX: Fix incorrect ESL password in /usr/share/bbb-fsesl-akka/conf/application.conf
> #
> ESL_PASSWORD=$(xmlstarlet sel -t -m 'configuration/settings/param[@name="password"]' -v @value /opt/freeswitch/etc/freeswitch/autoload_configs/event_socket.conf.xml)
> sudo sed -i "s/ClueCon/$ESL_PASSWORD/g" /usr/share/bbb-fsesl-akka/conf/application.conf
> ```

apt history.log:

Start-Date: 2021-04-06  23:52:27
Commandline: apt upgrade
Upgrade: bbb-apps-video:amd64 (1:2.2.0-53, 1:2.2.0-54), bbb-apps:amd64 (1:2.2.0-55, 1:2.2.0-56), bbb-html5:amd64 (1:2.2.0-1144, 1:2.2.0-1157), bbb-record-core:amd64 (1:2.2.0-77, 1:2.2.0-78), bbb-etherpad:amd64 (1:2.2.0-75, 1:2.2.0-79), bbb-web:amd64 (1:2.2.0-155, 1:2.2.0-156), bbb-fsesl-akka:amd64 (2.2.0-78, 2.2.0-79), bbb-apps-screenshare:amd64 (1:2.2.0-55, 1:2.2.0-56), bbb-apps-akka:amd64 (2.2.0-103, 2.2.0-104), bbb-config:amd64 (1:2.2.0-239, 1:2.2.0-240), bbb-webrtc-sfu:amd64 (1:2.2.0-116, 1:2.2.0-117)
End-Date: 2021-04-06  23:53:11

**Comment by bwurst** [comment]
@bits-fritz Thank you, you saved my life as my servers did not work any more after the update yesterday!

**Comment by basisbit** [comment]
@bits-fritz @bwurst I suggest you to update your servers regularly (at least once per month), so you don't miss critical security updates.

**Comment by bwurst** [comment]
I do upgrades regularly (every single release!). But I ran into this error where the ESL password has had a mismatch.

To be honest: Please, please, please rename/alias the post-upgrade-stuff to something more obvious like "bbb-conf --upgrade". As the hostname is not optional for --setip, I shot me in the knee last time when I gave this command the wrong hostname. So I did not do --setip after the last upgrade because I thought it'll cause more trouble than it fixes. So I left the regular upgrade path and the workaround from @bits-fritz fixed the trouble.
Now, reading the comment from @ffdixon above, I will do --setip after every future upgrade.
