### ISSUE TITLE
Error 2200 when sharing webcam on demo version

### ISSUE THREAD

**Issue by shaditobia** [bigbluebutton/bigbluebutton#9939]
Hello 
I create the session on moodle . this Error 2200 appears when sharing webcam on demo version . 

thank you

**Comment by basisbit** [comment]
For support requests, please use the [forum / mailing list](https://groups.google.com/forum/#!forum/bigbluebutton-setup). This issue tracker here is only for BBB development related issues. Sorry.
Also, please provide a description of the actual problem, or at least use the issue template.

**Comment by matiasilva** [comment]
Also duplicate of #8637
