### ISSUE TITLE
Webcam Not Selectable in Chrome

### ISSUE THREAD

**Issue by lkiesow** [bigbluebutton/bigbluebutton#9943]
If a webcam is blocked by another process and BigBlueButton tries to select it, the whole selection ends up in an error state with (depending on your browser) no chance of recovery:

![Screenshot from 2020-06-25 11-50-04](https://user-images.githubusercontent.com/1008395/85855304-566aeb80-b7b6-11ea-89c2-9bd5da6556b1.png)

### Scenario Chrome:

- Use your first webcam in another tool (e.g. OBS to generate a new virtual Webcam with branding)
- Open a BBB meeting
- Try sharing your webcam

The result is that BBB will try to select a webcam and immediately end up in an error state with no way of recovery or to select another webcam.

### Scenario Firefox (Workaround available):

- Use your first webcam in another tool (e.g. OBS to generate a new virtual Webcam with branding)
- Open a BBB meeting
- Try sharing your webcam
- Firefox will open a dialog asking the user which webcam to share
    - If the user selects the blocked webcam, everything is broken in the same way it is in Chrome
    - If the user selects a non-blocked webcam, sharing will work

---

Tested under Linux with `/dev/video0` used by FFmpeg to generate a virtual webcam.
Tested with BigBlueButton version 2.2.19 and earlier versions.

**Comment by wagnger** [comment]
The error happens on my computer with the internal webcam even when it is not blocked by another process (checked according to https://www.howtogeek.com/289333/how-to-tell-which-application-is-using-your-windows-pcs-webcam/ ). If I open the test site with Firefox the webcam works as expected. (Windows 10 20H2,  Chrome 87.0.4280.88, Firefox 84.0)

**Comment by blinry** [comment]
For me, a workaround in Chrome was to first select the desired webcam [in the browser settings](chrome://settings/content/camera). I could then successfully select it in BBB.

**Comment by KaroBe** [comment]
@blinry could you specify the Chrome browser settings that lead to success for you? Selecting the OBS Virtual Camera in chrome://settings/content/camera did not work in my case.

**Comment by prlanzarin** [comment]
FYI this has been fixed in #11068 (still unreleased).

**Comment by blinry** [comment]
@KaroBe Yeah, exactly that setting allows me to select the virtual camera in Chromium 88.0.4324.96 on Arch Linux. Sucks that it doesn't work for you – hope the fix will soon be released and deployed everywhere! :)

**Comment by prlanzarin** [comment]
Landed in [v2.2.32](https://github.com/bigbluebutton/bigbluebutton/releases/tag/v2.2.32).
