### ISSUE TITLE
External video posted to a different concurrent meeting on the same server

### ISSUE THREAD

**Issue by ravi-ct** [bigbluebutton/bigbluebutton#9944]
**Describe the bug**
We had 2 concurrent meetings running on the same server when a youtube video that was posted (using share external video) by the moderator for one room started playing all of a sudden in the second meeting. We dug through the logs to find that it was indeed shared on the second meeting. The moderator who shared the video was definitely not present in the second meeting

**To Reproduce**
We didn't report it earlier because there was no easy way to reproduce it. I am happy to share the logs but will require some time to anonymize user names, etc. from inside the logs before I can do that. Please let me know if that will help.

**Expected behavior**
Content shared or presented in one meeting should never appear in another meeting.

**Actual behavior**
External video shared in one meeting started playing in another meeting.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, Mac]
 - Browser [e.g. Chrome, Safari]
A variety of devices and browsers were being used by viewers present in both the meetings at that time. The same experience was seen for all.

**Smartphone (please complete the following information):**
 - Browser [e.g. stock browser, Safari]
A variety of devices and browsers were being used by viewers present in both the meetings at that time. The same experience was seen for all.

**Additional context**
$ sudo bbb-conf --check

BigBlueButton Server 2.2.17 (1992)
Kernel version: 4.15.0-106-generic
Distribution: Ubuntu 16.04.6 LTS (64-bit)

**Comment by antobinary** [comment]
Hi @ravi-ct ,

Please post the exact BBB version you hit this on (current is 2.2.19). You can find it by running `# bbb-conf --check`
We spotted an issue like that a number of months back and corrected it. Looking forward to hearing the BBB version

**Comment by ravi-ct** [comment]
Updated the issue with the BBB version. It's 2.2.17.

**Comment by ravi-ct** [comment]
Hi @antobinary 

Any pointer as to where the issue might be? We run a fairly large multi-tenant operation and we hit the issue a second time. Some pointer might help us to zero in on a fix that we can contribute back.

Thanks in advance.

**Comment by sergiocauich** [comment]
Hola @ravi-ct .

I have had the same problem and the version of the server is:

BigBlueButton Server 2.2.23 (2106)
                    Kernel version: 4.15.0-122-generic
                      Distribution: Ubuntu 16.04.7 LTS (64-bit)
                            Memory: 32888 MB
                         CPU cores: 8
I have not been able to replicate the error and when checking xml in the raw directory of the meeting there is no traces of the url of the video.

I would appreciate any support.

Greetings.

**Comment by ffdixon** [comment]
We've fixed that in the more recent versions of BigBlueButton.  Can you update to the latest version (2.2.30 at the time of this post) and let us know if the problem occurs again.

**Comment by sergiocauich** [comment]
Hi @ffdixon 

Good day.

Thank you very much for your answer I update the version and as you suggest I will be testing.

Just a question trying to find the source meeting of the video in the raw files that were generated in the archive process, I was not able to find the url of the video or some event that tells me which meeting the video comes from.

Any way to identify this either by the logs or by the raw?

Thank you very much for your help.
