### ISSUE TITLE
detect one problem with 1006

### ISSUE THREAD

**Issue by aztrock** [bigbluebutton/bigbluebutton#9948]
**Describe the bug**
When try activated mic in bbb-html, bbb-html send error 1006, FreeSwitch return Bad From Header, is because have two ':' in the name bbb build From header bad

**To Reproduce**

1, Join to conference whit name 1:x:1
2. Tray activate mic

**Expected behavior**
```
From: "w_cnhms7mlxogg_11-bbbID-1:x:1" <sip:w_cnhms7mlxogg_11-bbbID-1:x:1@x.x.x.x>;tag=rdaqf4d582
```

fs return
```
SIP/2.0 400 Bad From Header
Via: SIP/2.0/WSS adv22361rmns.invalid;branch=z9hG4bK2611908;received=66.175.213.96;rport=33574
To: <sip:echo67140@x.x.x.x>;tag=83KH6Qv0vey5B
Call-ID: 082p93nag8bsrihaprv4
CSeq: 8004 INVITE
Content-Length: 0
```

**Screenshots**
![image](https://user-images.githubusercontent.com/4043932/85881789-cfad1300-b7a3-11ea-9496-6af8df8a9da8.png)
![image](https://user-images.githubusercontent.com/4043932/85881920-0a16b000-b7a4-11ea-93aa-36dd9e8bc37e.png)

**BBB version (optional):**
BigBlueButton continually evolves. Providing the version/build helps us to pinpoint when an issue was introduced.
Example:
$ sudo bbb-conf --check | grep BigBlueButton
BigBlueButton Server 2.2.18 (2040)

**Desktop (please complete the following information):**
 - OS: Windows, Linux
 - Browser: Chrome, Firefox
 - Version unknown, Firefox Dev

**Comment by matiasilva** [comment]
I can reproduce this on test.bigbluebutton.org

**Comment by ffdixon** [comment]
This is an edge case where it shouldn't be very likely that a user's name has `:x:`.  Still, it's a bug and thanks for the very clear steps to reproduce.

**Comment by lim-on-air** [comment]
Hi, 
I got a 1006 error too but with a "normal" name (only diactritics in the name : "Jérémie").
I am on macos 10.15.6 and firefox 82.0.3.
With Chrome, it's ok.
