### ISSUE TITLE
One to one camera between moderator and attendees

### ISSUE THREAD

**Issue by ajithgopi** [bigbluebutton/bigbluebutton#9950]
Hi, it would be a great feature of the students couldn't see or hear each other... Or maybe just the audio is okay.

**Comment by matiasilva** [comment]
Hi @ajithgopi. Presently, this feature exists already. You can restrict webcams to be only visible to moderators, so students see themselves and any moderators but not other students. As for audio, there is an existing issue for this #9915.

**Comment by ajithgopi** [comment]
Thanks for the info.
