### ISSUE TITLE
getting 500 error after bb installation while clicking join

### ISSUE THREAD

**Issue by chaithukjp** [bigbluebutton/bigbluebutton#9951]
**Describe the bug**
Getting java.lang.NullPointerException error code 500 after clicking join button from main page.

**Installation type**
 bbb-install s

**Firewall and IP address type**
Is your server behind a NAT or firewall? Does your BBB server have its own IPv4 addres?

**Console output**
Please include the full console output from the install.

**Additional context**

Status Code | 500
-- | --
Exception Type | null
Message | null
Exception | java.lang.NullPointerException 	at org.apache.jsp.demoHTML5_jsp.getJoinURLExtended(demoHTML5_jsp.java:259) 	at org.apache.jsp.demoHTML5_jsp._jspService(demoHTML5_jsp.java:1257) 	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70) 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731) 	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:439) 	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:400) 	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:344) 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731) 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303) 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) 	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241) 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:221) 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122) 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505) 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169) 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103) 	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:956) 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116) 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:436) 	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1078) 	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:625) 	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316) 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) 	at java.lang.Thread.run(Thread.java:748)
Root Cause |  

output for bb conf-- check
#  /var/lib/tomcat7/demo/bbb_api_conf.jsp: mydomain.com
................................................................................
# Error: Could not connect to the configured hostname/IP address
#
#    https://mydomain.com/
#
# If your BigBlueButton server is behind a firewall, see FAQ.
# Error: Unable to connect to port 1935 (RTMP) on mydomain.com
# Warning: The setting of 35.184.4.138 for proxy_pass in
#
#    /etc/bigbluebutton/nginx/sip.nginx
#
# does not match the local IP address (10.128.0.3).
# (This is OK if you've manually changed the values)
# Warning: The API demos are installed and accessible from:
#
#    https://mydomain.com
#
# and
#
#    https://mydomain.com/demo/demo1.jsp
#
# These API demos allow anyone to access your server without authentication
# to create/manage meetings and recordings. They are for testing purposes only.
# If you are running a production system, remove them by running:
#
#    apt-get purge bbb-demo
# Error: Unable to reach default URL for presentation:
#
#    https://mydomain.com/default.pdf
#
# Check value for beans.presentationService.defaultUploadedPresentation in
#   /usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties
root@bbb:/etc/bigbluebutton/nginx#

**Comment by matiasilva** [comment]
Hi, thanks for posting. Please forward your question to https://groups.google.com/forum/#!forum/bigbluebutton-setup where it will be better handled. See you there!
