### ISSUE TITLE
Fails to connect with Samsung Galaxy s* default browser (Samsung Internet)

### ISSUE THREAD

**Issue by amohideen** [bigbluebutton/bigbluebutton#9952]
The error message is:

It looks like you are using an older version of a supported browser. Please upgrade your browser for full support.

However, I have the latest software on the phone.
!
![Screenshot_20200627-052618_Samsung Internet](https://user-images.githubusercontent.com/16897993/85933762-d5eddd00-b8d2-11ea-9a2b-1c180055a9f0.jpg)

**Comment by ffdixon** [comment]
What is the output of this URL from the tablet: https://test.bigbluebutton.org/html5client/useragent

**Comment by amohideen** [comment]
Samsung Internet 11.2.0 / Android 0.0.0

**Comment by KiriraJames** [comment]
What I got..

Samsung Internet 11.2.0 / Android 6.0.1

**Comment by ffdixon** [comment]
It looks like the `Samsung Internet 11.2.0` browser [supports webrtc](https://caniuse.com/#search=webrtc).  You can modify the list of browsers that BigBlueButton will support by adding this browser to BigBlueButton's supported list, see

  https://docs.bigbluebutton.org/2.2/troubleshooting.html#the-browser-is-not-supported

**Comment by basisbit** [comment]
Nowadays the majority of devices should support webrtc, maybe the supported webbrowsers whitelist could be changed to a blacklist, thus nit requiring so many adjustments for bigger bbb setups with bigger variety of users devices.

**Comment by KiriraJames** [comment]
Hi, could you please add it to the HTML5 client on the demo site?

**Comment by amohideen** [comment]
Affirmative.

**Comment by amohideen** [comment]
- browser: Samsung Internet
    version: [6, 0.1]

**Comment by mcferdev** [comment]
> Nowadays the majority of devices should support webrtc, maybe the supported webbrowsers whitelist could be changed to a blacklist, thus not requiring so many adjustments for bigger bbb setups with bigger variety of users devices.

Would be lovely... there are some problems when using webview on Android devices as well.

**Comment by nguyenxuanhoa493** [comment]
add to /usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml
minBrowserVersions:  
- browser: Samsung_Internet
    version: 10
  - browser: SamsungInternet
    version: 10

**Comment by amohideen** [comment]
Roger that. I will make the changes in my yml file.

Indeed I did add it earlier, however, I now have realised that I left a
space between  Samsung and Internet. I should have put it like
Samsung_Internet. My bad.

**Comment by matiasilva** [comment]
Be sure to close the issue when it has been solved :)

**Comment by fireba11** [comment]
How about adding that to the defaults?
Samsungs browser is chromium-based in recent versions so not much testing is needed, it works with v10 as shown above for us.

**Comment by matiasilva** [comment]
Please submit a pull request if you can!
