### ISSUE TITLE
Disable popup with presentation filename when entering a room

### ISSUE THREAD

**Issue by pbdco** [bigbluebutton/bigbluebutton#9956]
Add this feature to settings file in order to be able to deactivate this popup. 

Example: presentationnamepopup = false

![image](https://user-images.githubusercontent.com/64397076/86021186-35e1a200-b9ff-11ea-8a3d-f1f5a3212e4b.png)

**Comment by tylercopeland** [comment]
@pbdco thank you for sharing this issue. Just to confirm, this is the toast notification that you are referring to, correct? 

![Screen Shot 2020-06-29 at 9 50 06 AM](https://user-images.githubusercontent.com/1273169/86025283-05e4cf80-b9fc-11ea-8905-ed375435b389.png)

**Comment by tylercopeland** [comment]
@pbdco - I brought this topic up with one of our core developers, and the presentation notification is part of our efforts to ensure BigBlueButton is an accessible product. This toast message is used to notify a screen reader user of the current presentation. 

In the screenshot above, one idea would be to increase the z-index of the dark overlay, so the toast notification is behind, and the main action is focused on the user selecting an audio type.

**Comment by pbdco** [comment]
> @pbdco thank you for sharing this issue. Just to confirm, this is the toast notification that you are referring to, correct?
> 
> ![Screen Shot 2020-06-29 at 9 50 06 AM](https://user-images.githubusercontent.com/1273169/86025283-05e4cf80-b9fc-11ea-8905-ed375435b389.png)

@tylercopeland - Yes indeed, that's the popup.



> @pbdco - I brought this topic up with one of our core developers, and the presentation notification is part of our efforts to ensure BigBlueButton is an accessible product. This toast message is used to notify a screen reader user of the current presentation.
> 
> In the screenshot above, one idea would be to increase the z-index of the dark overlay, so the toast notification is behind, and the main action is focused on selecting their audio.

I understand. I think it would be nice to have this feature available on the settings file in order to disable/enable it for specific use cases.

**Comment by pbdco** [comment]
Hey guys any update on this?

**Comment by ffdixon** [comment]
None at the moment. We'll leave it in place for the moment as it's only visible for a few minutes and does serve an important role for accessiblity.

**Comment by jdaviescoates** [comment]
I'd also like this pop-up to be optional (especially given it often gets displayed twice or even 4 times on mobiles as per #10266).  

But even better would be the option to not have a presentation loaded by default at all!  

That way there would also be no need to always have the notification for accessibility reasons either, because there would be no presentation. That would be my preference by far!

I'm just searching through the issues at the moment to see if anyone else has suggestion this, if not I'll create a new issue about it...

**Comment by matiasilva** [comment]
Remove the default presentation and it won't be loaded.

**Comment by jdaviescoates** [comment]
Great, but remove it how @matiasilva?  the BBB instance I'm using has the Greenlight frontend and I can't see anywhere I can remove it.  I can only see an option to add a presentation, not remove the already existing default one.

![no_remove_presentation_option](https://user-images.githubusercontent.com/2113743/94018390-78214200-fda8-11ea-83c3-7e1cc06a1bcd.png)

**Comment by antobinary** [comment]
> We'll leave it in place for the moment as it's only visible for a few minutes and does serve an important role for accessibility.
