### ISSUE TITLE
Recordings not found

### ISSUE THREAD

**Issue by walid-Dev-TN** [bigbluebutton/bigbluebutton#9957]
I don't understand why the recordings are not published, 
when i execute "bbb-record --list" i got this message:
---------------------------------------------------------------------------------------------------------------------
bbb-rap-publish-worker.service - BigBlueButton recording and playback publish worker
   Loaded: loaded (/usr/lib/systemd/system/bbb-rap-publish-worker.service; static; vendor preset: enabled)
   Active: inactive (dead)
Condition: start condition failed at Mon 2020-06-29 17:19:33 CEST; 11ms ago
           ConditionPathExistsGlob=/var/bigbluebutton/recording/status/processed/*.done was not met
---------------------------------------------------------------------------------------------------------------------

thank you for replying

**Comment by matiasilva** [comment]
Hi, thanks for posting. Your support issue would be better handled here: https://groups.google.com/forum/#!forum/bigbluebutton-setup.
