### ISSUE TITLE
Can we install BigBlueButton on Kubernetes Infrastructure?

### ISSUE THREAD

**Issue by akash2213348** [bigbluebutton/bigbluebutton#9959]
Hi,
I have installed BigBlueButton on 32GB and 16vCPUs but now I want to install on kubernetes as its infrastructure is best in industry and I think it can easily scale load of  BigBluebutton. 

but I didn't find any document related to Kubernetes installation and I also want to know how BigBlueButton for IP and domain name? As we need to wish-list (domain or IP) before use.

Kindly let me know weather we can install it on Kubernetes, Is there any way? Thanks...

Regards,

Akash Sharma

**Comment by matiasilva** [comment]
Hi @akash2213348, I saw your post in the development forum. Let's keep discussion there.

**Comment by nemobis** [comment]
For those wondering, I suppose that's https://groups.google.com/g/bigbluebutton-dev/c/726_8n8bKxI
