### ISSUE TITLE
Check participants attention

### ISSUE THREAD

**Issue by jasmines** [bigbluebutton/bigbluebutton#9960]
Is there any development idea to check attendance attention during the conference?
I'm referring to the features other platforms have (see Cisco Webex):
https://help.webex.com/en-us/st7tr1/Track-Participant-Attention-in-Cisco-Webex-Training

Sorry if this question is obsolete or not relevant, I searched through the tracker and didn't find anything.

**Comment by matiasilva** [comment]
Hm..I'm not sure if the web browser is capable of detecting if another app is on top of it or if it has been minimized. I believe it can tell if another tab is focused, but that could be the student working on something else. As I see it, this is somewhat privacy invasive. It's not really the business of the presenter what the participants are doing. Thoughts? 

(and no, if you don't see it here in the issue tracker, chances are nobody is working on it but you can always start discussion as you have or submit a pull request if you have developed the changes)

**Comment by basisbit** [comment]
@jasmines why don't you just create a poll and have everyone choose an answer. Then you know who is actually participating and who isn't.

Tracking who still has main application focus on the meeting doesn't really help you in tracking if people are still participating or if they are for example cooking dinner or whatever, while having muted the audio. Also, many people use OneNote or similar apps to write down notes. Those people will show up in WebEx as not "paying attention" when in fact they actually are paying attention.

Anyways, the "attention tracking" approach which you suggested can't be implemented for a webbrowser app, thus I suggest closing this issue.

**Comment by iSamof** [comment]
There are many presentations for which this information is helpful. GoToWebinar also provides such information including percentage focus overall and per attendee. Given that it is not mandatory for moderators to use such info, those who wish to, can do so ... assuming it is technically do-able.

The privacy issue can be taken care of via the privacy policy. The suggestion is not to eavesdrop on what the user is actually doing outside of the presentation/class/webinar but rather whether the focus is on the presentation or not. 

The info would certainly help me determine which of my material is of greater interest to the audience and which require enhancement.

**Comment by matiasilva** [comment]
Couldn't you just ask the audience what they thought of your material? Or use the feedback form? We may be starting to get into some feature creep. If, however, you think this is worth pursuing some more concrete application (mockups, potential code changes, technical details) would be helpful for further discussion.

**Comment by iSamof** [comment]
In some cases, user actions speak louder than their words. In this particular case (user attention), the stats probably provide a more accurate picture than asking them directly. 

As for mocks ups and the like, I'd leave that to those to the OP, except to say that this feature is of course nothing new. It has been a part of Webex and GoToWebinar for a long time ... at least a decade for GoToWebinar. 

Lastly, I'd say this is useful but not a high priority. I recongise the dev team have to remain focused on priority items and in mind those are: performance, capacity (increase, i.e. number of attendees/meeting and per server) etc which are being discussed in other threads.

**Comment by jasmines** [comment]
I'm afraid my objective is not clear to all.
Many Italian laws regarding mandatory learning (some workers category MUST do courses) set requirements of courses, platforms and so on.
The attendance attention feature (for the platform, in this case) is mandatory for some of those laws, and it may be one of the main parameters to choose the platform.
Anyway, mine is only a proposal for developers.
The feature could be simple and check only the window focus, or more complex, with a face detection technology (https://realpython.com/face-detection-in-python-using-a-webcam)...

**Comment by basisbit** [comment]
Please post links to those laws.

**Comment by jasmines** [comment]
> Please post links to those laws.

They're in Italian, I should search for them, but mind that such requirements can be written also in particular private or public competition announcements, calls for bids, invitations to tender and so on...

**Comment by matiasilva** [comment]
If people go for a simple implementation, then what's the point of having it at all? It should either be a reliable, dependable metric or not exist. People have also mentioned other tools but a reminder that BigBlueButton is supposed to provide the highest-quality teaching experience, it's not meant for webinars or corporate meetings though people may be using it as such. I'm not entirely convinced this is a feature that should be highly prioritized given the goal above.

**Comment by iSamof** [comment]
@matiasilva - Please bear in mind, in a classroom scenario the tutor can visual clues from the students' behaviour and amend his lecture to keep their attention.

In remote learning, this is a valuable mechanism and metric for the effectiveness of the content and/or delivery. Asking students (that he will be grading) about how good the lecture was on results in medium to great responses. 

No student or attendee is going to come back and say ... you know, it was all good until the 24th minute, then it was a bit boring, so I was checking my emails. But once you mentioned "quantum indeterminacy" at the 37th minute my ears perked up and I came back to your lecture.

As I said in my previous response, for us this is a useful feature for our (business) presentations. But you reminded me of BBB's focus and for the eductors, this feature may be much more important. We won't know unless we get more people's feedback.

Let me leave you with the NASA engineers' favourite quote (which has become my favourite too ... as I keep telling my developers): One test is worth a  thousand expert opinions :-)

Maybe a survey of the BBB educators will reveal the priority of this feature.

**Comment by cod3r0k** [comment]
Dear All, Can we use this method? (http://jsfiddle.net/meehanman/40edh944/)

Could you help me to embed this and have this option for moderator usage to check the participant's attention?

How can we embed this simple and fine javascript code (which run in each participants browser and show it's value in BBB user section?)?

**Comment by iSamof** [comment]
@cod3r0k - There is a (fantastic) "layout manager" coming soon. See [#8729](https://github.com/bigbluebutton/bigbluebutton/pull/8728)

You may benefit from waiting for that release and adding your code there.

**Comment by matiasilva** [comment]
The above two issues mentioned exporting user entry and exit times. This information is already provided by the events.xml file, so I'm not sure what additional functionality the two issues seek.

**Comment by cod3r0k** [comment]
> The above two issues mentioned exporting user entry and exit times. This information is already provided by the events.xml file, so I'm not sure what additional functionality the two issues seek.

Dear @matiasilva , Thanks. How can I get it's information? Could we get it during the session? Or we just see them in the recording files?

**Comment by matiasilva** [comment]
You can get the participants names during the session at any given point. The `events.xml` file is generated in the recordings folder, yes: https://docs.bigbluebutton.org/dev/recording.html#events-outline

**Comment by cod3r0k** [comment]
> ents.xml

Thanks, We must update to the latest version to achieve this. Is it right?

**Comment by amg-web** [comment]
> You can get the participants names during the session at any given point. The `events.xml` file is generated in the recordings folder, yes: https://docs.bigbluebutton.org/dev/recording.html#events-outline

How are you going to explain it to the teacher?

Teachers need simple and easy way jist from web inteface.

**Comment by matiasilva** [comment]
> 
> 
> > ents.xml
> 
> Thanks, We must update to the latest version to achieve this. Is it right?

You just need to find this in the recording folder, it's been available for a while, no need to update :)

**Comment by matiasilva** [comment]
> > You can get the participants names during the session at any given point. The `events.xml` file is generated in the recordings folder, yes: https://docs.bigbluebutton.org/dev/recording.html#events-outline
> 
> How are you going to explain it to the teacher?
> 
> Teachers need simple and easy way jist from web inteface.

I would be tempted to say: provision this from whatever front-end you are using. imo it would be cleaner to do the parsing and filtering server-side then make that available via the frontend (kind of like the moodle integration does).

**Comment by basisbit** [comment]
> So I think the solution would be to record the sessions with camera on and have someone randomly check the recordings to confirm that the lawyer was indeed in front of the computer and paying attention. You can do random "confirmation test" just like random auditing of taxes.

Luckily this would not be legal thanks to data protection laws in many countries. You are trying to find a technical solution for a non-technical problem here. The random person checking some of the videos would have to know the participants to be able to verify they are the ones who signed up.
As an alternative if you actually need the participation check, have the presenter require everyone to show their passport/ID card with picture at the beginning of the session and have the presenter compare the ID card picture with the actual person on the webcam. This can be done using the 1 to N webcams mode so others don't get to see the ID card details and so on. Of course there exist tools/filters which make you look like someone else, but that is why you required the passport/id card to be shown.

**Comment by ritzalam** [comment]
> > So I think the solution would be to record the sessions with camera on and have someone randomly check the recordings to confirm that the lawyer was indeed in front of the computer and paying attention. You can do random "confirmation test" just like random auditing of taxes.
> 
> Luckily this would not be legal thanks to data protection laws in many countries. You are trying to find a technical solution for a non-technical problem here. The random person checking some of the videos would have to know the participants to be able to verify they are the ones who signed up.
> As an alternative if you actually need the participation check, have the presenter require everyone to show their passport/ID card with picture at the beginning of the session and have the presenter compare the ID card picture with the actual person on the webcam. This can be done using the 1 to N webcams mode so others don't get to see the ID card details and so on. Of course there exist tools/filters which make you look like someone else, but that is why you required the passport/id card to be shown.

Of course, you would inform the user the whole process. That the session is recorded and that the user need to provide a photo id to be shown in the camera. Though this would be out of BBB and should be in a 3rd party valued added application.

**Comment by keunes** [comment]
> The above two issues mentioned exporting user entry and exit times. This information is already provided by the events.xml file, so I'm not sure what additional functionality the two issues seek.

To get back to your original question, @matiasilva, I think the following sums up what we were looking for when testing BBB to see if it fits our purposes:
> it would be great if the current simple text export of the participant names, could be extended into a file (e.g. CSV) that also contains their join timestamp and maybe even their leave timestamp. With both join & leave time, we can calculate the duration of their participation, and e.g. only count the users that stayed, say, for 85% of the webinar duration.

Just to check I understood correctly, are you suggesting that since we were doing our tests, such feature has been implemented? (If yes, that'd be of great interest of work, and probably warrant another review of BBB).

**Comment by matiasilva** [comment]
@keunes the feature has always been with BigBlueButton since 2.0 (or earlier?). You do however need access to the server backend and the `events.xml` file. This is how the Moodle plugin can track student attendance, participation time, attention span, etc.

**Comment by keunes** [comment]
Thanks @matiasilva. Then let me reply to your earlier comment:
> The above two issues mentioned exporting user entry and exit times. This information is already provided by the events.xml file, so I'm not sure what additional functionality the two issues seek.

My request (#10009) asks to include the join (& leave) time in the participant report that is accessible to 'simple' event creators. This is not possible yet, so that's the additional functionality I'm seeking. (For an organisation like the one I work for - we organise quite a lot of trainings for teachers - asking our sysad for an export after each event is not feasible.)

**Comment by matiasilva** [comment]
It is possible, but it is a task for a front-end which is outside of the BigBlueButton scope. If you say, modified Greenlight, to read parse the events.xml file and extracted the times and dates (and a lot more information), then you could get this information very easily. There is even a ruby gem for this: https://github.com/bigbluebutton/bbb-events.

**Comment by keunes** [comment]
I see. Will request under Greenlight, then.

**Comment by keunes** [comment]
@matiasilva Seems it is not within Greenlight's scope - see the linked ticket in my previous post. So then it _is_ a task for BigBlueButton...

**Comment by keunes** [comment]
Ping to keep open

**Comment by ffdixon** [comment]
In the upcoming BigBlueButton 2.4 we have the [Learning Dashboard](https://docs.bigbluebutton.org/2.4/new.html) that gives the instructor a view of attendance for all users.  

See overview video: https://www.youtube.com/watch?v=yZrNYSxIIYk.

Take a look and let us know if this gives you the attendance reporting you are looking for.

**Comment by amg-web** [comment]
> Take a look and let us know if this gives you the attendance reporting you are looking for.

Nice. is it possible to get this info after meeting is over?

**Comment by keunes** [comment]
That looks great @ffdixon and indeed really quite advanced! In addition to @amg-web's question, I would be wondering if this data can be exported. It would greatly help with creating reports.

**Comment by keunes** [comment]
I see [on this blog](https://higheredlab.com/how-to-check-bigbluebutton-learning-dashboard-after-the-session/) that learning dashboard data is deleted automatically after session end, but that this can be changed via configuration. I also found in the docs that since 2.5 [learning analytics data can be exported as CSV](https://docs.bigbluebutton.org/2.5/new.html#download-data-as-csv). With that, rather than marking this issue as stale, I think it can be closed as Completed.
