### ISSUE TITLE
The webcam disconnect when you start recording after hours without recording in Firefox

### ISSUE THREAD

**Issue by albacodina** [bigbluebutton/bigbluebutton#9961]
**Steps to Reproduce:**
* Connect to bbb using webcam in Firefox.
* Wait 6 hours
* Start to record the room
* Continue recording for 1 hour

**Expected behaviour:**
* The recording finishes correctly

**Actual behaviour:**
* After an hour, the webcam disconnects from the videoconference and the camera button switches to offline. Trying to click it has no effect, stays blocked in trying to establish a connection.

**Desktop:**
 - Browser : Mozilla Firefox

**Comment by basisbit** [comment]
This sounds like a firewall / connection keep-alife time issue.
