### ISSUE TITLE
TURN configuration 

### ISSUE THREAD

**Issue by chandee77** [bigbluebutton/bigbluebutton#9974]
I set up coturn server and configure it with bbb as discribed (since my server is behind firewall I got ICE1007 and 1020 error with initial setup other than that everything worked well)
but after setting up turn server and restating bbb  gives following result

 
# Potential problems described below
# IP does not match:
#                           IP from ifconfig: 10.10.106.8
#   /etc/nginx/sites-available/bigbluebutton: katha.nso.gov.lk
# Not running:  tomcat7 or grails LibreOffice
................................................................................
# Error: Could not connect to the configured hostname/IP address
#
#    https://XX.XXXX/
#
# If your BigBlueButton server is behind a firewall, see FAQ.

# Warning: The setting of X.X.X.X for proxy_pass in
#
#    /etc/bigbluebutton/nginx/sip.nginx
#
# does not match the local IP address (10.10.106.8).
# (This is OK if you've manually changed the values)

nginx —————————————————► [✔ - active]
freeswitch ————————————► [✔ - active]
redis-server ——————————► [✔ - active]
bbb-apps-akka —————————► [✔ - active]
bbb-transcode-akka ————► [✔ - active]
bbb-fsesl-akka ————————► [✔ - active]
red5 ——————————————————► [✔ - active]
tomcat7 ———————————————► [✔ - active]
mongod ————————————————► [✔ - active]
bbb-html5 —————————————► [✔ - active]
bbb-webrtc-sfu ————————► [✔ - active]
kurento-media-server ——► [✔ - active]
etherpad ——————————————► [✔ - active]
bbb-web ———————————————► [✘ - activating]

fron client side I get 

Server Error
Invalid XXX(server name)  Endpoint and Secret

but before changing TURN configuration it was fine
any sujession

**Comment by matiasilva** [comment]
Hi, please your our support forum for help requests like this one: https://groups.google.com/forum/#!forum/bigbluebutton-setup
