### ISSUE TITLE
Audio/Video not supported on Safari/Chrome

### ISSUE THREAD

**Issue by Saif-S** [bigbluebutton/bigbluebutton#9975]
Using Api-Demo

ScreenShot of Safari OS

<img width="1440" alt="imgpsh_fullsize_anim" src="https://user-images.githubusercontent.com/59909627/86360957-bf5bd300-bc90-11ea-911b-26cb4ca75382.png">

ScreenShot of Chrome --- Windows 10

![2020-07-02 18_29_45-BigBlueButton - Demo Meeting](https://user-images.githubusercontent.com/59909627/86362079-655c0d00-bc92-11ea-9cf7-650dc85c3063.png)

**Comment by prlanzarin** [comment]
You haven't set BBB with HTTPS. WebRTC only works with HTTPS. Next time, post such support request in the mailing lists, please.

**Comment by Saif-S** [comment]
ThankYou
