### ISSUE TITLE
Ability to change name in participants list

### ISSUE THREAD

**Issue by bigbluebutton-issue-import** [bigbluebutton/bigbluebutton#998]
Originally reported on Google Code with ID 243

```
It would be nice to allow the users to change their display name in the
participants list.

Perhaps they could right-click it, choose "change display name" and then
have a small modal that would allow the change to be made.
```

Reported by `jeremythomerson` on 2009-11-12 01:37:47

**Comment by ffdixon** [comment]
Closing this issue -- we're not going to be letting users change their name.

**Comment by ambiso** [comment]
@ffdixon is this a feature you are against or one that you would be fine with if it existed but don't want to spend resources on implementing this feature right now?

**Comment by matiasilva** [comment]
I personally agree that the users shouldn't be allowed to change their name. When joining via a frontend like Greenlight, the user can already choose what name to provide the BBB API. When joining via Moodle or another LMS, then the names should match what's on the LMS.

**Comment by JFQueralt** [comment]
That is not entirely productive. In many cases you'll need users to be named in a specific way (for instance to quickly create breakout sessions and you can't be asking them to go out and come back to just to change their names.

**Comment by karlbeecken** [comment]
I think it actually is an important feature, as names can be used to specify group membership and stuff like that.

**Comment by rselimh** [comment]
Maybe it would be nice to add a reminder then that the username can not be changed later during the session

**Comment by alexgarel** [comment]
My user story: I enter a meeting but forgot to specify which organization I'm part of. I then see everyone did specify it and find it really useful… I search for the feature to change my name… but can't find it.
