### ISSUE TITLE
Sharing server among associations: Reservation calendar

### ISSUE THREAD

**Issue by rosa2** [bigbluebutton/bigbluebutton#9981]
Hello and thanks very much for your software

**Is your feature request related to a problem? Please describe.**
The server infrastructure for a BigBlueButton is expensive for one small organization, so we are trying to share among several small social organizations that will use it once a week or less. We have the problem that if we make connections at the same time the server can be overload.

**Describe the solution you'd like**
We would like to have a calendar for reservations. Is there a software that can be used? If not, could you please consider to implement it, please?

Thanks a lot for this excellent soft and your care for our privacy :)

**Comment by basisbit** [comment]
For support requests, please use the [forum / mailing list](https://groups.google.com/forum/#!forum/bigbluebutton-setup). This issue tracker here is only for BBB development related issues. Sorry.
