### ISSUE TITLE
Error 1020 when sharing webcam

### ISSUE THREAD

**Issue by victorvoltarelli** [bigbluebutton/bigbluebutton#9983]
Hello guys, yesterday we was able to use bbb normally.

Today we are receiving error 1020 while sharing webcam at Wi-Fi connection. But when i connect via 4G in my celphone everything works normally.

Any idea to solve the problem?

Thank you.

**Comment by basisbit** [comment]
For support requests, please use the [forum / mailing list](https://groups.google.com/forum/#!forum/bigbluebutton-setup). This issue tracker here is only for BBB development related issues. Sorry.

Also, see https://docs.bigbluebutton.org/2.2/configure-firewall.html#updating-kurento

**Comment by matiasilva** [comment]
Hi. Please use your favorite search engine to look up the solutions to your problem. This issue tracker and the google groups are all indexed so you should be able to find a solution there.
