### ISSUE TITLE
Only Audio working after using Turn server

### ISSUE THREAD

**Issue by elcssmouhsine** [bigbluebutton/bigbluebutton#9985]
For some reason bbb stopped working in our country, it seems the Internet provider decided to block webrtc maybe, but we managed to setup a Turn server and use it with bbb , but only Audio is now working , Camera/Screen share does not work.
is there any solution to this.

i get this message in chrome console : 

[22:41:24:0283]  WARN: clientLogger: Could not play video tag due to AbortError https://ns31192949.ip-51-91-73.eu/html5client/5c28ecb6f58cf3e3db2dd3eda277c2d36391fc0b.js?meteor_js_resource=true:121:290362

**Comment by matiasilva** [comment]
Hi, thanks for posting. Support requests are better handled in https://groups.google.com/forum/#!forum/bigbluebutton-setup.
