### ISSUE TITLE
Deleting current presentation should auto-select default.pdf

### ISSUE THREAD

**Issue by ffdixon** [bigbluebutton/bigbluebutton#9986]
**Describe the bug**
When a user deletes the current presentation, the presentation area in BigBlueButton goes blank.  It's not clear to the user they need to select another presentation after deleting the current presentation.

**To Reproduce**
1. Go to https://test.bigbluebutton.org/
2. Upload a new presentation
3. Delete it (and then click 'Confirm') 

**Expected behavior**
Revert back to default presentation

**Actual behavior**
Presentation area goes blank

**Screenshots**
![image](https://user-images.githubusercontent.com/290351/86493795-db1eb200-bd40-11ea-9e2b-9bdfc17fd2ca.png)

**BBB version (optional):**
2.2.19

**Comment by ravi-ct** [comment]
In a way, I like how it behaves in 2.2.19. An unintended consequence of this behaviour is that now we have a way to make all viewers go back to bigger webcam views due to the absence of the presentation as soon as the presentation is done with.

**Comment by Jossef-767** [comment]
That's right, right now, it's the only way to control the enlargement of the webcams area.

**Comment by matiasilva** [comment]
@Jossef-767  you could minimize the presentation, no?

**Comment by daminebenq** [comment]
what we should have is that we should add an automatic selection of default presentation onClick on both of (trash-icon + modal confirmation button)
