### ISSUE TITLE
WebCamera is not Working Fine Showing Error like "1020 media cloud not reach the server server" 

### ISSUE THREAD

**Issue by janardna** [bigbluebutton/bigbluebutton#9987]
Hi, 
I have installed big blue button using bbb-install.sh, the app is working fine, after that 
 I got some Issue on WebCamera, When I shared My Web camera I got Error Like "1020 Media Cloud not Reach The server"
 I am having  Ec2 Instance Ubuntu16  and i opened ports 22,80,443,16384-65535  and i am not Running behind on NAT.
 please let me know what i missed

**Comment by basisbit** [comment]
For support requests, please use the [forum / mailing list](https://groups.google.com/forum/#!forum/bigbluebutton-setup). This issue tracker here is only for BBB development related issues. Sorry.
