### ISSUE TITLE
getting errors about recordandplayback.rb and rap_process_worker after a while

### ISSUE THREAD

**Issue by ArmanEsf** [bigbluebutton/bigbluebutton#9988]
**Describe the bug**
Hi everybody, i setup a BBB server about a month ago and everything was fine until i upgraded from 2.217 version to 2.2.19 then i had a problem with voice and recordings, it turns out because ffmpeg takes too long time to edit and publish the video(so i think the voice disconnecting problem was due to high CPU and RAM usage of ffmpeg) and now i'm just dealing with it! If anybody else having this issue i would be glad to know how you fixed it.

but today i have more rooms and participants (about 8 and 90), suddenly nginx returned 404 error to all the clients and i couldn't access the panel even!
**What i did for tshoot :**
`bbb-conf --check` returns no error.
`bbb-conf --status` says everything is working and on.

but still can't login and getting 404 error, so i restarted service with `bbb-conf --restart` it ends with 0 potential warnings but after that could not login and 404 error still there, and also nginx says everything ok no error in logs.
then i decided to reboot the server after booting up and auto starting services everything back to normal and ok, so i told my clients to start again rooms and beside that run the `bbb-conf --watch`  to see whats gonna happen and after a while i get these errors :

**-- "ERRORS found in /var/log/bigbluebutton/*" --**
`/var/log/bigbluebutton/bbb-rap-worker.log.1:E, [2020-07-01T13:54:02.192985 #21311] ERROR -- : SIGTERM
/var/log/bigbluebutton/bbb-rap-worker.log.1:E, [2020-07-01T13:54:02.194397 #21311] ERROR -- : /usr/local/bigbluebutton/core/lib/recordandplayback.rb:124:in 'each_line'
/var/log/bigbluebutton/bbb-rap-worker.log.1:E, [2020-07-01T13:54:02.194468 #21311] ERROR -- : /usr/local/bigbluebutton/core/lib/recordandplayback.rb:124:in 'block in exec_ret'
/var/log/bigbluebutton/bbb-rap-worker.log.1:E, [2020-07-01T13:54:02.194530 #21311] ERROR -- : /usr/local/bigbluebutton/core/lib/recordandplayback.rb:123:in 'popen'
/var/log/bigbluebutton/bbb-rap-worker.log.1:E, [2020-07-01T13:54:02.194591 #21311] ERROR -- :/usr/local/bigbluebutton/core/lib/recordandplayback.rb:123:in 'exec_ret'
/var/log/bigbluebutton/bbb-rap-worker.log.1:E, [2020-07-01T13:54:02.194628 #21311] ERROR -- :/usr/local/bigbluebutton/core/scripts/rap-process-worker.rb:80:in 'block (2 levels) in process_archived_meetings'
/var/log/bigbluebutton/bbb-rap-worker.log.1:E, [2020-07-01T13:54:02.194819 #21311] ERROR -- :/usr/local/bigbluebutton/core/scripts/rap-process-worker.rb:56:in 'each'
/var/log/bigbluebutton/bbb-rap-worker.log.1:E, [2020-07-01T13:54:02.194852 #21311] ERROR -- : /usr/local/bigbluebutton/core/scripts/rap-process-worker.rb:56:in 'block in process_archived_meetings'
/var/log/bigbluebutton/bbb-rap-worker.log.1:E, [2020-07-01T13:54:02.194882 #21311] ERROR -- : /usr/local/bigbluebutton/core/scripts/rap-process-worker.rb:30:in 'each'
/var/log/bigbluebutton/bbb-rap-worker.log.1:E, [2020-07-01T13:54:02.194911 #21311] ERROR -- : /usr/local/bigbluebutton/core/scripts/rap-process-worker.rb:30:in 'process_archived_meetings'
/var/log/bigbluebutton/bbb-rap-worker.log.1:E, [2020-07-01T13:54:02.194940 #21311] ERROR -- : /usr/local/bigbluebutton/core/scripts/rap-process-worker.rb:155:in '<main>'
/var/log/bigbluebutton/bbb-rap-worker.log.1:E, [2020-07-05T06:42:45.111337 #24237] ERROR -- : SIGTERM
/var/log/bigbluebutton/bbb-rap-worker.log.1:E, [2020-07-05T06:42:45.112378 #24237] ERROR -- : /usr/local/bigbluebutton/core/lib/recordandplayback.rb:124:in 'each_line'
/var/log/bigbluebutton/bbb-rap-worker.log.1:E, [2020-07-05T06:42:45.112462 #24237] ERROR -- : /usr/local/bigbluebutton/core/lib/recordandplayback.rb:124:in 'block in exec_ret'
/var/log/bigbluebutton/bbb-rap-worker.log.1:E, [2020-07-05T06:42:45.112538 #24237] ERROR -- : /usr/local/bigbluebutton/core/lib/recordandplayback.rb:123:in 'popen'
/var/log/bigbluebutton/bbb-rap-worker.log.1:E, [2020-07-05T06:42:45.112601 #24237] ERROR -- : /usr/local/bigbluebutton/core/lib/recordandplayback.rb:123:in 'exec_ret'
/var/log/bigbluebutton/bbb-rap-worker.log.1:E, [2020-07-05T06:42:45.112660 #24237] ERROR -- : /usr/local/bigbluebutton/core/scripts/rap-process-worker.rb:80:in 'block (2 levels) in process_archived_meetings'
/var/log/bigbluebutton/bbb-rap-worker.log.1:E, [2020-07-05T06:42:45.112719 #24237] ERROR -- : /usr/local/bigbluebutton/core/scripts/rap-process-worker.rb:56:in 'each'
/var/log/bigbluebutton/bbb-rap-worker.log.1:E, [2020-07-05T06:42:45.112839 #24237] ERROR -- : /usr/local/bigbluebutton/core/scripts/rap-process-worker.rb:56:in 'block in process_archived_meetings'
/var/log/bigbluebutton/bbb-rap-worker.log.1:E, [2020-07-05T06:42:45.112910 #24237] ERROR -- : /usr/local/bigbluebutton/core/scripts/rap-process-worker.rb:30:in 'each'
/var/log/bigbluebutton/bbb-rap-worker.log.1:E, [2020-07-05T06:42:45.112971 #24237] ERROR -- : /usr/local/bigbluebutton/core/scripts/rap-process-worker.rb:30:in 'process_archived_meetings'
/var/log/bigbluebutton/bbb-rap-worker.log.1:E, [2020-07-05T06:42:45.113051 #24237] ERROR -- : /usr/local/bigbluebutton/core/scripts/rap-process-worker.rb:155:in '<main>'`

`/var/log/bigbluebutton/bbb-web.2020-06-22.log:2020-06-22T11:11:17.820-04:00 ERROR StackTrace - Full Stack Trace:
/var/log/bigbluebutton/bbb-web.2020-06-22.log:2020-06-22T11:11:17.824-04:00 ERROR StackTrace - Full Stack Trace:
/var/log/bigbluebutton/bbb-web.2020-06-22.log:2020-06-22T11:11:17.825-04:00 ERROR StackTrace - Full Stack Trace:
/var/log/bigbluebutton/bbb-web.2020-06-22.log:2020-06-22T11:11:17.831-04:00 ERROR StackTrace - Full Stack Trace:`

*(btw i replaced the ` with ' for the code style)*

and also have a ton o lines in `bbb-conf --debug` i don't know if it includes anything sensitive and should i share it or not and i can't check the whole lines because of this: 
`bbb-conf --debug | wc -l :
17460`
so if is necessary and i can post it, tell me please ;)

**Additional context**
i'm not sure about this but if there is a possibility that these errors happened for a lack of hardware?
i have hardware more than minimum requirements but with that number of rooms and clients i get the 80-98% of CPU usage and 4.7 avg of RAM usage and 80% classes freeze and nobody couldn't do anything!

Thanks in advance i really appreciate any ideas and helps ❤️

**Comment by basisbit** [comment]
For support requests, please use the [forum / mailing list](https://groups.google.com/forum/#!forum/bigbluebutton-setup). This issue tracker here is only for BBB development related issues. Sorry.

By the way, anything above 60% to 80% in average CPU usage will result in bad user experience. If you use a virtual server, replace it by a dedicated server with plenty of CPU performance. If necessary, use Scalelite to spread the meetings on a couple of different servers to support more concurrent sessions.
