### ISSUE TITLE
500 & null pointer exception for the first time API call

### ISSUE THREAD

**Issue by Eternosoft** [bigbluebutton/bigbluebutton#9989]
while triggering the create API call it throws null point exception for first time and while calling it again it responds success message with the meeting details.

**First Time call:**
![image](https://user-images.githubusercontent.com/57860872/86567346-dc422000-bf88-11ea-99c4-e96b00ddd2b3.png)
![image](https://user-images.githubusercontent.com/57860872/86567389-ec59ff80-bf88-11ea-8e1e-6f0fd78c28b2.png)

**Second Time:**
I'm getting success message
![image](https://user-images.githubusercontent.com/57860872/86567531-27f4c980-bf89-11ea-873d-3c8a3efabfef.png)

**bbb-conf --check value:**
BigBlueButton Server 2.2.19 (2029)
                    Kernel version: 4.4.0-1109-aws
                      Distribution: Ubuntu 16.04.6 LTS (64-bit)
                            Memory: 7814 MB
                         CPU cores: 4

/usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties (bbb-web)
       bigbluebutton.web.serverURL: https://bbb.eternosoft.in
                defaultGuestPolicy: ALWAYS_ACCEPT
                 svgImagesRequired: true

/etc/nginx/sites-available/bigbluebutton (nginx)
                       server name: bbb.eternosoft.in
                              port: 80, [::]:80
                              port: 443 ssl
                    bbb-client dir: /var/www/bigbluebutton

/var/www/bigbluebutton/client/conf/config.xml (bbb-client)
                Port test (tunnel): rtmp://bbb.eternosoft.in
                              red5: bbb.eternosoft.in
              useWebrtcIfAvailable: true

/opt/freeswitch/etc/freeswitch/vars.xml (FreeSWITCH)
                       local_ip_v4: 172.31.28.95
                   external_rtp_ip: 13.234.132.204
                   external_sip_ip: 13.234.132.204

/opt/freeswitch/etc/freeswitch/sip_profiles/external.xml (FreeSWITCH)
                        ext-rtp-ip: $${external_rtp_ip}
                        ext-sip-ip: $${external_sip_ip}
                        ws-binding: :5066
                       wss-binding: 13.234.132.204:7443

/usr/local/bigbluebutton/core/scripts/bigbluebutton.yml (record and playback)
                     playback_host: bbb.eternosoft.in
                 playback_protocol: https
                            ffmpeg: 4.2.2-1bbb1~ubuntu16.04

/etc/bigbluebutton/nginx/sip.nginx (sip.nginx)
                        proxy_pass: 13.234.132.204

/usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml (Kurento SFU)
                        kurento.ip: 13.234.132.204
                       kurento.url: ws://127.0.0.1:8888/kurento
                    kurento.sip_ip: 172.31.28.95
                    localIpAddress: 172.31.28.95
               recordScreenSharing: true
                     recordWebcams: true
                  codec_video_main: VP8
               codec_video_content: VP8

/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml (HTML5 client)
                             build: 960
                        kurentoUrl: wss://bbb.eternosoft.in/bbb-webrtc-sfu
                  enableListenOnly: true

# Potential problems described below
# The following properties in /usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties have no value:
#     defaultWelcomeMessage
defaultWelcomeMessageFooter
# IP does not match:
#                           IP from ifconfig: 172.31.28.95
#   /etc/nginx/sites-available/bigbluebutton: bbb.eternosoft.in
# Warning: API URL IPs do not match host:
#
#                                IP from ifconfig: 172.31.28.95
#  /var/lib/tomcat7/demo/bbb_api_conf.jsp: bbb.eternosoft.in

# Warning: The setting of 13.234.132.204 for proxy_pass in
#
#    /etc/bigbluebutton/nginx/sip.nginx
#
# does not match the local IP address (172.31.28.95).
# (This is OK if you've manually changed the values)

# Warning: The API demos are installed and accessible from:
#
#    https://bbb.eternosoft.in
#
# and
#
#    https://bbb.eternosoft.in/demo/demo1.jsp
#
# These API demos allow anyone to access your server without authentication
# to create/manage meetings and recordings. They are for testing purposes only.
# If you are running a production system, remove them by running:
#
#    apt-get purge bbb-demo

wget: missing URL
Usage: wget [OPTION]... [URL]...

Try `wget --help' for more options.
# Error: Unable to reach default URL for presentation
#
#
#
# Check value for beans.presentationService.defaultUploadedPresentation in
#   /usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties

**bbb-conf --status value:**
nginx —————————————————► [✔ - active]
freeswitch ————————————► [✔ - active]
redis-server ——————————► [✔ - active]
bbb-apps-akka —————————► [✔ - active]
bbb-transcode-akka ————► [✔ - active]
bbb-fsesl-akka ————————► [✔ - active]
red5 ——————————————————► [✔ - active]
tomcat7 ———————————————► [✔ - active]
mongod ————————————————► [✔ - active]
bbb-html5 —————————————► [✔ - active]
bbb-webrtc-sfu ————————► [✔ - active]
kurento-media-server ——► [✔ - active]
etherpad ——————————————► [✔ - active]
bbb-web ———————————————► [✔ - active]

Thanks in Advance

**Comment by matiasilva** [comment]
Hi, for development help please use https://groups.google.com/forum/#!forum/bigbluebutton-dev. Also, avoid pasting large amounts of text here and use pastebin or something of the sort.
