### ISSUE TITLE
I want to install version 2.2.2 of bigbluebutton now. Is there a way? Thank you.

### ISSUE THREAD

**Issue by z-j-j** [bigbluebutton/bigbluebutton#9990]
I want to install version 2.2.2 of bigbluebutton now. Is there a way? Thank you.

**Comment by matiasilva** [comment]
Hi, please have a browse in the issue tracker before posting an issue. There is a way to downgrade available in #9508 but be aware that 2.2.2 is significantly behind 2.2.19 (the current version).
