### ISSUE TITLE
Is it possible to get chat and survey information

### ISSUE THREAD

**Issue by burakguder** [bigbluebutton/bigbluebutton#9991]
How can I save chat and survey information to the external server ?

**Comment by matiasilva** [comment]
Poll information isn't possible natively nor is chat (though you can extract these from logs). You could have some luck parsing the events.xml file with the bbb-events ruby gem (in this repository). Also, keep in mind future questions like these should go in the developer group forum: https://groups.google.com/forum/#!forum/bigbluebutton-dev.

**Comment by basisbit** [comment]
For such questions, please use the mailing list mentioned above. For Feature requests, please stick to the issue template.
