### ISSUE TITLE
Couldn't able to install BBB from install.sh

### ISSUE THREAD

**Issue by smohankrishna** [bigbluebutton/bigbluebutton#9993]
**Describe the bug**

**Installation type**
Did you install manually or did you use the BBB-install script?
BBB script

**Firewall and IP address type**
Is your server behind a NAT or firewall? Does your BBB server have its own IPv4 addres?
BBB has its own Ip

**Console output**
Please include the full console output from the install.
E: Sub-process /usr/bin/dpkg returned an error code (1)
bash: line 1145: /etc/bigbluebutton/bbb-conf/apply-config.sh: No such file or directory
chmod: cannot access '/etc/bigbluebutton/bbb-conf/apply-config.sh': No such file or directory
 BigBlueButton does not appear to be installed.  Could not
locate:
/usr/share/red5/webapps/bigbluebutton/WEB-INF/red5-web.xml
BigBlueButton does not appear to be installed.  Could not
 locate:
 /usr/share/red5/webapps/bigbluebutton/WEB-INF/red5-web.xml

**Additional context**

**Comment by ffdixon** [comment]
Did you get errors earlier in the install?  What is the output of `dpkg -l | grep bbb` and `sudo apt-get install -f`?

**Comment by smohankrishna** [comment]
HI,

Am getting the error as

root@mavex-bbb:/home/AzureUser# dpkg -l | grep bbb and sudo apt-get install
--file
grep: option '--file' requires an argument
Usage: grep [OPTION]... PATTERN [FILE]...

Try 'grep --help' for more information.

**Comment by matiasilva** [comment]
Type those commands in separately :-) So first  `dpkg -l | grep bbb` then copy paste the output here. Then run `sudo apt-get install -f` and do the same.
