### ISSUE TITLE
how disable popup when begin a room?

### ISSUE THREAD

**Issue by MostafaHabibi** [bigbluebutton/bigbluebutton#9997]
hi
when i enter a room, there are some popup like test microphone or when choose webcam show a popup for choose quality.how can I disable these popups and set default for these popups?

popups like this 
<img width="1280" alt="Screen Shot 1399-04-17 at 1 54 45 PM" src="https://user-images.githubusercontent.com/66715212/86759193-9dc86600-c059-11ea-850b-59455507ac28.png">
<img width="1280" alt="Screen Shot 1399-04-17 at 1 54 24 PM" src="https://user-images.githubusercontent.com/66715212/86759235-a3be4700-c059-11ea-8f16-dcd5ad55e279.png">

**Comment by somuelle-tmt** [comment]
How do you know which cameras your participants have connected to their computers?

**Comment by basisbit** [comment]
For support requests, please use the [forum / mailing list](https://groups.google.com/forum/#!forum/bigbluebutton-setup). This issue tracker here is only for BBB development related issues. Sorry.

You can find answers to your question at https://docs.bigbluebutton.org

**Comment by matiasilva** [comment]
Also, please read the documentation!

**Comment by MostafaHabibi** [comment]
> Also, please read the documentation!

my dear friend,
i read the documentation but i can't find where is answer to my question in the document.if you know please tell me.thanks

**Comment by matiasilva** [comment]
https://docs.bigbluebutton.org/2.2/customize.html#application-parameters
